### ISSUE TITLE
NSIS BoringInstaller install for "all users" immediately jumps to finished page before installation is complete

### ISSUE THREAD

**Issue by rainyday** [electron-userland/electron-builder#1000]
* **Version**:  10.7.0

* **Target**: Win32 x64

When using the BoringInstaller mode for NSIS, selecting install for all users will cause the installer to, after asking for elevation to jump immediately to the finished page without actually appearing to run any install steps whatsoever. Installation will eventually be completed if the user waits on the finished screen until the installation has finished. If "finish" is clicked before this the installation will silently be aborted with whatever was partially installed left on the hard disk.

Running installer as administrator or installing "only for me" works as expected.

**Comment by develar** [comment]
Duplicates #767
