### ISSUE TITLE
Linux AppImage target doesn't reuse the launcher icon

### ISSUE THREAD

**Issue by grigio** [electron-userland/electron-builder#1003]
* **Version**: 10.7.0

* **Target**: Linux AppImage

When the application is open it doesn't reuse the launcher icon but it uses a new default one.

**The bug isn't present on target "Linux deb"**

![el-appimagebug](https://cloud.githubusercontent.com/assets/8074/21147128/3b7511fe-c154-11e6-90ab-e21eea3c50cf.png)

**Comment by probonopd** [comment]
Does this also happen when you launch the AppImage through the menu (e.g., by using the optional `appimaged` daemon for desktop integration)?

**Comment by grigio** [comment]
I installed `appimaged` and the result is the same, it seems it is started but it doesn't finish the installation for some reasons.. :(
```
❯ systemctl --user status appimaged
● appimaged.service - AppImage daemon
   Loaded: loaded (/usr/lib/systemd/user/appimaged.service; enabled; vendor pres
   Active: active (running) since mer 2016-12-14 23:05:35 CET; 18min ago
 Main PID: 25259 (appimaged)
   CGroup: /user.slice/user-1000.slice/user@1000.service/appimaged.service
           └─25259 /usr/bin/appimaged

dic 14 23:05:35 mibook systemd[3011]: Started AppImage daemon.
dic 14 23:05:35 mibook appimaged[25259]: _________________________
dic 14 23:05:35 mibook appimaged[25259]: -> REGISTER /home/mibook/.local/bin/app
dic 14 23:05:35 mibook appimaged[25259]: squashfs based type 2 AppImage
dic 14 23:05:35 mibook appimaged[25259]: Got root desktop: appimaged.desktop
dic 14 23:05:35 mibook appimaged[25259]: Installing desktop file
lines 1-13/13 (END)

```

**Comment by probonopd** [comment]
What do you mean by "it doesn't finish the installation"? Does it show up in the menu? Keep in mind that you may have to log out and log in to your desktop following appimaged installation to make it work.

**Comment by grigio** [comment]
> "it doesn't finish the installation"?
Probably not the last message is "Installing desktop file"

> Does it show up in the menu?
No

I logged out/in nothing change

**Comment by khurana3192** [comment]
This issue is there for me as well. My .AppImage file has my brand icon. However, when I open it, the sidebar uses the default ubuntu icon

**Comment by develar** [comment]
@khurana3192 Your issue is different. Please see https://github.com/electron-userland/electron-builder/issues/748#issuecomment-246580769
