### ISSUE TITLE
Using auto updater behind proxy

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1004]
* **Version**:  0.7.0 (electron udpater)

* **Target**:  nsis

Is there some way to use auto updater behind a proxy?

In every other http request I set `options = { ... 
    agent: myProxyAgent
}`

but I didn't find a way to pass this to the auto updater.

Any suggestion? If not then would you accept a PR if I implemented the possiblity to provide a specific agent to the Auto updater?

Thanks

**Comment by develar** [comment]
Please see #959 We should not use NodeJS HTTP API, but hromium electron API. If you can make PR — great, it will be very cool.

**Comment by maczikasz** [comment]
okay, I'll put creating the PR in our product backlog and will do it hopefully soon, thanks.

**Comment by develar** [comment]
Duplicates #959
