### ISSUE TITLE
Files changed after pack / build

### ISSUE THREAD

**Issue by bhajneet** [electron-userland/electron-builder#1005]
* **Version**: 7.14.1

* **Target**: mac x64

After packing / building, the golang executable under App.app/Contents/Resources/app/ is changed. I don't know in which way, but if I replace the executable manually the program works fine.

Else on run this child will exit immediately with code null and signal SIGKILL. I don't know what is being done in the build process to affect this file, they are also slightly different sizes when compared.

Weirdest thing is that it was working just a while ago, I have not updated or changed anything of significance. I'm not sure why / how it happened.

I have a signing certificate, I have tried exporting CSC_NAME, I have made sure the paths are correct. I finally narrowed it down to this golang executable (which starts a server; not a new feature, used to work before). Trying to run the golang executable on it's own fails immediately. So this is what causes the child spawn to exit immediately. However I don't understand the SIGKILL signal being sent, and I don't know what's in the golang executable that has changed. There are no error outputs.

**Comment by develar** [comment]
Please attach sample project. Only file permissions are fixed, file content copied as is.

Do you use antivirus?

**Comment by bhajneet** [comment]
Here is the app attached. This is the incorrect one. Also attached is shabadOS a golang executable. This should replace Shabad OS.app/Contents/Resources/app/main

https://drive.google.com/open?id=0B3fO8DyHx5LRcjJpeU5jVTJtVUE

You'll note they are both slightly different sizes. With the electron bundled one being just a bit larger. Permissions are the same on both.

I normally re-name shabadOS to main in the app folder before packing/building. That process hasn't changed.

There is no antivirus on this machine.

**Comment by bhajneet** [comment]
Hello, I've done a little more tinkering. Electron Packager works. However, I haven't checked how to create the dmg, sign the electron packager version, or what is inside the zip that electron builder makes. If I can figure that out I can go forward with my mac distribution albeit with some more manual work. How does electron builder interact with electron packager btw? It's odd that somehow it stops working. I also made sure to update all my packages to the newest version. It made no difference. I'm also wondering again and again if it could be something with our files that affects how they're copied over, but that too is proving difficult.

**Comment by develar** [comment]
@bhajneet Sorry for delay, I will investigate your issue today.

**Comment by develar** [comment]
@bhajneet Why do you don't use asar?

**Comment by develar** [comment]
I don't see golang executable in the `Shabad OS (Working)`. Is it possible to provide project sources, so, I can just build it to investigate (you can send me direct email)?

**Comment by develar** [comment]
I suggest you to use asar packaging and extraResources/extraFiles to unpack externally available executables. Feel free to send me project / ask if you cannot enable asar packaging due to some troubles.

**Comment by develar** [comment]
I cannot reproduce — `go` executable correctly copied (using asar packaging and `"extraResources": "go",` (path relative to the app project app directory)).
