### ISSUE TITLE
ASAR  No such file or directory - Running Applescript

### ISSUE THREAD

**Issue by Jonovono** [electron-userland/electron-builder#1008]
* **10.8.0**: 

* **1.4.7**: 

I am trying to use this library: https://github.com/mikaelbr/node-osascript

Every time I try to run Applescript from a file I get the error:

    Error: osascript: /Users/jordan/Desktop/plusaroo/dist/mac/Plusaroo.app/Contents/Resources/app.asar/app/refreshSpotify.applescript: No such file or directory

Any ideas?

**Comment by develar** [comment]
You need to add osascript to [asarUnpack](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-asarUnpack).

**Comment by Jonovono** [comment]
@develar I have tried that and it still happens. I can see the file in my app.asar.unpacked/app/refreshSpotify.applescript but still getting the same error message.

**Comment by develar** [comment]
You need to modify your code to call this script. For example, please see https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/commit/e3c308dc1cb24a5c85864023f88474e95ddbd8f0#diff-779ba29ca31786b5ba28f320e69586b2R27
