### ISSUE TITLE
update download uses lot of cpu, and may lost connection, and error not catchable

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#1010]
* **Version**: 10.8.1

* **Target**: win32

1. when downloading updates, it uses lots of CPU.
[Imgur](http://i.imgur.com/bmUjBZF.png)

(when not in update, it only use < 10%).

2. update may lost connection and get a incomplete package, then throw SHA2 checksum error. my service is over https, and a complete package is always correct. but they often download a incomplete one. there is apart of my nginx log:
[Imgur](http://i.imgur.com/HzMkid9.png)

my app total length is 35925496, but he failed 2 times before got a complete one.
I'm sure he is not close my app manually, he's waiting for update, and got a sha2 checksum error.

his network to my server works well, **when using wget or browser, download will always complete.**

3. the sha2 checksum error is not catchable.
I've listened `autoUpdater.on("error")` event, but still throws a error window.

[Imgur](http://i.imgur.com/DICT7y1.png)

**Comment by develar** [comment]
We will soon use chrome API to download instead of node. Please see #1024

**Comment by 0x30** [comment]
I have the same issue. I think it's because sha2 mismatch throws an exception from within a promise [here](https://github.com/electron-userland/electron-builder/blob/569dd8bb4e3e073e6bbcfda70c2fa34571ec5a41/nsis-auto-updater/src/electronHttpExecutor.ts#L97-L102). Wouldn't it make more sense to use the error callback?

**Comment by develar** [comment]
Fixed in electron-auto-updater 0.8.2
