### ISSUE TITLE
Stub Executables missing in Squirrel.Windows 1.5.1

### ISSUE THREAD

**Issue by morloy** [electron-userland/electron-builder#1011]
* **Version**:  10.8.1

* **Target**: Windows

Squirrel.Windows has introduced [Stub Executables  in version 1.5](https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.5.0).
Apparently, these are not built by electron-builder which makes all shortcuts unusable on Windows.

**Comment by bnnahmani** [comment]
I confirm, all shortuts are unusable on Windows

**Comment by rgl** [comment]
They are broken here too.

**Comment by rgl** [comment]
seems to be a bug with electron-builder, more exactly with the version that is pulled from [electron-builder-binaries](https://github.com/electron-userland/electron-builder-binaries/issues/1)

**Comment by develar** [comment]
Fixed, release will be in 20 minutes.
