### ISSUE TITLE
appx - can't build 32bit on 64bit machine

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1012]
* **Version**: latest

* **Target**: appx ia32

Hey @develar, it seems like electron-builder is always using the machine's arch when building appx:
https://github.com/electron-userland/electron-builder/blob/4faa3fb68709304cc6b75fb6d8b77134724fd3a9/src/targets/appx.ts#L66

Seems like `--ia32` is ignored. When I look into my ia32 manifest it says `ProcessorArchitecture="x64"
`. The appx filesize is different, though (~67mb x64, ~57mb x86).

Is the manifest wrong? Am I wrong?

**Comment by develar** [comment]
I don't know how to build AppX for ia32. Maybe we should just use 32bit appx to build 32bit appx. To investigate.

**Comment by black-snow** [comment]
I do have two `makeappx.exe` versions:

* C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe
* C:\Program Files (x86)\Windows Kits\10\bin\x86\makeappx.exe

Maybe it is actually enought to use the right one. I wonder why my appx files aren't the same in size. Is the electron stuff 32 bit but only the appx is not? Would be an easy fix then, I guess.

**Comment by develar** [comment]
>  Is the electron stuff 32 bit but only the appx is not? 

I guess so.

**Comment by black-snow** [comment]
I just created the appx manually with the x86 VS CMD and installed it. Windows stored it under `C:\Program Files\WindowsApps\appname-x86-someotherchars` and it ran fine. Guess that'll do.
I might have access to a 32bit Win10 machine on wednesday to verify.

@develar What's electron-builder using for makeappx? I saw something with bintray. Does it download a makeappx.exe from bintray?

**Comment by develar** [comment]
> Does it download a makeappx.exe from bintray?

Yes, and 32bit is available. Please see https://github.com/electron-userland/electron-builder-binaries/tree/master/winCodeSign package (i.e. https://github.com/electron-userland/electron-builder-binaries/tree/master/winCodeSign/windows-10/ia32) So, fix will be only to replace `process.arch` to corresponding value.

**Comment by black-snow** [comment]
Wow, that'd be a quick fix ;)

**Comment by black-snow** [comment]
Well damn, crashed:

> TypeError: Path must be a string. Received 0
>  at assertPath (path.js:7:11)
>  at Object.join (...)
>  at .../electron-builder/src/targets/appx.ts:66:22
> ...
> at AppXTarget.build (... electron-builder/out/targets/appx.js:123:11)
> at postAsyncTasks.push.default.map.it (... src/platformPackager.ts:163:85)
> ...

Also arch is wrong in appx. Gonna fix that.

**Comment by black-snow** [comment]
@develar please review the PR. It works for me locally but I edited the generated js - I'm not so sure about the ts source.
