### ISSUE TITLE
How to build on windows platform with autoUpdates.

### ISSUE THREAD

**Issue by Johnz86** [electron-userland/electron-builder#1013]
* **Version**: "electron-builder": "^10.8.0"

* **Target**: windows platform and msi package.

This is my build profile.
```
  "build": {
    "appId": "com.siemens.skboffline",
    "squirrelWindows": {
      "remoteReleases": "http://localhost:9000/dist/version/",
      "msi": true
    },
    "win": {
      "certificateFile": "./certs/my_signing_key.pfx",
      "certificatePassword": ""
    }
  },
```
The msi packages are not build. There are no RELEASES files and nuGet packages compared with older versions. I read outdated tutorials like https://blog.avocode.com/blog/get-that-damn-windows-auto-update-working-on-electron.

Is there some reasonable example for windows build and update with current electron-builder?
How can I build msi package?

**Comment by develar** [comment]
NSIS is the default target now. Please see https://github.com/electron-userland/electron-builder/releases/tag/v8.0.0

MSI — please see https://github.com/electron-userland/electron-builder/issues/723

**Comment by Johnz86** [comment]
Is there some description how the update with NCIS should work on server side?  With squirrel I could just specify setFeedUrl and return a RELEASES file. 

In your response the release note specifies that I should not setFeed on Windows and it should produce some app-update.yaml file. I do not see any such file. Is that because I have not specified any .build.publish information?

**Comment by develar** [comment]
> any .build.publish information?

Yes. Please set to `generic`.

> Is there some description how the update with NSIS should work on server side? 

https://github.com/ArekSredzki/electron-release-server/issues/87#issuecomment-261600371

**Comment by Daymannovaes** [comment]
Hey @develar how auto-updater works with NSIS, it isn't using Squirrel anymore? I found the docs a little confusing. I'll still need to implement the backend using `Nuts`, for example, as mentioned in the README?

Thanks!

**Comment by Daymannovaes** [comment]
Sorry, just found the answer here: https://github.com/electron-userland/electron-builder/issues/529

The docs is a bit outdatted, wouldn't be good to update it?

**Comment by develar** [comment]
> wouldn't be good to update it?

@Daymannovaes Do you mean project readme? Please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by Daymannovaes** [comment]
I saw it there, but the readme says `You also need to deploy your releases to a server. Consider using Nuts (uses GitHub as a backend to store the assets), Electron Release Server or Squirrel Updates Server.` which can lead to confusion. When I read first time I ask myself "so should I or shouldn't I implement the server with Squirrel?
