### ISSUE TITLE
Error in TravisCI

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#1014]
* **Version**: 
10.8.1

* **Target**: 
Linux

For some reason `install-app-deps` script fails on linux. It's working fine on OSX. Here is the logs - 
linux - https://travis-ci.org/zulip/zulip-electron/jobs/184270384
Config for linux - 
```json
{
  "sudo": "required",
  "os": "linux",
  "language": "node_js",
  "node_js": "6",
  "before_install": [
    "npm install -g gulp",
    "npm install"
  ],
  "cache": {
    "directories": [
      "node_modules",
      "app/node_modules",
      "$HOME/.electron",
      "$HOME/.cache"
    ]
  },
  "script": [
    "npm run travis"
  ],
  "group": "stable",
  "dist": "precise"
}
```
OSX - https://travis-ci.org/zulip/zulip-electron/jobs/184270383

Build - https://travis-ci.org/zulip/zulip-electron/builds/184270382

Travis build script - [travis-build-test.sh](https://github.com/zulip/zulip-electron/blob/dev/scripts/travis-build-test.sh)

@develar could you please tell me what I'm doing wrong here?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#travis-linux Please use Trusty  — https://docs.travis-ci.com/user/trusty-ci-environment/#Using-Trusty

**Comment by akashnimare** [comment]
@develar thanks a lot 💃
