### ISSUE TITLE
Sign app with multiple certificates 

### ISSUE THREAD

**Issue by symbyte** [electron-userland/electron-builder#1018]
* **Version**:6.3.0 

* **Target**: Mac, Windows

I am currently signing both our Mac and Windows builds using the CSC_LINK env variables. The time has come to renew our certificate so I have switched to signing with the renewed certificate. 

Auto updates for the Windows build recognize the new signing identity fine, but the Mac build rejects it as invalid. I have heard that this can be fixed by signing the app with both the old and new certificates. Is there any way to have electron builder sign with more than one identity with CSC_LINK? If it does not exist, is it possible to add?

**Comment by develar** [comment]
cc @sethlu 

It seems, it is not possible: codesign docs:

> When signing, causes codesign to replace any existing signature
             on the path(s) given. Without this option, existing signatures
             will not be replaced, and the signing operation fails.

**Comment by develar** [comment]
If you will provide link to how it is possible, it will be implemented.

**Comment by djpereira** [comment]
@develar when you can call `signtool.exe` multiple times and pass the /as parameter to append a signature.

> /as | Appends this signature. If no primary signature is present, this signature is made the primary signature.

See https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool
