### ISSUE TITLE
Updater: NSIS quitAndInstall() - Application closes but does not restart (old bug resurfaced?)

### ISSUE THREAD

**Issue by Zamiell** [electron-userland/electron-builder#1019]
* **Operating system**: Windows 7 Professional
* **electron-builder version**: 10.8.1
* **Node version**: 6.9.1
* **Npm version**: 3.10.8
* **Build target**: Only Windows (NSIS)
* **Main package.json**:

```
{
  "name": "RacingPlus",
  "description": "A racing mod for The Binding of Isaac: Afterbirth+.",
  "scripts": {
    "start": "electron ./app",
    "postinstall": "install-app-deps",
    "pack": "build --dir",
    "dist": "build",
    "dist2": "build --publish always"
  },
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "win": {},
    "publish": {
      "provider": "github"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Zamiell/isaac-racing-client.git"
  },
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/Zamiell/isaac-racing-client/issues"
  },
  "homepage": "https://isaacracing.net",
  "devDependencies": {
    "electron": "^1.4.12",
    "electron-builder": "^10.8.1"
  }
}
``` 

* **App package.json**:
```
{
  "name": "RacingPlus",
  "productName": "Racing+",
  "main": "./main.js",
  "version": "0.0.22",
  "description": "A racing mod for The Binding of Isaac: Afterbirth+.",
  "author": "Racing+",
  "license": "GPL-3.0",
  "dependencies": {
    "electron-auto-updater": "^0.5.3",
    "electron-is-dev": "^0.1.2",
    "electron-log": "^1.2.2",
    "fs-extra": "^1.0.0",
    "keytar": "^3.0.2",
    "linkifyjs": "^2.1.3",
    "tail": "^1.2.1",
    "teeny-conf": "^1.0.1",
    "touch": "^1.0.0",
    "tracer": "^0.8.7"
  }
}
```

* **Console output of building it**:
```
Building: isaac-racing-client v0.0.24

> RacingPlus@ dist2 D:\Repositories\isaac-racing-client
> build --publish always

Rebuilding native production dependencies for arch x64
Packaging for win32 x64 using electron 1.4.12 to dist\win-unpacked
Packaging NSIS installer for arch x64
Building NSIS installer
Creating Github Publisher - owner: Zamiell, project: isaac-racing-client, version: 0.0.24
Release with tag v0.0.24 doesn't exist, creating one
Uploading RacingPlus-Setup-0.0.24.exe [====================] 100% 0.0s
Released version 0.0.24 successfully.
```

Description of Problem
-------------------------

* As you can see from my `package.json` file, I am implementing NSIS automatic updates in my app using GitHub.
* Testing on Windows 7 Professional, the application successfully updates, but it **does not automatically reopen after closing**.

Simplified code snippet to reproduce the problem:

```
const autoUpdater = require('electron-auto-updater').autoUpdater;
autoUpdater.on('update-downloaded', function(e, notes, name, date, url) {
    autoUpdater.quitAndInstall();
});
autoUpdater.checkForUpdates();
````

I found some other issues on this, but they were closed as fixed in previous versions of `electron-builder`, so maybe this bug is back now.

**Comment by Zamiell** [comment]
Also, Vladimir do you get paid to maintain electron-builder?
If not, can you please provide me a PayPal email for a donation? I would like to thank you for your work.

**Comment by develar** [comment]
> Also, Vladimir do you get paid to maintain electron-builder?

No. But if you are commercial company and some feature is important for you — you can expect that donation can help to change priority. 

> If not, can you please provide me a PayPal email for a donation?

https://github.com/electron-userland/electron-builder#donations

**Comment by develar** [comment]
@Zamiell electron-auto-updater version is outdated. Please change `"^0.5.3"` to `"^0.7.1"` 

Commit to reference — https://github.com/electron-userland/electron-builder/commit/00a8d36b7734631588347a93a58488f8e144dde1

**Comment by develar** [comment]
Please note — "Since version 8 electron-builder rebuilds only production dependencies, so, you are not forced to use two package.json structure."

**Comment by Zamiell** [comment]
Ah! Yes, this is a very silly issue - I did `ncu --upgradeAll` in the root on my repository, but I also needed to  ALSO do it in the `app` subdirectory.

I donated. Thanks for your support! Make this donation go towards delta NSIS updates and OSX NSIS updates.

**Comment by Zamiell** [comment]
Develar - Is it recommend migrating to migrate to a 1 package.json structure going forward? The docs are unclear.

**Comment by develar** [comment]
In general, 1 package.json is easier to mantain. You just need to configure `files` properly to ignore dev only files. Currently, no strict recommendation.
