### ISSUE TITLE
The command "build --linux deb tar.xz" builds for macOS DMG (and not deb package). How to build debian package only?

### ISSUE THREAD

**Issue by vineetshopo** [electron-userland/electron-builder#1021]
Hi, I am on mac OSX El Capitan version 10.11.16. Node version is 4.1.2 and npm version is 2.14.4. The build property is
```
 "build": {
   "linux" : {
     "category" : "office",
      "target" : "deb"
   }
 },
```

And the script is 

`"build" : "build"`

I am running the command 
`npm run build --linux deb tar.xz`
to make a debian package for me. But this command creates a directory dist/mac and installs a DMG package instead. What's the solution?

**Comment by develar** [comment]
`npm run build --linux deb tar.xz`

Must be `npm run build -- --linux deb tar.xz`

**Comment by develar** [comment]
https://docs.npmjs.com/cli/run-script#synopsis

**Comment by vineetshopo** [comment]
Thanks. But now its causing another issue - `Unhandled rejection Error: Exit code: ENOENT. spawn gm ENOENT. `

Then there are a lot of lines for error

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux
