### ISSUE TITLE
Application has stopped working

### ISSUE THREAD

**Issue by kushang-s** [electron-userland/electron-builder#1022]
* **Version**: ^10.4.1

* **Target**: windows nsis

I've build the application for x64 and x86 using target as nsis for windows and I get this pop up "Application has stopped working" every time the installed app is opened only on windows 7 machines (both x86 & x64). However the app works properly but this pops up every single time. Is there anything I need to specify in the build script that I might be missing? Or has this got anything to do with the nsis?

NSIS settings used are: 
```
"nsis": {
      "oneClick": true,
      "perMachine": false,
      "allowElevation": false
    }
```

Error Code is 

> 0x80000003

 which has got something to do with windows registry for 

> !define HKEY_USERS

Additional information: I was using Squirrel before switching to NSIS.

![win_7_issue](https://cloud.githubusercontent.com/assets/24606069/21261381/0bc46a04-c3b1-11e6-97ac-4365fecec51a.jpg)

**Comment by develar** [comment]
Does it work correctly on win 10? Or on clean win 7? Is it possible to provide sample project / installer?

**Comment by kushang-s** [comment]
@develar Hi, sorry I was caught in some work and could not follow up on this post. It works correctly on windows 8 and above. Also it works correctly on windows 7 irrespective of the error shown above. I've created a sample project with the same configuration as my actual one which could be found over here https://github.com/kushang-s/electronDesktopDemo
