### ISSUE TITLE
Error ITMS-90287 when trying to deploy a MAS app built with electron-builder

### ISSUE THREAD

**Issue by tleunen** [electron-userland/electron-builder#1023]
* **Version**: 10.8.1
* **Target**: MAS

I'm trying to publish a new version of my app on the Mac App Store but I'm having difficulties with Application Loader. When Apple analyses the pkg file created by Electron-Builder, I receive 2 errors:

```
ERROR ITMS-90287: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.team-identifier' in 'com.xyz.xxxyyyzzz.pkg/Payload/xxxyyyzzz.app/Contents/MacOS/xxxyyyzzz'."
ERROR ITMS-90287: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.application-identifier' in 'com.xyz.xxxyyyzzz.pkg/Payload/xxxyyyzzz.app/Contents/MacOS/xxxyyyzzz'."
```

Any reason why? I've a valid and active profisionning profile for the distribution. And I have a `build/entitlements.mas.plist` file with 
```
<key>com.apple.security.application-groups</key>
<string>123ABC.com.xyz.xxxyyyzzz</string>
```

When running `build -m` I don't have any signing warnings/errors. It takes the right certificate. So I wonder what's missing.

The value of `application-groups` is the same as the one in my provisioning profile under `com.apple.application-identifier`, and `com.apple.developer.team-identifier` contains the right 123ABC value.
And when I inspect the plist file in the .app package created by electron-builder, I'm seeing the team id under `ElectronTeamID`, and the application id under `CFBundleIdentifier`.

Any help is welcome.
Thanks.

cc @bryan-jowers

**Comment by develar** [comment]
Please file issue to https://github.com/electron-userland/electron-osx-sign/issues
