### ISSUE TITLE
life cycle handler like “uninstall” for electron app installed by macOS dmg

### ISSUE THREAD

**Issue by wangxiexe** [electron-userland/electron-builder#1025]
* **Version**: 
10.8.1

* **Target**: 
macOS

I am using electron-builder to create app which has Squirrel.Mac support

the build output is dmg and I can install the app by drag it into application folder

but I noticed the life cycle events (which works fine on windows) like "--squirrel-uninstall" "--squirrel-updated" are not issued, and so I can not add handlers for them

I need to clear some application data like password saved in keychain before the application is moved into trash, but the handler is not even called.

Is it by design or there is something else I can do ? thanks!

**Comment by develar** [comment]
> Is it by design

Yes. macOS app doesn't have uninstall procedure. Well, you can provide special script for users to uninstall your app, but it is not common practice and users will just move app to trash.

**Comment by durga083** [comment]
Hi...

I am having the same issue, like how to delete user data when dmg is moved to uninstalled.
Can any one provide inputs on this?

Thanks,
Durga.

**Comment by ApurvaB** [comment]
Did you get any solution for this problem?I have same issue

**Comment by pravin-d** [comment]
@develar Hi, I'm having the same problem with uninstall. I want to know if its possible to run uninstall from the menu item in electron app ? Or maybe you could please elaborate on uninstall scripts that you have mentioned before?

**Comment by vcombey** [comment]
Hi, I'm having the same problem with uninstall. I want to know if its possible to run uninstall from the menu item in electron app ? Or maybe you could please elaborate on uninstall scripts that you have mentioned before?
