### ISSUE TITLE
Set platform npm environment variable

### ISSUE THREAD

**Issue by lgeiger** [electron-userland/electron-builder#1027]
* **Version**:  10.8.1

* **Target**: all

[`prebuild`](https://github.com/mafintosh/prebuild/) now fully supports Electron and works great together with `electron-builder` and the `npmSkipBuildFromSource` option.

Additionally it would be great if `electron-builder` could expose the platform it builds for to a `npm` environment variable (`npm_config_platform`) during the rebuilding of native modules.

This way [`prebuild`](https://github.com/mafintosh/prebuild/) would be able to download the correct prebuilt binary for the desired target.
This would make multi platform builds with native dependencies possible.

**Comment by mmckegg** [comment]
@lgeiger I actually added support for this on my own branch but never PR'd it because it was a bit hacky.

https://github.com/mmckegg/electron-builder/tree/rebuild-for-platform

**Comment by develar** [comment]
@mmckegg Would you like to send PR?

**Comment by develar** [comment]
Will be implemented soon.

**Comment by lgeiger** [comment]
@develar Thanks for the fast response!

I just tried `v10.9.0` and it doesn't fully work yet:

```
$ npm run pack

> nteract@0.0.15 pack /Users/lukasgeiger/code/nteract
> npm install && npm run clean && npm run build && build --dir --linux

> nteract@0.0.15 postinstall /Users/lukasgeiger/code/nteract
> install-app-deps

Rebuilding native production dependencies for darwin:x64
```

I use `build --dir --linux` and it still builds for mac (`darwin:x64`). Or am I missing something.

**Comment by lgeiger** [comment]
I'm sorry, the log (`Rebuilding native production dependencies for darwin:x64` was coming from the `npm install` command.

I'll investigate further.
