### ISSUE TITLE
extraResources in single package.json structure

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#1028]
* **Version**: Latest

* **Target**: Mac

My extraResources no longer seem to be getting copied into the app executable (only tested on mac so far). 

I have the following structure:

```
dir/
  - app/
  - ui/
  - extra/file.jar
  - package.json

```
I have the following in my package.json:

```
  "build": {
    "extraResources": [
      "extra/file.jar",
      "ui/**/*"
    ],

```
But both the ui folder and the file.jar are not copied to the app binary. This used to work fine when I had 2 package.json files.

Any ideas?

**Comment by develar** [comment]
Strange. Does it work if you append `**/` to your pattern?

**Comment by atypicalprogrammer** [comment]
Prepend **/ to ui/**/* as such : **/ui/**/* ? (I don't quite understand). No this does not work.

**Comment by develar** [comment]
> **/ui/**/*

Yes.

> No this does not work.

Is it possible to provide sample app?

**Comment by atypicalprogrammer** [comment]
See: https://github.com/iotaledger/wallet

**Comment by atypicalprogrammer** [comment]
hmm this is strange, it seems to be working now.... Guess I can close the issue. Sorry to waste your time.
