### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by stefanjudis** [electron-userland/electron-builder#103]
Test coverage should be much higher... :(

- [x] test cli.js
- [x] test main index
- [x] test osx builder
- [ ] test windows builder
- [ ] set up code coverage

**Comment by havenchyk** [comment]
@stefanjudis let's define the parts of code that should be tested first of all. On the other hand, let's use istanbul for code coverage.

**Comment by stefanjudis** [comment]
>  let's define the parts of code that should be tested first of all

Well all of it.

> On the other hand, let's use istanbul for code coverage.

I'm using coveralls usually which works fine and doesn't take me much set up time.

**Comment by havenchyk** [comment]
In this case let's use coveralls.

**Comment by stefanjudis** [comment]
:bowtie:

**Comment by stefanjudis** [comment]
Only tests for windows builder are missing. :)

**Comment by develar** [comment]
>  set up code coverage

That's not easy :( My branch https://github.com/develar/electron-builder/tree/coverage but it doesn't work yet. Maybe because we test against installed module and nyc excludes node_modules by default. I have no idea. Unlikely I will find time to finish it soon, anyone is welcome to help.

**Comment by develar** [comment]
@stefanjudis I added new label `backlog` and close issue so. To keep issue list clear.
