### ISSUE TITLE
Automatically creating app shortcut in windows

### ISSUE THREAD

**Issue by adamsiwiec** [electron-userland/electron-builder#1035]
* **Version**:  10.9.3

* **Target**:  Windows

This may seem vague, but how do I automatically create a shortcut to my application using the windows squirrel installer, and where does it install my app too? I can't seem to find where the <app_name>.exe file is installed too. Please comment if I need more info/files.

**Comment by develar** [comment]
Why do you need to use squirrel? Please use default nsis target.

**Comment by loziobiz** [comment]
You have to handle squirrel events.
You can see this as a good starting point
[](https://github.com/mongodb-js/electron-squirrel-startup)

**Comment by adamsiwiec** [comment]
Thanks @loziobiz, I will check it out and tell you how it goes.

**Comment by develar** [comment]
@adamsiwiec I suggest you to just use NSIS.

**Comment by adamsiwiec** [comment]
What are the benefits of using NSIS over squirrels, does it have automatic updates?

**Comment by develar** [comment]
#529
