### ISSUE TITLE
Recieving 'Application icon is not set' warning 

### ISSUE THREAD

**Issue by adamsiwiec** [electron-userland/electron-builder#1036]
* **Version**: 10.9.3

* **Target**:  Mac, Windows, Linux

I am recieving the `⚠  Application icon is not set, default Electron icon will be used` error even though there is proper files in the build directory.

```
❯ tree -L 2 
.
├── LICENSE.md
├── README.md
├── build
│   ├── background.png
│   ├── favicon.ico
│   ├── gray.icns
│   └── icons
├── dist
│   ├── mac
│   ├── win
│   └── win-unpacked
├── index.html
├── main.js
├── node_modules \\ Didn't want to list out all that :)
├── package.json
├── renderer.js
├── start.html
├── start.js
└── yarn.lock

```

Is this a bug or am I doing something wrong

**Comment by adamsiwiec** [comment]
Silly me, I forgot to notice that I have to name the different files to icon.ico and icon.icns. I think there should be a way to just check for files ending in `*.ico` ,`*.icns`, and `*.png`.

**Comment by develar** [comment]
> should be a way to just check for files ending in *.ico ,*.icns, and *.png.

It maybe unrelated icon — e.g. https://github.com/electron-userland/electron-builder/wiki/Options#FileAssociation-icon

**Comment by mmclau14** [comment]
if that is the case, then this is a bug. because it is saying that the application icon is not set, not that the file association icon is not set. very confusing

**Comment by leoj3n** [comment]
+1 this necessary bit of config should be exposed in error message if possible
