### ISSUE TITLE
TypeError: s.trim is not a function

### ISSUE THREAD

**Issue by df-karuna** [electron-userland/electron-builder#1037]
* **Version**: 4.6.0

* **Target**: nsis

Hello. I tried first time to use `electron-builder` but, the error `TypeError: s.trim is not a function` had occured and what is the `TypeError: s.trim is not a function` meaning in here.

I don't understand why ouutput like this `Signing StocktalkPC.exe (certificate file "undefined")` but I declared envrionment variable `WIN_CSC_LINK` the full path with file(ex, D:\myapp\cert.pfx)
and `WIN_CSC_KEY_PASSWORD` as my cfx's password. 

I'm using Windows Server 2008, and I tried to build for 32 bit application
and here is my `package.json` snippet and error messages.

Thanks for your help.
df-karuna.

```
  "devDependencies": {
    "asar": "^0.12.3",
    "electron": "^1.4.5",
    "typescript" : "^2.1.4",
    "electron-builder": "^7.14.2",
    "electron-installer-squirrel-windows": "^1.3.0",
    "electron-packager": "8.1.0"
  },
  "build": {
    "appId": "kr.stocktalk.pc",
    "forceCodeSigning" : true,
    "nsis" : {
      "runAfterFinish" : false,
      "installerIcon" : "./stocktalk.ico",
      "installerHeaderIcon" : "./stocktalk.ico",
      "language" : "0412",
      "include" : false
    },
    "win": {
      "target" : "nsis",
      "icon": "./stocktalk-large-test.ico",
      "signingHashAlgorithms" : "sha256",
      "certificateSubjectName" : "CDEFINITION",
      "timeStampServer" : false
    }
  },
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . --overwrite --icon=stocktalk.ico --asar --arch=ia32",
    "dist-test:win": "build --dir --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/",
    "dist-test:nsis": "build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/",
    "dist:win": "build --dir --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/",
    "dist:nsis": "build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/"
  },
```

```
D:\ws-atom\stocktalk-electron>npm run dist-test:nsis

> StocktalkPC@2.1.0 dist-test:nsis D:\ws-atom\stocktalk-electron
> build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 ia32 using electron 1.4.5 to dist\win-ia32-unpacked

Signing StocktalkPC.exe (certificate file "undefined")
node_modules\node-notifier is not packed into asar archive - contains executable code
Building nsis ia32

Building NSIS installer

Custom NSIS script is used - uninstaller is not signed by electron-builder
TypeError: s.trim is not a function
    at isEmptyOrSpaces (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\util\util.ts:280:25)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\platformPackager.ts:480:15
    at next (native)
From previous event:
    at WinPackager.getResource (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\platformPackager.js:512:11)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:258:42
From previous event:
    at NsisTarget.executeMakensis (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\targets\nsis.js:348:11)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:202:58
From previous event:
    at NsisTarget.buildInstaller (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\targets\nsis.js:269:11)
    at NsisTarget.finishBuild (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:67:49)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\packager.ts:138:31
From previous event:
    at Packager.doBuild (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\packager.js:254:11)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\packager.ts:102:32
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\packager.js:206:11)
    at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\builder.ts:234:33
    at next (native)
From previous event:
    at build (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\builder.js:81:21)
    at Object.<anonymous> (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\build-cli.js:66:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.j
s" "run" "dist-test:nsis"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! StocktalkPC@2.1.0 dist-test:nsis: `build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the StocktalkPC@2.1.0 dist-test:nsis script 'build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/'.
npm ERR! This is most likely a problem with the StocktalkPC package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs StocktalkPC
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls StocktalkPC
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ws-atom\stocktalk-electron\npm-debug.log
```

**Comment by develar** [comment]
> node v4.6.0

Could you please upgrade to node 6?

**Comment by df-karuna** [comment]
@develar Ah, thanks. I used too old version, right?

**Comment by develar** [comment]
>  I used too old version, right?

We cannot drop nodejs 4 support yet (although current LTS is 6), but I ask you to try nodejs 6 to be sure that it is or old version, or electron-builder bug.

**Comment by develar** [comment]
> "electron-builder": "^7.14.2",

Also please update electron-builder to latest 10.

**Comment by df-karuna** [comment]
@develar Okay, I'll try again after update all, and recomment here. Thanks a lot develar.

**Comment by df-karuna** [comment]
@develar Sorry to say that. I tried agin after upgrade electron-builder to 10.9.3 but result doesn't matter. 

I declared environment variables like this. 
![image](https://cloud.githubusercontent.com/assets/3124496/21426600/29a703e2-c893-11e6-8008-842e53f382bc.png)

**Comment by df-karuna** [comment]
My error output has changed.

> No native production dependencies
> Packaging for win32 ia32 using electron 1.4.13 to dist\win-ia32-unpacked
> Signing StocktalkPC.exe (certificate file "undefined")
> Error: Exit code: 1. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.5.
> 0\windows-6\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /n cert /fd sha256 /td sha256 /d StocktalkPC /du http
> s://github.com/cdefinition/pdb3020d901dd20e04b7d12450cce361261d71f2e311cc3e4c79a59b493a2e9bc (sha256 hash) D:\ws-atom\stockta
> lk-electron\dist\win-ia32-unpacked\StocktalkPC.exe
> SignTool Error: No certificates were found that met all the given criteria.
> 
> SignTool Error: No certificates were found that met all the given criteria.
> 
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\util\util.ts:77:16
>     at ChildProcess.exithandler (child_process.js:213:5)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I don't use my project with github but in code sign command error, 
it shows 
> htts://github.com/cdefinition/pdb3020d901dd20e04b7d12450cce361261d71f2e311cc3e4c79a59b493a2e9bc

What is it mean?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` to get full debug output.

**Comment by df-karuna** [comment]
Here is full debug output. 

> D:\ws-atom\stocktalk-electron>set DEBUG=electron-builder
> 
> D:\ws-atom\stocktalk-electron>npm run dist-test:nsis
> 
> > StocktalkPC@2.1.0 dist-test:nsis D:\ws-atom\stocktalk-electron
> > build --ia32 && cp ./stocktalk.ico ./dist/win-unpacked/
> 
> No native production dependencies
> Packaging for win32 ia32 using electron 1.4.13 to dist\win-ia32-unpacked
>   electron-builder Found existing nsis C:\Users\Administrator\AppData\Local\electron-builder\cache\nsis\nsis-3.0.4 +0ms
>   electron-builder Spawning D:\ws-atom\stocktalk-electron\node_modules\7zip-bin-win\x64\7za.exe x -bd C:\Users\Administrator\
> .electron\electron-v1.4.13-win32-ia32.zip -oD:\ws-atom\stocktalk-electron\dist\win-ia32-unpacked +1s
> 
> 7-Zip (a) [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
> 
> Scanning the drive for archives:
> 1 file, 44030471 bytes (42 MiB)
> 
> Extracting archive: C:\Users\Administrator\.electron\electron-v1.4.13-win32-ia32.zip
> --
> Path = C:\Users\Administrator\.electron\electron-v1.4.13-win32-ia32.zip
> Type = zip
> Physical Size = 44030471
> 
> Everything is Ok
> 
> Files: 74
> Size:       108417432
> Compressed: 44030471
>   electron-builder D:\ws-atom\stocktalk-electron\node_modules\7zip-bin-win\x64\7za.exe (3300) exited with code 0 +1s
>   electron-builder Dev or extraneous dependencies: 7zip-bin, 7zip-bin-win, ansi-align, ansi-escapes, ansi-regex, ansi-styles,
>  argparse, array-find-index, asap, asn1, assert-plus, async, asynckit, aws-sign2, aws4, balanced-match, base64-js, bcrypt-pbk
> df, bluebird, bluebird-lst-c, boom, boxen, buffer-crc32, brace-expansion, buffer-shims, builtin-modules, camelcase, camelcase
> -keys, capture-stack-trace, caseless, chalk, chromium-pickle-js, cli-boxes, ci-info, cli-cursor, cliui, color-convert, code-p
> oint-at, combined-stream, commander, compare-version, concat-map, core-util-is, create-error-class, cryptiles, cuint, current
> ly-unhandled, debug, debuglog, decamelize, deep-extend, delayed-stream, dezalgo, dot-prop, ecc-jsbn, electron, electron-downl
> oad, electron-macos-sign, error-ex, es6-promise, escape-string-regexp, esprima, exit-hook, extend, extsprintf, fd-slicer, fil
> led-array, find-up, forever-agent, form-data, fs-extra, fs.realpath, generate-function, generate-object-property, get-caller-
> file, get-stdin, glob, graceful-fs, graceful-readlink, har-validator, has-ansi, hawk, hoek, home-path, hosted-git-info, http-
> signature, imurmurhash, indent-string, inflight, inherits, ini, invert-kv, is-arrayish, is-builtin-module, is-ci, is-finite,
> is-fullwidth-code-point, is-npm, is-obj, is-property, is-redirect, is-retry-allowed, is-stream, is-typedarray, is-utf8, isarr
> ay, isbinaryfile, isstream, jju, jodid25519, js-yaml, jsbn, json-parse-helpfulerror, json-schema, json-stringify-safe, jsonfi
> le, jsonpointer, jsprim, klaw, latest-version, lazy-req, lcid, load-json-file, lodash, lodash._reinterpolate, lodash.template
> settings, lodash.template, loud-rejection, lowercase-keys, map-obj, meow, mime, mime-db, minimatch, mime-types, minimist, ms,
>  node-emoji, node-status-codes, normalize-package-data, normalize-path, nugget, number-is-nan, oauth-sign, object-assign, obj
> ect-keys, once, onetime, os-locale, os-homedir, os-tmpdir, osenv, package-json, parse-color, parse-json, parse-ms, path-exist
> s, path-is-absolute, path-type, pend, pify, pinkie, pinkie-promise, plist, plur, prepend-http, pretty-bytes, pretty-ms, proce
> ss-nextick-args, progress, progress-stream, punycode, qs, rc, read-installed, read-pkg, read-pkg-up, readable-stream, readdir
> -scoped-modules, redent, registry-auth-token, registry-url, repeating, require-directory, request, restore-cursor, require-ma
> in-filename, rimraf, sanitize-filename, semver, semver-diff, set-blocking, signal-exit, single-line-log, slide, sntp, source-
> map, source-map-support, spdx-correct, spdx-expression-parse, spdx-license-ids, speedometer, sprintf-js, string-width, string
> .prototype.codepointat, stat-mode, string_decoder, stringstream, strip-ansi, strip-bom, strip-indent, strip-json-comments, su
> mchecker, supports-color, throttleit, through2, timed-out, trim-newlines, tough-cookie, truncate-utf8-bytes, tunnel-agent, tw
> eetnacl, typedarray, unzip-response, typescript, update-notifier, url-parse-lax, utf8-byte-length, util-deprecate, util-exten
> d, uuid, uuid-1345, validate-npm-package-license, verror, walkdir, which-module, widest-line, window-size, wrap-ansi, wrappy,
>  write-file-atomic, xdg-basedir, xmlbuilder, xmldom, xtend, y18n, yauzl, archiver-utils, archiver, bl, compress-commons, conf
> igstore, concat-stream, crc32-stream, dashdash, duplexer2, end-of-stream, extract-zip, fs-extra-p, getpass, got, is-my-json-v
> alid, mkdirp, lazystream, read-all-stream, read-package-json, sshpk, tar-stream, yargs, yargs-parser, zip-stream, electron-bu
> ilder, asar, grunt-electron-installer, electron-installer-squirrel-windows, electron-packager +3ms
>   electron-builder Found existing winCodeSign C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCode
> Sign-1.5.0 +43ms
>   electron-builder Executing C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.5.0\rcedit
> .exe D:\ws-atom\stocktalk-electron\dist\win-ia32-unpacked\StocktalkPC.exe --set-version-string CompanyName C-Definition Corp.
>  --set-version-string FileDescription StocktalkPC --set-version-string ProductName StocktalkPC --set-version-string InternalN
> ame StocktalkPC --set-version-string LegalCopyright Copyright © 2016 C-Definition Corp. --set-version-string OriginalFilenam
> e  --set-file-version 2.1.0 --set-product-version 2.1.0 --set-icon D:\ws-atom\stocktalk-electron\stocktalk-large-test.ico +3m
> s
> Signing StocktalkPC.exe (certificate file "undefined")
>   electron-builder Executing C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.5.0\window
> s-6\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /n cert /fd sha256 /td sha256 /d StocktalkPC /du https://gith
> ub.com/cdefinition/pdb3020d901dd20e04b7d12450cce361261d71f2e311cc3e4c79a59b493a2e9bc (sha256 hash) D:\ws-atom\stocktalk-elect
> ron\dist\win-ia32-unpacked\StocktalkPC.exe +167ms
>   electron-builder node_modules\node-notifier is not packed into asar archive - contains executable code +11ms
> Error: Exit code: 1. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.5.
> 0\windows-6\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /n cert /fd sha256 /td sha256 /d StocktalkPC /du http
> s://github.com/cdefinition/pdb3020d901dd20e04b7d12450cce361261d71f2e311cc3e4c79a59b493a2e9bc (sha256 hash) D:\ws-atom\stockta
> lk-electron\dist\win-ia32-unpacked\StocktalkPC.exe
> SignTool Error: No certificates were found that met all the given criteria.
> 
> SignTool Error: No certificates were found that met all the given criteria.
> 
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\util\util.ts:77:16
>     at ChildProcess.exithandler (child_process.js:213:5)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by develar** [comment]
Please remove `"certificateSubjectName" : "CDEFINITION",` if you use `WIN_CSC_LINK`

**Comment by df-karuna** [comment]
@develar Can I ask one more thing?
Code signing was successful thanks for your help. 

but `s.trim is not a function` occured again like the title on this question. 
Is there more things to declare dependencies or nsis options?

> Packaging NSIS installer for arch ia32
> Building NSIS installer
>   electron-builder Spawning D:\ws-atom\stocktalk-electron\node_modules\7zip-bin-win\x64\7za.exe a -bd -mx=9 -mfb=64 -md=64m -
> ms=on D:\ws-atom\stocktalk-electron\dist\StocktalkPC-2.1.0-ia32.nsis.7z . +1s
> 
> 7-Zip (a) [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
> 
> Scanning the drive:
> 91 folders, 272 files, 112645168 bytes (108 MiB)
> 
> Creating archive: D:\ws-atom\stocktalk-electron\dist\StocktalkPC-2.1.0-ia32.nsis.7z
> 
> Items to compress: 363
> 
> 
> Files read from disk: 272
> Archive size: 28376537 bytes (28 MiB)
> Everything is Ok
>   electron-builder D:\ws-atom\stocktalk-electron\node_modules\7zip-bin-win\x64\7za.exe (8548) exited with code 0 +25s
>   electron-builder { APP_ID: 'kr.stocktalk.pc',
>   electron-builder   APP_GUID: '816f7065-a094-58d4-a6a4-0735c96b1f59',
>   electron-builder   PRODUCT_NAME: 'StocktalkPC',
>   electron-builder   PRODUCT_FILENAME: 'StocktalkPC',
>   electron-builder   APP_FILENAME: 'StocktalkPC',
>   electron-builder   APP_DESCRIPTION: '생생한 주식토크, 생톡',
>   electron-builder   VERSION: '2.1.0',
>   electron-builder   COMPANY_NAME: 'C-Definition Corp.',
>   electron-builder   PROJECT_DIR: 'D:\\ws-atom\\stocktalk-electron',
>   electron-builder   BUILD_RESOURCES_DIR: 'D:\\ws-atom\\stocktalk-electron\\build',
>   electron-builder   MUI_ICON: 'D:\\ws-atom\\stocktalk-electron\\stocktalk.ico',
>   electron-builder   MUI_UNICON: 'D:\\ws-atom\\stocktalk-electron\\stocktalk.ico',
>   electron-builder   APP_32: 'D:\\ws-atom\\stocktalk-electron\\dist\\StocktalkPC-2.1.0-ia32.nsis.7z',
>   electron-builder   HEADER_ICO: 'D:\\ws-atom\\stocktalk-electron\\stocktalk.ico',
>   electron-builder   COMPRESS: 'auto',
>   electron-builder   ONE_CLICK: null } +2ms
>   electron-builder { OutFile: '"D:\\ws-atom\\stocktalk-electron\\dist\\StocktalkPC Setup 2.1.0.exe"',
>   electron-builder   VIProductVersion: '2.1.0.0',
>   electron-builder   VIAddVersionKey:
>   electron-builder    [ '/LANG=0412 ProductName "StocktalkPC"',
>   electron-builder      '/LANG=0412 ProductVersion "2.1.0"',
>   electron-builder      '/LANG=0412 CompanyName "C-Definition Corp."',
>   electron-builder      '/LANG=0412 LegalCopyright "Copyright © 2016 C-Definition Corp."',
>   electron-builder      '/LANG=0412 FileDescription "생생한 주식토크, 생톡"',
>   electron-builder      '/LANG=0412 FileVersion "2.1.0"' ],
>   electron-builder   Unicode: true,
>   electron-builder   SetCompressor: 'lzma',
>   electron-builder   SetCompressorDictSize: '64' } +15ms
> Custom NSIS script is used - uninstaller is not signed by electron-builder
> TypeError: s.trim is not a function
>     at isEmptyOrSpaces (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\util\util.ts:237:25)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\platformPackager.ts:517:15
>     at next (native)
> From previous event:
>     at WinPackager.getResource (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\platformPackager.js:530:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:286:42
>     at next (native)
>     at runCallback (timers.js:637:20)
>     at tryOnImmediate (timers.js:610:5)
>     at processImmediate [as _immediateCallback] (timers.js:582:5)
> From previous event:
>     at NsisTarget.executeMakensis (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\targets\nsis.js:375:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:215:58
>     at next (native)
>     at D:\ws-atom\stocktalk-electron\node_modules\graceful-fs\graceful-fs.js:78:16
>     at tryToString (fs.js:455:3)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
> From previous event:
>     at NsisTarget.buildInstaller (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\targets\nsis.js:296:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\targets\nsis.ts:76:18
>     at next (native)
> From previous event:
>     at NsisTarget.finishBuild (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\targets\nsis.js:151:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\packager.ts:150:31
> From previous event:
>     at Packager.doBuild (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\packager.js:275:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\packager.ts:114:38
>     at next (native)
>     at runCallback (timers.js:637:20)
>     at tryOnImmediate (timers.js:610:5)
>     at processImmediate [as _immediateCallback] (timers.js:582:5)
> From previous event:
>     at Packager.build (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\packager.js:227:11)
>     at D:\ws-atom\stocktalk-electron\node_modules\electron-builder\src\builder.ts:241:40
>     at next (native)
> From previous event:
>     at build (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\builder.js:89:21)
>     at Object.<anonymous> (D:\ws-atom\stocktalk-electron\node_modules\electron-builder\out\cli\build-cli.js:68:41)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
