### ISSUE TITLE
auto-update error: 406 not acceptable

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1038]
* **Version**: 10.9.3

* **Target**: Windows --ia32

After `checking-for-update` event fire `error` event with error: [debug.log](https://github.com/electron-userland/electron-builder/files/669861/debug.2.txt)

**My app**:
* [releases](https://github.com/cawa-93/ad_maker/releases/)
* [main.js](https://github.com/cawa-93/ad_maker/blob/master/app/main.js#L44)
* [package.json](https://github.com/cawa-93/ad_maker/blob/master/package.json)
* [app package.json](https://github.com/cawa-93/ad_maker/blob/master/app/package.json)

**Comment by s-coimbra21** [comment]
* Version: 10.15.1
* Target: Windows (NSIS)

Happening to me consistently. I tried to debug this for a bit and saw that the request containing the Location header (for the redirect) wasn't being picked up.

**Comment by badams** [comment]
This seems to be caused by a change on Github's end, am looking into it

**Comment by s-coimbra21** [comment]
Does electron's `net.request` let you handle 302 redirects yourself?

**Comment by badams** [comment]
@s-coimbra21 I believe so, but I've opted for a different approach when retrieving the latest version tag in my PR (#1068)

**Comment by develar** [comment]
@badams did a great job, electron-auto-updater@0.8.6 (tag: next) published. Tag `next` because I don't have time to make all tests and we don't yet have special electron tests. Please try it.
