### ISSUE TITLE
Option to use system-installed electrion instead of per-package electron

### ISSUE THREAD

**Issue by nlowe** [electron-userland/electron-builder#1041]
* **Version**: 10.9.3

* **Target**: `linux`/`dir`

I'm trying to package [stanfieldr/ghetto-skype](https://github.com/stanfieldr/ghetto-skype) for Arch Linux. With `v1.5.0`, the project is now using `electron-builder`. I cannot seem to find a way to use the system installed copy of electron. The build system currently pulls an entire copy of electron, bloating the package to ~240mb. Arch has an [electron](https://www.archlinux.org/packages/community/x86_64/electron/) package in the official community repos, which lets us share the large runtime amongst packages that we install, decreasing the overall size of each application significantly in most cases.

Is there existing functionality that I've missed, or does this not exist yet?

**Comment by develar** [comment]
Do you mean from a user perspective (why app is so large) or from a developer perspective (why I need to use npm package electron if system provides)?

**Comment by nlowe** [comment]
From a developer perspective more or less. I believe the final package is large because you're essentially bundling a chrome(ium) runtime, correct?

**Comment by develar** [comment]
>  bundling a chrome(ium) runtime, correct?

Yes. And in case of Linux we don't change executable. Executable is just renamed.

I don't think that it is good idea to reuse system provided executable. Well you can — use some shell script to act as a proxy (find system installed electron and run app using it). But.... brrr....

Probably you can just use AppImage?
