### ISSUE TITLE
Conflicts in Auto-update Docs

### ISSUE THREAD

**Issue by jessep** [electron-userland/electron-builder#1044]
*electron builder version: 10.10.0*: 

*targets: mac/win*: 

The [auto-update docs](https://github.com/electron-userland/electron-builder/wiki/Auto-Update) linked from the home page mention a uniform api, but [this page](https://github.com/electron-userland/electron-builder/blob/eff85c38e99a7e11c47c1e40464258dfcae069bd/docs/Auto%20Update.md) mentions that the electron-auto-updater package only works on windows. Which is correct? I'm assuming both from the front page link and from [this code](https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/main.ts), which appears to check platform, that everything is supported, but wanted to make sure.

I'm happy to update the docs page appropriately once this is confirmed.

**Comment by develar** [comment]
> is not yet simplified. Update providers supported only on Windows

It means that simplified way is supported only on windows. On macOS you need to use electron official way (special server and setting feed URL).

Your PR to make it clear is welcome. Or you can help us to merge macOS code from https://github.com/megahertz/electron-simple-updater (it is planned).
