### ISSUE TITLE
Checksum mismatch on Windows NSIS

### ISSUE THREAD

**Issue by Daymannovaes** [electron-userland/electron-builder#1045]
* **Version**: 10.8.1

* **Target**: NSIS
(building from windows too)

* **Node version**: 6.9.1
* **npm version**: 4.0.3

I'm getting checksum mismatch, like following in the screenshot

![screenshot 18](https://cloud.githubusercontent.com/assets/3648665/21464447/0b89b716-c964-11e6-9988-cd59709bfed1.png)

I uploaded the executables with `--publish=always` at github and didn't change anything.
The fact that I'm checking for updates a lot of times even ater the download starts, can affect this?

Because just for test purpose, I put the check interval to 30 seconds, so I get `update-available` a bunch of times.

Plus, I'm getting everytime a different checksum. What's going on?

My autoupdater module is very simple:

```
autoUpdater.addListener('update-available', () => {
  logger.info('update-available');
});
autoUpdater.addListener('update-downloaded', (event, releaseNotes, releaseName, releaseDate, updateURL) => {
  autoUpdater.quitAndInstall();
});
autoUpdater.addListener('error', (error) => {
  logger.error('error when trying to check for update');
  logger.error(error);
});
autoUpdater.addListener('checking-for-update', () => {
  logger.info('checking-for-update');
});
autoUpdater.addListener('update-not-available', () => {
  logger.info('update-not-available');
});

async function setup() {
  autoUpdater.checkForUpdates();

  await sleep(30 * 1000);
  setup();
}
setup();
```

And but package config is simple too:

```
"build": {
    "appId": "some-id",
    "files": [
      "node_modules/**/*",
      ".env",
      "app/**/*"
    ],
    "publish": [
      {
        "provider": "github",
        "repo": "some-repo"
      }
    ],
    "win": {
      "certificateFile": "./certs/my_signing_key.pfx",
      "certificatePassword": ""
    }
  }
```

**Comment by develar** [comment]
Probably. Confirmed that we don't queue check updates requests. Should be fixed.

**Comment by tvanro** [comment]
**electron-builder**: 10.16.0
**electron-auto-updater**: 0.9.0

**Target**: NSIS
(building from docker on Linux)

I'm receiving the exact same error so there's still something going on I'm afraid.
Like with @Daymannovaes, the second checksum is different on each check from electron-builder. My guess is that it's doing the check on a whole file-download request instead of only the file.

**Comment by develar** [comment]
@tvanro What server do you use? Amazon S3? GitHub? Own server (please at least specify server — nginx, some node module).

**Comment by tvanro** [comment]
@develar thanks for getting back to me.
I'm using an own server, `nginx/1.11.5` to be precise.

**Comment by maczikasz** [comment]
I see the same issue, with ownserver (spring boot based) but what I also see is that the file that was downloaded is not runnable, @tvanro does that happen to you too?

**Comment by maczikasz** [comment]
Adding response.pause to the compiled js solved the issue for me

**Comment by tvanro** [comment]
You rock @maczikasz !
I installed **electron-auto-updater 0.9.1** and it works as expected now
