### ISSUE TITLE
Skip snap on mac?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#1048]
Since snap doesn't compile on mac (or windows?), is it possible to just skip it if we try to compile for linux? Only on linux should it be actually executed.

**Comment by develar** [comment]
Why you cannot use special command to build on Linux?

**Comment by atypicalprogrammer** [comment]
i'd still like to be able to build all the other linux targets on mac.

**Comment by develar** [comment]
snaps on mac will be supported tomorrow, I hope :)

**Comment by develar** [comment]
Snap works on mac.
