### ISSUE TITLE
Programmatic API breakage on minor version update

### ISSUE THREAD

**Issue by mihe** [electron-userland/electron-builder#1049]
Just did an update from `10.6.1` to `10.11.0` and found that my programmatic usage of your package wasn't compiling anymore (using TypeScript). Turns out the `directories` member of `DevMetadata` was moved to `BuildMetadata`. Not sure if I'm misusing the API in some way, but I couldn't really find any documentation outside of the actual `.d.ts` file, so if you could point me in the right direction that'd be great.

**Comment by develar** [comment]
Runtime is not broken (property is still taken in account).

Please use `config` instead of `devMetata.build` I will fix programmatic docs soon. You can post your code and I will help you to migrate.

**Comment by mihe** [comment]
No worries, managed to work it out myself after you pointed me in the direction of `config`. Thanks!
