### ISSUE TITLE
node-usb is not building for windows

### ISSUE THREAD

**Issue by mattapperson** [electron-userland/electron-builder#1051]
1.4.13

OSX and Windows

I am following all the steps for native modules, and have a number of other ones working. But when I added node-usb, and compile it from my Mac, it runs fine on Mac but on windows I get an error saying "not a valid win32 application". When I compile my app on windows all is fine with node-usb though.
Not really sure where to start debugging this... but I have tried blowing away my distilled folder and my node_module and reinstalling everything... no dice.

**Comment by develar** [comment]
Yes, you can build native modules only on the same platform.
