### ISSUE TITLE
How to delete AppData on uninstall squirrel app.

### ISSUE THREAD

**Issue by hifizz** [electron-userland/electron-builder#1052]
electron-builder version 10.12.0.

target: squirrelWindows

question: How to delete AppData on uninstall squirrel app?

I save my user_setting.json in the <% AppData%> path。But when the user want to uninstall the app and then install it. I want to deletee the user_setting.json file and setting a new file with the programe runing. My core question is how to handle the squirrel uninstall event to delete my user_setting.json file saved in the <%AppData%> direstory. I have google it but nothing to find, because It seems Squirrel doesn't remove app data folder from the source code. [squirrel uninstall code](Squirrel.Windows/UpdateManager.ApplyReleases.cs at master · Squirrel/Squirrel.Windows  https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs#L92). so,I need help.

**Comment by develar** [comment]
Maybe you will just use nsis target?

**Comment by hifizz** [comment]
@develar nsis is ok. But I just want to use Squirrel to pack my app. Squirrel app looks fancy more.

**Comment by develar** [comment]
> Squirrel app looks fancy more.

Do you mean installer? nsis provides correct progress window.

**Comment by PierBover** [comment]
I also need this feature in Squirrel.

Is this possible?

**Comment by develar** [comment]
@PierBover No, new features only for NSIS, default target.
