### ISSUE TITLE
can't find license?

### ISSUE THREAD

**Issue by devgaas** [electron-userland/electron-builder#1053]
* **Version**:  10.8

* **Target**:  1.4

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/electron/appnamedist/mac/Electron.app/Contents/Resources/app.asar.unpacked/out/appname-darwin-x64/LICENSE'

getting this error when trying to build for mac
I have in build/license.txt

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and provide full build log.

**Comment by develar** [comment]
> license.txt

We use license.txt only for NSIS, if I understand correctly.

**Comment by devgaas** [comment]
sudo DEBUG=electron-builder build --m 

correct

**Comment by develar** [comment]
> sudo DEBUG=electron-builder build --m

Please do not use `sudo` (for what)?

**Comment by develar** [comment]
On Linux you cannot build default `dmg` target. So, `--mac zip` if you want to build macOS  zipped app.

**Comment by devgaas** [comment]
no, this is mac.

**Comment by develar** [comment]
> no, this is mac.

So, definitely you should not use `sudo` ;)

**Comment by devgaas** [comment]
lol where does it dump the log? I'm having my friend build remotely on mac

**Comment by devgaas** [comment]
Extracting archive: /Users/appname/.electron/electron-v1.4.8-darwin-x64.zip--Path = /Users/appname/.electron/electron-v1.4.8-darwin-x64.zipType = zipPhysical Size = 42099326Everything is OkFolders: 143Files: 180Size:       112305663Compressed: 42099326  electron-builder /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za (52004) exited with code 0 +4s  electron-builder Dev or extraneous dependencies: abbrev, after, ansi, array-index, balanced-match, brace-expansion, buffer-shims, concat-map, d, debug, deep-extend, delegates, es5-ext, es6-iterator, es6-symbol, execspawn, expand-template, fs.realpath, fstream, gauge, ghreleases, ghrepos, ghutils, github-from-package, has-unicode, hyperquest, inflight, ini, isexe, jsonist, lodash.padend, lodash.pad, lodash.padstart, ms, nan, noop-logger, nopt, npmlog, once, os-homedir, os-tmpdir, osenv, path-array, path-is-absolute, process-nextick-args, pump, robotjs, semver, simple-get, simple-mime, strip-json-comments, tar, tar-fs, through2, unzip-response, url-template, util-deprecate, util-extend, which, wrappy, are-we-there-yet, bl, duplexer2, end-of-stream, node-gyp, prebuild, node-ninja, rc, rimraf, tar-stream +12ms  electron-builder .. is not packed into asar archive - contains executable code +13sError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/electron/appname/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/out/appname-darwin-x64/LICENSE'    at copyFile (/usr/local/lib/node_modules/electron-builder/src/util/fs.ts:124)

**Comment by devgaas** [comment]
build --m zip

gives same error

**Comment by develar** [comment]
Why your app located in the `/usr/local/lib/node_modules/electron`?

**Comment by devgaas** [comment]
it was moved. Now I get

```
Error: Exit code: 2. Command failed: /usr/bin/pd4cdf50bab944284b5876cc5548f6ebccbf3787f1defcc78d7b2bbd348921a1f (sha256 hash) /usr/local/lib/node_modules/electron-builder/templates/dmg/dmgProperties.plsh: -c: line 0: unexpected EOF while looking for matching `''sh: -c: line 1: syntax error: unexpected end of file

Cannot query image dimensions at /usr/local/lib/node_modules/electron-builder/templates/dmg/dmgProperties.pl line 21.

```

any clue? I have a icon file in build

**Comment by develar** [comment]
Do you have background dmg?

**Comment by develar** [comment]
Could you please provide full build log (with env `DEBUG=electron-builder`)? Or project?

**Comment by devgaas** [comment]
`   "category": "MeowMeow",
    "electronVersion": "1.4.8",
    "directories": [],
    "nsis": {
      "license": "LICENSE"
    },
    "dmg": {
      "backgroud": "build/background.png"
    }
}`

here is my dmg

**Comment by devgaas** [comment]
`
/usr/bin/pd4cdf50bab944284b5876cc5548f6ebccbf3787f1defcc78d7b2bbd348921a1f (sha256 hash) /usr/local/lib/node_modules/electron-builder/templates/dmg/dmgProperties.plsh: -c: line 0: unexpected EOF while looking for matching `''sh: -c: line 1: syntax error: unexpected end of fileCannot query image dimensions at /usr/local/lib/node_modules/electron-builder/templates/dmg/dmgProperties.pl line 21.
`
Now this weirdness

**Comment by devgaas** [comment]
I'm using the background.png from https://github.com/BZCoding/SkelEktron/tree/master/build

**Comment by develar** [comment]
@devgaas You don't need to specify path to DMG background it is equals to `build/background.png` Please try to remove explicit configuration.

**Comment by TheLastTech** [comment]
`ak57842378458% sudo DEBUG=electron-builder build --m
Rebuilding native production dependencies for darwin:x64
  electron-builder Spawning npm rebuild robotjs +0ms

> robotjs@0.4.5 install /Users/user2/Desktop/app/node_modules/robotjs
> prebuild --install

  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
robotjs@0.4.5 /Users/user2/Desktop/app/node_modules/robotjs
  electron-builder npm (2653) exited with code 0 +19s
Packaging for darwin x64 using electron 1.4.8 to dist/mac
  electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za x -bd /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip -o/Users/user2/Desktop/app/dist/mac +3s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 42099326 bytes (41 MiB)

Extracting archive: /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip
--
Path = /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip
Type = zip
Physical Size = 42099326

Everything is Ok

Folders: 143
Files: 180
Size:       112305663
Compressed: 42099326
  electron-builder /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za (3038) exited with code 0 +2s
  electron-builder Dev or extraneous dependencies: 7zip-bin, 7zip-bin-mac, accessibility-developer-tools, ansi-align, ansi-escapes, argparse, array-find-index, base64-js, bluebird-lst-c, boxen, buffer-crc32, builtin-modules, camelcase, camelcase-keys, capture-stack-trace, chromium-pickle-js, ci-info, cli-boxes, cli-cursor, cliui, co, co-prompt, code-point-at, color-convert, compare-version, create-error-class, cuint, currently-unhandled, debuglog, decamelize, devtron, dezalgo, dot-prop, electron, electron-builder-http, error-ex, es6-promise, esprima, exit-hook, fd-slicer, filled-array, find-up, fs-extra, get-caller-file, get-stdin, highlight.js, home-path, hosted-git-info, humanize-plus, imurmurhash, indent-string, invert-kv, is-arrayish, is-builtin-module, is-ci, is-finite, is-fullwidth-code-point, is-npm, is-obj, is-redirect, is-retry-allowed, is-utf8, isbinaryfile, js-yaml, jszip, keypress, klaw, latest-version, lazy-req, lcid, load-json-file, loud-rejection, lowercase-keys, macaddress, map-obj, mime, node-emoji, node-status-codes, normalize-package-data, normalize-path, number-is-nan, object-keys, onetime, os-locale, package-json, pako, parse-color, parse-json, parse-ms, path, path-exists, path-type, pend, pify, plist, plur, prepend-http, pretty-bytes, pretty-ms, process, progress, q, querystring, read-installed, read-pkg, read-pkg-up, readdir-scoped-modules, redent, registry-auth-token, registry-url, repeating, require-directory, require-main-filename, restore-cursor, sanitize-filename, semver-diff, set-blocking, signal-exit, single-line-log, slide, source-map, source-map-support, spdx-correct, spdx-expression-parse, spdx-license-ids, speedometer, sprintf-js, stat-mode, string-width, string.prototype.codepointat, strip-bom, strip-indent, sumchecker, throttleit, timed-out, trim-newlines, truncate-utf8-bytes, typedarray, update-notifier, url-parse-lax, utf8-byte-length, uuid-1345, validate-npm-package-license, walkdir, which-module, widest-line, wrap-ansi, write-file-atomic, xdg-basedir, xmlbuilder, xmldom, y18n, yauzl, archiver, archiver-utils, asar-electron-builder, compress-commons, concat-stream, configstore, crc32-stream, electron-build, electron-builder, electron-download, electron-macos-sign, extract-zip, fs-extra-p, got, lazystream, meow, nugget, progress-stream, read-all-stream, read-package-json, url, util, yargs, yargs-parser, zip-stream +10ms
  electron-builder Executing security find-identity -v +17s
  electron-builder Executing security find-identity -v -p codesigning +94ms
     0 valid identities found

     0 valid identities found

⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Building macOS zip
Building DMG
  electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za a -bd -mm=Deflate /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser-4.0.0-mac.zip Meow Meow's Browser.app +449ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive:
  electron-builder Spawning hdiutil create -srcfolder /tmp/electron-builder-nLIRcH/0-1-dmg/.background -srcfolder /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser.app -volname Meow Meow's Browser 4.0.0 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg +118ms
143 folders, 177 files, 129546034 bytes (124 MiB)

Creating archive: /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser-4.0.0-mac.zip

Items to compress: 320

......................................................................................................................
created: /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg
  electron-builder hdiutil (3044) exited with code 0 +13s
  electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg +42ms

Files read from disk: 177
Archive size: 45634713 bytes (44 MiB)
/dev/disk1          	GUID_partition_scheme          	
/dev/disk1s1        	Apple_HFS                      	/Volumes/Meow Meow's Browser 4.0.0

Everything is Ok
  electron-builder Executing ln -s /Applications /Volumes/Meow Meow's Browser 4.0.0/Applications +2s
  electron-builder &makeEntries("Meow Meow's Browser.app", Iloc_xy => [ 130, 220 ]),
  electron-builder &makeEntries("Applications", Iloc_xy => [ 410, 220 ]),
  electron-builder  +23ms
  electron-builder /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za (3042) exited with code 0 +32ms
  electron-builder Executing /usr/bin/perl /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl +33ms
  electron-builder Executing hdiutil detach /dev/disk1 +876ms
"disk1" unmounted.
"disk1" ejected.

Error: Exit code: 2. Command failed: /usr/bin/pd4cdf50bab944284b5876cc5548f6ebccbf3787f1defcc78d7b2bbd348921a1f (sha256 hash) /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
Cannot query image dimensions at /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl line 21.

sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
Cannot query image dimensions at /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl line 21.

    at /usr/local/lib/node_modules/electron-builder/src/util/util.ts:77:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
From previous event:
    at exec (/usr/local/lib/node_modules/electron-builder/src/util/util.ts:55:3)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:153:7
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:294:24
From previous event:
    at attachAndExecute (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:60:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:64:5
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:235:11)
    at postAsyncTasks.push.default.map.it (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:172:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:172:41)
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:80:26
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:80:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/usr/local/lib/node_modules/electron-builder/out/macPackager.js:162:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:275:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:227:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
`

**Comment by devgaas** [comment]
ak57842378458% sudo DEBUG=electron-builder build --m
Rebuilding native production dependencies for darwin:x64
  electron-builder Spawning npm rebuild robotjs +0ms

> robotjs@0.4.5 install /Users/user2/Desktop/app/node_modules/robotjs
> prebuild --install

  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
robotjs@0.4.5 /Users/user2/Desktop/app/node_modules/robotjs
  electron-builder npm (2653) exited with code 0 +19s
Packaging for darwin x64 using electron 1.4.8 to dist/mac
  electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za x -bd /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip -o/Users/user2/Desktop/app/dist/mac +3s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 42099326 bytes (41 MiB)

Extracting archive: /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip
--
Path = /Users/user2/.electron/electron-v1.4.8-darwin-x64.zip
Type = zip
Physical Size = 42099326

Everything is Ok

Folders: 143
Files: 180
Size:       112305663
Compressed: 42099326
  electron-builder /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za (3038) exited with code 0 +2s
  electron-builder Dev or extraneous dependencies: 7zip-bin, 7zip-bin-mac, accessibility-developer-tools, ansi-align, ansi-escapes, argparse, array-find-index, base64-js, bluebird-lst-c, boxen, buffer-crc32, builtin-modules, camelcase, camelcase-keys, capture-stack-trace, chromium-pickle-js, ci-info, cli-boxes, cli-cursor, cliui, co, co-prompt, code-point-at, color-convert, compare-version, create-error-class, cuint, currently-unhandled, debuglog, decamelize, devtron, dezalgo, dot-prop, electron, electron-builder-http, error-ex, es6-promise, esprima, exit-hook, fd-slicer, filled-array, find-up, fs-extra, get-caller-file, get-stdin, highlight.js, home-path, hosted-git-info, humanize-plus, imurmurhash, indent-string, invert-kv, is-arrayish, is-builtin-module, is-ci, is-finite, is-fullwidth-code-point, is-npm, is-obj, is-redirect, is-retry-allowed, is-utf8, isbinaryfile, js-yaml, jszip, keypress, klaw, latest-version, lazy-req, lcid, load-json-file, loud-rejection, lowercase-keys, macaddress, map-obj, mime, node-emoji, node-status-codes, normalize-package-data, normalize-path, number-is-nan, object-keys, onetime, os-locale, package-json, pako, parse-color, parse-json, parse-ms, path, path-exists, path-type, pend, pify, plist, plur, prepend-http, pretty-bytes, pretty-ms, process, progress, q, querystring, read-installed, read-pkg, read-pkg-up, readdir-scoped-modules, redent, registry-auth-token, registry-url, repeating, require-directory, require-main-filename, restore-cursor, sanitize-filename, semver-diff, set-blocking, signal-exit, single-line-log, slide, source-map, source-map-support, spdx-correct, spdx-expression-parse, spdx-license-ids, speedometer, sprintf-js, stat-mode, string-width, string.prototype.codepointat, strip-bom, strip-indent, sumchecker, throttleit, timed-out, trim-newlines, truncate-utf8-bytes, typedarray, update-notifier, url-parse-lax, utf8-byte-length, uuid-1345, validate-npm-package-license, walkdir, which-module, widest-line, wrap-ansi, write-file-atomic, xdg-basedir, xmlbuilder, xmldom, y18n, yauzl, archiver, archiver-utils, asar-electron-builder, compress-commons, concat-stream, configstore, crc32-stream, electron-build, electron-builder, electron-download, electron-macos-sign, extract-zip, fs-extra-p, got, lazystream, meow, nugget, progress-stream, read-all-stream, read-package-json, url, util, yargs, yargs-parser, zip-stream +10ms
  electron-builder Executing security find-identity -v +17s
  electron-builder Executing security find-identity -v -p codesigning +94ms
     0 valid identities found

     0 valid identities found

⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Building macOS zip
Building DMG
  electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za a -bd -mm=Deflate /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser-4.0.0-mac.zip Meow Meow's Browser.app +449ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive:
  electron-builder Spawning hdiutil create -srcfolder /tmp/electron-builder-nLIRcH/0-1-dmg/.background -srcfolder /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser.app -volname Meow Meow's Browser 4.0.0 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg +118ms
143 folders, 177 files, 129546034 bytes (124 MiB)

Creating archive: /Users/user2/Desktop/app/dist/mac/Meow Meow's Browser-4.0.0-mac.zip

Items to compress: 320

......................................................................................................................
created: /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg
  electron-builder hdiutil (3044) exited with code 0 +13s
  electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /tmp/electron-builder-nLIRcH/0-1-dmg/temp.dmg +42ms

Files read from disk: 177
Archive size: 45634713 bytes (44 MiB)
/dev/disk1          	GUID_partition_scheme          	
/dev/disk1s1        	Apple_HFS                      	/Volumes/Meow Meow's Browser 4.0.0

Everything is Ok
  electron-builder Executing ln -s /Applications /Volumes/Meow Meow's Browser 4.0.0/Applications +2s
  electron-builder &makeEntries("Meow Meow's Browser.app", Iloc_xy => [ 130, 220 ]),
  electron-builder &makeEntries("Applications", Iloc_xy => [ 410, 220 ]),
  electron-builder  +23ms
  electron-builder /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za (3042) exited with code 0 +32ms
  electron-builder Executing /usr/bin/perl /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl +33ms
  electron-builder Executing hdiutil detach /dev/disk1 +876ms
"disk1" unmounted.
"disk1" ejected.

Error: Exit code: 2. Command failed: /usr/bin/pd4cdf50bab944284b5876cc5548f6ebccbf3787f1defcc78d7b2bbd348921a1f (sha256 hash) /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
Cannot query image dimensions at /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl line 21.

sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
Cannot query image dimensions at /tmp/electron-builder-nLIRcH/0-2-dmgProperties.pl line 21.

    at /usr/local/lib/node_modules/electron-builder/src/util/util.ts:77:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
From previous event:
    at exec (/usr/local/lib/node_modules/electron-builder/src/util/util.ts:55:3)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:153:7
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:294:24
From previous event:
    at attachAndExecute (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:60:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:64:5
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:235:11)
    at postAsyncTasks.push.default.map.it (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:172:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:172:41)
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:80:26
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:80:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/usr/local/lib/node_modules/electron-builder/out/macPackager.js:162:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:275:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:227:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by develar** [comment]
Sorry, I have no idea. You can attach sample project so I can reproduce.
