### ISSUE TITLE
Can the Applications link to be optional?

### ISSUE THREAD

**Issue by jhg** [electron-userland/electron-builder#1054]
**Version**: 10.7.1

* **Target**: OSX

https://github.com/electron-userland/electron-builder/blob/master/src/targets/dmg.ts#L67
Can the Applications link to be optional?

**Comment by develar** [comment]
PR is welcome.

**Comment by develar** [comment]
Will be fixed soon.

**Comment by develar** [comment]
Link will be not created if no entry in the `content` with `path` `/Applications`
