### ISSUE TITLE
app is running before finished install

### ISSUE THREAD

**Issue by yangbeom** [electron-userland/electron-builder#1055]
* **Version**: 10.9.3

* **Target**: squirrelWindows (win x64)

app is running before finished install using setup.exe file that build squirrel Windows.

and before uninsall too.

how can i run app after finished insatll?

**Comment by develar** [comment]
Hi, not quite understand your issue. Maybe you can use nsis target?

**Comment by yangbeom** [comment]
oh sorry
when i build it, ignored some files
:)
