### ISSUE TITLE
How to auto-update in windows, completely lost

### ISSUE THREAD

**Issue by KYSSelectron** [electron-userland/electron-builder#1058]
I'm trying to understand how auto-update works with electron-builder when using windows (10) and packing for windows. I'm however lost in the docs (mainly https://github.com/electron-userland/electron-builder/wiki/Auto-Update).

What do I have to write in my dev package.json?

```
{
  "name": "myapp",
  "license": "GPL-3.0",
  "productName": "myapp",
  "author": "me",
  "description": "yes",
  "homepage": "https://myapp.github.io/",
  "repository": {
    "type": "git",
    "url": "https://github.com/myapp/myapp.github.io"
  },
  "devDependencies": {
    "electron": "^1.4.12",
    "electron-builder": "^10.7.0"
  },
  "dependencies": {
  },
  "scripts": {
    "start": "./node_modules/.bin/electron app",
    "build": "build --win --x64",
    "postinstall": "install-app-deps"
  },
  "build": {
    "appId": "my.app",
    "productName": "myapp",
    "win": {
      "icon": "./build/icon.ico"
    },
    "publish": {
      "provider": "github",
      "repo": "https://github.com/myapp/myapp.github.io"
    }
  }
}
```

Then, in my main.js page I have this

```
var autoUpdater = require('electron-auto-updater').autoUpdater;
// import {autoUpdater} from "electron-auto-updater" -> unexpected token import

app.on('ready', function() {
    autoUpdater.checkForUpdates();
});

autoUpdater.addListener("update-available", function(event) {
});

autoUpdater.addListener("update-downloaded", function(event, releaseNotes, releaseName, releaseDate, updateURL) {
    autoUpdater.quitAndInstall();
    return true;
});

autoUpdater.addListener("update-not-available", function() {
});
```

And that's it. What am I supposed to upload to the github repository? How can I check what's going on? The build works well in the sense that I get the installer .exe that installs and creates a shortcut of the application and this works. But other than that, auto-update is not there and I don't know what can I try.

**Comment by develar** [comment]
Step 1: Install electron-auto-updater as app dependency. Did you install it?

> What am I supposed to upload to the github repository

It will be automatically upload to GitHub repository on CI server. Define `GH_TOKEN`. On dev machine you can force publish using `--publish always `

**Comment by kazusa0106** [comment]
Is the server for auto-update must be https?I got "ERR_SSL_PROTOCOL_ERROR" after cheking-for-update.

**Comment by KYSSelectron** [comment]
Yes, I installed it

`npm install --save electron-auto-updater`

I have now defined GH_TOKEN with a generated token in https://github.com/settings/tokens, and set it either in command line `set GH_TOKEN=xxx` and in main.js
http://stackoverflow.com/questions/32971416/cross-platform-npm-start-script

```
var exec = require('child_process').exec;
var command = exec('set NODE_ENV=xxx');
command.stdout.on('data', function(data) {
  process.stdout.write(data);
});
command.stderr.on('data', function(data) {
  process.stderr.write(data);
});
command.on('error', function(err) {
  process.stderr.write(err);
});
```

I've added in the package.json (dev) scripts `"release": "build"` to publish always https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

By doing `npm run release` now it is trying to publish but fails. I've changed in the package.json

```
  "repository": {
    "type": "git",
    "url": "myapp/myapp.github.io"
  },
...
    "publish": {
      "provider": "github"
    }
```
And now it works in the sense that it is uploading the .exe file and I can see it in the github releases page.

But when I open my app, it is not detecting any new version (I keep changing the version at every build, so I can see within the app the number of the version to see if this has been updated)

*My repo is public, not sure if I need the token but anyway, I'm saying that because here it seems repos should be private https://github.com/electron-userland/electron-builder/issues/908

What can I do? I don't know how to get the messages from what is happening with the `autoUpdater.checkForUpdates();`, right now I don't know why it fails

**Comment by develar** [comment]
@KYSSelectron Please listen `error` event also to check errors.

**Comment by develar** [comment]
> Is the server for auto-update must be https?I

Yes, due to security reasons.

**Comment by kazusa0106** [comment]
could this be options (https as default vaule)  if provider is 'generic'?  Of course I can install nginx and configure https for my server but I'm using this in LAN.It's not neccesary.

**Comment by develar** [comment]
@kazusa0106 If you will send PR it will be accepted. Would you like? Probably https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/electronHttpExecutor.ts#L141 should be changed.

**Comment by KYSSelectron** [comment]
Ok, I'm listening now to `error ` and `checking-for-update`. I haven't found how to see the logs in windows (console.log doesn't work), so I'm opening a new window and printing in the title the error. And I have 2 windows opened, one for checking-for-update and another for error, but the "error" is empty.

How can I check what says in the `error`?

**Comment by kazusa0106** [comment]
@develar  OK, thanks for reply.
