### ISSUE TITLE
Docker -  wine -  bad exe format for rcedit.exe 

### ISSUE THREAD

**Issue by sneljo1** [electron-userland/electron-builder#1062]
I've been running the electron-builder:wine image successfully on my CI 2-3 days ago ( today 29/12 ). Unfortunately since then, my windows builds keep failing saying the rcedit.exe is a bad exe format. I went back and rerun previous successful builds and it is in fact also a problem there, so it's not a change on my end.

Could it possibly be because of commit 03e43d1830bcc50c0c7bd6f6ee6c26543e8233be ? The timing seems about right.

Full stacktrace minus the default npm stuff:
http://pastebin.com/VHTFzmGn

**Comment by SiKing** [comment]
I just hit this problem. How do I get the fix mentioned "in 10 minutes" above?

**Comment by Superjo149** [comment]
This was fixed in a release about a month ago. Are you using an older version?

**Comment by SiKing** [comment]
I was told to "just run this script" which ends up with this error. How can I tell if I have the good version?

**Comment by develar** [comment]
@SiKing `docker pull electronuserland/electron-builder:wine`

**Comment by SiKing** [comment]
I had time to dig into this some more.

Apparently in our build we are using electron-packager not the electron-builder. But I see the same error as reported by OP. Maybe I should move this to the correct project.
