### ISSUE TITLE
[FR][NSIS] allow submenu in start menu in programfiles

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1063]
right now the app start menu shortcut and the program files dir are created without submenu.
This would be very useful if we could define a submenu(most of the time would be a company name) to be used in start menu and program files.

Thanks

**Comment by develar** [comment]
<img width="494" alt="screen shot 2017-01-01 at 12 00 40" src="https://cloud.githubusercontent.com/assets/350686/21580941/f5e68756-d019-11e6-994e-4082d31cc477.png">
<img width="671" alt="screen shot 2017-01-01 at 12 01 22" src="https://cloud.githubusercontent.com/assets/350686/21580944/099498ba-d01a-11e6-8886-996f1594514d.png">

**Comment by farfromrefug** [comment]
You are amazing!!!
