### ISSUE TITLE
coulden't set icon for application on ubuntu

### ISSUE THREAD

**Issue by ho3einjb** [electron-userland/electron-builder#1064]
* **Version**: ^10.6.1

* **Target**: linux

i'm ubuntu user & and i couldent set icon for my app
this is Eror:
No native production dependencies
Packaging for linux x64 using electron 1.4.1 to dist/linux-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Building AppImage for arch x64

and this is build section of  my package.jason:
"build": {
    "appId": "985654798458542",
    "mac": {
      "category": "crm"
    },
    "win": {
      "iconUrl": "http://bahar.crm.dev/asset_files/img/icon.ico"
    },
    "linux": {
      "iconUrl": "http://bahar.crm.dev/asset_files/img/icon.ico"
    }
  }

**Comment by ho3einjb** [comment]
i couldent set icon for my app on linux with electron-builder

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder#quick-setup-guide 

Step 3.

> The Linux icon set will be generated automatically based on the macOS icns file (or you can put them into the build/icons directory if you want to specify them yourself. The filename must contain the size (e.g. 32x32.png) of the icon).
