### ISSUE TITLE
Docker - Linux (Appimage) error while loading shared libraries: libreadline.so.6: 

### ISSUE THREAD

**Issue by Superjo149** [electron-userland/electron-builder#1065]
* **Version**: 10.15.1

* **Target**: Linux (AppImage)

Using the electron-builder Docker image in CI i'm unable to package into an AppImage file. This does work locally.

**Receiving this error:** 
error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

Link to whole stack trace: 
http://pastebin.com/LfzdqX0y

**Comment by develar** [comment]
Hmm... Are you sure that you use latest docker image? Not `4`?

**Comment by Superjo149** [comment]
@develar I'm using wine. I'm pretty new to CI (gitlab) and docker but i'm not giving it any version so I think it should be using the latest one.

**Comment by develar** [comment]
How do you run? Using `docker run` https://github.com/electron-userland/electron-builder/blob/master/circle.yml#L17 ?

Please try to add to your docker run: `-e "USE_SYSTEM_XORRISO=true"`

**Comment by Superjo149** [comment]
I'm not really using docker run, i'm doing everything directly using the wine image. It should work if i just use the run command then?

Here's my gitlab-ci.yml:

```yml
image: electronuserland/electron-builder:wine

stages:
 - build
 - release
 - test

cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true

before_script:
  - npm install

.release: &release
  stage: release
  only:
    - master
  artifacts:
      paths:
      - release/*.*

build_app:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
      paths:
      - node_modules/
      - app/node_modules/
      - app/main.*

release-linux:
  <<: *release
  script:
  - npm run release-linux

release-win:
  <<: *release
  script:
  - npm run release-win

release-mac:
  <<: *release
  script:
  - npm run release-mac

test_e2e:
  stage: test
  script:
  - npm run test-e2e```

**Comment by develar** [comment]
> In short, with image we refer to the docker image, which will be used to create a container on which your build will run.

https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-an-image So.... must be ok. 

Well... Please try to set env `USE_SYSTEM_XORRISO=true`. https://docs.gitlab.com/ce/ci/yaml/#environment

**Comment by develar** [comment]
Is it possible to provide full log (including docker container creation (i.e. from all output of your CI run))?

**Comment by Superjo149** [comment]
Adding `USE_SYSTEM_XORRISO=true` as a var unfortunately did not work.

Here's my full log (of the package job for linux)
http://pastebin.com/Ys40nwM9

**Comment by develar** [comment]
Are you sure that electron-builder 10.15.1 is used? Is it specified as `^10.15.1` in the package.json?

**Comment by Superjo149** [comment]
Oops, I double checked. I had left it on 10.7.0 from testing, should be fixed in a newer version?

**Comment by develar** [comment]
> should be fixed in a newer version?

must be ;)

**Comment by Superjo149** [comment]
Allright, that did it. Sorry for the waste of time.
