### ISSUE TITLE
Downloading the Debian package from host results in warning 'This file may harm your computer. '

### ISSUE THREAD

**Issue by epezhman** [electron-userland/electron-builder#1073]
* **Version**: 7.14.1

* **Target**: Ubuntu 16.04 64 Bit

Hi, I'm building and packaging my app on Ubuntu 16.04 64 bit for Ubuntu 64 bit (.deb file). it's working alright and the debian package (.deb file) is also installed properly, and then afterward I host my app on AWS S3. The problem is when I download the .deb file from S3 both Firefox v50 and Chrome v55 are giving me warnings that it could be harmful to the computer, any idea what's causing this and how can be fixed? (I can download other debian packages for other software and they all can be downloaded without any warning, the problem is with my own app) thanks

**Comment by develar** [comment]
As far I know, problem not in your app, but in server. Because is not popular, chrome doesn't trust it. http://www.ghacks.net/2015/02/26/this-type-of-file-can-harm-your-computer-warning-in-chrome/

**Comment by develar** [comment]
BTW, please try to use AppImage — do you see such warn?
