### ISSUE TITLE
feat: use electron session and electron net APIs for /packages/electron-builder/src/util/nodeHttpExecutor

### ISSUE THREAD

**Issue by Unchosen** [electron-userland/electron-builder#1074]
Hi, in my electron app, I am using [electron's net API](https://github.com/electron/electron/blob/master/docs/api/net.md) to do my API requests to my services. 
This allows me to specify an [electron session object](https://github.com/electron/electron/blob/master/docs/api/session.md) that supports [having a proxy](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback) in place.
However, when I go to use the [electron-auto-updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-auto-updater) module, the http/https requests are being made directly via the node.js's APIs, in [_this file_](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/util/nodeHttpExecutor.ts#L46) (line 46 & 116) I think.

Is it possible to have a way to make it use the electron net API, or have an option for it somewhere?

**Comment by badams** [comment]
electron-auto-updater [does use the electron net API](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-auto-updater/src/electronHttpExecutor.ts#L57) The nodeHttpExecutor only used in the context of builds/ci the electronHttpexecutor is used when your app checks for updates

**Comment by develar** [comment]
@Unchosen `nodeHttpExecutor.ts` is not used in the electron-auto-updater.

**Comment by Unchosen** [comment]
Thanks for the quick response, and sorry for me misunderstanding it.
So I'll just need to set the proxy on electron.session.defaultSession I assume
