### ISSUE TITLE
.build.mac identity has confusing documentation

### ISSUE THREAD

**Issue by efaroni** [electron-userland/electron-builder#1078]
* **Version**:  7.3.0

* **Target**: Mac OS

.build.mac identity documentation reads: "The name of certificate to use when signing. Consider using environment variables CSC_LINK or CSC_NAME. MAS installer identity is specified in the .build.mas."

CSC_LINK is documented as The HTTPS link (or base64-encoded data, or file:// link, or local path) to certificate (*.p12 or *.pfx file). Shorthand ~/ is supported (home directory).

When I used CSC_LINK env variable, pointing to the public AWS url where my certificate is stored, as the .build.mac identity as suggested by the .build.mac identity documentation, the following error is thrown: Identity name "(My CSC_LINK here)" is specified, but no valid identity with this name in the keychain. Resolved when I used CSC_NAME instead... also works by just hard coding the name of the certificate without the "Developer ID Application:" prefix.

**Comment by develar** [comment]
... "instead of specifying this option" was added to avoid confusion.
