### ISSUE TITLE
How to include libappindicator1 in AppImage?

### ISSUE THREAD

**Issue by morloy** [electron-userland/electron-builder#1082]
* **Version**: 10.7.1

* **Target**: Linux/AppImage

I'm trying to build a Linux package in the AppImage format on macOS. Unfortunately, the tray icon doesn't show up since libappindicator1 is missing. Installing it using apt-get solves the problem, but isn't a very good solution.

Is there any way to include it in the AppImage? There's libnode and libffmpeg in the linux-unpacked folder, so I assume libappindicator1 should go there as well, but I don't know how to do it.

**Comment by develar** [comment]
Planned to implement, priority will be increased. I hope fix will be in 2 days.

**Comment by morloy** [comment]
Any updates on this?

**Comment by develar** [comment]
#1089 had a higher priority. Started to work on this :)

**Comment by develar** [comment]
@morloy Is it possible to provide a link to your project to test libappindicator1 support?

**Comment by develar** [comment]
fixed in `11.4.1`: set [appImage.includeRequiredLib](https://github.com/electron-userland/electron-builder/wiki/Options#AppImageOptions-includeRequiredLib) to `true`.

**Comment by morloy** [comment]
Thanks a lot! Will try to test and give feedback soon.

**Comment by morloy** [comment]
Just tested and it works.

It's a bit weird now, since **all** the dependencies are included, which bloats the AppImage by more than 50 MiB. However, I manually removed all libraries in `AppImage-packages/16.01.17/` expect `libappindicator` and `libindicator`. Now everything works fine and additional file size is negligible.

**Comment by develar** [comment]
@morloy It is a price. If you want to allow user to run AppImage everywhere, you need to it. For example, on Elementary OS. If you are disagree — well, more granulated config maybe introduced.

**Comment by probonopd** [comment]
@develar are you really bundling _all_ libs in that case? That may be overkill. Possibly it would be more sensible to just bundle the ones that are known to be absent from the default installation of well-known distros but needed for Electron.

**Comment by morloy** [comment]
I support @probonopd and would recommend to bundle libappindicator by default (~ 124KiB) and all the others *only* when `includeRequiredLib` is set to `true`.

**Comment by develar** [comment]
Only 291 KB is required to run AppImage on Elementary OS and support libappindicator1.
