### ISSUE TITLE
Help with the application icon

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1083]
I have one icon for the application. And I want to use it everywhere. By whatever name, with some expansion and what size should I save the image in the build folder?
I tried to keep it in size 32x32 as `build/icon.ico`. But in Windows icon blurred, and Ubuntu in its place a question mark.

**Comment by noahbenham** [comment]
The electron-builder [options documentation](https://github.com/electron-userland/electron-builder/wiki/Options) has some useful information about defaults and how to configure custom paths if you need.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder#quick-setup-guide 


Size is no specified — I will fix it, for please see linked real app example. 256x256 for wn and 512 for mac.
