### ISSUE TITLE
How to pin program to taskbar after install in Windows?

### ISSUE THREAD

**Issue by ethanwillis** [electron-userland/electron-builder#1084]
* **10.17.3**: 

* **Squirrel.Windows**: 

So, I've successfully generated an exe and nupkg for my project. It installs fine and creates a shortcut on my users desktop. However, I have a requirement to pin a shortcut to the application on the user's taskbar. Is there a way to do this from within electron-builder? I checked all of the options and didn't see anything. I'm not quite sure how to go about this.

**Comment by maczikasz** [comment]
You can do it with the NSIS target, most likely like this:

http://stackoverflow.com/questions/24326685/pin-icons-to-taskbar

**Comment by develar** [comment]
@ethanwillis It will be not implemented for Squirrel.Windows because default target is NSIS and NSIS is better than Squirrel.Windows.

@maczikasz Thanks for link, I will add option to pint programs to task bar for NSIS target.

**Comment by mattlyons0** [comment]
This feature should probably also be tied in with #926 which is still occurring for me (pin is removed on NSIS autoupdate)

**Comment by groovydaz** [comment]
To expand on @maczikasz's reply you can pin the main application by creating a custom NSIS include script in the "build" folder. Simply create the following file with the _customInstall_ macro as follow.

**build\installer.nsh**
```
!macro customInstall
    ${StdUtils.InvokeShellVerb} $0 "$SMPROGRAMS" "${PRODUCT_FILENAME}.lnk" ${StdUtils.Const.ShellVerb.PinToTaskbar}
!macroend
```


That pins the start menu shortcut which is created. Alternatively, you could pin the main program with the following snippet, but I found that when the program launched it would create a secondary icon (separate from the pin).
`${StdUtils.InvokeShellVerb} $0 "$INSTDIR" "${APP_EXECUTABLE_FILENAME}" ${StdUtils.Const.ShellVerb.PinToTaskbar}`

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
