### ISSUE TITLE
Using Amazon S3 for NSIS Auto-Update without SSL

### ISSUE THREAD

**Issue by adamlong5** [electron-userland/electron-builder#1086]
Why does the NSIS auto-updater _require_ SSL? It's [hard-coded](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-auto-updater/src/GenericProvider.ts#L18).

It would be great if we could pass an option in the `publish` options to use `http` instead of `https`. That way, we wouldn't have to go through setting up CloudFront + SSL certificates.

**Comment by develar** [comment]
Amazon S3 provides SSL for alll. https://s3.amazonaws.com/bucket_name Please see https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#GenericServerOptions
