### ISSUE TITLE
Setting "Priority" attribute for .deb packages is not possible

### ISSUE THREAD

**Issue by Sukram21** [electron-userland/electron-builder#1088]
* **Version**: 10.9.3

* **Target**: Linux, `deb`

When I build a `.deb` package with electron-builder, the package has priority _extra_ (visible in the "Details" tab in the package installer dialogue). I haven't found an option to set this value manually (e.g. change it to a more reasonable _optional_). 

More info about Debian priority values: https://www.debian.org/doc/debian-policy/ch-archive.html (_2.5 Priorities_)

**Comment by develar** [comment]
Workaround: `"fpm": ["--deb-priority YOUR_VALUE"]`in the build.linux

**Comment by hleitzell** [comment]
Out of curiousity, how would you pass that in as extra metadata?

**Comment by develar** [comment]
--em.build.linux.fpm
