### ISSUE TITLE
NSIS Updater SHA2 checksum mismatch exception

### ISSUE THREAD

**Issue by mattlyons0** [electron-userland/electron-builder#1090]
* **Version**: 11.1.1

* **Target**: Windows NSIS (with autoupdater)

If the SHA2 checksum in latest.yml doesn't match that of the file the following window pops up. Would it be possible to catch this and throw the 'error' event instead? I'm using the generic provider.
![Error Message](http://i.imgur.com/9qHE9AU.png "Error Message")

**Comment by develar** [comment]
Please specify version of electron-auto-updater? Do you use latest 0.10.0?

**Comment by mattlyons0** [comment]
Yes

**Comment by develar** [comment]
Are you sure that old version (that tried to update) uses latest `0.10.0`?

Ok, I will check this case manually.

**Comment by mattlyons0** [comment]
Yeah I just double checked right now

**Comment by mattlyons0** [comment]
Also if you kill the webserver while downloading
![error](http://i.imgur.com/XLrorw6.png "error")

Not sure if you can do anything about this one (without putting in more time than its worth) as it gives no useful informatino except Error being thrown somewhere... Fixing the one above might fix this one though.

**Comment by develar** [comment]
Fixed in 0.10.1

**Comment by develar** [comment]
All piped stream errors now are handled — promise will be rejected.
