### ISSUE TITLE
MAS build crashes

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#1091]
* **8.5.3**: 

* **Mas, Windows, Linux**: 

Hello. I'm using 8.5.3 version because it has a fix for [#897](https://github.com/electron-userland/electron-builder/issues/897) issue. But in the elder versions "electron-macos-sign" dependency was returned to the elder version (now it is "~1.4.0" in 10.17.3 builder version) and the bug is actual again. The mas build is crashing in the last version of the builder, but there are a lot of awesome features like NSIS and Snap  ((((((

**Comment by develar** [comment]
@sagorshkov Это не проблема electron-builder, а изменение в Apple политике подписей приложения, смотри пожалуйста ответ https://github.com/electron-userland/electron-osx-sign/pull/105#issuecomment-260211431

> This means that, going forward, distribution builds of Mac apps cannot be run directly; they are for submitting to iTunes Connect for app review only.

**Comment by develar** [comment]
@sagorshkov Discussion continued in the #897. Thanks for bug report. We definitely should somehow state current situation.
