### ISSUE TITLE
Differentiate Uninstall from Update (NSIS)

### ISSUE THREAD

**Issue by McPo** [electron-userland/electron-builder#1092]
10.5.0

NSIS

Ive created a custom NSIS script to prompt the user as to whether or not to remove the User Data.
I used the 'customUnInstall' macro. 

However when updating the application, customUninstall macro is called. Which results in the user being asked if it wants to wipe user data when updating. 

Instead a customUpdate macro should be called.

Related: #528 #885

**Comment by McPo** [comment]
This can be resolved by wrapping any such code in:

```
${IfNot} ${Silent}
${endIf}
```

I realise my initial request is unreasonable, as you would need to define when customUpdate would be called. (It would likely be called at the end of an install, not during during the installation phase).

Also general question. I appear to be getting an installation window when updating, was this not originally silent?

**Comment by develar** [comment]
You can detect is it auto update — https://github.com/electron-userland/electron-builder/blob/43add64ebf0943287858301b334dac8b28aee770/packages/electron-builder/templates/nsis/oneClick.nsh#L25

**Comment by develar** [comment]
> Ive created a custom NSIS script to prompt the user as to whether or not to remove the User Data.

PR welcome ;)

**Comment by JassiSingh08** [comment]
> 10.5.0
> 
> NSIS
> 
> Ive created a custom NSIS script to prompt the user as to whether or not to remove the User Data. I used the 'customUnInstall' macro.
> 
> However when updating the application, customUninstall macro is called. Which results in the user being asked if it wants to wipe user data when updating.
> 
> Instead a customUpdate macro should be called.
> 
> Related: #528 #885

hey I know its far from late but can you share your script? Iam getting the exact problem of deleting items even on update on my script as well
