### ISSUE TITLE
Possible to make DMG install MyApp.app in `~/Applications`? (for AutoUpdater)

### ISSUE THREAD

**Issue by hhff** [electron-userland/electron-builder#1093]
* **Version**: `7.15.2`

* **Target**:  OS X

Hi!  I'm struggling with the permissions issue for `autoUpdater` on MacOS, documented here:
https://github.com/atom/atom/issues/2860
https://github.com/electron/electron/issues/6345
https://github.com/Squirrel/Squirrel.Mac/issues/131

It appears from https://github.com/atom/atom/issues/2860#issuecomment-160476155 and https://github.com/Squirrel/Squirrel.Mac/issues/131#issuecomment-160478454 that installing the app into the User's application folder (`~/Applications`) will solve the issue.

I noticed that's what GitHub Desktop does (I believe that's an electron app).

Is this possible with Electron Builder?

Thanks!  hx

**Comment by develar** [comment]
GitHub Desktop distributed as zip, not as dmg. You can set mac target to `zip`. `--mac zip` Or in config: `"mac": {"target": ["zip"]}` https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-target

Or, you can change /Applications link in the DMG to user home — http://stackoverflow.com/a/3436104 Probably, electron-builder will do it for you. I will invesigate.

**Comment by hhff** [comment]
Thanks @develar - I tried changing the link to `~/Applications`, and the builder errored:

```
uilding DMG
Building macOS zip
TypeError: Cannot read property 'x' of undefined
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/targets/dmg.ts:99:30
    at next (native)
From previous event:
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/targets/dmg.ts:282:24
From previous event:
    at attachAndExecute (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/targets/dmg.js:60:22)
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/targets/dmg.ts:62:5
    at next (native)
From previous event:
    at DmgTarget.build (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/targets/dmg.js:230:11)
    at MacPackager.packageInDistributableFormat (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/macPackager.ts:210:25)
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/macPackager.ts:85:26
From previous event:
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/macPackager.ts:85:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/macPackager.js:170:11)
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/packager.ts:135:22
From previous event:
    at Packager.doBuild (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/packager.js:260:11)
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/packager.ts:103:32
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Packager.build (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/packager.js:212:11)
    at /Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/src/builder.ts:234:33
    at next (native)
From previous event:
    at build (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/builder.js:81:21)
    at Object.<anonymous> (/Users/hhff/dev/SC/light/Code/light/node_modules/electron-builder/out/build-cli.js:66:41)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/hhff/.node/bin/npm" "run" "package"
npm ERR! node v6.4.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! the-light-phone@0.1.0 package: `npm run build && build --publish never`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the the-light-phone@0.1.0 package script 'npm run build && build --publish never'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the the-light-phone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && build --publish never
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs the-light-phone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls the-light-phone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hhff/dev/SC/light/Code/light/npm-debug.log
```

**Comment by kgcbhfoj1** [comment]
**Workaround 1.**  If you want to install to ~/Applications then [Homebrew](http://brew.sh/) Cask is your friend.  Atom's auto-updater will then work from here forward.
`brew cask install --appdir="~/Applications" atom`

**Workaround 2.**  If you can live without Atom's auto-update and are prepared to head to the terminal when you need to update the Atom editor, use brew to install to /Applications:
`brew cask install --appdir="/Applications" atom`
 and run the following every few weeks:
`brew cask reinstall --appdir="/Applications" atom`
Having lived with the frustration of #2860, I have found this to be the easiest way.  Homebrew Cask is awesome for other apps (including `brew cask install --appdir="/Applications" github-desktop`).

IMHO, rebuilding the installer to install to ~/Applications by default is going in a non-standard direction.  Effort would be better spent on the root cause of [atom/atom#2860](https://github.com/atom/atom/issues/2860) for both Atom and for the greater good of all other Electron/Squirrel based apps.

**Comment by hhff** [comment]
Thanks @kgcbhfoj1 - however my issue is not related to Atom - this is for an end user application, and thus I agree!  We should fix squirrel once and for all.

**Comment by maczikasz** [comment]
Hello @hhff did you find any solution for this problem? I am currently facing the same issue, in the exact same situation

**Comment by hhff** [comment]
@maczikasz no unfortunately.  Squirrel needs a bunch of work and our app had to launch.  I quoted our client on the cost for "fixing squirrel" but they didn't wanna go that way.

Currently we just brick the app when there's a new version and force the user to manually update.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by sangeeth96** [comment]
@develar Is it possible to fix this within electron-builder itself? My naive assumption is that the following line can be tweaked to make this work: https://github.com/electron-userland/electron-builder/blob/ffa2a4e8328275fe03ec408b6c9909694bc7ae10/packages/dmg-builder/src/dmg.ts#L306

If `entryPath` starts with `~`, we do the same thing. This is an issue for the product I'm working on because access to `/Applications` is restricted by IT. I'm not sure if there are any other implications for this but if my direction is right, I can help out with this and maybe you can provide some pointers as well.

**Comment by develar** [comment]
@sangeeth96 Nope, it is not possible. DMG it is not executable file, it is just image. It is possible with `pkg`, but I don't recommend it for general use case.

**Comment by sangeeth96** [comment]
I see. If you could, could you answer just two questions—out of curiosity:

1. The line I referred to, seems to cause the `/` to get prepended when I give a path like `~/Applications`. When I do an `ls` inside the DMG volume, I get the following:
    
    ```
    lrwxr-xr-x  1 sangeeth.s  FLOCK\Domain Users    15B Mar 10 18:37 Applications -> /~/Applications
    drwxr-xr-x  3 sangeeth.s  FLOCK\Domain Users   102B Mar 10 18:11 Flock.app
    ```
    Based on this, shouldn't conditionally checking and not prepending `/` work here?
2. Is there a workaround here to be able to refer to a user's home directory? Maybe expand env variables?

**Comment by matthewpflueger** [comment]
> @develar I see. If you could, could you answer just two questions—out of curiosity:
> 
> 1. The line I referred to, seems to cause the `/` to get prepended when I give a path like `~/Applications`. When I do an `ls` inside the DMG volume, I get the following:
>    ```
>    lrwxr-xr-x  1 sangeeth.s  FLOCK\Domain Users    15B Mar 10 18:37 Applications -> /~/Applications
>    drwxr-xr-x  3 sangeeth.s  FLOCK\Domain Users   102B Mar 10 18:11 Flock.app
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Based on this, shouldn't conditionally checking and not prepending `/` work here?
> 2. Is there a workaround here to be able to refer to a user's home directory? Maybe expand env variables?

@sangeeth96 Did you ever figure out a solution to this?
