### ISSUE TITLE
Docs: Conflicting Default Setting

### ISSUE THREAD

**Issue by mattlyons0** [electron-userland/electron-builder#1094]
[https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-warningsAsErrors](https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-warningsAsErrors)

> | warningsAsErrors | <a name="NsisOptions-warningsAsErrors"></a><p>**Defaults** to <code>false</code>.</p> <p>If <code>warningsAsErrors</code> is <code>true</code> (**default**): NSIS will treat warnings as errors.</p> <p>If <code>warningsAsErrors</code> is <code>false</code>: NSIS will allow warnings.</p>
>  | menuCategory | <a name="NsisOptions-menuCategory"></a>Whether to create submenu for start menu shortcut and program files directory. Defaults to `false`. If `true`, company name will be used. Or string value.

The top statement and default next to the true condition conflict.

**Comment by develar** [comment]
`menuCategory` is not created by default.

`warningsAsErrors` fixed, thanks.
