### ISSUE TITLE
Advanced file copying not supported for "files". Why?

### ISSUE THREAD

**Issue by iMoses** [electron-userland/electron-builder#1096]
* **Version**: 10.17.3

* **Target**: Linux (deb)

I have a shared directory that contains a bunch of common files that we use in all our applications, not just electron. I would like to use it and include it in my code using the build configuration and I noticed that the feature is only supported for extra files and resources but not for the application files configured by the build. 
I know I can create my own build script that will copy the files, pack the application, then delete them again, but I was wondering why isn't this feature supported?
```
{
  "from": "../../applications/shared",
  "to": "shared",
  "filter": ["**/*"]
}
```

I also tried simply adding the path to the "files" property but it just doesn't work. I assumed it's because the path is external to the app directory.

```
"files": [
  "**/*",
  "../../applications/shared",
  "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples,*.d.ts}",
  "!**/node_modules/.bin",
  "!**/*.{o,hprof,orig,pyc,pyo,rbc}",
  "!**/._*",
  "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,test,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"
]
```

**Comment by develar** [comment]
Will be supported. For now, please create symlink — it is supported in the just released 11.2.0. E.g. create symlink project dir/foo to your shared resources dir.

**Comment by iMoses** [comment]
That's awesome, thanks! Using a symlink with 11.2.0 worked like a charm.
When should we be expecting for the support as part of the `package.json` configuration?
Is it somewhere down the line or is it already planned for a specific version?

**Comment by develar** [comment]
This feature looks not boring for me and not related to Windows — so, feel free to ping me if it will be not implemented in 2 weeks.

**Comment by iMoses** [comment]
Will do ;)

**Comment by develar** [comment]
BTW — All default ignores are added in any case — you don't need to repeat it if you configure own patterns. I will fix docs.

**Comment by iMoses** [comment]
@develar, Ping?
Was there any progress regarding this feature?
Thanks

**Comment by develar** [comment]
Will be fixed in one week as part of electron-compile support.
