### ISSUE TITLE
Error: did not pass validation: code failed to satisfy specified code requirement(s)

### ISSUE THREAD

**Issue by quanglam2807** [electron-userland/electron-builder#1098]
* **Version**: 11.1.1

* **Target**: darwin

autoUpdater returns:
```
Update error: Code signature at URL file:///Users/lamqu01/Library/Caches/com.webcatalog.app.ShipIt/update.zxHBM1P/WebCatalog.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

Squirrel/Squirrel.Mac#160 suggests to use codesign but both .app files returns same certificate.
Version 2.3.0
```
Quangs-MacBook-Pro:shit lamqu01$ codesign -d -v -r - ./23.app
Executable=/Users/lamqu01/Downloads/shit/23.app/Contents/MacOS/WebCatalog
Identifier=com.webcatalog.app
Format=app bundle with generic
CodeDirectory v=20200 size=210 flags=0x0(none) hashes=1+3 location=embedded
Signature size=8906
Timestamp=Jan 4, 2017, 11:05:00 PM
Info.plist entries=21
TeamIdentifier=FVFM95DDPG
Sealed Resources version=2 rules=12 files=18
host => identifier "com.apple.env" and anchor apple
designated => identifier "com.webcatalog.app" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = FVFM95DDPG
```

Version 2.4.0
```
Quangs-MacBook-Pro:shit lamqu01$ codesign -d -v -r - ./24.app
Executable=/Users/lamqu01/Downloads/shit/24.app/Contents/MacOS/WebCatalog
Identifier=com.webcatalog.app
Format=app bundle with generic
CodeDirectory v=20200 size=210 flags=0x0(none) hashes=1+3 location=embedded
Signature size=8906
Timestamp=Jan 8, 2017, 3:14:43 AM
Info.plist entries=21
TeamIdentifier=FVFM95DDPG
Sealed Resources version=2 rules=12 files=18
host => identifier "com.apple.env" and anchor apple
designated => identifier "com.webcatalog.app" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = FVFM95DDPG
```

What should I do?

**Comment by quanglam2807** [comment]
It seems to happen when I started building 2.4.0 with electron-builder 11.x instead of 10.17.2. 

Build 2.2.0 > Build 2.3.0 works normally (both uses 10.17.2).
Build 2.2.0 > Build 2.4.0 & Build 2.3.0 > Build 2.4.0 (only 2.4.0 uses 11.x) both fail.

So I think there might be something wrong with 11.x (including 11.2.0). You can check my build script https://github.com/webcatalog/desktop/blob/master/builder-mac.js

**Comment by quanglam2807** [comment]
I discovered that it happened because when I started using custom build script instead of CLI command, the app architecture is generic instead Mach-O thin (x86_64). But I still don't know what is wrong with my build script

```
const builder = require('electron-builder');
const execFile = require('child_process').execFile;

/* eslint-disable no-console */

// Promise is returned
builder.build({
  targets: builder.Platform.MAC.createTarget(),
  devMetadata: {
    build: {
      appId: 'com.webcatalog.app',
      mac: {
        category: 'public.app-category.utilities',
      },
      asar: true,
      asarUnpack: ['plugins/**'],
      files: ['!plugins/win32/**/*'],
      afterPack: ({ appOutDir }) => {
        // Use alternative exec to allow launching multiple instance of WebCatalog

        const fakeExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog`;
        const realExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog_Real`;

        return new Promise((resolve, reject) => {
          execFile('./build/generate_alt_exec.sh', [
            fakeExecPath,
            realExecPath,
          ], (err, stdout) => {
            console.log(err);
            console.log(stdout);

            if (err) {
              reject(err);
              return;
            }

            resolve();
          });
        });
      },
    },
  },
})
.then(() => {
  console.log('build successful');
})
.catch(console.log);
```

**Comment by quanglam2807** [comment]
Update: it's related to the afterPack script.

**Comment by DxCx** [comment]
@quanglam2807 can you eleborate more? i'm having similar issues..

**Comment by quanglam2807** [comment]
@DxCx 

```
 const fakeExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog`;
const realExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog_Real`;
```

Because of this code, the main process will be `fakeExecPath` but Squirrel needs to update `realExecPath`. But because it gets the file name from the main process, it tries to update the wrong binary and fails.

**Comment by DxCx** [comment]
Yeah im doing something similar to that, can you give me some hints on how did you fix it eventually?

**Comment by quanglam2807** [comment]
@DxCx I did not manage to fix it at all. I removed auto-update support :(.

**Comment by DxCx** [comment]
Alright thanks, ill update back if i find something new .. :)

**Comment by DxCx** [comment]
ok so some updates:
 - My first try was to replace the my shell script with native compiled mach-o exectuable
    this caused the bundle to be shown as "app bundle with Mach-O thin (x86_64)" instead of "app bundle with generic"
    but auto updates still did not work. (same error)
  - next, i opened `.../Contents/_CodeSignature/CodeResources` and took the automatic designated requirement set for my app, for example: `<string>identifier "....." and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = .....</string>`
and created a new requirements file named `requirements.rqset` under `resources` (buildResources)
inside this file i've set the requirement without the identifier, like so:
`designated => anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = .....`
then, under package.json mac.requirements i've set `requirements.rqset`
current state is that the app accepts the update (Even if i revered the native mach-o patch),
so it downloads it, but then it just quits the application.

i'm gonna continue working on this from time to time and give more updates.

**Comment by develar** [comment]
For what do you need to run several instances of app?

**Comment by DxCx** [comment]
i don't,
but i do have my own prelauncher before the electron app.

**Comment by develar** [comment]
For what?

**Comment by quanglam2807** [comment]
@develar My app is [webcatalog](https://github.com/webcatalog/) which allows users to run web apps as independent apps. Those apps use the same binary with the main Electron app, except that they are called with additional command-line parameters. 

```WebCatalog.app/Contents/MacOS/WebCatalog``` will launch the main Electron app.
```WebCatalog.app/Contents/MacOS/WebCatalog --url=https://messenger.com``` will launch the Facebook Messenger app.

It works similarly to the way Google implements Chrome Apps.

**Comment by develar** [comment]
Do you want to see several different icons in the Dock on macOS, right?

**Comment by ibash** [comment]
Just noting that I ran into this as well, using afterPack to replace the binary. My use case was to enable the `--inspect` flag for internal testing.
@quanglam2807 did you determine this was a problem with squirrel? Or this repo?

**Comment by quanglam2807** [comment]
@ibash I would say Squirrel.
