### ISSUE TITLE
Please update README.md to reflect the correct location of "remoteReleases" in package.json

### ISSUE THREAD

**Issue by ancrist** [electron-userland/electron-builder#1099]
* **10.9.2**: 

* **Windows x64**: 

The README places the "remoteReleases" field in the "build.win.squirrelWindows" node in the development package.json. This, however, does not work ( started a local http server that serves the older installers from a folder, and there are no requests logged from electron-builder) as no delta package is generated.

If on the other hand I place "remoteReleases" in the "build.win" node, then it works and delta packages are created.

**Comment by develar** [comment]
`remoteReleases` should be in the `build.squirrelWindows` As far I see, docs is correct.
