### ISSUE TITLE
App is installed under "Programs Files (x86)" on windows even when specifying --arch=x64

### ISSUE THREAD

**Issue by justinmchase** [electron-userland/electron-builder#11]
It appears to be getting the right binaries for electron but it seems to be putting it into the wrong location for some reason.

The code in the template is this: `InstallDir "$PROGRAMFILES\${APP_NAME}\"`

Which seems correct to me, so I'm not sure why this is happening. Filing this bug for posterity but I will investigate.

**Comment by tengyifei** [comment]
Should use `$PROGRAMFILES64`

**Comment by joeferraro** [comment]
http://nsis.sourceforge.net/Reference/$PROGRAMFILES

**Comment by develar** [comment]
Since 3.0 we support only Squirrel.Windows.
