### ISSUE TITLE
nsis to use productName rather than name for install path

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#1100]
- electron-builder@11.2.0
- win32

`pacakge.json`
```json
{ 
  "name": "myapp",
  "productName": "My App",
  "author": "My Company",

...
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": true,
      "runAfterFinish": false
    },
```

On selecting per machine install, the default path is:
```
C:\Program Files (x86)\My Company\myapp
```
Whereas I was hoping for:
```
C:\Program Files (x86)\My Company\My App
```

I simply want to do this to match the existing installers of My Company.

Obviously `productName` can contain characters which are not valid for use in file paths, so this functionality as a default might not be a good idea.

**Comment by develar** [comment]
Option will be added this week. It was decided to use `name` because `productName` is not safe and suitable for number of users..

**Comment by timfish** [comment]
>  It was decided to use name because productName is not safe and suitable for number of users

Thanks. Guessed as much!

**Comment by mastergberry** [comment]
Definitely wanted :) Thanks

**Comment by mastergberry** [comment]
@develar any quick update on this? A much desired feature before we push out our installer to users in the next week or so.

**Comment by develar** [comment]
I don't want to introduce yet another option. If product name matches `/^[-_0-9a-zA-Z ]+$/`, it will be used instead of safe name (applicable only for perMachine or boring installer).
