### ISSUE TITLE
asar target and prepackaged option support for it

### ISSUE THREAD

**Issue by pauliusuza** [electron-userland/electron-builder#1102]
* **electron-builder 11.2.3**: 

* **OSX**:

Builder crashes when trying to package app with --prepackaged command with the following error: 

```
Error: ENOENT: no such file or directory, 
open '/Users/pro/repository/desktop_app/dist/mac/Desktop.app/Contents/Resources/app-update.yml'
at /Users/pro/repository/desktop_app/node_modules/electron-builder/src/macPackager.ts:101:13
```

In my package.json:
`{"dist": "npm run compile && build --prepackaged ./asar"}`
where `./asar` is the folder containing app.asar, core.asar and node_modules.asar files

What I want is to be able to point electron-builder into a folder containing app.asar and it would package the apps for distribution.

**Comment by develar** [comment]
@pauliusuza Crash fixed. But `prepackaged` is not for your use case. @wojtkowiak Could you please share your experience — how do you us already packed asar files?

**Comment by pauliusuza** [comment]
So I found a temporary workaround by packing app.asar through the electron-builder, and including the remaining .asar files through extraResources key:

```
"build": {
    "asar": true,
    "files": [
      "!**",
      "index.js",
      "package.json"
    ],
    "extraResources": [
      {
        "from": "asar",
        "to": ""
      }
    ]
    ...
}
```

However, it would be really great if electron builder would have a feature which would simply pack the whole folder and it's contents if it has app.asar file without running additional checks.

`build --fromAsar ./path/to/folder/containing/app.asar_file/`

Would you consider adding this feature?

**Comment by develar** [comment]
@pauliusuza It is already supported (#759)

> without running additional checks

What error do you get?

**Comment by wojtkowiak** [comment]
I am not sure what this problem is actually about.
@pauliusuza if you are packing your app to asars yourself you just need to turn off asar packing in electron-builder, the rest should work. I am using `electron-builder` programmatically so I am just setting `asar` to false in build options.

**Comment by pauliusuza** [comment]
@develar it's checking for package.json and index.js files, so if I simply point it to a folder with asar files the build step fails.

**Comment by develar** [comment]
@pauliusuza So — you have some folder where asar files are located (`app.asar` is required) and just want to pack it into `.app` or `.dmg` or any other electron-buidler target?

Just curious — why electron-builder is not suitable to produce required asar files?

**Comment by pauliusuza** [comment]
@develar yes. Mostly for flexibility - we want to separate the build process and packaging process. Asar files would be build in one CI process and stored on a cdn, and packaging would run in another process on demand.

**Comment by develar** [comment]
> Asar files would be built in one CI process

Using electron-builder? Or using asar tool programmatically? I just want to understand to be sure that implemented solution will be the best solution (not workaround).

**Comment by pauliusuza** [comment]
Sure, thanks.

1) The first step of the process would be running asar tool programmatically (through gulp or npm script) and pack the required files into .asar archives, it would then store those .asar files into a CDN. This would run on CI on each commit.

2) Second step would be executed on demand. It would fetch the latest .asar files from CDN, store them into a folder, apply required customization / branding, and run electron builder to pack all of this into a distributable format.

**Comment by develar** [comment]
Got it. So:

1. New target `asar` will be added. electron-builder will just pack your app into `app.asar`.
2. `--prepackaged` will detect — is it fully prepackaged directory (has electron files) or not.

**Comment by pauliusuza** [comment]
@develar thanks, that sounds good

**Comment by pauliusuza** [comment]
So just a note for `--prepackaged /dir`
If app.asar already exists in the /dir, then it should check for existence of the package.json and index.js files inside the app.asar file, and not in the /dir folder itself.

**Comment by pauliusuza** [comment]
@develar I posted a [50$ bounty](https://www.bountysource.com/issues/40828634-asar-target-and-prepackaged-option-support-for-it) for this.

**Comment by develar** [comment]
Solution: just use electron-builder in a standard way. But your project directory must contain:

* app.asar and other files.

If electron-builder cannot find package.json in the project directory, app.asar will be used a source of project metadata.

Caveats:
* two-package.json structure is not supported. Because no dev package.json in the asar.app.
* if you build deb, you must specify `homepage` in the package.json Default discovery doesn't work because no git repository

This comment in progress — I will update as soon functionality is pushed/updated.

**Comment by develar** [comment]
Issue closed — please try 12.3.0.

> I posted a 50$ bounty for this.

If you want, you can donate. https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=W6V79R2RGCCHL

**Comment by develar** [comment]
Asar target — if need, please open separate issue.

**Comment by pauliusuza** [comment]
Sorry, this does not work.

How can i specify project directory through options and point it to a subfolder containing asar files?
Project folder contains files which should not be packaged, and there is no way to exclude them.

**Comment by develar** [comment]
> How can i specify project directory through options

current working directory or set explicitly using `--project` CLI.

**Comment by pauliusuza** [comment]
We are using electron-builder programmatically, not through CLI - is it possible to add a config parameter for the project directory?

**Comment by develar** [comment]
Set `projectDir` https://github.com/electron-userland/electron-builder/blob/60e1406a467b9aa7228936830d8ebda1570c7a1e/packages/electron-builder/src/packagerApi.ts#L11 to custom.

**Comment by pauliusuza** [comment]
Can't get this to work.

```
builder.build({
    appId: 'com.test.asar',
    projectDir: '/Users/pro/repository/test-project/temp/asar'
})
```

Error: Application entry file "index.js" in the "/Users/pro/repository/test-project/dist/mac/Test Project.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.

```
// index.js file exists:
$> asar list /Users/pro/repository/test-project/temp/asar/app.asar

/index.js
/package.json
```

Additional files in the asar folder were not copied to the Resources

**Comment by pauliusuza** [comment]
Running this in cli
```
build --project temp/asar
```

TypeError: Cannot read property 'directories' of undefined
at /Users/pro/repository/test-project/node_modules/electron-builder/src/packager.ts:122:68

**Comment by pauliusuza** [comment]
Would it not be simpler just to ignore the app folder packaging step if a specific flag is set, so we can include the .asar files via extraFiles / extraResources?

**Comment by develar** [comment]
@pauliusuza Is it possible to send me your directory with asar files to test?

**Comment by pauliusuza** [comment]
@develar I will send you an email shortly

**Comment by pauliusuza** [comment]
Thanks @develar for checking out the code. Leaving a comment here if someone has the same issue (this should be documented somewhere eventually)

Important bit is to specify the electronVersion and projectDir parameters.
Working example:

```
import * as builder from 'electron-builder';
let config = {
    config.appId: 'com.asar.test',
    directories: {
        buildResources: './build_resources'
    },
    electronVersion : '1.5.0'
}
builder.build({
    projectDir: './path/to/folder/with/asar/files',
    config: config,
}).then(() => {
    console.log('done');
}).catch((error) => {
    console.log(error);
})
```

**Comment by yansenlei** [comment]
@pauliusuza Have you successfully build a separate app.asar?
