### ISSUE TITLE
Separate build config from package.json

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#1109]
* **Version**: latest
* **Target**: mac, win, linux

I think it might be nice thing to consider to separate the `build` from `package.json` to a separate file, e.g. `build.json`. It could be optional in a way that either `build` key in `package.json` or `build.json`  would apply if present, similar to what `ava` has. What do you think?

It could make large `package.json`s more readable. If we already have 250 lines in `package.json` another 50-100 lines for build config make it quite unreadable.

I did a quick search in issues and couldn't find anything related, so sorry if this has already been discussed here.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/971#issuecomment-264701725

What do you think about `electron-builder.yml`?

**Comment by jakubzitny** [comment]
Yeah that would be great 👍 

Haven't really seen the YAML usage in JS world a lot, but it has its advantages. I would support json as well though. People will be able to migrate between their "build" part in `package.json` and the new extra file as they wish.

**Comment by develar** [comment]
You can write JSON in the yaml, you don't need to learn new syntax.

**Comment by jakubzitny** [comment]
Did not realize that, thanks. :)

**Comment by develar** [comment]
I am going to add support for `json` and `json5` to be sure that users are happy :)

**Comment by jakubzitny** [comment]
Hi @develar, when is this going to be available in npm`? I have `11.4.4` and I am getting `Unknown argument: config`.

**Comment by develar** [comment]
Currently no cli arg, just create file electron-builder.yml to n the project root.

**Comment by jakubzitny** [comment]
Allright, that does work.

**Comment by jakubzitny** [comment]
Hi @develar, are there any plans to add `--config` parameter so the config YAML can have different locations?
