### ISSUE TITLE
Support CFBundleDocumentTypes for macOS build

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#1110]
* **Version**: latest
* **Target**: mac, win, linux

I can set up a protocol scheme for macOS build. That should be translated into Info.plist of built app. There is another similar thing that allows users to drop files of certain types on the app icon. This is specified in [CFBundleDocumentTypes](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-101685) where you can add types of files you support.

Have you considered this before / do you think you could support this / are you open for PR introducing this support?

Thanks

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#buildfileassociations :)

**Comment by simonw** [comment]
> https://github.com/electron-userland/electron-builder/wiki/Options#buildfileassociations :)

It looks like the wiki doesn't exist any more. I think this is the relevant documentation now: https://www.electron.build/configuration/configuration.html#PlatformSpecificBuildOptions-fileAssociations
