### ISSUE TITLE
asar pack error when child process using a java (jar) file

### ISSUE THREAD

**Issue by phamtrong204** [electron-userland/electron-builder#1113]
* **Version**: 10.12.0

* **Target**: mac/win (may be on other)

I'm using a child process to recording keyboard and mouse event: [https://github.com/tomzx/gkm](https://github.com/tomzx/gkm)

gkm event is ok on debug or building app with `"asar": false`, but with `"asar": true`(default), event not firing.
I have testing with `"asarUnpack": "node_modules/gkm/*"`, but it not working too.

**Comment by develar** [comment]
Sorry for late answer. Have you identified issue?

**Comment by HealthD** [comment]
+1

**Comment by JonathanHeinz** [comment]
@develar same problem @ my project, i can't spawn a jar from asar. Do you know any solution?

**Comment by mahhov** [comment]
Similar, am using another dependency that delegates to a java jar. 
Running with node, or building with `"asar": false,` have no issues.
Running with `"asar": true,` results in:
`Error: Unable to access jarfile /tmp/.mount_clipbo42UUV2/resources/app.asar/node_modules/node-key-sender/jar/key-sender.jar`

**Comment by phamtrong204** [comment]
Sorry, i forgot to follow it.
In my case, it seems like Java can't handle the asar file as a folder, so it can't be access to jar file inside asar file.
This is my solution: copy jar file from asar file to a new real folder(not folder in asar) and execute it instead of executing direct inside asar file.
Hope it can help you.

**Comment by Randyshu2018** [comment]
> Sorry, i forgot to follow it.
> In my case, it seems like Java can't handle the asar file as a folder, so it can't access to jar file inside asar file.
> This is my solution: copy jar file from asar file to a new real folder(not folder in asar) and execute it instead of executing direct inside asar file.
> Hope it can help you.

hi,I set extraFiles with build config,and it can access jar file normally,but it caused a error when signing. below is error description:
'code object is not signed at all
In subcomponent: /opt/shurenwei/development/caic-cloud-platform/dist/mac/CAIC云平台.app/Contents/fabricServer-0.0.1-SNAPSHOT.jar'

**Comment by AJAndrei** [comment]
> Similar, am using another dependency that delegates to a java jar.
> Running with node, or building with `"asar": false,` have no issues.
> Running with `"asar": true,` results in:
> `Error: Unable to access jarfile /tmp/.mount_clipbo42UUV2/resources/app.asar/node_modules/node-key-sender/jar/key-sender.jar`

Have you found a solution to this? I am facing the same:
`Error: Unable to access jarfile C:\Users\..\AppData\Local\reader\app-0.1.0\resources\app.asar\node_modules\node-key-sender\jar\key-sender.jar`.
