### ISSUE TITLE
No launcher icon with Linux appimage build (icns errors)

### ISSUE THREAD

**Issue by KarlJakober** [electron-userland/electron-builder#1115]
* **Version**: next

* **Target**: linux

I originally had issues building a linux appimage using an icns files, (same issues others have had, could not detect my 512x512x32 file in the icns file). 

`Added to ISO image: file '/usr/share/icons/default/128x128/apps/testapp.png'='/tmp/electron-builder-oP7Hww/0-1-linux.iconset/icon_128x128x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/256x256/apps/testapp.png'='/tmp/electron-builder-oP7Hww/0-1-linux.iconset/icon_256x256x32.png'
xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-oP7Hww/0-1-linux.iconset/icon_512x512x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
`

Ive switched to using png files in my build/icons folder as you do in your onshape app. The appimage builds successfully with no errors, and the installer has an icon, however the launcher does not have an icon. I have included a 48x48.png file in that folder which seems to be the required size for the ubuntu launcher.

![screenshot from 2017-01-13 16-45-01](https://cloud.githubusercontent.com/assets/140006/21950446/aa88bb54-d9af-11e6-8bb0-b2cd318bc5fd.png)

Any advice is greatly appreciated, you do great work develar

**Comment by KarlJakober** [comment]
you mention here
https://github.com/electron-userland/electron-builder/issues/748#issuecomment-246580769
that you should not run the app through the appimage. When you first run the appimage it asks to create the icon on your launcher, which creates it with the question mark. there has to be a method around this rather than running it through the launcher

**Comment by develar** [comment]
Duplicates #748 

> there has to be a method around this rather than running it through the launcher

Yes, it depends in AppImage. Probably I will find time to fix it this year.
