### ISSUE TITLE
build.linux custom .desktop entries

### ISSUE THREAD

**Issue by Quacky2200** [electron-userland/electron-builder#1117]
electron-builder version 11.2.6

64 bit and 32 bit (primarily linux) targets

[Referring to my issue](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/25#issuecomment-272626055), I would like to be able to create custom entries for my .desktop file. Currently I'm wanting to use unity right-click menu items such as...

```
[Desktop Action PlayPause]
Name=Play/Pause
Exec=dbus-send --type=method_call --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

[Desktop Action Next]
Name=Next
Exec=dbus-send --type=method_call --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

[Desktop Action Previous]
Name=Previous
Exec=dbus-send --type=method_call --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
```

**Comment by PhilippeAssis** [comment]
I have a similar problem.
We need to create an option to the package.json so that attributes like [desktop action] can be added to * .desktop

I suggest something like:
```javascript
"desktop" : {
     "[Desktop Action]" : {
          "Name" : "...",
          "Exec" : "..."
     }
}
```

**Comment by PhilippeAssis** [comment]
@Quacky2200  A non-trivial and momentary solution may be this:
In the last "desktop" property add:
`[Desktop Action PlayPause]\nName=Play/Pause\nExec=...`

Example

```javascript
"desktop" : {
     "category" : "Audio\n\n[Desktop Action PlayPause]\nName=Play/Pause\nExec=..."
}
```

The result will be something like this:
```
category=Audio

[Desktop Action PlayPause]
Name=Play/Pause
Exec=...
```

**Comment by black-snow** [comment]
Is this still requested?
You could always do this when first starting the app, right?

**Comment by Quacky2200** [comment]
Personally, I don't really need this now.

However it would be best if the option were possible so that others can do the same if they wish

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
