### ISSUE TITLE
latest-mac.json contains https://github.com/undefined/undefined

### ISSUE THREAD

**Issue by salomvary** [electron-userland/electron-builder#1118]
* **Version**: electron-builder@11.2.5

* **Target**: Win, Mac

Using the `"release": "build"` approach with no explicit repo configured in package.json I ended up with a release containing `latest-mac.json` that looks like this:

```
{
  "version": "1.1.7",
  "url": "https://github.com/undefined/undefined/releases/download/v1.1.7/soundcleod-1.1.7-mac.zip"
}
```

See https://github.com/salomvary/soundcleod/releases/tag/v1.1.7

**Comment by develar** [comment]
Please use latest 11.3.1.

**Comment by develar** [comment]
serverless macOS update supported in the [11.3.0](https://github.com/electron-userland/electron-builder/releases/tag/v11.3.0).
