### ISSUE TITLE
DMG - move hidden directories out of view

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#1121]
This is quite low priority as it'll only be noticed by developers and others who have the `AppleShowAllFiles` preference set so that they can see hidden files in Finder.

This means that I/they see all the hidden folders (eg. `.background`, etc) added to the DMG scattered seemingly randomly within the DMG window!

I would be a good idea to position these hidden directories out of view by default.

Check out this [bug](https://c-command.com/forums/showthread.php/4069-How-do-I-keep-hidden-files-and-folders-out-of-view-in-the-DMG-in-an-automated-way) filed for DropDMG for the same reason.

**Comment by develar** [comment]
Actually we already do it, but x/y values were from from ancient ages.

**Comment by timfish** [comment]
I'm still seeing `.VolumeIcon.icns` in the top left when opening the dmg

**Comment by develar** [comment]
@timfish Please provide DMG settings and screenshot.

**Comment by timfish** [comment]
I have no mac or dmg settings (so its using the defaults).

![image](https://user-images.githubusercontent.com/1150298/27691442-4a1c8ce2-5ce4-11e7-83e2-87b163bb08b1.png)

**Comment by develar** [comment]
@timfish `.VolumeIcon.icns` is added to hidden items.
