### ISSUE TITLE
NSIS include functions

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1122]
* **Version**: 11.4.1

* **Target**: Windows

I am trying to write my own "include" script for nsis. I cannot seem to make function definitions though? Inside my macro I have the following:

```
!macro customInstall
  Call Foo
  # ...
!macroend

Function Foo
  # ...
FunctionEnd
```

Keep getting this error though: `warning: install function "Foo" not referenced - zeroing code (0-120) out`

I don't see what I am doing wrong. I tried moving the function into the macro but then it complained to me about having a function in a function.

**Comment by develar** [comment]
Please wrap it into 

```
!ifndef BUILD_UNINSTALLER

!endif
```

**Comment by fedegl** [comment]
@develar What do you need to wrap? the Call to the function? or the function definition?

**Comment by develar** [comment]
The function definition.

**Comment by agjs** [comment]
@develar Was this ever resolved? I'm having the same issue. Simply can't use a function in custom NSIS script at all.

**Comment by zwdgit** [comment]
Encountered the same problem

**Comment by GeorgeFlorian** [comment]
I have the same issues !
It's mind boggling how this hasn't been addressed in 9 whole years !
