### ISSUE TITLE
interface 'platform' doesn't exist

### ISSUE THREAD

**Issue by Quacky2200** [electron-userland/electron-builder#1123]
electron-builder version 11.2.6

64 bit and 32 bit Linux targets

I am building my snap with this configuration
```
...
    "linux": {
      "synopsis": "shortened...",
      "category": "Audio",
      "packageCategory": "GNOME;GTK;AudioVideo;Audio;Player",
      "depends": [
        "libappindicator1",
        "libindicator7",
        "libnotify4",
        "notify-osd",
        "wget",
        "unzip",
        "tar"
      ],
      "target": [
        "AppImage",
        "deb",
        "zip",
        "snap"
      ]
    }
  },
  "snap": {
      "confinement": "devmode",
      "grade": "stable"
  }, ...
```

I had my package reviewed and it has an interface named 'platform' - where did this come from and how do I remove it because it's automatically generated with electron-builder. Do I need to configure my snap differently or is this a bug? 

```
Evan Dandrea evan.dandrea at canonical.com 
Mon Jan 16 09:12:30 UTC 2017

Hi Matthew,

You've set your snap to use the 'platform' interface, but no such interface
exists. If you remove that line and 'unity8', then re-upload, it should
pass review.

Do you recall what you read that referenced a 'platform' interface? If
there's some outdated documentation out there, I'd like to get it fixed.

Let us know if you need any more help, and thanks for snapping Spotify!

```

**Comment by develar** [comment]
1. https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L35

2. https://insights.ubuntu.com/2016/12/08/using-the-ubuntu-app-platform-content-interface-in-app-snaps/

"Using the ‘platform’ plug (content interface) and specifying its default provider (‘ubuntu-app-platform’)"


Bug: this plug should be not added if `ubuntuAppPlatformContent` option is not set.

**Comment by develar** [comment]
Workaround until fixed version is not published: https://github.com/electron-userland/electron-builder/issues/509#issuecomment-269079536

1. edit generated snapcraft.yaml in the `dist/linux-unpacked-snap`
2. run `snapcraft snap` (current working directory must be `dist/linux-unpacked-snap`).

**Comment by Quacky2200** [comment]
Yeah I see that I can edit this, will I need to remove unity7 as well since I'm also removing unity 8?

**Comment by develar** [comment]
Why unity8 is not suitable? unity7 should be here in any case, I think. Please ask why `unity8` is bad.

**Comment by Quacky2200** [comment]
It just doesn't pass the reviewing stage on my snap. I will email them, it may just be that unity8 is not ready for my application?

**Comment by develar** [comment]
`unity8` is removed, `platform` is added only if `ubuntuAppPlatformContent` is specified. Eager to know about is it valid or not.

**Comment by develar** [comment]
Fixed in 11.4.3

**Comment by Quacky2200** [comment]
What is `ubuntuAppPlatformContent` supposed to refer to? Scopes?

**Comment by develar** [comment]
@Quacky2200 Please see docs https://github.com/electron-userland/electron-builder/wiki/Options#SnapOptions-ubuntuAppPlatformContent

**Comment by Quacky2200** [comment]
Thanks.

It looks like they just use it to save space for Qt apps due to Qt being supported mainstream by Ubuntu. Interesting... :+1:

**Comment by develar** [comment]
@Quacky2200 Is is not only Qt, but gconf/gtk/other weird stuff that is required to run electron apps (UI apps). Currently, usability is a nightmare.
