### ISSUE TITLE
electron net request not returning

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1124]
There you add a callback as a second argument to the request call.
Or the electron api does not define such a signature. We should use an event listener.
I should mention that i discovered this because my net requests never return

Also you should mention in the Readme that you require electron >= 1.4.5  because of```electron/net```

Will try and make a quick PR this afternoon

**Comment by develar** [comment]
Not quite understand what do you mean. I test auto update manually on windows and mac and it works for me.

> Will try and make a quick PR this afternoon

👍

**Comment by farfromrefug** [comment]
Sorry let me explain, [here](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-auto-updater/src/electronHttpExecutor.ts#L85), you add the response callback as the second argument. Or apparently it should be an event 'response'.
I am still trying to make it work here.

**Comment by develar** [comment]
@farfromrefug Docs on electron site is not correct. Please see implementation — https://github.com/electron/electron/blob/master/lib/browser/api/net.js#L353

**Comment by farfromrefug** [comment]
Ok actually this is a good news, as it means my problem comes from somewhere else!
Thanks @develar and sorry for the trouble

**Comment by develar** [comment]
@farfromrefug 

1. https://github.com/electron-userland/electron-builder/wiki/Auto-Update#quick-setup-guide
2. Set `DEBUG=electron-builder` and run app (if you use mac) directly in the terminal to see console out — yourApp.app/Contents/MacOS/yourapp
3. Just use IntellIJ IDEA to debug https://blog.jetbrains.com/webstorm/2016/01/webstorm-12-eap-144-3143/ "Debugging Electron applications"
