### ISSUE TITLE
App complains about publishing options when using squirrel on windows.

### ISSUE THREAD

**Issue by ggozad** [electron-userland/electron-builder#1125]
* **Version**: 11.3.0
* **Target**: win32:x64

Using squirrel as the windows target, while the dist builds fine when starting the app throws:
```
Error: Please pass PublishConfiguration object at createClient
```
The above comes from NsisUpdater.setFeedURL.
I expect NsisUpdater to not be invoked since I would like to use squirrel.

**Comment by develar** [comment]
> Error: Please pass PublishConfiguration object at createClient

Well, do not use `electron-auto-updater`. What's wrong?

**Comment by ggozad** [comment]
@develar Ops, I had no idea, didn't understand electron-auto-updater was only for NSIS targets. Perhaps this should be made more clear in the docs?
I also looked at the example but there there are no publishing options and I haven't managed to actually produce an NSIS target.

**Comment by develar** [comment]
> I haven't managed to actually produce an NSIS target.

NSIS is a windows target by default. 

> I haven't managed to actually produce an NSIS target.

You can file issue :)

> Perhaps this should be made more clear in the docs?

Will add.
