### ISSUE TITLE
Generic MacOs provider and unverified certificates

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1126]
If i use the generic provider with my own custom website, the checkForUpdates never returns.
This is because the electron net request never returns.
After investigating this i am almost sure this is due to this error "unable to verify the first certificate".
First thing is that electron net request does not return that error, thus your request don't reject.
I tried using the "rejectUnauthorized"  option which work with node http request, but it does not work with electron request.

Now there are 2 solutions to that:
- drop electron net request for node http/htttps request.
- allow using non secure connection

**Comment by develar** [comment]
Have you tried http://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app/38989441#38989441?

**Comment by farfromrefug** [comment]
@develar just tried it. Does not seem to be triggered with electron net request

**Comment by farfromrefug** [comment]
@develar i can confirm this is a certificate issue. Just created a certificate for my website and now it works!

**Comment by biroplane** [comment]
is there any chance to make the update work with self-certificate?
