### ISSUE TITLE
Windows builds for ia32 and x64 write same file

### ISSUE THREAD

**Issue by robwilkerson** [electron-userland/electron-builder#1127]
* **Version**: electron-builder@7.3.0

* **Target**: Windows (ia32 and x64)

I have a client that's pressing for both 32- and 64-bit apps for Windows. I seem to be able to build for each architecture just fine, but they write to the same file name (e.g. `dist/My App Setup 1.1.1.exe`). When I release a new version, I run all builds at the same time so only one Windows build is actually available since the first one that gets run gets overwritten by the second.

The unpacked contents get created in `dist/win-unpacked/` or `dist/win-ia32-unpacked/`, but both Setup executables get written directly in `dist/` with the same file name.

What can I do to avoid this? Ideally, I'd like the `Setup.exe` files to get written to `dist/win32/My App Setup 1.1.1.exe` and `dist/win64/My App Setup 1.1.1.exe`, but I'll settle for whatever allows me to keep both setup executables.

I don't see a way of customizing the `output` directory in a way that includes the platform and/or architecture in the directory name as a dynamic value. Any thoughts?

**Comment by develar** [comment]
On windows if you use NSIS (default target) you need to distribute the only installer. Not two.

https://github.com/electron-userland/electron-builder/issues/966#issuecomment-271328593

**Comment by develar** [comment]
> 7.3.0

Please use latest 11.
