### ISSUE TITLE
Failure while Building NSIS Installer

### ISSUE THREAD

**Issue by nathanewakefield** [electron-userland/electron-builder#1128]
* **Version**: 11.4.3

* **Target**: win32 x64

I keep trying to build my application, but I get:
Error: C:\Users\HBE Systems\AppData\Local\electron-builder\cache\nsis\nsis-3.0.4\Bin\makensis.exe exited with code 1

I will attach my package.json and npm-debug
![package](https://cloud.githubusercontent.com/assets/9122588/22005649/b8d3cf50-dc2a-11e6-942e-f8f49a806f45.PNG)

[npm-debug.txt](https://github.com/electron-userland/electron-builder/files/709852/npm-debug.txt)

Thanks in advance for your help

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by nathanewakefield** [comment]
So sorry for my lack of knowledge...
How do I do that? I tried running `DEBUG=electron-builder npm run build` but it told me DEBUG is not a known command

**Comment by danielmcq** [comment]
Looks like you're doing it from Windows, so try `set DEBUG=electron-builder && npm run build` instead.

**Comment by nathanewakefield** [comment]
Thanks, that command worked. Here's the output:
[log.txt](https://github.com/electron-userland/electron-builder/files/715057/log.txt)

**Comment by develar** [comment]
Duplicates #1181

Please see https://github.com/electron-userland/electron-builder/issues/1181#issuecomment-275984409
