### ISSUE TITLE
Fork and modify electron-builder

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1132]
* **Version**: 11.4.4

* **Target**: Windows

I am trying to fork the electron-builder project and make a few modifications. I was first having issues with the package.json not having a name/version and now am getting some weird errors about tar packs, addLocalDirectory, and addLocal.

How do i go about trying to include this modified fork of the project into my existing node project? I tried using the git+ssh devDependency but am having no luck as outlined above.

**Comment by develar** [comment]
You need to publish https://github.com/electron-userland/electron-builder/tree/master/packages/electron-builder

**Comment by develar** [comment]
`node test/out/helpers/setVersions.js p` to set package versions.

`node test/out/helpers/setVersions.js` to set dependency versions.

**Comment by RMorgan-Evernote** [comment]
How exactly do you fork and use the fork in your project?
Tried to point to my fork in my package.json
"electron-builder": "https://github.com/RMorgan-Evernote/electron-builder.git#master",
but that fails with:
'electron-builder' is not recognized as an internal or external command,

I went to my fork and ran "yarn release" which fails with a bunch of 403 errors.  I'm stuck here.
