### ISSUE TITLE
Only first artifact is uploaded to GitHub

### ISSUE THREAD

**Issue by blainesch** [electron-userland/electron-builder#1133]
* **Version**:  11.2.3
* **Target**:  Linux (dmg), mac and windows
* **Command**: `build --x64 --publish onTagOrDraft`

## Setup

I am having Travis CI run mac and linux, and appveyor run windows.

## Expected Behavior

When I push a tag it to create a release on github and upload the 3 artifacts. 

## Actual Behavior

The first CI job that finishes uploads the artifact, and the others do not.
 
## Additional Information

I have deleted the release on github multiple times to run each job individually, the first one to finish is always the one to upload the artifact, while the others do not upload. I am working on [this branch](https://github.com/tinytacoteam/zazu/tree/feature/electron-builder) trying to push a dummy version `0.3.2-beb` to make sure it works before merging.

**Comment by develar** [comment]
Does it work for 11.4.4?

**Comment by blainesch** [comment]
Confirmed, this still happens in 11.4.4

CI Builds:
https://ci.appveyor.com/project/blainesch/zazu/build/1.0.171
https://travis-ci.org/tinytacoteam/zazu/builds/192829811

Release on GitHub:
https://github.com/tinytacoteam/zazu/releases/tag/v0.3.2-build

**Comment by develar** [comment]
You set draft to false, but artifacts are not published for non-draft github release. So, first CI creates release and upload, but second cannot. To be fixed.

**Comment by blainesch** [comment]
Is there a timeline for this being fixed, or is there a workaround I can do until then?

**Comment by develar** [comment]
@blainesch Right now I review change before push :)

**Comment by blainesch** [comment]
Super quick, thanks :D

**Comment by develar** [comment]
It will be released as 11.5.0 in 30 minutes (if CI will be green ;)).

**Comment by blainesch** [comment]
]: It's still not uploading them all

https://travis-ci.org/tinytacoteam/zazu/builds/193498058
https://ci.appveyor.com/project/blainesch/zazu

You can see in the output it's installing 11.5.0

**Comment by develar** [comment]
@blainesch Please try 11.5.2 and set env DEBUG=electron-builder

**Comment by blainesch** [comment]
@develar here is the changeset:
https://github.com/tinytacoteam/zazu/commit/2d3c84eb0f93a9a1e5b32dc511e90910bf21ae5b

The tag:
https://github.com/tinytacoteam/zazu/releases/tag/v0.3.2-builder

The ci jobs:
https://travis-ci.org/tinytacoteam/zazu/jobs/194893264
https://ci.appveyor.com/project/blainesch/zazu/build/1.0.183

**Comment by develar** [comment]
@blainesch Why do you use draft: false? It leads to issue: one CI publishes release, but another CI is still not yet upload artifacts. Why don't you want to follow default workflow and publish release (edit release -> publish) manually? https://electron-builder.slack.com/archives/general/p1485961449000202

**Comment by blainesch** [comment]
@develar mostly preference. If it would work without the draft I'll turn it off.

**Comment by develar** [comment]
@blainesch Please to remove `draft` option.

**Comment by develar** [comment]
@blainesch Does it work for you?

**Comment by blainesch** [comment]
Yes removing the flag fixed the issue.
