### ISSUE TITLE
How To Use Custom NSIS Script Trigger External Executable (ex. Installer / Uninstaller) ?

### ISSUE THREAD

**Issue by FromStoneage** [electron-userland/electron-builder#1134]
* **Version**: 11.4.4

* **Target**: Windows

Newbies with NSIS script, please help to point to the right direction. I'm trying to build an NSIS installer that can trigger either an uninstaller on the system that's going to install or launch an embedded installer from Electron builder package. (a concrete example is, trying to embed [wkhtmltopdf installer](http://wkhtmltopdf.org/downloads.html) to the Electron builder NSIS installer or launch an uninstaller from the Windows OS via our Electron-builder NSIS installer.

I'm looking at the documentation on custom [NSIS script](https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script) there are two options provided that's using `script` or `include`.  It seems it's possible to use one of the flags and combine with http://nsis.sourceforge.net/Embedding_other_installers to achieve this. However, I have no clue how to combine the two into a working project. I tried to use the flag `include` and `script` to run a custom NSIS script from [hello world NSIS script](http://nsis.sourceforge.net/Simple_tutorials), everything seems to fail and keep getting `Error. Exit code 2` back

**below are the output**
```
> sdt@2.6.0 pack:win /home/jonathan/Documents/Git/test
> build --win --x64

Warning: "directories" in the root is deprecated, please specify in the "build"
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.4.14 to artifacts/win-unpacked
Packaging NSIS installer for arch x64
Building NSIS installer
Error: Exit code: 2. Command failed: wine /home/jonathan/Documents/Git/test/artifacts/test 2.6.0.exe

```
**package.json**
```
   "nsis":{
      "perMachine": false,
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "include": "build/installer.nsh"
    },
```
**build/installer.nsh**
```
# set the name of the installer
Outfile "test 2.6.0.exe"

# create a default section.
Section

# create a popup box, with an OK button and the text "Hello world!"
MessageBox MB_OK "Hello world!"

SectionEnd
```

Any help is much appreciated!!

**Comment by develar** [comment]
"Define wanted macro to customise" 

You forgot to define macros.
