### ISSUE TITLE
afterPack is not invoked anymore?

### ISSUE THREAD

**Issue by eriedl-kiban** [electron-userland/electron-builder#1135]
* **Version**: 11.4.4

* **Target**: Mac

I use the programmatic API and have an afterPack function registered. It used to be called in version  to work just fine in version 10.5.0. I decided to upgraded as the `--deep` flag not used when signing the Package Installer target for MacOS. In 11.4.4 afterPack does get executed anymore.
I also updated my packaging script and renamed `devMetadata` to `config`.

**Comment by eriedl-kiban** [comment]
OK, figured it out. afterPack and other properties used to be part of the `build` property previously, now they moved up one level it seems when `devMetadata` was renamed to `config`. Makes more sense anyway :)

Now the remaining issue is that the code signing on MacOS is still missing the `--deep` flag for `pkg` targets. I thought this was fixed with 11.4.4, but it turned out that the additional files were never copied, so the code signer never barfed.

**Comment by eriedl-kiban** [comment]
it seems the issue is in package electron-macos-sign. The `--deep` flag is not added to the sign arguments in file sign.js. I created an issue over there: https://github.com/electron-userland/electron-osx-sign/issues/125

**Comment by develar** [comment]
devMetadata not renamed — config it is devMetadata.build. I will fix docs.
