### ISSUE TITLE
Cannot find module "javascript error" on linux

### ISSUE THREAD

**Issue by aredfox** [electron-userland/electron-builder#1136]
* **Version**:  11.2.5

* **Target**: linux

When having build an unpacked version with --asar on, I got it running (packaged) for windows and macOS a-ok. Yet when running a build for linux, both being build ON macOS and on windows, the package errors out with the notification (via terminal): "javascript error - cannot find module moment.js".

As I said I compiled the linux version on Windows and on macOS, both fail. Tested on linux mint 17 and 18.1.

Am I doing something wrong, should I build on linux? I couldn't find info on the moment.js package to hold os-specific things preventing it to compile on macOS or Windows.

**Comment by develar** [comment]
Do you have native dependencies?

**Comment by aredfox** [comment]
I did have some native dependencies I think, but building on both platforms works now for me.
