### ISSUE TITLE
how to get steps install .exe file in win10 x64 with electron-builder?

### ISSUE THREAD

**Issue by CarlosRen** [electron-userland/electron-builder#1139]
I have some questions about electron-builder after follow steps:
* set key-value :  "pack": "build -mwl" , "dist": "build"
* create an app and run `npm run pack` and `npm build`
* add some autoupdater code to check the server infomation.

there is my questions:
* question 1 : I got a .exe install file without next steps , and i was excepting a normal .exe file 
* question 2 : as the introduction of autoupdater in electron  api, a installed app will stop warning "require squrriel" error, but it still alerting in my app.

with my code which execute the update informations check:
```
    const updatePath = host + "/updates/latest?version=" + appVersion + "&platform=" + platform;

    console.log(updatePath);

    autoUpdater.setFeedURL(updatePath);

    autoUpdater.on("checking-for-update",function(){
        console.log("checking-for-update");
    });

    autoUpdater.on("update-available",function(){
        console.log("update-available");
    });

    autoUpdater.on("update-not-available",function(){
        console.log("update-not-available");
    });

    autoUpdater.on("update-downloaded",function(){
        console.log("update-downloaded");
    })
```

except any suggestions , best wishes!

**Comment by develar** [comment]
1. I don't understand what problem do you have. If you use electron-squirrel-startup, do not use — it is not required for NSIS.
2. Please see auto-update https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by CarlosRen** [comment]
sorry for my unclear expression, i want to get an install file by electron-builder , after execute `npm pack` , i got a .exe file . i were expecting to get a few steps to install my app on computer when i opened it . But i got a processing bar , and after finished , i can use my app without any setup processes. 

did i need a .msi ? 

wish u help

**Comment by develar** [comment]
Please set oneClick to false — https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions
