### ISSUE TITLE
Issues codesigning on macOS with Travis CI

### ISSUE THREAD

**Issue by claygriffiths** [electron-userland/electron-builder#1142]
* **Version**: 11.3.0

* **Target**: macOS .zip

When building our application on Travis CI we're running into the following error and can't seem to find a way to get around it:

```
electron-osx-sign Signing... /Users/travis/build/XXXXX/XXXXX/dist/mac/AAAAA.app/Contents/MacOS/AAAAA +317ms
  electron-osx-sign Executing... codesign --sign Developer ID Application: XXXXXX --force --keychain /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-builder-7quhRM/0-1.keychain /Users/travis/build/XXXXX/XXXXX/dist/mac/AAAAA.app/Contents/MacOS/AAAAA +1ms
  electron-osx-sign Error executing file: 
 > Stdout:  
 > Stderr: /Users/travis/build/XXXXX/XXXXX/dist/mac/AAAAA.app/Contents/MacOS/AAAAA: timestamps differ by 345 seconds - check your system clock
 +6m
Unhandled rejection Error: Command failed: codesign --sign Developer ID Application: XXXXXX --force --keychain /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-builder-7quhRM/0-1.keychain /Users/travis/build/XXXXX/XXXXX/dist/mac/AAAAA.app/Contents/MacOS/AAAAA
/Users/travis/build/XXXXX/XXXXX/dist/mac/AAAAA.app/Contents/MacOS/AAAAA: timestamps differ by 345 seconds - check your system clock
```

Here are the main Travis CI settings:

```
os: osx
osx_image: xcode7.3

language: node_js

node_js:
  - "6"

env:
  - DEBUG=electron-osx-sign*
```

I've also tried changing the osx_image, accepting Xcode terms and conditions with the command they provide, as well as syncing with Apple's time server but nothing has helped.

**Comment by develar** [comment]
Well, it is a known issue (in the past, I hope) for xcode8 images, but for 7.3 should be ok. Well, it works for my sample project (https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml).

So... please open online apple developer site — https://developer.apple.com/account/ — do you see any notification (probably new terms is not accepted)? 

Also, you can try add to `script`:

```
script:
  - sudo ntpdate -u time.apple.com
```

**Comment by claygriffiths** [comment]
I tried logging into https://developer.apple.com/account/ and didn't see anything to accept.

Also, that's the command I tried when I mentioned syncing with Apple's time server.

If I try this on my own Mac it works fine. It also used to work (although inconsistent) on Travis CI previously.

**Comment by develar** [comment]
I hope you didn't disable asar?

Is it possible to provide full travis log (I want to see  timings)?

**Comment by claygriffiths** [comment]
Asar isn't disabled. asarUnpack is used very briefly.

I e-mailed you the log.

**Comment by develar** [comment]
Travis CI is very slow and it leads to timestamp error... Please try 11.5.0 (fix is not intended for you, but maybe, details in the https://github.com/electron-userland/electron-osx-sign/releases/tag/v0.4.3).

**Comment by claygriffiths** [comment]
We switched to [Bitrise](https://bitrise.io) and it's been working phenomenally.

**Comment by timfish** [comment]
@claygriffiths could you share details of how your config to get bitrise building your electron app?

**Comment by BenBach** [comment]
@claygriffiths @timfish Would be great to share that knowledge somewhere. Would really appreciate any help :-)

**Comment by timfish** [comment]
I've got a part finished blog post somewhere detailing getting a dual Mac/Linux build working on Bitrise. Will try and get it up somewhere...

**Comment by claygriffiths** [comment]
@BenBach 

The main thing that you need to do is add the appropriate Apple Developer ID certificate to the "Code Signing" section of the Workflow editor in Bitrise.

Then, make sure [`build.mac.identity`](https://www.electron.build/configuration/mac) in `package.json` matches the certificate you uploaded to Bitrise. I don't believe any of the `CSC` environment variables are needed unless you're building for Windows on something like AppVeyor.

After you do those two things, you can trigger `electron-builder` in your Bitrise Workflow. 😃
