### ISSUE TITLE
How to set an environment variable before starting packaged electron 

### ISSUE THREAD

**Issue by ferrisimo** [electron-userland/electron-builder#1144]
* **10.7.0**: 

* **1.4.14**: WIndows 64bit

This is not an issue, more a plea for help.

I have an application that needs more than the default thread count (4) to handle multiple serialports. I can controlled by setting UV_THREADPOOL_COUNT in package.json and everything works great.

"start": "cross-env UV_THREADPOOL_SIZE=20 electron ."

running on Windows 7 / 10 / mac. However my packaged application does not have the variable set.
I've attempted to set this using process.env.UV_THREADPOOL_SIZE in main.js but it looks like its too late at this point. Other attempts to either require in the app or set in the build script via --js-flags is failing.

Has anyone had this or a similar environment issue they have managed to package?

2 days of Googling and I've not managed a working solution other than npm start which is not a 
viable for a customer to do.

**Comment by develar** [comment]
http://stackoverflow.com/a/3036367/1910191

Create `.cmd` file and run it instead of app exe directly.

You need to change https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/nsis/installSection.nsh#L139

https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script (yes, not easy to change the only line, maybe you can fork for now and later send a PR).

**Comment by ferrisimo** [comment]
Many thanks. I'll give that a go.

**Comment by k3vinlusec** [comment]
Hi, ferrisimo
I also have the same issue, how to solve it finally? 
Thanks!

**Comment by joewandy** [comment]
@ferrisimo could you share how you fixed it please? :)

**Comment by ferrisimo** [comment]
I ended up just setting the variable in Windows I think as a manual step. Will temind myself when I’m back in the office. Apologies for the slow response!

**Comment by joewandy** [comment]
I ended up using node-powershell to set the variable. Here's my code, if anyone is interested:
```
        if (process.platform === 'win32') {
          const Shell = require('node-powershell')
          let ps = new Shell({
            executionPolicy: 'Bypass',
            noProfile: true
          })
          const command = "[Environment]::SetEnvironmentVariable('UV_THREADPOOL_SIZE', 128, 'User')"
          ps.addCommand(command)
          ps.invoke()
            .then(output => {
              dialog.showMessageBox({
                type: 'info',
                message: 'First time setup done.'
              })
              app.relaunch()
              app.quit()
            })
            .catch(err => {
              console.log(err)
              ps.dispose()
            })
        }
```

**Comment by minzhang2** [comment]
None of the above methods work.

**Comment by chenyanfei-m** [comment]
it's work in Windows

`javascript
const [command, ...args] = process.argv;
const subprocess = spawn(command, [...args, ignore_lock_switch], {
    env: {
        ...process.env,
        UV_THREADPOOL_SIZE: '128',
      },
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
})
subprocess.unref();
app.exit()
`

**Comment by FynniX** [comment]
I don't why you all using these complicated things. For me this is working fine, just put it inside the startup function.

```
if(app.isPackaged && process.env.UV_THREADPOOL_SIZE === undefined) {
        process.env.UV_THREADPOOL_SIZE = '32'
        app.relaunch()
        app.exit(0)
}
```
