### ISSUE TITLE
NSIS start program automatically when Windows starts

### ISSUE THREAD

**Issue by Zayelion** [electron-userland/electron-builder#1145]
**Feature Request**

* **electron-builder@11.4.4**: 

* **win32, win64**: 

packge.json

```JSON
{ 
  "name": "myapp",
  "productName": "My App",
  "author": "My Company",

...
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": ["Startup"],
      "runAfterFinish": false
    },
```
On selecting per machine install, the default path is:

    C:\Program Files (x86)\Startup\myapp

Whereas I was hoping for:

    C:\Program Files (x86)\My Company\myapp

And then for the installation to then place a shortcut into the startup menu. Or a way of naming the default path that is divorced from `menuCategory`.

**Comment by develar** [comment]
> to then place a shortcut into the startup menu

It will be in the menu without any menu category. Menu category for company name.

**Comment by Zayelion** [comment]
> It will be in the menu without any menu category. Menu category for company name.

Thats what happens when I set `menuCategory` to true, but I need the _link_ to the application in the `Startup` menu (`%appdata%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`), and the _default application path_ to be `C:\Program Files (x86)\My Company\myapp` **not** `C:\Program Files (x86)\Startup\myapp`.

**The intended effect is** that the product installs into the overarching parent company folder of `C:\Program Files (x86)\My Company\` when the user is rapidly clicking not `C:\Program Files (x86)\Startup\` and still be **started automatically on login, start, restart** like other programs in the users `%appdata%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by develar** [comment]
It is a new option. http://redino.net/blog/2013/06/nsis-start-program-automatically-when-windows-starts/

**Comment by develar** [comment]
"Start Menu/Startup Folder" will be implemented as it is a more better for user (easy to remove). PR welcome.

**Comment by Zayelion** [comment]
If someone familiar with the code starts working on this please say so here, otherwise when I get the time I will start working on the feature.

**Comment by alexbrazier** [comment]
@Zayelion This is how I have done it with the current version using the include file if this helps:

```
!ifndef BUILD_UNINSTALLER
  Function AddToStartup
    CreateShortCut "$SMSTARTUP\AppName.lnk" "$INSTDIR\AppName.exe" ""
  FunctionEnd

  ; Using the read me setting as an easy way to add an add to startup option
  !define MUI_FINISHPAGE_SHOWREADME
  !define MUI_FINISHPAGE_SHOWREADME_TEXT "Run at startup"
  !define MUI_FINISHPAGE_SHOWREADME_FUNCTION AddToStartup
!endif
!macro customUnInstall
  Delete "$SMSTARTUP\AppName.lnk"
!macroend

```

It uses the unused readme option - I'm not sure if this would be considered bad practice and you would rather implement it from scratch (although the MUI docs say you can use the readme for other purposes)

**Comment by Zayelion** [comment]
Thank you.
