### ISSUE TITLE
Create mac build on Linux, sign-only on macOS

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#1146]
* **Version**: latest
* **Target**: mac, linux, win

It would be cool if `electron-builder` supported Mac builds on Linux. Now, I know that you cannon properly build and sign a Mac build on anything different than a Mac. However, it should be possible to create a build on Linux and sign it later (e.g. via ssh) on a Mac.

What do you think? Would you be open to such a feature?

**Comment by develar** [comment]
You can create dmg only on macOS.

**Comment by jakubzitny** [comment]
How about the `.app` only?

**Comment by develar** [comment]
No one forbid you to build `tar.gz`, tar.xz`, `dir` and other common targets for mac ;) `--mac dir` or `--mac zip`. Or set target option (`mac.target`).

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-target

**Comment by develar** [comment]
Do you mean that you want ability "point to prepacked .app dir to just sign it"?

**Comment by jakubzitny** [comment]
Sorry I didn't realize the "dir" option can work on linux, just tried it and it works.

So yeah, now the "sign a prepacked .app dir" option would be quite useful.

**Comment by jakubzitny** [comment]
Closing with respect to #1159.
