### ISSUE TITLE
Abort download

### ISSUE THREAD

**Issue by sante85** [electron-userland/electron-builder#1150]
* **Version**: 
last tag

* **Target**: 
all

Make it possible abort download?

**Comment by develar** [comment]
What do you mean?

**Comment by sante85** [comment]
when autoUpdater download release file, and another event is emitted, I want programmatically abort (stop) download in progress and delete file in temp directory. 

2. delete file in temp directory even next release has been successfully installed.

Thanks

**Comment by sante85** [comment]
Hi developer, 
the problem is clear?

Thanks

**Comment by develar** [comment]
You can abort download — 

1. checkForUpdates returns Promise of UpdateCheckResult.
2. UpdateCheckResult has property `downloadPromise`.
3. We use special configured Bluebird — you can call `downloadPromise.cancel()`

But — `isCancelled` is not checked by `electronHttpExecutor.ts` or `nodeHttpExecutor.ts`. To be fixed.

> delete file in temp directory even next release has been successfully installed.

It is a different issue. To investigate (currently we suppose that OS will delete temp files).

**Comment by sante85** [comment]
I use generic provider on windows OS

**Comment by sante85** [comment]
we automatically delete temp file, because if download fail, on reopen app, it try dowload update. Repeating this step many times and create problem on disk full temp directory.

**Comment by sante85** [comment]
The problem is that while downloading the update, I wish I could stop at any time. Then if it is blocked or fails for other reasons, the temporary file should be deleted.

**Comment by sante85** [comment]
when autoUpdater download release file, and another event is emitted, I want programmatically abort (stop) download in progress and delete file in temp directory.

    delete file in temp directory even next release has been successfully installed.

Thanks

**Comment by sante85** [comment]
when autoUpdater download release file, and another event is emitted, I want programmatically abort (stop) download in progress and delete file in temp directory.

thanks

**Comment by Ruj89** [comment]
up

**Comment by develar** [comment]
UpdateCheckResult now has `cancellationToken` property — call `cancellationToken.cancel()`

**Comment by develar** [comment]
Docs will be updated later.

**Comment by sante85** [comment]
hi developer,
how to pass cancellationToken to updater? he write docs please?

**Comment by New-Key** [comment]
How is the implementation to abort the Download? I'm not clear in this aspect, checkForUpdates return a promise which I see on the JSON, but the implementations, to stop by user's demand, when autoDownload is false ?

**Comment by develar** [comment]
@New-Key 

```ts
import { CancellationToken } from "electron-builder-http"

const cancellationToken = new CancellationToken()
autoUdater.download(cancellationToken)

// stop download
cancellationToken.cancel()
```

**Comment by develar** [comment]
@New-Key I don't want expose `electron-builder-http` so, in the next version `CancellationToken` will be available from `electron-updater`. I will add example to docs.

**Comment by lzou** [comment]
@develar when i use autoUdater.download(cancellationToken), it's crash, the log is
`TypeError: g.autoUpdater.download is not a function
TypeError: g.autoUpdater.download is not a function
    at EventEmitter.<anonymous> (C:\Users\zou\AppData\Local\Programs\student\resources\app.asar\dist\electron\main.js:1:25552)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (C:\Users\zou\AppData\Local\Programs\student\resources\electron.asar\browser\api\web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)`

**Comment by genesy** [comment]
Am I doing this right ?

```
autoUpdater.checkForUpdates().then((downloadPromise) => {
    cancellationToken = downloadPromise.cancellationToken;
});
someEvent.then(() => { cancellationToken.cancel() })
```
when i trigger `cancellationToken.cancel()` i get an error `Error: Cancelled` why is it an error if i'm purposely doing it?

**Comment by jason-zuo** [comment]
@genesy hi ,i face the same problem ,can you fixed it?

**Comment by genesy** [comment]
@jason-zuo nope just left it as is. might be meant that way

**Comment by develar** [comment]
`electron-updater` `3.2.2` will not dispatch `error` event for `CancellationError`, but returned promise still will be rejected with `CancellationError` because otherwise not easy for you to handle this  properly (either `then` or `catch` handlers must be called for Promise, so, it is logical to call `catch`).

**Comment by mqliutie** [comment]
> @New-Key
> 
> Set `autoDownload` to `false` and then you can call `autoUdater.downloadUpdate` directly.
> 
> ```ts
> import { CancellationToken } from "electron-updater"
> 
> const cancellationToken = new CancellationToken()
> autoUdater.downloadUpdate(cancellationToken)
> 
> // stop download
> cancellationToken.cancel()
> ```

I called `cancellationToken.cancel()`,  and next time I check for udpating , download will always be cancelled.  

The log file is 
>[2021-10-14 20:46:16.808] [info]                       cancelled
[2021-10-14 20:46:16.809] [error]                      unhandledRejection Error: cancelled


How can I make it works again

Thanks
