### ISSUE TITLE
runAfterFinish checkbox appear checked when runAfterFinish is set to false

### ISSUE THREAD

**Issue by christianjkarlsson** [electron-userland/electron-builder#1151]
* **11.5.0**: 

* **Windows**: 

Seems no matter what I try to put in runAfterFinish, the checkbox still appear checked after installation. I'm setting oneClick to false because I'm using allowToChangeInstallationDirectory. Shouldn't this checkbox not show up or is there a way to make the application run after finish even when using allowToChangeInstallationDirectory. Example of package.json below:

"build": {
    "extraResources": [
    {
      "from": "app/node_modules/nodeaep",
      "to": "app.asar.unpacked/node_modules/nodeaep",
      "filter": "**/*"
    },
    {
      "from": "app/VROOT",
      "to": "app.asar.unpacked/VROOT",
      "filter": "**/*"
    },
    {
      "from": "../lua",
      "to": "app.asar.unpacked/VROOT/lua",
      "filter": "**/*"
    }
    ],
    "win": {
      "target": [
        "nsis"
      ],
     "icon": "build/icon.ico"
    },
    "publish": {
      "provider": "generic",
      "url" : "https://drive.google.com/drive/folders/****"
    },
    "nsis": {
      "menuCategory": true,
      "oneClick": false,
      "perMachine": true,
      "installerHeaderIcon": "build/icon.ico",
      "allowToChangeInstallationDirectory": true,
      "runAfterFinish": false
    },
  }

**Comment by develar** [comment]
Initially designed for one-click installer.

**Comment by develar** [comment]
For what you want to disable ability for user to run app after finish?

**Comment by christianjkarlsson** [comment]
I don't, but I want the allowToChangeInstallationDirectory feature, and since it doesn't work with the one-click installer I thought maby there was a way to hide the checkbox or a way to have run app after finish even with the allowToChangeInstallationDirectory set to true.

**Comment by christianjkarlsson** [comment]
To clarify: The run box is always ticked but it doesn't run after finish, nor can is unticked if I set runAfterFinish to false. Can it be hidden or even better, can it run after finish when using allowToChangeInstallDirectory.
![image](https://cloud.githubusercontent.com/assets/10851214/22327992/41bb17d8-e3ba-11e6-9dfd-0bb3624ac789.png)

**Comment by develar** [comment]
Please try 12.0.2

**Comment by christianjkarlsson** [comment]
Tried 12.0.2 and 12.0.3. runAfterFinish: true/false and not declared. It still doesn't run after pressing finish and checkbox is always ticked.

**Comment by yuvallb** [comment]
I'm having the same problem.
I want to disable/hide the "run after finish", but the runAfterFinish setting does not seem to have any affect

**Comment by develar** [comment]
@yuvallb For what do you want to hide it?

**Comment by yuvallb** [comment]
I don't really NEED to hide it, 
it's just that the application is not running when the checkbox is marked,
and my most frequent use case is installing the application on a citrix server, where it doesn't make sense to run the application after the installation.
so I prefer to hide the checkbox and not run it after installation.

**Comment by sylhero** [comment]
same issue @develar any updates?

**Comment by pedro-surf** [comment]
=/

**Comment by oldmtn** [comment]
Still have this issue

**Comment by beliaev-maksim** [comment]
@develar 
here is one use case. If you pack you app to work with electron-updater but at the same time want to allow user to specify installation path for the first installation

then your config file will look like:
```
"nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "runAfterFinish": true,
      "shortcutName": "my name"
    }
```

for the first run it is fully OK, however, when auto-update is done, app is not auto-restarted but stuck on last installation page with "start the app" checkbox ticked and user has to manually click Finish to start the app
