### ISSUE TITLE
Node FFI Cross-Platform

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#1152]
We are using Node FFI to integrate a C library. The library files are compiled beforehand on windows, mac and linux and added to our repo.

However, when I compile on mac, windows users get an error:

(this is on windows 64 bit). I also tried compiling just 64-bit, and not both 32 and 64 bit at the same time, but the error is the same.

![17 01 png](https://cloud.githubusercontent.com/assets/20187287/22175717/9094c874-e020-11e6-8a05-8c4971165a19.jpg)

The error goes away when I compile it on windows itself. So what might be the problem here? We don't really want to compile the releases on each platform separately. 

This is about this repo: https://github.com/iotaledger/wallet (dev branch)

Thanks.

**Comment by develar** [comment]
Please try to set npmSkipBuildFromSource to false.

**Comment by atypicalprogrammer** [comment]
Isn't that the default value (from wiki)?

**Comment by atypicalprogrammer** [comment]
I suppose you mean setting it to true. But these are c libraries, they are just added as extra files to the project. See the github link above. (libccurl.so etc).

**Comment by develar** [comment]
Ah, yes, true, to use prebuilt binaries. Ok, I will investigate your project when I will have time.

**Comment by atypicalprogrammer** [comment]
Thanks, any way we can speed this up? Do you offer premium support in exchange for dollars?

**Comment by develar** [comment]
> any way we can speed this up? Do you offer premium support in exchange for dollars?

Well, you can [donate](https://github.com/electron-userland/electron-builder#donations) to increase priority. But please note — donation is not a guarantee.

**Comment by atypicalprogrammer** [comment]
OK, we can do that. Will you accept IOTA's or Bitcoin or would you require funds in dollars? Dollars we can send in a week or 2 if required, as we are currently setting up the IOTA Foundation (Stiftung) in Germany. IOTA / Bitcoin we can send you faster. You can email your IOTA / Bitcoin address to dom@schiener.me

**Comment by develar** [comment]
@atypicalprogrammer Both native deps

>   Rebuilding native production dependencies for darwin:x64
electron-builder Spawning npm rebuild ref ffi +0ms

`ref` and `ffi` don't use [prebuild](https://www.npmjs.com/package/prebuild) — `"install": "node-gyp rebuild",` So, why do you expect that your app can be compiled on one platform?
