### ISSUE TITLE
What icons to provide for linux exactly and how to name them?

### ISSUE THREAD

**Issue by johannesjo** [electron-userland/electron-builder#1154]
* **Version**: 
v11.4.4

* **Target**: 
Linux

When building on linux and for linux I get the following error: `Error: Icon is not provided`
I put all the mac icons (from the icns folder) into the build/icons folder. I also tried creating only a  48x48 variant. All with the same result.

**Comment by develar** [comment]
Please see https://github.com/develar/onshape-desktop-shell/tree/master/build/icons

Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by Skywalker13** [comment]
@johannesjo: just save the icns icon in `build/icon.icns` (no icns folder here) and install the icnsutils package of your distrib (like `apt install icnsutils`).

**Comment by johannesjo** [comment]
Thank you very much! Maybe we can move put that link into the docs?

**Comment by develar** [comment]
It is already in the https://github.com/electron-userland/electron-builder#quick-setup-guide

Where do you want to see this doc? In the same way as for macOS — https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-icon?
