### ISSUE TITLE
NSIS fileAssosiations failed

### ISSUE THREAD

**Issue by ChannelOne** [electron-userland/electron-builder#1155]
* **Version**: 10.15.1

* **Target**: Win32-64 (win10 for debug)

I have add `fileAssociations` options to `build`, but after buiding, the NSIS installer didn't associate file to Electron. I don't why because there is no error messages.
```
"fileAssociations": [{
  "ext": "md",
  "name": "Markdown"
}]
```

**Comment by develar** [comment]
perMachine to true is required for file associations.

**Comment by ChannelOne** [comment]
@develar Yes, you are right.
