### ISSUE TITLE
Programmatically create multi arch NSIS installer 

### ISSUE THREAD

**Issue by loziobiz** [electron-userland/electron-builder#1156]
* **Version**: 14.4.4

* **Target**: NSIS

I know I can make a single multi-arch NSIS installer passing --ia32 --x64 to the ```build``` command with the CLI, but how can I do the same programmatically?
I tried  ```arch: ['x64', 'ia32']``` but I guess only strings are accepted.
I also took a look at ```electron-builder.d.ts``` without fortune.

**Comment by develar** [comment]
```
const builder = require("electron-builder")
const Platform = builder.Platform
const Arch = builder.Arch
Platform.MAC.createTarget(["nsis"], Arch.ia32, Arch.x64),
```
