### ISSUE TITLE
Portable Build

### ISSUE THREAD

**Issue by sabrehagen** [electron-userland/electron-builder#1157]
Hi,

How feasible is it to support a 'portable' build, that is, a version that runs on Windows that does not install to the local machine but rather runs without modifying the state of the machine. E.g. [Putty portable](http://portableapps.com/apps/internet/putty_portable)

Thanks

**Comment by develar** [comment]
Duplicates #808 PR welcome.

**Comment by aliaga-d** [comment]
why isn't a language configuration for portable as what nsis has?
