### ISSUE TITLE
building failed for linux on centos6

### ISSUE THREAD

**Issue by arthur791004** [electron-userland/electron-builder#1158]
* **Version**: 11.4.4

* **Target**: linux

Hi,

when I build for linux on centos6, I got the following error message:
**Exit code: ENOENT. spawn icns2png ENOENT**

I try to install libicns-utils on centos6, but I cannot find this utils...
Could I specified a png icon for linux to prevent to do icns2png?

Thanks.

**Comment by develar** [comment]
> The Linux icon set will be generated automatically based on the macOS icns file (or you can put them into the build/icons directory if you want to specify them yourself. The filename must contain the size (e.g. 32x32.png) of the icon).

e.g. https://github.com/develar/onshape-desktop-shell/tree/master/build/icons
