### ISSUE TITLE
Sign prepacked mac build only

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#1159]
* **Version**: latest
* **Target**: mac, linux, win

I am separating the feature request from #1146 — creating a `sign` option, that can be used to sign prepacked mac bundle that was already built before, e.g. on a different Linux CI machine.

**Comment by jakubzitny** [comment]
Is there any simple way to implement this @develar? It could really help to simplify Mac builds from Linux that are signed on a Mac.

**Comment by develar** [comment]
It is only one line of code, because now you can build prepackaged app — we don't sign it yet, but should.

What do you build? DMG? Why not just build on Mac?

**Comment by jakubzitny** [comment]
Can we create a DMG from prepackaged `.app` there already? We're on the electron-builder `12.2`, it might not have been there yet, or?

And yeah we have the whole CI pipeline on Linux machines as most of the build tools are more stable and easier to setup and maintain on Linux. We're just `scp`ing the Mac zip build to a Mac mini server, sign it there and then we want to continue building DMG where we left off on Linux. Right now we have extra `appdmg` dependency for this, but running this with electron-builder would be cool.

**Comment by develar** [comment]
> Can we create a DMG from prepackaged .app already

Yes. I realized that it is already supported. Build prepacked app — https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format

**Comment by develar** [comment]
> we want to continue building DMG where we left off on Linux

You cannot because DMG is supported only on mac. So, you just send .app to mac mini and pack it onto dmg (will be signed).

**Comment by jakubzitny** [comment]
Right, thanks. The `--prepackaged` flag for packing is what we'll use. :) 🎉
