### ISSUE TITLE
How to get icon path/image in electron-builder

### ISSUE THREAD

**Issue by bxpd** [electron-userland/electron-builder#1161]
Hi,

I'm using [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) to develop electron app (which uses electron-builder to pack apps).

I want to create [tray](http://electron.atom.io/docs/api/tray/#new-trayimage), but it requires icon path or native image. The question is how to retrieve icon image from electron-builder or how to tell electron-builder to include icons dir into resources (without packing), so I can use:

```appIcon = new Tray(iconPath | nativeImage)```

**Comment by develar** [comment]
Please use [extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraResources)

**Comment by phbernard** [comment]
I personally use [`extraFiles`](https://www.electron.build/configuration/contents#extraFiles), because `extraResources` copies the files in a `resources` subdirectory and somehow creates a mismatch between dev and package environments.
