### ISSUE TITLE
Pass --update flag to uninstaller when auto updating an application

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1162]
* **Version**:  latest

* **Target**: nsis

I would like to do some cleanup on uninstall in the customUninstall macro, but atm I cannot differentiate between uninstall or auto-update uninstall.

**Comment by maczikasz** [comment]
Thanks

**Comment by exprodrigues** [comment]
How to use?

**Comment by develar** [comment]
@exprodrigues Where do you want to use it?

**Comment by exprodrigues** [comment]
I was trying to differentiate the uninstall/update in the `customUnInit` macro.
It worked as follows:

```
!macro customUnInit
  ${GetParameters} $R0
  ${GetOptions} $R0 "--update" $R1
  ${If} ${Errors}
    # Custom commands on uninstall
  ${endIf}
!macroend
```
