### ISSUE TITLE
Auto-Updater update.yml not found when opening from "unpacked"

### ISSUE THREAD

**Issue by initPRAGMA** [electron-userland/electron-builder#1163]
* **Version**: Latest

* **Target**: All

http://stackoverflow.com/questions/41688503/electron-electron-builder-auto-updater-update-yml-not-found

Is there a way to only check for updates if it's actually a packed application?

**Comment by develar** [comment]
Please use https://www.npmjs.com/package/electron-is-dev

**Comment by develar** [comment]
https://github.com/develar/onshape-desktop-shell/blob/master/src/AppUpdater.ts

```
if (isDev()) {
      return
    }
```

**Comment by initPRAGMA** [comment]
Perfect thank you.
