### ISSUE TITLE
Support build flat pkg with preinstall and postinstall scripts

### ISSUE THREAD

**Issue by dzunglht** [electron-userland/electron-builder#1166]
* **Version**:  latest

* **Target**: mac darwin

1. please support flat pkg building with preinstall and postinstall scripts (currently, we just support pkg installer with no option, kindly note that pkg and dmg play different role)
Ref: https://derflounder.wordpress.com/2012/08/15/creating-payload-free-packages-with-pkgbuild/
2. please seperate build and publish artifact to github providers. says, we use other tools for building and produce outputs at somewhere, publish artifact just to push what released outputs we define
Ton of thanks

**Comment by dzunglht** [comment]
8 days passed ... We love your work
Regards,

**Comment by develar** [comment]
Busy on electron-updater :) So, you need preinstall and postinstall scripts options for `pkg` target?

**Comment by dzunglht** [comment]
yes, will it available on your next release ?. Currently, pkg build doesn't support preinstall and postinstall scripts and so we couldn't make use of PKG advantages over the DMG. 
Ref: https://derflounder.wordpress.com/2012/08/15/creating-payload-free-packages-with-pkgbuild/
Tons of thanks

**Comment by dzunglht** [comment]
10 days passed
Regards,

**Comment by dzunglht** [comment]
We love your work and waiting for your next update 
Regards,

**Comment by develar** [comment]
Implemented in the upcoming 13.3.0
