### ISSUE TITLE
electron atom asar file protection

### ISSUE THREAD

**Issue by kumarom1203** [electron-userland/electron-builder#1168]
* **HOW PROTECT ELECRON ASAR ( app.asar) FILE FROM UNPACKAGING**: 

* **electron atom**: 

Is any method to protect asar file generated by electron atom so no one can unpack **app.asar**  file. so that they can not alter the code

**Comment by develar** [comment]
No. Please see https://github.com/electron/electron/issues/3041

**Comment by kumarom1203** [comment]
then how i protect my code from alteration. is any method to encrypt js file and html file wich is used in electron.. pls help

**Comment by develar** [comment]
Sorry, it is out of this project scope. In general, your app should be signed (see code sign).
