### ISSUE TITLE
Build Debian source package from deb

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#1170]
Does anyone know how to build Debian source package? I have already built .deb using electron-builder. I'll need to add .deb to PPA so that users can install my app via `apt-get install myapp` on Ubuntu.

**Comment by develar** [comment]
On Ubuntu you should use Ubuntu store — electron-builder support `snap` target.

**Comment by develar** [comment]
Why current `deb` is not suitable as Debian source package?

**Comment by akashnimare** [comment]
@develar hmm, Launchpad PPAs only accepts "source" uploads, which contain three components: 
a electron-app_1.0.orig.tar.gz, a electron-app_1.0-0_ppa1.debian.tar.gz, and electron-app_1.0-0_ppa1.dsc (will vary based on version numbers etc). electron-builder only build .deb.

electron-builder appears to be using fpm under the hood. I don't think it has support for building Debian source packages.

This is what we can do to build Debian source package:
1. Create a normal Debian/ directory and write rules to build a Debian source package.
2. Modify electron-builder to support creating source packages — will almost certainly require dropping fpm.

More info - 
https://www.debian.org/doc/manuals/maint-guide/build.en.html
https://wiki.debian.org/BuildingTutorial

**Comment by develar** [comment]
[Snap](https://snapcraft.io) is a modern solution for your problem. Maybe you can use it instead of deb?

**Comment by akashnimare** [comment]
@develar well, it'd be nice to support Debian as well, but I can experiment with offering snaps for Ubuntu 😃
