### ISSUE TITLE
macOS auto update for Bintray

### ISSUE THREAD

**Issue by NoahAndrews** [electron-userland/electron-builder#1172]
Hi, I'm working on adding auto-update to a project, and I'd like to use Squirrel.Mac for the Mac version. I'm planning on using Bintray to store the zip file for that. The docs said to file an issue if auto-update on Mac via Bintray was something I needed, so here I am. :)

**Comment by develar** [comment]
Ok, as we have user request, it will be implemented (I hope, this week).

**Comment by develar** [comment]
Fixed in electron-update 2.0.0. Will be announced in the #1167.
