### ISSUE TITLE
add releaseNotes and releaseName to autoUpdate

### ISSUE THREAD

**Issue by aj-ptw** [electron-userland/electron-builder#1174]
* **^11.5.1**: 

* **macOS, win**: 

Ability to add `releaseNotes` and `releaseName` to `generic` provider to `latest-mac.json` or `latest.json` for win.

Thanks!

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1174

releaseDate added. info added to events (see updated docs https://github.com/electron-userland/electron-builder/wiki/Auto-Update)

for now, it is up to you to modify generated lates-* files and add releaseName/releaseNotes
