### ISSUE TITLE
Feature request: Custom Request Headers for Electron Updater

### ISSUE THREAD

**Issue by kevinphelps** [electron-userland/electron-builder#1175]
I'd like to be able add custom request headers (specifically, an authorization header) to the HTTP requests sent by electron updater. Perhaps as in config parameter passed to `autoUpdater.checkForUpdates()`?

**Comment by develar** [comment]
`requestHeaders` option should be added to [AppUpdater](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts) base class.

**Comment by kevinphelps** [comment]
Thanks for that info. I am happy to send a pull request.
