### ISSUE TITLE
question: Mac Application Icon

### ISSUE THREAD

**Issue by Timer** [electron-userland/electron-builder#1184]
Following the instructions outlined in the [quick start guide](https://github.com/electron-userland/electron-builder#quick-setup-guide), something isn't working.

Is there a separate file I need for the launchpad icon, or is something broken, or is there a known configuration value I might of flipped to cause this?

The display in launchpad shows the incorrect icon:
![](https://puu.sh/tCXrQ/9512a99617.png)

The icon is correct in the dock, however:
![](https://puu.sh/tCXuA/6a822df7a8.png)
and in Finder:
![](https://puu.sh/tCXyZ/87260fdf74.png)
and in the DMG (no picture).

**Comment by develar** [comment]
Does it work after restart?

**Comment by Timer** [comment]
Doesn't work after restart nor on a fresh install on a different Mac.

**Comment by sagorshkov** [comment]
@Timer Are you sure that you've prepared your iconset correctly? Please, take a look [this](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html#//apple_ref/doc/uid/20000957-CH87-SW1) guide by Apple. Attention to:
Table 75-1 App icon resource sizes

**Comment by develar** [comment]
Works for me. 👍 to @sagorshkov — please ensure that your icns is correct and has all required sizes (1024, 512 and so on). Example of correct icns file — https://github.com/develar/onshape-desktop-shell/blob/master/build/icon.icns

**Comment by Timer** [comment]
Thanks @develar & @sagorshkov -- I paid to have the logo created and looking at it deeper now it seems they made it wrong! Sorry for the hassle!
