### ISSUE TITLE
Ability to disable cache for electron-updater

### ISSUE THREAD

**Issue by Timer** [electron-userland/electron-builder#1186]
Hi, is there a way to disable the caching `electron-updater` does?
I'm using S3 as a generic provider and keep running into a situation where **my program will not update until the cache directory is deleted** (Mac and Windows).

I saw [here](https://github.com/develar/electron-updater/blob/master/lib/cache.js#L96) that you use the hash provided by amazon. Is it possible that AWS isn't updating the hash or something else?

Thanks!

**Comment by develar** [comment]
Fixed already in the electron-updater 1.3.1
