### ISSUE TITLE
ensure that update only to the application signed with same cert

### ISSUE THREAD

**Issue by cumajkeee** [electron-userland/electron-builder#1187]
I want to be sure that Windows (NSIS) application can update only to the application signed with same cert. 

For Squirrel.Mac it works. When I try to update Mac application, that is not signed/signed with different cert to the correct application (signed with correct cert) I get error during update.

Same thing seems not working for Windows one.

@develar, could you please suggest something?
Thanks in advance.

**Comment by develar** [comment]
It is planned functionality. And must-have functionality since Windows security model just *** and cannot protect users.

https://technet.microsoft.com/en-us/library/ee176840.aspx will be used to verify that update is signed and signed exactly by you.

**Comment by cumajkeee** [comment]
Perfect, thanks! Is it up in backlog, or planned for someday? :)

**Comment by develar** [comment]
> planned for someday

... when all critical issues like #1106 or #1172 will be fixed.

Issue is not closed backlog, so, it is planned to be fixed in short term (but as it is an open source project, it can took years :) without PR or donation).

**Comment by JanEgner** [comment]
Just wondering if there's going to be an easy way to cover the case of an expiring code signing certificate, i.e. when the update must be signed using a different certificate than the one used for the installed version, but both certs are issued to the same person/org.

**Comment by develar** [comment]
@JanEgner Expired Code Signed Cert is always valid regardless is it expired or not. Because electron-builder always sign it using timestamp server. http://stackoverflow.com/a/4417480/1910191

**Comment by JanEgner** [comment]
@develar Yes, but some day my cert will expire and I will have to get a new one. Stuff that I signed in the past, using the now-expired cert, will continue to be considered signed. But for my next update I need to use the new cert - i.e. a different one than for the installed version.
This would be an issue if you plan to check that the cert fingerprint is the same for the update as for the installed app.

**Comment by develar** [comment]
@JanEgner Yes. Nice question. Will be checked not by cert SHA256/SHA1, but by "Issued to" field. So, during build electron-builder will remember certificate publisher and on update exe signature will be verified:
1. must be signed and valid.
2. publisher still the same.

**Comment by JanEgner** [comment]
Yes, that sounds great!
(unless the publishing company changes its name - which my employer did several times in the past years - so it would be extra-cool to be able to set an alternative accepted publisher name during build).

**Comment by cumajkeee** [comment]
Hey @develar, there is some extra work planned for this issue?

**Comment by develar** [comment]
Please use `win.forceCodeSigningVerification` to disable this check. Check is not performed if app is not signed.

**Comment by JanEgner** [comment]
Awesome - thanks a lot @MariaDima and @develar!

**Comment by cumajkeee** [comment]
@develar, @MariaDima I still can update signed application to not signed.

**Comment by develar** [comment]
@cumajkeee Please specify version of electron-updater.

**Comment by cumajkeee** [comment]
"electron-updater": "2.1.1",
"electron-builder": "18.6.2"

**Comment by cumajkeee** [comment]
Any updates so far?

**Comment by develar** [comment]
@cumajkeee As soon as my working day will be over, I will take a look ;)

**Comment by MariaDima** [comment]
I checked, but with latest electron-updater 2.1.2.
I get errors for the cases where the update has not been signed at all or has been signed using a "different" certificate.

**Comment by develar** [comment]
@MariaDima Thans for verification.
@cumajkeee Please ensure that there is `publisherName` in your `app-update.yml` file.

**Comment by MariaDima** [comment]
One more note:
    In case someone uses the **setFeedURL** method, you need to make sure you update the options with the proper "publisherName".

**Comment by KochiyaOcean** [comment]
Is update of an unsigned application still allowed?

**Comment by develar** [comment]
@KochiyaOcean Must be not in the latest electron-updater.

**Comment by KochiyaOcean** [comment]
@develar OK I think I would stuck on electron-updater@1 until found an affordable cert.

**Comment by develar** [comment]
@KochiyaOcean If your app is not unsigned at all, update of an unsigned application is allowed. You are not forced to use code signing on Windows.

**Comment by KochiyaOcean** [comment]
@develar Understood. Thanks 👍

**Comment by vhmth** [comment]
@develar we've updated our org (and cert) from Opentest, Inc. -> Loom, Inc. Since the publisher name is now different, how should I go about this update? Just tested our staging app and it seems we run into an error telling us the update isn't signed by Opentest, Inc.

Is the only way forward:

1. Ship a new build with Opentest, Inc. cert that disables the check via `win.forceCodeSigningVerification=false`
2. Force people to upgrade to that version
3. Ship a new update with the app signed by Loom, Inc. and add that check back in

?

**Comment by paulius005** [comment]
exact error for what @vhmth mentioned here:
```
Error: New version 0.22.18 is not signed by the application owner: publisherNames: Opentest, Inc., raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1597838400000)/",
    "NotBefore": "/Date(1564704000000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03387E856C29FB71D1EA8C720C1A703F",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "4C2D6BB4572616B6544AD006A6DA220CC9B95A49",
    "Version": 3,
    "Issuer": "CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=\"Loom, Inc.\", O=\"Loom, Inc.\", L=San Francisco, S=ca, C=US"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1729555200000)/",
    "NotBefore": "/Date(1413936000000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03019A023AFF58B16BD6D5EAE617F066",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.5",
      "FriendlyName": "sha1RSA"
    },
    "Thumbprint": "614D271D9102E30169822487FDE5DE00A352B01D",
    "Version": 3,
    "Handle": 1863111192016,
    "Issuer": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}
```

**Comment by billoneil** [comment]
@vhmth @paulius005 Do you remember how you got past this issue?

**Comment by vhmth** [comment]
@billoneil we ended up shipping an update with the old (still current at the time) cert that would point to a new build that opened up the allowed publisher names to both Opentest (old) and Loom (new) and pointed to a new bucket for updates. We then had all builds signed with the new cert in that new bucket. This allowed us to get everyone onto the latest Opentest build (which is valid based on the time of cert, not the time of day that the app is run).

**Comment by jeetparikh** [comment]
hey @vhmth could you please elaborate a bit more on the `opened up the allowed publisher names to both Opentest (old) and Loom (new)`.. We are running into the same problem where our publisher has changed.. Thanks :)

**Comment by jeetparikh** [comment]
thanks for getting back @vhmth ... so when you say `config` -> is it the certificate that is issued with multiple publishers (old and new) - not sure if you can do that? OR is it some config in the electron process? Sorry I am bit new to this and so need some clarification. But this really feels like a game changer as we were almost going to get the users download a new version. But this sounds so much better. thanks

**Comment by jeetparikh** [comment]
@vhmth just looping back for some help. We had to take the hard path of manual update as our cert was expired and no way of getting back. But we would definitely like to publish the new builds to a new s3 bucket. Could you please provide some help on how you changed the s3 bucket name? Thanks.. Appreciate your help.
