### ISSUE TITLE
Application icon is missing in the taskbar on Windows

### ISSUE THREAD

**Issue by tan4eto86** [electron-userland/electron-builder#1190]
* **12.0.3**: 

* **Windows**: 

When the description of the application is more than 264 symbols after installing the application (I am using nsis installer) the icon in the taskbar is missing. Opening the exe file from unpackaged version has icon.

**Comment by develar** [comment]
Do you really use `1.5.0`?

**Comment by tan4eto86** [comment]
Yes, I do. But with the issue is for sure for all of the 1.4.x versions (we have it from a long time but now I finally found what is the problem).

**Comment by develar** [comment]
Current version is `12.0.3` ;) Please upgrade.

**Comment by tan4eto86** [comment]
Sorry, I checked the electron version. I'm using this version.

**Comment by develar** [comment]
So, I only can say big thanks to you for investigation. There are several open issues about it. I will investigate it in a several days.

**Comment by develar** [comment]
Relates: #1108

**Comment by tan4eto86** [comment]
No problems, I saw other issues but all of them were closed. Many thanks.

**Comment by time-flies** [comment]
I had the issue just now, but resolved ! 
I used electron-builder@7.14.1 & electron@1.4.8 at windows 10 operation stystem.
I just add modified the "author" to much more simple name(A TEST), and than run the installer , icon appeared in task bar & start menu.

**Comment by time-flies** [comment]
I found that if the icon is blank in task bar , the link path in Windows Start Menu would be : C:\Users\${user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\undefined\xxx

the correct link path should be like this :
C:\Users\${user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\${author}\${productName}.lnk

**Comment by develar** [comment]
I hope this issue is obsolete.
