### ISSUE TITLE
Application has stopped working

### ISSUE THREAD

**Issue by mehulsutariya** [electron-userland/electron-builder#1195]
This is a followup on issue: https://github.com/electron-userland/electron-builder/issues/1022

Version: ^10.4.1
Target: windows nsis
I've build the application for x64 and x86 using target as nsis for windows and I get this pop up "Application has stopped working" every time the installed app is opened only on windows 7 machines (both x86 & x64). However the app works properly. The pop up shows up only on some Windows 7 machines and appears every time the app is opened on those machines. 

Is there anything I need to specify in the build script that I might be missing? Or has this got anything to do with the nsis?

ScreenShot:
https://cloud.githubusercontent.com/assets/24606069/21261381/0bc46a04-c3b1-11e6-97ac-4365fecec51a.jpg

Sample Project:
https://github.com/kushang-s/electronDesktopDemo

NSIS settings used are:

"nsis": {
      "oneClick": true,
      "perMachine": false,
      "allowElevation": false
    }

Error Code is

0x80000003
which has got something to do with windows registry for

!define HKEY_USERS
Additional information: I was using Squirrel before switching to NSIS.

Thanks!
Mehul

P.S. This is far far better than squirrel. :)

**Comment by develar** [comment]
Could you please upgrade to 12.2.0? Unlikely it will help, but just to be sure.

**Comment by mehulsutariya** [comment]
It seems like the upgrade has fixed the issue, however I will verify it on a couple of other machines just to make sure.

**Comment by mehulsutariya** [comment]
Verified on other machines as  well. Closing the issue. Thanks for your help.
