### ISSUE TITLE
deb and AppImage on ElementaryOS

### ISSUE THREAD

**Issue by 0x00A** [electron-userland/electron-builder#1198]
* **Version**: 12.2.0

* **Target**: Linux (ElelemtaryOS, very recent release)

Recently I decided to switch from `electron-packager` to `elecron-builder`.

* **package.json**: (here are the relevant parts)

```
   "linux": {
      "icon": "../static/icons",
      "executableName": "voltra",
      "productName": "voltra",
      "target": [
        "AppImage",
        "deb",
        "rpm",
        "tar.gz"
      ]
    },
```

* **command**: build

This successfully outputs all of the expected packages. However, none of them are able to launch at all. The app runs fine in development (via `electron .`).

I tried to install the `deb` using `sudo dpkg --install Voltra_2.2.0_amd64.deb`. But it did nothing, it didn't output any messages or anything either. 

I tried the AppImage and it seems to install the correct icon, but also does nothing. No errors or anything.

So, I extracted the tar and tried to run the executable from lldb...

```
Process 24986 launched: './voltra' (x86_64)
Process 24986 stopped and restarted: thread 1 received signal: SIGCHLD
Process 24986 exited with status = 0 (0x00000000) 
```

Not much here. In the past i've found most problems are just incorrect paths, its a javascript error, or there is a missing dependency -- in which case electron usually says something. Anyone have any ideas?

**Comment by develar** [comment]
> I tried the AppImage

Please set option includeRequiredLib  —  https://github.com/electron-userland/electron-builder/issues/1082#issuecomment-272794622  on Elementary OS AppImage size will be reduced as now there is user request ;)

I will check deb case. But I think AppImage is good for you and I will #1082 in a short term.

**Comment by 0x00A** [comment]
@develar Hey! using `includeRequiredLib` and upgrading to the latest version has fixed my problem.
