### ISSUE TITLE
Main file never copied into asar

### ISSUE THREAD

**Issue by lyptt** [electron-userland/electron-builder#1199]
I'm getting "Error: Application entry file "index.js" in the "app.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration." when I try to package my app.

My package.json has a main entry 'index.js', 'index.js' is present in the same directory as this package.json. No matter what I do I can't get electron-builder copying index.js into the asar. I've listed the asar's contents and it's not present.

I've tried adding the 'index.js' into the 'files' group, this doesn't work either.

I'm really at a loss now, what magic am I supposed to invoke to get it to copy my main file?

**Comment by develar** [comment]
Do you have directory `web` or `app` in the root?

**Comment by develar** [comment]
If yes, please set https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-app to `.`

**Comment by lyptt** [comment]
That seems to fix it, thanks 👍

**Comment by develar** [comment]
Very strange. So, you have app directory and package.json in it? But in any case you build project directory as app directory?

**Comment by lyptt** [comment]
Yup I have an app directory which gets bundled up into one big script file and a bunch of resources in my /dist folder outside the app directory.

**Comment by develar** [comment]
If you can provide your project, it will be good to investigate why it is detected as app directory incorrectly.

**Comment by lyptt** [comment]
Sure thing - https://github.com/lyptt/fxeditor is the repository for the app.

**Comment by mobitar** [comment]
@develar I can't find information on the docs site about MetadataDirectories..has this property been removed? I'm experiencing the same issue in this question.

**Comment by mobitar** [comment]
Never mind, what worked for me was to set the "main" key in both package.json **and** app/package.json.
