### ISSUE TITLE
NSIS installer for ia32 and x64

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#1202]
* **12.3.0**: 

* **Windows**: 

@develar Is it possible to create one installer for both platforms right now? I can't find any info about it(((

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/966#issuecomment-271328593

**Comment by sagorshkov** [comment]
@develar Oooh. Thanks. Looks like I have to rest)))
