### ISSUE TITLE
disable cache control on check for update

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1205]
When using electron http request, you don't set a cache control.
This created an issue for me while getting the latest.json. It was always reading the cache even the file actually changed on my server.
To fix that i actually just added:
```
        options.headers = options.headers || {};
        options.headers['Cache-Control'] = 'no-cache';
```
[here](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts#L43) (though i am not using the very last version)

**Comment by develar** [comment]
Do you use electron-updater 1.3.1+?

**Comment by develar** [comment]
We do https://github.com/electron-userland/electron-builder/blob/02a96f43ff5667ff9779b8e8941ebde294ac5c5e/packages/electron-builder-http/src/httpExecutor.ts#L286 Was fixed this week.

**Comment by develar** [comment]
Duplicates #1186

**Comment by farfromrefug** [comment]
sorry my bad, i was not looking at the same source file, so i thought it was still pending.
Thanks
