### ISSUE TITLE
Ability to download proper app package based on user's architecture via NSIS

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1207]
As referenced in #1165

If we can change the installer to download the proper app package (32 vs 64 bit) instead of combining both and wasting space then this would be a benefit for people that have large installers.

Objective is to try and save bandwidth for updates/downloads and to make the installation process faster for the user (less download time for people with slow internet).

**Comment by mastergberry** [comment]
I suppose with this type of feature the updater system will need to have a way to specify whether to download the x32 or x64 bit update as well.

**Comment by akashnimare** [comment]
+1 for this.

**Comment by develar** [comment]
Use `nsis-web` to build web installer. If not nsisWeb.appPackageUrl is not set, web installer is version dependent (because versioned app package is downloaded).

Auto-Update — works as before. Package will be downloaded as part of installing.

**Comment by akashnimare** [comment]
@develar how do I use it (and autoupdates) if I'm releasing my app on GitHub?

**Comment by develar** [comment]
In the upcoming version `latest.yml` will be generated in the `nsis-web` subdirectory.

**Comment by akashnimare** [comment]
Let me know when it's released :)

**Comment by develar** [comment]
@akashnimare Please try 13.6.0

**Comment by akashnimare** [comment]
@develar How do I suppose to use it? I want to generate both the arch ia32+x64 on windows. Is it correct -
```json
scripts : {
"dist" : "build nsis-web --ia32 --x64"
}
```
or

```json
scripts : {
"dist" : "build --nsis-web"
}

**Comment by develar** [comment]
`build --win nsis-web --ia32 --x64`

**Comment by develar** [comment]
Or, you can set `nsis-web` as a default target: set [windows.target](https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-target) to `["nsis-web"]`.

**Comment by akashnimare** [comment]
Thanks, I'm trying it out 🚀

**Comment by akashnimare** [comment]
@develar So I have got three files here-
* app Web Setup 0.0.1
* app-0.0.1-ia32.nsis
* app-0.0.1-x64.nsis


and  latest.yml in `nsis-web` directory. I guess I have to upload all these files + latest.yml in my repo's GitHub release? **app Web Setup 0.0.1** is the actual link which I have to give to others to download my app?

**Comment by mastergberry** [comment]
I'm just curious, is there a way to go from the regular installer to the web installer eventually? Or not possible if you already published the first version of the app?

**Comment by develar** [comment]
> I guess I have to upload all these files + latest.yml in my repo's GitHub release?

Yes. It will be uploaded automatically. https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

> app Web Setup 0.0.1 is the actual link which I have to give to others to download my app?

Yes.

> is there a way to go from the regular installer to the web installer eventually? Or not possible if you already published the first version of the app?

It is possible without any issues or risks. Because `latest.yml` contains filename of installer, it will be just downloaded and installer. 

Even more — now you can change artifact name, you are not forced to use only `web` — https://github.com/electron-userland/electron-builder/wiki/Options#NsisWebOptions-artifactName

**Comment by akashnimare** [comment]
@develar Can I use perMachine and perClick with `nsis-web`
```json
build : {
    "win": {
      "target": "nsis-web",
      "icon": "build/icon.ico",
      "iconUrl": "https://raw.githubusercontent.com/zulip/zulip-electron/master/build/icon.ico"
    },
    "nsis-web": {
      "perMachine": true,
      "oneClick": false
    }
}

**Comment by develar** [comment]
You can try and report issue if it doesn't work ;)

**Comment by akashnimare** [comment]
@develar will update you on this. Btw setting `nsis-web` in win.target only build for the arch you'are on so I had to use `build --win nsis-web --ia32 --x64` to build for both the arch.

**Comment by develar** [comment]
> Btw setting nsis-web in win.target only build for the arch you'are on so I had to use

Yes, it sets only target, not arch. So, `build --win --ia32 --x64`
