### ISSUE TITLE
Populate autoUpdater.signals on linux (and other unsupported systems)

### ISSUE THREAD

**Issue by gamestailer94** [electron-userland/electron-builder#1211]
I just started using unit test, and my travis builds on linux always failed, after some hours I found out that signals does not get populated on linux.

So to workaround about this atm I need to catch the system before calling signals.updateDownloaded

It would be better if signals still gets populated but updateDownloaded never gets called on unsuported systems

**Comment by develar** [comment]
Linux is not supported at all, https://github.com/electron-userland/electron-builder/issues/1138 For now, you should not create autoUpdater for Linux.
