### ISSUE TITLE
Mac os manual downloading not working

### ISSUE THREAD

**Issue by TheNoim** [electron-userland/electron-builder#1213]
* **Version** (electron-builder): 12.0.3
* **Version** (electron-updater): 1.4.1

* **Target**: mac, linux, windows (problem only occurs on mac)

(https://electron-builder.slack.com/archives/electron-updater/p1486135517000116)

If you disable autoDownload in electron-updater and you try to manual start the download with `autoUpdater.downloadUpdate();`
Nothing happens. You get the console output:
`Downloading update from (Url to the update file github)`
but still nothing happens. No download started, no progress event and nearly no network input in activity. I tried this on two mac os based systems. Both macOS 10.12.3. If you need more details, ask. On windows everything is working fine.

**Comment by farfromrefug** [comment]
Same thing here. i am investigating to give you more details

**Comment by develar** [comment]
I didn't find any suspicious and to works for me. Please try latest versions.

**Comment by develar** [comment]
Obsolete since electron-updater 2.0.0 (will be released today).
