### ISSUE TITLE
Impossible to use default DMG volume image

### ISSUE THREAD

**Issue by lauracpierre** [electron-userland/electron-builder#1215]
* 10.9.2 (but issue still in version 12)

* mac

Currently the dmg file will start to find an icon for the volume once mounted. If you do not specify any, I expect to have the default volume icon from the OS. 

The issue is that he following code is getting the app icon as the dmg icon file. 
```js
if (!("icon" in specification)) {
  use(await packager.getIconPath(), it => {
      specification.icon = it
  })
}
```

It could be an option to use the same icon as the app but I find this rather confusing for the user. The whole DMG thing is not the greatest system in the world (so many people open the application form there, rather than moving it to the Application folder) and having a DMG volume mounted with the app icon doesn't help at all. 

What do you think? Happy to code the option and add the documentation if you agree with me. 

Thank you!

**Comment by develar** [comment]
Just set dmg.icon to `null` :)
