### ISSUE TITLE
electron-updater doesn't genrate latest.yaml when using autoUpdater.setFeedURL

### ISSUE THREAD

**Issue by sylhero** [electron-userland/electron-builder#1218]
Which version of electron-builder are you using?
* **Version**:  1.4.2

 Which version of electron-updater are you using (if applicable)?
12.0.3
What target are you building for?
* **Target**:  win

I'm using "electron": "^1.4.15" "electron-builder": "^12.0.3" and electron-updater": "^1.4.2". I used the
autoUpdater.setFeedURL({ provider: 'generic', url: 'https://s3/release' });
but I don't see the latest.yaml generated unless I config the build.publish. Anyone has the same issue?

**Comment by develar** [comment]
Please attach your config.

**Comment by sylhero** [comment]
in `package.json`:
`"win": {
      "target": "nsis",
      "icon": "test-build/assets/img/icon.ico",
      "publish": [
        {
          "provider": "generic",
          "url": "https://s3/release"
        }
      ]
    }
`
in the auto-updater:
`
const Updater = (logPath) => {
    autoUpdater.logger = Logger(logPath);
    autoUpdater.setFeedURL("https://test.com/release");
    autoUpdater.signals.updateDownloaded((it) => {
    });
    autoUpdater.checkForUpdates();
};
`

I noticed that if you don't config `publish` in the `package.json` it will not generate latest.yml. However, if you config both `publish` and `autoUpdater.setFeedURL` `autoUpdater.setFeedURL` will override the url in `publish`. I don't know if this is the desired behavior.

**Comment by develar** [comment]
> autoUpdater.setFeedURL will override the url in publish.

Please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update **Do not call setFeedURL**
