### ISSUE TITLE
How can i custom install path？

### ISSUE THREAD

**Issue by matthew-sun** [electron-userland/electron-builder#1222]
- electron-builder@11.4.4
- win32

**package.json**

`
        "nsis": {
            "runAfterFinish": false
        }
`
In oneClick true mode, I hope to change the defalut install path to "D:\".How can i do?

Thanks.

**Comment by develar** [comment]
Implemented in upcoming 13.2.0: option `nsis.artifactName` is added.

**Comment by develar** [comment]
If you want to install for all users, set `perMachine` to `true`

I don't like idea to set custom path for one-click installer. If you disagree, please explain for what do you need to set custom path.

**Comment by hervehobbes** [comment]
Hello,

Being able to select the install folder and drive is a very good option for end user when you have a very small SSD disk.

I'm very interested by a such option.
