### ISSUE TITLE
Mac preview or quick view

### ISSUE THREAD

**Issue by Bruno-de-l-Escaille** [electron-userland/electron-builder#1223]
* **13.0.0**: 

* **Mac**: 

How to do a mac preview, or you can name it also quick view. By pressing space button to have a quick look at the content of the app. I have an app viewer and I must have this option.

**Comment by develar** [comment]
Sorry, I don't have time to investigate it. http://superuser.com/questions/230204/make-os-xs-quick-look-work-for-custom-file-extensions
