### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by rophy** [electron-userland/electron-builder#1225]
From [Publishing-Artifacts#GithubOptions](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#GithubOptions) it seems to assume github.com. Is github enterprise supported?

**Comment by develar** [comment]
Not tested at all. Feedback wanted.

**Comment by theuniverse** [comment]
@rophy @develar Any test on this part, is GitHub Enterprise supported?

**Comment by develar** [comment]
@theuniverse Just try it. Should work.
