### ISSUE TITLE
Github Update Fails Due to Undefined

### ISSUE THREAD

**Issue by AlienHoboken** [electron-userland/electron-builder#1228]
electron-builder version:
* **13.3.1**: 

electron-updater version:
* **1.6.0**

target:
* **osx 64bit**: 

Hello, when running the auto-updater with electron-builder I'm receiving the following error (in the log file). It is essentially providing the host as "undefined" when looking for updates. 

```
Error: Error: Unable to find latest version on github, please ensure a production release exists: HttpError: 404 Not Found
"method: undefined url: https://undefined/AlienHoboken/{repo}/releases/latest
```

However my `latest-mac.json` has the correct details.

```
{
  "version": "0.1.0",
  "releaseDate": "2017-02-09T19:15:09.434Z",
  "url": "https://github.com/AlienHoboken/{repo}/releases/download/v0.1.0/{app}-0.1.0-mac.zip"
}
```

Is this a setup issue or an issue within electron-builder?

EDIT:
I've even tried adding the host to the `app-updated.yml`, still the same result
```
provider: github
host: github.com
owner: AlienHoboken
repo: {repo}
```

**Comment by develar** [comment]
Cannot reproduce, but some improvements were made in the 1.6.1
