### ISSUE TITLE
--config option

### ISSUE THREAD

**Issue by Frugality** [electron-userland/electron-builder#1229]
* **13.3.2**: 

* **Windows**: 

The Options wiki page references a "config" argument, which would allow you to specify different yml files for configuring your build. This is exactly what I needed! Unfortunately, it looks like that argument wasn't fully exposed. When I run the command, it tells me that the "config" argument doesn't exist:

`build --config electron-builder.prod.yml
`
```
Building:
[... lines omitted ...]
See the Wiki (https://github.com/electron-userland/electron-builder/wiki) for
more documentation.

Unknown argument: config
```

I would love to have this option! Right now I copy my yml file onto electron-builder.yml immediately before my build. Wiki page reference here: https://github.com/electron-userland/electron-builder/wiki/Options

Cheers,
-Courtland

**Comment by develar** [comment]
Will be added in 3 days.

**Comment by Frugality** [comment]
Awesome, thank you!!!
