### ISSUE TITLE
(armv7l) does not match system (armhf)

### ISSUE THREAD

**Issue by cyberquito** [electron-userland/electron-builder#1230]
* **Version**: 7.26.0

* **Target**: armv7l, Linux

Hi, when installing the .deb package for armv7l, on a raspberry PI 3 using Ubuntu Mate 16.04 I got the following error:

package architecture (armv7l) does not match system (armhf)

I'm using Mac OS X Sierra for development.

Thank you,

Quito

**Comment by develar** [comment]
https://github.com/electron/electron/issues/6055

**Comment by develar** [comment]
Closed due to #5706

**Comment by ryaz** [comment]
I'm not sure if it is the same issue, but I have raspberry pi3  and I built electron with --arch arm7l and that's what I'm getting:
```
dpkg: error processing archive adtop_0.1.0_armv7l.deb (--install):
 package architecture (armv7l) does not match system (armhf)
Errors were encountered while processing:
 adtop_0.1.0_armv7l.deb
pi@raspberrypi:~ $ uname -m
armv7l
```

**Comment by AlexanderKosianchuk** [comment]
Now i understand that it is not related to neither to electron nor to electron-builder:
```
sudo dpkg --add-architecture armv7l
````
But I think, it really would be helpful for many people if this row will find some reflection in doc.

**Comment by manast** [comment]
@AlexanderKosianchuk however the installation fails for me with errors of the kind:
```
Depends: libnotify4:armv7l but it is not installable
```

an apt-get update gives errors of the kind:
```
N: Skipping acquire of configured file 'main/binary-armel/Packages' as repository 'http://archive.raspberrypi.org/debian stretch InRelease' doesn't support architecture 'armv7l'
```

This was tested on the latest DietPi installation...

Any ideas?

**Comment by jtc42** [comment]
Interestingly, I've just found that if I run the unpacked application on my Pi, it works fine. As soon as I roll it into a deb, it stops working, because it doesn't want to install armv7l packages on an armhf system. Any ideas?

**Comment by andreolaya** [comment]
The same problem, I am trying to create a version of the application in .snap for arch arm7l but it does not work, "(armv7l) does not match system (armhf)".

**Comment by jtc42** [comment]
Okay so I made progress on this. The problem is that although the packaged Electron app for Armv7l will run just fine on a Pi, the Pi primarily uses the Armhf architecture. When electron-builder generates a deb or snap file from the packaged application, it lists the target architecture as armv7l.

If you want it to install on a Pi, the target arch of the snap or deb must be armhf. I've not tried this with snap packages, but I fixed our debs using the config:

```
...
linux:
  target:
    - target: deb
      arch:
        - armv7l
deb:
  fpm: ['--architecture', 'armhf']
electronVersion: 3.0.13

```

FPM is used by electron-builder to generate deb files, and so by overriding the `--architecture` option of FPM, you can put the armv7l package into an armhf deb file, and it works just fine.

Again, not tested with snaps, but hopefully this will help others somewhat.

**Comment by abulka** [comment]
@jtc42 Amongst dozens of failed posts and attempts re building an Electron .deb for Raspberry Pi yours seems the most promising, however I'm not sure how to convert your yaml syntax into a package.json JSON.  I tried adding your config fragment to `vue.config.js` but not sure if its correct

```js
module.exports = {
  transpileDependencies: [
    'vuetify'
  ],
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        // options placed here will be merged with default configuration and passed to electron-builder
        productName: 'Electron-Vue',
        appId: 'com.electron-vue.app',
        linux: {
          category: "Education",
          target: [
            {
              target: "deb",
              arch: [
                "armv7l"
              ]
            }
          ]
        },
        deb: {
          fpm: ["--architecture", "armhf"]
        }
      }
    }
  }
}
```

I ran with

    vue-cli-service electron:build --linux

but still got same error when attempting to install the .deb on the Raspberry Pi `Depends: libnotify4:armhf but it is not installable` etc.
