### ISSUE TITLE
[Urgent needed feature] Installer icon and application icon for Squirrel build mode

### ISSUE THREAD

**Issue by dzunglht** [electron-userland/electron-builder#1232]
Currently, Squirrel build doesn't support changing installer icon (kindly note that installer icon and application icon play different role for company identity and product identity) meanwhile we can change installer icon for NSIS build mode. We love your work and great achievements so far, please help support changing installer icon for Squirrel build via json build configurations.
Tons of Thanks,

**Comment by develar** [comment]
Squirrel.Windows is broken by design in this aspect and due to this and another number of reasons is deprecated. We don't waste our time to support it. Only maintaining. If you for some reasons cannot migrate to robust and maintainable NSIS — please file corresponding issue.
