### ISSUE TITLE
Avoid using an installed certificate when building mac package

### ISSUE THREAD

**Issue by LouWii** [electron-userland/electron-builder#1233]
* **Version**: 7.13.0

* **Target**: mac

Hi there,

I'm trying to build my app on a macbook that has a *Developer ID Application* certificate in the keychain that I don't want to use. It's installed for some Xcode development but I don't want to use it for my Electron app.
Is it possible to do that ? Because right now, it's picking it up automatically even if I set the `identity` parameter to an empty string. If I set it to whatever, electron builder will throw an error and won't build the `.dmg`.

Also, I tried to enter a *Mac Developer* certificate, but electron builder doesn't seem to find it. I believe it has to be a *Developer ID Application* certificate, is that correct ? If yes, how can I get one without registering an Apple Dev account and pay the $100 fees (if that's even possible)?

(Yes, I'm all lost with this certificate thing)

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Code-Signing

Set `CSC_IDENTITY_AUTO_DISCOVERY=false` env.

> even if I set the identity parameter to an empty string

Yes, `null` is not supported, but should be.

**Comment by develar** [comment]
>  I tried to enter a Mac Developer certificate, but electron builder doesn't seem to find it

You should set identity name (and id if need).

If you have `Mac Developer: Vladimir Krivosheev (744739DJ4Y)` cert, set `CSC_NAME` / identity to `Vladimir Krivosheev (744739DJ4Y)`.
