### ISSUE TITLE
App icon in wrong place when the build.productName is chinese

### ISSUE THREAD

**Issue by wangyibin** [electron-userland/electron-builder#1234]
* **Version**: 
electron-builder v13.3.1

* **Target**: 
mac dmg

Steps:
1. clone the project https://github.com/chentsulin/electron-react-boilerplate
1. modify the build.productName in package.json from "ElectronReact" to "你好"
1. run `npm run package`
1. open the dmg file, you can see the app icon in wrong place.

![image](https://cloud.githubusercontent.com/assets/678122/22823096/30ef8ba0-efbd-11e6-9e50-2427fa756bc4.png)

**Comment by lizzie** [comment]
#1335  the same problem.
