### ISSUE TITLE
Cannot find electron dependency to get electron version in the 'H:\www\gif\package.json'

### ISSUE THREAD

**Issue by govenlive** [electron-userland/electron-builder#1238]
* **Version 1.4.15**: 

* **Target win x64**: 

Pack to win always prompt as title

**Comment by develar** [comment]
Or add electron as dev dependency, or specify option https://github.com/electron-userland/electron-builder/wiki/Options#configuration-options-electronVersion

**Comment by govenlive** [comment]
thinks,I have according to your solution!
