### ISSUE TITLE
latest-mac.yml not generated

### ISSUE THREAD

**Issue by elhachmi** [electron-userland/electron-builder#1244]
* **electron-builder: 13.3.2**: 

* **electron-updater : 1.3.1**

* **mac: OSX 10.11.6**: 

I run npm run release, all things goes very nice, packaging to dmg, publishing to github, except latest-mac.yml file.

my script relase
```json
"release": "export GH_TOKEN=XXX && build -m",
```

my mac config
```json
    "mac": {
      "icon": "xx/xx/icon.icns",
      "target": "dmg",
      "publish": [
        {
          "provider": "github",
          "owner": "xxxx",
          "repo": "xx-xx"
        }
      ],
      "category": "xx.xx.xx.com",
      "extraResources": [
        {
          "from": "resources/xx",
          "to": "./xx"
        }
      ]
    },
```

**Comment by develar** [comment]
latest-Mac.json is uploaded in case of Mac.

**Comment by develar** [comment]
File is not generated because you set target to DMG. Please change to default target (remove explicit target). Update file is generated for zip.

**Comment by elhachmi** [comment]
Ok I found it in PublishManager.js, that is not mentioned on doc ;)
That's mean if I build a dmg and distribut it, he cannot be auto updated even if I publish zip and dmg to github with latest-mac.yml?

**Comment by develar** [comment]
> cannot be auto updated even if I publish zip and dmg to github with latest-mac.yml?

`latest-mac.json` will be generated alongside `zip`. What is  the problem?

**Comment by elhachmi** [comment]
Ok, no problem 😄
