### ISSUE TITLE
autoUpdater github pre-release

### ISSUE THREAD

**Issue by willyb321** [electron-userland/electron-builder#1247]
* **Version**: 13.5.0

Autoupdater version: 1.6.1

* **Target**: 
Windows

Is there a way with github auto-update to not download / install pre-releases. ie mark release as pre-release on github, then user opens program and currently it says to update. what would be good is if user opens program and doesn't see update till marked as latest?

**Comment by develar** [comment]
If release is marked as pre-release, it is ignored by electron-builder. Could you please provide link to your GitHub repo?

**Comment by willyb321** [comment]
Huh. Must've been a weird bug. Just tested it again, worked properly. [Here](https://github.com/willyb321/elite-journal/tree/master) is the repo if you need it. Thanks for the reply though.
