### ISSUE TITLE
Can't redefine MUI_WELCOMEFINISHPAGE_BITMAP for NSIS target

### ISSUE THREAD

**Issue by drakerui** [electron-userland/electron-builder#1248]
* **Version**: 10.17.3

* **Target**: win x64 NSIS

Can't redefine MUI_WELCOMEFINISHPAGE_BITMAP.

I tried to include this but the compilation fails because it is being defined elsewhere and I can't tell where.
```
!macro customHeader
  !define MUI_WELCOMEFINISHPAGE_BITMAP "${BUILD_RESOURCES_DIR}\installerSidebar.bmp"
!macroend
```
Am I missing something?

**Comment by develar** [comment]
1. Use 13.6.0
2. Did you set `oneClick: false` to enable boring installer?

**Comment by drakerui** [comment]
1. Ok, updated
2. Yes, here's the nsis section just in case:

```
"nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowElevation": false,
    }
```
Still get the same issue after the update, heres the error:
```
!define: "MUI_WELCOMEFINISHPAGE_BITMAP" already defined!
Error in macro customHeader on macroline 1
Error in script "<stdin>" on line 28 -- aborting creation process
```

**Comment by develar** [comment]
Feature (`installerSidebar.bmp`) will be added tomorrow CET. I cannot advise you without investigation . I think in any case electron-builder should allow you just put file `installerSidebar.bmp` into the build resources to customise installer sidebar.

**Comment by drakerui** [comment]
I see, thanks for the help.
I got it to work by replacing the default image manualy.
