### ISSUE TITLE
Can't find nodeHttpExecutor

### ISSUE THREAD

**Issue by einsibjani** [electron-userland/electron-builder#1252]
* **Version**: 13.6.0

* **Version**: 1.1.1

* **Target**: mac, linux

I setup a new Mac OS build server and my build failed with the error:

resolve 'file' or 'directory' out/nodeHttpExecutor in /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util
      resolve file
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor doesn't exist
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor.js doesn't exist
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor.jsx doesn't exist
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor.json doesn't exist
      resolve directory
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor doesn't exist (directory default file)
        /Users/jenkins/workspace/svarbox-client-ng-mac-development/node_modules/electron-builder-util/out/nodeHttpExecutor/package.json doesn't exist (directory description file)

So I tried upping the electron-builder version from ^11.5.1 (11.7.0 effective) to 13.6.0. Now the mac project builds, but the Linux build fails with the same error 😮

**Comment by einsibjani** [comment]
Got it to build on the linux machine by deleting node_modules and running npm install again. I'd like to know why it happened, but it's not critical any more.

**Comment by develar** [comment]
Do not use unreliable and buggy NPM, please use [yarn](https://yarnpkg.com) instead.
