### ISSUE TITLE
Location of app-update.yml

### ISSUE THREAD

**Issue by mikecao** [electron-userland/electron-builder#1254]
* **Version**: 
electron-builder 13.5.0
electron-updater 1.6.1

* **Target**: 
Win x64
MacOS

It looks like appUpdater checks for `app-update.yml` inside the electron `dist/resources` folder. Without it you'll get an error like:

```
Error: Error: ENOENT: no such file or directory, open 
'C:\Users\mike\AppData\Roaming\npm\node_modules\electron\dist\resources\app-update.yml'
```

This is problematic because if you install electron globally and use it to run applications using `electron path/to/app`, you will need to change the file depending on which app you're running. Even if electron is installed locally you have to place the file in there to do any testing.

I would suggest first looking in the app folder that is running, and then falling back to the electron folder if not found. Or make it configurable so we can set the location.

**Comment by develar** [comment]
auto-update supported only for installed applications. In the dev mode you should not use it. Please use https://github.com/sindresorhus/electron-is-dev to check.

Anyway — PR will be accepted.

**Comment by YamiChat** [comment]
I use auto-update for installed application
```
[2017-02-14 18:45:25:0741] [info] App starting...
[2017-02-14 18:45:30:0698] [info] Checking for update
[2017-02-14 18:45:30:0698] [info] Checking for update...
[2017-02-14 18:45:31:0713] [error] Error: Error: ENOENT: no such file or directory, open '/Volumes/Chat/Chat.app/Contents/Resources/app-update.yml'
    at Error (native)
From previous event:
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:238:27
    at next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:271:11)
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:147:33
    at next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:225:11)
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:137:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at MacUpdater._checkForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:181:11)
    at MacUpdater.checkForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:119:35)
    at Timeout._onTimeout (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/main.js:80:15)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-02-14 18:45:31:0713] [info] Error in auto-updater.
```
Use this example https://github.com/iffy/electron-updater-example

**Comment by mikecao** [comment]
Ok, I was able to get it to work by adding this to my code:

```
if (isDev) {
    autoUpdater.updateConfigPath = path.join(APP_PATH, 'app-update.yml');
}
```

The reason I need to run it in dev is because my application allows the user to trigger the update check manually, so I need to make sure that everything is working. Thanks for the great work on this project.

**Comment by develar** [comment]
@mikecao How does it work on macOS where code sign is required?

**Comment by develar** [comment]
Ah, I see that your error about windows (where code sign will be required later ;) if exe is signed).

**Comment by mikecao** [comment]
@develar I haven't tested macOS yet but plan to soon. I'll let you know if I run into any issues.

It is fine if the install part doesn't work because I can always build an installer and test that. But during dev I need to make sure I can at least trigger the update check and perform the download. So far it's working on Windows. When I exit my dev application, it installs the application update externally, so dev doesn't actually get the update, but that's ok.

**Comment by develar** [comment]
Too many complains. Reconsidered to be fixed.

**Comment by mikecao** [comment]
@develar You're right, code signing does cause a problem. I tested macOS and got the error, `Could not get code signature for running application`. I assume the same thing will happen when Windows signing is required.

I think my workaround is good enough for now since it allows me to at least test the update request. This probably doesn't need a fix. But It might be helpful to update the wiki to tell people they need to manually copy the `app-update.yml` after building if they want to test in dev. Or load it themselves using `updateConfigPath`.

**Comment by mikecao** [comment]
Maybe something like this will work?

```javascript
autoUpdater.setConfig({
  provider: 'generic',
  url: 'https://website.com/download',
  channel: 'latest'
});
```

Production can still use the `app-update.yml` file while in dev you will have to configure it manually.

**Comment by develar** [comment]
In the next version file `dev-app-update.yml` will be searched in the `app path` in a dev mode. Prefix `dev-` is used to make it clear, that file only for a dev mode.
