### ISSUE TITLE
Transitioning from Squirrel to NSIS

### ISSUE THREAD

**Issue by sklink** [electron-userland/electron-builder#1256]
* **Version**: 13.5.0

* **Target**: Win x64 ia32

A ton of users already have my Squirrel application. It uses the typical `electron` `autoUpdater` methods with `setFeedURL` and a `nuts` server.

I have a NSIS build created that operates properly and uses `electron-builder`'s `autoUpdate` and GitHub Releases. I've tested the NSIS version's auto update and I've confirmed that it's working.

How do I release a version to my current users that will properly uninstall the Squirrel version and install the NSIS version?

**Comment by develar** [comment]
Duplicates #837
