### ISSUE TITLE
codesign framework in node_modules

### ISSUE THREAD

**Issue by richmonkey** [electron-userland/electron-builder#1257]
* **13.7.0**: 

* **1.4.15**: 

codesign error:bundle format is ambiguous

I put *.app into node_modules,
Builder will  codesign the whole framework directory.

https://gist.github.com/jorangreef/27e708c67b7e6746a98a

**Comment by develar** [comment]
You should not use any other scripts to sign. electron-builder will sign for you. https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by richmonkey** [comment]
NO, I do't use other tools to codesign, the link is just information reference by search the error that output of electron-builder.

My app use one package that contain a app(screencapture.app), electron-builder can't codesign the screencapture.app.

**Comment by develar** [comment]
@richmonkey Please set env `DEBUG=electron-builder,electron-osx-sign*` and attach log of the terminal output.

**Comment by richmonkey** [comment]
> bauhinia@0.1.0 dist /Users/houxh/production/bauhinia/bauhinia_desktop
> build

No native production dependencies
Packaging for darwin x64 using electron 1.4.15 to dist/mac
Signing app (identity: Developer ID Application: Zhifeng Zhou (HB5A8TLKYL))
Error: Command failed: codesign --sign Developer ID Application: Zhifeng Zhou (HB5A8TLKYL) --force /Users/houxh/production/bauhinia/bauhinia_desktop/dist/mac/bauhinia.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture/bin/ScreenCapture.app/Contents/Frameworks/SCKit.framework/SCKit
/Users/houxh/production/bauhinia/bauhinia_desktop/dist/mac/bauhinia.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture/bin/ScreenCapture.app/Contents/Frameworks/SCKit.framework/SCKit: replacing existing signature
/Users/houxh/production/bauhinia/bauhinia_desktop/dist/mac/bauhinia.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture/bin/ScreenCapture.app/Contents/Frameworks/SCKit.framework/SCKit: bundle format is ambiguous (could be app or framework)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at MacPackager.sign (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/macPackager.js:265:11)
    at /Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/src/macPackager.ts:82:26
From previous event:
    at /Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/src/macPackager.ts:82:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/macPackager.js:173:11)
    at /Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/src/packager.ts:229:22
From previous event:
    at Packager.doBuild (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/packager.js:350:11)
    at /Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/src/packager.ts:157:38
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/packager.js:256:11)
    at /Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/src/builder.ts:217:65
    at next (native)
From previous event:
    at build (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/builder.js:71:21)
    at Object.<anonymous> (/Users/houxh/production/bauhinia/bauhinia_desktop/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bauhinia@0.1.0 dist: `build`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the bauhinia@0.1.0 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bauhinia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bauhinia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bauhinia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/houxh/production/bauhinia/bauhinia_desktop/npm-debug.log

**Comment by richmonkey** [comment]
The terminal log is same whether DEBUG env set or not set.

**Comment by develar** [comment]
@sethlu could you please advice?

**Comment by sethlu** [comment]
Hi @richmonkey @develar right now I can find a nested app bundle structure, which does seem usual 😕 I am personally not sure how to sign such app bundles or `ScreenCapture.app` should be manually placed at `Contents/Bundles/ScreenCapture.app` which is outside the scope of `electron-builder` currently?

@richmonkey I would suggest using `electron-builder` to package your app first (without the screen capture nested app bundle in `node_modules`) and manually move the nested app to under `Contents/Bundles` without calling `electron-osx-sign`. The signing of the nested app could be differently signed (I am not very sure)? Then we can probably try `electron-osx-sign` with the `--ignore="Bundles"` flag to skip resigning the nested app?

**Comment by black-snow** [comment]
@richmonkey Is this still an issue for you?

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

Donation/PR/votes are welcome.

**Comment by richmonkey** [comment]
electron-builder-lib/out/macPackager.js

**Comment by stevebaxter** [comment]
We have a similar problem, we have a node module that contains a framework that itself contains a framework (this is a very common pattern on the Mac). Electron-builder tries to sign the outer framework before the inner one and fails (they need to be signed in order).

**Comment by stevebaxter** [comment]
It looks like we need to use `codesign --sign --deep` for this to do the right thing.

**Comment by pieterdt** [comment]
that --deep flag didn't solve it for me though.
