### ISSUE TITLE
Building error (makensis)

### ISSUE THREAD

**Issue by UltraDosaaf** [electron-userland/electron-builder#1258]
Desperately trying to get installation package for win and mac :(
Maybe someone could help me with my first try.

**Project structure**
![2017-02-14_14-31-12](https://cloud.githubusercontent.com/assets/25608313/22927454/697f0362-f2c2-11e6-873e-1f80d6731aad.png)

**package.json**
```
{
    "version": "1.0.0",
    "productName": "App",
    "name": "electron-quick-start",
    "description": "Test Application.",
    "homepage": "http://foo.example.com",
    "author": "Mi Mo Mu",
    "license": "MIT",
    "main": "main.js",
    "scripts": {
        "start": "electron ."
    },
    "build": {
        "asar": true,
        "appId": "com.company.application",
        "copyright": "Copyright 2016 Corporation. All rights reserved.",
        "productName": "Application",
        "mac": {
            "title": "Test Title",
            "target": "dmg"
        },
        "win": {
            "target": "nsis"
        },
        "nsis": {
            "perMachine": true
        }
    },
    "devDependencies": {
        "electron": "latest",
        "electron-builder": "latest",
        "electron-packager": "latest"
    }
}
```

**Terminal output**

> C:\Users\it\Desktop\test_builder>build
> No native production dependencies
> Packaging for win32 x64 using electron 1.4.15 to dist\win-unpacked
> ⚠️  Application icon is not set, default Electron icon will be used
> Building NSIS installer
>   Packaging NSIS installer for arch x64
> Error: C:\Users\it\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.7\Bin\makensis.exe exited with code 3221225781
>     at ChildProcess.childProcess.once.code (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder
> -util\src\util.ts:134:14)
>     at ChildProcess.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> From previous event:
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:368:5
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.executeMakensis (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:417:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:199:16
> From previous event:
>     at NsisTarget.computeScript (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:270:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:174:68
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.buildInstaller (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:243:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:71:18
>     at next (native)
> From previous event:
>     at NsisTarget.finishBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:154:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:237:31
> From previous event:
>     at Packager.doBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:350:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:157:38
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at Packager.build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:256:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:217:65
>     at next (native)
> From previous event:
>     at build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:71:21)
>     at Object.<anonymous> (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\cli\build-cli.js:71:41)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> C:\Users\it\Desktop\test_builder>

**Comment by develar** [comment]
1. Disable MS Defender.
2. Remove C:\Users\it\AppData\Local\electron-builder\cache\nsis
3. Build again.

**Comment by UltraDosaaf** [comment]
1. Don't have it (Win 7 x64)

2. Done 
![2017-02-14_15-14-30](https://cloud.githubusercontent.com/assets/25608313/22928648/918be072-f2c8-11e6-842f-5fc5c1a34161.png)

3. Done
> C:\Users\it\Desktop\test_builder>build
> No native production dependencies
> Packaging for win32 x64 using electron 1.4.15 to dist\win-unpacked
> ⚠️  Application icon is not set, default Electron icon will be used
> Building NSIS installer
>   Packaging NSIS installer for arch x64
> Error: C:\Users\it\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.7\Bin\makensis.exe exited with code 3221225781
>     at ChildProcess.childProcess.once.code (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder
> -util\src\util.ts:134:14)
>     at ChildProcess.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Socket.<anonymous> (internal/child_process.js:334:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:498:12)
> From previous event:
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:368:5
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.executeMakensis (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:417:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:199:16
> From previous event:
>     at NsisTarget.computeScript (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:270:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:174:68
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.buildInstaller (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:243:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:71:18
>     at next (native)
> From previous event:
>     at NsisTarget.finishBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:154:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:237:31
> From previous event:
>     at Packager.doBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:350:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:157:38
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at Packager.build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:256:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:217:65
>     at next (native)
> From previous event:
>     at build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:71:21)
>     at Object.<anonymous> (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\cli\build-cli.js:71:41)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> C:\Users\it\Desktop\test_builder>

**Comment by develar** [comment]
Well, please try to extract https://bintray.com/electron-userland/bin/download_file?file_path=nsis-3.0.1.7.7z to C:\Users\it\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.7 Is your windows user is SYSTEM?

**Comment by UltraDosaaf** [comment]
Not sure am I "SYSTEM" user or not. But I have full admin rights, if it's what youre question is about.

Extracted and rebuilded:
> C:\Users\it\Desktop\test_builder>build
> No native production dependencies
> Packaging for win32 x64 using electron 1.4.15 to dist\win-unpacked
> ⚠️  Application icon is not set, default Electron icon will be used
> Building NSIS installer
>   Packaging NSIS installer for arch x64
> Error: C:\Users\it\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.7\Bin\makensis.exe exited with code 3221225781
>     at ChildProcess.childProcess.once.code (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder
> -util\src\util.ts:134:14)
>     at ChildProcess.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> From previous event:
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:368:5
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.executeMakensis (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:417:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:199:16
> From previous event:
>     at NsisTarget.computeScript (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:270:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:174:68
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.buildInstaller (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:243:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:71:18
>     at next (native)
> From previous event:
>     at NsisTarget.finishBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:154:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:237:31
> From previous event:
>     at Packager.doBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:350:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:157:38
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at Packager.build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:256:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:217:65
>     at next (native)
> From previous event:
>     at build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:71:21)
>     at Object.<anonymous> (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\cli\build-cli.js:71:41)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> C:\Users\it\Desktop\test_builder>

**Comment by develar** [comment]
I will test it using Win 7 tomorrow morning CET.  For now you can set `LOCALAPPDATA` to some another directory (e.g. `C:\electron-builder_localappdata` https://github.com/electron-userland/electron-builder/issues/1164#issuecomment-275048015)

**Comment by UltraDosaaf** [comment]
Will wait, thak you. 

Set another folder, but still no luck:
> C:\Users\it\Desktop\test_builder>build
> No native production dependencies
> Packaging for win32 x64 using electron 1.4.15 to dist\win-unpacked
> ⚠️  Application icon is not set, default Electron icon will be used
> Building NSIS installer
>   Packaging NSIS installer for arch x64
> Error: C:\electron-builder_localappdata\electron-builder\cache\nsis\nsis-3.0.1.7\Bin\makensis.exe exited with code 3221225781
>     at ChildProcess.childProcess.once.code (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder
> -util\src\util.ts:134:14)
>     at ChildProcess.g (events.js:291:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> From previous event:
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:368:5
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.executeMakensis (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:417:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:199:16
> From previous event:
>     at NsisTarget.computeScript (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:270:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:174:68
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at NsisTarget.buildInstaller (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:243:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\targets\nsis.ts:71:18
>     at next (native)
> From previous event:
>     at NsisTarget.finishBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\targets\nsis.js:154:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:237:31
> From previous event:
>     at Packager.doBuild (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:350:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:157:38
>     at next (native)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)
> From previous event:
>     at Packager.build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:256:11)
>     at C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:217:65
>     at next (native)
> From previous event:
>     at build (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:71:21)
>     at Object.<anonymous> (C:\Users\it\AppData\Roaming\npm\node_modules\electron-builder\out\cli\build-cli.js:71:41)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> C:\Users\it\Desktop\test_builder>

**Comment by develar** [comment]
Please try 13.8.0

If no luck, please try to install nsis manually http://nsis.sourceforge.net/Download

**Comment by UltraDosaaf** [comment]
Updated to 13.8.0

![2017-02-15_12-26-28](https://cloud.githubusercontent.com/assets/25608313/22969137/5e6789c4-f37e-11e6-992b-67bf6eefc159.png)


I've installed nsis manually and the fun part is... I can't build directly through nsis :)

![2017-02-15_12-58-53](https://cloud.githubusercontent.com/assets/25608313/22969222/bd761912-f37e-11e6-8529-6fff3182d63e.png)

**Comment by develar** [comment]
Please try to update windows 7 (maybe it is outdated and some update exists) or https://www.google.de/search?client=safari&rls=en&q=install+msvcp60&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=VSmkWLLOAYfAaNSuhcgF

**Comment by UltraDosaaf** [comment]
Tested on 4 more PCs and... you was totaly right, it is missed Windows update.
Spasibo, Vladimir!

**Comment by UweKeim** [comment]
Just came here via Google. In my case the cause was that the "Bin" folder of my NSIS3 installation was missing (due to my own fault).

Maybe this information may help others in the future.
