### ISSUE TITLE
GitHub URL in latest-mac.json gets the file name wrong

### ISSUE THREAD

**Issue by kobens** [electron-userland/electron-builder#1259]
* **Version**: latest

* **Target**: MacOS/Windows

When I build my app I get a github folder with a `latest-mac.json` file as expected. However there's a mismatch between the GitHub URL in `latest-mac.json` and the actual .zip-file being produced. 

`latest-mac.json`:
```json
{
  "version": "0.1.3",
  "releaseDate": "2017-02-14T12:39:51.844Z",
  "url": "https://github.com/myuser/myrepo/releases/download/v0.2.0/name-0.2.0-mac.zip"
}
```

and the file is called `productName-0.2.0-mac.zip`.

Shouldn't the url use `productName` rather than `name` (from `package.json`) so I can just upload both files as GitGub releases without having to change anything?

`package.json` looks like:

```
{
  "name": "name",
  ...
  "build": {
    "productName": "productName",
    "publish": {
      "provider": "github",
      "repo": "myrepo"
    }
  },
  ...
}
```

**Comment by develar** [comment]
@kobens For github you must use file in the `github` directory, not in the root.

**Comment by develar** [comment]
> I can just upload both files as GitGub releases without having to change anything?

electron-builder uploads file to GitHub using correct name. Please do not upload manually, but use https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

**Comment by kobens** [comment]
Thanks for the quick reply. I have my source code in a private github repo, and wanted to upload builds manually to a public 'releases' repo. Can I still do that?

**Comment by develar** [comment]
> Will it publish automatically to the public repo if I set that as the build.publish.repo?

Yes. You can set all options `owner` and repo` to not rely on automatic detection rules.

**Comment by kobens** [comment]
Why is there a naming difference for files published to GitHub, though?

**Comment by develar** [comment]
Because Github has stupid silly file naming restrictions.
