### ISSUE TITLE
 In MAC Sierra the app the app will not open after installing it

### ISSUE THREAD

**Issue by dariocavada** [electron-userland/electron-builder#1260]
* **Version**: 13.3.0

* **Target**: mac 

build a dmg for mac.

After installing the application and opening the app nothing happens. 
Only the menu "quit" and no other errors. 

Launching using electron (in the source) is working properly.

**Comment by develar** [comment]
Unlikely it is bug of electron-builder. So, debug it. Also see Console -> system.log

**Comment by ritz078** [comment]
@dariocavada Any solution for this? facing the same issue.
