### ISSUE TITLE
how to unpack folder into resources directly

### ISSUE THREAD

**Issue by asarimbekov** [electron-userland/electron-builder#1264]
* **Version**: 13.6.0

* **Target**: win

Hi, 

after using asar.Unpack my folder gets unpacked in the resources/app.asar.unpacked/folder. Is there a way to unpack my folder without placing it to app.asar.unpacked and directly into resources?

Thanks

**Comment by develar** [comment]
> Is there a way to unpack my folder without placing it to app.asar.unpacked and directly into resources?

https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraResources

**Comment by asarimbekov** [comment]
Sorry, still didn't get it.

If I use extraResources, then that folder will be added to the final asar package. What I want is to rename the unpacked folder. I thought about the workaround to exclude the folder from being packaged and then add it as an extra resource, however, exclusion didn't work for me (probably I used it wrongly) and the whole workaround seems a bit weird.

"build": {
        "asar": true,
        "files": ["!release/java${/*}"],
        "extraResources": {
            "from":"release/java",
            "to":"java"
        }
}

Here my asar file grows in size, I assume the java folder is added twice.

"build": {
        "asar": true,
        "asarUnpack": "java",
       }

Here the java folder is unpacked to app.asar.unpacked and I want it to be renamed to java

**Comment by develar** [comment]
Well, everything is correct and ok, but if extraResources is not excluded by default and included into the asar — it is bug. Is it possible to provide project to reproduce?

**Comment by asarimbekov** [comment]
Sorry, my bad. Was excluding the wrong directory. It works perfectly!

**Comment by develar** [comment]
It should be excluded by default if listed in the extraResources.
