### ISSUE TITLE
Linux - snap - plugs deprecated

### ISSUE THREAD

**Issue by patricksebastien** [electron-userland/electron-builder#1265]
* **Version**: 13.8.0
* **Target**: Linux - snap

Hi, I just sent you a donation, building a snap package of a electron application is really nice, so thank you.

I want to use a webcam. I am building this sample application: https://github.com/hokein/electron-sample-apps/tree/master/camera adding "plugs": ["default", "camera"]. When running the application with electron it works, but when trying to launch the snap it doesn't work.

I have this error when building, maybe it's related?
DEPRECATED: Custom plugins should now be placed in 'snap/plugins'.
See http://snapcraft.io/docs/deprecation-notices/dn2 for more information.

Thank you

**Comment by develar** [comment]
** All the snapcraft specific asset handling has been moved to the snap directory as the preferred location for the following: **

https://github.com/snapcore/snapcraft/releases/tag/2.26

**Comment by develar** [comment]
Thanks for donation and report — latest snapcraft is supported (and required).
