### ISSUE TITLE
electron-updater Support for private Github repository

### ISSUE THREAD

**Issue by AlienHoboken** [electron-userland/electron-builder#1266]
electron-builder version: **13.7.0**: 

electron-updater version: **1.6.4**

Target **Windows**: 

Electron updater seems unable to locate my private Github repository even when the GH_TOKEN environment variable is set. I've tried setting the env variable through the system settings, programatically by altering `process.env.GH_TOKEN`, and even passing the `token` parameter in app-update.yml (which seems it might be respected after looking into electron-updater's code). I've verified via logging that `process.env.GH_TOKEN` is properly set to my token which has all permission scopes granted.

Is there something I am missing or is there a known issue with private Github repositories? If I make the repo public then updater finds it and updates perfectly, so the integration is good.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/891#issuecomment-259210935

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/529#issuecomment-263202612

**Comment by develar** [comment]
As your app code is available fir everyone, electron updater can use only public resources.

**Comment by AlienHoboken** [comment]
Is there a reason for that limitation? Why can't electron-updater access private resources with a proper authentication token?

**Comment by develar** [comment]
Where a proper authentication token can be stored? Or do you want to somehow set it programmatically in setFeedURL?

**Comment by AlienHoboken** [comment]
The use case is like this:

We have an application which will be distributed on controlled machines, not distributed to the public. Therefore if we create a Github user with read only privileges to our private repository we are fine with storing an authentication token for that user on the machine (in an environment variable, app-update.yaml, wherever) so they can pull releases to update.

Would this be possible with electron-updater? And if so, could you point me in the correct direction?

**Comment by develar** [comment]
You need to write own provider and use api instead of public URL to download files and get latest info. Would you like to help and create PR?

**Comment by AlienHoboken** [comment]
Yeah if it's doable then I'm fine writing it and submitting a PR. You think the best way to proceed is a new provider? Or should github provider be extended to support private repositories?

**Comment by develar** [comment]
I prefer new provider because code will be totally rewritten.

**Comment by AlienHoboken** [comment]
Sounds good, will update with PR

**Comment by AlienHoboken** [comment]
Submitted PR #1343

**Comment by develar** [comment]
Please try electron-updater 1.9.0 (thanks to @AlienHoboken)
