### ISSUE TITLE
Different icons for application/file extension with same name on macOS and Windows

### ISSUE THREAD

**Issue by iffy** [electron-userland/electron-builder#1268]
* **Version**: ^13.6.0

* **Target**: Mac/Win/Linux

My application is named `LHTML` and the file extensions it knows about are `lhtml` (same but lowercase).

Here's the pertinent parts of my `package.json`:

```
{
  "name": "lhtml",
  "productName": "LHTML",
  ...
  "build": {
    ...
    "fileAssociations": [
      {
        "ext": "lhtml",
        "role": "Editor",
        "icon": "build/lhtmldoc.icns"
      }
    ],
    ...
  },
}
```

So I have these icons:

- `build/icon.icns` (macOS application icon)
- `build/icon.ico` (Windows application icon)
- `build/lhtmldoc.icns` (macOS `.lhtml` document icon)
- `build/lhtmldoc.ico` (Windows `.lhtml` document icon)

I don't have a way of specifying the `.lhtml` document icon for both Windows and macOS.

I propose supporting something like:

```
    "fileAssociations": [
      {
        "ext": "lhtml",
        "role": "Editor",
        "icon": "build/lhtmldoc.${iconExt}"
      }
    ],
```

**Comment by develar** [comment]
Why you cannot name file as `lhtml.icns`?

> because the app's icon is `Contents/Resources/LHTML.icns` and if the file icon is `lhtml.icns` it can put it at `Contents/Resources/lhtml.icns` because my filesystem won't allow it

**Comment by matiastucci** [comment]
I'm trying to do the same. My app has an icon and I want a different icon for my `fileAssociations` (same icon for Windows and OS X).  Is this already possible?

**Comment by iffy** [comment]
@matiastucci yes; here's how I did it: https://github.com/iffy/lhtml/blob/master/package.json#L54

**Comment by matiastucci** [comment]
@iffy awesome. Thanks 👍
