### ISSUE TITLE
changing the appId during the build

### ISSUE THREAD

**Issue by asarimbekov** [electron-userland/electron-builder#1269]
* **Version**: 13.9.0

* **Target**: win

Is there a way to change the appId during the build? I've tried --em.appId=newAppId, but it didn't work. I've realized that I have to change the appIds to prevent the installer from installing the app to the same folder. I have different installers per environment, such as dev and prod. If I don't change the appId both installers will point to the same location. This will happen only if for instance dev is already installed and one tries to install prod or vice-versa.

**Comment by develar** [comment]
`-c.appId=newApId`?

**Comment by asarimbekov** [comment]
yes, it helped! Wouldn't it be better to document these options available in new version?

**Comment by develar** [comment]
See `  build --config.nsis.unicode=false  configure unicode options for NSIS` in the readme. Yeach, it should be documented on the Options page.
