### ISSUE TITLE
Error: Please specify "bucket" for "s3" update server

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#1270]
* ** "electron-builder": "^13.9.0",**: 

* **macOS + Windows**: 

Fresh install and doing a build and getting 
```
Error: Please specify "bucket" for "s3" update server
    at /Users/framerate/code/whatever/client/node_modules/electron-builder/src/publish/publisher.ts:14:13
```

I have my own bash scripts that update to s3, so I'm not sure what this is caused from and I don't see any issues anywhere regarding it? I assume there's an option I can turn this off?

**Comment by framerate** [comment]
I'm able to roll back to a previous package.json configuration, but I'd like to know what caused this so I can fix it and do a proper upgrade to latest builder! Thanks!

**Comment by develar** [comment]
I suggest you to use our new publisher instead of your own.

Cause — AWS credentials headers are detected and s3 publisher in action. Set publisher to null to disable publishing.

**Comment by develar** [comment]
Rules documented in the https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

**Comment by develar** [comment]
Or do you have explicit generic provider configured?

**Comment by framerate** [comment]
It's odd, I didn't even know you COULD publish using this app. I've been working on this app for a year and I upgrade `electron-builder` every 2-3 months. This time I jumped from `11.X` to `13.X` when this was happening.

```
"release": "npm run build && npm run dist && npm run dist-win"
"build": "cross-env NODE_ENV=production webpack --config webpack.config.production.js --progress --profile --colors",
"dist": "build",
"dist-win": "build --platform=win32"
```

is my build setup, if it helps.

My deplyToS3 script just uses the aws command line tools to upload directly to s3 and invalidate cloudfront distributions.

I rolled back my package.json and manually updated electron-builder to `  "electron-builder": "^13.5.0",` and was able to build, so I have absolutely no idea why I was getting this vague error. I guess leave this closed but if you have any ideas what caused it I'd love to know!

**Comment by develar** [comment]
> AWS_SECRET_ACCESS_KEY are set and neither GH_TOKEN and BT_TOKEN are set — defaults to [{provider: "s3"}].

So, if you set these env, s3 publisher in action. If you don't want to use electron-builder publisher — set `publish` to `null`.

```
"build": {
  "publish": null
}
```

**Comment by framerate** [comment]
Yes!

Those are part of my environment for the AWS CLI. So I assume this update was why the major semver got updated, that's super breaking! 

Thanks for clearing it up! I'll take a look at your publisher this weekend :)

**Comment by develar** [comment]
> that's super breaking!

Yep. It is the reason we have so big version (13, and 14 is coming soon ;)).

**Comment by framerate** [comment]
thank you! @develar 👍
