### ISSUE TITLE
Install dependencies on OS during the app install ?

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1271]
Hi,

Is there a simple way to install OS libraries during the application install (or first launch) on Windows, macOS and Linux ? As example, if my application require a FUSE library (osxfuse on macOS) ?

**Comment by develar** [comment]
> macOS

`pkg` target and custom pre or post scripts. Or just ask user to install.


> Windows

Using custom script https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script

> Linux

FUSE preinstalled. I think maybe only some dep package should be bundled for AppImage or deb or snap.

**Comment by popod** [comment]
@develar thanks for very useful answer !

**Comment by develar** [comment]
Feel free to ask about concrete target or investigate — e.g. for snap you must configure additional plugs `fuse-support`.
