### ISSUE TITLE
Snaps for different architectures

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#1272]
* **13.9.0**: 

* **Linux**: 

Hello.
Is it possible to build the snap for 32bit under 64bit?
When I'm trying to build with --ia32 on the 64bit Ubuntu I get:
`Building for a different target architecture requires a plugin specific implementation in the 'desktop-glib-only' plugin
`

And also a small issue. When I'm trying to use [shell.openExternal](http://electron.atom.io/docs/api/shell/#shellopenexternalurl-options-callback) to open a link in the default browser it doesn't work. I've tried node modules like [this](https://www.npmjs.com/package/open). Don't work too. Do you have any ideas about it?

Thanks in advance.

**Comment by develar** [comment]
Supported in the latest snapcraft, but not yet on electron-builder side (https://github.com/snapcore/snapcraft/releases/tag/2.26 stage packages). Not sure about `desktop-glib-only`.

**Comment by develar** [comment]
>  When I'm trying to use shell.openExternal to open a link in the default browser it doesn't work

No permissions, I guess. https://snapcraft.io/docs/reference/interfaces `browser-support` is added by default. No idea what is required.

**Comment by sagorshkov** [comment]
@develar There is something else, I guess. My app works as the server and when I had not added a "network-bind" permissions(didn't add by default) in the [logs](https://snapcraft.io/docs/build-snaps/debugging) there was alert log like (please add plug 'network-bind'). But in this case, there are not any logs... Looks like some another cause... 

Ok, thanks for your answer. Do you plan to add the possibility to build snaps for both architectures at once?

**Comment by develar** [comment]
> Do you plan to add the possibility to build snaps for both architectures at once?

I doubt that snap can do this, but in any case it will be supported on electron-builder side (arch option)  as now there is a request. Please note — we ALREADY pass arch flag to snapcraft.

**Comment by sagorshkov** [comment]
Also, when I start the span there are these logs in the terminal:
```
git:(linux) ✗ my-snap
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```

**Comment by develar** [comment]
I have tried to get rid of this in the past but no luck. Bloody Linux weird stuff. Currently, I don't want and don't have time to investigate it. Last time was decided/investigated that it can be safely ignored.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/pull/416

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by akashnimare** [comment]
@develar I also get the same error as mentioned [here](https://github.com/electron-userland/electron-builder/issues/1272#issuecomment-280639085). I get this error with all the snap packages except Slack so I think there should be a workaround for the same.
