### ISSUE TITLE
latest-mac.json is not being created when publishing to Github

### ISSUE THREAD

**Issue by adamsiwiec** [electron-userland/electron-builder#1277]
* **Version**: 
11.2
1.7.1

* **Target**: 
Windows
Mac

Whenever publishing to Github, there is not latest-mac.json included in the release, but there is a latest.yml file being published. This is also exactly the same in my `dist` directory: There is a latest.yml, but no latest-mac.json. Why is it not there?

**Comment by develar** [comment]
Version 11 is old. Latest is 13.9.0

**Comment by adamsiwiec** [comment]
Still doesn't work with the latest version.

**Comment by johngodley** [comment]
@adamsiwiec have you changed the Mac build target setting from default?

I had specified DMG only in my Mac target and had the same problem of no `latest-mac.json` being created. After changing the Mac target back to the default (which produces zip and DMG) then `latest-mac.json` is generated.

**Comment by develar** [comment]
`latest-mac.json` is produced only if `zip` in the target list. Default target for macOS is ` ["dmg", "zip"]`

**Comment by adamsiwiec** [comment]
Why is it not produced with a dmg? The latest-mac.json definitely needs to be created no matter what type of target you are using. This needs to be changed in my opinion.

**Comment by sidneys** [comment]
I have the same problem with the latest-mac.json not being generated if publishing is disabled.

As i have my own deployment script, setting "build.publish = null" results in no json being generated, and thus auto-update not working.

**Comment by develar** [comment]
> As i have my own deployment script, setting "build.publish = null" results in no json being generated, and thus auto-update not working.

@sidneys In any case for auto-update you have to use at least [generic](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#GenericServerOptions) provider configured.

@adamsiwiec Squirrel.Mac is used under the hood and, so, `zip` is required in addition to dmg.

**Comment by sidneys** [comment]
@develar 

When setting "generic" as a provider, the build process aborts due to missing configuration (url, etc.), which is not needed in the first place in environments with custom publishing/deployment processes which would nonetheless use the auto-updating feature.

Is generation of these auto-update json  files tied to configuring a publisher? If so, this should be made separate, for example by providing an `build.autoUpdate = true` option in order to disentangle the **publish** and **auto-update** features.

**Comment by develar** [comment]
@sidneys URL is required and will be used to generate update file — latest-Mac. What's wrong?

**Comment by develar** [comment]
@sidneys GitHub cannot be used as generic server. Why our GitHub publisher is not suitable for you? Anyway — you are not forced to use it. Please disable publishing using CLI --publish=never and remove publish from config. GitHub provider will be detected automatically or set it explicitly.

**Comment by sidneys** [comment]
@develar 

Aren't the "latest" JSON and YML files required for auto update, apart from publishing?

**Comment by develar** [comment]
@sidneys required and generated always regardless of publishing. Even if never.
