### ISSUE TITLE
dist app quit unexpectedly caused by productName

### ISSUE THREAD

**Issue by xingoxu** [electron-userland/electron-builder#1278]
* **Version**: 13.9.0

* **Target**: macOS 10.12.3

Steps:

1. git clone https://github.com/xingoxu/electron-quick-start and you can see https://github.com/xingoxu/electron-quick-start/commit/42cd3af630783c306773408bd3201f458a583b2e I've only changed the productName
2. run `npm install && npm run dist` on macOS
3. open the dist app and you will see like this

![image](https://cloud.githubusercontent.com/assets/8542907/23113602/2786d9d8-f774-11e6-9e6b-f0a5cb41114e.png)

I've tried to test with the same length word like `Electron Quick Start` and it went well. Really weird, isn't it?

**Comment by develar** [comment]
As workaround, don't use ` Helper` postfix of your product name.

**Comment by develar** [comment]
Solution to avoid "what? I need to change my product name?" Will be published in 30 minutes.

**Comment by develar** [comment]
Fixed in 13.11.1
