### ISSUE TITLE
how could I build ***-full.nupkg file on MacOSX?

### ISSUE THREAD

**Issue by divefox** [electron-userland/electron-builder#1279]
* **Version**: 11.5.1

* **Target**: generate windows auto-update file ( ***-full.nupkg)

Hi，
    I want to build windows auto-update file on my macOS.But it doesn't work for me.It is only create the `test Setup 1.0.2.exe` file for me,not include the updated file named test-1.0.3-full.nupkg.
( I search the relate issues from your page and google it, but none of them work ).
Parts of my development package.json file is:
*****************************************
"scripts": {
    "start": "electron ./app --enable-logging",
    "dev": "NODE_ENV='development' gulp dev",
    "postinstall": "install-app-deps",
    "pack": "build --platform=win32 --arch=x64",
    "dist": "build -mwl --x64 --ia32",
    "dist:osx": "build -m --x64 --ia32",
    "dist:win64": "build -w --x64"
  },
  "build": {
    "appId": "com.product.test",
    "dmg": {
      "title": "test",
      "background": "build/background.jpg",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "win": {
      "iconUrl": "http://***/favicon.ico",
      "icon": "build/icon.ico"
    }
  },
  "repository": {
    "type": "git"
  },
  "license": "LGPL",
  "devDependencies": {
    "electron-builder": "^11.5.1",
    "electron-prebuilt": "^1.4.13"
  },
  "electronVersion": "1.4.3"
****************************************
How can I solve it? 
Pls help me, thank you!

**Comment by develar** [comment]
Squirrel.Windows is deprecated in favour of NSIS. I recommend you to use electron-updater https://github.com/electron-userland/electron-builder/wiki/Auto-Update

But if you insist to use Squirrel.Windows — set target to `squirrel ` and install `electron-builder-squirrel-windows` dependency in addition.

**Comment by develar** [comment]
Also, use latest electron-builder.

**Comment by divefox** [comment]
@develar 
Thank you very much!
I read the doc and download [electron-updater-example](https://github.com/iffy/electron-updater-example) to test.But still not generate the "example 0.3.3-full.nupkg" file.Is that something wrong?
parts of json file is:
*****************
"build": {
    "appId": "com.github.iffy.electronupdaterexample",
    "mac": {
      "category": "your.app.category.type",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "nsis": {
      "perMachine": true
    },
    "publish": [{
            "provider": "generic",
            "owner": "test",
            "repo": "test-example",
            "url": "http://10.20.103.64/update/${os}_${arch}"
        }]
  }
*****************
And I modify the package.json for [publis generic](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#publish-generic-any-https-server), it generate latest.yml (or latest-mac.json). The doc says these two files must uploaded to the server and then will check update.But my server is built by [electron-release-server](https://github.com/ArekSredzki/electron-release-server). It only can upload .zip .dmg .exe or .nupkg extended file.Is that means I can't use this server to control file? Just like the SimpleHTTPServer is OK?

Thanks again！
