### ISSUE TITLE
NSIS ExecWait Bug

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1281]
* **Version**: 13.5.0

Electon Updater: 1.6.0

* **Target**: x64

Weird bug I found when writing an installation script. Not sure if it is a NSIS bug or something you are doing interfering.

```
StrCpy $2 "$TEMP\Visual C++ 2015 Redistributable.exe"
MessageBox MB_OK "${PRODUCT_NAME} uses Microsoft Visual C++ 2015 Redistributable (x64) to run. \
						 $\r$\nWe cannot seem to find it on your system. It will now be downloaded and installed."        
nsisdl::download /TIMEOUT=30000 ${MS_VCPP_64_URL} $2
Pop $R0 ;Get the return value
    StrCmp $R0 "success" +3
      MessageBox MB_ICONSTOP "Download failed: $R0"
      Abort
ExecWait $2
Delete $2
```

If you use the above code segement 2 times but just change the first line to be something like: `$TEMP\Visual C++ 2015 Redistributable x86.exe`

if the original file name exists for some reason it just executes that one instead of the newly downloaded x86.exe. Seems like a path bug or something where it is just finding the first .exe that is matching the most words or something really freaking weird. Simply renaming the second file to be something completely different fixes the problem.

**Comment by develar** [comment]
Have you tried wrap in quotes: `ExecWait "$2"`

**Comment by FromStoneage** [comment]
@mastergberry verify that your $2 variable finds the right location of the executable. I have the same call in my custom NSIS script it works just fine with or without quotes.
