### ISSUE TITLE
Incorrect app-update.yml for Windows 32bit

### ISSUE THREAD

**Issue by adammeyer** [electron-userland/electron-builder#1282]
* **Version**: 13.11.1

* **Target**: Windows 32 and 64bit
`Platform.WINDOWS.createTarget('nsis-web', Arch.x64, Arch.ia32);`

My publish settings are:
`
publish: {
        provider: 'generic',
        url: 'https://domain.com/update/${os}_${arch}'
      }
`

Both 64bit and 32bit builds output the same `app-update.yml` in the resources directory.
`provider: generic
url: 'https://domain.com/update/win_x64'`

The 32bit build should have a different arch variable. Correct?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/NSIS#32-bit--64-bit

**Comment by develar** [comment]
Fixed, arch doesn't matter for windows, so, will be `'https://domain.com/update/${os}'`
