### ISSUE TITLE
Build with prepackaged app doesn't do anything for mac

### ISSUE THREAD

**Issue by dperetti** [electron-userland/electron-builder#1284]
13.10.1

mac

    ./node_modules/.bin/build --mac --pd /Users/dom/Dropbox/dev/codestory/binaries/MyApp-darwin-x64/MyApp.app

Immediately quits with no error or warning.

Works with --win. (and I'm on a Mac).

**Comment by dperetti** [comment]
I'm not the only one, apparently cc @develar.

**Comment by debelop13** [comment]
Yes, with --win works, --mac no.

**Comment by dperetti** [comment]
Linux : AppImage builds but doesn't run. Deb works but installed in /opt and no shortcut to apps in Ubuntu. Snap : error on build. :-(

**Comment by develar** [comment]
Reproduced. Fix will be in several hours.

**Comment by develar** [comment]
macOS: please try 14.1.1

**Comment by develar** [comment]
Snap fixed as well in the 14.1.1.

**Comment by develar** [comment]
Feel free to file new issue if something still  broken in the 14.1.1

**Comment by debelop13** [comment]
It works! Great!
