### ISSUE TITLE
Do not recommend StartCom for code signing certificates

### ISSUE THREAD

**Issue by arekkas** [electron-userland/electron-builder#1287]
See:

- https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html
- https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

**Comment by develar** [comment]
Code sign certs are valid. Only browser certs were affected.

**Comment by arekkas** [comment]
Since google and mozilla are on this, and startcom/wosing apparently misleads customers, I see two risks here:

a. microsoft might jump on it too
b. why recommend companies that aren't properly doing their job

**Comment by develar** [comment]
@arekkas Done.

**Comment by arekkas** [comment]
Thanks!
