### ISSUE TITLE
Snap : cp: cannot stat '/out/myappdir-snap': No such file or directory

### ISSUE THREAD

**Issue by dperetti** [electron-userland/electron-builder#1288]
13.11.1

Linux / snap

    DEBUG=electron-builder ./node_modules/.bin/build --linux --x64 -c ./distribute/electron-builder.yml --pd /Users/dom/Dropbox/dev/codestory/binaries/CodeStory-linux-x64
        
    cp: cannot stat '/out/CodeStory-linux-x64-snap': No such file or directory
[full output.txt](https://github.com/electron-userland/electron-builder/files/791932/output.txt)

**Comment by develar** [comment]
Duplicates #1284
