### ISSUE TITLE
Pinned program in windows taskbar unpinned after update

### ISSUE THREAD

**Issue by kutu** [electron-userland/electron-builder#1293]
* **Version**: 13.11.1

electron-updater: 1.7.1

* **Target**: nsis

Pinned program in windows taskbar unpinned after update

first line of my `main.js`
```js
require('electron').app.setAppUserModelId('ru.kutu.app');
```
in `package.json`
```json
{
	"build": {
		"appId": "ru.kutu.app",
```

**Comment by develar** [comment]
Duplicates #926
