### ISSUE TITLE
NSIS Artifact Name

### ISSUE THREAD

**Issue by AG-Shawn** [electron-userland/electron-builder#1296]
* **Version**: 14.1.1

* **Target**: NSIS - Win32 & Win64

I'm trying to create two executables with NSIS one for Windows 32bit and one for Windows 64bit, I'm able to create both fine, however they both export to the same filename causing the first one create to be overwritten. I thought using artifactName in build.nsis would solve the problem, however the "arch" variable doesn't seem to be working.

Any ideas what I could do to get a unique filename for each build, or what I'm doing wrong with the artifactName property?

Thanks

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/NSIS

One installer contains both arch.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/NSIS
