### ISSUE TITLE
Add option to specify what files to uninstall

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1298]
* **Version**: 13.5

* **Target**: NSIS

So some of my users apparently think it's a good idea to install their application onto their Desktop or into their Documents folder.....Terrible idea. To be clear instead of installing it into `C:\Users\<username>\Desktop\<Application Name>` they are doing `C:\Users\<username>\Desktop`

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/nsis/uninstaller.nsh#L42

This line is nuking their other files if they install it into a dumb location.

Is there a way to remove just the files we installed by default and possibly extra files also such as logs or something? I would even just be content with uninstalling the original files we installed and then use the customUnInstall macro to clean up the other ones.

**Comment by mastergberry** [comment]
I submitted a basic PR that will be a smart "temporary" solution assuming the programmer knows what is being bundled in the installation.

In theory all original installed files should be accounted for somewhere in the uninstaller. The current solution gives more power to the programmer to make the decision how they want to uninstall the program.

**Comment by develar** [comment]
It is why we don't allow to choose installation directory by default.

This feature was rejected to be implemented because by default user cannot choose installation directory.

> So some of my users apparently think it's a good idea to install their application onto their Desktop or into their Documents folder.....Terrible idea. 

Proper solution will be to automatically detect such folders and create subdir for app. Could you please file PR?

**Comment by mastergberry** [comment]
Sure I can attempt it. Will try to submit something in a couple of hours or so.

**Comment by mastergberry** [comment]
@develar So I found where to shove the code and the way I am thinking of doing this at the moment would check the `$APP_FILENAME` and see if it still in `$INSTDIR` after the `!insertmacro MUI_PAGE_DIRECTORY`

I have found this function to help with this http://nsis.sourceforge.net/StrContains

Is there some easier way to do it without having to include this extra function into the installer? If not where should this function be put?

**Comment by develar** [comment]
> where should this function be put?

`include` dir in the `nsis`.

**Comment by mastergberry** [comment]
I created a possible fix although I have not yet had time to test it. I can test it later this weekend or I can submit a PR for you to test/merge it in @develar

**Comment by develar** [comment]
@mastergberry Looks good for me (but not tested). You can file a PR.
