### ISSUE TITLE
Usage of ArtifactName with Bintray  Auto-Update

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#1305]
* **Electron Builder Version**: 14.4.0

* **Electron Updater Version**: 1.7.1

* **Target**: 
Windows NSIS

Hi, I just wanted to clarify the usage of the relatively new `artifactName` option that we can now use during the build process. Currently everything works perfectly using Bintray as our publisher (pre custom artifactName), but it seems like it might not take any custom artifact names into account when retrieving the latest update file: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/BintrayProvider.ts#L36

I may be mistaken, but it seems hardcoded to expect a file named `${AppName} Setup ${Version}.exe`.

Is it currently possible to define a custom artifactName with Bintray?

Thanks so much,
Nader

**Comment by develar** [comment]
What pattern do you use?

**Comment by naderhen** [comment]
I'm currently using the two package.json structure, targeting Windows with NSIS specifically. I'm experimenting with using electron-builder programmatically (as we deploy to many different environments and configurations in CI) so my config looks more or less like this:

```
{
    targets: Platform.WINDOWS.createTarget('nsis'),
    config: {
        directories: {
            app: 'electron',
            output: 'release'
        },
        publish: {
            provider: 'bintray',
            user: 'my@email',
            package: 'packagename',
            repo: 'reponame',
            owner: 'mybintrayownername'
        }
    }
};
```

**Comment by develar** [comment]
@naderhen Thanks, could you please specify `artifactName` that you want to use?

**Comment by naderhen** [comment]
Ideally, it would simply be something like `${AppName}.exe`.

**Comment by develar** [comment]
> Ideally, it would simply be something like ${AppName}.exe.

Keep in mind, that Bintray requires file name to be unique across all versions, so, filename should include version.

**Comment by develar** [comment]
Please try electron-updater 1.8.0
