### ISSUE TITLE
Allow usage of environmental variables in extraFiles and extraResources

### ISSUE THREAD

**Issue by liusy182** [electron-userland/electron-builder#1307]
* **Version**:  14.1.1

* **Target**: Windows

I have a electron native module that integrates with a third party library. The third party library has different configurations (x86 v.s. x64, Debug v.s. Release). I am thinking if it is a good idea to have electron-builder's `extraFiles` and `extraResources` accept file path with environmental variables. For example, 
```
 "extraFiles": [{
      "from": "third_party/%PLATFORM%/%DEBUG_RELEASE%",
      "to": "./"
    }],
```
If I set env `PLATFORM` to `x86` and `DEBUG_RELEASE` to `Release`. I want the files in `third_party/x86/Debug` to be copied to `./`.

Right now I can workaround this by having another script that modifies `package.json` based on different configurations.

**Comment by develar** [comment]
${env.ENV_NAME} — any environment variable.

**Comment by liusy182** [comment]
That is fast. Thanks a lot !
