### ISSUE TITLE
Dependencies in two package.json structure

### ISSUE THREAD

**Issue by ajbeaven** [electron-userland/electron-builder#1309]
At the end of [this document](https://github.com/electron-userland/electron-builder/blob/master/docs/Two%20package.json%20Structure.md), it is stated:

> If you use the two-package.json project structure, you'll only have your devDependencies in your development package.json and your dependencies in your app package.json.

Looking through [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json), it seems that this advice isn't followed and the project `package.json` file includes a list of dependencies as well as devDependencies.

Could you please clarify whether it's the docs or the boilerplate that is wrong here?

**Comment by develar** [comment]
Interesting question. Please open issue in the electron-react-boilerplate project ;)
