### ISSUE TITLE
How create Installer for all platforms together?

### ISSUE THREAD

**Issue by BulgakowS** [electron-userland/electron-builder#1311]
I'm trying find the way to create separated installer for each platform, and I need the each of them install already all platform apps in one folder. 
Assume on each of platforms I'm need install all of them. 
For example, I'm install app on flash drive at windows, go to mac and just launch mac version from this flash drive.

Can anyone help me with this? 

I'm hope you understand my english))

**Comment by develar** [comment]
> I'm hope you understand my english)) 

Не совсем понял. Нужен portable?

Do you need portable versions?

**Comment by develar** [comment]
Win: `--win portable` to produce portable.
Mac: `--mac dir` to produce `.app` bundle. You don't need dmg or pkg.
Linux: `--linux` Default appimage target is portable.

**Comment by develar** [comment]
All these args can be passed to `build` on macOS (you can build all only on macOS). https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by BulgakowS** [comment]
> Не совсем понял. Нужен portable?
> 
> Do you need portable versions?

Нужны инсталяторы что бы устанавливали все платформы сразу а не только свою. Как-то так. 
Что бы я на винде/маке/линуксе мог с одного инсталятора распаковать в папку все три платформы сразу и перейдя на другую платформу с этой папкой не устанавливал заново.

**Comment by develar** [comment]
Создаете portable как описано выше (https://github.com/electron-userland/electron-builder/issues/1311#issuecomment-283064031) и пользователь можно скачать их себе на флешку и запускать безо всякой инсталляции.
