### ISSUE TITLE
Error code signing on MacOS

### ISSUE THREAD

**Issue by ghego1** [electron-userland/electron-builder#1312]
* **electron-builder**: `14.5.2`

* **target**: MAS, `build --mac mas`

On building the production version of the app, I get these errors:

    Packaging for darwin x64 using electron 1.4.13 to dist/mac
    Error: Please remove prefix "Developer ID Application:" from the specified name — appropriate certificate will be chosen automatically
    at checkPrefix (/builds/electron/node_modules/electron-builder/src/codeSign.ts:230:11)
    at findIdentity (/builds/electron/node_modules/electron-builder/src/codeSign.ts:222:7)
    at /builds/electron/node_modules/electron-builder/src/macPackager.ts:136:22
    at Generator.next (<anonymous>)
    From previous event:
    at MacPackager.sign (/builds/electron/node_modules/electron-builder/out/macPackager.js:272:11)
    at /builds/electron/node_modules/electron-builder/src/macPackager.ts:82:26
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    From previous event:
    at /builds/electron/node_modules/electron-builder/src/macPackager.ts:82:10
    at Generator.next (<anonymous>)
    From previous event:
    at MacPackager.pack (/builds/electron/node_modules/electron-builder/out/macPackager.js:181:11)
    at /builds/electron/node_modules/electron-builder/src/packager.ts:252:22
    at Generator.next (<anonymous>)
    at /builds/electron/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:35:14
    at FSReqWrap.oncomplete (fs.js:111:15)
    From previous event:
    at Packager.doBuild (/builds/electron/node_modules/electron-builder/out/packager.js:371:11)
    at /builds/electron/node_modules/electron-builder/src/packager.ts:163:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    From previous event:
    at Packager.build (/builds/electron/node_modules/electron-builder/out/packager.js:263:11)
    at /builds/electron/node_modules/electron-builder/src/builder.ts:217:33
    at Generator.next (<anonymous>)
    From previous event:
    at build (/builds/electron/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/builds/electron/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by develar** [comment]
**Please remove prefix "Developer ID Application:" from the specified name — appropriate certificate will be chosen automatically**

**Comment by ghego1** [comment]
From where should I remove "Developer ID Application:"? In the keychain?

**Comment by develar** [comment]
Have you specified CSC_NAME?

**Comment by ghego1** [comment]
No, that's my problem, I have not specified the name of the certificate anywhere. I'm relying on the autodetect feature as when building the `.dmg` version.

**Comment by develar** [comment]
I am on vacation. I will check on Saturday. Are you sure that all required certs are there in keychain?

**Comment by ghego1** [comment]
I believe that all the needed certificates are there. I am indeed able to sign and distribute on the Mac App Store apps with Xcode, and I can sign dmg packages with electron builder.

Testing some more I've found out some potentially useful info: I'm now on electron-builder 12.3.1, I have downgraded thinking that the problem might had been with the newer version.

Turns out that that is not the case. I have tried to build the dmg with `npm run dist` (`build`) and it failed for the same reason (`Error: Please remove prefix ...`). I then ran `sudo npm run dist`, and the dmg was generated successfully, properly signed.

I have tried to build the `MAS` version with `sudo build --mac mas`, and the app is generated, with these messages:

    Packaging for mas x64 using electron 1.4.13 to dist/mas
    Signing app (identity: 3rd Party Mac Developer Application: TEAM (XXX))

But then, when launching the app, it crashes even before the window is generated due to `Exception Type: EXC_CRASH (Code Signature Invalid)`

I've even tried to submit it to the store, and it rejected the package saying that some signing details are inaccessible as having admin privileges (which I'm guessing is the result of using `sudo`).

**Comment by develar** [comment]
If possible, 
Please set env DEBUG=electron-builder and attach full log of the terminal output.

**Comment by ghego1** [comment]
Sure, glad to help. Only 1 problem: where should I set the env? My scripts look like this:
    
    "scripts": {
      "postinstall": "install-app-deps",
      "dist": "build",
      "mas": "build --mac mas",
      "dist-mac": "build --mac",
      "dist-linux": "build --linux deb",
      "dist-win32": "build --win --ia32",
      "dist-win64": "build --win --x64"
    },

**Comment by develar** [comment]
`DEBUG=electron-builder npm run mas`

**Comment by ghego1** [comment]
Here's the terminal output:

    > build --mac mas

    No native production dependencies
    Packaging for mas x64 using electron 1.4.13 to dist/mas
      electron-builder Spawning /Users/ghego/builds/electron/node_modules/7zip-bin-mac/7za x -bd /Users/ghego/.electron/electron-v1.4.13-mas-x64.zip -o/Users/ghego/builds/electron/dist/mas +0ms

    7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
    p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

    Scanning the drive for archives:
    1 file, 41161005 bytes (40 MiB)

    Extracting archive: /Users/ghego/.electron/electron-v1.4.13-mas-x64.zip
    --
    Path = /Users/ghego/.electron/electron-v1.4.13-mas-x64.zip
    Type = zip
    Physical Size = 41161005

    Everything is Ok

    Folders: 125
    Files: 84
    Size:       109292112
    Compressed: 41161005
      electron-builder /Users/ghego/builds/electron/node_modules/7zip-bin-mac/7za (5649) exited with code 0 +1s
      electron-builder Dev or extraneous dependencies: 7zip-bin, 7zip-bin-mac, ansi-align, ansi-regex, ansi-styles, argparse, array-find-index, asar-electron-builder, yauzl, yargs-parser, yargs, y18n, xtend, xmldom, xmlbuilder, xdg-basedir, write-file-atomic, wrap-ansi, wrappy, widest-line, which-module, verror, yargs-parser/node_modules/camelcase, yargs/node_modules/camelcase, validate-npm-package-license, uuid, util-deprecate, uuid-1345, utf8-byte-length, url-parse-lax, update-notifier, unzip-response, typedarray, tweetnacl, tunnel-agent, truncate-utf8-bytes, trim-newlines, tough-cookie, timed-out, through2, throttleit, supports-color, strip-json-comments, sumchecker, strip-indent, strip-bom, strip-ansi, through2/node_modules/xtend, stringstream, string_decoder, string.prototype.codepointat, string-width, sshpk, stat-mode, sprintf-js, speedometer, spdx-license-ids, spdx-expression-parse, spdx-correct, source-map-support, source-map, sntp, sshpk/node_modules/assert-plus, slide, single-line-log, signal-exit, semver-diff, set-blocking, semver, sanitize-filename, rimraf, require-main-filename, require-directory, request, registry-url, repeating, registry-auth-token, redent, rimraf/node_modules/glob, readable-stream, read-pkg-up, read-all-stream, rc, qs, read-pkg, punycode, progress-stream, progress, process-nextick-args, pretty-bytes, prepend-http, plist, read-all-stream/node_modules/isarray, rc/node_modules/minimist, read-all-stream/node_modules/readable-stream, pinkie-promise, pinkie, pify, pend, path-type, path-is-absolute, path-exists, parse-json, parse-color, package-json, os-tmpdir, os-locale, osenv, os-homedir, once, object-keys, object-assign, oauth-sign, number-is-nan, nugget, normalize-package-data, node-emoji, node-status-codes, ms, mkdirp, minimist, minimatch, mime-types, mime, mime-db, meow, nugget/node_modules/minimist, map-obj, macaddress, lowercase-keys, loud-rejection, load-json-file, lcid, lazy-req, meow/node_modules/minimist, latest-version, klaw, jsprim, jsonfile, jsonpointer, json-stringify-safe, json-schema, js-yaml, jsbn, jodid25519, isstream, isbinaryfile, isarray, is-utf8, is-typedarray, is-stream, is-retry-allowed, is-redirect, is-property, is-obj, is-npm, is-my-json-valid, is-fullwidth-code-point, is-ci, is-finite, is-builtin-module, is-arrayish, ini, invert-kv, inflight, inherits, indent-string, imurmurhash, http-signature, home-path, hosted-git-info, hoek, hawk, has-ansi, har-validator, graceful-readlink, graceful-fs, got, get-stdin, getpass, get-caller-file, generate-object-property, fs.realpath, generate-function, fs-extra-p, form-data, fs-extra, forever-agent, find-up, filled-array, fd-slicer, got/node_modules/isarray, getpass/node_modules/assert-plus, got/node_modules/readable-stream, extsprintf, extract-zip, extend, esprima, escape-string-regexp, es6-promise, find-up/node_modules/path-exists, electron-prebuilt, error-ex, electron-macos-sign, electron-download-tf, electron-builder-util, electron-builder-http, extract-zip/node_modules/debug, extract-zip/node_modules/mkdirp, electron-builder-core, ecc-jsbn, electron-builder, duplexer2, electron-prebuilt/node_modules/electron-download, electron-prebuilt/node_modules/fs-extra, electron-prebuilt/node_modules/minimist, electron-prebuilt/node_modules/path-exists, electron-prebuilt/node_modules/sumchecker, electron-download-tf/node_modules/minimist, electron-builder-util/node_modules/debug, electron-builder-http/node_modules/debug, dot-prop, delayed-stream, deep-extend, decamelize, debug, dashdash, currently-unhandled, duplexer2/node_modules/readable-stream, duplexer2/node_modules/isarray, cuint, cryptiles, create-error-class, configstore, core-util-is, concat-stream, concat-map, dashdash/node_modules/assert-plus, commander, compare-version, combined-stream, color-convert, code-point-at, configstore/node_modules/uuid, cliui, concat-stream/node_modules/isarray, concat-stream/node_modules/readable-stream, cli-boxes, ci-info, chromium-pickle-js, chalk, caseless, camelcase-keys, capture-stack-trace, camelcase, builtin-modules, buffer-shims, brace-expansion, boxen, bluebird-lst-c, boom, bluebird, bcrypt-pbkdf, base64-js, aws4, balanced-match, asynckit, asn1, assert-plus, aws-sign2 +4ms
    Error: Please remove prefix "Developer ID Application:" from the specified name — appropriate certificate will be chosen automatically
        at checkPrefix (/Users/ghego/builds/electron/node_modules/electron-builder/src/codeSign.ts:230:11)
        at findIdentity (/Users/ghego/builds/electron/node_modules/electron-builder/src/codeSign.ts:222:7)
        at /Users/ghego/builds/electron/node_modules/electron-builder/src/macPackager.ts:120:22
    From previous event:
        at MacPackager.sign (/Users/ghego/builds/electron/node_modules/electron-builder/out/macPackager.js:249:11)
        at /Users/ghego/builds/electron/node_modules/electron-builder/src/macPackager.ts:101:18
    From previous event:
        at MacPackager.pack (/Users/ghego/builds/electron/node_modules/electron-builder/out/macPackager.js:173:11)
        at /Users/ghego/builds/electron/node_modules/electron-builder/src/packager.ts:210:22
    From previous event:
        at Packager.doBuild (/Users/ghego/builds/electron/node_modules/electron-builder/out/packager.js:335:11)
        at /Users/ghego/builds/electron/node_modules/electron-builder/src/packager.ts:151:38
        at Generator.next (<anonymous>)
        at runCallback (timers.js:651:20)
        at tryOnImmediate (timers.js:624:5)
        at processImmediate [as _immediateCallback] (timers.js:596:5)
    From previous event:
        at Packager.build (/Users/ghego/builds/electron/node_modules/electron-builder/out/packager.js:261:11)
        at /Users/ghego/builds/electron/node_modules/electron-builder/src/builder.ts:214:40
        at Generator.next (<anonymous>)
    From previous event:
        at build (/Users/ghego/builds/electron/node_modules/electron-builder/out/builder.js:63:21)
        at Object.<anonymous> (/Users/ghego/builds/electron/node_modules/electron-builder/out/cli/build-cli.js:68:41)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:420:7)
        at startup (bootstrap_node.js:139:9)
        at bootstrap_node.js:535:3

**Comment by ghego1** [comment]
Any updates?

**Comment by twvm** [comment]
Any updates on this issue? I am running into the same issue with electron 1.6.6 and electron-builder 16.7.1. I have the my Developer ID Application: ... certificate installed and set CSC_NAME to the full name of the certificate.
