### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by enjoydiy** [electron-userland/electron-builder#1313]
I have read the document many times. But I have not known how to use Programmatic Api to package app. Are there any description about programmatic wiki or example?

**Comment by develar** [comment]
Have you read https://github.com/electron-userland/electron-builder#programmatic-usage ?

**Comment by enjoydiy** [comment]
Yeah, `{
  targets: Platform.MAC.createTarget(),
  config: {
   "//": "build options, see https://goo.gl/ZhRfla"
  }
}`

Just these code, I still do not know how to write the config to make a windows portable app. Is any an example?

**Comment by develar** [comment]
```
{ targets: Platform.MAC.createTarget("portable"), config: { "//": "build options, see https://goo.gl/ZhRfla" } }
```

**Comment by enjoydiy** [comment]
Thank you. I try...

**Comment by enjoydiy** [comment]
Done. Awesome project. Thanks.
