### ISSUE TITLE
Different architectures for different platforms

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1314]
For example I want to create nsis installer for  Windovs --ia32 --x64 and Linux deb --x64;
Perhaps there is a way to specify in the configuration area to build? Something like this:
```
{
  "appId": "com.electron.app",
  "compression": "maximum",
  "platforms": {
    "win": ["ia32", "x64"],
    "linux": "x64"
  }
}
```
In this case there is no need to specify the architecture of the platform and the command line. 
Instead of this
```
build -wl --x64 --ia32
```
Suffice it to perform
```
build
```

**Comment by develar** [comment]
Proposed solution: targets should accepts not only name, but object — name, arch. It also will simplify programmatic API.

Thanks for nice feature request. Will be implemented when I will return from vacation. Or PR welcome.

**Comment by cawa-93** [comment]
@develar It shout be somsing like this:
```json
"targets": [{
    "arch": ["ia32", "x64"],
    "platform": "win",
    "target": "nsis"
  },{
    "arch": ["ia32", "x64"],
    "platform": "linux",
    "target": "deb"
  }{
    "arch": ["x64"],
    "platform": "linux",
    "target": "snap"
  }]
```

**Comment by develar** [comment]
@cawa-93 We currently already have `targets` in the platform specific options, so, `targets` will be specified in the corresponding platform specific (e.g. `win`, `mac` or `linux`).

So, I propose:

```js
{
 "target": "nsis",
  "arch": ["ia32", "x64"],
}
```

without `"platform"`. And you are right — `target` instead of `name` is better.

**Comment by cawa-93** [comment]
Then maybe it should be done as follows:
```json
{
  "win": {
    "targets": [{
      "name": "nsis",
      "arch": ["ia32", "x64"],
    }]
  },
  "linux": {
    "targets": [{
      "name": "deb",
      "arch": ["ia32", "x64"],
    }, {
      "name": "snap",
      "arch": ["x64"],
    }]
  }
```
The idea is to be able specify architecture to individually for each platform and each target

**Comment by develar** [comment]
BTW, `-w default:ia32` is supported :)

**Comment by develar** [comment]
You still need to specify platforms in the command line. `build -wl --x64 --ia32` => `build -wl`

**Comment by timfish** [comment]
To build x64 Deb & ia32/x64 NSIS, the final syntax looks something like:

```
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32",
            "x64"
          ]
        }
      ]
    },
    "linux": {
      "target": [
        {
          "target": "deb",
          "arch": [
            "x64"
          ]
        }
      ]
    },
```
