### ISSUE TITLE
[Feature Request] [electron-publisher-s3] Use ~/.aws/credentials file as alternative to env variables

### ISSUE THREAD

**Issue by Sukram21** [electron-userland/electron-builder#1320]
It would be great if one could also provide his AWS credentials by using a `~/.aws/credentials` file like recommended in the aws-sdk documentation (see https://aws.amazon.com/sdk-for-node-js/?nc1=h_ls) instead of having to supply them via environment variables.

**Comment by develar** [comment]
It is supported, but our check requires env in any case. It is bug.

**Comment by rdbell** [comment]
~/.aws/credentials allows for multiple named profiles. Ideally it would be nice if electron-publish also supported specifying a profile by name.

**Comment by dperrymorrow** [comment]
we ended up writing our own script for pushing to S3 for this very reason. Would love to see this not require `ENV` vars

**Comment by develar** [comment]
> By default, the SDK checks the AWS_PROFILE environment variable to determine which profile to use. If the AWS_PROFILE variable is not set in your environment, the SDK uses the credentials for the [default] profile. To use one of the additional profiles, change the value of the AWS_PROFILE environment variable. In the previous example, to use the credentials from the work account, set AWS_PROFILE=work-account.
