### ISSUE TITLE
Module version mismatch with yarn

### ISSUE THREAD

**Issue by nono** [electron-userland/electron-builder#1322]
* **Version**: 14.5.3
* **Node**: v7.6.0
* **Yarn**: v0.21.3
* **Electron**: 1.4.13
* **Target**: Linux x64

Hello,

when using electron-builder with yarn, I got this error:

> Module version mismatch. Expected 50, got 51. This generally implies that leveldown was built with a different version of node than that which is running now. You may try fully removing and reinstalling PouchDB or leveldown to resolve.

But it works with npm.

**Comment by develar** [comment]
Do you use install-app-deps?

**Comment by develar** [comment]
> To ensure your native dependencies are always matched electron version, simply add "postinstall": "install-app-deps" to your package.json.

**Comment by nono** [comment]
Yes, I used `install-app-deps`

**Comment by develar** [comment]
Is it possible to provide project? I will check when return from vacation.

**Comment by nono** [comment]
Yes, it is cozy-desktop: https://github.com/cozy-labs/cozy-desktop. The main directory is the lib, and the electron is in `gui/`.

Have nice vacation!
