### ISSUE TITLE
[electron-publisher-s3] When releasing for macOS & Windows at once, all files get uploaded to path in mac publish config

### ISSUE THREAD

**Issue by muellermarkus** [electron-userland/electron-builder#1323]
* **Version**: 14.5.3

* **Target**: macOS & Windows

**Observed behavior:** `npm run release -- -mw` (release script configured as recommended in https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts) builds files for macOS & Windows and uploads all built files to the S3 path specified in `mac -> publish -> path`  (`package.json`)

**Expected behavior:** Upload of Windows specific files as specified in `win -> publish -> path`.

**Workaround:** `npm run release -- -m && npm run release -- -w`

**Comment by develar** [comment]
I will check on this weekend.

**Comment by danielwestendorf** [comment]
I can confirm this bug exists.

**Comment by develar** [comment]
Fixed in the upcoming 19.5.4
