### ISSUE TITLE
Where Do I Specify the Publish URL for the Generic Publish Option?

### ISSUE THREAD

**Issue by Pharylon** [electron-userland/electron-builder#1325]
* **Version**: 13.6.0
* **Target**: Windows

I'm trying to set up an Electron project to auto-update. I'm trying to follow the instructions on [this page](https://github.com/electron-userland/electron-builder/wiki/Auto-Update). 

Step 2 is [Configure Publish](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#PublishConfiguration) and this is completely confusing me. I want to set up the auto-update to download from our own website, so I'm trying to set up publishing using the "generic" option. So I set it up the "build" property on the package.json as this:

    "build": {
        "appId": "foo.desktop.app",
        "productName": "My Desktop App",
        "asar": true,
        "win": {
          "iconUrl": "https://example.com/path/to.ico",
          "publish": ["generic"]
        }
      },

Now when I run `build`, electron-builder says: 

    Error: Please specify "url" for "generic" update server

Where do I specify the URL? I can't figure it out, and the documentation isn't helping at all.

**Comment by develar** [comment]
Answered on SO (but yes, GitHub is a preferd way). I will fix docs.

**Comment by Pharylon** [comment]
Thanks for the quick reply and the help. Much appreciated!

**Comment by Pharylon** [comment]
For anyone else that happens upon this, by the way, the correct way is:

```
"win": {
      "iconUrl": "https://ctishipping.carotrans.com/americas/wp-content/themes/fringetech/images/CaroTransGlobe.ico",
      "publish": {
        "provider": "generic",
        "url": "https://ctishipping.carotrans.com/electron"
      }
    }
```

**Comment by almamlaka** [comment]
how if the generic is gitlab what is the url we need to use ?
