### ISSUE TITLE
Auto-updater and Windows

### ISSUE THREAD

**Issue by raphaelarias** [electron-userland/electron-builder#1327]
Which version of electron-builder are you using?
Version:  14.5.1

Which version of electron-updater are you using (if applicable)?
Version: 1.8.1

What target are you building for?
Target: MacOS, Windows.

I'm sorry if I couldn't find on my own. I'm using the new severless auto-updater with S3. It works perfectly - thank you very much - with MacOS, but what about Windows?

If it's working on MacOs should be working on Windows too, right? Or I maybe missing something?

**Comment by develar** [comment]
In, General, yes. Please enable debug logging https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by dventurino** [comment]
@raphaelarias I'm having the opposite problem (see https://github.com/electron-userland/electron-builder/issues/1315 and https://github.com/electron-userland/electron-builder/issues/1310)

Could you please share your package.json _build_ section (rename your buckets if you don't want to expose them) and the javascript handling the update events?

**Comment by akashnimare** [comment]
@dventurino @raphaelarias I have successfully implemented auto-updates both on Windows and macOs. I'm using NSIS target on windows and the autoupdates works quite well. Please check out - 
https://github.com/zulip/zulip-electron/blob/master/package.json#L71
https://github.com/zulip/zulip-electron/blob/master/app/main/autoupdater.js

**Comment by akashnimare** [comment]
@develar is it possible to get two different installers for windows (32bit + 64 bit) with auto updates? As of now, I'm using nsis-web installer but the downloading of 7z file gets blocked sometimes.

**Comment by develar** [comment]
@akashnimare please file issue.
