### ISSUE TITLE
Auto-updater is connecting to Github over port 80

### ISSUE THREAD

**Issue by mobitar** [electron-userland/electron-builder#1330]
electron-builder 11.2.3

electron-updater 1.3.1

I'm publishing artifacts to Github using auto settings. You can see my package.json here:
https://github.com/standardnotes/desktop/blob/master/package.json
https://github.com/standardnotes/desktop/blob/master/app/package.json

When the app starts, I'm intercepting the network requests and see that the app connects to http://github.com/standardnotes/desktop/releases/latest

notice the "http" and not "https". I do not specify protocol anywhere, and the docs say that https should be default. Am I missing some sort of configuration?

**Comment by develar** [comment]
> electron-updater 1.3.1

Please update to 1.8.1

> electron-builder 11.2.3

Please update to 15.0.0

**Comment by mobitar** [comment]
That fixes the issue, thanks.
