### ISSUE TITLE
AppImage should bundle libXss.so.1

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#1333]
Getting on SUSE Linux Enterprise Desktop (SLES) 12 SP 1:

```
/tmp/.mount_cwSVcv/usr/bin/yout: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

**Comment by develar** [comment]
Do you use latest electron-builder? Now this lib is bundled (for x64) — https://github.com/electron-userland/electron-builder-binaries/tree/master/AppImage/x86_64-linux-gnu

**Comment by probonopd** [comment]
Thanks. Now I remember :-)

**Comment by cstayyab** [comment]
This library is no longer being added to AppImage. I get this error:
`/tmp/.mount_WALC-0GN40HJ/walc: error while loading shared libraries: /tmp/.mount_WALC-0GN40HJ/usr/lib/libXss.so.1: file too short`
I have manually copy file to `linux-unpacked` folder and then use command `electron-builder --prepackaged dist/linux-unpacked` to make it all work. 
Same is the case with `libXtst.so.6`

**Comment by cstayyab** [comment]
> This library is no longer being added to AppImage. I get this error:
> `/tmp/.mount_WALC-0GN40HJ/walc: error while loading shared libraries: /tmp/.mount_WALC-0GN40HJ/usr/lib/libXss.so.1: file too short`
> I have manually copy file to `linux-unpacked` folder and then use command `electron-builder --prepackaged dist/linux-unpacked` to make it all work.
> Same is the case with `libXtst.so.6`

It is because https://github.com/electron-userland/electron-builder-binaries/tree/master/AppImage/x86_64-linux-gnu does not exist.
