### ISSUE TITLE
Add option to disable automatic detection of publish settings

### ISSUE THREAD

**Issue by drew-gross** [electron-userland/electron-builder#1334]
I recently spent a bunch of time debugging an issue where my environment had `AWS_SECRET_ACCESS_KEY` set for reasons unrelated to the electron project I was working on. This resulted in a very unhelpful error: `Error: Please specify "bucket" for "s3" update server` which seemed crazy to me because nothing anywhere in my project used s3 or aws. I eventually discovered https://github.com/electron-userland/electron-builder/issues/1270 which led me to check my env, where I found the `AWS_SECRET_ACCESS_KEY`.

I suggest that you add an option to disable all implicit detection of build or publish settings, I would much rather specify everything explicitly, as I find this type of magic auto-detection fails in very hard to debug ways. Otherwise, I suggest adding info about what settings have been auto-detected and how, for example: `Attempting to publish to s3 because AWS_SECRET_ACCESS_KEY is set. Error: Could not find "bucket" setting.`

**Comment by develar** [comment]
Set `publish` to `null` to disable auto detection.

**Comment by develar** [comment]
Hmm... No, you don't need to set it to `null`. Env must be not detected if no explicit config for s3.

**Comment by develar** [comment]
Fixed in 15.1.1
