### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by drew-gross** [electron-userland/electron-builder#1336]
Which version of electron-builder are you using?
14.5.3

Which version of electron-updater are you using (if applicable)?
None

What target are you building for?
Mac

I'm trying to update the deploy process of https://github.com/vshatskyi/black-screen. Previously, it would deploy a new release on every commit to `master`. We had some issues at some point and that broke, and now I'm trying to fix it. The deploy script just runs `npm run release`, which just contains `build publish --always`. But this only publishes a draft release, not a public release, which is not what I want. How can I publish a public release?

**Comment by develar** [comment]
CLI: `--draft=false`
