### ISSUE TITLE
How to set build_number/FileVersion manually

### ISSUE THREAD

**Issue by akaegi** [electron-userland/electron-builder#1337]
The docs say 
> CFBundleVersion (MacOS) and FileVersion (Windows) will be set automatically to version.build_number on CI server (Travis, AppVeyor and CircleCI supported).
How can I set this manually? (We are using [Bamboo](https://www.atlassian.com/software/bamboo) build server.)

**Comment by develar** [comment]
15.1.0 — Bamboo supported. In any case `buildVersion` documented.
