### ISSUE TITLE
How does install-app-deps work/determine dependencies?

### ISSUE THREAD

**Issue by dragantl** [electron-userland/electron-builder#1345]
* **Version**: 5.35.0

* **Target**: Electron@0.36.7

I am using `electron-prebuilt@0.36.7` because later versions have issues with libffmpeg.so shared library and WebChimera.

How does `install-app-deps` determine what needs to be rebuilt? Does it examine `app/node_modules/.bin` directory and rebuilds the corresponding modules? The reason I'm asking is that I have a requirement to provide some environment variables prior to installation of `wcjs-prebuilt` (as well as rebuilding it when electron version changes).

How should I order `install-app-deps` and my custom task? My custom task, as mentioned above, will setup some variables for `wcjs-prebuilt` per https://github.com/Ivshti/wcjs-prebuilt#configuration. Am I correct to assume that `install-app-deps` simply deletes and rebuilds modules that are found under `app/node_modules/.bin`?

In case there is no way to order `install-app-deps` and my custom script, does `install-app-deps` allow for specification of script to execute after it runs?

**Comment by dragantl** [comment]
Also, is there a way for `electron-builder` to expose `getElectronVersion` function that doesn't take arguments (examines package manually)? This functionality would have to be duplicated by my script (it already is but simpler as it checks specific entry and not various possible package names).

**Comment by develar** [comment]
>  is there a way for electron-builder to expose getElectronVersion function that doesn't take arguments (examines package manually)

https://github.com/electron-userland/electron-builder/wiki/API#electron-builderoututilreadpackagejsongetelectronversionconfig-projectdir-projectmetadata--promise

**Comment by develar** [comment]
`install-app-deps` rebuild all production deps with `binding.gyp` file.

**Comment by develar** [comment]
> does install-app-deps allow for specification of script to execute after it runs?

During build we automatically rebuild native deps. You can use https://github.com/electron-userland/electron-builder/wiki/Options#Config-beforeBuild

**Comment by dragantl** [comment]
Thanks for the info!
