### ISSUE TITLE
--ia32 parameter not working as expected anymore

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1348]
* **Version**: 15.2.0

* **Target**: Windows / NSIS

Commit f2056fa messed up the logic for building an ia32 only build.

running `build --ia32` now results in building ia32 and x64 in one NSIS installer, instead of just ia32 as it used to be pre 15.2.0.

**Comment by develar** [comment]
Cannot reproduce. Could you please attach debug log? 
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by HitomiTenshi** [comment]
Strange, on my pc at home it doesn't happen. I'll attach the log next week on monday then.

**Comment by HitomiTenshi** [comment]
Here's the log.
[log.txt](https://github.com/electron-userland/electron-builder/files/834949/log.txt)

**Comment by develar** [comment]
Could you please provide your config file?

**Comment by HitomiTenshi** [comment]
Here is my config file:
[electron-builder.txt](https://github.com/electron-userland/electron-builder/files/835203/electron-builder.txt)

**Comment by develar** [comment]
Please try 15.4.1.

**Comment by HitomiTenshi** [comment]
Nope, it's still doing ia32 and x64 in one nsis installer. I copied the cmd output this time directly. Doing `> log.txt` apparently didn't write everything into the file.

15.4.1 log:
[log-15.4.1.txt](https://github.com/electron-userland/electron-builder/files/837658/log-15.4.1.txt)

last working version 15.1.1 log:
[log-15.1.1.txt](https://github.com/electron-userland/electron-builder/files/837659/log-15.1.1.txt)

**Comment by develar** [comment]
@HitomiTenshi Could you please provide your config file?

**Comment by HitomiTenshi** [comment]
Haven't I already? It's right above "Please try 15.4.1". I'm using a yml config.

Well anyways, here it is again:
[electron-builder.txt](https://github.com/electron-userland/electron-builder/files/835203/electron-builder.txt)

**Comment by HitomiTenshi** [comment]
Thanks! `15.4.3` fixed it 👍
