### ISSUE TITLE
problem with certificateFile

### ISSUE THREAD

**Issue by George35mk** [electron-userland/electron-builder#1351]
* **Version**: 

* **Target**: 

what is the easy way to make a simple build i try for 2 days in the row but all time fails i just find this tutorial
[https://blog.avocode.com/blog/get-that-damn-windows-auto-update-working-on-electron](url) on the web but i nead a .pfx file how i can generate one

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder/wiki/Auto-Update about auto update.

**Comment by develar** [comment]
https://technet.microsoft.com/en-us/library/dd261744.aspx

**Comment by develar** [comment]
https://www.ssl.com/how-to/create-a-pfx-p12-certificate-file-using-openssl/

**Comment by George35mk** [comment]
first of all thnx alll for your help

**Comment by George35mk** [comment]
when i type this comand on CMD 

openssl pkcs12 -export -out certificate.pfx -inkey privateKey.key -in certificate.crt -certfile more.crt

is say 

'openssl' is not recognized as an internal or external command,
operable program or batch file.

**Comment by George35mk** [comment]
How to install the open ssl

**Comment by George35mk** [comment]
from that link install this [https://slproweb.com/products/Win32OpenSSL.html](https://slproweb.com/products/Win32OpenSSL.html) 

and i install this bro 
![default](https://cloud.githubusercontent.com/assets/20750445/23824265/d8195b8e-067b-11e7-9f5e-4df787e51aa7.PNG)

**Comment by George35mk** [comment]
but is not work i try this video from youtube but this guy is generate a .pen key https://www.youtube.com/watch?v=H8GxM9ApkYc

**Comment by George35mk** [comment]
ok i solved after 7 houers and 4 coffes and 127 chigaretes 👍

**Comment by George35mk** [comment]
thnx brother for  your help without hour help i never gona make it
