### ISSUE TITLE
Include files that are excluded by default

### ISSUE THREAD

**Issue by akorchev** [electron-userland/electron-builder#1352]
* **Version**: 15.2.0

* **Target**: nsis

Is there any way to override the default `files` option? I want to include `*.d.ts` from node_modules in the final output which are now excuded thanks to `"!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples,*.d.ts}",`

**Comment by develar** [comment]
Just set own `files` ;)

**Comment by develar** [comment]
For do you need to include d.ts?

**Comment by akorchev** [comment]
This is the first thing I tried. Still the *.d.ts files are ignored. After checking the code it seems that pattern is always appended after the user specified filed.

**Comment by develar** [comment]
I guess you need these files not as part of asar archive. So, just use extraFiles or extraResources.

**Comment by akorchev** [comment]
Thanks! I will try that.

**Comment by develar** [comment]
Please clarify for what do you need to bundle it. We build not a tool, but a solution.

**Comment by akorchev** [comment]
The electron app I am building creates web apps. It uses typescript to build those apps. This is why I need .d.ts files. This problem appeared after I upgraded to latest electron-builder.

**Comment by develar** [comment]
So, you definitely need to use extraResources/extraFiles because only in this case files will be available as regular files.

**Comment by akorchev** [comment]
Thanks! I originally used `asarUnpack` but it seems `extraResources` will do the job just fine.
