### ISSUE TITLE
AppImage file is not directly executable when downloaded from GitHub Releases

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#1353]
* **Version**: 15.3.0

* **Target**: AppImage

I'm building an AppImage target on Travis to have it automatically uploaded to GitHub Releases. When the AppImage file is downloaded from the GitHub release, however, it seems to have lost its executable bits and I had to do `chmod +x filename.AppImage` to make it work. Maybe it should be wrapped in a `.tar` file so the executable bits are preserved?

You can test it out here: https://github.com/sindresorhus/caprine/releases/tag/v2.0.0-beta.1

**Comment by develar** [comment]
Hi. It was initially implemented so, but author of Appmage asked us to not wrap. Please see and discuss https://github.com/electron-userland/electron-builder/issues/893 Given the fact who you are, option to wrap into archive can be added only by your vote.

**Comment by probonopd** [comment]
Please also see https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#common-mistake

If you want to make AppImages executable automatically, you might be interested in the optional appimaged daemon.
