### ISSUE TITLE
Don't build when CI run is a pull request

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#1354]
* **Version**: 15.3.0

It would be nice if `electron-builder` didn't try to build when the CI run is a pull request. The required codesign environment variables are not available on untrusted builds on Travis:

> Encrypted variables are not available to untrusted builds such as pull requests coming from another repository.
> - https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

I know I could turn off building on pull requests in the Travis repo settings, but I still want to do linting on pull requests.

Here's how it's currently failing: https://travis-ci.org/sindresorhus/caprine/jobs/210320431

**Comment by develar** [comment]
Fixed in 15.4.0

Code signing fixed if build is a part of a PR. In the same way as deployment.

**Comment by develar** [comment]
Reopened — MAS build should be skipped.

**Comment by djalmaaraujo** [comment]
@develar I don't know why this was added, looks incorrect to me, what is I want to have artifacts signed in my pull-requests for QA?

**Comment by sindresorhus** [comment]
@djalmaaraujo The issue description clearly describes why it was added. If you have other needs, open a separate issue and @develar might add an opt-in, but it's not a good default.

**Comment by djalmaaraujo** [comment]
@sindresorhus I understand the problem, but in circleci/Appveyor for example you don't have this issue. It would be ideal at least, to have a config option for that.

**Comment by djalmaaraujo** [comment]
Maybe I can do a "hack", setting all these 3 vars:

```TRAVIS_PULL_REQUEST``` ```CI_PULL_REQUEST``` ```CI_PULL_REQUESTS``` to false on the CI. But that's not good. Also, there's a TRAVIS custom variable inside of electron-builder, which doesn't make sense to me.

Just saying... :)

**Comment by develar** [comment]
It is not issue, it is security feature. On CircleCI you also can disable secret passing. As suggested above, please file issue to add option.
