### ISSUE TITLE
build.publish section in package.json is ignored

### ISSUE THREAD

**Issue by FelikZ** [electron-userland/electron-builder#1356]
* **Version**: 15.2.0

* **Version**: 1.8.2

* **Target**: nsis (win x64)

`build.publish` section from my package.json is ignored, it always use `repository` if exists or fallback to `./.git/config`.

What can be wrong and how to debug?

```javascript
// ...
  "private": true,
  "repository": {
    "type": "git",
    "url": "git+https://github.com/FelikZ/<repo>.git"
  },
// ...
  "build": {
    // ...
    "npmRebuild": true,
    "compression": "store",
    "asar": true,
    "win": {
      "target": "nsis",
      "publish": ["github"]
    },
    "nsis": {
      "oneClick": true
    },
    "publish": [{
        "provider": "github",
        "owner": "felikz",
        "repo": "<repo>",
        "token": "<token>"
    }],
```

I used [this](https://github.com/iffy/electron-updater-example) as an example repo.

**Comment by develar** [comment]
Config looks correct. I will check.

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by FelikZ** [comment]
@develar so I am trying to publish to vicaption/vicaption , while it ignore configuration and using FelikZ/vicaption repo.

package.json

```json
{
  "version": "0.2.1",
  "name": "Vicaption",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git+https://github.com/FelikZ/vicaption.git"
  },
  "scripts": {
    "start": "./node_modules/.bin/electron ./app",
    "postinstall": "install-app-deps",
    "pack": "build --dir -p never",
    "dist": "build --win --x64 -p never",
    "release": "build --win --x64 -p always --draft=false"
  },
  "build": {
    "appId": "com.vicaption.app",
    "copyright": "Copyright © 2017 Vicaption",
    "npmRebuild": true,
    "compression": "store",
    "asar": true,
    "asarUnpack": "faceswap",
    "win": {
      "target": "nsis",
      "publish": ["github"]
    },
    "nsis": {
      "oneClick": true
    },
    "publish": [{
        "provider": "github",
        "owner": "vicaption",
        "repo": "vicaption",
        "token": "<token>"
    }],
    "directories": {
      "buildResources": "build",
      "output": "dist",
      "app": "app"
    }
  },
  "devDependencies": {
    "electron": "1.4.3",
    "electron-builder": "15.2.0",
    "eslint": "3.17.0"
  }
}
```

[build.txt](https://github.com/electron-userland/electron-builder/files/839211/build.txt) log with `DEBUG=electron-builder`.

Thanks!

**Comment by develar** [comment]
In the upcoming 15.6.1 I added additional debug logging. Please try it and attach debug log again.

**Comment by FelikZ** [comment]
@develar 

```
Fri, 17 Mar 2017 17:40:10 GMT electron-builder no owner or project for github, call getInfo: owner: undefined, proj
ect: undefined
```

[build2.txt](https://github.com/electron-userland/electron-builder/files/851360/build2.txt)

**Comment by develar** [comment]
@FelikZ Thanks. Interesting... I will another debug log soon :)

**Comment by develar** [comment]
I see this message after:

```
Explicit publish provider: [
  "github"
]
```

Are you sure that correct config is used? Is it possible to see your project sources?

**Comment by develar** [comment]
I see "Two package.json structure is used" so, is config defined in the dev, and not app package.json?

**Comment by FelikZ** [comment]
@develar right, whole `build` section is defined on top level, non-app package.json. But it works since it understand `win` `target` `nsis` for example. Should `build.publish` section be defined under app/package.json instead?

**Comment by develar** [comment]
@FelikZ No, it should be in the dev package.json file. Ok, in 20 minutes I will publish new version and it will be clear.

**Comment by FelikZ** [comment]
@develar waiting with a hope and fingers crossed :)

**Comment by develar** [comment]
Please try 15.6.3 and attach debug log.

**Comment by FelikZ** [comment]
@develar hmm, some syntax error now.

[build3.txt](https://github.com/electron-userland/electron-builder/files/852411/build3.txt)

**Comment by develar** [comment]
Syntax error is fixed in the 15.6.4 but your config shows that GitHub is properly configured. Anyway, please try 15.6.4

**Comment by develar** [comment]
@FelikZ ouch, bingo — see win.publish in log effective config — from where?

**Comment by FelikZ** [comment]
@develar I used to add `build.win.publish = ['gitlab']`, since without it was trying to use bintray.

Apparently because the same issue - unable to see `build.publish`.

See log from 15.6.4 attached.

[build4.txt](https://github.com/electron-userland/electron-builder/files/852483/build4.txt)

(thanks for you time, much appreciated!)

**Comment by develar** [comment]
So, remove publish from win to fix issue.

**Comment by FelikZ** [comment]
@develar thanks, after I removed `publish` from `win` its detects `build.publish` section.

But apparently I am not able to publish to organization. I am using owner as `vicaption` and `project` as vicaption, but true is that the owner is `felikz`, he just owns `vicaption` organization.

So its not uploading to [vicaption/vicaption](https://github.com/vicaption/vicaption/releases) breaks on tag creation, while it works on [felikz/vicaption](https://github.com/felikz/vicaption/releases) like a charm.

Should it just work or this feature (uploading to organization) shouldn't work?

Thanks again!

**Comment by FelikZ** [comment]
@develar upload release file (exe) is broken for me in 15.2.0, 15.5.0 and 15.6.4. Rolled back to 7.12.1 - works fine. Will try increment versions one by one later. 

Want me to follow this in new issue, or its fine to keep it here?

**Comment by develar** [comment]
> but true is that the owner is felikz, he just owns vicaption organization.

GitHub resolves user from access token. So,  uploading to organization should work (and it is tested).

Please NEVER specify token in the config — please use only env `GH_TOKEN`.

**Comment by develar** [comment]
> Want me to follow this in new issue, or its fine to keep it here?

Please file separate issue. BTW, it works for me and all tests are green.

**Comment by FelikZ** [comment]
#1385
