### ISSUE TITLE
Question: Converting from nsis to nsis-web

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1358]
**Version:** 15.4.2

Hey. I believe I asked this already but I want to be 100% positive/understand everything (don't need anymore random uninstall nukings of people's C drives lol).

We have an application currently in beta and we have been using the nsis packager. We will be switching to the nsis-web packager soon as we want to have both 64 and 32 bit supported. Right now we have just been distributing 64 bit. We plan on adding 32 bit this week.

When we create the new installer we will have a 32 bit 7z and a 64 bit 7z. Will the existing clients understand how to parse the latest.yml? 

Normally when building a client (with nsis) I get:

```
win-unpacked/
Badlion Client Setup 0.9.6.exe
latest.yml
```

Now I am getting

```
nsis-web/latest.yml
win-ia32-unpacked/
win-unpacked/
Badlion Client Web Setup 0.9.6.exe
badlion-client-0.9.6-ia32.nsis.7z
badlion-client-0.9.6-x64.nsis.7z
```

(Side note [possible bug?]) the `name` from `package.json` is used for the `.7z` files instead of the `productName`. Not sure if this is going to cause issues or not. On this note the githubArtifactName is also using the `name` and not `productName` inside of latest.yml (not using this, just reporting it). Poking around inside of the web installer with a hex editor i don't think either of these is an issue, but regardless reporting/asking to be safe.

```
version: 0.9.6
releaseDate: '2017-03-13T12:12:42.179Z'
githubArtifactName: badlion-client-WebSetup-0.9.6.exe
path: Badlion Client Web Setup 0.9.6.exe
sha2: eb874dc58af6984e443caaeb379cb232b4733e64e58642b43b7a8b6531c88b50
```

So my main questions after all of this information are:

1. Will it properly update from `nsis` to `nsis-web` with only 64 bit originally being supported?
2. Will updates properly happen for both 64 bit and 32 bit? How is it checking for an update? Is it checking the `sha2/version` of the `latest.yml` above for both versions and looking to see if there is a new one?
3. When uploading the files to the s3 bucket I have setup do i need to move the `nsis-web/latest.yml` up one directory to just be `latest.yml` again? Otherwise the old installers will be looking for the wrong path?

Thanks.

**Comment by develar** [comment]
> 1. Will it properly update from nsis to nsis-web with only 64 bit originally being supported?

Updater is not aware of downloaded file. It can be Squirrel.Windows, NSIS, MSI, InnoSetup or anything else. Only regular exe file is required.

Installer is not aware about previously installed exe. It can be even old electron-builder 1.xx NSIS.

So, it will be properly updated.

> 2. Will updates properly happen for both 64 bit and 32 bit? How is it checking for an update?

Nothing changed here. Updater requests new installer. Nothing more. It is installer responsibility to download proper package (7z file).

> 3. When uploading the files to the s3 bucket I have setup do i need to move

Use electron-builder s3 publisher and do not think about it. Yes, `nsis-web/latest.yml` must be uploaded as `latest.yml`, without `nsis-web`.

> We will be switching to the nsis-web packager soon as we want to have both 64 and 32 bit supported. Right now we have just been distributing 64 bit. We plan on adding 32 bit this week.

If 30-40 MB is not overhead for you, I suggest to not use web installer. It is more reliable to distribute one installer (both archs are packed into one installer). But, the only risk here — custom user proxy settings (IE settings will be reused, downloaded using win api, not node api).

> (Side note [possible bug?]) the name from package.json is used for the .7z files instead of the productName. Not sure if this is going to cause issues or not. On this note the githubArtifactName is also using the name and not productName inside of latest.yml (not using this, just reporting it).

Due to weird GitHub requirements we have to use only safe name for package. It is ok that `name`, but not `productName` is used for 7z file.s

**Comment by mastergberry** [comment]
Ok I think the above answers most of my questions. So basically the actual application will just check latest.yml and then uninstall and install new one automatically (even if new one is just the web installer).

We are not currently using the s3 publisher since it was not originally available when we were testing things out. We just are using the generic server since we actually are using cloudfront and not s3 to distribute the files anyways. Not sure if that is supported or not.

Think we would try and prefer to not have the overhead if we can avoid it as it does add up over time into $$$. We actually are trying to fix/shrink our system down more. Also the IE proxy thing is something I definitely would like to avoid...just adds another layer of possible problems.

**Comment by mastergberry** [comment]
So wait I am confused on the `nsis-web` part. Is it `nsis-web` using the proxy stuff or the `nsis` installer if you put both 32 and 64 bit together?

**Comment by develar** [comment]
`nsis-web` downloads corresponding package from the internet. `nsis` installer contains all packages inside (offline installer).

**Comment by mastergberry** [comment]
Ah right....total derp. Does the `nsis-web` installer use the same proxy settings if you actually download a file via `nsis` such as:

`nsisdl::download /TIMEOUT=30000 ${MS_VCPP_32_URL} $2`

(Example from my scripts)

**Comment by develar** [comment]
@mastergberry We use more powerful [Inetc ](http://nsis.sourceforge.net/Inetc_plug-in) plugin.

**Comment by mastergberry** [comment]
I see. We will most likely go with the web installer because the packaging size is going to get gigantic for us since we have a lot of extra .dll's and .jar files we need to include depending on 32 or 64 bit architecture.

Thanks for all of the information.

One last question and then I am out of them. Where are the registry keys stored that the installer makes?

**Comment by develar** [comment]
> Where are the registry keys stored that the installer makes?

https://github.com/electron-userland/electron-builder/wiki/NSIS#guid-vs-application-name

```
!define INSTALL_REGISTRY_KEY "Software\${APP_GUID}"
!define UNINSTALL_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_GUID}"
!define UNINSTALL_DISPLAY_NAME "${PRODUCT_NAME} ${VERSION}"
```

**Comment by mastergberry** [comment]
One small followup question. The `INSTALL_REGISTRY_KEY` pretty much has nothing in it besides the actual `Install_Path`

What determines if a new version is available in `electron-updater`? version #?

**Comment by develar** [comment]
> What determines if a new version is available in electron-updater? version #?

Version in the `latest.yml` will be compared to current app version.

**Comment by mastergberry** [comment]
Where is that current app version? Inside of the actual exe hardcoded somewhere?

**Comment by develar** [comment]
> Where is that current app version? Inside of the actual exe hardcoded somewhere?

https://github.com/electron/electron/blob/master/docs/api/app.md#appgetversion
