### ISSUE TITLE
Error during 32bits Linux build with optional dependency

### ISSUE THREAD

**Issue by vincelwt** [electron-userland/electron-builder#1359]
Electron-builder **v15.4.2** on Linux

* **Target**: Linux (deb, AppImage, tar.xz)

Hi! 
I just tried updating after a long time electron-builder (coming from 7.9.0 where everything was working ok) but I'm stuck with this error when building for Linux. Mac build doesn't produce errors. I do have some native dependencies, but I set them as optionalDependencies so it should ignore them in case of errors.

I'm guessing the mediakeys dependency is causing the problem, as it is using dbus.
```

$ npm -v
3.10.10
$ node -v
v7.6.0
```

The package.json:
```
{
  "name": "harmony",
  "productName": "Harmony",
  "version": "0.5.0",
  "description": "Listen to music from everywhere",
  "main": "main.js",
  "author": "Vincent L <vince@getharmony.xyz>",
  "license": "GPL-3.0",
  "homepage": "http://getharmony.xyz",
  "scripts": {
    "start": "electron main.js",
    "buildOSX": "build --mac zip",
    "buildLinux": "build --linux AppImage deb tar.xz --x64 --ia32",
    "buildWin": "build --win nsis portable --x64 --ia32",
    "rebuild": "npm rebuild --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --abi=50",
    "postinstall": "install-app-deps"
  },

  "keywords": [
    "music",
    "player",
    "soundcloud",
    "google play",
    "spotify"
  ],
  "devDependencies": {
    "electron": "1.6.1"
  },
  "dependencies": {
    "configstore": "^1.4.0",
    "electron-analytics": "^0.1.2",
    "electron-window-state": "^4.0.1",
    "glob": "^7.0.6",
    "graceful-fs": "^4.1.6",
    "md5": "^2.0.0",
    "musicmetadata": "^2.0.2",
    "playmusic": "^2.2.0",
    "recursive-readdir": "^1.3.0",
    "request": "^2.69.0",
    "youtube-node": "^1.3.0",
    "ytdl-core": "^0.8.1"
  },
  "optionalDependencies": {
    "mpris-service": "^1.1.1",
    "mediakeys": "github:nogizhopaboroda/mediakeys",
    "ll-keyboard-hook-win": "^3.0.0"
  },
  "build": {
    "asar": true,
    "appId": "com.vincelwt.harmony",
    "compression": "store",
    "iconUrl": "https://raw.githubusercontent.com/vincelwt/harmony/master/build/icon.ico",
    "mac": {
      "category": "public.app-category.music"
    },
    "linux": {
      "category": "Music;Audio;AudioVideo",
      "packageCategory": "sound"
    }
  }
}

```

And the log of the issue:

```

> harmony@0.5.0 buildLinux /home/vince/harmony-build/harmony
> build --linux AppImage deb tar.xz --x64 --ia32

Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.6.1 to dist/linux-unpacked
Building AppImage for arch x64
Building tar.xz
Rebuilding native production dependencies for linux:ia32
Building deb
Error: /usr/local/bin/node exited with code 1
Output:

> dbus@0.2.23 install /home/vince/harmony-build/harmony/node_modules/dbus
> node-gyp configure build

make: Entering directory '/home/vince/harmony-build/harmony/node_modules/dbus/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/dbus/src/dbus.o
  CXX(target) Release/obj.target/dbus/src/connection.o
  CXX(target) Release/obj.target/dbus/src/signal.o
  CXX(target) Release/obj.target/dbus/src/encoder.o
  CXX(target) Release/obj.target/dbus/src/decoder.o
  CXX(target) Release/obj.target/dbus/src/introspect.o
  CXX(target) Release/obj.target/dbus/src/object_handler.o
  SOLINK_MODULE(target) Release/obj.target/dbus.node
dbus.target.mk:142: recipe for target 'Release/obj.target/dbus.node' failed
make: Leaving directory '/home/vince/harmony-build/harmony/node_modules/dbus/build'

Error output:
../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:709:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
/usr/bin/ld: cannot find -ldbus-1
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/dbus.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-std-1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/vince/harmony-build/harmony/node_modules/dbus
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dbus@0.2.23 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dbus@0.2.23 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dbus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vince/.npm/_logs/2017-03-13T17_01_57_982Z-debug.log

    at ChildProcess.childProcess.once.code (/usr/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:134:14)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/usr/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:97:3)
    at /usr/lib/node_modules/electron-builder/src/yarn.ts:118:11
From previous event:
    at rebuild (/usr/lib/node_modules/electron-builder/out/yarn.js:87:22)
    at /usr/lib/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at installOrRebuild (/usr/lib/node_modules/electron-builder/out/yarn.js:33:21)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:399:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/usr/lib/node_modules/electron-builder/out/packager.js:483:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:227:20
From previous event:
    at Packager.doBuild (/usr/lib/node_modules/electron-builder/out/packager.js:377:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:166:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/usr/lib/node_modules/electron-builder/out/packager.js:272:11)
    at /usr/lib/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/lib/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/usr/lib/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! harmony@0.5.0 buildLinux: `build --linux AppImage deb tar.xz --x64 --ia32`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the harmony@0.5.0 buildLinux script 'build --linux AppImage deb tar.xz --x64 --ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the harmony package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --linux AppImage deb tar.xz --x64 --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs harmony
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls harmony
npm ERR! There is likely additional logging output above.

```

**Comment by develar** [comment]
Possible workaround: use yarn (https://yarnpkg.com)

**Comment by vincelwt** [comment]
I'll try and report back, thanks.

**Comment by vincelwt** [comment]
Same error with yarn :/

$ yarn run v0.21.3

$ build --linux AppImage deb tar.xz --x64 --ia32 
Rebuilding native production dependencies for linux:x64
Rebuilding native dependency dbus
Packaging for linux x64 using electron 1.6.1 to dist/linux-unpacked
Building AppImage for arch x64
Building tar.xz
Rebuilding native production dependencies for linux:ia32
Rebuilding native dependency dbus
Building deb
Error: /usr/local/bin/node exited with code 1
Output:
yarn run v0.21.3
$ node-gyp configure build 
make: Entering directory '/home/vince/harmony-build/harmony/node_modules/dbus/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/dbus/src/dbus.o
  CXX(target) Release/obj.target/dbus/src/connection.o
  CXX(target) Release/obj.target/dbus/src/signal.o
  CXX(target) Release/obj.target/dbus/src/encoder.o
  CXX(target) Release/obj.target/dbus/src/decoder.o
  CXX(target) Release/obj.target/dbus/src/introspect.o
  CXX(target) Release/obj.target/dbus/src/object_handler.o
  SOLINK_MODULE(target) Release/obj.target/dbus.node
dbus.target.mk:142: recipe for target 'Release/obj.target/dbus.node' failed
make: Leaving directory '/home/vince/harmony-build/harmony/node_modules/dbus/build'
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.6.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vince/harmony-build/harmony/node_modules/dbus/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vince/.electron-gyp/.node-gyp/iojs-1.6.1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vince/.electron-gyp/.node-gyp/iojs-1.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/vince/harmony-build/harmony/node_modules/dbus',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:709:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
/usr/bin/ld: cannot find -ldbus-1
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/dbus.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-std-1
gyp ERR! command "/usr/local/bin/node" "/usr/share/yarn/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/vince/harmony-build/harmony/node_modules/dbus
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (/usr/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:134:14)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/usr/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:97:3)
    at /usr/lib/node_modules/electron-builder/src/yarn.ts:103:7
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at /usr/lib/node_modules/electron-builder/src/yarn.ts:101:27
From previous event:
    at rebuild (/usr/lib/node_modules/electron-builder/out/yarn.js:87:22)
    at /usr/lib/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at installOrRebuild (/usr/lib/node_modules/electron-builder/out/yarn.js:33:21)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:399:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/usr/lib/node_modules/electron-builder/out/packager.js:483:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:227:20
From previous event:
    at Packager.doBuild (/usr/lib/node_modules/electron-builder/out/packager.js:377:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:166:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/usr/lib/node_modules/electron-builder/out/packager.js:272:11)
    at /usr/lib/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/lib/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/usr/lib/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vincelwt** [comment]
It works well if I only build for x64 (no ia32).
Build is on a 64 bits machine.

**Comment by vincelwt** [comment]
For those encountering the same problem, the workaround I found is to set `npmRebuild` to false, and manually rebuild before with `npm rebuild --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --abi=50`

**Comment by develar** [comment]
@vincelwt Have you read https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#to-build-app-in-32-bit-from-a-machine-with-64-bit

> To build app in 32 bit from a machine with 64 bit
> sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib

**Comment by develar** [comment]
Sorry for late response but your advice is not correct — `npm rebuild --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --abi=50` When you build for ia32, arch must also specified. Please try to install required systems deps. `sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib`

**Comment by vincelwt** [comment]
@develar I already have these packages installed :/

**Comment by vincelwt** [comment]
Thanks, didn't knew about npm rebuild. I tried with `--arch=ia32` and it also fails. So it must must have something to do with the module, npm or my system. Closing this since unrelated with electron-builder.

**Comment by develar** [comment]
@vincelwt Please try in the terminal your command with arch

```
npm_config_arch=ia32 npm rebuild --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --abi=50
```

**Comment by develar** [comment]
I guess old version v7.6.0 doesn't pass this very critical arg, and error was not discovered. Yes, you have to install some linux package to build.

**Comment by vincelwt** [comment]
@develar Thanks for the help! 
Turns out the I only had to install `libdbus-1-dev:i386` to make it work!
Working fine now :) Sorry for bothering.
