### ISSUE TITLE
How to unpack a single file

### ISSUE THREAD

**Issue by Kunze** [electron-userland/electron-builder#1360]
1.4.1

windows

This is my structure:

MyApp
  |--node_modules
  |--config.json

I can create an asar running this command "C:\Users\murilo\Desktop>asar pack MyApp app.asar --unpack config.json" but I can't usigng electron-package.. I tried everything I see and nothing works:

electron-packager . --overwrite --asar=true --asar.unpack='config.json' --platform=win32 --prune=true --out=release-builds
electron-packager . --overwrite --asar=true --asar.unpack='MyApp/config.json' --platform=win32 --prune=true --out=release-builds
electron-packager . --overwrite --asar=true --asar.unpack='**/config.json' --platform=win32 --prune=true --out=release-builds
electron-packager . --overwrite --asar=true --asar.unpack={config.json} --platform=win32 --prune=true --out=release-builds
electron-packager . --overwrite --asar=true --asar.unpack='*.json' --platform=win32 --prune=true --out=release-builds
electron-packager . --overwrite --asar=true --asar.unpack='./config.json' --platform=win32 --prune=true --out=release-builds

and a lot else!!!!

How can I make it works???

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#Config-asarUnpack

**Comment by Kunze** [comment]
This documentation is insufficient to me since using "--unpack config.json" works!!

**Comment by develar** [comment]
> electron-packager 

This project — electron-builder. Have you tried https://github.com/electron-userland/electron-builder/wiki/Options#Config-asarUnpack
