### ISSUE TITLE
cross-platform build

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1362]
I am working on macOs and am thinking about building the Windows version directly from Mac.
I do use native modules so i need a way to get the correct binaries for Windows. 
You mention in the Wiki that it works with prebuild.
In my case the modules don't use prebuild but they use node-pre-gyp and i am almost sure i can make it work: node-pre-gyp tries to download pre built during npm install.

What i need to understand is how you tell "prebuild" to download "windows" version of the binaries while building Windows version from macOs? Is that a command line argument?
That way i can try and port it to node-pre-gyp

Thanks

**Comment by develar** [comment]
Set [npmSkipBuildFromSource](https://github.com/electron-userland/electron-builder/wiki/Options#Config-npmSkipBuildFromSource) to `false`.

If module provides correct binaries for electron, it will be used.

**Comment by farfromrefug** [comment]
@develar thanks missed this in the doc! works great
