### ISSUE TITLE
Multi Platform Build: platform variable replace in options

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#1363]
I am trying the Multi Platform Build from mac.
I am facing an issue which that some of my options depend on the platform it is building for.
For example the building platform name appears in my ```publisher``` ```url``` or some ```extraFiles```.
Is there a way to have variable replace within options? 
for example ```https://my.site.com/files/{{ platform }}/``` could have platform replaced by the platform it is being built for.

There might already be another way to achieve this. If not i could look at it and possibly make a PR.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#file-macros
