### ISSUE TITLE
Question/Improvement to nsis-web and estimated installation size

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1364]
* **Version**: 15.4.2

* **Target**: nsis-web

Not sure if this easily do-able/possible but maybe check which .7z file they will need in advance and what the total size of the installation will be on their computer? Right now it just shows around 432KB which is obviously very wrong compared to the actual installation which in my case is around 432MB lol.

I figure maybe this information could be slipped into the latest.yml and parsed to be used instead of the web installer's installation size?

**Comment by develar** [comment]
Do you mean EstimatedSize for UNINSTALL_REGISTRY_KEY? i.e. in the windows add/remove program?

**Comment by mastergberry** [comment]
No i mean the actual installation one. Like when the web installer runs it asks for an installation directory and gives and estimated size that will be used.
