### ISSUE TITLE
serialport.node is not packaged.

### ISSUE THREAD

**Issue by wangyueming** [electron-userland/electron-builder#1366]
* **Version**: 13.3.2

* **Target**: macOS Sierra

I use [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate)
After I make package with "npm run package" and run the program, it shows below:
<img width="418" alt="2017-03-13 10 27 34" src="https://cloud.githubusercontent.com/assets/10303419/23905868/565d2614-0907-11e7-8641-da6615c67a4c.png">

**Comment by develar** [comment]
Better to file issue to electron-react-boilerplate Maybe you need to unpack this node dep (but it should be unpacked automatically). See asarUnpack option.

> 13.3.2

Please update to latest version, 15.5.0

**Comment by wangyueming** [comment]
I succeeded by installing serialport in ${root}/app/node_modules rather than  ${root}/node_modules.
