### ISSUE TITLE
dmg icon get a wrong position if productName contains Unicode character

### ISSUE THREAD

**Issue by changkun** [electron-userland/electron-builder#1369]
* **Version**: 15.4.2
* **Target**: macOS

`package.json` build field:

```js
  "build": {
    "appId": "test.test",
    "productName": "Test",
    "directories": {"buildResources": "assets"},
    "mac": {
      "category": "public.app-category.entertainment",
      "target": [ "dmg" ],
      "icon": "assets/icon.icns"
    },
    "dmg": {
      "contents": [
        {
          "x": 415,
          "y": 170,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 135,
          "y": 170,
          "type": "file"
        }
      ]
    },
    "win": {"target": ["nsis"]},
    "linux": {"target": ["deb"]}
  },
```

**Wrong position if productName contains unicode characters**
![screen shot 2017-03-14 at 17 21 29](https://cloud.githubusercontent.com/assets/5498964/23910670/c9c666ce-08da-11e7-968b-3520407c1523.png)
**Correct position if productName only english character**
![screen shot 2017-03-14 at 17 11 21](https://cloud.githubusercontent.com/assets/5498964/23910249/4e7cd18e-08d9-11e7-8e87-c7d1b00b9605.png)

**Comment by changkun** [comment]
This is a bug since https://github.com/electron-userland/electron-builder/commit/89f7f6a.

**Comment by develar** [comment]
Probably we should force utf8 encoding for perl source file. Sorry for delay, I will investigate in 2 days.

**Comment by changkun** [comment]
@develar Somehow you removed UTF8 encoding from [line 48](https://github.com/electron-userland/electron-builder/blob/89f7f6ab1aaf482a2d6147f6cbd81be4f8356f37/packages/electron-builder/templates/dmg/dmgProperties.pl), I would guess this is the source of the bug:

```perl
&makeEntries(Encode::decode("UTF-8", $ENV{'appFileName'}), Iloc_xy => [ $ENV{'appFileX'}, $ENV{'appFileY'} ]),		 +    $ENTRIES
&makeEntries("Applications", Iloc_xy => [ $ENV{'APPLICATIONS_LINK_X'}, $ENV{'APPLICATIONS_LINK_Y'} ]),
```

**Comment by develar** [comment]
Duplicates #1234
