### ISSUE TITLE
 Possible asar issue - pages in sub-folders not displaying

### ISSUE THREAD

**Issue by biomade** [electron-userland/electron-builder#1371]
"electron-builder": "^15.4.3"

n/a

"electron": "^1.6.0"

I am building an electron application (of course)
I am trying to build portable windows package.

The main window loads fine but when I select a menu item (bcrypt/encrypt) that points to the sub-folder item (bcrypt/encrypt.html), the window is empty. When I run the application from npm start everything works as expected.
I have the unpacked the arar and the sub-folder and the folder for bcrypt and the included files are there.  See my package.json below as well as the application structure

YET, when I have asar = false, everything works ok (I don't have any external files that need to be unpacked)

My application structure is
bcryptdesktoptool
----app
--------main.html
--------assets
----------global.css
----------variables.css
--------bcrypt
----------encrypt.js
----------encrypt.html
----------validate.js
----------validate.html
----node_modules
----package.json
----app.js
Here is my development package.json
```
{ 
  "name": "bcryptdesktoptool", 
  "productName": "Bcrypt Desktop Tool", 
  "version": "0.0.1", 
  "description": "An Electron Desktop tool to encrypt passwords and validate them using bcrypt",
   "main": "app.js", 
   "scripts": { 
     "start": "electron app.js",
     "test": "standard", "
      package-win": "build" 
    }, 
   "keywords": [ "Electron", "bcrypt", "node" ], 
   "author": "laurie k", 
   "license": "ISC", 
  "devDependencies": { 
     "devtron": "^1.4.0", 
     "electron": "^1.6.3", 
     "electron-builder": "^15.4.3", 
     "standard": "^9.0.1" }, 
   "dependencies": { 
       "bcryptjs": "^2.4.3" 
     }, 
   "build": { 
       "appId": "com.kernology.bcryptdesktoptool", 
       "productName": "Bcrypt Desktop Tool",
       "artifactName": "BcryptTool.exe", 
       "files": "**/*", 
       "asar": true, 
       "asarUnpack":"**/*", 
       "win": { 
          "target": "portable" 
        }
     }
 }
```

**Comment by develar** [comment]
For what do you use explicit `asarUnpack`? And `files`?

**Comment by biomade** [comment]
I was using the files to make sure the pages and my css's were being included, I thought there was a chance that they were not and I used thw asarUpack to see what was in the asar (unpacked). I removed them after I found everything was ok, I just forgot to remove them when I posted the package.json

**Comment by develar** [comment]
Is it possible to provide project, so, I can just run and check?

**Comment by biomade** [comment]
Here is a link to the GitHub repo [https://github.com/biomade/BcryptDesktopTool](https://github.com/biomade/BcryptDesktopTool)
The latest and greatest branch is the 'ReleaseMe' which is the primary branch. This has both the electron-build and electron-package scripts.   
I look forward to hearing about what you find.

**Comment by develar** [comment]
You have 2 erros in your app.

1. Filenames in the asar archive are CASE SENSITIVE. Folder is named as **B**crypt, but in the code referenced as **b**crypt.

2. No menu on macOS because you set menu not on `ready` event.

**Comment by biomade** [comment]
Thanks, I did not know there was a case sensitivity issue.
