### ISSUE TITLE
allowToChangeInstallationDirectory is not support on Squirrel?

### ISSUE THREAD

**Issue by divefox** [electron-userland/electron-builder#1372]
* **Version**: 
15.4.3

* **Target**: 
windows

Here is parts of my packager.json 

"win": {
      "target": [
        "nsis",
        "squirrel"
      ]
    },
    "publish": [
      {
        "provider": "generic",
        "owner": "fox",
        "repo": "fox",
        "url": "http://127.0.0.1/update/${os}_${arch}"
      }
    ],
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": true,
      "runAfterFinish": false
    }

The release file of exe (by Nsis generated) can't autoupdate?
Or the release file of exe (by Squirrel generated) can't have the property of allowToChangeInstallationDirectory to select path by user?
Is that right? And how can I use both of the property, autoupdate and allowToChangeInstallationDirectory to one release file?

Thank you very much for your help!

**Comment by develar** [comment]
NSIS supports auto-update — https://github.com/electron-userland/electron-builder/wiki/Auto-Update

Squirrel.Windows is deprecated — use NSIS, allowToChangeInstallationDirectory is supported only by NSIS.

**Comment by SunithaHegde** [comment]
Is there a way to avoid prompt for the path while installing the updated application.?
I'm using electron-updater along with allowToChangeInstallationDirectory:true. 
I need prompt for installation directory only for the first installation. Whenever there is an update on the app, it should be installed in the same location.
