### ISSUE TITLE
URLs generated by s3Url result in certificate error on request -> breaks S3 autoUpdate

### ISSUE THREAD

**Issue by Sukram21** [electron-userland/electron-builder#1373]
* **Version**: 15.4.2

* **Target**: mac, win

In https://github.com/electron-userland/electron-builder/commit/7041b5d3e2b17983973d5cea41215b5c371609d7#diff-36ba9eb20bed1b6c45f54cf4faedfcabL81, the `s3Url` method behavior was changed from `https://s3.amazonaws.com/${options.bucket}` to `https://${options.bucket}.s3.amazonaws.com`. 

**Resulting Problem:** If the bucket name contains any dots, requesting new URL will result in a SSL certificate warning (AWS S3 wildcard certificate is `*.s3.amazonaws.com, s3.amazonaws.com` -> doesn't match). This is already mentioned here: https://github.com/electron-userland/electron-builder/commit/7041b5d3e2b17983973d5cea41215b5c371609d7#diff-b8b7b963245d02b44186a38315e09df6L85 

> format `https://s3.amazonaws.com/bucket_name` [must be used](http://stackoverflow.com/a/11203685/1910191)

I guess this just got lost when committing.

**Result:** S3 auto-update checks don't work as they get stuck in a SSL certificate warning.

**Solution:** Revert the `s3Url` method behavior. 

I will create a pull request soon. Maybe I'm missing something, but was there a reason for this change?

**Comment by develar** [comment]
Because

```
develar-imac:~ develar$ curl -v -L https://s3.amazonaws.com/develar/test/latest.yml
*   Trying 54.231.40.2...
* TCP_NODELAY set
* Connected to s3.amazonaws.com (54.231.40.2) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: s3.amazonaws.com
* Server certificate: DigiCert Baltimore CA-2 G2
* Server certificate: Baltimore CyberTrust Root
> GET /develar/test/latest.yml HTTP/1.1
> Host: s3.amazonaws.com
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< x-amz-bucket-region: eu-central-1
< x-amz-request-id: 1D7811AE111228D4
< x-amz-id-2: xXq5ltKGLm9b7a8LuIIarqsqmxfJpViGr+w9mL0Da3uvSeqpmvCOOAcmkayIjEbPKTo9FFiJo3k=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Wed, 15 Mar 2017 10:24:13 GMT
< Server: AmazonS3
< 
<?xml version="1.0" encoding="UTF-8"?>
* Curl_http_done: called premature == 0
* Connection #0 to host s3.amazonaws.com left intact
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>develar</Bucket><Endpoint>develar.s3.amazonaws.com</Endpoint><RequestId>1D7811AE111228D4</RequestId><HostId>xXq5ltKGLm9b7a8LuIIarqsqmxfJpViGr+w9mL0Da3uvSeqpmvCOOAcmkayIjEbPKTo9FFiJo3k=</HostId></Error>
```

**Comment by develar** [comment]
Dotted name works for me. No cert error for `http://develar.dot.s3.eu-central-1.amazonaws.com/latest.yml`. And I have no idea how to make it working if use `https://s3.amazonaws.com/${options.bucket}` format.

**Comment by Sukram21** [comment]
Ok, I got what you mean!

On your second comment: Dotted names work if accessing the file via http. But accessing via https does not work.

**Comment by Sukram21** [comment]
And the URL generated by `s3Url` is an https URL in either case, so it will lead to the mentioned problem with dotted names.

**Comment by develar** [comment]
@Sukram21 Ouch, yes. I got warning.

So, the question is — how can I access files in subdirectories? Why I get PermanentRedirect error accessing `http://s3.amazonaws.com/develar.dot/latest.yml`?

**Comment by Sukram21** [comment]
The two possible S3 url patterns for dotted bucket names are:
1. We omit the https: `http://${options.bucket}.s3.amazonaws.com` Downside: No SSL connection.
2. We add a region to the hostname: `https://s3.${options.region}.amazonaws.com/${options.bucket}`Downside: Additional option (`region`) users have to specify (but only if they are using dotted bucket names!)

**Comment by develar** [comment]
I prefer solution 2. If region is specified, use this format.

**Comment by develar** [comment]
BTW — do not modify `.md` files, or use `yarn api` to regenerate it.

**Comment by Sukram21** [comment]
Ok, I'll implement solution 2. 

Thanks for the advice - didn't recognize that the `.md` file contents are generated automatically.

**Comment by Sukram21** [comment]
Note: Instead of having to set a region manually in the options, we could identify the region programmatically (via `bucket.get_location` like described by https://github.com/boto/boto/issues/2836#issuecomment-250434915). 

I will implement the `option.region` variant as it is is easier, but it would be a nice iteration for the future if anyone is fancy doing it.

**Comment by develar** [comment]
@Sukram21 If we can use http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property, we  should use it. 
So, please 

* move this dependency to main electron-builder
* modify app-update.yml (add region) to avoid this dependency in the electron-updater

But... in any case `option.region` is required and so, you can do only it, and I will do rest of work.

**Comment by Sukram21** [comment]
I'll look into it

**Comment by Sukram21** [comment]
Thanks for telling me the approach on how to implement it! 

I now added some commits to #1374. 
Had quite some trouble understanding the code base (and still not completely sure if I did everything right). 
Additional difficulties: `npm test`/`yarn test` result in quite a lot of errors for me. Also, after running `yarn api`, a lot of changes occurred in `docs/Developer API.md`, I'm not sure why that's the case.

So - I would appreciate a code review with suggestions how to continue 😅

**Comment by jonmanzo** [comment]
FYI, Region specific url for S3 is s3-region.amazonaws.com not s3.region...

**Comment by Sukram21** [comment]
Ah, thanks, you're right. The bucket I use allows the use of `s3.<region>.amazonaws.com`, that's why I thought this would be normal (see http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region for valid endpoint names).

It is even a bit more complicated - from http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro , I conclude that the pattern `https://s3-<aws-region>.amazonaws.com/<bucket>` does not work for buckets in the US East (N. Virginia) region. For buckets in this region, `http://s3.amazonaws.com/<bucket>` must be used.

**Comment by develar** [comment]
@Sukram21 As we will use new format only for dotted names, we can handle this issue later.

**Comment by jonmanzo** [comment]
Just a thought, but with all the possibilities, why not expose a bucketEndpoint option, thus allowing the full url to be pieced together if desired?

**Comment by develar** [comment]
We should provide a solution, not a tool with million options. As your original issue is solved (auto detect region if dotted and use it), I prefer to wait another bug report about unsupported regions.

**Comment by jonhester** [comment]
This still seems to be an issue. I'm wondering if the new version of electron-builder-http wasn't properly built because this is what I have still for `publishOptions.js` even though the version is 15.5.1:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.githubUrl = githubUrl;
exports.s3Url = s3Url;
function githubUrl(options) {
    return `${options.protocol || "https"}://${options.host || "github.com"}`;
}
function s3Url(options) {
    let url = `https://${options.bucket}.s3.amazonaws.com`;
    if (options.path != null) {
        url += `/${options.path}`;
    }
    return url;
}
//# sourceMappingURL=publishOptions.js.map
```

**Comment by develar** [comment]
> even though the version is 15.5.1:

**15.6.1**

**Comment by jonhester** [comment]
Hmmm, npm shows 15.5.1 as the latest: https://www.npmjs.com/package/electron-builder-http.  And if I try to install manually I get `Couldn't find any versions for "electron-builder-http" that matches "15.6.1"
`. Is it possible that this still needs to be published?

**Comment by develar** [comment]
@jonhester Thanks. 15.6.2 published.
