### ISSUE TITLE
install-app-deps failure cause can't find module electron-updater

### ISSUE THREAD

**Issue by cumajkeee** [electron-userland/electron-builder#1375]
* **Version**: 15.2.0

* **Updater Version**: 1.8.2

* **Target**: NSIS

```
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! version not found: electron-updater@1.8.2
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR! /Users/{path}/electron/app/npm-debug.log
```
If install manually - works fine. What can be the reason of it?

**Comment by develar** [comment]
Please update `electron-updater` to 1.10.1

**Comment by cumajkeee** [comment]
@develar, same result

**Comment by cumajkeee** [comment]
Hey @develar any ideas why it can happen? Manual install works, when try to see latest available version using ```npm view electron-updater version``` - also see 1.10.1. But when clean all deps, and try to call ```npm i``` from root, in always fails on install-app-deps step.

**Comment by develar** [comment]
@cumajkeee Could you please show your package.json? Have you tried yarn?

**Comment by cumajkeee** [comment]
Yarn - no, which one dev or app?

**Comment by develar** [comment]
> which one dev or app?

dev

**Comment by cumajkeee** [comment]
```
{   
"name": “***”, 
"version": “0.0.1”,   
"description": “***”,   
"private": true,   
"scripts": { 
    "postinstall": "install-app-deps", 
    "start": "npm run prepare && electron ./app", 
    "s": "electron ./app",
     "prepare": "grunt clean:electron && grunt electron:dev -f",
     "prepare:prod": "grunt clean:electron && grunt electron:prod -f",
     "build": "npm run prepare && build --x64", 
    "build:prod": "npm run prepare:prod && build --x64"
   },
   "build": { 
    "appId": “***”, 
    "extraFiles": [       "resources/**"     ], 
    "mac": { 
      "category": “***”
     }, 
    "dmg": {
       "contents": [ 
        {
           "x": 330, 
          "y": 220,
           "type": "link", 
          "path": "/Applications" 
        }, 
        {
           "x": 117,
           "y": 220 
        } 
      ]  
   },
     "win": {
       "target": "nsis"
     }, 
    "nsis": {
       "deleteAppDataOnUninstall": true
     }, 
    "publish": { 
      "provider": "generic", 
      "url": ""
     } 
  },
   "devDependencies": { 
    "electron": "1.6.2", 
    "electron-builder": "15.4.3" 
  }
 } 
```

**Comment by cumajkeee** [comment]
latest builder not used cause errors in it's dependencies is still there https://github.com/electron-userland/electron-builder/issues/1344

**Comment by cumajkeee** [comment]
BTW @develar , have other question to you. If for example I use node-modules that are rebuild for native lang. I build application with on PC with Win10 with all needed env. And application I install on clear Windows 7. Is there possibility to have problems due older OS version will not understand modern code in rebuild modules and trigger errors?

**Comment by develar** [comment]
> Is there possibility to have problems due older OS version will not understand modern code in rebuild modules and trigger errors

In case of Windows — no. It is ok to build on win 10 for win 7. (it is possible to write such native node modules, but it is theoretical).

**Comment by cumajkeee** [comment]
For me also, just several users has problems with that. So I want to understand the whole process for modules rebuild to identify core of a problem. Last question, node-gyp rebuild modules for specific electron version. Is it problem that locally I have node v4.5.0, and my target (electron 1.6.2) using node. v7.x.x?

**Comment by develar** [comment]
> node-gyp rebuild modules for specific electron version. Is it problem that locally I have node v4.5.0, and my target (electron 1.6.2) using node. v7.x.x?

In any case electron headers are specified explicitly, regardless of node version.

> Is it problem that locally I have node v4.5.0

I suggest you to use at least latest LTS 6. Or better 7.

**Comment by cumajkeee** [comment]
Thanks a lot.
