### ISSUE TITLE
Symlinks in asarUnpack are not copied

### ISSUE THREAD

**Issue by NTag** [electron-userland/electron-builder#1376]
* **Version**: 15.2.0

* **Target**: Linux x64

With the `asarUnpack` option, it is possible to specify directories. The symlinks in those will not be copied in the `app.asar.unpack/` destination folder.

I think we can see [here](https://github.com/electron-userland/electron-builder/blob/fb24e26afac08b1b73c342beb07a0fbe33a6f067/packages/electron-builder/src/asarUtil.ts#L225) that only *files* are added to the array `filesToUnpack`, and that no symlink will be added to `filesToUnpack`.

**Comment by develar** [comment]
Workaround: set asar to false.

**Comment by develar** [comment]
I hope it is obsolete now.

**Comment by Lucaszw** [comment]
This issue (or at least a similar one) still appears to be occurring for me. I have a bunch of sibling packages, that are linked together via `lerna bootstrap`. When running electron-builder, the node_modules of the sibling packages are not installed causing some missing package errors.
```
lerna --version
2.5.1
electron-builder --version
19.56.0
npm --version
5.4.2
node --version
v8.2.1
```

**Comment by develar** [comment]
@Lucaszw Is it possible to provide sample project?

**Comment by Lucaszw** [comment]
Np!

https://github.com/Lucaszw/lerna-electron-builder-sample

After running electron builder:
`app/dist/win-ia32-unpacked/resources/app/node_modules` does not include lodash or backbone (dependencies of packages/app's siblings).

Running the installer leads to the following error message:

![capture](https://user-images.githubusercontent.com/2607311/35865270-1164631a-0b22-11e8-8bce-efd28046cb67.PNG)

**Comment by Slapbox** [comment]
Is there anything we can try to resolve this? I tried adding the relevant folders to `asarUnpack`, but no luck with that.

`Electron-builder 20.8.1`
`Node 8.11.1`
`npm 5.6.0`

**Comment by sytolk** [comment]
This issue exist for Linux platform with electron-builder v22.13.1
