### ISSUE TITLE
Fails: Auto-update in Windows with autoDownload=false and downloadUpdate() / checkForUpdates() (after switching to autoDownload=true)

### ISSUE THREAD

**Issue by KYSSelectron** [electron-userland/electron-builder#1381]
* **Version**: 10.15.2

* **Target**: windows10

While executing `autoUpdater.checkForUpdates();` works in the sense that it downloads and installs the update, I'm failing trying to give the user the option of saying "yes" or "later".

I've tried two things, this is

```
autoUpdater.autoDownload = false;
autoUpdater.checkForUpdates();
```
and when the user says YES
```
autoUpdater.downloadUpdate();
```
And the second strategy, when the user says YES
```
autoUpdater.autoDownload = true;
autoUpdater.checkForUpdates();
```

Both fail and I cannot update the application. Am I doing something wrong or this is not yet implemented?

**Comment by KYSSelectron** [comment]
Doesn't work after having updated to version 15.5.1

**Comment by AlienHoboken** [comment]
You can let autoupdater download the update in the background as normal, then when it is ready you can display a prompt to let them decide. To do this listen to the `updated-downloaded` event on autoUpdater to know when an update is ready to install. Then when the user says to proceed, call `autoUpdater.quitAndInstall()`. For example:

```javascript
autoUpdater.checkForUpdates()

autoUpdater.on('update-downloaded', function(progress) {
  if(user says yes to update)
    autoUpdater.quitAndInstall();
  else
    //postpone update
});
```

**Comment by KYSSelectron** [comment]
I've noticed I had an error in the code. Once solved I've executed your suggestion and what I've seen is that

- when running `autoUpdater.quitAndInstall();` it doesn't close the app or does anything "visible"
- when NOT running this (the user says NO), it neither does anything
- BUT, in **both** cases when I close the app it gets **updated** (invisibly, but the desktop icon disappears and appears again and when I start it again it is the last version)

Now I haven't tested whether `downloadUpdate()` works or not, but I'd guess it doesn't provided the behavior of `quitAndInstall()`

**Comment by KYSSelectron** [comment]
It seems that it works, but the error on my code was the responsible (I have tested changing the `autoUpdater.autoDownload` and checking again for updates), so I close the issue.

Thanks!
