### ISSUE TITLE
Can i stop the download if the download have alredy start??

### ISSUE THREAD

**Issue by George35mk** [electron-userland/electron-builder#1384]
* **Version**: 
12.3.1

* **Target**: 
1.4.2

there is any method that i can use if i want to stop the download if the download started like

````
autoUpdater.cancelTheDownload();
````

or this is bad idea ??

thnx all for your help

**Comment by develar** [comment]
Please see `cancellationToken` in the https://github.com/electron-userland/electron-builder/wiki/Auto-Update#UpdateCheckResult

Call [cancel](https://github.com/electron-userland/electron-builder/wiki/Developer-API#module_electron-builder-http/out/CancellationToken.CancellationToken+cancel).

**Comment by George35mk** [comment]
thnx

**Comment by jason-zuo** [comment]
hi,can you fixed it,i faced the same problem,and i use` downloadPromise.cancel()` is note work
