### ISSUE TITLE
Download update from public Github repo failed on Mac

### ISSUE THREAD

**Issue by KSKS** [electron-userland/electron-builder#1388]
electron-builder: 15.6.4
electron-updater: 1.10.4

Steps:
1. Publish two versions (0.4.7, 0.4.8) of my app to a public Github repository.
2. Download and run version 0.4.7.
3. "update-available" is fired by autoupdater.
4. Downloading update from Mac failed with error:
Update download failed. The server sent an invalid response. Try again later.

The same steps works on Windows.

After I analyzed the network traffic, I found these requests/responses:

request "GET https://github-cloud.cs.amazonaws.com/releases/.../...56781c.json?...."
response with 200 OK and json:
{
  "version": "0.4.8",
  "releaseDate": "2017-03-20T23:08:58.409Z",
  "url": "https://github.com/KSKS/mtio-dev-releases/releases/download/v0.4.8/ManualTest.io-0.4.8-mac.zip"
}

If I follow that url, I can download the zip.

Then followed with:
request "GET https://api.github.com/repos/KSKS/mtio-dev-releases/releases/assets/3449539" with header "Accept: application/json"
response with 200 OK and a json with a browser_download_url to "https://github.com/KSKS/mtio-dev-releases/releases/download/v0.4.8/latest-mac.json"

request "GET https://api.github.com/repos/KSKS/mtio-dev-releases/releases/assets/3449539" with header "Accept: application/**zip**"
response with **415 Unsupported Media Type** and body
{"message":"Unsupported 'Accept' header: [#<Sinatra::Request::AcceptEntry:0x007f6f8cf56290 @entry=\"application/zip\", @type=\"application/zip\", @params={}, @q=1.0>]. Must accept 'application/json'.","documentation_url":"https://developer.github.com/v3/media"}

I think this is where the download failed and the invalid response error is returned.

**Comment by AlienHoboken** [comment]
It looks like you have `GH_TOKEN` environment variable set. If `GH_TOKEN` variable is set, electron-updater defaults to using Github API / Private Github Provider. Try unsetting for public repositories.

However it still should work for public repos. Let me look and see if I can tell what is going on.

@develar Perhaps we need a **private** flag in github publish configuration? People deploying and testing updater on same box might unexpectedly use private github provider.

**Comment by develar** [comment]
@AlienHoboken Probably we should not use private GitHub provider only because `GH_TOKEN` env exists. Maybe we should add option to github options like `private`?

**Comment by AlienHoboken** [comment]
It looks like you have GH_TOKEN environment variable set. If GH_TOKEN variable is set, electron-updater defaults to using Github API / Private Github Provider. Try unsetting for testing auto update with public repositories.

However it still should work for public repos. Let me look and see if I can tell what is going on.

@develar Perhaps we need a private flag in github publish configuration? People deploying and testing updater on same box might unexpectedly use private github provider. Only use private provider if private flag AND GH_TOKEN?

**Comment by KSKS** [comment]
After removing the token it is working now. Thank you.

I originally put the token in the GithubOption under build->publish in the package.json, which was, obviously, used to publish my releases. I thought that was an accepted use case of Github token, so it never occurred to me that it was the culprit. It would be nice to use a private flag instead, and maybe even return an error/warning if only one of the private flag and token is present. Just a suggestion.
