### ISSUE TITLE
${arch} missing from app-update.yml

### ISSUE THREAD

**Issue by mikecao** [electron-userland/electron-builder#1389]
* **Version**: 15.6.2

* **Target**: Windows

This is in my `package.json`:

```
    "publish": {
      "provider": "generic",
      "url": "https://website.com/download/${os}/${arch}",
      "channel": "latest"
    }
```

The generated `app-update.yml` file contains this:

```
provider: generic
url: 'https://website.com/download/win'
channel: latest
```

**Comment by develar** [comment]
Nsis installer contains both archs. So, no arch.

**Comment by mikecao** [comment]
@develar I think it should still default to whatever was passed in. If I run `build --x64 --mac` and it shows up, but doesn't when I run `build --x64 --win`, then that can be confusing.

**Comment by develar** [comment]
> then that can be confusing.

> build --x64 --mac and it shows up

Really? I will check. Wanted behaviour — pass arch for mac or not?

**Comment by mikecao** [comment]
Ok I just tried a build for mac with the latest version and it doesn't show there either. But it used to work in older versions so something changed. If it's no longer supported then that's fine. But I think if `${arch}` is defined it should put something there instead of blank.

**Comment by develar** [comment]
> But I think if ${arch} is defined it should put something there instead of blank.

We just remove it from pattern. It doesn't work?

**Comment by mikecao** [comment]
I was just surprised it used to work but now doesn't. But it's ok, I can work around it. Thanks for the help. Closing this.

**Comment by develar** [comment]
>  I can work around it.

Tell what you want and it will be fixed. What's wrong?

**Comment by mikecao** [comment]
I think it should always pass the arch defined by the build command into `${arch}`.

**Comment by develar** [comment]
What to do in case of NSIS, where one installer contains both archs?

**Comment by mikecao** [comment]
It should be the same for NSIS, if I do `build --x64 --win` I would expect `x64` to show up. It's mainly for building a correct url so it shouldn't matter what the installer contains.

**Comment by develar** [comment]
And if you do `build --x64 --ia32 --win` arch should be removed, right?

**Comment by mikecao** [comment]
Maybe `x64-ia32`? I just don't think it should be blank because you don't know if something was broken.

**Comment by develar** [comment]
> Maybe x64-ia32

No, because it is not valid arch string. I think it is better just remove arch from macro (as it is now).

**Comment by mikecao** [comment]
Ok that's fine
