### ISSUE TITLE
GitHub: Allow pre-release builds to be auto updated

### ISSUE THREAD

**Issue by jwheare** [electron-userland/electron-builder#1391]
* **Version**: 15.6.2

* **Target**: All

Currently, releases marked as "pre-release" are not supported by the auto-updater. An option should be added for this.

From a chat with @develar on Slack:

> Option will be added to AppUpdater. Default to use pre-release IF app version has "A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.”.

> We will detect latest pre-release using atom feed (https://github.com/owner/repo/releases.atom)

**Comment by develar** [comment]
Related #1182

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1149#issuecomment-294342878
