### ISSUE TITLE
Pepper Flash Plugin erro on load

### ISSUE THREAD

**Issue by miguelsmuller** [electron-userland/electron-builder#1392]
Hello everyone,

I'm trying to create an install for my educational game aggregator project. But I'm having problems, I'm using the Pepper Flash Plugin to run the games and it seems like it does not work after with the electron-builder.

This is my project: [https://github.com/miguelsmuller/centro-de-estudos](https://github.com/miguelsmuller/centro-de-estudos)
I'm using electron 1.6.2

And I'm trying to create the installer for linux. But in case on windows also is not working.

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-builder/issues/644#issuecomment-237662259
