### ISSUE TITLE
Add muon support

### ISSUE THREAD

**Issue by quanglam2807** [electron-userland/electron-builder#1394]
* **Version**: 15.6.2
* **Target**: All

I'm working on a browser-like desktop app and https://github.com/brave/muon (a forked version of Electron) seems to work much better. Is it possible to use electron-builder with muon?

**Comment by develar** [comment]
Should be easy to support. I will check in 2 days.

**Comment by develar** [comment]
@bbondy electron-builder supports `muon`.  Probably https://www.npmjs.com/package/brave-builder can be deleted.

**Comment by develar** [comment]
Set [muonVerson](https://github.com/electron-userland/electron-builder/wiki/Options#Config-muonVersion) to build for muon.

**Comment by bbondy** [comment]
Thanks for the heads up, I posted this bug on our tracking to change back
https://github.com/brave/browser-laptop/issues/7857

**Comment by quanglam2807** [comment]
@develar Kudo! But I received this bug when I signed the app:

```
Signing app (identity: Developer ID Application: Quang Lam (FVFM95DDPG))
{ Error: Command failed: codesign --sign Developer ID Application: Quang Lam (FVFM95DDPG) --force /Users/quanglam2807/Projects/webcatalog/dist/mac/WebCatalog.app/Contents/Frameworks/Brave Framework.framework/Brave Framework
/Users/quanglam2807/Projects/webcatalog/dist/mac/WebCatalog.app/Contents/Frameworks/Brave Framework.framework/Brave Framework: code object is not signed at all
In subcomponent: /Users/quanglam2807/Projects/webcatalog/dist/mac/WebCatalog.app/Contents/Frameworks/Brave Framework.framework/Helpers/crashpad_handler
```

I guess it's because `electron-builder` does not sign `crashpad_handler`.
