### ISSUE TITLE
i try to use electron with typescript 

### ISSUE THREAD

**Issue by George35mk** [electron-userland/electron-builder#1397]
* **Version**: 

* **Target**: 
windows

i just try to use typescript with electon but when i run the app i have this error on the console
![typescript error](https://cloud.githubusercontent.com/assets/20750445/24231245/21f9f3b2-0f8c-11e7-839b-0c27003b0732.PNG)

````
class Student {
    fullName: string;
    constructor(public firstName, public middleInitial, public lastName) {
        this.fullName = firstName + " " + middleInitial + " " + lastName;
    }
}

interface Person {
    firstName: string;
    lastName: string;
}

function greeter(person : Person) {
    return "Hello, " + person.firstName + " " + person.lastName;
}

var user = new Student("Jane", "M.", "User");

document.body.innerHTML = greeter(user);
````

i have see some projects on github use typescript , what i am doing wrong ??

**Comment by AlienHoboken** [comment]
Is this an issue with electron-builder? Or just a general programming question. If it's a programming question check out [http://stackoverflow.com/](http://stackoverflow.com/). Issues on GitHub are for problems with the project.

**Comment by George35mk** [comment]
ye is general question

**Comment by develar** [comment]
Please see TS project — https://github.com/develar/onshape-desktop-shell

**Comment by George35mk** [comment]
thnx develar i try to use typescript in my electron project becase is very dificul to controle the code, and i read that with typescrit you can make apps with 100 000+ lines of code , is easy to control and i remember i was looking on your project and i see  some files with ts extension. i am new to programming and i just ask your light . again thnx for the link develar
