### ISSUE TITLE
mac build zip file name does not follow build.artifactName

### ISSUE THREAD

**Issue by rophy** [electron-userland/electron-builder#1398]
* **Version**:  13.9.0

* **Target**:  mac

I have the following values in package.json:
- name: hello
- productName: world
- version: 1.0
- build.artifactName:  `${name}-${version}-${os}.${ext}`

# Expected Results:
1. hello-1.0-mac.dmg
2. hello-1.0-mac.zip

# Actual Results:
1. hello-1.0-mac.dmg
2. world-1.0-mac.zip    ---> Incorrect

**Comment by develar** [comment]
> Currently supported only for mas, pkg, dmg and nsis.

Will be supported.

**Comment by TriLe965** [comment]
> Will be supported.

Is it supported? I'm using electron-builder version 22.14.5 and still don't know how to set the `artifactName` of the zip output.

**Comment by jaydoherty** [comment]
Is it supported? I also can't figure out if it is supported now.

**Comment by bhavin-deep** [comment]
Also looking for this. @develar any updates here?

**Comment by lamualfa** [comment]
Need to custom the mac zip artifact name.
