### ISSUE TITLE
Error during Code Signing in Windows 7

### ISSUE THREAD

**Issue by lstrzalk** [electron-userland/electron-builder#1403]
* **5.24.1**: 

* **Windows app**: 

Without Code Signing electron-builder works properly. But when i set CSC_LINK and CSC_KEY_PASSWORD i recieve an error:

> SignTool Error: An error occurred while attempting to load the signing
        certificate from: C:\Users\username\AppData\Local\Temp\electron-builder-eZ9sHV\0.p12

This error occures after:
>Packaging for platform win32 ia32 using electron 1.3.2

Running script is:

> build --ia32

Log:
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle future_output\~predist: future_output
6 silly lifecycle future_output\~predist: no script for predist, continuing
7 info lifecycle future_output\~dist: future_output
8 verbose lifecycle future_output\~dist: unsafe-perm in lifecycle true
9 verbose lifecycle future_output\~dist: PATH: (Here is path)
10 verbose lifecycle future_output\~dist: CWD: C:\Users\username\Downloads\DesktopOffline\DesktopOffline
11 silly lifecycle future_output\~dist: Args: [ '/d /s /c', 'build --ia32' ]
12 silly lifecycle future_output\~dist: Returned: code: 4294967295  signal: null
13 info lifecycle future_output\~dist: Failed to exec dist script
14 verbose stack Error: future_output dist: `build --ia32`
14 verbose stack Exit status 4294967295
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid future_output
16 verbose cwd C:\Users\username\Downloads\DesktopOffline\DesktopOffline
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error future_output dist: `build --ia32`
22 error Exit status 4294967295
23 error Failed at the future_output dist script 'build --ia32'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pega-desktop-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build --ia32
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pega-desktop-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pega-desktop-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by develar** [comment]
Are you sure that your p12 file is correct and contains not only cert, but also private key?

**Comment by lstrzalk** [comment]
Yes, If I sign manually by signtool it's ok.

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by lstrzalk** [comment]
C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline>set DEBUG=electron-builder

C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline>npm run dist

\> OUTPUT-desktop-client@7.30.0-snapshot dist C:\Users\strzl\Downloads\DesktopOffli
ne\DesktopOffline
\> build --ia32

CI detected, so artifacts will be published if draft release exists
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for platform win32 ia32 using electron 1.3.2 to dist\win-ia32-unpacked


  electron-builder Found existing nsis C:\Users\strzl\.cache\nsis\nsis-3.0.1 +0m
s
  electron-builder Found existing winCodeSign C:\Users\strzl\.cache\winCodeSign\
winCodeSign-1.4.1 +2s
  electron-builder Executing C:\Users\strzl\.cache\winCodeSign\winCodeSign-1.4.1
\rcedit.exe C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\dist\win-ia32
-unpacked\OUTPUT.exe --set-version-string CompanyName www.OUTPUT.com --set-version-s
tring FileDescription OUTPUT-desktop-client --set-version-string ProductName OUTPUT
--set-version-string InternalName OUTPUT --set-version-string LegalCopyright Copyr
ight c 2017 www.OUTPUT.com --set-version-string OriginalFilename  --set-file-versi
on 7.30.0-snapshot --set-product-version 7.30.0-snapshot --set-icon C:\Users\str
zl\Downloads\DesktopOffline\DesktopOffline\resources\icons\AppIcon.ico +0ms
Signing OUTPUT.exe (certificate file "C:\Users\strzl\AppData\Local\Temp\electron-b
uilder-c4Lx5B\0.p12")
  electron-builder Executing C:\Users\strzl\.cache\winCodeSign\winCodeSign-1.4.1
\windows-6\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.d
ll /f C:\Users\strzl\AppData\Local\Temp\electron-builder-c4Lx5B\0.p12 /d OUTPUT /d
u https://www.OUTPUT.com/ /p test C:\Users\strzl\Downloads\DesktopOffline\DesktopO
ffline\dist\win-ia32-unpacked\OUTPUT.exe +765ms
Error: Command failed: C:\Users\strzl\.cache\winCodeSign\winCodeSign-1.4.1\windo
ws-6\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f
C:\Users\strzl\AppData\Local\Temp\electron-builder-c4Lx5B\0.p12 /d OUTPUT /du http
s://www.OUTPUT.com/ /p test C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline
\dist\win-ia32-unpacked\OUTPUT.exe
SignTool Error: An error occurred while attempting to load the signing
        certificate from: C:\Users\strzl\AppData\Local\Temp\electron-builder-c4L
x5B\0.p12

SignTool Error: An error occurred while attempting to load the signing
        certificate from: C:\Users\strzl\AppData\Local\Temp\electron-builder-c4L
x5B\0.p12

    at C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\node_modules\elect
ron-builder\src\util\util.ts:96:16
    at ChildProcess.exithandler (child_process.js:217:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at Object.exec (C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\node_
modules\electron-builder\src\util\util.ts:77:3)
    at C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\node_modules\elect
ron-builder\src\windowsCodeSign.ts:114:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at tsAwaiter (C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\node_mo
dules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\node
_modules\electron-builder\out\builder.js:153:12)
    at Object.<anonymous> (C:\Users\strzl\Downloads\DesktopOffline\DesktopOfflin
e\node_modules\electron-builder\out\build-cli.js:23:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! OUTPUT-desktop-client@7.30.0-snapshot dist: `build --ia32`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the OUTPUT-desktop-client@7.30.0-snapshot dist script 'build --
ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the OUTPUT-desktop-client p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs OUTPUT-desktop-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls OUTPUT-desktop-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\strzl\Downloads\DesktopOffline\DesktopOffline\npm-debug.log

**Comment by develar** [comment]
Windows version?

**Comment by lstrzalk** [comment]
Windows 7 Enterprise SP 1 64-bit, it's running as virtual machine.

**Comment by develar** [comment]
Something is wrong with your system — we bundle special `signtool.exe` for such old windows versions, but...

* please use windows 10 to build
* or try to download https://www.microsoft.com/en-us/download/details.aspx?id=8279, find `signtool.exe` in the downloaded dir and set `SIGNTOOL_PATH` to file path.

**Comment by develar** [comment]
> 5.24.1:

Ouch, really? Please use latest version.
