### ISSUE TITLE
Rebuilding the native dependencies for muon fails

### ISSUE THREAD

**Issue by quanglam2807** [electron-userland/electron-builder#1404]
* **Version**: 16.3.0

* **Target**:  muon / darwin

`electron-builder` rebuilds the native dependencies using electron server. For example, if `muonVersion  = '2.56.9`, it will load from `https://atom.io/download/electron/v2.56.9/iojs-v2.56.9.tar.gz` and then fail.

**Comment by bbondy** [comment]
at the moment download url isn’t relevant because we are using target=node, this might change in the future though.

**Comment by develar** [comment]
So, we should not rebuild at all... Only for arch. Thanks for answer.

**Comment by bridiver** [comment]
the npmrc config should also now have `target=node` instead of `target=electron` for muon. This reflects a recent change to integrate node with the exe rather than having a separate node shared lib. As long as node v8 versions stay in sync with chromium v8 versions we can avoid the download/rebuild. This is really a muon issue I think and not electron-builder, but we can't close electron-builder issues

**Comment by quanglam2807** [comment]
I hope this issue will be fixed soon. Electron has many problems with `window.open` and a lot of my users rely on it.

**Comment by bridiver** [comment]
There is nothing to fix @quanglam2807 
These are the current settings https://github.com/brave/browser-laptop/blob/master/.npmrc
and for chromium 56 based muon versions you would use
https://github.com/brave/browser-laptop/blob/v0.13.5dev/.npmrc

**Comment by quanglam2807** [comment]
@bridiver But `electron-builder` will try to build with atom npmrc, right? So @develar still needs to change some configurations to make it work smoothly?

**Comment by bridiver** [comment]
it will use whatever .npmrc you have in your project. It tries to download from atom.io because you are missing `disturl = https://brave-laptop-binaries.s3.amazonaws.com/atom-shell/dist` in your .npmrc

**Comment by quanglam2807** [comment]
@bridiver Kudo! I don't even have a `.npmrc`. I'm newbie.

**Comment by develar** [comment]
@bridiver Fix is required on electron-builder side because we explicitly set all required env/cli args. Fixed.

**Comment by bridiver** [comment]
@develar as of 2.57.x native node modules will not work with `target=electron`. See `.npmrc` settings in my comment above.

**Comment by develar** [comment]
@bridiver We don't set `target=electron` for muon anymore (since 16.8.0). As @bbondy said, "at the moment download url isn’t relevant because we are using target=node, this might change in the future though."

**Comment by bbondy** [comment]
OK we changed to requiring a new .npmrc like this now:

```
runtime = electron
target_arch = x64
brave_electron_version = 2.58.5
chromedriver_version = 2.27
target = v2.58.5
disturl=http://brave-laptop-binaries.s3.amazonaws.com/atom-shell/dist/
build_from_source = true
```

@quanglam2807 could you update to that?

**Comment by bbondy** [comment]
also if you don't mind publishing a release, this will save us from having to fork as we need to do a release asap.

**Comment by quanglam2807** [comment]
@bbondy I am sorry but I cannot test it now as I am working on another pull request. But as I understand, `electron-builder` automates many processes so @develar needs to make some changes to make it compatible with the `.npmrc` file.

**Comment by bbondy** [comment]
No problem we'll find a work-around. Is there a way to tell it to not rebuild native modules?

**Comment by quanglam2807** [comment]
@bbondy You can set `npmRebuild` to `false`. https://github.com/electron-userland/electron-builder/wiki/Options

**Comment by develar** [comment]
@bbondy I can publish release today according to your comment. How we can compute chromedriver_version from brave version?

**Comment by develar** [comment]
According to @bbondy comment earlier, electron-builder doesn't rebuild native modules for muon now.

**Comment by bbondy** [comment]
I think you don't actually need it since it is only needed if you are running tests and for packaging you don't do that.

**Comment by bbondy** [comment]
Thanks for your help guys, we were stuck on a really old version so we couldn't use npmRebuild, but we just updated to the latest and now it works again.
https://github.com/brave/browser-laptop/issues/8481

**Comment by quanglam2807** [comment]
@bbondy @develar  Also, I have problem with signing: https://travis-ci.org/webcatalog/webcatalog/jobs/226981722.
