### ISSUE TITLE
Asar: false, causing exception on app startup with v16.4.0

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#1409]
* **Version**: 16.4.0

* **Target**: Win64 NSIS

Just updated from 15.4.3 to 16.4.0

Received the following exception on App startup (install OK): 

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Unable to find a valid app at Object.<anonymous> ......\resources\electron.asar\browser\init....:9

If I set `asar: true`, all is good.

I use `asar: false` during development. 

**Build Config:**
```javascript
"build": {
    "appId": "com.myapp.myapp",
    "asar": false,
    "productName": "My App",
    "compression": "store",
    "npmRebuild": false,
    "win": {
      "target": [
        "nsis"
      ],
      "certificateSubjectName": "My Cert",
      "legalTrademarks": "My Trademark™"
    },    
    "nsis": {
      "perMachine": false,
      "allowElevation": true,
      "oneClick": true,
      "language": "3081"
    },
    "directories": {
      "buildResources": "resources",
      "output": "package_desktop",
      "app": "dist"
    }
  }
```

**Comment by dharders** [comment]
**FYI:** just tried v16.3.0 with `asar: false` and it worked!

Something happened in latest release ;)

**Comment by dharders** [comment]
Thanks @develar , just tried 16.4.2 with the fix but same exception still occurring on app launch, with `asar: false`. 16.3.0 last known working version.

**Comment by develar** [comment]
@dharders Is it possible to provide app for reproduce?

**Comment by dharders** [comment]
@develar Sure, here you go [https://github.com/dharders/electron-builder-repro-app-issue1409](https://github.com/dharders/electron-builder-repro-app-issue1409)

Instructions are given in the repo `README.md`

**Comment by develar** [comment]
Thanks, fix will be in the next release.

**Comment by dharders** [comment]
Thanks @develar ! I can confirm this is now working. You're a champion!
