### ISSUE TITLE
Arguments aren't passed to Electron with portable target

### ISSUE THREAD

**Issue by yishn** [electron-userland/electron-builder#1410]
* **Version**:  16.4.2

* **Target**:  `portable`

When creating a portable executable file, say `portable.exe`, it's desirable that all arguments that are passed to `portable.exe` are also passed to Electron as well. It's currently not the case.

**Comment by mordonez-me** [comment]
Is there a way to pass args to portable?

**Comment by RoyiAvital** [comment]
Is there a documentation about portable mode?
The output is single `EXE`. In what way it is portable?

**Comment by RoyiAvital** [comment]
Users would love to some clarification as requested in https://github.com/jgraph/drawio-desktop/issues/22.
