### ISSUE TITLE
Prebuild guidance

### ISSUE THREAD

**Issue by neurosnap** [electron-userland/electron-builder#1411]
Greetings,

Thanks for all your hard work @develar on this project, much appreciated.

I was curious about using prebuild for a native module dependency to avoid building the app using windows/linux.  

Am I able to provide the prebuilt binaries for a native dependency myself?  How does electron-builder determine if prebuild is available for a dependency?

So if I use prebuild on a project, like `node-spellchecker` that does not provide their own prebuild, can I instruct electron-builder to use it?

Thanks!

**Comment by develar** [comment]
Follow to official Electron recommendations, electron-builder by default explicitly force rebuild from sources.

Please set [npmSkipBuildFromSource) to use prebuild binaries.

> Am I able to provide the prebuilt binaries for a native dependency myself? How does electron-builder determine if prebuild is available for a dependency?

Yes. Just follow official tool manuals. https://www.npmjs.com/package/prebuild

During past year we have identified and fixed mostly all issues in this area, and `prebuild` is also much better now than before. So, maybe, we should reconsider default value for `npmSkipBuildFromSource`. But it can leads to broken app (you cannot test release for all platforms every time), so, I am afraid it will be not enabled by default. So, you have to enable it explicitly.
