### ISSUE TITLE
Protocol scheme should work also in Linux

### ISSUE THREAD

**Issue by pakastin** [electron-userland/electron-builder#1413]
* **Version**: latest

* **Target**: Linux

Protocol scheme should work also in Linux:
https://github.com/electron/electron/issues/4857#issuecomment-201124281

Would be great if electron-builder would support it without hacks.. :)

**Comment by Eshva** [comment]
Do I understand correctly that custom protocol registration that specified in build.protocols works only for MacOS? For Windows we need hack using NSIS target, for Linux we need some kind of hacks too. Maybe the electron-builder docs should be updated to reflect this clearly?

**Comment by pakastin** [comment]
desktop file should just have `MimeType` `x-scheme-handler/PROTOCOL_NAME_HERE`:
https://github.com/webtorrent/webtorrent-desktop/blob/73d5a4e1ab47c7139df836f4b7755f332d00a9c4/static/webtorrent.desktop#L16
