### ISSUE TITLE
Add vPrefixedTagName for auto update

### ISSUE THREAD

**Issue by alexbrazier** [electron-userland/electron-builder#1417]
* **Cersion**: 16.4.2

* **Target**: macOS

The publish option `vPrefixedTagName` should be added for auto update as the the `latest-mac.json` file and the auto update request to get the latest version will always assume that the url is `v1.0.0` instead of just `1.0.0`, causing errors if you don't tag releases starting with a `v`

**Comment by develar** [comment]
We write publish config as is, so, `vPrefixedTagName` is already available for `GitHubProvider`.

But! Due to Squirrel.Mac limitation we have to build url **in-advance** — **build-time**. So `computeDownloadUrl` should be fixed.

Done — will be release in 10 minutes.

**Comment by alexbrazier** [comment]
Awesome, thanks for the quick fix.
There also appears to be an issue with `GitHubProvider.ts` in a couple of places where the url is hardcoded with a `v` e.g. `https://github.com${basePath}/download/v${versionInfo.version}/${name}`, is it possible to use the `vPrefixedTagName` tag name for this as well?

**Comment by develar** [comment]
> is it possible to use the vPrefixedTagName tag name for this as well?

Yes, you are right, it is a part of fix.
