### ISSUE TITLE
Wiki: depends for deb in LinuxOptions

### ISSUE THREAD

**Issue by NTag** [electron-userland/electron-builder#1420]
Hello,

In the Wiki, the `depends` option (specifying the dependencies for a Linux `deb` target) is in the [LinuxBuildOptions](https://github.com/electron-userland/electron-builder/wiki/Options#linuxbuildoptions--platformspecificbuildoptions) part, whereas it seems it should be in the [DebOptions](https://github.com/electron-userland/electron-builder/wiki/Options#deboptions--linuxbuildoptions) part (which is the case in the [test](https://github.com/electron-userland/electron-builder/blob/5cfc69353c2915566b8a9a148ccaa7a78e22219e/test/src/linux/debTest.ts#L15), and what I experienced).

Or I didn't understand the documentation...

**Comment by develar** [comment]
It is supported in both places.

**Comment by NTag** [comment]
It didn't work for me in the `linux` part with `electron-builder` version 16.6.0. The deb only depended on the default dependencies. When moving `depends` to the `deb` part, then it worked.

Moreover, when removing the line `depends: ["foo"]` of [the test](https://github.com/electron-userland/electron-builder/blob/5cfc69353c2915566b8a9a148ccaa7a78e22219e/test/src/linux/debTest.ts#L16) `custom depends` of `test/out/linux/debTest.js`, it still passes (whereas it is supposed to test the dependency on `foo`).
