### ISSUE TITLE
Running Nsis-generated installer twice for same version silently overwrites directory

### ISSUE THREAD

**Issue by JonMarbach** [electron-userland/electron-builder#1421]
* **Version**: 16.6.0

n/a

* **Target**: win nsis

From what I can tell, there's no prompt in the nsis installer to prevent the user from re-installing an already-installed version over the top of itself (i.e., into the same, existing, directory.) (I'm using the nsis boring installer.) Should there be a prompt to confirm when overwriting an existing directory?

**Comment by develar** [comment]
For what? You should not write app datato app installation dir.
