### ISSUE TITLE
[question] How to handle exe name different from productName for nsis installer?

### ISSUE THREAD

**Issue by JonMarbach** [electron-userland/electron-builder#1422]
* **Version**: 16.6.0

n/a

* **Target**: win nsis

(Apologies in advance, I'm new to electron builder and nsis...)

I'm using electron-builder in --prepackaged mode, and it appears that the nsis installer is looking for an exe which has a name matching the productName from the package.json. Is there a way to tell the nsis installer that the "main" exe is named something else? If not, can I kindly request that feature?

To be extra clear, my productName has a space in it, like this: "Foo Bar" and my executable has another name, let's say "fb.exe". Is there a way to direct the nsis installer to treat fb.exe as the executable to run?

**Comment by develar** [comment]
Will be implemented. Could you please explain why you cannot use electron-builder directly?

**Comment by darkguy2008** [comment]
I'm needing this as well, because if I set ProductName a subdirectory in the user's install directory is created with that name, and I don't want that.

**Comment by baparham** [comment]
> Will be implemented. Could you please explain why you cannot use electron-builder directly?

Any update on this in the last 3 years?
