### ISSUE TITLE
From portable?

### ISSUE THREAD

**Issue by Wandalen** [electron-userland/electron-builder#1423]
We have several build targets for electron output: electron-portable, electron-installation.
Is it possible to make installation from portable built instead of remaking it from scratch? 
Many thanks.

**Comment by develar** [comment]
> Is it possible to make installation from portable built instead of remaking it from scratch?

What do you mean?

**Comment by Wandalen** [comment]
<img width="293" alt="screen shot 2017-03-31 at 2 27 22 pm" src="https://cloud.githubusercontent.com/assets/7414255/24548750/d9b58032-161e-11e7-948a-da2f5eb1bcab.png">

Encore.app are same.
First it's produced by electron-packager. 
Second time by your package( electron-builder ).
I'm wondering, is it possible to tell electron-builder to reuse portable package produced by electron-packager to make installation file( ie *.dmg ) somehow?

**Comment by develar** [comment]
Strongly recommended to use electron-builder also for packaging. But in any case you can — please see https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format

**Comment by Wandalen** [comment]
Exactly what I've looked for. Thank you for recommendation. 
Is it possible to produce only portable without producing installations with your package?

**Comment by develar** [comment]
> Is it possible to produce only portable without producing installations with your package

Yes. Use target `dir` or CLI `--dir`. e.g. to build for linux  — `--linux dir`. Or for current platform: `--dr`

PS. It is not portable. It is unpacked. We have special `portable` target for windows.

**Comment by Wandalen** [comment]
I see. Any difference between portable target for windows and unpacked?

**Comment by develar** [comment]
> Any difference between portable target for windows and unpacked?

it is one file and compressed using lzma  (~30 MB resulting electron app).

**Comment by Wandalen** [comment]
Got it. A bit confusing, but make sense. Thank you.
