### ISSUE TITLE
Github provider upload file name doesn't follow build.artifactName 

### ISSUE THREAD

**Issue by krystophv** [electron-userland/electron-builder#1427]
* **Version**: 16.6.0

* **Target**: mac, windows

When using the Github provider, it seems that the uploaded artifact's file name (`safeArtifactName`) doesn't take into account any configuration of the actual `artifactName` - it is always the same, regardless of the configured `artifactName`. It seems that this may be a similar issue to: https://github.com/electron-userland/electron-builder/issues/1398

**Comment by develar** [comment]
Related #1390

**Comment by develar** [comment]
Duplicates #1390

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/1390#issuecomment-288019166 If you are disagree, please comment linked issue.
