### ISSUE TITLE
Unpacking asar reveals entire source code

### ISSUE THREAD

**Issue by ngprasad** [electron-userland/electron-builder#1428]
* **electron-builder Version**: 13.9.0

 
* **electron-updater Version**: 1.8.2

* **Target**: Mac, Windows

I just noticed that after building the signed app has all application source code in asar file(MyApp.app>Show Package Contents>Contents>Resources>app.asar). This file upon unpacking has source code that anyone can see. How can I exclude source code from getting into the binary? We are developing a closed source application.

**Comment by develar** [comment]
Please see https://github.com/electron/electron/issues/3041
