### ISSUE TITLE
Help needed with file association

### ISSUE THREAD

**Issue by DracotMolver** [electron-userland/electron-builder#1429]
Electron-builder: 10.17.3
Target: Windows 10

Hi there. I'm trying to use the fileAssociations option. First, this is how the code in the `package.json` is formed
```json
  "build": {
    "win": {
      "target": [
        "nsis",
        "squirrel"
      ]
    }
  },
  "fileAssociations": [
    {
      "ext": [".mp3", ".wmv", ".wav", ".ogg"],
      "description": "Music file extension",
      "role": "none"
    }
  ],
  "nsis": {
    "perMachine": true
  },
```
It works fine, I mean, It doesn't throws me any error. But!, when I install the app, there is no file associated to the app. I can choose *Open with* and and I do click over a mp3 file, the app is launched. If this is the behavior, sorry and there's not an issue.

Secondly - this is a doubt -, when the app is launched by a file, how I can catch the path fo the file or the event emitted of being opened by the file. Thanks a lot for your time

**Comment by FromStoneage** [comment]
try:

- remove `squirrel` as target
- a custom file extension see if any file loads
- it sounds like its loading but you can't catch the file
- put logs in electron ipcrenderer and main process, use command line to launch the app. Rest are node.js code to handle files.

**Comment by develar** [comment]
> Electron-builder: 10.17.3

Please update to latest version.

**Comment by DracotMolver** [comment]
How can you close this without giving a decent answer. I wanted to say how to solve the second doubt, because it could be useful for someone else.

**Comment by develar** [comment]
If update will not help you — feel free to reopen.

**Comment by Ishaangandhi** [comment]
"Secondly - this is a doubt -, when the app is launched by a file, how I can catch the path fo the file or the event emitted of being opened by the file. Thanks a lot for your time"

I have the same question.

**Comment by sytolk** [comment]
I have an other question.. if app is started from file association like `electron-app /file/path..` how can I start App with an other param like `electron-app --my-custom-parm` -> this will be parsed like file path. It's much better to have additional parameter for file association only like `electron-app -open=/file/path..` Now I needs to catch and exclude any additional parameters from different sources like testing with spectron: `--user-data-dir` `--use-mock-keychain`
