### ISSUE TITLE
Try Rebuilding native production dependencies for win32:x64

### ISSUE THREAD

**Issue by LizanLycan** [electron-userland/electron-builder#1430]
[Latest Version]

--------------------- DESCRIPTION --------------------

When I run the `build` command the error below appears. I notice that the command `node-gyp configure build` worked correctly when I ran it directly in the native module folder "odbc". Any solution?

---------------------  ERROR ---------------------------
build --dir --ia32 --x64
Rebuilding native production dependencies for win32:x64
Error: C:\nodejs\node.exe exited with code 1
Output:

 odbc@1.2.1 install C:\ELECTRON-APP-PATH\node_modules\odbc-
 node-gyp configure build

Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\Release\iojs.lib : fatal error LNK1127: library is corrupt [C:\ELECTRON-APP-PATH\node_modules\odbc\build\odbc_bindings.vcxproj]

Error output:
gyp ERR! build error

**Comment by develar** [comment]
Is `npm rebuild` works?

**Comment by LizanLycan** [comment]
Completely, without errors. Another thing I must limit is that, for the native module 'odbc', an .npmrc file must be configured to correct an error with respect to .dll https://github.com/w1nk/node-odbc/issues/100#issuecomment-212504903

**Comment by develar** [comment]
Ouch, error is clear for me.  Please copy your `.npmrc` to `~/.electron-gyp`

**Comment by LizanLycan** [comment]
No, the error still appears. In such a case, how could you configure what I configure in .npmrc, but with electron-builder?

**Comment by develar** [comment]
> what I configure in .npmrc, but with electron-builder?

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/yarn.ts

Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by LizanLycan** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   'printer',
1 verbose cli   'odbc' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 info readInstalled object
5 verbose rebuild path, id [ 'C:\\USER\\Desktop\\APP-FOLDER\\node_modules\\odbc',
5 verbose rebuild   'odbc@1.2.1' ]
6 verbose rebuild path, id [ 'C:\\USER\\Desktop\\APP-FOLDER\\node_modules\\printer',
6 verbose rebuild   'printer@0.2.2' ]
7 silly rebuild set [ 'C:\\USER\\Desktop\\APP-FOLDER\\node_modules\\odbc',
7 silly rebuild set   'C:\\USER\\Desktop\\APP-FOLDER\\node_modules\\printer' ]
8 info build C:\USER\Desktop\APP-FOLDER\node_modules\odbc
9 info lifecycle odbc@1.2.1~preinstall: odbc@1.2.1
10 silly lifecycle odbc@1.2.1~preinstall: no script for preinstall, continuing
11 info linkStuff odbc@1.2.1
12 silly linkStuff odbc@1.2.1 has C:\USER\Desktop\APP-FOLDER\node_modules as its parent node_modules
13 verbose linkBins odbc@1.2.1
14 verbose linkMans odbc@1.2.1
15 verbose rebuildBundles odbc@1.2.1
16 info lifecycle odbc@1.2.1~install: odbc@1.2.1
17 verbose lifecycle odbc@1.2.1~install: unsafe-perm in lifecycle true
18 verbose lifecycle odbc@1.2.1~install: PATH: C:\USER\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\USER\Desktop\APP-FOLDER\node_modules\odbc\node_modules\.bin;C:\USER\Desktop\APP-FOLDER\node_modules\.bin;C:\USER\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\USER\Desktop\APP-FOLDER\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\nodejs\;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\USER\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\USER\AppData\Roaming\nvm;C:\Ruby22-x64\bin;C:\MinGW\bin;C:\MinGW\msys\bin\1.0;C:\USER;C:\USER
19 verbose lifecycle odbc@1.2.1~install: CWD: C:\USER\Desktop\APP-FOLDER\node_modules\odbc
20 silly lifecycle odbc@1.2.1~install: Args: [ '/d /s /c', 'node-gyp configure build' ]
21 silly lifecycle odbc@1.2.1~install: Returned: code: 1  signal: null
22 info lifecycle odbc@1.2.1~install: Failed to exec install script
23 verbose stack Error: odbc@1.2.1 install: `node-gyp configure build`
23 verbose stack Exit status 1
23 verbose stack     at EventEmitter.<anonymous> (C:\USER\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
23 verbose stack     at emitTwo (events.js:106:13)
23 verbose stack     at EventEmitter.emit (events.js:191:7)
23 verbose stack     at ChildProcess.<anonymous> (C:\USER\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
23 verbose stack     at emitTwo (events.js:106:13)
23 verbose stack     at ChildProcess.emit (events.js:191:7)
23 verbose stack     at maybeClose (internal/child_process.js:877:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
24 verbose pkgid odbc@1.2.1
25 verbose cwd C:\USER\Desktop\APP-FOLDER
26 error Windows_NT 10.0.14393
27 error argv "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "printer" "odbc"
28 error node v6.9.4
29 error npm  v4.1.1
30 error code ELIFECYCLE
31 error odbc@1.2.1 install: `node-gyp configure build`
31 error Exit status 1
32 error Failed at the odbc@1.2.1 install script 'node-gyp configure build'.
32 error Make sure you have the latest version of node.js and npm installed.
32 error If you do, this is most likely a problem with the odbc package,
32 error not with npm itself.
32 error Tell the author that this fails on your system:
32 error     node-gyp configure build
32 error You can get information on how to open an issue for this project with:
32 error     npm bugs odbc
32 error Or if that isn't available, you can get their info via:
32 error     npm owner ls odbc
32 error There is likely additional logging output above.
33 verbose exit [ 1, true ]

**Comment by develar** [comment]
Please attach electron-buidler out ("Rebuilding native production" and so on). I want to see exact command to ask you to try it manually.

**Comment by LizanLycan** [comment]
Rebuilding native production dependencies for win32:x64
Error: C:\nodejs\node.exe exited with code 1
Output:

> odbc@1.2.1 install C:\USER\Desktop\APP-FOLDER\node_modules\odbc
> node-gyp configure build

Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
  odbc.cpp
..\src\odbc.cpp(224): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc.cpp(271): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc.cpp(868): warning C4996: 'v8::Object::SetPrototype': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\o
dbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(2832): note: see declaration of 'v8::Object::SetPrototype'
..\src\odbc.cpp(897): warning C4996: 'v8::Object::SetPrototype': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\o
dbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(2832): note: see declaration of 'v8::Object::SetPrototype'
  odbc_connection.cpp
..\src\odbc_connection.cpp(584): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\no
de_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_connection.cpp(673): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\no
de_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_connection.cpp(917): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\no
de_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_connection.cpp(1166): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\n
ode_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
  odbc_statement.cpp
..\src\odbc_statement.cpp(219): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\nod
e_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_statement.cpp(274): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\nod
e_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_statement.cpp(507): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\nod
e_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_statement.cpp(572): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\nod
e_modules\odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
c:\users\lizandro zerpa\desktop\sistelsim\sistelsim_dev\api_rest\administrador-electron\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'SQLLEN' to 'double', possib
le loss of data [C:\USER\Desktop\APP-FOLDER\node_modules\odbc\build\odbc_bindings.vcxproj]
  ..\src\odbc_statement.cpp(360): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,SQLLEN>(A0)' being compiled
          with
          [
              A0=SQLLEN
          ]
  odbc_result.cpp
..\src\odbc_result.cpp(187): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(8334): note: see declaration of 'v8::Value::ToInt32'
..\src\odbc_result.cpp(340): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(8334): note: see declaration of 'v8::Value::ToInt32'
..\src\odbc_result.cpp(436): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(8334): note: see declaration of 'v8::Value::ToInt32'
..\src\odbc_result.cpp(597): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules\
odbc\build\odbc_bindings.vcxproj]
  C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(8334): note: see declaration of 'v8::Value::ToInt32'
  dynodbc.cpp
  win_delay_load_hook.cc
  Generating Code...
  strptime.c
C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\Debug\iojs.lib : fatal error LNK1127: library is corrupt [C:\USER\Desktop\SisTelSim\SisTelSim_Dev\API_REST\administr
ador-electron\node_modules\odbc\build\odbc_bindings.vcxproj]

Error output:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\USER\Desktop\APP-FOLDER\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\USER\\Desktop\\SisTelSim\\SisTelSim_Dev\\API_REST\\administrador-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "
build"
gyp ERR! cwd C:\USER\Desktop\APP-FOLDER\node_modules\odbc
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "printer" "odbc"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! odbc@1.2.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the odbc@1.2.1 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the odbc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs odbc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls odbc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\USER\Desktop\APP-FOLDER\npm-debug.log

    at ChildProcess.childProcess.once.code (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder-util\src\util.ts:134:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder-util\src\util.ts:97:3)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\yarn.ts:118:11
From previous event:
    at rebuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\yarn.js:87:22)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\yarn.ts:16:11
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at installOrRebuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:403:13
    at next (native)
From previous event:
    at Packager.installAppDependencies (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:485:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:231:20
    at next (native)
From previous event:
    at Packager.doBuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:379:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:274:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--debug"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! SisTelSimElectron@1.0.0 build: `build --dir --ia32 --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the SisTelSimElectron@1.0.0 build script 'build --dir --ia32 --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SisTelSimElectron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --dir --ia32 --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SisTelSimElectron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SisTelSimElectron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\USER\Desktop\APP-FOLDER\npm-debug.log

**Comment by develar** [comment]
It seems debug is not set. On windows please before build execute `set DEBUG=electron-builder`.

**Comment by LizanLycan** [comment]
> build --dir --ia32 --x64

  electron-builder Effective config: {
  electron-builder   "appId": "org.test.mytest",
  electron-builder   "nsis": {
  electron-builder     "oneClick": false,
  electron-builder     "allowToChangeInstallationDirectory": true
  electron-builder   },
  electron-builder   "electronVersion": "1.4.15",
  electron-builder   "win": {
  electron-builder     "icon": "build/icon.ico"
  electron-builder   }
  electron-builder } +0ms
Rebuilding native production dependencies for win32:x64
  electron-builder Spawning C:\nodejs\node.exe C:\USER\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js rebuild printer odbc +8s

> odbc@1.2.1 install C:\USER\Desktop\APP-FOLDER\node_modules\odbc
> node-gyp configure build

Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\Release\iojs.lib : fatal error LNK1127: library is corrupt [C:\USER\Desktop\SisTelSim\SisTelSim_Dev\API_REST\admini
strador-electron\node_modules\odbc\build\odbc_bindings.vcxproj]
Error: C:\nodejs\node.exe exited with code 1
Error output:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\USER\Desktop\APP-FOLDER\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\USER\\Desktop\\SisTelSim\\SisTelSim_Dev\\API_REST\\administrador-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "
build"
gyp ERR! cwd C:\USER\Desktop\APP-FOLDER\node_modules\odbc
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "printer" "odbc"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! odbc@1.2.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the odbc@1.2.1 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the odbc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs odbc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls odbc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\USER\Desktop\APP-FOLDER\npm-debug.log

    at ChildProcess.childProcess.once.code (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder-util\src\util.ts:134:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder-util\src\util.ts:97:3)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\yarn.ts:118:11
From previous event:
    at rebuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\yarn.js:87:22)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\yarn.ts:16:11
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at installOrRebuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:403:13
    at next (native)
From previous event:
    at Packager.installAppDependencies (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:485:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:231:20
    at next (native)
From previous event:
    at Packager.doBuild (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:379:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\packager.js:274:11)
    at C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\USER\Desktop\APP-FOLDER\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! SisTelSimElectron@1.0.0 build: `build --dir --ia32 --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the SisTelSimElectron@1.0.0 build script 'build --dir --ia32 --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SisTelSimElectron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --dir --ia32 --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SisTelSimElectron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SisTelSimElectron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\USER\Desktop\APP-FOLDER\npm-debug.log

**Comment by develar** [comment]
Please execute
```
npm_config_arch=x64 npm rebuild odbc printer --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --abi=50 --arch=ia32
```

**Comment by develar** [comment]
Please specify electron-builder version.

**Comment by LizanLycan** [comment]
electron-builder version 16.6.1, this version is like information or should I configure it somewhere?. Sorry, npm_config_arch is an npm command? Because as I am in Windows there is the bug of the binaries, then I must run from the folder .bin

**Comment by develar** [comment]
@LizanLycan I have changed command to avoid env.

**Comment by LizanLycan** [comment]
I pass to perfection without errors

**Comment by LizanLycan** [comment]
@develar It will happen to you to see something, I do not know if there will be the problem:

When I ran the given sentence, (npm rebuild ....): 

>Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
>  odbc.cpp
>  odbc_connection.cpp
>  odbc_statement.cpp
>  odbc_result.cpp
..\src\odbc_statement.cpp(219): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\USER\Desktop\APP-FOLDER\no
de_modules\odbc\build\odbc_bindings.vcxproj]
>  C:\USER\ .node-gyp\iojs-1.4.15\deps\v8\include\v8.h(3283): note: see declaration of 'v8::Function::NewInstance'
..\src\odbc_result.cpp(187): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\USER\Desktop\APP-FOLDER\node_modules
\odbc\build\odbc_bindings.vcxproj]
>  C:\USER\.node-gyp\iojs-1.4.15\deps\v8\include\v8.h(8334): note: see declaration of 'v8::Value::ToInt32'

Note that it runs directly with .node-gyp; While when running with electron builder (build ...), it runs from .electron-gyp \ .node-gyp

**Comment by LizanLycan** [comment]
Well, I find a solution. I copy the `C:\USER\.node-gyp\iojs-1.4.15\` folder content in the `C:\USER\.electron-gyp\.node-gyp\iojs-1.4.15\`  folder, and that's it!!
