### ISSUE TITLE
After building macOS app, an unexpected connection occur to files.lifehacklabs.org

### ISSUE THREAD

**Issue by danielfebrero** [electron-userland/electron-builder#1431]
* **Version**: 16.6.1
* **Target**: macOS

Hello, when building app with electron-builder, my Little Snitch (network monitor) detect an outgoing connection to files.lifehacklabs.org when opening my app.
When building with electron-packager (so another module), I do not have this kind of problem.
Is it a normal behaviour ? What is the reason of this connection ?

![screen shot 2017-04-04 at 17 23 49](https://cloud.githubusercontent.com/assets/20900798/24664804/dd9c6770-195b-11e7-9fc8-583eaa0dd3a1.png)

Thank you for your help!

**Comment by develar** [comment]
electron-builder doesn't inject any additional node modules or files.

Please search string `files.lifehacklabs.org` in your project files.
