### ISSUE TITLE
Donation to electron-builder?

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#1433]
Hello, is there a way to donate to this project directly or from other platforms such as https://opencollective.com?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Donations

Also you can use https://gratipay.com/electron-builder/ 

Why do you prefer opencollective.com?

**Comment by akashnimare** [comment]
This project has helped me a lot in setting up  autoupdates, building various installers etc in all my electron apps. The support given by @develar is really appreciable ❤️.

**Comment by akashnimare** [comment]
Maybe because of the few points mentioned here -
https://github.com/gratipay/inside.gratipay.com/issues/458
https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac
https://medium.com/open-source-life/money-and-open-source-d44a1953749c

**Comment by develar** [comment]
@stefanjudis Could you please approve open collective access (https://help.github.com/articles/approving-third-party-applications-for-your-organization/)? read only access is required (to verity star count).

Yes — I am not going to move electron-builder to own org because I don't see any reason to do it.

**Comment by akashnimare** [comment]
Make sense!

**Comment by stefanjudis** [comment]
@develar Do you maybe have the repo where we had the org discussions? I'm tired of this setup here. :) Let's figure this out please.

**Comment by develar** [comment]
> he link to the issue where we had the org discussions

https://github.com/iffy/electron-updater-example/issues/8
