### ISSUE TITLE
Is it possible to specify a license for PKG similar to NSIS?

### ISSUE THREAD

**Issue by akorchev** [electron-userland/electron-builder#1434]
* **Version**: N/A

* **Target**: PKG

Is it possible to specify a license that the user has to accept when targeting PKG? The `license` option for NSIS does exactly the same.
According to [this](http://stackoverflow.com/questions/11953439/mac-how-to-add-a-license-txt-to-a-pkg-built-with-productbuild-using-component) SO answer it should be easy to set via distribution.xml. I've found [this line](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/targets/pkg.ts#L34) but I don't know what creates the `distribution.xml` file and whether it is possible to edit it or specify a custom one.

**Comment by develar** [comment]
Exactly because of this our pkg target implementation uses XML.

We do `synthesize`, but we don't modify it.

Would you like to prepare a PR?

**Comment by develar** [comment]
BTW, why you want pkg instead of dmg?

**Comment by akorchev** [comment]
> BTW, why you want pkg instead of dmg?

Because I want the user to accept the EULA first :) So far I think only PKG supports that. 

> Would you like to prepare a PR?

Sure. Where is `distribution.xml` created?

**Comment by develar** [comment]
> So far I think only PKG supports that.

**Comment by akorchev** [comment]
Thanks! I found out [this SO answer](http://stackoverflow.com/questions/8970981/attach-license-file-to-dmg-under-osx) which works fine for me. Feel free to close.

**Comment by develar** [comment]
Feel free to open issue for DMG.
