### ISSUE TITLE
Version number directory kept in new versions of electron-builder

### ISSUE THREAD

**Issue by nunziotocci** [electron-userland/electron-builder#1435]
* **Version**:  16.6.1

* **Target**: NSIS

When installing an electron app that is build with electron-builder 16.16.1, if there is an older version of the app installed that was built with electron-builder 7.10, it keeps the version number directory.

Example:
If you install [Postage 3.2.3](https://github.com/workflowproducts/postage/releases/tag/eV3.2.3), then you build a new installer with electron-builder 16.6.1, then run that, it will install into a version number directory.

**Comment by nunziotocci** [comment]
Still broken in 17.0.1:
![capture](https://cloud.githubusercontent.com/assets/7560749/25099145/bb22fd8e-2370-11e7-9d3a-cc1884474158.PNG)

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

It doesn't led to any user issue.
