### ISSUE TITLE
Build system app for mac os

### ISSUE THREAD

**Issue by jkanche** [electron-userland/electron-builder#1436]
* **Version**: 16.6.2

* **Target**: mac, dmg

I am building an app and would like to install it system wide (copy binary to /usr/local/bin). What should I do If I want to package my app into a system wide app ? Is there documentation anywhere that lets me do this ?

**Comment by develar** [comment]
Or copy executable on first run, or use pkg target. Currently, you cannot change default installation path, but you can use after script.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1396
