### ISSUE TITLE
Can't codesign

### ISSUE THREAD

**Issue by s2young** [electron-userland/electron-builder#1441]
* **16.7.1**: 

* **mas**: 

I have been through all the code-signing issues and tried everything I know to try but I continue to get the error:  Identity name "[NAME]" is specified, but no valid identity with this name in the keychain

Following are the certs found running the 'security find-identity -v' command:

 ......
 11) 5BFFD281CC10B48FE57028F5E5A200C28DDBDACA "3rd Party Mac Developer Application: MedCenterDisplay LLC (UNBZ95H8G9)"
 12) 451290B195B537EA016FA9287D3E4BC7B5E57D14 "3rd Party Mac Developer Installer: MedCenterDisplay LLC (UNBZ95H8G9)"
 13) 8DFF38599E8864EB6354BF9393F8CED8836FD48D "Mac Developer: Stuart Young (QQW2H24ZW9)"
 14) BB9608419766D3002EAEB092EE2E6CBE0AD14068 "Mac Developer: Stuart Young (75KJW6BC4H)"
....

I have tried setting mas.identity to the following values:
3rd Party Mac Developer Installer: MedCenterDisplay LLC (UNBZ95H8G9)
3rd Party Mac Developer Application: MedCenterDisplay LLC (UNBZ95H8G9)
MedCenterDisplay LLC (UNBZ95H8G9)
MedCenterDisplay LLC
UNBZ95H8G9

Nothing works.  Your help would be GREATLY appreciated.  Thanks!

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by develar** [comment]
On local machine please try to not set  `identity`.

**Comment by s2young** [comment]
Yes, on local machine it works but uses my personal identity. I'm trying to build for the store.

**Comment by develar** [comment]
> it works but uses my personal identity. I'm trying to build for the store.

Please attach terminal output. In your "'security find-identity -v' command:" I see the only 3rd Party Mac Developer Application / 3rd Party Mac Developer Installer pair and so, don't understand "it works but uses my personal identity"

**Comment by s2young** [comment]
It uses the 'Mac Developer: Stuart Young' identity.  The warning tells me this is for development only. I'm trying to build for production, using the MedCenterDisplay identity.  Working on getting you log output now.

**Comment by s2young** [comment]
electron-builder Two package.json structure is used (dev: /Users/stuart/Development/apps/app-electron/package.json, app: /Users/stuart/Development/apps/app-electron/dist/ppmgr/package.json) +0ms
  electron-builder Effective config: {
  electron-builder   "appId": "com.patientpoint.viewer",
  electron-builder   "productName": "PatientPoint App Viewer",
  electron-builder   "copyright": "© 2017",
  electron-builder   "icon": "src/icons/ppmgr",
  electron-builder   "win": {
  electron-builder     "certificateFile": "src/mcd.pfx",
  electron-builder     "certificatePassword": "<stripped sensitive data>"
  electron-builder   },
  electron-builder   "mas": {
  electron-builder     "entitlements": "dist/ppmgr/entitlements.plist"
  electron-builder   },
  electron-builder   "mac": {
  electron-builder     "target": "pkg",
  electron-builder     "identity": "MedCenterDisplay LLC (UNBZ95H8G9)",
  electron-builder     "bundleVersion": "000",
  electron-builder     "category": "public.app-category.business"
  electron-builder   },
  electron-builder   "directories": {
  electron-builder     "app": "./dist/ppmgr"
  electron-builder   }
  electron-builder } +2ms
Installing app dependencies for arch x64 to /Users/stuart/Development/apps/app-electron/dist/ppmgr
  electron-builder Spawning npm install --production --cache-min 999999999 +42ms
ppmgr@1.0.0 /Users/stuart/Development/apps/app-electron/dist/ppmgr
├─┬ archiver@1.1.0 
│ ├─┬ archiver-utils@1.3.0 
│ │ ├── lazystream@1.0.0 
│ │ └── normalize-path@2.0.1 
│ ├── buffer-crc32@0.2.5 
│ ├─┬ glob@7.0.6 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.5 
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.1 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├── once@1.4.0 
│ │ └── path-is-absolute@1.0.0 
│ ├── lodash@4.15.0 
│ ├─┬ readable-stream@2.1.5 
│ │ ├── buffer-shims@1.0.0 
│ │ ├── core-util-is@1.0.2 
│ │ ├── isarray@1.0.0 
│ │ ├── process-nextick-args@1.0.7 
│ │ ├── string_decoder@0.10.31 
│ │ └── util-deprecate@1.0.2 
│ ├─┬ tar-stream@1.5.2 
│ │ ├─┬ end-of-stream@1.1.0 
│ │ │ └── once@1.3.3 
│ │ └── xtend@4.0.1 
│ └─┬ zip-stream@1.1.0 
│   └─┬ compress-commons@1.1.0 
│     └── crc32-stream@1.0.0 
├── async@2.0.1 
├─┬ firebase@3.6.9 
│ ├── base64-url@1.3.3 
│ ├── base64url@2.0.0 
│ ├── buffer-equal-constant-time@1.0.1 
│ ├── dom-storage@2.0.2 
│ ├── ecdsa-sig-formatter@1.0.7 
│ ├── faye-websocket@0.9.3 
│ ├── hoek@2.16.3 
│ ├── isemail@1.2.0 
│ ├── joi@6.10.1 
│ ├── jsonwebtoken@7.1.9 
│ ├── jwa@1.1.4 
│ ├── jws@3.1.4 
│ ├── lodash.once@4.1.1 
│ ├── moment@2.16.0 
│ ├── ms@0.7.2 
│ ├── rsvp@3.2.1 
│ ├── safe-buffer@5.0.1 
│ ├── topo@1.1.0 
│ ├── websocket-driver@0.6.5 
│ ├── websocket-extensions@0.1.1 
│ ├── xmlhttprequest@1.8.0 
│ └── xtend@4.0.1 
├─┬ fs-extra@2.0.0 
│ ├── graceful-fs@4.1.6 
│ └── jsonfile@2.4.0 
├─┬ htmlparser2@3.4.0 
│ ├── domelementtype@1.3.0 
│ ├── domhandler@2.2.1 
│ ├── domutils@1.3.0 
│ └─┬ readable-stream@1.1.14 
│   └── isarray@0.0.1 
├─┬ jimp@0.2.27 
│ ├── bignumber.js@2.4.0 
│ ├── bmp-js@0.0.1 
│ ├── es6-promise@3.2.1 
│ ├── exif-parser@0.1.9 
│ ├── file-type@3.8.0 
│ ├── jpeg-js@0.2.0 
│ ├─┬ load-bmfont@1.2.3 
│ │ ├── buffer-equal@0.0.1 
│ │ ├── parse-bmfont-ascii@1.0.6 
│ │ ├── parse-bmfont-binary@1.0.6 
│ │ ├─┬ parse-bmfont-xml@1.1.3 
│ │ │ ├── xml-parse-from-string@1.0.0 
│ │ │ └─┬ xml2js@0.4.17 
│ │ │   ├── sax@1.2.1 
│ │ │   └── xmlbuilder@4.2.1 
│ │ └─┬ xhr@2.2.2 
│ │   ├─┬ global@4.3.0 
│ │   │ ├─┬ min-document@2.18.1 
│ │   │ │ └── dom-walk@0.1.1 
│ │   │ └── process@0.5.2 
│ │   ├── is-function@1.0.1 
│ │   └─┬ parse-headers@2.0.1 
│ │     ├── for-each@0.3.2 
│ │     └── trim@0.0.1 
│ ├── mime@1.3.4 
│ ├── pixelmatch@4.0.2 
│ ├── pngjs@3.0.0 
│ ├── read-chunk@1.0.1 
│ ├─┬ stream-to-buffer@0.1.0 
│ │ └── stream-to@0.2.2 
│ ├── tinycolor2@1.4.1 
│ └─┬ url-regex@3.2.0 
│   └── ip-regex@1.0.3 
├─┬ machine-uuid@1.0.8 
│ └── node-uuid@1.4.1 
├── moment@2.14.1 
├── moment-timezone@0.5.5 
└─┬ request@2.74.0 
  ├── aws-sign2@0.6.0 
  ├── aws4@1.4.1 
  ├─┬ bl@1.1.2 
  │ └── readable-stream@2.0.6 
  ├── caseless@0.11.0 
  ├─┬ combined-stream@1.0.5 
  │ └── delayed-stream@1.0.0 
  ├── extend@3.0.0 
  ├── forever-agent@0.6.1 
  ├── form-data@1.0.1 
  ├─┬ har-validator@2.0.6 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├─┬ commander@2.9.0 
  │ │ └── graceful-readlink@1.0.1 
  │ ├─┬ is-my-json-valid@2.13.1 
  │ │ ├── generate-function@2.0.0 
  │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ └── is-property@1.0.2 
  │ │ └── jsonpointer@2.0.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├─┬ hawk@3.1.3 
  │ ├── boom@2.10.1 
  │ ├── cryptiles@2.0.5 
  │ ├── hoek@2.16.3 
  │ └── sntp@1.0.9 
  ├─┬ http-signature@1.1.1 
  │ ├── assert-plus@0.2.0 
  │ ├─┬ jsprim@1.3.0 
  │ │ ├── extsprintf@1.0.2 
  │ │ ├── json-schema@0.2.2 
  │ │ └── verror@1.3.6 
  │ └─┬ sshpk@1.10.0 
  │   ├── asn1@0.2.3 
  │   ├── assert-plus@1.0.0 
  │   ├─┬ bcrypt-pbkdf@1.0.0 
  │   │ └── tweetnacl@0.14.3 
  │   ├─┬ dashdash@1.14.0 
  │   │ └── assert-plus@1.0.0 
  │   ├── ecc-jsbn@0.1.1 
  │   ├─┬ getpass@0.1.6 
  │   │ └── assert-plus@1.0.0 
  │   ├── jodid25519@1.0.2 
  │   ├── jsbn@0.1.0 
  │   └── tweetnacl@0.13.3 
  ├── is-typedarray@1.0.0 
  ├── isstream@0.1.2 
  ├── json-stringify-safe@5.0.1 
  ├─┬ mime-types@2.1.11 
  │ └── mime-db@1.23.0 
  ├── node-uuid@1.4.7 
  ├── oauth-sign@0.8.2 
  ├── qs@6.2.1 
  ├── stringstream@0.0.5 
  ├── tough-cookie@2.3.1 
  └── tunnel-agent@0.4.3 

  electron-builder npm (6654) exited with code 0 +11s
Packaging for darwin x64 using electron 1.6.2 to dist/mac
  electron-builder Spawning /Users/stuart/Development/apps/app-electron/node_modules/7zip-bin-mac/7za x -bd /Users/stuart/.electron/electron-v1.6.2-darwin-x64.zip -o/Users/stuart/Development/apps/app-electron/dist/mac +1s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 44691942 bytes (43 MiB)

Extracting archive: /Users/stuart/.electron/electron-v1.6.2-darwin-x64.zip
--
Path = /Users/stuart/.electron/electron-v1.6.2-darwin-x64.zip
Type = zip
Physical Size = 44691942

Everything is Ok

Folders: 143
Files: 180
Size:       115338982
Compressed: 44691942
  electron-builder /Users/stuart/Development/apps/app-electron/node_modules/7zip-bin-mac/7za (6662) exited with code 0 +3s
  electron-builder Dev or extraneous dependencies: ../../../electron-builder.yml, ../../../electron-builder.json, ../../../electron-builder.json5 +1ms
  electron-builder Executing security find-identity -v +4s
  electron-builder Executing security find-identity -v -p codesigning +14ms
  1) 5941A1587CDE0F550BBAD2F91347D1413776BB7A "iPhone Distribution: MedCenterDisplay LLC (UNBZ95H8G9)"
  2) C6FC96F6763DD67FF755CCC21E01C1B69F7DF9A8 "iPhone Distribution: Northwestern University (E74ZKF37E6)"
  3) 5BFFD281CC10B48FE57028F5E5A200C28DDBDACA "3rd Party Mac Developer Application: MedCenterDisplay LLC (UNBZ95H8G9)"
  4) 8DFF38599E8864EB6354BF9393F8CED8836FD48D "Mac Developer: Stuart Young (QQW2H24ZW9)"
  5) BB9608419766D3002EAEB092EE2E6CBE0AD14068 "Mac Developer: Stuart Young (75KJW6BC4H)"
  6) D0569ACC3CC1B8211D18FEB18CCE93136F8AC59A "iPhone Distribution: InPocket, LLC (GKNH3EZZBJ)"
  7) 4108F0CEECCEA615F2C9559317274095ADAA79FF "iPhone Developer: Stuart Young (75KJW6BC4H)"
  8) A43B1AA6E9E10978EB619538283A3D62BA2CAEC8 "iPhone Distribution: PATIENTPOINT NETWORK SOLUTIONS, LLC (QA59E2543A)"
     8 valid identities found

  1) 55F4074FDD6C8E91B2000E52B18250D201158DF5 "Apple Push Services: com.2ndvote.iosapp"
  2) A04ABFB680962100446FF0FBEA1CAFFB4C2C0C1F "Apple Push Services: com.medcenterdisplay.carsource"
  3) C1DE97BA16DC756A09719390ABF2739CDF91DF81 "Apple Push Services: com.medcenterdisplay.donelsonanimal"
  4) 5941A1587CDE0F550BBAD2F91347D1413776BB7A "iPhone Distribution: MedCenterDisplay LLC (UNBZ95H8G9)"
  5) C9FE646C7C8BFE8029BD50901F5E0D641CA9EA24 "Apple Push Services: com.medcenterdisplay.mpsseminars"
  6) CA1A58E4503901819AF2564B76269605B12422B9 "Apple Push Services: com.medcenterdisplay.smb-dcmetro"
  7) CB517D0170F84F7C843B6D42A61E9B1A2171B871 "Apple Push Services: com.medcenterdisplay.smb001"
  8) 5D6F6A6B035C2E435CA2FE954195B3BBF70BB585 "Apple Push Services: com.medcenterdisplay.swedish"
  9) C6FC96F6763DD67FF755CCC21E01C1B69F7DF9A8 "iPhone Distribution: Northwestern University (E74ZKF37E6)"
 10) D9F926938FA02BAAAB2209F15880E07A59B26BCD "Apple Push Services: com.medcenterdisplay.smb-greatam"
 11) 5BFFD281CC10B48FE57028F5E5A200C28DDBDACA "3rd Party Mac Developer Application: MedCenterDisplay LLC (UNBZ95H8G9)"
 12) 451290B195B537EA016FA9287D3E4BC7B5E57D14 "3rd Party Mac Developer Installer: MedCenterDisplay LLC (UNBZ95H8G9)"
 13) 8DFF38599E8864EB6354BF9393F8CED8836FD48D "Mac Developer: Stuart Young (QQW2H24ZW9)"
 14) BB9608419766D3002EAEB092EE2E6CBE0AD14068 "Mac Developer: Stuart Young (75KJW6BC4H)"
 15) D0569ACC3CC1B8211D18FEB18CCE93136F8AC59A "iPhone Distribution: InPocket, LLC (GKNH3EZZBJ)"
 16) 4108F0CEECCEA615F2C9559317274095ADAA79FF "iPhone Developer: Stuart Young (75KJW6BC4H)"
 17) A43B1AA6E9E10978EB619538283A3D62BA2CAEC8 "iPhone Distribution: PATIENTPOINT NETWORK SOLUTIONS, LLC (QA59E2543A)"
     17 valid identities found

Error: Identity name "MedCenterDisplay LLC (UNBZ95H8G9)" is specified, but no valid identity with this name in the keychain
    at /Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/macPackager.ts:148:17
    at next (native)
From previous event:
    at MacPackager.sign (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/out/macPackager.js:276:11)
    at /Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/macPackager.ts:82:26
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at /Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/macPackager.ts:82:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/out/macPackager.js:181:11)
    at /Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/packager.ts:257:24
    at next (native)
    at xfs.stat (/Users/stuart/Development/apps/app-electron/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/stuart/Development/apps/app-electron/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:117:15)
From previous event:
    at Packager.doBuild (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/out/packager.js:379:11)
    at /Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/packager.ts:170:52
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Packager.build (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/out/packager.js:274:11)
    at Object.<anonymous> (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/src/builder.ts:198:33)
    at next (native)
From previous event:
    at Object.build (/Users/stuart/Development/apps/app-electron/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/stuart/Development/apps/app-electron/Gruntfile.js:448:11)
    at Object.thisTask.fn (/Users/stuart/Development/apps/app-electron/node_modules/grunt/lib/grunt/task.js:73:16)
    at Object.<anonymous> (/Users/stuart/Development/apps/app-electron/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/stuart/Development/apps/app-electron/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/stuart/Development/apps/app-electron/node_modules/grunt/lib/util/task.js:293:12)
    at /Users/stuart/Development/apps/app-electron/node_modules/grunt/lib/util/task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
