### ISSUE TITLE
NSIS LangString "MUI_TEXT_INSTALLING_TITLE" is not set

### ISSUE THREAD

**Issue by mediaslav** [electron-userland/electron-builder#1442]
* **Version**: 
16.7.1

* **Target**: 
NSIS

Appveyor builds started failing:

> Processing config: C:\Users\appveyor\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.10\nsisconf.nsh
> Processing script file: "<stdin>" (ACP)
> Processed 1 file, 10 command line commands, writing output (x86-ansi):
> warning: LangString "MUI_TEXT_INSTALLING_TITLE" is not set in language table of language 2070
> Note: you may have one or two (large) stale temporary file(s) left in your temporary directory (Generally this only happens on Windows 9x).
> Error output:
> Error: warning treated as error

 full log here: http://bit.ly/2palvPL

However building on local PC is ok

v16.6.2 works ok @ appveyor

**Comment by develar** [comment]
And appveyor doesn't allow to you to remove caches...

**Comment by develar** [comment]
Works for me — tests on all CI servers and sample app. Soon new version will be published, may be it will help.

**Comment by kossolax** [comment]
I just had same issue with version 16.8.2

I removed %appdata%/electron-builder directory, but it doesn't fixe my issue.

Any other file to remove?

Thanks for help,

**Comment by develar** [comment]
@kossolax remove local node_modules and install again.

**Comment by kossolax** [comment]
So, removed:

%appdata%/electron-builder
%appdata%/npm-cache
%appdata%/../Local/Temp/npm-*
%appdata%/../Local/Temp/electron-*
./node_modules


 My electron-builder isn't installed globaly. 


 After a npm install, same issue.

**Comment by develar** [comment]
@kossolax Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by kossolax** [comment]
$env:DEBUG="electron-builder"
npm run release > log.log 2> err.log


[log.txt](https://github.com/electron-userland/electron-builder/files/912773/log.txt)
[err.txt](https://github.com/electron-userland/electron-builder/files/912772/err.txt)

Thanks for helping,

**Comment by develar** [comment]
@kossolax Bingo! `"unicode": false,` Please try to remove this option. Are you sure that you want to disable unicode?

**Comment by kossolax** [comment]
Oh ! It was disabled because of MS-defender bugs.

 I removed the options, same issue. 

So I removed %appdata%/electron-builder again with unicode enabled, and now it's running !

 Thanks 😄

**Comment by aziks** [comment]
Hi @develar !! 

I'm trying to build an installer with my own NSIS script (wich worked in the past without electron-builder) and I got the error:

warning 6040: LangString "MUI_TEXT_WELCOME_INFO_TITLE" is not set in language table of language 1066
Error: warning treated as error

I did everything that you say in your last messages (delete npm-cache, delete electron-builder, delete node_modules and force nsis:{ "unicode": true } in my package.json but I got the same error.

I have read that "MUI_TEXT_WELCOME_INFO_TITLE" is deprecated in NSIS and I don't know what can I do now, please help. I send you the full log from DEBUG=electron-builder. 

Thanks!!

[log.txt](https://github.com/electron-userland/electron-builder/files/3471726/log.txt)

**Comment by aziks** [comment]
I have also tried the option { "warningAsErrors": false } but it didnt work
