### ISSUE TITLE
Uncaught TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by blksheep93** [electron-userland/electron-builder#1443]
Been trying to figure this out for the past hour or so. All solutions pointed to a versioning problem, so I updated everything and it still persists. Would love to be able to make http calls,

Electron v1.6.2
Node v6.10.2
npm v4.4.4

What I've done:

- npm cache clean

- Moved electron to global and deleted all node_managers in folders levels up from app.

- Updated electron ,node, and npm

- Required current version of electron in dev dependancies/

**main.js file**
```
const electron = **require('electron')**
// Module to control application life.
const app = **electron.app**
// Module to create native browser window.
const BrowserWindow = **electron.BrowserWindow**
```

Offending code.

```
const request = net.request({
		method: 'GET',
		protocol: 'http:',
		hostname: 'link',
		path: form_string
	});
```

**Comment by develar** [comment]
`electron.net` instead of just `net`?

**Comment by blksheep93** [comment]
The net part issn't the problem, the request part is. 

Solution tested, added changed to electron.net.request, problem persists.

**Comment by develar** [comment]
Does it work before package?

**Comment by blksheep93** [comment]
Not sure what exactly you mean by "package", but Electron has worked fin until I tried using request.

The full code in the file

function login(){
	var username = document.getElementById('username').value;
	var password = document.getElementById('password').value;
	//Dubtel_ajax(link', 'login_response', 'login_response');
	var test = httpGet('link');
	console.log(test);


	var form_string = null;
    form_string= "/username="+ username + "&password=" + password;
  
    const {net} = require('electron');
	const request = electron.net.request({
		method: 'GET',
		protocol: 'http:',
		hostname: 'link',
		path: form_string
	});
	console.log("request: " + request);

	request.on('response', (response) => {
	 console.log(`STATUS: ${response.statusCode}`);
	  response.on('error', (error) => {
	    console.log(`ERROR: ${JSON.stringify(error)}`)
	  })
	});

	request.on('login', (authInfo, callback) =>{
		//callback('username', 'password')
	});

	request.end();
};

**Comment by develar** [comment]
Sorry, This issue is not related to electron-builder — please post issue to generic electron forum. As your app doesn't work before packaging.
