### ISSUE TITLE
ERROR when building NSIS installer:

### ISSUE THREAD

**Issue by outhmanetoudaoui** [electron-userland/electron-builder#1444]

**Comment by outhmanetoudaoui** [comment]
![image](https://cloud.githubusercontent.com/assets/25899341/24823758/866501ca-1c02-11e7-81cf-75ccd8aea822.png)

**Comment by develar** [comment]
How many memory do you have?

**Comment by outhmanetoudaoui** [comment]
I have 8Go free in my disk

**Comment by outhmanetoudaoui** [comment]
For my project I have 600Mo when I use electron-builder I receive this error but when I follow the same process on another project size 100Mo everything works well

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by outhmanetoudaoui** [comment]
when i run electron-builder with DEBUG "set DEBUG=electron-builder && npm run  release
![sans titre](https://cloud.githubusercontent.com/assets/25899341/24830386/573cdb74-1c85-11e7-9a97-1ab958cbf15d.png)
" i see this:

**Comment by develar** [comment]
Sorry, on Windows you need to use `set DEBUG=electron-builder` and only then do build.

**Comment by outhmanetoudaoui** [comment]
The same problem when i do set DEBUG=electron-builder and I run build

**Comment by develar** [comment]
How big is your win-unpacked dir? Do you use latest electron-builder?

**Comment by outhmanetoudaoui** [comment]
the win-unpakced have 269Mo and I use latest electron-builder
