### ISSUE TITLE
Disable code sign of app

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#1446]
I'm building an unofficial desktop client of telegram and I don't want to sign it. How do I achieve that?

**Comment by develar** [comment]
Set env `CSC_IDENTITY_AUTO_DISCOVERY` to `false`

**Comment by develar** [comment]
Also you can set `identity` to `null` (https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-identity)

**Comment by akashnimare** [comment]
`identity: null` fixed it. Thanks 👍

**Comment by ccnokes** [comment]
This seems to be broken in 17.3.1. Not a big deal, but just so you know.

**Comment by pronebird** [comment]
I put `identity: null` in my YML with no luck
