### ISSUE TITLE
NSIS Build Error

### ISSUE THREAD

**Issue by Dear-Min** [electron-userland/electron-builder#1447]
No native production dependencies
Packaging for win32 ia32 using electron 1.6.2 to dist\win-ia32-unpacked
Building NSIS installer
  Packaging NSIS installer for arch ia32
Error: C:\Users\Dear.min\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.10\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=NovaClient"
Command line defined: "APP_GUID=101cdda1-fd1f-5ae4-b2c7-447e7b7e5f74"
Command line defined: "PRODUCT_NAME=Nova Client"
Command line defined: "PRODUCT_FILENAME=Nova Client"
Command line defined: "APP_FILENAME=NovaClient"
Command line defined: "APP_DESCRIPTION=Dawn of Change Lobby Client"
Command line defined: "VERSION=0.17.2"
Command line defined: "COMPANY_NAME=DearMin"
Command line defined: "PROJECT_DIR=C:\Users\Dear.min\Desktop\Dev\dist"
Command line defined: "BUILD_RESOURCES_DIR=C:\Users\Dear.min\Desktop\Dev\dist\build"
Command line defined: "APP_PRODUCT_FILENAME=Nova Client"
Command line defined: "MUI_ICON=C:\Users\Dear.min\Desktop\Dev\dist\build\launcher.ico"
Command line defined: "MUI_UNICON=C:\Users\Dear.min\Desktop\Dev\dist\build\launcher.ico"
Command line defined: "APP_32=C:\Users\Dear.min\Desktop\Dev\dist\dist\NovaClient-0.17.2-ia32.nsis.7z"
Command line defined: "APP_32_NAME=NovaClient-0.17.2-ia32.nsis.7z"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "MULTI_LANGUAGE_INSTALLER"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=C:\Users\Dear.min\AppData\Local\Temp\electron-builder-EVGA9m\0-1-uninstaller.exe"
Processing config: C:\Users\Dear.min\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.10\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
Bad text encoding: <stdin>:6
Error in script "<stdin>" on line 6 -- aborting creation process

NSIS script:
!addincludedir "C:\Users\Dear.min\AppData\Roaming\npm\node_modules\electron-builder\templates\nsis\include"
!addplugindir /x86-unicode "C:\Users\Dear.min\AppData\Local\electron-builder\cache\nsis-resources\nsis-resources-3.0.0\plugins\x86-unicode"
!addplugindir /x86-unicode "C:\Users\Dear.min\Desktop\Dev\dist\build\x86-unicode"

LangString win7Required 1033 "Windows 7 and above is required"
LangString win7Required 1049 "Требуется Windows 7 и выше"
LangString win7Required 1031 "Windows 7 and above is required"
LangString win7Required 1036 "Windows 7 and above is required"
LangString win7Required 3082 "Windows 7 and above is required"
LangString win7Required 2052 "Windows 7 and above is required"
LangString win7Required 1028 "Windows 7 and above is required"
LangString win7Required 1041 "Windows 7 and above is required"
LangString win7Required 1040 "Windows 7 and above is required"
LangString win7Required 1043 "Windows 7 and above is required"
LangString win7Required 1045 "Windows 7 and above is required"
LangString win7Required 1058 "Windows 7 and above is required"
LangString win7Required 1029 "Windows 7 and above is required"
LangString win7Required 1053 "Windows 7 and above is required"
LangString win7Required 1044 "Windows 7 and above is required"
LangString win7Required 1030 "Windows 7 and above is required"
LangString win7Required 2070 "Windows 7 and above is required"
LangString x64WinRequired 1033 "64-bit Windows is required"
LangString x64WinRequired 1049 "Требуется Windows 64-bit"
LangString x64WinRequired 1031 "64-bit Windows is required"
LangString x64WinRequired 1036 "64-bit Windows is required"
LangString x64WinRequired 3082 "64-bit Windows is required"
LangString x64WinRequired 2052 "64-bit Windows is required"
LangString x64WinRequired 1028 "64-bit Windows is required"
LangString x64WinRequired 1041 "64-bit Windows is required"
LangString x64WinRequired 1040 "64-bit Windows is required"
LangString x64WinRequired 1043 "64-bit Windows is required"
LangString x64WinRequired 1045 "64-bit Windows is required"
LangString x64WinRequired 1058 "64-bit Windows is required"
LangString x64WinRequired 1029 "64-bit Windows is required"
LangString x64WinRequired 1053 "64-bit Windows is required"
LangString x64WinRequired 1044 "64-bit Windows is required"
LangString x64WinRequired 1030 "64-bit Windows is required"
LangString x64WinRequired 2070 "64-bit Windows is required"
LangString appRunning 1033 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1049 "Приложение ${PRODUCT_NAME} уже запущено.$\r$\nНажмите OK для закрытия."
LangString appRunning 1031 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1036 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 3082 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 2052 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1028 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1041 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1040 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1043 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1045 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1058 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1029 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1053 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1044 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 1030 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString appRunning 2070 "${PRODUCT_NAME} is running.$\r$\nClick OK to close it."
LangString chooseInstallationOptions 1033 "Choose Installation Options"
LangString chooseInstallationOptions 1049 "Выберите опции установки"
LangString chooseInstallationOptions 1031 "Choose Installation Options"
LangString chooseInstallationOptions 1036 "Choose Installation Options"
LangString chooseInstallationOptions 3082 "Choose Installation Options"
LangString chooseInstallationOptions 2052 "Choose Installation Options"
LangString chooseInstallationOptions 1028 "Choose Installation Options"
LangString chooseInstallationOptions 1041 "Choose Installation Options"
LangString chooseInstallationOptions 1040 "Choose Installation Options"
LangString chooseInstallationOptions 1043 "Choose Installation Options"
LangString chooseInstallationOptions 1045 "Choose Installation Options"
LangString chooseInstallationOptions 1058 "Choose Installation Options"
LangString chooseInstallationOptions 1029 "Choose Installation Options"
LangString chooseInstallationOptions 1053 "Choose Installation Options"
LangString chooseInstallationOptions 1044 "Choose Installation Options"
LangString chooseInstallationOptions 1030 "Choose Installation Options"
LangString chooseInstallationOptions 2070 "Choose Installation Options"
LangString chooseUninstallationOptions 1033 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1049 "Выберите опции удаления"
LangString chooseUninstallationOptions 1031 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1036 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 3082 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 2052 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1028 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1041 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1040 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1043 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1045 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1058 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1029 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1053 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1044 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 1030 "Choose Uninstallation Options"
LangString chooseUninstallationOptions 2070 "Choose Uninstallation Options"
LangString freshInstallForAll 1033 "Fresh install for all users."
LangString freshInstallForAll 1049 "Новая установка для всех пользователей."
LangString freshInstallForAll 1031 "Fresh install for all users."
LangString freshInstallForAll 1036 "Fresh install for all users."
LangString freshInstallForAll 3082 "Fresh install for all users."
LangString freshInstallForAll 2052 "Fresh install for all users."
LangString freshInstallForAll 1028 "Fresh install for all users."
LangString freshInstallForAll 1041 "Fresh install for all users."
LangString freshInstallForAll 1040 "Fresh install for all users."
LangString freshInstallForAll 1043 "Fresh install for all users."
LangString freshInstallForAll 1045 "Fresh install for all users."
LangString freshInstallForAll 1058 "Fresh install for all users."
LangString freshInstallForAll 1029 "Fresh install for all users."
LangString freshInstallForAll 1053 "Fresh install for all users."
LangString freshInstallForAll 1044 "Fresh install for all users."
LangString freshInstallForAll 1030 "Fresh install for all users."
LangString freshInstallForAll 2070 "Fresh install for all users."
LangString freshInstallForCurrent 1033 "Fresh install for current user only."
LangString freshInstallForCurrent 1049 "Новая установка только для текущего пользо вателя."
LangString freshInstallForCurrent 1031 "Fresh install for current user only."
LangString freshInstallForCurrent 1036 "Fresh install for current user only."
LangString freshInstallForCurrent 3082 "Fresh install for current user only."
LangString freshInstallForCurrent 2052 "Fresh install for current user only."
LangString freshInstallForCurrent 1028 "Fresh install for current user only."
LangString freshInstallForCurrent 1041 "Fresh install for current user only."
LangString freshInstallForCurrent 1040 "Fresh install for current user only."
LangString freshInstallForCurrent 1043 "Fresh install for current user only."
LangString freshInstallForCurrent 1045 "Fresh install for current user only."
LangString freshInstallForCurrent 1058 "Fresh install for current user only."
LangString freshInstallForCurrent 1029 "Fresh install for current user only."
LangString freshInstallForCurrent 1053 "Fresh install for current user only."
LangString freshInstallForCurrent 1044 "Fresh install for current user only."
LangString freshInstallForCurrent 1030 "Fresh install for current user only."
LangString freshInstallForCurrent 2070 "Fresh install for current user only."
LangString onlyForMe 1033 "Only for &me"
LangString onlyForMe 1049 "Только для &меня"
LangString onlyForMe 1031 "Only for &me"
LangString onlyForMe 1036 "Only for &me"
LangString onlyForMe 3082 "Only for &me"
LangString onlyForMe 2052 "Only for &me"
LangString onlyForMe 1028 "Only for &me"
LangString onlyForMe 1041 "Only for &me"
LangString onlyForMe 1040 "Only for &me"
LangString onlyForMe 1043 "Only for &me"
LangString onlyForMe 1045 "Only for &me"
LangString onlyForMe 1058 "Only for &me"
LangString onlyForMe 1029 "Only for &me"
LangString onlyForMe 1053 "Only for &me"
LangString onlyForMe 1044 "Only for &me"
LangString onlyForMe 1030 "Only for &me"
LangString onlyForMe 2070 "Only for &me"
LangString forAll 1033 "Anyone who uses this computer (&all users)"
LangString forAll 1049 "Для &всех пользователей данного компьютера"
LangString forAll 1031 "Anyone who uses this computer (&all users)"
LangString forAll 1036 "Anyone who uses this computer (&all users)"
LangString forAll 3082 "Anyone who uses this computer (&all users)"
LangString forAll 2052 "Anyone who uses this computer (&all users)"
LangString forAll 1028 "Anyone who uses this computer (&all users)"
LangString forAll 1041 "Anyone who uses this computer (&all users)"
LangString forAll 1040 "Anyone who uses this computer (&all users)"
LangString forAll 1043 "Anyone who uses this computer (&all users)"
LangString forAll 1045 "Anyone who uses this computer (&all users)"
LangString forAll 1058 "Anyone who uses this computer (&all users)"
LangString forAll 1029 "Anyone who uses this computer (&all users)"
LangString forAll 1053 "Anyone who uses this computer (&all users)"
LangString forAll 1044 "Anyone who uses this computer (&all users)"
LangString forAll 1030 "Anyone who uses this computer (&all users)"
LangString forAll 2070 "Anyone who uses this computer (&all users)"

Var startMenuLink
Var desktopLink

!include "common.nsh"
!include "MUI2.nsh"
!include "multiUser.nsh"
!include "allowOnlyOneInstallerInstance.nsh"

!ifdef INSTALL_MODE_PER_ALL_USERS
  !ifdef BUILD_UNINSTALLER
    RequestExecutionLevel user
  !else
    RequestExecutionLevel admin
  !endif
!else
  RequestExecutionLevel user
!endif

!ifdef ONE_CLICK
  !include "oneClick.nsh"
!else
  !include "boringInstaller.nsh"
!endif

!ifmacrodef customHeader
  !insertmacro customHeader
!endif

!ifdef BUILD_UNINSTALLER
  SilentInstall silent
!else
  Var appExe
!endif

Function .onInit
  !ifmacrodef preInit
    !insertmacro preInit
  !endif
  !ifdef BUILD_UNINSTALLER
    WriteUninstaller "${UNINSTALLER_OUT_FILE}"
    !insertmacro quitSuccess
  !else
    !insertmacro check64BitAndSetRegView

    !ifdef ONE_CLICK
      !insertmacro ALLOW_ONLY_ONE_INSTALLER_INSTANCE
    !else
      ${IfNot} ${UAC_IsInnerInstance}
        !insertmacro ALLOW_ONLY_ONE_INSTALLER_INSTANCE
      ${EndIf}
    !endif

    !insertmacro initMultiUser

    !ifmacrodef customInit
      !insertmacro customInit
    !endif
  !endif
FunctionEnd

!ifndef BUILD_UNINSTALLER
  !include "installUtil.nsh"
!endif

Section "install"
  !ifndef BUILD_UNINSTALLER
    !include "installSection.nsh"
  !endif
SectionEnd

!ifdef BUILD_UNINSTALLER
  !include "uninstaller.nsh"
!endif

**Comment by develar** [comment]
Do you use 16.8.0?

**Comment by Dear-Min** [comment]
@develar I used 16.7.1

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output. I want to see your config.

**Comment by Dear-Min** [comment]
[log.txt](https://github.com/electron-userland/electron-builder/files/908377/log.txt)

Here it is.

**Comment by develar** [comment]
@Dear-Min Do you have `.yarnclean` file?

**Comment by Dear-Min** [comment]
@develar no.

**Comment by develar** [comment]
Please try 16.8.2

**Comment by Dear-Min** [comment]
Resolved, I appreciate for your help :)
