### ISSUE TITLE
Add preinst script for .deb target

### ISSUE THREAD

**Issue by MaksymMPanchyshyn** [electron-userland/electron-builder#1448]
* **Version**: 16.8.0
* **Target**:  Linux

Hi everyone, I am trying to build my electron app in .deb for linux, and I want to include license agreement question during installation, as I know this can be implemented using `preinst` script, I can add `postinst` using electron-builder (see [#795](https://github.com/electron-userland/electron-builder/issues/795)), but I can't find such feature for `preinst`. 

Is there any others ways to implement this or I can forget about `preinst` for now? :)

**Comment by develar** [comment]
Yeah, we have `after`, but not `before`.

You can try to set `before-install` using advanced hidden `fpm` option:

```
{
  "linux": {
    "fpm": ["before-install": "The path (relative to project dir) to a script to be run before package installation"]
  }
}
```

**Comment by MaksymMPanchyshyn** [comment]
OK, I'm tried to do so, but there is a syntax error, I tried something like this 
```
{
  "linux": {
    "fpm": ["The path (relative to project dir) to a script to be run before package installation"]
  }
}
```
Because I can't set array like in your example. This adds `preinst` script in .deb package but it doesn't executes (script is in DEBIAN directory of .deb package), for now I keep on source code research. Maybe I will find some way to implement this. 

Besides, any help are welcome :)

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by raffis** [comment]
see https://github.com/electron-userland/electron-builder/pull/2392
