### ISSUE TITLE
ENOENT for AppImage\xorriso

### ISSUE THREAD

**Issue by KPrabs106** [electron-userland/electron-builder#1449]
* **Version**: 13.11.1

* **Target**: Linux ARMv7l 

I'm trying to package for Linux, but it fails

>Skip app dependencies rebuild because platform is different
Packaging for linux armv7l using electron 1.6.6 to release\linux-armv7l-unpacked
Downloading tmp-19372-0-electron-v1.6.6-linux-armv7l.zip
[============================================>] 100.0% of 42.58 MB (6.08 MB/s)
Building AppImage for arch armv7l
Error: Exit code: ENOENT. spawn C:\Users\Kartik\AppData\Local\electron-builder\cache\AppImage\AppImage-09-07-16-linux\xorriso ENOENT

When I navigate to the directory, the path is valid and the file does exist.

**Comment by KPrabs106** [comment]
The above is when I run it on my Windows machine. When I try to run it on my Linux ARM, I get the following similar error:
>Unhandled rejection Error: spawn /home/pi/Documents/Electron Projects/Application/node_modules/7zip-bin-linux/arm/7za ENOENT

And this directory does not exist

**Comment by develar** [comment]
To build Linux on Windows — please use Docker https://github.com/electron-userland/electron-builder/wiki/Docker

**Comment by develar** [comment]
>  I try to run it on my Linux ARM

Yes, we don't provide 7zip for arm, I hope docker solution will help you to build on windows.
