### ISSUE TITLE
Remove example-app from sources

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#145]
Size of `example-app` is 315MB. 315MB binary files. And git doesn't support binaries properly — once it was committed, [no way to remove](https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/). 

I don't see any reason to store dist output under the version control. 

Even, even if it is really needed, [LFS](https://git-lfs.github.com) or separate repo could be used.

PS. Travis doesn't support caches on OS X.

**Comment by stefanjudis** [comment]
These were stored to check easily with `npm run test-build` is the commands succeed.

But I see the point.
