### ISSUE TITLE
Error: *_delta.nupkg don't created when i use electron builder and remoteReleases

### ISSUE THREAD

**Issue by outhmanetoudaoui** [electron-userland/electron-builder#1451]
*_delta.nupkg don't created when i use electron builder and remoteReleases.
see error in screenshot
![sans titre](https://cloud.githubusercontent.com/assets/25899341/24853282/d641dcde-1dda-11e7-94d3-f14475792090.png)

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

Or just use NSIS.

**Comment by VerteDinde** [comment]
@outhmanetoudaoui What is your remoteReleases url set to?
