### ISSUE TITLE
Symbol information

### ISSUE THREAD

**Issue by snene** [electron-userland/electron-builder#1454]
I am using electron-builder to generate the executable for Mac and Windows platforms. I want to get symbol information for the executable. This symbol information is needed to get readable information out of the crash reports that are sent using Electron supported crash reporter.

Can anyone please help with the ways to get this symbol information when using electron-builder?

**Comment by develar** [comment]
We don't remove symbol information for native modules. So, your question is not clear for me.

**Comment by snene** [comment]
Thanks for the reply! Let me provide some more information. We have an Electron based app that we package using electron-builder for mac and windows platforms. 

We also use crash reporter that is supported by Electron. In order to look at the minidumps sent by the crash reporter, we need to generate symbol information for the executables to be placed on the breakpad server.

When I try to extract symbol information from the exe for windows, symupload utility(provided by breakpad) fails to read the symbol information from the file.

So my question is how do I get symbol information that I can use with the mini breakpad server. Please let me know if I am not clear and you have further questions.

**Comment by develar** [comment]
it is better to ask this question in the general electron community.

I am not expert here, but what I think — electron-builder uses provided exe from electron dist. Only file properties (icon, meta info) and code signing are added. So, you just need to grab symbols from official dist — e.g. if you use https://github.com/electron/electron/releases/tag/v1.6.6 and win x64, you need to grab electron-v1.6.6-win32-x64-symbols.zip

**Comment by snene** [comment]
Thanks @develar !
