### ISSUE TITLE
Add ability to hide dock icon immediately

### ISSUE THREAD

**Issue by leo** [electron-userland/electron-builder#1456]
Electron has a native method that allows you to hide the dock icon, but it will pop up at the startup anyway and only hide later. In turn, electron-builder should support [this](https://github.com/electron/electron/issues/422#issuecomment-279257496).

**Comment by develar** [comment]
Please use https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-extendInfo to add any custom Info.plist entries.
e.g. set `extendInfo` to `{"LSUIElement": 1}`

**Comment by leo** [comment]
Sweet, thanks!

**Comment by sirbrillig** [comment]
Updated link for the `extendInfo` key: https://www.electron.build/configuration/mac.html#MacConfiguration-extendInfo
