### ISSUE TITLE
npm shrinkwrap requires electron-download@4.2.1 dependencies that doesn't exists

### ISSUE THREAD

**Issue by FromStoneage** [electron-userland/electron-builder#1458]
* **Version**: 16.8.2

* **Target**: any

running `npm install electron-builder@16.8.2 --save-dev` to upgrade existing electron-builder to the latest. I have a `shrinkwrap` hook that would also generate and update `npm-shrinkwrap.json`. After `npm-shrinkwrap.json` updated you will see the latest `electron-builder@16.8.2` would require `electron-download@4.2.1` dependencies which won't exists 

> "electron-builder": {
>       "version": "16.8.2",
>       "from": "electron-builder@16.8.2",
>       "dev": true,
>       "dependencies": {
>         "@electron-builder/electron-download": {
>           "version": "4.2.1",
>           "from": "@electron-builder/electron-download@4.2.1",
>           "dev": true
>         },

it cases our CI build to fail.

Looks like[ this commit](https://github.com/electron-userland/electron-builder/commit/5b8386088dadf4f947b20aca5edc08054dbadc5c) introduced the dependencies

**Comment by develar** [comment]
16.8.3

**Comment by develar** [comment]
BTW, use yarn :)

**Comment by FromStoneage** [comment]
Thanks, @develar good suggestion, just tried yarn its lighting fast compare to npm!
