### ISSUE TITLE
Asar is applied on current folder instead of project directory

### ISSUE THREAD

**Issue by taffeldt** [electron-userland/electron-builder#1459]
* **Version**: 16.8.2

No version of electron-updater is being used.

* **Target**: Windows x64 (probably happend with any)

I am using a setup with two _package.json_ files.
My build process compiles my Typescript files into Javascript and stores them in the _dist/_ folder. Inside this dist folder is the inner _package.json_ containing the electron builder configuration inside the build tag.
This build tag contains: `"build: { "appId": "com.example.project", "asar": false }`

The outer package.json calls the builder via a NPM command: `build --dir --projectDir dist`

The result is just as expected and works absolutely fine. If I set _asar_ to true, though, the command crashes telling me the index.js could not be found. Calling the command via console directly does the same thing if I call it from the main folder. Calling it from the subfolder dist instead without setting the _--projectDir_ flag works fine.

Executing _asar list_ on the broken .asar file shows all of my files from the main directory instead of the subfolder's entries.

**Comment by develar** [comment]
I hope it is obsolete now.
