### ISSUE TITLE
Enforce HTTPS For Bintray API Requests

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#1460]
* **Version**: 
14.4.0

Electron Updater: 1.7.1

* **Target**: 
Widows 64 Bit NSIS

I'm building for Bintray using the programmatic api as follows: 
```
{
    targets: Platform.WINDOWS.createTarget('nsis'),
    config: {
        directories: {
            app: 'electron',
            output: 'release'
        },
        publish: {
            provider: 'bintray',
            user: 'my@email',
            package: 'packagename',
            repo: 'reponame',
            owner: 'mybintrayownername'
        }
    }
};
```

Everything works perfectly, however we noticed that when the app begins checking for updates, it is issuing a non-HTTPS request to `http://api.bintray.com/packages/owner/repo/package/versions/_latest`. This is, of course redirected (301) to HTTPS on Bintray's end but it would be preferable for the initial request to be secure from the start. Is there a particular reason that this request would need to be HTTP? I'm more than willing to submit a PR if you can point me in the right direction!

Thanks,
Nader

**Comment by develar** [comment]
Thanks!

**Comment by develar** [comment]
Node http executor uses HTTPS agent. But! Electron http executor allows us to specify protocol in the options and by default uses `http`.  So, we must **always** specify `protocol`.
