### ISSUE TITLE
builder not working from a single directory project.

### ISSUE THREAD

**Issue by AshenPheonix** [electron-userland/electron-builder#1462]
I just updated electron-builder (15.6.2)
updater version 1.12 (though irrelevant)
Target Windows is showing issue at this point

When building straight (using build in the directory of the project) the builder does not go anywhere to get information beyond the basic HTML document, leaving nothing but a blank image on the project. If I use a packager on the project directory first, then build from that prepackage, it works fine.

Public project on github: https://github.com/AshenPheonix/CloudCoinWallet

**Comment by black-snow** [comment]
Do you still have issues? Please also try the lastest version for there have been a kajillion of fixes in the meantime ;)
