### ISSUE TITLE
Possible publish to Nexus OSS with generic provider?

### ISSUE THREAD

**Issue by coelho-extremosistemas** [electron-userland/electron-builder#1466]
* **Version**: "^16.8.3"

* **Target**:  "appImage"

I am try to publish my target in the nexus OSS 3 server. 
I create a npm-repo for this project, But I'm not sure if the generic provider can be used for this purpose.

**Comment by develar** [comment]
Auto update not supported on last nur for now.

If nexus oss can serve some dir — it is supported. 

But generic doesn't publish — it is used only for auto update information.
