### ISSUE TITLE
installer fails with jpg uncaught exeception

### ISSUE THREAD

**Issue by bwmmc** [electron-userland/electron-builder#1468]
* **electron-builder@16.6.0**: 

* **Windows 64 bit**: 

Hi,

I inherited some code from a previous developer, he had been using electron 1.4.2 but I'm 1.6.2.
I've attached my package file. (extension changed from json to txt).

There is also a apckage.json file in the apps folder, (attached as package-apps.txt)
[package-app.txt](https://github.com/electron-userland/electron-builder/files/920088/package-app.txt)

[package.txt](https://github.com/electron-userland/electron-builder/files/920053/package.txt)

The app seems to build fine:

```
C:\Electron\electron-menubar-mdcl>yarn run dist
yarn run v0.21.3
$ build
No native production dependencies
Packaging for win32 x64 using electron 1.6.2 to dist\win-unpacked
Building NSIS installerInline image 2
  Packaging NSIS installer for arch x64
Done in 59.20s.
C:\Electron\electron-menubar-mdcl>
```

The electron app runs fine in visual studio code but when I try to run the installer it fails with the following message:

![err](https://cloud.githubusercontent.com/assets/27008725/25011661/08843592-2066-11e7-92b2-29e80df4d9d9.png)

 I took a look at app.asar and possibly the body section could be the problem?

  img src="mdclidea.jpg" width="120" height="100" 
  
just because the jpg is listed but no real reason to think it would be a problem.

Is this a bug or have I messed up somewhere?

Thanks,
Seán

**Comment by develar** [comment]
Please try to disable asar — set asar to false. Does it help?
