### ISSUE TITLE
Platform support for OpenBSD?

### ISSUE THREAD

**Issue by 0x6373** [electron-userland/electron-builder#1470]
* **Version**: 1.6.2

* **Target**: OpenBSD

I was trying to get https://github.com/cryptocat/cryptocat running on an OpenBSD system.
After cloning the repository i ran "npm run setup", but this fails while installing electron@1.6.2 with the following error message:

```
> electron@1.6.2 postinstall /store/cryptocat/cryptocat/node_modules/electron
> node install.js

/store/cryptocat/cryptocat/node_modules/electron/install.js:61
      throw new Error('Electron builds are not available on platform: ' + platform)
      ^

Error: Electron builds are not available on platform: openbsd
    at getPlatformPath (/store/cryptocat/cryptocat/node_modules/electron/install.js:61:13)
    at Object.<anonymous> (/store/cryptocat/cryptocat/node_modules/electron/install.js:19:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
npm ERR! OpenBSD 6.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

What would be needed to add support for OpenBSD as a platform?
Is this something realistically possible?

**Comment by develar** [comment]
Could you please file issue to https://github.com/electron-userland/electron-prebuilt/issues?

**Comment by develar** [comment]
Please try to add openbsd to the switch statement in the install.js line 61 (locally in your node modules, see filepath in the stack trace). Does it work?

**Comment by 0x6373** [comment]
Hi, will do.

Since npm seems to cleanup after an error i just cloned electron-prebuilt, added the switch statement and did a ```npm install .``` (not sure if this is the right way to do).

This fails while trying to download the release from github (```Error: Failed to find Electron v1.6.6 for openbsd-x64 at https://github.com/electron/electron/releases/download/v1.6.6/electron-v1.6.6-openbsd-x64.zip```).
Is there a way to force npm to compile it locally instead of trying to fetch a pre-build release?

**Comment by MarshallOfSound** [comment]
@develar @0x6373 Electron does not currently support OpenBSD to FreeBSD so there aren't any precompiled releases available do download.  I highly doubt Electron will even build on those platforms as no code has been written to support them.

**Comment by develar** [comment]
@MarshallOfSound electron works on FreeBSD, so for me not clear why openbsd is not supported.

**Comment by MarshallOfSound** [comment]
@develar Is that just running the Linux build?  There's on open issue on electron re it not working so I'll be surprised if it's working all of a sudden :D

**Comment by black-snow** [comment]
Related: https://github.com/electron/electron/issues/3797
