### ISSUE TITLE
Rebuild stucks on Windows

### ISSUE THREAD

**Issue by quanglam2807** [electron-userland/electron-builder#1472]
* **Version**: 16.8.3

* **Target**: Windows (AppVeyor)

Rebuild stucks on Windows. But it works if I downgrade to 16.8.2. I think it could be related to #1450 

16.8.3: https://ci.appveyor.com/project/webcatalog/webcatalog/build/213
16.8.2: https://ci.appveyor.com/project/webcatalog/webcatalog/build/224

**Comment by quanglam2807** [comment]
@develar Still stucks :( https://ci.appveyor.com/project/webcatalog/webcatalog/build/234

**Comment by develar** [comment]
Have you update deps — https://github.com/webcatalog/webcatalog/blob/master/package.json#L49 ?

**Comment by quanglam2807** [comment]
@develar Wrong branch https://github.com/webcatalog/webcatalog/commit/c1209e4f2e4b57e213f0d9d57ae0ef961e322973

**Comment by develar** [comment]
Will be fixed in 17.0.1
