### ISSUE TITLE
NSIS: Cannot rename output?

### ISSUE THREAD

**Issue by Ratismal** [electron-userland/electron-builder#1473]
* **Version**: 11.7.0
* **Target**: NSIS (windows)

I've been having issues with file output names in combination with publishing. When I build, I get a file titled `ProductName Setup X.Y.Z.exe`. I then manually upload this file and the `latest.yml` as a github release, and the former turns into `ProductName.Setup.X.Y.Z.exe`. However, the githubArtifactName in the `latest.yml` file displays as `productname-Setup-X.Y.Z.exe`. This inconsistency causes auto-updates to break.

I want to upload my releases manually, but I don't want to have to modify my `latest.yml` every time. I read in this issue (https://github.com/electron-userland/electron-builder/issues/1390#issuecomment-288019166) that you cannot customize the githubArtifactName, so I figured the next best thing was to preformat the output file to be consistent with it. However, I can't seem to get any of my outputs to change.

Here's a snippet of my package.json:
```json
"build": {
  "artifactName": "adasdsadsdsa.${ext}",
  "nsis": {
      "artifactName": "Aasfdoasufbuasofusoa.${ext}"
   }
}
```
After hours of tinkering, I desperately filled in the artifactNames with keymashes, but I still get `ProductName Setup X.Y.Z.exe`. What am I doing wrong?

EDIT: Here's my [repository](https://github.com/Ratismal/DiscordMungeon) for reference.

**Comment by develar** [comment]
11.7 is old version. Please upgrade.

**Comment by Ratismal** [comment]
Ah, I was confused because 11.7.0 was the only thing npm would give me. I installed yarn and was able to update from there. Thank you for your help!
