### ISSUE TITLE
sqlite3 db-file is not found within app.asar

### ISSUE THREAD

**Issue by wende60** [electron-userland/electron-builder#1474]
happy easter,

Trying to create a build for mac osx, also working on a mac.
This is a part of my package.json to show what i use (based on electron-boilerplate-sqlite):

```
"dependencies": {
    "sqlite3": "^3.1.8"
  },
  "devDependencies": {
    "electron": "^1.6.2",
    "electron-builder": "^10.17.3"
  }
```

This is how i set the path to the db-file
**const dbFile = path.join(__dirname, '/appData.db');**

In the build the path is like this:
**/Users/[USERNAME]/[PATH-TO-CONTENT]/Contents/Resources/app.asar/app/appData.db**

... and I end up with an error:
SQLITE_CANTOPEN: unable to open database file

Now setting asar to false in the build-options. The path is now like this:
**/Users/[USERNAME]/[PATH-TO-CONTENT]/Contents/Resources/app/app/appData.db**

The app works fine.
How can i solve this problem?

regards, jo

**Comment by develar** [comment]
Please use extraResources https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraResources

**Comment by wende60** [comment]
thanks for the hint, but it seems to be not very handy... i end up here:
   
` "extraResources": ["appData.db"],`

and here:

const dbFile = path.join(__dirname, '/appData.db').**replace('/app.asar', '')**;

hmmm...

**Comment by develar** [comment]
Update: add examples to doc.

**Comment by piyush0** [comment]
@wende60 
```
"extraResources": ["appData.db"],
```

Did it work?

**Comment by wende60** [comment]
as mentioned above, it works only if i toggle the path like here:
`const dbFile = path.join(__dirname, '/appData.db').replace('/app.asar', '');`

I stopped testing here as I switched to a completely different setup using pouchdb...

cheers, jo

**Comment by develar** [comment]
Fix on electron side is required. https://www.npmjs.com/package/hazardous

**Comment by wende60** [comment]
cool, thanks :)

**Comment by debotos** [comment]
"extraResources": ["appData.db"],
and
const dbFile = path.join(__dirname, '/appData.db').replace('/app.asar', '');

Worked for me!!!

**Comment by salmidiv** [comment]
hi evryone 
i fix it with this 
in packege.json , in build section add: 
"extraResources": [
      "path/to/database.sqlite3"
    ],
in main.js add use:
const getDBPath = (filename) => {
    let base = app.getAppPath()
    if (app.isPackaged) {
        base = base.replace('\\app.asar', '')
    }
    return path.resolve(base, `path/to/${filename}.sqlite3`)
}

**Comment by avinashcoditation** [comment]
thanks buddy, worked for me

**Comment by zestones** [comment]
> hi evryone i fix it with this in packege.json , in build section add: "extraResources": [ "path/to/database.sqlite3" ], in main.js add use: const getDBPath = (filename) => { let base = app.getAppPath() if (app.isPackaged) { base = base.replace('\app.asar', '') } return path.resolve(base, `path/to/${filename}.sqlite3`) }

Worked for me too

**Comment by dxsuporte** [comment]
I used it that way, and everything worked out fine.

//##########################################

const Path = require('path')

const config = {
client: 'better-sqlite3',
connection: {
filename: Path.join(__dirname, __dirname.includes('app.asar') ? '../../database' : '/database'),
},
useNullAsDefault: true,
migrations: {
tableName: 'migrations',
directory: Path.join(__dirname, '/migrations'),
},
seeds: {
directory: Path.join(__dirname, '/seeds'),
},
}
module.exports = require('knex')(config)
