### ISSUE TITLE
When user attempts to open (NSIS) installer there is a crash.

### ISSUE THREAD

**Issue by justintocci** [electron-userland/electron-builder#1475]
* **Version**: 17.0.1

* **Target**: NSIS

# When user attempts to open installer there is a crash. 
The crash doesn't happen every time. I am on Win10 Anniversary Update. If you open with the mouse it crashes much more often than if you open from terminal. We are not associating extensions so unsure why System.dll is being copied to Temp folder.

Faulting application name: Postage Setup 3.2.5.exe, version: 3.2.5.0, time stamp: 0x584dca75
Faulting module name: System.dll, version: 0.0.0.0, time stamp: 0x584dca1a
Exception code: 0xc0000005
Fault offset: 0x00001581
Faulting process id: 0xf58
Faulting application start time: 0x01d2b7a635fa6056
Faulting application path: C:\Users\jtocci\Desktop\Postage Setup 3.2.5.exe
Faulting module path: C:\Users\jtocci\AppData\Local\Temp\nshECFA.tmp\System.dll
Report Id: 4097c144-caaa-4583-b065-a4e108e998a2
Faulting package full name: 
Faulting package-relative application ID:

**Comment by develar** [comment]
Is it possible to provide exe for test?

**Comment by justintocci** [comment]
Both these versions are affected:
V17.0.1
https://github.com/workflowproducts/postage/releases/download/eV3.2.6/Postage.Windows.3.2.6.zip

v16.8.?
https://github.com/workflowproducts/postage/releases/download/eV3.2.5/Postage.Windows.3.2.5.zip

**Comment by develar** [comment]
I hope obsolete now.

**Comment by ssboisen** [comment]
We just had a customer with this problem. As @justintocci suggested it's possible to actually install the application if you launch it from terminal. It's pretty strange.

**Comment by jstdoit** [comment]
Me too with the same problem, strange.

**Comment by ssboisen** [comment]
I wonder if this isn't related #2134 and perhaps fixed with the `19.33.0` release though it's strange that @justintocci had it in april?

**Comment by develar** [comment]
@ssboisen @jstdoit Thanks for reports, your issue was a regression and fixed in the 19.33.0
