### ISSUE TITLE
WIN_CSC_KEY_PASSWORD can't have spaces

### ISSUE THREAD

**Issue by jessep** [electron-userland/electron-builder#1476]
* **Version**: 17.0.1

* **Target**: windows

If I make  WIN_CSC_KEY_PASSWORD "electron-builder is cool", only "electron-builder" gets used as the password, so the build fails. Easy enough to fix by using a password without spaces, but wanted to file the bug as the password for a .p12 file can have spaces in it.

Didn't check if CSC_KEY_PASSWORD has the same issue.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
