### ISSUE TITLE
Made a script to use electron-simple-updater. Interest in PR?

### ISSUE THREAD

**Issue by jessep** [electron-userland/electron-builder#1477]
* **Version**: 17.0.1

* **Target**: mac/win/linux

I wanted a uniform API for auto-update, so I messed around with [electron-simple-updater](https://github.com/megahertz/electron-simple-updater). With a proper updates.json file, electron-simple-updater works nicely with the artifacts published on GH releases by electron-builder, but producing one by hand is annoying. So I wrote a script to produce and upload the updates.json file automatically for me.

In my opinion, the uniform updates api, and lack of need for a mac updates server are big wins. Would there be interest in switching to use electron-simple-updater? If so, happy to polish this and create a PR so people could have an easy way to use electron-simple-updater.

**Comment by develar** [comment]
Electron-simple-updater is merged into electron-updater. If you want to help, you can make PR to finish merge and support Linux. https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by jessep** [comment]
Oh, then why does it say on that wiki page that simplified auto update is
not supported on windows?

**Comment by develar** [comment]
> Simplified auto-update is not supported for Squirrel.Windows.

Supported for NSIS, default target for Windows.
