### ISSUE TITLE
Cannot make build for windows and mac on my linux machine

### ISSUE THREAD

**Issue by himanshu21092** [electron-userland/electron-builder#1479]
I am using 8.7.0 version of electron-builder. I am trying to build for MacOS and WIndows. I am very new to electron, I am facing different errors on both builds. And I am using Linux machine for build.

MacOS build error :- 
> build --mac

Skip app dependencies rebuild because platform is different
Packaging for darwin x64 using electron 1.6.2 to dist/mac
⚠️  Do not use "undefined" as appId, "com.electron.pos" will be used instead
⚠️  macOS application code signing is supported only on macOS, skipping.
Building DMG
Building macOS zip
Error: spawn hdiutil ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Windows build error :-
 > build --win

Skip app dependencies rebuild because platform is different
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /home/himanshu/Documents/electron/node_modules/electron-builder/src/packager.ts:300:13
    at throw (native)

Please help me resolve this. Thanks in advance.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build you need to install wine. And please use latest version.

**Comment by himanshu21092** [comment]
Hi, Thanks @develar for swift reply. I am able to build exe for windows but still not able to generate dmg for mac. Can you help me with that?

**Comment by develar** [comment]
You can build DMG only on macOs.

**Comment by himanshu21092** [comment]
Okay thanks so much.
