### ISSUE TITLE
Codesign: No such file or directory

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#1480]
* **Version**: 11.7.0

* **Target**: OSX

(This is really a comment so that others can find the solution if they are looking. Please close.) 

I was getting an error during the build process
```
codesign --verify --deep--verbose=2  --strict  /path/to/app/Test.app
...
/path/to/app/Test.app: No such file or directory
```
After a lot of debugging, it turns out this is a really terrible and cryptic codesign error message. 
If I change it to `--strict=symlinks`
I get better info: `/path/to/app/Test.app: invalid destination for symbolic link in bundle`
Sure enough, there was a symlink in my bundle pointing outside the bundle.

**Comment by develar** [comment]
Please try latest versions.

**Comment by meekaah** [comment]
this still happens with the LATEST version, electron-osx-sign implemented a new option "strict-verify" that you can set to false. we should be able to override / set this parameter. currently impossible. @develar

**Comment by iamsush** [comment]
@all, I had the same issue and was getting the same type of error. However, I was able to resolve it by removing all the symlinks from my concerned folder(I was using a 3rd party library, there were many symlinks).

Note: Remove all the symlinks found by
`find ./YOUR_CONCERNED_FOLDER/ -type l -ls`

I hope it would help someone!

**Comment by DominikLevitsky** [comment]
This is currently happening in electron-builder 22.8

**Comment by bedney** [comment]
I can confirm that this continues to happen on electron-builder 22.8. Since there is no way to pass a setting for `strict-verify` flag for the signing code, I had to hack (the output JS file) `macPackager.js` file, around line 341, to add the following to the list of options to the signing code:

`"strict-verify": false`

**Comment by john8329** [comment]
This happened to me when I tried switching from npm to yarn. Still don't know the exact reason, but I presume it has to do with some stuff in node_modules that gets copied at build time.
