### ISSUE TITLE
Create Appimage target with admin privilege

### ISSUE THREAD

**Issue by mahdifani14** [electron-userland/electron-builder#1481]
16.8.2

Linux

I would like to have execution file with admin privilege for all Linux distributions and the only option I found is Appimage but, you didn't consider admin right option for Appimage target. Could you help me and let me know if you are working on this feature or how can I overcome my issue?
Thanks,

**Comment by develar** [comment]
It is better to use sud when needed — https://github.com/automation-stack/electron-sudo

**Comment by mahdifani14** [comment]
@develar The problem of electron-sudo is the TTY ticket when you are running GUI application with graphical sudo tools.
In my application, I need admin privilege several times but not in a row, and due to active TTY feature, every time it's asking the user to insert the username and password which is not good. That's why I want to have the admin privilege at the starting point and wrap the whole application inside one TTY ticket.
Is it possible to create Appimage then modify the execution file permission to admin?

**Comment by dbolton** [comment]
@mahdifani14 Does the following help: https://stackoverflow.com/questions/37322862/check-if-electron-app-is-launched-with-admin-privileges-on-windows/46779649#46779649

**Comment by mahdifani14** [comment]
@dbolton Thanks for following up,
Actually, despite I'm not working on that project anymore but, this solution is applicable only for `win` not `linux` OSs which was my problem.
I think it could be a work around to have admin privilege wrapper for `linux` distributions.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
