### ISSUE TITLE
Builds failing on windows since 16.8.4

### ISSUE THREAD

**Issue by bcomnes** [electron-userland/electron-builder#1487]
* **Version**: 
16.8.4 - 17.0.1

* **Target**:  Windows  NSIS installer

Since 16.8.4, my windows builds have been failing with the following message:

```
Building NSIS installer
  Packaging NSIS installer for arch x64
Error: ENOENT: no such file or directory, open 'C:\projects\hyperamp\node_modules\electron-builder\templates\nsis\messages.yml'
```

Example failed build: https://ci.appveyor.com/project/bcomnes/hyperamp/build/1.0.31

I don't have access to a windows machine at the moment, but I'll try to dig into the issue more when I do.  Any ideas?

**Comment by develar** [comment]
Please remove `*.yml` from your `.yarnclean` file. https://github.com/hypermodules/hyperamp/blob/master/.yarnclean#L38

**Comment by bcomnes** [comment]
Derp.  Thank you!
