### ISSUE TITLE
Strictly confined snaps can't find xdg-open

### ISSUE THREAD

**Issue by flexiondotorg** [electron-userland/electron-builder#1489]
Which version of electron-builder are you using?
* **17.0.1**: 

What target are you building for?
* **Linux/snap**: 

When a snap is built and confinement is set to `strict` then the `command:` stanza needs to coerce PATH so the Electron app can find the `/usr/local/bin/xdg-open` shim included in the core snap. For example, the `command:` stanza should be generated to appear something like this:

    env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/opt/Example/example

**Comment by develar** [comment]
How can I reproduce and test?

**Comment by flexiondotorg** [comment]
@develar You'll need an Electron application which uses `execute.shell` to open URIs. Create a confined snap of that application, make sure `snapd-xdg-open` is installed on your Ubuntu 16.04 host. Attempting to open an URI via `execute.shell` won't do anything unless PATH has `/usr/local/bin` added.

[Rambox](https://github.com/saenzramiro/rambox) uses `electron-builder` and `execute.shell`, I'll add snap support and share a link to my branch in a bit.

**Comment by flexiondotorg** [comment]
Here is my simple fork of Rambox that adds snap support and suitable for testing:

  * https://github.com/flexiondotorg/rambox/tree/snap-support

**Comment by flexiondotorg** [comment]
> Snap is isolated due to security reasons, so, it seems, we should bundle it.

Just to be clear there is nothing to bundle. `xdg-open` is included in `usr/local/bin/` of the core runtime snaps use. So all that is required is coercing PATH as I described.

**Comment by saenzramiro** [comment]
Any news on this?

**Comment by develar** [comment]
Sorry, i don't have time. 
Moved to backlog to keep issue list clear.

**Comment by jleyva** [comment]
Hi,
have anyone tried if the workaround (change the command: in the .yam file to include /usr/local/bin/ in the PATH is working? We just tried without any result.
Can anyone share here a working .yaml file?
