### ISSUE TITLE
'node_modules' missing if 'platform.nodeName !== process.platform'

### ISSUE THREAD

**Issue by luclu** [electron-userland/electron-builder#1490]
**electron-builder: `17.0.1`**

When using the `isTwoPackageJsonProjectLayoutUsed` configuration building a platform different from the current OS will lead to a missing `node_module` folder (see [src/packager.ts#L180](https://github.com/electron-userland/electron-builder/blob/67ed60bafab49ad60db3a992930584db7729a882/src/packager.ts#L180)):
```javascript
else if (this.isTwoPackageJsonProjectLayoutUsed) {
      if (platform.nodeName === process.platform) {
        return installDependencies(this.appDir, this.electronVersion, arch, "rebuild")
      }
      else {
        log("Skip app dependencies rebuild because platform is different")
      }
}
```

Running the rebuild process once if `isTwoPackageJsonProjectLayoutUsed` and `npmRebuild` evaluate `true` would be a better way in my opinion.

As a temporary workaround we copy over the possible dirty working instance of the `node_modules` folder.

**Comment by develar** [comment]
Obsolete now.
