### ISSUE TITLE
dmg license

### ISSUE THREAD

**Issue by akorchev** [electron-userland/electron-builder#1491]
* **Version**: latest

* **Target**: any

Is there any event fired before uploading the assets? I am currently trying `afterPack` but it seems it is too early. I am adding a license agreement to a DMG in afterPack (using a Promise) but it looks as if afterPack doesn't wait and the DMG is uploaded before my script finishes and ends up corrupted. Here is my code:

```
afterPack() {
    return new Promise((resolve, reject) => {
         child_process.execFileSync(path.join(__dirname, 'licenseDMG.py'), [
             'DMG_FILE.dmg', 
             'eula.txt' 
         ])
         resolve()
     })
}
```

**Comment by develar** [comment]
License for DMG will be supported today.

**Comment by develar** [comment]
English supported. Russian and other non-ASCII langs — feel free to open issue if need.

**Comment by akorchev** [comment]
I tried 17.1.0 and got the following error:

```
: Exit code: 2. Command failed: Rez -a /var/folders/93/y7sx09v14ks_9syc38tzk2b40000gn/T/electron-builder-y3MwQL/0-3.r -o /Users/korchev/github/radzen-studio/dist/dist/Radzen-1.0.4.dmg
/var/folders/93/y7sx09v14ks_9syc38tzk2b40000gn/T/electron-builder-y3MwQL/0-3.r:282: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Hex string spans lines.
/var/folders/93/y7sx09v14ks_9syc38tzk2b40000gn/T/electron-builder-y3MwQL/0-3.r:283: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Invalid number.
/var/folders/93/y7sx09v14ks_9syc38tzk2b40000gn/T/electron-builder-y3MwQL/0-3.r:283: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Expected ';' or '}', but got 'Unknown token'
```

**Comment by develar** [comment]
@akorchev Is it possible to provide your license text?

**Comment by akorchev** [comment]
[license_en.txt](https://github.com/electron-userland/electron-builder/files/951838/license_en.txt)

**Comment by akorchev** [comment]
Here is the code I am currently using to add a license. There is some escaping going on: https://github.com/andreyvit/create-dmg/blob/master/support/dmg-license.py#L96
