### ISSUE TITLE
Module loader unable to find file when run from Installer (NSIS, Squirrel), works unpacked and in development

### ISSUE THREAD

**Issue by arekkas** [electron-userland/electron-builder#1494]
* **Version**: `^16.4.0`
* **Target**:
  * Windows NSIS x64
  * OSX bundle / dmg

When packaging the bundle of my app and installing it via an EV-signed NSIS l installer `build`, a file can not be found:

![grafik](https://cloud.githubusercontent.com/assets/3372410/25316760/faa918ca-286c-11e7-800b-5c98c795f3bb.png)

The same thing applies to OSX packaged app and dmg.

The weird thing is however, that if I run the unpacked app `./dist/win-unpacked` the error does not appear. I extracted the contents of `app.asar` and the file which is **said to be** not found **does** in fact exist:

![grafik](https://cloud.githubusercontent.com/assets/3372410/25316794/2e926e48-286d-11e7-958c-627407c4fc58.png)

I'm not doing anything fancy in my electron-builder.json:

```js
{
  "appId": "com.ory.sites.desktop",
  "copyright": "Copyright © 2017 ORY GmbH",
  "mac": {
    "category": "public.app-category.productivity"
  },
  "nsis": {
  },
  "win": {
    "certificateSubjectName": "ORY GmbH",
  },
  "publish": {
    "provider": "s3",
    "bucket": "xxxxxx",
    "path": "xxxxx"
  },
  "files": [
    "package.json",
    "transpiled/",
    "node_modules/"
  ],
}
```

You might ask yourself why there's a webpack error. I'm running a webpack server within my electron app because I am building a static site generator. The file which is not found is basically the entrypoint of said webpack server. It resides within the electron app.

As I said everything works with an unpacked app and in development, but once the app is packaged it no longer finds the file (although it's there).

Here is the same error on a packaged OSX file:

<img width="863" alt="bildschirmfoto 2017-04-23 um 21 52 36" src="https://cloud.githubusercontent.com/assets/3372410/25316908/307362c4-286f-11e7-89a2-a7e41ceb0b14.png">

I can send the app if it helps identifying the issue. Let me know.

**Comment by arekkas** [comment]
Here's the error on a OSX app with `asar: false`, also showing that the file actually exists:

<img width="845" alt="bildschirmfoto 2017-04-23 um 22 01 28" src="https://cloud.githubusercontent.com/assets/3372410/25316977/82a64cb8-2870-11e7-9f74-fb5222aba363.png">

**Comment by arekkas** [comment]
I disabled asar packaging on windows too, and now I'm seeing this error:

![grafik](https://cloud.githubusercontent.com/assets/3372410/25316925/b5e89816-286f-11e7-93a9-626ac89210ac.png)

**Comment by arekkas** [comment]
I was able to trace this back to webpack not being aple to find a node_module:

```
[2017-04-24 11:47:34:0147] [error] webpack-dev-middleware: A compile error occurred: ModuleNotFoundError: Module not found: Error: Can't resolve 'babel-loader' in 'C:\Users\foobar\AppData\Local\Programs\ory-sites-app'
    at factoryCallback (C:\Users\foobar\AppData\Local\Programs\ory-sites-app\resources\app.asar\node_modules\webpack\lib\Compilation.js:260:39)
    at factory (C:\Users\foobar\AppData\Local\Programs\ory-sites-app\resources\app.asar\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (C:\Users\foobar\AppData\Local\Programs\ory-sites-app\resources\app.asar\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel (C:\Users\foobar\AppData\Local\Programs\ory-sites-app\resources\app.asar\node_modules\webpack\lib\NormalModuleFactory.js:202:22)
```

**Comment by arekkas** [comment]
Ok, apparently webpack got confused due to the cwd being `/` when running as an installed app. I fixed that now and it works.

**Comment by fangxiang1** [comment]
@arekkas how to solve
