### ISSUE TITLE
No licenses present after build

### ISSUE THREAD

**Issue by JM-Mendez** [electron-userland/electron-builder#1495]
--Which version of electron-builder are you using?--
I've tried both 17.0.3 and 17.1.0.

--What target are you building for?--
Mac

-- Enter your issue details below this comment. --
When I open package contents after building, I'm missing the license file I included in the build directory, as well as the chromium license. I can copy over my licenses using extraFiles or extraResources. But aren't I required to have the chromium license?

I'm using webpack and electron-react-boilerplate as well. Here's my package.json config

```
"build": {
    "files": ["dist/", "node_modules/", "app.html", "main.js", "main.js.map"],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": ["nsis"]
    },
    "linux": {
      "target": ["deb", "AppImage"]
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  },
```
and this is my folder structure
```
app
resources
  |
  |-- license_en.txt
```

**Comment by develar** [comment]
license_en.txt will be used as DMG license. Do you mean that it should be included as file into the distribution?

Chromium license — it is ok.

**Comment by JM-Mendez** [comment]
I see. That license does show up when the DMG is mounted. I still don't get the LICENSES.chromium.html. But I found another of your posts from a couple years back saying the builder didn't add those anyways. So I'll just add those using the extraResources option I suppose and consider this resolved. Thanks for the quick reply.

**Comment by develar** [comment]
@JM-Mendez Decided that it is ok to not include `LICENSES.chromium.html` https://github.com/electron-userland/electron-builder/issues/916#issuecomment-260944707

**Comment by ngprasad** [comment]
@JM-Mendez What did you add to extraResources to make it work? I am trying to add LICENSES.chromium.html and added this:-
`extraResources: LICENSES.chromium.html` but it doesn't work.

**Comment by develar** [comment]
@ngprasad for what?

**Comment by JM-Mendez** [comment]
Without knowing your project structure, I'd guess that the license you're trying to add isn't at the root of the project. Extra resources are relative to the package.json location.

**Comment by ngprasad** [comment]
@develar I have noticed that LICENSES.chromium.html gets deleted immediately after the package is built. Is there a way to retain the LICENSES file content resources of the app? I am asking because ours is a commercial application and we want to make sure that there will not be any issue with licenses.

**Comment by ngprasad** [comment]
@JM-Mendez It gets created in package directory i.e. the output directory but even if I add that path to extraResources it doesn't work.

**Comment by JM-Mendez** [comment]
@ngprasad I just built a package, checked it's package content (I'm on mac), and it's in the resources folder. I put everything in a license folder at the root level, then added this to my package.json

```
"extraResources": [
      "./licenses"
    ],
```
Not sure why yours gets deleted, but you could try putting it inside a folder and see if that helps.
