### ISSUE TITLE
Is there a way to specify multiple package.json's?

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#1496]
A quick question in regard to trying to make a production and development build.

We would like to be able to have 2 installations on the computer. A production and a development build. It is quite annoying to have to keep uninstalling one or the other to test.

Since the information from package.json such as the `name`, `productName`, and `appId` etc are all used in the `build` block is there a way to specify multiple `build` blocks or something of the sort?

**Comment by develar** [comment]
Duplicates #1250

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390

**Comment by mastergberry** [comment]
Thanks as always :)
