### ISSUE TITLE
NSIS build - add welcome page

### ISSUE THREAD

**Issue by thavasukkannu** [electron-userland/electron-builder#1501]
Version: 17.0.3
Target: NSIS (windows)

Thanks for given NSIS features. 

I have taken the build, it's working good. When I install the .exe setup it starting with "choose install location" in the Windows Installer setup page. But my requirement is adding the "Welcome page" as the first page. 

![test](https://cloud.githubusercontent.com/assets/28038281/25420986/4a24e3cc-2a78-11e7-9936-2b64485ec358.png)

![welcome](https://cloud.githubusercontent.com/assets/28038281/25420994/53708256-2a78-11e7-848d-2201b613593d.png)

Is that possible with using Installer.nsh? or any other way to achieve this? please suggest.

**Comment by develar** [comment]
`MUI_PAGE_WELCOME` is not added by intention. Only for uninstaller — https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/nsis/boringInstaller.nsh#L51

For what do you need welcome page?

**Comment by thavasukkannu** [comment]
@develar Thanks for quick replay :) .

For greeting window page.

Actually I need to create a custom page before the installation page. Is it possible?
I would like to create same as below image.

![requirement](https://cloud.githubusercontent.com/assets/28038281/25424089/b3467b84-2a84-11e7-9b10-174d8b7f47bc.png)

**Comment by develar** [comment]
Well, if https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script will be not enough, you can fork project, modify as you need and send PR.

**Comment by thavasukkannu** [comment]
@develar  Ok thanks :) .

**Comment by Sivasss94** [comment]
Actually i just used electron builder (nsis target) to create a setup file for windows application, but i need to add another one installer page in the setup, so i can get the input (serverIP) from the end user and i can modify the api_url in app.asar file or asar unpacked main.js file. Is there any another way? I checked the Custom Installer script, but it is little confusing. So Please help me in this. And Thanks in advance.
