### ISSUE TITLE
Built app always uses default electron icon

### ISSUE THREAD

**Issue by adityavm** [electron-userland/electron-builder#1502]
* **Version**: 
17.1.1

* **Target**: 
Mac OSX

The built app doesn't get the icons included in the folder. It always uses the default electron icon.

Icon files in the build folder >
<img width="438" alt="screen shot 2017-04-26 at 12 54 59 pm" src="https://cloud.githubusercontent.com/assets/80849/25422773/9deb8554-2a7f-11e7-8249-f8bca6b6fbaa.png">

Icons not found >
<img width="487" alt="screen shot 2017-04-26 at 12 54 23 pm" src="https://cloud.githubusercontent.com/assets/80849/25422779/a6a52f06-2a7f-11e7-9547-9974277a0fdd.png">

**Comment by arekkas** [comment]
You need to put the icons in `build`, it's in the readme: https://github.com/electron-userland/electron-builder#quick-setup-guide

**Comment by adityavm** [comment]
@arekkas and I included a screenshot showing the icons in the build folder

**Comment by arekkas** [comment]
I don't see a folder labeled "dist" in there. It looks like you put the icons in the root directory of your project. Check this again:

![](https://cloud.githubusercontent.com/assets/80849/25422773/9deb8554-2a7f-11e7-8249-f8bca6b6fbaa.png)

**Comment by adityavm** [comment]
@arekkas I'm not sure if I'm misunderstanding, but in the screenshot, the prompt at the top shows that I'm in the `build` folder, and the fifth line shows the `dist` folder. 

The icons are in the root of the `build` folder as suggested in the readme.

**Comment by arekkas** [comment]
Why is the package.json and node_modules in your build directory? It seems like this is the root of your project.

**Comment by adityavm** [comment]
@arekkas so that the path is correct for app.js when running the app during development and after packaging the asar.

Do you think that's the issue? Should I try to place the icons inside a `build/build` folder?

**Comment by arekkas** [comment]
> Do you think that's the issue? Should I try to place the icons inside a build/build folder?

Yes

**Comment by adityavm** [comment]
@arekkas that worked. I had specified a `--projectDir` which I suppose caused the lookup to happen in the wrong path. Thank you.
