### ISSUE TITLE
dev-app-update.yml not found

### ISSUE THREAD

**Issue by zeevl** [electron-userland/electron-builder#1505]
* **Version**: 17.1.1
* **electron-updater version**: 1.14.2
* **Target**: MacOS

This is in relation to the recently-fixed https://github.com/electron-userland/electron-builder/issues/1254

Now, running `autoUpdater` using `electron path/to/app` results in 
```
autoUpdater { Error: ENOENT, dev-app-update.yml not found in /.../node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar
```

Is there something I should be doing to generate this file?

**Comment by develar** [comment]
If you want to use updater in a dev mode, you need to add this file manually.

**Comment by develar** [comment]
Please specify electron version.

**Comment by zeevl** [comment]
electron version 1.6.6

Is there a template of what this file should contain?   Not even sure where to find the generated app-update.yml..

**Comment by alexcroox** [comment]
I'm not sure where to manually add this file either...

`default_app.asar` is in a binary format so I can't amend anything inside of it

**Comment by sebn** [comment]
@zeevl I believe the generated file is `./dist/win-unpacked/resources/app-update.yml` for Windows, or `./dist/mac/MyApp.app/Contents/Resources/app-update.yml` for macOS. You can copy it to `app/dev-app-update.yml`.

**Comment by alexcroox** [comment]
@sebn Is this where you mean?

![ss](https://cl.ly/kOsx/Screen%20Shot%202017-05-11%20at%2014.12.19.png)

As this doesn't seem to work.

I could add it manually to `./dist/mac/MyApp.app/Contents/Resources/app-update.yml` but that directory gets emptied and re-generated with every build so this would only work for 1 release cycle and I'd have to repeat the action every time?

**Comment by sebn** [comment]
@alexcroox Maybe you're confusing development and production setup?

**Comment by alexcroox** [comment]
Yer I'm still confused unfortunately. I'm running `webpack-dev-server --hot --colors --config webpack.renderer.config.js --port ${config.port} --content-base app/dist`

The error I'm getting is `Error: ENOENT, dev-app-update.yml not found in /Users/alex/Projects/xxxx/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar`.

I'm still not sure where to manually copy `dev-app-update.yml`. I've added it to:

1. `/Users/alex/Projects/xxxx/node_modules/electron/dist/Electron.app/Contents/Resources`
2. `/Users/alex/Projects/xxxx/dist/mac/xxxxx.app/Contents/Resources`

Still the same error

**Comment by develar** [comment]
`dev-app-update.yml` is only and only for testing during development and unpacked. And it is advanced feature. Consider to test using packed app.

**Comment by alexcroox** [comment]
The work around for development has been

```
if (process.env.NODE_ENV === 'development')
    // Skip autoupdate check
  else
    autoUpdater.checkForUpdates()
```

**Comment by develar** [comment]
https://github.com/sindresorhus/electron-is-dev recommended.

**Comment by TimNZ** [comment]
@develar Mate...

The issue is you have a hard-wired check for dev-app-update.yml, already using the electron-is-dev module.
It is in AppUpdater.js:loadUpdateConfig()

It is using electron app.getAppPath() when dev mode is detected, which is generally going to point to default_app.asar when running 'electron' for dev.

This makes no sense as it can't be implemented as we can't place a file there.

So why have the code?

You are awesome for making electron-builder/electron-updater, but I find a lot of your dev decisions very baffling and frustrating when encountered, unlike any other popular open source package I've used.

Perhaps you should consider asking a couple of people to join a committee who bring a different perspective?  Happy to help, I have 20+ years of SD experience, a lot of architecture.

**Comment by TimNZ** [comment]
This referenced issue is breaking even production builds because I have 'electron' in my dev path which causes electron-is-dev to return true when it shouldn't.

https://github.com/sindresorhus/electron-is-dev/issues/4

**Comment by develar** [comment]
You should not use electron updater in the dev mode.

**Comment by alexcroox** [comment]
That makes it incredibly hard to develop an updating system/UI if you have to build every time you change a line of code relating to the update system UX...

**Comment by TimNZ** [comment]
I can understand it not being supported in dev mode, the update system must rely on an install having files in certain places.

**Comment by develar** [comment]
@alexcroox Please note — not "must", but "should". Want to test — no problem. Just create `dev-app-update.yml` with your own configuration to test :)

**Comment by develar** [comment]
@TimNZ On macOS your update will be successful only if app is signed, but place doesn't matter (so you can run it not only for /Applicaitons, but from dist folder also). So, no way to test update fully, but you can test "update system UX" using `dev-app-update.yml`.

**Comment by develar** [comment]
To make clear — we are not going to improve this aspect without properly formulated issue request. (Hint: JetBrains IDEs allows you to debug packed applications, even in the asar, in the same way as you debug your dev build). `dev-app-update.yml` is not created for you, it is your responsibility to create it according to your needs. If you think that it will be cool if electron-builder will have special command to generate such file or even somehow grab configuration on the fly from your electron-builder configuration — please file issue (and if you commercial company — you can even donate to make sure that feature will be implemented in a short term).

**Comment by develar** [comment]
@alexcroox If your issue is that dev file is not located correctly (The error I'm getting is Error: ENOENT, dev-app-update.yml not found in /Users/alex/Projects/xxxx/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar.), I will check it now.

**Comment by alexcroox** [comment]
@develar yer I added it to those 2 locations above but was still getting the error not found. Ran out of places to find that I might be able to place it

**Comment by alexanderwe** [comment]
Maybe this will help someone for solving this issue. For me it worked creating the `dev-app-update.yml` manually  in the top level of my electron app. I am using the two package.json way.

My directory structure then looks like this

```
.
├── app
│   ├── main
│   │   ├── main.js
│   │   └── update.js
│   ├── package.json
│   ├── renderer
│   │   ├── ...
│   │       └── main.jsx
│   └── yarn.lock
├── dev-app-update.yml
├── package.json
├── publish.sh
└── yarn.lock
```

And in `dev-app-update.yml` I inserted the following for using GitHub:

```
owner: yourGHName
repo: yourGHRepoName
provider: github
```

**Comment by JerryGoyal** [comment]
Hi, is the path issue fixed? for me `dev-app-update.yml` is still expecting to be at `...Contents/Resources/default_app.asar ` location which is invalid.
for me workaround for now: 
```
if (isDev) {
    autoUpdater.updateConfigPath = path.join(__dirname, 'app-update.yml');
}
```

**Comment by ysfjwd** [comment]
quick question, what is the format of the `dev-app-update.yml` file?

**Comment by alexanderwe** [comment]
In case you want to use GitHub as your "Update Server" the following format should work
```
owner: yourGitHubName
repo: yourRepositoryName
provider: github
```
At least this is what is working for me

**Comment by zhanyouwei** [comment]
@alexanderwe Hi
I did as you said. But, Get the following tips.

```
[11:11:37.156] [info] Checking for update
[11:11:37.156] [info] Checking for update...
[11:11:37.297] [info] Generated new staging user ID: xxx-xxx-xxxx
[11:11:37.348] [info] Update for version 1.6.2 is not available (latest version: 1.0.2, downgrade is disallowed.
[11:11:37.349] [info] Update not available.
```

**Comment by alexanderwe** [comment]
@zhanyouwei 
Did you made a release for the new version on your GitHub repo ?

**Comment by hatpick** [comment]
I get this on windows
```
ENOENT, dev-app-update.yml not found in [path]\node_modules\electron\dist\resources\default_app.asar
```

**Comment by jetlej** [comment]
When I run this locally with the fix above, it compares the latest release of my app to the version of electron rather than the app itself.

**Comment by Slapbox** [comment]
Anyone manage to get this working with Amazon S3? I've burned a day and a half on this seemingly simple task.

I get `null` as my result every time without fail in development.

I can't even understand where the `autoUpdater` is supposed to be checking for the `yml` file and whether it's doing that and failing to find it, if the configuration is wrong, etc. This is a complete black box besides digging through the source code yourself to understand what's going on.

I understand it's recommended to test this in a packaged app, but that's not really feasible in every situation. I've tried setting the updateConfigPath and a every other tip I've found online and in this thread, and always `null`, every single time, with no errors or warnings regarding `dev-app-update.yaml`

**Comment by Slapbox** [comment]
Hope this saves somebody a day.

In `development` env, **DO NOT USE** `checkForUpdatesAndNotify()` - You MUST USE `checkForUpdates()`

This little oversight cost me big time. I expected it would still check for updates, but it doesn't seem to from what I can tell.

I assume this is because this isn't _really_ a supported feature, there's no provided partial functionality for that function in development, seems to be the case. The promise always resolves with `null` from what I can tell.

All credit to @yeongjet - https://github.com/electron-userland/electron-builder/issues/3753

**Comment by nihalmpatel** [comment]
Creating a file dev-app-update.yml in root directory with following content fixed the problem for me of my generic server setup:

```
provider: generic
url: http://127.0.0.1:8080/releases
channel: latest
```

**Comment by aziks** [comment]
@nihalmpatel it worked like a charm!! thanks!!

**Comment by luoschool** [comment]
在根目录中创建具有以下内容的文件dev-app-update.yml可以解决我的通用服务器设置问题：
`provider: generic
url: http://127.0.0.1:8080/releases

**Comment by luoschool** [comment]
在根目录中创建具有以下内容的文件dev-app-update.yml可以解决我的通用服务器设置问题：
`provider: generic
url: http://127.0.0.1:8080/releases`
