### ISSUE TITLE
Support retina DMG background image

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#1506]
If I also have a `build/background@2x.png` background, `electron-builder` should use it as a retina background.

The `appdmg` module supports this: https://github.com/LinusU/node-appdmg#retina-background

**Comment by develar** [comment]
We decided that it is better to use tiff directly, so, please see http://stackoverflow.com/a/11204769/1910191 (link from https://github.com/electron-userland/electron-builder/wiki/Options#DmgOptions-background)

`tiffutil -cathidpicheck myimage.png myimage@2x.png -out myimage.tiff`

**Comment by sindresorhus** [comment]
Why make it harder than necessary though? `electron-builder` already handles a lot of manual steps. Also `appdmg` already supports this. I thought you were using it underneath. `@2x.png` is a very common pattern for this. I don't want to manually generate archaic TIFF files.

**Comment by develar** [comment]
Will be implemented.

**Comment by sondremare** [comment]
Any news on this?
