### ISSUE TITLE
how to link the forked electron-builder to my project?

### ISSUE THREAD

**Issue by sabariferin** [electron-userland/electron-builder#1507]
Version : Latest
Target : NSIS

@develar, I have forked the latest version of this project and changed the few of the codebase to support some additional features for NSIS. I need to test it locally whether the changed codes are working or not. How to integrate the forked project with my electron project? 
Please help.

**Comment by develar** [comment]
`NODE_PATH=/path/to/electron-builder/packages node/path/to/electron-builder/packages/electron-builder/out/cli/build-cli.js --mac dir` (working directory — your project directory)

replace here `/path/to/electron-builder` to path to electron-builder and `-mac dir` to your build args.
