### ISSUE TITLE
Build setup.exe from prepackaged app

### ISSUE THREAD

**Issue by Kylart** [electron-userland/electron-builder#1508]
Hello,

I have an already packaged App in a directory called App-win32-x64 for example (I used electron-packager to have this). I would like to build a setup.exe using this prepackaged app programmatically. 

Does anyone have a hint on how to do this ? A link with the right wiki page would be enough I think since I might have missed it in my research.

Thanks!

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format
