### ISSUE TITLE
empty latest-mac.json uploaded on S3 bucket

### ISSUE THREAD

**Issue by MatBenetti** [electron-userland/electron-builder#1513]
I'm using following packages:

* **electron-builder 17.1.1**

* **electron-updater 1.14.2**

I'm publishing onto s3 as provider and i've experienced upload of empty latest-mac.json file on to s3, while it's generated without problem on local.

Profile that problem it's little trickie.. i've notice that when i update "version" in package.json the file is uploaded correctly.

As i said, on the local "dist/" folder the "latest-mac.json" file is valid with content.

The application zip package is always uploaded without problem.

I'm using **electron-publisher-s3** version **17.0.3** 

This is package.json relevant rows:

```
"build": {
    "appId": "com.company.app",
    "publish": {
      "provider": "s3",
      "bucket": "com-company-app",
      "region": "eu-west-1"
    },
    "mac": {
      "target": "zip"
    },
    "protocols": [
      {
        "name": "com-company-app",
        "schemes": [
          "com-company-app"
        ]
      }
    ],
  },
```

![issue](https://cloud.githubusercontent.com/assets/385030/25530640/46f1174c-2c27-11e7-9929-f38cfc3405ef.png)
![screen shot 2017-04-28 at 15 27 25](https://cloud.githubusercontent.com/assets/385030/25530642/475a1a08-2c27-11e7-99cd-9d56b054b119.png)
![screen shot 2017-04-28 at 15 28 58](https://cloud.githubusercontent.com/assets/385030/25530693/74ebd614-2c27-11e7-918d-e551bf1d4020.png)

**Comment by boedy** [comment]
I'm having the same problem, but for windows latest.yml. For me the weird thing is it works on my local machine, but it fails on my CI server (Wercker). The application .exe uploads fast every time, but when it's time for the latest.yml to upload the process hangs for about 30 seconds. It then completes leaving an empty layest.yml (0 B) on S3. The CI does, just as @MatBenetti said, create the local latest.yml file.

I run the following command:
`build -p always --win --project ./www; sleep 10; cat dist/latest.yml`

Result:
```
Packaging for win32 x64 using electron 1.4.15 to ../dist/win-unpacked
Signing My app.exe (certificate file: "./windows_code_signing_cert.p12")
Building NSIS installer
  Packaging NSIS installer for arch x64
  Signing NSIS uninstaller (certificate file: "./windows_code_signing_cert.p12")
Signing My app Setup 1.0.2.exe (certificate file: "./windows_code_signing_cert.p12")
Publishing to S3 (bucket: my-s3-bucket)
Uploading My app Setup.exe to S3
Uploading latest.yml to S3
version: 1.0.2
releaseDate: '2017-05-04T22:37:31.701Z'
githubArtifactName: My app Setup.exe
path: My app Setup.exe
sha2: 09991253c332f414e1097474c04f46b8fb6a503fc985354960c408b3aba4a5c6
```
**packages**
"electron-builder": "^17.1.2",
"electron-publisher-s3": "^17.1.2",
"electron-updater": "^1.14.3",

**Comment by esamelson** [comment]
I'm having the same problem - the yml file sometimes fails to upload, and an empty copy is left on my server. It happens inconsistently when building from my local machine - appears to upload fine sometimes, but hangs and fails other times. There is never any problem with uploading the actual exe file. Also, there is no indication (other than the hang) from electron-builder that there is a failure; it eventually just returns, saying the upload is 100% complete.

I'm running `build --win --ia32 --x64 -p always`

**Comment by develar** [comment]
Duplicates #1582
