### ISSUE TITLE
Configuring autoUpdater and publishing artifacts to GitHub

### ISSUE THREAD

**Issue by benjam1n** [electron-userland/electron-builder#1514]
Hi there!

I'm super confused how to setup updater + publishing artifacts and I haven't been able to found a decent guide/tutorial - are there any? At least a sample app?

So I have private repo for my app's code, but I'd like to use a different (public) repo for my releases - that should be possible, right? Because if it was one the same private repo I'm not really sure how could updater access its releases.

My package.json build params:

```
"build": {
  "publish": [
    {
      "provider": "github"
    }
  ],
  "productName": "Devise",
  "appId": "com.devise.devise",
  "mac": {
    "category": "..."
  },
  "asar": true,
  "asarUnpack": [
    ...
  ],
  "dmg": {
    ...
  }
}
```

Build/dist actions work fine.  Files that are built:
* dist/Devise-1.0.0.dmg
* dist/Devise-1.0.0-mac.zip
* github/latest-mac.json
* mac/Devise.app are

**Comment by benjam1n** [comment]
Nevermind, https://github.com/megahertz/electron-simple-updater + https://github.com/megahertz/electron-simple-publisher is exactly what I need.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update
