### ISSUE TITLE
NSIS multi arch using native package dependencies that use cmake-js

### ISSUE THREAD

**Issue by tiangolo** [electron-userland/electron-builder#1516]
* **Version**: 17.1.1

**Electron-updater**: 1.11.0

* **Target**: Windows

I'm building an application that uses [`active-win`](https://github.com/sindresorhus/active-win). For Windows, it uses [`fastcall`](https://github.com/cmake-js/fastcall), which in turn uses [`cmake-js`](https://github.com/cmake-js/fastcall) (comparable with [`node-ffi`](https://github.com/node-ffi/node-ffi)).

Following [`cmake-js`' guide](https://github.com/cmake-js/cmake-js#electron) I added a section to my `package.json` to specify that I wanted `cmake-js` to build for electron, as: 

```json
...
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.6.7",
    "arch": "x64"
  }
...
```

That way, when installing a package that uses `cmake-js` it will compile it for electron using that architecture.

But I'm trying to use `electron-builder` multi-arch NSIS installer, and that uses  [`electron-gyp` to rebuild for each architecture](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/yarn.ts#L35). 

Is there a way to support dependency packages that use `cmake-js` using NSIS multi architecture?

What would be needed from the `cmake-js` side to support it here?

What would need to be done here to support it?

I also opened a corresponding issue in `cmake-js`: https://github.com/cmake-js/cmake-js/issues/83

**Comment by tiangolo** [comment]
@develar I'm planning on creating a PR to "add support" for `cmake-js` dependencies.

If I'm not wrong, it seems it would just be adding some `cmake-js` configs as environment variables in here: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/yarn.ts#L25

In any case, it wouldn't make `cmake-js` a dependency, it would only use it when needed. That would give automatic support for `cmake-js` modules in `electron-builder`.

Do you think that's something useful / acceptable for the project?

**Comment by develar** [comment]
> Do you think that's something useful / acceptable for the project?

It is useful, acceptable and wanted PR. Thanks for clear report and investigation.

**Comment by tiangolo** [comment]
Great!

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by tiangolo** [comment]
Cool. :ok_hand: 

I were unable to work on it as I don't have a feasible test case.

My use case was using fastcall in Windows 32 bits, but it seems that it is not that simple, or at least it doesn't work right away: https://github.com/cmake-js/fastcall/issues/17

I ended up migrating `active-win` back to `node-ffi` instead of `fastcall`.

**Comment by Jinex2012** [comment]
@tiangolo To fix this issue you have to dig into the node_module code itself.

see here:
https://github.com/chentsulin/electron-react-boilerplate/issues/646#issuecomment-270685328

**Comment by tiangolo** [comment]
Thanks @Jinex2012 , I had an idea on how to proceed, but I was trying to use some Windows APIs and `fastcall` doesn't support doing that. So I didn't have a way to actually test that it was working, or if it would...

It is now a feature request in `fastcall`: https://github.com/cmake-js/fastcall/issues/17
