### ISSUE TITLE
Start Menu Icon Remains As Default Icon

### ISSUE THREAD

**Issue by Gochida** [electron-userland/electron-builder#1518]
* **Version**: 17.1.1

Building an app for Windows.

I'm attempting to add an Icon to my electron app, and it appears to be used just fine in the application window's title bar, on the task bar, in the installer window... but when I go to launch the app via the start menu I see that the icon is the default Electron icon.
![icons](https://cloud.githubusercontent.com/assets/10173555/25549485/d9ce7e3e-2c26-11e7-858f-ff6ef4273294.png)

I've placed the icon in a folder labeled 'build', and placed that folder in the root folder of the project.

You can download the icon here: https://drive.google.com/open?id=0B72mAd2e8P24djdRY3RsY19uV28
These are the sizes in the icon:
16 x 16
24 x 24
32 x 32 
48 x 48
64 x 64
96 x 96 
128 x 128
192 x 192
256 x 256

**Comment by arekkas** [comment]
I have the same issue, but also in the taskbar and on the desktop!

**Comment by arekkas** [comment]
The installer itself looks correct: 
![grafik](https://cloud.githubusercontent.com/assets/3372410/25559150/1550f0bc-2d36-11e7-8b44-559efd7b4c28.png)

**Comment by arekkas** [comment]
Oh, I think in my case it's actually some windows cache or something

![grafik](https://cloud.githubusercontent.com/assets/3372410/25559500/a9774c32-2d3b-11e7-9bd6-ac703e131fa9.png)

**Comment by alexeyvax** [comment]
I have the same issue, on linux.

**Comment by alexeyvax** [comment]
It works to me (for Linux). I created folder "build" and added some icons and folder "icons" to it. Then I added some icons in folder "icons". Don't change the folders and icons name.
—  build
—— icons
——— 32x32.png
——— 32x32.png.ico
—— icon.icns
—— icon.ico
