### ISSUE TITLE
electron-updater v1.14.* throws cannot find module 'debug'

### ISSUE THREAD

**Issue by mzmiric5** [electron-userland/electron-builder#1521]
* **Version**: 17.1.1.

* **electron-updater version**: 1.14.*

* **Target**: Mac & Windows

Using ES5 import of electron-updater v 1.14.* causes the built applications to throw
```
Uncaught Exception:
Error: Cannot find module 'debug'
```
on launch. Using electron-updater v 1.13.* does not cause this issue.

**Comment by develar** [comment]
Please try 1.14.3

**Comment by barretodaniel** [comment]
I'm having the same issue with 1.14.3

**Comment by develar** [comment]
Is it possible to provide app for inspect / test?

**Comment by develar** [comment]
Error is clear.

**Comment by barretodaniel** [comment]
I'm reinstalling node_modules now to see if that clears it up.

**Comment by develar** [comment]
Fixed in electron-updater 1.14.4 Sorry for delay.

**Comment by barretodaniel** [comment]
Yep, I'm clear with the new version.
