### ISSUE TITLE
[electron-updater] proxy authentication

### ISSUE THREAD

**Issue by BurningEnlightenment** [electron-userland/electron-builder#1528]
* **Version**: latest

Hi,
currently it seems like the `login` events of the net.requests created in [`electronHttpExecutor`](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts) cannot be intercepted by the user which is obviously problematic if the app is used behind a proxy that requires authentication.
Would a PR to resolve this be accepted? If yes, do you have any design guidelines/ preferences?

**Comment by develar** [comment]
> Would a PR to resolve this be accepted?

Yes.

> If yes, do you have any design guidelines/ preferences?

I am not expert here and cannot advice. Maybe https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/PrivateGitHubProvider.ts approach — `session.fromPartition` will be useful.

**Comment by develar** [comment]
> if the app is used behind a proxy that requires authentication.

Is proxy configured in the system settings? Or windows does't support it? How does Google Chrome works for you?

**Comment by BurningEnlightenment** [comment]
> Is proxy configured in the system settings? Or windows does't support it? How does Google Chrome works for you?

We manually set the proxy settings for the default session using `setProxy()` and therefore also need a way to manually provide the credentials through the `login` event fired by the `ClientRequest` object.

**Comment by BurningEnlightenment** [comment]
closed by a892a5b
