### ISSUE TITLE
Question: What's the process like to migrate codesign certificate

### ISSUE THREAD

**Issue by steverandy** [electron-userland/electron-builder#1532]
I'm using electron-builder to sign an app for Mac and Windows. I would like to know if electron-builder supports codesign certificate migration. For example changing codesign certificate for organization name change. What's the process like and will the autoupdate still work?

**Comment by develar** [comment]
I am sorry, but I cannot advice. I am not expert in this area and I am not aware about it. If something will be required to be implemented on electron-builder side — feel free to reopen and ask.

**Comment by develar** [comment]
Auto update will work.

**Comment by Isahara86** [comment]
I have tried to sign install file and update file with different certificates. The auto update works only on windows on Mac you will get an error.

**Comment by Ajeey** [comment]
@Isahara86 Were you able to solve the mac error? What was the changes you did on windows to make it work?

**Comment by Slapbox** [comment]
@develar, I vaguely recall reading something about adding acceptable organization names for the auto-updater to accept codesigning certificates from. Am I remembering incorrectly?

I'm trying to move from an individual code signing certificate to a corporate one on OSX without users losing auto-update during/after the transition.
