### ISSUE TITLE
Why does electron-updater not create app-update.yml if mac publish options doesn't include "zip"?

### ISSUE THREAD

**Issue by mstralka** [electron-userland/electron-builder#1533]
* **electron-1.6.8**: 
* **electron-builder-17.3.1**

* **mac**: 

I have been trying to use electron-updater, but I only wanted to publish the *DMG* file for mac. If I only publish the DMG file (excluding `zip` from the targets), the `app-update.yml` file is not created, and autoUpdater will not work. 

Reading the source code for `electron-builder/packages/electron-builder/src/publish/PublishManager.ts`, I see that if platform == mac and targets does not include "zip", then it silently returns before creating `app-update.yml`.
```js
      if (event.electronPlatformName === "darwin") {
        if (!event.targets.some(it => it.name === "zip")) {
          return
        }
      }
```

Why is the `zip` target required for autoUpdater to create the app-update.yml file?

**Comment by mstralka** [comment]
I figured it out - the autoUpdater downloads the zip file (not the DMG) so it doesn't make sense for app-update.yml to be created if the zip file is not created.

**Comment by develar** [comment]
Yes. It maybe will be changed in the future, but for now it is requirement of Squirrel.Mac.
