### ISSUE TITLE
NSIS - nested start menu folders

### ISSUE THREAD

**Issue by floi1** [electron-userland/electron-builder#1538]
* **Version**: 17.3.1
* **Target**:  windows

I noticed that I can't set a nested path for start menu shortcut of my application.
Even setting a string with "menuCategory" option into my package.json at project level it creates only a level.

While searching into your scripts I noticed that's because you use sanitize-filename package.
So, using a path string like "level1\\application\\" will result into a single level "level1application".

can you add the possibility to give a path with multiple levels?

![image](https://cloud.githubusercontent.com/assets/27846014/25911534/7cfeeb48-35b4-11e7-9dd1-09eb0d04de8d.png)

Setting "menuCategory" item like this the result will be:

![tmp](https://cloud.githubusercontent.com/assets/27846014/25911603/c5f2165e-35b4-11e7-9afe-0466418fb045.png)

Using a string with a backslash into json file

![image](https://cloud.githubusercontent.com/assets/27846014/25911825/86cc9a16-35b5-11e7-87cd-217d67ec4f5d.png)

Return me this

![tmp3](https://cloud.githubusercontent.com/assets/27846014/25911872/a8c27afa-35b5-11e7-8fc0-15062d73f968.png)

I want to create a folder tree like Microsoft apps

![tmp2](https://cloud.githubusercontent.com/assets/27846014/25911710/267b4888-35b5-11e7-807e-ac7612cb0189.png)

**Comment by javydreamercsw** [comment]
Is there documentation oh how to use this?
