### ISSUE TITLE
Git submodule package.json dependencies

### ISSUE THREAD

**Issue by Johnz86** [electron-userland/electron-builder#1539]
In our project we have multiple git submodules, which have their own package.json definition.
The main package.json has definition like this:
```package.json
  "dependencies": {
    "react": "15.4.2",
    "submodule_1": "client/submodule_1",
    "submodule_2": "client/submodule_2",
  },
```
The file structure of the project is something like this:
```
   root_project
   |-client
   |    |-submodule_1
   |    |   '--package.json
   |    '-submodule_2
   |        '--package.json
   '-package.json
```

So on npm install we have a all necessary modules downloaded.
The problem is that electron does not package the submodule dependencies to the final installer.
Is there a way to build the electron app with the dependencies from nested git submodules?

**Comment by develar** [comment]
How do you install sub node modules? Using Lerna or manually?

**Comment by develar** [comment]
Am I right — you somehow compile your project, and expect, that electron-builder will copy all node_modules directories plus your packages files?

**Comment by develar** [comment]
As workaround, please try to specify `node_modules` explicitly in the `files` (see https://github.com/electron-userland/electron-builder/wiki/Options#Config-files) (but I am not sure, also, dev deps will be not filtered).

**Comment by Johnz86** [comment]
The installation of dependencies is done with postinstall step:
```package.json
"scripts": {
      "postinstall": "npm install submodule_1 && npm install submodule_2",
},
```
The workaround is not very good, because it would be easier just to copy all dependencies from submodules to main package.json.
In that way I lose the flexibility of git submodules and shared code.

**Comment by develar** [comment]
Will be implemented.

**Comment by DutchKevv** [comment]
+1 same here

My situation:
1 root package.json that is being used when the packaged is being distributed through npm publish.
1 package.json in client folder for Client modules (Angular 4)
1 package.json in server folder for Server modules (Typescript etc)
1 package.json in electron folder (electron-builder etc)

My problem:
Only the server/node_modules needs to be copied (and does that), but now electron copies ALL server/node_modules and it doesn't prune the server/node_modules folder

https://github.com/electron-userland/electron-packager/issues/657#issuecomment-304726788

**Comment by develar** [comment]
Fixed, but only if you use default and recommended enabled ASAR packaging.

**Comment by bradydowling** [comment]
I'm having this issue with and without asar packaging. I'll dig into it more with asar enabled but @develar what do you mean by "use default"?

**Comment by develar** [comment]
@bradydowling My comment is not relevant anymore. Please file a new issue (thanks for project) to be not forgotten
