### ISSUE TITLE
Automatic unpack detection in scoped packages unpacks the entire scope

### ISSUE THREAD

**Issue by pmoleri** [electron-userland/electron-builder#1540]
* **Version**: 17.5.0
* **Target**: Windows

I have multiple packages under the same npm scope, say:
* `@example/foo` (with dlls)
* `@example/bar`

As result, all packages under `@example` get unpacked.
```
app.asar.unpacked/
    node_modules
        @example/
            foo/
            bar/
```
although `bar` shouldn't.

Running in debug mode:
`export DEBUG="electron-builder"; ./node_modules/.bin/build`,
it prints the following message:
```
electron-builder node_modules\@example is not packed into asar archive - contains executable code
```

**Comment by develar** [comment]
Confirmed.
