### ISSUE TITLE
Changed name of app, auto updates failing

### ISSUE THREAD

**Issue by alexcroox** [electron-userland/electron-builder#1544]
Building for OS X, hosted on github.

A few versions back I changed `productName` from `testTimer` to `Test Timer`.

I expected the auto update to fail for the next release given that the `testTimer.app` would become `Test Timer.app`. However, I'm now several updates deep since the name change and the autoupdater is still failing during `autoUpdater.quitAndInstall()` with:

```
Error: Error: ENOENT: no such file or directory, lstat '/Applications/testTimer.app'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
```

I'm guessing the old app name is cached somewhere, but not sure where, and how to update.

**Comment by thisismydesign** [comment]
@alexcroox how did you resolve this?

**Comment by thisismydesign** [comment]
In the end, we had no issue to change the name on Windows, other than having to reference the old appdata directory. Can't speak for mac.
