### ISSUE TITLE
Adding a license file for Mac .pkg target

### ISSUE THREAD

**Issue by gniezen** [electron-userland/electron-builder#1547]
* **Version**: 17.0.3

* **Target**: mac, pkg

It looks like it's possible to add a license file for Windows NSIS as well as Mac .dmg, but not for Mac .pkg target?

**Comment by genbandbrent** [comment]
any forecast for this feature?

**Comment by develar** [comment]
Only if will be donated.

**Comment by genbandbrent** [comment]
Thanks. How long would it take if a donation were made?

**Comment by develar** [comment]
@genbandbrent https://github.com/electron-userland/electron-builder/issues/1639#issuecomment-307354319 You can expect fix this week if.
