### ISSUE TITLE
Specify artifact name template for publishing and autoupdate

### ISSUE THREAD

**Issue by d9k** [electron-userland/electron-builder#1548]
* **Version**: 16.3.0

* **Target**:  Win 32bit/64bit (separately)

I know that electron builder returns lists of artifacts (I mean resuilting installers, *.exe for windows) so I can rename files after build
https://github.com/electron-userland/electron-builder/issues/899#issuecomment-260137675

But I have a need to not only make separate builds for win32/win64 targets (large different sets of dlls for each architecture) but also publish them to github with different names automatically (there is requirment auto-update). How can I solve an issue for automated publishing and automatic update for separate 32bit/64bit builds?

**Comment by d9k** [comment]
For generic public configuration it is possible to use `${arch}` and `${os}` variables in auto update url template.
https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#GenericServerOptions

But what if I want to specify different names for artifacts with different ${arch} published as github releases?

**Comment by yhostc** [comment]
+1

**Comment by develar** [comment]
artifactName is respected now if safe (a-z0-9_-.)
