### ISSUE TITLE
how to set windows uninstall application icon?DispalyIcon invalid

### ISSUE THREAD

**Issue by hengkx** [electron-userland/electron-builder#1550]
how to set windows uninstall application icon?
I need custom path icon。
` WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" "DisplayIcon" "$INSTDIR\uninstall.ico,0"`don't use.

**Comment by hengkx** [comment]
`var startMenuLinkUnInstall

!macro setUninstallLinkVars
  !ifdef MENU_FILENAME
    StrCpy $startMenuLinkUnInstall "$SMPROGRAMS\${MENU_FILENAME}\Uninstall ${PRODUCT_FILENAME}.lnk"
  !else
    StrCpy $startMenuLinkUnInstall "$SMPROGRAMS\Uninstall ${PRODUCT_FILENAME}.lnk"
  !endif
!macroend

!macro customHeader

!macroend

!macro preInit

!macroend

!macro customInit
  !insertmacro setUninstallLinkVars
!macroend

!macro customInstall
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" HelpLink "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" URLUpdateInfo "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" URLInfoAbout "http://www.fulu.com"
#   WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" "DisplayIcon" "$INSTDIR\uninstall.ico,0"

  CreateShortCut "$startMenuLinkUnInstall" "$INSTDIR\${UNINSTALL_FILENAME}" "" "$INSTDIR\${UNINSTALL_FILENAME}" 0 "" "" ""
!macroend

!macro customUnInit
  !insertmacro setUninstallLinkVars
!macroend

!macro customUnInstall
  WinShell::UninstShortcut "$startMenuLinkUnInstall"
  Delete "$startMenuLinkUnInstall"
!macroend
`

**Comment by develar** [comment]
`uninstallerIcon` options was added to `nsis`. Defaults to `uninstallerIcon.ico`

**Comment by hengkx** [comment]
@develar Thanks,I set it this way;
 `"nsis": {
      "oneClick": true,
      "perMachine": true,
      "include": "build/installer.nsh",
      "uninstallerIcon": "uninstallerIcon.ico"
    },`
uninstall application icon  invalid

**Comment by develar** [comment]
Do you use latest version? Did you remove your custom code? Where icon is invalid and how?

**Comment by hengkx** [comment]
@develar 
1.I use version `17.10.0`
2.I use electron version `1.6.8`
3.I removed code
4.
![c](https://cloud.githubusercontent.com/assets/8358236/26289671/8dc92730-3ed4-11e7-81cc-3b6f688c4bda.png)

**Comment by develar** [comment]
Just put uninstallerIcon.ico to build dir and nothing more. ExtraResources not required.

**Comment by hengkx** [comment]
@develar Still not in use，`"nsis": {
      "oneClick": true,
      "perMachine": true,
      "include": "build/installer.nsh",
    },`

**Comment by hengkx** [comment]
build/installer.nsh
`var startMenuLinkUnInstall

!macro setUninstallLinkVars
  !ifdef MENU_FILENAME
    StrCpy $startMenuLinkUnInstall "$SMPROGRAMS\${MENU_FILENAME}\Uninstall ${PRODUCT_FILENAME}.lnk"
  !else
    StrCpy $startMenuLinkUnInstall "$SMPROGRAMS\Uninstall ${PRODUCT_FILENAME}.lnk"
  !endif
!macroend

!macro customHeader

!macroend

!macro preInit

!macroend

!macro customInit
  !insertmacro setUninstallLinkVars
!macroend

!macro customInstall
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" HelpLink "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" URLUpdateInfo "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" URLInfoAbout "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" URLInfoAbout "http://www.fulu.com"
  WriteRegStr SHCTX "${UNINSTALL_REGISTRY_KEY}" Comments "我是附加内容"


  CreateShortCut "$startMenuLinkUnInstall" "$INSTDIR\${UNINSTALL_FILENAME}" "" "$INSTDIR\${UNINSTALL_FILENAME}" 0 "" "" ""

  WriteRegStr HKCU "SOFTWARE\Classes\directory\shell\${PRODUCT_FILENAME}" "" "Open With ${PRODUCT_FILENAME}"
  WriteRegStr HKCU "SOFTWARE\Classes\directory\shell\${PRODUCT_FILENAME}" "Icon" "$\"$appExe$\""
  WriteRegStr HKCU "SOFTWARE\Classes\directory\shell\${PRODUCT_FILENAME}\command" "" "$\"$appExe$\" $\"%1$\""
  WriteRegStr HKCU "SOFTWARE\Classes\directory\background\shell\${PRODUCT_FILENAME}" "" "Open With ${PRODUCT_FILENAME}"
  WriteRegStr HKCU "SOFTWARE\Classes\directory\background\shell\${PRODUCT_FILENAME}" "Icon" "$\"$appExe$\""
  WriteRegStr HKCU "SOFTWARE\Classes\directory\background\shell\${PRODUCT_FILENAME}\command" "" "$\"$appExe$\" $\"%V$\""
!macroend

!macro customUnInit
  !insertmacro setUninstallLinkVars
!macroend

!macro customUnInstall
  WinShell::UninstShortcut "$startMenuLinkUnInstall"
  Delete "$startMenuLinkUnInstall"

	DeleteRegKey HKCU "SOFTWARE\Classes\directory\shell\${PRODUCT_FILENAME}"
	DeleteRegKey HKCU "SOFTWARE\Classes\directory\background\shell\${PRODUCT_FILENAME}"
!macroend
`

**Comment by hengkx** [comment]
![image](https://cloud.githubusercontent.com/assets/8358236/26297399/36b43fee-3f05-11e7-9cda-5ec7de95214c.png)

**Comment by hengkx** [comment]
@develar 
The icon I saw in the uninstall panel was correct, but the uninstall application(exe) icon was not wrong
