### ISSUE TITLE
Switch /D is ignored

### ISSUE THREAD

**Issue by rozumny** [electron-userland/electron-builder#1551]
* **17.5.0**: 

* **WIN64**: 

Adding switch /D to set custom install directory when running generated installer from command line is ignored. Any idea how can this be done?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/nsis/multiUser.nsh `InstDir`.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by bennol** [comment]
@rozumny were you able to get `/D` working for you?

**Comment by rozumny** [comment]
I had to change multiUser.nsh as following:

`!include FileFunc.nsh
!include UAC.nsh

!define FOLDERID_UserProgramFiles {5CD7AEE2-2219-4A67-B85D-6C9CE15660CB}
!define KF_FLAG_CREATE 0x00008000

!define INSTALL_REGISTRY_KEY "Software\${APP_GUID}"
!define UNINSTALL_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_GUID}"
!define UNINSTALL_DISPLAY_NAME "${PRODUCT_NAME} ${VERSION}"

# current Install Mode ("all" or "CurrentUser")
Var installMode

!ifndef INSTALL_MODE_PER_ALL_USERS
  !ifndef ONE_CLICK
    Var hasPerUserInstallation
    Var hasPerMachineInstallation
  !endif
  Var PerUserInstallationFolder

  !macro setInstallModePerUser
    StrCpy $installMode CurrentUser
    SetShellVarContext current

    # сhecks registry for previous installation path
    ReadRegStr $perUserInstallationFolder HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation
    ${if} $perUserInstallationFolder != ""
      StrCpy $INSTDIR $perUserInstallationFolder
    ${else}
      StrCpy $0 "$LocalAppData\Programs"
      # Win7 has a per-user programfiles known folder and this can be a non-default location
      System::Call 'Shell32::SHGetKnownFolderPath(g "${FOLDERID_UserProgramFiles}",i ${KF_FLAG_CREATE},i0,*i.r2)i.r1'
      ${If} $1 == 0
        System::Call '*$2(&w${NSIS_MAX_STRLEN} .r1)'
        StrCpy $0 $1
        System::Call 'Ole32::CoTaskMemFree(ir2)'
      ${endif}
      StrCpy $INSTDIR "$0\${APP_FILENAME}"
    ${endif}

    ${GetParameters} $R0
    ${GetOptions} $R0 "-D=" $R1
    ${IfNot} ${Errors}
      StrCpy $INSTDIR $R1
    ${EndIf}

    ${GetOptions} $R0 "-C=" $R1
  ${IfNot} ${Errors}
  CopyFiles $R1 $INSTDIR
${EndIf}
  !macroend
!endif

!ifdef INSTALL_MODE_PER_ALL_USERS_REQUIRED
  Var perMachineInstallationFolder
  
  !macro setInstallModePerAllUsers
    StrCpy $installMode all
    SetShellVarContext all

    !ifdef BUILD_UNINSTALLER
      ${IfNot} ${UAC_IsAdmin}
        ShowWindow $HWNDPARENT ${SW_HIDE}
        !insertmacro UAC_RunElevated
        Quit
      ${endif}
    !endif

    # сheck registry for previous installation path
    ReadRegStr $perMachineInstallationFolder HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation
    ${if} $perMachineInstallationFolder != ""
      StrCpy $INSTDIR $perMachineInstallationFolder
    ${else}
      StrCpy $0 "$PROGRAMFILES"
      !ifdef APP_64
        ${if} ${RunningX64}
          StrCpy $0 "$PROGRAMFILES64"
        ${endif}
      !endif

      !ifdef MENU_FILENAME
        StrCpy $0 "$0\${MENU_FILENAME}"
      !endif

      StrCpy $INSTDIR "$0\${APP_FILENAME}"
    ${endif}

    ${GetParameters} $R0
    ${GetOptions} $R0 "-D=" $R1
    ${IfNot} ${Errors}
       StrCpy $INSTDIR $R1
    ${EndIf}

    ${GetOptions} $R0 "-C=" $R1
  ${IfNot} ${Errors}
  CopyFiles $R1 $INSTDIR
${EndIf}
  !macroend
!endif`

**Comment by bennol** [comment]
@rozumny Thank you so much for the quick response!
This seems to be quite a good fix at least for the MultiUser Installer - Should this be a PR?

**Comment by rozumny** [comment]
you can push it if it works for you ;)

**Comment by bennol** [comment]
I planned to create a PR with a parameter check for `/D` like this 
```
${GetParameters} $R0
${GetOptions} $R0 "/D=" $R1
${IfNot} ${Errors}  
  StrCpy $INSTDIR $R1
${EndIf}
```
but the `/D` parameter is translated into an initial $INSTDIR value by NSIS and afterwards no longer obtainable from the script. 

Not sure what the cleanest way to go is for the PR:
- Use the default `/D` parameter functionality and introduce some clutter (uninstaller check, skip registry reading), comply with the usage rules of the default parameter 
> It must be the last parameter used in the command line and must not contain any quotes, even if the path contains spaces
http://nsis.sourceforge.net/Docs/Chapter3.html#installerusagecommon

- Introduce new parameter (e.g. `/INSTDIR`), simple implementation, minimal code changes, no default NSIS compliance

If one of the maintainers (@develar ?) will point me into the direction, I'd be happy to submit the PR.

**Comment by develar** [comment]
@bennol Cool. We don't recommend NSIS `GetParameters` API. Please try `${StdUtils.GetParameter}` instead (see http://muldersoft.com/docs/stdutils_readme.html#f24cc3f9).
