### ISSUE TITLE
Cannot config multiple target

### ISSUE THREAD

**Issue by andy5638** [electron-userland/electron-builder#1553]
* **Version**: 17.5.0

* **Target**: Windows,Mac,Linux

I'm trying to build applications on each desktop platform including windows,mac and linux. I want to offer multiple installer format to let user to choose. Here is my config:
```
config: {
    linux: {
        target: "deb zip"
    },
    win: {
        target: "nsis zip"
    },
    mac: {
        target: "dmg zip"
    }
}
```
And I got error message: 

> Unknown target: nsis zip

For now I have to build twice for each file format. Is that possible to build them in a row?

**Comment by develar** [comment]
`target: ["nsis", "zip"]`
