### ISSUE TITLE
Error building appx

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1559]
Hey @develar,

* **Version**: 17.8.0

* **Target**: win, appx

Last version I used for building appx was 11.something. Seems like the options "language" has changed.

This was my previous working build block:

```json
{
  "appId": "...",
  "copyright": "...",
  "asar": true,
  "files": [
    "app/**/*",
    "node_modules/**/*",
    "package.json"
  ],
  "extraFiles": [
    "..."
  ],
  "win": {
    "target": [
      "appx"
    ],
    "publisher": "...",
    "backgroundColor": "transparent",
    "identityName": "...",
    "displayName": "...",
    "publisherDisplayName": "..."
  }
}
```

But running builder now throws: 

> "Invalid option object"
> at xyz\node_modules\electron-builder\src\util\readPackageJson.ts:153:11

Complaining about the *win* part. I tried to understand the options wiki (which has changed drastically) but I don't seem to get it. It's become too nested, I think. Guess we should add some examples.

Please tell me how the config must look for building appx with the latest version of electron-builder.

Thanks

**Comment by develar** [comment]
`publisherDisplayName`, `displayName`, `identityName`, `backgroundColor` and `publisher`  must be in the `appx`.

**Comment by develar** [comment]
Have you seen http://electron-userland.github.io/electron-builder/?

**Comment by black-snow** [comment]
Yes, I've seen that. Couldn't extract any useful information from it, though.

> must be in the `appx`

`appx` is a string in my example. Should I wrap the params in an object with the index `appx`? Or shall `target` be an object with `appx` as a field? Gonna give both a try.

**Comment by develar** [comment]
```
"build": {
  "appx": {
  }
}
```

**Comment by develar** [comment]
> . Couldn't extract any useful information from it, though.

Could you please provide an example of useful/good docs?

**Comment by black-snow** [comment]
Thanks for your quick reply (again).

That seemed to work .. at first. But then weird things happened ;)

> Building NSIS installer
  Packaging NSIS installer for arch ia32
  Signing NSIS uninstaller (certificate file: "xyz.pfx")

Why would it build an NSIS installer if I told him to pack for *appx*? It then continues:

> Signing xyz.exe (certificate file: "xyz.pfx")
Error: Exit code: 1. Command failed: C:\Users\xyz\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.7.0\windows-10\x64\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /f xyz.pfx /fd sha256 /td sha256 /d xxx /du http://example.org /as xyz\di
st\xyz.exe
SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: xyz\dist\xyzexe

Did it download and try to sign my ia32 app with a x64 singtool? Is that correct? And how come the file is being used by another process?

Should I open a new issue?

---

Concerning the docs: Dunno; liked the docs how they were ~half a year ago. Less segmented and with examples. Frankly, I don't quite know what to do with the json schema tool and I'm somewhat too lazy to read and understand the schema. It's like I had to learn japanese to read the manual of my car.

**Comment by black-snow** [comment]
Alright, I figured it out. I need both, `config.win.target[0] = appx` as well as `config.appx`.

Gonna close this for now.

**Comment by black-snow** [comment]
@develar  Have you had time to look into this? Sadly, due to https://github.com/electron-userland/electron-builder/issues/1576 and me being bad in *ts*, I fear I cannot fix this myself.
From the simplicity of the fix I found in the transpiled code I'd guess that the fix shouldn't be hard.

**Comment by develar** [comment]
Not yet. I will take a look tonight.

**Comment by black-snow** [comment]
Thank you

**Comment by develar** [comment]
@black-snow #1515

**Comment by develar** [comment]
Issue reopened — something should be fixed in the our docs.
