### ISSUE TITLE
Cant set window size for dmgInstaller.

### ISSUE THREAD

**Issue by ms4ever7** [electron-userland/electron-builder#1562]
I am making ember electron app, and when I an running the command 
`ember electron:make --platform darwin` it is taking options from electron-forge-config.js file, 
here it is options for macOs:
`  electronInstallerDMG: {
    title: 'DyeGraph',
    background: 'public/assets/images/logo.png',
    icon: '/Users/roman.blyztsiv/projects/dyegraph/public/assets/images/logo.png',
    window: {
      width: 450,
      height: 427
    },
    contents: [
    { 'x': 94, 'y': 260, 'type': 'file', 'path': '/Users/roman.blyztsiv/projects/dyegraph/electron-out/DyeGraph-darwin-x64/DyeGraph.app' },
    { 'x': 355, 'y': 260, 'type': 'link', 'path': '/Applications' }
    ]
  },` , Problem is that , image size is 600x571, so I set window's size to same, but somehow it resized my image to 450x427 . So now i am trying to resize window to 450x427 too , but it is not changing at all.
I was trying to make everything work as it is in [this(Ghost)](https://github.com/tryghost/Ghost-Desktop) example, but it is not working.

**Comment by develar** [comment]
If you use electron-forge, please file issue to electron-forge. Options for electron-builder in the `build.dmg` https://github.com/electron-userland/electron-builder/wiki/Options#DmgOptions

**Comment by develar** [comment]
@ms4ever7 https://github.com/electron-userland/electron-forge This project — electron-builder ;)
