### ISSUE TITLE
Can't set DMG-Installer background and window size when doing ember electron:make

### ISSUE THREAD

**Issue by ms4ever7** [electron-userland/electron-builder#1563]
* **Version**:  ember-electron: ^2.2.1

* **Target**: Mac

I am using ember electron to create my app , but i am having problem with macOS installer. To build my app i am using  `ember electron:make` command and it takes options from eletron-forge-config.js file.I  was trying to set a background image for dmg-installer, and as my iamge has size 600x571 , i set same window size.
But somehow it resized my image and my windows became 600x571, but image 450x427.
Then I tried to resize window size to 450x427 , but now it not resizing at all.
 Here is my code now for dmg installer:
`electronInstallerDMG: {
    title: 'DyeGraph',
    background: 'public/assets/images/logo.png',
    icon: '/Users/roman.blyztsiv/projects/dyegraph/public/assets/images/logo.png',
    window: {
      width: 450,
      height: 427
    },
    contents: [
    { 'x': 94, 'y': 260, 'type': 'file', 'path': '/Users/roman.blyztsiv/projects/dyegraph/electron-out/DyeGraph-darwin-x64/DyeGraph.app' },
    { 'x': 355, 'y': 260, 'type': 'link', 'path': '/Applications' }
    ]
  },`
I was trying to make everything like [here](https://github.com/tryghost/Ghost-Desktop) , but nothing is happening

**Comment by develar** [comment]
Duplicates #1562
