### ISSUE TITLE
How to remove "Space required" text for NSIS installer ?

### ISSUE THREAD

**Issue by abbish** [electron-userland/electron-builder#1566]
Hi

As the following image , how to config to hide or remove these text which marked on image ?

becuz the "Space required" size was incorrect, or who knows hot to setup the size in electron builder ?

![cfed8162-fc94-4d19-a61d-ed7cb6405215](https://cloud.githubusercontent.com/assets/138192/26296992/9b61ddb8-3f03-11e7-9d23-5bb8156cb8e6.png)

**Comment by develar** [comment]
Thanks, for suggestion,`SpaceTexts none` should be specified. Will be implemented soon.

BTW — why do you need to hide it?

**Comment by develar** [comment]
`SpaceTexts none` is added. true solution — compute size (since we use 7zip, NSIS cannot detect correctly) and use `SectionSetSize`, — help wanted.

**Comment by abbish** [comment]
@develar 
Thank you for your timely response on this issue, may i know which version will contain this change ?

**Comment by develar** [comment]
18.1.0 will be released today (you will be notified when this issue will be closed).

**Comment by abbish** [comment]
Thanks

**Comment by abbish** [comment]
![screen shot 2017-05-31 at 5 26 04 pm](https://cloud.githubusercontent.com/assets/138192/26625579/2071004a-4627-11e7-9796-75bc6ab35249.png)

Add option like this ?

**Comment by develar** [comment]
@abbish no, in the NSIS scripts. It is already disabled and released, please try 18.1.1.

**Comment by samantrader** [comment]
Hi  
how  can  add  this  'SpaceTexts none'  in     NSIS scripts ?
