### ISSUE TITLE
Product name for linux targets takes from app/package.json, cant change it dynamically 

### ISSUE THREAD

**Issue by verget** [electron-userland/electron-builder#1567]
* **Version**: 17.1.2
* **Target**: deb

In case of linux data for builds names takes from app/package.json "name" and "version" values unlike of mac and window, where it coming from root package.json. So I can't dynamically change build name like for nsis, for example "build --config.productName=Example"

**Comment by develar** [comment]
Where incorrect name is used?

**Comment by verget** [comment]
it's used for build naming, so my example "build --config.productName=Example" - will create on windows build with name "Example-{version}.exe" but on linux it will be "{name-from-app/package.json-{version}.deb}"

**Comment by develar** [comment]
By intention. According to Linux convention.  See also #775.

**Comment by verget** [comment]
Is there some way for dynamically  add custom string to linux build names without "app/package.json" change? Im looking for a way to marker my builds depending on git branch from which it made. (dev, prod etc)

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390

`--em.name=newName`

**Comment by verget** [comment]
After update to 20.0.6 version `--em.name=newName` failed with error `Unknown argument: em`. When I tried `--confign.name=newName` - I had error `configuration has an unknown property 'name'`, command `--confign.productName=newName` return no error but also didnt do anything with build name, it still marked as wrote in package.json productName field.
