### ISSUE TITLE
Comment in electron-builder.json5 blows install/build up

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1569]
* **Version**:  17.8, 17.10.0

* **Target**: appx

Having comments in `.json5` should be fine but even `npm install` fails when I have a comment in my `electron-builder.json5`.

> > install-app-deps
 
YAMLException: missed comma between flow collection entries at line 22, column 3:
      // }
      ^
    at generateError (xyz\node_modules\electron-builder\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)

Building fails as well.

**Comment by black-snow** [comment]
@develar We can't use `js-yaml` for that, do we? `json5` comments are javascript-style comments, i. e. `//` or `/**/` whereas `yaml` comments are `#`. `yaml` supports `json` (no comments at all) but does not support `json5`.

I'll see if I can file a PR fixing this.

**Comment by develar** [comment]
18.0.0 released, thanks for PR.
