### ISSUE TITLE
electron-updater using non-existent Electron classes "RequestOptions" and "LoginAuthInfo"

### ISSUE THREAD

**Issue by TAGC** [electron-userland/electron-builder#1572]
* **electron-builder version**: 17.10.0

* **electron-updater version**: 1.16.0

* **electron version**: 1.7.1

* **Target**: windows (squirrel)

Trying to follow the [onshape-desktop-shell](https://github.com/develar/onshape-desktop-shell) example, I installed the latest version of `electron-builder` and `electron-updater` in my TypeScript project. However, when I try building my project (for development or production) I see the following TypeScript errors:

```
ERROR in [at-loader] ./node_modules/electron-updater/out/electron-updater.d.ts:8:67
    TS2694: Namespace 'Electron' has no exported member 'RequestOptions'.

ERROR in [at-loader] ./node_modules/electron-updater/out/electron-updater.d.ts:10:58
    TS2694: Namespace 'Electron' has no exported member 'LoginAuthInfo'.

ERROR in [at-loader] ./node_modules/electron-updater/out/electron-updater.d.ts:12:39
    TS2694: Namespace 'Electron' has no exported member 'RequestOptions'.

ERROR in [at-loader] ./node_modules/electron-updater/out/electron-updater.d.ts:62:50
    TS2694: Namespace 'Electron' has no exported member 'LoginAuthInfo'.
```

**Comment by develar** [comment]
Do you use types/electron npm package as electron typing?

**Comment by TAGC** [comment]
@develar No, I use electron's in-built typings (`node_modules/electron/electron.d.ts`) that they've started providing since v1.6.9.

**Comment by develar** [comment]
Thanks, migrated to new official typings, will be released in several days.
