### ISSUE TITLE
Question: why linux distro is so large ?

### ISSUE THREAD

**Issue by gengjiawen** [electron-userland/electron-builder#1573]
Recently I try to build github client for linux, but the package is very big.
Here is the release page : https://github.com/gengjiawen/desktop/releases/ .

**Comment by black-snow** [comment]
What's the issue? Electron apps are always rather huge due to the whole chrome+node stuff.

**Comment by gengjiawen** [comment]
If you click the link, you will find linux AppImage is more than 500m, while windows is less than 70m.

**Comment by black-snow** [comment]
Now I see it. That's weird. The mac app is quite big, too. I don't see this being the case with other electron apps so you're right, there must be something wrong. Can you provide your build config?

**Comment by gengjiawen** [comment]
it's in the feature/ci_build branch.

**Comment by gengjiawen** [comment]
It's because one of the module is too big https://github.com/gengjiawen/desktop/issues/3.

**Comment by develar** [comment]
Sorry that I didn't investigate it for you — you know, there are too many requests and my free time limited. Thanks for confirmation.

**Comment by gengjiawen** [comment]
Thanks for your reply and for your great attribution. I have multi project using this module and they are works great. So it's likely a problem on the github desktop itself. And it turns out that way.
