### ISSUE TITLE
yarn test stuck/ win10

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1576]
* **Version**: 17.10.0

* **Target**: -

`npm test` fails. Windows 10 Creators Update x64

> AssertionError: false == true
    at fixWinEPERM (E:\_user\Desktop\electron-builder\node_modules\fs-extra\lib\remove\rimraf.js:117:5)
    at options.lstat (E:\_user\Desktop\electron-builder\node_modules\fs-extra\lib\remove\rimraf.js:86:14)
    at E:\_user\Desktop\electron-builder\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:114:15)

Also `AppImage` test seem to fail instead of being skipped:

> Building AppImage for arch x64
 FAIL  test\out\linux\linuxPackagerTest.js (6.293s)
  ● AppImage

>    Exit code: ENOENT. spawn C:\Users\xyz\AppData\Local\electron-builder\cache\AppImage\AppImage-09-07-16-linux\xorriso ENOENT
      at packages/electron-builder-util/src/util.ts:75:16
      at exithandler (child_process.js:212:5)

~~Also it'd be nice to have a section in the readme about contributing. Do I need to take any steps in order to get *electron-builder* set up for contibution? (windows)~~ found the CONTRIBUTING.MD

**Comment by black-snow** [comment]
Didn't see the contributing.md - gonna close this for now.

**Comment by black-snow** [comment]
Aight, I installed yarn and ran `yarn && yarn compile`.

But `yarn test` seems to be stuck at 

```sh
$ node ./test/out/helpers/runTests.js skipArtifactPublisher ALL_TESTS=isCi
custom opt: skipArtifactPublisher
custom opt: ALL_TESTS=isCi
Custom env ALL_TESTS=false
```

no progress and no CPU/MEM usage for about an hour - gonna quit this now.
`npm test` is stuck at the very same point.

**Comment by black-snow** [comment]
```
$ node ./test/out/helpers/checkDeps.js
Checking asar-integrity
Checking electron-builder
Checking electron-builder-core
Checking electron-builder-http
Checking electron-builder-squirrel-windows
Checking electron-builder-util
Checking electron-forge-maker-appimage
Checking electron-forge-maker-nsis
Checking electron-forge-maker-nsis-web
Checking electron-forge-maker-snap
Checking electron-publish
Checking electron-publisher-s3
Checking electron-updater
Error: Cannot find module 'E:\_user\Desktop\electron-builder\packages\electron-builder-core\package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at readJSON (E:\_user\Desktop\electron-builder\node_modules\depcheck\dist\utils\index.js:27:10)
    at depcheck (E:\_user\Desktop\electron-builder\node_modules\depcheck\dist\index.js:68:57)
    at result (E:\_user\Desktop\electron-builder\test\out\helpers\checkDeps.js:20:57)
    at E:\_user\Desktop\electron-builder\test\out\helpers\checkDeps.js:19:30
    at Generator.next (<anonymous>)
From previous event:
    at check (E:\_user\Desktop\electron-builder\test\out\helpers\checkDeps.js:59:21)
error Command failed with exit code 4294967295.
...

**Comment by develar** [comment]
@black-snow Please do yarn compile before.

**Comment by black-snow** [comment]
@develar I see `yarn compile v0.26.1` happening when I run `yarn test`.
When I run `yarn compile` it's `yarn compile v0.24.6`
After yielding the above error once it's not stuck after generating tests. Maybe I can give it another shot tomorrow.

**Comment by black-snow** [comment]
Error's still the same. Tested in git bash and power shell.

**Comment by develar** [comment]
Will be cool if you will investigate it :(

**Comment by black-snow** [comment]
'Aight. Let me document my findings:

1) In fact there is no `package.json` in `packages/electron-builder-core`. There's just an `out` dir and nothing else while, for example, there is `src` +`out` + `package.json` + `readme.md` + `tsconfig.json` in `packages/electron-builder-http`.

**investigating** -> 2) - so there must be something wrong with the pipeline that constructs this

**Comment by develar** [comment]
> electron-builder-core

delete this dir, not exists anymore.

**Comment by develar** [comment]
> AppImage

Fixed. Skip on windows.

> only zip

Fixed. Skip on windows.

> failed peer dep

I hope fixed.

**Comment by black-snow** [comment]
@develar awesome! Please trigger me when it's pushed so I can give it another try.

**Comment by develar** [comment]
@black-snow Pushed to master.

**Comment by black-snow** [comment]
We're getting closer:

```
 FAIL  test\out\linux\linuxPackagerTest.js
  ● AppImage - default icon, custom executable and custom desktop

    Exit code: ENOENT. spawn C:\Users\m02ph\AppData\Local\electron-builder\cache\AppImage\AppImage-09-07-16-linux\xorris
o ENOENT

      at packages/electron-builder-util/src/util.ts:64:16
  × AppImage - default icon, custom executable and custom desktop (3728ms)

 FAIL  test\out\nsisUpdaterTest.js
  ● Test suite failed to run

    ProcessTerminatedError: cancel after 2 retries!

      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:87:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:36)
      at ontimeout (timers.js:488:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:283:5)

A worker process has quit unexpectedly! Most likely this is an initialization error.

Test Suites: 1 failed, 2 skipped, 3 passed, 4 of 27 total
Tests:       1 failed, 35 skipped, 6 passed, 42 total
Snapshots:   6 passed, 6 total
error Command failed with exit code 1.
```
