### ISSUE TITLE
no commit task

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1577]
* **Version**: 17.10.0

* **Target**: -

CONTRIBUTING.md says:

> run npm run commit in your terminal after staging your changes in git.

But there ain't no such task in `package.json`.
I installed commitizen `npm i -g commitizen` and ran `git cz` but that just made a normal commit.

**Comment by develar** [comment]
Incorrect sentence removed. In any case PR will be squashed and commit messages reformatted if need. Contributor should not worry about it.
