### ISSUE TITLE
Mac signing: wrong team/group id are used when using a provision profile.

### ISSUE THREAD

**Issue by feens** [electron-userland/electron-builder#1579]
While doing some builds for the Mac App Store, we ran into an issue that when dev mode is used, the script grabbed the correct certificate, but the problem is that it was using the certificate ID as the team/application-group ids, which is incorrect when using a proper provisioning profile.  In that case, the group/team should match the distribution version...just the certificate should differ.  

This is correctable by specifying entitlements files and settings those values manually, rather than having them injected.  But ultimately it would make more sense for the script to decipher the proper values and pass them along.  

This is true on *master* as of 2017-05-19.

**Comment by develar** [comment]
Issue not clear for me. PR welcome.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
