### ISSUE TITLE
"status 401: Unauthorized" issue with dl.bintray.com

### ISSUE THREAD

**Issue by RTLer** [electron-userland/electron-builder#1581]
* **Version**: electron-builder@^17.10.0

* **Target**: windows mac linux

i'm trying to use electron-builder in travic-ci osx image and it tries to call  `https:://dl.bintray.com//electron-userland/bin/winCodeSign-1.7.0.7z` which is not valid url (it must be `https://dl.bintray.com/electron-userland/bin/winCodeSign-1.7.0.7z`) and produce `401 Unauthorized` error

travic-ci log: [https://travis-ci.org/ZarinPal/Panel/builds/235513645#L740](https://travis-ci.org/ZarinPal/Panel/builds/235513645#L740)

how can i get it to work properly?

**Comment by develar** [comment]
Why you decided that `https:://dl.bintray.com//electron-userland/bin/winCodeSign-1.7.0.7z` is requested? As far I see, URL is correct and it is bintray issue.

**Comment by develar** [comment]
Please try 18.0.1.
