### ISSUE TITLE
latest.yml is completely empty when uploaded to S3 bucket

### ISSUE THREAD

**Issue by TAGC** [electron-userland/electron-builder#1582]
* **electron-builder version**: 17.10.0 

* **electron-updater version**: 1.16.0

* **Target**: Windows 7 64-bit

I've tried configuring electron-builder to publish releases of my Electron app to a newly-created S3 bucket:

```json
{
  "scripts": {
    "release:win": "npm run build && build --win --x64 -p always",
  },
  "build": {
    "publish": [
      {
        "provider": "s3",
        "bucket": "<company_bucket_name>",
        "path": "<product_name>"
      }
    ],
   }
}
```

I see these logs as I'm running the build:

```
No native production dependencies
Packaging for win32 x64 using electron 1.7.1 to bin\win-unpacked
Building NSIS installer
  Packaging NSIS installer for arch x64
Publishing to S3 (bucket: <company_bucket_name>)
[====================] 100% 0.0s | latest.yml to S3
[====================] 100% 0.0s | <product> Setup 0.1.0.exe to S3
```

After the build is complete, I can see both files in the expected location in the S3 bucket. The executable looks about the right size, and I can download it and run it successfully.

However, the uploaded version of `latest.yml` right next to it is 0 bytes big (completely empty). When I launch my installed application, I see these logs:

```
[2017-05-24 13:58:17:0764] [info] Created main window
[2017-05-24 13:58:17:0812] [info] Checking for update
[2017-05-24 13:58:20:0044] [error] Error: TypeError: Cannot read property 'sha2' of undefined
```

**Comment by TAGC** [comment]
I've implemented a workaround until this issue is resolved:

**package.json**

```js
{
  "scripts": {
    "republish-latest": "node  --trace-warnings -r babel-register ./utils/republish-latest.js",
    "release:win": "npm run build && build --win --x64 -p always && npm run republish-latest",
  }
}
```

**utils/republish-latest.js**

```js
/**
 * Temporary script until electron-builder#1582 is resolved (https://github.com/electron-userland/electron-builder/issues/1582).
 */
import * as path from 'path'
import { S3 } from 'aws-sdk'
import { readFileSync } from 'fs'

const BUCKET = '<company>-releases'
const KEY = '<product>/latest.yml'
const LATEST_YML_PATH = path.resolve(__dirname, '../bin/latest.yml')

const s3Options = {
  signatureVersion: 'v4'
}

const putOptions = {
  Bucket: BUCKET,
  Key: KEY,
  ACL: 'public-read',
  Body: readFileSync(LATEST_YML_PATH)
}

const s3 = new S3(s3Options)

function callback (err, data) {
  if (err) {
    console.error('Error occurred while trying to publish latest.yml\n', err)
  } else {
    console.log(data)
    console.info(`Successfully published latest.yml to ${BUCKET}`)
  }
}

s3.putObject(putOptions, callback)
```

**Comment by TAGC** [comment]
Interestingly, this issue doesn't seem to happen for `alpha.yml`, only `latest.yml` i.e. `alpha.yml` gets published to S3 fine and I don't need to use this workaround.

**Comment by nilsbandel** [comment]
I have the same issue. Everything works great on mac, on windows the installer is uploaded fine but the latest.yml is empty.

There is a 2-minute timeout or so before the publish command returns.

On my end, I have the issue both for latest and alpha channels.

**Comment by develar** [comment]
Please try 18.3.5 and it if fails, please set env `DEBUG=electron-builder` and attach build log.

**Comment by develar** [comment]
`electron-publisher-s3` `18.4.0` published. Please try it.

**Comment by develar** [comment]
electron-publisher-s3 18.4.1 published.
