### ISSUE TITLE
how to set windows uninstall application icon? Uninstall ******.exe icon

### ISSUE THREAD

**Issue by hengkx** [electron-userland/electron-builder#1585]

**Comment by hengkx** [comment]
![qq 20170526131400](https://cloud.githubusercontent.com/assets/8358236/26481684/6f040eca-4215-11e7-92b0-3154fe05b944.png)

**Comment by steverandy** [comment]
For squirrel, set `iconUrl` in `squirrelWindows` option. It needs to be a public URL, not local file.

**Comment by hengkx** [comment]
@steverandy I want to use nsis

**Comment by develar** [comment]
Recently added uninstallerIcon option doesn't set icon for uninstaller exe. That's bug.

**Comment by hengkx** [comment]
@develar Is there any solution that can be implemented?

**Comment by develar** [comment]
It is one line fix, I will fix it in 2 days.

**Comment by hengkx** [comment]
@develar Thanks

**Comment by madeeha96** [comment]
Where is it fixed? :/
