### ISSUE TITLE
<script src="..."></script> not working after building

### ISSUE THREAD

**Issue by lotsacode** [electron-userland/electron-builder#1586]
In my `index.html` I have included a js file like this
    `<script src="./js/script.js"></script>`
launching the app with `npm start` works just fine.  When I build it according to the tutorial and launch the app it shows `index.html` but cannot find `./js/script.js` I tried electron-packager and got the same issue. 
OS: windows 10.

**Comment by develar** [comment]
Please ensure that js file is packed. Try to use `js/script.js` path.

**Comment by lotsacode** [comment]
Not sure what this means
I added `"files": ["**/*"]` to `build` in `package.json` with no luck.

**Comment by develar** [comment]
Have you tried `js/script.js`?

**Comment by FireBrandMint** [comment]
To anyone seeing this in the future, your problem might be the same as mine:
it simply didn't come to mind that I needed dev tools to see the console logs of the script that are only posted in the actual window.

Try NOT calling window.removeMenu() and call window.openDevTools()
