### ISSUE TITLE
Can I publish to my self-hosted release server with CLI?

### ISSUE THREAD

**Issue by dengyaolong** [electron-userland/electron-builder#1587]
* **Version**: 17.10.0

* **electron-update Version**: 1.16.0

* **Target**: Document shows we can publish to Github or Amazon S3，however，I want to publish to my self-hosted release server with CLI -p. And electron-updater set feedUrl dynamic. Just like http://my.release.server.com/update/mac/?uid=currentUserId&version=1.0.0，because my product needs gray scale upgrade by uid and version.

**Comment by develar** [comment]
Use any other tool to publish to your server. Or file issue to support SFTP publisher.

 > And electron-updater set feedUrl dynamic

https://github.com/electron-userland/electron-builder/wiki/Auto-Update#module_electron-updater.AppUpdater+setFeedURL

Yes, just `autoUpdater.setFeedUrl("http://my.release.server.com/update/mac")` and then file `latest-mac.json` will be requested, but due to Squirrel.Mac limitation it is not supported yet. Works only on windows (`latest.yml` file will be requested).

So, I suggest you to configure `publish` during build time, and pass required parameters not a query params, but as headers.

```js
autoUpdater.requestHeaders = {"name": "customHeaderValue"}
```

**Comment by dengyaolong** [comment]
So , I can't auto updater on mac ?

**Comment by develar** [comment]
You can, just configure generic publish config:

```json
"publish": {
  "provider": "generic",
  "url": "http://my.release.server.com/update/mac"
}
```

and in the runtime set your custom headers using `autoUpdater.requestHeaders`.

Anyway mac will support dynamic urls as Windows, in 2 weeks (nearly finished).

**Comment by dengyaolong** [comment]
One more question，what's difference between electron-updater and electron's auto-updater?

**Comment by develar** [comment]
@dengyaolong https://www.npmjs.com/package/electron-updater#differences-between-electron-updater-and-built-in-autoupdater

**Comment by dengyaolong** [comment]
any latest.yml example? what should I response when update available？

**Comment by develar** [comment]
@dengyaolong 

```
{
  "provider": "generic"
  "url": "https://example.com"
}
```

and `latest.yml` will be generated for you.

**Comment by dengyaolong** [comment]
Um.. I hava a update server to return update or not, however, nsis installer(.exe) saved in a storage service(not amazon s3).
e.g: 
* my updater server is:  http://my.updater.com/latest.yml
* the nsis installer url is: http://s3.mystorage.com/release/1.1.0.exe

electron client check from update server, update server return the installer url, electron client download the url.

I try to use 
`
{
  "provider": "generic"
  "url": "http://my.updater.com"
}
`
and response latest.yml
`
version: 1.2.0
releaseDate: '2017-06-06T07:30:23.993Z'
path: http://s3.mystorage.com/release/1.1.0.exe
sha2: xxxxxxx 
`
check url is right, but download is 'http://my.updater.com/http://s3.mystorage.com/release/1.1.0.exe'.

How to set latest.yml that can tell client downloand from the storage service?

**Comment by develar** [comment]
> check url is right, but download is 'http://my.updater.com/http://s3.mystorage.com/release/1.1.0.exe'.

@dengyaolong It is bug, I will fix it today.

BTW, for what do you need to have own server?

**Comment by dengyaolong** [comment]
My product need to grayscale update ，so  I need to request my company grayscale service,  and do some auth.

**Comment by dengyaolong** [comment]
windows electron-updater not use squirrel? I saw that, it download a exe, and run the exe ? right?

**Comment by develar** [comment]
> it download a exe, and run the exe ? right?

Yes.

**Comment by dengyaolong** [comment]
why didn't use squirrel?

**Comment by dengyaolong** [comment]
> @dengyaolong It is bug, I will fix it today.

do you fixed the bug ?
