### ISSUE TITLE
auto updater, add a flag to NOT restart the app after update (e.g. "update on quit") ?

### ISSUE THREAD

**Issue by coclav** [electron-userland/electron-builder#1589]
Hello;
the autoUpdater has `quitAndInstall` which restarts the app when the update is done. I would like to give user the option to install update when they quit the app (and, therefore, prevent the automatic restart of the app)

My suggestion is, when download is finished to give user the option to "update now!" (calls existing `quitAndInstall` and restarts the app as expected; or second option "update on quit" : set flags `autoUpdater.autoRestart = false` and I can trigger the same `quitAndInstall` when the user is closing the last window.

Background: user can have several windows open with changes not saved, etc. so we are not keen on interrupting the user all the time.

Thanks

**Comment by develar** [comment]
Simply do nothing — what is you requested — is it default behaviour. Do nothing — do not call `quitAndInstall`. Downloaded update will be installed on app quit.

**Comment by develar** [comment]
>  user can have several windows open with changes not saved, etc. so we are not keen on interrupting the user all the time.

That's we do not recommend call `quitAndInstall`.

**Comment by develar** [comment]
Do not bother user — simply download, notify using system notification and nothing more. Update will be installed on app quit. https://github.com/electron-userland/electron-builder/wiki/Auto-Update#examples "using system notifications."

**Comment by coclav** [comment]
haha, awesome. Even more magic awesomness in electron-builder. You all rock!

**Comment by AustinLeath** [comment]
Just found this, thanks for the clarification lol.
