### ISSUE TITLE
Allow building nsis with fileAssociations and without perMachine: true

### ISSUE THREAD

**Issue by steverandy** [electron-userland/electron-builder#1590]
* **Version**: 18.0.1

* **Target**: mac, nsis

Currently, if you have `fileAssociations`, you cannot build nsis without setting `perMachine: true`, because the script will throw error:

`Error: Please set perMachine to true — file associations works on Windows only if installed for all users`.

I need `fileAssociations` for mac build and I'm OK if nsis build will ignore `fileAssociations` when `perMachine` is not `true`. In this case a warning message will be ideal rather than an error.

**Comment by develar** [comment]
Move `fileAssociations` to `mac` :)
