### ISSUE TITLE
Create DMG installer from windows

### ISSUE THREAD

**Issue by devildant** [electron-userland/electron-builder#1591]
hello,

i package my app with electron-packager, and i would like create an installer for mac with electron builder, but ./node_modules/.bin/build --prepackaged <packed dir> create only the installer for windows, il try to add the --mac option but i take an error (only work on mac).

it's possible to create an DMG from windows?

best regards

**Comment by devildant** [comment]
i don't want sign the app for mac

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

No. It is not possible. DMG tool works only on macOS.

**Comment by devildant** [comment]
hello thx for your reply,
Too bad!
