### ISSUE TITLE
AutoUpdate github status 404

### ISSUE THREAD

**Issue by alirezaac** [electron-userland/electron-builder#1593]
i used [this guide](https://github.com/iffy/electron-updater-example) to setup autoupdater for windows nsis it works ok for generic provider but when i use github  here is result
`Found version 0.1.3 (url: https://github.com/pineapplethi3f/venice/releases/download/v0.1.3/venice-Setup-0.1.3.exe)`
`Downloading update from https://github.com/pineapplethi3f/venice/releases/download/v0.1.3/venice-Setup-0.1.3.exe`
`Error: Error: Cannot download "https:://github.com//pineapplethi3f/venice/releases/download/v0.1.3/venice-Setup-0.1.3.exe", status 404: Not Found`

**Comment by frostebite** [comment]
????

**Comment by sostenesapollo12** [comment]
I have the same issue
