### ISSUE TITLE
Implement electron-packager afterCopy handle

### ISSUE THREAD

**Issue by DutchKevv** [electron-userland/electron-builder#1595]
* **Version**: 
18.0.1

* **windows x64**: 

I have a use case where I need to prune multiple directories. Opened a ticket at electron-packager and they recommend doing it manual through the `afterCopy` / `afterExtract` handle

https://github.com/electron-userland/electron-packager/issues/657#issuecomment-304714318

Would it be possible to implement it in the builder config just like the `afterPack` event?? 

Thanks!

**Comment by develar** [comment]
We don't force users to program if something can be easily done automatically. Please vote for #1539 Since you are the second users, this feature will be implemented this week (very easy).

Please describe why do you have several package.json files.

**Comment by DutchKevv** [comment]
https://github.com/electron-userland/electron-builder/issues/1539#issuecomment-304806447

**Comment by develar** [comment]
Duplicates  #1539
