### ISSUE TITLE
Checksum Validation Failing with NSIS updates

### ISSUE THREAD

**Issue by wharri220** [electron-userland/electron-builder#1601]
Electron Version: 1.4.13
Electron Builder Version: 18.0.1

Checksum validation is failing after downloading app update. I'm using a generic provider. The provider I'm using is Azure Blob storage. I am simply publishing my artifacts to a container in blob storage, and using that container endpoint the provider url. Error message in output is 

Error: Error: SHA2 checksum mismatch, expected 60d868696835a767d43cd933600c9d9a3d5c99c3d90893bdb4c045f5974347ed, got 38d100455cfaedf1789204a90e0f1202939fe70647e66f9d7efcabc7b82b3ea9

**Comment by sarunyousaklor** [comment]
Ok

**Comment by wharri220** [comment]
It seems I have uploaded mismatched files at some point, I cleared out everything and started from scratch and it is working now. Thanks!
