### ISSUE TITLE
Identity validation option is incorrect

### ISSUE THREAD

**Issue by feens** [electron-userland/electron-builder#1603]
Currently when signing, the option `skipIdentityValidation: true,` is passed, which I'm assuming is supposed to ensure that `electron-osx-sign` doesn't do identity validation and uses the identity as passed.  However, the correct option for `electron-osx-sign` is now `'identity-validation': false`.

I made mention of this issue in https://github.com/electron-userland/electron-osx-sign/issues/135

**Comment by sethlu** [comment]
Ref:

- Pull request on `electron-osx-sign`: https://github.com/electron-userland/electron-osx-sign/pull/126
- `electron-builder` script: https://github.com/electron-userland/electron-builder/blob/381e8c0dfd079a1bc6485797789a9da78a51f1e6/packages/electron-builder/src/macPackager.ts#L187

**Comment by develar** [comment]
Thanks for spotting!
