### ISSUE TITLE
can't upload to github in CI

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#1605]
* **Version**: 
18.3.0

* **Target**: 
all

my project are using electron-builder for a long time. it used to work, but now can't upload to github releases.

my workflow is create a draft, and then push with same `version`, then build in Travis CI and AppVeyor. it says `CI detected, so artifacts will be published if draft release exists` but don't upload.
if I create a Tag, It can detect tag and says to upload, but still no file in draft release.

package.json
https://github.com/moecube/moecube/blob/master/package.json
Travis CI config file
https://github.com/moecube/moecube/blob/master/.travis.yml
AppVeyor config file
https://github.com/moecube/moecube/blob/master/appveyor.yml
log of Travis CI
https://api.travis-ci.org/jobs/238199283/log.txt?deansi=true
https://api.travis-ci.org/jobs/238201759/log.txt?deansi=true (Tagged)
log of AppVeyor 
https://ci.appveyor.com/api/buildjobs/mo4o3dga78wchqvp/log
https://ci.appveyor.com/api/buildjobs/boryaw0bup5hx3ga/log (Tagged)

**Comment by develar** [comment]
Reproduced, known issue. Will  be fixed ASAP.
