### ISSUE TITLE
images missing after package

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#1606]
* **Version**: 
18.3.0

* **Target**: 
mac

i have a `images` directory with some `.png` images in it.
https://github.com/moecube/moecube/tree/master/images
and refer them in `index.html` like `<img src="./images/xxx.png">`
after package the image could not be find.

extract app.asar, I see images directory is empty.

**Comment by develar** [comment]
You have specified images as extraResources — https://github.com/moecube/moecube/blob/master/package.json#L93

Please try to not do it or use `process.resourcesPath` instead of `./` in the production.

**Comment by zh99998** [comment]
well, you are right, thanks.
remove `images` from `extraResources` solved
