### ISSUE TITLE
file name in latest-mac.json does not match actual file name

### ISSUE THREAD

**Issue by rophy** [electron-userland/electron-builder#1607]
* **Version**:  v18.3.0

* **Target**:  Mac

relevant contents in package.json:
```json
{
  "name": "my-client",
  "productName": "My Client",
  "version": "1.6.0-SNAPSHOT",
  "build": {
    "appId": "my.client",
    "artifactName": "${name}-${version}-${os}.${ext}",
    "publish": {
      "provider": "generic",
      "url": "http://server.com/updates/${os}",
      "channel": "latest"
    },
   ...
}
```

After the fix for #1398, the built file name will be: `my-client-1.6.0-SNAPSHOT-mac.zip`.

Expected generated `latest-mac.json`:
```json
{
  "version": "1.6.0-SNAPSHOT",
  "releaseDate": "2017-06-01T10:49:27.250Z",
  "url": "http://server.com/updates/mac/my-client-1.6.0-SNAPSHOT-mac"
}
```

Actual generated `latest-mac.json`:
```json
{
  "version": "1.6.0-SNAPSHOT",
  "releaseDate": "2017-06-01T10:49:27.250Z",
  "url": "http://server.com/updates/mac/My Client-1.6.0-SNAPSHOT-mac.zip"
}
```

Problem:  since zip file now follows build.artifactName, the URL in latest-mac.json should follow it too.

**Comment by bill-pixvana** [comment]
I'm running into the same issue as well. Any update or am I not using the naming conventions correctly?

**Comment by develar** [comment]
Not fixed yet. As workaround, do not use custom artifactName.

**Comment by bill-pixvana** [comment]
I'm using the artifactName to avoid spaces in the productName problem (https://github.com/electron-userland/electron-packager/issues/297). We were seeing updating problems with spaces in the productName.

**Comment by develar** [comment]
@bill-pixvana thanks for donation. Issue will be fixed 22 September. Do you electron-updater 2 or 1?

**Comment by bill-pixvana** [comment]
Version 2.8 of electron-updater. Thanks for the help

**Comment by bill-pixvana** [comment]
@develar Any update on this issue?

**Comment by develar** [comment]
Should be fixed now.
