### ISSUE TITLE
Examples for Config format?

### ISSUE THREAD

**Issue by hackjutsu** [electron-userland/electron-builder#1609]
I ran into a `Config is invalid` error after updating the electron-builder version from v11.4.4 to v18.3.5. Obviously some breaking changes happen in between regarding the config format.

```
Error: Config is invalid:
{
  "win": [
    {
      "title": "Unknown option",
      "author": "Unknown option"
    },
    "Invalid option object"
  ]
}
```

I browsed around the wiki but failed to find a migration guide. (Maybe the version I was using is too old). Is there a working configs example for different platforms(macOS/Windows/Linux) so that I could get a general idea about how the config format has been changed?

This is my old configs.

```
  "build": {
    "appId": "com.cosmox.lepton",
    "mac": {
      "category": "public.app-category.productivity",
      "publish": [
        "github"
      ]
    },
    "win": {
      "title": "Lepton",
      "author": "CosmoX",
      "target": "nsis",
      "publish": [
        "github"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    },
    "linux": {
      "target": "AppImage",
      "publish": [
        "github"
      ]
    }
  }
```

**Comment by develar** [comment]
How to proceed:

1. Open https://github.com/electron-userland/electron-builder/wiki/Options
2. Search option name on page. e.g. `title` 

`title` only in the DMG options, so, in the `win` it doesn't make any sense and can be removed. Hint: you should use `productName` in the `config` if `name` in the root is not suitable for you.

**Comment by develar** [comment]
`author` should be in the root, not in the `config`.

**Comment by develar** [comment]
> how the config format has been changed

It was not changed. Just validation added ;)

**Comment by hackjutsu** [comment]
@develar 

Ah, I got it wrong in the first place and haven't realized it until the validation is added.

I'll get it fixed. Thanks!

**Comment by Tev-work** [comment]
@develar could you please include exactly what you have said in https://github.com/electron-userland/electron-builder/issues/1609#issuecomment-305711214 in the docs? Just at the start of the Options page. It would make a lot of things clearer :)

(I honestly don't have time for PR right now, but I'll gladly contribute to docs when I get to it, probably sometime over the summer)
