### ISSUE TITLE
install-app-deps not found

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1610]
* **Version**: 18.3.5 (latest)

* **Target**: Windows

A fresh `npm i` won't succeed:

> Der Befehl "install-app-deps" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Which translates to *"command install-app-deps couldn't be found"*.

Log output:

```
3980 info lifecycle xyz@0.10.4~install: xyz@0.10.4
3981 silly lifecycle xyz@0.10.4~install: no script for install, continuing
3982 silly postinstall xyz@0.10.4
3983 info lifecycle xyz@0.10.4~postinstall: xyz@0.10.4
3984 verbose lifecycle xyz@0.10.4~postinstall: unsafe-perm in lifecycle true
3985 verbose lifecycle xyz@0.10.4~postinstall: PATH: xxx
3986 verbose lifecycle xyz@0.10.4~postinstall: CWD: E:\xyz
3987 silly lifecycle xyz@0.10.4~postinstall: Args: [ '/d /s /c', 'install-app-deps' ]
3988 silly lifecycle xyz@0.10.4~postinstall: Returned: code: 1  signal: null
3989 info lifecycle xyz@0.10.4~postinstall: Failed to exec postinstall script
3990 verbose stack Error: xyz@0.10.4 postinstall: `install-app-deps`
3990 verbose stack Exit status 1
3990 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
3990 verbose stack     at emitTwo (events.js:125:13)
3990 verbose stack     at EventEmitter.emit (events.js:213:7)
3990 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
3990 verbose stack     at emitTwo (events.js:125:13)
3990 verbose stack     at ChildProcess.emit (events.js:213:7)
3990 verbose stack     at maybeClose (internal/child_process.js:887:16)
3990 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
3991 verbose pkgid xyz@0.10.4
3992 verbose cwd E:\xyz
3993 verbose Windows_NT 10.0.15063
3994 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
3995 verbose node v8.0.0
3996 verbose npm  v5.0.0
3997 error code ELIFECYCLE
3998 error errno 1
3999 error xyz@0.10.4 postinstall: `install-app-deps`
3999 error Exit status 1
```

**Comment by black-snow** [comment]
Seems like it's somehow been an issue on my side.

**Comment by Lange** [comment]
I am having this issue as well in [nodecg/dashboard](https://github.com/nodecg/dashboard), started with v18.3.0. What did you do to resolve it @black-snow?

**Comment by black-snow** [comment]
Errrr... lemme think for a moment.

I think I upgraded to node v8.0+ and that lead to trouble. Not so sure anymore.
Anyhow, I threw the whole `node_modules` in the trash bin and did a fresh `npm i --dev`.
In fact, I think I forgot the dev-switch :D

**Comment by Lange** [comment]
Ahh okay, interesting. I cleared all my build caches on TravisCI and now my builds are passing again. Thanks for pointing me in the right direction!

**Comment by black-snow** [comment]
@Lange you're welcome and good luck with your project :)

@develar hey, thanks for stopping by again ;)
Now I'm curious; what bugs did you encounter with npm/npm5? I haven't had any problems with npm so far ('cept for times before shrinkwrap/lock). But I'm sure you've had to get into the details of npm way more often that I did.
The only time I used yarn was when testing `electron-builder` (which still won't work on my win machine btw ;) ). I wonder why they didn't contribute to *npm* instead of brewing their own stuff. Didn't read a line about considering that [here](https://code.facebook.com/posts/1840075619545360).

**Comment by develar** [comment]
I am tired to recommend users to remove node modules. It is like Windows reboot.
I am tired to think in case of any error that cache clearing will help me. Especially on CI.
I am tired to make npm working in the docker with various fs implementations.

I am tired to wait until npm wil install/update.
I am tired to type in npm run task, instead of yarn task (no run).
I am tired to fix issues on different machines — npm 5 has lock file also, but yarn is better (see last post in the yarn blog).

I am tired to run npm prune and dedupe.

In addition, you should use yarn for electron apps because yarn automatically clean and reduce size of node modules. Your node modules always in the ideal tree.

**Comment by black-snow** [comment]
> I am tired to type in npm run task, instead of yarn task (no run).

Most important bit. Gets me everytime :D

Well, but that's yarn compared to yarn - would've been nice to measure against npm. Hasn't npm put heavy effort into de-duping?
Which blog post do you mean?

**Comment by black-snow** [comment]
If you relate to [this](https://twitter.com/bestander_nz/status/833696202436784128) - he compared `yarn@0.20.3` to `yarn@0.21.2`. It's nice that they optimized yarn but the comparison to npm is missing :)

**Comment by develar** [comment]
> but the comparison to npm is missing

NPM simply doesn't implement  this logic, NPM tree (especially after numerous install/update) is much worse than Yarn tree.

**Comment by black-snow** [comment]
Have you compared `node_modules` size after `npm dedupe` and `yarn install`?
Don't get me wrong, I don't want to argue. I'm just curious.

I'll give it a try an measure.

**Comment by develar** [comment]
npm: 286,5 MB Done in 12.454s.

yarn: 273,7 MB Done in 4.86s.

project — electron-builder. The main issue —automatic deduplication/prune is not fixed in the NPM at all, only yarn does it automatically. In case of yarn I can just work and forget about package manager issues.

**Comment by black-snow** [comment]
`npm i --dev` with semi-hot caches, 247mb, 2 minutes (1 minute w/ hot cache)
after `npm dedupe` 244mb
`yarn` no caches, 234mb, 1 minute (30s w/ hot cache) plus a node-gyp error that I can't check right now (fsevents)

So yeah, surely outperforms the shit out of npm regarding install time :)

**Comment by develar** [comment]
if you execute `npm dedupe` after `install` and get different size, it means that WTF... it is why yarn is recommended for Electron apps, where deps tree must be in the ideal form always. It is just shame that install doesn't produce ideal tree and explicit dedupe/prune is required.
