### ISSUE TITLE
No contents only a blank page after build

### ISSUE THREAD

**Issue by zhengyan-bme** [electron-userland/electron-builder#1615]
* **Version**: 18.1.0

* **Target**: win32

I use simulatedgreg/electron-vue framework. npm run dev is OK. However, when release the app using  electron builder, only a blank page obtained.
Node version: 6.10.2
NPM version: 5.0.2
Operating System: windows 7 sp1
when run npm run build:
test2@0.0.0 build D:\test2
node .electron-vue/build.js && build

lets-build

√ building main process
√ building renderer process

Hash: 805fe29aae4a7db20829
Version: webpack 2.6.1
Time: 1656ms
Asset Size Chunks Chunk Names
main.js 1.06 kB 0 [emitted] main

Hash: 893c91ac3bb246cfb611
Version: webpack 2.6.1
Time: 8747ms
Asset Size Chunks Chunk Names
imgs/logo.png 61.9 kB [emitted]
renderer.js 96.7 kB 0 [emitted] renderer
styles.css 1.25 kB 0 [emitted] renderer
index.html 324 bytes [emitted]
Child html-webpack-plugin for "index.html":
Asset Size Chunks Chunk Names
index.html 567 kB 0

OKAY take it away electron-builder

electron-builder 18.3.5
No native production dependencies
Packaging for win32 x64 using electron 1.7.2 to build\win-unpacked
Building NSIS installer
Packaging NSIS installer for arch x64

**Comment by develar** [comment]
Do you see any error in the dev tools?

**Comment by zhengyan-bme** [comment]
No errors found. I also used the default template-SimulatedGREG/electron-vue for testing my environment. The same result got. And electron-packager can not work too. I think it is hard to solve. Not any clue there.

**Comment by zhengyan-bme** [comment]
Ok, instead of npm I used yarn to manage the dependencies of modules. It works!

**Comment by develar** [comment]
Never use npm. Yarn FTW.

**Comment by AlexVFornazieri** [comment]
Guys, I'm here with this problem, even with the yarn, any other possible causes?
No error is displayed, including in the output log of the executable.

OS: Window SL 10 x64
Node: v8.10.0
Electron: v1.8.4
-----------------
 OKAY  take it away `electron-builder`

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\electron-builder.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=grpc
  • packaging       platform=win32 arch=x64 electron=1.8.4 appOutDir=build\win-unpacked
  • building        target=nsis file=build\maestro-player Setup 0.9.5.exe archs=x64 oneClick=true
  • building block map blockMapFile=build\maestro-player Setup 0.9.5.exe.blockmap
Done in 530.66s.
