### ISSUE TITLE
Do not pack "elevate.exe" when not needed

### ISSUE THREAD

**Issue by MariaDima** [electron-userland/electron-builder#1620]
* **Version**: 18.5.0 (behavior changed in 13.6.0)

* **Target**: Windows

When an electron application is installed in a user-controlled location, then elevation functionality seems to not be needed.

Since there is an option to allow or not elevation (allowElevation), is it possible to use it in order to not pack at all the "elevate" executable?

**Comment by develar** [comment]
Problem — one day you decided to switch to another type of installer. For updater newly downloaded installer should be black box.

**Comment by MariaDima** [comment]
You are right.

Could the updater do a cleanup before termination?

The reason I'm asking:
Security scans and IT don't like the existence of the elevate executable, so I'm trying to see if we could make it optional for the people that consider it a risk.
Otherwise, users would have to take care of this as part of their application.

**Comment by develar** [comment]
> Security scans and IT don't like the existence of the elevate executable

We should sign it, will it be enough?

>  I'm trying to see if we could make it optional for the people that consider it a risk.

I suggest to introduce new option for that (in the `nsis` NsisOptions).
