### ISSUE TITLE
Cannot find electron dependency to get electron version?

### ISSUE THREAD

**Issue by Ziiiro** [electron-userland/electron-builder#1623]
electron-builder 18.5.1

* **Version**: 

* **Target**: 
win

Error: Cannot find electron dependency to get electron version in the 'C:\Users\Proidi\Desktop\smart1\SmartEXE\package.json'

it makes me confused,how can help me

**Comment by Ziiiro** [comment]
it makes me confused

**Comment by develar** [comment]
yarn add electron --dev
