### ISSUE TITLE
AutoUpdater doesn't follow semantic version ordering when allowPrerelease is set to true

### ISSUE THREAD

**Issue by daveespo** [electron-userland/electron-builder#1625]
* **Version**: 18.0.1

* **Target**: Mac and Windows

If you set allowPrerelease to true, the heuristic for determining the "latest version" reverts to a lexical sort of the available releases on the Github, vs the semantic version sort order defined here:

https://www.npmjs.com/package/semver-compare

This is the offending line:

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/GitHubProvider.ts#L51

It plucks the 'first' version that appears in the /releases response from Github ... which, unfortunately, is not always the latest version semantically. For example, if you have a version 1.0.16 published (prerelease or not), it concludes that the 'latest version' is 1.0.9 when allowPrerelease is set to true

````
[2017-06-05 17:10:17:0162] [info] Checking for update
[2017-06-05 17:10:18:0853] [info] Update for version 1.0.16 is not available (latest version: 1.0.9, downgrade is disallowed.
````

This is the code I'm using to kick off autoUpdate:

````
autoUpdater.allowPrerelease = true;
autoUpdater.checkForUpdates();
````

And here's a Github repo that has enough releases where the sort order problem manifests itself:

https://github.com/aloeai/desktop/releases

When allowPrerelease is set to false, this is not a problem since AutoUpdater uses the /latest URL from Github to determine the latest release.

**Comment by black-snow** [comment]
Thanks for your report!
Didn't verfiy but sounds valid. Did you try fixing it yourself? PRs welcome :)

**Comment by daveespo** [comment]
Sorry, I used up the budget on getting my Electron app up and running so I can't come back to this in the foreseeable future. It's unfortunate that Github's default sort order doesn't honor the semantic versioning order.

**Comment by black-snow** [comment]
@daveespo Sorry to hear that :{
It'd be nice to pass a flag to choose the sorting. Maybe we should ask *gh* :D

Anyways, this sounds like a legit problem. I, too, would expect that it fetches the next version following *semVer*. I didn't look at the code but it shouldn't be hard to get a list of all releases and extract the *semVer'ish* next to fetch.

If you find time for it - always happy to receive a PR.

**Comment by daveespo** [comment]
It's a miracle ... I filed the bug about the sort order of the /releases page with Github ... they acknowledged it as a bug ... and have rolled out the fix.

That makes this ticket moot
