### ISSUE TITLE
Question: converting from Squirrel to NSIS programmatically

### ISSUE THREAD

**Issue by khaledabbas** [electron-userland/electron-builder#1627]
* **Version**: 18.5.1

* **Target**: Windows

I have a windows app that uses squirrel autoupdate, now I want to update to NSIS without having to redistribute the app again to all my clients. So my question is: Is it possible to introduce a squirrel update that will programmatically convert the app to NSIS?

Thanks very much

**Comment by develar** [comment]
Related #837

Yes. By default NSIS is per-user. So, you can simply download programmatically new NSIS installer and run it.

Problem — as #837 is not yet fixed, you need also somehow remove old squirrel app.

**Comment by khaledabbas** [comment]
Great, thanks @develar for all the effort you're putting here!
