### ISSUE TITLE
Blank setup window (Windows 10)

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#1630]
* **Version**: 18.5.1

* **Target**: Windows 10

I've created a simple installer for my electron app using electron-builder. Works great. However, when I run the installer exe I get a mostly blank window:

![blank-setup-win](https://user-images.githubusercontent.com/18287271/26879404-f3356b24-4b5e-11e7-893d-5517fac57409.jpg)

How can I add some text to this window (like, "Please wait while app is installed...")?

**Comment by balugege** [comment]
+1 i would like to put some text there

**Comment by black-snow** [comment]
Which target is that? Can you provide your build config?

**Comment by logidelic** [comment]
Target is default (nsis I assume). My build config is pretty minimal:

```
{
  "name": "xxx",
  "version": "1.1.1",
  "description": "xxx desc",
  "author": "xxx-auth <support@xxx.com>",
  "main": "main.js",
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  },
  "build": {
    "appId": "com.xxx.xyz",
    "artifactName": "${productName}-${version}.${ext}",
    "publish": [
      {
        "provider": "generic",
        "url": "https://www.xxx.com/dl/app/"
      }
    ]
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build"
  }
}
```

Thanks.
