### ISSUE TITLE
Default Install directory

### ISSUE THREAD

**Issue by kokiii** [electron-userland/electron-builder#1634]
* **Version**: 18.6.2

* **Target**:  Windows NSIS

Hello! 
When I'm setting `menuCategory` like "Company/SubDir", default install dir changing to "C:/Program Files/Company/SubDir/productName/"
Is it possible to set the default installation folder as "C:/Program Files/Company/SubDir/" ?
I just don't want to put another sub directory in the "/Company/SubDir/"
Thanks.

**Comment by VishwasShashidhar** [comment]
+1
