### ISSUE TITLE
Mac App Store listing includes unsupported languages 

### ISSUE THREAD

**Issue by jarek-foksa** [electron-userland/electron-builder#1635]
* **Version**: 18.3.5

* **Target**: mas

I have created an app package using Electron Builder and submitted it to the Mac App Store. For some reason [the app listing on MAS](https://itunes.apple.com/us/app/boxy-svg/id611658502?mt=12) shows that the app supports all possible languages/locales rather than just the English language.

I suspect this is because Electron Builder creates dummy <language>.lproj files in Resources/ directory.

**Comment by develar** [comment]
Because of https://github.com/electron/electron/pull/363 

If you are agree that "navigator.language return current system locale instead of always en-US or empty string," fix is not required for you — I can make an option to skip it. 

But consider to ask Electron community about it.

**Comment by develar** [comment]
Duplicates #708

**Comment by jarek-foksa** [comment]
Thanks for explanation. Since I'm not planning to support languages other than English, I can just remove all other locales in `afterPack` callback as suggested in the other thread.
