### ISSUE TITLE
NSIS Installation Directory

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#1637]
I see this installs to %LOCALAPPDATA%/Programs with the name from the package.json -- Is it possible to use the product name property instead? (which includes spaces)

**Comment by develar** [comment]
Problem is that product name can be changed, but name is not changed often. Are really want to have some problems related to spaces/special symbols?

**Comment by atypicalprogrammer** [comment]
So the default is the name directory then? What is the naming scheme for each OS if I may know? Does it hurt to change it on a production app?
