### ISSUE TITLE
user data is not deleted when DMG is uninstalled/trashed.

### ISSUE THREAD

**Issue by durga083** [electron-userland/electron-builder#1638]
Hi...
We have developed an electron based application and we are using electron-builder to create DMG and EXE.
Application specific user data is stored at app.getPath('userdata') location.
When application is un-installed, this data is not getting cleared. 
Could anyone guide me on how this data can be cleared?

Thanks.

**Comment by develar** [comment]
It is intended and desired behavior. As all other companies does, you can or give instructions for users how to delete user data, or develop some special unstaller (if too many paths to delete).

For example, dropbox provide simple text instructions — https://www.dropbox.com/help/desktop-web/uninstall-dropbox

**Comment by durga083** [comment]
Hi,

Thanks for the reply. Does this apply for windows as well? Or is there any feature we can use for windows specifically.

Thanks,
Durga.

**Comment by develar** [comment]
On Windows you need to set [nsis. deleteAppDataOnUninstall](https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-deleteAppDataOnUninstall) to `true`.

**Comment by durga083** [comment]
Thanks. Appreciate your quick response.

I have few questions related to the electron application...
1.) In windows, while installing the electron application I see a screen which shows up like something is happening. Is there anyway to stop showing that screen?
2.) Electron application needs .net. Is there any way where I can verify if .net is available on the users machine before installing?

Thanks in advance.

**Comment by develar** [comment]
> Is there anyway to stop showing that screen?

Better to provide screenshots. If you need silent install — just run with `/S`

> Is there any way where I can verify if .net is available on the users machine before installing?

There is easy way to customize NSIS script — https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script

**Comment by durga083** [comment]
Ok. I will check on that.

**Comment by durga083** [comment]
Can you suggest a way to develop a special uninstaller as there are many paths to delete?

**Comment by develar** [comment]
If you store data only in the `app.getPath('userdata') `, why simply not ask users to manually remove this dir?

> Can you suggest a way to develop a special uninstaller?

I suggest to develop uninstaller as part of your app. e.g. action "Remove user data" in the Help menu. And advise users to invoke this action before moving .app to trash.

**Comment by durga083** [comment]
OK. We will try that, but still wanted to see if we can do it so that we can avoid manual work of the user.

**Comment by snake-py** [comment]
> On Windows you need to set [nsis.deleteAppDataOnUninstall](https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-deleteAppDataOnUninstall) to `true`.

Hey the reference seems not to be working or am I wrong? Do I simply need to add an additional field in my json file?
