### ISSUE TITLE
Code Signing Problem on MAC

### ISSUE THREAD

**Issue by himanshu21092** [electron-userland/electron-builder#1645]
electron-builder@8.7.0

electron-updater@2.1.1

* **Target**:  MAC

I am having problems in Signing the app. I am getting unknown format in import. I have tried all the combinations of certificates, but still getting the same error. Please help. Following is the error.

> electron-builder Executing security import /var/folders/8r/_2t25jh96w3f7nvd2l85tdsr0000gn/T/electron-builder-SCsQZW/t-a0f6-1.p12 -k /var/folders/8r/_2t25jh96w3f7nvd2l85tdsr0000gn/T/electron-builder-SCsQZW/t-a0f6-0.keychain -T /usr/bin/codesign -T /usr/bin/p8364cf9ef03fd66a8b249b4bf565ed2c8c73e02a5f56b56a03a373f82f07d23e (sha256 hash) -P 12345 +66ms
Unhandled rejection Error: Exit code: 1. Command failed: security import /var/folders/8r/_2t25jh96w3f7nvd2l85tdsr0000gn/T/electron-builder-SCsQZW/t-a0f6-1.p12 -k /var/folders/8r/_2t25jh96w3f7nvd2l85tdsr0000gn/T/electron-builder-SCsQZW/t-a0f6-0.keychain -T /usr/bin/codesign -T /usr/bin/p8364cf9ef03fd66a8b249b4bf565ed2c8c73e02a5f56b56a03a373f82f07d23e (sha256 hash) -P 12345
security: SecKeychainItemImport: Unknown format in import.
security: SecKeychainItemImport: Unknown format in import.

**Comment by VishwasShashidhar** [comment]
Suggest you upgrade electron-builder to some newer version and try again. 8.7.0 is quite old.
