### ISSUE TITLE
How can I add a app extension to a mac app

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1648]
* **Version**: latest

* **Target**: MAC/ZIP

We are writing an app extension that requires that it's placed in the Plugins folder inside our .app and also requires files to be placed in the Frameworks folder, is there any way to do this with electron builder?

**Comment by develar** [comment]
Using [extraFiles](https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraFiles).

See from/to syntax:

``
 [
   {
     "from": "path/to/source",
     "to": "Contents/Frameworks",
   }
 ]
```

`extraFiles` can be defined per-platform, e.g. in the `mac`.

**Comment by maczikasz** [comment]
Awesome, thanks I did not notice, only extraResources

**Comment by develar** [comment]
When you will have working solution, please paste here your final config and I will make article in the wiki like it was done for kernel exts (https://github.com/electron-userland/electron-builder/wiki/macOS-Kernel-Extensions).

**Comment by maczikasz** [comment]
Will do as soon as the ignore things are added, because at the moment its horribly hacky :)
