### ISSUE TITLE
Appx name changed

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1650]
* **Version**: 18.8.1

* **Target**: Appx, x86 (--ia32) build on x64

I just upgraded to 18.8.1 and the package naming seems to have changed for my build is failing. 
Previously my `--ia32` package was named `appname-version-ia32.appx` and the x64 package had no arch postfix. Now, it seems, the 32bit package ain't got no arch postfix, too. Didn't see this in the changelog so I guess this wasn't intended.

I build 32 and 64 bit packages - if the names collide I can't build both.

**Comment by develar** [comment]
Fixed, test for appx ia32 added. Will be released soon.
