### ISSUE TITLE
Shorter name of executable `electron-builder`

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#1656]
Why we need executable name `electron-builder`? Because `create-react-app` also has `build` task and it leads to confusion. Now you can use `electron-builder` instead of `build`. Name is too long? Yes — maybe soon `elb` will be added as alias, feel free suggest your variants.

Of course, `build` will be not removed due backward compatibility :)

**Comment by develar** [comment]
Do you like `elb`? Please vote using reactions 👍  or 👎 and if you don't like, please explain / suggest your variant.

**Comment by brandonhilkert** [comment]
`elb` is a common acronym used with AWS, which could confuse the situation? `ebuild`?

**Comment by pmoleri** [comment]
I think `electron-builder` is fine

**Comment by develar** [comment]
> ebuild?

Thanks, @brandonhilkert https://wiki.gentoo.org/wiki/Ebuild

**Comment by brandonhilkert** [comment]
@develar ah...probably always something then. Maybe it's not worth shortening. The trade-off doesn't seem worth the potential confusion. I vote keep it `electron-builder`.

**Comment by surajreddy** [comment]
I think `electron-builder` is fine as well. Other plugins like `electron-windows-store`, etc. use the full name and it's clear what's going on.

Especially if someone is using a lot of plugins and commands in their process, using the full name adds a lot of clarity.

**Comment by pronebird** [comment]
`electron-builder` is alright. There is no need to have it any other way.

**Comment by igor-lemon** [comment]
+1 for `electron-builder`

**Comment by black-snow** [comment]
+2½ for full name

**Comment by develar** [comment]
Thanks to all. Short named bin will be not added.
