### ISSUE TITLE
NSIS Windows Updates - Config

### ISSUE THREAD

**Issue by VishwasShashidhar** [electron-userland/electron-builder#1664]
* **Version**: 18.6.2

 
* **Electron Updater Version**: 2.1.2

* **Target**: Windows

1. I'm using electron-builder to create the windows unpacked build and then using the unpacked build to create an MSI with Advanced Installer.
2. And, I'm using NSIS for auto-updates which works perfectly except for the below caveats

- If my product is installed under C:\Program Files\Company\Product in the first place, after an NSIS update, the update is installed under C:\Program Files\Company and the C:\Program Files\Company\Product sub-directory is left as is, so, that's a duplicate.
- With advanced Installer, I have my product name as "Product-Electron" and the same is reflected in the control panel for uninstallation. Again, after an NSIS update is done, the name of the product is now changed to "Product-x.y.z" in the Control Panel.

Is there any config with the current electron-builder to address the above concerns?

TIA!

**Comment by VishwasShashidhar** [comment]
https://github.com/electron-userland/electron-builder/issues/1634

**Comment by develar** [comment]
>  after an NSIS update, the update is installed under C:\Program Files\Company and the C:\Program Files\Company\Product sub-directory is left as is, so, that's a duplicate.

Please try to use [menuCategory](https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-menuCategory). If it will not enough, special option can be added to specify custom installation path.

> Again, after an NSIS update is done, the name of the product is now changed to "Product-x.y.z" in the Control Panel.

No such option yet.

**Comment by VishwasShashidhar** [comment]
Thanks @develar, will look into it.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-uninstallDisplayName
