### ISSUE TITLE
Multiple targets not working via Programmatic API

### ISSUE THREAD

**Issue by ripexz** [electron-userland/electron-builder#1665]
* **Version**: 18.6.2

* **Target**: osx, windows, linux (tried variations of arch and target types, thats not the issue here)

The programmatic API docs shows an example with:
```
builder.build({
  targets: Platform.MAC.createTarget(),
  config: {
   "//": "build options, see https://goo.gl/ZhRfla"
  }
})
```

And it works perfectly fine for a single platform build, same for Linux and Windows.
However, whenever I try passing multiple targets, e.g.:
```
targets: [Platform.WINDOWS.createTarget('squirrel', Arch.ia32), Platform.LINUX.createTarget('appimage', Arch.ia32), Platform.MAC.createTarget()]
```
It throws an error:
```
electron-builder 18.6.2
[14:40:00] Error: Unknown platform: windows,[object Map]
    at Packager.createHelper (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/packager.ts:319:15)
```

Am I doing something wrong here or are multiple targets just not supported?

**Comment by develar** [comment]
Please try

```
builder.build({
  mac: ["default"],
  linux: ["appimage:ia32"],
  win: ["squirrel.windows:ia32]
  config: {
   "//": "build options, see https://goo.gl/ZhRfla"
  }
})
```

**Comment by ripexz** [comment]
Got a little further this time, initially got this:
```
electron-builder 18.6.2
No native production dependencies
Packaging for darwin x64 using electron 1.6.10 to dist/mac
Signing app (identity: Developer ID Application: TeamworkPM (ES2A6CKPMW))
Building macOS zip
Building DMG
Skip app dependencies rebuild because platform is different
Packaging for linux ia32 using electron 1.6.10 to dist/linux-ia32-unpacked
Building AppImage for arch ia32
Skip app dependencies rebuild because platform is different
Segmentation fault: 11
```

then removed `linux` from the list and got
```
electron-builder 18.6.2
No native production dependencies
Packaging for darwin x64 using electron 1.6.10 to dist/mac
Signing app (identity: Developer ID Application: TeamworkPM (ES2A6CKPMW))
Building macOS zip
Building DMG
Skip app dependencies rebuild because platform is different
[16:32:03] Error: Unknown target: squirrel.windows
    at createCommonTarget (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/targets/targetFactory.ts:82:11)
    at outDir (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/winPackager.ts:140:55)
    at mapper (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/targets/targetFactory.ts:49:16)
    at WinPackager.createTargets (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/winPackager.ts:140:9)
    at createTargets (/Users/paulius/Code/timer-app/node_modules/electron-builder/src/targets/targetFactory.ts:56:12)
    at /Users/paulius/Code/timer-app/node_modules/electron-builder/src/packager.ts:257:28
```

Also it seems to override the `config`, for example it built a Mac version with .dmg, .zip and yml update file... whereas in the config I am targeting `mas` and normally just passing `targets: Platform.MAC.createTarget()` would create a MAS build as expected.

Of course as a workaround I can just run this multiple times with different `targets` specified but it would be handy to do multiple builds at once.

**Comment by develar** [comment]
Yes, squirrel is a correct target name, fixed.

> Segmentation fault: 11

Better to build x64 AppImage :)

**Comment by ripexz** [comment]
> Also it seems to override the config, for example it built a Mac version with .dmg, .zip and yml update file... whereas in the config I am targeting mas and normally just passing targets: Platform.MAC.createTarget() would create a MAS build as expected.

I changed `mac: ["default"]` to `mac: ["mas"]` and it's building MAS versions now

> Yes, squirrel is a correct target name, fixed.

Yep, that seems to work now

> Better to build x64 AppImage :)

Ran without errors, but what about the poor 32-bit users? 😄

**Comment by bnku** [comment]
My solution:

```js
const config = { ... };
const targets = new Map()
    .set(Platform.LINUX, new Map())
    .set(Platform.WINDOWS, new Map());
    .set(Platform.MAC, new Map());

builder.build({
    targets,
    config,
})
```
