### ISSUE TITLE
The "portable" Windows target grabs the artifact name set by the "nsis" target

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1667]
* **Version**: 18.6.2

* **Target**: Windows portable

I have a `build.nsis.artifactName` property set, which is grabbed when I build the "nsis" target, however if I build the "portable" target, it also grabs the value of that nsis specific artifact name, which means I can't get different files when building both nsis and portable.

Could we support a different artifact name for Windows portable builds?

**Comment by jviotti** [comment]
Oh, looks like passing `build.portable.artifactName` actually works. Should this be added to the docs?

**Comment by develar** [comment]
Inheritance — portable - nsis - win - config.

Yes should be documented. Do you think that portable should not inherit nsis artifact?

**Comment by jviotti** [comment]
I see. The inheritance makes sense. I guess making it clear that that's the case should be more than enough :+1:
