### ISSUE TITLE
Using the electronDist uses a hard-link instead of copying the custom electron build directory

### ISSUE THREAD

**Issue by djpereira** [electron-userland/electron-builder#1670]
* **Version**: 18.6.2
* **Target**: darwin

When we use electron-builder with the "electronDist" option, the custom electron build gets copied over using "hard-links" instead of actually copying the content.

When you specify a custom electron build directory, `dirPackager.unpack` calls `electron-builder-util.copyDir` which uses hard-links by default.

The problem with this, is that as the content of the electron dist "copy" gets modified (icons, name, etc.) the original electronDist source folder "mirrors" the changes.

This is not an issue for each use case, but you definitely get into trouble very often, specially if you try to run electron-builder again.

I think that ideally we want to make an actual copy of the files each time, not a hard link.

This is why I had the problems mentioned in https://github.com/electron-userland/electron-builder/pull/1658

**Comment by develar** [comment]
Thanks for investigation, fixed.
