### ISSUE TITLE
ENOENT - appx - readInstalled.ts

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1671]
* **Version**: 19.2.2

* **Target**: appx

I tried to build my `ia32` version to verify that the appx name has the arch postfix again but it now fails with this:

```
> set CSC_KEY_PASSWORD=&&set CSC_LINK=%cd%/build/cert/xyz.pfx&&build --ia32
 
electron-builder 19.2.2
Using electron-builder.json5 configuration file
No native production dependencies
Packaging for win32 ia32 using electron 1.6.11 to dist\win-ia32-unpacked
 
... and 1 more
CSC_KEY_PASSWORD is not defined, empty password will be used
Signing xyz.exe (certificate file: "E:\xyz\build\cert\xyz.pfx")
Error: ENOENT: no such file or directory, open 'E:\xyz\app\package.json'
    at E:\xyz\node_modules\electron-builder\src\readInstalled.ts:36:21
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1755:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at _readInstalled (E:\xyz\node_modules\electron-builder\out\readInstalled.js:101:22)
    at E:\xyz\node_modules\electron-builder\src\readInstalled.ts:22:21
    at Generator.next (<anonymous>)
    ...
```

In fact there is not `package.json` inside `app` and there never was :| It's one level up.

**Comment by black-snow** [comment]
@develar works again with 19.2.7, thanks

Say, is there some way to hook into the build process? I need to add some more assets and pri-files to the appx. Currently I unpack the appx that's generated, genrate/add my files, pack it up again and sign it again. It works perfectly but it could be nicer.

**Comment by develar** [comment]
@black-snow Stay tuned — https://github.com/electron-userland/electron-builder/pull/1657 will be merged in 2 days :)

**Comment by black-snow** [comment]
Whoa, super awesome. Didn't see this PR.
