### ISSUE TITLE
Support setting boolean properties with -c.extraMetadata

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1674]
* **Version**: 18.6.2

* **Target**: debian

I need to set a boolean value using `--extraMetadata`, however it seems that this option only supports strings, therefore something like:

```
--extraMetadata.updates.enabled=false
```

Results in:

```json
{
    "updates": {
        "enabled": "false"
    }
}
```

I haven't tested it, but I suspect the same issue applies to numbers.

Of course I can workaround this limitation from my application code, however I wonder if we could add support for values other than strings.

Some thoughts:

- We could check if the value equals `false`, `true`, or contains only numbers and coerce appropriately, however there might be cases where you really need to set something like `"false"`
- Maybe there can be `--extraMetadataBoolean` and `--extraMetadataNumber` options?

**Comment by develar** [comment]
19.4.0 allows you to specify `extraMetadata` in the config. Is it solution for you?

**Comment by develar** [comment]
Fixed in 19.7.0

**Comment by jviotti** [comment]
Sorry for the delay. I somehow missed the previous comment. The value of the variable I want to inject depends on certain make options, so having a configuration option would not be ideal.

> Fixed in 19.7.0

What was the fix? Can you point me to a commit? I checked the CHANGELOG and the git history, but couldn't find anything relevant.

**Comment by develar** [comment]
> What was the fix? 

 new Ajv({allErrors: true, coerceTypes: true})

`coerceTypes` was set to `true`.

**Comment by jviotti** [comment]
I just tested 19.7.0, but `--extraMetadata.updates.enabled=false` still results in a `'false'` string.

**Comment by develar** [comment]
`-c.extraMetadata.updates.enabled`

**Comment by develar** [comment]
latest release is 19.8.0


`--extraMetadata` depreciation was not yet announced.

**Comment by jviotti** [comment]
I upgraded to 19.8.0 and ran `--config.extraMetadata.updates.enabled` but still the same result.

**Comment by develar** [comment]
Got it. `extraMetadata` typed as `any` and, so, not possible to convert. Well... is it ok for to specify it not in the CLI, but in the config file?

**Comment by develar** [comment]
19.9.1

**Comment by jviotti** [comment]
> Well... is it ok for to specify it not in the CLI, but in the config file?

My particular use case is to disable auto updates on Debian and RPM packages (that we publish to Bintray repositories). Is there a better way to solve this with `electron-publish`?

**Comment by develar** [comment]
1. It is fixed. We just convert true/false strings to bool.
2. extraMetadata will not work in this case because we build app for platform and then pack it into distributable formats. So, deb/rpm will use the same source dir.

Currently, I don't see way except somehow in the runtime detect. But — in any case auto update is not supported on Linux yet and will be supported only for AppImage. And AppImage sets some special ens, so, you can detect that app is running from AppImage.

**Comment by lurch** [comment]
Minor correction to @jviotti 's previous comment - we're not actually auto-updating at the moment, but checking for a newer version of the app being available on the server than is running locally, and presenting a pop-up to the user if so. But obviously if the user has installed Etcher through some package-manager (like deb or rpm) we expect them to be updating through that, and we don't want to show them a pop-up that a newer version is available for manual download.

> It is fixed. We just convert true/false strings to bool.

Thanks :)

**Comment by develar** [comment]
@lurch So, use `process.env.APPIMAGE != null` to check that app running using AppImage.

**Comment by timo955** [comment]
9e772313e29de77f9c44eb18ab0f8726d815fd7a
