### ISSUE TITLE
Document the necessary icon sizes for linux

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1679]
* **Version**: 18.6.2

* **Target**: debian

The linux docs mention that the `icon` property should point to a directory containing PNGs of different dimensions. What are the required dimensions? Can that be documented?

**Comment by black-snow** [comment]
Seems like 512x512 (https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/targets/LinuxTargetHelper.ts#L145) - but valid point, should be mentioned somewhere in the docs.

**Comment by develar** [comment]
I am working on https://github.com/electron-userland/electrify New wiki page will be not added. Our plan to promote this app when it will be ready. And, probably, publish web version of app to electron.build web site. No one read docs — interactive wizard is required.

**Comment by black-snow** [comment]
Sounds interesting. I'm not with you concerning this point, though. People (especially devs) do read docs. I do. jviotti does (obviously).

**Comment by develar** [comment]
Ok, I will add `Icons` wiki page (since electron.build site has foggy future.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Icons
