### ISSUE TITLE
Windows: No notification in case an error occurs during update signature verification

### ISSUE THREAD

**Issue by MariaDima** [electron-userland/electron-builder#1680]
* **Version**: 19.3.0

* **Target**: Windows

In case of an error during the execution of the command "Get-AuthenticodeSignature '${tempUpdateFile}' | ConvertTo-Json -Compress", no error is thrown to the upper layers.

An error could occur (for example) if either the command "Get-AuthenticodeSignature" or "ConvertTo-Json" cannot be executed.

**Comment by MariaDima** [comment]
@develar we face a case where a user uses Windows 7 Enterprise with SP1.
The installed powershell version is 2.
The "ConvertTo-Json" command is supported by powershell v3 and higher.

Of course we can tell the user to install the latest powershell, but do you think it's possible to enhance the code so that it performs a check on whether this command is supported or not?
If it's supported the code with be executed as it is.
If not we drawback to a simpler execution (without match printing, or by extracting some basic info using the Get-AuthenticodeSignature).

**Comment by develar** [comment]
@MariaDima I think, for users of so old OS, we can simply disable this check and do not worry. Could you please prepare PR if agree?

**Comment by MariaDima** [comment]
I think that our customers won't like it from security perspective.
To be honest, I would prefer to guide them for upgrading powershell, rather than bypass the verification.
Let me check and if needed I'll prepare a PR.

Thanks!

**Comment by MariaDima** [comment]
Just to be sure, you suggest disabling the verification check completely, right?

**Comment by develar** [comment]
If you user decided to use unsecured and not maintained ( End of mainstream support — January 13, 2015 ) windows versions — yes.
