### ISSUE TITLE
Generate all icon assets from single image

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#1682]
With the improved AppX support, there are now a lot of different icon assets required. 

It would be great if electron-builder generated all the assets from a single SVG or PNG file. I've been looking at using [electron-icon-maker](https://www.npmjs.com/package/electron-icon-maker) to do this although it doesn't yet support AppX and it appears most of the work is done with [icon-gen](https://www.npmjs.com/package/icon-gen).

**Comment by develar** [comment]
Our official statement was and, in general, "is" — it is easy to prepare assets for each platform once and then do not slowdown build or think that someday your app will be with "broken" or not good quality icon.

But your point is valid and, as it is match our mission, feature accepted and will be implemented. Not quite clear is AppX will be supported (cc @surajreddy — is it possible to generate squire icons for AppX easily?).

**Comment by timfish** [comment]
electron-builder could generate the icons in the default paths (or relative to the yml config being run) so the user can check them in or gitignore if they want them generated every time? This would at least encourage best practices but make it very simple to get started.

**Comment by develar** [comment]
No, it is better to generate it on the fly. But good idea — additional subcommand will be added to generate icons in addition to generation on the fly.

**Comment by surajreddy** [comment]
@develar @timfish this is possible, but a few notes:
1. You don't need scaled assets. If you don't include targetsize, etc., you only need 4 assets (`StoreLogo.png`, `Square150x150Logo.png`, `Wide310x150Logo.png`, `Square44x44Logo.png`)

2. There are some plugins like this that enables creating these assets easier: https://www.npmjs.com/package/svg2uwptiles 

However, automatic asset generation like this is not ideal for everyone, because the logo by itself can look really bad in the splash screen and start tile areas. But like @develar mentioned, having this as an additional subcommand is a good idea.

**Comment by surajreddy** [comment]
Also, Visual Studio Community Edition has a tool that generates assets for you. (You can get to it by creating a blank visual studio uwp app project, and editing the AppXManifest file)

^ This is just an extra link for those who want to create their icons manually, it's not easy to automate this.

**Comment by black-snow** [comment]
VS2017 has the asset tool built-in I think. For earlier versions there's [this](https://marketplace.visualstudio.com/items?itemName=shenchauhan.UWPTileGenerator).

**Comment by develar** [comment]
`jimp` was initially rejected because quality of images is very important. Not clear is it still actual.

**Comment by timfish** [comment]
Its also worth noting that for my application at least, I have
- Application icon
- Variation used for `fileAssociations` 

So it would be great if anywhere the default icon can be overridden, they can be generated from SVG/PNG files too. 😄

**Comment by black-snow** [comment]
The generation was appx specific whereas `fileAssociations` work x-platform (am I right?). I don't think there's much need for *creating* other icons within the build flow.

I'm not sure I understood what you're asking for. You should be able to set custom icons for `fileAssociations`. Why would you want to *generate* them? There isn't a kajillion different sizes, scales and other versions for them, right?

**Comment by timfish** [comment]
[electron-icon-maker](https://www.npmjs.com/package/electron-icon-maker) currently generates icons for Windows/Linux/Mac so when opening this issue I was suggesting it covers generating app icons for ALL the platforms from a single SVG/PNG file. That means from a single file it will generate `.ico`, `.icns`, multiple `XxY.png`'s for Linux and multiple `XxY.png`'s for AppX where required.

`fileAssociations.icon` requires both `.ico`, `.icns` so the same code which generates the above could work here too...

**Comment by develar** [comment]
Upcoming 19.54.0:

* `icns` generation from icon set (dir with PNG files). At least 512x512 is required.
* `icns` generation from one PNG file. At least 512x512 is required.

For Linux no icon set generation — Linux Zoo accepts one PNG file. One improvement here — now you can specify one PNG file instead of icon set.

**Comment by haoxi911** [comment]
Hello everyone, I found the free Windows app [App Icon Maker](https://apps.microsoft.com/detail/9n3wsnpkrw6g?hl=en-US&gl=US) works well on generating different icons from the same image for APPX package. Is there a better way to do this in 2024?

![image](https://github.com/electron-userland/electron-builder/assets/12502170/db4bf470-f80a-4ca6-85c6-c5b234522fa5)
