### ISSUE TITLE
Node-notifier not getting fired after packaging with electron builder

### ISSUE THREAD

**Issue by suku-h** [electron-userland/electron-builder#1683]
17.8.0

 Windows >= 7

Node notifier is not getting fired after being packaged. Node-Notifier needs to be unpacked as suggested [here](https://www.npmjs.com/package/node-notifier#within-electron-packaging). I believe I am making a mistake in the package.json while executing this process when using electron-builder. 

```json
 "build": {
    "appId": "NotiTest",
    "asarUnpack": [
      "./app/node_modules/node-notifier/vendor/**"
    ],
    "win": {
      "icon": "./build/images/app-icon.ico",
      "target": "nsis"
    },
    "nsis": {
      "oneClick": true,
      "perMachine": false,
      "allowElevation": false
    }
  },
  "scripts": {
    "start": "NODE_ENV=development ./node_modules/.bin/electron app",
    "build": "NODE_ENV=production ./node_modules/.bin/webpack",
    "watch": "NODE_ENV=development ./node_modules/.bin/webpack-dev-server --hot --inline",
    "dist": "sh build.sh && build -w --x64 --ia32"
 }
```

Can you suggest what is the correct method?

**Comment by develar** [comment]
Do you see `asar.unpacked` dir in the resources?

**Comment by suku-h** [comment]
yes. I can see it

**Comment by develar** [comment]
Please try to use https://www.npmjs.com/package/hazardous

**Comment by suku-h** [comment]
Hazardous didn't help.
I added the following code to the app.js
require('hazardous');
const path = require('path');
const notifierUnpacked = path.join(__dirname, 'app.asar.unpacked/node_modules/node-notifier/vendor');

**Comment by develar** [comment]
Please zip project and send me if possible. Maybe will be a chance that I will inspect it today.
