### ISSUE TITLE
appx manifest - supported languages

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1684]
It's great to have some improved appx support for I can drop a lot of custom scripts. Now there's one thing I'm still missing and that's support for listing supported languages in the appx manifest. Currently `en-US` is the default one and that can't be changed easily. (I'm unpacking the appx, changing the manifest, packing, signing.)

See: https://docs.microsoft.com/en-us/windows/uwp/globalizing/manage-language-and-region#specify-the-supported-languages-in-the-apps-manifest

I'd like to state the supported languages in my build config like:

```json
"appx": {
  "publisher": "...",
  "languages": ["en-US", "de-DE", "FR-fr"]
}
```

Where the first one's the default language. It should default to `en-US`.

I'll try to file a PR if you aren't faster ;)

**Comment by develar** [comment]
> I'll try to file a PR if you aren't faster ;)

I have assigned you to fix it ;)

**Comment by develar** [comment]
Our test suite currently doesn't unpack appx and doesn't verify manifest — test will be not easy to write.

**Comment by black-snow** [comment]
Aight.
Shouldn't be too hard if we have `makeappx.exe` available unless I'm missing something. Haven't looked at the tests yet.

1. Unpack appx or do this before packing
2. Regex check (simple) or throw some xml parsing at it (overkill).

**Comment by develar** [comment]
@black-snow In case of Info.plist we remove some always changed fields and then toMatchSnapshot(). Will be cool if you will add such functionality to test appx.

**Comment by black-snow** [comment]
Thanks for the hint.

**Comment by develar** [comment]
BTW, so disappointing that we cannot run makeappx on mac/linux :(

**Comment by black-snow** [comment]
This is the first time I'm actually doing something in typescript. [Implementation ](https://github.com/black-snow/electron-builder/commit/9ce1497f59fcd1d77dd501807443ec833cbd45ee) should be done.

After a quick glimpse at jest snapshot testing I'm really confused. Where are those snapshots? How would I add one? How would that snapshot look like? * Serialized* manifest? appx?
Also I'm confused by the `appx` test. What does it do? It's calling `app` wich is basically `assertPack` which doesn't even generate an appx, does it? There's no easy way to hook into single build steps for appx, eh? Guess you were right ...

> test will be not easy to write.

**Comment by develar** [comment]
Jest automatically creates snapshot file on first run. Appx test check that appx produces some files, but appx works only on Windows. 

I will grab your changes and will commit :)

**Comment by develar** [comment]
@black-snow Thanks!

**Comment by black-snow** [comment]
@develar You're welcome.
I'll be writing my thesis the next couple weeks so, sadly, I won't be looking into appx tests.
