### ISSUE TITLE
Runtime error for a build on window feat. electron-compile (forge)

### ISSUE THREAD

**Issue by alexstrat** [electron-userland/electron-builder#1686]
* **Version**: 19.4.2

Trying to build en electron-forge (electron-compile) project with builder on Windows. Build without error but the .exe fails to open with this error:

`SyntaxError: unexpected token import`

<img width="573" alt="screenshot 2017-06-17 02 12 41" src="https://user-images.githubusercontent.com/687961/27248345-79852d0e-5302-11e7-9994-8be03d39c464.png">

I prepared a reproduction repo here: https://github.com/getstation/forge-builder-example The screenshot is coming from this example.

```
# on windows
git clone https://github.com/getstation/forge-builder-example
npm install .
npm run pack
# open the .exe in /dist
```

**Comment by alexstrat** [comment]
Looking at the difference in the asar between Mac and Windows, it looks like the `.cache` on Windows is not populated correctly:
<img width="1082" alt="screenshot 2017-06-19 10 24 58" src="https://user-images.githubusercontent.com/687961/27276040-1d057ff0-54da-11e7-9f22-4802e8f58a16.png">

Whereas on mac (where I see no error):
<img width="373" alt="screenshot 2017-06-19 10 28 15" src="https://user-images.githubusercontent.com/687961/27276054-2830afbc-54da-11e7-9bad-854aec556203.png">

**Comment by alexstrat** [comment]
@develar have you had a chance to investigate this one?

If not, how can I help you? Do you have a hint where I should start looking?

**Comment by develar** [comment]
19.6.3
