### ISSUE TITLE
afterPack callback is not called at the same time for windows & mac.

### ISSUE THREAD

**Issue by DxCx** [electron-userland/electron-builder#1689]
* **Version**: 19.4.2

* **Target**: mac(dmg+zip) + windows(nsis)

Hey,
I'm using the `afterPack` option in order to do some modifications in the package before we are doing the actual shipping.
but it looks like the same callback is called on a different time in build pipe on windows and mac.
code signing on windows happens before `afterPack` and on mac after `afterPack`.

on windows it is called at `postInitApp` (https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/winPackager.ts#L271)
on mac it is called right after `doPack` (https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/macPackager.ts#L111)
please note that doPack is the one that actually calls `postInitApp` (https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/platformPackager.ts#L194)
and then `afterPack` at the end of it.

IMO, sign should not be inside packing stage but right after it (just like `mac`)
anyway it looks wired it's not the same.

**Comment by DxCx** [comment]
hey @develar any suggestions about this one?

**Comment by develar** [comment]
Fixed. After CI run, will be pushed to upstream and released (~3 hours).

**Comment by DxCx** [comment]
neat! thank you @develar !

**Comment by DxCx** [comment]
Alright @develar i was able to verify it is working as intended on version 19.11.1.
thanks alot! 👍
