### ISSUE TITLE
How to set the artifact version manually? 

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#1691]
* **Version**: 19.4.2

* **Target**: dmg

I've read the documentation and am trying to follow it, but am clearly doing something wrong.
Here is a *partial* package.json
```
{
  "name": "test",
  "version": "0.1.1",
  "build": {
    "appId": "me.xx.yy",
    "productName": "test",
    "files": [
      "dist/",
      "node_modules/",
      "package.json"
    ],
    "mac": {
      "icon": "build/icon.icns"
    },
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
  },
  "devDependencies": {
    "electron-builder": "^19.4.2"
  }
}

```

```
npm build
...
ls -1 dist dist/mac
test-0.0.0-mac.zip
test-0.0.0.dmg

dist/mac
test.app
```

I am trying to get it to read the package.json version, which is 0.1.1

What am I doing wrong?

**Comment by brandonmp** [comment]
don't have an answer but I'm hitting the same problem, with both dmg and exe targets.

I tried setting `build.buildVersion`, and while it doesn't throw any errors or anything, it doesn't affect the resultant versioning.

**Comment by brandonmp** [comment]
i figured this out in my use case. are you using [2-`package.json` structure](https://github.com/electron-userland/electron-builder/wiki/Two-package.json-Structure)? 

I am, and I couldn't get builder to acknowledge my version in `<projectRoot>/package.json`, neither for artifact version nor for automatic channel inference (eg `1.0.0-alpha.1` makes the channel `alpha` automatically).

However, once I set the version number in `<projectRoot>/app/package.json`, everything worked as expected.

hth

**Comment by rr326** [comment]
Aha! So obvious in retrospect! Thank you!

**Comment by rr326** [comment]
FYI - if you want to have the version number bump automatically and you are not using a CI package, you can do:
`"build": "cd app && npm version patch && cd .. &&  npm run pack && build"`
