### ISSUE TITLE
Publishing .dmg and .zip to GitHub not working

### ISSUE THREAD

**Issue by stevenfabre** [electron-userland/electron-builder#1695]
* **Version**:  17.1.1

* **Target**:  Mac

Hi there — really enjoying the module, made my life so much easier.

One thing doesn't seem to be working though. When I run `npm run release` which basically runs the following `npm run build && build --publish always`, everything seems to be working until it tries to "Publish to GitHub". The release gets created properly, however the DMG and ZIP files do get stuck at 0% and aren't being uploaded. After 20 or 30 seconds I get the following error:

`Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:804:14)
From previous event:
    at CancellationToken.createPromise (/Users/stevenfabre/Git/gif-mock/node_modules/electron-builder/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at NodeHttpExecutor.doApiRequest (/Users/stevenfabre/Git/gif-mock/node_modules/electron-builder-util/src/nodeHttpExecutor.ts:51:30)
`

Do you guys have any idea what I'm doing wrong? My work around for now is to upload the ZIP and DMG files manually in the release, which isn't ideal.

Thanks

**Comment by tafax** [comment]
Exactly the same here.

**Comment by blahah** [comment]
I'm not seeing the error by my TravisCI builds for macOS stall at this point until the CI times out:

```
Publishing to Github (owner: codeforscience, project: sciencefair, version: 1.0.0-beta11)
sciencefair-1.0.0-beta11.dmg to GitHubsciencefair-1.0.0-beta11.dmg to GitHubsciencefair-1.0.0-beta11.dmg to GitHub
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by blahah** [comment]
I just tested this locally on macOS and the process stalled after DMG upload completed, as it does on CI.

@develar I'm wondering if it could be related to the changes here: https://github.com/electron-userland/electron-builder/commit/5e0a646250def577dccec7eee31d915cccc61814#diff-92bda2c005cb7d5149c7c8f48a99ea87

**Comment by develar** [comment]
Hmmm works for me on CI.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder:* ` and attach log of the terminal output.

Please also use next version of electron-builder or at least latest. And be sure that you use node 8 and Xcode 8.3.3 on travis

**Comment by develar** [comment]
https://travis-ci.org/develar/onshape-desktop-shell/jobs/245894336

Travis file: https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml

**Comment by blahah** [comment]
@develar I can confirm that the stalling issue is node7 v node8 - my builds [are now uploading fine](https://travis-ci.org/codeforscience/sciencefair/jobs/245992489). Thanks for your help :)

However, I now think I've hijacked this issue and the thing @stevenfabre reported is different. Perhaps upgrading to latest version and setup will fix that too.
