### ISSUE TITLE
Possible to update to a GitHub release marked pre-release?

### ISSUE THREAD

**Issue by eanders-MS** [electron-userland/electron-builder#1696]
* **Version**: 19.2.7

* **Target**: windows/nsis

Hello, I would like to be able to selectively allow updates to new releases on GitHub marked pre-release (enable by passing a flag on the command line). Is this possible with electron-builder's autoUpdater? This will allow us to test the auto-update process to a new release before making it generally available. The process of making it generally available would be to simply remove the pre-release flag.

**Comment by brandonmp** [comment]
I don't know much about this issue since I use s3 for publishing, [but i saw this in the docs](https://github.com/electron-userland/electron-builder/blob/86af4cd9da1c289c503cb062d5cfd9cb42983f28/docs/Auto%20Update.md#appupdater--internaleventemitter)--is it helpful?

> `allowPrerelease` = `false` Boolean - GitHub provider only. Whether to allow update to pre-release versions. Defaults to true if application version contains prerelease components (e.g. 0.12.1-alpha.1, here alpha is a prerelease component), otherwise false.

**Comment by eanders-MS** [comment]
Huh, I was trying that the other day and it wasn't working for me. But today it works as you describe. Probably user error. Will try to get a repro if I see it again.
Thanks!
