### ISSUE TITLE
mac: Ignore Contents/PlugIns

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1699]
* **Version**: latest

* **Target**: dmg

I need to ignore a file when signing my application, at the moment I cannot do this with electron builder, I checked the code and noticed that it uses electron-osx-sign. That has a property called ignore, could you pls expose this as an option for MAC builds?

Thanks

**Comment by develar** [comment]
19.6.2

**Comment by maczikasz** [comment]
awesome thanks very mcuh
