### ISSUE TITLE
[idea] Rely on version from root package.json in 2-package.json structure

### ISSUE THREAD

**Issue by brandonmp** [electron-userland/electron-builder#1700]
I mentioned this in #1691, but it looks like for `version` info in 2-package.json structures, `builder` is looking at the nested one, ie `app/package.json`

not sure if it's a bug or as-intended, but it's counter-intuitive so I wanted to make a note here. Maybe just a simple docs update is sufficient here.

**Comment by rr326** [comment]
+1 on the docs. Maybe even a little section of which fields should be in which package.json. After @brandonmp figured this out, I did some experimentation and realized all the meta fields should be in `app/package.json` It would have been helpful to know. Thanks.
