### ISSUE TITLE
no such file or directory, open 'c:\testing\electron\node_modules\sqlite3\undefined'

### ISSUE THREAD

**Issue by azurinko** [electron-userland/electron-builder#1703]
electron-builder 19.5.1

Failed to execute 'C:\Program Files\nodejs\node.exe c:\testing\electron\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=c:\testing\electron\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=c:\testing\electron\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64 --python=C:\Python27\python.exe --msvs_version=2017' 

https://pastebin.com/zKvFRS9y

I just installed sqlite, used electron-rebuild on it and added it to code, I would like to pack it, but this is what happens, no googling did helped.

**Comment by develar** [comment]
Next version of electron-builder will not force build from sources by default. I hope, it helps.
