### ISSUE TITLE
QUESTION: how to copy a .dll near the .exe file ?

### ISSUE THREAD

**Issue by RilRil** [electron-userland/electron-builder#1708]
* **Version**:  13.3

* **Target**:  nsis

Hello, I am building a windows installer (nsis), and I would like to embed a .dll file with it. I need it to be near the .exe file (near ffmpeg.dll, node.dll, etc... )

Is there an easy way to achieve this ?

thanks !

**Comment by develar** [comment]
1. Use latest release.
2. https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraResources

**Comment by RilRil** [comment]
works perfectly ! thanks
