### ISSUE TITLE
Cannot downgrade installed pkg

### ISSUE THREAD

**Issue by p120ph37** [electron-userland/electron-builder#1711]
* **Version**: 19.5.1
* **Target**: pkg

`BundleIsVersionChecked` seems to default to `true`.  It would be nice to be able to override this default to allow for downgradable pkg files.

See: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pkgbuild.1.html

**Comment by p120ph37** [comment]
After doing some more research and testing, it seems that the `BundleIsVersionChecked` option that is mentioned in the `pkgbuild` manpage is only applicable when using `pkgbuild` in its stand-alone `--root` form, and not applicable for the `--component` form as used in `electron-builder`.

The effect of this option is to populate or clear the contents of the `<bundle-version>` tag in the `PackageInfo` which is contained in the inner `pkg`.  As far as I can tell, there doesn't seem to be a command-line option to `pkgbuild --component` which directly controls this tag.

If I manually use `pkgutil --expand`, edit the inner `PackageInfo` to remove the contents of the `<bundle-version>` tag, and then use `pkgutil --flatten` to repackage, the resulting installer is capable of downgrading an installation.

One really confusing "feature" is that the installer does not give any indication when an attempted downgrade is prevented - it still displays the success screen, and the only way to tell that the downgrade was not actually applied is to examine the installed application itself.

**Comment by develar** [comment]
Not clear right now how to fix it.

**Comment by p120ph37** [comment]
Yeah, I'm not sure how to fix it properly either.  It's kind of an unusual use-case.  I think Apple expects people who might need this feature to use the `pkgbuild --root` form which accepts the `BundleIsVersionChecked` option in the plist file.

I currently have a fixup script that expands the pkg, empties the `<bundle-version>` tag in the inner `PackageInfo` and re-flattens.  If the `pkg` target becomes complex enough someday that it needs to do an expand/flatten for other reasons, this would be a good feature to include at that point, but I can't see any way to include it cleanly in the current build process.

And maybe Apple will add another command-line option to `pkgbuild --component` someday to control this?  (heh, I doubt it).

**Comment by develar** [comment]
Still not moved to backlog — it not windows, so, probably I will return to this task when other urgent issues will be fixed.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by p120ph37** [comment]
It looks to me like this has been fixed by now.  The `isVersionChecked` option appears to be working correctly.
