### ISSUE TITLE
Building a DMG takes ages

### ISSUE THREAD

**Issue by derwaldgeist** [electron-userland/electron-builder#1714]
Version: "next"
Target: macOS El Capitan

The build process for the DMG takes a very long time until it returns. In my case, the total time is 316s, although the resulting DMG is just 90MB. Interestingly, the DMG is ready long before the build finishes. If I just double-click it, it works as expected. Just the build process waits much longer until it returns to the terminal prompt. What may be the reason for this behavior?

**Comment by develar** [comment]
Are you on macOS Sierra?

**Comment by Meadowcottage** [comment]
Also getting this issue. Build process can take an extremely long time.
Same issue in both MacOS Sierra and MacOS High Sierra (Beta).

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by derwaldgeist** [comment]
Hi, I am on El Capitan.

**Comment by develar** [comment]
Please update to sierra (it will be required soon to produce signed DMG).

In any case please attach debug log.

**Comment by develar** [comment]
Reopen if log provided.

**Comment by derwaldgeist** [comment]
Here is the log. Not very informative, though.

Upgrading to Sierra is always an issue for me, since every new macOS version tends to break some music making app.

```
yarn dist v0.24.6
$ build 
Rebuilding native production dependencies for darwin:x64
Rebuilding native dependency midi
Packaging for darwin x64 using electron 1.7.2 to dist/mac
Signing app (identity: Developer ID Application: xxx (yyy))
Building macOS zip
Building DMG
✨  Done in 390.56s.
```

**Comment by derwaldgeist** [comment]
PS: I can't reopen this.

**Comment by develar** [comment]
@derwaldgeist Please set env DEBUG=electron-builder

**Comment by develar** [comment]
`DEBUG=electron-builder yarn dist`

**Comment by sivaramsi** [comment]
It got stuck here am using high sierra stable, 
`Building DMG
  electron-builder Spawning /Users/sivaramsi/work/localsync/localsync-electron/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/sivaramsi/work/localsync/localsync-electron/dist/localsync-0.1.0-mac.zip localsync.app +54s
  electron-builder cwd: /Users/sivaramsi/work/localsync/localsync-electron/dist/mac +0ms
  electron-builder Spawning hdiutil create -srcfolder /private/var/folders/wd/v7ffn4fs5vsdht83g6k8w9b00000gn/T/temp-files-v8ysnX/1-dmg/.background -srcfolder /Users/sivaramsi/work/localsync/localsync-electron/dist/mac/localsync.app -volname localsync 0.1.0 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /private/var/folders/wd/v7ffn4fs5vsdht83g6k8w9b00000gn/T/temp-files-v8ysnX/0.dmg +47ms`

**Comment by develar** [comment]
@sivaramsi Please use 19.31.1

**Comment by derwaldgeist** [comment]
I now have the situation that the DMG creation process won't finish at all. It's got stuck after creating the Zip for hours; I even let it run over night, and it didn't return to the command prompt. Logs attached.

[logs.txt](https://github.com/electron-userland/electron-builder/files/1887450/logs.txt)

**Comment by derwaldgeist** [comment]
Additional info: I read in another thread, that this behaviour was observed when the Firebase Admin API was included, which is the case in my app.

**Comment by derwaldgeist** [comment]
Same problem with 20.8.1. I now removed the Firebase Admin API `"firebase-admin": "^5.5.1"`, the problem goes away and also signing is fast again. So I guess the build process has a problem with libraries that contain a large number of files?

**Comment by twigs67** [comment]
This is happening for me as well, but I'm using Travis-Ci to do the build and the build alone takes upwards of 12 minutes each time. This is after the app has been notorized.

Has anyone found a solution to this? I'm attempting to use travis_wait to extend the timeout period, but I'd like to find a better solution.

**Comment by akashnimare** [comment]
My build process is just stuck on `signing..` and it takes a few hours to build. Is this normal? I'm on `v20.43.2`.

**Comment by derwaldgeist** [comment]
@akashnimare I realized that this especially happens if you have large 3rd party libraries, like in the Firebase case.

**Comment by akashnimare** [comment]
Hmm, I doubt it since it used to work well in previous versions of electron-builder. I'm recently facing these build issues.

**Comment by filipponova** [comment]
I have the same problem with bitbucket pipeline self hosted runner. It takes 12/15 minutes.

`
  • electron-builder  version=23.6.0 os=22.3.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/sre-team/atlassian-bitbucket-pipelines-runner/temp/997ae5b3-a202-568d-a4e2-5fcd3a3bf058/build/build
  • packaging       platform=darwin arch=x64 electron=22.2.0 appOutDir=dist/mac
  • signing         file=dist/mac/TestReachApp.app identityName=Developer ID Application: <XPTO> (xpto) identityHash=XPTO provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/XPTOAppSetup.zip
  • building        target=DMG arch=x64 file=dist/XPTOAppSetup.dmg
  • building block map  blockMapFile=dist/XPTOAppSetup.dmg.blockmap
  • building block map  blockMapFile=dist/XPTOSetup.zip.blockmap
  execution time: 14m 17s
`
