### ISSUE TITLE
Unable to specify multiple paths for electronDist

### ISSUE THREAD

**Issue by eanders-MS** [electron-userland/electron-builder#1716]
* **Version**: 19.6.1 

* **Target**: Windows

I'm using electron-builder with a custom build of Electron. When building my NSIS installer for Windows, I need to be able to specify `electronDist` for both `ia32` and `win64` architectures, since NSIS packages both architectures in a single installer. It seems that I cannot specify `electronDist` per-architecture. Is there a way to do this?

**Comment by eanders-MS** [comment]
I have a local folder with electron builds zipped. Would it be possible to point electron-builder to this base folder and have it pick the right platform & target?
![image](https://user-images.githubusercontent.com/12176807/27408188-55947ea4-5690-11e7-9c33-76c57966aeb3.png)

**Comment by eanders-MS** [comment]
I found a solution. I can configure electron-download to use a mirror and/or local cache.

**Comment by develar** [comment]
Request is reasonable, reopened.

**Comment by develar** [comment]
> I can configure electron-download to use a mirror and/or local cache.

Using electronDownload option.
