### ISSUE TITLE
Code-signing Node.js add-ons on Windows

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1723]
What are your thoughts on code-signing `*.node` files on Windows?

See https://github.com/resin-io/etcher/issues/1519. This is not the first time we encounter an anti-virus software that detects a `*.node` file as malicious. We've been manually asking these companies to whitelist such files, however code-signing could solve the problem entirely.

I tried manually code-signing add-ons with `signtool sign` and they load fine.

**Comment by develar** [comment]
Why do you unpack node files? It works in the asar.

**Comment by develar** [comment]
Feature will be implemented in several days.

**Comment by jviotti** [comment]
> Why do you unpack node files? It works in the asar.

Oh, I didn't know this was possible! Thanks a lot for the advice!

**Comment by develar** [comment]
To be check — is electron unpack it on the fly or not. Anyway — trust electron-builder. Do not disable smart unpack without reason and corresponding issue in th electron-builder project :)

**Comment by develar** [comment]
When even one file is unpacked, the whole module cannot be packed into asar. So, you should unpack only when it is really required.

**Comment by jviotti** [comment]
See https://github.com/electron-userland/electron-builder/issues/1738. Looks like `electron-builder` unpacks the whole `lzma-native` when smartUnpack is enabled.
