### ISSUE TITLE
AppImage artifact name does not use `artifactName` template

### ISSUE THREAD

**Issue by p120ph37** [electron-userland/electron-builder#1726]
* **Version**: 19.6.0
* **Target**: AppImage

The `AppImage` target uses the `computeSafeArtifactName` method to generate the output artifact name.  This method uses a hard-coded template string of `"${name}-${version}-${arch}.${ext}"` rather than using the configured `artifactName` from `package.json`.

**Comment by develar** [comment]
Yeah, it is what I don't want do because it violates Linux convention. Ok.... #775

**Comment by p120ph37** [comment]
My `artifactName` template is set to `${name}-${version}.${ext}`, so it doesn't suffer the spaces-in-name bug.  One possible (drastic) solution would be to change the top-level default value to `${name}-${version}-${arch}.${ext}`, but allow overrides.  Another possible solution would be to have a localized `artifactName` parameter that does not inherit from the global default, and can be overriding within the `pkg` target config.

**Comment by develar** [comment]
Fixed in 19.7.3.
