### ISSUE TITLE
electron.app.relaunch doesn't work inside AppImage

### ISSUE THREAD

**Issue by p120ph37** [electron-userland/electron-builder#1727]
* **Version**: 19.6.0
* **Target**: AppImage

Calling `electron.app.relaunch()` from within an AppImage does not properly relaunch the application upon `electron.app.quit()`.  This is true both for the no-argument form of `relaunch()`, as well as if an `execPath` is provided, even if the `execPath` is outside the `AppImage`

e.g.: 
```
electron.app.relaunch({execPath: '/usr/bin/zenity', args: ['--info', '--text=Hello']});
electron.app.quit();
```

Interestingly, the `relaunch()` method does work correctly if the application binary within the mounted AppImage is started directly. (e.g., run the AppImage once to cause the `/tmp/.mount*` to happen, and then go into that mountpoint while the first copy is still running and execute the electron binary directly.  This second directly-executed copy is able to correctly relaunch, but the first copy is not)

**Comment by camhart** [comment]
Unstale please!

**Comment by camhart** [comment]
For what it's worth, execFile (From child_process) on the AppImage should cause it to relaunch.

**Comment by peteringram0** [comment]
hi @camhart have you got an example of what your doing here please? Im getting the same issue.

**Comment by camhart** [comment]
@peteringram0 the code below will launch the new AppImage--just be sure to exit 
```
//I'm using the following to quit (upon upgrade)--I haven't tested whether just app.quit() works in place of this but I would think so
autoUpdater.quitAndInstall(true, true)

const execPath = path.join(getHomeFolder(), 'SomeApp.AppImage')
const { execFile } = require('child_process')
execFile(execPath)
```

Keep in mind AppImage's execute from a temp directory, so I don't think you can use __filename or anything like that.

**Comment by Skywalker13** [comment]
> @peteringram0 the code below will launch the new AppImage--just be sure to exit
> 
> ```
> //I'm using the following to quit (upon upgrade)--I haven't tested whether just app.quit() works in place of this but I would think so
> autoUpdater.quitAndInstall(true, true)
> 
> const execPath = path.join(getHomeFolder(), 'SomeApp.AppImage')
> const { execFile } = require('child_process')
> execFile(execPath)
> ```
> 
> Keep in mind AppImage's execute from a temp directory, so I don't think you can use __filename, which is why I've hardcoded the execPath and that feature simply doesn't work if it's moved from that location. If someone knows how to get the actual AppImage path when executing from a temp directory I'd love to hear how.

It's my workaround:
```js
  /* ... args ... */
  const {app} = require('electron');
  const options = {args};
  if (process.env.APPIMAGE) {
    options.execPath = process.env.APPIMAGE;
    options.args.unshift('--appimage-extract-and-run');
  }
  app.relaunch(options);
  app.exit(0);
```

**Comment by madmurl0c** [comment]
> It's my workaround:
> 
> ```js
>   /* ... args ... */
>   const {app} = require('electron');
>   const options = {args};
>   if (process.env.APPIMAGE) {
>     options.execPath = process.env.APPIMAGE;
>     options.args.unshift('--appimage-extract-and-run');
>   }
>   app.relaunch(options);
>   app.exit(0);
> ```
After applying the workaround that @Skywalker13 mentioned the app did restart but I wasn't able to execute any `sudo ...` commands anymore. (I know it's not recommended but I use electron on raspberry pi based closed systems and need to change the hostname, touchscreen brightness, etc. from within electron.) I came up with this solution:
```typescript
const options: RelaunchOptions = {
  args: process.argv.slice(1).concat(['--relaunch']),
  execPath: process.execPath
};
// Fix for .AppImage
if (app.isPackaged && process.env.APPIMAGE) {
  execFile(process.env.APPIMAGE, options.args);
  app.quit();
  return;
}
app.relaunch(options);
app.quit();
```

Hopefully it will save someone some time :)

**Comment by p120ph37** [comment]
This might be related to https://github.com/electron/electron/issues/34808 ?

**Comment by XilinJia** [comment]
I need to modify @madmurl0c 's workaround for it to work.  Here it is:

```
	if (app.isPackaged && process.env.APPIMAGE) {
		const options: RelaunchOptions = {
			args: process.argv,
			execPath: process.execPath,
		};
		execFile(process.env.APPIMAGE, options.args);
		app.quit();
		return;
	}
	app.relaunch();
        app.quit();
```

**Comment by dhaval-rao** [comment]
@peteringram0 the code below will launch the new AppImage--just be sure to exit

//I'm using the following to quit (upon upgrade)--I haven't tested whether just app.quit() works in place of this but I would think so
autoUpdater.quitAndInstall(true, true)

const execPath = path.join(getHomeFolder(), 'SomeApp.AppImage')
const { execFile } = require('child_process')
execFile(execPath)
Keep in mind AppImage's execute from a temp directory, so I don't think you can use __filename, which is why I've hardcoded the execPath and that feature simply doesn't work if it's moved from that location. If someone knows how to get the actual AppImage path when executing from a temp directory I'd love to hear how.

It's my workaround:

  /* ... args ... */
  const {app} = require('electron');
  const options = {args};
  if (process.env.APPIMAGE) {
    options.execPath = process.env.APPIMAGE;
    options.args.unshift('--appimage-extract-and-run');
  }
  app.relaunch(options);
  app.exit(0);


this is work for me.

i have relaunch app in specific time interval.
that work for me.

i have ubuntu 22.04
