### ISSUE TITLE
Auto update does not work on machines with Powershell version < 3

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#1732]
* **Version**:  LATEST 

* **Target**:  NSIS

The auto updater was changed to use "Convert-from-json" function which was introduced in powershell 3, so on windows 7 machines without powershell 3 it will not work. If that's intented we will need to adjust our system requirements, please tell me if there is a way to make it backward compatible.

Thanks

**Comment by develar** [comment]
@MariaDima I will disable this functionality as discussed on Windows 7.

**Comment by MariaDima** [comment]
I prepared a PR.
Should I commit it, or you are already working on it?
