### ISSUE TITLE
Signing for Windows 10 hangs in 18.8.1 - With workaround

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#1735]
* **Version**: 18.8.1

* **Target**: NSIS x64

I recently upgraded to electron-builder 18.8.1. _Previously I was using 18.5.1 and signing was working correctly._ Without any changes other than the upgrade to 18.8.1, I noticed that when building the installer, the process would hang at:

`Signing CorpApp.exe (certificate file: "c:\Users\user\dev\corp\apps\certs\corp_code.p12")`

Looking at the hung process I saw that it was trying to execute:

`powershell.exe "(Get-PfxCertificate \"c:\Users\user\dev\corp\apps\certs\corp_code.p12\").Subject"`

When I tried to execute this step manually I noticed that it was prompting me for a password. I tried to type in my certificate password where the electron-builder script was hung, and sure enough, that allowed the script to continue.

My password is specified correctly in the CSC_KEY_PASSWORD environment variable (and was working with 18.5.1)...

**Comment by develar** [comment]
Why closed?

**Comment by logidelic** [comment]
I had used npm upgrade which updated me to 18.8.1 so I thought that was the latest release, but I see in your releases that there are much newer releases, so I'm trying with the latest (19.6.3) as I type this...

**Comment by develar** [comment]
https://github.com/PowerShell/PowerShell/issues/3970

**Comment by develar** [comment]
Nope, it is serious regression.
