### ISSUE TITLE
asar smart unpack unpacks the whole lzma-native module

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1738]
* **Version**: 19.4.0

* **Target**: dmg

From https://github.com/electron-userland/electron-builder/issues/1723. 

Enabling `smartUnpack` causes the whole `lzma-native` module to be unpacked for some reason.

```sh
$ ls dist/mac/Etcher.app/Contents/Resources/app.asar.unpacked/node_modules
lzma-native/
$ ls dist/mac/Etcher.app/Contents/Resources/app.asar.unpacked/node_modules/lzma-native
LICENSE            binding/           build/             deps/              liblzma-build.sh*  node_modules/      src/
bin/               binding.gyp        cflags.sh*         index.js           liblzma-config.sh* package.json
```

Try to build Etcher (https://github.com/resin-io/etcher) for an example.

**Comment by develar** [comment]
Unpacked, because of `lzma-native/deps/bin_x86-64/liblzma.dll` But definitely dll is not required for macOS app. We should skip such files at all.

**Comment by develar** [comment]
Another reason — `lzma-native/build/liblzma/xz-5.2.3/tests/compress_prepared_bcj_sparc` Solution — electron-builder will also ignore such files (test only, not requited for production).

**Comment by develar** [comment]
BTW – highly recommended to use yarn and `yarn clean` (but do not rely on default yarn clean file, please use only https://github.com/develar/onshape-desktop-shell/blob/master/.yarnclean, because *.yml rule must be removed (yml files requited for NSIS).

**Comment by develar** [comment]
Haven't yet time to inspect your app, but this particular feature is implemented.

**Comment by develar** [comment]
Please note — in windows will be still unpacked because of DLL.

**Comment by jviotti** [comment]
Awesome, thanks a lot for the quick fix. Please let me know when you publish this to npm.

> BTW – highly recommended to use yarn and yarn clean (but do not rely on default yarn clean file, please use only https://github.com/develar/onshape-desktop-shell/blob/master/.yarnclean, because *.yml rule must be removed (yml files requited for NSIS).

Yeah, we've been wanting to move to Yarn for a while, but there are some issues with optional dependencies that prevented us from adopting it. There were some yarn tickets we were tracking for this, so maybe a good time to give it another go.

**Comment by develar** [comment]
> when you publish this to npm.

19.8.0 released.
