### ISSUE TITLE
github macOS uploads stalling (local +  travisCI)

### ISSUE THREAD

**Issue by blahah** [electron-userland/electron-builder#1739]
* **Version**:  electron-builder@next

* **Target**: macOS

macOS build stalls indefinitely at DMG upload stage. DMG is uploaded but the task never moves on to ZIP upload.

electron-builder config: https://github.com/codeforscience/sciencefair/blob/master/electron-builder.yml
travis config: https://github.com/codeforscience/sciencefair/blob/master/.travis.yml
Example Travis CI build: https://travis-ci.org/codeforscience/sciencefair/jobs/246525407

**Comment by blahah** [comment]
donated $50 via donorbox for this issue (though the form for entering issue number was broken - I had to delete some event listeners and adjacent elements to be able to type more than 1 char)

**Comment by develar** [comment]
Your tavis file is ok (latest Xcode + node 8), and now it seems all ok ok, so, I guess, it was temp GitHub failure?

**Comment by blahah** [comment]
@develar yes it seems to have fixed itself! I will keep an eye on it - for now we can close this :)
