### ISSUE TITLE
Squirrel.Windows: options.name is invalid

### ISSUE THREAD

**Issue by eanders-MS** [electron-userland/electron-builder#1743]
* **Version**: 19.8.0

* **Target**: squirrelWindows

I am transitioning my app from Squirrel.Windows to NSIS, and in the process updating the name of my application. Existing installations of my app use Squirrel.Windows to auto-update, and so for backward compatibility reasons, I need the build output of the squirrelWindows target to output the previous application name. Perusing the source of `electron-builder-squirrel-windows`, it appears that the `name` option is the configuration I need, but it isn't exposed. I get this error when I try to set it:
```javascript
[09:25:48] Error: Config is invalid:
{
  "squirrelWindows": [
    {
      "name": "Unknown option"
    },
    "Invalid option object"
  ]
}
```

Yet, it is in SquirrelOptions:
(in electron-builder/packages/electron-builder-squirrel-windows/src/squirrelPack.ts)
```javascript
export interface SquirrelOptions {
 ...
  name: string
... 
}
```

Any chance it could be included in the exposed options?

**Comment by develar** [comment]
Fix will be available today.

**Comment by develar** [comment]
For obvious reasons this option will be not documented and not tested (well, in any case I cannot right now because my iMac is broken).
