### ISSUE TITLE
force run after silent update doesn't work. using `appUpdater.quitAndInstall(isSilent=true, isForceRunAfter=true)`

### ISSUE THREAD

**Issue by alondanoch** [electron-userland/electron-builder#1746]
* **Version**: 
"electron": "^1.7.2",
"electron-builder": "^19.9.1",
"electron-updater": "^2.4.3",

* **Target**: 
win (NSIS)
(tested on windows 10 latest)

* **Issue**: 
using the new `isForceRunAfter` feature with `appUpdater.quitAndInstall(isSilent=true, isForceRunAfter=true)`, to force reopen app after update doesnt work (update works, but doesnt run).

please see example code and package.json in the following repo:
https://github.com/alondanoch/sparkdownload

**Comment by develar** [comment]
Works for me.

Your code is not fully correct, please see https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-306709572

You need to use setImmediate

**Comment by Kunze** [comment]
Did not work for me on windows, eve using setImmediate. The app closes but not reopen.

**Comment by afroewis** [comment]
In my case (windows), the application closes, but doesn't restart.

**Comment by harryhle** [comment]
For me, `quitAndInstall` with `isForceRunAfter=true` works in some occasions and fails on the others. 

It works when I run `checkForUpdates`  before launching the Electron main window.

However, after the the main window is launched, this function fails to force run the app. In details, it downloaded the update, installed the new version, quit the app, but fail to launch the app again after installing. 

`setImmediate` or `setTimeout` didn't help to resolve this issues. 

I also tried replicate the source code like below, but it still wouldn't force run the app after installing.
```
autoUpdater.on('update-downloaded', info => {
   spawn(info.downloadedFile, ['--force-run'], {
        detached: true,
      })
})
```
