### ISSUE TITLE
Possible to publish without building?

### ISSUE THREAD

**Issue by eanders-MS** [electron-userland/electron-builder#1750]
* **Version**: 19.10.0

* **Target**: (copied from build scripts):
`targets: builder.Platform.WINDOWS.createTarget(["nsis", "zip"], builder.Arch.ia32, builder.Arch.x64),`
`targets: builder.Platform.WINDOWS.createTarget(["squirrel"], builder.Arch.x64),`
`targets: builder.Platform.MAC.createTarget(["dmg", "zip"]),`
`targets: builder.Platform.LINUX.createTarget(["deb", "rpm", "AppImage"], builder.Arch.ia32, builder.Arch.x64),`

Our build system utilizes a code signing service. After electron-builder finishes packaging our app for a given target, we submit the build to our code sign service. After some amount of time, the service returns the signed binaries. At this point, I would like to be able to leverage electron-builder's publish capability to publish a draft release to github. Is it possible to programmatically invoke electron-builder's publish feature on a preexisting set of files? Something like:

```javascript
    builder.publish({
        targets: builder.Platform.LINUX.createTarget(["deb", "AppImage"], builder.Arch.ia32, builder.Arch.x64),
        config
    });
```

**Comment by eanders-MS** [comment]
Oh, I think I just have to call electron-publish directly.

**Comment by develar** [comment]
I suggest to ask feature — sign on remote instead of own solution. I will accept it.

**Comment by eanders-MS** [comment]
I think I lack the context to understand your suggestion.
I found a straight-forward solution to my problem by calling electron-publish programmatically from my build script. If you like you can see it here (gulpfile.js): https://github.com/eanders-MS/electron-test

**Comment by develar** [comment]
Cool that you are so smart :) 👍

**Comment by develar** [comment]
Closed for now — @eanders-MS is a true developer. For others — wait feature request. Our feature list todo is full and no need to add another item without request.
