### ISSUE TITLE
Licenses for node_modules?

### ISSUE THREAD

**Issue by premitius** [electron-userland/electron-builder#1755]
* **Version**: 
14.5.3

* **Target**: 
Mac, Win

I have an electron app that I want to distribute. I'm using a lot of npm packages with different licenses, for example ISC & MIT licenses. To quote the ISC license:

> "Permission to use, copy, modify, and/or distribute this software for any
> purpose with or without fee is hereby granted, **provided that the above
> copyright notice and this permission notice appear in all copies.**"

How can I make sure that the copyright notice of all my node_modules appear in the distributed app? I have created an .asar app and when inspecting the package contents on Mac, I cannot find any file containing the licenses of the npm packages I am using.

**Comment by develar** [comment]
We specially do not ignore LICENSE files in node_modules.

> How can I make sure that the copyright notice of all my node_modules appear in the distributed app

Install asar globally (`npm i asar -g`) and `asar l app.asar`.

```
develar-home:~ develar$ asar l /Users/develar/Documents/electrify/dist/mac/Electrify.app/Contents/Resources/app.asar 
/package.json
/node_modules
/node_modules/vuex
/node_modules/vuex/LICENSE
...
```
