### ISSUE TITLE
Question: File Association get file path

### ISSUE THREAD

**Issue by jbw91** [electron-userland/electron-builder#1757]
* **Version**: 19.8.0

* **Target**: mac

Not using electron-updater

I have file associations working correctly for my application. However, I can't find anywhere in the documentation where to obtain the file path of the file being used to open the application. So I would expect, if I were to double click `myfile.xyz` to open my application, that the path to the file I clicked on would be available to access in my application, possibly in `process.argv`. When I tested this theory, it only had the path to the application being opened. My question is, how can I tell what file is being used to open this application? I would expect that I could open that file, and then access that file from a file path.

Any help would be greatly appreciated!

**Comment by develar** [comment]
Have you read https://github.com/electron/electron/blob/master/docs/api/protocol.md?

**Comment by jakesyl** [comment]
@jbw91 were you able to resolve this?

**Comment by donaldmstephan** [comment]
To resolve this I capture that `open-file` event when it happens. If the app is not ready (in the case of opening the app with file association),  capture the event and then pass it into the mainWindow when it renders. Note that I've only tested this on Mac and not windows. The Electron docs say that on Windows you can simply grab that path from the `process.argv`.

```
let fileEvent = null;
app.on('will-finish-launching', async () => {
  app.on('open-file', async (ev, path) => {
    if (mainWindow) {
      mainWindow.send('file-open', (ev, path));
    } else if (app.isReady() && !mainWindow) {
      renderMainWindow({ type: 'file-open', ev, path });
    } else {
      fileEvent = {
        ev,
        path
      }
    }
  });
});

app.on('ready', async () => {
  protocol.registerFileProtocol(...)

  if (fileEvent) {
    renderMainWindow({ type: 'file-open', ev: fileEvent.ev, path: fileEvent.path });
    fileEvent = null;
  } else {
    renderMainWindow();
  }
});
```
