### ISSUE TITLE
Windows autoupdate isn't working

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#1759]
-  electron-builder version:  16.6.1

- electron-updater version: 1.14.0

* target: Windows and Mac

In my `package.json` file, I have the following build configuration. Most important is the publish property that points to an s3 bucket.

```js
{
        "name": "Notion",
        "version": "0.1.10",
        "main": "main.js",
        "author": "Notion Labs, Incorporated",
        "dependencies": {
                "electron-is-dev": "^0.1.2",
                "electron-log": "^2.2.2",
                "electron-spellchecker": "1.0.6",
                "electron-updater": "^1.14.0",
                "electron-window-state": "3.0.3",
                "storage-lru": "0.1.1"
        },
        "devDependencies": {
                "electron": "1.6.2",
                "electron-builder": "16.6.1",
                "electron-rebuild": "1.5.7"
        },
        "build": {
                "appId": "notion.id",
                "productName": "Notion",
                "mac": {
                        "category": "public.app-category.productivity"
                },
                "directories": {
                        "app": ".",
                        "output": "../../dist",
                        "buildResources": "."
                },
                "protocols": [
                        {
                                "name": "notion",
                                "schemes": [
                                        "notion"
                                ]
                        }
                ],
                "publish": [
                        {
                                "provider": "generic",
                                "url": "https://s3-us-west-2.amazonaws.com/desktop-release/",
                                "channel": "latest"
                        }
                ]
        }
}
```

I've deployed the applications to S3:

![image](https://user-images.githubusercontent.com/1794527/27667718-8f0d94c6-5c31-11e7-8456-fa9e0820b5da.png)

Everything is working fine with the Mac autoupdate, but the Windows app isn't updating. I can check the logs and see that its not updating as well:

```
$ tail -f log.log
[2017-06-28 18:38:47:0678] [info] Checking for update
[2017-06-28 18:38:47:0921] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
[2017-06-28 18:39:47:0696] [info] Checking for update
[2017-06-28 18:39:48:0178] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
[2017-06-28 18:40:47:0707] [info] Checking for update
[2017-06-28 18:40:48:0064] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
[2017-06-28 18:41:47:0723] [info] Checking for update
[2017-06-28 18:41:47:0990] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
[2017-06-28 18:42:47:0747] [info] Checking for update
[2017-06-28 18:42:48:0011] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
[2017-06-28 18:43:47:0765] [info] Checking for update
[2017-06-28 18:43:48:0015] [info] Update for version 0.1.9 is not available (latest version: 0.1.9, downgrade is disallowed.
```

One thing that's odd is the generated `latest.yml` file has a `githubArtifactName` field which seems irrelevant. 

https://s3-us-west-2.amazonaws.com/desktop-release/latest-mac.json
https://s3-us-west-2.amazonaws.com/desktop-release/latest.yml

I'm not a Windows user so I'd appreciate any help or suggestions you have to help me figure this out!

**Comment by develar** [comment]
> electron-builder version: 16.6.1
electron-updater version: 1.14.0

Please use latest versions.

**Comment by ccorcos** [comment]
Well at the time I shipped these apps, I was using the latest versions so they're already out in the wild and I can't change that... :/ So if I upgrade, I'm not sure that's going to help unless its a file format issue with the latest.yml file. But I feel like the logs would have reported that.

P.S. holy crap, there's a new version every other day!

**Comment by develar** [comment]
Interesting, maybe problem in the version — `0.10` vs `0.1.9`... need to check semver rules.

**Comment by develar** [comment]
Or cache issue in the old electron-updater version...

**Comment by ccorcos** [comment]
well its `0.1.9` and `0.1.10`. and everything worked fine on Mac. I'll upgrade and see what happens to the yml file.

**Comment by ccorcos** [comment]
I upgraded those packages to the latest ones on NPM:

```
"electron-builder": "19.8.0",
"electron-updater": "2.4.3",
```

The `latest.yml` file has pretty much the same format with the addition of a new sha512 hash. But everything else is basically the same. Maybe this is a caching issue with electron-updater. I'll check that out.

**Comment by ngprasad** [comment]
@ccorcos I am also facing the same issue on Windows 10. I can see the new binary getting downloaded but never get the prompt to update. However it works fine on mac. Were you able to figure out why its not working on windows?

**Comment by ngprasad** [comment]
Tried with the latest version of electron-builder (19.3.x), electron-updater (2.x.x) and electron (1.7.x)

**Comment by ccorcos** [comment]
Sorry to let you down @ngprasad but the windows update just worked. I think it must have been a caching issue! Have you looked at the logs? It usually quite helpful
