### ISSUE TITLE
downloading yml from site with invalid certificate fails without error

### ISSUE THREAD

**Issue by pieterh** [electron-userland/electron-builder#1760]
When electron-updater 2.4.3 on windows tries to connect to a server using the generic https provider and the certificate of this server is invalid, there is no error about the invalid certificate logged/reported. The updater fails silently.
I expected an error was emitted indicating that updating is failing due to an issue with the certificate and that this error was thrown.

**Comment by develar** [comment]
Workaround — please listen https://github.com/electron/electron/blob/master/docs/api/app.md#event-certificate-error

**Comment by pieterh** [comment]
we already had this handler in place for an other site (not related to the updater). it does a console.log but we didn't see anything in the console for the event. other items we see appear in the log so I assumed that this event was just for normal pages and not used when the updater encounters this problem, Are you sure that this workaround should work?

**Comment by develar** [comment]
No, I am not sure, but updater doesn't use node http — Electron Net API is used instead. To be check.
