### ISSUE TITLE
Option to strip other items from package.json on build

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#1764]
electron-builder is already stripping much of the un-needed stuff from the package.json on building releases. I would however also like it to strip the `jspm` node too. Could `jspm` be added or would it help to have a config option so users could selectively strip other unnecessary nodes?

**Comment by develar** [comment]
jspm, ava, babel are removed now.

**Comment by sindresorhus** [comment]
@develar Some other popular package.json root keys that should be removed:

- `xo` https://github.com/chalk/chalk/blob/8d26c1401cac1b1123e6b82f20f866e1d8756986/package.json#L56
- `nyc` https://github.com/sindresorhus/loud-rejection/blob/6727cc1f760f545b6765d28913d86aee1a64ea3d/package.json#L54
- `eslintConfig` https://github.com/geekjuice/webhook-tester/blob/cc5aa2a66f618c43a9f2145ecf2530554a92a207/package.json#L2
