### ISSUE TITLE
Exit code error 255 due to broken link?

### ISSUE THREAD

**Issue by Alkaselzer22** [electron-userland/electron-builder#1766]
* **Version**: 19.8.0
* **Target**: Linux x64, Windows x64

I'm getting a 
> Command failed with exit code 255 
error message while running the ./node_modules/.bin/build -l --x64 or ./node_modules/.bin/build -w --x64 commands. The traceback brings me to:

> Packaging` for linux x64 using electron latest to dist/linux-unpacked
> Downloading` tmp-28600-0-electron-vlatest-linux-x64.zip
> Error:` GET https://github.com/electron/electron/releases/download/vlatest/electron-vlatest-linux-x64.zip returned` 404

Could it be possible that the link is dead/broken/offline?

**Comment by develar** [comment]
Please set electron version to exact version, e.g. 1.6.11. Not `latest`.

**Comment by Alkaselzer22** [comment]
That resolved my issue. Thank you very much for your help!
