### ISSUE TITLE
Application with createDesktopShortcut=false doesn't launch automatically

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#1767]
* **Version**:  19.10.0 or 19.11.1

* **Target**: nsis

According to the [documentation ](https://github.com/develar/electron-builder/blob/350e24106aba4882bb63e184ce9a964092728b79/docs/Options.md) if new option **createDesktopShortcut** is set to false, no desktop shortcut is created after installation. But in addition the application doesn't launch automatically and there is no application in the start menu. In this case users don't have ability to start the application after it is installed.
Is it expected behavior?

**Comment by develar** [comment]
No :)

**Comment by clusterberries** [comment]
Ok, thanks! Waiting for the fix then

**Comment by develar** [comment]
@clusterberries Simply because feature was shipped to hear feedback and now we have one :)
