### ISSUE TITLE
timeStampServer for StartCom certificate

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1769]
Hello,

Should I use the timestamp server from [StartCom](https://www.startcomca.com/index/support?v=25#60) for time stamping my application or could I keep the default values from the [doc](https://github.com/electron-userland/electron-builder/blob/350e24106aba4882bb63e184ce9a964092728b79/docs/Options.md) ?

```
rfc3161TimeStampServer = http://timestamp.comodoca.com/rfc3161 String - The URL of the RFC 3161 time stamp server.

timeStampServer = http://timestamp.verisign.com/scripts/timstamp.dll String - The URL of the time stamp server.
```

Thanks !

**Comment by develar** [comment]
rfc3161TimeStampServer/timeStampServer doesn't depend on Certificate Authority. You can use defaults.

**Comment by popod** [comment]
@develar thank you very much for answering !! ;)
