### ISSUE TITLE
NSIS builder not use ${arch} macro in artifactName

### ISSUE THREAD

**Issue by ert78gb** [electron-userland/electron-builder#1774]
* **Version**: 19.11.1

electron-updater: 2.2.0

* **Target**: Win ia32 x64

Hi,

I programatically create build config I set artifactName, but NSIS builder not use ${arch} macro.
I use appveyor to create release bundle for Win. I use separated configuration because I use platform specific dependencies that I build on platform.
I have 1 or 2 issues:
- NSIS builder use ${arch} macro when create installer.
- If create NSIS installer for x64 and ia32 architecture then the latest.yml file should generate correctly. Maybe need 2 latest.yml 1 for x64 and 1 for ia32 same than mac.
 
The script file:
https://github.com/ert78gb/agent/blob/feat-283-win64-bit-installer/scripts/release.js
thx,
Robi

**Comment by develar** [comment]
https://electron-builder.slack.com/archives/C3X4YCA14/p1498730241455460

**Comment by develar** [comment]
Without registration — https://electron-builder.slackarchive.io/general/page-17/ts-1498730241455460
