### ISSUE TITLE
[idea] builder should do pre-publish check for things that would break autoupdate

### ISSUE THREAD

**Issue by brandonmp** [electron-userland/electron-builder#1777]
After figuring out #1773, i got a little nervous that i could potentially one day push a build that won't autoupdate & started thinking about how to test this aspect of the build

I think the easiest way would be if `electron-builder` did a simple check before publishing, verifying things like 'does the `publisherName` match the name on the code sign cert?'

Not sure what else should be tested/would be easy to test, though i'm sure there are other things

**Comment by develar** [comment]
Actually, `publisherName` can be array of possible names (for cert migration).
