### ISSUE TITLE
channel file name macro doesn't work when channel is latest

### ISSUE THREAD

**Issue by brandonmp** [electron-userland/electron-builder#1778]
* **Version**: 
        "electron": "^1.6.11",
        "electron-builder": "^19.11.1",
        "electron-publisher-s3": "^19.5.0",

* **Target**: mac, win

my publish config is:

```
        "publish": {
            "provider": "s3",
            "bucket": "my bucket",
            "path": "${channel}/${os}"
        },
```

~~where channel is automatically inferred from the version in `app/package.json`~~
**ETA**: it's also null when channel is manually set to `latest`, i.e.:
```
        "publish": {
            "provider": "s3",
            "bucket": "my bucket",
            "path": "${channel}/${os}",
            "channel": "latest"
        },
```

When that version is `1.0.3-beta.12`, this works fine and `path: beta/win`/`path: beta/mac` shows up in `app-update.yml`.

however, when version is `1.0.3`, the `app-update.yml` shows `path: null/win`/`path: null/mac`

**Comment by develar** [comment]
If no channel but channel macro exists, we should use latest, right?

**Comment by brandonmp** [comment]
agreed. the behavior in other parts where `channel` is used (eg, `app-update.yml`) is to default to `latest`, so I think it's consistent that every `${channel}` macro should default to `latest` as well
