### ISSUE TITLE
Compiling with xml files

### ISSUE THREAD

**Issue by debelop13** [electron-userland/electron-builder#1780]
Version: "electron-builder": "^19.11.1",

Hi!
I am assembling project with ember-electron, and I want to use electron-builder to make .app and .dmg to use electron-updater, and when I compile with "build --mac" my app directory assembled, I get the following error:

Error: Compiling myproject/electron-out/project/ember/crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle.

I know that ember-electron uses electron-compile and is skipping the warning/error:
https://github.com/electron/electron-compile/issues/167

Can be the same here?

Thanks

**Comment by develar** [comment]
Please try to add to `.compilerc` new entry:

```xml
  "application/xml": {
    "passthrough": true
  }
```

**Comment by debelop13** [comment]
Thanks!

I have this error now: 

Error: Found compiler settings for missing compiler: application/xml
