### ISSUE TITLE
build package publish config wrong

### ISSUE THREAD

**Issue by sante85** [electron-userland/electron-builder#1783]
* **Version**: 19.12.0

* **Target**: win

build config .....

    "publish": {
      "url": "https://10.8.0.1:8080/SAPS/offlineClientUpdates/${os}",
      "provider": "generic"
    }

run "dist:win": "build -w --x64 --ia32 --projectDir dist"

electron-builder 19.12.0
Error: Config is invalid:
{
  "publish": [
    {
      "url": [
        "Unknown option",
        "Unknown option"
      ],
      "owner": "Unknown option"
    },
    "Required option",
    "Should be array",
    "Should be null,string",
    "Invalid option object"
  ]
}

How to fix:
  1. Open https://github.com/electron-userland/electron-builder/wiki/Options
  2. Search the option name on the page.
    * Not found? The option was deprecated or not exists (check spelling).
    * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder ` and attach log of the terminal output.

**Comment by sante85** [comment]
electron-builder 19.12.0
  electron-builder Effective config:
  electron-builder appId: com.masvis.sultanoffline
  electron-builder compression: maximum
  electron-builder electronVersion: 1.6.11
  electron-builder nsis:
  electron-builder   include: build/installer.nsh
  electron-builder   installerHeader: ''
  electron-builder   license: ''
  electron-builder   deleteAppDataOnUninstall: true
  electron-builder linux:
  electron-builder   target:
  electron-builder     - deb
  electron-builder win:
  electron-builder   icon: icon-red.ico
  electron-builder   legalTrademarks: 'Tauro Sistemi 2017, tutti i diritti registrati'
  electron-builder publish:
  electron-builder   provider: generic
  electron-builder   owner: Masvis
  electron-builder   url: 'https://10.8.0.1:8080/SAPS/offlineClientUpdates/${os}'
  electron-builder  +0ms
  electron-builder [
  electron-builder   {
  electron-builder     "keyword": "additionalProperties",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/additionalProperties",
  electron-builder     "params": {
  electron-builder       "additionalProperty": "url"
  electron-builder     },
  electron-builder     "message": "should NOT have additional properties"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "additionalProperties",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/additionalProperties",
  electron-builder     "params": {
  electron-builder       "additionalProperty": "owner"
  electron-builder     },
  electron-builder     "message": "should NOT have additional properties"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "additionalProperties",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/additionalProperties",
  electron-builder     "params": {
  electron-builder       "additionalProperty": "url"
  electron-builder     },
  electron-builder     "message": "should NOT have additional properties"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "required",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/required",
  electron-builder     "params": {
  electron-builder       "missingProperty": "bucket"
  electron-builder     },
  electron-builder     "message": "should have required property 'bucket'"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "additionalProperties",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/additionalProperties",
  electron-builder     "params": {
  electron-builder       "additionalProperty": "owner"
  electron-builder     },
  electron-builder     "message": "should NOT have additional properties"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "additionalProperties",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/additionalProperties",
  electron-builder     "params": {
  electron-builder       "additionalProperty": "url"
  electron-builder     },
  electron-builder     "message": "should NOT have additional properties"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "type",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/properties/publish/anyOf/4/type",
  electron-builder     "params": {
  electron-builder       "type": "array"
  electron-builder     },
  electron-builder     "message": "should be array"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "type",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/properties/publish/anyOf/5/type",
  electron-builder     "params": {
  electron-builder       "type": "null,string"
  electron-builder     },
  electron-builder     "message": "should be null,string"
  electron-builder   },
  electron-builder   {
  electron-builder     "keyword": "anyOf",
  electron-builder     "dataPath": ".publish",
  electron-builder     "schemaPath": "#/properties/publish/anyOf",
  electron-builder     "params": {},
  electron-builder     "message": "should match some schema in anyOf"
  electron-builder   }
  electron-builder ] +339ms
Error: Config is invalid:
{
  "publish": [
    {
      "url": [
        "Unknown option",
        "Unknown option"
      ],
      "owner": "Unknown option"
    },
    "Required option",
    "Should be array",
    "Should be null,string",
    "Invalid option object"
  ]
}

How to fix:
  1. Open https://github.com/electron-userland/electron-builder/wiki/Options
  2. Search the option name on the page.
    * Not found? The option was deprecated or not exists (check spelling).
    * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

    at D:\Progetti\sultan-offline-client\node_modules\electron-builder\src\util\config.ts:195:5
From previous event:
    at validateConfig (D:\Progetti\sultan-offline-client\node_modules\electron-builder\out\util\config.js:205:22)
    at D:\Progetti\sultan-offline-client\node_modules\electron-builder\src\packager.ts:129:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (D:\Progetti\sultan-offline-client\node_modules\electron-builder\out\packager.js:222:11)
    at D:\Progetti\sultan-offline-client\node_modules\electron-builder\src\builder.ts:251:40
    at next (native)
From previous event:
    at build (D:\Progetti\sultan-offline-client\node_modules\electron-builder\out\builder.js:69:21)
    at Object.args [as handler] (D:\Progetti\sultan-offline-client\node_modules\electron-builder\src\cli\cli.ts:41:4)
    at Object.self.runCommand (D:\Progetti\sultan-offline-client\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (D:\Progetti\sultan-offline-client\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (D:\Progetti\sultan-offline-client\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (D:\Progetti\sultan-offline-client\node_modules\electron-builder\src\cli\cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist:win"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sultan-offline-client@2.0.0 dist:win: `build -w --x64 --ia32 --projectDir dist`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the sultan-offline-client@2.0.0 dist:win script 'build -w --x64 --ia32 --projectDir dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sultan-offline-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build -w --x64 --ia32 --projectDir dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sultan-offline-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sultan-offline-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Progetti\sultan-offline-client\npm-debug.log

**Comment by develar** [comment]
Hmm... Really strange.

**Comment by sante85** [comment]
i have tried with 18.6.2 and do correctely.

**Comment by develar** [comment]
Strange, I cannot reproduce.

**Comment by develar** [comment]
Could you please `rm -rf node_modules && yarn install`? ([yarn](https://yarnpkg.com/en/docs/install) is recommended instead of npm).

**Comment by develar** [comment]
And please try `19.12.1`

**Comment by sante85** [comment]
rm -rf node_modules already carried out, with no results.

where is 19.12.1 version?

**Comment by develar** [comment]
> where is 19.12.1 version?

Just set version to `19.12.1` (it is next version).

**Comment by sante85** [comment]
resolved in 19.13.0
