### ISSUE TITLE
Reuse Chromium and Node Binaries

### ISSUE THREAD

**Issue by popey456963** [electron-userland/electron-builder#1786]
It would be really wonderful if we could lower the executable size of Electron.  The current ~120MB is somewhat unwieldy for a large number of individuals.  Could we enable this builder to perhaps add the ability to only download Node/Chromium if it isn't installed already, and centralize the installation of those programs somewhere.

With Electron becoming more and more popular, I currently have about 20-30 applications using it installed at the moment, each with their own copy of Chromium and Node.

(Apologies if asked before, searched for terms I could think of and nothing came up)

**Comment by black-snow** [comment]
This is rather an issue with electron itself, not electron-builder.
I've seen some discussions about this topic round the web.

**Comment by develar** [comment]
Duplicates https://github.com/electron/electron/issues/673
