### ISSUE TITLE
How to reset autoupdater?

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#1787]
* **Version**: 
```
"electron": "1.6.2",
"electron-builder": "16.6.1",
"electron-updater": "^1.14.0",
```

* **Target**:  OSX, Windows

I'm trying to debug an issue where auto-updater keeps downloading an update from our update server costing us a fortune in data-transfer costs. So I'm starting out by downloading the old app and making sure it updates. However, when I download an old version of the application, its not updating. I've tested this before and it worked. Perhaps there's a cache somewhere of the old updates or something that I can delete. Any ideas?

**Comment by develar** [comment]
Please see logs if it was enabled. Or try to uninstall app and then install old version to test. Mac or Windows?

**Comment by ccorcos** [comment]
Mac. Sadly I don't have logs enabled on this build and its using Nuts / Squirrel. Its an old one. It seems to be working in production though so I'm not too worried -- I think I just found our issue though. I'll open up a more relevant issue for that.

**Comment by develar** [comment]
In the 2.x version of updater more reliable solution for Mac is used.
