### ISSUE TITLE
extraResources/binaries both do not work

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#1790]
* **Version**: 
19.12

* **Target**:  macOS

I am trying to pack a binary into the app bundle and sign it along with it. However documentation is quite vague about path lookup. I can't get it to work, it does not see files and cannot sign the binary. Files are not being copied and *no errors* are being emitted. I expect specified files to be copied in `Contents/Resources`.

```
appId: com.example.app
copyright: © Acme Inc.
productName: Product name

asar: true

directories:
  buildResources: build-assets/
  output: dist/

files:
  - package.json
  - init.js
  - build/
  - node_modules/

extraResources:
  - ../acme/release/some_executable_here

dmg:
  contents:
    - type: link
      path: /Applications
      x: 410
      y: 150
    - type: file
      x: 130
      y: 150

mac:
  target:
    - dmg
  binaries:
    - some_executable_here
  category: public.app-category.tools
  extendInfo:
    LSUIElement: true

win:
  target:
    - nsis

linux:
  target:
    - deb
    - AppImage

```

Build output:

```
> acme@1.0.11 private:build /Users/coyote/looneytunes
> build --config distribution.yml "--mac"

electron-builder 19.12.0
Using distribution.yml configuration file
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.6.11 to dist/mac
Signing app (identity: XXX Developer ID Application: YYY ZZZ (PPP))
Error: Command failed: codesign --sign XXX --force some_executable_here
some_executable_here: No such file or directory
```

**Comment by pronebird** [comment]
update:

I figured out that by default extraResources copies entire file structure into `Resources`. However with `from` and `to` keys I was able to override that, i.e:

```
extraResources:
  - from: ../acme/release/some_executable_here
    to: some_executable_here
```

**Comment by pronebird** [comment]
Closing since I solved that with from/to and binaries are automatically detected

**Comment by JimmyMow** [comment]
@pronebird did you solve the code signing issue? I am facing the same problem

**Comment by pronebird** [comment]
@JimmyMow 

Just use a `from` and `to` combo to bundle assets, i.e:

```
extraResources:
  - from: ../acme/coyote
     to: .
```

**Comment by JimmyMow** [comment]
@pronebird thanks. 

and then where will the binary be packaged? inside `Resources`?

**Comment by pronebird** [comment]
@JimmyMow if you put the record in `extraResources` section then I think it goes into `Resources`.
