### ISSUE TITLE
something error during packing

### ISSUE THREAD

**Issue by Tanjh1996** [electron-userland/electron-builder#1792]
When i pack my application today, it meet some errors. I reset to the previous version,it has the same error. how can i deal with it.
![error](https://user-images.githubusercontent.com/20512530/27861135-16e9194e-61b2-11e7-8a97-d5fd675a3b15.png)

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder ` and attach log of the terminal output.

**Comment by Tanjh1996** [comment]
it ssems ok these days.
