### ISSUE TITLE
TrayIcon conversion error in main process

### ISSUE THREAD

**Issue by yuri-karkh** [electron-userland/electron-builder#1793]
* **Version**: 19.13.0

* **Target**: nsis/dmg/unpacked

Electron: 1.7.4

![mac](https://user-images.githubusercontent.com/12514101/27866598-ae40ab30-619f-11e7-9413-87a941288e17.PNG)
![win](https://user-images.githubusercontent.com/12514101/27866596-ae3dbc04-619f-11e7-9ecd-a37472a97a7b.PNG)

Hello, I have next problem, so thank you in advance for your time: when build nsis or dmg installer (or unpacked version of the build under mac and win) with electron builder I get the error related to conversion of Tray icon: "Error processing argument at at index 0, conversion failure from PATH_TO_ICON", see attached. For windows and mac used .ico and .icns versions of the icons, path is absolute (see attached code snippets). In version 18.x everything was ok and no such error appear. Few notes: if I comment Tray init code, all work as expected; if I package same code with electron-packager directly all work as expected and issue doesn't appear. Also tried to pass NativeImage instead of icon path to Tray() but same result. Tried also asar to set on/off, no luck. What can be a reason of this error? Thanks for the help.

![main](https://user-images.githubusercontent.com/12514101/27866597-ae3ddeb4-619f-11e7-94f0-dc2aaeec1ebb.PNG)
![package](https://user-images.githubusercontent.com/12514101/27866599-ae40ff68-619f-11e7-8a99-5f0ebf2e8f71.PNG)

**Comment by develar** [comment]
Installer build resources are not packed into your app. Please explicitly specify such icon in the `files` option. `"files": ["*/**", "installerResources/icon.*"]`

**Comment by yuri-karkh** [comment]
thanks @develar, it was not obvious from docs for me. Now all work as expected.

**Comment by develar** [comment]
Electron packager doesn't have smart rules about files. Electron builder does the best to produce minimal app. Tray icon it is known issue — although it should be clear that build resources should be not packed into app :) and behavior is logical.

**Comment by develar** [comment]
I will add note to option about it.

**Comment by yuri-karkh** [comment]
Agree about your mentions, anyway thanks for quick help!
