### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 on mas-dev

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1795]
* **Version**: 19.13.0

* **Target**: mas-dev

I'm experimenting with the MAS targets, but getting some issues I don't really understand. I'm building the `mas-dev` target for a dummy digital clock app I've been using for testing purposes:  https://github.com/jviotti/digital-clock.

The build seems to go without any errors:

```sh
$ CSC_NAME="Juan Cruz Viotti (6AZR5XBJ4X)" npm run dist

> digital-clock@1.1.0 dist /Users/jviotti/Projects/personal/digital-clock
> build

electron-builder 19.13.0
No native production dependencies
Packaging for mas x64 using electron 1.6.6 to dist/mas-dev
Signing app (identity: 228D4C001B71A1B85C3FA629A500BD422740F0C9 Mac Developer: Juan Cruz Viotti (6AZR5XBJ4X))
```

However, this is what I get when I run the app:

```
$ open dist/mas-dev/Digital\ Clock.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jviotti/Projects/personal/digital-clock/dist/mas-dev/Digital Clock.app.
```

I found https://github.com/electron-userland/electron-builder/issues/1180, but it doesn't seem related to my issue (I'm not adding `root` to the mix anywhere).

Steps to reproduce:

```sh
git clone https://github.com/jviotti/digital-clock
cd digital-clock
git checkout mas
npm install
npm run dist
open dist/mas-dev/Digital\ Clock.app
```

What am I missing?

***

I tried adding a custom entitlements file that disables the app sandbox:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <false/>
  </dict>
</plist>
```

Which gets rid of the original error, and the app icon appears in the dock, but the app doesn't run at all.

**Comment by jviotti** [comment]
This is what I get if I run the binary directly:

```
$ ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock 
Killed: 9
```

**Comment by jviotti** [comment]
Running the app (and the binary directly) with `sudo` leads to the same results.

**Comment by black-snow** [comment]
Are you using `tmux`?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/1196#issuecomment-310638965

I am sorry — I don't have experience in this area and cannot advise you. I don't have time to investigate this issue for you.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by jviotti** [comment]
Thanks for the help, I'm indeed using `tmux`. Here's what I tried:

- Running the binary directly, from `tmux`:

```sh
$ ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock
zsh: killed     ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock
```

- Running the binary from outside `tmux`:

```sh
$ ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock 
zsh: killed     ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock
```

- Opening the `.app` from outside `tmux` (same error as in the original issue)
- The `.app` binary has execution permissions, but still, I added them again, and same issue
- Running binary with `reattach-to-user-namespace`, same thing

```sh
$ reattach-to-user-namespace ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock
zsh: killed     reattach-to-user-namespace ./Digital\ Clock.app/Contents/MacOS/Digital\ Clock
```

- Tried removing quarantine attributes from the generated `.app`. Same issue

***

Is there an electron-builder example running the latest version where the MAS target works?

By reading https://stackoverflow.com/questions/28105587/what-makes-an-os-x-app-not-open-with-the-error-lsopenurlswithrole-failed-with, it seems that the issue could be caused by the binary exitting with code 1, as a result of an electron-builder bug for example. I'll investigate further.

**Comment by jviotti** [comment]
@develar Maybe its just me, but I can't see that the current electron-builder version downloads the MAS electron package. It seems to re-use the normal one, which as far as I understand, won't work.

**Comment by jviotti** [comment]
Never mind, I see that the tool outputs that the MAS version is being downloaded:

```
Downloading tmp-12135-0-electron-v1.7.4-mas-x64.zip
[>                                            ] 1.5% of 47.44 MB (129.49 kB/s)
```

**Comment by jviotti** [comment]
I tested a `mas-dev` generated build on another MacBook, and got the following error:

```
Process:               Digital Clock [702]
Path:                  /Volumes/VOLUME/*/Digital Clock.app/Contents/MacOS/Digital Clock
Identifier:            com.example.digitalclock
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Digital Clock [702]
User ID:               501

Date/Time:             2017-07-12 21:17:52.706 -0400
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        F4B972D2-73CB-0DBD-8F2F-EA7FD035F7B5

Sleep/Wake UUID:       4D1C687F-C925-4C1D-8102-A84C9C92974D

Time Awake Since Boot: 15000 seconds
Time Since Wake:       24 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    mapped file            00000001089d3000-00000001089d4000 [    4K] r-x/rwx SM=COW  

Thread 0 Crashed:
0   dyld                          	0x0000000111d08000 _dyld_start + 0
1   ???                           	0x0000000000000001 0 + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5722cc60
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000111d08000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x111d07000 -        0x111d44287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7038
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=336K resident=0K(0%) swapped_out_or_unallocated=336K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                             220K        3 
__LINKEDIT                          88K        2 
__TEXT                             248K        2 
mapped file                         20K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             64.6M       12 

Model: MacBookAir6,2, BootROM MBA61.0099.B22, 2 processors, Intel Core i7, 1,7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736443120
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736443120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.47.1a8)
Bluetooth: Version 5.0.1f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Card Reader
USB Device: Transcend
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
```

The highlight from the above report is:

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

Not sure if there's an actual issue with the code-signing, or its just because that laptop doesn't have the certificates I signed the app with.

**Comment by jviotti** [comment]
I'm not sure if this is related at all, but I noticed something odd with my Apple certificates:

<img width="487" alt="screen shot 2017-07-12 at 9 49 24 pm" src="https://user-images.githubusercontent.com/2192773/28147073-0c3be18a-674c-11e7-9586-d1816ed73a7a.png">

Notice that the ID of the "Mac Developer" one is different from the others (I tried re-generating it multiple times with the same results), and if I pass either of the IDs to `CSC_NAME`, then the build complains about missing certificates. I'm currently using `CSC_NAME="Juan Cruz Viotti"`, which seems to match all.

Just to check if it made a difference, I decided to try exporting all the certificates as described in https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos, and use `CSC_LINK` instead.

After exporting all the mentioned certificates, `electron-builder` complains with the following error:

```
$ CSC_KEY_PASSWORD=1234 CSC_LINK=~/Desktop/Certificates.p12 npm run dist

> digital-clock@1.0.0 dist /Users/jviotti/Desktop/digital-clock
> build

electron-builder 19.16.0
No native production dependencies
Packaging for mas x64 using electron 1.6.6 to dist/mas-dev
Error: App is not signed: cannot find valid "Mac Developer" identity, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

All identities:
  1) 0D518D444C64B1848401633B6D4FCE4521B55DBD "3rd Party Mac Developer Application: Juan Cruz Viotti (97Z2ARC25P)"
  2) 05AA35FD83683D947C2C7BA92B4F1457C85CFDD2 "3rd Party Mac Developer Installer: Juan Cruz Viotti (97Z2ARC25P)"
  3) A47BD9C3F5673016668927D93AE986996ED5B761 "Developer ID Application: Juan Cruz Viotti (97Z2ARC25P)"
  4) 736F176DE52D79DB88DEABEAE0F67D6338C15C2D "Mac Developer: Juan Cruz Viotti (6AZR5XBJ4X)"
     4 identities found

  Valid identities only
  1) 0D518D444C64B1848401633B6D4FCE4521B55DBD "3rd Party Mac Developer Application: Juan Cruz Viotti (97Z2ARC25P)"
  2) 05AA35FD83683D947C2C7BA92B4F1457C85CFDD2 "3rd Party Mac Developer Installer: Juan Cruz Viotti (97Z2ARC25P)"
  3) A47BD9C3F56730166
```

The error doesn't make much sense, since it complains that the "Mac Developer" cert is missing, while its clearly there, in the list of detected certificates:

```
  4) 736F176DE52D79DB88DEABEAE0F67D6338C15C2D "Mac Developer: Juan Cruz Viotti (6AZR5XBJ4X)"
```

Could this all be related to some very weird code-signing issue I have? Can someone else try generating a `mas-dev` target out of my dummy app to confirm?

**Comment by jviotti** [comment]
Actually, in the above error message, `electron-builder` also displays a list of "Valid identities", and the "Mac Developer" one seems to be missing from that list. How can that be?

**Comment by jviotti** [comment]
Hm, so `6AZR5XBJ4X` seems to end up in `Info.plist` as my team ID, even though `97Z2ARC25P` is the correct one according to the Apple Developer dashboard. I'll try re-creating the certs all over again...

**Comment by jviotti** [comment]
Why is a `Mac Developer` cert required anyway? https://electron.atom.io/docs/tutorial/mac-app-store-submission-guide/ only mentioned that you need the "3rd Party Mac Developer" pair.

**Comment by jviotti** [comment]
I'm out of ideas. I registered an App ID in the Apple Developer dashboard, and configured electron-builder with it. I also create brand new certificates associated with that App ID and created and installed every type of provisioning profile for that App ID, and still the same issue :(

**Comment by develar** [comment]
@jviotti If you build `mas-dev` — it is dev only build and you need `Mac Developer`. If you want build for AppStore — use `mas`
