### ISSUE TITLE
Cwd of portable app

### ISSUE THREAD

**Issue by Losiara** [electron-userland/electron-builder#1796]
* **Version**: 
"electron-builder": "^19.12.0"

* **Target**: 
win=portable

While developing with command ```process.cwd()``` I get of app root dir. When I build single file app. I am getting app dir in the temp area. How can I get pwd() of portable built app?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1612#issuecomment-307724419
