### ISSUE TITLE
region in publish with s3 provider is invalidate.

### ISSUE THREAD

**Issue by chenhbc** [electron-userland/electron-builder#1800]
* **Version**: 19.12.0

2.4.4

* **Target**:  Mac & Windows

I configured the region attribute in the package.json file, But it didn't work.
![image](https://user-images.githubusercontent.com/5241418/27946643-3f8f407a-6325-11e7-8f25-71a061395721.png)

I printed it in s3.js, it is undefined.
![image](https://user-images.githubusercontent.com/5241418/27946730-9cc5cf98-6325-11e7-8a5f-2c9885548ae3.png)

![image](https://user-images.githubusercontent.com/5241418/27946758-b898ee30-6325-11e7-8d57-32db24a10ee4.png)

What's wrong with the configuration?

**Comment by develar** [comment]
Please try 19.5.3
