### ISSUE TITLE
Auto-update doesn't work with S3

### ISSUE THREAD

**Issue by Vj3k0** [electron-userland/electron-builder#1801]
* **Version**: 19.12.0

* **Target**: Mac and Windows

I've implemented all of the things like in Wiki, and publish works fine. All of the files are neatly uploaded. However, when I start the app, it states no updates available, but looking at the response, I see I get 204 No content. Do I need to setup something on S3 to accept request being made? I see that request is using execute-api, but I haven't worked with it before and don't know if there is something to do extra.

Any help would be appreciated. 

Great work btw. I'm updating app from builder v7. :-)

**Comment by develar** [comment]
Hi! Nice to see you again :)

Please https://github.com/electron-userland/electron-builder/wiki/Auto-Update#debugging and attach log here. Or contact me using slack :) to debug step by step :)

**Comment by Vj3k0** [comment]
Seems like I need generic provider instead of S3 to use it with our update architecture. I'll see if I can make it on my own. Thank so much! :-)
