### ISSUE TITLE
Add the possibility to specify exe name in squirrel windows packaging

### ISSUE THREAD

**Issue by lele85** [electron-userland/electron-builder#1802]
Hi there, i was using `grunt-electron-packager` to build windows setup and autoupdate package. The problem is that in order to not break the auto update of the currently released package i need to specify the `productFilename` and not infer it from the `productName`. I need to be 100% sure about the `.exe` file.

I digged into the source code and i hacked a solution that is quite easy to implement.

Is the feature planned?
Would you accept a PR on that?

**Comment by develar** [comment]
> Is the feature planned?

squirrel.windows in maintenance mode

> Would you accept a PR on that?

Yes, you need to add support for artifactName option in the Squirrel.Windows target.

**Comment by develar** [comment]
I don't know why and who vote 5 times for this issue, but `artifactName` is supported for squirrel.windows despite the fact that this target in the maintenance mode. 19.15.0 will be released in several days.

**Comment by lele85** [comment]
Hi there, maybe i didn't explain the issue in the right way, i'm not talking about the `setup.exe` name but the actual program executable name. I digged into electron builder source code and right now the program exe is calculated as `sanitizeFileName(productName)`.

**Comment by develar** [comment]
PR welcome (and testing).
