### ISSUE TITLE
Squirrel Windows and [Content_Types].xml

### ISSUE THREAD

**Issue by lele85** [electron-userland/electron-builder#1803]
I think i found an issue with the generated `.nupkg` update package when i package my project. The fact is that it seems the tool is generating a generic `[Content_Types].xml` file not taking in consideration the content of my resources folder.

```
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
    <Default ContentType="application/vnd.openxmlformats-package.relationships+xml" Extension="rels"/>
    <Default ContentType="application/octet" Extension="nuspec"/>
    <Default ContentType="application/octet" Extension="pak"/>
    <Default ContentType="application/octet" Extension="asar"/>
    <Default ContentType="application/octet" Extension="bin"/>
    <Default ContentType="application/octet" Extension="dll"/>
    <Default ContentType="application/octet" Extension="exe"/>
    <Default ContentType="application/octet" Extension="dat"/>
    <Default ContentType="application/vnd.openxmlformats-package.core-properties+xml" Extension="psmdcp"/>
    <Default ContentType="application/octet" Extension="diff"/>
    <Default ContentType="application/octet" Extension="bsdiff"/>
    <Default ContentType="text/plain" Extension="shasum"/>
</Types>
```
This is the generate file and doesn't take in account that i'm shipping some `.mp3` files  and a `.node` one in the `app.asar.unpacked` folder.

The result is that when the application download and installs the autoupdate these file are not copied in the application folder, resulting in a broken installation.

**Comment by develar** [comment]
I doubt — this logic for ages and no one report about it.

**Comment by lele85** [comment]
Actually i was quite surprised too. I spent half a day digging in `electron-builder` and `squirrel-windows` sources to understand if i was missing something but looks like `Content-Types` are only added here:

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-squirrel-windows/src/squirrelPack.ts#L141

Setting up a test case is quite tricky since i would need to prepare a project, an update `nupkg` package and host everything somewhere. I can assure the issue exists.
