### ISSUE TITLE
Using beta version of electron instead of latest stable

### ISSUE THREAD

**Issue by chris-malloy-mri** [electron-userland/electron-builder#1804]
* **Version**: 19.13.0

Electron builder is currently using 1.7.4, even though my package.json specifies 1.6.11. I also have 1.6.11 installed globally. The problem with this is that 1.7.4 is a beta build, and I want to be on the stable channel.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder* ` and attach log of the terminal output.

**Comment by chris-malloy-mri** [comment]
I'm not seeing any extra debug info from that. Is this what you are looking for?

`electron-builder 19.13.0
No native production dependencies
Packaging for win32 x64 using electron 1.7.4 to dist/win-unpacked
No native production dependencies
Packaging for win32 ia32 using electron 1.7.4 to dist/win-ia32-unpacked
Building NSIS installer
  Packaging NSIS installer for arch x64
  Packaging NSIS installer for arch ia32`

**Comment by black-snow** [comment]
Can't replicate this issue. Using 19.13.0, having electron 1.6.11 in my package.json:

```
Packaging for win32 ia32 using electron 1.6.11 to dist\win-ia32-unpacked
```

**Comment by chris-malloy-mri** [comment]
For me I tested on Linux and Mac. I have not tested on Windows. I recently switched to yarn, but I don't think that should have any effect.

**Comment by black-snow** [comment]
So you're building win on mac/linux with mono etc.? Can you provide your build config / package.json?

**Comment by chris-malloy-mri** [comment]
I am not doing anything special, just using the command line args for build.

package.json
```
{
  "private": true,
  "name": "",
  "productName": "",
  "author": {
    "name": "",
    "email": ""
  },
  "homepage": "",
  "version": "0.7.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "build --dir",
    "dist": "build"
  },
  "devDependencies": {
    "electron": "^1.6.11"
  },
  "build": {
    "appId": "",
    "mac": {
      "category": "",
      "type": "distribution"
    }
  },
  "postinstall": "install-app-deps"
}
```

build-win.sh
```
build -w --x64 --ia32 --project $folder
```

**Comment by black-snow** [comment]
Alright. Now I was able to reproduce this. When I look at `node_modules/electron/package.json` it actually is `1.7.4` so this ain't no typo but a real issue. Gonna investigate.

**Comment by develar** [comment]
@black-snow Please see computeElectronVersion method. If we cannot compute electron version, we simply ask Github about it (`/electron/electron/releases/latest`).

**Comment by black-snow** [comment]
My `yarn.lock` contained this:

```
electron@^1.6.11:
  version "1.7.4"
  resolved "https://registry.yarnpkg.com/electron/-/electron-1.7.4.tgz#db8b85ae98dffb7a82938e5ea6eed3cb66f62a65"
  dependencies:
    "@types/node" "^7.0.18"
    electron-download "^3.0.1"
    extract-zip "^1.0.3"
```

I deleted `node_modules/electron` and ran `yarn` again and voila, now it's 1.6.11 ...

**Comment by black-snow** [comment]
Alright: `^1.6.11` leads to `1.7.4` being installed wheres without the caret it's `1.6.11`. You probably do **NOT** want `^` (updates minors) but `~` (patch only).

**Comment by develar** [comment]
@black-snow But... `npm view electron`

```
'dist-tags': { latest: '1.6.11', beta: '1.7.4' }
```

So, update must not occur.

Anyway — you should use fixed electron version. No ^ or ~.

**Comment by black-snow** [comment]
@develar Yeah right. But it's `yarn` that installs `1.7.4` not `electron-builder` :)

**Comment by chris-malloy-mri** [comment]
Oh I see. I can confirm npm is upgrading to 1.7.4 for me, not build. I do want it to upgrade automatically with ^ though. I just don't want beta versions. Maybe this is an issue with the electron project.

**Comment by develar** [comment]
> Maybe this is an issue with the electron project.

No, it is yarn/npm issue, because `latest` is correctly set to `1.6.11` and `1.7.4` is a `beta`.

**Comment by chris-malloy-mri** [comment]
Thanks for looking into this.
