### ISSUE TITLE
How to disable publishing using programmatic API?

### ISSUE THREAD

**Issue by eriedl-kiban** [electron-userland/electron-builder#1805]
* **Version**: 
19.13.0

* **Target**: 
any

I upgraded from 17.7.0 to 19.13.0 after the code signing issue on macOS was fixed. Now I'm stuck as the build process assumes that building on Jenkins should also include publishing to somewhere. I don't want this. How do I disable it? The documentation says that you can use the command line switch `--publish never`. Howerver, we use the programmatic API to build and package the app. What is the equivalent in the programmatic API to disable publishing? Thank you.

**Comment by develar** [comment]
The same :)

add
```
publish: "never"
````

to the root options object.

**Comment by develar** [comment]
Or publish: null in the config.

**Comment by eriedl-kiban** [comment]
I had tried various combinations, but not that one 😫 : `publish: "never"` to the build config, which blew up as it's an unrecognized publish configuration. and `publish: null` to the root config, which also blew up.
Now it works as expected, thanks! 👍

**Comment by develar** [comment]
Yeah, we on the way to get rig of root object wrapper and use only config. For simplification.

**Comment by TLmaK0** [comment]
Empty array `publish: []` works for me.
