### ISSUE TITLE
s3-publisher pushes win & mac to same folder w/ os file macro 

### ISSUE THREAD

**Issue by brandonmp** [electron-userland/electron-builder#1808]
* **Version**: 
```
"electron": "^1.6.11",
    "electron-builder": "^19.13.0",
    "electron-devtools-installer": "^2.2.0",
    "electron-publisher-s3": "^19.12.0",
```

* **Target**: dmg,  nsis

My publish config is:

```
"publish": {
      "provider": "s3",
      "bucket": "my bucket",
      "path": "${channel}/${os}"
    },
```

and the build command is:

`build -mw --x64 --publish always`

so the dmg/zip should go to `my-bucket/latest/mac` and the exe should go to `my-bucket/latest/win`

However, both are ending up in `my-bucket/latest/mac`

**Comment by Vj3k0** [comment]
Same problem here.

**Comment by develar** [comment]
Duplicates #1323
