### ISSUE TITLE
nsis-web appPackageUrl property causes 404 error on web installer

### ISSUE THREAD

**Issue by xavero** [electron-userland/electron-builder#1810]
* **Version**: 19.13.0

* **Target**: nsis and nsis-web

When I define the **appPackageUrl** property in _nsis-web_ section, the web installer cannot download the 7zip files, because the installer script don't append the filenames to the Package Url

Example: 
- git clone https://github.com/xavero/electron-boilerplate
- run: 
  npm install && npm run installer
- start a web server on _dist_ folder and download **Electron Boilerplate Web Setup 0.0.0.exe**
- Run the installer to see the error of file not found

**Comment by develar** [comment]
Sorry for late response. It is by design, in the docs "URL like `https://example.com/download/latest` allows web installer to be version independent (installer will download latest application package).".

To provide own url — configure publish. e.g. generic provider.

```
{
  "provider": "generic",
  "url": "your url"
}
```

**Comment by xavero** [comment]
Sorry, didn't notice was by design. 
Can I change my PR to expose APP_PACKAGE_URL_IS_INCOMPLETE in some way ?

In my case I don't  have full control of the server, so I cannot send the correct zip file (ia32 or x64) for the client installer, since I cannot read the header of the request. 

I had to created 2 JSON config files, one for the NSIS Full Setup and another for the NSIS Web, and run the packaging 2 times.

**Comment by develar** [comment]
@xavero You are not forced to specify publish options for all targets. Simply specify it in the `nsisWeb`  and it will be applied only for web installer. Is it ok for you?

**Comment by xavero** [comment]
I feel dumb now.. I didn't realize that publish options was also a property for the nsis and nsisWeb targets... I was only setting in the root level.

Yes, I think that will work for me. Thanks for all the help.

**Comment by Alex-D** [comment]
@develar I'm sorry but I did not understand how it should works with CDN.

I can't read `X-Arch` since it's a CDN. I did not want to put a server to do a redirect since it's a point of failure.

Can we just set something like:

```javascript
build.nsisWeb.appPackageUrl = 'myapp-${arch}.nsis.7z'
```

For now, it's not possible, it crashes at build, but it will be more comfortable if we can use variables, at least arch's one.

Thanks :)

**Comment by PaoJiao** [comment]
@develar hello, in my  case, put `publish` into `nsisWeb` not work. it always try to download `xxx.nsis.7z` from `http://example.com/dist`. help plz.

```js
{
  // ...
  "nsisWeb": {
    "publish": {
      "provider": "generic",
      "url": "http://example.com/dist/nsis-web",
      "channel": "latest"
    }
  },
  "publish": {
    "provider": "generic",
    "url": "http://example.com/dist",
    "channel": "latest"
  }
  // ...
}
```
