### ISSUE TITLE
The module was compiled against a different Node.js version using NODE_MODULE_VERSION 51. This version of Node.js requires NODE_MODULE_VERSION 53.

### ISSUE THREAD

**Issue by AwsmOli** [electron-userland/electron-builder#1812]
* **Version**: 19.13.0

* **Target**: darwin x64

develar at the Slack Channel told me to report this - as it seems to be a bug:

im trying to get my Electron Ionic App packaged - so i followed the Quickstart and got the following Error: `The module was compiled against a different Node.js version using NODE_MODULE_VERSION 51. This version of Node.js requires NODE_MODULE_VERSION 53. (...).`

after consulting your Slack Channel develar suggested to try it with env `DEBUG=electron-builder*`

and trying: `"buildDependenciesFromSource": true,` in m `build` property of `package.json`

with  `"buildDependenciesFromSource": true` i saw it rebuilding serialport and it worked.

develar told me that this is still wrong behaviour and i should not need 
`"buildDependenciesFromSource": true`  
as he described to me:
> this options makes sense only for prebuild and prebuild must fallback to build from sources if no suitable version.
> in your case no fallback and it leads to runtime error.
> prebuild installs incorrect version instead of correct/rebuilding. Why — not clear yet.

[package.json  with `"buildDependenciesFromSource": true`](https://pastebin.com/2kLUyGie)
[Log of Successfull packaging with `"buildDependenciesFromSource": true` ](https://pastebin.com/rM8Eb26K)
[Logs of Unsuccessfull build](https://pastebin.com/mND50ff4)

i seem to be able to reproduce it when i delete my node_modules, then i use `buildDependenciesFromSource`once and do not delete my node_modules it keeps working (which makes sense to me)

**Comment by timfish** [comment]
You shouldn't usually need to use `buildDependenciesFromSource`. 

If you just want to build and native modules which are npm dependencies, just add the following to your npm scripts:

```
    "postinstall": "electron-builder install-app-deps",
```

**Comment by AwsmOli** [comment]
Yes, thats what i thought it says in the [quick setup guide](https://github.com/electron-userland/electron-builder#quick-setup-guide), so i added that line to my scripts in package json (see link to it in im original post).

But for some reason it did not help.

**Comment by develar** [comment]
@timfish For some not yet unknown reasons prebuild fails to install correct version.

**Comment by develar** [comment]
serialport uses ugly (sorry, but please do not use it, please use prebuild) node-pre-gyp instead of prebuild.

**Comment by develar** [comment]
I guess `electron-v54-*` is missed and because node-pre-gyp is not so good as prebuild, rebuild from sources is not occurred.

**Comment by develar** [comment]
I am sorry, but I don't have time to support node-pre-gyp. https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1180#issuecomment-314674524 Please ask node modules authors to use prebuild or just fork such module and fix it. if you are commercial company, you can donate and I will do something like https://github.com/atom/node-keytar/pull/67 for you.

**Comment by develar** [comment]
Yes — my intention to not support `node-pre-gyp` and do not add any workarounds if some module still use it. It violates electron-builder project rules, but I hope it will make current strange and absurd situation more visible and in the end, all authors of native modules for Electron, will use prebuild and it will make Electron development more easy.

**Comment by islemaster** [comment]
Ran into a this issue today on [my project](https://github.com/code-dot-org/browser) that uses `electron-builder` and `node-serialport` and was worried it would be a nightmare to track down.

Turns out it was as simple as updating my dependencies (as described [at the end of this thread](https://github.com/node-serialport/node-serialport/issues/1180#issuecomment-321874626)). `node-serialport` switched to `prebuild` [in version 6.0.0 about three weeks ago](https://github.com/node-serialport/node-serialport/blob/master/CHANGELOG.md#600-2017-10-09).  Now things are just working, without `buildDependenciesFromSource` or the postinstall `install-app-deps` step.  Recording here for others who stumble upon this thread. Thanks @reconbot!

**Comment by timfish** [comment]
On changing electron version you should always remove `node-modules` and install all dependencies again. On Windows I sometimes have to clear out the node-gyp cache/temp directory before everything will build again.

**Comment by ramnivash** [comment]
delete node_module and run npm i

**Comment by Pimentoso** [comment]
Can I necro this issue or should I open a new one? I'm having the exact same problem except updating serialport is not helping.



* **Version**: "22.7.0"



* **Electron Version**: "5.0.13"
* **Electron Type (current, beta, nightly)**: current



* **Target**: darwin x64

My package.json

```json
  "dependencies": {
    "clone": "^2.1.2",
    "electron-log": "^3.0.5",
    "electron-settings": "^3.2.0",
    "electron-updater": "4.3.1",
    "exceljs": "^1.10.0",
    "johnny-five": "1.5.0",
    "jquery": "^3.5.0",
    "nconf": "^0.10.0",
    "node-pixel": "Pimentoso/node-pixel",
    "serialport": "^8.0.8",
    "underscore": "^1.9.1"
  },
  "devDependencies": {
    "electron": "5.0.13",
    "electron-builder": "22.7.0",
    "electron-reload": "^1.4.0"
  },
  "scripts": {
    "start": "./node_modules/.bin/electron .",
    "build": "electron-builder build --mac --win --publish never",
    "deploy": "electron-builder build --mac --win --publish always"
  },
```

I'm deleting the node_modules dir, then running npm install

```bash
npm install                                                                                                                                            ✔  5272  22:28:15

> @serialport/bindings@8.0.8 install /Users/xxx/node_modules/serialport/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild


> ejs@3.1.3 postinstall /Users/xxx/node_modules/ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> serialport@8.0.8 postinstall /Users/xxx/node_modules/serialport
> node thank-you.js

Thank you for using serialport!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/serialport/donate



> electron@5.0.13 postinstall /Users/xxx/node_modules/electron
> node install.js

added 543 packages from 391 contributors and audited 544 packages in 12.873s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

Error I'm getting:

```bash
Error: The module '/Users/xxx/node_modules/serialport/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (/Users/xxx/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/xxx/node_modules/serialport/node_modules/@serialport/bindings/lib/darwin.js:2:36)
```

I tried with and without the postinstall rebuild script. Everything works using electron-rebuild but I want to move away from it.
