### ISSUE TITLE
windows portable apps and automatic update

### ISSUE THREAD

**Issue by amircodota** [electron-userland/electron-builder#1813]
Hi, There

I'm using electron builder 17.10.0.

I can successfully create an nsis installer, and publish it to S3. I also have automatic updates working.

I recently got a request to create a portable app in addition to the nsis installer, to support users who cannot run an installer due to corporate policy,
When testing it, I can successfully build and run a portable app. However, no latest.yml file is generated, so while I can successfully publish to S3, there is no automatic updates for new versions.

Is automatic updates for windows portable apps supported somehow, and I am missing something? If it is not supported, do you have a recommendation as to how to achieve automatic updates for portable apps?

Thanks a lot 

Amir

**Comment by develar** [comment]
Portable means portable :) No auto-updates.

> cannot run an installer due to corporate policy

If portable allowed, install should be allowed too. Do you use per machine or default per user?

**Comment by amircodota** [comment]
Thanks for the answer.

I'll take a look at the per machine vs per user, see if it solves my customer issue.

Thanks

**Comment by bmsuseluda** [comment]
> Portable means portable :) No auto-updates.
> 
> > cannot run an installer due to corporate policy
> 
> If portable allowed, install should be allowed too. Do you use per machine or default per user?

@develar in my opinion, one does not exclude the other. For me a portable app only means that it can be copied to a another folder or computer and just works, so it has everything it needs to run. for me AppImage on linux is a portable too and electron builder provides an auto update mechanism for it. So im curious why not for windows portables as well?
Thanks in regards
