### ISSUE TITLE
19.15.1 reports wrong version during build

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1816]
* **Version**: 19.15.1

* **Target**: Windows ia32 NSIS

Output:

```
> build --ia32 --dir

electron-builder 0.0.0-semantic-release
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 ia32 using electron 1.7.4 to dist\win-ia32-unpacked
```

It should say electron-builder `19.15.1`.

**Comment by black-snow** [comment]
This is the spot: https://github.com/electron-userland/electron-builder/blob/452085b7ba9034e0a7a9f6664de1b749ea172bc6/packages/electron-builder/package.json#L4

**Comment by black-snow** [comment]
develar has addressed this - guess it will be fixed in the next release
