### ISSUE TITLE
Do not add ` "x-amz-acl": "public-read"` to the header when uploading artefacts to S3 bucket

### ISSUE THREAD

**Issue by romanrev** [electron-userland/electron-builder#1822]
* **Version**:  18.3.0
* **Electron-Updater**: 2.0.0
* **Target**:  OSX/Windows

We have to allow the `s3:PutObjectAcl` in the IAM policy for the `electron-builder` to be able to successfully upload the artefacts to the S3 bucket, since it always adds a header ` "x-amz-acl": "public-read"` with each upload request - trying to mark every object it uploads to the bucket as publicly readable. 
I suggest that this behaviour should be optional - and not the default one, since one can also achieve the same effect with appropriately crafted S3 bucket policy - which we actually prefer to.
Another use case is when an S3 bucket with the built artefacts should not be publicly accessible at all.

**Comment by develar** [comment]
> and not the default one

Cannot agree because for most users it is what we should do. Because we cannot complicate documentation and ask to do some additional steps.

**Comment by romanrev** [comment]
well, please at least make an option to disable that behaviour, thank you

**Comment by develar** [comment]
19.16.0 — you can set acl to null to disable adding. Will be released today.

**Comment by develar** [comment]
@romanrev Released. Please check.

**Comment by romanrev** [comment]
thanks, much appreciated for your speedy resolution of the issue!
