### ISSUE TITLE
fix: msi does not seem to work with squirrel target

### ISSUE THREAD

**Issue by jeansebbaklouti** [electron-userland/electron-builder#1823]
Hello,
I use electron-builder 19.10.0 and i try to build a msi package with this configuration on ubuntu:
```
"win":{
     "icon":"./app/icones/myicone.ico",
     "target": ["squirrel"]
    },
    "squirrelWindows":{
      "msi":true
    }
...
}
```

but the only package that i get is an ".exe",
someone has an idea ? there are something wrong ? 
do you need more information ?

Ideally, i would like to use nsis target, but it seems impossible to build msi package with nsis target!?

best,
Jean-Sébastien

**Comment by develar** [comment]
You can build MSI for Squirrel.Windows only on Windows.

NSIS is recommended — and there is an easy way to build MSI — https://github.com/electron-userland/electron-builder/issues/723#issuecomment-244815601 In short: http://www.exemsi.com/

**Comment by jeansebbaklouti** [comment]
ok thanks for your answer, i read this post, but i can not use http://www.exemsi.com/ on my building platform. With this tools , we can only do the job manually.

**Comment by develar** [comment]
> With this tools , we can only do the job manually.

Sorry, but MSI support will be added only if will be donated.
