### ISSUE TITLE
MSI Support for NSIS

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#1825]
* **Version**: Latest

* **Target**: Windows

 Would it be possible to support building an MSI programmatically? We are able to build for Windows using NSIS perfectly, but some clients require an .msi in order to install via GPO. 

I'm aware of a number of GUI tools that allow you to do this rather easily, but we'd obviously much prefer this be done on CI along with the rest of our build process. It seems that the WiX Toolset may provide a way to do this within wine, but that's a little out of my expertise. Happy to help in any way.

Best,
Nader

**Comment by develar** [comment]
Duplicates #723
