### ISSUE TITLE
.NetCore + Electron

### ISSUE THREAD

**Issue by willsicko** [electron-userland/electron-builder#1830]
"electron": "^1.4.1"
"electron-builder": "^19.16.0"

Hey everyone, I try to build a project in .NetCore + electron, but I stuck. I don't if that possible

![image](https://user-images.githubusercontent.com/9969564/28196094-efb021a2-6813-11e7-8583-ae1bb105e6c9.png)

I was able to create a project to read a  exe project NetCore.

![image](https://user-images.githubusercontent.com/9969564/28196475-80e6b1b6-6816-11e7-90ac-1fccba446ffa.png)

but when I try to run the exe electron doesn't work.
![image](https://user-images.githubusercontent.com/9969564/28196454-65a112a2-6816-11e7-8dce-cc2c4ab849be.png)

doesn't launch.

Ps: Sorry for my english

**Comment by develar** [comment]
Not clear for me how do you use NetCore.

**Comment by willsicko** [comment]
first I execute the exe of project netcore webapplication, and the remote server is mounted

![image](https://user-images.githubusercontent.com/9969564/28225133-31432c6c-6897-11e7-83de-6c3db308fc10.png)


then I connect the localhost and I read the  project

![image](https://user-images.githubusercontent.com/9969564/28225519-977e749a-6898-11e7-9c53-26994eb868e2.png)


@develar

**Comment by develar** [comment]
Does it work before packaging?

**Comment by alex-erygin** [comment]
https://scotch.io/@rui/how-to-build-a-cross-platform-desktop-application-with-electron-and-net-core

**Comment by GregorBiswanger** [comment]
Hi, 
we coded an open source solution for electron with .net core: **Electron.NET**.
[https://github.com/ElectronNET/Electron.NET](https://github.com/ElectronNET/Electron.NET)

Enjoy!
