### ISSUE TITLE
Installed build has duplicates of several .exe in resources folder

### ISSUE THREAD

**Issue by scott-plutovr** [electron-userland/electron-builder#1831]
* **Version**: electron-builder 17.1.1

I don't think we are?

* **Target**: "squirrel"

An installed build has duplicates of the executables. One copy at the top level of the `resources` folder and the others down in their various sub-directories.

We are also using electron-builder-squirrel-windows 19.2.0 along with electron 1.6.6.
We are using the `extraResources` array to include one directory containing an application that is launched and we couldn't ever get it to launch properly when included in the .asar. This also happens with `"asar": false`. Things look fine in the win-unpacked folder after doing the `npm run dist`.

**Comment by scott-plutovr** [comment]
FYI installed looks fine if I update `electron-builder` from 17.1.1 to 19.16.0 and `electron-builder-squirrel-windows` from 19.2.0 to 19.16.0. Not sure which one of these is the culprit but I'll see if just updating one takes care of things.

**Comment by scott-plutovr** [comment]
Well, `electron-builder-squirrel-windows` 19.16.0 has a peer dependency on `electron-builder` 19.16.0 so I can't test just reverting `electron-builder`. I'll probably just stay with the latest versions since it appears to be working.

**Comment by develar** [comment]
It was bug in the Squirrel and now it is fixed.
