### ISSUE TITLE
Questions regarding onTagOrDraft

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-builder#1835]
* **Version**: 19.16.0

* **Target**: Windows, Linux & macOS

I don't seem to understand the `onTagOrDraft` argument specified in the following command:

```
electron-builder --publish onTagOrDraft
```

My understanding from [Publishing Artifacts](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts) is that artifacts are uploaded from Travis CI to GitHub if a release draft exists, but are not uploading anything if the draft doesn't exist.

It's obviously a misunderstanding from me, because the [Travis build](https://travis-ci.org/FantasticFiasco/magellan/jobs/254502804) is creating the draft, and then uploads the artifacts. How should I configure `electron-builder` to upload the artifacts only as long as there is a draft?

**Comment by develar** [comment]
You are right. Fixed.
