### ISSUE TITLE
node-notifier is not put in .asar.unpacked

### ISSUE THREAD

**Issue by arantes555** [electron-userland/electron-builder#1841]
* **Version**: 19.16.0

* **Target**: MacOS

I'm building an app that uses node-notifier. When in dev, it works correctly. However, once packaged, there are no notifications, and no error is thrown.
It turns out that node-notifier's included executables are not automatically detected and put in the .asar.upacked upon build, which prevents to call the executables.

As a workaround, adding `"asarUnpack": ["./node_modules/node-notifier/vendor/**"]` to the config works.

This problem did not happen before I bumped electron-builder from 16.1.0 to 19.16.0 .

I know this issue is similar to #1683 , but it's not the same, as in it the executables are put in the .asar.unpacked but somehow are not executed.

**Comment by develar** [comment]
Thanks for report, I will check. 

Do not use node-notifier. Please use Electron API.

**Comment by arantes555** [comment]
We explored that option, but the native electron API offers much less options and control than node-notifier, and has less compatibility with older systems. It looks like it's a bit better now than it used to be last time I checked. However, the fact that it's renderer-process-only is still quite cumbersome.

**Comment by develar** [comment]
> However, the fact that it's renderer-process-only is still quite cumbersome.

Not anymore in the recent Electron :)

**Comment by aguynamedben** [comment]
@arantes555 Thanks for the workaround 👍 

FWIW the main process version of `Notification` is [marked as experimental](https://electronjs.org/docs/api/notification#new-notificationoptions-experimental), but great to see it's on the way to being added to Electron!

**Comment by arantes555** [comment]
@develar I'm sorry but the issue is still not obsolete. I just tested right now with the latest electron-builder, and the issue still exists. The existence of the `Notification` API should not in any way allow electron-builder to not do what its doc says and put executables in `.asar.unpacked` automatically, just because in this specific case it happens to be a package that deals with notifications.

**Comment by bvallier** [comment]
Add "node-notifier": "^5.3.0" to your dependencies (in addition to your devDependencies) and try to rebuild. That worked for me.
