### ISSUE TITLE
There doesn't seem to be a way to publish without also rebuilding

### ISSUE THREAD

**Issue by iffy** [electron-userland/electron-builder#1842]
* **Version**: 18.6.2

* **Target**: macOS, Windows, Linux

I want to be able to build on macOS for macOS and the docker+wine image for Windows and Linux (because I have native dependencies) and then do `build -p always --no-build` to just upload the files (without rebuilding).

**Comment by develar** [comment]
Why it is a problem? Why you cannot fix native dep to use prebuild? Btw — wine not a solution to build native dep.

**Comment by iffy** [comment]
@develar I have no idea how to use `prebuild` is one problem :)  I'm trying to get sqlite to work on macOS, Linux, Windows.

If I figure out how to use `prebuild` I'll happily contribute back some documentation.

**Comment by develar** [comment]
Fork native module and prepare PR like https://github.com/atom/node-keytar/pull/67 publish as moduleName-prebuild until PR is no accepted. Enjoy build on any platform.

**Comment by iffy** [comment]
@develar sqlite3 already has prebuilt binaries: https://github.com/mapbox/node-sqlite3/wiki/Binaries  but I don't know how to use them.

For instance, what does `package.json` look like for an Electron app with sqlite3 that builds for macOS, Linux and Windows?

What command do I run to package the app?

**Comment by develar** [comment]
This module uses node-pre-gyp — and this module is not good.

**Comment by develar** [comment]
Please see https://github.com/mapbox/node-sqlite3/issues/840

**Comment by iffy** [comment]
But what do I **do**?  I'm looking for an example Electron application that has Sqlite and builds on Linux, Windows and macOS.  I'm happy to create such an example, but I can't figure out where I'm supposed to even start.

**Comment by develar** [comment]
Fork sqlite3, get rid of node-pre-gyp, use prebuild as in the example above.

Or just wait when someone will donate and I will do it. And build only on target platform.

**Comment by bompi88** [comment]
@develar An option to publish without rebuilding could be nice to have if you need to run some tests on the build before publishing. Or is there alternative ways of doing this? I've to run my app to test whether the correct version of fibers is bundled with my build, so I know for sure whether my users can run the app properly.

**Comment by develar** [comment]
You can set `afterPack` function to verify packaged app:

```ts
(context: AfterPackContext) => Promise<any> | null
```

**Comment by develar** [comment]
Probably you want ability to set `afterPack` to path to some script, right?

**Comment by bompi88** [comment]
@develar yes, thats right. I need to use the programatic API for this, right?

**Comment by bompi88** [comment]
I found my answer to this 👍 `programmatic API only`
