### ISSUE TITLE
[Windows] DLL Hijacking vulnerability

### ISSUE THREAD

**Issue by LucasVidal** [electron-userland/electron-builder#1843]
* **Version**: 13.11.1

* **Target**: macos, win32, win64

Hi! We packaged a version of our electron app and distributed. However received reports that some .dlls are not being loaded properly, and thus, becoming a vulnerability.

> "The installer contains a DLL hijacking vulnerability that could allow an unauthenticated, remote attacker to execute arbitrary code on the targeted system. This vulnerability exists due to some DLL file is loaded by ‘installer.exe’ improperly. And it allows an attacker to load this DLL file of the attacker’s choosing that could execute arbitrary code without the user's knowledge.
Affected DLLs mentioned below:
 api-ms-win-core-synch-l1-2-0.dll
 api-ms-win-core-fibers-l1-1-1.dll
 api-ms-win-core-localization-l1-2-1.dll
 api-ms-win-core-synch-l1-2-0.dll
 api-ms-win-core-fibers-l1-1-1.dll
 api-ms-win-core-localization-l1-2-1.dll"

Where and how are they linked? Is there any way we can fix this?
Thanks!

**Comment by develar** [comment]
It seems you use 1.7.4 electron :) Could you please try to use latest electron-builder?

**Comment by athomson1** [comment]
Hello @develar 
We have had the same report, and confirmed the vulnerability ourselves.

`"electron-builder": "19.16.2"`
`"electron": "^1.6.11"`

Any idea? Thanks!

**Comment by develar** [comment]
You cannot have the same report because these dll should only in the 1.7.5 version ;)

**Comment by LucasVidal** [comment]
Thanks for replying... but what I meant is that I could reproduce the vulnerability with the latest version. 
![electron-builder-dll-injection](https://user-images.githubusercontent.com/668566/29095495-8f1eb702-7c56-11e7-98cc-87a16d1b7182.png)

**Comment by athomson1** [comment]
Thanks for replying, but what I meant is that I could reproduce the vulnerability with the latest version.
![electron-builder-dll-injection](https://user-images.githubusercontent.com/30703791/29095534-b18a62aa-7c56-11e7-9cf1-af9cb481a175.png)
