### ISSUE TITLE
Blank screen on build

### ISSUE THREAD

**Issue by EthanBogart** [electron-userland/electron-builder#1851]
* **Version**:  19.16.2

* **Target**: Mac x64

Hello, I have a pretty tiny (so far) Electron app. It runs fine on `electron .` but when I run `build -m --x64` or `build` the resulting app simply gives me a white screen. Is there any way to debug this? Are there some common issues that may give this result? I looked on Google but couldn't find anything.

**Comment by EthanBogart** [comment]
Just donated to increase priority.

**Comment by hengkx** [comment]
open dev tools ,See what is wrong。`window.openDevTools();`

**Comment by develar** [comment]
I recommend you to use https://github.com/sindresorhus/electron-debug So, when app is packed, you can use shortcuts to open devtools.

**Comment by EthanBogart** [comment]
@hengkx @develar Thank you! I'm trying out electron-debug first.

**Comment by EthanBogart** [comment]
Update: The window.openDevTools did the trick. So now here's my problem, and I can't figure out exactly what's wrong. 

So when I open the debug menu, the exact error I get is `Uncaught Error: Cannot find module` where I require my `start.js` file. I have made sure all these files are listed either in `files` or under `buildResources` so I don't know what I'm doing wrong here.
