### ISSUE TITLE
Cannot find module '***' [Windows]

### ISSUE THREAD

**Issue by cmzz** [electron-userland/electron-builder#1852]
* **Version**: 19.16.0

* **Target**:  windows 7 x64

Im building an app on windows.  When build success and run app , then got error "Cannot find module "ultron".

If add "ultron"  to dependencies,  got an other error : "Cannot find module "safe-buffer".

I know issuse [217](https://github.com/electron-userland/electron-packager/issues/217) but cannot work for me .  `module.paths is undifined` ?

Anyone have ideas..

![image](https://user-images.githubusercontent.com/6111715/28507287-4a75e65a-7064-11e7-914b-e89bf300a75a.png)

![image](https://user-images.githubusercontent.com/6111715/28507293-52f7d234-7064-11e7-9a5d-66b8dbfc9373.png)

![image](https://user-images.githubusercontent.com/6111715/28507304-6c7ee1c0-7064-11e7-8136-ceb334e2331c.png)

![image](https://user-images.githubusercontent.com/6111715/28507316-8b4fe928-7064-11e7-8bb1-c7e0b04b0773.png)

You see, if build on mac, more modules did put in than build on windows in `win-unpacked\resources\app\node_modules` folder

**Comment by cmzz** [comment]
Config in packages.json

```
"build": {
    "asar": false,
    "productName": "pigtk-robot",
    "appId": "org.simulatedgreg.electron-vue",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico",
      "publish": [
        "github"
      ],
      "target": "squirrel",
      "certificateFile": "./certs/pigtk-robot.pfx",
      "certificatePassword": "my_password"
    }
...
}
```

**Comment by hengkx** [comment]
try rebuild,[electron-rebuild](https://github.com/electron/electron-rebuild)

**Comment by develar** [comment]
@hengkx Not required, electron-builder automatically rebuilds.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder:* ` and attach log of the terminal output.

**Comment by cmzz** [comment]
@develar Thanks for help.

![image](https://user-images.githubusercontent.com/6111715/28513238-e721a8cc-7087-11e7-93b6-e0b5a0bdc1bf.png)
![image](https://user-images.githubusercontent.com/6111715/28513260-f4f43a32-7087-11e7-8850-36bd2bb09dcf.png)

**Comment by cmzz** [comment]
@develar Its work fine with version `19.10.0`

**Comment by develar** [comment]
@cmzz Could you please provide project to reproduce?

**Comment by cmzz** [comment]
@develar Sure

**Comment by cmzz** [comment]
Above version `19.13.0`,  Cannot pack all npm module.

**Comment by develar** [comment]
Do you use npm or yarn? Please remove `package-lock.json` and `node_modules` And install using yarn (not npm) again.

**Comment by develar** [comment]
As far I see (in my case solution "remove package-lock.json" helps), DO NOT USE F**** NPM. Sorry for  capslock, but please do not ever use npm and never store `package-lock.json` (if you use npm by error, remove created package-lock.json after it and use only yarn).

**Comment by develar** [comment]
Tip: node-notifier not required anymore — latest electron can show notifications from main process.

**Comment by cmzz** [comment]
@develar Aha  thanks... Its work for me now. FUCK NPM

**Comment by hrwndr** [comment]
Hi,
i solved it by migrating from npm to yarn.. that worked!!

**Comment by orzechdev** [comment]
I had the same issue with pnpm. After migrating to yarn the issue is solved. But what was the reason and why it doesn't work with pnpm?

**Comment by dieharders** [comment]
I spent all day trying to get this to work. Switching from PNPM to YARN worked for me. No idea why pnpm doesn't work but npm is referenced in the docs as if you have a choice but you dont.

Yarn should really be documented as the ONLY package manager that works with electron-builder (again, NO idea why? someone enlighten me?)
