### ISSUE TITLE
[electron-updater] response from Generic Provider getLatestVersion becomes [ 'Object object' ]

### ISSUE THREAD

**Issue by vuamitom** [electron-userland/electron-builder#1853]
* **Version**: 
electron-builder 19.16.0

electron-updater 2.7.1 

* **Target**: Windows 64bit

Look like something wrong with the call to HttpExecutor in Generic Provider. 

`result = safeLoad(await this.executor.request<string>(options))`

result objects becomes ['Object object'] instead of the proper json that has been returned. 

Reverting to electron-updater 1.15.0, where HttpExecutor is not used, fixes this issue.

**Comment by develar** [comment]
Is your server returns correct JSON mime-types?

**Comment by develar** [comment]
Ok, code will be simplified to avoid such errors.

**Comment by vuamitom** [comment]
> Is your server returns correct JSON mime-types?

It's returning response with header: 'Content-Type': 'application/json'

**Comment by develar** [comment]
Please try new version.

**Comment by vuamitom** [comment]
Thank you, that was a quick fix.
