### ISSUE TITLE
Can't set app version through `--em.version` parameter

### ISSUE THREAD

**Issue by zhaoyi0113** [electron-userland/electron-builder#1854]
I am using electron-builder to build a desktop application. I use below configuration in `package.json` file to build the app by electron-builder:

```
    "scripts":{
        "dist": "build --em.mode=prod --em.version=07-24-2017"
    }
```

The application can be built but I get below error when I launch it:

```
    App version is not valid semver version: "24-07-2017
```

How can I set electron build version?

**Comment by develar** [comment]
Version must be according to semver rules, the same as npm package version.
