### ISSUE TITLE
Cannot run when install into C://program files/

### ISSUE THREAD

**Issue by chenyuncai** [electron-userland/electron-builder#1858]
* **18.5.1**: 

* **win32-x64**: 

Hi, there is a problem I encountered:

we build a executable exe file with nsis config's perMachine true.

now we install the app into the exact path

the problem is: the app cannot start by double click.

I checked the processes in taskManager. It is running but there is any browser window showing or logs in my log file.

Then, I choose run as admin, It runs correctly as normal as which with the build config "oneClick: true"

Thanks!

Now we have to package the installer with simple config that install into the user's appData directory.

I want to know is there any other config that I can avoid this and it also can install into any path

Thanks again.

ps: we cannot update the builder to latest as we have use this version for a long time

**Comment by develar** [comment]
Please use 19.16.3

**Comment by chenyuncai** [comment]
OK, I'll try it. Thanks.
