### ISSUE TITLE
Error downloading electron-builder required tools files

### ISSUE THREAD

**Issue by evollhhan** [electron-userland/electron-builder#1859]
* **Version**:  19.12.0

For some reason, the building process could not download winCodeSign, nsis-resources and other files automatically, always get timeout errors(maybe blocked by some wall). Could I just download the electron-builder-binaries zip from github or some other sites and extract to a specific folder so i can skip the download process when building my app? Thx

**Comment by develar** [comment]
Yes — https://github.com/electron-userland/electron-builder-binaries/releases

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder-binaries/releases/tag/winCodeSign-1.9.0

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-resources-3.0.0

**Comment by develar** [comment]
Unpack using 7z to cache dir.

**Comment by evollhhan** [comment]
Many thanks for prompt reply.

**Comment by SaromChars** [comment]
where are these tool files should be put in ??

**Comment by develar** [comment]
macOS:  `~/Library/Caches/electron-builder`
Linux: `~/.cache/electron-builder`
windows: `%LOCALAPPDATA%\electron-builder\cache`

**Comment by develar** [comment]
```
.
├── AppImage
│   ├── AppImage-09-07-16-mac
│   └── AppImage-17-06-17-mac
├── AppImage-packages
│   └── 10.03.17
├── Squirrel.Windows
│   ├── Squirrel.Windows-1.5.2.0
│   └── Squirrel.Windows-1.6.0.0
├── fpm
│   └── fpm-1.8.1-20150715-2.2.2
├── linux-tools
│   └── linux-tools-mac-10.12
├── nsis
│   └── nsis-3.0.1.13
├── nsis-resources
│   ├── nsis-resources-3.0.0
│   └── nsis-resources-3.1.0
├── winCodeSign
│   └── winCodeSign-1.9.0
└── wine
    └── wine-2.0.1-mac-10.12
```

**Comment by SaromChars** [comment]
thx！！！

**Comment by develar** [comment]
Zip file to extract instead of tedios downloading:  https://drive.google.com/file/d/0Bz3JwZ-jqfROc1FNT25FeTVoRWM/view?usp=sharing

**Comment by myfrndjk** [comment]
Hi,

I also face a similar problem.
I downloaded all dependencies from https://drive.google.com/uc?export=download&id=0Bz3JwZ-jqfROc1FNT25FeTVoRWM

keep that in my `project/resources` folder.
When I try to run `cp-r project/resources/* ~/.cache/electron-builder` I get `/.cache/electron-builder': No such file or directory`

Is there any way i can use `project/resources/` as dependencies rather than pushing it to cache
Any sample would be great

Thanks
Jk

**Comment by divefox** [comment]
mark & thx!

**Comment by ZhouHansen** [comment]
@develar Could you please explain this question in detail?
> where are these tool files should be put in ?? 

I use windows, and the files unzipped from the winCodeSign-2.4.0 which I downloaded manually are below:

![_20190201174951](https://user-images.githubusercontent.com/8222181/52115550-d89ac300-2649-11e9-9943-d12468420310.png)

And in `%LOCALAPPDATA%\electron-builder\cache`, there's a `winCodeSign`  directory, which files should I put into the `winCodeSign`  directory?

And after put the right thing to `winCodeSign`  directory, when I run `npm run builder`, will electron-builder still download the  `winCodeSign`  automatically?

@SaromChars 新年好！能告诉我怎么解决这个问题么？

**Comment by Gabrielkaliboy** [comment]
Can you change these files to another storage location?Current storage locations are painful for Chinese developers

**Comment by BadReese** [comment]
In China , simply use command ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ npm run dist

**Comment by Ahmedkholaif** [comment]
> Zip file (92MB) to extract instead of tedios downloading: https://drive.google.com/uc?export=download&id=0Bz3JwZ-jqfROc1FNT25FeTVoRWM
> 
> Or 7z archive (40MB) https://drive.google.com/uc?export=download&id=0Bz3JwZ-jqfRORjZTa3FPWUpJT0E

this file isn't available anymore. how can I get it?
and how to skip the download stage and read from the cache? 
thanx for the great efforts

**Comment by rohitisinhk** [comment]
> ```
> .
> ├── AppImage
> │   └── AppImage-17-06-17-mac
> ├── AppImage-packages
> │   └── 10.03.17
> ├── Squirrel.Windows
> │   └── Squirrel.Windows-1.6.0.0
> ├── fpm
> │   └── fpm-1.8.1-20150715-2.2.2
> ├── linux-tools
> │   └── linux-tools-mac-10.12
> ├── nsis
> │   └── nsis-3.0.1.13
> ├── nsis-resources
> │   └── nsis-resources-3.1.0
> ├── winCodeSign
> │   └── winCodeSign-1.9.0
> └── wine
>     └── wine-2.0.1-mac-10.12
> ```

nsis-resources now reside under nsis

**Comment by mohamed-assif-z** [comment]
nsis-resources-3.4.1.7z always downloading even after manually downloaded and inserted into "%LOCALAPPDATA%\electron-builder\cache"

> electron-builder build --win -c.extraMetadata.main=build/electron.js --publish never

  • electron-builder  version=22.9.1 os=10.0.18363
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • description is missed in the package.json  appPackageFile=C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\package.json
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=10.1.3 appOutDir=dist\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=dist\test Setup 0.1.0.exe archs=x64 oneClick=true perMachine=false
  ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z": proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        Y:/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        Y:/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        Y:/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        Y:/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/download.DownloadArtifact
        Y:/Documents/app-builder/pkg/download/artifactDownloader.go:107
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
        Y:/Documents/app-builder/pkg/download/artifactDownloader.go:27
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        Y:/Documents/app-builder/main.go:90
runtime.main
        c:/go/src/runtime/proc.go:203
runtime.goexit
        c:/go/src/runtime/asm_amd64.s:1373  
  ⨯ C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

                             Error: C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

                                 at ChildProcess.<anonymous> (C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\builder-util\src\util.ts:243:14)

                                 at Object.onceWrapper (events.js:421:26)

                                 at ChildProcess.emit (events.js:314:20)

                                 at maybeClose (internal/child_process.js:1051:16)

                                 at Socket.<anonymous> (internal/child_process.js:442:11)

                                 at Socket.emit (events.js:314:20)

                                 at Pipe.<anonymous> (net.js:673:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 electron-pack: `electron-builder build --win -c.extraMetadata.main=build/electron.js --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 electron-pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-10-19T05_25_01_242Z-debug.log

**Comment by mohamed-assif-z** [comment]
> nsis-resources-3.4.1.7z always downloading even after manually downloaded and inserted into "%LOCALAPPDATA%\electron-builder\cache"
> 
> > electron-builder build --win -c.extraMetadata.main=build/electron.js --publish never
> 
> • electron-builder version=22.9.1 os=10.0.18363
> • loaded configuration file=package.json ("build" field)
> • loaded parent configuration preset=react-cra
> • description is missed in the package.json appPackageFile=C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\package.json
> • writing effective config file=dist\builder-effective-config.yaml
> • packaging platform=win32 arch=x64 electron=10.1.3 appOutDir=dist\win-unpacked
> • default Electron icon is used reason=application icon is not set
> • building target=nsis file=dist\test Setup 0.1.0.exe archs=x64 oneClick=true perMachine=false
> ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z": proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.
> github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
> Y:/Documents/app-builder/pkg/download/downloader.go:206
> github.com/develar/app-builder/pkg/download.(*Downloader).follow
> Y:/Documents/app-builder/pkg/download/downloader.go:234
> github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
> Y:/Documents/app-builder/pkg/download/downloader.go:128
> github.com/develar/app-builder/pkg/download.(*Downloader).Download
> Y:/Documents/app-builder/pkg/download/downloader.go:112
> github.com/develar/app-builder/pkg/download.DownloadArtifact
> Y:/Documents/app-builder/pkg/download/artifactDownloader.go:107
> github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
> Y:/Documents/app-builder/pkg/download/artifactDownloader.go:27
> github.com/alecthomas/kingpin.(*actionMixin).applyActions
> C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
> github.com/alecthomas/kingpin.(*Application).applyActions
> C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
> github.com/alecthomas/kingpin.(*Application).execute
> C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
> github.com/alecthomas/kingpin.(*Application).Parse
> C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
> main.main
> Y:/Documents/app-builder/main.go:90
> runtime.main
> c:/go/src/runtime/proc.go:203
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> ⨯ C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE stackTrace=
> 
> ```
>                          Error: C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> 
>                              at ChildProcess.<anonymous> (C:\Local Disk\Web_Designing_Projects\Practice(Updated)\euro_lights\client\node_modules\builder-util\src\util.ts:243:14)
> 
>                              at Object.onceWrapper (events.js:421:26)
> 
>                              at ChildProcess.emit (events.js:314:20)
> 
>                              at maybeClose (internal/child_process.js:1051:16)
> 
>                              at Socket.<anonymous> (internal/child_process.js:442:11)
> 
>                              at Socket.emit (events.js:314:20)
> 
>                              at Pipe.<anonymous> (net.js:673:12)
> ```
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! test@0.1.0 electron-pack: `electron-builder build --win -c.extraMetadata.main=build/electron.js --publish never`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the test@0.1.0 electron-pack script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\hp\AppData\Roaming\npm-cache_logs\2020-10-19T05_25_01_242Z-debug.log

I have solved this issue by
1. Dont create seperate folder "nsis-resources" in cache directory
2. Extracted "nsis-resources-3.4.1.7z" folder should be placed inside "nsis" folder inside cache directory
     C:\Users\xxx\AppData\Local\electron-builder\cache
     winCodeSign\winCodeSing-2.6.0
     nsis\nsis-3.0.4.1
     nsis\nsis-resources-3.4.0

**Comment by shayded-exe** [comment]
@develar It would be very useful if this information could be included in the documentation. I had to spend hours searching to deal with this.

There also doesn't seem to be any easy way to get the latest release of each of the binaries without manually going through the github releases and downloading each one. It would be nice if there was a page that linked to the latest release of each package.

**Comment by thisang** [comment]
I've got the same problem.

> ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-4.0.1-mac/wine-4.0.1-mac.7z": dial tcp 20.205.243.166:443: connect: operation timed out

so I downloaded this file and unzipped to `/Libary/Caches/electron-builder/wine/wine-4.0.1-mac`, when I running it again, it shows:

> ⨯ cannot execute  cause=exit status 1
                    errorOut=wine: /Users/xxx/Library/Caches/electron-builder/wine/wine-4.0.1-mac/wine-home is not owned by you

I changed the permissions on that directory to everyone can read and write，but it does'nt work。

what should I do？

**Comment by DanLowo** [comment]
For those having this issue on Windows. It turns out the Windows firewall blocks requests to objects.github for some reason.

You can resolve this by turning off the firewall either public or private (depending on your network setup)

**Comment by ZaidP101** [comment]
Hi, I downloaded nsis-resources-3.4.1.7z from the official release:
https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z

According to the expected structure, it should contain:
nsis-resources-3.4.1.7z
├── Plugins/
├── Stubs/
├── !Defines.nsh
└── UAC.nsh

But the archive I downloaded only includes:
Plugins/

There is no Stubs/ folder and the .nsh files are also missing.

Is this an issue with the uploaded archive, or has the structure changed for version 3.4.1?
Thanks!
