### ISSUE TITLE
Interfacing with Rust using node-ffi

### ISSUE THREAD

**Issue by EthanBogart** [electron-userland/electron-builder#1861]
* **Version**: 19.16.2

* **Target**: Any (mostly Mac)

Hello, this is more of a question than an issue. I have some compiled Rust files (.dylib) that I would like to use with node-ffi. I have tried adding the path to `files`, but that doesn't seem to work. I also see there are options for external files and resources but I don't quite understand how to use them. What is the best way to package these files into the app, if at all possible?

**Comment by develar** [comment]
Please use extraFiles or extraResources option (see wiki Options).
