### ISSUE TITLE
Support absolute paths to updater resources

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#1862]
* **Version**: 
```
"electron": "1.7.4",
"electron-builder": "19.13.0",
"electron-updater": "2.4.4",
```

* **Target**: Mac and Windows

In a previous version of the electron-updater, the `latest-mac.json` file contained a fully qualified path to download the next application version, for example:

```
{
  "version": "0.1.12",
  "releaseDate": "2017-07-25T17:28:28.808Z",
  "url": "https://desktop-release.notion-static.com/Notion-0.1.12-mac.zip"
}
```

However the new `latest-mac.yml` and the old windows `latest.yml` do not provide a full url:

```
version: 0.1.12
releaseDate: '2017-07-25T17:28:28.820Z'
githubArtifactName: Notion-0.1.12-mac.zip
path: Notion-0.1.12-mac.zip
sha512: >-
  RlrpWxGYKbPKvs/ja8/J1ZoRJ3T1Xt0G0Ey9S3kh6/rDb1vgG2HbSSHRm9SJ7zIkW96IZB/kl5flxxPr7W/74g==
```

This is problematic for me because we moved S3 buckets and our new one sits behind cloudflare. The old mac applications were able to update, but the newer mac apps and all the windows apps were not able to make the transition over to the new bucket.

My point is, it would be really nice if we use fully qualified urls :)

**Comment by ccorcos** [comment]
Actually, I suppose I can just upload a new app to the old bucket which points to the new bucket...

**Comment by hengkx** [comment]
I hope too

**Comment by develar** [comment]
Duplicates #1678 (actually, fixed for @ccorcos )

**Comment by develar** [comment]
Please note — file is generated with relative URL, but you can change `path` to absolute URL if need.

**Comment by hengkx** [comment]
@develar Thanks

**Comment by liliakai** [comment]
Can we also have an option to generate absolute urls in latest.yml? It would be nice to avoid editing yml files between building and publishing.

**Comment by develar** [comment]
@liliakai For what? Why your new version is not hosted on the same server where old version?
