### ISSUE TITLE
GH_TOKEN in Docker

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1867]
In my `.bashrc` I add
```
export GH_TOKEN=...
```
But inside the docker container this variable is not present. I have to export it manually every time. Is there a way to automatically import a variable from the environment into a container?

**Comment by develar** [comment]
Pass `--env-file docker-env.list` where `docker-env.list` file like https://github.com/electron-userland/electron-builder/blob/master/test/docker-env.list
