### ISSUE TITLE
windows build in wine re-downloads electron image everytime

### ISSUE THREAD

**Issue by rophy** [electron-userland/electron-builder#1868]
* **Version**: 18.3.0

* **Target**:  Windows

I have been using a linux node to build windows image following [this guide](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build).

Problem: it seems everytime the electron image (53MB) is re-downloaded. Is it possible to configure the env to prevent re-downloading electron images?

**Comment by develar** [comment]
Do you use docker?

**Comment by rophy** [comment]
Yes, using the wine container to do win build in a linux node with following command:

```
docker run --rm -i -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine /bin/bash -c "npm install && npm prune && npm run dist"
```

**Comment by cawa-93** [comment]
A similar situation: Every time the docker is restarted, electron image are downloaded again. I'm working on Linux

**Comment by rophy** [comment]
Managed to find fix:  somehow, electron cache directory changed from `~/.electron` to `~/.cache/electron`, so the docker command should be changed from:

```
docker run ... -v ~/.electron:/root/.electron electronuserland/electron-builder:wine ...
```

to:

```
docker run ... -v ~/.cache:/root/.cache electronuserland/electron-builder:wine ...
```
