### ISSUE TITLE
Question about the behavior of auto-update

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1869]
If I call `autoUpdater.checkForUpdates()` the `autoUpdater` will check for the update and automatically download it. But, what if I do not call `autoUpdater.quitAndInstall()` on emit `update-downloaded`? Will the update be installed after the user closes the application himself?

**Comment by develar** [comment]
Yes. Silently installed on quit. It is recommended behavior. Should be s strong reason to do anything else.

**Comment by Symbolk** [comment]
> Yes. Silently installed on quit. It is recommended behavior. Should be s strong reason to do anything else.

I got the log:
```
09:52:58.566 > Auto install update on quit
09:52:58.567 > Install: isSilent: true, isForceRunAfter: false
```
But I wonder how to set the isSilent to false? I did not call `autoUpdater.quitAndInstall()`
