### ISSUE TITLE
Avast Flagging my nsis build for win-32 electron app as threat and after sometime it reports that as clean.

### ISSUE THREAD

**Issue by umairpro1** [electron-userland/electron-builder#1870]
Electron Builder Version 19.16.0
this is my config file ....
{
    "appId": "*************",
    "asar": true,
    "electronVersion": "1.7.3",
    "files": [
      "view/**/*",
      "archive/**/*",
      "config/**/*",
      "engine/**/*",
      "localImg/**/*",
      "node_modules/**/*",
      "backgroundLogs/**/*",
      "exportModules/**/*",
      "scripts/**/*",
      "sign/**/*",
      "tools/**/*",
      "package.json"
    ],
    "compression" : "maximum",
    "asarUnpack":[
      "**/backgroundLogs/*",
      "**/node_modules/node-notifier/**/*"
    ],
    "forceCodeSigning" : true,
    "publish": [{
        "provider": "generic",
        "url": "http://*********************",
        "channel": "beta"
    }],
    "win": {
      "target": "nsis"
    },
    "nsis": {
      "useZip":true,
      "createDesktopShortcut":true
    }
  }

The Avast flagging make my autoUpdater fail. Please Help.

**Comment by develar** [comment]
File issue to Avast.

Is your app signed?

**Comment by umairpro1** [comment]
yes the app is signed but still gets flagged as threat says its publisher unknown but my app is signed and i used the forcecodesigning to check. so, its signed.

**Comment by danielfebrero** [comment]
Hey, same problem here.
App is signed, developer is recognised by Windows but considered as untrusted, Avast scan freeze .exe for scanning during each update / install

**Comment by umairpro1** [comment]
@develar Each and every time i have to upload my build to ftp before releasing to avoid this problem. And please help any other way around for this?

**Comment by develar** [comment]
Please ask Avast support about it. It is the only way to fix. Even Microsoft fixed bug in the MS Defender for us, so, I am sure, that Avast will fix it by request.

**Comment by danielfebrero** [comment]
@develar are you using s3 or a custom ftp ? In my case I am using s3 and cannot sort it out. There is also windows saying that the app is not safe, and I have to click on "show more informations" to execute it. Note that I am not a regular Windows user and I have no idea if it is a normal behaviour or not. The app is signed.
I will contact Avast support, as we are releasing a public beta by the end of the week.
Feedback is welcome (private beta: http://avantpremiere.addaps.com)

**Comment by danielfebrero** [comment]
I contacted Avast support, I will let you know once I get a answer

**Comment by develar** [comment]
FYI about S3 — https://github.com/electron-userland/electron-builder/issues/1185

**Comment by develar** [comment]
Just to be clear — we use not modified NSIS version 3.0.1 (proven solution and used by numerous companies, including Google and others). So, only Avast can fix it. If Avast will ask us to to do some tweaks — we are open for discussion and required changes will be implemented.

**Comment by danielfebrero** [comment]
Ok understood, thank you very much for your work

**Comment by umairpro1** [comment]
@develar Thank you so much for your support and I will contact avast regarding this issue and will keep you posted.

@danielfebrero  I am using custom ftp

**Comment by danielfebrero** [comment]
@develar I contacted avast support and get the following answer:

Hello,

Thank you for contacting Avast.

The provided file doesn't seem to be detected by Avast. Could you please send us a screenshot of the detection message you're getting? http://take-a-screenshot.org/

Prokop
The Avast Support Team

I will follow and let you know

**Comment by danielfebrero** [comment]
@develar I contacted avast support and get the following answer:

Hello,

_Thank you for contacting Avast.

The provided file doesn't seem to be detected by Avast. Could you please send us a screenshot of the detection message you're getting? http://take-a-screenshot.org/

Prokop
The Avast Support Team_

I will follow and let you know

**Comment by develar** [comment]
Feel free to reopen on Avast answer.
