### ISSUE TITLE
Copy files without duplicating directory hierarchy in app folder

### ISSUE THREAD

**Issue by chris-kostiw** [electron-userland/electron-builder#1873]
* **Version**: 19.6.3
* **Target**: OS X, Windows

Is there any way to configure electron-builder to copy the files from a project sub-directory into the app folder without also copying the sub-directory hierarchy itself? My project builds all web resources into a folder: <project>/target/webroot. I'd like to copy everything from "target/webroot" directly into the Resources/app folder, e.g.:

    <project>
        target
            webroot
                bundle.js
                index.html

should result in the following structure in the electron package:

    Product.app
        Contents
            Resources
                app
                    bundle.js
                    index.html

I can see how file glob patterns are used to choose the source files to copy, but is there a way to control the destination via the electron-builder configuration options?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#Config-files Use to/from form.

Example: https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/electron-builder.yml

**Comment by chris-kostiw** [comment]
Thanks. I had tried using the to/from/filter form but electron-builder threw an error complaining that my config was invalid. I've opened another issue about that.
