### ISSUE TITLE
Config files to-from-filter results in error

### ISSUE THREAD

**Issue by chris-kostiw** [electron-userland/electron-builder#1874]
* **Version**: 19.6.3
* **Target**: OS X

I am trying to use the "files" from/to/filter configuration option to control the files that get copied to my app, using a JSON configuration file. 

    "files": [
    {
        "from": "target/webroot",
        "to": "static",
        "filter": ["**/*"]
    }

This results in a build time error:

    Error: Config is invalid:
    {
    "files[0]": "Should be string",
    "files": [
        "Should be null,string",
        "Invalid option object"
    ]
    }

This is the configuration I am trying to get working.

    {
        "appId": "com.example",
        "productName": "My Product",
        "asar": false,
        "forceCodeSigning": false,
        "electronCompile": false,
        "directories": {
            "output": "distributables/installers"
        },
        "files": [
        {
            "from": "target/webroot",
            "to": "static",
            "filter": ["**/*"]
        }
        ],
        "mac": {
        "target": ["zip"],
        "icon": "src/assets/productlogo.icns",
        "category": "public.app-category.business"
        },
        "dmg": {
        "icon": "src/assets/myproduct.icns",
        "background": "src/assets/product.png",
        "contents": [
            {
            "x": 448,
            "y": 344,
            "type": "link",
            "path": "/Applications"
            },
            {
            "x": 192,
            "y": 344,
            "type": "file"
            }
        ]
        }
    }

Have I misunderstood how to configure files?

**Comment by develar** [comment]
Please use latest version. 19.6.3 is old.

**Comment by chris-kostiw** [comment]
My apologies. I thought all of my electron dependencies were up to date.
