### ISSUE TITLE
Packaging up Create-react-app and electron error

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#1878]
I am packaging up my electron app `electron-builder"` after I build the Create-react-app `react-scripts build`.

The error I receive when I try to run my packaged app is:

```
Not allowed to load local resource: 
file:///Users/profile/app/dist/mac/App.app/Contents/Resources/app.asar/build/index.html
```

Am I missing a step, to package the react app with electron?

the main.js is one level deeper in from the build folder,

Here is the url in my main.js 
```
const startUrl = process.env.ELECTRON_START_URL || url.format({
        pathname: path.join(__dirname, '/../build/index.html'),
        protocol: 'file:',
        slashes: true
  });
```

**Comment by hengkx** [comment]
``` javascript
import path from 'path';
import { format } from 'url';
window.loadURL(urlFormat({
    protocol: 'file',
    hash: '',
    pathname: path.join(__dirname, '/../build/index.html')
  }));
```

**Comment by AhadCove** [comment]
Sorry the code was being cut out, this is what it is already, receiving the error with this:
```
const startUrl = process.env.ELECTRON_START_URL || url.format({
        pathname: path.join(__dirname, '/build/index.html'),
        protocol: 'file:',
        slashes: true
  });
```

**Comment by develar** [comment]
Please consider to use short form like `file://${__dirname}/../build/index.html`

Have  you read https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3? What electron-builder version do you use?

**Comment by AhadCove** [comment]
I am using `electron-builder: 19.16.0`
I am building it and trying with `file://${__dirname}/../build/index.html` right now

**Comment by AhadCove** [comment]
Just updated to 19.18.0
That article helped, thanks. 
It's loading up my CRA App now, so that's a big step. Thank you again

**Comment by ryan-ds** [comment]
Still not working. I'm getting a blank screen
