### ISSUE TITLE
Squirrel Windows is not using productName for nupkg

### ISSUE THREAD

**Issue by lazlojuly** [electron-userland/electron-builder#1879]
* **Version**: 19.18.0

* **Target**: win squirrel 

I am trying to build for Windows with `squirrel` configuration and I am using `productName` in package.json. 

For a mac build, `productName` is picked up correctly for both artifacts (dmg and zip).

For win `name` is being used. This causes an error in `electron-builder-squirrel-windows`.

I cannot use `name` for product name as my app is also a scoped npm package.

package.json example:
```
"scripts": {
  build:mac: build --mac,
  build:win: build --win,
},
"version":"0.0.0",
"name": "@myscope/my-package-name",
"productName": "My Desktop App",
"build": {
    "appId": ".....",
    "win": {
      "target": "squirrel",
      "icon": null
    },
...
```

From looking at the source of `squirrelPack.ts` it looks like it supports `productName` for `Setup.exe` file but it ignores it for `nupkg`... Is this intentional? 

Error:
Unhandled rejection Error: ENOENT: no such file or directory, open '...repos/myapp/build/win/@myscope/my-package-name-0.0.0-full.nupkg'
    at Error (native)
From previous event:
    at /...myapp/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:107:9

**Comment by lazlojuly** [comment]
Update, it does not work with scoped package name for building linux either. Only works for mac builds.

**Comment by develar** [comment]
Consider to use default nsis target.

**Comment by lazlojuly** [comment]
I can't, I need to use Squirrel :(

**Comment by develar** [comment]
Workaround: set `name` in the `squirrelWindows` to your value.

**Comment by lazlojuly** [comment]
@develar thanks very much for the prompt response! Much appreciated!

The suggested workaround works, as in the error is no longer occuring.

However, now I am getting a different error from `NuGet.ZipPackage`:

```
Unhandled exception: System.InvalidOperationException: Package does not contain a manifest.
  at NuGet.ZipPackage.EnsureManifest () [0x00044] in ......
```

Have you seen this error message before and maybe a suggestion what might be causing this?

I am looking at the source code for [nuget/ZipPackage]( https://github.com/grendello/nuget/blob/master/src/Core/Packages/ZipPackage.cs) and can see two places for manifest validation... at this point I do not have the understanding of what either of those mean...
