### ISSUE TITLE
Which platforms and targets support automatic updates?

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1880]
Is auto-update supported for Windows Portable? Linux AppImage?

**Comment by develar** [comment]
#1138

**Comment by develar** [comment]
> Windows Portable?

No, by design.

**Comment by cawa-93** [comment]
What about Linux? Are there any targets supported?

**Comment by develar** [comment]
@cawa-93 #1138 :)

> Are there any targets supported?

What do you mean?

**Comment by cawa-93** [comment]
I mean will auto-update work on the Linux appimage, Linux deb and others?

**Comment by develar** [comment]
Yes, as soon as someone will donate or I will have time.

**Comment by cawa-93** [comment]
I did not find in the wiki a clear formulation of which os/target/arch support auto-update and which are not.
