### ISSUE TITLE
Improve default certificate recognized for app signing

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1883]
Hi Develar !

I've tried to build my electron application for Windows and macOS on my mac. I've a Startcom cert (for Windows and an Apple developer cert for mac). I've changed nothing in my package.json to customise app signing (I've let the default settings).

But I saw that my macOS application was signed with the Startcom cert.. I think this will very useful to sign the mac application with the Apple certificate by default (if many are found) !

I know that I can customise the package.json to do what I want, but I think this should be the default behaviours..

Thanks ;)

**Comment by develar** [comment]
Sorry for late response. We do use non-Apple certs only if we cannot find Apple cert. Do you mean that in your case app was signed using non-Apple cert even if there are Apple cert?

**Comment by popod** [comment]
Yes, exactly. I've an Apple cert and a non-Apple cert in Keychain and with default electron-builder configs, the mac application generated is signed with the non-Apple cert..

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder:*` and attach log of the terminal output.

**Comment by develar** [comment]
Feel free to send me direct message on slack if you want privacy.

**Comment by popod** [comment]
Sorry @develar but I cannot reproduce my problem.. I tried now and this seems to works as wanted.

I think that I had "unwanted" environment variables defined in the session !
