### ISSUE TITLE
NSIS windows app - How to sign the app ?

### ISSUE THREAD

**Issue by poojas2288** [electron-userland/electron-builder#1886]
* **Version**: 
19.5.1

* **Target**: 
NSIS

I am creating a windows app using NSIS targtet. I use following command : 
build --ia32

It creates an installer.exe. I need to sign the app as well as the installer.
I can sign the installer using signtool. But How can I install the app ?
When I install the app using the installer created, the app properties show that it is not signed.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by jthrilly** [comment]
Sorry, I am having the exact same issue, and that documentation does not help. 

It says it you have an EV certificate you need to add an additional parameter (`win.certificateSubjectName`) in the builder config, but I am _not_ using an EV certificate so this does not apply.

I have my USB token plugged in and unlocked, but the build process does not attempt to sign the exe before packaging it for the installer. What do I need to do?

**Comment by develar** [comment]
if you don't have p12/pfx file, but only USB token — please set `certificateSubjectName`.

**Comment by poojas2288** [comment]
So it asks for certificate password, and I do not have password. 
I have been provided a .PFX certificate file only, through which we can manually sign the installer using signtool : 
signUserFiles.exe -signer signtool.exe -cert certificate.pfx -file myinstaller.exe

So is there a way to do that  for the application as well ?

**Comment by develar** [comment]
If pfx file doesn't have password — set password to empty string.

**Comment by poojas2288** [comment]
I tried that, it says password not correct. The PFX itself contains the password embedded within itself and it works well when I manually sign the file using signtool.

Is there a way that I can somewhere include the signtool command in some script file so that  it signs the application also that is created during the  building process, because the build command directly creates the installer.

**Comment by develar** [comment]
PFX file canot contain password — it is or protected, or not. If protected — you must set password. If not protected — empty password must be specified. It is tested and works for me. And strongly recommend to protected pfx using password.

**Comment by poojas2288** [comment]
The PFX is provided by client's side and is protected, and the details are not exposed to us, which is the reason for other windows app we use signtool to manulally sign the apps.

**Comment by develar** [comment]
I don't understand. signtool also requires password if you use protected pfx.

**Comment by poojas2288** [comment]
So our client has provided a tool, which is a wrapper built on signtool, which we use for manually signing windows app, and the password has not been provided.

And in electron builder, since the build command directly creates the installer,  so I can sign the installer manually but not the actual application. 

So what I need is  : 

1. Modify some build scripts
2. First I get the unpacked folder created that contains the application.exe
3. I manually sign this app
4. Then I build the installer

Is it possible?

**Comment by develar** [comment]
> So our client has provided a tool, which is a wrapper built on signtool,

So, your issue is completely different. You just want to specify custom path to signtool. So, just set env  `SIGNTOOL_PATH` to path to such tool.

**Comment by poojas2288** [comment]
I am trying to set the env SIGNTOOL_PATH : 

env SIGNTOOL_PATH=pathToMyTool&&build --ia32

It shows unknown command

**Comment by develar** [comment]
@poojas2288 On windows you have to use another syntax `set SIGNTOOL_PATH=pathToMyTool` Please google it.

**Comment by aquaMi123** [comment]
I am also facing similar issue. I even tried setting signtool_path but it didn't sign my app. Is there any change required in package.json as well ?

**Comment by develar** [comment]
@aquaMi123 Please do not mix issues and do not hide important information like "client has provided a tool, which is a wrapper built on signtool". @aquaMi123 if in your case no need to use custom tool, please file new issue.

**Comment by poojas2288** [comment]
Hi @develar , I have set the signtool path as well, but it is still not signing my application. Do I need to make any other change in some configuration as well?

Is there a way that first I get the unpacked folder, then I'll sign the app,and then I build the installer over that. This will solve my problem.

**Comment by develar** [comment]
> Is there a way that first I get the unpacked folder, then I'll sign the app

No, because under the hood a lot of files can be signed (e.g. uninstaller).

> not signing my application

Did you set `CSC_LINK` env (or `certificateFile` option in the `win`)? Please provide debug log — set env `DEBUG=electron-builder`

**Comment by poojas2288** [comment]
Yes, I set CSC_LINK.

Following are the logs -

electron-builder 19.5.1
  electron-builder Effective config: {
  electron-builder   "appId": "mishareapp.mitel",
  electron-builder   "mac": {
  electron-builder     "category": "mishareapp"
  electron-builder   },
  electron-builder   "win": {
  electron-builder     "icon": "group.ico"
  electron-builder   },
  electron-builder   "nsis": {
  electron-builder     "oneClick": true,
  electron-builder     "perMachine": true,
  electron-builder     "installerIcon": "group.ico"
  electron-builder   }
  electron-builder } +0ms
No native production dependencies
Packaging for win32 ia32 using electron 1.7.3 to dist\win-ia32-unpacked
  electron-builder Found existing nsis C:\Users\pooja_sr\AppData\Local\electron-
builder\cache\nsis\nsis-3.0.1.13 +2s
  electron-builder Found existing nsis-resources C:\Users\pooja_sr\AppData\Local
\electron-builder\cache\nsis-resources\nsis-resources-3.0.0 +16ms
  electron-builder Spawning C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\e
lectron-builder\node_modules\7zip-bin\node_modules\7zip-bin-win\x64\7za.exe x -b
d C:\Users\pooja_sr\AppData\Local\electron\Cache\electron-v1.7.3-win32-ia32.zip
-oD:\projects\native_app\local\dist\win-ia32-unpacked +405ms

7-Zip (a) 17.00 beta (x64) : Copyright (c) 1999-2017 Igor Pavlov : 2017-04-29

Scanning the drive for archives:
1 file, 44456108 bytes (43 MiB)

Extracting archive: C:\Users\pooja_sr\AppData\Local\electron\Cache\electron-v1.7
.3-win32-ia32.zip
--
Path = C:\Users\pooja_sr\AppData\Local\electron\Cache\electron-v1.7.3-win32-ia32
.zip
Type = zip
Physical Size = 44456108

Everything is Ok

Files: 74
Size:       107213332
Compressed: 44456108
  electron-builder C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-b
uilder\node_modules\7zip-bin\node_modules\7zip-bin-win\x64\7za.exe (6472) exited
 with code 0 +1s
  electron-builder Found existing winCodeSign C:\Users\pooja_sr\AppData\Local\el
ectron-builder\cache\winCodeSign\winCodeSign-1.8.0 +125ms
  electron-builder Executing C:\Users\pooja_sr\AppData\Local\electron-builder\ca
che\winCodeSign\winCodeSign-1.8.0\rcedit.exe D:\projects\native_app\local\dist\w
in-ia32-unpacked\MiShareApp.exe --set-version-string FileDescription MiShareApp
--set-version-string ProductName MiShareApp --set-version-string InternalName Mi
ShareApp --set-version-string LegalCopyright Copyright c 2017 Mitel Networks Cor
poration --set-version-string OriginalFilename  --set-file-version 8.0.1 --set-p
roduct-version 8.0.1.0 --set-version-string CompanyName Mitel Networks Corporati
on --set-icon D:\projects\native_app\local\group.ico +16ms
  electron-builder Dev or extraneous dependencies in the D:\projects\native_app\
local:  +124ms
CSC_KEY_PASSWORD is not defined, empty password will be used
Signing MiShareApp.exe (certificate file: "D:\projects\native_app\Authenticode\m
itelAuthenticode.pfx")
  electron-builder Executing D:\projects\native_app\Authenticode\signUserFiles.e
xe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f D:\projects\nat
ive_app\Authenticode\mitelAuthenticode.pfx /d MiShareApp /du http://www.mitel.co
m/ D:\projects\native_app\local\dist\win-ia32-unpacked\MiShareApp.exe +531ms
Error: Exit code: 1. Command failed: D:\projects\native_app\Authenticode\signUse
rFiles.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f D:\proj
ects\native_app\Authenticode\mitelAuthenticode.pfx /d MiShareApp /du http://www.
mitel.com/ D:\projects\native_app\local\dist\win-ia32-unpacked\MiShareApp.exe


INFORMATION: D:\projects\native_app\Authenticode\signUserFiles.exe starting. Thu
 08/03/2017 11:52:06

INFORMATION: Verifying input options...

ERROR: Either the search directory (-dir) or the executable file (-file) option
is required to continue...



    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\node_
modules\electron-builder-util\src\util.ts:77:16
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at exec (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder
\node_modules\electron-builder-util\src\util.ts:55:3)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
indowsCodeSign.ts:142:2
From previous event:
    at spawnSign (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-bu
ilder\out\windowsCodeSign.js:113:22)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
indowsCodeSign.ts:62:5
    at next (native)
From previous event:
    at sign (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder
\out\windowsCodeSign.js:46:21)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
inPackager.ts:228:15
    at next (native)
From previous event:
    at WinPackager.doSign (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\el
ectron-builder\out\winPackager.js:315:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
inPackager.ts:209:16
From previous event:
    at WinPackager.sign (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\elec
tron-builder\out\winPackager.js:296:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
inPackager.ts:268:16
From previous event:
    at WinPackager.signAndEditResources (C:\Users\pooja_sr\AppData\Roaming\npm\n
ode_modules\electron-builder\out\winPackager.js:339:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\w
inPackager.ts:274:16
From previous event:
    at WinPackager.postInitApp (C:\Users\pooja_sr\AppData\Roaming\npm\node_modul
es\electron-builder\out\winPackager.js:348:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\p
latformPackager.ts:194:148
From previous event:
    at WinPackager.doPack (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\el
ectron-builder\out\platformPackager.js:258:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\p
latformPackager.ts:97:16
    at next (native)
From previous event:
    at WinPackager.pack (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\elec
tron-builder\out\platformPackager.js:159:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\p
ackager.ts:243:24
From previous event:
    at Packager.doBuild (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\elec
tron-builder\out\packager.js:366:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\p
ackager.ts:163:52
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electr
on-builder\out\packager.js:267:11)
    at C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builder\src\b
uilder.ts:235:40
    at next (native)
From previous event:
    at build (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electron-builde
r\out\builder.js:69:21)
    at Object.handler (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\electr
on-builder\src\cli\cli.ts:42:4)
    at Object.self.runCommand (C:\Users\pooja_sr\AppData\Roaming\npm\node_module
s\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\Users\pooja_sr\AppData\Roaming\npm\node_
modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.Yargs.Object.defineProperty.get [as argv] (C:\Users\pooja_sr\AppDa
ta\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)

    at Object.<anonymous> (C:\Users\pooja_sr\AppData\Roaming\npm\node_modules\el
ectron-builder\src\cli\cli.ts:37:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

D:\projects\native_app\local>

**Comment by poojas2288** [comment]
Can I somehow append my signing command in windowsCodeSign.js so as to sign the application ; 

signUserFiles.exe -signer signtool.exe -cert mitelAuthenticode.pfx -file myApp.exe

**Comment by poojas2288** [comment]
I did some changes in windowsCodeSign.js inorder to make it compatible with my existing tool/command and it worked.

**Comment by develar** [comment]
Please send PR. No need to polish it, I will do required style/other changes if need.
