### ISSUE TITLE
portable app with startup parameters

### ISSUE THREAD

**Issue by christophew** [electron-userland/electron-builder#1887]
* 19.18.1

* win

I just upgraded electron & electron builder to the latest version to test the 'portable' build option.

It seems that the portable build ignores the startup parameters of the electron app.
Is this an issue, or am I doing something wrong?

This is my config:
"build": {
    "appId": "my.app.id",
    "win": {
      "target": [
        "portable"
      ]
    },
    "electronCompile": false,
    "directories": {
      "output": "dist/installer"
    }
  }

**Comment by develar** [comment]
Duplicates #1410
