### ISSUE TITLE
ExtraFiles use the highest root directory?

### ISSUE THREAD

**Issue by ErraticFox** [electron-userland/electron-builder#1889]
Hello, I'm packaging my app with `ffmpeg.exe` and `ffprobe.exe`. I'm using `ExtraFiles` on the two and it puts them in `app/resources` whereas `ExtraResources` puts them in `app/resources/resources`. Though my app only uses `ffmpeg` and `ffprobe` if they're *only* in the **root** directory so in this case that'd be the folder `app`. How can I do this?

**Comment by develar** [comment]
Yes, `relative to the project directory`. You can use `from`/`to` options.
