### ISSUE TITLE
Asar packages everything even itself?

### ISSUE THREAD

**Issue by fab1an** [electron-userland/electron-builder#1890]
* **Version**: latest

* **Target**: mac OSX

I tried using electron-builder. By default it seems to package everything into ASAR, even non-electron files.

The mainpage states: 

> Please note that everything is packaged into an asar archive by default.

Whereas [this page](https://github.com/electron-userland/electron-builder/wiki/Two-package.json-Structure) states:

> Since version 8 electron-builder rebuilds only production dependencies, so, you are not forced to use two package.json structure.

What confuses me as well is that it will even package it's own generated `.app` into the asar-archive, created a nested archive that gets bigger and bigger…

**Comment by develar** [comment]
> it will even package it's own generated .app into the asar-archive

It seems you have configured custom output directory?

**Comment by fab1an** [comment]
Yes: `output: "."`.

**Comment by develar** [comment]
So, what do you expect ;)? How electron-builder can exclude such file magically? Do not use `.` or configure `files` property.

**Comment by fab1an** [comment]
:) okay.

I assumed electron-builder would work like webpack: start from the index-file and include only what's necessary.

**Comment by develar** [comment]
> I assumed electron-builder would work like webpack: start from the index-file and include only what's necessary.

To use node module in the webpack, you often have to specify it as external, because not all commons module can be bundled.

The same story here — we cannot assume that you explicitly require all files, maybe you use it as dll / external file (to load using fs API).

**Comment by develar** [comment]
If you want to use webpack — use http://github.com/electron-userland/electron-webpack and avoid manual configuration :)
