### ISSUE TITLE
Pulling files from artifactory during install?

### ISSUE THREAD

**Issue by mm739521** [electron-userland/electron-builder#1891]
19.13.0

Windows

To preface, I'm fairly new to electron and electron-builder.

I'm creating a desktop application on linux  and using electron-builder to create installers for Windows.  The application uses a separate .exe file and dll files that are from a separate project.  

Currently I'm having to copy and paste these files in the project after installation every time I want to do a new build.

What steps (or option) would I need to take in order to have electron-builder automate this for me?

**Comment by develar** [comment]
So, you want to be able to specify files from http://, not only from local file system, right?

**Comment by mm739521** [comment]
Correct, is there a way to do that already?

**Comment by mm739521** [comment]
@develar Is this something that electron-builder supports currently? and if so, what option would I need to implement this?

**Comment by develar** [comment]
For now, you can simply commit such files to project (consider to use git-lfs).

**Comment by develar** [comment]
So, do you need this feature or not?

**Comment by mm739521** [comment]
Not anymore, no.  Instead I created a script to download the files I needed to the project and used the extraFiles option to package them.

**Comment by mm739521** [comment]
Specifying http urls in the extraFiles parameter?/
