### ISSUE TITLE
Builds doesn't work

### ISSUE THREAD

**Issue by diakov2100** [electron-userland/electron-builder#1893]
Hi, I am trying to make a build of app https://github.com/nontrip/YaStreamDesktop
If I make a "clean" build without precompiling there is an exception unexpected token import.
If I make a build with compiling modules there is an exception that something is not precompiled or something is missing.
So I really need your help as I tried everything I found and I am quite close to give up, but we spent a lot of effort on this project(
pls...

**Comment by Mooooooon** [comment]
HI, My steps.
1. `git clone https://github.com/nontrip/YaStreamDesktop.git`
2. `yarn`
3. `yarn add electron-builder --dev`
4. add package.json scripts `"win": "electron-builder --win --x64 --dir"`
5. add package.json build
```
  "build": {
    "appId": "your.id"
    "files": [
      "!log.txt"
    ],
    "extraFiles ": [
      "log.txt"
    ]
  }
```
6.edit main.js
```
import { app, BrowserWindow } from 'electron';
//to
const {app, BrowserWindow} = require('electron')
```
7.`yarn win`
8. run dist\win-unpacked\electron-es6-react.exe

He seems to be working properly.


![run](http://i.imgur.com/RYSVofv.png)

**Comment by develar** [comment]
Будем считать, все ок сейчас, если что, переоткрывайте ;)
