### ISSUE TITLE
Signed my app, still marked as unsafe by Chrome and Windows Defender

### ISSUE THREAD

**Issue by Lorempn2** [electron-userland/electron-builder#1894]
Hello, i signed my Windows app by using a standard certificate (not an extended). But if I download the .exe, Chrome is still marking the exe as unsafe. If I then execute the exe, Windows Defender popups with another warning. However, I see the company name as the publisher, so I think the signing went ok, is this just normal behaviour for this kind of certificate?

**Comment by Mooooooon** [comment]
Self-signed certificate? It's normal.

**Comment by Lorempn2** [comment]
No not self-signed. It's a Comodo cert.

**Comment by develar** [comment]
Duplicates #1185
