### ISSUE TITLE
Question - Build NSIS for both 32 and 64 bits

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1897]
With electron-builder v19.19.1, when I build for windows with defaults params `build -w`, I get a nsis installer who only works for 64 bits. Is it correct ?

In fact, I expected that by default, the nsis contain both 32 and 64 bits versions. What do you think to do this behaviour by default ?

And second, is there any way to define the build target arch for Windows only in the package.json ? Because, now I use `build -wml --x64 --ia32` and it build 32 bits versions for linux too and I do not want that..

Thanks

**Comment by cawa-93** [comment]
```json
"win": {
  "target": [
    {
      "target": "nsis",
      "arch": [
        "x64",
        "ia32"
      ]
    }
  ]
},
"linux": {
  "target": [
    {
      "target": "AppImage",
      "arch": [
        "x64"
      ]
    }
  ]
}
```

**Comment by popod** [comment]
@cawa-93 Thank you! I've missed the "arch" options.. But the linux part is not necessary. By default only arch x64 is build.

And what about setting by default arch x64 and ia32 when target is "nsis" for Windows build ?

**Comment by cawa-93** [comment]
What do you have in mind?
You can see https://github.com/electron-userland/electron-builder/issues/1314

**Comment by develar** [comment]
> when target is "nsis" for Windows build ?

Currently, `platformSpecific` is respected, but not `targetSpecific`. Feel free to file feature request.

**Comment by popod** [comment]
@develar I'm not sur that you have understound what I'm trying to say ^^

> With electron-builder v19.19.1, when I build for windows with defaults params `build -w`, I get a nsis installer who only works on 64 bits systems. Is it correct ?
>
> In fact, I expected that by default, the nsis contain both 32 and 64 bits versions. What do you think to set this by default ?

So, what do you think to change the current default build settings. And automatically build and include ia32 and x64 in nsis installer by default ?

**Comment by develar** [comment]
I don't think that it is a good default. And ia32 must die.

**Comment by popod** [comment]
Yes, I think like you, but many users always run Windows with ia32.. :( So this will be more interesting for developper to support this by default.

But this is only a "question/proposal".. This is not a problem for me to add this 2 more lines in package.json to config what I want.

**Comment by cawa-93** [comment]
@popod I think you are wrong. Regardless of the choice of OS or target, a single approach to the default parameters should be maintained. It is not a good idea to build NSIS somehow differently

**Comment by popod** [comment]
@cawa-93 Okey, yes I understand. Thanks for reply ;)

**Comment by GammaGames** [comment]
(In case anyone else gets here from google)

It gives me the error `configuration.win has an unknown property 'arch'` with the above settings. I was able to build by using this in package.json instead:

```json
"scripts": {
  "dist": "electron-builder --ia32 --x64 -w"
}
```

**Comment by hypnoboutique** [comment]
```configuration.win has an unknown property 'arch'```

Same. Shame.

**Comment by alirezavalizade** [comment]
How about the 'squirrel'? @cawa-93

**Comment by fabiospampinato** [comment]
It doesn't looks like @cawa-93's [configuration](https://github.com/electron-userland/electron-builder/issues/1897#issuecomment-320454346) doesn't work anymore in v21.2.0, at least when using the programmatic API, what are we supposed to use now?

**Comment by Mhmetengineer** [comment]
Can u solve problem ? @fabiospampinato

**Comment by fabiospampinato** [comment]
@Mhmetengineer you have to call the build method like so:

```ts
builder.build ({
  ia32: true,
  x64: true,
  win: {
    target: [
      'dir',
      'nsis',
      'zip'
    ]
  }
})
```

**Comment by umamichi** [comment]
↑
`configuration has an unknown property 'x64'.`

**Comment by flaushi** [comment]
if both architectures are built in, how can the user choose then? I'm on mac, trying to understand.
For me this does work to get both arch's:

``` 
"win": {
      "target": {
        "target": "nsis",
        "arch": [
          "ia32",
          "x64"
        ]
      },
```

**Comment by flaushi** [comment]
> I don't think that it is a good default. And ia32 must die.

Yes, but still today there exist problems with 64 bit that do not exist with 32bit.
A customer updated windows server version from 2012 to 2019, together with Citrix version I guess.
Now the x64 version does not render anymore (white screen opens, html not rendered), but with only --ia32, everything is fine.

So, yes, it should die, but the software should survive :)

**Comment by m4heshd** [comment]
> (In case anyone else gets here from google)
> 
> It gives me the error `configuration.win has an unknown property 'arch'` with the above settings.

That's because It belongs inside the `config` property of `rawConfig`. You must've added it in the root of `rawConfig`.

> ↑ Error has occurred
> `configuration has an unknown property 'x64'.`

I think you must've done the opposite of above. Try it inside the the `config`.

**Comment by 0100Light** [comment]
For `configuration.win has an unknown property 'arch'` error, in my case (using `electron-builder.yml`, you have to type 2 "target"s, which looks like this:

```yml
win:
  target:
    target: nsis
    arch:
      - x64
      - ia32
  executableName: progress-toolbox
nsis:
  artifactName: ${name}-${version}-${arch}.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
```
