### ISSUE TITLE
Build Snaps on MacOS without Docker

### ISSUE THREAD

**Issue by nikhiljha** [electron-userland/electron-builder#1898]
* **Version**: 19.19.1

* **Target**: Linux / Snap

Currently on MacOS, snaps are built inside a Docker image. Recently `snapcraft` became available in MacOS with brew (`brew install snapcraft`). This would probably speed up builds considerably as a new docker image doesn't need to be created every single time a build is run.

**Comment by develar** [comment]
Cool news. I will check.

**Comment by develar** [comment]
Doesn't work for me. "snapcraft exited with code 1".

**Comment by nikhiljha** [comment]
Looks like only `snapcraft cleanbuild` is working, which depends on `lxc`/`lxd`. To my understanding that is basically docker, so looks like we're not getting native build tools just yet :(
