### ISSUE TITLE
Downloading wine-2.0.1-mac-10.12 blocked

### ISSUE THREAD

**Issue by simlw** [electron-userland/electron-builder#1901]
* **Electron-builder Version**: 19.19.1

* **electron-updater Version**: 1.16.0

* **Target**: windows 

I want to packaging for mac and windows packager. Packaging for darwin x64 is successful. But it is blocked at **“Downloading win-2.0.1-mac-10.12“”** when packaging for **win32 x64**.  

 I don't know why and is it necessary downloading wine every time?  Actually I have install wine-2.7 in my Mac.     

The following is my package.json file.
```
// package.json
...
 "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder -mw"
  },
  "build": {
    "appId": "com.electron.tool",
    "publish": [
      {
        "provider": "generic",
        "url": "http://localhost:3000"
      }
    ],
    "mac": {
      "category": "electron.tool",
      "target": [
        "dmg",
        "zip"
      ]
    }
  },
  "devDependencies": {
    "electron": "^1.4.15",
    "electron-builder": "^19.19.1"
  },
  "dependencies": {
    "electron-download-tf": "^4.3.1",
    "electron-log": "^1.3.0",
    "electron-updater": "^1.16.0"
  }
```
Does anyone know what's wrong? Give me some advices, please.

**Comment by develar** [comment]
> I don't know why and is it necessary downloading wine every time?

It is cashed after first request.

>  I have install wine-2.7 in my Mac.

No need.

Probably blocked by proxy. As workaround, you can set env `USE_SYSTEM_WINE=true`. Or investigate why blocked.

**Comment by simlw** [comment]
@develar Thank you for you reply. I have tried many times and success finally.  Probably because of the network. And I have choose your advice and set `USE_SYSTEM_WINE=true` in my env and it is worked.
