### ISSUE TITLE
Passing cmd options to electrons

### ISSUE THREAD

**Issue by SwiftsNamesake** [electron-userland/electron-builder#1905]
version of electron-builder are you using? -->

* **Version**: 

* **Target**: 

Maybe this has been asked before, but how do you specify command line arguments that should be passed to `electron` programmatically? I know about `app.commandLine.appendSwitch` but that doesn't work for certain parameters (eg. `--enable-mixed-sandbox`).

**Comment by develar** [comment]
Please use https://github.com/electron/electron/blob/master/docs/api/app.md#appenablemixedsandbox-experimental-macos-windows
