### ISSUE TITLE
deb icon for Linux Software Center

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1907]
Hi,

I do not find any doc about the `build.deb.icon` config in the package.json ?
- Why not get the default icon like for the `build.linux.icon` ?
- What should be the icon format and name (should the name contain the size like for `build.linux.icon`) ?

Thanks for answer. And I think the doc should be improved if no default param is used.. ;)

**Comment by develar** [comment]
It is just ability to specify custom icon for deb. common -> linux -> deb configuration chain.

**Comment by popod** [comment]
Thanks @develar for answer. So if nothing is specified for the deb icon, the linux icon is used ? But how to define the icon for the deb installer ? The app icon is ok, but not the installer icon..

![img_4925](https://user-images.githubusercontent.com/3807312/29038008-44038050-7ba6-11e7-8a95-0b114b9edbbb.JPG)

**Comment by develar** [comment]
It is not deb, but Ubuntu "feature". Or it is not Ubuntu?

**Comment by popod** [comment]
Yes, the OS is Ubuntu, but the installer package is a .deb.

**Comment by faboweb** [comment]
I have the same issue. Installed app has the desired icon but the `.deb` file hasn't and in the software center there is also no icon visible.

**Comment by popod** [comment]
I think that this is still an issue now..

**Comment by develar** [comment]
Consider to use snap. 

I don't have time to investigate this case and deb it is deprecated format to distribute apps.

For example, upcoming support for ARM (build on any OS), will be implemented only for snap.

**Comment by popod** [comment]
@develar Okey, thank you for information !
