### ISSUE TITLE
target appx does not create latest.yml with with generic publish setting

### ISSUE THREAD

**Issue by RIAEvangelist** [electron-userland/electron-builder#1908]
* **Version**: 19.19.1

* **electron-updater version**: 2.8.2

* **Target**: appx

I am testing an app build for windows... `nsis` target creates latest.yml `appx` target does not. The only difference is the target. everything works correctly and the appx checks for updates. It correctly downloads an update if available and rejects it if sha is bad. (manually updated version and path in a hand made latest.yml just to make sure it would try to download)

```json
"publish": [
            {
                "provider": "generic",
                "url": "http://localhost:7374/"
            }
        ]
```

**Comment by RIAEvangelist** [comment]
[issue also on slack if you would prefer to discuss there](https://atomio.slack.com/archives/C044E597S/p1502142396456747)

**Comment by develar** [comment]
`appx` it is format for Windows Store. So, auto-update is not suitable for it.

**Comment by RIAEvangelist** [comment]
@develar there are uses where appx will not be installed through the store like internal apps in locations without external network access or regulated environments. 

The code certificate is added to the trusted group, and the app is then installed like any other app accept it is a unified app which sandboxes and gives access to varius unified apis on windows.

The important thing here is this means the sandboxed app is installable on win 10 and 10S.

If a user specifies "generic" the latest.yml should be left. Everything else is already working as is, the app does check the server for the latest.yml and if it specifies a newer version it will download and install if the checksum matches.

**Comment by develar** [comment]
Do you mean that only if app packed into appx, it has access to "unified apis on windows"? Do you mean that NSIS is not suitable for you?

**Comment by RIAEvangelist** [comment]
That is correct, also in windows 10S only appx files will work. 

[Appx are now installable via double click.](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#sideload-your-app-package)

**Comment by RIAEvangelist** [comment]
So the above is in the official docs, and here is a post about it on their blog from 2016  [https://blogs.msdn.microsoft.com/appinstaller/2016/05/27/app-installer/](https://blogs.msdn.microsoft.com/appinstaller/2016/05/27/app-installer/)

**Comment by RIAEvangelist** [comment]
the nsis and appx flows, feels and security are very different. appx is a lot like appimage or snap for linux while nsis is like deb for ubuntu.

**Comment by RIAEvangelist** [comment]
issue should probably remain open as it seems like allowing the latest.yml to be created when the user specifies "generic" should be the default behavior as per the spec and docs.

**Comment by develar** [comment]
So, do you expect that app updater will download new appx package and install it somehow?

**Comment by RIAEvangelist** [comment]
It is already trying. App updater is working as expected. I just need the latest.yml 

I wrote one by hand to test, but I did not know the right checksum so after checking, electron-updater did download the newer version but it failed to install because manually I did not use the right checksums.

**Comment by RIAEvangelist** [comment]
I do not think any changes other than putting the latest.yml in the dir are needed.

**Comment by develar** [comment]
I am not sure that it will correctly (we need to remove old app, or maybe it is automatically upgraded and handled?). Ok. Got your point.

PS. I like AppX, but MS decided to not support it on old OS versions and that’s why we cannot use it as a default target. Another reason is that no way (currently) to pack and sign appx on non-Windows OS.

**Comment by develar** [comment]
Developer note: we don't need sha512 checksum for AppX, because appx file contains signed block map.

**Comment by RIAEvangelist** [comment]
windows sucks like that... but `maybe` it's getting better, they have bash now atleast.

they seem to be forcing the appx migration over the next few releases, likely for security reasons.

I'll be happy to test any feature branch as I have everything setup already. I can provide notes if I need to specify anything like setFeedURL etc.

**Comment by develar** [comment]
Keep in mind — in current/planned implementation, you will be not able to produce both nsis and appx, because `latest.yml` contains reference or to nsis, or to appx (as github artifacts doesn't support folders).

**Comment by RIAEvangelist** [comment]
I think for the time being that is acceptable because the electron-builder options gives several ways around this. It  would fall under a further feature request to allow both to be published as generic in the same repo in the same folders at the same time on the same windows machine for the same update server. It seems a bit edge case even for me.

In the short term the user can simply build both on a ci or locally in different repo clones or specify an out dir for each for this extra edge case.

I [forked and updated the publishmanager](https://github.com/RIAEvangelist/electron-builder/commit/8802dd730ed40b7329cf497f759b4c331f9568c2) to allow `latest.yml` for `appx` and everything works perfect until the elevate.exe is required. The `target/appx` needs to add the elevate.exe to the package resources dir like the nsis does.

assistance with that part would be helpful

![screenshot from 2017-08-08 13-21-34](https://user-images.githubusercontent.com/369041/29093268-18d341e8-7c3e-11e7-92b0-57c27f0ed1e7.png)

**Comment by RIAEvangelist** [comment]
Once we get this working I can create a repo with an example app for demo and docs as well as add the docs to the wiki.

**Comment by RIAEvangelist** [comment]
I forced the elevate.exe to be included just to test and now the old app shuts down properly, but this is as far as I could get for now. It des not run the new appx, have to take a look at `electron-updater` to see what commands it runs

**Comment by RIAEvangelist** [comment]
this could be from the setting in `electron-updater`? perhaps the user has to click the install option in the appx installer

**Comment by develar** [comment]
`appx` file it is just zip file. You cannot execute it directly. Some tool should be used to install appx file.

**Comment by RIAEvangelist** [comment]
appx files are executed directly they do not use another tool to install or run.
