### ISSUE TITLE
使用electron-builder配合electron-updater实现自动更新

### ISSUE THREAD

**Issue by AragornZJF** [electron-userland/electron-builder#1909]
使用electron-builder配合electron-updater实现自动更新
node -v 6.11.2
npm -v 3.10.10
electron -v 1.4.13 
windows system  arch=ia32
-----------------------------------------------------------------------
main.js 
// 检测更新，在你想要检查更新的时候执行，renderer事件触发后的操作自行编写
function updateHandle(){
    let message={
      error:'检查更新出错',
      checking:'正在检查更新……',
      updateAva:'检测到新版本，正在下载……',
      updateNotAva:'现在使用的就是最新版本，不用更新',
    };
    const os = require('os');
    autoUpdater.setFeedURL('http://192.168.0.208:7081/outApp/');
    autoUpdater.on('error', function(error){
      sendUpdateMessage(message.error)
    });
    autoUpdater.on('checking-for-update', function() {
      sendUpdateMessage(message.checking)
    });
    autoUpdater.on('update-available', function(info) {
        sendUpdateMessage(message.updateAva)
    });
    autoUpdater.on('update-not-available', function(info) {
        sendUpdateMessage(message.updateNotAva)
    });
    
    // 更新下载进度事件
    autoUpdater.on('download-progress', function(progressObj) {
        mainWindow.webContents.send('downloadProgress', progressObj)
    })
    autoUpdater.on('update-downloaded', 
 function (event, releaseNotes, releaseName, releaseDate, updateUrl, quitAndUpdate) {
        ipcMain.on('isUpdateNow', (e, arg) => {
            //some code here to handle event
            autoUpdater.quitAndInstall();
        })
        mainWindow.webContents.send('isUpdateNow')
        app.quit();
    });
    
    //执行自动更新检查
    autoUpdater.checkForUpdates();
}
********>>************run results....

Checking for update
update for version 1.6.11 is not available (latest version : 0.0.2, downgrade is disallowed.)

**Comment by yeliex** [comment]
use English thanks

**Comment by develar** [comment]
Issue report is not clear for me.

> update for version 1.6.11 is not available (latest version : 0.0.2, downgrade is disallowed.)

So, your server returns this data. For what do you use setFeedURL?

**Comment by AragornZJF** [comment]
ok use electron-builder and electron-updater 
The message tips is 
`` update for version 1.6.11 is not available (latest version : 0.0.2, downgrade is  #disallowed.)

> How can I resolve this question ??

**Comment by develar** [comment]
Your current app version is "1.6.11" (do you run unpacked app or packed?). Latest (returned by your server) is 0.0.2. So, update is disallowed.

**Comment by AragornZJF** [comment]
thanks  my local app version 0.0.1 why show electron version "Your current app version is "1.6.11"  ??
![image](https://user-images.githubusercontent.com/23381574/29061638-4954ffd8-7c51-11e7-853b-4fc7d8dda79d.png)

**Comment by develar** [comment]
Please specify electron-updater and electron-builder version. Do you run packed exe or as `electron app`?

**Comment by dtboy1995** [comment]
不允许降级操作。

笔者发现在检查更新的时候，electron 会把 electron 的版本当作当前应用版本（package.json）。

当前应用是基于 electron@1.7.5，应用版本为1.0.0，而服务器上应用版本低于1.7.5，进而提示不允许降级操作。

这个bug是由于 electron 配置启动地址错误造成的。

把 /.electron-vue/dev-runner.js
中 startElectron
路径 path.join(__dirname, '../dist/electron/main.js')
改成 '.'

**Comment by zhangshichun** [comment]
> startElectron

you a right!so 66666
