### ISSUE TITLE
How to reduce app file size

### ISSUE THREAD

**Issue by mharrisn** [electron-userland/electron-builder#1911]
* **Version**: 19.16.0

electron-updater@2.8.2

* **Target**: Mac, Windows

Currently, my app is structured with the one package approach but after building, the app is bundling all of the dependencies in the package.json, which is not necessary. I assume the two package approach is supposed to resolve this, but when I implement that, none of my app files are copied over. Here is the build object from my parent project:

```
"build": {
        "appId": "xxx.xxx.xxx",
        "productName": "XXX",
        "electronVersion": "1.6.11",
        "directories": {
            "app": "./electron",
            "buildResources": "resources/electron"
        },
        "publish": {
            "provider": "generic",
            "url": "http://127.0.0.1:8080/"
        },
        "asar": false,
        "files": [
            "./electron/**/*",
            "./www/**/*"
        ],
        "dmg": {
            "background": "resources/electron/osx/dmg-background.png",
            "icon": "resources/electron/osx/dmg-icon.icns"
        },
        "mac": {
            "category": "public.app-category.business",
            "icon": "resources/electron/osx/icon.icns"
        },
        "nsis": {
            "createDesktopShortcut": true,
            "installerHeader": "win/installerHeader.bmp",
            "installerIcon": "win/installerIcon.ico",
            "installerSidebar": "win/installerSidebar.bmp"
        },
        "win": {
            "icon": "resources/electron/win/icon.ico"
        }
    },
```

electron/package.json:
```
{
    "name": "xxx-xxx",
    "description": "A node package project",
    "version": "0.0.1",
    "author": "Author Name",
    "homepage": "http://www.company.com/",
    "private": true,
    "license": "UNLICENSED",
    "scripts": {},
    "dependencies": {
        "electron-log": "^2.2.7",
        "electron-updater": "^2.8.2"
    },
    "devDependencies": {
        "npm-run-all": "^4.0.2"
    },
    "main": "./main.js"
}
```

When I try to build, I get an error:
`Error: Application entry file "main.js"  does not exist. Seems like a wrong configuration.`

When I open the unpacked app, I can see that the /app folder in the project only includes a `package.json` file & the `node_modules` folder with the two dependancies installed. My assumption was that including `./electron/**/*` in the `build.files` config would copy the contents of that folder to the bundle but that's not the case.  I've read through the documentation and I'm not sure what I'm doing wrong. I'd like to only install: the contents of my electron folder, my parent project's www folder, and the electron specific node dependencies into the app bundle.

**Comment by develar** [comment]
Let's solve step by step.

1. Please use 1 package.json. What problems do you have?

**Comment by mharrisn** [comment]
Using 1 package.json:

Here is a rough outline of my project structure:

* root
   * electron/
      * main.js
   * node_modules/
   * package.json (Dependencies for Angular 4 & electron)
   * src/
      * source files for angular 4 webapp (.scss, .ts, .html files)
   * www/  (Compiled output of src Project)

When my application is packed, the bundle file size is larger than it needs to be. There is a node_modules folder created in the bundle of my app. It appears to include all of the dependencies in my project's root package.json file. Those dependancies are used to build my webapp project and are compiled into the www folder.  All I need for the app bundle is the content of the www folder and any libs needed for electron to function. 

My problem is that the node_modules folder is being added to the bundle and I haven't discovered a way to prevent it from being added to the app bundle.

**Comment by develar** [comment]
Is it possible to provide me your project? Or list all files in the `www`? Are there `node_modules` in the `www`? Or do you mean that all deps are bundled into one file in the `www`?

**Comment by ednew2018** [comment]
Try to not include node_modules to your app.asar like the following.
"build": { ... "files": [ "!node_modules" ], ... }
