### ISSUE TITLE
How to include a js file/module that is not in node_modules ?

### ISSUE THREAD

**Issue by williamAlhant** [electron-userland/electron-builder#1912]
* **Version**: ^19.0.0

* **Target**: MacOS

My directory structure is the following
```
ProjectDirectory
  main.js
  package.json
OtherProject
  module.js
```
I am requiring `module.js` in `main.js`like this : `require('../OtherProject/module')`

The packaged application throws an error because it cannot find this file. How can I include this file ? Can I use the `extraFiles`option ?

**Comment by develar** [comment]
You should not require files outside of project root directory. Please or move `OtherProject` to project, or publish it as npm module.

**Comment by develar** [comment]
Please note — using form/to fields, you can construct any structure as you want.

**Comment by develar** [comment]
And on macos you can use symlinks to link OtherProject to your project (so, require will work not only the packed mode).
