### ISSUE TITLE
Set publisherName in app-update.yml even if no FileCodeSigningInfo for Windows

### ISSUE THREAD

**Issue by joneian** [electron-userland/electron-builder#1913]
* **electron-builder Version**: 19.16.0

* **electron-updater Version**: 2.8.0

* **Target**: Building for Windows on Mac

I'm working in an environment where I'm not allowed access to our certificate files. We have a service I send my executable to and it comes back signed. So, to get a signed Windows electron app, I'm currently doing:
1. `node_modules/.bin/build -w`
2. Send `dist/win-unpacked/MyApp.exe` to get signed and replace the same file
3. `node_modules/.bin/build -w --prepackaged dist/win-unpacked/`
4. Send `dist/MyInstaller.exe` to get signed.

That all works fine, except upon auto update because I've signed the app myself app-update.yml doesn't contain publisherName, so the certificate of the download isn't verified.

This happens because winPackager.ts doesn't set publisherName if there's no FileCodeSigningInfo [here](https://github.com/electron-userland/electron-builder/blob/165e11c6f7d6ea4be589a39823caa50c71b78928/packages/electron-builder/src/winPackager.ts#L85). 
Could we remove that check so publisherName is still set in this scenario? I'm happy to submit a pull request if this makes sense.

**Comment by develar** [comment]
> That all works fine

Uninstaller is not signed in this case.

> Could we remove that check so publisherName is still set in this scenario?

No, because we need cert info to compute it.

Workaround: set `win.publisherName` name explicitly. https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-publisherName

**Comment by joneian** [comment]
Thanks for looking at this @develar .
> Uninstaller is not signed in this case.

Good point, thanks.

> Workaround: set win.publisherName name explicitly.

This doesn't work for the reasons I mentioned: If I set that but the exe isn't signed then the code I mentioned returns null and does not set the publisherName in the app-update.yml. That's what I'm trying to fix here.

Thanks again!
