### ISSUE TITLE
The NSIS installer is not installing anything.

### ISSUE THREAD

**Issue by Miroware8** [electron-userland/electron-builder#1914]
* **Version**: 19.19.1

* **Target**: Windows

When running my one-click NSIS installer after building the setup EXE file, it adds an entry to the programs/features list, but it does not install the actual program anywhere and also does not run the program after installing. Attempting to change the `nsis` properties variously in my `package.json` file did not do anything differently. This was not a problem before I tried to certify the program through the Windows App Cert Kit.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal build output.

Is it possible to provide your exe to inspect?

**Comment by Miroware8** [comment]
How do I set that environmental variable?
Here's my EXE file.
https://miroware.io/temp/COMPLETE-BULLSHIT-ia32.exe
It might actually just be an issue with my own computer, not with the EXE file. Tell me whether that's the case.

**Comment by Miroware8** [comment]
OH, WAIT. It, for whatever reason, works perfectly now. I have no idea what the issue was before, but it no longer exists.

**Comment by develar** [comment]
Restart *** *** Windows, right?

**Comment by Miroware8** [comment]
Uh... The EXE file isn't working again. I also just had someone else download the EXE file to see if it worked, and they verified that it didn't. I have no idea what's up. Here's the EXE file, and I don't know how to set an environmental variable.
https://miroware.io/completebullshit/COMPLETE-BULLSHIT-ia32.exe

**Comment by Miroware8** [comment]
The problem is persisting on that one program but not on new programs I try to create with Electron. Could you please reopen the issue and help me out?

**Comment by Miroware8** [comment]
![image](https://user-images.githubusercontent.com/14056899/29237962-48b80c16-7ef7-11e7-84d8-586fcacb513a.png)

**Comment by Miroware8** [comment]
Oh. A few people *are* inconsistently having the problem. I'm not sure what the correlation is, but some people have the same problem I do and some people don't.

**Comment by develar** [comment]
@Miroware8 Please use prerelase 19.22.0 I have made some changes.

**Comment by develar** [comment]
And please provide your config.

**Comment by Miroware8** [comment]
I have now updated both of those download links, and it works now!
...but, just in case, if by "config" you mean "`package.json` file", here it is.
```json
{
  "name": "COMPLETE-BULLSHIT",
  "version": "4.1.3",
  "description": "This is COMPLETE BULLSHIT.",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "author": {
    "name": "Grant Gryczan",
    "email": "grantgryczan@gmail.com"
  },
  "license": "ISC",
  "build": {
    "appId": "com.miroware.COMPLETE-BULLSHIT",
    "productName": "COMPLETE BULLSHIT",
    "mac": {
      "category": "public.app-category.utilities",
      "icon": "./favicon.icns"
    },
    "win": {
      "target": "nsis",
      "icon": "./favicon.ico"
    },
    "nsis": {
      "createDesktopShortcut": false,
      "uninstallDisplayName": "COMPLETE BULLSHIT"
    },
    "linux": {
      "synopsis": "This is COMPLETE BULLSHIT.",
      "description": "This is COMPLETE BULLSHIT.",
      "category": "Utility"
    }
  },
  "devDependencies": {
    "electron": "^1.7.5",
    "electron-builder": "^19.21.0"
  }
}
```

**Comment by develar** [comment]
@MariaDima Thanks a lot for your fixes. First happy user :)

**Comment by develar** [comment]
Problem was in the `createDesktopShortcut` option. Now it is handled correctly.

**Comment by Miroware8** [comment]
Alright, nice.

**Comment by BkSouX** [comment]
Hi, I have the same issue with the 20.14.7 version :cry: ( don't know yet if its fine with the last version )

**Comment by meilechwieder** [comment]
> Hi, I have the same issue with the 20.14.7 version 😢 ( don't know yet if its fine with the last version )

Still same issue, installer not opening
