### ISSUE TITLE
Exec in nsis include

### ISSUE THREAD

**Issue by SimoneTosato** [electron-userland/electron-builder#1919]
* **Version**: 19.19.1
* **Target**:  Windows 10

I'm trying to use an NSIS script ( `include`, not `script` ) to install some drivers for an usb device, i'm using `zadic.exe` and it is works like a charm from command line. My installer script: 
```
 !macro preInit
   ; This macro is inserted at the beginning of the NSIS .OnInit callback
   NSISdl::download https://s3.eu-central-1.amazonaws.com/fermiumlabs-libwdi-builds/master/examples/zadic.exe $TEMP/zadic.exe
 !macroend

 !macro customInstall
    Exec 'elevate "$TEMP/zadic.exe" --vid 0xxxxx --pid 0xxxxx --create "XXXXXX" --noprompt'
 !macroend
```
preInit works perfectly and downloads the file, for the customInstall I've tried multiple execution methods, `Exec`, `!system` (since i've seen it in your example scripts) and `nsExec::Exec`. I've obtained some result only with `!system` but only launches the command while building and not when using the built installer.

**Comment by develar** [comment]
I missed this issue, is it solved?

**Comment by SimoneTosato** [comment]
yes

```
!macro customHeader
   RequestExecutionLevel admin
 !macroend

 !macro customInstall
   NSISdl::download https://s3.eu-central-1.amazonaws.com/fermiumlabs-libwdi-builds/master/examples/zadic.exe $TEMP\zadic.exe
   ExecWait '"$TEMP\zadic.exe" --vid xxxxxx --pid xxxxxx --create "XXXXXXX" --noprompt'
 !macroend
```


this worked like a charm
