### ISSUE TITLE
Deb license missing?

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#1921]
* **Version**: 
19.19.1

* **Target**: 
Linux (deb)

In ubuntu software center License is missing even though I have set it [here](https://github.com/zulip/zulip-electron/blob/master/package.json#L7) and [here](https://github.com/zulip/zulip-electron/blob/master/app/package.json#L6).

![image](https://user-images.githubusercontent.com/2263909/29140327-be31f664-7d67-11e7-827e-3c6e53085b22.png)

**Comment by JamesTiberiusKirk** [comment]
Same Problem here, it just defaults me to no license, and the first version I had entered in my project "0.0.1"

**Comment by tsuriga** [comment]
Same. I tried with both "SEE LICENSE IN LICENSE" type of license entry and with some random valid SPDX identifier ("AMPAS" I believe), in both cases the License field stayed as "Unknown".

**Comment by develar** [comment]
It is known not-yet-known-how-to-fix issue related to Ubuntu Software Center. Help wanted.

**Comment by dragonDScript** [comment]
I still need help. I have set the package json license field to mit yet it shows as proprietary software.
