### ISSUE TITLE
Code Signing: Multiple Choices

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#1924]
```Electron-bulder: 19.20.0```

I am trying to Sign my app just for developer, but it will not go through. I get a yellow warning message saying that 8 valid identities were found: (Half Iphone certs, half Mac certs).

I tried setting CSC_NAME in my Env, but it told me to erase the prefix, because it will find the cert automatically with the suffix, but I ended up in the same place. The yellow warning message saying 8 valid identities were found.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder:* ` and attach log of the terminal output.
