### ISSUE TITLE
Include python binaries in pkg

### ISSUE THREAD

**Issue by NPellet** [electron-userland/electron-builder#1925]
**Question !**

* **Version**:  19.19.1

* **Target**: mac

Hello !

I am calling python scripts from my nodejs environment. For now, Python is installed globally on the target computer. My question is: is there a way to add local python binaries (for example, during the building) so that I don't depend on the previous Python installation (and on the PATH env variable) ?

Not sure this question should be targeted to electron-builder, though...

Thanks in advance

**Comment by develar** [comment]
If you can avoid providing own Python — avoid it :)

Python 2.7.10 is preinstalled on macOS.

**Comment by NPellet** [comment]
Hmm ok. Avoiding it is, then...
(I said mac, but in fact, I also need to compile on Windows. I'll just tell people to preinstall Python in this case)

Thanks. This can be closed for me.

**Comment by develar** [comment]
To bundle some files, you can use `extraFiles` / `extraResources` options.
