### ISSUE TITLE
v19.20.0 does not read electron-builder.yml

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1927]
* **Version**: 19.20.0

* **Target**: win32 ia32 NSIS

The default config file `electron-builder.yml` is not being read. I tried changing a bunch of settings because my app was getting extremely huge. Turns out it didn't read the config file and just put all files into the asar package.

Version `19.19.1` works fine.

Edit:
To clarify why I think it is not reading the config file:

I tried to set `asar: false` and it didn't do anything.

**Comment by develar** [comment]
Thanks for using prerelease version. I will check.

**Comment by develar** [comment]
@HitomiTenshi Do you have `build` in the `package.json`?

**Comment by HitomiTenshi** [comment]
Sorry that I couldn't answer in time! No I don't have a `"build": ""` entry if that's what you mean.

I do have a script that calls `build --ia32` though.

**Comment by HitomiTenshi** [comment]
Just tested `19.20.1` and the issue is fixed. Thanks for your hard work!

**Comment by develar** [comment]
I have added unit test to avoid such regressions in the future :) Thanks for confirmation, probably `19.20.1` will be marked as release version.
