### ISSUE TITLE
How to specify different location of app directory in final macOS build?

### ISSUE THREAD

**Issue by martinezmj** [electron-userland/electron-builder#1933]
* **Version**: 19.19.1

* **Target**: macOS

```
{
  "name"    : "myapp",
  "description": "MyApp",
  "author": "Me",
  "version" : "2.0.0",
  "main"    : "main.js",
  "build": {
    "appId": "myapp",
    "asar": false,
    "electronVersion": "1.6.11",
    "directories": {
      "output": "build"
    },
    "mac": {
      "target": "zip",
      "identity":null,
      "icon": "myicon.icns"
    },
    "win": {
      "target": "zip",
      "icon": "myicon.ico"
    }
  }
}
```

Currently, when I build, `app` is located at `myapp.app/Contents/Resources/app/`.

I want it to be located outside of the application bundle.
`myapp.app`
`resources/app`

Essentially, I need it to mimic the location, relative to the executable, as the windows build.
`myapp.exe`
`resources/app`

Is there a way to achieve this?

**Comment by develar** [comment]
For what?

**Comment by martinezmj** [comment]
It would be convenient to have both windows and mac executables in the same directory, with application resources shared, not duplicated in different locations.

**Comment by develar** [comment]
> not duplicated in different locations.

For what? In any case win app will be started on win, mac on mac? And most of the resources are system-dependent.

**Comment by martinezmj** [comment]
My understanding is that app contains only my own code and resources, not Electron resources or anything system-dependent.   Say you don't know what OS the user is using and you want to give them a disk that contains both windows and mac builds.  If windows, they click myapp.exe.  If mac, they click myapp.app.  In this directory, you don't want to duplicate all your application resource in both resource/app and myapp.app/Contents/Resources/app/.   You just want one copy there.  Say it's an automated process and you want it to be as fast as possible, so you don't want to copy twice.

I was able to achieve this using symlinks in the mac build, but that turned out to be problematic in other ways.  So it sounds like there's no way to achieve this via electron-builder options?

**Comment by develar** [comment]
Size of windows DLLs: 40 MB.
Size of main windows executable: 80 MB

Size of macOS Frameworks: 125 MB.

I doubt that your app contains cross-platform resources that consumes more disk space.

> If windows, they click myapp.exe

It seems you want portable — use `portable` target to pack win app into one exe file (compressed using LZMA).
