### ISSUE TITLE
Cannot package "asar" as a runtime dependency

### ISSUE THREAD

**Issue by andycreeth** [electron-userland/electron-builder#1935]
* **Version**:  19.10.0

* **Target**: Windows x64

It seems like it is impossible to add the "asar" npm module as a packaged runtime dependency for my application.  Although Asar is primarily used by electron, it was released as a separate general purpose package on Github (https://github.com/electron/asar) and has applications beyond electron packagin.  My application was using asar essentially like a tarball for storing user data and assets that could be easily transferred between systems as a single file.  It seems like electron-builder always assumes that Asar is a development dependency and will never include it with the packaged app, even when the `package.json` lists it as a dependency.

I think the offending code is here: https://github.com/electron-userland/electron-builder/blob/af9842364749549b8f55a022536ef8d8eaf3d7c8/packages/electron-builder/src/util/packageDependencies.ts#L34

I recognize that this is a fairly niche use case, but it seems overly presumptuous to assume that Asar would only ever be used for packaging the electron app.

**Comment by develar** [comment]
Fixed in 19.21.0.
