### ISSUE TITLE
Code-Signing Certificate questions

### ISSUE THREAD

**Issue by ErraticFox** [electron-userland/electron-builder#1936]
I was wondering how exactly I'd go about Code Signing my application to remove stuff like SmartScreen on Windows 10. Currently, I see that the "EV Code Signing Certificate" would be the one to do this but with the other certificate it's mentioned it's "often cheaper" which implies I need to purchase one. As someone completely new to the code signing process where could I buy this and how would I go about signing my app with it?

**Comment by develar** [comment]
Duplicates #1185
