### ISSUE TITLE
Miss app-update.yum for installed app.

### ISSUE THREAD

**Issue by cmzz** [electron-userland/electron-builder#1938]
* **Version**: 
```
    electron: 1.7.4
    electron-builder: 19.16.2
    electron-builder-squirrel-windows: 19.16.0
```

* **Target**: windows 32  64

That's an installed release app.

```
Error: Error: ENOENT: no such file or directory, open 'C:\Users\zyxcba\AppData\Local\pigtk\app-0.1.6\resources\app-update.yml'
    at C:\Users\zyxcba\AppData\Local\pigtk\app-0.1.6\resources\app\node_modules\electron-updater\src\AppUpdater.ts:304:27
```

app-update.yml not created.  
Can anyone help.? thanks

**Comment by develar** [comment]
Squirrel.Windows is deprecated target. Please use NSIS.

> Simplified auto-update is supported on Windows if you use the default NSIS setup, but is not supported for Squirrel.Windows.
