### ISSUE TITLE
Can't specify an AppX icon

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1940]
* **Version**: 19.19.1

* **Target**: appx

The AppX target doesn't seem to be able to find the icon at `build/icon.ico`, or by a `win.icon` setting.

Is there a special way to set an AppX icon? See an example AppX build, where the icon is still the default Electron logo:

![no icon](https://user-images.githubusercontent.com/2192773/29244593-d11c8a2c-7f89-11e7-9fb6-1d306e48f34c.PNG)

**Comment by jviotti** [comment]
So looks like I can provide the following files in `build/appx`:

```
Square150x150Logo.png
Square44x44Logo.png
StoreLogo.png
Wide310x150Logo.png
```

I haven't seen this documented anywhere (I had to look at the code), so I might send a documentation PR soon.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/1897#issuecomment-320454346

**Comment by jviotti** [comment]
Maybe I'm missing something, but how is that thread related to AppX packages?

**Comment by develar** [comment]
@jviotti Sorry, link fixed, docs added — https://github.com/electron-userland/electron-builder/wiki/Icons#appx
