### ISSUE TITLE
How to pass flags when app starting (Linux)

### ISSUE THREAD

**Issue by Toinane** [electron-userland/electron-builder#1946]
Hello here! 
I have one question about electron-builder. (i use the latest release):
For linux, to start my app, I use this command "electron src/main.js --enable-transparent-visuals --disable-gpu" to have transparent windows. but when I build a .deb, .appImage or unpacked, I think the flag didn't work. How I can pass these flags when the app is starting?

Thank you! :)

```JSON
{
  "main": "src/main.js",
  "scripts": {
    "start": "electron src/main.js --enable-transparent-visuals --disable-gpu"
  }
}
```

**Comment by develar** [comment]
https://github.com/electron/electron/blob/master/docs/api/app.md

app.commandLine.appendSwitch

app.disableHardwareAcceleration

**Comment by Toinane** [comment]
Ah! Thank you so much! And sorry to have make this issue just for this

**Comment by gormonn** [comment]
@develar this is not working for `--ignore-gpu-blacklist`, for example. See issue: https://github.com/electron/electron/issues/15339
For example, in my case, this makes it impossible to use hardware acceleration to play Full HD video on certain configurations in Electron.
