### ISSUE TITLE
snap Exec path

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#1948]
* **Version**: 
19.8.0

* **Target**:
Linux -> Snap 

Hello. I'm using snaps to distribute my application for Linux.
I noticed that after **snap install my-app** there is no app's icon(shortcut) in the Launcher. 
Tested on Ubuntu 16.04 and 17.04; I tried to reboot my system. 
The desktop launcher that's created does not have a line defining the executable, which seems to be **/snap/bin/my-app**
The desktop launcher that seems to be the one exposed to the Unity Desktop is **/var/lib/snapd/desktop/applications/my-app_my-app.desktop**
 I have added the Exec line and this resolved the issue; The icon works fine in the launcher
Here's my edited launcher

[Desktop Entry] 
Name=MyApp
Comment=Desktop App
Terminal=false 
Type=Application 
Icon=/snap/my-app/7/meta/gui/icon.png 
Exec=/snap/bin/my-app

**Comment by sagorshkov** [comment]
Any ideas about this behavior? 
Perhaps I'm doing something wrong... But I can't find any options related to the exec paths or something like this in linux->snap config options((

**Comment by develar** [comment]
Ouch, `${packager.executableName}` evaluated to empty string and so, `!= null` failed. Fixed, will be published in 20 minutes.
