### ISSUE TITLE
Cannot find module 'electron-updater'

### ISSUE THREAD

**Issue by fabriciolelis** [electron-userland/electron-builder#1949]
* **Electron-builder: ^2.8.7**

* **Target: Windows** 
This error occurs after build the app in dev mode the app works.

**Comment by develar** [comment]
Please `npm ls --production`

**Comment by fabriciolelis** [comment]
+-- @angular/animations@4.3.4
| `-- tslib@1.7.1
+-- @angular/common@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/compiler@4.3.4
| `-- tslib@1.7.1 deduped
+-- UNMET PEER DEPENDENCY @angular/core@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/forms@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/http@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/platform-browser@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/platform-browser-dynamic@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/router@4.3.4
| `-- tslib@1.7.1 deduped
+-- @ngx-translate/core@7.2.0
+-- @ngx-translate/http-loader@0.1.0
+-- @types/socket.io-client@1.4.29
+-- bootstrap@3.3.7
+-- brace@0.10.0
| `-- w3c-blob@0.0.1
+-- code-point-at@1.1.0
+-- core-js@2.5.0
+-- debug@2.6.8
| `-- ms@2.0.0
+-- electron-updater@2.8.7
| +-- bluebird-lst@1.0.3
| | `-- bluebird@3.5.0 deduped
| +-- debug@3.0.0
| | `-- ms@2.0.0 deduped
| +-- electron-builder-http@19.21.0
| | +-- bluebird-lst@1.0.3 deduped
| | +-- debug@3.0.0
| | | `-- ms@2.0.0 deduped
| | `-- fs-extra-p@4.4.0 deduped
| +-- electron-is-dev@0.3.0
| +-- fs-extra-p@4.4.0
| | +-- bluebird-lst@1.0.3 deduped
| | `-- fs-extra@4.0.1
| |   +-- graceful-fs@4.1.11
| |   +-- jsonfile@3.0.1
| |   | `-- graceful-fs@4.1.11 deduped
| |   `-- universalify@0.1.1
| +-- js-yaml@3.9.1 deduped
| +-- lazy-val@1.0.2
| +-- lodash.isequal@4.5.0
| +-- semver@5.4.1
| +-- source-map-support@0.4.15
| | `-- source-map@0.5.6
| +-- uuid-1345@0.99.6
| | `-- macaddress@0.2.8
| `-- xelement@1.0.16
|   `-- sax@1.2.4
+-- ion-rangeslider@2.2.0
| `-- jquery@3.2.1 deduped
+-- jquery@3.2.1
+-- js-yaml@3.9.1
| +-- argparse@1.0.9
| | `-- sprintf-js@1.0.3
| `-- esprima@4.0.0
+-- lodash@4.17.4
+-- ng2-ion-range-slider@1.0.3
| +-- UNMET PEER DEPENDENCY @angular/core@4.3.4 deduped
| +-- @types/jquery@2.0.48
| `-- ion-rangeslider@2.2.0 deduped
+-- ng2-slideable-directive@1.0.13
| `-- ng2-styled-directive@1.0.5 deduped
+-- ng2-slider-component@1.0.9
| +-- ng2-slideable-directive@1.0.13 deduped
| `-- ng2-styled-directive@1.0.5 deduped
+-- ng2-styled-directive@1.0.5
+-- ngx-bootstrap@1.8.1
| `-- moment@2.18.1
+-- ngx-dropdown@0.0.22
+-- request@2.81.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.6.0
| +-- caseless@0.12.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.1
| +-- forever-agent@0.6.1
| +-- form-data@2.1.4
| | +-- asynckit@0.4.0
| | +-- combined-stream@1.0.5 deduped
| | `-- mime-types@2.1.16 deduped
| +-- har-validator@4.2.1
| | +-- ajv@4.11.8
| | | +-- co@4.6.0
| | | `-- json-stable-stringify@1.0.1
| | |   `-- jsonify@0.0.0
| | `-- har-schema@1.0.5
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | | `-- hoek@2.16.3 deduped
| | +-- cryptiles@2.0.5
| | | `-- boom@2.10.1 deduped
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| |   `-- hoek@2.16.3 deduped
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.4.1
| | | +-- assert-plus@1.0.0
| | | +-- extsprintf@1.3.0
| | | +-- json-schema@0.2.3
| | | `-- verror@1.10.0
| | |   +-- assert-plus@1.0.0
| | |   +-- core-util-is@1.0.2
| | |   `-- extsprintf@1.3.0 deduped
| | `-- sshpk@1.13.1
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- bcrypt-pbkdf@1.0.1
| |   | `-- tweetnacl@0.14.5 deduped
| |   +-- dashdash@1.14.1
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   | `-- jsbn@0.1.1 deduped
| |   +-- getpass@0.1.7
| |   | `-- assert-plus@1.0.0
| |   +-- jsbn@0.1.1
| |   `-- tweetnacl@0.14.5
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.16
| | `-- mime-db@1.29.0
| +-- oauth-sign@0.8.2
| +-- performance-now@0.2.0
| +-- qs@6.4.0
| +-- safe-buffer@5.1.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.2
| | `-- punycode@1.4.1
| +-- tunnel-agent@0.6.0
| | `-- safe-buffer@5.1.1 deduped
| `-- uuid@3.1.0
+-- request-promise@4.2.1
| +-- bluebird@3.5.0
| +-- request-promise-core@1.1.1
| | `-- lodash@4.17.4 deduped
| +-- stealthy-require@1.1.1
| `-- tough-cookie@2.3.2 deduped
+-- rxjs@5.4.3
| `-- symbol-observable@1.0.4
+-- save@2.3.1
| +-- async@2.5.0
| | `-- lodash@4.17.4 deduped
| +-- event-stream@3.3.4
| | +-- duplexer@0.1.1
| | +-- from@0.1.7
| | +-- map-stream@0.1.0
| | +-- pause-stream@0.0.11
| | | `-- through@2.3.8 deduped
| | +-- split@0.3.3
| | | `-- through@2.3.8 deduped
| | +-- stream-combiner@0.0.4
| | | `-- duplexer@0.1.1 deduped
| | `-- through@2.3.8
| +-- lodash.assign@4.2.0
| `-- mingo@1.3.3
+-- socket.io-client@2.0.3
| +-- backo2@1.0.2
| +-- base64-arraybuffer@0.1.5
| +-- component-bind@1.0.0
| +-- component-emitter@1.2.1
| +-- debug@2.6.8 deduped
| +-- engine.io-client@3.1.1
| | +-- component-emitter@1.2.1 deduped
| | +-- component-inherit@0.0.3
| | +-- debug@2.6.8 deduped
| | +-- engine.io-parser@2.1.1
| | | +-- after@0.8.2
| | | +-- arraybuffer.slice@0.0.6
| | | +-- base64-arraybuffer@0.1.5 deduped
| | | +-- blob@0.0.4
| | | `-- has-binary2@1.0.2 deduped
| | +-- has-cors@1.1.0 deduped
| | +-- indexof@0.0.1 deduped
| | +-- parsejson@0.0.3
| | | `-- better-assert@1.0.2 deduped
| | +-- parseqs@0.0.5 deduped
| | +-- parseuri@0.0.5 deduped
| | +-- ws@2.3.1
| | | +-- safe-buffer@5.0.1
| | | `-- ultron@1.1.0
| | +-- xmlhttprequest-ssl@1.5.3
| | `-- yeast@0.1.2
| +-- has-cors@1.1.0
| +-- indexof@0.0.1
| +-- object-component@0.0.3
| +-- parseqs@0.0.5
| | `-- better-assert@1.0.2
| |   `-- callsite@1.0.0
| +-- parseuri@0.0.5
| | `-- better-assert@1.0.2 deduped
| +-- socket.io-parser@3.1.2
| | +-- component-emitter@1.2.1 deduped
| | +-- debug@2.6.8 deduped
| | +-- has-binary2@1.0.2
| | | `-- isarray@2.0.1 deduped
| | `-- isarray@2.0.1
| `-- to-array@0.1.4
`-- zone.js@0.8.16

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder* ` and attach log of the terminal output.

**Comment by fabriciolelis** [comment]
This print helps?
![error](https://user-images.githubusercontent.com/8815495/29366474-80e19086-8270-11e7-8889-b34552ab4c64.jpg)

**Comment by develar** [comment]
I guess you use some boilerplate and forget to add electron-updater as production dependency. Or somehow else misconfigure electron-builder. Full debug log can help me to understand your project.

**Comment by fabriciolelis** [comment]
The log and package.json are in this link:
https://gist.github.com/fabriciolelis/68bdfc4f28c38bc2d164e19af2ac9141

**Comment by develar** [comment]
I cannot help you without project. Is it possible to provide?

**Comment by fabriciolelis** [comment]
Sorry, but I can't do that.

**Comment by develar** [comment]
I need only skeleton of project — not actual source files. I see that you provide some extra package file and have some build script to copy the whole app to a new dir. Maybe you need to add electron-update dep to some file, or ... I don't understand structure of your project and, so, cannot advice.

**Comment by develar** [comment]
Maybe you need just set your build dir as app directory.

**Comment by fabriciolelis** [comment]
This can help you?
![project-structure](https://user-images.githubusercontent.com/8815495/29416000-279d15b0-833b-11e7-817d-d5270a4a4e23.jpg)

**Comment by develar** [comment]
Ok, let's guessing :)

What `app_package.json` does? Maybe you need to add `electron-update` as dependency here?

**Comment by develar** [comment]
Ouch, I see that ` "app": "./dist",` So, is `dist/package.json` contains `electron-updater`?

**Comment by fabriciolelis** [comment]
No, `dist/package.json` does not contain  `electron-updater`

**Comment by develar** [comment]
@fabriciolelis Please answer to https://github.com/electron-userland/electron-builder/issues/1949#issuecomment-323083808 "What app_package.json does? Maybe you need to add electron-updater as dependency here?"

**Comment by fabriciolelis** [comment]
@develar Thanks for your help. I've solved the problem put the dependencies in app_package.json

**Comment by develar** [comment]
Cool. Your boilerplate is mysterious for me :)

**Comment by hyungseokno** [comment]
"devDependencies": {
    "electron": "^8.0.0",
    "electron-builder": "^22.3.2"
  },
  "dependencies": {
    "electron-log": "^4.0.6",
    "electron-updater": "^4.2.0"
  }

The processing method must be registered again after deletion.

a) yarn remove electron-updater
b) yarn add electron-updater
 
This should be added to the "dependencies" section as above.

**Comment by OldManMeta** [comment]
This is still happening - I've deleted node_modules, rebuilt, repackaged, the lot - and still getting this error.

updater is firmly in my dependecies (not dev) as well.

Thoughts?

**Comment by idsong** [comment]
i run into the same scenario, doing the same thing as you, deleting 'node_module', cleaning the cache, but it didn't work.  If you're using Windows, you can check the running programs, find you app and kill them all.
