### ISSUE TITLE
Remove temp fork dependencies 

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#195]
Documentation states that electron-packager and https://github.com/electronjs/windows-installer are used under the hood. The truth being that some electron-packager-tf and electron-winstaller-temp-fork are actually being used. 
@develar Do you plan on maintaining updates to the original projects?
If so the documentation should state the truth otherwise electron-builder should really depend on the originals.

**Comment by develar** [comment]
As it is finally published, we can use original project.

But @havenchyk tried pre-release version and reported that there is a critical error in the original windows-installer.

I will check it in a few days.

**Comment by havenchyk** [comment]
@demetris-manikas yep, in my case I have not correct handling of the path and get an exception. I'll create an issue against windows-installer after double check.

**Comment by havenchyk** [comment]
@develar tested with the electron-winstaller@2.0.5, probably we can use it instead of fork.

**Comment by develar** [comment]
Closed for now. We **do** PR to electron-packager (e.g. https://github.com/electron-userland/electron-packager/pull/318), windows-installers and other important and critical for us modules. But 

* we cannot wait sometimes when our changes will be landed.
* our changes sometimes are experimental (work for our users, but pointless to create PR if code will be or may be should be changed).
