### ISSUE TITLE
Error setting config value under build with --config.extraMetadata

### ISSUE THREAD

**Issue by jonbeller** [electron-userland/electron-builder#1954]
* **Version**: 19.22.1

* **Target**: Windows/Mac

I'd like to modify the bintray repo I publish to via the command line.

In my `package.json` I have under `build`
```    
"publish": {
      "provider": "bintray",
      "repo": "myapp-alpha",
      ...
}
```

When I run `build --config.extraMetadata.build.publish.repo=myapp-beta --publish always` I get the error `Error: --em.build is deprecated, please specify as -c"`. I get the error no matter if I use `--em` or `-c.extraMetadata`.

**Comment by develar** [comment]
`-c.publish.repo=my app-beta`

build key not required for c.
