### ISSUE TITLE
Set target to env variable

### ISSUE THREAD

**Issue by FrogTheFrog** [electron-userland/electron-builder#1955]
* **19.19.1**;

* **Target**:  `nsis`, `portable`, `deb`, `AppImage ` and `zip`.

Hello,

I'm building an app for the specified targets. `nsis` and `portable` works great, however I'm having some trouble with `zip` and other archives. I need to set 3 different user data directories for these configurations. For `nsis` I use default, `portable` uses `PORTABLE_EXECUTABLE_DIR` and `zip` would also use a executable directory. 

However, apart from `portable`, I have no idea which target the app was build with. I could use an API to set targets manually, however `electron-builder`'s `CLI` is enough for me and I believe it would be a nice addition for `electron-builder`.

**Comment by develar** [comment]
Not clear for me what feature you are asking for.

Do you mean that you need some runtime env for `zip` app?

BTW, for what do you need `zip` in addition to `portable`?

**Comment by FrogTheFrog** [comment]
I would like, for example, for `process.env.ELECTRON_BUILDER_TARGET` to be set to `zip`, `portable`, `nsis` or whatever an app is build with.

Portable is for Windows only. Let's say I want a portable app (given that all dependencies are installed) for linux. If the user downloaded `.deb` release, user data should be in `~/.config`, if user download `.zip`, user data should be near executable. For this to work I need `ELECTRON_BUILDER_TARGET`.

**Comment by develar** [comment]
@FrogTheFrog On Linux I recommend to use AppImage (it is default target). env `APPIMAGE` is available for you and you can use it to compute user data path near AppImage file.

**Comment by FrogTheFrog** [comment]
I'm already building AppImage (didn't think it would be necessary to mention, updated first post to match all targets), however there are some hardcore users who would like to have `zip` for both Windows and Linux.

You said, that `APPIMAGE` is available. Is this also the case for other targets?

**Comment by develar** [comment]
Electron builder for zip target uses original electron exe and cannot set env. Possible solution — if no APPIMAGE env, it is zip target. You can use standard API to get path to executable.

**Comment by FrogTheFrog** [comment]
I see, just one last question. When build with `nsis` target, is `NSIS` env set?

**Comment by develar** [comment]
No. The same problem — original electron executable is used as is.

Maybe you can use --em to add extra field to package.json, but in this case you can build only one target per CLI invocation.

**Comment by FrogTheFrog** [comment]
Well, I'll figure something out. Thank you for your time and have a nice day @develar !

**Comment by develar** [comment]
To be clear — we are open to any suggestion that will make user life more easier and will simplify build configuration. Regardless how complex implementation could be. But in this case no way except using special wrapper for electron — but this solution has runtime impact and, so, not acceptable. Because alternative solution in the user code — just check presence of some env, has no impact at all and doesn't look complex.

If you use webpack (electron-webpack) and want ability to build app per target — feel free to request.
