### ISSUE TITLE
RangeError: Maximum call stack size exceeded when invoke computeSortedPaths

### ISSUE THREAD

**Issue by frankLife** [electron-userland/electron-builder#1956]
* **Version**:  19.22.1(latest)

* **Target**:  mac

![image](https://user-images.githubusercontent.com/5081884/29373341-809601aa-82e0-11e7-87d7-6f69c0f057e8.png)

But when I use v13.11.1 builder , the process works.
How can solve this ❓

**Comment by develar** [comment]
Remove `node_modules` and install deps using [yarn](https://yarnpkg.com/en/): `yarn`

**Comment by frankLife** [comment]
thanks, it works

**Comment by develar** [comment]
Please don't use buggy NPM :)
