### ISSUE TITLE
Video with GetUserMedia not working after build

### ISSUE THREAD

**Issue by elissonlima** [electron-userland/electron-builder#1957]
* **Version**: 5.12

* **Target**: windows

Running app from command line using electron the webcam works well, but after run electron-build the webcam does not work.

I'm using navigator.mediaDevices.getUserMedia.

**Comment by rgasparfin** [comment]
how did you solve this ? I´m having the same problem

**Comment by patrickmichalina** [comment]
Same here... runs fine in electron before the build process. Now I just see a DOMException.

**Comment by takuyabz** [comment]
me too,

**Comment by vedaprakashms** [comment]
any update on this ?? i know this is a long shot. 
to be more accurate, i have narrowed the problem to be not packing "navigator.mediaDevices"
![image](https://user-images.githubusercontent.com/28106564/120070041-a88f4d80-c0a6-11eb-8bf4-7960662292f0.png)
## Any other Fixes to use webcam in a electron project ??

**Comment by mmaietta** [comment]
From a quick search, this tutorial points at using 
```
window.navigator.webkitGetUserMedia(
    {video: true},
...
```
Ref: https://livebook.manning.com/book/cross-platform-desktop-applications/chapter-11/23

Also found this:
```
const constraints = {
    audio: false,
    video: {
        mandatory: {
            maxHeight: 480,
            maxWidth: 800,
            minHeight: 480,
            minWidth: 800,
        }
    }
};

const videoElement = document.getElementById('video');

navigator.getUserMedia = navigator.webkitGetUserMedia;
navigator.getUserMedia(
    constraints,
    stream => videoElement.src = window.URL.createObjectURL(stream),
    error => console.error(error));
```
Ref: https://stackoverflow.com/a/45361226
