### ISSUE TITLE
command faild when build linux version 

### ISSUE THREAD

**Issue by frankLife** [electron-userland/electron-builder#1959]
* **Version**: 19.22.2

* **Target**: deb

![image](https://user-images.githubusercontent.com/5081884/29403599-5cdef678-836b-11e7-87e2-802af110b593.png)

**Comment by frankLife** [comment]
@develar may you give some advice ? 🤔

**Comment by develar** [comment]
Please try 19.23.1

**Comment by develar** [comment]
Should be fixed in 19.24.0.
