### ISSUE TITLE
nsis icons

### ISSUE THREAD

**Issue by 42cph4nzt48** [electron-userland/electron-builder#1960]
* **Version**: v19.22.1

* **Target**: nsis, nsis-web

Target **nsis** works great, but the displayed icon is pixelated. I've tried an ico file that includes the following image sizes: 16x16, 24x24, 32x32, 48x48, 64x64, 128x128 and 256x256.

Both the small icon in the window title bar (16x16) and the larger one in the dialog header (32x32) are ugly. Deleting all sizes but 32x32 doesn't help either. 

Would be great if anybody knows how to solve this problem. The App icon looks good in all sizes.

With regard to the nsisWeb target I'm looking for a way to read the appPackageUrl from an external file. This is not really important, but would be nice to have.

Thanks for your help!

**Comment by develar** [comment]
Is this issue still actual? We use provided icon as is.

> With regard to the nsisWeb target I'm looking for a way to read the appPackageUrl from an external file. This is not really important, but would be nice to have.

Please file new issue and describe use case.

**Comment by 42cph4nzt48** [comment]
I've just tried it without **installerIcon** and **installerHeaderIcon** and it looks the same. When I remove the 'build/icon.ico' as well and rename the icon files, the electron standard icon is used. 

> ⚠️  Application icon is not set, default Electron icon will be used

The default icons of NSIS installer look blurry and pixelated as well. Is this maybe an issue with NSIS installer?

**Comment by develar** [comment]
If default icons looks blurry, it means that something is broken in your system :)

**Comment by develar** [comment]
Windows version?

**Comment by 42cph4nzt48** [comment]
Hi, it's a Virtual Machine. Yes, the default icon is bIurry too. I think the problem is the high resolution of the screen together with the VM. The images seem to be scaled. Thank you develar.
