### ISSUE TITLE
NSIS - Change $INSTDIR to a custom path

### ISSUE THREAD

**Issue by hemavidal** [electron-userland/electron-builder#1961]
`Electron Builder - 19.22.1`
`Target - NSIS`

I'm trying to change the default installation directory to custom(Ex: C:\MyApp) and remove default(C:\Program Files\MyApp).
**package.json**
```json
{
    "win": {
      "target": "NSIS",
      "icon": "build/icon.ico"
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "include": "build/installer.nsh"
    }
}
```
I used !macro preInit, but didn't work:
**build/installer.nsh**
```
!macro preInit
  StrCpy $INSTDIR "C:\MyApp"
!macroend
```
**error**
```log
command StrCpy not valid outside Section or Function
```
It is possible to change default installation do C:\MyApp even if installer have only in elevation mode?

**Comment by develar** [comment]
`ReadRegStr $perMachineInstallationFolder HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation` is used to detect previous path.

If you want to set custom path,

```
WriteRegStr SHELL_CONTEXT "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\MyApp"
```

can be used (note - not tested).

> allowToChangeInstallationDirectory

not required in this case.

**Comment by hemavidal** [comment]
I resolved with this:
`!macro preInit
	SetRegView 64
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\MyApp"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\MyApp"
	SetRegView 32
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\MyApp"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\MyApp"
!macroend`

**Comment by sincerefly** [comment]
@hemavidal Can I change ${INSTALL_REGISTRY_KEY} to a String，Beacuse I wan't know the regedit path，when I change it， Program will not create uninstall panel record

**Comment by Kelerchian** [comment]
@hemavidal @develar 
Just letting you know guys:
This would make autoUpdate always install to "C:\MyApp" (or your designated default dir) It happens on electron-builder 20.4.1.

Steps to reproduce:
1. Make to version of your app, e.g. v0.1.0 and v.0.1.1
2. Install v0.1.0 on somewhere other than "C:\MyApp", for example "C:\MyAppp"
3. Let the autoupdate run.
4. Autoupdate will install on "C:\MyApp"

**Comment by soubhikchatterjee** [comment]
Does anyone knows what variable to use such that i can set the $INSTDIR  path as "C:\Users\{CURRENT_USERNAME}"

Where {CURRENT_USERNAME} is the currently logged in username.

Thanks

**Comment by TDola** [comment]
> Does anyone knows what variable to use such that i can set the $INSTDIR path as "C:\Users{CURRENT_USERNAME}"
> 
> Where {CURRENT_USERNAME} is the currently logged in username.
> 
> Thanks

I am also looking for this information

**Comment by Kelerchian** [comment]
> > Does anyone knows what variable to use such that i can set the $INSTDIR path as "C:\Users{CURRENT_USERNAME}"
> > Where {CURRENT_USERNAME} is the currently logged in username.
> > Thanks
> 
> I am also looking for this information

I'm not sure if you can set the $INSTDIR

But, you can use [nsExec](https://nsis.sourceforge.io/NsExec_plug-in) to call `echo %homedrive%%homepath%` to get the user's home directory, which is `C:\Users\{CURRENT_USERNAME}`
