### ISSUE TITLE
Is there a way to disable the "integrate $APPIMAGE with your system" prompt for linux deploys?

### ISSUE THREAD

**Issue by y3sh** [electron-userland/electron-builder#1962]
* **19.22.1**: 

* **linux**: 

Is there a way to disable the prompt "Would you like to integrate $APPIMAGE with your system?" for linux builds?

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/linux/AppRun.sh#L165

I'm trying to create an automated deploy/run process for linux-powered kiosks, and this prompt requires a human to be present at each kiosk to click yes/no.

**Comment by y3sh** [comment]
Oh -- do we just need to have one of these files touched?

```
# Exit immediately of one of these files is present
# (e.g., because the desktop environment wants to handle desktop integration itself)
check_prevent "$HOME/.local/share/$VENDORPREFIX/no_desktopintegration"
check_prevent "/usr/share/$VENDORPREFIX/no_desktopintegration"
check_prevent "/etc/$VENDORPREFIX/no_desktopintegration"

```
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/linux/AppRun.sh#L100

**Comment by develar** [comment]
@y3sh I will add option to skip this prompt today (~several hours).

**Comment by develar** [comment]
19.24.0

```json
    "appImage": {
      "systemIntegration": "doNotAsk"
    }
```

**Comment by y3sh** [comment]
Tested... works perfect. I appreciate that fast turnaround!

**Comment by probonopd** [comment]
If you are managing the linux-powered kiosks, you could also set a setting on the system that would prevent _all_ such questions from appearing. Now I'm curious, is your linux-powered kiosk project publicly available?

**Comment by y3sh** [comment]
It's a private project. That's a good point, but I like the setting develar provided for when we roll out to different linux distros I don't have to go and disable this per each flavor of linux.

**Comment by oblitum** [comment]
Can I have this configuration for all AppImages I start by default, by saving it to a configuration file in my home directory? I couldn't find if that's documented.

**Comment by oblitum** [comment]
Sorry, I was asking as a final user of an AppImage I got, not as an AppImage builder. I don't system integrate the AppImage, and it keeps me asking about system integration any time I start it, I just wished to mute that.

**Comment by develar** [comment]
If asked every launch — it is bug. Please run in terminal and attach here terminal output.

**Comment by develar** [comment]
Set env APPIMAGE_SILENT_INSTALL=true in your user env to always perform silent installation.

**Comment by oblitum** [comment]
@develar I just want a silent execution, without have to install the .AppImage. Do you mean `APPIMAGE_SILENT_INSTALL=true` you system integrate without asking?

**Comment by oblitum** [comment]
For what is worth, I'm running [Steam ROM Manager](https://github.com/FrogTheFrog/steam-rom-manager/releases), and terminal output is empty. I always have to click NO for system integration when I start it.

**Comment by develar** [comment]
To disable — create file $HOME/.local/share/appimagekit/no_desktopintegration

**Comment by oblitum** [comment]
@develar OK, thanks for the info.

**Comment by jeancf** [comment]
@develar 

> create file $HOME/.local/share/appimagekit/no_desktopintegration

Does it also work for all users with `/usr/share/appimagekit/no_desktopintegration`?

**Comment by probonopd** [comment]
Yes.

**Comment by jeancf** [comment]
I check and it does. Perfect, thanks!

**Comment by gusbemacbe** [comment]
> To disable — create file $HOME/.local/share/appimagekit/no_desktopintegration

It does not work.

**Comment by gusbemacbe** [comment]
@probonopd 

Please, let us disable the annoying and repetitive startup dialog in Manjaro! Stop of forcing us to integrate the apps into the system!

**Comment by develar** [comment]
```json
{
  "appImage": {
    "systemIntegration": "doNotAsk"
  }
}
```


@gusbemacbe Just set `systemIntegration` See https://www.electron.build/configuration/appimage

**Comment by gusbemacbe** [comment]
@develar 

I do not develop AppImages. I do not have electron and npm installed. May I install them?

**Comment by develar** [comment]
@gusbemacbe Hmm... this repo about electron-builder.

**Comment by gusbemacbe** [comment]
@develar Hum, let @probonopd know.

**Comment by probonopd** [comment]
> @probonopd
> 
> Please, let us disable the annoying and repetitive startup dialog in Manjaro! Stop of forcing us to integrate the apps into the system!

I agree. I would recommend to get rid of the desktop integration wrapper bash script inside the AppImages produced by `electron-builder` entirely. In the AppImage project, we have long stopped using such scripts.

Users who want desktop integration can use the optional `appimaged` daemon or third-party solutions like AppImageLauncher.

**Comment by nshiell** [comment]
Is it possible to have an environment variable? I like the desktop integration feature, however when running AppImages in shell scripts I need for the dialog to not appear and for them not to be installed.

Maybe something like:

`APPIMAGE_DO_NOT_INSTALL=1 ./SomeFile.AppImage`

**Comment by probonopd** [comment]
Please see

https://github.com/AppImage/AppImageKit/blob/076a88a57d7ca1a8d77bdbf7d8e92f37eea03dab/desktopintegration#L133-L145

It _should_ not attempt desktop integration if 
* a file called `no_desktopintegration` is present in one of the three locations
* a process called `appimaged` is running
* the environment variable `DESKTOPINTEGRATION` is not empty
