### ISSUE TITLE
[Linux] Desktop files contain at least one XDG main category

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#1965]
AppImages generated with electron-builder are most often lacking a `Categories=` entry in their `*.desktop` file.

For example:

```
[Desktop Entry]
Name=Webpack Dashboard
Comment=Webpack Dashboard
Exec=AppRun
Terminal=false
Type=Application
Icon=webpack-dashboard-app
X-AppImage-Version=0.1.0-beta.2
X-AppImage-BuildId=7039a870-8362-11a7-13de-27f5aa0eed21
```
This makes `desktop-file-validate` reject the desktop file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, electron-builder should __enforce__ that at least one of the following is set in the `Categories=` key. (Please test the result with `desktop-file-validate` and make sure it passes.)

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, electron-builder could offer to specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

**Comment by develar** [comment]
@probonopd Thanks for clear feature report, but I have already taken into account your note. Please see release notes — https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1

**Comment by probonopd** [comment]
Excellent @develar! Sorry for having opened an issue on what is already implemented.
