### ISSUE TITLE
set env variable to the packed app ?

### ISSUE THREAD

**Issue by kiuKisas** [electron-userland/electron-builder#1966]
* **Version**:  19.22.1

* **Target**:  Windows (NSIS)

Hi, I try to make an app with `electron-builder` and I neet to set `NODE_ENV=production`. 
I use `cross-env` to set it, I try to put it on my scripts (start, pack and dist) but doesn't work.

Any idea how can I do this ? Do I miss something ? 

I made this temporally fix but if any way exist to add env variable to the packed app, it can be awesome ! 
```
if (process.env.NODE_ENV == undefined) process.env.NODE_ENV = "production"
```
Thank's in advance !

**Comment by develar** [comment]
In general, it is not possible. Please see https://github.com/electron-userland/electron-builder/issues/1955 for details.

I recommend you to use https://github.com/sindresorhus/electron-is-dev

Is it suitable for you? If not, for what do you need such env for packed app?

**Comment by develar** [comment]
Well, you can also use webpack (https://github.com/electron-userland/electron-webpack), but I think `electron-is-dev` will be enough for you.

**Comment by kiuKisas** [comment]
Hi, thank's for your quick answer. 
I just need that to use `no-config`, so different config file in production and development. 
I'll go with my first solution, thank's again !

**Comment by develar** [comment]
Do you want ability — electron-builder should automatically use or `electron-builder.dev.yml` if NODE_ENV=developement, or `electron-builder.production.yml`?

**Comment by kiuKisas** [comment]
Maybe I wasn't clear enough, I just need different conf file in dev and prod.

- `config/dev.json` when I'm testing the app with `npm start`
- `config/prod.json` when I launch the app after installation

I'm using `node-config` that load my conf file according to `NODE_ENV`.

So I set `npm start` with `NODE_ENV=development` with this following line at the beginning of my app, it does the tricks for production.
```
if (process.env.NODE_ENV == undefined) process.env.NODE_ENV = "production"
```

**Comment by karimhossenbux** [comment]
not sure if it will help someone but I end up using webpack.DefinePlugin

```
/**
 * Adjust mainConfig for production settings
 */
if (process.env.NODE_ENV === 'production') {
  mainConfig.plugins.push(
    new BabiliWebpackPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    })
  )
}
```

it redeclares process.env.NODE_ENV during build script to make it available into the built app

**Comment by daniellizik** [comment]
> Is it suitable for you? If not, for what do you need such env for packed app?

Late reply but yes, in my app I'm simply doing `mainWindow.loadURL(...)` but these need to be pointed to different deploy targets...localhost, staging, pilot, etc., prod.

**Comment by Bear1110** [comment]
Good. I can't even know this way.

**Comment by jjtfsalgado** [comment]
@daniellizik I'm struggling with the same requirement, did you found a solution for it?

**Comment by daniellizik** [comment]
@jjtfsalgado I just wrote a script that cached `package.json` in a temporary file, then modified `package.json` and ran the build. Ugly but it worked.

**Comment by alexandermckay** [comment]
Why not just use the get method `app.isPackaged`
[Docs](https://www.electronjs.org/docs/api/app#appispackaged-readonly)

**Comment by daniellizik** [comment]
@alexandermckay that'd work if you only had two environments as the docs suggest. If you have like three or more you need something else.

**Comment by fergardi** [comment]
I'm interested as well in this feature. I work with 5 or more environments (development, staging, demo, preproduction, production), and of course my window url changes accordingly. Usually I set my environment variables using dotenv or crossenv, but with electron-builder this does not work.

Any news or workarounds?

Thanks.

**Comment by LeonardoRick** [comment]
How hard is to find a solution to such a simple feature

**Comment by mmaietta** [comment]
electron-builder is a packager, not a bundler.

If you'd like to bundle variables that are defined by env vars (such as via `export` or `cross-env`), then I would advise for webpack's Define plugin or any other _bundler_

**Comment by avisk1** [comment]
Having to use an entire bundler for simply setting a couple of environment variables for the packaged app seems really tedious. And it's not like setting environment variables for the packaged app is uncommon, this is a feature that many apps will need to use if they want to keep their API keys and whatnot secure. There should really be a better way to do this.

**Comment by mmaietta** [comment]
env vars are for configuring a running process. Hence we have `process.env.<VAR>` 

If one were to zip a folder with a TOKEN env var set, would you expect the un-zip of the folder to restore the TOKEN env var? I'd hope not.

This functionality/request is 100% not within the realm of electron-builder. You provide the bundled/packaged/env-injected app code, electron-builder packages it.
