### ISSUE TITLE
macos  10.12.6 MAS package crash on launch 

### ISSUE THREAD

**Issue by fu122zh** [electron-userland/electron-builder#1967]
* **Version**: electron-builder 19.23.0

* **Target**: macos

dmg work fine. but MAS pkg will crash on launch, i think may be something wrong with code sign...

crash report:
Process:               EDITOR [10651]
Path:                  /Users/USER/Documents/*/EDITOR.app/Contents/MacOS/EDITOR
Identifier:            im.EDITOR.pceditor
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           EDITOR [10651]
User ID:               501

Date/Time:             2017-08-20 02:45:15.599 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        3BA22CA9-FBEA-3969-F4DB-E86B8E15EED6

Sleep/Wake UUID:       908F1DE1-7255-44F9-8CC9-3C0FC0391E7A

Time Awake Since Boot: 32000 seconds
Time Since Wake:       9100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010a1ba000-000000010a1bb000 [    4K] r-x/rwx SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000010c551000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff55a45c48
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010c551000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10a1ba000 -        0x10a1baff7 +??? (0) <107BF4A4-1BF7-306B-944D-7DED190A60FE> (null)
       0x10c550000 -        0x10c58ddc7 +??? (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 37022
    thread_create: 0
    thread_set_state: 0

AND BUILD LOGS:
OKAY  take it away `electron-builder`

electron-builder 19.23.0
No native production dependencies
Packaging for mas x64 using electron 1.7.6 to build/mas
  electron-osx-sign electron-osx-sign@0.4.7 +0ms
Signing app (identity: 39773BF9CCB517E0457D54A4A6BC31618C776C46 3rd Party Mac Developer Application: Shenzhen Grameen Vision Cultural Communication Co., Ltd (HDGHJS34MK))
  electron-osx-sign `identity` passed in arguments. +5ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile:
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +2ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`:
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +2ms
  electron-osx-sign Executing... security cms -D -i /Users/LI/Documents/code/EDITOR-destop/embedded.provisionprofile +3ms
  electron-osx-sign Provisioning profile:
 > Name: EDITOR-pc-editor-appstore-profile
 > Platforms: [ 'mas' ]
 > Type: distribution
 > Path: /Users/LI/Documents/code/EDITOR-destop/embedded.provisionprofile
 > Message: { AppIDName: 'EDITOR pc',
  ApplicationIdentifierPrefix: [ 'HDGHJS34MK' ],
  CreationDate: 2017-08-15T09:42:48.000Z,
  Platform: [ 'OSX' ],
  DeveloperCertificates: [ <Buffer 30 82 06 01 30 82 04 e9 a0 03 02 01 02 02 08 53 22 43 cd f1 1a 46 d6 30 0d 06 09 2a 86 48 86 f7 0d 01 01 05 05 00 30 81 96 31 0b 30 09 06 03 55 04 06 ... > ],
  Entitlements:
   { 'keychain-access-groups': [ 'HDGHJS34MK.*' ],
     'com.apple.application-identifier': 'HDGHJS34MK.im.EDITOR.pceditor',
     'com.apple.developer.team-identifier': 'HDGHJS34MK' },
  ExpirationDate: 2018-08-15T08:49:30.000Z,
  Name: 'EDITOR-pc-editor-appstore-profile',
  TeamIdentifier: [ 'HDGHJS34MK' ],
  TeamName: 'Shenzhen Grameen Vision Cultural Communication Co., Ltd',
  TimeToLive: 364,
  UUID: '0a08a903-d090-45e3-9240-43990b571e3a',
  Version: 1 } +88ms
  electron-osx-sign Found 1 provisioning profile. +4ms
  electron-osx-sign Looking for existing provisioning profile... +0ms
  electron-osx-sign Embedding provisioning profile... +1ms
  electron-osx-sign Copying file...
 > Source: /Users/LI/Documents/code/EDITOR-destop/embedded.provisionprofile
 > Target: /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/embedded.provisionprofile +0ms
  electron-osx-sign Automating entitlement app group...
 > Info.plist: /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Info.plist
 > Entitlements: /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.plist +2ms
  electron-osx-sign `ElectronTeamID` not found in `Info.plist`, use parsed from provisioning profile: HDGHJS34MK +3ms
  electron-osx-sign Entitlements file updated:
 > Info.plist: /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Info.plist +5ms
  electron-osx-sign `com.apple.application-identifier` not found in entitlements file, new inserted: HDGHJS34MK.im.EDITOR.pceditor +0ms
  electron-osx-sign `com.apple.developer.team-identifier` not found in entitlements file, new inserted: HDGHJS34MK +0ms
  electron-osx-sign `com.apple.security.application-groups` found in entitlements file: HDGHJS34MK.im.EDITOR.pceditor +0ms
  electron-osx-sign Entitlements file updated:
 > Entitlements: /var/folders/nm/fg4spn8d4gv2c2sk5pg4bf9h0000gn/T/tmp-entitlements-2928-0.plist +1ms
  electron-osx-sign Signing application...
 > Application: /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app
 > Platform: mas
 > Entitlements: /var/folders/nm/fg4spn8d4gv2c2sk5pg4bf9h0000gn/T/tmp-entitlements-2928-0.plist
 > Child entitlements: /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist
 > Additional binaries: undefined
 > Identity: { name: '3rd Party Mac Developer Application: Shenzhen Grameen Vision Cultural Communication Co., Ltd (HDGHJS34MK)',
  hash: '39773BF9CCB517E0457D54A4A6BC31618C776C46' } +1ms
  electron-osx-sign Walking... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents +1ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +49ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +1ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +2s
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +171ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework +394ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/Electron Framework.framework +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper EH.app/Contents/MacOS/EDITOR Helper EH +1s
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper EH.app/Contents/MacOS/EDITOR Helper EH +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper EH.app +126ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper EH.app +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper NP.app/Contents/MacOS/EDITOR Helper NP +118ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper NP.app/Contents/MacOS/EDITOR Helper NP +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper NP.app +114ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper NP.app +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper.app/Contents/MacOS/EDITOR Helper +136ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper.app/Contents/MacOS/EDITOR Helper +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper.app +168ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/Frameworks/EDITOR Helper.app +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/MacOS/EDITOR +134ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /Users/LI/Documents/code/EDITOR-destop/build/entitlements.mas.inherit.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app/Contents/MacOS/EDITOR +0ms
  electron-osx-sign Signing... /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app +196ms
  electron-osx-sign Executing... codesign --sign 39773BF9CCB517E0457D54A4A6BC31618C776C46 --force --entitlements /var/folders/nm/fg4spn8d4gv2c2sk5pg4bf9h0000gn/T/tmp-entitlements-2928-0.plist /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app +1ms
  electron-osx-sign Verifying... +209ms
  electron-osx-sign Verifying application bundle with codesign... +0ms
  electron-osx-sign Executing... codesign --verify --deep --verbose=2 --strict /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app +0ms
  electron-osx-sign Verified. +779ms
  electron-osx-sign Displaying entitlements... +0ms
  electron-osx-sign Executing... codesign --display --entitlements :- /Users/LI/Documents/code/EDITOR-destop/build/mas/EDITOR.app +0ms
  electron-osx-sign Entitlements:
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <string>HDGHJS34MK.im.EDITOR.pceditor</string>
    <key>com.apple.application-identifier</key>
    <string>HDGHJS34MK.im.EDITOR.pceditor</string>
    <key>com.apple.developer.team-identifier</key>
    <string>HDGHJS34MK</string>
  </dict>
</plist> +47ms
  electron-osx-sign Application signed. +0ms
Done in 55.50s.

**Comment by develar** [comment]
Please see #1196

**Comment by fu122zh** [comment]
@develar 
i uploaded the binary to iTunes Connect  for review, jejected by iTunes Connect 
Guideline 2.1 - Performance Your app crashed on Mac running macOS 10.12.6 when we: - App quits unexpectedly upon launch No crash log was

Is there anything else settings not set up？...
thanks

**Comment by develar** [comment]
Cc @sethlu could you please advise?

**Comment by sethlu** [comment]
Hi @fu122zh, the app is expected to crash at launch if code-signed for submission to iTunes Connect. (Ref: https://github.com/electron-userland/electron-osx-sign/issues/130#issuecomment-313744747) To test the app locally for development purposes, I would suggest signing with your `Mac Developer` certificate and setting the provisioning file to the one for development (not distribution)... Then your app should be able to launch correctly.

CC: @develar

**Comment by fu122zh** [comment]
@sethlu
i had sign my app by distribution certificate and provisioning file....
do you mean that i should upload my app to iTunes Connect signed by Mac Developer certificate and development provisioning file.
thanks a lot.

**Comment by sethlu** [comment]
@fu122zh so the one already signed with distribution certificate and the distributional provisioning profile is fine for submission to the Mac App Store. The *catch* is that... this signed version cannot be launched locally... and that's what caused your app to crash.

And to test it locally you may re-sign it with a development certificate and a development provisioning profile.

**Comment by jwheare** [comment]
@sethlu I'm still seeing this `Code Signature Invalid` crash on launch even when the app is signed with a `Mac Developer` certificate and a **development** provisioning profile in the working directory.

Apple's advice is to use the "archive" build flow:

https://developer.apple.com/library/content/qa/qa1884/_index.html
https://developer.apple.com/library/content/qa/qa1778/_index.html

Does electron-builder need to package the app in a specific way to make this work?

Here's my debug log

```
> DEBUG=electron-builder,electron-osx-sign ./node_modules/.bin/electron-builder --mac mas-dev
electron-builder 19.32.2
Using electron-builder.yml configuration file
  electron-builder Effective config:
  electron-builder mac:
  electron-builder   category: public.app-category.productivity
  electron-builder   target:
  electron-builder     - dmg
  electron-builder     - zip
  electron-builder mas:
  electron-builder   publish: null
  electron-builder linux:
  electron-builder   category: Network;IRCClient
  electron-builder   target:
  electron-builder     - deb
  electron-builder     - AppImage
  electron-builder dmg:
  electron-builder   icon: null
  electron-builder appId: com.irccloud.desktop
  electron-builder protocols:
  electron-builder   - name: IRC server URL
  electron-builder     role: Viewer
  electron-builder     schemes:
  electron-builder       - irc
  electron-builder       - ircs
  electron-builder  +0ms
Rebuilding native production dependencies for darwin:x64
  electron-builder Spawning npm rebuild spellchecker@3.4.3 +5s
  electron-builder cwd: /Users/james/src/irccloud/desktop +0ms

... snip ...

  electron-builder npm (87453) exited with exit code 0 +18s
Packaging for mas x64 using electron 1.8.1 to dist/mas-dev
  electron-builder Spawning /Users/james/src/irccloud/desktop/node_modules/7zip-bin-mac/7za x -bd /Users/james/Library/Caches/electron/electron-v1.8.1-mas-x64.zip -aoa -o/Users/james/src/irccloud/desktop/dist/mas-dev +771ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 47530767 bytes (46 MiB)

Extracting archive: /Users/james/Library/Caches/electron/electron-v1.8.1-mas-x64.zip
--
Path = /Users/james/Library/Caches/electron/electron-v1.8.1-mas-x64.zip
Type = zip
Physical Size = 47530767

Everything is Ok

Folders: 125
Files: 85
Size:       119443356
Compressed: 47530767
  electron-builder 7za (88816) exited with exit code 0 +2s
  electron-builder Executing security find-identity -v +6s
  electron-builder Executing security find-identity -v -p codesigning +16ms

... snip ...

  electron-builder      7 valid identities found
  electron-builder  +1s

... snip ...

  electron-builder      15 valid identities found
  electron-builder  +175ms
 electron-osx-sign electron-osx-sign@0.4.7 +0ms
Signing app (identity: CERTHASHREDACTED Mac Developer: James Wheare (DEVIDREDACTED))
  electron-osx-sign `identity` passed in arguments. +4ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile:
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +0ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`:
 * Disable by setting `pre-auto-entitlements` to `false`. +1ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +0ms
  electron-osx-sign Executing... security cms -D -i /Users/james/src/irccloud/desktop/James_Desktop_App_Dev.provisionprofile +3ms
  electron-osx-sign Provisioning profile:
 > Name: James Desktop App Dev
 > Platforms: [ 'darwin', 'mas' ]
 > Type: development
 > Path: /Users/james/src/irccloud/desktop/James_Desktop_App_Dev.provisionprofile
 > Message: { AppIDName: 'IRCCloud',
  ApplicationIdentifierPrefix: [ 'TEAMIDREDACTED' ],
  CreationDate: 2017-02-01T10:21:14.000Z,
  Platform: [ 'OSX' ],
  DeveloperCertificates: [ <Buffer REDACTED > ],
  Entitlements:
   { 'keychain-access-groups': [ 'TEAMIDREDACTED.*' ],
     'com.apple.application-identifier': 'TEAMIDREDACTED.com.irccloud.desktop',
     'com.apple.developer.ubiquity-kvstore-identifier': 'TEAMIDREDACTED.*',
     'com.apple.developer.ubiquity-container-identifiers': [ 'TEAMIDREDACTED.*' ],
     'com.apple.developer.team-identifier': 'TEAMIDREDACTED',
     'com.apple.developer.aps-environment': 'development' },
  ExpirationDate: 2018-02-01T10:21:14.000Z,
  Name: 'James Desktop App Dev',
  ProvisionedDevices: [ 'DEVICE-UUID-REDACTED' ],
  TeamIdentifier: [ 'TEAMIDREDACTED' ],
  TeamName: 'IRCCloud Ltd.',
  TimeToLive: 365,
  UUID: 'PROFILE-UUID-REDACTED',
  Version: 1 } +134ms
  electron-osx-sign Found 1 provisioning profile. +4ms
  electron-osx-sign Looking for existing provisioning profile... +4ms
  electron-osx-sign Embedding provisioning profile... +1ms
  electron-osx-sign Copying file...
 > Source: /Users/james/src/irccloud/desktop/James_Desktop_App_Dev.provisionprofile
 > Target: /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/embedded.provisionprofile +0ms
  electron-osx-sign Automating entitlement app group...
 > Info.plist: /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Info.plist
 > Entitlements: /Users/james/src/irccloud/desktop/build/entitlements.mas.plist +2ms
  electron-osx-sign `ElectronTeamID` not found in `Info.plist`, use parsed from provisioning profile: TEAMIDREDACTED +5ms
  electron-osx-sign Entitlements file updated:
 > Info.plist: /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Info.plist +3ms
  electron-osx-sign `com.apple.application-identifier` not found in entitlements file, new inserted: TEAMIDREDACTED.com.irccloud.desktop +0ms
  electron-osx-sign `com.apple.developer.team-identifier` not found in entitlements file, new inserted: TEAMIDREDACTED +1ms
  electron-osx-sign `com.apple.security.application-groups` not found in entitlements file, new inserted: TEAMIDREDACTED.com.irccloud.desktop +0ms
  electron-osx-sign Entitlements file updated:
 > Entitlements: /var/folders/cp/TMPIDREDACTED/T/tmp-entitlements-1559a-0.plist +2ms
  electron-osx-sign Signing application...
 > Application: /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app
 > Platform: mas
 > Entitlements: /var/folders/cp/TMPIDREDACTED/T/tmp-entitlements-1559a-0.plist
 > Child entitlements: /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist
 > Additional binaries: undefined
 > Identity: { name: 'Mac Developer: James Wheare (DEVIDREDACTED)',
  hash: 'CERTHASHREDACTED' } +3ms
  electron-osx-sign Walking... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents +3ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +49ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +1ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +4s
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +375ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework +735ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/Electron Framework.framework +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper EH.app/Contents/MacOS/IRCCloud Helper EH +2s
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper EH.app/Contents/MacOS/IRCCloud Helper EH +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper EH.app +431ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper EH.app +1ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper NP.app/Contents/MacOS/IRCCloud Helper NP +376ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper NP.app/Contents/MacOS/IRCCloud Helper NP +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper NP.app +582ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper NP.app +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper.app/Contents/MacOS/IRCCloud Helper +432ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper.app/Contents/MacOS/IRCCloud Helper +1ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper.app +296ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/Frameworks/IRCCloud Helper.app +0ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/MacOS/IRCCloud +337ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /Users/james/src/irccloud/desktop/build/entitlements.mas.inherit.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app/Contents/MacOS/IRCCloud +1ms
  electron-osx-sign Signing... /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app +964ms
  electron-osx-sign Executing... codesign --sign CERTHASHREDACTED --force --entitlements /var/folders/cp/TMPIDREDACTED/T/tmp-entitlements-1559a-0.plist /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app +0ms
  electron-osx-sign Verifying... +1s
  electron-osx-sign Verifying application bundle with codesign... +1ms
  electron-osx-sign Executing... codesign --verify --deep --verbose=2 --strict /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app +0ms
  electron-osx-sign Verified. +1s
  electron-osx-sign Displaying entitlements... +0ms
  electron-osx-sign Executing... codesign --display --entitlements :- /Users/james/src/irccloud/desktop/dist/mas-dev/IRCCloud.app +0ms
  electron-osx-sign Entitlements:
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.temporary-exception.shared-preference.read-only</key>
    <array>
      <string>com.apple.symbolichotkeys</string>
    </array>
    <key>com.apple.security.files.downloads.read-write</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.application-identifier</key>
    <string>TEAMIDREDACTED.com.irccloud.desktop</string>
    <key>com.apple.developer.team-identifier</key>
    <string>TEAMIDREDACTED</string>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>TEAMIDREDACTED.com.irccloud.desktop</string>
    </array>
  </dict>
</plist> +71ms
  electron-osx-sign Application signed. +0ms
```

**Comment by sethlu** [comment]
@jwheare from the debug log I cannot think of an obvious solution. Can you provide a screenshot from the Console at the time your app's trying to launch? It should provide more details about the exception.

On https://github.com/electron-userland/electron-osx-sign/issues/153#issuecomment-333312280, `electron-osx-sign` currently doesn't support discovering provisioning profiles from the user library, since the build environments may differ.

**Comment by jwheare** [comment]
Well, I just tried with a fresh provisioning profile, and it now works. I'm chalking this up to the old profile having an old certificate associated with it. Sorry!

**Comment by jwheare** [comment]
Can that maybe be verified by the signing process? If the profile and certificate don't match show an error?

**Comment by sethlu** [comment]
@jwheare That sounds that a nice enhancement! Actually I encountered exactly the same issue with a dated provisioning profile and it took me some time to figure out the problem. Currently I am not sure how such misplacement can be verified and the code signing for production cannot be checked easily. Would you like to open an issue on `electron-osx-sign` and we can derive a method for it?

**Comment by jwheare** [comment]
Sure thing, done :) electron-userland/electron-osx-sign#154. Even if this only works for development signing it would be a help.

**Comment by sethlu** [comment]
@jwheare Great, thanks for providing some references too! I will try to experiment a little bit with that.
