### ISSUE TITLE
AppVeyor + "Cannot find module '7zip-bin-win'"

### ISSUE THREAD

**Issue by l3laze** [electron-userland/electron-builder#1968]
* **Version**: 19.22.1

* **Target**: Mac, Linux AppImage x86/x64, Windows NSIS x86/x64

I have been working on this for hours and no matter what it just keeps failing. IDK why that is, but I can build just fine locally on Mac OS X for Windows using Wine! Lol...

I also had this problem with Travis-CI at first, but it was fixed after I found an issue with my deploy script where it was still trying to deploy x86_64 and x86 versions of Linux AppImage, but it's building i386 and x86_64 versions nowadays. I have not found any obvious issues that would cause this same problem with AppVeyor.

I have tried installing 7zip, 7zip-bin, and 7zip-bin-win globally with NPM before running the build script on AV and none of them changed anything other than making it take just a little longer to fail. I've also tried both using the same NPM and Node I have installed locally and using the latest versions, and again nothing. I also tried changing the artifactName from using -'s to using _'s and, wait for it, again...nothing.

At this point I've tried everything I can think of including more than what's listed here but I have since forgotten, and it's all failing. After about 30 attempts I'm now ready to consider it a bug with electron-builder or that I just suck at life so hard I need help figuring out my own project's problem.

https://travis-ci.org/l3laze/ReliefValve
https://ci.appveyor.com/project/l3laze/reliefvalve
https://github.com/l3laze/ReliefValve

**Comment by develar** [comment]
It seems as always NPM bug. 

https://github.com/electron-userland/electron-builder/issues/1852#issuecomment-317648679

Do you use npm or yarn? Please remove `package-lock.json`,  `yarn.lock` and `node_modules` And install using yarn (not npm) again. 

DO NOT USE F**** NPM. Sorry for capslock.

**Comment by develar** [comment]
Example of CI files with yarn — https://github.com/electron-userland/electron-builder/issues/1751#issuecomment-312809154

**Comment by l3laze** [comment]
It worked pretty quickly after switching over -- thank you very much. Sorry to have added to the workload.


No problem with the caps; I can understand and at this point also agree with that statement =\ I can't believe npm is so broken..lol; that's really sad.

**Comment by develar** [comment]
Duplicates #1852
