### ISSUE TITLE
I use other package,There is '.editorconfig' file inside the template,packaged file is not found

### ISSUE THREAD

**Issue by hengkx** [electron-userland/electron-builder#1969]
* **Version**: 19.22.1

* **Target**: Windows 10,Windows 7

![image](https://user-images.githubusercontent.com/8358236/29506158-d267fc50-867c-11e7-9ca3-c3d6cbb9cd16.png)

packaged after:
![image](https://user-images.githubusercontent.com/8358236/29506195-fa4cfaf4-867c-11e7-9b4c-05d7e4b87d7b.png)

**Comment by develar** [comment]
`'.editorconfig` is filtered out always. Why it is required?

**Comment by hengkx** [comment]
@develar I need create a project by boilerplate.`.editorconfig`  inside boilerplate.[vd-generator](https://github.com/FuluUE/vd-generator/tree/master/boilerplates/project/pcWeb)

**Comment by develar** [comment]
Yeach, I will release some fix for you in several hours.

**Comment by hengkx** [comment]
Thank you very much

**Comment by develar** [comment]
Please try 19.24.1
