### ISSUE TITLE
Difference in CPU usage after Bundling

### ISSUE THREAD

**Issue by fab1an** [electron-userland/electron-builder#1970]
* **Version**: 19.22.1

* **Target**: mac

I have an application that displays a desktop-widget (frameless desktop window). 
When I start electron directly everything works as it should. 

When I package and sign the app using electron-builder performance drops.
Whenever I fiddle my mouse over the desktop I see the main-process using CPU in the Activity Monitor.

I tried profiling my app, but this ONLY occurs after packaging everything to an `.app` - bundle.

**Comment by develar** [comment]
Interesting. Electron version? We use Electron original Info.plist as is (only meta like name and version are changed), so, issue is not clear for me.

**Comment by fab1an** [comment]
Latest version from npm: 1.6.11

**Comment by develar** [comment]
Latest stable is 1.7.5. Could you please update just to be sure?

**Comment by fab1an** [comment]
Ah, I do have `1.7.5` ("Packaging for darwin x64 using electron 1.7.5 to dist/mac")

Just `package.json` reported the old version.

**Comment by develar** [comment]
Unlikely I can help you. electron-builder doesn't touch any setting and doesn't try to customise something. You can send me app to check it on another machine.

If you use electron-is-dev (or similar approach) — check such places in your code. Try to don't use devtools or devtron (if you use) in the dev mode to check.

**Comment by develar** [comment]
Is app signed?

**Comment by fab1an** [comment]
I will try to make a test-case. Yes, the app is signed.

**Comment by develar** [comment]
To be sure, try to test unsigned app.

**Comment by fab1an** [comment]
Why did you close this?

**Comment by develar** [comment]
I cannot help you and want to keep issue list clear. If you want to keep this issue open to make visible for other users — ok, reopened.

**Comment by fab1an** [comment]
Thanks, your choice. When I get around to the testcase I'll report what I find.

**Comment by develar** [comment]
You can still send me your app to test on another machine to ensure, that it is not your local issue.

**Comment by fab1an** [comment]
I haven't tracked down the bug, but I've verified that this occurs sometimes without electron-builder as well, so I'm closing this issue. Thank you for your quick help.

**Comment by fab1an** [comment]
@develar I have found what causes this. It's not an issue with signing.

Electron-builder sets "Supports Automatic Graphics Switching" to `TRUE` in `Info.plist`, which isn't set when running electron-directly. 
If I set that switch to `FALSE` the excess CPU usage goes away.

**Comment by develar** [comment]
@fab1an maybe related https://github.com/electron/electron/issues/9413

**Comment by fab1an** [comment]
My problem was: I had LSUIElement set in Info.plist to hude the dock icon. 
In the signed build this somehow let to the transparent fullscreen browserwindow to never lose focus hence the cpu usage on mouseover. 

I solved it by setting "focusable" to false on the BrowserWindow.
