### ISSUE TITLE
electron-builder loses *.h file with and without asar active

### ISSUE THREAD

**Issue by Alexisdu31** [electron-userland/electron-builder#1971]
* **Version**:  1.7.6

* **Target**:  Linux x64 and Win x64

In my application, I'm using some "\*.h" file. When I run `npm run dist` script (`"dist": "build"`) all of my "\*.h" files disappear on the unpack folder (and the executable is unusable). It's not an asar problem, I try `asarUnpack` and  `"asar" : "false"` for unpack my folder with my "\*.h" and I have the same result.
Every "\*.h" file in every subfolder is deleted, no exception...

At the beginning I suspected asar, but I installed it globally with npm on my computer and it's work perfectly : my "\*.h" files are not lost. (`asar pack myFolder myFolder.asar` and `asar e myFolder.asar testFolder`)

**Comment by develar** [comment]
Yes `.h` files are excluded by default. Do you mean that these files are part of your app, not from node_modules?

**Comment by Alexisdu31** [comment]
Yes they are part of my app. Is there a way to include them ?

**Comment by develar** [comment]
@Alexisdu31 Fixed in the 19.24.2

**Comment by Alexisdu31** [comment]
Thank you verry much @develar, it's work perfectly ! 

`npm update` for update electron-builder to 19.24.2 !

I just found i have `.o` file too in my project :/ To tell you everything i embedded an arduino package on my app (i hvve no other options) and arduino package need `.o` file in avr to compile my scketch.

Its possible to delete o file in `fileMatcher.ts` or not ?

Alexis

**Comment by develar** [comment]
Quite uncommon for apps to have o files, so, we just should include it — if someone need to exclude it, well, just ignore. For node_modules should be removed as before.

19.24.3

> npm update

Will not work because these releases are not latest, tag `next` is used for pre-releases.

**Comment by Alexisdu31** [comment]
Thank you very much @develar!
