### ISSUE TITLE
Self-signed code certificated is not accepted, saying CSSMERR_TP_NOT_TRUSTED

### ISSUE THREAD

**Issue by soulbeing** [electron-userland/electron-builder#1973]
* **Version**:   19.24.1

* **Target**: Mac, Window

1: I followed https://support.apple.com/kb/PH20131?locale=en_GB&viewlocale=en_US to create a self-signed certificate, only for code sign.
2: I followed https://github.com/electron-userland/electron-builder/wiki/Code-Signing, to export the certificate and base64 the .p12 file, and uses CSC_LINK, and CSC_KEY_PASSWORD
3: I run my electron build on Jenkins, and end up with the following:
All identities:
  1) 6CA65EA58B63E5AAF33EF872330C34EB29BCD406 "electronBuild" (CSSMERR_TP_NOT_TRUSTED)
     1 identities found

  Valid identities only
     0 valid identities found

4: Since I'm using squirrel, which need to be signed, and as the build didn't recognize my self-signed certificate, I can't open the built app.
5: Then I try build my app locally in the machine, using CSC_NAME of the same Certificate, all works fine. Then I try build app locally using CSC_LINK and CSC_KEY_PASSWORD, still works all fine.
So the issue is why my electron-build in jenkins refuse to accept the same certificate?

**Comment by develar** [comment]
Is cert marked as trusted in the keychain?

Do you aware that you can use free Mac developer cert from Apple for dev builds?

**Comment by develar** [comment]
Ouch — I see, you use it on CI. So, is Mac developer cert is an option for you? If not, I can try to fix this issue, but consider just use free cert from Apple.

**Comment by soulbeing** [comment]
So in order to use this free cert from Apple, do I have to have an Apple account, and generate Mac Developer Cert from Xcode(this is what I know about)? Or is there a link where I can simply download the Mac Developer Cert?

**Comment by soulbeing** [comment]
Btw, I tried multiple ways to create the self-signed code sign certificate, and the most correct one is like this: I created Self-Signed CA first, then I create a LEAF certificate, issued by the self-signed CA, and as a result, the self-sign certificate is marked as "this certificate is valid", and looks all good when I evaluate it for code sign.

**Comment by develar** [comment]
Yes, you need have Apple account (paid membership not required) and issue cert using Xcode.

**Comment by soulbeing** [comment]
Actually, I figured it out. I don't need to have a specific Apple ID for this. So basically the right way to create a self-signed certificate for electron build on CI is:
1: Create a self-signed Certificate CA first by choose "Certificate Assistant -> Create a Certificate Authority", enter a email, uncheck "Make this CA the default", uncheck "Let me Override defaults", use "Self-Signed Root CA" for type and "Code Signing" for user certificate.
2: Change the Trust Settings to "Always Trust"
3: Then choose ""Certificate Assistant -> Create a Certificate" , use "Leaf" for Type, and "Code Signing" for Type, check "Let me Override defaults", in one of the following steps, choose the self-signed CA as An Issuer, and keep default for all the else.
4: Select Both CA and Certificated you generated, export "BOTH", base64 it blabla.....the rest is the same as described in the https://github.com/electron-userland/electron-builder/wiki/Code-Signing
5: Use the value as CSC_LINK in a CI, all works fine.

**Comment by soulbeing** [comment]
it would be nice and helpful if you can include my findings in https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by develar** [comment]
So cool to see a smart user :) I will add your comment to docs.

**Comment by salomvary** [comment]
Unfortunately the solution by @soulbeing does not work for me. Even though I set "Always Trust" for everything both on the CA and the self-signed certificate before exporting, they will both be untrusted when imported to Travis: https://travis-ci.org/salomvary/electron-hello-world/jobs/602838577#L265

The same certificate works fine locally on my MacBook. Maybe the trust settings are not exported?

Btw the above mentioned wiki is now completely gone, this is the replacement I guess: https://www.electron.build/code-signing
