### ISSUE TITLE
Error during update downloading

### ISSUE THREAD

**Issue by Isahara86** [electron-userland/electron-builder#1975]
"electron-builder": "19.24.1"

"electron-updater": "2.8.7"

Windows/Mac OS X

Error during update downloading.
steps:
1. start downloading update.
2. turn off the internet connection
![screenshot_6](https://user-images.githubusercontent.com/22307774/29552610-be5ed8a6-8720-11e7-840b-0a274441fa56.png)

**Comment by sirgallifrey** [comment]
I'm having the same problem. It's probably due to a [aborted event](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_aborted) that should be listened to. I tried to find the issue but I could not understand the codebase well enough to make sense of it yet...

**Comment by develar** [comment]
@sirgallifrey bingo! https://electron.atom.io/docs/api/client-request/#event-abort Fixed.
