### ISSUE TITLE
Window build failed on CI because of wrong -pass

### ISSUE THREAD

**Issue by soulbeing** [electron-userland/electron-builder#1977]
* **Version**: 19.24.1

* **Target**: Window

So basically I run electron build on Jenkins, (yesterday finally figured out self-signed code certificate), now when I build windows version using "build --w", it ends up with the following error:

electron-builder 19.24.1
CI detected, so artifacts will be published if draft release exists
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 x64 using electron 1.4.10 to dist/win-unpacked
Signing orion.exe (certificate file: "/private/var/folders/zq/hkyk02dn457ftn42vr4d2tj4000102/T/electron-builder-UE7Ypy/0.p12")
Error: Exit code: null. Command failed: /Users/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/ci/osslsigncode -in /Users/dist/win-unpacked/app.exe -out /Users/dist/win-unpacked/app-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /private/var/folders/zq/hkyk02dn457ftn42vr4d2tj4000102/T/electron-builder-UE7Ypy/0.p12 -h sha1 -n orion -pass 5ea631c48b7f901ac9dcb156f48a4daae0d76368d84ddc8dd0e791cc11a2654c (sha256 hash)

I use CSC_LINK and CSC_KEY_PASSWORD;

And I did some experiments locally
1: using the same "osslsigncode" command, but with the real password(not the hashed one) for the .p12 file,  everything works fine.
2: then I try to decode this sha256 hash, "5ea631c48b7...", it can't be reverted
So my question is how to fix this? is there something wrong with my real password, which is just 6 digit long with number and letters.

**Comment by develar** [comment]
sha256 hash is used to not show your pass in the logs. To ensure that your real password is correctly set, compute sha256 of it and compare.

**Comment by develar** [comment]
If you pass contains spaces, please avoid it.

**Comment by soulbeing** [comment]
I figured it out again. I have to use strong password https://security.stackexchange.com/questions/54763/how-secure-is-pkcs-12/54773#54773 for Windows build. and magically it works then.
