### ISSUE TITLE
Error: Cannot detect repository by .git/config. Please specify "repository" in the package.json

### ISSUE THREAD

**Issue by meowtec** [electron-userland/electron-builder#1981]
* **Version**: 
19.24.1

* **Target**: 
Mac

Failed with this error.
```
Error: Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts
    at /Users/berton/workspace/git/project/node_modules/_electron-builder@19.24.1@electron-builder/src/publish/PublishManager.ts:499:13
```

I am using gitlab for managing my project, and the repository field is:

```
"repository": {
  "type": "git",
  "url": "git@gitlab.domain.com:group/project.git"
 },
```

Maybe a github repository is necessary for publishing but I don't need it. 

I tried to add `--publish never`, no work.

**Comment by meowtec** [comment]
After I set `repository.url` to `https://github.com/electron-userland/electron-builder.git`, it build success.

**Comment by develar** [comment]
Please set `"publish": null` in the configuration to disable publishing.

**Comment by develar** [comment]
Solution: we should detect such case and disable default github provider.

**Comment by hkmoon** [comment]
I tried to publish the build to ```bintray``` with ```gitlab```. It gave the same error. It would be nice to handle such a case too.

**Comment by dombarnes** [comment]
Is this bug going to get addressed as its 2yrs old now?

**Comment by mahwd** [comment]
any solution ? This is 2 years since issue labeled as bug.

**Comment by Zaynex** [comment]
Did you add `publish` config in your package.jon ?
You can read the docs about it(https://www.electron.build/configuration/publish)

Example:
```
{
 "devDependencies":{},
"build": {
  "publish": [
      {
        "provider": "generic",
        "url": "http://download.ydstatic.com/notewebsite/downloads/meeting/"
      }
    ]
  }
}
```

**Remember publish belongs to build config**

**Comment by mikecbone** [comment]
@meowtec solution worked for me, but seems silly I have to add this to get it to work
