### ISSUE TITLE
Changes logs for electron-updater

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#1986]
Hi Develar ! Is there a way to see the `electron-updater` change logs ?

**Comment by develar** [comment]
Inspect electron-builder release notes — marked `electron-updater`. e.g. https://github.com/electron-userland/electron-builder/releases/tag/v19.18.0

Is it ok for you?

**Comment by popod** [comment]
This is what I do now. But it will be usefull to add the electron-updater release version in your comments. Is this possible ?
Because when I update this dependencie, I check the changes from my current version to the repository newer version and this is tricky without versions numbers..

**Comment by develar** [comment]
Separate changelog will be from now on.

**Comment by popod** [comment]
Nice, thanks !
