### ISSUE TITLE
How to add a NSIS README.md page to my app?

### ISSUE THREAD

**Issue by hemavidal** [electron-userland/electron-builder#1988]
"electron": "1.7.5",
"electron-builder": "19.24.1",
Target NSIS

- I've tried releaseInfo, but what i know it is used for publish app not to build .exe|.msi package.
- I want something similar of Lincese Page (I've tried adding license: **'build/license.txt'** and )
![image](https://user-images.githubusercontent.com/1553814/29692000-21d7b0c6-8904-11e7-9d80-17ee4c324808.png)

**Comment by develar** [comment]
So, why not to use license as readme ;)?

**Comment by hemavidal** [comment]
The license page is customizable?

**Comment by develar** [comment]
You can set own text. What else do you want to change?

**Comment by hemavidal** [comment]
Title, description...
All license text citations must be changed!

**Comment by develar** [comment]
Info for developer or heroes:

https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script

http://nsis.sourceforge.net/Readme_Page_Based_on_MUI_License_Page

**Comment by hemavidal** [comment]
Thanks for support @develar!
I'll read about it!

**Comment by develar** [comment]
You can or send PR, or wait when I will find time to support it.
