### ISSUE TITLE
Using file:/// in HTML in packaged apps

### ISSUE THREAD

**Issue by ajbdev** [electron-userland/electron-builder#1989]
* **Version**: 19.24.1

* **Target**: win32

When I package my app, tags using URL's referencing file:/// stop working. For example, I have a video tag whose source is an absolute URL to a spot on the hard disk and it reports this when I attempt to play:

```Uncaught (in promise) DOMException: The element has no supported sources.```

I am assuming this is somehow related to the ASAR packaging. Is there a way to whitelist certain file:/// URL's? In my particular case, I need to be able to reference files from the user's Documents directory directly with elements.

**Comment by ajbdev** [comment]
I am able to fix this by inlining the external video as a base64 encoded string like so:


```const videoData = 'data:video/webm;base64,' + new Buffer(fs.readFileSync(pathToExternalVideo)).toString('base64')```

Feels kinda gross though.

**Comment by develar** [comment]
Please use [exraResources](https://github.com/electron-userland/electron-builder/wiki/Options#Config-extraResources) to copy such video not to asar, but to `resources`. 

For packed app (you can use electron-is-dev or simply detect that current __dirname contains `.asar`), you can use https://github.com/electron/electron/blob/master/docs/api/process.md#processresourcespath to get path to resources dir.

**Comment by ajbdev** [comment]
The videos don't exist at the time of packaging. They are created by the app itself when it's ran and then played back afterwards.

**Comment by develar** [comment]
Where do you store it? Must be in the user data, not in app installation dir.

**Comment by ajbdev** [comment]
I had been storing them in the `app.getPath('documents')` folder (I wanted users to be able to find the video files easily on their own if they wanted to). Is it possible to do that or does it have to use the user data folder?

**Comment by develar** [comment]
> app.getPath('documents'

It is also user data.

So, I see that it is not related to electron-builder. Probably it is security restriction of Chrome to load videos from local disk. Not related to asar since you store video in the user dir and access it.

**Comment by ajbdev** [comment]
I think you're right. I tried setting webSecurity to false in the BrowserWindow webPreferences config but that didn't work. Either way this doesn't seem to be related to electron-builder.

**Comment by develar** [comment]
Ok, I hope you will find solution. btw — https://github.com/RIAEvangelist/electron-video-player also uses electron-builder but it seems can play video files from disk.

**Comment by ajbdev** [comment]
Thank you for the help!
