### ISSUE TITLE
How I add a my binary dependency in deb package?

### ISSUE THREAD

**Issue by fabriciolelis** [electron-userland/electron-builder#1991]
* **Version**: 
**19.22.2** 

* **Target**: 
**Linux**

I want to generate a deb package and inside this deb package, I need to put a binary file that I created.

**Comment by develar** [comment]
extraResources or extraFiles options. Please see https://github.com/electron-userland/electron-builder/wiki/Options

**Comment by fabriciolelis** [comment]
Is possible to do this in condition mode?
For example, I only add this package when I generated a build in Linux? I think if I use extraResources or extraFiles every time when I make a build I need this file in my project.

**Comment by develar** [comment]
@fabriciolelis You can specify `extraResources` in the `linux`. You can also write additional config file (use `extends: "electron-builder.yml"` to inherit from common config (extract config to `electron-builder.yml` from package.json `build`)) and specify it as `--config=yourCustomConfig`

**Comment by fabriciolelis** [comment]
@develar The option afterInstall in deb section, Is to create a script or a path to script? I asked this, because I need to create a service after the instalation process finish.

**Comment by develar** [comment]
@fabriciolelis It is path to script like `https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/linux/after-install.tpl` relative to project dir.
