### ISSUE TITLE
Support Google API KEY 

### ISSUE THREAD

**Issue by bradennapier** [electron-userland/electron-builder#1994]
This seems to completely break the ability to set the GOOGLE_API_KEY.  in development this is used to set the google api key from default so that the google apis actually work.  This does not work with electron builder as it is not passed in.... so this is actually 100% impossible to do as far as i can tell

**Comment by develar** [comment]
https://github.com/electron/electron/blob/master/docs/api/environment-variables.md

> process.env.GOOGLE_API_KEY = 'YOUR_KEY_HERE'

**Comment by develar** [comment]
On Mac env from bash is not available for apps.
