### ISSUE TITLE
Cannot find module 'cycle'

### ISSUE THREAD

**Issue by zhuhongyong** [electron-userland/electron-builder#1997]
* **Version**: 
19.24.1

* **Target**: 

Hi, i am a new to electron,  when i use electron-builder to package my project to a exe file,  and when i launch this exe file,  i received a error dialog,  
![image](https://user-images.githubusercontent.com/20338343/29743442-d250589c-8ac4-11e7-879e-609c0235da1c.png)

can you give any help ?

**Comment by develar** [comment]
Do you use npm? If yes, please use yarn instead. Npm is buggy and not recommended.

Is cycle in your production deps?

**Comment by jsgv** [comment]
@develar Do my packages have to be added as production deps?
I have them as dev deps.

**Comment by zhuhongyong** [comment]
Dear,


Thanks, I have solved the problem。
 
 
------------------ Original ------------------
