### ISSUE TITLE
Error Building on Mac (Zip)

### ISSUE THREAD

**Issue by DevCubeHD** [electron-userland/electron-builder#2000]
* **Version**:  1.6.6

* **Target**:  Mac, DMG

When I try to build on Mac VM I get this error:
https://paste.cloudsystem.io/xazofideva.rb
Zip file cannot be unzipped?

**Comment by develar** [comment]
Could you please try electron 1.6.11?

**Comment by develar** [comment]
Or latest 1.7.5

**Comment by DevCubeHD** [comment]
CloudSystem-Builders-Mac:Webpanel felix$ electron -v
v1.4.13
CloudSystem-Builders-Mac:Webpanel felix$ npm -v
3.10.10


newest possible on mac, arent they?

**Comment by develar** [comment]
Do not install electron globally. Latest electron is `1.7.5` (https://github.com/electron/electron/releases/tag/v1.7.5)

**Comment by DevCubeHD** [comment]
sudo npm install electron --save-dev?
To make it not globally?

**Comment by DevCubeHD** [comment]
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron" "--save-dev" "--save-exact"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path /Volumes/VMware Shared Folders/Webpanel/node_modules/.staging/assert-plus-f2d0622c/package.json
npm ERR! code EIO
npm ERR! errno -5
npm ERR! syscall open

npm ERR! EIO: i/o error, open '/Volumes/VMware Shared Folders/Webpanel/node_modules/.staging/assert-plus-f2d0622c/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/VMware Shared Folders/Webpanel/npm-debug.log

**Comment by DevCubeHD** [comment]
VMWare should not make the problem, right?

**Comment by develar** [comment]
This error not related to electron-builder, NPM cannot find your package.json. Is dir exist?
