### ISSUE TITLE
Publishing artifact as draft with electron-builder 19.26.0

### ISSUE THREAD

**Issue by yangwao** [electron-userland/electron-builder#2001]
* **Version**:  electron-builder 19.26.0
* **Target**: linux:x64

$ node .electron-vue/build.js && electron-builder --draft
lets-build
...
electron-builder 19.26.0
CI detected, so artifacts will be published if draft release exists

[Travis log is here](https://travis-ci.org/yangwao/skCube-data-collector/jobs/268972677)

Before this fix https://github.com/electron-userland/electron-builder/issues/1835 it worked as every time I received draft in Releases section at Github, now I tried to use --draft, but I must be doing something wrong. Can you pinpoint me how to automatically create draft of release? Thanks.

**Comment by develar** [comment]
Duplicates #1996

**Comment by yangwao** [comment]
How is this duplicate of #1996 ? 
In [appveyor](https://ci.appveyor.com/project/yangwao/skcube-data-collector/build/0.1.39) and [Travis log](https://travis-ci.org/yangwao/skCube-data-collector/jobs/268972677) I don't see that behaviour.

**Comment by develar** [comment]
@yangwao Please try 19.26.2

**Comment by develar** [comment]
@yangwao If you want to create releases automatically, you need to pass `--publish=always` (or name your script in the package.json as `release`).

**Comment by yangwao** [comment]
@develar I want to create **drafts** automatically even if they doesn't exists. `--draft` nor `--draft=true` does not work. 😞 
[Using information from wiki](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#cli-flags)

**Comment by develar** [comment]
> automatically even if they doesn't exists

@yangwao So, use `--publish=always` :)

**Comment by develar** [comment]
Sorry for confusion — `--draft` option not about "create or not create", this option about "is created release will be marked as draft or as release"

**Comment by yangwao** [comment]
Now I get it. Thanks for explanation! 🎉 
Now it works 
![image](https://user-images.githubusercontent.com/5887929/29809208-899cb4f0-8c9b-11e7-8b4c-ddee31132361.png)
Also, sent some donation, keep up project on!
