### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [electron-userland/electron-builder#2005]
* **Version**: 19.24.1 for Win7

Not using electron-updater

* **Target**:  Win7 Portable

I am writing an app whose sine qua non is to read and write to its own database, a single JSON file created by [LokiJS](http://lokijs.org/#/). The "unbuilt" version is working wonderfully and spawning its BrowserWindow on schecule. However, I want to build the package in order to to minimize the space I need to store it and to avoid storing unnecessary dev dependencies. The package will be distributed to a select few people who work in the same place I do, and all of them use Windows 7 as I do. The package builds without any errors, and if I disable the ASAR creation, I can see that all the files that should be in the app folder are there to the exclusion of others. However, I try to start the "built" version of the app, and no BrowserWindow is spawned. I can see the app process in the Windows Task Manager, but it will run indefinitely until I call to end it. I would inspect the contents of the logs except I HAVE NO CLUE WHERE THEY ARE. If you want to tell me where the logs are, or to look for a certain file, then please refer to the app folder as "app" (PLEASE no dollar signs or brackets of any shape) and the Windows system folder as "C:\Windows\SYSTEM\" or "C:\Windows\SYSTEM32\", whichever is correct. Thank you!

**Comment by develar** [comment]
Do you see any error in the devtools?

**Comment by ssimo3lsuhsc** [comment]
Yes, that's right. Error whether ASAR creation is enabled or disabled. As for the devtools, I don't understand what you are asking me to do. Whether you want me to debug the build process or debug the app launch, I cannot do your bidding without a list of steps. As much as I have developed, this is my first time "building" or "packaging" an app in any language.

**Comment by develar** [comment]
Please install https://github.com/sindresorhus/electron-debug#install (easy way) and open devtools.

```
const {app, BrowserWindow} = require('electron');

require('electron-debug')({showDevTools: true});
```

**Comment by ssimo3lsuhsc** [comment]
I can't get it to show ANYTHING. My app will NOT spawn BrowserWindows. I cannot use electron-debug.

**Comment by develar** [comment]
Well, so, just debug, using console statements or what do you prefer. If no lack — send me your app I will take a look.

**Comment by ssimo3lsuhsc** [comment]
I think I managed to figure it out myself. Loki wasn't finding the file it was supposed to find; I needed to use path.join and __dirname to find it.
