### ISSUE TITLE
Write to console.log / process.stdout on Windows

### ISSUE THREAD

**Issue by hash-bang** [electron-userland/electron-builder#2011]
* **Version**: 19.26.3
* **Target**: Windows (+ Mac, Linux is working fine)

This is possibly unrelated to electron-builder and possibly also a stupid question but I'm having real difficulty figuring out how to get access to `console.log` / `process.stdout.write` on Windows. Any output to those functions will be silently disguarded and the console (when the .exe is run from it) will not show anything.

Executables compiled for on Linux are working fine. I cannot currently test on Mac but assume its also fine there.

I understand Windows has a differentiation between GUI and console applications and tried a [few](https://stackoverflow.com/q/41818689/1295040) different [workarounds](https://github.com/electron/electron/issues/683#issuecomment-67055285) but for the life of me I cannot figure out how to do this (or even if its possible).

**Comment by develar** [comment]
Have you read https://stackoverflow.com/questions/31759367/using-console-log-in-electron-app?
