### ISSUE TITLE
Is it possible to autoupdate when the app quits, without restarting the app

### ISSUE THREAD

**Issue by chris-kostiw** [electron-userland/electron-builder#2015]
* **Version**: 19.17.0
* **Target**: OS X, Windows

I would to be able to launch my app, then run autoupdater in the background to download an update, and wait until the user quits the app before installing. I would like the update to happen when the user quits, or the next time the user launches the application.

I would like to avoid having to launch the app, download the installer, then relaunch the app, if that's possible.

Is there any way to do this with autoUpdater?

**Comment by develar** [comment]
It works by default. Just show notification and nothing more: https://github.com/develar/onshape-desktop-shell/blob/master/src/AppUpdater.ts

**Comment by chris-kostiw** [comment]
Thanks! I thought I had to call quitAndInstall() when I shut down, but that caused problems and the app would not launch normally the next time it was launched. I guess the trick is to just let the app quit normally and let the updater do the update automatically.
