### ISSUE TITLE
AppX: Reading publisher String from Certificate wrongly

### ISSUE THREAD

**Issue by markusmoenig** [electron-userland/electron-builder#2018]
Platform: Windows

For the AppX target, when the "publisher" string is missing electron-builder reads the "publisher" string from the certificate. However, special characters inside the certificate are read wrongly.

My STREET segment contained "Straße", the "ß" character was read as ?? causing the signing to crash. When taking this string, correcting the "ß" character and placing it in the appX / publisher section of the package.json it worked.

Took me some time to figure out why the signing crashed.

**Comment by develar** [comment]
Duplicates #2003 

Danke. I will fix this *** powershell issue this week.
