### ISSUE TITLE
Build Process Ignores `app/dist/` folder?

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#2021]
19.27.2

Win32/Mac

I recently tried again to update all my dependencies, including electron-builder. Everything was going great until I tried to build a production build. I kept getting "bundle.js not found" when I launched my app.

After a few hours of debugging (and turning off ASAR) I noticed that my `resources/app/` folder was copying EVERYTHING in local `/app/` (as expected) *except* `/app/dist/*`. There was no /dist folder no matter what. I tried including it via package.json `build/files` but that didn't seem to work either.

I was previous using `19.22.1` so I was hoping you could fill me in on what changed between `19.22.1` and `19.27.2` (if anything) that could have maybe caused this behavior?

Thanks in advance!

**Comment by develar** [comment]
@framerate Nothing changed. But I guess it is bug — #1929

Please as workaround change `directories.output` to another value.

**Comment by develar** [comment]
Duplicates #1929

**Comment by develar** [comment]
Duplicated issue will be fixed today, sorry for delay.

**Comment by framerate** [comment]
> Duplicated issue will be fixed today, sorry for delay.

Huh! Sorry I missed that one, I promised I searched! Thanks @develar, glad I'm not just crazy!
