### ISSUE TITLE
electron-builder loses *.obj file with and without asar active

### ISSUE THREAD

**Issue by wangez** [electron-userland/electron-builder#2022]
Version: 19.27.2
Target: Win x64
In my application, I'm using some "*.obj" file to show some 3d module. When I run npm run dist script ("dist": "build") all of my "*.obj" files disappear on the unpack folder (and the executable is unusable). It's not an asar problem, I try asarUnpack and "asar" : "false" for unpack my folder with my "*.obj" and I have the same result.
Every "*.obj" file in every subfolder is deleted, no exception...
I have see this [issue](https://github.com/electron-userland/electron-builder/issues/1971)
I want .obj files also can be filtered out only from node_modules, not from app.

**Comment by develar** [comment]
Will be fixed today.

**Comment by wangez** [comment]
Thank you very much

**Comment by develar** [comment]
Fixed in `19.27.3`.
