### ISSUE TITLE
Windows (Squirrel) Start Menu Category Won't Change from Email Address

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#2024]
* **19.27.2**: 

* **Windows**: 

```
    "win": {
            "icon": "build/icon.ico",
            "target": "squirrel",
            "publisherName": "Secret Cow Level"
        },
```
I thought by reading the documentation that `publisherName` was what I was missing, but no matter what I do, it seems to use my email from `package.json` -> `author` field? I don't want my email to be the Start Menu Category.

What am I missing? :)

**Comment by develar** [comment]
And you don't want to change `author`?

**Comment by framerate** [comment]
> And you don't want to change author?

Package.json author I believe is following this format: https://docs.npmjs.com/files/package.json

I have:

```
    "author": {
        "email": "justin@mydomain.com",
        "name": "My Company"
    }
```

I would expect that to use `My Company` for the company name, copyright and start menu (instead of my personal email address) but maybe that's not the case?

**Comment by develar** [comment]
We parse `author` and use only `name` component. So, it is indicator that parsing is not correctly implemented. Will investigate.

**Comment by develar** [comment]
Must be in the app package.json

**Comment by framerate** [comment]
Oh ok! Lastly, that seems a bit odd since ALL of the other `electron-builder` stuff is in `/package.json` right?

Why would this one feature use `/app`/? Or am I mistaken?

**Comment by develar** [comment]
> Why would this one feature use /app/? 

Because author belongs to your app, it is metadata.

electron-builder configuration it is just build configuration, not metadata.

Nevermind — now we check author in the dev metadata also :)

**Comment by develar** [comment]
You are not alone — #1881

**Comment by develar** [comment]
`publisherName` intended for code signature validation. Not as company name. As your issue is not about what to use, but misplaced author field, I am not going to think — should we use it as company name or not.

**Comment by framerate** [comment]
I think it's just a little confusing. We could fix it by updating documentation too, sure, but the idea of 99% of the time updating `/package.json` except this case where I need to update `/app/package.json` (in relation to electron builder). I would think there should be some (maybe new) config option in `/package.json` that is documented and if that doesn't exist, fall back to `/app/package.json#author` perhaps.

**Comment by develar** [comment]
Please try 19.27.6

**Comment by framerate** [comment]
> Please try 19.27.6
Ok! What i the change? Is it just falling back to /package.json#author to find a name?

**Comment by develar** [comment]
Yes, fallback to dev metadata.
