### ISSUE TITLE
Put package.json into packages

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#2028]
`package.json` contains useful metadata about the application (e.g., author, license etc.) that could be used by software centers, e.g., the [AppImageHub](https://appimage.github.io/apps/) central directory of available AppImages.

It would be useful if this file would be shipped inside packages and AppImages, along with the application.

**Comment by develar** [comment]
It is in the `resources/app.asar`  ASAR is simple — https://github.com/electron/asar

**Comment by probonopd** [comment]
Thank you!

**Comment by develar** [comment]
Please note — if asar disabled, `resources/app/package.json`

**Comment by probonopd** [comment]
Interestingly, the [file inside the AppImage](https://github.com/AppImage/appimage.github.io/commit/96ae9a7d5c0e9d5a6cd80ef8e7bc5757fc79c24d) seems to have less information than the [file on GitHub](https://github.com/develar/onshape-desktop-shell/blob/master/package.json).
I can live with it for now, but it would be neat to know the version of electron-builder that was used to generate the AppImage.

**Comment by develar** [comment]
@probonopd All sensitive information like devDependencies, electron-builder configuration, AVA, Jest and so on, are stripped. But metatada is not removed :)
