### ISSUE TITLE
Stuck at building DMG for darwin x64

### ISSUE THREAD

**Issue by AudioW** [electron-userland/electron-builder#2032]
* **19.27.3**: 

2.8.9

* **darwin x64**: 

I am attempting to build using electron-builder for darwin x64. No defaults are changed in the package.json except for the output directory and product name. The output folder and mac.zip is created and are working fine but the process seems to get stuck when creating the DMG.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by AudioW** [comment]
Log Output

Nothing happens after 7za exited with code 0

`Building DMG
  electron-builder Spawning /Users/default/app/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/default/app/release/App-1.5.0-mac.zip App.app +16s
  electron-builder cwd: /Users/default/App/release/mac +0ms
  electron-builder Spawning hdiutil create -srcfolder /private/var/folders/xv/czvkt3y14119n73jyl3j8z2r0000gn/T/electron-builder-SYT187/1-dmg/.background-srcfolder /Users/default/App/release/mac/App.app -volname App 1.5.0 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /private/var/folders/xv/czvkt3y14119n73jyl3j8z2r0000gn/T/electron-builder-SYT187/0.dmg +40ms
  electron-builder 7za (8500) exited with exit code 0 +4m`

**Comment by giridharprakash** [comment]
Hi

Anyone has solution for this?

**Comment by giridharprakash** [comment]
Building macOS zip
Building DMG
  electron-builder Spawning /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/dist/Tarzan-0.0.1-mac.zip Tarzan.app +5s
  electron-builder cwd: /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/dist/mac +0ms
  electron-builder Spawning hdiutil create -srcfolder /private/var/folders/9z/xwjdzb4d0yb34x1h20fxb5nr0000gn/T/temp-files-Vypto1/1-dmg/.background -srcfolder /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/dist/mac/Tarzan.app -volname Tarzan 0.0.1 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /private/var/folders/9z/xwjdzb4d0yb34x1h20fxb5nr0000gn/T/temp-files-Vypto1/0.dmg +20ms
  electron-builder 7za (1709) exited with exit code 0 +1m
  electron-builder Async task error: Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
  electron-builder     at new GitHubPublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-publish/src/gitHubPublisher.ts:51:15)
  electron-builder     at createPublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:324:14)
  electron-builder     at PublishManager.getOrCreatePublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:165:19)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:137:32
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at PublishManager.artifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:492:11)
  electron-builder     at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:110:69)
  electron-builder     at emitOne (events.js:120:20)
  electron-builder     at EventEmitter.emit (events.js:210:7)
  electron-builder     at Packager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:121:23)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:260:23
  electron-builder     at Generator.next (<anonymous>)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/graceful-fs/graceful-fs.js:99:16
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/graceful-fs/graceful-fs.js:43:10
  electron-builder     at FSReqWrap.oncomplete (fs.js:135:15)
  electron-builder From previous event:
  electron-builder     at writeUpdateInfo (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:144:22)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:155:34
  electron-builder From previous event:
  electron-builder     at PublishManager.artifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:492:11)
  electron-builder     at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:110:69)
  electron-builder     at emitOne (events.js:120:20)
  electron-builder     at EventEmitter.emit (events.js:210:7)
  electron-builder     at Packager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:121:23)
  electron-builder     at MacPackager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:97:15)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/targets/ArchiveTarget.ts:30:14
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at ArchiveTarget.build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/targets/ArchiveTarget.js:60:11)
  electron-builder     at taskManager.addTask.default.map.it (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:110:85)
  electron-builder From previous event:
  electron-builder     at MacPackager.packageInDistributableFormat (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:110:41)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/macPackager.ts:89:26
  electron-builder From previous event:
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/macPackager.ts:89:10
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at MacPackager.pack (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/macPackager.js:183:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:260:24
  electron-builder From previous event:
  electron-builder     at Packager.doBuild (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/packager.js:338:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:186:52
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at Packager.build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/packager.js:257:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/builder.ts:286:40
  electron-builder     at Generator.next (<anonymous>)
  electron-builder     at build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/builder.js:69:21)
  electron-builder     at loadEnv.then (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/cli/cli.ts:49:4)
  electron-builder From previous event:
  electron-builder     at build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/builder.js:69:21)
  electron-builder     at loadEnv.then (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:155:79)
  electron-builder     at runCallback (timers.js:781:20)
  electron-builder     at tryOnImmediate (timers.js:743:5)
  electron-builder     at processImmediate [as _immediateCallback] (timers.js:714:5)
  electron-builder From previous event:
  electron-builder     at Object.args [as handler] (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:155:68)
  electron-builder     at Object.self.runCommand (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/lib/command.js:233:22)
  electron-builder     at Object.Yargs.self._parseArgs (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/yargs.js:1018:24)
  electron-builder     at Object.get [as argv] (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/yargs.js:927:19)
  electron-builder     at Object.<anonymous> (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:151:418)
  electron-builder     at Module._compile (module.js:569:30)
  electron-builder     at Object.Module._extensions..js (module.js:580:10)
  electron-builder     at Module.load (module.js:503:32)
  electron-builder     at tryModuleLoad (module.js:466:12)
  electron-builder     at Function.Module._load (module.js:458:3)
  electron-builder     at Function.Module.runMain (module.js:605:10)
  electron-builder     at startup (bootstrap_node.js:158:16)
  electron-builder     at bootstrap_node.js:575:3 +28ms
  electron-builder Async task error: Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
  electron-builder     at new GitHubPublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-publish/src/gitHubPublisher.ts:51:15)
  electron-builder     at createPublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:324:14)
  electron-builder     at PublishManager.getOrCreatePublisher (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:165:19)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:137:32
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at PublishManager.artifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:492:11)
  electron-builder     at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:110:69)
  electron-builder     at emitOne (events.js:120:20)
  electron-builder     at EventEmitter.emit (events.js:210:7)
  electron-builder     at Packager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:121:23)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:306:19
  electron-builder     at Generator.next (<anonymous>)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/graceful-fs/graceful-fs.js:99:16
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/graceful-fs/graceful-fs.js:43:10
  electron-builder     at FSReqWrap.oncomplete (fs.js:135:15)
  electron-builder From previous event:
  electron-builder     at writeUpdateInfo (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:144:22)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:155:34
  electron-builder From previous event:
  electron-builder     at PublishManager.artifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/publish/PublishManager.js:492:11)
  electron-builder     at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/publish/PublishManager.ts:110:69)
  electron-builder     at emitOne (events.js:120:20)
  electron-builder     at EventEmitter.emit (events.js:210:7)
  electron-builder     at Packager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:121:23)
  electron-builder     at MacPackager.dispatchArtifactCreated (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:97:15)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/targets/ArchiveTarget.ts:30:14
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at ArchiveTarget.build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/targets/ArchiveTarget.js:60:11)
  electron-builder     at taskManager.addTask.default.map.it (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:110:85)
  electron-builder From previous event:
  electron-builder     at MacPackager.packageInDistributableFormat (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/platformPackager.ts:110:41)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/macPackager.ts:89:26
  electron-builder From previous event:
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/macPackager.ts:89:10
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at MacPackager.pack (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/macPackager.js:183:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:260:24
  electron-builder From previous event:
  electron-builder     at Packager.doBuild (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/packager.js:338:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/packager.ts:186:52
  electron-builder     at Generator.next (<anonymous>)
  electron-builder From previous event:
  electron-builder     at Packager.build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/packager.js:257:11)
  electron-builder     at /Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/builder.ts:286:40
  electron-builder     at Generator.next (<anonymous>)
  electron-builder     at build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/builder.js:69:21)
  electron-builder     at loadEnv.then (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/src/cli/cli.ts:49:4)
  electron-builder From previous event:
  electron-builder     at build (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/builder.js:69:21)
  electron-builder     at loadEnv.then (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:155:79)
  electron-builder     at runCallback (timers.js:781:20)
  electron-builder     at tryOnImmediate (timers.js:743:5)
  electron-builder     at processImmediate [as _immediateCallback] (timers.js:714:5)
  electron-builder From previous event:
  electron-builder     at Object.args [as handler] (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:155:68)
  electron-builder     at Object.self.runCommand (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/lib/command.js:233:22)
  electron-builder     at Object.Yargs.self._parseArgs (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/yargs.js:1018:24)
  electron-builder     at Object.get [as argv] (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/yargs/yargs.js:927:19)
  electron-builder     at Object.<anonymous> (/Users/giridharprakash/MyData/Projects/OneView/tarzanapp/node_modules/electron-builder/out/cli/cli.js:151:418)
  electron-builder     at Module._compile (module.js:569:30)
  electron-builder     at Object.Module._extensions..js (module.js:580:10)
  electron-builder     at Module.load (module.js:503:32)
  electron-builder     at tryModuleLoad (module.js:466:12)
  electron-builder     at Function.Module._load (module.js:458:3)
  electron-builder     at Function.Module.runMain (module.js:605:10)
  electron-builder     at startup (bootstrap_node.js:158:16)
  electron-builder     at bootstrap_node.js:575:3 +293ms

**Comment by asethwright** [comment]
Same problem on MacOS High Sierra (10.13)

**Comment by develar** [comment]
Use 19.31.1
