### ISSUE TITLE
Specify entitlements per binary

### ISSUE THREAD

**Issue by fab1an** [electron-userland/electron-builder#2035]
* **Version**: 19.27.3
* **Target**: MAS

I'm bundling an (login)helper into my app. Everything works except that the MAS-build signs the helper automatically with the following entitlements:

```
$> codesign -d --entitlements :- dist/mas/MyApp.app/Contents/Library/LoginItems/MyAppLoginHelper.app
Executable=....
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```

LoginHelpers don't work if the inherit a sandbox, so I need to get rid of the second key `com.apple.security.inherit`. I thought about supplying `entitlementsInherit`, but then Frameworks wouldn't be signed properly.

How can I patch this, just for the helper?

**Comment by develar** [comment]
I suggest you to integrate this logic into electron-builder. 

`MyAppLoginHelper.app` is suitable for any app, if I am not wrong, so, electron-builder can sign and bundled it automatically (if some option is set).

Please see https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/macPackager.ts#L161 Here we can ignore `MyAppLoginHelper.app`

**Comment by fab1an** [comment]
I don't understand. At the moment I'm copying that bundle via  `extraFiles` and electron-builder signs it. It works, only that the wrong entitlements are used.

**Comment by fab1an** [comment]
If I ignore the file, it's not signed at all…

**Comment by develar** [comment]
https://github.com/electron/electron/issues/7312#issuecomment-322718450

I suggest — send me `MyAppLoginHelper.app` and electron-builder will copy it to `Library/LoginItems` and sign correctly. You can expect feature CET evening.

**Comment by fab1an** [comment]
Agreed. I'll check whether the release on the AppStore works (local dev-build does) then I will send it to you.
I just need to figure out how to export an unsigned-app from XCode. Otherwise i'll just delete the _CodeResources folder or so.

**Comment by fab1an** [comment]
Here you are, you have to supply an appropriate appId in the Info.plist, I believe it has to be different from the main-app.

[LoginHelper.zip](https://github.com/electron-userland/electron-builder/files/1280831/LoginHelper.zip)

**Comment by fab1an** [comment]
Reach out if you need anything.

**Comment by fab1an** [comment]
@develar did you integrate this?

**Comment by fab1an** [comment]
This is now officially supported in electron, it seems.

**Comment by develar** [comment]
Yep, since electron 2.
