### ISSUE TITLE
Ubuntu 16.04: AppImage icon not shown in Launcher and in Application list

### ISSUE THREAD

**Issue by dpalou** [electron-userland/electron-builder#2040]
* **Version**: 19.27.3

* **Target**: Ubuntu 16.04

I'm using an icns file as a source for the icons (same icns used in Mac building). If I create a snap, the icon is shown as it should. However, if I create an AppImage and I run it, the icon isn't shown in the Launcher. Also, if I search my app in the list of Applications, the icon isn't shown either:

![screen shot 2017-09-06 at 09 51 02](https://user-images.githubusercontent.com/7590321/30101855-205b86fc-92ee-11e7-88b4-c977458e6344.png)

![screen shot 2017-09-06 at 09 51 26](https://user-images.githubusercontent.com/7590321/30101866-2637fa6a-92ee-11e7-97f3-bc31af118846.png)

The build process doesn't display any error. I have installed the required libraries, specially:

icnsutils graphicsmagick xz-utils snapcraft gcc-multilib g++-multilib

This is my icns file:

https://github.com/moodlehq/moodlemobile2/blob/master/resources/desktop/icon.icns

And here is my package.json (of course, I remove "target: snap" to create the AppImage):

https://github.com/moodlehq/moodlemobile2/blob/master/package.json#L137

Am I doing something wrong?

Thanks!

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/748#issuecomment-246580769

Duplicates #748

**Comment by develar** [comment]
19.28.0
