### ISSUE TITLE
How to include executible files in the installed program folder

### ISSUE THREAD

**Issue by dbolton** [electron-userland/electron-builder#2042]
* **Version**: 19.27.3

* **Target**: win32 x64

I have a third party exe file that I would like to to be able to distribute with the Electron app and call from within the Electron app. Currently I have the exe files in the development directory, but it is not appearing in the installed directory. 

My package.json includes the following section. 
```
  "files": [
    "testfile.txt",
    "Binaries/ShadowSpawn-0.2.2-x64/ShadowSpawn.exe",
    "Binaries/ShadowSpawn-0.2.2-x64/ShadowSpawn.pdb",
    "Binaries/ShadowSpawn-0.2.2-x86/ShadowSpawn.exe",
    "Binaries/ShadowSpawn-0.2.2-x86/ShadowSpawn.pdb"],
```

My hope was the exe files would appear in pathtoinstalledapp\Binaries\* (I don't see them when I navigate to the folder using Windows Explorer)

What is the best way to include exe files in the distributable?

**Comment by dbolton** [comment]
I have also tried adding the following line to package.json:
```
  "dependencies": {
    "ShadowSpawn": "file:./Binaries/ShadowSpawn-0.2.2-x64/ShadowSpawn.exe"
  },
```

**Comment by develar** [comment]
Please use extraResources or extraFiles.
