### ISSUE TITLE
7zip-bin-mac/7za: Error: spawn EACCES

### ISSUE THREAD

**Issue by krainboltgreene** [electron-userland/electron-builder#2044]
* **Version**:  19.27.7

For some reason this line 

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/packager/dirPackager.ts#L57

is crapping out with EACCES. The bin definitely exists on my harddrive at the location it's trying to see.

**Comment by krainboltgreene** [comment]
Changing the permissions of the file to 755 has "resolved" the issue

**Comment by hovancik** [comment]
Same issue here. 
@krainboltgreene what file do you mean? 7za binary?

**Comment by krainboltgreene** [comment]
Yes, that file exactly.

**Comment by develar** [comment]
Cannot believe. File permissions is ok. It was some local issue, I guess . Closed for now.

**Comment by r4zzz4k** [comment]
Nope, just updated my dependencies and got the same thing. "chmod +x node_modules/7zip-bin-linux/x64/7za" fixes it.
I'm off, unfortunately, so can't investigate right now.

**Comment by hovancik** [comment]
I have the same on 2 different macs

**Comment by jmsaavedra** [comment]
Same problem, same fix worked: `chmod +x node_modules/7zip-bin-mac/7za`

Thanks!

**Comment by krainboltgreene** [comment]
Looks like this was solved in a recent npm patch.

**Comment by blacklightpy** [comment]
> Looks like this was solved in a recent npm patch.

I don't think so
