### ISSUE TITLE
install-app-deps & electron-builder install-app-deps commands not found

### ISSUE THREAD

**Issue by harishajdarevic** [electron-userland/electron-builder#2045]
* **Version**: 19.27.7

* **Target**: Linux 64bit ( Ubuntu )

I'm installing sqlite3 in my electron project. On one thread I saw that it is good after installation to run "electron-builder install-app-deps" to install all dependencies for native node modules.

After installation of electron-builder when I run:

haris@Laptop:~/development/walter/bimobject/angular-electron-starter$ install-app-deps
install-app-deps: command not found
haris@Laptop:~/development/walter/bimobject/angular-electron-starter$ electron-builder install-app-deps
electron-builder: command not found

I'm getting results as commands not found.

What is problem?

**Comment by develar** [comment]
To invoke commands from`node_modules/.bin`, you or call it using path (but not name). or, if you use NodeJS 8, using `npx electron-builder`
