### ISSUE TITLE
After the upgrade is automatically restarted, the webview userAgent does not use the new version in package.json

### ISSUE THREAD

**Issue by randolph249** [electron-userland/electron-builder#2046]
Before the upgrade, the version number in package.json was 2.0.0. After the quitAndInstall auto restart, the version number in package.json was updated to 2.1.0 but the userAgent of webview was still 2.0.0. After manually close the APP restart,the userAgent returned to normal version(2.1.0)
Please answer this exception

**Comment by develar** [comment]
Well... please provide update logs.
