### ISSUE TITLE
FileSet doesn't work in files configuration

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-builder#2047]
I have this section in the config file:
```
    "files": [
        "assets",
        {
            "from": "custom/config.json",
            "to": "config.json"
        }
    ]
```
Building dmg gets the error below:
```
electron-builder 19.2.7
Using custom/electron-builder.json configuration file
Error: Config is invalid:
{
  "files[0]": "Should be string",
  "files": [
    "Should be null,string",
    "Invalid option object"
  ]
}
```
It builds fine without the fileset inside "files".

Many thanks!

**Comment by develar** [comment]
> 19.2.7

Too old :)

**Comment by bingqiao** [comment]
Sorry I thought I changed to the latest.

Now just tested on 19.28.1 and got a different error:

```
Error: ENOTDIR: not a directory, scandir '/Users/xxxx/custom/config.json'
    at Error (native)
From previous event:
    at /Users/xxxx/node_modules/builder-util/src/fs.ts:60:30
    at next (native)
    at walk (/Users/xxxx/node_modules/builder-util/out/fs.js:116:22)
    at /Users/xxxx/node_modules/electron-builder/src/util/AppFileCopierHelper.ts:34:25
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

It is not a directory which is correct. But does fileset only work for directory patterns?

Similar config works for extraResources.

**Comment by bingqiao** [comment]
BTW this was tested on mac

**Comment by bingqiao** [comment]
Just tested this on Windows and same error.

**Comment by bingqiao** [comment]
I managed to get one single file copied in the end using the following config but it would be easier to be able to just set the file that needs copying:

```
        {
            "from": "custom/",
            "to": "./",
            "filter": ["config.json"]
        }
```

**Comment by bingqiao** [comment]
@develar I think there is still a bug in the use of fileset of files section because "from" doesn't work if a file path is specified. At least this is not clear from the documentation. And the fileset of extraResources does allow a file path.

**Comment by develar** [comment]
Thanks, I will check.

**Comment by ravicious** [comment]
> I managed to get one single file copied in the end using the following config but it would be easier to be able to just set the file that needs copying

This is still the case in 2023. `FileSet` in `files` won't work properly unless `from` and `to` are dirs. Individual files can be controlled by the `filter` property.
