### ISSUE TITLE
Connectivity issues with nsis-web

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#2049]
* **Version**: 15.4.3

* **Target**: Windows (Nsis-Web)

![image](https://user-images.githubusercontent.com/1483171/30197611-0c3fa974-9469-11e7-9fe7-ee5e58ee8bd4.png)

I'm not sure if this was fixed in later versions, but i've had a few miscellaneous reports here and there that people are having issues download sometimes from cloudfront (AWS S3 CDN). I've seen other screenshots (I don't have atm) that show a user having issues with the download stopping like 1/3 of the way through saying it lost connection and can't continue and consistently doing this when he had no other internet issues.

Are there any known bugs with the nsis-web downloader plugins being used?

**Comment by develar** [comment]
I am not aware.

We should:

1. try 3 times before user confirmation to retry.
2. try to download without proxy.

**Comment by develar** [comment]
BTW, user now (next version will be released), can 

> Download package file into the same directory where installer located. It will be detected automatically and used instead of downloading from the Internet. Please note — only original package file is allowed (checksum is checked).

**Comment by mastergberry** [comment]
Is it possible for the download to resume if it does lose connectivity? Or not possible with the way it downloads the files.

**Comment by mastergberry** [comment]
![image](https://user-images.githubusercontent.com/1483171/30199653-f3446a4e-9473-11e7-8a64-d16b2ef316d1.png)

User said in the past he had no issues downloading the client.

**Comment by mastergberry** [comment]
https://www.youtube.com/watch?v=Pb8Uenf-Dyw

A user recorded this being an issue...I think they got it to work later, asking what they changed/how it was fixed.

**Comment by mastergberry** [comment]
User from video claims to have moved to a new house and new ISP and this was how it got fixed for him...so many some ISP's are adding proxies automatically and causing issues which is probably beyond our scope of control?

**Comment by develar** [comment]
> causing issues which is probably beyond our scope of control?

Used NSIS plugin tries to use system/explorer proxy. We can try to download without proxy.

Yes — bypassing of ISP proxy is not "possible".

I will check issue when delta updates will be implemented.

**Comment by develar** [comment]
We are going to promote web installer (since it is awesome) and this feature will be implemented in a short term.

**Comment by mastergberry** [comment]
We only use awesome features at Badlion 🏆

**Comment by develar** [comment]
Addressed in 21.1.0, but only end user can verify that is fixed.
