### ISSUE TITLE
[FEATURE REQUEST]: Add checkbox for clean uninstall.

### ISSUE THREAD

**Issue by S74nk0** [electron-userland/electron-builder#2058]
Hello, 

I think that adding a checkbox for a clean uninstall when using boring uninstaller (NSIS Windows) would be something more people might find useful. I am not sure how big of a task this might be but if it isn't a big hassle please consider adding it. If you can give me guidelines (to save time in research) on how to do this myself I would also appreciate it (and maybe make a PR if this would make sense for the project).

Regards.

**Comment by develar** [comment]
Do you mean remove app data?

**Comment by S74nk0** [comment]
Yes. This is somewhat related to #2057 .

**Comment by arsinclair** [comment]
This would require creating another [installer page](https://nsis.sourceforge.io/Docs/Chapter4.html#pages) in https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/uninstaller.nsh with a checkbox to ask the user if the preferences should be deleted. Then, if checkbox is checked, we'd just execute the same cleanup logic that already works for one-click installer - [here](https://github.com/electron-userland/electron-builder/blob/fce1a1fab66e3f5cd741a4cecc4af8377aea9dd8/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L90-L106).

This should be really simple, but I believe it's better and faster if someone familiar with the codebase does it.

**Comment by arsinclair** [comment]
Has this been implemented?

**Comment by mmaietta** [comment]
Nope. And since it's from 2017, I've closed it because it won't ever be worked on.
