### ISSUE TITLE
electron-updater NSIS isForceRunAfter = false ?

### ISSUE THREAD

**Issue by l7s** [electron-userland/electron-builder#2059]
* electron-updater v. 2.8.9
* nsis

After performing NSIS update I would expect the app to automatically restart, however this doesn't happen. Seems to me the problem is [in this line](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L147) which should read `this.install(true, true)` instead of `this.install(true, false)` to set `isForceRunAfter` to `true`.

**Comment by develar** [comment]
We follow and recommend Electron team implementation — app silently updated on quit. And next time when user use app, it is already updated. 

Mentioned flags allows you to not follow recommendations and implementat your custom way of updating.
