### ISSUE TITLE
Clarification/question regarding autoupdate for .exe - NSIS - S3

### ISSUE THREAD

**Issue by myfrndjk** [electron-userland/electron-builder#2060]
Hi,

Previously I was using default electron auto-upate and Squirrel windows.
I tried  NSIS 

```
      "publish": {
        "provider": "s3",
        "bucket": "autoupdate",
        "path": "https://s3-us-west-2.amazonaws.com/autoupdate/"
      }
```

clarifications:
Is it mandatory to have credentials because I cant use credentials in code so I made changes in S3 bucket so only few IPs can access that.

If credentials are mandatory I can handle publish part manually,
**What are all the artifacts** I have to move to `https://s3-us-west-2.amazonaws.com/autoupdate/`

I searched various threads unfortunately cant find what are all the artifacts to be moved to autoupdate, in NSIS  it is creating only latest.yml and bla.exe and some file in resource folder. 

I tried to set that `https://s3-us-west-2.amazonaws.com/autoupdate/` as generic server this time it printed message as `published to null`

I just want to update my app from this location https://s3-us-west-2.amazonaws.com/autoupdate/ without access key/credentials.What will be the best approach.

Ps: squirrel is exactly doing above work but some where in doc it is mentioned as depricated.
So planning to move to NSIS

Thanks
Jk

**Comment by myfrndjk** [comment]
We need to put file.exe and latest.yml in S3 update folder
resolving the issue since it is fixed

**Comment by develar** [comment]
I am so sorry. Totally missed this ticket.

**Comment by develar** [comment]
If you still have some questions — feel free to ask.

**Comment by myfrndjk** [comment]
@develar : No issues :) Thanks for your response :) Will bug you if I stuck some where.

**Comment by VerteDinde** [comment]
@myfrndjk Sorry to bug you on a closed issue, but did you have to manually add the .yml file to your S3 bucket? I'm using AppVeyor and wondered if we could automate the creation.

**Comment by develar** [comment]
@VerteDinde just configure s3 provider and will be uploaded automatically. https://www.electron.build/configuration/publish

**Comment by myfrndjk** [comment]
@VerteDinde : Hi as @develar mentioned it is automated process if you can use access and secret key of your aws account  then in your terminal add 

```
$ export AWS_ACCESS_KEY_ID=youraccesskey
$ export AWS_SECRET_ACCESS_KEY=yoursecretkey
```
for some reasons if you cant use access key/secrety or aws certificate then you have to manually move file.exe and latest.yml manually into that respective s3 folder 

Thanks
Jk

**Comment by VerteDinde** [comment]
Thanks @myfrndjk ! I see - and were you able to set your `feedUrl` to a custom url to read the update differences, or is done through the SHA differences in the latest.yml file?

**Comment by myfrndjk** [comment]
I am doing it using automated process so I dont have to set feed url manually.
It will automatically taken from package.json

```
"publish": {
  "provider": "s3",
  "bucket": "bucket-name"
}
```
