### ISSUE TITLE
Windows AppStore Certification Problem

### ISSUE THREAD

**Issue by markusmoenig** [electron-userland/electron-builder#2061]
After getting my app successfully into the Mac AppStore I am now working on the Windows AppStore.

The first errors reported by the Windows App Certification Kit are inside the App manifest resources tests:

Image reference "assets\Square150x150Logo.png": The image "assets\Square150x150Logo.png" failed the size restrictions of 150 X 150.
Image reference "assets\Wide310x150Logo.png": The image "assets\Wide310x150Logo.png" failed the size restrictions of 310 X 150.

Initial internet searches did not show anything. Any ideas ?

**Comment by develar** [comment]
Cc @black-snow

**Comment by black-snow** [comment]
@markusmoenig Hi and thanks for contributing.

Sounds like your 150x150 Logo isn't 150x150 ... have you checked them?

**Comment by markusmoenig** [comment]
@black-snow Which logo ? :) Sorry, I seem to have missed something in the documentation. These two logos, what do they represent and how do I have to embed them in the package.json ? Are they Windows AppStore specific ? Maybe you can give me a link to the docu for this ?

**Comment by black-snow** [comment]
There you go: https://www.electron.build/icons#appx

**Comment by markusmoenig** [comment]
@black-snow Thanks! Totally missed this!

**Comment by black-snow** [comment]
You're welcome. If there's anything to improve please let us know.

**Comment by markusmoenig** [comment]
I will let you know how the process to get in the AppStore is going....

Biggest obstacle seem to be the new Windows 10 S restrictions which are a problem in Electron itself: https://github.com/electron/electron/issues/10493

**Comment by markusmoenig** [comment]
@black-snow Another question, if we provide the appx splash screen asset, it means that we should not manually show the splash screen ourselves again in main.js as Windows is doing it for us ?

**Comment by black-snow** [comment]
@markusmoenig I've no experience with that - I think I don't have an splash screen image in my app. Guess you'll have to test it out.
However, I think that windows will only show the splash screen until the electron runtime is somehow ready. But that might not be the time your app is actually ready. So it still might be useful to show your own splash until you're fully functional.

**Comment by markusmoenig** [comment]
@black-snow Ok, thanks. The Windows guide lists several splash screen sizes, I guess when I place them in the appx folder electron-builder will include all of these in the build (like the different icons) right ? Just asking because on the icon page only one splashscreen.png is listed.

**Comment by black-snow** [comment]
Dunno. I used to create resource files manually.

> By using a resource reference, you can supply images of different scales so that Windows can choose the best size for the device and screen resolution. You can also supply high contrast images for accessibility and localized images to match different UI languages.

@develar I can't remember if electron-builder got support for pri files etc.

**Comment by develar** [comment]
@surajreddy could you please comment about pri files?

**Comment by surajreddy** [comment]
@black-snow @markusmoenig currently builder will generate a pri file if you have scaled assets, as a pri file is needed to support scaled assets.

Here is the code that does it: https://github.com/electron-userland/electron-builder/pull/1657/files#diff-50432ba8f11abf70bd46546e0c4d42e5R87

**Comment by black-snow** [comment]
Awesome. So you can add different sizes (see naming rules) and Windows will choose the right one @markusmoenig

**Comment by markusmoenig** [comment]
@surajreddy @black-snow Great! Thanks a lot for the help guys!

**Comment by markusmoenig** [comment]
@develar @black-snow @surajreddy Just to give some feedback. Windows certification for the AppStore seems to fail because of https://github.com/electron/electron/issues/10551.

This would mean that all Electron apps who use WebGL cannot get into the AppStore currently :(

**Comment by black-snow** [comment]
That might actually be the case. *IMHO* MS fucked up. I'm on the dev newsletters and didn't receive sh** about those *policy updates* + it's a crazy decision that ALL store apps MUST support Windows S and thus cannot use 99% of the windows features anymore ...

**Comment by mplogas** [comment]
@black-snow easy here. We have our store policies publicy available out [here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare). 

@markusmoenig I think you misunderstood my mail, but let's continue it in our mailthread.

**Comment by black-snow** [comment]
@mplogas Sorry for being outrageous. Isn't it nuts to just make such a huge change (for electron devs at least) without letting us know somehow or (preactively) helping us? Feels like a middlefinger to me which is weird for MS support was pretty great so far.
Or have I missed the announcement? Of course I'm not scanning the policies for updates periodically.

**Comment by markusmoenig** [comment]
@mplogas Yes. We are mixing two issues here. The WebGL issue is resolved.

**Comment by markusmoenig** [comment]
@black-snow Sorry for the confusion. I panicked a bit about the WebGL issue which has been resolved now. So things got a bit mixed up.

**Comment by black-snow** [comment]
@markusmoenig Everything's fine :) Glad your issue has been resolved. 👍 
The only thing I'm confused about is the whole Windows S / Win Store thing ...

**Comment by mplogas** [comment]
@black-snow since Electron apps aren't really affected by the Windows10 S change, I don't see anyone here @Microsoft giving you the the middle-finger. 
Our job as AppConsults is to help developers through the repackaging and publishing process. We dedicate a lot of our time in finding those issues, work around it or have policies adapted. So please be constructive and point out blocking issues so I can make the store team aware of this.
