### ISSUE TITLE
Old icons cached? - New icons are not consistently used across

### ISSUE THREAD

**Issue by distributev** [electron-userland/electron-builder#2062]
* **Version**:  "electron-builder": "^19.27.1",

* **Target**: build -w --ia32 (Windows 10 64bit)

It seems the same (or similar) issue was raised here - https://github.com/electron-userland/electron-builder/issues/840

I changed all the icons with new icons I regenerate the exe file 3 or 4 times but the old icon (even if meanwhile I re-generated 3 or 4 times with 4 different icons) still show next the my App.exe in Windows Explorer. When I double click and launch the app the correct / new icon is showing in task manager.

Here is a screen-shot

![wrong-icon](https://user-images.githubusercontent.com/19224635/30317067-56c61260-97a9-11e7-9ad7-a8fce481e354.png)

**Comment by develar** [comment]
Do you use installer to install app and launch or run it directly?

Just restart Windows.

**Comment by distributev** [comment]
I run the app directly. I have no intention to create an installer I want to create a self contained app.

I restarted Windows and the behavior is the same I see the old icon near the App.exe and the new icon when the app is started and it's in the task-bar.

Do you have an idea why the old icon is still being used?

**Comment by develar** [comment]
Consider to use portable target if you want self-contained app.

**Comment by distributev** [comment]
I already doing that - this is an extract from package.json

  "win": {
      "artifactName": "${productName}.${ext}",
      "target": [
        "portable"
      ]
    }

Can this be related with the cached icons?

**Comment by develar** [comment]
Do you mean that on desktop do you see old icon of portable executable?

**Comment by distributev** [comment]
Yes the PortableApp.exe shows the old icon in Windows Explorer.

If I double click and launch the new (correct) icon is coming in Taskbar.

**Comment by develar** [comment]
Possible Solution — portable should refresh desktop on launch.

**Comment by distributev** [comment]
I don't understand what you want to say here. I launched the exe many times and Windows Explorer icon does not change (refresh) - the old icon will remain.  Windows was restarted also.

**Comment by dharders** [comment]
Ahhh the old windows icon cache issue. I've dealt with this before. From memory I used a combination of these hacks:

[http://www.winhelponline.com/blog/refresh-icon-cache-windows-7-quickly/](http://www.winhelponline.com/blog/refresh-icon-cache-windows-7-quickly/) 
[http://nsis.sourceforge.net/Refresh_shell_icons](http://nsis.sourceforge.net/Refresh_shell_icons)
[https://stackoverflow.com/questions/3243317/make-windows-refresh-icon-cache](https://stackoverflow.com/questions/3243317/make-windows-refresh-icon-cache)

I agree, Windows is a pain ;)

**Comment by andyb1979** [comment]
I discovered today Electron (or Windows) is caching the icon based on app ID. 

In my electron app I set app ID here
```
app.setAppUserModelId('com.myco.myappname');
```

If I changed that app ID when I changed the icon, the cached icon went away

**Comment by Smileyprog** [comment]
> I discovered today Electron (or Windows) is caching the icon based on app ID.
> 
> In my electron app I set app ID here
> 
> ```
> app.setAppUserModelId('com.myco.myappname');
> ```
> 
> If I changed that app ID when I changed the icon, the cached icon went away

My hero!
