### ISSUE TITLE
How to use afterInstall

### ISSUE THREAD

**Issue by hobbyquaker** [electron-userland/electron-builder#2065]
* **Version**: latest

* **Target**: deb, rpm, dmg

An electron project I'm working on does use node-hid and I want to create a udev rule file to so unprivileged users can use the usb device - but I have no clue how to do that. 
* Can it be done by using `afterInstall`? 
* Do I have to configure that in package.json? Can it be configured only for deb and rpm targets and not for dmg and .tar.gz? 
* Can I just put a shell command in there like `echo "therules..." > /etc/udev/rules.d/99-mydevice-hid.rules`?

**Comment by develar** [comment]
afterInstall option is allowed and applies only FPM targets — e.g. For rpm and deb. Please create file like https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/linux/after-install.tpl somewhere in the project and set option to relative to project root path.

**Comment by develar** [comment]
Please note — you need to duplicate option in both deb and rpm option and objects (e.g deb: `{ afterInstall: ... }`)

**Comment by hobbyquaker** [comment]
Thank you!
