### ISSUE TITLE
Updating increases app size (macOS)

### ISSUE THREAD

**Issue by ivandroid** [electron-userland/electron-builder#2067]
Updating **electron-builde**r from **16.8.4** to **19.27.3** increases the app size from **50** to **100 MB**. Any idea why?

**Comment by develar** [comment]
Please compare output of `asar list app.asar`

**Comment by ivandroid** [comment]
I cannot find any .asar files in my built mas archive.

**Comment by develar** [comment]
Should be app.asar if you don't disable asar packaging.

**Comment by ivandroid** [comment]
The app.asar file size increases from 23.5 (16.8.4) MByte to 130 Mbyte (19.33.0).

**Comment by develar** [comment]
Please compare output of `npx asar list app.asar`

**Comment by ivandroid** [comment]
OK, the problem was solved. Since the dist directory was in the files array, it was included into the build package. After removing the dist directory from the files array the app size doesn't increase anymore. However electron-builder 16.8.4 excluded the dist directory from the files array by default. 

Thank you for your help.

**Comment by develar** [comment]
Did you set custom output dir?
