### ISSUE TITLE
Changing local file dynamically once packaged?

### ISSUE THREAD

**Issue by Zeedinstein** [electron-userland/electron-builder#2070]
* **Version**: 19.27.7

* **Target**: NSIS

Hi, I'm trying to use node-json-db with my electron application.
This works fine in development. But when I package it with electron-builder it doesn't allow changes to the local json file that is being used as a local database for the app. So if I change a setting it doesn't actually write to file. 

Is this because of how electron-builder packages the files? Is there a way around it?

**Comment by develar** [comment]
You must not write to app installation dir. Use API app.getPath userData to get path to use data dir.
