### ISSUE TITLE
The built exe file is using Electron's Icon

### ISSUE THREAD

**Issue by aprilmintacpineda** [electron-userland/electron-builder#2071]
- electron-builder@19.27.7
- target: windows using nsis

I have an `icon.ico` file on my `build directory` but when I build the app the `icon` of the `exe` file that was built on the `unpacked` folder is using electron's icon and not the icon I specified, the rest are good, the icon of the app when it runs is using my icon, the installer is also using my icon (I'm not sure about the uninstaller, I have not tried it out), but the `application.exe` is still using electron's icon.

###### build configuration
```js
"build": {
  "nsis": {
    "oneClick": false,
    "perMachine": true,
    "allowElevation": true,
    "allowToChangeInstallationDirectory": true,
    "deleteAppDataOnUninstall": true,
    "createDesktopShortcut": true,
    "installerIcon": "build/icon.ico",
    "uninstallerIcon": "build/icon.ico",
    "uninstallDisplayName": "Uninstall LIMS",
    "license": "EULA"
  },
  "win":{
    "target": "nsis",
    "icon": "build/icon.ico",
    "publisherName": "April Mintac Pineda"
  },
  "appId": "com.aprilmintacpineda.lims",
  "productName": "Lending Information Management System (LIMS)",
  "buildVersion": "1.0.86.7",
  "copyright": "April Mintac Pineda 2017",
  "files": [
    "app/**/*",
    "models/**/*"
  ],
  "extraFiles": [
    "database/main.sqlite"
  ]
},
```

**Comment by aprilmintacpineda** [comment]
PS, the `icon.ico` is `256x256`.

**Comment by develar** [comment]
Try to restart Windows :(

**Comment by aprilmintacpineda** [comment]
Today, started my PC and fixed a few `bugs` in my app, then I built it with `electron-builder` and all of a sudden, like magic, the `EXE` is now using the `app icon` I have specified. All is well about the icon for now. Can someone explain what happened though?

**Comment by develar** [comment]
Bloody Windows.

Our NSIS installer does desktop icons refresh.

**Comment by develar** [comment]
In case of macOS we specially update timestamp of file, maybe we should do it for Windows (but it should be not required since we modify file in any case).
