### ISSUE TITLE
cannot find information about electron-updater v1.9.3 

### ISSUE THREAD

**Issue by SJ-AW** [electron-userland/electron-builder#2073]
Hi everyone,

* electron-builder: 19.27.3
* Npm version: 4.6.1

I am a little bit confused about electron-updater.
When I update my package.json with npm, It find v2.9.3. But on npm the latest version is v2.8.9 (cf. https://www.npmjs.com/package/electron-updater).
And when I try to find the change log, nothing about v1.9.3 (cf. https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/CHANGELOG.md).
So my questions are:
* Where can I find the change log about v1.9.3?
* May I used electron-updater alone or I have to use electron-builder? (I created a module in which one I use electron-updater and I use this module in another project where I have installed electron-builder)

**Comment by develar** [comment]
1.9.3 tagged as next. differential update supported — https://github.com/electron-userland/electron-builder/releases/tag/v19.28.4

Yes, electron-updater can be used standalone and doesn't depend on electron-builder.

**Comment by SJ-AW** [comment]
Hi,
Maybe I was not clear enough, how can we deduce electron-updater's version from electron-builder's one on https://github.com/electron-userland/electron-builder?
I cannot see any tag, release or changelog showing where the v2.9.3 is.
And where can we find informations about every past version of electron-updater?
Here https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/CHANGELOG.md, they are just the changelog of 2.8.8 and 2.89.

Thanks again

**Comment by develar** [comment]
Because of such requests, we started to write separate changelog for electron-updater. Sorry, that next release was not reflected in the changelog yet.

**Comment by SJ-AW** [comment]
Thank you for the answer develar, you and the other contributors make a great job with electron-builder, it's a pleasure to use it.
