### ISSUE TITLE
NSIS script Update PATH ENV variable

### ISSUE THREAD

**Issue by jegj** [electron-userland/electron-builder#2075]
im trying to update the PATH env variable with a customize installer. i'm using  **EnvVarUpdate** method.
http://nsis.sourceforge.net/Path_Manipulation

But always i got :  **Invalid comand EnvVarUpdate**

This is part of my config  file : 
```js
"nsis": {
  "include": "build/installer.nsh"
},
"win": {
  "target": "nsis"
}
```

**Comment by develar** [comment]
> !include "EnvVarUpdate.nsh" #download http://nsis.sourceforge.net/mediawiki/images/a/ad/EnvVarUpdate.7z
 
Have you copied downloaded EnvVarUpdate.nsh to build?
