### ISSUE TITLE
Website certificate

### ISSUE THREAD

**Issue by giokara** [electron-userland/electron-builder#2080]
Hi,

Currently the website https://electron.build is not available due to a missing certificate. Is it possible to fix this so the documentation of the package becomes available again?

Thanks!

**Comment by develar** [comment]
Works for me. Are you from Russia or China?

**Comment by develar** [comment]
Ok, chrome shows that connection is not fully trusted. I will check. For now it works for in the safari and chrome.

**Comment by develar** [comment]
It will be fixed 22 September.

**Comment by giokara** [comment]
No, but we are working behind a firewall.
Tested in the meanwhile with VPN connection and website works perfectly fine, sorry!

**Comment by develar** [comment]
Reopened — chrome report as not fully secure.
