### ISSUE TITLE
Is it possible to configure s3 provider to work with private artifacts?

### ISSUE THREAD

**Issue by limoragni** [electron-userland/electron-builder#2081]
Congrats on your amazing work on this repo! 

For our use case is not possible to have the artifacts publicly available on s3. Is there a way of setting credentials on the autoUpdater requests? 

Thanks!

**Comment by develar** [comment]
Yes. You can set requestHeaders property of autoUpdater to map name to value.

**Comment by develar** [comment]
Property documented on https://www.electron.build/auto-update but not detailed. I will improve docs.

**Comment by limoragni** [comment]
Thanks for the quick response! Ok, I'll try setting the headers with that option.

**Comment by develar** [comment]
Example to improve docs is welcome:)
