### ISSUE TITLE
certificate regex check the "subject  CN="  sub string doing so harsh.

### ISSUE THREAD

**Issue by QTGate** [electron-userland/electron-builder#2082]
https://github.com/electron-userland/electron-builder/blob/31d64f8b23b713754bdf615f62b2d4ff1a4cd46e/packages/electron-builder/src/winPackager.ts#L390

Hello,

My certificate subject have string that is not end with CN=(xxxxx).
It looks have a lot of information string in the subject line like /C= /OU= /O= ...
I saw your winPackager.js have regex match it looks need a /CN=() string be the end of the line.
```js
const match = result.match(/^subject.*\/CN=([^\/]+)$/m);
```
I changed it then I got perfect running.
```js
// const match = result.match(/^subject.*\/CN=([^\/]+)$/m);
const match = result.match(/^subject.*\/CN=([^\/]+)/m);
```
Thanks!

Peter
That code looks can't pass all certificate

**Comment by develar** [comment]
Fix will be applied 22 September.
