### ISSUE TITLE
database sqlite migrations?

### ISSUE THREAD

**Issue by aprilmintacpineda** [electron-userland/electron-builder#2083]
- Version: electron-builder@19.27.7
- Target: windows using NSIS

###### Using
- sequelize@4.2.0

On the process of installing, is it possible to tell the installer to:
- Create a sqlite database called `my_db.sqlite` on the path `userData` path.
- run migrations that will create database tables for `my_db.sqlite`.

**Comment by develar** [comment]
Yes, please see Custom nsis script — https://www.electron.build/configuration/nsis

But I recommend you to do it on app launch. E.g. Check some meta file is migration required or not.

**Comment by iashraful** [comment]
@aprilmintacpineda Have you successfully done the migration. If Yes? please help me to do this.
