### ISSUE TITLE
Allow NSIS Installer greater than 2Gb

### ISSUE THREAD

**Issue by anthonybriand** [electron-userland/electron-builder#2086]
* **Version**: 19.27.3

* **Target**: Win64-NSIS

Hello,

I am developing an application whose embedded data are 2.7Gb, the problem is that NSIS contains a default limit of 2Gb.

Do you have the possibility to integrate a system like http://nsis.sourceforge.net/Multi-volume_Distribution or http://nsis.sourceforge.net/WimImage_plug-in into the NSIS installer?

**Comment by develar** [comment]
Is it ok if installer will be only x64?

**Comment by develar** [comment]
Also, it is already supported in the next tagged release. Just set target to nsis-web and distribute created 7z package files as part of distribution (if package file doesn't exist on install time — it will be downloaded from internet).

**Comment by jyotigupta007** [comment]
Is it resolved we are facing same issue?

**Comment by colin-guyon** [comment]
Same here, we also have this issue... Did someone found how to embed more than 2GB of data, or do you have any advice?
