### ISSUE TITLE
Option to add extra files to the root of dmg

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-builder#2087]
* **19.28.4**: 
* **MacOS**: 

At the moment the dmg created by electron-builder only has the electron app included. It would be useful to allow extra files or directories to be added to the dmg.

In the code below from `electron-builder/packages/electron-builder/src/targets/dmg.ts`:
```
    await spawn("hdiutil", addVerboseIfNeed(["create",
      "-srcfolder", backgroundDir,
      "-srcfolder", appPath,
      "-volname", volumeName,
      "-anyowners", "-nospotlight", "-fs", "HFS+", "-fsargs", "-c c=64,a=16,e=16",
      "-format", "UDRW",
    ]).concat(tempDmg))
```
There could be another -srcfolder (or many other) to allow an extra file or directory to be included in the dmg.

One of reasons to include extra files is to have all eula/license files for different languages and regions included. The license feature of dmg doesn't work for multiple licenses in same language but different regions.

Thanks

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/pull/2064

Will be released 22 September.
