### ISSUE TITLE
Question about program version ?

### ISSUE THREAD

**Issue by doomtr666** [electron-userland/electron-builder#2088]
Hi,
I notice that when I specify version 1.2.3 in package.json, and buildVersion 4.5.6 in build.json, the final file version of the electron executable once the package is installed is something like "1.2.3.4.5.6", which seems to be the concatenation of the 2 versions. I wonder why it is the case ?

* **Version**: 19.27.7
* **Target**: NSIS

**Comment by develar** [comment]
Because buildVersion it is build number.

**Comment by develar** [comment]
Hmm... contradicts to the docs.

**Comment by doomtr666** [comment]
Thanks !
