### ISSUE TITLE
how to change latest.yml version value

### ISSUE THREAD

**Issue by liseen315** [electron-userland/electron-builder#2091]
* **Version**: 19.28.4

electron updater version: 2.8.9

* **Target**: nsis

`version: 0.3.0
releaseDate: '2017-09-18T12:40:55.580Z'
path: HIPOS_TEST-Setup-0.3.0.exe
sha512: >-
  q2XMypCVpCp1nBrJWYnqolK/jbIACL4jm+i1FwRSOUFVc7jCbuAvrjFdwN97WaK2OXZ4C1tiLL2bnPTrCI5dIA==
githubArtifactName: HIPOS-Setup-0.3.0.exe
sha2: 8a4b96ac7779dbba876ad074be8b168664deb68e94074ad21426081ba8792703`

i want to change version value in  latest.yml ,i know this value is read from package.json,but i want defined other version value ,example version_test ,what should i do ? thank you !

**Comment by develar** [comment]
You can use `extraMetadata` to set another app version for build.
