### ISSUE TITLE
Install without Start Menu Link and Shortcut

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2093]
How can I remove the Start Menu link ?
I know that I can use `createDesktopShortcut` to `false` to remove the shortcut, but it don't remove the menu link and I can't find anything in the docs.

**Comment by develar** [comment]
Could you please describe use case? May be you want portable target?

**Comment by marceloavf** [comment]
I want to install it normally, but I don't want the user looking for it on window search

![image](https://user-images.githubusercontent.com/5435657/30559621-9ca3cf8e-9c8b-11e7-841c-addb80afa1da.png)

And also the start menu link:

![image](https://user-images.githubusercontent.com/5435657/30559648-b43044a2-9c8b-11e7-9c90-55f27ecbe35f.png)

**Comment by develar** [comment]
Will be implemented 22 September.
