### ISSUE TITLE
How to open a welcome webpage after exe install successfully

### ISSUE THREAD

**Issue by pageborn** [electron-userland/electron-builder#2097]
Who can help me, give me some suggestions, thank you very much!

**Comment by marceloavf** [comment]
You can do with this approach:

First of all, you'll need to let `runAfterFinish` option equal `true` in your `nsis` option inside **package.json** (if you are using it).

Then, you can open the same `BrowserWindow` that you would open as normal, but use the [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) property inside  your webpage to know if it's the first open*.

1. `localStorage.getItem("firstOpen")` exists ? if not, then it's user first opening
2. after that, localStorage.setItem('firstOpen', true) - set firstOpen to true

With this option, you can call a welcome page inside of it or use [IPC](https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md) to open a new `BrowserWindow` for you.

---

_* If user install your app again or an update, the localStorage option will continue there._

**Comment by pageborn** [comment]
@marceloavf  Get it,  thank you.
