### ISSUE TITLE
Linux icon not showing 

### ISSUE THREAD

**Issue by gengjiawen** [electron-userland/electron-builder#2098]
```
"electron-builder": "19.27.7"
```
Related issue: https://github.com/gengjiawen/desktop/issues/14.
Repro repo: https://github.com/gengjiawen/desktop.

On my Ubuntu 16.04, the issue also exists (using AppImage https://github.com/gengjiawen/desktop/releases), it this a bug or Do i miss something ? Thanks.

![image](https://user-images.githubusercontent.com/3759816/30652743-ba6bf146-9e5b-11e7-8cdc-ce25c9dce49d.png)

**Comment by mmouterde** [comment]
I lost icon in Ubuntu 16.04 too.
My electron-builder configuration and version did not changed.

**Comment by ashokgelal** [comment]
I can confirm this bug.
"electron": "^1.7.8",
 "electron-builder": "^19.33.0",

**Comment by develar** [comment]
Is it still an issue?

**Comment by gengjiawen** [comment]
Yes, it still exist.

**Comment by Molunerfinn** [comment]
@gengjiawen Set the `icon` option to the `BrowserWindow` will fix this problem.
![image](https://user-images.githubusercontent.com/12621342/41884687-09ca46c4-7927-11e8-9cc7-00a939e25405.png)

**Comment by gengjiawen** [comment]
@Molunerfinn Thanks, I will take a look.
