### ISSUE TITLE
Enable sandbox mode 

### ISSUE THREAD

**Issue by posix4e** [electron-userland/electron-builder#2100]
The newest

* **Version**: 
Of course!     "electron-builder": "^19.28.4",

There's discussion at https://forum.snapcraft.io/t/snappy-and-users-and-groups-obsolete/331 on how to enable the snaps to access the sandbox which we need at brave
This allows things like  browsers to use user namespaces in its sandbox <snapd-interface> <Snappy:Fix Released by jdstrand> <https://launchpad.net/bugs/1586547>
 see https://github.com/snapcore/snapd/wiki/Interfaces#browser-support or  use 'allow-sandbox: true'. 

So the TLDR is we want both of them activated, enable-sandbox and browser-support, but not turned on by default
Major browser manufacturers may want to use.... Use of 'allow-sandbox' will require permission for distro in the public Snap Store at this time

**Comment by develar** [comment]
Now you can use object with attributes instead of just plug name.

```
"browser-sandbox": {
  "interface": "browser-support",
  "allow-sandbox": true
}
```
