### ISSUE TITLE
DigitalOcean Spaces support

### ISSUE THREAD

**Issue by ashokgelal** [electron-userland/electron-builder#2101]
* **Version**: 
electron-builder: 19.27.7
electron-updater: 2.8.9

* **Target**: 
macOS

This is more of a minor feature request than a bug report.

DigitalOcean today announced public availability of their new service - [Spaces](https://www.digitalocean.com/community/tutorials/an-introduction-to-digitalocean-spaces#feature-requests) - think of it as like AWS S3 but from DigitalOcean. One of the nice things about Spaces is that, just like with every DigitalOcean products, the UI is simple to use and easy to navigate through even for a newbie. And the best part is that [Spaces API is fully compatible with S3 and including aws-sdk](https://www.digitalocean.com/community/questions/has-anyone-used-aws-sdk-to-operate-on-do-spaces-how-to-do-it). Now, if `electron-publisher-s3` allowed to pass the endpoint as an option, just like for bucket, region etc, we could use Spaces without further customization and would open more options and make our lives even easier. Thank you.

**Comment by ashokgelal** [comment]
With some tinkering I was able to publish artifacts to Spaces but couldn't figure out how to configure download. I get ACCESS DENIED even after hard coding s3Url in publishOptions.ts file

**Comment by develar** [comment]
19.30.0

**Comment by ashokgelal** [comment]
Wow, that was quick! Thank you!

**Comment by develar** [comment]
I just was impressed. DO simply rocks (opposite to Bintray). Of course, S3 is cheaper for me than DO (no need to pay 5 euro upfront), but I think for commercial companies it is cheaper than S3.

**Comment by develar** [comment]
One note — for now you are forced to specify region — maybe in the future region will be computed automatically (as we do for S3).

**Comment by ashokgelal** [comment]
I use DO because it's just simple to manage and use and I could ask anyone to do DO related tasks for me (such as an intern) without a AWS training. It's worth more than $5 per month to be honest.

As far as specifying the region goes, it's okay. It will be sometime before DO supports other regions anyway. I will remember to open an issue when they do. Thanks again!

**Comment by develar** [comment]
Do not forget to update to electron-updater 2.10.0 also (DO support).

**Comment by ashokgelal** [comment]
Just tried this and unfortunately it's not working :( I get a configuration is invalid error as soon as I run `yarn release`. This is what my packages.config looks like:

```
"scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder",
    "release": "build",
...
},
"build": {
    "productName": "foobar",
    "appId": "com.foobarr",
    "directories": {
      "output": "build"
    },
    "publish": [
      {
        "provider": "spaces",
        "name": "myspacesname",
        "region": "nyc3"
      }
    ],

    "electron-updater": "^2.10.0",
    "electron-builder": "^19.30.0",
```

When I change it back to s3, it doesn't spit the error.

**Comment by develar** [comment]
Reproduced, additional test (schema) added.

**Comment by develar** [comment]
Please try 19.30.1

**Comment by ashokgelal** [comment]
I don't see 19.30.1 tagged.

**Comment by ashokgelal** [comment]
Never mind. Just got it!

**Comment by ashokgelal** [comment]
Still no luck:
```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: Please set env DO_KEY_ID (see https://www.electron.build/configuration/publish#spacesoptions)
    at SpacesPublisher.createClientConfiguration (/~/node_modules/electron-publisher-s3/src/spacesPublisher.ts:37:13)
    at ~/node_modules/electron-publisher-s3/src/basePublisher.ts:50:47
    at Generator.next (<anonymous>)
    at ~/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
```
I've already set environment variables `DO_KEY_ID` and `DO_SECRET_KEY`

**Comment by develar** [comment]
Code looks correct. Please ensure that env is set. How did you set it?

**Comment by ashokgelal** [comment]
Using export from terminal as well as setting the variables in my .zshrc
file.

**Comment by develar** [comment]
Well... please try to modify /~/node_modules/electron-publisher-s3/src/spacesPublisher.js `createClientConfiguration` to print current envs: `console.log(JSON.stringify(process.env, null, 2))`

**Comment by ashokgelal** [comment]
Ok. I will try it and let you know.

**Comment by develar** [comment]
Do you use Docker?

**Comment by ashokgelal** [comment]
No, I don't use Docker. But anyway, `rm -rf node_modules` && npm install seems to have done the trick ¯\\_(ツ)_/¯. It's working now. Thanks for your help and everything you do for electron

**Comment by bahadirdogru** [comment]
is there any full example package json with publish, auto update, digitalocean support?

**Comment by natearmagost** [comment]
@bahadirdogru 

I just got something working with:
```
    "electron": "^6.0.10",
    "electron-builder": "^21.2.0"
    "electron-updater": "^4.1.2"
```

https://github.com/natearmagost/electron-updater-digitalocean-example
