### ISSUE TITLE
Failed to Find Electron v1.8.0

### ISSUE THREAD

**Issue by iklemm** [electron-userland/electron-builder#2104]
* **Version**:  Latest Version ( by "yarn add electron-builder" )

* **Target**:  Windows x64

I followed instructions and run "yarn dist" yielding:

"electron builder Error: Failed to find Electron v1.8.0 for win32-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-win32-x64.zip"

obviously v.1.8.0 is not available and has been moved from github.

**Comment by iklemm** [comment]
Btw:  I did not declare to use v.1.8.0

Snippet of my package.json:

"devDependencies": {
    "electron": "^1.7.6",
    "electron-builder": "^19.27.7"
  },

**Comment by weicracker** [comment]
I have also encountered the same problem.

![image](https://user-images.githubusercontent.com/19145072/30735141-7b86c040-9fb0-11e7-81ce-47db77327c91.png)

**Comment by develar** [comment]
I guess problem is that your node modules contained electron 1.8.0 Please change 

> "electron": "^1.7.6",

to

```
"electron": "~1.7.6",
```

and run `yarn` to update node_modules.

Recommended to not use ^ for electron version (or even ~) to be sure that tested and proven electron version is used for your app..
