### ISSUE TITLE
Auto launch via .pkg on Mac

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2105]
* **Version**: 
17.1.2

* **Target**: 
.pkg

How do I auto launch the app after successful installation from .pkg format?

**Comment by develar** [comment]
Using scripts  — https://www.electron.build/configuration/pkg#PkgOptions-scripts

**Comment by Ajeey** [comment]
@develar I did try that but seems like the scripts are not being added.
Found this comment in the `pkg.js` file -
```
// to use --scripts, we must build .app bundle separately using pkgbuild
// productbuild --scripts doesn't work (because scripts in this case not added to our package)
// https://github.com/electron-userland/electron-osx-sign/issues/96#issuecomment-274986942
```
