### ISSUE TITLE
Possible to delegate code signing

### ISSUE THREAD

**Issue by bhalbright** [electron-userland/electron-builder#2106]
* **Version**: 19.27.7

* **Target**: nsis (I'm not specifying arch)

Hello, I only started using electron-builder yesterday and was amazed how easy to get going. But I do have a question about code signing. At my organization we have a signing "service" of sorts where I http post a binary and get the signed binary back. Is there some programmatic hook or something I could use to be able to integrate this rather than using the built-in mechanism that electron-builder provides? If not, is there any info you can provide to point me in the right direction of how I could 'roll my own'? Thanks for your time.

**Comment by develar** [comment]
Simply set env `SIGNTOOL_PATH` and `SIGNTOOL_TIMEOUT` See https://github.com/electron-userland/electron-builder/pull/1944#issue-250012296

**Comment by bhalbright** [comment]
Hello, just wanted to leave a note for anyone else looking at this, the custom signing tool won't be invoked unless you set the CSC_LINK (or WIN_CSC_LINK) to something, like some base 64 string (found this info from the repo @dchest  mentioned in #1944 )

**Comment by develar** [comment]
Solution in the upcoming 19.31.0:

`readonly sign?: CustomWindowsSign| string | null` option in the `win` 

where `CustomWindowsSign = (configuration: CustomWindowsSignTaskConfiguration) => Promise<any>`

**Comment by develar** [comment]
> just wanted to leave a note for anyone else looking at this, the custom signing tool won't be invoked unless you set the CSC_LINK (or WIN_CSC_LINK) to something

Fixed — `sign` is set, it will be called in any case.

**Comment by develar** [comment]
19.30.1 https://www.electron.build/configuration/win#how-do-delegate-code-signing
