### ISSUE TITLE
Code sign after exe generation - sha512 checksum mismatch

### ISSUE THREAD

**Issue by jsessink** [electron-userland/electron-builder#2111]
Electron Builder - ***19.27.7***
Electron Updater - ***2.8.9***
NSIS

After running electron-builder for Windows, we have a build script that runs to code sign the exe before deployment.  After it gets to the server, electron-updater fails with a sha512 checksum mismatch (which the error occurs during the install, after it has been fully downloaded).  I have also tried pulling the exe file down from the server and running a codesign util from Visual Studio CMD, and then re-uploading.  The auto updater also fails with the same error. 

Now, forgive me if I'm mistaken, but shouldn't the updater still work with a code-sign after the exe has generated?

My sign script:
signtool.exe sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /sha1 **value** "**path**"

**Comment by develar** [comment]
You cannot modify exe file after build. electron-builder signs for you — https://www.electron.build/code-signing

**Comment by amir-hadi** [comment]
@develar There is no way of doing this? Even updating the SHA512 of the latest.yml? Because we do build everything using Linux, but just sign under Windows. Anyway around this?

**Comment by develar** [comment]
Please use API to delegate code sign.

**Comment by AlanZou007** [comment]
@amir-hadi I have the same problem, and I don't know how to solve it. help~

**Comment by todanley** [comment]
@develar Hi, I have the same issue. I have tried to put "sign": "./sign.js" into my package.json to delegate code sign to a local script "./sign.js". However, the publish process of electron builder updater failed because it tried to sign .exe file before even building it. When delegated code sign was executed there wasn't even a .exe file. How to fix this?

**Comment by EdmarPereira** [comment]
Same problem here, after electron-builder finish the process for windows I need to run a script to sign the .exe and this causes the mismatch error
