### ISSUE TITLE
Error: Failed to find Electron v1.8.0 for <electron-v1.8.0-release-url>

### ISSUE THREAD

**Issue by mreilaender** [electron-userland/electron-builder#2113]
**Electron-updater version**: 2.8.9
**Electron-builder version**: 19.27.7
**Node version**: 7.8.0
**NPM version**: 4.2.0
**Target/Source System**: Windows

If the electron-version (_electronVersion_ in `package.json`) isn't manually set to 1.7.8. the build fails. In the [electron repository](https://github.com/electron/electron/releases) v.1.8.0 hasn't been released yet so I don't know why electron-builder wants to build with that version.

[Stacktrace](https://pastebin.com/a78WGTei) and [`package.json`](https://pastebin.com/54KGmJDW)

**Comment by develar** [comment]
Remove `node_modules` and `yarn` again.

**Comment by mreilaender** [comment]
Works but why ... ?

**Comment by develar** [comment]
Because electron-builder prefers to use **the same** electron version as you use during development.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/2104#issuecomment-331386076
