### ISSUE TITLE
Delta update support on Mac?

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2114]
* **Version**: 
"electron": "~1.6.2",
"electron-builder": "^19.29.2"

* **Target**: 
Mac

I tried the auto updater provided by electron builder works seamlessly. But it downloads the entire .zip. Is there any support for delta updates of the app?

**Comment by develar** [comment]
Not yet.

**Comment by harshitsilly** [comment]
check this space we are working on https://github.com/electron-userland/electron-builder/issues/4769
