### ISSUE TITLE
NSIS: Ability to specify `electronDist` path for ia32 and x64 targets

### ISSUE THREAD

**Issue by ObekTech** [electron-userland/electron-builder#2116]
* **Platform**: Windows

We are using build targets `Platform.WINDOWS.createTarget('nsis-web', Arch.ia32, Arch.x64)` (Programmatically) and we use a forked version of electron with the option `electronDist`.

**Problem**: `electronDist` option only allows one path to either `ia32` or `x64` Release folder of custom local electron fork, which does not allow both targets to be packaged for NSIS installer.

**Feature**: Ability to specify `electronDist` path for ia32 and x64 so that `Platform.WINDOWS.createTarget('nsis-web', Arch.ia32, Arch.x64)` packages both targets with local electron fork.

Thank you.

**Comment by ObekTech** [comment]
Closing. Found Solution #1716

**Comment by develar** [comment]
Just set `electronDist` to path where ZIP file located.
