### ISSUE TITLE
Code Signing Failure (libffmpeg.dylib)

### ISSUE THREAD

**Issue by coreybutler** [electron-userland/electron-builder#2118]
* **Version**: 19.31.1
* **Target**: mac/dmg

It appears as though the `libffmpeg` library isn't being signed. I'm not sure how electron-builder is handling this, so perhaps it's an upstream issue? If that's the case, is there a way to strip this from the final build prior to code signing (my app doesn't strictly need it)? I've looked around for a way to prune/ignore this, but I must be looking in the wrong places or doing something wrong.

![image](https://user-images.githubusercontent.com/770982/30888388-f4b44324-a2e5-11e7-98b7-59ab01b23e3f.png)

**Comment by develar** [comment]
Please provide build error text.

**Comment by coreybutler** [comment]
There isn't any build error.... that's the problem. When I posted this, I suspected the `libffmpeg.dylib` file wasn't being signed. However; upon further inspection, it looks like the file is being signed, but has the wrong permissions associated with it.... thus why the last line of the screenshot shows "One executable file has no executable permissions, but should" for `libffmpeg.dylib`.

Does electron-builder assign permissions, or is that happening in an upstream module?

For reference, I used [RB App Checker Lite](https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12) to test this. I build the app and drag the resulting `.app` file into the checker utility.

**Comment by develar** [comment]
We fix permissions only for app files. But Electron dist copied as is. Need to check Electron issue tracker about it.

**Comment by coreybutler** [comment]
Thanks @develar - I'll follow up on the electron board. 

@sethlu - let me know if you think this could be related electron-osx-sign... I can cross-post there if appropriate.

**Comment by sethlu** [comment]
@coreybutler Thanks for raising this issue! I just tested the major Electron releases and realized this permission issue seemed to appear in all of them. I don't think neither `electron-builder` nor `electron-osx-sign` created this issue...

On a more practical evaluation of it, the signed app can pass through the even without an executable `libffmpeg.dylib` with strict `codesign` verification. I'd be interested following an issue tracking on Electron.

**Comment by coreybutler** [comment]
@sethlu - thanks for testing... certainly seems like an upstream issue.
