### ISSUE TITLE
DMG and App generated doesnt show the Icon set in build configuration

### ISSUE THREAD

**Issue by santbob** [electron-userland/electron-builder#2120]
**Versions** 
`Node` - `v8.2.1`
`Yarn` - `0.27.5`
`electron-builder` - `19.31.1`

**Target Build** - `Mac`

Firstly thanks for this wonderful project.

I am trying to use Custom icon for the app targeting `Mac` and did read quite a few links online on how to do that including [Electron builder Configuration](https://www.electron.build/configuration/configuration) but dont seem to get either the dmg or the app have the custom icon.

Created a sample app to demonstrate the problem - https://github.com/santbob/react-route-electron

Does it need to code-signed for it to work?

**Comment by develar** [comment]
Config looks correct. I will check your project manually later, for now please set env DEBUG=electron-builder and attach terminal output, maybe it will hep to identify the issue.

**Comment by santbob** [comment]
```
$ yarn electron-pack
yarn electron-pack v0.27.5
$ yarn build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  40.13 KB  build/static/js/main.f60de0ef.js
  299 B     build/static/css/main.c17080f1.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

$ build --em.main=build/electron.js
electron-builder 19.31.1
No native production dependencies
Packaging for darwin x64 using electron 1.7.8 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing

All identities:
  1) 0A489866A695E9D25D09B3CA049F5F880039BFDE "com.apple.idms.appleid.prd.6c6342736f6e344a42563945457832717037506938673d3d"
     1 identities found

  Valid identities only
  1) 0A489866A695E9D25D09B3CA049F5F880039BFDE "com.apple.idms.appleid.prd.6c6342736f6e344a42563945457832717037506938673d3d"
     1 valid identities found
Building DMG
Done in 26.14s.
```

**Comment by develar** [comment]
Should be fixed now.
