### ISSUE TITLE
[updater]: TypeError: (_url || _load_url(...)).URL is not a constructor

### ISSUE THREAD

**Issue by wenxin3262** [electron-userland/electron-builder#2124]
* **Version**: 
electron-builder: 19.27.3

electron-updater: 2.10.0

* **Target**:  -mw

Tried with a few different version combinations.
downgraded the builder to 19.27.3
downgraded the updater to 2.9.3
still get the error on mac only:
[2017-09-27 16:02:02.277] [error] error Cannot check for updates: TypeError: (_url || _load_url(...)).URL is not a constructor
    at newBaseUrl (/Applications/xxx.app/Contents/Resources/app.asar/node_modules/electron-updater/src/main.ts:144:18)

I think it's because I am using electron 1.4.16 that comes with node 6.x and `URL` should be `Url` in this case.

* **Fixed**:
downgrade electron-updater to 2.8.9

Recommendation: can we have release notes somewhere for electron-updater

**Comment by juncaixinchi** [comment]
+ 1

**Comment by develar** [comment]
Yes, if you use electron-updater 2.0, please use at least stable Electron 1.7

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/CHANGELOG.md but this change was not reflected (because Electron 1.6 is released quite long ago).

**Comment by AlexCatch** [comment]
I'm also getting this version with Electron version 1.7.11 & updater version 2.20.1.

This only happens when packaging for production, it works fine in dev.
