### ISSUE TITLE
C++ Add-on not being included in the packaged version

### ISSUE THREAD

**Issue by alexlyp** [electron-userland/electron-builder#2127]
* **Version**: 19.31.1

* **Target**: 1.4.15

We are currently using electron-builder to package our electron application here: https://github.com/decred/decrediton  Building everything works as expected on all platforms except for windows.  

Due to issues with the way Windows handles shutdown requests for spawned child-processes, we created an add-on (win32ipc) which creates a pipe that allows our specific child-processes (dcrd and dcrwallet) to be signaled to cleanly shutdown when the pipe is closed.  

We have confirmed that the addon works, but unfortunately we are having difficulty including the add-on into our packaged windows version.  
https://github.com/decred/decrediton/blob/master/app/main.development.js#L306

As you can see there, this would work on any given system when locally built, but it will be still be using this absolute path when launched else where which leads to the module not being found.  

We have tried including the built win32ipc into our extraResources directory and then refer to them directly, but it appears it can't find the path and returns `Cannot find module: "."`  

Any help/guidance on including a built add-on to be accessed via the main process would be much appreciated!  Cheers.

**Comment by develar** [comment]
> If you have native addons of your own that are part of the application (not as a dependency), set nodeGypRebuild to true.
