### ISSUE TITLE
Windows icon in taskbar 'cut in half', until the app is 'pinned'

### ISSUE THREAD

**Issue by amir-hadi** [electron-userland/electron-builder#2128]
* **Version**: 19.31.1
* **Target**: win (NSIS)
My icon is broken / cut in half in Windows 10. I could not test other Windows versions yet. Interestingly the icon appears correct when I 'pin' the app to the taskbar.

Here are example screenshots:
![capture](https://user-images.githubusercontent.com/234253/30975559-da27ba0c-a472-11e7-921f-6d4927e9b893.PNG)
![capture2](https://user-images.githubusercontent.com/234253/30975558-da00026e-a472-11e7-9f4e-944b3c3a8659.PNG)

We are using an 256x256 sized ICO file. Can anyone advise? Did someone experience similar issues yet?

**Comment by eshcharc** [comment]
I experience the same issue. Any news regarding this?

**Comment by tylerjames** [comment]
I had a similar thing where my icon appeared with black vertical lines running down it until I pinned and then unpinned it.

I built from a Mac. The .ico file appears just fine in Finder. No idea what the problem is.

**Comment by ortichon** [comment]
@amir-hadi @eshcharc @tylerjames 
Joining late to this thread...
I've fixed a similar issue by changing the `icon` property of `electron-builder.json` to be more specific.
initially I had:
```json
{
...
    "win": {
        "icon": "dist",
        "target": ["portable"]
    },
...
}
```

and now I have:
```json
{
...
    "win": {
        "icon": "dist/favicon-256x256.png",
        "target": ["portable"]
    },
...
}
```

hope it helps.
worked for me on
* **version** : 20.14.7
* **operation system** : windows 10

**Comment by Last-Order** [comment]
As the issue which referenced this one. Using icofx to generate ico files can solve this problem.
https://github.com/mb21/panwriter/issues/2#issuecomment-445551408
https://github.com/mb21/panwriter/issues/2#issuecomment-445555521

**Comment by Venryx** [comment]
The solutions in the panwriter issue thread worked for me (my comment: https://github.com/electron-userland/electron-builder/issues/5083#issuecomment-691698188).

It would be nice if electron-builder handled this itself someday, though. (avoiding the image cut-off issue, without being so picky about the input file for the icon)

**Comment by CookieTriste** [comment]
I find a simple solution that work everytime. Just compile it as normal, then use a third-party application like Ressource Hacker to manually edit the icon.
