### ISSUE TITLE
How do I include images in package?

### ISSUE THREAD

**Issue by buddythumbs** [electron-userland/electron-builder#2130]
Hopefully this is a quick one, if not I will add in details.

I have images in components (inside `app/components/...`) which are stored in `app/assets/images/` - these show OK when in dev mode but after packaging, the images show as broken links in the built app.

Should these files be stored in resources? (outside app folder).

If so, I need some help on including images outside the app folder in my react components.

**Comment by develar** [comment]
Please use `extraResources` to not pack images into asar archive (enabled by default due to poor IO on WIndows). And then in a production mode (not dev) use `process.resourcesPath` as a base path to your images. https://www.electron.build/configuration/configuration#Configuration-extraResources

**Comment by buddythumbs** [comment]
Hey - thanks for the quick response.
BTW I am packaging portable option for windows but on a mac if that matters.
So I add 
```
"extraResources": {
   "app/assets/*"
}
```

???

If you have an example of this that would help - if not I can google around

Thx

**Comment by develar** [comment]
```
"extraResources": {
   "app/assets/**/*"
}
```

**Comment by develar** [comment]
Yes, you can specify `extraResources` only for `mac` or only for `win` if need.
