### ISSUE TITLE
Extra language support for DMG license dialog

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-builder#2131]
* **Version**: 19.32.2
* **Target**: MacOS

Is it possible to add extra language support for DMG license dialog?

It seems dmgbuild does support this but that feature is not exposed through electron-builder.

In addition, language codes ar, ko_KR and uk_UA do not work. The dmg does get built but cann't be openned with any of those languages present.

Many thanks

**Comment by develar** [comment]
Do you want to change default button labels? See https://www.electron.build/configuration/dmg (licenseButtons_LANG_CODE.json).

> uk_UA

Я проверю данную локаль.

**Comment by bingqiao** [comment]
@develar that's exactly what I was looking for. Thanks!

Any comment on the second issue where some languages codes not working?

**Comment by bingqiao** [comment]
@develar there is actually another issue regarding Russian license.

I tried adding an English license named with Russian language code: license_ru.rtf. This is because I'd like to show the Russian UI even though the license itself is still in English.

This didn't work. There was some encoding error and I had to use license_ru.txt (the plain text version of that English license) instead.

Thanks

**Comment by develar** [comment]
> There was some encoding error

Screenshot please.

>  license_ru.rtf

Please attach this file.

**Comment by bingqiao** [comment]
I haven't been able to reproduce that encoding error. It has been a bit inconsistent in my testing.

But I seem to have found something. I can't have both Chinese and Russian enabled in adding license.

The tow files attached are empty. It seems what matters here is the fact that these two charsets are being processed.





 If I have one of them together with another license named as license_en.rtf, it will work. But it doesn't work if both are present.
