### ISSUE TITLE
Auto update doesn't work for macOS if only specify dmg as target

### ISSUE THREAD

**Issue by tylerlong** [electron-userland/electron-builder#2137]
* **Version**: 19.33.0

* **Target**: 2.10.1

If I specify

```
"mac": {
      "target": [
        "dmg"
      ]
}
```

Then `latest-mac.yml` is not generated at all. And thus auto upgrade doesn't work.

It seems that I also need to add "zip" as target. Is it by design or bug?

**Comment by develar** [comment]
https://www.electron.build/auto-update

> zip target for macOS is required for Squirrel.Mac, whereas latest-mac.yml cannot be created, which causes autoUpdater error. Default target for macOS dmg+zip, you don't need to explicitly specify target.
