### ISSUE TITLE
Add git-lfs to base docker image

### ISSUE THREAD

**Issue by joaocc** [electron-userland/electron-builder#2140]
This is useful to speed up builds on CI systems that don't have git-lfs already installed (eg: gitlab)
```
apt-get update  -qq
apt-get install -qq software-properties-common
add-apt-repository ppa:git-core/ppa
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt-get install -qq git-lfs
```

**Comment by develar** [comment]
Just to make clear — it will work ONLY if CI supports docker natively. i.e. it will work on CircleCI, but on Travis. Because of security (SSH keys).

**Comment by joaocc** [comment]
On gitlab, I have run those lines on a build with ```image: electronuserland/builder:wine``` and ```git-lfs pull``` seemed to work fine (although I am not sure the repo I tested it with has LFS content).

I don't know about CircleCI (never looked at it).
But my intention was just to make it available, not to automatically run it.

**Comment by develar** [comment]
👍

**Comment by develar** [comment]
Done.
