### ISSUE TITLE
App opens to blank screen in production (Mac App Store)

### ISSUE THREAD

**Issue by holgersindbaek** [electron-userland/electron-builder#2143]
I've finally pushed my Electron app to the Mac App Store. It works great in development, by opening the app created by the electron builder signed with the development signature.

When I create my "mas" build and sign it with the production certificate, I can't open it on my Mac (this is how it should be, from what I understand). When I push it to the Mac App Store, the person who reviews it can open it, but the app opens to a blank screen.

My Electron app is essentially loading my website. This is my main.js:

    <!DOCTYPE html>
    <html>
      <head>
        <link rel="stylesheet" type="text/css" href="./styles.css">
      </head>
      <body>
        <div id="topbar">
          <p>Some app</p>
        </div>
        <script>

          // Add webview
          const webview = document.createElement('webview');
          webview.id = 'webview';
          webview.preload = './electronPreload.js';
          document.body.appendChild(webview);

          // Detect if online
          const loadSite = () => {
            webview.src = getParams(window.location.search).environment === 'production' ? 'https://myawesomewebsite.com/?platform=desktop' : 'http://localhost:3000/?platform=desktop';
          }
          loadSite();
        </script>
      </body>
    </html>

So 2 questions remain:

1. Why is the app window blank? I'm thinking that I might be missing some entitlement that allows the app to access the web. What do you think?
2. Is there some way I can test the production build locally, so I can make sure that I've actually fixed the issue before I push for review again?

**Comment by holgersindbaek** [comment]
No one has experienced anything similar?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-osx-sign/issues/151

**Comment by holgersindbaek** [comment]
Thanks for the quick feedback. Seems like that might be the solution to getting it through Apple review.

From what I understand in that issue, the way to test a distribution build locally, is by specifying development provisioning profile in the distribution build.

Right now, Electron Builder just picks the provisioning profile in the root folder. Is there a way I can specify which provisioning profile to use for which builds?

**Comment by kaansoral** [comment]
@holgersindbaek I'm in this exact same situation right now, what was your final solution?

**Comment by holgersindbaek** [comment]
Have your provisioning profiles in the root folder and no other provisioning profiles.

**Comment by kaansoral** [comment]
Originally, before submitting for review, without placing `embedded.provisionprofile` in the Contents folder of .app before signing, the flattened .pkg upload failed

So I assumed placing the `embedded.provisionprofile` - In the Contents folder after `electron-packager` but before `electron-osx-sign` and `electron-osx-flat` would be enough, as it allows the .pkg upload with `Application Loader`

So obviously I'm missing something, I'm only placing the `embedded.provisionprofile` which is for "Mac Distribution" - Am I supposed to put bundle another .provisionprofile too?

**Comment by kaansoral** [comment]
After diving into the depths of the provisioning, sandboxing and entitlements, I believe it's the missing `<key>com.apple.security.network.client</key>` entitlement property that's causing this issue - and if the .pkg uploads, it's not related to code signing - It needs to be manually added, and interestingly there's not much related discussions online

So both our testers assumably saw blank pages as the sandbox blocked the network call (doesn't explain how 'dom-ready' fired instantly and hid my custom loader, but it's a good enough explanation)

Currently submitting a new build, If I don't update this thread, future readers could assume the solution held
