### ISSUE TITLE
Electron 19.33.0 -> Error: AppX Application.Id can’t start with numbers: "3601...

### ISSUE THREAD

**Issue by ivandroid** [electron-userland/electron-builder#2144]
It can. Mine starts with 3601...

**Comment by develar** [comment]
Cannot https://github.com/electron-userland/electron-builder/issues/2108

"Please set appx.applicationId"

**Comment by Tazeg** [comment]
Couldn't find the answer to this question...

**Comment by Tazeg** [comment]
Finally solved. A short answer is :

	"appx": { 
	"identityName": "12345MYCOMPANY.MYAPP", 
	"publisher": "CN=XXXXXX", 
	"publisherDisplayName": "MYCOMPANY", 
	"applicationId": "MYCOMPANY.MYAPP" 
	}, 

"publisher", "identityName" and "publisherDisplayName" are given on developer.microsoft.com, Your App > App Management > App identity

**Comment by hermit99** [comment]
Thanks @Tazeg applicationId that you added was the key to solve the issue.
