### ISSUE TITLE
the custom dist url cannot be usage

### ISSUE THREAD

**Issue by yhostc** [electron-userland/electron-builder#2149]
https://github.com/electron-userland/electron-builder/blob/a3240c269308eaf8b67ce96c8f93dcf055738826/packages/electron-builder/src/util/yarn.ts#L50

I tried to customize `disturl` in `.npmrc`, but it didn't work. Maybe `process.env` should be at the end of the object.

**Comment by develar** [comment]
For what do you need to change it? [ELECTRON_MIRROR](https://github.com/electron-userland/electron-download)?

**Comment by yhostc** [comment]
Yes, I've already configured `electron_mirror` in `.npmrc`.

**Comment by cynx** [comment]
@develar electron_mirror seems to have no impact on this. In corporates usually the electron headers are store on custom url (internal) and disturl can be used to configure this. I am currently facing this issue as well. can disturl be made configurable or honor .npmrc disturl config?

**Comment by smildlzj** [comment]
has same problem, @develar
