### ISSUE TITLE
Windows appx package family name?

### ISSUE THREAD

**Issue by ivandroid** [electron-userland/electron-builder#2150]
After uploading an appx file to the Windows App Store there is an error: "Invalid package family name"

How can I include package family name into the electron builder configuration?

**Comment by develar** [comment]
Hmm... Have you set `publisherName`?https://github.com/electron-userland/electron-builder/issues/2108#issuecomment-333200711

**Comment by ivandroid** [comment]
Yes, the publisher name is set, but it's also invalid. Does package family name depend on publisher name? I think, I have bought a wrong code signing certificate. My windows app store publisher name deffers from the publisher name in the code signing certificate. Do I have to request a code signing certificate with the same publisher name as in the Windows App Store?

**Comment by develar** [comment]
@ivandroid As @qmatteoq you don't need buy code sign cert for AppX app.

> I confirm that the package uploaded on the Store doesn't have to be signed. Even if you sign it, the certificate is removed and the package resigned with a Microsoft one during the certification process.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/2108#issuecomment-333191838

**Comment by ivandroid** [comment]
Thank you for this useful information. I revoked my code signing certificate yesterday. But I have one last question: What about the certificate pfx file which can be set in the electron builder configuration? I bought a code signing certificate and then exported it as pfx file. Is it necessary?

**Comment by ivandroid** [comment]
I've successfully uploaded an unsigned app to the Windows App Store. Many thanks for your useful information. You saved me a lot of time and money. :)

**Comment by develar** [comment]
> Is it necessary?

As @qmatteoq said, no, for Windows Store it is not required. We are still waiting answers to https://github.com/electron-userland/electron-builder/issues/2108#issuecomment-333283622 and https://github.com/electron-userland/electron-builder/issues/2108#issuecomment-333290042 and when we will have answers, our docs (and impl) will be improved to avoid such issues.
