### ISSUE TITLE
Binary not found in new AppImage support

### ISSUE THREAD

**Issue by mzuehlke** [electron-userland/electron-builder#2151]
* **Version**: 19.34.0
* **Target**: AppImage

The build AppImage fails to start:

    ./cate-desktop-1.0.0-dev.1-x86_64.AppImage
    /tmp/.mount_cate-dBbVFqT/AppRun: Line 54: /tmp/.mount_cate-dBbVFqT/app/cate-desktop: file not found

Line 54 in `AppRun`:

    BIN="$APPDIR/app/cate-desktop"

Actually the searched binary is inside a `linux-unpacked` directory:

    app/linux-unpacked/cate-desktop

**Comment by develar** [comment]
@mzuehlke Thanks, 19.34.1
