### ISSUE TITLE
packaging windows and macOs

### ISSUE THREAD

**Issue by Devhercule** [electron-userland/electron-builder#2152]
Hi,

I want to use electron-builder to package my application.

I would like to know if I can build a package for MacOs from Windows.

I'm on windows, and I want to create an executable for Mac, is it possible?

Thank you

**Comment by develar** [comment]
Hi, pease see https://www.electron.build/multi-platform-build

Let's assume that you don't have native deps. 
There are 2 issues:
* you can create DMG only on macOS.
 * you can code sign app only on macOS.

If you just want to create `zip` — you can use our Docker images https://www.electron.build/multi-platform-build#docker to build macOS on Linux using docker for windows (https://docs.docker.com/docker-for-windows/).

Also, you can use Travis CI (https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows).
