### ISSUE TITLE
Is there a way to define a minimum Windows version?

### ISSUE THREAD

**Issue by PierBover** [electron-userland/electron-builder#2156]
We want to prevent Windows 7 users of installing our app.

Is there a way to configure a minimum windows version?

**Comment by develar** [comment]
Yes, using https://www.electron.build/configuration/nsis#custom-nsis-script

http://nsis.sourceforge.net/Get_Windows_version

Default installer has:

```
${IfNot} ${AtLeastWin7}
    MessageBox MB_OK "$(win7Required)"
    Quit
  ${EndIf}
```

**Comment by PierBover** [comment]
I imagine this is not available in Squirrel either?

**Comment by develar** [comment]
Yes, only NSIS gives you freedom and ability to customize installer using simple script language.
