### ISSUE TITLE
Does NSIS work with autoUpdater?

### ISSUE THREAD

**Issue by PierBover** [electron-userland/electron-builder#2157]
If not, what would be the proper way of handling app updates with NSIS?

**Comment by develar** [comment]
Yes, please see https://www.electron.build/auto-update

**Comment by PierBover** [comment]
Thanks @develar .

So I imagine if an app is already using Squirrel with `autoUpdater` the user would need to uninstall and reinstall from scratch to switch to `electron-updater` and NSIS. Is this correct?

**Comment by develar** [comment]
> the user would need to uninstall and reinstall from scratch to switch to

Yes. Only NSIS allows you to migrate to another installer, but Squirrel.Windows supports only Squirrel.Windows.

You can use https://github.com/electron-userland/electron-builder/issues/837#issuecomment-309170901

**Comment by jclopmel** [comment]
> If not, what would be the proper way of handling app updates with NSIS?

autoUpdater is does but wach out with new versions, that crash quite a lot.

**Comment by xmedeko** [comment]
One way to make auto update Squirell.Windows to NSIS could be (not tested):
1. Let say you have `myapp.exe`, make a NSIS installer and rename it to `myapp.exe`.
2. Make a nupkg full for Squirell.Windows containing just the `myapp.exe` and release it.

The Electron auto updater will install the `myapp.exe`. When the user runs it first (or the auto installer runs it). It would run just the NSIS installer and install the proper `myapp`.
