### ISSUE TITLE
Taking too long for build process

### ISSUE THREAD

**Issue by YuilTripathee** [electron-userland/electron-builder#2159]
* **Version**:  19.34.1

* **Target**:  Windows

This always continue to download this zip file with low download rate and takes a lot of time.
> electron-builder 19.34.1
>No native production dependencies
>Packaging for win32 x64 using electron 1.6.14 to dist/win-unpacked
>Downloading tmp-8824-0-electron-v1.6.14-win32-x64.zip
>[>                                                       ] 0.7% of 52.88 MB (487.12 B/s)

**Comment by develar** [comment]
Please see mirror options —  https://github.com/electron-userland/electron-download
