### ISSUE TITLE
nsis-web ignoring the artifactName config parameter for GitHub

### ISSUE THREAD

**Issue by jessep** [electron-userland/electron-builder#2162]
* **Version**: 19.34.1

* **Target**: windows

I have ` "artifactName": "${productName}.${ext}"` set, yet nsis is uploading `WorkFlowy-WebSetup-0.1.0.exe` to github.

As you can see in my build config, I've tried to set it in three places, none seem to work. Is this a bug? Am I doing things wrong? Is this naming somehow important?

```
"build": {
    "artifactName": "${productName}.${ext}",
    "appId": "com.workflowy.desktop",
    "mac": {
      "category": "public.app-category.productivity",
      "target": [
        "default",
        "mas"
      ]
    },
    "win": {
      "artifactName": "${productName}.${ext}",
      "target": "nsis-web"
    },
    "nsis": {
        "artifactName": "${productName}.${ext}"
    },
    "compression": "normal",
    "publish": {
      "provider": "github"
    },
    "linux": {
      "category": "Office"
    }
  }
```

**Comment by develar** [comment]
Web installer configuration should be defined in the `nsisWeb`.

**Comment by develar** [comment]
Docs fixed.

**Comment by jessep** [comment]
Still doesn't appear to be working. Here's my config file:
```
  "build": {
    "artifactName": "${productName}.${ext}",
    "appId": "com.workflowy.desktop",
    "mac": {
      "category": "public.app-category.productivity",
      "target": [
        "default",
        "mas"
      ]
    },
    "win": {
      "target": "nsis-web"
    },
    "nsisWeb": {
        "artifactName": "${productName}.${ext}"
    },
    "compression": "normal",
    "publish": {
      "provider": "github"
    },
    "linux": {
      "category": "Office"
    }
  }
```
Here's what was uploaded to github:
```
[====================] 100% 0.0s | WorkFlowy-WebSetup-0.1.1.exe to GitHub
```

**Comment by develar** [comment]
@jessep GitHub doesn't allow spaces and other special symbols in the name. So, if your `artifactName` is not suitable for Github, default safe name pattern is used. So, what's is your `productName`? You can contact me directly using Slack if it is a private information.

**Comment by jessep** [comment]
It's WorkFlowy. So, for mac, for example, it is coming out as WorkFlowy.dmg

**Comment by jessep** [comment]
Thanks so much, really appreciate this fix! It was blocking release on windows, because changing the installer name with every release requires the installer to build up credibility with their malware detection thingy for each release, making it super hard for people to install.
