### ISSUE TITLE
Localizing "displayName" for AppX files

### ISSUE THREAD

**Issue by dimazer** [electron-userland/electron-builder#2163]
* **Version**: 19.32.2

* **Target**: Windows / AppX

Is it possible to localize display (displayName tag) for AppX (Windows Store) target? Is there a ready work flow for it or can it be done only with unpacked package adding additional ressources?

Many thanks for your support

**Comment by develar** [comment]
Have you tried `displayName ` https://www.electron.build/configuration/appx?

**Comment by dimazer** [comment]
Thanks for your feedback.

Yes, but i want to localize it. My app has differnet names for different languages. Maybe is it possible to localize it.
