### ISSUE TITLE
Upload to github release not working?

### ISSUE THREAD

**Issue by gengjiawen** [electron-userland/electron-builder#2164]
electron-builder: 19.34.2.

Repro repo: 
https://github.com/gengjiawen/electron-devdocs
Travis ci log:
https://travis-ci.org/gengjiawen/electron-devdocs/jobs/284522006. The log shows it has uploaded the binary, but I can't find it in the release page.

It's working before. But recently https://github.com/SimulatedGREG/electron-vue remove two package.json structure. I sync with the change. Is this the reason ?

**Comment by develar** [comment]
Works for me. If you use both travis and appveyor, consider to create draft release in advance. Or just remove appveyor and use our recommended travis conf (https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml) to build win on linux on Travis CI.

**Comment by gengjiawen** [comment]
My other project can create release automatically using electron-builder. The confusing part is log say it's being uploaded while it's not.

**Comment by develar** [comment]
If you want to understand why, please set `DEBUG=electron-builder` env. But I guess because of race AppVeour vs Travis.

**Comment by gengjiawen** [comment]
Thanks, I will give it a try.

**Comment by gengjiawen** [comment]
With `DEBUG=electron-builder` set, I see why binary not uploaded. Should this show even when the env not set ?
```
Release with tag v0.9.8 doesn't exist and is not created, artifact Devdocs-0.9.8.dmg is not published
```

**Comment by gengjiawen** [comment]
And why some repo can automatically create release draft ?

**Comment by develar** [comment]
>  why some repo can automatically create release draft ?

draft release created when script named as `release` or when `--publish=always` CLI param specified.

**Comment by gengjiawen** [comment]
The script name is `release`, as you can see https://github.com/gengjiawen/electron-devdocs/blob/master/.travis.yml#L39.

**Comment by gengjiawen** [comment]
The script name is `release`, as you can see https://github.com/gengjiawen/electron-devdocs/blob/master/.travis.yml#L39.

**Comment by develar** [comment]
I see `Warning: Release with tag v0.9.8 already exists` in the log. It means that you have created non-draft release and so, by default, artifact is not uploaded to. (yes, I am aware that when this issue was posted, there was no such release).

**Comment by develar** [comment]
> Should this show even when the env not set ?

Level changed to `warn` if `publish` is set to `always` (as in your case).

**Comment by gengjiawen** [comment]
If the tag not exist, it won't automatically create the draft release either.
I bump version in this commit, https://github.com/gengjiawen/electron-devdocs/commit/c71cc7c4b7681984a176aa3330dd2fe52f84b21c.
Related travis log:  https://travis-ci.org/gengjiawen/electron-devdocs/jobs/284909216.
```
2017-10-08T02:57:24.431Z [secure] Release with tag v0.9.9 doesn't exist and is not created, artifact Devdocs-0.9.9.dmg is not published
```

**Comment by develar** [comment]
Your release script invokes build - I think it is a problem. You need to pass publish-always explicitly.

To investigate - can we detect nested script or not.

**Comment by gengjiawen** [comment]
You are right, nested script is the cause. I change release script to below, and it's working as expected.
```
"release": "node .electron-vue/build.js && electron-builder",
```
