### ISSUE TITLE
Code signing is extremely slow

### ISSUE THREAD

**Issue by brandoncc** [electron-userland/electron-builder#2169]
* **Version**: 
19.35.0

* **Target**: 
Darwin x64

I just updated a fairly small app from a very old version of electron-boilerplate which used electron-builder v9 or something like that. My releases used to be quick, with code signing only taking a couple of seconds. Code signing takes *forever* now. I just completed a build which took 537s, almost all of which was stuck at code signing.

Is there a known solution to this problem?

**Comment by develar** [comment]
macOS version? Is latest Xcode installed? If yes to both, try to restart macOS (not joke).

**Comment by brandoncc** [comment]
MacOS Sierra 10.12.6 and Xcode 9.0 (9A235). I actually did try restarting and it didn't help. I just tested building the electron-boilerplate template and it signed very fast.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder,electron-osx-sign*` and attach log of the terminal output.

**Comment by brandoncc** [comment]
There is a *massive* list of files in `/Contents/Resources/app.asar.unpacked/node_modules/grpc/third_party/boringssl/fuzz/**/*` that were signed (and took pretty much the entire build time). 

I am rebuilding right now with redirected output to a file because it was much longer than my shell buffer history.  Here is what I have until that completes.

[log.txt](https://github.com/electron-userland/electron-builder/files/1369302/log.txt)

Please let me know if you need the full log when it completes.

**Comment by brandoncc** [comment]
It finally completed, here you go.

[build.log](https://github.com/electron-userland/electron-builder/files/1369341/build.log)

**Comment by develar** [comment]
Until I will not find time to investigate your project, you can investigate what files in the grpc module are not required for you and exclude it using `files` option.

**Comment by brandoncc** [comment]
I think I am getting grpc from firebase-admin. I do use that, so I am guessing I need the ssl part :-/

**Comment by vincentsong** [comment]
I got same issue with Firebase-admin lib

**Comment by smyrgl** [comment]
I have seen this as well...it is because of grpc and the inclusion of boringssl.  It is running codesign on the cert_corpus files located here: https://github.com/google/boringssl/tree/master/fuzz/cert_corpus

**Comment by derwaldgeist** [comment]
I'm having the same issue. Code signing takes ages. I'm also using firebase-admin.

**Comment by p0la** [comment]
Did you guys find any solution to this ? Same problem here with firebase-admin. @vincentsong @derwaldgeist

**Comment by derwaldgeist** [comment]
If I remove firebase-admin, signing is fast again. But DMG building still takes very long.

**Comment by derwaldgeist** [comment]
There's another issue #1714 about this which has been closed.

**Comment by pronebird** [comment]
Why don't you folks raise this issue with the firebase-admin instead? It's not like electron-builder can do much about the binaries in the third party module. Also, to help resolve this issue, you can try signing those binaries manually and measure how long it takes.

**Comment by derwaldgeist** [comment]
Well, I was expecting that this wasn't just an issue with `firebase-admin`, but with all large packages.

**Comment by pronebird** [comment]
I can only think of pre-signing such dependencies with cache invalidation tight together with package lock file. This is not trivial and big task IMO.

**Comment by derwaldgeist** [comment]
Ok, thx for that feedback.

**Comment by Arjan-Zuidema** [comment]
I had an issue with slow code signing as well. It seems to be connected with #3685 and can be fixed by cleaning your com.apple.security.plist file. See [this](https://github.com/electron-userland/electron-builder/issues/3685#issuecomment-480083871) comment. I hope this will fix any of your problems.

**Comment by develar** [comment]
Each year Apple getting worse and worse. Each year Apple makes code singing and code signing process more slowly, more cumbersome, more complicated and more buggy. I doubt that I can do anything here since no more pleasure to work on macOS related issues as even MS did this process more simpler.

**Comment by Arjan-Zuidema** [comment]
It looks to me the actual keychain file gets deleted, but the entry remains in the com.apple.security.plist file. Using the command `security delete-keychain <keychain path>` removes the entry from that file, with a 'No such file or directory' error.
