### ISSUE TITLE
[electron-updater] Allow to more friendly set autoUpdater.channel

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#2172]
Could you provide an easyer way to set `autoUpdater.channel`. This to allow us to set the wanted version at startup depending on the users settings (if they want beta or not) ?

And related to #1182, automatically set `allowDowngrade = true`.

Thanks

**Comment by popod** [comment]
@develar is this in progress ? When this will be finish, I could do some doc about the management of channels..

**Comment by popod** [comment]
Hello @develar any news about this feature ? Thanks !

**Comment by popod** [comment]
Thanks a lot @develar!
I will try this with #1182 !

**Comment by develar** [comment]
Fixed in 2.17.3
