### ISSUE TITLE
autoUpdater.quitAndInstall does not force run with oneClick=false installation and silent install

### ISSUE THREAD

**Issue by shaycobs** [electron-userland/electron-builder#2179]
* **Version**: 
19.27.7

* **Target**: 
2.10.2

I have an app with an installation which is not oneClick and allows to change installation directory, and when auto-updating the app the silent installation finishes but the app doesn't run. When I change the installation to oneClick the app runs after the silent installation.
This is its nsis:
```
"nsis": {
      "oneClick": "false",
      "allowToChangeInstallationDirectory": "true"
    }
```

I'm using setImmediate as it was given as a solution in #1604.
```
setImmediate(function() {
                app.removeAllListeners("window-all-closed");
                updateWindow.close();
                autoUpdater.quitAndInstall(true, true);
            });
```

**Comment by GhostfromTexas** [comment]
Our company, Balanced Media Technology, has a fix for this we are submitting as a PR and will reference this error.

Our PR will also fix the force-run being broken in general.
