### ISSUE TITLE
Throttled appUpdater.checkForUpdates()

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2190]
* **Electron-builder Version**:  19.36.0
* **Electron-updater Version**: 2.11.0
* **Target**:  Windows

The main problem is that when I use `.checkForUpdates()` command, the renderer window freezes for a while, causing some distortions in animations, is this normal or is there any way to fix it?

**Comment by develar** [comment]
Do you call from main process?

**Comment by marceloavf** [comment]
Yes, all the calls are made inside main process using `ipc`:

**Main process**
```
ipcMain.on('check-for-updates', () => {
  autoUpdater.checkForUpdates();
});
```

**Renderer process**
```
checkForUpdates() {
   ipcRenderer.send('check-for-updates');
},
```

**Comment by develar** [comment]
Very strange. What electron version do you use? How often do you call it?

**Comment by marceloavf** [comment]
It's Electron *1.7.8*

Just once, after the `browserWindow` is ready to show,  I call it with a `setTimeout`, otherwise it flicker my initial fade animation.

**Comment by develar** [comment]
Got it. Please try to call using setImmediate

**Comment by marceloavf** [comment]
This way?

```
setImmediate(() => {
  ipcMain.on('check-for-updates', () => {
    autoUpdater.checkForUpdates();
  });
});
```

What this `setImmediate` exactly do?

**Comment by develar** [comment]
No, in the IPC main handler. To postpone check after.

**Comment by marceloavf** [comment]
Okay, Do you have some example, please?

**Comment by develar** [comment]
Please try 

‘’’
ipcMain.on('check-for-updates', () => {
  setImmediate(() => {
    autoUpdater.checkForUpdates();
  });
});
‘’’

**Comment by marceloavf** [comment]
Keeps happening

**Comment by develar** [comment]
> Just once, after the browserWindow is ready to show, I call it with a setTimeout, otherwise it flicker my initial fade animation.

Ok, so, use this approach :)
