### ISSUE TITLE
Docker images out of date

### ISSUE THREAD

**Issue by joaocc** [electron-userland/electron-builder#2193]
Even thought the Dockerfiles already seem to include git-lfs, docker images still don't show them.
Could you pls run the build command so the latest changes are available?
(ideally, the travis build process could also build and send the images to dockerhub).
Thx

$ docker images
electronuserland/electron-builder         wine                651ec3eb711b        5 weeks ago         1.6GB
electronuserland/electron-builder         latest              c12699b17ac1        5 weeks ago         1.17GB

$ docker run --rm -it electronuserland/electron-builder:wine bash

# git lfs
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/releases/tag/v19.29.2
