### ISSUE TITLE
makensis.exe fails if LOCALAPPDATA path contains non-Latin characters

### ISSUE THREAD

**Issue by mvarakin** [electron-userland/electron-builder#2197]
Hello,

electron-builder fails if LOCALAPPDATA path contains non-Latin characters.
I am on Windows 10. electron-builder version is 19.37.1.

Below is an extract of a log.

> Error: C:\Users\Михаил\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe exited with code 1
> Output:
> [skipped]
> Command line defined: "COMPRESS=auto"
> Command line defined: "BUILD_UNINSTALLER"
> Command line defined: "UNINSTALLER_OUT_FILE=c:\Electron\resources\project_name\dist\.__uninstaller-nsis-project_name.exe"
> Processing config: C:\Users\������\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\nsisconf.nsh
> Processing script file: "<stdin>" (ACP)
> 
> Error output:
> Plugin not found, cannot call nsProcess::_FindProcess
> Error in macro nsProcess::FindProcess on macroline 1
> Error in macro CHECK_APP_RUNNING on macroline 3
> !include: error in script: "uninstaller.nsh" on line 10
> Error in script "<stdin>" on line 150 -- aborting creation process

My solution after days of unsuccessful googling:
I manually set LOCALAPPDATA= ... to another path before building and it works.

**Comment by develar** [comment]
> I manually set LOCALAPPDATA= ... to another pat

What another path can be used if your user name contains non-ASCII symbols?

**Comment by mvarakin** [comment]
I just 'set LOCALAPPDATA=C:/Electron'
On first run of the builder, npm installed libraries there and now the builder works.

**Comment by develar** [comment]
Not clear how can electron-builder fix it because we cannot dir outside of user dir because of access level.

**Comment by develar** [comment]
Workaround for now — set env `ELECTRON_BUILDER_CACHE`.
