### ISSUE TITLE
Unsupported provider: undefined. (Mac, generic provider)

### ISSUE THREAD

**Issue by petren** [electron-userland/electron-builder#2198]
* **Electron builder: 19.37.1**: 
* **Electron updater: 2.12.0**: 
* **Target: Mac (Squirrel), zip**: 

I'm trying to get Electron auto update to work, but am running into issues. 

autoUpdater runs and hits my http server:
![screen shot 2017-10-13 at 8 52 14 am](https://user-images.githubusercontent.com/4563915/31554936-05cec056-aff4-11e7-84cc-3b5c7a7719e9.png)

After that it fails. I am using "dev-app-update.yml" to debug because rebuilding the application every time was very time consuming. When it runs, it outputs the following error:
![screen shot 2017-10-13 at 8 55 10 am](https://user-images.githubusercontent.com/4563915/31555011-47e21560-aff4-11e7-8b61-4404b49ad3ea.png)

My package.json build looks as follows:
```json
"build": {
    "appId": "com.app.td",
    "productName": "TD",
    "publish": [{
        "provider": "generic",
        "url": "http://localhost:8080/"
    }],
    "win": {
        "target": "nsis"
    },
    "nsis": {
        "perMachine": true
    },
    "mac": {
        "category": "public.app-category.finance",
        "target": [
            "zip",
            "dmg"
        ]
    }
}
```

I'm confused because the error says "unsupported provider: undefined" but I have listed a generic provider.

I am awaiting approval from Apple, so I don't have a certificate yet. Will it not work at all even for testing without? 

Any help is greatly appreciated! Thanks.

**Comment by petren** [comment]
Nevermind, I finally got my logging in order and it's the code signature.

**Comment by pureZjr** [comment]
I have the same problem，but i not reall understand how to handle it，can u teach me？
