### ISSUE TITLE
Linux AutoUpdate AppImage quitAndInstall does not restart the app

### ISSUE THREAD

**Issue by kwent** [electron-userland/electron-builder#2200]
Hi,

I'm trying the newly linux AutoUpdate with target: `AppImage` but when i call `quitAndInstall` new AppImage is downloaded and present on my filesystem but the app does not reboot on it.

```
"electron-builder": "^19.37.1",
"electron-updater": "^2.12.1",
```

Thanks for your great work !

Regards

**Comment by develar** [comment]
It is expected default behaviour. Flag `isForceRunAfter` is not set and not supported for AppImage currently.

**Comment by mobitar** [comment]
Linux now supports auto-update? This is news :) @develar I know you got your hands full already, but perhaps an email newsletter would be a good way to build engagement and drive up donations :)

**Comment by develar** [comment]
@mobitar Email newsletter to about new features? You can use https://about.sibbell.com :)

**Comment by mobitar** [comment]
Ah interesting, didn't know about that :)

But never underestimate the power of email in driving up engagement. It's a really powerful tool. Because people might not donate the first time, but if they notice you're continually pushing out updates, then it makes a difference. This isn't particularly a problem for you to solve, but just open-source projects in general.

**Comment by sacunningham** [comment]
Should the quitAndInstall method still install the updated AppImage?  I'm able to get the download to succeed with AppImage's.  In the Event handler for 'update-downloaded' i'm calling quitAndInstall and i'm faced with "Unhandled rejection Error: Object has been destroyed".  Without quitAndInstall how do you get the update installed on the users machine?

**Comment by develar** [comment]
To be clear — I have checked and tested manually only default recommended case. I will check and fix this use case next week.

**Comment by jaxxThageesan** [comment]
Any update on this issue I am running into the same issue when trying to upgrade linux.

**Comment by develar** [comment]
Ok, will check in several days.

**Comment by Nirupg63** [comment]
Is there any update on this?

**Comment by kwent** [comment]
Hi,

I did a donation few weeks ago about this issue ? Any news ? How are tasks prioritized ? Thanks :)

Regards

**Comment by develar** [comment]
Duplicates #2240

Please be aware of https://github.com/electron-userland/electron-builder/issues/2240#issuecomment-350304675

> quitAndInstall is not recommended because electron-updater launches application not using gtk-launch and so, icon of the app maybe missed (the same effect as "launch by file vs launch via spotlight").

@kwent Please try electron-builder 19.52.1 and electron-updater 2.18.2
