### ISSUE TITLE
~/Applications(Install only for me) option is not selected by default even though the UI installer shows selected when pkg is created with allowCurrentUserHome:true

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2201]
* **Version**:  19.37.0

* **Target**:  Mac

 I am creating a pkg with the config -
```
"pkg": {
      "allowAnywhere": false,
      "allowCurrentUserHome": true,
      "allowRootDirectory": false
    },
```

And it DOES create a package that does not require admin password.

But the problem is the **"Install only for me"** option is not selected by default. I had to manually click **"change install location"** -> the default selected is "Install for all users on this computer" (even though in the package.json for electron builder I have mentioned `"allowRootDirectory": false` && even though the UI in the installer shows "install only for me" is selected ) -> Manually click **"install only for me"** and then the package would install the app without the admin password. And the app would be in the `~/Applications` (current user apps) rather than `/Applications` (for all users)

Step 1 - 
<img width="613" alt="screen shot 2017-10-14 at 9 54 27 am" src="https://user-images.githubusercontent.com/1799117/31572592-920c15ea-b0c7-11e7-958f-0ad0f520e4ab.png">

Step 2 - 
Notice here, it directly jumps to step 3 of the installer and in doing so, **"install for all users of this compuer"** is selected by default and hence the installer prompts for an admin password. Opposite to the config I used during the build time.

<img width="620" alt="screen shot 2017-10-14 at 9 54 35 am" src="https://user-images.githubusercontent.com/1799117/31572597-a8de9a36-b0c7-11e7-9aaa-a0f8fe18a022.png">

Step 3 -
Then, I have to click on **"change install location"**   which takes me to the step 2 of the installer.
Here on arrival, I get an error message "installer does not allow this software to be installed here" but the UI on the installer shows the "install for me only" is selected. But actually, the **"install for all users of this compuer"** and hence the error message.

<img width="613" alt="screen shot 2017-10-14 at 9 54 49 am" src="https://user-images.githubusercontent.com/1799117/31572601-b66970d6-b0c7-11e7-82bd-eacefa5d1aa8.png">

Step 4  -
To get rid of the above error msg, I have to manually click **"install only for me"** option and then the installation succeeds without prompting for admin password and the app is installed to `~/Applications`

<img width="612" alt="screen shot 2017-10-14 at 9 54 59 am" src="https://user-images.githubusercontent.com/1799117/31572603-bce45854-b0c7-11e7-8db7-bcc306969537.png">

@develar Can you please provide any inputs?

pkg link - https://www.dropbox.com/s/844rqyk64asb7pt/test.pkg?dl=0

P.S Thank you for the awesome work of electron-builder 👍

**Comment by develar** [comment]
Last several weeks I was focused on delta updates, I will take a look on this issue in 2 days. macOS is our top priority (even not recommended pkg target).

**Comment by Ajeey** [comment]
I would be happy to use dmg but with dmg there is always a case - what if the user does not move the app to the applications folder.

With pkg I am assured that the app resides in applications folder after installation.

**Comment by etyp** [comment]
We're running into this as well. @develar any idea how we can aim to solve it? Willing to help out.

**Comment by dungvt** [comment]
Hello everyone,
Do we have any idea to solve this problem?. That really a bit confusing for the user.

**Comment by wittjeff** [comment]
This is also an accessibility issue. Even without the bogus error message, one cannot go to the list control and re-select "Install for me only" using the keyboard alone. So a keyboard-only user is blocked, even though the requested setting appears to be the default. Multiple layers of not-right.

**Comment by wittjeff** [comment]
Seems to be an issue in the pkg installer, which is a Mac OS component.  See also https://github.com/ContinuumIO/anaconda-issues/issues/836

**Comment by aam1r** [comment]
This is still happening on macOS Big Sur (11.2.3), but does not happen on macOS Monterey (12.1).

Has anyone been able to figure out why this happens and if there's a workaround here?
