### ISSUE TITLE
Support for hoisted node_modules (lerna + yarn workspaces)?

### ISSUE THREAD

**Issue by evgenykochetkov** [electron-userland/electron-builder#2205]
* **Version**: 19.34.2

* **Target**: mac, windows

In a standard lerna + yarn workspaces monorepo hoisted dependencies are not included in asar:
```
repo_root
    node_modules
        ... hoisted common deps, not included in asar
    packages
        electron_app
            node_modules
                ... only these are included
        other_packages
```

If there is no official workaround, I'd love to submit a PR, but would really appreciate some guidance.
So far I've changed [`_readInstalled`](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/util/packageDependencies.ts#L82) to look for packages listed in package.json until root, like `require` does, but that did not completely solved the issue and I'm stuck :(

**Comment by evgenykochetkov** [comment]
Also, this seems kind of related to #1837

**Comment by evgenykochetkov** [comment]
UPD: I solved it, will create a PR soon

**Comment by develar** [comment]
@evgenykochetkov Sorry, https://github.com/develar/electron-builder/commit/7844c3b19a20e5dfba71a920b0a6db7d9211736c

**Comment by evgenykochetkov** [comment]
@develar Oh, nice 👍🏻
