### ISSUE TITLE
password with generic provider

### ISSUE THREAD

**Issue by erikkurtu** [electron-userland/electron-builder#2207]
* **Version**: latest
* **Target**: nsis

I'm using electron-updater with a "generic" provider. The setup is working well, but I need to secure my web directory and setup file. I'd like to do this via an htaccess login or parameter.

I setup a htaccess parameter and tried setting my url property (in package.json) to www.mydomain.com/mydirectory/latest.yml?param=rightthing. And then setting the path in latest.yml to setup.exe?param=rightthing. That, and a few variations, didn't work.

Can you give me some direction on setting something up to password protect my yml and setup files while still using the generic provider?

Thanks much

**Comment by develar** [comment]
Please set `requestHeaders` to your required headers.

About http auth — https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
