### ISSUE TITLE
Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by lzcrwxl** [electron-userland/electron-builder#2208]
* **Version**: electron-builder 19.37.2

* **Target**: nsis

I'm using electron-builder,it can be built but the dll files cannot be found,the errors show as:
C:\Users\hasee\Desktop\jiacerproject\electron-quick-start\dist\win-ia32-unpacked\resources\app.asar

C:\Users\hasee\Desktop\jiacerproject\electron-quick-start\dist\win-ia32-unpacked\resources\app.asar\cardapi66.dll:74 Uncaught Error: Dynamic Linking Error: Win32 error 126

does asar package all the files even dll files?

**Comment by develar** [comment]
Could you please provide project?
