### ISSUE TITLE
Non-default keychain for signing on OSX

### ISSUE THREAD

**Issue by claymcleod** [electron-userland/electron-builder#2209]
* **Version**: 19.37.2

* **Target**: Mac

Have you considered adding an option for a non-default keychain? Looks like electron-sign-osx does support this, but I don't see an option exposed through the command line application. This is needed for EV certs.

**Comment by develar** [comment]
Next version:

```
| `CSC_KEYCHAIN`| The keychain name. Used if `CSC_LINK` is not specified. Defaults to system default keychain.
```

**Comment by claymcleod** [comment]
Awesome, thanks @develar
