### ISSUE TITLE
Busted DTSDKName

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#2211]
* **Version**: electron-builder 1.7.9

* **Target**: macOS 10.13

`DTSDKName` is busted when building with electron-builder, i.e currently it outputs the following in `Info.plist`: 

```
macosx10.1010.10
```

**Comment by develar** [comment]
What do you mean? In the original Info.plist 

```
	<key>DTSDKName</key>
	<string>macosx10.1010.10</string>
```

So, electron-builder uses it as is.

**Comment by pronebird** [comment]
10.10 repeated twice. So weird.
