### ISSUE TITLE
[Feature request] Remove data on unsinstall any mac package or allow run script

### ISSUE THREAD

**Issue by Cherviakov** [electron-userland/electron-builder#2214]
* **Version**: 19.8.0

* **Target**: Linux, Mac, Windows

On windows there option to remove data on uninstall, on linux can add bash script, which will run
on deb package remove. But on mac there seems to be no way to remove data on unistnall till now
in all available package types. Can this be added for mac? Or maybe ability to run script on package
remove, like in linux?

**Comment by develar** [comment]
Provide uninstall action in your app or uninstall script. pkg theoretically can support it.
