### ISSUE TITLE
Error when using electron-builder 19.37.2 (win32 : ia32)

### ISSUE THREAD

**Issue by hikahidbiza** [electron-userland/electron-builder#2215]
Hello, Im having a problem when executing the command npm run dist ( aka build -w  ------- Please see the package section)
I have a windows machine 32bit, thanks for helping me out
Here is my complete log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ted\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@5.4.2
3 info using node@v8.6.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle Munshiiii@1.0.0~predist: Munshiiii@1.0.0
6 info lifecycle Munshiiii@1.0.0~dist: Munshiiii@1.0.0
7 verbose lifecycle Munshiiii@1.0.0~dist: unsafe-perm in lifecycle true
8 verbose lifecycle Munshiiii@1.0.0~dist: PATH: C:\Users\ted\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\ted\Desktop\RSM\node_modules\.bin;C:\oracle\product\10.2.0\db_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\MATLAB\R2009a\bin;C:\Program Files\MATLAB\R2009a\bin\win32;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Users\ted\AppData\Roaming\npm;C:\AppServ\Apache24\bin;C:\AppServ\php5;C:\AppServ\MySQL\bin;C:\oracle\product\10.2.0\db_1\bin
9 verbose lifecycle Munshiiii@1.0.0~dist: CWD: C:\Users\ted\Desktop\RSM
10 silly lifecycle Munshiiii@1.0.0~dist: Args: [ '/d /s /c', 'build -w' ]
11 silly lifecycle Munshiiii@1.0.0~dist: Returned: code: 4294967295  signal: null
12 info lifecycle Munshiiii@1.0.0~dist: Failed to exec dist script
13 verbose stack Error: Munshiiii@1.0.0 dist: `build -w`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ted\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ted\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid Munshiiii@1.0.0
15 verbose cwd C:\Users\ted\Desktop\RSM
16 verbose Windows_NT 6.1.7600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ted\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v8.6.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 4294967295
22 error Munshiiii@1.0.0 dist: `build -w`
22 error Exit status 4294967295
23 error Failed at the Munshiiii@1.0.0 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]

Here is my package.json:

{
  "name": "Munshiiii",
  "version": "1.0.0",
  "description": "This is a short Description of the project",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
	"dist": "build -w"
  },
  "author": "Hicham Dbiza",
  "license": "ISC",
  "devDependencies": {
    "electron": "1.7.8",
    "electron-prebuilt": "^1.4.13"
  },
  "dependencies": {
    "asar": "^0.13.0",
    "cradle": "^0.7.1",
    "fs": "0.0.1-security",
    "git": "^0.1.5",
    "jquery": "^3.2.1",
    "jsdom": "^11.3.0",
    "loke-ipc": "^1.0.5",
    "mongodb": "^2.2.33",
    "node-couchdb": "^1.2.0",
    "pouchdb": "^6.3.4",
    "pouchdb-replication-stream": "^1.2.9",
    "scanner.js": "^1.0.0"
  },
  "build":{
	"appId": "com.hicham.dbiza.faizan",
	"win":{
		"target": "nsis",
		"icon": "build/Munshiiii.ico"
	}
  }
}

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.
