### ISSUE TITLE
Delta updates for NSIS target (not only nsis-web target)

### ISSUE THREAD

**Issue by SteveJay7** [electron-userland/electron-builder#2217]
I am using electron-builder 19.37.2 

I would like to have delta updates for my nsis (win x64) installer, so I added "differentialPackage": true to my nsis options.

But still, only the full version is being created and published.
Although it seems that adding this option triggered some different code because the size of the installers exe file changed from 60MB to 63MB (without any code changes).

I would appreciate any help in finding the issue why no delta file is being created.

Thanks!

**Comment by develar** [comment]
Supported only for nsis-web target for now.

**Comment by SteveJay7** [comment]
thanks for the quick response.

I changed target to nsis-web. now the web-installer adn the 7z files are created, but the 7z files are still all 64MB.

is there something wrong in my config?

`   "asar": true,
    "win": {
      "icon": "build/icons/icon.ico",
      "target": "nsis-web"
    },
    "nsisWeb": {
      "installerIcon": "build/icons/icon.ico",
      "differentialPackage": true,
      "artifactName": "${productName}_Setup_${version}.${ext}"
    },`

**Comment by BethanyBerkowitz** [comment]
@develar my team is also quite interested in differential updates for the nsis target! I'll be making a donation shortly.

**Comment by develar** [comment]
@BethanyBerkowitz Status update — I still cannot finish one feature, but work on this issue will be started this week. Sorry for delay.

**Comment by BethanyBerkowitz** [comment]
@develar Will I be getting an nsis Christmas present or coal in my stocking? 🎄 🎅

**Comment by jan-j** [comment]
@develar Is this feature still work in progress? I've tried it myself with latest electron-builder and electron-updater, but it seems like it only works with __NSIS_DIFFERENTIAL_UPDATE__ env variable set to true and then it still misses *.blockMap.json file which is not generated (at least without debug env var).

BTW thank you for building great Electron tools

**Comment by Dorkside** [comment]
Any update on this feature? Nsis-web target is OK for now, but doesn't emit the correct progress events while downloading.
Progress works fine with nsis target, but doesn't do differential, so isn't optimal.

**Comment by olleweb** [comment]
@develar Does delta updates work for NSIS target now? I have set `differentialPackage` to `true` for nsis but I still get "Cannot download differentially, fallback to full download". It works as expected when using the nsis-web installer.
