### ISSUE TITLE
Clarification: Setting auth headers for Electron Updater's update feed

### ISSUE THREAD

**Issue by VerteDinde** [electron-userland/electron-builder#2223]
* **Version**:  Electron Builder 19.27.7
* **Version**: Electron Updater 2.10.1
* **Target**: NSIS

I just wanted some clarification around how to use electron-updater's setFeedUrl. I know that this is called by the updater and the user should not call it - however, we have authentication headers that we are passing into this function on our Mac build. 

Is there a way to use the auto-updater when authentication is required to get to the updating URL's end point?

Code: 
```
  if (platform === 'win32') {
    addEventHandlers();

    // this is how it's done for Mac
    const feedUrl = getFeedUrl();
    const feedHeaders = getFeedHeaders(jwt);

    // Is there a way to do the below with electron-updater?
    try {
      autoUpdater.setFeedURL(feedUrl, feedHeaders);
    } catch (error) {
      logger.error('Updater set feed URL error', { error, feedUrl });
      return;
    }

    autoUpdater.checkForUpdates();
    stopCheckingForUpdates();
}
```

This is an excellent repo, and I'm happy to add a PR for documenting how this is done/a tutorial for future people, so you don't have to answer this again. Thanks Develar!

**Comment by develar** [comment]
Please use `autoUpdater.requestHeaders` to set additional headers.
