### ISSUE TITLE
Warning: "token" specified in the github publish options in Visual Studio Team Services

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2226]
```
Warning: "token" specified in the github publish options. It should be used only for [setFeedURL](module:electron-updater/out/AppUpdater.AppUpdater+setFeedURL).
```
I'm receiving this warning because I can't set GH_TOKEN in`environment variable` in VSTS (Visual Studio Team Services) CI, so I send this encrypted via command to yarn like that:
```js
yarn build -c.win.certificatePassword=$(CSC_KEY_PASSWORD) -c.win.publish.token=$(GH_TOKEN) --publish always
```

![image](https://user-images.githubusercontent.com/5435657/32003219-2ed6196c-b97d-11e7-806b-c9e82c4e1fa0.png)

Should I ignore this warning or I need disable it?

---

* **Electron-updater - Version**: 2.14.1
* **Electron-builder - Version**: 19.39.0
* **Target**:  Windows | nsis-web

**Comment by develar** [comment]
Since VSTS is a MS product, probably you are right and env is not supported.

> Should I ignore this warning or I need disable it?

Please check that generated app-update.yml in the resources doesn't contain your token.

**Comment by marceloavf** [comment]
I checked `app-update.yml` inside `build\win-unpacked\resources` and it contains my token and others information about my _github_ owner and repository, what should I do?

**Comment by develar** [comment]
So, please set env in your script instead of `-c.win.publish.token` using `set` command`. Or `cross-env`. Token must be not exposed.

**Comment by etykira** [comment]
> So, please set env in your script instead of `-c.win.publish.token` using `set` command. Or `cross-env`. Token must be not exposed.

I tried using cross-env but my token is still showed in my app-update.yml.
