### ISSUE TITLE
Can't publish built Win from a Mac for GitHub

### ISSUE THREAD

**Issue by iwiedenm** [electron-userland/electron-builder#2229]
electron-builder: 19.41.1
electron-simple-updater: 1.2.2
electron-simple-publisher: 0.4.7
building on Mac for Mac and Windows

If I run:
`./node_modules/.bin/publish --transport-token <GH token here>`
It publishes my Mac apps perfectly.

I want to publish Win, as well. So I installed docker and used it to build my app for Win by...
1. `cd` to app location via terminal
2. run docker container listed here https://www.electron.build/multi-platform-build#docker

```
docker run --rm -ti \
  --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
  --env ELECTRON_CACHE="/root/.cache/electron" \
  --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
  -v ${PWD}:/project \
  -v ${PWD##*/}-node-modules:/project/node_modules \
  -v ~/.cache/electron:/root/.cache/electron \
  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
  electronuserland/builder:wine
```

3. built Win by running `./node_modules/.bin/electron-builder --win --x64`
Also, my build target for win in package.json is NSIS

When I run `./node_modules/.bin/publish ./publisher.json win32-x64` from the terminal with docker I get errors:

```
root@57875d98d4a3:/project# ./node_modules/.bin/publish win32-x64
File /project/dist/win/Somiibo Setup 0.0.1.exe doesn't exists. You can try to check if:
 - electron-builder successfully made a build
 - electron-builder and electron-simple-publisher are up to date
 - if nothing helps please create a new github issue. Don't forget to include electron-builder version to the bug report.
```

Although I get that error, I still see a file called "Somiibo Setup 0.0.1.exe" but it's not in a folder called `dist/win/`, it's just in `dist/`. Why is it looking in dist/win? 

Thanks for the help!

**Comment by develar** [comment]
Why do you use electron-simple-publisher instead of built-in publishing?

> Why is it looking in dist/win?

It is electron-simple-publisher issue, I guess.
