### ISSUE TITLE
How to disable downgrading of app ?

### ISSUE THREAD

**Issue by poojas2288** [electron-userland/electron-builder#2230]
* **Version**: 
19.5.1

* **Target**: 
nsis, dmg

I am able to manually install an older version of app, whereas it should be disabled.

**Example** : 
If I have my app installed with version 1.3.
If I launch my app installer with version 1.2, then 1.2 gets installed. However, downgrade should not be possible since I already have a higher version of app already installed.

Please let me know if there exists any option to disable downgrade while installation.

**NOTE** - I know there is downgrade related option in auto-updater, but I am not wanting that. I need something within electron-builder itself.

**Comment by develar** [comment]
It is not possible for DMG. But possible to implement for NSIS. PR or donation welcome.

**Comment by Bhanuka94** [comment]
Hello @develar, do you have a sample NSIS implementation to prevent downgrading the electron app?
