### ISSUE TITLE
electron-builder times out on Travis CI

### ISSUE THREAD

**Issue by GitSquared** [electron-userland/electron-builder#2231]
* **Version**: 19.41.0 (latest)

* **Target**: Windows Portable (x64 & ia32)

I have a Travis setup that runs electron-builder on Docker (just like the [recommended Travis setup](https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml)).

This setup used to work until a few days ago when it began randomly crashing (1 out of 2 builds or something) because electron-builder did not produce any output for 10min. This happens in the `wine: Pulling from electronuserland/builder` step.

Here's a failing build log:
https://travis-ci.org/GitSquared/edex-ui/builds/293077172
And one that passed (using the same package.json and travis.yml configuration):
https://travis-ci.org/GitSquared/edex-ui/builds/292594760

Should i just make Travis wait longer? In working builds the long-lasting step is the download of nsis resources, the pull on the wine repo thingy usually runs for less than a minute.

**UPDATE**: If the pulling step mentioned above is updating the Docker image, this might have nothing to do with electron-builder:
https://www.traviscistatus.com/incidents/v4jnp6nkgzqx
I'll keep an eye on this one.

**Comment by GitSquared** [comment]
Closed : Issue between Travis and Docker Hub.

https://github.com/docker/hub-feedback/issues/1225

**Comment by develar** [comment]
Anyway wine image now has wine-home in a separate layer.
