### ISSUE TITLE
Release not uploaded to GitHub

### ISSUE THREAD

**Issue by islemaster** [electron-userland/electron-builder#2234]
* **Version**: 19.37.2

* **Target**: Windows, OSX, Linux

I'm working on a new-ish project at https://github.com/code-dot-org/browser, building for Windows on Appveyor, and Linux and OSX on Travis.

I'm not sure what I'm doing wrong, but it's fairly common for my releases to be missing some or all of the build artifacts from these CI builds - and the build output is very unhelpful in this respect.  For example, [here's the appveyor build output](https://ci.appveyor.com/project/islemaster/browser) for my [latest release](https://github.com/code-dot-org/browser/releases/tag/v0.0.7) which I tried creating before any of the builds finished (I've since learned this is not the right way to do it).

```
Publishing to Github (owner: code-dot-org, project: browser, version: 0.0.7)
Uploading code-dot-org-browser-setup-0.0.7.exe to GitHub
Warning: Release with tag v0.0.7 already exists
Warning: Release with tag v0.0.7 doesn't exist and is not created, artifact code-dot-org-browser-setup-0.0.7.exe is not published
```

So I'm not sure whether the build is unhappy that the release _does_ exist, or thinks it _doesn't_.

My [last release](https://github.com/code-dot-org/browser/releases/tag/v0.0.6) got its Windows and OSX artifacts, but not its Linux artifacts, and I did not create the release before builds finished.  Output from the respective build containers:

[Windows/Appveyor:](https://ci.appveyor.com/project/islemaster/browser/build/0.0.27)
```
Publishing to Github (owner: code-dot-org, project: browser, version: 0.0.6)
Uploading code-dot-org-browser-setup-0.0.6.exe to GitHub
Release with tag v0.0.6 doesn't exist, creating one
```
[OSX/Travis](https://travis-ci.org/code-dot-org/browser/jobs/292348346)
```
Publishing to Github (owner: code-dot-org, project: browser, version: 0.0.6)
Uploading code-dot-org-browser-0.0.6.dmg to GitHub
Uploading code-dot-org-browser-0.0.6-mac.zip to GitHub
Uploading latest-mac.json to GitHub
```
[Linux/Travis](https://travis-ci.org/code-dot-org/browser/jobs/292348347)
```
Publishing to Github (owner: code-dot-org, project: browser, version: 0.0.6)
Uploading code-dot-org-browser-0.0.6-x86_64.AppImage to GitHub
Warning: Release with tag v0.0.6 already exists
Warning: Release with tag v0.0.6 doesn't exist and is not created, artifact code-dot-org-browser-0.0.6-x86_64.AppImage is not published
Uploading code-dot-org-browser_0.0.6_amd64.deb to GitHub
Warning: Release with tag v0.0.6 doesn't exist and is not created, artifact code-dot-org-browser_0.0.6_amd64.deb is not published
Warning: Release with tag v0.0.6 doesn't exist and is not created, artifact latest-linux.yml is not published
```

Am I missing something really obvious?  If we're going to use separate containers for builds, they _must_ be able to deal with not being the first container done, right?  Can we at least update the build output to be more helpful?

**Comment by develar** [comment]
Is `--publish=always` is specified?

>  Can we at least update the build output to be more helpful?

Set env `DEBUG=electron-builder`.

**Comment by develar** [comment]
Message is more clear in the 19.45.3.
