### ISSUE TITLE
Auto-updater: switch code signing certificates

### ISSUE THREAD

**Issue by MaKleSoft** [electron-userland/electron-builder#2243]
We're thinking about switching the provider for our code signing certificates but are worried that this will cause problems when pushing updates to users through auto-update. Is there a way to migrate code signing certificates without having people download and install the app again manually?

**Comment by develar** [comment]
macOS — cannot advice, Squirrel.Mac is used under the hood.
Windows — set [publisherName](https://www.electron.build/configuration/win#WindowsConfiguration-publisherName) to array of your old name and new name. `["old", "new"]`

**Comment by MaKleSoft** [comment]
@develar thanks for the info! But how does this work exactly - when I publish a new version with the additional publisher name, should that version be signed with the old or the new certificate?

I'm a big fan of this project but tbh the documentation can be lacking sometimes. Maybe it would be a good idea to create an F.A.Q. section for things like this?

**Comment by matheussige** [comment]
@MaKleSoft were you able to solve this? My certificate changed before we could update publisherName on our config. Now, we're not being able to update our user's installed software

**Comment by MaKleSoft** [comment]
@matheussige We ended up renewing the existing certificate so we never actually had to do this. But my understanding is that once your old certificate expires, there is no way to migrate existing users to a new one, at least not through auto-updates.

**Comment by damianobarbati** [comment]
@develar my app auto-updates but I'm having 2 different versions of app with different publish name in Windows Control Panel.
Setting `publisherName` is ignored and the app is always installed under a publisher name equal to the common name in my EV cert.
