### ISSUE TITLE
Develar's local machine path in appImage target code

### ISSUE THREAD

**Issue by KararTY** [electron-userland/electron-builder#2244]
```ts
env: {
  PATH: `${vendorToolDir}:"/Users/develar/Library/Caches/electron-builder/
  linux-tools/linux-tools-mac-10.12.3/bin:${process.env.PATH}`
}
```
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/targets/appImage.ts#L109

@develar, your local machine path is here for some reason. Was this a mistake?

**Comment by develar** [comment]
@KararTY it is mistake, but doesn't lead to any error.
