### ISSUE TITLE
Translate documentation

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2248]
## Choose a language

Default: 

* **[English](https://www.electron.build/)** (en)

Translations:
- [ ] **Brazilian Portuguese** (pt-br) - WIP

---

Create translation for international languages, since it uses `Gitbook`, this should be the default method:
https://toolchain.gitbook.com/languages.html

E.g.: 
`electron-builder/docs/pt-br/`

**Comment by develar** [comment]
Address will be pr.electron.builder. Are you sure that we need translation? English for me also not native Lang, but don’t even think to translate docs to ru oder Deutsch.

**Comment by develar** [comment]
In general, 👍 I will make required changes to make translation possible.

**Comment by marceloavf** [comment]
I often receive some question from brazilian electron community, figure out that they do not understand some things because of the language, so for me it's good to improve my english and also help those who are starting.
