### ISSUE TITLE
Plugin not found, cannot call nsProcess::_FindProcess

### ISSUE THREAD

**Issue by osnoser1** [electron-userland/electron-builder#2249]
* **Version**: 19.43.0

* **Target**: Electron app.

This error occurs when executing:

![image](https://user-images.githubusercontent.com/1179744/32227398-afd34c26-be21-11e7-9436-3a98e384f1d6.png)
![image](https://user-images.githubusercontent.com/1179744/32227486-f5c73440-be21-11e7-895e-3e49a8b011c8.png)

I guess it's related to special characters.

Beforehand thank you very much.

**Comment by develar** [comment]
Duplicates #2197 please workaround in the issue.
