### ISSUE TITLE
"Custom NSIS script: LangString installing" Error

### ISSUE THREAD

**Issue by q569608465** [electron-userland/electron-builder#2251]
* **Version**: 
19.27.7

* **Target**: 
windows 7
node v6.11.5
npm  v3.10.10

I want to modify the installation prompt, I can't find the configuration in the document.
Then I set env DEBUG=electron-builder,electron-builder:*  and attach log of the terminal output, I found the script : "LangString installing 1033 "Installing, please wait..."",
![image](https://user-images.githubusercontent.com/12602541/32259462-a68c8cf6-befb-11e7-921a-3885f5d43e9b.png)

finally, I found "Custom NSIS script" in the electron-builder document, but I get Errors when I run "electron-builder":
![image](https://user-images.githubusercontent.com/12602541/32258973-81921194-bef8-11e7-8821-67acb654d970.png)

I was in a quandar，if you have an answer , please tell me ,thanks!

**Comment by q569608465** [comment]
I've found another way to do what I want： modify the messages.yml

**Comment by develar** [comment]
Yes, for now no user way to set custom translation.
