### ISSUE TITLE
Unable to find a valid app

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-builder#2254]
* **Version**: 19.43.2
* **electron-updater**: v2.15.0
* **Target**: nsis

This issue is the result of upgrading to v19.43.2. In  v19.42.2 everything worked as expected. All source code is available [here](https://github.com/FantasticFiasco/searchlight).

Long story short, when I run `electron-builder --dir -c.compression=store -c.mac.identity=null` and starting the exe from the dist folder, I get the error message `Unable to find a valid app`.

**Comment by develar** [comment]
Already fixed in the 19.43.4.
