### ISSUE TITLE
Can't publish -- TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by brandoncc** [electron-userland/electron-builder#2256]
* **Version**:  19.34.1

* **Target**: MacOS

I can build, but I can't publish. It gets to the point of saying it is going to publish and then tells me a path is undefined but should be a string. Another odd thing is that my laptop goes into overdrive (fan spins up) during the time between it saying it is going to publish and the error being displayed. I am thinking there may be an infinite loop or something happening.

I have attached my error log with `DEBUG=electron-builder`: [error.log](https://github.com/electron-userland/electron-builder/files/1436647/error.log)

Thanks in advance.

**Comment by develar** [comment]
Please try latest version.

**Comment by brandoncc** [comment]
That was exactly the problem, sorry for the trouble! You guys move fast, I actually thought i was on the newest version because that was the newest the last time I had checked. Lesson learned 👍
