### ISSUE TITLE
Empty  squirrel-windows/temp folder

### ISSUE THREAD

**Issue by thre-isdd** [electron-userland/electron-builder#2257]
* **Version**:   19.43.0
* **Target**:  win server 2016, x64

Trying to build win squirrel application,  But after "Building Squirrel.Windows for arch x64" message I got this error:
Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\BuildAgent2\work\deb57f9ceb2f2d58\dist\squirrel-windows\.temp\Update.exe'
Folder .temp is empty.  What cold be wrong?

**Comment by develar** [comment]
Is electron-builder-squirrel-windows  updated to 19.43.0?

**Comment by thre-isdd** [comment]
Yep, it's version 19.43.0.
