### ISSUE TITLE
extraResources does not copy regular files without "from" and "to"

### ISSUE THREAD

**Issue by ortix** [electron-userland/electron-builder#2259]
* **Version**: 19.43.3

* **Target**: darwin:x64

When I build my application the `extraResources` command does not copy regular files to the `Resources` folder. Only if I use `from` and `to` does it pick up regular files. This is not expected behaviour.

**Comment by lzkelley** [comment]
Is this also fixed by https://github.com/electron-userland/electron-builder/commit/d0c6c04fbf82ee759c8b0f8ccb112e60297c969e, i.e. https://github.com/electron-userland/electron-builder/issues/2265?
