### ISSUE TITLE
Why is latest-mac.json being created?

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2261]
* **Version**: 
"electron-builder": "19.41.0",
"electron-publisher-s3": "19.30.0",
"electron-updater": "2.10.0"

* **Target**: 
Mac & Windows

When I run the publish command with the following config - 
```
"publish": {
      "provider": "s3",
      "bucket": "mybucket",
      "path": "dev",
      "acl": "public-read"
    }
```
I see `latest-mac.json `is being created with the following data - 
```
"version": x.x.x,
"releaseData": some date,
"url": "url pointing to the app's zip in s3 bucket"
```

What is the significance of this `latest-mac.json` file. 
Is it safe to delete from s3?
Is it necessary for auto update to work?
Thoughts?

**Comment by develar** [comment]
Backward compatibility with electron-updater 1.x

Upcoming electron-builder 19.44.0 will offer you an option to disable this file generation:

```ts
/**
   * The electron-updater compatibility semver range. e.g. `>= 2.16`, `>=1.0.0`.
   *
   * @default >=1.0.0
   *
   * 1.0.0 latest-mac.json
   * 2.15.0 path
   * 2.16.0 files
   */
  readonly electronUpdaterCompatibility?: string | null
```

**Comment by Ajeey** [comment]
Thanks for the clarification @develar
