### ISSUE TITLE
Losing shortcuts

### ISSUE THREAD

**Issue by avengerweb** [electron-userland/electron-builder#2266]
* **Version**:  19.43.3

* **Target**: win32 (x64) - nsis

Lose shortcuts on win. When I build with old version 19.26.3, works perfectly.

**Comment by develar** [comment]
Default configuration?

**Comment by avengerweb** [comment]
Ok, is not update problem. When I build using win machine it create icons, today I build using my mac, and shortcut not appears (

**Comment by avengerweb** [comment]
> {
>   "name": "sirus-open-launcher",
>   "productName": "Sirus Launcher",
>   "version": "1.0.2-alpha.19",
>   "author": "AvengerWeb <avengerweb@yandex.ru>",
>   "description": "Лаунчер для игрового сервера WoW Sirus.su",
>   "license": null,
>   "main": "./dist/electron/main.js",
>   "scripts": {
>     "build": "node .electron-vue/build.js",
>     "build:darwin": "cross-env BUILD_TARGET=darwin node .electron-vue/build.js",
>     "build:linux": "cross-env BUILD_TARGET=linux node .electron-vue/build.js",
>     "build:mas": "cross-env BUILD_TARGET=mas node .electron-vue/build.js",
>     "build:win32": "cross-env BUILD_TARGET=win32 node .electron-vue/build.js",
>     "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
>     "build:web": "cross-env BUILD_TARGET=web node .electron-vue/build.js",
>     "dev": "node .electron-vue/dev-runner.js",
>     "lint": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src",
>     "lint:fix": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src",
>     "pack": "npm run pack:main && npm run pack:renderer",
>     "pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
>     "pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
>     "postinstall": "npm run lint:fix",
>     "release:win": "npm run build:win32 && electron-builder --win --ia32 --x64",
>     "release:linux": "npm run build:win32 && electron-builder --linux --x64"
>   },
>   "build": {
>     "appId": "su.sirus.launcher",
>     "artifactName": "SirusLauncher-${version}.${ext}",
>     "extraResources": [
>       {
>         "from": "icons/",
>         "to": "icons/"
>       }
>     ],
>     "directories": {
>       "output": "build"
>     },
>     "linux": {
>       "executableName": "siruslauncher",
>       "target": "AppImage",
>       "icon": "icons/linux/"
>     },
>     "win": {
>       "target": "NSIS",
>       "icon": "icons/icon"
>     },
>     "publish": [
>       {
>         "provider": "generic",
>         "url": "https://sirus.su/launcher/"
>       }
>     ]
>   },
>   "dependencies": {
>     "axios": "^0.16.1",
>     "electron-json-storage": "3.1.*",
>     "electron-log": "2.2.7",
>     "electron-updater": "^2.15.0",
>     "fs-extra": "^4.0.2",
>     "materialize-css": "^0.99.0",
>     "md5-file": "^3.2.3",
>     "node-machine-id": "^1.1.9",
>     "node-notifier": "^5.1.2",
>     "rimraf": "^2.6.2",
>     "vue": "^2.5.2",
>     "vue-electron": "^1.0.6",
>     "vue-router": "^2.8.1",
>     "vuex": "^2.5.0",
>     "webtorrent": "^0.98.20"
>   },
>   "devDependencies": {
>     "babel-core": "^6.22.1",
>     "babel-eslint": "^7.0.0",
>     "babel-loader": "^7.0.0",
>     "babel-plugin-transform-runtime": "^6.22.0",
>     "babel-preset-env": "^1.6.1",
>     "babel-preset-stage-0": "^6.5.0",
>     "babel-register": "^6.2.0",
>     "babili-webpack-plugin": "^0.1.1",
>     "cfonts": "^1.1.3",
>     "chalk": "^1.1.3",
>     "copy-webpack-plugin": "^4.2.0",
>     "cross-env": "^5.1.0",
>     "css-loader": "^0.28.7",
>     "del": "^2.2.1",
>     "devtron": "^1.1.0",
>     "electron": "1.7.9",
>     "electron-builder": "^19.40.0",
>     "electron-debug": "^1.1.0",
>     "electron-devtools-installer": "^2.2.1",
>     "electron-packager": "^8.5.0",
>     "eslint": "^3.13.1",
>     "eslint-config-standard": "^10.2.1",
>     "eslint-friendly-formatter": "^3.0.0",
>     "eslint-loader": "^1.3.0",
>     "eslint-plugin-html": "^2.0.0",
>     "eslint-plugin-import": "^2.8.0",
>     "eslint-plugin-node": "^4.2.2",
>     "eslint-plugin-promise": "^3.6.0",
>     "eslint-plugin-standard": "^3.0.1",
>     "extract-text-webpack-plugin": "^2.0.0-beta.4",
>     "file-loader": "^0.11.1",
>     "html-webpack-plugin": "^2.16.1",
>     "json-loader": "^0.5.4",
>     "multispinner": "^0.2.1",
>     "node-sass": "^4.5.3",
>     "sass-loader": "^6.0.6",
>     "style-loader": "^0.18.1",
>     "url-loader": "^0.5.7",
>     "vue-html-loader": "^1.2.2",
>     "vue-loader": "^12.2.1",
>     "vue-style-loader": "^3.0.3",
>     "vue-template-compiler": "^2.5.2",
>     "webpack": "^2.2.1",
>     "webpack-dev-server": "^2.9.3",
>     "webpack-hot-middleware": "^2.20.0"
>   }
> }
>

**Comment by avengerweb** [comment]
ok, finally I build in 19.26.3 and it works... with shortcuts

**Comment by avengerweb** [comment]
for example: Build with new version https://sirus.su/launcher/SirusLauncher-1.0.2-alpha.19.exe
and build with old version of electron-builder: https://sirus.su/launcher/SirusLauncher-1.0.2-alpha.20.exe

**Comment by develar** [comment]
если возможно предоставить тестовый проект — я проверю завтра.

**Comment by avengerweb** [comment]
@develar, will try to do it today.
