### ISSUE TITLE
Windows code signing on Mac OSX with Paralles installed

### ISSUE THREAD

**Issue by aytek** [electron-userland/electron-builder#2268]
* **Version**: 19.45.0

* **Target**: Mac

I have Paralles Desktop Pro installed with an EV certificate on my Mac (with a USB dongle plugged in)
When trying to sign the win build on Mac, it always fails. I see the following errors on the command line.
```
Error: Exit code: 2. Command failed: prlctl exec {**user_id**} --current-user \\Mac\Host\\Users\user\Library\Caches\electron-builder\winCodeSign\winCodeSign-1.9.0\windows-10\x64\signtool.exe sign /t http://timestamp.globalsign.com/?signature=sha2 /sha1 **SHA1_CODE** /s **Store Name** /d **Product Name** /du **website_url** \\Mac\Host\\Users\user\electron\ft\release\win-unpacked\file_name.exe

    at /Users/user/electron/ft/node_modules/builder-util/src/util.ts:108:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

...
```
When trying to sign the build on Windows it signs successfully but on Mac it always fail. 
Here is my build script:

```
    "nsis": {
      "perMachine": true
    },
    "win": {
      "target": [
        "nsis"
      ],
      "certificateSubjectName": "My Certificate Subject Name",
      "timeStampServer": "http://timestamp.globalsign.com/?signature=sha2",
      "certificatePassword": "PASSWORD"
    },
```

And here is the build command
`npm run build && build --win --ia32 --x64`

Could be related with my Paralles configuration?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output. If you want privacy — send me direct message in the Slack.

**Comment by develar** [comment]
> I have Paralles Desktop Pro installed with an EV certificate on my Mac (with a USB dongle plugged in)

Please ensure that this dongle device is connected not your mac, but to virtual machine.

**Comment by mavisoft** [comment]
@develar Please check your Slack. I have sent them 2 days ago. Thanks.

**Comment by aytek** [comment]
@develar I have sent them 2 days ago, please check your Slack. Thanks.

**Comment by develar** [comment]
@aytek I don't see direct message from you in the Slack (http://electron-builder.slack.com/).

**Comment by aytek** [comment]
@develar Okay I sent it to the correct Slack. Sorry.

**Comment by rjb8682** [comment]
Did this ever go anywhere? Running into this issue as well...

**Comment by johnryan** [comment]
@aytek did you ever figure this out?

**Comment by johnryan** [comment]
@rjb8682 did you ever get your EV signing working?

**Comment by rjb8682** [comment]
@johnryan I believe we did! And to be honest, for us it was just updating electron-builder and making sure parallels was running so the signing could be automatically started. 

Also making sure to have the pro license for parallels instead of the lowest one. If you don't have pro or higher, the library to talk between the mac and parallels isn't available

**Comment by johnryan** [comment]
@rjb8682 thanks for the tip, I think i've done all that, including upgrading parallels. The `Exit code: 2. Command failed: prlctl exec ...` error is pretty vague...i might just try to reinstall parallels / windows 10.

**Comment by rjb8682** [comment]
@johnryan Yeah, sorry it wasn't much help! Hope you can figure it out, though

**Comment by johnryan** [comment]
Thanks to @develar for helping me debug...In the end my particular problem was that my parallels wasn't configured to access my windows drives correctly...here's a screenshot of the VM sharing configuration that worked:

<img width="812" alt="screen shot 2018-02-09 at 10 23 08 am" src="https://user-images.githubusercontent.com/416564/36034816-3ea7f360-0d83-11e8-80ac-ffa8240d69d1.png">

**Comment by develar** [comment]
In addition, please note also, that "Share Mac user folders with Windows" **must be** not** checked.

**Comment by mobitar** [comment]
Such a cool feature! I just tested this using the free version of Parallels and it works flawlessly.

**Comment by damianobarbati** [comment]
@develar I'm still getting the following:
```
  • ensure that 'Share folders' is set to 'All Disks', see https://goo.gl/E6XphP
  • ensure that 'Share folders' is set to 'All Disks', see https://goo.gl/E6XphP
Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: Exit code: 255. Command failed: prlctl exec {aac0be65-f135-4bfc-b508-2cada07b8201} --current-user \\Mac\Host\\Users\damiano\Library\Caches\electron-builder\winCodeSign\winCodeSign-2.0.0\windows-10\x64\makeappx.exe pack /o /f \\Mac\Host\\Users\damiano\Desktop\tav-client\dist\__appx-x64\mapping.txt /p \\Mac\Host\\Users\damiano\Desktop\tav-client\dist\TAV-6.2.5.appx /nc
```

**Comment by damianobarbati** [comment]
Furthermore: is this parallels builiding required if I'm not trying to sign the .appx (just store)?

**Comment by adunndevster** [comment]
Hmmm...
I have parallels pro installed
I'm using the settings above
Am using electron 4.1.0 and electron-builder 20.38.5
I'm running paralles, and have my EV token device plugged in.
I see that it is reading it fin in windows using SafeNet Auth Client

I'm getting this error: Please ensure that your are logged in "Windows 10" parallels virtual machine

Has anyone else seen this? Thanks for any help!

**Comment by Nealsoni00** [comment]
Also experiencing the same issue. I have the exact settings specified above by @johnryan. 
I am using:
Electron-builder Version: 21.2.0
Electron Version: v6.0.4
Parallels Desktop Pro Version 15.1.2 (47123)

Any advice would be greatly appreciated, Thanks!

**Comment by johnryan** [comment]
@Nealsoni00 fwiw I switched to the jsign method in the docs a while back.

**Comment by klishevich** [comment]
Have the issue. I am using:

- macOS Catalina: 10.15.2
- Parallels Desktop 15 for Mac Home Edition: Version 15.1.2 (47123)
- electron: 6.1.4
- electron-builder: 21.2.0

Changing Parallels preferences does not help. Switched to Windows for signing windows code :(

**Comment by zdQAQ** [comment]
@klishevich try upgrade electron-builder to a higher version. such as 22.2.0. 

It's worked for me.

**Comment by 447491480** [comment]
> Thanks to @develar for helping me debug...In the end my particular problem was that my parallels wasn't configured to access my windows drives correctly...here's a screenshot of the VM sharing configuration that worked:
> 
> <img alt="screen shot 2018-02-09 at 10 23 08 am" width="812" src="https://user-images.githubusercontent.com/416564/36034816-3ea7f360-0d83-11e8-80ac-ffa8240d69d1.png">
<img width="629" alt="image" src="https://github.com/electron-userland/electron-builder/assets/8955429/b9680176-7dac-4692-9b13-b2913af8e8ea">

there is no "All Disks" options now, in pd 18 business edition.  what can i do?

**Comment by Stapxs** [comment]
@447491480
Hello, I also encountered the same problem. You can turn on this option to achieve the same effect.

- Select the ```Manage folder...``` and then select your mac.
  <img width="1283" alt="image" src="https://github.com/electron-userland/electron-builder/assets/42486439/53de61ec-55d6-4590-8091-67985dd036b3">

In this way, you can access all Mac files in Windows, which is the same as the options answered above.
<img width="831" alt="image" src="https://github.com/electron-userland/electron-builder/assets/42486439/74797fe3-f1ca-45ab-8086-d145853961d9">
