### ISSUE TITLE
How to use asar contents without extracting that ?

### ISSUE THREAD

**Issue by bhavin00** [electron-userland/electron-builder#2271]
How to use asar contents without extracting that :---

In sample electron repo by electron community, They use in main.js file like following:-
e
mainWindow.loadURL(url.format({
  pathname: path.join(__dirname, 'index.html'),
   protocol: 'file:',
  slashes: true
   }))

and that works perfectly fine after build.. But when I use path.join in another function like:-

//my code
const { spawn } = require('child_process');

const subprocess = spawn(process.argv[0], [path.join('app.js')], {
  detached: true,
  stdio: 'ignore'
});

subprocess.unref();

it works in electron .

But after build it will not work because It goes to find app.js file inasar file.. How to solve that and use like elecrron community use in frist code sample ?

**Comment by develar** [comment]
For spawn, you need to unpack such files. Use asarUnpack (https://www.electron.build/configuration/configuration).
