### ISSUE TITLE
asar.unpacked errors when target is (wix) MSI installer

### ISSUE THREAD

**Issue by saifelse** [electron-userland/electron-builder#2272]
* **Version**:  19.45.0
* **Target**: Windows MSI

Problematic node module (`yarn add trash`): https://github.com/sindresorhus/trash

Relevant part of package.json:
```
  "scripts": {
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder"
  },
  "build": {
    "win": {
      "target": "msi"
    },
    "msi": {
      "oneClick": true,
      "perMachine": true
    }
  }
```

Build script:
```
FLAGS='DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_'

docker run --rm -ti \
  --env-file <(env | grep -iE "${FLAGS}") \
  --env ELECTRON_CACHE="/root/.cache/electron" \
  --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
  --env DEBUG="electron-builder,electron-builder:*" \
  -v ${PWD}:/project \
  -v ${PWD##*/}-node-modules:/project/node_modules \
  -v ~/.cache/electron:/root/.cache/electron \
  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
  electronuserland/builder:wine \
  /bin/bash -c "yarn && yarn dist --win"
```

First error that occurs:
```
Z:\project\dist\__msi-temp-x64\project.wxs(60) : error CNDL0027 : The Directory/@Name attribute's value 'APPLICATIONFOLDER:\resources/app.asar.unpacked/node_modules/trash\' contains a invalid filename 'resources/app.asar.unpacked/node_modules/trash'. Legal filenames contain no more than 260 characters and must contain at least one non-period character. Any character except for the follow may be used: \ ? | > < : / * ".
```

It looks as though forward slashes are still being when backslashes are expected. Let me know if there is anything else I can provide.

**Comment by readme42** [comment]
I also get a lot of 

C:\Users\...\packages\__msi-temp-x64\project.wxs(259) : error CNDL1147 : Backslash terminate the Component/@Directory attribute's inline directory value 'resources\app.asar.unpacked\node_modules\...'. A backslash ensures a directory name will not be mistaken for a directory reference.

**Comment by vinnymac** [comment]
When building on macOS High Sierra today with a similar msi config I received the same `CNDL0027` errors.

**Comment by vinnymac** [comment]
@saifelse @readme42 I was actually able to fix my similar error above. All I had to do was remove it from the build process by adding this `"!node_modules/spawn-rx"` to the list of files allowed in my build. I don't need spawn-rx at runtime personally. So if you are able to exclude any of these dependencies that are giving you trouble it might help. If you still need them at runtime I am not sure what we can do at the moment, but hopefully someone figures out why the `project.wxs` file includes these paths that give wix trouble.
