### ISSUE TITLE
 Release with tag doesn't exist and is not created

### ISSUE THREAD

**Issue by mobitar** [electron-userland/electron-builder#2275]
This is not a very high priority issue. But thought I'd share some behavior I'm seeing. 

If I already have a release on GitHub (pre-release in this case), and then I run `npm run release` (`electron-builder -mwl --x64 --ia32`), I see these two conflicting messages:

⚠️  Release with tag v2.0.3 already exists
⚠️  Release with tag v2.0.3 doesn't exist and is not created, artifact app-2.0.3-x86_64.AppImage is not published

First it says it already exists, then it says it doesn't exist and is not created. Perhaps just the messaging needs to be updated? But in any case, is there a way to overwrite existing artifacts on release?

*electron-builder 19.45.0*

**Comment by develar** [comment]
> is there a way to overwrite existing artifacts on release

No. The only workaround — set `releaseType` in the GitHub publish options to `release` and artifacts will be overwritten, but only if release published not more than 2 hours ago. 
Do you want this feature?

**Comment by develar** [comment]
Fixed in 19.45.3

**Comment by mobitar** [comment]
> Do you want this feature?

Not necessarily, it's not that important. I only use it when I publish a pre-release, then update with final release. Maybe releases should be treated as immutable anyway? Not sure what the best workflow is for something like this.
