### ISSUE TITLE
Mac updates breaking change

### ISSUE THREAD

**Issue by nkt** [electron-userland/electron-builder#2276]
electron-builder@19.45.0 doesn't upload to S3 `latest-mac.yml` file, even if `electronUpdaterCompatibility: '>=1.0.0'` added explicitly.

**Comment by develar** [comment]
S3 Publisher Version?

**Comment by nkt** [comment]
19.42.0

**Comment by develar** [comment]
Please use latest 19.45.0

**Comment by nkt** [comment]
ah, sorry. 19.45.0

**Comment by develar** [comment]
Working on, very strange that our test suite doesn't catch it.

**Comment by nkt** [comment]
Thanks!
