### ISSUE TITLE
How web installer works 

### ISSUE THREAD

**Issue by mvarakin** [electron-userland/electron-builder#2279]
Hi!

It may be silly question but I can't get how web nsis installer works.

I set target as nsis-web and added nsisWeb section inside build section (also tried to put it as a top-level section with the same effect).

```
  "build": {
    "appId": "my_app_id",
    "productName": "my_product_name",
    "win": {
      "target": "nsis-web",
      "icon": "build/icon.ico",
      "publish": [
        "github"
      ]
    },
    "nsisWeb": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false,
      "createDesktopShortcut": true
    },
    "files": [
      "build/**/*",
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ]
  }
```

Now I run npm build and get dist/nsis-web folder with a .7z file. And no .exe file anywhere.
What is next? Where is an installer and where I need to put this .7z file and how the installer will know where to download it from?

**Comment by danwhite-ad** [comment]
Anyone able to help with this? Any good blogs available on the subject?
