### ISSUE TITLE
MSI fails with CNDL1147 

### ISSUE THREAD

**Issue by readme42** [electron-userland/electron-builder#2280]
* **Version**:  19.45.4

* **Target**: msi

msi bundling fails with tons of the following errors: 

Error: Exit code: 1147. Command failed: C:\ ... \AppData\Local\electron-builder\cache\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=C:\ ... \packages\win-unpacked -pedantic -wx project.wxs

`C:\Users\ ... \packages\__msi-temp-x64\project.wxs(259) : error CNDL1147 : Backslash terminate the Component/@Directory attribute's inline directory value 'resources\app.asar.unpacked\node_modules\ ... _u'. A backslash ensures a directory name will not be mistaken for a direct
ory reference.`

NSIS builds are running fine. Is this a bug or am I doing something wrong?

Maybe this is related to #2272?

**Comment by develar** [comment]
Because MSI and WiX sucks, and not so awesome as NSIS, it will take some time until all pitfalls will be catched and workarounds added. I will investigate this issue.

**Comment by develar** [comment]
Please try add

```
"msi:" {
  "warningsAsErrors": false
}
```

to config.

**Comment by readme42** [comment]
Thanks a lot develar. Just rise your hand if you need more information.

**Comment by develar** [comment]
Please attach `__msi-temp-x64\project.wxs` file. Set env `DEBUG=electron-builder` — in this case file will be not deleted after build.

**Comment by readme42** [comment]
`warningsAsErrors: false` helped, .msi is created successfully.

**Comment by readme42** [comment]
I will send the .wxs via email, if this is ok?

**Comment by vinnymac** [comment]
When building on Windows 10 I saw the same errors. Using the `warningsAsErrors` flag it seemed to fix things.

**Comment by NuSkooler** [comment]
@develar I'm also seeing this now with `electron-builder` 20.5.1. `warningsAsErrors: false` works around the issue.

**Comment by vaibhav6233m** [comment]
Hi can anybody give an example package.json for adding warningsAsErrors: false. I used it like this but it is throwing errors:

>     "win": {
>       "target": [
>         {
>           "target": "nsis"
>         },
>         {
>           "target": "msi",
>           "msi": {
>             "warningsAsErrors": false
>           }
>         }
>       ],
>       "icon": "icon.ico"

**Comment by GastonFerrari** [comment]
@vaibhav6233m put the "msi" key at the same level as "win", not under it.
So:
`
"build": {
  "win": {
    ...
   },
  "msi": {
      "warningsAsErrors": false
  }
}
`

**Comment by develar** [comment]
Duplicates #2272
