### ISSUE TITLE
Electron builder nsis build with electron-updater not installing app

### ISSUE THREAD

**Issue by Nikitikitavi** [electron-userland/electron-builder#2281]
Electron-builder 19.45.4

electron-updater 2.16.1

Target - nsis

I am trying to migrate from "squirrel" to "nsis". Have problems on building app to "nsis" target. I am using latest versions of electron and electron-updater, electron-builder.
I am building using "npm run dist" for building

In building an installer for windows no any errors. After I run installer app is added to programs, but not running. Also it couldn't be runed by clicking shortcut. Nothing happen.

Also in /users/<UserName>/AppData/Local/<appName> only .dead file exist, so app seems not installed properly.

After researching I found that reason in "electron-updater". Before, I used autoUpdater from 

`electron - autoUpdater = require("electron").autoUpdater;`

And now I am using electron-updater -

`autoUpdater = require("electron-updater").autoUpdater;`

So when I change this line to previous one (`autoUpdater = require("electron").autoUpdater;`)
App is installing properly, but autoUpdater not work of course.
Any thoughts on this?

**Comment by purplekrayons** [comment]
Are you actually performing the update check?

```
const autoUpdater = require('electron-updater').autoUpdater;
autoUpdater.checkForUpdatesAndNotify();
```
