### ISSUE TITLE
Specify application directory for portable apps

### ISSUE THREAD

**Issue by qhoekman** [electron-userland/electron-builder#2283]
* **19.16.0**: 

* **Windows**: 

When I've created a portable app, I want to persist the cache data or specify the application directory. At the moment It'll use a folder inside %LOCALAPPDATA%\Temp\ . If there is a way to specify the application directory, that would be nice. Thanks in advance!

**Comment by develar** [comment]
> For portable app, PORTABLE_EXECUTABLE_DIR env is set (dir where portable executable located).

**Comment by develar** [comment]
https://github.com/electron/electron/issues/1404#issuecomment-194391247
