### ISSUE TITLE
Error electron-updater min ver required by current electron-builder

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2287]
```console
electron-builder 19.45.4
Error: At least electron-updater 2.16.1 is required by current electron-builder version.
```

Receiving an error that says I need at least 2.16.1 of electron-updater but I have 2.16.2 already.

---

* **Electron-updater - Version**: 2.16.2
* **Electron-builder - Version**: 19.45.4
* **Target**:  Windows | nsis-web

**Comment by develar** [comment]
Are you sure that 19.45.4 is installed? `yarn upgrade`

**Comment by marceloavf** [comment]
![image](https://user-images.githubusercontent.com/5435657/32560277-5fe91b9e-c490-11e7-8b78-30082baf2ff2.png)
![image](https://user-images.githubusercontent.com/5435657/32560293-6799c23a-c490-11e7-81b2-94a55b6cbbc2.png)

**Comment by develar** [comment]
Please set version of electron-updater to `^2.16.2` :)
