### ISSUE TITLE
Large package caused by asarUnpack

### ISSUE THREAD

**Issue by tylerlong** [electron-userland/electron-builder#2290]
* **Version**:  19.45.4

* **Target**:  macOS default

## Sample build config:

```json
"build": {
    "files": [
      "...",
      "build/a-large-binary-file",
      "..."
    ], 
    "asarUnpack": [
      "build/a-large-binary-file"
    ]
  }
```

Pay attention to "build/a-large-binary-file". I need to asarUnpack it because I want to spawn it.

## Problem is

It appears twice in the final package:

* Contents/Resources/app.asar.unpacked/build/a-large-binary-file
* Contents/Resources/app.asar/build/a-large-binary-file

Since it is large, it also make the final distribution package large.

## Proposal

Don't asar anything which needs to be asarUnpack. If it is going to be unpack, what is the point of packing it in the first place?

Or can we remove the file from the asar archieve after unpacking it? Just to reduce the final distribution file size.

**Comment by sadyashica** [comment]
@tylerlong Having the exact same issue. Been trying to resolve this for a while, with no real success. Did you find a workaround?

**Comment by develar** [comment]
@sadyashica Use `extraResources` instead of `asarUnpack` for static files. https://www.electron.build/configuration/contents

**Comment by develar** [comment]
Do not specify in `files`. Use or `extraResources` or `extraFiles`. `asarUnpack` is not required.
