### ISSUE TITLE
electron-updater and private source code

### ISSUE THREAD

**Issue by naheller** [electron-userland/electron-builder#2292]
In a recent issue #2289 I learned that electron-updater requires a `GH_TOKEN` on each user's machine in order to download private GitHub Releases. Since my app is only meant for employees of my company, I'm wondering if I can include the token in my code, and serve the initial DMG internally. 

I got this idea from an [issue](https://github.com/iffy/electron-updater-example/issues/14) over at `electron-updater-example`, which uses `setFeedURL`:

<img width="788" alt="screen shot 2017-11-11 at 3 50 59 pm" src="https://user-images.githubusercontent.com/18204925/32694642-2b6792b2-c6fa-11e7-9df3-e00e2bd99481.png">

However the auto-updater [docs](https://www.electron.build/auto-update) say _not_ to use `setFeedURL`:

<img width="749" alt="screen shot 2017-11-11 at 4 04 10 pm" src="https://user-images.githubusercontent.com/18204925/32694647-4db93cd0-c6fa-11e7-8c28-c361a34d619e.png">

I understand the security risks in hardcoding a token into the code, but is it possible to allow an app using electron-updater to download updates from a private GitHub repo using this method somehow?

If not, would this be possible using S3 in a similarly private/closed source situation?

Thank you!

**Comment by naheller** [comment]
So I've gone ahead and tried this, and the result is new errors! I went ahead and added a setFeedURL with the following data:

    autoUpdater.setFeedURL({
        provider: 'github',
        owner: 'owner',
        repo: 'repo',
        token: 'token'
    })

and the error log shows the following:

    [error] Error: Error: Unable to find latest version on GitHub (https://api.github.com/repos/[owner]/[repo]/releases/latest), please ensure a production release exists: Error: net::ERR_CONNECTION_REFUSED
    at CancellationToken.createPromise (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:69:30)
    at ElectronHttpExecutor.request (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:61:17)
    at PrivateGitHubProvider.httpRequest (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/Provider.ts:26:26)
    at /Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/PrivateGitHubProvider.ts:86:38
    at Generator.next (<anonymous>)

When I follow the link shown (`https://api.github.com/repos/[owner]/[repo]/releases/latest`): I get the following error from GitHub in my browser:

    {
      "message": "Not Found",
      "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
    } 

Is the link being built incorrectly? What needs changing? 

Thanks again!

**Comment by naheller** [comment]
@develar? anyone?

**Comment by develar** [comment]
1. You can set `token` and `private: true` in the publish options and so, no need to call `setFeedURL`.
2. In your current example you must also set `private: true` to use `PrivateGitHubProvider`.

**Comment by naheller** [comment]
@develar thanks for your reply. I have a `publish` script, but not options. Should I set a separate publish options object? Here is my package.json:

```
{
  "name": "training-tracker",
  "version": "0.0.1",
  "productName": "Training Tracker",
  "description": "Training Tracker application using electron and react",
  "author": "author",
  "homepage": "homepage",
  "repository": {
    "type": "git",
    "url": "url",
    "private": true
  },
  "private": true,
  "license": "MIT",
  "main": "main.js",
  "scripts": {
    "testDev": "electron .",
    "testProd": "electron . --noDevServer",
    "dev": "webpack-dev-server --hot --host 0.0.0.0 --config=./webpack.dev.config.js",
    "build": "webpack --config webpack.build.config.js",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "publish": "build -p always"
  },
  "devDependencies": {
    ...
  },
  "dependencies": {
    ...
  },
  "build": {
    "appId": "com.github.author.repository",
    "files": [
      "dist",
      "node_modules",
      "main.js",
      "package.json"
    ],
    "directories": {
      "output": "output"
    },
    "mac": {
      "target": [
        "zip",
        "dmg"
      ]
    }
  }
}
```

**Comment by naheller** [comment]
Hi @develar, thanks for your reply. I have adjusted my `package.json` publish options to look as follows:

```
"build": {
    "appId": "com.github.owner.repo",
    "productName": "Training Tracker",
    "files": [
      "dist",
      "node_modules",
      "main.js",
      "package.json"
    ],
    "directories": {
      "output": "output"
    },
    "mac": {
      "publish": {
        "provider": "github",
        "private": true,
        "token": "token"
      },
      "target": [
        "zip",
        "dmg"
      ]
    }
  }
```

...and in my `main.js`, I simply call `autoUpdater.checkForUpdatesAndNotify()` when the app is ready.

When I run my app, the log shows the following error:

`[error] Error: Error: Unable to find latest version on GitHub (https://api.github.com/repos/owner/training-tracker/releases/latest), please ensure a production release exists`

Following the link above, I see this in my browser:

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}
```

What am I missing? Thanks!

**Comment by naheller** [comment]
I'll also add that my GitHub Releases look like this:

![screen shot 2017-11-16 at 3 57 24 pm](https://user-images.githubusercontent.com/18204925/32922410-f06aaac8-cae6-11e7-94ff-726f88fbda4b.png)

**Comment by naheller** [comment]
Hoping this does not get buried as a "closed" issue!

**Comment by naheller** [comment]
paging @develar. should I create a new issue?

**Comment by JuanDavidLopez95** [comment]
Hi, please re-open this issue! I am in the same exact situation.

**Comment by francescocatalano** [comment]
+1

**Comment by AnupamJuniwal** [comment]
> {
>   "message": "Not Found",
>   "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
> }

I see that you have defined build options in package.json, I had to face the same problem and found that defining build options in electron-builder.json (seperate file) fixes this issue.

much like done by this guy:
https://github.com/linuxjuggler/electron-auto-update-example

**Comment by zeyadmoamen1210** [comment]
same issue but 401
please ensure a production release exists: HttpError: 401
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
any solution ?

**Comment by jesusrogliero** [comment]
Saludooo!!!

Estoy actualmente en la misma problemática, alguien ha podido encontrar la solución?
