### ISSUE TITLE
DMG update

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-builder#2293]
Hi, 

If i choose only ```dmg``` as a target, will the auto-update work? 
I mean is the update yml file generated?

Thanks

**Comment by alexghi** [comment]
As stated in the official docs ```zip``` target for macOS is required for Squirrel.Mac, whereas ```latest-mac.yml``` cannot be created, which causes autoUpdater error.

So if you choose only dmg, explicitly, the auto-update will not work. By default, the target for macOS is dmg + zip so you can simply leave it like it is.

you can (should) always check the docs: https://www.electron.build/auto-update
[#2137](https://github.com/electron-userland/electron-builder/issues/2137)
