### ISSUE TITLE
symlink no such file or directory

### ISSUE THREAD

**Issue by frankLife** [electron-userland/electron-builder#2295]
* **Version**:   19.45.4

* **Target**: dmg

same like this [issue](https://github.com/theia-ide/theia/issues/753)

**when excute electron-builder --mac --dir**

![image](https://user-images.githubusercontent.com/5081884/32744001-cafa7374-c873-11e7-97c8-183866cf8707.png)

It may relate to [dugite](https://github.com/desktop/dugite) ?

And when I change dugite from dependencies to devDependencies, it can pass build without error, but dugite dependecy will lose in release app .

**when excute without --dir , it will be fine**

@develar

**Comment by kittaakos** [comment]
Same as #2298.

**Comment by hrishabhkumar** [comment]
Is there any workaround you found?

**Comment by develar** [comment]
Duplicates #2298
