### ISSUE TITLE
set dmg app title text font color

### ISSUE THREAD

**Issue by frankLife** [electron-userland/electron-builder#2297]
Is there a option to set app text font color instead of default black color?

**Comment by CydeSwype** [comment]
+1, we would like to use a darker background in the DMG window and the black text is hard/impossible to read on it.

**Comment by CydeSwype** [comment]
this doesn't appear to be possible (in any DMGs... so likely an Apple limitation), but there's a workaround.  just add light-colored "bubbles" in your background image like this: https://www.dropbox.com/s/w34fn9z165wjyv4/Screenshot%202018-02-07%2015.03.16.png?dl=0

**Comment by zhoushaokun** [comment]
@mmaietta   Is this feature supported?  Why I don't find the config options in https://www.electron.build/configuration/dmg.
Could you please give the right reference? thanks!

**Comment by mmaietta** [comment]
AFAIK, it's not possible to change background color of a DMG window. The workaround is to have a DMG background image that has your color selection
