### ISSUE TITLE
How to add dlls to application package

### ISSUE THREAD

**Issue by d9k** [electron-userland/electron-builder#230]
Hi! Maybe I've missed something... How can I add dll libraries to application installation package? The dlls must be at the same (package's root) folder where `MyApp.exe` located (`node.dll` and others).

**Comment by develar** [comment]
I don't see such option in the electron-packager.

What solution do yo like — `extraResources` dir in the `build` directory (and configurable path to change default)?

Or just specify `extraResources` to filenames of a files to be copies?
Maybe there is another solution to magically find such dlls and copy it?

**Comment by d9k** [comment]
@develar thanks for answering!
Are you just planning this feature?
Do there exist any working solution exists for now?

If you ask me, I love gulp's style of pattern matching. Files and folders can be specified. `!` symbol at the beginning of rule means exclusion. `extraResources` may be different for each platform. For example:

```
"build": {
//...
"extraResources":  [
//    "common"
],
"win": {
     // ...
     "extraResources":  [
          "./*.dll",
          "!./exclude-me.dll"
     ],
},
"osx": {
     // ...
     "extraResources":  [
          // osx-specific
     ],
},
}
```

**Comment by develar** [comment]
> Do there exist any working solution exists for now?

No. But once will be a proposal, it will be implemented. Since today is Friday, you can expect working solution on Monday.

I like your proposal.

**Comment by develar** [comment]
`electron-packager` currently has option `extra-resource` but only for OS X.

**Comment by develar** [comment]
Doc draft note:
* [glob](https://www.npmjs.com/package/glob#glob-primer) is used.
* You can use `${os}` (expanded to osx, linux, win according to current platform) and `${arch}` in the pattern.
* If directory matched, all content is copied. So, you can just specify `foo` to copy `<project_dir>/foo` to app.

**Comment by develar** [comment]
And, obviously, you should use two-package.json layout, because otherwise electron-packager will copy all project dir to app. See #182 and https://github.com/loopline-systems/electron-builder/issues/39#issuecomment-188855084

**Comment by develar** [comment]
v2.10.0 is a pre-release version, once you confirm that it works as expected, it will be tagged as latest.

**Comment by d9k** [comment]
@develar, yes, it works as expected, thanks a lot! :relieved:
