### ISSUE TITLE
SubjectName check failed

### ISSUE THREAD

**Issue by yhostc** [electron-userland/electron-builder#2301]
certificateSubjectName check failed in the 19.45.6 version, and my certificateSubjectName was chinese. Problems are as follows

`
Error: Cannot find certificate 北京大米科技有限公司, all certs: {"Subject":"CN=�������׿Ƽ����޹�˾, O=�������׿Ƽ����޹�˾, L=Beijing, S=Beijing, C=CN, SERIALNUMBER=911100081805016993, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.1=Beijing, OID.1.3.6.1.4.1.311.60.2.1.2=Beijing, OID.1.3.6.1.4.1.311.60.2.1.3=CN","PSParentPath":"Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"1037BE4D2BAD73A593F8A5C2031BF1BCB2382C90"}
`

**Comment by showgoodjiang** [comment]
We found this related with certificateSubjectName Chinese Name Characters.
