### ISSUE TITLE
[question] How to customize the artifact names for Linux?

### ISSUE THREAD

**Issue by kittaakos** [electron-userland/electron-builder#2302]
* **Version**: 19.45.6

* **Target**: deb, AppImage

Hi there, I am trying to customize the name of the output artifacts produced by the `electron-builder`.
 - For the Windows `nsis` installer, I can do `nsis.artifactName: ${productName}-Installer-${version}.${ext}`. It works perfectly.
 - For the `dmg` one on OS X, I was lucky, and it uses the product name by default. I do not have to do much here.
 - My question is: how can I customize the name of the `AppImage` and `deb` outputs for Linux. I assume, there is documentation for this too what I have accidentally overlooked. The output seems to be a bit inconsistent. For instance, the default file name is the name of the npm package. For the `deb` it uses underscore before the version, while a dash is used for the `AppImage`. (For example: `yangster-electron-0.1.0-x86_64.AppImage` and `yangster-electron_0.1.0_amd64.deb`). I have tried to customize the `executableName`, it did not have any effect on the output.

 The `electron-builder.yml` configuration can be found here: https://github.com/theia-ide/yangster-electron.

 Thank you!

**Comment by develar** [comment]
> The output seems to be a bit inconsistent

It is consistent — name convention according to format. And each format (and Linux distro) has own naming  convention :)

**Comment by develar** [comment]
On the same level, where `win` defined, configure `appImage` and `deb`:

```json
"appImage": {
  "artifactName": "..."
}
```

**Comment by knlshh** [comment]
@develar How does one use the `AppInfo` property? I want to add my build version and number to my artifact name and tried adding `"artifactName": "${productName}-${appInfo.buildNumber}-${appInfo.buildVersion}-.${ext}"` to my `package.json` and got a "macro not defined" error.
