### ISSUE TITLE
NSIS Installer, make entry into registry (windows)

### ISSUE THREAD

**Issue by itsmebhavin** [electron-userland/electron-builder#2303]
* **Version**: 19.24.1

* **Target**: 2.15.0

I have NSIS Installer building from electron-builder and works fine. I can see App_Guid registry key as well. Now i have to make an entry into windows registry under certain path (e.g. HKLM/WOWXXX/CRDL/{APP_NAME} when installing installer. 

How can I tweak the installer/build script to create registry entry when we install it?
Appreciate help.

Current installer.nsh
```
 !macro preInit
    SetRegView 64
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\CRDL\UFP"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\CRDL\UFP"
    SetRegView 32
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\CRDL\UFP"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\ProgramData\CRDL\UFP"
 !macroend
```

**Comment by shuaishenk** [comment]
This is my intaller.nsh
`!macro customInstall
    SetRegView 64
	WriteRegStr HKCR "cloud" "" "URL:yunpan"
	WriteRegStr HKCR "cloud" "URL Protocol" ""
	WriteRegStr HKCR "cloud\shell" "" ""
	WriteRegStr HKCR "cloud\shell\open" "" ""
	WriteRegStr HKCR "cloud\shell\open\command" "" '"$INSTDIR\cloud_app.exe" "%1"'
	SetRegView 32
	WriteRegStr HKCR "cloud" "" "URL:yunpan"
	WriteRegStr HKCR "cloud" "URL Protocol" ""
	WriteRegStr HKCR "cloud\shell" "" ""
	WriteRegStr HKCR "cloud\shell\open" "" ""
	WriteRegStr HKCR "cloud\shell\open\command" "" '"$INSTDIR\cloud_app.exe" "%1"'
!macroend
!macro customUnInstall
   DeleteRegKey HKCR "cloud"
!macroend`
It resgists a URL Protocol called cloud  when installing the app.
