### ISSUE TITLE
Trying to include non-Electron folders in my NSIS installer distribution

### ISSUE THREAD

**Issue by espositot** [electron-userland/electron-builder#2304]
* **19.45.4**: 

* **Windows 7**: 

Trying to include the following folders in my NSIS-installer distro:

C:\myelectronapp\javaprograms_1\

C:\myelectronapp\javaprograms_2\

The final result should be that these folders (and their contents) would be installed under (in) my Electron project.

My installer.nsh file is such:

!macro preInit
	SetRegView 64
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\"
	SetRegView 32
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\"
	File /r javaprograms_1\
	File /r javaprograms_2\
!macroend

But I get the error `no files found`

Being new to NSIS I suspect I am using the `File` (or placing the `File`) clause incorrectly.
Any assistance would be appreciated.

**Comment by purplekrayons** [comment]
Be sure you've included those directories in your build configuration -- im assuming in this example, that your `package.json` is located in `c:/myelectronapp`.

```
"build": {
    "files": [
        "javaprograms_1/**/*",
        "javaprograms_2/**/*"
    ]
}
```

To note, in this example, the `**/*` indicates that all sub directories and all files should be included.

**_If this was the answer, please report back and close this issue. Thank you._**

**Comment by espositot** [comment]
The build process fails saying that the index.js file does not exist -- but it does.  When I take the "files" you mentioned out of the package.json, the build does not fail.  But of course the build does not include the folders as well.  The folders I want to include are located in the same folder ( C:\Users\me\myproject ) as "package.json".

The error is:
```
Error: Application entry file "index.js" in the "C:\Users\me\myproject\dist\win-unpacked\resources\app.asar"
does not exist. Seems like a wrong configuration.

```
package.json file:
```
{
  "name": "myproject",
  "version": "1.0.0",
  "description": "myproject",
  "author": "me",
  "license": "GNU",
  "main": "index.js",
  "build": {
    "appId": "myproject",
    "productName": "myproject",
    "files": [
        "javaprograms_1/**/*",
        "javaprograms_2/**/*"
      ],
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "icons/ico/myproject.ico"
    },
    "nsis": {
      "installerIcon": "icons/ico/myproject.ico",
      "uninstallerIcon": "icons/ico/myproject.ico",
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "license": "LICENSE",
      "runAfterFinish": true,
      "include": "build/installer.nsh"
    }
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build",
    "postinstall": "install-app-deps",
    "electron": "electron ."
  },
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-builder": "^19.45.4",
    "bluebird": "^3.5.1",
    "extract-zip": "^1.6.6",
    "fluent-ffmpeg": "^2.1.2",
    "fs": "0.0.1-security",
    "string-search": "^1.2.0",
    "sybase": "^1.2.1"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "bootstrap-dialog": "^1.34.6",
    "jquery": "^3.2.1",
    "jsdom": "^11.3.0",
    "mysql": "^2.15.0"
  }
}

```

**Comment by purplekrayons** [comment]
That is because you are only including those two folders. It cant find `index.js` because you haven't included `index.js`. I would probably also avoid renaming `main.js` to `index.js`.

Typically, an Electron project is structured as such:

```
myapp/
├── package.json
├── main.js
└── index.html
```

You would then have to include your project files like this:

```
"build": {
    "files": [
        "main.js",
        "index.html"
    ]
}
```

I can't really provide you specific answers as I know nothing about your project. I recommend you read through the [Electron Quick Start Guide](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md).

**Comment by espositot** [comment]
Hello purplekrayons,
  First off -- thanks for your help.  :-)

  I have renamed the files as per the "quick start" guide (and your suggestions) and included them in the build.  The build works but:

1. I still don't pull in those folders.
2. and the pages render as straight text.

I should mention that I am using Bootstrap for my UI.  The index.html page (and all child pages) are using the Bootstrap framework.

So the first thing that comes to mind is -- do I need to include something else (in the package.json file)?

**Comment by purplekrayons** [comment]
Yes, you would need to include every file in your project by including them in your `package.json` file. Maybe this might be a better approach to organizing your project structure:

```
myProject/
│
├── myElectronApp/
│   ├── javaprograms_1/
│   │   └── #whatever this is
│   ├── javaprograms_2/
│   │   └── #whatever this is
│   ├── scripts/
│   │   └── batman.js
│   ├── styles/
│   │   └── batman.css
│   ├── images/
│   │   └── batman.jpg
│   ├── index.html
│   └── main.js
│
├── node_modules/
│   └── #a boatload of node modules, including bootstrap
│
├── package.json
```

Which would allow you to include your entire app folder, as such:

```
{
    "name": "myelectronapp",
    "version": "1.0.0",
    "author": "Batman <bat@man.com>",
    "build": {
        "files": [
            "myElectronApp/**/*",
            "node_modules/**/*",
            "package.json"
        ],
    }
}
```

To include jQuery and Bootstrap, include them in your `index.html` as so:

```
<html>

    <head>

        <title>Batman</title>
        <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="styles/batman.css">

    </head>

    <body>

        <img src="images/batman.jpg" alt="Because I'm Batman..." />

        <script src="../node_modules/jquery/dist/jquery.min.js"></script>
        <script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="scripts/batman.js"></script>

    </body>

</html>
```

[Refer here](https://github.com/electron/electron-quick-start/blob/master/main.js) for an example `main.js` file.

**Comment by espositot** [comment]
Hello purplekrayons,
This is great information.  One outstanding issue -- still not getting the Java program folders to come across in the installation.  Does the installer not recognize .jar files?  (Sounds silly but I had to ask -- that is all that is in the javaprograms folders).  I am calling a Java program from my Electron app.

Thanks a bunch.

**Comment by purplekrayons** [comment]
Is it important that you package things into an asar archive? If not, you could always disable it:

```
"build": {
    "asar": false
}
```

**Comment by espositot** [comment]
Hello purplekrayons,
  Time for our daily talk ...  :-)
 ` "asar": false` does indeed work.  But the files unpack in` C:\Users\me\myelectron\resources\app` and I need them to unpack in `C:\Users\me\myelectron`.
  There is an `asar-unpack` but I believe it is deprecated.
  Any suggestions?  You've been a tremendous help and this thread will be useful to others...

**Comment by espositot** [comment]
Hello purplekrayons,
  Got this to work by adding the Function code below to my NSIS installer.nsh file:

```
!macro preInit
	SetRegView 64
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\myelectronapp"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\myelectronapp"
	SetRegView 32
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\myelectronapp"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\myelectronapp"
!macroend

Function .onInstSuccess
  	SetOutPath "$INSTDIR"
  	CopyFiles "$INSTDIR\resources\app\*" "$INSTDIR\"
FunctionEnd

```

Thanks again for all your help...
