### ISSUE TITLE
electron-builder uploads null.blockmap file

### ISSUE THREAD

**Issue by lutzroeder** [electron-userland/electron-builder#2312]
electron-builder 19.45.4
electron-updater 2.16.1

Running `electron-builder --mac --linux --win --publish always`

Issue: A `null.blockmap` file is uploaded to GitHub. Why is this file created, is it actually needed and is there a way to not have it deployed or properly named?

**Comment by AdamSalma** [comment]
Any idea how to stop this from happening?
