### ISSUE TITLE
i can not building DMG when my os update to macOs High Sierra version 10.13.1

### ISSUE THREAD

**Issue by 405go** [electron-userland/electron-builder#2320]
* **Version**:  10.17.3

* **Target**:  DMG

i can build DMG before i did not  has updated my os version to 10.13.1,
now It can build XXX.app and XXX.zip success, but It stop when Building DMG and It no error and log to show, just link something no happend, It is so bad to me, I hope some can resolve it, thankes!!!!!!1

**Comment by purplekrayons** [comment]
electron-builder works fine in OSX High Sierra. The issue is with your code. Please include error logs so someone may assist you.

**Comment by 405go** [comment]
I use another mac and update to 10.13.1 to package dmg, It is bad to package it also, and i  find a mac 10.12.1 to test it, it is success to package; about logs, there is no logs to show, the terminal just stop when Building DMG.

**Comment by 405go** [comment]
I back my os to 10.11.6, it is resolved.

**Comment by hx4111** [comment]
I have got the same problem  as yours ...  same situation

**Comment by 405go** [comment]
just back your os version  and you will resolved it. @hx4111

**Comment by hx4111** [comment]
#2115 
I have resolved it with update electron-builder to latest.

**Comment by 405go** [comment]
all right @hx4111

**Comment by develar** [comment]
Yes, macOs High Sierra supported by latest electron-builder.

**Comment by andrei-sheina** [comment]
Was using electron-builder version 19.10 and faced into the same issue. Updrage to the latest version (19.50 atm) fixed it.
