### ISSUE TITLE
Disable adding meta-data to electron.exe on Windows

### ISSUE THREAD

**Issue by danmo** [electron-userland/electron-builder#2323]
latest

* **Version**: 

* **Target**: Win

Hi,

I'm using a custom electron build and on windows the electron.exe file is renamed to {ProductName}.exe,  icon is added and other meta-data is added.

Is there a way I can disable this such that the .exe file stays untouched ? I need it's signature to stay the same.

**Comment by develar** [comment]
Option `signAndEditExecutable` added.

```json
"win": {
  "signAndEditExecutable": false
}
```
