### ISSUE TITLE
Macros in artifactName

### ISSUE THREAD

**Issue by mvarakin** [electron-userland/electron-builder#2325]
Hello,

I would like to use macros in artifactName based on env variable.
So I have two scripts in package.json

```
"dev" : "set MY_ENV=dev&&build"
"prod" : "build" (without MY_ENV)
```

I use the following 

```
"artifactName": "${productName} Setup ${version}-${env.MY_ENV}.${ext}"
```

But if I run 'prod' script I got the error 'Error: MY_ENV is not defined'.
Setting 'prod' as 'set MY_ENV=&&build' does not help.

I don't need any suffix in my prod version.
Why not just to ignore ${env.MY_ENV} if it has not been set?

UPD: Also ${arch} is not working. It's never appended to the artifactName.
My win section is 

```
    "win": {
		"target": [
			{
			  "target": "nsis",
			  "arch": [
				"ia32"
			  ]
			}
		  ],
      "icon": "build/icon.ico",
      "publish": [
        "github"
      ]
    }
```

**Comment by develar** [comment]
> Why not just to ignore ${env.MY_ENV} if it has not been set?

Because it can lead to unexpected results. If will be a warning instead of error, it maybe not convenient to catch it (e.g. on CI server).

Solution — define empty env.

>  Also ${arch} is not working. It's never appended to the artifactName.

NSIS produces both arch in one installer.  Please see https://www.electron.build/configuration/nsis#32-bit--64-bit
