### ISSUE TITLE
Please Clarify: auto updating

### ISSUE THREAD

**Issue by purplekrayons** [electron-userland/electron-builder#2326]
In the actual electron-builder docs, absolutely nowhere does it state that a Mac application must be signed in order for auto updating to work.

However, if you refer to the [electron docs for auto updating](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md), it states:

> Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac

Auto updating isnt working for my Mac app and after some searching, came to find the above information.

Can you confirm, electron-builder wont auto-update a Mac app unless it's signed?

If so, I feel like thats a **critical** piece of information you've left out of your documentation. Please add it.

**Comment by develar** [comment]
> electron-builder wont auto-update a Mac app unless it's signed?

Yes. It is requirement of Squirrel.Mac.
