### ISSUE TITLE
How can I make a resource file executable on Linux

### ISSUE THREAD

**Issue by Eshva** [electron-userland/electron-builder#2334]
* **Version: 19.37.2**: 

* **Target: Linux (AppImage, Deb)**: 

Namaste!
I'm very new to Electron development and using electron-builder. My test application should have a local ASP.NET Core web-service that serve access to the application business logic. So I'm able to make a package for Windows and Linux. On Windows installed application works as a charm but on Linux (Ubuntu) I have a problem with executing web-service executable. It just doesn't have 'executable' attribute set. If I set manually after installation the application starts and works as expected.
I do package my web-service files as resource files (in a sub folder). My problem is:
1. How can I mark a file in resources as an executable after installation on Linux?

May be I do something wrong and I should pack web-service folder differently (not as a resource) but I can't find this information in the documentation and on the Net. Please point me to the possible solutions.

**Comment by purplekrayons** [comment]
`chmod +x <filename>`

**Comment by develar** [comment]
AppImage spec forbids packing into archive. And as app is downloaded from web, exec bit is unset. Please see https://discourse.appimage.org/t/how-to-make-an-appimage-executable/80
