### ISSUE TITLE
Where are the instructions for building for Linux target from Windows host?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#2335]
https://www.electron.build/multi-platform-build This page makes it sound like you can do it, but doesn't seem to explain how?

Thanks very much for any help.

**Comment by develar** [comment]
Install Docker and see info about docker usage on the https://www.electron.build/multi-platform-build

Or wait 2 days — on Sunday/Monday will be launched free electron build service to Electron app on any OS for any OS (for now, will be only for Linux).

**Comment by develar** [comment]
You can try experimental build server to build appimage— set env:

```
_REMOTE_BUILD=true
ELECTRON_BUILD_SERVICE_ENDPOINT=45.63.115.123
```

Current limitation — icon is not applied.

**Comment by Slapbox** [comment]
@develar Thanks very much for taking the time to respond. There's a service coming in just a few days to make building for any OS easier? Is there any more info on that yet? It sounds like I should just wait for that.

I studied the multi-platform-build doc, but it seemed only to have a Docker command that would run in a Linux environment unless I'm missing something.

**Comment by develar** [comment]
electron build service is launched. Please try 19.47.1. No announce — silent launch :)

**Comment by Slapbox** [comment]
I appreciate this very personal announcement you've made for me, as well as the great work you all do!

I'm going to try this right now. Thanks very much @develar

**Comment by develar** [comment]
About privacy and other details — https://github.com/develar/electron-build-service#privacy
