### ISSUE TITLE
Run electron-builder without package.json

### ISSUE THREAD

**Issue by fab1an** [electron-userland/electron-builder#2352]
I'm managing my build and `node_modules` with gradle/java. Is there a way to run electron-builder without having a package.json file?
I just need to set version and name for the config.

**Comment by develar** [comment]
You in any case need to create package.json to provide metadata.

The main problem is that you don't want to specify dependencies, right? Is your node_modules contains only production dependencies?

**Comment by fab1an** [comment]
I have the dependencies specified in my gradle build
(looks like this):

![screen shot 2017-12-02 at 07 45 23](https://user-images.githubusercontent.com/55547/33512662-cc002604-d734-11e7-88af-bb02728372a2.png)

**Comment by fab1an** [comment]
That ui

**Comment by develar** [comment]
No, you also need to tell what dependencies are production and what not. Or do you mean that `node_modules` contains only production and so, electron-builder can simply copy it as is?

**Comment by fab1an** [comment]
Yes, exactly, I have only production dependencies in there.

**Comment by develar** [comment]
Got it. I will add user-friendly way to do it.

**Comment by fab1an** [comment]
Great, thanks!

**Comment by fab1an** [comment]
I'm generating the package.json file on the fly now as well, so i'll close this.
