### ISSUE TITLE
autoUpdater doesn't check cache before update downloading

### ISSUE THREAD

**Issue by nkt** [electron-userland/electron-builder#2353]
This behaviour reproduces on windows. Just call `autoUpdater.checkForUpdates()` twice.

**Comment by oxygen** [comment]
At least on Windows, autoUpdater.checkForUpdates(), without any changes to latest.yml and the latest published setup.exe on a static HTTP repo, would redownload the same setup.exe in a new temporary directory.

With a setInterval() it would fill the disk, as it does not clean up after itself.
Even without a setInterval, it still leaves traces, and it should cleanup after itself on application exit.

I know there's a update-downloaded event, however, it is desirable to recheck for even newer updates even if there's an older update downloaded but not installed.

Checking at an interval for two reasons (already mentioned in the first post):
 - getting a new update right after updating is a bad user experience
 - being able to skip a bad (crashing app on start for some users?) downloaded update by superseding it with a newer fixed version, before the user clicks update.

Currently, I am avoiding .checkForUpdates() inside the setInterval() by making a side HTTP call to see if the last-modified timestamp on latest.yml has changed. This shouldn't be needed.

The tmp project https://github.com/raszi/node-tmp makes sure to clean-up temporary files on application exit somehow, or manually through an API.

Feature request:
 - cleanup temporary folder
 - checkForUpdates() must be smarter and remember it has already successfully downloaded a certain version.

**Comment by oxygen** [comment]
Has this been fixed?

**Comment by develar** [comment]
Yes, please try latest version.
