### ISSUE TITLE
TS2304 Error when running Build

### ISSUE THREAD

**Issue by FlowShowcontrol** [electron-userland/electron-builder#2357]
* **19.47.1**: 

* **Windows**: 

Running 'build' ends up with the two following errors:

```
node_modules/builder-util-runtime/out/httpExecutor.d.ts(52,69): error TS2304: Cannot find name 'Set'.
node_modules/builder-util-runtime/out/rfc2253Parser.d.ts(1,47): error TS2304: Cannot find name 'Map'.
```

**Comment by amfio** [comment]
Presumably you are using TypeScript for your build process. Have you tried following the solutions here?
https://stackoverflow.com/a/39418293

I believe you just need to tell the TypeScript compiler that you want to include the types for ES6.
