### ISSUE TITLE
Electron Build Service

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#2359]
Proud to announce that free public electron build service is launched.

* only linux targets for now.
* native decencies are not handled, please use prebuild.
* NodeJS 8.9.1+ is required.
* at least electron-builder 19.48.2 is required.
* Server is open source — https://github.com/electron-userland/electron-build-service

Depending on your feedback, macOS and Window build agents will be launched.

How does it work: by default. i.e. now you are able to do `build --linux` on Windows.

Add your reactions to comments below to vote.

**Comment by develar** [comment]
I want macOS build agent.

**Comment by develar** [comment]
I want Windows build agent.

**Comment by develar** [comment]
If you vote for Windows, please explain, because currently only appx target requires Windows.

**Comment by Slapbox** [comment]
I finally got around to trying the build server and I'm a little confused. After Electron-Builder produces the `linux-unpacked` folder it then says in my terminal:

```
Schedule remote deb build for arch x64
Schedule remote appImage build for arch x64
Done in 96.16s
```
But nothing appears to happen after that even after 10 minutes. What exactly is supposed to happen and what's a reasonable amount of time to expect to wait at this early stage to know if it did work? I know the docs say, _"Queue waiting is not predictable for now,"_ but I'm a little confused about exactly what to expect when the build is completed.

Can you give me any insight? Thanks again @develar and to the entire development team!

**Comment by develar** [comment]
Right now you can expect AppImage and deb in 80-90 seconds.
Do you see artifacts in your out dir? Is build was finished? What is the name of your app (to check server logs).

**Comment by Slapbox** [comment]
Thanks very much @develar.

I've retried the process just now, this time with only `AppImage` as a target and with the application name `SlapboxApp`. 

I do see what appears to be a fully populated folder called `linux-unpacked` upon completion of my build command, and my command ends off with:

```
Packaging for linux x64 using electron 1.7.9 to release\linux-unpacked
Schedule remote appImage build for arch x64
Done in 98.74s.
```

![image](https://user-images.githubusercontent.com/6835891/34006938-153adb14-e0ce-11e7-9ae3-6da89f278386.png)

I tried disabling my firewall completely for a few minutes just to be sure as well. Any thoughts? Thanks again!

**Comment by develar** [comment]
@Slapbox What files do you have in the `dist` (parent dir of linux-unpacked).

**Comment by Slapbox** [comment]
Oh I don't have anything there. I'm using [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) and it seems to put the files into `app\dist\` as opposed to `release\dist\`

I take it this is probably the root of my issue? What I'm doing is running `yarn run package-linux` from the scripts in the [package.json for electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json).

Any thoughts on how I would proceed in fixing this setup to be compatible? Thanks again!

**Comment by develar** [comment]
@Slapbox Thanks. Because of Christmas/New Year, I still doesn't have time to investigate. Will be fixed soon anyway.

**Comment by develar** [comment]
@Slapbox Should be fixed in 19.52.1.

**Comment by Slapbox** [comment]
@develar I just saw this reply and gave it a shot. Works like a charm!

**Comment by Georift** [comment]
Hey, thanks for providing this service, it definitely makes it more straightforward getting out Linux builds. 😃 

However I wonder if we could have a discussion regarding this being enabled by default. I work in an enterprise environment where sending anything to a public service would be considered a big no no. I have since found the `remoteBuild` option and I'll be using that for all my work projects from now on.

I understand why it's enabled by default, we want to provide the most seamless experience for the user, but perhaps we could change it to an opt-in? Say on windows when we encounter a linux build but no `remoteBuild `option present it displays a message saying something like _"Your platform does not support local linux builds. A free public electron build service exists, to enable it set 'remoteBuild' to true"_?

What do you think @develar?

**Comment by FelikZ** [comment]
I would love to have all platforms especially Windows, to trigger CI builds remotely, regardless of the platform where the trigger happens.

**Comment by Georift** [comment]
@develar I'm sorry for taking so long to reply. Yep I've seen the privacy notes, however I think it's worth pointing out that not all builds are destined for the wider public. There may be cases where the application is an internal tool, or a tool used in the day to day operations of a company. The contents of the build even after compiled can still contain sensitive information.

I feel the safest path is to provide at least some information to the user that this is happening. I'd be happy to provide a PR that adds and interactive opt in to keep the user experience as high as possible. What are your thoughts?

**Comment by develar** [comment]
@Georift PR will be accepted. You can do it or on NodeJS side, or on Go side https://github.com/develar/app-builder/blob/master/pkg/remoteBuild/RemoteBuilder.go We are in transition to get rid of NodeJS in favour of Go, so, better if it will be done on Go side (but please note, that you will need to open input stream on nodejs side, currently stdio configured to ignore, if I am not wrong).

**Comment by Slapbox** [comment]
@develar, not directly related, but is there anything I can read on why the team decided on Go as opposed to Node? Seems like it would be valuable learning material.

**Comment by develar** [comment]
> why the team decided on Go as opposed to Node

Pyhton/Node/Ruby is not a good languages for CLI tools. Go produces single executable, that you can run everywhere and build everywhere (and end user can install any version of your tool using one simple command). You can use whatever dependencies your want, and so on. Easy to install any version, you can organize your project as you want — it is linker responsibility to build required parts, not you should create myriads small unmaintable hell of node modules. Not to mention go routines (yes, Promise is not a solution).

**Comment by vamsee9** [comment]
cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1ftm1h2": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.

can't build for linux on windows

**Comment by eduboxgithub** [comment]
I'm also getting the same error as @vamsee9.

How can we build linux from a windows machine?

```
cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fv6j5n": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fv6j5n": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fv6j5n": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1fv6j5n": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.  
  ⨯ D:\_GIT\SIGADesktop\electron\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```
