### ISSUE TITLE
Use with electron-prebuilt-compile

### ISSUE THREAD

**Issue by hacdias** [electron-userland/electron-builder#2361]
Is it possible to use electron builder with electron-prebuilt-compile? If so, how?

**Comment by develar** [comment]
What's problem do you have? In general, electron-prebuilt-compile is supported and extra configuration is not required.

**Comment by hacdias** [comment]
It gives me an error like this:

```
File "D:\Code\ipfs-shipyard\station2/__shim.js" not under the source direct
```

**Comment by Megajin** [comment]
#2319 is the issue, it has nothing to do with `electron-prebuilt-compile`.

**Comment by Megajin** [comment]
@develar  I guess this issue can be closed too.

**Comment by hacdias** [comment]
@develar @Megajin so, this bug was fixed but I'm still wondering how to run it. If I try to run it with electronCompile set to false, I get syntax errors (because I'm using ES6). If I set it to true, it doesn't find electron-compile module. So I'm wondering which is the best way to use electron-builder + electron-prebuilt-compile?
