### ISSUE TITLE
Building both windows 32 and 64 bit installers using prepackaged command

### ISSUE THREAD

**Issue by danmo** [electron-userland/electron-builder#2362]
Hi,

I'm using the prepackaged command to build the installer using slightly modified versions of win-ia32-unpacked and win-unpacked folders.

However, right now I need to run --prepackaged in turn for each folder and produce separate installers.

How could I use the --prepackaged command to build both 32 and 64 bit into one installer?

**Comment by develar** [comment]
Could you please describe why you are forced to use prepackaged?

>  using slightly modified versions of win-ia32-unpacked and win-unpacked folders.

`afterPack` is more suitable for this task. Please see https://www.electron.build/configuration/configuration

**Comment by danmo** [comment]
@develar the electron.exe binary needs a special VMP signature for playing DRM encrypted content. Also, this step needs to come after the digital signature, not sure afterPack would do it in this case.

Would need an afterPack, after signing and adding metadata to the electron.exe.

Waiting for your advice, many thanks.

**Comment by develar** [comment]
> Also, this step needs to come after the digital signature

So, afterPack is not an option for you.

Ok... what about to fight on your side, but instead open a PR to apply this transformation on electron-builder side? PR will be accepted and new version released very quickly, often in 6 hours, so, PR or details how to apply this signature, are welcome.
