### ISSUE TITLE
Linux: no such file or directory, open '/opt/morpheus-vue/resources/app-update.yml'

### ISSUE THREAD

**Issue by mbykov** [electron-userland/electron-builder#2364]
* **Version**: 
    "electron": "^1.7.9",
    "electron-builder": "^19.48.2",

    "electron-updater": "^2.16.3",

* **Target**: 
       "target": [
        "deb"
      ],

but alas:

$ morpheus-vue
Running in production
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/morpheus-vue/resources/app-update.yml'
    at /opt/morpheus-vue/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27

code: https://github.com/mbykov/morpheus-vue
travis: https://travis-ci.org/mbykov/morpheus-vue

what can be done?

**Comment by figueiredo-lucas** [comment]
Haven't been able to use AutoUpdater with .deb either, I used AppImage instead. It generates the code correctly but then [this](https://github.com/electron-userland/electron-builder/issues/2240) happens.

**Comment by develar** [comment]
@mbykov For `deb` electron-updater must be not used. Only AppImage supports auto-update. See checkForUpdatesAndNotify function implementation how to check that app distributed as AppImage.

@figueiredo-lucas Again, sorry that mentioned issue not fixed yet.

**Comment by figueiredo-lucas** [comment]
@develar No worries, man! Whenever you can. Thanks anyway!

**Comment by mbykov** [comment]
Great, thank you!

**Comment by erguotou520** [comment]
Is this will not be implemente for `deb`?
