### ISSUE TITLE
"directories" in the root is deprecated, please specify in the "build"

### ISSUE THREAD

**Issue by daffylumampao** [electron-userland/electron-builder#2371]
Hi, I'm a little new to electron and am currently trying electron builder. I can't seem to run the programmatic usage of electron-builder or at least I don't understand the documents on how. Here is my current code: 

```
"use strict"

const builder = require("electron-builder")

const Platform = builder.Platform


builder.build({
    targets: Platform.WINDOWS.createTarget('msi'),
    config: {
    }
})
  .then(() => {
    console.log('OK')
  })
  .catch((error) => {
    console.log(error)
  })
```

How can I use it programmatically? Thank you.

**Comment by develar** [comment]
Specify `directories` in the `config`.

**Comment by daffylumampao** [comment]
Hi @develar, I updated my code to this:
builder.build({
    targets: Platform.WINDOWS.createTarget('msi'),
    config: {
        appId: 'test.electron.id',
        directories: {
            output: '../dist',
        },
    },
})
  .then(() => {
    console.log('OK')
  })
  .catch((error) => {
    console.log(error)
  })

but it still returns ' Error: "directories" in the root is deprecated, please specify in the "build" '.  What am I doing wrong?

**Comment by daffylumampao** [comment]
Hi @develar <https://github.com/develar>, I updated my code to this:

builder.build({
targets: Platform.WINDOWS.createTarget('msi'),
config: {
appId: 'test.electron.id',
directories: {
output: '../dist',
},
},
})
.then(() => {
console.log('OK')
})
.catch((error) => {
console.log(error)
})

but it still returns ' Error: "directories" in the root is deprecated,
please specify in the "build" '. What am I doing wrong?

"buildResources = build String - The path to build resources." what is the
diferrence between buildResources and output?

I created a script build.js and i run it using 'node build.js'


Regards,

Daffy

**Comment by daffylumampao** [comment]
I was able to find the problem. Since I was using the builder.build, I didn't noticed I also declared 'directories' in my package.json. Sorry! But there's another problem I'm currently having which is this one: 

"Exit code: 94. Command failed"
"error LGHT0094 : The identifier 'Icon:icon.ico' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker"

Here is my currentc code:
builder.build({
  targets: Platform.WINDOWS.createTarget('msi'),
  config: {
    appId: 'test.electron.safetybrowser',
    directories: {
      app: "./src/app/",
      buildResources: "./src/clients/tripleone/icon.ico"
    },
  }
})

Any ideas on this?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by daffylumampao** [comment]
Here's the result of the electron-builder-ydebug.yml:

x64:
  firstOrDefaultFilePatterns:
    - '**/*'
    - '!dist{,/**/*}'
    - '!**/*.{iml,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,suo,xproj,cc,pdb}'
    - '!**/._*'
    - '!**/electron-builder.{yaml,yml,json,json5,toml}'
    - '!**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.flowconfig,.jshintrc,.eslintrc,.circleci,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,appveyor.yml,.travis.yml,circle.yml,.nyc_output}'
    - '!.editorconfig'
productionDependencies:
  'C:\Users\user\Documents\duplicate-safetybrowser\src\app':
    - after
    - ajv
    - asn1
    - assert-plus
    - async
    - asynckit
    - aws-sign2
    - aws4
    - balanced-match
    - base64-js
    - bcrypt-pbkdf
    - boom
    - brace-expansion
    - browser-launcher2
    - browser-launcher2\node_modules\lodash
    - browser-launcher2\node_modules\rimraf
    - caseless
    - co
    - colors
    - combined-stream
    - concat-map
    - core-util-is
    - cryptiles
    - cryptiles\node_modules\boom
    - cycle
    - dashdash
    - date-utils
    - debug
    - delayed-stream
    - ecc-jsbn
    - electron-context-menu
    - electron-dl
    - electron-is-dev
    - electron-json-storage
    - ext-list
    - ext-name
    - extend
    - extsprintf
    - eyes
    - fast-deep-equal
    - fast-json-stable-stringify
    - forever-agent
    - form-data
    - fs.realpath
    - getpass
    - glob
    - har-schema
    - har-validator
    - hawk
    - headless
    - hoek
    - http-signature
    - inflight
    - inherits
    - ip
    - is-plain-obj
    - is-typedarray
    - isexe
    - isstream
    - jsbn
    - json-schema
    - json-schema-traverse
    - json-stringify-safe
    - jsprim
    - lodash
    - lru-cache
    - mime-db
    - mime-types
    - mime-types\node_modules\mime-db
    - minimatch
    - minimist
    - mkdirp
    - modify-filename
    - ms
    - oauth-sign
    - once
    - os-homedir
    - os-tmpdir
    - osenv
    - path-exists
    - path-is-absolute
    - performance-now
    - plist
    - pseudomap
    - punycode
    - pupa
    - qs
    - request
    - rimraf
    - rwlock
    - safe-buffer
    - sntp
    - sort-keys
    - sort-keys-length
    - sshpk
    - stack-trace
    - stringstream
    - tough-cookie
    - tunnel-agent
    - tweetnacl
    - uid
    - unused-filename
    - util-deprecate
    - uuid
    - verror
    - which
    - win-detect-browsers
    - winston
    - winston\node_modules\async
    - wrappy
    - xmlbuilder
    - xmlbuilder\node_modules\lodash
    - xmldom
    - xtend
    - yallist
    - yargs

**Comment by daffylumampao** [comment]
Here is the debug log:
[debug-log.txt](https://github.com/electron-userland/electron-builder/files/1550060/debug-log.txt)

**Comment by purplekrayons** [comment]
Possibly due to the typo in your path to the .ico file:

> buildResources: "./src/clients/**clietn**/icon.ico"

I feel like it should be:

> buildResources: "./src/clients/**client**/icon.ico"

**Comment by daffylumampao** [comment]
I was able to solve this by using NSIS instead.
