### ISSUE TITLE
how to add welcome page in custom header?

### ISSUE THREAD

**Issue by dengyaolong** [electron-userland/electron-builder#2372]
* **Version**: 19.22.1

* **Target**: add welcome page in custom header file

I see electron-builder can use nsis.include to add a custom header.

now I want to use almost every thing about nsis default installer. But I need to add a welcome page.
It's there any solution add it in my custom header?

**Comment by dengyaolong** [comment]
Just like `!insertmacro MUI_WELCOME_PAGE`

**Comment by develar** [comment]
Duplicates #1501
