### ISSUE TITLE
Private GitHub Provider: neither event "update-available" nor event "update-not-available" fired after checkForUpdates()

### ISSUE THREAD

**Issue by nicholaslee119** [electron-userland/electron-builder#2374]
* **Version**: 19.43.3

* **electron-updater Version**: 2.16.1

* **Target**:  Mac

I use autoUpdater for my private github repo like this:

```js
autoUpdater.setFeedURL({
  provider: 'github',
  token: 'MY_TOKEN',
  owner: 'nicholaslee119',
  private: true,
  repo: 'electron-updater-example'
});

console.log("App start....")

autoUpdater.on('checking-for-update', () => {
  console.log('Checking for update...');
})

autoUpdater.on('update-available', (info) => {
  console.log('Update available.');
})
autoUpdater.on('update-not-available', (info) => {
  console.log('Update not available.');
})

autoUpdater.on('error', (err) => {
  console.log('Error in auto-updater. ' + err);
})

app.on('ready', function()  {
  console.log("ready!!!");
  autoUpdater.checkForUpdates();
});

```

and here is output

```
App start....
ready!!!
Checking for update...

```

It seems like the neither update-available nor update-not-available were fired after checkForUpdates()

**Comment by develar** [comment]
Reopened because @jpeizer reported that it is still broken. https://github.com/electron-userland/electron-builder/issues/2379#issuecomment-351420471

**Comment by jpeizer** [comment]
Logs:
```
[11:11:59.539] [info] Checking for update
[11:12:03.157] [info] Found version <version> (url: <package>.exe)
[11:12:03.158] [info] Downloading update from <package>.exe
```
This is where it appears to stop.  Let me know if you want any more details.

**Comment by nicholaslee119** [comment]
@jpeizer Thanks for your report, I will check it in a couple of days

**Comment by nicholaslee119** [comment]
@develar 
I am handling the problem of downloading update from private Github,
and I have seen there is a local Proxy Server for downloading assets,
Could you tell me why are you putting this local Proxy Server in that way?

**Comment by develar** [comment]
@nicholaslee119 Because Squirrel.Mac doesn't support arbitrary URL, but we cannot use predefined URLs for GitHub releases.
