### ISSUE TITLE
Signtool on programmatic usage(question)

### ISSUE THREAD

**Issue by daffylumampao** [electron-userland/electron-builder#2378]
Hi,

I have a question. How can you assign this type of signtool programmatically? Can you give me an elaborate example? I am currently using 'NSIS' for windows.

SignTool=signname"{#ProjectHomeBase}\build\signtool.exe" sign /f "{#ProjectHomeBase}\build\something.pfx" /t http://timestamp.verisign.com/scripts/timstamp.dll /p 12345678 $f

**Comment by develar** [comment]
What problem do you have? Of course, you can set `sign` to custom function (see https://www.electron.build/configuration/win), but it is advanced usage. I think, it is not required for you.

**Comment by daffylumampao** [comment]
I already have a signtool.exe but I don't know where to put it on code. Is it like 'signingHashAlgorithms: SignTool=signname'?

**Comment by develar** [comment]
electron-builder does it for you. For what do you need to provide your own version?

**Comment by daffylumampao** [comment]
Oh. Ok I see. I just taught that signing must be done separately. So to clarify? Signing is already being done by electron-builder and so the setup.exe on your folder is already signed?

**Comment by develar** [comment]
Unlike other tools, electron-builder is a complete solution. Just provide cert (https://www.electron.build/code-signing) and that's all.

**Comment by daffylumampao** [comment]
Hi develar,

I just want to ask if what should be the vaIue in the sign key to have a custom digital signature for our project. Since I can't use the certificateFile because I don't know the password. Here is my code:

builder.build({
    config: {
        directories: {
            app: './src/app/',
        },
        win: {
            target: ['nsis'],
            icon: './src/clients/user/icon.ico',
            sign: ????,
            certificateFile: './build/install-script/smartbrowser.pfx',
        },
        nsis: {
            oneClick: false,
            installerIcon: './src/clients/user/icon.ico',
            installerHeaderIcon: './src/clients/user/icon.ico',
            uninstallerIcon: './src/clients/user/icon.ico',
        },
    },
})

**Comment by daffylumampao** [comment]
@develar Is the certificateFile in win responsible for showing the digital signature tab on the .exe file?

**Comment by develar** [comment]
Yes. You can use or env to specify cert, or this option.

**Comment by daffylumampao** [comment]
May I ask how can you set it up in the env?

**Comment by develar** [comment]
Please see https://www.electron.build/code-signing
