### ISSUE TITLE
Installer directory name not updating with 'name'

### ISSUE THREAD

**Issue by Narmdo** [electron-userland/electron-builder#2383]
* **Version**: 19.8.0

* **Target**: Windows

I'm working on a project based off the electron-react-boilerplate.
After doing a package, and running the installer, the project was installed to %localappdata%/Programs/electron-react-boilerplate

Of course this isn't what I wanted, so I ensured package.json had the correct 'name' value. (The boilerplate uses a two-package setup, and I had missed the name within the /app/package.json).

However after building and packaging again, it still continues to install to that directory.

I have searched the project for 'electron-react-boilerplate' and it only remains in some readme's and changelogs, not in any source or config file whatsoever.

Does anyone have a way to solve this?

**Comment by develar** [comment]
Application installed where previous version of app was installed. Please provide your config, and please try to uninstall old app.

**Comment by Narmdo** [comment]
Which config files are relevant? Just the package.json files?
Also, completely deleting that directory before repackaging and installing doesn't solve the issue.

**Comment by develar** [comment]
Update electron builder to 19.53.0 and attach dist/electron-builder.yml
