### ISSUE TITLE
Reduced Installer Size. Why?

### ISSUE THREAD

**Issue by purplekrayons** [electron-userland/electron-builder#2390]
I noticed a dramatic reduction in the size of my resulting NSIS Windows installer. As of **19.46.4**, i was getting a Windows installer size just over 200MB. I updated to **19.49.0** last night and the resulting installer is now only 61MB. I've ran it a couple times -- its consistently now right around 61MB. I noticed it's now also producing a `blockmap` file. Don't get me wrong, this is great, but, it makes me wonder why? @develar Can you please shed some light -- is this expected? I should further note, that there were no changes to the size of my mac app (.dmg)

**Comment by develar** [comment]
Actually, size should be a little bit bigger.

Please inspect app.asar files in the resources. E.g. asar l app.asar.

**Comment by purplekrayons** [comment]
I've compared the installation directories, and i've also unpacked and compared the app.asar file -- they are both right around the same (200MB).

`C:\Users\<user>\AppData\Local\Programs\<myprogram>\`
`C:\Users\<user>\AppData\Local\Programs\<myprogram>\resources\app.asar`

I can confirm that everything is where it should be, and my app still works normally using the .exe installer that was ~200MB and the latest .exe installer that is ~61MB.

It almost seems as though up until 19.49.0, my window installer was never being compressed or something?

**Comment by develar** [comment]
Now it is forbidden to specify compression level to ensure that blockmaps are the same for different versions. I suspect that you have invalid config. 
Please set env `DEBUG=electron-builder` and attach log of the terminal output. To see effective configuration.

**Comment by purplekrayons** [comment]
Sorry, but I can't quite seem to figure out how this works? I've tried:

`set DEBUG=electron-builder`
`npm set DEBUG=electron-builder`

Doesnt result in debug output in terminal.

**Comment by develar** [comment]
Note that PowerShell uses different syntax to set environment variables.

$env:DEBUG = "electron-builder"
Then, run the program to be debugged as usual.

**Comment by purplekrayons** [comment]
Appreciate the help!

Here's the resulting debug:

[electron-builder-debug.txt](https://github.com/electron-userland/electron-builder/files/1563262/electron-builder-debug.txt)

**Comment by purplekrayons** [comment]
You know, now i'm looking at this debug file -- i noticed i have this set in my `package.json`

`"compression": "store",`

It looks like i was never compressing my installers and didn't even realize it until you've forced the compression thing. This would indeed explain the sudden decrease in file size.

Interesting to note however, that my `.dmg` files have never changed -- have always remained around 180MB. Did the change you make only apply to NSIS installers?

**Comment by develar** [comment]
1. We must warn users.
2. Investigate DMG case.
