### ISSUE TITLE
Where can I find the chromium version of a specific version before installing?

### ISSUE THREAD

**Issue by JohnWeisz** [electron-userland/electron-builder#2394]
We are packing an audio production app with electron-builder, and this is sensitive to Chromium updates and changes in Chromium version (bugs, temporarily working workarounds, etc.). I'd like to find out the version used by electron-builder _before_ installing, but couldn't find this information in the docs.

Is the current version available somewhere? I'm particularly interested about `19.49.0`.

**Comment by Zamiell** [comment]
This has to do with Electron, not electron-builder, so you posted this in the wrong repository. Electron-builder is just the thing that packs everything in an ASAR.

**Comment by JohnWeisz** [comment]
> This has to do with Electron, not electron-builder, so you posted this in the wrong repository. Electron-builder is just the thing that packs everything in an ASAR.

Indeed, although no mention of Electron version exists in the documentation either (or if there _is_ one, I 
was unable to find it).
