### ISSUE TITLE
How to sign your electron application code with electron-builder 

### ISSUE THREAD

**Issue by Neo13Pr** [electron-userland/electron-builder#2401]
* **electron-builder version**- 19.45.5
* **Target**: 

Windows 7

How to sign your electron application code with electron-builder ?

Hello there,

I  want to sign my electron application code, i am new in this electron development so could anyone tell me how to sign electron application with code signing certificates

I am using windows platform to create build.

and one more thing how to set "certificateSubjectName" and where?

**Comment by develar** [comment]
https://www.electron.build/code-signing

https://www.electron.build/configuration/win
