### ISSUE TITLE
unable to sign dmg using electron builder

### ISSUE THREAD

**Issue by vamshisana** [electron-userland/electron-builder#2402]
i am using dependencies 
"devDependencies": {
    "electron": "~1.7.8",
    "electron-builder": "^19.49.0"
  }
and when i run for build and publish i get following output in debug mode i have also exported the CSC_NAME CSC_KEY_PASSWORD also 

here is the log

Apple:carnegie hurix$ DEBUG=electron-builder npm run buildandpublish

> carnegie@1.2.4 buildandpublish /Users/hurix/Desktop/vamshi/carnegie
> electron-builder -p always   

electron-builder 19.49.0
  electron-builder Effective config:
  electron-builder appId: com.kitaboo.app
  electron-builder mac:
  electron-builder   category: com.kitaboo.app
  electron-builder   type: distribution
  electron-builder target: dmg
  electron-builder publish:
  electron-builder   provider: s3
  electron-builder   bucket: test-electrons
  electron-builder  +0ms
  electron-builder Unresolved dependencies after first round: 7zip-bin-linux, 7zip-bin-win +6s
Rebuilding native production dependencies for darwin:x64
  electron-builder Spawning /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js rebuild ws@0.4.31 ws@0.5.0 +667ms
  electron-builder cwd: /Users/hurix/Desktop/vamshi/carnegie +0ms

> ws@0.5.0 install /Users/hurix/Desktop/vamshi/carnegie/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> ws@0.4.31 install /Users/hurix/Desktop/vamshi/carnegie/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
ws@0.5.0 /Users/hurix/Desktop/vamshi/carnegie/node_modules/ws
ws@0.4.31 /Users/hurix/Desktop/vamshi/carnegie/node_modules/engine.io-client/node_modules/ws
  electron-builder node (21508) exited with exit code 0 +34s
Packaging for darwin x64 using electron 1.7.9 to dist/mac
  electron-builder Executing unzip -oqq -d /Users/hurix/Desktop/vamshi/carnegie/dist/mac /Users/hurix/Library/Caches/electron/electron-v1.7.9-darwin-x64.zip +6s
  electron-builder node_modules/7zip-bin-mac/7za is not packed into asar archive - contains executable code +20s
⚠️  Application icon is not set, default Electron icon will be used
  electron-builder Executing security find-identity -v +51s
  electron-builder Executing security find-identity -v -p codesigning +69ms
  electron-builder      0 valid identities found
  electron-builder  +479ms
  electron-builder   1) 6F5F65CABD9732290C5624741DC88A31C5679853 "Developer ID Installer: Hurix Systems Pvt Ltd (V5SZS65EA4)"
  electron-builder      1 valid identities found
  electron-builder  +31ms
  electron-builder Executing security find-identity +37ms
  electron-builder 
  electron-builder Policy: X.509 Basic
  electron-builder   Matching identities
  electron-builder   1) 6F5F65CABD9732290C5624741DC88A31C5679853 "Developer ID Installer: Hurix Systems Pvt Ltd (V5SZS65EA4)"
  electron-builder      1 identities found
  electron-builder 
  electron-builder   Valid identities only
  electron-builder   1) 6F5F65CABD9732290C5624741DC88A31C5679853 "Developer ID Installer: Hurix Systems Pvt Ltd (V5SZS65EA4)"
  electron-builder      1 valid identities found
  electron-builder  +228ms
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing

All identities:
  1) 6F5F65CABD9732290C5624741DC88A31C5679853 "Developer ID Installer: Hurix Systems Pvt Ltd (V5SZS65EA4)"
     1 identities found

  Valid identities only
  1) 6F5F65CABD9732290C5624741DC88A31C5679853 "Developer ID Installer: Hurix Systems Pvt Ltd (V5SZS65EA4)"
     1 valid identities found
Building macOS zip
Building DMG
⚠️  Application icon is not set, default Electron icon will be used
  electron-builder Executing /Users/hurix/Desktop/vamshi/carnegie/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/hurix/Desktop/vamshi/carnegie/dist/carnegie-1.2.4-mac.zip carnegie.app +333ms
  electron-builder cwd: /Users/hurix/Desktop/vamshi/carnegie/dist/mac +0ms
  electron-builder macOS version: 10.11.6 +86ms
  electron-builder Spawning hdiutil create -srcfolder /Users/hurix/Desktop/vamshi/carnegie/dist/mac/carnegie.app -volname carnegie 1.2.4 -anyowners -nospotlight -format UDRW -fs HFS+ -fsargs -c c=64,a=16,e=16 /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/0.dmg +2ms
....................................................................
created: /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/0.dmg
  electron-builder hdiutil (22244) exited with exit code 0 +38s
  electron-builder Executing hdiutil resize -size 205813170 /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/0.dmg +7ms
  electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/0.dmg +233ms
  electron-builder /dev/disk1          	GUID_partition_scheme          	
  electron-builder /dev/disk1s1        	Apple_HFS                      	/Volumes/carnegie 1.2.4
  electron-builder  +2s
  electron-builder Executing ln -s /Applications /Volumes/carnegie 1.2.4/Applications +40ms
  electron-builder Executing /usr/bin/perl /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/1-dmgProperties.pl +107ms
  electron-builder env: {
  electron-builder   "volumePath": "/Volumes/carnegie 1.2.4",
  electron-builder   "appFileName": "carnegie.app",
  electron-builder   "iconSize": 80,
  electron-builder   "iconTextSize": 12,
  electron-builder   "windowX": 400,
  electron-builder   "windowY": 100,
  electron-builder   "VERSIONER_PERL_PREFER_32_BIT": "true",
  electron-builder   "backgroundFilename": "background.tiff"
  electron-builder } +2ms
  electron-builder cwd: /Users/hurix/Desktop/vamshi/carnegie/node_modules/dmg-builder/vendor +0ms
  electron-builder Executing hdiutil detach /dev/disk1 +2s
  electron-builder "disk1" unmounted.
  electron-builder "disk1" ejected.
  electron-builder  +11s
  electron-builder Spawning hdiutil convert /private/var/folders/1d/vbqjbm994qq23df2b0f280g00000gn/T/temp-dir-66mTz7/0.dmg -ov -format UDZO -o /Users/hurix/Desktop/vamshi/carnegie/dist/carnegie-1.2.4.dmg -imagekey zlib-level=9 +3ms
Preparing imaging engine…
Reading Protective Master Boot Record (MBR : 0)…
   (CRC32 $E410548B: Protective Master Boot Record (MBR : 0))
Reading GPT Header (Primary GPT Header : 1)…
   (CRC32 $5C6C1649: GPT Header (Primary GPT Header : 1))
Reading GPT Partition Data (Primary GPT Table : 2)…
   (CRC32 $FEF38DF2: GPT Partition Data (Primary GPT Table : 2))
Reading  (Apple_Free : 3)…
   (CRC32 $00000000:  (Apple_Free : 3))
Reading disk image (Apple_HFS : 4)…
..............................................................................
   (CRC32 $3EF1271E: disk image (Apple_HFS : 4))
Reading  (Apple_Free : 5)…
..............................................................................
   (CRC32 $00000000:  (Apple_Free : 5))
Reading GPT Partition Data (Backup GPT Table : 6)…
..............................................................................
   (CRC32 $FEF38DF2: GPT Partition Data (Backup GPT Table : 6))
Reading GPT Header (Backup GPT Header : 7)…
...............................................................................
   (CRC32 $632ADAB3: GPT Header (Backup GPT Header : 7))
Adding resources…
...............................................................................
Elapsed Time: 19.197s
File size: 68417080 bytes, Checksum: CRC32 $57FAD036
Sectors processed: 402050, 396844 compressed
Speed: 10.1Mbytes/sec
Savings: 66.8%
created: /Users/hurix/Desktop/vamshi/carnegie/dist/carnegie-1.2.4.dmg
  electron-builder hdiutil (22557) exited with exit code 0 +20s
packager=======[object Object]
 

my certificate is also added in keychains and that is a valid one

**Comment by KrzysZG37** [comment]
@vamshisana please, check this post:
[https://github.com/electron-userland/electron-builder/issues/2399](url)
It might help you

**Comment by KrzysZG37** [comment]
I see that there is a problem with this link, please check issue no 2399 in closed issues section.

**Comment by vamshisana** [comment]
The issue is solved there was a problem with the certificate type that i was using while making my build
