### ISSUE TITLE
Nsis: Update is not installed if user restarts OS after 'update-downloaded' event.

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#2403]
* **Version**: 19.45.5

* **Electron-updater**: 2.16.1

* **Target**: nsis

When update is ready for installation and user just shutdowns his PC or restarts it, update is not installed. It is a very common case, as a result many our users doesn't have up-to-date application. 
Also if we check for updates after system restart, it is downloaded one more time.

One additional question: how can we get name of temp folder where update is downloaded?

**Comment by develar** [comment]
Related: #2709
