### ISSUE TITLE
Error: Application entry file "build/electron.js" in the "<path>/dist/mac/<app-name>/Contents/Resources/app.asar" does not exist.

### ISSUE THREAD

**Issue by thinkholic** [electron-userland/electron-builder#2404]
* **Version**: 
`19.49.0`

* **Target**: 
mac

I'm using `create-react-app` and also followed below blog post.
https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3

```
Error: Application entry file "build/electron.js" in the "/Users/jarvis/Dev/sandbox/elec-app/dist/mac/elec-app.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/jarvis/Dev/sandbox/elec-app/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /Users/jarvis/Dev/sandbox/elec-app/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:33:11
    at next (native)
    at /Users/jarvis/Dev/sandbox/elec-app/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
:
```

**Comment by andymorris** [comment]
I was also getting this error (though I'm trying to build on Windows with 19.52.1) and just wanted to note that the workaround described in #2030 worked for me:

> Workaround: please add "extends": null to build.

**Comment by Mosquito13** [comment]
I'm getting the exactly same error that @thinkholic mentioned, but on Windows.

The workaround didn't work.

**Comment by thinkholic** [comment]
I didn't checked with the workaround suggested by @andymorris yet. Hoping to try tonight.

**Comment by develar** [comment]
Well... have you created this file?

**Comment by thinkholic** [comment]
@develar 
> created this file?

You means?

**Comment by develar** [comment]
https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3

> Add this electron.js file to the “public” folder.

> We’re adding it in the “public” folder instead of “src” so it can get copied to the “build” folder as it is. This is needed for the production version, and it’s explained later.

**Comment by thinkholic** [comment]
@develar yes I did.

and I'll update the issue later tonight after trying the workaround you have mentioned in #2030 
Thanks!.

**Comment by thinkholic** [comment]
Tried with `"extends": null`. still the same.

@develar

**Comment by thinkholic** [comment]
Changed `--em.main` path to `public/electron.js` in `package.json` and then build was successful.

Now getting another error when I running installed app on my mac, but build error has fixed.

**Comment by DanCarl857** [comment]
I have tried adding `"extends: null` and also already had `--em.main` path to `public/electron.js` in `package.json` and my build still fails. Any other ideas, I could try?

**Comment by F-Petersen** [comment]
try script:
build -c.extraMetadata.main=<path/to/electron.js>

**Comment by patarapolw** [comment]
Somehow, setting `files` work

```
"build": {
    "files": [
      "dist/**/*",
      "package.json"
    ],
}
```

**Comment by zcmgyu** [comment]
@patarapolw Thanks a lot. "build/**" not work for me, but "dist/**/*" works like a charm

**Comment by Dar0n** [comment]
Adding path to my electron-starter file in the "file" section worked for me.
https://github.com/electron-userland/electron-builder/issues/2955
```
"build": {
    "appId": "com.example.electron-cra",
    "files": [
      "./build/**/*",
      "./public/electron-starter.js"
    ],
    "directories": {
      "buildResources": "assets"
    }
  },
```

**Comment by stevenroussey-desiclabs** [comment]
Simply adding "react-scripts" to the base project will cause this error.

**Comment by vlory73** [comment]
Not sure this will help much, but (in my case) I found that my preelectron-pack was not executing correctly, thus not creating the build folder.

I followed a derived instruction from the mentioned by the OP and found that the **build** folder wasn't there.

As I use npm, I changed the line `"preelectron-pack": "npm run-script build",` and it solved the issue for me.

**Comment by cperthuis** [comment]
same problem, `"preelectron-pack": "npm run build",` fixed the issue.

**Comment by kvsur** [comment]
> Somehow, setting `files` work
> 
> ```
> "build": {
>     "files": [
>       "dist/**/*",
>       "package.json"
>     ],
> }
> ```
it works after do this， thank you so much!!!

**Comment by kvsur** [comment]
> Somehow, setting `files` work
> 
> ```
> "build": {
>     "files": [
>       "dist/**/*",
>       "package.json"
>     ],
> }
> ```

@patarapolw It  work for we , thanks

**Comment by roshad** [comment]
I'm getting this error cos I didnt build my cra first.

**Comment by IlimaVIP** [comment]
Tried everything... for me solution was just to rename the file itself public/main.js to public/electron.js and as well as updating "main": "public/electron.js" in package.json

after this update (which means that it wasn't complaining anymore about not finding electron.js file 🎉)  I moved on to another error for the wrong code sign 😩...

**Comment by mqliutie** [comment]
It seems depend on what the main field is set in `package.json`.

**Comment by jiangyv1718** [comment]
FYI,remove the   "react-scripts": "^3.4.0" from  dependencies works for me

> Simply adding "react-scripts" to the base project will cause this error.

**Comment by tronghieu60s** [comment]
> Simply adding "react-scripts" to the base project will cause this error.

Yes, it's worked for me. Remove the "react-scripts": "^3.4.0" ==> Fix.

**Comment by sage9731** [comment]
> FYI,remove the "react-scripts": "^3.4.0" from dependencies works for me
> 
> > Simply adding "react-scripts" to the base project will cause this error.

That's helpful for me too, thanks!

**Comment by jubalm** [comment]
This seems very silly but I just realized running react-scripts was clearing the entire **build** folder which is where i set the compiled **main** script to output as well. simply swapping the build order and running them synchronously fixed my issue.

**Comment by ANG95** [comment]
agregar en el pakage.json
"files": [
      "build/**/*",
      "node_modules/**/*",
      "./public/electron.js"
    ],

**Comment by hot-gril** [comment]
Removing `react-scripts` from my package.json deps fixed it for me. No idea why.

**Comment by zwhitchcox** [comment]
I don't understand why it just assumes the entry file is `build/electron.js`, and there is no way to change that. I guess I just have to restructure my entire project, when they could have just given you the option to change the entry file.

It wouldn't be *as* big of a deal if I knew this was going to work, but as of now, this is the third packager I've tried, so the odds aren't looking good.

**Comment by Anbifa** [comment]
Like some people pointed out, `react-scripts` causes the issue. And according to the documentation, this seems to be expected behavior

> _extends_ String - The name of a built-in configuration preset or path to config file (relative to project dir). Currently, only react-cra is supported.
 If react-scripts in the app dependencies, react-cra will be set automatically. Set to null to disable automatic detection.

It seems to sneak a `react-scripts build` into the `electron-builder` command. Interestingly enough, the react-scripts fails for me if run separately, but not when wrapped into the original command. Anyways, you end up with the intransparent `"build/electron.js" file does not exist` error.


Like the documentation says, disabling **_extends_** in the built settings helped for me


**package.json**
```
{
  ...
  "build": {
    "extends": null,
    ...
  }
}
```

**Comment by ericblade** [comment]
having similar issue here, but it's calling the entrypoint "index.js", which does not correspond to anything in my project, at all.  The package.json points to main as "build/main.js".  Inside the asar file, are a small collection of node modules I've never heard of, and absolutely nothing else.  It's like builder is just completely ignoring everything inside the configuration it claims it's loading.  

I'm so very confused.

And the documentation is incomprehensible.

**Comment by dperetti** [comment]
@ericblade yeah electron-builder is really powerful but the documentation is super messy.
The problem I just faced is that by default, `extraMetadata` seems to set `main` to `"main.js"`.
Like this:
```json
extraMetadata: {
    "main": "main.js",
  }
```
... and it overrides the value that is set in your `package.json`, which is really unexpected.

**Comment by usman250994** [comment]
For me it solved by :
pass in the entry file path externally, using files param
then over write the "main"  with that file name using extraMetadata param

as follows:

`"build": {
    "appId": "com.electron.xxx",
    "mac": {
      "category": "your.app.category.type"
    },
    "files":[
      "./main.tsx"
    ],
    "extraMetadata": {
      "main": "main.tsx"
    }
  }`

**Comment by geelus** [comment]
If you are like me and neither of the above solutions work, simply remove the "files" section completely and it'll start working magically!

**Comment by buchey8070** [comment]
> If you are like me and neither of the above solutions work, simply remove the "files" section completely and it'll start working magically!

True words! I like this kind of magic!

**Comment by FangPengbo** [comment]
https://www.hi917.com/detail/325.html

解决了我的问题

**Comment by mifi** [comment]
For those wondering why it's looking for `build/electron.js` and `extraMetadata` override works:
https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/app-builder-lib/src/presets/rectCra.ts#L19

**Comment by ChristophAckerl** [comment]
What worked for me was to just run 

`npm run build`

before running, for example

`npm run electron-builder --win --x64`

**Comment by TomYeoman** [comment]
This problem drove me mad for a while (my server is built into the non default path of `build/server/electron.js` instead of just `build/electron.js`). for some reason setting "main" wasn't working, the only thing that worked was as per @mifi additional info.

```
  "build": {
    "extraMetadata": {
      "main": "build/server/electron.js"
    }
  }
```

**Comment by AliGhelichkhani** [comment]
> If you are like me and neither of the above solutions work, simply remove the "files" section completely and it'll start working magically!

@geelus Thanks for your help, it works for me.

**Comment by nswon** [comment]
<img width="505" alt="스크린샷 2023-10-13 오전 11 09 03" src="https://github.com/electron-userland/electron-builder/assets/80371249/4a0194c3-52dc-4003-8cc8-d5399d4639d1">


I can't fix this problem, but I think this discussion above could be a hint.
help me!

**Comment by qzw881130** [comment]
```
  "build": {
    "appId": "com.zhiwei.boxnewapp",
    "productName": "Box New App",
    "directories": {
      "output": "dist"
    },
    "asar": true,
    "files": [
      "./dist/**/*",
      "package.json",
      "./electron.js",
      "./assets/**/*",
      "./esrc",
      "./preload.js",
      "./db.sql"
    ],
    "extraMetadata": {
      "main": "electron.js"
    },
    "win": {}
  },
```

i added this code, it works.  "electron.js" is entry file.

```
    "extraMetadata": {
      "main": "electron.js"
    },
```

**Comment by hoyame** [comment]
### Problem

When building the application, you encounter the following error:

```
⨯ Application entry file "build/electron.js" in the "/Users/hoyame/Env/main-app/dist/mac-arm64/my-react-app.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration. failedTask=build stackTrace=Error:
```


### Solution

To resolve this issue, follow these steps:

1. **Duplicate the `main.js` file:**

    Duplicate the `main.js` file located in the `public` directory and rename the copy to `electron.js`.

    ```sh
    cp main.js public/electron.js
    ```

2. **Rebuild the application:**

    After duplicating the file, rerun your application's build command.

This should resolve the configuration issue and allow the application to find the correct entry file.

**Comment by Klencodes** [comment]
putting this in package.json
"main": "electron/main.js",

"files": [
      "dist/app-name/**/*",
      "electron/**/*",
      "package.json"
    ],
works for me
