### ISSUE TITLE
Pb with nsis custom script 

### ISSUE THREAD

**Issue by jeremco** [electron-userland/electron-builder#2406]
* **Version**: 19.49.2

* **Target**: Win32, on MacOSX High Sierra

Hi

I try to use a custom script for nsis, using script option. 
I have a pb, the nsis build is in error : File: "${UNINSTALLER_OUT_FILE}" -> no files found.

I have not the UNINSTALLER_OUT_FILE in my scripts (i have copied the nsis template and replaced reference to ${UNINSTALLER_OUT_FILE} by uninstall.exe)

I think the pb is that using makensis,current path is in electron-builder nsis template, so makensis is using official scripts, not my script

Here are the logs : 

[nsis.log](https://github.com/electron-userland/electron-builder/files/1578461/nsis.log)

Jérémie

**Comment by develar** [comment]
Please provide your custom script.

**Comment by jeremco** [comment]
Hi 

As I said, i have just took the template nsis script from electron builder and replaced UNINSTALLER_OUT_FILE with uninstall.exe. Here is the archive of the script

I reference it in my package.json : "script": "./nsis/installer.nsi"
[nsis.zip](https://github.com/electron-userland/electron-builder/files/1610930/nsis.zip)

Thanks 
Jeremie

**Comment by meekaah** [comment]
did you manage to get it working? i'm having the same issue... can't seem to figure it out

**Comment by jeremco** [comment]
Hi,

Sorry for the late answer. No I did not. 
Is there any evolutions on this issue ?
