### ISSUE TITLE
Can't install the app with non-admin user (custom nsis script) 

### ISSUE THREAD

**Issue by vxsx** [electron-userland/electron-builder#2408]
* **Version**: 19.48.3
* **Updater version**: 2.17.2
* **Target**: nsis

 
Not sure if it's an issue with the builder or not, but - I'm trying to install my app with admin privileges (and run it also with admin privileges)
For that, i've been using following include:

```
!macro customHeader
    RequestExecutionLevel admin
!macroend
!macro customInit
    WriteRegStr HKLM "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
                    "$INSTDIR\${PRODUCT_FILENAME}.exe" "RUNASADMIN"
    WriteRegStr HKCU "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
                   "$INSTDIR\${PRODUCT_FILENAME}.exe" "RUNASADMIN"
!macroend
```

This was working correctly with electron-builder version 17.1.2 before.

What happens now is the installer asks for password before start, but then fails with following error:
```
C:\Users\$adminUsername\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\$appname.lnk

Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item.
```

My guess is it tries to install shortcuts for the user who granted the admin rights instead of current user, but have no idea where to look to fix it.

I'm sorry if this is the wrong place (or if I'm doing something really really wrong). Would appreciate any help.

**Comment by DarkJ24** [comment]
Have a look at this link, it might help you: https://www.easeus.com/data-recovery/windows-cannot-access-the-specified-device-path-or-file.html
