### ISSUE TITLE
Update loop does not update application

### ISSUE THREAD

**Issue by KrzysZG37** [electron-userland/electron-builder#2409]
electron-updater
Version: 2.17.6

electron-builder
Version: 19.49.0

I have a problem with automatic update of application. Updates resists on S3, and my application finds the newest version properly. But after update, it probably does not update application at all, and starts the entire process again:

Here's my code snippet:

`const {autoUpdater} = require("electron-updater");
if(!isDev){
  app.on('ready', function()  {
    log.info(autoUpdater.currentVersion);
    autoUpdater.checkForUpdates();

    autoUpdater.on('update-downloaded',function(info) {
      setTimeout(function() {
         autoUpdater.quitAndInstall();
      }, 100);
    });
}`

**Comment by saatana97** [comment]
I got the same problem,my app can check update success and finish download,but it do not install new version after app quit,the only way is run app as administrator by self

**Comment by KrzysZG37** [comment]
@saatana97  Did you resolve the problem? I am still facing it.

**Comment by luismiguelprs** [comment]
Same problem...
Apparently here the problem happened when the update was generated from a different machine than the previous version.

**Comment by akashnimare** [comment]
Getting the same issue on electron-builder v20 also.

**Comment by radreamer** [comment]
same here, but only for macOS: https://github.com/electron-userland/electron-builder/issues/3067

**Comment by playengineio** [comment]
Anyone found a solution to this issue?
