### ISSUE TITLE
assign the win-unpack and nsis.exe to different directories(question)

### ISSUE THREAD

**Issue by daffylumampao** [electron-userland/electron-builder#2410]
On build, can you assign the win-unpack and nsis.exe to different directories?

**Comment by develar** [comment]
What do you mean? For what? Currently, only root output directory can be configured.

**Comment by daffylumampao** [comment]
What i mean is for example, the .exe file is found in “test1” folder, while the win-unpacked is found on “test2” folder.

**Comment by develar** [comment]
Not possible for now. Please describe use case.

**Comment by daffylumampao** [comment]
On build, you can have an option to separate your .exe file and your win-unpacked to a different path. That's how I describe it I guess.

**Comment by daffylumampao** [comment]
follow up question @develar, is there a way to just disable the win-unpacked?

**Comment by develar** [comment]
You can simply ignore this dir.

**Comment by daffylumampao** [comment]
Hi @develar, I think we can close this since I did a workaround for it programmatically. I just used [mv](https://www.npmjs.com/package/mv) of npm and used it to transfer where I wanted the .exe file to be.

**Comment by develar** [comment]
Could you please explain for what? Why out directory should not contain intermediate results?
