### ISSUE TITLE
Unable to publish when setting endpoint url to CloudFront

### ISSUE THREAD

**Issue by miickel** [electron-userland/electron-builder#2414]
* **Version**: 19.49.0

* **electron-updater version**: 2.17.6

We have this app that we're about to distribute globally using S3 + CloudFront.

S3 is setup correctly and I can publish as usual using `build --mac --win -p always`, but if I set the `publish.endpoint` option to the CloudFront URL (e.g. https://d3tpy77yecs5fp.cloudfront.net) it fails with:

`Error: Cannot Cleanup [...] XMLParserError: Unexpected close tag`

Is S3 + CloudFront supported? Do I need to use `setFeedURL`?

Thanks

**Comment by develar** [comment]
Could you please provide full error? Is publish successful?

**Comment by bithavoc** [comment]
Cloudfront won't take S3 upload requests, so you can not point `endpoint` to cloudfront.

However, it'd be really great to allow specify the front-end `url` for distribution. I know `GenericServerOptions` has an option for this.

**Comment by develar** [comment]
@bithavoc You can set 2 publish providers, first one will be used for electron-updater, all will be used to publish (so, as you said, just use GenericServerOptions for CouldFront).

**Comment by bartoszhernas** [comment]
Did anyone get this working? What I am really looking for is:
1) Upload to S3
2) But download from CloudFront via autoupdate.

Is it enough to set up GenericServer (CloudFront) as first on the list, and S3 as second? Then publish will upload to S3 all files, but use CF to fetch the files?

**Comment by shadow-light** [comment]
You can set the publish config as S3 in `package.json` but then in your Electron script overwrite the config with a generic one for your cloudfront:

```js
autoUpdater.setFeedURL({
    provider: 'generic',
    url: 'https://anydomain.com/',
})
autoUpdater.checkForUpdatesAndNotify()
```

**Comment by KomTak001** [comment]
I was investigating a similar case.
The solution is similar, but in my case I also had to specify a "channel".
This is because we used the development build tag name `X.Y.Z-dev`.
In this case, the uploaded feed check yml file will be generated in `dev.yml`.
For production builds, the tag will be `X.Y.Z`, so` channel` will be `latest`.

```
    Public: Public:
      -Provider: s3
        Region: [s3 Region]
        Bucket: [s3 bucket]
        Path: [s3 upload prefix]
        acl: private
```
```
        autoUpdater.setFeedURL ({{
          Provider: "Generic",
          url:
            "https: // [CDNDomain] / [s3 upload prefix] /",
          Channel: "dev",
        });
```
