### ISSUE TITLE
electron-updater(onError): err param without code property

### ISSUE THREAD

**Issue by gmanriqueUy** [electron-userland/electron-builder#2415]
* **Version**: 
19.59.2

* **Version of electron-updater**:
2.17.6

* **Target**: 
Windows (*NSIS*), Linux (*AppImage*)

I'm implementing custom management of events while autoupdating. Currently I'm working on the `error` callback which gets called with an error as a parameter.

I'm almost sure that previously I was able to do something like this:

```javascript
updater.on('error', function(err) {
  switch(err.code) {
    // handle different errors
  }
}
```

But now, trying to implement missing connection error, the `err` param only have `message` and `stack` as props, but not `code` prop. Without it, it gets difficult to handle different errors.

What am I missing here?

Hope I've been concise and clear enough.

Thanks!

**Comment by develar** [comment]
`code` is an optional property.

Done — mostly all errors that thrown by updater now has `code` field. Upcoming electron-updater 2.18.1.
