### ISSUE TITLE
[Build electron app for Raspberry Pi 3]

### ISSUE THREAD

**Issue by Neewd** [electron-userland/electron-builder#2417]
Hello everyone, 

It's not an issue but more a request for help. 
I am quite a newbie on all that platform stuff. 

I chose to develop my application with Electron because I knew that was cross-platform. 
But now that I have a stable version, I want to build it, to be runnable on my Raspberry Pi 3. 

I get really confused with all that "target", "arch" etc.
Do I have to build for Linux or Debian ? Knowing that I am running on Raspbian Jessie.
I tried to find some configurations for a electron-app build for raspberry but I have found none. 

So, if anyone can tell me what option I have to set (and with what parameter if possible) to build my app for my Raspberry Pi 3 (run on Raspbian) it would be amazing ! 

Thanks !

**Comment by Chaitanyachavali** [comment]
You can build electron app for raspberry pi 3 on it's terminal!
Install electron-packager via npm. For more info check this [link](https://www.npmjs.com/package/electron-packager#installation)
`sudo npm install electron-packager -g`
On your terminal give command `uname -m`. By this you can get the architecture type.

## Understanding the command:
`electron-packager <app-root-folder-path> --overwrite --platform=<platform-type> --arch=<arch-type> --out=<output-folder-path>`

`<app-root-folder-path>`: path of the electron app folder (`/home/pi/chaitanya/electronapp` in my case)
`--overwrite`: overwrite previous builds
`<platform-type>`: OS platform (As I need for raspberry pi platform will be `linux`)
`<arch-type>`: architecture type (If you don't know about this just write the output given by `uname -m`. In my case it is `armv7l`)
`<output-folder-path>`: Path for saving build
For more flags checkout this [link](https://github.com/electron-userland/electron-packager/blob/master/usage.txt)

## Building:
`electron-packager /home/pi/chaitanya/electronapp --overwrite --platform=linux --arch=armv7l --out=/home/pi/chaitanya/electronapp/release-builds`

Now go to output folder and you can find your arm build.

**Comment by develar** [comment]
`electron-builder --linux:arm`
