### ISSUE TITLE
nsis-web: Windows 7 and above is required when installing on Windows 7

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2420]
* **Electron-builder Version**: 19.49.0

* **Target**:  Windows

When try to install in some `Windows 7` systems it returns `Windows 7 and above is required`

![image](https://user-images.githubusercontent.com/5435657/34433795-d239658c-ec68-11e7-9479-0f636b1b73e8.png)

[infsistema.zip](https://github.com/electron-userland/electron-builder/files/1592857/infsistema.zip)
[nfo-system.txt](https://github.com/electron-userland/electron-builder/files/1592858/nfo-system.txt)

**Comment by marceloavf** [comment]
Seems that version 6.1.7601 don't match any in `WinVer.nsh` specification

**Comment by tance77** [comment]
having this same issue is there a solution. @marceloavf

**Comment by marceloavf** [comment]
No solution yet @tance77

**Comment by WesamMikhail** [comment]
any update on this? some of our users have been facing the same issue!

**Comment by tance77** [comment]
https://github.com/electron-userland/electron-builder/issues/2681 this is relatead

**Comment by WesamMikhail** [comment]
@tance77 some of our users did some testing and it seems as if running the app in compatible mode as windows server 2008 solves the issue. It isn't really a fix but just thought I should let you know

**Comment by tance77** [comment]
@WesamMikhail Thank you I will let our users know this too.

**Comment by jiixing** [comment]
I had this issue when running the .exe after   
npm run dist:win32 

but if i then run the installer to install the .exe  the resulting .exe runs fine

**Comment by evecalm** [comment]
same problem when one user install electron app on windows 10 😥

**Comment by asinbow** [comment]
As a workaround, I patched file `node_modules/app-builder-lib/templates/nsis/common.nsh` before build phase:
```javascript
content = content.replace(/\$\{AtLeastWin7\}/g, '1  == 1');
```

**Comment by jackple** [comment]
I still have this problem. Is there any solution?

**Comment by Gallardo994** [comment]
Same issue. Any fix other than forking?

**Comment by witcher112** [comment]
@jackple @Gallardo994 one of our users had a similar issue. As it turned out, compatibility mode for Windows Vista was set for the setup. After turning it off, the setup works correctly.
