### ISSUE TITLE
AutoUpdate takes 60 seconds to fail validating signature on Windows 7 due to PowerShell version

### ISSUE THREAD

**Issue by jlgreen2012** [electron-userland/electron-builder#2421]
* Electron-builder version **19.47.1**: 

* Electron-updater version 2.16.3

* **Target**: NSIS 32bit and 64bit

On Windows 7, the ConvertTo-Json command is not available when attempting to validate the signature of the update. I see a check in the code here to handle this:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
```
export function verifySignature(publisherNames: Array<string>, tempUpdateFile: string, logger: Logger): Promise<string | null> {
  return new BluebirdPromise<string | null>((resolve, reject) => {
    execFile("powershell.exe", [`Get-AuthenticodeSignature '${tempUpdateFile}' | ConvertTo-Json -Compress`], {
      timeout: 60 * 1000
    }, (error, stdout, stderr) => {
      if (error != null || stderr) {
        try {
          execFileSync("powershell.exe", ["ConvertTo-Json test"], {timeout: 10 * 1000})
        }
        catch (testError) {
          logger.warn(`Cannot execute ConvertTo-Json: ${testError.message}. Ignoring signature validation due to unsupported powershell version. Please upgrade to powershell 3 or higher.`)
          resolve(null)
          return
        }
...
```

Reading the code, I would expect the try statement to fail after 10 seconds at most, fall into the catch and move on. However, according to my logs, it's taking an entire 60 seconds (the full timeout value of the first execFile call) to get to the `logger.warn` statement in the catch block.

This is leading to a very poor user experience, and I'm hoping the issue might be clearer to you than to me. Is there a way to make this fail faster? Thanks!

**Comment by develar** [comment]
We don't check Windows version because user can update PS. But in case of error we can just return null if `winVersion.startsWith("6.") && !winVersion.startsWith("6.3")`.

**Comment by develar** [comment]
Timeout reduced from 60 to 30 seconds.

**Comment by develar** [comment]
2.18.2
