### ISSUE TITLE
Is there a nice way to unpack an npm package with its dependencies?

### ISSUE THREAD

**Issue by TomRomanowski** [electron-userland/electron-builder#2422]
* **Version**: 19.49.2

* **Target**: Windows(NSIS), Mac(ZIP)

I want to unpack an npm package, **java**, with its dependencies. Currently, I am doing:
```json
"asarUnpack": [
  "node_modules/async/**/*",
  "node_modules/find-java-home/**/*",
  "node_modules/glob/**/*",
  "node_modules/java/**/*",
  "node_modules/lodash/**/*",
  "node_modules/nan/**/*"
],
```
**async**, **find-java-home**, **glob**, **lodash**, and **nan** are **java**'s dependencies. Is there a better way to do this?

**Comment by develar** [comment]
No, for now you have to specify all deps explicitly. Help-wanted.
