### ISSUE TITLE
How does electron building behave when executing builder with `-wl` params?

### ISSUE THREAD

**Issue by jhnferraris** [electron-userland/electron-builder#2427]
I'm quite curious on how 

```
$ build -wl

```

behaves. Is it concurrently build windows and linux installer at the same time or it builds windows then linux installer?

The reason why I'm asking is that when I execute `build -wl` it eats up all of my memory therefore blocking me to do other coding jobs. thanks for the insight. :)

**Comment by develar** [comment]
Yes, concurrently. Windows NSIS target is CPU hungry, because of lzma2 compression. Remote AppImage is also CPU hungry, because of zstd compression. And memory — because of used dict size.

If you just want to produce development builds — you can try to pass `--config.compression=store` to disable compression (not applicable in all cases).

**Comment by jhnferraris** [comment]
@develar  What's your suggested CPU and RAM spec for a "builder machine" taking into account the CPU and memory requirement of electron builder?

**Comment by develar** [comment]
Well... Do you aware of https://github.com/electron-userland/electron-build-service? Why do you need to setup own build machine instead of some cloud service (Travis and so on)?

**Comment by develar** [comment]
> CPU

doesn't matter. Build will be just slow if CPU not powerful.

> Memory

Due to lzma2 dist size, 1 GB of RAM is recommended. But... most of out targets doesn't use large dict size anymore (for differential updates we set dict size to 4M instead of 64-64M). e.g. portable uses, but nsis not.

**Comment by jhnferraris** [comment]
@develar I am not aware of the Build service. I was asking because we're planning to setup a Jenkins CI on an EC2 for building electron apps. 

Thanks for the inputs.
