### ISSUE TITLE
Windows: Failed to modify resources

### ISSUE THREAD

**Issue by jkudish** [electron-userland/electron-builder#243]
Trying to build an app for Windows, from Windows, I get a "Failed to modify resources" error. See [full log here](https://gist.github.com/jkudish/f8173ac4bef7eb1b354a)

Seems to be related to https://github.com/Squirrel/Squirrel.Windows/issues/488 and to https://github.com/atom/grunt-electron-installer/issues/96 though I am not positive it's the exact same error or not.

Despite the error, the build completes (but setup icon isn't set)

**Comment by jkudish** [comment]
FWIW I tried to follow the steps [here](https://github.com/atom/grunt-electron-installer/issues/96#issuecomment-194786617) but that didn't help.

**Comment by develar** [comment]
@jkudish Looks like icon is missed, see https://github.com/loopline-systems/electron-builder#in-short about icons (step 2 "icon.ico (Windows app icon)").

**Comment by jkudish** [comment]
I have the URL specified as per the documentation in my `app/package.json` not in the main development `package.json`. Should it be in both?

**Comment by develar** [comment]
Under the hood we also set `setupIcon` (https://github.com/electronjs/windows-installer#usage)  So, file `build/icon.ico` must exists. Do you have it?

**Comment by jkudish** [comment]
Yep, I have the file, and I have it in my config too:

```
"build": {
        "iconUrl": "https://app.theimagesalon.com/public/imgsalon.ico",
        "osx": { ... },
        "win": {
            "title": "The Image Salon",
            "publisher": "The Image Salon",
            "authors": "The Image Salon",
            "iconUrl": "https://app.theimagesalon.com/public/imgsalon.ico",
            "setupIcon": "build/icon.ico"
        }
    },
```

**Comment by jbleuzen** [comment]
I have the same error when building on a Win10 VM (x64). On another VM Win7 (ia32) we don't have this problem....

**Comment by jkudish** [comment]
Hmm good to know @jbleuzen -- I'll try a Win7 VM

**Comment by jkudish** [comment]
Tried in a Win7 VM (ia32). Same problem.

**Comment by jkudish** [comment]
Is the `.ico` supposed to be a certain size? Mine is 256x256 but wondering if that's the issue?

**Comment by jkudish** [comment]
Seems to be related to the VM setup. I tried again on a native windows machine from a friend and the app compiled without any problems there. Will try to figure out what about the VM is being problematic.

**Comment by develar** [comment]
Reopened — I am going to check some option values on electron-builder side because Squirrel.window produces unclear ugly error messages.

Yes, icon must be at least 256 size.
