### ISSUE TITLE
PDBs are invariably ignored

### ISSUE THREAD

**Issue by computerquip-streamlabs** [electron-userland/electron-builder#2433]
* **Version**: 19.51.0
* **Target**: x86_64 Windows

We've begun to ship PDBs with our builds to ease debugging pains. Recently, we changed a native module to act as an actual node_module but noticed that whenever it's copied, all PDB files are ignored, regardless of inclusion rules. This isn't listed as one of the default exclusions in the docs (here: https://www.electron.build/file-patterns) but it's in the implementation found here: https://github.com/electron-userland/electron-builder/blob/c050b5206fc86584271644674590c31292d41f14/packages/electron-builder-lib/src/fileMatcher.ts#L160

This is problematic since this seemingly can't be turned off. I can provide a PR that removes the PDB exclusion if that's the correct solution.

**Comment by computerquip-streamlabs** [comment]
Is there any word on this? This has really screwed up our programming flow. I can make a fix but I'd like to know the intention here before just throwing code up in a PR.

**Comment by develar** [comment]
Set `includePdb` to `true` (19.55.2).
