### ISSUE TITLE
Question: Users have no ~/.aws/credentials file, yet are able to update

### ISSUE THREAD

**Issue by naheller** [electron-userland/electron-builder#2439]
Hi @develar and crew --

I have a question about AWS credentials when publishing to a _private_ S3 bucket. I understand that, as a developer, my credentials are used to publish the app to S3. However, how are my users able to retrieve updates without having credentials of their own?

My coworkers are using this app, and many have no ~/.aws/credentials files, yet they are able to get updates from the private S3 bucket where I provide the app.

How are users able to do this? Thanks!

**Comment by develar** [comment]
Because defaul ACL is public.

https://www.electron.build/configuration/publish

> acl = public-read "private" | "public-read" - The ACL. Set to null to not add.
