### ISSUE TITLE
Missing documentation: extraFiles / extraResources

### ISSUE THREAD

**Issue by lzkelley** [electron-userland/electron-builder#2442]
I'm having problems running a python backend once my application is packages into a MacOS app.  I think the problem is effectively the same as [this stackoverflow post](https://stackoverflow.com/questions/41199981/run-python-script-in-electron-app) which suggests some `asar` stuff, or alternatively to use `extraResources`.  The [documentation for extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources) seems to be missing from the updated docs, but judging from newer 'Issues' it looks like this has been deprecated in place of `extraFiles`... is that accurate, or are these different things?

The [old documentation can be found here](https://github.com/electron-userland/electron-builder/wiki/Options/0887791855c27cc73500cc0df58718482a12c533).

Are these arguments documented anywhere else, or could some of the old documentation be moved over to the new site?

Finally: users as ignorant as myself may be a small minority, but I would definitely find it extremely helpful to have some example use cases of how/when/why to include external files and packages in the distributions.  It seems to be pretty easy to get setup in an electron development environment (i.e. just running the source files directly), but once things move to packages it adds a whole new layer of complexity.

Thanks!

**Comment by develar** [comment]
Why missed? Please see https://www.electron.build/configuration/configuration

**Comment by lzkelley** [comment]
@develar 🤦 sorry!
