### ISSUE TITLE
snap classic confinement can't be used on Mac because of Docker issue

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron-userland/electron-builder#2445]
Hello,

I just got following promising email from Snapcraft team 

> We had hoped to feature easy-disk-cleaner in GNOME Software and on the Ubuntu Twitter account, but it's currently set up as a strict confinement snap. This means that it cannot see directories outside of $HOME.
> 
> Would you be amenable to setting `confinement: classic` and pushing a new revision? I'd happily shepherd you through the approval process for classic confinement.

I was succeeded with building `snap` package on Mac earlier with default `strict` confinement. 
https://www.electron.build/configuration/snap

But had an issue while trying to build snap on Mac with `classic` confinement as requested in the email

```
classic confinement requires the core snap to be installed. Install it by running `snap install core`.
Error: docker exited with code 2
    at ChildProcess.childProcess.once.code (/usr/local/lib/node_modules/electron-builder/node_modules/builder-util/src/util.ts:241:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
```

This is apparently Docker issue, but not electron builder. But I quite stuck while fixing it, so kindly asking for help.

**Comment by develar** [comment]
Hi.

> snap install core

Never heard about it. Ok, our docker images will be updated to pre-install `core` snap.

**Comment by develar** [comment]
Works for me now. `confinement: "classic",` Please check.

**Comment by vasyl-shumskyi** [comment]
Awesome. Thank you so much @develar Will give it a try!

**Comment by vasyl-shumskyi** [comment]
Can't use https://github.com/electron-userland/electron-builder/releases/tag/v19.56.0 because of icons issue https://github.com/electron-userland/electron-builder/issues/2570 to verify if it works.
