### ISSUE TITLE
Help in building app without downloading electron from github

### ISSUE THREAD

**Issue by myfrndjk** [electron-userland/electron-builder#2448]
19.52.1

* **Version**: No

2.9.4

* **Target**: windows

When I try to build electron in my environment linux host I am getting following error.
`getaddrinfo ENOTFOUND github.com github.com:443`

On checking the log I found that builder is trying to download electron from github instead of using it from dependencies.Is there a way to use electron which is present inside node_modules or how do i fix that `getaddrinfo ENOTFOUND github.com github.com:443` issue, I guess that issue caused by proxy issue.

Thanks
Jk

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-download about setting mirror or cache location.

**Comment by myfrndjk** [comment]
Hi,

Thanks for reply I read that unfortunately cant make it work.
I tried this line in my package.json 
`"release": "set ELECTRON_CACHE=/root/.cache/electron && set ELECTRON_CUSTOM_DIR=./node_modules/electron/ && chmod -R +x node_modules && build --win --publish always",`


Still it tries to download electron from github only.
It would be great if you provide some sample / right way of doing it.

Thanks
Jk

**Comment by Ajeey** [comment]
You can set the mirror via package.json
```
"build": {
   "electronDownload": {
      "mirror": "https://xxx/electron-binaries/",
      "quiet": false,
      "verifyChecksum": false
    }
}
```

**Comment by myfrndjk** [comment]
@Ajeey Thanks for the help.It helped to an extend.Seems download is not supported in by host.
Is there a way to use downloaded/local electron.zip file for build.
I added electron zip inside resources and tried below code 
```

    "electronDist":"resources/electronzipfiles/",
    "electronDownload": {
      "quiet": false,
      "verifyChecksum": false,
      "cache":"~/.cache/electron/"
    } 
```

Now it is not trying to download `electron` by tries to download `codesign` and again fails.
If i tries to add codesign.z inside resources no use still it is trying to download from git hub.
Not sure how to add those dependencies in local


Thanks
Jk

**Comment by myfrndjk** [comment]
similar issue https://github.com/electron-userland/electron-builder/issues/1859

**Comment by mandyr** [comment]
@myfrndjk were you able to solve this issue? I am facing the same problem with winCodeSign-1.9.0 and I took the same steps you did.

**Comment by develar** [comment]
@mandyr Please try version 20.8.0

**Comment by rajshak123** [comment]
@develar I also have the same issue.It downloads electron from repo even though i already have electron in npm_modules.Is there any flag which can point to local installation of electron instead of downloading it everytime a new build is initiated?

**Comment by GKSONG** [comment]
In my case (electron-builder : 20.44.4), the following configuration works.

C:\Users\xxx\AppData\Local\electron-builder\cache
     winCodeSign\winCodeSing-2.4.0
     nsis\nsis-3.0.3.2
     nsis\nsis-resources-3.3.0

**Comment by amt-work** [comment]
@GKSONG Can you post the package.json you used to make this work? I'm struggling trying to figure it out.

**Comment by vanminhquangtri** [comment]
@myfrndjk have you solved the problem yet? I got same problem and would like to hear any advice from you. Thank you.

**Comment by myfrndjk** [comment]
Hi all,

I never solved this issue.
Thanks

**Comment by vanminhquangtri** [comment]
Thank @myfrndjk
For me it works when in package.json, add build property. assets is the folder where we place the zip file of electron.
```

"build": {
    "electronDownload": {
      "cache": "./assets",
      "isVerifyChecksum": false,
      "platform": "win32"
    }
  }
```
