### ISSUE TITLE
`react-scripts` dependency excluded from output bundle

### ISSUE THREAD

**Issue by timkendrick** [electron-userland/electron-builder#2449]
* **Version**: 19.52.1

* **Target**: mac

I'm currently working on an Electron app that allows users to compile their own React projects. One of the dependencies of the app is `react-scripts`.

I couldn't figure out why the `react-scripts` dependency was being excluded from the output bundle, even though it is listed as a `dependency` of the main app (not a `devDependency`).

After trying all sorts of increasingly crazy attempts to get my project building, I finally managed to track this down to Electron Builder's set of `knownAlwaysIgnoredDevDeps` [in electron-builder-lib/util/packageDependencies.ts](https://github.com/electron-userland/electron-builder/blob/72c48cd9f353bc034c600a1305057e6384ef1a30/packages/electron-builder-lib/src/util/packageDependencies.ts#L30-L37). When I manually edit the electron-builder code and remove `react-scripts` from this set, it is copied into the output correctly.

Does this mean that these exclusions are incorrectly being applied to `dependencies`, not just `devDependencies`?

**Comment by develar** [comment]
Removed from `knownAlwaysIgnoredDevDeps`.

**Comment by timkendrick** [comment]
Thanks for the fix!

My only slight concern is that this issue could potentially also apply to any of the other dependencies in that list (e.g. `jest`).

I guess ideally electron builder could figure out which packages to filter out by checking against the `package.json` and seeing which are `devDependencies` and which are `dependencies`, and not including the `devDependencies`?

Or alternatively, maybe this list could be configurable so that you can override the default list if your app has unusual requirements?

Thanks for making the fix though, it fixes my problem at least!

**Comment by develar** [comment]
Why jest can be required?

**Comment by timkendrick** [comment]
Jest might be required e.g. if you're building a jest test runner GUI app for writing quick TDD-style experiments/fiddles.

I imagine that in this scenario you'd want to bundle the `jest` library to avoid having to set up a whole new npm project each time you launch the app.

**Comment by develar** [comment]
Already excluded from list :) Thanks for explanation.
