### ISSUE TITLE
docker: poorly formatted environment:variable in travis (TRAVIS_COMMIT_MESSAGE)

### ISSUE THREAD

**Issue by quantumkv** [electron-userland/electron-builder#2450]
* **Version**: 19.49.2 

* **Target**: Windows and Linux using Docker.

While building for windows and linux using docker on trusty environment in travis, i am getting this error: 

`docker: poorly formatted environment: variable 'Refactored Settings system by moving it from dexie to JSON. Results in less complexity and efficiency as listeners are removed.' has white spaces.`

I have used the travis config as provided in the docs sample project. The builds were running fine with the same config before. Between the last successful build and the current build, the .travis.yml file has not been touched at all.

The mac builds are working perfectly, so I assume the error is due to some config issue.

**Comment by develar** [comment]
Please show result of  `env`  command (except TOKEN and other passwords).

**Comment by szeck87** [comment]
@quantumkv How did you determine that TRAVIS_COMMIT_MESSAGE was the cause?  I think I have a similar issue with that variable causing OSX builds to fail.

**Comment by quantumkv** [comment]
The error I got referred to my git message string. After some googling i found out that docker has a well documented issue with newlines when any such text is passed to --env-file

The error you are getting with TRAVIS_COMMIT_MESSAGE might be due to newlines in you git commit message. Keeping your newlines as LF instead of CRLF might solve the issue.

**Comment by szeck87** [comment]
GitHub PR merges are pre-filled and formatted that way.  I noticed when going through your old Travis builds that were failing that your commit messages were structured the same way.

We're just blanking out that variable in Travis now until (or if) we figure out what the actual problem is.  But I was just curious if this was something similar and if you found a root cause.

**Comment by Clover-Lindo** [comment]
@xsokaris I found another way here https://github.com/moby/moby/issues/12997#issuecomment-307665540

Here's my full script:
```
  npm run build:prod
  ENVS=`env | grep -iE '^(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)([A-Z]|_)*=' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run $ENVS --rm \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "npm run release:linux && npm run release:win"
  else
    npm run release:mac
  fi
```

Istead of passing vars with --env-file, it creates a list of `-e VAR1 -e VAR2`, and docker will be able to find the value of each itself.
I also fixed the regex so it only takes vars **starting by**, and not only containing "DEBUG", "NODE_" etc.

Eventually you'll have to add your environment variable pattern if it is not already matched by the regular expression.

**Comment by johannesjo** [comment]
@Clover-Lindo this somehow leaves out my tokens (GH_TOKEN in this case).

**Comment by kontrollanten** [comment]
@Clover-Lindo Thanks for your line, it was the only solution that worked for me! Here's my full command

```
        docker run --rm \
         --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine-02.17 \
          /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
```
