### ISSUE TITLE
Clarify Build With Native Node Packages

### ISSUE THREAD

**Issue by sqwk** [electron-userland/electron-builder#2453]
* **Version**: 
"electron": "1.7.10",
"electron-builder": "19.52.1",
"electron-rebuild": "1.6.0",

* **Target**: 
Mac x64

I am using `electron-rebuild` to rebuild a native node package (`leveldown`) for my my dev environment. For the production build this will not include the necessary package and the app will fail on open with the error "Could not locate the bindings file". Duplicating the necessary package to the second application `package.json` (two package structure) and adding `electron-builder install-app-deps` before the actual build process fixes this issue.

In both cases the following is required as part of the webpack config:

    externals: {
        'leveldown': 'require("leveldown")'
    }

Is this how this is supposed to work? Effectively, I am compiling native node modules twice: Once for the dev environment using `electron-rebuild` and once for a production build using `install-app-deps`. Is there a way to simplify and use one process for both dev and production builds?

**Comment by develar** [comment]
No, you cannot use the same node_modules dir. Each time on build electron-builder will automatically rebuild app native deps for Electron version.
