### ISSUE TITLE
Publish S3 to Google Cloud Bucket

### ISSUE THREAD

**Issue by sqwk** [electron-userland/electron-builder#2456]
Has anyone got any experience publishing updates to a Google Cloud bucket instead of an Amazon S3 server? Apparently the two are interoperable? Is there any documentation on how to configure the publish and auto-update settings?

**Comment by myfrndjk** [comment]
S3 and Google Cloud  uses completely different API and authentication cant be interchanged.
builder doc: https://www.electron.build/configuration/configuration

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

If it is S3 compatible — use endpoint option. Otherwise — wait a hero who will contribute this support.

**Comment by develar** [comment]
Btw, s3 publish will be soon moved to golang instead of nodejs.
