### ISSUE TITLE
Show app installation info on installing Windows NSIS update version

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#2460]
* **Version**: 19.52.1
* **Electron-updater version**: 2.18.2
* **Target**: nsis

Hi! I found the following issue:
When we download an update and then just exit the application, it is updated in the background. But it may be not obvious for the user. And if the user tries to open app during such update, we get an error:
![image](https://user-images.githubusercontent.com/9727404/34817519-4fcded6e-f6c9-11e7-8a98-5e9013be52c8.png)
After that application seems to be installed, but when it is launched, it has old version.

I also checked it using older version of electron-builder (19.49.0) and updater (2.17.6). In this case after user tries to open app during installation, he just sees that shortcut is not available. When update is installed, app is launched with new version.

**Comment by develar** [comment]
Nothing is changed, it just a timing issue.

**Comment by clusterberries** [comment]
@develar it is strange, because I can't reproduce error with 19.49.0 version, tried several times.
