### ISSUE TITLE
scripts getting removed from package.json

### ISSUE THREAD

**Issue by sekar-worx** [electron-userland/electron-builder#2461]
* **19.45.1**: 

* **Linux**: 

scripts objects is removed from package.json. Basically it should be configured from builder options.

**Comment by develar** [comment]
Could you please describe use case?

**Comment by sekar-worx** [comment]
I am using electron builder to generate the build. In this my use case it was a rapid application development tool there i need to maintain the package.json script in electron builder but it is removing. It only occurs in ubuntu, mac. If it is configurable through builder options it will be useful for me.

**Comment by tulinisarg** [comment]
So we are building an IDE which comes with a "seed" app. This seed app contains a package.json where the scripts need to be preserved. We are writing workarounds for now where we change the file name while packaging and then rename it later. Like @sekar-worx said it would help if this can be configured via builder options.

**Comment by develar** [comment]
Option `removePackageScripts` added.

**Comment by sekar-worx** [comment]
@develar, Thank you very much. Can you tell how can i test this feature ?. I checked the version 19.55.3 it is not there.

**Comment by sekar-worx** [comment]
@develar Thank you very much. This feature working fine. i tested this feature using 19.56.2 version. Can you please merge this with master ?

**Comment by develar** [comment]
> Can you please merge this with master ?

If you mean release this version as latest (not as next on NPM), it cannot be done right now.
