### ISSUE TITLE
Change macOS "Standard Menu Item Actions" app name

### ISSUE THREAD

**Issue by fttx** [electron-userland/electron-builder#2468]
* Electron version: 1.7.10
* Electron builder: 19.52.1
* Target: macOS

### Given package.json

```
{
    "name": "barcode-to-pc-server",
    ...
    "build": {
        "productName": "Barcode to PC server",
        ...
    }
    ...
}
```

### Expected behavior

I expected to see the package.json>build>productName in the application menu>About/Hide/Quit
Is there another property for that?

### Actual behavior

I see the package.json>name in the application menu
![image](https://user-images.githubusercontent.com/5663423/34906909-b9c0b41e-f876-11e7-849f-e89dc49415da.png)

docs: https://electronjs.org/docs/api/menu#standard-menu-item-actions

**Comment by AhadCove** [comment]
In your main.js (Main Electron file) towards the top have 
```app.setName("Your New Name");```

https://electronjs.org/docs/api/app#appsetnamename

If that doesn't work I set productName at the top of my package.json also. Outside of build

**Comment by fttx** [comment]
`app.setName("Your New Name");` worked, thanks

**Comment by alexlyp** [comment]
Apologies for bumping a slightly unrelated issue, but is there a way to completely remove the "About ..." menu item?  I looked through the configuration documentation but didn't see anything that stood out.

**Comment by Faksprod** [comment]
@alexlyp
•1 You can set a new Menu by following this example found in [the doc here](https://electronjs.org/docs/api/menu#main-process). You can custom this Menu by adding/removing what you need.

•2 Below the condition specific for Mac OS X which is `if (process.platform === 'darwin')` you can remove the object `{role: 'about'}` and you won't see the About xxx label anymore.
