### ISSUE TITLE
Option to set minimum macOS version the app is supported on

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#2472]
* **Version**: 19.52.1

* **Target**: macOS

It's a common need to be able to define the minimum macOS version an app runs on.

Currently I use:

```json
"mac": {
  "extendInfo": {
    "LSMinimumSystemVersion": "10.12.0"
  }
}
```

But would be nicer to be able to do:

```json
"mac": {
  "minimumSystemVersion": "10.12.0"
}
```

Also because almost no one using Electron knows about this property. I have yet to encounter an open source Electron app that uses it, but I know for sure, nobody is testing their app back to macOS 10.9, which is the default target. So another argument for this small addition is discoverability.

This could potentially also be added to the [NSIS config for Windows](http://nsis.sourceforge.net/Get_Windows_version).

**Comment by jlarmstrongiv** [comment]
May also be relevant if your native modules will not run on a lower version:
```json
{
    "dist": "CXXFLAGS=\"-mmacosx-version-min=10.13\" LDFLAGS=\"-mmacosx-version-min=10.13\" electron-builder",
    "postinstall": "CXXFLAGS=\"-mmacosx-version-min=10.13\" LDFLAGS=\"-mmacosx-version-min=10.13\" electron-builder install-app-deps"
}
```
