### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#2478]
With electron 1.8 supporting arm64, I notice that electron-builder does not. Any plans? Is there anything specific holding it up?

**Comment by develar** [comment]
Nothing stops. Should be very easy.

**Comment by logidelic** [comment]
Great to hear. I've started playing on my side and if I get everything working I will contribute the updates, if this is desired.

One thing that's already stumped me: In `getAppBuilderTool()` (`electron-builder-lib/src/targets/tools.ts`), where do the checksums come from?

**Comment by develar** [comment]
So, you can send PR? Great.

> where do the checksums come from?

For what? Do you mean that app-builder doesn't support arm64?

**Comment by logidelic** [comment]
If I get it working, I will certainly send a PR. :) Stay tuned.

Regarding the app-builder support: I just saw your checkin there, and now I understand. Thanks for that.

**Comment by logidelic** [comment]
I made PRs for 7zip-bin and electron-builder itself.

However, for appimagetool (electron-builder-binaries), I have a hesitation. I have built AppImageKit and it works correctly. However, appimagetool seems to expect mksquashfs to be located at ../lib/appimagekit/mksquashfs (relative to appimagetool).

This is different from our other appimagetool binaries, which have mksquashfs in the same directory. I couldn't find any build option to achieve this. Any ideas?

(For my local setup I have the mksquashfs binary in ../lib/appimagekit/mksquashfs and it works correctly, but obviously this should be in an architecture-specific directory...)

**Comment by develar** [comment]
Also, for AppImage we need a runtime-arm64 file

**Comment by logidelic** [comment]
Hi,

`mksquashfs`: Yea, I tried putting them all into the same directory (exactly as the other architectures are setup), but then when I try to run the dist I am stopped with the following error. I wonder if newer versions of `appimagekit` hardcode the (relative) location of `mksquashfs`...

```
Error: Exit code: 1. Command failed: /home/user/.cache/electron-builder/appimage/appimage-9.0.4/linux-arm64/appimagetool --runtime-file /home/user/.cache/electron-builder/appimage/appimage-9.0.4/runtime-arm64 --no-appstream /home/user/app/dist/__appImage-arm64 /home/nvidia/app/dist/AppNm-1.5.6.AppImage

No such file or directory: /home/user/.cache/electron-builder/appimage/appimage-9.0.4/linux-arm64/../lib/appimagekit/mksquashfs
```

Runtime: Yes, I have the runtime in the right place and it works as well.

**Comment by develar** [comment]
@logidelic Please ask @TheAssassin https://github.com/AppImage/AppImageKit/pull/618

**Comment by logidelic** [comment]
Will do.

**Comment by logidelic** [comment]
Ok, managed to get this going by undefining `AUXILIARY_FILES_DESTINATION` during the build.

PR sent for **electron-builder-binaries.**

At least for my tests thus far, everything works. :)
