### ISSUE TITLE
Error: spawn hdiutil ENOENT from electronuserland/builder:wine Docker image

### ISSUE THREAD

**Issue by lduros** [electron-userland/electron-builder#2480]
"electron-builder": "^19.52.1",
    "electron-installer-dmg": "^0.2.1",

* **Version**: 

* **Target**: Windows/Linux/MacOSX

I'm running electron-builder on a Docker instance with Gitlab-CI (similar to Travis)
I get the error mentioned in the title whenever it tries to build the DMG file. This seems to make sense since hdiutil is an OS X binary. However I'm not completely sure how to address this issue when working from a GNU/Linux environment.

Here is what my "build" settings look like in package.json:
```
  "build": {
    "appId": "com.example.app",
    "directories": {
      "buildResources": "public"
    },
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": "NSIS"
    }
  }
```

Thanks for any help and guidance,

**Comment by develar** [comment]
> electron-installer-dmg

Not required. electron-builder can produce DMG.

You can build DMG only on macOS.

**Comment by MalekBouba** [comment]
I'm using the latest docker builder image on a MacOS 11.2.3, with
```
"electron": "^2.0.6",
"electron-builder": "^20.26.0",
```
Does this count as macOS or not? can I build OSX apps or not?
