### ISSUE TITLE
Include devDependencies

### ISSUE THREAD

**Issue by mk010101** [electron-userland/electron-builder#2481]
I need to include all devDependencies when packaging the app. However, I get this: 
**Error: Package "electron-builder" is only allowed in "devDependencies".**

The reason I need to include electron-builder is that the app **is** the builder (GUI of sorts). 

What would be the correct approach? Also, is it possible to avoid making users install node/npm and just include them in the App?

**Comment by develar** [comment]
Set env `ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY=true`

> is it possible to avoid making users install node/npm and just include them in the App?

You can use electron as node.

**Comment by mk010101** [comment]
Thanks for the quick response.
The env worked fine, however I'm getting another issue: the rebuilding part is not rebuilding native dependencies (7zip-bin-win is one of them). Here's my gulp code:

`gulp.task("mkexe",  ()=> {

    let config = {
        win: ["nsis"],
        mac: ["dmg"],
        config: {
            asar: false,
            npmRebuild: true,
            appId: "m.k.builder",
            files: [
                "**/*",
            ],
            directories: {
                app: "./",
                output: "./../__RELEASE_test",
                buildResources: "build"
            },
        },
    };

    process.env.ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY=true;

    builder.build(config)
        .then(() => {
           console.log("done.")
        })
        .catch((error) => {
           console.log(error);
        });


});`

I'm building on osx.
