### ISSUE TITLE
Auto Updates not working for private Github Repository: undefined URL

### ISSUE THREAD

**Issue by Arieg419** [electron-userland/electron-builder#2482]
Hi, I am using electron-builder v 19.53.7

I am packaging my electron-app for Mac OS X and Windows. I am successfully packaging the app, creating a DMG installer for mac, NSIS installer for Windows and executables for both platforms.

I am pointing to my private repository (where the source code is), where I have set up releases.

![image](https://user-images.githubusercontent.com/8246234/34994283-a87ffdec-fadb-11e7-84fd-681118c76bc9.png)

This is the build config I have set up in package.json

![image](https://user-images.githubusercontent.com/8246234/34994035-f5d224e0-fada-11e7-917f-99bec5c93e2a.png)

I have a GitHub repo scope/permission token set up as GH_TOKEN in my environment (verified).

When following the auto update flow [listed here](https://github.com/iffy/electron-updater-example) I get this error:

![image](https://user-images.githubusercontent.com/8246234/34994551-94f4cbb2-fadc-11e7-87a4-2efc78991b67.png)

The URL in the error does not exist. Am I doing something wrong, that's causing the wrong URL to be pinged? I've read through all the issues I could find, I would appreciate help in solving this.

Thank you!

**Comment by develar** [comment]
From docs:

> Only for very special cases — not intended and not suitable for all users.

Please do not use private GitHub. Otherwise you have to provide your GitHub token for all users.

So, please think twice.

> I have a GitHub repo scope/permission token set up as GH_TOKEN in my environment (verified).

Are you on macOS?

**Comment by Arieg419** [comment]
Okay I understand. I was under the impression that a private repo could work from these posts

https://github.com/electron-userland/electron-builder/issues/2314
https://github.com/electron-userland/electron-builder/issues/1393#issuecomment-288191885

I am on Mac OS X, yes. 

I want to do auto-updating without exposing my code (public repo) to the client or providing my Github token.

Do you recommend two repos - one private one for source code, and public one with just releases no source code.
https://github.com/iffy/electron-updater-example/issues/19

If so, what would files would I need in the public repo?

Thank you

**Comment by develar** [comment]
> I am on Mac OS X, yes.

So, your env is not correct. https://github.com/sindresorhus/shell-env

> Do you recommend two repos

I recommend you to use Amazon S3. It will cost you several $ (or more, if your app will be very popular). Or 5$ — DigitalOcean Spaces (250GB storage, 1TB Outbound bandwidth).

> If so, what would files would I need in the public repo?

Repository can be empty. Or just readme.

**Comment by Arieg419** [comment]
I am using the dotenv npm package and supplying my token in a .env file (that is in the .gitignore). Upon startup I am logging the GH_Token as a test and I see it properly.

Perhaps I'm not understanding correctly, but how can the repo be empty? The client is supposed to fetch the updates from there? Shouldn't it atleast contain the release artifacts?

![image](https://user-images.githubusercontent.com/8246234/34996364-121613e4-fae2-11e7-981e-3f485734749e.png)

Thank you!

**Comment by develar** [comment]
> The client is supposed to fetch the updates from there, shouldn't it at least contain the release artifacts

No. GitHub releases is used. Release artifacts not under VCS.

**Comment by apurvaSynerzip** [comment]
@develar I am facing the same issue with Github private repo, and I cannot switch to aws/s3.Can you provide solution?

**Comment by rllola** [comment]
@apurvaSynerzip We created a service just for this purpose : https://www.update.rocks/ 

Please feel free to contact us for any request.
