### ISSUE TITLE
Error: Application entry file "index.js" in the resources/app.asar does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by Nikolas1814** [electron-userland/electron-builder#2484]
My electron version is 19.53.7 and I am building for linux(x64)
The error I get is 
_Error: Application entry file "index.js" in the "/home/nikolas/Documents/ora-app/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/nikolas/Documents/ora-app/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:7:12)_

The output of this command _asar.js list app.asar_ is:
`
/LICENSE.md
/README.md
/index.html
/main.js
`
My main package.json:
```
{
  "name": "Ora",
  "productName": "Ora",
  "version": "1.0.2",
  "description": "Task management and team collaboration",
  "main": "./index.js",
  "scripts": {
    "watch": "webpack --watch",
    "dist" : "build"
  },
  "build": {
    "appId": "com.ora.ora",
    "linux": {
      "target": [
        "snap"
      ]
    }
  },  

  "devDependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "clean-webpack-plugin": "0.1.17",
    "copy-webpack-plugin": "4.2.1",
    "css-loader": "0.28.7",
    "electron": "^1.7.9",
    "electron-installer-snap": "^1.0.1",
    "electron-packager": "9.1.0",
    "eslint": "4.11.0",
    "eslint-config-dimitarnestorov": "1.1.1",
    "eslint-loader": "1.9.0",
    "extract-loader": "1.0.1",
    "file-loader": "1.1.5",
    "html-loader": "0.5.1",
    "less": "2.7.3",
    "less-loader": "4.0.5",
    "postcss-loader": "2.0.8",
    "raw-loader": "0.5.1",
    "style-loader": "0.19.0",
    "svgo": "1.0.3",
    "svgo-loader": "2.0.0",
    "webpack": "3.8.1"
  }
}
```
and the once in my app:
```
{
  "name": "ora",
  "version": "0.8.0-14",
  "description": "Task management done right! With kanban, time tracking, reports and team chat - Ora is your team's command center!",
  "main": "./index.js",
  "scripts": {
    "build": "webpack",
    "build:prod": "yarn; webpack -p --env production",
    "build:prod:sentry": "yarn; webpack -p --env production-sentry",
    "build:prod:this": "webpack -p --env production",
    "watch": "webpack --watch",
    "start": "webpack --watch",
    "watch:prod": "webpack -p --watch --env production",
    "watch:noeslint": "webpack --watch --env no-eslint",
    "watch:oradev": "webpack --watch --env oradev",
    "watch:noreload": "webpack --watch --env no-browsersync"
  },
  "browserslist": [
    "> 0.4%"
  ],
  "devDependencies": {
    "@codemotion/angular-disqus": "1.0.0",
    "@codemotion/angular-emoji-picker": "0.0.6",
    "@codemotion/angular-image-cropper": "1.0.0",
    "@codemotion/angular-mention": "0.9.24",
    "@codemotion/angular-photoswipe": "0.0.1",
    "@codemotion/angular-toast": "2.0.0",
    "@codemotion/angular-ui-bootstrap": "2.5.0",
    "@codemotion/canvas-to-blob": "1.0.0",
    "@codemotion/chunk-manifest-webpack-plugin": "1.1.2",
    "@codemotion/j-i-c": "2.0.2",
    "@uirouter/angularjs": "1.0.6",
    "ajv": "5.2.2",
    "angular": "1.6.6",
    "angular-animate": "1.6.6",
    "angular-country-picker": "2.0.1",
    "angular-drag-scroll": "git://github.com/codemotionapps/angular-drag-scroll.git#b21feb2e61fad8113456074837ccb9a26e06c5d8",
    "angular-elastic": "2.5.1",
    "angular-filter": "0.5.17",
    "angular-google-picker": "git://github.com/codemotionapps/angular-google-picker.git#3b11f415e412edfab03460eb19c364cb3cf53060",
    "angular-hotkeys": "1.7.0",
    "angular-image-dimensions": "1.1.0",
    "angular-joyride": "1.0.10",
    "angular-loading-bar": "0.9.0",
    "angular-notification-center": "git://github.com/codemotionapps/angular-notification-center.git#2c07ccf4f97812ebe41672f1c69d490f68f0a025",
    "angular-nvd3": "git://github.com/codemotionapps/angular-nvd3.git#0ee281d2167cae300501d6d2055812c341554ad5",
    "angular-recaptcha": "4.1.0",
    "angular-sanitize": "1.6.6",
    "angular-simple-number-mask": "git://github.com/codemotionapps/angular-simple-number-mask.git#3fa8a86a242ce015fde3301b560a9b37d1220d8a",
    "angular-svg-round-progressbar": "<1",
    "angular-trello-api-client": "1.0.0",
    "angular-xeditable": "0.8.0",
    "autoprefixer": "7.1.4",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-es2017": "6.24.1",
    "bootstrap": "git://github.com/codemotionapps/bootstrap.git#fe3f7bef2a880eb5c8207207d6947bd10ec2296e",
    "braintree-web": "^3.22.2",
    "browser-sync": "2.18.13",
    "browser-sync-webpack-plugin": "1.2.0",
    "chrono-node": "1.3.5",
    "clean-webpack-plugin": "0.1.16",
    "color": "2.0.0",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.28.7",
    "d3": "git://github.com/codemotionapps/d3.git#a0bf9ed03f7056a4b9e34c383fedddb91c9b58c4",
    "eslint": "4.7.2",
    "eslint-loader": "1.9.0",
    "extract-loader": "1.0.1",
    "file-loader": "0.11.2",
    "file-saver": "1.3.3",
    "gsap": "1.20.2",
    "html-loader": "0.5.1",
    "html-webpack-plugin": "2.30.1",
    "htmllint-loader": "1.3.8",
    "imports-loader": "0.7.1",
    "jsTag": "git://github.com/codemotionapps/jsTag.git#54cfa8fd19ee30ffe3d8a31af199ad709bf7fca5",
    "less": "2.7.2",
    "less-loader": "4.0.5",
    "moment": "2.18.1",
    "ng-csv": "0.3.6",
    "ng-dialog": "1.4.0",
    "ng-file-upload": "12.2.13",
    "ngclipboard": "1.1.1",
    "ngstorage": "0.3.11",
    "nvd3": "git://github.com/codemotionapps/nvd3.git#a42ff9705dcda2b12e9700eae16070c3bb602aac",
    "oclazyload": "1.1.0",
    "parse-diff": "0.4.0",
    "perfect-scrollbar": "0.8.1",
    "postcss-loader": "2.0.6",
    "prismjs": "1.8.1",
    "raven-js": "3.17.0",
    "raw-loader": "0.5.1",
    "request": "2.82.0",
    "satellizer": "0.15.5",
    "showdown": "1.7.4",
    "snapsvg": "0.5.1",
    "snapsvg-animator": "0.0.3",
    "style-loader": "0.18.2",
    "sugarss": "1.0.0",
    "svgo": "0.7.2",
    "svgo-loader": "1.2.1",
    "webpack": "3.6.0",
    "webpack-sentry-plugin": "1.14.0"
  },
}

```

**Comment by jaganathanb** [comment]
How did you solve your issue?

**Comment by Nikolas1814** [comment]
I removed "main" : "index.js" from my submodule and the problem disappeared

**Comment by vishakhag6** [comment]
@Nikolas1814 Hey... I am getting the same issue with Ubuntu.
My main.js contains:

```
const { app, BrowserWindow } = require('electron');
let win;
function createWindow() {

  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600 });

  // If you want to give full screen
  // win = new BrowserWindow({ fullscreen: true })

  // and load the index.html of the app. 
  win.loadFile('../dist/app/index.html');

  // Open the DevTools.
  win.webContents.openDevTools();

  // Emitted when the window is closed.
  win.on('closed', () => {
    win = null
  })
};

// This method will be called when Electron has finished   
// initialization and is ready to create browser windows.   
// Some APIs can only be used after this event occurs.   
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {

  // On macOS it is common for applications and their menu bar     
  // to stay active until the user quits explicitly with Cmd + Q     
  if (process.platform !== 'darwin') { app.quit() }
});

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the     
  // dock icon is clicked and there are no other windows open.
  if (win === null) { createWindow() }
});  

```

package.js contains: 

  "main": "./main.js",
  "scripts": {
    "watch": "webpack --watch",
    "dist" : "build"
  },
  "build": {
    "appId": "com.app.app",
    "linux": {
      "target": [
        "snap"
      ]
    }
  }, 
The error which I am getting while running the command is:` npm run build`
**Error: Application entry file "main.js" in the "/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.**

As per your reply, If I remove "main" : "main.js" then I get another error which is: 

**Error: Application entry file "index.js" in the "/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.**

and there is no index.js file in the whole project. So is there any solution?

**Comment by shivshankar3578** [comment]
I don't have main in submodule but still throwing the same error. any idea?

**Comment by haoXu-web** [comment]
> I don't have main in submodule but still throwing the same error. any idea?
Maybe the value of main is not correct, it should be "./dist/electron/main.js" for example. if deleted, it has the default value of "./index.js".

**Comment by SamiDepp** [comment]
I was using "files" to "build" entry, forgetting to specify electron-main.js leaded me to this error.
```
"files": [
      "dist/**/*",
      "package.json",
      "electron-main.js"
    ]
```

**Comment by qiufeihong2018** [comment]
app.asar必须要有main入口，其实将app.asar解压就会发现其中有background.js，那么我们的package.json中的要设置入口
`  "main": "background.js",'`

**Comment by sibaiabis** [comment]
> app.asar必须要有main入口，其实将app.asar解压就会发现其中有background.js，那么我们的package.json中的要设置入口
> ` "main": "background.js",'`

good! thanks for your answer.

**Comment by Miorey** [comment]
Hello to fix this I set:

vue.config.js
```json
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                productName: `MV-Launcher`,
                files: [
                    `dist/**/*`,
                    `node_modules/**/*`,
                    `package.json`,
                    `background.js`
                ]
            },
        }

    },
```
and in package.json
```json
  "main": "background.js",
```

**Comment by ThomasNicolai** [comment]
For me I had to add : 
`  "build": {
    "asar": true,
    "files": [
      "./dist/**/*"
    ],
    "win": {}
  },`
To my package.json.

**Comment by patrick-motard** [comment]
@ThomasNicolai you may be on an older version if that worked for you:
```javascript
INFO  Building app with electron-builder:
  • electron-builder  version=22.14.5 os=20.6.0
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=/Users/runner/work/able/able/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/runner/work/able/able/dist_electron/bundled/package.json
InvalidConfigurationError: 'build' in the application package.json (/Users/runner/work/able/able/dist_electron/bundled/package.json) is not supported since 3.0 anymore. Please move 'build' into the development package.json (/Users/runner/work/able/able/package.json)
    at Object.checkMetadata (/Users/runner/work/able/able/node_modules/app-builder-lib/src/util/packageMetadata.ts:78:11)
    at Packager.build (/Users/runner/work/able/able/node_modules/app-builder-lib/src/packager.ts:335:5)
    at Object.executeFinally (/Users/runner/work/able/able/node_modules/builder-util/src/promise.ts:12:14) {
  code: 'ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION'
}
/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1.6.0/index.js:144
				throw err;
				^
Error: Command failed: npx --no-install vue-cli-service electron:build --mac --publish always 
    at checkExecSyncError (child_process.js:635:11)
```

**Comment by njj-abs** [comment]
Please help me to solve this error.
```
npx electron-builder
  • electron-builder  version=23.6.0 os=5.4.0-144-generic
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=23.2.0 appOutDir=dist/linux-unpacked
  ⨯ Application entry file "index.js" in the "/home/njj/dev/electronjs/electron-demo/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "index.js" in the "/home/njj/dev/electronjs/electron-demo/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
    at LinuxPackager.sanityCheckPackage (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
    at LinuxPackager.doPack (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at LinuxPackager.pack (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/njj/dev/electronjs/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/njj/dev/electronjs/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by electroniccc** [comment]
> Please help me to solve this error.
> 
> ```
> npx electron-builder
>   • electron-builder  version=23.6.0 os=5.4.0-144-generic
>   • writing effective config  file=dist/builder-effective-config.yaml
>   • packaging       platform=linux arch=x64 electron=23.2.0 appOutDir=dist/linux-unpacked
>   ⨯ Application entry file "index.js" in the "/home/njj/dev/electronjs/electron-demo/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "index.js" in the "/home/njj/dev/electronjs/electron-demo/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
>     at error (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
>     at Object.checkFileInArchive (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
>     at LinuxPackager.checkFileInPackage (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
>     at LinuxPackager.sanityCheckPackage (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
>     at LinuxPackager.doPack (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
>     at LinuxPackager.pack (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
>     at Packager.doBuild (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:441:9)
>     at Object.executeFinally (/home/njj/dev/electronjs/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
>     at Packager._build (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:376:31)
>     at Packager.build (/home/njj/dev/electronjs/electron-demo/node_modules/app-builder-lib/src/packager.ts:337:12)
>     at Object.executeFinally (/home/njj/dev/electronjs/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
> ```

try set `{"extends": null}`, this works for me

**Comment by nemo-giser** [comment]
> > app.asar必须要有main入口，其实将app.asar解压就会发现其中有background.js，那么我们的package.json中的要设置入口
> > ` "main": "background.js",'`
> 
> good! thanks for your answer.

设置完报错：
⨯ Application entry file "background.js" in the "D:\myCode\Smart-Mining\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "background.js" in the "D:\myCode\Smart-Mining\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at checkFileInArchive (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:31:11)
    at WinPackager.checkFileInPackage (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\platformPackager.ts:514:7)
    at WinPackager.sanityCheckPackage (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\platformPackager.ts:562:5)
    at WinPackager.doPack (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\platformPackager.ts:319:5)
    at WinPackager.pack (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\platformPackager.ts:140:5)
    at Packager.doBuild (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\packager.ts:445:9)
    at executeFinally (D:\myCode\Smart-Mining\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\packager.ts:379:31)
    at Packager.build (D:\myCode\Smart-Mining\node_modules\app-builder-lib\src\packager.ts:340:12)
    at executeFinally (D:\myCode\Smart-Mining\node_modules\builder-util\src\promise.ts:12:14)
