### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by peteringram0** [electron-userland/electron-builder#2485]
* **Version**: 19.19.1
* **Target**: DMG

Im getting the following error when building. I have checked disk space and im fine.

<img width="1151" alt="screen shot 2018-01-16 at 21 19 40" src="https://user-images.githubusercontent.com/6588942/35012874-43455ce2-fb03-11e7-886a-3864f646bc24.png">

This seems to be happening when it mounts the drive.

Thanks

**Comment by develar** [comment]
What was the problem?

**Comment by peteringram0** [comment]
Still not 100% sure to be honest but its more related to ExtractTextPlugin than electron-builder itself so im closing the the issue here.
