### ISSUE TITLE
Auto publishing on github via AppVeyor

### ISSUE THREAD

**Issue by ziajka** [electron-userland/electron-builder#2488]
* **19.52.1**: 

* Windows: 

Hi Guys,

First of all many thanks for a great software!

During set up our CIs for CD we have experienced issue with AppVeyor and publishing to github releases. 
Project is building however during publish phase we're getting this error (I've hidden username and repo name):

```

Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: undefined url: https://api.github.com/repos/(username)/(repo)/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"

```
Of course we have correct GH_TOKEN. After investigation I found out that (username) is not correct, because this repository belongs to organisation and this is how it should be accessed.

Problem is that you're taking value for username from `APPVEYOR_ACCOUNT_NAME` but you should take it from `APPVEYOR_REPO_NAME` (https://www.appveyor.com/docs/environment-variables/).

Workaround is to manually adjust `owner` in `GithubOptions`. CircleCI and TravisCI are working with no issues.

I'm just letting you know about this issue. Thanks!

Cheers,
Dominik

**Comment by develar** [comment]
Thanks a lot for a clear report with a proposed fix!
