### ISSUE TITLE
Let User select how to install (per-machine / per-user) application with file assocations

### ISSUE THREAD

**Issue by brusherru** [electron-userland/electron-builder#2496]
* **Version**: 19.39.0

* **Target**: NSIS

I want to provide installation of my application with file associations list, along with this I want to let Users without Admin rights install the application (but without file associations).
So, in this case, I could not set `"perMachine": true`, cause it will ask for Admin rights.

Here is the line, which throws an error and prevents me from building NSIS with both conditions: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/targets/nsis/NsisTarget.ts#L519

I just commented it and it builds fine, and the installer works fine without any problems. All my conditions are met. So...
* Is it excessive check?
* If not — why it needed and how it could break something?
* Is there any plans to fix it?
* At least, if it's correct, it should be there and etc — maybe you know some workaround?

Thanks.

**Comment by develar** [comment]
@brusherru and other voters — I have got enough issues about not working file associations because by default one-click non-admin installer is used and so, it leads to misunderstanding.

Got your point — check relaxed, now it is allowed to have file association for assisted installer.

**Comment by nikku** [comment]
Note that per user file associations should work soon, too: https://github.com/electron-userland/electron-builder/issues/2860.
