### ISSUE TITLE
Unable to sign: bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by JimmyMow** [electron-userland/electron-builder#2502]
"electron-builder": "^19.49.2"

When building a DMG I can successfully build and sign the application without a 3rd party binary in `extraResources`, as soon as I add the binary into the `extraResources` configuration I fail to sign and error out with `bundle format unrecognized, invalid, or unsuitable`

**Comment by develar** [comment]
Sample project? Please try latest electron-builder.
