### ISSUE TITLE
Building:  Is there a way to setup exe without administator?

### ISSUE THREAD

**Issue by divefox** [electron-userland/electron-builder#2504]
* **Version**: 
electron-builder: 19.51.0

not use

* **Target**: 
nsis
window 7

 Hi, guys,
    I want to use no permission and everyone can setup the exe on the windows.Is there hava a way to install the 'exe' (under windows) without administator?

Thank you very much.

**Comment by develar** [comment]
Default NSIS target for Windows creates one-click non-admin installer.
