### ISSUE TITLE
Missing `extraResources` folder in WIN portable

### ISSUE THREAD

**Issue by soimy** [electron-userland/electron-builder#2509]
Version: v19.54.0
Target: win portable 

As mentioned in [document](https://www.electron.build/configuration/contents#files) the `extraResouces` shall be located at `resouces` folder.
But when I build with target=portable, I cannot find the `resources` folder either at `exe` path or %APPDATA%

**Comment by develar** [comment]
`resources` directory in the unpacked executable. Not final.

**Comment by develar** [comment]
Please use https://github.com/electron/electron/blob/master/docs/api/process.md#processresourcespath in a production mode.
