### ISSUE TITLE
Start at system startup NSIS Windows

### ISSUE THREAD

**Issue by ihachani** [electron-userland/electron-builder#2511]
* **Version**:  19.48

* **Target**:  Windows 10 NSIS (using docker)

I need to make the application start at system startup. I can't write to the system register. I need to create a shortcut at startup folder. How can I do that? I saw that you can modify the NSIS with a script.

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/nsis#custom-nsis-script

In general, will be cool to have this functionality as part of electron-builder configuration, help-wanted.
