### ISSUE TITLE
Cannot find valid code signing certificate despite valid identities being printed in console during build

### ISSUE THREAD

**Issue by nparsons08** [electron-userland/electron-builder#2513]
* **Version**: 19.54.0

* **Electron  Builder**: 2.19.1

* **Target**: 
mac, windows, linux (--mwl)

I run the command `build --em.main=build/electron.js -mwl --x64 e -p always` and it goes through the proper steps and then it says "skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=" and prints:

```
1) 2B12438F977D8D2F0E1CEDEBC76A7422FD04587E "3rd Party Mac Developer Application: Foo.io Inc (EHV7XZLAHA)"
 2) FAC6726A0A4AFC4C06D46A46834279BB3EB25844 "3rd Party Mac Developer Installer: Foo.io Inc (EHV7XZLAHA)"
           2 identities found

Valid identities only
1) 2B12438F977D8D2F0E1CEDEBC76A7422FD04587E "3rd Party Mac Developer Application: Foo.io Inc (EHV7XZLAHA)"
2) FAC6726A0A4AFC4C06D46A46834279BB3EB25844 "3rd Party Mac Developer Installer: Foo.io Inc (EHV7XZLAHA)"
```

I'm at a loss... Cannot figure out how to sign my application with electron-builder.

**Comment by TuckerDowns** [comment]
You need an ID of type "Developer ID Application" create one via Apple Developer program

**Comment by nparsons08** [comment]
Already have that. And it’s in my keychain.

**Comment by TuckerDowns** [comment]
The "3rd Party Mac Developer Application" =/= "Developer ID Application"

I just found out that you should be able to generate one of the correct type of profiles from XCode but you need to be the team agent in your Apple Developer program (if you are enterprise) 

Try XCode > Preferences > Accounts > ... > Manage Certificates > + > Developer ID Application

**Comment by TuckerDowns** [comment]
Or, at least that's where I've ended up after working on this issue for all 8 hours of my day. Going to try to get our team agent to generate one of those certificates tomorrow.

**Comment by nshoes** [comment]
@TuckerDowns did you ever resolve your issue? I'm having the same one. Added every cert available and the `.pkg` is still not signed (checking with `codesign`).

**Comment by adammoisa** [comment]
Same here, I have it in my keychain but it's not picking it up. Anyone make progress?

**Comment by BeatriceThalo** [comment]
Our team uses one build server (OS X 10.13.6 not 10.12) and after getting a certificate that was not prefixed "iPhone Developer:" but rather "Developer ID Application:" with either no `identity` property in `electron.builder.json` or setting the `identity` property to the certificate suffix/part after the colon, we got an "<App Name> Helper EH" error until we gave ssh access to the keychain.

**Comment by aguynamedben** [comment]
This is happening to me after getting a new laptop. I have the same certificates installed identically on both laptops, but electron-builder isn't finding the certificate on the new laptop even though it's identically installed.

Are there any ways to debug this? It's keeping me from releasing new version of my app on the new laptop. I'm using electron-builder 20.28.4.

**Comment by zhaoterryy** [comment]
Is ```security find-identity -vp codesigning``` able to find your certs?

**Comment by Randyshu2018** [comment]
> Try XCode > Preferences > Accounts > ... > Manage Certificates > + > Developer ID Application

how to find the created certificate?

**Comment by johannesjo** [comment]
@Randyshu2018 Keychain Access (another application).

I can't figure this out. Got all the certificates in place, they are listed by electron builder but somehow it doesn't see them as the right ones...

**Comment by lemmycaution** [comment]
Hi there, 
This is still happening, is there any explanation why issue closed, is there any viable solution? or direct any clue as a workaround?

Bests,

**Comment by AndrewKeplinger** [comment]
I'm seeing same issue, I think.  I can see the certificates in keychains, with private key, but "security find-identity" doesn't show them.  code sign won't let me use them for signing.  Stuck.

**Comment by lemmycaution** [comment]
@zhaoterryy no it's not listing in my case. I have a `Developer ID Application: xxx....` visible in keychain but not in command line. Any tips more than welcome, thanks.

**Comment by 4dams** [comment]
Any updates on this? :(

**Comment by DaveLomber** [comment]
This Apple stuff is a total crap... 

It does not work neither with 'Apple Distribution' nor with 'Developer ID Application'

What is '3rd Party Mac Developer Application'? is there any guide how to generate this one?

**Comment by samuelmeuli** [comment]
@DaveLomber A "3rd Party Mac Developer Application" certificate [seems to be the same as a "Mac App Distribution" certificate](https://stackoverflow.com/a/13603031/6767508).

[In Xcode 11, the "Apple Development" and "Apple Distribution" certificates have replaced the corresponding iOS/macOS certificates](https://stackoverflow.com/a/58717827/6767508). `electron-builder` still requires a "Mac App Distribution" certificate, though. You can create one in your [Apple Developer Account](https://developer.apple.com/account/resources/certificates/list). Click `+`, `Mac App Distribution`, `Continue` and follow the remaining steps. Download your certificate and open it. This will add it to your Keychain, where `electron-builder` can find it.

**Comment by continuata** [comment]
I had the same issue, turns out that due to Mac updates they are now looking for different certificates.

https://developer.apple.com/account/resources/certificates/list

**Comment by openspeedtest** [comment]
I had same issue, I requested and generated new certificate from my M1 Mini, Certificated Generated from MacBook Pro was not working. So all you need to do is created new certificate from that machine and make sure you added your developer account on Xcode. now run `security find-identity -vp codesigning` It will show recently created valid certificate.

**Comment by typologist** [comment]
Here's what worked for me, hopefuly it'll be useful to someone else that runs into this issue:

## 1. How do I check I have a valid identity certificate?

Run `security find-identity -vp codesigning`. You should see a `1 valid identities found`. If it shows 0, it means you need to generate a new one.

## 2. What specific certificates do I need?

- If your app will be distributed _inside_ the App store, you'll need: `Mac App Distribution` and `Mac Installer Distribution`.
- If your app will be distributed _outside_ the Mac App Store: `Developer ID Application` and `Developer ID Installer`

## 3. Where do I get those certificates?

You can generate them [here](https://developer.apple.com/account/resources/certificates/list). Choose the ones according to the previous point.

> **IMPORTANT:** If you have XCode 11 or later, you will need to generate new developer and installer certificates even if the ones on your the apple website are not expired! Make sure you select `Profile Type > G2 Sub-CA (Xcode 11.4.1 or later)` on the "Create a New Certificate" screen!

Download them and double-click them to add to your keychain

## 4. Is that it?

No. You also need to ensure you have a Certification Authority. To check
```
certtool y | grep Developer\ I
```
This should print a list
```
   Common Name     : Developer ID Certification Authority
   Common Name     : Developer ID Installer: <Your name> (XXX)
   Common Name     : Developer ID Application: <Your name> (XXX)
```
You should have them all 3. If you're missing the authority one, go to [this page](https://www.apple.com/certificateauthority/). In my case, I needed the **Developer ID - G2** and the **Worldwide Developer Relations - G2**.

Good luck.

**Comment by fluke777** [comment]
@typologist Good, stuff. Thank you.

Any idea where I get the 

      Common Name     : Developer ID Installer: <Your name> (XXX)
      Common Name     : Developer ID Application: <Your name> (XXX)

**Comment by typologist** [comment]
@fluke777 not sure I follow, it's literally the step 3 in my above point. 

Let me know if you have any questions!

**Comment by fluke777** [comment]
I see. I was confused by the fact I am seeing different results when running

  certtool y | grep Developer\ I

But that is probably not necessarily a problem. Was just able to notarize. All good. And thanks for the instructions. Very helpful.

**Comment by tylerlong** [comment]
I meet the same issue today. It turns out that I didn't install the intermediate cert.
After I installed the intermediate cert, the issue disappeared.

**Comment by meta72** [comment]
I ran into this issue, where the CI did not find a valid certificate even though it printed multiple valid ones. In a local terminal or via SSH it was signing just fine. I followed all suggested steps here (thank you all for them), still no luck.

Turns out, our build pipeline set the environment variable `CSC_NAME` with the ID of an expired certificate. Replaced it with the new one and it's working.

**Comment by josedagama** [comment]
> Here's what worked for me, hopefuly it'll be useful to someone else that runs into this issue:
> 
> ## 1. How do I check I have a valid identity certificate?
> Run `security find-identity -vp codesigning`. You should see a `1 valid identities found`. If it shows 0, it means you need to generate a new one.
> 
> ## 2. What specific certificates do I need?
> * If your app will be distributed _inside_ the App store, you'll need: `Mac App Distribution` and `Mac Installer Distribution`.
> * If your app will be distributed _outside_ the Mac App Store: `Developer ID Application` and `Developer ID Installer`
> 
> ## 3. Where do I get those certificates?
> You can generate them [here](https://developer.apple.com/account/resources/certificates/list). Choose the ones according to the previous point.
> 
> > **IMPORTANT:** If you have XCode 11 or later, you will need to generate new developer and installer certificates even if the ones on your the apple website are not expired! Make sure you select `Profile Type > G2 Sub-CA (Xcode 11.4.1 or later)` on the "Create a New Certificate" screen!
> 
> Download them and double-click them to add to your keychain
> 
> ## 4. Is that it?
> No. You also need to ensure you have a Certification Authority. To check
> 
> ```
> certtool y | grep Developer\ I
> ```
> 
> This should print a list
> 
> ```
>    Common Name     : Developer ID Certification Authority
>    Common Name     : Developer ID Installer: <Your name> (XXX)
>    Common Name     : Developer ID Application: <Your name> (XXX)
> ```
> 
> You should have them all 3. If you're missing the authority one, go to [this page](https://www.apple.com/certificateauthority/). In my case, I needed the **Developer ID - G2** and the **Worldwide Developer Relations - G2**.
> 
> Good luck.

This has worked for me! 
Many thanks!
