### ISSUE TITLE
Windows NSIS installer defaults to German if system language is not supported by electron-builder

### ISSUE THREAD

**Issue by agritchie** [electron-userland/electron-builder#2517]
I'm using electron-builder version 19.37.2 to build my Electron project into a Windows installer via NSIS. This issue was seen on both Windows 10 and 7.

If Windows is set to a language that is not supported by electron-builder, rather than defaulting to English, the NSIS installer ends up displaying German. This was seen when Windows was set to Thai, Turkish, and Icelandic.

**Comment by Wello6143** [comment]
Yeah, it also seen on Vietnamese too.
