### ISSUE TITLE
code object is not signed at all

### ISSUE THREAD

**Issue by ibash** [electron-userland/electron-builder#2522]
* **19.55.2**: 

* **macos 10.13.2**: 

Steps:
1. Add an extra file that is an executable like:
   ```
   "extraFiles": [{
        "from": "foo.sh",
        "to": "MacOS/foo.sh"
    }]
   ```
2. Try to package the app with code signing

Expected:
Signs the executable

Actual:
Fails with "code object is not signed at all" and refers to the extra file.

**Comment by ibash** [comment]
I was able to solve this by using an afterPack script to move the file.

**Comment by nguyenhthai** [comment]
I also encountered the same problem after using the extraFiles config to add additional files after building the app. My extra file only includes simple string like date string and it is just a json file, not even a script file. The same configuration on Windows works fine without any error during code signing process, but fail on Mac OS.

Using the afterPack config like above or using the extraResources config instead mitigate the problem. I don't know if this is intended or not. If so, there should be a document for it.

**Comment by zepedrorocha** [comment]
I had the same problem 

> Error: Command failed: codesign --sign (.....)
/Users/travis/build/(...)/app-1/dist/mac/myapp (beta).app/Contents/MacOS/myapp (beta): code object is not signed at all
In subcomponent: /Users/travis/build/(...)/app-1/dist/mac/myapp (beta).app/Contents/eula.md

I was using 'extraFiles' but had to use 'afterPack' to copy the files and avoid this problem.

**Comment by fishear** [comment]
I had the same problem when building for MacOS by using 'extraFiles'. It doesn't work although I switched to 'extraResources'

**Comment by jacklovepdf** [comment]
I have solved this problem!
