### ISSUE TITLE
Versioning of the Dockerfiles

### ISSUE THREAD

**Issue by kraenhansen** [electron-userland/electron-builder#2531]
* **Version**: 19.55.3 but N/A
* **Target**: Linux and Windows

I am using the `electronuserland/builder:wine-chrome` docker image in my build process.
Because of [wine being based on the :latest](https://github.com/electron-userland/electron-builder/blob/master/docker/wine/Dockerfile#L1) which is now based on node 9, I started getting failed builds. I would have loved if there existed a `wine-chrome-8` image that I can revert to and keep using until all my dependencies have pre-builts for Electron on Linux and Windows.

**Comment by develar** [comment]
Just use image in a form `@sha256:c34ce3c1fcc0c7431e1392cc3abd0dfe2192ffea1898d5250f199d3ac8d8720f`

where `c34ce3c1fcc0c7431e1392cc3abd0dfe2192ffea1898d5250f199d3ac8d8720f` is a desired image hash. All published images available for you in this form. It another question how to list available hashes for image :)

**Comment by kraenhansen** [comment]
This just happened to me again with the most recent upgrade to node 10 🤦‍♂️

**Comment by kraenhansen** [comment]
I currently get this error when trying to use the hash you provided previously - it seems the image is missing from the registry:

```
Step 1/6 : FROM electronuserland/builder:wine-chrome@sha256:c34ce3c1fcc0c7431e1392cc3abd0dfe2192ffea1898d5250f199d3ac8d8720f
manifest for electronuserland/builder:wine-chrome@sha256:c34ce3c1fcc0c7431e1392cc3abd0dfe2192ffea1898d5250f199d3ac8d8720f not found
Building ci/realm-studio:pr-a921de30b7a73b772c53720784191befd1dc588e image failed
script returned exit code 1
```
