### ISSUE TITLE
Auto-generation of `icns` from PNG causes corrupt icon

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#2533]
* **Version**: 19.55.2

* **Target**: macOS

After we [started using](https://github.com/wulkano/kap/commit/741a5ec7d34ddb605a1df24d909e71bf04ab3fb4) the PNG to `icns` generation, implemented in [v19.53.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.53.1), we started seeing issues with corrupt icons: 

![image](https://user-images.githubusercontent.com/170270/35528225-c8baad4e-055f-11e8-82fa-792f3e2a82d9.png)

![image](https://user-images.githubusercontent.com/170270/35528372-3a58a424-0560-11e8-8be7-6254838fa38a.png)

**Comment by skllcrn** [comment]
Seeing this on macOS 10.13.2

**Comment by albinekb** [comment]
Seeing this on macOS `10.13.2 (17C88)`

**Comment by Aarbel** [comment]
any news for this ?
