### ISSUE TITLE
Linux auto-update ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#2534]
* **Version**: 19.55.1
* **electron-updater**: 2.18.2
* **Target**: Linux

See attached screenshot. When one of my computers attempts to auto-update my electron app, the following **popup error dialog** displays on that computer:

![img_0511](https://user-images.githubusercontent.com/18287271/35536133-f8be5320-0513-11e8-8ee7-c173b3c11696.jpeg)

Aside from the fact that I don't know why this error is occurring (the file on the server seems correct and it works from another computer), I am much more concerned with the fact that:

- It popped up an error dialog. Is there a way to avoid this behavior?
- It did not log a corresponding error to autoUpdater.logger

**Comment by afshing** [comment]
Mac also

**Comment by iffy** [comment]
Yes, the title should be changed to also include macOS.

**Comment by EtienneLem** [comment]
> It popped up an error dialog. Is there a way to avoid this behavior?

I believe the only way is to use `uncaughtException`:
```js
// Don’t show error popup to users
process.on('uncaughtException', (error) => {
  console.error(error)
})
```

I think that’s because errors are re-thrown (see #2398)
