### ISSUE TITLE
Publish without building

### ISSUE THREAD

**Issue by marcoancona** [electron-userland/electron-builder#2536]
Is it possible to publish without rebuilding? The use-case I have in mind is the following:
- build
- run some tests on the packaged app
- publish

At the moment I have to run `build --publish never`, run the tests and then `build --publish always` which takes twice the time to package the app.

**Comment by develar** [comment]
Is it possible for you to use afterPack hook?

**Comment by AzeeSoft** [comment]
Hi @develar , is this feature available now? I need to manually validate the application before publishing it, and hence cannot use the afterPack hook.

**Comment by SuperKirik** [comment]
Here is one more thread about this:
https://github.com/electron-userland/electron-builder/issues/4535
