### ISSUE TITLE
Using TFS as publish repo instead of GitHub

### ISSUE THREAD

**Issue by ChristianHaase** [electron-userland/electron-builder#2539]
* **Version**: 
`electron-builder` - 19.55.2
`electron-updater` - 2.20.1

* **Target**: Win (nsis)

After following several guides on publishing and auto-updating an electron app, I've hit my head against a wall. It's simple enoug to get working with Github and the GitHub Personal Access Token, and automatically fetch and download updates on various clients. 

However, I'm currently building an "on-premise" application at my company, and we have and internal network with no access from the outside world. This means that I would need to publish updates to a local git repo.

We're 3 developers in the company, and we're all using TFS 2017 as our source control provider. The repo for my application is a git repo, so the basics should be the same. in TFS 2017 it's now possible to create a personal access token, just like GitHub, but I can't seem to get it working.

I've created my TFS PAT, and included it in my `electron-builder.yml` as well placed the repo url in my `package.json`. The `provider` in my `electron-builder.yml` is still `github`, as I'm not sure what else to put there.

As mentioned, I can't seem to get this working, and I was wondering if it's possible to publish to a TFS repo, and create a release just like GitHub?

**Comment by develar** [comment]
TFS doesn't support releases as Github.

> we have and internal network with no access from the outside world

Just use [Minio](https://www.minio.io) as S3 provider. Configure publisher as for Amazon S3 and set `endpoint` to your local instance of Minio.
