### ISSUE TITLE
Updating Squirrel.Windows to v1.7.9

### ISSUE THREAD

**Issue by steverandy** [electron-userland/electron-builder#2543]
There is a [new version](https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.7.9) of Squirrel.Windows that fixes splash screen issue. Will it be possible to incorporate this update to the new electron-builder release?

Thanks!

**Comment by rcorredera** [comment]
Issue related : https://github.com/electron-userland/electron-builder/issues/2704

**Comment by develar** [comment]
@rcorredera Update to 1.9.0 is ready and will be released tomorrow morning CET.
