### ISSUE TITLE
Deprecated documentation about docker images

### ISSUE THREAD

**Issue by sin6pi7** [electron-userland/electron-builder#2544]
* **Version**: 19.55.3

* **Target**: Windows/Linux

Documentation (https://www.electron.build/multi-platform-build) states:
```
builder:wine — Wine, NodeJS 8 and required system dependencies. Based on builder:8. Use this image if you need to build Windows targets
```
However, `builder:wine` image actually contains NodeJS 9:
```
$ sudo docker run electronuserland/builder:wine node -v                                         
v9.4.0 
```

Is there a possibility to have an image ready for building Windows targets with specified NodeJS version?

**Comment by danielecr** [comment]
this my answer to 
> Why nodejs 9 is not suitable for you?

Because of eslint, for example
> error eslint@5.7.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
> error Found incompatible module

but my question may be, how can I upgrade/change the used node version? adding:
in Dockerfile like:

```
FROM electronuserland/builder:wine
RUN node install -g n
RUN n 9.11.1
```
is ok?

**Comment by danielecr** [comment]
RUN node install -g n

 ---> Running in f333fa3c40e7

module.js:557

    throw err;

    ^



Error: Cannot find module '/project/install'

    at Function.Module._resolveFilename (module.js:555:15)

    at Function.Module._load (module.js:482:25)

    at Function.Module.runMain (module.js:701:10)

    at startup (bootstrap_node.js:194:16)

    at bootstrap_node.js:618:3

**Comment by danielecr** [comment]
so funny ... the correct Dockerfile is:

```
FROM electronuserland/builder:wine
RUN npm install -g n
RUN n 9.11.1
```
and it works, I can use node 9.11.1 or whatever using n
