### ISSUE TITLE
Turn off node_modules deps resolving or the warning about missing deps

### ISSUE THREAD

**Issue by wojtkowiak** [electron-userland/electron-builder#2551]
Hey,

I am in the proces of updating `electron-builder@13.11.1` to the newest one in `meteor-desktop`.
I did mention in the past 🙂 (https://github.com/electron-userland/electron-builder/issues/982#issuecomment-265447351) that I am packing my node_modules into asar before building installer. Now `electron-builder` is complaining about unresolved deps as `node_modules` is not present at the time it processes the app. 
I know that I can set the `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES` but is still gives a warning (https://github.com/electron-userland/electron-builder/issues/982#issuecomment-265447351)

Would you add an option to disable this mechanism or at least disable this warning in any way?

Of course I can prepare the PR but just let me know how would you prefer this to be realised?

**Comment by develar** [comment]
Please see Packager.productionDeps getter. I guess here we should check is node_modules dir exist if `beforeBuild` is already set. And do nothing if not dir and `beforeBuild` is set.

**Comment by wojtkowiak** [comment]
Sth like this https://github.com/wojtkowiak/electron-builder/commit/bbacd3e3381930d08472481b0acc291f2c2328c0 ?

But maybe better to condition this also with and additional env var?

**Comment by develar** [comment]
Yep (except that I think no need to `exists` if beforeBuild not set).

> maybe better to condition this also with and additional env var?

No, no pleasure for users to guess such env instead of just "build my app".

**Comment by develar** [comment]
> Maybe in the beforeBuild desc?

👍

**Comment by UberMouse** [comment]
I can't find any mention of this option in the current version. Is there some other way to not get electron-builder to check for missing deps? Our CI log ends up with nearly 600,000 lines because of all the unresolved deps spam in the logs, so looking for a solution to suppress it.
