### ISSUE TITLE
Build both 32 & 64 bit execuable file seperately.

### ISSUE THREAD

**Issue by erguotou520** [electron-userland/electron-builder#2554]
* **Version**: 
`^19.19.1`

* **Target**: 
`targets = Platform.WINDOWS.createTarget()` &
```js
      win: {
        icon: 'build/icons/icon.ico',
        target: [
          {
            target: 'nsis',
            arch: [
              'x64', 'ia32'
            ]
          }
        ]
      }
```

I want to build both 32 & 64 bit target nsis file seperately instead of one execuable nsis file. How to do that?

**Comment by develar** [comment]
Please try:

```
win: {
  target: ['nsis:ia32', 'nsis:x64']
}
```

**Comment by develar** [comment]
But I am afraid that the only way to build — build 2 times. Anyway — please explain why do you need this and why nsis-web is not a solution (if big size is an issue).

**Comment by erguotou520** [comment]
The `two-in-one` nsis file is almost `70MB` while `x64` is about `35MB`. And I need to provide offline package for users so `nsis-web` do not fit me.

**Comment by erguotou520** [comment]
The workaround now is to create a `ia32` task after `x64` build finished and change the `artifactName` like bellow:
```js
        {
          win: {
            icon: 'build/icons/icon.ico',
            artifactName: '${productName} Setup ${version}-ia32.${ext}',
            target: [
              {
                target: 'nsis',
                arch: [
                  'ia32'
                ]
              }
            ]
          }
```

**Comment by erguotou520** [comment]
This workaround can build `ia32` exe file. But when appveyor publish the 2 exe file to github, the last `ia32` exe file will overwrite the previous `x64` file as their publish name is the same. I didn't find a way to change the upload file's name, so how to fix this problem?

**Comment by peterdanis** [comment]
You can set the `artifactName` to include `${arch}` (e.g. `${productName}_v${version}_${arch}.${ext}`) and run build process twice, first time with `--ia32` and second time with `--x64` argument.

**Comment by erguotou520** [comment]
I have mentioned this above, but the second one will overwrite the first one on github.

**Comment by Disorrder** [comment]
@peterdanis ${arch} doesn't work, just ignoring :(

**Comment by erguotou520** [comment]
Yes, I have tried `${arch}` recently again, it not work. And another issue is the `latest.yml` will be overwrited at the second time.

**Comment by emilsall** [comment]
I am also looking for a way to publish separate builds for 32 and 64 bit and bumped in to the issue with the build and latest.yml being overwritten when publishing. Did anyone find a solution for this? @erguotou520

**Comment by AtiqGauri** [comment]
can we pass arch in `dist: electron-builder` command itself?

something like  `dist: electron-builder --x64`

**Comment by mahnunchik** [comment]
Related issue https://github.com/electron-userland/electron-builder/issues/4467

**Comment by yeefun** [comment]
It works:

```json
"scripts": {
  "release-win": "electron-builder --win --publish always"
},
"build": {
  "win": {
    "artifactName": "${productName} Setup ${version} ${arch}.${ext}",
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64",
          "ia32"
        ]
      }
    ]
  }
}
```
