### ISSUE TITLE
electron-builder.yml ignored if buildDependenciesFromSource is being set

### ISSUE THREAD

**Issue by derwaldgeist** [electron-userland/electron-builder#2555]
I had to set the `buildDependenciesFromSource` flag since `node-serialport` won't build its native dependencies without it (see discussion on #1812).

Since I did this, `electron-builder` ignores the `electron-builder.yml` file and thus complains `Application icon is not set, default Electron icon will be used` on build time. The build also seems to be corrupt since files are missing.

Is there a way to use `buildDependenciesFromSource` and still ensure the build configuration settings defined in `electron-builder.yml` are being used?

**Comment by develar** [comment]
That's very strange. electron-builder version? Where  `buildDependenciesFromSource` is set? Please set env `DEBUG=electron-builder` and attach log of the terminal output.
