### ISSUE TITLE
macOS cannot update from server running on localhost

### ISSUE THREAD

**Issue by jmpugh** [electron-userland/electron-builder#2561]
* **electron-builder**: 19.56.0

* **electron-updater**: 2.20.1

* **Target**: macOS 10.13.2

* **node: 8.9.1**
* **npm: 5.5.1**

**package.json**:
```
{
  "name": "***",
  "version": "1.0.0",
  "description": "***",
  "main": "src/main.js",
  "scripts": {
    "start": "electron .",
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "***",
    "productName": "***",
    "copyright": "***",
    "directories": {
      "buildResources": "public"
    },
    "mac": {
      "icon": "./icons/icon.icns"
    },
    "publish": {
      "provider": "generic",
      "url": "https://localhost/update"
    }
  },
  "author": "***",
  "dependencies": {
    "electron-log": "^2.2.14",
    "electron-updater": "^2.20.1"
  },
  "devDependencies": {
    "electron": "^1.8.1",
    "electron-builder": "^19.56.0"
  }
}
```

I am attempting to hook up electron-updater to update from a locally running server that will serve the appropriate file(s) based on the target platform that the server is running on. However, I cannot get electron-updater to advance beyond the initial `checking-for-update` event.

```
jpugh:ui-capture ⚡️   make run-electron DEBUG=electron-builder
npm start --prefix ./electron

> echo360-capture@1.0.0 start /Users/jpugh/work/ui-capture/electron
> electron .

Checking for update
[15:22:42.179] [warn] Checking for update...
  electron-builder Request: {
  electron-builder   "headers": {
  electron-builder     "X-User-Staging-Id": "0e5d752a-b57c-5e3f-8a85-b2bea6fd53a6",
  electron-builder     "User-Agent": "electron-builder",
  electron-builder     "Cache-Control": "no-cache"
  electron-builder   },
  electron-builder   "protocol": "https:",
  electron-builder   "hostname": "localhost",
  electron-builder   "path": "/update/latest-mac.yml"
  electron-builder } +0ms
```

I have set the feedUrl to `https://localhost/update` which should serve the latest-mac.yml stored locally. When I hit this URL in Chrome the latest-mac.yml is downloaded. I can also use node's https module to GET the file and it returns it as expected. But no matter what I try, `electron-updater` never actually hits this endpoint (I know this from checking the logs on the server). It may be important to note that I have disabled authentication on the server so it should not be an issue on that side.

I have successfully been able to get the auto updates working with S3 but unfortunately this solution will not suffice. I am using Postman to compare the response of the S3 URL that returns the latest-mac.yml to the response of the local server that returns the latest-mac.yml and there are no significant differences.

I have hit a wall and am not sure what else to do. Please let me know what other information would be helpful to know. TIA!

**Comment by thelittlebug** [comment]
maybe try to set localhost to a full hostname in /etc/hosts?
so you can reach your config via www.myupdateservice.com instead of localhost

**Comment by jmpugh** [comment]
No luck as I experience the same issues mentioned in the original post. When using a full hostname, I am able to download the file via Chrome but `electron-updater` stalls at `checking-for-update`.

**Comment by develar** [comment]
Problem is that electron-updater expects HTTPS, not plain HTTP.

**Comment by jmpugh** [comment]
I _am_ sending the request via HTTPS as noted above.

**Comment by develar** [comment]
Is your cert self-signed? https://stackoverflow.com/a/46789486

**Comment by jmpugh** [comment]
Yes I am using a self-signed cert and have that code you mentioned above. FWIW I have also disabled ATS (https://github.com/electron/electron/pull/7933) in order to rule that out as well.

**Comment by jmpugh** [comment]
The following are the responses from both my generic localhost provider and my S3 provider:
```
localhost:

Status: 200 OK Time: 36ms Size: 736 B
Accept-Ranges →bytes
Connection →close
Content-Length →551
Content-Type →binary/octet-stream
Date →Tue, 13 Feb 2018 16:40:10 GMT
Server →software-capture-3/?.?
```
```
S3:

Status: 200 OK Time: 73ms Size: 989B
Accept-Ranges →bytes
Content-Length →623
Content-Type →binary/octet-stream
Date →Tue, 13 Feb 2018 16:40:20 GMT
ETag →"XXX"
Last-Modified →Tue, 06 Feb 2018 19:33:59 GMT
Server →AmazonS3
x-amz-id-2 →XXX
x-amz-request-id →XXX
```

The only difference I see is the `Connection: close` header which I don't think is an issue as the file is getting served via the browser. Again, setting the `feedUrl` to use S3 works like a charm but is not feasible as an end-solution:
```
Checking for update...
  electron-builder Request: {
  electron-builder   "headers": {
  electron-builder     "X-User-Staging-Id": "0e5d752a-b57c-5e3f-8a85-b2bea6fd53a6",
  electron-builder     "User-Agent": "electron-builder",
  electron-builder     "Cache-Control": "no-cache"
  electron-builder   },
  electron-builder   "protocol": "https:",
  electron-builder   "hostname": "s3.amazonaws.com",
  electron-builder   "path": "/path/to/files/latest-mac.yml"
  electron-builder } +0ms
  electron-builder Response: 200 OK, request options: {
  electron-builder   "headers": {
  electron-builder     "X-User-Staging-Id": "0e5d752a-b57c-5e3f-8a85-b2bea6fd53a6",
  electron-builder     "User-Agent": "electron-builder",
  electron-builder     "Cache-Control": "no-cache"
  electron-builder   },
  electron-builder   "protocol": "https:",
  electron-builder   "hostname": "s3.amazonaws.com",
  electron-builder   "path": "/path/to/files/latest-mac.yml"
  electron-builder } +252ms
Found version 1.0.1 (url: /path/to/files/Echo360 Capture-1.0.1-mac.zip, /path/to/files/Echo360 Capture-1.0.1.dmg)
Update available.
Downloading update from /path/to/files/Echo360 Capture-1.0.1-mac.zip, /path/to/files/Echo360 Capture-1.0.1.dmg
```

I am really stuck on this - any other ideas?

**Comment by jmpugh** [comment]
Update:

I got it to work by creating a self-signed certificate for localhost (https://certsimple.com/blog/localhost-ssl-fix) and configuring my release server to use it. It seems that the previous way I was handling this (https://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app/46789486#46789486) was not enough for me.
