### ISSUE TITLE
Feature request: Prevent the You need to format the disk in drive windows popup

### ISSUE THREAD

**Issue by aamm132** [electron-userland/electron-builder#2568]
I was wondering if it would be possible to prevent windows from popping up the window asking to format the disk drive. In etcher, when a USB is flashed this window pops up: 
![image](https://user-images.githubusercontent.com/25181342/36034651-53d93acc-0d7a-11e8-8900-b69c5b479584.png)

Regardless of the answer, the flashing is successful anyways. So in essence, the window is unnecessary and annoying. Is there a way already to prevent it? If so, what is it? If not, is it possible to add a way preventing this? 
Thanks for any help!

**Comment by develar** [comment]
Are you sure that it is related to electron-builder?

**Comment by aamm132** [comment]
I'm not sure, no. But it was mentioned that electron could be used to help incorporate this feature: 
[Etcher issue](https://github.com/resin-io/etcher/issues/2024)

**Comment by develar** [comment]
It is app-specific, we cannot fix it.
