### ISSUE TITLE
2.11.0 nests locales and resources in additional folders

### ISSUE THREAD

**Issue by djpereira** [electron-userland/electron-builder#257]
Going from 2.9.5 to 2.11.0 creates a locales folder within the locales folder and drops the respective files there. Same deal for resources. Due to do this then the application does not run after installing it. Everything works fine using 2.9.5.

I'm building on Windows using `build -d`. The packaging process is fine, the issue is during the installer creation. I suspect that the problem arose when you went to electron-winstaller-fixed 2.0.6-beta.1 from 2.0.5.

I'm using npm 2.14.20 and node 4.4.0.

Here's my package.json:
```
{
  "name": "xxx",
  "description": "description",
  "version": "0.1.0",
  "main": "main.js",
  "author": "xxx",
  "devDependencies": {
    "electron-builder": "^2.9.5",
    "electron-prebuilt": "^0.37.2"
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "pack": "build",
    "dist": "build -d"
  },
  "build": {
    "app-bundle-id": "your.id",
    "app-category-type": "your.app.category.type",
    "iconUrl": "https://raw.githubusercontent.com/xxx/xxx.sky.nucleus.desktop/master/build/icon.ico"
  }
}
```

**Comment by havenchyk** [comment]
@djpereira I have the same with `2.11.0`. Try to use `electron-builder@2.10.1` instead for now, should work fine. It looks like the problem relates to `windows-installer` and should be fixed there.

**Comment by marttinen** [comment]
Can confirm the doubled resources/resources and locales/locales folder and also that it works again when using electron-builder@2.10.1.

**Comment by develar** [comment]
Please try [3.0.0](https://github.com/electron-userland/electron-builder/releases/tag/v3.0.0) (`next` version). Please be aware of breaking changes (see release notes).

**Comment by marttinen** [comment]
Works fine with 3.0.0, thanks. (noMsi works now too :+1: )
