### ISSUE TITLE
__dirname electron application

### ISSUE THREAD

**Issue by B-ot** [electron-userland/electron-builder#2571]
How can one get an accurate path to the directory a portable electron app is running from?The app has been compiled through electron builder. I am creating an app for windows at the moment as I have already found a solution for mac.

**Comment by develar** [comment]
`process.resourcesPath` https://github.com/electron/electron/blob/master/docs/api/process.md

**Comment by decaller** [comment]
updated answer
`process.env.PORTABLE_EXECUTABLE_DIR`
https://stackoverflow.com/questions/46307797/how-to-get-the-original-path-of-a-portable-electron-app
