### ISSUE TITLE
Feature-request: OS based app dependencies

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#2573]
* **Version**: 
19.53.6

I'm not sure if it's the right place to ask for the feature but this is what I'm looking for -

* Recently, I wanted to use `semver` node module on Linux but not on Windows/macOS. I added the dependency in app's package.json. Used `files` option to ignore semver on macOS/Windows but it didn't work. It still throws an error saying `cannot find module 'semver'` after packaging on macOS/Windows.

I was wondering if we can add an option to configure electron-builder to only add that particular dependency in app's package.json if it satisfies the OS.

I'm requesting something like - [npm-platform-dependencies](https://www.npmjs.com/package/npm-platform-dependencies)

**Comment by develar** [comment]
> cannot find module 'semver' after packaging on macOS/Windows.

You should use or lazy imports (babel), or do not use `import` for semver module and do explicit `require` where modules is required.
