### ISSUE TITLE
README should note openjpeg-tools as an older name for jpeg dependency

### ISSUE THREAD

**Issue by mykter** [electron-userland/electron-builder#2578]
The latest version depends on `opj_decompress` which is provided by `libopenjp2-tools` on recent debian distros, but on Trusty - which is notably the most recent distro on Travis - the package is called `openjpeg-tools`.

It might be helpful to name `opj_decompress` as the actual binary that is needed, to help people on other distros find the right package?

**Comment by develar** [comment]
Are you sure that `opj_decompress` is not preinstalled on Travis? Anyway, it seems we cannot prebundle opj_decompress for Linux x64.

**Comment by mykter** [comment]
Good question, I didn't actually check: I just changed the package dependency from icnsutils to libopenjp2-tools which failed.

**Comment by develar** [comment]
opj_decompress is now bundled for Linux x64.
