### ISSUE TITLE
How to toggle dev tools?

### ISSUE THREAD

**Issue by daviddelusenet** [electron-userland/electron-builder#2581]
* **Version**: 19.52.1

* **Target**: Mac

Quite a simple question: I was wondering how to toggle dev tools in a packaged application? I can't find anything about this in the documentation or on Google.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-webpack-quick-start/blob/master/src/main/index.js#L16

**Comment by daviddelusenet** [comment]
Thanks for the response.

However, I meant: how to toggle dev tools in a package application with a keyboard shortcut?

**Comment by develar** [comment]
https://github.com/sindresorhus/electron-debug

**Comment by daviddelusenet** [comment]
The `electron-debug` package seems outdated, not maintained and doesn't even work.

I've opened an issue there in the hopes of getting it to work, any help is very welcome: https://github.com/sindresorhus/electron-debug/issues/60

**Comment by onmyway133** [comment]
`Cmd+Alt+I` in macOS or `win.openDevTools()`

**Comment by michaelkebe** [comment]
`Ctrl+Shift+i` in Windows.

**Comment by beedell-roke** [comment]
@onmyway133 and @michaelkebe, <del>those key combinations may not work when overridden by the application, like [`bitwarden/clients/issues/13431#issuecomment-3576776361`](https://github.com/bitwarden/clients/issues/13431#issuecomment-3576776361) appears to demonstrate. [^1]</del> as [`bitwarden/clients/pull/7765`](https://github.com/bitwarden/clients/pull/7765#issue-2112185477) demonstrates, this can be disabled.

[^1]: [`community.bitwarden.com/t/97670`](https://community.bitwarden.com/t/how-can-one-invoke-the-electron-clients-devtools/97670?u=rokejulianlockhart)
