### ISSUE TITLE
Gatekeeper warning when installing app on Mac OS

### ISSUE THREAD

**Issue by ifrias-fuze** [electron-userland/electron-builder#2582]
* **Version**: 20.0.3

* **Target**: 1.7.10

Right now we are signing  our application artifacts  ( dmg, exe, nupkg ) with an authenticode certificate from digicert. The command used is this:

 electron-builder --mac -p always

Environment vars used : CSC_LINK, CSC_KEY_PASSWORD

For Mac OS,  what are the additional steps to enable our Developer ID certificate to sign the DMG so we don't get the gatekeeper warning after getting the release from Github Releases ? The Developer ID certificate is in keychain, so from the docs, electron-builder should pick it up and sign it properly before sending that version to GH.

My question is if we need to make any other configuration besides the one described on the documentation to enable code signing on Mac OS.

**Comment by develar** [comment]
`CSC_LINK` for macOS is broken in the 20.0.4, fix will be released today evening CET.

But if it is already in the keychain, but not used by electron-builder, please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by develar** [comment]
> authenticode certificate from digicert

Yep, for macOS only Apple certs are valid. Not from digicert.
