### ISSUE TITLE
GUID vs Application Name?

### ISSUE THREAD

**Issue by richard-fine** [electron-userland/electron-builder#2584]
* **Version**: ~19.49.0
* **Target**: NSIS

Can you explain more about the reason for creating registry keys using GUIDs rather than application names? I have already read the docs at https://www.electron.build/configuration/nsis but it doesn't make sense to me.

I get the feeling that it's because you want to avoid name collisions, but given that we are generating the GUID deterministically from the name anyway, it seems like anyone who uses the same name would generate the same GUID, and get a collision anyway?

We'd prefer to use a properly named key for two reasons:
* We are already shipping other (non-Electron) applications which are using named keys (HKLM/Software/CompanyName/...) and we'd prefer to keep all our applications grouped under the same key.
* We have customers who want to detect our application based on the presence of the registry key, and telling them "check for HKLM/Software/CompanyName/ProductName" is much nicer than "check for HKLM/Software/<some GUID>".

Is there some way we can override this behavior, either by (ab)using the keys in build.nsis, or by using custom NSIS script/macros/etc?

**Comment by develar** [comment]
Thanks for clear question.

> and get a collision anyway

but scope is not so wide and limited to electron-builder produced electron apps.

> We'd prefer to use a properly named key

Because of that, format of specified `guid` is not validated. Use whatever you want :)

```json
"build": {
  "nsis": {
    "guid": "whatever_you_want"
  }
}
```

**Comment by Mic75** [comment]
We're facing a side effect when specifying a custom guid.
The application is not listed anymore in the _Add / Remove Program_ Window from the Control Panel.

Any ideas about that?
