### ISSUE TITLE
Can we publish nsis and nsis-web at the same time with auto update?

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#2588]
* **Version**: `19.56.0`

* **Target**: `build --win --x64 --ia32 -p always`

We are looking to publish `nsis` and `nsis-web`.

```
    "win": {
      "target": [
        "portable",
        "nsis",
        "nsis-web"
      ]
    },
```

We will mostly distribute the `nsis-web` installer, but we want to have the `nsis` installer available for people to download independently if needed. I notice that when we publish to GitHub releases only the `nsis-web` `latest.yml` is attached. Will auto-update for the `nsis` still work in this case? Can we publish `nsis` and `nsis-web` together?

**Comment by sandeep1995** [comment]
It was really good question, not sure why it was never answered!

**Comment by andidev** [comment]
I can confirm that update still works but it will be random what installer will be used since latest.yml will be randomly from `nsis` and `nsis-web`.
In case `nsis` wins installation process will be slower while with `nsis-web` it will be faster since it downloads half the size.

**Comment by andidev** [comment]
Relates to
https://github.com/electron-userland/electron-builder/issues/8794
