### ISSUE TITLE
Could not find file 'xxxxx\xxx-win32-ia32\ui_resources_200_percent.pak'

### ISSUE THREAD

**Issue by valaxy** [electron-userland/electron-builder#259]
After input `.\node_modules\.bin\build -d dest` on win7, the error occurs:
Sometimes, it report `Could not find file 'xxxxx\xxx-win32-ia32\ui_resources_200_percent.pak`, sometimes, it report `Could not find file 'xxxxx\xxx-win32-ia32\LICSENCE`, sometimes the other files.

I double checked the `xxx-win32-ia32` directory, I did really have those files, How can I fix that?

**Comment by havenchyk** [comment]
@valaxy electron-builder uses the fork of electron-winstaller under the hood, so please check, is it the same issue https://github.com/electronjs/windows-installer/issues/45?

**Comment by uggrock** [comment]
I have the same issue. The message I get is that it is missing 'msccr120.dll'.

**Comment by havenchyk** [comment]
@uggrock I believe it's an another issue. http://superuser.com/a/827889/288765

**Comment by uggrock** [comment]
But I have this file in the dist folder. The files is copied from the electron-prebuilt distribution.

**Comment by develar** [comment]
Please try [3.0.0](https://github.com/electron-userland/electron-builder/releases/tag/v3.0.0) (`next` version). Please be aware of breaking changes (see release notes).
