### ISSUE TITLE
Allow configuration of entry file if using CRA

### ISSUE THREAD

**Issue by nfantone** [electron-userland/electron-builder#2592]
* **Version**: `20.0.4`

As per recent (great) additions, `create-react-app` is automatically identified. However, the name and location of your application's entry file is [strictly imposed by the build pipeline](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/presets/rectCra.ts#L8). It'd be nice to allow users to configure it's location/path/name instead of forcing one.

What about using `package.json` own `"main"` property instead?

Thanks!

**Comment by develar** [comment]
Do you mean that your app compiles fines, but in any case you got this warn?

**Comment by nfantone** [comment]
@develar No, sorry. Misleading explanation on my part. Piggybacking on your response, I'll rephrase the issue as: "My app compiles fine _only_ if I place a file called `electron.js` under a directory called `public/`".

I was asking if we could, somehow, omit the hard restriction on users and let them use any entry file they want. For example, I initially had a `public/main.js` file (ie.: **not** named `electron.js`) and the build was failing on me.

**Comment by develar** [comment]
@nfantone Simply set `extends` to `null` and configure project as you want:

```
{
    directories: {
      buildResources: "assets"
    },
    files: ["build/**/*"],
  }
```

i.e. exactly what default config for react-cra is.

> What about using package.json own "main" property instead?

Original idea was that this entry for non-electron version. That's why there is 

```
extraMetadata: {
      main: "build/electron.js"
    }
```

in the default config. 

I think, we need to check both electron.js and main.js files.

**Comment by nfantone** [comment]
@develar Got it. But still, I wouldn't want to lose every other (present or future) defaults. Is there any way to keep the config extension while _overriding some values_?
