### ISSUE TITLE
Documentation - auto-update with channels

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#2593]
Hi @develar ! I'm ready to write some documentation about release with channels as said in #1182. Who could I write this ?

1. In this tutorial section (create a new tutorial) : https://github.com/electron-userland/electron-builder/tree/master/docs/tutorials ?
2. Or in this auto update page : https://github.com/electron-userland/electron-builder/blob/master/docs/auto-update.md ?

I think 1. is the more better path to do that.

**Comment by develar** [comment]
Yes, separate tutorial is better. Thanks a lot in advance.

**Comment by popod** [comment]
@devlar Ok!
I've already written a draft in this PR #2595 . I close this issue and we could discuss about the documentation in the PR.
