### ISSUE TITLE
How do I add dependencies to AppImage builds?

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#2597]
* **Version**: 19.56.0

* **Target**: x64

My app uses the keytar library, which depends on libsecret.

We tried submitting our AppImage build to AppImageHub, however, it is failing their Travis CI build with:

> Error: libsecret-1.so.0: cannot open shared object file: No such file or directory

The AppImage maintainer says that we need to bundle the libsecret dependency with our AppImage build.

See https://github.com/AppImage/appimage.github.io/pull/379

I see a way to specify the `depends` option array on `deb` and `rpm` builds, but I do not see that option available for `appImage` at https://www.electron.build/configuration/linux

How do I specify dependencies for the packaged AppImage?

My project, for reference: https://github.com/bitwarden/desktop

**Comment by kspearrin** [comment]
@develar So this would require us to package the libsecret binary with the AppImage itself?

**Comment by develar** [comment]
@kspearrin Actually, I think that you don't need to bundle libsecret — all known for me and used by users Linux distro contains this dependency. That's why we don't bundle it by default. So, I suggest to ask AppImageHub to add this dependency to Travis.

> us to package the libsecret binary with the AppImage itself

Yes.
