### ISSUE TITLE
Bintray publisher doesn't escape filename

### ISSUE THREAD

**Issue by vassilevsky** [electron-userland/electron-builder#2600]
Hello 🙃

First of all, THANK YOU for an amazing project! I was pleasantly surprised by how well it works with all the defaults!

NSIS builder uses `${productName} Setup ${version}.${ext}` file name template by default. When it is uploaded to Bintray, the following error occurs:

```
TypeError: Request path contains unescaped characters
```

[Full build log](https://ci.appveyor.com/project/IlyaVassilevsky/overtube/build/1.0.5)

I have changed `artifactName` to `${productName}-${version}.${ext}` and it was uploaded without problems.

It seems that file name should be escaped before it is added to request path.

I used:
* AppVeyor (your sample template)
* node 8.9.4
* electron-builder@20.0.5

**Comment by waseemballoul** [comment]
It’s a great project 👍👍

**Comment by develar** [comment]
Please try 20.0.6 (it is `next` release).
