### ISSUE TITLE
.exe ffi module can't find dll, Dynamic Linking Error: Win32 error 126 

### ISSUE THREAD

**Issue by tiancovici** [electron-userland/electron-builder#2602]
**Version using:**
`"electron-builder": "^20.0.5"`
**Trying to build Angular 5 + Electron for Windows**
I have following structure:
```
/Project
--/src          (angular)
--/electron (electron)
--/---/renderer
--/dist           (angular build)
--/---/assets (angular build assets, dll files as well)
--/release     (electron build)

```

and everything seems to work but asset dll file isn't integrated well
if i run electron ./electron directory, dll file gets integrated well. 

**Inside main.js i refer to it as the following**
```
var rcs9k = ffi.Library(path.join(__dirname, './renderer/assets/RCS9K'), {
 'Initial':       ['int',['int', 'int'] ]
})
```
I created a script that copies dist folder content to electron/renderer, and package.json to electron, then i try to build electron
```
{
  "name": "TEST",
  "version": "0.0.0",
  "license": "MIT",
  "main": "main.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "buildProd": "ng build --prod --aot --output-hashing false",
    "copyFiles": "cpx ./dist/* ./electron/renderer && cpx ./dist/assets/* ./electron/renderer/assets && cpx package.json ./electron",
    "electron": "electron ./electron",
    "win": "electron-builder -w"
  },
  "build": {
    "appId": "test",
    "directories":{
      "buildResources": "electron/assets",
      "app": "electron",
      "output": "release"
    }
  },
.. dependencies

}
```

**Comment by develar** [comment]
Please use `extraResources` to copy dlls (so, it will be not packed into asar). https://www.electron.build/configuration/contents#extraresources Please use `process.resourcesPath` to construct path in the production mode.

**Comment by tiancovici** [comment]
Thanks,
I'm still facing this issue after including extraResource, am i doing something wrong here?

  "build": {
    "appId": "radar.raccon",
    "directories":{
      "app": "electron",
      "output": "release"
    },
    "extraResources": ["electron/renderer/assets/*.dll"]
  },

**Comment by develar** [comment]
@tiancovici What files do you see in the `dist/win-unpacked/resources`?

**Comment by tiancovici** [comment]
@develar I see the files I need in the following structure

`win-unpacked/resources/electron/renderer/assets`

in my main.js I refer to the following path
`path.join(__dirname, './renderer/assets/<file name>')`

**Comment by tiancovici** [comment]
I guess the question is
How do I reference a dll file inside main.js, and make sure it can reference it in the final build 
inside resources?
