### ISSUE TITLE
electron-builder 20.0.5 Cannot find module 'app-builder-bin-win'

### ISSUE THREAD

**Issue by meltedspark** [electron-userland/electron-builder#2603]
* **Version**: 20.0.5

* **Target**: Windows

`electron-builder` on Windows (both ia32 & x64) fails with the following error:

>   • executing node-gyp rebuild arch=x64
>   • installing production dependencies platform=win32 arch=x64 appDir=D:\playground\electron-angular-native\dist
>   • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
>   • packaging       platform=win32 arch=x64 electron=1.8.2 appOutDir=build-artifacts\win-unpacked
> Error: Cannot find module 'app-builder-bin-win'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (D:\playground\electron-angular-native\node_modules\app-builder-bin\index.js:16:90)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at _load_appBuilderBin (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\builder-util\out\util.js:219:29)
>     at Promise (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\builder-util\src\util.ts:356:11)
>     at new Promise (<anonymous>)
>     at executeAppBuilder (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\builder-util\src\util.ts:355:3)
> From previous event:
>     at WinPackager.resolveIcon (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:562:36
>     at Generator.next (<anonymous>)
>     at WinPackager.getOrConvertIcon (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:587:11)
>     at Lazy.WinPackager._iconPath.Lazy (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:59:43)
>     at Lazy.get value [as value] (D:\playground\electron-angular-native\node_modules\lazy-val\src\main.ts:18:23)
>     at WinPackager.getIconPath (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:195:27)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:292:33
>     at Generator.next (<anonymous>)
>     at WinPackager.signAndEditResources (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\winPackager.js:405:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:343:18
> From previous event:
>     at WinPackager.getOrConvertIcon (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:587:11)
>     at Lazy.WinPackager._iconPath.Lazy (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:59:43)
>     at Lazy.get value [as value] (D:\playground\electron-angular-native\node_modules\lazy-val\src\main.ts:18:23)
>     at WinPackager.getIconPath (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:195:27)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:292:33
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.signAndEditResources (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\winPackager.js:405:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:343:18
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.signApp (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\winPackager.js:423:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:211:16
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)
> From previous event:
>     at WinPackager.doPack (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:268:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:115:16
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.pack (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:188:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:372:24
>     at Generator.next (<anonymous>)
>     at xfs.mkdir.er (D:\playground\electron-angular-native\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at Packager.doBuild (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:441:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:316:52
> From previous event:
>     at Packager._build (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:385:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:278:23
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)
> From previous event:
>     at Packager.build (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:341:11)
>     at D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\src\index.ts:50:40
>     at Generator.next (<anonymous>)
> From previous event:
>     at build (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\electron-builder-lib\out\index.js:47:21)
>     at build (D:\playground\electron-angular-native\node_modules\electron-builder\src\builder.ts:228:10)
>     at then (D:\playground\electron-angular-native\node_modules\electron-builder\src\cli\cli.ts:48:33)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)
> From previous event:
>     at Object.args [as handler] (D:\playground\electron-angular-native\node_modules\electron-builder\src\cli\cli.ts:48:33)
>     at Object.runCommand (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
>     at Object.parseArgs [as _parseArgs] (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\yargs\yargs.js:1014:30)
>     at Object.get [as argv] (D:\playground\electron-angular-native\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
>     at Object.<anonymous> (D:\playground\electron-angular-native\node_modules\electron-builder\src\cli\cli.ts:42:15)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Function.Module.runMain (module.js:676:10)
>     at findNodeScript.then.existing (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\index.js:266:14)
>     at <anonymous>

**Comment by meltedspark** [comment]
Fixed in 20.0.6 (electron-builder@latest installs 20.0.5 though)

**Comment by laurent22** [comment]
Same issue on macOS and Linux with 20.2.0. Solution is `npm install --save-dev app-builder-bin`

**Comment by harryhahn** [comment]
i use nvm and 
i copy the content of the project node_module/app-builder-bin-win  folder to the nodes folder like 
C:\Users\harry\AppData\Roaming\nvm\v8.2.1\node_modules\electron-builder\node_modules.
and now it runs
