### ISSUE TITLE
do not strip "bugs" field from package.json

### ISSUE THREAD

**Issue by mcous** [electron-userland/electron-builder#2606]
* **Version**: Applies to >= v19.49.3

* **Target**: macOS (zip), Windows (NSIS), Linux (deb) 

First off, thanks for all your hard work on this project!

I would like to include a "Report an Issue" link in my app. For consistency, I would like to drive that link with the `bugs.url` field in my application's `package.json`. However, 4dc71d7 introduced a change in `packages/electron-builder-lib/src/fileTransformer.ts` so that the `bugs` field gets stripped from `package.json`.

This ticket is to request that `bugs` not be removed, or if its removal is important for some use-cases, an option similar to `removePackageScripts` and `extraMetadata` to whitelist certain fields from removal. If one of these changes seem useful, I'm happy to open a PR!

**Comment by develar** [comment]
To avoid such issues, `bugs` should be removed only from dependencies, not from app package.json. Thanks for clear error report.

**Comment by mcous** [comment]
Thank you very much for the quick resolution!
