### ISSUE TITLE
webpackJsonp problem loading in electron.

### ISSUE THREAD

**Issue by manodupont** [electron-userland/electron-builder#2609]
* **Version**: 
"electron": "^1.8.2",
"electron-builder": "^20.0.5",

* **Target**: 
All

I always have the same issue : webpackJsonp is not recognized. My index.html starts my app, that is bundled, as this: 

```
<script id="vendors" src="assets/vendors.js"></script>
<script id="source" src="assets/main.js"></script>
...
```

Wha i can see in my app folder extracted, is that all my files are there. At the path they need to be. proof is, its really reading the webpacked version cause i have an error from it. But, why can't it be read ? I always have the same error about webpackJsonp which is declared in vendors, which is read first in my index.html. So it should work.

**Comment by develar** [comment]
I guess because of asar packaging. Please try to use `asarUnpack` for renderer files.
