### ISSUE TITLE
Publish to s3 giving error on electron-publish-s3

### ISSUE THREAD

**Issue by cookiejest** [electron-userland/electron-builder#2610]
* **Version**: 
    "electron": "~1.7.8",
    "electron-builder": "^20.0.6",
    "electron-publisher-s3": "^20.0.5",

Windows, distribute to S3 bucket using electron-publisher-s3

I get an error message saying electron-publisher-s3 cannot be found inside the electron-builder module.

I can see it is installed correctly both globally and locally. Any ideas?

//Package.json file
```
 "scripts": {
    "start": "./node_modules/.bin/electron .",
    "test": "mocha",
    "win": "electron-builder -w",
    "make-cert": "electron-builder create-self-signed-cert -p xxcertname"
  },
  "build": {
    "win": {
      "certificateFile": "private/xx.pfx",
      "verifyUpdateCodeSignature": false,
      "publisherName": "xxcertname",
      "publish": [
        {
          "provider": "s3",
          "bucket": "MYSECRETBucketname"
        }
      ]
    }
  },
```

**Comment by develar** [comment]
Please provide full error stack trace. Do you use yarn or npm?

**Comment by cookiejest** [comment]
NPM

**Comment by develar** [comment]
So, try to remove node_modules and install again.

**Comment by cookiejest** [comment]
Doing that now, however I feel it is a version issue with "electron-publisher-s3"

**Comment by cookiejest** [comment]
I was building successfully to github without issue

**Comment by cookiejest** [comment]
Ok I have redone npm install.. now when I attempt to publish I 

C:\Users\adamc\AppData\Roaming\npm\node_modules\electron-builder\out\cli\cli.js:1
(function (exports, require, module, __filename, __dirname) {


SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)

**Comment by cookiejest** [comment]
ok i got this working
