### ISSUE TITLE
electron-updater error when restart for update

### ISSUE THREAD

**Issue by hallss93** [electron-userland/electron-builder#2612]
* **Version**:  20.0.7

* **Target**:  2.20.1

In my application I use electron-updater 2.20.1 and electron-builder 20.0.7.
When the application receives the update, which it closes to install, windows opens the taskkill.exe to kill the open process for installation. OK. But the taskkill is fixing the following error:
```
ERROR: Process with PID 2728 <child process of PID 6024> could not be finalized.
Reason: The process can not finalize itself.
SUCCESS: The process with PID 5660 <PID child process 2768> has been finalized.
[...]
```

I do not understand why this error, since the installer I understand does not work as ChildProcess.
Can someone help me?

**Comment by hallss93** [comment]
@develar-vacation some news?

**Comment by develar** [comment]
Duplicates #2516
