### ISSUE TITLE
Dynamic builds renaming not working on linux after 20.x version of builder

### ISSUE THREAD

**Issue by verget** [electron-userland/electron-builder#2615]
* **Version**: 20.0.6
* **Target**: linux

After update to 20.0.6 version `build --linux --em.name=newName` failed with error `Unknown argument: em`. When I tried `--confign.name=newName` - I had error `configuration has an unknown property 'name'`, command `--confign.productName=newName` return no error but also didnt do anything with build name, it still marked as wrote in package.json productName field.

**Comment by develar** [comment]
`--config.extraMetadata.name`
