### ISSUE TITLE
Cannot find module 'google-auth-library' after build

### ISSUE THREAD

**Issue by pamtbaau** [electron-userland/electron-builder#2618]
* **Version**: 20.0.8

* **Target**: Windows 10

In the `main.js` of my Electron app I `require('google-auth-library')` to authenticate the app to read my Gmail. When running the app using `electron .` all works fine. When building the application using `electron-builder`, and running the generated `.exe` I get the error `Cannot find module 'google-auth-library'`

**Comment by pamtbaau** [comment]
Solved. My bad...

**Comment by dm-Heirloom** [comment]
What was the problem?  I'm facing something similar.  Thx.

**Comment by pamtbaau** [comment]
@dm-Heirloom I'm sorry, I should have included what the mistake was...

According the history of my repo.... I removed `"!**/build"` from "files" in the electron-builder config in package.json:
```
"files": [
   "!.vscode",
   "!config",
   "!src",
   "!**/build",                <-- I removed this line
   "!**/*/credentials"
],
```
