### ISSUE TITLE
autoUpdater.quitAndInstall causes app to re-open twice with nsis

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#2619]
* **Version**: electron-builder 20.0.7 and electron-updater 2.20.1

* **Target**:  build --win --x64 --ia32

We use `nsisWeb` with:

    "nsisWeb": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "artifactName": "${productName} Installer ${version}.${ext}",
      "uninstallDisplayName": "${productName}",
      "deleteAppDataOnUninstall": true
    },

We also handle updates manually with `autoUpdater` and prompt the user when an update is ready to install. If the user selects to "Restart Now", we call `autoUpdater.quitAndInstall();`. This causes the installer to run, and install the update.

After the update is installed the app automatically starts back up. This is the desired behavior.

The problem is that the "completed" installer window is still shown with the "Run" checkbox checked.

![image](https://user-images.githubusercontent.com/1190944/36564871-c7944246-17ec-11e8-9adc-bf8485bd6763.png)

If a user closes the installer window another instance of the app opens. We would like the ability to stop the installer window from staying open on the "completed" step whenever updates are ran from `autoUpdater.quitAndInstall();` since the app is going to open back up already anyways. I tried `autoUpdater.quitAndInstall(false, true);` as well, but it didn't seem to change anything.

**Comment by akashnimare** [comment]
I was about to open an issue for this.
