### ISSUE TITLE
Issue: Code singing not working

### ISSUE THREAD

**Issue by fpsqdb** [electron-userland/electron-builder#2631]
* **Version**:  20.0.8

* **Target**: win-64

After upgrade from 19.56.0, code singing not working, there is no sign process information from output, 
it seems that builder skip the sign step, follow is the output.

  • electron-builder version=20.0.8
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=D:\Project\builder\electron-builder.yaml
  • no native production dependencies
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
  • packaging       platform=win32 arch=x64 electron=1.7.9 appOutDir=D:\Project\builder\win-unpacked
  • building        target=nsis file=D:\Project\builder\Test Setup 1.0.0.exe archs=x64 oneClick=false
  • building block map blockMapFile=D:\Project\builder\Test Setup 1.0.0.exe.blockmap

and this is the output from 19.56.0

  • electron-builder version=19.56.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=D:\Project\builder\electron-builder.yaml
  • no native production dependencies
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
  • packaging       platform=win32 arch=x64 electron=1.7.9 appOutDir=D:\Project\builder\win-unpacked
  • signing         file=D:\Project\builder\win-unpacked\Test.exe certificateFile=D:\Project\Test\build\win\temp.pfx
  • building        target=nsis file=D:\Project\builder\Test Setup 1.0.0.exe archs=x64 oneClick=false
  •   Signing NSIS uninstaller file=D:\Project\builder\.__uninstaller-nsis-Test.exe certificateFile=D:\Project\Test\build\win\temp.pfx
  • signing         file=D:\Project\builder\Test Setup 1.0.0.exe certificateFile=D:\Project\Test\build\win\temp.pfx
  • building block map blockMapFile=D:\Project\builder\Test Setup 1.0.0.exe.blockmap

**Comment by kspearrin** [comment]
Just thought I'd share, I'm using 20.1.0 and my EV code signing is still working fine.

**Comment by fpsqdb** [comment]
20.1.1 is still not working for me.

**Comment by Negan1911** [comment]
I think that could be related to #2639 could you verify?

**Comment by fpsqdb** [comment]
@Negan1911 that works, thanks!
