### ISSUE TITLE
Use projectDir instead of project

### ISSUE THREAD

**Issue by tangb** [electron-userland/electron-builder#2633]
* **Version**: 
20.0.8

* **Target**: 
linux 64bits

When executing on linux debian stable amd64 (8.10):
> ./node_modules/.bin/electron-builder --linux --x64 --projectDir "build/myproject_tree"

I got this error:
> Use projectDir instead of project

Is this option deprecated? **=> EDIT: yes --project is deprecated but not --projectDir (according to changelog v20.0.0)**
I tryed with --project instead of --projectDir and it did the same. **=> EDIT: yes it is the same option ;-)**

I used it 6 months ago and it works, is the option changed?

Thank you very much ;-)

**Comment by tangb** [comment]
Here is the build part of my package.json:

```
    "build": {
        "appId": "com.cleep.cleepdesktop",
        "productName": "CleepDesktop",
        "asar": false,
        "linux": {
            "icon": "resources/",
            "target": [
                "tar.gz",
                "AppImage",
                "deb"
            ],
            "maintainer": "me <me@me.com>",
            "category": "Network",
            "executableName": "cleepdesktop",
            "synopsis": "Cleep devices manager"
        },
        "AppImage": {
            "systemIntegration": "ask"
        },
        "deb": {
            "icon": "resources/256x256.png",
            "packageCategory": "misc",
            "priority": "optional",
            "depends": []
        },
        "win": {
            "icon": "resources/icon",
            "target": "nsis"
        },
        "nsis": {
            "menuCategory": "Cleep",
            "shortcutName": "CleepDesktop"
        },
        "mac": {
            "category": "public.app-category.utilities",
            "target": "dmg",
            "icon": "resources/icon",
            "extendInfo": "Info.plist"
       },
        "dmg": {
            "icon": "resources/icon.icns"
        }
    }
```

**Comment by stefanedberg** [comment]
I'm having the same problem. 

electron-builder 20.2.0
npm 5.6.0
node.js v8.9.1

```
build -mw --projectDir dist/
```

**Comment by cybertim** [comment]
`--projectDir` does not work since version 19.56.2
My work around is running the `electron-builder` inside the correct folder.
It is probably due to the https://github.com/electron-userland/electron-builder/blob/9d6eb9602522048597b185c604f02387820aa8d9/packages/electron-builder-lib/src/packager.ts#L139 check on the name project that also matches with projectDir.

**Comment by stefanedberg** [comment]
To be able to run in the root my solution was this (two package-json structure):

package.json
```
...
"scripts": {
    "dist": "cd dist/ && build -mw"
}
...
```

**Comment by tangb** [comment]
@develar you're the best, thank you very much for the fix :+1:
