### ISSUE TITLE
productName to App's path and Working directory

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#2638]
* **Version**:  20.0.6

* **Target**:  NSIS

Hi Guys. I've got an interesting issue with productName config field. In my case, I need to build two different apps. The production and Beta apps. I need two absolutely independent apps. I use one package.json file and two .yml files which I pass with -c="" CLI param. To rename my app to "AppName Beta" I use productName field in the beta.yml. I've noticed that the on Windows (NSIS with default config oneClick = true etc...) the resulting app path and working directory are: 

Path to app:
```C:\Users\UserName\AppData\Local\Programs\${name from package.json here}\{productName from .yml file here}.exe```

Working Directory:
```C:\Users\UserName\AppData\Local\Programs\${name from package.json here}```

Is it right? 
${name from package.json here} should be {productName from .yml file here} in both cases. 
If productName is declared, it should be used in the Path instead name from package.json Or I'm wrong? (edited)

**Comment by develar-vacation** [comment]
You must change also name https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390

‘-c.extraMetadata.name=foo’

**Comment by sagorshkov** [comment]
But I cant use spaces there, rught?) With productName I can...

25 февр. 2018 г. 17:34 пользователь "develar-vacation" <
notifications@github.com> написал:

**Comment by sagorshkov** [comment]
if i declared product Name it should've used instead name from package.json
automatically. In all cases. Or not?

25 февр. 2018 г. 17:54 пользователь "Sergey Gorshkov" <
sgorshkov@crystalnix.com> написал:

**Comment by develar-vacation** [comment]
There are places where name is also used. So, to be sure, I suggest to change both name AND productName.

**Comment by sagorshkov** [comment]
Looks like ‘-c.extraMetadata.name=App\ Name’ works with spaces too. But I cant understand, If I have to use -c.extraMetadata.name I don't need productName at all, right?

**Comment by develar-vacation** [comment]
Well, yes. Please check that electron API app.getPath works correctly.
