### ISSUE TITLE
CSC_LINK is ignored on Windows

### ISSUE THREAD

**Issue by salomvary** [electron-userland/electron-builder#2639]
* **Version**:  20.2.0 

* **Target**: Windows

Despite the [documentation implies](https://github.com/electron-userland/electron-builder/blob/e67013507e8268ae92cba57db10f28eee22d6333/docs/code-signing.md) `CSC_LINK` and `WIN_CSC_LINK` are interchangeable on Windows, `CSC_LINK` seems to be competely ignored and no code signing is attempted. Example of a [build running on AppVayor](https://ci.appveyor.com/project/salomvary/electron-hello-world/build/1.0.15) with `CSC_LINK` set.

Everything works as expected if I use `WIN_CSC_LINK`.

**Comment by arantes555** [comment]
Seeing the same problem... Worked fine until 19.56.0

**Comment by Syed-Umair** [comment]
Any update on this issue. I am also facing the same problem. Do I have to update in all my projects to this new environmental variable name or should I wait?

**Comment by develar-vacation** [comment]
I am on vacation. Will be fixed Saturday. For now you can pin electron builder version and do not update.
