### ISSUE TITLE
how to build inno installer on windows

### ISSUE THREAD

**Issue by jokyme** [electron-userland/electron-builder#2645]
* **Version**: 19.47.1
electron-updater(version):2.16.3
* **Target**: windows x32

i packaged a inno installer as a upgrade application
when i update the application, the sha512 is not match because i replace the nsis installer with inno installer. and the lastet.yml is auto generation by electron-builder. so, how to solve this problem?

how to make a inno installer with electron-builder on windows, and update the application with electron-updater.

**Comment by develar-vacation** [comment]
Well, what’s problem to update sha512? 

Btw, why inno?

**Comment by jokyme** [comment]
@develar-vacation because inno can identify the version already installed, the next installation will not allow users to choose the installation directory.
i want to install and update my application as normal but not "oneclick".

**Comment by samuelcarreira** [comment]
I use Inno setup (like visual studio code) because I am familiar with that setup
I created a gulp task to automate the build process (build, update version on ISS file, etc.).
First, you build your windows app to a dir (no packed)
Then you pack that folder with the Inno Setup
