### ISSUE TITLE
nsis installer isuee with “artifactName”

### ISSUE THREAD

**Issue by jokyme** [electron-userland/electron-builder#2646]
* **Version**: 19.47.1
electron-updater(version):2.16.3
* **Target**: windows x32

i set the artifactName, and when i installing the program,
The second installation will uninstall the previously installed program,
And will not install the new version

```
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "artifactName": "${productName}.${ext}",
      "installerLanguages": "zh_CN",
      "language": "2052",
      "runAfterFinish": true,
      "perMachine": true,
      "createDesktopShortcut": true,
      "guid":"6FE791B5-1E82-4E2F-97DB-85DCE411B49C"
    },
```

**Comment by develar** [comment]
guid is used to detect is app the same or not. Not filename.
