### ISSUE TITLE
NSIS Multilanguage installer: overridable strings?

### ISSUE THREAD

**Issue by TheSLX** [electron-userland/electron-builder#2649]
This is not a bug report (as what I'm asking is not implemented as far as I know)

* **Version**:  19.19.1

2.4.4 (not relevant)

* **Target**: Windows / Mac (only windows is relevant)

I have learned trough various searches that the NSIS installer is localized in certain languages if you enable multiLanguageInstaller.
I have done so an it works as I expected, but I'm having some issues with text clipping in certain languages (due to the long application name).

I was wondering if there was any way to override the default translation strings (even for a specific language would help me).
I don't mind getting my hands dirty in NSIS scripts or even the open source, but I am looking for a starting point.
I'm currently using a custom include (build/installer.nsh), is that the place where I could override some global variables or is that a dead end?

I'm sorry if this is not the right place to ask this.

Thank you

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
