### ISSUE TITLE
NSIS oneClick arguments

### ISSUE THREAD

**Issue by meekaah** [electron-userland/electron-builder#2655]
* **Version**: 20.0.8

* **Target**: Windows

I havent found any way to define CLI arguments to the auto launched application (using oneClick) with the default NSIS templates. 

It seems i would need to use a full custom script for that simple need, am I missing something? 

What would be even better would be to be able to set CLI args for shortcuts as well (desktop / start menu)

Anyways thanks for the help

**Comment by meekaah** [comment]
i've also thought that electron-updater should probably also reuse the CLI args that were passed to the main process when killing and restarting the app after the update

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
