### ISSUE TITLE
Why you delete travis yml example?

### ISSUE THREAD

**Issue by PinkyRabbit** [electron-userland/electron-builder#2658]
Hello! All from wiki was moved to website. And really hard to find info, when you dont know what to seek. I learning electron now and try to bind together bintray plus github with Travis CI. I found some guides, all linked to [this page](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts). But wiki was moved and there is nothing about Travic CI. I found some... examples, dont know is they good or not, but I'll try to use it. I created this issue because, after all my walknigs around theme, I remembered funny poem about npm packages. Maybe it will be reason to return some examples in github electron-bulder wiki:
```
This Is Just To Say

I have deprecated
the packages
that were on
your profile

and which
you were probably
wishing
to unpublish

Forgive me
they were precious
so unsupported
and so old.
```
Dont remember who author, but not me. Nice day and thanks for electron and electron-builder!

**Comment by develar** [comment]
Hmm... travis example was always on Multi Platform Build page.

https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows

**Comment by develar** [comment]
If you want to add some examples to docs — you are welcome. Just open pull request ;)
