### ISSUE TITLE
Can't run app if asar is not used (msi target)

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#2659]
* **Version**:  20.0.8
* **Electron**: 1.8.2
* **Target**: msi

I've changed my configuration in order to build both *.exe and *.msi installers:
```
    "win": {
      "target": [
        {
          "target": "nsis"
        },
        {
          "target": "msi"
        }
      ]
    },
    "nsis": {
      "deleteAppDataOnUninstall": true,
      "packElevateHelper": false,
      "differentialPackage": false
    },
    "msi": {
      "warningsAsErrors": false
    },
```

By default we don't pack node_modules into asar, because it can lead to some errors. So the configuration also includes:
```
  "asarUnpack": [
    "node_modules/**"
  ],
```
The build process is successful, but when I run *.msi, it is installed and app is launched, I got the error:
![image](https://user-images.githubusercontent.com/9727404/36933288-823ffdbe-1ee7-11e8-893e-990287ea5609.png)

I also tried to set `"asar": false`, but received an error:
![image](https://user-images.githubusercontent.com/9727404/36933424-664dbe6e-1ee9-11e8-887a-c371529ecbe1.png)

Only `"asar": true` without `asarUnpack` property works fine and *.msi can be installed and run without errors.

No issues with *.exe file in any of this cases. I believed that both installers creates the same file structure, but it doesn't seem to be true.

Also I found out that both application installed via *.exe and *.msi use the same data (local storage, settings and so on), but they are displayed as two separate programs in 'programs and features list'. When I uninstall one of them, all program data is removed, so the second app entry is not valid any more. Is it expected behavior?

**Comment by develar** [comment]
Close #2272
