### ISSUE TITLE
Built application displays nothing but a white screen

### ISSUE THREAD

**Issue by kingerking** [electron-userland/electron-builder#2662]
So when I build my project no errors are shown during the building process, but when I try to open the built version it simply displays a white screen upon opening. My build settings in the package.json looks like so: 
```
  "build": {
    "appId": "com.example.electron-cra",
    "files": [
      "**"
    ],
    "directories": {
      "buildResources": "."
    }
  },
```
and my "pack" npm script is simply calling "electron-pack"

**Comment by dwalintukan** [comment]
I am having the same issue. Previously it was working fine. FYI, I am using `restify` to serve a static webpage and using electron to go to the localhost in which it is ported to.

**Comment by gknapp** [comment]
I've been struggling with the same issue. I think it's a problem with the path the resources as @venkatgoud mentioned. I noticed today that if I am in one directory, run the executable, the application works, if I `cd` to another, I am presented with a blank screen.

My `BrowserWindow.loadURL()` and renderer `src` paths are relative, I've tried absolute but still have the same issue. I'm using `file://` URLs to access them.

I've not found a solution yet but have just stumbled across the electron docs on [application packaging](https://electronjs.org/docs/tutorial/application-packaging). It seems that reading resources from `asar` files should be transparent from within your source code.

I've tried the documented method in the quick start examples:

```javascript
browserWindow.loadURL(url.format({
  pathname: path.join(__dirname, "index.html"),
  protocol: 'file:',
  slashes: true
}));
```

Within my `app.asar` my files are in the `/build/` directory, so my code looks like: `path.join(__dirname, "build/index.html")`.

**Comment by N4G1B4T0R** [comment]
Hi, I got the same issue and I figure out this using devtools

`
 mainWindow.webContents.openDevTools();
 mainWindow.webContents.on("devtools-opened", () => {
     mainWindow.webContents.closeDevTools();
 });
`

I don't know how but it works for me. I guess, it would be helpful for u.

**Comment by Melegy90** [comment]
Why is this closed? No one provided any answer and this error still persists with me and I'm using the latest version to date (12.2.0)

**Comment by develar** [comment]
Because it is not electron-builder issue, please debug what's wrong using debugger/other tools.

**Comment by DanX3** [comment]
It may be a dump answer, but in my case I was using single quote character ' instead of a backtick `
I didn't know that backticks allows expansion of their argument

**Comment by Phiiii** [comment]
If any of you guys use React Router, one of the thing that might break your Electron build is `BrowserRouter`.

**Using `HashRouter` will fix this problem.**

**Comment by amolngt** [comment]
i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

blank white screen after one day..
Please Help

**Comment by amolngt** [comment]
> If any of you guys use React Router, one of the thing that might break your Electron build is `BrowserRouter`.
> 
> **Using `HashRouter` will fix this problem.**

i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

blank white screen after one day..
Please Help

**Comment by amolngt** [comment]
> It may be a dump answer, but in my case I was using single quote character ' instead of a backtick `
> I didn't know that backticks allows expansion of their argument

solved probelm?
i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

blank white screen after one day..
Please Help

**Comment by mtagaizi** [comment]
Could help : this line, in the main process, right after the imports, solved the problem in our case.

```
require('electron-debug')();
```

**Comment by sscullen** [comment]
Using MemoryRouter instead of BrowserRouter worked for me. https://stackoverflow.com/questions/47274378/react-router-v4-electron-does-a-timeline-exist-where-they-play-nice-together/47391340#47391340

**Comment by pbaldridge** [comment]
> Could help : this line, in the main process, right after the imports, solved the problem in our case.
> 
> ```
> require('electron-debug')();
> ```

Just a quick note here, if you use symantec, there is a good chance it will quarantine your .exe as soon as it's built if you add this require. I really, really despise symantec.

**Comment by conceptdeluxe** [comment]
Thx @Phiiii, this actually solved it 👍 

For the sake of completeness, here is the solution for Vue as well:

```
const router = new VueRouter({
    mode : 'hash',
    routes,
});
```

**Comment by mohamed1408** [comment]
> I have add similar problem before. Turns out that the path to css and js was incorrect.
> Are there are any errors in DevTools console?

dev tools not displaying but everything are ther but just not displaying including menus.

**Comment by laclance** [comment]
I have the same issue with an application that was working fine previously. No dev tools or menus, not sure how to debug

**Comment by laclance** [comment]
It seems app works when built without a windows code signing certificate but doesnt work when built with a valid certificate. We have another app though using the same certificate and it works fine.

**Comment by KillingJacky** [comment]
> Thx @Phiiii, this actually solved it 👍
> 
> For the sake of completeness, here is the solution for Vue as well:
> 
> ```
> const router = new VueRouter({
>     mode : 'hash',
>     routes,
> });
> ```

Confirm, same issue resolved. Thanks @Phiiii @conceptdeluxe

**Comment by kevincastejon** [comment]
I'm not using any router but I still got blank screen when app is built, in the earlier stages of my app developement it was working just fine, I really don't know what caused this.
What solution do you have for non-router-users ?

**Comment by mohamed1408** [comment]
> It seems app works when built without a windows code signing certificate but doesnt work when built with a valid certificate. We have another app though using the same certificate and it works fine.

Hi laclance actually the problem is in gpu
so run the app through cmd by disabling gpu

Path\to\your.exe --disable gpu

**Comment by Faksprod** [comment]
Same problem here. Blank screen after opening my signed `appName.app` or even after having installed the `appName.pkg` file. How am I suppose to get logs to investigate on this problem once the app has been signed? No error thrown in the Terminal during building and signing process.

Everything work fine when running `electron .`

I'm not using any router. Actually, I'm doing this test by using the [electron-quick-start](https://github.com/electron/electron-quick-start) example app, so I don't think the problem could comes from any part of the code in the `main.js`, `preload.js` or `rendere.js` files in which I didn't change anything.

I'm using:
```
"electron": "^5.0.13",
"electron-builder": "^22.0.0"
```

I'm trying to sign my app for a MAS submission. Thanks to [this post](https://github.com/electron/electron-osx-sign/issues/200#issuecomment-582149822) I succeed the step of signing my .app by following instructions on [this blog](https://webspaceteam.com/electron/how-to-publish-an-electron-application-to-mac-app-store).

Signing seems ok. But now... Blank screen!
Any advises guys? Thanks!

**Comment by semanticbodger** [comment]
For me, this was caused by my adding a self-sign localhost cert to my certificates.  When I removed it from Windows using the 'MMC' utility, the app came back up.

**Comment by HemantKumarProgrammer** [comment]
if you have an icon defined in electron's main.js(in Browser window), the problem maybe there. no worries, you can solve it
check this-
https://stackoverflow.com/q/63878416/13114354

**Comment by ntoporcov** [comment]
Been looking at this issue for a little while. For me it was caused because my app wasn't able to access environment variables from the built version.

A great way to find out what causes it (on windows at least) is starting the app from the command line. The error will get outputted there.

**Comment by jbool24** [comment]
> Using MemoryRouter instead of BrowserRouter worked for me. https://stackoverflow.com/questions/47274378/react-router-v4-electron-does-a-timeline-exist-where-they-play-nice-together/47391340#47391340

This solution also worked for me useing Vuejs. During runtime WebHistory (similar to react-router BrowserRouter) doesn't the load application pages correctly. For Vuejs and electron use `createMemoryHistory` to use in-memory routing.

**Comment by OmarYuusf** [comment]
This problem is due to the wrong link between the build folder & entry point of your app

DON’T USE in this way

mainWindow.loadURL(isDev ? ‘http://localhost:3000' : `file://${path.join(__dirname, ‘../build/index.html’)}`);

USE IN THIS WAY

mainWindow.loadURL(isDev ? ‘http://localhost:3000' : `file://${__dirname}/../build/index.html`);


and if you use React router you must replace (`Router`) >> (`HashRouter`)

**Comment by StepanovRoma** [comment]
It really works, you saved me from an unsolvable problem, I have an existing react project and adding electron to it <3

**Comment by HARISHKUMAR023** [comment]
thank man , now it working fine , happy coding !!
