### ISSUE TITLE
Can I build electron for armv6(Raspberry pi zero w) ?

### ISSUE THREAD

**Issue by idealist33** [electron-userland/electron-builder#2663]
* **Version**: 

2.0.0

* **Target**: 
raspberry pi zero w armv6

Hi I want to use electron project for raspberry pi zero w which architecture is armv6l.
I can execute my project in raspberry pi 3b (armv7l). how can I build my project?
Should I build my project with rpi zero w? I can't see any option for armv6l.

**Comment by agnoam** [comment]
Does someone know how to build for ARMv6 today ?
It's still a problem, I have built for ARMv7l for my Rpi 3 B+ and working fine. But I also need for armv6 (Raspberry zero W)
