### ISSUE TITLE
Ability to generate release notes from commits

### ISSUE THREAD

**Issue by armaldio** [electron-userland/electron-builder#2666]
Is it possible to generate releaseNotes from previous commits ?
Even with a CI ?

**Comment by develar-vacation** [comment]
In general yes, I don’t see any issues here.

**Comment by armaldio** [comment]
But how with electron-builder ?

**Comment by develar** [comment]
Well... it is out of electron-builder scope. PR welcome.

**Comment by armaldio** [comment]
OK, thanks!
