### ISSUE TITLE
Code signing for windows

### ISSUE THREAD

**Issue by GeometricProgress** [electron-userland/electron-builder#2669]
electron-builder: 20.2.0
"electron": "^1.8.3",
    "electron-builder": "^20.3.1",
    "electron-rebuild": "^1.6.0"

Hey guys, I must congratulate you on a champion repo.

I am trying to build my app for windows using my valid code signing p12 certificate.  I can't work out where the CSC_LINK and CSC_KEY_PASSWORD go? In the package.json file or in the cli?  If I must type it in the cli exactly what must I type. Furthermore, if mypassword contains characters like '%&@- etc" will that be a problem? 

my package .json is 
{
  "name": "UfmApp",
  "version": "1.0.0",
  "description": "Understanding the Financial Markets Course",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "win": "electron-builder -w",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "appId": "myid",
    "win": {
      "target": "nsis",
      "icon": "icon.ico",
      "certificateFile": "private/mycert.p12",
      "verifyUpdateCodeSignature": true,
      "publisherName": "Geometric Progression"
    }
  },
  "devDependencies": {
    "devtron": "^1.4.0",
    "electron": "^1.8.3",
    "electron-builder": "^20.3.1",
    "electron-rebuild": "^1.6.0",
    "video.js": "^6.7.4",
    "videojs": "^1.0.0",
    "videojs-playlist": "^4.0.2"
  },
  "dependencies": {
    "electron-json-storage": "^4.0.0",
    "electron-window-state": "^4.1.1",
    "node-machine-id": "^1.1.9",
    "npm": "^5.7.1"
  }
}

Any help would be great.

Thanks

Mark

**Comment by jonzlin95** [comment]
See the thread here https://github.com/electron-userland/electron-builder/issues/2639

Basically there's a bug and you need to use WIN_CSC_LINK and WIN_CSC_KEY_PASSWORD

**Comment by GeometricProgress** [comment]
Thanks for the prompt response. If I understand you correctly, although there is a bug if I add a script such as script1 below and in the CLI type yarn script1 it should work? 
"scripts": {
    "start": "electron .",
    "win": "electron-builder -w",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "script1": "set WIN_CSC_LINK=\"private/test.p12\" && set WIN_CSC_KEY_PASSWORD=\"pass\" && electron-builder -w",
    "postinstall": "electron-builder install-app-deps"
  }, 
When I do this I am now getting  PFX password incorrect.

Am I missing something?

Regards Mark

**Comment by GeometricProgress** [comment]
Please ignore the above.
I found out that when you add a script like script1 above, you must remove the quotes.  Therefore script1 should read:
"script1": "set WIN_CSC_LINK=private/test.p12 && set WIN_CSC_KEY_PASSWORD=pass && electron-builder -w"

Thanks for all your help!

**Comment by avvRobertoAlma** [comment]
I had the same problem.

**Comment by Aarbel** [comment]
Solved for me, thanks !

**Comment by QaisAlkhateeb** [comment]
This link was helpful for me:
https://stackoverflow.com/questions/16082333/why-i-get-the-specified-pfx-password-is-not-correct-when-trying-to-sign-applic
