### ISSUE TITLE
Issue building for x86

### ISSUE THREAD

**Issue by ECDonelson** [electron-userland/electron-builder#2671]
* **Version**: 
1.4.4

N/A

* **Target**: 
x86 Windows 7 Professional

I would like to know how to build an electron application using electron-builder for x86. I have no issue building for x64 but I have a users computer that's running x86 and I cant install the program on her computer because of the version difference. 

Is there a way to force which type of application electron-builder will build or is this a lost cause?

**Comment by jonzlin95** [comment]
```
"win": {
      "target": [
        {
          "target": "nsis-web",
          "arch": [
            "ia32",
            "x64"
          ]
        }
      ],
```
