### ISSUE TITLE
AutoUpdate: Linux AppImage, quitAndInstall doesn't rename the update correctly

### ISSUE THREAD

**Issue by SteffenDE** [electron-userland/electron-builder#2672]
* **Version**: 20.3.1
* **Target**: Linux AppImage

I tried to implement autoupdate using AppImage on Linux. I am starting the app from `/home/user/app.AppImage` on boot, but after updating the file is replaced with something like `installer-x.y.z-x86_64.AppImage`. On the next reboot, the original path doesn't exist any more and the app won't start. Is this expected behaviour? I thought the update process will just replace the old AppImage file with the new one.
```
[2018-03-07 02:14:08.800] [info] Checking for update
[2018-03-07 02:14:09.537] [info] Found version 0.1.11 (url: app-0.1.11-x86_64.AppImage)
[2018-03-07 02:14:09.540] [info] Downloading update from app-0.1.11-x86_64.AppImage
[2018-03-07 02:14:09.602] [info] No cached update available
[2018-03-07 02:14:09.859] [info] File has 6 changed blocks
[2018-03-07 02:14:09.888] [info] Full: 47,451.58 KB, To download: 119.13 KB (0%)
[2018-03-07 02:14:11.998] [info] New version 0.1.11 has been downloaded to /home/user/.config/app/installer-0.1.11.AppImage
[2018-03-07 02:14:12.009] [info] Install on explicit quitAndInstall
[2018-03-07 02:14:12.012] [info] Install: isSilent: false, isRunAfter: true
```
`/home/user/.config/app/installer-0.1.11.AppImage` is moved to `/home/user/installer-0.1.11.AppImage` instead of `/home/user/app.AppImage`.

**Comment by AdrianoFerrari** [comment]
Same here, and I suspect it started when I upgraded electron and electron builder:

From: 
```
"electron": "^1.8.2",
"electron-builder": "^20.0.4",
```
To:
```
"electron": "^2.0.0-beta.4",
"electron-builder": "^20.5.1",
```

**Comment by AdrianoFerrari** [comment]
Probably the changes in this line of `BaseUpdater` are the source of this:
https://github.com/electron-userland/electron-builder/blob/ba4809aeb3bd3b27f66ee684c3e6e8ab0cf55186/packages/electron-updater/src/BaseUpdater.ts#L40

**Comment by SteffenDE** [comment]
I'm not sure if this is fixed correctly yet. Instead of the updated app being named `installer-0.1.11.AppImage` it is now called `app-0.1.11-x86_64.AppImage`, which is still not correct if the AppImage was just named `app.AppImage` before updating it.
While the original AppImage file on the server is actually called `app-0.1.11-x86_64.AppImage`, I usually rename it when installing it on a client machine.
So my original issue

> On the next reboot, the original path doesn't exist any more and the app won't start. Is this expected behaviour?

still applies...

Maybe we could check `process.env.APPIMAGE` to get the correct path of the AppImage file?

**Comment by AdrianoFerrari** [comment]
Confirmed that doesn't seemed to have been fixed correctly yet. I'm back to getting `installer-2.0.8.AppImage` (where `2.0.8` is the new version number). Will see what I can do to fix this properly.

**Comment by SlavkoPekaric** [comment]
Hi, I seem to be running into a similar issue with NSIS, upon download of the update:

Error: ENOENT: no such file or directory, rename 'C:\Users\User\AppData\Roaming\{appId}\**temp-installer-1.0.2.exe**' -> 'C:\Users\User\AppData\Roaming\{appId}\**installer-1.0.2.exe**'

Saw it the code that this is a change from Feb 18th:
https://github.com/electron-userland/electron-builder/commit/ba4809aeb3bd3b27f66ee684c3e6e8ab0cf55186#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Any idea what might be wrong, or how I can go around it?

Using:
Windows 10
electron: 2.0.0
electron-builder: 20.0.4 (tried newer version as well but rolled back to check)

Thanks in advance!
