### ISSUE TITLE
DifferentialDownloader checks for Accept-Ranges but...why?

### ISSUE THREAD

**Issue by meekaah** [electron-userland/electron-builder#2673]
* **Version**: 20.0.8

* **Target**: Windows

The DifferentialDownloader checks the Accept-Ranges header to know if the server supports multiple range requests, and falls back to full download if the header is not present with the following error: Server doesn't support Accept-Ranges

This seems REALLY weird to check the Accept-Ranges header in this case, but to download the embedded blockmap the code doesn't check if the Accept-Ranges header is present or not.

In my case I use Microsoft Azure Blog Storage to host my generic server, it doesn't return the Accept-Ranges header, but it DOES support it (as the download of the embedded blockmap works) but after that it "fails" to download the differential blocks because of the missing header..

**Comment by develar** [comment]
Wel... But why in this case response code is not `206`?

**Comment by develar** [comment]
electron-updater 2.21.1 will include response code into error message to understand.

**Comment by meekaah** [comment]
good question, anyways i thought i should create the issue even though i found a workaround on my end (it might not be the case for everyone). I just set the useMultipleRangeRequest for my azure provider and works fine.

**Comment by meekaah** [comment]
I set the useMultipleRangeRequest for my azure provider and it now works fine. I think i understand the problem, i think azure blob storage doesnt support multiple range requests only one. which is why the download of the blockmap works fine but the differential download doesnt. I think this was a false alert

**Comment by develar** [comment]
Ok, closed for now. "Microsoft" means broken by design and I do not want t waste my time. Feel free to reopen.

**Comment by meekaah** [comment]
yeah and i completely agree... it was just more "convenient" for the company i work at to host this on azure for now..

**Comment by Troldefar** [comment]
@meekaah 

Can you pls help me out? I'm having the exact same issue as you but i have no idea how to solve it, i tried implementing useMultipleRequestRange but says error...

  "build": {
    "appId": "example-electronapplication",
    "productName": "example",
    "win": {
      "certificateFile": "./example/example.pfx",
      "certificatePassword": "",
      "publisherName": "example",
      "asar": false,
      "target": "NSIS",
      "icon": "build/icon.ico",
      "publish": [
        {
          "provider": "generic",
          "url": "https://example.blob.example.windows.net/example/",
          "useMultipleRequestRange": true
        }
      ],
      "appId": "example"
    }
  },

**Comment by Troldefar** [comment]
@meekaah Where did you bring in useMultipleRangeRequest? Can't seem to get it working

**Comment by meekaah** [comment]
@Troldefar under build > publish

**Comment by Troldefar** [comment]
@meekaah still not working, did you set anything up within azure blob storage? or only that one line in package.json ?

**Comment by AbdulMuqtadeer** [comment]
It is not working for me as well. @meekaah Did you make changes in Azure storage blob as well ?

**Comment by develar** [comment]
Anyone can fix method `checkIsRangesSupported` in file `multipleRangeDownloader.ts` to check some another header (Server?) to detect that it is "Microsoft Azure Blog Storage ". And send PR.

**Comment by AbdulMuqtadeer** [comment]
It worked for me after changing the default version of the storage account to latest version. Older version does not support AcceptRange header.

**Comment by z1988hf** [comment]
How to change the default version of the storage account to latest version? @AbdulMuqtadeer
