### ISSUE TITLE
makensis.exe exited with code 1

### ISSUE THREAD

**Issue by GeometricProgress** [electron-userland/electron-builder#2674]
Hi guys

"electron": "^1.8.3",
"electron-builder": "20.4.0",
Running win 10 64bit
Target Windows  build

This project rocks! I have a small problem right at the end of the build. I have deleted the cache and I am using yarn.  build falls down at:

_AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe exited with code 1
Error output:
File: failed creating mmap of "C:\APPS\UfmApp\dist\UfmApp-1.0.0-x64.nsis.7z"
Error in macro extractEmbeddedAppPackage on macroline 18
Error in macro installApplicationFiles on macroline 53
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 146 -- aborting creation process

    at ChildProcess.childProcess.once.code (C:\APPS\UfmApp\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)_

Any help would be appreciated.

Regards

Mark

**Comment by develar** [comment]
What is your windows username? (full path to makensis.exe)

**Comment by GeometricProgress** [comment]
Hi

The full path is:
C:\Users\Mark\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe

It it helps, my package.json is:
`{
  "name": "UfmApp",
  "version": "1.0.0",
  "description": "Understanding the Financial Markets Course",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "win": "electron-builder -w",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "script1": "set CSC_LINK=private/test.p12 && set CSC_KEY_PASSWORD=pass && electron-builder -w",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "appId": "com.gpifm.ufmapp",
    "win": {
      "target": "nsis",
      "icon": "icon.ico",
      "certificateFile": "private/test.p12",
      "verifyUpdateCodeSignature": true,
      "publisherName": "Geometric Progression"
    },
    "nsis": { "oneClick": false, "allowToChangeInstallationDirectory": true, "useZip": true } 
  },
  "devDependencies": {
    "devtron": "^1.4.0",
    "electron": "^1.8.3",
    "electron-builder": "20.4.0",
    "electron-rebuild": "^1.6.0",
    "video.js": "^6.7.4",
    "videojs": "^1.0.0",
    "videojs-playlist": "^4.0.2"
   
  },
  "dependencies": {
    "electron-json-storage": "^4.0.0",
    "electron-window-state": "^4.1.1",
    "node-machine-id": "^1.1.9"
    }
}`

**Comment by develar** [comment]
Please try to remove `useZip`.

**Comment by GeometricProgress** [comment]
Unfortunately, same outcome. Any other ideas?

**Comment by GeometricProgress** [comment]
Ok found problem by elimination.  I have folder of videos in the app which is 4.54Gb which I need to package with the app.  If I run the above config but remove the folder it works.  Is there a limit to the size of folders / app?

**Comment by GeometricProgress** [comment]
I realise it is more appropriate to close this issue and post the above as a separate question.  For anyone following the thread, the above package works; the problem is a folder which exceeds 4.5gb in assets.  It seems to work if the app size is less than 3gb, however I will post this as a question.

Thanks Mark

**Comment by murray971** [comment]
I've got the same issue with video size. did you figure this out?

**Comment by GeometricProgress** [comment]
Try this link. https://github.com/electron-userland/electron-builder/issues/2628#issuecomment-372017626

The above thread works but was not the answer that was suitable for me.  I ended up solving the solution by effectively dividing the program in 2 and calling one program from the other.

**Comment by murray971** [comment]
Thanks- I’ll check it out

**Comment by siikakamania** [comment]
> Ok found problem by elimination. I have folder of videos in the app which is 4.54Gb which I need to package with the app. If I run the above config but remove the folder it works. Is there a limit to the size of folders / app?

Thank you so much man, May Allah gives you blessing for explaining how to fix this, i literally trying my best to solve this problem for the last 72 hours, thank you so much kind stranger for not left anyone hanging on how to fix it🙏🙏🙏
