### ISSUE TITLE
Issue packaging native dependence using asar 

### ISSUE THREAD

**Issue by BiancoA** [electron-userland/electron-builder#2679]
* **Version**:     "electron-builder": "^20.4.1",

* **Target**: Mac Os X

I am trying to package `sharp`. Everything works fine in `dev` mode but if I try to use the result of `yarn dist`, the resulting `.app` does not start. I found that a workaround is to add
```
  "build": {
    "asar": true,
    "asarUnpack": [
      "**/node_modules/sharp/**/*"
    ]
  },
```

to package.json.

I forked electron-builder to do some tests: https://github.com/BiancoA/electron-webpack-quick-start

**Comment by BiancoA** [comment]
I was able to replicate the issue with the code here: https://github.com/BiancoA/electron-webpack-quick-start/blob/master/src/renderer/index.js 

the problem seems to be in the 

```
 for (var i = 0; i < 10; i++) {
          arrayOfPromises.push(sharp(inputImgPath)...
...
```

Am I misusing sharp? should I wait for each promise to complete before initialising a new one?

for the problem with the .asar package i think it may be an issue in electron-builder, so i created an issue here: https://github.com/electron-userland/electron-builder/issues/2679

**Comment by develar** [comment]
sharp depends on `dylib` and so, should be unpacked. I will add `dylib` to auto unpack.

**Comment by tungvn** [comment]
I use Sharp in my electron app and it really unpacks asar. But when the app is packed, the app still uses sharp in app.asar and it makes some errors.
