### ISSUE TITLE
Installer Won't Work On (Some) Windows 7 Machines

### ISSUE THREAD

**Issue by tance77** [electron-userland/electron-builder#2681]
* **Electron-builder Version**: 19.49.0

* **Electron-updater Version**: 2.16.1

* **Microsoft Windows Version** 6.1.7601

* **Target**: NSIS

It seems fairly random, but when trying to run the installer on Windows 7 machines I sometimes get this error.  "Windows 7 and above is required." We have successfully installed other applications that are electron based on the same computer. We have also installed it successfully on other Windows 7 machines. This is a really puzzling error.

Here is a [screenshot](https://imgur.com/a/HjLGL) of the OS Info and The error message.

**Comment by meekaah** [comment]
Can you type "ver" in a command prompt and give us the version returned? This is very strange...

**Comment by tance77** [comment]
@meekaah Sorry for the late reply. Have to go through a chain of communication to get the data, but both users returned: ```Microsoft Windows [Version 6.1.7601]```

**Comment by tance77** [comment]
Any news on this issue?

**Comment by taylorhakes** [comment]
I have the same issue with the same version of Windows. Were you able to resolve it?

**Comment by tance77** [comment]
@taylorhakes It seems to happen a lot on computers that are an illegal copy of windows 7. That is all I was able to surmise though.

**Comment by develar** [comment]
electron-updater 3.4.0

**Comment by jackple** [comment]
Any news on this issue?
