### ISSUE TITLE
Building native production dependencies on Windows issue

### ISSUE THREAD

**Issue by spawnrider** [electron-userland/electron-builder#2683]
* **Version**:
    - Node : 8.9.1
    - NPM : 5.7.1
    - Yarn :  1.5.1
    - electron : 1.8.3
    - electron-builder : 20.4.1
    - electron-rebuild : 1.7.3
    - No Electron-updater used

* **Target**: 

Windows (NSIS)

* **Description**:

I am trying to build an Electron app with Electron-builder in order to create an NSIS installer for Windows using Yarn / npm. 

There is an issue at the step **rebuilding native production dependencies platform=win32 arch=x64** with a native plugin (pcsclite) rebuild using nodegyp. 

Note that the node_gyp build command is running well if I run it separatly (see [nodegyp_build.log](https://github.com/electron-userland/electron-builder/files/1800155/nodegyp_build.log))
I attached the full logs for contextual information.
- [yarn-error_pcsc.log](https://github.com/electron-userland/electron-builder/files/1800147/yarn-error_pcsc.log)
- [yarn_build_output.log](https://github.com/electron-userland/electron-builder/files/1800148/yarn_build_output.log)

* **Full debug output log** : 
[full_debug_log.log](https://github.com/electron-userland/electron-builder/files/1800157/full_debug_log.log)

An idea : It seems to be linked to CPP Warning ....

Thanks a lot for your help.

**Comment by zhouzr** [comment]
I got same problem when building native dependencies of grpc.
