### ISSUE TITLE
Single quote in a product name leads to NSIS failure

### ISSUE THREAD

**Issue by gemma-ferreras** [electron-userland/electron-builder#2686]
Hi everyone!

I am having issues to do the build in windows (mac and linux is working). 

* **Electron-builder version**: 20.4.0
* **Target**: platform=win32 arch=x64

The build falls down at:

[1] npm run build-renderer exited with code 0
  • electron-builder version=20.4.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/electron-builder.yaml
  • installing production dependencies platform=win32 arch=x64 appDir=/Users/local/repos/desktop/app
  • packaging       platform=win32 arch=x64 electron=1.7.5 appOutDir=release/win-unpacked
  • building        target=nsis-web file=release/nsis-web/testing Web Setup 0.6.0.exe archs=x64 oneClick=true
  • building embedded block map file=release/nsis-web/0.6.0-x64.nsis.7z

`Error: /Users/desktop/Library/Caches/electron-builder/nsis/nsis-3.0.1.13/mac/makensis exited with code 1
Error output:
DetailPrint expects 1 parameters, got 3.
Usage: DetailPrint message
Error in macro CHECK_APP_RUNNING on macroline 15
!include: error in script: "uninstaller.nsh" on line 10
Error in script "<stdin>" on line 150 -- aborting creation process

    at ChildProcess.childProcess.once.code (/Users/local/repos/desktop/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)`

[log.txt](https://github.com/electron-userland/electron-builder/files/1802510/log.txt)
[package.txt](https://github.com/electron-userland/electron-builder/files/1810533/package.txt)

Any help would be appreciated.

Thanks

**Comment by develar** [comment]
What's your product name of app?

**Comment by gemma-ferreras** [comment]
@develar it is in the log file. I added all the error. Thanks for checking

**Comment by develar** [comment]
Not a regression. Product name contains `'`.

**Comment by gemma-ferreras** [comment]
@develar I added the package.json so you can check. Thanks
