### ISSUE TITLE
NSIS Installer logging

### ISSUE THREAD

**Issue by alvarezn** [electron-userland/electron-builder#2691]
Hooking into the electron-updater logger i get at the latest 

> Auto install update on quit

at which point either my application comes back with a new version, or it fails and i need to rely on the user to say what happened.

I'm trying to record to a file. Installation version X started, installation version X finished, any errors.  Is there another option that i'm missing?

**Comment by develar** [comment]
The only available logging — electron-updater logs. NSIS doesn't have logging ability.

**Comment by develar** [comment]
dev info: http://nsis.sourceforge.net/Logging:Enable_Logs_Quickly
