### ISSUE TITLE
Question about files/extraFiles/extraResources

### ISSUE THREAD

**Issue by tmchng** [electron-userland/electron-builder#2693]
**version**: 20.4.1

I'm having trouble understanding some problems and restrictions that I ran into with files/extraFiles/extraResources configuration. I've read all possible documentations that I could find, and it still isn't clear to me. Please help me understand.

Assuming the following project structure:
```
project
├── app
│   ├── index.html
│   └── index.js
├── electron
│   ├── main.js
│   ├── pack.js
│   └── package.json
└── package.json
```
`/app` is the application that I wish to release as a web application AND package as an electron app.
`/electron` is a packaging helper project that uses `electron-builder`; it is also the "app root" for `electron-builder`
`/electron/pack.js` is a node script that runs the `electron-builder` api. 

Now the question is, how do I include files from `/app` into the electron app?

1. I read in several places (eg. #597) that the paths should be **"relative to the (electron) project directory".** The term "relative" usually means that I should be able to specify something like `'../app/**/*'` -- this is a valid relative path. However I don't think "relative" means what I think it means in this case. **It seems like "relative" means that the file/directory must be contained within the electron project directory.** Please correct me if I'm wrong.
2. If files must be from within the electron project directory, maybe "relative" is not the most accurate term to use? It is really easy to think that I could specify either relative or absolute path for files/extraFiles/extraResource, but this clearly doesn't work for files outside of the electron project directory.
3. Why can't I use absolute path or relative path that points outside of the electron project? I know nothing about how build-electron works underneath, but I thought we're simply copying files and directories, so I really don't understand why there is such restriction.

NOTE: I discovered the following while I was testing and writing up this issue:

### Relative path will only work if you use `Fileset.from`, and it cannot be a glob pattern

This works
```
files: [
  {from: '../app/', to: '.'}
]
```
This doesn't work (`Fileset` + glob pattern)
```
files: [
  {from: '../app/**/*', to: '.'}
]
```
This doesn't work (relative path without using `Fileset`)
```
files: [
  '../app/'
]
```

I feel this is something that developers should be able to know by reading the documentation, but I had to figure it out through trial and error. Hope this will be useful to others who happen to across the same issue.

**Comment by AdrianoFerrari** [comment]
I've also found that when running with `DEBUG=electron-builder`, only the `FileSet` versions gives us a "file source doesn't exist" warning:
![screenshot_2018-04-28_11-54-05](https://user-images.githubusercontent.com/323678/39398384-e5d6df7c-4ada-11e8-9319-632c484154f0.png)

When using a `String` or `Array String`, **no warning is visible**. Here I ran the same code as above, but with
```
  "build": {
    "appId": "com.gingkoapp.desktop",
    "extraResources": "xyznonsensepath",
...
```
And I don't get a warning:
![screenshot_2018-04-28_11-57-58](https://user-images.githubusercontent.com/323678/39398410-6b44342a-4adb-11e8-8fde-02c36aa1029e.png)

Improving the docs would be important, but I think most people would be able to figure things out if we had warnings when a file isn't found, along with the path it tried.

**Comment by ovsokolov** [comment]
Im trying to understand where eventually this extra resources being installed. I can package extraResources and see them in  dmg file but i don't see this folder anywhere being created on destination machine

**Comment by yoav-shaham** [comment]
I'm pretty sure its being installed in the temp folder while being run

**Comment by shearer12345** [comment]
I would really like to see a warning when use String or Array String and files are missing also.

Is there a way to make electron-builder treat warnings as errors?

**Comment by temoke-levelops** [comment]
It's so frustrating that this isn't in the docs. u_u

**Comment by m4heshd** [comment]
@develar can we add this to the docs?

**Comment by thien-do** [comment]
Thank you for having this issue! It saves me a huge time. Let me try to make a PR for this

**Comment by thien-do** [comment]
Related: https://github.com/electron-userland/electron-builder/issues/1912

**Comment by livthomas** [comment]
I agree that this part of the documentation is not written very well. I spend a lot of time trying to copy a folder. I was only able to copy a single file. But after reading this thread, I realized I can skip the `filter` parameter and then it started working.

**Comment by fstanchina** [comment]
I'm not sure if this is the proper place to write this, so please redirect me elsewhere if necessary.
We were just bitten by a missing `extraResources` file. Someone forgot to compile a small tool, so we released our app without a required piece. We were fully expecting an error and a failed build if a file was missing. Our fault for not checking this before, but this seems like a rather catastrophic bug to me.
Either a file is needed, or it isn't. There's no reason to put a file in `extraResources` if it isn't actually used, so why no error if it's missing? Is there a way to tell the builder a file is necessary?
