### ISSUE TITLE
Do not upload auto-update files for the second configured provider

### ISSUE THREAD

**Issue by IGassmann** [electron-userland/electron-builder#2697]
Autoupdate relies only on the first provider. Thus, there's no need to upload the metadata files for the other configured providers.

It's useful for example when we have GitHub configured as the second provider and we don't want to publish all those metadata files.

**Comment by develar** [comment]
Interesting... In general you are right.

**Comment by IGassmann** [comment]
@develar what are the exceptions? If the first provider is down, will it rely on the secondo one, or that doesn't happen?

**Comment by develar** [comment]
No, but such implementation can be used by some users. That's why I think it is not safe to do it even if I agree that this behaviour should be by default.

**Comment by IGassmann** [comment]
I understand. Another idea would be to give an option to specify what provider we want to use for auto-update:

```
  "publish": [
    {
      "provider": "s3",
      "bucket": "my-bucket",
      "path": "app",
      "region": "us-east-1",
      "autoUpdate": "true" // true by default
    },
    {
      "provider": "github",
      ...
      "autoUpdate": "false"
    }
]
```

**Comment by develar** [comment]
Option added:

```
  /**
   * Whether to publish auto update info files.
   *
   * Auto update relies only on the first provider in the list (you can specify several publishers).
   * Thus, probably, there`s no need to upload the metadata files for the other configured providers. But by default will be uploaded.
   *
   * @default true
   */
  readonly publishAutoUpdate?: boolean

```

to `PublishConfiguration`.

i.e. as you have suggested, but `publishAutoUpdate instead of `autoUpdate`. Feel free to discuss the option name.
