### ISSUE TITLE
__stacit is not defined 

### ISSUE THREAD

**Issue by silentpride** [electron-userland/electron-builder#2698]
Hello there !
when I run dev, everything is OK.
But, when I run build and run the project, err occurred :
【A JavaScript error occurred in the main process】
【Uncaught Exception: ReferenceError: __stacic is not defined】

In [main.js], my code is like this:
/**
Set __static path to static files in production
https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-static-assets.html
*/
if (process.env.NODE_ENV !== 'development') {
global.__static = require('path')
.join(__dirname, '/static')
.replace(/\/g, '\\')
}
let iconPath = path.join(__static, 'icon.png')
let transparentIconPath = path.join(__static, 'transparent_icon.png')

Any suggestion ?
THX

**Comment by stefan-ysh** [comment]
Hi～

 Have you solved this problem？could you give me any suggestion？

Thanks

**Comment by silentpride** [comment]
> Hi～
> 
> Have you solved this problem？could you give me any suggestion？
> 
> Thanks

Time has passed so long. I can't remember detail.
I just remember i moved this code later ,  things went right.
