### ISSUE TITLE
Packaging app for platform too slow, 

### ISSUE THREAD

**Issue by Luncher** [electron-userland/electron-builder#270]
my application File size:

[luncher@localhost release-test]$ ls
app  build  dist  node_modules  package.json
[luncher@localhost release-test]$ du -sh ./*
108M	./app
420K	./build
423M	./dist
170M	./node_modules
4.0K	./package.json
[luncher@localhost release-test]$ 

my build options:
 "build": {
    "asar": false,
    "app-bundle-id": "hr.creaticon.eatodo",
    "app-category-type": "public.app-category.productivity",
    "iconUrl": "http://eatodo.s3.amazonaws.com/icon.ico"
  },

**Comment by develar** [comment]
Please specify target platform. See https://github.com/electron-userland/electron-builder/issues/181#issuecomment-189145205

**Comment by Luncher** [comment]
"scripts": {
    "dist": "npm run dist:osx && npm run dist:win",
    "dist:osx": "build --platform darwin -d",
    "dist:win": "build --platform win32 -d"
  },

I've specified version：
npm run dist:win

**Comment by Luncher** [comment]
When I specified asar equal to false, too slow~

**Comment by develar** [comment]
Slow — what is your target and host OS? Without asar is ok? CPU, RAM? Please provide exact timing — use time command.

**Comment by Luncher** [comment]
**Without asar is ok.**

[luncher@localhost SingleIDEServer]$ uname -a
Linux localhost.localdomain 3.17.4-301.fc21.x86_64 #1 SMP Thu Nov 27 19:09:10 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

--- 

[luncher@localhost SingleIDEServer]$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
stepping	: 3
microcode	: 0x1c
cpu MHz		: 1086.617
cache size	: 3072 KB

---

I am waiting for the end of time command

Removing /data/SingleIDEServer/build/release-test/dist/win-x64
Packaging app for platform win32 x64 using electron v0.37.2

**Comment by Luncher** [comment]
Packaging app for platform win32 x64 using electron v0.37.2

real	108m29.333s
user	197m33.096s
sys	17m57.266s
[luncher@localhost release-test]$

**Comment by Luncher** [comment]
Who can help me check why? Thank you

**Comment by develar** [comment]
I, but I will have time only on weekend. It is interesting why `asar=false` is slow, but default `asar=true` not. Why you cannot use `asar`?

**Comment by develar** [comment]
Anyway, consider to use https://www.appveyor.com to build win aritfact (see https://github.com/electron-userland/electron-builder/blob/master/docs/multi-platform-build.md).

**Comment by Luncher** [comment]
Because I have to modify the app folder inside the file,

**Comment by Luncher** [comment]
Thank you :+1:

**Comment by Luncher** [comment]
Ask a question. 

`extra Resources` option whether to extract out of resources from app.asar

**Comment by develar** [comment]
> `extraResources` option whether to extract out of resources from app.asar

No. Copied separately. Not in the asar in any case.

**Comment by Luncher** [comment]
What other way to extract the rar files?

**Comment by Luncher** [comment]
Why do I use mac computer to compile windows installer is very slow. . .

**Comment by Luncher** [comment]
There are other ways you can see the log information?

**Comment by develar** [comment]
Set `DEBUG` env to `*’

**Comment by develar** [comment]
@Luncher `electron-winstaller-fixed 2.0.6-beta.6` published, please try `npm update` and build.

**Comment by Luncher** [comment]
When I upgraded version of the compiler prompt an error:

---

Packaging app for platform linux x64 using electron v0.37.4
Error: Please specify project homepage
    at LinuxPackager.<anonymous> (/data/LocalHolaStudio/release/node_modules/electron-builder/src/linuxPackager.ts:178:13)
    at [object Generator].next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at tsAwaiter (/data/LocalHolaStudio/release/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/data/LocalHolaStudio/release/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/data/LocalHolaStudio/release/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

---  

dev json: 

  "license": "ISC",
  "devDependencies": {
    "electron-builder": "^3.2.0",
    "electron-prebuilt": "^0.37.4"
  },
  "build": {
    "asar": false,
    "iconUrl": "http://7xsec6.com1.z0.glb.clouddn.com/icon.ico",
    "app-bundle-id": "holaverse.studio",
    "app-category-type": "public.app-category.productivity",
    "osx": {
      "title": "HolaStudio",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    }
  }

**Comment by develar** [comment]
Linux requires `homepage` now because it is important for Ubuntu Software Center (see https://github.com/electron-userland/electron-builder/blob/master/docs/options.md#user-content-#DevMetadata-homepage)

**Comment by Luncher** [comment]
thank you man。How do I build Linux Package URL? I have not put the project on github.

**Comment by develar** [comment]
@Luncher Does you project have public project page?

**Comment by Luncher** [comment]
Have a website, you see, write directly to this site can it?
[HolaStudio](http://studio.holaverse.com)

**Comment by develar** [comment]
@Luncher Yes. Any URL is accepted. You can specify your company or product web site. `Developer Web site` (https://wiki.ubuntu.com/SoftwareCenter).

**Comment by Luncher** [comment]
thank you.

**Comment by Luncher** [comment]
`chore: update NuGet to 3 `

Seems to not work, I have built a windows compiler environment

**Comment by Luncher** [comment]
How to set linux installation package icon it? After the update version of the icon disappeared. The build application json option to move to the developer json.

**Comment by develar** [comment]
> Seems to not work, I have built a windows compiler environment

Sorry, don't understand. It is slow, or error was thrown?

> How to set linux installation package icon it? After the update version of the icon disappeared.

Do you mean that you upgrade electron-builder version from 2 to 3 and no more Linux icon? Or did you use 3.x before, but after `npm update` linux icon is not correctly applied?

**Comment by Luncher** [comment]
another question，my dev package.json:

---

  "scripts": {
    "dist": "npm run dist:linux && npm run dist:win",
    "dist:osx": "build --platform darwin -d",
    "dist:win": "build --platform win32 -d",
    "dist:linux": "build --platform linux -d"
  },

---

-d What does it mean?

**Comment by develar** [comment]
> -d What does it mean?

`--dist` "to package in a distributable format (e.g. DMG, windows installer, NuGet package)" You don't need to pass it because your script name has prefix `dist:`.

**Comment by Luncher** [comment]
When I run:

[luncher@localhost release]$ npm run dist:linux

> HolaStudio@0.0.1 dist:linux /data/LocalHolaStudio/release
> build --platform linux --arch all -d

Installing app dependencies for arch ia32 to /data/LocalHolaStudio/release/app
----------------------------------------------------
Reading icns family from /data/LocalHolaStudio/release/build/icon.icns...
 Extracting icons from /icon.icns...
  Saved 'is32' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_16x16x32.png.
  Saved 'il32' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_32x32x32.png.
  Saved 'ih32' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_48x48x32.png.
  Saved 'it32' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_128x128x32.png.
  Saved 'ic08' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_256x256x32.png.
  Saved 'ic09' element to /tmp/electron-builder-24640n5k0r9R0yYIi/icon_512x512x32.png.
Extracted 6 images from /icon.icns.

--- 
my icons:

[luncher@localhost build]$ ls
background.png  icon.icns  icon.ico
[luncher@localhost build]$ pwd
/data/LocalHolaStudio/release/build
[luncher@localhost build]$ 

---  

I watched electron packager help documentation.:

icon - String

Currently you must look for conversion tools in order to supply an icon in the format required by the platform:

OS X: .icns
Windows: .ico (See below for details on non-Windows platforms)
Linux: this option is not required, as the dock/window list icon is set via the icon option in the BrowserWindow constructor. Setting the icon in the file manager is not currently supported.

I do not know how to set the app icon for linux platform

**Comment by develar** [comment]
> I do not know how to set the app icon for linux platform

electron-builder does it. If it doesn't work, it is a regression. I will check.

**Comment by Luncher** [comment]
thank you

**Comment by develar** [comment]
@Luncher Cannot confirm Linux icon bug. Please file separate issue (and provide details — "the icon disappeared" — where icon is missed?).

**Comment by develar** [comment]
@Luncher Your answer about NuGet 3 is important, please try it and report how does it work for you (if doesn't work, don't forget to attach debug log).

**Comment by Luncher** [comment]
I compiled a problem in the mac platform. Will the mac system log file where to see it?I compiled a

**Comment by Luncher** [comment]
I installed dmg file, double-click the apk file, the system prompts can not be opened

**Comment by develar** [comment]
@Luncher `DEBUG=electron-windows-installer:* npm run dist -- --platform win32` (correct npm script name — in your case may be `dist:win`).

**Comment by Luncher** [comment]
My first question is in the translation of the mac system files can not be installed and turned on. You can help to look at this issue.

**Comment by Luncher** [comment]
Do you know the log file is?

**Comment by develar** [comment]
@Luncher Please don't mix several questions in one issue. Please file another issue.

**Comment by Luncher** [comment]
ok

**Comment by develar** [comment]
https://github.com/electron/windows-installer/issues/55
