### ISSUE TITLE
checkForUpdatesAndNotify updates but does not notify on Windows 10

### ISSUE THREAD

**Issue by forman** [electron-userland/electron-builder#2700]
**electron-builder**: 19.56.0
**electron-updater**: 2.20.1
**electron**: 1.8.2
**node**: 8.9.4
**npm**: 5.6.0

**Target**: Windows 10

First of all, thanks so much for this great tool! It is helping us a lot.

My problem is that `autoUpdater.checkForUpdatesAndNotify()` updates perfectly but does not notify on Windows 10. On Mac I get the expected toast when the update is available.

The project is [cate-desktop](https://github.com/CCI-Tools/cate-desktop) which uses a two-package.json structure.

**Comment by forman** [comment]
Could be related to https://github.com/electron/electron/issues/10864

**Comment by marceloavf** [comment]
Me neither, try all solutions in https://github.com/electron/electron/issues/10864 but doesn't work, seems to be windows problem.

**Comment by marceloavf** [comment]
@forman I get it working again by setting Notification on import, setting model ID and default protocol:
```js
import { Notification } from "electron"

app.setAppUserModelId("com.xxxx.xxxx");
app.setAsDefaultProtocolClient('xxxxx');
```

**Comment by forman** [comment]
@marceloavf Great, thanks! 

However, even after reading the `electron` API docs, I have no clue what arguments to pass to that API.

Where does the ID passed to `setAppUserModelId` come from? Am I free to choose? Or is it generated and must be registered in the OS or with Microsoft, e.g. by the installer of the app? 

Also, could you given me a hint what protocol to pass to  `setAsDefaultProtocolClient` that would enable the update notifications. 

Thanks again!

**Comment by marceloavf** [comment]
@forman According to [Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459%28v=vs.85%29.aspx), AppUserModelId is defined with this base form `CompanyName.ProductName.SubProduct.VersionInformation` while the SubProduct and VersionInformation portions are optional.

Seems that if two apps set the same `AppUserModelId` it change some internal ID and if also sets the same `ProtocolClient` it opens a select menu.

I used to write it like this: `com.companyName.softwareName`, the `ProtocolClient` is just a shortcut to open your software with a command, I constantly use my company name summarized with the software name, for example: `ps-softwarename`.

**Comment by forman** [comment]
@marceloavf Thanks, again. I will try it now.

**Comment by Praveer1981** [comment]
> Important to note here, that just calling `setAppUserModelId` is not enough, the string that you set there needs to match `build.appId` in your `package.json` (at least that's how I got it to work).
@tzachshabtay  :
https://docs.microsoft.com/en-us/windows/win32/shell/appids?redirectedfrom=MSDN
