### ISSUE TITLE
Install spinner GIF issue

### ISSUE THREAD

**Issue by johanpoirier** [electron-userland/electron-builder#2704]
* **Version**: 20.5.1

* **Target**: Squirrel.Windows

The display of the `install-spinner.gif` is slightly broken during the install process on windows. The transparency is removed and the gif is resized. What has changed since the 19.20.0 version?

Thanks.

**Comment by rcorredera** [comment]
The problem appears on version 19.43.0 of electron-builder-squirrel-windows.

**Comment by develar** [comment]
Duplicates  #2543
