### ISSUE TITLE
Error: spawn npm ENOENT issue on Windows

### ISSUE THREAD

**Issue by ykim** [electron-userland/electron-builder#271]
I've installed electron-build (3.1.1) on Windows 8.1 and Windows 10 to be able to code-sign my application in Windows, but I keep on encountering this issue:

```
Installing app dependencies for arch ia32 to C:\Users\IEUser\Desktop\client\app
Error: spawn npm ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
```

After modifying the util.ts file to use "npm.cmd" instead of "npm", it looks like it runs now.

**Comment by havenchyk** [comment]
@ykim could you please provide your configs(package.json)? PR is welcome.

**Comment by develar** [comment]
@havenchyk problem not in the config, but in the environment. For some reason, npm location is not detected and we use just `npm` as fallback.

**Comment by ykim** [comment]
@develar What do you think is a good solution? A simple one I could suggest is to check the platform and switch from "npm" to "npm.cmd" if you're on Windows.

**Comment by develar** [comment]
@ykim if you get error as part of npm run script — npm run dist, not as part of direct call executable `build` — env must contain all required information, so, the question why error happens in this case. 

I don't want just specify shell: true for Windows if cause of error is not clear.

**Comment by kkapron** [comment]
@ykim I had the same problem on Windows 7. Modifying the util.ts file works, but I think that the cleaner way to handle this issue for now is to export environment variable. In my project (I'm using electron-builder in programmatic way) I just did:
`process.env.npm_execpath - "C:\\Program Files\\nodejs\\node_modules\\npm";`

**Comment by develar** [comment]
@kkapron How did you run — npm run * or direct call executable?

**Comment by kkapron** [comment]
@develar This is my example (I omitted unnecessary code):

I needed some other enhancements, so in my project I created my own class:
```
const packager = require('electron-builder/out/packager');

class ElectronPackager extends packager.Packager {
  // some code...
}

module.exports = ElectronPackager;
```

Then I use it in my gulpfile
```
var ElectronPackager   = require('./gulp/ElectronPackager');

gulp.task('electron-build', function(done) {
  if (process.platform === 'win32' && !process.env.npm_execpath) {
    process.env.npm_execpath = "C:\\Program Files\\nodejs\\node_modules\\npm";
  }
  var packager = new ElectronPackager({
    // some options...
  });
  packager.build()
    .then(function(){ done(); })
    .catch(function(err){ done(err); });
});
```
And then just in terminal:
`gulp electron-build`

:smile:

**Comment by develar** [comment]
@kkapron Thanks. Will be fixed soon.

> I needed some other enhancements

it will be cool to discuss about it — it will be easy you if your changes will be in upstream ;)

**Comment by kkapron** [comment]
@develar Great!
> it will be cool to discuss about it — it will be easy you if your changes will be in upstream ;)

Now the most important for me is to have configurable output directory and I see that you already have it on your issues list #272. It was faster for me to write the class extension than refactor my application structures to achieve this. :smile:

**Comment by develar** [comment]
@kkapron #272 fixed. Anything else?
