### ISSUE TITLE
Set Publisher/Developer in app

### ISSUE THREAD

**Issue by amaurymartiny** [electron-userland/electron-builder#2710]
* **Version**: 20.2.0

* **Target**: Windows, Mac and Linux

I had a look at the docs at electron.build, but I couldn't find my answer. I built the app with electron-builder on all platforms, but I cannot get the correct developer/publisher in the packaged app:
- On windows, the publisher is undefined
- On mac, I get a warning for unidentified developer
- On linux, `snap list` shows an empty cell in the Developer column for my app

I put the `author` field in my package.json like this:
```json
  "author": {
    "name": "My Company",
    "email": "admin@company.io"
  },
```

Is app signing required? On all three platforms?

**Comment by IGassmann** [comment]
For Windows and macOS you need to sign your app for getting the correct developer/publisher in the packaged app.
