### ISSUE TITLE
Is there a way to bake in the --inspect flag?

### ISSUE THREAD

**Issue by philippefutureboy** [electron-userland/electron-builder#2712]
* **Version**: 20.5.1
* **Target**: W7

Hey there!

I was wondering, is there a way to enable the --inspect flag for the main process of the packaged electron app? I read through the configuration docs and couldn't find anything related to that. I would like to do some performance analysis on a certain function and having access to the devtools would greatly help :)

Thanks again for your wonderful work!

Keep it up ✨

**Comment by philippefutureboy** [comment]
Lol came back here without remembering I posted this a month ago.

Would be a wonderful feature <3

**Comment by develar** [comment]
Not possible because we don't introduce any wrapper for your electron app.

> having access to the devtools would greatly help :)

https://github.com/sindresorhus/electron-debug

app.commandLine.appendSwitch(.., ...) if you want for renderer process.

**Comment by philippefutureboy** [comment]
Thanks for your answer @develar!

If the feasibility ever changes, let me know ✨
