### ISSUE TITLE
Update silent mode configuration

### ISSUE THREAD

**Issue by vshymanskyy** [electron-userland/electron-builder#2714]
* **Version**: 19.56.0

* **Target**: Windows, NSIS

Currently, the "on-exit" updater always runs in silent mode.
It would be cool to have this configurable somehow.

Thanks!

https://github.com/electron-userland/electron-builder/blob/ba4809aeb3bd3b27f66ee684c3e6e8ab0cf55186/packages/electron-updater/src/BaseUpdater.ts#L138

**Comment by fridgerator** [comment]
💯 👍  ⬆️ 

There are obviously issues if a user tries re-opening the application while the silent install is happening.

Would be great if this option was also added to `checkForUpdatesAndNotify`

**Comment by fridgerator** [comment]
I can see this is going to require more work than just adding some options.  The AppImage updater looks like its just `mv -f` from one folder to another.  Changing the [`APPIMAGE_SILENT_INSTALL`](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppImageUpdater.ts#L108) environment variable does nothing.

I didnt look into the NSIS updater.

**Comment by vshymanskyy** [comment]
Why is this obsolete? Are there any changes?

**Comment by develar** [comment]
A bunch of changes were done recently in this area. Please check latest version.

**Comment by develar** [comment]
I don't want to complicate.

Set `autoUpdater.autoInstallOnAppQuit` to `false` and add own `quit` app handler if you want to customize this behaviour.

Yeach, probably we should introduce `autoQuitOptions` but... for now I don't have time to think how to do it properly and keep API clean and clear. Feel free to open PR.
