### ISSUE TITLE
app.asar can't find my index.html，how can I do ？

### ISSUE THREAD

**Issue by Picktarget** [electron-userland/electron-builder#2716]
I just use angular 5 with electron，I can run it correvtly when I excuted  “npm run ele-dev” in Development ，but after I excute “npm run dist” to package ,it produces *.exe. then I click the excutable file ,it tells me 
![qq 20180320112737](https://user-images.githubusercontent.com/12743709/37634486-b822d314-2c31-11e8-90f7-6e1061bd7aea.png)
I just have single package.json
here is my project strcture and package.json
![qq 20180320112339](https://user-images.githubusercontent.com/12743709/37634403-4a66f6a2-2c31-11e8-84f8-1dd9b604dcb0.png)

then this is my main.js
![qq 20180320112837](https://user-images.githubusercontent.com/12743709/37634515-da46df80-2c31-11e8-8d10-228682bef4fd.png)

what should I do to solve this problem!

**Comment by zankooh** [comment]
Did you find a solution to this problem?
