### ISSUE TITLE
how to disable install updates when the app in normal quit?

### ISSUE THREAD

**Issue by vegawong** [electron-userland/electron-builder#2717]
* **Version**: 
electron-builder: 20.0.8

electron-updater: 2.21.1

* **Target**: win --ia32 nsis

here is my updater event setting 
```javascript
 autoUpdater.on('checking-for-update', () => {
            this.sendStatusToWindow('Checking for update...')
        })
        autoUpdater.on('update-available', (ev, info) => {
            this.sendStatusToWindow('Update available.')
        })
        autoUpdater.on('update-not-available', (ev, info) => {
            this.sendStatusToWindow('Update not available.')
        })
        autoUpdater.on('error', (ev, err) => {
            this.sendStatusToWindow('Error in auto-updater.')
        })
        autoUpdater.on('download-progress', (ev, progressObj) => {
            this.sendStatusToWindow('Download progress...')
        })
        autoUpdater.on('update-downloaded', (ev, info) => {
            this.sendStatusToWindow('downloaded')
        })
```

and then i provide a notice UI in renderer UI View include a button to click for update;

it sends an event to call `autoUpdater.quitAndInstall` via the ipc;

such as 
```javascript
 ipcMain.on('autoupdate-message', (event, arg) => {
            switch (arg) {
                case 'installUpdate':
                    updater.quitAndInstall()
                    break
                case 'check':
                    updater.checkUpdate()
                    break
                default:
                    break
            }
        })
```

then it works; but...
when i get the notice message as `restart to install updates`, and i want to ignore it;
it also run install updates when i does as normal quite. it always run...
is there some options to disable `force install update when app quit`?
how can i resolve it?

**Comment by MariaDima** [comment]
Maybe this helps:
https://github.com/electron-userland/electron-builder/issues/2493

"electron-updater 2.20.0 — set autoInstallOnAppQuit to false."

**Comment by rohanrk-tricon** [comment]
@vegawong Can you please tell me how you achieved "renderer UI View include a button to click for update"? 
autoUpdater.on('update-downloaded', (info) => {` 
ipcMain.on('autoupdate-message', (event, arg) => {
            switch (arg) {
                case 'installUpdate':
                    updater.quitAndInstall()
                    break
                case 'check':
                    updater.checkUpdate()
                    break
                default:
                    break
            }
        })
        });`
        
and inside renderer
`  window.electron.ipcRenderer.once('autoupdate-message', (arg) => {
    // eslint-disable-next-line no-console
    console.log(arg);
    navigate(MESSAGE_SCREEN);
    window.electron.ipcRenderer.sendMessage('autoupdate-message', [
      'installUpdate',
    ]);
  });`
  Now no need to click any button, I am just routing to MESSAGE_SCREEN and then sending installUpdate back to ipc. This is how I am doing. Please let me know where I am going wrong.
