### ISSUE TITLE
Package MAS error

### ISSUE THREAD

**Issue by mulyk** [electron-userland/electron-builder#2719]
* **electron-builder**: 20.6.2
* **electron**: 2.0.0-beta.4
* **target**: mas

Hello
When I download the package to the Itunes I get an error:
`ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'com.github.electron.loginhelper' of 'com.my.app/Contents/Library/LoginItems/Electron Login Helper.app' is already in use by another application."`

**Comment by countravioli** [comment]
I just did my first submission to the App Store through Application Loader and I got that same error back from iTunes connect. Not sure if I'm building wrong or something is borked so just chiming in here too.

* electron-builder: 20.8.2
* electron: 2.0.0-beta.7
* target: mas

**Comment by sferoze** [comment]
@mulyk did you find any resolution to this?

**Comment by dbtek** [comment]
I am also suffering from this issue. Any solution / workaround?

**Comment by sferoze** [comment]
@dbtek Go to the .app, right click and show package contents. 

Then go to `my.app/Contents/Library/LoginItems/` and just delete `Electron Login Helper.app`

That worked for me

**Comment by dbtek** [comment]
@sferoze thanks for the reply. I am using electron-builder. I can just do that however Application Loader only accepts .pkg. I don't know how to I modify .pkg.

**Comment by sferoze** [comment]
@dbtek Ah yah, you have to output the .app file from electron-builder. I think it outputs that along with the .pkg. 

So edit the .app file and then you will have to re-package the .app file. Quick google search will show you how to do that.

**Comment by mulyk** [comment]
@dbtek, I modified the function createMacApp in builder script node_modules/electron-builder-lib/out/electron
Here are the necessary changes: [https://github.com/mulyk/test/commit/f92a55a2f33155c8842f2808d475e5d527f0d7b8](url)
This only works for the Mas target, for the rest the Login Helper is not supplied and the script will give an error, you need to use the standard or add condition

**Comment by dbtek** [comment]
Thanks @mulyk. I'll try.

**Comment by dbtek** [comment]
It seems crash is unrelated to patch. It crashes without it too. (On 20.11.1)

**Comment by mulyk** [comment]
@dbtek Yes, the package for mas doesn't run from the file, only from the store

**Comment by dbtek** [comment]
@mulyk, sorry for the level of noobness. Apple rejected binary stating "App crashes on launch".
Is there anyway to repeat it locally with MAS build.

**Comment by tschellenbach** [comment]
* electron-builder: 20.13.3
* electron: 2.0.0
* target: mas

Still has this problem.

**Comment by develar** [comment]
@mulyk Why not prepare PR :(

**Comment by develar** [comment]
Will be fixed, sorry for delay.

**Comment by countravioli** [comment]
I'm running into this issue still. If I'm reading things @develar 's fix should be in the current version. I'm on **20.26.1** and electron **2.0.5** trying to build mas. Getting this error from Apple's Application Loader.

ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'com.github.electron.helper' of '<MY APP>.app/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app' is already in use by another application."

**Comment by juandavidcruzs** [comment]
Hello 👋

"electron-builder": "20.28.4"
"target": "mas"

When I upload to AppStore Connect I get this error: `Error: CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'org.phantomjs' of 'phantomjs' is already in use by another application.`

Any new workarounds?
