### ISSUE TITLE
Ability to customize the output directory

### ISSUE THREAD

**Issue by michaelbazos** [electron-userland/electron-builder#272]
Is there any possibility to customize the output directory, i.e. to write in another folder than `dist`?

**Comment by Vj3k0** [comment]
It's possible for Windows. In your root package.json:
```
"build": {
    "osx": {
      ...
    }
    "win": {
      "outputDirectory": "release"
    }
}
```
Note: `release` directory is in relative to your root directory (where your package.json is).

The problem here is that `electron-builder` expects it to be in dist and it will try to move files around and will cause error.

**Comment by develar** [comment]
Not yet. Will be implemented on weekends.
