### ISSUE TITLE
Split build and package steps

### ISSUE THREAD

**Issue by eanders-MS** [electron-userland/electron-builder#2724]
* **Version**: 20.2.0

* **Target**: OSX ("dmg", "zip"), Windows ("squirrel", "nsis"), Linux ("deb", "AppImage")

This is more a question than an issue... We're using electron-builder to build and package our app. We call electron-builder from a gulp task like this:
```js
  builder.build({
    targets: builder.Platform.MAC.createTarget(["dmg", "zip"]),
    config
  });
```

We want to split building and packaging into two distinct steps so that we can sign the built files in a separate step that occurs externally. Is this possible in the current API? It might look something like this:

##### Step 1: Build
```js
  // Output of this step is the unpacked folder (contains unsigned binaries)
  builder.build({
    config
  });
```
##### Step 2: Sign
```
Upload files to Signing Service. We get them back at some point in the future.
```
##### Step 3: Package
```js
  // Input to this step is the unpacked folder (or in our case, a copy of it containing the now-signed binaries)
  // Output of this step is the packaged app (dmg, zip, etc.)
  builder.package({
    targets: builder.Platform.MAC.createTarget(["dmg", "zip"]),
    config
  });
```
I'm perusing the documentation and sources to see how it can be accomplished, but thought I'd ask here too.

Thank you.

**Comment by eanders-MS** [comment]
This was pretty simple, it turns out. Here's my solution in case it benefits others.

##### Step 1: Build
```js
  // Build the 'dir' target for the platform
  builder.build({
    targets: builder.Platform.MAC.createTarget(["dir"]),
    config
  });
```

##### Step 3: Package
```js
  // This time, specify the redistributable formats you want built (dmg and zip in this case).
  // Additional argument: 'prepackaged'. Set to the 'dir' target's output folder from Step 1.
  builder.build({
    targets: builder.Platform.MAC.createTarget(["dmg", "zip"]),
    config,
    prepackaged: 'path/to/dir/output'
  });
```

**Comment by eanders-MS** [comment]
@develar A few details about building prepackages I wanted to ask you:
- I noticed something: Whereas Linux and Windows append `-unpacked` to their staging folders, the mac build just outputs to a folder named `mac`, then building the `dir` target. Why not `mac-unpacked`?
- I'm curious how the NSIS build works in the prepackaged scenario. I can only specify one prepackaged folder to the build configuration, but NSIS packages both 32-bit and 64-bit builds into a single installer. Does it not need access to both the `win-unpacked` and `win-ia32-unpacked` folders?

**Comment by develar** [comment]
@eanders-MS 

> Why not mac-unpacked?

Because macOS app bundle it is a directory named as your app. We cannot place "MyAwesomeApp.app` into `dist` directory, because there is already target for MAS (Apple Store).


> how the NSIS build works in the prepackaged scenario

Yes, that's is the problem. NSIS in this case support only one arch.

**Comment by eanders-MS** [comment]
@develar I have need to split up the different phases of electron-builder's build process, so that building the installer can happen separately, as a distinct step from the phase that produces the "unpacked" folders. At the same time, I need to be able to utilize NSIS's multi-architecture bundling capability. This is needed so that I can send the executable off for signing, then build the installer once the exes are signed (and then sign the installer itself, but that's not a problem).

The build steps would look like:
1. electron-builder: generate the unpacked folder(s)
2. external: Executables in these folders are shipped off for signing.
3. external: At some point, we get the signed files back.
4. electron-builder: create the installer.

Is this possible to do with what's available today?

**Comment by develar** [comment]
@eanders-MS 

> Is this possible to do with what's available today?

Yes. External code signing is supported for Windows — https://www.electron.build/configuration/win
