### ISSUE TITLE
Windows: Desktop/start menu shortcut not recreated on reinstall 

### ISSUE THREAD

**Issue by tzarebczan** [electron-userland/electron-builder#2725]
* **Version**: 
electron-builder: 20.5.1

Electron updater: electron-updater: 2.21.0

* **Target**: Windows, Linux, OSX

If a desktop shortcut is removed, it is not re-created if re-running the installer. If uninstalled and then reinstalled, shortcut is created again. 

Steps:
1) Install https://github.com/lbryio/lbry-app/releases/tag/v0.21.1-rc.4
2) Remove desktop shortcut
3) Run installer again

Fix:
4) Uninstall LBRY
5) Run installer again
6) Desktop shortcut created.

**Comment by tzarebczan** [comment]
@develar did you have a chance to look at this? We are hoping to ship an app update tomorrow and this may affect some of our users. If it's a quick/obvious fix, would love to get it taken care of. I've donated a few bucks to the issue :p

**Comment by develar** [comment]
"tomorrow" depends on your time zone. Are you in CET?

**Comment by develar** [comment]
Because issue donated, I will take a look now. But as far I see — it is expected behaviour — if user decided to remove shortcut, installer doesn't attempt to create it again. Why this behaviour is not good for you?

**Comment by tzarebczan** [comment]
EST, was hoping to release tomorrow AM. 

It's mostly an issue because we are migrating from a 32bit build to 64 bit (installs to a different directory) - some old users may run the 32bit uninstaller later on which removes the shortcuts from the 64 bit install. Simply re-running the 64 bit installer doesn't fix it, they'd need to uninstall and reinstall. 

I would think that re-installing an existing build or uninstalling/installing would produce the same result - desktop/shortcut icon creation.

**Comment by develar** [comment]
Set `createDesktopShortcut` to `always`.

```json
"nsis": {
      "createDesktopShortcut": "always"
    }
```


` Whether to create desktop shortcut. Set to `always` if to recreate also on reinstall (even if removed by user).`

Not applicable if updated — on auto-update shortcut will be not recreated.

> I would think that re-installing an existing build or uninstalling/installing would produce the same result - desktop/shortcut icon creation.

Seems logical for me too, but for now it will be not default. Too dangerous and too sensitive area.

20.7.0 — will be released for you in 5-10 minutes.

**Comment by tzarebczan** [comment]
@develar thank you so much for the prompt response and fix for this!

**Comment by develar** [comment]
update: version `20.6.2`.

**Comment by tzarebczan** [comment]
@devlar when should we expect the release to be up on https://github.com/electron-userland/electron-builder/releases?

**Comment by tzarebczan** [comment]
@devlar any update?

**Comment by develar** [comment]
@tzarebczan 20.6.2 released specially for you and I don't have time to announce release for all users since I need to polish other (not required for you) things. Just set version to `20.6.2` in the package.json

**Comment by tzarebczan** [comment]
@develar whoops, now I understand, thanks! (and I mistagged you while on mobile)

**Comment by tzarebczan** [comment]
@develar seeing this:
```
Extracted all strings!
  • electron-builder version=20.6.2
  • loaded configuration file=C:\Users\SoloDolo\Desktop\new2\lbry-app\electron-builder.json
  • loaded parent configuration file=C:\Users\SoloDolo\Desktop\new2\lbry-app\node_modules\electron-webpack\electron-builder.yml
Error: Configuration is invalid.
 - configuration.nsis should be one of these:
   object { allowElevation?, allowToChangeInstallationDirectory?, artifactName?, createDesktopShortcut?, createStartMenuShortcut?, deleteAppDataOnUninstall?, differentialPackage?, displayLanguageSelector?, guid?, include?, installerHeader?, installerHeaderIcon?, installerIcon?, installerLanguages?, installerSidebar?, language?, license?, menuCategory?, multiLanguageInstaller?, oneClick?, packElevateHelper?, perMachine?, preCompressedFileExtensions?, publish?, runAfterFinish?, script?, shortcutName?, unicode?, uninstallDisplayName?, uninstallerIcon?, uninstallerSidebar?, useZip?, warningsAsErrors? } | {
     "type": "null"
   }
   Details:
    * configuration.nsis.createDesktopShortcut should be a boolean.
    * configuration.nsis should be null:
      {
```

**Comment by develar** [comment]
@tzarebczan Please try 20.7.1

**Comment by tzarebczan** [comment]
@develar that worked! Will do some more testing later on, but I think it re-creates the desktop icon. It doesn't, however, re-create the shortcut in C:\ProgramData\Microsoft\Windows\Start Menu\Programs. Good thing is that it still finds the program when searching it from the startmenu because of the desktop icon

**Comment by Araxeus** [comment]
Why is this issue closed?
this is still happening..

>  it re-creates the desktop icon. It doesn't, however, re-create the shortcut in C:\ProgramData\Microsoft\Windows\Start Menu\Programs.
