### ISSUE TITLE
Why is there a releaseDate?

### ISSUE THREAD

**Issue by mkarp** [electron-userland/electron-builder#2727]
* **Versions:**

```
"electron-builder": "20.5.1",
"electron-packager": "^11.1.0",
"electron-publisher-s3": "^20.5.0",
```

* **Target:** macOS

When publishing a build with a command:

```
electron-builder --publish always -c.releaseInfo.releaseDate="2018-03-21T00:00:00.000Z"
```

the generated `electron-builder.yaml` contains the specified `releaseDate`, however in the generated `latest-mac.yml` the `releaseDate` is different. I assume it's the current timestamp, according to:

https://github.com/electron-userland/electron-builder/blob/cec30697912f56705fff42f7ac054fae4f4e735a/packages/electron-builder-lib/src/publish/updateInfoBuilder.ts#L185

Is this a bug or the `releaseDate` configuration option has a different intent?

Thank you!

**Comment by develar** [comment]
Now `releaseDate` is not set if already set by user.

**Comment by mkarp** [comment]
@develar Thank you!
