### ISSUE TITLE
iconUrl

### ISSUE THREAD

**Issue by Luncher** [electron-userland/electron-builder#273]
iconUrl must specify it? I can specify a local icon file?

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder/blob/master/docs/options.md iconUrl

**Comment by Luncher** [comment]
Thank you! I have not seen this document before

**Comment by gmonte** [comment]
link OFF

**Comment by madeeha96** [comment]
> See https://github.com/electron-userland/electron-builder/blob/master/docs/options.md iconUrl

Error 404 :/
