### ISSUE TITLE
Unknown argument: em

### ISSUE THREAD

**Issue by lightninglu10** [electron-userland/electron-builder#2733]
* **Version**: 
20.5.1

* **Target**: macOS

Hey guys, I'm trying to run the command 
```
electron-builder --em.main=./build/electron/electron.js
```
but it says 

```
Unknown argument: em
```

In the examples though, it shows it like this: 

```
  electron-builder --em.foo=bar             set package.json property `foo` to
```

which seems to be the same as what i'm doing. What's up with that?

**Comment by rouftom** [comment]
Use that instead `electron-builder -c.extraMetadata.main = build / electron.js` . 
Take a look at the same issue  [https://github.com/electron-userland/electron-builder/issues/2657](url)

**Comment by elibroftw** [comment]
@rouftom this*
