### ISSUE TITLE
The folder “app.zip” doesn’t exist

### ISSUE THREAD

**Issue by Matho** [electron-userland/electron-builder#2741]
Version
electron-builder: 20.7.1
electron-updater: 2.21.3

Target:
Mac OSX High Sierra

I have issue with error message ‘The folder “app.zip” doesn’t exist.’ At first I thought it is something related to space in file name, so after publishing to aws s3 I manually renamed the space in filename with dash. It was working, but only one time. Then I thought the issue was with cache. I tried to set  autoUpdater.requestHeaders = {"Cache-Control": "no-cache"}. Then it was working, but only for one time. I dont know why this bug occurs. The error message:

`Error: Error: The folder “app.zip” doesn’t exist.: The folder doesn’t exist.\n    at MacUpdater.doDownloadUpdate (/Applications/appname/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12)\n    at <anonymous>`

The same code works on windows. There is no space in windows installation file. Could you help me, please? I donated to increase issue priority.

Thanks

**Comment by develar** [comment]
Do you publish both zip and dmg files to s3? Please provide electron-builder configuration.

**Comment by Matho** [comment]
Yes, both zip and dmg are published to aws s3. Here is package.json:
`
{
  "name": "RocketMonkeysRecorder",
  "productName": "Rocket Monkeys Recorder",
  "version": "1.0.6",
  "description": "Make up to 40 €/hour by testing websites, games and applications.",
  "main": "index.js",
  "scripts": {
    "start:dev1": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "start:dev2": "node server.js",
    "electron": "electron .",
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist:linux": "webpack && electron-builder --linux",
    "dist:mac": "webpack && electron-builder --mac",
    "dist:win": "webpack && electron-builder --win",
    "dist:win32": "webpack && electron-builder --win --ia32",
    "ship:win_prod": "webpack && electron-builder --win -p always",
    "ship:mac_prod": "webpack && AWS_PROFILE=production electron-builder --mac -p always",
    "build": "webpack"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/dascope/rocket-monkeys-recorder-electron.git"
  },
  "author": "Rocket Monkeys <hello@rocketmonkeys.io>",
  "license": "ISC",
  "homepage": "https://www.rocketmonkeys.io/",
  "build": {
    "protocols": {
      "name": "Rocket Monkeys Recorder",
      "schemes": [
        "rcktmonkeys"
      ]
    },
    "publish": {
      "provider": "s3",
      "bucket": "rm-auto-update-electron"
    },
    "asarUnpack": [
      "**/*"
    ],
    "files": [
      "build/icon.icns",
      "build/icon.ico",
      "build/icons/*.png",
      "build/nsh-plugins",
      "build/installer.nsh",
      "!uploads/*.mp4",
      "uploads/index.html",
      "binaries/${os}/${arch}/node.exe",
      "binaries/${os}/${arch}/node",
      "binaries/${os}/${arch}/aperture",
      "dist/bundle.js",
      "src",
      "electron",
      "nodejs_server",
      "*.html",
      "*.js",
      "*.tpl",
      "*.sh",
      "*.json",
      "*.md",
      "*.lock"
    ],
    "extraResources": [
      "node_modules/electron"
    ],
    "appId": "io.rocketmonkeys.electron_recorder",
    "nsis": {
      "oneClick": true,
      "perMachine": true,
      "artifactName": "Rocket-Monkeys-Recorder_setup_${version}.${ext}"
    },
    "dmg": {
      "artifactName": "Rocket-Monkeys-Recorder_setup_${version}.${ext}",
      "iconSize": 80,
      "background": "build/background.tif",
      "window": {
        "width": 540,
        "height": 380
      },
      "contents": [
        {
          "x": 110,
          "y": 180
        },
        {
          "x": 400,
          "y": 180,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "deb": {
      "afterInstall": "linux_postinstall.tpl"
    },
    "win": {
      "icon": "build/icon.ico",
      "target": "NSIS"
    },
    "mac": {
      "category": "public.app-category.video",
      "target": "default",
      "icon": "build/icon.icns"
    },
    "linux": {
      "icon": "build/icons",
      "category": "AudioVideo",
      "desktop": {
        "Icon": "/opt/Rocket Monkeys Recorder/resources/app.asar.unpacked/build/icons/64x64.png"
      },
      "target": [
        "deb"
      ]
    }
  },
  "devDependencies": {
    "electron": "1.8.3",
    "electron-builder": "^20.7.1",
    "webpack": "^3.10.0",
    "electron-publisher-s3": "^20.6.1"
  },
  "dependencies": {
    "aperture": "git+ssh://git@code.softpoint.sk:martin.markech/aperture.git",
    "asar": "^0.14.0",
    "aws-sdk": "^2.164.0",
    "axios": "^0.17.1",
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-1": "^6.1.18",
    "bonjour": "^3.5.0",
    "bugsnag": "^2.1.3",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "compare-version": "^0.1.2",
    "cross-spawn": "^5.1.0",
    "domify": "^1.4.0",
    "electron-is-dev": "^0.3.0",
    "electron-redux": "^1.3.1",
    "electron-updater": "^2.21.3",
    "execa": "^0.9.0",
    "ffmpeg-static": "^2.1.0",
    "ffprobe-electron": "^1.1.2",
    "ffprobe-static": "^2.0.0",
    "fluent-ffmpeg": "^2.1.2",
    "formidable": "^1.1.1",
    "http-server": "^0.10.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "lodash": "^3.10.1",
    "mime": "^2.0.3",
    "mocha": "^2.4.5",
    "open": "git+ssh://git@code.softpoint.sk:martin.markech/node-open.git",
    "opn": "^5.1.0",
    "react": "^0.14.3",
    "react-addons-test-utils": "^0.14.7",
    "react-dom": "^0.14.3",
    "react-modal": "^3.1.2",
    "react-redux": "4.3.0",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "recordrtc": "^5.4.6",
    "redux": "^3.1.0",
    "redux-devtools": "^3.4.1",
    "redux-devtools-dock-monitor": "^1.1.2",
    "redux-devtools-log-monitor": "^1.4.0",
    "redux-form": "^6.6.3",
    "redux-promise": "^0.5.3",
    "strip-ansi": "^4.0.0",
    "webpack-dev-server": "^2.9.4",
    "websocket": "^1.0.25",
    "winston": "^2.4.0"
  }
}`

**Comment by IGassmann** [comment]
@Matho what's the name of your built zip file? Can you also comment here the content of your `latest-mac.yml` generated file?

**Comment by Matho** [comment]
Currently the filename is Rocket-Monkeys-Recorder-1.0.5-mac.zip , I changed spaces in filename and in json/yml with '-' because I though it makes the problems. 

[latest-mac.json.txt](https://github.com/electron-userland/electron-builder/files/1848213/latest-mac.json.txt)
[latest-mac.yml.txt](https://github.com/electron-userland/electron-builder/files/1848215/latest-mac.yml.txt)

**Comment by IGassmann** [comment]
This issue might be related to https://github.com/electron-userland/electron-builder/issues/2706. The second `url` value in your `latest-mac.yml` file doesn't match your actual zip file name.

**Comment by dascope** [comment]
Hi @develar @IGassmann - can we expect a resolution to this soon? It's blocking us from launching our app. Many thanks.

**Comment by IGassmann** [comment]
@dascope a workaround is to manually rename the file or the `url` values in the `latest-mac.yml` so they match each other. Download the necessary files, make the edits and re-upload them to S3. You'll have to do that with every release. It's inconvenient, but it works.

**Comment by Matho** [comment]
Thanks Igor. I renamed the zip file name to match the dmg filename. It is working on my mac, but it is not working on 2 different mac. The error is same.  Maybe some issue with cache?

**Comment by dascope** [comment]
hi @develar @IGassmann , we are still stuck unfortunately. we tried the rename but it did not work as @Matho describes above. thanks for your help.

**Comment by develar** [comment]
@dascope Please contact me using Slack (https://slackin.electron.build). Is it possible to show me your S3 bucket?

**Comment by IGassmann** [comment]
@develar does 254d7c5 resolve #2706?

**Comment by Matho** [comment]
No, this fix doesn't fix 2706. It fixes only cache issue.

**Comment by bezzer** [comment]
Have noticed this also fails when auto-updater is downloading from a server that sets the file name using Content-Disposition:

```
Content-Disposition: attachment; filename="MyApp_0.1.2.zip"
```

The downloader names the file MyApp_0.1.2.zip, then fails to find it with the error reported above. 

Luckily we were able to work around this by updating the server to match what the updater is expecting after a bit of debugging.
