### ISSUE TITLE
NSIS: update installers remain on disk after installation

### ISSUE THREAD

**Issue by vbeausoleil** [electron-userland/electron-builder#2744]
* **electron-builder Version**: 20.2.0

* **electron-updater Version**: 2.21.3

* **Target**: Windows NSIS

As mentioned in the issue's title, update installers are not cleaned up after install. Every update downloads a new installer and stores it in `C:\Users\%USERNAME%\AppData\Roaming\%APP_NAME%` as you can see in the following screenshot: 
![issue](https://user-images.githubusercontent.com/10699482/37911363-d37bed84-30dd-11e8-936f-26d3a18264f0.png)`

I am worried that in the long run, the directory will grow in size and users less diligent in their resource management might find their free disk space shrinking unexpectedly because of this behavior.

Is there a configuration parameter allowing to clean up previous installers (after an update, for example) or do I need to implement the clean up process inside my app?

Thank you!

**Comment by develar** [comment]
One file in any case is required (for differential updates, not yet enabled by default). Other... maybe it is trace of various version of updater (code was changed).... Need to check.

**Comment by petren** [comment]
+1, we are noticing the same issue.

**Comment by mkoleva** [comment]
Any tips on how to clean those or any workarounds? We are about to release our app to a large number of users and I am wondering if a future fix would clean leftover files or we should wait until it is fixed.

**Comment by develar** [comment]
Fixed, please use electron-updater 2.23.3 AND electron-builder 20.19.1
