### ISSUE TITLE
Missing entry in Add / Remove window of Control panel when using custom GUID

### ISSUE THREAD

**Issue by Mic75** [electron-userland/electron-builder#2749]
**Version**:  19.49.4
**Target**: nsis
**Relates to**: #2584 

We're facing a side effect when specifying a custom guid.
The application is not listed anymore in the Add / Remove Program Window from the Control Panel.

Any ideas about that?

**Comment by develar** [comment]
Looks like a bug. Will be investigated.

**Comment by etherElric** [comment]
Is there any news on the investigation of this?
