### ISSUE TITLE
NSIS installer crashes on Windows 8.1 x64

### ISSUE THREAD

**Issue by aleks-pro** [electron-userland/electron-builder#2751]
20.8.0

2.21.4

Windows 8.1 x64

In most cases, the NSIS installer works fine, but sometimes when you start it or try to switch between pages, it crashes. I could not reproduce the issue when 'oneClick 'option is enabled either. There is the crash report below.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	test-win-0.1.0.exe
  Application Version:	0.1.0.0
  Application Timestamp:	5a6fed7c
  Fault Module Name:	System.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a6fed15
  Exception Code:	c0000005
  Exception Offset:	00001581
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	5f25
  Additional Information 4:	5f2531ae070278f893fa99352dadd49e

**Comment by julianhille** [comment]
i've seen this too

**Comment by xiajingren** [comment]
hi. Has this problem been solved? I have the same problem
