### ISSUE TITLE
How do I rebuild keytar using electron-builder instead of electron-rebuild?

### ISSUE THREAD

**Issue by gknapp** [electron-userland/electron-builder#2756]
* **Version**: 20.8.1

* **Target**: Windows x64

During build, the following notice is shown:
> electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from `devDependencies`

I have a rebuild script in my `package.json` as I use `keytar`:
 - `"rebuild": "electron-rebuild -f -w keytar"`

If I remove `electron-rebuild`, what command do I use to rebuild using `electron-builder`?

**Comment by develar** [comment]
electron-builder does rebuild for you automatically. No need to use anything else.

**Comment by douglassllc** [comment]
What if you are using webpack-dev-server, which will fail to load if a package (i.e. keytar) is not rebuild for the platform on which I am development.

For example, I build for the Windows platform.  Then I go back to regular develop mode and run webpack-dev-server which fails because the keytar package needs to be rebuilt.

The solution mentioned would require me todo a complete build for my development environment just to have keytar rebuilt.

**Comment by devuxer** [comment]
@develar 

I have the same question, except SQLite instead of keytar.

What is the equivalent of this:

`electron-rebuild -f -w sqlite3`

...in electron-builder?

**Comment by thrazu** [comment]
Same question. Any answer?

**Comment by douglassllc** [comment]
I have not found the answer.

**Comment by Laruxo** [comment]
I have a `start` script that runs webpack-dev-server. Adding `"prestart": "electron-builder install-app-deps"` solved the problem for me.

**Comment by douglassllc** [comment]
@Laruxo thanks for the suggest.  I will give this a try.

**Comment by GeorgeFlorian** [comment]
Its almost 2025 and I am also encountering issues with this.

I run the dev build on my Linux Machine: `"dev": "npx electron-rebuild && concurrently \"npm run dev:vite\" \"npm run dev:electron\"",` and I build for Windows `"dist": "rm -rf dist dist_electron && npm run build && electron-builder --win",`
```json
  "build": {
    "appId": "com.ceva.automat-plata-parcare",
    "productName": " Automat Plata Parcare",
    "directories": {
      "output": "dist_electron",
      "buildResources": "build"
    },
    "files": [
      "dist/**/*",
      "electron/**/*",
      "build/**/*"
    ],
    "win": {
      "target": "portable",
      "icon": "build/m_icon.ico",
      "artifactName": "Automat-Plata-Parcare-${version}.exe",
      "executableName": "Automat Plata Parcare.exe"
    }
  },
  ```
  
After every build I get `Error: /home/george/Projects/automat-parcare-kiosk/node_modules/keytar/build/Release/keytar.node: invalid ELF header` and I have to delete node_modules and reinstall them. 
  
`npx electron-rebuild` does nothing to fix my issue.
