### ISSUE TITLE
electron-updater support for AppX update is either broken or missing

### ISSUE THREAD

**Issue by benjamincburns** [electron-userland/electron-builder#2758]
* **Version**: 2.21.6
* **Target**: Win32, AppX

My app was originally built using electron-forge, and as a result we elected to distribute with AppX. When we needed auto update functionality I saw that electron-builder had support for AppX targets & auto updates, so it seemed like a natural choice. However, it seems like auto updates on AppX don't work.

First, `latest.yml` is built such that it points to the NSIS installer only. To get around this I hand-edited with the info for the AppX. This caused my app to get so far as downloading the new installer and restarting, but nothing happened from that point forward. I could be mistaken, but I think the signature check passed, even.

Taking a brief look at [the entrypoint code](https://github.com/electron-userland/electron-builder/blob/541605ff2038c1b9485d8f0a3c88167f61e80b8d/packages/electron-updater/src/main.ts#L20-L30), from the outset it seems the windows update support is built around the NSIS installer target. Further inspection of the [`NsisUpdater` class](https://github.com/electron-userland/electron-builder/blob/541605ff2038c1b9485d8f0a3c88167f61e80b8d/packages/electron-updater/src/NsisUpdater.ts) confirms that suspicion.

I'm very happy to submit a PR for an `AppXUpdater`, but I'm wondering if any of the maintainers (cc @develar) have attempted this yet, or know of any pitfalls or gotchas I should look out for w.r.t. AppX. For instance, I know that AppX is a sandboxed environment. 

One thing I can think of straight off is that a goal of the change should be for AppX builds to be distributable alongside NSIS builds, meaning both build types should be capable of choosing the correct update target.

**Comment by develar** [comment]
AppX it is only for Windows 10+ and only for Windows Store. So, auto-update is not supported for AppX.

You can set `electronUpdaterAware` to `true`, but then you will get https://github.com/electron-userland/electron-builder/issues/1908#issuecomment-321189761

So, electron-builder supports AppX updates (set mentioned option), but electron-updater doesn't (because no need AppX since it is supported only on Windows 10).

I will close issue as "backlog" and "help-wanted"

**Comment by benjamincburns** [comment]
I'm confused by this issue being closed, then all the labels being added. Are you saying you would or wouldn't accept a pull request for this? If you would accept a PR, why close the issue?

**Comment by develar** [comment]
> If you would accept a PR, why close the issue?

Opened issue means that someday maintainers will find time to implement this feature. Closed means  what added tags means. In this case `help wanted` and `backlog`.
