### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by havenchyk** [electron-userland/electron-builder#276]
- [ ] About passing the tests on windows
- [ ] About passing the tests on linux and osx
- [ ] About npm version

**Comment by develar** [comment]
Tests in master must be green. Period. Always. If squirrel.windows sometimes failed, it is developer responsibility to restart it ASAP. So, I don't think that badges will be useful.

**Comment by havenchyk** [comment]
I'll provide the PR for it and then you can accept it or not. I don't see the version of package on the github, so I have to go to the npmjs.com and then check the version.

**Comment by havenchyk** [comment]
Added PR #280.
