### ISSUE TITLE
app-update.yml not generated when using --prepackaged flag

### ISSUE THREAD

**Issue by cmttan** [electron-userland/electron-builder#2761]
* **Version**: 
"electron-builder": "^20.8.1",
"electron-updater": "^2.21.4",

* **Target**:
Windows/NSIS

A similar issue is found here: #2667 but what worked for op didn't work for me.
I am trying to get auto-update working in my application but can't seem to get past this error about missing `app-update.yml`.

After running this build script: `"package-win-release": "build --win --ia32 --prepackaged ./release/win-ia32-unpacked"`, an installer is generated as well as the `latest.yml` file.

After running the installer, starting the app, and looking at the log file found here `C:\Users\userName\AppData\Roaming\myApp`  for auto-update, I'm seeing this:
```
[2018-03-30 14:55:28.935] [info] ---- checking for update...
[2018-03-30 14:55:28.966] [info] Checking for update
[2018-03-30 14:55:28.966] [info] Checking for update...
[2018-03-30 14:55:29.639] [error] Error: Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\myApp\resources\app-update.yml'
 at t.NsisUpdater.loadUpdateConfig (C:\Program Files (x86)\myApp\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:508:1)
 at t.Lazy.configOnDisk [as creator] (C:\Program Files (x86)\myApp\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:210:1)
 at t.Lazy.get value [as value] (C:\Program Files (x86)\myApp\resources\app.asar\webpack:\node_modules\lazy-val\out\main.js:22:1)
 at t.NsisUpdater.getUpdateInfo (C:\Program Files (x86)\myApp\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:421:1)
 at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
[2018-03-30 14:55:29.639] [info] Error updating app.

```
package.json build configuration below. I've added the publish configuration to all of the areas that I've seen examples of.  I've also tried setting the publish configuration in those specific areas but still no luck.
```
  "build": {
    "productName": "my product name",
    "appId": "com.app.id",
    "compression": "normal",
    "nodeGypRebuild": false,
    "asar": true,
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "extraFiles": [],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "target": [
      "nsis"
    ],
    "publish": [{
      "provider": "generic",
      "url": "http://localhost:8088"
    }],
    "win": {
      "target": "nsis",
      "publisherName": "publisher",
      "icon": "resources/icon",
      "publish": [{
        "provider": "generic",
        "url": "http://localhost:8088"
      }]
    },
    "linux": {
      "target": [
        "deb",
        "AppImage"
      ],
      "category": "Development"
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "perMachine": true,
      "artifactName": "${productName}-Setup.${buildVersion}.${ext}",
      "publish": [{
        "provider": "generic",
        "url": "http://localhost:8088"
      }]
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  },
```

**UPDATE 4/2/2018:** After removing `--prepackaged` flag from the build script, the `app-update.yml` file is generated but the application is not working.  How does the `--prepackaged` flag affect the build and creation of app-update.yml?

**Comment by midevnull** [comment]
I noticed the same.

> "electron-updater": "4.0.6"
>"electron-builder": "20.38.5"

This doesnt not create an app-update.yml file:
> electron-builder --dir && DoSomethingElse && electron-builder --prepackaged dist/build/win-unpacked --publish alway

While this does:
> electron-builder build --publish always

This is not really an issue. But I am curious why that is.

**Comment by brennomarques** [comment]
Hello, I have this problem, I do everything in the documentation, now I did it like that, but even so it keeps saying that there was no finder "app-update.yml" when the Build was generated, I don't know what else to do. I'm using Linux x64

```
[2020-05-23 18:08:12.893] [info] Checking for update
[2020-05-23 18:08:12.956] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_assistZQfY4W/resources/app-update.yml'
[2020-05-23 19:58:50.565] [info] Checking for update
[2020-05-23 19:58:50.612] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_assistzhNIYM/resources/app-update.yml'
[2020-05-23 21:57:14.388] [info] Checking for update
[2020-05-23 21:57:14.440] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_assistfTHclG/resources/app-update.yml'
[2020-05-24 00:15:33.335] [info] Checking for update
[2020-05-24 00:15:33.379] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_assistlyhvqs/resources/app-update.yml'
[2020-05-24 09:33:38.438] [info] Checking for update
[2020-05-24 09:33:38.486] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_assistTtLBna/resources/app-update.yml'
```

**Comment by marciot** [comment]
Did anyone find a solution for this? Same issue.

**Comment by brennomarques** [comment]
Hello, all right, I had no answer here, but before looking for information and I found one that resovel, as I'm using electron and vue.js, in the same directory a file called vue.config.js was created, I put the build settings in it, getting like this .....

**********************************************************************************************************************************
```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                appId: "",
                productName: "",
                artifactName: "",
                publish: [{
                    provider: "generic",
                    url: "http://localhost:8080/"
                }],
                linux: {
                    target: "AppImage",
                    synopsis: "",
                    description: "",
                    executableName: "teste",
                    category: "Utility",
                },
                mac: {
                    category: "public.app-category.productivity",
                    target: [
                        "dmg"
                    ],
                },
                win: {
                    "target": [{
                        "target": "nsis",
                    }],                   
                }
            }
        }
    }
}
```

After all this you will have a problem signing the code, if you are doing it for windows, MAC, linux. to subscribe to a look at the documentation, https://www.electronjs.org/docs/tutorial/code-signing, I am using electron-builder, so https://www.electron.build/code-signing.

I hope it helps! I had this same problem again and solve it the same way, I have a skeleton in git with the correct configuration using electron and vue cli as a plugin

https://github.com/brennomarques/skeleton-vue-electron

https://github.com/brennomarques/electron-update

**Comment by marciot** [comment]
@brennomarques:

It seems like your situation is a bit different, but I found a solution that worked for me.

Since I was using "electron-packager" to build the app, and using `--prepackaged` to tell "electron-builder" about it, the `app-update.yml` was not being placed in the resources directory of the app. As far as I can tell,  "electron-builder" would do this automatically when not using `--prepackaged`.

So my solution was to tell "electron-packager" to include an `app-update.yml` using the command line switch `--extra-resource=app-update.yml`. I had to manually create a `app-update.yml` for it to include, like so:

```
owner: <github-username>
repo: <github-repo>
provider: github
updaterCacheDirName: <github-repo>-updater
```

Now, this solution works, but it is not ideal because if the repo changes location, the `app-update.yml` needs to be updated manually. One of the nice features of `electron-builder` is that it ordinarily takes care of this step automatically. Ideally, there would be a way to tell `electron-builder` where to write out a `app-update.yml` file, even when `--prepackaged` is being used.

**Comment by brennomarques** [comment]
@marciot I understand, in this case it is really different. some time I had a problem when I was in developer mode, it did not generate app-update.yml, I had to inform electron to generate it when I was in developer, but solve it.

I am currently studying how to work with The PKCS # 11 standard defines an API-independent platform for cryptographic tokens.

Success in your project.

**Comment by FoonkG** [comment]
I'm having the same issue, please reopen this.

**Comment by SentoxAIO** [comment]
+1, I am facing the same issue
