### ISSUE TITLE
Question about file association path

### ISSUE THREAD

**Issue by javisperez** [electron-userland/electron-builder#2762]
* **Version**: 20.6.2

* **Target**: darwin linux, windows

Hello there!

I know this might be been asked many times but I've just found one issue related (https://github.com/electron-userland/electron-builder/issues/1757) and is still unclear for me.

Basically, I want to understand about the file association works, can't find the full flow on the documentation, so, I'm sorry if this issue is annoying.

I'm building an app which (when done) will be targeted to Linux, Mac, and Windows and i've add the file association entry but i dont know how to get the path of the clicked file when a file is double clicked to open with my app.

Seems like we need to use protocols for that but, does double clicking a file send it as a custom protocol? if so, what protocol? 

Also, i've seen that for windows we can use `process.argv[1]` but doesn't work for mac/linux, am i right on that?

So, what do i need to get the "double click to open" behavior working on the three targets?

Thank you a lot! ✌️

**Comment by Ishaangandhi** [comment]
What about the second or third file opened via the app?
As I understand, the 'open-file' event on app will get triggered?

**Comment by bm777** [comment]
yes, app can receive from the OS, but ipcMain is only for the communication via channels between the main process and the rendered process.

so you should do this to receive the event from the OS:

```js
const { app } = require('electron');

app.on('open-file', (event, path) => {
    event.preventDefault();
    // Handle the file path (e.g., open the file in a new window).
    console.log('File opened:', path);
    // Your file handling logic here
});

app.on('ready', () => {
    // Your application initialization logic here.
});
```
