### ISSUE TITLE
App installation fails after updating electron-builder

### ISSUE THREAD

**Issue by thavasukkannu** [electron-userland/electron-builder#2764]
* **node version**: 8.11.1
* **npm version**: 5.8.0
* **electron version**: 1.8.4
* **electron-builder version**: 20.8.2
* **electron-updater** : 2.20.1
* **Target**: Windows

We had electron-builder version 20.5.1 and app installation went smooth.

When we updated electron-builder to 20.6.1, the app installation failed with the below error message.
We then updated to 20.8.2 and still getting the same issue. 

![error1](https://user-images.githubusercontent.com/28038281/38236871-1cc38c98-3743-11e8-857a-1344d7edbf89.png)

When we clicked the app desktop shortcut, it throws the below error

![error2](https://user-images.githubusercontent.com/28038281/38236876-21e79e58-3743-11e8-92f3-65a2a3ebc3a3.png)

Please let us know if we are missing something.

Thanks in advance,

**Comment by KingRial** [comment]
I can confirm to have the same situation.
The only way to obtain a correct executable was to downgrade to electron-builder@20.5.1

**Comment by MichaelIT** [comment]
yes, I can confirm this issues.
- node version: 8.11.1
- npm version: 5.6.0
- yarn version: 1.6.0
- electron version: 1.8.4
- electron-builder version: 20.10.0
- electron-updater : 2.21.8

When I goto system event, I found flowing error message:
```
“C:\Projects\iprint-electron\release\win-ia32-unpacked\app.exe”的激活上下文生成失败。在指令清单或策略文件“C:\Projects\iprint-electron\release\win-ia32-unpacked\app.exe”的第 0 行出现错误。 无效的 Xml 语法。
```
I means there is wrong xml in exe manifest, so i go to manifest xml file, open it with editor, and I found:
![wx20180422-203602](https://user-images.githubusercontent.com/5445733/39095069-d36c2e68-466c-11e8-91be-fd25d6af82fc.png)

**Comment by MichaelIT** [comment]
By the way, It work with electron-builder version 19.55.3

**Comment by KingRial** [comment]
It works also on version 20.5.1 (with all the later releases it doesn't work)

**Comment by gmarinosyan** [comment]
Having exactly the same issue with any version 20.6.1 and up.

**Comment by ijse** [comment]
+1

**Comment by KingRial** [comment]
It seems I can replicate the problem with a simple project by adding the following configurations and launching the build operation from Win10:

````
"win": {
  "target": "nsis",
  "icon": "assets/build/installer/images/icon/icon_256x256.png",
  "requestedExecutionLevel": "requireAdministrator"
},
"nsis": {
  "allowElevation": true,
  "createDesktopShortcut": true,
  "createStartMenuShortcut": true,
  "menuCategory": "HelloWorld",
  "deleteAppDataOnUninstall": true,
  "oneClick": false,
  "perMachine": true,
  "allowToChangeInstallationDirectory": true,
  "runAfterFinish": true,
  "license": "assets/build/installer/win/license.txt",
  "warningsAsErrors": true
}
```

Still trying to understand what of these options is the cause of the problem

**Comment by develar** [comment]
@KingRial Problem in the `requestedExecutionLevel`

**Comment by KingRial** [comment]
Yes, I can confirm that: just tested right now.
