### ISSUE TITLE
Get application path coherently in dev and production and cross-platform. What is the best way?

### ISSUE THREAD

**Issue by nkint** [electron-userland/electron-builder#2765]
Hi, I'm new to electron, and I need some hints.

macOs: Sierra 10.12.6
node: v9.5.0
electron: 1.8.4
electron-builder: 20.8.1

I'm trying to make an electron app that loads files in the directory where the applicaiton is.

I'm using this small file following a pattern found in the [`remote` documentation](https://electronjs.org/docs/api/remote#remoterequiremodule):
```
const { app } = require('electron')
let path = app.getAppPath()
function get() {
  return path
}
module.exports = { get: get }
```
that I'm calling it in the renderer file as 
```
const rootAppDir = window.require('electron').remote.require('./electron-app-path').get()
```

In development I get the directory of the project (where I have the `package.json` and where I call `electron .`:
```
/Users/user/path/to/electron-experiment
```
 while in production (after `electron-builder --mac`) I get the asar folder:
```
/Users/user/path/to/electron-experiment/dist/mac/electron-experiment.app/Contents/Resources/app.asar
```
That is not a real directory I can explore with `cd` shell command.

What I want is `/Users/user/path/to/electron-experiment/dist/mac`.
I can resolve it with some tricky combination of `'../'` and `path.join` but I feel there should be a better solution.

Do you have any hints?

**Comment by Slapbox** [comment]
Wrap paths in `path.normalize(somePath)`

Make sure you first `import path from 'path';`
