### ISSUE TITLE
Is there a way to cache built native dependencies?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#2766]
I'm troubleshooting some issues with my packaged application that's required me to package my app many many times. `rebuilding native dependencies` every run adds a whole lot of time. Is there some way to cache these?

**Comment by develar** [comment]
Yes — your native module must use `prebuild` https://github.com/prebuild/prebuild

electron-builder is not going to reinvent the wheel, `prebuild` is awesome.

**Comment by Slapbox** [comment]
Thanks @develar I'll look into that!
