### ISSUE TITLE
[QUESTION] Beta and Alpha versioning

### ISSUE THREAD

**Issue by Stoyvo** [electron-userland/electron-builder#2768]
* **Version**: 20.8.1

Following the documentation here: https://github.com/electron-userland/electron-builder/blob/master/docs/tutorials/release-using-channels.md#release_using_channels

I understand that I can release, lets say: 1.1.0-beta
Usually you have a number of revisions to the beta. How do versions work with the beta or alpha channel?
Based on research from https://semver.org/, I should be able to release: 1.1.0-beta.1 or 1.1.0-beta.2, etc.

Does Electron-Updater support this?

**Comment by mkarp** [comment]
@Stoyvo Yes, from what I can tell it will work like you expect. electron-publisher will create different `*.yml` files (in your case it's `beta.yml` for Windows and `beta-mac.yml` for macOS) and electron-updater will fetch the correct one. 

Btw, you can use ` npm version prerelease` to update the prerelease version in your package.json.

**Comment by Stoyvo** [comment]
Thanks @mkarp!
