### ISSUE TITLE
[Question] Macro to only write extraFiles if file does not exist

### ISSUE THREAD

**Issue by davidAlittle** [electron-userland/electron-builder#2769]
* **Version**: 
19.56.2

* **Target**: 
Win 64

So we're using the extraFiles section to add some directories to the installed folder location.
```		
"extraFiles": [
			"Documents/",
			"Logs/",
			"Logs/Faults/"
		],
```
Which works awesome, but the files in these folders get changed by the application, so we don't want to over-write them when the user updates by running a newer version of the installer. 

the nsis docs say you can do ifFileExists in a script/macro, but I'm not sure where to put that or how to call it. Any tips?

If it matters, this is on an OEM system, so we control the target (it's our PC, our field service are the ones doing the updates), we can't use squirel or any kind of auto-updating, and we're customizing the install location:
```
// build\installer.nsh
!macro preInit
    SetRegView 64
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Company\App"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Company\App"
    SetRegView 32
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Company\App"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Company\App"
 !macroend
```

So, for example, I need to check to make sure ```C:\Company\App\Documents\configs.ini``` doesn't already exist before copying it.

Also, we're using FBWF to prevent changes to most of the system, with our directory excluded, which is why we're not storing these things in Users/user/AppSettings or whatever the default is.

**Comment by develar** [comment]
Solution — 

1. do not use `extraFiles` (remove configuration).
2. define own macro `customInstall` and do whatever you want. `PROJECT_DIR` and `BUILD_RESOURCES_DIR` are available for you to specify path to source files. Use ut like `${PROJECT_DIR}` in a string.

**Comment by develar** [comment]
FYI: `customInstall` macro inserted AFTER `installApplicationFiles`

**Comment by JeongJun-Lee** [comment]
Hello, I hava a same issue but I'm novice at both electron-bulilder and nsis. I can't learn how to write a custom script through the link above. Could you give me a more useful tutorial link? Thanks.

**Comment by JeongJun-Lee** [comment]
Hello, I hava a same issue but I'm novice at both electron-bulilder and nsis. I can't learn how to write a custom script through the link above. Could you give me a more useful tutorial link? Thanks.

@davidAlittle Did you find a solution? Could you give me a hint?

**Comment by davidAlittle** [comment]
@JeongJun-Lee Sorry, I didn't. 

I looked at the docs for nsis (in general), but didn't have the time to figure any of it out. Which is really unfortunate, because we have some pretty significant installer issues we're having to hack around (over-writing user files that have to be in certain directories, etc). 

If there are docs, I'd really love love love to see them.
