### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by havenchyk** [electron-userland/electron-builder#277]
- [ ] Issue template
- [ ] PR template

Materials:
- https://github.com/blog/2111-issue-and-pull-request-templates
- https://github.com/kentcdodds/issue-template

**Comment by develar** [comment]
Decided to not do it, because most of the issues are different. JetBrains Youtrack, e.g., also doesn't have templates.

**Comment by havenchyk** [comment]
Hm. You always almost ask to add the config and so on. But it's not a problem for me. Can be closed in this case.
