### ISSUE TITLE
Uninstall application does not delete Folder on Windows AppData/Roaming

### ISSUE THREAD

**Issue by marcusjwhelan** [electron-userland/electron-builder#2770]
19.29.2

2.20.0

nsis-web

When uninstalling the application a remnant folder related to the application stays behind in the users/appdata/roaming folder. This turned out to be a problem when I had errors with my database. After I fixed it and released the update this folder related to the application must be holding some kind of information that kept the update from helping.

 After deleting the folder and re-installing the application the fixes I made finally went through. This was a very specific case and did not happen to all the applications only one. However I feel like when uninstalling this folder related to the application should be removed.

**Comment by develar** [comment]
Set `deleteAppDataOnUninstall` to `true` (in the `nsis`). https://www.electron.build/configuration/nsis
