### ISSUE TITLE
Windows installer metadata is incorrect

### ISSUE THREAD

**Issue by bontibon** [electron-userland/electron-builder#278]
I am generating a Windows installer (on Windows) using version 3.1.1. I noticed that the generated installer has "[object Object]" as the value for both "File description" and "Product name".

![properties](https://cloud.githubusercontent.com/assets/110883/14115374/16f80030-f5b1-11e5-858a-13f03e27d729.png)

The application executable itself has the correct values.

Examining the nuspec template in `node_modules/electron-winstaller-fixed/lib/index.js` shows where the issue might be:

```javascript
    const nuspecContent = `<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>${ metadata.name }</id>
    <title>${ metadata.title }</title>
    <version>${ convertVersion(metadata.version) }</version>
    <authors>${ metadata.authors || metadata.owners }</authors>
    <owners>${ metadata.owners || metadata.authors }</owners>
    <iconUrl>${ metadata.iconUrl }</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>${ metadata }</description>   <!-- This accounts for the incorrect description -->
    <copyright>${ copyright }</copyright>
  </metadata>
....
```

**Comment by havenchyk** [comment]
Have the same bug (probably with 3.1.0) as well.

**Comment by develar** [comment]
@havenchyk regression introduced by commit https://github.com/develar/windows-installer/commit/8f76c91d1a6c238f39c9c966e88214cc7d14a4ca (branch builder) I added you as collaborator, so, you can fix it and publish electron-winstaller-fixed module because I am on vacation now.
