### ISSUE TITLE
Build electron-builder locally

### ISSUE THREAD

**Issue by shaluyadav13** [electron-userland/electron-builder#2781]
I have forked the electron-builder into Bitbucket and specify that repo in the package.json dependencies.

It didn't work. The problem is that electron-builder is a collection of modules and not sure how to get all the internal dependencies consistent. Also, how to build it locally and substitute the local version for the published version.

Can anyone help me with this?

**Comment by AllSeeingEye** [comment]
Compilation totally works if you use Yarn:

`git clone <repo-url>`
`cd electron-builder`
`yarn`
`yarn compile`

After that, I've copied the contents of `packages` into the `node_modules` folder of my project and it somehow worked (but I admit, this is a savage way to debug).

Hope it helps.

**Comment by shaluyadav13** [comment]
Thank You, I am able to compile and debug. I have made some code changes in electron-builder code those changes work fine when I debug. I want my project to always use the modified electron-builder code, so I was wondering if there is any way I can replace `electron-builder: "19.48.3"` with my local electron-builder project?

**Comment by AllSeeingEye** [comment]
@shaluyadav13 this might help:
https://stackoverflow.com/questions/14381898/local-dependency-in-package-json

**Comment by develar** [comment]
To set version: `yarn set-versions`

To use local version: set `NODE_PATH` env to `/full/path/to/electron-builder/packages`

**Comment by develar** [comment]
Example run configuration for IntelliJ IDEA or Webstorm:

```xml
    <configuration name="Unnamed (8)" type="NodeJSConfigurationType" factoryName="Node.js" singleton="false" application-parameters="--mac zip -c.compression=store" path-to-js-file="$PROJECT_DIR$/packages/electron-builder/out/cli/cli.js" working-dir="$PROJECT_DIR$/../onshape-desktop-shell">
      <envs>
        <env name="NODE_PATH" value="$PROJECT_DIR$/packages" />
      </envs>
    </configuration>
```

**Comment by shaluyadav13** [comment]
on executing `Yarn set-versions` I am getting an error. Below is the stack trace:
```
yarn run v1.5.1
$ node test/out/helpers/setVersions.js
Error: Exit code: ENOENT. spawn yarn ENOENT
    at C:\Users\syadav\Documents\projects\electron-builder\packages\builder-util\src\util.ts:124:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at getLatestVersions (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:34:26)
    at setPackageVersions (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:54:26)
    at main (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:28:11)
    at <anonymous>
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node test/out/helpers/setVersions.js
Directory: C:\\Users\\syadav\\Documents\\projects\\electron-builder
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\syadav\\Documents\\projects\\electron-builder\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Haemp** [comment]
@develar Would love it 

> To set version: `yarn set-versions` You don't need to set versions, just set `NODE_PATH` env:
> 
> To use local version: set `NODE_PATH` env to `/full/path/to/electron-builder/packages` (e.g. `/Users/develar/Documents/electron-builder/packages`)

Would love it if that piece of information could find it's way into the docs.
