### ISSUE TITLE
How to disable code signing in windows?

### ISSUE THREAD

**Issue by eranimo** [electron-userland/electron-builder#2786]
* **Version**: 
20.8.1

* **Target**: 
Windows

How do I disable code signing in Windows? This app is internal and will not be distributed. I have an apple Developer ID certificate but when using it I get the following error when updating:

```
Sign verification failed, installer signed with incorrect certificate...
```

The docs do NOT make it clear whether or not code signing is required. It doesn't appear that it is, which is strange.

**Comment by develar** [comment]
Just do not specify code sign cert for win. Set `win.verifyUpdateCodeSignature` to `false` to explicitly disable signature verification on update.

**Comment by eranimo** [comment]
Thanks.

How do I disable it for macOS? Or is it absolutely required?

**Comment by develar** [comment]
set env `CSC_IDENTITY_AUTO_DISCOVERY` to `false`.

**Comment by eranimo** [comment]
When set that env, in the app autoupdate fails and I get a code signing error.

**Comment by mqliutie** [comment]
@develar Set `win.verifyUpdateCodeSignature` to `false` is not work for me. `electron-builder` version is `24.13.3`
`win.sign` to  `false` not work too.
