### ISSUE TITLE
I want to have a file in afterSign asarUnpack. How should I configure it?Can you give me an example?

### ISSUE THREAD

**Issue by y489436672** [electron-userland/electron-builder#2791]
* **Version**: 
19.19.1

* **Target**: 
MAC OS

I want to have a file in afterSign asarUnpack. How should I configure it?Can you give me an example?

**Comment by develar** [comment]
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = _default;

// test custom windows sign using path to file
async function _default(params) {
  // your code
} 
```

and `afterSign: "path/to/file`.

**Comment by y489436672** [comment]
Sorry, I still don't quite understand how to go to asarUnpack a specified file.

**Comment by y489436672** [comment]
async function _default(params) {
  // your code
} 
How do I write the files specified by asarUnpack?
