### ISSUE TITLE
msi icon

### ISSUE THREAD

**Issue by GitNomster** [electron-userland/electron-builder#2799]
* **Version**: 20.6.1

* **Target**: msi

I created the installation file. But when I installed it, the shortcuts has no icon.
![op](https://user-images.githubusercontent.com/29253035/38864334-d35259e2-4253-11e8-8dc7-83f91699c74d.JPG)

My package json:

> {
>   "name": "electron-webpack-quick-start",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "dev": "electron-webpack dev",
>     "compile": "electron-webpack",
>     "dist": "npm run compile && electron-builder",
>     "dist:dir": "npm dist --dir -c.compression=store -c.mac.identity=null"
>   },
>   "build": {
>     "productName": "program",
>     "directories": {
>       "output": "dist"
>     },
>     "win": {
>       "icon": "icons/icon.ico",
>       "target": "msi"
>     }
>   },
>   "dependencies": {
>     "source-map-support": "^0.5.4"
>   },
>   "devDependencies": {
>     "electron": "1.8.4",
>     "electron-builder": "20.6.1",
>     "electron-webpack": "^2.0.1",
>     "webpack": "^4.4.1"
>   },
>   "resolutions": {
>     "webpack-sources": "1.0.1"
>   }
> }

**Comment by dvankuren** [comment]
I'm running into this as well.  Looking at the source, icon.ico is specified (hard-coded) as the icon.  According to the Wix documentation, this will not work.

http://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcut.html

"Identifier reference to Icon element. **The Icon identifier should have the same extension as the file that it points at**. For example, a shortcut to an executable (e.g. "my.exe") should reference an Icon with identifier like "MyIcon.exe""

**Comment by dvankuren** [comment]
Running into the same issue here (version 20.28.4).  The executable displays the proper icon, but the shortcut does not.  According to the Wix documentation, there may be some issues with the template that is being generated?  Icon.ico is hardcoded into the template, but the Wix documentation says that an ico file shouldn't work.

http://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcut.html

"Identifier reference to Icon element. **The Icon identifier should have the same extension as the file that it points at**. For example, a shortcut to an executable (e.g. "my.exe") should reference an Icon with identifier like "MyIcon.exe""
