### ISSUE TITLE
Msi target separates files and subdirectories into different directories

### ISSUE THREAD

**Issue by GastonFerrari** [electron-userland/electron-builder#2804]
* **Version**: 20.9.0 (and going back at least to 19.35.1)

* **Target**: msi

When we build our app without packing it in an asar file there's 2 directories for each of the app directories, eg:

```
resources
│   electron.asar    
│
└───app
│   └───src
│       └───src_subdir
│       └───src_subdir_u
│           │   subSrcFile1.txt
│   └───src_u
│       │   srcFile1.txt
│       │   srcFile2.txt
│       │   ...
│   
└───app_u
    │   package.json
```

I'm pretty sure the issue is in this file: packages/electron-builder-lib/src/targets/MsiTarget.ts

This line in particular:
```
let result = `<Component${directoryId === null ? "" : ` Directory="${directoryId}"`}>`
```

I think the Directory in the component needs to be the actual directory and not the directoryId

**Comment by develar** [comment]
Duplicates #2272
