### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sagorshkov** [electron-userland/electron-builder#2808]
* **Version**: 20.9.0

* **Target**: snap

Hi guys! I've updated the electron builder to the latest version because of [#2803](https://github.com/electron-userland/electron-builder/issues/2803) fix there. It works and it passed the automated review in the Store. But now I'm getting the Segmentation fault (core dumped) error after install a snap from the Store.
![screenshot from 2018-04-18 22-22-33](https://user-images.githubusercontent.com/15627840/38944960-093e37fc-4357-11e8-84db-7cdd6fe77a89.png)
Any ideas about it? Thanks in advance.

**Comment by develar** [comment]
> I’ve tried to use 20.9.2 but the problem with Segmentation fault (https://github.com/electron-userland/electron-builder/issues/2808) is still there for me

Where do you build (OS?)?
What is your config?
Is option `useTemplateApp` (under `snap`) help you?

**Comment by develar** [comment]
Should be fixed in 20.10.0
