### ISSUE TITLE
Asar exception after using msi for installation

### ISSUE THREAD

**Issue by Nederby** [electron-userland/electron-builder#2809]
* **Version**:  20.8.1
* **Version**:  Electron: 1.8.2
* **Target**: MSI

My config builds both `*.msi` and `*.exe` file.

```javascript 
   "build": {
     "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        },
        {
          "target": "msi",
          "arch": [
            "x64",
            "ia32"
          ]
       }
    ],
    "asar": true, // is not required - default is also true.
    "nsis": {
      "installerIcon": "./assets/dixa-install.ico",
      "uninstallerIcon": "./assets/dixa-install.ico",
      "oneClick": false,
      "artifactName": "dixa-setup-${version}.${ext}"
    },
    "msi": {
      "warningsAsErrors": false // does not publish the msi installer without this.
    }
  }
```

The builds are successful, but when we run the MSI installer, it is installed and the app is launched but then the following exception is thrown.:

![pasted image at 2018_04_18 10_52 am](https://user-images.githubusercontent.com/6588469/38921842-017d61b0-42f7-11e8-9eef-34a3433faea0.png)

**When running `.exe` everthing works - the app is installed and is launched and works**

**Comment by Nederby** [comment]
I have narrowed the issue down to two modules [node-notifier](https://github.com/mikaelbr/node-notifier) and [jabra](https://www.npmjs.com/package/jabra) somehow the msi build process can't pack these two moduls with asar.
on node-notifier the docs says.:

> **Within Electron Packaging**
If packaging your Electron app as an asar, you will find node-notifier will fail to load. Due to the way asar works, you cannot execute a binary from within an asar. As a simple solution, when packaging the app into an asar please make sure you --unpack the vendor folder of node-notifier, so the module still has access to the notification binaries. To do this, you can do so by using the following command:
> `asar pack . app.asar --unpack "./node_modules/node-notifier/vendor/**" `

and on Jabra the docs says.:

> For Electron.JS: If you are using asar packaging then you need to unpack some of the resources used in this module. These resources are native library files i.e libjabra.dll, libjabra.dylib & libjabra.so, which is stored in a shared-lib folder. By default latest electron builder will automatically unpack, but if it does not work then you can provide below option to your build process. To know more, see this link
```
"build": {
    "asarUnpack": ["node_modules/jabra"]
}
```

But it does not seem to work. Is there any issue with msi native libraries - again it works when building and runing the **nsis** `exe` installer

**Comment by ndrantotiana** [comment]
Could you opt for a glob like:

`
"build": {
....
    "asarUnpack": ["**node_modules/jabra/**", "**node_modules/node-notifier/**"]
...
}
`

**Comment by Nederby** [comment]
@ndrantotiana thanks - but adding a glob did not work.

**Comment by develar** [comment]
Duplicates #2272
