### ISSUE TITLE
Windows ia32 installer not being built anymore on x64 machine?

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#281]
After upgrading to version 3.1.1 no ia32 installer is being built.
Is this expected or is it a bug?

Thanks

**Comment by develar** [comment]
It is expected. We build only current arch. Please see #233

**Comment by demetris-manikas** [comment]
Correct me if I get this right. 
Instead of allowing user to set the arch argument so as to build for a specific arch (say x32) the whole thing went away?
So I now need to have an ia32 machine to build for ia32?

**Comment by develar** [comment]
No. Only default was changed. You can use `--arch i32` or `--arch all` to build ia32on 64bit machine.

**Comment by demetris-manikas** [comment]
Thanks a lot.

**Comment by vicentedealencar** [comment]
I am not using the command line so it is not clear where to set `arch`, so I tryed like this on the package.json

```
  "build": {
    "arch": "ia32",
    ...
```

but I get this error `Error: Option arch is ignored, do not specify it.`

Am I missing something?

**Comment by develar** [comment]
@vicentedealencar Do you use `build` method directly?

So, 

```
export interface BuildOptions extends PackagerOptions, PublishOptions {
}

export async function build(originalOptions?: BuildOptions): Promise<void>
```

It means that you just call

```
build({arch: "ia32"})
```

**Comment by vicentedealencar** [comment]
Is `build` on package.json of type `BuildOptions`?

Using the thing I first tryed - `"arch": "ia32",` - doesn't work because of [this code](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L251)

**Comment by develar** [comment]
@vicentedealencar No. It is a `BuildMetadata`.
