### ISSUE TITLE
Remove "runAfterFinish" checkbox

### ISSUE THREAD

**Issue by giacgbj** [electron-userland/electron-builder#2811]
* electorn-builder:  20.9.2
* electron-updater: 2.21.8

I'd like to use nsis to produce a Windows installer with the following configurations:
* "oneClick": false,
* "runAfterFinish": false

I'd like that "runAfterFinish" could produce an installer when the latest page of the wizard is the same as the one I see now, but without the checkbox. The page would be useful to notify the user that the app has been installed: I like the "oneClick" installer and I'm a Mac user, but unfortunately I have to produce ad installer which satisfies Windows users expected behaviour.

Moreover, the app can't be use without being externally called using a scheme, so there's no reason to open it after the installation.

**Comment by Pandakls** [comment]
Hi,
I've an alternative problem (i don't know if i should reopen another issue)

What do I need: 
- Allow to choose the installation folder and launch directly the app after this step (No Finish step page)
- No installer at all when updating (=Auto close the finish step)

What I tried : 
- Do some stuff with the option "AutoCloseWindow" for Nsis installer attribute > I didn"t suceed in writing the script
- Passe the option runAfterFinish to true > Does nothing with assisted installer (and false only hides the check box not all the step)
- Remove the FinishSection by overriding the step > I didn't succeed in writing the script
- try to set the "oneClick" Option to {isUpdated}, but this variable is only available in scripts

Thanks in advance for your Help, I'm wondering why in the doc, we allow some macro to be conditionned to isUpdated, and a simple options like that is not available to avoid update assisted installer. Or maybe i'm dumb

Regards.
