### ISSUE TITLE
The windows setup installer can't install

### ISSUE THREAD

**Issue by dingchaoyan1983** [electron-userland/electron-builder#2812]
* **Version**: 
electron-builder: "20.3.1",
electron1.8.3

* **Target**: Windows

![wechatimg1374](https://user-images.githubusercontent.com/7593506/38996011-ce5b05cc-441c-11e8-9448-a1da94eb0172.jpeg)

As see, the Install button is disabled, so can anyone give me a reason

**Comment by develar** [comment]
Please try latest 20.9.2 and attach here your NSIS config, please try to restart Windows.
