### ISSUE TITLE
Mac pkg multi language support for LICENCES

### ISSUE THREAD

**Issue by gengshenghong** [electron-userland/electron-builder#2816]
* **Version**: 20.9.2

* **Target**: Mac, pkg

I've found the support for windows NSIS #1365. It seems this is not supported for mac pkg? I am not familiar with Mac pkg, but I guess it can be supported by pkg format(standard)?

Thanks,
Shenghong

**Comment by pedro-surf** [comment]
=/

**Comment by OrganicChem** [comment]
Essential to a seamless installation, language is quite important. It's hard to see why this has not been resolved for pkg building. Please address this fix.

**Comment by pedro-surf** [comment]
Also, should be able to get selected language from installer to later usage on application itself.
https://github.com/electron-userland/electron-builder/issues/5352
