### ISSUE TITLE
How to pass flags properly

### ISSUE THREAD

**Issue by alex-cory** [electron-userland/electron-builder#2818]
I start my app like this:
`"start-elec-devtools": "./node_modules/.bin/electron . --qtumpath=./qtum/mac/bin --dev --devtools",`

I need to be able to build it like this too
`"build:mac-devtools": "yarn install-dep; ./node_modules/.bin/electron-builder build -m --devtools",`

How to accomplish?

**Comment by develar** [comment]
Duplicates #2712
