### ISSUE TITLE
Where do config options app-bundle-id and app-category-type should be declared?

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#282]
Now that there is no build section in the application package.json where is the right place to put 
app-bundle-id and app-category-type?
I guess under the osx section but since I could not find it anywhere in the docs (they seem a bit out of date) 
Thanks

**Comment by develar** [comment]
Please see #251. What's wrong in docs?

**Comment by demetris-manikas** [comment]
Read it but  still it is not clear to me whether I  should declare app-bundle-id app-category-type under build or under osx. I believe that the options.md should contain the above mentioned parameters.

**Comment by havenchyk** [comment]
@demetris-manikas it should be near the osx or windows, not inside. PR is welcome :)

**Comment by havenchyk** [comment]
```
"build": {  
   "app-bundle-id": "test.test.test",
   "app-category-type": "test.test.test",
   "iconUrl": "test.test.test",
   "osx": {  
      "title": "test.test.test"
   },
   "win": {  
      "authors": "My corp.",
      "noMsi": true
   }
}
```

**Comment by develar** [comment]
Thanks. Docs will be fixed. Under the build. PR — it is not yet documented, but only TS files should be modified — part of the md files will be regenerated automatically on npm run compile.

**Comment by demetris-manikas** [comment]
Thanks to all

**Comment by demetris-manikas** [comment]
@develar 
Trying to create a PR for this little thing should I run npm run compile before committing the options.md or not? 
Also the npm run test fails at several points complaining for missing json-parse-helpfulerror package.

**Comment by develar** [comment]
@demetris-manikas add comments in the source file https://github.com/electron-userland/electron-builder/blob/master/src/metadata.ts#L56 (see other comments for example) and then run compile — options.md will be updated.


Missing package — strange, do you npm 3?

**Comment by demetris-manikas** [comment]
Thanks. I 'll give it a go in the afternoon. 
I used node 4.4.1 (npm 2.14.20). I 'll try 5.1.1 (npm 3.3.12) and I ''ll get back to you.

**Comment by develar** [comment]
> json-parse-helpfulerror

Yes... NPM 2 for some reason doesn't install this package. Please use NPM 3.

(currently, NPM 3 is broken again and our CI OS X tests failed again, it seems NPM is not reliable :().

**Comment by TakenPilot** [comment]
Regarding this example:
```
"build": {  
   "app-bundle-id": "test.test.test",
   "app-category-type": "test.test.test",
   "iconUrl": "test.test.test",
   "osx": {  
      "title": "test.test.test"
   },
   "win": {  
      "authors": "My corp.",
      "noMsi": true
   }
}
```

Why are some in camelCase and some in kebab-case?

**Comment by develar** [comment]
> Why are some in camelCase and some in kebab-case?

Because it is a electron-packager options. I don't yet have time to fix it. Feel free to open PR :)
