### ISSUE TITLE
build .deb failed on Centos

### ISSUE THREAD

**Issue by chzhm159** [electron-userland/electron-builder#2822]
* **electron-builder 20.10.0**: 

* **target deb**: 
* Linux version 3.10.0-693.el7.x86_64 (`builder@kbuilder.dev.centos.org`) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) `#1` SMP Tue Aug 22 21:09:27 UTC 2017
* CentOS Linux release 7.4.1708 (Core)
* **xz (XZ Utils) 5.2.2,liblzma 5.2.2**:
* **tar (GNU tar) 1.26**
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

`[root@localhost tmp.tLmKMoUSMp]# ./node_modules/.bin/electron-builder -l deb
  • electron-builder version=20.10.0-------  • writing effective config file=dist/electron-builder-effective-config.yaml-------  • no native production dependencies-------packager.info.tempDirManager:  TmpDir { debugName: 'packager', tempFiles: [], registered: false }
templateOptions:  { executable: 'asdf', productFilename: 'asdf' }
value is null _this.options:  /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/after-install.tpl
value is null _this.options:  /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/after-remove.tpl
  • packaging       platform=linux arch=x64 electron=1.8.4 appOutDir=dist/linux-unpacked-------outputPath:  /tmp/temp-dir-BQTeHE/0-after-install
config:  #!/bin/bash

`# Link to the binary`
ln -sf '/opt/asdf/asdf' '/usr/local/bin/asdf'

outputPath:  /tmp/temp-dir-BQTeHE/1-after-remove
config:  #!/bin/bash

`# Delete the link to the binary`
rm -f '/usr/local/bin/asdf'

  • building        target=deb arch=x64 file=dist/asdf_1.0.0_amd64.deb-------  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category-------file:  /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm
args:  [ '--verbose',
  '-s',
  'dir',
  '-t',
  'deb',
  '--architecture',
  'amd64',
  '--name',
  'asdf',
  '--force',
  '--after-install',
  '/tmp/temp-dir-BQTeHE/0-after-install',
  '--after-remove',
  '/tmp/temp-dir-BQTeHE/1-after-remove',
  '--description',
  '\n wware',
  '--version',
  '1.0.0',
  '--package',
  '/tmp/workspace/tmp.tLmKMoUSMp/dist/asdf_1.0.0_amd64.deb',
  '--maintainer',
  'Barney Rubble <b@rubble.com>',
  '--url',
  'https://github.com/electron/electron-quick-start#readme',
  '--vendor',
  'Barney Rubble <b@rubble.com>',
  '--deb-compression',
  'xz',
  '--depends',
  'gconf2',
  '--depends',
  'gconf-service',
  '--depends',
  'libnotify4',
  '--depends',
  'libappindicator1',
  '--depends',
  'libxtst6',
  '--depends',
  'libnss3',
  '--depends',
  'libxss1',
  '--license',
  'CC0-1.0',
  '/tmp/workspace/tmp.tLmKMoUSMp/dist/linux-unpacked/=/opt/asdf',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/asdf.png',
  '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/asdf.png',
  '/tmp/temp-dir-BQTeHE/2-asdf.desktop=/usr/share/applications/asdf.desktop' ]
Error: Exit code: 1. Command failed: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm --verbose -s dir -t deb --architecture amd64 --name asdf --force --after-install /tmp/temp-dir-BQTeHE/0-after-install --after-remove /tmp/temp-dir-BQTeHE/1-after-remove --description 
 wware --version 1.0.0 --package /tmp/workspace/tmp.tLmKMoUSMp/dist/asdf_1.0.0_amd64.deb --maintainer Barney Rubble <b@rubble.com> --url https://github.com/electron/electron-quick-start#readme --vendor Barney Rubble <b@rubble.com> --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license CC0-1.0 /tmp/workspace/tmp.tLmKMoUSMp/dist/linux-unpacked/=/opt/asdf /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/asdf.png /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/templates/linux/electron-icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/asdf.png /tmp/temp-dir-BQTeHE/2-asdf.desktop=/usr/share/applications/asdf.desktop
{:timestamp=>"2018-04-24T11:14:14.430381+0800", :message=>"Setting workdir", :workdir=>"/tmp", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.446568+0800", :message=>"Setting from flags: architecture=amd64", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.446751+0800", :message=>"Setting from flags: description=\n wware", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.446831+0800", :message=>"Setting from flags: epoch=", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.446906+0800", :message=>"Setting from flags: iteration=", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.446999+0800", :message=>"Setting from flags: license=CC0-1.0", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447091+0800", :message=>"Setting from flags: maintainer=Barney Rubble <b@rubble.com>", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447177+0800", :message=>"Setting from flags: name=asdf", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447262+0800", :message=>"Setting from flags: url=https://github.com/electron/electron-quick-start#readme", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447360+0800", :message=>"Setting from flags: vendor=Barney Rubble <b@rubble.com>", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447451+0800", :message=>"Setting from flags: version=1.0.0", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.447760+0800", :message=>"Converting dir to deb", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.450007+0800", :message=>"Creating boilerplate changelog file", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.450193+0800", :message=>"Reading template", :path=>"/root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/templates/deb/changelog.erb", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.451209+0800", :message=>"No deb_installed_size set, calculating now.", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.453751+0800", :message=>"Reading template", :path=>"/root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/templates/deb.erb", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.457688+0800", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2018-04-24T11:14:14.702682+0800", :message=>"Creating", :path=>"/tmp/package-deb-build-9adae438c05334ad35e6989b4e616822a7b2bce1b0c9d0c20a17e0b4c954/control.tar.gz", :from=>"/tmp/package-deb-build-9adae438c05334ad35e6989b4e616822a7b2bce1b0c9d0c20a17e0b4c954/control", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.750666+0800", :message=>"tar (child): '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/app-builder-bin-linux/x64/app-builder': Cannot exec: No such file or directory", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.750853+0800", :message=>"tar (child): Error is not recoverable: exiting now", :level=>:info}
{:timestamp=>"2018-04-24T11:14:14.752551+0800", :message=>"Process failed: tar failed (exit code 13). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-7ee35c9b0cacbc93ff44aebab36f8e55ebc0bb7b0c9ecd037368035a876b\", \"-I'/tmp/workspace/tmp.tLmKMoUSMp/node_modules/app-builder-bin-linux/x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-9adae438c05334ad35e6989b4e616822a7b2bce1b0c9d0c20a17e0b4c954/data.tar.xz\", \".\"]", :level=>:error}

    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/builder-util/src/util.ts:126:6
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
From previous event:
    at FpmTarget.build (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/targets/fpm.js:370:7)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/platformPackager.ts:134:24
From previous event:
    at AsyncTaskManager.add (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/platformPackager.ts:126:17)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/platformPackager.ts:117:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at LinuxPackager.pack (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/platformPackager.js:265:7)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/packager.js:605:7)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/graceful-fs/graceful-fs.js:99:16
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/packager.js:532:7)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/packager.ts:289:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/packager.js:491:7)
    at /tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at Object.runCommand (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/tmp/workspace/tmp.tLmKMoUSMp/node_modules/electron-builder/src/cli/cli.ts:28:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`

**Comment by orlandodemauro** [comment]
@vladimiry  @chzhm159  i´m getting the same issue, any update on this?
this is my environment:

 thanks guys

**Comment by vladimiry** [comment]
> {:timestamp=>"2018-04-24T11:14:14.750666+0800", :message=>"tar (child): '/tmp/workspace/tmp.tLmKMoUSMp/node_modules/app-builder-bin-linux/x64/app-builder': Cannot exec: No such file or directory", :level=>:info}

The original error says there is no `/tmp/workspace/tmp.tLmKMoUSMp/node_modules/app-builder-bin-linux/x64/app-builder` file to exec. As far as I understand the current stable electron-builder version depends on `app-builder-bin` but not on `app-builder-bin-linux`. So I guess you are running the outdated electron-builder vesrion. If you use the most recent electron-builder vesrion I can suggest as a quick guess to remove `/home/*****/.cache/electron-builder` and `node_modules`, ie do clean build. If still fails try symlinking app-builder-bin to app-builder-bin-linux.

**Comment by orlandodemauro** [comment]
@vladimiry sorry i intended to mention @develar :) sorry guys for the misunderstanding. btw i´m using the last version of the tool and here there are my logs
[logs.txt](https://github.com/electron-userland/electron-builder/files/3007662/logs.txt)

**Comment by orlandodemauro** [comment]
@vladimiry sorry i intended to mention @develar :) sorry guys for the misunderstanding. btw i´m using the last version of the tool and here there are my logs
[logs.txt](https://github.com/electron-userland/electron-builder/files/3007662/logs.txt)

**Comment by orlandodemauro** [comment]
@develar any suggestion on this? i installed fpm v 1.11.0 but i still get the same error

**Comment by amey91** [comment]
Was anyone able to resolve this issue? @chzhm159 @orlandodemauro

**Comment by fabcotech** [comment]
+1 I have the same

**Comment by mindscratch** [comment]
Same issue when trying to build mattermost-desktop in centos7 docker image.
