### ISSUE TITLE
npm run test tries to run for all platforms.

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#283]
While running npm run tests the winPackagerTest fails.
It is expected but it would be nice not to try runnning tests known to fail.
The console reads
 1 test failed
 3 tests skipped
It is not clear to me whether the skipped tests should be skipped anyway or they did not run due to the aforementioned test failure.

**Comment by develar** [comment]
Skipped tests — it is ok. To run all tests you need to use OS X. So, some tests are skipped — OS X tests on Linux for example.

All tests are expected to be green —  please provide full log (including npm error message to get info about your host OS).

Yes, test suite written in assumption that developer uses 64bit machine.

**Comment by demetris-manikas** [comment]
My mistake. I meant that test suites for windows should not be run on linux since they fail.

**Comment by develar** [comment]
No. Test suite for Windows should be runnable on Linux — just install required system packages. See readme in test directory. Yes, there are no detailed commands for Linux :) but package names are the same. 

Why our CI UNIX agent doesn't run it? Because I doesn't have time to configure it yet :(

**Comment by demetris-manikas** [comment]
After installing all prerequisites I get the following error.
failed with

> 
> Failed with exit code: 255
> Output:
> System.InvalidOperationException: The input package file /home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/win-x64/TestApp.1.0.0.nupkg targets no platform and cannot be transformed into a release package.
> at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func2 releaseNotesProcessor, System.Action1 contentsPostProcessHook) [0x00000] in :0 
> at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in :0 
> at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in :0 
> at Squirrel.Update.Program.main (System.String[] args) [0x00000] in :0 "
> 

contents of npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/dm/.nvm/versions/node/v5.1.0/bin/node',
> 1 verbose cli '/home/dm/.nvm/versions/node/v5.1.0/bin/npm',
> 1 verbose cli 'run',
> 1 verbose cli 'test' ]
> 2 info using npm@3.3.12
> 3 info using node@v5.1.0
> 4 verbose run-script [ 'pretest', 'test', 'posttest' ]
> 5 info lifecycle electron-builder@0.0.0-semantic-release~pretest: electron-builder@0.0.0-semantic-release
> 6 verbose lifecycle electron-builder@0.0.0-semantic-release~pretest: unsafe-perm in lifecycle true
> 7 verbose lifecycle electron-builder@0.0.0-semantic-release~pretest: PATH: /home/dm/.nvm/versions/node/v5.1.0/lib/node_modules/npm/bin/node-gyp-bin:/home/dm/projects/electron-builder/node_modules/.bin:/home/dm/.nvm/versions/node/v5.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dm/etc:/home/dm/Android/Sdk/tools:/home/dm/Android/Sdk/platform-tools:/home/dm/Android/Ndk
> 8 verbose lifecycle electron-builder@0.0.0-semantic-release~pretest: CWD: /home/dm/projects/electron-builder
> 9 silly lifecycle electron-builder@0.0.0-semantic-release~pretest: Args: [ '-c', 'npm run compile && npm run lint' ]
> 10 silly lifecycle electron-builder@0.0.0-semantic-release~pretest: Returned: code: 0 signal: null
> 11 info lifecycle electron-builder@0.0.0-semantic-release~test: electron-builder@0.0.0-semantic-release
> 12 verbose lifecycle electron-builder@0.0.0-semantic-release~test: unsafe-perm in lifecycle true
> 13 verbose lifecycle electron-builder@0.0.0-semantic-release~test: PATH: /home/dm/.nvm/versions/node/v5.1.0/lib/node_modules/npm/bin/node-gyp-bin:/home/dm/projects/electron-builder/node_modules/.bin:/home/dm/.nvm/versions/node/v5.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dm/etc:/home/dm/Android/Sdk/tools:/home/dm/Android/Sdk/platform-tools:/home/dm/Android/Ndk
> 14 verbose lifecycle electron-builder@0.0.0-semantic-release~test: CWD: /home/dm/projects/electron-builder
> 15 silly lifecycle electron-builder@0.0.0-semantic-release~test: Args: [ '-c', 'node ./test/out/helpers/runTests.js' ]
> 16 silly lifecycle electron-builder@0.0.0-semantic-release~test: Returned: code: 1 signal: null
> 17 info lifecycle electron-builder@0.0.0-semantic-release~test: Failed to exec test script
> 18 verbose stack Error: electron-builder@0.0.0-semantic-release test: node ./test/out/helpers/runTests.js
> 18 verbose stack Exit status 1
> 18 verbose stack at EventEmitter. (/home/dm/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
> 18 verbose stack at emitTwo (events.js:87:13)
> 18 verbose stack at EventEmitter.emit (events.js:172:7)
> 18 verbose stack at ChildProcess. (/home/dm/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 18 verbose stack at emitTwo (events.js:87:13)
> 18 verbose stack at ChildProcess.emit (events.js:172:7)
> 18 verbose stack at maybeClose (internal/child_process.js:818:16)
> 18 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 19 verbose pkgid electron-builder@0.0.0-semantic-release
> 20 verbose cwd /home/dm/projects/electron-builder
> 21 error Linux 3.13.0-74-generic
> 22 error argv "/home/dm/.nvm/versions/node/v5.1.0/bin/node" "/home/dm/.nvm/versions/node/v5.1.0/bin/npm" "run" "test"
> 23 error node v5.1.0
> 24 error npm v3.3.12
> 25 error code ELIFECYCLE
> 26 error electron-builder@0.0.0-semantic-release test: node ./test/out/helpers/runTests.js
> 26 error Exit status 1
> 27 error Failed at the electron-builder@0.0.0-semantic-release test script 'node ./test/out/helpers/runTests.js'.
> 27 error Make sure you have the latest version of node.js and npm installed.
> 27 error If you do, this is most likely a problem with the electron-builder package,
> 27 error not with npm itself.
> 27 error Tell the author that this fails on your system:
> 27 error node ./test/out/helpers/runTests.js
> 27 error You can get their info via:
> 27 error npm owner ls electron-builder
> 27 error There is likely additional logging output above.
> 28 verbose exit [ 1, true ]

**Comment by demetris-manikas** [comment]
Did some more research and this is what I came up with.
Unzipping the TestApp...nuget I get the following results
> inflating: TestApp.nuspec          
>   inflating: lib%5Cnet45%5Clocales/am.pak  
>   inflating: lib%5Cnet45%5Clocales/ar.pak  
>   inflating: lib%5Cnet45%5Clocales/bg.pak  
>   inflating: lib%5Cnet45%5Clocales/bn.pak  
>   inflating: lib%5Cnet45%5Clocales/ca.pak  
>   inflating: lib%5Cnet45%5Clocales/cs.pak  
>   inflating: lib%5Cnet45%5Clocales/da.pak  
>   inflating: lib%5Cnet45%5Clocales/de.pak  
>   inflating: lib%5Cnet45%5Clocales/el.pak  
>   inflating: lib%5Cnet45%5Clocales/en-GB.pak  
>   inflating: lib%5Cnet45%5Clocales/en-US.pak  
>   inflating: lib%5Cnet45%5Clocales/es-419.pak  
>   inflating: lib%5Cnet45%5Clocales/es.pak  
>   inflating: lib%5Cnet45%5Clocales/et.pak  
>   inflating: lib%5Cnet45%5Clocales/fa.pak  
>   inflating: lib%5Cnet45%5Clocales/fake-bidi.pak  
>   inflating: lib%5Cnet45%5Clocales/fi.pak  
>   inflating: lib%5Cnet45%5Clocales/fil.pak  
>   inflating: lib%5Cnet45%5Clocales/fr.pak  
>   inflating: lib%5Cnet45%5Clocales/gu.pak  
>   inflating: lib%5Cnet45%5Clocales/he.pak  
>   inflating: lib%5Cnet45%5Clocales/hi.pak  
>   inflating: lib%5Cnet45%5Clocales/hr.pak  
>   inflating: lib%5Cnet45%5Clocales/hu.pak  
>   inflating: lib%5Cnet45%5Clocales/id.pak  
>   inflating: lib%5Cnet45%5Clocales/it.pak  
>   inflating: lib%5Cnet45%5Clocales/ja.pak  
>   inflating: lib%5Cnet45%5Clocales/kn.pak  
>   inflating: lib%5Cnet45%5Clocales/ko.pak  
>   inflating: lib%5Cnet45%5Clocales/lt.pak  
>   inflating: lib%5Cnet45%5Clocales/lv.pak  
>   inflating: lib%5Cnet45%5Clocales/ml.pak  
>   inflating: lib%5Cnet45%5Clocales/mr.pak  
>   inflating: lib%5Cnet45%5Clocales/ms.pak  
>   inflating: lib%5Cnet45%5Clocales/nb.pak  
>   inflating: lib%5Cnet45%5Clocales/nl.pak  
>   inflating: lib%5Cnet45%5Clocales/pl.pak  
>   inflating: lib%5Cnet45%5Clocales/pt-BR.pak  
>   inflating: lib%5Cnet45%5Clocales/pt-PT.pak  
>   inflating: lib%5Cnet45%5Clocales/ro.pak  
>   inflating: lib%5Cnet45%5Clocales/ru.pak  
>   inflating: lib%5Cnet45%5Clocales/sk.pak  
>   inflating: lib%5Cnet45%5Clocales/sl.pak  
>   inflating: lib%5Cnet45%5Clocales/sr.pak  
>   inflating: lib%5Cnet45%5Clocales/sv.pak  
>   inflating: lib%5Cnet45%5Clocales/sw.pak  
>   inflating: lib%5Cnet45%5Clocales/ta.pak  
>   inflating: lib%5Cnet45%5Clocales/te.pak  
>   inflating: lib%5Cnet45%5Clocales/th.pak  
>   inflating: lib%5Cnet45%5Clocales/tr.pak  
>   inflating: lib%5Cnet45%5Clocales/uk.pak  
>   inflating: lib%5Cnet45%5Clocales/vi.pak  
>   inflating: lib%5Cnet45%5Clocales/zh-CN.pak  
>   inflating: lib%5Cnet45%5Clocales/zh-TW.pak  
>   inflating: lib%5Cnet45%5Cresources/app.asar  
>   inflating: lib%5Cnet45%5Cresources/atom.asar  
>   inflating: lib%5Cnet45/natives_blob.bin  
>   inflating: lib%5Cnet45/snapshot_blob.bin  
>   inflating: lib%5Cnet45/d3dcompiler_47.dll  
>   inflating: lib%5Cnet45/ffmpeg.dll  
>   inflating: lib%5Cnet45/libEGL.dll  
>   inflating: lib%5Cnet45/libGLESv2.dll  
>   inflating: lib%5Cnet45/msvcp120.dll  
>   inflating: lib%5Cnet45/msvcr120.dll  
>   inflating: lib%5Cnet45/node.dll    
>   inflating: lib%5Cnet45/vccorlib120.dll  
>   inflating: lib%5Cnet45/xinput1_3.dll  
>   inflating: lib%5Cnet45/content_resources_200_percent.pak  
>   inflating: lib%5Cnet45/content_shell.pak  
>   inflating: lib%5Cnet45/ui_resources_200_percent.pak  
>   inflating: lib%5Cnet45%5Csquirrel.exe  
>   inflating: lib%5Cnet45%5Cicudtl.dat  
>   inflating: lib%5Cnet45%5CLICENSE   
>   inflating: lib%5Cnet45%5CTestApp.exe 

Looks like the .nupkg file has not been created properly but I really don't know where to search.
@develar Any hints or suggestions?

**Comment by develar** [comment]
"targets no platform and cannot be transformed into a release package."

your mono version is outdated. see https://github.com/electron/windows-installer/issues/63#issuecomment-206278075 Please install official recent package `mono-complete` http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

Docs about Linux packages in progress, mostly done. Will be PR tomorrow.

**Comment by develar** [comment]
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update

sudo apt-get install mono-complete
```

**Comment by demetris-manikas** [comment]
Thanks.

**Comment by develar** [comment]
wine:

```
sudo add-apt-repository ppa:ubuntu-wine/ppa
sudo apt-get update
sudo apt-get install wine1.8 tricks
winetricks -q vcrun2013
```

**Comment by develar** [comment]
Docs updated.
