### ISSUE TITLE
NSIS installer both oneClick and perMachine set to false

### ISSUE THREAD

**Issue by giacgbj** [electron-userland/electron-builder#2830]
Could it be possible to implement the scenario where both "oneClick" and "perMachine" are set to false in order to have a wizard installer where the user cannot choose where to install it (and the installation is obviously per-user) but (s)he's assured that the installation has been completed (last wizard page)?

**Comment by develar** [comment]
Have you tried `allowElevation` to `false`?

**Comment by giacgbj** [comment]
I've tried it, but the first page of the wizard still shows both the two options (the first one grayed out). Moreover, the user could still relaunch the installer with elevated privileges and install it per-machine. So the user is not forced to install it per-user.

**Comment by DeekshithShetty** [comment]
@giacgbj Did you get any solution? I also have a similar requirement.

**Comment by DeekshithShetty** [comment]
I could achieve this by creating a custom installer script.

```
!macro preInit
	SetRegView 64
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppData\Programs\${PRODUCT_FILENAME}"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppData\Programs\${PRODUCT_FILENAME}"
	SetRegView 32
	WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppData\Programs\${PRODUCT_FILENAME}"
	WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppData\Programs\${PRODUCT_FILENAME}"
!macroend
```
Then point your nsis include script to the custom script
```
nsis: {
   include: 'build/installer.nsh',
   oneClick: true,
}
```

**Comment by odiseo42** [comment]
@DeekshithShetty Actually your script will help me a lot, but i want to check if the installation has been  done previously perMachine. For context, I've enabled perMachine=true in the past, but i want to make perMachine=false by default in my next releases.

So i want to:
* Check if the installation has been done per machine, and if so, preserve that directory (C:\Program Files)
* Otherwise continue with installation per user.

I'm just wondering how can I know if the installation has been done perMachine previously.

**Comment by DeekshithShetty** [comment]
@odiseo42 Recently VS Code released their User Setup file. They basically uninstalled the perMachine (C:\Program Files) setup and installed a fresh copy in AppData. But I am not aware of how they found out if the app was already installed. [What is VS Code User Setup](https://stackoverflow.com/questions/51928174/what-is-vscode-user-setup-for-windows)
