### ISSUE TITLE
How to  output the different files in different folders ?

### ISSUE THREAD

**Issue by DevidCIC** [electron-userland/electron-builder#2833]
I am using electron-builder so that my electron app gets auto updated.

I am building the app for Windows and Linux OS. But I have the following problem:
The build electron app has to be distinguished in the OS and the CHANNEL. So when I run the electron-builder for Windows the files should land under the folder  ```....packages/win/develop-build/HERE```
And if I do the same for Linux the files should land in ```....packages/linux/develop-build/HERE```.
So that would be ```packages/${os}/${channel}/```

In my package.json I  use ```"output": "../electron-build"```. The problem is I can't do something like ```"output": "../electron-build/${os}/${channel}"```  as this is not allowed. So how can I accomplish this ?

**Comment by develar** [comment]
electron-builder publishes according to publish configuration (https://www.electron.build/configuration/publish), and you can use `${channel}` macro in all publish options, including `path` for S3.

**Comment by develar** [comment]
Reopened — nothing stops us — if user wants simply use `${channel}` macro as output path — we should support it.

**Comment by DevidCIC** [comment]
If output would support macros that would be great. Is there some other solution how I can accomplish what I want ?

My package.json for electron looks like this:
```json
"build": {
    "appId": "electron-builder.%npm_package_name%",
    "directories": {
      "output": "../electron-build"
    },
    "win": {
      "asar": false,
      "icon": "../src/assets/icon/nt-white.ico",
      "publish": [
        {
          "provider": "generic",
          "url": "https://se-dnexec.cic-software.de/ElectronUpdate/${os}/${channel}"
        }
      ]
    },
    "linux": {
      "icon": "../src/assets/icon/nt-white.ico",
      "target": [
        "deb"
      ],
      "publish": [
        {
          "provider": "generic",
          "url": "https://se-dnexec.cic-software.de/ElectronUpdate/${os}/${channel}"
        }
      ]
    }
  },
```
