### ISSUE TITLE
More docs on scripts when building pkg

### ISSUE THREAD

**Issue by amaurymartiny** [electron-userland/electron-builder#2836]
* **Version**: 20.10.0

* **Target**: macos pkg

https://www.electron.build/configuration/pkg#PkgOptions-scripts: I didn't manage to make this work. Are the docs up to date? Am I missing something?

Here are my steps:
- Put an inexistant path to the `scripts` fields under `pkg` -> electron-builder throws a "file not found" error. This proves the field is taken into account.
- Put a folder path in the `scripts` field. In this folder I have one script `script.sh`, which has correct `#!/bin/bash` and chmod a+x permissions (I can run it with `./path/to/script.sh`) -> electron-builder builds the pkg, however the script is not run (Or where should I look to see if it's running?)
- Put directly the path to the script.sh itself in the `scripts` field -> same as point 2.

**Comment by develar** [comment]
Link in the docs — http://macinstallers.blogspot.de/2012/07/scripting-in-installer-packages.html

**The name of the scripts must be “preinstall” and “postinstall”.***
