### ISSUE TITLE
Passing protocol options does not work

### ISSUE THREAD

**Issue by dennyferra** [electron-userland/electron-builder#284]
**electron-packager** supports setting a protocol for OSX apps by setting: **protocol** and **protocol-name** options (https://github.com/electron-userland/electron-packager/blob/cd38cb09c92c234ec07b878b718c6111d2d1d31a/cli.js#L11). When setting these options in package.json electron-builder does not appear to pass them to electron-packager resulting in a plist file that does not contain the corresponding values for the protocol.

Tested this on OSX 10.11.4, node 5.8.0, npm 3.8.0, electron-builder 6.0.0

I believe this may be because the options are not defined in **metadata.ts > interface BuildMetadata**. I'd be happy to submit a fix if anyone can point me in the right direction.

**Comment by develar** [comment]
> I believe this may be because the options are not defined

Yes, but not on our side, but on electron-packager side. I don't see it in the https://github.com/electron-userland/electron-packager I will investigate.

**Comment by dennyferra** [comment]
Looks like there is an issue open, seems like it just needs documentation: https://github.com/electron-userland/electron-packager/issues/121

**Comment by develar** [comment]
@dennyferra So, source code is clear — you should use not CLI arg names, but [option names](https://github.com/electron-userland/electron-packager/blob/303de520cef5a46d61a7a8646e9d83aa079af20a/mac.js#L57). i.e. `protocol` is an object.

**Comment by dennyferra** [comment]
@develar Thank you! That's what I was missing. Works as expected now.

**Comment by giacgbj** [comment]
I tried to use it like this in package.json, but it doesn't produce any effect in Info.plist:

`{
  [...]
  "build": {
    [...]
    "mac": {
      [...]
      "protocols": [
        {
          "name": "AName",
          "schemes": [
            "ascheme"
          ]
        }
      ]
    }
    [...]
  }
}
`

What's wrong?

**Comment by develar** [comment]
@giacgbj Should be in the build, not in the mac. Yes, it is usability bug.

**Comment by giacgbj** [comment]
@develar Thanks! 
IMHO, It would be the proper place if it'd be cross-OS :)
Will it ever be?
