### ISSUE TITLE
Cannot build Linux/AppImage on Windows, getting "TypeError: Cannot match against undefined or null"

### ISSUE THREAD

**Issue by JohnWeisz** [electron-userland/electron-builder#2840]
* **Version**: 20.10.0
* **Target**: linux (AppImage)

Hi. I have the `AppImage` target specified in the `linux.target` array, such as:

**package.json**

```json
{
  "build": {
    "linux": {
      "target": ["AppImage", "zip"]
    }
  }
}
```

When trying to build with `build --linux --x64` on a Windows dev machine, I'm getting the following error (edited for easier reading), but _only_ if `AppImage` is set (it works flawlessly otherwise):

```
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (...electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:31:5)
    ...
```

*[Full console output with stack-trace](https://gist.github.com/JohnWeisz/274ea9dd8823da56f7b8f7f0cf914f9f)*

I've been investigating the mentioned source file, but couldn't trace down the exact cause of this issue. Is it perhaps caused by trying to build a linux AppImage on a Windows dev machine? (I can set up a linux virtual machine if this is a wontfix, so it's not a critical issue for us, but it would be great to build on Windows)

**Comment by develar** [comment]
NodeJS version?

**Comment by JohnWeisz** [comment]
```
node -v
```

Gives `v6.11.2` on the same console `build` was ran from.

**Comment by develar** [comment]
To build AppImage on Windows you need latest LTS release — 8, not old 6.
