### ISSUE TITLE
Errors when building with electron-updater

### ISSUE THREAD

**Issue by trueflywood** [electron-userland/electron-builder#2842]
* **Version**: 20.0.5

* **Target**: windows x64 nsis

When I add an electron-updater to the assembly, I get errors.
```

WARNING in ./node_modules/source-map-support/source-map-support.js
Module not found: Error: Can't resolve 'module' in 'C:\Users\Project\node_modules\source-map-support'

ERROR in ./node_modules/electron-updater/out/AppImageUpdater.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Project\node_modules\electron-updater\out'
ERROR in ./node_modules/electron-updater/out/NsisUpdater.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Project\node_modules\electron-updater\out'
ERROR in ./node_modules/electron-updater/out/windowsExecutableCodeSignatureVerifier.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Project\node_modules\electron-updater\out'

```
 electron-updater@2.21.8

source-map-support@0.5.5

**Comment by amilest7777** [comment]
Hello

there two issues are not related.

1. workaound for source-map-support issue:
I had the same error, i fixed the version of source-map-support to 0.4.3 ("source-map-support": "0.4.3") in the package.json of the electron-updater module.

2. workaround for child_process module in electron:
Add this configutarion in top level of package.json of electron-updater module: browser: { fs: false, child_process: false }
