### ISSUE TITLE
NSIS install for all users (program files), childProcess requires (spawn) run as administrator by Windows

### ISSUE THREAD

**Issue by hatpick** [electron-userland/electron-builder#2843]
I have created a nsis installer for my electron app using the following build:
```
"build": {
        "appId": "my.app.id",
        "asar": false,
        "win": {
            "icon": "icon.png",
            "publisherName": "company inc"
        },
        "directories": {
            "buildResources": "src/electron/build",
            "output": "dist/electron",
            "app": "src/electron"
        },
        "publish": {
            "provider": "generic",
            "url": "my url",
            "channel": "latest"
        },
	"nsis": {            
            "perMachine": true,
            "allowToChangeInstallationDirectory": true,
            "allowElevation": true,
            "oneClick": false
        }
    }
```

When I try to install, windows shows the UAC dialog, and installs the app under "Program Files" folder. When I open the app, electron window shows up and the content is just fine, however the childProcess that I create using "spawn" in the main process does NOT run unless I open the app as "administrator" once. After that all is good, any ideas?

Electron Version: 1.8.4
Electron Builder Version: 20.8.1

**Comment by yft** [comment]
+1

**Comment by Zver64** [comment]
Having the same issue.

**Comment by freddy-daniel** [comment]
But how to make app data for all users instead of user profile?

**Comment by Hari-Muniganti** [comment]
I am facing same issue. when i run the application as admin it is working fine. But when i run as non-admin user it is not working as expected.
In my case it is creating folder and file in C:\Program Files (x86)\app where app folder is created. 
It is giving following errors
**Uncaught Error: EPERM: operation not permitted, open** **Uncaught Error: EPERM: operation not permitted, mkdir**
