### ISSUE TITLE
Allow code signing of third party .exe

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2853]
* **Version**:  Latest

* **Target**: Windows

Allow code signing of third party .exe and elevate.exe in /resources folder.

Context - 
Some systems on windows have strict security policy where in they do not allow any .exe which is NOT code signed to run.
To solve this, the best approach is to code sign all .exe files that are included in the app.

**Comment by develar** [comment]
Please try 20.12.0

**Comment by Ajeey** [comment]
This should go down in history as the fastest turnaround time for a "feature request". Literally around 60 mins. :) 👍
