### ISSUE TITLE
Can not load native module in production

### ISSUE THREAD

**Issue by lvbeck** [electron-userland/electron-builder#2854]
* **19.56.2**: 

* **ia32**: 

Hi,

I want to use a custom native addon module in my electron app. The module is located in 
```
C:\my-application-root-dir\node_modules\myaddon\build\Release\myaddon.node
```
and in src\main\index.js I require my module with relative path:
```
var myaddon = require('../../node_modules/myaddon/build/Release/myaddon')
```
in the package.json, I put my module in dependencies:
```
  "dependencies": {
    "myaddon":"^1.0.0",
  },
```
this config is working in the develop environment.

When I build my app with electron-builder for production, build was successfully and a setup file is generated, and I find the myaddon in unpacked directory under build
```
C:\my-application-root-dir\build\win-ia32-unpacked\resources\app.asar.unpacked\node_modules\myaddon\build\Release\myaddon.node
```
However after I install the application in another PC, A Javascript error occurred in the main process:
```
Cannot open C:\my-application-root-dir\node_modules\myaddon\build\Release\myaddon.node: Error: Uncaught Exception:
Error: Cannot find module .
```

After I search for answers for hours I found something in the document:
```
If you have native addons of your own that are part of the application (not as a dependency), set nodeGypRebuild to true.
```
does this mean, in my case, myaddon is not as a dependency? Should I put my myaddon inside /node_modules or in /src ?

And if I set nodeGypRebuild to true,  the build process will fail, did I make something wrong? 

Or the way I require my custom addon is wrong? 

Any help would be appreciated.

**Comment by lvbeck** [comment]
It seems that node-loader use a hardcore absolute path:
https://github.com/webpack-contrib/node-loader/issues/12

issue solve by replace node-loader with [native-ext-loader](https://github.com/smt116/node-native-ext-loader), I also test node-addon-loader, but it's not working.

webpack.main.config.js:

```
      {
        test: /\.node$/,
        loader: 'native-ext-loader',        
        //use: 'node-addon-loader',
        //use: 'node-loader',
        options: {
          //rewritePath: path.resolve(__dirname, 'dist')
        },           
      }
```

**Comment by yalamber** [comment]
even using native-ext-loader did not work for me, I am using electron forge though.

**Comment by stoefln** [comment]
Why was this closed? I also have the issue...

**Comment by imndx** [comment]
native-ext-loader did not work for me.

**Comment by downace** [comment]
electron-builder@21.0.11, same problem

`native-ext-loader` worked for me

**Comment by Pmjin** [comment]
native-ext-loader did not work for me, too....

**Comment by gdorion** [comment]
@Pmjin What did you end up doing ? I have a similar issue with Windows only on certain machines.

**Comment by Vasanthvivi** [comment]
i am also unable to load native dll using ffi
