### ISSUE TITLE
Change default installation directory value

### ISSUE THREAD

**Issue by stephane-r** [electron-userland/electron-builder#2855]
* **Version**: 20.5.1

* **Target**: Windows, NSIS format

Hi community :slight_smile:

I would like change the default installation directory `C:\Users\UserName\AppData…` to custom path.

I’ve try to add `installer.nsh` with custom path in my `build` folder, but no result : the default path is stay.

```
!macro preInit
SetRegView 64
WriteRegExpandStr HKLM “{INSTALL_REGISTRY_KEY}" InstallLocation "C:\myApp" 
WriteRegExpandStr HKCU "{INSTALL_REGISTRY_KEY}” InstallLocation “C:\myApp”
SetRegView 32
WriteRegExpandStr HKLM “{INSTALL_REGISTRY_KEY}" InstallLocation "C:\myApp" 
WriteRegExpandStr HKCU "{INSTALL_REGISTRY_KEY}” InstallLocation “C:\myApp”
!macroend
```

My `electron-builder.yml` :

nsis:
allowToChangeInstallationDirectory: true
oneClick: false
perMachine: false

Anyone can help me ? :slight_smile:

Thank you community !

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/1961#issuecomment-324743484

Because perMachine is false, you must use `HKCU` in addition (or instead) `HKLM`

**Comment by stephane-r** [comment]
Hi @develar 

I'm sorry, but i've same result with this script too :(

**Comment by eBitzu** [comment]
I have the opposite problem, I want to create a folder in the user home folder and can't figure out the config

`  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "${PROFILE}\${COMPANY_NAME}\${PRODUCT_NAME}"
` 
This doesn't work, $Profile doesn't work... I'm kinda lost here
