### ISSUE TITLE
files property exits with ENOTDIR when copying and renaming single files

### ISSUE THREAD

**Issue by adlk** [electron-userland/electron-builder#2857]
* **Version**: 20.11.1 / 20.8.2

* **Target**: mac (dmg), win (nsis) and linux (tar.gz, .deb)

According to the docs, in v12.1.0, file mappings were introduced: 
> You can use file macros in the `from` and `to` fields as well. `from` and `to` can be files and you can use this to rename a file while packaging.

However, using a `files` configuration like:
```
files:
  - from: app/build/bundle.js
    to: app/build.js
```

Results in:
`Error: ENOTDIR: not a directory, scandir '/Users/foo/project/app/build/bundle.js'` – I've double checked, the file at this location _does_ exist.

**Comment by develar** [comment]
It seems this functionality is broken. I will check it tomorrow CET. Please try workaround:

```
files:
  - from: app/build/bundl*.js
    to: app
```

**Comment by adlk** [comment]
@develar unfortunately the workaround does not work. For now we'll do it within our task runner but it would be great to skip that in favor of using the single file & rename feature.

**Comment by aguynamedben** [comment]
Just ran into this with electron-builder@19.54.0. I get the same error. When I tried the work around, I no longer got the error, but the resulting file (`env`) in my case was still missing from the ASAR archive.

Partial "build" section of my package.json:
```js
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json",
      "templates/",
      {
        "from": "../env.productio*",
        "to": "env"
      }
    ],
```

Thanks for the time you put into Electron. It's awesome.

**Comment by aguynamedben** [comment]
I also tried this and it didn't error but also didn't include the file in the ASAR:
```js
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json",
      "templates/",
      "../env.production"
    ],
```

Maybe it's related to navigating up out of the /app directory?

**Comment by avner-hoffmann** [comment]
any news about this? is it going to be solved?
I can't get the "files" configuration to work, I'm getting the same errors as the folks above. The trick with the glob pattern doesn't seem to work. It seems that the "from" only knows to work with directories, but even when I try to copy the entire directory I get another error: 
> TypeError: Cannot read property 'files' of undefined 

If this options doesn't seem to work at least remove it from the documentation so developers won't fight to make it work when it isn't, it's waisting time

**Comment by liaozhongwu** [comment]
I met the same error, Could you please provide me with some demos about how to rename files?

**Comment by nessup** [comment]
Can also confirm this is still an issue. The documentation states that this should work:

> You can use file macros in the from and to fields as well. from and to can be files and you can use this to rename a file while packaging.

I've gotten around this issue by having the renaming done by an earlier build step.
