### ISSUE TITLE
windows firewall and electron-updater

### ISSUE THREAD

**Issue by vieruu** [electron-userland/electron-builder#2867]
* **Version**: 20.11.1

* **Target**: win

i'm using electron-updater and the windows firewall pop out appears and I'm wondering if clicking cancel would affect the app

**Comment by vieruu** [comment]
elloooo 
anyone here ?

**Comment by develar** [comment]
If outcoming connection will be blocked — yes. I am not aware of such issues. In general, it is ok — but electron-updater doesn't check is connection blocked or not — error is not handled in a smart way.
