### ISSUE TITLE
cannot launch multiple instances of same app with different appId / appId not used for "Application Support" folder on macOS

### ISSUE THREAD

**Issue by rvanmil** [electron-userland/electron-builder#2869]
* **Version**: 20.11.1

* **electron-updater version**: 2.21.10

* **Target**: mac default

I'm using the `--config` flag to make different builds (development, staging, production) of the same application and I have specified different `appId` values in each configuration file (`com.myapp.dev`, `com.myapp.tst`, `com.myapp`). The `package.json` contains a `name` value which is the same on each build.

What I noticed is that when I launch a build (doesn't matter which one), and after that I launch a different build, it will not launch a second instance of the application, but instead focuses the instance which was launched first. So for instance, I launch the DEV build, and when I launch the TST build after that it will not launch the TST build, but it will focus de DEV build instead.

After some searching I also noticed that inside the `~/Library/Application Support` folder a folder is created for my application, but it has the name of the `name` property in the `package.json` file and not the value of the `appId` in the configuration file.
This turned out to be the cause of why it wouldn't let me launch multiple instances of different builds with different `appId` values. Somehow the `name` value in the `package.json` file is used to create this folder and/or makes macOS think it is the same application when launching a different build.

When I create builds with different `name` values in the `package.json` file the problem is solved and I can run different builds at the same time.

I don't know if this is a bug or intended behaviour. In the latter case, is there another way to fix this problem?

**Comment by rvanmil** [comment]
The workaround is to specify `name` in the `extraMetadata` using the same value as used in `appId`. This overwrites the `name` value in the `package.json` inside the built application.
Not sure if this is the way it's supposed to work but it does fix the problem.

**Comment by develar** [comment]
You can use CLI `--config.extraMetata.name`
