### ISSUE TITLE
Question: How do I use electron-builder.env

### ISSUE THREAD

**Issue by qtphan734** [electron-userland/electron-builder#2870]
* **Version**:  v20.11.1

 N/A yet. 

* **Target**:  Windows

This is a question rather than an issue.  In the documentation, it mentioned using electron-builder.env to set the environment variables.  How do I actually use this?

I created an electron-builder.env in my project root directory with 'NODE_ENV=production', but when I ran 'build --dir', it didn't seem to apply when my executable is running. I have  two config files, one for production and one for development.  The app will use the corresponding config based on the NODE_ENV set.

**Comment by develar** [comment]
Applicable only for build, not for your final app.

**Comment by zyf0330** [comment]
How to inject env to runtime?

**Comment by valoricDe** [comment]
@develar Could you elaborate what you mean by `Applicable only for build, not for your final app.`?
I generating a packaged app but the process.env does not contain the variables of the `eletron-builder.env`.
@zyf0330 I read that you can use shell-env for runtime environment access.
