### ISSUE TITLE
electron-updater not reading sha2 key from latest.yml

### ISSUE THREAD

**Issue by SimChenB** [electron-userland/electron-builder#2874]
* **Version**: 16.8.2

* **electron-updater Version**: 2.21.10

* **Target**: Win

Hi,

I'm having an issue with electron-updater : 
It seems that the updater is not able anymore to check sha256  checksum from latest.yml
=> In Provider.ts (method getFileList) we dont read the sha256 checksum ('sha2' key) in latest.yml, so an error is thrown "Update info doesn't contain nor sha256 neither sha512 checksum". 
I'm not sure about how i'm supposed to contribute to correct this, any help would be appreciated.
Thx

**Comment by develar** [comment]
> 16.8.2

Please use latest electron-builder.

**Comment by ryuken73** [comment]
I've got the same error today.
After inserting 1 line to Provider.js, error cleared

line 130
```
  if (updateInfo.path != null) {
    return [{
      url: updateInfo.path,
      sha512: updateInfo.sha512
     ,sha2 : updateInfo.sha2  // add this line to use sha2 value in latest.yml**
    }];
```
