### ISSUE TITLE
electron-updater: using zeit/hazel update server?

### ISSUE THREAD

**Issue by hibiyasleep** [electron-userland/electron-builder#2877]
* **Version**: latest.
* **Target**: Linux ARMv7l.

This is just a quick question, Can I configure `electron-updater` to use with [hazel](https://github.com/zeit/hazel) update server? should I have to implement new provider?

**Comment by Ajeey** [comment]
Why do you need an extra server component. Just publish your electron builds to s3 and point the update url to that bucket.

**Comment by develar** [comment]
https://github.com/zeit/hazel it is workaround. electron-updater doesn't require you to setup and maintain any server.

**Comment by develar** [comment]
https://www.electron.build/auto-update

**Comment by hibiyasleep** [comment]
Just because hazel server is already there. thanks for replies, i'll try s3 publish.
