### ISSUE TITLE
Typo in `EP_PRELEASE` environment variable

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#2878]
The environment variable documented [here](https://github.com/electron-userland/electron-builder/blob/master/docs/configuration/publish.md#githuboptions) has a typo.

It should be `EP_PRELEASE` => `EP_PRERELEASE` The typo is also in the codebase.

**Comment by develar** [comment]
Renamed to `EP_PRE_RELEASE `.

**Comment by develar** [comment]
20.13.2
