### ISSUE TITLE
v2.21.10 can't find module 'debug'

### ISSUE THREAD

**Issue by Picktarget** [electron-userland/electron-builder#2879]
* **Version**: 
v2.21.10

v2.21.10

* **Target**: 
win-x64

**Comment by Picktarget** [comment]
![error](https://user-images.githubusercontent.com/12743709/39762029-321fccfc-530c-11e8-9cdb-121dfa9e3bef.PNG)
error.PNG…]()

**Comment by Picktarget** [comment]
"build": {
    "productName": "AI Tickets",
    "appId": "com.AITickets.client",
    "artifactName": "${productName}-${version}-${os}-${arch}-setup.${ext}",
    "win": {
      "target": "nsis",
      "icon": "build/icons/icon.png"
    },
    "files": [
      "**/*",
      "!**/e2e/**/*",
      "!**/src/**/*",
      "!**/.angular-cli.json",
      "!**/karma.conf.js",
      "!**/protractor.conf.js",
      "!**/tsconfig.json",
      "!**/tslint.json"
    ],
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "deleteAppDataOnUninstall": true
    },
    "directories": {
      "buildResources": "build",
      "output": "release"
    }
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "electron-log": "^2.2.14",
    "electron-updater": "^2.21.10",
    "ng-zorro-antd": "^0.6.15",
    "ngx-electron": "^1.0.4",
    "ngx-perfect-scrollbar": "^5.3.5",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "electron": "^2.0.0",
    "electron-builder": "^20.13.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jslint": "^0.12.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

**Comment by develar** [comment]
It is your application error. If you use debug module, install it. Why did you decide that it is from electron-updater? Is there full stack trace?
