### ISSUE TITLE
After the update version of the system can not be installed under mac

### ISSUE THREAD

**Issue by Luncher** [electron-userland/electron-builder#288]
After the update version of the system can not be installed under mac.

When I double-click the app, the system prompt can not be opened.

In addition, the icons are not displayed correctly

**Comment by Luncher** [comment]
Who can test mac system about it? I do not feel my personal reasons

**Comment by develar** [comment]
> After the update version of the system

Do you mean "update electron-builder version"?

> I double-click the app, the system prompt can not be opened

`.app` file? Is it signed? Does "Open" in the context menu on file works? System Preferences -> Allow Apps downloaded from -> ? 

> the icons are not displayed correctly

Where?

**Comment by Luncher** [comment]
updated the electron-builder as well as electron-prebuilt to the latest version, the system can generate at mac dmg file, but the file can not be opened after generation. 

When I double-click the generated apk file prompt can not be opened.

app file is not signed, the previous version I have compiled success, and can be opened. Is there any log file you can see, I want to know what went wrong the.

**Comment by develar** [comment]
> the generated apk file

we don't generate apk. dmg file is generated. Do you open .dmg or .app? What about "Allow Apps downloaded"?

**Comment by Luncher** [comment]
yes when i click .app .Unable to open the system prompts.

**Comment by Luncher** [comment]
I shot you wait

**Comment by Luncher** [comment]
[img](http://pan.baidu.com/s/1dE5tzJN)

**Comment by develar** [comment]
@Luncher

* System Preferences -> Allow Apps downloaded from -> ?
* Open file using context menu action `Open` — right click on file -> Open .

**Comment by Luncher** [comment]
It has been set to allow downloads from any source

 using context menu action Open Was invalid

**Comment by Luncher** [comment]
After the file extraction app can run. Double-click the app file directly Unable to open tips

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-packager/issues/300

**Comment by develar** [comment]
Set electron-prebuilt version to `"electron-prebuilt": "0.37.3"` as temp workaround.

**Comment by Luncher** [comment]
Icon normal, but still can not open the .app file

**Comment by Luncher** [comment]
I do not know how to do, do you have any suggestions?

**Comment by Luncher** [comment]
I have solved this problem, I fall back electron-builder version 2.11.0, compile it again.

**Comment by develar** [comment]
@Luncher Please see https://github.com/electron-userland/electron-packager/pull/244#issuecomment-211233698

**Comment by Luncher** [comment]
thanks

**Comment by Luncher** [comment]
I'll try

**Comment by develar** [comment]
OS X bug. Just restart.
