### ISSUE TITLE
Build process gets stuck building native windows dependencies

### ISSUE THREAD

**Issue by ianaya89** [electron-userland/electron-builder#2882]
- Version:
    - Node : 8.11.1
    - NPM : 5.6.0
    - Yarn : 1.6.0
    - electron : 1.8.3
    - electron-builder : 20.4.1

- Target: Windows (NSIS)

- Description:
I am trying to build an application, built works great for **linux** and **osx** but **gets stuck on windows**. I don't get any errors, the build process just stay in the step: `rebuilding native dependency name=secp256k1` forever. Actualy I am not event building the app yet, just trying to run `npm i` or `yarn`.

- Logs:

```
Build started
git config --global core.autocrlf input
git checkout -qf c0a029795ab91c46b5226ba31f940cd6e98ccc07
Running Install scripts
Install-Product node 8 x64
Uninstalling node 4.8.7 (x86)...
Installing node 8.11.1 (x64)...
yarn
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-linux@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-mac@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-bloq@1.1.0" has incorrect peer dependency "eslint-config-standard@>= 11".
warning " > eslint-config-bloq@1.1.0" has unmet peer dependency "eslint-plugin-jsdoc@>= 3".
warning " > eslint-config-bloq@1.1.0" has incorrect peer dependency "eslint-plugin-node@>= 6".
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder version=20.5.1
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=keccak
  • rebuilding native dependency name=websocket
  • rebuilding native dependency name=sha3
  • rebuilding native dependency name=secp256k1
```

Thanks a lot for your help.

**Comment by develar** [comment]
1. remove electron-rebuild — not required.
2. do not call `install-app-deps` on CI or for before build. Please try simply run build — rebuild will be done automatically if need.

**Comment by ghadaghada** [comment]
Same problem. @ianaya89  did you find a solution ? Thanks.

**Comment by ianaya89** [comment]
Yes, I could solve it using `yarn` to install deps and run build command.
Before that, I had to install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) => `npm i -g --production windows-build-tools`

**Comment by ianaya89** [comment]
@ghadaghada 

I could solve the issue doing the following:

1. Install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) as global dep: `npm i -g --production windows-build-tools`
2. Remove `node_modules` and use `yarn` to install local deps.
3. Set electron builder as debug mode using an env var: `DEBUG=electron-builder`
4. Run build process using `yarn`.

**Comment by ghadaghada** [comment]
@ianaya89  
when I tried to run the second step you proposed to me I had this error.
![capture](https://user-images.githubusercontent.com/10168565/40519461-eae766b8-5fbf-11e8-9bda-83b1dee37ada.PNG)

**Comment by ianaya89** [comment]
Check if you have installed python and if it is in windows PATH.

**Comment by ghadaghada** [comment]
Thanks you, I added PYTHON to the Path. Then I executed the set DEBUG = electron-builder command and running yarn again but this error appears. 
![capture](https://user-images.githubusercontent.com/10168565/40550782-6668fb96-603b-11e8-9bc9-986d7534fe10.PNG)
