### ISSUE TITLE
Set GitHub Releases body

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#2886]
* **Version**: 20.13.3

* **Target**: macOS

I'm using electron-builder to automatically publish nightly builds of my app to GitHub Releases. Using Travis CI cron job, it builds a new release every day. This works great, but I would like to include some info in the release notes, like what commit it was built on, etc. Could you provide a way to set the body text of the release note? Preferably through a command-line flag. The `body` parameter from https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by develar** [comment]
`-c.releaseInfo.releaseNotes="new features"`
