### ISSUE TITLE
How can I set the OSX app icon?

### ISSUE THREAD

**Issue by cajus** [electron-userland/electron-builder#289]
The documentation only talks about the icon used for the _.dmg_, while the resulting application still has the electron default icon. How can I set the Icon for the App itself?

**Comment by develar** [comment]
It is a critical bug due to electron 0.37.4  Set electron-prebuilt version to "electron-prebuilt": "0.37.3" as temp workaround. See https://github.com/electron-userland/electron-packager/issues/300

**Comment by ccnokes** [comment]
> Set electron-prebuilt version to "electron-prebuilt": "0.37.3" as temp workaround
Does this mean actually use 0.37.3 as a workaround or just set the package.json to that?

**Comment by develar** [comment]
@ccnokes It is already fixed (but you must use electron 0.37.4+). May be https://github.com/LinusU/node-appdmg/issues/84#issuecomment-197426861 is your issue?

**Comment by ccnokes** [comment]
@develar Ok, I'm using electron 0.37.8 and electron-builder 2.8.2 (I know I'm on an old version) and was seeing the issue. So you think upgrading to the latest electron-builder fix the issue for me or is something  else going on? 

It looks like there's some breaking changes upgrading from 2.8.2 so I was hoping to avoid it if possible but I'll bite the bullet if needed. 

Thanks!

**Comment by develar** [comment]
@ccnokes yes, it is fixed in the 3.5.0+.

**Comment by framerate** [comment]
> The documentation only talks about the icon used for the .dmg, while the resulting application still has the electron default icon. How can I set the Icon for the App itself?

I'm seeing this on builder 3.17.1 and electron 0.37.8. Is this a known issue?

**Comment by nickdima** [comment]
Is it possible to have separate icons for app and mounted dmg? I don't want the mounted dmg to have the same icon as the app.

**Comment by develar** [comment]
@nickdima `osx.icon` is only and only DMG icon. So, just set it to path to icon.

**Comment by nickdima** [comment]
great, thanks!
