### ISSUE TITLE
The `releaseInfo.releaseNotes` config does not set the GitHub Releases body

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#2890]
* **Version**: 20.13.3

* **Target**: macOS

I'm using this:

```
electron-builder --mac --linux --win --publish=always --config.releaseInfo.releaseNotes=foo
```

But the body in the GitHub Releases item is not set: https://github.com/lukechilds/hyperdex-nightlies/releases/tag/v0.0.0-074605b-18.5.10.916 However, the `latest.yml` file does contain the release notes, so it's clear that it's the GitHub part that's not working.

**Comment by mxstbr** [comment]
Seeing the same thing!

**Comment by jetlej** [comment]
+1

**Comment by sindresorhus** [comment]
Please keep it open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by jjustin3** [comment]
It appears as if the body and title are never even applied when creating the release. The only place this is done is when creating the updateInfo Yaml file.

https://github.com/electron-userland/electron-builder/blob/7b8fa16485a0740a4902c9174b57588b04ee04e8/packages/electron-publish/src/gitHubPublisher.ts#L207-L212

**Comment by jjustin3** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
@stale 🤷‍♂️

**Comment by cawa-93** [comment]
So did anyone find solutions, Workarounds or something else? Did only the @stale bot bravely try to solve this issue?

**Comment by miguelhrocha** [comment]
I think @jjustin3 has a very good point, I'll create a PR to send the releaseNotes as the body of the GitHub release

**Comment by baparham** [comment]
I was under the impression this flag was for the release information that goes into a windows .exe file (via rcedit or something). Has anyone actually dug into the code to find out where this config.releaseInfo object is used?
