### ISSUE TITLE
Build stucks building native addon

### ISSUE THREAD

**Issue by akimasa** [electron-userland/electron-builder#2892]
* **Version**: 20.13.3

* **Target**: Windows x64 (zip)

Similar to #2882
Build stucks when rebuilding native addon.
Build works well with `$env:DEBUG="electron-builder"`
Looks like there are a lot of warning output from msbuild and they are stuck

* log
```
> git clone https://github.com/akimasa/electron-quick-start
> cd .\electron-quick-start\
> npm i
> npm run build.win32

> electron-quick-start@1.0.0 build.win32 C:\Users\Akimasa\Documents\work\tmp\electron-quick-start
> electron-builder --windows=zip --x64 ./ sample

  • electron-builder version=20.13.3
  • writing effective config file=dist\electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
```
stucks here.

**Comment by lubo08** [comment]
Same problem. Pleas help somebody.

**Comment by ianaya89** [comment]
@akimasa @lubo08 Check if the solution I used in #2882 helps

**Comment by lubo08** [comment]
This work $env:DEBUG="electron-builder", but it is nasty workaround should work even is not in debug mode. :)

**Comment by akimasa** [comment]
I know it works with `$env:DEBUG="electron-builder"`.(I have mentioned in my first post)
This temporary solves the problem.
Not good for parmanent solution.
I hope this issue can be fixed.

https://github.com/electron-userland/electron-builder/blob/d649815e62c44e60fed624077464711cb3cf5462/packages/electron-builder-lib/src/util/yarn.ts#L88
https://github.com/electron-userland/electron-builder/blob/d649815e62c44e60fed624077464711cb3cf5462/packages/builder-util/src/util.ts#L204
https://github.com/electron-userland/electron-builder/blob/d649815e62c44e60fed624077464711cb3cf5462/packages/builder-util/src/util.ts#L211

Maybe we need passing some option to spawn function.
Output from build tool need to redirect somewhere.
If you forgot receiving output, it works when output buffer is not full, but stop working after buffer is full.
