### ISSUE TITLE
appUpdater.quitAndInstall() app closing order is not as described in the docs when running on windows

### ISSUE THREAD

**Issue by avner-hoffmann** [electron-userland/electron-builder#2893]
- **Versions:**

electron-builder: 20.0.4
electron-updater: 2.20.1 / 2.21.10 (latest)

- **Target**:  Windows x64 (7, 10)

From electron-builder documentation:

> Note: autoUpdater.quitAndInstall() will close all application windows first and only emit before-quit event on app after that. This is different from the normal quit event sequence.

This is corresponding to the behavior described in Electron's auto updater docuementation.

However, this is not the case when running on windows (both 7 and 10).
I ran some tests and from my logs I specifically see that after running updater.quitAndInstall(), the before-quit event runs before my window's close event, which is not the case when my app is running on macOS (behaving well as documented).

Is this issue known and/or solved in a version I don't have?
I'm sure I'm not the first one to find out about this....

**Comment by develar** [comment]
Sorry I don't understand what the issue you have. Is updater misfunction as result? Please provide updater debug logs (https://www.electron.build/auto-update#debugging).

Related: #2896

**Comment by avner-hoffmann** [comment]
I can provide my logs but it won't help you since the output is a flow I'm having in my app.

The issue is as simple as I wrote. electron-updater doesn't behave as described in the docs when the app is running on Windows. Please read the attached docs.
I'm relying on the quit event sequence as described in the docs, but since electron-updater doesn't behave as described I'm resulting in that my app is trying to update and install twice, which results in an update failure and my app is unable to update itself
