### ISSUE TITLE
Improve Windows installer task kill process (related to child processes)

### ISSUE THREAD

**Issue by tzarebczan** [electron-userland/electron-builder#2894]
* **Version**: 20.13.3

electron-updater: 2.21.4

* **Target**: Windows

The upgrade process was changed (https://github.com/electron-userland/electron-builder/issues/2516) to use taskkill which works great for us but we are having trouble when we run our installer while the app is running. We get the prompt to close LBRY, which occurs, but it leaves one of our grandchild  processes running (which is not good because we are trying to update that running file). 

Can the installer process be updated to use the same mechanism for killing processes as the upgrade process?  Haven't dug into the code to see what the differences are, but I'm assuming it's not the same because of the different behavior. 

Donating...

**Comment by develar** [comment]
Both uses the same logic to kill. Let's investigate #2896 and then maybe this issue will gone.

**Comment by tzarebczan** [comment]
I'll give the newer updater a shot and report back, but I don't expect this behavior to change (it's always worked like this).

**Comment by tzarebczan** [comment]
@develar this still exists even though https://github.com/electron-userland/electron-builder/issues/2896 was fixed by upgrading the updater version. This is fairly easy to reproduce in our environment. When I run the installer while the app is running, I'm left with a single lbrynet-daemon.exe process (it starts with 2, a shell processes which launches the main one) that is not killed off. The in-app upgrade process kills both. 

Any thoughts? Let me know if I need to give you more info/example.

**Comment by tzarebczan** [comment]
@develar any updates?

**Comment by tzarebczan** [comment]
@develar can you take a look at this one again? Were there any changes recently which may have fixed it? Should be easy to reproduce.

**Comment by tzarebczan** [comment]
@develar any updates?

**Comment by tzarebczan** [comment]
@develar this is still happening on 20.22.0. This is how the app normally starts up:
![install1](https://user-images.githubusercontent.com/8120721/43423699-1541340e-941b-11e8-8494-b0bfc8cd1409.jpg)

When clicking OK, LBRY.exe related processes shut down, but a single lbrynet-daemon.exe stays open. The result is:
![install2](https://user-images.githubusercontent.com/8120721/43423728-2928d620-941b-11e8-8c88-01f0f83adda3.jpg)

This causes a few issues:
1) The lbrynet-daemon.exe files does not get updated because it's in use (we frequently update it). 
2) If a user closes the LBRY app now, lbrynet-daemon.exe will continue running
3). If we do update lbrynet-daemon.exe and a user runs the installer manually while LBRY is open (this scenario),  they will then need to end task it manually, and re-rerun the installer. 

When updating the app via electron-updater/auto update, the lbrynet-daemon.exe processes are killed completely. 

Can you please take another look?

**Comment by develar** [comment]
Sorry that this is not yet addressed.

**Comment by kauffj** [comment]
@develar is it possible to hook into anything during the auto update process so that we can kill this ourselves?

**Comment by tzarebczan** [comment]
@develar Any updates on this? Any comments to the above question?

**Comment by tzarebczan** [comment]
@develar any help please?

**Comment by tzarebczan** [comment]
@develar We keep running into this problem with every update and would really appreciate some assistance. Either please fix the software or give us a way to run something after a successful update. I've also tried reaching out on Slack to no avail. Sent another donation.

**Comment by develar** [comment]
@tzarebczan Please check 21.1.6 (it is not announced, but released as next for you).

**Comment by tzarebczan** [comment]
Thank you, we'll check this out and let you know. Does this just solve the problem or let us run a script. I'll see if there is any documentation.

**Comment by tzarebczan** [comment]
I saw the code, it looks like it should fix the issue of not killing the process. We'll give it a shot! Thank you again!!!!

**Comment by tzarebczan** [comment]
Actually, now that I looked at the original issue, I'm not sure we have control over this. This is the case when our app is already running, and the installer is launched. The installer decides to kill the app, which then doesn't remove the child subprocesses.
