### ISSUE TITLE
Application starts before NSIS installer is closed.

### ISSUE THREAD

**Issue by dscalzi** [electron-userland/electron-builder#2895]
* **Version**:  20.13.3

* **election-updater**: 2.21.10

* **Target**: nsis x64

After an auto-update, the application starts immediately, while the NSIS installer is still open. On the installer, you are given an option to open the application when finished. This option is enabled by default. Closing the installer with this option enabled will open another instance of the application.

Before the auto-update, I'm only calling
```javascript
autoUpdater.quitAndInstall()
```

I don't think this is expected behavior. I'm currently on Windows 10.

**Comment by develar** [comment]
@dscalzi @computerquip-streamlabs Do you use assisted installer or one-click?

**Comment by dscalzi** [comment]
Assisted installer

**Comment by develar** [comment]
Duplicates #2619
