### ISSUE TITLE
Windows upgrade triggers installer twice (2 UAC screens)

### ISSUE THREAD

**Issue by tzarebczan** [electron-userland/electron-builder#2896]
* **Version**: 20.13.3

electron-updater: 2.21.4

* **Target**: Windows

See behavior of current upgrade process here: https://github.com/lbryio/lbry-app/issues/1423
It looks like the upgrade process kicks off the installer twice - once for the regular upgrade process and once for the "install on close" upgrade. This results in a UAC prompt that appears twice and can be confusing to users. If clicked through quickly, install succeeds, but if you wait on the 2nd UAC, it may end up closing the other installer/running app. 

Could possibly be related to https://github.com/electron-userland/electron-builder/issues/2893 ? 

Will donate

**Comment by develar** [comment]
@tzarebczan Thanks for donation. 

I have inspected your code — looks correct.
1. Please update electron-updater to `2.21.10` There was some related to your case changes.
2. If error will be reproducible for 2.21.10 (old app and new app both have this version), please attach  debug log (please see https://www.electron.build/auto-update#debugging).

**Comment by tzarebczan** [comment]
@develar this is fixed on 2.21.10, no more dual UAC prompts!
