### ISSUE TITLE
Redundant / diverged: README.md !== docs/README.md

### ISSUE THREAD

**Issue by felixrabe** [electron-userland/electron-builder#2898]
https://github.com/electron-userland/electron-builder/blob/master/README.md
and
https://github.com/electron-userland/electron-builder/blob/master/docs/README.md

seem to have been updated independently. I suggest to merge them and make one of them (either a symlink or)* a Markdown file containing just

    See (link to other README.md)

(\* Symlink might be a bad idea if there are any relative links (didn't check this fully).)

If you like this idea, I could give it a go and submit a PR. Caveat: I don't personally use electron-builder at the moment, but I'm investigating Electron-related build tools.

**Comment by develar** [comment]
One is used as GitHub project readme, another one as site readme. Now they are different :)
