### ISSUE TITLE
Firewall always ask for connection permission when the app open

### ISSUE THREAD

**Issue by DannyFeliz** [electron-userland/electron-builder#2909]
* **Version**: 20.9.2

* **Target**: windows/portable
<hr>

Hi, I'm using [socket.io](https://socket.io/) to keep a real-time connection with a backend service but I have an issue with the firewall. Because this is a portable app everytime the app is opened it looks that it is extracted in the temporary folder, which will generate a new folder (so the path to the app will be different) in every run. which will make the firewall think that this is another app asking for the connection permissions. How can I change the extraction path when I run the app?

(This is the screen that I get every time I run the app)
![image](https://user-images.githubusercontent.com/5460365/40011621-5cd8a02c-5776-11e8-9cac-54608196d0a4.png)

This is my socket.io configuration
```js
const io = require("socket.io")(6524);

io.on("connect", socket => {
    socket.on("notification", data => {
        EventBus.$emit("notifications", JSON.parse(data));
    });
});
```

My build settings in `package.json`
```js
    "build": {
        "productName": "xxx",
        "appId": "xxx.xxx.xxx",
        "directories": {
            "output": "build"
        },
        "files": [
            "dist/electron/**/*",
            "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples,*.d.ts}",
            "!**/node_modules/.bin",
            "!**/*.{o,hprof,orig,pyc,pyo,rbc}",
            "!**/._*",
            "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}",
            "!**/node_modules/search-index/si${/*}"
        ],
        "win": {
            "icon": "build/icons/myicon.ico",
            "target": "portable"
        }
    },
```

Any idea about how at least I could specify an extraction path or make this extract it the execution folder?

**Comment by DannyFeliz** [comment]
@develar any idea about this?

**Comment by DannyFeliz** [comment]
Well I had to get rid of the portable option and use the unpacked version

**Comment by agjs** [comment]
Any help on this one? We are getting exactly the same thing only when using a portable version.

**Comment by agjs** [comment]
Hi @DannyFeliz. This issue has been fixed now as your portable application can reside in a specific location. Right now, you should only get a firewall window when you run the portable for the first time.

**Comment by agjs** [comment]
@develar You should close this one too as it's the same issue as #3799

**Comment by DannyFeliz** [comment]
@agjs I'm glad you guys got it 🎉
