### ISSUE TITLE
Code Signing: Download Certificate Error

### ISSUE THREAD

**Issue by dennyferra** [electron-userland/electron-builder#291]
I'm building an Electron app and using electron-builder to build installer for Windows. I'm trying to use the `CSC_LINK` and `CSC_KEY_PASSWORD` environment variables to sign the app as described in the README.

My first attempt returns the following error:

> Unhandled rejection Error: unable to verify the first certificate
> at Error (native)
> at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
> at emitNone (events.js:80:13)
> at TLSSocket.emit (events.js:179:7)
> at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
> at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
> From previous event:
> at Object.downloadCertificate (C:\projects\presentation\Electron\node_modules\electron-builder\src\codeSign.ts:97:18)
...

I did some googling and ran across a few people setting the following ENV variable:  `NODE_TLS_REJECT_UNAUTHORIZED=0` I tried it and now get a different error:

> Unhandled rejection Error: Request error, status 400: Bad Request
at ClientRequest.<anonymous> (C:\projects\presentation\Electron\node_modules\electron-builder\src\httpRequest.ts:36:16)
...

I'm not sure this is an electron-builder issue since the trace points to Node's https module however I'm posting here as suggested from my SO post (http://stackoverflow.com/questions/36315668/electron-builder-code-signing-download-certificate-error/)

Build env: Windows 10 using node 5.9.0. Thanks

**Comment by demetris-manikas** [comment]
Well... The docs are not clear. I believe the method described for code signing works only for OSX. To sign your windows app you will need to get hold of a Microsoft code signing certificate and add the following entries in your build.win section
      "certificateFile": "PATH_TO_WindowsCodeSigning.pfx",
      "certificatePassword": ""
 as described in https://github.com/electron/windows-installer#usage

**Comment by develar** [comment]
@demetris-manikas "OS X and Windows code singing is supported." — Windows supported.

@dennyferra issue is different — we cannot even download certificate file.

`CSC_LINK` — do you use Google Drive or something else? Is it HTTPS link?

**Comment by dennyferra** [comment]
> CSC_LINK — do you use Google Drive or something else? Is it HTTPS link?

Yes I used Google Drive url and HTTPS (same as described in README with different id param). My `CSC_KEY_PASSWORD` also has no special characters (just letters and numbers if that matters).

I don't know if this helps at all but I have Git/MinGW installed and when running a curl request (verbose) I also get a 400 Bad Request (*** for id):

> $ curl -v https://drive.google.com/uc?export=download&id=***
> * timeout on name lookup is not supported
> *   Trying 172.217.0.14...
> * Connected to drive.google.com (172.217.0.14) port 443 (#0)
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> *   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
>   CApath: none
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *        subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.google.com
> *        start date: 2016-03-23 19:41:18 GMT
> *        expire date: 2016-06-15 19:20:00 GMT
> *        subjectAltName: drive.google.com matched
> *        issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
> *        SSL certificate verify ok.
> GET /uc?export=download HTTP/1.1
> Host: drive.google.com
> User-Agent: curl/7.43.0
> Accept: */*
>
> HTTP/1.1 400 Bad Request
> Content-Type: text/html; charset=UTF-8
> P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
> x-chromium-appcache-fallback-override: disallow-fallback
> Date: Wed, 06 Apr 2016 00:37:02 GMT
> Expires: Wed, 06 Apr 2016 00:37:02 GMT
> Cache-Control: private, max-age=0
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> Server: GSE
> Alternate-Protocol: 443:quic
> Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
> Accept-Ranges: none
> Vary: Accept-Encoding
> Transfer-Encoding: chunked
>
```
<HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Bad Request</H1>
<H2>Error 400</H2>
</BODY>
</HTML>
```
> Connection #0 to host drive.google.com left intact
> id: =***: no such user

**Comment by develar** [comment]
@dennyferra Please ry to upload to Dropbox. If `curl` cannot fetch it means that error not on our side.

**Comment by dennyferra** [comment]
Looks like Dropbox works. I still had to set `NODE_TLS_REJECT_UNAUTHORIZED=0` and `CSC_LINK` needed to be set without quotes:

Success:
`SET CSC_LINK=https://www.dropbox.com/s/path/to/file.p12?dl=1`
Failed:
`SET CSC_LINK="https://www.dropbox.com/s/path/to/file.p12?dl=1"`

Installer now gets signed with the certificate. Thanks for the help @develar
