### ISSUE TITLE
nsis: oneClick/assistedInstaller APP_FILENAME inconsistency 

### ISSUE THREAD

**Issue by bennol** [electron-userland/electron-builder#2911]
* **Version**: 20.13.2

* **Target**: nsis

I am using a two package.json structure:
The inner `package.name` is configured as `com.company.applicationname` and `config.productName` is set as `ApplicationName`.

--- 

When building with 
```
"nsis": {
  "oneClick": true,
  "perMachine": false
}
```
 the nsis environment variable `APP_FILENAME` is `com.company.applicationname ` resulting in an installation directory under `%LOCALAPPDATA%\Programs` named the same. 

#### Problem
When building additional installers using `oneClick = false` or `perMachine = true` the `APP_FILENAME` is modified to match the `productFilename`, resulting in an installation directory named `ApplicationName`. 
https://github.com/electron-userland/electron-builder/blob/2fb0ee2b9f27e716e9e62a0690f76137c6394246/packages/electron-builder-lib/src/targets/nsis/NsisTarget.ts#L147

This leads to inconsistent results when using the 
- oneClick installer (installs to  `%LOCALAPPDATA\Programs\com.company.applicationname `)
- assisted installer with the `only current user` setting or alternatively `/currentUser` argument (installs to `%LOCALAPPDATA\Programs\ApplicationName`) 

My questions are:
- What is the way to go, to force the oneClick installer naming to be in line with the rest? Should the electron-builder behavior be changed?
- Is there a direct way to override the installation dir name/APP_FILENAME? Should there be?

**Comment by thetroy** [comment]
Just tripped over this too.

Why does setting `oneClick` prevent the use of `productFilename` @develar ? 
It's been like that since this was added:
https://github.com/electron-userland/electron-builder/commit/2539cfba20dc639128e75c5b786651b652bb4b78

**Comment by develar** [comment]
>  to force the oneClick installer naming to be in line with the rest

Better to use name without space, better to use name that not changed so often as product name. That's why `isTryToUseProductName` is set to `!oneClick || isPerMachine`.

> Is there a direct way to override the installation dir name/APP_FILENAME? 

No, but pull request will be accepted.

Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
