### ISSUE TITLE
It's not clear how to get differential updates on macOS/Windows

### ISSUE THREAD

**Issue by iffy** [electron-userland/electron-builder#2912]
* **Version**: 20.8.2 and 20.13.3

* **electron-updater**: 2.21.4

* **Target**: macOS/Windows/Linux

My app is not doing differential updates (I can tell because none of the `.blockmap` files have been downloaded) and I don't see anything in the docs that explains how to get them to work: https://www.electron.build/configuration/publish (searching the page for "differential" yields only one result).

Are differential updates not live yet?

**Comment by develar** [comment]
NSIS now supports differential updates, macOS soon.

**Comment by sandeep1995** [comment]
I don't find detailed documentation around this. Like what kind of server I can use to enable this.

**Comment by AleksMeshkov** [comment]
> NSIS now supports differential updates, macOS soon.

any updates for OS X?

**Comment by wslp12** [comment]
> NSIS now supports differential updates, macOS soon.

Is mac currently not supported?

**Comment by RiggedToBlow** [comment]
can somebody please answer this question 😅
