### ISSUE TITLE
electron-builder error

### ISSUE THREAD

**Issue by 819460357** [electron-userland/electron-builder#2915]
> application-name@0.0.1 dist F:\workspace\桶装水项目\trunk\code\front_end\pc\merch-end\electron-app
> electron-builder --win --x64

  • electron-builder version=20.13.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=packers\electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.4 appOutDir=packers\win-unpacked
  • default Electron icon is used reason=application icon is not set
  • no native production dependencies
  • packaging       platform=win32 arch=ia32 electron=1.8.4 appOutDir=packers\win-ia32-unpacked
  • building        target=nsis file=packers\Zhaizhishe Setup 0.0.1.exe archs=x64, ia32 oneClick=true
Error: C:\Users\Administrator\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=org.lzj.demo1"
Command line defined: "APP_GUID=bd0576c0-c762-56de-9d81-9c215af5daac"
Command line defined: "PRODUCT_NAME=Zhaizhishe"
Command line defined: "PRODUCT_FILENAME=Zhaizhishe"
Command line defined: "APP_FILENAME=application-name"
Command line defined: "APP_DESCRIPTION=��һ���汾"
Command line defined: "VERSION=0.0.1"
Command line defined: "PROJECT_DIR=F:\workspace\Ͱװˮ��Ŀ\trunk\code\front_end\pc\merch-end\electron-app"
Command line defined: "BUILD_RESOURCES_DIR=F:\workspace\Ͱװˮ��Ŀ\trunk\code\front_end\pc\merch-end\electron-app\build"
Command line defined: "APP_32=F:\workspace\Ͱװˮ��Ŀ\trunk\code\front_end\pc\merch-end\electron-app\packers\application-name-0.0.1-ia32.nsis.7z"
Command line defined: "APP_32_NAME=application-name-0.0.1-ia32.nsis.7z"
Command line defined: "APP_32_HASH=F2207FC67A2754BF5C086E418FCF0EC743B7295F88A95CF9EFB8E0AD48D0D8F4C8FF6EBE1BBE9675AFDC00274FEAC2FEFDE54581E38DF96894D94A197C55CD3C"
Command line defined: "APP_64=F:\workspace\Ͱװˮ��Ŀ\trunk\code\front_end\pc\merch-end\electron-app\packers\application-name-0.0.1-x64.nsis.7z"
Command line defined: "APP_64_NAME=application-name-0.0.1-x64.nsis.7z"
Command line defined: "APP_64_HASH=64CC9DEC71D2F3DFC8C4B4F6A8692EBF489832368FCD2828EF302836D8BB24EA0E7E4BF378A007F2E1E7581F8F71D56FC1DC47EF4258D892357C91A98CEF23DA"
Command line defined: "COMPANY_NAME=lzj"
Command line defined: "APP_PRODUCT_FILENAME=Zhaizhishe"
Command line defined: "APP_INSTALLER_STORE_FILE=Zhaizhishe\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=Zhaizhishe"
Command line defined: "UNINSTALL_DISPLAY_NAME=Zhaizhishe 0.0.1"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=F:\workspace\Ͱװˮ��Ŀ\trunk\code\front_end\pc\merch-end\electron-app\packers\.__uninstaller-nsis-application-name.exe"
Processing config: C:\Users\Administrator\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
!include: could not find: "F:\workspace\桶装水项目\trunk\code\front_end\pc\merch-end\electron-app\node_modules\electron-builder-lib\templates\nsis\include\StdUtils.nsh"
Error in script "<stdin>" on line 1 -- aborting creation process

    at ChildProcess.childProcess.once.code (F:\workspace\桶装水项目\trunk\code\front_end\pc\merch-end\electron-app\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

What should I do？

**Comment by xiaonanhaier** [comment]
Me too. Have you solved the problem?

**Comment by mbarison** [comment]
I think it has to do with the fact that you are using chinese charaters in your path, see this:
https://github.com/electron-userland/electron-builder/issues/2197
