### ISSUE TITLE
electron-builder install-app-deps can't find Pre-built binaries

### ISSUE THREAD

**Issue by Supamiu** [electron-userland/electron-builder#2916]
* **Version**:  20.13.3

* **Target**: No target specified

Additional informations: 

  * **platform**: win32 arch=x64
  * **Node**: 9.5.0
 * **OS**: Windows 10 v1709, build 16299.431

When trying to run `electron-builder install-app-deps`, an error pops saying that no binaries are found for grpc@1.10.1 and electron@2.0.0. Antivirus disabled (saw that this error sometimes appeared because of antivirus).

Error output:
> node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/electron-v2.0-win32-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and electron@2.0.0 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! build error 

Tested with both npm 6.0.1 and yarn 1.6.0, same error on both.

**Full Error log** (Created a gist to avoid very big issue comment): https://gist.github.com/Supamiu/c4dc30844cbe8946619431e1381fe5e2

**Comment by Supamiu** [comment]
This issue is only present with electron 2.0.0, but I have display issues with electron 1.8.4 so a fix is definetly needed.

**Comment by develar** [comment]
Please ask grpc module to 
1. use https://www.npmjs.com/package/prebuild instead of node-pre-gyp
2. provide prebuilds for electron 2.

As workaround, please try to set `buildDependenciesFromSource` to `true` (electron-builder config.)

**Comment by Supamiu** [comment]
@develar By "ask grpc module", do you mean I should create an issue on their repository?

**Comment by develar** [comment]
@Supamiu Yes, I think they don't yet provide prebuilt for electron 2.
