### ISSUE TITLE
Cancellation Token parameters and download Promise are being null/empty in UpdateCheckResult

### ISSUE THREAD

**Issue by sowjanya11** [electron-userland/electron-builder#2917]
* **Version**: 20.10.0

* **Version**: 2.21.8

* **Target**: dmg + zip (MAC)

I have done code signing for my electron app, and got electron-updater events working, but couldn't cancel the update download while the download is in progress. Getting cancellationToken in updateCheckResult as 
cancellationToken: { "domain": null, "_events": {}, "_eventsCount": 0, "parentCancelHandler": null, "_parent": null, "_cancelled": false}

**Comment by jason-zuo** [comment]
do you have answer, i face the same problems

**Comment by sowjanya11** [comment]
import { CancellationToken } from "electron-builder-http"

const cancellationToken = new CancellationToken()
autoUdater.download(cancellationToken)

// stop download
cancellationToken.cancel()

This worked for me @jason-zuo 
Reference  https://github.com/electron-userland/electron-builder/issues/1150

**Comment by develar** [comment]
```
import { CancellationToken } from "electron-updater"

const cancellationToken = new CancellationToken()
autoUdater.downloadUpdate(cancellationToken)

// stop download
cancellationToken.cancel()
```

**Comment by develar** [comment]
Duplicates #1150
