### ISSUE TITLE
cli.js unexpected token function while trying to build windows

### ISSUE THREAD

**Issue by joshualeduc** [electron-userland/electron-builder#2919]
20.13.4, 20.13.0, 20.12.0

na

windows 64 portable 

I recently cleaned out my node_modules folder and npm installed everything again. After doing so, when I run "npx electron-builder build -w", I get the error

...\node_modules\electron-builder\out\cli\cli.js
Unexpected token function

It's been awhile now since I last updated my packages, and I'm not sure how to go about debugging this.

**Comment by joshualeduc** [comment]
Nevermind sorry, after seeing another error from the read-config-file package I realized that my errors were being caused by my version of node. Moving to the latest LTS (v8) from v6 solved my issues.

**Comment by pravin-d** [comment]
Thanks man.. Got the same error.. fixed it the same way.. node js version was old
