### ISSUE TITLE
Add loading spinner (loadingGif) to electron-winstaller-fixed options

### ISSUE THREAD

**Issue by atietje** [electron-userland/electron-builder#292]
createWindowsInstaller allows to specify a file that will be used instead of the [default loading spinner](https://github.com/electron/windows-installer/blob/master/resources/install-spinner.gif). This option is not used in WinPackager.packageInDistributableFormat.

I suggest to add `loadingGif: this.metadata.loadingGif` to the options in function packageInDistributableFormat and add the path to the development package.json like 
`{
"build": {"loadingGif": "./build/install-spinner.gif"}
}`

**Comment by develar** [comment]
> suggest to add loadingGif: this.metadata.loadingGif to the options

This option should be listed not in the metadata root `.`, but in the `build.win`. It is supported already. See https://github.com/electron-userland/electron-builder/blob/master/docs/options.md

> add the path to the development package.json like 

Yep! Definitely should be added.
