### ISSUE TITLE
Web installer forces application to open before hits the last screen

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#2921]
* **Version**: 19.53.6

* **Target**: nsis-web

I cannot find a mistake in our nsh file we use for our electron-builder project. When upgrading our application using nsis-web it seems to force open the application after the installation/patching is done before they can even get to the last screen to choose whether they want to run it or not.

Seems like a mistake with the --force-run stuff.

```
"nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "runAfterFinish": false,
      "unicode": true,
      "differentialPackage": true
    },
```

Relevant nsis information is above.

**Comment by develar** [comment]
Should be fixed now.
