### ISSUE TITLE
Build task for target snap not working after adding stagePackages libappindicator1

### ISSUE THREAD

**Issue by kamleshi9** [electron-userland/electron-builder#2925]
* **Version**: 20.13.4
* **Linux Version**: Ubuntu 18.04
* **Snapcraft Version**: 2.42

* **Target**: snap

With introduction for GNOME 3.26 in ubuntu 17.10 libappindicator1 is required to support tray in electron. As I add it to electron-builder.yml the build is failing.
electron-builder.yml (linux part):
```
 linux:
  maintainer: "Riva FZC <support@flock.com> (https://flock.com)"
  synopsis: "Flock Desktop App"
  artifactName: "Flock-linux.${ext}"
  category: "Network"
  icon: "build/icons"
  target:
    - snap
snap:
  summary: "Flock: Team Communication App"
  stagePackages: 
    - libc6
    - default
    - libappindicator1
  plugs: 
    - default
    - camera
```

First error:

> yarn run v1.6.0
$ electron-builder --linux -c.productName='Flock (Beta)' -c.extraMetadata.name=flock-chat
  • electron-builder version=20.13.4
  • loaded configuration file=/home/kamlesh/repos/flocktron/electron-builder.yml
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=keyboard-layout
  • rebuilding native dependency name=nslog
  • rebuilding native dependency name=@paulcbetts/spellchecker
  • rebuilding native dependency name=@paulcbetts/cld
  • packaging       platform=linux arch=x64 electron=1.8.4 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/Flock-linux.snap
Setting target machine to 'amd64'
DEPRECATED: The 'install' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn9 for more information.
Preparing to pull desktop-gtk2 
Ign http://dl.google.com/linux/chrome/deb stable InRelease                     
Hit http://packages.microsoft.com/repos/vscode stable InRelease                
Hit http://dl.google.com/linux/chrome/deb stable Release                       
Hit http://in.archive.ubuntu.com/ubuntu bionic InRelease                       
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Get:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2 kB]   
Hit https://dl.yarnpkg.com/debian stable InRelease                             
Hit http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease             
Fetched 166 kB in 0s (0 B/s)                                                   
Pulling desktop-gtk2 
Cloning into '/home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/src'...
remote: Counting objects: 1142, done.
remote: Total 1142 (delta 0), reused 0 (delta 0), pack-reused 1142
Receiving objects: 100% (1142/1142), 188.26 KiB | 126.00 KiB/s, done.
Resolving deltas: 100% (597/597), done.
'app' has prerequisites that need to be staged: desktop-gtk2
Preparing to build desktop-gtk2 
Building desktop-gtk2 
make FLAVOR=gtk2 -j3
gcc -Wall -O2 -o bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
make FLAVOR=gtk2 install DESTDIR=/home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install
install -D -m755 desktop-launch /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/bin/desktop-launch
install -D -m644 flavor-select /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/
install -D -m644 bindtextdomain.so /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/
 export XDG_DATA_DIRS=/home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/usr/share
 update-mime-database /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/usr/share/mime
 [ -f /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/usr/share/icons/Adwaita//index.theme ]
 gtk-update-icon-cache-3.0 -q /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/usr/share/icons/Adwaita/
/bin/sh: 24: gtk-update-icon-cache-3.0: not found
 which gtk-update-icon-cache-3.0
Failed to run 'install': Exit code was 127.
  ⨯ exit status 2

**I saw the PR for it #2715 that it is for faster startup so i removed that part.
The new error is:**

 

> yarn run v1.6.0
$ electron-builder --linux -c.productName='Flock (Beta)' -c.extraMetadata.name=flock-chat
  • electron-builder version=20.13.4
  • loaded configuration file=/home/kamlesh/repos/flocktron/electron-builder.yml
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=keyboard-layout
  • rebuilding native dependency name=nslog
  • rebuilding native dependency name=@paulcbetts/spellchecker
  • rebuilding native dependency name=@paulcbetts/cld
  • packaging       platform=linux arch=x64 electron=1.8.4 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/Flock-linux.snap
Setting target machine to 'amd64'
Preparing to pull desktop-gtk2 
Ign http://dl.google.com/linux/chrome/deb stable InRelease                     
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Hit https://dl.yarnpkg.com/debian stable InRelease                             
Hit http://packages.microsoft.com/repos/vscode stable InRelease                
Hit http://dl.google.com/linux/chrome/deb stable Release                       
Hit http://in.archive.ubuntu.com/ubuntu bionic InRelease                       
Get:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2 kB]   
Hit http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease             
Fetched 166 kB in 0s (0 B/s)                                                   
Pulling desktop-gtk2 
Cloning into '/home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/src'...
remote: Counting objects: 1142, done.
remote: Total 1142 (delta 0), reused 0 (delta 0), pack-reused 1142
Receiving objects: 100% (1142/1142), 188.26 KiB | 100.00 KiB/s, done.
Resolving deltas: 100% (597/597), done.
'app' has prerequisites that need to be staged: desktop-gtk2
Preparing to build desktop-gtk2 
^[[CBuilding desktop-gtk2 
make FLAVOR=gtk2 -j3
gcc -Wall -O2 -o bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
make FLAVOR=gtk2 install DESTDIR=/home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install
install -D -m755 desktop-launch /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/bin/desktop-launch
install -D -m644 flavor-select /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/
install -D -m644 bindtextdomain.so /home/kamlesh/repos/flocktron/dist/__snap-x64/parts/desktop-gtk2/install/
Staging desktop-gtk2 
Preparing to pull app 
Ign http://dl.google.com/linux/chrome/deb stable InRelease                     
Hit http://in.archive.ubuntu.com/ubuntu bionic InRelease                       
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Hit https://dl.yarnpkg.com/debian stable InRelease                             
Hit http://packages.microsoft.com/repos/vscode stable InRelease                
Get:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2 kB]   
Hit http://dl.google.com/linux/chrome/deb stable Release                       
Hit http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease             
Fetched 166 kB in 0s (0 B/s)                                                   
Pulling app 
Preparing to build app 
Building app 
Staging app 
Priming desktop-gtk2 
The GLIBC version of the targeted core is 2.23. A newer libc will be required for the following files:
 /home/kamlesh/repos/flocktron/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.7 (requires GLIBC 2.25)
 /home/kamlesh/repos/flocktron/dist/__snap-x64/prime/lib/x86_64-linux-gnu/libbsd.so.0.8.7 (requires GLIBC 2.25)
 /home/kamlesh/repos/flocktron/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0 (requires GLIBC 2.26)
 /home/kamlesh/repos/flocktron/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10 (requires GLIBC 2.25)
 /home/kamlesh/repos/flocktron/dist/__snap-x64/prime/lib/x86_64-linux-gnu/libexpat.so.1.6.7 (requires GLIBC 2.25)
'libc6' is required inside the snap for this part to work properly.
Add it as a `stage-packages` entry for this part.
  ⨯ exit status 2

need help
@develar @3v1n0 @flexiondotorg

**Comment by develar** [comment]
@kamleshi9 You need to set it in the electron-builder config:

```
"build": {
  "snap": {
    "stagePackages": ["default", "libappindicator1"]
  }
}
```

**Comment by develar** [comment]
Wait, do you build snap on Ubuntu 18.04? Well... please try to set env `_REMOTE_BUILD=true`, does it help (yes, `_REMOTE_BUILD` with `_`)?

**Comment by kamleshi9** [comment]
Still not working:

> yarn run v1.6.0
$ _REMOTE_BUILD=true electron-builder --linux -c.productName='Flock (Beta)' -c.extraMetadata.name=flock-chat
  • electron-builder version=20.13.4
  • loaded configuration file=/home/kamlesh/repos/flocktron/electron-builder.yml
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=keyboard-layout
  • rebuilding native dependency name=nslog
  • rebuilding native dependency name=@paulcbetts/spellchecker
  • rebuilding native dependency name=@paulcbetts/cld
  • packaging       platform=linux arch=x64 electron=1.8.4 appOutDir=dist/linux-unpacked
  • scheduling remote build target=snap arch=x64
(node:25629) ExperimentalWarning: The http2 module is an experimental API.
  • downloading               path=/home/kamlesh/.cache/electron-builder/zstd/zstd-1.3.3-x64 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/zstd-1.3.3/zstd-v1.3.3-linux-x64.7z
  • compressing and uploading to remote builder
  • uploaded to remote builder time=0s 22ms
Error: spawn /home/kamlesh/.cache/electron-builder/zstd/zstd-1.3.3-x64/zstd ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at RemoteBuildManager.upload (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuildManager.ts:119:5)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuildManager.ts:94:27
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuildManager.doBuild (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/remoteBuilder/RemoteBuildManager.js:251:7)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuildManager.ts:81:12
From previous event:
    at RemoteBuildManager.build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuildManager.ts:66:5)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuilder.ts:71:33
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuilder.ts:104:5)
    at _bluebirdLst.default.mapSeries.arch (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/remoteBuilder/RemoteBuilder.js:172:19)
From previous event:
    at RemoteBuilder.build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/remoteBuilder/RemoteBuilder.ts:49:6)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/linuxPackager.js:191:7)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/packager.ts:381:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.doBuild (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /home/kamlesh/repos/flocktron/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/kamlesh/repos/flocktron/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/kamlesh/repos/flocktron/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/kamlesh/repos/flocktron/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/home/kamlesh/repos/flocktron/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at <anonymous>

**Comment by develar** [comment]
@kamleshi9 Thanks, I will investigate.

**Comment by kamleshi9** [comment]
Tried with the same config on Ubuntu 16.04 and it is working.
Might be an issue only with ubuntu 18.04.

**Comment by develar** [comment]
Yes. That's why we provide free build service and uses template app. I will fix zstd on Linux and you will be able to build snap using our remote service on any your linux machine.

**Comment by develar** [comment]
libappindicator1 is bundled now.

**Comment by kamleshi9** [comment]
@develar the template snap has libappindicator1 bundled?

**Comment by develar** [comment]
Will be pushed to upstream and released today evening. It took me a lot of time since snap is not cross-platform tool :(
