### ISSUE TITLE
Built App Cannot Connect to Database

### ISSUE THREAD

**Issue by auphali** [electron-userland/electron-builder#2932]
* **20.1.0**: 

* **Win, NSIS**: 

I am building an app for CRUD to an oracle database. For convenience, I use "Node-ADODB" library to do it. It works perfectly in development mode.
But once i build the app and try to run it, i can see that there is no response from database at all.

I also made a child process to execute and read value using a VBScript. It works fine in development but it does not work after build.

I also include the script folder in the extraResource config.

Build process was smooth, no error whatsoever. And when execute the app from terminal to look what the main process can feed me back, no sign of error. Simply no response from those scripts.

Do I miss something in the build process?

**Comment by KMurphs** [comment]
I also have the same issue. Application queries database in dev environment, but not in build.

**Comment by develar** [comment]
Sorry, I can only recommend to debug, please see https://electronjs.org/docs/tutorial/application-debugging
