### ISSUE TITLE
How are the two certificates selected?

### ISSUE THREAD

**Issue by y489436672** [electron-userland/electron-builder#2933]
* **Version**: 
electron-builder 19.19.1

* **Target**: 
win7

SignTool Error: Multiple certificates were found that meet all the given
        criteria. Use the /a option to allow SignTool to choose the best
        certificate automatically or use the /sha1 option with the hash of the
        desired certificate.
The following certificates meet all given criteria:

How should I choose? I don't know where to write these options.

**Comment by develar** [comment]
Please set under `win` -- or `certificateSubjectName`, or `certificateSha1`
