### ISSUE TITLE
Windows: Side-by-side install

### ISSUE THREAD

**Issue by akorchev** [electron-userland/electron-builder#2934]
* **Version**:  20.x

* **Target**: Windows NSIS

Is there any way to allow side-by-side installs on Windows? At the moment I can change the product name via the `productName` setting. This is reflected in the installer and .exe filenames but the installation directory remains the same as before changing the product name. All I want is to allow more than one version of my application to be installed. Say "X" and "X Beta". How can I do that?

**Comment by develar** [comment]
You need to change name as well. `-c.extraMetadata.name=ny-beta-app`
