### ISSUE TITLE
Cannot build the app with "requestedExecutionLevel": "requireAdministrator"

### ISSUE THREAD

**Issue by Dominic-Preap** [electron-userland/electron-builder#2936]
- **Version:** 20.13.4
- **Target:** windows
- **Problem:** cannot build app with "requestedExecutionLevel": "requireAdministrator" | "highestAvailable" but working as "asInvoker"

So everything is working fine on electron-builder 20.5.1 then I decide to upgrade to version 20.13.4. Build the app and running as development is fine but when I build the app and open it is display the dialog message below. I'm also checking in Event Viewer and got this line.
`Activation context generation failed for "pathToApp\app.exe".Error in manifest or policy file "pathToApp\app.exe" on line 0. Invalid Xml syntax.` Does this also relate to #2934? 

![image](https://user-images.githubusercontent.com/14802170/40342178-524e7ea4-5db3-11e8-8c82-b51998254d2e.png)

**[UPDATE]:** I try to lower the version, but it is not working since version 20.6.0.

**package.json**
```json
{
  "resolutions": {
    "webpack-sources": "1.1.0"
  },
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  },
  "dependencies": {      
    "electron-store": "^1.3.0",    
    "material-ui": "^0.20.0",    
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-router-dom": "^4.2.2",
    "source-map-support": "^0.5.6",
    "typeface-roboto": "^0.0.54"  
  },
  "devDependencies": {   
    "electron": "^2.0.1",
    "electron-builder": "^20.13.4",
    "electron-webpack": "^2.1.1",
    "electron-webpack-ts": "^2.0.2",    
    "tslint": "^5.9.1",
    "tslint-react": "^3.5.1",
    "typescript": "^2.8.3",
    "webpack": "^4.8.3"
  },
  "build": {
    "productName": "MyApp",
    "compression": "maximum",
    "forceCodeSigning": false,
    "asar": true,
    "win": {
      "icon": "resources/icon/icon.ico",
      "requestedExecutionLevel": "highestAvailable"    
    }   
  }
}
```

**Comment by develar** [comment]
I doubt that it is regression. Please attach your app (or send me privately using email/slack).

**Comment by whyour** [comment]
+1

**Comment by Dominic-Preap** [comment]
@develar Did you get my email? It has been a week now. Thanks

**Comment by gmarinosyan** [comment]
+1, having the same issue

**Comment by moriczgergo** [comment]
+1

**Comment by moriczgergo** [comment]
By the error message, it seems that electron-builder is referencing the .exe file as the manifest. I've extracted the manifest from the .exe file, and it's fully valid XML.

**Comment by ijse** [comment]
+1

**Comment by reFX-Mike** [comment]
We have a similar problem.

As soon as we add:

```
"build": {
    "win": {
      "requestedExecutionLevel": "highestAvailable"
    }
  },
```

we can't even run the app anymore. Installer works fine, but app can't be started.

Does anybody know how to get it to work?

**Comment by omarkadry** [comment]
I had to downgrade to 20.4.1, the issue appears to be in 20.5.1

**Comment by reFX-Mike** [comment]
Thank you so much. It works perfectly now!

**Comment by Zane0816** [comment]
+1;After many attempts, I am sure it can't run since version 20.6.0.

**Comment by reFX-Mike** [comment]
Why is this issue being ignored? Somebody set the label "reply needed", but then ignores all replies?

**Comment by mastergberry** [comment]
Had to downgrade back down to 19.53.6 in order to do anything

**Comment by reFX-Mike** [comment]
It works just fine with version 20.4.1, so shouldn't it be fairly simple to compare changes between 20.4.1 and the most recent version (only looking at relevant changes, of course) and then fixing it?

**Comment by develar** [comment]
@reFX-Mike It was done by @mastergberry Problem in a new signtool version from MS (most likely). I cannot downgrade it because it will affect other users (that uses default).

**Comment by reFX-Mike** [comment]
@develar that is correct. Everything is default except the “requireAdministrator” setting.

**Comment by allexzander** [comment]
I have the same issue. Downgraded to  19.53.6 for now.

**Comment by erguotou520** [comment]
Any progress on this?

**Comment by mastergberry** [comment]
Tagging @develar as it appears this was fixed upstream https://github.com/electron/rcedit/pull/78 in 1.1.1

**Comment by erguotou520** [comment]
Test on electron@3.0.3, not worked. @mastergberry

**Comment by Deafwave** [comment]
+1; Have downgraded to 20.4.1 but  am running into NSIS problems now. I presume they'd fix themselves with a newer electron-builder version.

**Comment by gjavi1** [comment]
On version `20.28.4`, adding this seems to solve the issue:

```javascript
"win": {
      "requestedExecutionLevel": "requireAdministrator",
      "signAndEditExecutable": false
  }
```
But this seems to break the `requestedExecutionLevel` of the packaged app, it does not prompt for elevated privileges

**Comment by erguotou520** [comment]
The manifest file is started with BOM which should be removed.

**Comment by erguotou520** [comment]
I have tried to extract the manifest file, remove the bom, update manifest file, but not worked finally and no error occured.
Some code like:

```js
const { execSync } = require('child_process')
const pkg = require('../package.json')

const mtPath = path.join(__dirname, 'mt.exe')
const exeFilePath = path.join(__dirname, `../build/app-${pkg.version}.exe`)

console.log('Start to extract manifest')
execSync(`${mtPath} -inputresource:${exeFilePath};#1 -out:scripts/manifest.old.xml`)
console.log('Start to remove bom')
require('./removeBom')
console.log('Start to pack the new manifest into exe file')
execSync(`${mtPath} -manifest scripts/manifest.xml -outputresource:${exeFilePath};#1`)
console.log('Done')
```

**Comment by M90K7** [comment]
Windows EventViewer ->
Activation context generation failed for "F:\Projects\........exe".Error in manifest or policy file "F:\Projects\........exe" on line 0. Invalid Xml syntax.

**Comment by reFX-Mike** [comment]
@develar It seems pretty clear that someone is writing a BOM at the beginning of the manifest. This is not supported and causes the manifest to be invalid. Shouldn't it be trivial to remove that?

**Comment by reFX-Mike** [comment]
OK, works fine now with 20.31.0. Isn't the latest official only 20.29.0? Where is 20.31.0 coming from?

**Comment by M90K7** [comment]
We are waiting for the next bug 😄

**Comment by develar** [comment]
> Where is 20.31.0 coming from?

https://github.com/electron-userland/electron-builder/releases/tag/v20.31.0

Great, so, I will close issue, thanks for confirmation.

**Comment by erguotou520** [comment]
@develar `20.31.0` seems to pack `files` into asar file and I'm using api to pack.
```
files: ['dist/bundled/**/*']
```
It works for cli mode.

**Comment by lianxis204** [comment]
@OrangeChu Have you found a solution in version 22.3.27
