### ISSUE TITLE
Is it possible to change node.__dirname to false?

### ISSUE THREAD

**Issue by OualidYousfi** [electron-userland/electron-builder#2938]
* **Version**: 
20.8.1

* **Target**: Windows

In node_modules/electron-webpack/out/main.js, I want to change the node.__dirname variable to false. Is it possible to do so through a webpack.config.js or any other way? Or is there no such freedom?

**Comment by develar** [comment]
For what?

**Comment by OualidYousfi** [comment]
When I execute "yarn dev" and try to go into development mode it works on Windows. However it doesn't work on Mac or Linux, and it gives me a "[not allowed to load local resource](https://github.com/electron/electron/issues/5107)" error.

When I change node.__dirname from "!this.isProduction" to "false" development mode works on Mac/Linux as well. No longer get the error. I don't know what the problem is. The file exists and I'm passing along the correct file path.

```
window.loadURL(url.format({
      pathname: path.join(__dirname, '../../src/index.html'),
      protocol: 'file',
      slashes: true
    }))
```

That's why I was wondering if you could change node.__dirname, asides from making a change in the package itself.

Thanks for the reply!

**Comment by develar** [comment]
Strange. Is it possible to provide demo project?

**Comment by OualidYousfi** [comment]
Just tested it with [electron-webpack-quick-start](https://github.com/electron-userland/electron-webpack-quick-start), on both Windows and Linux. What I did was add an index.html in the src folder. The content doesn't particularly matter. Then edit this in main/index.js.

```
  if (isDevelopment) {
    //window.loadURL(`http://localhost:${process.env.ELECTRON_WEBPACK_WDS_PORT}`)
    window.loadURL(formatUrl({
      pathname: path.join(__dirname, '../index.html'),
      protocol: 'file',
      slashes: true
    }))
  }
  else {
    window.loadURL(formatUrl({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file',
      slashes: true
    }))
  }
```
On Linux (and presumably Mac too) it gave me an "not allowed to load local resource" error.
On Windows the index.html loaded as expected. No error.

**Comment by develar** [comment]
No need to use own index.html. Use renderer/index.js to put your content using JS.

**Comment by awbacker** [comment]
These are quite unhelpful responses.  I have the same issue, and considering that the quickstart _itself_ puts an index.html in src/ ...
