### ISSUE TITLE
Can NSIS installer check if newer version of app is already installed ?

### ISSUE THREAD

**Issue by poojas2288** [electron-userland/electron-builder#2939]
* **Version**: 
19.4

* **Target**: 
NSIS

I have created NSIS installer using electron-builder.
I already have a higher version of my app installed.
When I execute the installer, it should show this message that a newer version of app is slready installed, like it happens with default windows apps. Instead, it installs the lower version of app.

Can the NSIS installer, at the time of execution, check if a newer version of app is already installed or is it possible that it does not installs this version since it is lower that the installed one ?

**Comment by develar** [comment]
It is possible, but we don't have plans to implement it. Help wanted. Please see https://car-park-attendant-cleat-11576.netlify.com/configuration/nsis#custom-nsis-script

**Comment by Bhanuka94** [comment]
Do you have an example NSIS code to check if newer version of the app installed?

I am building my electron app with electron-builder and NSIS.

It will be better if you mention the procedures,
