### ISSUE TITLE
Finalize support for yarn workspaces (hoisted node modules)

### ISSUE THREAD

**Issue by fubhy** [electron-userland/electron-builder#2944]
* **Version**: v20.4.17

* **Target**: linux, mac, windows

In #2205, support for yarn workspaces was partly resolved so that, in case there is no node_modules directory inside of the application directly, it will check for hoisted node_modules further up in the directory hierarchy. However, this is not the right condition to check for. When using yarn workspaces, there are cases where only parts of the node modules are hoisted to the workspace root. It's actually valid to (either manually or due to version conflicts) have parts of your node modules hoisted to the workspace while other node modules remain directly in ${appDir}/node_modules.

My case is exactly that. I have a single dependency which is NOT hoisted to the workspace root. However, due to that, this condition (https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/util/AppFileCopierHelper.ts#L43) evaluates to false which results in electron-builder not seeing my workspace root's node_modules directory at all. That means that none of my dependencies are copied to the package.

I temporarily solved this for me by manually setting isNodeModulesHandled to false (https://github.com/electron-userland/electron-builder/blob/4ea9f03882945f320b8c5cef330444ea0b8daad0/packages/electron-builder-lib/src/util/AppFileWalker.ts#L47).

Is there a way to manually configure the file walker so that it respects and looks at the workspace root's node_modules directory? If not, we maybe need to improve the heuristics for figuring out if we are in a workspace driven environment and, in case we are, always add both directories (the local package's and the workspace root node_modules) to the file walker.

I am happy to work on a pull request if you can point me in the right direction.

**Comment by fubhy** [comment]
I've opened a PR that contains a working version for my setup. If I am not mistaken this should not break other non-workspace builds. It's quite a stupid fix (it just blindly checks parent node modules now). Not sure what the consequences are.

**Comment by fubhy** [comment]
Out of curiosity... Is there a reason why you build your own custom heuristics for discovering / resolving node modules? Wouldn't it be much simple if you just did something along these lines (sudo code);

```js
for (const dependency of pkgJson.dependencies) {
  const depPath = path.dirname(require.resolve(`${dependency}/package.json`));
  copyNodeModule(depPath);
}
```

**Comment by develar** [comment]
`require.resolve` does the same — checks parent and so on. So, final solution will be slower than current.

**Comment by fubhy** [comment]
I know that it does the same but it would move the heavy lifting for node module resolution out of electron-builder. I am not sure if it would be palpably slower actually. For a moderately sized app, the production dependency graph should not include more than a few hundred dependencies. Running require.resolve on a few hundred items shouldn't matter that much.

At the end of the day, I believe it would be worth a short. Maintaining a custom implementation of node module resolution doesn''t seem reasonable especially because it means constantly iterating on the custom implementation as new things like yarn workspaces, etc. evolve.

**Comment by develar** [comment]
@fubhy Keep in mind — yarn workspaces and so on doesn't add new features. Logic is the same — search module from current to root.

I am also doesn't like fact that we have this implementation but last time I have checked and I don't see how we can simplify. I will check your PR, right for now me not clear what's wrong.

**Comment by fubhy** [comment]
@develar the problem I am having right now occurs in an edge case where I have two node_modules directories. One at the workspace root, and one inside of the individual package inside the workspace. The conditionals in electron-builder-lib currently assume that, if there is a node_modules directory inside of the individual package, it does not need to check further up in the tree (e.g. the workspace root). That assumption is incorrect because with yarn workspaces you can control which dependencies should be hoisted and which dependencies should remain within the individual package.

**Comment by jlongster** [comment]
Somehow, that same setup is working fine for me. Yarn has hoisted most modules up to the root directory, my electron app exists as a sub-package, and there is another sub-package that has a few non-hoisted modules in its own node_modules. Going into the electron app sub-package and running `electron-build` works fine - the modules from the other sub-package are included.

I am running into https://github.com/electron-userland/electron-builder/issues/2942 though, but I think it's a separate issue.

**Comment by fubhy** [comment]
> @fubhy Keep in mind — yarn workspaces and so on doesn't add new features. Logic is the same — search module from current to root.

Yeah, it doesn't add new features to node resolution (that ecosystem is locked down and there won't be any changes to how node modules are looked up in the future). However, re-implementing dependency graph traversal and node module discovery still seems unecessary. I think it would be possible (without losing any performance, maybe even improving it) to build the lookup and resolution around existing work like https://www.npmjs.com/package/npm-logical-tree and require.resolve. That's a bit out of scope for this issue though :)

**Comment by fubhy** [comment]
@jlongster But does the sub-package that represents the electron app also have non-hoisted dependencies? That's what the conditional checks. If the appDir has a node_modules directory, it will not bother looking for hoisted dependencies. A sibling package with non-hoisted dependencies is fine.

**Comment by fubhy** [comment]
```
- workspace-root/
    - node_modules/ <-- hoisted dependencies
     - packages/
        - packages/some-library
            - packages/some-library/node_modules <-- non-hoisted dependencies of sibling (this is fine)
        - packages/electron-app
            - packages/electron-app/node_modules <-- non-hoisted dependencies of sibling (this won't work :sad:)
```

**Comment by fubhy** [comment]
That's strange because this line (https://github.com/electron-userland/electron-builder/pull/2945/files#diff-353a2dca652ad5fd58fb25f0c314a1d6L45) clearly checks if there is a node_modules directory and doesn't check hoisted node modules if there is.

**Comment by jlongster** [comment]
@fubhy I figured out my problem. Is there any chance yours is related? https://github.com/electron-userland/electron-builder/pull/2948

**Comment by fubhy** [comment]
@jlongster cool. I'll give your PR a shot tomorrow and check if it is related in any way. I'll let you know.
