### ISSUE TITLE
OSX build fail with "bundle format is ambiguous"

### ISSUE THREAD

**Issue by apolkingg8** [electron-userland/electron-builder#2957]
* **Version**:  20.14.7 with Electron 2.0.2

* **Target**: OSX

```
signing         file=dist/mac/Tiat.app identityName=Developer ID Application: XXX (XXXXXX) identityHash=XXXXXXX provisioningProfile=none
{ Error: Command failed: codesign --sign XXXXXXXX --force /Users/apolkingg8/Documents/myWork/MYAPP/dist/mac/MYAPP.app/Contents/Resources/app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework

/Users/apolkingg8/Documents/myWork/MYAPP/dist/mac/MYAPP.app/Contents/Resources/app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework: bundle format is ambiguous (could be app or framework)
```
I tried update XCode, update OSX, restart mac, nothing works :(

**Comment by apolkingg8** [comment]
Thanks for your reply, but no luck for me.
I tried to `rm -rf node_modules` and reinstall it, but got same issue.

run `yarn why electron` in project folder
```
=> Found "electron@2.0.2"
info Has been hoisted to "electron"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "1.44GB"
info Disk size with unique dependencies: "1.74GB"
info Disk size with transitive dependencies: "10.32GB"
info Number of shared dependencies: 92
```

run `yarn why electron` in app folder
```
error We couldn't find a match!
```

`npm ls --production` in project folder
```
└── (empty)
```

`npm ls --production | grep electron` in app folder
```
├─┬ electron-ga@1.0.6
├─┬ electron-is@2.4.1
│ ├── electron-is-dev@0.3.0
├─┬ electron-localshortcut@3.1.0
│ ├── electron-is-accelerator@0.1.2
│ ├── keyboardevent-from-electron-accelerator@1.1.0
├─┬ electron-updater@2.21.10
│ ├── electron-is-dev@0.3.0 deduped
```

It looks like no `electron` as a production dep.

**Comment by apolkingg8** [comment]
I tried to downgrade to `electron-builder@20.0.5`, and it works now. Did I missed some breaking change about this?

**Comment by marbemac** [comment]
We have the same exact issue with any release newer than `electron-builder@20.0.5`.

**Comment by GhostDev26** [comment]
I am having the exact same issue with electron-builder@20.15.0, I have tried all versions below, the only one that worked for me is electron-builder@20.5.1, But I need the latest version, please can someone help me out.

**Comment by KleggerKoder** [comment]
I was having this problem using electron-packager.  adding the --no-deref-symlinks brought everything back to life
