### ISSUE TITLE
"icon.png: file already closed" when building

### ISSUE THREAD

**Issue by apolkingg8** [electron-userland/electron-builder#2960]
* **Version**: 20.15.1 with Electron 2.0.2

* **Target**: OSX

```
  • electron-builder version=20.15.1
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=2.0.2 appOutDir=dist/mac
  ⨯ close /Users/apolkingg8/Documents/myWork/alice/build/icon.png: file already closed
```
It works fine on Windows, and also works before I upgrade.

**Comment by apolkingg8** [comment]
I tried to downgrade to `electron-builder@20.0.5`, and it works now. Did I missed some breaking change about this?

**Comment by develar** [comment]
It is just error warning, you can ignore it.

**Comment by pronebird** [comment]
I can't reproduce this warning when using `.icns` format.

**Comment by develar** [comment]
Should be obsolete now.
