### ISSUE TITLE
Autoupdate AppImage renames file

### ISSUE THREAD

**Issue by partap** [electron-userland/electron-builder#2964]
* **Version**: 
electron-builder@20.13.4

electron-updater@2.18.2

* **Target**: 
linux/AppImage

When my app runs autoupdate, it overwrites the currently-running appimage, including the filename.  
Example: 
If I have my app installed as `~/Applications/myapp`, then after autoupdating, the file becomes `~/Applications/myapp-1.0.1-x86_64.AppImage`

This makes it difficult to run the app from a script (in my case, it needs to run at startup)

**Comment by partap** [comment]
I'm not sure what would be the best solution for this.  

- Add an option for electron, e.g. `appimage.keepFilename: true`
- Automatically keep filename if it doesn't match a pattern, e.g. `appname-{version}-{arch}.AppImage`
- Modify publishing pipeline so that it leaves the version out of the actual filename? e.g. instead of writing out `appname-1.0.1-x86_64.AppImage`, use a subdirectory: `dist/appname-1.0.1-x86_64-AppImage/appname.AppImage` (or `appname-1.0.1-x86_64-AppImage/appname` ... unsure if the `.AppImage` extension is actually necessary).  

The more I think about it, I like this last idea.  When I first found out about the AppImage format, it seemed to me like a linux version of the Mac `Application.app` format, which I like.  The difference is that Mac apps usually come packaged in a `.dmg` file for installation, so I would download `appname-1.0.1.dmg`, which would contain `appname.app`, and then copy the app executable (directory) into `Applications` or whatever.   Unlike mac `.dmg`'s, the existing AppImage files don't have any sort of installation procedure, they just run from `~/Downloads` or whatever.

So, what if publishing pipeline generated a tgz file instead?  An `appname-{version}-{arch}-appimage.tgz` file which extracts a directory containing `appname` (or `appname.AppImage`).  For initial installation, the user copies that somewhere more permanent (e.g. `~/Applications`)

This would require autoupdater to take an additional step... after downloading the update, it would need to extract the tgz file, and then do the normal copy and restart with the new appimage file.

**Comment by develar** [comment]
@partap Thanks for donation.

**Comment by ttlgeek** [comment]
@partap Hello, i was wondering if you could tell me how you managed to make the Appimage start on system startup ? And if you figured out how to keep the file name after app update ?

Thanks

**Comment by partap** [comment]
@ttlgeek Sorry I missed your comment earlier...

We ended up running a shell script on desktop startup rather than trying to run the AppImage directly.  The script basically runs `~/myappdir/myapp-*` so it ignores the version number in the filename.  

Kinda cheezy, but it works well enough for our needs...it's a non-interactive kiosk signage app.
