### ISSUE TITLE
Code Signing Windows (Digicert)

### ISSUE THREAD

**Issue by theyezzyman** [electron-userland/electron-builder#2965]
* **Version**: 20.2.0

* **Target**: Windows

I am trying to code sign on Windows w/ a digicert standard certificate.

I am using this command `set WIN_CSC_LINK=private/test.p12 && set WIN_CSC_KEY_PASSWORD=pass && build`. The command itself works, but I can't seem to get the correct path to the certificate.

If you have used digicert standard certificate before, what steps did you take to use + code sign with it? Thank you!

**Comment by jasonjmcghee** [comment]
Take a look at: https://github.com/electron-userland/electron-builder/issues/654
