### ISSUE TITLE
Incompatibility with strict node_modules installed by pnpm

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#2968]
* **Version**: 20.15.1

* **Target**: macOS

I am using pnpm rather than npm or yarn and electron-builder is unable to resolve certain dependencies after building an application. I get the following error only when using pnpm rather than npm:

```
Unresolved node modules: electron-is-dev, electron-localshortcut, 7zip, cross-unzip, rimraf, semver, fbjs, loose-envify, object-assign, prop-types, react, buffer-from, source-map, arrify, chalk, diff, make-error, minimist, mkdirp, source-map-support, yn
```

That means those are dependencies of my own dependencies that are not included in the output. Running the output throws an exception regarding missing modules. Installing those manually defeats the purpose of pnpm at this point and I'd like to know whether there is any way to resolve this.

EDIT: Just tried using the pnpm option `--shamefully-flatten` and it still does not work.

**Comment by PureSpider** [comment]
This is still an issue.

**Comment by saltyshiomix** [comment]
@PureSpider 

As of `pnpm@^4`, the `--shamefully-flatten` option is renamed to `--shamefully-hoist`:

```zsh
$ pnpm install --shamefully-hoist
```

And this should be worked 👍
