### ISSUE TITLE
"--publish=release" is not pushing latest.yml and latest-mac.yml to GitHub release so autoupdate is broken

### ISSUE THREAD

**Issue by damianobarbati** [electron-userland/electron-builder#2971]
"--publish=release" is not pushing latest.yml and latest-mac.yml to GitHub release thus auto-update is not working because it does not find them.

I'm building with DEBUG=electron-builder but it seems to upload every file but them: do we have to explicitly tell in `build` to publish them as well?

Furthermore: does electron-builder "sleep" between downloads for any reason? Or is the `electron-builder } +2m` reporting needed time to upload an asset to release?

Building on MacOS High Sierra.
Versions:
```
    "dependencies": {
        "auto-launch": "^5.0.5",
        "better-console": "^1.0.1",
        "electron-log": "^2.2.14",
        "electron-updater": "^2.21.10",
        "lodash": "^4.17.10",
        "luxon": "^1.2.1",
        "mz": "^2.7.0",
        "sleep-promise": "^6.0.0",
        "typeface-montserrat": "^0.0.54",
        "ws": "^5.1.1"
    },
    "devDependencies": {
        "babel-eslint": "^8.2.3",
        "electron": "^2.0.1",
        "electron-builder": "^20.13.4",
        "electron-debug": "^1.5.0",
        "electron-reload": "^1.2.2",
        "eslint": "^4.19.1",
        "eslint-loader": "^2.0.0",
        "eslint-plugin-jest": "^21.15.0",
        "eslint-plugin-react": "^7.7.0",
        "png2icns": "^0.0.1"
    }
```

**Comment by damianobarbati** [comment]
EDIT: sometimes latest*.yml are pushed, sometimes are not!

**Comment by damianobarbati** [comment]
Just me having this I guess...?

**Comment by mseneshen** [comment]
I'm having this issue too, specifically when setting the `releaseType` to `prerelease` or `release`. They publish properly when the `releaseType` is `draft`.

It seems that after publishing the executables, the `latest.yml` and `latest-linux.yml` files aren't being published with the same options specified in `package.json`. The publisher is attempting to publish them as a draft, where the actual publishing type is a prerelease/release.

Here are some logs that show the executable uploading properly, and then the .yml files failing:

```
  • uploading       file=abcd-0.0.37.exe provider=GitHub
    [====================] 100% 0.0s | abcd-0.0.37.exe to GitHub
  • publishing      publisher=Github (owner: mseneshen, project: abcd, version: 0.0.37)
  • GitHub release not created reason=existing type not compatible with publishing type tag=v0.0.37 version=0.0.37 existingType=release publishingType=draft
  • skipped publishing file=latest-linux.yml reason=existing type not compatible with publishing type tag=v0.0.37 version=0.0.37 existingType=release publishingType=draft
  • skipped publishing file=latest.yml reason=existing type not compatible with publishing type tag=v0.0.37 version=0.0.37 existingType=release publishingType=draft
```

**Comment by mseneshen** [comment]
I'm working towards a fix. I'll post an update here soon.

**Comment by mseneshen** [comment]
I found the source of the issue:
https://github.com/electron-userland/electron-builder/blob/5f3935162647127efce401b667b917e67ab8d2ee/packages/electron-builder-lib/src/publish/updateInfoBuilder.ts#L97

Removing this line fixes the issue, but clearly it was put there for a reason. I linked it back to this issue: https://github.com/electron-userland/electron-builder/issues/2199#issuecomment-343852815

@develar , is there a good reason this line exists? I haven't experienced any issues removing it, but I am only building for Linux and Windows.

**Comment by damianobarbati** [comment]
Any update on this? :)

**Comment by dlamon1** [comment]
I am experiencing this bug three years later. Is the fix to remove this line?

**Comment by YouLiLiao** [comment]
> 

When I updated to 22.14.5, I found that the problem had been fixed

**Comment by YouLiLiao** [comment]
> I am experiencing this bug three years later. Is the fix to remove this line?

@dlamon1 When I updated to 22.14.5, I found that the problem had been fixed
