### ISSUE TITLE
Blockmap

### ISSUE THREAD

**Issue by KorobkaVadim** [electron-userland/electron-builder#2972]
OS: MacOS
Version: 19.55.2

How I can disable building blockmap? I don't need in differntial updates, but blockmapping is very slow.
Building binaries - 10 minutes, blockmap - 30 minutes.

**Comment by develar** [comment]
Log is asynchronous. I guess in your case code signing is slow. Please provide build log.

**Comment by KorobkaVadim** [comment]
How get it? And After I press Ctrl + C, I can use my dmg and pkg, as his is not code signing

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by warpdesign** [comment]
I am having the same problem: building blockmap is rather slow: is there a way to disable it? Same for embedded block map.

**Comment by KorobkaVadim** [comment]
I have this problem still 😑
