### ISSUE TITLE
Windows Store (appx): Apps are not allowed to have a Version with a revision number other than zero specified in the app manifest.

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#2979]
* **Version**: ^20.8.1

* **Target**: --win --x64 --ia32

When trying to submit an appx that was built with AppVeyor to the Windows Store, we get rejected during validation with:

> You must fix all package validation errors before submitting.
> 
> Bitwarden-1.3.0-ia32.appx
> 
> Package acceptance validation error: Apps are not allowed to have a Version with a revision number other than zero specified in the app manifest. The package Bitwarden-1.3.0-ia32.appx specifies 1.3.0.553.

553 was the build number from AppVeyor, which seems to be getting automatically injected into the built appx manifest file:

```
  <Identity Name="8bitSolutionsLLC.bitwardendesktop"
    ProcessorArchitecture="x64"
    Publisher='...'
    Version="1.3.0.553" />
```

This seems to be new since I don't recall this happening in previous versions of submitting our app to the Windows store.

**Comment by morajabi** [comment]
I get the same exact error :( and the number increases with every build.

**Comment by kspearrin** [comment]
I worked around this problem for now by defining environment variable `BUILD_NUMBER` to `0` in AppVeyor settings, which will override `APPVEYOR_BUILD_NUMBER` in electron builder.

**Comment by develar** [comment]
@kspearrin Thanks for clear explanation, fixed.

**Comment by semireg** [comment]
@morajabi, @kspearrin, are either of you using "App Flights" to create a "beta channel" for early releases of your appx builds? When I upload two different versions of X.Y.Z.0, even across "non flighted" and a "Beta" flight, I get an error from the interface:

```All .msix and .appx packages (including previously published and currently uploaded) must be uniquely identified by their full names. You have provided two packages with the full name SemiregIndustriesLLC.MyApp_X.Y.Z.0_X64_ which have different contents. Please remove one of these packages, or increment current package versions to continue.```

Check out #3875 for more information.

But I can't see where to remove the package because it's already been approved in a flight. 😕

**Comment by semireg** [comment]
Just got off a chat with MS dev support. They say the only option is to bump the next version higher than all previous versions (flighted or non-flighted). There's no way around this.  🤷‍♂

**Comment by GarryLowther** [comment]
Crazy that an arbitrary poor decision by a junior software engineer at Microsoft can cause so much grief as it defies common sense.
Most people today are using YYYY.MM.DD.HHmm e.g. 2021.09.01.1045 as their version numbers as it is the most logical approach.

**Comment by rickymohk** [comment]
Just run into this and find out this really bad. They provide no way to revise pre-release version without significantly bumping up the version number. Resource ID is not allowed, fourth digit is not allowed.
