### ISSUE TITLE
No dmg bacgkround

### ISSUE THREAD

**Issue by burakcan** [electron-userland/electron-builder#299]
Hello. It was working before, say 1-2 weeks ago but with nothing changed; the dmg's background is gone. I can see that it is present in a folder named `.background` as background.tiff.

Any thoughts?

"electron-builder": "^2.9.5",
"electron-prebuilt": "^0.37.2",

**Comment by develar** [comment]
Please upgrade electron-builder to 3.x (latest version is 3.4.0). Please note — you have to upgrade because of https://github.com/electron-userland/electron-packager/issues/300

**Comment by burakcan** [comment]
@develar thank you for quick response.
i'm trying to upgrade from the repo. when it will be published on npm?

**Comment by develar** [comment]
@burakcan 3.4.0 marked as latest. (in any case latest github release can be installed as `next`).

**Comment by develar** [comment]
I hope your issue is not https://github.com/LinusU/node-appdmg/issues/84

**Comment by burakcan** [comment]
Restarting the computer fixed the problem :D weird

**Comment by develar** [comment]
@burakcan So, it is https://github.com/LinusU/node-appdmg/issues/84 :)

**Comment by burakcan** [comment]
Yes it is :)
I've just upgraded to 3.x too, thank you :)
