### ISSUE TITLE
MacOS delta update

### ISSUE THREAD

**Issue by zhaoterryy** [electron-userland/electron-builder#2995]
Hi,

When will MacOS delta updates be supported? I'm willing to donate for this feature!

**Comment by thomasdarde** [comment]
Seems this ticket can be closed

**Comment by develar** [comment]
No, still not enabled. Why? Well... I am not yet pinged enough :)

**Comment by zhaoterryy** [comment]
@develar PING :)

**Comment by jeffcunat** [comment]
I need this one too ! PING ! :)

**Comment by meekaah** [comment]
@develar  PING 👍

**Comment by KASOGIT** [comment]
Ping 👍

**Comment by connormakh** [comment]
PING PLS

**Comment by arekzaluski** [comment]
Ping. It will be awesome to have this feature.

**Comment by SinghManmohan** [comment]
@develar : I believe it would be a real life-saver not to have download the 130MB electron framework with each update! Please see if it's doable.

**Comment by CapOM** [comment]
This is causing random issues https://github.com/develar/app-builder/issues/24

**Comment by zdQAQ** [comment]
ping pls~

**Comment by harshitsilly** [comment]
@zdQAQ  @CapOM @arekzaluski  - Hi please check this space . https://imjselectron.github.io/electron-differential-updater/#/?id=quick-start
We have differential update working on mac.
For final touches we need 2-7 days. But you guys can still use it.

**Comment by b-zurg** [comment]
@harshitsilly why not make a PR for the features and fixes into the autoUpdater published here?  That way it would get used by far more people.

**Comment by harshitsilly** [comment]
> @harshitsilly why not make a PR for the features and fixes into the autoUpdater published here? That way it would get used by far more people.
Right now there are some concerns:-
1)mac diff update is for zip not for dmg.
2)zip made by electron-builder is corrupted so most of the community make the zip again with the help of ditto..or any other tool. This functionality is exposed by the module.. So I am not sure if we raise the pr this part will be merged bcoz its a part of the build process.
Why we need this?
For the differential update to work, the zip app is needed in cache location. To zip it we need to know the compression process. So if we can control the build process then we will be sure about making zip of the app and moving to cache location.
