### ISSUE TITLE
Cannot use strings in package.json version

### ISSUE THREAD

**Issue by BuffMcBigHuge** [electron-userland/electron-builder#2997]
"electron": "2.0.2"
"electron-builder": "20.15.1"
"electron-compile": "^6.4.2"
"electron-updater": "^2.21.10"
"electron-publisher-s3": "^20.15.0"

macOS

My team and I had a difficult time figuring out why latest-mac-yml was not being created and published to S3 upon building. We discovered that you cannot use text in the package.json version, i.e. "1.0.0-beta-7", opposed to "1.0.0". A suggestion is to update the docs to include this limitation.

**Comment by pronebird** [comment]
Does it work if you use `1.0.0-beta7?` as in semver examples?

**Comment by develar** [comment]
If `beta`, it means that channel file will be named as `beta`, not `latest`. Feel free to send PR to make docs more clear.
