### ISSUE TITLE
Spotlight indexing [macos]

### ISSUE THREAD

**Issue by damianobarbati** [electron-userland/electron-builder#2998]
Scenario:
- I move my-app into /Applications folder
- I open Spotlight and type "my-app"
- no results are shown

Is there anything we need to add into build config to force the indexing of the application i.e: CFBundleExecutable?

https://discuss.atom.io/t/spotlighting-indexing-of-an-atom-shell-app/14935

**Comment by pronebird** [comment]
I think I had no issues with this. Sometimes it takes time for Spotlight to catch up.

**Comment by develar** [comment]
electron-builder already force touch of .app dir to ensure that icon is updated. I guess it is sporadic and very rare issue and we cannot do anything here.
