### ISSUE TITLE
CustomWindowsSignTaskConfiguration no proper tutorial available

### ISSUE THREAD

**Issue by vaidyaanand** [electron-userland/electron-builder#3014]
* **Version**: 
Version : "^20.15.1"

* **Target**: 
Target: Windows 10

I am configuring package.json for windows. Thanks to your efforts, You have to build a nice package. But, I also want to sign (custom- Untrusted) my windows installer file and unable to do. Can you Please add a tutorial for it?

I have gone through this tutorial [Windows configurations](https://www.electron.build/configuration/win#WindowsConfiguration-sign) and got this line:

> sign String | (configuration: CustomWindowsSignTaskConfiguration) => Promise - The custom function (or path to file or module id) to sign Windows executable.

The problem is, I am not getting how to create JS file for windows installer signing and what parameters I have to use for its configurations.

If you close this issue due to any reason, I would like to request you to provide reference links for windows installer sign configuration. I have searched a lot, google it, and tried to make it but unable to do so.

**Comment by vaidyaanand** [comment]
Is there any update on this issue? Please revert back.

**Comment by vaidyaanand** [comment]
Is there any updated?

**Comment by SimonBourdon** [comment]
i need help too with the exact same issue
