### ISSUE TITLE
Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by michael-lucas-net** [electron-userland/electron-builder#3022]
"electron": "^2.0.2",

 "electron-updater": "^2.21.11",

Win, Mac

I had my application running for 2 weeks or so, but suddenly the updater stopped working, though I didn't change anything. I have 2 certificates exported etc. and as I said, it worked well.

Anyone got an idea?

**Comment by ChenAlon** [comment]
Having the same issue on Mac.  
```
Error: Could not get code signature for running application
at Server.<anonymous> (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:85:28)
```

@michael-lucas-net, did you solved it? Would love to understand how.

Versions:
"electron": "^3.0.9",
"electron-builder": "^20.0.6",
"electron-updater": "^2.20.1",

**Comment by michael-lucas-net** [comment]
My mac had a software update and after that the certificate didn't work anymore. I guess the problem occurred because I used the Mac OS beta.

I had to create a new certificate and use it in all my updates.
