### ISSUE TITLE
[Bug] nsis-web auto-update just uninstall application without new installation

### ISSUE THREAD

**Issue by pawsong** [electron-userland/electron-builder#3025]
* **Version**: 20.15.3

* **Version**: 2.21.10

* **Target**: nsis-web

`nsis-web` auto-update uninstalls previous installed files but does not install new one, so auto-update just deletes installed files.

I think this issue is caused by #2739. `child_process`.`spawn` doesn't seem to require double quotes, and unexpected double quotes makes nsis script cannot parse `--package-file` properly.

## Possible solutions
- Rollback #2739 to remove double quotes
- Add `shell: true` or `windowsVerbatimArguments: true` to spawn options

Reference:
https://stackoverflow.com/questions/12310468/node-js-child-process-issue-with-args-quotes-issue-ffmpeg-issue#comment16520727_12310468

**Comment by pawsong** [comment]
The temporary patch I am using:

*electron-updater+2.21.10.patch*

```patch
--- a/node_modules/electron-updater/out/NsisUpdater.js
+++ b/node_modules/electron-updater/out/NsisUpdater.js
@@ -228,6 +228,7 @@ class NsisUpdater extends _BaseUpdater().BaseUpdater {
     }

     const spawnOptions = {
+      shell: true,
       detached: true,
       stdio: "ignore"
     };
```

**Comment by paulingalls** [comment]
please do.  I'm having the same problem.

**Comment by pawsong** [comment]
@develar Can I get some feedback?

**Comment by pawsong** [comment]
@paulingalls https://github.com/ds300/patch-package might help you before fixed version is deployed :)

**Comment by chrisbruford** [comment]
Don't know if it's an option for you guys but I've turned off silent install so that the UAC can get triggered. I'll turn it back on if/when this gets fixed.

**Comment by jeffcunat** [comment]
@develar  Any news about this one, we also had problems with nsis-web and auto-update...

**Comment by jeffcunat** [comment]
I really suggest a rollback #2739 to remove double quotes, because I have spaces in my path and it works with the previous code and not after merging #2739
