### ISSUE TITLE
latest-linux.yml not generated for deb files

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#3034]
* **Version**: 20.15.1

* **Target**: Linux/Ubuntu

latest-linux.yml not generated for deb file.....
command use : build -p always

in package.json:

"linux": {
      "maintainer": "Md Azmal <azmalmd12@gmail.com>",
      "category": "Audio",
      "icon": "./build/png",
      "target": [
        "AppImage",
        "deb"
      ]
    }

**Comment by develar** [comment]
`deb` files is supposed to be distributed using system package manager. Auto update supported only for AppImage.

**Comment by mkermani144** [comment]
@develar I think this should be mentioned in the docs.
