### ISSUE TITLE
Wrong cursor in snap files

### ISSUE THREAD

**Issue by poacc** [electron-userland/electron-builder#3035]
* **Version**: 20.15.1

* **Target**: Linux (snap)

After installing the "snap" file created by electron-builder, wherever mouse cursor is set to "pointer" it shows the wrong cursor.
![b](https://user-images.githubusercontent.com/40565164/41852112-15bc1390-7882-11e8-8c35-d1d290bfe430.png)
Using "deb" and "AppImage" files created by electron-builder does not have this side effect.
![a](https://user-images.githubusercontent.com/40565164/41852224-6c46b09e-7882-11e8-831f-6736e3f0080a.png)

**Comment by julian-alarcon** [comment]
Some doc about this.

https://forum.snapcraft.io/t/supporting-desktop-themes-via-the-content-interface/4122
https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
https://forum.snapcraft.io/t/desktop-improvements-report-and-plans/3510/1
https://forum.snapcraft.io/t/layouts-re-mapping-snap-directories/1471
https://forum.snapcraft.io/t/snap-layouts/7207/1
https://docs.snapcraft.io/snap-layouts/7207

**Comment by develar** [comment]
Fixed in 20.44.0.
