### ISSUE TITLE
Electron-Updater | Windows Portable

### ISSUE THREAD

**Issue by Lyca-Knight** [electron-userland/electron-builder#3036]
* **Version**: 20.16.0

* **Updater-Version**: 2.21.0

* **Target**: WIN (portable)

Is there any way to use the Electro-Updater under Windows with the portable Target?
The Updater work great on Linux (AppImage). Under Windows i get the following error message:
```
[error] Error: Error: ENOENT: no such file or directory, open 'C:\Users\Admin\AppData\Local\Temp\nswF6AD.tmp\app\resources\app-update.yml'
    at C:\Users\Admin\AppData\Local\Temp\nswF6AD.tmp\app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:391:27
```
Any way to fix this?

**Comment by develar** [comment]
Portable doesn't support auto-update by intention. It is "portable" :)

**Comment by rnowak8** [comment]
@develar AppImage is also "portable" but auto-update is working for it, it's just replacing the AppImage file with a new version.
