### ISSUE TITLE
Windows events still necessary? Electron now has uniform api

### ISSUE THREAD

**Issue by jessep** [electron-userland/electron-builder#304]
In your auto update docs, you say be sure to handle windows events. However, Electron now supports a uniform client api for windows/mac events: http://electron.atom.io/docs/v0.37.5/api/auto-updater/

Just wanted to clarify that this is a documentation issue, not something I'd need to worry about.

**Comment by develar** [comment]
autoupdate api is not new.

You should handle Squirrel.windows events otherwise you get issue https://github.com/mongodb-js/electron-squirrel-startup Consider to use https://github.com/mongodb-js/electron-squirrel-startup

**Comment by jessep** [comment]
Well, the windows support for it is new as of December. Maybe that doesn't count as new? https://github.com/electron/electron/pull/1984#issuecomment-151059407

**Comment by develar** [comment]
> Maybe that doesn't count as new?

Yes, in the JS world is quite old ;)
