### ISSUE TITLE
Flatten copied file 

### ISSUE THREAD

**Issue by redplane** [electron-userland/electron-builder#3041]
* **Version: 20.16.0**: 
* **windows x64**: 

Hi,

I'm using `electron-builder` to build my application.
This is my project structure:

![prj](https://user-images.githubusercontent.com/7974095/41896549-784935a8-7957-11e8-8da4-7fe14090fa04.png)

This is my `build` configuration : 

```
"build": {
    "appId": "com.electron.pesonal-cv",
    "productName": "personal-cv",
    "files": [
      "src/dist"
    ],
    "nsis": {
      "createDesktopShortcut": "always"
    },
    "extraResources": null
  }
```

In my `app.asar` file, it consist of a folder `src/dist`, it should be contents of `dist` folder only.

How can I copy the files that has the root as `src/dist` to my `app.asar` file ?

Thank you,

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/contents

```
"files": {
  {"from": "src/dist"}
}
```

**Comment by redplane** [comment]
Thank @develar,

How about just copying a specific `node_module` directory.
What I've tried is : 

```
"build": {
    "appId": "com.electron.pesonal-cv",
    "productName": "personal-cv",
    "files": [
      {
        "from": "src/dist",
        "filter": ["!resources/*"]
      },
      {
        "from": "node_modules",
        "filter": ["node_modules/sqlite3"]
      }
    ],
    "nsis": {
      "createDesktopShortcut": "always"
    },
    "extraResources": null
  }
```

But every modules in `node_modules` have been copied to my `app.asar` file. 

What wrong am I doing ?

**Comment by develar** [comment]
You should not worry about node_modules Only production deps will be copied.

**Comment by redplane** [comment]
Actually I'm using `webpack` to bundle the library I use. The only node_module I want to copy is `sqlite3`. 
I don't know what wrong with my filter. It doesn't exclude node modules which are not `sqlite3`

**Comment by develar** [comment]
@redplane I suggest you to not fight and simply move all your deps to `devDependencies` except wanted (`sqlite3`).

**Comment by redplane** [comment]
Thank you for your tip :).

It works like a charm.
I think this question can be closed.
