### ISSUE TITLE
[signing] How to specify different certificates for mas and dmg target

### ISSUE THREAD

**Issue by damianobarbati** [electron-userland/electron-builder#3044]
@develar since a "store-distributed app" needs "Mac Developer certificate" and a "not store-distributed app" needs a "Developer ID certificate", how can I specify different .p12 files for the 2 targets? Possibly without "autodiscovery"?

Because right now I have CSC* variables linking to the "Developer id" .p12 file, and the "Mac developer certificate" just in my keychain (and it is not found, but that's another story).

Thanks for your great effort into this as always! 😁

**Comment by develar** [comment]
Just pack both certs into one p12 file :) P12 file can contains several certs and electron-builder will select proper one.

Also, please see https://www.electron.build/configuration/mas

> Inherits macOS options.

So, you can use or `-c.mas.identity=` to specify different identity name if differs
