### ISSUE TITLE
Getting error for building osx installler

### ISSUE THREAD

**Issue by rsaccon** [electron-userland/electron-builder#305]
OS: Mac OS X
nvm / nodejs: v5.10.1
npm: 3.8.7
electron-builder: 3.5.0

```
Robertos-MacBook-Pro:myapp robertosaccon$ npm run dist:osx

> MyApp@0.0.1 dist:osx /Users/robertosaccon/go/src/github.com/rsaccon/myapp
> build --platform darwin -d

Installing app dependencies for arch x64 to /Users/robertosaccon/go/src/github.com/rsaccon/myapp/app
Packaging app for platform darwin x64 using electron v0.37.5
Signing app
Creating DMG
Creating ZIP for Squirrel.Mac
Unhandled rejection Error: Cannot find module '../build/Release/volume.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
   ...
```
a `MyApp-0.0.1-mac.zip` files gets created in the dist folder, but there is no DMG there

**Comment by develar** [comment]
Did it work before?
Do you have build/background.png and build/icon.icns?

**Comment by develar** [comment]
Try to eject all existing DMG.

**Comment by rsaccon** [comment]
@develar, thanks for the quick reply.
no, it never worked, I have also tried with several electron builder releases < 3.5.0, but same result
```
ls build
background.png	icon.icns	icon.ico
```
I have no DMG mounted

**Comment by develar** [comment]
I think it is your project configuration error. If you can, send me a project and I will see.

**Comment by develar** [comment]
Please try to remove your node_modules and run `npm install` again. Attach npm install log here (console output).

**Comment by rsaccon** [comment]
@develar, thanks a lot, after reinstalling all node_modules it worked (but I am stuck now with an error for windows, will open new issue for that)

**Comment by develar** [comment]
@rsaccon Yep, npm is not reliable.
