### ISSUE TITLE
only a blank screen after build

### ISSUE THREAD

**Issue by didmehh** [electron-userland/electron-builder#3052]
* **Version**: 
  - electron: "^2.0.3"
  - electron-builder: "^20.16.0"

* **Target**: 
current was `dmg`, if works, need to build for windows platform.

Current environment was a create-react-app product, i had reference [From React to an Electron app ready for production](https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3).

#### the issue was dev work and build not work, it's only a blank screen.

some config:
 `package.json`
```javascript
...
"main": "public/electron.js",
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "electron-dev": "concurrently \"BROWSER=none npm start\" \"wait-on http://localhost:3000 && electron .\"",
    "preelectron-pack": "npm run clean-dist && npm run build",
    "electron-pack": "build -c.extraMetadata.main=build/electron.js",
    "clean-dist": "rm -rf ./dist"
  },
"build": {
    "appId": "com.example.electron-cra",
    "productName": "test-cra",
    "files": [
      "build/**/*",
      "node_modules/**/*"
    ],
    "directories": {
      "buildResources": "assets"
    }
  },
...
```

`public/electron.js`

```javascript
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

const path = require('path');
const url = require('url');
const isDev = require('electron-is-dev');
require('electron-debug')();

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({width: 900, height: 680});
  mainWindow.webContents.openDevTools()

  mainWindow.loadURL(isDev ? 'http://localhost:3000' : `file://${path.join(__dirname, '../build/index.html')}`);
  mainWindow.on('closed', () => mainWindow = null);
}

app.on('ready', createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  }
});
```

then in the chrome devTools, has some error:
```shell
Failed to load resource:  net::ERR_FILE_NOT_FOUND       main.4184e132.css
Failed to load resource:  net::ERR_FILE_NOT_FOUND       main.1445b1ba.js
```

because of electron version?

**Comment by didmehh** [comment]
i'm resolve it by add homepage.
but another issue was 
```error
Failed to load resource:  net::ERR_FILE_NOT_FOUND       1.4e85fab7.chunk.js
```

such as this error because of electron don't support code splitting?

**Comment by develar** [comment]
Sorry, issue not related to electron-builder. Maybe `"asar": false` will help you, but you need to investigate what's wrong with your loader.

**Comment by didmehh** [comment]
thks. set `"asar": false` not work too, i think because of [code splitting with react-router](https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html).

**Comment by gen4sp** [comment]
> thks. set `"asar": false` not work too, i think because of [code splitting with react-router](https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html).

Do you solve your issue? Have the same one

**Comment by gen4sp** [comment]
> @gen4sp
> I had resolved it by use hashRouter replace browserRouter
> 
> > such as this error because of electron don't support code splitting? or [2167](https://github.com/electron-userland/electron-builder/issues/2167)

ok, thanks. It seems is not my case :(

**Comment by HemantKumarProgrammer** [comment]
If you have a **icon** defined in **main.js** (in any browser window) then the problem maybe that. And you can surely **solve** it. Check here https://stackoverflow.com/a/63936522/13114354

**Comment by cnscorpions** [comment]
@didmehh thank you, it works for guys who use react-router with BrowerRouter 大兄弟救了命🤣
