### ISSUE TITLE
Can NSIS be used used as dependency for electron-builder?

### ISSUE THREAD

**Issue by shaluyadav13** [electron-userland/electron-builder#3054]
NSIS binaries are fetched from the electron-builder-binaries project. The electron-builder-binaries project URL is hardcoded. I want to use NSIS binaries with logging enabled. For which I have created a fork from electron-builder and electron-builder-binaries. But doing all this makes maintenance of forks are pretty tough. So, if we could create an NSIS package and use that as dependency then things will be little simple for those who want to use custom builds of NSIS.

Suggestions will be appreciated. :)

**Comment by develar** [comment]
Set `ELECTRON_BUILDER_NSIS_DIR` dir. 20.18.0

**Comment by shaluyadav13** [comment]
Thank you for the change. I tried setting the ELECTRON_BUILDER_NSIS_DIR variable but while packaging .exe using `electron-builder` in scripts getting below error.
 Error: ENOENT: no such file or directory, copyfile 'C:\Users\syadav\AppData\Local\electron-builder\test\nsis\nsis-3.0.3.0 \elevate.exe' -> 'C:\Users\syadav\Documents\projects\appname\dist\win-ia32-unpacked\resources\elevate.exe'
    at doCopyFile (C:\Users\syadav\Documents\projects\appname\node_modules\builder-util\out\fs.js:294:44)
    at copyOrLinkFile (C:\Users\syadav\Documents\projects\appname\node_modules\builder-util\src\fs.ts:190:2)
    at then (C:\Users\syadav\Documents\projects\appname\node_modules\builder-util\src\fs.ts:138:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have the file on the specified location. Could you please help me with this?
