### ISSUE TITLE
AppImage not running on Ubuntu 16.04

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#3055]
* **Version**: 20.14.7

* **Target**: Linux / AppImage

The AppImage file is not running on ubuntu 16.04 
It blinks on the launcher tab and closes

**Comment by develar** [comment]
Please try latest version.

**Comment by hn6pot** [comment]
Hi, i've got the same issue on the last version available : 20.38.5.

I can't run the app image (ofc i change the file right before (chmod a+x)) but it fail 
sudo: ./test.AppImage : commande introuvable

**Comment by jayarjo** [comment]
Encountering this in the latest version: 20.40.2. I opened a new issue: https://github.com/electron-userland/electron-builder/issues/3906
