### ISSUE TITLE
electron-builder compile every source code under src

### ISSUE THREAD

**Issue by worudso** [electron-userland/electron-builder#3056]
* **Version**: 20.15.1

* **Target**: all platforms

I expected electron-builder to compile necessary files only(which webpack is for).
However when I made syntax errors in unused `.tsx` files under `src`, it emitted errors on build.
I don't think it's desired behavior. Or are they from tslint perhaps?

**Comment by develar** [comment]
Electron compile is not webpack and processes all files.
