### ISSUE TITLE
Add ability to rename .exe file

### ISSUE THREAD

**Issue by havenchyk** [electron-userland/electron-builder#306]
In the electron-winstaller we have property setupExe:

setupExe	- The name to use for the generated Setup.exe file. Can we backport it to the fork?

**Comment by develar** [comment]
No. This option will be forbidden (when fork will be rebased). Because names are important — github publish for example.

If you want to change generated installer name — more smart option maybe introduced (arch, version and other macro).

**Comment by havenchyk** [comment]
It's not important, but it's an option at windows-installer, so i didn't see any problem with backporting. In the readme you're saying that under the hood you use windows-installer, I don't quite understand, why should we filter this option

**Comment by develar** [comment]
>  I don't quite understand, why should we filter this option

* Because we upload artefact to GitHub 
* Currently we use different naming.
* This option is ugly — no macro support.

Do you remember — when you specify conflicting electron-packager options it leads to mystic errors. I don't want to open Pandora's box.

**Comment by havenchyk** [comment]
> Because we upload artefact to GitHub

Actually, I don't. But I see your point, thanks for explanation.
