### ISSUE TITLE
Cannot build linux package on Windows.

### ISSUE THREAD

**Issue by redplane** [electron-userland/electron-builder#3061]
* **Version**: 20.16.0 
* **Electron version**: v.2.0.1
* **Target**: Linux (AppImage), Windows (nsis)

Hi,

I'm trying to build my electron application target to both Windows and Linux.
This is my configuration:

```
"build": {
    "appId": "com.electron.pesonal-cv",
    "productName": "personal-cv",
    "files": [
      {
        "from": "build",
        "filter": [
          "!resources/*"
        ]
      }
    ],
    "win": {
      "target": "nsis"
    },
    "linux": {
      "target": ["AppImage"],
      "icon": "asset/icons/app.linux.png",
      "synopsis": "For testing ng-electron-structure",
      "category": "Development"
    },
    "extraResources": [
      {
        "from": "build/resources",
        "to": "resources"
      }
    ]
  }
```

However, when I ran the `build` command, the output is 

```
|- win-unpacked
|- electron-builder-effective-config.yaml
|- lastest.yml
|- <app name> Setup 1.0.0.exe
|- <app name> Setup 1.0.0 blockmap
```

There was no output for linus system. What wrong have I done ?

Thank you.

**Comment by develar** [comment]
https://www.electron.build/multi-platform-build

```
electron-builder -mwl
```

You should pass `--linux --windows` if you want to build linux on non-linux OS.

**Comment by yangjunfocus** [comment]
@develar i have tried `electron-builder -mwl` still can't build Mac

**Comment by pearlamp** [comment]
Is there an solution update to this problem?

**Comment by danlan21** [comment]
> @develar i have tried `electron-builder -mwl` still can't build Mac

You can only build mac on an Apple system.
