### ISSUE TITLE
Not a valid win32 application

### ISSUE THREAD

**Issue by yovanoc** [electron-userland/electron-builder#3063]
* **Version**: 20.19.1

* **Target**:  All target, but the problem is only windows on Linux docker image. (https://github.com/cookie-project/cookietouch/blob/master/.travis.yml)

When we installed the setup.exe given by Travis on my s3 bucket.

![unknown](https://user-images.githubusercontent.com/7302317/42124192-bf814e10-7c5e-11e8-84c1-b73057114c6a.png)

**Comment by yovanoc** [comment]
Oh i rolled back to electron 2 and it's working, it's just with electron 3 beta, so where is the problem here? no prebuilt binaries?

**Comment by develar** [comment]
Yes, I think so.

**Comment by yovanoc** [comment]
Sorry for the reply after this is closed but where can we wee available versions of electron ?
