### ISSUE TITLE
process.env.PATH undefined

### ISSUE THREAD

**Issue by tonyyls** [electron-userland/electron-builder#3066]
hi, when i produce dmg and exe by using electron-builder.  i found that  process.env.PATH is not worked in my code.  but it works  in the console. 

Have you  ever meet this ?

![qq20180702-141113](https://user-images.githubusercontent.com/1624736/42147949-c60f2f04-7e02-11e8-82c5-a3ba52abcb32.png)
<img width="463" alt="qq20180702-141612 2x" src="https://user-images.githubusercontent.com/1624736/42147950-c65f9fac-7e02-11e8-8b3e-1cde302c0a0b.png">

**Comment by develar** [comment]
https://github.com/sindresorhus/shell-env

**Comment by oinochoe** [comment]
@develar Has it not been fixed yet? If so, can I use that module?
