### ISSUE TITLE
autoUpdater doesn't work

### ISSUE THREAD

**Issue by radreamer** [electron-userland/electron-builder#3067]
electron-builder@20.19.1

electron-updater@2.23.3

* **Target**: nsis, dmg, zip

I'm testing auto updates for both channels latest and beta and get the following situation:
 1) upload a new version (0.2.3) to my provider and run installed app with the previous version (0.2.2):

```Checking for update
Found version 0.2.3 (url: Quatrix Express-0.2.3-mac.zip, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg)
Downloading update from Quatrix Express-0.2.3-mac.zip, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg
/ requested
/app.zip requested
download-progress listener count: 0
2018-07-02 12:19:16.449 Quatrix Express[25808:1116509] Download completed to: file:///Users/rodion/Library/Caches/quatrix.express.ShipIt/update.MgUxQur/app.zip
New version 0.2.3 has been downloaded
Proxy server for native Squirrel.Mac is closed (was started to download https://<provider_url>/Quatrix%20Express-0.2.3-mac.zip)
```

2) according to this code in my `main.js` I see the message about the new version which will be installed after close:

```
app.on('ready', () => {
  autoUpdater.checkForUpdatesAndNotify()
})

autoUpdater.on('update-downloaded', info => {
  win.webContents.send('updateReady')
})
```

3) then I close the app, start it again and get the same output about new version again:

```
Checking for update
Found version 0.2.3 (url: Quatrix Express-0.2.3-mac.zip, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg)
Downloading update from Quatrix Express-0.2.3-mac.zip, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg, Quatrix Express-0.2.3.dmg
/ requested
/app.zip requested
download-progress listener count: 0
2018-07-02 12:19:43.005 Quatrix Express[25839:1116907] Download completed to: file:///Users/rodion/Library/Caches/quatrix.express.ShipIt/update.OJm2r1y/app.zip
New version 0.2.3 has been downloaded
Proxy server for native Squirrel.Mac is closed (was started to download https://<provider_url>/Quatrix%20Express-0.2.3-mac.zip)
```

4) I see the message about new version again and there are no updates

P.S. All works well for Windows. 

P.P.S. This behavior is not constant, because I had the same situation for the previous version and updated installed after few "exit-run" actions

**Comment by radreamer** [comment]
my build section:
```
"build": {
    "appId": "quatrix.express",
    "productName": "Quatrix Express",
    "publish": [
      {
        "provider": "generic",
        "url": "http://127.0.0.1:8080"
      }
    ],
    "mac": {
      "category": "public.app-category.productivity"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "generateUpdatesFilesForAllChannels": true,
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    }
  }
```

**Comment by yeluoqiuzhi** [comment]
I have the same problem

**Comment by chevonc** [comment]
Having same issue here as well

**Comment by playengineio** [comment]
Anyone found a solution to this issue?

**Comment by yaseersheriff** [comment]
Also seeing the same issue: 

`[14:16:29.882] [warn] Error: Could not locate update bundle for axiomdesktop within file:///Users/axiom/Library/Caches/axiomdesktop.ShipIt/update.RadPasT/

[14:16:29.883] [error] Error: Error: Could not locate update bundle for axiomdesktop within file:///Users/axiom/Library/Caches/axiomdesktop.ShipIt/update.RadPasT/
[14:16:29.883] [info] Error in auto-updater.
[14:16:30.940] [info] Proxy server for native Squirrel.Mac is closed (was started to download http://axiom.ai/desktop_app/axiom-desktop-mac-latest.zip)`

**Comment by yanlee26** [comment]
Error: Error: Could not locate update bundle for com.github.Electron within file:///Users/elliotyan/Library/Caches/com.github.Electron.ShipIt/update.puOMysF/

I wonder why this issue closed ?

**Comment by skylingfly** [comment]
same issue here, autoUpdater doesn't work

**Comment by mqliutie** [comment]
`Error: Error: Could not locate update bundle for com.github.Electron within file:///Users/liutie3/Library/Caches/com.github.Electron.ShipIt/update.1sJx6lI/`

Hi , Anybody knows can i update app in the local?

**Comment by LaurentGENTY** [comment]
Got the same problem here, still no solutions ?
