### ISSUE TITLE
Electron Updater. Bug saving old installers.

### ISSUE THREAD

**Issue by KorobkaVadim** [electron-userland/electron-builder#3069]
* **Version**: 
^2.18.2

* **Target**: Win32

After every update, we don't delete old binary file. After 6 updates, 300mb installers locate:
C:\Users\${user}\AppData\Roaming\${AppProductName}
installer-1.0.2.exe
installer-1.0.1.exe
installer-1.0.0.exe etc.

**Comment by develar** [comment]
Already fixed, please use 2.23.3 AND electron-builder 20.19.1

**Comment by develar** [comment]
Duplicates #2744
