### ISSUE TITLE
Code Signing on Mac

### ISSUE THREAD

**Issue by ghego1** [electron-userland/electron-builder#307]
I'm not sure this is an issue, or just a misconfiguration on my side, but I really do not understand how to sign code.

I must admit that I do not understand what this means: `On a development machine set environment variable CSC_NAME to your identity (recommended).`.

Where should I set the `environment variable CSC_NAME`? In the package.json?

I've also tried to `pass --sign parameter` like this: `npm run pack --sign`, however I still get the message `App is not signed: CSC_LINK or CSC_NAME are not specified`.

But where should I specify those?

PS I've all the certificates from Apple and I already managed to sign an app built with xcode.

**Comment by jbleuzen** [comment]
You must set this variable just before `npm run dist`

**Comment by develar** [comment]
> Where should I set the environment variable CSC_NAME? In the package.json?

Where you want. But as @jbleuzen said, before run tool :)

**Comment by ghego1** [comment]
Thank's for the clarification :-)
