### ISSUE TITLE
[electron-updater] providing an alternative signature verification implementation (NSIS) via API

### ISSUE THREAD

**Issue by MaxFichtelmann** [electron-userland/electron-builder#3071]
* **master/20.19.1**: 

* **master/20.19.1**: 

* **Windows/NSIS**: 

In an application I am developing, I want to be able perform some extended signature verification before accepting and applying an update. I want to make sure, that the update is not only signed by an entity with a specific subject DN, but a specific CA certificate.

As far as I can see, the ideal solution for me would be to be able to programmatically influence how `NsisUpdater.verifySignature` works, i.e. by supplying an alternative implementation via options (like setFeedUrl).

I am more than willing to provide a PR for this feature, but I am not sure, if my take is a good fit.

**Comment by develar** [comment]
PR will be definitely accepted and welcome.

**Comment by develar** [comment]
Keep in mind — DN is enough if certificate issued by trusted authority center. It is a reason why code sign cert is not so cheap compared to domain cert. No one except you can sign binary with your name.

**Comment by MaxFichtelmann** [comment]
well - after further investigation, I realized the NsisUpdater instance is exposed as the `autoUpdater` - so I can directly replace the function in question.
