### ISSUE TITLE
update fails silently

### ISSUE THREAD

**Issue by radreamer** [electron-userland/electron-builder#3074]
I faced with a problem, that my application after start log `Checking for update` and that's all – no info or error. I'm using a generic provider. I spend on it almost all day and then I found the reason – invalid certificate(NET::ERR_CERT_INVALID) on my site.

Would be great to have an error about it in the autoUpdater logs.

**Comment by stvitaly** [comment]
@radreamer, do you remember what was the final reason for the issue?
I am experiencing the similar issue with our application.

> I faced with a problem, that my application after start log `Checking for update` and that's all – no info or error. I'm using a generic provider. I spend on it almost all day and then I found the reason – invalid certificate(NET::ERR_CERT_INVALID) on my site.
> 
> Would be great to have an error about it in the autoUpdater logs.
