### ISSUE TITLE
[Bug] addRandomQueryToAvoidCaching does not respect query parameters

### ISSUE THREAD

**Issue by johanwilson** [electron-userland/electron-builder#3076]
* **electron-builder Version**: 20.19.1

* **electron-updater Version**: 2.23.3

* **Target**: --win --x64 

The latest versions does not respect query parameters in **publish->url** anymore. 
`"https://gitlab/.../artifacts/master/raw/dist?job=build_electron_win"`

electron-update.logger dump:
```
[2018-07-04 13:43:15.673] [error] Error: Error: Cannot find channel "latest.yml" update info: HttpError: 404 Not Found
"method: undefined url: https://gitlab/.../artifacts/master/raw/dist/latest.yml?noCache=1chihl2ff"
```

**Comment by develar** [comment]
electron-updater 3.0.2

**Comment by Hector1567XD** [comment]
> electron-updater 3.0.2

It helped by upgrading to the latest version, thanks =D!
