### ISSUE TITLE
electron-builder post install script failed with gyp rebuild failed "This platform is not implemented yet"

### ISSUE THREAD

**Issue by GeeshangXu** [electron-userland/electron-builder#308]
>..\src\volume.cc(9): fatal error C1189: #error:  This platform is not implemented yet [D:\electron->quick-start\node_modules\.npminstall\macos-alias\0.2.9\macos-alias\b
>uild\volume.vcxproj]

I am using win10 x64, when use command "npm install" after install electron-builder successfully i got this error during the post install script runing time . It seems nothing to do with node-gyp, could be macos-alias 's problem .It's source code  ..node_modules\.npminstall\macos-alias\0.2.9\macos-alias\src is only about apple not windows platform.   
so, it seems the electron-builder use modules don't support windows , is it a bug right now?  
------
The  volume.cc source lies 
```c++
#include <nan.h>
#include <node.h>
#include <v8.h>

#ifdef __APPLE__
#include "impl-apple.cc"
#else
#error This platform is not implemented yet
#endif

using v8::FunctionTemplate;

NAN_MODULE_INIT(Initialize) {
  Nan::Set(target, Nan::New("getVolumeName").ToLocalChecked(),
    Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
}

NODE_MODULE(volume, Initialize)
```

**Comment by develar** [comment]
>  is it a bug right now?

I think it is a npm bug. Please specify npm version and nodejs (npm 3 and node 5 are recommended).

Related: https://github.com/electron-userland/electron-builder/issues/305#issuecomment-209061963

Please try to remove your node_modules and run npm install again. Attach npm install log here (console output).

**Comment by GeeshangXu** [comment]
Yes it is really nothing to do with elctron-builder. It turns out to be a bug of  the tool "cnpm" which is a  npm client for China mirror of npm [Taobao NPM mirror](https://npm.taobao.org) belongs to Alibaba Group. The tool cnpm  claims "Support all commands just like npm",  obviously not for this one LoL. I just swich to the npm , everthing is ok.  I'll submit this issue to [cnpm](https://github.com/cnpm/cnpm).
