### ISSUE TITLE
electron-builder is not bundling the python files

### ISSUE THREAD

**Issue by ishandutta2007** [electron-userland/electron-builder#3081]
This is my directory structure where `renderer.js` is included by `index.html` .
The python scripts `visitor.py` and `download.py` are called from `renderer.js` via [python-shell][1].
Once I bundle, it is not able to find the python scripts

      |_ index.html
      |_ styles.css
      |_ main.js
      |_ package.json
      |_ dist/
      |_ node_modules/
      |_ renderer.js
      |_ visitor.py
      |_ download.py

I tried putting everything in `files: [...]` in `package.json` under `build > files` and then ran `npm run dist`.
I also tried copying python files to `dist` folder explicitly and then ran `npm run dist`.
None are working.

> /Application/test.app/Contents/Resources/app.asar/remderer.js:226
> Error: python: can't open file 'visitor.py': [Error 2] No such file or
> directory

This is my package.json

    {
      "name": "test",
      "version": "1.0.0",
      "description": "",
      "main": "main.js",
      "scripts": {
        "start": "electron .",
        "pack": "build --dir",
        "dist": "build"
      },
      "author": "",
      "license": "ISC",
      "build": {
        "appId": "com.example.app",
        "files": [
          "dist/",
          "node_modules/",
          "index.html",
          "main.js",
          "package.json",
          "renderer.js",
          "styles.css",
          "visitor.py",
          "download.py"
        ],
        "dmg": {
          "contents": [
            {
              "x": 110,
              "y": 150
            },
            {
              "x": 240,
              "y": 150,
              "type": "link",
              "path": "/Applications"
            }
          ]
        },
        "linux": {
          "target": [
            "AppImage",
            "deb"
          ]
        },
        "win": {
          "target": "squirrel",
          "icon": "build/icon.ico"
        }
      },
      "dependencies": {
        "csv-parse": "^2.5.0",
        "electron-css": "^0.6.0",
        "npm": "^6.1.0",
        "python-shell": "^0.5.0",
      },
      "devDependencies": {
        "electron": "^2.0.3",
        "electron-builder": "^20.19.1"
      }
    }

  [1]: https://www.npmjs.com/package/python-shell

**Comment by wandonye** [comment]
I have a similar question. I am using this approach:
https://github.com/fyears/electron-python-example
with electron-build instead of electron-package in the tutorial. I'm looking for method to include python exe into bundled app using electron-build

**Comment by pronebird** [comment]
You should be able to bundle anything within `extraResources` section. Not sure why the files section does not work. Also, it's strange that you want to bundle `dist/` into the app. I think `dist/` is a default output folder for the installer.
