### ISSUE TITLE
NSIS application crashes on install and launch

### ISSUE THREAD

**Issue by talmukund** [electron-userland/electron-builder#3083]
20.14.7

* **Version**: 

Windows-NSIS
* **Target**: 

We are packaging our application using electron builder. For 2008 server and windows 7 machine, when application gets launched after install, it crashes immediately. Though if we close the error and launch our application again, it never crashes.

![image](https://user-images.githubusercontent.com/13693156/42373822-a602fce8-8133-11e8-83b8-790ce86b6ebd.png)

**Comment by pronebird** [comment]
Maybe it gets launched in a wrong working directory.

**Comment by talmukund** [comment]
@pronebird I think this issue was fixed in latest version. I will verify it once again.
