### ISSUE TITLE
Include vue-cli-plugin-electron-builder in boilerplate section

### ISSUE THREAD

**Issue by nklayman** [electron-userland/electron-builder#3087]
Would it be possible to include my tool, [vue-cli-plugin-electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder), in the boilerplate section of the docs? While it isn't really a boilerplate, it sets up electron-builder in a Vue CLI 3 app. I noticed that the section lacked any Vue-related boilerplates and I think my plugin would be a great addition.

Thanks for your consideration!

**Comment by develar** [comment]
@nklayman Vue supported via electron-webpack. But your tool is actuallly `Vue CLI 3 plugin`, so, thanks a lot.

**Comment by develar** [comment]
Added to both site and GitHub project readme.
