### ISSUE TITLE
Blockmap Comparision Fails for AWS S3

### ISSUE THREAD

**Issue by developeryashraj** [electron-userland/electron-builder#3091]
* **Version**: 20.19.2

* **Target**: Windows

I found that when we use S3 as a provider then it fails to compare and check blockmap files [at this place](https://github.com/electron-userland/electron-builder/blob/v20.19.2/packages/electron-updater/src/NsisUpdater.ts#L152). This is the log of `fileInfo`, `newBlockMapUrl` and `oldBlockMapUrl` Object.

**Fileinfo :-**
```
{
  url: URL{
    href: 'https://AWS_S3_HOST//bucket-yashraj/electron%20Setup%2011.0.3.exe',
    origin: 'https://AWS_S3_HOST',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'AWS_S3_HOST',
    hostname: 'AWS_S3_HOST',
    port: '',
    pathname: '//bucket-yashraj/electron%20Setup%2011.0.3.exe',
    search: '',
    searchParams: URLSearchParams{
      
    },
    hash: ''
  },
  info: {
    url: 'electron Setup 11.0.3.exe',
    sha512: 'k3seJ1BoSsaxAxODNJqhf7xUh6vfQUflvU+qu0mXXiuBFb8gpvt0oDS2rJm6gP+4lEilw6Gt8bt7BbimXftVNQ==',
    size: 52021199
  }
}
```
**newBlockMapUrl :-**
```
{
  url: URL{
    href: 'https://bucket-yashraj/electron%20Setup%2011.0.3.exe',
    origin: 'https://bucket-yashraj',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'bucket-yashraj',
    hostname: 'bucket-yashraj',
    port: '',
    pathname: '/electron%20Setup%2011.0.3.exe',
    search: '',
    searchParams: URLSearchParams{
      
    },
    hash: ''
  }
}
```
**oldBlockMapUrl :-**
```
{
  url: URL{
    href: 'https://bucket-yashraj/electron%20Setup%2011.0.3.exe',
    origin: 'https://bucket-yashraj',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'bucket-yashraj',
    hostname: 'bucket-yashraj',
    port: '',
    pathname: '/electron%20Setup%2011.0.3.exe',
    search: '',
    searchParams: URLSearchParams{
      
    },
    hash: ''
  }
}
```
You can see that **AWS_S3_HOST** is removed from `newBlockMapUrl` and `oldBlockMapUrl` objects. So it will never get blockmap files!!. 

I have checked with replacing `${fileInfo.url.pathname}` with `${fileInfo.url.href}` and have checked for both provider `s3` and `general` and it is working fine.

@develar I am also creating  PR to get reviewed by you if it is proper solution and to make electron better!! :slightly_smiling_face:

**Comment by developeryashraj** [comment]
@develar Line with `electron-publisher-s3` information can be removed now from https://www.electron.build/configuration/publish under **S3Options** as it has already been improved in release [20.19.0](https://github.com/electron-userland/electron-builder/releases/tag/v20.19.0)

**Comment by developeryashraj** [comment]
@develar can you guide me on this issue to solve it? or the PR #3092 will work ok for a while until you give a new release with the proper solution.!

**Comment by develar** [comment]
@developeryashraj I think issue is that your file url contains double slash after host name. It should be fixed now.

**Comment by develar** [comment]
```
"publish": [
  {
    "provider": "s3",
    "bucket": "bucket-yashraj",
    "endpoint": "https://AWS_S3_HOST/"
  }
]
```

Do not use `endpoint`. Or remove trailing slash.

**Comment by developeryashraj** [comment]
@develar Thanks for the reply. Let me give it a try and come back here with the updates.

**Comment by developeryashraj** [comment]
@develar It was my bad. It's just that trailing slash `"/"` in the endpoint :unamused: Thanks for the help. :+1: It's working !!

**Comment by develar** [comment]
Let me keep it open since it is electron-builder failure to not strip trailing slash. Humans have a right to make mistakes.
