### ISSUE TITLE
Compiled Auto-Updater don't work with private gitlab repository

### ISSUE THREAD

**Issue by MrCodingMen** [electron-userland/electron-builder#3094]
* **Version**: 20.19.2 

* **Target**: NSIS windows

When I start Electron via `npm start`, the auto-updater works. However, when I compile and start Electron, the following error occurs: `Cannot find channel "latest.yml" update info: HttpError:404` .

**Screenshots**
http://prntscr.com/k48se7

**Comment by didmehh** [comment]
i can't work also.

```error
Cannot parse update info from latest.yml in the latest release artifacts (http://git.example.cn/group/respo/tree/updater/dist/latest.yml?noCache=1ci1h2p2g): YAMLException: end of the stream or a document separator is expected at line 3, column 17:
    <head prefix="og: http://ogp.me/ns#">
```

**Comment by artemgood** [comment]
@develar can you say what could be the problem?

**Comment by artemgood** [comment]
I solved the problem for myself, the problem was in the noCache parameter (latest.yml?noCache=XXXXX). As a result, I returned to the version of the "electron-updater": "2.21.4"
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/providers/GenericProvider.ts#L21 , this.updater.isAddNoCacheQuery.

**Comment by ashxdev** [comment]
Hi @artemgood, do you use private gitlab repository? Could you provide how do you set settings for token?
Thanks.

**Comment by artemgood** [comment]
@ashxdev yes, i use private repository. 
For example:
```
autoUpdater.requestHeaders = { "PRIVATE-TOKEN": "Personal access Token" };
autoUpdater.autoDownload = true;

autoUpdater.setFeedURL({
    provider: "generic",
    url: "https://gitlab.com/_example_repo_/-/jobs/artifacts/master/raw/dist?job=build"
});
```

**Comment by MrCodingMen** [comment]
Hello, I have the problem that the package.json says that I want to use version 2.21.4 of electron-updater: "electron-updater": "^2.21.4".
However, Gitlab has the following in the console:
` ├electron-updater@2.23.3┬ ─ `

.gitlab-ci.yml: https://hastebin.com/baqiqetixu.coffeescript
scripts from package.json: https://hastebin.com/wicunigeji.bash

How can I downgrade to version 2.21.4?

**Comment by develar** [comment]
Duplicates #3094

**Comment by AlanZou007** [comment]
@didmehh as this problem been solved?

**Comment by Hector1567XD** [comment]
> @didmehh as this problem been solved?
In the duplicate they mentioned it was a problem of electron updater versions and it worked for me by updating!
