### ISSUE TITLE
Include main category for inferred DEB desktop entries

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#3098]
* **Version**: 20.19.2

* **Target**: Linux (`.deb`)

For the inferred entries here https://github.com/electron-userland/electron-builder/commit/c050b5206fc86584271644674590c31292d41f14#diff-5ca12bdfd89d325ac75e075de69ff64bR261, you need to also set a main category.

For example
`"public.app-category.social-networking": "Chat",`
should be
`"public.app-category.social-networking": "Network;Chat",`

---

> Note that at least one Main Category must be included in the desktop entry's list of categories. - https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html

**Comment by develar** [comment]
And `Office;Finance`
