### ISSUE TITLE
Sign both windows&osx

### ISSUE THREAD

**Issue by burakcan** [electron-userland/electron-builder#310]
We're developing a cross platform app which we build using electron-builder(travis, osx machine). Code signing for osx is working but i couldnt understand how to specify the certificates for windows (i have my pfx file). Should i seperate builds for each platform?

**Comment by develar** [comment]
It is not yet possible to sign windows on OS X platform. See https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build So, yes, you have to setup CI agent on windows.

**Comment by develar** [comment]
> couldnt understand how to specify the certificates for windows

In the same way as for OS X. See https://github.com/electron-userland/electron-builder#code-signing 

Just set CSC_LINK/CSC_KEY_PASSWORD.

**Comment by burakcan** [comment]
thanks @develar :100:
