### ISSUE TITLE
electron-builder does not copy directories named "node_modules" into my application

### ISSUE THREAD

**Issue by SJ-AW** [electron-userland/electron-builder#3104]
electron-builder: >= 20.15.2
target: Windows, Mac OS, Linux

Hi everyone,

Since the new solution for copying node_modules (cf. https://github.com/electron-userland/electron-builder/releases/tag/v20.15.2), is not possible anymore to pass node_modules directory in electron package during build.

My electron app follows this structure:

```
├── dist_electron
|   ├── electron-main
|   ├── electron-renderer
|   └── webapp-bundle
|        ├── dist
|        └──  node_modules
|
├── index.js
├── package.json
```

My electron-builder config:

```
config = {
  appId: `AppName`,
  directories: {
    output: 'dist_electron/electron-binaries',
    buildResources: 'src/electron/resources'
  },
  asar: true,
  files: [
    'index.js',
    'dist_electron',
    '!dist_electron/electron-binaries'
    '!node_modules',
    'package.json',
  ]
  ...
}
```

I don't need to electron-builder copies node_modules from my package.json dependencies.

My bundles are compile with webpack and for my webapp-bundle I need to add a node_modules directory with uncompilable modules.

Before electron-builder 20.15.2 it's was possible to copy directories named "node_modules".

So my question is: How can I copy children directories named 'node_modules' into my application? I don't find any option or other informations.

Thanks

**Comment by pronebird** [comment]
You may want to ditch the Webpack, because there are no HTTP requests running between hard drive and Electron binary, and all assets and code are already bundled into ASAR archive.

**Comment by SJ-AW** [comment]
I use electron to make a launcher. So the idea is to have the possibility to launch different web apps than I compiled with Webpack before. So I need Webpack.

**Comment by develar** [comment]
I don't have time to prepare answer yet, but workaround for now: use afterPack hook. Use hook like https://www.electron.build/configuration/win#how-do-delegate-code-signing (no such clear docs for afterPack :()

define `afterPack` under `build`.

**Comment by ncaq** [comment]
Maybe, to use [Two package.json Structure - electron-builder](https://www.electron.build/tutorials/two-package-structure) solve it.

**Comment by bosspan** [comment]
Same problem for me. Have you solved it?

**Comment by dmnsgn** [comment]
> I don't have time to prepare answer yet, but workaround for now: use afterPack hook. Use hook like [electron.build/configuration/win#how-do-delegate-code-signing](https://www.electron.build/configuration/win#how-do-delegate-code-signing) (no such clear docs for afterPack :()
> 
> define `afterPack` under `build`.

@develar How would that work with `asar:true`? If I am copying my `node_modules` folder with a mix of `context.packager.info.projectDir` and 	`context.appOutDir`, `resources/app/` (or `Contents/Resources/app`) will exist without asar but will throw a `ENOENT: no such file or directory` with asar true.

**Comment by Timmmm** [comment]
I guess you guys are all talking about [this](https://www.electron.build/configuration/contents#files) annoying feature:

> `package.json` and `**/node_modules/**/*` is added to your custom [`files` entry] in any case.

Pretty annoying! I want Electron-builder to *only* add the entries in `files`. It seems like Vue's electron-builder plugin's solution is to copy `package.json` into your `dist` directory, and then run electron-builder there (or pass the `--app` command line option I guess). Then there is no `node_modules` directory to copy.

> You may want to ditch the Webpack, because there are no HTTP requests running between hard drive and Electron binary, and all assets and code are already bundled into ASAR archive.

Right but Webpack does more than just bundling Javascript. It can process images, compile Typescript, add mocks, minify Javascript, etc.

**Comment by AndiMelnikk** [comment]
В мене спрацювало, добавити це в package.json :   

"build": {
    "includeSubNodeModules" : true
  }

**Comment by AndiMelnikk** [comment]
It worked for me to add this to package.json:

"build": {
"includeSubNodeModules": true
}

**Comment by Valeaal** [comment]
In the package.json:
 "files": [
      [...],
      {
        "from": "[...]/node_modules",
        "to": "[...]/node_modules",
        "filter": [
          "**/*",
          "!**/.bin/**"
        ]
      },
      {
        "from": "[...]/node_modules/.bin",
        "to": "[...]/node_modules/.bin"
      }
    ],

make sure to copy .bin in the end, if not, you'll receive the error "ENOENT: no such file or directory, symlink", at least on electron-builder 23.6
