### ISSUE TITLE
download-progress never fires, everything else works for update.

### ISSUE THREAD

**Issue by uclaitsscott** [electron-userland/electron-builder#3106]
"electron-builder": "^20.19.2"
"electron-updater": "^2.23.3"
nsis

My application generally works, however; download-progress is never called, while all others are called. Below is my code:

autoUpdater.on('checking-for-update', () => {
    log.info('Checking for update...');
});

autoUpdater.on('update-available', (ev, info) => {
    log.info('Update Available.');
});

autoUpdater.on('update-not-available', (ev, info) => {
    log.info('Update not available.');
    winUpdate.webContents.send('update-progress', 100);
    winUpdate.close();
    win.show();
});

autoUpdater.on('error', (ev, err) => {
    winUpdate.webContents.send('update-progress', 100);
    log.info('Error in auto-updater...');
});

autoUpdater.on('download-progress', (obj) => {
    log.info("download-progress");    
    winUpdate.webContents.send('update-progress', obj.percent);
});

autoUpdater.on('update-downloaded', (ev, info) => {
    log.info('Update downloaded; will install in 3 seconds.');
    winUpdate.webContents.send('update-progress', 100);
    setTimeout(() => {
        autoUpdater.quitAndInstall();
    }, 3000);
});

**Comment by tmirun** [comment]
i have same problem

**Comment by TonyLiuYan** [comment]
when differential update the  download-progress never fires

**Comment by develar** [comment]
Duplicates #2521

**Comment by gmonte** [comment]
Same problem here! 
I have an app that works in macOS and Windows.
macOS fire this listener, but Windows never fire this.

My dependencies:
`
    "electron": "^3.0.10",
    "electron-reload": "^1.3.0",
    "electron-builder": "^20.36.2",
    "electron-publish": "^20.37.0",
    "electron-updater": "^4.0.4"
`

**Comment by Oscabrera** [comment]
the solution is use electron-differential-updater 

https://www.npmjs.com/package/electron-differential-updater

**Comment by Rain-Pavilion** [comment]
I encountered the same problem caused by my server not returning the file size when downloading the file.
