### ISSUE TITLE
Is there a way to change only CFBundleDisplayName via config?

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-builder#3109]
* **Version**:  20.4.1

* "electron-updater": "2.20.1"

* **Target**: mac

I need to be able to change CFBundleDisplayName without affecting CFBundleName i.e. I want my app menu bar to be other than the one used in the .app file and folder, mostly because I use auto updates and I don't want users losing personal data when upgraded to a version with a new productName.

**Comment by develar** [comment]
```
"extendInfo": {
  "CFBundleDisplayName": "My Awesome Name"
}
```

under `build` or in your `electron-builder.json` (yml, yaml and so on).
