### ISSUE TITLE
Why is the default an invalid argument?

### ISSUE THREAD

**Issue by ZapUser77** [electron-userland/electron-builder#3110]
* **Version**: 

* **Target**: Raspberry Pi 3, Arch: armv7l

Why is it not detecting my system armv7l?  And why is your default an invalid argument?

electron-builder install-app-deps

Install app deps

Options:
--version Show version number [boolean]
--help Show help [boolean]
--platform The target platform
[choices: "linux", "darwin", "win32"] [default: "linux"]
--arch The target arch
[choices: "ia32", "x64", "armv7l", "arm64", "all"] [default: "arm"]

Invalid values:
Argument: arch, Given: "arm", Choices: "ia32", "x64", "armv7l", "arm64", "all"

**Comment by ZapUser77** [comment]
You want me to send a press release?  Or a Public Relations?

I'm trying to install an app, Zap wallet, and get the above error, and I reported the problem to them, they told me to report it to you.

https://github.com/LN-Zap/zap-desktop/issues/418

**Comment by develar** [comment]
PR stands for "pull request". I will fix it soon.

**Comment by ZapUser77** [comment]
Why was the ticket closed?  Default still is arm.  Just tried it.

**Comment by develar** [comment]
What version have you tried, please attach screenshot of error.

**Comment by ZapUser77** [comment]
pi@raspberrypi:~/source/zap-desktop $ sudo npx electron-builder install-app-deps
electron-builder install-app-deps

Install app deps

Options:
  --version   Show version number                                      [boolean]
  --help      Show help                                                [boolean]
  --platform  The target platform
                        [choices: "linux", "darwin", "win32"] [default: "linux"]
  --arch      The target arch
             [choices: "ia32", "x64", "armv7l", "arm64", "all"] [default: "arm"]

Invalid values:
  Argument: arch, Given: "arm", Choices: "ia32", "x64", "armv7l", "arm64", "all"

**Comment by develar** [comment]
Do you use 20.23.0?

**Comment by ZapUser77** [comment]
I don't know what your asking, or where to find the answer.

You need to be more specific than a string of numbers.. or "What version?"  
What version of what?  I'm guess electron... but I have no idea where to locate the answer. 

So, when you ask me a question, please be specific, and include *how* to find the answer as well.

Thanks.

**Comment by develar** [comment]
Please ensure that electron-builder version is set to `20.23.1` in your `package.json`. 

If you use electron-builder globally, please upgrade it using `npm install -g electron-builder@next`

Please note — since electron-builder is very popular and widely used I cannot publish release for all as soon as it is released. So, npm tags are used. Your bug is fixed in the pre-release version and so, you need to specify tag `electron-builder@next` if you want to use this version. Simple `npm upgrade` will not update to this version.

**Comment by develar** [comment]
You can check version using `sudo npx electron-builder install-app-deps --version`

**Comment by ZapUser77** [comment]
Ok, changed the package.json dependancy to 20.23.1.
No longer get the default error.
Thanks.
