### ISSUE TITLE
Out of Memory during installation

### ISSUE THREAD

**Issue by ZapUser77** [electron-userland/electron-builder#3114]
* **Version**: 

* **Target**: 
Raspberry Pi 3
With 1 gig of ram

Issuing this command:
sudo npx electron-builder install-app-deps --arch=armv7l

Absolutely nothing else was running, 900MB out of 1 gig of ram was free when started

Runs for several hours then yields:
<--- Last few GCs --->

[1135:0x38d6648]  1676547 ms: Mark-sweep 496.7 (522.4) -> 496.7 (507.4) MB, 2058.7 / 0.0 ms  (average mu = 0.815, current mu = 0.000) last resort GC in old space requested
[1135:0x38d6648]  1678583 ms: Mark-sweep 496.7 (507.4) -> 496.7 (507.4) MB, 2036.2 / 0.0 ms  (average mu = 0.686, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x502061dc]
    1: StubFrame [pc: 0x5025ab7c]
Security context: 0x5fc1263d <JSObject>
    2: replace [0x5fc0b951](this=0x6ee048d9 <Very long string[141687589]>,0x6ee0490d <JSRegExp <String[5]: \r?\n>>,0x6ee04929 <String[12]\: \x1b[39m$&\x1b[31m>)
    3: applyStyle [0x27eb5581] [/home/pi/source/zap-desktop/node_modules/chalk/index.js:197] [bytecode=0x30761ba1 offset=354](this=0x6ee0465d <JSFunction builder (sfi = 0x30...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted

**Comment by develar** [comment]
> home/pi/source/zap-desktop/node_modules/chalk/index.js:197

It is application error, not electron builder.

**Comment by lineCode** [comment]
> * **Version**:
> 
> * **Target**:
>   Raspberry Pi 3
>   With 1 gig of ram
> 
> Issuing this command:
> sudo npx electron-builder install-app-deps --arch=armv7l
> 
> Absolutely nothing else was running, 900MB out of 1 gig of ram was free when started
> 
> Runs for several hours then yields:
> <--- Last few GCs --->
> 
> [1135:0x38d6648] 1676547 ms: Mark-sweep 496.7 (522.4) -> 496.7 (507.4) MB, 2058.7 / 0.0 ms (average mu = 0.815, current mu = 0.000) last resort GC in old space requested
> [1135:0x38d6648] 1678583 ms: Mark-sweep 496.7 (507.4) -> 496.7 (507.4) MB, 2036.2 / 0.0 ms (average mu = 0.686, current mu = 0.000) last resort GC in old space requested
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> ```
> 0: ExitFrame [pc: 0x502061dc]
> 1: StubFrame [pc: 0x5025ab7c]
> ```
> Security context: 0x5fc1263d 
> 2: replace [0x5fc0b951](this=0x6ee048d9 <Very long string[141687589]>,0x6ee0490d <JSRegExp <String[5]: \r?\n>>,0x6ee04929 <String[12]: \x1b[39m$&\x1b[31m>)
> 3: applyStyle [0x27eb5581] [/home/pi/source/zap-desktop/node_modules/chalk/index.js:197] [bytecode=0x30761ba1 offset=354](this=0x6ee0465d <JSFunction builder (sfi = 0x30...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> Aborted

how can resolve it
