### ISSUE TITLE
Add hook to run a command right before publishing

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#3116]
* **Version**: 20.20.4

* **Target**: macOS

I need a hook to be able to run a script right before `electron-builder` publishes the artifacts to GitHub. `afterSign` is almost what I need, but it says "(but before pack into distributable format)". I need to run it after packing into distributable format, when all the distributable files are completely done.

**Comment by develar** [comment]
> when all the distributable files are completely done.

It is not serial process. As soon as there is something to publish, it is published.

What exactly do you want to do? Maybe more high-level functionality can be added?

**Comment by sindresorhus** [comment]
> What exactly do you want to do? Maybe more high-level functionality can be added?

I need to produce a PGP-signed checksum file with hashes of all the distributables, so users can be sure the files are not modified and comes from us.

Example: https://github.com/atomiclabs/hyperdex/releases/tag/v0.1.0-alpha.9 (Look at the `SHASUMS256.txt.asc` file) 

Right now, we generate it by downloading all the distributables after publishing and then manually uploading the checksum file. (https://github.com/atomiclabs/hyperdex/blob/master/signedchecksum)

**Comment by develar** [comment]
Ok. Do you use CLI or low-level programmatic API `Packager`?

**Comment by sindresorhus** [comment]
The CLI with config in package.json.

**Comment by develar** [comment]
https://tools.ietf.org/html/rfc4880#section-7

**Comment by develar** [comment]
Since you are VIP user, will be fixed today.

**Comment by develar** [comment]
Ideally, we can use go lib and produce it on the fly, but for now just a hook `afterAllArtifactBuild` will be added to allow users to do whatever is needed.
