### ISSUE TITLE
Possible to automatically require NSIS click-once installer to run elevated?

### ISSUE THREAD

**Issue by neilrees** [electron-userland/electron-builder#3117]
* **Version**: 20.19.2

* **Target**: NSIS

I have a some configuration steps that need to be performed at install time which currently elevate individually.  Is it possible to get the entire installer to require elevation at the start, but still use the oneClick installer and do a per-user install?

Switching to the boring installer and per machine does require elevation, but is it possible for a oneClick installation?

```
"win": {
  "target": [
    "nsis"
  ]
},
"nsis": {
  "oneClick": true
}
```

**Comment by develar** [comment]
Have you tried to set `perMachine: true` (under `nsis`)?

**Comment by develar** [comment]
Got your question. Need to investigate, should be possible.

**Comment by neilrees** [comment]
Settng `"oneClick": true` and `perMachine: true` does indeed produce an installer that automatically elevates but the installation goes to \Program Files rather than $AppData.

On reflection, I'm not sure the combination I'm asking for makes sense - if the installer requires elevation then it's performing machine wide setup changes and so should be probably be installed into \program files.

**Comment by jonasem** [comment]
For us it would make sense, as our installer launches other installers for drivers we need to work, which are installed per machine. The annoying part now is that if the installer is not in focus when elevate privileges are beeing invoked, the elevation prompt doesn't show up. It just appears as a minimized icon on the start menu until you open it, leaving the user to believe the installer is frozen.
