### ISSUE TITLE
How to verify checksums manually?

### ISSUE THREAD

**Issue by mobitar** [electron-userland/electron-builder#3119]
I'm trying to verify checksums of files manually, but the result I'm getting doesn't match what's published.

For example, for [Onshape-0.5.18-x86_64.AppImage](https://github.com/develar/onshape-desktop-shell/releases/tag/v0.5.18), the published sha512 checksum is 
```
aJB+pb9ueyI7+KQfIQ2s4GZ4ISE1yXLtgZ5/RVFU813DBRPfwy5RtIMQNMKRHJ6Lqyc9rlbWr56zG0Zl6tif6g==
``` 

However, when I run 
```
openssl dgst -sha512 Onshape-0.5.18-x86_64.AppImage
```
 or 
```
shasum -a512 Onshape-0.5.18-x86_64.AppImage 
```
I get 
```
68907ea5bf6e7b223bf8a41f210dace06678212135c972ed819e7f455154f35dc30513dfc32e51b4831034c2911c9e8bab273dae56d6af9eb31b4665ead89fea
```
 which in base64 is 
```
Njg5MDdlYTViZjZlN2IyMjNiZjhhNDFmMjEwZGFjZTA2Njc4MjEyMTM1Yzk3MmVkODE5ZTdmNDU1MTU0ZjM1ZGMzMDUxM2RmYzMyZTUxYjQ4MzEwMzRjMjkxMWM5ZThiYWIyNzNkYWU1NmQ2YWY5ZWIzMWI0NjY1ZWFkODlmZWE=
```

Are the checksums for the contained asar file only?

**Comment by mobitar** [comment]
Sorry, I had this wrong. I was converting the sha512 as ASCII to base64, rather than converting the sha512 binary data to base64. Doing it correctly matches up.

**Comment by develar** [comment]
Source code: https://github.com/develar/app-builder/blob/master/pkg/blockmap/blockmap.go

**Comment by develar** [comment]
`blake2b` not used because still NodeJS is used for electron-updater and in any case blake2b is not convenient for users.

**Comment by strikeflare** [comment]
This question is already closed but I would like to know how I can verify the checksum of an NSIS installer made by Electron-Builder manually. 

If I have following checksum in latest.yml:
`ZkkPBBqhX8vkq71iTcV+xvKyqcVCVVSpBDkQujDeMyzrp4tFCsW0KwTQBJXcJVuaxYyhCKNTA7t4RL0AhnyMrg==`

And a NSIS installer myElectronInstaller.exe:

When I check the installer with OpenSSL:
`openssl dgst -sha512 .\myElectronInstaller.exe`

Or with Powershell:
`Get-FileHash -Path .\resources\myElectronInstaller.exe -Algorithm SHA512`

I will get a different result:
`c4f0c2e3bb0add9f5ece7431901d7f09972661ec6e856c27c133be6a253223ed2b1ce4a1ac933383b7292547e6aec784286f31f183bba5762ad73fd99c299690`

Is there any documentation how an user can verify the checksum? Or how Electron Auto Updater verifies the checksum after he has downloaded an update?

**Comment by shalomthegreat** [comment]
In case anyone else needs this, szTheory [posted a solution](https://github.com/szTheory/exifcleaner/issues/119#issuecomment-830718034) in one of the sub issues. This works on mac at least (haven't tested the others): `shasum -a 512 {file_location} | cut -f1 -d\\ | xxd -r -p | base64`
