### ISSUE TITLE
Command not found error after upgrading from 2.11.0 to 3.0.0 (and beyond)

### ISSUE THREAD

**Issue by robwilkerson** [electron-userland/electron-builder#312]
I have an app that builds and packages just fine with the following top level npm modules:

```
├── electron-builder@2.11.0
├── electron-packager@6.0.2
└── electron-prebuilt@0.36.12
```

As soon as I upgrade to `electron-builder@3.0.0` (I've also tried 1 or 2 later versions), I get this error:

> sh: electron-builder: command not found

The command I'm running looks like this:

```
electron-builder \"dist/osx/My App-darwin-x64/My App.app\" \
    --platform=osx 
    --out=dist/osx/ 
    --config=build/config.json
```

I haven't found anything to indicate that something in either my command usage or my system config needs to change, but maybe I'm looking in the wrong places or not reading something carefully enough?

**Comment by develar** [comment]
Since 2.8 we have a new API and old API was removed in the 3.0. Please see https://github.com/electron-userland/electron-builder#in-short (and note about [Two package.json structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure)
