### ISSUE TITLE
Code signing failed on Mac and Windows builds (Error: connect ECONNREFUSED 127.0.0.1:443)

### ISSUE THREAD

**Issue by hans-permana** [electron-userland/electron-builder#3121]
* **electron-build version**: 19.56.2
* **electron-updater version**: 2.20.1

* **Target**: MacOS & Windows

Hi guys, I had some successful builds using the same electron build version and suddenly I got an error today when trying to build again. The previous build was 28 days ago. I did a build for Linux, Windows, and MacOS, and I got an error only on MacOS and Windows (due to the signing). 

The full stacktrace can be found here (MacOS) https://travis-ci.org/CCI-Tools/cate-installer/jobs/404454285 and here (Windows) https://ci.appveyor.com/project/ccitools/cate-installer/build/164

And here is the source code of the project: https://github.com/CCI-Tools/cate-desktop

I have spent multiple hours to debug this issue without any significant returns. I thought it was an issue of Travis or AppVeyor not allowing a specific connection, but I can actually reproduce it on my local Mac and Windows machines. Could you point me to a more obvious direction on where to look to solve this issue?

Cheers,
Hans

**Comment by hans-permana** [comment]
turned out that it was an issue of reaching the certificate file via the provided URL stored in CSC_LINK variable. The reason as to why the downloadable link was suddenly unreachable is still unknown, but the solution was to change the format of the URL. 

A suggestion: it would be nice to show a more informative error message when this happens (eg. why it needs to connect to 127.0.0.1:443, what is the request, etc.). This will save hours spent on debugging this kind of error.

**Comment by develar** [comment]
It is more clear in a latest version of electron-builder.

**Comment by zzzZZZ1117** [comment]
The pending stream has been canceled (caused by: connect ECONNREFUSED 51.15.76.176:443)

I don't know what it's for
