### ISSUE TITLE
Fatal error: Unable to commit changes

### ISSUE THREAD

**Issue by 819460357** [electron-userland/electron-builder#3122]
Error: Exit code: 1. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.1.0\rcedit-x64.exe F:\workspace\tzs\trunk\code\front_end\pc\merch-end\electron-app\packers\win-unpacked\ybs.exe --set-version-string FileDescription ybs --set-version-string ProductName
ybs --set-version-string LegalCopyright zzs --set-file-version 0.0.7 --set-product-version 0.0.7.0 --set-version-string InternalName ybs --set-version-string OriginalFilename  --set-version-string CompanyName lzj --set-icon F:\workspace\tzs\trunk\code\front_end\pc\merch-end\electron-app\favicon.ico                                      help!

**Comment by navono** [comment]
always show this error in my CI machine. I've tried to restart machine and not work.

**Comment by yft** [comment]
https://github.com/electron-userland/electron-packager/issues/590

**Comment by develar** [comment]
Please try 21.0.11
