### ISSUE TITLE
How to add a custom page/field to NSIS setup

### ISSUE THREAD

**Issue by dominicdesu** [electron-userland/electron-builder#3124]
Hello,
I would like to let the user insert a custom value during NSIS setup of my electron app and then pass this value to the application.
I thought I could add a TextField to the installer and save this value to a file, which I later read from the application (don't know if there is an easier way?)

As I have no experience with NSIS, I'd like to ask if this is possible at all with the current integration of NSIS into electron-builder and if you could give me a hint what to look for?
All the example I looked at on the NSIS site show how to create a complete installer with pages, but as far as I can see in electron-builder I would need to insert the page as a macro?

Thanks,
Dominic

**Comment by sarada123** [comment]
Hi, I am also wants to add a macro to update client database with the new database.But now it is replacing all the content with the new installer content.Do you have any idea on how to use app.getPath('userData')
if Yes,Please let me share it may be helpful for me
Thanks in advance

**Comment by agpreynolds** [comment]
Hi, I have a similar requirement to create a custom installer page, did either of you ever figure out how to do this?

**Comment by minhtan143** [comment]
This is a necessary feature
