### ISSUE TITLE
Electron-updater confusion with import/repos

### ISSUE THREAD

**Issue by tzarebczan** [electron-userland/electron-builder#3125]
* **Version**: 

* **Target**: 

The electron-updater page says that it's now part of electron-builder, but the docs say:
```
Use autoUpdater from electron-updater instead of electron:

import { autoUpdater } from "electron-updater"
```

Does that mean we still require electron-updater in our package.json?

**Comment by develar** [comment]
https://www.electron.build/auto-update/#quick-setup-guide 

Step one.
