### ISSUE TITLE
Electron auto updates functionality

### ISSUE THREAD

**Issue by sarada123** [electron-userland/electron-builder#3126]
electron-builder 19.47.1

* **Version**: 

electron-updater 2.21.10

For windows
* **Target**: 

My application is a desktop application and i want to send notifications to those who already installed the installer in their systems.For that i copied all the code you specified in your links.but i am not getting any notifications.
I am new to electron as well as for electron auto updates.let me know how to do this
I have searched for a complete and fully working example for that,but unfortunately i did not find any relavent link.Please help me in resolving this issue as early as possible
High Prioriy

**Comment by develar** [comment]
Do you use `checkForUpdatesAndNotify`?

See https://github.com/electron/electron/issues/10864

**Comment by sarada123** [comment]
yes i am calling checkForUpdatesAndNotify Method in app.on("ready")
But no luck

**Comment by akshitkrnagpal** [comment]
@sarada123 
Please try using  `electron-log`

Add this after importing autoUpdater.
```
autoUpdater.logger = require("electron-log")
autoUpdater.logger.transports.file.level = "info"
```
You'll get more info on what is going on.
