### ISSUE TITLE
Auto-updater running uninstall script

### ISSUE THREAD

**Issue by Alin13** [electron-userland/electron-builder#3128]
**Electron-builder**: 19.56.2
**Electron-updater**: ^3.0.1
**Target**: Windows

Build config:
```
"nsis": {
	"include": "windows/uninstall.nsh",
	"deleteAppDataOnUninstall": true
}
```

Uninstall.nsh:
```
!macro customUnInstall
	; remove the scheduled task + registry
!macroend
```

I'm using electron-updater to check and install new updates in my app, but I have a small issue regarding the above configs: when a new update is installed the `appData` is not removed (which is ok), but the `uninstall.nsh` is called (which is bad).
Is there a way to call `uninstall.nsh` just when the app is uninstalled manually and not on updates (just as the behavior for `appData`) ?

**Comment by develar** [comment]
Wrap your code into

```
${ifNot} ${isUpdated}
${endIf}
```

**Comment by Alin13** [comment]
Wow, that was a quick response. Thank you very much !

**Comment by develar** [comment]
Note — we are not going to simplify and introduce yet another macro, because this feature ONLY for those, who understand what they are doing. And so, additional level of magic is not acceptable. I have added note to doc about `${isUpdated}` and `customUnInstall`.
