### ISSUE TITLE
Build and code signing with EV certificate and USB token device failed on win 7

### ISSUE THREAD

**Issue by ulver2812** [electron-userland/electron-builder#3133]
* **Version**: 20.0.5 

* **Target**: Windows

Hi, i'm trying to build on win 7 with an EV certificate and USB token device, I don't have any issue on win 10 but on win 7 the build process remain stuck on packaging step.

![cattura](https://user-images.githubusercontent.com/25301598/42949171-7b06b870-8b71-11e8-8639-b954b10bcc3b.PNG)

The build without certificate goes smoothly.

I think that the USB device token or the client software to manage it are not the culprit because I can sign any executable file using the the certificate authority software signing utility.

There's a verbose flag that I can use to run build command in order to get more debug information ?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

I guess that your version of " the certificate authority software signing utility", `signtool` is different to https://github.com/electron-userland/electron-builder-binaries/tree/master/winCodeSign/windows-6

You can try to replace signtool.exe in your caches (electron-builder/winCodeSign) (local app data) or set env `SIGNTOOL_PATH=your/path/to/signtool.exe`

**Comment by ulver2812** [comment]
Hi, thanks for the answer, I set the env `DEBUG=electron-builder`

**Comment by ulver2812** [comment]
I figured out the issue, it was related to this powershell command: `ConvertTo-Json`

It isn't supported on powershell 2.0, I updated the powershell to 3.0 and now the build goes smoothly.

@develar thanks for your help!
