### ISSUE TITLE
Building nsis installer using electron-builder trigger traps.

### ISSUE THREAD

**Issue by shaluyadav13** [electron-userland/electron-builder#3134]
When building the installer setup electron-builder executes the installer (..ie appName.exe) to extract the uninstaller (ie .__uninstaller-appName.exe) to sign it and then it repackages the setup again.

At this step the installer is NOT yet signed and triggers Traps.

The issue comes from ...\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js :: computeScriptAndSignUninstaller() in the line:
`await (0, _builderUtil().execWine)(installerPath, []);`

 A dirty workaround is to add code to sign the installer just before that line:
`await packager.sign(installerPath, " ...sign installer to prevent Traps interrupting the next call");`
`await (0, _builderUtil().execWine)(installerPath, []);`

However, this is not enough (...alas).  Internally, electron-builder will use Windows signtool.exe to sign, and the signing would fail if the target has cert records already. 

Any suggestions will be much appreciated. Thanks!

**Comment by neknalb** [comment]
We have the same problem here, too.

A solution to this would be more than welcome.
