### ISSUE TITLE
Allow user to set installation path

### ISSUE THREAD

**Issue by jraspiprojects** [electron-userland/electron-builder#3136]
There have been many requests (https://github.com/beakerbrowser/beaker/issues/1029) to allow the user to set the installation path for the program

**Comment by Zamiell** [comment]
This is already implemented, read the docs at electron.build, you have to specify an optional parameter in your package.json.

**Comment by jraspiprojects** [comment]
no, at installation time we need a text box specifing the path to the installation directory like and the default will be
<code>C:\Program Files\Program Name\</code>

**Comment by Imfdj** [comment]
https://www.electron.build/configuration/nsis
![image](https://user-images.githubusercontent.com/25856248/55711987-792daa80-5a20-11e9-90b7-811930309948.png)
