### ISSUE TITLE
Electron Updater - Error: The folder “app.zip” doesn’t exist

### ISSUE THREAD

**Issue by jebbdomingo** [electron-userland/electron-builder#3138]
* **electron-builder Version**: 20.19.2

* **electron-updater Version**: 2.23.3

* **Target**: Mac

When publishing the app via `yarn dist --publish always` I set it to generate both dmg and zip files (zip is required for auto-update in Mac) in GitHub release
i.e.
`my-app-1.0.0.dmg` and
`my-app-1.0.0-mac.zip`
but during auto-update, it looks for `my-app-1.0.0-mac.dmg` (with the `-mac`), manually renaming the file `my-app-1.0.0.dmg` to `my-app-1.0.0-mac.dmg` in GitHub release fixes the auto-update.

**Comment by develar** [comment]
electron-updater 3.4.0

**Comment by gryzzly** [comment]
@develar experiencing the same issue, but the `electron-updater@latest` is `3.1.2` for me

**Comment by gryzzly** [comment]
@develar sorry for noise, do you have a suggestion what else could we look at?

**Comment by develar** [comment]
@gryzzly Today major fixes were released as electron-updater 3.2.2. Also, please update electron and electron-builder.

At least, error message will be different, I am sure :) Also, please next time please provide logs (https://www.electron.build/auto-update#debugging)

**Comment by gryzzly** [comment]
@develar thanks for the reply! will be upgrading the updater and electron / electron-builder tomorrow. 

Unfortunately the logs would be problematic to provide as this is not really happening to any of the developers. But hopefully either updates will just fix the problem or new error messages we’d get from users would help us investigate.
