### ISSUE TITLE
Windows build failing on the Docker image (electronuserland/builder:wine-mono)

### ISSUE THREAD

**Issue by alanionita** [electron-userland/electron-builder#3143]
# Versions
    "electron": "^2.0.5",
    "electron-builder": "^20.24.2",
    "electron-builder-squirrel-windows": "^20.24.2",
# Target
Windows, with Squirrel event for a legacy auto-update
# Environment 
MacOS running a docker container from the docs  electronuserland/builder:wine-mono
# Issues

## timezone broken link
Initial issues with tzdata, but managed to fix that after an apt-get update & apt-get upgrade tzdata

## Cannot find winemenubuilder.exe

updated the docker image wine package and now I get 

```bash
Starting to read in Zip file!
Updating Resource!
Failed to update resource
Usage: WriteZipToSetup [Setup.exe template] [Zip File]

wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
```

EDIT: Updated "electron-builder-squirrel-windows" === > 20.24.2

**Comment by alanionita** [comment]
electron-builder-squirrel-windows@20.24.0 requires a peer of app-builder-lib@~20.24.0. 

I'm guessing this is electron-builder-lib but that is already installed.

    Module electron-builder-squirrel-windows must be installed in addition to build Squirrel.Windows:    Error: Cannot find module 'app-builder-lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)

**Comment by develar** [comment]
@alanionita Sorry for confusion — major version of `electron-builder-squirrel-windows` must be equals to major version of used electron-builder.

I have marked electron-builder `20.24.0` as latest.

**Comment by alanionita** [comment]
NPM lists 20.23.1 as the latest version for electron-builder

Trying to use 20.24.0 throws 

     npm ERR! code E404
     npm ERR! 404 Not Found: app-builder-lib@20.24.0

**Comment by alanionita** [comment]
Same error on the latest version. 

```bash
Error: Exit code: 255. Command failed: wine /root/.cache/electron-builder/Squirrel.Windows/Squirrel.Windows-1.7.8/WriteZipToSetup.exe /project/dist/squirrel-windows/ABB-GIS-PC Setup 1.2.9.exe /tmp/temp-dir-ZHW5rR/2-setup.zip
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)

    Starting to read in Zip file!
    Updating Resource!
    Failed to update resource
    Usage: WriteZipToSetup [Setup.exe template] [Zip File]
```

**Comment by marvi14** [comment]
@alanionita could you make this work? I'm trying also to build my windows squirrel app in this Docker image

**Comment by alanionita** [comment]
@marvi14 The build kept crashing because of Wine on Mac OS. From what I've been reading it the docker image could be a corrupted wine build. 

My only solution was to build on a Windows machine, but I haven't tried using the latest version of electron and electron-builder.

**Comment by desh901** [comment]
I had the same issue and i've solved installing `Xvfb`

On the **electronuserland/builder:wine*** container:
```
apt install xvfb
Xvfb :0 &
export DISPLAY=:0
yarn && yarn ship
```
