### ISSUE TITLE
20.24.2 - Unknown option "p"

### ISSUE THREAD

**Issue by peterdanis** [electron-userland/electron-builder#3146]
* **Version**:  20.24.2

* **Target**: all

Got error `Unknown option "p"` when setting `--publish never` via `-p` shortcut (`electron-builder -p never --x64`).

![image](https://user-images.githubusercontent.com/26599181/43004239-65854cd2-8c2f-11e8-9b49-2f6afd16225c.png)

**Comment by develar** [comment]
Yeah, I see that version was marked as latest too earlier...
