### ISSUE TITLE
Electron-builder with sqlite3

### ISSUE THREAD

**Issue by sarada123** [electron-userland/electron-builder#3147]
19.47.1

* **Version**: 

2.21.10

windows 7/windows10 and mac
* **Target**: 

I build the installer with nsis ia32 arch, I use sqlite3 and everything works fine until the update is downloaded since it replaces all the files in the installation folder.
Then my database file is deleted, how can I prevent my database file from being deleted with the new versions?

I am generating the installer using electron-builder of version 19.47.1,using the command
electron-builder --platform=win32

**Comment by bkniffler** [comment]
Does this help? https://github.com/electron-userland/electron-builder/issues/2667

**Comment by develar** [comment]
You should write db file to user data dir, not to app data dir.
