### ISSUE TITLE
Define withoutDir in zip target

### ISSUE THREAD

**Issue by CEikermann** [electron-userland/electron-builder#3148]
Hello,

I have a quick question about the zip targets.

We would like to zip the whole folder on MAC instead of just the "*.app" file. We have found out that the option "withoutDir" is by default set to true, which results into that only the "*.app" file will be zipped.

How can we set the option withoutDir to false or is there a other way to add files to the zip file made by electron builder (files adding to the zip file, not to the application content folder)

**Comment by CEikermann** [comment]
I guess this is the root cause:
https://github.com/electron-userland/electron-builder/blob/c35b3150536be66a9e1c2aae75f7e8f7f610699d/packages/app-builder-lib/src/targets/ArchiveTarget.ts#L39

Its by default always false on mac and can not be configured

**Comment by develar** [comment]
Could you please describe your use case? For what do you need to add additional files? Why DMG is not used?

**Comment by develar** [comment]
In general I recommend DMG, it allows you to provide extra files.

If you insist and sure that zip suitable for you, I can add option like extraDistFiles for Mac.


Btw, is auto update works for such zip?

**Comment by CEikermann** [comment]
A option like extraDistFiles sounds great, this means these files will be copied to the dist folder and will be part of the zip file for all distributions (mac, windows, ...) ?

We are not using the auto updater for our project

**Comment by develar** [comment]
Ok. You can expect feature this week, feel free to ping if need.

**Comment by CEikermann** [comment]
Oh that would be awesome, thanks very much :)

**Comment by CEikermann** [comment]
Hey @develar, do you have a quick update regarding this feature? :)

**Comment by develar** [comment]
@CEikermann Ok, two pings from a reasonable user is enough :)

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/blob/efb40dabc608f9787e6ef9420e0fe71cfa97acf7/test/src/mac/macArchiveTest.ts#L40

Docs https://www.electron.build/configuration/contents is applicable for this option.
