### ISSUE TITLE
Refuse to generate Linux builds if no XDG categories are provided

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#3149]
Missing `Categories=` entries in ''.desktop'' files are [the top #1 annoyance](https://github.com/AppImage/appimage.github.io/issues/2#event-1212176287) in AppImages (and probably `deb` and `rpm`) generated by `electron-builder`. Would it be possible to add a check to `electron-builder` that would force people to select at one of the following [XDG main categories](https://standards.freedesktop.org/menu-spec/latest/apa.html) in the `Categories=` key:

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, developers may specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

**Comment by develar** [comment]
Related #3098

**Comment by develar** [comment]
This issue is obsolete since "Aug 12, 2017" (https://github.com/electron-userland/electron-builder/commit/022d5422f94bc02f45b9c9e5fc9548e720da9aae) Users simply uses old version of electron-builder.


1. if no category, mac category mapped
2. if no mac category or cannot be mapped, warn is printed and `Utility` is used.

**Comment by probonopd** [comment]
Thanks. 

> if no mac category or cannot be mapped, warn is printed and Utility is used.

Can we make it refuse to build instead? That will make people think about the correct category.
