### ISSUE TITLE
More control over code signing

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#3151]
* **Version**: latest

* **Target**: ALL

Hi, 

I've got a report from one of my colleagues that `electron-builder` signs all binaries it can find, in some cases that includes signing binaries previously signed by Microsoft and so on, which is apparently undesired. 

From our brief exchange we concluded that we could benefit from having a list of files/glob patterns to sign and a list of files/glob patterns to exclude from being signed.

We haven't got to PR implementation yet and I'd really like to gather a feedback. Would community benefit from having more control over code signing?

1. List of files to sign - array of paths | glob patterns
1. List of files to exclude from being signed - array of paths | glob pattern

**Comment by develar** [comment]
It is a reason why functionality was disabled by default. We must check is already signed or not. PR welcome, but fix is not easy. If you will managed to do it — great, not — I will do it at least this year :)

**Comment by mvd-ows** [comment]
How about:

`signtool verify /pa /u 1.3.6.1.5.5.7.3.3 file-to-verify`

Also:

`As always, SignTool returns 0 on success, 1 on failure, and 2 on warning.`

**Comment by gniezen** [comment]
I have another use case where this would be pretty useful if implemented: we manually sign the catalog (.cat) files of our Windows drivers that are installed with a custom NSIS script. Having electron-builder sign the .cat files mean we can make changes to the .inf files and just run inf2cat as part of our appveyor script to generate the .cat files.

**Comment by colin-guyon** [comment]
Hi, do you have any update on this?
Would it be already possible to just add a custom `sign` function that would check filenames and do nothing for the files that we don't want to sign, else call the default sign function of electron-builder? (is the default sign function of electron builder importable in some way?)
Thanks

**Comment by woxixiulayin** [comment]
i can not find ways to sign what files i need, electron-build sign all exe files default, can we use sign param to define what files we need to sign?
