### ISSUE TITLE
RequireAdministrator level not working on portable

### ISSUE THREAD

**Issue by migmacdev** [electron-userland/electron-builder#3156]
* **Electron builder version 20.24.5**: 
* **Node version 8.11.1**
* **NPM version 6.1.0**
* **Target: Windows portable**: 

Setting the "requestedExecutionLevel": "requireAdministrator" value exports an exe without the specified admin required level.

code:
```
"build": {
	"appId": "your.id",
	"win": {
		"icon": "ic_launcher.ico",
		"requestedExecutionLevel": "requireAdministrator",
		"target": [
			{
			    "target": "portable"
			}
		]
	}
}
```
The exported output doesn't have admin privileges.

**Comment by xiaoxiangmoe** [comment]
@migmacdev see https://github.com/electron-userland/electron-builder/issues/3738
