### ISSUE TITLE
Windows 10 Search shows the electron icon instead of the app icon

### ISSUE THREAD

**Issue by vsavkin** [electron-userland/electron-builder#3157]
* **Version**: 20.19.2

* **Target**: win, nsis

I have `icon.ico` that gets picked when I build an NSIS target. The installer shows the icon, the app shows the icon. It's shown everywhere except the Windows 10 Search, where I see the Electron icon instead of the app icon. Do I need to set it separately in the configuration?

**Comment by develar** [comment]
Restart windows?

**Comment by NehaTawar** [comment]
@vsavkin Did you find a solution for this one? because i am also facing same issue.

**Comment by NehaTawar** [comment]
I am able to resolve the issue here is a solution reference : #3910.
