### ISSUE TITLE
electron-builder is not creating the .msi installer

### ISSUE THREAD

**Issue by diegomarcov** [electron-userland/electron-builder#316]
Hi folks, thank you for this awesome package!

I've been using electron-builder for several months to create my .exe installers. Now I'm trying to create .msi installers as well, and it seems like the build.win.noMsi option doesn't affect the output of electron-builder, because I can't get a .msi installer even with the option noMsi = false.

I'm using the two package.json configuration as recommended.

My dev package.json includes:

```
"build" : {
    "win" : {
		"noMsi": "false",
		"iconUrl" : "<my-icon-url>",
        "title" : "MyApp",
        "version" : "0.0.1",
        "publisher": "Me"
    }
  }
```

My app package.json includes:

```
{
  "name": "MyApp",
  "version": "0.0.1",
  "description" : "MyApp for Windows.",
  "main": "main.js",
  "author": "Me",
  "homepage" : "https://www.what-about-me.com",
  "license": "MPL-2.0",
}
```

I toggled the noMsi value but no matter what it says, I only get my .exe, my .nupkg, and two RELEASES and RELEASES-ia32 files.

Am I doing something wrong?

Thanks!

**Comment by havenchyk** [comment]
@diegomarcov try to set the boolean value, I believe it's possible in json.

**Comment by diegomarcov** [comment]
@havenchyk I did, see the third line of my dev package.json. "noMsi" is false, which should provide an Msi installer. Just in case the negative flag confused even the devs, I tried with "true". It doesn't work either. Only the .exe installer is provided.

**Comment by develar** [comment]
msi generation works only on Windows. Are you on Windows?

**Comment by diegomarcov** [comment]
Yes, I'm running this on a Windows 7 32-bit installation.

**Comment by develar** [comment]
@diegomarcov Not yet tried, but only bool `false` will work, not a string value. Please try.

```
 "noMsi": false,
```

Not quoted, just `false`

**Comment by diegomarcov** [comment]
I feel very stupid now, but that worked :). Sorry for bothering you guys. Thanks a lot!

**Comment by develar** [comment]
Reopened. Current behaviour is not user friendly and must be fixed.
