### ISSUE TITLE
EACCES: permission denied when trying to open the app

### ISSUE THREAD

**Issue by thatsnoi** [electron-userland/electron-builder#3161]
* **Version**:  20.24.4
* **Target**: macOS (HIgh Sierra)

I have tried to package my electron app on mac using electron-builder. There are no errors while doing so, however, once I try to open the app I get the following error:

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> 
> Error: EACCES: permission denied, mkdir

I have not found any similar errors related to electron-builder and it also works just fine for windows. I have also tried using 'sudo'.

Thanks in advance for any help.

**Comment by MunzerDw** [comment]
Sorry Brother i am not familiar with such problems

**Comment by develar** [comment]
It is some your app specific issue, please investigate.
