### ISSUE TITLE
Electron Updater: Error checking for updates on Private GitHub repo

### ISSUE THREAD

**Issue by hicaro** [electron-userland/electron-builder#3163]
* **electron-builder**: 20.25.0

* **electron-updater**: 3.0.3

* **Target**: macOS (High Sierra)

I have encountered an error running electron-updater against GitHub enterprise:

```js
[11:02:13.525] [error] Error: TypeError: Cannot read property 'assets' of undefined
    at /Users/user/projects/becks/prodsuite/MyProject/out/mac/MyProject.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/PrivateGitHubProvider.ts:31:31
```

This basically happened due to the following facts:

* All releases were published to GitHub using `alpha` in the version number, e.g. `v0.1.2-alpha`;
* Releases were not published as pre-releases (did not check the `This is a pre-release` checkbox);
* electron-update automatically sets `allowPrerelease` to true in case of containing an pre-release component such as `alpha` in the version name, according to the [documentation](https://www.electron.build/auto-update/#appupdater-eventemitter);

Whenever there is a check for updates, the function `getLatestVersion()` is called (in my case since I am using a private repo), which will call `getLatestVersionInfo`.
> line 26 of electron-builder/packages/electron-updater/src/providers/PrivateGitHubProvider.ts 

```js
const releaseInfo = await this.getLatestVersionInfo(cancellationToken)
const asset = releaseInfo.assets.find(it => it.name === channelFile) // error happens here
```

As it was detected the `alpha` in my version number, setting `allowPrerelease` to true, in `getLatestVersionInfo`, it fetched all releases not just the latest one. Then, within the function, upon receiving the http response, the following happened:

```js
if (allowPrerelease) {
    version = version.find((v: any) => v.prerelease)
}
```

As I did not have any release with `prerelease` set to true, `version` became `undefined`. This value was returned and assigned to `releaseInfo` in getLatestVersion.
When the code tried to extract assets from releaseInfo, it errored out.

The way I see the fix for this is to either throw an error if version becomes `undefined` within getLatestVersionInfo or make it check for undefined in `releaseInfo` in getLatestVersion.

I can make the change a submit a PR, if you guys prefer. I just wanted to check what would be the expected behavior for this.

Full functions for reference:
```js
async getLatestVersion(): Promise<PrivateGitHubUpdateInfo> {
    const cancellationToken = new CancellationToken()
    const channelFile = getChannelFilename(getDefaultChannelName())

    const releaseInfo = await this.getLatestVersionInfo(cancellationToken)
    const asset = releaseInfo.assets.find(it => it.name === channelFile)
    if (asset == null) {
      // html_url must be always, but just to be sure
      throw newError(`Cannot find ${channelFile} in the release ${releaseInfo.html_url || releaseInfo.name}`, "ERR_UPDATER_CHANNEL_FILE_NOT_FOUND")
    }

    const url = new URL(asset.url)
    let result: any
    try {
      result = safeLoad((await this.httpRequest(url, this.configureHeaders("application/octet-stream"), cancellationToken))!!)
    }
    catch (e) {
      if (e instanceof HttpError && e.statusCode === 404) {
        throw newError(`Cannot find ${channelFile} in the latest release artifacts (${url}): ${e.stack || e.message}`, "ERR_UPDATER_CHANNEL_FILE_NOT_FOUND")
      }
      throw e
    }

    (result as PrivateGitHubUpdateInfo).assets = releaseInfo.assets
    return result
  }

private async getLatestVersionInfo(cancellationToken: CancellationToken): Promise<ReleaseInfo> {
    let basePath = this.basePath
    const allowPrerelease = this.updater.allowPrerelease

    if (!allowPrerelease) {
      basePath = `${basePath}/latest`
    }

    const url = newUrlFromBase(basePath, this.baseUrl)
    try {
      let version = (JSON.parse((await this.httpRequest(url, this.configureHeaders("application/vnd.github.v3+json"), cancellationToken))!!))
      if (allowPrerelease) {
        version = version.find((v: any) => v.prerelease)
      }
      return version
    }
    catch (e) {
      throw newError(`Unable to find latest version on GitHub (${url}), please ensure a production release exists: ${e.stack || e.message}`, "ERR_UPDATER_LATEST_VERSION_NOT_FOUND")
    }
  }
```

**Comment by JuanDavidLopez95** [comment]
I was getting this issue earlier. I was able to solve it for some strange reason by doing the following steps:

1. Confirming that you are using the correct authentication token, and that it is equal to GH_Token on your system environment variables.

2. Not sure if this has anything to do with it, but I have my `autoUpdater.allowPrerelease = true;` 

3. Deleting your node_modules folder, but reinstall with `npm install`.

4. Uploading a release via the `npm run release` command, but making sure that release is ultimately dubbed not as a draft or pre-release.

**Comment by alexandrricov** [comment]
I feel
```typescript
version = version.find((v: any) => v.prerelease)
```
should be
```typescript
version = version.find((v: any) => v.prerelease) || version[0];
```
Updater is checking current app version, and if it contains `alfa` or `beta` etc.,  `allowPrerelease` became `true`.
If no one update contains `prerelease` github flag – app crashes.
If next release (ordered by semver) contains `prerelease` flag – then if will be installed, but I can't see how to exit from `prerelease` circle using current implementation.
I've tested proposed change, and it works well for me. I hope it could be a solution.
