### ISSUE TITLE
Packed wrong node modules when project have multiple version of hoisted modules

### ISSUE THREAD

**Issue by brcps12** [electron-userland/electron-builder#3164]
* **Version**: 20.25.0

* **Target**: Windows

The project uses hoisted node_modules (like Lerna), and has some dependencies that have same sub-dependency but are different version in each other. In this situation, electron-builder has not include these dependencies of different version into package.

For instance, there are `moduleA` and `moduleB`, and they depend on `moduleF`, but in the `moduleA`, it depends `moduleF` versioned 1.0.0, and in the `moduleB` depends 2.0.0. After execute electron-build commands, both `moduleA` and `moduleB` use only one (1.0.0 or 2.0.0).

Sample project:
https://github.com/brcps12/hoisted-electron-builder

Without hoisted, displayed version messages of `moduleF` are different for `moduleA` and `moduleB`.
But with hoisted, displayed messages are same.

**Comment by mboperator** [comment]
This is still an issue -- getting it in my project
