### ISSUE TITLE
Electron-Updater fails when connection resets.

### ISSUE THREAD

**Issue by dscalzi** [electron-userland/electron-builder#3171]
* **electron-builder**: 20.25.0
* **electron-updater**: 3.0.3

* **Target**: nsis x64

I'm currently on vacation and have a less than reliable internet connection. The speed is fine, 40mbps download, however it drops here and there. I was doing some development work and pushed out an update, however I noticed that the autoupdater failed.

This is what happens:
* Start app
* Check for update
* Update is available, download begins.
  * Compares blockmap files.
  * No cache available, falls back to full download.

Here is where the issue begins.

* Download starts but goes very slowly.
  * Download reaches ~6MB/50MB (varying) and then just stops. No console errors.
  * After keeping the app open for a while with this stopped download, I get the following alert.

![image](https://user-images.githubusercontent.com/9703873/43240613-b18773c8-9097-11e8-8bc6-2bb9af23419f.png)

Again, the updater works perfectly with a solid internet connection, but fails with a weaker one. I'm not sure if anything can be done to fix this, however I thought I would bring it to your attention.

**Comment by jason-zuo** [comment]
@dscalzi i face the same problem, do you fixed it ?

**Comment by dscalzi** [comment]
No I haven't fixed it. Don't have time to look for a probably cause in the library so I'm waiting on the devs to give this a look.

**Comment by mo22** [comment]
Note that this should in my opinion trigger `autoUpdater.on('error',...` and not cause an uncaught exception error that terminates the app and makes it unusable.

**Comment by Christilut** [comment]
Just noticed this too. `autoUpdater.on('error',...` isn't called which surprised me. And I also think it should be able to recover.
Connection reset might only happen with poor connections but there is also the event that a connection switch happens, when a user changes from WIFI to cabled network. The auto updater also fails to recover there.

**Comment by mikeyyyzhao** [comment]
Any updates on this?

**Comment by genyx** [comment]
This is still a problem. Especially when the app is as large as 500MB which may take a couple of minutes to download.

**Comment by MiguelSOliveira** [comment]
Still happens on our end. Only on windows.

**Comment by genyx** [comment]
i worked around this by extracting large asset files and downloading them when the app starts for the first time (including versioning). i was able to minimize the updater file size to 135MB instead of 600+ MB. 
(i use Electron.NET and a .net 5 blazor app packed into)

**Comment by oboshto** [comment]
Still happens for my users. Installed versions:
```
    "electron": "21.4.0",
    "electron-builder": "24.6.4",
    "electron-rebuild": "3.2.9",
```

My updater file size is around 1.6GB
