### ISSUE TITLE
Electron App (for production) with any database in a single file. 

### ISSUE THREAD

**Issue by bdouram** [electron-userland/electron-builder#3178]
Hi!

I'm begginer in **Electron ecosystem** and i need make one **powerfull desktop app**.
I choose the electron because i'm experient with JavaScript and i really want make one software using React xD.

I have many questions and the first of my list is:
Can I put my "powerfull application" and the database (relational or not relational) in a **single installer (for production)** using the electron-builder?

If it's possible, may you have some tutorials to share with me?

Thank you all.

**Comment by KacyLuzz** [comment]
You can add a database file in the source.

**Comment by develar** [comment]
...and on launch check, if db in the user app data or not. copy if not.
