### ISSUE TITLE
Get executable APP name in main.js for portable

### ISSUE THREAD

**Issue by Cefold** [electron-userland/electron-builder#3186]
I see that `process.env.PORTABLE_EXECUTABLE_DIR` will return executable dir, but how can I get full app name, assume some users would change that app name?

I want to toggle shortcut and startup, which will need dir and app name, `C:/Users/${user}/AppData/Local/Temp` is not useful since it will change every time.

`System::Call 'Kernel32::SetEnvironmentVariable(t, t)i ("PORTABLE_EXECUTABLE_DIR", "$EXEDIR").r0'`

It only sets `PORTABLE_EXECUTABLE_DIR`.

**Comment by develar** [comment]
Have you tried https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname?

**Comment by Cefold** [comment]
Yes, that's what I needed, thanks.
I have a rookie question, when can I use the new feature? The newest version v20.26.1 does not have this feature.

By the way, what is the difference from `APP_FILENAME`  and `APP_EXECUTABLE_FILENAME`?

**Comment by develar** [comment]
Release will be today evening CET.

**Comment by Cefold** [comment]
I tried the new feature, but `PORTABLE_EXECUTABLE_APP_FILENAME` will return the name in `package.json`, not the real portable app name.
More importantly, the `PORTABLE_EXECUTABLE_APP_FILENAME` is fixed. 

For example, `package.json` file has `"name": "MyAPP"`, `"productName": "my.app"`, 
I will get a portable app `my.app 1.0.0.exe`, and but `PORTABLE_EXECUTABLE_APP_FILENAME` will return `MyAPP`, if I change the APP name, the return value stays the same. What I want is getting `my.app 1.0.0`, and if I change that file name to `anotherAPP.exe`, `PORTABLE_EXECUTABLE_APP_FILENAME` should return `anotherAPP`.

**Comment by develar** [comment]
https://www.electron.build/configuration/nsis/#portable


`PORTABLE_EXECUTABLE_` it is a common prefix for all envs that set by portable wrapper.

> By the way, what is the difference from APP_FILENAME and APP_EXECUTABLE_FILENAME?

`APP_EXECUTABLE_FILENAME` is not for users (you are electron-builder user), it is internal developer only name.  In the docs `PORTABLE_EXECUTABLE_APP_FILENAME` described as "sanitized app name to use in file paths."

Now I realised that you want `PORTABLE_EXECUTABLE_FILE `

**Comment by Cefold** [comment]
Thank

**Comment by Cefold** [comment]
Yes, I need full path, include portable wrapper, to set shortcut and startup. The hard part is that user might change the portable wrapper name. E.g. if I hardcode the name to `my.app 1.0.0.exe`, and user change it to something like `anotherAPP.exe`, the functions used that name will not work.

I guess that name should be passed from nsis to node env, but it seems portable mode does not support Custom NSIS script.

**Comment by develar** [comment]
What shortcut do you mean?

**Comment by develar** [comment]
Why do you use portable in this case?

**Comment by Cefold** [comment]
I don't want to use portable, that's users request, some people really hate to install something or unzip something, they just want a single executable, even it will create a tmp folder and unzip everything to that folder.

**Comment by develar** [comment]
@Cefold Please try 20.27.1

**Comment by Cefold** [comment]
Great, now `PORTABLE_EXECUTABLE_APP_FILENAME` will return full path, and `path.basename(process.env.PORTABLE_EXECUTABLE_FILE)` will return executable name.

Thank you.

**Comment by kiprobinson** [comment]
For anyone else who finds this- I found that using `process.execPath` works. I was using an exe built by electron-packager, but not a portable one.

**Comment by felipecrs** [comment]
In case others come here, the following should make it more explicit:

For portable app, following environment variables are available:

* `PORTABLE_EXECUTABLE_FILE` - path to the portable executable.
* `PORTABLE_EXECUTABLE_DIR` - directory where the portable executable is located.
* `PORTABLE_EXECUTABLE_APP_FILENAME` - sanitized app name to use in [file paths](https://github.com/electron-userland/electron-builder/issues/3186#issue-345489962).

- https://github.com/electron-userland/electron-builder/pull/6981

**Comment by XT3RM1NATOR** [comment]
In my app none of them workPORTABLE_EXECUTABLE_FILE 
PORTABLE_EXECUTABLE_DIR
PORTABLE_EXECUTABLE_APP_FILENAME. is trying to acess process.env wont it only return values hardcoded in the .env file or am i wrong?
