### ISSUE TITLE
Question: Caching electron-builder downloads on CI

### ISSUE THREAD

**Issue by amilajack** [electron-userland/electron-builder#3190]
`electron-builder` makes a number of downloads from `electron-userland/electron-builder-binaries`. What directory are those downloads saved to? Also should they be cached? `electron-builder` takes  quite a while on CI. Trying to find ways to optimize.

**Comment by develar** [comment]
Please see sample travis.yml —  https://www.electron.build/multi-platform-build/#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows

And I doubt that downloading is a bottleneck. Try 20.27.0 — in this version download time is printed.

**Comment by develar** [comment]
```
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
```

**Comment by xiaoxiangmoe** [comment]
@develar can we cache it in build directory?
