### ISSUE TITLE
write EPIPE error when building

### ISSUE THREAD

**Issue by andyadamescu** [electron-userland/electron-builder#3192]
* **20.26.0**: 

3.0.3

* **Win x64**: 

Hello,
On CentOS the build fails with an EPIPE error:

yarn run v1.7.0
$ electron-builder --win --x64
  • electron-builder version=20.26.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.5 appOutDir=dist/win-unpacked
  • default Electron icon is used reason=application icon is not set
  • building        target=nsis file=dist/ElectronTest Setup 0.5.7.exe archs=x64 oneClick=true
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite (net.js:864:14)
error Command failed with exit code 1.

Any help on this?
Thx

**Comment by munybt** [comment]
I'm having the same issue

**Comment by quoyi** [comment]
> I'm having the same issue

I'm too.  Building with wine docker image on mac 10.13
```sh
(node:887) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Socket.Writable.end (_stream_writable.js:585:10)
    at Socket.end (net.js:588:31)
    at /project/node_modules/builder-util/src/util.ts:197:26
    at new Promise (<anonymous>)
    at spawnAndWrite (/project/node_modules/builder-util/src/util.ts:180:10)
    at NsisTarget.executeMakensis (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:552:11)
    at NsisTarget.computeScriptAndSignUninstaller (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:339:5)
    at NsisTarget.buildInstaller (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:277:103)
    at NsisTarget.finishBuild (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:109:7)
    at async Promise.all (index 3)
    at AsyncTaskManager.awaitTasks (/project/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/project/node_modules/app-builder-lib/src/packager.ts:456:5)
    at executeFinally (/project/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/project/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/project/node_modules/app-builder-lib/src/packager.ts:337:12)
(node:887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
same with flag `--unhandled-rejections=strict`

**Comment by joelcorey** [comment]
I am having the same issue.

**Comment by qld-cf** [comment]
same issue. 
linux centos

**Comment by qld-cf** [comment]
> I am having the same issue.

@joelcorey have you solved?

**Comment by qld-cf** [comment]
> > I'm having the same issue
> 
> I'm too. Building with wine docker image on mac 10.13
> 
> ```shell
> (node:887) UnhandledPromiseRejectionWarning: Error: write EPIPE
>     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
>     at writeGeneric (internal/stream_base_commons.js:145:3)
>     at Socket._writeGeneric (net.js:784:11)
>     at Socket._write (net.js:796:8)
>     at doWrite (_stream_writable.js:403:12)
>     at writeOrBuffer (_stream_writable.js:387:5)
>     at Socket.Writable.write (_stream_writable.js:318:11)
>     at Socket.Writable.end (_stream_writable.js:585:10)
>     at Socket.end (net.js:588:31)
>     at /project/node_modules/builder-util/src/util.ts:197:26
>     at new Promise (<anonymous>)
>     at spawnAndWrite (/project/node_modules/builder-util/src/util.ts:180:10)
>     at NsisTarget.executeMakensis (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:552:11)
>     at NsisTarget.computeScriptAndSignUninstaller (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:339:5)
>     at NsisTarget.buildInstaller (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:277:103)
>     at NsisTarget.finishBuild (/project/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:109:7)
>     at async Promise.all (index 3)
>     at AsyncTaskManager.awaitTasks (/project/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
>     at Packager.doBuild (/project/node_modules/app-builder-lib/src/packager.ts:456:5)
>     at executeFinally (/project/node_modules/builder-util/src/promise.ts:12:14)
>     at Packager._build (/project/node_modules/app-builder-lib/src/packager.ts:373:31)
>     at Packager.build (/project/node_modules/app-builder-lib/src/packager.ts:337:12)
> (node:887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> same with flag `--unhandled-rejections=strict`

 have you solved? @quoyi

**Comment by qld-cf** [comment]
> I'm having the same issue

@munybt  have you solved?

**Comment by munybt** [comment]
@qld-cf No, I did not solve it. I just changed the distro on the machine I where was building the app.

**Comment by qld-cf** [comment]
> @qld-cf No, I did not solve it. I just changed the distro on the machine I where was building the app.

@munybt centos linux?

**Comment by qld-cf** [comment]
> @qld-cf No, I did not solve it. I just changed the distro on the machine I where was building the app.

@munybt how did you build the app? thx

**Comment by munybt** [comment]
@qld-cf I just changed to a Ubuntu machine and built the app with `electron-builder --win --x64`

**Comment by SAbolfazlSH** [comment]
same issue
Does anybody solve this problem?

**Comment by Yutiy** [comment]
Same Issue
Does anybody solve this problem?

**Comment by elliotthill** [comment]
When I get this error it is because I have another service bound to port 3000, when I disable that or change the port, it fixes the issue.
