### ISSUE TITLE
autoUpdater.downloadUpdate throws syscall rename error on windows

### ISSUE THREAD

**Issue by farafonov-alexey** [electron-userland/electron-builder#3193]
* **Version**:  20.26.0 ( also tried on 20.26.1)

* **electron-updater version**:  3.0.3 (also tried on 3.1.1)

* **Target**: 
Windows x86

I'm calling autoUpdater.checkForUpdates() and then autoUpdater.downloadUpdate() throws error - 
```json 
{
"code": "ENOENT", 
"dest": "C:\\Users\\{User}\\AppData\\Roaming\\{program-name}\\__update__\\{program-full-name}-dev.1.exe", 
"errno": -4058, 
"path": "C:\\Users\\{User}\\AppData\\Roaming\\{program-name}\\__update__\\temp-0-{program-full-name}-dev.1.exe",
"syscall": "rename" }
```
Old versions of electron-builder(19.52.1) and electron-updater(2.18.2) were free of this error.

I've made a research and found that this error message can cause ['node-fs-extra'](https://www.npmjs.com/package/fs-extra) package which is using in your ['fs-extra-p'](https://www.npmjs.com/package/fs-extra-p), but i can't track down which method.

Our program full name has some spaces and unicode characters(russian symbols), maybe this can cause an error.
Any help will be appreciated.

**Comment by farafonov-alexey** [comment]
I think I realise the possible cause of error.
Calling checkForUpdates() function starts downloading process of update file. I don't think its a desired behavior, because documentation states that [checkForUpdates](https://www.electron.build/auto-update/#module_electron-updater.AppUpdater+checkForUpdates) 

> Asks the server whether there is an update.

and only [checkUpdatesAndNotify](https://www.electron.build/auto-update/#module_electron-updater.AppUpdater+checkForUpdatesAndNotify) 

> Asks the server whether there is an update, **download** and notify if update available.

So, when the process of downloading is in progress calling downloadUpdate() leads to the error above.

**Comment by develar** [comment]
> I'm calling autoUpdater.checkForUpdates() and then autoUpdater.downloadUpdate()

Because you listen update-available event, but not update-downloaded event, right?

Good. Regardless of your incorrect client code, error should be fixed and electron-updater don't fail with unclear internal error.
