### ISSUE TITLE
electron-builder 20.26.1 wont find squirrel

### ISSUE THREAD

**Issue by Troldefar** [electron-userland/electron-builder#3194]
* **Version**: 
  "scripts": {
    "start": "./node_modules/.bin/electron .",
    "build": "build --win",
    "test": "echo \"Error: no test specified\" && exit 1",
    "rebuild": "electron-rebuild -f -w bcrypt"
  },
  "build": {
    "squirrelWindows": {
      "remoteReleases": ""
    },
    "win": {}
  },
  "devDependencies": {
    "devtron": "^1.4.0",
    "electron": "^2.0.2",
    "electron-builder": "^20.26.1",
    "electron-packager": "^12.1.0",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.8.1",
    "electron-reload": "^1.2.2",
    "electron-squirrel-startup": "^1.0.0",
    "electron-updater": "^2.23.3",
    "electron-window-state": "^4.1.1",
    "electron-winstaller": "^2.6.4"
  },
  "dependencies": {
    "async": "^2.6.1",
    "bcryptjs": "^2.4.3",
    "child_process": "^1.0.2",
    "devtron": "^1.4.0",
    "express": "^4.16.3",
    "mysql2": "^1.5.3",
    "tedious": "^2.6.1",
    "update-electron-app": "^1.3.0"
  }

* **Target**:  Windows

When i run npm run build it compiles, creates and exe file and a blockmap file, ... however! The latests.yml file wont update and when i try to install this and run my application it states that it can not find squirrel, what am i doing wrong??
![squirrelwrong](https://user-images.githubusercontent.com/24574792/43437400-1c448a08-9489-11e8-814d-721fd0aae6da.PNG)

**Comment by develar** [comment]
By default electron-builder produces NSIS, not Squirrel.Windows.
