### ISSUE TITLE
CFBundleIdentifier Collision - MAS build rejected

### ISSUE THREAD

**Issue by countravioli** [electron-userland/electron-builder#3196]
* **Version**: 20.27.0
* **electron-updater**: 3.1.1
* **Target**: mas

Apple's Application Loader will not accept mas build due to CFBundleIdentifier Collision.

Seems related to #2719 

> ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'com.github.electron.helper' of 'SportFX Studio/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app' is already in use by another application."

The same error message above, is also displayed for other plist files
* 'SportFX Studio/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app'
* 'SportFX Studio/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper EH.app'
* 'SportFX Studio/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper NP.app'

Doing a a little investigation, I run `find ./ -name 'Info.plist' ` in the "./dist/mas/SportFX Studio.app" folder which returns 14 plist files. The following look good with having the values for `<key>CFBundleIdentifier</key>` scoped to my app id
```
.//Contents/Info.plist
.//Contents/Frameworks/SportFX Studio Helper NP.app/Contents/Info.plist
.//Contents/Frameworks/SportFX Studio Helper.app/Contents/Info.plist
.//Contents/Frameworks/SportFX Studio Helper EH.app/Contents/Info.plist
.//Contents/Library/LoginItems/SportFX Studio Login Helper.app/Contents/Info.plist
```

However, these plist files have the "generic" CFBundleIdentifier's still
```
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/Resources/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Mantle.framework/Versions/A/Resources/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/Info.plist
.//Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Info.plist
.//Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/Info.plist
```

Additional Notes while trying to debug / fix
* Also effected previous versions of electron-builder:20.26.1 electron-updater:3.0.3
* Tried upgraded to the electron 3.0.0@beta-3 and it still affected as well.
* building with current versions, the result of the mas-dev build launches just fine.

**Comment by countravioli** [comment]
I was able to solve this by using the afterPack hook (hooks were new to me in general).

```
{
    "afterPack": "./hooks/afterPack.js",
}
```
```
const fs = require('fs');
const fse = require('fs-extra');
const path = require('path');
module.exports = function (params) {
    const unpackFile = path.join(params.appOutDir, '/SportFX Studio.app/Contents/Resources/app.asar.unpacked');
    console.log('EXISTS?', fs.existsSync(unpackFile));
    console.log("REMOVE", unpackFile);
    fse.removeSync(unpackFile);
};
```

**Comment by juandavidcruzs** [comment]
Hi @countravioli,

I tried to add the "afterPack" item in my package.json root and the file (afterPack.js) you provided. But nothing happens, do I need to do anything else? Is that "afterPack" hook being called automatically? I can't relate any call to that file in the whole building process. What should I do.

Thanks so much in advance.

**Comment by arslankaleem7229** [comment]
> 

Were you able to resolve this issue?

**Comment by arslankaleem7229** [comment]
> I was able to solve this by using the afterPack hook (hooks were new to me in general).
> 
> package.json
> 
> ```
> {
>     "afterPack": "./hooks/afterPack.js",
> }
> ```
> 
> afterPack.js
> 
> ```
> const fs = require('fs');
> const fse = require('fs-extra');
> const path = require('path');
> module.exports = function (params) {
>     const unpackFile = path.join(params.appOutDir, '/SportFX Studio.app/Contents/Resources/app.asar.unpacked');
>     console.log('EXISTS?', fs.existsSync(unpackFile));
>     console.log("REMOVE", unpackFile);
>     fse.removeSync(unpackFile);
> };
> ```
> 
> I think there is either a problem with my config, of which I cannot find, or in the builder code itself right now where the app.asar.unpacked file is not being cleaned up. For me this was leading to all my builds being about 75MB bigger than they needed to be. This removed bloat from the build distributable files and allowed me to pass upload to the MAS.

This helps in deployment to testflight but then I got this error on install 

<img width="260" alt="Screenshot 2022-07-29 at 12 27 47 PM" src="https://user-images.githubusercontent.com/49631685/181707496-509ed378-5465-4192-b7b3-9b2bdb4bf2ac.png">
