### ISSUE TITLE
Build for windows not working..

### ISSUE THREAD

**Issue by cttech** [electron-userland/electron-builder#3197]
* **Version**: 
20.14.7

* **Target**: 
Windows

Hi, 
When I am trying to build for windows I see the following error. I deleted the cache and try with the following options..

"win": {
       "target": [
      "portable"
    ]
  },
  "portable": {
    "useZip": true
  },

I see the following error. 

Error: C:\Users\john\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=com.electron.XXX-projectname"
Command line defined: "APP_GUID=523e9f33-6669-5097-9182-4aceca974e87"
Command line defined: "PRODUCT_NAME=XXX-projectname"
Command line defined: "PRODUCT_FILENAME=XXX-projectname"
Command line defined: "APP_FILENAME=XXX-projectname"
Command line defined: "APP_DESCRIPTION=XXX projectname with electron js and angular"
Command line defined: "VERSION=1.1.0"
Command line defined: "PROJECT_DIR=C:\XXX\projectname"
Command line defined: "BUILD_RESOURCES_DIR=C:\XXX\projectname\build"
Command line defined: "APP_DIR_64=C:\XXX\projectname\XXX-projectname-builds\win-unpacked"
Command line defined: "COMPANY_NAME=XXX"
Command line defined: "APP_PRODUCT_FILENAME=XXX-projectname"
Command line defined: "APP_INSTALLER_STORE_FILE=XXX-projectname\installer.exe"
Command line defined: "ZIP_COMPRESSION"
Command line defined: "COMPRESSION_METHOD=zip"
Command line defined: "REQUEST_EXECUTION_LEVEL=user"
Command line defined: "COMPRESS=auto"
Processing config: C:\Users\john\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
File: failed creating mmap of "C:\XXX\projectname\XXX-projectname-builds\win-unpacked\resources\app.asar"
Error in script "<stdin>" on line 88 -- aborting creation process

    at ChildProcess.childProcess.once.code (C:\XXX\projectname\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Any Idea plz?

**Comment by jasonayre** [comment]
I am seeing what looks like the same error - When I run it with debug on, I see several instances of the following error before the script breaks 

`
  electron-builder wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
  electron-builder err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
`;

Then shortly after

`
Error: /Users/jayre_imac/Library/Caches/electron-builder/nsis/nsis-3.0.1.13/mac/makensis exited with code 1
Error output:
File: failed creating mmap of "/Users/jayre_imac/code/myapp/dist/myapp-1.0.0-x64.nsis.7z"
Error in macro extractEmbeddedAppPackage on macroline 9
!include: error in script: "installSection.nsh" on line 182
`

@cttech can you try running with `DEBUG=electron-builder` to see if you're seeing the same wine error before it breaks?

**Comment by develar** [comment]
@jasonayre Wine error doesn't matter. Please build with `DEBUG=electron-builder` and  attach `dist/builder-debug.yml` Or maybe just your project if possible.

**Comment by develar** [comment]
And make sure that you use latest version.
