### ISSUE TITLE
can't find windows files on mac

### ISSUE THREAD

**Issue by mickychen0524** [electron-userland/electron-builder#3199]
* **Version**: 
20.26.1

* **Target**: 
macOS

when I run 'npm run dist', I can see mac app files generated but can't see any windows executable files like exe or ms installer

**Comment by develar** [comment]
Please see https://www.electron.build/cli/#target

**Comment by mickychen0524** [comment]
@develar I tried it but still no luck
"win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "publisherName": "xxx"
    }

**Comment by develar** [comment]
See `and use`.

You still need to pass flag which OS you want to build for.

`--windows` to build for windows.

**Comment by mickychen0524** [comment]
thanks, it works!
