### ISSUE TITLE
Add new package support to electron-updater

### ISSUE THREAD

**Issue by dguayrobotiq** [electron-userland/electron-builder#3207]
This is more a question than an issue. I'm looking to auto-update a [Makeself](https://github.com/megastep/makeself) package with `electron-updater`. I'm already packaging my app and uploading the package on S3. I just need to auto-update the package now.  

Is this something doable by extending `BaseUpdater`? Otherwise, how should I proceed?

Thanks

**Comment by develar** [comment]
So, only Linux?

**Comment by dguayrobotiq** [comment]
@develar yes it's only for Linux. In our case, AppImage doesn't work.

**Comment by develar** [comment]
So, very easy:

1. copy https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppImageUpdater.ts
2. remove differential update impl from `doDownloadUpdate` method (see `isDownloadFull`)
3. `doInstall` is suitable as is (because downloaded file simply executed and no magic here). Maybe you need somehow handle `isSilent` / `isRunAfter `

Feel free to send PR to make sure that in the future your updater will be maintained by us.

**Comment by develar** [comment]
To use your new updater — simply use it instead of `electron-updater`.

**Comment by dguayrobotiq** [comment]
@develar ok thanks ! That's what I was going to do so that makes sense ! I'll try to make a PR if I end up making it work

**Comment by dguayrobotiq** [comment]
@develar Since I'm packaging and uploading my `makeself` package with custom scripts, will I have to manually create and upload a `latest-linux.yml` file to my S3 as well?

**Comment by develar** [comment]
> will I have to manually create and upload a latest-linux.yml file to my S3 as well?

Nice question. Yes, you must.

Don't you use electron-builder?  Or do you plan? Or do you want to just use electron-updater and nothing more?

**Comment by dguayrobotiq** [comment]
@develar I use `electron-builder` as well but there is no option for `makeself` packaging

**Comment by dguayrobotiq** [comment]
@develar Currently, I have an error with `app-update.yml` not found and I stumble upon [this question which you answered](https://stackoverflow.com/questions/41688503/electron-electron-builder-auto-updater-update-yml-not-found)

I just realized we are running our app from the unpacked directory since `makeself` is just a self-extractable archives. Would that work in any way?

**Comment by develar** [comment]
Why do you use  Makeself instead of AppImage?

**Comment by develar** [comment]
Copy from `resources/app-update.yml` (build AppImage with env `DEBUG=electron-builder` and you will see stage dir for AppImage).

Or call [setFeedURL](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+setFeedURL)

**Comment by dguayrobotiq** [comment]
@develar We can't use AppImage because we have issues making it work on the system we're working on. I've talked with the AppImage team but there's no solutions for now. 

So you're saying the auto-update should work even if we run the app from the unpacked directory? We just need to make sure we have a `app-update.yml` in the resource folder (or call setFeedURL)?

Also, are all attributes in the `latest.yml` file required? What if `sha512`, `size` or `blockMapSize` are not there?

**Comment by develar** [comment]
> We just need to make sure we have a app-update.yml in the resource folder (or call setFeedURL)?

Yes.

> Also, are all attributes in the latest.yml file required? What if sha512, size or blockMapSize are not there?

You can omit size and blockMapSize, but should include sha512

**Comment by dguayrobotiq** [comment]
@develar Thanks a lot for your help. This is a bit more complicated than I've anticipated.

Since `makeself` extract itself and run the binary inside the `unpacked` directory, I'm a bit lost with what I should replace `oldFile` variable in the `doDownloadUpdate(...)` function and the `appImageFile` (which I renamed `makeselfFile`) variable in the `doInstall(...)` function.

I believe they should point to the `makeself` file which start the binary. After trying that, I get an error in the `autoUpdater.on("error",...` event which I logged:

```
[04:40:16.797] [info] Checking for update
[04:40:17.305] [info] Found version 3.0.0 (url: https://s3.amazonaws.com/my_bucket/my-app-3.0.0.run)
[04:40:17.310] [info] Downloading update from https://s3.amazonaws.com/my_bucket/my-app-3.0.0.run
[04:40:17.349] [info] No cached update info available
Update error = Error: ENOENT: no such file or directory, chmod '/tmp/.config/my-app/__update__/temp-my-app-3.0.0.run'
```

Looking at the code I think the problem is around here but I'm not sure what I'm doing wrong exactly: https://github.com/electron-userland/electron-builder/blob/86d64c24eb480d92131d5691798cdff9d7926c3c/packages/electron-updater/src/AppUpdater.ts#L553

Looks like it's trying to `unlink` a temp file that isn't there...

**Comment by dguayrobotiq** [comment]
So after more investigating, I realized the error happened when we do `await chmod(updateFile, 0o755);` in `AppImageUpdater` (or in my case, my updater `MakeselfUpdater`). 

I realized I wasn't catching and logging this error too:

```
Cannot download differentially, fallback to full download:Error: unexpected end of file
    at InflateRaw.zlibOnError (zlib.js:153:15)
From previous event:
    at j.R [as _captureStackTrace] (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:1:18976)
    at new d (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:1:32197)
    at /tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:1:35286
    at t.MakeselfUpdater.executeDownload (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:1:144524)
    at t.MakeselfUpdater.executeDownload (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:1:145342)
    at t.MakeselfUpdater.<anonymous> (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:2:68427)
    at Generator.next (<anonymous>)
    at s (/tmp/selfgz2728027850/linux-ia32-unpacked/resources/app.asar/dist/electron-main.js:2:67263)
    at <anonymous>
```

> remove differential update impl from doDownloadUpdate method (see isDownloadFull)

Since you told me to remove this, it just try to `chmod` the `updateFile` right after.

After uncommenting the `isDownloadFull` and letting `await this.httpExecutor.download(fileInfo.url.href, updateFile, downloadOptions);` run, the update is downloaded to the temp folder !

Is it normal that it always use this method though?
