### ISSUE TITLE
Question : Able to build electron application in offline environment with no internet connection?

### ISSUE THREAD

**Issue by WebStew** [electron-userland/electron-builder#3208]
* **20.26.1**: 

Hi,

Is it possible to use electron-builder in an offline environment with no internet connection to build an electron application?

Currently all of our application dependencies are installed using Yarn with an offline folder.
The Electron binaries are installed using an environment variable to point a local folder.

Is something similar available with Electron Builder - apologies I couldn't anything in the documentation or on the line.

**Comment by develar** [comment]
Use env `ELECTRON_BUILDER_CACHE` — set it to path to some local dir, build with internet access, and then somehow save this to use later as offline cache.

But please note — for code signing, you have to use online timestamped server

**Comment by WebStew** [comment]
Hi @develar ,

Many thanks for the quick response. Is there any way to build an Electron app in a completely offline environment end to end including code signing?

**Comment by develar** [comment]
@WebStew Probably you can setup own timestamp server for windows codesign, but I am not sure about macOS codesign. Sorry, cannot advice here, need to investigate.

**Comment by develar** [comment]
See https://stackoverflow.com/questions/14733206/how-to-create-a-timestamp-server-for-signature-purposes

**Comment by develar** [comment]
See https://www.electron.build/configuration/win

`rfc3161TimeStampServer ` and `timeStampServer ` (you need to set both).

**Comment by develar** [comment]
macOS info: https://stackoverflow.com/a/19464252

**Comment by WebStew** [comment]
Many thanks for all the information @develar

**Comment by acfromspace** [comment]
> Use env `ELECTRON_BUILDER_CACHE` — set it to path to some local dir, build with internet access, and then somehow save this to use later as offline cache.
> 
> But please note — for code signing, you have to use online timestamped server

This is vague to me.

Is there an example code of how this is executed? I can't tell if I have to make an `.env` file, put it along with the script command, etc.

Where does the cache go if I'm putting this in an offline machine?

How does the offline machine know how to reference the `ELECTRON_BUILDER_CACHE`?
