### ISSUE TITLE
Files show up as modified on fresh fork

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#321]
After forking and cloning this project 
git status reports 
	modified:   test/fixtures/test-app/build/icon.icns
	modified:   test/fixtures/test-app/build/icon.ico

Any help?
Thanks

**Comment by develar** [comment]
Did you install git-lfs? Please see contributing.md

**Comment by demetris-manikas** [comment]
I believe I have.
git lfs pull
Git LFS: (0 of 13 files) 0 B / 78.32 KB

**Comment by develar** [comment]
Related: https://help.github.com/articles/dealing-with-line-endings/

Are you on Windows?

**Comment by demetris-manikas** [comment]
No. I am using Ubuntu 14.04.4 LTS (trusty)

**Comment by demetris-manikas** [comment]
git lfs ls-files doesnot include the two files mentioned above
00115aa5b5 * test/fixtures/test-app-one/build/background.png
6f3b427c8e * test/fixtures/test-app-one/build/icons/128x128.png
91bb28a5c8 * test/fixtures/test-app-one/build/icons/16x16.png
72ba904f5e * test/fixtures/test-app-one/build/icons/24x24.png
ff3766bbfd * test/fixtures/test-app-one/build/icons/256x256.png
a19e774644 * test/fixtures/test-app-one/build/icons/32x32.png
e30328541c * test/fixtures/test-app-one/build/icons/48x48.png
0d8c14d09d * test/fixtures/test-app-one/build/icons/512x512.png
7057cf1f1a * test/fixtures/test-app-one/build/icons/64x64.png
404def074d * test/fixtures/test-app-one/build/icons/96x96.png
366832d82e * test/fixtures/test-app-one/build/incorrect.ico
ce636d201e * test/fixtures/test-app-one/install-spinner.gif
050d246a84 * test/fixtures/test-app/build/background.png

**Comment by develar** [comment]
Yes, these files are not stored usung git lfs (we're added before), it seems git is confused as result. As solution we can try to readd files to force use of git lfs.
