### ISSUE TITLE
Provide support for building/outputting a Flatpak as part of the build pipeline

### ISSUE THREAD

**Issue by x80486** [electron-userland/electron-builder#3212]
I see there is a [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap) and also an [`electron-installer-dmg`](https://github.com/electron-userland/electron-installer-dmg).

Would it be possible to have an `electron-installer-flatpak` also?

Or just support that format out-of-the box when using the `electron-builder` alone?

**Comment by Wetrain** [comment]
This would be awesome, all Linux distributions support Flatpak :) unlike Snap!

**Comment by oscartbeaumont** [comment]
Are there any updates on this?

**Comment by gasinvein** [comment]
Isn't this a duplicate of #512?
