### ISSUE TITLE
How to check if we're running a dev or production version?

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#3213]
I would like to only autoupdate the app if I'm not in development mode, while avoiding to have to change the code all the time.

What is the best way to check if my app is running in dev mode?
I'm looking for something like,

```
if (!app.isDevMode) {
  //Update, set dev tools, etc.
}
```

Didn't find anything clear in the docs.

**Comment by phanos** [comment]
I see a lot of recommendations suggesting using electron-is-dev

**Comment by gajop** [comment]
Is this really the recommended way? Feels bizarre to use a third party library for this, especially as it's only three lines of code.

Please consider merging this into electron, or electron-builder, it is essential functionality.

Thanks for the answer though!
