### ISSUE TITLE
Configuration & Documentation on fileAssociations

### ISSUE THREAD

**Issue by Martin-Pitt** [electron-userland/electron-builder#3216]
* **Version**: Latest

* **Target**: macOS  & Windows

Whilst trying to figure out how to configure a URL protocol, I saw it was listed at the `fileAssocations` property.

See: https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations

However there are glaring issues with the documentation:

* `name` and `role` are listed twice
* `name` is listed as both required and optional, so which is it?
* What is `schemes` and why is it required?
* What's a `Protocol` type? Is that just a string or is it a specific object?

Also, are there examples of the different practical usecases for `fileAssociations`? It's a bit confusing with URL protocol not being file association but being configured here.

**Comment by phanos** [comment]
I was taking a look at this section too with some confusion... it looks like there is some sort of formatting issue for the list nesting levels. take a look at this: https://github.com/electron-userland/electron-builder/blob/docs/generated/PlatformSpecificBuildOptions.md

**Comment by lexicalunit** [comment]
This threw me too. It looked like the documentation for what a `Protocol` object is was totally missing.
