### ISSUE TITLE
[Feature request] Skip Squirrel step

### ISSUE THREAD

**Issue by antelle** [electron-userland/electron-builder#322]
For apps that don't use Squirrel, that would be useful to completely skip Squirrel archives creation step at build. For example, by adding `autoUpdate: false` config option.

**Comment by develar** [comment]
What do you want to get? Zip or just dir with exe?

**Comment by develar** [comment]
Related to #279

**Comment by antelle** [comment]
I want to get installers without zip for auto-update.

**Comment by develar** [comment]
Do you mean OS X or Windows?

**Comment by antelle** [comment]
Both. Currently my workflow is:
1. package apps for OSX, Windows and Linux with electron-packager
2. build installers for OSX and Windows with electron-builder (I'm on old version, v2.1)
3. create a deb for linux myself

I'm switching to use new electron-builder (hope, it will allow to simplify steps 1 and 2), and I would like to get exe and dmg without additional step of building squirrel zip because I'm using own auto-update instead of squirrel.

**Comment by develar** [comment]
Windows requires Squirrel, please see #279. I think, for you it is ok. Update zip is not created for Windows.

OS X is OS X — no problem here, it is not *** Windows. Got your request, should be a way to disable zip archive generation.

Linux — we can build deb.

Yes, new version should simplify your build — if not, blame me and feel free to file any issue.

**Comment by develar** [comment]
> package apps for OSX, Windows and Linux with electron-packager
I hope it is clear — you do not need to use electron-packager directly anymore.

**Comment by develar** [comment]
OS X: disable ZIP generation — set `build.osx.target` to `["zip]` See https://github.com/electron-userland/electron-builder/wiki/Options#OsXBuildOptions-target

Windows: I think you ok with Squirrel.

**Comment by antelle** [comment]
Thank you!
Yes, Squirrel for Windows is ok, I've switched the installer to using it.
