### ISSUE TITLE
Downloading artifacts as a separate step 

### ISSUE THREAD

**Issue by shesek** [electron-userland/electron-builder#3220]
Is there a way to download all the required artifice files separately from building the app?

I'm using `libfaketime` to make reproducible electron builds (successfully for deb, snap, tar.gz and windows, still trying to figure out AppImage). The problem is that it invalidates TLS certs (they appear to come from the future), which causes the artifact downloads to fail.

My current solution is to trigger a dummy `electron-builder` build for an empty app as a `RUN` step in my Dockerfile (without `faketime`) to download all the artifices, then later (in `CMD`) build the actual app with `faketime` enabled.

This, however, makes my docker build much slower than necessary. And it's a hack. A way to download artifices without building would be much more elegant.

This is also generally useful in a Docker environment, where one could `ADD package.json` and download artifices in an earlier step, then `ADD` everything and build the app in a later step, which better utilizes Docker's caching mechanism and reduces build times.

**Comment by shesek** [comment]
Ping? :)

**Comment by develar** [comment]
Pong :)

```
node_modules/app-builder-bin/linux/x64/app-builder prefetch-tools
```

Change `app-builder-bin` according to your platform (inspect content of `node_modules/app-builder-bin` to find suitable executable).

See https://github.com/electron-userland/electron-build-service/blob/72711d0a1f8041b0de5622ede7b96e4f19290510/cmd/builder/Dockerfile#L50

It is used for electron build service docker image. Something can be missed. Feel free to open a new ticket to prefetch missed dependency.
