### ISSUE TITLE
arch is stripped for windows builds.

### ISSUE THREAD

**Issue by burtonator** [electron-userland/electron-builder#3224]
* **Version**: 20.27.1

* **Target**: win

I'm trying to make .exe files for each platform.  32bit and 64bit but it seems if I put -${arch} in the artifactName it's ignored.

I added a custom prefix to the artifactName so I KNOW it used it but the resulting .exe doesn't have x64 in it like I would like

If I don't make per platform .exe files (one for 32bit and one for 64bit) then I end up with a 600MB installer... 300MB is bad enough already! :)

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/nsis#32-bit-64-bit and https://www.electron.build/configuration/nsis#web-installer

**Comment by JannisX11** [comment]
Likely the same issue: #3574
