### ISSUE TITLE
Set title for GitHub release (GithubOptions)

### ISSUE THREAD

**Issue by sondreb** [electron-userland/electron-builder#3225]
* **Version**: 20.27.1

* **Target**: Mac, Linux, Win

I have attempted to find a solution on setting the title of a GitHub release, and so far no luck. The documentation explains a process where the release definition is created before-hand, and then publish is run. I want to avoid this manual step, and simply have electron-builder create the release.

That works fine, but the problem is no option or ability to define the title of the release. The release is simply named with the version, e.g. "0.0.19".

I would like to name it, something like "MyApp 0.0.19 (Preview)".

This would simplify the deployment of only being a publish operation on the release (after testing), and not a rename of the title.

**Comment by sondreb** [comment]
Attempted to set the "-c.releaseInfo.releaseName" parameter, which was described in the documentation here: https://www.electron.build/configuration/configuration

It says:

"releaseInfo - The release info. Intended for command line usage:"

I was unable to get it working by applying that as a parameter to electron-builder, I also attempted to get it working by adding this section to the root scope of my electron-builder.json:

```json
"releaseInfo": {
    "releaseName": "MyApp ${version} (Preview)"
  },
```

No such luck.

Here is the example I found by someone else, I presume it doesn't work: https://github.com/electron-userland/electron-builder/issues/550#issuecomment-318425437

Another one which attempted to do something similar with YAML config, I doubt that would ever work, but he closed the issue without explaining the solution: https://github.com/electron-userland/electron-builder/issues/1832

And same here: https://github.com/electron-userland/electron-builder/issues/2890

I can additionally confirm that setting the value in the CLI command, does properly write that override value to the "builder-effective-config.yaml" file.

```
-c.releaseInfo.releaseName=\"HELLO-WORLD!\"
```

![image](https://user-images.githubusercontent.com/309938/43983278-1641e186-9cfa-11e8-9d0d-c947d1ffb37f.png)

This releaseName value is not "respected" when publishing to GitHub.

I think the issue is with this line right here, which retrieves the **version** as the name:

https://github.com/electron-userland/electron-builder/blob/efb40dabc608f9787e6ef9420e0fe71cfa97acf7/packages/electron-publish/src/gitHubPublisher.ts#L201

**Comment by bra1n** [comment]
This is still an issue.

**Comment by bra1n** [comment]
I opened another ticket because Stalebot closed this one. (good job, Stalebot!)
