### ISSUE TITLE
Does Code Signing on Mac needs me to pay Apple $99 for developer account?

### ISSUE THREAD

**Issue by deadcoder0904** [electron-userland/electron-builder#3227]
I was trying to use Auto Update but found logs that I can't since its not Code Signed.

Will it require me to pay $99 developer fee? If not, how will I develop further? The docs I've read feel very incomplete & not beginner friendly at all.

Also, @develar I think [this](https://github.com/chentsulin/electron-react-boilerplate/issues/1289#issuecomment-348708068) should be added to Auto Update documentation. I posted it on the [wrong issue to add](https://github.com/chentsulin/electron-react-boilerplate/issues/1289#issuecomment-412291507) it. I was struggling with where to call `AppUpdater` class.

**Comment by karimhossenbux** [comment]
Yes, to get the certificate and sign your app you need that developer account from apple

**Comment by karimhossenbux** [comment]
It is: https://www.electron.build/code-signing#where-to-buy-code-signing-certificate

**Comment by deadcoder0904** [comment]
Oops its the link in the StackOverflow answer but I think it can be done better. One or two lines inline would've stopped me from hours of Googling 😂

Now its just me. Maybe if others also face the same issue, it should be included.

**Comment by deadcoder0904** [comment]
Anyways thank you & I'll close this one

**Comment by leohxj** [comment]
No, only for notarized your app, you need an Apple Developer Id Cert, that need to pay $99.
or your just use the Apple Developer Cert (can export from xcode account pane).
