### ISSUE TITLE
electron build: ⨯ zip: not a valid zip file

### ISSUE THREAD

**Issue by AmrMKayid** [electron-userland/electron-builder#3228]
* **Version**: 20.27.1

* **Target**: mac

when I try to build the electron app i get this error
>   ⨯ zip: not a valid zip file

<img width="1680" alt="screen shot 2018-08-12 at 2 59 10 pm" src="https://user-images.githubusercontent.com/18689888/44002258-4b7ed560-9e40-11e8-91bf-e87b752fe22d.png">

**Comment by pksunkara** [comment]
Got it too. But it immediately went away in the next run.

**Comment by mluis** [comment]
Same here.

**Comment by afc163** [comment]
+1

**Comment by mluis** [comment]
I think this should be an aborted download of the zip file. Does anyone knows where it stands so one can remove it to be downloaded again?

**Comment by thomasdao** [comment]
For Mac, you may delete the cache electron zip file at ~/Library/Caches/electron

**Comment by ismet** [comment]
Getting the same error. 
**electron-builder:** v20.28.2
**electron version:** v2.0.8

My simple build object in package.json is as following:
```
"build": {
    "productName": "product-name",
    "appId": "com.xyz.abc",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "publish": null
  }
```

Is there anything wrong?

**Comment by MasterOfTheTiger** [comment]
The problem is probably a corrupted cached zip file. Try clearing the cache (wherever it is on Windows).

**Comment by elwinzhu** [comment]
same error. cleared the cached zip file but it doesn't help. what is the reason on earth?

**Comment by MasterOfTheTiger** [comment]
Maybe another cache? That's what happened to me.

**Comment by XuShaohua** [comment]
NOTE: On linux, these zip files are placed in `$HOME/.cache/electron` directory.

And by the way, this shall be a bug of electron-builder. If hash missmatch or zip file not fully downloaded, why not remove it and re-download zip file?

**Comment by sgruhier** [comment]
Got same issue. Remove cache (~/Library/Caches/electron on mac) fixed it. It forces reloading

**Comment by Dhruvit36** [comment]
I Found Path on windows : C:\Users\Your Username\AppData\Local\electron\Cache

Delete Zip file from this folder :)

**Comment by samuelcarreira** [comment]
On Linux you can delete the cache folder
`rm -rf ~/.cache/electron`
It worked for me when I had the same problem

**Comment by develar** [comment]
@samuelcarreira Please provide full stack trace of error.

**Comment by Trevor-143** [comment]
> I Found Path on windows : C:\Users\Your Username\AppData\Local\electron\Cache
> 
> Delete Zip file from this folder :)

Thanks a lot for this.

**Comment by tas33n** [comment]
> I just had the same issue. I am running Linux and deleting `$HOME/.cache/electron`didn't fix it because this apparently is the wrong path. Check the paths here: https://github.com/electron-userland/electron-download#cache-location

tnx alot. it fixed after removing old catch files.

**Comment by Fallsleep** [comment]
it happens when you run multiple build task after install electron in `package.json`.

when building task run after `packaging`,  it will `download` the binary zip file.
if you run two or more build task, 
the first task may run well, 
others will failed beacuse zip file was corrupted after twice download.

in linux ,just remove `~/.cache/electron` folder, and build again:
```shell
rm -rf ~/.cache/electron
```
