### ISSUE TITLE
very slow app after electron-builder

### ISSUE THREAD

**Issue by fuzunspm** [electron-userland/electron-builder#3229]
* **Version**: 20.27.1

* **Updater V**:3.1.1

* **Target**: macOS

My app was working fine. I've finished it so it was time to publish via electron-builder. I export my app and installed for testing and everything works fine but now my project app is running so slow. I can't test it because it takes 2 minutes to open all windows. When it finally launches it looks like 1 fps all the time

**Comment by BHDHakim** [comment]
same thing here...

**Comment by develar** [comment]
I think this issue is obsolete (new Electron version).
