### ISSUE TITLE
Allow to specify custom build-version for electron-packager

### ISSUE THREAD

**Issue by antelle** [electron-userland/electron-builder#323]
Currently `build-version` for electron-packager (i.e. build number) is returned from env variable [here](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L191). I'm using build number as commit sha from [gitinfo](https://github.com/damkraw/grunt-gitinfo) grunt task. That would be great to allow specifying custom build number as `builder.build` option.
Workaround:
```javascript
require('electron-builder/out/platformPackager')
    .PlatformPackager.prototype.computeBuildNumber = function() { return ...; }
```

**Comment by develar** [comment]
In progress. Do not send PR — there is some TS design issue (nullability). Fix will be today/tomorrow.
