### ISSUE TITLE
Error with UAC.dll not being found

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#3234]
* **Version**: Latest

* **Target**: Nsis-Web

When trying to use the following in my custom .nsh file

`    !insertmacro UAC_RunElevated`

it throws the below error

```
Error output:
Plugin not found, cannot call UAC::_
Error in macro UAC_RunElevated on macroline 1
```

This happens only one time when a fresh install is done and it needs to download the nsis resources plugin...if the system is built again it finds the proper UAC.dll and then works fine.

Seems to be some minor logic mess up with the way it downloads/runs.

**Comment by mastergberry** [comment]
Never mind...seems to have broken again. Randomly working and not working?

**Comment by mastergberry** [comment]
This is definitely some kind of race condition...it randomly works and others times it does not work with no changes to the configuration/system.

**Comment by jiminy-billy-bob** [comment]
@mastergberry Have you ever found the cause of this issue?

**Comment by mastergberry** [comment]
Nope
