### ISSUE TITLE
Updating from Pre-Release to Release version fails with S3

### ISSUE THREAD

**Issue by samuelcolburn** [electron-userland/electron-builder#3236]
* **Version**:  20.26.0

* **Electron-Updater Version**:  3.0.3

* **Target**:  win-32 nsis

Publishing with S3. Updater does not appear to recognize release builds and update to them. I can update from `v0.0.1-alpha.12` to  `v0.0.1-alpha.13` , but I released `v0.0.1` and users on the alpha release do not see an update. As a test, I released `v0.0.2` as well, and no difference. However, if I manually upgrade a user to `v0.0.1`, they will update to `v0.0.2`. I have not specified any release channels. My build config: 
```
  "build": {
    "productName": "Beacon",
    "appId": "com.github.****.beacon",
    "directories": {
      "output": "build"
    },
    "publish": {
      "provider": "s3",
      "bucket": "beacon-release",
      "region": "us-east-1"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico",
      "verifyUpdateCodeSignature": false
    },
    "linux": {
      "icon": "build/icons"
    }
  }
```

**Comment by Anenth** [comment]
@samuelcolburn got any solution for this?

**Comment by samuelcolburn** [comment]
It's been a while since I looked at that project but I think I just ended up having to use release versioning.
