### ISSUE TITLE
App unsafe, windows defender says not to run installer

### ISSUE THREAD

**Issue by idanlo** [electron-userland/electron-builder#3239]
After building and releasing on github, when opening the installer on windows, i get this alert:
![image](https://user-images.githubusercontent.com/28350511/44096397-d06b333c-9fe3-11e8-89e4-1ae7a6fb91e4.png)
![image](https://user-images.githubusercontent.com/28350511/44096421-e007be8c-9fe3-11e8-8ddd-c67a1fa9bf46.png)
I read something about code certificate or something like that but I don't understand what it means. I need to pay so that my app will not be seen as unsecure?

**Comment by develar** [comment]
> The regular (and often cheaper) Code Signing Certificate shows a warning during installation that goes away once enough users installed your application and you’ve built up trust. The EV Certificate has more trust and thus works immediately without any warnings

https://www.electron.build/code-signing

You need to wait several days until your download location will be marked as safe.
