### ISSUE TITLE
Cannot build for mac on windows.

### ISSUE THREAD

**Issue by yangjunfocus** [electron-userland/electron-builder#3246]
* **Version**: 
20.22.0

3.0.3

* **Target**: 
Mac

OS: windows
I want to building for mac.
cli yarn release --linux --win,building package is ok
but cli yarn release --mac , terminal log this `Build for macOS is supported only on macOS, please see https://electron.build/multi-platform-build` ,why is that?

**Comment by benjamincburns** [comment]
Not the maintainer, but my own reading between the lines follows.

Code signing of mac applications can only be done on mac, and macOS licensing terms limit virtualization of macOS to apple hardware only so it's unlikely that many users are building against virtualized macOS environments from a Windows host.

**Comment by Slapbox** [comment]
It's explained clearly in the docs that this is not possible due to restrictions from Apple. This is not going to be fixed.

**Comment by develar** [comment]
Duplicates #2359
