### ISSUE TITLE
Unable to set icon

### ISSUE THREAD

**Issue by tigierrei** [electron-userland/electron-builder#3250]
* **Version**:  20.11.1

* **Target**: win nsis

When I run `yarn dist` it throws the error `Unable to set icon` . Googling around I have discovered it is caused by a bug in rcedit and it was reported in november 2017, so it seems strange to me that no one has find a solutions until now. Are there any other solutions?

[Here my package.json](https://hastebin.com/bigiparabe.json)

[Here the error message](https://hastebin.com/osaquteyub.cpp)

**Comment by tigierrei** [comment]
@develar I'm sorry to directly tag you but I just need a quick yes or no for the above question... if no, do you know an estimated time to get it fixed?

**Comment by mceachen** [comment]
First update to the latest version (20.28.3 currently), and attach your icon to this ticket. 

FWIW I found windows to be pretty picky with what was accepted as a "correct" format of the `icon.ico` (as it can contain a number of differently formatted images at different resolutions). There are several working examples in the docs, copy one of those icon.ico files into your project and see if that works.
