### ISSUE TITLE
Codesigning Windows build, on a Mac, not working

### ISSUE THREAD

**Issue by adeperio** [electron-userland/electron-builder#3256]
* **Version**: 
20.28.1

* **Target**:  Windows ia32

Hi, I am getting an issue code-signing a Windows .exe build, on a Mac, using a .p12 certificate generated by Apple, and stored in the Mac keychain.

Codesigning works for the Mac app fine. But when trying to sign the Windows build it's not able to sign it.

If possible I would like to try and sign Windows build on a macOS machine, as I've read this is possible in the docs (I hope I've read that correctly?)

After trying to codesign I check the build using:
```
codesign -dv [path/to/app/appname].exe
```

And always get (for the Windows build only, the Mac app signs fine):
```
code object is not signed at all
```

I am building for both Mac and Windows, but for Windows I only build for the ia32 architecture at the moment. Here is what my build config looks like in my package.json

```
"build": {
    "appId": "[my-app-id]",
    "files": [
      "public/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "directories": {
      "buildResources": "build/resources"
    },
    "mac": {
      "category": "public.app-category.productivity",
      "target": [
        "dmg",
        "zip"
      ],
      "publish": {
        "provider": "s3",
        "bucket": "[BUCKET_NAME]",
        "path": "my-path"
      }
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ],
      "publish": {
        "provider": "s3",
        "bucket": "[BUCKET NAME]",
        "path": "my-path"
      }
    },
    "extends": null
  },
```

And here also is how my .env file looks, where I load up environment variables for electron-builder:

```
export ENV_NAME=staging

export CSC_NAME='[certificatename]' #example 1A3JKJD89O
export CSC_LINK=./path/to/mycert/cert.p12
export CSC_KEY_PASSWORD='my-passowrd'
export WIN_CSC_LINK=./path/to/mycert/cert.p12
export WIN_CSC_KEY_PASSWORD='my-passowrd'
export CSC_IDENTITY_AUTO_DISCOVERY=true
export DEBUG=electron-builder

export AWS_ACCESS_KEY_ID=[AWSKEYID]
export AWS_SECRET_ACCESS_KEY=[AWSSECRETACCESSKEY]
export AWS_S3_ENDPOINT=[S3ENDPOINT]
```

And finally, here's the yarn command I run to package the build (this is in a yarn script)

```
export $(grep -v '^#' ./path/t/my/env/file/staging.env | xargs) && electron-builder -p never -mw --ia32 
```

I am not sure what I am missing here? Would anyone have an idea of what else I would need to do?
Thanks! :)

**Comment by Joshandrews43** [comment]
Did anyone find a solution to this?

I am trying to sign an electron application for Windows (I am on a Mac) and am running into the same problem with a Code signing certificate (not EV certificate).
