### ISSUE TITLE
autoUpdater.setFeedURL & autoUpdater.getFeedURL don't work

### ISSUE THREAD

**Issue by Applelo** [electron-userland/electron-builder#3259]
* **Electron Builder Version**: 20.28.1

* **Electron Updater Version**: 3.1.1

* **Target**:  Windows

I try to use the function _autoUpdater.setFeedURL_ to change updater default url but nothing happen.
`autoUpdater.setFeedURL({ "provider": "generic", "url":'http://mywebsite/application/client'});`

And when I try to use the function _autoUpdater.getFeedURL_, the function return _Deprecated. Do not use it_.

**Comment by mrbbm** [comment]
I too got the same issue...

- "electron-builder": "^20.8.2"
- "electron-updater": "^4.0.0"

**Comment by develar** [comment]
updater doesn't use new config? Or just `getFeedURL`  doesn't work (and should not)?

**Comment by jayarjo** [comment]
From what I see in the source `getFeedURL` is [not meant to work](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L183) (anymore perhaps?)

```js
 getFeedURL(): string | null | undefined {
    return "Deprecated. Do not use it."
  }
```

@mrbbm, @Applelo have you solved your problem with `setFeedURL`?

**Comment by Applelo** [comment]
@devlear The updater doesn't use the new config and use instead the config set in package.json. I would like to use getFeedUrl to see if the change was setted.

@jayarjo I didn't solve the problem because I'm not longer part of the project where I needed to use different FeedUrl.

**Comment by jayarjo** [comment]
@Applelo you could use `checkForUpdates()` or `getUpdateInfoAndProvider()` directly (undocumented for some reason) to see details about current config and more. Both return a Promise though.

**Comment by sonvu06** [comment]
> * **Phiên bản Electron Builder** : 20.28.1
> 
> * **Phiên bản cập nhật điện tử** : 3.1.1
> 
> * **Mục tiêu** : Windows
> 
> Tôi cố gắng sử dụng chức năng _autoUpdater.setFeedURL_ để thay đổi url mặc định của trình cập nhật nhưng không có gì xảy ra.
> `autoUpdater.setFeedURL({ "provider": "generic", "url":'http://mywebsite/application/client'});`
> 
> Và khi tôi cố gắng sử dụng hàm _autoUpdater.getFeedURL_ , hàm trả về _Không được chấp nhận. Không sử dụng nó_ .

**Comment by Silvano14** [comment]
Why the documentation is not updated?

**Comment by jim60105** [comment]
When I saw this CLOSED issue, I was surprised that [the doc](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+getFeedURL) hadn't been updated in FOUR years.
