### ISSUE TITLE
Need to Add Page in NSIS installer

### ISSUE THREAD

**Issue by SivaThiyagarajan** [electron-userland/electron-builder#3263]
Actually i just used electron builder (nsis target) to create a setup file for windows application, but i need to add another one installer page in the setup, so i can get the input (serverIP) from the end user and i can modify the api_url in app.asar file or asar unpacked main.js file. Is there is any another way? I checked the Custom Installer script, but it is little confusing. So Please help me in this. And Thanks in advance.

**Comment by agpreynolds** [comment]
Hi, did you ever figure this out? I have a similar requirement and am struggling to implement the custom page

**Comment by sheinin** [comment]
A solution would be appreciated.
