### ISSUE TITLE
Electron Builder AutoUpdater download-progress event is not called on Windows

### ISSUE THREAD

**Issue by fhinardi** [electron-userland/electron-builder#3264]
Version:
Electron Builder - 20.26.0
Electron Updater - 3.0.3
Target: windows - nsis

**Comment by leonardochaia** [comment]
I believe that NSIS **differential** updates do not have progress implementation. (I cant find where I read that right now)

**Comment by leonardochaia** [comment]
#2521

**Comment by develar** [comment]
Duplicates #2521

**Comment by Romain-P** [comment]
@develar ? still bugued
