### ISSUE TITLE
allowPrerelease documentation wrong

### ISSUE THREAD

**Issue by TanninOne** [electron-userland/electron-builder#3268]
* **electron-builder Version**: 20.28.1
* **electron-updater Version**: 3.0.3

* **Target**: Windows

Am I crazy or is the documentation for allowPrerelease completely wrong?
It says:

> allowPrerelease = false Boolean - GitHub provider only. Whether to allow update to pre-release versions. Defaults to true if application version contains prerelease components (e.g. 0.12.1-alpha.1, here alpha is a prerelease component), otherwise false.

But the way it actually works is that with allowPrerelease=true it simply takes the newest version, ignoring the github pre-release and if it's false it will ignore prereleases.
The code at https://github.com/electron-userland/electron-builder/blob/b987a683f31d1695ff2bda125ff40c3e0a664802/packages/electron-updater/src/providers/GitHubProvider.ts#L46 never looks at any version components afaict.

Could someone please clarify what the _intended_ behaviour is?

**Comment by TanninOne** [comment]
ping

**Comment by develar** [comment]
`this.allowPrerelease = hasPrereleaseComponents(currentVersion)`

It is how property is computed. In mentioned code then we simply use first (as entries as sorted) item. If not allowed, then we compute `getLatestVersionString` (pre-release is not latest).
