### ISSUE TITLE
.deb packaging issues

### ISSUE THREAD

**Issue by antelle** [electron-userland/electron-builder#327]
Produced .deb-files have some issues:

1: permissions (I get 0 instead of root/root in permissions):
```
tar -tvf data.tar.xz 
drwx------  0 0      0           0 Apr 17 09:19 ./
drwxr-xr-x  0 0      0           0 Apr 17 09:19 ./opt/
```
I'm building on Mac, this may be an issue. Currently I'm using [patched grunt-contrib-deb](https://github.com/antelle/grunt-contrib-deb) for this, and it can create debs with correct permissinos on each platform. You may create something like this...

2: control file
```
Package: keeweb
Version: 1.1.2-3413983
License: MIT
Vendor: Antelle@Antelle-MacBook.local   <-------------- machine name?? seems there's no option to change it
Architecture: amd64
Maintainer: Antelle <antelle.net@gmail.com>
Installed-Size: 104670 
Section: default
Priority: extra
Homepage: https://keeweb.info
<------------------- Description must be on two lines (see below)
Description: Free cross-platform password manager compatible with KeePass
```
Correct description:
```
Description: (short description, if provided, or empty line)
 bla-bla-bla <------- note the space at the beginning!
```

**Comment by develar** [comment]
We use https://github.com/jordansissel/fpm. Do you use latest 1.5?

**Comment by develar** [comment]
Not quite understand why description is not correct.

**Comment by antelle** [comment]
> Do you use latest 1.5?

Yes, I've just installed it for this.
Description: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Description
```
Description: <single line synopsis>
     	 <extended description over several lines>
```
Some distros (ubuntu?) doesn't show description if it's just synopsis (see [this](https://github.com/antelle/keeweb/issues/141#issuecomment-207443224) comment).

**Comment by develar** [comment]
Please file issues to https://github.com/jordansissel/fpm/issues (and mention this ticket, so, I can subscribe). If you will not get answers/solution in a 2 days, it will be fixed our side. Maybe we will stop to use fpm and will use other solution.

**Comment by develar** [comment]
@antelle I see that you did a lot of tweets in the your package. Maybe I will reuse code from it. Because in this case most of our users will not need to install ruby&gems.

**Comment by develar** [comment]
@antelle Got about description. fpm cannot fix it due to backward compatibility, I guess. I will fix it on our side if Mint/Ubuntu will show correctly new format of description.

**Comment by antelle** [comment]
I've according to [fpm wiki](https://github.com/jordansissel/fpm/wiki), we can specify vendor:
`--vendor VENDOR               (optional) vendor name for this package`
Regarding description:
```
--description DESCRIPTION     Add a description for this package. You can include '
    ' sequences to indicate newline breaks. (default: "no description")
```
Permissions:
```
--[no-]deb-use-file-permissions (deb only) Use existing file permissions when defining ownership and modes
--deb-user USER               (deb only) The owner of files in this package (default: "root")
--deb-group GROUP             (deb only) The group owner of files in this package (default: "root")
```
So I think this could be fixed without making changes to fpm.
> Maybe I will reuse code from your package

I would expect from electron-builder to build RPM's as well. So I'd stick with fpm because it's capable to build them, maybe you will consider adding an RPM option in future as well.

**Comment by develar** [comment]
@antelle Description in progress, permissions — to investigate (as you see, deb-user/deb-group defaults to root already).

**Comment by antelle** [comment]
I think the problem with permissions is with 'deb-use-file-permissions', so it could be getting permissions from OS which is incorrect on mac.

**Comment by develar** [comment]
On install no permissions issues:

```
develar@ubuntu:/opt$ ls -l
total 8
drwxr-xr-x 4 root root 4096 Apr 17 08:20 Onshape
drwxr-xr-x 4 root root 4096 Apr 17 13:49 TestApp
```

**Comment by develar** [comment]
Description. You are right — thanks. Mint & Ubuntu render it a bit different but in both cases better than before.

**Comment by develar** [comment]
@antelle You can pass most of the fpm flags using `build.linux` field `fpm: ['--flag', 'value', '--flag2', 'value2']` I don't test it, bit should work. Feel free to open new issue if permissions issue is still actual (as I checked, on install permissions are ok).
