### ISSUE TITLE
Hook for after electron.exe has completely finished being modified

### ISSUE THREAD

**Issue by amfio** [electron-userland/electron-builder#3272]
* **Version**: 
20.22.0

* **Target**: 
Windows

**Description**:
Once Electron builder has finished modifying electron.exe into its final form I would like to apply some changes to the exe manually myself before it is code signed.

Currently I am carrying out these changes in the `afterPack` hook, however I think further changes to the exe are taking place by (or a dependency of) electron-builder after this hook has been triggered. I am assuming this because the final .exe file is corrupt and crashes with an Access Violation error.

If I move my .exe modifications a bit later in the build process (e.g. either by dumping them in the custom Windows code signing override/delegate function; or by running them manually after electron builder has completely finished) the .exe works as expected which points to electron-builder doing  _something_ to the .exe after the `afterPack` hook and before the code signing takes place. I have tried looking through the code but I cannot work out what changes take place in this timeframe. 

As I would like to make use of the electron-builder code-signing functionality, I do not want to override the custom `sign` function and also cannot make my modifications after electron-builder has finished and the code has been signed. This means I need to try find (or implement) an alternative hook to carry out my tasks after the exe has been completely finished, but before the code signing takes place.

To help me with this, I have a few questions if anyone can give some guidance that would be fantastic:
- Does something happen to the .exe after `afterPack` or am I going down a rabbit hole? I had assumed at this stage the binary was completely finished but it doesn't seem that way.
- Is there any other kind of hook I could hook into that represents "after the .exe is completely finished and won't be touched again until code-signing"? I have obviously looked at the docs and not found one, but just wanted to ask incase anyone had any ideas or if I have missed something!
- If there isn't such a hook, would you consider accepting a PR to implement one? E.g. maybe `preCodeSign` or `afterPackFinalised`? Obviously once I find out what (if anything) is happening to the exe after `afterPack` it would be easier to come up with a `afterX` hook name.

Just for the sake of completeness, I am making similar modifications to the Electron framework binary for OSX, however it doesn't seem to suffer from this same issue and executing the changes from the `afterPack` hook is working.

**Comment by amfio** [comment]
I have carried out further investigation into where exactly the .exe file gets modified between the `afterPack` hook and the code signing. I think I have found that it is the execution of `rcedit` to add the resources to the .exe.
https://github.com/electron-userland/electron-builder/blob/2df0e1cc03992bf74febcc76cb24206f2876239d/packages/app-builder-lib/src/winPackager.ts#L335

So that at least solves my first questions of what is causing the .exe to change after `afterPack`.

My question now is: wouldn't it make more sense to carry out the `editResources` part of the `signAndEditResources` before the `afterPack` hook is called so that the app is in its final state by the time the `afterPack` hook is invoked?

If you don't agree that that makes sense (or if you don't think it is possible for technical reasons) would you consider reviewing a PR to add a `afterResourceFinalised` type hook that occurs after the .exe is in its final form, but before the code signing takes place?

**Comment by dominic-simplan** [comment]
Same here. I would like to rename the .exe before it is packaged, but with both afterPack or afterSign, the app icon is lost from the exe if I try to rename it in one of these hooks.

**Comment by develar** [comment]
@dominic-simplan To rename app you should use `artifactName`

**Comment by develar** [comment]
@amfio Please use `afterSign` hook.

**Comment by amfio** [comment]
`afterSign` unfortunately does not meet my needs, I need to carry out a task after the exe is in its final form but **before** code signing takes place. Effectively my hacked solution to this problem was to override the signing functionality but to then invoke the original signing function, e.g:

```
import * as windowsCodeSign from '../node_modules/electron-builder-lib/out/windowsCodeSign';
const originalSignFunction = windowsCodeSign.sign;

windowsCodeSign.sign = function(options) {
    const signFunctionContext = this;
    const signFunctionArgs = arguments;

    return doMyPostExeFunction().then(() => {
        return originalSignFunction.apply(signFunctionContext, signFunctionArgs);
    });
};
```

There is no longer active development on the app I required the functionally for, but I still think a hook for `preSign` to carry out tasks immediately before the signing process makes sense - or at least making it so that `afterPack` is truly after everything is done (e.g. after the `.exe` has been modified using `rcedit`). Obviously I am happy to submit a PR for this, I was just originally looking for clarification as to why additional modifications were taking place between the `afterPack` and the code signing process.
