### ISSUE TITLE
${author} is not replaced

### ISSUE THREAD

**Issue by skleeschulte** [electron-userland/electron-builder#3273]
* **Version**: 20.28.2

* **Target**: Windows, NSIS, ia32 and x64

I have an electron-builder.json file with a copyright field:

    {
        "copyright": "Copyright © 2018 ${author}",
        ...

And I have an author field in the package.json file:

    {
        "author": {
            "name": "Bob",
            "email": "bob@foo.bar"
        },
        ...

Rightclicking the NSIS setup file and choosing Properties -> Details, I see "Copyright © 2018 ${author}" in the copyright field.

Am I missing something or is this a bug?

**Edit:** The `${author}` placeholder for the copyright field is documented here: [https://www.electron.build/configuration/configuration#configuration](https://www.electron.build/configuration/configuration#configuration)

**Comment by amfio** [comment]
I believe the documentation is suggesting that default copyright value is hard-coded to the form "Copyright © year ${author}" where electron builder will fill in the author for you.

I think if you override the value of the "copyright" field in electron-builder.json, it completely overrides the default value will appear exactly as you have suggested, I do not think any interpolation takes place.

This looks to be where the logic occurs so feel free to come to your own conclusion:
https://github.com/electron-userland/electron-builder/blob/d68041e3c7f0905b53229ce018813500e1ae269b/packages/app-builder-lib/src/appInfo.ts#L104-L110
