### ISSUE TITLE
App doesn't work when the target is "mas" and some files are not signed

### ISSUE THREAD

**Issue by oscarjiv91** [electron-userland/electron-builder#3275]
Hello. I'm using the v20.28.2 of electron builder. When I make a build for distribution to Mac App Store, using the Application Loader, the .app inside the "mas" folder throw this error when I try to open it:

> LSOpenURLsWithRole() failed with error -10810 for the file /path/to/my_application.app

And when I try to run directly from the binary I see this message in terminal and I can't find a way to debug it:

> Killed: 9

Setting the target to **.dmg** works well though. I have these certificates in my keychain:

> 3rd Party Mac Developer Application: Company, Inc (xxxxxxxx)
> 3rd Party Mac Developer Installer: Company, Inc (xxxxxxxx)
> Developer ID Application: Company, Inc (xxxxxxxx)
> Developer ID Installer: Company, Inc (xxxxxxxx)

Although I can't open this .app, I tried to submit it using Application Loader. It uploaded successfuly after a few fixes with my certificates, but later I received an email from Apple saying that some .so files weren't signed. I have these .so files in the asar.unpack (only way to make it work). 

Is there a way that electron-builder can sign these files? Only some type of files are currently being signed?

I also tried this approach:
1. Added a script using 'afterSign' in package.json
2. Signed manually those .so files like:

> codesign --sign "3rd Party Mac Developer Application: Company, Inc (xxxxxxxx)" --force $path/to/the_file.so

I still can't open the .app inside the "mas" folder. I submited to the App Store again but not receiving any email from them yet.

Any ideas on how to solve it, or debug this?

This is my entitlements.mas.inherit.plist

<img width="798" alt="captura de pantalla 2018-08-25 a la s 09 51 00" src="https://user-images.githubusercontent.com/4256218/44618897-b3a95500-a84c-11e8-8321-61eea00ead91.png">

And the entitlements.mas.plist (application-group is replaced by the actual application group)

<img width="798" alt="captura de pantalla 2018-08-25 a la s 09 50 48" src="https://user-images.githubusercontent.com/4256218/44618892-aa1fed00-a84c-11e8-8984-83ef09607e73.png">

**Comment by tassoevan** [comment]
Any updates on this?

**Comment by oscarjiv91** [comment]
1. After some tests I figured out that the .app inside the "mas" folder doesn't work because of the com.apple.security.app-sandbox. If it's set to "YES" I'm not able to open it. BUT after submit it to the App Store, they can open and review it with no problem. Probably because it has to be ran in sandbox mode? (I tried this without success on my computer).

2. I signed the .so files using "afterPack" in package.json. To run this .js script:

```
exports.default = function(context) {

  const exec = require('child_process').exec;

  var yourscript = exec('sh sign_missing_files.sh',
  (error, stdout, stderr) => {
      console.log(`${stdout}`);
      console.log(`${stderr}`);
      if (error !== null) {
        console.log(`exec error: ${error}`);
      }
  });


}
```

That runs this .sh script:
```

export root_path=$PWD
export t_path="$root_path/dist/mas/MyApp.app/Contents/Resources"
echo "signing missing files"
codesign --sign "3rd Party Mac Developer Application: MyCompany, Inc (XXXXXXXX)" --force $t_path/app.asar.unpacked/path/to/file/example.so --verbose=2
```

After doing this, I didn't receive any error related to unsigned files from Apple

**Comment by ganeshrvel** [comment]
you could have just used the "build"."mas"{"binaries": ['/file/to/binary'] } in package.json in the current version of electron builder
