### ISSUE TITLE
Proper way to get the path to extraFiles

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#3281]
I am currently using the [extraFiles](https://github.com/gajop/spring-launcher/blob/7e3a4ccd4bf50d2ca5deef12fab17400b989d854/package.json#L24) property to bundle [binaries](https://github.com/gajop/spring-launcher/tree/7e3a4ccd4bf50d2ca5deef12fab17400b989d854/bin).

That seems to work fine (at least with AppImage), but figuring out the correct path is starting to be pretty [tricky](https://github.com/gajop/spring-launcher/blob/7671b1700ffb98c56f0031896d308e9e702f6f4f/src/spring_platform.js#L11-L14), and I can only imagine it will get more difficult with other build targets.

Is there a proper way to get the path to the extraFiles that would work in both dev mode and various electron-builder targets?

**Comment by develar** [comment]
For production `process.resourcesPath` should work https://electronjs.org/docs/api/process#processresourcespath — `path.dirname(process.resourcesPath)` (since you use extraFiles, and not extraResources).

But for dev no way.

**Comment by gajop** [comment]
Thanks, will check it out!

**Comment by twigs67** [comment]
Hey, do you actually have bin in your electron packaged app, because I can't find it in mine? 

Also, for Windows, don't you have to use backslash, e.g., ```ath.resolve(`${process.resourcesPath}\\.\\/bin\\${executableBin}`);```?
