### ISSUE TITLE
Windows installer error 2725

### ISSUE THREAD

**Issue by LorenzoBonanni** [electron-userland/electron-builder#3287]
* **Version**: 20.28.3

* **Target**: Windows, msi, x64

I'm compiling on Linux for a windows platform. It generates the .msi file but when i try to install it on a windows platform windows installer gives me error 2725

**Comment by angle319** [comment]
same issue

**Comment by dsanders1234** [comment]
Same issue on macOS

**Comment by lcannon** [comment]
Getting this as well
