### ISSUE TITLE
Built an application using Electron and Confused between the packages ?

### ISSUE THREAD

**Issue by praveen5655** [electron-userland/electron-builder#3288]
Hello everyone,

It's not an issue but its a request as i am new to raspberry-pi3 environment.

I choose to develop my application with Electron because I knew that was cross-platform.
Now I have successfully build the application but confused in building a package like I have to package to Linux or Debian.
I packaged it to linux and tried to execute in raspbian but its not executing.

I get really confused with all that "target", "arch" etc.
Do I have to build for Linux or Debian ? Knowing that I am running on Raspbian Jessie.
I tried to find some configurations for a electron-app build for raspberry but I have found none.

please help me to overcome this problem which appropriate suggestion and links.

So, if anyone can tell me what option I have to set (and with what parameter if possible) to build my app for my Raspberry Pi 3 (run on Raspbian) it would be amazing !

Thanks !

**Comment by NickGeek** [comment]
You have to build a deb file (debian package), which is under the linux group. Debian/Raspian is a linux distribution. Your architecture for a Raspberry Pi would have to be ARM (the type of CPU).

**Comment by praveen5655** [comment]
Thank you Mr.NickGeek.
I did it and now I am able to install in it my raspberryPI3 .
but now upon opening the application I am getting the error like "INVALID DESKTOP ENTRY FILE" what might be the problem...
Please help me..
