### ISSUE TITLE
Error: Please set electron-updater version to "^3.0.3"

### ISSUE THREAD

**Issue by sarfarazansari** [electron-userland/electron-builder#3289]
* **"electron-builder": "20.28.3"**: 

* **"electron-updater": "^3.0.3"**: 

```
At least electron-updater 3.0.3 is recommended by current electron-builder version. Please set electron-updater version to "^3.0.3"
```

I've tried with few different versions but not able to fix.

**Comment by gryzzly** [comment]
Killing node_modules and doing `npm install` solved this problem for me

**Comment by sundowatch** [comment]
`yarn add electron-updater` or `npm install electron-updater` solved my problem.
