### ISSUE TITLE
auto-updater timeout specification

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#3292]
Currently there doesn't seem to be a way to set a timeout, and the program tends to be stuck in the autoupdate sequency for a long time, checking to see if there are any updates.
It would be useful to be able to specify a specific timeout interval after which the connection gives the usual `Error: net::ERR_CONNECTION_TIMED_OUT` error.

**Comment by obsius** [comment]
I too have encountered this issue and would like to know how to specify a longer timeout.

**Comment by anna-tc** [comment]
I would appreciate being able to specify a longer timeout.

**Comment by SinghManmohan** [comment]
Anything yet?
