### ISSUE TITLE
Can separate 32 and 64 bit Windows versions be created?

### ISSUE THREAD

**Issue by JohannBlake** [electron-userland/electron-builder#3293]
It isn't clear from the docs whether electron builder lets you create separate 32 and 64 bit versions. I have seen that the nsis target creates a single combined 32/64 bit version. Seems like overkill considering the massive install size just for one version alone. If it is possible, how do you do this? Is this done in the package.json file or from the command line or both?

**Comment by ozooner** [comment]
It's quite clear in the docs:
https://www.electron.build/configuration/nsis#32-bit-64-bit

`--ia32` for only 32bit
`--x64` for only 64bit

**Comment by tzarebczan** [comment]
So the only option is to run the builder twice, one time with each option? Will autoupdater know which file to download automatically?

**Comment by apascualm** [comment]
me too, I join the doubt.

**Comment by iahmedani** [comment]
me too, I join the doubt.

**Comment by BrightSoul** [comment]
Should I join the doubt? Yes, I join the doubt too.

**Comment by marceloch2** [comment]
No, it will not work, just tested here, installed a 32 bits and upload to the Updater server an "electron-builder build --win --x64 --ia32" version, the 32bits machines get the update and crash.

This command above to generate for both arch is not working anymore here with 32bits machines.

Any news folks?

**Comment by HemalR** [comment]
Can confirm - all our users on a 32 bit machine get stuck in a loop, being told that an update has been downloaded but no installation happens when they click on 'restart' and we then have to manually walk them through re-downloading and reinstalling the program

**Comment by HemalR** [comment]
Right, did an experiment by replacing this command:

`build --mac --win -p always`

With this one:

`build --mac --win --x64 --ia32 -p always`

And thus far it seems that that fixes things. I.e. -Updates work automatically for both 32 and 64 bit machines.

I also updated electron to 5.0 and electron builder to 20.41.0 during this change as other potential variables that may have had this effect... Just putting this out there...

**Comment by dnory0** [comment]
If anyone is still looking for a solution, I created a workaround and published it on medium [here](https://medium.com/@h.hocine.abdellatif/electron-builder-create-separate-32-and-64-bits-installers-for-windows-77d12184c0ac), hope it helps somebody.

**Comment by complabs28** [comment]
> If anyone is still looking for a solution, I posted [a workaround on medium](https://medium.com/@h.hocine.abdellatif/electron-builder-create-separate-32-and-64-bits-installers-for-windows-77d12184c0ac), hope it helps somebody.

I cannot see the Gist Package.json Codes Embedded in the Post.
