### ISSUE TITLE
Error: Unresolved node modules: core-js

### ISSUE THREAD

**Issue by mohammadjalili** [electron-userland/electron-builder#3295]
* **electron-builder: 20.28.1**: 

* **Target: Windows x64**: 

hi , i export windows app many times. but today i get this error after run **npm run dist**

`electron-builder
electron-builder version=20.28.1
loaded configuration file=package.json ("build" field)
writing effective config file=dist\builder-effective-config.yaml
Error: Unresolved node modules: core-js
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\packageDependencies.ts:108:17
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\packageDependencies.ts:164:10)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\packageDependencies.ts:82:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Collector.collect (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\packageDependencies.ts:84:6)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\out\util\packageDependencies.js:123:47
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\out\util\packageDependencies.js:128:17)
    at Lazy.<anonymous> (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:112:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (C:\Users\Mohammad\Documents\Project\poker\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\yarn.ts:128:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\out\util\yarn.js:239:18)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at installOrRebuild (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\out\util\yarn.js:68:17)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:457:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:418:70)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:368:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\Users\Mohammad\Documents\Project\poker\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\node_modules\yargs\lib\command.js:237:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (C:\Users\Mohammad\Documents\Project\poker\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! persis-poker@0.0.1 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the persis-poker@0.0.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohammad\AppData\Roaming\npm-cache\_logs\2018-09-03T10_42_04_384Z-debug.log`

<details>
<summary>npm ls --prod</summary>

> +-- @angular/animations@5.2.11
> | `-- tslib@1.9.3
> +-- UNMET PEER DEPENDENCY @angular/common@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @angular/compiler@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @angular/compiler-cli@5.2.11
> | +-- chokidar@1.7.0
> | | +-- anymatch@1.3.2
> | | | +-- micromatch@2.3.11
> | | | | +-- arr-diff@2.0.0
> | | | | | `-- arr-flatten@1.1.0
> | | | | +-- array-unique@0.2.1
> | | | | +-- braces@1.8.5
> | | | | | +-- expand-range@1.8.2
> | | | | | | `-- fill-range@2.2.4
> | | | | | |   +-- is-number@2.1.0
> | | | | | |   | `-- kind-of@3.2.2 deduped
> | | | | | |   +-- isobject@2.1.0
> | | | | | |   | `-- isarray@1.0.0 deduped
> | | | | | |   +-- randomatic@3.0.0
> | | | | | |   | +-- is-number@4.0.0
> | | | | | |   | +-- kind-of@6.0.2
> | | | | | |   | `-- math-random@1.0.1
> | | | | | |   +-- repeat-element@1.1.2 deduped
> | | | | | |   `-- repeat-string@1.6.1
> | | | | | +-- preserve@0.2.0
> | | | | | `-- repeat-element@1.1.2
> | | | | +-- expand-brackets@0.1.5
> | | | | | `-- is-posix-bracket@0.1.1
> | | | | +-- extglob@0.3.2
> | | | | | `-- is-extglob@1.0.0 deduped
> | | | | +-- filename-regex@2.0.1
> | | | | +-- is-extglob@1.0.0 deduped
> | | | | +-- is-glob@2.0.1 deduped
> | | | | +-- kind-of@3.2.2
> | | | | | `-- is-buffer@1.1.6
> | | | | +-- normalize-path@2.1.1 deduped
> | | | | +-- object.omit@2.0.1
> | | | | | +-- for-own@0.1.5
> | | | | | | `-- for-in@1.0.2
> | | | | | `-- is-extendable@0.1.1
> | | | | +-- parse-glob@3.0.4
> | | | | | +-- glob-base@0.3.0
> | | | | | | +-- glob-parent@2.0.0 deduped
> | | | | | | `-- is-glob@2.0.1 deduped
> | | | | | +-- is-dotfile@1.0.3
> | | | | | +-- is-extglob@1.0.0 deduped
> | | | | | `-- is-glob@2.0.1 deduped
> | | | | `-- regex-cache@0.4.4
> | | | |   `-- is-equal-shallow@0.1.3
> | | | |     `-- is-primitive@2.0.0
> | | | `-- normalize-path@2.1.1
> | | |   `-- remove-trailing-separator@1.1.0
> | | +-- async-each@1.0.1
> | | +-- UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
> | | +-- glob-parent@2.0.0
> | | | `-- is-glob@2.0.1 deduped
> | | +-- inherits@2.0.3
> | | +-- is-binary-path@1.0.1
> | | | `-- binary-extensions@1.11.0
> | | +-- is-glob@2.0.1
> | | | `-- is-extglob@1.0.0
> | | +-- path-is-absolute@1.0.1
> | | `-- readdirp@2.1.0
> | |   +-- graceful-fs@4.1.11
> | |   +-- minimatch@3.0.4
> | |   | `-- brace-expansion@1.1.11
> | |   |   +-- balanced-match@1.0.0
> | |   |   `-- concat-map@0.0.1
> | |   +-- readable-stream@2.3.6
> | |   | +-- core-util-is@1.0.2
> | |   | +-- inherits@2.0.3 deduped
> | |   | +-- isarray@1.0.0
> | |   | +-- process-nextick-args@2.0.0
> | |   | +-- safe-buffer@5.1.2 deduped
> | |   | +-- string_decoder@1.1.1
> | |   | | `-- safe-buffer@5.1.2 deduped
> | |   | `-- util-deprecate@1.0.2
> | |   `-- set-immediate-shim@1.0.1
> | +-- minimist@1.2.0
> | +-- reflect-metadata@0.1.12
> | `-- tsickle@0.27.5
> |   +-- minimist@1.2.0 deduped
> |   +-- mkdirp@0.5.1
> |   | `-- minimist@0.0.8
> |   +-- source-map@0.6.1
> |   `-- source-map-support@0.5.6
> |     +-- buffer-from@1.1.1
> |     `-- source-map@0.6.1 deduped
> +-- UNMET PEER DEPENDENCY @angular/core@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @angular/forms@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- UNMET PEER DEPENDENCY @angular/http@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @angular/platform-browser@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @angular/platform-browser-dynamic@5.2.11
> | `-- tslib@1.9.3 deduped
> +-- @fortawesome/angular-fontawesome@0.1.1
> | `-- tslib@1.9.3 deduped
> +-- @fortawesome/fontawesome-svg-core@1.2.2
> | `-- @fortawesome/fontawesome-common-types@0.2.2
> +-- @fortawesome/free-brands-svg-icons@5.2.0
> | `-- @fortawesome/fontawesome-common-types@0.2.2 deduped
> +-- @fortawesome/free-solid-svg-icons@5.2.0
> | `-- @fortawesome/fontawesome-common-types@0.2.2 deduped
> +-- @ionic/storage@2.1.3
> | +-- @types/localforage@0.0.30
> | +-- localforage@1.4.3
> | | `-- lie@3.0.2
> | |   +-- es3ify@0.1.4
> | |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
> | |   | +-- jstransform@3.0.0
> | |   | | +-- base62@0.1.1
> | |   | | +-- esprima-fb@3001.1.0-dev-harmony-fb deduped
> | |   | | `-- source-map@0.1.31
> | |   | |   `-- amdefine@1.0.1
> | |   | `-- through@2.3.8
> | |   +-- immediate@3.0.6
> | |   +-- inline-process-browser@1.0.0
> | |   | +-- falafel@1.2.0
> | |   | | +-- acorn@1.2.2
> | |   | | +-- foreach@2.0.5
> | |   | | +-- isarray@0.0.1
> | |   | | `-- object-keys@1.0.12
> | |   | `-- through2@0.6.5
> | |   |   +-- readable-stream@1.0.34
> | |   |   | +-- core-util-is@1.0.2 deduped
> | |   |   | +-- inherits@2.0.3 deduped
> | |   |   | +-- isarray@0.0.1
> | |   |   | `-- string_decoder@0.10.31
> | |   |   `-- xtend@4.0.1
> | |   `-- unreachable-branch-transform@0.3.0
> | |     +-- esmangle-evaluator@1.0.1
> | |     +-- recast@0.10.43
> | |     | +-- ast-types@0.8.15
> | |     | +-- esprima-fb@15001.1001.0-dev-harmony-fb
> | |     | +-- private@0.1.8
> | |     | `-- source-map@0.5.7
> | |     `-- through2@0.6.5 deduped
> | `-- localforage-cordovasqlitedriver@1.5.0
> |   +-- @types/localforage@0.0.30 deduped
> |   `-- localforage@1.4.3 deduped
> +-- @ngx-share/core@5.3.1
> | `-- tslib@1.9.3 deduped
> +-- angular2-image-upload@1.0.0-rc.1
> +-- electron-push-receiver@2.1.0
> | +-- electron-config@1.0.0
> | | `-- conf@1.4.0
> | |   +-- dot-prop@4.2.0
> | |   | `-- is-obj@1.0.1
> | |   +-- env-paths@1.0.0
> | |   +-- make-dir@1.3.0
> | |   | `-- pify@3.0.0
> | |   +-- pkg-up@2.0.0
> | |   | `-- find-up@2.1.0
> | |   |   `-- locate-path@2.0.0
> | |   |     +-- p-locate@2.0.0
> | |   |     | `-- p-limit@1.3.0
> | |   |     |   `-- p-try@1.0.0
> | |   |     `-- path-exists@3.0.0
> | |   `-- write-file-atomic@2.3.0
> | |     +-- graceful-fs@4.1.11 deduped
> | |     +-- imurmurhash@0.1.4
> | |     `-- signal-exit@3.0.2
> | `-- push-receiver@2.0.1
> |   +-- http_ece@1.0.5
> |   | `-- urlsafe-base64@1.0.0
> |   +-- long@3.2.0
> |   +-- protobufjs@6.8.8
> |   | +-- @protobufjs/aspromise@1.1.2
> |   | +-- @protobufjs/base64@1.1.2
> |   | +-- @protobufjs/codegen@2.0.4
> |   | +-- @protobufjs/eventemitter@1.1.0
> |   | +-- @protobufjs/fetch@1.1.0
> |   | | +-- @protobufjs/aspromise@1.1.2 deduped
> |   | | `-- @protobufjs/inquire@1.1.0 deduped
> |   | +-- @protobufjs/float@1.0.2
> |   | +-- @protobufjs/inquire@1.1.0
> |   | +-- @protobufjs/path@1.1.2
> |   | +-- @protobufjs/pool@1.1.0
> |   | +-- @protobufjs/utf8@1.1.0
> |   | +-- @types/long@4.0.0
> |   | +-- @types/node@10.9.4
> |   | `-- long@4.0.0
> |   +-- request@2.88.0
> |   | +-- aws-sign2@0.7.0
> |   | +-- aws4@1.8.0
> |   | +-- caseless@0.12.0
> |   | +-- combined-stream@1.0.6
> |   | | `-- delayed-stream@1.0.0
> |   | +-- extend@3.0.2
> |   | +-- forever-agent@0.6.1
> |   | +-- form-data@2.3.2
> |   | | +-- asynckit@0.4.0
> |   | | +-- combined-stream@1.0.6 deduped
> |   | | `-- mime-types@2.1.19 deduped
> |   | +-- har-validator@5.1.0
> |   | | +-- ajv@5.5.2
> |   | | | +-- co@4.6.0
> |   | | | +-- fast-deep-equal@1.1.0
> |   | | | +-- fast-json-stable-stringify@2.0.0
> |   | | | `-- json-schema-traverse@0.3.1
> |   | | `-- har-schema@2.0.0
> |   | +-- http-signature@1.2.0
> |   | | +-- assert-plus@1.0.0
> |   | | +-- jsprim@1.4.1
> |   | | | +-- assert-plus@1.0.0
> |   | | | +-- extsprintf@1.3.0
> |   | | | +-- json-schema@0.2.3
> |   | | | `-- verror@1.10.0
> |   | | |   +-- assert-plus@1.0.0
> |   | | |   +-- core-util-is@1.0.2 deduped
> |   | | |   `-- extsprintf@1.3.0 deduped
> |   | | `-- sshpk@1.14.2
> |   | |   +-- asn1@0.2.4
> |   | |   | `-- safer-buffer@2.1.2 deduped
> |   | |   +-- assert-plus@1.0.0
> |   | |   +-- bcrypt-pbkdf@1.0.2
> |   | |   | `-- tweetnacl@0.14.5 deduped
> |   | |   +-- dashdash@1.14.1
> |   | |   | `-- assert-plus@1.0.0
> |   | |   +-- ecc-jsbn@0.1.2
> |   | |   | +-- jsbn@0.1.1 deduped
> |   | |   | `-- safer-buffer@2.1.2 deduped
> |   | |   +-- getpass@0.1.7
> |   | |   | `-- assert-plus@1.0.0
> |   | |   +-- jsbn@0.1.1
> |   | |   +-- safer-buffer@2.1.2
> |   | |   `-- tweetnacl@0.14.5
> |   | +-- is-typedarray@1.0.0
> |   | +-- isstream@0.1.2
> |   | +-- json-stringify-safe@5.0.1
> |   | +-- mime-types@2.1.19
> |   | | `-- mime-db@1.35.0
> |   | +-- oauth-sign@0.9.0
> |   | +-- performance-now@2.1.0
> |   | +-- qs@6.5.2
> |   | +-- safe-buffer@5.1.2
> |   | +-- tough-cookie@2.4.3
> |   | | +-- psl@1.1.29
> |   | | `-- punycode@1.4.1
> |   | +-- tunnel-agent@0.6.0
> |   | | `-- safe-buffer@5.1.2 deduped
> |   | `-- uuid@3.3.2 deduped
> |   +-- request-promise@4.2.2
> |   | +-- bluebird@3.5.1
> |   | +-- request-promise-core@1.1.1
> |   | | `-- lodash@4.17.10
> |   | +-- stealthy-require@1.1.1
> |   | `-- tough-cookie@2.3.4
> |   |   `-- punycode@1.4.1 deduped
> |   `-- uuid@3.3.2
> +-- ionic-angular@3.9.2
> +-- ionicons@3.0.0
> +-- ng2-tooltip-directive@2.1.5
> | `-- tslib@1.9.3 deduped
> +-- ngx-clipboard@10.0.0
> | +-- UNMET PEER DEPENDENCY core-js@>=2.4.1
> | `-- ngx-window-token@0.0.4
> +-- ngx-uploadx@1.2.1
> | `-- tslib@1.9.3 deduped
> +-- UNMET PEER DEPENDENCY rxjs@5.5.11
> | `-- symbol-observable@1.0.1
> +-- sw-toolbox@3.6.0
> | +-- path-to-regexp@1.7.0
> | | `-- isarray@0.0.1
> | `-- serviceworker-cache-polyfill@4.0.0
> `-- zone.js@0.8.26
`npm ERR! peer dep missing: @angular/common@^2.4.9 || ^4.0.0, required by angular2-image-upload@1.0.0-rc.1
npm ERR! peer dep missing: @angular/common@^6.0.0-rc.0 || ^6.0.0, required by ng2-tooltip-directive@2.1.5
npm ERR! peer dep missing: @angular/core@^2.4.9 || ^4.0.0, required by angular2-image-upload@1.0.0-rc.1
npm ERR! peer dep missing: @angular/core@^6.0.0-rc.0 || ^6.0.0, required by ng2-tooltip-directive@2.1.5
npm ERR! peer dep missing: @angular/http@^2.4.9 || ^4.0.0, required by angular2-image-upload@1.0.0-rc.1
npm ERR! peer dep missing: rxjs@^6.0.0, required by ngx-uploadx@1.2.1
npm ERR! peer dep missing: core-js@>=2.4.1, required by ngx-window-token@0.0.4`
</details>

**Comment by hn3000** [comment]
It says `UNMET PEER DEPENDENCY core-js` and `npm ERR! peer dep missing: core-js@>=2.4.1, required by ngx-window-token@0.0.4' in your log output, looks like you forgot to install it -- it needs to be installed manually.

This may have changed in one of the modules that require it?
