### ISSUE TITLE
Does electron-builder work with loginhelper?

### ISSUE THREAD

**Issue by holgersindbaek** [electron-userland/electron-builder#3302]
* **Version**: 20.28.2

* **Target**: mas

I'm trying to implement Electron's new login helper with my Mac app, but I can't seem to get it to work. I'm using electron-builder to build my mac app and it seems there's a specific step in the build process to get the login helper to work:

https://electronjs.org/docs/tutorial/mac-app-store-submission-guide

Can someone confirm that electron-builder does or does not work with electron's new login helper?

**Comment by holgersindbaek** [comment]
When I look in the mac console, I get the following error when l double click the login helper: "Process is not in an inherited sandbox."

![screen shot 2018-09-07 at 17 44 21](https://user-images.githubusercontent.com/698979/45229273-b0d74700-b2c5-11e8-9fc2-4ed8b266906f.jpg)

It seems like someone else has had the same problem in their Electron build process:

https://github.com/electron/electron/issues/5248

Is it me doing something wrong or does electron-builder simply not support the login helper functionality?

**Comment by holgersindbaek** [comment]
I still haven't figured this out. Am I really the only one who is experiencing this issue?

**Comment by holgersindbaek** [comment]
I've started a bounty on SO if anyone feel like looking into it:

https://stackoverflow.com/questions/52709467/electron-login-helper-wont-work-process-is-not-in-an-inherited-sandbox

**Comment by holgersindbaek** [comment]
I ended up signing my application again using Electron's guide - https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md - and now the start at login works.

I'm leaving the bug open, since it should be electron-builder's job to do this.

**Comment by jack-arms** [comment]
Can this be reopened? It seems electron-builder is still not able to sign the login item helper incorrectly on the latest version?

@holgersindbaek were you able to get around this while still using electron-builder, e.g. with afterPack or something like that? Or did you skip electron-builder entirely?
