### ISSUE TITLE
Is it possible to not show the installer screen on updates when "oneClick": false?

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-builder#3303]
I want to let my users choose whether the installation is perMachine/perUser, and also to pick installation directory. So i have

```
    "nsisWeb": {
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true,
}
```

However, every time there's an update, the user has to see the same installation window all over again. Is there a way for electron builder to auto detect the installation settings and directories, and figure itself out to apply update without prompting any UI?

**Comment by Pandakls** [comment]
>> UP <<

I need exactly the same behaviour with this config :

"nsisWeb": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
}

I don't want to show the prompt for updates

**Comment by Pandakls** [comment]
Moreover, i think that the assisted installer should be hidden by default during update.
Usually there's no need to change repository neither the per machine options.
