### ISSUE TITLE
runFullTrust warning when submitting to Microsoft Store 

### ISSUE THREAD

**Issue by evalbahs** [electron-userland/electron-builder#3306]
* **Version**: 19.19.1

* **Target**: appx

I am trying to submit the app to Microsoft Store, but  after verification process (at the Store) runFullTrust warning appears.
I can submit app, but I need to approve that runFullTrust capability is necessary for my app.
----------------------------------------
From the Store:
Restricted capabilities

We detected the use of one or more restricted capabilities in your Package.appxmanifest file. You must request approval to use restricted capabilities by providing more information below. Please include as much detail as possible.  Learn more

If you don't need to declare these capabilities or added them in error, you can remove them from your Package.appxmanifest file and then upload the updated package(s). 
----------------------------------------
The following restricted capabilities require approval before you can use them in your app: runFullTrust
Why do you need the runFullTrust capability, and how will it be used in your product?*
----------------------------------------

I wrote following comment:
It is introduced in accordance with documentation
Package an app manually (Desktop Bridge)
links: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-manual-conversion

https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-manual-conversion#capabilities

For desktop apps that you package by using the desktop bridge, you'll have to add the runFullTrust capability.

<Capabilities>
  <rescap:Capability Name="runFullTrust"/>
</Capabilities>

Is it correct?
Do I need to remove the runFullTrust capability (How can I do it?)?

**Comment by mvbn** [comment]
For electron app on Windows, that’s normal and correct. As reason, just mention that is an Electron app.

**Comment by mvbn** [comment]
I also had this warning. As reason, I mentioned that is an Electron app. And I submitted it. After one week, I received an e-mail from Microsoft, asking me to approve an agreement from a link. And to reply at the e-mail when done. Then, after two days, was finally on the store.

**Comment by vanejung** [comment]
@mvbn No worries. Fingers crossed with mine then.

**Comment by mvbn** [comment]
@vanejung Good luck!

**Comment by evalbahs** [comment]
> @evalbahs I had the same on my submission. Did you manage to successfully submit the app onto the store?

My apologies for the slow reply. Yes, I did manage to successfully submit the app onto the store. I just mentioned that is an Electron app.

**Comment by vanejung** [comment]
@evalbahs Crap, I totally forgot about this ticket.. Thanks for letting me know. My app has successfully gone through too.

@mvbn Thank you for your help earlier as well!

**Comment by haoxi911** [comment]
Hello everyone, it has been 5 years, are you still publishing your Electron apps to Microsoft Store? I am new to this field, and I am most curious that if `runFullTrust` mandatory for Electron apps to run and why?

**Comment by m-a-x-c** [comment]
> Hello everyone, it has been 5 years, are you still publishing your Electron apps to Microsoft Store? I am new to this field, and I am most curious that if `runFullTrust` mandatory for Electron apps to run and why?

Did you manage to get your Electron app on to the Store with runFullTrust?

**Comment by FANMixco** [comment]
> > Hello everyone, it has been 5 years, are you still publishing your Electron apps to Microsoft Store? I am new to this field, and I am most curious that if `runFullTrust` mandatory for Electron apps to run and why?
> 
> Did you manage to get your Electron app on to the Store with runFullTrust?

I was able to do it. I still feel it's strange.
