### ISSUE TITLE
npm run test failure on fresh fork

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#331]
@develar Sorry to bug you again but I am trying to be able to contribute to the project to no avail.
My current problem is that npm run test outputs the following (ubuntu trusty node 5.10.1):
npm run test

> > electron-builder@0.0.0-semantic-release pretest /home/dm/projects/electron-builder
> > npm run compile && npm run lint
> 
> 
> > electron-builder@0.0.0-semantic-release compile /home/dm/projects/electron-builder
> > npm run compile-production && npm run compile-test
> 
> 
> > electron-builder@0.0.0-semantic-release compile-production /home/dm/projects/electron-builder
> > tsconfig -i 2 && ts-babel
> 
> Write doc to /home/dm/projects/electron-builder/docs/options.md
> 
> > electron-builder@0.0.0-semantic-release compile-test /home/dm/projects/electron-builder
> > tsconfig -i 2 test && ts-babel test
> 
> 
> > electron-builder@0.0.0-semantic-release lint /home/dm/projects/electron-builder
> > tslint src/*.ts test/src/*.ts
> 
> 
> > electron-builder@0.0.0-semantic-release test /home/dm/projects/electron-builder
> > node ./test/out/helpers/runTests.js
> 
> Execute /home/dm/.nvm/versions/node/v5.10.1/bin/node /home/dm/.nvm/versions/node/v5.10.1/lib/node_modules/npm/bin/npm-cli.js install --cache-min 999999999 --production /home/dm/projects/electron-builder (cwd: /tmp/electron_builder_published)
> test@1.0.0 /tmp/electron_builder_published
> ├── electron-builder@0.0.0-semantic-release  invalid
> ├─┬ electron-packager@7.0.0
> │ ├─┬ asar@0.11.0
> │ │ └─┬ mksnapshot@0.3.0
> │ │   └── decompress-zip@0.3.0 
> │ ├── electron-download@2.1.1 
> │ └── plist@1.2.0 
> └─┬ read-package-json@2.0.3
>   └── json-parse-helpfulerror@1.0.3 
> 
> npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
> npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.6
> npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
> npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@0.0.1
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
> Execute /home/dm/.nvm/versions/node/v5.10.1/bin/node /home/dm/.nvm/versions/node/v5.10.1/lib/node_modules/npm/bin/npm-cli.js prune --production (cwd: /tmp/electron_builder_published)
> Execute /home/dm/projects/electron-builder/node_modules/.bin/ava  (cwd: /home/dm/projects/electron-builder)
> 
>   - CodeSignTest › create keychain
>   - osxPackagerTest › mac: two-package.json
>   - osxPackagerTest › mac: one-package.json
>   - osxPackagerTest › custom background
>   ✔ RepoSlugTest › repo slug from TRAVIS_REPO_SLUG
>   ✔ RepoSlugTest › repo slug from APPVEYOR
>   ✔ BuildTest › invalid platform
> Skipping app dependencies installation because dev and app dependencies are not separated
> Skipping app dependencies installation because dev and app dependencies are not separated
> Removing /home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/win-x64
> Packaging app for platform linux x64 using electron v0.37.5
> Packaging app for platform win32 x64 using electron v0.37.5
> Skipping app dependencies installation because dev and app dependencies are not separated
> Packaging app for platform linux x64 using electron v0.37.5
> Skipping app dependencies installation because dev and app dependencies are not separated
> Skipping app dependencies installation because dev and app dependencies are not separated
> Packaging app for platform linux x64 using electron v0.37.5
> Packaging app for platform linux x64 using electron v0.37.5
> Skipping app dependencies installation because dev and app dependencies are not separated
> Installing app dependencies for arch x64 to /tmp/electron-builder-test-31496-test-app-5/app
> Skipping app dependencies installation because dev and app dependencies are not separated
> Skipping app dependencies installation because dev and app dependencies are not separated
>   ✔ linuxPackagerTest › no-author-email (248ms)
> Packaging app for platform linux x64 using electron v0.37.5
> Skipping app dependencies installation because dev and app dependencies are not separated
> Removing /tmp/electron-builder-test-31517-test-app-one-0/dist/win-x64
> Packaging app for platform win32 x64 using electron v0.37.5
>   ✔ BuildTest › build in the app package.json (326ms)
>   ✔ winPackagerTest › icon < 256 (318ms)
> Skipping app dependencies installation because dev and app dependencies are not separated
> Packaging app for platform linux x64 using electron v0.37.5
>   ✖ linuxPackagerTest › linux - icons from ICNS failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31506-test-app-one-0/dist/TestApp-linux-x64/electron' -> '/tmp/electron-builder-test-31506-test-app-one-0/dist/TestApp-linux-x64/TestApp'"
>   ✖ linuxPackagerTest › linux failed with "ENOENT: no such file or directory, link '/home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/TestApp-linux-x64/electron' -> '/home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/TestApp-linux-x64/TestApp'"
>   ✖ winPackagerTest › win failed with "ENOENT: no such file or directory, link '/home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/TestApp-win32-x64/electron.exe' -> '/home/dm/projects/electron-builder/test/fixtures/test-app-one/dist/TestApp-win32-x64/TestApp.exe'"
>   ✖ winPackagerTest › noMsi as string ENOENT: no such file or directory, link '/tmp/electron-builder-test-31517-test-app-one-0/dist/TestApp-win32-x64/electron.exe' -> '/tmp/electron-builder-test-31517-test-app-one-0/dist/TestApp-win32-x64/TestApp.exe'
>   ✖ BuildTest › custom output dir failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31496-test-app-one-1/customDist/TestApp-linux-x64/electron' -> '/tmp/electron-builder-test-31496-test-app-one-1/customDist/TestApp-linux-x64/TestApp'"
>   ✖ BuildTest › productName with space failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31496-test-app-one-2/dist/Test App-linux-x64/electron' -> '/tmp/electron-builder-test-31496-test-app-one-2/dist/Test App-linux-x64/Test App'"
>   ✖ BuildTest › version from electron-prebuilt dependency failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31496-test-app-one-4/dist/TestApp-linux-x64/electron' -> '/tmp/electron-builder-test-31496-test-app-one-4/dist/TestApp-linux-x64/TestApp'"
>   ✖ BuildTest › custom buildResources dir failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31496-test-app-one-0/dist/TestApp-linux-x64/electron' -> '/tmp/electron-builder-test-31496-test-app-one-0/dist/TestApp-linux-x64/TestApp'"
> Packaging app for platform linux x64 using electron v0.37.5
>   ✖ BuildTest › copy extra resource failed with "ENOENT: no such file or directory, link '/tmp/electron-builder-test-31496-test-app-5/dist/TestApp-linux-x64/electron' -> '/tmp/electron-builder-test-31496-test-app-5/dist/TestApp-linux-x64/TestApp'"
> API rate limit exceeded for actperepo.
>   ✔ ArtifactPublisherTest › GitHub upload (880ms)
> API rate limit exceeded for actperepo.
> API rate limit exceeded for actperepo.
>   ✔ ArtifactPublisherTest › GitHub upload org (789ms)
>   ✔ ArtifactPublisherTest › GitHub overwrite on upload (773ms)
>   ✔ winPackagerTest › detect install-spinner (2s)
> 
>   9 tests failed
>   4 tests skipped
>

**Comment by develar** [comment]
For me only `winPackagerTest › win ` test failed. 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

**Comment by develar** [comment]
As a first contribution, you can investigate this issue ;)

FYI: win tests on Travis will be enabled when I will get rid of nuget to pack.

**Comment by demetris-manikas** [comment]
Well... It wont exactly be a contribution... Digging a bit into the code I bumped on runTests.js.deleteOldElectronVersion so I got the idea to clear my $HOME/.electron folder. 
This made the errors go away.
