### ISSUE TITLE
Running per-machine installation conditionally on Custom NSIS script

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-builder#3319]
* **Version**: 20.28.4
* **Target**: nsis-web

I plan to change my app from perMachine=true to perMachine=false, but on app updates, i want previous users that installed per machine to keep having their per machine installation.

I thought i could do this by  adding `"include": "build/installer.nsh"` and do something like this:

```
!macro preInit
  # сheck registry for previous installation path
  ${if} ${FileExists} "C:\Program Files\${APP_FILENAME}" # is there a better way to detect a per-machine installation?
   # run the multi user installer
  ${else}
    # do nothing, as perMachine = false already
  ${endif}
!macroend
```

The reason for why i want to try this is because I want to keep `oneClick: false`. So really I have two questions as declared in my code above:

1. What is the best way to detect a per machine installation?
2. How can i make my include nsh script to run the per machine installation process?

**Comment by feelipegr** [comment]
Did you or someone find a better way to check that ? I have the same need here
