### ISSUE TITLE
Question - What is up with nsis-web?

### ISSUE THREAD

**Issue by Menighin** [electron-userland/electron-builder#3320]
* **Version**:  20.28.4
* **Target**: nsis-web

Hi!
Im studying right now how to publish my app for my client in the future.
The best way for my client would be some kind way to run my app without installing it. Like a portable (usually they dont have admin permission on their machine to install apps). But the best BEST way would be some kind of [Java Web Start-like-thing](https://en.wikipedia.org/wiki/Java_Web_Start). This way, the users would access some URL and would download/update/run the application "through" this URL. Is there any kind of publishing like this?

Checking the docs I have seen we have a guy called `nsis-web` but I couldn't find anything about what the heck is it... I even released [a version](https://github.com/Menighin/Vuetify-Electron-Test/releases/tag/v.0.0.1) of a small app to test it but couldn't really see the difference between this and the normal installer... Can someone please explain?

Any help is much appreciated,
Regards

**Comment by iclems** [comment]
Nsis installer contains full app so download size of installer is much larger. Nsis-web installer is very small and then downloads the package itself. 

I agree it would be interesting to get feedback on the preferred way for users who officially don't have the right to install an app. 

Have you tried "portable"?

**Comment by Menighin** [comment]
Hi @iclems, thanks for the answer.

So about portable, we have thought about it but I have some doubts you may help with:

- is it possible to auto update a portable app? Just like we have with the installed ones?
- if so, is the update another big download or does it just downloads "the modified" files?

I'm asking because I generated a simple app with a home screen, built it in portable mode and it was 60mb! It's too large! And then I was worried because I couldn't find any of my code in the build, meaning that an update would maybe download the whole thing again...

Thanks!

**Comment by musafiroon** [comment]
b

**Comment by shairoemi** [comment]
Hey @Menighin, would you mind sharing what solution you ended up going with?
I'm currently exploring solutions to very similar problems as the ones you described and would appreciate your advice.
Thanks!
