### ISSUE TITLE
Custom background for pkg installer

### ISSUE THREAD

**Issue by aeijaei** [electron-userland/electron-builder#3321]
* **Version**:  20.28.3

* **Target**:  mac pkg

Is there a way to include a custom background in PKG installer?
There is no "background" option yet for "pkg" unlike with the "dmg" target.

I am thinking of reconstructing the pkg to embed the background image resource and modifying the distribution.xml.

**Comment by aeijaei** [comment]
I just used pkgbuild and productbuild to create the PKG installer. Closing this ticket now.

**Comment by Amanoi** [comment]
eletron-builder !you can try ! please set the option for background!
