### ISSUE TITLE
Q : Does MSI work with auto-update ?

### ISSUE THREAD

**Issue by bisonfute** [electron-userland/electron-builder#3322]
here https://github.com/electron-userland/electron-builder/releases/tag/v19.41.0 it is written that it does not. But so far many release came with msi improvements and I am not sure about the situation now. Nothing is written in the doc (I would be happy to contribute on writing something in the doc about that).

If not, would auto-update work if I wrap the NSIS in a MSI ?

Thanks for your help.

**Comment by odiseo42** [comment]
Yes. You can ship your app as MSI. Then it doesn't really matter how it got installed, since the auto update will download any file it needs from whatever update server you're using.

**Comment by r0stig** [comment]
Just to add to the discussion; I like that the msi does not come with auto-update. Our company distributes the nsis-installer to "normal" users and msi to companies that has a IT-department that distributes the installations, in those cases the environments is locked down and auto-update wont work.

If msi should have auto-update enabled I would like to set this with a flag or have some kind of variable so I can check this in the code.

**Comment by develar** [comment]
No, MSI should not work with auto-updates because MSI for admins, not for end users.

**Comment by avner-hoffmann** [comment]
@bisonfute - I did the same thing, but I noticed that after the auto update, the new version appears in the window apps as another app. e.g. if my app name is "MyApp" then after installing the MSI I see my app in the installed applications as "MyApp", and when pressing on it I can see its version as 1.12.2.0
Once I deploy a newer release (MSI + NSIS) and auto update the application I see two applications in the installed apps, both are called "MyApp" but one with the older version 1.12.2.0 and the newer with version 1.12.3
@develar - Why is this happening and how can I avoid that? (I did used the nsis configuration key uninstallDisplayName as ${productName} to remove the version number from the installed app name)

**Comment by NunoCuradoFuze** [comment]
@avner-hoffmann have you ever found the solution for this?

**Comment by avner-hoffmann** [comment]
@NunoCuradoFuze - did you try newer versions of electron-builder?

**Comment by NunoCuradoFuze** [comment]
@avner-hoffmann - yes, feeding to MSI the lastest.yml generated by NSIS works but the result are two entries with different app versions. Did you manage to solve your issue?

**Comment by ismoil793** [comment]
It is 2024, what happend on this issue? I hope there is a solution
Is it possible to configure auto update for MSI builds of electron?

**Comment by somebody-kseny** [comment]
> It is 2024, what happend on this issue? I hope there is a solution Is it possible to configure auto update for MSI builds of electron?

Interested too

**Comment by ismoil793** [comment]
> > It is 2024, what happend on this issue? I hope there is a solution Is it possible to configure auto update for MSI builds of electron?
> 
> Interested too

there is a tricky way to achieve it, say you have `YOUR_APP.msi` that you release to some cloudhost. You should always release both `YOUR_APP.msi` and `YOUR_APP.exe` versions of your app. 

Then, you can install `YOUR_APP.msi` to your PC. Later on when you release new versions (`.msi` and `.exe`)
`YOUR_APP.msi` electron-updater will automatically download and instal `YOUR_APP.exe` version. That's how you can keep it up-to-date. But in OS it will show up as you have 2 apps (but it will work as a single app)

**Comment by Pritraj** [comment]
> > > It is 2024, what happend on this issue? I hope there is a solution Is it possible to configure auto update for MSI builds of electron?
> > 
> > 
> > Interested too
> 
> there is a tricky way to achieve it, say you have `YOUR_APP.msi` that you release to some cloudhost. You should always release both `YOUR_APP.msi` and `YOUR_APP.exe` versions of your app.
> 
> Then, you can install `YOUR_APP.msi` to your PC. Later on when you release new versions (`.msi` and `.exe`) `YOUR_APP.msi` electron-updater will automatically download and instal `YOUR_APP.exe` version. That's how you can keep it up-to-date. But in OS it will show up as you have 2 apps (but it will work as a single app)

So if I have the msi signed, to make auto update work, Do I neew to sign the exe too? OR may be both unsigned ?
