### ISSUE TITLE
Can't build snaps on Ubuntu for any other arch than x64

### ISSUE THREAD

**Issue by andreashuber69** [electron-userland/electron-builder#3326]
* **Version**: 20.28.4
* **Target**: snap
* **Node**: v8.12.0
* **NPM**: 6.4.1

Steps to reproduce:
1. Clone https://github.com/andreashuber69/net-worth-desktop
2. In `package.json` replace the linux arch `x64` with `armv7l`.
3. `npm run dist`

On Ubuntu 18.04 x64 the above fails with the following message:

> Cannot set machine from deb_arch 'armv7l'

Full log: [log.txt](https://github.com/electron-userland/electron-builder/files/2386709/log.txt)

Going by the docs, `armv7l` seems to be deprecated. Is this architecture no longer supported?

**Comment by TsPuujee** [comment]
`yarn add electron-packager`
add to **package.json**
scripts": {
"dist": electron-packager ./ MyApp --platform=linux --arch=armv7l
}
`yarn dist`
