### ISSUE TITLE
.build.win.icon is ignored

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-builder#333]
In `WinBuildOptions` there is an option `icon` but the winPackager only looks for icon as `buildResources + 'icon.ico'`

**Comment by develar** [comment]
[Here](https://github.com/electron-userland/electron-builder/wiki/Options#buildwin) no such option ;)

If you want to set app icon, set [build.icon](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon) (path relative to project root).

**Comment by mcfedr** [comment]
`build.icon` not working, https://github.com/electron-userland/electron-builder/blob/master/src%2FwinPackager.ts#L50

It seems like I might have to change to the convention, basically this is legacy, I am currently trying to update from `electron-builder` v2

**Comment by mcfedr** [comment]
I just saw this https://github.com/electron-userland/electron-builder/blob/master/src%2Fmetadata.ts#L158 and thought it might work
