### ISSUE TITLE
autoUpdater.autoInstallOnAppQuit not working?

### ISSUE THREAD

**Issue by paulshapiro** [electron-userland/electron-builder#3330]
* **Version**: 20.28.4

electron-updater 3.1.2

* **Target**: Mac, Windows, Linux

I've set `autoUpdater.autoInstallOnAppQuit` to false, and confirmed that after an update is downloaded (at the event handler) and the user opts not to `.quitAndInstall()`, the app will still install the update when it's quit.

Digging through the code this was not expected as `BaseUpdater/addQuitHandler` should bail if the flag is false. https://github.com/electron-userland/electron-builder/blob/f966f1a22bd7577e493595ac261e4b38ec0ce233/packages/electron-updater/src/BaseUpdater.ts#L65

**Comment by paulshapiro** [comment]
Confirmed as well that `autoUpdater.quitHandlerAdded` is undefined after download and that `autoUpdater.autoInstallOnAppQuit` is still false.

Would love to ship this feature but some members our specific audience would be really upset if they couldn't opt-out of updates. Happy to provide anything else that I can in order to help diagnose.

**Comment by paulshapiro** [comment]
By the way I sent you guys a little Bitcoin via xmr.to with one of my Monero test wallets in the MyMonero desktop app :)

**Comment by develar** [comment]
Fixed in electron-updater 3.1.5 Sorry for delay.

**Comment by paulshapiro** [comment]
@develar Which is the commit which fixed this / Are you certain that this is fixed? I keep seeing the new version of the app getting installed when clicking 'Later' (which does nothing but dismiss my manual dialog) even though `autoUpdater.autoInstallOnAppQuit` is set to `false`. (`autoUpdater.autoDownload` is set to `true` in this scenario). This is with having updated to electron-updater `4.0.6`.

**Comment by paulshapiro** [comment]
Here is my commit where I switched over to the new desired behavior in our app, which does not function as expected. https://github.com/mymonero/mymonero-app-js/commit/71c2d85e92695d80cce2c34a7c90e9ce3313ccbc

**Comment by paulshapiro** [comment]
Hey @develar - appreciate everything you're doing for the community… any information on this one? Thanks a ton for your amazing work.

**Comment by HovhannesB** [comment]
I am facing the same problem, I don't want to update the app without quitandinstall, because if you quit app and very fast open it, it opens with bugs (in one case no fonts, in other no screen). You should close the app and open again to see it normal.

**Comment by paulshapiro** [comment]
@develar Any idea what's up? Hope we can work out this challenge. We're super excited to use this feature. Thanks so much for your amazing work!!

**Comment by jmeinke** [comment]
Happens to them: https://github.com/Automattic/simplenote-electron/issues/1094
Also happens to us with electron-updater v4.0.10. When the user chooses to install the update and clicks later "Later" on the update dialog, the new version of the app is installed without further notification after restarting the app twice.

**Comment by stuartbrussell-intuit** [comment]
I'm seeing this with electron-updater 4.2.0, but only on Windows. On macOS it works as expected.

**Comment by FindChenLinJie** [comment]
how to disable app auto update when app normal quit

**Comment by jaehwa-v6x** [comment]
Setting `autoUpdater.autoInstallOnAppQuit = false` is effective when used before `autoUpdater.checkForUpdate();` However, it appears to be ineffective if used afterwards. In Electron, squirrel.mac is utilized for Mac auto-updates, but unfortunately, squirrel.mac does not seem to offer a mechanism for cancellation.

https://github.com/electron/electron/blob/7981d955b8f84e2129f5a907445fbc0aea6b9fe8/shell/browser/auto_updater_mac.mm
https://github.com/Squirrel/Squirrel.Mac/blob/master/Squirrel/SQRLUpdater.h
