### ISSUE TITLE
Question: Need help getting my tray icon to work on Mac/OS

### ISSUE THREAD

**Issue by kwleland** [electron-userland/electron-builder#3331]
electron-builder version 20.28.4
target: Mac

my app directory  eg /Users/myname/appdirectory has my package.json, main.js etc.

It also has a build directory in it named: build

In the build directory I have a tray icon named: abc.png

I can't figure out how to specify "files" in my package.json so that  running the dmg from electron-builder has a working tray icon.  I tried many possibilities from searching other peoples issues.
There seems to be too many variables where I can have something a little off. 

i used nativeImage so that the dmg wouldn't die on typeError.

but this

let image = nativeImage.createFromPath('./build/abc.png')
tray = new Tray(image);

apparently doesn't find the image although it works with pre electron builder npm start - 
nor does inspection of
/Applications/projectname/Contents/Resources
turn up any sign of abc.png

I concur with others that putting this in the quick start might be helpful.
I know that the language behind files, extraFiles, extraResources is super powerful, so
that electron-builder can build lean-mean images -
but a starter example would help newbies from being buried.

Thanks for a great project - it was exciting to see my electron app come up almost perfectly in a
one file install.
I know its just a little tweak away from working perfectly.

**Comment by thecoolwinter** [comment]
I got it to work by doing this:
In package.json:
"build": {
    //alll ur other things
    "files": ["**/*", "build/icons/icon.png"]
}

put the 16x16 png in that directory
then in the index.js in the tray icon 
tray = new Tray(__dirname + nativeImage.createFromPath('./build/abc.png'))

**Comment by kwleland** [comment]
thanks

Just before I checked back I also got it to work with
    "extraResources": ["./extraResources/**"]
but I like yours better.

The key thing that was really messing me up as you noted 

"build": {
  //all ur other things
  "files" or "extraResources" goes here
}

I had files or extraResources at a higher level (outside of build) which is crap.
