### ISSUE TITLE
Looks for linux homepage in the development package.json not in the application package.json

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-builder#334]
The docs say looks for [homepage in application](https://github.com/electron-userland/electron-builder#in-short) but the code looks in the [development package](https://github.com/electron-userland/electron-builder/blob/master/src%2FplatformPackager.ts#L184)

**Comment by develar** [comment]
And it is [documented in the dev](https://github.com/electron-userland/electron-builder/wiki/Options#development-packagejson). readme will be fixed, thanks.

**Comment by mcfedr** [comment]
Seems confusing that the name and description come from the application package, but that homepage and license come from dev. 

To me it would make sense to look for everything in application package, maybe even falling back to checking dev package (for backwards compatibility?)

I would be willing to make a pull request if its something that would be considered? Maybe this conversation has been had already
