### ISSUE TITLE
Build Electron App for Linux using Docker on Windows 10

### ISSUE THREAD

**Issue by hschindler** [electron-userland/electron-builder#3340]
* **Version**:  3.0.0

* **Target**: Linux

Hello,
I try to run the docker container on Windows 10 with the command from documentation (Multi Platform Build).
This command doesn' work.
The following line does not work: 
--env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \

When I remove this line I get the error:
The source path "C:/Users/xx/.cache/electron"
doesn't exist and is not known to Docker.

I tried it in cmd.exe because PowerShell do not work with "<" operator.

Can somebody help me with the docker run command?

**Comment by GamingWolf** [comment]
I ran into the same issue, and while I didn't fix the issue with the provided docker stuff, I was able to make it work with my own [Dockerfile](https://github.com/GamingWolf/dockerfiles/blob/master/electron-build-work-around/Dockerfile). Note that I only build .rpm and .deb for x64 and armv7l and have not tested other options, however you can just add all the packages you need in the Dockerfile before you build it.

Build the docker image with "docker build -t name_you_want ."
and run it as follows "docker run -it -w /work/ -v PATH/TO/REPO:/work name_you_want".

once its running you will be able to do yarn dist (or whatever your command is) and it will create the unpacked and packaged files.

A small disclaimer, I am by no means an expert on docker and this is the first time I have done something with docker, so if it does not work for you I am very sorry.
