### ISSUE TITLE
Can't start snap - Error while loading libgconf-2.so.4

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron-userland/electron-builder#3341]
Recently I've upgraded electron-builder from `20.2.0` to `20.28.4`

The snap package was built succesfully  with latest electron-builder `20.28.4` But when running snap package  on Ubuntu `18.04`  I am getting the following error: 

```
error while loading shared libraries: libgconf-2.so.4: no such file or directory
```

In older version `20.2.0` there is no such issue and the snap package is running properly. So I had to rollback electron-builder. 

The error can be easily worked around by installing missed dependency

```
sudo apt -y install libgconf2-4
```

But proper solution is to get rid of the dependency or bundle it if possible to snap package.

**Comment by develar** [comment]
Is it still error for latest electron-builder (snap template was updated)? How did you build snap — on Linux or macOS?

**Comment by vasyl-shumskyi** [comment]
Hey @develar , 

Glad to see you again. I have built snap-package on Mac.

With `electron-builder 20.32.2` I can't reproduce this error anymore. 

Thanks!

**Comment by slntopp** [comment]
Same with `electron-builder 22.11.7` on Ubuntu, built on Mac
