### ISSUE TITLE
setFeedUrl issue

### ISSUE THREAD

**Issue by alexa026** [electron-userland/electron-builder#3351]
* **latest**: 

* **mac win**: 

Hi everyone,

I'm experiencing an issue with `setFeedUrl` function when I use it in the app, I get the error message saying that "setFeedUrl is not defined".

Heres my code:
```
app.on("ready", () => {
  const log = require("electron-log")
  log.transports.file.level = "debug"
  autoUpdater.logger = log
  autoUpdater.setFeedUrl({
     provider: 'generic',
     url: 'http://localhost:3002/'
  });
  autoUpdater.checkForUpdatesAndNotify()
  .then(r => {
    log.debug('r', r);
  })
  .catch(e => {
    log.debug('e', e);
  })
});
```

I specifically want to use setFeedUrl on the programmatic way. Even though I know there's an option of adding it in package.json.

**Comment by larvata** [comment]
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L200

There is a typo in your code, the method name is `setFeedURL`.

**Comment by alexa026** [comment]
oh for the love of god, thanks a lot!
