### ISSUE TITLE
Update installation fails on OSX (electron 3.0.0)

### ISSUE THREAD

**Issue by gseregni** [electron-userland/electron-builder#3354]
* **Version**: 20.28.4

* **Target**: OSX

Update installation fails on OSX

at App.checkForUpdates (/Applications/App.app/Contents/Resources/app.asar/webpack:/src/main/update.js:13:15)
    at App.emit (events.js:187:15) code: -1022, domain: 'NSURLErrorDomain' }
Unhandled rejection Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
    at __esModule (/Applications/App.app/Contents/Resources/app.asar/webpack:/node_modules/builder-util-runtime/out/CancellationToken.js:28:39)
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18

Currently using electron 3.0.0

We are pushing updates using Github Releases repo

Someone can help us,?

**Comment by framerate** [comment]
could be related to #3377, no solve figured out yet

**Comment by gseregni** [comment]
Adding this to package.json helps with the transport layer error
```

"extendInfo": {
       "NSAppTransportSecurity": {
          "NSAllowsArbitraryLoads": true
        },
        "NSExceptionDomains": {
          "localhost": {
            "NSTemporaryExceptionAllowsInsecureHTTPSLoads": false,
            "NSIncludesSubdomains": false,
            "NSTemporaryExceptionAllowsInsecureHTTPLoads": true,
            "NSTemporaryExceptionMinimumTLSVersion": "1.0",
            "NSTemporaryExceptionRequiresForwardSecrecy": false
          }
        }
      }
```
