### ISSUE TITLE
Environment variables missing in built application

### ISSUE THREAD

**Issue by joshwcomeau** [electron-userland/electron-builder#3363]
* **Version**: 20.28.4

* **Target**: MacOS

I'm building a developer tool application, where the user needs to be able to run Node commands from within the UI.

When running in development, I have access to the operating system's environment variables, including `process.env.PATH`. This can be used to find the location of Node.js on the filesystem.

When I try running the built version of the app, `process.env` is a small subset of what it should be, and `PATH` doesn't include the path to Node (I'm using NVM).

I tried using [fix-path](https://github.com/sindresorhus/fix-path), didn't help.

If seeing the full code would help, [here's the PR](https://github.com/joshwcomeau/guppy/pull/267/files#diff-fe04ab44bc2c6a9faffe0e23fec8e61c) to switch to electron-builder (highlighting the main Electron file). Really appreciate any guidance!

**Comment by develar** [comment]
Please see https://github.com/sindresorhus/shell-env#readme

**Comment by busterbogheart** [comment]
@joshwcomeau Were you ever able to solve this?  The linked `shell-env` didn't seem relevant.
