### ISSUE TITLE
Cannot download differentially: __installer.exe missing

### ISSUE THREAD

**Issue by bishbashbosh123** [electron-userland/electron-builder#3364]
* 20.28.4: 

* 3.1.2

* Windows - NSIS

Hi,
I'm attempting to use electron-updater for the first time (previously used Squirrel for windows) but I am getting an error in the logs when it is attempting to "download differentially". I am using an S3 bucket. The error is:
```
[2018-10-04 16:09:24.332] [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\James\AppData\Roaming\my-app\__installer.exe'
    at C:\Users\James\AppData\Local\Programs\my-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:119:29
    at Generator.next (<anonymous>)
From previous event:
    at GenericDifferentialDownloader.doDownloadFile (C:\Users\James\AppData\Local\Programs\my-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:118:82)
    at GenericDifferentialDownloader.downloadFile (C:\Users\James\AppData\Local\Programs\my-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:92:17)
    at GenericDifferentialDownloader.doDownload (C:\Users\James\AppData\Local\Programs\my-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:79:17)
    at C:\Users\James\AppData\Local\Programs\my-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\GenericDifferentialDownloader.ts:6:16
    at Generator.next (<anonymous>)
```
It appears to be looking for the latest installer as `__installer.exe` which does not exist in my `AppData\Roaming\my-app\` folder.... but there is a `MyApp Setup 0.0.5.exe` in the `AppData\Roaming\my-app\__update__\` directory... perhaps it should be looking there instead?
 
It does successfully download the full version for update, but obviously the delta update would be better.

Thanks for advice.

**Comment by mpfau** [comment]
same problem over here

**Comment by artemv** [comment]
Same here. Sounds like an electron-updater issue though, not electron-builder (if Squirell delta updating worked).

**Comment by artemv** [comment]
@ddio as for me I've tried to use the same name in `electron-buildr.json`' `productName` and `package.json`' `name` - same issue. But in my case the name is a scoped NPM package like `@my-scope/my-package`.

**Comment by zhaoterryy** [comment]
Does this only occur on first update? Try version 20.30.0 or greater. The fix for this issue was introduced in 20.29.1.

**Comment by develar** [comment]
Duplicates #3400

**Comment by bennettatoms** [comment]
Hi there!

First of all, thank you for all your work on electron-builder (it's remarkable!), and for being so responsive to the issues raised. We're using electron-builder v20.34.0 and just got the same error trying to auto-update for the first time on a windows machine. Mac auto-updating seems to be working fine, but on the windows box we got: 

>  [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\ThisGuy\AppData\Local\OurElectronApp\installer.exe'

The only directory I see inside 'C:\Users\ThisGuy\AppData\Local\OurElectronApp\' is `pending`.

Any advice?

**Comment by skorunka** [comment]
Having the same issue as described by @bennettatoms

**Comment by bennettatoms** [comment]
FWIW, @skorunka , we are now on version 21.2.0 and have not been having any issues with our windows builds.

**Comment by Lazare-42** [comment]
Hello !

I too would like to start by thanking the Electron-updater team for it's work.

We have the same issue as @bennettatoms . To add something to it, electron-updater raises :

> [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\ThisGuy\AppData\Local\OurElectronApp\installer.exe'

When in fact that `exe` file is located at:

> 'C:\Users\ThisGuy\AppData\Local\ourElectronApp-updater\installer.exe'

**Comment by Lazare-42** [comment]
Oops, never mind, this issue was solved by a simple `"npm audit fix"` on my side.

**Comment by mpfau** [comment]
@reddybhavanish sorry, but I am not working on this issue anymore...
