### ISSUE TITLE
Wine image crashes during Windows build

### ISSUE THREAD

**Issue by paulshapiro** [electron-userland/electron-builder#3365]
* **electron-builder** 20.28.4

* **electron-updater** 3.1.2

* **Target** Windows

Thanks for the software. 

I donated recently and would much appreciate your help on this matter as it's blocking our last couple releases for Windows.

Using the stock wine 2.0.3 image that gets downloaded automatically for MacOS 10.13 during `electron-builder`, wine errors with 

```
  • executed        file=~/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine stderr=
                      winedevice.exe(6871,0x401f6000) malloc: *** error for object 0x40301812: pointer being freed was not allocated
                      *** set a breakpoint in malloc_error_break to debug
```

If I instead have electron-builder use my system wine package with `export USE_SYSTEM_WINE=true` and make sure that the wine setup of `~/.wine` occurs under 32-bit mode with `export WINEARCH=win32` before causing wine to set up with e.g. `wine uninstaller` (is 32-bit setup still necessary?), I get a different error:

```
  • executing       file=wine args=[path to]/mymonero-app-js/dist/MyMonero Setup 1.1.0.exe
  • executed        file=wine stderr=
                      0029:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
                      0029:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
                      ...
                      wine: Unhandled page fault on read access to 0x427b02d1 at address 0x4221e70a (thread 0029), starting debugger...
                      0029:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 32 52") (1115)
                      Read the Wine Developers Guide on how to set up winedbg or another debugger
```

`winedbg --auto 32 52` manually run also fails as expected, showing an alert of `Wine program crash`, `Internal errors - invalid parameters received`.

Will owe someone a beer or two if they can help

**Comment by paulshapiro** [comment]
I worked around this by using docker. However, my Windows build is still not launching despite wine not crashing on build. Trying to figure out what's going on.

**Comment by drew-royster** [comment]
@paulshapiro 
It looks like it's not even attempting to build on windows for me. What's your package.json look like?

**Comment by develar** [comment]
Wine updated to 3.0.3 Please try.

**Comment by cenkingunlugu** [comment]
> 3.0.3 Pl

Hello, i am using latest version of electron builder, but i am still getting wine-2.0.3-mac-10.13 and i am having same problem. What can the reason be?
