### ISSUE TITLE
build productName generates app data in two directories

### ISSUE THREAD

**Issue by jeffcunat** [electron-userland/electron-builder#3375]
* **Version**: 20.28.4

* **Target**: nsis

When you set a productName field in the build section of the package.json, the installer will generate two directories.
One is named with the package.json name value and contains Cache, Cookies ...
The other is named with the package.json build.productName value and contains __installer.exe and logs

forked git to illustrate the problem : https://github.com/jeffcunat/electron-webpack-quick-start.git
=> yarn dist
=> click on dist/Electron Quick Start Setup 0.0.0.exe
=> two directories are created in AppData/Roaming : electron-webpack-quick-start and Electron Quick Start

If you set a package.json productName field with the same value than the build.productName value, only one directory productName is created

**Comment by capc0** [comment]
any updates on this?

**Comment by pamann** [comment]
Same issue here, causing some problems with local storage for us. Please reopen

**Comment by finnatsea** [comment]
Still having this issue. Is there another place to modify to ensure app data is placed in its own directory? This is causing breakage when building dev and insider versions.

Can we reopen?
