### ISSUE TITLE
Custom path for latest.yml

### ISSUE THREAD

**Issue by Maxime117** [electron-userland/electron-builder#3376]
Hello

I build applications for Windows and OSX using a generic provider.
My problem is that latest.yml and latest-mac.yml are generated assuming that the zip / exe application is in the same directory as the .yml.

Indeed, my architecture is as follows:
```
updates
│  latest.yml
│  latest-mac.yml
│
└──stable
   └──darwin
   │   └──0.0.1
   │      │ MyApp-0.0.1-mac.zip
   │
   └──win32
       └──0.0.1
          │ MyApp Setup 0.0.1.exe
```

Is there a parameter in the "publish" configuration to prefix the URL in latest.yml with a custom path (and macros such as platform, version ...)?

What I would like
```
files:
  - url: /stable/darwin/0.0.1/MyApp-0.0.1-mac.zip
    ...
path: /stable/darwin/0.0.1/MyApp-0.0.1-mac.zip
...
```

Thanks !

**Comment by develar** [comment]
See https://www.electron.build/configuration/publish#genericserveroptions

Use `url`

> In all publish options File Macros are supported.

**Comment by andrienko** [comment]
Adding version to `url` is useless - as the old versions do not know the version of the newest build. So, version 1.1.1 will seek for updates in http://somestuff.com/updates/1.0.1 folder, while the newest versions is in 5.0.2 folder.

**Comment by Coding-Kiwi** [comment]
@develar I think this should be reopened.
In [createUpdateInfo](https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/app-builder-lib/src/publish/updateInfoBuilder.ts#L165) `path` and `files: - url: ` default to `path.basename(event.file)`. Why not add a small config option here to prefix a path or the version?

Currently I have to build and then manually patch the yaml file to be able to put my releases in seperate folders.

**Comment by hanzhenfang** [comment]
same to me,

**Comment by devPablo** [comment]
I'm facing the same issue, need dynamic "url" & "path" in latest.yml so that electron-updater knows where to look in my S3 bucket. My current solution is to edit the latest.yml file through a Bash script before uploading the release build to S3.
