### ISSUE TITLE
Windows app dependencies not being packaged on Appveyor

### ISSUE THREAD

**Issue by Lange** [electron-userland/electron-builder#338]
Hi again,

When I build my Windows x64 app locally, the `app/node_modules` folder is added to the `app.asar` archive as expected, and everything works. However, my Appveyor builds do not seem to have a `node_modules` folder within their `app.asar`, resulting in runtime errors about missing dependencies.

- [Appveyor build log](https://ci.appveyor.com/project/Lange/dashboard/build/1.0.47)
- [appveyor.yml](https://github.com/nodecg/dashboard/blob/master/appveyor.yml)
- [Release w/ downloads](https://github.com/nodecg/dashboard/releases/tag/v1.0.0)

This issue specifically affects my Windows/Appveyor builds. The OSX/Linux builds seem to be fine.

Thanks!

**Comment by develar** [comment]
Please change https://github.com/nodecg/dashboard/blob/master/appveyor.yml#L22 to `npm install`

In the onshape-desktop-shell there is an error — npm update used instead of `npm install`.

**Comment by Lange** [comment]
Ahh of course. It works now, thanks so much!

**Comment by develar** [comment]
Yeah, it is an npm bug :( So bad :(
