### ISSUE TITLE
Install after quit is not working on Windows NSIS

### ISSUE THREAD

**Issue by andreygmc** [electron-userland/electron-builder#3381]
* **Version**: 
"electron-builder": "20.28.4"
"electron-updater": "3.1.2"

* **Target**: 
Windows 10, NSIS

I have electron application for all users on PC. After update downloaded, I close application. But new installation didn't start. I see only uninstallation of old version.
If application installed only for current user, update process continues fine.
Last logs:
```
12/10/2018 11:36:59.51 [info] [Updater] Auto install update on quit
12/10/2018 11:36:59.54 [info] [Updater] Install: isSilent: true, isRunAfter: false
```

**Comment by SimoPrG** [comment]
I reproduced the same issue here: https://github.com/SimoPrG/electron-zero

I installed the 0.0.0 version for all users in Program Files. Then I released the 0.0.1 version. The auto-update detected the new version and downloaded it. After I closed the app only the uninstaller ran, but the new installer did not.
