### ISSUE TITLE
Enable hardened runtime for macOS 

### ISSUE THREAD

**Issue by bradleySuira** [electron-userland/electron-builder#3383]
* **Version**: ^20.28.4

* **Target**: macOs

With the recent release of macOS Mojave, Apple give us the option to upload a macOS app to be notarized to distribute outside the AppStore to don't have any problem with Gatekeeper. I tried to figure out how to enable the hardened runtime for an Electron app but without success, the first option that I think, was entitlements but isn't, so have the option to enable hardened runtime will be a great feature for macOs distribution outside the AppStore. 

I'm a web/mobile developer and don't have all the knowledge how is builded electron and if it's possible enable this feature, to I want to be humble and if this options is impossible to implement or crazy, my apologize in advance.

Refs:
- [Distribute outside the Mac App Store (macOS)](https://help.apple.com/xcode/mac/current/#/dev033e997ca)
- [Upload a macOS app to be notarized](https://help.apple.com/xcode/mac/current/#/dev88332a81e)

**Solution we'd like**
If it's possible, have an option in the build configuration to enable the hardened runtime for mac os applications.

**Alternatives considered**
Not any at this time, but if we can have something similar to react-native, nativescript or cordova, where we have the option to access the native projects and tweak if its necessary will be great

**Additional context**
The hardened runtime only can be enabled with xcode, because is a flag in the project.pbxproj file and is only available trough native apps with xcode,  so the `xcodebuild` tool when create the archive and sign the app, enable this flag. I don’t now how exactly electron works  but I think that have like a template with a compiled app and the `electron-builder` for example, only replace and bundle the content inside.

[Enable hardened runtime (macOS)](https://help.apple.com/xcode/mac/current/#/devf87a2ac8f)

-----
![image](https://user-images.githubusercontent.com/1889891/46876991-51f57800-ce05-11e8-8efc-9e7415a599b2.png)
![screen shot 2018-10-11 at 9 18 18 pm](https://user-images.githubusercontent.com/1889891/46876993-5326a500-ce05-11e8-9c30-c5dd01cf16dc.png)

**Comment by bradleySuira** [comment]
Thanks @dariocravero, awesome, I will try your suggestions, for now is not a priority for our app to be notarized but still necessary for the future, when I have results, I will share here in case that it's helps to others.

Regards!

**Comment by noahott** [comment]
I'm having a problem with my app where when hardenedRuntime is enabled, the app will crash immediately upon launch without any visible error messages. If I launch from the command line I see this:

`#
# Fatal error in , line 0
# Check failed: SetPermissions(area_start, area_size, PageAllocator::kReadWriteExecute).
#
#
#
#FailureMessage Object: 0x7ffee7d1f740Illegal instruction: 4
`

**Comment by gniezen** [comment]
Not sure how helpful it is, but there is an [electron-notarize](https://github.com/electron-userland/electron-notarize) module in electron-userland. It would be great if electron-builder can automatically notarize macOS apps during packaging!

**Comment by gcadmes** [comment]
Anyone know if hardenedRuntime support has been added to electron-builder yet?

**Comment by gcadmes** [comment]
@rajivshah3, regarding your last comment on December 1st 2018, have you added hardenedRuntime support to electron-builder? The documentation for electron-osx-sign has a "TODO" statement for electron-builder support.
Please let me know. thx

**Comment by martani** [comment]
Hardened runtime is now available in electron-builder [[link](https://github.com/electron-userland/electron-builder/commit/7d5f952b12406683fd77a5eaac45e8d6b0b9f257#diff-95f823016d05ece1f904f6c59a352eba)]. I'm able to submit the app for notarization successfully via `xcrun altool --notarize-app`, but then it crashes when started after that.

Has anyone figured out the issue for this?

**Comment by chawei** [comment]
just realize this has been implemented in `v20.41.0`. thanks @loremattei!
https://github.com/electron-userland/electron-builder/commit/7d5f952

**Comment by rajivshah3** [comment]
@gcadmes according to @chawei it has been implemented. I wasn't able to get it to work in our own app unfortunately, it keeps crashing for us as well 😕

**Comment by develar** [comment]
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

21.0.10 (not yet released):

* set hardenedRuntime to true by default
* set gatekeeperAssess by default to false

I am fighting with Apple support to restore my account (bloody useless security questions), but I hope next week will be first-class support for notarization.

**Comment by noahott** [comment]
> @noahott it looks like it failed to change the permissions on a section of memory to `RWX` (read/write/execute) -- as @rajivshah3 suggests you need to enable the "allow-jit" entitlement.

I've added the allow-jit entitlement, along with a few others and am still getting the same error on launch.

com.apple.security.cs.allow-jit
com.apple.security.cs.allow-unsigned-executable-memory
com.apple.security.cs.disable-library-validation
com.apple.security.cs.disable-executable-page-protection

Anything else you can think to try for this?

**Comment by idoodler** [comment]
@noahott Hi I am experiencing the same issue but with the `mas-dev` target. I discovered that the entitlements are returned as a binary plist, not as a plist.

The entitlements can be viewed with the following command: `codesign -d --entitlements :- /Path/to/my.app`

May this be an issue. I suspect Electron expects a plist instead of a bplist when setting the permissions.

Apple rejected our App because of  a crash and I think its because of this issue. I just discovered the `mas-dev` target while debugging this issue.

Again, here ist he log I get:
```



#
# Fatal error in , line 0
# Check failed: SetPermissions(area_start, area_size, PageAllocator::kReadWriteExecute).
#
#
#
#FailureMessage Object: 0x7ffee4cfc5d0Illegal instruction: 4
```

There is no issue with the dmg version of the app, it is successfully notarized and signed. The `mas`target isn't notarized, as it is not required. I just tried to also notarize the `mas` target, but still no success.

Any input on this issue.

**Comment by idoodler** [comment]
@noahott I just checked the "Console" Application (The one used for viewing log).

I discovered the following log entry (after filtering for the Application name):
`failed to parse entitlements for MyApp[74469]: OSUnserializeXML: syntax error near line 1`

Do you get the same log message?

**Comment by noahott** [comment]
@idoodler I'm not finding any console log messages with "OSUnserializeXML"

**Comment by noahott** [comment]
I added "entitlementsInherit": "entitlements.darwin.plist" and i no longer get the SetPermissions error, but my app still crashes with a different error now 

`
cwd = process.cwd();
                        ^
Error: ENOENT: no such file or directory, uv_cwd
`

**Comment by idoodler** [comment]
@noahott thx for your reply. I already have set the property `entitlementsInherit`. The app in question is already deployed in the AppStore, but I am unable to push an update because of this odd behaviour. I opened an TSI at Apple. I think it‘s a Problem with the `codesign` tool from Apple.
