### ISSUE TITLE
publisher "send request failed"

### ISSUE THREAD

**Issue by thosmos** [electron-userland/electron-builder#3387]
* **Version**: "electron-builder": "^20.28.4", "electron-publisher-s3": "^20.17.2", "electron-updater": "^3.1.2"
* **Target**: mac osx

```json
  "build": {
    "publish": {
      "provider": "s3",
      "bucket": "my-bucket-name"
    }
  }
```
when I run `./node_modules/.bin/electron-builder -p always` I get the following error:
```
  ⨯ RequestError: send request failed
caused by: Get https://s3.amazonaws.com/my-bucket-name?location=: dial tcp 52.216.101.37:443: connect: host is down
```
The URL works fine if I browse to it, so it appears to be something wrong with the uploader.

**Comment by kresnahendri** [comment]
I got the same error. it because the endpoint is incorrect. separator  between `s3` and `amazon.com`. It should be customize in `build.publish.endpoint` in `package.json`. like this:
```
"build": {
  "publish": {
    "provider": "s3",
    "endpoint": "https://{bucket_name}.s3-ap-southeast-1.amazonaws.com"
    // ...
  }
}
```
