### ISSUE TITLE
ANSI escape sequences displayed literally when downloading NSIS for the 1st time

### ISSUE THREAD

**Issue by tmcdos** [electron-userland/electron-builder#3388]
* **Version**:  20.28.4

* **Target**: Windows 7 SP1 x64

### Expected behavior

All ANSI escape sequences should be executed rather than displayed literally.

### Actual behavior

Notice the bright green, dark blue, and yellow texts in the attached screenshot - however, when the downloading of NSIS installer begins then the ANSI escape sequences are displayed literally rather then being executed.
![nsis](https://user-images.githubusercontent.com/19253115/46907026-0205d680-cf15-11e8-8a0e-27bae234bd25.png)

### How to reproduce

You can use the repository of an actual project - https://github.com/tmcdos/mockapist but I think this can be reproduced with any project on Windows.
Just make sure that there is no **Cache** folder inside `d:\Profile\user\AppData\Local\electron-builder`

$ git clone git@github.com:tmcdos/mockapist.git
$ npm install
$ npm build

**Comment by tmcdos** [comment]
Issue is not stale and needs more attention.

**Comment by develar** [comment]
Fixed in 21.x versions.
