### ISSUE TITLE
Unable to publish on Github Releases using Travis

### ISSUE THREAD

**Issue by tmoreno** [electron-userland/electron-builder#3389]
* **Version**: 20.28.2 
* **Target**: Windows

Hi!

I'm trying to publish Windows releases on Github using Travis.

I have this Travis configuration file:
https://github.com/tmoreno/open-log-viewer/blob/master/.travis.yml

When I fire a new release, Travis send me this error:

`GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"`

I don't have that error for OSX config.

If I remove this line:
```
--env-file <(env | grep -vE '\r|\n' | grep -iE 'GH_TOKEN|DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|WIN_CSC|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
```

It's works without errors but the exe file is not signed.

How I can sign and publish my exe file?

Thanks!

**Comment by polarathene** [comment]
Is this still an issue for you? The linked yml file is created/committed in Jan 2019, whereas your issue is from Oct 2018.
