### ISSUE TITLE
Windows shortcut doesn't work when `productName` contains a space

### ISSUE THREAD

**Issue by Lange** [electron-userland/electron-builder#339]
When `build.productName` in `package.json` contains a space, the shortcut generated by the Windows installer will not work, as it does not wrap the exe name in quotes. For example:

```
C:\redacted\Local\nodecg\Update.exe --processStart NodeCG Dashboard.exe
```
... instead of:
```
C:\redacted\Local\nodecg\Update.exe --processStart "NodeCG Dashboard.exe"
```

**Comment by develar** [comment]
Reported as Squirrel.Windows issue https://github.com/Squirrel/Squirrel.Windows/issues/667

**Comment by philipgiuliani** [comment]
Same issue for me, i've put a dash in the meanwhile!
