### ISSUE TITLE
Question: Does electron-builder use electron mas build when packaging for mas & mas-dev?

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#3392]
* **Version**: 20.28.4

Not used

* **Target**: mas-dev

I am trying to use securityScopedBookmarks as described [here](https://electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options-callback) and [here](https://github.com/electron/electron/pull/11711#issue-164728914).  

When I do my showOpenDialog callback, I'm getting an empty bookmarks return value, which the documentation says: `The bookmarks array will be empty if the app is not bundled for mas`

I *am* bundling for mas. The documentation also says: `Note that in order to test this, one must build electron for mas`

SO - Is electron-builder bundling for mas with the electron-mas build? (eg: electron-v3.0.4-mas-x64.zip)? 

If not, that would explain my problems. If so, then something else is weird.

Thanks.

**Comment by rr326** [comment]
Never mind - I'm pretty certain it does.
(I deleted everything from ~/Library/Caches/electron and confirmed that it is downloading the mas build.)

**Comment by jfuechsl** [comment]
@rr326 I'm running in the same issue you described above. Did you find a fix for it?

**Comment by jfuechsl** [comment]
@rr326 Tracked down your comments in https://github.com/electron/electron/pull/11711. I think that will get me somehwere. Thanks for the test repo!

**Comment by rr326** [comment]
Check out [this issue](https://github.com/electron/electron/issues/16664). 
I think the security scoped bookmark feature is not working properly.
