### ISSUE TITLE
'Unhandled rejection Error: Cannot find certificate 中文测试'

### ISSUE THREAD

**Issue by ovo4096** [electron-userland/electron-builder#3396]
* **Version**:  ^20.28.1

* **Target**: Windows 10

I entered the Subject Name of my certificate but I get a error is cannot find it. What should I do?
My certificate is Chinese Subject Name, Does it not support Chinese?

```
Unhandled rejection Error: Cannot find certificate 中文测试
```

```
certificateSubjectName: '中文测试'
```

**Comment by ovo4096** [comment]
I successfully found it using the SHA1 value of the certificate. but `certificateSubjectName` not found it.

This may be a problem it does not support chinese? 
```
win: {
  certificateSha1: '1E9CFB308269A03100DA31319E2562C2F7XXXXX',
  timeStampServer: 'http://timestamp.digicert.com'
}
```

**Comment by HadiChen** [comment]
Does't support Chinese

**Comment by kzimny** [comment]
Thank you @ovo4096, that solved my issue. My certificate address contains an umlaut `ü`. The certificate was always found but in the pre-release version 22.3.0 of electron-builder that seems to be a problem. Your solution helped me a lot. Thanks!

**Comment by AFTM7512** [comment]
@ovo4096 我按照你的方法试了，结果还是 Cannot find certificate？
