### ISSUE TITLE
Weird behaviour after build

### ISSUE THREAD

**Issue by MiXT4PE** [electron-userland/electron-builder#3399]
* **Version**:  20.28.4

* **Target**: win

**Edit: I think I found the issue: Hardware Acceleration seems to be disabled. How can I force it?**

While developing when I ran my app it started immediately and worked perfectly fine. After I build it (which took forever) it takes minutes to even show a window, takes forever to load the page or register a button-click. It also displays weird artifacts when hovering over the buttons and when opening a pdf it just straight out doesn't work at all.

package.json:
```
{
  "name": "redacted",
  "version": "redacted",
  "description": "redacted",
  "main": "javascript/main.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder --x64",
    "postinstall": "electron-builder install-app-deps"
  },
  "author": "redacted",
  "homepage": "redacted",
  "license": "redacted",
  "build": {
    "appId": "redacted",
    "productName": "redacted",
    "win": {
      "target": "portable",
      "icon": "build/icon.png"
    },
    "mac": {
      "category": "public.app-category.education",
      "icon": "build/icon.png",
      "target": "dmg"
    },
    "forceCodeSigning": "false"
  },
  "devDependencies": {
    "electron": "^2.0.8",
    "electron-builder": "^20.28.4"
  },
  "dependencies": {
    "jquery": "^3.3.1",
    "mathjax-electron": "^2.0.1"
  }
}
```
 If you wonder why I use such an outdated electron version see here:
[https://stackoverflow.com/questions/52844135/view-pdf-in-electron-browserwindow](https://stackoverflow.com/questions/52844135/view-pdf-in-electron-browserwindow)

**Comment by develar** [comment]
https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration
