### ISSUE TITLE
Files and Folders packaged with Installer

### ISSUE THREAD

**Issue by MiXT4PE** [electron-userland/electron-builder#3408]
I am building a application for Windows, macOS and Linux and I have to include an entire folder with pdfs, mp4s etc. into the installer. I want the installer to put those files into AppData and for the program to be able to access them there. 

What is the recommended way of doing this?

**Comment by develar** [comment]
See https://www.electron.build/configuration/contents

Use extraResources and then copy from app resources to AppData https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname
