### ISSUE TITLE
Error while making windows build on linux

### ISSUE THREAD

**Issue by AlexzAK** [electron-userland/electron-builder#3409]
electron-builder version=20.28.4
target=Squirrel.Windows arch=x64

Same issue as here https://stackoverflow.com/questions/47997471/electron-builder-cannot-build-update-for-windows/52948579#52948579

Error message is:
`Error: Exit code: 255. Command failed: mono .../Update-Mono.exe --releasify ...`
`wine: cannot find L"C:\\windows\\system32\\.7z.exe"`

Workaround:
Copy `7z.exe` into `~/.cache/electron-builder/Squirrel.Windows/Squirrel.Windows-1.7.8/` (on linux)

`Update-Mono.exe` is launched from there, so then it able to find `7z.exe`

UPD: for mac os dir should be `/Users/<user>/Library/Caches/electron-builder/Squirrel.Windows/Squirrel.Windows-1.7.8/Update-Mono.exe`

**Comment by develar** [comment]
@AlexzAK Please try 20.31.0 and electron-builder-squirrel-windows 20.31.1
