### ISSUE TITLE
 Cross building electron 2.0.11 on Linux for Mac OS X broken (worked with electron 1.8.8) 

### ISSUE THREAD

**Issue by hacker112** [electron-userland/electron-builder#3416]
* **Version**: 
20.28.4

* **Target**: 
Mac/Windows/Linux (32/64-bit)

* Output of `node_modules/.bin/electron --version`:
v2.0.11
* Operating System (Platform and Version) that ran the built version:
Mac OS X 10.11.6 (15G22010)
* Operating System (Platform and Version) where electron-builder was run:
Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v1.8.8

**Expected Behavior**
Building electron for multiple platforms on Linux and running it on Mac OS X worked well with electron 1.8.8, building it with:

    electron-builder --win --mac zip --linux AppImage --x64 --ia32

**Actual behavior**
With electron 2.0.11 the cross platform build binary fails at start with the following error report:

```
Process:               APP [1239]
Path:                  /Users/USER/Downloads/APP.app/Contents/MacOS/APP
Identifier:            com.company.app
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           APP [1239]
User ID:               501

Date/Time:             2018-10-23 08:32:10.716 +0200
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        5623F84E-462A-5F0D-B125-A74632BAD08D


Time Awake Since Boot: 510 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Downloads/APP.app/Contents/MacOS/APP
  Reason: image not found

Binary Images:
    0x7fff61b0f000 -     0x7fff61b46a47  dyld (360.22) <6B9CD3BA-2D60-3629-A0CB-AB810F55E8DD> /usr/lib/dyld

Model: MacPro3,1, BootROM MP31.006C.B05, 8 processors, Quad-Core Intel Xeon, 2,8 GHz, 32 GB, SMC 1.25f4
Graphics: AMD Radeon HD 6xxx, AMD Radeon HD 6xxx, PCIe, 1024 MB
Graphics: ATI Radeon HD 2600 XT, ATI Radeon HD 2600, PCIe, 256 MB
Memory Module: DIMM Riser B/DIMM 1, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser B/DIMM 2, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser A/DIMM 1, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser A/DIMM 2, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser B/DIMM 3, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser B/DIMM 4, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser A/DIMM 3, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
Memory Module: DIMM Riser A/DIMM 4, 4 GB, DDR2 FB-DIMM, 800 MHz, 0x80CE, 0x4D3339355435313630515A342D4345363620
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x9A), Atheros 9380: 4.0.74.0-P2P
Bluetooth: Version 4.4.6f4, 3 services, 18 devices, 1 incoming serial ports
Network Service: Ethernet 1, Ethernet, en0
Network Service: Ethernet 2, Ethernet, en1
Network Service: Wi-Fi, AirPort, en2
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
Serial ATA Device: ST2000DX001-1NS164, 2 TB
Parallel ATA Device: OPTIARC DVD RW AD-7170A
USB Device: USB Bus
USB Device: USB Bus
USB Device: Evoluent VerticalMouse 4 Left
USB Device: Evoluent VerticalMouse 3
USB Device: USB Bus
USB Device: Bluetooth HCI
USB Device: USB Bus
USB Device: USB 2.0 Bus
USB Device: USB2.0 Hub
USB Device: Mass Storage Device
USB Device: Microsoft¬Æ Nano Transceiver v2.0
USB Device: KB700 Kinesis Freestyle
FireWire Device: built-in_hub, Up to 800 Mb/sec
Thunderbolt Bus: 
```

**Comment by hacker112** [comment]
Well, the product is not really called APP. I just masked the real name since I don't know if my client want to have their product name here. The productName use the following pattern "Xxxxxxxxx YYY zzzzzz".

**Comment by davej** [comment]
Right Oops. I received a similar error when I didn't have productName specified.

**Comment by develar** [comment]
Please try 20.31.2

**Comment by hacker112** [comment]
I have tested this a bit now, and it does not have anything to do with the electron version. I even got it on with the electron v1.8.8. It seems like it is not related to if I am building it on Mac or Linux either. But it is related the how the symlinks like `App.app/Contents/Frameworks/Electron Framework.framework/Electron Framework` are handled when they are zipped.

In version 20.29.0+ (including 20.31.2)  seems like the symlinks are created when they are extracted from the ZIP they come out as regular files (with the link strings in them).

There seems to be some kind of a race condition 20.28.4 (and some earlier versions, I think have seen it in 20.27.1 also, I have been trying a lot of versions). So sometimes it works well and creates the `App.app/Contents/Frameworks/Electron Framework.framework/Electron Framework` symlink and on some builds it fails and the symlinks are missing. 

So one problem is replaced by another problem. Or maybe the race condition problem is still there also.

I don't know how far back the problem exists. But I am going back to 20.20.4 (since I was not able to go back to 20.8.1 since I got the error https://github.com/electron-userland/electron-builder/issues/3107 ).

**Comment by develar** [comment]
@hacker112 So, 20.31.2 doesn't work for you?

**Comment by hacker112** [comment]
@develar No it does not work since the symlinks have been converted to regular files when they have been 

It looks like this (no symlinks):
![screenshot 2018-11-12 09 39 45](https://user-images.githubusercontent.com/620746/48335767-fbc36100-e65e-11e8-8773-ce60313c3e8b.png)

Instead of this (correct symlinks before it has been zipped):
![screenshot 2018-11-12 09 39 56](https://user-images.githubusercontent.com/620746/48335784-054cc900-e65f-11e8-872d-521295dc59b1.png)

**Comment by develar** [comment]
@hacker112 Could you please test 20.35.0 and electron 3.0.8?

**Comment by hacker112** [comment]
Same problem. The problem is not bound to electron version but to how the symlinks are handled when zipped. The non compress APP.app is OK and the APP.app in the .dmg i also ok, but the that has been zip compressed has lost its symlink properties.

**Comment by develar** [comment]
@hacker112 Ouch, do you mean that unarchive from original Electron works correctly, but problem in created app.zip (created for auto-update)?

**Comment by hacker112** [comment]
I am not using auto update. But the zip that is created when I build.

If we see the build process as two parts:
1. Build the app (for mac)
2. Package the app for distribution (in this case zip)

Step 1 works, but step 2 fails. 

This screenshot show what works and the zip that that breaks the app:
![screenshot-2018-11-13-08 02 03](https://user-images.githubusercontent.com/620746/48396562-2672ef80-e71b-11e8-81c3-92d2fce36ede.png)
