### ISSUE TITLE
Desktop file configuration Exec is not applied

### ISSUE THREAD

**Issue by dalviik** [electron-userland/electron-builder#3418]
* **Version**: 20.28.4

* **Target**: Linux

I have this configuration in my package.json, everything's work well but when the desktop file is created, it doesn't apply my exec path
```
"build": {
    "appId": "my-app-electron",
    "productName": "my-app-electron",
    "asar": true,

    "linux": {
        "target": [
            "AppImage"
        ],
        "desktop": {
            "Name": "My Electron App",
            "Exec": "/home/dapaza/Documents/my-app-electron",
            "TryExec": "/home/dapaza/Documents/my-app-electron"
        }
    }
}
```
Is there another way to configure that Exec path?

Thanks

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/linux

> executableName String - The executable name. Defaults to productName. Cannot be specified per target, allowed only in the linux.
