### ISSUE TITLE
Change package description

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#342]
GitHub: 

Change 
`Build installers for Electron apps the easy way`
to 
`Complete solution to package and deploy Electron app`

Change link here: http://electron.atom.io/docs/v0.37.6/tutorial/application-distribution/ (to electron-userland)

**Comment by develar** [comment]
I am not native, maybe someone will help us :)

**Comment by stefanjudis** [comment]
@develar Package description updated...

I'm of vor vacation now for ~2 weeks so will barely able to respond. :)
