### ISSUE TITLE
Change main entry point at runtime

### ISSUE THREAD

**Issue by littlebee** [electron-userland/electron-builder#3422]
* **Version**: 20.19.2

* **Target**: Mac .dmg

I have a question.  

Is it possible to change main entry point for the built application at runtime? 

I’m working on an electron-builder built Electron app that will also have a secondary Electron app that can be accessed via the command line.   Both apps must be in one .dmg which installs a single MacOS Application Bundle and a single copy of the Electron runtime.  It would be preferable to bundle both apps in the same .asar because they share common code.  Something like:  
```
ELECTRON_ENTRY="out/secondaryApp.js" /Applications/MyApp.app/Contents/MacOS/MyApp
```
where the out/secondaryApp.js is relative to the asar root?

Done!  Bribery is a system I understand!

**Comment by develar** [comment]
In your main.js you can simply check envs and include corresponding files. Sorry, I don't get your problem.

**Comment by littlebee** [comment]
That was the solution I had come up with too.   We were wondering if there was simply a cleaner way than using a conditional require at the entry point.

**Comment by develar** [comment]
Thanks for donation.

>  if there was simply a cleaner way 

Provided Electron runtime binary is not modified and used as is. App is distributed in a lot of various formats and it is not reasonable to invent some special solution for such conditional logic in front of your app. So, KISS principle.

**Comment by develar** [comment]
e.g. on Linux for AppImage this logic can be added, but on Windows executable is used as is.

**Comment by littlebee** [comment]
You're welcome!  and thank you for the fast response.   I hear you.
