### ISSUE TITLE
20.29.0 Bug? MAS codesigning fails

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#3425]
* **Version**: 20.29.0

* **Target**: mas 

This is a new error that shows up in 20.29 but not 20.28.
With `DEBUG=electron-osx-sign`

      electron-osx-sign Executing... codesign --sign 6A26EE0DB4362DA30BE6EF06695E6AF16B101C69 --force --entitlements build/entitlements.mac.inherit.plist /Users/rrosen/dev/filing/dist_prod_dist/mac/FileSimple.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa +0ms
      electron-osx-sign Error executing file:
     > Stdout:
     > Stderr: /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/MacOS/FileSimple: code object is not signed at all
    In subcomponent: /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/Library/LoginItems/Contents/_CodeSignature/CodeResources
     +36ms
    Error: Command failed: codesign --sign C706993845BB96DBE90EF9DC927A955FBAF62731 --force --entitlements build/entitlements.mac.inherit.plist /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/MacOS/FileSimple
    /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/MacOS/FileSimple: code object is not signed at all
    In subcomponent: /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/Library/LoginItems/Contents/_CodeSignature/CodeResources

When I built with previous versions I'd get an app stucture of:

    ls FileSimple.app/Contents/Library/LoginItems
    ./        ../       FileSimple Login Helper.app/

When I build with 20.29:

    ls dist_prod_dist/mas/FileSimple.app/Contents/Library/LoginItems                                         
    ./        ../       Contents/

Looking at the changes in 20.29 it seems you've changed the building of helpers and maybe this bug crept in. (I know this is prerelease so maybe you'd catch it anyway, but I needed to try 20.29 because I'm stuck on a bug related to #3412)

**Comment by develar** [comment]
I will check.

**Comment by develar** [comment]
Electron version?

**Comment by rr326** [comment]
4.0.0-beta.5

**Comment by develar** [comment]
So, now it is more clear why our test is green :) Because latest stable is tested.

**Comment by rr326** [comment]
Ah - ok.  I've bumped up to latest electron and ebuilder in the hopes that is solves another bug I'm dealing with so maybe I pushed it too far to the bleeding edge.

**Comment by develar** [comment]
@rr326 Thanks a lot for report. Fixed, will be released soon. It is incompatible change in Electron 4.

**Comment by develar** [comment]
@nornagon I see your commit https://github.com/electron/electron/commit/e22a80b210b4b6087e8dbbe22c895df93ca5f7ff Was moving `Electron Login Helper` out of `Electron Login Helper.app` intentional change or bug?

electron 4: 

<img width="1343" alt="screenshot 2018-10-28 at 09 46 10" src="https://user-images.githubusercontent.com/350686/47613841-5329d480-da96-11e8-97dc-30561397030d.png">

electron 3:

<img width="291" alt="screenshot 2018-10-28 at 09 46 51" src="https://user-images.githubusercontent.com/350686/47613848-6b015880-da96-11e8-924e-2a3e1a3f654d.png">

**Comment by rr326** [comment]
Any update on this @devlar or @nornagon? 

I'm pretty sure there is a bug in electron 3.0.7 and 4.0.0-beta.6 but I can't verify (and create an issue) since I can't get a clean build.  I'd like to be able to post the issue so it can be resolved before 4.0.0 goes GA.

**Comment by nornagon** [comment]
That looks like a bug in 4.0.x, could you raise a bug over on https://github.com/electron/electron/issues? thanks!

**Comment by nornagon** [comment]
(dunno what's happening on 3.0.x though)
