### ISSUE TITLE
Patch away NSS_VersionCheck("3.26")

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#3426]
* **Version**: Latest

* **Target**: Linux

Recent app builds fail on older distributions (such as Ubuntu 16.04.0) with

```
NSS_VersionCheck("3.26")
```

The internet is full of corresponding bug reports.

Turns out many applications run absolutely fine if one patches this restriction away using

```
sed -i -e 's|3.26|3.00|g' chrome
```

This allows many applications to run that would just fail to launch otherwise.

**Comment by develar** [comment]
Do you mean patch electron binary? Probably better to ask electron team to do it.

**Comment by develar** [comment]
Hmm... it seems that probably bundled with appimage libraries should be updated. But 
https://github.com/electron-userland/electron-builder-binaries/tree/master/AppImage/lib/x64 we don’t bundle libnss3 for now. It can leads to issues on other distro.

**Comment by probonopd** [comment]
> Do you mean patch electron binary? Probably better to ask electron team to do it.

Yes, I mean the main binary (that can come under various names).

I am not sure whether bundling libnss3 would be a good idea, probably not.

**Comment by develar** [comment]
Please report issue to Electron, because it will be bad if electron-builder will change provided binaries.
