### ISSUE TITLE
"files" documentation is confusing

### ISSUE THREAD

**Issue by kingpalethe** [electron-userland/electron-builder#3427]
From here: https://www.electron.build/configuration/contents

`Default pattern **/* is not added to your custom if some of your patterns is not ignore (i.e. not starts with !). package.json and **/node_modules/**/* (only production dependencies will be copied) is added to your custom in any case.`

A few issues

-- `custom` is not defined
-- `if some your patterns is not ignore` is not really English
-- many of the links on this page are broken

**Comment by develar** [comment]
Links fixed.

> if some your patterns is not ignore is not really English

What is your suggestion? How do we can improve?

**Comment by CosmoMyzrailGorynych** [comment]
> -- if some your patterns is not ignore is not really English
KISS, you've already written it: "If some of your patterns do not start with `!` symbol."
Better: "If at least one of your patterns does not start with `!` symbol."
