### ISSUE TITLE
Code Signing and Update system

### ISSUE THREAD

**Issue by KorobkaVadim** [electron-userland/electron-builder#3428]
* **19.53.7**: 

* **Win32**: 

I have one appplication in production. Recently I bought code sign certificate and update all users to new version with code signing, I write:
"build": {
  "win": {
    "publisherName": "Some Inc.",
  }
}
This is typo, publisherName in my cert is Some Inc without dot. What do I can? For example, can I return changes?

**Comment by develar** [comment]
`publisherName` can be an array.

**Comment by KorobkaVadim** [comment]
@develar Please, read my qustion again. I deployed program with typo in publisherName. How do I update users? Only manual?

**Comment by develar** [comment]
I think so. No other variants.

**Comment by KorobkaVadim** [comment]
@develar In connection with the problem above, I am going to revoke the old certificate, will there be any problems associated with this from current users?

**Comment by KorobkaVadim** [comment]
I want revoke cert with publisherName: "Some Inc" and publish "Some Inc.". Win32.
