### ISSUE TITLE
Is it possible to change the name of an existing app?

### ISSUE THREAD

**Issue by guanxun14** [electron-userland/electron-builder#3429]
Hey @develar, thanks for your work on this repo! Couldn't find any existing issues about this, sorry to bother you with these questions.

I want to change the name of my app (as it appears to users); will changing `productName` in `package.json` be sufficient to change this?

Additionally, might I face any issues with Auto Update for existing users of my app (on Windows and macOS) if I do so?

**Comment by develar** [comment]
Yes, you can change `productName` and it will not affect auto-update. I am not sure 100% if you use Squirrel.Windows instead of NSIS, but should be ok.

**Comment by develar** [comment]
Please note — recommended to set productName in electron-builder config, and not in root of package.json because otherwise Electron will use product name as path to app data.

**Comment by develar** [comment]
https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname

https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by develar** [comment]
@guanxun14 Yes. But please note that it is opensource project and I cannot guarantee that everything will work as expected. Just try.

**Comment by guanxun14** [comment]
Will do! Trying to make future plans for my app, so I thought to ask this in advance. 

Thank you again for your time, I really appreciate it! :)

**Comment by mqliutie** [comment]
If I have an app named `A.app` in `/Application` directroy, Now I want to change it to `B.app`,  I set productName to `B`, App can run perfectly but in `/Application` the app name is still `A`.  Is there a way to change it?

**Comment by thirteen13Floor** [comment]
I have an app named A.app in /Application directroy

Now I want to change it to B.app

I have set productName to B

The app can run perfectly

But in /Application the app name is still A.

Is there a way to change it?
