### ISSUE TITLE
Cannot commit changes in private fork

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#343]
I have prepared a PR for the project but I cannot commit my changes due to the following error 
git commit -m "feat: accept multiple default app dirs"
Aborting commit due to empty commit message.
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `validate-commit-msg`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 

Cannot figure what causes this. @develar Any suggestions?
Thanks

**Comment by develar** [comment]
Your commit message is valid. Please try to run `node ./node_modules/.bin/validate-commit-msg`.

**Comment by develar** [comment]
If doesn't help, remove `unlink .git/hooks/commit-msg`. And run `node ./node_modules/.bin/validate-commit-msg` again. If error will be not fixed after that, well, unlink again `node ./node_modules/.bin/validate-commit-msg` to disable commit message validation.

**Comment by demetris-manikas** [comment]
.git/hooks/commit-msg does not exist on my machine. I have the pre-commit enabled thow.

**Comment by demetris-manikas** [comment]
I still haven't managed to commit properly.

**Comment by demetris-manikas** [comment]
Should there be a .git/hooks/commit-msg or not?

**Comment by develar** [comment]
Please run `node ./node_modules/pre-commit/install.js`

**Comment by demetris-manikas** [comment]
I solved the problem by copying ./git/hooks/pre-commit to ./git/hooks/commit-msg and then renaming ./git/hooks/pre-commit. Looks like pre-commit cannot check the message since it has not been entered yet

**Comment by demetris-manikas** [comment]
https://www.npmjs.com/package/pre-git looks as a more complete tool to handle git hooks. Should 
I take a look at it for usage in this project?

**Comment by demetris-manikas** [comment]
Well, it was pretty straightforward.

**Comment by develar** [comment]
@demetris-manikas Please get rid of pre-commit and use pre-git. It is better because addition run task is not required.
