### ISSUE TITLE
NSIS uninstall fails for standard (non-admin) user?

### ISSUE THREAD

**Issue by daldridge-cs** [electron-userland/electron-builder#3430]
* **Version**: 20.28.3

* **Target**: NSIS (Win32, x64)

I have an application that generates an NSIS installer using these `package.json` settings:
```
  "build": {
    ...
    "win": {
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "oneClick": false,
      "perMachine": false
    },
    ...
  },
```

This assisted installer successfully installs when selecting per-user ("Just for me (<username>" on the first dialog).  As expected, it does not request admin credentials.  However, when attempting to *un*install, it asks for admin credentials, starts the uninstall (I see the first "Uninstalling <product>..." dialog or whatever it says...) -- but then nothing happens and the application remains installed in the per-user location.

This is all happening under a "standard user" (non-admin) account.  There are no issues when running the install and uninstall with an admin user.

Any ideas?

**Comment by develar** [comment]
It is bug. Honestly, I cannot say when it will be fixed. Help wanted.

**Comment by pcad** [comment]
I've observed the same issue.  This also happens when I run `electron-boilerplate`'s `release` command and the produced exe.

**Comment by Rudedog9d** [comment]
I've noticed this when using `{"oneClick": true}` aswell. Something interesting on **Windows 10** I noticed though:

When uninstalling with **Programs and Features**, it doesn't prompt for admin

![image](https://user-images.githubusercontent.com/15984156/53202429-6c7e0000-35f4-11e9-9690-cfc48e776ca5.png)


But When uninstalling with **Apps and Features**, it _does_ prompt for admin.

![image](https://user-images.githubusercontent.com/15984156/53202464-84ee1a80-35f4-11e9-987c-6d81af162511.png)

(Pictures for clarity, but no electron app included for privacy)

**Comment by bsmoran620** [comment]
Same issue with oneClick installer:
- Version: 20.39.0

- Settings:
`"nsis": {
      "deleteAppDataOnUninstall": true,
      "oneClick": true,
      "perMachine": false
}`

Installs fine on Windows 10 for a non-admin user. Uninstall script runs (confirmed via MessageBox), but nothing is removed (files, shortcuts, etc.). Tried 'customUnInstall' macro with `SetShellVarContext current` but still no luck. 

Anyone make progress on this?

**Comment by enggjiten** [comment]
I tried with  customUnInstall as well. Just remove the registry. Files and folder are not deleted.

**Comment by Mr1008** [comment]
Any update about this guys? This is quite annoying to be honest

**Comment by silviosan** [comment]
Are there any news regarding this Problem? A fix would be really appreciated!

**Comment by kane41** [comment]
I have to solve this problem.

**Comment by amirburbea** [comment]
This still plagues electron-builder.

I did notice that when I get the UAC prompt from windows, it is to `"%INSTALL_PATH%\uninstall my-app.exe" /currentuser`.  At first I thought it was this `/currentuser` thing, but when I just manually run the uninstaller (with or without the `/currentuser` argument) there is no UAC prompt.

**Comment by Mr1008** [comment]
I am afraid that this is just a standard behavior of UWP Apps & Features panel in Windows 10. It prompts UAC for each non-UWP/Appx app.

**Comment by amirburbea** [comment]
Can someone from the project authors file a bug/feedback with Microsoft?
It's possible that they'll take that feedback and address it.

If there's a link to a public page with the bug on Microsoft's site I'm
sure a number of us would be happy to upvote the issue.

**Comment by gottscj** [comment]
Is there a potential workaround?

Thanks!

**Comment by amirburbea** [comment]
Just tell them to uninstall via

start/run/appwiz.cpl

Then it does not prompt for uac

**Comment by fogelton** [comment]
It is a windows bug, I am using nsis for my own installer
