### ISSUE TITLE
Tag repository for electron-updater npm package versions

### ISSUE THREAD

**Issue by neilrees** [electron-userland/electron-builder#3431]
The latest version of `electron-updater` is `3.1.5` - https://www.npmjs.com/package/electron-updater

The repository is tagged with the versions of `electron-builder`, latest version are e.g. `20.29.0` and `20.29.1`.

Is it possible to ascertain which commit in the repository a build of `electron-updater` corresponds to?  How to check whether a fix is present or not?

**Comment by develar** [comment]
electron-builder release notes contains something like 

> electron-updater 3.2.5 release.

or 

> electron-updater 3.2.4 pre-release.

**Comment by neilrees** [comment]
Thanks, however I can't see any release note mentioning the current latest version `3.1.5` released three days ago.

Last mention of `3.1.x` is in release `20.26.1` which is 
> electron-updater 3.1.1 pre-release

**Comment by develar** [comment]
Sorry, by mistake in release notes was referenced as 3.2.x, but actually it is 3.1.x

**Comment by neilrees** [comment]
👍 
However (sorry to go on about this!) the release note says:
> electron-updater: Fix grammar in notification message (#3410) (7953e56)

The change in https://github.com/electron-userland/electron-builder/commit/7953e56 does not appear to be in the `3.1.5` npm package.

(Hence the ask for a git tag :-) ) 

I did `npm view electron-updater dist.tarball` which returned `https://registry.npmjs.org/electron-updater/-/electron-updater-3.1.5.tgz` and the change isn't in that tarball.

**Comment by develar** [comment]
Boo... Yes, it makes sense to add tags for electron-updater to make clear.

Now tagged as `electron-updater-v3.1.6` and such tags will be used from now on.

3.1.6 released with  7953e56 change.
