### ISSUE TITLE
NSIS: Localize messages in include script

### ISSUE THREAD

**Issue by hoefling** [electron-userland/electron-builder#3432]
* **Version**: 20.28.1

* **Target**: `nsis`

I'm using `include` to include custom nsis script, reduced to:

```
!macro customInstall
    SetDetailsPrint textonly
    ; inform the user or he might think the installer is frozen
    DetailPrint "Doing some long running stuff, this might take some time"
    nsExec::Exec "$INSTDIR\myapp.exe /DOSTUFF"
!macroend
```

Is there a possibility to specify localizations for the custom message in `DetailPrint`? Looking at the source code, I see the `messages.yml` and the generation of `messages.nsh`, but unsre whether I can inject my own stuff into it.

**Comment by develar** [comment]
Please use http://nsis.sourceforge.net/Reference/LangString

**Comment by hoefling** [comment]
Tried that already, with no avail. When not loading language files (relying on the including script to do that), I get the (expected) error

```
warning 7025: "${LANG_RUSSIAN}" is not a valid language id, using language id 1031! (C:\path\to\build\installer.nsh:16)
Error output:
Error: warning treated as error

    at ChildProcess.childProcess.once.code (C:\path\to\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
```

When loading the language file explicitly:

```
LoadLanguageFile "${NSISDIR}\Contrib\Language files\Russian.nlf"
LangString msg ${LANG_RUSSIAN} "Some text"

!macro customInstall
    ...
!macroend
```

I get another error

```
Processing config: C:\Users\jenkins\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
Error: can't load same language file twice.
Error in macro MUI_LANGUAGEEX on macroline 13
Error in macro MUI_LANGUAGE on macroline 4
Error in macro addLangs on macroline 1
Error in script "<stdin>" on line 103 -- aborting creation process

    at ChildProcess.childProcess.once.code (C:\path\to\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
```

**Comment by develar** [comment]
yeach. it is the reason why here https://github.com/electron-userland/electron-builder/blob/c35b3150536be66a9e1c2aae75f7e8f7f610699d/packages/app-builder-lib/src/targets/nsis/nsisLang.ts#L84

> result.push(`LangString ${messageId} ${lcid[langWithRegion]} "${value.replace(/\n/g, "$\\r$\\n")}"`)

lcid is used https://github.com/electron-userland/electron-builder/blob/775c2553775c10b3c9b8ee6e86022b7f02aa8aa8/packages/builder-util/src/langs.ts#L25

You have two solutions:

1. use lcid
2. or add ability to provide custom files with translations, so, `nsisLang`logic will add your translations.

**Comment by hoefling** [comment]
Oh, I see. Makes sense now! Thank you for your help!

**Comment by develar** [comment]
You can probably get fatal warning if don't specify translation for all messages (as you can see, our generator simply uses en instead as fallback). So, if you will decide to use lcid and do not send us patch to support custom translations, maybe https://www.electron.build/configuration/nsis#NsisOptions-warningsAsErrors will be required to be set to `false`.

**Comment by hoefling** [comment]
Will be happy to help, especially that it looks like the large parts of the code for processing the `messages.yml` can be reused. Do you have any remarks/additions to the following approach:

1. Adapt the logic in `nsisLang.ts` to be able to write `customMessages.nsh` or `includeMessages.nsh` from passed path to YAML file
2. Add a new option `messages` to the `NsisOptions` interface (is the naming acceptable?)
3. In the `NsisTarget.computeCommonInstallerScriptHeader` method, if both files specified in `include` and `messages` options are present, invoke the generation of `customMessages.nsh` (I guess it wouldn't make much sense to include custom messages without including a custom script?)
4. Add two tests, for the case that both `include` and `messages` are set (the custom header file must be generated) and for the case that `include` is not set, but the `messages` are (no custom header file generated)
5. Enhance the [Custom NSIS Script](https://www.electron.build/configuration/nsis#custom-nsis-script) section with an example of message localization (custom messages file example + message usage in custom script)

**Comment by develar** [comment]
> I guess it wouldn't make much sense to include custom messages without including a custom script?

Yes, new option `messages` makes sense only if default is used (because no need for this for portable).

> Add a new option messages to the NsisOptions interface (is the naming acceptable?)

I would prefer `languageFiles`.

**Comment by develar** [comment]
> Add two tests

It maybe not easy, feel free to not waste ime and I will ad it.
