### ISSUE TITLE
How to customize Linux / Mac installers ?

### ISSUE THREAD

**Issue by Alin13** [electron-userland/electron-builder#3436]
I want to package the app for Linux (Ubuntu and maybe others too) and Mac. But when the application is installing I also need to run a script used to install some third party software.

For Windows (nsis) I know that there is a configuration: "include": "installer.nsh".

Is there something similar for Linux / Mac that I can use to do this ?

**Comment by develar** [comment]
For AppImage not possible.
For mac DMG not possible.

You can use alternative formats, but I just recommend you to install required software on first run.

**Comment by crazydevlegend** [comment]
@Alin13 can you please tell me how I can run a terminal on Windows after installing the app?
I have to change registry values after installing and I wonder I can implement this.
Can you please help me with this?
