### ISSUE TITLE
Build in a bash-like shell on Windows, sign as a separate step in Powershell?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#3437]
My current build setup uses a lot of bash commands which Powershell on Windows 7 doesn't support. Is there any way to build the project using my preferred terminal (babun) and sign it separately in Powershell afterwards?

**Comment by Slapbox** [comment]
Thanks @develar - Is there possibly an example you know of for how to sign the executable and installer this way? I've tried rewriting my build scripts using `gulp` for cross-platform use to avoid needing this, but frankly, Windows command line is terrible.

I know this is an advanced feature, but my use case is not that advanced, I would think? Surely not everyone is building for Windows on a Mac?

If not an example, is there any pointer in the right direction you could give me? I have no idea what Electron-Builder is doing under the hood to sign things on Windows. During a quick glance at the code, I only found the Mac signing related parts.

Thanks for any advice you might be able to give @develar

**Comment by develar** [comment]
> my use case is not that advanced, I would think

advanced :)

Link https://www.electron.build/configuration/win#how-do-delegate-code-signing contains example of JS file that you can use to implement your own code signing of windows binaries.

Problem — uninstaller created on the fly and signed, app exe signed, and then both are packed into installer that also signed. So, no way to sign it later. if you have custom sign logic, given example is the only known for me solution.

Feel free to describe your use cases and explain why default code sign is not suitable for you.

**Comment by Slapbox** [comment]
@develar it's the "` your custom code`" part that trips me up, but fortunately I won't be needing that.

Setting `win.publisherName` got me closer, so it's not that I can't use my usual terminal, just that I can't use `get-PfxData`.  I'd been hitting timestamp server issues which I thought were an extension of this problem, but I'm guessing that was just a transient problem with my default timestamp server, because I just got it to work now on the third try.

In case anyone needs a different timestamp server though in the future: https://github.com/electron-userland/electron-builder/issues/2795#issuecomment-381745045

Thanks for everything @develar!
