### ISSUE TITLE
Typo on 29.30.0 ? Was this supposed to be named 20.30.0?

### ISSUE THREAD

**Issue by dorian-coygo** [electron-userland/electron-builder#3439]
This may mess up some people's semver dependency package.

P.S. Thanks for all you do!

**Comment by develar** [comment]
Well, it is first (`0`) patch release for minor (`30`) version for `20` major version ;) No?

**Comment by develar** [comment]
Yes, it is typo.

**Comment by develar** [comment]
Thanks!
