### ISSUE TITLE
Force download regardless of version or channel

### ISSUE THREAD

**Issue by Hexellate** [electron-userland/electron-builder#3442]
* **Version**: 20.31.2

* **Target**: Windows (nsis)

I'm trying to set up auto update with Bintray, and because channels do not work with Bintray, I'm trying to emulate channels by using different repositories. The issue is that because technically the updater sees these as the same channel, I cannot seem to get the updater to downgrade the version even though allowDowngrade is set to true. When I check for update, it returns the update info correctly, however if I then call the downloadUpdate method, the program returns the error `Unhandled rejection Error: Please check update first`. Is there any way to force this download to start?

**Comment by develar** [comment]
Are you really want to use unreailible bintray?

**Comment by Hexellate** [comment]
I initially tried to use channels with bintray, however it seems that it disregards whatever channel I set and always uses the "latest" channel. Additionally, if I set the channel in the version field of package (e.g. 0.1.2-alpha), the yml files it produces will always end with "_latest" (e.g. 0.1.2-alpha will become 0.1.2-alpha_latest.yml).

**Comment by Hexellate** [comment]
Also I'm using bintray because Amazon S3 and DigitalOcean Spaces both cost money, GitHub doesn't support having 3 channels, and I don't have a generic server to use.

**Comment by oriSomething** [comment]
Allow downgrade would really be helpful if supported for "latest" channel also.

Is there is a plan to support it, if I'll make a PR, will it be considered to be merge?
