### ISSUE TITLE
Contributing: Windows build fails.

### ISSUE THREAD

**Issue by dscalzi** [electron-userland/electron-builder#3445]
Hey, I'm trying to build the source on windows, however I am getting an error. The issue is exactly the same one which causes the AppVeyor builds to fail.

https://ci.appveyor.com/project/stefanjudis/electron-builder/builds/19997577

`yarn` succeeds, but `yarn compile` failes.

**Cannot find module 'builder-util-runtime'.**

Any insight would be appreciated.

Edit:
[First build with this issue.](https://ci.appveyor.com/project/stefanjudis/electron-builder/builds/19938711) https://github.com/electron-userland/electron-builder/commit/90eb8556ff8093905f3be7618391a79548479894
[Last 'working' build.](https://ci.appveyor.com/project/stefanjudis/electron-builder/builds/19933225) https://github.com/electron-userland/electron-builder/commit/0cc7a0451023186e0d7502676057d13dfa4dbfdf

Edit 2:
Problematic Commit: https://github.com/electron-userland/electron-builder/commit/bcf094791f575ea4d9c4e110869a1ea6dee3d288 (likely)

**Comment by develar** [comment]
Indeed... I will fix it today (since I am on macOS, not easy for me to load windows and investigate).

**Comment by dscalzi** [comment]
The issue was in ts-babel. I have submitted a PR which resolves the issue https://github.com/develar/ts-babel/pull/14

**Comment by dscalzi** [comment]
@develar When you pushed 6.1.1 you forgot to compile it. The module still has the old output on npm, hence why AppVeyor still fails. Compiling it locally, it works.

Could you update the release 😅
