### ISSUE TITLE
Provide a way to trust a self-signed certificate or custom CA with GenericHTTPServer of electron-updater

### ISSUE THREAD

**Issue by burnpanck** [electron-userland/electron-builder#3453]
* **Version**: Note, these are not the most recent versions because of a current issue with auto-update on macOS
   - electron-builder: 20.22.0
   - electron-updater: 3.0.3
* **Target**: macOS, linux, windows

See also my stack-overflow question: https://stackoverflow.com/questions/53168332/trust-custom-ca-in-electron-builders-autoupdater-without-importing-to-system

**Comment by develar** [comment]
Duplicates #2561

**Comment by burnpanck** [comment]
Hm, I have seen that other issue, but it doesn't help in my case... That other issue was solved by using a self-signed certificate, but no part of the whole thread shows *how* electron-builder is made accept that certificate. Particularly, our server exposes a certificate that is not directly self-signed, but signed by a self-signed custom certificate authority. Therefore, I need a way to influence the list of accepted certificate authorities, such as the `ca` option of Node.js' [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) (used by Node.js' `https.request`). But electron-updater uses the `electron.net` API, for which I do not know how to set the CA list. Furthermore, from reading the source, I don't think there is a way to pass options to the requests internally made by electron-updater.

**Comment by develar** [comment]
@burnpanck Do you mean that handler for https://electronjs.org/docs/api/app#event-certificate-error doesn't work for you?

**Comment by burnpanck** [comment]
It does not - in my case, the `certificate-error` never gets emitted. There is one comment on the stack-overflow answer mentioned in #2561 (https://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app/46789486#46789486) which suggests that the method using `certificate-error` only works from the render process.

**Comment by develar** [comment]
@burnpanck Solution found — https://electronjs.org/docs/api/session#sessetcertificateverifyprocproc 

New electron-updater version will be published soon.

**Comment by develar** [comment]
`netSession`

**Comment by baptx** [comment]
As a user, I fixed the issue with `--ignore-certificate-errors` mentioned here:
https://askubuntu.com/questions/1099613/install-ssl-certificate-for-electron-application
