### ISSUE TITLE
Proposed documentation improvements

### ISSUE THREAD

**Issue by Lange** [electron-userland/electron-builder#346]
_As mentioned in [this comment](https://github.com/electron-userland/electron-builder/issues/340#issuecomment-212444753) on Issue #340._

I've just [published my first electron-builder application](https://github.com/nodecg/dashboard/releases/tag/v1.0.0), and would like to improve the docs in areas where I had trouble. Specifically, I propose the following changes:

- Add docs about implementing autoUpdater.
 - I did not initially realize that I needed to have code that set the update feed URL and handled update events.
- Add more prominent mentions of the [`docs`](https://github.com/electron-userland/electron-builder/tree/master/docs) folder, specifically [`Publishing Artifacts.md`](https://github.com/electron-userland/electron-builder/blob/master/docs/Publishing%20Artifacts.md).
 - I completely missed this folder at first, and could have saved some time if its contents were more prominently linked to from the main README.
- On Windows, if your `CSC_LINK` has an `&` character in it, it must be wrapped in doublequotes (`"`). Singlequotes (`'`) will not work, nor will not using any quotes.
- Add docs explaining that the OSX DMG installer window size is based on the size of `background.png`.
 - I spent a few hours confused, trying to figure out what the resolution of the DMG installer would be so I would know what size to make my `background.png`. It took a while for me to realize that the resolution of the DMG would be based on the size of my `background.png`.
- More clearly document the recommended draft/release workflow.
 - As discussed in [this comment](https://github.com/electron-userland/electron-builder/issues/340#issuecomment-212426562) on Issue #340.

If these seem like good proposals, I will begin work on a pull request.

Further suggestions are welcome.

**Comment by develar** [comment]
> Add docs about implementing autoUpdater.

Already added. See https://github.com/electron-userland/electron-builder#auto-update "your app must handle Squirrel.Windows events" And in the https://github.com/electron/windows-installer#handling-squirrel-events

But yes – it is not properly highlighted in the our doc/README. 👍 

> Add more prominent mentions of the docs folder

It is only for developers, [wiki](https://github.com/electron-userland/electron-builder/wiki) for end users. "Publishing artifacts to GitHub Releases" in the readme points to wiki.

But yes – may be we should mention wiki explicitly. 👍 

> On Windows, if your CSC_LINK has an & character in it, it must be wrapped in doublequotes ("). 

👍 

> Add docs explaining that the OSX DMG installer window size is based on the size of

👍 

> More clearly document the recommended draft/release workflow.

👍 + here we should fix/improve some things in the electron-builder.

**Comment by develar** [comment]
Forget to mention — wiki is not edited directly — to edit, edit files in the `docs`  directory. And then it is synced using git subtree merge (once PR is accepted/new version published).

**Comment by Lange** [comment]
Got it. I will begin work on this today.

**Comment by daviseford** [comment]
Sup Lange! Funny to see you here (this is davis aka woot)

**Comment by Lange** [comment]
Oh haha, hey @daviseford.

@develar, do you have a preference for how I should structure these commits? Should each change be its own commit, or do you plan to squash and merge?

**Comment by develar** [comment]
@Lange As you want. No strict rules here. The only rule — don't use rebase once PR is created. Maybe I will squash, maybe not, depends on number of your "respond to review" commits :)

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
