### ISSUE TITLE
Auto update with admin rights

### ISSUE THREAD

**Issue by flabbyThoroughbred** [electron-userland/electron-builder#3470]
Hi,

I'm running into problems trying to auto update my app. My intention is to install the app per machine with a start menu shortcut but no dashboard shortcut. Initial installation is done via pdq deployment as admin.
However subsequent auto updates prompt the user to enter a login and password to proceed. Is there a way to circumvent this step for the update to be as invisible as possible?

My module versions are:
`electron: 1.8.5`
`electron-builder: 20.29.0`
`electron-updater: 3.1.3`

Here are my nsis options:
`      "oneClick": true,`
`      "perMachine": true,`
 `     "createStartMenuShortcut": true,`
`      "createDesktopShortcut": false`

Thanks!
-Mark

**Comment by develar** [comment]
No, if app installed per machine, it requires admin rights to be updated because user doesn’t have write access. So, UAC Dialog is shown.
