### ISSUE TITLE
Electron-Updater differential update fails with operation overlaps previous operation

### ISSUE THREAD

**Issue by retina-design** [electron-userland/electron-builder#3485]
* **electron-builder**:  Version 20.36.2
* **electron-updater**: Version 4.0.4
* **Target**: nsis-web
* **System**: Windows

The AutoUpdater gives me this error...
`[2018-11-18 17:01:42.356] [error] Cannot download differentially, fallback to full download: Error: operation (block index: 23902, checksum: Vx/fVEzWD3gMPbOsQJC+QZlJ, kind: COPY) overlaps previous operation (checksum: Vx/fVEzWD3gMPbOsQJC+QZlJ):
abs: 7267809 until 500356092 and 500206446 until 500238540`

... using this configuration
```JSON
"build": {
    "appId": "<appId>",
    "nsisWeb": {
      "oneClick": true,
      "perMachine": false,
      "differentialPackage": true
    },
    "publish": {
      "provider": "generic",
      "url": "https://<username>:<password>@<URL>"
    },
    "win": {
      "icon": "./lib/resources/icons/icon.ico",
      "target": "nsis-web"
    },
    "files": [
      "*.js",
      "build/**/*",
      "node_modules/**/*"
    ]
  },
```
The connection to the server seems to work as the updater can find the new version and successfully falls back to the full download. The _package.7z_ exists in the {User}/AppData/Local/{name}-updater.

Thanks in advance.

**Comment by develar** [comment]
Just to make clear — update is working, but instead delta-, full- download is performed.

**Comment by sandeep1995** [comment]
Facing exactly the same issue for `nsis` target. I also enabled my generic server to accept byte ranges.

**Comment by sandeep1995** [comment]
> Also got this error with `nsis` target
@alxmiron Are you able to solve? @develar Is there any way out?

**Comment by alxmiron** [comment]
No. I just get full download each time instead of differential

**Comment by sandeep1995** [comment]
Yeah, I am also facing the same. I want diff download. Any luck on these? @alxmiron

**Comment by zhaoterryy** [comment]
Please try using 20.34.0 for now.

**Comment by sandeep1995** [comment]
> Please try using 20.34.0 for now.

@zhaoterryy  Downgraded to 20.34.0 Still facing the same error. I am building for only `nsis`.
I am using minio server as a local s3 setup.

Here is the log

```
[2018-11-29 03:09:25.501] [info] Found version 5.0.8 (url: App-Name Setup 5.0.8.exe)
[2018-11-29 03:09:25.502] [info] Downloading update from App-Name Setup 5.0.8.exe
[2018-11-29 03:09:25.515] [error] updaterCacheDirName is not specified in app-update.yml Was app build using at least electron-builder 20.34.0?
[2018-11-29 03:09:25.529] [info] No cached update info available
[2018-11-29 03:09:25.535] [info] Download block maps (old: "http://192.168.43.222:5000/test-data/App-Name%20Setup%201.0.8.exe.blockmap", new: http://192.168.43.222:5000/test-data/App-Name%20Setup%205.0.8.exe.blockmap)
[2018-11-29 03:09:25.657] [error] Cannot download differentially, fallback to full download: Error: operation (block index: 2676, checksum: sClKbnS13fglyGVAr0iRCnBU, kind: COPY) overlaps previous operation (checksum: sClKbnS13fglyGVAr0iRCnBU):
abs: 46508973 until 56008949 and 55999891 until 56008949
rel: 0 until 9499976 and 9490918 until 9499976
    at validateAndAdd (C:\Program Files\App-Name\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\downloadPlanBuilder.ts:99:13)
    at computeOperations (C:\Program Files\App-Name\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\downloadPlanBuilder.ts:83:9)
    at GenericDifferentialDownloader.doDownload (C:\Program Files\App-Name\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:52:24)
    at GenericDifferentialDownloader.download (C:\Program Files\App-Name\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\GenericDifferentialDownloader.ts:6:17)
    at C:\Program Files\App-Name\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:172:10
    at Generator.next (<anonymous>)
```

**Comment by zhaoterryy** [comment]
Downgrade electron-updater as well, to 3.2.3.

**Comment by develar** [comment]
And no one still answered me... "Please provide links to old and new executables and blockmaps." Now I have time to investigate issue, but I don't have test data....

**Comment by sandeep1995** [comment]
@develar I would like to really help you out in this regard. But as our repository is closed source, I can't share the links. 

Is there any other way to provide you the same?

**Comment by develar** [comment]
Validation disabled for now, because assert message is clear that probably validation is too strict. Please try electron-updater 4.0.5.

@zhaoterryy Thanks for sorting issues out — participation of such VIP users like you, increase issue priority, nearly as donation :) 

> Is there any other way to provide you the same?

@sandeep1995 Is it possible to provide old and new blockmap files? These files contain only blake2 hashes and sizes.

**Comment by LurkingOctopus** [comment]
Was facing the same error for a while and finally found the right combination for my app! Hope this helps anyone still searching:

electron: 4.0.6
electron-updater: 3.2.3
electron-builder: 20.34.0

**Comment by gimdongwoo** [comment]
Please reopen this issue.

**Comment by liflovs** [comment]
Still a problem
"electron-builder": "^21.2.0",
"electron-updater": "^4.1.2",

**Comment by 8balloon** [comment]
Thank you @LurkingOctopus for your answer.

If anyone doesn't want to update electron itself, matching up the following dep versions may be sufficient:

```
electron-updater: 3.2.3
electron-builder: 20.34.0
```

(This worked for me)

**Comment by doyle-mark** [comment]
Still a problem

**Comment by doyle-mark** [comment]
Experiencing the same issue. Details attached (https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/577)

**Comment by yanlee26** [comment]
same issue , please reopen 
```
updaterCacheDirName is not specified in app-update.yml Was app build using at least electron-builder 20.34.0?
```
-------deps:

```
  "devDependencies": {
    "electron": "^8.2.3",
    "electron-builder": "^22.5.1"
  },
  "dependencies": {
    "electron-log": "^4.1.1",
    "electron-updater": "^4.2.5"
  }


```

**Comment by harshitsilly** [comment]
@yanlee26 Hi, try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/).. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.

**Comment by sandeep1995** [comment]
https://github.com/electron-delta/electron-delta it uses binary diffing for updates.
