### ISSUE TITLE
AppImages missing magic bytes.

### ISSUE THREAD

**Issue by azubieta** [electron-userland/electron-builder#3486]
We have found several AppImages (listed [here](https://github.com/AppImage/AppImageKit/issues/822) ) that doesn't properly follow the [AppImageSpec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format). Mainly the one "SHOULD contain the magic hex 0x414901 at offset 8 (why?)" for type 2 AppImages.

This is required to difference a typ2 AppImage  from a regular executable.

**Comment by develar** [comment]
I am sure that these apps were built using old version of electron-builder.

**Comment by azubieta** [comment]
Could you provide a link to a newly built app to test and close the issue in both projects?
