### ISSUE TITLE
How can I identify programmatically if the program is running from a package?

### ISSUE THREAD

**Issue by burnpanck** [electron-userland/electron-builder#3489]
Our app supports two methods of running:
- From the source directory, e.g. using `yarn start`
- From a distributable package build using `electron-builder`
However, those two methods differ in a number of details, such as file-paths, CLI arguments, etc.
Is there an easy way to identify (from JS in the main process of the electron app), if the app is running from a distributable package? The solution should work on all three platforms, macOS, linux and windows.

**Comment by develar** [comment]
https://github.com/electron/electron/blob/master/docs/api/app.md#appispackaged

**Comment by develar** [comment]
https://github.com/sindresorhus/electron-is-dev
