### ISSUE TITLE
Can't Build for Windows

### ISSUE THREAD

**Issue by loreberti89** [electron-userland/electron-builder#3492]
version of electron-builder: 20.36.2
version of electron-updater :  4.0.4
Node: 8.12.0
Electron: 3.0.10
webpack:  4.25.1

* **Target**: 
```
"win": {
      "target": [
        "nsis-web"
      ],
      "icon": "build/icons/icon.ico"
    },
    "nsis": {
      "artifactName": "${productName}-Setup-${version}.${ext}",
      "oneClick": true,
      "perMachine": true,
      "allowToChangeInstallationDirectory": false,
      "runAfterFinish": true,
      "deleteAppDataOnUninstall": false,
      "differentialPackage": true
    }
```

When I try to build I receive:

> Error: C:\Users\Lorenzo\Documents\App\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
>     at ChildProcess.childProcess.once.code (C:\Users\Lorenzo\Documents\App\node_modules\builder-util\src\util.ts:244:14)
>     at Object.onceWrapper (events.js:317:30)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:915:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> From previous event:
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.signAndEditResources (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\winPackager.ts:251:158)
>     at _bluebirdLst.default.map.file (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\winPackager.ts:354:21)
>     at go$readdir$cb (C:\Users\Lorenzo\Documents\App\node_modules\graceful-fs\graceful-fs.js:162:14)
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\winPackager.ts:352:27
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.signApp (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\winPackager.ts:346:73)
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\platformPackager.ts:250:16
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.doPack (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\platformPackager.ts:113:16
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.pack (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:406:24
>     at Generator.next (<anonymous>)
>     at xfs.stat (C:\Users\Lorenzo\Documents\App\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
>     at C:\Users\Lorenzo\Documents\App\node_modules\graceful-fs\polyfills.js:285:20
>     at FSReqWrap.oncomplete (fs.js:153:5)
> From previous event:
>     at Packager.doBuild (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:372:24)
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:342:57
>     at Generator.next (<anonymous>)
>     at C:\Users\Lorenzo\Documents\App\node_modules\graceful-fs\graceful-fs.js:111:16
>     at C:\Users\Lorenzo\Documents\App\node_modules\graceful-fs\graceful-fs.js:45:10
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at Packager._build (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:311:133)
>     at C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:307:23
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at Packager.build (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\packager.ts:264:14)
>     at build (C:\Users\Lorenzo\Documents\App\node_modules\app-builder-lib\src\index.ts:59:28)
>     at build (C:\Users\Lorenzo\Documents\App\node_modules\electron-builder\src\builder.ts:227:10)
>     at then (C:\Users\Lorenzo\Documents\App\node_modules\electron-builder\src\cli\cli.ts:46:19)
>     at <anonymous>
> error Command failed with exit code 1.

I've tried to download a quick start electron:

So I have this package.json

```
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^3.0.7",
    "electron-builder": "^20.36.2"
  },
  "build": {
    "appId": "test.id",
    "win": {

      "icon": "build/icons/icon.ico"
    }
  }
}
```
but when I launch yarn dist :

> yarn run v1.2.1
> $ electron-builder
>   • electron-builder version=20.36.2
>   • loaded configuration file=package.json ("build" field)
>   • no native production dependencies
>   • packaging       platform=win32 arch=x64 electron=3.0.10 appOutDir=dist\win-unpacked
> [31m  ⨯[0m Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z: proxyconnect tcp: dial tcp :0: connectex: Indirizzo richiesto non valido nel proprio contesto.
> github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
> 	/Users/develar/Documents/app-builder/pkg/download/downloader.go:167
> github.com/develar/app-builder/pkg/download.(*Downloader).follow
> 	/Users/develar/Documents/app-builder/pkg/download/downloader.go:200
> github.com/develar/app-builder/pkg/download.(*Downloader).Download
> 	/Users/develar/Documents/app-builder/pkg/download/downloader.go:75
> github.com/develar/app-builder/pkg/download.DownloadArtifact
> 	/Users/develar/Documents/app-builder/pkg/download/artifactDownloader.go:105
> github.com/develar/app-builder/pkg/download.downloadFromGithub
> 	/Users/develar/Documents/app-builder/pkg/download/tool.go:62
> github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
> 	/Users/develar/Documents/app-builder/pkg/download/tool.go:57
> github.com/develar/app-builder/pkg/download.DownloadArtifact
> 	/Users/develar/Documents/app-builder/pkg/download/artifactDownloader.go:68
> github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
> 	/Users/develar/Documents/app-builder/pkg/download/artifactDownloader.go:26
> github.com/alecthomas/kingpin.(*actionMixin).applyActions
> 	/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
> github.com/alecthomas/kingpin.(*Application).applyActions
> 	/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
> github.com/alecthomas/kingpin.(*Application).execute
> 	/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
> github.com/alecthomas/kingpin.(*Application).Parse
> 	/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
> main.main
> 	/Users/develar/Documents/app-builder/main.go:73
> runtime.main
> 	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201
> runtime.goexit
> 	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333

> Error: C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-bin\win\x64\app-builder.exe exited with code 1
>     at ChildProcess.childProcess.once.code (C:\Users\Lorenzo\Documents\testElect
> ron\electron-quick-start\node_modules\builder-util\src\util.ts:244:14)
>     at Object.onceWrapper (events.js:317:30)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:915:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> From previous event:
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.signAndEditResources (C:\Users\Lorenzo\Documents\testElectron
> \electron-quick-start\node_modules\app-builder-lib\src\winPackager.ts:251:158)
>     at _bluebirdLst.default.map.file (C:\Users\Lorenzo\Documents\testElectron\el
> ectron-quick-start\node_modules\app-builder-lib\src\winPackager.ts:354:21)
>     at go$readdir$cb (C:\Users\Lorenzo\Documents\testElectron\electron-quick-sta
> rt\node_modules\graceful-fs\graceful-fs.js:162:14)
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\winPackager.ts:352:27
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.signApp (C:\Users\Lorenzo\Documents\testElectron\electron-qui
> ck-start\node_modules\app-builder-lib\src\winPackager.ts:346:73)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\platformPackager.ts:250:16
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.doPack (C:\Users\Lorenzo\Documents\testElectron\electron-quic
> k-start\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\platformPackager.ts:113:16
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.pack (C:\Users\Lorenzo\Documents\testElectron\electron-quick-
> start\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\packager.ts:406:24
>     at Generator.next (<anonymous>)
>     at xfs.stat (C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\no
> de_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \graceful-fs\polyfills.js:285:20
>     at FSReqWrap.oncomplete (fs.js:153:5)
> From previous event:
>     at Packager.doBuild (C:\Users\Lorenzo\Documents\testElectron\electron-quick-
> start\node_modules\app-builder-lib\src\packager.ts:372:24)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\packager.ts:342:57
>     at Generator.next (<anonymous>)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \graceful-fs\graceful-fs.js:111:16
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \graceful-fs\graceful-fs.js:45:10
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at Packager._build (C:\Users\Lorenzo\Documents\testElectron\electron-quick-s
> tart\node_modules\app-builder-lib\src\packager.ts:311:133)
>     at C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_modules
> \app-builder-lib\src\packager.ts:307:23
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at Packager.build (C:\Users\Lorenzo\Documents\testElectron\electron-quick-st
> art\node_modules\app-builder-lib\src\packager.ts:264:14)
>     at build (C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_
> modules\app-builder-lib\src\index.ts:59:28)
>     at build (C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_
> modules\electron-builder\src\builder.ts:227:10)
>     at then (C:\Users\Lorenzo\Documents\testElectron\electron-quick-start\node_m
> odules\electron-builder\src\cli\cli.ts:46:19)
>     at <anonymous>
> error Command failed with exit code 1.

**Comment by mayur5478** [comment]
+ 1 not able to build on windows
Error: B:\recorder-to-test-720p not a file
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\codeSign\macCodeSign.ts:128:11
    at Generator.next (<anonymous>)
    at B:\recorder-to-test-720p\node_modules\fs-extra-p\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at _downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:268:31)
    at downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:219:31)
    at Lazy.WinPackager.cscInfo (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:61:12)
    at Lazy.get value [as value] (B:\recorder-to-test-720p\node_modules\lazy-val\src\main.ts:18:23)
    at Lazy.<anonymous> (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:88:40)
    at Generator.next (<anonymous>)
From previous event:

**Comment by loreberti89** [comment]
I Solved in this way:

Put package from github manually  in folder:

> C:\Users\user\AppData\Local\electron-builder\cache

Remove node modules and reinstall with yarn.

**Comment by mayur5478** [comment]
By package what do you mean?

**Comment by mayur5478** [comment]
Cannot find module 'C:\Users\Mayur\AppData\Roaming\npm\node_modules\electron-builder\out\cli\cli.js' gives me this error when I removed electron-builder

**Comment by loreberti89** [comment]
in my case , I had problem with:

> Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z

try to delete all node_modules, and reinstall all packages.

**Comment by mayur5478** [comment]
Are you saying that I should delete all the global packages as well?

**Comment by loreberti89** [comment]
no, node modules in your project.
and then try to install with yarn.
Be careful to have in your package.json all the dipendencies like:

> "electron": "3.0.7",
> "electron-builder": "^20.34.0",

And the others that you need.

**Comment by mayur5478** [comment]
cool will try and reply back. Thanks for your help.

**Comment by mayur5478** [comment]
in my case , I had problem with:

Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z


So did you download a different version and did it solve your problem?

**Comment by mayur5478** [comment]
That error still persists ...not able to build on windows +1
Error: B:\recorder-to-test-720p not a file
at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\codeSign\macCodeSign.ts:128:11
at Generator.next ()
at B:\recorder-to-test-720p\node_modules\fs-extra-p\node_modules\graceful-fs\polyfills.js:285:20
at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
at _downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:268:31)
at downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:219:31)
at Lazy.WinPackager.cscInfo (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:61:12)
at Lazy.get value [as value] (B:\recorder-to-test-720p\node_modules\lazy-val\src\main.ts:18:23)
at Lazy. (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:88:40)
at Generator.next ()
From previous event:


This is my package.json
{
  "name": "Hifi_recorder",
  "version": "1.0.7",
  "description": "An elegant video and screen recorder",
  "main": "main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron . --disable-gpu",
    "pack": "build --dir",
    "dist": "build"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Screen recorder",
    "Camera recorder",
    "Video recorder",
    "desktop application"
  ],
  "author": "HiFiTechnologySolutions",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron-builder": "^20.36.2"
  },
  "build": {
    "appId": "HiFi_recorder",
    "publish": [
      {
        "provider": "generic",
        "url": "http://13.58.84.186/HiFi_recorder"
      }
    ],
    "win": {
      "icon": "assets/images/icon.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false
    }
  },
  "dependencies": {
    "electron-json-storage": "^4.1.4",
    "electron-updater": "^4.0.4",
    "sweetalert2": "^7.29.1"
  },
  "iohook": {
    "targets": [
      "node-51",
      "electron-53"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
}

**Comment by rburmeister** [comment]
> in my case , I had problem with:
> 
> > Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
> 
> try to delete all node_modules, and reinstall all packages.

What did you do to fix the package issue? I'm running into the same problem. Thanks!
