### ISSUE TITLE
Support macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by HaNdTriX** [electron-userland/electron-builder#3496]
* **Version**:  v3.0.10

* **Target**: macOS Mojave v10.x

In order to fully support macOS Mojaves new darkMode we need to set the following in value in the apps `Info.plist`.

```xml
<plist>
<dict>
  ...
  <key>NSRequiresAquaSystemAppearance</key>
  <false />
  ...
</dict>
</plist>
```

For more infos check out the electron guide on this topic: [Electron Guide/Dark Mode](https://electronjs.org/docs/tutorial/mojave-dark-mode-guide)

**Comment by develar** [comment]
Fixed in upcoming 20.37.0
