### ISSUE TITLE
electron-auto-update not working with S3

### ISSUE THREAD

**Issue by sourabhChourasiya** [electron-userland/electron-builder#3498]
* **Version**: 
    "electron": "^3.0.6",
    "electron-updater": "^4.0.4",
    "electron-builder": "^20.28.4",

* **Target**: 
    "mac": {
      "target": [
        "dmg",
        "zip"
      ],
    },

Hello,

I am working on electron auto update with s3. I followed the docs and implemented the same. I manually uploaded the required files like dmg, zip and latest.yml inside a folder on s3 bucket. However, when I start the app, it states no updates available. Do I need to setup something on S3 to accept request being made? pulling my hair into need, Any help would be appreciated.

Thanks

below is the configuration
    ```"publish": {
      "provider": "generic",
      "url": "https://<-cdn url->/folder1/folder2",
      "publishAutoUpdate": true,
      "channel": "latest"
    },```

**Comment by dariocravero** [comment]
@sourabhChourasiya does this help https://github.com/electron-userland/electron-builder/issues/1618#issuecomment-442206418?

**Comment by sourabhChourasiya** [comment]
@dariocravero Thanks for the #1618 reference, this worked. Also `build --publish always` is there in my code, There was some permission issue on the bucket, I resolved that issue. Now uploading the dmg, zip is working fine.

Thanks.
