### ISSUE TITLE
this.app.whenReady is not a function when running electron-updater

### ISSUE THREAD

**Issue by jetlej** [electron-userland/electron-builder#3505]
* **Version**: 20.36.2

* **electron-updater:** 4.0.4

* **Target**: mac + web

I'm trying to use electron-updater, but I get this error: 

```
TypeError: this.app.whenReady is not a function
at ElectronAppAdapter.whenReady (/Users/jetlej/Projects/Task Slayer/code/node_modules/electron-updater/src/ElectronAppAdapter.ts:9:21)
```

Comes from this code: 

```
app.on('ready', () => {
  autoUpdater.checkForUpdates()
})
```

**Comment by zhaoterryy** [comment]
What Electron version are you running?

**Comment by zhaoterryy** [comment]
electron-builder > 20.35.0 requires Electron 3.

**Comment by jetlej** [comment]
That was the issue. Upgrading to electron 3.0 made it work! Thanks

**Comment by njdullea** [comment]
I have electron v4.0.6 and am having this issue. Does anyone have any suggestions?
