### ISSUE TITLE
ERROR:  TypeError: packager.info.callArtifactBuildStarted is not a function

### ISSUE THREAD

**Issue by insub** [electron-userland/electron-builder#3508]
* **Version**: 
"electron-builder": "^20.14.7",
"electron-builder-lib": "^20.14.7",
"electron-builder-squirrel-windows": "^20.14.6",
"webpack": "^4.20.2",
"webpack-cli": "^3.1.1",
"webpack-dev-server": "^3.1.3",
"webpack-target-electron-renderer": "^0.4.0",
node v8.12.0
npm 6.4.1
npm config set msvs_version 2015

* **Target**: 
win: [
  "squirrel",
  "zip"
]

i use appveyor.com CI，and i get error when package: 

`ERROR:  TypeError: packager.info.callArtifactBuildStarted is not a function\n    at C:\projects\testapp\packages\cx-app\node_modules\electron-builder-squirrel-windows\src\SquirrelWindowsTarget.ts:29:25\n    at Generator.next (<anonymous>)`

**Comment by develar** [comment]
electron-builder 20.38.0 marked as latest, so, it will be compatible with your updated `electron-builder-squirrel-windows`.
