### ISSUE TITLE
Allow architecture "${arch}" in artifactName for AppImage

### ISSUE THREAD

**Issue by fxha** [electron-userland/electron-builder#3510]
* **Version**:  20.38.0

* **Target**:  AppImage x86_64

First of all thanks for your great work! With the latest version `20.38.0` you break backward compatibility because you changed the output name of AppImage's. My question is, whether it is possible to include the `${arch}` variable in the `artifactName` for AppImage's like for the `tar.gz.` target. So we don't have to change your CI script because spaces are uncommon on Linux as binary name.

CLI output with `marktext-${version}-${arch}.${ext}` as `artifactName`:

```
  • building        target=AppImage arch=x64 file=build/marktext-0.13.65.AppImage
  • building        target=tar.gz arch=x64 file=build/marktext-0.13.65-x64.tar.gz
```

As you can see, the AppImage ignores the architecture but the other target is fine.

`product.json` snippet:

```
    "linux": {
...
      "artifactName": "marktext-${version}-${arch}.${ext}",
      "target": [
        {
          "target": "AppImage"
        },
        {
          "target": "tar.gz"
        }
      ]
    }
```

Before we used the default AppImage name:

```
 • building        target=AppImage arch=x64 file=build/marktext-0.13.65-x86_64.AppImage
```

**Comment by develar** [comment]
Fixed in `20.38.1`.
