### ISSUE TITLE
latest-mac.yml and latest-mac.json are not generated in the dist folder

### ISSUE THREAD

**Issue by applecool** [electron-userland/electron-builder#3513]
* **Version**:  
electron-builder: 20.38.2
electron-updater: 4.0.5
electron: 3.0.10

* **Target**: 
Mac 

I have a pretty simple hello world electron app. 
The following is my package.json config:
```

{
  "name": "hello-electron",
  "version": "0.0.1",
  "description": "Hello Electron App",
  "main": "main.js",
  "author": "applecool",
  "scripts": {
    "start": "electron .",
    "mac": "electron-builder -m",
    "win": "electron-builder -w",
    "build": "electron-builder -mwl",
    "publish-mac": "electron-builder build -m -p onTagOrDraft"
  },
  "build": {
    "appId": "com.applecool.electron",
    "directories": {
      "buildResources": "."
    },
    "mac": {
      "category": "public.app-category.productivity",
      "target": ["zip", "dmg", "pkg"]
    }
  },
  "dependencies": {
    "electron-log": "2.2.17",
    "electron-updater": "4.0.5"
  },
  "devDependencies": {
    "electron": "3.0.10",
    "electron-builder": "20.38.2"
  }
}


```

When I run the command: `electron-builder build -m -p onTagOrDraft` it generates the `.zip`, `.pkg`, `.blockmap`, `.dmg`, and a `builder-effective-config.yaml` files in the `dist` folder. The `latest-mac.json` and `latest-mac.yml` are not generated which are required for the auto-updater to work.

**Note:** I did see a bunch of issues where it was pointed that when the target is set to `dmg`, it doesn't create the `json` and `yml` files. Instead that needs to be set to `dmg` and `zip`. I tried with all the combinations and without the target property too. It doesn't generate the required `json` and `yml` files.

Could anyone let me know if I am doing anything wrong?

Thank you.

**Comment by zhaoterryy** [comment]
You are missing the publish key. It is required for creating the `latest-mac.yml` file.

https://www.electron.build/configuration/publish

**Comment by applecool** [comment]
My repo is on a github enterprise and when I give the publish property and set the command option to `electron-builder build -m -p never`, it gives me the following warning:
Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
and then fails.

I did give my enterprise url for the repo in the repository property in the package.json. But it still fails.

**Comment by doughock** [comment]
Did you check that GH_TOKEN is set in your environment?  You will need to get a token from GitHub and specify it in your environment.

As for the *.yml files, they are not generated locally, but will be published to GitHub.

**Comment by adeperio** [comment]
HI has anyone figured out this issue? I'm getting the same problem except its for when I publish to S3

**Comment by rlugge** [comment]
@adeperio did you ever solve this?  I'm successfully uploading to S3 on build, so _clearly_ I have the publish key set, but it's not generating the latest-mac file.  I had one created this morning when I was still fiddling with configurations, but now that I have a working config it's not creating the latest-mac.yml file.

**Comment by rlugge** [comment]
So in my case, it turned out that having my version end on 'a' (version 0.0.1a) was breaking things.
