### ISSUE TITLE
Make checkForUpdates available even when auto update isn't possible

### ISSUE THREAD

**Issue by kontrollanten** [electron-userland/electron-builder#3514]
* **Version**: 
20.36.2

* **Target**: 
linux deb

I'd suggest to create the `app-update.yml` file for all targets so that it's possible to call `checkForUpdates` even for targets that doesn't support auto update. The purpose is to make it possible to notify users that they should update their application.

If this is an appreciated feature I'd be happy to investigate further what it takes to make this possible.

**Comment by zhaoterryy** [comment]
I think it would take more work to make this happen using checkForUpdates() than creating your own custom check. It would be pretty simple to create some custom logic for this.

**Comment by kontrollanten** [comment]
Wouldn't it be nice if this feature was a part of the electron-builder? Of course I can write my own check, but I think it would be a great idea to make it easier for developers to promote their users to update their software (for security reasons, etc).
