### ISSUE TITLE
 CSC_IDENTITY_AUTO_DISCOVERY=false for mas creates error

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#3522]
* **Version**:  20.33.2

* **Target**:  mas

1) If you set CSC_IDENTITY_AUTO_DISCOVERY=false, you get an error instead of a warning.
I understand the app isn't ready for release, but if I'm intentionally turning off codesigning (and doing it separately), I don't want an error. A warning would be sufficient.

2) Also, setting mac.identity = false does not skip codesigning as the documentation says.

**Comment by zhaoterryy** [comment]
I haven't looked into this but please confirm that you don't have `"forceCodeSigning": true` set.

**Comment by rr326** [comment]
Confirmed. No "forceCodeSigning" at all.

**Comment by ishowshao** [comment]
i get error too, can't skip code sign
