### ISSUE TITLE
Command-line options to resolve Error: Application entry file "index.js" in the .\.\.app.asar does not exist

### ISSUE THREAD

**Issue by hanct** [electron-userland/electron-builder#3527]
electron-builder=v20.38.2
Node.js=10.13.0

Hi,
I got the error

Error: Application entry file "index.js" in the "D:\...dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.

How do I specify a specific file (say, main.js) to be my application entry file via options of the below command line. Cos it seem like by default, it refers to index.js
npx electron-builder build --win portable

**Comment by zhaoterryy** [comment]
Try `electron-builder  -c.extraMetadata.main=main.js`.
