### ISSUE TITLE
electron-updater : Retest to support Bitbucket private repos as well

### ISSUE THREAD

**Issue by iiitmanikanta** [electron-userland/electron-builder#3533]
Need an option to configure Private Bit Bucket Repo for auto updates

**Comment by ceharsh24** [comment]
There is no direct support for this. 

- You can use any CI (i.e. bitbucket Pipelines, TravisCI, Appveyor) services with Bitbucket. During the CI configuration, you can run a script to deploy artifacts on S3 or DigitalOcean Spaces and then you can easily use electron-updater.
