### ISSUE TITLE
Skip checkForUpdatesAndNotify because application is not packed

### ISSUE THREAD

**Issue by harrison0723** [electron-userland/electron-builder#3537]
`"electron-builder": "^20.38.2"`

`"electron-updater": "^4.0.5",`

* **Target**: 
darwin and win32

autoUpdater's `checkForUpdatesAndNotify()` is ignored with the log `Skip checkForUpdatesAndNotify because application is not packed` even when in a packaged app.

**Comment by harrison0723** [comment]
I was using an older version of electron. Upgrading it solves the issue.

**Comment by AbdulMuqtadeer** [comment]
I am also getting the same issue. I am using below versions:

```
 "electron-builder": "^20.38.4",
 "electron-updater": "^4.0.7",
 "electron": "4.0.0",
```

**Comment by mr-islam** [comment]
@harrison0723 THANK YOU SO MUCH! I spent 3 hours struggling with this issue and finally, finally it stopped giving me this error. 

@MrC1997 I was on electron@2.0.2 before, now I upgraded to electron@4.2.8 and it's working!
