### ISSUE TITLE
Generate portable executable file without other by-product files

### ISSUE THREAD

**Issue by hanct** [electron-userland/electron-builder#3543]
electron-builder version: 20.38.2

Currently, my package.json contains the below

     "build":{
    "directories":{ 
      "app":"dist",
      "output":"dist/packOutput"
    }
    "win":{
      "target":"portable"
    }
     }

Sure, I got what i want. A portable exectuable file is indeed generated after executing electron-builder.
But i observe that there are other files generated as well in the output folder. This includes
1) win-unpacked folder (which contains many files inside
2) builder-effective-config.yaml
3) node_modules folder

Is there any option not to output 1) ,2) and 3), or at least automatically remove it, after creating the standalone executable file.

I just only want the portable executable file.

**Comment by hanct** [comment]
Anyone?

**Comment by zhaoterryy** [comment]
There isn't an option for what you're asking for. Is there a particular reason why you don't want these files generated? If you really need this, you can write a custom build script that removes those files post-build.

**Comment by hanct** [comment]
Hi,
Thanks for replying. As my goal is to create a single exectuable file, I dont really need any other additional files generated. But from your reply, it seem that it is not possible to remove currently. So perhaps in future version of electron-builder, can provide an option to remove thoss files generated for convenience.
