### ISSUE TITLE
NSIS installer crashes on Windows 7 x64

### ISSUE THREAD

**Issue by joeyer** [electron-userland/electron-builder#3545]
electron-builder Version: 20.38.3:
Target Platform : x32:

NSIS generated by electron-builder crashes in most of the time in Windows 7. Crash Report given below.

Problem Event Name:	APPCRASH
Application Name:	Linkus-1.2.23-win-setup.exe
Application Version:	1.2.23.0
Application Timestamp:	5a6fed7c
Fault Module Name:	System.dll
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	5a6fed15
Exception Code:	c0000005
Exception Offset:	00001581
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	2052
Additional Information 1:	0a9e
Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
Additional Information 3:	0a9e
Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Click on the installation package, then cancel, and it will appear several times.But if you have already installed this program before, then you will not crash when you perform this operation.

**Comment by yangbo1983** [comment]
it is exeactly what i occured

**Comment by qmphan** [comment]
I am experiencing the same problem on a freshly installed windows 7


![image](https://user-images.githubusercontent.com/3208166/52864542-a9e91600-313a-11e9-80d8-dededf3136f9.png)

**Comment by julianhille** [comment]
i\ve seen this too on windows 8

**Comment by xiajingren** [comment]
hi. What is the final solution? I have a similar problem.

**Comment by Yoryky** [comment]
i have been troubled by this problem for a long time.  then I solve this problem by adding  'portable' config such below 
"win": {
    "target": [
      "nsis",
      "portable",
      "zip"
    ],
    "icon": "resources/icon.ico"
  },

hope that someone can be helped.

**Comment by leandrogianotti** [comment]
I have the same problem. My installer crash sometimes and I found that it's crashing when It tries to execute this line https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/multiUser.nsh#L35

I did a temporary fix removing from line 33 to line 38 and my installer doesn’t crash anymore and It looks like it works fine, but I'm not sure about why it's crashing in this line.
