### ISSUE TITLE
Question/FR? option for --js-flags (not possible via .appendSwitch)

### ISSUE THREAD

**Issue by remmythical** [electron-userland/electron-builder#3550]
* **Version**: 20.38.3 (latest to date)

Hi, i was looking for a way to pass the --js-flags option to build my app using the experimental .mjs esmodules supported by node 8.5.0+.
I searched through the docs and issue, but until now every question about electron command line arguments were answered with linking to the .appendSwitch() API by electron.

This is, however, not usable if you want to pass node flags for the main thread, because [here you _have_ to pass them to electron directly](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--js-flagsflags).

I was wondering if i was missing something on how to accomplish this in another way, or if this would be an improvement, not yet available?

(I know of the possibility to transpile my source to use modules, but wanted to see if i could get this feature without adding another compile step)

**Comment by damianobarbati** [comment]
@remmythical did you find solution? 
I'm trying to pass custom arguments to electron.
In the unpacked version I can easily use `electron -r esm`  to enable ESM imports but I don't know how to have `electron-builder` pass these arguments down to `electron` bin.
@develar can you help?

**Comment by dalenoe** [comment]
@damianobarbati Did you end up having any luck? I am trying to accomplish this as well, and can't seem to find any documentation. So here I am, looking at stale/closed issues.

**Comment by damianobarbati** [comment]
Unfortunately I didn't find anything. 
Stuck as you, using `requite` 😔
