### ISSUE TITLE
electron-updater cannot access private gitlab repository anymore

### ISSUE THREAD

**Issue by steve501** [electron-userland/electron-builder#3551]
* **Version**: 3.1.2

* **Target**: linux, mac and windows

I had a working setup of electron using the electron-updater with my private gitlab repository. My gitlab access token is not expired.
However since some weeks (at least it seems to be since then) the automatic updates stopped working without me changing anything in the updater coder or in the gitlab repository.
Now I checked for the error and in the console I get 
Error: Error: Cannot parse update info from latest-linux.yml in the latest release artifacts (https://gitlab.com<url-to-the-latest-yml>.yml): YAMLException: end of the stream or a document separator is expected at line 3, column 17:
    <head prefix="og: http://ogp.me/ns#">
gitlab seems to return an HTML page which is the sing in page.

this is the config in for the updater
`autoUpdater.setFeedURL({
    provider: "generic",
    url: "https://gitlab.com/svrecer/ugram-release/raw/master/dist/"
});

///////////////////
// Auto upadater //
///////////////////
autoUpdater.requestHeaders = {"PRIVATE-TOKEN": "RJVBtKdzfTAFutc3X-sH"};
autoUpdater.autoDownload = true;`

It doesn't work for my linux builds, windows builds or the mac builds. I already tried generating a new access token but got the same result.

**Comment by zomars** [comment]
I could be wrong, but I think you need to configure publish options in the package.json file as [described in the docs.](https://www.electron.build/configuration/publish#genericserveroptions)

**Comment by zomars** [comment]
Nevermind, it seems that there's [an issue with GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/47336).

**Comment by rllola** [comment]
I might be wrong but distributing your private token inside your app might be a bit dangerous ? I am not familiar with GitLab and I don't know what is its scope though. 

But hey a friend and I are working on auto-update service (https://www.update.rocks/) we are working on extending our service to GitLab. Would be great if you can contact us and we could work together on making it happening :wink:
