### ISSUE TITLE
Uncaught Exception: Cannot find module "/foo.app/.../app.asar/build/electron.js"

### ISSUE THREAD

**Issue by pfbarnet** [electron-userland/electron-builder#3552]
Upon launching my app after build I get the following error:

> A Javascript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module 
> '/Users/foo/dist/mac/foo.app/Contents/Resources/app.asar/build/electron.js"
> etc.  

Some details:
The app in question is a chat app that utilizes Express and depends on a server.  I'm using chatkit by Pusher.  
<img width="418" alt="screen shot 2018-12-16 at 1 43 22 pm" src="https://user-images.githubusercontent.com/33267691/50057465-d8e20c00-0138-11e9-8506-d85c1a73bc1b.png">

**Comment by SupremeTechnopriest** [comment]
Do you have that file added to your `package.json` under `build.files`?  If not it wont be added to the build.
