### ISSUE TITLE
Ubuntu 18.04 Sidebar Icon Bad quality (sawtooth-like)

### ISSUE THREAD

**Issue by allexzander** [electron-userland/electron-builder#3553]
* **Version**:  20.29.0

* **electron-updater version**: 2.21.10

* **Target**: AppImage

I am having an issue with how left sidebar (toolbar) icon looks after built **AppImage** for Ubuntu and ran it on Ubuntu 18.04.
I am specifying icon in a `BrowserWindow` settings like this: 
`let window = new BrowserWindow({ icon: icon.png });`

After I've built and packaged the AppImage target, I ran it on Ubuntu 16.04 first, and it works fine there.

Tried on Ubuntu 18.04 - image quality is significantly less.

Attaching screenshots.

Here how the icon looks on Ubuntu 16.04 (no quality issues spotted):
![50068642-45244480-01f9-11e9-877d-d4cf0d0968fc](https://user-images.githubusercontent.com/12224014/50069851-70f5f900-01fe-11e9-847a-675f7ff20089.png)

And here is the screenshot from Ubuntu 18.04 with icon having bad quality issue:
![50068674-6422d680-01f9-11e9-8864-7192a31b3d9e](https://user-images.githubusercontent.com/12224014/50069881-879c5000-01fe-11e9-8d76-f565d3db3691.png)

Here is the source image:
![delete1](https://user-images.githubusercontent.com/12224014/50069930-b7e3ee80-01fe-11e9-93f8-e489fe77367f.png)

I tried searching similar issues in Google with no results. I tried download AppImage-distributed applications from other vendors, and most of them are having exactly the same issue in Ubuntu 18.04.

Please, suggest a workaround. Thank you.

**Comment by SupremeTechnopriest** [comment]
My guess (and its only a guess) is that when it down scales the image you are losing fidelity.  Try using an image that is the native icon size.

**Comment by allexzander** [comment]
@SupremeTechnopriest Any idea what the native icon size should be? I browsed GIMP's icon size here https://github.com/GNOME/gimp/tree/master/desktop they have same dimensions, with largest being 256x256. Thx for suggestion btw.

**Comment by SupremeTechnopriest** [comment]
I am about to start testing Linux in my own app. I will let you know what I
discover.

**Comment by dannypaz** [comment]
Having the same issues as above. I have no found any solutions aside from https://github.com/mattermost/desktop/issues/828, however the issue isn't completely solved because it requires the user to "dock" the application
