### ISSUE TITLE
Q: Possible to roll back an update via modifying .yml file?

### ISSUE THREAD

**Issue by dorian-coygo** [electron-userland/electron-builder#3554]
* **Version**: electron-builder: 20.36.2

* **Version**: electron-updater 4.0.4

* **Target**: linux

I have 2 questions:
1) Is there documentation / best practice on rolling back to a previous version? I am assuming it would be to revert a commit, then bump package.json, then build and publish.If this isn't correct, let me know.

2) Is there a faster way to roll back to a previous version without rebuilding by just modifying the `latest.yml`? I tried to just modify the `version: XXXX` which seems to catch an update, but then I get stuck in an updating loop. Maybe this isn't possible due to differential updates?

Example:
* We use an s3 bucket to store our `.AppImage` and `latest-linux.yml` file.
* We build `0.0.3` and deploy it to our bucket.
* We notice a bug in `0.0.3` and want to quickly rollback to `0.0.2`. 
* One way: revert the bad commit, bump package.json to `0.0.4`, build, and publish to s3 bucket. ~10-15 minutes
* 2nd way: download `0.0.2` `latest-linux.yml` (since we version control the file and ymls), and change `version: 0.0.2` to  `version: 0.0.4` and then publish to s3 bucket. ~ 1 minute. My initial test seemed to cause an update loop for me, but maybe I have to change more than just `version`.

**Comment by framerate** [comment]
@develar Is this correct or is there a better way?

>1. Is there documentation / best practice on rolling back to a previous version? I am assuming it would be to revert a commit, then bump package.json, then build and publish.If this isn't correct, let me know.

We hit this today with a production-only bug :(

**Comment by framerate** [comment]
@dorian-coygo 

For the record, I ended up just doing this:

> * One way: revert the bad commit, bump package.json to `0.0.4`, build, and publish to s3 bucket. ~10-15 minutes

Hopefully there's a better way soon that comes to light.

**Comment by BERNARDO31P** [comment]
Is there still no way to correctly rollback to a different version?
