### ISSUE TITLE
How would .gitignore look like?

### ISSUE THREAD

**Issue by tenzan** [electron-userland/electron-builder#356]
Hello!

Can you please show how would `.gitignore` look like for electron application?

I assume, it should ignore `dist` folder that's created when running `npm run pack`, etc..

Thanks.

**Comment by develar** [comment]
1) [Two package.json structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure) is strongly recommended.
2) See https://github.com/develar/onshape-desktop-shell/blob/master/.gitignore

```
dist/
node_modules/
```
