### ISSUE TITLE
Step-by-step tutorial on package creation

### ISSUE THREAD

**Issue by tenzan** [electron-userland/electron-builder#357]
Though, it's explained to some extent how to create platform specific applications at
https://github.com/electron-userland/electron-builder#two-packagejson-structure

Is there avaialable any step-by-step tutorial?

It'd nice to have for the following sample app https://github.com/electron/electron-quick-start

Thanks.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder#two-packagejson-structure

+

https://github.com/electron-userland/electron-builder#in-short

+

Real project example — https://github.com/develar/onshape-desktop-shell

= ?

Well, yes, will be cool. Help wanted ;)

**Comment by tenzan** [comment]
@develar Hi!

I'm interested. If you will help me when I get stuck then I'm ready to work on this. ;)

Cheers.

**Comment by develar** [comment]
Also see http://electron.rocks/electron-builder-explained/

> I'm interested. If you will help me when I get stuck then I'm ready to work on this. ;)

Of course.

**Comment by tenzan** [comment]
@develar Agreed! I'll be working on it during my free time.
We'll keep in touch 👍

**Comment by develar** [comment]
Moved to backlog. Feel free to reopen if you want to help.

**Comment by develar** [comment]
Reopened as @paulbjensen wants to do it.

**Comment by develar** [comment]
Closed again due to lack of activity.
