### ISSUE TITLE
How to target an entry file during packaging?

### ISSUE THREAD

**Issue by daniellizik** [electron-userland/electron-builder#3570]
* **Version**: `20.38.3`

* **Target**: os x, windows 32-bit

How do I specify an entry file for an electron app? According to [this](https://github.com/electron-userland/electron-builder/issues/1966#issuecomment-323449139) I cannot send environment variables to a packaged app, so the only way to package separate, say, staging/pilot/test/prod apps is to use different entry files, for instance:

```js
// index.staging.js
require('./mainProcess')({ APP_URL: 'staging.foo.com' });

// index.pilot.js
require('./mainProcess')({ APP_URL: 'pilot.foo.com' });

// index.production.js
require('./mainProcess')({ APP_URL: 'foo.com' });
```
It's not exactly clear in the CLI or API docs if it's possible to pass an entry parameter to the builder though there is a brief note saying this should be:

> Option files to indicate which files should be packed in the final application, **including the entry file**, maybe required.

I read [here](https://github.com/electron-userland/electron-builder/issues/2165#issuecomment-334927404) that electron's official recommendation is to use webpack, but the app I have has very little application code, it just calls `mainWindow.loadURL(config.APP_URL)`. I think [this](https://webpack.electron.build/environment-variables) is not exactly what I need; I don't need environment variables injected during the webpack build, but during the electron builder packaging. Or am I wrong on that...?

You can use `--config` to target a json file, but if you do that builder says `configuration has an unknown property 'main'`

**Comment by daniellizik** [comment]
Also tried dynamically generating a `electron-builder.env` file with `NODE_ENV` (according to the docs) like this

```bash
#!bin/bash

$ cat > electron-builder.env << EOF
$ NODE_ENV=$1
$ EOF

$ build -m
$ rm electron-builder.env
```
but in the packaged app NODE_ENV isn't getting passed correctly

**Comment by daniellizik** [comment]
also this... https://discuss.atom.io/t/solved-dotenv-doesnt-work-after-build/42616

total hack solution

```json
{
  "main": "src/index.js",
  "scripts": {
    "build:pilot": "sh scripts/build.sh pilot",
    "build:production": "sh scripts/build.sh production"
  },
  "build": {
    "directories": {
      "output": "dist/TARGET"
    }
  }
}
```

```bash
#!bin/bash

# cache our real package.json
# we need to make a fake one for electron builder
$ mv package.json _package.json

# make tmp package.json
$ cp _package.json package.json

# set entry file
$ sed -i '' "s/index.js/index.$1.js/" package.json

# set output folder
$ sed -i '' "s/TARGET/$1/" package.json

# package app
$ build -m

# get rid of electron config package.json
$ rm package.json

# "reset" old package
$ mv _package.json package.json
```

```bash
$ npm run build:pilot
```

**Comment by raymondjacobson** [comment]
Any luck with this?

**Comment by daniellizik** [comment]
@raymondjacobson nope, i just had to hack a script that takes my actual config and temporarily overrides `build` in my package.json.
