### ISSUE TITLE
Cannot use copy and paste after packaged

### ISSUE THREAD

**Issue by hugetiny** [electron-userland/electron-builder#3571]
Cannot use copy and paste （command+c or command+v）in input or textarea
after packaged

    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm

**Comment by 18124772589** [comment]
同问，解决了吗？
