### ISSUE TITLE
NSIS artifactName ${arch} macro doesn't work (returns empty string)

### ISSUE THREAD

**Issue by AnonymerNiklasistanonym** [electron-userland/electron-builder#3574]
* **Version**: 20.38.4 (in combination with electron: 4.0.0, node: 11.6.0 on x64 Windows 10)

* **Target**: nsis

My `package.json` code:

```json
{
  ...
  "name": "appName",
  "version": "0.0.1",
  "build": {
    ...
    "appId": "appId",
    "win": {
      ...
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      ...
      "artifactName": "${productName}_installer_v${version}_os=${os}_arch=${arch}.${ext}"
    }
  }
}
```

After executing
-  `electron-builder . --win --ia32 --x64`
- or `electron-builder . --win --ia32`
- or `electron-builder . --win --x64`

the packaged output file name is always: `appName_installer_v0.0.1_os=win_arch=.exe` 

To be sure I tested if there are any differences between the output files. I found out that all the created files that override themselves are different in their size:

Command | Output file size
--- | ---
`electron-builder . --win --ia32` | 45MB
`electron-builder . --win --x64` | 46MB
`electron-builder . --win --ia32 --x64` | 91MB

- **Problem:** I think the `${arch}` marco is recognized (there is no error like when you would use an unsupported macro like `${nullUndefined}`) but instead of the arch an empty string is printed/returned which should not happen(?).

Complete source code for debugging: https://github.com/AnonymerNiklasistanonym/IliasBuddyDesktop

**Comment by hengkx** [comment]
I have the sane problem.

**Comment by MichaelIT** [comment]
+1

**Comment by JannisX11** [comment]
This is still an issue in 21.1.1.

**Comment by JannisX11** [comment]
Pretty sure I found the cause of the issue.
https://github.com/electron-userland/electron-builder/blob/4bc0559b3957674ab4280dfc9197a9ebeb8fd53c/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L130
The line just passes `null` as the arch name instead of the actual arch of the individual installers.

**Comment by develar** [comment]
Arch doesn't matter for NSIS, because both archs packed into the same installer.

**Comment by JannisX11** [comment]
> Arch doesn't matter for NSIS, because both archs packed into the same installer.

They are not, that's the problem. There is an option to include both archs in the same installer (`electron-builder --x64 --ia32`), but that would double the file size of the installer, which is not what I want.
By default, Nsis installers only work for one architecture.
