### ISSUE TITLE
Dynamic import support

### ISSUE THREAD

**Issue by p-herbert** [electron-userland/electron-builder#3575]
* **electron-builder version**: 20.38.4
* **electron version**: 3.0.13

* **Target**: macOS, Windows

Hello!

I was having issues packaging my web application into an `Electron` application using `electron-builder`. Eventually I was able to get it to work by removing _all_ dynamic imports. For example:

```
// Bad
Const MyComponent = import('./MyComponent.jsx');

// Good
import MyComponent from './MyComponent.jsx';
```

Are dynamic imports on the roadmap? Or have I misconfigured something in my build process? Here is the relevant information from my `package.json`:

```
{
    "homepage": "./",
    "main": "public/electron.js",
    "scripts": {
        "start": "react-scripts start",
        "electron": "env-cmd .env.development electron .",
        "build": "react-scripts build",
        "build:development": "env-cmd .env.development npm run build",
        "build:staging": "env-cmd .env.staging npm run build",
        "build:production": "env-cmd .env.production npm run build",
        "pack": "electron-builder --dir",
        "dist": "electron-builder",
        "postinstall": "patch-package && electron-builder install-app-deps"
    },
    "build": {
        "compression": "store",
        "mac": {
            "target": "default",
            "identity": null
        },
        "win": {
            "target": "nsis"
        },
        "extraResources": [
            {
                "from": "build/images",
                "to": "images"
            }
        ]
    }
}
```

**Comment by huddlhire** [comment]
Ran into the same issue. Works locally, but the imports fail in the packaged app. :(

**Comment by the-cult-of-jarvis** [comment]
ran into the same issue. Works locally but fails in the packaged app. :(

**Comment by develar** [comment]
> Are dynamic imports on the roadmap?

electron-builder doesn't preprocess your source code.
