### ISSUE TITLE
[feature request] `app-builder-lib`: add breadcrumb to enable the app to identify the build target at runtime

### ISSUE THREAD

**Issue by warren-bank** [electron-userland/electron-builder#3579]
I'm not super familiar with all of the internals.. but it seems that the simplest solution would be if a javascript file were injected into the app directory during the build process for each target.

ex: `./app/electron_builder_metadata.js`
```javascript
window.electron_builder_metadata = {
  "target": "deb"
}
```

if the script in the app's renderer process wants to make use of this information..

ex: `./app/index.html`
```html
<html>
<head>
<script src='electron_builder_metadata.js'></script>
<script src='renderer.js'></script>
...
```

ex: `./app/renderer.js`
```javascript
switch (window.electron_builder_metadata.target) {
  case 'deb':
    alert('deb package')
    break
}
```

..might be a more complex problem if any aspect of the build process occurs in parallel.. and all parallel threads use a shared app directory.

however, this isn't entirely dissimilar to the `extraFiles` config option.

**Comment by warren-bank** [comment]
however, the above methodology wouldn't be of any benefit to the main process.. at least not prior to the app's `ready` event

can you think of a way to inject this metadata directly into `process.env.electron_builder_metadata` for both main and renderer processes?

**Comment by sindresorhus** [comment]
I would also like to see other `electron-builder` metadata included, like build date and Git commit SHA.

**Comment by warren-bank** [comment]
as suspected, [this previous issue](https://github.com/electron-userland/electron-builder/issues/1955) confirms that it just isn't viable to set a custom environment variable that would be accessible to the electron processes at runtime..

very open to other ideas..

**Comment by warren-bank** [comment]
notes:

* the following proposal is rather invasive..
  * shouldn't be enabled by default
  * could be enabled by passing a CLI flag (ex: `--inject-metadata`)

what if:

* `./app/electron_builder_metadata.js`
  * auto generated:
    * `process.env.electron_builder_metadata = {target: "", timestamp: "", commit: "", ...}`
  * renderer process can opt to include this &lt;script&gt; file

* `./app/electron_builder_metadata.main.js`
  * auto generated by combining:
    * `./app/electron_builder_metadata.js`
    * ';'
    * `./app/main.js` (path as determined by `main` attribute in `package.json`)

* `-c.extraMetadata.main='electron_builder_metadata.main.js'`
