### ISSUE TITLE
Q: Can I add drivers for installation?

### ISSUE THREAD

**Issue by phhoef** [electron-userland/electron-builder#3582]
* **Version**:
    "electron-builder": "^20.38.4",
    "electron-builder-lib": "^20.23.1",
    "electron-builder-squirrel-windows": "^20.38.3"

* **Target**: macOS, Windows

I am building a small App that communicates with an Arduino via RS232 interface.
On Mac it's not a big deal, as the default drivers are working.
On windows it's necessary to install the Arduino Drivers. Is it possible to include these drivers in the setup?
I am using Squirrel as Windows Installer.

**Comment by DarkAnfi** [comment]
I have the same question...

**Comment by develar** [comment]
No, it is possible only using NSIS installer. Or as part of your app (recommended) on first start.
