### ISSUE TITLE
Can I use AutoUpdater without a publish configuration?

### ISSUE THREAD

**Issue by adamoldelo** [electron-userland/electron-builder#3587]
* **Version**:  latest

* **Target**: NSIS

I am trying to configure AutoUpdater with an NSIS target to an S3 bucket. The problem is that I need to sign the app with an EV cert locally before publish. So the two possibilities are:

1. Configure the publish profile to sign the app with my EV cert locally before uploading to the S3 bucket. Basically I would need a custom script to run after build but before publishing.

2. Avoid the publish profile, tell AutoUpdater the bucket to look for the updates (the S3 bucket) and upload my app to S3 manually.

Are either of these options possible? Any guidance on this is appreciated!

Thanks in advance.

**Comment by develar** [comment]
You can use `setFeedURL(publish_options)` to set dynamically.
