### ISSUE TITLE
package.json Error

### ISSUE THREAD

**Issue by do-web** [electron-userland/electron-builder#3588]
* **Version**: 
20.38.4

* **Target**: 
MAC

I get an error "Error: 'build' in the application package.json (bundled/package.json) is not supported since 3.0 anymore. Please move 'build' into the development package.json (package.json)"

What does it mean, there is nothing in the documentation.

**Comment by halfbloodman** [comment]
> * **Version**:
>   20.38.4
> 
> * **Target**:
>   MAC
> 
> I get an error "Error: 'build' in the application package.json (bundled/package.json) is not supported since 3.0 anymore. Please move 'build' into the development package.json (package.json)"
> 
> What does it mean, there is nothing in the documentation.

I've got the same error, is there any way to fix it?

**Comment by ckvnahsik** [comment]
I got same issues

**Comment by frogred8** [comment]
i had gotten the same error but found a solution.
electron-builder supports a config file so i moved "build" field on package.json to new config file.
i'll show my config and you can refer to the document below.
https://www.electron.build/configuration/configuration#configuration

**command line**
`
npm run electron:build --config electron-builder.json
`

**electron-builder.json**
```
{
    "productName": "myApp",
    "appId": "com.myApp",
    "asar": true,
    "protocols": {
      "name": "myApp",
      "schemes": [
        "myApp"
      ]
    },
    "mac": {
      "target": [
        "default"
      ]
    },
    "win": {
      "target": [
        "portable"
      ]
    },
    "portable": {
      "artifactName": "myApp.exe"
    },
    "extends": null
}
```

**Comment by crossle** [comment]
same problem

**Comment by HeiShanLaoYao889** [comment]
I used your method but still changed the default configuration

**Comment by shturnev** [comment]
@frogred8  thank you, it helped

**Comment by knghlp508** [comment]
@frogred8 Thanks! It works.
