### ISSUE TITLE
Running multiple alpha/beta/latest releases concurrently

### ISSUE THREAD

**Issue by avner-hoffmann** [electron-userland/electron-builder#3589]
**Version:**
**electron-builder**: 20.34.0
**electron-updater**: 3.2.3 

**Target:**
dmg (mac),
nsis (windows)

I'm trying to be able to build and run concurrently different releases of my app (alpha, beta, production...)
I'm not interested in app channeling, since I have a different publish configuration for each release, and each release is looking at different latest-mac.yml/latest.yml located on different domains (I prefer to work that way). 
I do want to be able to treat each release as if it's a different app, so that the OS will consider each release type as a different app and I'll be able to run them concurrently. 

I played a little with electron-builder configuration files and changed the _appId_ and _productName_ fields to be different for each release, but that wasn't sufficient. Only after I changed the package.json _name_ field I was able to install and run two different releases (I think I've read that the uniqueness of the app is determined by the combination of the _name_ and _version_ fields). 
However, I don't want to manually change the _name_ field in the package.json file every time I'm building a different release of my app..

What's the right way to achieve this?

**Comment by zhaoterryy** [comment]
See config option "extraMetadata" in: https://www.electron.build/configuration/configuration.html#configuration
