### ISSUE TITLE
icon directory doesn't contain icons

### ISSUE THREAD

**Issue by tontonfranki** [electron-userland/electron-builder#3591]
* **Version**: 20.38.4

* **Target**: 
I don't know if this is a bug or configuration problem, but when I package the app with command ->
`npm run build:prod && electron-builder build --windows`, I'm getting error after packaging 

![image](https://user-images.githubusercontent.com/22175142/50811581-0441bc00-12dd-11e9-8aa0-d5d238c2f3fe.png)

This is the stack
![image](https://user-images.githubusercontent.com/22175142/50811602-263b3e80-12dd-11e9-9146-458e1f14f774.png)

For the config 

In my electron-builder.json
```
"win": {
    "icon": "dist",
    "target": [
      "portable"
    ]
  }
```
In my angular.json
![image](https://user-images.githubusercontent.com/22175142/50811976-da899480-12de-11e9-9dc0-cf0f516a62be.png)

Also, I can see favicon.ico in my /dist folder
![image](https://user-images.githubusercontent.com/22175142/50811712-9ba70f00-12dd-11e9-89bc-88839fdb8c5b.png)

I also tried .png icon...
Could this be related to https://github.com/electron-userland/electron-builder/issues/3232
Am I missing something? Thanks for any help!

**Comment by YolandaXQY** [comment]
你是怎么解决的后来

**Comment by tranbaduyuy** [comment]
I got the issue too, any one had the advice for this?

**Comment by chudakM** [comment]
mb try smth like this [http://prntscr.com/mjpg4u](url)

> * **Version**: 20.38.4
> 
> * **Target**:
>   I don't know if this is a bug or configuration problem, but when I package the app with command ->
>   `npm run build:prod && electron-builder build --windows`, I'm getting error after packaging
> 
> ![image](https://user-images.githubusercontent.com/22175142/50811581-0441bc00-12dd-11e9-8aa0-d5d238c2f3fe.png)
> 
> This is the stack
> ![image](https://user-images.githubusercontent.com/22175142/50811602-263b3e80-12dd-11e9-9146-458e1f14f774.png)
> 
> For the config
> 
> In my electron-builder.json
> 
> ```
> "win": {
>     "icon": "dist",
>     "target": [
>       "portable"
>     ]
>   }
> ```
> In my angular.json
> ![image](https://user-images.githubusercontent.com/22175142/50811976-da899480-12de-11e9-9dc0-cf0f516a62be.png)
> 
> Also, I can see favicon.ico in my /dist folder
> ![image](https://user-images.githubusercontent.com/22175142/50811712-9ba70f00-12dd-11e9-89bc-88839fdb8c5b.png)
> 
> I also tried .png icon...
> Could this be related to #3232
> Am I missing something? Thanks for any help!

mb try smth like this [http://prntscr.com/mjpg4u](url)

**Comment by Aarbel** [comment]
Same issue here, have you found a solution ?

**Comment by Aarbel** [comment]
@tontonfranki

**Comment by Aarbel** [comment]
Ok found a solution:

1. You should use png instead of ico (i also had a `unknown output format set` error)
2. You should add this in your package.json:
```
build: {
	…
    "linux": {
      "category": "TODO: fille the category of your app",
      "icon": "build/1024x1024.png or any route to the right png file > 256px X 256px",
      "target": [
        "AppImage"
      ]
    },
}
```
