### ISSUE TITLE
Failed to specify 'Exec' entry in desktop config

### ISSUE THREAD

**Issue by elvisvoer** [electron-userland/electron-builder#3594]
* **Version**: 20.38.3

* **Target**: 

Looks like this commit https://github.com/develar/electron-builder/commit/0f2c25fab49ac2a9e584ecb9dcadadcb01242e88 forbids the use of `Exec` in desktop configuration.

@develar can you explain why that decision was made considering `Exec` is a valid entry of a Desktop file? 

Also documentation here should have been updated when such change is made: https://www.electron.build/configuration/linux

**Comment by MyTheValentinus** [comment]
Hello,
Me too, i try to enable desktop entry for AppImage build but i do not find any documentation to generate this file. No entry was added on Ubuntu and Deepin.

Thanks

**Comment by hugetiny** [comment]
@elvisvoer I think the Exec in desktop configuration should be generated or edited when the app is opened,cause the exec option changes due to the file location of app
