### ISSUE TITLE
Checksum error on Windows differential download, full update works

### ISSUE THREAD

**Issue by asalvo** [electron-userland/electron-builder#3597]
**Version**
├─ electron-builder@20.38.4
├─ electron-devtools-installer@2.2.4
├─ electron-download@4.1.1
├─ electron-log@2.2.17
├─ electron-osx-sign@0.4.11
├─ electron-publish@20.38.3
├─ electron-to-chromium@1.3.99
├─ electron-updater@4.0.6
└─ electron@3.0.11

**Target/Environment**:
- Default Targets for Mac and Windows. Problem is only occurring on Windows. 
  - building for both ia32 and x64
- Files are hosted on Azure Blob Storage, so I have set useMultipleRangeRequest to false. 

**Problem**
I get error messages in the log when the update is downloaded. These appear to be limited to trying to do a differential update. The app is updated using the full installer without further errors. I would like to understand the errors better and hopefully eliminate them before releasing the app to customers. 

With differentialPackage set to true, and the blockmap file uploaded to azure, I get the following checksum error. 

`[error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected UY6EliTy/kpCtc4FGX/vZJ0GSJfxqtDXxDhGqywUi8P29U4WhLwRn3AN6aLDSAVTk3SXcB+KfUyzQlen8E8scw==, got FklFAv+qiQOJiTBolrFyvbK0ngYhlwuBunoJb9RFXAAB6/nAblcbzyT42kGIbwQFv8CD7sY7URO/vDGttio3tg==`

The expected checksum value is in latest.xml. I have verified that the checksum of the installer file matches what is in latest.xml both before upload, and after downloading it (I checked both the file downloaded by electron-updater, as well as manually downloaded the file from Azure Blob Storage). 

**My current Workout-Around that has a slight annoyance**
I really don't need differential updates right now, so I tried to disable it by setting differentialPackage to false, and while the blockmap is now longer generated, electron-builder still tries to download it and generates a legit error. 

`[error] Cannot download differentially, fallback to full download: Error: Cannot download "https://trainrdtrcmn01un1softw01.blob.core.windows.net/installers/windows/v001/InstallerTest/TrainerRoad-Alpha-2019.1.0.93.exe.blockmap", status 404:`

I could not find a publish configuration option which would disable electron-updater from trying to download the non-existant blockmap file. Does one exist? I know it's kind of petty, but I would like to keep error messages out of our logs if possible to cut down on noise from our support team.

**Comment by gimdongwoo** [comment]
When publishing for windows, no block map file generated.
Is it a bug?
