### ISSUE TITLE
Support ability to specify install location on Windows

### ISSUE THREAD

**Issue by joeferraro** [electron-userland/electron-builder#36]
This is helpful for folks who do not have admin access, for example

**Comment by demetris-manikas** [comment]
Before proceeding  with this feature electron-builder needs to get rid of the RMDir /r $IINSTDIR in the uninstaller as mentioned by
http://nsis.sourceforge.net/Reference/RMDir
http://nsis.sourceforge.net/Validating_$INSTDIR_before_uninstall
Otherwise bad bad things will happen eventually

**Comment by develar** [comment]
Since 3.0 we support only Squirrel.Windows. And Squirrel.Windows [installs to the local user account](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/goals.md#installing).
