### ISSUE TITLE
ipcMain and ipcRenderer don't fire after building

### ISSUE THREAD

**Issue by osztenkurden** [electron-userland/electron-builder#3601]
* **Version**: 20.38.4

* **Target**: Windows

On dev environment, everything works good, so after clicking on image (React), showImage() is called, which then calls ipcRenderer.send:

`showImage(){
const ipc = window.require('electron').ipcRenderer;
ipc.send('openOverlay', this.imageId);
}`

And in the main.js I have:

`electron_1.ipcMain.on('openOverlay', function (_e, imageId){

    winOverlay = new electron_1.BrowserWindow({ frame: false, fullscreen: true, transparent: true, resizable: false });

    var overlayUrl = url.format({
        pathname: path.join(__dirname, '../build/index.html'),
        protocol: 'file:',
        slashes: true,
        hash: "/viewer/" + imageId
    });
    winOverlay.loadURL(overlayUrl);
    winOverlay.on('closed', function () {
        winOverlay.quit();
        winOverlay = null;
    });
});`
It may look weird because it's transpiled from TypeScript.

And for 100% showImage() is called, but nothing happens - ipcMain.on() isn't fired, despite the fact, that before building everything worked perfectly.

**Comment by nickfan** [comment]
@osztenkurden i got the same trouble, have you found any solution yet?

**Comment by hannq** [comment]
+1，have you found any solution yet?

**Comment by GuilhermeDaniluski** [comment]
is there a solution?

**Comment by kyleedenise** [comment]
+1, still looking for a solution to this

**Comment by mmaietta** [comment]
Not sure what version the new report is for. Also, this seems unrelated to electron-builder and more related to your runtime.

Please try a more recent version of electron builder. `latest` is up at 22.11.x

**Comment by ExquisiterEmil** [comment]
+1, even with 22.11.5 I got that issue with my build
