### ISSUE TITLE
the appimage doesn't quit after i triggered app.quit() in linux

### ISSUE THREAD

**Issue by hugetiny** [electron-userland/electron-builder#3603]
![image](https://user-images.githubusercontent.com/19659202/51114363-0f966980-1840-11e9-8e6c-8e1df9bc03e2.png)
after i click the 'X'
![image](https://user-images.githubusercontent.com/19659202/51114439-4ff5e780-1840-11e9-8c7a-1f3ba00dfe52.png)
the process is still there

**Comment by hugetiny** [comment]
here is the code
![image](https://user-images.githubusercontent.com/19659202/51114506-787de180-1840-11e9-8a6a-93b3789e3df9.png)

**Comment by hugetiny** [comment]
and the icon is still in tray and can't be destroyed which works fine in Windows and Mac

**Comment by kraenhansen** [comment]
This looks like an electron bug to me, why do you think this is related to electron-builder?

**Comment by hugetiny** [comment]
@kraenhansen  I can debug with the electron installed on Linux but failed after I packaged into a AppImage
