### ISSUE TITLE
Updater differential download from github doesn't send "download-progress" event

### ISSUE THREAD

**Issue by mrbuds** [electron-userland/electron-builder#3606]
* **Version**:  
electron-builder: 20.38.4
electron-updater 4.0.6

* **Target**: 
windows x64

It seems that when the updater is doing a differential download from github the event "download-progress" is not passed.

When i build my electron app on my computer, updater get a sha512 checksum mismatch, and proceed to a full download on github, which show download progress correctly.
When i use a build made by appveyor with certificates, updater do a differential download from github, and my app doesn't show any download progress bar.

**Comment by duizhenpeng** [comment]
I also encountered the same problem. I hope to get help.

**Comment by Stanzilla** [comment]
Still valid

**Comment by develar** [comment]
Duplicates #2521
