### ISSUE TITLE
exe not run as administrator

### ISSUE THREAD

**Issue by tzahush** [electron-userland/electron-builder#3607]
* **Version**:  latest

latest

* **Target**:  latest

Hello, my package.json build looks like this:
 

>  "build": {
>     "buildDependenciesFromSource": true,
>     "npmRebuild": true,
>     "npmArgs": [
>       "--arch=ia32",
>       "--platform=win32"
>     ],
>     "asar": false,
>     "publish": {
>       "provider": "s3",
>       "bucket": "*****",
>       "path": "/"
>     },
>     "files": [
>       "server/**/*",
>       "ExamApplication.zip",
>       "main.js",
>       "client/**/*",
>       "SafeExamBrowserInstaller.exe"
>     ],
>     "win": {
>       "target": "nsis",
>       "icon": "icon.ico",
>       "legalTrademarks": "*****ltd",
>       "artifactName": "***.exe",
>       "requestedExecutionLevel": "highestAvailable",
>       "signAndEditExecutable": false
>     },
>     "nsis": {
>       "createStartMenuShortcut": false,
>       "oneClick": true,
>       "runAfterFinish": true,
>       "include": "installer.nsh",
>       "allowElevation": true,
>       "perMachine": false
>     }
>   }

But still the application is not ran as administrator, the manifest file does not contain the highestAvailable, is it possible i am doing something wrong?

thank you

**Comment by zNoobs** [comment]
Same problem here (but I use "target": "portable"), I compiled with:
- "requestedExecutionLevel": "highestAvailable"
and
-  "requestedExecutionLevel": "requireAdministrator"

The .exe does not open (no error, nothing happens) when I launch it with a double click, it opens only if I do right-click "Run as admin" or start it from a cmd with admin rights.
