### ISSUE TITLE
How to build an OSX app for both Non-Mac AppStore and for Mac AppStore?

### ISSUE THREAD

**Issue by hp011235** [electron-userland/electron-builder#361]
Hi,

I would like to know as to how can I get the builds for both AppStore and non-AppStore version? Can I just provide different certificates link for CSC_LINK & CSC_INSTALLER_LINK as mentioned here: [https://github.com/electron-userland/electron-builder/wiki/Code-Signing](here)? But, then how can I get two artifacts out of that? Also, I want to know how should I provide my entitlements file for electron-builder to use?

Thanks in advance,
-Hetal

**Comment by develar** [comment]
>  how should I provide my entitlements file for electron-builder to use?

https://github.com/develar/onshape-desktop-shell/issues/3#issuecomment-215003279

> how can I get the builds for both AppStore and non-AppStore version?

https://github.com/electron-userland/electron-builder/issues/332#issuecomment-214686006 Will be fixed soon.

Duplicates #332

**Comment by hp011235** [comment]
I was able to resolve to get my app sandboxed by restarting my machine. I don't know why, but totally weird. Now, it is showing that my app is sandboxed. 

However, when I start my app, its showing nothing but a spinner. My app gets hanged and is not responding anymore. Has anyone faced this issue before?

![screen shot 2016-04-27 at 6 13 47 pm](https://cloud.githubusercontent.com/assets/7158776/14872760/4458758c-0ca4-11e6-8096-81521e28df74.png)

**Comment by develar** [comment]
> by restarting my machine. I don't know why, but totally weird. 
OS X bug, see https://github.com/electron-userland/electron-packager/issues/323

> Any ideas as to why the sandboxed app is not even starting completely?

Please open Console (OS X system app) -> All Messages to see errors.

**Comment by hp011235** [comment]
> Please open Console (OS X system app) -> All Messages to see errors.

`
4/27/16 10:30:00.325 PM taskgated[110]: no application identifier provided, can't use provisioning profiles [pid=4904]
4/27/16 10:30:00.000 PM kernel[0]: Sandbox: SampleApp(4904) deny file-read-data /
4/27/16 10:30:00.000 PM kernel[0]: Sandbox: SampleApp Helpe(4906) deny mach-lookup org.chromium.Chromium.rohitfork.4904
4/27/16 10:30:00.000 PM kernel[0]: Sandbox: SampleApp Helpe(4907) deny mach-lookup org.chromium.Chromium.rohitfork.4904
4/27/16 10:30:10.000 PM kernel[0]: Sandbox: SampleApp(4904) deny file-read-data /Users/hp011235/Library/Preferences/com.apple.symbolichotkeys.plist
4/27/16 10:30:54.994 PM com.apple.xpc.launchd[1]: (com.apple.WebKit.Networking.F5886699-8067-4CA8-AFC9-85E95424E390[1377]) Service exited with abnormal code: 1
4/27/16 10:30:55.032 PM com.apple.xpc.launchd[1]: (com.apple.WebKit.WebContent.C180C26E-6BB4-4D81-8393-DDE7AECD20FC[1378]) Service exited with abnormal code: 1
`

This is the error stack appearing in my Console.

**Comment by hp011235** [comment]
Seems like this problem is a know one in electron: https://github.com/electron/electron/issues/3871
