### ISSUE TITLE
An example how to build full portable exe file on windows OS

### ISSUE THREAD

**Issue by JaLe29** [electron-userland/electron-builder#3612]
I am trying to build a simple demo app for download and unzip the file from internet.

I am using one external library called `unzipper`.

When I build app to exe file and start it, I am getting error 'Uncaught Error: Cannot find module 'unzipper'.

My build property in package.json is:

```
"build": {
		"win": {
			"target": [
				{
					"target": "portable",
					"arch": [
						"x64",
						"ia32"
					]
				}
			]
		},
		"files": [
			"electron/**/*",
			"node_modules"
		]
	}
```

What is wrong? How can I create one exe file including all node_modules libs?

**Comment by meekaah** [comment]
my first guess would be that you have unzipper set in your dev dependencies an not actual dependencies?
