### ISSUE TITLE
Auto-update fails with ENOENT: no such file or directory, rename

### ISSUE THREAD

**Issue by aguynamedben** [electron-userland/electron-builder#3622]
* **Version**: 
electron-builder@20.38.3
electron-updater@4.0.6

* **Target**: macOS 10.14.2

We're seeing an error after the update is downloaded. This error is different from others open issues because it's on **rename**, not chmod.

```
Error: ENOENT: no such file or directory, rename '/Users/username/Library/Application Support/Caches/tesla-updater/pending/temp-Command E-1.2.22-mac.zip' -> '/Users/username/Library/Application Support/Caches/tesla-updater/pending/Command E-1.2.22-mac.zip'
```

Our flow: The user hits a keyboard shortcut, we run `autoUpdater.checkForUpdates();`. Note: the user may hit they keyboard shortcut a lot of times (triggering parallel downloads?) The download starts. The download finishes, and we call `autoUpdater.quitAndInstall();`:

```js
  autoUpdater.on('update-downloaded', (updateInfo) => {
    log.info(`autoUpdater - Version ${updateInfo.version} downloaded, notify, quitting, installing, and relaunching`);

    const notification = new Notification({
      title: `Restarting Command E`,
      body: `Updating to version ${updateInfo.version}`,
    });
    notification.show();

    setTimeout(() => {
      log.info(`autoUpdater - Quitting and installing now`);
      autoUpdater.quitAndInstall();
    }, 3000);
  });
```

Here's the full error:

![image](https://user-images.githubusercontent.com/107841/51557174-081f2380-1e31-11e9-8137-526912b56f0d.png)

Any ideas? Thanks for the work you put into this amazing library.

**Comment by aguynamedben** [comment]
After reading https://github.com/tutao/tutanota/issues/1032, I'm curious: Is it okay to call `autoUpdater.checkForUpdates();` multiple times? How does electron-updater avoid race conditions? We're currently calling `autoUpdater.checkForUpdates();` every time a user hits a keyboard shortcut. Normally this will be infrequent, but the user may hit the shortcut many times in a row, triggering many `autoUpdater.checkForUpdates();`.

**Comment by aguynamedben** [comment]
Also: This seems like an intermittent problem. Many times, the next time `autoUpdater.checkForUpdates();` runs everything works fine and the app can update.

**Comment by aguynamedben** [comment]
Sometimes this error is intermittent (i.e. autoupdate fails the first few tries, then eventually works), but other times it seems to block our users persistently (i.e. several tries of running `autoUpdater.checkForUpdates();` continue to fail with this error).

**Comment by TheFeelTrain** [comment]
I am having this same issue in my application on both Windows and Linux as well.

Error: ENOENT: no such file or directory, chmod '/home/thefeeltrain/.cache/soonlauncher-updater/pending/temp-soonlauncher-4.4.1.AppImage'

This is also a copy of #3526

**Comment by erickmaynard** [comment]
I am still having this issue in 21.2.0

**Comment by janzelinka** [comment]
same issue here

**Comment by sanzog03** [comment]
when you use both `autoUpdater.autoDownload = true;` and 
```
autoUpdater.on("update-available", info => {
 autoUpdater.downloadUpdate();
});
```` in same code, both code tries to dowload the updates. Hence, a conflict arises when trying to install and quit the app.
> so, set `autoUpdater.autoDownload = false;` and everything will work as it's supposed to.

**Comment by douglassllc** [comment]
**Version:**

- electron-builder@22.9.1
- electron-updater@4.3.5

**Target:** macOS 10.12.6

`autoUpdater.autoDownload = false` is set

Still experiencing this issue

<img width="632" alt="electron-updater-issue" src="https://user-images.githubusercontent.com/2228700/144638111-9ada12b0-b836-4227-9333-688f85e0baf6.png">
