### ISSUE TITLE
Error on windows updates - spawn setup.exe EACCES

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#3623]
* **Version**: builder v20.38.5 and updater v4.0.6

* **Target**: `--win --x64 --ia32`

See the following test application as an example:
https://github.com/kspearrin/electron-updater-issue

Hi @develar ,
I have donated in hopes of raising the priority on this issue. It is creating a bit of a large problem with our app that we are trying to release updates to.

Our apps current production version uses Electron v3.0.13, electron-builder v20.31.2, and electron-updater v3.0.3. Whenever we published an update of our app, all users now get the following error whenever the `update-downloaded` event runs:

```
autoUpdater.on('update-downloaded', (info) => {
   autoUpdater.quitAndInstall(false, true);
});
```

```
Uncaught Exception:
Error: spawn C:\Users\me\AppData\Roaming\electron-updater-example\__update__\electron-updater-example-web-setup-2.0.1.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

![capture](https://user-images.githubusercontent.com/1190944/51558614-e41e0b00-1e4d-11e9-8895-bf366438c6d8.PNG)

This problem seems to only occur on Windows. It didn't error on macOS, but I have yet to test Linux.

I guess it is a permissions issue. Running the application in administrator mode solves the problem, but this is not a good solutions for thousands of users of the application currently.

This looks like a similar issue: https://github.com/electron-userland/electron-builder/issues/3480

We've also tried publishing an update which upgrades electron-builder to the latest v20.38.5 and electron-updated to v4.0.6, but the same problem still occurs. I believe the broken version is currently in production, so I am not sure how repair this problem for the thousands of users currently using the broken version.

**Reproduction steps**

Using the sample app at: https://github.com/kspearrin/electron-updater-issue/releases

1. [Download and install version v2.0.0](https://github.com/kspearrin/electron-updater-issue/releases/download/v2.0.0/electron-updater-example-web-setup-2.0.0.exe). This version uses builder v20.31.2, and updater v3.0.3
2. Run the application. It will try to update to [v3.0.1](https://github.com/kspearrin/electron-updater-issue/releases/download/v3.0.1/electron-updater-example-web-setup-3.0.1.exe). This version uses builder v20.38.5 and updater v4.0.6.
3. Observe the error.

You can see that this problem was resolved in the latest builder/updater versions by first installing v3.0.0 and seeing it successfully update to v3.0.1. Both of these use the latest builder v20.38.5 and updater v4.0.6.

----------

How do we repair this problem for our existing users on the broken version so that they can automatically update without having to run the application in administrator mode? This would create a support nightmare if users have to manually work around this error.

**Comment by SRDigisolutions** [comment]
Same issue here!

**Comment by kspearrin** [comment]
@SRDigisolutions Did you find a fix for production versions that are already affected?

**Comment by SRDigisolutions** [comment]
@kspearrin No i had to force them to download a new version in this case.

**Comment by kspearrin** [comment]
@develar Before I go through the pain of dealing with the support consequences of pushing our next update out with this problem, I figured I would ask one last time if you had any suggestions on a workaround to this problem? Thanks.

**Comment by agjs** [comment]
@develar We are having the exact same issue. Would appreciate the response. Thanks :)

**Comment by damianobarbati** [comment]
Anybody solved this? 
All my app users are stuck in an infinite loop of autoupdate!

Having:
```
Cannot run installer: error code: EACCES, error message: "spawn C:\Users\damians\AppData\Local\<myapp>\pending\<myapp>.exe EACCES", will be executed again using elevate if EACCES"
```

My deps:
```
    "dependencies": {
        "auto-launch": "^5.0.5",
        "better-console": "^1.0.1",
        "electron-log": "3.0.9",
        "electron-updater": "^4.2.0",
        "lodash": "^4.17.15",
        "luxon": "^1.21.3",
        "mz": "^2.7.0",
        "node-machine-id": "^1.1.12",
        "sleep-promise": "^8.0.1",
        "typeface-arimo": "^0.0.72",
        "ws": "^7.2.0"
    },
    "devDependencies": {
        "electron": "^7.1.3",
        "electron-builder": "21.2.0",
        "electron-debug": "3.0.1",
        "electron-notarize": "^0.2.1",
        "eslint": "^6.7.2",
        "png2icns": "^0.0.1"
    }
```

**Comment by michaelsogos** [comment]
HI @SRDigisolutions 

Any news about this?

**Comment by justinireland** [comment]
Bump

**Comment by jackple** [comment]
+1

**Comment by nuryagdym** [comment]
+1

**Comment by tofishes** [comment]
+1

**Comment by nikitakls** [comment]
+1

**Comment by npc1437** [comment]
+1

**Comment by xiesantao** [comment]
+1

**Comment by anyaoqi** [comment]
+1

**Comment by jackple** [comment]
@kspearrin have you fixed this problem?

**Comment by DaengDo** [comment]
+1

**Comment by saif-o99** [comment]
+1

**Comment by juruo221** [comment]
+1

**Comment by jaeilnet** [comment]
+1

**Comment by zhaojunyan9528** [comment]
+1

**Comment by zhaojunyan9528** [comment]
配置electron-builder：
```
win: {
  ...
  requestedExecutionLevel: 'requireAdministrator'
},
portable: {
  requestExecutionLevel: 'admin'
}
 ```
 这样就可以了
