### ISSUE TITLE
EXE reported as  virus

### ISSUE THREAD

**Issue by distributev** [electron-userland/electron-builder#3628]
and for sure there is no virus / malware inside the exe. 

Below you find more details about this behaviour.

**_Symantec Endpoint_** interfered so I uninstalled it and tried **_AVAST antivirus_** which refuses to let the EXE sending any emails until AVAST is turned off completely.

I couldn't add an exception in AVAST because the EXE creates a new executable file in a different temporary folder every time it runs.  This drove AVAST antivirus crazy.  It would "ALERT" and scan this "new" EXE and then said it was clean, but it won't let it send any emails.

**_Is there a way to specify the location of the temporary executable file that is created so that at least I can add that as an exception to AVAST?_**

**Comment by pgupt** [comment]
I am facing the same issue.
