### ISSUE TITLE
create-self-signed-cert -CertStoreLocation error

### ISSUE THREAD

**Issue by lucaspojo** [electron-userland/electron-builder#3636]
Electron-builder : 20.38.5
Electron :  4.0.2

Error ouput : Missing arguments for CertStoreLocation.
loejf2\Desktop\yyysoft-2.0\dist\jemdoloke.pfx" -CertStoreLocation

How to fix it ? thx

**Comment by Vbubblery** [comment]
the same problem, no one cares about it?
