### ISSUE TITLE
Electron builder resigning other binaries included in extrafiles

### ISSUE THREAD

**Issue by msdos621** [electron-userland/electron-builder#3637]
* **Version**:  20.28.4
Today in our application we bundle a partner's exe as part of extraFiles.    
```json
"build": {
    "mac": {
      "category": "public.app-category.utilities",
      "extraFiles": [
        "bin/mac/**/*"
      ]
    },
    "win": {
      "publisherName": "Redacted Technologies, Inc",
      "certificateSubjectName": "Redacted Technologies, Inc",
      "extraFiles": [
        "bin/win/**/*"
      ]
    },
```

The problem we have is that the code signing process seems to blow away the signature from our partners .exe file and replaces it with our code certificate.  Here is a screenshot of the signature before we build and a picture of the signature of the version that ends up installed
<img width="818" alt="beforeafter" src="https://user-images.githubusercontent.com/882850/51757611-d3f66d80-2091-11e9-87fc-8ed63561604d.png">

Is there anyway to exclude files form being signed or perhaps a way to ignore extraFiles completely during signing?

**Comment by hrishabhkumar** [comment]
Is there any update on how to skip the signing of already signed binaries?
