### ISSUE TITLE
autoUpdater with Gitlab -- odd sign in error

### ISSUE THREAD

**Issue by flabbyThoroughbred** [electron-userland/electron-builder#3638]
Using: 

- electron 1.8.5
- electron-builder 20.29.0
- electron-updater 3.1.3

Building for OSX

I've been getting a weird error when I compile and run my app. When it checks for updates I get:

`
Error: HttpError: 401 Unauthorized
"You need to sign in or sign up before continuing."
`

I am building and updating through a private gitlab repository and only until recently have I been getting this problem. At first I thought it was a access token issue, so I updated my access token. Still nothing. I can't seem to figure out at what point in the process it wants authentication. My only other guess is that there's something wrong with the provided feed URL.
However, I have other apps that I've built to similar (if not exact) spec that have no problems and consistently work.
There is literally nothing different about the methodology that I've employed here and other working, updating apps.

Has anyone encountered this error before whether using a generic provider or github, etc? I am at a loss.

Thanks!

**Comment by flabbyThoroughbred** [comment]
As is usually the case when I exhaust all options and go to the last resort of posting in a forum, I figure out the problem almost immediately after.
All is well!

**Comment by osenvosem** [comment]
@flabbyThoroughbred So, what was the solution?

**Comment by flabbyThoroughbred** [comment]
My apologies for not providing a response. 
In this case the problem was that I did not have a sufficient certificate with which to build. I had to purchase an apple developer ID and go through the proper code signing procedure in order for it work.
