### ISSUE TITLE
AutoUpdater creates the update.AppImage file instead of replacing it

### ISSUE THREAD

**Issue by hugetiny** [electron-userland/electron-builder#3639]
* **Version**: 
Electron:4.0.2
Electron-builder:20.38.5

* **Target**: 
AppImage

AutoUpdater creates the update.AppImage file instead of replacing it
Related issue:https://github.com/hugetiny/negibox/issues/3

**Comment by Lakshman1996** [comment]
Hey @hugetiny, i have similar issue. Were you able to find a workaround or any other possible solutions.

**Comment by gorilla-devs** [comment]
Same issue here

**Comment by hugetiny** [comment]
@Lakshman1996 not yet

**Comment by slmarcos** [comment]
Has anyone found a solution?
