### ISSUE TITLE
any way to make the installer register to run at system startup ?

### ISSUE THREAD

**Issue by talarari** [electron-userland/electron-builder#364]
i'm developing a productivity app that's kind of like spotlight on a mac, i want it to automatically run on system startup (windows mostly) .
so when i restart my pc i don't need to manually start it again.

**Comment by develar** [comment]
Google it. First result — https://www.npmjs.com/package/auto-launch

**Comment by talarari** [comment]
saw this, was wondering if there's something built in with electron-builder.
thanks! i'll use auto-launch module.

**Comment by develar** [comment]
@talarari Not possible, because in case of DMG user just copy app to any location and run. So, the only correct (reliable, cross-platform) solution is to handle it on an application-level.
