### ISSUE TITLE
Cannot install sqlite3 on windows

### ISSUE THREAD

**Issue by abolfazl-moeini** [electron-userland/electron-builder#3643]
Hello

I'm using electron-prebuilt 1.4.13 and electron-builder 20.38.5.
After installing electron-builder and sqlite3 using the npm install --save-dev electron-builder sqlite3
command, when I run install-app-deps  command i got the following erron on Windows 10 OS.

Please Help Me.
> install-app-deps

  • please use as subcommand: electron-builder install-app-deps
  • electron-builder version=20.38.5
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> sqlite3@4.0.6 install C:\assets\build\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\assets\build\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\assets\build\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v1.4' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v1.4-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and electron@1.4.13 (electron-v1.4 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Abolfazl\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\assets\\build\\node_modules\\sqlite3\\lib\\binding\\electron-v1.4-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\assets\\build\\node_modules\\sqlite3\\lib\\binding\\electron-v1.4-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v1.4"
gyp ERR! cwd C:\assets\build\node_modules\sqlite3
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\assets\build\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\assets\build\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v1.4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\assets\build\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\assets\\build\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\assets\build\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abolfazl\AppData\Roaming\npm-cache\_logs\2019-01-28T14_57_16_640Z-debug.log

    at ChildProcess.childProcess.once.code (C:\assets\build\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at _rebuild (C:\assets\build\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\assets\build\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\assets\build\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\assets\build\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\assets\build\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\assets\build\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (C:\assets\build\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\assets\build\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at main (C:\assets\build\node_modules\electron-builder\src\cli\install-app-deps.ts:65:10)
    at Object.<anonymous> (C:\assets\build\node_modules\electron-builder\src\cli\install-app-deps.ts:70:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

Please note that every thing works fine on ubuntu OS.

Regards.

**Comment by sankarcheppali** [comment]
Please verify that you have Visual C++ build environment

https://github.com/nodejs/node-gyp#installation

**Comment by tarikhagustia** [comment]
same here :( any solution ?

**Comment by Jsonzhang0215** [comment]
I use electron version 3.1.1 have same problem.
But i found the following issue `node-sqlite3`

https://github.com/mapbox/node-sqlite3/issues/1056](https://github.com/mapbox/node-sqlite3/issues/1056)

In other words, ` node-sqlite3` not support all versions of electron.

I change link at browser want to find a useable link. 

Finally, `https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v3.0-win32-x64.tar.gz` download success.

So i change electron to 3.0.16 build pass.

I hope it will help you.

**Comment by wuno** [comment]
@Jsonzhang0215 Can you provide a little more information? You show a download to a binary and you said you changed your build to 3.0.16, how did you determine that was the correct Electron build to use? 

Also, is there a solution to this for Electron 5? 4 maybe? 

I have been trying to build sqlite3 on Windows 10 and have failed or a week straight.

**Comment by wuno** [comment]
I got it working with exactly what @Jsonzhang0215 said. 

> "sqlite3": "4.0.6",
> "electron": "3.0.16"

I am really not understanding why node-pre-gyp can not access the binding for the latest versions. I would think that is something that a lot of people would like to have fixed. 

At the very least if we could have some documentation to show us which versions of Electron support which versions of sqlite3 so we can use the most recent versions possible if we really wanted latest.

**Comment by GeraldLow** [comment]
Hi, any solution for this issue?

**Comment by develar** [comment]
Duplicates #2792

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/2792#issuecomment-504883376

**Comment by ebmbook** [comment]
Revert to "electron": "3.0.16" will fix this issue but will generate you more errors.  The best solution for me was to uninstall NodeJS and install it back.

**Comment by junioressono** [comment]
Hello at all,
I've same issue since two days. Please @ebmbook can you let us know wich node version you are using ?

**Comment by junioressono** [comment]
Super for me !!!
1 - I've downgraded my Node to LTS version
2 - npm i -g electron-builder
3 - use specifics versions of libs
"dependencies": {
    "sqlite3": "^4.0.9",
    "electron": "^5.0.6"
  },
  "devDependencies": {
    "electron-rebuild": "^1.8.5"
  }
4 - npm install

And bingo !!!

Thanks a lot for you and in particular to @natearmagost
https://github.com/mapbox/node-sqlite3/issues/1163#issuecomment-512080209

**Comment by rokkoo** [comment]
I solve it, removin a reinstalling phyton and them installing C++ packages from Visual Studio installer.
