### ISSUE TITLE
Unable to create windows version build on macOS using -mw option.

### ISSUE THREAD

**Issue by sourabhChourasiya** [electron-userland/electron-builder#3644]
**Dependencies**

"electron": "^3.0.6",
"electron-builder": "^20.38.4",
"node" : 10.15.0
"vue": "^2.3.3",
"vue-electron": "^1.0.6",
"electron-updater": "^4.0.4",

**Target**

macOS and Windows

```
    "mac": {
      "target": [
        "dmg",
        "zip"
      ],
      "icon": "icons/icon.icns",
      "identity": "identity",
      "artifactName": "Application.${ext}"
    },
    "publish": {
      "provider": "generic",
      "url": "https://www.test.com",
      "publishAutoUpdate": true,
      "channel": "latest"
    },
    "win": {
      "target":["nsis"],
      "icon": "icons/icon.ico",
      "artifactName": "Application.${ext}",
      "certificateSubjectName": "subject Name",
    }
```

**Requirnment**

I am trying to create windows version build on macOS system using **electron-builder -mw** option.

**Command to create build**
**npm run electron-builder -mw**

**Issue**

The above command is able to generate **.dmg** file but as it starts to build for windows it gives following error and terminates the operation.

```
packaging       platform=win32 arch=x64 electron=3.0.13 appOutDir=build/win-unpacked
  ⨯ Get https://github.com/electron/electron/releases/download/v3.0.13/electron-v3.0.13-win32-x64.zip: proxyconnect tcp: dial tcp :0: connect: can't assign requested address
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:167
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:200
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:75
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:191
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:171
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:71
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333
```

**Comment by ceharsh24** [comment]
You need Wine to build apps for windows on MacOS.

**Comment by sourabhChourasiya** [comment]
@ceharsh24 I tried with Wine as well but got the same error.

**Installed wine form:** https://wiki.winehq.org/MacOS

**XQuartz-2.7.11**
**wine-4.0**

is there anything need to be added with the electron-builder command?

**Comment by ceharsh24** [comment]
"win": {
      "publish": {
        //Your Publish Code 
      },
      "certificateFile": /CertificateName,
      "verifyUpdateCodeSignature": false,
      "publisherName": "Your Company Name/Product Name",
      "target": {
        "target": "nsis",
        "arch": [
          "x64",
          "ia32"
        ]
      }
    },
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false,
      "perMachine": true,
      "uninstallDisplayName": "/Uninstaller Name"
    },


- This is what I am using to build win32 & win64 on my mac.
- I am doing it with wine-3.0.3.

I hope this will fix your issue. If not, do let me know.

**Comment by sourabhChourasiya** [comment]
@ceharsh24 
Tried the suggested configuration, but unfortunately, the result was same.
I am not getting any clue that what am i missing here to add on?
is anything need to be added with the electron-builder command? my current command is:

**DOTENV_CONFIG_PATH=./.env.production node -r dotenv/config .electron-vue/build.js && electron-builder -mw**

The prompted error looks like electron builder is unable to download some file from the given URL in the error, Is it? As it is showing

```
packaging       platform=win32 arch=x64 electron=3.0.13 appOutDir=build/win-unpacked
  ⨯ Get https://github.com/electron/electron/releases/download/v3.0.13/electron-v3.0.13-win32-x64.zip:
proxyconnect tcp: dial tcp :0: connect: can't assign requested address
```


This is my **win** config now

```
    "win": {
      "publish": {
        "provider": "generic",
        "url": "https://aws.com/release/windows",
        "publishAutoUpdate": true,
        "channel": "latest"
      },
      "target": {
        "target": "nsis",
        "arch": [
          "x64",
          "ia32"
        ]
      },
      "icon": "icons/icon.ico",
      "artifactName": "Application.${ext}",
      "certificateSubjectName": "subject name",
      "certificatePassword":  "password"
    },
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false,
      "perMachine": true
    },
```

**Comment by sourabhChourasiya** [comment]
I added **NO_PROXY=*** (https://github.com/electron-userland/electron-builder/issues/2665) in the build command that resolved the current issue.


But now facing another issue related to code sign **certificateSubjectName** token (code sign via USB Token). I will create another ticket for the same if needed.

@ceharsh24 Thanks for your help.

Closing this ticket.

**Comment by sourabhChourasiya** [comment]
Hello @ceharsh24 

Are you aware of the below error related to wine?

As i can see that there is an open issue related to the same (https://github.com/electron-userland/electron-builder/issues/3562)

I upated the electron-builder to latest one

**"electron-builder": "^20.38.5"**

**XQuartz-2.7.11
wine-4.0**

```
error output:wine: failed to initialize: dlopen(/tmp/wine-stage/wine/usr/lib/wine/ntdll.dll.so, 258): image not found

github.com/develar/app-builder/pkg/util.Execute
        /Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
        /Volumes/data/Documents/app-builder/pkg/wine/wine.go:75
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
        /Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:78
runtime.main
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201
runtime.goexit
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333
```

**Comment by ceharsh24** [comment]
Update your xcode and see if that fixes or not. And also, I can not see certificate configuration in your code. I think you need a certificate as well to build windows installer on mac. You can get one from keychain app on mac. You need .pfx file for windows. Later for production you need it from apple or windows itself.

**Comment by sourabhChourasiya** [comment]
I am using webStrom, not Xcode. will this make any difference?

I have to certificates for both mac and windows.
mac certificate is available in keychain and in **identity** key in config as well, which is working fine and getting auto detected by the electron builder for macOS.

For window, the certificate is installed in the **USB Token 5110** provided by digicert, also written in **win** config in **certificateSubjectName** (as suggested here: https://www.electron.build/configuration/win#WindowsConfiguration-certificateSubjectName ) which is working fine when building on windows system, now when building on macOS it is giving the error relate to wine posted in above comment.

```
"mac": {
      "target": [
        "dmg",
        "zip"
      ],
      "icon": "icons/icon.icns",
      "identity": "identity",
      "artifactName": "Application.${ext}"
    },
 "win": {
      "target":["nsis"],
      "icon": "icons/icon.ico",
      "artifactName": "Application.${ext}",
      "certificateSubjectName": "certificate Name",
    }

```

**Comment by ceharsh24** [comment]
I did some research and couldn't find much. The only solution I see is related to the Xcode version. If you are on MacOS Mojave, make sure you have updated the Xcode 10.1. I think that will fix your problem. And even I use WebStorm and VSCode, but to build on Mac, XCode required.

**Comment by sourabhChourasiya** [comment]
Okay, let me check this one after updating the Xcode.
