### ISSUE TITLE
Linux AppImage: Passing command-line flags to underlying electron app

### ISSUE THREAD

**Issue by livnev** [electron-userland/electron-builder#3647]
I asked this question in the `AppImageKit` repo but they recommended I try here: https://github.com/AppImage/AppImageKit/issues/917

I'm trying to run an Electron app distributed as an AppImage and I'd like to pass a command line flag to the underlying (Electron) app. In my particular case, I'd like to pass `--disable-gpu` to Electron to work around a well bug in Electron's hardware acceleration: no Electron apps work unless this flag is supplied. Is there a way to do this, or a way to get the `.AppImage` to do this?

**Comment by dabo248** [comment]
@livnev did you find a solution to this?

**Comment by livnev** [comment]
@dabo248 sadly, no (as far as I recall).

**Comment by vladimiry** [comment]
@dabo248 you can repack the AppImage thing with added `./AppRun` patching, like https://github.com/vladimiry/ElectronMail/blob/a53ff3b84046ad1aad63fb6b54ccc602e48c75be/scripts/electron-builder/build-appimage.ts#L11-L27

**Comment by dabo248** [comment]
I made a small mistake, so it works now for my use case: passing custom arguments to an .AppImage (`./xyz.AppImage --test`) and accessing them in Electron's main process with `process.argv`.
