### ISSUE TITLE
Update for version 4.0.1 is not available (latest version: 1.1.1901200, downgrade is disallowed).

### ISSUE THREAD

**Issue by gclsoft** [electron-userland/electron-builder#3648]
20.38.4 
electron: 4.0.1

```
Update for version 4.0.1 is not available (latest version: 1.1.1901200, downgrade is disallowed).
```
How to prevent this check for update? My own check url is : 
`    autoUpdater.setFeedURL('https://m.xxx.com/');
    autoUpdater.checkForUpdates();
`

**Comment by TrueSlu** [comment]
Also coming across this issue.

**Comment by lanweihong** [comment]
Can you solve the problem? I also encountered this problem.

**Comment by zouye** [comment]
这个问题应该是electron-updater的bug，解决办法就是：主动设置当前版本
 // 设置当前版本,必须主动设置否则，有bug会去取electron的版本,而不是app的版本
 autoUpdater.currentVersion = config.version
 // 设置更新地址
 autoUpdater.setFeedURL(config.autoUpdateURL)
.............

**Comment by w602542704** [comment]
> autoUpdater.currentVersion = config.version

非常棒！(๑•̀ㅂ•́)و✧

**Comment by ccc-chan** [comment]
config是从哪里来的？
