### ISSUE TITLE
Command failed winCodeSign makepri.exe (since 20.33.1)

### ISSUE THREAD

**Issue by mirka** [electron-userland/electron-builder#3654]
* **Version**: [20.33.1](https://github.com/electron-userland/electron-builder/releases/tag/v20.33.1) thru 20.38.5 (It was working up to 20.32.0)

* **Target**: AppX

Starting in version 20.33.1, [our appx build fails](https://ci.appveyor.com/project/Automattic/simplenote-electron/builds/21860675/job/kvbgo00lbqu2cj91) with this error:

```
  • building        target=AppX arch=ia32 file=release\Simplenote-win-1.3.4-ia32.appx
Error: Exit code: 2148008452. Command failed: C:\Users\appveyor\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\windows-10\ia32\makepri.exe new /Overwrite /Manifest C:\projects\simplenote-electron\release\__appx-ia32\AppxManifest.xml /ProjectRoot C:\projects\simplenote-electron\release\__appx-ia32\appx /ConfigXml C:\projects\simplenote-electron\node_modules\app-builder-lib\templates\appx\priconfig.xml /OutputFile C:\projects\simplenote-electron\release\__appx-ia32\resources.pri
```

All of our other targets (dmg, nsis, linux, and also unsigned appx) are unaffected.

Do you have any idea what may be causing this? I'm wondering if it's related to this commit → https://github.com/electron-userland/electron-builder/commit/76fdd42

**Comment by belcherj** [comment]
I think that error code means that the manifest is invalid: "The Appx package's manifest is invalid"
