### ISSUE TITLE
autoUpdater not using the custom provider

### ISSUE THREAD

**Issue by hxx0215** [electron-userland/electron-builder#3656]
* **Version**:
**  electron-builder:20.32.0
** electron-updater:3.1.7
#

* **Target**: OSX and Windows

I try to use the custom provider. It can builder normally. But when I use autoUpdater it will say "Unsupported provider: custom"
I read the source code in the source code of [providerFactory.ts](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/providerFactory.ts). I found it does not support the custom provider. What can I do to make autoUpdater to use my provider?

**Comment by W1M0R** [comment]
I also have this issue.
