### ISSUE TITLE
Why now packaging use electron 3.1.3?

### ISSUE THREAD

**Issue by gbonline** [electron-userland/electron-builder#3658]
* **Version**: 
20.38.4

* **Target**: 
cross compiling from linux to win

I followed the instructions on your site to cross compiling or build package in linux for win10 with docker image and wine. and all goes well.
Yesterday I made the build with the command 

yarn dist --win

and in the packaging information I got electron version 4.0 and builder downloaded the "electron-v4.0.3-win32-x64.zip" . And the building process gone well

Today, a few minutes ago, I made a new build but the packaging information say "electron=3.1.3" and downloaded the "electron-v3.1.3-win32-x64.zip"
and the build goes well. But I don't have changed anything on my configuration files like packages.json

In the image the output of last "yarn dist" command
why this downgrade ?
![senzanome](https://user-images.githubusercontent.com/3273873/52131410-ff9ec800-263c-11e9-8a1c-8431a6b4a01c.png)

**Comment by arik555** [comment]
How can I use electron version 2.0.17 instead of electron=3.1.3 ? Can we change that parameter while excuting the builder? Please help.

**Comment by johanpoirier** [comment]
@arik555 yes: https://www.electron.build/configuration/configuration#Configuration-electronVersion
