### ISSUE TITLE
User confusion with DMG file.

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#3661]
Hey there, I've noticed after some update, the DMG file has the same icon as the application itself. This is confusing a lot of our users into thinking that its the app. They then open the app inside the mounted Volume and the auto-updater doesn't work. This causes an app update popup to appear every time they open the app annoying them.

These aren't tech savvy people -- the problem is with the UX of installing an app built with electron builder. How can we improve this to reduce confusion?

1. I think it would be helpful if the Volume did not have an icon. Hopefully the `{dmg: {icon: false}}` would fix that, or maybe point it to an invalid place?

2. It might help to have some instruction inside the .dmg that says to right-click and eject after moving into the applications folder.

3. I see `internetEnabled` says it will put the Application on the Desktop and unmount the Volume immediately after downloading. That's another option.

4. Perhaps we could give users the .zip version of the app. Is there any particular reason to use a .dmg file?

Any thoughts? Thanks.

https://www.electron.build/configuration/dmg

**Comment by meekaah** [comment]
i would agree an option to not supply an icon would be pretty useful

**Comment by ccorcos** [comment]
The following works for me:

```json
{
  "build": {
    "dmg": {
      "icon": false
    }
  }
}
```

**Comment by meekaah** [comment]
oh ok i didnt try that, ill give it a go thx

**Comment by douglassllc** [comment]
Has anyone gotten the internetEnabled option to work.  Everything builds, but when I download the DMG using a browser I don't get the automatically decompress of the image.  Or the application is not set on the desktop, unmount and remove the disk image file.

Most important would be the ability to unmount the disk after the install.  User are getting confused and attempting to click on the disk volume icon on the desktop to start the application.

Any recommendation would be appreciated.
