### ISSUE TITLE
Desktop file for Linux not generated with AppImage

### ISSUE THREAD

**Issue by MyTheValentinus** [electron-userland/electron-builder#3662]
* **Version**: 
20.38.5

* **Target**: 
Linux AppImage

After lot of test, the .desktop file for AppImage target is not generated.
I try multiple methods, create my own .desktop file, not create etc..
No problem on `deb` target.

**Comment by MyTheValentinus** [comment]
After some research and deep debug, it's causing to the default Artifact Name with space.
On some linux distros, if you have a space inside your AppImage name, the .desktop is refused by system and not created.
To fix, change artifact name to remove space and apparently work normaly now.
```json
"linux": {
      "target": [
        {
          "target": "AppImage"
        }
      ],
      "maintainer": "Valentin DEVILLE",
      "category": "AudioVideo",
      "artifactName": "${productName}-${version}.${ext}",
      "desktop": {
        "Name": "${productName}",
        "Terminal": "false"
      }
    },
```

**Comment by MyTheValentinus** [comment]
I suggest you to change the default generated var with removed space.

Thanks

**Comment by hugetiny** [comment]
@MyTheValentinus  I had the same problem, how to solve this?

**Comment by hugetiny** [comment]
@MyTheValentinus I tried to add the "Categories" option ,but still not work

**Comment by MyTheValentinus** [comment]
Hello @hugetiny,
Remo any space and slash from your productName.
Thanks

**Comment by hugetiny** [comment]
If i add "artifactName": "${productName}-${version}.${ext}",the generated AppImage will be failed to execute

**Comment by hugetiny** [comment]
"artifactName": "${productName}${arch}${version}.${ext}" works!

**Comment by MyTheValentinus** [comment]
In my case this, work: 

```json
"linux": {
      "target": [
        {
          "target": "AppImage"
        }
      ],
      "maintainer": "Valentin DEVILLE",
      "synopsis": "App qui permet d'écouter Radio 50/50",
      "category": "AudioVideo",
      "artifactName": "PlayerRadio50_50-${version}.${ext}",
      "desktop": {
        "Name": "Radio 50/50 Player",
        "Terminal": "false"
      }
    },
```
```

**Comment by hugetiny** [comment]
yes,in order to let multi-targets works,I have to add ${arch} for different bundles

**Comment by MyTheValentinus** [comment]
A comment, just to keep this issue open

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/releases/tag/v21.0.1

**Comment by weiluenju** [comment]
It is possible to modify or get the filename of desktop file?

Because the filename of desktop file AppImageLauncher created is not equal to name in package.json.

(The filename is start with appimagekit_[random string]-[name in package.json].desktop)

This will lead to the menu bar show the name in package.json, not the Name in desktop file.

(OS: Ubuntu 20)

**Comment by marf** [comment]
Hello, I do not understand if we can include a .desktop file or if now it is handled by AppImageLauncher do you have some documentation regarding this?
