### ISSUE TITLE
Nested content is missing from the bundled application if folder is named as `node_modules`

### ISSUE THREAD

**Issue by kittaakos** [electron-userland/electron-builder#3665]
* **Version**: 
`electron-builder@20.38.5`

* **Target**: 
`dmg`

I would like to include a `lib` folder in a bundled application. The `lib` folder has the following structure:
```
lib/
  |
  +-- foo.txt
  |
  +-- node_modules/ (#note, this is not a real node_modules folder, it's just the name and I do not have control over it)
  |    |
  |    +-- bar.txt
  |    
  +-- other/
        |
        +-- baz.txt
```

My final app will contain the `lib` folder with the `foo.txt` and `other` (with the `baz.txt`) but the `node_modules` folder with the nested `bar.txt` will be missing. Perhaps this is due to the `node_moduels` folder name but I am just guessing. I have the following `build` config in my `package.json`.

```json
"build": {
    "files": [
      "app/**/*",
      "lib/**/*"
    ],
    "asar": false,
    "publish": null
  }
```

I have set up a [sample repository](https://github.com/kittaakos/foo-bar) for it. Steps to reproduce:
 - `git clone https://github.com/kittaakos/foo-bar.git`
 - `cd foo-bar && npm i`
 - `cd dist/mac/foo-bar.app/Contents/Resources/app/lib/ && ls -al` (on macOS)

`foo.txt` and `other` are in the `lib` folder, but the nested `node_modules/bar.txt` is not there. I would like to include it as is, if possible.

What am I doing wrong? Thank you!

**Comment by richjun** [comment]
I have same issue.

**Comment by tjfryan** [comment]
Also getting this issue

**Comment by tjfryan** [comment]
As a temporary workaround, I found that using a fileset instead of a glob can include these folders, but it's kinda gross and is likely harder the more 'node_modules' folders you want to include

```
"files": [
  ...,
  {
    "from": "path/to/node_modules",
    "to": "path/to/node_modules",
    "filter": ["**/*"]
  }
],
```

**Comment by grantcv1** [comment]
I'm using the technique suggested by @tjfryan. The thing to realize, as alluded to, is that you cannot use file globbing in your from and to paths. Instead, you must specify a separate fileset for every node_module folder you need to include. It's a messy workaround.
