### ISSUE TITLE
Ability to detect packaging format.

### ISSUE THREAD

**Issue by burtonator** [electron-userland/electron-builder#3668]
I'm trying to package for the Microsoft App Store so I need to disable updates since that platform does it by itself.

I just need a simple way to test the packaging format.  If it's appx I would just disable the update menu item.

I don't think this is possible right now though.  Went through all the docs and couldn't find anything.

**Comment by ZudoMC** [comment]
Seconded, I'm looking to release on Windows Store as well, disabling updates is a necessity.

**Comment by burtonator** [comment]
one thing I was looking at is whether there's a way to inject variables into the electron builder process.  I don't think this is supported.

If this was a feature then I could just inject my own variables... like APPX=true

**Comment by burtonator** [comment]
Also, I looked at process.env from within my app and there aren't any env vars that I could use to detect that Im running from the MS App Store.

**Comment by ZudoMC** [comment]
Maybe you could work it out from `process.execPath`? See if it contains anything.

**Comment by dimitarnestorov** [comment]
`process.windowsStore`
