### ISSUE TITLE
.mas build not packaging icon.icns

### ISSUE THREAD

**Issue by daniellizik** [electron-userland/electron-builder#3670]
* **Version**: 20.38.3

* **Target**: mas, platform=darwin arch=x64 electron=2.0.6

I read through [this](https://github.com/electron-userland/electron-builder/issues/3284) but it wasn't much help. My setup is:

**project structure**
```
embedded.provisionProfile
Certificates.p12
package.json
build
  icon.icns
  entitlements.mas.plist
src
  index.js
```

**package.json build object**
```
    "directories": {
      "buildResources": "build",
      "output": "dist"
    },
    "mac": {
      "target": "mas",
      "entitlements": "./build/entitlements.mas.plist",
      "icon": "./icon.icns"
    },
    "mas": {
      "type": "distribution",
      "category": "public.app-category.productivity",
      "entitlements": "./build/entitlements.mas.plist",
      "icon": "./icon.icns"
    }
```
I can see my icon configuration is correct in the output via `export DEBUG=electron-osx-sign*`

```
path resolved    outputFormat=icns path=/Users/daniellizik/source/app/build/icon.icns
```

When I check the package contents for the .app build everything seems fine:

**Info.plist**
```xml
<key>CFBundleIconFile</key>
<string>app.icns</string>
```

**file structure**
```
Contents
  Resources
    app.icns
```

However, when I extract the .pkg build via `xar -xf app.pkg` and open `PackageInfo` in vim I only get this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<pkg-info overwrite-permissions="true" relocatable="false" identifier="com.company.app" postinstall-action="none" version="1.0.0" format-version="2" generator-version="InstallCmds-667 (17G4015)" install-location="/Applications" auth="root" preserve-xattr="true">
    <payload numberOfFiles="228" installKBytes="127653"/>
    <bundle path="./app.app" id="com.company.app" CFBundleShortVersionString="1.0.0" CFBundleVersion="1.0.0"/>
    <bundle-version>
        <bundle id="com.company.app"/>
    </bundle-version>
    <upgrade-bundle>
        <bundle id="com.company.app"/>
    </upgrade-bundle>
    <update-bundle/>
    <atomic-update-bundle/>
    <strict-identifier>
        <bundle id="com.company.app"/>
    </strict-identifier>
    <relocate>
        <bundle id="com.company.app"/>
    </relocate>
</pkg-info>
```

The result is

<img width="113" alt="screen shot 2019-02-07 at 18 45 42" src="https://user-images.githubusercontent.com/10506366/52403235-9ec63280-2b09-11e9-865e-0eb70782106c.png">

xcode 10.1 application loader is complaining about this and I cannot submit to the app store

<img width="457" alt="screen shot 2019-02-07 at 18 53 34" src="https://user-images.githubusercontent.com/10506366/52403294-bd2c2e00-2b09-11e9-9648-038cb6aadd87.png">

anybody else have any luck?

**Comment by Qiplex** [comment]
Same here. @daniellizik were you able to resolve this? 

<img width="668" alt="screen shot 2019-02-14 at 23 24 02" src="https://user-images.githubusercontent.com/32670415/52818524-ad838b00-30af-11e9-8a04-97fe227c9027.png">

**Comment by Qiplex** [comment]
@daniellizik i was able to resolve this after correctly regenerating @2x icon (1024x1024)  

> try creating a 1024x1024.png then using this script to generate your icon:
> 
> https://github.com/jamf/icns-Creator/blob/master/icns_creator.sh

**Comment by daniellizik** [comment]
@Qiplex ah I see...so electron-builder is not packaging the icon because it's not formatted correctly. I'll try again and let you know, thank you!
