### ISSUE TITLE
Auto-update appears to work but does not on macOS 10.12.6

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron-userland/electron-builder#3675]
* **Version**: 
* electron-builder v20.38.5
  electron-updater v4.0.6
  https://github.com/signalapp/Signal-Desktop/blob/development/package.json#L116

* **Target**: 
macOS

A user on macOS 10.12.6 cannot auto-update from Signal Desktop v1.21.0 to v1.21.1, both using the above builder/updater versions. They get a popup telling them to update, they hit 'restart', the app closes and restarts, but it's still on the previous version.

Their update-related logging suggests that it should be working:

```
Checking for update
Found version 1.21.1 (url: signal-desktop-mac-1.21.1.zip)
Downloading update from signal-desktop-mac-1.21.1.zip
updater cache dir: /Users/cjappl/Library/Application Support/Caches/signal-desktop-updater
Update has already been downloaded to /Users/cjappl/Library/Application Support/Caches/signal-desktop-updater/pending/signal-desktop-mac-1.21.1.zip).
/ requested
/1549666686205-7243.zip requested
/1549666686205-7243.zip requested by Squirrel.Mac, pipe /Users/cjappl/Library/Application Support/Caches/signal-desktop-updater/pending/signal-desktop-mac-1.21.1.zip
Proxy server for native Squirrel.Mac is closed (was started to download https://updates.signal.org/desktop/signal-desktop-mac-1.21.1.zip)
2019-02-08 14:58:12.277 Signal[13081:77063715] action buttonPressed:
2019-02-08 14:58:12.523 Signal[13081:77063715] action _close:
```

But I suppose it is missing a confirmation that the file was downloaded by Squirrel.

Let me know if you have any other ideas for data we could collect on this.

Signal Desktop issue: https://github.com/signalapp/Signal-Desktop/issues/2107#issuecomment-461975891

**Comment by cjappl** [comment]
Here to provide any more info if you need it! Thanks for looking into it
