### ISSUE TITLE
MAS testing

### ISSUE THREAD

**Issue by fdrwld** [electron-userland/electron-builder#3679]
* **Version**: 
20.38.4

* **Target**: mas, mas-dev

Hi,
first of all, thanks for your great work with electron. )

I'm trying to upload my app to Apple Store. App is sandboxed, no crash reporter and auto updater is disabled. Building for dmg and pkg (not mas) targets works fine, but after uploading mas file, Apple Store responses with "app crashes on launch" with no errors/ no logs provided.

So 1) can you clarify difference between pkg, mas and mas-dev targets, is it related only with certificate type that is used for signing (Developer ID Application / 3rd Party Mac Developer Application)?

And 2) is there any way to run MAS build locally, before uploading it to the Store (maybe with specific dev certificate)? Building for mas-dev target, app signing fails with "no valid identity with this name in the keychain". 

Thank you in advance.

**Comment by vasyl-shumskyi** [comment]
Subscribed

**Comment by vasyl-shumskyi** [comment]
#3702
