### ISSUE TITLE
macOS: incorrect cache directory used for updates

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron-userland/electron-builder#3680]
* **Version**: 
  electron-builder v20.38.5
  electron-updater v4.0.6
  https://github.com/signalapp/Signal-Desktop/blob/development/package.json#L116

* **Target**: 
macOS

Cache is `~/Library/Application Support/Caches/signal-desktop-updater/`
But should be:  `~/Library/Caches/signal-desktop-updater/`

Why is this a problem? `~/Library/Caches/` is excluded from backups with Time Machine, excluded from search indexing, and the system will handle purging out old files automatically.

Original bug: https://github.com/signalapp/Signal-Desktop/issues/3132

**Comment by abarsov** [comment]
faced the same issue, it is still relevant
