### ISSUE TITLE
Set productName based on environment variable

### ISSUE THREAD

**Issue by alekplay** [electron-userland/electron-builder#3682]
This isn't as much of a bug or issue report as it is a question or feature request. I want to change the `productName` of my application based on an environment variable. 

I've tried using a [File Macro](https://www.electron.build/file-patterns#file-macros) in my `electron-builder.json` like so:

    "productName": "Application Name ${env.NETWORK_TYPE}",

But it actually builds as `Application Name ${env.NETWORK_TYPE}`, despite the variable being set. Is there a way for me to dynamically adjust the product name without writing a bash script to replace it?

**Comment by sanoopjose** [comment]
Any solution for this issue?

**Comment by djfyaci** [comment]
How to Solve the Problem？

**Comment by djfyaci** [comment]
Set parameters like this on the command line：
`electron-builder --win --x64 --config.productName=newName`

**Comment by lars-wobus** [comment]
> Set parameters like this on the command line：
> `electron-builder --win --x64 --config.productName=newName`

I am sorry for re-opening this issue.
But I want to share a proper solution.
@djfyaci's solution was almost right!

For anyone who come to this place: Don't forget the additional `--` in between!
 `electron-builder --win --x64 -- --config.productName=newName `

**Comment by dgana** [comment]
Actually i have a successful build with using @djfyaci solution
