### ISSUE TITLE
Don't set GitHub Releases draft title

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#3683]
* **Version**: 20.38.5

* **Target**:  macOS

When using auto-publishing to GitHub Releases, it creates a new release draft and sets the title to the version number. This is moot as GitHub will fall back to the tag name when no title is set, which *is* the version number.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
@stalebot We've been seeing each other for a while now. I think it's time you met my parents.

**Comment by LuKks** [comment]
We just need to remove line 210, right? `name` is optional: [/v3/repos/releases/#create-a-release](https://developer.github.com/v3/repos/releases/#create-a-release)
https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/electron-publish/src/gitHubPublisher.ts#L207-L214

`createRelease` is used here:
https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/electron-publish/src/gitHubPublisher.ts#L133-L139

Assuming that `this.options.publish` in `always` is the auto-publish option.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by mmaietta** [comment]
Hi @sindresorhus , please give this a shot. You can use [patch-package](https://www.npmjs.com/package/patch-package) to always have this patch applied as a `postinstall` hook.
Filename `electron-publish+22.10.5.patch`
```
diff --git a/node_modules/electron-publish/out/gitHubPublisher.js b/node_modules/electron-publish/out/gitHubPublisher.js
index 75e5ca2..e24f0f7 100644
--- a/node_modules/electron-publish/out/gitHubPublisher.js
+++ b/node_modules/electron-publish/out/gitHubPublisher.js
@@ -273,7 +273,7 @@ class GitHubPublisher extends _publisher().HttpPublisher {
   createRelease() {
     return this.githubRequest(`/repos/${this.info.owner}/${this.info.repo}/releases`, this.token, {
       tag_name: this.tag,
-      name: this.version,
+      // name: this.version,
       draft: this.releaseType === "draft",
       prerelease: this.releaseType === "prerelease"
     });

```
That should deactivate the draft title per the earlier comment.

**Comment by sindresorhus** [comment]
Thanks, but it's not important enough to deal with `patch-package`. I just manually remove the title until this is properly fixed `electron-builder`.

**Comment by sindresorhus** [comment]
Please keep this open.

**Comment by sindresorhus** [comment]
Please keep this open.
