### ISSUE TITLE
electron-updater not finding correct downloads/repo url

### ISSUE THREAD

**Issue by jyoung295** [electron-userland/electron-builder#3689]
* **Version**: 20.28.4

* **electron-updater Version**: 4.0.6

* **Target**: Mac

I'm trying to set up auto updating, and wasn't getting any result from my tests, so I checked my logs and I'm seeing:
```
[error] Error: HttpError: 404 Not Found
"method: undefined url: https://github.com/companyNameHere/repoNameHere/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```
Originating from `MacUpdater.checkForUpdatesAndNotify` in electron-updater. I don't know why it's looking for a file named `releases.atom`.

In my package.json I'm setting up publish as:
```
"publish": {
        "provider": "github",
        "releaseType": "draft",
        "url": "https://github.com/companyNameHere/repoNameHere/releases/download/v1.1.0-beta/"
      }
```

It is a private repo, but publishing works perfectly, this only came up when I tried to implement auto updating.

**Comment by hemantsinghi** [comment]
Hi @jyoung295, did you find the solution?

**Comment by agnoam** [comment]
Hi @jyoung295 how did you solved this problem ? (if solved at all)
