### ISSUE TITLE
linux builder error

### ISSUE THREAD

**Issue by Luncher** [electron-userland/electron-builder#369]
`dev package.json`

{
  "name": "HolaStudio",
  "version": "0.0.1",
  "homepage": "http://studio.holaverse.cn",
  "description": "HolaStudio Release Version.",
  "scripts": {
    "dist": "npm run dist:linux && npm run dist:win",
    "dist:osx": "build --platform darwin --arch all -d",
    "dist:win": "build --platform win32 --arch all -d",
    "dist:linux": "build --platform linux --arch all -d"
  },
  "keywords": [
    "HolaStudio"
  ],
  "author": "holaverse Tech Inc.",
  "license": "ISC",
  "devDependencies": {
    "electron-builder": "2.11.0",
    "electron-prebuilt": "0.37.2"
  },

---  

error: 

Downloading electron-v.37.2-linux-ia32.zip
Error: GET https://github.com/atom/electron/releases/download/v.37.2/electron-v.37.2-linux-ia32.zip returned 404
[ Error: GET https://github.com/atom/electron/releases/download/v.37.2/electron-v.37.2-linux-ia32.zip returned 404
      at Request.<anonymous> (/data/LocalHolaStudio/release/node_modules/nugget/index.js:170:61)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestResponse (/data/LocalHolaStudio/release/node_modules/request/request.js:1156:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
      at TLSSocket.socketOnData (_http_client.js:359:20)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:188:7)
      at readableAddChunk (_stream_readable.js:172:18)
      at TLSSocket.Readable.push (_stream_readable.js:130:10)
      at TLSWrap.onread (net.js:535:20) ]

npm ERR! Linux 3.17.4-301.fc21.x86_64
npm ERR! argv "/home/luncher/.nvm/versions/node/v6.0.0/bin/node" "/home/luncher/.nvm/versions/node/v6.0.0/bin/npm" "run" "dist:linux"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! HolaStudio@0.0.1 dist:linux: `build --platform linux --arch all -d`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the HolaStudio@0.0.1 dist:linux script 'build --platform linux --arch all -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the HolaStudio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform linux --arch all -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs HolaStudio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls HolaStudio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/LocalHolaStudio/release/npm-debug.log

**mirror cache: **  
```javascript  
[luncher@localhost release]$ ls ~/.electron
electron-v0.37.2-darwin-x64-symbols.zip  electron-v0.37.4-darwin-x64.zip
electron-v0.37.2-darwin-x64.zip          electron-v0.37.4-linux-arm.zip
electron-v0.37.2-linux-arm.zip           electron-v0.37.4-linux-ia32.zip
electron-v0.37.2-linux-ia32.zip          electron-v0.37.4-linux-x64.zip
electron-v0.37.2-linux-x64.zip           electron-v0.37.4-mas-x64.zip
electron-v0.37.2-mas-x64.zip             electron-v0.37.4-win32-ia32.zip
electron-v0.37.2-win32-ia32.zip          electron-v0.37.4-win32-x64.zip
electron-v0.37.2-win32-x64.zip           electron-v0.37.7-linux-x64.zip
[luncher@localhost release]$ 

```

**Comment by Luncher** [comment]
Why repeat download mirror?

**Comment by Luncher** [comment]
How to set up a mirror path?

**Comment by develar** [comment]
Please try to set `electron-prebuilt` version to `0.37.7`

**Comment by Luncher** [comment]
I have no time to change this, you help me look at how to set up mirror path?

**Comment by develar** [comment]
Ah, got your problem — you use outdated version of electron-builder, right? Please try 3.13.1. 

Or if you cannot update electron-builder version, change `"electron-prebuilt": "0.37.2"` to `"electron-prebuilt": "^0.37.2"`

**Comment by develar** [comment]
Duplicates #215.

**Comment by Luncher** [comment]
What does that mean?

` change "electron-prebuilt": "0.37.2" to "electron-prebuilt": "^0.37.2"`

@develar

**Comment by develar** [comment]
See #215
