### ISSUE TITLE
fileAssociations fails on msi target

### ISSUE THREAD

**Issue by alxAgu** [electron-userland/electron-builder#3694]
* **Version**: 20.38.5

* **Target**: Windows

fileAssociations not working on msi targets. After installing the app, the files with extension .asdfgh are not recognized, works fine with nsis and dmg targets though.  Bellow my config:
```
	"build": {
		"icon": "build_resources/icon.icns",
		"directories": {
			"buildResources": "build_resources",
			"app": "myAppDir",
			"output": "dist"
		},
		"fileAssociations": [
			{
				"ext": "asdfgh",
				"name": "Alphabet File",
				"role": "Viewer"
			},
		],
		"mac": {
			"category": "public.app-category.finance",
			"target": [
				"dir",
				"dmg"
			],
			"type": "development",
			"asar": true
		},
		"win": {
			"target": [
				"dir",
				"msi",         
			],
			"icon": "build_resources/icon.ico",
			"asarUnpack": [
				"**node_modules/regedit/**"
			]
		},
}
```

**Comment by skececi** [comment]
> * **Version**: 20.38.5
> 
> * **Target**: Windows
> 
> fileAssociations not working on msi targets. After installing the app, the files with extension .asdfgh are not recognized, works fine with nsis and dmg targets though. Bellow my config:
> 
> ```
> 	"build": {
> 		"icon": "build_resources/icon.icns",
> 		"directories": {
> 			"buildResources": "build_resources",
> 			"app": "myAppDir",
> 			"output": "dist"
> 		},
> 		"fileAssociations": [
> 			{
> 				"ext": "asdfgh",
> 				"name": "Alphabet File",
> 				"role": "Viewer"
> 			},
> 		],
> 		"mac": {
> 			"category": "public.app-category.finance",
> 			"target": [
> 				"dir",
> 				"dmg"
> 			],
> 			"type": "development",
> 			"asar": true
> 		},
> 		"win": {
> 			"target": [
> 				"dir",
> 				"msi",         
> 			],
> 			"icon": "build_resources/icon.ico",
> 			"asarUnpack": [
> 				"**node_modules/regedit/**"
> 			]
> 		},
> }
> ```

I am having the same issue - did you find a way to properly associate the file type when using MSI?
