### ISSUE TITLE
Is it possible to signing to dmg, not app ?

### ISSUE THREAD

**Issue by pyeongoh** [electron-userland/electron-builder#3697]
* **Version**: 20.36.2

electron-updater version: 2.21.4

* **Target**: win: nsis(x64, ia32), mac: default( dmg )

content is same with title, is it possible to signing to dmg? not app.
I already signing on app, and It works well.
but, I faced the trouble that is the chrome browser blocked download my app even has no problem my build process (include signing my app).
So I thought I could solve it by signing app and dmg. 
please tell me know about this problem ( point is chrome blocked my app (It is already signed) )
and please tell me the way about signing on dmg

**Comment by yi-ge** [comment]
```
codesign --force --sign "Developer ID Application: <identityIdentifier>" <pathToDMG>
```

[https://stackoverflow.com/questions/23824815/how-to-add-codesigning-to-dmg-file-in-mac](https://stackoverflow.com/questions/23824815/how-to-add-codesigning-to-dmg-file-in-mac)
