### ISSUE TITLE
Appveyor, Travis and GitHub releases, existingType vs. publishingType clash

### ISSUE THREAD

**Issue by sebastian-raubach** [electron-userland/electron-builder#3699]
* **Version**: 20.19.2

* **Target**: Windows, Linux and Mac

I'm trying to build installers using electron-builder, travis-ci and appveyor.
Everything works fine, except deploying the final files to a GitHub release.
Both for Windows and Mac, the artifacts are added just fine, but for Linux, I always get this error:

```
skipped publishing file=humbug_2.19.2_amd64.deb reason=existing type not compatible with publishing type tag=v2.19.2 version=2.19.2 existingType=release publishingType=draft
```

I'm sure it must just be a setting in the configuration that needs to be set properly, but I cannot find the culprit.

The repository in question is this one:
https://github.com/sebastian-raubach/humbug-electron

If you need any further information from me, let me know!

**Comment by thomasnordquist** [comment]
The github release has to be a "draft".
`existingType=release` => indicates that your release is no longer a draft but a release.

**Comment by sebastian-raubach** [comment]
Ok, that's fair. I could only manage to get AppVeyor and Travis to trigger on an actual release though. Any tips for that?

**Comment by thomasnordquist** [comment]
Not entirely sure, maybe check the publish option:
https://www.electron.build/configuration/publish

I use "always" for my builds and only package when "$TRAVIS_TAG" is set.
