### ISSUE TITLE
Windows software update broken due to publisherName with no cert

### ISSUE THREAD

**Issue by paulshapiro** [electron-userland/electron-builder#3700]
* **Version**: 20.38.5

4.0.6

* **Target**: Windows / NSIS

A previous version of our app MyMonero (1.1.7) has a `publisherName` set in `package.json`. We didn't realize auto-update wasn't working in this version (a 404 was occurring - which is now fixed) ... and now in the new version 1.1.8, once the update downloads, the app throws an error (which then causes the app to quit - very undesirable, I must say… since it breaks the app for everyone on Windows) ... which says `"New version 1.1.8 is not signed by the application owner: publisherNames: MyMonero Pty Ltd., rawInfo: { "SignerCertificate": null, "TimeStamperCertificate", null, "Status": 2, …` . 

I've tried removing publisherName from the 1.1.8 package.json but it seems like it's grabbing publisherName from the existing version 1.1.7's config. I've also tried using `verifyUpdateCodeSignature: false` in 1.1.8 package.json but again it seems to be using the 1.1.7 config (which would make sense). 

This issue seems similar in principle to https://github.com/electron-userland/electron-builder/issues/1856 , however, we do not actually do any code signing on Windows yet.

Is there any way we can fix this issue for people on 1.1.7 so that the app doesn't quit?

**Comment by xuzhaobin** [comment]
我今天也出现了这个问题，并且没有找到解决方案。这个问题对于用户当前的应用程序是致命的，现在看来，用户只能手动下载你的1.1.8，虽然这有点糟糕。

**Comment by xuzhaobin** [comment]
你需要先推送一个1.1.7（修复后的），这样更新检查就会认为最新版本是1.1.7，你的用户就不会检查更新，暂时可以使用。但是只要推送1.1.8之后，这个问题仍然会存在。

**Comment by paulshapiro** [comment]
Do you mean pushing a fixed 1.1.7 will fix the existing installs of 1.1.7? Not sure I follow.

**Comment by xuzhaobin** [comment]
No, but it ensures that users who download 1.1.7 later won't have this problem again.

**Comment by paulshapiro** [comment]
All releases prior to the latest, 1.1.8, have the issue though, effectively, and 1.1.8 is the latest anyway. Still unsure I follow.
