### ISSUE TITLE
Windows packaging error: image must be at least 256x256 

### ISSUE THREAD

**Issue by shajeeck** [electron-userland/electron-builder#3709]
* **Version**: 20.38.5

* **Target**: Windows

Building for windows gives an error for small images `image <X> must be at least 256x256 `
found a similar closed issue: https://github.com/electron-userland/electron-builder/issues/2462

**Comment by KsAkira10** [comment]
this is error occurs when building in OS X too

**Comment by Justkant** [comment]
linux too

**Comment by crystalbyte** [comment]
I have the same issue.

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
I have the same problem using an Angular 7+ app packaged in Electron on windows.
I believe the PrimeNG user interface suite creates those images and gifs on npm build.

I tried ignoring the files in package.json, electron-builder config files but that didn't work.
My temporary solution is to delete the files after building them with **rimraf** npm package

Note this is more a hack and not a solution for the issue which is caused in electron-builder.
in **package.json:**

`"scripts":{
    "release": "npm run build:prod && 
rimraf dist/hue.0614c27197fc3ce572e1.png dist/color.c7a33805ffda0d32bd2a.png dist/line.567f57385ea3dde2c9ae.gif dist/loading.8732a6660b528fadfaeb.gif dist/password-meter.d59e6dc2616c53ce8e77.png && electron-builder build --windows",
} `

**Comment by z16166** [comment]
I have the same problem when building the following app:
https://github.com/signalapp/Signal-Desktop/


happy@ubuntu:~/Signal-Desktop$ electron-builder --version
22.3.6
happy@ubuntu:~/Signal-Desktop$ electron --version
v8.0.3
happy@ubuntu:~/Signal-Desktop$ npm --version
6.13.7
happy@ubuntu:~/Signal-Desktop$ uname -a
Linux ubuntu 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

happy@ubuntu:~/Signal-Desktop$ electron-builder build
  • electron-builder  version=22.3.6 os=5.3.0-42-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@journeyapps/sqlcipher@4.0.0, curve25519-n@1.5.0, dtrace-provider@0.8.8, fs-xattr@0.3.0, sharp@0.23.0, websocket@1.0.28 platform=linux arch=x64
  • install prebuilt binary  name=sharp version=0.23.0 platform=linux arch=x64
  • build native dependency from sources  name=sharp
                                          version=0.23.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /home/happy/.npm/_prebuilds/c9ae1f-sharp-v0.23.0-electron-v76-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.23.0/sharp-v0.23.0-electron-v76-linux-x64.tar.gz
    prebuild-install http request Proxy setup detected (Host: 192.168.2.73, Port: 8118, Authentication: No) Tunneling with httpsOverHttp
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.23.0/sharp-v0.23.0-electron-v76-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.0.3 runtime=electron arch=x64 libc= platform=linux)
    
  • packaging       platform=linux arch=x64 electron=8.0.3 appOutDir=dist/linux-unpacked
  • building        target=deb arch=x64 file=dist/signal-desktop_1.32.1-beta.1_amd64.deb
  ⨯ image /home/happy/Signal-Desktop/build/icon.ico must be at least 256x256

**Comment by Silvano14** [comment]
Why this issue is closed? I have the same problem with  
- linux mint  
- electron-builder: 22.4.1,

`  • downloaded      url=https://github.com/electron/electron/releases/download/v9.1.2/electron-v9.1.2-win32-x64.zip duration=26.295s
  ⨯ image /usr/local/apache2/icons/pie7.png must be at least 256x256
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn dist' returned a non-zero code: 1
`

**Comment by killroy42** [comment]
How can I specify smaller sizes? The downscaling to actual icon sizes makes the large images useless!
