### ISSUE TITLE
installer integrity check has failed

### ISSUE THREAD

**Issue by xiaosu95** [electron-userland/electron-builder#3710]
"version": "20.28.4"
Some users have problems
"installer integrity check has failed
nsis error"
This may be a configuration problem. Still a computer problem

**Comment by LukeXF** [comment]
@xiaosu95 did you resolve this issue?

**Comment by xiaosu95** [comment]
> @xiaosu95 did you resolve this issue?
user can solve this problem after user re-download installer package.
