### ISSUE TITLE
[Question] What will happen to console.log from main process ? 

### ISSUE THREAD

**Issue by shirshak55** [electron-userland/electron-builder#3711]
Hi,

I used to do console log from main process to log messages etc so that I can see various message related to electron application. It works properly on development as I have terminal open and console log logs all the details on terminal.

But when i use electron builder we know we don't have any terminals etc so where do those console log go? Yeah renderer log can be viewed in devtool but I am talking about main process logs. 

Do electron builder shallow the main process console logs or it get stored in some files etc? Or should i use fs module and append to some file ?

Thanks.

**Comment by yalzeee** [comment]
I haven't tried this myself, but i recall seeing somewhere that though you cant get console logs from cmd, you can from git bash command line. You should try it.

**Comment by shirshak55** [comment]
if we execute binary from command line we will get console logs otherwise it shallow the console log :)
