### ISSUE TITLE
CSSMERR_TP_NOT_TRUSTED

### ISSUE THREAD

**Issue by royheuer** [electron-userland/electron-builder#3712]
electron-builder: 20.38.5
electron: 2.0.5

Good day,

I am getting the following error:

  • signing         file=dist/mac/ReportPro.app identityName=Mac Developer: XXX (****) identityHash=**** provisioningProfile=none
Error: Command failed: codesign --verify --deep --strict --verbose=2 Test.app
Test.app: CSSMERR_TP_NOT_TRUSTED
In architecture: x86_64

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

Here is my package.json:

  "build": {
    "copyright": "Copyright © 2019 ${author}",
    "asar": true,
    "directories": {
      "buildResources": "."
    },
    "files": [
      "!node_modules/electron/**/*"
    ],
    "mac": {
      "category": "public.app-category.business",
      "target": "dmg"
    },
    "dmg": {
      "background": "background.png",
      "window": {
        "x": 540,
        "y": 380
      }
    },
    "win": {
      "target": "nsis",
      "icon": "icon.ico"
    }

Not sure what I am doing wrong? Please can you assist?

**Comment by allenlongbaobao** [comment]
i meet the same issue. did you fix this or not? any suggestions?

**Comment by bauhauce** [comment]
i meet the same issue. did you fix this or not? any suggestions?
