### ISSUE TITLE
primeng resource images with Angular app cause error - imagefilename must be at least 256x256

### ISSUE THREAD

**Issue by sandipchitale** [electron-userland/electron-builder#3716]
* **Version**: 
20.38.5

* **Target**: 
WIndows.

When I use [primeng ](https://github.com/primefaces/primeng) in a [Angular ](https://angular.io/)based Electron application some of the resources ([images](https://github.com/primefaces/primeng/tree/master/src/assets/components/images) end up in dist folder. While building I get an error that the image must be at least 256x256.

**Comment by reneszabo** [comment]
Same here !

> hue.0614c27197fc3ce572e1.png must be at least 256x256

**Comment by KsAkira10** [comment]
this is error occurs when building in OS X too

**Comment by shajeeck** [comment]
any workaround found so far? #3709

**Comment by jindalrohit** [comment]
I am facing same issue. Did you guys get any solution for this?

**Comment by unfamous31** [comment]
did any one find a solution yet ??
