### ISSUE TITLE
Github Private Repo cannot download

### ISSUE THREAD

**Issue by si-Blue** [electron-userland/electron-builder#3717]
electron-builder: 20.38.5

electron-updater: 4.0.6

Target: NSIS

I'm experiencing an error message of not found when trying to download a file update from a Github private repo. I have read over all of the related articles and made sure I am following the steps correctly. I currently have my autoUpdater.setFeedURL as follows: 

 autoUpdater.setFeedURL({ provider: 'github', owner: '*****', repo: '****', token: process.env.GH_TOKEN, private: "true" })

I have made sure that the GH_TOKEN is set appropriately and have also tried just inputting it directly to make sure it works correctly. When I attempt to check for updates, it finds the file correctly, but then I get the following error message when it actually tries to download the update:

2019-02-26 12:01:53 update: Checking for update...
2019-02-26 12:01:55 update: Update available. 
2019-02-26 12:01:56 update: Error in auto-updater. Error: Cannot download "https://api.github.com/repos/*****/****/releases/assets/11252383", status 404: Not Found

I created this same test using Postman and found that it crashes the application if I submit the header info:
Accept: application/octet-stream

If I remove this info from the request, it works correctly on Postman. When doing the same thing by editing the httpExecutor.js file and removing the header info under requestOptions, it downloads the file correctly.  Can you tell me what i'm doing wrong?

Also, the updater is trying to download the differential file even though I have my target set to just NSIS. I'm not sure if these are related, but I would like it to only download the full file each time. Is this possible?

**Comment by JohannBlake** [comment]
Auto-updater cannot download from private repos. The docs indicate this. Solution: If your source code is in a private repo, create another repo that is public. This public repo doesn't contain any of your source code but is only used to push the build file to which anyone can download.

**Comment by sostenesapollo** [comment]
I thik that i did not understand, can you show the step by step to do this ?
