### ISSUE TITLE
AppX target ignores fileAssociations

### ISSUE THREAD

**Issue by bartcich** [electron-userland/electron-builder#3718]
* **Version**: 20.38.5

* **Target**: AppX

When building AppX target - file associations aren't generated. Nsis and build for mac works ok.

It looks that generated AppxManifest.xml file doesn't contain any information about file associations that should look like [this](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation)

**Comment by danielweck** [comment]
We're experiencing the same problem. Any news at your end, @bartcich?

**Comment by danielweck** [comment]
I implemented a fix in this PR: https://github.com/electron-userland/electron-builder/pull/4302
