### ISSUE TITLE
Generated windows installer is not an installer

### ISSUE THREAD

**Issue by mikew** [electron-userland/electron-builder#372]
Using this command to build an installer for my app:

```bash
build --appDir public/ --dist --platform win32 --arch x64
```

Everything works, but launching the "installer" on windows just opens my app and another instance of ... something with Electron's `install-spinner.gif`. After a few seconds my app is relaunched, but once it's quit there's no sign of the installation.

**Comment by develar** [comment]
@mikew Works for me. But I guess, maybe is a regression. Could you please send me your app is possible and I will check?

**Comment by develar** [comment]
And please check that you handle https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by mikew** [comment]
It was an issue with my handling of squirrel events. I adapted the code from the "real example" in the readme and everything works.
