### ISSUE TITLE
artifactName configuration example should be more clear

### ISSUE THREAD

**Issue by netroby** [electron-userland/electron-builder#3721]
The document should provided us more detail about `artifactName ` configuration.
If we built AppImage , the output file name default was `appname 0.1.1.AppImage`
There is a space here, It will broken all the linux system intergrate.

The correct file name should be
```

    "artifactName": "${name}-${version}-${os}.${ext}",
```

No space, but this not describe at the document. 
I waste a few days to dig this problem out. very very hard work

**Comment by selurvedu** [comment]
Bump
