### ISSUE TITLE
cannot move downloaded into final location (another process downloaded faster?) error=rename 

### ISSUE THREAD

**Issue by yalzeee** [electron-userland/electron-builder#3722]
"electron-builder": "^20.38.5"

Not using electron updater
**Target**:  Windows
Running electron builder on windows 10 Home

build process cannot package and presents this error
cannot move downloaded into final location (another process downloaded faster?) error=rename C:\Users\Developer\AppData\Local\electron-builder\Cache\winCodeSign\105845327 C:\Users\Developer\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0: Access is denied. path=C:\Users\Developer\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0 tempFile=C:\Users\Developer\AppData\Local\electron-builder\Cache\winCodeSign\105845327

I have tried to run the process with an administrative window, but still presents the error.
I would appreciate any help

**Comment by yalzeee** [comment]
Fixed the issue, turns out it was my anti-virus that was stopping my files from being moved. Took me weeks to figure this out and drove me crazy a bit. If you're having this issue try disabling your anti-virus for a bit and see if it works for you too

**Comment by gajet5** [comment]
Use administrator rights on the console.

**Comment by vineetpsat** [comment]
just disable anti virus. It works for me.
