### ISSUE TITLE
Electron white screen issue

### ISSUE THREAD

**Issue by amolngt** [electron-userland/electron-builder#3723]
Hello all,

I am facing blank white screen  issue.. when electron runs for long time(2-3 days) .... my node-electron(v1.7.16) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

Please Help

**Comment by MarshallOfSound** [comment]
Closing as this user is spamming comments and issues across multiple repositories.
