### ISSUE TITLE
Travis CI Build Number & CFBundleVersion prevent App Submission

### ISSUE THREAD

**Issue by thomasnordquist** [electron-userland/electron-builder#3730]
* **Version**: 20.38.5

* **Target**: mas

Travis increments build numbers, last build number in my case is *316*
My App version is 0.2.2

While submitting the app to the AppStore with the `Application Loader`, ther validation fails since it only supports versions with three version numbers. 

0.2.2 => OK
0.2.2.1 => Not OK

It seems the build number is ammended to the version.

After reading this:
https://www.electron.build/configuration/configuration#build-version-management
it appears that using the `TRAVIS_BUILD_NUMBER` will lead to store-incompatible builds.

```
ERROR ITMS-90257: "This bundle is invalid. The value for key CFBundleVersion [0.2.2.316] in the Info.plist file must be a period-separated list of at most three non-negative integers."
```

Building locally avoids this issue.

**Comment by mahnunchik** [comment]
It is **not** stale!

**Comment by roshan00123** [comment]
@thomasnordquist have you found any solution on this? 
@mahnunchik any idea on this?
