### ISSUE TITLE
Cannot extract publisher name from code signing certificate: error: exit status 1 (Windows)

### ISSUE THREAD

**Issue by iffy** [electron-userland/electron-builder#3731]
* **Version**: 20.38.5

* **Target**: Windows 10

```
  • electron-builder version=20.38.5
  • loaded configuration file=C:\proj\app\config_beta.js
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=3.0.10 appOutDir=dist\win-unpacked
Cannot extract publisher name from code signing certificate: error: exit status 1
path: \\vboxsrv\project\cache\electron-cache\winCodeSign\winCodeSign-2.4.0\openssl\openssl.exe
args: \\vboxsrv\project\cache\electron-cache\winCodeSign\winCodeSign-2.4.0\openssl\openssl.exe pkcs12 -in C:\proj\csc_link.p12 -passin sha512-first-8-chars-6ba2e434 -nokeys
output: 
error output:WARNING: can't open config file: /usr/local/ssl/openssl.cnf
5784:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:.\crypto\asn1\tasn_dec.c:1220:
5784:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:.\crypto\asn1\tasn_dec.c:386:Type=PKCS12
```

Why do you think it's looking for `/usr/local/ssl/openssl.cnf` on a Windows box?

**Comment by iffy** [comment]
I've tracked the problem down to this `certificate-info` command in this Go package: https://github.com/develar/app-builder/blob/master/pkg/codesign/p12.go#L26

I suspect [this `log.Debug(...)` line](https://github.com/develar/app-builder/blob/master/pkg/codesign/p12.go#L50) ought to be running, but I don't see that output.  I wonder where it logs to?  Looks like maybe I can enable it by setting `DEBUG` env var to [something](https://github.com/develar/app-builder/blob/master/pkg/log-cli/cli.go#L15).  I'll try that.

Anyway it looks like it calls [`DecodeAllCerts` from develar/go-pkcs12](https://github.com/develar/go-pkcs12/blob/54baa4f32c6a1a1f2ee3d634c676330c43264610/decoder.go#L7) which I suspect is failing for some reason and which is why app-builder reverts to trying with openssl.

**Comment by kri5t** [comment]
I had the same issues as you, but when I upgraded the package to 20.39.0 (yarn add electron-builder@20.39.0) the issue disappeared and the app is now getting code-signed. Maybe this helps you too?

I am not running mine in a Virtual Box though.

**Comment by iffy** [comment]
Turns out I was using the wrong blob of text for the certificate (CSC_LINK).  I was base64 *encoding* the cert instead of base64 *decoding* it :)
