### ISSUE TITLE
MAS - How to add or change values in info.plist

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron-userland/electron-builder#3732]
Versions: 

- electron-builder `20.38.5`
- macOS Mojave `10.14.3`
- electron `4.0.7`

I have the app which reads user data folder recursively including user _Photos_ folder.  

Apple rejected the app because of the security warning. 

I found the screenshot of the warning for **VS Code** for better understanding:

![46212840-456a1d80-c337-11e8-9060-cc2bbb0fe8e3](https://user-images.githubusercontent.com/2331802/53974414-36b83b80-410b-11e9-80a4-a15e944d62b7.png)

> Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
> 
> 
> We noticed that your app requests the user’s consent to access their photos but does not clarify the use of this feature in the applicable purpose string.
> 
> Next Steps
> 
> To resolve this issue, please revise the purpose string in your app’s Info.plist file to specify why the app is requesting access to the user's photos. You can modify your app's Info.plist file using the property list editor in Xcode.
> 
> The permission request alert should specify how your app will use this feature to help users understand why your app is requesting access to their personal data.
> 
> Resources
> 
> For additional information and instructions on requesting permission, please review the [Requesting Permission](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/requesting-permission/) section of the macOS Human Interface Guidelines and the [Information Property List Key Reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18). You may also want to review the [Technical Q&A QA1937: Resolving the Privacy-Sensitive Data App Rejection](https://developer.apple.com/library/archive/qa/qa1937/_index.html) page for details on how to provide a usage description for permission request alerts.
> 
> Learn more about Protecting the User’s Privacy.
> 
> Please see attached screenshot for details.

I will greatly appreciate if someone can let me know what is correct way in to add or change values in `info.plist` to overcome the rejection?

Thanks a lot! 

More info: [Information Property List Key Reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18)

/cc @develar @sethlu

**Comment by sethlu** [comment]
The [Information Property List Key Reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18) linked looks a little outdated 🤔

I guess, following the rejection notes, you'll need to add [NSPhotoLibraryUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsphotolibraryusagedescription?language=objc) to your `Info.plist`... To specify extra items to the plist, here's the a [related usage note for `electron-builder`](https://www.electron.build/configuration/mac):

> - `extendInfo` any - The extra entries for `Info.plist`.

**Comment by vasyl-shumskyi** [comment]
@sethlu you are life saver! I must have missed this option...
