### ISSUE TITLE
App works when I run "npm start", but does not work after packaging

### ISSUE THREAD

**Issue by hugeprestigellc** [electron-userland/electron-builder#3734]
Hi, I'm on macOS, using the latest version of Electron, Electron Builder, etc. When I run my Electron app using npm start, it works fine. But when I package it up using npm run dist, and then run the app, the app no longer works properly. 

It shows my index.html but none of the config data loads/displays. After researching this a bit, I'm thinking that perhaps the config files and other .js files are not getting packaged up for some reason.

The app is really simple. It just loads some data from a config file and displays it on index.html at the moment. All files are in the root folder (excluding anything in the node_modules folder) 

The documentation on files was kind of hard to understand. Do I need to specify exactly which files/folders get packaged up in package.json? Or is everything packaged up by default?

Thank you.

**Comment by kitattyor** [comment]
Did you find out what happened?
