### ISSUE TITLE
Proton-native with native dependency (keytar) packaged app fails on windows 

### ISSUE THREAD

**Issue by yrik** [electron-userland/electron-builder#3736]
Here is the sample app http://github.com/yrik/broken-native.
It consists of a basic app made with `create-proton-app` and keytar as a dependency (`npm i --save keytar`). I have built it on appveyer (see conf inside) for win x86. The result is not functional, it throws an error. 

<img width="483" alt="Screen Shot 2019-03-09 at 9 51 13 AM" src="https://user-images.githubusercontent.com/394729/54068903-ce27a680-4251-11e9-955c-4e55a2b75825.png">

Here is build log:
[broken-log.txt](https://github.com/electron-userland/electron-builder/files/2948240/broken-log.txt)

* **Version**: latest
* **Target**: windows (x86)

**Comment by yrik** [comment]
I have rebuild it with adding of `"postinstall": "electron-builder install-app-deps",` and now I have different error:

`The specified procedure could not be found`

<img width="475" alt="Screen Shot 2019-03-09 at 10 06 08 AM" src="https://user-images.githubusercontent.com/394729/54069005-198e8480-4253-11e9-8e25-a5db010ef6e1.png">

Build log: [broken-log.txt](https://github.com/electron-userland/electron-builder/files/2948247/broken-log.txt)

**Comment by develar** [comment]
Please try 21.0.11
