### ISSUE TITLE
[Feature Request] loadingGif Initialization Time

### ISSUE THREAD

**Issue by daviseford** [electron-userland/electron-builder#374]
Hey folks, I have a feature request for you.

I read somewhere a couple days ago (can't find it now) that the build.win.loadingGif is only called after x number of seconds - it's only supposed to show for "big" installations.

I'd like to make sure that the loadingGif shows immediately to our users - I'd like to bypass the 3-4 second delay before the loadingGif shows.

Reason: On Windows, we have a lot of users complaining about the setup process.

They doubleclick setup.exe, and there's no indication of activity from the OS - it just looks like it's hanging, or waiting on the user. A lot of users end up clicking the setup again and occasionally creating errors.

Solution: I'd like to be able to specify an option in my package.sjon underneath "loadingGif"

ex.

"win":{
       "loadingGif": "/path/to/gif/",
       "gif_delay": 100 // 100 milliseconds
}

**Comment by REEMERGEMEDIA** [comment]
+1
I'd like to be able to show a custom image on screen during the installation process so users know that something is going on.

**Comment by develar** [comment]
> I'd like to be able to show a custom image on screen during the installation process 

See https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-loadingGif

> AnimatedGifWindow.ShowWindow(TimeSpan.FromSeconds(4), animatedGifWindowToken.Token, progressSource);

Yes. 4 seconds. Please see https://github.com/Squirrel/Squirrel.Windows/issues/77 and comment there.

"I'll probably lower this to maybe 2sec, but I don't really want it to be configurable, if people want a non-custom number, they can use their fork"

It means that: please double check that you handle Squirrel events correctly — "either Squirrel events are being handled incorrectly".


If it will be still actual for you, I will make PR to Squirrel.Windows. But please note — author of Squirrel.Windows doesn't want to accept such PR.

**Comment by daviseford** [comment]
Thanks develar! I commented on the issue. Really hope this feature can work

**Comment by develar** [comment]
@daviseford Did you check — do you handle Squirrel.Windows events correctly? If so and if you still has this issue, I will fix it. But please note — I don't want to do if just because issue is opened — please ensure that it is really needed and no error on your side.

**Comment by daviseford** [comment]
I did check, and Squirrel.Windows events are handled correctly. I'd just like to be able to reduce the 4 second loading time :)

Thanks so much!

**Comment by develar** [comment]
Delay is removed. It is not possible to fix it correctly — currently, Squirrel.Windows bootstrap (pure C++) extract animation gif, update.exe and package and only then starts update.exe. Well, if some user doesn't like it — just use OS X.

**Comment by kunkinkan** [comment]
Is the animation delay removed on windows 32 bit too? I tried it there and it takes quite a while for that loading gif to show up, in fact, it shows up AFTER the app is installed and RUNNING! (And then quickly disappears again) Annoying!

**Comment by develar** [comment]
@kunkinkan Don't forget about the rest of my comment — *It is not possible to fix it correctly — currently, Squirrel.Windows bootstrap (pure C++) extract animation gif, update.exe and package and only then starts update.exe (net45).* You can expect true progress bar in the upcoming NSIS installer.

**Comment by abuhenasobuj** [comment]
It's will be very good feature.
We can this feature to introducing our apps by GIF Animation.
Eg:
First I want to show an splash screen that took nearly 10 sec then installation will start & finished in few sec.

**Comment by develar** [comment]
@abuhenasobuj Just use NSIS target (default now).
