### ISSUE TITLE
Empty folders not packaged

### ISSUE THREAD

**Issue by vasiltabakov** [electron-userland/electron-builder#3740]
* **Version**: 20.39.0
* **Target**: 7z

When packing empty folders are not included in the archive (.7z) file or in the -unpacked fodler (e.g. win-unpacked).

This is causing an issue because even if it's empty the folder should exist so our app functions properly. For now we're thinking of adding some dummy file inside the folder to mitigate the issue.

Is this a config thing or a bug ?

**Comment by LaNsHoR** [comment]
This issue is still present 22.9.1. I would be good to have a fix for it, the workaround of adding dummy files works but that's not a valid solution in some scenarios.

**Comment by jcnmsg** [comment]
The problem persists on 22.14.5 as well, even with a dotfile like `.gitkeep` inside.
