### ISSUE TITLE
Unpacked directory of mac on windows

### ISSUE THREAD

**Issue by Armaldio** [electron-userland/electron-builder#3741]
* **Version**: ^20.38.5

* **Target**: Mac on Windows

This is a question.

I'm wondering if it's possible to build an unpacked directory with electron-builder.
I know I cannot make installers for mac, like dmg, but since it's possible with windows while on windows and it's possible with electron-packager, I'm wondering if it's possible with electron-builder too.

**Comment by meekaah** [comment]
sorry AFAIK you can't build any macOS app / dmg / pkg on platforms other than macOS
