### ISSUE TITLE
Electron Updater doesn't like server response headers for multipart byterange

### ISSUE THREAD

**Issue by obsius** [electron-userland/electron-builder#3742]
* **Version**: 20.39.0
* **Updater Version**: 4.0.6
* **Target**: NSIS

Doing a delta request to Digital Ocean Spaces.  Updater is configured properly and works with the delta updates off.

I was getting this error:
`Content-Type "multipart/byteranges" is expected, but got "application/octet-stream"`

so I changed my server header to match and then got this error:

`Content-Type "multipart/byteranges" is expected, but got "multipart/byteranges"`

which makes no sense.

So I see that `multipleRangeDownloader.ts` has this block of code:
```ts
    const contentType = safeGetHeader(response, "content-type")
    const m = /^multipart\/.+?(?:; boundary=(?:(?:"(.+)")|(?:([^\s]+))))$/i.exec(contentType)
    if (m == null) {
      reject(new Error(`Content-Type "multipart/byteranges" is expected, but got "${contentType}"`))
      return
    }
```

The server is returning a `Content-Range`, and I think that's to spec, so I don't know why this code is only checking `Content-Type` when `Content-Range` is a valid response.

I think this server response should be acceptable, but Electron Updater doesn't agree:
```
HTTP/1.1 206 Partial Content
Content-Length: 57891
Content-Range: bytes 154514-212404/50262321
Accept-Ranges: bytes
Last-Modified: Tue, 12 Mar 2019 11:14:40 GMT
Content-Type: application/octet-stream
Date: Tue, 12 Mar 2019 11:35:35 GMT
```

**Comment by obsius** [comment]
Closing, I see now that there's an option to send out single requests: useMultipleRangeRequest = false

**Comment by SinusPi** [comment]
Still, the multiple-range downloader shouldn't fall back to a full download if multiple ranges aren't supported, or a single range was requested and served.
