### ISSUE TITLE
Windows Build Signing certificateFile field won't pull web resources

### ISSUE THREAD

**Issue by dbhagen** [electron-userland/electron-builder#3746]
* **Version**: 20.38.5
electron-builder-squirrel-windows: 20.39.0

* **Target**: Windows

I'm trying to set up a multiplatform build. Linux and Mac are fine, but now using a DigiCert code-signing cert for Windows Squirrel builds and I can't get it to work like the other platforms.

First, for the record, if I set c.win.certificateFile to a local cert.p12 file and set `$WIN_CSC_KEY_PASSWORD` to the unlock password, the build succeeds properly.

When I change c.win.certificateFile to a Google drive direct download link (as mentioned in this page, search for "direct": https://www.electron.build/code-signing), I get this during signing:
```
Error: ENOENT: no such file or directory, open 'https://drive.google.com/uc?export=download&id=<REMOVED FOR CONFIDENTIALITY>'
    at _bluebirdLst.default.map.it (/Users/user/Projects/new-electron-webpack-project/node_modules/app-builder-lib/out/util/cacheManager.js:151:98)
```

If I take out c.win.certificateFile and put in it's place c.win.cscLink with the same URL, it appears to download the file but then (keep in mind `$WIN_CSC_KEY_PASSWORD` is still set) I get:
```
Error: Exit code: 255. Command failed: /Users/user/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/darwin/10.12/osslsigncode -in /Users/user/Projects/new-electron-webpack-project/dist/win-unpacked/AppName.exe -out /Users/user/Projects/new-electron-webpack-project/dist/win-unpacked/AppName-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /private/var/folders/sg/_n7wfn852qd6n36fp2_79fwm0000gn/T/t-VeaPvf/0.p12 -h sha1 -n AppName -i https://github.com/<removed>/<removed>/blob/master/README.md -pass <HASH> (sha256 hash) to parse PKCS#12 file: /private/var/folders/sg/_n7wfn852qd6n36fp2_79fwm0000gn/T/t-VeaPvf/0.p12 (Wrong password?)
4745868908:error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure:p12_kiss.c:119:
```

Sections of packages.json:
```
  "build": {
    "appId": "com.appname",
    "forceCodeSigning": true,
    "extends": null,
    "files": [
      "src/**/*",
      "node_modules/**/*",
      "package.json",
      "LICENSE.md",
      "README.md"
    ],
    "directories": {
      "buildResources": "resources"
    },
    "win": {
      "timeStampServer": "http://timestamp.digicert.com",
      "cscLink": "https://drive.google.com/uc?export=download&id=<removed>",
      "target": "Squirrel",
      "icon": ""
    },
    "nsis": {
      "oneClick": true,
      "installerIcon": "",
      "uninstallerIcon": ""
    }"
```

**Comment by dbhagen** [comment]
The boy marked this as stale. Anyone have any thoughts on this issue?

**Comment by develar** [comment]
Have you tried google drive direct link generator https://sites.google.com/site/gdocs2direct/?

**Comment by dbhagen** [comment]
Yes, I'm using direct  links. I removed the ID from the config, but it correctly downloads the certificate.
