### ISSUE TITLE
electronVersion is not computed from electronDist

### ISSUE THREAD

**Issue by bughit** [electron-userland/electron-builder#3747]
* **Version**: 20.39.0

* **Target**: dir

https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/electron/electronVersion.ts#L47

It ends up doing an unnecessary and incorrect request to github.com/electron/electron/releases/latest

If the version is (potentially) needed when specifying electronDist, it should be computed from electronDist, if it's not needed the computation should be skipped.

**Comment by Vanisper** [comment]
The issue still persists. Is there any willingness to discuss it again? @mmaietta 🙏
https://github.com/electron-userland/electron-builder/blob/8e1c7ff1883103cc26b28d70b34d1a1bcc8ebd9e/packages/app-builder-lib/src/electron/ElectronFramework.ts#L164-L177

The `electronDist` configuration exists in `configuration`, so ElectronDist can be considered in this stage.

The core challenge is that `electronDist` is processed too late. To fix this, we need to move it to an earlier stage.

---

Here is the call stack during debugging:

<img width="1080" height="256" alt="Image" src="https://github.com/user-attachments/assets/2e2ad7d6-0b58-4368-874a-37d3228205cb" />

---

However, I've realized this may not be a defect. Also, a custom "electronDist" could run the risk of lacking strict versioning.
And, I've found that electronVersion can be customized.

This issue generates **context** and **logs** that do not match reality (about `electronVersion`).
So far, I have found no breaking issues.

**Finally, thanks for your contribution!**

**Comment by mmaietta** [comment]
AFAIK, it's not possible to properly calculate the version from the `electronDist` without CLI w/ the electron executable. We can't do this most notably because that can't be emulated easily for cross-platform packaging.

How would you suggest computing the true electron version from an electron zip file or raw electron output directory? Both methods need to be supported.

**Comment by Vanisper** [comment]
Thank you for the reply. @mmaietta 

There are two versions of electron installed in my project, one of which is installed using an alias:

<img width="600" height="800" alt="Image" src="https://github.com/user-attachments/assets/2ba0e840-f1a3-4148-804c-29bc5ddff6bd" />

As shown in the figure above, the standard electron package's dist directory will store a version file.

Of course, this is the product of the postinstall execution script for the standard electron package.
> https://github.com/electron/electron/blob/7961206fcb78691195d42ab08d43652b6cf951dd/npm/install.js#L42-L53
```js
downloadArtifact({
  version,
  artifactName: 'electron',
  force: process.env.force_no_cache === 'true',
  cacheRoot: process.env.electron_config_cache,
  checksums: (process.env.electron_use_remote_checksums || process.env.npm_config_electron_use_remote_checksums) ? undefined : require('./checksums.json'),
  platform,
  arch
}).then(extractFile).catch(err => {
  console.error(err.stack);
  process.exit(1);
});
```
Here, the "version" is actually obtained through the package.json of the module package.

Based on this version and system environment information,
the corresponding zip product will be fetched from the remote, for example: '**https://github.com/electron/electron/releases/download/v22.3.27/electron-v22.3.27-darwin-arm64.zip**'.

I believe the version file mentioned above is from within this compressed package.

---

Here's a potential approach:

- **Standard Workflow**: If the `electronDist` follows the official versioning structure (e.g., includes a `version` file), we can read the version from it seamlessly.

- **Fallback & Warning**: For cases that don't comply (e.g., missing the `version` file), we can default the `electronVersion` to `'unknown'` and show a clear warning: "Your custom electronDist is missing a 'version' file..."

**Comment by mmaietta** [comment]
> Here's a potential approach:
> Standard Workflow: If the electronDist follows the official versioning structure (e.g., includes a version file), we can read the version from it seamlessly.
> Fallback & Warning: For cases that don't comply (e.g., missing the version file), we can default the electronVersion to 'unknown' and show a clear warning: "Your custom electronDist is missing a 'version' file..."

This requires the version resolution step to be **after** the electron app is extracted. So all of the download/unpack needs to happen before the ElectronFramework init.

I'll see if I can add parsing of that in `createElectronFrameworkSupport` but that requires `prepareApplicationStageDirectory` to be executed much much earlier, not sure if we can do that. It'll require additional investigation, but I can't add this as a high priority task.

**Comment by Vanisper** [comment]
Understood. Please just handle this when you have time.
