### ISSUE TITLE
Install libappindicator1 as a dependency of the linux package

### ISSUE THREAD

**Issue by nono** [electron-userland/electron-builder#375]
Hello,

The electron documentation says:

> On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.

So, I'd like to know if it is possible to make electron-builder generate .deb package with a dependency on libappindicator1.

**Comment by develar** [comment]
Indeed, http://electron.atom.io/docs/latest/api/tray/ 

Possible workaround (not tested): Add to `build.linux` (development package.json) new field:
```
"fpm": ["--depends", "libappindicator1"]
```

**Comment by nono** [comment]
It works:

```
$ dpkg -I dist/cozy-desktop-gui-0.11.0-amd64.deb | grep Depends
 Depends: libappindicator1
```

**Comment by develar** [comment]
Cool. It will be added by default soon. I hope, it will work for all Linux distro.

FYI: `fpm` key is not documented and never will be documented because it is intended only to experiment/test.

**Comment by nono** [comment]
By the way, electron depends of `libnotify` for notifications on Linux. It may be added to fpm depends too.

Cf http://electron.atom.io/docs/v0.37.2/tutorial/desktop-environment-integration/#linux

**Comment by develar** [comment]
Thanks you for suggestion,
* option `depends` added.
* by default `["libappindicator1", "libnotify"]`

@nono Please don't forget to remove experimental `fpm` from your config after update.

**Comment by nono** [comment]
On Debian and Ubuntu, the package is not called `libnotify`, but `libnotify-bin`. I've opened a PR: #410

**Comment by nono** [comment]
Thanks!

**Comment by develar** [comment]
@nono Travis CI is down, so, I cannot publish new version. I hope, it will be published in a few hours.

**Comment by develar** [comment]
Or set env `USE_SYSTEM_XORRISO=true` (10.13.1+)

**Comment by rahilsondhi** [comment]
Version: `electron-builder 16.6.0`
Building for linux on a macOS

What is the expected behavior here? Is `dpkg` supposed to install all the dependencies, or is it up to the user to install the missing dependencies on their own?

When I do `dpg -i install myapp.deb`, I get:

```
$ sudo dpkg -i myapp.deb
(Reading database ... 207816 files and directories currently installed.)
Preparing to unpack myapp.deb ...
Unpacking myapp (0.2.5) over (0.2.5) ...
dpkg: dependency problems prevent configuration of myapp:
 myapp depends on libappindicator1; however:
  Package libappindicator1 is not installed.

dpkg: error processing package myapp (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 myapp
```

However, when I do `dpkg -I myapp.deb | grep libappindicator1`, it's present.

**Comment by develar** [comment]
@rahilsondhi Do you build AppImage in parallel or only deb?

>  Is dpkg supposed to install all the dependencies

Yes, libappindicator1 in the depends.

**Comment by rahilsondhi** [comment]
@develar no AppImage, just deb and rpm.

**Comment by develar** [comment]
@rahilsondhi Use Software Install app to instal deb. Or see http://askubuntu.com/questions/40011/how-to-let-dpkg-i-install-dependencies-for-me

**Comment by freeminder9237** [comment]
apt-get install libappindicator1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libappindicator1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libappindicator1' has no installation candidate
