### ISSUE TITLE
How to configure desktop file entry for AppImage ?

### ISSUE THREAD

**Issue by hugetiny** [electron-userland/electron-builder#3750]
"appImage": {
      "systemIntegration": "doNotAsk",
      "desktop": {
        "Name": "Negibox",
        "Icon": "build/icon_256x256.png",
        "Comment": "The only downloader you need"
      }
    }
I wrote this in package.json ,but didn't work ,the .desktop file cannot be find in /usr/share/applications or ~/.local/share/applications, although the icon file is generated in ~/.local/share/applications

**Comment by zyuhel** [comment]
You should put desktop inside linux section, not appImage.
