### ISSUE TITLE
Skip checkForUpdatesAndNotify because application is not packed

### ISSUE THREAD

**Issue by jettangs** [electron-userland/electron-builder#3753]
dev-app-update.yml:
```
provider: generic
url: http://192.168.19.128:3000/suzao_pc/update
```
package.json:
```  
"dependencies": {
    "electron-updater": "^4.0.6",
    "log4js": "^4.0.2"
  },
  "devDependencies": {
    "electron": "^4.1.0",
    "electron-builder": "^20.39.0"
  }
```
system:
win10
electron version is latest and already add dev-app-update.yml in the project root directory，why I still got this warning，help!

**Comment by jettangs** [comment]
I should use autoUpdater.checkForUpdates

**Comment by edelCustodio** [comment]
Hi @jettangs, I'm trying to sign my app but seems like I need to pay for it, do you know if there is a free option?

**Comment by Slapbox** [comment]
@yeongjet, thank you so much for updating with the solution. I just spent my entire day on this and I had little hope this would work after so many things failed, BUT IT DID!
