### ISSUE TITLE
[mac] Autoupdate fails if 'LSFileQuarantineEnabled' flag is enabled in Info.plist

### ISSUE THREAD

**Issue by paulbennet** [electron-userland/electron-builder#3754]
* **Version**: 20.38.5
Note: It should be the same case in 20.39.0, since I didn't find any issues related to this reported earlier, and no fixes pushed for this.

* **Updater Version**: 4.0.5

* **Target**: Mac [DMG]

Adding and enabling 'LSFileQuarantineEnabled' flag in the Info.plist file, makes our app mark all 
 new downloaded/created files in user's machine via NodeJS as "quarantined" (downloaded from the internet). We require this feature in our app, since it downloads external files to user's machine.

But, it seems when the auto-updater downloads an update file ( zip or dmg ), it is also marked as "quarantined" and hence the update fails throwing error as in below.

"Can’t be updated when it’s running from a read-only volume .."

Initially we thought this would be an issue for users who didn't move the app into Applications folder, but it was happening for almost all mac users. So I guess the issue is with electron-builder marking files are quarantined.

Solution:
- Unmark update files by removing the quarantine attributes, entries once downloaded

**Comment by gch1p** [comment]
I have the same issue in my Electron app. I want quarantine bit to be set on files downloaded by user, but `LSFileQuarantineEnabled` in `Info.plist` breaks autoUpdater... I guess I'll have to set quarantine bit manually by calling xattr or by some other way.

**Comment by abarsov** [comment]
the issue is still actual
