### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [electron-userland/electron-builder#3759]
Greetings, I'm here today to offer my services. As a graphic designer in development and an open source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process (of course) is totally free and we would be working together to create the design that fits best with your project. Of course, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colors, shapes, etc. 

Sorry for disturbing if this is not the proper channel, best regards.

**Comment by develar** [comment]
Well, from what I see you offer it to several open source projects. Thanks, but I will prefer if you will already somehow involved, otherwise logo can be a little bit artificial :)
