### ISSUE TITLE
Auto-Updater - Redirect

### ISSUE THREAD

**Issue by Narmdo** [electron-userland/electron-builder#3763]
I'm currently using electron-publisher and electron-updater to deploy/update my application with an S3 bucket.

I'm now looking to migrate the storage.

In short, I need to deploy to the old location, but have the updater look in the new location for updates. Is this at all possible? Currently the updater uses the publishing location to check for updates.

**Comment by meekaah** [comment]
publish to your new storage place, and manually copy that release to your old storage. if the channel names are the same it will work. i've done it multiple times
