### ISSUE TITLE
CI Windows signing fails

### ISSUE THREAD

**Issue by adammeyer** [electron-userland/electron-builder#3766]
* **Version**: 
20.39

* **Target**: Windows

CSC_LINK env var is set to the base64 string of my cert and CSC_KEY_PASSWORD is set to the password.

Build fails with the following error:
`Error: Exit code: 1. Command failed: C:\Users\appveyor\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\windows-10\x64\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f C:\Users\appveyor\AppData\Local\Temp\1\t-s8aA3U\0.p12 /d ... /du ... /p 547a87e4e124e9242959c6e8bc095881ec8b24eb4f9134cba1978d2cf5e7f2b9 (sha256 hash) /debug C:\projects\....exe`
`SignTool Error: The specified PFX password is not correct.`

The password is correct. If I change the password to something incorrect, the following error shows:
`Error: Cannot extract publisher name from code signing certificate: password incorrect
    at C:\projects\wedesktop\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:93:11`

Locally I don't have this issue, it's just on AppVeyor.  Any suggestions would be appreciated.

**Comment by adammeyer** [comment]
I re-exported the cert using SHA1 encryption instead of SHA256 and that solved the issue.  I guess SHA256 is supported in Windows 10, but not Win Server 2016.

**Comment by roel4ez** [comment]
SHA1 is not recommended to be used.
My signing is working on a local machine (win10) but is failing on the CI server (win2016). Is there another way to deal with this error?
