### ISSUE TITLE
nsis-web missing shortcuts

### ISSUE THREAD

**Issue by meekaah** [electron-userland/electron-builder#3767]
* **electron-builder**: 20.39.0
* **electron-builder**: 4.0.6
* **Target**: nsisWeb

After initial install the desktop and start menu shortcuts are created, but once it updates they are deleted.

here is my nsisWeb configuration i used:
`  
"nsisWeb": {
    "include": "build/app/installer.nsh",
    "artifactName": "App-${version}.${ext}"
  }
`

i have also tried with this:
`  "nsisWeb": {
    "include": "build/app/installer.nsh",
    "artifactName": "App-${version}.${ext}"
    "createDesktopShortcut": "always",
    "createStartMenuShortcut": true
  }`
I didnt experience this issue before we upgraded from "electron-builder": "20.29.0" and "electron-updater": "3.1.5"

Any ideas? Is there any way to debug the nsis install to see how/why it gets removed? are there any logs somewhere that i could enable?

Thanks for your help

**Comment by meekaah** [comment]
Ok well i've played around a bit more with it. 
here's my conclusion i think there is an issue with the default values for createDesktopShortcut and createStartMenuShortcut. in the documentation it says that they're both set to true by default, it doesnt seem to be the case. when set explicitly to true it works as expected.
I have a workaround for my issue but there is none the less a problem to be looked at i beleive.

**Comment by onelsonic** [comment]
Hi there, I can reproduce the exact same issue with the current version : 
"electron": "^8.0.2",
"electron-builder": "^22.3.2"
on windows 10 Pro version 1903

First web install with nsis-web works fine, then 
on second install/update we have the missing shortcuts problem.
The update try to launch this exe :
C:\Users\THEUSER\AppData\Local\Programs\APPNAMEFOLDER
When this folder only contains two files: 
"uninstallerIcon.ico"
"Uninstall APPNAME.exe"
