### ISSUE TITLE
Auto-Updater promise error during check for update

### ISSUE THREAD

**Issue by SmellydogCoding** [electron-userland/electron-builder#3771]
* **electron-builder**: 20.38.5

* **electron-updater**: 4.0.6

* **electron**: 3.0.0

* **Target**: win32 x64

When my app loads and checks for updates:
```
autoUpdater.on('checking-for-update', function () {
  console.log('Checking for update...')
})
```

after it finishes comparing the blockfiles for the current and previous builds, I get this error that repeats endlessly:

```
(node:18120) Warning: a promise was created in a handler at _stream_writable.js:471:7 but was not returned from it, see http://goo.gl/rRqMUw
    at eval (webpack:///./node_modules/bluebird/js/release/generators.js?:197:21)
```

**Comment by develar** [comment]
Obsolete since electron-updater 4.1.0
