### ISSUE TITLE
FileAssociation on windows

### ISSUE THREAD

**Issue by netweng** [electron-userland/electron-builder#3774]
electron-builder version: 20.8.1
electron-update version:2.21.10
electron version: 1.8.4

* **Target**:  windows10   32bit

i got 2 problem:
1. when my productName has chinese characters, build failed
detail error stuck:
![image](https://user-images.githubusercontent.com/11407764/54806849-4496c080-4cb6-11e9-81bc-b60c62ea568f.png)

2. i use the full english name temporary and when i click the file , it always launch a new application, even though there is a application existing. what should i do if i want to use   only one application to handle the new open file?

**Comment by netweng** [comment]
sorry for my stupid question, i solved the question 2 by use `app.makeSingleInstance` and still thinking about the question 1, anyone has a solution?

**Comment by xiaoping6688** [comment]
> sorry for my stupid question, i solved the question 2 by use `app.makeSingleInstance` and still thinking about the question 1, anyone has a solution?

![image](https://user-images.githubusercontent.com/16394201/55211114-9f379b80-5225-11e9-9986-80d51587e578.png)

**Comment by netweng** [comment]
solved this question, it's not electron-builder problem. close this issue please.

**Comment by netweng** [comment]
solve this question by change the modify node_modules/electron-build-lib/out/targets/nsisTarget.js,
add `args.push("-INPUTCHARSET", "UTF8")`
into line 636. don't know why exactly, anyone can explain it ?

**Comment by netweng** [comment]
> > sorry for my stupid question, i solved the question 2 by use `app.makeSingleInstance` and still thinking about the question 1, anyone has a solution?
> 
> 我的没问题啊
> ![image](https://user-images.githubusercontent.com/16394201/55211160-d73ede80-5225-11e9-9258-9120d94c32d3.png)

或许是版本不同？我的版本都比较就，electron是1.8.4, electron-builder是20.8.1
