### ISSUE TITLE
Semver "metadata" and S3 yml filename

### ISSUE THREAD

**Issue by hibiyasleep** [electron-userland/electron-builder#3775]
* **Version**: 20.39.0

* **Target**: Unrelated, NSIS/dmg if not.

Our project is currently in 'preview' build, and has version name of `v3.0.0-pre2`. (surely next if `v3.0.0-pre3`, semver can parse it anyway)

however, when I publish my build to S3 -

> [(docs: /configuration/publish)](https://www.electron.build/configuration/publish#continuous-deployment-workflow-on-amazon-s3-and-other-non-github)
> Set your version in your application package.json to 1.9.0-snapshot (or 1.9.0-master or whatever you want your development channel to be named)

`pre2.yml` created because electron-builder detects `pre2` as *development channel*.

since semver don't force 'metadata' to be build channel name, I wish there's an option to ignore metadata field when decide a build channel.

**Comment by develar** [comment]
Check `detectUpdateChannel` and `channel` (to set explicitly) options.
