### ISSUE TITLE
Cannot Publish to Private GitHub - 404 Not Found - Method undefined  url

### ISSUE THREAD

**Issue by AndreD23** [electron-userland/electron-builder#3776]
* **Version**: 20.38.5

* **Target**: Windows ia32 and x64

I'm trying to push the project to GitHub releases in a private repository.

The main target is Win ia32 and x64.

I setted the token in the console by 

`set GH_TOKEN=<blabla>`

And at the package.json file:

```
"publish": {
      "provider": "github",
      "repo": "electron-todo-tasks",
      "owner": "AndreD23",
      "host": "github.com",
      "protocol": "https",
      "releaseType": "draft",
      "token": "<blablabla>",
      "private": true
    }
```

I'm the only one who will have access to the project, so updating the token in the file apparently not a problem.

But, when I run:

`electron-builder --x64 --ia32 --publish always`

It shows me the error:

```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: undefined url: https://github.com/repos/AndreD23/electron-todo-tasks/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

I'll attach  the hole error.

[2019-03-22T13_04_27_992Z-debug.log](https://github.com/electron-userland/electron-builder/files/2996644/2019-03-22T13_04_27_992Z-debug.log)

[electron publish error.txt](https://github.com/electron-userland/electron-builder/files/2996648/electron.publish.error.txt)

I tried to change the option always to onTag or onTagOrDraft and change releaseType to release.

I tried to manually create a draft on GitHub first, not works.

I tried to make the repository public for tests, not work too.

I tried to regenerate the token two times and updated at the envs, console and package.json, not works.

There are some configuration that I've missed? What I have to do for the electron publish to GitHub?

At the error, it says that cannot find  https://github.com/repos/AndreD23/electron-todo-tasks/releases. Openning it on web browser, it returns 404. I found strange the link, because it adds the word "repos" after github.com, and removing it in the browser it loads fine. This word is setting automatically?

**Comment by edelCustodio** [comment]
Hi @AndreD23 

CC @develar @naheller 

Same happens to me, I have 2 days trying to solve this and I have not had luck. the url https://github.com/repos/edelCustodio/electron-auto-update/releases has "repos" word, if I get rid that it works fine on the browser.

Seems like private repo is not well supported by `electron-builder`, at least this is something that I have read on a few threads.

**Comment by edelCustodio** [comment]
Hi @AndreD23 

This works for me, on PowerShell type this `[Environment]::SetEnvironmentVariable("GH_TOKEN","my-personal-token","User")` and be sure that you package.json will be like this:

`"build": {
    "appId": "com.friasoftit.electron-auto-update",
    "productName": "Electron Auto Update",
    "publish": [
      {
        "provider": "github",
        "owner": "edelCustodio",
        "repo": "electron-auto-update"
      }
    ],
    "win": {
      "publish": [
        "github"
      ],
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    }
  },`

And then I run this command `yarn run publish` and this is how is my `publish` is on my package.json `"publish": "build --win -p always"` don't forget to close and open a new PowerShell terminal

**Comment by AndreD23** [comment]
It Worket!! Thank you so much @edelCustodio!!

**Comment by rllola** [comment]
Hi @edelCustodio and @AndreD23,

Also as an alternative there is https://www.update.rocks/. It is free for open source project and has been built to work with private github repo.

**Comment by AndreD23** [comment]
Thanks for the advice @rllola ! I'll look this alternative.

**Comment by jan-scorl** [comment]
I've had the same issue as well and the problem is indeed that the automatically generated URL contains `/repos/` which breaks the link. Not specifying `host` as `github.com` and `protocol` as `https` solves the problem.

@maintainers: Is that the intended behavior?

**Comment by Monder87** [comment]
I used all your solutions but with no luck, i finally resolved using another set up.
This is what i tried and failed:

 - use env variable GH_TOKEN on my mac adding it to the _bash_profile, updating the console, verifying  `printenv` was giving me the right value  

 - use the GH_TOKEN inside the electron-builder.yml with this setup:
 ```
publish:
  provider: github
  token: _your_token_
  private: true
  repo: _your_repo_
```
 - write the variable in .env file and directly calling it inside package.json with grep:
 ```
 "publish": {
      "provider": "github",
      "host": "github.com",
      "protocol": "https",
      "token": "${grep GH_TOKEN' .env }",
      "private": true
    }
```
- hand writing the token in the package json:
```
"mac": {
    "target": "dmg",
    "category": "utilities",
    "type": "development",
    "publish": {
      "provider": "github",
      "host": "github.com",
      "protocol": "https",
      "token": "GH_TOKEN=_your_token_",
      "private": true
    }
  },
```
in all these cases i got alway this error:
```
 ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
```

i fixed following this setup in package.json:

```
"build": {
    "appId": "com.electron.yourapp",
    "asar": true,
    "asarUnpack": "node_modules/puppeteer/.local-chromium/**/*",
    "productName": "_your_product name_",
    "files": [
      "build/**/*",
      "node_modules/**/*"
    ],
    "directories": {
      "buildResources": "public"
    },
    "publish": {
      "provider": "github",
      "private": true,
      "owner": "_your_username_"
    },
    "mac": {
      "target": "dmg",
      "category": "utilities",
      "type": "development",
      "icon": "./public/icon.icns",
      "publish": {
        "provider": "github",
        "owner": "_your_username_",
        "repo": "_your_repo_",
        "private": true,
        "token": "_your_token_""
      }
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "icon": "./public/icon.png",
     "publish": {
        "provider": "github",
        "owner": "_your_username_",
        "repo": "_your_repo_",
        "private": true,
        "token": "_your_token_""
      }
    }
  }
```

and worked without issue deploying my build in GitHub private repo, hope this can help someone!
@develar  maybe is needed a better documentation on private repos both for github private and bitbucket as well
