### ISSUE TITLE
FPM Package for armv7l?

### ISSUE THREAD

**Issue by khvnhtung** [electron-userland/electron-builder#3777]
* **Version**: ^20.39.0

* **Target**: Linux Armv7l

It seems that Electron Builder can't find an compatible fpm package for arm to build my deb package and instead download fpm for linux x86 as you can see here:
https://pastebin.com/xNM8XhUx
Any help would be greatly appreciated!

**Comment by zachzoup** [comment]
Did you ever figure this out? I'm seeing the same issue on 20.39.0.

**Comment by tungbox** [comment]
> Did you ever figure this out? I'm seeing the same issue on 20.39.0.

I couldn't find any way to solve this so I have to buit the deb package on my macbook and then deploy it to my Raspberry Pi.

**Comment by develar** [comment]
arm will be supported for snap (https://github.com/electron-userland/electron-builder/issues/3977), but no plans to support other formats.

Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
