### ISSUE TITLE
symbol lookup error: /tmp/.org.chromium.Chromium.fqwEqo: undefined symbol:

### ISSUE THREAD

**Issue by SublimeCT** [electron-userland/electron-builder#3778]
* **Version**: 20.34.0

* **Target**: Electron = `3.1.6` platform = `Linux` arch = `x64`

this project focked from `electron-vue`

native packages: 
- usb `1.5.0`
- serialport `7.1.4`

add script `"postinstall": "electron-builder install-app-deps" to `package.json`

I use `./node_modules/.bin/electron-rebuild` and `./node_modules/.bin/electron-builder install-all-deps`, development environment is fine, then running `electron-builder --linux`

finally, I running this `AppImage` file, but It's not work.

```bash
$ ./build/electron-pack-0.0.1-x86_64.AppImage
```

Error:

/tmp/.mount_electrw8tUHB/electron-pack --type=renderer --no-sandbox --service-pipe-token=DF2402B0D2FB381B28D870ED088DA2B4 --lang=zh-CN --app-path=/tmp/.mount_electrw8tUHB/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --num-raster-threads=2 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=DF2402B0D2FB381B28D870ED088DA2B4 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101: symbol lookup error: /tmp/.org.chromium.Chromium.fqwEqo: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE

**Comment by digilist** [comment]
I am getting a similar error with rocketchat-desktop on Arch Linux.

```
App threw an error during load
Error: /tmp/.org.chromium.Chromium.pMG0nQ: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/lib/rocketchat-desktop.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/rocketchat-desktop.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
```

**Comment by torpesco** [comment]
I'm getting the exact same error as digilist, also on Arch Linux.

**Comment by abianche** [comment]
same error as @digilist and @torpesco, on Arch, with bitwarden-desktop

**Comment by torpesco** [comment]
After a bit of digging, I found a relatively simple solution for myself: I rebuilt rocketchat-desktop against electron 4.1.4.

An aside: This took a bit too much work for me, as it turns out there's some weird problem on my work network interfering with certain downloads from github, and the bizarre thing is that with electron 3.1.6, I could run makepkg, but with 4.1.4, it hung on the yarn upgrade step -- until I connected my PC to a different network.

**Comment by develar** [comment]
Please try 21.0.5 (and update electron to 4 or 5).
