### ISSUE TITLE
electron-builder corrupting -mac.zip file

### ISSUE THREAD

**Issue by lutzroeder** [electron-userland/electron-builder#3779]
* **Version**: 20.39.0
* **Target**: mac, zip

@develar, running `npx electron-builder --mac` creates invalid ZIP files because extra blockmap data is appended to the ZIP file via [this](https://github.com/electron-userland/electron-builder/commit/a6c5bc4ad4c9f9894bffe349fd55bd708a6262e8) change. `unzip` searches the last ~66000 bytes for the `PK\x05\x05` signature and extra data is big enough to miss that window. It's hit and miss based on the rounded size of the last block.

```
~: unzip Netron-2.9.7-mac.zip 
Archive:  Netron-2.9.7-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Netron-2.9.7-mac.zip or
        Netron-2.9.7-mac.zip.zip, and cannot find Netron-2.9.7-mac.zip.ZIP, period.
```

See also:
 * https://github.com/lutzroeder/netron/releases/download/v2.9.7/Netron-2.9.7-mac.zip
 * https://travis-ci.org/Homebrew/homebrew-cask/builds/510817237?utm_source=github_status&utm_medium=notification

**Comment by giddens9527** [comment]
Found the same issue. Also this seems influencing auto-update for autoupdater.

**Comment by CapOM** [comment]
Reopen please, thx you!

**Comment by kjohnstonadept** [comment]
Yes I also hit this - please re-open.
