### ISSUE TITLE
When I uninstalled the app I found a folder that had not been deleted

### ISSUE THREAD

**Issue by xiaoping6688** [electron-userland/electron-builder#3786]
`"deleteAppDataOnUninstall": true `
It is not working.

![image](https://user-images.githubusercontent.com/16394201/55129557-801c0980-5152-11e9-8220-22111ec3a673.png)

**Comment by enggjiten** [comment]
When I run the uninstaller, apart from registry nothing is removed.
Tried with deleteAppDataOnUninstall and customUnInstall.

**Comment by enggjiten** [comment]
Using electron-builder 20.39.0.
