### ISSUE TITLE
Modify default configuration

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [electron-userland/electron-builder#3787]
I changed the configuration file and made an error packing it
![image](https://user-images.githubusercontent.com/24189898/55139101-ed8a6300-516f-11e9-8670-bd23ef392a33.png)
![image](https://user-images.githubusercontent.com/24189898/55139166-0e52b880-5170-11e9-805d-f3ff85141f0b.png)

**Comment by xiaoping6688** [comment]
![image](https://user-images.githubusercontent.com/16394201/55151202-ab215000-5188-11e9-8322-d62aee7ae379.png)
`"buildResources": "config"`
