### ISSUE TITLE
how package.json variable to nsis?

### ISSUE THREAD

**Issue by wnsduq8282** [electron-userland/electron-builder#3788]
* **Version**: 

* **Target**: 

Hello. I have a question.
I want to call variable in nsis from package.json.

for example.

[pacakge.json] 
{
  "name": "led-assistant",
  "version": "1.3.2",
...
}

[installer.nsh]
I want use above version variable in nsis.
like ${VERSION}... how can i do?

**Comment by xiaoping6688** [comment]
![image](https://user-images.githubusercontent.com/16394201/55210820-3a2f7600-5224-11e9-921e-3d5ae8f192ee.png)
for example：
`import {version} from './app/package.json';`
