### ISSUE TITLE
Option to ignore files for signing

### ISSUE THREAD

**Issue by torjusb** [electron-userland/electron-builder#3790]
* **Version**:  20.39.0

* **Target**: OS X

We have a .app bundled in the app. I'm using the `asarUnpack` option for this. But I'm running into problems with the app signing, as it seems to be trying to sign files/folders which are not signable.

This is the error I'm getting:

```
Error: Command failed: codesign --sign *** --force /Users/***/Contents/Resources/app.asar.unpacked/resources/osx/***.app/Contents/Frameworks/Breakpad.framework/Breakpad: bundle format is ambiguous (could be app or framework)
```

Is there any way to ignore files which should not be signed? Or an option to specify exactly which files _should_ be signed? I've tried the `binaries` option, but it still tries to sign the other files.

**Comment by xiaoping6688** [comment]
![image](https://user-images.githubusercontent.com/16394201/55271521-e3d83b00-52e8-11e9-9384-c2febac88475.png)

**Comment by torjusb** [comment]
It's unclear to me how changing those settings helps. Even with `forceCodeSigning: false` it still exists when the `codesigns` fails with `bundle format is ambiguous`. I also still want to package my app files in an .asar file, but leave .app we package in the `app.asar.unpacked` folder.

**Comment by hrishabhkumar** [comment]
There should be an option to specify list of files/folder or module which is not required to sign.

**Comment by hrishabhkumar** [comment]
Is there any update on this please?

**Comment by benoitlahoz** [comment]
Any update on this?
