### ISSUE TITLE
disable asar for a file

### ISSUE THREAD

**Issue by Sombian** [electron-userland/electron-builder#3791]
* **Version**: 1.2.0

* **Target**: windows / nsis

in my app, i used .json file for the configration.
as asar made it read-only i cant update this after complied but in dev.

        asarUnpack: [
          `./src/configuration.json`
        ],
        extraResources: [
          `./src/configuration.json`
        ],
        win: {
          icon: './src/assets/icon.ico'
        }

what have i done wrong?

**Comment by mceachen** [comment]
Changing files in your installation directory is never going to be a good idea. Put configuration files in the user's data directory. See https://electronjs.org/docs/api/app#appgetpathname and use the `userData` directory.

**Comment by zgramana** [comment]
I have the same need, though for an entire directory, but in my case I need to be able to load .NET assemblies at runtime via a sidekick executable.
