### ISSUE TITLE
auto-updater on windows: reboot during update install leaves incomplete installation [nsis]

### ISSUE THREAD

**Issue by siebertm** [electron-userland/electron-builder#3798]
* **Version**: electron-updater v4.0.7
* **Target**: win64 NSIS

We're experiencing a proper error condition when using auto-updater: Our application is run by our customers from boot to shutdown (I'd even say "from dawn to dusk" :p). This means that the auto-updater finds an update and marks it for installation on exit - fine.

Now, the user's work day ends, they want to run home. They shut down the app (the update installer starts), and immediately shut down windows.

Now, windows at some point kills the update installer NSIS process, leaving behind an incompletely installed app! :boom: 

The question is now for me: is this a fixable bug or should we rather "move" the update installation to another point in time? I could think of rearrange stuff so that the update is installed on launch - essentially slowing down the launch due to the pending update...

What is the official stance on this issue? Did anybody else experience (and solve) this?

**Comment by Channe** [comment]
[2019-06-18 18:27:03.030] [info] Update installer has already been triggered. Quitting application.

I have same question.

**Comment by Channe** [comment]
"electron-updater": "^4.0.6",
"electron": "^5.0.2",

**Comment by mceachen** [comment]
@develar, I believe this is still a bug (but the stale bot closed it). Do you consider it an NSIS issue?

**Comment by Muukuro** [comment]
One solution (for certain use cases) might be to configure electron-updater to only trigger the install manually (i.e. not on close).

https://www.electron.build/auto-update#appupdater-eventemitter

Set `autoInstallOnAppQuit` to `false`.
