### ISSUE TITLE
Is it possible to set PORTABLE_EXECUTABLE_DIR to a different path?

### ISSUE THREAD

**Issue by agjs** [electron-userland/electron-builder#3799]
Hi, 
We would like to have the same path each time our portable application is running and we wonder if it's possible to set *PORTABLE_EXECUTABLE_DIR* to a specific path? 

Essentially, we would love to keep the portable in the temp directory, but instead of having this hash-like folder name, we would like to keep it in **TEMP/application-name**.

Thanks in advance

**Comment by agjs** [comment]
@develar Could you please let us know as soon as possible if this is possible or not? If not, we will contribute to electron-builder, it's quiet urgent for us. Thanks

**Comment by develar** [comment]
Here is a security problem  — if not random path will be used, then we need to empty dir before unpacking, to make sure that no malicious/not expected files.

Could you please explain your case in short?

**Comment by agjs** [comment]
@develar The issue we have is that each time we run our portable application, it asks for firewall permissions for private and public networks. (exactly like this: #2909).

The idea we had is that, if portable application would be run every time from the same path and we initially add a firewall rule e.g. 

> ExecWait 'netsh advfirewall firewall add rule name=SomeName dir=in action=allow program="$INSTDIR\name-portable.exe" enable=yes profile=public,private'

We would at least be able to point to firewall rule to the same location, which hopefully wouldn't ask for firewall permissions each time you run the portable, but only the first time. 

Unless we can fix this firewall issue somehow, I don't see any other way to fix this other then having the portable in the same location each time.

**Comment by develar** [comment]
You can expect feature in 2 hours. Path will be computed as hash from installer (or other content, not yet clear).

**Comment by agjs** [comment]
@develar Sounds amazing man. Please, feel free to ping me if you need any help, I'd like to assist.

**Comment by develar** [comment]
Please try https://github.com/electron-userland/electron-builder/releases/tag/v20.40.0 (`next` version).

https://github.com/segmentio/ksuid is used to generate directory name in temp directory. `ksuid` is computed during build of portable executable.

**Comment by agjs** [comment]
Amazing work @develar.I guess this ksuid can/will always be the same or at least, we will be able to use the same one?

**Comment by develar** [comment]
> `ksuid` is computed during build of portable executable.

Each invocation of `electron-builder build` will produce a new one.

**Comment by agjs** [comment]
I understand. But how will this solve the described issue above? The application will always be in a different place still, which means we can't add a firewall rule that points to the same location, no?

**Comment by develar** [comment]
From your code

```
ExecWait 'netsh advfirewall firewall add rule name=SomeName dir=in action=allow program="$INSTDIR\name-portable.exe" enable=yes profile=public,private'
```

I decided that you have custom code for portable nsis script and so, proposed solution is suitable for you. No?

**Comment by agjs** [comment]
1. With the solution you provided, we would have to add a firewall rule each time you run the portable because each time, the path would be different. 
2. Portable target doesn't support NSIS script in the electron-builder.yml file. This means that we could only add this rule under the NSIS target and point to the static location.

So, no, I don't think this would work :( ...

**Comment by develar** [comment]
> could only add this rule under the NSIS target and point to the static location.

So, you have some other installer that do it?
Is it task requires sudo? Or it just performed silently without any OS questions?

**Comment by agjs** [comment]
No, we don't have any other installer. We want to do this using electron-builder and NSIS.

I believe that having an option to provide a path for the portable application would solve this and many other potential issues. 

I don't think that adding firewall rule would require any sudo (this is Windows only).

**Comment by agjs** [comment]
So again, what we want to do is not really complex. 

1. We want to be able to install a portable application in the path we choose. 
2. Add a firewall rule for that path so when the application is run again, the system doesn't ask for firewall permissions again.

**Comment by agjs** [comment]
@develar If you don't have time to do this, can I do a pull request and add an ability to provide a custom path for portable?

**Comment by develar** [comment]
```
/**
   * The unpack directory name in [TEMP](https://www.askvg.com/where-does-windows-store-temporary-files-and-how-to-change-temp-folder-location/) directory.
   *
   * Defaults to [uuid](https://github.com/segmentio/ksuid) of build (changed on each build of portable executable).
   */
  readonly unpackDirName?: string
```

option was added. Release will be in 10 minutes.

```
config: {
    portable: {
      unpackDirName: "0ujssxh0cECutqzMgbtXSGnjorm",
    }
  }
```

**Comment by develar** [comment]
Please try `20.40.1`.

**Comment by agjs** [comment]
@develar Fixes our issue. Awesome work @develar. Make sure to update the docs too, am sure many people will need this. Cheers

**Comment by DannyFeliz** [comment]
@agjs @develar Thank you very much guys 💪

**Comment by Basajarau** [comment]
Hello, Im trying to set the unpackDirName but I'm having issues.

I have the last electron-builder in my package-lock.json:
`    "electron-builder": {
      "version": "20.40.0",
      "resolved": "https://registry.npmjs.org/electron-builder/-/electron-builder-20.40.0.tgz",
      "integrity": "sha512-xTUq9lMdqXzc+2h68l0MtESk6cErNye7n0zXKKUlBvun+KYiIzhzpIJyt1OW2Wb7K89KHP1aGuxLXQe8h/LQyg==",
      "dev": true,
    },`

And the configuration set in my electron-builder.json
`{
  "productName": "XXX",
  "directories": {
    "output": "app-builds"
  },
  "portable": {
    "unpackDirName": "0ujssxh0cECutqzMgbtXSGnjorm"
  },`

Am I doing something wrong? Im getting the following error:
"* configuration.portable has an unknown property 'unpackDirName'. These properties are valid:..."

¿Could you help me? Please :)

Thanks in advance!

**Comment by ransome1** [comment]
@DannyFeliz, @agjs, @develar, I would like to use the unpackDirName attribute in my own app, as users are having issues with the portable app creating new instances everytime they open it from Windows' task bar (https://github.com/ransome1/sleek/issues/72).

But I can't get it setup in my package.json. All possible configuration fail for me and I have no idea how to use the yml config (mentioned above my @develar), which is being build by electron-builder as a result of what I setup in my package.json.

This is what my package.json target config looks likes right now
```
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": ["x64", "ia32"]
        }
      ],
      "unpackDirName": "sleek",
      "icon": "assets/icons/sleek.ico",
      "publisherName": "CN=2B3D4037-FF2E-4C36-84A6-CFF49F585C0C"
    },
```
Which fails, as electron builder doesn't recognise the unpackDirName parameter. Can you guys point me towards a solution please? :)

**Comment by valueerrorx** [comment]
```
portable: {
      unpackDirName: "0ujssxh0cECutqzMgbtXSGnjorm",
}
```

this works as expected BUT it introduces a new problem =>

now the electron app extracts into a specific tmp directory and if started twice the second instance starts to overwrite files in the temp directory while the first is still loading. the first instance then crashes and must be killed via taskmanager.

how can i circumvent this problem?

(the code in main.js already requests singleInstance but the problem occurs before the code is even read)

THX!

**Comment by jeffrson** [comment]
Any solution to the problem unpacking two instances?

**Comment by voltara13** [comment]
I agree, the problem with two copies is still relevant.
