### ISSUE TITLE
Make it possible to perform post actions with arguments after MSI install

### ISSUE THREAD

**Issue by noahlaux** [electron-userland/electron-builder#3803]
* **20.38.3**: 

* **MSI**: 

I have a use case where I have to create a file utilizing the arguments provided to the `.msi`. 

eg:

```sh
msiexec /i "myapp.msi" /quiet WRAPPED_ARGUMENTS="/autostart=false /streaming_notification=true"
```

It doesn't seem possible to currently, as the wix template is [fixed](https://github.com/electron-userland/electron-builder/blob/e59f6c3b6155534fe2076fc1b8a0ba0bbc348f62/packages/app-builder-lib/src/targets/MsiTarget.ts#L26), and it doesn't seems like there's another way to achieve this.

**Comment by develar** [comment]
Pull request welcome. Sorry, but I don't have time to implement it any time soon. I suggest to do post action as part of first app start.

**Comment by noahlaux** [comment]
But how would I get the arguments passed to the `MSI` from the post action?
