### ISSUE TITLE
build deb on bamboo red-hat

### ISSUE THREAD

**Issue by orlandodemauro** [electron-userland/electron-builder#3805]
* **Version**: 20.39.0 

* **Target**:  deb

hi guys,
is it possible to build deb packages in red-hat or centos? i have been able to create deb packages on ubuntu and rpm on red-hat, but when i try to build deb in Bamboo with a redhat machine and i´m getting a permission issue on the tar command:

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
tar : (GNU tar) 1.26
xz : (XZ Utils) 5.2.2
liblzma 5.2.2
node --version : v8.11.4
npm --version : 5.6.0
fpm v 1.11.0
here the logs [logs (3).txt](https://github.com/electron-userland/electron-builder/files/3044753/logs.3.txt)

**Comment by develar** [comment]
You can try set env `_REMOTE_BUILD=true` to build deb using build service if you cannot configure local machine properly.
