### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by rajeshkh** [electron-userland/electron-builder#3808]
Here I just want to move a db file from 
From :- 'C:\Program Files\electron_app\resources\electron_app.db' 
To   :- 'C:\Users\Sys26\AppData\Roaming\electron_app\electron_app.db' 

but while I am installing this app for all user the db file "electron_app.db" is not able to move getting error like "Error: EPERM: operation not permitted",  while if I am installing this app for single user means Only for particular user then its working fine.

can anyone help me get solutions for this.

package.json
![n1](https://user-images.githubusercontent.com/49303188/55613055-52187400-57a7-11e9-9ac9-aef7ec9079f0.png)

**Comment by develar** [comment]
You need to use solution like https://github.com/jorangreef/sudo-prompt#readme

**Comment by OliverBrotchie** [comment]
Have been running into a similar issue when trying to use CHMOD on a binary that is required for the app to run. Develar's solution fixed it
