### ISSUE TITLE
NSIS - Custom pages appear twice

### ISSUE THREAD

**Issue by agpreynolds** [electron-userland/electron-builder#3809]
* **Version**:  20.39.0

* **Target**:  NSIS (With custom include)

Hello i've noticed some strange behaviour when attempting to create a custom installer page.

My config is as follows:
```
  "build": {
    "appId": "my-app",
    "directories": {
      "output": "dist"
    },
    "extraResources": {
      "from": "..\\..\\output\\test\\api",
      "to": "api/",
      "filter": [
        "**/*"
      ]
    },
    "nsis": {
      "oneClick": false
    },
    "win": {
      "target": [ "nsis" ]
    }
  }
```

With an additional script (build/installer.nsh):

```
!include MUI2.nsh

!macro customWelcomePage

	!insertMacro MUI_PAGE_WELCOME

!macroEnd
```

What appears to be happening is the pages appear in the following order:
- **Welcome**
- per-user / per-machine
- Administrator access confirmation
- **Welcome**
- Installation
- Completed

With the welcome page appearing twice.

This also happens with more sophisticated custom pages defined with the command:
`Page custom someFunction`

Is there something obvious which i'm doing wrong?

**Comment by agpreynolds** [comment]
As an additional piece of information. This doesn't seem to happen with oneClick set to false and perMachine set to true.

I suspect it is related to https://github.com/electron-userland/electron-builder/blob/4ee4be63159472d621abc30d5fbe017d7a88981a/packages/app-builder-lib/templates/nsis/multiUserUi.nsh#L9

However i'm not sufficiently experiences in NSIS and MUI to suggest how to resolve it

**Comment by EthannYakabuski** [comment]
Can't seem to get it to work with your suggestion of perMachine = true either. Any other suggestions?
