### ISSUE TITLE
OSX Signed App Invalid Due to ShipIt Altered

### ISSUE THREAD

**Issue by ractoon** [electron-userland/electron-builder#381]
Hi There,

After building a signed OSX app it was being flagged during install as damaged/invalid. I'm able to force an install by overriding security settings. However, digging in it looks like the signed app is invalid due to: Requirements and resources didn't pass static validation.

Specifically:

```
Error details: “-67054: a sealed resource is missing or invalid” {
	Error in subcomponent: Contents/Frameworks/Squirrel.framework
	Resources altered: 
		Contents/Frameworks/Squirrel.framework/Versions/Current/Resources/ShipIt
}
```

It seems like the Squirrel components are being modified after signing. Builder packages are currently set up to use:

```
"devDependencies": {
    "electron-builder": "next",
    "electron-prebuilt": "0.37.8",
    "rimraf": "^2.5.2",
    "tsconfig-glob": "^0.4.3",
    "typescript": "^1.8.9"
  }
```

Any insight you could offer would be greatly appreciated.

Thanks!

**Comment by develar** [comment]
Duplicates #377.

Please do `npm update`.

**Comment by ractoon** [comment]
Thank you! That was it.
