### ISSUE TITLE
windows/nsis @ 20.40.0: installer shows 'are you sure you want to uninstall?' popup

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron-userland/electron-builder#3813]
* **Version**:  20.40.0

* **Target**:  Windows, NSIS

When installing on top of an already-existing installation, or installing an auto-update, the user gets a confusing popup: 'are you sure you want to uninstall?'

This is especially bad in our app, because we delete all user data on uninstall. (it's not that the data is deleted - it's that users might be worried that it will be, then click cancel which seems to hang the install)

I think it's this line, where the `/S` was removed.: https://github.com/electron-userland/electron-builder/commit/c84ecff171dac128a1d5552a1287a375dc57df07#diff-b120190be851fb383eab0c06dbeebd08R173

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v20.40.2
