### ISSUE TITLE
Cannot find certificate with 'certificateSubjectName' when it contains special characters

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#3817]
* **Version**: 20.39.0

* **Target**: windows / x64

When using a certificateSubjectName containing special characters, the certificate cannot be found because is doesn't match the encoding in the certificate store.

The following configuration should work if a certificate with the matching subject is in the store:

`certificateSubjectName: "CN=Company Sàrl, O=Company Sàrl, STREET=MyStreet, L=MyLocation, S=MyState, PostalCode=MyCode, C=MyCountry"`

But it give me the following error:

> Error: Cannot find certificate CN=Company Sàrl, O=Company Sàrl, STREET=MyStreet, L=MyLocation, S=MyState, PostalCode=MyCode, C=MyCountry, all certs
: {"Subject":"CN=Company S�rl, O=Company S�rl, STREET=MyStreet, L=MyLocation, S=MyState, PostalCode=MyCode, C=MyCountry","PSParentPath":"Microsoft.
PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"8B9E87038AE1A987E64B204CB32410F2727A0D6F"}

Using the following configuration works:

`CN=Company S�rl, O=Company S�rl, STREET=MyStreet, L=MyLocation, S=MyState, PostalCode=MyCode, C=MyCountry`

I expect the subjects to be decoded with their respective encoding and then compared.

The certificate is encoded correctly, here is the output from PowerShell:

Command:

`Get-ChildItem -Recurse Cert: -CodeSigningCert | Select-Object -Property Subject,PSParentPath,Thumbprint`

Output:

`CN=Company Sàrl, O=Company Sàrl, STREET=MyStreet, L=MyLocation, S=MyState, PostalCode=MyCode, C=MyCountry Microsoft.PowerShell.Security\Certificate::CurrentUser\My XXXMYXHASHXXX`

**Comment by midevnull** [comment]
Same issue here. Also on win x64 with 20.39.0:

> 
> Error: Cannot find certificate xxxé, all certs: {"Subject":"CN=xxx�, O=xxx�, L=Berlin, S=Berlin, C=DE, SERIALNUMBER=DOC:20180528, OID.2.5.4.15=Business Entity, OID.1.3.6.1.4.1.311.60.2.1.1=Berlin, OID.1.3.6.1.4.1.311.60.2.1.2=Berlin, OID.1.3.6.1.4.1.311.60.2.1.3=DE","PSParentPath":"Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"xxx"}
> 
>     at C:\Users\xxx\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:141:9

**Comment by fengerzh** [comment]
It just looks ugly, but works ok.

**Comment by dume2007** [comment]
Same issue with chinese certificateSubjectName:

 Cannot find certificate 杭州*****科技有限公司, all certs: {"Subject":"CN=����С������Ƽ����޹�˾, O=����С������Ƽ����޹�˾, L=��
����, S=�㽭ʡ, C=CN,

**Comment by fengerzh** [comment]
> Same issue with chinese certificateSubjectName:
> 
> Cannot find certificate 杭州*****科技有限公司, all certs: {"Subject":"CN=����С������Ƽ����޹�˾, O=����С������Ƽ����޹�˾, L=��
> ����, S=�㽭ʡ, C=CN,

你需要先把文件编码变成gbk，然后把正确的文字内容拷贝进去，然后再把文件格式变成utf-8，这时候就可以用了。不能直接拷贝乱码进去，拷贝乱码进去是没有意义的。

**Comment by EddieOne** [comment]
Same problem but without special characters. Can someone give an example of a proper value for certificateSubjectName?

**Comment by williamtsang88** [comment]
We fixed the problem by doing the following steps:
![Image](https://github.com/user-attachments/assets/1dbe09ca-2149-46a2-a5b0-2d118005eefd)
