### ISSUE TITLE
Cann't write file

### ISSUE THREAD

**Issue by hon** [electron-userland/electron-builder#382]
There is a configration function in my app. The user can config the server url, and then get data from the url. 
After the user fill in the input and click save, I write the url into a local file. It worked fine when I use:
```bash
'electron ./app'. 
```
But I can't write to the file after I made a .exe file with electron-builder:
```bash
'build --platform win32 --arch x64'
```
Is it possiable?

**Comment by develar** [comment]
> I write the url into a local file.

Where file is located? You must write to app installation directory, you should use http://stackoverflow.com/questions/30465034/where-to-store-user-settings-in-electron-atom-shell-application

**Comment by hon** [comment]
Thank you, It works.

**Comment by hon** [comment]
Hi, develar
I write the config information into 'userData' folder. Now if the I update the app, will the config file be overwrite?

**Comment by develar** [comment]
> will the config file be overwrite?

It is up to you. electron-builder or Squirrel.Windows doesn't touch it.

**Comment by hon** [comment]
ok, thank you.
