### ISSUE TITLE
Set asar to false is not working, __shim.js and .cache is missing from unpacked archive

### ISSUE THREAD

**Issue by belloyang** [electron-userland/electron-builder#3822]
`"electron-builder": "^20.39.0"`

* **Version**: 20.39.0

* **Target**:  platform=win32 arch=x64

I encounter this issue when `asar` is set to false. The resources are not asar packed, but they are also not transpiled, since my project is using Typescript, I can't start the app.
when I set asar to true, I have to manually unpack the archive, and it works fine after that.
By comparison, the unpacked resource( when asar=false ) misses __shim.js and .cache folder which can be found in the manually unpacked archive.
Can anyone please share some idea or thought about how can I fix this problem? I really appreciate it.
The build config is as follows:
```
"build": {
    "asar": false,
    "win": {
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true
    }
  }
```

**Comment by bennyschmidt** [comment]
This is still happening in 2025: https://github.com/electron-userland/electron-builder/issues/9124

`asar: false` does nothing, it still removes your files/folders
