### ISSUE TITLE
Electron Auto Update on Windows with limited user permissions

### ISSUE THREAD

**Issue by TDola** [electron-userland/electron-builder#3824]
* **Version**: 20.38.5

* **Target**: NSIS-Web

I am looking for a way to make the auto updates work on Windows systems where the application is installed perMachine but the user has limited permissions.  I need it to install updates without needing a UAC prompt to log in.  Is there an update service or anything that can be used to do this?

**Comment by sostenesapollo12** [comment]
"limited permissions" explain this

**Comment by TDola** [comment]
The user account has no access to install anything, they are a limited user in Windows.  The install is run by the admin initially, but we want regular automated updates handled without the admin.

**Comment by TDola** [comment]
I have been able to slightly cheese it by making the application install to a different folder on the users C drive, one that they have full permission to.  But it still pops a useless UAC prompt where the user has to choose to run as user, and then it works.  Is there a way to remove that UAC prompt?

**Comment by sostenesapollo12** [comment]
Have you already tried to use the `electron-update` ?
I think that when it installs the update it automatically removes the .exe file

**Comment by TDola** [comment]
From what I can tell, perMachine=true forces a run as admin, and perMachine=false gives runasinvoker.  I need a way to have runasinvoker for perMachine=false.

I just had one successful test using this setup

        "nsisWeb": {
            "createDesktopShortcut": false,
            "createStartMenuShortcut": true,
            "menuCategory": true,
            "guid": "appname",
            "perMachine": false,
            "allowElevation": false,
            "differentialPackage": true,
            "include": "installer.nsh",
            "uninstallDisplayName": "${productName}",
            "runAfterFinish": false,
            "oneClick": true,
            "allowToChangeInstallationDirectory": false
        },

With the installer.nsh like this

```
!macro preInit
 SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\app\appname"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\app\appname"
 SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\app\appname"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\app\appname"
!macroend
```


```
!macro customInstall
  DetailPrint "Register appname URI Handler"
  DeleteRegKey HKCR "appname"
  WriteRegStr HKCR "appname" "" "URL:appname"
  WriteRegStr HKCR "appname" "URL Protocol" ""
  WriteRegStr HKCR "appname\DefaultIcon" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
  WriteRegStr HKCR "appname\shell" "" ""
  WriteRegStr HKCR "appname\shell\Open" "" ""
  WriteRegStr HKCR "appname\shell\Open\command" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME} %1"
!macroend
```

And using a script to create the folder with full permissions on everyones computer ahead of deployment.  This all results in a thoroughly convoluted solution.

**Comment by Mr1008** [comment]
If you have `perMachine=false` and `allowElevation=true` make sure you are writing to correct reg key with your protocol:

```nsis
${if} $installMode == "all"
    DeleteRegKey HKCR "${PROTOCOL_NAME}"
    WriteRegStr HKCR "${PROTOCOL_NAME}" "" "URL:${PROTOCOL_NAME}"
    WriteRegStr HKCR "${PROTOCOL_NAME}" "URL Protocol" ""  
    WriteRegStr HKCR "${PROTOCOL_NAME}\shell" "" ""
    WriteRegStr HKCR "${PROTOCOL_NAME}\shell\Open" "" ""
    WriteRegStr HKCR "${PROTOCOL_NAME}\shell\Open\command" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME} %1"
  ${else}
    DeleteRegKey HKCU "Software\Classes\${PROTOCOL_NAME}"
    WriteRegStr HKCU "Software\Classes\${PROTOCOL_NAME}" "" "URL:${PROTOCOL_NAME}"
    WriteRegStr HKCU "Software\Classes\${PROTOCOL_NAME}" "URL Protocol" ""  
    WriteRegStr HKCU "Software\Classes\${PROTOCOL_NAME}\shell" "" ""
    WriteRegStr HKCU "Software\Classes\${PROTOCOL_NAME}\shell\Open" "" ""
    WriteRegStr HKCU "Software\Classes\${PROTOCOL_NAME}\shell\Open\command" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME} %1"
  ${endif}
```

Also make sure you are cleaning after yourself when uninstalling:
```nsis
!macro customUnInstall
  ${if} $installMode == "all"
    DeleteRegKey HKCR "${PROTOCOL_NAME}"
  ${else}
    DeleteRegKey HKCU "Software\Classes\${PROTOCOL_NAME}"
  ${endif}
!macroend
```

**Comment by TDola** [comment]
Thank you @Mr1008 , I will add that in my next release.
