### ISSUE TITLE
electron-builder: command not found

### ISSUE THREAD

**Issue by mittalyashu** [electron-userland/electron-builder#3825]
* **Version**: 20.19.2

* **Target**: `dmg`, `mac`, `win`, `linux`

When I run this command `electron-builder`, it shows me this error.

![image](https://user-images.githubusercontent.com/29014463/56075790-e4db9300-5de5-11e9-837e-0c72e542a0d6.png)

**Comment by develar** [comment]
It is installed locally. See  https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by miguelyoobic95** [comment]
Hey guys, I have the module installed locally, in my node_modules, but somehow still get the above error.

This is in version `21.2.0` if electron builder.

**Comment by Icecubelegacy** [comment]
I am getting the same issue in version 22.3.5 of electron builder

**Comment by gschafra** [comment]
We're also getting this error (`Command "electron-builder" not found`) when trying to run electron-builder from within a `package.json` script (`"electron:win-build": "yarn build:prod && electron-builder build --win --ia32"`). Installing electron-builder globally in our case is NOT an acceptable solution (using CI infrastrukture).  In particular, the electron-builder docs recommends installing the package locally (using yarn, see https://www.electron.build/#installation), providing the "runner" in the `node_modules/.bin` directory, which is searched for by yarn (and npm?) automatically. In my case, this problem occured on a win agent (with yarn v1.22.5) and after upgrading electron-builder from v22.8.1 -> v22.9.1, which caused the `electron-builder` runner missing in the `node_modules/.bin` directory after a clean `yarn install` (whereby I cannot exclude that the runner existing until then was an artifact of a previous update/install).  Any help on this is very much appreciated.

**Comment by arnaudambro** [comment]
I cleaned my node modules and retried and it worked!
