### ISSUE TITLE
Updater folder

### ISSUE THREAD

**Issue by GitNomster** [electron-userland/electron-builder#3831]
* **Version**: 20.39.0

* **Target**: Win x64

When I create nsis and install it, the "{appName}-updater" folder, with installer in it, is created in the AppData/Local folder. How to prevent it?

**Comment by agjs** [comment]
@GitNomster Hey man, did you figure this one out?

**Comment by GitNomster** [comment]
@agjs Not yet. For now I plan to delete this file with the script after installation.

**Comment by Ajeey** [comment]
@GitNomster Why do you want to prevent it? I believe it is for caching downloaded updates.

**Comment by GitNomster** [comment]
@Ajeey Maby, but i'm not using builder auto-update, so i want to delete this file.

**Comment by develar** [comment]
> i'm not using builder auto-update, so i want to delete this file

PR to handle this feature request will be accepted.

Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
