### ISSUE TITLE
Question: Publish to multiple S3 providers 

### ISSUE THREAD

**Issue by douglassllc** [electron-userland/electron-builder#3832]
* **Version**: 0.40.2

* **Version**: 4.0.6

* **Target**: linux, mac, and win

I was wondering if their is a way to publish to more then one S3 provider during the same publish command.  My current attempt, seems to upload to last one in the list of publish entries.

So what I am hoping todo is publish to 3 different locations, 2 S3 providers and 1 GitHub provider.  Currently what happens is the last S3 provider and the 1 GitHub provider are used during the publish.

Thanks for any recommendations.

**Comment by develar** [comment]
Publishing is done to all, auto-update for first one. Does it work in 21.0.5?

**Comment by douglassllc** [comment]
@develar I'll check and get back with you in the next few days.
