### ISSUE TITLE
afterAllArtifactBuild not working

### ISSUE THREAD

**Issue by douglassllc** [electron-userland/electron-builder#3837]
* **Version**: 0.40.2

* **Version**: 4.0.6

* **Target**: linux, mac, and win

I have the following in my package.json
`"afterAllArtifactBuild": "tasks/afterBuild.js"`
The `afterBuild.js` script returns a string (i.e. filePath) to an additional artifact that I would like published.  Example: `'/path/to/project/dist/product-latest-mac.dmg'`.  This is to allow links from out website to always point at the latest version. 

However, when I run the publish, I see that my script (`afterBuild.js`) returns the string, but I see the following error in the console.

`cannot expand pattern "${channel}/${os}": macro os is not defined`. 

All of my original artifacts are published properly to the s3 bucket in the channel/os directory, but the file added by the `afterBuild.js` script is not uploaded and I get the following error on the console.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Product@0.9.0-beta publish:mac: `rimraf dist && electron-webpack && electron-builder build -m -p always`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Product@0.9.0-beta publish:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-04-18T14_18_50_771Z-debug.log
```

What am I missing on my configuration or usage of afterAllArtifactBuild

**Comment by rimonhanna** [comment]
have you figured out what was the issue?

**Comment by douglassllc** [comment]
@rimonhanna This remains an issue for me.  I would like to see this resolved, however I went ahead and created a afterPack script that creates the extra file I wanted and uploads it directly to S3.
