### ISSUE TITLE
Configurable knownAlwaysIgnoredDevDeps

### ISSUE THREAD

**Issue by Ciantic** [electron-userland/electron-builder#3839]
* **Version**: master

This hard coded list of exclusions is a pain point, if one searches back old issues:

https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/util/packageDependencies.ts#L31-L37

I currently have a problem that I need to add dependency there `cli-highlight`. Because one peer dependency of mine has that incorrectly in their package.json. I think the list of ignored dependencies should be configurable for each build.

It should be named `ignoredDependencies` or something simple, if it's made configurable.

**Comment by develar** [comment]
Since 21.0.5 not required any more.
