### ISSUE TITLE
How to get portable package path

### ISSUE THREAD

**Issue by oyljerry** [electron-userland/electron-builder#3841]
* **Version**: 20.39.0

* **Target**: Windows

I have build a portable package (pkg.exe) on windows, when I put in C:\Users\xxxx\Documents\app folder to run, it will extract files into C:\Users\xxxx\AppData\Local\Temp\<guid>.tmp\app folder, then launch main/render process. 

So, My question is that: when my js running in electron render process, How can it get the path of pkg.exe folder (such as C:\Users\xxxx\Documents\app)

Thanks in advance.

**Comment by cxwithyxy** [comment]
#3186 

issues/3186 it mentioned `process.env.PORTABLE_EXECUTABLE_DIR`

I tried. But it cannot work now

**Comment by oyljerry** [comment]
> process.env.PORTABLE_EXECUTABLE_DIR

Thanks, It works.
