### ISSUE TITLE
Code Signing with EV SHA2 Certificate

### ISSUE THREAD

**Issue by dotconnor** [electron-userland/electron-builder#3842]
* **Version**: 20.39.0

* **Target**: Windows

Hey, I'm trying to code sign a windows app on windows but it fails every single time.
Its an EV certificate from DigiCert. The build fails with the following error:

```
The following certificates were considered:
    Issued to: A-1 Motion & Design, Inc
    Issued by: COMODO RSA Code Signing CA
    Expires:   Fri Apr 05 19:59:59 2019
    SHA1 hash: F2DDEBB105E57FBC747E790E6BE432788D5639D8

    Issued to: A-1 Motion & Design, Inc
    Issued by: DigiCert EV Code Signing CA (SHA2)
    Expires:   Wed Apr 22 08:00:00 2020
    SHA1 hash: 5AA3003505119C7E465DB2DCC0DE2AC44F37A5E1

    Issued to: 2d68f8c047e2a7c0
    Issued by: Token Signing Public Key
    Expires:   Fri Mar 30 14:28:39 2018
    SHA1 hash: 2CC5673A0E72579EB1A5DB1B6B244D5EC82E3F39

After EKU filter, 2 certs were left.
After expiry filter, 1 certs were left.
After Hash filter, 0 certs were left.
After Private Key filter, 0 certs were left.

SignTool Error: No certificates were found that met all the given criteria.
```

The only I have set in the config for code signing is
```
certificateSubjectName: 'A-1 Motion & Design, Inc'
```

**Comment by roby65** [comment]
I have the same problem, it looks like it is looking for the wrong SHA2 hash and discards the correct valid signing certificate.
How did you fix this?

**Comment by dotconnor** [comment]
@roby65 I'm not sure I ever figured out what was wrong, we now just do all of our code signing on macOS using this guide: https://www.electron.build/tutorials/code-signing-windows-apps-on-unix.

**Comment by roby65** [comment]
I removed all expired certs and that fixed the problem!
