### ISSUE TITLE
How to set the language of the generated exe file?

### ISSUE THREAD

**Issue by aliaga-d** [electron-userland/electron-builder#3847]
* **Version**: 
electron-builder 20.39.0 
* **Target**: 
  Windows

This is a question: If I want to only create an exe file (not an installer) I am assuming I have to use "target":["portable"]  (I have not gotten to make this work though - if there is a simple example I will be very greatful)

My question is how can you set the language property of the executable to something other than english??

This is similar to 
[https://github.com/electron-userland/electron-builder/issues/768](url)
where in the final post dharders commented on how to set the language of the installer by setting
"language":"1041" to the nsis options.
But how about if we are using not nsis but portable?

**Comment by jaimecoj** [comment]
Any update?
