### ISSUE TITLE
Apps Installed into /Applications on OSX Always Damaged

### ISSUE THREAD

**Issue by ractoon** [electron-userland/electron-builder#385]
After completing a build (app is fully signed) and uploading to a server I'm able to download the dmg and copy the app to the `/Applications` directory successfully. However, when attempting to run the app I receive the error message `App is Damaged Can’t Be Opened` with the options to cancel or move to trash.

If I change the install path to my specific user's Applications directory in the config such as:

````
"osx": {
      "identity": "{my developer ID string}",
      "contents": [
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Users/myusername/Applications"
        },
        {
          "x": 130,
          "y": 220,
          "type": "file"
        }
      ]
    },
````

And go through the same process of upload/download and install I'm able to successfully run the application. It seems like there's something going on with permissions for the root `/Applications` directory which brings up two questions:

1) Is there a way to allow the app to run in the default `/Applications` directory with a setting or additional config?

2) If that is not possible is there a way to specify to install in the User's directory dynamically? I've tried setting path to `$HOME/Applications` but it did not work unfortunately.

Any insight you can offer would be greatly appreciated. Thanks!

**Comment by develar** [comment]
OS X bug. Just restart. https://github.com/electron-userland/electron-packager/issues/323

You can see error message in the Console (standard OS X app — open it, see All Messages)

**Comment by ractoon** [comment]
Ahh, that did the trick. Everything working as expected now, thanks again!

**Comment by ccnokes** [comment]
I'm having the same issue as @ractoon but restarting my computer did not clear it up, and unlike the issue in the electron-packager (https://github.com/electron-userland/electron-packager/issues/323 and here http://www.openradar.me/23614087), the CFBundleExecutable name didn't change between builds. Am I missing something? I thought it was a server configuration issue because the dmg works directly off of our CI server but not when downloaded from a remote IIS server. Is that similar to what you were experiencing @ractoon?

**Comment by develar** [comment]
@ccnokes error message in the Console (standard OS X app — open it, see All Messages) is the same?

**Comment by ivanovit** [comment]
We had the same issue but we didn't want to ask our users to restart their machines(also we didn't have a mechanism to notify them). So we decided to add a symlink **Electron -> AppName**. Not the best option but this is our solution for now. This symlink can be created in the [afterPack build option](https://github.com/electron-userland/electron-builder/wiki/Options#build).


```javascript
		
var Promise = require("bluebird"),
      fs = Promise.promisifyAll(require("fs"));

devMetadata: {
			build: {
				afterPack: function (params) {
					var currentExecutable = params.options.productName,
						appName = params.options.productName + ".app",
						oldExecutable = path.join(params.appOutDir, appName, "Contents", "MacOS", "Electron");
					return fs.symlinkAsync(currentExecutable, oldExecutable);
				}
			}
		}
```
