### ISSUE TITLE
electron-updater cannot download release asset in github private repo on windows

### ISSUE THREAD

**Issue by DonaldChiang** [electron-userland/electron-builder#3851]
* **Version**:  20.28.4

* **Target**:  nsis

I am using electron-updater to do auto-update in my app and my source code contains on private GitHub repo.

I already set publish setting in electron-builder.yml like:

```
publish:
- provider: github
  owner: owner
  repo: repo
  private: true
  token: token
```

Now I can update my app on MacOS but Windows. In Windows, electron-updater can get latest release asset url but download, it seems like electron-updater call GitHub api without access_token or Authorization on Headers, please help. Thanks!

![image](https://user-images.githubusercontent.com/29910065/56624474-9642ba00-666b-11e9-8963-bdc9d5cbca7e.png)

It seems like electron-updater resolve release assets url in PrivateGitHubProvider with GH_TOKEN and call doDownload in HttpExecutor without GH_TOKEN

UPDATE:
I saw there error log when testing update locally:

```
updater cache dir: C:\Users\UserName\AppData\Local\AppName
No cached update info available
Download block maps (old: "https://api.github.com/repos/owner/repo/releases/assets/12203630.blockmap", new: https://api.github.com/repos/owner/repo/releases/assets/12203630.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 5 MB
```

**Comment by DonaldChiang** [comment]
Downgrade solve this problem
```
"electron": "4.0.6",
"electron-builder": "20.34.0",
"electron-updater": "3.2.3"
```

**Comment by grantcv1** [comment]
Due to bugs in Electron 4.X (HTML5 dropdown lists don't work)  that are only fixed in Electron 5.0, downgrading to 4.X is not an option for me. This is depressing. I struggled 18 months ago to get this work and after days of running into issue after issue, I just gave up. I was hopeful that something would be different now, but this remains of minefield of bugs.

**Comment by mozainuddin** [comment]
I'm wondering the same thing if there is a solution without downgrading...
I have the exact issue in Windows, however, the code works perfectly on Mac.

Windows 10
---
node: v12.14.1
npm: v6.13.4
---
Electron: v7.1.11
electron-builder: v22.3.2
electron-updater: v4.2.0

**Comment by mozainuddin** [comment]
I'm wondering the same thing if there is a solution without downgrading...
I have the exact issue in Windows, however, the code works perfectly on Mac.

- Windows 10
- node: v12.14.1
- npm: v6.13.4

- Electron: v7.1.11
- electron-builder: v22.3.2
- electron-updater: v4.2.0

**Comment by hmpargi** [comment]
Yes, I am having the same issue I work on Mac but not on windows.  I am not sure if they going to release any fix for this.

**Comment by mozainuddin** [comment]
Issue fix for me after updating electron-updater to v4.2.2 =D

**Comment by hmpargi** [comment]
> Issue fixed for me after updating electron-updater to v4.2.2 =D
> 
> * Windows 10
> * node: v12.16.0
> * npm: v6.13.4
> * electron: 8.0.1
> * electron-builder: 22.3.2
> * electron-updater: 4.2.2

Please can you post the publish settings from package.json and setFeedURL.  I am having still problems on windows.

**Comment by mozainuddin** [comment]
> 
> 
> > Issue fixed for me after updating electron-updater to v4.2.2 =D
> > 
> > * Windows 10
> > * node: v12.16.0
> > * npm: v6.13.4
> > * electron: 8.0.1
> > * electron-builder: 22.3.2
> > * electron-updater: 4.2.2
> 
> Please can you post the publish settings from package.json and setFeedURL. I am having still problems on windows.

Hello @hmpargi, please check my reply in this post [https://github.com/electron-userland/electron-builder/issues/4621#issuecomment-589920650](url)

**Comment by clampinou** [comment]
"build": {
... ,
"files": [
"node_modules",
"build",
"app",
"assets",
"capacitor.config.json"
]
}

This worked for me!
