### ISSUE TITLE
Installing dependencies in PKG preinstall script

### ISSUE THREAD

**Issue by olmokramer** [electron-userland/electron-builder#3853]
* **Version**: 20.19.2

* **Target**: Mac-PKG

Is it possible to include a `.pkg` file (specifically, [OSXFuse](https://osxfuse.github.io/)'s) and run that in my pkg's preinstall script? Our application has OSXFuse as a dependency, and we would like to distribute its installer with ours.

I've seen [this issue](https://github.com/electron-userland/electron-builder/issues/3436) but that answer's about dmg builds, not pkg.

Of course it's possible to include the installer in the `extraFiles` option, and then run the installer in the `postinstall` script, but I want to run the installer in the `preinstall` script, and bail the installation of our application if it fails.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
