### ISSUE TITLE
Incorrect path in `TryExec` for some filenames

### ISSUE THREAD

**Issue by mburtscher** [electron-userland/electron-builder#3856]
* **Version**: 20.38.5

* **Target**: AppImage

We are building an app with desktop integration enabled. So when launched on Linux it will ask for integration. If confirmed, a file like the following is created:

**/home/USER/.local/share/applications/appimagekit-fusion-timetracking.desktop**

```
[Desktop Entry]
Name=Time Tracking
Comment=Time Tracking desktop client
Exec="/home/USER/Time Tracking 4.1.0.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-fusion-timetracking
StartupWMClass=Time Tracking
X-AppImage-Version=4.1.0
Categories=Utility;
X-AppImage-BuildId=1IlWXaN0trZZYfkIbwJBiubCfAY
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_Time Ty9afMm/AppRun
TryExec=/home/USER/Time\\sTracking\\s4.1.0.AppImage
```

As you can see I used a filename of `Time Tracking 4.1.0.AppImage` in this example. When a filename with spaces is used the filename is incorrectly escaped for the `TryExec` parameter. This will prevent the application from being shown in the application menu (Ubuntu).

**Incorrect = Not working**

* `TryExec=/home/mburtscher/Time\\sTracking\\s4.1.0.AppImage` (Original)
* `"TryExec=/home/mburtscher/Time Tracking 4.1.0.AppImage"`

**Correct = Working**

* `TryExec=/home/mburtscher/Time Tracking 4.1.0.AppImage`
* `TryExec=/home/mburtscher/Time\sTracking\s4.1.0.AppImage`

**Comment by develar** [comment]
Fixed in 21.0.5
