### ISSUE TITLE
Code signing windows app using SHA256

### ISSUE THREAD

**Issue by incurito** [electron-userland/electron-builder#386]
While code signing works flawlessly in AppVeyor (windows environment), the installer is signed using SHA1. Win10 requires at least SHA256 and I'm unable to find documentation to specify SHA256 for code signing. Whereas, code signing windows app in OSX environment seems to use SHA256. Am I missing something?

**Comment by develar** [comment]
Confirmed, fixed, release will be today.

**Comment by develar** [comment]
Release is still not production ready — yet another fix — we must use dual-code sign (sha1+sha256) to not break old Windows version. And sign must be timestamped (as OS X already does).
