### ISSUE TITLE
Electron App Doesn't Launch After Packaging

### ISSUE THREAD

**Issue by mswilson4040** [electron-userland/electron-builder#3860]
* **Version**: 
20.39.0

* **Target**: 
Any Target / Windows / Portable

My application is running just fine, but after packaging the application using `electron-builder`, the app doesn't launch. The exe gets produced and I don't see any errors/warnings in the console.

Is there any logging I can enable on the app or any other steps I can do to try and figure out what's going on? Here is my full package.json below. I think the `build` property is the most important (?)

Basically, I'm just trying to package my app into a single exe so I can distribute it. Forgive the unused scripts in the package.json as it's all my attempts at trying to package an app. I will say, the script `build-win32` works fine. But, it doesn't end up as a single exe so I can't use it.

I am running `npm run dist`

```
{
  "name": "MyApp",
  "version": "1.0.0",
  "description": "my test app",
  "main": "main.js",
  "build": {
    "asar": true,
    "appId": "my.app",
    "productName": "MyApp",
    "win": {
      "target": "portable"
    }
  },
  "scripts": {
    "start": "electron .",
    "build-win32": "electron-packager . --asar --platform=win32 --arch=x64 --overwrite --executableName BTSniffer",
    "build-mac": "electron-packager . --asar",
    "postinstall": "electron-builder install-app-deps",
    "rebuild": "electron-rebuild -w sqlite3 -p",
    "forge": "electron-forge package",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "asar": "^1.0.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "css-loader": "^2.1.1",
    "electron": "^4.1.3",
    "electron-builder": "^20.39.0",
    "electron-debug": "^2.2.0",
    "electron-packager": "^13.1.1",
    "electron-rebuild": "^1.8.4",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2"
  },
  "dependencies": {
    "express": "^4.16.4",
    "glob": "^7.1.3",
    "knex": "^0.16.3",
    "request-promise": "^4.2.4",
    "sql.js": "^0.5.0"
  }
}


```

**Comment by Slapbox** [comment]
@mswilson4040 your best bet is to enable devtools and open them on start in production, or do you mean the app doesn't even run? I strongly recommend using [electron-unhandled](https://github.com/sindresorhus/electron-unhandled), which will probably help you get to the bottom of this very quickly.

**Comment by mswilson4040** [comment]
@Slapbox. Did that, it crashes before it's got a chance to open the dev tools. I did, however figure out what the issue was. It was a missing module issue. I didn't have the module referenced anywhere in my project so that's a little confusing. The module in question was `request`

I figured this out by finding an electron logging package on npm (`electron-log`). I then wrapped my entire `main.js` file in a `try/catch` and logged the exception with `electron-log`. After that, I could then open the logfile and review the exception.

**Comment by Slapbox** [comment]
Glad you figured it out!

Electron-unhandled is like automatically wrapping everything in a try/catch. I'm not sure of _exactly_ how it works, but that's pretty much the effect it has. Strongly recommend it, as it's super easy to implement and will probably save you hours or days. Also helps prevent production crashes from unforeseen bugs.

If you're all set, remember to close your issue.

**Comment by danidan95** [comment]
> @Slapbox. Did that, it crashes before it's got a chance to open the dev tools. I did, however figure out what the issue was. It was a missing module issue. I didn't have the module referenced anywhere in my project so that's a little confusing. The module in question was `request`
> 
> I figured this out by finding an electron logging package on npm (`electron-log`). I then wrapped my entire `main.js` file in a `try/catch` and logged the exception with `electron-log`. After that, I could then open the logfile and review the exception.

can you attach here the example, please?

**Comment by Slapbox** [comment]
@danidan95 put this in your renderer process and your main process:

```js
const unhandled = require('electron-unhandled');

unhandled();
```

**Comment by pablogalarza** [comment]
> @Slapbox. Did that, it crashes before it's got a chance to open the dev tools. I did, however figure out what the issue was. It was a missing module issue. I didn't have the module referenced anywhere in my project so that's a little confusing. The module in question was `request`
> 
> I figured this out by finding an electron logging package on npm (`electron-log`). I then wrapped my entire `main.js` file in a `try/catch` and logged the exception with `electron-log`. After that, I could then open the logfile and review the exception.

Hi @Slapbox...And how u do that? (const log = require('electron-log');)... require is needded to use electron-log...isent it?

**Comment by Slapbox** [comment]
@pablogalarza  put it in your preload instead of renderer.

**Comment by pablogalarza** [comment]
other way...when u execute .exe from console, u can see errors

**Comment by Slapbox** [comment]
I don't know what you're trying to ask. If you still need help please take the time to make clear where you're stuck and what the issue is.

**Comment by Slapbox** [comment]
You can (and must) add the electron-unhandled code in the main process also for it to work.

Are you using electron-log as your logger? If so, you can configure the log function electron-unhandled will use when it encounters an unhandled error.

In our main process, we run this before almost any other code:

```js
  const unhandled = require('electron-unhandled');
  unhandled({
    logger: log.error,
  });
 ```
 
 With `log.error` being the function provided by electron-log. Hope this helps!
