### ISSUE TITLE
Create signed NSIS and unsigned APPX

### ISSUE THREAD

**Issue by idoodler** [electron-userland/electron-builder#3861]
* **Version**: 20.31.2

* **Target**: Windows

I need to create a signed NSIS installer for our own distribution channel and an unsigned APPX package for Windows Store submission.

Right now I have to manually trigger two builds, one with the `certificateFile` and `certificatePassword` property and one without.

It would be quite handy to be able to define this property per target. Is there any known workaround?

**Comment by idoodler** [comment]
Any input on this?

**Comment by hotlong** [comment]
+1

**Comment by mistersdevelopment** [comment]
I am also experiencing this issue.

**Comment by danielweck** [comment]
+1 !

**Comment by idoodler** [comment]
Any update?

**Comment by danielweck** [comment]
Just thinking, what about an environment variable such as `CSC_IDENTITY_AUTO_DISCOVERY` (true by default, but when set to false, this makes ElectronBuilder skip the automatic discovery of a code signing certificate / entity defined at the system level ... for example KeyChain in MacOS)
I set this env var to false when I want to create unsigned DMG builds for testing.

**Comment by koenoe** [comment]
I'm still experiencing this issue too.

@danielweck That sounds good to me :-)
