### ISSUE TITLE
Can't include shared libraries in linux for snap

### ISSUE THREAD

**Issue by farafonov-alexey** [electron-userland/electron-builder#3862]
* **Version**: 20.38.5
* **Target**:  linux x64 snap
* **Host**:   Ubuntu 18.04.2 x64
* **Node version**: v10.15.3

How can I include shared libraries?

I've used this linux related builder config section:
```
  "linux": {
    "target": ["AppImage", "snap"],
    "extraFiles":
      [
        {
          "from": "node_modules/node-atol-wrapper/build/Release",
          "to": "usr/lib",
          "filter": ["lib*"]
        }
      ]
  },
```
Inside /build/linux-unpacked/ directory successfully created usr/lib/ folder with some *.so files
The AppImage version of the app starts without a problem!

When starting the snap I get an error
> Error: libfptr10.so: cannot open shared object file: No such file or directory
>     at process.module.(anonymous function) [as dlopen] 

I've inspect two folders: 
1) /tmp/.mount_{project}.XXXXX/ for AppImage and found /usr/lib inside it with the file mentioned above. So its' fine.
2) /snap/${project}/current/ for snap and found **2(two)** related folders : 
-    /usr/lib  with some deafult libs and 
-    /**usr_1**/lib/ with our extraFiles libs

I think that's why snap app can't locate included *.so files and i don't know why this usr_1 folder is created.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. Pull request or donation (discuss in prior) welcome.
