### ISSUE TITLE
How to disable packaging when nodeGypRebuild is true

### ISSUE THREAD

**Issue by RobinCodeX** [electron-userland/electron-builder#3866]
* **Version**: 20.39.0

* **Target**: any

I'm using `electron-builder.build({config: {nodeGypRebuild: true}})` to build my C++ addons, but the packaging is unwanted.

**Comment by develar** [comment]
Do you mean that you want just rebuild native deps?

**Comment by RobinCodeX** [comment]
> 
> 
> Do you mean that you want just rebuild native deps?

Yes
