### ISSUE TITLE
Windows/NSIS: installerHeaderIcon is pixelated

### ISSUE THREAD

**Issue by warpdesign** [electron-userland/electron-builder#3867]
* **Version**: 20.39.0

* **Target**: Windows/NSIS/x64

The `installerHeaderIcon` appears pixelated/ugly. I didn't specify one so I am assuming it's using the application's icon, which is a 512x512 png file that's crystal clear:

![icon-512x512](https://user-images.githubusercontent.com/199648/57011987-8a736c80-6c04-11e9-9e98-f01d6966d0b6.png)

I tried reducing the icon size to 256x256 but it's still pixelated in the end:

![Capture d’écran 2019-05-01 à 11 08 42](https://user-images.githubusercontent.com/199648/57011679-35832680-6c03-11e9-9869-880cba21e179.png)

What's the suggested size for the `installerHeaderIcon`? Is there a way to make it look clear and not pixelated?

**Comment by warpdesign** [comment]
Note that I tried on 1080p and high DPI monitors: the problem is the sam.

**Comment by Mr1008** [comment]
Can you try to convert png to ico format? I think NSIS does not interpolate while scaling properly. When you convert it to ICO format, it would contain various sizes and NSIS will take correct one.

**Comment by ImaGrimGrimGuy** [comment]
I have this same issue, even when specifying the icon for the NSIS target to be a .ico file with multiple resolutions, is there a specific resolution that is required by NSIS?

**Comment by hmdfthid** [comment]
Problem still exists in electron-builder version 22.10.5

**Comment by RoboZoom** [comment]
Following up - running into the same issue. If anyone has found a solution to this, would be appreciated.

Running v23.0.3

**Comment by asphub** [comment]
This issue is not resolved yet. Do anyone have any suggested solution for this?
