### ISSUE TITLE
DMG builder does not support languages mentioned in docs

### ISSUE THREAD

**Issue by jahidzaynal** [electron-userland/electron-builder#3869]
* **Version**:  20.39.0
* **Target**:  DMG

I'm trying to add multiple licence files as per documentation at [DMG configuration](https://www.electron.build/configuration/dmg), but while that doc says I can use languages listed in [here](https://github.com/meikidd/iso-639-1/blob/master/src/data.js) - that isn't true. There are languages that `dmg-builder` does not support, and you can see this in this [much smaller subset](https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmgLicense.ts#L135) - errors with
```
Error: Cannot determine region code for el_EL
```
This happens with multiple languages, the ones I've encountered are `el`, `sl`, and `id`.
If you just add language code without region as `license_[lang].txt` it automatically appends the capital form of `lang` to the end as `[lang]_[LANG]` and it doesn't find that in the `regionCodes` list.

Also, the default buttons list isn't complete [here](https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/licenseDefaultButtons.ts) - you should expect the default to at least match the region codes, but you end up with licence text in, for example, Turkish but buttons in English.

**Comment by HeikoH** [comment]
same with `ar`; having a license file called `license_ar.txt` results in https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmgLicense.ts#L126 being called with `ar_SA`, which cannot be found in `regionCodes`

**Comment by JaAlSaDev** [comment]
> same with `ar`; having a license file called `license_ar.txt` results in https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmgLicense.ts#L126 being called with `ar_SA`, which cannot be found in `regionCodes`

I'm having this exact issue right now.

Any solutions?
