### ISSUE TITLE
msi crash

### ISSUE THREAD

**Issue by gggin** [electron-userland/electron-builder#387]
just use "dist:win64":"build --platform win32 --arch x64"
npm run dist
two package.json (dev version and production version)

{
  "name": "test",
  "version": "1.0.2",
  "description": "",
  "main": "main.js",
  "dependencies": {
    "babel-preset-react": "^6.3.13",
    "babelify": "^7.2.0",
    "electron-builder": "^3.17.1",
    "jQuery": "^1.7.4",
    "jsdom": "^7.2.2",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "shadowsocks": "^1.5.3"
  },
  "devDependencies": {
        "electron-builder": "^3.1.2",
        "electron-prebuilt": "^0.37.2"
  },
  "build": {
      "app-bundle-id": "test.test.test",
      "app-category-type": "test.tes.test.productivity",
      "iconUrl": "http://eatodo.s3.amazonaws.com/icon.ico",
      "win": {
        "noMsi": false
      }
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "install-app-deps",
    "start": "electron ./app --enable-logging",
    "dev": "NODE_ENV='development' npm run start",
    "dist": "npm run dist:osx && npm run dist:win32 && npm run dist:win64",
    "dist:osx": "build --platform darwin",
    "dist:win32": "build --platform win32 --arch ia32",
    "dist:win64": "build --platform win32 --arch x64"
  },
  "author": "gggin",
  "license": "ISC"
}

log: everything is good!

node 6.0.0
npm 3.8.6

on which system do you want to create installers (OS X, Windows or Linux)
Windows

**Comment by develar** [comment]
https://github.com/electron/windows-installer/issues/40#issuecomment-218072177 So, close as invalid?

**Comment by gggin** [comment]
just close this, but can you answer my question in electron/windows-installer#40?

**Comment by develar** [comment]
@gggin No, sorry, but for me its is a crazy windows ***, sorry. See https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md
