### ISSUE TITLE
Setting Last Quartet of Windows Store Version

### ISSUE THREAD

**Issue by semireg** [electron-userland/electron-builder#3875]
* **Version**: 20.39.0
* **Target**: win/appx

Thank you for this wonderful module. I've been successfully publishing my app to the Microsoft Store and Mac App Store (MAS). Huzzah! 

Sending multiple builds of the same version to the MAS works fine by setting Mac --> "bundleVersion": "X0Y0Z00N" where app's version is X.Y.Z and the build number is logically N for that version.

[Docs](https://www.electron.build/configuration/configuration#Configuration-win) read, ```buildVersion String - The build version. Maps to the CFBundleVersion on macOS, and FileVersion metadata property on Windows. Defaults to the version.```

Is this buildVersion string added to appx files? I started doing beta testing in the Microsoft Store. They recommend what they call a "Package flight" where you specify which user accounts get access to certain packages (appx). However, when I upload two of the "same" X.Y.Z.0 (different buildVersion, N) I get an error:

```All .msix and .appx packages (including previously published and currently uploaded) must be uniquely identified by their full names. You have provided two packages with the full name SemiregIndustriesLLC.MyApp_X.Y.Z.0_X64_ which have different contents. Please remove one of these packages, or increment current package versions to continue.```

I think we need to set the build number as the last portion of the appx version. Is there any way to change `X.Y.Z.0` to `X.Y.Z.N` where N is the buildVersion?

**Comment by semireg** [comment]
Digging into the codebase I found an oddity. Where does [this call to getVersionInWeirdWindowsForm](https://github.com/electron-userland/electron-builder/blob/c84ecff171dac128a1d5552a1287a375dc57df07/packages/app-builder-lib/src/targets/AppxTarget.ts#L188) go to? I can't Google [any reference](https://www.google.com/search?client=safari&rls=en&q=getVersionInWeirdWindowsForm&ie=UTF-8&oe=UTF-8) to it.

**Comment by semireg** [comment]
Thanks to the GitHub link in the source I finally tracked down a conversation about this segment of code, https://github.com/electron-userland/electron-builder/issues/2635. 👍 

Still need to figure out the best way to rectify this for appx, passing in false, etc...

**Comment by develar** [comment]
Thanks for donation.

Well, it is so by intention — https://github.com/electron-userland/electron-builder/issues/2979

Interesting....

**Comment by semireg** [comment]
You're welcome! I really appreciate the work that's gone into this project.

Thanks for digging up the issue reference. More info the better. Time to open a ticket with Microsoft... 🎺

**Comment by develar** [comment]
As you have donated and need some urgent solution, and as no one except MS guys can clear up this thing, I will just add option to force settings build number (in 1 hour).

**Comment by semireg** [comment]
That's appreciated so I can test, but I unfortunately expect MS to reject the app with the same error referenced in #2979. If you make that change I'll test and report back.

Btw, is there a guide on setting up a proper electron-builder dev environment? I forked the project, cloned on my machine, built using `yarn compile` and I'm unsure how to "install" the resulting npm module in my project. Is there a doc that clarifies that process? That way, I could do this change/testing myself. Self serve 🙌

**Comment by develar** [comment]
`setBuildNumber` option is added to `appx`.

**Comment by develar** [comment]
> is there a guide on setting up a proper electron-builder dev environment

https://github.com/electron-userland/electron-builder/issues/2781#issuecomment-380332942

In short — after `yarn compile`, you don't need to publish, just set `NODE_PATH` to force resolving of electron-builder to your local installation instead of installed.
