### ISSUE TITLE
Chore feature request: make "Target.name" property located in "app-builder-lib/src/core" union type

### ISSUE THREAD

**Issue by vladimiry** [electron-userland/electron-builder#3877]
The `name` property is currenlty defined as a [raw string](https://github.com/electron-userland/electron-builder/blob/4d92abfd5c7b4ee4774b3055c9752d75bcf5c423/packages/app-builder-lib/src/core.ts#L75). Making it union type like `"appimage" | "snap" | "nsis" ...` would improve the type safety. So it would be possible to distinguish the targets by `name` in a type-safe way.

**Comment by develar** [comment]
Thanks for suggestion. We have quite a lot of targets, I think using of union type will only complicate development.

**Comment by vladimiry** [comment]
Well, I think that should have been done from the day one an so I agree at the current point it would complicate things for the end users.
