### ISSUE TITLE
App Icon sets to default after signing the application

### ISSUE THREAD

**Issue by iamsush** [electron-userland/electron-builder#3878]
* **Version**:  "20.39.0"
* **Target**: Windows

App Icon (in the taskbar) sets to default electron icon after signing the application. If the app is not signed, everything works fine. Let me know if you need more details.

**Comment by iamsush** [comment]
Actually, electron-builder was signing all the exe(s) present in my resource folder. But I wanted electron-builder to sign only the final exe of my application. So for that, I tried _signAndEditExecutable = flag_, which resolved my concern to sign only the final exe, but created the above issue. 

I removed that property, and now the application is working fine. 

(PS: Please explain certain properties in the docs for better understanding. As for e.g., I cannot infer much with this statement, 
_signAndEditExecutable = true Boolean - Whether to sign and add metadata to executable. Advanced option._
Thanks.)

**Comment by adriendurepaire** [comment]
@iamsush have you found a solution to avoid the code signing of the executables inside your resource folder, without losing your app icon?

**Comment by Brouilles** [comment]
Same problem here. Any solution?
