### ISSUE TITLE
While creating windows appx package electron-builder is taking default icon for app

### ISSUE THREAD

**Issue by NehaTawar** [electron-userland/electron-builder#3879]
* **Version**: 20.40.2

* **Target**: windows

I am creating my app using ionic cordova and after creating build for windows. Using electon-builder to create the appx file. By default appx is getting created inside dist folder.
Now the issue which I am facing is whenever I create a build while launching I see only **electron default Icon**, even if i did set the buildDerectories and icon property properly.

![image](https://user-images.githubusercontent.com/16165958/57302510-f704d480-70f8-11e9-87a1-ff2b962271c1.png)

I have set properties in **package.json** file as below:

```
{ 
     "build": {
        "extraFiles": [
          "some-internal-plugin-dist"
        ],
        "appId": "myCompany.myApp",
        "nsis": {
          "perMachine": true,
          "oneClick": false,
          "allowToChangeInstallationDirectory": true
        },
        "squirrelWindows": {},
        "files": [
          "electron.js",
          "www/**/*"
        ],
		 "directories": {
		"buildResources": "www/build"
		},
		"appx": {
		  "identityName": "myCompany.myApp",
		  "publisher": "CN=number",
		  "publisherDisplayName": "my publisher name",
		  "applicationId": "myApp",
		  "displayName": "myApp"
		},
        "win": {
          "certificateFile": "./certs/CordovaApp.wincert.pfx",
          "icon":  "www/build/win.ico",
          "publisherName": "my Company",
          "target": [
            {
              "target": "nsis",
              "arch": [
                "ia32"
              ]
            }
          ]
        },
        "nodeGypRebuild": "false",
        "npmRebuild": "false"
      }
    }
```
Please let me where am i doing wrong and what exactly should I set the properties?
How and where to specify the assets all the assets for windows?
So to resolve this can anyone please help?

**Comment by semireg** [comment]
I don't know why yours isn't working correctly, but I can share details of my app's setup.

Here's a photo of my icons in vscode. 
![2019-05-09 at 9 47 AM](https://user-images.githubusercontent.com/1819762/57462973-83211400-723f-11e9-879f-2e1eae947f5e.png)

Here's the relevant properties in my "build" from package.json:

```
  "build": {
    "productName": "Label LIVE",
    "appId": "com.semireg.LabelLIVE",
    "buildVersion": "10305001",
    "artifactName": "${productName}-${version}-${buildVersion}.${ext}",
    "generateUpdatesFilesForAllChannels": false,
    "buildDependenciesFromSource": true,
    "nodeGypRebuild": false,
    "npmRebuild": false,
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json",
      "embedded.provisionprofile"
    ],
    "win": {
      "target": [
        "nsis"
      ],
      "extraFiles": {
        "from": "app/win-dlls/"
      }
    },
    "nsis": {
      "oneClick": true,
      "perMachine": false,
      "warningsAsErrors": true,
      "runAfterFinish": true
    },
    "appx": {
      "publisher": "CN=122121212-12121-1212-12121-121212121212",
      "backgroundColor": "transparent"
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    },
  },
```

For exact sizes of the images you'll want to consult https://www.electron.build/configuration/appx#appx-assets.

Now, after all this, my setup still isn't perfect. My icon is still too small, but it's something I'm living with for the moment.

![2019-05-09 at 9 54 AM](https://user-images.githubusercontent.com/1819762/57463470-7cdf6780-7240-11e9-8e67-33004a6ca111.png)

**Comment by NehaTawar** [comment]
sure will try and let you know @semireg

**Comment by NehaTawar** [comment]
This is what worked for me:

1. Downgraded electron-builder version to: **20.39.0**
2. Changed the directories entry in package.json as :
      ```"directories": {
      "buildResources": "build",
      "output": "build"}
3. Created **appx** named folder inside the **build** directory and created the build directory at package.json level
4. Added icon named **"StoreLogo.png"** inside build/appx directory that we have created earlier.
5. add the entry of the same in :
```
 "win": {
  "icon":"build/appx/StoreLogo.png"
}
```
6. After this just create the appx using **electron-builder -w appx**  command 
 
While installing the appx now i am able to see logo on launcher/install popup screen.
Now I have one more doubt after complete installation i am still seeing the default electron logo at the **task-bar**  and also in the apps & features if i search for my application there also the default electron icon. So can anyone please help me to resolve this issue?

**Comment by NehaTawar** [comment]
On the launcher/install popup i am **able to see** the app logo like below hidden with red color:
![image](https://user-images.githubusercontent.com/16165958/57766379-e372f280-7724-11e9-8764-7f10aa54fe69.png)


After installing and launching the app i am still able to see the default electron icon in the taskbar as below highlighted in red:
![image](https://user-images.githubusercontent.com/16165958/57765906-08b33100-7724-11e9-9ef3-a52a63efee95.png)

Also in the installed app also after searching for my app i am getting the default electron icon as below highlighted in red:

![image](https://user-images.githubusercontent.com/16165958/57766065-562f9e00-7724-11e9-9a10-4ca82ef99fd4.png)

How can i resolve this one?
I tried adding all related resources as mentioned in : https://www.electron.build/configuration/appx

**Comment by NehaTawar** [comment]
Solved the above issue using below steps:

1. Added the assets mentioned in the appx link:   https://www.electron.build/configuration/appx 

2. created **appx** folder in the **build** directory, keep the package.json as mentioned above.

3. Make sure the app logos named should be specific as metioned in the link .PNG format.

4. Earlier i had icon names as e.g **Square44x44Logo.png** format .PNG then after changing the name **to** **Square44x44Logo** kept format .PNG as it is I was able to solve installed app issue.

 But now only one icon is not getting replaced i.e when we search for app in **windows** in the best match still default electron icon is seen. Adding screenshot for the same :
![image](https://user-images.githubusercontent.com/16165958/58018628-f02a8880-7b20-11e9-9584-92781dccd331.png)

Can anyone please help me to resolve this?

**Comment by NehaTawar** [comment]
Able to resolve all the issues here is reference for the last issue mentioned in comment https://github.com/electron-userland/electron-builder/issues/3910  , but I really feel the documentation need to be updated properly.

**Comment by wildhart** [comment]
@NehaTawar, did you ever get the "Best Match" icon fixed?  I have the same issue, all my other icons are OK.
