### ISSUE TITLE
Signing OSX App Fails: Electron Framework: bundle format is ambiguous (could be app or framework)

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#388]
I've been looking for solutions and am only able to find vague answers without solutions in various electron related issue trackers.

```Error: Command failed: codesign --sign Mac Developer: FIRST LAST (UNIQUE_ID) -fv /Users/framerate/code/dist/Project-darwin-x64/Project.app/Contents/Resources/app/dist/Project-darwin-x64/Project.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
/Users/framerate/code/dist/Project-darwin-x64/Project.app/Contents/Resources/app/dist/Project-darwin-x64/Project.app/Contents/Frameworks/Electron Framework.framework/Electron Framework: bundle format is ambiguous (could be app or framework)```

electron-builder: 3.17.1
electron-prebuilt: 0.37.8
node: 6.0.0
npm: 3.8.8
OSX: 10.11.5 Beta (15F31a)

Any suggestion would be appreciated, since the signing is all inside `electron-builder`.

For the record:

`codesign -s 'Mac Developer: FIRST LAST (UNIQUE_ID)' -f dist/Project-darwin-x64/Project.app --deep`

Seems to work, but since I want to use `electron-builder` to auto package the update files and DMG, I'm not sure how to manually inject the codesign.

Thanks!

**Comment by framerate** [comment]
Well, apparently after upgrading to the newest XCode, this magically went away. Sorry for the false fire alarm, guys.

**Comment by develar** [comment]
@framerate  I am curios — did you restart machine?

**Comment by framerate** [comment]
I did not! Just reinstalled latest xcode and opened it/closed it once :)

**Comment by FrenchBully** [comment]
I too ran into this issue until I realized I had the wrong version for electron declared.  Hope that helps. 
electron-packager . "App Name" --platform=darwin --arch=x64 --version=YOUR_ELECTRON_VERSION --app-bundle-id="com.AppName" --app-version="1.0.0" --build-version="1.0.100"

**Comment by thehalvo** [comment]
@FrenchBully you saved my ass on this one. Thanks for this.

**Comment by cinder92** [comment]
@FrenchBully im using 1.6.6 version of electron and this is not working :(
