### ISSUE TITLE
window.require is undefined

### ISSUE THREAD

**Issue by nofear87** [electron-userland/electron-builder#3880]
As soon as I pack my windows application with electron builder window.require is undefined and I can't access any node modules. Any ideas?

Just running electron on my angular build works fine.

electron-builder version=20.39.0

**Comment by luissantiagodev** [comment]
Just in case someone goes into the same problem I got it solved by enabling nodeIntegration to true
```
mainWindow = new BrowserWindow({
	width: 1200,
	height: 800,
	icon: `${__dirname}/Icon/AppIcon.icns`,
	title: 'Punto de venta',
	nativeWindowOpen: true,
        resizable: false,
	nodeIntegration: true,
	webPreferences: {
		webSecurity: false,
		nodeIntegration: true,
	}
});

```

**Comment by nofear87** [comment]
Solved my problem, too. Thanks!
