### ISSUE TITLE
Compile custom app with dynamic Config Electron

### ISSUE THREAD

**Issue by loreberti89** [electron-userland/electron-builder#3883]
**version  electron-builder**  : "^20.34.0",

**version electron-updater** : "^4.0.4",

* **Target**:  Windows

I've built an App with Electron with electron Builder and auto update.

My problem is that I need some configuration in my App Electron (like apikey) that (obviously) is different from user to user.

Example:

- user1 : api1, 
- user2: api2

My app should use this ApiKey, and I need this ApiKey before the user make Login in App Electron. So I'm looking for a solution that can include a dynamic configuration. For now I thought to build the app in "real time" whith a specific routine on my server. Something like:

click on button

- launch a command that run yarn build with configuration file.
- put the exe compiled on specific folder
- send link for mail to user for download.
- So make an app for User and send link in async way to user mail for download. But I don't really like this approach for performance issues.

Someone with more experience can suggest something different with Electron?

**Comment by thisismydesign** [comment]
I've also run into this. You could use file macros: https://www.electron.build/file-patterns#file-macros

E.g. use env to provide custom config: `${env.ENV_NAME}`
