### ISSUE TITLE
Dash insterted in a version string in .exe name

### ISSUE THREAD

**Issue by GintV** [electron-userland/electron-builder#3884]
* **Version**: 20.36.2 && 20,40.2
* **Target**: nsis Windows

When building installer, exe filename should end up being something like "[productName] Setup [version].exe" Instead, it seems that version string gets a dash after third digit in version, if it contains of more the 3 numbers seperated by dots.

What I mean:
**Version: 2015.5.10 => 2015.5.10
**Version: 2015.5.10.12 => 2015.5.1-0.12
**Version: 201500.10324235.45 => 201500.10324235.45
**Version: 201500.10324235.45.3453 => 201500.10324235.4-5.3453

**Comment by develar** [comment]
It is how semver and win version works, https://github.com/electron-userland/electron-builder/blob/b83f5801771585c18524c3cee74e59de5fa9ab30/packages/app-builder-lib/src/appInfo.ts#L46

Feel free to further investigate, if I am wrong.
