### ISSUE TITLE
Option to not rebuild a native module since it needs to be built with custom options

### ISSUE THREAD

**Issue by wuno** [electron-userland/electron-builder#3886]
* **Version**: 
4.0.0

I am trying to build a native module. I need to pass some special build options to it. I install the module with the special build options and then when I run 

`yarn electron:serve`

It rebuilds the module using the node-pre-gyp binding. 

More specifically, I am building sqlite3. This works great with `Electron Builder` and `node-pre-gyp` but I need to build it with the extension sqlcipher so I can use AES-256 encryption for the database.

Is there a way to tell Electron-Builder to not rebuild a specific module when I run 

`yarn electron:serve`
or
`yarn electron:build`

**Comment by develar** [comment]
Please see https://www.electron.build/configuration/configuration about `npmRebuild`
