### ISSUE TITLE
Inconsistent versions of builder-util-runtime

### ISSUE THREAD

**Issue by ffflorian** [electron-userland/electron-builder#3887]
* **Version**: 20.40.2

When I run `tsc` on version 20.40.2, I get the following error:
```
./node_modules/app-builder-lib/out/publish/PublishManager.d.ts:11:14 - error TS2416: Property 'cancellationToken' in type 'PublishManager' is not assignable to the same property in base type 'PublishContext'.
  Type 'import("/home/florian/git/wire-desktop-packages/node_modules/builder-util-runtime/out/CancellationToken").CancellationToken' is not assignable to type 'import("/home/florian/git/wire-desktop-packages/node_modules/builder-util/node_modules/builder-util-runtime/out/CancellationToken").CancellationToken'.
    Types have separate declarations of a private property 'parentCancelHandler'.

11     readonly cancellationToken: CancellationToken;
                ~~~~~~~~~~~~~~~~~
```

AFAIC this is caused by inconsistent version definitions for `builder-util-runtime`:
* [`electron-builder`](https://github.com/electron-userland/electron-builder/blob/a127a61e0b3920d4f305791cd9d618546f018d83/packages/electron-builder/package.json#L51) uses a fixed version (`8.2.1`)
* [`app-builder-lib`](https://github.com/electron-userland/electron-builder/blob/7d5f952b12406683fd77a5eaac45e8d6b0b9f257/packages/app-builder-lib/package.json#L49) uses a fixed version (`8.2.1`)
* [`electron-updater`](https://github.com/electron-userland/electron-builder/blob/7d5f952b12406683fd77a5eaac45e8d6b0b9f257/packages/electron-updater/package.json#L21) uses the most recent patch version (`8.2.2`)
* [`builder-util`](https://github.com/electron-userland/electron-builder/blob/7d5f952b12406683fd77a5eaac45e8d6b0b9f257/packages/builder-util/package.json#L22) uses the most recent minor version (`8.2.2`)
* [`electron-publish`](https://github.com/electron-userland/electron-builder/blob/7d5f952b12406683fd77a5eaac45e8d6b0b9f257/packages/electron-publish/package.json#L18) uses the most recent minor version (`8.2.2`)

**Comment by ffflorian** [comment]
@develar any update on this?

**Comment by ffflorian** [comment]
:tada:

**Comment by ccorcos** [comment]
This is happening to me again on `22.11.3`.

**Comment by ccorcos** [comment]
I just added `"skipLibCheck": true` to my tsconfig as a workaround.
