### ISSUE TITLE
Wrong docs: executableName doesn't default to productName

### ISSUE THREAD

**Issue by googleson78** [electron-userland/electron-builder#3888]
* **Version**: 
20.38.4
* **Target**: 
Linux dir

According to [documentation](https://www.electron.build/configuration/linux) `executableName` should default to `productName`. This is not true, it defaults to the global `name` field.

**Comment by googleson78** [comment]
I am unmarking this issue from being stale manually, because it now has recent activity. It will not be closed, because I have done this. No problem!

**Comment by googleson78** [comment]
I am unmarking this issue from being stale manually, because it now has recent activity. It will not be closed, because I have done this. No problem!

**Comment by Slapbox** [comment]
This seems to still be an issue, at least on Linux?
