### ISSUE TITLE
Cross-platform build linux to macos with sharp prebuild native module

### ISSUE THREAD

**Issue by KillerCodeMonkey** [electron-userland/electron-builder#3892]
* **Version**: 20.4.2

* **Target**: `platform=darwin arch=x64 electron=4.2.0 appOutDir=package/mac`

Hey there i want to build a macos electron app on an ubuntu machine.

Sharp is the only "native" module. But i think the problem is, that when electron-builder is running, it simply uses the linux native module instead of installing the version for the target electron build os.

see my issue there: https://github.com/lovell/sharp/issues/1697

Is this even possible or is there another way to achieve this?

The build on my CI works without any error, but when i start my app it freezes directly without throwing an error. If i remove sharp, it works again.

I thought when a repo provides all native prebuilts (like sharp does) electron-builder downloads the one necessary for the target platform.

And i am a little confused with the config settings: npmRebuild, buildDependenciesFromSource

I thought this worked out of the box, because of the build output of electron-builder:
```sh
rebuilding native production dependencies platform=darwin arch=x64
rebuilding native dependency name=sharp
```

Thank you :)

**Comment by baparham** [comment]
@KillerCodeMonkey did you ever figure out a solution to this?

**Comment by KillerCodeMonkey** [comment]
Nope, just building The app with GitHub actions for the different
platforms.

Am 06.02.2021 in 14:00, Brad Parham <notifications@github.com> schrieb:

@KillerCodeMonkey <https://github.com/KillerCodeMonkey> did you ever figure
out a solution to this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/electron-userland/electron-builder/issues/3892#issuecomment-774474043>,
or unsubscribe
