### ISSUE TITLE
how to set publish url dynamically?

### ISSUE THREAD

**Issue by zzzgit** [electron-userland/electron-builder#3893]
![image](https://user-images.githubusercontent.com/1060733/57689463-2758ef80-7672-11e9-96f4-e7eded0932a0.png)

 In `package.json`, we can assign the update URL.
However, how could I set it dynamically, for instance, depending on certain conditions?

**Comment by mvkanha** [comment]
Its better if you take environment variable

**Comment by ravindra-clarion** [comment]
> Its better if you take an environment variable

I also need to set the build URL dynamically.

Can you please elaborate more on how can we use environment variables?

**Comment by mvkanha** [comment]
https://electronjs.org/docs/api/environment-variables

**Comment by baizp** [comment]
Call `autoUpdater.setFeedURL` to reset!
