### ISSUE TITLE
"Application icon is not set"on Ubuntu

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron-userland/electron-builder#3896]
Version: 20.40.2
Target: deb

I'm receiving the following message when I build my app on Ubuntu 16.04:
default Electron icon is used reason=application icon is not set

The same issue was already fixed (https://github.com/electron-userland/electron-builder/issues/3495), works for 20.38.2 but is still reproducible in version 20.43.0

**Comment by xland** [comment]
This issue is still there in version 21.2.0
And I can not rollback the electron-builder version
Because lower version of electron-builder will not work with electron 6.0.x

**Comment by xland** [comment]
@develar

**Comment by FelixPcll** [comment]
I still can not set the icon on linux in version 22.3.2
