### ISSUE TITLE
Cannot get `asar-unpack` to work

### ISSUE THREAD

**Issue by mikew** [electron-userland/electron-builder#390]
Our Electron app uses `convert` from ImageMagick, and that needs some .xml files alongside the binary. Our electron folder ends up looking like this:

```
public/
├── external/
│   ├── colors.xml
│   ├── convert
│   ├── delegates.xml
│   └── magic.xml
├── app.css
├── app.js
├── electron-main.js
├── index.html
├── package.json
└── vendor.js
```

I'm able to run `asar pack public/ public.asar --unpack 'public/external/*'` and get both `public.asar` and  `public.asar.unpacked`, but I cannot for the life of me figure out the path to be passed via `build.asar-unpack` in the development `package.json`.

I've tried ...

```json
  "build": {
    "asar-unpack": "public/external/*"
  }
  "build": {
    "asar-unpack": "external/*"
  }
  "build": {
    "asar-unpack": "app/external/*"
  }
  "build": {
    "asar-unpack": "*/external/*"
  }
  "build": {
    "asar-unpack": "dist/ProductName-darwin-x64/Electron.app/Contents/Resources/app/external/*"
  }
```

... But am not able to get `app.asar.unpacked`. Is there anything I'm missing?

**Comment by mikew** [comment]
Ah, figured it out. Using a globstar works, and no matter your directory structure, your files will be under `app/`. The following works:

```json
  "build": {
    "asar-unpack": "**/app/external/*"
  }
```

**Comment by develar** [comment]
It is the shame because we inherit this configuration option from the electron-packager. So, it is not smart and not user-friendly and no any checks :( So sad :( We will rework and introduce new smart option.

**Comment by develar** [comment]
Enjoy – now we correctly set `cwd`for glob and relative patterns work.

Also you can use https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources

**Comment by develar** [comment]
Please note `asar-unpack` is deprecated, use  [extraResources ](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-asar).

**Comment by whyboris** [comment]
Thank you @mikew for also sharing your answer. In 2018 this worked:
```
"mac": {
  ...
  "target": "dmg",
  "asar": true,
  "asarUnpack": [
    "../node_modules/@ffmpeg-installer"
  ]
}
```
Successfully get this once the _dmg_ is installed:
```
contents/
├── Resources/
│   ├── app.asar
│   ├── app.asar.unpacked/
│   │   ├── node_modules/
│   │   │      ├── @ffmpeg-installer/
```
Now the tricky part is referring to it from within my app :trollface:

**Comment by challenger532** [comment]
I have this problem:
![screenshot from 2018-02-28 14-02-57](https://user-images.githubusercontent.com/6458536/36786705-0badb1b8-1c90-11e8-903c-a419e83ef5d9.png)
any idea?

**Comment by johnsilvester** [comment]
@challenger532 try changing:
  "asarUnpack": ["../node_modules/sqlite3"],

to

  "asarUnpack": ["/node_modules/sqlite3"],

**Comment by sridharkalaibala** [comment]
`"asar": {
          "unpackDir": "src/move"
        },`
        
        this worked for me.
