### ISSUE TITLE
No connection could be made because the target machine actively refused 

### ISSUE THREAD

**Issue by e404r** [electron-userland/electron-builder#3902]
cannot get, wait          attempt=0 error=Get https://service.electron.build/find-build-agent?no-cache=1edt005: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it. waitTime=2

**Comment by Scr3w1912** [comment]
Same problem while trying to build linux dist on electron 7.0.0 and electron-builder 22.1.0.
This problem only occurs while trying to build the linux dist. The Windows on works just fine without any issue. tested on the same machine.
