### ISSUE TITLE
NSIS .exe(not installer) size is too large

### ISSUE THREAD

**Issue by insub** [electron-userland/electron-builder#3903]
if use NSIS package , when installed ,i find out the xxxx.exe file(like: C:\Program Files\some\some.exe) size is more like 70M
and if use Squirrel package, ,i find out the xxxx.exe file(like: C:\Program Files\some\some.exe) size only 400KB

why ? 
And how to reduce the size of the executable after installation（NSIS）?
thank.

**Comment by Tajnymag** [comment]
Mine is over 130MB. I know it has been 2 years, but could you elaborate on your final solution, @insub? Including a different packaging tool.
