### ISSUE TITLE
Copy node_modules from subdirectory

### ISSUE THREAD

**Issue by GregorBiswanger** [electron-userland/electron-builder#3905]
Hi Community,
I have a subdirectory with own package.json and node_modules. If I build with asar, only the node_modules from root folder will include. The two package.json-way is not a solution. The root and subdirectory is a own part of the app on runtime.

As example:
\node_modules (Need NO devDependencies)
\HostHookProject
-- \node_modules <-- Missing in asar! (Need NO devDependencies)
-- \package.json
package.json

**Comment by GregorBiswanger** [comment]
I found a solution with the file configuration:

```
    "files": [
      {
        "from": "./ElectronHostHook/node_modules",
        "to": "ElectronHostHook/node_modules",
        "filter": ["**/*"]
      },
      "**/*"
    ]
```

**Comment by rezonant** [comment]
Yes, I think the documentation says this should work without all the ceremony, in fact it states that `**/node_modules/**/*` is added to the `files` list automatically, but that does not appear to be the case.

From https://www.electron.build/configuration/contents#files

> Default pattern `**/*` is not added to your custom if some of your patterns is not ignore (i.e. not starts with !). `package.json` and `**/node_modules/**/*` (only production dependencies will be copied) is added to your custom in any case. All default ignores are added in any case — you don’t need to repeat it if you configure own patterns.

This solution saved me much hairpulling, thanks @GregorBiswanger
