### ISSUE TITLE
Resulting `AppImage` launches perfectly in Ubunti 18.04, but fails in Ubuntu 16.04 

### ISSUE THREAD

**Issue by jayarjo** [electron-userland/electron-builder#3906]
* **Version**: 20.40.2

* **Target**: AppImage

Resulting `AppImage` launches perfectly in Ubunti 18.04, but fails in Ubuntu 16.04 with the following error:

> Cannot mount AppImage, please check your FUSE setup.You might still be able to extract the contents of this AppImage if you run it with the --appimage-extract option. See https://github.com/probonopd/AppImageKit/wiki/FUSE for more information.

![appimage](https://user-images.githubusercontent.com/150075/57966376-0b02ce80-7962-11e9-9215-80fe32458b1e.png)

At first I even thought that maybe `AppImage` is not even supported on Ubuntu 16.04, but it doesn't seem to be mentioned anywhere and there are people successfully launching `AppImage`s created via other means. So my guess is maybe the format or contents in the generated `AppImage` are somehow incompatible with older versions of Ubuntu.

**Comment by develar** [comment]
Upcoming electron-builder 20.45.0 will build AppImage with update AppImage runtime (v12), maybe it will fix the issue. Or use snap.
