### ISSUE TITLE
setBadgeCount doesn't seem to do anything on Linux even in Unity Launcher

### ISSUE THREAD

**Issue by jayarjo** [electron-userland/electron-builder#3907]
* **Version**: 20.40.2

* **Target**: AppImage

Documentation says:

> On Linux, it only works for Unity launcher.

> Note: Unity launcher requires the existence of a _.desktop_ file to work, for more information please read Desktop Environment Integration.

AppImage adds its own .desktop file to the system and yet there's seemingly no effect from `setBadgeCount()`. I assume that it should show a badge on the app icon in the toolbar?

`app.setBadgeCount(10)` itself returns `true`. 

Are there any specific conditions under which it should be called maybe?

**Comment by jayarjo** [comment]
Err... I meant to file this on Electron repo.

**Comment by abrunenko** [comment]
I have the same problem. If I create a DEB package with .desktop file, app.setBadgeCount() works. After. desktop file created by AppImage - no(

**Comment by develar** [comment]
Does it work for snap?

**Comment by jayarjo** [comment]
@abrunenko make sure that the name of your app doesn't contain a space (for some reason it fails if it does)  and you also need to specify `desktop` file name in a `desktopName` field of the `package.json` file. Neither one or the other is mentioned anywhere near the description of `setBadgeCount`, but there are absolutely required, IMHO.
