### ISSUE TITLE
auto-updater not working on windows ia32

### ISSUE THREAD

**Issue by vicentedealencar** [electron-userland/electron-builder#391]
Hi, I am able to generate and host a win 64 release, but it looks like many users use Windows 32. I tryed to setup the auto-updater for that, but now there is an Exception that says `There should be at least one full release`, even though there is a full release there.

![image](https://cloud.githubusercontent.com/assets/1762868/15162414/26d50dce-16d9-11e6-993d-9d3c129eb13b.png)

![image](https://cloud.githubusercontent.com/assets/1762868/15162518/b34c3b9c-16d9-11e6-9692-7cf96f102651.png)

On a last try I removed `-ia32` from the `nupkg`s and to the `RELEASE`s files accordingly, and it works. It is not ideal to but I will do this manually for the next releases.

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130

For windows consider only distributing 64-bit versions.
