### ISSUE TITLE
after build,CSS/JS could not found 404.

### ISSUE THREAD

**Issue by DipSyJava** [electron-userland/electron-builder#3911]
after build,CSS/JS could not found 404.

**Comment by FlyingGeese** [comment]
Can you provide any more info? Starting with the structure of your application. What files in what folders, etc.

**Comment by basher** [comment]
I'm having the same problem with a Create React App + Capacitor + Electron builder.

I've already filed a [Capacitor Github issue](https://github.com/ionic-team/capacitor/issues/1604), but no response yet.

As explained in that issue:

- I have previously built CRA/Electron apps successfully, but this is the 1st time with Capacitor.
- Electron builder builds locally with Capacitor, but not in an Azure pipeline.

**Comment by basher** [comment]
My Capacitor issue is now fixed - see updated comments in Git issue in my previous comment.
