### ISSUE TITLE
Problem with Auto-Update (downgrade is disallowed)

### ISSUE THREAD

**Issue by 50l3r** [electron-userland/electron-builder#3917]
* **Electron builder version**: 20.19.2
* **Electron updater version**: 4.0.6
* **Electron version**: 3.1.9
* **Target**: Win x64

Hi guys,

I have an error trying to update my app in development environment:

This is my feed url:

    autoUpdater.setFeedURL({
        provider: 'github',
        repo: 'gestios-native',
        owner: '50l3r',
        private: true,
        token: 'XXXXXXXXXXXXXXXXXXX'
    });
    autoUpdater.checkForUpdates();

And i listen all events and send to ipcrenderer:

	const sendStatusToWindow = (text) => {
		if(mainWindow){
			mainWindow.webContents.send('message', text);
		}
	};

	autoUpdater.on('checking-for-update', () => {
		sendStatusToWindow('Checking for update...');
	});

	autoUpdater.on('update-available', () => {
		sendStatusToWindow('Update available');
	});

	autoUpdater.on('update-available', () => {
		sendStatusToWindow('Update not available');
	});

	autoUpdater.on('error', err => {
		sendStatusToWindow(`Error updating: ${err.toString()}`);
	});

	autoUpdater.on('download-progress', progressObj => {
		sendStatusToWindow(`Download speed: ${progressObj.bytesPerSecond} - Download ${progressObj.percent}%`);
	});

	autoUpdater.on('update-downloaded', () => {
		sendStatusToWindow(`Update downloaded: Installing...`);

		autoUpdater.quitAndInstall();
	});

I have only one release:

![](https://i.gyazo.com/d2618fc65ff8128b01e7abffece38666.png)

But when i execute `npm run dev` i recieve this error:

> Update for version 3.1.9 is not available (latest version: 0.0.1, downgrade is disallowed).

3.1.9 its my electron version. ¿Why can detect the electron version instead of my app?

**Comment by linuxjuggler** [comment]
When running your development code the version which electron will pick is electron app not your app, you should build your app and try it as a production app.

**Comment by 50l3r** [comment]
> When running your development code the version which electron will pick is electron app not your app, you should build your app and try it as a production app.

There not exist an option to test in development?

**Comment by linuxjuggler** [comment]
no out of the box, one of the possible ways is to use minio check https://github.com/electron-userland/electron-builder/issues/3053 for more info

**Comment by 50l3r** [comment]
Much thanks. I'l try in production

**Comment by Skriptach** [comment]
@linuxjuggler "not out of the box"
Then what purpose of `dev-app-update.yml`?

**Comment by linuxjuggler** [comment]
@Skriptach for me I use this file `dev-app-update.yml` to separate my local update dev server information from the production one.

**Comment by Skriptach** [comment]
@linuxjuggler  That's it! And I supposed to use it too.
But I got same issue as topic starter.

**Comment by linuxjuggler** [comment]
@Skriptach Short answer, when using **electron-updater** you **should not use** `setFeedURL`.

My long answer can be found [here](https://stackoverflow.com/a/57071713/1013493).
