### ISSUE TITLE
Electron and NodeJS is unable to write logs to a file

### ISSUE THREAD

**Issue by soubhikchatterjee** [electron-userland/electron-builder#3922]
I am running a nodejs app inside electron. The nodejs app writes logs to a log file that sits in a same installed path of the app. 

I then use electron builder to build an installer. On a windows machine when I install the application under `C:\Users\username`, the nodejs app writes logs to the log file without any issue. But the problem arises when the app is installed under `C:\Program Files\MyApp`, the app shows the following error:

> Error: EPERM: operation not permitted, open 'C:\Program
> Files\MyApp\resources\app.asar.unpacked\server\logs\output.log'

However if I run the app as an administrator then it works perfectly. This clearly is a permission issue. How do I make my app write to the log in the above mentioned path without any admin privileges?

Thanks in advance.

**Comment by pashvin** [comment]
Program file is a shared and protected location. Even thought let's say it is not protected you should not write log there. Normally logs should be stored per user bases so if diff user use the same machine (diff user login using diff username and password and use same app), log should go to diff folder.

Best practice is to use user's app folder and you can get that using electron API getPath('appData') or use getPath('log') and create log files there.

See https://electronjs.org/docs/all#appgetpathname.
