### ISSUE TITLE
Snaps don't build for Raspberry Pi (armv7l)

### ISSUE THREAD

**Issue by ZaneL** [electron-userland/electron-builder#3923]
* **Version**: 

20.40.2

* **Target**: 

armv7l

When trying to build the app as a snap for armv7l, it throws this error:

`cannot set machine from deb_arch 'armv7l'`

It looks as though the problem is that it is passing the term "armv7l" into snapcraft when snapcraft uses the term "armhf" for the same architecture.

![image](https://user-images.githubusercontent.com/8253139/58365235-63fcc600-7e7e-11e9-9080-749a9f06961b.png)

**Comment by fpdrozd** [comment]
I have the same problem.
