### ISSUE TITLE
Raspberry Pi ElectronJS

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#3925]
I want to make a Raspberry Pi that runs an ElectronJS app. That app must be built and not run via `npm start` like MagicMirror.

How could I arrange that?

**Comment by rdzidziguri** [comment]
Any advice on this? also, i would prefer to get some hints regarding minimal Xorg setup to run it on raspbian-stretch-lite

**Comment by develar** [comment]
Duplicates #3488 3977
