### ISSUE TITLE
Uninstalling application causes error "Windows 7 or higher is required"

### ISSUE THREAD

**Issue by kanishk98** [electron-userland/electron-builder#3930]
* **Version**: 20.40.2 

**electron-updater version**: 4.0.6

* **Target**: `nsis-web`

A user on Windows 10 enterprise uninstalled the app and got the error prompt "Windows 7 and above is required".
I'm pretty much clueless as to why this is happening, so if I can get some indicators on the reasons for the issue, that'd be great.

**Comment by joeyer** [comment]
Solve it？
