### ISSUE TITLE
Application install path on windows does not respect name or productName

### ISSUE THREAD

**Issue by chrisckc** [electron-userland/electron-builder#3932]
> You must change also name [#1250 (comment)](https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390)
> 
> ‘-c.extraMetadata.name=foo’
[https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390](https://github.com/electron-userland/electron-builder/issues/1250#issuecomment-279404390)
https://github.com/electron-userland/electron-builder/issues/2638

- electron-builder version=20.38.5  running on MacOS
- target=nsis

I am having this issue creating Windows builds, there is no issue for Mac builds, for Mac i can create builds for testing and staging that install side by side with the production build, but on windows they overwrite each other as the installation folder does not change.

To build i am using the builder api via  build script which get the "build" entry from package.json and modifies it according to NODE_ENV. I am not modifying package.json, there is only one and i prefer to keep it that way.

These are the effective configs that end up being used in the script when   `builder.build(builderConfig)` is called.

Production config:

```
package.json
"productName": "My Application",
 "name": "my-application",
"build": {
    "appId": "com.myself.my-application",
    "productName": "My Application",
................
```

Testing config:

```
package.json
"productName": "My Application",
 "name": "my-application",
"build": {
    "appId": "com.myself.my-application-testing",
    "productName": "My Application-testing",
   "extraMetadata": {
      "name": "my-application-testing"
   },
................
```

This is what ends up in the builder-effective-config.yaml file:

```
directories:
  output: build
  buildResources: build
appId: com.myself.my-application-testing
productName: My Application-testing
..........
extraMetadata:
  name: my-application-testing
electronVersion: 4.0.2
```
My initial thoughts were that the generated installation folder would be:
` \AppData\Local\Programs\<name>\<productName>.exe`

However despite using extraMetadata.name as previously suggested, the windows build still installs into the same folder
` \AppData\Local\Programs\my-application\My Application-testing.exe`
rather than being installed in:
` \AppData\Local\Programs\my-application-testing\My Application-testing.exe`

It looks like extraMetadata.name is ignored and the name from package,json is still being used.
I haven't tried this on Linux yet.

This issue does not occur on Mac because there is no concept of an installation folder, all applications go into the /Applications folder, so as long as the name of the .app package is different the apps will successfully install side by side.

On Mac you also have to make sure that the appId is changed. If it remains the same, although the name of the .app package is different and you can see the individual apps in finder when looking in the application folder, when you look at the list of apps via the keyboard shortcut which shows all the app icons, you can only see one of the apps.

**Comment by prcdpr** [comment]
This is still relevant

**Comment by TreehouseNorris** [comment]
See my above solution/workaround
