### ISSUE TITLE
Error: Bad EXE format for .node file

### ISSUE THREAD

**Issue by tusaeff** [electron-userland/electron-builder#3933]
* **Version**: 20.40.2
* **Target**: nsis
* **OS**: MacOS Mojave
* **Node version**: v8.16.0
* **NPM version**: 6.4.1

**problem definition**
I'm trying to build my application that contains native addons. it is successfully built but after launching an error occurs:

Uncaught Exception: 
Error: Bad EXE format for /*some path*/dist_electron/win-unpacked/resources/app/node_modules/scrypt/build/Release/scrypt.node

p.s. i disabled asar to to determine the specific addon

**what I was trying to do**:
1. specified arch ia32
2. tried to make a build in a docker (electronuserland/electron-builder-wine)
3. changed the version of the node to 9 and 10
4. tried to rebuild dependencies by explicitly indicating the win platform and arch32
5. used two or three latest versions of scrypt.node

I will be very grateful if you can bring me closer to understanding what is happening

**Comment by develar** [comment]
Please try 21.0.15
