### ISSUE TITLE
AppImage start but do nothing

### ISSUE THREAD

**Issue by byAbaddon** [electron-userland/electron-builder#3939]
* **20.43.0**: 

* **Appimage**: 

Hi
I created Appimage in Linux Arch with 'electron-builder' ,
app starts but do nothing after click 'No'.
Press click 'Yes' , appeared category /Game / icon , and after i click in icon again  nothing.
What is wrong?
![2](https://user-images.githubusercontent.com/51271834/58966950-e446f380-87bb-11e9-8a67-54e68f440f3d.png)

**Comment by develar** [comment]
Upcoming electron-builder 20.45.0 will build AppImage with update AppImage runtime (v12), maybe it will fix the issue. Or use snap.
