### ISSUE TITLE
Docs in multiple locations?

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#394]
Why are the docs both in the repo and the wiki?

I would recommend only keeping them in the repo, see: https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4

**Comment by develar** [comment]
> Why are the docs both in the repo and the wiki?

We sync `./docs` to wiki using git subtree merge when `next` release is marked as `latest` and available for all users.

Example: `Code Signing.md` was modified to document new feature "base64-encoded data".  But we must not confuse users of latest release — they should read docs only about generally available features. When feature is ready and release is tested, it is marked as `latest` (by default we publish as `next`) and wiki updated.

**Comment by sindresorhus** [comment]
Fair enough, though I think it would have been easier to just link to the repo docs in the latest tag instead.

At least add something to the contribution guidelines about where to contribute to the docs. Maybe inject an edit link in the wiki pages that goes directly to editing of the source or something.

**Comment by develar** [comment]
> I think it would have been easier to just link to the repo docs in the latest tag instead.

Another advantage of Wiki — "Pages" (side panel, ability to add custom footer).

> Maybe inject an edit link in the wiki pages that goes directly to editing of the source or something.

Yes, should be implemented.
