### ISSUE TITLE
Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache on 20.43.0

### ISSUE THREAD

**Issue by vkolova** [electron-userland/electron-builder#3948]
* **Version**: 20.43.0

* **Target**: MacOS

Sign verification fails for MacOS on v20.43.0.
```
To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=5.0.2 appOutDir=.....
  • signing         file=/../../..app identityName=Mac Developer: .... (....) identityHash=... provisioningProfile=none
Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /../../..app
.....app: rejected

```
The build passes with no issues on v.20.41.0.

**Comment by snatvb** [comment]
Same problem

**Comment by dangeredwolf** [comment]
Same problem here.

**Comment by johaven** [comment]
Same problem

**Comment by arjndr** [comment]
Same problem, works on 20.41.0

**Comment by vub** [comment]
Same problem ( electron-builder version=20.43.0 )

**Comment by agungsetyawan** [comment]
try to 'spctl --master-disable'

**Comment by snatvb** [comment]
@agungsetyawan sorry, what is spctl? This is tool for sign app (certificate)?

**Comment by vkolova** [comment]
This seems to work on 20.44.4, so I guess I'm closing this issue.

**Comment by johaven** [comment]
No changes with 20.44.4, i get this message:

```javascript
Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache: rejected
```

**Comment by lincolnthree** [comment]
Still broken on 21.0.15

**Comment by zengdongbao** [comment]
Same problem. 20.44.4
But works on another macbook in same version

**Comment by RickyWong33** [comment]
Same problem. 20.44.4

**Comment by neue** [comment]
> but 'spctl --master-disable' solve the problem

Disabling gatekeeper isn't a "solution", what you build wont work elsewhere.
