### ISSUE TITLE
Shared Library file being generated instead of an executable on Linux 19.04

### ISSUE THREAD

**Issue by manavbp** [electron-userland/electron-builder#3950]
On packing the app for Ubuntu 19.05, the Linux unpacked folder gives a shared library file rather than an executable something like the following.

![57453628-7ffc4700-7284-11e9-953d-b986015ace69](https://user-images.githubusercontent.com/31549495/59099936-33b72c00-8942-11e9-9f32-c5bc2cb51688.png)

Instead of 
![57453661-973b3480-7284-11e9-9759-80454536a729](https://user-images.githubusercontent.com/31549495/59099977-53e6eb00-8942-11e9-92bb-e0520551fc14.png)

and if I double click the file, I'm getting the following error

![57453716-b5089980-7284-11e9-8721-53b4761541c8](https://user-images.githubusercontent.com/31549495/59100002-64976100-8942-11e9-997f-6a4b3e0a4576.png)

**Comment by develar** [comment]
Please check 21.0.1

**Comment by manavbp** [comment]
Hey @develar I just checked and the issue still seems to persist on 21.0.1

**Comment by develar** [comment]
Reproduced on  Ubuntu LTS 18.0.4. 

Steps to reproduce: download official release https://github.com/electron/electron/releases/tag/v5.0.6 (or 5.0.5 and so on) and unpack.

So, it is not electron-builder issue, but rather Ubuntu file manager bug. Binary is correct, e.g. application works correctly (I pack to AppImage and run, or run from Terminal).

So, please file bug to Ubuntu or Electron issue trackers.
