### ISSUE TITLE
electron-updater size

### ISSUE THREAD

**Issue by astoilkov** [electron-userland/electron-builder#3953]
* **Version**: electron-updater 4.0.6
* **Target**: macOS

`electron-updater` increases the bundle size of our main process script by 22 times to half a megabyte. Pasting the screenshots produced by webpack bundle analyzer plugin:

**Without `electron-updater`:**
![image](https://user-images.githubusercontent.com/884810/59109987-c4900680-8946-11e9-89cb-0b644fe36ecb.png)

**With `electron-updater`:**
![image](https://user-images.githubusercontent.com/884810/59110029-e1c4d500-8946-11e9-8540-f4511f497545.png)

`electron-builder` is the most popular tool for packaging and publishing apps and I love it. It is so easy to work with. The auto-updating feature is so easy to set up. However, seeing that our app will load slower makes me think about the decision to use the `electron-updater` plugin.

Is there a way to minimize the bundle size by using different libraries to do the same? I am pasting a few resources to show where the size problems are.

https://bundlephobia.com/result?p=electron-updater@4.0.12

https://bundlephobia.com/scan-results?packages=@types/semver@6.0.0,lazy-val@1.0.4,bluebird-lst@1.0.9,fs-extra-p@8.0.2,js-yaml@3.13.1,semver@6.1.1,source-map-support@0.5.12,builder-util-runtime@0.0.0-semantic-release,lodash.isequal@4.5.0,pako@1.0.10

![image](https://user-images.githubusercontent.com/884810/59110853-9ad7df00-8948-11e9-9ec6-342b2682f15f.png)

**Comment by develar** [comment]
<img width="872" alt="Screenshot 2019-07-01 at 10 22 43" src="https://user-images.githubusercontent.com/350686/60421467-2f50fc80-9bea-11e9-8ea2-bdf37d9f989f.png">

result for 4.1.0 — https://bundlephobia.com/result?p=electron-updater@4.1.0

2 less dependencies. Can be reduced further.

**Comment by astoilkov** [comment]
Please don't close this issue as @develar said: "Can be reduced further.".

**Comment by astoilkov** [comment]
Please don't close this issue as @develar said: "Can be reduced further.".

**Comment by sandeep1995** [comment]
Please don't close this issue as @develar said: "Can be reduced further.".
