### ISSUE TITLE
Provide mirror option for downloading electron-builder-binaries

### ISSUE THREAD

**Issue by sachetsharma1** [electron-userland/electron-builder#3954]
* **Version**: 20.41.0
* **Target**: WIndows

github.com is blocked on our build servers. We managed to work around the electron download  by providing our own mirror but there is no mirror option for electron-builder-binaries. It will be helpful if a similar option can be exposed for the same.

**Comment by xiaoxiangmoe** [comment]
use `ELECTRON_BUILDER_BINARIES_MIRROR`

**Comment by xiaoxiangmoe** [comment]
use `ELECTRON_BUILDER_BINARIES_MIRROR`

see :

https://github.com/electron-userland/electron-builder/blob/f3404d32f029dfb63e83067012f15ef67838f326/packages/app-builder-lib/src/binDownload.ts#L21-L25
