### ISSUE TITLE
DmgContent path not supports file macros

### ISSUE THREAD

**Issue by arunkumar36** [electron-userland/electron-builder#3956]
* **20.4.3**: 

* **MAC Dmg**: 

I want to add DmgContent ([docs](https://www.electron.build/configuration/dmg)) path value as file macro but its not working , I want to install the app in /Users/(username)/Applications (current user's application) directory.

{"dmg":{
"contents": [
        {
          "x": 240,
          "y": 125
        },
        {
          "x" : 680,
          "y" : 125,
          "type":"link",
          "path" : "${env.HOME}/Applications"
        }
      ],
}
}

How to do this?

**Comment by develar** [comment]
Not, it is not possible.

Duplicates #1093.
