### ISSUE TITLE
[Question] How to fail MacOS build when Developer ID Application signing identity wasn't found?

### ISSUE THREAD

**Issue by cumajkeee** [electron-userland/electron-builder#3958]
I often pay attention that MacOS build is skipping signing step with reason:
```
reason=cannot find valid "Developer ID Application"
```
 **but** produce deliverable. 🤔 (let's imagine this happed in production)
Any chance to prevent producing app if signing failed?

**Comment by popod** [comment]
Hi, has this been implemented or is there already an options to do this ? I think that this is a good thing to do to allow us to ensure that the macOS signing process is successful.

**Comment by popod** [comment]
No body else care about this ?

**Comment by cumajkeee** [comment]
@popod looks like there is already available option: "forceCodeSigning": true. Check this docs: https://www.electron.build/configuration/configuration#overridable-per-platform-options
