### ISSUE TITLE
Master branch doesn't compile

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#396]
@develar I get the following error when running npm run compile and I dont have a clue how to get fix it.

> /home/dm/projects/electron-builder/typings/node.d.ts (426,11): Interface 'NodeBuffer' incorrectly extends interface 'Uint8Array'.
>   Types of property 'fill' are incompatible.
>     Type '(value: any, offset?: number | undefined, end?: number | undefined) => Buffer' is not assignable to type '(value: number, start?: number | undefined, end?: number | undefined) => this'.
>       Type 'Buffer' is not assignable to type 'this'.
> 

Can you please fix it so that I can go ahead with a couple of PRs?
Should a run tests be added in the pre-push section at least?

**Comment by develar** [comment]
@demetris-manikas Local and CI on all OS tests passed. Please ensure that your  `typings/node.d.ts` equals to master version and in the `package.json` — `"typescript": "1.9.0-dev.20160511",` (explicit version).

**Comment by demetris-manikas** [comment]
@develar The problem only seems to go away when I change the signature of fill in  to 
fill(value: any, offset?: number, end?: number): this; Which looks proper by the way
I use node 5.11.1 (npm 3.8.3)

**Comment by develar** [comment]
@demetris-manikas Real node version doesn't matter. Please check that `node_modules/typescript/package.json` version is `1.9.0-dev.20160511`. Do you `npm install` after each git update?

**Comment by demetris-manikas** [comment]
Yes, I do. Checked that the typescript version is 1.9.0-dev.20160511. 
I did another rebase of my fork just now and everything looks good.
As I see you removed the fill method. Thanks
