### ISSUE TITLE
Prevent "Rebuilding all packages"

### ISSUE THREAD

**Issue by ethernomad** [electron-userland/electron-builder#3968]
* **Version**: 20.43.0

I have 
`
"postinstall": "electron-builder install-app-deps"
`

But when I run `yarn upgrade` yarn still rebuilds the packages, which seems unnecessary because they need to be rebuilt anyway by electron-builder.

Is there any way to prevent yarn from "Rebuilding all packages"

**Comment by develar** [comment]
This question is to yarn, not to electron-builder. I would say it is quite ok. And better if you will file issue to native module author to provide prebuild .
