### ISSUE TITLE
custom build steps for Mac builds

### ISSUE THREAD

**Issue by ammmir** [electron-userland/electron-builder#397]
on Mac builds for my app, i need to copy custom directory structures into the .app bundle, like XPC services, other .app bundles, etc. could you please add support for a custom build step like running a script or arbitrary command right before the deep codesign step?

**Comment by develar** [comment]
Why [extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#user-content-BuildMetadata-extraResources) is not suitable to copy  "custom directory structures"?

**Comment by ammmir** [comment]
@develar because it'll copy them into the `Contents/Resources` dir if i'm reading the docs correctly

**Comment by develar** [comment]
@ammmir If it will copy to root of the app (`yourApp/.`), will be it a solution for you?

**Comment by ammmir** [comment]
@develar yes, that'll work, too :)

**Comment by ammmir** [comment]
@develar actually, as part of my build process, i also need to modify `Contents/Info.plist` prior to codesigning, so a provision for running a custom command prior to the codesigning step would allow most flexibility imho.

**Comment by develar** [comment]
Actually, there is an option `platformPackagerFactory` in the `PackagerOptions`, but it is very low-level. I will add custom function. BTW, why do you need to modify Info.plist, maybe we can add some options to avoid programmatic usage?

**Comment by ammmir** [comment]
@develar in my case, i'm adding a privileged helper tool, which requires the main app bundle's Info.plist to contain a `SMPrivilegedExecutables` dict. there may be other uses too.. bat basically, i need to edit the Info.plist *and* add some files into various directories (MacOS, Library, etc.)

**Comment by develar** [comment]
>  i'm adding a privileged helper tool, which requires the main app bundle's Info.plist to contain a SMPrivilegedExecutables dict

Please use https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#extend-info (in the `build`).

**Comment by develar** [comment]
Implemented as:
```
      build: {
        afterPack: () => {
          called = true
          return Promise.resolve()
        }
      }
```

**Comment by develar** [comment]
Do you copy files into `Contents/`?

**Comment by develar** [comment]
@ammmir Do you copy files into `Contents/`?

**Comment by hannanabdul55** [comment]
So does the step of copying `extraResources` files occur after codesigning is completed? 
I think it is so because if I specify an `extraResources` parameter, it is giving me an invalid DMG.

**Comment by develar** [comment]
@hannanabdul55 No. Please open new issue and describe "invalid DMG" (https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12)

**Comment by hannanabdul55** [comment]
@develar , Sure.

**Comment by jwheare** [comment]
> BTW, why do you need to modify Info.plist, maybe we can add some options to avoid programmatic usage?

In case you wanted to add some options, another use case for `extend-info` that we use is for setting up custom URL handlers (`CFBundleURLTypes`) for use with [`app.setAsDefaultProtocolClient(protocol)`](http://electron.atom.io/docs/all/#appsetasdefaultprotocolclientprotocol-macos-windows)

Here's our `Info.plist` file: https://github.com/irccloud/irccloud-desktop/blob/master/Info.plist

(I'm personally fine with using `extend-info` for this, so this is just an fyi on use cases)

**Comment by develar** [comment]
@jwheare Please see https://github.com/electron-userland/electron-builder/issues/575#issuecomment-241508042
