### ISSUE TITLE
AutoUpdater可以修改latest.yml文件名吗？或者读取CDN上的latest.yml文件需要怎么做？

### ISSUE THREAD

**Issue by DipSyJava** [electron-userland/electron-builder#3970]

**Comment by DipSyJava** [comment]
Referer missing?

**Comment by nixklai** [comment]
You will need to install `electron-updater` first, and configure the update information in `package.json` as shown [HERE](https://www.electron.build/configuration/publish).
You read more about it [HERE](https://www.electron.build/auto-update).

As far as I know, `electron-updater` will always read the `latest.yml` in the given URL, like one on a CDN.

-----------

您需要先安裝`electron-updater`，並如[此](https://www.electron.build/configuration/publish)所示於`package.json`設定更新配置，。
你可以在[此](https://www.electron.build/auto-update)進一步了解electron-updater的自動更新功能。

據我所知，當`electron-updater`將讀取指定URL中的`latest.yml`。你可以就此定義CDN的網址，並由客戶端的Electron自行讀取`latest.yml`。客戶端一旦發現`latest.yml`中的版本有更新，就會下載當時`latest.yml`指定的程式並且安裝。

**Comment by DipSyJava** [comment]
> You will need to install `electron-updater` first, and configure the update information in `package.json` as shown [HERE](https://www.electron.build/configuration/publish).
> You read more about it [HERE](https://www.electron.build/auto-update).
> 
> As far as I know, `electron-updater` will always read the `latest.yml` in the given URL, like one on a CDN.
> 
> 您需要先安裝`electron-updater`，並如[此](https://www.electron.build/configuration/publish)所示於`package.json`設定更新配置，。
> 你可以在[此](https://www.electron.build/auto-update)進一步了解electron-updater的自動更新功能。
> 
> 據我所知，當`electron-updater`將讀取指定URL中的`latest.yml`。你可以就此定義CDN的網址，並由客戶端的Electron自行讀取`latest.yml`。客戶端一旦發現`latest.yml`中的版本有更新，就會下載當時`latest.yml`指定的程式並且安裝。

但是我的CDN需要授权认证，请求头中必须加入Referer,但当我加入了这个属性后，通过抓包工具竟神奇的发现这个属性被屏蔽了，而设置的其他请求头却能正常获取。
所以我在提出这个问题后的几天里就已经发现这个问题了。

**Comment by develar** [comment]
And you can always set your own options using `setFeedURL`.

**Comment by DipSyJava** [comment]
> And you can always set your own options using `setFeedURL`.

As you said, the 'referer' attribute was set in autoUpdater.requestHeaders, which was missed.

**Comment by nixklai** [comment]
I don't know whether the Referer removal is a security feature of some sort, but I used [`electron-referer`](https://github.com/akameco/electron-referer) to work around it.

**Comment by DipSyJava** [comment]
> I don't know whether the Referer removal is a security feature of some sort, but I used [`electron-referer`](https://github.com/akameco/electron-referer) to work around it.

I think so too, but our company stipulates that we must use Referer, because other projects use Referer, so I want to ask if we can cancel the blocked Referer in some way, just set it in 'autoUpdater.request Headers'. Thank you for your answer. Although I don't know the use of electronic-referer, maybe electr. On-referer can't solve my current problem
