### ISSUE TITLE
Proper documentation checkForUpdatesAndNotify

### ISSUE THREAD

**Issue by Superlokkus** [electron-userland/electron-builder#3971]
`checkForUpdatesAndNotify` should be proper documented especially about the differences to `checkForUpdates`.

Only by try and error and looking into the implementation I found out that it checks if the app is packed in contrast to `checkForUpdates`, also I am not sure if it respects the `autoDownload` and `autoInstallOnAppQuit` properties, because its notification says otherwise.

**Comment by develar** [comment]
Pull request wanted.
