### ISSUE TITLE
Indicator of portable app loading

### ISSUE THREAD

**Issue by campbellhennessy** [electron-userland/electron-builder#3972]
* **Version**: 20.43.0

N/A

* **Target**:  Windows portable

I have packaged a portable exe that is running off a USB. There are a lot of static media files in the project so my app.asar is several hundred MB in size. The application itself loads quickly in development (like 2-3s) but when opened from the exe it takes about a minute to load on some computers from the time the user clicks. I assume that this is the app.asar being copied to a temporary directory and decompressed.

My issue isn't with the delay, this is the price we pay for wanting it portable on a USB. The issue we are having is that there is no indication to the user that the application is still loading. The cursor spins for a few seconds but then goes back to a normal mouse and the only way you can tell the program is loading is that there is an entry in the task manger. This leads to some users clicking the executable many times before many windows start to open.

Is there a way to launch a small modal or other indication to the user that the application is still alive before the app.asar is transferred?

**Comment by develar** [comment]
Please try to use `useZip` option for portable target.

```
"portable": {
  "useZip": true
}
```

**Comment by campbellhennessy** [comment]
Sorry, I was a bit slow.  I'm not sure if I entered it correctly or not, but I did not find any improvement with the following:

 ```
"win": {
      "target": "portable",
      "icon": "build/icon.png"
    },
    "portable": {
      "useZip": true
    }
```

Did I put it in correctly?  Though wouldn't it still need to unzip when it copies the files to the temporary directory?  Again, I am okay if it takes a long time to load, it is just that I would like to make sure the user is aware that the application is loading and that they shouldn't keep clicking at the icon.

**Comment by campbellhennessy** [comment]
I had some success in getting something like my desired outcome by modifying the portable.nsi file in the app-builder-lib package to set the installer to silent only after initialization.  This way it shows the "verifying installer..." message during the CRCCheck but then goes silent before the install.  I found the bulk of my startup delay is the CRCCheck and at least with this the user knows that the application is in the process of starting.  

The top of my portable.nsi file now looks like this:
`!include "common.nsh"
!include "extractAppPackage.nsh"

WindowIcon Off
AutoCloseWindow True
RequestExecutionLevel ${REQUEST_EXECUTION_LEVEL}

;SilentInstall silent

Function .onInit
  !insertmacro check64BitAndSetRegView
  SetSilent silent
FunctionEnd`

**Comment by develar** [comment]
I think `CRCCheck off` is a good value for portable — doesn't make a lot of sense, since in any case it is a part of some package.

**Comment by develar** [comment]
CRCCheck is disabled in 21.0.2

**Comment by grafanauser** [comment]
> Please try to use `useZip` option for portable target.
> 
> ```
> "portable": {
>   "useZip": true
> }
> ```
> 
> in your electron-builder config.

useZip is missing in the documentation
