### ISSUE TITLE
Problem with armhf/armv7l (raspberry pi) when creating snaps

### ISSUE THREAD

**Issue by ZaneL** [electron-userland/electron-builder#3976]
* **20.44.0**: 

armv7l

Thanks so much for all of the snap related updates! I snapped an electron app (using the newest electron version - 5.0.4) and it worked perfectly for my amd64 ubuntu machine.

I then tried building it for my raspberry pi (armv7l) and got this error:
` ⨯ enum value must be one of amd64,i386,armv7l,arm64, got 'armhf'`

The command I'm running is 
`build --linux --armv7l snap`

I can see one of the changes was that you added a bit of code to change the text from armv7l to armhf for snapcraft, but something must still be a little wonky.

**Comment by develar** [comment]
Fixed in 20.44.1
Thanks for donation.
