### ISSUE TITLE
build snap for armhf on amd64

### ISSUE THREAD

**Issue by ZaneL** [electron-userland/electron-builder#3977]
* **Version**: 
20.44.1

* **Target**: 
armv7l

Thanks for that last fix! I tried building the snap for armv7l with the newest update and now it just hangs. I'm trying to build the snap on my amd64 ubuntu machine -- so I'm not sure if cross compilation is working yet?

I'm running this command:
`build --linux --armv7l snap`

Which results in it hanging here:

![alt text](https://i.ibb.co/9NnWV5r/lockup.png "123")

**Comment by ZaneL** [comment]
Ran it again with debugging enabled:

`  • execute command           args=snapcraft snap --output out.snap --target-arch armhf path=/snap/bin/snapcraft
  • exited          command=app-builder code=0 pid=27841 out={"size":55691740,"sha512":"UdwcMRA/l5TuewSyzB8Mzz1H4IRL4gkFgm2X6Kucghc3CGjcxeBOQyl0E/OYbyXxdhN/NeMNPk85pp/zEriz6g==","blockMapSize":59700}
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
  • calling getInfo reason=owner or project is not specified explicitly provider=github owner=undefined project=undefined`

**Comment by develar** [comment]
>  and now it just hangs.

Building? If debug enabled, then you can find dir `___snap-*` in your dist.

1. Please ensure that you use latest snapcraft version (at least 3.1) and multipass is installed (https://github.com/CanonicalLtd/multipass).
2. in terminal `cd ___snap-*` (here * means your arch — I am not sure what's exactly used) and then execute `snapcraft snap --output out.snap --target-arch armhf `

**Comment by ZaneL** [comment]
That worked!

Generated a snap that was 47.6MB. Thank you so much!

**Comment by develar** [comment]
Hmmm.... interesting. Some problem with multipass, I will investigate what's wrong.

Is app working on arm device correctly?

**Comment by ZaneL** [comment]
Unfortunately I can't test it on my raspberry pi for a couple of days. When I get back from my weekend trip I'll test it out asap.

**Comment by ZaneL** [comment]
Okay so I tested it out today and the snap wouldn't run on my raspberry pi. The snap was generated by going into the  `__snap-armv7l*` folder and manually typing `snapcraft snap --output out.snap --target-arch armhf`. When running this on a pi, it threw some error claiming that the snap's target architecture was for amd64...just out of curiosity I tried to install that snap on my amd64 machine it that didn't work either.

Then what I did was I modified the snapcraft.yaml file and added these lines:

`architectures:
  - build-on: amd64
    run-on: armhf`

After building that snap, I tried installing it on my pi and it actually did install. When trying to run it, it threw the following error:
`error while loading shared libraries: libnss3.so: cannot open shared object file: no such file or directory`

**Comment by develar** [comment]
@ZaneL Please try https://github.com/electron-userland/electron-builder/issues/3977#issuecomment-502333976 again, but use `snapcraft snap --output out.snap --target-arch armv7l` (i.e. use arch name `armv7l`)

Do you know, is it possible to test without raspberry hardware?

**Comment by develar** [comment]
Maybe you should build not for `armv7l`, but `arm64`?

I see `armhf` arch for https://packages.ubuntu.com/bionic/libnss3.

**Comment by ZaneL** [comment]
If I use the command `snapcraft snap --output out.snap --target-arch armv7l` it just throws an error and says: `Cannot set machine from deb_arch 'armv7l'`

I'm running 32 bit ubuntu on my pi, so it should be armv7l/armhf, rather than arm64.

I just managed to get it working on my pi by screwing around with stuff (but it's throwing quite a few errors / warnings). 

![alt text](https://i.ibb.co/6ZcPk0C/electron.jpg "")

What I did was added these lines to the yaml

```
architectures:
  - build-on: amd64
    run-on: armhf

```

Then I changed the confinement from strict to `classic` (in the yaml) and typed `snapcraft` in that directory to generate the snap file.

When running it on the pi, it spit out these warnings/errors, but it still seems to run.
```/home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiolibproxy.so: cannot open shared object file: No such file or directory
Failed to load module: /home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiolibproxy.so
/home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiognomeproxy.so: cannot open shared object file: No such file or directory
Failed to load module: /home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiognomeproxy.so
/home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiognutls.so: cannot open shared object file: No such file or directory
Failed to load module: /home/zane/snap/electron-quick-start/common/.cache/gio-modules/libgiognutls.so
/home/zane/snap/electron-quick-start/common/.cache/gio-modules/libdconfsettings.so: cannot open shared object file: No such file or directory
Failed to load module: /home/zane/snap/electron-quick-start/common/.cache/gio-modules/libdconfsettings.so
GLib-GIO-Message: 00:14:40.615: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Fontconfig error: Cannot load default config file
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

(electron-quick-start:25179): Gtk-WARNING **: 00:14:43.131: /snap/electron-quick-start/x2/gnome-platform/usr/lib/arm-linux-gnueabihf/gtk-3.0/3.0.0/immodules/im-ibus.so: cannot open shared object file: No such file or directory

(electron-quick-start:25179): Gtk-WARNING **: 00:14:43.132: Loading IM context type 'ibus' failed
```

**Comment by ZaneL** [comment]
So it seems like in either case (when using strict or classic confinement) for some reason it can't find some of the shared libraries.

I think you can emulate an armv7l (raspberry pi) using QEMU, but I haven't tried it. [https://azeria-labs.com/emulate-raspberry-pi-with-qemu/](url)

**Comment by develar** [comment]
Maybe it is `snapcraft` bug — created VM is not `armhf`, but `amd64`.  Or for amd64 Ubuntu VM corresponding arch is not added and apt simply downloads lib for `amd64`. You can check it, 

`multipass list` to get list of VMs, and then `shell` to open a shell and then perform some commands to check arch / installed archs and so on.

I will check it this week.

**Comment by develar** [comment]
Turned out, it is snapcraft "bug" — https://forum.snapcraft.io/t/snapcraft-3-x-target-arch-not-working/9730 / https://forum.snapcraft.io/t/snapcraft-3-x-cross-compilation-amd64-armhf-in-multipass-vm/9758/4

**Comment by develar** [comment]
Do you use Raspberry Pi 3 Model B+? I am going to buy https://www.amazon.de/ABOX-Raspberry-Ultimatives-Starterkit-aus-Schaltnetzteil/dp/B07DQHZ11S to test and build arm.

**Comment by ZaneL** [comment]
Thanks for figuring that out! Yes, I use pretty much the same setup for my raspberry PI.

**Comment by ZaneL** [comment]
I've returned with some info on how to build snaps for armhf  (raspberry pi) + arm64. I assume things will change in the near future to make this easier, but at the moment there are two problems:

1.) Cross compilation isn't really working in snapcraft at the moment...so it doesn't seem possible to build an armhf snap on an amd64 system without some bizarre problems -- especially an electron snap.

2.) As a result of this, you need to build the snaps locally on your raspberry pi. The issue is that you can't do this easily, since multipass won't run on ubuntu server, ubuntu mate (or any standard linux OS) since virtualization (KVM) is typically disabled for arm systems in the kernel.

**Temporary solution:**

One thing I've tried that worked is as follows:

1.) Setup your electron app with the newest version of electron-builder on your raspberry pi and attempt to build the snap. It will fail (because KVM is disabled and it can't launch multipass), but it will spit out a folder in the dist directory that looks like **__snap-arm64**

2.) CD into this folder and enter the following commands (obviously these will change a bit depending on armhf/arm64 and your app name):

```
lxc launch ubuntu:18.04 mysnapcraft
lxc file push -r . mysnapcraft/home/ubuntu/
lxc exec mysnapcraft -- /bin/bash 
snap install snapcraft --classic
cd /home/ubuntu/__snap-arm64
snapcraft --destructive-mode
exit
lxc file pull mysnapcraft/home/ubuntu/__snap-arm64/electron-quick-start_1.0.0_arm64.snap .
```
You should now have the snap in your __snap-arm64 folder.

What you've done here is created a container, copied the electron project and snap files into the container, installed snapcraft in the container, and ran snapcraft in destructive mode to build everything without using multipass. Then the last command copies the snap file that you've built back out of the container.

**Comment by ZaneL** [comment]
Looks like this new "solution" I found isn't really working any better than just doing it that first way...

**Comment by ZaneL** [comment]
I ran unsquashfs on the snap to check it out and it looks like libnss3.so is completely missing from the snap...not sure why yet...

![alt text](https://i.ibb.co/z6xhTGj/image.png "")

**Comment by develar** [comment]
Just to be  sure — please use 21.0.3 instead of 20.x

**Comment by ZaneL** [comment]
I'm using 21.0.3

**Comment by develar** [comment]
I cannot yet have access to arm machine, 

you can try sample app: `sudo snap install armhf-electron-template-snap --edge`

**Comment by ZaneL** [comment]
I installed your snap on the newest ubuntu core image on my raspberry pi and it looks like your snap has the same problem as mine. Throws the same error about libnss3.so.


![alt text](https://i.ibb.co/qCLpCZf/image.png "")

**Comment by ZaneL** [comment]
Okay I figured out what the problem is. 

https://github.com/electron-userland/electron-builder/blob/2623eebd41100ba2daf81632e80e45fbc8ae087e/packages/app-builder-lib/src/targets/snap.ts#L103

In the LD_LIBRARY_PATH section where it pulls in **linuxArchName**, it should be aarch64 instead of arm-aarch64, and the same for the 32 bit arm one...

You can see this here where I've run unsquashfs on the snap file and then searched for libnss. It is in fact in there, but the link is wrong because it is using arm-aarch64 instead of aarch64.

```
ubuntu@ubuntu:~/electron-quick-start/dist/squashfs-root$ find . -name "libnss*"
./usr/lib/aarch64-linux-gnu/nss/libnssdbm3.chk
./usr/lib/aarch64-linux-gnu/nss/libnssckbi.so
./usr/lib/aarch64-linux-gnu/nss/libnssdbm3.so
./usr/lib/aarch64-linux-gnu/libnss3.so
./usr/lib/aarch64-linux-gnu/libnssutil3.so
```

**Comment by ZaneL** [comment]
...and I'm guessing that error has something to do with this when building the snap:

```
The 'app-files' part needs the following libraries that are not included in the snap or base:
usr/lib/aarch64-linux-gnu/libX11.so.6
usr/lib/aarch64-linux-gnu/libXau.so.6
usr/lib/aarch64-linux-gnu/libXdmcp.so.6
usr/lib/aarch64-linux-gnu/libXext.so.6
usr/lib/aarch64-linux-gnu/libxcb.so.1
These dependencies can be satisfied via more stage-packages, more parts, or content sharing.
```

**Comment by develar** [comment]
arch triplet is fixed in upcoming 21.0.4, thanks for investigation.

**Comment by develar** [comment]
Works for me. I will release template (so, you can build your app on any OS) tomorrow.

**Comment by develar** [comment]
In the console you can see errors like https://github.com/nextcloud/nextcloud-snap/issues/221, but it is ok as far I see.

**Comment by snblackout** [comment]
Hello.  Sorry to bring attention to this again.  Trying to build on Ubuntu for arm but having difficulties.  Not even attempting to build for arm from what I see in log.  See below.  Any ideas on what I should check first to resolve?  Btw, the snap that is generated runs just fine on the system I'm using to build which is Ubuntu

> electron-builder "snap" "armv7l"
--
  |  
  | • electron-builder  version=22.2.0 os=5.3.0-26-generic
  | • loaded configuration  file=package.json ("build" field)
  | • writing effective config  file=dist/builder-effective-config.yaml
  | • packaging       platform=linux arch=x64 electron=7.1.9 appOutDir=dist/linux-unpacked
  | • building        target=snap arch=x64 file=dist/myapp_0.0.1_amd64.snap
  | • default Electron icon is used  reason=application icon is not set


Linux ubuntu 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by snblackout** [comment]
Well of course I figured it out.  My `scripts` section in my `package.json` I was naming the task `dist snap arm` and I'm guessing this was conflicting with a reserved name of some sort.  I renamed the task `test` and tried again then it picked up on my switches to use the arm architecture.  Frustrating.
