### ISSUE TITLE
owner or project is not specified explicitly

### ISSUE THREAD

**Issue by linonetwo** [electron-userland/electron-builder#3982]
Version: 20.43.0

    Target: Windows

In appveyor, what does this message means?

```
calling getInfo reason=owner or project is not specified explicitly provider=github owner=undefined project=undefined
```

**Comment by develar** [comment]
Well, it is debug message. Quite a lot of fields are inferred, and debug logs allows you to understand what's performed under the hood to get it.

**Comment by linonetwo** [comment]
Yeah, seems it is not blocking anything. My releasing succeed in spite of it.
