### ISSUE TITLE
Could not get code signature for running application if you restart a running app for autoupdate

### ISSUE THREAD

**Issue by danutzcodrescu** [electron-userland/electron-builder#3983]
* **Version**: 20.43.0
* **Electron updater**:4.0.6
* **Target**:  MacOs

My application is built with electron builder and I have a button that will relaunch the app in case there is a new update available.

Here is the code:
```javascript
    remote.app.relaunch();
    remote.app.exit(0);

```

If someone presses this button, the app throws this error in an alert: `Could not get code signature for running application`. However, after pressing ok the app is updated successfully. If you completely close the app instead of pressing the button, and then start it again the message does not appear and the update is applied.

Question is: how can I get rid of this message?

**Comment by ZibanPirate** [comment]
https://github.com/electron/electron/issues/7476
