### ISSUE TITLE
electron-builder packages with wrong electron binary version

### ISSUE THREAD

**Issue by thomasnordquist** [electron-userland/electron-builder#3984]
* **Version**: 20.44.1

* **Target**: mac / snap / nsis/ appx ....

I have electron@5.0.4 installed but when I package, electron-builder downloads electron@5.0.0 which is not the version I developed and tested with. This may lead to very unfortunate bugs/incompatibilities.

Details:
`electron-builder` appears to rely on the electron version provided in `package.json` and ignores installed/locked versions.
A version string like `^5.0.0` can be understood as `5.0.0 >= allowed versions > 6.0.0`.

Example
While version 5 is specified in `package.json`
```
"dependencies": {
    "electron": "^5",
    "electron-builder": "20.44.1"
}
```

The package manager may/will choose to install more recent packages:
`yarn.lock`
```
electron@5:
  version "5.0.4"
  resolved "https://registry.yarnpkg.com/electron/-/electron-5.0.4.tgz#2e0d09055363e983f4a73317cde4821c39617b02"
  integrity sha512-7QaKorvANvP+azMT7wElx33oLlqw8QxmLs7/outfH7LC5amErk4EUtWDesQ6Zgr+s5pYFbykl8ZtJ4ZGXER05g==
  dependencies:
    "@types/node" "^10.12.18"
    electron-download "^4.1.0"
    extract-zip "^1.0.3"
```

`yarn.lock` or `package-lock.json` do reflect the actual used package versions.

The [workaround](https://github.com/thomasnordquist/MQTT-Explorer/commit/0e0fbae8bb464b8eacd559b10c0e074c3c42243f) is to set the specific electron version in the `package.json` dependencies, this is however not the way one normally uses the package manager since lock files exist. (and will most certainly interfere with greenkeeper and depandabot)

Just noticed this by accident, packaging using electron `5.0.0` and expecting `5.0.4` (since I specifically updated to `5.0.4`) would have caused a lot of headaches.

**Comment by develar** [comment]
No, electron-builder checks installed version — see https://github.com/electron-userland/electron-builder/blob/fd86d92079c1b31aa54299cd44316867086968ad/packages/app-builder-lib/src/electron/electronVersion.ts#L23

Maybe you use custom project dir during build (that not equal to actual project dir, where node modules installed)?

**Comment by thomasnordquist** [comment]
You are correct, I use a fresh clone (from .git) to prepare builds in a subdirectory. (to prevent using a dirty workspace by accident)

After building I remove the `devDependencies` in this subdirectory with `yarn install --production`, electron-builder can no longer determine the electron version since electron itself is a dev dependency.

I can confirm that the issue does not occur when the dev-dependencies are present/installed.

**Comment by develar** [comment]
Another workaround for such build scripts: pass CLI arg `-c.electronVersion` or set config `"electronVersion": "version"`.

**Comment by sandeep1995** [comment]
If you are trying to upgrade to Electron 7.0, make sure your dev dependencies is like the following
```json
"devDependencies": {
    "electron": "7.0.0",
}
```
Notice it has to be `7.0.0` not `^7.0.0`. The parser is poorly written.

**Comment by edmofro** [comment]
If using a yarn-workspaces based mono-repo and seeing "none of the possible electron modules are installed", add the following to your `package.json`

```
"workspaces": {
    "nohoist": [
      "electron"
    ]
  }
```

This forces `yarn` to keep `electron` in the package `node_modules` rather than hoisting it up to the root (where `electron-builder` doesn't seem to spot it)

**Comment by AgainPsychoX** [comment]
I have similar issue while using npm workspaces. I have structure
```
root/             // Main folder, workspace
root/app/         // My app, no real `node_modules` here
...               // The app is just using node_modules of its workspace,
root/node_modules // <-- this one. And there is `electron`
...
```

Maybe the `getElectronVersionFromInstalled` could check directory above if the project is using workspaces?

**Comment by steveruizok** [comment]
The fix for me was replacing `electron: "^15.3.0"` with `electron: "15.3.0"`.

**Comment by nour-dev** [comment]
@develar solution is best for monorepos

**Comment by tresorama** [comment]
> If using a yarn-workspaces based mono-repo and seeing "none of the possible electron modules are installed", add the following to your `package.json`
> 
> ```
> "workspaces": {
>     "nohoist": [
>       "electron"
>     ]
>   }
> ```
> 
> This forces `yarn` to keep `electron` in the package `node_modules` rather than hoisting it up to the root (where `electron-builder` doesn't seem to spot it)

Working in a Yarn monorepo workspace this solution worked!
But in my case the glob pattern should be edited like this to make it *nohoisting* every `electron`-ish packages

```json
"workspaces": {
    "packages":[
      "apps/*"
    ],
    "nohoist": [
      "**electron**"
    ]
  },
```

Thank you @develar ! 😎

**Comment by Dhruv7201** [comment]
electron version to 7.0.1; update electron-builder to 22.4.0

**Comment by cgx-system** [comment]
Same with electron-builder v25.1.8
Removing the ^ before electron version worked, so it seems to be just an issue with electron-builder reading semver !
Should have been fixed a long time ago, IMHO...

**Comment by Catlike14** [comment]
Is there a way to resolve it without setting a fixed version?

**Comment by Nokel81** [comment]
If you use the `electron-builder-config.js` option instead of using the JSON option, you can specify `electronVersion: require('electron/package.json').version,` which resolves the issue. At least it did for me for the project I work on which is a monorepo and the application is not at the root, but we also dedupe and hoist dependencies
