### ISSUE TITLE
Snap fails to start on Ubuntu 16.04: `libudev.so.1: cannot open shared object file`

### ISSUE THREAD

**Issue by thomasnordquist** [electron-userland/electron-builder#3986]
* **Version**: 20.44.1

* **Target**: snap

I tested with Ubuntu 18.04 and 16.04, 18.04 runs just fine.

Application crashed on launch with:
```
/snap/core/6964/usr/lib/snapd/snap-confine: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory
```

I believe this to be an issue with the snap package size optimization with this pre-release @develar, I would have loved to fix it myself but I can't seem to find the snap templates.
Great work, by the way 👍

Ubuntu 16.04 has still long term support until April 2021, I think it's worth fixing it for 16.04.

May also be a duplicate of https://github.com/electron-userland/electron-builder/issues/3979

Workaround: downgrade to 20.43.0 and build the snap by hand.

**Comment by develar** [comment]
No doubt, Ubuntu 16 is fully supported version and I tested (and tests) results on it.

It is your https://github.com/thomasnordquist/MQTT-Explorer/blob/master/package.json project, right (so, you don't have stage packages and any custom)?

Where did you build — OS?

**Comment by develar** [comment]
BTW, have you updated Ubuntu 16 — `sudo apt-get update -qq`?

**Comment by thomasnordquist** [comment]
Building on travis (ubuntu 16.04)
And on my server ubuntu 18.04.

I tested with a ubuntu live-dvd (in VirtualBox).

What do you mean with "(so, you don't have stage packages and any custom)"?

I just removed my [repackaging](https://github.com/thomasnordquist/MQTT-Explorer/blob/master/scripts/afterAllArtifactBuild.ts#L13-L19) script and try again.

Ill also try `sudo apt-get update -qq`.

**Comment by thomasnordquist** [comment]
After installing ubuntu 16.04 (not using the live-dvd) with the latest packages the issue is resolved.

It appears I still need [repackaging](https://github.com/thomasnordquist/MQTT-Explorer/blob/master/scripts/afterAllArtifactBuild.ts#L13-L19) for the snapcraft review, I'll update https://github.com/electron-userland/electron-builder/issues/3608 with details.

Thanks for the fast response, I'd never guessed that a package upgrade would be the solution...
