### ISSUE TITLE
Ensure that AppImages contain valid .DirIcon file

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#3988]
* **Version**: Latest
* **Target**: Linux AppImage

Every AppImage needs to contain  a top-level `.DirIcon` file. Please use a 256x256 px png. (`linuxdeployqt` puts the main icon specified in the desktop file there, but `electron-builder `is not using `linuxdeployqt`.)

References: 
* https://github.com/AppImage/AppImageSpec/blob/master/draft.md#the-filesystem-image
* https://github.com/AppImage/AppImageSpec/issues/27
* https://github.com/geraldoramos/nikola/issues/31
* https://github.com/wagerr/wagerr-electron-app/issues/4
* https://github.com/neopostmodern/wohnungsbot/issues/1

cc @develar

**Comment by develar** [comment]
Hmm.... In this [line](https://github.com/develar/app-builder/blob/master/pkg/package-format/appimage/appLauncher.go#L93) `iconFileName` should be changed to `.DirIcon`. I was under impression that electron-builder creates some explicitly named icon file. Have to check it again. Cannot believe :)
