### ISSUE TITLE
Remote build failed: "Need executable 'ar' to convert dir to deb

### ISSUE THREAD

**Issue by NieLeben** [electron-userland/electron-builder#3992]
* **Version**: 20.44.4

* **Target**: Linux

* **Description**:
I tried building this on windows which started a remote build and failed at:
"{:timestamp=>"2019-06-22T19:29:29.520389+0000", :message=>"Need executable 'ar' to convert dir to deb", :level=>:error}".

Full log [here](https://pastebin.com/Be6VjFa4).

**Comment by IZUNA894** [comment]
what  is the solution?

**Comment by veici** [comment]
You can install ar command using the following [apt-get command](https://www.cyberciti.biz/tips/linux-debian-package-management-cheat-sheet.html?utm_source=Linux_Unix_Command&utm_medium=faq&utm_campaign=nixcmd)/[apt command](https://www.cyberciti.biz/faq/ubuntu-lts-debian-linux-apt-command-examples/?utm_source=Linux_Unix_Command&utm_medium=faq&utm_campaign=nixcmd):
$ sudo apt install binutils

OR
$ sudo apt-get install binutils
