### ISSUE TITLE
Prevent autolaunch after NotSilent Update

### ISSUE THREAD

**Issue by MurAnn** [electron-userland/electron-builder#3996]
* **20.44.4**: 

4.0.6

* **NSIS**: 

The Autoupdater method quitAndInstall() has no option for showing the update progress and prevent the app from starting after the update is finished. It says that the option isForceRunAfter is ignored once silent is false, but I NEED to show the update progress, and I DON'T want the app to start after it.

**Comment by develar** [comment]
> but I NEED to show the update progress, and I DON'T want the app to start after it.

In this case user has an option to uncheck "run" on finish.
