### ISSUE TITLE
Tests fail on linux

### ISSUE THREAD

**Issue by demetris-manikas** [electron-userland/electron-builder#400]
@develar While running the tests I get test failed with "spawn 7za ENOENT"
When I set USE_SYSTEM_FPM=true then I only get  the following error
A has '/usr/share/doc/testapp/changelog.Debian.gz' and B has '/usr/share/doc/testapp/changelog.gz')
and when I change the linuxExpectedContents  changelog.gz to changelog.Debian.gz 
the tests pass.
Any advice?

**Comment by develar** [comment]
> When I set USE_SYSTEM_FPM=true then I only get the following error
A has '/usr/share/doc/testapp/changelog.Debian.gz' and B has '/usr/share/doc/testapp/changelog.gz')

fpm outdated, update `gem update fpm`.

> While running the tests I get test failed with "spawn 7za ENOENT"

Update sources and `npm install`, see https://github.com/electron-userland/electron-builder/issues/399 I hope it is fixed now.
