### ISSUE TITLE
How to test auto-update in dev mode?

### ISSUE THREAD

**Issue by TongDaDa** [electron-userland/electron-builder#4000]
* **Version**: 
Latest

Latest

* **Target**: 
Mac

I want to develop the auto-update functionality, but It just performs on when I packed it, so I want it to work on dev mode.

I have known the `dev-app-update.yml` configuration file, I place it to the current app-path that gets by `app.getAppPath()` but It seems doesn't work for my environment, It result `null` by calling the `checkForUpdatesAndNotify` and my generic server has not received any request.

<img width="675" alt="屏幕快照 2019-06-28 下午7 34 26" src="https://user-images.githubusercontent.com/23241188/60339613-cf850680-99db-11e9-8614-efe4b5be2bf2.png">

How to make the practice that experiences the auto-update in dev mode work?

**Comment by b-zurg** [comment]
So for anyone looking at this you can have a yaml file like this in the root repo if you have a local minio server running.

```yaml
endpoint: http://localhost:9000
provider: "s3"
bucket: "test-update"
```
