### ISSUE TITLE
Can't fork child with portable

### ISSUE THREAD

**Issue by Cefold** [electron-userland/electron-builder#4003]
* **Version**:  electron-builder: 20.44.4

* **Target**:  windows portable

At first I put js file inside ASAR, and the app under `win-unpacked` folder worked, but with portable app, it won't work.
```
    const cp_path = 'app.asar/server/server.js';
    const rootFolder = path.join(__dirname, '..');
    child = fork( cp_path,[], {  cwd: rootFolder  } );
```
----------

Then I tried to put js file outside of ASAR
```
"extraResources": [
    "server/server.js"
 ]
```
Then `child = fork(path.join(__dirname, '../server/server.js'))`, but the result stays the same, everything works with the app under win-unpacked folder, but portable app won't fork the child.

**Comment by Cefold** [comment]
I tried
```
const childPath = path.join(__dirname, '../app.asar/server/server.js');
child = fork( childPath,[],  { } );
```
The result is still the same, everything works with the app under `win-unpacked` folder, but portable app won't fork the child.

**Comment by mikecbone** [comment]
@Cefold Did you find a solution to this not working when packed up into the portable images?

**Comment by phinolex** [comment]
Please share your solution. I'm experiencing the exact same issue
