### ISSUE TITLE
Is it safe to delete/exclude “inspector” folder from Electron 5 package?

### ISSUE THREAD

**Issue by aabuhijleh** [electron-userland/electron-builder#4005]
* **Version**: 20.39.0
* **Target**: 32-bit  Windows

I’ve recently updated Electron from v4 to v5 and found a new ~9MB folder `inspector` containing 188 files  in the installed Electron package at **`node_modules/electron/dist/resources/inspector`** or **`${packagedApp}/resources/inspector`** after packaging with `electron-builder`. What is this for?

There seems to be no consequences for deleting this folder.

**Is it safe to delete/exclude it from my packaged app?**

Package used: electron@5.0.6 for 32-bit Windows

Thanks in advance!

**Comment by develar** [comment]
I think, electron-builder will add special option to remove this folder (obviously, you will be not able to use devtools from chrome anymore).

**Comment by aabuhijleh** [comment]
@develar. actually, I can still use devtools perfectly after removing it which is why I was so confused.

**Comment by develar** [comment]
Then better to ask in electron github issue tracker, because builder just builds :)

**Comment by aabuhijleh** [comment]
Alright I asked [here](https://github.com/electron/electron/issues/19075).

**Comment by aabuhijleh** [comment]
Looks like this folder is going to be removed in future releases > 5.0.6
