### ISSUE TITLE
Snap does not launch when Ubuntu uses Wayland

### ISSUE THREAD

**Issue by thomasnordquist** [electron-userland/electron-builder#4007]
* **Version**:  20.44.1
* **Version**:  21.0.6

* **Target**: snap

I received a bug-report that electron does not launch since it cannot find the X11 server.
https://github.com/thomasnordquist/MQTT-Explorer/issues/145
`(mqtt-explorer.bin:26930): Gtk-WARNING **: 17:02:23.483: cannot open display: :0`

### I did some tests and started Ubuntu 18.04 with [wayland enabled](https://www.maketecheasier.com/switch-xorg-wayland-ubuntu1710/):
- AppImage: ✔️(works)
- .deb: ✔️(works)
- Snap: 🚨(does not start)

Disabling wayland with the `WAYLAND_DEBUG=1` environmental resolved the issue.
(I added the flag to the snap environmental configuration for now)

I also tested if the AppImage build uses the XServer or Wayland. [(by testing if the eyes of the xeyes test application move while hovering over a window)](https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a)
According to the "xeyes test", AppImage and the debian package build seem to use the XServer within wayland (xwayland).

**Edit**: The issue is probably not limited to ubuntu, but systems using wayland in general

**Comment by develar** [comment]
Maybe it is fixed in `21.0.6`. Please try.

**Comment by thomasnordquist** [comment]
I tried `21.0.6` but it did not make a difference.

**Comment by develar** [comment]
Electron doesn't support WAYLAND (https://github.com/electron/electron/issues/9056), so, the only solution for now — to disable WAYLAND for snap. Snap itself supports ability to access host WAYLAND socket.

Fixed in 21.0.8.

**Comment by thepont** [comment]
A lot of electron apps are able to run using Xwayland if the `GDK_BACKEND` environment var is set to `X11`.

I don't know if this helps, but I appeared here after having issues with another electron app, and resolved it this way.

See: https://wiki.archlinux.org/index.php/Wayland#Electron_based_applications_/_VS_Code

**Comment by julian-alarcon** [comment]
Electron now supports wayland, but there are still some bugs.
http://github.com/electron-userland/electron-builder/issues/9452
