### ISSUE TITLE
How to notify existing users after switching release repo?

### ISSUE THREAD

**Issue by benxgao** [electron-userland/electron-builder#4009]
We released to repoA before, and we are planning to switch to repoB as release repo, is it possible to notify existing users to update their software?

**Comment by develar** [comment]
Do you mean updater information? Just release last release that have new update info to old repo and that's all. So, old user will be updated to this version, and then this version will update to recent version from your new repo.

**Comment by benxgao** [comment]
Yes thats what I mean @develar , thanks. Do you mean I run the same github releasing script with the same version to both repoA and repoB, then it gonna work? Would you mind explaining how it works?
