### ISSUE TITLE
应用相关信息可以脱离package.json，放到electron-builder.yaml中

### ISSUE THREAD

**Issue by GuoSirius** [electron-userland/electron-builder#4017]
* **Version**:  29.30.0

* **Target**: win

![image](https://user-images.githubusercontent.com/48358523/60691029-06d54500-9eff-11e9-8fae-544e3b22f862.png)

以上信息可以都放进electron-builder里面吗，而不是优先读取package.json里的版本信息，应用名称等

**Comment by develar** [comment]
Я не очень понял, простите.
