### ISSUE TITLE
MacOS - Custom Protocol opens the base Electron App, not the app I just built

### ISSUE THREAD

**Issue by rmincling** [electron-userland/electron-builder#4020]
electron-builder@20.44.4
electron@5.0.5

* **Target**: MacOS

Hi,

I am trying to add a custom url scheme for my electron app. In the code i use setAsDefaultProtocolClient('testapp') as suggested by docs. This works fine when the app is already open in dev mode.

For a production build I add the following to the package.json:
```
"build": {
    ...
    "protocols": {
      "name": "testapp",
      "schemes": [
        "testapp"
      ]
    },
    ....
}
```

I then build the app as normal using the command "electron-builder -m zip", then unzip the resulting build.

Now when i try to open the app via the url (starting with 'testapp://') only the base electron app opens, not the app I have just built, screenshot below.
![Screenshot 2019-07-05 at 10 17 20](https://user-images.githubusercontent.com/40352976/60712091-29bb2580-9f0e-11e9-8478-9f3bb563238c.png)

If I then open my built app manually, close it, and then try t open via the url again, my newly built app opens. Which makes sense as the code within the app is setting the scheme via setAsDefaultProtocolClient().

Any advice on how to make my built app open by default without me having to manually open the app then close it?

Kind regards,

Rob

**Comment by rmincling** [comment]
Ok, i resolved this mysefl once I noticed I had an old version of my app installed via dmg, residing in the applications folder. Once I removed this, the newly built app from the zip file opened fine via url :)

**Comment by colinrw** [comment]
hey @rmincling, i am having the exact same issue right now. 
i have this working in development, but when i package my application, the deeplink opens the default Electron app instead of my actual application. I already removed all associated files in my applications folder. 
what command have you used to package your app? i used `"package": "electron-forge package"` for my packaging. 

do you have any idea how i can solve the opening of the base Electron app? thank you :)

**Comment by Cycododge** [comment]
I kept experiencing this as well. For those stuck here, the package [electron-app-universal-protocol-client](https://www.npmjs.com/package/electron-app-universal-protocol-client) was easy to use and made the problem go away.
