### ISSUE TITLE
MacOS - Read-only file system

### ISSUE THREAD

**Issue by rmincling** [electron-userland/electron-builder#4021]
electron-builder@20.44.4
electron@5.0.5

MAcOS

As a small example piece of code. I am just trying to load a .webm file and convert to to avi using ffmpeg. These are found in /media within the app directory. 

If I build the app and run it manually then there are no issues, the .avi file is written. However, if i try to open the app via a url scheme from a browser, the app opens, but I get this error message:

`Uncaught Exception:
Error: ffmpeg exited with code 1: /Volumes/Example 1.0.0/Example.app/Contents/Resources/app/media/test.avi: Read-only file system`

Any advice on how to resolve this?

Cheers,

Rob

**Comment by develar** [comment]
It seems app opened not from install path /Applications, but from attached DMG. Just detach DMG :)

**Comment by rmincling** [comment]
That did the trick, awesome, thank you!
