### ISSUE TITLE
Broken snaps on Lubuntu

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-builder#4024]
* **Version**: 21.0.10

* **Updater**: 4.1.1

* **Target**: snap

Since the new snap template that reduces snap sizes dramatically has been introduced I haven't been able to run snaps produced by electron-builder under Lubuntu, they seem to install correctly, but then launching the app from the terminal exits immediately.

**Comment by develar** [comment]
Lubuntu version?

**Comment by fabiospampinato** [comment]
Sorry I forgot to mention this: I'm using Lubuntu 18.04.2, 64 bit.

**Comment by fabiospampinato** [comment]
It seems to be launching in Ubuntu proper, same version, weird.

**Comment by develar** [comment]
Just run from Terminal and inspect error output. I am going to investigate this issue this evening (or tomorrow morning).

**Comment by fabiospampinato** [comment]
I see no output at all in Lubuntu.

**Comment by fabiospampinato** [comment]
I've fixed the bug that was preventing the snap to launch on Ubuntu, but now I'm getting the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/media/psf/Home/Projects/notable/package.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at new Conf (/snap/notable/x1/resources/app.asar/main.js:9:116135)
    at new ElectronStore (/snap/notable/x1/resources/app.asar/main.js:1:25287)
    at Module.<anonymous> (/snap/notable/x1/resources/app.asar/main.js:21:6036)
    at __webpack_require__ (/snap/notable/x1/resources/app.asar/main.js:1:150)
    at Object.<anonymous> (/snap/notable/x1/resources/app.asar/main.js:9:86198)
    at __webpack_require__ (/snap/notable/x1/resources/app.asar/main.js:1:150)
```

Which looks very application-specific but the same app bundled in the `deb` format can run properly under the same system, so maybe the issue here comes from `electron-builder`?

**Comment by develar** [comment]
I cannot reproduce. I suppose it is specific for your app, I can only suggest to debug what's wrong.

You can also try hello-world snap to ensure that it is not your system specific issue: https://drive.google.com/file/d/1RKNTBzzmK2TlG2-nrBz9cuJ-usmkID5H/view?usp=sharing

**Comment by fabiospampinato** [comment]
> You can also try hello-world snap to ensure that it is not your system specific issue: drive.google.com/file/d/1RKNTBzzmK2TlG2-nrBz9cuJ-usmkID5H/view?usp=sharing

Is this supposed to do anything? Launching it from the terminal exits immediately for me, launching it from the menu makes the cursor with the spinning wheel show for a bit and nothing happens.

**Comment by develar** [comment]
Something is wrong with your system if you don't see hello world.

`sudo apt-get update && sudo apt-get upgrade -qq`?

**Comment by fabiospampinato** [comment]
I tried that, I rebooted, reinstalled the demo snap, but nothing changed.

Is there anything else that you'd like me to try? This is most likely an issue with my installation if this works for you in Lubuntu, even though I haven't done anything strange with it, I just use it every once in a while for testing stuff.

**Comment by develar** [comment]
I am not expert, I can suggest you to google it, e.g. see https://askubuntu.com/questions/783979/how-do-i-debug-snaps

**Comment by develar** [comment]
If no luck, you can ask help https://forum.snapcraft.io/

**Comment by thomasnordquist** [comment]
You might also want to run the snap with `export ELECTRON_ENABLE_STACK_DUMPING=true`.

### snappy-debug
`snappy-debug` from develar's response will show if the application tried to load files that do not exist (for instance missing libraries etc., invalid file permissions, some AppArmor rules).

[Example](https://github.com/thomasnordquist/MQTT-Explorer/issues/135
) from a user where Electron tried to access an App-unrelated path (no idea why)
![d3ee62ab239cda0edb4581c195df92b48d6b32a8_2_1380x776](https://user-images.githubusercontent.com/7721625/59928148-641cc100-943e-11e9-922e-1b2dd99779c8.png)

### Reference system
Also running a fresh Lubuntu installation (in VirtualBox) might provide a more reproducible scenario or at least gives you a working reference system to compare to.
