### ISSUE TITLE
Linux set Installation window icon

### ISSUE THREAD

**Issue by harshkoralwala** [electron-userland/electron-builder#4025]
Hello,
I need help for linux to set icon.
electron-builder version:"20.44.4"
From documents, I come to know we can not set deb file Icon.
It's Ok.
I want to change the Installation time Application icon.
Please refer below image(red area).
How can I change that?
![install](https://user-images.githubusercontent.com/33347464/60807858-6b64fe00-a1a4-11e9-87b3-6840432ff423.png)

Second Thing,
I want to set apllication icon on uninstall screen.
Kindly refer below image.
How can i achieve it?
![uninstall](https://user-images.githubusercontent.com/33347464/60808200-4d4bcd80-a1a5-11e9-8047-64b25f912fe9.png)

My package config for linux looks like:

   "build": {
        "appId": "testapp001",
        "compression": "maximum",
        "productName": "test",
        "directories": {
            "buildResources": "resources",
            "output": "test-release"
        },
        "files": [
            "dist",
            "main.js"
        ],
       "linux": {
            "category": "Utility",
            "synopsis": "test Application",
            "executableName": "test-Setup",
            "description": "testtesttesttest",
            "vendor": "test",
            "maintainer": "test 2",
            "target": [
                "deb"
            ],
            "icon": "./resources/512x512.icns"
        },
    }

The icns file exists at this place and it works fine for application window(i can say start menu of linux)

Thanks in Advance.

**Comment by develar** [comment]
First, please try 21.0.10
Second, consider to use snap (and publish to store) instead of deb.

**Comment by harshkoralwala** [comment]
Hello @develar ,
Thanks for the reply.
I have upgraded version to  21.0.10.
My package.json looks like....
             "electron-builder": "^21.0.10",
As I want output as `deb` file only, so I cannot test with snap solution.
My application needs to be distributed locally.
After upgrading the version still, I cannot find a solution.
Please suggest me more solutions.

Thank you.

**Comment by develar** [comment]
snap also can be distributed locally, simply `snap install file.snap --dangerous`.

Please set env `DEBUG=electron-builder` (see https://www.electron.build/#debug) and attach log of the terminal output.

**Comment by harshkoralwala** [comment]
Hello @develar ,
Thank you again for quick reply.
I tried solution provided by you of snap.
But,actually as per my requirement i want to distribute application where installation screen **MUST** there (in all OS),so before installation user can read basic description,official website and all other details of app.
This all information snap doesn't  provide on installation.
Thats why i am focusing on `deb` type.As it provides installation screen with all mentioned details.

So kindly provide me solution of my issue with `deb` fromat.

Thank you in advance.

**Comment by develar** [comment]
@harshkoralwala Ok, to further investigate the issue, I need debug log (see my previous message about `DEBUG` env). 

Don't get me wrong — I just want to be sure that you are understand what are you doing. Yes, clicking on snap doesn't open installation window, actually, OS doesn't help user to install it. I suggest to open topic on https://forum.snapcraft.io/ and ask why. I believe that snap is a better format than deb. (but of course, it is not a reason to not fix issues for deb, that's why this issue is not closed and debug logging was requested).

**Comment by harshkoralwala** [comment]
Hello @develar,

Thank you for your suggestion.
As youare interested to investigate the issue.I am sharing logs.

1. _My script tag of Package.json has one Property for Linux build as:_

 **"dist-linux": "electron-builder --linux",**

Logs are as follows:

harsh@harsh-Desktop:~/Harsh.koralwala/test-Angular$ DEBUG=electron-builder
harsh@harsh-Desktop:~/Harsh.koralwala/test-Angular$ npm run dist-linux

> test@0.0.1 dist-linux /home/harsh/Harsh.koralwala/test-Angular
> electron-builder --linux

  • electron-builder  version=21.0.10 os=4.15.0-54-generic
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=/home/harsh/Harsh.koralwala/test-Angular/package.json
  • writing effective config  file=test-release/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=5.0.1 appOutDir=test-release/linux-unpacked
  • building        target=deb arch=x64 file=test-release/test_0.0.1_amd64.deb
harsh@harsh-Desktop:~/Harsh.koralwala/test-Angular$ 

I hope I have given you what you expect.If not just share exact step for desired logs.

Is there any other way by that I can achieve the desired output for Linux build?

Thank you in advance.

**Comment by develar** [comment]
Please execute `DEBUG=electron-builder npm run dist-linux`

**Comment by Youzi-wr** [comment]
hi,@harshkoralwala 
have you solved this problem?
i got the same question with you

**Comment by harshkoralwala** [comment]
Hello @Youzi-wr,

  As per discussion with @develar, this functionality we can not achieve.

  Though I have downloaded an official deb file for VS code, slack & firefox. On all of them's installation screen, the icon displayed is the same as we can see in our build's installation screen.

So I believe we **can not** change the icon.

Thank You.

**Comment by IhorVimmi** [comment]
@harshkoralwala hi! did u solve you issue now?)

**Comment by harshkoralwala** [comment]
Hello @IhorVimmi,

Sorry to say, but this functionality can not be achieved as it does not support till now...

Please refer my last reply for more details  https://github.com/electron-userland/electron-builder/issues/4025#issuecomment-523371031

Waiting for this feature support.

Thank you.
