### ISSUE TITLE
Wrong `version` in artifactname when building for Mac

### ISSUE THREAD

**Issue by bohrapp** [electron-userland/electron-builder#4026]
* **Version**: 20.44.4

* **Target**: mac

When setting the `artifactName` with the variable `${version}` the value `0.1.0` is used, while `package.json` is `0.2.3`.

Building on Windows 10 for win64 and win32 does not produce this error.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

And please use electron-buidler 21
