### ISSUE TITLE
Builder not setting app icon for OSX

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#403]
`  "icon": "assets/app.icns",`

Mentioned in #289.
`    "electron-builder": "^3.20.0",`

`npm run dist`

DMG icon is fine. Application icon is default electron. Windows icon works as expected.

**Comment by develar** [comment]
Just change `build/icon.icns` file. `icon` in the configuration `build.osx` it is DMG icon, not app icon.

**Comment by develar** [comment]
Yeah, my be we should rename it to make it more clear.

**Comment by amsoell** [comment]
Sorry, this is still unclear to me—is it no longer possible to set the OS X app icon using electron-builder? The documentation doesn't show any way.

**Comment by develar** [comment]
> Sorry, this is still unclear to me—is it no longer possible to set the OS X app icon using electron-builder? 

Just change build/icon.icns file. If you want to explicitly set to some path (not recommended) — set `build.icon`.
