### ISSUE TITLE
blockmap Forbidden - autoUpdater - private S3 bucket

### ISSUE THREAD

**Issue by stuartcusackie** [electron-userland/electron-builder#4030]
* **Version**: 20.44.4

* **Target**: Windows

I am getting this error after removing public access from my S3 bucket through the AWS console. It also happens when I grant full public access to the bucket and use 'acl': 'private' in my publish config.

```
cannot download differentially, fallback to full download: 
Error: Cannot download "https://mybucket.s3.amazonaws.com/releases/electron/win/MyApp%20Setup%200.0.6.exe.blockmap", status 403: Forbidden
```

The actual Setup file seems to download fine.

It is a private repository but I have given my AWS user FullS3Access and it still doesn't work.

**Is this the problem?:**
It can see that the aws region is missing from my autoUpdater blockmap requests:

`Download block maps (old: "https://mybucket.s3.amazonaws.com/releases/electron/win/MyApp%20Setup%200.0.6.exe.blockmap", new: https://mybucket.s3.amazonaws.com/releases/electron/win/MyApp%20Setup%200.0.7.exe.blockmap)`

The files are actually located at:
`https://mybucket.s3-eu-west-1.amazonaws.com/releases/electron/win/MyApp+Setup+0.0.6.exe.blockmap`

So the region is being added correctly to my autoUpdater.requestHeaders but I have no control over the blockmap request urls.

I am using aws4 to sign my request headers.

**Comment by stuartcusackie** [comment]
Think I just found my answer:
https://github.com/electron-userland/electron-builder/pull/3536

I can see this fix has been merged into master. Is it part of a tagged version?

**Comment by mvkanha** [comment]
You have to add region and channel name @stuartcusackie

**Comment by stuartcusackie** [comment]
@mvkanha I already have the region set in my builder config. Do I really need the channel??

I am trying to set up channels like so:

```
version: **'x.x.x-beta'**,
builder: {
	    appId: 'com.myname.myapp',
	    productName: 'MyApp',
            **generateUpdatesFilesForAllChannels: true,**
		win: {
	    	    icon: 'src-electron/icons/icon.ico'
	        },
	    nsis:{
	      oneClick: false,
	      allowToChangeInstallationDirectory: true
	    },
	    publish: [{
			provider: 's3',
			**region: 'eu-west-1',**
			bucket: 'mybucket',
			path: '/releases/win/',
			acl: 'private'
		}]
	  }
```

**Comment by mvkanha** [comment]
I think you should add endpoint to configuration.
Here I am attaching my configuration
```
"publish": [
			{
				"provider": "s3",
				"bucket": "mybucket",
				"region": "us-east-2",
				"path": "/",
				"endpoint": "https://s3.us-east-2.amazonaws.com",
				"channel": "latest"
			}
		] 
```

**Comment by develar** [comment]
Obviously, if bucket is private, electron-updater cannot access it.

**Comment by stuartcusackie** [comment]
@develar You actually can access a private bucket by updating the autoUpdater request headers. 

Example:

```
autoUpdater.on('checking-for-update', () => {
  let opts = {
  	service: 's3',
  	region: 'eu-west-1',
  	method: 'GET',
        // define your host variable elsewhere
  	host: host,
        // define your latest.yml path elsewhere
        path: latest_yml_path
  };
  aws4.sign(opts, {
    // define access credential variables elsewhere
    accessKeyId: access_key_id,
    secretAccessKey: secret_access_key
  });
  log.info('Signed:');
  log.info(opts);
  autoUpdater.requestHeaders = opts.headers
})

autoUpdater.on('update-available', (info) => {
	log.info('Update available. Info:');
	log.info(info);
  // define your release path variable elsewhere
  let update_path = `/${release_path}/${info.path}`;
  let opts = {
  	service: 's3',
  	region: 'eu-west-1',
  	method: 'GET',
  	host: host,
    path: update_path
  };
  aws4.sign(opts, {
    accessKeyId: access_key_id,
    secretAccessKey: secret_access_key
  });
  log.info('Signed:');
  log.info(opts);
  autoUpdater.requestHeaders = opts.headers
  autoUpdater.downloadUpdate()
})

```

This works except for the Blockmap request. I will try what @mvkanha has said and set an endpoint in my publish config.

**Comment by develar** [comment]
@stuartcusackie PR will be accepted, should be easy to find error and fix it.

**Comment by stuartcusackie** [comment]
@develar Thanks. I will try to find where the region can be added in the autoUpdater code.

@mvkanha Adding the endpoint and channel didn't work. I get an aws when I do that:
_SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided_

```
 publish: [{
			provider: 's3',
                        // here's my region
			region: 'eu-west-1',
			bucket: 'mybucket',
                        // I tried both of these endpoints:
                        // endpoint: 'https://s3.eu-west-1.amazonaws.com',
			endpoint: 'https://mybucket.s3-eu-west-1.amazonaws.com',
			channel: 'latest',
			path: '/releases/win/',
                        // no acl needed. Private bucket
			acl: null
		}]
```

**Comment by stuartcusackie** [comment]
Maybe the region isn't the problem. 

I wonder if the blockmap requests need two more aws signing requests (one for the old blockmap and one for the new)...

**Comment by justinwaite** [comment]
Did you ever get this figured out @stuartcusackie?

**Comment by david-wallace-croft** [comment]
I have this problem as well.  It happens even if I have differentialPackage set to false such that there are no blockmaps uploaded to S3.  Is there a way to disable request for blockmaps?

**Comment by yangfan0356** [comment]
I had the same problem, I did the following experiment:  Configure s3 bucket to allow .blockmap files to be downloaded by public, open CloudTrail to track events. If I use a browser, I can directly download all .blockmap files, I can also see the download record in CloudTrail. Now, if I use autoupdate to check update and download, from CloudTrail, it only have two records:  the record to download latest.yml, and the record to actually download the exe file. But I didn't see any records to download .blockmap files at all!    If I use browser to download the exe file directly, the CloudTrail will have a record with "AccessDenied".  I was expecting two records in CloudTrail with "AccessDenied" for downloading .blockmap files, but I cannot see the requests at all.

**Comment by yangfan0356** [comment]
> Maybe the region isn't the problem.
> 
> I wonder if the blockmap requests need two more aws signing requests (one for the old blockmap and one for the new)...

I believe you are right. I checked the server log for the event, and there exists two requrests for both old and new blockmap files, and they all have "SignatureDoesNotMatch" access deny.

**Comment by yangfan0356** [comment]
> Maybe the region isn't the problem.
> 
> I wonder if the blockmap requests need two more aws signing requests (one for the old blockmap and one for the new)...

@stuartcusackie 

I guess you are right. I checked the server log for the download events, and there exists two requrests for both old and new blockmap files, and they all have "SignatureDoesNotMatch" access deny (perhaps they used the signed header we set for requestheader for the actual EXE).

**Comment by mmaietta** [comment]
>Is there a way to disable the requests for blockmaps?

I took a quick look at the code, this is where the requests for the blockmaps are:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L175-L177
You can comment out the post-compiled line in your node modules and give it a try, I'm not sure how it'll impact diff downloads. The function always returns false and I didn't see elsewhere in the code for `.blockmap` string constants

Here's where it uses the headers:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L144-L147


>I wonder if the blockmap requests need two more aws signing requests (one for the old blockmap and one for the new)...

Happy to review a PR on this if someone is willing to give it a stab 🙂 
These are our Dev Env Setup instructions: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by bansari-electroscan** [comment]
Facing the same issue. @stuartcusackie were you able to make it work?

**Comment by stuartcusackie** [comment]
> Facing the same issue. @stuartcusackie were you able to make it work?

@bansari-electroscan  I did not. I'm still using a public bucket.

**Comment by ktc1016** [comment]
I was able to make it work on my private bucket by adding "channel" as one of the attributes in "dev-app-update.yml" file

I'm still figuring out what's the connection of this and the production app-update.yml but I hope this will also work on your project

```
-- dev-app-update.yml
provider: s3
region: region-1
bucket: bucket-name
endpoint: https://s3.region.amazonaws.com
channel: latest
path: /path/to/file/
acl: private

```

**Comment by leena-prabhat** [comment]
Setting `autoUpdate.autoDownload = false;` has no effect. After calling `autoUpdate.downloadUpdate();`, update process starts downloading blockmap file. After that shows 403 Forbidden, the full file is downloaded.

**Comment by ktc1016** [comment]
@leena-prabhat after reviewing my detailed logs, it looks like the 403 forbidden error message was just captured by my "try-catch" statements. Therefore, my solution did not fix the original issue. 

Apologies, I'll update my comment to avoid further confusions.

**Comment by code-drunk-debug-sober** [comment]
Hey, anyone got anything or any combination to work on it ? I tried multiple scenarios but none success. facing issues from SignatureDoesNotMatch - The request signature we calculated does not match the signature you provided. Check your key and signing method. This is even after setting the feed url.

**Comment by qube13** [comment]
It is not a solution to this problem but a workaround. We developed a lambda function that returns a signedUrl in the Location header, the autoUpdater automatically redirects to the signedUrl.  
```javascript
// in electron app 
autoUpdater.setFeedURL({
    provider: 'generic',
    url: `https://my-lambda-function.com/`,
    useMultipleRangeRequest: false,
  });
autoUpdater.requestHeaders = { 'x-api-key': API_KEY };
```

in lambda function: 

```javascript
// create a signedUrl based on the pathParameters 
return {
    statusCode: 302,
    headers: { Location: signedUrl },
  }

```

**Comment by linchen1010** [comment]
I also had this issue during developing. It's not a solution but I end up using aws-sdk to download my file if electron-updater found any updater version in my private S3. 
This will not utilize the blockmap to download the updated app, and it might take a few more seconds to download your app.
You will also need to run the installer manually to trigger that update, I did it with child_process.spawn.
```
import * as AWS from 'aws-sdk';
import fs from 'fs';

autoUpdater.on('checking-for-update', () => {
    let opts = {
        service: 's3',
        region: s3_region,
        host: s3_host,
        path: latest_yml_path
    };
  
    aws4.sign(opts, {
        accessKeyId,
        secretAccessKey,
        sessionToken
    });
    autoUpdater.requestHeaders = opts.headers
})

autoUpdater.on('update-available'), (updateInfo) => {
    AWS.config.update({
        accessKeyId,
        secretAccessKey,
        sessionToken
    });
    const s3 = new AWS.S3();
    const version = this.getVersion(updateInfo.path);
    const params = {
        Bucket: `${your_s3_bucket}`,
        Key: `${path_to_your_file)`
    }
   download(s3, params);
}
```

and the download looks something like this:

```
const download = (s3, params) => {
  s3.getObject(params, async (err, data) => {
      if (err) {
          throw new Error(err)
      }
      await fs.promises.writeFile(filePath, data.Body);
      console.info(`${filePath} has been downloaded!`);
      autoUpdater.emit('update-downloaded', filePath);
  });
}
```

**Comment by rohanrk-tricon** [comment]
Were you able to find out how to do it @stuartcusackie @develar @mayankvadia @justinwaite ?

`publish: [{
    provider: 's3',
    region: 'us-east-1',
    bucket: 'mybucket',
    endpoint: 'https://s3.us-east-1.amazonaws.com',
    channel: 'latest',
    path: '/',
   acl: 'private'
}]`
and my autoupdater looks like this 

`class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;
    autoUpdater.checkForUpdatesAndNotify();
   }}
`
`Error:
 HttpError: 403 Forbidden
 ...
 at createHttpError (C:\Program Files\xyz\resources\app.asar\dist\main\webpack:\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:14:12)`

**Comment by bansari-electroscan** [comment]
@rohanrk-tricon  Did you found any solution around this? Tried public and private buckets, played around with the request options. Nothing works. It's always signature mismatch error.  :(

**Comment by mmaietta** [comment]
Not sure where it is failing tbh. Is the electron distributable being signed/modified after electron-builder produces the app-update file pre-upload to s3? That would change the signature of the file after the update hash has been generated.

**Comment by rohanrk-tricon** [comment]
@bansari-electroscan @mmaietta I was finally able to make it work.
The publish inside your build object in package.json should look like this.
```
  "build": {
    "publish": {
      "provider": "s3",
      "bucket": "<your-bucket-name>",
      "acl": null,
      "channel": "latest",
      "path": "/",
      "endpoint": "https://s3.<region>.amazonaws.com"
    }
  },
```

This is my AppUpdater class which performs all auto-update events

```
import aws4 from 'aws4';

class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;

    // To check for updates
    // To get the latest.yml file we are authenticating the request with getOptions func
    autoUpdater.logger.info('Auto update initiated...');
    autoUpdater.on('checking-for-update', () => {
      autoUpdater.logger?.info('checking for updates...');
      autoUpdater.requestHeaders = getOptions('latest.yml').headers;
    });

    // To get the latest exe file we are authenticating the request with getOptions func
    // options.path contains name of latest exe
    autoUpdater.on('update-available', (options) => {
      autoUpdater.logger?.info('update available event is triggered');
      autoUpdater.requestHeaders = getOptions(options.path).headers;
    });

    autoUpdater.on('update-downloaded', async (event, arg) => {
      autoUpdater.logger?.info('update download triggered');
    });

    // Set the feed URL of our s3 bucket
    autoUpdater.setFeedURL(`${process.env.AWS_FEED_URL}`);

    // Checks for updates and notifies the user
    autoUpdater.checkForUpdatesAndNotify().catch((err) => {
      autoUpdater.logger = err;
    });
  }
}
```
 getOptions() will attach required authentication headers(accessKeyId and secretAccessKey) to each call to the s3 bucket.
 You need to keep all AWS related info in an env file.
 
```
 // util function to authenticate our requests to s3
const getOptions = (path: string) => {
  const options = {
    service: process.env.AWS_SERVICE,
    region: process.env.REGION,
    method: 'GET',
    // define your host variable elsewhere
    host:
      process.env.AWS_S3_BUCKET +
      '.s3.' +
      process.env.REGION +
      '.amazonaws.com',
    // define your latest.yml path elsewhere
    path,
  };
  // autoUpdater.logger?.info('options--', options);

  aws4.sign(options, {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  });
  // autoUpdater.logger?.info('options2--', options);
  return options;
};
```
  you can see what auto updater logs in this file path
  
  **C:\Users\user\AppData\Roaming\Electron\logs\main.log**
  
  Let me know, how that works out for you.

**Comment by code-drunk-debug-sober** [comment]
> @bansari-electroscan @mmaietta I was finally able to make it work. The publish inside your build object in package.json should look like this.
> 
> ```
>   "build": {
>     "publish": {
>       "provider": "s3",
>       "bucket": "<your-bucket-name>",
>       "acl": null,
>       "channel": "latest",
>       "path": "/",
>       "endpoint": "https://s3.<region>.amazonaws.com"
>     }
>   },
> ```
> 
> This is my AppUpdater class which performs all auto-update events
> 
> ```
> import aws4 from 'aws4';
> 
> class AppUpdater {
>   constructor() {
>     log.transports.file.level = 'info';
>     autoUpdater.logger = log;
> 
>     // To check for updates
>     // To get the latest.yml file we are authenticating the request with getOptions func
>     autoUpdater.logger.info('Auto update initiated...');
>     autoUpdater.on('checking-for-update', () => {
>       autoUpdater.logger?.info('checking for updates...');
>       autoUpdater.requestHeaders = getOptions('latest.yml').headers;
>     });
> 
>     // To get the latest exe file we are authenticating the request with getOptions func
>     // options.path contains name of latest exe
>     autoUpdater.on('update-available', (options) => {
>       autoUpdater.logger?.info('update available event is triggered');
>       autoUpdater.requestHeaders = getOptions(options.path).headers;
>     });
> 
>     autoUpdater.on('update-downloaded', async (event, arg) => {
>       autoUpdater.logger?.info('update download triggered');
>     });
> 
>     // Set the feed URL of our s3 bucket
>     autoUpdater.setFeedURL(`${process.env.AWS_FEED_URL}`);
> 
>     // Checks for updates and notifies the user
>     autoUpdater.checkForUpdatesAndNotify().catch((err) => {
>       autoUpdater.logger = err;
>     });
>   }
> }
> ```
> 
> getOptions() will attach required authentication headers(accessKeyId and secretAccessKey) to each call to the s3 bucket. You need to keep all AWS related info in an env file.
> 
> ```
>  // util function to authenticate our requests to s3
> const getOptions = (path: string) => {
>   const options = {
>     service: process.env.AWS_SERVICE,
>     region: process.env.REGION,
>     method: 'GET',
>     // define your host variable elsewhere
>     host:
>       process.env.AWS_S3_BUCKET +
>       '.s3.' +
>       process.env.REGION +
>       '.amazonaws.com',
>     // define your latest.yml path elsewhere
>     path,
>   };
>   // autoUpdater.logger?.info('options--', options);
> 
>   aws4.sign(options, {
>     accessKeyId: process.env.AWS_ACCESS_KEY_ID,
>     secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
>   });
>   // autoUpdater.logger?.info('options2--', options);
>   return options;
> };
> ```
> 
> This is how I have set my env file which will hold all aws info
> 
> ```
>   AWS_ACCESS_KEY_ID: <your access key id>,
>   AWS_SECRET_ACCESS_KEY: '<your secret access key>',
>   REGION: '<region>,
>   OUTPUT: 'json',
>   AWS_S3_BUCKET: '<your-bucket-name>',
>   AWS_SERVICE: 's3',
>   AWS_FEED_URL: 'https://<your-bucket-name>.s3.<region>.amazonaws.com',
> ```
> 
> You can see what auto updater logs in this file path
> 
> **C:\Users\user\AppData\Roaming\Electron\logs\main.log**
> 
> **Note: It will be easy for you if you enter all the sensitive info in the code directly as a string until you test it, later you can move it to env file.**
> 
> Let me know, how that works out for you.

Thanks for the great info and sorry for jumping in. Even I am in a similar dilemma. Can you please also share the S3 bucket policy that you have set for it ?

**Comment by rohanrk-tricon** [comment]
@code-drunk-debug-sober

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAppS3Releases",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::release-bucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::release-bucket"
            ]
        }
    ]
}
```
I found this somewhere when I was working on it, check the actions allowed for the bucket, and also check if you have enabled CORS(Cross-Origin Resource Sharing).

**Comment by EliveltonRepolho** [comment]
Hello @rohanrk-tricon , can you post your CORS config ?

I am getting this error `Error: Error: net::ERR_CERT_COMMON_NAME_INVALID`  and not sure what else I have to do, I have a bucket with public access enabled (not sure if it really needed), created an user with the policy you sent on comment above and set following CORS:

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Content-Range",
            "Content-Length",
            "ETag"
        ]
    }
]
```

One question about the policy you just sent, are you attaching to an user or setting directly in the bucket ? Directly in the bucket it says `Principal` is neede, I am asking because not sure what I may be doing wrong.

Thanks in advance

**Comment by reddybhavanish** [comment]
i am getting error 403 forbidden after following all these steps.

**Comment by ricopollantecs** [comment]
any updates on this?

**Comment by fabiobsantosprogrow** [comment]
Nowadays we still facing the same problem with version 6.1.4.
I don't understand why this issue is closed when people still having issues...
We will try the download manually on private s3 https://github.com/electron-userland/electron-builder/issues/4030 but I would like to have some guidance how to this using the auto-update without extra work.
