### ISSUE TITLE
Expected identifier, string or number error on Windows in 20.44.0

### ISSUE THREAD

**Issue by aullman** [electron-userland/electron-builder#4031]
* **Version**: 20.44.0

* **Target**: Windows 'nsis'

With the 20.44.0 release I started getting this error message on Windows when doing a build. Rolling back to 20.43.0 fixed the issue for me.

![image (1)](https://user-images.githubusercontent.com/733672/60887893-c710b380-a298-11e9-917d-bc8143d3957a.png)

**Comment by aullman** [comment]
Sorry, I take it back. Something else is going on here.

**Comment by fairking** [comment]
@aullman Hi my friend, Did you fix that problem. I also get the same error every time I do `npm install` or `npm run postinstall`.
What was you solution?

![image](https://user-images.githubusercontent.com/13495631/145586310-6fecbd78-5a8c-4cd8-8004-2176d651d884.png)
