### ISSUE TITLE
deb fails to install on the new Debian Buster

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-builder#4033]
* **Version**: 21.0.10

* **Updater**: 4.1.1

* **Target**: deb

I've got an issue, [here](https://github.com/notable/notable/issues/725), for an app of mine where the provided `deb` package, available [here](https://github.com/notable/notable/releases/download/v1.6.1/notable_1.6.1_amd64.deb), can't be installed on the recently released Debian Buster because one library called `libgnome-keyring0` has been deprecated in favor of another one called `libsecret`.

I think this is most probably an issue coming from `electron-builder`.

**Comment by fabiospampinato** [comment]
Well that was quick 😄 Thank you so much @develar!

**Comment by develar** [comment]
There is an easy workaround for you, but I will prefer to release a new version. Please try `21.0.13`

**Comment by fabiospampinato** [comment]
Trying to install the _old_ deb in Debian 10 KDE outputs the following error:

<img width="434" alt="Screen Shot 2019-07-09 at 21 47 27" src="https://user-images.githubusercontent.com/1812093/60918583-f96be200-a293-11e9-8e02-eda40c7746b3.png">

Trying to install the _new_ deb instead outputs the following:

<img width="438" alt="Screen Shot 2019-07-09 at 21 45 00" src="https://user-images.githubusercontent.com/1812093/60918606-0557a400-a294-11e9-903b-0310710dac2d.png">

I tried installing the missing packages via `apt-get`, but they don't see to be available via the default sources. I'm going to download the Gnome-flavored version of Debian 10 and try again, maybe that changes something.

**Comment by fabiospampinato** [comment]
Same exact result on Debian 10 Gnome, I suppose the issue might not be fixed after all?

**Comment by fabiospampinato** [comment]
I can still install the new `deb` in Ubuntu 18.04 though.

**Comment by fabiospampinato** [comment]
Also v21.0.13 seems to break building mac apps too, I forgot to save the error message, and I don't remember that target caused the issue (maybe it was `pkg`) unfortunately.

**Comment by fabiospampinato** [comment]
I've tried v21.0.14 but that doesn't work for me either 🤷‍♂

**Comment by gscscnd** [comment]
In the [most recent version of fpm.go][1], the produced Debian package would still depend on [gir1.2-gnomekeyring-1.0][2], which is unavailable in buster.

[1]: https://github.com/develar/app-builder/blob/2a1fcddeb8fcefc1b0e496daba12527d7c2b663c/pkg/package-format/fpm/fpm.go#L133-L134
[2]: https://tracker.debian.org/pkg/libgnome-keyring

**Comment by dvergeylen** [comment]
`gir1.2-gnomekeyring-1.0` dependency has been removed in https://github.com/develar/app-builder/commit/5768a760e60a1d3259684bb6f4636504507967b6 (see [this line](https://github.com/develar/app-builder/commit/5768a760e60a1d3259684bb6f4636504507967b6#diff-c3cc8aef80b033aede8349cb7989eeadL134)) but @develar did not make a new release yet.
