### ISSUE TITLE
Linux package name

### ISSUE THREAD

**Issue by josephsmendoza** [electron-userland/electron-builder#4037]
For SideQuest, the product name is acceptable on Mac and Windows, but for Linux we need the package name to be lowercase, however I don't see any documentation on specifying that. Specifically, if someone wants to uninstall, they should run something like `apt remove sidequest` as opposed to `apt remove SideQuest`

**Comment by develar** [comment]
I suggest to use snap instead of deb.

Please see https://www.electron.build/configuration/linux#LinuxConfiguration about `executableName`

But yes, 

`"--name", appInfo.linuxPackageName,`- for now no way to set custom name.

**Comment by develar** [comment]
Please try:

```
  "build": {
    "deb": {
        "fpm": ["--name", "sidequest"]
      }
  }
```
