### ISSUE TITLE
Error spawning gm on Travis CI

### ISSUE THREAD

**Issue by BHSPitMonkey** [electron-userland/electron-builder#404]
Hi,

Similar to #239, I'm seeing my Travis build die with `Unhandled rejection Error: spawn gm ENOENT`.

The build can be viewed here: https://travis-ci.org/BHSPitMonkey/hipchat-electron/jobs/130203544

Travis config: https://github.com/BHSPitMonkey/hipchat-electron/blob/2214aca814340947001fdc02ee0ab78bc4239c63/.travis.yml

Any suggestions?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux Please install `graphicsmagick` package.

**Comment by BHSPitMonkey** [comment]
Thanks, that wasn't part of the sample travis.yml configuration earlier on that page.

**Comment by HoverBaum** [comment]
I am running into the same error. Tried a few different approaches to install that current try here https://github.com/HoverBaum/BlankUp-Electron/blob/master/.travis.yml

But nothing seems to work. Could someone point me into a direction as to how to make this work?

**Comment by develar** [comment]
@HoverBaum I see that Linux build is ok. https://travis-ci.org/HoverBaum/BlankUp-Electron To fix OS X build, use conditional https://github.com/develar/electron-builder/blob/e923e72b1565a5d8870d91e01a3d44b7a58b9b06/.travis.yml#L31 
```
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y graphicsmagick; fi
```

**Comment by HoverBaum** [comment]
Awesome. Thanks for the ultra fast reply @develar. I was missing the `fi` in earlier attempts.
