### ISSUE TITLE
Electron application can't launch on mac os

### ISSUE THREAD

**Issue by ecourdoisy** [electron-userland/electron-builder#4044]
Hello, 

I've an electron application with "electron": "^5.0.6", "electron-builder": "^21.0.15"

I build it on my mac (on Mojave), it works and I can launch app file.

I send it to an other mac (on Mojave). When I launch the application I've an error, application can't launch because apple can't see if there are malwares inside, need update application.

But electron and electron builder is up to date and application is signin. I've done npm update and yarn upgrade.

Where is the problem ? I can't see same error on web (original error is in french si I hav'nt exact wording).

Thanks a lot !

**Comment by KASOGIT** [comment]
Apple introduced a new concept of notarization, in order to solve your warning you should notarize your app, i advise you to follow this tutorial explaning how to achieve that :) https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by ecourdoisy** [comment]
Thanks a lot for you answer, I modify my configuration to notarize my application but can't finish builde :(
I've this error : *** Error: To use this application, you must first sign in to iTunes Connect and sign the relevant contracts. (1048)

I go on iTunes Connect but see anything, and  I'm using application password
