### ISSUE TITLE
Many temp node/tmp files on user PC 

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#4047]
* **Version**: `v20.40.2`

* **Target**: 
Windows

Okay, so there are two issues basically. Our app create following files on each run -
a) Two `*.node` file
b) Two `*.tmp` file (type - Icon)

![image](https://user-images.githubusercontent.com/2263909/61159832-fcc4cf00-a51a-11e9-8d05-bd57589c72a1.png)

![image](https://user-images.githubusercontent.com/2263909/61159819-edde1c80-a51a-11e9-9d94-0ef82966f0bd.png)

We have fixed `a)` using [this](https://github.com/zulip/zulip-desktop/pull/791). Any idea about how to fix `b)`?

Note - the issue is critical since a few user reported -
> For context, one user had 70gb of those files by the time he noticed. My own PC had close to 1gb.

**Comment by akashnimare** [comment]
@develar please have a look whenever you get time :)

**Comment by tongyuhu** [comment]
This is a native module, and I have encountered this problem！

**Comment by tongyuhu** [comment]
> Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set asarUnpack - please file an issue if this doesn’t work.
smartUnpack = true Boolean - Whether to automatically unpack executables files.
ordering String
asarUnpack Array<String> | String - A glob patterns relative to the app directory, which specifies which files to unpack when creating the asar archive.


Some addon are not included in smartUnpack. You need to add it manually。
` "asarUnpack":"**\\*.node"`
