### ISSUE TITLE
Configuration docs generation issue

### ISSUE THREAD

**Issue by oNaiPs** [electron-userland/electron-builder#4050]
Check screenshot: `protocols` should not be part of `fileAssociations`, and `name`/`schemes` should be bullets inside `protocols`. There may be other errors related to the generation but these were the ones that caught my attentions.

Not sure how to fix them, but should be simple for the person that is maintaining these generation scripts.

Page: https://www.electron.build/configuration/configuration

<img width="704" alt="Screen Shot 2019-07-12 at 3 13 24 PM" src="https://user-images.githubusercontent.com/374130/61161214-c4d87000-a4b7-11e9-9cc9-232dd1b89b87.png">

**Comment by oNaiPs** [comment]
This issue still applies

**Comment by thegecko** [comment]
This is still an issue and caused a lot of confusion through misinformation.
