### ISSUE TITLE
macOS CFBundleDocumentTypes should contain LSHandlerRank 

### ISSUE THREAD

**Issue by semireg** [electron-userland/electron-builder#4052]
* **Version**: 20.39.0 (but no hits searching repo for LSHandlerRank keyword)

* **Target**: macOS

I received a warning on App Store submission:

## ITMS-90788: Incomplete Document Type Configuration
The CFBundleDocumentTypes dictionary array in the com.My App Info.plist should contain an LSHandlerRank value for the CFBundleTypeName '$documentTypeName' entry. Refer to https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW1 for more information on the LSHandlerRank key.

This seems to be a recently added requirement.

**Comment by Jocs** [comment]
@semireg Any updates on this issue? I also meet this same issue when I upload pkg package to App Store.

**Comment by semireg** [comment]
Not fixed yet.
