### ISSUE TITLE
APP_Name cannot be opened because of a problem (image attached)

### ISSUE THREAD

**Issue by mazlano27** [electron-userland/electron-builder#4053]
* **Version**: 21.0.15

* **Target**: Mac & Windows

Hi, after updating to electron-builder 21.0.15, my electron app builds (no errors shown in console), however upon launching the application - the following error pops up:

<img width="422" alt="Screenshot 2019-07-14 at 12 40 22 PM" src="https://user-images.githubusercontent.com/29986983/61179432-b8c5ed00-a634-11e9-84a5-90c70aef5de3.png">

Reverting back to electron-builder 20.44.4 fixed the issue.

Im currently using Mac OS 10.14.5 and my Mac build script is as follows:

"mac": {
      "target": "zip",
      "category": "public.app-category.productivity"
}

Thank you for your attention and any help would be much appreciated.

Additional information: I do not plan to release my app on the apple store. It's just a productivity app i'm building for internal use within my organisation.

**Comment by inweid** [comment]
@mazlano27 I have the same problem, version electron-builder 20.44.4
