### ISSUE TITLE
Can't set different names to app axecutable and app folder.

### ISSUE THREAD

**Issue by Zver64** [electron-userland/electron-builder#4056]
* **Version**: 20.44.4

* **Target**: windows

I have following configuration in my packaje.json file:
```
"build": {
    "productName": "MyApp",
    "appId": "com.myApp",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "win": {
      "icon": "build/icons/icon.ico",
      "requestedExecutionLevel": "requireAdministrator"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true
    }
```

When I install my app on windows, I see the following default instalation path:
**.../Program Files/MyApp**
If I don't change it, then all files wil be installed in this folder and the executable name woild be MyApp.exe. If i change the installation path, for example, to this:
**.../Program Files/CustomFolder**
then all files will be installed into **.../Program Files/CustomFolder/MyApp/ and the executable file will remain MyApp.exe.
There are two things I wan't to change:
1. I want to have different name for app folder and app executable. For example folder name: MyApp, executable name: myAwesomeApp.exe, so after I install my app into default path it would be **/Program Files/MyApp/MyAwesomeApp.exe**
2. If I change the path to **.../Program Files/CustomFolder** - I don't want to create MyApp subfolder in it.

**Comment by Zver64** [comment]
And also I found an interesting behavior. I figured out that if the folder where you want to install your app doesn't exist yet, then the app will be installed in it directly. If this folder exists and even if it is empty - there would be created another folder inside of it named same as **productName** property in the package.json. In my case it is **MyApp**. 
But there is more. Let's say I have installed my app in "C:\testFolder". If I try to install the app again - it will automatically find the previous installation path and suggest it to me. And if I click yes, it will first uninstall previously installed app and install it again. But. I have custom "customRemoveFiles" script that does not remove the app folder, which means the folder "C:\testFolder" still exist when the app is about to be installed again. So it creates a subfolder named **MyApp**, as described above. 
I guess I should use custom installation script or something like that? I am not good at writing these scripts and there is not much to read about custom scripts in the documentation of electron-builder, so maybe someone knows where I can find default scripts that are used in electron-builder. Any help would be much appreciated.

**Comment by Zver64** [comment]
I think a found a piece of code responsible of creating a subfolder. It is in `node_modules/app-builder-lib/templates/nsis/assistedInstaller.nsh` starting at line 43 in my version of electron-builder which is currentrly 20.44.4.
Here is the code:
```
!define MUI_PAGE_CUSTOMFUNCTION_PRE instFilesPre

    # sanitize the MUI_PAGE_DIRECTORY result to make sure it has a application name sub-folder
    Function instFilesPre
      ${If} ${FileExists} "$INSTDIR\*"
        ${StrContains} $0 "${APP_FILENAME}" $INSTDIR
        ${If} $0 == ""
          StrCpy $INSTDIR "$INSTDIR\${APP_FILENAME}"
        ${endIf}
      ${endIf}
    FunctionEnd
```
It would be great if this was optional and also had a configurable folder name. And also I think it would be better if it would check the path even if it doesn't exist yet.

**Comment by srepollock** [comment]
Is there any other way to change the application name for the outputted files? (.app, .exe, .deb)?
