### ISSUE TITLE
Cannot find module '../../electron-osx-sign/util-identities'

### ISSUE THREAD

**Issue by just-jeb** [electron-userland/electron-builder#4067]
* **Version**: 
21.1.0

* **Target**: 
OSX

Error:
```
  ⨯ Cannot find module '../../electron-osx-sign/util-identities'
Require stack:
- /Users/xxx/yyy/node_modules/app-builder-lib/out/codeSign/macCodeSign.js
- /Users/xxx/yyy/node_modules/app-builder-lib/out/macPackager.js
- /Users/xxx/yyy/node_modules/app-builder-lib/out/packager.js
- /Users/xxx/yyy/node_modules/app-builder-lib/out/index.js
- /Users/xxx/yyy/node_modules/electron-builder/out/builder.js
```

And indeed, no such folder in latest version of `app-builder-lib` (21.1.0). Forgot to package? 
The error comes from [here](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/macCodeSign.ts#L297).

**Comment by josiah1888** [comment]
For those looking for a quick fix, I built successfully on electron-builder versions 21.0.X

**Comment by just-jeb** [comment]
Downgrade works for me too but then for some reason ChromeDriver is not starting and Spectron tests fail. I guess I'll wait for the fix, seems like it's just about adding the folder to package.
