### ISSUE TITLE
Trouble building delta package for Squirrel.Windows on OSX

### ISSUE THREAD

**Issue by mhagmajer** [electron-userland/electron-builder#407]
I came across following problems listed below when trying to get Squirrel delta nupkg for Windows to upload to GitHub releases on OSX. I have `remoteReleases` pointing to my GitHub repository of the app.

- Squirrel downloaded the previous package but complained that the new package did not exist. My guess is that it didn't look for it in the `dist` directory.
- Windows artifacts where never uploaded to GitHub releases. I had to manually upload them. It works fine with OSX.

**Comment by develar** [comment]
> Windows artifacts where never uploaded to GitHub releases. I had to manually upload them. It works fine with OSX.

Fixed, delta is uploaded.

> Squirrel downloaded the previous package but complained that the new package did not exist

Fixed, regression.

**Comment by mhagmajer** [comment]
Great. Much appreciated!
