### ISSUE TITLE
NSIS: App installation directory is different for oneClick build vs attended/non-oneClick build

### ISSUE THREAD

**Issue by chrisckc** [electron-userland/electron-builder#4070]
* **Version**: 20.44.4

* **Target**: win

I recently added this section to my package.json build config to disable one click install and allow the user to change the per machine and install location options but found that it also changes the default directory that the app is installed into (for a windows build):

```
"nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true
    },

```
Without the above section, an unattended one-click installer is created which on a clean installation installs the app into: `\AppData\Local\Programs\<packagejson.name>\` so unless you use the "build.extraMetadata" option to change the "name" property, multiple apps with different "productName" but the same "name" values overwrite each other despite creating separate registry entries and desktop shortcuts (which seem to be based on the productName.

When adding the above config which creates the attended installer, on a clean install the app is installed into: `\AppData\Local\Programs\<packagejson.build.productName>` allowing separate app installations to be created by changing "productName" without also having to change the "name " property.

If the app is installed first using the one-click installer and then installed over the top using the attended installer, the attended installer detects an existing installation at: `\AppData\Local\Programs\<packagejson.name>\` , then removes the contents of the directory and installs the app at: `\AppData\Local\Programs\<packagejson.name>\<packagejson.build.productName>` instead of` \AppData\Local\Programs\<packagejson.build.productName>`
uninstalling the app then leaves behind an empty `\AppData\Local\Programs\<packagejson.name>\ `directory but does correctly remove the registry entries.

Not sure if this is an NSIS issue or electron-builder issue.

Created this a separate issue, i first mentioned it here:
https://github.com/electron-userland/electron-builder/issues/4065

**Comment by namish800** [comment]
@chrisckc Were you able to resolve this issue? I am facing the same issue I have two versions of an app with different name and product Name but when I install them they overwrite each other

**Comment by robsonkades** [comment]
@chrisckc  @namish800  I have the same problem :/

**Comment by namish800** [comment]
@robsonkades I solved the issue by changing the AppID for both the versions in the package.json

**Comment by robsonkades** [comment]
thank you

**Comment by robsonkades** [comment]
@namish800 for me, it still doesn't solve the problem, I need to have two installations, regardless of the version.
even though I customized the installation directory, it removes the other installations. :/

**Comment by jamninetyfive** [comment]
> @namish800 for me, it still doesn't solve the problem, I need to have two installations, regardless of the version.
> even though I customized the installation directory, it removes the other installations. :/

same here .~
