### ISSUE TITLE
squirrel is deprecated and i want to move to NSIS. (how to move to NSIS with autoUpdate functionality working) 

### ISSUE THREAD

**Issue by MuhammadHaseebAli** [electron-userland/electron-builder#4077]
"electron": "^5.0.6"
i am using default autoUpdate of electron 
squirrel

i am packaging app with target squirrel and i am using electron default autoupdate and https://github.com/ArekSredzki/electron-release-server for this purpose. 
can you please guilde me how can i make nupkg file from NSIS as /electron-release-server needs it

**Comment by wslp12** [comment]
me too 
my package.json  file 
"build": {
        "win": {
            "target": "nsis"
        },
        "nsis": {
            "oneClick": false,
            "allowToChangeInstallationDirectory": false
        }
    },
Nupkg file not created after build
