### ISSUE TITLE
exec: "sh": executable file not found in $PATH when packaging

### ISSUE THREAD

**Issue by TongDaDa** [electron-userland/electron-builder#4080]
* **Version**: latest

* **Target**: darwin

I used programmatic API to build with electron-builder upon my own shell of `exec`.

If I run a file that invoking the programmatic API of electron-builder directly on my CLI, It works well, but I take this file to my another new file to execute it using `spawn/exec` it has thrown an error. the log is below.

```
  •  writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  •  packaging       platform=darwin arch=x64 electron=5.0.2 appOutDir=dist/mac
  ⨯  error
exec: "sh": executable file not found in $PATH
github.com/develar/app-builder/pkg/download.GetCacheDirectory
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:215
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:60
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337
```

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

**Comment by TongDaDa** [comment]
@develar The problem was found.

Because my child_process is given the option`{env: { a: 12} }`, It overwrites the `PATH` variable in the env of process, so the first main process to execute it works fine, it didn't work.

**Comment by TongDaDa** [comment]
:cherries:
