### ISSUE TITLE
bug(linux): New fileAssociation support produces wrong xml that cannot be parsed

### ISSUE THREAD

**Issue by nicodorn** [electron-userland/electron-builder#4089]
* **Version**: 21.1.3

* **Target**: linux(deb)

The commit c11fa1f1033aeb7c378856d7db93369282d363f5 produces wrong xml that cannot be parsed correctly. The problem are two closing &lt;/mime-info&gt;. Simply omit line 40 of the commit and add the backtick to line 39. Then everything should be fine.

**Comment by develar** [comment]
Should be already fixed in 21.1.5

**Comment by nicodorn** [comment]
It is indeed. Pardon me!
