### ISSUE TITLE
A crossplatform way to create file associations

### ISSUE THREAD

**Issue by sunabozu** [electron-userland/electron-builder#409]
There are the `extend-info` option and `installer.nsi.tpl` template that allow you to create file association on OS X and Windows separately, but from the application's perspective it's the same thing. Can we have a metadata field in `package.json` for describing file extensions we are interested in? It might look like this:

```
"build": {
  ...
  "file-associations": "txt|xyz|pdf"
}
```
Then it could be translated to specific entries in `Info.plist` and `installer.nsi.tpl` respectively. It would be very handy.

**Comment by develar** [comment]
We don't use NSIS installer anymore. 

And Squirrel.Windows is a pathetic parody (sorry, sorry, I am really sorry, but to be honest — it is true) to OS X app. Much better than NSIS and other windows installers, but still just a pathetic parody.

So, Squirrel.Windows doesn't support declarative way to create shortcuts or file associations. It is your responsibility in your app code to setup it during first run (or on update — events `--squirrel-install` or `--squirrel-updated`). First google result — https://www.npmjs.com/package/windows-registry (I didn't check, just google).

We are not commercial organization, so, I am not going to fix Squirrel.Windows in my free time. It is relatively easy to fix, though (we DO already our own fork to fix some obvious things, but I want to touch windows code only when it is really needed). 

I see two ways to fix it:
1) Magic app wrapper. i.e. you will be forced to use some framework. Don't like it.
2) `Info.json` in the setup package. Before call `--squirrel-install` or `--squirrel-updated` handlers, we read descriptor and perform required actions. Yep — it is  very easy to implement.

If you want to help — https://github.com/develar/Squirrel.Windows/tree/build (main branch is `build`). Sorry, I am not going to do it. No time. And no pleasure to touch dead *** windows.

**Comment by sunabozu** [comment]
Thank you for a such detailed explanation. I'll try to handle it in the application itself.

**Comment by develar** [comment]
Since NSIS is outperforms Squirrel.Windows in all aspects, issue is reopened and will be implemented. For NSIS only. Because once #529 will be implemented, NSIS will be set as default windows target.

#563

**Comment by develar** [comment]
@sunabozu Your confirmation that file associations are the same for both platform (example of your config) is very appreciated.

**Comment by rwlnd** [comment]
Following up on this, it would be nice if you could supply an image/icon for the file association in the build config.

**Comment by develar** [comment]
@rwlnd mac or win?

**Comment by rwlnd** [comment]
@develar - I'm sure it can be done on win , not sure about mac as I don't use that actively
The process to add an icon for a file association is descrbed in this [stackoverflow](http://stackoverflow.com/questions/9093481/add-a-new-file-association-in-windows-7)

- Right click the new key and create a subkey DefaultIcon.
- Set the new key's default value to C:\Some\Path\To\Your\Icon\Ressource.ico,0 (the 0 is the index of the icon to be used; if there's only one icon in the ressource, it has to be 0).

**Comment by develar** [comment]
Windows — we should use http://nsis.sourceforge.net/FileAssoc instead of current implementation to specify icon.

**Comment by develar** [comment]
@rwlnd next version (5.28.0): just create `ext.ico` in the `build` directory (where `ext` is your ext). Or set `icon` (relative to `build`).

**Comment by sfraise** [comment]
Is this supposed to be working in the current build now?

I tried the following but didn't seem to work.
"build": {
    "fileAssociations": {
      "ext": "myext",
      "name": "MYEXT"
    }

**Comment by develar** [comment]
@sfraise Yes. Please specify target OS and targets (nsis — boring or one-click, per-machine or not. Currently tested only for per-machine. Not per current user.

**Comment by sfraise** [comment]
@develar Thanks, I probably should have shown my whole build section.  Here's what I have below, it doesn't seem to be working, not throwing any errors or anything, just not associating the extension to the program:

`  "build": {
    "appId": "com.elite.planner",
    "app-category-type": "public.app-category.business",
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "resources/windows/icon.ico"
    },
    "nsis": {
      "oneClick": true,
      "installerHeaderIcon": "resources/windows/setup-icon.ico"
    },
    "mac": {
      "icon": "resources/osx/icon.icns"
    },
    "dmg": {
      "icon": "resources/osx/dmg-icon.icns",
      "background": "resources/osx/dmg-background.png"
    },
    "fileAssociations": {
      "ext": "elite",
      "name": "ELITE"
    }
  },
  "directories": {
    "buildResources": "resources"
  },`

**Comment by sfraise** [comment]
This doesn't seem to work on Macs?

**Comment by develar** [comment]
@sfraise Planned to implemented. Currently, I am very busy :) Cannot promise. Is it critical for you?

**Comment by sfraise** [comment]
It is kind of, app goes to client Monday.  Primary device will be surface pro 3's so the windows installer is the most important but some will be using macs so has to be an option.

Is there anything I can do to help out?

**Comment by develar** [comment]
> Is there anything I can do to help out?

Well, you always can use `extend-info` (https://github.com/electron-userland/electron-builder/issues/397) Ok, I increase priority.

**Comment by sfraise** [comment]
If I have to I can try to manually add the association to the plist but your implementation is a heck of a lot more simple lol.  Do you have a rough idea on when you'll have a chance to get to it?

**Comment by develar** [comment]
> Do you have a rough idea on when you'll have a chance to get to it?

2 days.

**Comment by sfraise** [comment]
Perfect, I really appreciate it.

**Comment by sfraise** [comment]
Hey Develar, we hand this app over to the client in about 7 hours so just wanted to see if you had a chance to do any more with the Mac implementation?  I'm sure we'll be pushing out a revision soon anyway but just wanted to see if we might still be able to sneak this into this initial release.

**Comment by develar** [comment]
@sfraise Will be pushed in 10-20 minutes after test. And published after push in 10 minutes.

**Comment by develar** [comment]
If Linux is required for you — feel free to file new issue about it. Currently, no short-term plans to add file accusations for Linux and new issue about it will be an indicator of interest. In the original description stated only "allow you to create file association on OS X and Windows separately".

**Comment by sfraise** [comment]
Sweet, you rock @develar!

**Comment by sfraise** [comment]
I'm getting an error trying to build on windows now when setting perMachine: true in the package.json file, any ideas?

**Comment by develar** [comment]
@sfraise It seems that you also set `oneClick` to `false`. Such combination was not initially supported and so, not tested (no tests at all). #700

**Comment by sfraise** [comment]
No, I have oneClick: true set

**Comment by develar** [comment]
@sfraise Please try 6.3.0 and if you still get error, please file new issue with error message

**Comment by sfraise** [comment]
no joy

**Comment by sfraise** [comment]
Here's my full package.json...

`{
  "build": {
    "appId": "com.elite.planner",
    "app-category-type": "public.app-category.business",
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "resources/windows/icon.ico"
    },
    "nsis": {
      "oneClick": true,
      "installerHeaderIcon": "resources/windows/setup-icon.ico"
    },
    "mac": {
      "icon": "resources/osx/icon.icns"
    },
    "dmg": {
      "target": [
        "nsis"
      ],
      "icon": "resources/osx/dmg-icon.icns",
      "background": "resources/osx/dmg-background.png"
    },
    "fileAssociations": {
      "ext": "elite",
      "name": "ELITE"
    }
  },
  "directories": {
    "buildResources": "resources"
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "build": "gulp build",
    "prerelease": "gulp build --env=production",
    "release": "build --x64 --publish never",
    "start": "gulp start",
    "pretest": "gulp build-unit --env=test",
    "test": "electron-mocha app/specs.js.autogenerated --renderer --require source-map-support/register",
    "pree2e": "gulp build-e2e --env=test",
    "e2e": "mocha app/e2e.js.autogenerated --require source-map-support/register"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "electron": "1.3.3",
    "electron-builder": "^6.3.0",
    "electron-mocha": "^3.0.0",
    "fs-jetpack": "^0.9.0",
    "gulp": "^3.9.0",
    "gulp-batch": "^1.0.5",
    "gulp-less": "^3.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.3.5",
    "mocha": "^3.0.2",
    "rollup": "^0.34.7",
    "source-map-support": "^0.4.2",
    "spectron": "^3.3.0",
    "yargs": "^4.2.0"
  }
}
`

**Comment by sfraise** [comment]
If I put quotes around the true value (ie. "perMachine": "true") the build doesn't fail, haven't verified that the file association is working that way though yet.  We shouldn't have to wrap a true/false value in quotes here correct?

**Comment by develar** [comment]
> We shouldn't have to wrap a true/false value in quotes here correct?

Yes, must be not wrapped. Please file new issue and attach build log. Without error message I cannot help you.

**Comment by sfraise** [comment]
Well that seems to also be a problem, I was going to copy the npm-debug.log last night with the other stuff but for some reason its not writing it which is strange because it was before if a build failed.  In my ide there is a blank spot where a file should be but no file.

Here's a screen shot of the error I get in the command line:
![electron-error](https://cloud.githubusercontent.com/assets/5533668/18097102/31b8fe0a-6ea2-11e6-9c98-9352e9164b98.png)

Just out of curiosity I set up a fresh new project and electron boilerplate install and got the same thing.  Does electron builder use Visual Studio assets to actually do the build and could it be some issue with my VS setup?

**Comment by develar** [comment]
@sfraise Please create separate issue — please don't mix.

> Just out of curiosity I set up a fresh new project and electron boilerplate install and got the same thing. 

Please create new separate issue and attach sample project, I will test it.

**Comment by sfraise** [comment]
See new issue https://github.com/electron-userland/electron-builder/issues/715
