### ISSUE TITLE
Help debugging Avast/AVG CyberCapture installer interference

### ISSUE THREAD

**Issue by tnishimura** [electron-userland/electron-builder#4093]
* **Version**: electron-builder 21.1.5
electron 5.0.8

electron-updater 4.1.2

* **Target**: Windows 10, NSIS

Problem: I make installers with electron 21.1.5 for NSIS. It is signed with an EV certificate from digicert. With almost all antivirus systems, there is no problem, and indeed Virustotal reports nothing malicious. However, for Avast and AVG (AVG is owned by Avast and afaik use same tech underneath), they have a subsystem called "CyberCapture" which intercepts installation of files they have never seen before, and "interrogates" them. This somehow interferes with the NSIS installer and causes various errors, as seen below:

![eb-error-1](https://user-images.githubusercontent.com/519704/61919277-ca977200-af09-11e9-8f42-9f608c03770b.png)

![eb-error-2](https://user-images.githubusercontent.com/519704/61919284-cc613580-af09-11e9-905c-c6f7e8763fad.png)

![eb-error-3](https://user-images.githubusercontent.com/519704/61919544-f9faae80-af0a-11e9-8575-5ee565ce2df2.png)

You can see clearly on the first one that "Avast CyberCapture" around the window. If you close the error window, you get:

![eb-cybercapture](https://user-images.githubusercontent.com/519704/61919547-fc5d0880-af0a-11e9-9d92-d0784585dc29.png)

This issue doesn't seem to be caused by a false positive -- it seems to be related to this CyberCapture system. I say this because even after the file has been "interrogated" by Avast, and I have submitted the file to VirusTotal, the issue persists. I am trying to contact Avast about this issue but they seem to not care, though I will keep trying.

**I know that this isn't electron-builder's responsibility to fix**. But, I'd like to know if anyone has any hints on debugging this issue -- I don't even know how to view NSIS logs -- or any possible workarounds. 

Previous related issues I found:
* [Issue 550](https://github.com/electron-userland/electron-builder/issues/550): This is about FP's (which mine is not), and I do not see an option to use Zip compression in the docs any more.

P.S. I have donated for this issue.

**Comment by develar** [comment]
Yes, `useZip` is the first option that you can try to overcome the issue. This option is undocumented (marked as private).


```
"build":  {
  "nsis": {
    "useZip":true
  }
}
```

**Comment by tnishimura** [comment]
I added the useZip option. The resulting installer is the same size, which I assume useZip isn't doing anything (?). It has the same problem as described (gets caught by Avast's CyberCapture system). My package.json looks something like:

    { 
       "author" : {
          "email" : "example@example.com",
          "name" : "example, LLC"
       },
       "build" : {
          "appId" : "com.example",
          "electronVersion" : "5.0.8",
          "nsis" : {
             "deleteAppDataOnUninstall" : true,
             "oneClick" : true,
             "useZip" : true
          },
          "productName" : "Example Product Name",
          "win" : {
             "certificateSubjectName" : "example, LLC",
             "icon" : "./icon.ico"
          }
       },
       "dependencies" : {
          "archiver" : "^3.0.0", 
          "debug" : "^4.1.1",
          "electron-localshortcut" : "^3.1.0",
          "electron-log" : "^3.0.6", 
          "electron-updater" : "^4.1.2",
          "fs-extra" : "^7.0.1", 
          "glob" : "^7.1.3"
       }, 
       "description" : "example description",
       "devDependencies" : { 
          "electron-builder" : "^21.1.5"
       },
       "homepage" : "https://www.example.com",
       "main" : "main.js",
       "name" : "example", 
       "productName" : "Example Product Name",
       "version" : "1.6.8"
    }

**Comment by greenimpala** [comment]
@tnishimura did you get this problem sorted with Avast and AVG in the end?
