### ISSUE TITLE
Does electron builder alter the require.resolve() in any way?

### ISSUE THREAD

**Issue by gtamas** [electron-userland/electron-builder#4095]
* **Version**: latest (20.44.x)

* **Target**: Mac, dmg

The nodeJS function require.resolve() does not return anything at all. The same code works fine in dev builds, but when building for prod, this returns an empty string (no matter what module's path you are trying to resolve). 

Does electron builder alter this function in any way? I know webpack has the same function, but that behaves differently. It works with module ids instead of module names. 

My question is: how is it possible that this function returns nothing in prod builds. Same thing happens when building for Windows.,

**Comment by develar** [comment]
No, app code is not handled by electron-builder.

It is some Electron specific.
