### ISSUE TITLE
Custom entitlements causes app to crash on macOS 10.14+

### ISSUE THREAD

**Issue by HeberLemus** [electron-userland/electron-builder#4097]
* electron-builder 21.1.2: 

* MAC - .dmg - 10.14+: 

anytime i try to specify a custom entitlements file my app will crash. if i allow the defaults to be set, the app works and opens, but the users webcam and audio cannot be accessed

the entitlements im trying to set is com.apple.security.device.camera and com.apple.security.device.audio-input with the default ones of com.apple.security.cs.allow-unsigned-executable-memory and com.apple.security.cs.disable-library-validation

my app works on 10.13.6 and below, when needing permissions to access hardware wasnt an issue

also tried setting
`"extendInfo": {
        "NSMicrophoneUsageDescription": "I need access to your microphone to send your voice to others in the session room.",
        "NSCameraUsageDescription": "I need access to your camera so that others can see you in the session room."
      }`

as by accident i discovered a comment block within the electron package that said

> Important: In order to properly leverage this API, you must set the
    NSMicrophoneUsageDescription and NSCameraUsageDescription strings in your app's
    Info.plist file. The values for these keys will be used to populate the
    permission dialogs so that the user will be properly informed as to the purpose
    of the permission request. See Electron Application Distribution for more
    information about how to set these in the context of Electron. This user consent
    was not required until macOS 10.14 Mojave, so this method will always return
    true if your system is running 10.13 High Sierra or lower.

the errors i get are exactly the same in nature as the ones [here](https://github.com/electron-userland/electron-builder/issues/4040) where it shows up as a code signing error.

i have also tried
*only setting the entitlements property, not the entitlementsInherit
*setting both to the same file
*setting entitlementsInherit to a file only containing com.apple.security.cs.allow-unsigned-executable-memory and com.apple.security.inherit

have i forgotten something? (i have donated)

More Info: the package that is being used for webcam and audio is 'opentok'. you can think of it like skype, hangouts, discord, and slack that all access your webcam and microphone so you can talk to others in the same room. the purpose of the app is for a video service as part of a larger scheme so this needs to work

**Comment by UdaraJay** [comment]
I've also had this issue; the only way I can get signing to work is by using the default entitlements. I've tested every combination of entitlements to sign a darwin build and it always results in the above ^ error.

**Comment by alibosworth** [comment]
I believe that this issue is still occuring

**Comment by HeberLemus** [comment]
indeed it is, the conversation mainly moved back to https://github.com/electron-userland/electron-builder/issues/4040 as it revolves around the same thing, but in #4040 i presented a temporary solution
