### ISSUE TITLE
Builder fails somewhat randomely

### ISSUE THREAD

**Issue by anl176** [electron-userland/electron-builder#4098]
* **Version**: 21.1.5

* **Target**: mas

**Problem:**
Building for mas usually fails
```
DevUsers-MacBook-Pro:bellcrank_desktop devuser$ yarn build
yarn run v1.17.3
$ electron-builder --mac --windows
  • electron-builder  version=21.1.5 os=18.7.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=5.0.8 appOutDir=dist/mac
  • packaging       platform=mas arch=x64 electron=5.0.8 appOutDir=dist/mas
  • signing         file=dist/mac/MyApp.app identityName=Developer ID Application: MREN, INC (ABC123) identityHash=MYIDENTITYHASH provisioningProfile=development.provisionprofile
  • signing         file=dist/mas/MyApp.app identityName=Developer ID Application: MREN, INC (ABC123) identityHash=MYIDENTITYHASH provisioningProfile=development.provisionprofile
  ⨯ ENOENT: no such file or directory, unlink '/var/folders/kp/kyxglrd56xv8fp1v1tyg87740000gn/T/af326d02a1f74fa001e3543e7058a0f8bd96bb49.plist'  
      stackTrace=
        Error: ENOENT: no such file or directory, unlink '/var/folders/kp/kyxglrd56xv8fp1v1tyg87740000gn/T/af326d02a1f74fa001e3543e7058a0f8bd96bb49.plist'
          at processImmediate (internal/timers.js:439:21)
        From previous event:
          at module.exports.getProvisioningProfileAsync (/Users/devuser/Documents/bellcrank_desktop/node_modules/app-builder-lib/electron-osx-sign/util-provisioning-profiles.js:66:6)
          at module.exports.preEmbedProvisioningProfile (/Users/devuser/Documents/bellcrank_desktop/node_modules/app-builder-lib/electron-osx-sign/util-provisioning-profiles.js:153:14)
          at /Users/devuser/Documents/bellcrank_desktop/node_modules/app-builder-lib/electron-osx-sign/sign.js:327:15
          at MacPackager.sign (/Users/devuser/Documents/bellcrank_desktop/node_modules/app-builder-lib/src/macPackager.ts:202:5)
  • building        target=DMG arch=x64 file=dist/MyApp-1.0.0.dmg
  • building        target=macOS zip arch=x64 file=dist/MyApp-1.0.0-mac.zip
  • building block map  blockMapFile=dist/MyApp-1.0.0.dmg.blockmap
  • building embedded block map  file=dist/MyApp-1.0.0-mac.zip
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Sometimes build works after I make "some" kind of modification like changing entitlements or reinstalling my dev provisioning profile. Running build after a success fails even though no files were modified.

For reference, I've been following this guide: https://samuelmeuli.com/blog/2019-04-09-publishing-an-electron-app-on-the-mac-app-store/.

I generated all macOS certs through xCode and have them in my KeyChain 
![Screen Shot 2019-07-26 at 12 28 10 PM](https://user-images.githubusercontent.com/53317810/61977856-6d9cca00-afa4-11e9-801e-0c8db4e3ddbd.png)
and created a dev provisioning profile to match my device. 
![image](https://user-images.githubusercontent.com/53317810/61978047-fe73a580-afa4-11e9-9ef6-de91d90f8b3d.png)

I tried recreating all my certs/profiles, taking out entitlements until it was either empty or just sandbox and following the linked guide as closely as possible. Sometimes the build works but never twice in a row and usually replicating what I did to get the build working does not work.

I am completely new to Electron with very little experience in the Apple Development Ecosystem so I included as much detail as possible below. I suspect it's something like my entitlements or certs being wrong. For example, I have entitlements for push notifications but did not turn that on in my app's identifier capabilities. Then again, I got it building once by just removing entitlements  `<key>com.apple.application-identifier</key>` up to the line `
`

Maybe bonus clue is when a build is successful and I try to run my app in `build/dist/mas/MyApp.app` it fails with the `EXC_BAD_ACCESS (Code Signature Invalid)` Exception. I run my code through VS Code if that matters. Many thanks and sorry for wall of text.

snippet of package.json
```
{
  "build": {
    "appId": "ABC123.com.MyApp.desktop",
    "mac": {
      "target": ["dmg", "mas", "zip"],
      "electronLanguages": ["en"],
      "icon": "build/logo.icns",
      "category": "public-app-category.productivity",
      "provisioningProfile": "development.provisionprofile"
    },
    "mas": {
      "type": "development"
    }
  },
  "devDependencies": {
    "electron": "^5.0.8",
    "electron-builder": "^21.1.5"
  },
  "dependencies": {
    "electron-push-receiver": "^2.1.2"
  }
}
```

build/entitlements.mas.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- Enables App Sandbox -->
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.application-identifier</key>
    <string>ABC123.com.MyApp.desktop</string>
    <key>com.apple.developer.team-identifier</key>
    <string>ABC123</string>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>ABC123.com.MyApp.desktop</string>
    </array>
    <!-- Receive push notifications for macOS -->
    <key>com.apple.developer.aps-environment</key> 
    <true/>
    <!-- Access file dialog -->
    <key>com.apple.security.files.user-selected.read-only</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <!-- Access hardware cameras -->
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
</dict>
</plist>
```

Relevant root file structure
```
package.json
development.provisioningprofile
build
    - logo.icns
    - entitlements.mas.plist
src
    - source files
```

What a success looks like
![image](https://user-images.githubusercontent.com/53317810/61978788-02082c00-afa7-11e9-838e-d9b7ba89c280.png)

**Comment by anl176** [comment]
I feel like I'm clutching at straws here but something I noticed is that all builds that starts with signing `dist/mas/myApp.app` instead of `dist/mac/myApp.app` succeed (though opening up `mas/myApp.app` gives `EXC_BAD_ACCESS`).

![Screen Shot 2019-07-29 at 10 34 33 AM](https://user-images.githubusercontent.com/53317810/62071257-fd36b880-b1f0-11e9-8ba6-613c78398b18.png)

The above worked after trying yarn add electron/electron-builder. I did that without removing the packages so nothing should have change.

**Comment by samuelmeuli** [comment]
The release that broke this seems to be 21.0.5 (https://github.com/electron-userland/electron-builder/compare/v21.0.3...v21.0.5)

**Comment by anl176** [comment]
Downgraded to version `21.0.3` which prompted me to notarize the app. Followed https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/ and the build always works.

Running 
- mac/MyApp.app fails with EXC_CRASH (Code Signature Invalid)
- mas/MyApp.app starts but it seems a library I use `electron-push-receiver` does not work in this instance of the app
- locally with `electron .` works as I expected with `electron-push-receiver` working as well.

Running latest (`21.1.5`) causes build to fail with
![image](https://user-images.githubusercontent.com/53317810/62083374-9f639a00-b20b-11e9-9501-060aa23b7bb3.png).

I do not know entirely what this means for my project but this seems like a more consistent problem to tackle. Leaving the issue open as the original question still stands as to why my builds on latest were so inconsistent (whether the app was notarized or not).

**Comment by alibosworth** [comment]
We're getting this too with the same message with v21.2.0

**Comment by anl176** [comment]
@alibosworth I was not able to resolve my original issue but I followed these [2](https://github.com/electron-userland/electron-builder/issues/4074) [issues](https://github.com/electron/electron-osx-sign/issues/200) to create a working PKG for putting my app on the macOS App Store.

I downgraded my Electron to 5.0.7, followed the video to get a base working project, modified it, then manually signed it with the script **sign-mas.sh** in the link above. Hope that helps a bit.

**Comment by alibosworth** [comment]
Thanks @anl176, we seem to be able to have everything work properly (building and signing) by downgrading to electron-builder 21.0.15 (with Electron 5.0.3).

**Comment by alibosworth** [comment]
Actually, unfortunately while downgrading to 21.0.15 lets the MAS build work, it breaks the signing of the MAC build so we are kind of stuck, because 21.2.0 works for the MAC build but not the MAS one.

**Comment by idoodler** [comment]
I am experiencing the same issue, after trying to notarize an app which requires me to update to electron-builder `21.2.0`. I basically have the same issue as @anl176 describes.

**Comment by carstengrimm** [comment]
i am having the same issues too...

**Comment by idoodler** [comment]
Any updates on this?

**Comment by erickmaynard** [comment]
I am having the same problem on 21.2.0. I can get it to build successfully by running my build command with sudo, but this causes all sorts of issues, too many to go into in a single post.

**Comment by idoodler** [comment]
Any update on this? Has anyone been able to successfully notarize an Electron App?

**Comment by johannesjo** [comment]
This is probably the better place to look for a solution:
https://github.com/electron/electron-osx-sign/issues

**Comment by dabeku** [comment]
+1 Same issue here

**Comment by muhzi4u** [comment]
I am facing the same issue. Any update on this?

**Comment by erickmaynard** [comment]
@muhzi4u There is no update, but I found a workaround. When building a MAS build, don’t pass an array into your “target”, only do “target”: “mas”. Passing additional items into the target is what’s causing the error. As long as mas is the only target it no longer fails for me.
