### ISSUE TITLE
Change app.asar.unpacked to app.asar

### ISSUE THREAD

**Issue by MarchWorks** [electron-userland/electron-builder#4101]
* **Version**: 
20.40.2

* **Target**: 
Windows 10

I am using puppeteer in my app in dev mode there is no problem but after building and installing the app I get the following error
```
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\Nabil\AppData\Local\Programs\AniTV\resources\app.asar\node_modules\puppeteer\lib\Launcher.js:349:14)
    at ChildProcess.<anonymous> (C:\Users\Nabil\AppData\Local\Programs\AniTV\resources\app.asar\node_modules\puppeteer\lib\Launcher.js:340:64)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Error: Failed to launch chrome! spawn C:\Users\Nabil\AppData\Local\Programs\AniTV\resources\app.asar\node_modules\puppeteer\.local-chromium\win64-674921\chrome-win\chrome.exe ENOENT
```
as you can see it's an `ENOENT` the path should be
`C:\Users\Nabil\AppData\Local\Programs\AniTV\resources\app.asar.unpacked\node_modules\puppeteer\.......` instead of `C:\Users\Nabil\AppData\Local\Programs\AniTV\resources\app.asar\node_modules\puppeteer\.....`
or I should have `app.asar` instead of `app.asar.unpacked`

**Comment by MarchWorks** [comment]
Here https://github.com/GoogleChrome/puppeteer/issues/2134

**Comment by z1988hf** [comment]
@MarchWorks ， the solution which changed exefilepath from asar to asar.unpack breaks differential update. That is weird. 

 Cannot download differentially, fallback to full download: Error: sha512 checksu
m mismatch, expected 67Eby+/2lNYBbvjihFsSxyIvEcZ7xuPl97suPTmRtJjnilk/P9eHR1OEfx6
kY77n1WwtgxSbxShxOCyNv2RdjQ==, got yWWUIDoNUvI/ZA1ffCzijtEkRyOSyr9tia8Lj+9s2HfLC
A0g5Vx3HlDApkcEKFgWdqrb9Z+swfWWoOjFnkOS6A==

**Comment by MarchWorks** [comment]
@z1988hf I haven't got any error when I followed https://github.com/GoogleChrome/puppeteer/issues/2134#issuecomment-408221446
