### ISSUE TITLE
New helper apps on macOS in Electron v6

### ISSUE THREAD

**Issue by MarshallOfSound** [electron-userland/electron-builder#4104]
* **Version**: 🤷‍♂ 

* **Target**: macOS

This is just a heads up that `electron@6` will include two new "Helper.app" applications as a result of a Chromium change and builder needs to be updated to support those two new helpers.

Refs: https://github.com/electron/electron/issues/19500#issuecomment-515891941

`electron-packager` commit to handle the new files --> https://github.com/electron/electron-packager/commit/8d407e7b18c9e09f4590667fe28841f0ece974f7

**Comment by stevenroussey-desiclabs** [comment]
Related: https://github.com/electron/electron/issues/19510

**Comment by matt3224** [comment]
Any timeline on this?

**Comment by Kilian** [comment]
For reference, this is where the new helpers need to be added: https://github.com/electron-userland/electron-builder/blob/b83f5801771585c18524c3cee74e59de5fa9ab30/packages/app-builder-lib/src/electron/electronMac.ts#L44-L50

**Comment by btzsoft** [comment]
guys, any timeline? thx!

**Comment by btzsoft** [comment]
@Kilian I did this changes, also added to `moveHelpers` but the same, app is crashing.

**Comment by caesar** [comment]
@Kilian @btzsoft there are many more places in that file where the new helpers need adding. (Ideally it should be refactored to make the code DRYer for so many helpers.)

**Comment by btzsoft** [comment]
@caesar I did it working right now, my mistake was that I haven't included `(GPU)` helper also.
I changed `electronMac.js` directly from `node_modules` until a new release will be here. 
Thx!

**Comment by steverandy** [comment]
@btzsoft can you share the code snippet?

**Comment by Kilian** [comment]
@btzsoft @steverandy Or submit a PR? ;)

**Comment by Evoks** [comment]
PR #4111

**Comment by develar** [comment]
Thanks! 21.2.0 released.

**Comment by gaodeng** [comment]
@develar @Evoks 
I upgraded from Electron5 to 6 (electron-builder to the latest version),  when submitted via the Application Loader, it gives these error:
```
ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (GPU) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (GPU).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(GPU)', which is not a valid bundle identifier." 

ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (Plugin) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (Plugin).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(Plugin)', which is not a valid bundle identifier."

ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (Renderer) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (Renderer).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(Renderer)', which is not a valid bundle identifier."

```

**Comment by caesar** [comment]
I think the issue is caused by these lines:

https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/src/electron/electronMac.ts#L109-L117

**Comment by johannesjo** [comment]
Still an issue for me with 21.2.0.

**Comment by jcc** [comment]
Still an issue for me with 21.2.0.

**Comment by dimitrisnl** [comment]
Happens to me too.

(I know posting a comment doesn't help, but since the thread is locked I wanted to bring some extra attention.)

**Comment by turbidwater** [comment]
Updating electron-builder to 21.2.0 and adding electron-packager did resolve this for me.
`"electron-builder": "^21.2.0",
 "electron-packager": "^14.2.1",`
