### ISSUE TITLE
Can portable app using a random folder to decompress the application

### ISSUE THREAD

**Issue by xalc** [electron-userland/electron-builder#4105]
* **21.1.5**

* **Windows**

Using build script below to build a windows portable app with some extraResources
```json
"build": {
    "productName": "App",
    "extraResources": [
      "./resourFolder/**/*"
    ],
    "files": [
      "!resources/*"
    ],
    "portable": {
      "requestExecutionLevel": "admin"
    },
    "win": {
      "target": "portable",
      "icon": "./src/resources/images/icon.ico",
      "artifactName": "App.exe",
      "publisherName": "App.exe"
    }
  },
```

It will success build the ```App.exe```.
But if the App.exe is large , the decompress will take  long time. At this time, if user trying to double click for relaunch the App, it will throw file not find errors.
![image](https://user-images.githubusercontent.com/18441947/62039503-6ab30b00-b22a-11e9-8385-d257f900c877.png)

After some investigation, we found it caused by ```unpackDirName``` value in exectron-builder source code .
```
defines.UNPACK_DIR_NAME = portableOptions.unpackDirName || (await executeAppBuilder(["ksuid"]))
``` 
in ```NisiTarget.ts```

It used a fixed location to decompress the application. 
User trying to double click several times for relaunch the app, this time some folder may be removed during the decompress process. so the app will throw file not found error.

Can we use a random folder to decompress the application so that the file will not dropped in that case?

**Comment by xalc** [comment]
But do someone  have a work round to fix this?

**Comment by valueerrorx** [comment]
```
"portable":` {                
            "unpackDirName": true
        },
        "win": {
            "icon": "public/icons/icon.ico",
            "target": [
                {
                    "target": "portable",
                    "arch": [
                        "x64"
                    ]
                }
            ],
            "artifactName": "${productName}_${version}.${ext}"
        }
```
just for information and easy use:
unpackdirname: true creates a new tmp folder on every unpack/start of the electron app and fixes that problem..

**Comment by valueerrorx** [comment]
https://github.com/electron-userland/electron-builder/issues/7870

as stated in this issue electron should not behave this way. it should immediately create some sort of lockfile (for the time of the extraction process) in the directory and not allow a second process to unpack into the same directory as long as this lockfile exists.
