### ISSUE TITLE
Linux AppImage & systemIntegration

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#4107]
* **Version**: 21.1.5

* **Target**: AppImage (linux)

Previously I had the linux AppImage target configured with:

```
    "appImage": {
      "systemIntegration": "doNotAsk"
    }
```

However, with recent versions of electron-builder, this produces the error:

```
  ⨯ appImage.systemIntegration is deprecated, https://github.com/TheAssassin/AppImageLauncher is used for desktop integration"
```

I read through the linked page, but it didn't quite explain what exactly has changed or how I can use the *doNotAsk* option.

Any clarification would be appreciated.

**Comment by GhostlyDark** [comment]
From what I understand the option doesn't exist anymore. 

When launching an AppImage built without _systemIntegration_ specified, I do **not** get asked to integrate it. One has to delete `"systemIntegration": "doNotAsk"` in order to get electron-builder working.

**Comment by gaodeng** [comment]
why systemIntegration is removed?

**Comment by magne4000** [comment]
Since this parameter was removed, "Add to favorite" action on Ubuntu adds the favorite to the Dock as it should, but clicking on it does not launch the app. cc @develar

**Comment by gaodeng** [comment]
@bot ?

**Comment by gaodeng** [comment]
?

**Comment by viankakrisna** [comment]
i think the removal of appimage's systemIntegration is premature. until we have AppImageLauncher, AppImageUpdate, or appimaged is included in major linux distribution, the ux of appimages has worsen. previously the user just need the .appimage to install the app, now they also need to install these other software to have a nice ux. Is there any way we could bring back the systemIntegration without downgrading to earlier version?
