### ISSUE TITLE
Mac ZIP folder gets corrupted app (using new notarization process)

### ISSUE THREAD

**Issue by pashvin** [electron-userland/electron-builder#4108]
* **Version**: Electron-builder: 21.1.1

* **Target**: Mac-> DMG,ZIP
Electron version: 5.0.7

Recently we started using new notarization process and it is working for dmg option.
We also have zip format but when I extract app from zip and try to use it , then it is not able to open that app.

**Comment by pashvin** [comment]
![image](https://user-images.githubusercontent.com/36708072/62164430-3fcfc200-b2d1-11e9-9c0b-8d5fcbc4a1db.png)

Error screenshot (after unzip and try to run app)

**Comment by qwertvasilii** [comment]
Have same issue but either with dmg or just app shipped to another mac it stops with same error after run, although on my mac app starting normally. signed, notarized

**Comment by shahan312** [comment]
I have the same issue. The executable file inside the macos folder in the `.app` package doesn't have execute privileges after unzipping.

**Comment by pashvin** [comment]
Any fix available yet?

**Comment by pashvin** [comment]
Please fix this issue as it is 100% reproducible and annoying.

**Comment by pashvin** [comment]
Duplicate of https://github.com/electron-userland/electron-builder/issues/4299

**Comment by leohxj** [comment]
any solution?
