### ISSUE TITLE
Can't start app installed from DMG (using electron 6.0.0)

### ISSUE THREAD

**Issue by pashvin** [electron-userland/electron-builder#4109]
* **Version**: Electron version: 2.1.5

* **Target**: Mac->DMG . This is electron version 6.0.0 which is very new.

I can start electron 6.0.0 stand alone app but when I build DMG and install app, it does not start

**Comment by qwertvasilii** [comment]
same issue

**Comment by qwertvasilii** [comment]
seems to be related to https://github.com/electron/electron/issues/19511

**Comment by pashvin** [comment]
Thanks and totally understand as Electron 6.0 just released so not every thing will be ready on day one.
I will wait for the fix.

**Comment by pashvin** [comment]
Closing as duplicate as follow the original issue.
