### ISSUE TITLE
Missing .dll files on Windows when building on OSX

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#411]
I'm using electron-builder to package my Electron app and running into issues in the Windows distributable (in both x64 and ia32 arch). I am working on OSX El Capitan 10.11.2

I receive the following output when building: `build --platform win32`

```
Skip app dependencies rebuild because platform is different
Packaging app for platform win32 x64 using electron v1.1.0
```

The packaging step itself seems to complete successfully and I am able to access my release folder via a shared network drive in VirtualBox.

I'm using the following build of Microsoft Edge on Win 10 Stable:
![image](https://cloud.githubusercontent.com/assets/99392/15296614/18a361da-1b64-11e6-891a-38a78c788eb6.png)

When I attempt to open the `*Setup.0.0.1.exe` file on the Windows Machine, I see the following error almost immediately:

![image](https://cloud.githubusercontent.com/assets/99392/15296661/5da8a95c-1b64-11e6-86ff-a253048cc87f.png)

Clicking OK, I receive another:

![image](https://cloud.githubusercontent.com/assets/99392/15296702/8c946a6c-1b64-11e6-89d6-a52da5623d89.png)
  
There seems to be a related issue [here](https://github.com/electron/electron/issues/5528) but from the build output, it seems that I'm using the most up to date version of electron (1.1.0).

Any advice or a point in the right direction would be greatly appreciated. Please let me know if there is any more information I can provide.

Thanks!

**Comment by matjaz** [comment]
1.1.0 does not include electron/electron#5538 fix

**Comment by develar** [comment]
Closed as 3rd-party issue.
