### ISSUE TITLE
Restarting packaged app not working

### ISSUE THREAD

**Issue by M0rious** [electron-userland/electron-builder#4110]
* **Version**: 
21.1.5

* **Target**: 
Windows 10

My application restarts using
```typescript
    app.relaunch();
    app.quit();
```
This works fine if run from source or packaged using electron-packager.
If the app runs from a single .exe file build by electron-builder, it just exits the application without restarting.
Any hints on how to fix this?
Thanks!

**Comment by M0rious** [comment]
We have posted a 300$ bounty at [Bountysource](https://www.bountysource.com/issues/78012564-restarting-packaged-app-not-working) for this issue!
@develar

**Comment by hwoodiwiss** [comment]
Are you able to provide some more context around the issue? I'm unable to reproduce this. Even just providing your package.json would be helpful.

**Comment by M0rious** [comment]
Sure, I have uploaded a demo application that reproduces the issue for me:
[Demo-Repo](https://github.com/M0rious/electron-builder-restart-demo)

To run
`npm install`
`npm run package-win-portable`

go to portable directory and run demo 1.3.0.exe.

To trigger the restart, open the "DEV" Menu and select "Neustart".

For me, this closes the application but does not start it back up - as described above.

**Comment by hwoodiwiss** [comment]
The packaged app is stored as an NSIS archive, so the demo app is running from temp.

If you replace your code with the below, it should resolve your issue:

`                    var opt: Electron.RelaunchOptions = {};
                    opt.args = process.argv.slice(1).concat(['--relaunch']);
                    opt.execPath = process.execPath;
                    if(app.isPackaged && process.env.PORTABLE_EXECUTABLE_FILE != undefined)
                    {
                        opt.execPath = process.env.PORTABLE_EXECUTABLE_FILE;
                    }
                    app.relaunch(opt);
                    app.quit();
`

**Comment by M0rious** [comment]
You are correct, this seems to work - great, thanks!

**Comment by Araxeus** [comment]
for anyone that still encouter this problem like me:
```js
function restart() {
    app.relaunch({ execPath: process.env.PORTABLE_EXECUTABLE_FILE });
    app.quit();
}
```
execPath will be undefined if not in portable app resulting in the default behavior
