### ISSUE TITLE
Multiplatform Build Documentation is lacking. I can fix!

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#412]
I can issue a PR but I need to understand it first.

What I'd like to do (and [seems possible from documentation](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build)) is build OSX and Windows files from OSX (no MSI). 

The documentation linked (https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build) says it's possible but I'd like to add the actual commands to this page if you could point me in the right direction.

Once I figure it out I'll issue a PR. Thanks!

**Comment by develar** [comment]
> if you could point me in the right direction.

Edit file https://github.com/electron-userland/electron-builder/blob/master/docs/Multi%20Platform%20Build.md (see https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation)

> I'd like to add the actual commands to this page

If it can be somehow simplified (since we are smart tool), it should be done. Anyway, please open PR and it will be discussed.

**Comment by framerate** [comment]
@develar That's the page I'm referring to. There is no real directions i can see.

The directions are "install these two apps in homebrew". But then what? I've scoured the issue tracker and seen you can pass `--platform` and `--arch` commands but that doesn't seem to work. That's the missing step I want to add.

The *assumption* by me, the user of the documentation, is that I install those through `brew` and then `npm run dist` and OSX and Windows should just magically build for me! ([according to this](https://github.com/electron-userland/electron-builder#in-short)). But whatever the missing command line flag is to make Windows build on OSX seems to be missing :(

**Comment by develar** [comment]
> --platform and --arch commands but that doesn't seem to work

It works. Yes, this should be documented.

**Comment by framerate** [comment]
Are those pass-throughs to electron-packager or anything that I can see the list of valid commands?

**Comment by develar** [comment]
> I can see the list of valid commands?

https://github.com/electron-userland/electron-builder#cli-usage

Just pass these args in your script task. `"dist-win": "build --platform=win32"`

**Comment by framerate** [comment]
Great. And is it not possible to create the update files (`RELEASES, project.nupkg, project.exe`) for Windows while using OSX?

**Comment by framerate** [comment]
Thanks I got it, I'll try and clean up the documentation tomorrow to make it clearer!

**Comment by develar** [comment]
> is it not possible to create the update files (RELEASES, project.nupkg, project.exe) for Windows while using OSX?

Possible. Just install required tools (as stated in the docs). FYI: docker support is coming

**Comment by ghego1** [comment]
> Just pass these args in your script task. "dist-win": "build --platform=win32"
This should definitely be in the docs! :-)

**Comment by develar** [comment]
> This should definitely be in the docs! :-)

`--win` :)
