### ISSUE TITLE
libappindicator1 dependency conflict in Ubuntu 18

### ISSUE THREAD

**Issue by FyreDemonyte** [electron-userland/electron-builder#4120]
* **Version**: 20.39.0

* **Target**: 
  • packaging       platform=linux arch=x64 electron=4.1.1 appOutDir=app-builds/linux-unpacked
  • building        target=tar.gz arch=x64 file=app-builds/Stratis Core-v1.2.1-linux-x64.tar.gz
  • building        target=deb arch=x64 file=app-builds/Stratis Core-v1.2.1-linux-amd64.deb

Referencing issue:
https://github.com/stratisproject/StratisCore/issues/262

Problem:
Ubuntu 18 already has a default packages installed 
```
ii  libappindicator3-1                                          12.10.1+18.04.20180322.1-0ubuntu1           amd64        Application Indicators
ii  libindicator3-7                                             16.10.0+18.04.20180321.1-0ubuntu1           amd64        panel indicator applet - shared library

```
app-builder-lib linux deps uses libappindicator1 and libindicator7 (which are ubuntu 16) dependencies.

Thus electron-builder would need to setup its package deps per linux distro's specific packages, not as a one package fits all.

**Comment by D3m0nKingx** [comment]
```bash
sudo dpkg -i 'Stratis Core-v1.2.1-linux-amd64.deb'
(Reading database ... 224381 files and directories currently installed.)
Preparing to unpack Stratis Core-v1.2.1-linux-amd64.deb ...
Unpacking stratis-core (1.2.1) over (1.2.1) ...
dpkg: dependency problems prevent configuration of stratis-core:
 stratis-core depends on libappindicator1; however:
  Package libappindicator1 is not installed.
```

**Comment by D3m0nKingx** [comment]
installing libappindicator1 on ubuntu 18 creates a situation where the system tray icons change over to a "x" indicating as if the icons are "missing", but this is rather conflict of having libappindicator installed  running side-by-side with libappindicator3-7. 

Ubuntu 18 doesn't flag this as an issue having both packages installed at the same time even so it causes issues.

**Comment by D3m0nKingx** [comment]
**libappindicator1** referenced file locations:

node_modules/app-builder-lib/scheme.json https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/scheme.json#L496

node_modules/app-builder-lib/out/options/linuxOptions.d.ts https://github.com/electron-userland/electron-builder/blob/68ffd54aca4dc65f3f932a6580d744ae656ecbaf/packages/app-builder-lib/src/options/linuxOptions.ts#L106

node_modules/app-builder-lib/out/targets/fpm.js

node_modules/app-builder-lib/out/targets/fpm.js.map

node_modules/app-builder-lib/out/targets/snap.js

node_modules/app-builder-lib/out/targets/snap.js.map

**Comment by FyreDemonyte** [comment]
Pinging so issue doesn't go to the ignore bin. Hopefully someone takes a look at this, need this issue addressed since it's occuring in https://github.com/stratisproject/StratisCore/issues/262.
