### ISSUE TITLE
How to create an exe file from win-unpacked folder

### ISSUE THREAD

**Issue by Tinysymphony** [electron-userland/electron-builder#4121]
Version: 20.44.4
Target: Windows

The win-unpacked folder is created every time I run electron-builder. I want to know how to create the exe file directly from the win-unpacked folder so I can modify the built files before packing.

**Comment by fiefdx** [comment]
@Tinysymphony Try this: #4132 , it should be similar, I just figure out how to separate the package sequence on ubuntu linux.

**Comment by Tinysymphony** [comment]
@fiefdx It works for me. Thanks.

**Comment by Julia-Houng** [comment]
请给我写一份附上报价表的邮件回复
