### ISSUE TITLE
NSIS uninstaller now has two entries in windows registry

### ISSUE THREAD

**Issue by shnassar** [electron-userland/electron-builder#4126]
* **Version**:  21.2.0
electron-updater: 4.1.2

* **Target**: nsis

With the changes in https://github.com/electron-userland/electron-builder/pull/4069 I'm now seeing the previous version's entry in the uninstall list after an update. Inspected my windows registry and am seeing two entries for the app - the new one with `{}` and the old one without.

**Comment by jeremyspiegel** [comment]
Looks like a duplicate of https://github.com/electron-userland/electron-builder/issues/4092.

**Comment by shnassar** [comment]
Closing in favor of https://github.com/electron-userland/electron-builder/issues/4092
