### ISSUE TITLE
Proton Native run dist problem-windows

### ISSUE THREAD

**Issue by frankgo81** [electron-userland/electron-builder#4133]
I am using electron builder to run the default Proton native example, however, I've run into this error:

$ npm run dist

> test-proton-app-2@0.0.1 dist E:\github\test-proton-app-2
> electron-builder

  • electron-builder  version=21.2.0 os=10.0.18362
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-proton-app-2@0.0.1 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-proton-app-2@0.0.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frank guo\AppData\Roaming\npm-cache\_logs\2019-08-08T08_20_42_548Z-debug.log

**Comment by frankgo81** [comment]
The Package.json file:


{
  "name": "test-proton-app-2",
  "version": "0.0.1",
  "description": "A minimal Electron application",
  "author": "sssd",
  "private": true,
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "dependencies": {
    "proton-native": "latest"
  },
  "devDependencies": {
    "electron-builder": "latest",
    "babel-cli": "latest",
    "babel-preset-env": "latest",
    "babel-preset-stage-0": "latest",
    "babel-preset-react": "latest"
  }
  
}

**Comment by miguelyoobic95** [comment]
Facing a similar issue here, all packages seem to be installed correctly ....

**Comment by lengchu** [comment]
electron-builder currently does not support windows for packaging Proton Native app

> https://www.electron.build/configuration/configuration#proton-native

**Comment by miguelyoobic95** [comment]
@lengchu while the above is true, I am getting that error in a non-Proton Native app and downgrading the electron-builder version fixes the problem entirely. Seems like an issue somewhere else to me :)

**Comment by lengchu** [comment]
@miguelyoobic95 this [issue](https://github.com/electron-userland/electron-builder/issues/3984) may be helpful to you

**Comment by vrpratheep22** [comment]
Just install electron 

npm install electron --save-dev

**Comment by miguelyoobic95** [comment]
@lengchu cheers for pointing that out, I have been using the `--c.electronVersion` but will investigate where the case is the same, we have upgraded to electron 7.0.0 so maybe it does not have the problem anymore.

Using the above flag is an acceptable workaround for the time being though.
