### ISSUE TITLE
Symlinks not created for MacOS

### ISSUE THREAD

**Issue by mvid-servoy** [electron-userland/electron-builder#4135]
* **Version**: 21.2.9

* **Target**: MacOS

After upgrading to the latest libs and building my app, tar.gz target does not contain the symlinks for the Frameworks (Electron, Mantle, ReactiveCocoa, Squirrel). The dmg target has no problem
When extracting the app from that tar.gz, and launching the following error occurs:

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Downloads/servoyngdesktop.app/Contents/MacOS/servoyngdesktop
  Reason: no suitable image found.  Did find:
	/Users/marian/Downloads/servoyngdesktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/marian/Downloads/servoyngdesktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Data used:

package.json:
{
  "name": "ServoyElectronCLI",
  "asar": "false",
  "productName": "ServoyElectronCLI",
  "version": "1.0.0",
  "description": "Servoy Electron Command Line Interface",
  "main": "app/src/main.js",
  "scripts": {
    "pack": "electron-builder --dir -w",
    "distw": "electron-builder -w",
    "distl": "electron-builder -l",
    "distm": "electron-builder -m",
    "distwl": "electron-builder -ml",
    "distml": "electron-builder -ml",
    "distmw": "electron-builder -mw",
    "distmwl": "electron-builder -mwl",
    "distw32": "electron-builder -w --ia32",
    "postinstall": "electron-builder install-app-deps"
  },
  "bin": {
    "electron": "lib/cli.js"
  },
  "author": "Servoy",
  "license": "ISC",
  "dependencies": {
    "builder-util": "^21.1.6"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/Servoy/electron.git"
  },
  "devDependencies": {
    "electron": "6.0.0",
    "electron-builder": "^21.2.0",
    "electron-rebuild": "^1.8.5",
    "node-gyp": "^5.0.3"
  }
}

Electron-builder.yml:
productName: "servoyngdesktop"
appId: "servoy.client.ng-desktop"
buildVersion: "2019.09"
artifactName: "${productName}-${buildVersion}.${ext}"

`#` Package electron code into a asar archive. Set to false to debug issues.
asar: true
buildDependenciesFromSource: false
npmRebuild: false
electronCompile: false
nodeVersion : 12.4.0
nodeGypRebuild: false
remoteBuild: false
asarUnpack: "./config/servoy.json"

`#` Mac OS configuration
mac:
  icon: "resources/icons/servoy_logo.png"
  artifactName: "servoyngdesktop-${buildVersion}-mac.${ext}"
  target: “tar.gz”

`#` Config for OSX dmg
dmg:
  artifactName: "servoyngdesktop-${buildVersion}-mac.${ext}"
  contents:
    - x: 130
      y: 220
    - x: 410
      y: 220
      type: "link"
      path: "/Applications"

`#` Windows configuration
win:
  icon: "resources/icons/servoy_logo.png"
  artifactName: "servoyngdesktop-${buildVersion}-win.${ext}"
  target:
    - "tar.gz"

`#` Config for the windows installer
nsis:
  oneClick: true
  perMachine: true
  allowToChangeInstallationDirectory: false

`#` Linux configuration
linux:
  maintainer: “mvid@servoy.com"
  executableName: "servoyngdesktop"
  artifactName: "servoyngdesktop-${buildVersion}-linux.${ext}"
  category: Development
  target:
    - "tar.gz"

directories:
  buildResources: "."
  output : "./target"

Console output:

Vids-MacBook-Pro:electron-builder marian$ electron-builder -m
  • electron-builder  version=21.2.0 os=18.6.0
  • loaded configuration  file=/Users/marian/git/electron-builder/electron-builder.yml
  • writing effective config  file=target/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=6.0.0 appOutDir=target/mac
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                1) 9F4A4BC5E0BFA0C8A25F8FBBDFE40145BA4A7E44 "member: 59550EAD-85B7-4B29-B415-2DBDCCCEACCD FE889C88-8816-487C-9EFE-4ECB313C1773" (CSSMERR_TP_NOT_TRUSTED)
                                                   1 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=macOS tar.gz arch=x64 file=target/servoyngdesktop-2019.09-mac.tar.gz
Vids-MacBook-Pro:electron-builder marian$ 

Note that manually making the tar from the mac output dir itself through the command line fix the problem:
 tar -czvf servoyngdesktop-2019.06-mac.tar.gz servoyngdesktop.app

This manually created tar.gz is working fine. I'm expecting to get the same tar.gz from electron-builder.

On Windows/Linux I have no problem.
Please advice ...!

**Comment by jcompagner** [comment]
Shouldn't this case be looked at?
i think the fix shouldn't be that hard right? It is just weird that the tar files are just in a wrong state
