### ISSUE TITLE
Mas build temporary file crash and sandbox failing

### ISSUE THREAD

**Issue by florianperrot44** [electron-userland/electron-builder#4137]
Electron builder version 21.2.0

**Error is :**
_signing         file=dist/mas/DS Link.app identityName=3rd Party Mac Developer Application: Distribution Service (Z6LWQ664YM) identityHash=345ADF3FAC6A3100845B88213CB1DD73C9276F4C provisioningProfile=embedded.provisionprofile
(node:41674) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
  ⨯ ENOENT: no such file or directory, unlink '/var/folders/z5/rxk9rrsd3p7gjk7x3gmpw1n80000gn/T/c4268fc22b00dab5be25354ae494f3b70fa01b40.plist'  stackTrace=
                                                                                                                                                   Error: ENOENT: no such file or directory, unlink '/var/folders/z5/rxk9rrsd3p7gjk7x3gmpw1n80000gn/T/c4268fc22b00dab5be25354ae494f3b70fa01b40.plist'_

pkg file is generated in dist/mas directory but when i push the app to Application Uploader, Apple says me that some files are not Sandboxed (My app helper, app login helper and other).

**entitelments.mas.plist  :**  
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>com.apple.security.app-sandbox</key>
<true/>
<key>com.apple.security.files.user-selected.read-only</key>
<true/>
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
</dict>
</plist>

**package.json**
{
  "name": "ds-link-app",
  "productName": "DS Link",
  "version": "1.0.0",
  "description": "DS Link application",
  "main": "main.js",
  "bin": "cli.js",
  "scripts": {
    "dev": "electron . --debug",
    "test": "mocha && standard",
    "postinstall": "electron-builder install-app-deps",
    "start": "yarn install && electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "release": "electron-builder",
    "publish": "GH_TOKEN=. build -p always",
    "preparemac": "cp node_modules/app-builder-lib/out/electron/electronMac.js build/electronMac.original.js",
    "package:standalone": "CSC_KEY_PASSWORD=xxx CSC_LINK=./build/certificats-mac-dsdownloader.p12 electron-builder",
    "package:app-store":  "CSC_KEY_PASSWORD=xxx CSC_LINK=./build/certificats-mac-dsdownloader.p12 electron-builder"
  },
  "repository": "https://github.com/florianperrot44/ds-dcp-downloader",
  "keywords": [
    "Electron",
    "API",
    "demo"
  ],
  "build": {
    "appId": "com.electron.ds.link",
    "compression": "normal",
    "files": [
      "**/*",
      "!**/node_modules/electron",
      "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
      "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
      "!**/node_modules/*.d.ts",
      "!**/node_modules/.bin",
      "!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}",
      "!.editorconfig",
      "!**/._*",
      "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}",
      "!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}",
      "!**/{appveyor.yml,.travis.yml,circle.yml}",
      "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}"
    ],
    "mac": {
      "category": "public.app-category.productivity",
      "icon": "assets/app-icon/mac/ds.icns",
      "entitlements": "build/entitlements.mac.plist",
      "extendInfo": {
        "CFBundleDevelopmentRegion":"fr-FR"
      },
      "target": [
          "dmg",
          "mas"
      ],
      "provisioningProfile" : "embedded.provisionprofile"
    },
    "mas": {
        "entitlements": "build/entitlements.mas.plist",
        "type": "distribution",
        "category": "public.app-category.productivity"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]"icon": "assets/app-icon/win/ds.ico"
    },
    "nsis": {
      "createDesktopShortcut": "always",
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "assets/app-icon/win/ds.ico",
      "uninstallerIcon": "assets/app-icon/win/ds.ico",
      "allowElevation": true
    },
    "dmg": {
      "icon": "assets/app-icon/mac/ds.png.icns",
      "contents": [
        {
          "x": 110,
          "y": 220
        },
        {
          "x": 400,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    }
  },
  "author": "GitHub",
  "license": "MIT",
  "devDependencies": {
    "@octokit/rest": "^16.25.2",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "check-for-leaks": "^1.2.0",
    "devtron": "^1.4.0",
    "electron": "^5.0.1",
    "electron-builder": "^21.2.0",
    "electron-rebuild": "^1.8.4",
    "highlight.js": "^9.3.0",
    "husky": "^0.14.3",
    "mocha": "^5.2.0",
    "npm-run-all": "^4.0.2",
    "rimraf": "^2.5.2",
    "signcode": "^1.0.0",
    "spectron": "^5.0.0",
    "standard": "^12.0.1"
  },
  "dependencies": {
    "check-internet-connected": "^2.0.1",
    "datatables.net-bs4": "^1.10.19",
    "dateformat": "^3.0.3",
    "datepicker-bootstrap": "^1.9.13",
    "diskusage": "^1.1.1",
    "electron-download-manager": "^2.3.0",
    "electron-log": "^3.0.5",
    "electron-settings": "^3.2.0",
    "electron-shortcut-normalizer": "^1.0.0",
    "electron-store": "^3.2.0",
    "electron-updater": "^4.0.6",
    "extract-zip": "^1.6.7",
    "file-size-tree-js": "^1.0.2",
    "glob": "^7.1.3",
    "i18next": "^15.1.0",
    "i18next-node-fs-backend": "^2.1.3",
    "jquery": "^3.4.1",
    "jquery-i18next": "^1.2.1",
    "nodemailer": "^6.2.1",
    "request": "^2.88.0",
    "sax": "^1.2.4"
  },
  "standard": {
    "env": {
      "mocha": true
    }
  }
}

**Comment by florianperrot44** [comment]
SandBox failing in appstore validation is resolved.
I added entitelments.inherited.properties in build folder and all went ok in validation step.

App was sent to Cupertino labs...but few hours after i received a mail with a rejection and logs.
The binary signature is bad.

This is caused by  electron-osx-sign (see the first error up) that can't delete (unlink) a temporary file. Probably the provisionning profile plist file (imported from apple website)

I managed only one time to build my app without this error...but i miss to change version number of my app.. arghh.
Now i have always the same error in building :

ENOENT: no such file or directory, unlink '/var/folders/z5/rxk9rrsd3p7gjk7x3gmpw1n80000gn/T/c4268fc22b00dab5be25354ae494f3b70fa01b40.plist'

I have reinstalled a fresh copy, updated yarn, clean yarn cache, deleted nodes, reinstalled all, downgraded electron-build....nothing changed

Any one to help me ?
Thanks.

**Comment by alibosworth** [comment]
I believe you might be seeing the same issue as we are having here: https://github.com/electron-userland/electron-builder/issues/4098

**Comment by johannesjo** [comment]
I had to delete all caches for electron under `~/Library/Caches/electron` than it started working again.

**Comment by dabeku** [comment]
+1 Same issue here
