### ISSUE TITLE
Ask user to confirm if he wants to delete AppData (quick solution with sample NSIS script)

### ISSUE THREAD

**Issue by samuelcarreira** [electron-userland/electron-builder#4141]
* **Version**:  21.2.0

* **Target**: Windows NSIS target

Sometimes I want to update my app and keep the AppData extra files (which stores the JSON config file and the logs) and in other occasions, I want to completely uninstall my app and remove all the files.
I am aware of this option [nsis.deleteAppDataOnUninstall](https://github.com/electron-userland/electron-builder/issues/885) but I don't want to always delete the AppData files on uninstall, so **I think you should add a message box to ask for the user choice when he manually uninstalls the app**.

My temporary solution is to add a custom NSIS script with that instructions. On the manual uninstall process appears a message box and the user can choose to delete or not the AppData folder.  When the installer run as silent (update or install over a previous installation), the message box doesn't appear (I used the /SD command).
_Note: I migrated from the InnoSetup to NSIS because of the auto-update feature included in the electron-builder, so that's my first NSIS script. Beware of any bugs._

### Instructions:
1- Create the file  **./build/uninstaller.nsh**
2- Insert the following code
```
!macro customUnInstall
  MessageBox MB_YESNO "Delete app config and log folder?" \
    /SD IDNO IDNO Skipped IDYES Accepted

  Accepted:
    RMDir /r "$APPDATA\${APP_FILENAME}"
    !ifdef APP_PRODUCT_FILENAME
      RMDir /r "$APPDATA\${APP_PRODUCT_FILENAME}"
    !endif
    Goto done
  Skipped:
    Goto done
  done:
!macroend
```
3- add the following line to the **electron-builder.json** file (or in build key of **package.json**)
```
"nsis": {
   ...  
   "include": "build/uninstaller.nsh"
}
```

**Comment by BHuys** [comment]
@samuelcarreira , thank you for this solution, I'm having a simular use-case. I'm just wondering how you store your local data? My nsis APPDATA path is different from my electron app.getPath('appData') so my uninstaller tries to remove the wrong directory.

APPDATA : c:\\programData\{appname}
electron appData is 'c:\\users\{user}\appData\roaming\{appname}

**Comment by Puneetkumarpal** [comment]
hello i want to ask password on app uninstall can you help me!

**Comment by lucasrabiec** [comment]
> @samuelcarreira , thank you for this solution, I'm having a simular use-case. I'm just wondering how you store your local data? My nsis APPDATA path is different from my electron app.getPath('appData') so my uninstaller tries to remove the wrong directory.
> 
> APPDATA : c:\programData{appname} electron appData is 'c:\users{user}\appData\roaming{appname}

@BHuys you need to set `SetShellVarContext current` at the beginning of macro:
```nsh
!macro customUnInstall
  SetShellVarContext current
  MessageBox MB_YESNO "Delete app config and log folder?" \
    /SD IDNO IDNO Skipped IDYES Accepted

  Accepted:
  [...]
```
