### ISSUE TITLE
at least snapcraft 3.1.0 is required, but snapcraft, version edge

### ISSUE THREAD

**Issue by gengjiawen** [electron-userland/electron-builder#4142]
* **Version**: 
Repro: https://github.com/gengjiawen/electron-devdocs
```
Docker: electronuserland/builder:wine-chrome
electron-builder  version=21.2.0 os=4.15.0-1043-aws
```
Full log: https://circleci.com/gh/gengjiawen/electron-devdocs/2#tests/containers/0.
snap file not generated too.

* **Target**: 
```json
      "target": [
        "AppImage",
        "snap",
        "deb"
      ]
```

**Comment by johannesjo** [comment]
Same issue here. Started appearing "randomly" for travis.

**Comment by raymondjacobson** [comment]
same issue here

**Comment by solid-studio** [comment]
same issue

**Comment by kontrollanten** [comment]
https://github.com/electron-userland/electron-builder/issues/3549#issuecomment-515801468 works as  a workaround for me.

**Comment by yvesh** [comment]
same issue here

**Comment by gengjiawen** [comment]
not stale.
