### ISSUE TITLE
Electron updater not success and restart when use app.on('window-all-closed')

### ISSUE THREAD

**Issue by purocean** [electron-userland/electron-builder#4143]
* **Version**: 
```
    "electron-updater": "^4.1.2",
    "electron": "^6.0.0",
    "electron-builder": "^21.2.0",
```

* **Target**: 
Windows 10

I write code 

```js
app.on('window-all-closed', () => {
    // do nothing. prevent exit.
})
```

Check update. Update Progress half and exit. No log output. Just installer programmer exit.

And I remove `app.on('window-all-closed')`
It is works fine.

**Comment by cegonzalv** [comment]
I'm having the same problem...

**Comment by purocean** [comment]
@cegonzalv 
Temporary solution:
```
autoUpdater.quitAndInstall()
app.exit()
```

**Comment by upjersdave** [comment]
Experiencing the same problem here on Windows 64bit.

Update gets downloaded => `autoUpdater.quitAndInstall()` => Installer starts and dies without an error message half way though.

If I run the installer exe direct from the `pending` folder in `APPDATA`, the update works fine, so the installer files are fine, but there seems to be a problem when updating _while_ the electron app is running.

I have tried the various suggestions; removing window-all-closed and adding `app.exit()` but every time the installer continues to die half way through.

Any ideas?

**Comment by cegonzalv** [comment]
Same problem here... Tried both solutions without any success.

Ended up going back to electron-builder version 20.44.4

**Comment by VladSanko** [comment]
Hi. @upjersdave, Same problem. Did you solve this issue ?

**Comment by mkinoshi** [comment]
We are having the same issue on the following versions too
"electron-updater": "4.2.2",
"electron": "7.1.8",
"electron-builder": "22.2.0",

**Comment by jmit-modern** [comment]
> @cegonzalv
> Temporary solution:
> 
> ```
> autoUpdater.quitAndInstall()
> app.exit()
> ```

After all it's working!
