### ISSUE TITLE
macOS error with null identity

### ISSUE THREAD

**Issue by ofekashery** [electron-userland/electron-builder#4144]
* **Version**: 21.2.0

* **Target**: macOS

```
Error: Application entry file "dist/electron/main.js" in the ".../launcher/dist/mac/FIRST LEGO League TMS.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
```

Mac configuration
```json
"mac": {
  "category": "public.app-category.education",
  "target": "dir",
  "identity": null
}
```

It works without the ``identity``.

**Comment by alibosworth** [comment]
@ofekashery I haven't used "identity" before, but if it works without defining any identity, have you considered leaving it out? The docs suggest not using this option, maybe it isn't the best option:

> Consider using environment variables CSC_LINK or CSC_NAME instead of specifying this option

Also I noticed your target is a "dir", which is an unpackaged directory of files (only for testing), I feel like it is maybe incompatible with "identity", which is for signing? (You can't sign an unpackaged directory!)
