### ISSUE TITLE
Invalid Bundle Identifier Electron Helper (GPU, Plugin, and Renderer) Mac App Store

### ISSUE THREAD

**Issue by dimitarnestorov** [electron-userland/electron-builder#4151]
* **Version**: 21.2.0
* **Target**: macOS App Store
* **Electron Version**: 6.0.1

Couldn't find a duplicate of my issue which I feel is odd. Can anyone confirm  Electron 6+ on the App Store using electron-builder?

![image](https://user-images.githubusercontent.com/8790386/62866022-91883b80-bd18-11e9-84f8-2f6055e5a0f2.png)

Pretty sure the problem is the brackets, I believe the uppercase letters isn't.

**Comment by gaodeng** [comment]
related https://github.com/electron-userland/electron-builder/issues/4104

**Comment by gaodeng** [comment]
workaround - change node_modules/app-builder-lib/out/electron/electronMac.js line 178
to 
```
helper.CFBundleIdentifier = `${helperBundleIdentifier}.${postfix.replace(/[^a-z0-9]/gim,"")}`;

```

**Comment by dangeredwolf** [comment]
I had the same issue, thankfully @gaodeng's solution seems to have worked.
