### ISSUE TITLE
app crashes on start when signing helper apps (gpu, renderer, plugin)

### ISSUE THREAD

**Issue by DanielLeberle** [electron-userland/electron-builder#4155]
* **Version**: 
electron-builder version: 21.0.2
electron version: 6.0.1
* **Target**: Mac OS 

Hi everyone,

I followed this tutorial to create and sign my app:
https://electronjs.org/docs/tutorial/mac-app-store-submission-guide

I build the app with the following line:
```
electron-packager . --appname=myApp --app-bundle-id=myapp.bundle.id --electron-version=6.0.1 --overwrite --platform=mas --arch=x64 --icon=resources/Icon.icns --prune --out=mas-build --ignore --app-version=1.0.0 --build-version=10 --ignore=.+.o$
```

The tutorial however does not provide any information about whether signing the helper apps or not, so I tried the following:
1. Signing all 3 additional helper apps the same way as the default helper app. But after signing the app won't start anymore. Application loader accepts the binary and shows no error on upload.

Codesign verify output in this case:
```
--prepared:.../myApp.app/Contents/Library/LoginItems/myApp Login Helper.app    
--validated:.../myApp.app/Contents/Library/LoginItems/myApp Login Helper.app    
--prepared:.../myApp.app/Contents/Frameworks/myApp Helper (GPU).app    
--validated:.../myApp.app/Contents/Frameworks/myApp Helper (GPU).app    
--prepared:.../myApp.app/Contents/Frameworks/myApp Helper (Renderer).app    
--validated:.../myApp.app/Contents/Frameworks/myApp Helper (Renderer).app    
--prepared:.../myApp.app/Contents/Frameworks/myApp Helper.app    
--validated:.../myApp.app/Contents/Frameworks/myApp Helper.app    
--prepared:.../myApp.app/Contents/Frameworks/myApp Helper (Plugin).app    
--validated:.../myApp.app/Contents/Frameworks/myApp Helper (Plugin).app    
--prepared:.../myApp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.    
--validated:.../myApp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.     
.../myApp.app: valid on disk      
.../myApp.app: satisfies its Designated Requirement
```

2. Not signing the 3 additional helper apps. Now the main app starts but when I try to upload the app via application loader, I  get the error that the sandbox entitlement is missing for the helper apps (which makes sense since I did not codesign the apps with any additional entitlements).

Codesign verify output in this case:
```
.../myApp.app: code object is not signed at all       
In architecture: x86_64
```

So I guess I have to codesign the helper apps, but with what entitlements in the plist?
Or is it possible to add the sandbox entitlement somehow else?

Thanks for your help!

**Comment by alibosworth** [comment]
@DanielLeberle I can't help exactly, But I noticed you are running `electron-packager` on the CLI but you've opened an issue on `electron-builder`?

**Comment by DanielLeberle** [comment]
@alibosworth thanks for your reply. you are absolutely right, my issue does not really concern electron-builder. I will try to find a better place to post my problem
