### ISSUE TITLE
electron-builder strictly ignoring my excludes

### ISSUE THREAD

**Issue by gencer** [electron-userland/electron-builder#4156]
* **Version**: v21.2.0
* **Target**: Windows x64

This is part of build section on my `package.json`:
```json
  "build": {
    "productName": "ElectronReact",
    "appId": "org.develar.ElectronReact",
    "artifactName": "${productName}_setup.${ext}",
    "files": [
      "dist/",
      "main.js",
      "package.json",
      "!node_modules/*",
      "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}",
      "!**/*.{map}"
    ],
```

As you can see I excluded map files (sourcemaps) by last element of `files` using `!**/*.{map}` pattern. However, electron-builder still includes them in asar package.

How can I exclude sourcemaps when packaging it via asar? Sourcemaps already uploaded to remote server while production build therefore, no need to install on clients device.

**Comment by alibosworth** [comment]
@gencer I'm afraid I don't have any experience using the files array, in fact I didn't eve know about it until I glanced upon your report, however were you able to confirm that `npm pack --dry-run` correctly avoids listing the sourcemaps? That'll help narrow down the issue.

**Comment by bartoszhernas** [comment]
I am having exactly the same issue. I tried different settings and somehow map files are not being excluded.

**Comment by bartoszhernas** [comment]
Moving `mac.files` (and windows and linux ones) configuration to main `files` configuration solved the issue
