### ISSUE TITLE
Error building msi on linux

### ISSUE THREAD

**Issue by andrewluka** [electron-userland/electron-builder#4158]
* **Version**: electron-builder version: 21.2.0

* **Target**: Windows MSI
OS: Ubuntu Linux

I am trying to build a Windows msi installer on linux by using Wine.
When I try to build the msi, I get this error from the console:
<pre>
  • electron-builder  version=21.2.0 os=5.0.0-23-generic
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=6.0.2 appOutDir=dist/win-unpacked
  • building        target=MSI arch=x64 file=dist/App.msi
  ⨯ cannot execute  cause=exit status 103
                    out=WiX Toolset Linker version 
Copyright (c) .NET Foundation and contributors. All rights reserved.

Updating file information.

                    errorOut=Z:\home\user\Desktop\appname\dist\__msi-x64\project.wxs(146) : error LGHT0103 : The system cannot find the file 'Z:\home\user\Desktop\appname\dist\win-unpacked\resources\app.asar.unpacked\node_modules\node-notifier\vendor\terminal-notifier-LICENSE'.
    
                    command=wine 'Z:\home\user\.cache\electron-builder\wix\wix-4.0.0.5512.2\light.exe' -out 'Z:\home\user\Desktop\appname\dist\App.msi' -v -spdb -sw1076 '-dappDir=Z:\home\user\Desktop\appname\dist\win-unpacked' -pedantic -wx -sval project.wixobj
                    workingDir=
npm ERR! code ELIFECYCLE
</pre>

I think it complains about a file being not found, but when I browse my filesystem, the file seems to be present.

**Comment by alibosworth** [comment]
Hi @andrewluka I don't know anything about building for Linux, however if you run the command directly, do you get an error?

`wine 'Z:\home\user\.cache\electron-builder\wix\wix-4.0.0.5512.2\light.exe' -out 'Z:\home\user\Desktop\appname\dist\App.msi' -v -spdb -sw1076 '-dappDir=Z:\home\user\Desktop\appname\dist\win-unpacked' -pedantic -wx -sval project.wixobj`

"appname" here is a little suspicious.

**Comment by andrewluka** [comment]
When I run the command directly, I get this error:
<pre>
light.exe : error LGHT0103 : The system cannot find the file 'project.wixobj' with type 'Source'.
</pre>
"appname" is the root directory of the project.

**Comment by albcunha** [comment]
I´m getting the same proble with windows 10, wix 311. I tried to downgrade to win 10 and it didnt work. The only solution was to remove-it msi from package json, as explained on this thread:

https://github.com/electron-userland/electron-builder/issues/4345#issuecomment-736906491

**Comment by chris-moon** [comment]
I've been facing this where light is failing during our electron-builder command. it looks like it might have been caused by this change 7 years ago https://github.com/electron-userland/electron-builder/commit/9770851c1a8c1d543bbe20d8b80d9867b28fe099#diff-da4f2396ed3d7083c74d6df00f6aadf98fb8785208617e7f38ce83d07531a47dR59

```
const objectFile = stageDir.getTempFile("project.wixobj")
```
was changed to
```
const objectFiles = ["project.wixobj"]
```

The staging directory when I run electron-builder is in `output/__msi-x64` in my case so running `light` 2 folders up fails. When i execute the `light` command from `output/__msi-x64` it succeeds in generating an msi
