### ISSUE TITLE
Adding extra files `package.json` throws an error with app.asar

### ISSUE THREAD

**Issue by joshuef** [electron-userland/electron-builder#4160]
* **Version**: 
21.2.0

-

* **Target**: 
MacOs 10.14.5

Adding `extra files` to include `package.json` from the root dir:
```
...
"files": [
      "./package.json",
      "app/dist/**/*",
      "app/tray-icon.png",
      "app/app.html",
      "app/bg.html",
      "app/main.prod.js",
      "app/main.prod.js.map"
    ],
"extraFiles": [
      {
        "from": "internals/what.js",
        "to": "what.js"
      },
      {
        "from": "package.json",
        "to": "package.json"
      }
    ],
```

Throws:

``` ⨯ Application "package.json" in the "<the_path>/release/mac/SAFE Network App.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration. ```

`what.js` doesn't throw any error. But simply adding the extra files package.json entry means the build fails. (Although the file is _actually_ copied over).

Any ideas if this is config or a bug?

(Seems similar to https://github.com/electron-userland/electron-builder/issues/2404 , though nothing there helps )

**Comment by BrunoQuaresma** [comment]
I'm having the same issue.

**Comment by alibosworth** [comment]
@joshuef @BrunoQuaresma may I ask why you are adding package.json to `extraFiles`?

**Comment by joshuef** [comment]
@alibosworth to access some of its contents. (current version for us)

**Comment by joshuef** [comment]
I ended up doing this via [afterpack](https://www.electron.build/configuration/configuration#afterpack), FYI @BrunoQuaresma .

(Though I still think the issue is valid)

**Comment by joshuef** [comment]
Still relevant AFAIK.
