### ISSUE TITLE
Electron specified procedure could not be found

### ISSUE THREAD

**Issue by jindalrohit** [electron-userland/electron-builder#4162]
Application is working fine on my system but on client system it is showing this issue.

![image](https://user-images.githubusercontent.com/12742169/63156226-dcb09000-c031-11e9-99ee-dc7d8fdfff48.png)

Technologies used :

Angular v8
Electron v4.1.4
Realm v3.0.0

**Comment by alibosworth** [comment]
What makes you think this is electron-builder related?

What version of electron-builder are you using, and what kind of build are you shipping to this customer?

**Comment by jindalrohit** [comment]
@alibosworth  I am using "electron-builder": "20.41.0". I am providing .exe file to customer. The same file is working on my system but not on customer system. 

I am using windows 10 and customer is using windows7 - 64 bit. Is this happening due to windows?

**Comment by alibosworth** [comment]
I don't know, is there any way you can test windows 7? Perhaps a VM? https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

The error shown is missing a lot of content ("..."), can the user expand that window to show where the error is happening more specifically? It looks like it might be Realm.

I have no experience with Realm, but it seems it doesn't officially support Electron? https://github.com/realm/realm-js/issues/928

**Comment by jindalrohit** [comment]
@alibosworth Realm does not support windows 7. That's why it is happening.

https://docs.realm.io/sync/realm-studio#release-notes
