### ISSUE TITLE
On Travis CI, codesigning rejected.

### ISSUE THREAD

**Issue by sasagar** [electron-userland/electron-builder#4164]
* **Version**: 21.0.0 and over (up to the latest)

* **electron-updater version**: 4.1.2

* **Target**: Mac and Windows

When I pushed to my repository and build with Travis CI, codesigning has been rejected.  
But, with version 21.0.0, it passes.

The error message I see is below.

```
> electron-builder -mw
  • electron-builder  version=21.1.6 os=17.4.0
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=darwin arch=x64 electron=6.0.2 appOutDir=/Users/travis/build/sasagar/[myAppName]/dist/mac
  ⨯ macOS High Sierra 10.13.6 is required to sign
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [myAppName]@4.6.3 release: `electron-builder -mw`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the [myAppName]@4.6.3 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travis/.npm/_logs/2019-08-16T13_37_41_331Z-debug.log
The command "npm run release" exited with 1.
```

If more info needed, please notify me.

**Comment by alibosworth** [comment]
What's the environment on your Travis?

>macOS High Sierra 10.13.6 is required to sign

**Comment by sasagar** [comment]
@alibosworth 
Sorry that I noticed your reply late.

> What's the environment on your Travis?

I didn't specify the version (only specifying using XCode).  
After I specify the OSX version, it works!

Thanks for your suggestion.

**Comment by deepkesh26** [comment]
I am getting same issue can you please tell me location and file where you set OSX version

> @alibosworth
> Sorry that I noticed your reply late.
> 
> > What's the environment on your Travis?
> 
> I didn't specify the version (only specifying using XCode).
> After I specify the OSX version, it works!
> 
> Thanks for your suggestion.

**Comment by JuanIrache** [comment]
@deepkesh26 Did you ever find out where to set the OSX version? Thanks
