### ISSUE TITLE
unable to include .d.ts files from node_modules

### ISSUE THREAD

**Issue by dannypaz** [electron-userland/electron-builder#4165]
Im trying to use ts-node w/ electron-builder but cannot get the types to be found (or to be used in the package).

Is there a way that I can override the globs that are used in the `files` option of the builder? https://www.electron.build/configuration/contents#files

I've been able to look into the `node_modules` directory AND have added `DEBUG=electron-builder` and still not able to see any of the `@types` folders being copied

**Comment by inca** [comment]
It doesn't work for me either, and I have no decent workaround so far. 🆘
