### ISSUE TITLE
Error: Code signature at URL | did not pass validation: code failed to satisfy specified code requirement(s)

### ISSUE THREAD

**Issue by jenitaex** [electron-userland/electron-builder#4166]
* **Version**: 20.15.1

 
electron-updater: v2.21.10

* **Target**: Mac

 
After successful download of update, getting `Error: Code signature at URL <path to .app> did not pass validation: code failed to satisfy specified code requirement(s)`

To sign the app, we used a newly generated Developer ID application certificate as the old certificate that was used previously was expired.

What is already tried:
- Run `codesign --verify --deep --verbose=2  <path_to_app>`
Output:
```
<Path>: valid on disk
<Path>: satisfies its Designated Requirement
```

**Comment by alibosworth** [comment]
@jenitaex We ran into this too. My understanding is that the autoupdate (based on squirrel-mac) will fail in that way if the Team ID changes, check this out: https://github.com/Squirrel/Squirrel.Mac/issues/160

>For an update to be considered valid it must meet the designated requirement of the current version.

>This is done to verify the authenticity of a given update, and to prevent a malicious update from being installed over the top of a genuine version.

**Comment by PByH** [comment]
I have exactly the same situation.
A few months ago I've created an application and signed it with a certificate which is expired now. So I've got another certificate and use it to sign my app, but auto-update is not working: "electron-builder did not pass validation code failed to satisfy specified code requirements". As far as I understand, there is a workaround for windows platform ("verifyUpdateCodeSignature":false property), but there are no workarunds for mac. Can you add the same property for mac/dmg platform?

**Comment by mattdh250** [comment]
Hi,

We now have the same problem. Our code signing certificate is due to expire in Janurary 2020 so I was going through and updating our applications with our newly issued certificate.

I resigned our electron app and built for Windows and tested that we were able to auto-update from the previous version signed with our expiring certificate to our new version signed with our new certificate. This worked without any issues.

I repeated the same test on mac only to receive this error.

We are using:
Electron: 4.2.10
Electron-builder: 21.2.0
Electron-update: 4.0.6

The tests were run on a mac running macOS Catalina (10.15).

Using codesign I was able to get the following signing information for the original app:
```
$ codesign -d -v -r - "/Applications/DemoApp.app/"
Executable=/Applications/DemoApp.app/Contents/MacOS/DemoApp
Identifier=com.DemoApp.mediaplayer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=380 flags=0x10000(runtime) hashes=3+5 location=embedded
Signature size=4665
Signed Time=16 Oct 2019 at 14:32:14
Info.plist entries=24
TeamIdentifier=not set
Runtime Version=10.12.0
Sealed Resources version=2 rules=13 files=9
designated => identifier "com.DemoApp.mediaplayer" and certificate leaf = H"34fde3281bcd9f816971d0a7c3ae55c1e0a94ea5"
```

And the same command against the new app returns:
```
$ codesign -d -v -r - "/Applications/DemoApp 2.app/"
Executable=/Applications/DemoApp 2.app/Contents/MacOS/DemoApp
Identifier=com.DemoApp.mediaplayer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=380 flags=0x10000(runtime) hashes=3+5 location=embedded
Signature size=4665
Signed Time=25 Oct 2019 at 11:37:25
Info.plist entries=24
TeamIdentifier=not set
Runtime Version=10.12.0
Sealed Resources version=2 rules=13 files=9
designated => identifier "com.DemoApp.mediaplayer" and certificate leaf = H"09ee96209aa6b8ea58faf974e2e207e9cc657683"
```

The only obvious difference is the certificate leaf (which I believe is the identity hash), which I would expect to be different as they are different certificates?

Just to provide a little more information on the actual certificates themselves:

**Original Certificate**
```
$ codesign -dvvvv --extract-certificates /Applications/DemoApp.app
Executable=/Applications/DemoApp.app/Contents/MacOS/DemoApp
Identifier=com.DemoApp.mediaplayer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=380 flags=0x10000(runtime) hashes=3+5 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=658432
Hash type=sha256 size=32
CandidateCDHash sha1=17d87fb361a8e9aec2b5cd51e5c1fe6b4ecc4794
CandidateCDHashFull sha1=17d87fb361a8e9aec2b5cd51e5c1fe6b4ecc4794
CandidateCDHash sha256=10b8ac8796fe0ff0100971a1235752ae45bda296
CandidateCDHashFull sha256=10b8ac8796fe0ff0100971a1235752ae45bda296fc00991eaabd5d2c4e57e3e3
Hash choices=sha1,sha256
CMSDigest=20676ce98d3972859e3a2b48ac5155264917f0e5c55e8f311e65db79eb31e8e5
CMSDigestType=2
Page size=4096
CDHash=10b8ac8796fe0ff0100971a1235752ae45bda296
Signature size=4665
Authority=DemoApp Limited
Authority=DigiCert SHA2 Assured ID Code Signing CA
Authority=DigiCert Assured ID Root CA
Signed Time=16 Oct 2019 at 14:32:14
Info.plist entries=24
TeamIdentifier=not set
Runtime Version=10.12.0
Sealed Resources version=2 rules=13 files=9
Internal requirements count=1 size=104
```

**New Certificate**
```
$ codesign -dvvvv --extract-certificates "/Applications/DemoApp 2.app"
Executable=/Applications/DemoApp 2.app/Contents/MacOS/DemoApp
Identifier=com.DemoApp.mediaplayer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=380 flags=0x10000(runtime) hashes=3+5 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=658432
Hash type=sha256 size=32
CandidateCDHash sha1=1a537e85425b36b2e4baa58a773740686e6c79fd
CandidateCDHashFull sha1=1a537e85425b36b2e4baa58a773740686e6c79fd
CandidateCDHash sha256=61a8aabef3c1506a47e33251d6e2c5044fa211d4
CandidateCDHashFull sha256=61a8aabef3c1506a47e33251d6e2c5044fa211d49acb9fd2b8464f52191e991c
Hash choices=sha1,sha256
CMSDigest=440d5ae05548200498041f878e5ab6aefdb50bd77e951981f0655cf67cd5c981
CMSDigestType=2
Page size=4096
CDHash=61a8aabef3c1506a47e33251d6e2c5044fa211d4
Signature size=4665
Authority=DemoApp Limited
Authority=DigiCert SHA2 Assured ID Code Signing CA
Authority=DigiCert Assured ID Root CA
Signed Time=25 Oct 2019 at 11:37:25
Info.plist entries=24
TeamIdentifier=not set
Runtime Version=10.12.0
Sealed Resources version=2 rules=13 files=9
Internal requirements count=1 size=104
```

Can anyone more knowledgeable on this help to identify why this is not working? It is important that we are able to update our users from the current version to the new version of our application, which is signed with this new certificate.

**Comment by mattdh250** [comment]
Following on from my previous comment, I now understand how designated requirements work and how they can be specified to resolve the issue I ran into where auto-update was failing when the next version of our app was signed by a re-issued certificate.

As per the comment [here](https://github.com/Squirrel/Squirrel.Mac/issues/160#issuecomment-171545819), the only way I have found to get this working is to build an intermediate update with a custom designated requirement that covers both the original and new certificate and that is signed with the original certificate.

In practice, what you need to do to accomplish this is:

1.
