### ISSUE TITLE
Appx Windows Store requires indentityName to start with numbers.

### ISSUE THREAD

**Issue by Stanlyhalo** [electron-userland/electron-builder#4178]
I am using the latest version of electron-builder. I tried setting my identityName for windows store because it requires to start with numbers, and it errors on build because it can't start with numbers. I began using UWP JavaScript on Visual Studio and I realized it has a xml file that has all the application information for it's identity. So I tried putting it in my nodejs project (there the same thing just I had hope to have the ability to use nodejs again), and I ran this in command prompt: npm run dist --config myXMLfile.xml, and I got errors when uploading it to Microsoft partner center for my windows store application, the errors were coming from the Identity name, and the fact that I can't have a space for my application name even though I registered it as that.

**Comment by sungle3737** [comment]
i have same problem
