### ISSUE TITLE
I build fails on mac,the error is no such file or directory,

### ISSUE THREAD

**Issue by 9walkStep** [electron-userland/electron-builder#4184]
* **Version**: 
electron-builder 19.56.2 electron 4.0.4

* **Target**: 
mac dmg pkg

"mac/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist" 
Electron Helper EH.app isn't exist

**Comment by vtebano13** [comment]
I am having this same issue.  Was this ever fixed?  Is there a workaround?
