### ISSUE TITLE
Linux Ubuntu AppImage target no icon

### ISSUE THREAD

**Issue by osenvosem** [electron-userland/electron-builder#4186]
* **Version**: 21.1.5

* **Target**: Linux AppImage

Icons are located in the default `build` directory. This is it's structure:

```
build
├── icon.icns
├── icon.ico
├── icon.png
└── icons
    ├── 128x128.png
    ├── 16x16.png
    ├── 256x256.png
    ├── 32x32.png
    ├── 512x512.png
    └── 64x64.png
```

I tried to specify path to icon in the configuration. Result is the same:

Ubuntu 19.04

![Screenshot from 2019-08-27 17-38-51](https://user-images.githubusercontent.com/6762673/63781386-5da13e80-c8f2-11e9-8c64-685ab5930016.png)

Any workaround?

**Comment by BloodShura** [comment]
Same problem here.

**Comment by BloodShura** [comment]
Yes, it **IS** relevant.

**Comment by BloodShura** [comment]
Once again: it **IS** relevant.

**Comment by BloodShura** [comment]
YES YES YES YES, ONCE AGAIN, YES

**Comment by mahnunchik** [comment]
+1

**Comment by ttomaszewski** [comment]
+1

**Comment by mahnunchik** [comment]
![20200808_191450](https://user-images.githubusercontent.com/780935/91752238-56c4a000-ebc6-11ea-9a91-1e293d03352e.jpg)

**Comment by BloodShura** [comment]
Hello darkness, my old friend. We've been abandoned once again.
