### ISSUE TITLE
Build and sign an .ipa

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#419]
Hi,

I would like to generate an .ipa to send my app with Applicaiton Loader, how can I do it with electron-builder ?

I have my .dmg and .app file with

> npm run-script dist

My package.json :

```
{
  "scripts": {
    "start": "electron ./app --enable-logging",
    "dev": "NODE_ENV='development' npm run start",
    "dist": "npm run dist:osx",
    "dist:osx": "build --platform darwin"
  },
  "devDependencies": {
    "electron-builder": "3.23.0",
    "electron-prebuilt": "1.1.0"
  },
  "build": {
    "productName": "MyApp",
    "app-bundle-id": "MyApp",
    "app-category-type": "public.app-category.productivity",
    "iconUrl": "http://website.com/icon.ico",
    "osx": {
      "title": "Sparkle",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "mas": {
      "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)"
    }
  }
}
```

**Comment by develar** [comment]
https://en.wikipedia.org/wiki/.ipa_(file_extension)

> An .ipa file is an **iOS application** archive file which stores an iOS app. Each .ipa file includes a binary for **the ARM architecture** and can only be installed on an iOS device.

Hmm... Do you want to build electron app for iOS?

**Comment by jechazelle** [comment]
No for Mac Store, but I have a problem to send my App (Sign + Send)

**Comment by develar** [comment]
For mas you need to build `pkg`, it is supported. Please see https://github.com/electron-userland/electron-builder/issues/332#issuecomment-213997877 Set [target](https://github.com/electron-userland/electron-builder/wiki/Options#OsXBuildOptions-target) to `mas`.

**Comment by jechazelle** [comment]
Thank you !

I added "target": "mas" in my package.json

```
"osx": {
      "title": "Sparkle",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "target": "mas",
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },

```

I think  it's ok, but I have an the same error : 

`Error: App is not signed: CSC_LINK or CSC_NAME are not specified, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing`

I don't understand where can I declare this CSC_LINK (The HTTPS link (or base64-encoded data) to certificate (*.p12 file).) and CSC_NAME

I try this : 
`export CSC_NAME="Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)"`

I have to question : 

1 - In my package.json I declare "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)", why declare in my package.json and with export ?

```
"osx": {
      "title": "Sparkle",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "target": "mas",
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "mas": {
      "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)"
    }
```

2 -  I know that CSC_LINK is "The HTTPS link (or base64-encoded data) to certificate (*.p12 file)" form documentation, but where can I found this ? What is the format ? example : export CSC_LINK="url / string / number" ?

**Comment by jechazelle** [comment]
Thank you develar !!
