### ISSUE TITLE
[macos]Is there a simple way to clear user data after uninstall app?

### ISSUE THREAD

**Issue by hawx1993** [electron-userland/electron-builder#4190]
whether we can clear user data if a user deletes an electron app from Application?

like add { "deleteAppDataOnUninstall": true} on windows?

**Comment by pronebird** [comment]
We ship a custom `uninstall.sh` script for macOS since there is no official uninstaller available.

`pkgutil` supports a couple of commands but probably not very useful, see:
https://wincent.com/wiki/Uninstalling_packages_(.pkg_files)_on_Mac_OS_X

**Comment by hawx1993** [comment]
@pronebird If user deletes app from Application, then how we can delete user data?

**Comment by pronebird** [comment]
@hawx1993 that's true, I can only think of bundling the uninstall script with DMG or give explicit instructions on the removal.

**Comment by hawx1993** [comment]
I use electron-localstorage to set one flag into app, while everytime you start app, which will check if the flag can get from app, if not, this was new installed and opend first time, so it will clear the old userdata.

```js
const storage = require('electron-localstorage');
const rimraf = require('rimraf');

if(platform.isMac && !isDevelopment) {
  storage.setStoragePath(path.join(__dirname,'../data.json'));
  const opened = storage.getItem('opened');
  const update = storage.getItem('updated');

  if(!opened) {
    rimraf(`${userDataPath}`, () => {
      console.log('clear user data path done!')
    })
  }
  storage.setItem('opened', 'true');
}
```

**Comment by Coffe2Cat** [comment]
> I use electron-localstorage to set one flag into app, while everytime you start app, which will check if the flag can get from app, if not, this was new installed and opend first time, so it will clear the old userdata.
> 
> ```js
> const storage = require('electron-localstorage');
> const rimraf = require('rimraf');
> 
> if(platform.isMac && !isDevelopment) {
>   storage.setStoragePath(path.join(__dirname,'../data.json'));
>   const opened = storage.getItem('opened');
>   const update = storage.getItem('updated');
> 
>   if(!opened) {
>     rimraf(`${userDataPath}`, () => {
>       console.log('clear user data path done!')
>     })
>   }
>   storage.setItem('opened', 'true');
> }
> ```

我也有同样的需求，也用了类似的方法实现了，我的做法是：在dmg的安装包里加入了一个flag文件，然后在安装后启动app的时候会检查这个文件是否存在，存在的话就会去清理AppData下面的文件，然后退出app的时候会删掉这个flag文件。然后在后面的每次启动和退出app都会去判断这个flag文件的存在。

但是现在领导要求清理的逻辑不要去触碰主程序，就应该放在安装步骤里面。。所以这块还能有其他办法吗？如何在安装dmg包的时候去清理appdata下面的文件。
