### ISSUE TITLE
nsis: reboot after installation?

### ISSUE THREAD

**Issue by fxwcryi** [electron-userland/electron-builder#4192]
Hi,
We're installing drivers using the nsis option !macro customInstall which works great, and we realized we need to reboot the (Windows) machine after installation.

We plan to add the following to the customInstall macro, right after we finish installing the drivers:
MessageBox MB_YESNO|MB_ICONQUESTION "Do you wish to reboot the system?" IDNO +2
    Reboot

And are wondering if this is safe? i.e. - can we assume it is safe for us to reboot the machine in customInstall? is everything else done at that point?

Thanks!!

**Comment by juanmartin** [comment]
HI! I'm also curious about this.
In our case we actually need to reboot after uninstalling.

**Comment by Testman231** [comment]
I have the same problem.

**Comment by crazydevlegend** [comment]
It's a MUST-IN feature for a installation wizard.
and I'm wondering how we can detect the moment installation is done successfully.

I tried with `.onInstSuccess`, but the message box is prompted at the the beginning.
