### ISSUE TITLE
generating latest-linux.yml, latest-mac.yml

### ISSUE THREAD

**Issue by trae-op** [electron-userland/electron-builder#4194]
For **latest-linux.yml** format of file **.AppImage** default. And for **latest-mac.yml** format of file **.zip**.
Can I change this?
For example **latest-mac.yml** change to **.dmg** format, and **latest-linux.yml** change to **.deb**
![image](https://user-images.githubusercontent.com/12648541/63927541-9528fb80-ca56-11e9-8070-9ea9d6b8d5e9.png)

**Comment by pronebird** [comment]
What's your builder config?

**Comment by trae-op** [comment]
> What's your builder config?

"build": {
    "appId": "MyApp",
    "extraResources": "build/**/*",
    "files": [
      "!dist/*"
    ],
    "directories": {
      "output": "dist/${os}/"
    },
    "publish": [
      {
        "provider": "generic",
        "url": "http://my-app.com/downloads/${os}/"
      }
    ],
    "mac": {
      "category": "public.app-category.productivity",
      "artifactName": "${productName}-${version}-${arch}.${ext}",
      "target": [
        "dmg",
        "zip"
      ]
    },
    "linux": {
      "category": "Chat;GNOME;GTK;Network;InstantMessaging",
      "packageCategory": "GNOME;GTK;Network;InstantMessaging",
      "description": "Desktop for Linux",
      "target": [
        "deb",
        "zip",
        "AppImage"
      ],
      "artifactName": "${productName}-${version}-${arch}.${ext}"
    },
    "snap": {
      "synopsis": "Desktop App"
    },
    "dmg": {
      "icon": "build/icon.icns",
      "iconSize": 100,
      "contents": [
        {
          "x": 380,
          "y": 200,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 110,
          "y": 200,
          "type": "file"
        }
      ]
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "icon": "build/icon.ico"
    },
    "nsis": {
      "perMachine": true,
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    }
  },

**Comment by danieltigse** [comment]
Did you solve it @trae-op ?

**Comment by trae-op** [comment]
> Did you solve it @trae-op ?

No, I have applied other solutions

**Comment by mmaietta** [comment]
Right now, `electron-updater` only supports dmg, AppImage, and nsis for auto-updates. That's what the `path` var is being used for IIRC. https://www.electron.build/auto-update
We'd need additional "installer" scripts written to enable other extensions to be used.

@trae-op, just curious, what was your solution?
