### ISSUE TITLE
Uncaught Error: Access is denied

### ISSUE THREAD

**Issue by Zyles** [electron-userland/electron-builder#4195]
* **Version**: 
21.2.0

* **Target**: 
Windows 10

Error after building when running exe:

```
Uncaught Error: Access is denied.
\\?\C:\Users\user\AppData\Local\Temp\f19512a4-a38b-4428-96b3-7b487cad10a1.tmp.node
```

And app is blank page.

**Comment by pronebird** [comment]
What is `\\?` in the path?

**Comment by Zyles** [comment]
I don't know, you tell me.

**Comment by pronebird** [comment]
@Zyles it's like UNC path, are you running the project from some net disk or something?

**Comment by Zyles** [comment]
No just Win 10.

`electron/js2c/asar.js:155`

**Comment by Zyles** [comment]
Still a problem.

**Comment by Zyles** [comment]
Still a problem.

**Comment by cegonzalv** [comment]
Hi, I'm having the same problem after installing node-printer as a dependency on my electron app

**Comment by macgill4444** [comment]
We're running into this to for a user on Win10. Any updates?

**Comment by Jeff1912** [comment]
遇到同样问题

**Comment by Jeff1912** [comment]
it can be solved by executing the program by administrator
