### ISSUE TITLE
[macos]how to select 'install for me only' by default while install pkg?

### ISSUE THREAD

**Issue by hawx1993** [electron-userland/electron-builder#4196]
As the picture shows below, I wonder know how to config so that I can install a pkg file and let `install for me only` as a default option. So that I do not need to input  password.

![image](https://user-images.githubusercontent.com/5305263/63930274-93c2f780-ca85-11e9-8d1f-9e7a2198e846.png)

**Comment by pashvin** [comment]
Try this

"pkg": {
            "allowCurrentUserHome": true,
            "allowAnywhere": false,
            "allowRootDirectory": false
        }

**Comment by pronebird** [comment]
This is literally described in the docs:
https://www.electron.build/configuration/pkg
