### ISSUE TITLE
[msi]Unable to delete the AppData while uninstall the Applicaton using msi installer

### ISSUE THREAD

**Issue by abhishekmatcha** [electron-userland/electron-builder#4198]
* **Version**: 21.2.0

* **Target**:  Windows

I am using the msi installer when we uninstall the application the AppData related to the application is not getting removed.
Is there any Simple way we can remove AppData ?

**Comment by Farshatov-Alex-Magora** [comment]
Any updates here???

**Comment by liquangu** [comment]
+1 for the question.

**Comment by darshitshah8** [comment]
any luck ?
