### ISSUE TITLE
cannot enable long stack traces after promises have been created

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#420]
I already have my app packaged. What is a simple way to generate the installers? I'm having a lot of trouble with the documentation.

**Comment by develar** [comment]
What's wrong here — https://github.com/electron-userland/electron-builder#in-short? 

> I already have my app packaged

electron-builder does it, do not reinvent the wheel and waste your time.

**Comment by mzmousa** [comment]
Okay, not sure if I should post a new issue then, but this seems to be my error, and not sure if it's from ```electron-builder``` or my app:
```Error: cannot enable long stack traces after promises have been created```

**Comment by mzmousa** [comment]
It's something wrong with my app. Just followed the simple start guide on the [electron-quick-start](https://github.com/electron/electron-quick-start) page and electron-builder worked fine there. Thakns

**Comment by develar** [comment]
>  I'm having a lot of trouble with the documentation.

Feel free to list your troubles here and docs will be improved.
