### ISSUE TITLE
App is not signed: CSC_LINK or CSC_NAME example

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#421]
Hi,

I try to build my app to MAS (with "target": "mas" in my package.json, I think  it's ok, but I have an the an error : 
`App is not signed: CSC_LINK or CSC_NAME`

Can I have an example please ?

I don't understand how can I declare this CSC_LINK (The HTTPS link (or base64-encoded data) to certificate (*.p12 file).) and CSC_NAME

I try this : 
`export CSC_NAME="Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)"`

In my package.json I declare "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)", why declare in my package.json and with export ?

```
"osx": {
      "title": "Sparkle",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "target": "mas",
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "mas": {
      "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)"
    }
```

I know that CSC_LINK is "The HTTPS link (or base64-encoded data) to certificate (*.p12 file)" form documentation, but where can I found this ? What is the format ? example : export CSC_LINK="url / string / number" ? Can I have an example please ?

Thank you !

**Comment by develar** [comment]
Export in the docs https://github.com/electron-userland/electron-builder/wiki/Code-Signing is a link — link to https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html#//apple_ref/doc/uid/TP40012582-CH31-SW7

If you don't have Xcode, open Keychain -> login -> My Certificates -> select your cert -> export

**Comment by jechazelle** [comment]
I must copy and paste the content from my CertificateSigningRequest.certSigningRequest in export CSC_LINK="content_CertificateSigningRequest.certSigningRequest" ?

**Comment by develar** [comment]
`CSC_LINK` is a HTTPS link to file (see "Upload *.p12 file" in the [docs](https://github.com/electron-userland/electron-builder/wiki/Code-Signing)).

**Comment by jechazelle** [comment]
I rename my certificate CertificateSigningRequest.certSigningRequest by cert, and I upload this on my server, I try export CSC_LINK="http://mywebsite.com/cert", but it doesn't work

But when I export my file, his name is CertificateSigningRequest.certSigningRequest not *.p12, I must rename it ?

**Comment by develar** [comment]
@jechazelle https://youtu.be/pQaXpUouz2A

**Comment by develar** [comment]
Don't understand your issue. Export cert+key using keychain. See video. You get p12 file. Upload it or encode to base64 data. Set CSC_LINK env to link or base64 data. That's all.

**Comment by jechazelle** [comment]
Woow thank you very much @develar, your movie help me !! :)
I think you can put the movie link in your documentation, it's very easy with this !

I set this :

export const CSC_LINK="https://drive.google.com/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx"
export const CSC_KEY_PASSWORD="strongpass&"

export const CSC_INSTALLER_LINK="https://drive.google.com/uc?export=download&id=0BxxgD-KEa7-iXzRCxxxxxxxxxx"
export const CSC_INSTALLER_LINK="strongpass&"

export const CSC_INSTALLER_LINK="Developer ID Application: Jeremie Chazelle (XXXXXXXX)"

But I have always this error Error: App is not signed: CSC_LINK or CSC_NAME are not specified

Do you have an idea ?

**Comment by jechazelle** [comment]
Woow thank you very much @develar, your movie help me !! :)
I think you can put the movie link in your documentation, it's very easy with this !

I set this :

```
export const CSC_LINK="https://drive.google.com/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx"
export const CSC_KEY_PASSWORD="pass&"

export const CSC_INSTALLER_LINK="https://drive.google.com/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx"
export const CSC_INSTALLER_KEY_PASSWORD="pass&"

export const CSC_NAME="Developer ID Application: Jeremie Chazelle (XXXXXXXX)"
```

But I have always this error Error: App is not signed: CSC_LINK or CSC_NAME are not specified

Do you have an idea ?

**Comment by mbrainiac** [comment]
@jechazelle 

```
Consider to not use special characters (for bash) because “values are not escaped when your builds are executed”.
```

You should escape your CSC_LINK and CSC_KEY_PASSWORD

http://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-in-bash-how-do-we-know-it

**Comment by jechazelle** [comment]
thx @mbrainiac !

I tried
`sed -e 's/[]\/$*.^|[]/\\&/g' myfilecsc_link (with https://drive.google.com/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx in my file) `
same with CSC_KEY_PASSWORD

the result :
```
CSC_LINK : https:\/\/drive\.google\.com\/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx
CSC_PASSWORD : pass&
```

my new variable :
```
export CSC_LINK="https:\/\/drive\.google\.com\/uc?export=download&id=0BxxgD-KEa7-iXzxxxxxxx"
export CSC_KEY_PASSWORD="pass&"
```

But I have the same error:

```
Error: App is not signed: CSC_LINK or CSC_NAME are not specified, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
    at OsXPackager.<anonymous> (/Users/jeremiechazelle/Sites/release-checker-app/node_modules/electron-builder/src/osxPackager.ts:87:15)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/Users/jeremiechazelle/Sites/release-checker-app/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/Users/jeremiechazelle/Sites/release-checker-app/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/Users/jeremiechazelle/Sites/release-checker-app/node_modules/electron-builder/src/build-cli.ts:47:2)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by jechazelle** [comment]
Thx @mbrainiac !

**Comment by JeroenVinke** [comment]
https://www.youtube.com/watch?v=pQaXpUouz2A&feature=youtu.be helped me a lot, thanks for that. Please consider adding this to the [code signing](https://github.com/electron-userland/electron-builder/wiki/Code-Signing) page as i'm sure it will help others
