### ISSUE TITLE
electron-builder Linux packing is not working

### ISSUE THREAD

**Issue by tijo123** [electron-userland/electron-builder#4211]
My package.json file
    
  "build": {
    "appId": "12345",
    "productName": "MYAPP",
    "copyright": "Copyright 2019 ${author}",
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    },
    "win": {
      "target": "NSIS",
      "icon": "assets/logo/logo.png"
    }
  },
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },

But packing is working only on windows version only..

* **Version**: 

* **Target**:

**Comment by AleshaOleg** [comment]
Try to add `512x512.png` icon to your assets folder, as described here - https://www.electron.build/icons#linux. The path for your project will be `assets/icons/512x512.png`.

**Comment by tijo123** [comment]
I have added the icon(assets/icons/512x512.png). Still not working
After running **npm run dist** command,  Linux Application setup is not created. Only created windows exe set up.
I need to create Linux installation setup
The out put after running  **npm run dist**
![Capture2](https://user-images.githubusercontent.com/53806091/64337889-ef4d3200-cffd-11e9-91b3-a85b6853675f.PNG).

**Package.json**

    "linux": {
      "target": [
        "AppImage",
      ]
    },
    "win": {
      "target": "NSIS",
      "icon": "assets/logo/logo.png"
    }

**Comment by AleshaOleg** [comment]
You should build Linux version under Linux :D

**Comment by tijo123** [comment]
Sorry I am very new in electron. I cant understand.

**Comment by AleshaOleg** [comment]
To build a Linux version you should use real Linux machine. Or you can try to build with a multi-platform build as it's described here - https://www.electron.build/multi-platform-build.

**Comment by tijo123** [comment]
Ok...Thanks

**Comment by tijo123** [comment]
Hi,
I have created Linux version using AppImage format. After successfully created the application is not installed in linux (**mint**) system. I need to install the application in our system. 
Now we need to click the AppImage to start an application

    "linux": {
      "target": "AppImage",
      "category": "Application",
      "icon": "assets/logo/logo.png"
    },

**Comment by xudeming208** [comment]
> Hi,
> I have created Linux version using AppImage format. After successfully created the application is not installed in linux (**mint**) system. I need to install the application in our system.
> Now we need to click the AppImage to start an application
> 
> ```
> "linux": {
>   "target": "AppImage",
>   "category": "Application",
>   "icon": "assets/logo/logo.png"
> },
> ```

So do I.

**Comment by xudeming208** [comment]
> Hi,
> I have created Linux version using AppImage format. After successfully created the application is not installed in linux (**mint**) system. I need to install the application in our system.
> Now we need to click the AppImage to start an application
> 
> ```
> "linux": {
>   "target": "AppImage",
>   "category": "Application",
>   "icon": "assets/logo/logo.png"
> },
> ```

参考：https://github.com/electron-userland/electron-builder/issues/4506
