### ISSUE TITLE
Prevent MSI auto updating

### ISSUE THREAD

**Issue by bynho** [electron-userland/electron-builder#4212]
* **Version**:  21.2.0

* **Target**:  msi and nsis

I am building my distribution packaged with electron-webpack and have auto update on as well.  However I do not want MSI to automatically update, it seems that auto updater is using the latest.yml generated by the NSIS...  Is there a way to prevent MSIs automatically updating?  If not, is there a way for me to identify in the code whether the app is running from an MSI or NSIS ?

Thanks

**Comment by cslecours** [comment]
@bynho What did you end up doing?

**Comment by gilisegal** [comment]
@cslecours @bynho any solutions?

**Comment by prabhatsaini91** [comment]
Setup a configuration file inside your application. Let's say `{msi: true}` exists somewhere in that configuration file. Then you can simply check it inside the main process of your application and either run AutoUpdater or not. I use this - 
`  // App should call auto updater only when it is not an MSI
  if(!appConfig.msi) {
    AppUpdater();
  }`

**Comment by cslecours** [comment]
> @cslecours @bynho any solutions?

We ended up finding that some files (can't remember which ones) in the installation folder were different if installed by an msi or not and we enable/disable the autoupdater accordingly.
