### ISSUE TITLE
No such file or directory, Info.plist

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#422]
This fails on my system: ```build --platform darwin```.
I have npm version 3.8.9, node version 6.1.0, am running windows 7. However, the build for win32-x64 works fine.

**Comment by develar** [comment]
It is not possible to build OS X app on Windows. Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by develar** [comment]
Reopened – user-friendly error must be explicitly thrown
