### ISSUE TITLE
[release-it][win]use dash or dot instead of space for windows build output file(.exe)

### ISSUE THREAD

**Issue by geyuqiu** [electron-userland/electron-builder#4223]
electron-builder: 19.34.1

* **Version**: 
I will try with up-to-date version again

electron-updater: 2.18.2

* **Target**: 
Windows (built on mac)

release-it replaces empty space with . and electron-builder interprets empty space with -
so for a file with the name `electron-boilerplate setup 0.0.4.exe`, `electron-boilerplate-setup-0.0.4.exe` is given in `latest.yml`, and in release/tag, it is uploaded as: `electron-boilerplate.setup.0.0.4.exe`
Consequently, electron updater looks for the wrong file to download 

https://github.com/geyuqiu/deployElectron/releases

**Comment by brunolemos** [comment]
Came here to suggest the same thing. Depending on the way I do the release (manually or automated), the space gets replaced with space or dot, breaking the download link on my landing page, for example.
