### ISSUE TITLE
Question about autoUpdate and extraFiles on NSIS

### ISSUE THREAD

**Issue by martinvergara26** [electron-userland/electron-builder#4227]
* **Version**: 21.2.0

* **Target**: Windows 7, 8 and10

My app is packaged with three **extraFiles** directories, let's name them A, B, C. They are correctly copied in the installation directory after NSIS completes. 

Using autoUpdate, is it possible to update my app without removing directories A and B from installation directory, but updating C?

Thanks!

**Comment by martinvergara26** [comment]
@kzimny I didn't have the time to test it yet. But it is great news for me if `extraFIles` don't get updated.
Are you targeting nsis or nsis-web? It seems that `differentialPackage` option is [only valid on nsis-web](https://github.com/electron-userland/electron-builder/issues/2217)

**Comment by kzimny** [comment]
yes, I'm targeting nsisWeb:
```
        "nsisWeb": {
            "artifactName": "${productName}-Setup-${version}.${ext}",
            "oneClick": true,
            "perMachine": false,
            "allowToChangeInstallationDirectory": false,
            "runAfterFinish": true,
            "deleteAppDataOnUninstall": true,
            "differentialPackage": true
        },
```

**Comment by martinvergara26** [comment]
I'm following [this example](https://github.com/iffy/electron-updater-example) and works great.

BUT, if a modify an extra file, the file gets modified when app gets updated. And if I delete the file from extra files, then the file gets deleted when app is updated. 

Neither of these behaviors is useful for me. I need to maintain some extra files as they are (database files).

Tried with nsis and nsis-web targers. This is my package-json:

```
{
  :
  "build": {
    "appId": "<my-project-id>",
    "win": {
      "target": [
        {
          "target": "nsis-web",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "linux": {},
    "mac": {},
    "directories": {
      "buildResources": "public"
    },
    "nsis": {
      "differentialPackage": true
    },
    "nsisWeb": {
      "differentialPackage": true
    },
    "extraFiles": ["some_database_file"]
  },
  "devDependencies": {
    "electron": "^3.0.2",
    "electron-builder": "^20.28.4"
  },
  "dependencies": {
    "electron-log": "^1.3.0",
    "electron-updater": "4.2.0"
  }
}

```

**Comment by kzimny** [comment]
If you don't want the database and other modified files to be overridden, you need to extract them outside of your installation directory.

**Comment by martinvergara26** [comment]
Thank you @kzimny 
I'm facing to take that approach.
All I'm thinking right now is to move my extra files to app user data directory when the app is loaded for the first time. I would get the dir with app.getPath('userData')
But, of course, this would take a time.
