### ISSUE TITLE
Creating windows artifacts under different dir name (win, win-unpacked)

### ISSUE THREAD

**Issue by hp011235** [electron-userland/electron-builder#423]
Hello,
Since last week my windows artifacts are created under different directory names (win & win-unpacked).
Previously it was created under MyApp-win32-x64 & win-x64.
I am creating only x64 artifacts and build by running: `build --platform win32 --arch x64`.

Also, I didn't find anything around this in the release logs except [this one](https://github.com/electron-userland/electron-builder/releases/tag/v3.22.1) which seems to be for x32

PS: I am getting this difference in names after upgrading electron-builder from v3.17.0 to v3.25.0.

Thanks!

**Comment by develar** [comment]
It is intended change. Sorry that it was not mentioned in the release notes.

**Comment by hp011235** [comment]
@develar Apart from that, there are significant changes in unpacked directory.
Previously, it was looking like this:
![screen shot 2016-05-24 at 5 02 21 pm](https://cloud.githubusercontent.com/assets/7158776/15524860/358d18be-21da-11e6-826d-205ec8e5a9ff.png)

And now it is looking like this:
![screen shot 2016-05-24 at 4 57 26 pm](https://cloud.githubusercontent.com/assets/7158776/15524886/3be1d43e-21da-11e6-8e83-09e40624a948.png)

For some reason, the files under the hood have changed. And I am not able to find the MyApp.exe like before? Can you please explain what is going on here?

Thanks!

**Comment by hp011235** [comment]
@develar Can you please respond?

**Comment by develar** [comment]
@hp011235 I didn't respond because in the 4.x unpacked dir looks as before :)

**Comment by hp011235** [comment]
Thanks :)
