### ISSUE TITLE
electron-updater mac .dmg throw RR_UPDATER_ZIP_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by 15011120064** [electron-userland/electron-builder#4230]
MacUpdater  findFile(files, "zip", ["pkg", "dmg"])
findFile:files.find(fileInfo => !not.some(ext => fileInfo.url.pathname.toLowerCase().endsWith(`.${ext}`)))

Is the .pkg and .dmg formats not supported? Returns undefined when in dmg format?

**Comment by oskarhane** [comment]
Plus one on this. It would be great to being able to have other targets than zip for updates.
Zip has issues with notarization so updates are currently broken on MacOS Catalina.
