### ISSUE TITLE
Codesigning: "a sealed resource is missing or invalid", file modified in Squirrel framework

### ISSUE THREAD

**Issue by ccnokes** [electron-userland/electron-builder#424]
Mac OSX: 10.11.5
Electron: 0.37.8
electron-builder: 3.25.0

I just recently started having issues with codesigning. When I was on 3.16.0 and I ran this after building:

`codesign --verbose=4 --deep --strict MyApp.app/`

It would return: 

```
MyApp.app/: a sealed resource is missing or invalid
In subcomponent: MyApp.app/Contents/Frameworks/Squirrel.framework
file modified: MyApp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/Resources/ShipIt
```
After upgrading to 3.25.0, I don't get that error. Which is great, I'm a little curious as to why though... 

Anyways, since upgrading, the main problem I'm dealing with is that when I download the .dmg from Chrome, it says: "This kind of file could harm your computer, do you want to download anyways?". 

I don't know if this issue is even related to electron-builder, it was just my best first guess. Any help or guidance that you can offer would be much appreciated.

**Comment by develar** [comment]
I will check Chrome. Please use [RB App Checker Lite](https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12) to verify that your DMG is correct.

**Comment by ccnokes** [comment]
Thanks --- I'll add that Firefox and Safari work. RB App Checker doesn't let me drop dmgs on it, but it looks like my .app is ok. Do you want any output from it?

**Comment by ccnokes** [comment]
@develar thanks for looking into this, let me know if you've found anything. I went ahead and opened an issue on Chromium's issue tracker (https://bugs.chromium.org/p/chromium/issues/detail?id=614057#c2). 

What I was mainly trying to find out with that Chromium ticket was if Chrome is using any underlying OSX services for it's security check. They explain it doesn't, so I guess the issue isn't directly related to electron-builder or even Mac OSX. 

For the record, I still see the issue described in that Chromium issue, and I have no idea how they didn't see it after trying 20 times. ¯\_(ツ)_/¯. My organization has decided that occasionally getting that flag in the Chrome UI isn't a show-stopper so we're just living with it. 

Thanks for the great package!

**Comment by Ali-Baker** [comment]
I am getting this error too electron version `19.0.4`

```
In subcomponent: {APP}/Contents/Frameworks/Electron Framework.framework
{APP}/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/libEGL.dylib
{APP}/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/libvk_swiftshader.dylib
{APP}/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/libffmpeg.dylib
{APP}/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/libGLESv2.dylib
```

Where `{APP}` is the app directory
