### ISSUE TITLE
Is Electron Builder Dead?

### ISSUE THREAD

**Issue by neilrees** [electron-userland/electron-builder#4245]
There seems to have been a sudden halt to commits, the CI build is broken, and there are an increasing number of PRs?

**Comment by pashvin** [comment]
I noticed the same. There is no new build from long time and there is no response for any critical issues.
I am generating ZIP artifact and it get getting corrupted app and I opened that defect long time ago but no response.

**Comment by JCBsystem** [comment]
so what is a good alternative to Electron Builder ?

**Comment by poiru** [comment]
@JCBsystem We switched to using `electron-packager`, `electron-installer-windows`, `electron-osx-sign`, `electron-notarize`, and `electron-rebuild` directly. Took me a day to switch over, but the result works very well without all the `electron-builder` magic.

**Comment by develar** [comment]
All valid pull requests merged, sorry for delay.

**Comment by pashvin** [comment]
@develar Should we expect a new build soon? I am waiting for the fix on mac zip artifact (app inside zip is not running after extracting zip). I am waiting for that fix since last release. It was working before but broke in last release.

**Comment by tom-james-watson** [comment]
Also waiting on a new npm build for the new snap autostart feature. Is there something holding up the new build that we can maybe help out with?
