### ISSUE TITLE
Unable to exclude a directory from the build

### ISSUE THREAD

**Issue by ashleydavis** [electron-userland/electron-builder#4246]
* electron-builder 21.2.0

* Testing on Windows 10, but would also like to build for MacOS.

Thanks for electron-builder. I've been using it for a year and it's been great.

I've come across an issue that I can't work out on my own.

I'm unable to exclude a directory from my build.

I'm using a node_module called 'nightmare' and it includes it's own (older) copy of Electron. This makes the bundle huge and I'd like to download it after install. I've tried excluding the directory 'node_modules/nightmare/node_modules/electron' from the build but I can't get it to work.

I've prepared a simple example here:
https://github.com/ashleydavis/issue-excluding-directory-from-electron-builder

This example is based on the Electron Quick Start with the addition of electron-build. I've then installed nightmare as a dependency.

To try out the example, clone or download it, then:
```
npm install
npm run build
```

You can then install the application from the 'dist' directory and inspect its resources to see that the 'electron' dependency is not excluded.

Please see my example package file here:
https://github.com/ashleydavis/issue-excluding-directory-from-electron-builder/blob/master/package.json

I've customized the field "build.files" as follows:
```
        "files": [
            "**/*",
            "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
            "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
            "!**/node_modules/*.d.ts",
            "!**/node_modules/.bin",
            "!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}",
            "!.editorconfig",
            "!**/._*",
            "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}",
            "!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}",
            "!**/{appveyor.yml,.travis.yml,circle.yml}",
            "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}",
            "!node_modules/nightmare/node_modules/electron${/*}"
        ],
```
Note the exclusion at the end of the array.

I've also tried the following alternatives:
```
            "!**/node_modules/nightmare/node_modules/electron/*"
            "!**/node_modules/nightmare/node_modules/electron"
            "!**/node_modules/nightmare/node_modules/electron/**/*"
            "!**/node_modules/nightmare/node_modules/electron${/*}"
            "!node_modules/nightmare/node_modules/electron/*"
            "!node_modules/nightmare/node_modules/electron"
            "!node_modules/nightmare/node_modules/electron/**/*"
            "!node_modules/nightmare/node_modules/electron${/*}"
```

I've set DEBUG=electron-builder and committed the output here:
https://github.com/ashleydavis/issue-excluding-directory-from-electron-builder/blob/master/build.log

**Comment by tjfryan** [comment]
I'm getting something like this as well.  There doesn't seem to be a common-sense way to ignore individual node_modules in general. Something simple like `"!node_modules/unneededModule"` does not exclude 'unneededModule', although `"!**/node_modules/unneededModule/**/*"` does a close enough job, except if unneededModule has its own internal node_modules folder, that folder will always be present. I'm unable to find any glob that can exclude that intern node_modules folder.

Another workaround I've tried that almost worked but not quite is
```
{
  "from": "node_modules",
  "to": "node_modules",
  "filter": [
    "**/*",
    "unneededModule"
  ]
}
```
This caused the _opposite_ problem, where if any of my node_modules had its own node_modules folder that it relied upon, that internal node_modules folder was not present in the output bundle.

I've also tried manually deleting the files from the build directory immediately before running electron-builder, but the files somehow got bundled into the app.asar, despite them not reappearing in the build directory

There is some really confusing and inconsistent behavior with folders named node_modules that isn't very well documented.

**Comment by ashleydavis** [comment]
I think I worked around this by having two separate package files. One for dev and one for the Electron build. I also make use of Browserify which allows you to inline some npm modules and leave others alone. 

Be nice to get a proper fix though!

**Comment by o2genum** [comment]
Got this bug as well:
```
files:
- node_modules/**/*
- "!node_modules/unneeded-module${/*}"
```

This will exclude files in `node_modules/unneeded-module/` directory, but `node_modules/unneeded-module/node_modules` is still included.
