### ISSUE TITLE
Can't access removable media in Snap Linux - No slots option

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron-userland/electron-builder#4252]
electron-builder : `21.2.0`
electron: `6.0.10`
____________

Hello, 

To access removable USB media on Linux, `plugs` and `slots` needed to be setup with electron-builder.  

Here is my configuration: 

```
 "snap": {
      "confinement": "strict", 
      "plugs" : ["default", "removable-media" ],
      "slots" : ["default", "removable-media" ]
    },
```

As mentioned in [electron-builder docs](https://www.electron.build/configuration/snap) `plugs` working perfectly. 

But looks like there is no option for `slots`. And removable media can't be accessed without them. 

See more info on snap Linux interface management here:
https://snapcraft.io/docs/interface-management

-----

Right now when we access removable media in Snap package we just receive **Permission Denied** error like this: 

<img width="741" alt="Screen Shot 2019-12-27 at 10 17 03" src="https://user-images.githubusercontent.com/2331802/71508959-3a7f9f00-2892-11ea-8bfc-0f17cd06c238.png">

**Comment by vasyl-shumskyi** [comment]
@develar whenever you have time, can you please have a look on this?

**Comment by Sn8z** [comment]
I'm in the same position as @vasyl-shumskyi.
I'm trying to get MPRIS functionality to work correctly in a Snap which, if I'm understanding things correctly, means that I've got to configure a slot for it.
Any feedback on this issue @develar would be greatly appreciated.

Btw, thanks for all the great work you guys put in!

**Comment by vasyl-shumskyi** [comment]
@jdstrand could you advice something here as snap developer? 
maybe there is some workaround for this issue for electron snap publishers.

**Comment by farrisbar** [comment]
'slots' support is needed to build graphical electron based slots for Ubuntu "snappy" core (e.g. kiosk type apps)

**Comment by vasyl-shumskyi** [comment]
It is still relevant.

**Comment by vasyl-shumskyi** [comment]
I think it still relevant. Can devs confirm?

**Comment by vasyl-shumskyi** [comment]
Well, it turned out not be `electron-builder` issue. But `snapd` limitation. 

Snapd doesn't allow to auto-connect `removable-media` plug.

Checkout following threads for references:

- https://forum.snapcraft.io/t/opera-requests-auto-connect-to-removable-media
- https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455


The only way is to add `removable-media` plug to `electon-builder` configuration

```
"plugs" : ["default", "removable-media" ]
```

and then connect `removable-media` manually via Terminal 

```
snap connect snap-name:removable-media
```

It would be really great if snapd developers make `auto-connection` of `removable media` possible.
