### ISSUE TITLE
Electron app is not working while opening the app

### ISSUE THREAD

**Issue by velnandha27** [electron-userland/electron-builder#4255]
* **Version**: 

* **Target**: 

electron app is builded and the installed the app but its shown a error msg like 
![Screenshot_12](https://user-images.githubusercontent.com/55082171/65369626-21e96280-dc6d-11e9-887a-1eab3a335e9d.png)

**Comment by velnandha27** [comment]
how to fix that error

**Comment by JCBsystem** [comment]
this is not a electron-builder error

try 
yarn add electron-is-dev

**Comment by velnandha27** [comment]
yarn add electron-is dev is not working its shown an error
