### ISSUE TITLE
Code signing macOS, unidentified developer

### ISSUE THREAD

**Issue by kolking** [electron-userland/electron-builder#4257]
* **Version**: 20.34.0

* **Target**: macOS High Sierra 10.13.6

I have a valid Developer ID Application certificate installed, when I'm building my app everything seems to be ok:
```
  • packaging       platform=darwin arch=x64 electron=3.0.10 appOutDir=release/mac
  • signing         file=release/mac/MyApp.app identityName=Developer ID Application: Good Inc. (XXXXX) identityHash=XXXXX provisioningProfile=none
  • building        target=macOS zip arch=x64 file=release/MyApp-0.1.0-mac.zip
  • building        target=DMG arch=x64 file=release/MyApp-0.1.0.dmg
  • building block map blockMapFile=release/MyApp-0.1.0.dmg.blockmap
  • building embedded block map file=release/MyApp-0.1.0-mac.zip
```

When I'm checking the app after downloading it to another mac (the same macOS version 10.13.6), it shows the following:
```
$ codesign --verify --verbose /Applications/MyApp.app
/Applications/MyApp.app: valid on disk
/Applications/MyApp.app: satisfies its Designated Requirement

$ spctl --assess --verbose /Applications/MyApp.app
/Applications/MyApp.app: accepted
source=Developer ID

$ spctl -vvv -a -t open --context context:primary-signature /Applications/MyApp.app
/Applications/MyApp.app: accepted
source=Developer ID
origin=Developer ID Application: Good Inc. (XXXXX)
```

Apple's [SignatureCheck tool](https://developer.apple.com/download/more/?=SignatureCheck) also tells the app and dmg are valid.
```
$ /Volumes/Signature\ Check/check-signature ~/Downloads/MyApp-0.1.0.dmg 
(c) 2014 Apple Inc.  All rights reserved.
YES

$ /Volumes/Signature\ Check/check-signature /Applications/MyApp.app
(c) 2014 Apple Inc.  All rights reserved.
YES
```

But the GateKeeper still shows the "Unidentified Developer" warning when trying to open. What am I missing? What else can be wrong and how can I troubleshoot this?

**Comment by JCBsystem** [comment]
https://help.apple.com/xcode/mac/current/#/dev033e997ca

have you notarized it ?

**Comment by kolking** [comment]
@JCBsystem No, but it's only required for macOS starting from 10.14.5, and I'm checking it on macOS 10.13.6, so I assume that the GateKeeper in 10.13.6 should not show the warning for an app signed with Developer ID Application certificate.

>Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. Beginning in macOS 10.15, notarization is required by default for all software.

**Comment by erickmaynard** [comment]
> Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. Beginning in macOS 10.15, notarization is required by default for all software.

Actually I think that's not true. It seems like they check notarization via some server, because we just started getting our apps unable to run unless they are notarized even on High Sierra.

**Comment by wrgoto** [comment]
@kolking Were you ever able to solve this issue? We ran into this while trying to onboard a customer with High Sierra 10.13.6. Our app works on newer versions of macOS.

**Comment by kolking** [comment]
@wrgoto Nope, I had no time to figure out a solution, so just upgraded to a newer macOS.
