### ISSUE TITLE
NSIS updater silently crashes in case target files are locked

### ISSUE THREAD

**Issue by andrienko** [electron-userland/electron-builder#4259]
* **Version**: 21.2.0 
* **Target**: Windows, NSIS

We have an electron app that runs its own java child-process, that is shipped as app resources.

Once the update begins to install, the app quits successfully (everything is logged in our app).
And, judging from the logs provided by users, sometimes the app folder is locked by something (maybe an antivirus? disk failure? who knows) during the update (and the app was closed at this point)

The updater just silently quits then, without any indication that something has gone wrong, the user runs the partially-upgraded app (as he decides it succeeded) and gets his data corrupted.

Did not find anything looking like a solution in documentation (besides using custom NSIS scripts, of course)

Now, is there an option to at least let our users know that something has gone wrong (the file in resources folder has failed to be rewritten by newer version)?

**Comment by HimanshuSingh2308** [comment]
Hi,
Facing the same issue can anyone please help
*Important -> not happening on all devices happening randomly
