### ISSUE TITLE
How to set the window position?

### ISSUE THREAD

**Issue by xwartz** [electron-userland/electron-builder#426]
![image](https://cloud.githubusercontent.com/assets/4149827/15449208/bce9da28-1fa9-11e6-9f38-acc388a02722.png)

How do i center the installing window on screen ?

And this is my resp (https://github.com/xwartz/douban.fm/).

**Comment by develar** [comment]
I see only x and y in the https://github.com/LinusU/node-appdmg#json-specification Please file issue to https://github.com/LinusU/node-appdmg/issues

**Comment by xwartz** [comment]
I see the `window options` 

```
// Window options
  "window": {
    // Position when opened
    "position": { "x": 250, "y": 250 },

    // Window size
    "size": { "width": 500, "height": 500 }
  },

```

**Comment by develar** [comment]
Yes, but screen size is different, so, it is not clear for me how to center using x/y.

**Comment by xwartz** [comment]
OK. I see.

**Comment by develar** [comment]
appdmg issue: https://github.com/LinusU/node-appdmg/issues/104
