### ISSUE TITLE
Example of GitHub Actions to build a cross-platform Electron app

### ISSUE THREAD

**Issue by nathany** [electron-userland/electron-builder#4260]
Thanks for resolving #4176 

Is there any example of building a generic Electron app with GitHub Actions? The area that I have been running into trouble is with Spectron and ChromeDriver.

**Comment by stevenroussey-privicy** [comment]
The best I have found so far is [this article on Medium](https://medium.com/@johnjjung/building-an-electron-app-on-github-actions-windows-and-macos-53ab69703f7c)

**Comment by samuelmeuli** [comment]
Here you go: [`action-electron-builder`](https://github.com/samuelmeuli/action-electron-builder)
