### ISSUE TITLE
Invalid Icon File Size

### ISSUE THREAD

**Issue by RacerDelux** [electron-userland/electron-builder#4262]
I am using electron-builder v=21.2.0
Building for windows.

It just about completes (it gets to 'building' step when this happens:

```
Error while loading icon from "C:\RP1\ArcMages\arcmages-vue-client\dist_electron\.icon-ico\icon.ico": invalid icon file size
Error in macro MUI_INTERFACE on macroline 86
Error in macro MUI_PAGE_INIT on macroline 7
Error in macro MUI_PAGE_INSTFILES on macroline 5
!include: error in script: "oneClick.nsh" on line 8
Error in script "<stdin>" on line 107 -- aborting creation process

    at ChildProcess.childProcess.once.code (C:\RP1\ArcMages\arcmages-vue-client\node_modules\builder-util\src\util.ts:239:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```
This is the properties of the .ico file it is trying to use.
![image](https://user-images.githubusercontent.com/2667344/65462444-75011800-de1b-11e9-8928-656c2f9200a5.png)

I am generating my icons with the fllowing:

> electron-icon-builder --input=./public/image/branding/ArcMageLogoV2.png --output=build --flatten

Icons are below.
[icons.zip](https://github.com/electron-userland/electron-builder/files/3644510/icons.zip)

**Comment by RacerDelux** [comment]
This is STILL an issue and never fixed.

**Comment by hovancik** [comment]
I believe you need to use another program to generate `.ico`. I've had this just now and was fixed by using another tool (and from another source file)

**Comment by inDigiNeous** [comment]
Getting this same error. Used this convert to convert macOS ICNS icon to Windows ico:
https://www.coolutils.com/online/ICNS-to-ICO

**Comment by supertommy** [comment]
@Sakari369 I had used that site too and it didn't work; I think that site actually produces a bad ICO file.

I used this one instead: https://image.online-convert.com/convert-to-ico

I had to convert the ICNS to PNG first.

**Comment by Sakari369** [comment]
Yeah I used another program to produce a working icon. So probably an issue with some ICO files only.

**Comment by RacerDelux** [comment]
This would still be an issue within electron-builder then. Sadly the issue got closed.

**Comment by ZQ-jhon** [comment]
> Getting this same error. Used this convert to convert macOS ICNS icon to Windows ico:
> https://www.coolutils.com/online/ICNS-to-ICO

helpful for me, thanks for share!
