### ISSUE TITLE
macOS - Hardened runtime and node-hid missing 'path'

### ISSUE THREAD

**Issue by krpiatkowski** [electron-userland/electron-builder#4264]
21.1.1

* **Version**: 

Not relevant

* **Target**: 
macOS

We are using node-hid and want to notarize the app for catalina
The issue is that when setting  "hardendRuntime" the hid path disappears from the devices.

node-hid seems to be aware of this issue, and it might be related to they way electron-builder/electron-sign-osx signs apps.

https://github.com/node-hid/node-hid/issues/321

Are we losing entitlements for usb when hardning the runtime ?

**Comment by krpiatkowski** [comment]
Its turns out the missing entitlement is
com.apple.security.cs.allow-dyld-environment-variables
It seems to working fine afterwards

**Comment by gniezen** [comment]
Maybe that entitlement should be added by default instead of requiring a custom entitlements file? I just ran into the same issue.

**Comment by faisalm786** [comment]
> Its turns out the missing entitlement is
> com.apple.security.cs.allow-dyld-environment-variables
> It seems to working fine afterwards

May I know how to make sure it is working afterwards. I am using the node-hid in a module and use yalc to add to main module which is built. if I set hardenRuntime=true, the app crashes, if I set it to false, the app can run but still usb cannot detect. 

If I don't hardRuntime  (https://github.com/node-hid/node-hid/issues/321#issuecomment-517909735) and follow these workaround is by coping the node.HID from release, It can detect USB but if I transfer the APP file to another Mac it says file is damaged.

This is very frustrating and our customers are waiting. Anyone kindly please guide us to solve this problem. 

// entitlements.mac.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>com.apple.security.files.user-selected.read-only</key><true/>
<key>com.apple.security.files.user-selected.read-write</key><true/>
<key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
<key>com.apple.security.automation.apple-events</key><true/>
<key>com.apple.security.device.usb</key><true/>
<key>com.apple.security.cs.allow-jit</key><true/>
<key>com.apple.security.cs.allow-dyld-environment-variables</key><true/>
<key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
<key>com.apple.security.cs.disable-library-validation</key><true/>
<key>com.apple.security.device.audio-input</key><true/>
<key>com.apple.security.device.bluetooth</key><true/>
<key>com.apple.security.device.camera</key><true/>
<key>com.apple.security.device.microphone</key><true/>
<key>com.apple.security.files.user-selected.read-only</key><true/>
<key>com.apple.security.files.user-selected.read-write</key><true/>
<key>com.apple.security.network.client</key><true/>
<key>com.apple.security.network.server</key><true/>
<key>com.apple.security.cs.disable-executable-page-protection</key><true/>
<key>com.apple.security.temporary-exception.files.absolute-path.read-only</key><true/>
<key>com.apple.security.temporary-exception.files.absolute-path.read-write</key><true/>
</dict>
</plist>

//entitlements.mac.inherit.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
    <key>com.apple.security.cs.disable-library-validation</key><true/>
    <key>com.apple.security.temporary-exception.apple-events</key><true/>
    <key>com.apple.security.cs.allow-jit</key><true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key><true/>
    <key>com.apple.security.automation.apple-events</key><true/>
    <key>com.apple.security.device.usb</key><true/>
    <key>com.apple.security.device.audio-input</key><true/>
    <key>com.apple.security.device.bluetooth</key><true/>
    <key>com.apple.security.device.camera</key><true/>
    <key>com.apple.security.device.microphone</key><true/>
    <key>com.apple.security.files.user-selected.read-only</key><true/>
    <key>com.apple.security.files.user-selected.read-write</key><true/>
    <key>com.apple.security.network.client</key><true/>
    <key>com.apple.security.network.server</key><true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key><true/>
    <key>com.apple.security.temporary-exception.files.absolute-path.read-only</key><true/>
    <key>com.apple.security.temporary-exception.files.absolute-path.read-write</key><true/>
  </dict>
</plist>

build settings
"mac": {
      "category": "public.app-category.utilities",
      "target": [
        "dmg"
      ],
      "hardenedRuntime": false,
      "gatekeeperAssess": false,
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.inherit.plist",
      "type": "distribution",
      "icon": "./build/icon512"
    },

**Comment by comountainclimber** [comment]
> Its turns out the missing entitlement is
> com.apple.security.cs.allow-dyld-environment-variables
> It seems to working fine afterwards

I added this entitlement but the paths are still empty strings... anyone have any idea how to resolve this while still keeping hardenedRuntime
