### ISSUE TITLE
Electron 6.0.10 with Electron builder 21.2.0 Mac app crashes right launch.

### ISSUE THREAD

**Issue by ash67** [electron-userland/electron-builder#4272]
* **Version**:  21.2.0

* **Target**: dmg, zip

* **Electron**: 6.0.10
* **Mac Version**: 10.14.6

My electron app builds successfully but it crashes right I launch it. 

I checked logs in console.app. Here are some of the errors 

```Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Volumes/myapp/myapp.app/Contents/, NSFilePath=/Volumes/my app/my app.app/Contents/PlugIns, NSUnderlyingError=0x7fd4f2c57660 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}```

```
CODE SIGNING: process 7544[My App]: rejecting invalid page at address 0xce885fc2000 from offset 0x0 in file "<nil>" (cs_mtime:0.0 == mtime:0.0) (signed:0 validated:0 tainted:0 nx:0 wpmapped:1 dirty:0 depth:0)
```

```
Unable to load Info.plist exceptions (eGPUOverrides)
```
Funny thing is that I do have info.plist file in my package. I could see here

![image](https://user-images.githubusercontent.com/22991045/65704191-0fe43700-e054-11e9-88cc-c9eaa6d1e51d.png)

I tried the below fix but I had no luck with it.

https://github.com/electron-userland/electron-builder/issues/4151#issuecomment-520663362

Please guide me on how to fix this problem.

**Comment by oNaiPs** [comment]
@ash67 did you figure out how to fix this?

**Comment by ash67** [comment]
@oNaiPs  

I fixed the issue after I notarized my app. The below guides help me a lot:

https://help.apple.com/xcode/mac/current/#/dev033e997ca

https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db
