### ISSUE TITLE
Documentation request: generic update server requirements

### ISSUE THREAD

**Issue by matsev** [electron-userland/electron-builder#4275]
The [GenericServerOptions](https://www.electron.build/configuration/publish#genericserveroptions) paragraph of the Publish documentation contains information about information that is for the electron builder configuration, but it lacks information about what is required on the server side. Please consider add some general guide lines about what is required on the server side, e.g. is a static file server enough, what files needs to be uploaded, what are the purpose of each file, etc.

**Comment by gemma-ferreras** [comment]
I am looking also for this documentation. Did you find it?

**Comment by matsev** [comment]
@gemma-ferreras I am afraid I don't have more information regarding this matter. In the end, our product owner decided that it was ok to publish our application to a static S3 bucket.
