### ISSUE TITLE
How to disable packing into asar files?

### ISSUE THREAD

**Issue by ahgan84** [electron-userland/electron-builder#428]
Hi guys, i notice that after we installed the app fr the installer, our html sources files are all pack into app. asar and electron. asar. May i know is there a way to open it or not pack our source file into asar? This is because for maintenance convenience, we sometimes need to modify the html coding at the spot..

**Comment by gamestailer94** [comment]
just add asar: false under build in you dev `package.json`
see https://ci.appveyor.com/project/gamestailer94/quest-editor/build/1.0.54#L330

**Comment by develar** [comment]
You should use asar because 

* Windows io is very poor —app start up time
* You must not (yes, must) modify app files after installation — code signing. Please use standard system locations to store user config.

**Comment by ahgan84** [comment]
@develar , u mean if i disable the asar, it wil take longer time for my app to start up?

Can u explain more on what is code signing? And what is standard system location to store user config?

**Comment by develar** [comment]
> what is code signing

https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx

> And what is standard system location to store user config?
https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname  see userData

**Comment by ahgan84** [comment]
I know that code signing is for security purposes but my app won't be distributing online. It will only be used privately.
