### ISSUE TITLE
Electron Builder 21.x.x signs every dll in win-unpacked?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#4283]
* **Version**:  `21.2.0`

* **Target**: Windows

Is this intentional and necessary, or something that can be configured? Every included vendor dll in a native dependency in `win-unpacked` is signed now, increasing the build time from about 120 seconds to 426 seconds.

**Comment by Slapbox** [comment]
Still relevant. Can anyone explain why the change in behavior? Builds take way, _way_ longer.

**Comment by Slapbox** [comment]
Seems to be resolved.

**Comment by Slapbox** [comment]
Issues persists in `22.3.2`

I assume this unavoidable, but it wasn't the case in prior versions and I'm not aware of any Windows security changes that would necessitate it. 

If anyone can speak to this, I'd really like to know. It kind of does suck for builds to take 8 minutes, instead of 2. Other than that, <3 Electron-Builder.

**Comment by Slapbox** [comment]
Still relevant.

**Comment by Slapbox** [comment]
Forever relevant.

**Comment by adriendurepaire** [comment]
#4728

**Comment by adriendurepaire** [comment]
Seems to be related to #4728

**Comment by Slapbox** [comment]
Issue seems to be resolved in latest.
