### ISSUE TITLE
Don´t throw error if Release is not a Draft and build triggered by Tag

### ISSUE THREAD

**Issue by gamestailer94** [electron-userland/electron-builder#429]
See:
https://ci.appveyor.com/project/gamestailer94/quest-editor/build/1.0.54#L330
https://travis-ci.org/gamestailer94/quest-editor/jobs/132003730#L835

Built was started because draft was saved (tag created)

Maybe just note it.

**Comment by develar** [comment]
Yeah, it is known issue.

Consider do not trigger builds for tags in any case:

```
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
```

(https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml#L48)

**Comment by develar** [comment]
We must not throw error (just a warning) if there are `TRAVIS_TAG` or `APPVEYOR_REPO_TAG` or `CIRCLE_TAG`
