### ISSUE TITLE
macOS: How to upload pkg without Application Loader

### ISSUE THREAD

**Issue by semireg** [electron-userland/electron-builder#4293]
* **Target**: macOS

I couldn't find any help on how to upload the resulting pkg file to App Store Connect with Xcode 11 because, well, Application Loader is no longer available.

This project may want to include basic instructions on how to perform this step, or even integrate the script's below into publish options of electron-builder.

Step 1: Create and Download New Key
![2019-10-05 at 1 21 PM](https://user-images.githubusercontent.com/1819762/66259167-70b9f080-e773-11e9-9af3-7099c8581e55.png)

Take note of `Issuer ID` and `Key ID`

Step 2: Save the downloaded key to this local folder:
```
mkdir -p ~/.appstoreconnect/private_keys
mv ~/Downloads/AuthKey_J7AABCDEFG.p8 ~/.appstoreconnect/private_keys/
```

Step 3: Use atool command to upload pkg.
```
xcrun altool --upload-app -f release/mas/My-App-X.Y.Z-BUILD.pkg --apiKey J7AABCDEFG --apiIssuer 69A-BCDEFGHI-JKLMNOPQR-STUVWXYZ-4d1
```

I hope this saves some time for others looking to do the same.

**Comment by alicerunsonfedora** [comment]
Looks like you can also use Transporter on the App Store: https://apps.apple.com/us/app/transporter/id1450874784?mt=12
