### ISSUE TITLE
What is blocking a new version?

### ISSUE THREAD

**Issue by tom-james-watson** [electron-userland/electron-builder#4296]
There are a couple of fixes that are on `master` that I'm waiting to be released as a new version. Is there anything blocking the publishing of a new version?

Thanks!

**Comment by TanninOne** [comment]
#3185 should have blocked every release of the last 18 months or so as they are all fundamentally broken. But eh, who cares. Nothing matters.

**Comment by tom-james-watson** [comment]
Looks like a new version has been published - thanks devs!
