### ISSUE TITLE
Update node (and yarn) version in docker image, e.g. for ESLint >6.x.x 

### ISSUE THREAD

**Issue by iaktern** [electron-userland/electron-builder#4298]
* **Version**: the current _electronuserland/builder:wine_ image (but this concerns most other _builder_ images as well, e.g. _builder:latest_)

* **Target**: 

The installation of my projects dependencies fail, because I'm using ESLint 6.5.1 and this seems to need at least Node version >=11.10.1 (the image has 11.10.0 installed)

![grafik](https://user-images.githubusercontent.com/12514017/66391589-ca1d5c00-e9cd-11e9-97aa-bb82f4b4d261.png)

(Also yarn seems to be a little bit outdated.)

**Comment by trabek** [comment]
Is there some easy workaround? I am using create-react-app, so the ESLint version is not specified by me.

**Comment by sapkra** [comment]
@trabek Just build the docker image yourself and publish it to docker hub. You have to change the base images of the Dockerfiles and inside the `docker/build.sh` to your one.

**Comment by trabek** [comment]
> @trabek Just build the docker image yourself and publish it to docker hub. You have to change the base images of the Dockerfiles and inside the `docker/build.sh` to your one.

I'll try that. Thank you.

**Comment by trabek** [comment]
ended up using `yarn --ignore-engines` as workaround

**Comment by andrew-pyle** [comment]
What's stopping this docker image from using one of the active LTS versions of node? v10 or v12 https://nodejs.org/en/about/releases/

**Comment by hariharan888** [comment]
Any updates!

**Comment by sapkra** [comment]
In the next release there will be a change in the docker images. I hope they will be built and pushed to Dockerhub. @develar

**Comment by keepitsimple** [comment]
Long waiting change. Is it possible to make a ENV NODE_VERSION=11.10.0 overwritable from outside?

**Comment by keepitsimple** [comment]
> What's stopping this docker image from using one of the active LTS versions of node? v10 or v12 https://nodejs.org/en/about/releases/

Yes it's weird choice to use version 11.x instead of LTS
