### ISSUE TITLE
Application Loader and ERROR ITMS-90237

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#430]
Hi,

I try to send my application with application loader,

but I have an error : 

`ERROR ITMS-90237: the product archive package's signature is invalid. Ensure that it is signed with your "3rd party mac developer installer" certificate`

My package.json

```
    "osx": {
      "title": "MyApp",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "target": "mas",
      "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)",
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "mas": {
      "identity": "Jeremie Chazelle"
    }
```

I tried to replace 

` "identity": "Developer ID Application: Jeremie Chazelle (XXXXXXXXXX)",`
by
`"identity": "3rd Party Mac Developer Installer: Jeremie Chazelle (XXXXXXXXXX)",`

but I have an error when I launch the build : 

Error: Command failed: codesign --sign 3rd Party Mac Developer Installer: Jeremie Chazelle (XXXXXXXXXX) -fv --entitlements /Users/jeremiechazelle/Sites/my-app/node_modules/electron-osx-sign-tf/default.mas.inherit.entitlements /Users/jeremiechazelle/Sites/my-app/dist/MyApp-mas-x64/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
3rd Party Mac Developer Installer: Jeremie Chazelle (XXXXXXXXXX): this identity cannot be used for signing code

Do you have an idea ?

**Comment by develar** [comment]
No. I have no idea. For some reason proper MAS installer certificate is not found. Something is wrong with your cert.

**Comment by ajaycallhippo** [comment]
I have also facing this issue. 

ITMS-90237: The product archive package's signature is invalid. Ensure that it is signed with your '3rd Party Mac Developer Installer' certificate.
