### ISSUE TITLE
Updater not updating

### ISSUE THREAD

**Issue by stevenroussey-privicy** [electron-userland/electron-builder#4300]
* **Version**:  electron-builder  version=21.2.0 os=18.7.0 electron-updater=4.1.2
* **Target**: macos

Building for macos, and have the app working fine, signed and notarized. Using GitHub to host the release. At some point auto-updater was working fine, but I see that it is not working now. 

It finds the update just fine. It downloads it. I find the file in the Cache (\~/Library/Application Support/Caches/privicy-pal-updater/pending/PrivicyPal-0.1.12-mac.zip) as a zip and here (\~/Library/Caches/com.privicy.pal.ShipIt/update.FVpudS6/PrivicyPal.app). 

I have added logs, to log level silly:
```
[2019-10-08 14:20:08.121] [info] Checking for update
[2019-10-08 14:20:10.077] [info] Found version 0.1.12 (url: PrivicyPal-0.1.12-mac.zip, PrivicyPal-0.1.12.dmg)
[2019-10-08 14:20:10.079] [info] Downloading update from PrivicyPal-0.1.12-mac.zip, PrivicyPal-0.1.12.dmg
[2019-10-08 14:20:10.082] [debug] updater cache dir: /Users/steven.roussey/Library/Application Support/Caches/privicy-pal-updater
[2019-10-08 14:20:10.311] [info] Update has already been downloaded to /Users/steven.roussey/Library/Application Support/Caches/privicy-pal-updater/pending/PrivicyPal-0.1.12-mac.zip).
[2019-10-08 14:20:10.479] [info] / requested
[2019-10-08 14:20:10.483] [info] /1570569610312-5606.zip requested
[2019-10-08 14:20:10.483] [info] /1570569610312-5606.zip requested by Squirrel.Mac, pipe /Users/steven.roussey/Library/Application Support/Caches/privicy-pal-updater/pending/PrivicyPal-0.1.12-mac.zip
[2019-10-08 14:20:34.450] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/privicy/privicypal-releases/releases/download/v0.1.12/PrivicyPal-0.1.12-mac.zip)
```

But no errors. 

The app does not update. Code here:

```
  autoUpdater.on('update-downloaded', (event) => {
    updateProgress('progress.appupdater.update-downloaded', 100);
    const response = dialog.showMessageBoxSync(ApiMain.getUserInterface(), {
      type: 'question',
      buttons: ['Now', 'Later'],
      defaultId: 0,
      message: `Version ${event.releaseName} is available, do you want to install it now?`,
      title: 'Update available',
    });

    if (response === 0) {
      // required for timing issue
      setImmediate(() => {
        // prevent close handlers from quitting on window close
        app.removeAllListeners('window-all-closed');
        const browserWindows = BrowserWindow.getAllWindows();
        browserWindows.forEach(function(browserWindow) {
          browserWindow.removeAllListeners('close');
        });
        autoUpdater.quitAndInstall();
      });
    }
  });
```

I kick things off like this:
```
  const checker = () => {
    autoUpdater.checkForUpdatesAndNotify();
    setTimeout(checker, 8 * 3600 * 1000);
  };
  setTimeout(checker, 15000);
```

The update will not install when quitting, and it will not install via `quitAndInstall`, and it shows no error messages anywhere I can find.

**Comment by stevenroussey-desiclabs** [comment]
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/MacUpdater.ts :
```
export class MacUpdater extends AppUpdater {
  private readonly nativeUpdater: AutoUpdater = require("electron").autoUpdater
  ...
  quitAndInstall(): void {
    this.nativeUpdater.quitAndInstall()
  }
}
```

**Comment by stevenroussey-desiclabs** [comment]
https://github.com/electron/electron/blob/master/shell/browser/auto_updater_mac.mm#L165 it looks like `relaunchToInstallUpdate` which leads to https://github.com/Squirrel/Squirrel.Mac/blob/b5ce589c4ca5d61388f555a8fd4a7705a114e427/Squirrel/SQRLUpdater.m#L737

**Comment by stevenroussey-desiclabs** [comment]
I installed XCode, attached to my process, and created a symbolic breakpoint for relaunchToInstallUpdate. Indeed it stops, but it is all assembly. :(

**Comment by jsheffers** [comment]
What was the fix here?  Having a similar issue

**Comment by twohappy** [comment]
I got a similar issue since upgrade electron-builder from 20.36.2 to 22.3.2.
the .zip file is downloaded and when the app restarted, nothing happened.

I also got a error message 
```javascript
{
  "code": -1,
  "domain": 'SQRLCodeSignatureErrorDomain'
}
```
it turned out that package inside dmg is not signed by default after certain version of electron-builder.

**Comment by johnryan** [comment]
@twohappy Can you share what you changed in order to get code signing to work?

**Comment by twohappy** [comment]
@johnryan 
It's too long so can't remember what i did. 
I was likely intended to add some hash to version code and the builder failed to parse it. 
the problem was related with some configs inside package.json or somewhere else. 
check the version code or non english characters. 
when packaging, the builder parsing version code under windows and darwin seems to be different. One can work, the other can not.
