### ISSUE TITLE
How to only change release name to electron app

### ISSUE THREAD

**Issue by magaya-rherranz** [electron-userland/electron-builder#4303]
My product name contain spaces. The installer name is correct but I want to remove the spaces in the executable (app name).
I used relaseinfo and it is not working for me.
Any help, pelase

**Comment by idanwork** [comment]
Hi maybe this is what you are looking for?

In the package.json define: 
```JSON
"productName":"NameWithoutSpace"
```
And the installer's artifcat define name with spaces (example for windows' NSIS)
```JSON
"nsis": {
  "artifactName":"Name With Space Setup ${version}.${ext}"
}
```

I haven't actually tried that
