### ISSUE TITLE
How to make .full-nupkg?

### ISSUE THREAD

**Issue by mydansun** [electron-userland/electron-builder#431]
I run this command `npm run pack` and I only get the dist folder with my unpackaged app

I was a novice, I hope someone can help me.

**Comment by develar** [comment]
See step 4: https://github.com/electron-userland/electron-builder#in-short

> And then you can run npm run pack or npm run dist (to package in a distributable format (e.g. dmg, windows installer, deb package)). Both scripts are the same because If script named dist or name has prefix dist:, flag --dist is implied.

**Comment by develar** [comment]
Related: https://github.com/electron-userland/electron-builder/issues/413
