### ISSUE TITLE
autoUpdate failed in Windows

### ISSUE THREAD

**Issue by Senasiko** [electron-userland/electron-builder#4312]
* **Version**: 20.39.0

version of electron-updater: 4.1.2

building for: windows

When I have a new release, autoUpdate is  succeed in Mac. But failed in windows.
the result is that the app was quitted, and the folder what app installed was cleaned, and the new release was downloaded in `...\app-updater\pending\`.
In the 'update-download' event  callback, I execute `autoUpdater.quitAndInstall(true, true);` then in `NsisUpdater.js` `function doInstall()`, I logged the Info like
```
    this._logger.info('updater process', this.installerPath, args);
    this._logger.info('updater options', options);
```
the info is 
```
update process undefined [ '--updated', '/S', '--force-run' ]
updater options { installerPath:
   'C:\\Users\\Administrator\\AppData\\Local\{appName}-updater\\pending\\{appName}.exe',
  isSilent: true,
  isForceRunAfter: true,
  isAdminRightsRequired: false }
```
nsis config info 
```
   "nsis": {
      "artifactName": "${productName}.${ext}",
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true
    },
```
So I want to know what should I do?

**Comment by kaitlynbrown** [comment]
I'm having the same problem.
Is there a reason the issue is closed? Were you able to find a solution?

**Comment by Senasiko** [comment]
> I'm having the same problem.
> Is there a reason the issue is closed? Were you able to find a solution?

I solved my problem by changing `nsis.artifactName` in `package.json`.
Because artifact's name is same with app name, so the installer will not execute.

**Comment by DominikLevitsky** [comment]
@Senasiko We are having exactly the same issue, as mentioned above. What have you changed the artifact name to? We are currently using `"artifactName": "${productName}-${version}.${ext}"`. Can you provide your nsis settings, please?

**Comment by Senasiko** [comment]
@DominikLevitsky I just change `${productName}.${ext}` to `"${productName}_setup.${ext}"`. If your issue is same with mine, your change should solve it.

**Comment by DominikLevitsky** [comment]
@Senasiko Thank you for the answer, but this did not help. It seems we have a different issue there.
