### ISSUE TITLE
Got error code 15 in electron-winstaller-fixed\vendor\zip-x64.exe

### ISSUE THREAD

**Issue by crashbell** [electron-userland/electron-builder#432]
I'm trying to make a build for Windows. All required environments were set up, everything worked well with `electron-builder` `2.x` but when we attempted to use `3.25.0` we always suffer a problem with `zip-x64` (we tried with 2 Windows machines but no luck).

Build in `package.json`
```JSON
  "build": {
    "osx": {
      "title" : "Sample",
      "contents": [
        {"x": 522, "y": 250, "type": "link", "path": "/Applications"},
        {"x": 124, "y": 250, "type": "file"}
      ]
    },
    "win": {
      "title" : "Sample",
      "msi": true
    }
  }
```

Gulp function

```js
import builder from 'electron-builder'
const buildAsync = BPromise.promisify(builder.build.bind(builder))
async function createInstaller() {
  await buildAsync({
    platform: process.platform,
    devMetadata: {
      build: {
        asar: false,
        name: AppConfig.productName,
        ignore: new RegExp(
          '^/((src)|(\\..+)|(webpack.+)|(gulpfile.+)|(installer.nsi.tpl)|' +
          '(README\\.md)|(test)|(coverage)|' +
          '(dist)|' + // don't include the other build outcome which runs in parallel
          '(node_modules/babel)|' +
          '(node_modules/eslint)|' +
          '(node_modules/radium/node_modules/babel-(.*))|' +
          '(node_modules/material-ui/src)|' +
          '(node_modules/isparta)|' +
          '(node_modules/gulp-istanbul)|' +
          '(node_modules/webpack)|' +
          '(node_modules/webpack-dev-server)|' +
          '(node_modules/node-sass)|' +
          '(node_modules/css-loader)|' +
          '(node_modules/roboto-fontface))$')
      }
    }
  })
}
```

Error log: https://gist.github.com/crashbell/1c9c095b5faed387469e4d6e9a98889e

__node v5.7.0__
__npm v3.9.0__

**Comment by develar** [comment]
> 15	Zip could not open an output file (typically the archive) for writing.

Please set env `DEBUG=electron-windows-installer` to get debug output.

**Comment by crashbell** [comment]
<img width="653" alt="screen shot 2016-05-23 at 6 08 16 pm" src="https://cloud.githubusercontent.com/assets/810139/15468955/636cb34e-2111-11e6-9d2e-04d292a05b6f.png">

@develar this is what I got. I have no idea about missing `desktop-1.0.0-full.nupkg`

**Comment by develar** [comment]
It seems you use scoped name, right? `@kobiton`? And name in the your app package.json is scoped (please specify)?

**Comment by crashbell** [comment]
@develar Yes I do. I have some libs installed from my private repo, could it be the problem?

**Comment by develar** [comment]
@crashbell Scoped names not supported in all tools — electron-packager and original (not only our fork) windows-installer. You don't need to use scoped name for your electron app since you will never publish it to npm registry. So, just remove scope name.

**Comment by crashbell** [comment]
the name in my `package.json` is like
```
{
  "name": "@scope/desktop",
}
```
It seems to cause the path problem. I changed it to a normal name, let's see if the problem will be solved.

**Comment by crashbell** [comment]
It passed the zip issue, I struggle with another:
<img width="640" alt="screen shot 2016-05-23 at 6 25 19 pm" src="https://cloud.githubusercontent.com/assets/810139/15469329/cbd2685a-2113-11e6-9c11-53a10cb0c56d.png">

But it seems to be not the same problem, so I'm gonna close this issue and investigate this. 

@develar thanks a lot!

**Comment by develar** [comment]
Reopened — I am tired to answer about scoped name and it should be supported (just remove prefix).

**Comment by develar** [comment]
> But it seems to be not the same problem

Ensure that your description in the package.json is set to nn-empty value.
