### ISSUE TITLE
Snapcraft stuck after launching a VM

### ISSUE THREAD

**Issue by NorbertBodziony** [electron-userland/electron-builder#4320]
* **Version**: 21.2.0

* **Target**: Snap
* **System**: Ubuntu 16.04

When creating app with additional statePackages:
` "snap": {
      "stagePackages": [
        "default",
        "build-essential",
        "wget",
        "libgomp1",
        "gcc-6",
        "libc6-dev"
      ]
    }`
snap is build inside multipass VM but after launching it hangs.
After running top inside VM i see 90% CPU on sshd process.

**Comment by shturnev** [comment]
Similarly. Ubuntu 19.04

**Comment by krsriq** [comment]
Same problem on Ubuntu 19.10.
