### ISSUE TITLE
[mas] notarised app giving error on launch

### ISSUE THREAD

**Issue by taher** [electron-userland/electron-builder#4325]
* **Version**: 
21.2.0

* **Target**: 
mas, dmg

![image](https://user-images.githubusercontent.com/79488/66882933-d87d0080-efe9-11e9-809a-835ceef1ab58.png)

".B4X8EQS24E.to.go.osx.PKI44C" cannot  be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

we have successfully notarized the pkg file before upload.

**Comment by taher** [comment]
I think that this binary is unpacked at load time from app.asar .

*. Should smartUnpack have not packed this executable

*. Should it also have been code signed before packaging

**Comment by james-criscuolo** [comment]
Over in issue #4040 they came to the conclusion that you need to add all of your native dependencies to `asarUnpack` for the app store. It's unclear if that step directly relates to your message, but it's seemingly a required step now that Catalina is released.

**Comment by JohnTendik** [comment]
I believe mas builds shouldnt be notarized. Only standalone versions (non app store) builds should be notarized as the notarization step happens when you upload your mas build to the app store.
