### ISSUE TITLE
Trying to setup a 'offline' build environment using ELECTRON_BUILDER_CACHE produces error

### ISSUE THREAD

**Issue by torlenor** [electron-userland/electron-builder#4326]
* **Version**: 21.2.0

* **Target**: Linux x64 (deb, rpm, AppImage)

We would like to be able to perform builds in an offline environment. For that we tried setting the env ELECTRON_BUILDER_CACHE variable and perform an "online" build first to generate the cache (following the steps in issue https://github.com/electron-userland/electron-builder/issues/3208), but it ends with the error

```
$ ELECTRON_BUILDER_CACHE=vendor/electron-builder electron-builder
  • electron-builder  version=21.2.0 os=4.15.0-65-generic
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • description is missed in the package.json  appPackageFile=/home/user/development/sandbox/ares/gui_poc_electron/app/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=6.0.11 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/siminspector-0.0.1.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • default Electron icon is used  reason=application icon is not set
  • building        target=deb arch=x64 file=dist/siminspector_0.0.1_amd64.deb
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=9.378s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
    p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (906E9),ASM,AES-NI)
    
    Scanning the drive for archives:
    
                    errorOut=
    ERROR: No more files
    vendor
    
    
    
    System ERROR:
    Unknown error -2147024872
    
                    command=/home/user/development/sandbox/ares/gui_poc_electron/app/node_modules/7zip-bin/linux/x64/7za x -bd vendor/electron-builder/fpm/272238164.7z -ovendor/electron-builder/fpm/272238164
                    workingDir=vendor/electron-builder/fpm
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The content of the cache directory after this error is

```
vendor/electron-builder/appimage:
appimage-12.0.1

vendor/electron-builder/fpm:
040185139  040185139.7z  272238164  272238164.7z
```
When we don't set the env variable the builds works flawlessly.

**Comment by torlenor** [comment]
Bump (still in issue)

**Comment by cryptomilk** [comment]
Still an issue ...

**Comment by cryptomilk** [comment]
@torlenor Could you try with:

```
export ELECTRON_BUILDER_CACHE=$(pwd)/vendor/electron-builder
electron-builder
```

**Comment by torlenor** [comment]
Sorry, still an issue, but I was not able to try that, yet.

**Comment by cryptomilk** [comment]
Still an issue ...

**Comment by irfancnk** [comment]
Still an issue

**Comment by advaithm** [comment]
yup this is broken. it doesn't respect the env var

**Comment by mmaietta** [comment]
Has anyone actually tried this suggestion? It'd at least confirm whether relative and/or absolute paths are viable
https://github.com/electron-userland/electron-builder/issues/4326#issuecomment-586291523

Anyways, the error looks to be here:
`-ovendor/electron-builder/fpm/272238164`
There's no space in between `-o` and "vendor"

That being said, I can't find that code anywhere in the latest version of electron-builder ^22.11. The only place `7za` args are used are using "a" command, and not "x" as your console logging shows (`...7zip-bin/linux/x64/7za x -bd ...`)
https://github.com/electron-userland/electron-builder/search?q=debug7zargs

Happy to review any PR for a fix. Local dev env is fairly easy to set up:
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
But someone please confirm this issue exists on the latest electron-builder because the code error logged is no longer present in the codebase.

**Comment by advaithm** [comment]
> Has anyone actually tried this suggestion? It'd at least confirm whether relative and/or absolute paths are viable
> [#4326 (comment)](https://github.com/electron-userland/electron-builder/issues/4326#issuecomment-586291523)
> 
> Anyways, the error looks to be here:
> `-ovendor/electron-builder/fpm/272238164`
> There's no space in between `-o` and "vendor"
> 
> That being said, I can't find that code anywhere in the latest version of electron-builder ^22.11. The only place `7za` args are used are using "a" command, and not "x" as your console logging shows (`...7zip-bin/linux/x64/7za x -bd ...`)
> https://github.com/electron-userland/electron-builder/search?q=debug7zargs
> 
> Happy to review any PR for a fix. Local dev env is fairly easy to set up:
> https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
> But someone please confirm this issue exists on the latest electron-builder because the code error logged is no longer present in the codebase.

I've set absolute path, it didn't work

**Comment by calarin** [comment]
I am also trying to set up an 'offline' build and this would definitely help.

**Comment by advaithm** [comment]
for electron you need `ELECTRON_CACHE` and `ELECTRON_SKIP_BINARY_DOWNLOAD` set I have no idea how everything else works, I've hacked around the issue in flatpaks by setting target to dir
