### ISSUE TITLE
Version mismatch Issue

### ISSUE THREAD

**Issue by simonlast** [electron-userland/electron-builder#433]
I'm trying to build an electron app using electron builder. It seems to work, but the 'paste' event isn't being handled in the electron-builder version. It does work when I use the 'electron' command.

I took a screenshot of the behavior here:
(On the left is the electron-builder version, with no paste event. On the right is the 'electron' version. Both are running the same version of electron.)

![image](https://cloud.githubusercontent.com/assets/1704018/15486695/6a152ac4-20fc-11e6-9179-71e41d15aeb1.png)

These are the command line arguments I am using:

		--platform, darwin,
		--arch all
		--version 1.1.1
		--out ./build/static/desktop
		--overwrite
		--icon ./build/static/icon.icns

**Comment by develar** [comment]
It seems you use old electron-builder version? Because `--icon`, `--overwrite`, `--out` and `--version` is not a CLI args in the 3.x ?

**Comment by simonlast** [comment]
Oops, I put this issue on the wrong package! I got confused between electron builder and packager... 😬

**Comment by simonlast** [comment]
OK, so I switched to using electron-builder, and still get the same issue.

It builds and runs properly, and displays the same version as if I had run it from 'electron', but clipboard events do not fire in the browser (copy, paste, etc.)

My code:

	builder.build({
		platform    : [builder.Platform.OSX],
		devMetadata : {
			build: {
				"app-bundle-id"     : "notion.id",
				"app-category-type" : "Productivity"
			},
			directories: {
				"app"            : "build/desktop",
				"output"         : "build/static/desktop",
				"buildResources" : "build/static"
			},
		}
	})
	.then(() => {
		// handle result
		callback()
	})
	.catch((error) => {
		// handle error
		callback(error)
	})

**Comment by simonlast** [comment]
I figured it out. It turns out I wasn't creating the menu properly.
