### ISSUE TITLE
Error building DMG target on macOS 10.15 after 21.2.0 upgrade

### ISSUE THREAD

**Issue by alexlyp** [electron-userland/electron-builder#4330]
* **Version**: 
21.2.0

* **Target**: 
Mac/Dmg

After having issues with 10.15 macOS I read this previous issue here: https://github.com/electron-userland/electron-builder/issues/3990

I updated to 21.2.0 and and receive the following error: 
`/bin/sh: build: command not found`

My package.json is as follows for the macOS dmg target:
`"build": {
    "dmg": {
        "contents":  [
            {
               "x": 130,
               "y":  220,
             },
             {
                "x": 410,
                "y": 220,
                "type": "link",
                "path":  "/Applications"
              }
          ]
      }
}`

Are there additional configuration steps that I'm missing? I'm getting the same error when removing the dmg build and simply doing a `"mac": { "target": "pkg" }` instead.

**Comment by DoomyTheFroomy** [comment]
They removed/changed the build script, you will just have to change your call to `./node_modules/.bin/electron-builder build` + [your options]

**Comment by alexlyp** [comment]
Awesome that did the trick, thanks for the help!
