### ISSUE TITLE
Building fails with: Error: Exit code: ENOENT. spawn prlctl ENOENT

### ISSUE THREAD

**Issue by andreborud** [electron-userland/electron-builder#4333]
* **Version**:  21.2.0
* **Electron updater**: 4.1.2
* **Target**: mac & win
Electron 6.0.12 & Node 12.4.0

Trying to build for win and mac (on a mac with Catalina) manages to build some of the files but the fails here:
```
% electron-builder build --mac --win
  • electron-builder  version=21.2.0 os=19.0.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=desktop-releases/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=6.0.12 appOutDir=desktop-releases/mac
  • signing         file=desktop-releases/mac/App.app identityName=************
  • building        target=macOS zip arch=x64 file=desktop-releases/App-mac.zip
  • building        target=DMG arch=x64 file=desktop-releases/App-0.3.16.dmg
  • packaging       platform=win32 arch=x64 electron=6.0.12 appOutDir=desktop-releases/win-unpacked
  • building        target=nsis file=desktop-releases/App Setup 0.3.16.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=desktop-releases/App-0.3.16.dmg.blockmap
  • building embedded block map  file=desktop-releases/App-0.3.16-mac.zip
  ⨯ Exit code: ENOENT. spawn prlctl ENOENT  stackTrace=
                                                        Error: Exit code: ENOENT. spawn prlctl ENOENT
                                                            at /Users/andreborud/.nvm/versions/node/v12.4.0/lib/node_modules/electron-builder/node_modules/builder-util/src/util.ts:125:16
                                                            at exithandler (child_process.js:297:5)
                                                            at ChildProcess.errorhandler (child_process.js:309:5)
                                                            at ChildProcess.emit (events.js:200:13)
                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)


                                                            at onErrorNT (internal/child_process.js:456:16)
                                                            at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

is this a config error or something else?

**Comment by roby65** [comment]
Catalina doesn't support 32bit anymore, so compiling Win32 is not possible anymore.
As a workaround, I am using a VM with Win10 to compile it.

**Comment by andreborud** [comment]
Update: The building error is only when building for Windows.

@roby65 even though Catalina doesn't support 32bit anymore, shouldn't it be able to build for Win 64bit? Adding the --x64 flag with building for Win produces the same error. But thanks for the tip, I will try to build it on my windows machine. But it would be nice to build for all platforms with one command.

**Comment by roby65** [comment]
AFAIK wine, used to build for Win, is 32bit, so it doesn't work

**Comment by andreborud** [comment]
I see, that would break it!

**Comment by Annihil** [comment]
[Potential solution using docker](https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-541099759)

**Comment by dmtask** [comment]
I have the same Problem. The Docker Solution does not work help me, because it is a 32Bit Installtion and my 64bit Files crashed... :(

**Comment by muhzi4u** [comment]
@dmtask Any luck ?

**Comment by muhzi4u** [comment]
@muhzi4u I am also waiting. We are facing a lot of challenges, after updating to `Catalina`.

**Comment by dmtask** [comment]
No, I'm afraid not. Under MacOS he no longer takes the Developer certificate and refuses to start the app. But building is possible.

**Comment by dmtask** [comment]
@muhzi4u 
I was able to solve the startup problem under MacOS with the help of https://github.com/electron/electron-osx-sign.

You have to sign the app and it is important that the option "hardened-runtime" is enabled. Under MacOS 10.15.x this is mandatory.

**Comment by Zophyr** [comment]
Try this: https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-559138959

**Comment by reddybhavanish** [comment]
Facing the same issue while building the app using Circle CI tool. Any leads to proceed further? Any help is much appreciated?
