### ISSUE TITLE
NSIS Generated installer stuck

### ISSUE THREAD

**Issue by ivictbor** [electron-userland/electron-builder#4335]
* **Version**:  21.2.0

* **Target**: nsis

```
    "nsis": {
      "artifactName": "${productName}Setup-${os}.${ext}"
    },
```

![image](https://user-images.githubusercontent.com/1838656/67151174-7282c880-f2ca-11e9-86ab-de6f653c2e73.png)

Windows 10. On 2 PCs it worked fine, on third it always stuck.
Tried:
- rebooingt PC
- disabling antivirus and firewall.
- runing from cmd to see some errors, control returned immediately, no output
- runing from admin

Could you please advice steps to troubleshoot or find/enable some logs

**Comment by martinvergara26** [comment]
Same problem here
