### ISSUE TITLE
`update-desktop-database` might not be installed, but is used by Debian postinst scripts

### ISSUE THREAD

**Issue by strugee** [electron-userland/electron-builder#4341]
* **Version**: 21.2.0; I have confirmed via source code inspection that this is still an issue

* **Target**: Debian package

Installing Signal Desktop on a _very_ minimal Debian installation results in a warning in the postinstall script about `update-desktop-database` not being installed. Do all electron-builder apps install `.desktop` files to `/usr/share/applications`? Because if so this functionality would be completely covered by dpkg hooks and we could just delete the offending line. If not I'm not entirely sure what to do here (maybe just redirect stderr to `/dev/null`?)

**Comment by explosivose** [comment]
we have also noticed this with users on very minimal debian installations

**Comment by skybert** [comment]
This bug is still relevant, just saw this one on my system:
```
$ grep PRETTY /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```

The remedy both for `electron-builder` and me is simple, of course:
```
~ $ apt-file search update-desktop-database
desktop-file-utils: /usr/bin/update-desktop-database
desktop-file-utils: /usr/share/man/man1/update-desktop-database.1.gz
~ $ dpkg -l desktop-file-utils            
dpkg-query: no packages found matching desktop-file-utils
```
It's still good to iron out these minor issues to make the user experience of installing packages (`signal-desktop` in my case), better.

**Comment by alx696** [comment]
Change after-install.tpl can solve the problem. example:

https://github.com/alx696/polong-desktop/commit/02a41aca3f4b93719115ee8a43463393e418a307
