### ISSUE TITLE
Auto Updater not working with Linux AppImage

### ISSUE THREAD

**Issue by travis5491811** [electron-userland/electron-builder#4349]
Electron Builder:
* **21.2.0**:  Via `vue-cli-plugin-electron-builder 1.4.0`

Electron Updater
v4.1.2

Target
* **Linux**: 

Hello, Electrons auto updater is working good on Windows. But it does not work at all on Linux AppImage. `autoUpdater.checkForUpdates();` seems to do nothing in Linux. I'm even building for Windows and Linux from a Linux machine and the auto-updater doesn't work for the Linux AppImage.

If this is by design can you point me to the relevant documentation?

Am I suppose to be doing something different to auto-update when using Linux (Mint or Ubuntu)?

**Comment by travis5491811** [comment]
> Currently, only macOS and Windows are supported. There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution's package manager to update your app.

[Ref](https://electronjs.org/docs/api/auto-updater)

**Comment by FedericoCeratto** [comment]
https://www.electron.build/auto-update#auto-updatable-targets  lists "Linux: AppImage"

**Comment by sarathms** [comment]
> > Currently, only macOS and Windows are supported. There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution's package manager to update your app.
> 
> [Ref](https://electronjs.org/docs/api/auto-updater)

This links to the `autoUpdater` provided by `electron` which is different from the one provided by `electron-builder` here. The link in the previous comment should help.
