### ISSUE TITLE
Large app fails to build for Windows

### ISSUE THREAD

**Issue by rasmuswoelk** [electron-userland/electron-builder#4353]
* **Version**: 21.2.0

* **Target**: Windows

* **Building on**: Mac/Linux
<hr />

## Context
I'm building a simple app for a client that involves bundling up a static Gatsby-site with a bunch of video files and serving the content locally when the app is loaded.

## The desired result
A single .app/.exe file that opens and loads the local web app.

## What's working
I can easily build the app for Mac. The app bundle is a bit large (8GB) but it works as expected.

I can also get it to build for Windows if I remove some of the larger video files. 

## The issue
It fails when I try to build for Windows. I'm using the build config below.

After some time looking into this issue, I found that it only fails when the bundled assets become too large – even when I use the "extraResources" config. See my build config below.

Is there a file size limitation for Windows apps? And if so; is there a workaround for this?

## Build config
```json
"build": {
    "productName": "MY_APP",
    "extraResources": ["**/*.mp4"],
    "win": {
      "target": [
        "portable"
      ]
    },
    "portable": {
      "artifactName": "MY_APP.exe"
    }
  },
```

## Error output
```
Command line defined: "REQUEST_EXECUTION_LEVEL=user"
Command line defined: "UNPACK_DIR_NAME=1Sn3whWWovHs6mC7aOG8FdnpECp"
Command line defined: "ESTIMATED_SIZE=6562882"
Processing script file: "<stdin>" (UTF8)
File: failed creating mmap of "/my-app-release/my-app-release-1.0.0-x64.nsis.7z"
Error in macro x64_app_files on macroline 1
Error in macro extractEmbeddedAppPackage on macroline 17
Error in script "<stdin>" on line 111 -- aborting creation process
  • exited          command=makensis code=1 pid=718
  • async task error  error=
                        Error: /root/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                            at ChildProcess.childProcess.once.code (/project/node_modules/builder-util/src/util.ts:239:14)
                            at Object.onceWrapper (events.js:285:13)
                            at ChildProcess.emit (events.js:197:13)
                            at maybeClose (internal/child_process.js:984:16)
                            at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ⨯ [object Object]
```

## Example of (barely) successful build
When removing a few video files I can get it to build. Here's the last part of the output for a successful build.

```
...
Install: 0 pages (0 bytes), 1 section (32792 bytes), 171 instructions (4788 bytes), 558 strings (5226 bytes), 26 language tables (4420 bytes).

Using zlib compression.

EXE header size:               40960 / 39424 bytes
Install code:                  31174 / 31170 bytes
Install data:             2130941940 / 2130941940 bytes

Total size:               2131014074 / 2131012534 bytes (100.0%)
  • exited          command=makensis code=0 pid=11101
```

**Comment by rasmuswoelk** [comment]
Switching to the `nsis-web` target for Windows solved my issue.

**Comment by harmonikas996** [comment]
Thanks @rasmuswoelk ! I managed to pack 25GB large bundle with `nsis-web`.
