### ISSUE TITLE
Auto Update Custom Provider Example

### ISSUE THREAD

**Issue by devinhaughey** [electron-userland/electron-builder#4359]
electron-builder: 20.38.5
electron-updater: 4.0.14
Target: Windows_64

I am trying to use the auto-updater to contact a custom server using authentication and bearer tokens, but it appears that there isn't an option for the generic server to pass http headers or any sort of authentication to a server. I looked into the source code and saw that it is possible to pass the http headers, but the libraries aren't exposed for usage in the generic server provider code or custom. 

In researching this, I came across this post about custom providers https://github.com/electron-userland/electron-builder/issues/3261 which describes what I would like to, but there isn't any documentation on how to use it besides a comment to look at the test as an example. 

Has anyone used the custom provider to pass http headers or authentication like I would like to do? 
Could someone provide an example or update the documentation for usage of custom provider for auto-updater?

**Comment by W1M0R** [comment]
You can look at these files for usage ideas:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-publish/src/publisher.ts
https://github.com/electron-userland/electron-builder/blob/master/test/src/PublishManagerTest.ts

For an electron-builder configuration in your `package.json` that looks like this:

```json
  "build": {
    "directories": {
      "buildResources": "resources",
      "output": "release"
    },
    "publish": {
      "provider": "custom"
    }
  },
```

Put the following file in your `buildResources` folder, e.g. `resources/electron-publisher-custom.js`:

```javascript
const electronPublish = require('electron-publish');
class Publisher extends electronPublish.Publisher {
  async upload(task) {
    console.log('electron-publisher-custom', task.file);
  }
};
module.exports = Publisher;
```

Run `electron-builder --publish always` to see the output of the custom provider.
