### ISSUE TITLE
electron-builder --mac not working on circleCI

### ISSUE THREAD

**Issue by SeungjongHan** [electron-userland/electron-builder#4362]
* **electron-builder Version**: 21.2.0

* **electron-updater Version**: 4.0.0

* **Target**: Mac OS

electron-builder command for mac fails with the error message below.
![image](https://user-images.githubusercontent.com/25889313/67701367-15fd6880-f9b0-11e9-8f68-6a121ae8df66.png)

**Comment by JohnTendik** [comment]
Hmm. What version is your OS? The error says 10.13.6 required, but from the build output it says your os=16.7.0 which === 10.12.6

**Comment by SeungjongHan** [comment]
@JohnTendik Thanks. I found myself wrong. I will close this issue.
