### ISSUE TITLE
Download-progress event not firing with autoDownload=false

### ISSUE THREAD

**Issue by Christilut** [electron-userland/electron-builder#4363]
`"electron-builder": "^21.2.0",`
`"electron-updater": "^4.1.2",`

* **Target**: Windows 10

I'm doing a manual update:
```js
autoUpdater.autoDownload = false

autoUpdater.on('update-available', async (info: any) => {
  sendUpdateStatusMessage({
    message: 'Update found'
  })

  await autoUpdater.downloadUpdate()
})
```

But it seems that the `download-progress` event is not firing when turning off autoDownload. When I enable autoDownload, the progress event fires as expected. The event after that, `update-downloaded` does fire.

Is this intended or a bug?

**Comment by mrgodhani** [comment]
Same is in the Mac as well. Does not seem to fire download event

**Comment by leohxj** [comment]
this issue is not resolved, reopen it.

**Comment by leohxj** [comment]
@mrgodhani do you solved this problem?
