### ISSUE TITLE
Fails to build both ia32 and x64 arch (windows) after upgrade to Electron 7.0

### ISSUE THREAD

**Issue by acherniak** [electron-userland/electron-builder#4372]
* **Version**: 22.1.0

* **Target**: -w --x64 --ia32

Running **electron-builder -w --x64 --ia32** fails:
...
  • signing         file=dist\next\win-ia32-unpacked\resources\elevate.exe certificateFile=build/CodeSignCert.p12
  • building embedded block map  file=dist\next\nsis-web\vaporstream-1.2.3-x64.nsis.7z
  • building embedded block map  file=dist\next\nsis-web\vaporstream-1.2.3-ia32.nsis.7z
  •   Signing NSIS uninstaller  file=dist\next\nsis-web\__uninstaller-nsis-web-vaporstream.exe certificateFile=build/CodeSignCert.p12
  ⨯ [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vaporstream@1.2.3 dist-next: `set UPD_CHAN=next&&electron-builder -w --x64 --ia32`
...
Yet each individual option works fine
It worked fine with Electron 6.0.12, but broke after upgrade to Electon 7.0

**Comment by acherniak** [comment]
#4402

**Comment by PengCJun** [comment]
i have same problem
