### ISSUE TITLE
How to set different environment variables?

### ISSUE THREAD

**Issue by TheJohnPython** [electron-userland/electron-builder#4375]
Hi! I have some states of development for my application. There is build script for each state:

```
"build:work": "cross-env STAND=work electron-builder",
"build:prod": "cross-env STAND=prod electron-builder"
```
When i start `myApp.exe`, process.env.STAND is undefined.
I need pass this env variable from build time into run time (like DefinePlugin in webpack).

What are some ways to do this? Thanks!

**Comment by twigs67** [comment]
I'm also looking for this as well. I want to create a development build.

**Comment by tboulis** [comment]
+1

**Comment by TheJohnPython** [comment]
I found the following solution:
1. build electron using webpack and set variables by DefinePlugin
```
  plugins: [
    new webpack.DefinePlugin({
      "process.env": {
        STAND: JSON.stringify(process.env.STAND)
      }
    })
  ]
```
2. then build webpack bundle with electron-builder
