### ISSUE TITLE
Create Electron MSI that installs Visual C++ Redistributable (vcredist_x64) and Python

### ISSUE THREAD

**Issue by vpaladino778** [electron-userland/electron-builder#4376]
* **Target**: Windows MSI

Hello! The electron app i'm creating relies on [vcredist_x64](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) as well as Python27.dll. I was wondering if it's possible to package this into the MSI.

**Comment by sitemercadorafaelberrocal** [comment]
Hi, have you figured out how to embed another .exe or .smi into the builder?

**Comment by vpaladino778** [comment]
@sitemercadorafaelberrocal Unfortunately i have not found a within electron builder. The solution i'm currently looking into is using [dotNetInstaller](https://dblock.github.io/dotnetinstaller/). This is an external tool that can package MSI/exe's together into one installer.

**Comment by Superlokkus** [comment]
> @sitemercadorafaelberrocal Unfortunately i have not found a within electron builder. The solution i'm currently looking into is using [dotNetInstaller](https://dblock.github.io/dotnetinstaller/). This is an external tool that can package MSI/exe's together into one installer.

#4679 should help you
