### ISSUE TITLE
loadingGif size

### ISSUE THREAD

**Issue by sunabozu** [electron-userland/electron-builder#438]
I'm trying to replace the standard gif image that is used during the installation, but I can't determine a proper resolution for it. The [default gif](https://raw.githubusercontent.com/electron/windows-installer/master/resources/install-spinner.gif) is 268x167, but the installer stretches it out. I measured those dimensions and corrected the size of my image, but then the installer just truncated it.

Is there a way to make it look good?

**Comment by develar** [comment]
I see nothing suspicious in the https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/AnimatedGifWindow.cs

Please repost issue to https://github.com/Squirrel/Squirrel.Windows/issues (don't forget to mention this issue, so, I can subscribe).

**Comment by develar** [comment]
Do you use OS X (retina?) or Windows?

**Comment by sunabozu** [comment]
@develar I generate installers on OS X (no retina) and then test them on Windows that runs inside Parallels Desktop.

**Comment by sunabozu** [comment]
Additional information: I used a png file instead of an actual gif. With gif there is no problem with scaling, but the quality is considerably worse.

**Comment by develar** [comment]
Moved to backlog. Because Squirrel.Windows will be not default target in the next major release. For NSIS it is not required.
