### ISSUE TITLE
[feat]: The pkg interface adds the must-close attribute

### ISSUE THREAD

**Issue by BlackHole1** [electron-userland/electron-builder#4380]
* **Version**: `22.1.0`

* **Target**:  `pkg`

currently, some of the interfaces are provided when packaging the pkg application, but not all.

In the Apple developer documentation, there is a [must-close](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW77) attribute. I think this property is very necessary to join in.

Apple's introduction to `must-close`:

> Identifies applications that must be closed before the package is installed.
> Applications are considered only if the package that contains this element has been selected for installation.

Because the current `electron-builder` does not provide this property, it will not exit some apps that must be quit when installing pkg. You must use `postinstall` or `preinstall` to force the process to be killed. This is a very bad user check.

**Comment by BlackHole1** [comment]
I added the relevant PR: https://github.com/electron-userland/electron-builder/pull/4382

**Comment by Tomyail** [comment]
I need this feature。 👏👏
