### ISSUE TITLE
[macOS notarization] Adding com.apple.security.cs.allow-jit to entitlements.plist

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#4385]
Hi,

I think that the `com.apple.security.cs.allow-jit` property should be added in this file `packages/app-builder-lib/templates/entitlements.mac.plist`.

Because this seems to be recommended by [electron-notarize](https://github.com/electron/electron-notarize#prerequisites) (point 4 of section prerequisites).

**Comment by pdesantis** [comment]
Good find, this seems useful. Here's the [Apple documentation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit) on this key.

**Comment by popod** [comment]
I've done a PR to add this property.

@develar could you check it and tell me if I need to change something ? Thanks a lot :)
