### ISSUE TITLE
Native module not found after Build 

### ISSUE THREAD

**Issue by vkiranmaniya** [electron-userland/electron-builder#4389]
* **Version**: 
electron-builder v21.2.0
electron v6.0.9
node v10.16.0

* **Target**: 

1. Mac
zip, dmg
2. Windows
nsis
3. Linux
AppImage, tar.gz

Custom native module not found after building the app installers. However, running with electron . in dev environment, It works fine. Here is the screen capture.
![image](https://user-images.githubusercontent.com/22276302/68103407-a8e05a80-fefc-11e9-8059-a77661304bd8.png)

Here is the **node-gyp** configuration from **binding.gyp** file
`{
    "targets": [{
        "target_name": "altron",
        "sources": [
            "src/altron.cc"
        ],
    }]
}`

**Comment by taratatach** [comment]
This looks similar to the issue I reported here: #4370

**Comment by vkiranmaniya** [comment]
> This looks similar to the issue I reported here: #4370
there is no solution or workaround given.

**Comment by Mhmetengineer** [comment]
Can u solve this problem ? @vkiranmaniya

**Comment by vkiranmaniya** [comment]
@Mhmetengineer not yet, I wrote and compiled the Node native module but it doesn't work in the production build of the electron.

**Comment by vkiranmaniya** [comment]
The issue has not been fixed, please provide detail on how to use compiled native module in electron production build.
