### ISSUE TITLE
Different names for ia32 and win64 nupkg

### ISSUE THREAD

**Issue by gamestailer94** [electron-userland/electron-builder#439]
if not something like this happens:
https://ci.appveyor.com/project/gamestailer94/quest-editor/build/1.0.64#L398

**Comment by develar** [comment]
For windows consider only distributing 64-bit versions — see https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130 Or use custom update server.

**Comment by gamestailer94** [comment]
I use nuts as update server.
so I just need a Way for nuts to diferentiate between win x64 and ia32 releases.
As for the Auto update thing i have a workaround for that, its just the upload part of the builder...

**Comment by develar** [comment]
> and yes I need to have ia32

Well, so, just distribute only ia32 as solution.

**Comment by gamestailer94** [comment]
> Well, so, just distribute only ia32 as solution.
All I was askting was a arch suffix on window artifacts (like on linux builds)

**Comment by develar** [comment]
> All I was askting was a arch suffix on window artifacts (like on linux builds)

It was implemented earlier, but it leads to critical error — nupkg MUST NOT contain arch suffix because package name is present in the RELEASES file. So, we should fix update server AND Squirrel.Windows to use arch suffix in the package name. But it is unrealistic to fix Squirrel.Windows.

**Comment by gamestailer94** [comment]
hmm, well ok if there is really no other way, then i will use ia32.

**Comment by develar** [comment]
There is solution — use other update server (not nuts because of https://github.com/GitbookIO/nuts/issues/32) and host artifacts not on the Github.

**Comment by ArekSredzki** [comment]
@develar yeah, electron-release-server has full arch support. It was never "broken" so didn't think to put it in the README. Feel free to put in a PR :)

**Comment by kunkinkan** [comment]
mac naming issues too; 

zip is named = "App Name-0.1.2-mac.zip"
dmg is named = "App Name-0.1.2.dmg"

(why does the zip version have "-mac"?)

**Comment by develar** [comment]
> why does the zip version have "-mac"

* Squirrel.Mac requirement. 
* zip is a generic format — it is not clear — is it for OS X or Windows.

**Comment by steverandy** [comment]
@develar Will you be open to implement or accepting PR for supporting ia32 and x64 when publishing to github by using suffix?

I plan to build a custom update server that will handle serving files for both arch.

**Comment by develar** [comment]
Yes. But please note — now default target is nsis.

**Comment by steverandy** [comment]
@develar I think Squirrel.Windows supports suffix in the filename (https://github.com/Squirrel/Squirrel.Windows/pull/450)

Will there be any issue if we use something like "appname-1.0.0-beta0-ia32-full.nupkg" in RELEASES?

**Comment by develar** [comment]
I cannot advice. Nsis is recommended default target now. In any case, PR will be accepted.
