### ISSUE TITLE
Invalid path with prepackaged app on linux

### ISSUE THREAD

**Issue by stigi** [electron-userland/electron-builder#4391]
* **Version**: `22.1.0`
* **Target**:  Linux
* Electron Version: `7.0.1`

## Issue

Electron-builder is failing when I break the packaging apart by using `--dir` and `--pd`.
It looks like the `--pd` step is behaving like a zip bomb, creating deeply nested copies of `__appImage-x64` resulting in the following error (or similar for other final path components):

```
⨯ open /Users/ullrich/tmp/linux-package/electron-quick-start/dist/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/__appImage-x64/usr/share/icons/hicolor/16x16/apps/electron-quick-start.png: file name too long
```

## Repro

I was able to reproduce the bug in a clean setup:

- `git clone https://github.com/electron/electron-quick-start.git`
- `cd electron-quick-start`
- `yarn add electron-builder`
- `yarn electron-builder -l --dir`
- `yarn electron-builder -l --pd dist`

**Comment by catdad** [comment]
I came here to report a similar issue, but your repro steps actually got me to a place where it actually works. In the last step, you are providing the wrong directory. Try the command like this:

```bash
yarn electron-builder -l --pd dist/linux-unpackaged/
```

Note the path: it has to be the path directly to the unpackaged app, and the `/` at the end if actually very important.

I was running my command without the `/` at the end, which works for my Windows and MacOS builds, but fails for the AppImage... in case anyone else runs into this same issue.
