### ISSUE TITLE
EV code signing nsis on MacOS Catalina

### ISSUE THREAD

**Issue by damianobarbati** [electron-userland/electron-builder#4395]
I recently upgraded to Catalina and to `electron-builder` to 22.1.0 but I can no longer build and sign my application.

But I'm not sure whether this is related to 1) Catalina 2) Parallels installation 3) electron-builder@22.1.0

When electron-builder fires the command on the win10 virtual machine I always get "Select a smart card device" popup (screenshot down here).
But:
- the EV certificate USB token is permanently attached to the machine
- the SafeNet client is installed, working and certificate is visible
- single logon is enabled thus no password is needed

<img width="859" alt="ev" src="https://user-images.githubusercontent.com/2225869/68284567-094ad580-007e-11ea-85cc-94fb386eb8f9.png">

Is parallels signing not supported anymore? Is the following the official and best way to sign with EV token? 
https://www.electron.build/tutorials/code-signing-windows-apps-on-unix#signing-windows-app-on-mac-using-osslsigncode

**Environment details**

Build command:
```
electron-builder --win --ia32 --x64 --config.compression=store
```

Configuration in `package.json`:
```
"build": {
    "generateUpdatesFilesForAllChannels": true,
    "appId": "net.xxx.xxx",
    "publish": {
        "provider": "github",
        "vPrefixedTagName": false,
        "releaseType": "release"
    },
    "files": [
        "./*.json",
        "./*.js",
        "./assets/*",
        "./icons/*",
        "./main/*",
        "./renderer/*",
        "./shared/*",
        "./node_modules/typeface-montserrat/files/*.woff2"
    ],
    "directories": {
        "buildResources": "./icons",
        "output": "./dist"
    },
    "asar": true,
    "win": {
        "target": [
            "nsis"
        ],
        "icon": "./icons/logo.ico",
        "publisherName": [
            "xxx srl"
        ],
        "certificateSubjectName": "xxx srl",
        "verifyUpdateCodeSignature": false
    },
    "nsis": {
        "oneClick": false,
        "perMachine": true,
        "allowElevation": true,
        "deleteAppDataOnUninstall": true,
        "createDesktopShortcut": "always",
        "menuCategory": "xxx - xxx",
        "installerHeaderIcon": "./icons/logo.ico",
        "installerIcon": "./icons/logo.ico",
        "uninstallerIcon": "./icons/logo.ico",
        "installerSidebar": "./icons/win-installer-sidebar.bmp",
        "installerHeader": "./icons/win-installer-header.bmp",
        "uninstallerSidebar": "./icons/win-uninstaller-sidebar.bmp",
        "license": "./assets/license.html"
    }
}
```

Dependencies are:
```
"dependencies": {
    "electron-log": "3.0.8",
    "electron-updater": "4.2.0"
},
"devDependencies": {
    "electron": "^4.2.12",
    "electron-builder": "22.1.0",
    "electron-debug": "3.0.1"
}
```

**Comment by menelike** [comment]
Can not confirm, it works on my side in conjunction with:

- Parallels: `Version 14.0.1 (45154)`
- electron-builder: `21.2.0`
- macOS: `10.15.1 (19B88)` (Catalina)

**Comment by damianobarbati** [comment]
The issue was a non original ISO image from Windows installed by default by Parallels.
