### ISSUE TITLE
Import declaration conflict with TS 3.7

### ISSUE THREAD

**Issue by ffflorian** [electron-userland/electron-builder#4397]
* **Version**: 20.44.4
* **TypeScript version**: 3.7.2

When building with TypeScript 3.7.2, I get the following error:

```
node_modules/app-builder-lib/out/electron/ElectronFramework.d.ts:3:10 - error TS2440: Import declaration conflicts with local declaration of 'ElectronPlatformName'.

3 import { ElectronPlatformName, Packager } from "../index";
           ~~~~~~~~~~~~~~~~~~~~
```

**Comment by vladimiry** [comment]
The workaround is to enable the `skipLibCheck` TS compilation option. But yes it's better ti fix the cause.

**Comment by ffflorian** [comment]
Thanks for the workaround @vladimiry!
