### ISSUE TITLE
Github releases not working in windows machine

### ISSUE THREAD

**Issue by limoragni** [electron-userland/electron-builder#440]
Hey! 
I want to publish to Github from Appveyor and Travis

I have it working in an OSX machine and on Travis. But I'm having problems doing it in a windows machine and Appveyor. 

When I run npm run release it builds without giving any errors and exits before creating the release on github.

I did some debugging and I think there's a callback that's not being called here in builder.js:

```
if (options.publish != null && options.publish !== "never") {
   //IT GETS HERE WITH NO PROBLEM
   let publisher = null;
   packager.artifactCreated(event => {
       //IT NEVER GETS HERE!!
       if (publisher == null) {
          publisher = createPublisher(packager, options, repositoryInfo, isPublishOptionGuessed);
       }
       if (publisher) {
           publisher.then(it => publishTasks.push(it.upload(event.file, event.artifactName)));
       }
   });
}
```
The part of my package.json that has the config.

```
"main": "index.js",
  "version": "2.4.14",
  "scripts": {
    "start": "export LOCAL=true || set LOCAL=true && electron --enable-debugging dev/build/index.js",
    "postinstall": "cd dev && npm install",
    "version": "./tasks/copy_package_version.sh && git add -A dev/package.json",
    "push": "npm version patch && git push origin HEAD",
    "pack": "export BUILD_ENVIRONMENT=production || set BUILD_ENVIRONMENT=production && gulp build && build",
    "dist": "export BUILD_ENVIRONMENT=production || set BUILD_ENVIRONMENT=production && gulp build && build",
    "release": "export BUILD_ENVIRONMENT=production || set BUILD_ENVIRONMENT=production && gulp build && build",
    "test": "npm -v"
  },
  "build": {
    "app-bundle-id": "com.metrica-sports.footmapp",
    "app-category-type": "public.app-category.sports",
    "win": {
      "iconUrl": "https://s3-eu-west-1.amazonaws.com/footmapp/metrica/footmapp_logo.ico"
    },
    "osx": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    }
  },
```

**Comment by develar** [comment]
It works for me for my app. Are you sure that you add required GH_TOKEN?

**Comment by limoragni** [comment]
Yes, I've checked and process.env.GH_TOKEN holds the token. I assume this might be a problem with my configuration, but I don't know where to start looking. And, without really knowing the code, I think is strange that callback is never called in builder.js. packager.artifactCreated is being called I'm sure of that.

**Comment by develar** [comment]
Ouch. Maybe you forget to pass `--dist` flag?

> Please note — if you don't name your script dist or prefix it with dist: and you don't pass --dist flag, application will be not packed in a distributable format.

**Comment by limoragni** [comment]
I didn't pass the --dist flag. This is working fine on OSX though. The script is called release, I thought that was enough for electron-builder to infer it has to be packed in a distributable format. And I do have the dist script there. Question, when I do npm run release, does electron-builder needs me to already have the dist script defined in the package.json?  Is the --dist flag mandatory when calling npm run release?

**Comment by limoragni** [comment]
Thanks a lot @develar the --dist flag did the trick! 

A couple of things I find confusing.

I don't know where I'm supposed to add the publish options. Is it in the "build" part of the package.json? 
If I'm calling the release script, shouldn't it already infer I want things packed for distribution?

**Comment by develar** [comment]
>  Is the --dist flag mandatory when calling npm run release?

Yes, it will be fixed soon — https://github.com/electron-userland/electron-builder/issues/413

> I don't know where I'm supposed to add the publish options
>  shouldn't it already infer I want things packed for distribution?

What do you mean? `publish` is a CLI arg. You don't need to specify artifacts — what do you build is what will be published.
