### ISSUE TITLE
Bug in release 22.1.0 "[object Object] error Command failed with exit code 1."

### ISSUE THREAD

**Issue by kzimny** [electron-userland/electron-builder#4402]
Which version of electron-builder are you using?
* **Version**: 22.1.0

Which version of electron-updater are you using (if applicable)?
* **Version**: 4.2.0

What target are you building for?
* **Target**: nsis-web

* **package.json**:
```
    "build": {
        "appId": "com.xxx.yyy",
        "productName": "Viewer",
        "afterSign": "crv/config/afterSignHook.js",
        "directories": {
            "output": "build"
        },
        "nsisWeb": {
            "artifactName": "${productName}-Setup-${version}.${ext}",
            "oneClick": true,
            "perMachine": false,
            "allowToChangeInstallationDirectory": false,
            "runAfterFinish": true,
            "deleteAppDataOnUninstall": true,
            "differentialPackage": true
        },
        "publish": {
            "provider": "generic",
            "url": "https://www.xxxxx.com/${os}",
            "channel": "latest"
        },
        "files": [
            "!apps${/*}",
            "!tsconfig.json",
            "!tslint.json",
            "!yarn-error.log",
            "!yarn.lock"
        ],
        "win": {
            "extraResources": [
                {
                    "from": "crv/assets/data",
                    "to": "../",
                    "filter": "test*"
                }
            ],
            "icon": "crv/assets/icons/icon.ico",
            "target": [
                {
                    "target": "nsis-web",
                    "arch": [
                        "x64",
                        "ia32"
                    ]
                }
            ]
        },
        "mac": {
            "extraResources": [
                {
                    "from": "crv/assets/data",
                    "to": "../../../",
                    "filter": "test*"
                }
            ],
            "icon": "crv/assets/icons/icon.icns",
            "hardenedRuntime": true,
            "gatekeeperAssess": false
        }
    },
```

* **Error**:
```
$ electron-builder .
  • electron-builder  version=22.1.0 os=10.0.18362
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=build\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@4.1.0 platform=win32 arch=x64
  • rebuilding native dependency  name=sqlite3 version=4.1.0
  • packaging       platform=win32 arch=x64 electron=7.1.1 appOutDir=build\win-unpacked
  • rebuilding native dependencies  dependencies=sqlite3@4.1.0 platform=win32 arch=ia32
  • rebuilding native dependency  name=sqlite3 version=4.1.0
  • packaging       platform=win32 arch=ia32 electron=7.1.1 appOutDir=build\win-ia32-unpacked
  • building        target=nsis-web file=build\nsis-web\Viewer-Setup-1.0.18.exe archs=x64, ia32 oneClick=true perMachine=false
  • building embedded block map  file=build\nsis-web\crv-1.0.18-ia32.nsis.7z
  • building embedded block map  file=build\nsis-web\crv-1.0.18-x64.nsis.7z
  ⨯ [object Object]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "run-electron-builder" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

With electron-builder version 21.2.0 everything works fine.

**Comment by JamesCoyle** [comment]
I can run `electron-builder --ia32` and `electron-builder --x64` fine but `electron-builder --ia32 --x64` no longer works.

**Comment by JamesCoyle** [comment]
Here is where things go wrong for me in the debug logs (full logs in attached zip):

```
File: failed creating mmap of "C:\Repositories\Blis\public-display\build\blis-public-display-2.0.0-x64.nsis.7z"
Error in macro x64_app_files on macroline 1
Error in macro compute_files_for_current_arch on macroline 12
Error in macro extractEmbeddedAppPackage on macroline 14
Error in macro installApplicationFiles on macroline 79
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 160 -- aborting creation process
  • exited          command=makensis.exe code=1 pid=8432
  • async task error  error=
                        Error: C:\Users\jcoyle\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4\Bin\makensis.exe exited with code 
ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                            at ChildProcess.<anonymous> (C:\Repositories\Blis\public-display\node_modules\.pnpm\registry.npmjs.org\builder-util\22.1.0\node_modules\builder-util\src\util.ts:239:14)
                            at Object.onceWrapper (events.js:300:26)
                            at ChildProcess.emit (events.js:210:5)
                            at maybeClose (internal/child_process.js:1021:16)
                            at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ⨯ [object Object]
 ERROR  Command failed with exit code 1.
```
[debug-log.zip](https://github.com/electron-userland/electron-builder/files/3840737/debug-log.zip)

**Comment by kzimny** [comment]
In version 21.2.0 the uninstaller was not generated. Maybe it has something to do with the uninstaller that is generated in version 22.1.0?

**Comment by youyinnn** [comment]
I got this too, I change to 21.2.0 and it still happening

**Comment by kzimny** [comment]
I build nsiWeb for Windows and Mac with version 21.2.0 and the configuration above. Everything works fine. v22.1.0 does not work on my side.

**Comment by youyinnn** [comment]
I think I just luckily tested out why I got this error in my case.
It is weird and you probably can not believe it:
I use a **512x512 icon** as app icon, and the [configuration of `installerIcon` & `uninstallerIcon` ](https://www.electron.build/configuration/nsis#web-installer) is using it as default.
Turns out I can not use **512x512 icon** as `installerIcon` & `uninstallerIcon`
Finally, I use **256x256 icon** as `installerIcon` & `uninstallerIcon` and leave 512 to the app icon

# And it worked，even on v22.1.0！！！

**Comment by kzimny** [comment]
Wow!! It this is true you are a genius!! I'll test it asap. Thank you.

**Comment by kzimny** [comment]
I checked and **can not** confirm that the icon size causes the problem. Probably you built your executable with the option `nsis `as follow:

```
    "build": {
        "nsis": {
            ...
        },
        "win": {
            "target": [
                {
                    "target": "nsis",
                    "arch": [
                        "ia32",
                        "x64"
                    ]
                }
            ]
        },
    },
```
In my solution I use the [web-installer](https://www.electron.build/configuration/nsis#web-installer). As describe in the documentation this is the better way to go if you file is huge, because the web Installer automatically detects OS architecture and downloads corresponding package file which is smaller by half than the nsis package. When I build with `nsis `option everything goes through. 

With the debug option `set DEBUG="electron-builder"` I get the following error:
```
Processing config: C:\Users\Krzysztof\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4\nsisconf.nsh
Processing script file: "<stdin>" (ACP)
!insertmacro: macro "_If" requires 4 parameter(s), passed 6!
Error in macro downloadApplicationFiles on macroline 19
Error in macro installApplicationFiles on macroline 63
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 160 -- aborting creation process
  • exited          command=makensis.exe code=1 pid=9920
  • async task error  error=
                        Error: C:\Users\Krzysztof\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                            at ChildProcess.childProcess.once.code (C:\ZNF_SandBox2\Mvc\StorkCMS\Stork.SPA\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:239:14)
                            at Object.onceWrapper (events.js:277:13)
                            at ChildProcess.emit (events.js:189:13)
                            at maybeClose (internal/child_process.js:970:16)
                            at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  ⨯ [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crv@1.0.1 electron-builder: `electron-builder .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crv@1.0.1 electron-builder script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Krzysztof\AppData\Roaming\npm-cache\_logs\2019-11-18T05_49_48_379Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In my opinion this is a bug.

**Comment by qq1066536** [comment]
electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

error  !!!!
move electron-builder to devDependencies

**Comment by kzimny** [comment]
This is not an error but rather an information. electron-builder is already installed in devDependencies and even if I completely remove electron-rebuild the error `⨯ [object Object]` is still there. 

Can anybody compile with v22.1.0 for both platforms `electron-builder -w --ia32 --x64` and target set to "nisis-web"?

**Comment by alanfelp** [comment]
Também estou com o mesmo problema

**Comment by alanfelp** [comment]
I also have the same problem, I can't compile `nsis-web` with `electron-builder -w --ia32 --x64`

**Comment by lzxjs** [comment]
me too,I also have the same problem

**Comment by kzimny** [comment]
@dangeredwolf : since [changes ](https://github.com/electron-userland/electron-builder/commit/d738644d6e55b027c81e9b7cdd27dc5af9189b0a#diff-798fb79fa062b2e80f1942334e811efa) in version 22.1.0 some users cannot build with target set to `nsis-web`. Do you have an idea why we get the error message above? Can you build your or an boilerplate project with target set to `nsis-web` without errors?

**Comment by damajor** [comment]
I don't know if it will help but I have the exact same behavior trying to build with "--win portable"

**Comment by kzimny** [comment]
`portable` works fine with v.22.3.0:
```
        "win": {
            "icon": "crv/assets/icons/icon.ico",
            "target": [
                {
                    "target": "portable",
                    "arch": [
                        "x64",
                        "ia32"
                    ]
                }
            ]
        },
```
No errors. Only `nsis-web` doesn't work.

**Comment by GitNomster** [comment]
Same problem with
` "build":
        "win": {
            "target": [
                {
                    "target": "nsis",
                    "arch": [
                        "ia32",
                        "x64"
                    ]
                }
            ]
        },
    },`

**Comment by kzimny** [comment]
`nsis` works fine with this and above configuration:
```
        "nsis": {
            "artifactName": "${productName}-Setup-${version}.${ext}",
            "oneClick": true,
            "perMachine": false,
            "allowToChangeInstallationDirectory": false,
            "runAfterFinish": true,
            "deleteAppDataOnUninstall": true,
            "differentialPackage": true
        },
```

**Comment by GitNomster** [comment]
Not for me( Building on linux for win work with builder 20.43.0 and electron 6.1.7, but now didn't work with builder 22.2.0 and electron 7.1.9.

**Comment by kzimny** [comment]
Can you try with electron-builder@next v.22.3.0?

**Comment by GitNomster** [comment]
Already tried with 22.3.0 and 22.3.1, problem still persist.

**Comment by kzimny** [comment]
Yes, very strange. Someone made a mess after version version 20.43.0 or 21.2.0.

**Comment by GitNomster** [comment]
Error even with electorn 6.1.7 on builder 22.2.0. But works with v 21.2.0.

**Comment by Nditah** [comment]
I had to remove the icon for electron-build  to work
`
            "icon": "crv/assets/icons/icon.ico",
`
Changing version for 21.2.0 to 22.3.0 didn't help at all.

**Comment by VeselyT** [comment]
> @dangeredwolf : since [changes ](https://github.com/electron-userland/electron-builder/commit/d738644d6e55b027c81e9b7cdd27dc5af9189b0a#diff-798fb79fa062b2e80f1942334e811efa) in version 22.1.0 some users cannot build with target set to `nsis-web`. Do you have an idea why we get the error message above? Can you build your or an boilerplate project with target set to `nsis-web` without errors?

I had to change this line https://github.com/electron-userland/electron-builder/blob/d738644d6e55b027c81e9b7cdd27dc5af9189b0a/packages/app-builder-lib/templates/nsis/include/webPackage.nsh#L20 to fix the build for me. It should be only `${if} ${IsNativeAMD64}`

**Comment by kzimny** [comment]
@VeselyT are you familiar with installer scripts? If you tested and it works on your side can you make a PR please?

**Comment by antoinepryy** [comment]
Same error w. 20.39.0 version. My application consists in a React main process that launch 2 python processes (with large .WAV file), since I remove both of them the build is succesful. Maybe you should try a build without large files that may be present in your source code !

**Comment by gblue1223** [comment]
In my case, some file inside the project folder was using by another program and could not access from the builder.
After close the program which using the file the builder works without any problem!
