### ISSUE TITLE
Autoupdate: expose the fact that the update is not available at the UpdateCheckResult

### ISSUE THREAD

**Issue by MOZGIII** [electron-userland/electron-builder#4403]
Take a look at the following code: 

https://github.com/electron-userland/electron-builder/blob/b83f5801771585c18524c3cee74e59de5fa9ab30/packages/electron-updater/src/AppUpdater.ts#L358-L370

Here the `isUpdateAvailable` is called to determine whether the latest version is or isn't an update for the current version, and then an event is issued. The resulting information, however, isn't exposed in the `UpdateCheckResult`, which would be very reasonable to have.

I propose adding a boolean to indicate whether the latest version is an update for the current version or not by adding a new field to the `UpdateCheckResult` (for example `isUpdate`) and setting it to `false` if we're returning from the `if (!await this.isUpdateAvailable(updateInfo)) { ... }` branch, and to `true` otherwise. 

It looks like the `UpdateCheckResult` exists precisely to expose the details like this, so it's a shame it's not available.

**Comment by MOZGIII** [comment]
:disappointed:

**Comment by jurij** [comment]
I came across the same issue. I need to know if an update exists or not. As it seems it should be fine to check if `cancellationToken` exists as of right now?
