### ISSUE TITLE
App crashing after build

### ISSUE THREAD

**Issue by mrgodhani** [electron-userland/electron-builder#4406]
* **Version**: 22.1.0

Electron Updater: 4.2.0

* **Target**: Mac

Application right away crashes or closes after building an app using the latest electron-builder. Works file when using 21.2.0 version electron-builder.

**Comment by sidneys** [comment]
@mrgodhani Did you manage to fix this issue? It still persists (see https://github.com/electron-userland/electron-builder/issues/4408)..

**Comment by mrgodhani** [comment]
@sidneys No, I closed it in favor of #4408
