### ISSUE TITLE
Update log for osx installer/update

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#441]
I have a ```Nuts``` server running that holds update releases for my electron app. I just created installers for osx, and am trying to use the ```auto-update``` feature. However, I can't seem to find a log for whether or not the updates were successful. On Windows, I believe there was a file called ```SquirrelSetup.log```. I'd like to know if there's something similar on OSX, or a way I can check if my app is updating.

**Comment by mzmousa** [comment]
Oops. Guess I'm a noob when it comes to using developing on OSX. Just open ```Console``` and any logging information will be displayed there.

**Comment by develar** [comment]
Yes, and you can your own using nslog, see https://github.com/develar/onshape-desktop-shell/blob/master/src/AppUpdater.ts
