### ISSUE TITLE
Multiple Apple accounts (how to choose a different Apple Certificate)

### ISSUE THREAD

**Issue by andiskim** [electron-userland/electron-builder#4411]
* **Version**: 22.1.0

* **Target**: MacOS

When I run **yarn dist** I get a codesign request with a developer account that I am not using (this is someone else's account).  How do I re-target the codesign with my personal Apple Certificate rather than allowing the program to choose by itself?

**Comment by kzimny** [comment]
You can try to [change the Apple ID](http://osxdaily.com/2014/11/08/change-apple-id-mac-os-x/), when the certificate was added with from another account.
