### ISSUE TITLE
Cannot overwrite publish config using auto update

### ISSUE THREAD

**Issue by jsheffers** [electron-userland/electron-builder#4419]
* **Electron Builder: 22.1.0**: 

* **Electron Updater: 4.2.0**

* **Targets: Mac & Win**: 

I'm using yarn to trigger the building of my app, however, when I try to publish it to GitHub, it's auto-detecting the owner and project from the git repository even when I specify custom publish options.  I build my app using the following.

`electron-builder --mac --win --config ./config/my.app.yaml --publish always`

Every time it builds I get a 404 and the GET URL is incorrect.  I'm setting the publish config in package.json like so:

```
  "build": {
    "publish": [
      {
        "provider": "github",
        "owner": "username",
        "repo": "project",
        "private": true
      }
    ]
  },
```

However, the API call that's used to get the releases is using the wrong owner and project.  Any ideas on how to fix this?

**Comment by newCodeRunner** [comment]
You need to add the following in package.json

  "repository": "github:[userName]/[repoName]",
