### ISSUE TITLE
Any options to skip installAppDependencies

### ISSUE THREAD

**Issue by noteon** [electron-userland/electron-builder#442]
installAppDependencies is slow. In test install process, I want to skip installAppDependencies.
Is there any option to do it?

**Comment by develar** [comment]
To speed up during test, set compression to store — see https://github.com/electron-userland/electron-builder/wiki/Options

Could you please provide example of slow native ext — name?

**Comment by noteon** [comment]
"Set compression to store" do a big help, but I still want an option to skip installAppDependencies.   In my project, there is a few native module (mongodb driver, redis driver, fibers, kerberos). In common, I just build native modules once, then in build process, gulp will copy native module to app directory. I need not to rebuild them again.

**Comment by develar** [comment]
CLI: `--no-npmRebuild`.
Programmatic usage: `npmRebuild: false`.

Version 4 will be released soon.
