### ISSUE TITLE
v22.0.0 and v22.1.0 are marked as "pre-release" in GitHub

### ISSUE THREAD

**Issue by ezzatron** [electron-userland/electron-builder#4421]
* **Version**: N/A

* **Target**: N/A

Are these supposed to be marked as pre-releases?:
- https://github.com/electron-userland/electron-builder/releases/tag/v22.0.0
- https://github.com/electron-userland/electron-builder/releases/tag/v22.1.0

If they're actually pre-release versions, shouldn't they follow SemVer and use an `-rc` or similar suffix?

**Comment by kzimny** [comment]
Versions 22.0.0 and 22.1.0 are not suitable for production, there are too many bugs. They did not deserve to be called pre-releases. They should be definitely renemed.

**Comment by ezzatron** [comment]
Why was this closed? It got marked as stale while I was asleep, and I didn't even get a chance to get notified before it was closed. I'd still like to know if `electron-builder` follows SemVer or not. It's important for maintaining projects that use it.

**Comment by develar** [comment]
Releases marked as `pre-release` on Github have tag `next` on NPM. So, you will not get update to this version unless explicitly specifying `@next`.

**Comment by ezzatron** [comment]
Is it possible something's not working correctly in the deployment process? Because, at least on npmjs.com there's no indication that [22.0.0](https://www.npmjs.com/package/electron-builder/v/22.0.0) or [22.1.0](https://www.npmjs.com/package/electron-builder/v/22.1.0) are unstable releases.

And when I run `yarn outdated` to see what needs upgrading, I'm pretty sure this package's "pre-release" versions get suggested (I can't demo this right now because there are no pre-release versions with a higher version number than the current stable version).

I think most developers would naively assume that `electron-builder` follows SemVer. If there's a good reason not to, that's fine, but it would be helpful to see it documented somewhere.

Unless I'm missing something, I really think `22.0.0` and `22.1.0` would have been better off tagged as `22.0.0-rc1` and `22.0.0-rc2` (using a suffix to indicate a SemVer pre-release).
