### ISSUE TITLE
github token is missing when downloading release (but is present when fetching blockmap)

### ISSUE THREAD

**Issue by florianlenz** [electron-userland/electron-builder#4423]
* **Version**:  `22.1.0`

* **Electron Updater Version**: `4.2.0`

* **Target**:  Windows

I am running into an odd situation. I am trying to pull my github releases from a private github repository. I already read the docs multiple times and actually, authentication with github IS working in SOME cases. I am e.g. able to download the `.blockmap` files. However, authentication is failing when trying to download the release it self. Github is giving a `404` error. That was quite confusing, therefore I started to inspect the HTTP traffic and I figured out that for the request that is supposed to download the release, no token seems to be added to the request. I made some screenshots. I don't think I am miss configuring something since I am actually able to download the blockmap files.

<img width="1119" alt="missing-token" src="https://user-images.githubusercontent.com/16626192/68934368-06539180-07b0-11ea-9a58-9be4d8410535.png">
<img width="1089" alt="authenticated-request" src="https://user-images.githubusercontent.com/16626192/68934369-06539180-07b0-11ea-9d15-8052496a26da.png">

Please let me know if there's anything I can help with in order to resolve this problem. @develar You seem to be the main maintainer (so I am asking you directly), I would like to offer a bounty to the person that is able to fix the bug. I saw that I am able to donate [here](https://www.electron.build/donate). Will you internally distribute the bounty to the one who fixes it? 

Thank you for taking the time to read this issue,
Florian

**Comment by didiokener** [comment]
I am facing the same issue, when i downgrade electron, electron builder and electron updater it solves the issue, i don't know why. Versions i downgraded: 
"electron-builder": "^20.28.3",
"electron": "4.0.6",
"electron-updater": "^3.1.2"
I would like to see the latest version working fine.
