### ISSUE TITLE
missing local-chromium when installing puppeteer

### ISSUE THREAD

**Issue by nofear87** [electron-userland/electron-builder#4426]
I have installed puppeteer via electron-builder conf files within dependecies. The local-chromium folder under node_modules/puppeteer is missing then :-( any ideas?

Is there a possibility to pass process env vars to the dependency installation?

The puppeteer logfiles can be helpful to solve this issue:

```
function logPolitely(toBeLogged) {
  const logLevel = process.env.npm_config_loglevel;
  const logLevelDisplay = ['silent', 'error', 'warn'].indexOf(logLevel) > -1;

  if (!logLevelDisplay)
    console.log(toBeLogged);
}
```

**Comment by dancingbannana** [comment]
did you ever find a fix
