### ISSUE TITLE
Plz supporting not to download  everytime

### ISSUE THREAD

**Issue by youyinnn** [electron-userland/electron-builder#4427]
* **Version**: 

v21.2.0

* **Target**: 

win - nsis

Dear all, 

I found that very annoyed every time I try to build apps with this tool, it will always try to download a bunch of binary files such as electron-xxx.zip or nsis.xxx.zip

Can it be set to an existing file?

**Comment by ShadixAced** [comment]
It normally "caches" the downloads when it's over, maybe this has to do with file permissions on your side...

**Comment by youyinnn** [comment]
@ShadixAced 
Yeah, I know they are necessary, I was stuck in the building step and it took me a long time to figure out there was something related to my network(for download) and the permission problem(for unzip and move, probably need to turn off the anti-virus app).

And it stopped download when those files were actually finishing two step: **downloaded** and **unzipped**, if one of these step is faild, then it will download again.

So I was wondering can it be set to an existing unzipped location to skip the steps above, that will be nice.

**Comment by ShadixAced** [comment]
@youyinnn Ah I see. 

As far as I know, it only puts the zip and the unzipped program to a folder in your project called "cache". 

I do not know if we can modify this (I don't think so)
