### ISSUE TITLE
electron-builder app.asar  error

### ISSUE THREAD

**Issue by misteraries** [electron-userland/electron-builder#4429]
* **Version**: 
22.1.0

22.1.0

* **Target**: 

⨯ remove E:\IssueHub\release\win-unpacked\resources\app.asar: The process cannot access the file because 
it is being used by another process.
github.com/develar/go-fs-util.EnsureEmptyDir
        /Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:98
github.com/develar/app-builder/pkg/electron.UnpackElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:38
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.13/libexec/src/runtime/asm_amd64.s:1357  
  ⨯ E:\IssueHub\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

I had to close the editor and reopen it to compile properly.

**Comment by kzimny** [comment]
Does the error happen when your app run into an error or always? In my case I was not able to compile again when the app started with error.

**Comment by misteraries** [comment]
> Does the error happen when your app run into an error or always? In my case I was not able to compile again when the app started with error.

My application does not start, compile directly, or have this error, my application can not package now, very upset

**Comment by kzimny** [comment]
Do you try to open the compiled app in `E:\IssueHub\release\win-unpacked\yourApp.exe` before you start the next compilation? Can you describe a little bit more the steps what are you doing and what happen on your side.

**Comment by misteraries** [comment]
> 在`E:\IssueHub\release\win-unpacked\yourApp.exe`开始下一个编译之前，您是否尝试在其中打开已编译的应用程序？您能否再描述一下您正在做的步骤以及您身边发生的事情。

I directly opened vscode, and then directly ran NPM run electronic-builder build -- Windows, and then directly reported an error. Sometimes I had to restart the computer to successfully package it.

**Comment by kzimny** [comment]
can you try to run the build command in the cmd console outside of vscode (not in vscode terminal).

**Comment by misteraries** [comment]
> can you try to run the build command in the cmd console outside of vscode (not in vscode terminal).

I can try it when I get to the company. My PC is not Windows. I will reply after I try it. Thanks !

**Comment by misteraries** [comment]
> can you try to run the build command in the cmd console outside of vscode (not in vscode terminal).

Same error

**Comment by savokiss** [comment]
Same error, I can only solve this by restart my laptop

**Comment by misteraries** [comment]
> Same error, I can only solve this by restart my laptop

me too

**Comment by savokiss** [comment]
@misteraries I installed the latest VSCode v1.40.2 and now it seems ok. Or you can try close VSCode and reopen it~

**Comment by zitanlin** [comment]
> @misteraries I installed the latest VSCode v1.40.2 and now it seems ok. Or you can try close VSCode and reopen it~

close VScode work for me~~

**Comment by bei-yang** [comment]
After I close the VScode, it can be packed, otherwise it cannot be.
Why is that?
Has it been fixed?

**Comment by LeonardoRick** [comment]
One of the worse libraries setup I ever seen

**Comment by mmaietta** [comment]
Thanks for the valuable feedback on how to improve.

For anyone else, does this still repro on 22.10.5?

**Comment by thajj** [comment]
> Thanks for the valuable feedback on how to improve.
> 
> For anyone else, does this still repro on 22.10.5?

Hi, yes I am still able to reproduce it.

Yes I was able with the verssion

**Comment by bot101** [comment]
Anybody found a fix for this yet? Frustrating.

**Comment by NeneWang** [comment]
I fixed it by closing the built app.

In my case, I closed the app after testing it, and that fixed the error.

**Comment by nisith44** [comment]
close the VS code and run the command using CMD worked for me

**Comment by roymina** [comment]
fixed by: disable or remove "live server" plugin

**Comment by thkings** [comment]
after disable the extension "Live Server", it works for me

**Comment by hmsun-es** [comment]
I had the same problem with the vscode extension ".NET Core Test Explorer".

**Comment by neilenns** [comment]
For what it's worth, I just hit this as well. Closing vscode and running the package command from a terminal window solved it.

**Comment by GabrielBursi** [comment]
I deleted the dist folder and runned script to build again
