### ISSUE TITLE
Build with target: mas, app does not respond on launch

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#443]
Hi,

when I build with target: mas, the app does not respond on launch, and does not display any windows (myapp.app => 140,8Mo).
when I build without target: mas, identity, it's ok, my app respond on launch, when I click on myApp.app (myapp.app => 142,9Mo).

```
    "electron-builder": "3.25.0",
    "electron-prebuilt": "1.0.1",

    "electron-builder": "3.27.0",
    "electron-prebuilt": "1.0.2",
```

**Comment by develar** [comment]
Duplicates #436
