### ISSUE TITLE
How to get the file path when double click target file (has been associated using Electron builder)

### ISSUE THREAD

**Issue by hz0324** [electron-userland/electron-builder#4431]
I have searched the internet for a while, nothing found that can help me solve this problem.
I have used electron builder to associate file to my electron app. It works fine, when double click the file, my app opens.
Now, I need to get the path of the file. I found people saying it can be retrieved from process.argv, but I didn't see anything related to filepath in mine. 
What did I do wrong? How can I get the file path?

Please help, thank you very much.

![image](https://user-images.githubusercontent.com/5040078/69038352-97cb3980-0a24-11ea-8a92-516a41b720a2.png)

**Comment by kzimny** [comment]
I'm using SQLite database that is located/saved outside of the compiled app. In the main process check for platform and find the path.
```
const isDevMode = process.execPath.match(/[\\/]electron/);
function getDbPath(): string {
    if (isDevMode) {
        return '(this is my root in devepolment mode) ./crv/assets/data/test.db';
    } else {
        return process.platform === 'win32' ?
            '(this is the relative path to your app on win32) ./test.db' :
            path.join(path.dirname(process.execPath), '/../../../test.db');
    }
}

const dbAbsolutPath = process.platform === 'win32' ? path.resolve(getDbPath()) : getDbPath();

```
