### ISSUE TITLE
[Feature request] Option to disable update info in Mac "zip" target

### ISSUE THREAD

**Issue by garrettjstevens** [electron-userland/electron-builder#4433]
* **Version**: 22.1.0

* **Target**: Mac zip

Hello there, and thanks for the great software.

I'm trying to create a Mac ZIP file that doesn't have the update info (blockmap) appended to it (because I'm running into https://github.com/electron-userland/electron-builder/issues/3779 and https://github.com/develar/app-builder/issues/24). However, it looks like `macPackager.ts` always creates `ArchiveTarget` with `isWriteUpdateInfo` set to `true`.

https://github.com/electron-userland/electron-builder/blob/8b6580f43a3224b0afe0c9ad7739dab2769cdc68/packages/app-builder-lib/src/macPackager.ts#L75-L78

https://github.com/electron-userland/electron-builder/blob/8b6580f43a3224b0afe0c9ad7739dab2769cdc68/packages/app-builder-lib/src/targets/ArchiveTarget.ts#L12-L14

I'd like to request an option to disable `isWriteUpdateInfo` for Mac ZIP targets.

Thanks!

**Comment by CapOM** [comment]
Please re-open, still needed to avoid https://github.com/develar/app-builder/issues/24
