### ISSUE TITLE
react-scripts node-sass not excluded

### ISSUE THREAD

**Issue by infFenrir** [electron-userland/electron-builder#4434]
windows 10
node 12.13.0
electron 6.x.x - 7.x.x
electron-builder 21.2.0 

Thank you so much for your library :)

When developing i use react-scripts and node-sass, react-scripts requires installation node-sass in 'dependencies', when building the project I see in the console:
`• loaded parent configuration  preset=react-cra`
but also
`• rebuilding native dependencies  dependencies=node-sass@4.13.0 platform=win32 arch=x64`
for me it means that electron-builder excluded react-scripts but not excluded node-sass...
How to avoid this?

**Comment by kzimny** [comment]
you can exclude some folders or files in your build: { ... } part in package.json.
```
    "build": {
        "appId": "org.myorg.myapp",
        "productName": "Viewer",
        "afterSign": "crv/config/afterSignHook.js",
        "directories": {
            "output": "build"
        },
        "nsisWeb": {
            "artifactName": "${productName}-Setup-${version}.${ext}",
            "oneClick": true,
            "perMachine": false,
            "allowToChangeInstallationDirectory": false,
            "runAfterFinish": true,
            "deleteAppDataOnUninstall": true,
            "differentialPackage": true
        },
        "publish": {
            "provider": "generic",
            "url": "https://www.myapp.org/sw/${os}",
            "channel": "latest"
        },
        "files": [
            "!styles${/*}",
            "!themes${/*}",
            "!.editorconfig",
            "!.gitignore",
            "!angular.json",
            "!README.md",
            "!tsconfig.json",
            "!tslint.json",
            "!yarn-error.log",
            "!yarn.lock"
        ],
        "win": {
            "extraResources": [
                {
                    "from": "crv/assets/data",
                    "to": "../",
                    "filter": "test*"
                }
            ],
            "icon": "crv/assets/icons/icon.ico",
            "target": [
                {
                    "target": "nsis-web",
                    "arch": [
                        "x64",
                        "ia32"
                    ]
                }
            ],
            "certificateSubjectName": "my company name",
            "verifyUpdateCodeSignature": false
        },
        "mac": {
            "extraResources": [
                {
                    "from": "crv/assets/data",
                    "to": "../../../",
                    "filter": "test*"
                }
            ],
            "icon": "crv/assets/icons/icon.icns",
            "hardenedRuntime": true,
            "gatekeeperAssess": false
        }
    },
```
In my case the sass stuff is located in /themes and /styles folders.

**Comment by infFenrir** [comment]
But i do not need to rule out files scss, I need to exclude dependencies `node-sass` as he excludes `react-scripts`. Because as i understand it gets into the result bundle after assembly `electron-builder`...

**Comment by kzimny** [comment]
Maybe you need to separate your configuration into workspaces with yarn? I ran into similar problem a while ago with webpack and @angular-devkit/build-angular:browser

**Comment by infFenrir** [comment]
Yes, I understand how to do it. But since the `electron-builder` is automatically enabled `preset=react-cra` which already excludes `react-scripts`, I think he should be able to exclude and `node-sass`. But after reading the documentation I did not find anything similar. So I decided to create this issue...

**Comment by infFenrir** [comment]
Yes it is relevant :)
