### ISSUE TITLE
How to build electron application Electron + React + ExpressJS ??

### ISSUE THREAD

**Issue by topspinppy** [electron-userland/electron-builder#4437]
* **Version**:  ^22.1.0

* **Target**:  

Sorry  I don't speak English that well.

I want to build Electron With React And Express JS
In parts of React , it's No Problem 

but ExpressJS Can't Start After Build to exe 

How to solve this :'(

Package.json 
I`{
  "name": "vehecle_act_system",
  "version": "0.1.0",
  "private": true,
  "main": "./config",
  "homepage": "./",
  "author": "Mind Solution",
  "dependencies": {
    "antd": "^3.25.0",
    "axios": "^0.19.0",
    "babel-loader": "^8.0.6",
    "bootstrap": "^4.3.1",
    "electron-is-dev": "^1.1.0",
    "electron-log": "^3.0.9",
    "electron-spawn": "^5.0.0",
    "kill-port": "^1.6.0",
    "moment": "^2.24.0",
    "random-port": "^0.1.0",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-highlight-words": "^0.16.0",
    "react-loadable": "^5.5.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "reactn": "^2.2.4",
    "reactstrap": "^8.1.1",
    "styled-components": "^4.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "electron-dev": "set ELECTRON_DISABLE_SECURITY_WARNINGS=true && set ELECTRON_START_URL=http://localhost:3000 && electron .",
    "dev": "concurrently -k \"npm start\" \"wait-on http://localhost:3000 && npm run electron-dev \"",
    "electron-pack": "electron-builder -w",
    "electron-build": "yarn build",
    "prod-win": "electron-packager . vehecle_act_system --platform=win32 --arch=x64 --out dist/"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-syntax-async-generators": "^7.2.0",
    "concurrently": "^5.0.0",
    "electron": "^7.0.1",
    "electron-builder": "^22.1.0",
    "electron-packager": "^14.1.0",
    "eslint": "^6.6.0",
    "wait-on": "^3.3.0"
  },
  "build": {
    "appId": "com.mindsolution.app",
    "productName": "vehecal_act_system",
    "extends": null,
    "directories": {
      "buildResources": "build"
    },
    "files": [
      "./config/index.js",
      "node_modules",
      "*.js",
      "build",
      "backend"
    ],
    "extraResources": [
      {
        "from": "./backend",
        "to": "backend"
      }
    ],
    "win": {
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false
    }
  }
}
`
My Structure Electron React Project
![image](https://user-images.githubusercontent.com/18381211/69220760-4ba90200-0ba8-11ea-9b47-f54c3d192aa9.png)

In this picture 
Backend Folder <---- this is folder, I want to run after build to exe 

In my root file initial project
Part1
![image](https://user-images.githubusercontent.com/18381211/69220914-9dea2300-0ba8-11ea-94c3-30993f83be51.png)

Part2
![image](https://user-images.githubusercontent.com/18381211/69220934-acd0d580-0ba8-11ea-999f-20667a8a69bf.png)

Part3
![image](https://user-images.githubusercontent.com/18381211/69220949-b5291080-0ba8-11ea-831e-8a22e300af47.png)

Help me please

**Comment by momakes** [comment]
What error do you get?
