### ISSUE TITLE
How to change the folder name on AppData/Roaming

### ISSUE THREAD

**Issue by MrAmericanMike** [electron-userland/electron-builder#4438]
I have noticed that after installing an application, the installer creates a folder in AppData/Roaming.

However this folder name is all lowercase.

Where is electron-builder taking this name from, and how can I Capitalize it?

**Comment by kzimny** [comment]
this is the of the package:
![image](https://user-images.githubusercontent.com/12007674/69484182-9ccb2700-0e30-11ea-9661-b10a6ac86dd8.png)
Well, I don't think you can capitalize the name.

**Comment by MrAmericanMike** [comment]
I used Capitalization there. (Even when it's technically not recommended) but after installing the folder was still all lowercase.

**Comment by kzimny** [comment]
Solution: don't use capitalization there.

**Comment by MrAmericanMike** [comment]
> 
> 
> Solution: don't use capitalization there.

Well, when going to the Romaing folder, most applications use capitalization. I know it's not big deal, but I would like to be able to display my app name there with capitalization. In my opinion it looks better and more professional.

**Comment by leopucci** [comment]
Seems to be a small detail but to have a great product you have to care for details. 
Nsis is removing a period from productName: Name.Test and also lower casing the first letter.
