### ISSUE TITLE
Publish to network drive

### ISSUE THREAD

**Issue by michaeljpeake** [electron-userland/electron-builder#4439]
I'm writing software to be used in-house at a company. They are not keen to have builds of their software published on the internet. Instead, they would like to have it stored on a network drive.

Is there a way to publish to a network drive, such that the electron-updater will work?

**Comment by kzimny** [comment]
Did you try with the network path?
```
        "publish": {
            "provider": "generic",
            "url": "\\myServerXYZ\software\${os}",
            "channel": "latest"
        },
```

**Comment by deleoeduardo** [comment]
I have the same scenario. I need to update my electron app through a windows network drive, maybe I can develop a custom solution but I think that someone have solved this issue before.
