### ISSUE TITLE
How can I use afterPack?

### ISSUE THREAD

**Issue by lzdnku307** [electron-userland/electron-builder#444]
Since sqlite3 needs to rename manually after rebuild, so I need to use afterPack. But It didn't work.
My code:
```
//build
builder.build({
    platform: [builder.Platform.OSX],
    devMetadata: {
      build: {
        ignore: ignoreFunc(),
        afterPack: function() {
          console.log('after pack!!!!!!!!!!!!!!!!!!');
         renameSqlite3();
          return Promise.resolve();
        }
      },
    }
  })
  .then(() => {
    // handle result
  })
  .catch((error) => {
    // handle error
    console.log(error);
  });
```

**Comment by develar** [comment]
electron-builder version?

**Comment by lzdnku307** [comment]
@develar 
electron-builder 3.17.1

Options

  -d, --dist             Whether to package in a distributable format (e.g. DMG, windows installer,
                         NuGet package).
  -p, --publish string   Publish artifacts (to GitHub Releases): onTag (on tag push only) or
                         onTagOrDraft (on tag push or if draft release exists).
  --platform string[]    darwin, linux, win32 or all. Current platform (darwin) by default.
  --arch string          ia32, x64 or all. Defaults to architecture you're running on.
  --sign string
  -h, --help             Display this usage guide.

  Project home: https://github.com/electron-userland/electron-builder

**Comment by develar** [comment]
Release notes is clear — https://github.com/electron-userland/electron-builder/releases — this feature was added in the `3.25.0`

**Comment by darkguy2008** [comment]
Still the bug/documentation is not enough to know how does this work. There's no provided example on how to use an external file, for instance.
