### ISSUE TITLE
quitAndInstall() will not restart the app if BrowserWindow closable option is set to false

### ISSUE THREAD

**Issue by jsheffers** [electron-userland/electron-builder#4440]
* **electron-builder: 22.1.0**: 

* **electron-updater: 4.2.0** 

* **Mac, Win**: 

Using the auto-updater it is not possible to set the `closable` property to `false` and still use the `quitAndInstall()` function.   It would be great if this function could bypass that setting (maybe this is already possible?).  Our use case requires the user not be able to close the app, but we'd like for it to close itself when `quitAndInstall()` is run.  Is this possible?

**Comment by jsheffers** [comment]
After digging into this further it looks like quitAndInstall() is actually using the native electron function.  This function calls `this.app.quit()`, which is simply a request to close all windows.  This means any windows that are defined with `closable=false` will decline to close.  To me, it seems like this function should call `app.exit()` to guarantee an immediate app closure.  This might be better suited in the electron issue queue, however.

**Comment by kaitlynbrown** [comment]
I wish I had found this issue before spending the entire day tediously debugging auto update.

Please re-open this issue as it absolutely needs to be fixed.
