### ISSUE TITLE
Automatic update error

### ISSUE THREAD

**Issue by storagess** [electron-userland/electron-builder#4442]
electron-builder: 21.2.0
electron-updater: 4.2.0
electron：7.1.1
Target: Windows

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

[确定]

Switching to electron 6.14 is fine

**Comment by kzimny** [comment]
Check for existing internet connection in your main process before start the updater

**Comment by p-smith** [comment]
I experienced the same issue with Electron 7.1.1. Two error messages appear in succession with "Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE". The HTTP response code failure is a 404 status when the 2 blockmap files are requested. Since I don't use the blockmaps, the requests end with 404 Not Found. It looks like this is only a problem in Electron 7.1.1 or newer.

**Comment by Ryuurock** [comment]
+1

**Comment by danielehrhardt** [comment]
Could we somehow handle this Error Response? Not with this Message:
https://i.imgur.com/srmybs9.png

**Comment by halfmagic** [comment]
Using 7.1.1, enabling differential download option on package.json made this error message disappear, but checking blockmap process is too long and I want to skip it, anyway after analyzing, it downloads the full installer

**Comment by OcULaR-Krowned** [comment]
Just got this error as well here is my versions etc:
"devDependencies": {
    "electron": "^7.1.1",
    "electron-builder": "^22.4.1"
  },

  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.11.2",
    "animate.css": "^3.7.2",
    "bootstrap": "^4.3.1",
    "electron-updater": "^4.2.5",
    "jquery": "^3.4.1",
    "popper.js": "^1.16.0",
    "socket.io": "^2.3.0"
  },

**Comment by NeroVanbiervliet** [comment]
This error also appears on macOS when your app is not signed

**Comment by SinusPi** [comment]
Does this eventually get fixed, somewhere within the Electron 7.x -> Electron 12.x timeline? Apparently the problem is somewhere within Electron's http core, as electron-updater has all errors within the blockmap-downloading section nicely caught, and yet the error bombs...
