### ISSUE TITLE
Parameters for silent install for .exe, .dmg, .appimage output of Electron Build

### ISSUE THREAD

**Issue by rharish100193** [electron-userland/electron-builder#4445]
* **Version**: 21.0.15

* **Target**: Window, Linux and Mac

What are the parameters to install the output _**.exe**_ files of windows and _**.pkg**_ files of mac if we want to install it silently.
Like Thunderbird for Mozilla - [Thunderbird Silent Installation Arguments](https://wiki.mozilla.org/Installer:Command_Line_Arguments)

**Comment by rharish100193** [comment]
I think I found a solution.
[https://gitlab.ow2.org/RocketChat/Rocket.Chat.Electron](
https://gitlab.ow2.org/RocketChat/Rocket.Chat.Electron)

**Windows Options**
On Windows you can run a silent install by adding the _**/S**_ flag. You can also add the options below:


**/S** - Silent install

**/allusers** - Install for all users (requires admin)

**/currentuser** - Install for current user only (default)

**/disableAutoUpdates** - Disable autoupdates (Application will not update automatically / User can't update via dialog )

**Comment by Rajdeep97** [comment]
Any way to specify the directory to install to during silent install?

**Comment by kungfux** [comment]
> Any way to specify the directory to install to during silent install?

@Rajdeep97 `/D` e.g. `setup.exe /D="path"`

**Comment by H4kt** [comment]
Is there a way to still create a shortcut on the desktop?

**Comment by PAXANDDOS** [comment]
A way to auto-open the application after silent installation?

**Comment by hello1101n** [comment]
> A way to auto-open the application after silent installation?

myAppInstaller.exe /S --force-run

--force-run
