### ISSUE TITLE
Can publish step be run separately?

### ISSUE THREAD

**Issue by andrewghobrial** [electron-userland/electron-builder#4447]
electon-builder: 21.2.0

electron-updater: 4.2.0

**Target**: 

Win: nsis, msi
Mac: dmg, zip

Our unsigned app is sent off separately to get signed before we get it back. Is it possible to run a publish-only command to correctly publish the returned signed artifact?

**Comment by ShadixAced** [comment]
What you could do is to ask for electron-builder not to publish your files, and then codesign it using another program and publishing it through GitHub by an API.

**Comment by andrewghobrial** [comment]
This won't work because the hashsum of the output will have changed after signing. electron-builder has to create the latest.yml file for auto updating to work.

**Comment by abarsov** [comment]
We have the same issue in our build infrastructure.
Signing of all distributives is done by dedicated sign server, CI server that run electron-builder has no direct access to signing certificate.

**Comment by andrewghobrial** [comment]
I wonder if it's possible to use a script in the afterPack hook to call the remote signing API.
