### ISSUE TITLE
Fails to build for Win32 platform on MacOS Catalina

### ISSUE THREAD

**Issue by erichs** [electron-userland/electron-builder#4448]
* **Version**: 20.40.2

* **Electron-Updater**: 4.0.6

* **Target**: Win32

Cross-linking with [this issue](https://github.com/electron-userland/electron-builder-binaries/issues/30), as I'm not sure where it belongs.

It appears that MacOS Catalina [no longer supports any 32-bit compatible binaries](https://discussions.apple.com/thread/250716875).  Attempting to build for the `win32` platform on MacOS Catalina produces an error of the form:

```
• packaging       platform=win32 arch=x64 electron=5.0.1 appOutDir=dist/win-unpacked
  • downloading               parts=8 size=62 MB url=https://github.com/electron/electron/releases/download/v5.0.1/electron-v5.0.1-win32-x64.zip
  • downloaded                duration=4.605s url=https://github.com/electron/electron/releases/download/v5.0.1/electron-v5.0.1-win32-x64.zip
  • downloading               parts=1 size=5.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloaded                duration=1.121s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloading               parts=4 size=26 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z
  • downloaded                duration=2.325s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z
  ⨯ error: fork/exec /Users/erichs/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine: bad CPU type in executable
```

**Comment by ShadixAced** [comment]
Part of WINE might be 32-bit, which will not run on OSX Catalina. Please see if there's any fork or "32-bit-free" version of WINE.

**Comment by jsheffers** [comment]
Use docker, this is what I currently have to do:  https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine

**Comment by erichs** [comment]
Thanks, @jsheffers! Indeed that works. It still might be nice to support native cross-platform build on Catalina. Perhaps as @ShadixAced suggests, there's a 64-bit-only version of WINE the project could adopt?

**Comment by gillisig** [comment]
> (Wine won't work on macOS Catalina 10.15). 

From https://wiki.winehq.org/MacOS

Just thought I'd share that since I ran across it when installing wine and remembered this issue.

**Comment by digason** [comment]
Now that Crossover can run on Catalina, it's only a matter of time before pure Wine is able to do the same. I feel like this is a high enough probability, that this issue remain open, as it should be solvable in theory.  If not now, sometime this year.

https://www.codeweavers.com/about/blogs/jwhite/2019/12/10/celebrating-the-difficult-the-release-of-crossover-19

**Comment by jsheffers** [comment]
This is fixed using the latest build of EB
