### ISSUE TITLE
Failed to build with Electron 7.0.0 on MacOS

### ISSUE THREAD

**Issue by quynk94** [electron-userland/electron-builder#4449]
* **Electron-builder:** 22.1.0
* **Electron:** 7.0.0
* **Target:** Mac 

I cloned [electron-webpack-quick-start](https://github.com/electron-userland/electron-webpack-quick-start) project, then change version of electron to `7.0.0`. when i run `yarn dist`, i encountered this error:
![Screen Shot 2019-11-21 at 4 56 24 PM](https://user-images.githubusercontent.com/8005041/69394058-7a8cb880-0d0d-11ea-97e7-5856c649ba6e.png)

Change back to `5.0.6` is fine.

**Comment by momakes** [comment]
@quynk94 FWIW, I'm on electron `7.1.2` (basically like 7) and the same electron-builder version, but it builds successfully. 

It _probably_ is a problem with having different python versions installed, but might be otherwise.
Try running `echo $PATH` and make sure all paths are valid in there.

**Comment by ShadixAced** [comment]
As the error message says, it seems that it cannot find Python installed in your machine (or the PATH written isn't the good one)

Best bet would be to reinstall Python and letting it rewrite the PATH environment.

**Comment by quynk94** [comment]
@momakes @ShadixAced 
Thank you for yours supports. My Python is installed in `/usr/local/bin/python`, just need to create link to `/usr/bin/python`
