### ISSUE TITLE
Allow to Add Release Notes

### ISSUE THREAD

**Issue by shockone** [electron-userland/electron-builder#445]
When creating a release draft on Github, I'd like to be able to specify the draft's body.

**Comment by develar** [comment]
You can just create it on Github before build. Is it suitable for you?

**Comment by shockone** [comment]
That's what I do now, but it means I have to manually deal with Github API, which would otherwise be handled by `electron-builder`. It already knows my token, release ID and stuff like that.

**Comment by develar** [comment]
Do you mean that
* you want to specify draft's body template
* or https://github.com/semantic-release/release-notes-generator/
* or grab from somewhere (History.md)?

**Comment by shockone** [comment]
The first option.
