### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Floffah** [electron-userland/electron-builder#4453]
* **Version**: 22.1.0

* **Target**: win32/linux(deb,tar.gz)

I am using windows 10 1903 latest
When i build my app, i get this
All code is [here](https://github.com/Floffah/rigglscholar/)
i ran `npx electron-builder -p always -l -w` to get this.
```
Get https://service.electron.build/find-build-agent?no-cache=1etg91m: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  
  ⨯ E:\projects\unfinished\app\rigglscholar\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

**Comment by kzimny** [comment]
Did you try to build for one platform only? `npx electron-builder -p always -l` or `npx electron-builder -p always -w` v22.1.0 is very buggy.

**Comment by Floffah** [comment]
@kzimny yes. i tried building it for both seperately and just for the deb file. when i build it to the deb no matter what i get a connection failed error even in 21.2.0

**Comment by kzimny** [comment]
Found in electron-builder [documentation](https://www.electron.build/configuration/publish#github-repository-and-bintray-package) and npm [documentation](https://docs.npmjs.com/files/package.json#repository). 
Question: why do you use git+ https:
```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Floffah/rigglscholar.git"
  }
```
instead of:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/Floffah/rigglscholar.git"
  }
```

**Comment by Floffah** [comment]
i didn't, it was what the `npm init` wrote because i had already initialised the git workspace and npm picked that up. anyway, thanks!

**Comment by kzimny** [comment]
does it work as expected now?

**Comment by Floffah** [comment]
nope

**Comment by kzimny** [comment]
Try to build for windows only and see what happen.
https://github.com/electron-userland/electron-builder/issues/3569

**Comment by Floffah** [comment]
i've already done that and tracked it down to deb and snap
