### ISSUE TITLE
Could not find module electron-v5.0-win32-x64\node_sqlite3.node

### ISSUE THREAD

**Issue by techuila** [electron-userland/electron-builder#4458]
I tried building my app on my mac to windows by the command vue-cli-service electron:build --windows
But after running it on a windows environment, it doesn't have sqlite3 on a windows platform, it only has for its own environment which is darwin. How do I solve this?

**Comment by ShadixAced** [comment]
SQlite3 is a native module and needs to be compiled. Could you please make sure that this depedency is compiled by either electron-builder or either by v8 ?

**Comment by techuila** [comment]
It's compiled by electron-builder. So to solve this issue, I would just have to compile it on a windows  machine to get it to work?

**Comment by kzimny** [comment]
In my project I compile for mac and windows separately. The SQLite driver is platform dependent and need to be compiled on the target os. You need to compile on windows to get the SQLite work.

**Comment by techuila** [comment]
Ok got it. 
Thanks for clarifying it to me.
