### ISSUE TITLE
Auto-update installer loops if old version is still running (NSIS)

### ISSUE THREAD

**Issue by jsheffers** [electron-userland/electron-builder#4463]
* **electron-builder: 22.1.0**: 

* **electron-updater: 4.2.0**: 

* **Mac**: 

I've set up auto-updating with S3 using the NSIS installer (non-web).  My application only checks for updates each time it's open.  I'm running into a install loop in Windows 10 under the following conditions.

1. Install version 1.0.0 on Windows 10 (latest version on S3)
2. Publish version 2.0.0 to S3
3. Leave the current 1.0.0 app open on the Windows machine
4. Double click the application icon again to open a new instance of the app

Following this sequence means I have two instances of the same application running.  One is the older 1.0.0 version which won't get a new update until restarted, and the other is a new instance of 1.0.0 which is now aware that there is a new version 2.0.0.  In this circumstance, the application that is trying to auto-update will get into an install loop and never finish **unless** I manually close the other version of the app that is not aware of the updates.  After closing the old version of the application the installer does stop looping and installs the new version, but in my case, I can't know if the user will already have a version of the application running.

Obvious fixes would be:

1. Don't allow the application to be opened more than once (probably out of scope for this repo)
2. Kill any processes via the auto-updater somehow

Has anyone else run into this issue?  Is it possible to fix this from this codebase?

**Comment by kzimny** [comment]
I would suggest to check if more than one instance is running and if so close the second one.

**Comment by jsheffers** [comment]
Yep, the following fixes this issue:

```
app.requestSingleInstanceLock();
app.on("second-instance", (event, argv, cwd) => {
  app.quit();
});
```
