### ISSUE TITLE
How to define the www folder?

### ISSUE THREAD

**Issue by RafaeldelM** [electron-userland/electron-builder#4464]
Hello,
I would like to define where I  have the built project. Do you know how I can do it?

My project is done in Angular, and I have the build results in a www folder. How I can specify to electron-builder just get from there? I was checking and there is /src/rendered, but it request a index.js file, and angular the entry file is index.html.

Thanks,

**Comment by kzimny** [comment]
I don't think you can use the standard angular CLI compilation and electron-builder CLI to compile for your final app. Check the boilerplates https://www.electron.build/#boilerplates Maybe you will find one of them useful. To get angular project work with electron compile your angular project with webpack https://v5.angular.io/guide/webpack#common-configuration. Other useful tutorial:
https://www.freecodecamp.org/news/how-to-configure-webpack-4-with-angular-7-a-complete-guide-9a23c879f471/
In electron you always work with main and renderer process. The goal is to compile the code for main (electron) and renderer (angular) process in one build in order them work together. 
You can configure the main process in mainConfig and renderer in rendererConfig as follow:

![image](https://user-images.githubusercontent.com/12007674/69564671-b648ac00-0fb3-11ea-9513-bbfcf7d71373.png)

In mainConfig you can set the entry point and output path:
![image](https://user-images.githubusercontent.com/12007674/69565879-1f312380-0fb6-11ea-8ab1-748cbbde18de.png)

The next step are the build commands. You can run the command for production and development separately:

```
    "scripts": {
        "electron-builder": "electron-builder .",
        "build-prod": "webpack --config webpack.prod.js --progress --color",
        "run-dev": "webpack --config webpack.dev.js --watch --progress --color --inline",
        "run-prod": "npm-run-all --sequential build-prod electron-builder"
    },
```

set the name in main variable in package.json to let electron know which file is responsible for the main process:
```
{
    "name": "myapp",
    "productName": "myapp",
    "version": "1.0.0",
    "description": "My first app",
    "main": "./main.bundle.js",
}

```

Of course, my short my short description is very superficial, but it should help to understand the idea how to get angular and electron parts work together.

**Comment by RafaeldelM** [comment]
Hi Kzimmy,
Thanks a lot for your explanations.  
I don't understand why I need webpack? In the end, a build angular project is like an Html file. 
Can I use electron-builder without webpack?
Thanks,

**Comment by kzimny** [comment]
This is not as easy as you imagine. Maybe take a look at electron fundamentals https://codeburst.io/electron-basics-and-fundamentals-b85b23aa611d You work at least in two processes: electron (the main process) and the renderer (angular) process. I assume that you work with typescript. Then you definitely want the two processes to communicate. My explanation should show how to compile the main and renderer code together. At least you have to inject the compiled files from renderer process into the index.html file.
If you follow a different approach in which the processes do not need to communicate with each other you can compile your angular and electron projects separately.

**Comment by RafaeldelM** [comment]
Thank you Kzimmy!
