### ISSUE TITLE
`--publish onTag` only works in specific CIs

### ISSUE THREAD

**Issue by thisismydesign** [electron-userland/electron-builder#4469]
* **Version**: 21.2.0 & master

* **Target**: all

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-publish/src/publisher.ts#L98-L101

This gave us some headaches using GitHub Actions and wouldn't work locally either.

As is: `--publish onTag` only supports a set of specific CIs. This is [not documented](https://www.electron.build/configuration/publish).

Expected: if this remains the case the exact behavior should be documented. However, the correct behavior could be achieved by relying on `git` instead.

For example the following pseudo-code returns whether there's a tag checked out:
`!(git symbolic-ref -q HEAD) && (git describe --tags --exact-match)`

See also: https://stackoverflow.com/questions/18659425/get-git-current-branch-tag-name

**Comment by tgxn** [comment]
Still seems problematic that this only supports GitHub and Bintray.
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/publish/PublishManager.ts#L162

**Comment by thisismydesign** [comment]
The link above using fixed lines: https://github.com/electron-userland/electron-builder/blob/e7179b57bdba192acfdb439c03099e6629e98f6a/packages/app-builder-lib/src/publish/PublishManager.ts#L165-L168

**Comment by ScubaDrew** [comment]
Does not seem to work correctly on GitLab. Tags result in `current build is not for a git tag`
