### ISSUE TITLE
401-unauthorized token with bad credential while publishing the new update to git hub

### ISSUE THREAD

**Issue by Karthik7Nayak** [electron-userland/electron-builder#4472]
* **Version**:     "electron-builder": "^21.2.0",

* **Target**: appImage

this is my package.json .First time deploy worked and successfully published to git hub.next I did some changes and tried to deploy but throws stated error

"scripts": {
      "deploy": " electron-builder build  --publish always"
 },
"build": {
      "appId": "com.electron.eliteGamer",
      "compression": "normal",
      "extends": null,
      "files": [
            "*.js",
            "build",
            "dist",
            "renderer"
      ],
      "mac": {
            "target": "zip"
      },
      "linux": {
            "target": [
                  "AppImage",
                  "zip"
            ]
      },
      "win": {
            "target": "squirrel"
      },
      "publish": {
            "provider": "github",
            "repo": "Demo",
            "owner": "xyz",    
            "token": "2***********7"
      }
  }

**Comment by kzimny** [comment]
Did you try to set the host in publish config? Check with another options https://www.electron.build/configuration/publish.html#githuboptions.
What is the error exactly? State error????
