### ISSUE TITLE
Error: Can't distribute in linux

### ISSUE THREAD

**Issue by BeatPlus** [electron-userland/electron-builder#448]
When attempting to distribute in Linux (Ubuntu 14.04), npm returns me an error and fails to build binaries. I tried creating x64 and ia32, same result.
Here is the error log: 
http://pastebin.com/raw/ikhGJVKw

And the commands returned by the console:
http://pastebin.com/raw/D3GNckvT

My package.json
http://pastebin.com/raw/HU0tAMjP

Some people also told me they are getting troubles with OSX, `electron-builder` does not install app dependencies for them. I will contact them and provide more info

**Comment by develar** [comment]
Please install icnsutils  and other requires system packages, see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux

**Comment by BeatPlus** [comment]
I now have all required system packages installed, I still get the following errors:
http://pastebin.com/raw/iG2aB6ze

It seems there is an error with icon and another bug with the final path, which attempts to write in `linux-` rather than `linux`

**Comment by develar** [comment]
Do you use pre-release electron-builder 4.x?

**Comment by BeatPlus** [comment]
I am using electron-builder@4.1.0

**Comment by develar** [comment]
@BeatPlus Yeach, it is known regression. Fix will be tomorrow. Until that you can use release version v3.25.0.

**Comment by BeatPlus** [comment]
@develar Great, but I still get an error using v3.25.0, it fails to create icon from Icon.icns. This is my log
http://pastebin.com/raw/7XT5Ueze

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/239

* `icns2png --version`?
* https://github.com/electron-userland/electron-builder/issues/239#issuecomment-215676565 Please check.
* https://github.com/electron-userland/electron-builder/issues/239#issuecomment-215680424 i.e. you can just "or "build/icons directory — filename must contains size (e.g. 32x32.png))"

**Comment by BeatPlus** [comment]
@develar It now works, I manually fixed some troubles `icns2png` was having. 
Thank you! I'll close the issue

**Comment by develar** [comment]
>  I manually fixed some troubles icns2png was having. 

Could you please describe what exactly? Or icns2png is just broken?

**Comment by BeatPlus** [comment]
@develar It was just broken, I do not really know why. I purged it and check other dependencies if they were causing troubles. None of them seemed like, so I just reinstall icns2png and problem was fixed.
