### ISSUE TITLE
help!!! my local storage file can’t build for my app,how can i do ?

### ISSUE THREAD

**Issue by lazyliang** [electron-userland/electron-builder#4481]
my package.json 
`"build": {
    "appId": "com.example.electron-cra",
    "files": [
      "build/**/*",
      "node_modules/**/*",
      "public/**/*",
       "/electron.js",
      "/path/**/*"
    ],
    "directories": {
      "buildResources": "assets"
    }`
my data file is in the path/**/* ,and then failed.

how can i do?

**Comment by kzimny** [comment]
try to remove the slash before path `path/**/*` instead of `/path/**/*`. What you are you mean with local storage? extraResources https://www.electron.build/configuration/contents.html#extraresources? What failed?

**Comment by lazyliang** [comment]
> try to remove the slash before path `path/**/*` instead of `/path/**/*`. What do you mean with local storage? extraResources https://www.electron.build/configuration/contents.html#extraresources? What failed?

Thanks kzimny, I solve this question , change asar to false, and then change the path in main.js to
Var Datastore = the require (' nedb '),
Db = new Datastore({filename:path.join(s,'public/datafile')}); .
As shown below package.json:
```
"build": {
    "appId": "com.example.electron-cra",
    "files": [
      "build/**/*",
      "node_modules/**/*",
      "public/**/*",
      "main.js",
      "datafile",
      "path/**/*",
      "package.json"
    ],
    "mac": {
      "icon": "public/icon/tangerine.png"
    },
    "asar": false,
    "directories": {
      "output": "dist"
    }
  },

```
My directory structure is a bit messy, do you have a better structure recommendation, thanks again！
