### ISSUE TITLE
Useless programmatic API docs

### ISSUE THREAD

**Issue by KaKi87** [electron-userland/electron-builder#4483]
* **Version**: 21.2.0

* **Target**: Windows & Linux

Hello,

I have a [VueJS](https://github.com/vuejs/vue) app bundled with [ParcelJS](https://github.com/parcel-bundler/parcel/tree/1.x) and I'd like to build it programmatically.

However, the [programmatic API documentation](https://www.electron.build/api/electron-builder) doesn't explain anything about how to do anything.

Here are the details :
* Parcel bundler transpiles into `./dist`
* I'd like Electron Builder to compile `.appx` and `.appimage` files into `./release`
* 64-bit only

Thanks

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
Up

**Comment by redbrain** [comment]
Yikes. I want to do something similar and the API says basically nothing. Does anyone know anything?

**Comment by KaKi87** [comment]
Unfortunately, I still got no answer so I'm stuck with `electron-packager` for now, which doesn't provide `.appx` nor `.appimage` builds. :/

**Comment by KaKi87** [comment]
> what is blocking it?

The lack of answers from authors.

**Comment by KaKi87** [comment]
Up

**Comment by redbrain** [comment]
Up

**Comment by JJ-8** [comment]
Why don't you just write a script in your packages.json that does the job for you? So a bit like this:
 
```
[parceljs command] && [electron builder command]
```
And you configure electron builder in such a way that it takes the dist output as input and you set the appx config correctly.
Then you can just invoke it from the command line and it will be build for you automatically. No need to use any internal APIs.

**Comment by KaKi87** [comment]
I prefer building from a [`build.js`](https://git.kaki87.net/KaKi87/template-electron-vue-parcel/src/branch/master/build.js) script and only have `"build": "node ./build.js"` in [`package.json`](https://git.kaki87.net/KaKi87/template-electron-vue-parcel/src/branch/master/package.json) for it to be easier to read.

**Comment by Vaggal** [comment]
Up

**Comment by KaKi87** [comment]
Up

**Comment by mmaietta** [comment]
Here's a preview of the latest generated API docs
https://jolly-roentgen-9c9aba.netlify.app/api/electron-builder.html

**Comment by KaKi87** [comment]
So I suppose those are generated from JSDoc, could you please add `@description` tags ?

Names of modules, methods, arguments and return values aren't really helpful here :/

**Comment by mmaietta** [comment]
That's a pretty big ask for just one contributor to add retroactively to all functions.

Perhaps you could request a few/several functions in particular that would be useful and what you're looking for exactly out of it?
I've never written tech docs before, so I'm somewhat interested in contracting someone do to so that already has the expertise (and time).

I've also added an example from one of my project setups using the API.
https://jolly-roentgen-9c9aba.netlify.app/api/programmaticusage

**Comment by Vaggal** [comment]
Would it be useful to create an issue for the `@description ` tags so that it can be tackled bit by bit if someone has the will to do it, or at least do some functions.

@mmaietta thanks for the example, I was in the process of adding one myself.

**Comment by mmaietta** [comment]
I suppose so? It might be more constructive than the title of this issue... 😕

**Comment by KaKi87** [comment]
Sorry for that issue title.
2 years ago, I was angry at the time, because I spent many time looking for answers to my question.
I asked to so many communities on Reddit, Discord, Gitter, Slack, etc. and never got any answer, not a single one.

However I think that underestimating the value of API docs is bad, we might be a few who asked for it, but I'm pretty sure many people like me are stuck with electron-packager because it's the one which has usable API docs.

I'll have a look at the example though, thanks.

**Comment by KaKi87** [comment]
> That's a pretty big ask for just one contributor to add retroactively to all functions.

Well, I'm sorry for saying this but, if this work would have began two years ago, it would have been done by now.

> Perhaps you could request a few/several functions in particular that would be useful and what you're looking for exactly out of it?

For that I would have to already know which ones I need, but I don't.
However you can have a look at my original message to see what I need.

**Comment by KaKi87** [comment]
I just had a look at the examples : it contains many callbacks and parameters which aren't really self-explanatory and some contains calls to functions that aren't defined in the example itself 🤔

**Comment by mmaietta** [comment]
You sure you didn't read the configuration docs?

```
builder.build({
  targets: Platform.LINUX.createTarget(),
  config: options // Your electron-builder.js config object. Literally the same structure as electron-builder.js/electron-builder.yaml and in the package.json "build" entry
})
```

```
const options = {
    files: [
        "dist"
    ],
    directories: {
      output: "release"
    },
    win: {
        target: {
            target: 'appx',
            arch: 'x64'
        },
    },
    linux: {
        target: {
            target: 'AppImage',
            arch: 'x64'
        },
    },
};
```

**Comment by KaKi87** [comment]
Thank you, but here's what I get :
```
(node:18826) UnhandledPromiseRejectionWarning: TypeError: types is not iterable
    at processTargets (/home/user/Documents/project/node_modules/app-builder-lib/src/packager.ts:203:26)
    at new Packager (/home/user/Documents/project/node_modules/app-builder-lib/src/packager.ts:219:7)
    at Object.build (/home/user/Documents/project/node_modules/electron-builder/src/builder.ts:212:31)
    at /home/user/Documents/project/build.js:14:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by KaKi87** [comment]
@mmaietta Please ?

**Comment by mmaietta** [comment]
You really should debug further on your own... or at least describe what you've tried already.
Spitballing here based on your error message of "not iterable" in `processTargets(...)`, convert `target` into an array, like below, for both OS configs.
```
        target: [{
            target: 'AppImage',
            arch: 'x64'
        }]
```

**Comment by KaKi87** [comment]
> You really should debug further on your own

I would if there were proper documentation that I could use, which is what this GitHub issue is about, after all.
Otherwise, I have no idea how could I be able to debug this.
All I can do is get the link to [`app-builder-lib/src/packager.ts:203:26`](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/packager.ts#L203), but I don't know how to read this.

> at least describe what you've tried already

I did what you told me to do :
```js
const electronBuilder = require('electron-builder');
await electronBuilder.build({
    targets: electronBuilder.Platform.LINUX.createTarget(),
    files: ['dist'],
    directories: {
        output: ['build']
    },
    win: {
        target: [{
            target: 'appx',
            arch: 'x64'
        }],
    },
    linux: {
        target: [{
            target: 'AppImage',
            arch: 'x64'
        }],
    }
});
```
But I am still experiencing this error.
Thanks

**Comment by Vaggal** [comment]
@KaKi87 The structure should be:
```javascript
const electronBuilder = require('electron-builder');
await electronBuilder.build({
    targets: electronBuilder.Platform.LINUX.createTarget(),
    config: {
        files: ['dist'],
        directories: {
            output: ['build']
        },
        win: {
            target: [{
                target: 'appx',
                arch: 'x64'
            }],
        },
        linux: {
            target: [{
                target: 'AppImage',
                arch: 'x64'
            }],
        }
    }
});
```

Notice the `config` property that you have omitted in your example.

**Comment by KaKi87** [comment]
*Mea culpa*. I ran into a few more errors after that, but I got almost everything working using the following code, and even (surprisingly) easily added Mac support.
```js
await electronBuilder.build({
    targets: {
        'linux': electronBuilder.Platform.LINUX.createTarget(),
        'win32': electronBuilder.Platform.WINDOWS.createTarget(),
        'darwin': electronBuilder.Platform.MAC.createTarget()
    }[process.platform],
    config: {
        files: fs.readdirSync('.', { withFileTypes: true })
            .filter(item => ![
                '.git',
                '.gitignore',
                'build.js',
                'README.md',
                'yarn.lock',
                ...fs.readFileSync('./.gitignore', 'utf8')
                    .split('\n')
                    .filter(path => !['dist', 'node_modules'].includes(path))
            ].includes(item.name))
            .map(item => `${item.name}${item.isDirectory() ? '/**' : ''}`),
        directories: {
            output: 'build'
        },
        win: {
            target: [{
                target: 'appx',
                arch: 'x64'
            }],
        },
        appx: {
            applicationId: name.split('-').map(substring => `${substring[0].toUpperCase()}${substring.slice(1, substring.length).toLowerCase()}`).join('')
        },
        linux: {
            target: [{
                target: 'AppImage',
                arch: 'x64'
            }],
        },
        mac: {
            target: [{
                target: 'dmg'
            }]
        }
    }
});
```
However, the `.appx` file seem unusable on Windows : even with [developer mode](https://www.tenforums.com/attachments/tutorials/294509d1598386508-turn-off-developer-mode-windows-10-a-turn_on_developer_mode_in_settings-1.jpg?s=266faac9aa5b00d4df57811c7025014f) enabled. Does it mean code signing is unavoidable ? If yes, what's the easiest way to do it programmatically ? Thanks

**Comment by Vaggal** [comment]
@KaKi87 you should read the docs more carefully. [AppX Package Code Signing](https://www.electron.build/configuration/appx#appx-package-code-signing)

Personally I would suggest either submitting it in the store or switching to NSIS.

Anyway, this conversation adds no value to the original issue.

**Comment by KaKi87** [comment]
> you should read the docs more carefully

I did. I firstly got [there](https://www.electron.build/configuration/appx#appx-package-code-signing) then [there](https://www.electron.build/code-signing#windows) then [there](https://www.electron.build/configuration/win#WindowsConfiguration-certificateSubjectName), and also [there](https://www.electron.build/tutorials/code-signing-windows-apps-on-unix.html#integrate-signing-with-electron-builder) through Google search.

However, it does not say anywhere how to actually generate the certificate file.

> I would suggest either submitting it in the store or switching to NSIS

My current project is a developer tool for AWS Serverless, so not something that is meant to be on the Microsoft Store.
