### ISSUE TITLE
Placing Icon in Build Folder doesnt Function, also Portable icon isnt default Electron Icon

### ISSUE THREAD

**Issue by skylerspark** [electron-userland/electron-builder#4486]
* **Version**: 21.2.0
* **Target**: Windows [Portable]

I have tried setting my Icon via the Package,json, I also tried using 'path' and browserWindow to set it, And FINALLY i tried setting it by removing all ICON changes in the whole project, then simply placing my icon.png and icon.ico in the build folder.

Still NOTHING. This is seriously starting to piss me off how something so simple is so difficult to get working on this project.

also, I dont know if this is a bug or relative issue, but when you use Electron-builder with windows target ['portable'], the outputted EXE uses an Installer Icon rather than the default Electron Icon (Or whatever you set that to, but I CANT, so thats a bit out of the current league)

Docs are extremely low-density and barely give any notation to how to use the icons besides placing them in the build folder (Which I did) (which doesnt actually work)

Any ideas here? Im Aggravated and Annoyed, and Id like my project to just have an icon...

**Comment by radetsky** [comment]
Same here. Need help. How to place the icon for Windows Portable binary?

**Comment by 4vomAst** [comment]
When building a portable package on Windows, the main window and taskbar icon is correct. But the portable exe icon is wrong. The exe contains always the default installer icon.

`
{
  "name": "launcher",
  "version": "0.0.1",
  "description": "Native launcher",
  "main": "index.js",
  "dependencies": {
    "electron-serve": "^0.4.1"
  },
  "devDependencies": {
    "electron": "^7.1.14",
    "electron-builder": "^22.4.0"
  },
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "electron-builder install-app-deps",
    "electron-dist": "electron-builder"
  },
  "build": {
    "productName": "MyProduct",
    "appId": "my.launcher",
    "win": {
      "target": ["portable"],
	  "icon": "build/icon.ico"
    },
    "nsis": {
	  "installerIcon": "build/installerIcon.ico"
    },
    "portable": {
      "artifactName": "launcher.exe"
    }
  },
  "author": "Company GmbH",
  "license": "ISC"
}
`
