### ISSUE TITLE
How to run a script after installation on non-rpm builds

### ISSUE THREAD

**Issue by NathanPB** [electron-userland/electron-builder#4487]
* **Version**: 21.2

* **Target**: NSIS

I found a way to run scripts after installation on rpm builds in  [this page](https://www.electron.build/configuration/linux#linuxtargetspecificoptions-apk-freebsd-pacman-p5p-and-rpm-options), but I couldn't find any equivalent for Windows NSIS, deb or Mac.
Is there any form of doing this?

I want to run a bash/bat script to modify the permissions of an inner directory in the installation and give write permissions to everyone into it.

**Comment by NathanPB** [comment]
Deb solution: #2050 (very confusing documentation, had to scrap old issues to find it out). But still not found any way to do with NSIS and MacOS specific

**Comment by prashantbodh099** [comment]
Hello @NathanPB !

I also have the same requirement i.e., To execute a .bat file just after the installation on the windows system .
Did you find any workaround for the same?

**Comment by tar-unix** [comment]
Why this is mark completed?
What is the way to run script after installation?

**Comment by tar-unix** [comment]
I found it, here is the solution: https://documentation.help/CTRE-NSIS/Section4.7.html#:~:text=Callback%20functions%20will%20be%20called,of%20Sections%20or%20other%20Functions.
