### ISSUE TITLE
Packaging Electron v5+ with sandbox (AppImage) 

### ISSUE THREAD

**Issue by christianbundy** [electron-userland/electron-builder#4495]
* **Version**: 21.2.0

* **Target**: AppImage

See: https://github.com/electron-userland/electron-builder/issues/3872

This issue was closed, but the solution only fixes the problem for `.deb` builds. AppImages are still broken by default, and there's currently no solution (other than asking people to [manually patch their AppImage](https://github.com/ssbc/patchwork/issues/1217#issuecomment-559609983)). Is there any recommended course of action for broken AppImage releases?

Thanks!

**Comment by vladimiry** [comment]
> and there's currently no solution (other than asking people to manually patch their AppImage)

So there is a workaround of developers to apply the patching during the packages preparing stage. Like https://github.com/vladimiry/ElectronMail/blob/fb4fef50423e67fe06562f1f448c0c761c515d2f/scripts/electron-builder/build-appimage.ts (unpacking the AppImage, applying the changes, packing it back).

**Comment by christianbundy** [comment]
cc: @develar

**Comment by L3o-pold** [comment]
Always an issue...

**Comment by ttomaszewski** [comment]
Still an issue...
