### ISSUE TITLE
Customize release name on creation

### ISSUE THREAD

**Issue by limoragni** [electron-userland/electron-builder#450]
When creating a release `electron-builder` is using the tag as a name which is good, `v2.0.1` but I think it would be useful if you could add some more information like `v2.0.1-dev`

In my use case adding a suffix to the tag would be enough. Maybe there are some other use case where is useful to replace everything?

**Comment by rafajaques** [comment]
+1
I would like to set the filename also. My app name has spaces and I don't want the installer to have it.

**Comment by develar** [comment]
@rafajaques This issue about github release name. 

> My app name has spaces and I don't want the installer to have it.

See https://github.com/electron-userland/electron-builder/issues/452#issuecomment-222736865

**Comment by rafajaques** [comment]
I'm sorry! Thanks!
