### ISSUE TITLE
Question: where to store data from NSIS installer?

### ISSUE THREAD

**Issue by aalvarez255** [electron-userland/electron-builder#4500]
Hi,

I added a custom page to the default NSIS installer so I can config an IP address (input field) during my app installation. This IP address is common to all app users and must be stored somewhere to be used later on the electron app.

My question is, where can I save this IP address? My first attempt was to save a .json file in the installation directory (Program Files) but it seems that the installation folder files are deleted during app updates, so I lost my settings file.

Any ideas? Thanks :)

**Comment by kzimny** [comment]
Maybe in `app.getPath('userData')` ? Similar problem as in #4227

**Comment by aalvarez255** [comment]
Any clue on how to find `app.getPath('userData')` path from NSIS? :/

**Comment by serg06** [comment]
> Any clue on how to find `app.getPath('userData')` path from NSIS? :/

For me it corresponds to `$APPDATA\${APP_PACKAGE_NAME}`.

Note: It seems like it might also be `$APPDATA\${APP_FILENAME}` or `$APPDATA\${APP_PRODUCT_FILENAME}` sometimes, I can't tell for sure. Source: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/uninstaller.nsh
