### ISSUE TITLE
Can't override publish config via CLI?

### ISSUE THREAD

**Issue by clearydude** [electron-userland/electron-builder#4503]
* **Version**: 21.2.0

There isn't a ton of documentation on overriding electron-builder config via the CLI tool. I've been trying to set the package name for a bintray publish target with `-c.publish.package=foo2` but from the effective config this unsets all of the other publish config.
Is there a way to just be able to override one part of the publish config without everything being removed? Essentially I need to be able to override the package name or user ONLY via the CLI, leaving the other options in tact.
Thanks!

**Comment by SuperKirik** [comment]
Hello !
Is it an update on it ?

I would like to override `bucket` in 'publish' section of config when building and publishing the staging version of the app.
