### ISSUE TITLE
Error: Redirect was cancelled

### ISSUE THREAD

**Issue by ianjennings** [electron-userland/electron-builder#4505]
electron-builder@21.2.0

electron-updater@4.2.0

target=**mac**

Having problems getting my autoUpdate to work. Note that I'm pointing at a github repository that is different than the one in the .git/config.

```
stdout: 20:53:04.849 › Checking for update
stdout: 20:53:04.986 › Current microphone access status: granted
stdout: 20:53:05.027 › Current camera access status: granted
20:53:05.028 › true true
stdout: 20:53:07.240 › Found version 0.0.10 (url: app-0.0.10-mac.zip, app-0.0.10.dmg)
stdout: update avail, downloading
stdout: 20:53:07.241 › Downloading update from app-0.0.10-mac.zip, app-0.0.10.dmg
stderr: 20:53:07.243 › updaterCacheDirName is not specified in app-update.yml Was app build using at least electron-builder 20.34.0?
stderr: (electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
stdout: 20:53:07.246 › updater cache dir: /Users/xxx/Library/Application Support/Caches/app
stdout: 20:53:07.251 › No cached update info available
stderr: 20:53:07.542 › Error: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
stdout: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

**Comment by ianjennings** [comment]
Tried switching to s3 today and had the same result.

**Comment by ianjennings** [comment]
Was previously electron@7.x.x and fixed by downgrading to electron@6.x.x.

**Comment by szTheory** [comment]
I'm also getting this error with `7.1.1` and Github Releases.

**Comment by marcoancona** [comment]
> Was previously [electron@7.x.x](mailto:electron@7.x.x) and fixed by downgrading to [electron@6.x.x](mailto:electron@6.x.x).

Same here. This issue should not be closed.

**Comment by jkhoel** [comment]
also getting this, electron@7.1.4 and electron-updater@4.2.0 against a GH repo

Getting it on both build version as well as development version using dev-app-update.yml

**Comment by lutzroeder** [comment]
Works in `electron@7.1.2`, fails starting `electron@7.1.3`.

@MarshallOfSound @codebytere @ckerr is there an Electron issue tracking this?

**Comment by sidneys** [comment]
also getting this bug.

**Comment by lyswhut** [comment]
I also getting this error in `7.1.5`.

**Comment by burtonator** [comment]
Is there a fix for this?  I'm dead in the water and can't push releases.  This should not be closed.

**Comment by newCodeRunner** [comment]
Also getting this windows 10, electron 7.1.5

**Comment by agata** [comment]
Also getting this mac OS, electron 7.1.6

**Comment by lgqAozora** [comment]
I also getting this error in electron 7.1.7 , electron-builder 22.1.0, windows 10.

**Comment by patrickeller** [comment]
Also getting this with:
electron@7.1.7
electron-updater@4.2.0
electron-builder@21.2.0

**Comment by lucasboinet** [comment]
Is there any solution ? or we have to downgrade electron version ? or any alternative ?

**Comment by szTheory** [comment]
Looks like a fix might have been merged into master. Seems important enough to warrant a regression test for. Not sure what the process is to get it backported to 7 and released. https://github.com/electron/electron/commit/ed6a3877a438c1109692a387cef97c21cb3cab3c

**Comment by kemuri** [comment]
Having the same issue with
    "electron": "^7.1.4",
    "electron-builder": "^21.2.0",
    "electron-updater": "^4.2.0",
    "update-electron-app": "^1.5.0"

Any solutions beside downgrading 6.x?

**Comment by lutzroeder** [comment]
See electron/electron#21566 for details. The regression was introduced in 7.1.3 so downgrading to 7.1.2 should work.

**Comment by kemuri** [comment]
Thanks, 7.1.2 worked perfectly! :)

**Comment by nornagon** [comment]
Electron v7.1.8 should have the fix to this issue.

**Comment by agata** [comment]
I've checked it on macOS, Windows and Linux. It works fine.

- Electron v7.1.8
- electron-builder v22.2.0
- electron-updator v4.2.0

**Comment by tytech3** [comment]
Still have this issue on Windows 7 -

    "electron": "^7.1.7",
    "electron-builder": "^21.2.0",
    "electron-updater": "^4.2.0",

**Comment by patrickeller** [comment]
> Still have this issue on Windows 7 -
> 
> ```
> "electron": "^7.1.7",
> "electron-builder": "^21.2.0",
> "electron-updater": "^4.2.0",
> ```

Try to update electron to 7.1.8

**Comment by tytech3** [comment]
> > Still have this issue on Windows 7 -
> > ```
> > "electron": "^7.1.7",
> > "electron-builder": "^21.2.0",
> > "electron-updater": "^4.2.0",
> > ```
> 
> Try to update electron to 7.1.8
Updated to 7.1.9,
It's successfully recognizing updates now. So thats good. but now im getting /releases/assets/<numbers> , status 404: not found

**Comment by patrickeller** [comment]
> > > Still have this issue on Windows 7 -
> > > ```
> > > "electron": "^7.1.7",
> > > "electron-builder": "^21.2.0",
> > > "electron-updater": "^4.2.0",
> > > ```
> > 
> > 
> > Try to update electron to 7.1.8
> 
> Updated to 7.1.9,
> It's successfully recognizing updates now. So thats good. but now im getting:
> 
> Error: Cannot download
> 
> "https://api.github.com/repos/tytech3/myrepo/releases/assets/1743203", status 404: not found

Looks like that's not a bug in electron / the updater itself. So try to check your updater configuration. Like the repo name for example

**Comment by tytech3** [comment]
> > > > Still have this issue on Windows 7 -
> > > > ```
> > > > "electron": "^7.1.7",
> > > > "electron-builder": "^21.2.0",
> > > > "electron-updater": "^4.2.0",
> > > > ```
> > > 
> > > 
> > > Try to update electron to 7.1.8
> > 
> > 
> > Updated to 7.1.9,
> > It's successfully recognizing updates now. So thats good. but now im getting:
> > Error: Cannot download
> > "https://api.github.com/repos/tytech3/myrepo/releases/assets/1743203", status 404: not found
> 
> Looks like that's not a bug in electron / the updater itself. So try to check your updater configuration. Like the repo name for example


It's all correct, I copy pasted it from github itself. The weird thing is, if i go into the browser and just type it in manually, that is "api.github.com/repos/tytech3/repoanme/releases/latest" i still get not found. Triple checked spelling and everything.

I have a GH_TOKEN set on my machine environment variables as well. Any ideas on what to try next?

**Comment by patrickeller** [comment]
> 
> It's all correct, I copy pasted it from github itself. The weird thing is, if i go into the browser and just type it in manually, that is "api.github.com/repos/tytech3/repoanme/releases/latest" i still get not found. Triple checked spelling and everything.
> 
> I have a GH_TOKEN set on my machine environment variables as well. Any ideas on what to try next?

It's hard to to find a bug without seeing the code.
I suggest you to open a new thread on stackoverflow with your code

**Comment by didiokener** [comment]
@tytech3 have you tried update electron builder to the latest version?
electron-builder: 22.3.2

**Comment by cyphercodes96** [comment]
Same issue

    "electron": "^7.1.11",
    "electron-builder": "^22.2.0",
    "electron-updater": "^4.2.0",

**Comment by itselviz** [comment]
same issue

"electron": "^7.1.11",
"electron-builder": "^22.2.0",
"electron-updater": "^4.2.0",

**Comment by matextrem** [comment]
Any update? I have the same problem as @tytech3

**Comment by miquelvir** [comment]
Same issue

"electron": "^9.0.5",
"electron-builder": "^22.7.0",
"electron-updater": "^4.3.1"
