### ISSUE TITLE
Hiring a freelance for help

### ISSUE THREAD

**Issue by RafaeldelM** [electron-userland/electron-builder#4507]
Hi!
I'm becoming really frustrated with electron-builder because the autoupdater doesn't work on my computer: "Can not find Squirrel".
I was reading everything, I was trying to change everything, but nothing works.
For that reason, I would like to hire a freelance to help me with that. 
Is there any available?
Thanks,
Rafa

**Comment by develar** [comment]
If you use electron-builder default target for Windows, then NSIS is produced instead of Squirrel.Windows. So, you should not use native electron updater, but `electron-updater` instead. https://www.electron.build/auto-update

**Comment by RafaeldelM** [comment]
Hi,
Yes! That's what I'm using, nsis and autoupdater calling to my backend.

For that reason I don't understand why this error, building in my Mac and in my Win10.

Here my package.json.
https://github.com/electron-userland/electron-builder/issues/4498

Thanks

**Comment by kzimny** [comment]
Did you solved the problem?

**Comment by RafaeldelM** [comment]
Yes! The crash was because my backend was returning a "bad" JSON answer.  Just I switch to DigitalOcean update and everything worked correctly!
Thanks for asking.
