### ISSUE TITLE
After packaging app can't access microphone & camera

### ISSUE THREAD

**Issue by SimanovichSiarhei** [electron-userland/electron-builder#4514]
* **Version**: 21.1.5
Up to 22.2.0 same issue
Latest known working version 20.38.5

* **Target**: MacOS dmg

After packaging application can't access microphone or camera. When downgraded to 20.38.5, OS message to grant access appeared, and mic working fine.

**Comment by pashvin** [comment]
Do you include entitlement file with following two flags? It is new requirement from Apple as part of signing app.

    <key>com.apple.security.device.audio-input</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>

**Comment by SimanovichSiarhei** [comment]
@pashvin, thanks, that is same thing that I have found. Closing this issue.
