### ISSUE TITLE
electron-builder does not respect yarn workspace and pulls in incorrect version into bundled app

### ISSUE THREAD

**Issue by kittaakos** [electron-userland/electron-builder#4516]
* **Version**: 
`21.2.0`

* **Target**: 
macOS, dmg

When I use `yarn` workspaces, the `electron-builder` does not handle the versions correctly and pulls in an incorrect version into the final app's dependencies.

I set up a [repo](https://github.com/kittaakos/test-electron-builder) to reproduce it, and described the oddity [here](https://github.com/kittaakos/test-electron-builder#oddity).

[Steps to reproduce](https://github.com/kittaakos/test-electron-builder#steps-to-reproduce):
 - `yarn`
 - start the electron app: `yarn --cwd ./examples/app start` and check the version,
 - package the electron app: `yarn --cwd ./examples/app package` and check the version.

Can someone please verify whether it is a bug or a missing feature? Or is my expectation about the versions correct at all?

Thank you!

**Comment by kittaakos** [comment]
> Is this still relevant?

Sure.

> If so, what is blocking it?

Some feedback from the maintainers; whether it is a bug or not, seems to be a defect though.

> Is there anything you can do to help move it forward?

I even set up a repository with the steps to reproduce, what else should I do, dear stale bot?

**Comment by mifi** [comment]
Did you manage to solve this? I've got the same issue https://github.com/electron-userland/electron-builder/issues/8519#issuecomment-2440193102

**Comment by beyondkmp** [comment]
@mifi I have tested electron-builder v25.1.8 and it has resolved the issue in #4516 (electron v21). Could you please test if v25.1.8 has resolved your issue as well?
<img width="836" alt="image" src="https://github.com/user-attachments/assets/e5b6cce4-b0a1-4c29-8866-c700c53415ec">
