### ISSUE TITLE
Adding deb format to latest-linux.yml file

### ISSUE THREAD

**Issue by trae-op** [electron-userland/electron-builder#4519]
**electron-builder**: v22.2.0
**electron-updater**: ^4.2.0
**electron**: v7.1.3
I need to add build **.deb** for **latest-linux.yml** to **files** property
![image](https://user-images.githubusercontent.com/12648541/70436419-e901a280-1a91-11ea-9207-b0a5d61a258e.png)

**My builder config**:
"build": {
    "appId": "myApp",
    "extraResources": "build/**/*",
    "generateUpdatesFilesForAllChannels": false,
    "files": [
      "!dist/*"
    ],
    "directories": {
      "output": "dist/${os}/"
    },
    "publish": [
      {
        "provider": "generic",
        "url": "https://myApp.com/downloads/${os}/"
      }
    ],
    "mac": {
      "category": "public.app-category.productivity",
      "artifactName": "${productName}-${version}-${arch}.${ext}",
      "target": [
        "dmg",
        "zip"
      ]
    },
    "linux": {
      "category": "Chat;GNOME;GTK;Network;InstantMessaging",
      "packageCategory": "GNOME;GTK;Network;InstantMessaging",
      "description": "RMClient Desktop for Linux",
      "target": [
        "deb",
        "zip",
        "AppImage"
      ],
      "artifactName": "${productName}-${version}-${arch}.${ext}"
    },
    "snap": {
      "synopsis": "RMClient Desktop App"
    },
    "dmg": {
      "icon": "build/icon.icns",
      "iconSize": 100,
      "contents": [
        {
          "x": 380,
          "y": 200,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 110,
          "y": 200,
          "type": "file"
        }
      ]
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "icon": "build/icon.ico"
    },
    "nsis": {
      "perMachine": true,
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    }
  }

**Comment by danieltigse** [comment]
Hey did you solve it @trae-op ?

**Comment by EdvinM** [comment]
I would like to know if this is possible or a workaround have been found as well.

**Comment by mmaietta** [comment]
Hi all! Happy to accept a PR on this. IIRC, deb isn't supported for auto-updating, so I'm guessing that's why it isn't included in the latest-linux.yml

Easy way to set up a dev env:  https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
