### ISSUE TITLE
Publishing artifacts with different names

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#452]
Whenever I generate windows installers (haven't tried on other OS's) I get a ```.exe``` file in the form ```AppName Setup x.x.x.exe```. I don't want to have spaces in the filename - is there a way to configure the builder to do this? Or say I just want to have ```Setup.exe```. Just not the default.

**Comment by develar** [comment]
> . I don't want to have spaces in the filename - is there a way to configure the builder to do this?

Not yet. Why don't you like spaces? Please note — on publish to gihub `-` will be used instead of space.

**Comment by mzmousa** [comment]
I don't like spaces (at the moment) because right now I'm using https://github.com/aktau/github-release to do my releasing to Github, and spaces in the name are causing some trouble. I'm not running AppVeyor or Travis CI, I'm running Hudson - so I wasn't sure if electron-builder supported that.

**Comment by develar** [comment]
> I'm running Hudson - so I wasn't sure if electron-builder supported that.

Nothing magic here. Just define `GH_TOKEN` env. Please see https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

Feel free to file issues if github publisher doesn't suit you.

Closed as Won't Fix since we already don't use spaces for published artifacts,

**Comment by develar** [comment]
But! Maybe we should detect that it is a CI server and produce `-`... Hmm... Could you please post here `console.log(process.env)` on your Hudson server?
