### ISSUE TITLE
mac targets [pkg] not being signed when [mas] is also being signed. (22.1.0+)

### ISSUE THREAD

**Issue by patrickmichalina** [electron-userland/electron-builder#4520]
* **Version**: 22.1.0+
* **Target**: Mac

When packaging targets `["dmg", "pkg", "mas"]`, only MAS is signed correctly.

https://github.com/electron-userland/electron-builder/pull/4321/commits/68aed335c84ff84d612d002185807d857363a175 introduced this issue.

**Comment by patrickmichalina** [comment]
This code fixes the issue but feels a bit hacky using `mas` as the lookup string.

```js
const appFileName = `${this.appInfo.productFilename}.app`;

await _bluebirdLst().default.map((0, _fsExtra().readdir)(packContext.appOutDir), file => {
    const inputPath = path.join(packContext.appOutDir, file)
      
    if (file === appFileName && !inputPath.indexOf('/mas/')) {
      return this.sign(inputPath, null, null);
    }

    return null;
});
```

**Comment by pashvin** [comment]
I think when new notarization process introduced, then setting dmg flag sign flag = true was causing some issues. I may be wrong but as far as I know if application is notarized and if DMG is not signed , then gatekeeper does not complain but when I tried the same (PKG is not signed but app is signed), then it did not work. DMG has signed flag that you need to turn it on. I don't see any flag for PKG. It will be nice to get the same flag for PKG too.

**Comment by pashvin** [comment]
By the way I am not using mac artifact and for me pkg is also not signed. For you if you do not generate mas , then does pkg comes signed? if yes, then can you tell me what are the flag you set in package.json for PKG?

**Comment by patrickmichalina** [comment]
@pashvin you are right, there is also an issue with PKG not being signed. I haven't tried all the different permutation for this process but looks like this section of code needs some work and unit tests to prevent regressions.

**Comment by juancarlosfarah** [comment]
When building with v22.3.2, if I include `mas` and `dmg`, the `dmg` does not get signed either, although the `mas` gets signed without a problem. Removing `mas` allows the `dmg` to get signed.
