### ISSUE TITLE
Cannot rename file using configuration build.files

### ISSUE THREAD

**Issue by KoltesDigital** [electron-userland/electron-builder#4522]
* **Version**: 21.2.0

* **Target**: NA

[The doc states that app contents can be renamed using `from` and `to`](https://www.electron.build/configuration/contents#files) (#1119). However it doesn't work:

1. Setting `from` to an existing file path, and `to` to the expected file path, the expected file does not exist in the asar. It seems `from` is still considered as a directory path, since the FileMatcher contains `**/*` in `patterns`. Maybe `glob` doesn't return anything now, while when you implemented this feature it returned the original path?
2. Not setting `from`, but instead setting `filter` to `["<file path>"]`, actually creates a directory at the expected file path, containing a hierarchy of dirs and finally a unique file, with the original name.
3. Setting `from` to the file's directory, and setting the filename in `filter`, does the same as point 2 expect the file is directly in the directory.

There's no explanations in the doc, so I have no other ideas. Can you please check the feature is working as intended, and if so, give some more details?

**Comment by KoltesDigital** [comment]
Of course it is still relevant, you haven't even replied.

**Comment by KoltesDigital** [comment]
Yes it is.

**Comment by KoltesDigital** [comment]
...

**Comment by KoltesDigital** [comment]
...

**Comment by conrallendale** [comment]
`from` is really treated like a dir. `walk` in `fs` perform a readdir in it, returning no results. Then, in `platformPackager.js` method `copyAppFiles`,  `files` is filtred for empty: `return result.filter(it => it.files.length > 0);`

**Comment by conrallendale** [comment]
Workaround is to disable asar (`asar: false`), then use extraResources to copy files to app folder, like:
```
extraResources:
  - from: .env.client.production
    to: app/.env.client
```

**Comment by KoltesDigital** [comment]
stalebot: ...

@conrallendale thanks for digging and for the workaround. Mine is to simply copy files before running `electron build`.
