### ISSUE TITLE
electron-builder downloads win32 ia32 on Win10 ARM64

### ISSUE THREAD

**Issue by soapdog** [electron-userland/electron-builder#4532]
* **Version**: 21.2.0

* **Target**: windows (portable and dir)

I have been using NodeJS compiled for Windows 10 under ARM64 with Electron 7.1.3 for Windows 10 ARM64, all native on a Surface Pro X but when I try to use _electron-builder_ with it it tries downloading the Electron version for 32bits x86 Windows 10 which is not the correct version for the platform. I'm not running under emulation, the nodejs engine that is running is built for ARM.

**Comment by richard-townsend-arm** [comment]
Hi (stumbled across this issue whilst looking for another one). Are you setting `npm_config_arch=arm64` and `npm_config_target_arch=arm64` in your terminal, and passing the `--arm64` flag to electron-builder?

**Comment by soapdog** [comment]
@richard-townsend-arm I'll try with all of these when I get home. I tried so many different combinations that I am not sure I used all those together. I believe that the `--arm64` was not passed as a command line param but a config in `package.json`.
