### ISSUE TITLE
MacOS: Electron app quit unexpectedly

### ISSUE THREAD

**Issue by manngo** [electron-userland/electron-builder#4533]
**electron-builder version:** 21.2.0 I think. To be sure, I did the following:

	npm uninstall -g electron-builder
	npm install -g electron-builder@21.2.0

**electron version:** 6.1.5

I uninstalled the newer version and installed 6.1.5, and set it in my `package.json` file. This was because of suggestions in similar issues.

**Target:** MacOS (Catalina)

When I run the application with

	npm start

the application works.

The built application will not run. I use the following command:

	electron-packager . --overwrite --platform=darwin --arch=x64 --prune=true --extend-info "info.plist" --out="../release-builds/"

The application quits with the message:

>[app]  quit unexpectedly

which is true but unhelpful.

There are similar issues but they appear to be resolved by using electron-builder 21.2.0. This doesn’t appear to work for me.

Appreciate any help possible, such as how to go about debugging.

**Comment by sidneys** [comment]
@manngo

Does this error occur when you build the app directly (.app), or only when you build a zip?
This might be related to https://github.com/electron-userland/electron-builder/issues/4299.

Kind regards

**Comment by manngo** [comment]
> @manngo
> 
> Does this error occur when you build the app directly (.app), or only when you build a zip?
> This might be related to #4299.
> 
> Kind regards

This happens without zipping it at all.

**Comment by manngo** [comment]
This is not an electron-builder issue. I switched to electron-packager, so this is my mistake. It’s actually an issue with the electron version.
