### ISSUE TITLE
child_process execFile on Mac OS does not work

### ISSUE THREAD

**Issue by andyjslee** [electron-userland/electron-builder#4534]
I am trying to execute a python binary file (created via pyinstaller) through my Electron application on Mac OS. Invoking the child_process execFile function on the binary file works fine until I package my Electron application using electron-builder. For your reference, this occurs in both Electron v7.1.2 and v7.1.4 (latest version at the time of this post). This problem doesn't occur on my Windows machine with the same underlying source code. It only happens on Mac OS regardless of whether I package the Electron app with or without asar. Interestingly, the problem goes away when I run the Electron application using the unix executable in App/Contents/MacOS/App. What is the official workaround/fix for this?

**Comment by a1992012015** [comment]
解决了吗？

**Comment by megasanjay** [comment]
Facing the same issue. Did you figure it out?
