### ISSUE TITLE
Icon Blank in Start Menu

### ISSUE THREAD

**Issue by electronart** [electron-userland/electron-builder#4538]
21.2.0

N/A

* **Target**: 
		"win": {
			"icon": "Icon.ico",
			"target": "msi",
		}

Hello, when building MSI for windows, start menu displays blank icon

![image](https://user-images.githubusercontent.com/21058800/70921770-dbfa2b80-201c-11ea-88eb-43c7f0a07638.png)

However, if I `right click -> more -> Open file location` correct icon is displayed.

Ideas?

**Comment by kzimny** [comment]
It seems that your Icon.ico is saved in root directory of your project. According to the [documentation ](https://www.electron.build/icons.html#windows-nsis) the icon needs to be placed in the buildResources directory. Build resources is not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly:

```
    "build": {
        "files": [
            "Icon.ico"
        ],
    },
```

Hope this help.
