### ISSUE TITLE
Version of node in Docker image electron-builder:wine not updated

### ISSUE THREAD

**Issue by nicolas-van** [electron-userland/electron-builder#4539]
As far as I can understand the version of node.js has been updated in the base Dockerfile of `electronuserland/builder` to version `12.13.1` since quite a long time. I assume the concerned Dockerfile [is this one](https://github.com/develar/electron-builder/blob/master/docker/node/Dockerfile).

Yet when I check the version of node with this command (as of 17 December 2019, without any cache):

```
docker run -ti electronuserland/builder:wine sh -c "node -v"
```

I get this output:

```
v11.10.0
```

According to Docker Hub this tag was published only a few days ago. I assume it is kind of a problem somewhere in the list or Dockerfiles inheriting from each other. Notably the [Dockerfile for wine](https://github.com/develar/electron-builder/blob/master/docker/wine/Dockerfile) inherits from the `electronuserland/builder:latest` image that was not updated since 10 months.

**Comment by lorenzorivosecchi** [comment]
Hi @nicolas-van, have you found any workaround ?
I need at least v11.10.1 for a project

**Comment by nicolas-van** [comment]
@lorenzorivosecchi : Nope, didn't searched. I just use the provided version for now.

**Comment by lorenzorivosecchi** [comment]
I tried to re build the image myself running `docker build .` on the wine directory, but once inside the container `node --version` still returns v10.11.0

Am I missing something ?

**Comment by gabrielfnogueira** [comment]
I ran into this issue today. What solved for me was to download this repo, run `./docker/build.sh` and then inside the container `node --version` returned `v12.14.1` as it should.

**Comment by sapkra** [comment]
Duplicate https://github.com/electron-userland/electron-builder/issues/4298
