### ISSUE TITLE
Improve publish parameterization for CI/CD

### ISSUE THREAD

**Issue by kputh** [electron-userland/electron-builder#4542]
* **Version**: 22.2.0

* **Targets**: all

When you do continuous integration, you usually store sensitive configuration like passwords and api keys (_secrets_) outside of your version control system, and inject these at build time using environment variables. electron-builder has lots of configuration containing secrets that currently cannot be injected from the command line – at least not according to the documentation. The same is true for configuration like artifact storage addresses and channel/bucket names.

I propose that the electron-builder cli should have a single mechanism for overwriting any publish configuration, and that the documentation should point this out. Example configuration options are:

- every configuration named `token`
- every publish configuration named `channel`
- `buildVersion`
- `artifactName`
- `releaseInfo`

**Comment by kputh** [comment]
I now realize that electron-builder already supports what I proposed. However, it is absent from the beginning of _Common Configuration_, which explains how to configure electron-builder.

**Comment by shaharmor** [comment]
@kputh can you share how you did it?

**Comment by kputh** [comment]
Sure. electron-builder allows you to do this: `electron-builder build -c.publish.endpoint='http://example.org' -c.publish.bucket='bucket-name'` It doesn't work for all configuration, but - according to documentation - for all the publish configuration.
