### ISSUE TITLE
Electrton builder must NOT try to publish to github by default

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [electron-userland/electron-builder#4546]
* **Version**: 21.2.0

* **Targets**: a lot (Windows, Linux, mac: AppImage, portable and NSIS for Windows; zip).

So, the scenario that happened:

* I transitioned from nw.js to electron;
* I already had a build pipeline in Travis: linters, builders, packers;
  * Travis had also a specific "publish" step, with restrictions that make it perform on tags and `master` only. It had logic for GitHub releases and itch.io.
  * due to this, I already had env variables set for GitHub as well.
* So I push changes first to a specific branch, then merge it to `develop`.
* Builds fail, because of `electron-builder` trying to publish packages to Github. :woman_facepalming: (`artifacts will be published if draft release exists  reason=CI detected`)
  * and thank gods my token to GitHub was not called `GH_TOKEN`.

This is unacceptable. `electron-builder` is "A complete solution to package and build a ready for distribution Electron app [...]", not to _deliver_ packages. It is never expected to upload something on its own. It is not a CI/CD pipeline — and we already have our own, for what is worth.

But this is hilarious in *any* scenario because any project will have a CI and may have tokens for GitHub to get/post info not required for packages. It also makes a default config 100% fail if it is run inside Travis or such.
All in all, as authors of apps, we better know *where* and *when* to publish them. We have automation bound to releases, even for draft ones (notifications about releases ready for further advancement to production state, and with links for testing packages).

**Comment by kzimny** [comment]
Did you try to use the ```--publish newer``` option? I agree with you in many arguments, but as you probably know there are not many better solutions to package and build a ready for distribution Electron app. There are some bugs that are not fixed and the main and co-authors of the packages are obviously overwhelmed.

**Comment by CosmoMyzrailGorynych** [comment]
> Did you try to use the --publish newer option?

I use `electron-builder` as a node module in `gulp`, and I don't need `electron-builder` to publish the app. Rn, I just skip the packaging in Travis. It should also be fixable by `"build": { "publish": []}`

> but as you probably know there are not many better solutions to package and build a ready for distribution Electron app

This is a poor argument, really.

Bugs are bugs; ill-chosen decisions in an app's functionality are a different matter.

**Comment by kzimny** [comment]
Yes, there are also a few other bugs. But nobody cares.

**Comment by CosmoMyzrailGorynych** [comment]
inactive issues are still issues

**Comment by budait** [comment]
This issue is still present.
It is especially annoying when builder is used programmaticaly from nodejs in a CI environment.
The current workaround is to specify `publish: null` in config. IHMO this should be the default.
