### ISSUE TITLE
[Feature Request] Ability to set author/CompanyName programmatically

### ISSUE THREAD

**Issue by dknutsen** [electron-userland/electron-builder#455]
So I'm using electron-builder programmatically in a script because we build the same app with multiple whitelabeled builds, each with unique branding (icons, app name, etc). This allows me to simply run the script with the name of the app that I want to build and electron-builder builds it the requested way. 

This all works great with the exception of author/CompanyName, causing my Windows apps to install under "Undefined" company (because in package.json my author is simply ""). As far as I can tell the only way to set that is to set it in the package.json, which of course would make the company name/author the same for all of our whitelabeled apps, and there isn't really a good author name that will work for everyone. 

Would that be something that could be added to be specified in the programmatic API? 
Alternatively not installing the app under an author subdirectory at all would be acceptable (basically being able to leave author/CompanyName out completely).

**Comment by develar** [comment]
```
builder.build({
  targets: Platform.OSX.createTarget(),
  devMetadata: {
    "//": "build and other properties, see https://goo.gl/5jVxoO"
  }
})
```

Just set `author` in the `devMetadata` – `devMetadata` allows you to override any field in the `package.json`.

**Comment by dknutsen** [comment]
So I tried adding the "author" field to devMetadata as suggested but no luck. I managed to get it to work though after looking through the electron-builder code a little bit and experimenting. 

In case anyone else runs across this, here's what I did:
First I put the following in my script for the builder config (note that it must go in `devMetadata.build`):

    builder.build({
      ...
      devMetadata: {
        build: {
          ...
          'version-string': {
            "CompanyName":  `${companyName}`,
            "FileDescription":  `${appDescription}`,
            "ProductName":  `${appName}`,
            "InternalName":  `${appName}`,
          },
          ...
        }
    })
  
That worked right for the description however I was getting an error on the CompanyName value. In my `package.json` i had the "author" field set to just "" which mean that when it was looking at `metadata.author.name` it was trying to get the name key from an undefined object. So what I had to do to fix this was this in my package.json:

    {
      "author": ""
    }

with this:

    {
      ...
      "author": {
        "name": "DefaultName"
      },
      ...
    }

Now setting the company name and description works perfectly. Thanks @develar for the assistance and all the work on a great tool!

**Comment by develar** [comment]
Reopened — wtf it doesn't work.

**Comment by develar** [comment]
`appMetadata` was added.

**Comment by ChengLin-Zhou** [comment]
appMetadata has no company property
