### ISSUE TITLE
TypeError: Cannot read property 'Provider' of undefined，谁能帮我？

### ISSUE THREAD

**Issue by w602542704** [electron-userland/electron-builder#4554]
![image](https://user-images.githubusercontent.com/24689873/71404351-476f7900-266d-11ea-9a99-367abfa5c51a.png)
![image](https://user-images.githubusercontent.com/24689873/71404376-55bd9500-266d-11ea-92a8-c51870d120fd.png)
在做应用更新功能时报错，不知道什么原因，谁能帮助我

**Comment by w602542704** [comment]
原来是我传入下载的地址是undefined😂

**Comment by popod** [comment]
@w602542704 as you find a solution to this issue, could you please close it ? Thank you :)
