### ISSUE TITLE
How to build app for macOS on Linux

### ISSUE THREAD

**Issue by puqing-h** [electron-userland/electron-builder#4555]
I used image for electronuserland/builder:wine and electronuserland/builder are the same error
![image](https://user-images.githubusercontent.com/34705240/71408772-4c86f500-267a-11ea-9710-133b84e21192.png)
So what can i do ?

**Comment by root-expert** [comment]
You can't do that. You can only build MacOS on Mac.

**Comment by b-zurg** [comment]
As mentioned above you can only really build for mac if you're running the build on a mac.   There are CI servers (I think AppVeyor or Travis CI) that can do this for you if you don't have a machine but they will cost some money.
