### ISSUE TITLE
[typescript] `fs-extra` an `yargs` missing types error

### ISSUE THREAD

**Issue by IlCallo** [electron-userland/electron-builder#4556]
* **Version**:  22.2

* **Target**: 

Hey there, you use `fs-extra` and `yargs` to provide typings, but those dependencies aren't provided with the production build (aka they are listed under `devDependencies` instead of `dependencies`).

This causes a `Could not find a declaration file for module 'fs-extra'|'yargs'` error when compiling with TS and your types are referenced in some ways.

See [this issue](https://github.com/microsoft/types-publisher/issues/81) for the reasons behind putting `@types/*` dependencies into `dependencies`.

Sometimes this could cause errors in production builds and is not feasible, but in your case it seems to be harmless to add the two missing dependencies

**Comment by kzimny** [comment]
There is no error on missing `fs-extra` and `yargs` types in my project compiled with TS, even in production build. I don't need to import `fs-extra` and `yargs` dependencies. I want to understand what cause the problem on your side.

**Comment by IlCallo** [comment]
In my case, error is generated by these 3 code pieces

https://github.com/electron-userland/electron-builder/blob/a215a83e7bce553760cb8033f44dcdc31e1b3316/packages/electron-publish/src/publisher.ts#L5

https://github.com/electron-userland/electron-builder/blob/a215a83e7bce553760cb8033f44dcdc31e1b3316/packages/builder-util/src/fs.ts#L2

https://github.com/electron-userland/electron-builder/blob/a215a83e7bce553760cb8033f44dcdc31e1b3316/packages/electron-builder/src/builder.ts#L5


There are the errors.
```
ERROR in /.../node_modules/electron-builder/node_modules/builder-util/out/fs.d.ts(2,23):
TS7016: Could not find a declaration file for module 'fs-extra'. '/.../node_modules/fs-extra/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/fs-extra` if it exists or add a new declaration (.d.ts) file containing `declare module 'fs-extra';`

ERROR in /.../node_modules/electron-builder/out/builder.d.ts(4,19):
TS7016: Could not find a declaration file for module 'yargs'. '/.../node_modules/yargs/index.js' implicitly has an 'any' type.
  Try `npm install @types/yargs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yargs';`

ERROR in /.../node_modules/electron-publish/out/publisher.d.ts(4,23):
TS7016: Could not find a declaration file for module 'fs-extra'. '/home/p-caleffi/Documenti/source/quasar-typescript-starter/node_modules/fs-extra/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/fs-extra` if it exists or add a new declaration (.d.ts) file containing `declare module 'fs-extra';`

Version: typescript 3.7.3, eslint 6.8.0
```

If you set `skipLibCheck`  in `tsconfig.json` you won't get any error.
I dunno why you don't get them.
I tryed both v21.2.0 and v22.2.0, same result.

My usage of electron-builder is here;

https://github.com/IlCallo/quasar/blob/40199d2732d99195f30115b77c88e2cda4a7f33a/ui/types/configuration/electron-conf.d.ts#L1

The problem is not present into the quasar monorepo because it isn't a TS codebase, it's just a JS codebase exporting TS typings, but as soon as I try it on a TS project the problems arise

**Comment by kzimny** [comment]
Installed config-integrated branch successfully:
![image](https://user-images.githubusercontent.com/12007674/71622707-1268a680-2bd8-11ea-9913-dfd695a9df07.png)
What is the next step? How do you compile and build your app? There are no actions defined in scripts part of package.json. I'm not using `skipLibCheck` in my project.

**Comment by IlCallo** [comment]
You should install quasar cli globally and run `quasar dev` or `quasar build` inside the project folder. Or install it locally and access it via node_modules path

**Comment by kzimny** [comment]
Got it work. Yes, you are right. Installing @types/* in dependencies is always the better choice for such a huge libraries as electron-builder. Make a PR, the chance to accept it is not bad. As a workaround you can install the types in your local project:
`` 
yarn add @types/fs-extra
yarn add @types/yargs
``
Good luck!

**Comment by IlCallo** [comment]
Yeah, I already know the workarounds :)
I'll make a PR as soon as I return from vacation :+1: 

Thank you for taking the time to reproduce and confirm the error
