### ISSUE TITLE
app version is not a valid semver version "0.0.2-beta"

### ISSUE THREAD

**Issue by chenyuhu** [electron-userland/electron-builder#4557]
node 10.16
electron 5.0.2
electron-builder ^20.41.0
electron-updater ^4.0.6
"version": "0.0.1-alpha",

yarn dev  error 
app version is not a valid semver version "0.0.2-beta"
@zeke @jlongster @malept

**Comment by malept** [comment]
@chenyuhu Please do not tag random people into issues you file, it's very impolite.

**Comment by chenyuhu** [comment]
> @chenyuhu请不要在您提出的问题中标记随意的人，这是非常不礼貌的。

sorry, But I'm really urgent @malept
