### ISSUE TITLE
Linux build target not working

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#456]
I'm trying to generate ```rpm```, ```tar.gz```, and ```deb``` files for my app, but whenever I set the target, it only produces a ```deb``` file and a folder with the unpacked linux files in it. It doesn't produce any other files. It doesn't even throw any errors. I have the following entry in my ```package.json```:
```
"build": {
    "linux": {
      "target": ["deb","rpm","tar.gz"]
    }
  }
```

**Comment by mzmousa** [comment]
Perfect. Thank you. 
I know you're quite a busy dev so I appreciate how responsive you are!!

**Comment by develar** [comment]
Please be aware of #460 (not confirmed yet, tests passed).
