### ISSUE TITLE
Package "electron-builder" is only allowed in "devDependencies".

### ISSUE THREAD

**Issue by cyrilfr** [electron-userland/electron-builder#4563]
Hi, I want to build an electron app for ARMv7 in production. The command:

    npm --arch=arm --target_arch=arm --production --no-registry install

gives me this error:

> Package "electron-builder" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.

How to build the app with electron-builder in prod?

**Comment by sapkra** [comment]
I think this should be possible:

```console
ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY=true npm --arch=arm --target_arch=arm --production --no-registry install
```

But I think I will make a PR to remove this crazy rule because this is against the official documentation of npm for `devDependencies`.
