### ISSUE TITLE
Performance issues on Windows executable startup

### ISSUE THREAD

**Issue by Edward-Lombe** [electron-userland/electron-builder#457]
Is there any reason why the generated executable would be taking minutes to initialise, currently seeing a large delay in the clicking of the app and then eventual start. The final size of the .exe file is ~57mb.

What is the best way to start debugging performance issues like this. I do not have these issues when building for OSX, if that helps.

**Comment by develar** [comment]
Please try 4.2.0 version.

**Comment by develar** [comment]
Feel free to reopen if 4.2 has the same issue.
