### ISSUE TITLE
"Cannot find certificate" on Windows

### ISSUE THREAD

**Issue by oscarjiv91** [electron-userland/electron-builder#4575]
* **Version**: 21.2.0
* **Target**: Windows

Hi, I've been trying to use an EV certificate for Windows app. I bought the certificate from ssls.com, and got 2 files: **.crt** and **.p7b**

I installed the .crt and added the **certificateSubjectName** in my package.json. But I alqays get this error 
<img width="561" alt="Captura de Pantalla 2020-01-03 a la(s) 18 41 49" src="https://user-images.githubusercontent.com/4256218/71751288-d6dd0f00-2e59-11ea-9ca1-6c3ad7b16cd4.png">

What are the correct steps do this? I have been researching for hours but it's still not very clear. Please help!

**Comment by oscarjiv91** [comment]
Used powershell and `Get-ChildItem -Recurse Cert: -CodeSigningCert | Select-Object -Property Subject,PSParentPath,Thumbprint | ConvertTo-Json -Compress`. No results :(

**Comment by kzimny** [comment]
Which certificate did you exactly bought? You need an EV Codesign certificate, not EV SSL Certificate.

**Comment by oscarjiv91** [comment]
Yes, I believe we have the EV SSL. I was thinking they were different but didn't find any accurate information. I thought they were the same. Will close this issue. Thanks @kzimny.

**Comment by TimePerformance** [comment]
Hello, 
I had the same problem with a EV code signing certificate from ssl.com.
The certificateSubjectName was right but I still got "cannot find certificate".
The issue was solved when I provided the **certificateSha1** with the **Thumbprint** .
