### ISSUE TITLE
self-signed codesigning certificate? (mac)

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#458]
I created a certificate via keychain access > certificate assistant > create a certificate.  (in the login keychain)

```
name: My Test Certificate
identity type: self signed root
certificate type: code signing

```

Then I type the following in the terminal before building; 

`export CSC_NAME="My Test Certificate"
`
But output is: 

`Identity name "My Test Certificate" is specified, but no valid identity with this name in the keychain
`

What is the problem? Is it not possible to use a self-signed certificate?

**Comment by develar** [comment]
> What is the problem? Is it not possible to use a self-signed certificate?

In our tests we use self-signed cert too. But it is supported only if you specify `CSC_LINK` and `CSC_PASSWORD`.

`CSC_NAME` doesn't support self-signed or non-Apple certs. Should be fixed.

**Comment by develar** [comment]
Please try to make your self-signed cert as trusted using keychain (it must be green). Otherwise it is not valid and, so, not returned.

**Comment by Vj3k0** [comment]
Hey Vladimir, doesn't work for me either. Same problem. I've created code signing certificate from Keychain Access. In release notes, I've seen:

> CSC_NAME env or build.osx.identity is still not removed because it is required if you have several identities. But now instead of Developer ID Installer: Your Name (XXXXXXXXXX), you should specify only Your Name — appropriate certificate will be chosen automatically.

Can this be an issue?

**Comment by develar** [comment]
@Vj3k0 Yes, should be fixed.

**Comment by develar** [comment]
```
develar-home-imac:onshape-desktop-shell develar$ security find-identity -v -p codesigning
  1) 5160729A078E4EF0401986C2328E4D3BD55FFE0E "Test Test"
  2) 32F67D8F957E740C692ADD8CD5A5E463992193DD "Vladimir Krivosheev"
     2 valid identities found
```
<img width="701" alt="screen shot 2016-06-06 at 20 25 56" src="https://cloud.githubusercontent.com/assets/350686/15832978/e88d362a-2c24-11e6-98ee-b70e86ab36a7.png">

**Comment by antoniobrandao** [comment]
@develar that solved it, thanks ! ❤️

**Comment by gmcdev** [comment]
@develar - THANK YOU!

**Comment by LckySndays** [comment]
Anyone know how to use Mac Developer: XXX (YYYY) to sign?
Always got "is specified, but no valid identity with this name in the keychain" error
The certificate is exist in the keychain (security find-identity -v -p codesigning)

If I create my own certificate and make it trusted so it appear on (security find-identity -v -p codesigning), I can sign my Apps without any problem.

The problem only exist when using Mac Developer: XXX (YYYY) to sign the app
I have tried to just specify XXX or Mac Developer: XXX in CSC_NAME but still no luck.

**Comment by develar** [comment]
@LckySndays It is forbidden currently, please vote for #812
