### ISSUE TITLE
Example folder is stripped from app.asar

### ISSUE THREAD

**Issue by luukhoeben** [electron-userland/electron-builder#4580]
Which version of electron-builder are you using?

* **Version**: ^21.2.0

Which version of electron-updater are you using (if applicable)?
^4.0.6 is installed but we don't use it yet.

What target are you building for?
* **Target**: Windows

Enter your issue details below this comment:
We have a file we need to include in the app.asar node_modules, which is in a folder called example.

Now we have tried alot but we found that builder always strips out any example, even when we try to overwrite the files array in the build in the package.json.

Is there any way we can include this folder (with a config.json in it) in the app.asar?

**Comment by kzimny** [comment]
Try with extraFiles configuration https://www.electron.build/configuration/contents.html#extrafiles
```
        "win": {
            "extraFiles": [
                {
                    "from": "root/assets/data",
                    "to": "your/destination",
                    "filter": "test*"
                }
            ],
        },
```

**Comment by luukhoeben** [comment]
@kzimny 

Hey we tried your solution but doing that, it isn't going to be in the asar file. Instead it will be in a seperate folder.

We need it to be in the asar because it is a package inside the node_modules we use that has an example/config.js in the source and it always requires the file, so without it the application won't work (it is  the AdonisJS shield package) and because the builder strips out anything with the name 'example', it strips out this folder.

Do you know how we can fix it?
