### ISSUE TITLE
Parallels not detected while building for win target on macOS Catalina

### ISSUE THREAD

**Issue by amargautam** [electron-userland/electron-builder#4581]
* **Version**: 21.2.0

* **Target**: Windows

I am on macOS Cataline v10.15.2. I have parallels installed v15.1.2 with Windows 10 professional. When I try to build for Electron v7.1.7 for windows, I get the following error message. It used to work fine on older macOS.

```
• packaging       platform=win32 arch=x64 electron=7.1.7 appOutDir=dist/win-unpacked
⨯ Cannot find suitable Parallels Desktop virtual machine (Windows 10 is required)
```

**Comment by amargautam** [comment]
Anyone else got this issue? I have been trying to resolve this for a while now. Please help.

**Comment by amargautam** [comment]
@develar Can you kindly look into this please?

**Comment by amargautam** [comment]
Does anyone have this issue?

**Comment by Athrun-ilan** [comment]
Does anyone have this issue ?

**Comment by amargautam** [comment]
I still have this issue. I have been trying to figure this out for a long time. No idea why it won't work.

**Comment by amargautam** [comment]
I got this issue resolved. Here is what really happened but I don't know why.

On my macOS I had Bootcamp partition with Parallels. Before Catalina, I had Parallels detect and run my Bootcamp Windows 10 without rebooting my computer. When I would build, Parallels would take my Bootcamp Windows 10 and make the windows build possible on macOS.

After I upgraded to Catalina, for not sure what reason, I started getting the error - `Parallels not detected while building for win target`

Just today, I removed my bootcamp and installed windows on Parallels VM directly. Then I made a build and it all worked fine.

**Comment by Athrun-ilan** [comment]
I got this issue resolved too:
update  electron-builder@22.4.0  
update electron@8.1.0 
no need to open  Parallels Desktop

**Comment by pliablepixels** [comment]
Do we now need parallels with windows installed on a mac if we are building windows binaries on a mac machine? I am still on Mojave, and using electron builder 22.4.0 to create windows exe installers using the following in package.json. I am just about considering migrating to Catalina and wanted to see if the wine issue was resolved.
```
 "win": {
      "icon": "icon.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
```

**Comment by amargautam** [comment]
@pliablepixels I am not sure if you need the Windows virtual machine on Catalina if you do not use EV certificate. We use EV code signing so it is mandatory to have parallels with Windows 10. Makes sense?

**Comment by pliablepixels** [comment]
@amargautam thanks. Yes, makes sense for your signing requirement.
