### ISSUE TITLE
Missing sqlite3 binding modules for windows when compiled from mac

### ISSUE THREAD

**Issue by techuila** [electron-userland/electron-builder#4584]
Could not find module electron-v5.0-win32-x64\node_sqlite3.node 
[Issue](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/565)

**Comment by kzimny** [comment]
Sqlite3 is platform dependent. The package should be compiled on a target os.

**Comment by techuila** [comment]
So the only way to make it crossplatform is compile it also on a target os?

**Comment by kzimny** [comment]
I'm working with Sqlite3 and electron. The only way I know is to build your solution with Sqlite3 package on the target os and after that compile for distribution with electron-builder.

**Comment by techuila** [comment]
So the best way is to download a vmware with 2 diff os  (windows, linux) on my mac then compile it on that 2 os to get the bindings?

**Comment by kzimny** [comment]
AFAIK this is the only way to get it work.
