### ISSUE TITLE
executableArgs do not work on snap

### ISSUE THREAD

**Issue by Laruxo** [electron-userland/electron-builder#4587]
I have quite simple requirement to have app start on boot and to do it minimized. So far snap gives me the biggest headache. I already have autoStart working and now I am trying to make it start hidden. From what I've read the best way is to add `--hidden` argument when it is starting on boot. For that in snap desktop file I need this line: `Exec=myApp --hidden`

I've tried adding `executableArgs: ['--hidden']` to linux target, but it did not work. From what I could find this condition seems to be at fault - https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/LinuxTargetHelper.ts#L95

`exec` is equal to `packager.executableName`, so it cannot be `null`:
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/snap.ts#L182

I would be happy to make a PR to fix this but I am not sure if `executableArgs` can be safely moved out of that `if`. Or maybe there is some better solution?

This could also solve AppImage issues such as https://github.com/electron-userland/electron-builder/pull/4496

**Comment by Laruxo** [comment]
Still relevant. Need input from the devs how to fix this.

**Comment by develar** [comment]
> I would be happy to make a PR to fix this but I am not sure if executableArgs can be safely moved out of that if

To answer, need to try. I suggest to do some changes and prepare PR. I will take responsibility to finish PR as nessary.

**Comment by Cabecinha84** [comment]
We are also facing issues, in our case we are trying to add --no-sandbox but its not added, and we are using the latest version of the builder. So the AppImage generated doesn't run for example on debian 10.

`"linux": {
      "icon": "build/icons",
      "target": [
        "deb",
        "AppImage"
      ],
      "executableArgs": [
        "--no-sandbox"
      ]
    },`

**Comment by jojapoppa** [comment]
Can we please get some action on this item?  It would resolve the issue that AppImages cannot work properly on Debian, as the --no-sandbox flag will not work without this fix.  The executableArgs section is supposed to be functional.  tx
