### ISSUE TITLE
disable update functionality? 

### ISSUE THREAD

**Issue by wesleywesley** [electron-userland/electron-builder#459]
I don't need any update functionality, how can I disable it?

**Comment by develar** [comment]
It doesn't make any sense, see #279.

If you want to disable OS X zip building, set [target](https://github.com/electron-userland/electron-builder/wiki/Options#OsXBuildOptions-target) to `dmg`.

**Comment by wesleywesley** [comment]
So solution is to program the squirrel startup events and just quit immediately? Seems like some wasted resources though?

**Comment by develar** [comment]
@wesleywesley Well, we can produce 7z self-extracted archive or just archive (e.g. zip). Is what you want instead of Squirrel.Windows?

**Comment by wesleywesley** [comment]
No, I would like an actuall installer (so that it adds desktop shortcuts and other things). Just not update functionality.
