### ISSUE TITLE
Windows install location

### ISSUE THREAD

**Issue by JasonCraneAdkins** [electron-userland/electron-builder#4598]
# Feature Request

## Change of Install Location
Installation should be located at “c:\Program Files” or “c:\Program Files (x86)”

## Feature motivation
Installation of Software (Executable) in AppData often been abused to install Scamware or other malicious Software without Admin Privileges.
AntiVirus Software and Intrusion Prevention software often block installations to this Folder.
In addition, most Companys prevent Installation to this location as well.

A Application as nice as Notable shouldn’t use a install locations preferred by Malicious Software.

And yes, I tried Installation with Administrative rights, same result

## Notable asked me to open this request on electron-builder.
https://github.com/notable/notable/issues/978

**Comment by DrakeXiang** [comment]
I think if you choose 'install for me'(not the exact words, but you know what I mean) you will get AppData as default installation path, if you choose 'install for all users' or `perMachine` is set to `true` you will get `c:\Program Files` as default path.

**Comment by JasonCraneAdkins** [comment]
if i would had this choice, i would have not open up this request

**Comment by Qazzian** [comment]
I don't get this choice. App is installed in <userFolder>/AppData/Local/Programs/<packageName>
