### ISSUE TITLE
Parallelize builds more

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-builder#4603]
I think builds should be parallelized more.

Currently for example as far as I can tell electron-builder just waits for my mac builds to be notarize and compressed, which takes forever, before building the other artifacts.

I think the various supported platforms (macOS, linux and win) should have their artifacts build in parallel, possibly also multiple assets for the same platform should be build in parallel as well.

This would cut down the time it takes me to make releases _considerably_, possibly even more if I switch to a machine with more cores.

**Comment by fabiospampinato** [comment]
Maybe I could just call electron builder 3 times in parallel, one for each platform, and each time tell it specifically which platforms to build for 🤔

**Comment by fabiospampinato** [comment]
> Maybe I could just call electron builder 3 times in parallel, one for each platform, and each time tell it specifically which platforms to build for 🤔

Apparently this works, and with it I've been able to cut my build times by a factor of 2.

However a more built-in solution would be able to achieve more, like different builds for the same OS should probably be computed in parallel. I can achieve a 2x speed up just because notarization takes forever, but most compute time is actually spent on building artifacts for Linux for me, and those are still run serially with this trick.

**Comment by fabiospampinato** [comment]
Here we go again...

**Comment by fabiospampinato** [comment]
😩 @develar

**Comment by fabiospampinato** [comment]
😩😩 @develar

**Comment by fabiospampinato** [comment]
What I love about idiotbot here is that even if you engage with it it still succeeds in closing issues.

**Comment by pie6k** [comment]
I agree. I have notarize script that takes a bit of time and is performed in sequence for each build (arm and x64 on mac). I'd prefer those to happen in parell as they're not really heavy to do, but long because I wait for apple server.

**Comment by philip-peterson** [comment]
I would also like to see this. Can the issue be reopened?
