### ISSUE TITLE
Manual password entry for EV cert on Windows

### ISSUE THREAD

**Issue by tdbender** [electron-userland/electron-builder#4604]
* **Version**: 21.2.0

* **Target**: Windows, nsis

I'm signing using an EV certificate, but for each file signed I'm prompted to enter the cert password.  None of the documented ways of providing a password seem to work (CSC_KEY_PASSWORD, WIN_CSC_KEY_PASSWORD, certificatePassword).  Debug logs show signtool isn't being invoked with the "/p" option.  Is this not possible for EV certificates or am I missing something?

**Comment by kzimny** [comment]
In my case the ev certificate was distributed on a USB flash drive. I had to install the SafeNet Authentication Client. In client settings there is an option to enable single logon.
![image](https://user-images.githubusercontent.com/12007674/72806972-a6b5ae80-3c56-11ea-88b3-1b0817fe144b.png)
Maybe are you looking for [integrated ](https://www.electron.build/tutorials/code-signing-windows-apps-on-unix.html#integrate-signing-with-electron-builder) signin option?

**Comment by tdbender** [comment]
This is very helpful.  With "single logon" enabled, I entered the password once (OK twice, since sha1 and sha256 signing apparently happens in parallel), but didn't have to enter it again after that.  Previously each build required entering the password 12 times.  I suspect I won't be required to enter it again until I reboot, or logoff.

Thank you!
