### ISSUE TITLE
How to get feedURL on download-updated?

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [electron-userland/electron-builder#4608]
* **Version**:  22.2.0

* **Target**:  Ubuntu

So, we use electron builder to handle auto update, I'm trying to get the feed url.

- I tried https://www.electron.build/auto-update#event-update-downloaded
`autoUpdater.signals.updateDownloaded((info: UpdateDownloadedEvent)` but it doesn't have the url info
- I tried https://electronjs.org/docs/api/auto-updater#event-update-downloaded
`autoUpdater.on('update-downloaded', function(event: any, releaseNotes: any, releaseName: any, releaseDate: any, updateUrl: any):` but still updateUrl is null.
- Also tried `autoUpdate.getFeeedUrl()` but it return "function is deprecated"

**so the question is how can I get the feed/update url?**

**Comment by kzimny** [comment]
Check the [documentation](https://www.electron.build/auto-update#quick-setup-guide). Set the url in package.config as follow:
```
        "publish": {
            "provider": "generic",
            "url": "https://www.mysite.org/myFolder/${os}",
            "channel": "latest"
        },
```

**Comment by AhmedAbdoOrtiga** [comment]
> Check the [documentation](https://www.electron.build/auto-update#quick-setup-guide). Set the url in package.config as follow:
> 
> ```
>         "publish": {
>             "provider": "generic",
>             "url": "https://www.mysite.org/myFolder/${os}",
>             "channel": "latest"
>         },
> ```

That doesn't solve it, I'm asking about the provided API's that doesn't seem to work, I already set the url, I wanna get it in **updateDownloaded** even or using **getFeedUrl()**

**Comment by jackple** [comment]
+1

**Comment by Alnarra** [comment]
Has there been any update on an api to get this? That doesn't involve directly tapping the package.json file? Clearly it's being stored somewhere

**Comment by moloch--** [comment]
This is becoming much more of a problem with the MacOS x64/arm64, since builder produces a single yml per OS (instead of OS/Arch) the auto updater will always download either x64 or arm64 regardless of the runtime architecture. There also doesn't seem to be any good way to modify the feed URL at runtime to select the proper architecture due to this issue.
