### ISSUE TITLE
stdout maxBuffer exceeded when creating delta package

### ISSUE THREAD

**Issue by guidupuy** [electron-userland/electron-builder#461]
I'm creating windows installer from Mac OSX, using the `removeReleases` option so Squirrel can generate delta updates. Everything's working fine, up to a point:

- `electron-builder` correctly fetches my remote `RELEASES` file and downloads the latest full update package
- It then successfully creates the new installer and full update package.
- It then proceeds to create the delta package, but fails with the following message:

  ```
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
From previous event:
    at exec (/Users/guillaumedupuy/project/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:45:10)
    at /Users/guillaumedupuy/project/node_modules/electron-winstaller-fixed/lib/index.js:224:47
    at [object Generator].next (native)
```

It looks like `electron-winstaller-fixed` is using `exec`, which, in this case, is a rather bad idea since the output from `DeltaPackageBuilder` can be really large, ultimately causing a `maxBuffer exceeded` error.

I think the blame can be put on https://github.com/develar/windows-installer/commit/9afd116b739b07719987d2bd0e66eafd95581903 - see my [comment](https://github.com/develar/windows-installer/commit/9afd116b739b07719987d2bd0e66eafd95581903#commitcomment-17716268) there.

**Comment by develar** [comment]
https://github.com/develar/windows-installer/commit/9afd116b739b07719987d2bd0e66eafd95581903#commitcomment-17716337

**Comment by guidupuy** [comment]
Hey @develar, I see you closed the issue - is any fix in the works?

**Comment by guidupuy** [comment]
Thanks for the temp fix!
