### ISSUE TITLE
Sqlite3 native dependency crashes on MAS build

### ISSUE THREAD

**Issue by steve981cr** [electron-userland/electron-builder#4616]
* **Version**: 22.3.2

* **Target**: mas

This is my first Electron app so probably I am just missing a step or two to resolve this issue. Or maybe it's a bug.

My electron app uses a SQLite database and requires the sqlite3 npm package.
To work in the development environment it must be rebuilt into a binary file using  electron-rebuild. This works fine in development.
But when I build for the MAS using the required sandbox entitlement it crashes on launch. To isolate the issue I used the process on a Hello World app. I can build it for the MAS fine but if I install the sqlite3 dependency and require it (even without using the database) it crashes on launch. Below are the messages. I highlighted in yellow what seems to be significant.
<img width="419" alt="error-img1" src="https://user-images.githubusercontent.com/3175290/73143501-88352600-404f-11ea-8aa2-c55454c65dbf.png">

<img width="419" alt="error-img2b" src="https://user-images.githubusercontent.com/3175290/73143561-9899d080-4050-11ea-86c9-d01004d80fa4.png">

Appears to be an issue with signing the sqlite3 native dependency if I follow it correctly. Says something about Library Validation and library load disallowed by system policy. 
Do I need to take some additional steps?

**### Additional   Information:**
• I have the relevant signing certificates installed: 3rd Party Mac Developer Application and 3rd   Party Mac Developer Installer.
• I'm not requesting any entitlements other than the required ones for sandboxing.
```
    <key>com.apple.security.app-sandbox</key><true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>12345ABCDE.com.domainname.appname</string>
    </array> 
```
• I created a provision profile for the app using my 3rd Party Mac Developer Application certificate. It's in a file at the project's root directory called MacAppStore.provisionfile.

**MAS build console logs**
During the MAS build for production, sqlite3 is rebuilt as a native dependency. Below are the console logs:
```
•   electron-builder  version=22.3.2   os=18.7.0
•   loaded configuration  file=package.json   ("build" field)
•   writing effective config    file=dist/builder-effective-config.yaml
•   rebuilding native dependencies    dependencies=sqlite3@4.1.1 platform=darwin arch=x64
•   packaging       platform=mas arch=x64   electron=6.1.7 appOutDir=dist/mas
• signing         file=dist/mas/AppName.app   identityName=3rd Party Mac Developer Application: TeamName (12345ABCDE)   identityHash=SOMELONGSTRING provisioningProfile=MacAppStore.provisionprofile
```

**Some info from the Sqlite3 docs which may be relevant:**

> The sqlite3 module uses node-pre-gyp to download a pre-compiled binary for your platform, if it exists. Otherwise, it uses node-gyp to build the extension. It is also possible to make your own build of sqlite3 from its source instead of its npm package.

**Relevant keys from the package.json file:**
I tried this with and without the postinstall script, and also tried setting buildDependenciesFromSource to true.  
```
"dependencies": {
  "sqlite3": "^4.1.1"
},
"devDependencies": {
  "electron": "^6.1.7"
},
"scripts": {
  "postinstall": "electron-builder install-app-deps"
},
"build": {
  "appId": "com.domainname.appname",
  "mac": {
    "target": "mas",
    "hardenedRuntime": false,
    "gatekeeperAssess": false,
    "entitlements": "build/entitlements.mas.plist",
    "entitlementsInherit":   "build/entitlements.mas.inherit.plist",
    "provisioningProfile":   "MacAppStore.provisionprofile",
    "type": "distribution",
  }
}
```

**Comment by develar** [comment]
Coluld you please try to add:

```
<!-- https://github.com/electron-userland/electron-builder/issues/3940 -->
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
```

to your `entitlements` file?

**Comment by steve981cr** [comment]
Unfortunately that didn't work. My interpretation of the Apple docs is that:
1) some entitlements are designed to work on hardened runtime (which you use when distributing outside the MAS). The entitlement you mentioned is one of those. Here's the link to the hardened runtime entitlements https://developer.apple.com/documentation/security/hardened_runtime_entitlements
and heres the link to the disable-library-validation entitlement https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation 

2) And others are designed to work on sandboxed apps (disable-library-validation is not one of those) which are listed at https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1

**Comment by kzimny** [comment]
Indeed strange issue. I'm using sqlite3 without having similar trouble, but I don't build with target set to "mas". Can you try with the following configuration?
```
  "mac": {
    "hardenedRuntime": true,
    "gatekeeperAssess": false,
  }
```

**Comment by steve981cr** [comment]
Thanks, that works for distributing outside the Mac App Store if you also notarize the app and add hardened runtime entitlements of:
```
<key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
<key>com.apple.security.cs.disable-library-validation</key><true/>
```

But to distribute the app through the Mac App Store the app needs to be sandboxed, meaning the app is self contained. For that you need to use the mas target and create a "provisioning profile" in your apple developer account. 

Are you intending to distribute your app on the mac app store? If so I'd be interested to know if you get the same errors I do. 

And actually I found additional information since posting this issue. Adding:
```
"asarUnpack": [
  "**/*.node"
]
```
to the package.json file under the "mac" key will allow the signed sqlite binary file to be read by Apple. So that solved the signing issue. But I'm still not out of the woods. I'm now getting a new error, also from sqlite3, that crashes the app on launch. I've queried the Apple Support forum. We'll see what they have to say. Another point is this is not specific to Sqlite. I tried it with other node dependencies and they throw the same error. Seems all the trouble started with Catalina OS, as they threw a bunch of new roadblocks up.

**Comment by kzimny** [comment]
Yes, you are right. I'm not using mas target. In my case the size of sqlite3 database is too big to distribute to Mac App Store. Just wanted to confirm that sqlite3 works fine when distributing outside of Mac App Store.

**Comment by steve981cr** [comment]
I found the reason the app crashes when you have node native dependencies on a mas build. First, apple requires third party executables be signed in addition to the total app and the .pkg installer. Apple can't read the signature if it is inside the app.asar binary file that is created when you build the app. The solution to this is to unpack all .node executable files and put them in a folder called app.asar.unpacked. you do this by adding 
```
"asarUnpack": [
  "**/*.node"
]
```
to the package.json file in build.mac. Then the files will be signed and Apple will be able to read the signature.
But when electron-builder creates the .pkg file, it changes the permissions of the app.asar.unpacked folder not giving execute access. So when I install the app it crashes with a permissions error. The fix is to either keep the same permissions for unpacked files as they originally had, or to give permissions of 755.
@develar - this is a bug that definitely needs to be fixed.

**Comment by Padge91** [comment]
I ran into this issue today as well. App still crashes, though the initial error appears to be gone. Now to hunt down the new error...

**Comment by bojanbizjak** [comment]
Same issue

**Comment by xintengbao** [comment]
same issue, do you have solution？

**Comment by QAQmmttyyy** [comment]
same issue

**Comment by QAQmmttyyy** [comment]
same issue @steve981cr hi, did you fix it now?

**Comment by serdarde** [comment]
Hey @Padge91, can you please share your solution to this issue? Thanks

**Comment by Padge91** [comment]
@serdarde It's been a while and I'm no longer with the same company, but if I remember correctly, I ended up building for pkg instead (I believe this issue only effects mas installs.). That had its own issues, but I eventually got something working.

**Comment by serdarde** [comment]
Thanks for the quick return @Padge91 🙏🏼
