### ISSUE TITLE
AppImage icon not working

### ISSUE THREAD

**Issue by Coding-Kiwi** [electron-userland/electron-builder#4617]
* **Version**: 
21.2.0

* **Target**: 
linux, Appimage

As stated in the [docs](https://www.electron.build/configuration/appimage):

> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.

I'm not a big fan of this decision but it for sure has reasons, idk.
I tried out linux mojave (arch linux) and installed the appimagelauncher to integrate the AppImage, Sadly there is no icon in the start menu.

 The AppImage [docs ](https://docs.appimage.org/reference/appdir.html) say the icon file has to be in `<root>/usr/share/icons/<theme>/<resolution>/apps/myapp.<ext>`, I extracted the AppImage generated by electron-builder and the icon file in there symlinks to `usr/share/icons/hicolor/scalable/myapp.svg`, as you see `/apps` is missing, this might be the cause?

**Comment by Coding-Kiwi** [comment]
Yes it is still relevant.
Whats blocking it? well nobody seems to care.

**Comment by digimezzo** [comment]
@Coding-Kiwi I have no idea how to resolve this on AppImage level, but I just applied a workaround to my project, which I found by looking at other open source projects.

1. Add a "static" folder to your Electron project

![image](https://user-images.githubusercontent.com/11945339/80907558-877bf200-8d18-11ea-85b4-70e5ab2d855e.png)

2. Add some icons to them in png format. I found that a 64x64 png icon looked best in the docks in Linux. Larger sizes are jagged.

3. In you main.ts, add this:

```
import * as os from 'os';

const globalAny: any = global; // If you use TypeScript, Global does not allow setting custom properties.

// Static folder is not detected correctly in production
if (process.env.NODE_ENV !== 'development') {
  globalAny.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\');
}

Then, when creating the BrowserWindow, you can reference the icons:

mainWindow = new BrowserWindow({
      'x': 50,
      'y': 50,
      'width': 500,
      'height': 500,
      backgroundColor: '#fff',
      icon: path.join(globalAny.__static, os.platform() === 'win32' ? 'icons/icon.ico' : 'icons/64x64.png'),
      show: false
    });
```

**Comment by puresick** [comment]
I am having the same issue with AppImages not showing any Icon, except with the workaround described in https://github.com/electron-userland/electron-builder/issues/2269

It differs from the workaround described above by digimezzo in the fact that I needed to name my icon a specific way, regardless the icons resolution: "Icon-512x512.png"

**Comment by mahnunchik** [comment]
It seems I have the same issue...

**Comment by mahnunchik** [comment]
IT IS RELEVANT!

**Comment by itsjavi** [comment]
I've set the icon path in the window settings and it shows the icon in the Ubuntu dock,
but the AppImage file itself doesn't have an icon. I don't know if that's a linux limitation?

![image](https://user-images.githubusercontent.com/122741/89659989-f7c68080-d8d0-11ea-8607-be69354a7867.png)

**Comment by martin-juul** [comment]
bump

**Comment by qishibo** [comment]
version `20.44.4` is the last version which can generate a desktop file, since `21.0.0`, the desktop file is no longer generated

**Comment by Coding-Kiwi** [comment]
@qishibo thats what I wrote in the issue description.
AppImageLauncher is inconvenient for the user and a lazy excuse by electron-builder, but even when I tried to use AppImageLauncher I could not get it to work because of wrong paths

**Comment by mahnunchik** [comment]
![201316111820369728](https://user-images.githubusercontent.com/780935/98511540-813d7400-226d-11eb-80c9-2f52097ffa4f.jpg)

**Comment by puresick** [comment]
Why has this issue been closed @develar?

**Comment by amcolash** [comment]
Pretty sure this is why things have not been working consistently for a while (2017): https://github.com/AppImage/AppImageKit/issues/346
