### ISSUE TITLE
Location of app.exe

### ISSUE THREAD

**Issue by wesleywesley** [electron-userland/electron-builder#462]
When I right-click to open the app's shortcut file location, it brings me to User/AppData/Local/AppName

In that directory, i see following structure; 

app-1.0.0
packages
SquirrelSetup (file)
Update

But not the actual app.exe, that is in the app-1.0.0 folder. Wouldn't it be better if there was some kind of shortcut or launch application in this directory too? Or, alternatively, put that squirrel and update stuff in another folder because it's quite confusing to the layman.

**Comment by develar** [comment]
Please file issue to https://github.com/Squirrel/Squirrel.Windows/issues
