### ISSUE TITLE
Cannot download update from github private repo

### ISSUE THREAD

**Issue by ShinZ6** [electron-userland/electron-builder#4621]
**electron-updater**
4.2.0

**Target**
Windows 10 1909

This issue happens only on Windows, tested the same setup on Linux and I can download and install the update from the github private repo. If I set the repo to public it works on Windows though.

Here is the error stack trace:

Found version 0.0.15 (url: pos-web-app-Setup-0.0.15.exe)
Downloading update from pos-web-app-Setup-0.0.15.exe
updater cache dir: C:\Users\User\AppData\Local\pos-web-app-updater
No cached update info available
Download block maps (old: "https://api.github.com/repos/ShinZ6/pos-electron-builds/releases/assets/17605956.blockmap", new: https://ap
Cannot download differentially, fallback to full download: Error: Cannot parse blockmap "https://api.github.com/repos/ShinZ6/pos-electhub.com/repos/ShinZ6/pos-electron-builds/releases/assets/17605956", status 404: Not Found
    at ClientRequest.<anonymous> (C:\Users\User\AppData\Local\Programs\pos-web-app\resources\app.asar\background.js:2:62915)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:11588) UnhandledPromiseRejectionWarning: Error: Cannot download "https://api.github.com/repos/ShinZ6/pos-electron-builds/release
    at ClientRequest.<anonymous> (C:\Users\User\AppData\Local\Programs\pos-web-app\resources\app.asar\background.js:2:62915)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:11588) UnhandledPromiseRejectionWarning: Error: Cannot download "https://api.github.com/repos/ShinZ6/pos-electron-builds/release
    at ClientRequest.<anonymous> (C:\Users\User\AppData\Local\Programs\pos-web-app\resources\app.asar\background.js:2:62915)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)

**Comment by didiokener** [comment]
Having the same issue.
I thought the commit #4568 had solved this issue, but it seems did not.
My versions:
"electron": "^7.1.10",
"electron-builder": "^22.3.2",
"electron-updater": "^4.2.0"

**Comment by mozainuddin** [comment]
Me too. the exact same issue

- electron: 7.1.11
- electron-builder: 22.3.2
- electron-updater: 4.2.0

**Comment by mantis** [comment]
From looking at the HTTP requests:

```
This calls <repo>/releases/latest - with a security token
 Gets back JSON object with .exe (id=068), .exe.block (id=069), latest.yml (id=087)

It then tries to request 087 - which is the latest.yml file - with a security token
 Gets back a yaml file containing version, files, url:.exe, path.exe

It then tries to request for the api <repo>/releases/assets/068.blockmap - with a token

It then makes a 2nd request for the api <repo>/releases/assets/068.blockmap - with a token

Finally it tries to make a request for <repo>/releases/assets/068 - without a security token - which fails with a 404
```

Not being an expert, but it looks like it's calculating the wrong path for the blockmap, and also dropping the security token when it falls back from the differential to the full download

**Comment by VitruxPT** [comment]
electron: 8.0.0
electron-builder: 22.3.2
electron-updater: 4.2.0

Same issue here, but I also get a `[error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB` error after `Download block maps (old: "https://api.github.com/repos/VitruxPT/w-assistant/releases/assets/17927075.blockmap", new: https://api.github.com/repos/VitruxPT/w-assistant/releases/assets/17927075.blockmap)`

Blockmaps are also the same (new and old)

**Comment by hmpargi** [comment]
**electron-builder version: ^22.3.2"
electron version: ^8.0.0"
electron-updater version: 4.2.0"
Target: Windows 10
Github Private repository**

**`[2020-02-13 22:17:34.744] [info] Checking for update
[2020-02-13 22:17:37.465] [info] Found version 1.0.0 (url: psstracker-Setup-1.0.0.exe)
[2020-02-13 22:17:37.465] [info] Downloading update from psstracker-Setup-1.0.0.exe
[2020-02-13 22:17:37.469] [info] No cached update info available
[2020-02-13 22:17:37.471] [info] Download block maps (old: "https://api.github.com/repos/myusername/psstracker/releases/assets/18021931.blockmap", new: https://api.github.com/repos/myusername/psstracker/releases/assets/18021931.blockmap)
[2020-02-13 22:17:37.934] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\har\Desktop\Myapps\epssapp\psstracker\dist\win-unpacked\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:239:26)
    at ClientRequest.<anonymous> (C:\Users\har\Desktop\Myapps\epssapp\psstracker\dist\win-unpacked\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:298:17)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)`**

I having the same issue. exact same

**Comment by mozainuddin** [comment]
It worked/fixed for me after upgrading electron-updater to v4.2.2.

**Comment by didiokener** [comment]
It worked for me as well.
`electron: 8.0.1,`
`electron-builder: 22.3.2,`
`electron-updater: 4.2.2`

**Comment by hmpargi** [comment]
> It worked/fixed for me after upgrading electron-updater to v4.2.2. =D
> 
> * electron: 8.0.1
> * electron-builder: 22.3.2
> * electron-updater: 4.2.2

So  how you guys doing authentication to github. SetfeedURL ?

`ipcMain.on('autoUpdate.status', () => {
  const data = {
  "provider":"github",
  "owner":"theowner",
  "repo":"electronrepo",
  "token": process.env.GITHUB_TOKEN
  };
  updater.setFeedURL(data);
});`

Also are you guys puting Token inside pakage.json ?
Can you please give me package.json and setFeedURL Settings?

**Comment by mantis** [comment]
I think i'm stuck at the same point as @hmpargi - best I can managed at the moment is a cannot download incrementally, the old+new block maps showing the same url, and a 404 when trying the download

**Comment by mozainuddin** [comment]
> 
> 
> > It worked/fixed for me after upgrading electron-updater to v4.2.2. =D
> > 
> > * electron: 8.0.1
> > * electron-builder: 22.3.2
> > * electron-updater: 4.2.2
> 
> So how you guys doing authentication to github. SetfeedURL ?
> 
> `ipcMain.on('autoUpdate.status', () => { const data = { "provider":"github", "owner":"theowner", "repo":"electronrepo", "token": process.env.GITHUB_TOKEN }; updater.setFeedURL(data); });`
> 
> Also are you guys puting Token inside pakage.json ?
> Can you please give me package.json and setFeedURL Settings?

I have the token inside pakage.json 

- Package.json

```
"build": { 
[...],
"publish": [
      {
        "provider": "github",
        "repo": "<repo-name>",
        "owner": "<username>",
        "token": "<TOKEN>",
        "private": true
      }
    ],
[...]
}
```

I didn't use the setFeedURL, it does it automatically for me.

- main.js

```

const { autoUpdater } = require('electron-updater');

// on function ready
  autoUpdater.checkForUpdatesAndNotify();


// autoUpdater status
  autoUpdater.on('checking-for-update', () => { ...  });
  autoUpdater.on('update-available', (info) => { ... });
  autoUpdater.on('update-not-available', (info) => { ...  });
  autoUpdater.on('error', (err) => { ... });
  autoUpdater.on('download-progress', (progressObj) => { ...  });
  autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => { ... });
```

**Comment by mantis** [comment]
I've tried specifying  the repo/owner/token in the publish bit, and for me at least, I still get the original behaviour - it tries to download the same old/new blockmaps - tries to fall back and download an asset and gets a 404

**Comment by mantis** [comment]
it's 1am, but i've debugged this tonight, and worked out what's going on. Will try and work out a PR for this tomorrow.

**Comment by VedranKapor** [comment]
I do not use electron builder but
`  "devDependencies": {
    "electron": "^8.2.5",
    "electron-packager": "^14.2.1",
    "electron-winstaller": "^4.0.0",
  }`
when I set my feedUrl as
`const squirrelUrl = "https://github.com/VedranKapor/electron-autoupdate-wininstaller/releases/latest"; 
  autoUpdater.setFeedURL({ provider: 'github', url:squirrelUrl, token: 'token' });`
i try to do autoupdate from public gitHub release using electron squirrel, but I get this error.
![squirrelError](https://user-images.githubusercontent.com/35230669/82125083-c6dc2100-97a3-11ea-9971-b8d9bba2a9cc.PNG)

Please help.
Thanks
