### ISSUE TITLE
How to exclude file when build electron with electron-builder?

### ISSUE THREAD

**Issue by hh54188** [electron-userland/electron-builder#4623]
* **22.2.0**: 

* **win**: 

What I want is not exclude unused file, but exclude used file package into `.exe` file

I provide a file like `config.json` for user to edit some custom config, then the application could read the file to do something. So I don't hope this file package into `.exe` file.

How should I config electron-builder to exclude this file?

**Comment by kzimny** [comment]
Are you looking for the [files ](https://www.electron.build/configuration/contents.html#files) option?
```
    "build": {
        "files": [
            "!myconfig.json"
        ],
    },
```
