### ISSUE TITLE
Uninstall application at old path when new application is installing to a new path

### ISSUE THREAD

**Issue by jsheffers** [electron-userland/electron-builder#4624]
electron-builder: 22.10
electron-updated: 4.2.0 
NSIS - Windows

I used the custom NSIS script in the documentation to change the install directory for my application:

```
!macro preInit
  SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Folder\Another\Folder"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Folder\Another\Folder"
  SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Folder\Another\Folder"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Folder\Another\Folder"
!macroend
```

This works great however, I want to change that installation directory to a new path (after the application has already been installed on 350+ machines).  If I push a new update my application will check for updates, find a new update and then download and install it.  

*Old*
`C:\Users\joe\AppData\Local\Appname`

*New*
`C:\Appname`

I now have two of the applications installed on the computer (I only want the new one).  Technically only the new one shows up in add/remove programs, but the old version still exists in the file system.  Is there a way to ensure that old application gets removed?  Since it seems like it is being overwritten (not showing up in add/remove programs) is it safe to just remove the old path directory and files?

**Comment by idanwork** [comment]
Hi 

I use something similar, uninstall very old version by executing the QuietUninstallString from the registry.

Add this to your _preInit_

```nsh
  ReadRegStr $0 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{your guid here}"  "QuietUninstallString"
  ${IfNot} ${Errors}
  ${AndIfNot} $0 == ""
    ExecWait '$0'
  ${EndIf}
```

Change if you need from HKLM to HKCU ( I see you have both)


I also add   
```nsh
ClearErrors
```

After each removal but it's more of precaution
