### ISSUE TITLE
shared folder

### ISSUE THREAD

**Issue by wesleywesley** [electron-userland/electron-builder#463]
I have a folder that i'd like to remain after updates and even when the user downloads an installation file and runs it again. Specifically for mac, I'd like that folder to be put in /Users/name/Library/Application Support/AppName. 

How could I accomplish this? It seems everything is now kept in the .app itself. Note that this folder should be updateable too. 

Impossible? or not?

**Comment by develar** [comment]
You can do what you want in the local FS. See https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by wesleywesley** [comment]
one final question (sorry), but are the squirrel windows events also available on mac? I'd like to copy the folder from the app to the shared location on the event "--squirrel-updated". How would you do that on mac?

**Comment by develar** [comment]
On OS X no such events. You can use https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

>  I'd like to copy the folder from the app to the shared location

Maybe just copy folder on start if doesn't exists?

**Comment by wesleywesley** [comment]
Folder needs to be overwritten for every update, but I suppose I can compare some files or save some setting with version info. thanks.
