### ISSUE TITLE
Automatic upgrade failed

### ISSUE THREAD

**Issue by kf53916** [electron-userland/electron-builder#4638]
* **Version**: 
electron：7.1.11
electron-builder：21.2.0
electron-updater：4.2.0

* **Target**: 
target：zip，nsis
platform：win32 
arch：x64
os：10.0.17763

The installation package has been downloaded to the local computer. After starting the upgrade installation wizard, the installation progress is halfway back, causing the update to fail. If you cancel the upgrade and open the application again, it will automatically update to the latest version.
The main.log file prints out： [error] Cannot download differentially, fallback to full download

**Comment by kzimny** [comment]
Try again with electron-builder v.22.3.2

**Comment by jsheffers** [comment]
Confirmed this still happens with v.22.3.2
