### ISSUE TITLE
DMG build fails if internetEnabled, v7.1.10 with node v13.7

### ISSUE THREAD

**Issue by grumpygary** [electron-userland/electron-builder#4639]
Which version of electron-builder:
7.1.10

Which version of electron-updater:
4.2.0

Node version:
13.7 (note: the build also fails with node LTS v12.14.1)

Target:
MacOS DMG

Build works fine if !internetEnabled.  If internetEnabled == true, it fails with: "require(...).split is not a function" in dmg.ts, line 61 (which I believe is transpiled into dmg.js, line 165, where require("os").split(".") is used.

My assumption is that this has to do with the node version, since the call is looking for the first element in the split array.  If I call "require("os").split(".")" in my main/index.js it throws the same exception.

**Comment by kzimny** [comment]
Try to build with v.22.3.2 of electron-builder.

**Comment by grumpygary** [comment]
oops.  I was incorrect above:

electron is 7.1.10 (latest)
electron-builder is 22.3.3  (which is later than your suggestion)

BTW, thanks for the rapid response!

**Comment by grumpygary** [comment]
BTW, getting production builds to work like the dev builds do is a real challenge.  Do you know where to find an overview of the various production paths -- by platform -- for: the app root (my app files are in a folder of of that), as well as user data files?  Your docs are technically correct, but how the production apps differ from the dev version could use a separate explanation.

**Comment by grumpygary** [comment]
Um... I just checked again (to make sure), and I am using 22.3.2.  Oops...

**Comment by CharonTao** [comment]
Um,I had the same problem。Then I checked the source code of the electron builder git repository。I find it.
`
if (this.options.internetEnabled && parseInt(require("os").split(".")[0], 10) < 19) {
      await exec("hdiutil", addLogLevel(["internet-enable"]).concat(artifactPath))
    }
`
'require("os")' is Object , You can't use “split” method

**Comment by jhbsa** [comment]
I just updated electron-builder to latest (22.6.0) on MacOS Catalina and am receiving this same error - which consequently fails the build. I would say it is still relevant Mr. Stalebot.

**Comment by jhbsa** [comment]
as a followup, I believe the intended code should have been:
parseInt(require("os")**.release()**.split(".")[0], 10)

Now I just need to figure out how to create a pull request and get it approved. Or perhaps I can request an update to the pull request associated with this bug. @migliorinie can you make this minor change to fix this bug and update/resend a pull request to the project? Please :)
