### ISSUE TITLE
Reason for "couldn't create a delta for atom.asar, attempting to create bsdiff" error

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#464]
Up until recently, I've been able to generate delta packages (windows). Now I keep getting error, and I'm not sure if it's stuck or it just hangs for a really long time, because it will stay on that step for 5-10 minutes. I have no problem creating the -full.nupkg file individually (without delta files) though.

**Comment by develar** [comment]
Previously such warn was not printed to console. But now you see it. Squirrel.Windows delta building just sucks and we not yet fix it. On slow machine it can take 20 minutes.

**Comment by develar** [comment]
In my fork I fixed error logging and got real error:

"
2016-06-05 16:44:15> DeltaPackageBuilder: We couldn't create a delta for Onshape.exe, attempting to create bsdiff: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.CreateDelta(String oldFilePath, String newFilePath, String deltaFilePath)
   at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing)
2016-06-05 16:45:58> DeltaPackageBuilder: \lib\net45\snapshot_blob.bin
"

@taspeotis Do you have any clue why "The operation completed successfully" leads to System.ComponentModel.Win32Exception?

**Comment by develar** [comment]
Ideally, we should use bsdiff to get uncompressed out and then compress using lzma (as xdelta does). But unlikely I will fix it. NSIS support is coming with autoupdate instead of Squirrel.Windows.

**Comment by taspeotis** [comment]
Hi, v1 of *DeltaCompressionDotNet* didn't have [`SetLastError = true`](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.dllimportattribute.setlasterror(v=vs.110).aspx) for P/Invoke. So there's an error, but we've lost our chance to get the error code.

It also didn't set some flags like ignore memory constraints.

https://msdn.microsoft.com/en-us/library/bb417345.aspx#msdelta (CTRL+F `DELTA_FLAG_IGNORE_FILE_SIZE_LIMIT`).

v2 *might* solve this, but Squirrel doesn't ship with it. There were some breaking changes to the API in v2, so it's currently limited to v1.x.

You could try building v1 from sources and putting `SetLastError = true` into the `DllImport` attributes as necessary, then swap your assembly in lieu of the one that ships with Squirrel.

**Comment by develar** [comment]
@taspeotis Thanks a lot for answer. I read about DELTA_FLAG_IGNORE_FILE_SIZE_LIMIT in your readme but didn't realise that it is only in the v2.

In any case we use our own fork of Squirrel.Windows. I will test fix in the my fork and then send PR to Squirrel.Window.

**Comment by taspeotis** [comment]
You're welcome. Hopefully what I conveyed is correct, it's been a while since I did the file limit changes.

If you are worried about memory usage, you can take a look at MSDN's documentation [here](https://msdn.microsoft.com/en-us/library/bb417345.aspx#runtime_reqs). The key is:

* Process: `CreateDelta`
* Estimated Memory Usage (MB): `10.2 * ( SourceSize + TargetSize ) + 2.7`

So your 160mb file will require ~3.3GB of memory assuming the source and destination are approximately 160mb. This is too much for a 32-bit process.

**Comment by develar** [comment]
Moved to backlog. Because Squirrel.Windows will be not default target in the next major release.
