### ISSUE TITLE
Linux .desktop with options on "Exec" is refused

### ISSUE THREAD

**Issue by squalou** [electron-userland/electron-builder#4642]
* **Version**: 
using electron-builder 22.3.2

* **Target**: 
npm run dist for Linux "deb"

Issue.

I have to build a .desktop file that has, an Exec line like this :

```
Exec=env SOME_VAR="some_value"  executableName %U
```

This is supported by desktop files and should be easy to package.

I try this :

```
  "build": {
    "appId": "My App",
    "linux": {
      "category": "Network;",
      "desktop": {
        "Exec": "env SOME_VAR='some_value' myApp"
      },
      "target": [
        "deb"
      ]
    }
  },

```

I get this exception

```
 ⨯ Please specify executable name as linux.executableName instead of linux.desktop.Exec  stackTrace=
```

Of course I tried to tweak the executableName, of course it didn't work.

How am I supposed to perform this properly ?

IMHO hte exception is plain stupid, leave people who know what they do do what they want.

thanks for any idea,

regards

**Comment by squalou** [comment]
note that after a quick check in the code, I found a reference to this as a reason to ban desktop.Exec

https://github.com/electron-userland/electron-builder/issues/3418

the 'ban' solution is clearly not a solution, unless there are other means or respecting .desktop file standards which I didn't find.

**Comment by axetroy** [comment]
my solution:

add a `after-install` hook to the deb package

```json
    "deb": {
      "fpm": [
        "--after-install=script/deb_after_install.sh"
      ]
    }
```

```sh
#!/bin/sh

appID="myappid"

if [ `whoami` = "root" ];then
  echo "Exec=/opt/$appID/$appID --no-sandbox %U" >> /usr/share/applications/$appID.desktop
fi
```

It will overwrite the origin Exec with the new one
