### ISSUE TITLE
app-builder-bin folder size

### ISSUE THREAD

**Issue by grumpygary** [electron-userland/electron-builder#4643]
22.3.2

MacOs

I noticed something in the resulting macos .app file. In the sub-folder resources/app/node_modules/app-builder-bin (I can see it if I turn asar off).  It includes binaries for all platforms.  The mac binary is around 18MB, while the linux binaries total around 60MB, and Windows is another 30MB.  It seems like a waste of space/bandwidth to include all of them.  Is there a reason for this?  Is there a way to include only the binaries required for each platform?

**Comment by prv123** [comment]
I'm facing the same issue... have you found solution for it?
