### ISSUE TITLE
cannot notarize build on mac os 10.15

### ISSUE THREAD

**Issue by StebneRuslan** [electron-userland/electron-builder#4648]
macOS version - 10.15.3
Xcode version - 11.3.1

electron version - 3.1.11
electron-builder - 21.2.0
electron-notarize - 0.2.1

build an app with this electron-builder config (https://prnt.sc/qxszft)

after successful signed run this notarize command 
"xcrun altool --notarize-app -f path/to/my/app.dmg --primary-bundle-id my-app.myapp -u username -p password"

or run use electron-notarize package (https://www.npmjs.com/package/electron-notarize)
with this configuration - https://prnt.sc/qxt069

After these steps we will get errors to log like that (https://prnt.sc/qxt0q2)

Could you please help me. How I can sign chromium inside the "puppeteer" package?

**Comment by JohnDenis** [comment]
We have the same problems!

**Comment by cc-till** [comment]
Same here.

**Comment by glawson** [comment]
could be related - https://developer.apple.com/news/?id=12232019a

**Comment by twigs67** [comment]
Same. We have two packages that are being affected by this, fsevents and puppeteer. Both packages are receiving the following errors:

- The signature does not include a secure timestamp.
- The binary is not signed.
- The executable does not have the hardened runtime enabled.

 I'm a bit puzzled by this though, as asar is enabled. 

Anyone have any luck on this?

**Comment by twigs67** [comment]
Ok, I think I narrowed it down. This [tweet/video](https://twitter.com/rosyna/status/1168999285171675136?lang=ca) helped me. 

So it looks like we have to sign each of the individual packages. Now the question is, how do we do that? Any guesses @glawson @cc-till @JohnDenis @StebneRuslan

**Comment by twigs67** [comment]
There's more activity in #4656

**Comment by amargautam** [comment]
Our notarize is working fine. Not sure what your issue is. Not to deviate from the actual issue(sorry), out of curiosity, why you still using electron version - 3.1.11

By the way, we don't sign the DMG itself. Here is my config. See if this helps -

```
"mac": {
      "category": "public.app-category.xxx",
      "type": "distribution",
      "icon": "./assets/icon.icns",
      "entitlements": "./entitlements.mac.plist",
      "entitlementsInherit": "./entitlements.mac.plist",
      "hardenedRuntime": true,
      "gatekeeperAssess": false
    },
    "dmg": {
      "background": "./assets/background.png",
      "sign": false,
      "contents": [
        {
          "x": 140,
          "y": 250
        },
        {
          "x": 400,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    }
```

**Comment by twigs67** [comment]
@amargautam are you packaging any third-party binaries, e.g., chromium?

**Comment by StebneRuslan** [comment]
Will be useful https://www.npmjs.com/package/puppeteer-in-electron
this package can run electron window with puppeteer core

**Comment by StebneRuslan** [comment]
We have solved this issue.
Download chromium archive locally
Install [puppeteer-core](https://www.npmjs.com/package/puppeteer-core)
Install [asar](https://www.npmjs.com/package/asar)

before app ready event in electron, extract chromium archive to the resources folder
`asar.extractFile(path.resolve(__dirname), '.local-chromium.zip')`

set executable path to puppeteer launch

`chromium = await puppeteer.launch({
    headless: true,
    executablePath: pathToLocalChromium
  })`

**Comment by twigs67** [comment]
@StebneRuslan we're trying to package chromium with are desktop app so that users don't have to download chromium. Do you know if Apple will notarize an application that includes  ```.local-chromium.zip``` in the package?

**Comment by isaacaddis** [comment]
I still have this issue :(

**Comment by Zvika88** [comment]
Hi @twigs67 , did you find a solution to signing puppeteer within an electron app?  

I too am having this issue with my electron app, i.e. notarize fails  with: "The binary is not signed.", "The signature does not include a secure timestamp.", "The executable does not have the hardened runtime enabled." . And the errors repeat for Chromium and for all the frameworks and libraries it uses. 

Thanks for!
Z.

**Comment by Colin-Moran** [comment]
I also have this issue. Any luck @twigs67 ?

**Comment by colinfran** [comment]
@Colin-Moran @Zvika88 @twigs67 did any of you find a solution for this?

I too am using puppeteer and not able to get puppeteer's chromium code signed when I try to notarize the app.

**Comment by gregoirepuget** [comment]
@Colin-Moran @Zvika88 @twigs67 Me too.
Trying to find a solution
