### ISSUE TITLE
extraResources path?

### ISSUE THREAD

**Issue by wesleywesley** [electron-userland/electron-builder#465]
How can I get the path to extraResources items?

**Comment by develar** [comment]
In your electron app? Sorry, this question is outside of electron-builder scope ;) 

Sorry again, but if you ask about it, it seems you use `extraResources ` wrong ;) Why do you want to use extraResources?

**Comment by wesleywesley** [comment]
In my app yes, i need to get a location of a file that is in the extraResources. Then I will execute a child process for that file (executable). Seems this is exactly what extraResources are for? Don't want these files in the asar archive.

**Comment by develar** [comment]
> Seems this is exactly what extraResources are for?

Yes.

What's wrong in the docs — https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources — 

> into the app’s resources directory (Contents/Resources for OS X, resources for Linux/Windows)

?

**Comment by wesleywesley** [comment]
hmm ok that works. but this folder is deleted when I'm again calling the install. is it possible to keep it around?

**Comment by develar** [comment]
>  is it possible to keep it around?

this question is outside of electron-builder scope ;) You has full access to local FS — do what you want :) You must not put or store mutable data inside app.

**Comment by wesleywesley** [comment]
it's not "inside the app", it's inside AppData, which is supposed to hold all app data :-)

**Comment by wesleywesley** [comment]
So this is a squirrel.windows issue?

**Comment by develar** [comment]
> though the whole appData folder seems to be removed when installing again
> So this is a squirrel.windows issue?

Cannot believe... Yeah, if it is true, it is very disappointing. Yes, ask about in the squirrel.windows issue tracker.
