### ISSUE TITLE
Linux AppImage relaunch not working

### ISSUE THREAD

**Issue by Hirobreak** [electron-userland/electron-builder#4650]
* **Version**: 21.2.0

* **Version**: 4.0.0

* **Target**: Linux

In my app I have to guide the user through some steps and then restart the app to apply changes. Everything works fine on MacOS and Windows 10 but when I run the AppImage, go through the steps and restart the app, it never restarts, I have to start it manually and that ruins the UX.
I'm restarting the app as follows:
```javascript
ipc.answerRenderer('restart-app', () => {
  app.relaunch();
  app.exit(0);
});
```
I also tried to pass `execFile` but the path where the AppImage is executed first is a `/temp` folder and it does restart but with missing icons and files and it eventually crashes.

**Comment by Pabrisson** [comment]
same issue here...

**Comment by AlexandrGas** [comment]
same issue here...

**Comment by bosomt** [comment]
still broken :)

**Comment by busaku** [comment]
still broken..

**Comment by kdreaming** [comment]
still...

**Comment by ragauskl** [comment]
Got same issue, solution that worked for me was:

* Use original AppImage path, not the one in execPath pointing to /temp
* Using AppImage can result in error 'Cannot mount AppImage, please check your FUSE setup.', therefore add `--appimage-extract-and-run` as FIRST argument ([based on this](https://docs.appimage.org/user-guide/troubleshooting/fuse.html#extract-and-run-type-2-appimages))

```ts
import { app } from 'electron'

app.relaunch({
  execPath: process.env.APPIMAGE,
  args: [
    '--appimage-extract-and-run',
    ...process.argv.slice(1)
  ]
})

app.exit(0)
```

**Comment by johannesjo** [comment]
I am encountering the same problem.

**Comment by zshuaia** [comment]
+1

**Comment by ibandominguez** [comment]
@ragauskl suggestion worked great!
