### ISSUE TITLE
A question about how to build a linux destop-app successfully

### ISSUE THREAD

**Issue by zzl4883a** [electron-userland/electron-builder#4651]
"electron": "^7.1.7",
"electron-builder": "^22.3.2",

* **Version**: 

* **Target**: 
linux debain

package.config:
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron ./src/main.js",
    "buildWin": "electron-builder",
    "buildLinux": "electron-builder --linux deb tar.xz"
  },
I use the command "npm run buildLinux", it reports an error:
 cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f3nh5j: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f3nh5j: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f3nh5j: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get https://service.electron.build/find-build-agent?no-cache=1f3nh5j: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
  ⨯ E:\test\ElectronLinux\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                       Error: E:\test\ElectronLinux\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

I can build a windows desktop application successfully by using "npm run buildWin",so what should I do to solve this error?

**Comment by CodeDead** [comment]
Instead of building on Windows, you can still build Windows images on a linux system (and at the same time linux images). There's already an issue open for this as well:

https://github.com/electron-userland/electron-builder/issues/4318
