### ISSUE TITLE
Best practice for setting codesigning env variables

### ISSUE THREAD

**Issue by guidupuy** [electron-userland/electron-builder#466]
I'm struggling setting the various code-signing environment variables (`CSC_LINK`, `CSC_NAME` etc.) on Mac OSX.

My Issue is that env variables set via `npm` scripts don't seem to be picked up by `electron-builder`. Here's how my `npm` script looks like:
```
export CSC_LINK=mylink && export CSC_KEY_PASSWORD=mypwd && build -w --x64
```

Note that while this doesn't work, if I set the variables via the terminal everything works correctly. 

I'm guessing this is because the `electron-builder` code is being executed in a different process where env variables aren't available anymore, but I'm not sure. I basically have 2 questions:

- _should_ this work, ie is this the right way to set env variables in terms of best practices?
- if yes, is there a way we can ensure that env variables set via `npm` scripts get picked up by `electron-builder`?

**Comment by develar** [comment]
Never, please never use these env in your npm script (in any case Windows doesn't support it).

I hope you read https://github.com/electron-userland/electron-builder/wiki/Code-Signing

On OS X development machine it works without any configuration. Just import your cert to keychain. It will be automatically discovered and used.

On CI server see docs. 

> should this work,

**It should, but be aware of special characters (for bash)**. I suppose bash just confused and doesn't set env correctly. In this case you can set `CSC_LINK` to base64 encoded data of file. Or try to escape link (and password).

**Comment by develar** [comment]
To be clear — you use normal OS — OS X, not ugly Windows, so, for security reasons on development machine keychain is preferred way to store certs. No files, no env — it is all not secured (on CI env is secured because it is one-time isolated container).

**Comment by guidupuy** [comment]
I should have mentioned that I'm building on OSX targeting Windows, so I do need to set the `CSC_LINK` and `CSC_KEY_PASSWORD` env variables.

**Comment by guidupuy** [comment]
And it's not a problem with special characters, since using the exact same `export` command directly in terminal works.

**Comment by develar** [comment]
> since using the exact same export command directly in terminal works.

So use syntax `CSC_LINK=mylink CSC_KEY_PASSWORD=mypwd build -w --x64` (not export).

> I'm building on OSX targeting Windows, so I do need to set the

Hmm... it seems we should support this case. Do you want this feature or store cert in the fs is ok for you?

**Comment by guidupuy** [comment]
Stupid me... simply adding the env variables before calling `build` is enough for me.

**Comment by mzmousa** [comment]
@develar 
> So use syntax `CSC_LINK=mylink CSC_KEY_PASSWORD=mypwd build -w --x64` (not export).
is this the syntax to use in the npm script? Or somewhere else?

**Comment by guidupuy** [comment]
In the npm script

**Comment by daveywc** [comment]
On Windows I had to use: CSC_LINK=mylink CSC_KEY_PASSWORD=mypwd && build

Note the addition of the double ampersand to join multiple statements on the command line.

**Comment by aaronsedna** [comment]
My standard code-signing certificate is issued by Comodo CA and is valid till 2021 and the password I used is correct.

I am building on a Windows 10 Machine.

I tried setting the CSC_LINK environment variable as instructed in the video. My certificate have a password, so I used the CSC_KEY_PASSWORD to set the password as well.

But when I run "node run dist", it doesn't code sign the exe.

Can you please please help?
Has the CSC_LINK syntax changed?

Here is the link to my package.json file: https://www.dropbox.com/s/hz2wq8jrnm5rvs9/package.json?dl=0

Thanks!
