### ISSUE TITLE
Single installer for different arch targets not working

### ISSUE THREAD

**Issue by MehediH** [electron-userland/electron-builder#4661]
Using latest electron-builder, building a single NSIS installer for ARM64 and x64 fails to install the app on x64.  Works just fine on ARM64. But running the exe from the unpacked folder works on both.

The issue is the same using nsis-web, where the behaviour is opposite, with the installation working fine on x64 but failing on ARM64.

![image](https://user-images.githubusercontent.com/10274434/74101109-22a46780-4b2e-11ea-8d3c-5e4a5da7b211.png)

**Comment by kzimny** [comment]
Could be the same issue https://github.com/electron-userland/electron-builder/commit/d5a00c3e519a995a1540c8b9e89a4be7432db7f8. The fix is not yet released https://github.com/electron-userland/electron-builder/commits/master
