### ISSUE TITLE
Desktop Shortcut Icon Has to Be Manually Enabled

### ISSUE THREAD

**Issue by gtkpr** [electron-userland/electron-builder#4662]
* **Version**: 
Electron 8.0.0
Electron-Builder 22.3.2

* **Target**: 
NSIS

For some reason the desktop shortcut that is created upon installation displays an Electron icon instead of the expected icon.

    "icon": "assets/icon_256.ico",
    "nsis": {
      "installerIcon": "assets/icon.ico",
      "uninstallerIcon": "assets/icon.ico",
      "installerHeaderIcon": "assets/icon.ico"
    }

I have to manually "Change Icon..." for the expected icon to take effect.

![Image](https://i.postimg.cc/GtFDYQmq/desktop-shortcut.png)

**Comment by amargautam** [comment]
Just use this and you should be fine. This icon will be used 

```
"win": {
      "icon": "./assets/icon.ico",
      "verifyUpdateCodeSignature": true,
      "publisherName": "XXX",
      "rfc3161TimeStampServer": "http://timestamp.comodoca.com/rfc3161",
      "timeStampServer": "http://timestamp.digicert.com"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false,
      "license": "./licenses/license_en.txt",
      "artifactName": "${productName}-${version}.${ext}",
      "createDesktopShortcut": "always",
      "createStartMenuShortcut": true,
      "deleteAppDataOnUninstall": true,
      "runAfterFinish": true,
      "allowToChangeInstallationDirectory": true
    },
```

Let me know how it goes.
