### ISSUE TITLE
auto-update with new signing certificate

### ISSUE THREAD

**Issue by katat** [electron-userland/electron-builder#4664]
Hi there,

We have a mac app already support auto-update with an existing apple developer ID certificate in an organization. We are wondering if the auto-update function of the previous releases signed with the old developer ID certificate would still work with the newly pushed releases signed with a new developer ID certificate. 

For example:
1. Version 1 is signed with an old certificate
2. Version 2 is signed with a new certificate
3. Both certificates are from different developer IDs authorized by the same organization
4. Will auto-update function of version 1 still work for updating itself to version 2?

Any guidelines are appreciated!

Many thanks.

**Comment by kzimny** [comment]
Does developer ID change when certificate expires? Why are both certificate from different developer ID? You sign your app with "Developer ID Application: Your Company name (4X4JHFGJH)"

**Comment by katat** [comment]
Hi @kzimny 

> Why are both certificate from different developer ID?
Because the other developer ID comes from other developer's apple account.

**Comment by amargautam** [comment]
It doesn't matter who the developer is, the certificate that is actually used is issued by the organization. If the developers belong to the same organization, you are fine.

**Comment by siucht** [comment]
This is exactly the problem that our company has right now.

1. Version-1 signed with cert-1, by our team with devID-1
 cert-1 is expiring soon, and signing the App moved to specialized team (same company), which has devId-2 
2. Version-2 signed with cert-2, by different team with devID-2

The result: auto-update is failing with:
```
Updater - /1585584720009-4953.zip requested by Squirrel.Mac, pipe /Users/user/Library/Application Support/Caches/xxx-updater/pending/xxx.zip
main - [Error: Code signature at URL file:///xxx.app/ did not pass validation: code failed to satisfy specified code requirement(s)] {
  code: -1,
  domain: 'SQRLCodeSignatureErrorDomain'
}
```
OS: MacOS
"electron": "6.1.9",
"electron-builder": "22.4.1",
"electron-updater": "^4.1.2",

**Question**
How to make auto-updater to recognize the old signature as the valid one?

**Comment by johnryan** [comment]
@siucht Did you ever find a solution to this?

**Comment by teaxio** [comment]
Hi,
Did anyone figure out a way around this? We are in the same situation where we upgraded from personal certificate to enterprise certificate and now auto-updater is not willing to install the new version due to signature conflict `"code":-1,"domain":"SQRLCodeSignatureErrorDomain"`
Any help would be greatly appreciated.

**Comment by jasonnet** [comment]
Is there any progress on this?    If I hold the old and the new private keys, how can I fix this problem for our users?

**Comment by floating** [comment]
Hey @katat, did you ever figure out a solution here? We are in the same situation trying to upgrade from a personal certificate to an enterprise certificate.

Thanks for any pointers

cc @teaxio @jasonnet

**Comment by ratanservegar** [comment]
Hi, 
Anyone found a solution for this?

**Comment by asself** [comment]
I have the same problem

**Comment by algomage** [comment]
I also have same issue for windows
