### ISSUE TITLE
Latest electron-builder fails to install in empty project

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#4667]
`electron-builder` is currently failing to install in an empty project. I can't work out if this is an issue with npm as the package looks like [it's available](https://www.npmjs.com/package/7zip-bin/v/5.0.3).

Windows:
```
> mkdir test
> cd test
> yarn init -y
> yarn add electron-builder
```
Results in:
`error Couldn't find package "7zip-bin@~5.0.3" required by "builder-util@22.3.2" on the "npm" registry.`

**Comment by dbjorge** [comment]
The issue appears to be specific to invoking electron-builder from the context of a yarn run-script

**Comment by pfgallagher** [comment]
Having a similar issue. Thinking it may be an NPM issue. Possibly coincidental, but it seems to be specific to packages that start with a digit.

**Comment by timfish** [comment]
Yeah this is almost certainly a yarn/npm issue. `yarn add 7zip-bin` also fails

**Comment by karanbirsingh** [comment]
yarn issue here: https://github.com/yarnpkg/yarn/issues/7902 (another instance of starting-with-digit)

**Comment by timfish** [comment]
I'll close this for now then as it doesn't look like it's an electron-builder issue
