### ISSUE TITLE
Question: win packager icon size check

### ISSUE THREAD

**Issue by JimiC** [electron-userland/electron-builder#467]
I noticed that there is a check on the icon size when packaging windows artifacts. Any particular reason  why the icon size has to be greater or equal to 256 pixels? From my experience 128 pixel icon works equally fine.

Thanks in advance.

**Comment by develar** [comment]
Squrrel.Windows requires this size. And Windows.

Please see — http://stackoverflow.com/questions/3236115/which-icon-sizes-should-my-windows-applications-icon-include

**Comment by JimiC** [comment]
Damn. Didn't knew that 256px has become mandatory for Vista+. I always used an icon with 16, 32, 48, 64,128 resolution. According to the stackoverflow topic you linked, the 256 version only gets used when scaling the display resolution to 200%. Quite rear in the early days of SD monitors but with the 4K monitors around the corner I bet that 512 will become mandatory too.

Thanks a lot for the info. Much appreciate it.
