### ISSUE TITLE
Question: How to tag GitHub releases

### ISSUE THREAD

**Issue by vitalykarasik** [electron-userland/electron-builder#4671]
21.2.0

* **Target**:  Mac and Windows

From my Jenkins CI I need to publish every build, and download & install on the next step.
According to https://www.electron.build/configuration/publish, I should "Set the “Tag version” to the value of version in your application package.json, and prefix it with v".
But in fact  my situation is:
- "version": "0.0.420rc" (package.json)
- builder publishes release to '0.0.420-rc' and it's tricky to download because of GitHub's random prefix (.../untagged-4c47c21b6ea10a4fc994/....)
- I created v0.0.420rc tag, but it didn't help.
It doesn't have to be tag - any method will allow me to publish and download release into my CI is OK.

thanks,
Vitaly

**Comment by amargautam** [comment]
I used - https://www.npmjs.com/package/package-version-git-tag
