### ISSUE TITLE
How to set directory paths

### ISSUE THREAD

**Issue by twigs67** [electron-userland/electron-builder#4672]
Hello all,

When I add a package (puppeteer in this case) to extraFiles, my app is unable to find it when packaged. It's trying to locate the package at ```\Users\AppData\Local\Programs\myApp\resources\app.asar\node_modules\puppeteer```, but this isn't even a valid file path.

Is there a way to add the path to the system paths, so that it can find it? 

I see that there is an option to add ```to``` and ```from``` using the files option, but the other directory options (extraResources & extraFiles) don't seem to have this option. 

Any help would be appreciated.

**Comment by kzimny** [comment]
extraResources have from .. to ... option https://www.electron.build/configuration/contents.html#extraresources
Then you can access those files at runtime as follow:
```
import * as path from 'path';
const x = process.platform === 'win32' ?
            './test.db' :
            path.join(path.dirname(process.execPath), '/../../../test.db');
```
