### ISSUE TITLE
Error opening file for writing in win 10

### ISSUE THREAD

**Issue by joeyer** [electron-userland/electron-builder#4677]
electron: 4.2.2
electron-builder: 21.0.15
An error occurred during the installation process

![image](https://user-images.githubusercontent.com/11498128/74522894-10c02b80-4f57-11ea-9bb1-5a346e345570.png)

system：
![image](https://user-images.githubusercontent.com/11498128/74523051-5da40200-4f57-11ea-83d7-efaca51c99d4.png)

**Comment by BusinessDuck** [comment]
Looks same as mine https://github.com/electron-userland/electron-builder/issues/4678
Is it update process or clean installation?

**Comment by joeyer** [comment]
@BusinessDuck clean installation

**Comment by BusinessDuck** [comment]
That works for me:
1) use `deleteAppDataOnUninstall`: true, in nsis config.
2) Allow change installation directory to user by `allowToChangeInstallationDirectory`
