### ISSUE TITLE
Is it possible to run a secondary installer?

### ISSUE THREAD

**Issue by andrew-mclachlan** [electron-userland/electron-builder#4679]
Hi !

I am bundling an .exe that requires the Visual Studio redistributable to be installed. Is it possible to run that installer during the installation of my Electron App? And if so, how would I go about setting that up?

Thanks in advance!

**Comment by andrew-mclachlan** [comment]
I think I've answered my own question:
I need an nsis nsh script entry similar to:
```
macro customInstall
  ExecWait '"$INSTDIR\resources\DPInst.exe" /sw'
!macroend
```

**Comment by Superlokkus** [comment]
Can somebody enlighten my if the need to install the VC++ redist for native modules oneself, changed over the time? I have the feeling in electron 4 or 3 it was installed by the installer by default. I am confused by the different closed tickets in electron, electron-packager and electron-builder. Even more about the intended behavior in the future. Still thx @andrew-mclachlan

**Comment by andrew-mclachlan** [comment]
I believe that this issue can be closed.

**Comment by andrew-mclachlan** [comment]
For future generations...
```
!macro preInit
  SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
  SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
!macroend

!macro customInstall
  
  ReadRegStr $1 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{BC958BD2-5DAC-3862-BB1A-C1BE0790438D}" "DisplayVersion"
  StrCmp $1 "14.0.23026" installed

;not installed, so run the installer
  File /oname=$PLUGINSDIR\vc_redist.x64.exe "${BUILD_RESOURCES_DIR}\..\extras\vc_redist.x64.exe"
  ExecWait '"$PLUGINSDIR\vc_redist.x64.exe" /passive /norestart'

installed:
;we are done

!macroend
```

**Comment by Minami-Kotori** [comment]
> For future generations...
> 
> ```
> !macro preInit
>   SetRegView 64
>   WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
>   WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
>   SetRegView 32
>   WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
>   WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\My Product"
> !macroend
> 
> !macro customInstall
>   SetRegView 64
> 
>   ReadRegStr $1 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{BC958BD2-5DAC-3862-BB1A-C1BE0790438D}" "DisplayVersion"
>   StrCmp $1 "14.0.23026" installed
> 
> ;not installed, so run the installer
>   File /oname=$PLUGINSDIR\vc_redist.x64.exe "${BUILD_RESOURCES_DIR}\..\extras\vc_redist.x64.exe"
>   ExecWait '"$PLUGINSDIR\vc_redist.x64.exe" /passive /norestart'
> 
> installed:
> ;we are done
> 
> !macroend
> ```

Hi Andrew

I came accross the same issue, how ever when I added the custom NSIS script I wasn't able to make an installer with yarn dist. May I ask how do you configure the builder? Thanks.

**Comment by andrew-mclachlan** [comment]
Hi there - what is the error that you're encountering? I didn't do anything special for the installer. I specified the install script and built with electron-builder as per the docs. Which platform are you building for? I can post a snippet.

**Comment by Minami-Kotori** [comment]
> Hi there - what is the error that you're encountering? I didn't do anything special for the installer. I specified the install script and built with electron-builder as per the docs. Which platform are you building for? I can post a snippet.

Hi Andres

I'm building for Windows.  

`  "build": {
    "directories": {
      "buildResources": "build/release"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "script": "build/installer.nsi"
    },
    "win": {
      "icon": "lib/img/logo.ico"
    }
  }`

and the NSIS script is as follows:
`!macro customInstall
  File /oname=$PLUGINSDIR\vc_redist.x64.exe "${BUILD_RESOURCES_DIR}\..\msvc\vc_redist.x64.exe"
  ExecWait '"$PLUGINSDIR\vc_redist.x64.exe" /passive /norestart'
!macroend`

When ever electron-builder gets to the custom script part it stops and give me error 1.
Any ideas would be appreciated thank you.
