### ISSUE TITLE
4.2.1 Doesn't Include `.node` Files

### ISSUE THREAD

**Issue by shockone** [electron-userland/electron-builder#468]
I have a native dependency (https://github.com/chjj/pty.js/), which used to work in applications packaged by 4.2.0.

Currently the file `build/Release/pty.node` isn't included in the bundle. I'm not sure it's about it being `.node`, but I suspect that's the case because [there were some changes to globbing](https://github.com/electron-userland/electron-builder/commit/a7b2932981efbf32058d5bba615f46a1e7e0cbeb)

You can reproduce it by cloning https://github.com/shockone/black-screen and executing `npm run pack`. If you change the version in `package.json` to 4.2.1, the build will be broken.

**Comment by develar** [comment]
Fix will be published in 15 minutes.

**Comment by develar** [comment]
TODO: We must get rid of regexp ignore rules and use glob.

**Comment by shockone** [comment]
You're very responsive @develar, thank you.
