### ISSUE TITLE
Can I disable differential download?

### ISSUE THREAD

**Issue by gschattenhofer** [electron-userland/electron-builder#4682]
* **electron-builder**: 21.2.0

* **electron-updater**: 4.2.0

* **Target**:  NSIS

I want to disable differential download on NSIS using electron-updater, so it always fallback to full download. Is there a way to do it?

**Comment by akorchev** [comment]
I recently wanted to do the same. Checked the [implementation](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L37) and it seems there isn't currently a way to disable differential downloads. In my case I am still using the Nuts server for downloads and it doesn't support either blockmap files or HTTP ranges. 

Your best bet would be to fork electron-updater.

**Comment by gschattenhofer** [comment]
@akorchev Thanks for the suggestion. I would leave the fork solution as a last resource, don't want to deal with the maintenance and extra tests for it.

I'm currently considering deleting the blockmap after the publish and add a handler to the exception thrown. Any thoughts on that or warns are more than welcome.

**Comment by aabuhijleh** [comment]
I'm also interested in disabling this default behavior. I think this should be relatively simple to add as a property. @develar wdyt?

```js
autoUpdater.differentialDownload = false
```

By setting this to false, electron-updater should automatically fallback to a full download and not try to download blockmaps or throw exceptions.

**Comment by aabuhijleh** [comment]
If you look at the electron-builder [configuration documentation](https://www.electron.build/configuration/nsis) you can find this option `differentialPackage`. If you set that to false, a blockmap file will no longer be generated. However, electron-updater will still try to download the blockmap and if it fails, it falls back to a full download.

so this option

```js
autoUpdater.differentialDownload = false
```

is still needed to prevent unnecessary download attempts.

**Comment by gschattenhofer** [comment]
`differentialPackage ` works only on NSIS WEB targets per the documentation.

**Comment by aabuhijleh** [comment]
If I don't add `differentialPackage` to NSIS target, I still get `.blockmap` files generated.

**Comment by Vaggal** [comment]
@gschattenhofer 
> `differentialPackage ` works only on NSIS WEB targets per the documentation.

I think this is not correct.

Per the documentation 

> `differentialPackage` Boolean - Defaults to true for web installer (nsis-web)

It just defaults to true for web installer. It doesn't mean that it only works on it. In my experience if you set it false, it will full download the package.

**Comment by kylegundersen** [comment]
![remove-differential-installer](https://user-images.githubusercontent.com/10299789/112722994-6bf27a80-8eda-11eb-9645-b53d5ad9b891.JPG)
It was easy enough to remove just comment out the two lines above, hopefully, this helps someone. BTW the differential updater makes the app lock up badly so this is a must-do for the quality of life for your users. Good luck, and happy coding! 

Also if someone wants to take the time to variable this conditional that would be great ;).

**Comment by indutny-signal** [comment]
Hey! Just curious, what was the reason you wanted to disable differential updates? Are they are worse in some ways?

**Comment by appurist** [comment]
@indutny-signal  In my case it was because it was a government project with a strict update procedure so there were no downloads at all and it looked like this feature added considerably to the build process (whether that is true or not I don't know). So I wanted to disable them to see the difference, and because they weren't being used anyway.

**Comment by kylegundersen** [comment]
@indutny-signal  In my case it was the fact that if the differential downloader fails, which for me it did every time. The biggest problem is when it was checking if the differential could be applied. It froze my application's main process for a couple minutes which is unacceptable for end-users.

**Comment by indutny-signal** [comment]
@kylegundersen oh no, thanks for sharing!
