### ISSUE TITLE
Error: Cannot find module 'source-map-support/source-map-support.js'

### ISSUE THREAD

**Issue by jfhbrook** [electron-userland/electron-builder#4685]
I'm using electron-builder 22.3.2. I haven't configured electron-updater. I'm using electron-webpack 2.7.4. My whole app is [here](https://github.com/jfhbrook/ihydra). This build is for Windows 10.

electron-builder seems to be able to do the build just fine, but when I try to run my app it throws an error about source map support:

![image](https://user-images.githubusercontent.com/57536/74873891-01adf480-532e-11ea-9c51-f8a4d2bff919.png)

I tried explicitly installing source-map-support (0.5.16) and that didn't really help.

Thanks!

**Comment by jfhbrook** [comment]
I'm not working on this project right now, but the issue hasn't gone away either. I could reproduce it at any time. It's probably a real bug at worst and a documentation issue at best.

**Comment by labriola** [comment]
It is still an issue

**Comment by labriola** [comment]
@jfhbrook since you mention it might just be a documentation issue at best, does that imply there is a work around by some type of configuration?

**Comment by jfhbrook** [comment]
I'm not aware of one - I just decided not to build an exe for my hack project.

**Comment by labriola** [comment]
Thanks

**Comment by labriola** [comment]
For anyone who finds this thread. 

The specific problem is that source-map-support is listed as a devDependency in your package.json.... so while its attempting to be used at runtime with a lot of default electron/webpack configs which include sourcemaps, it's not included in the asar

**Comment by appurist** [comment]
I ran into this today and it is certainly blocking, on a high-visibility security-related project. If anyone has any clues about how to avoid this error, I'd appreciate it. I've tried adding the dependency to my project myself, but dev and prod dependencies, no luck. I don't know where the reference is coming from.

**Comment by appurist** [comment]
Correction: adding source-map-support as a production dependency _does_ avoids the issue.

This should be documented somewhere, not only as a _dependency_, but as a _production_ dependency.
(If it is, I haven't found it in hours of Google searches.)

I have found my index.html in my app.asar file there is a direct call to require there:
```
<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
      <script>require("source-map-support/source-map-support.js").install()</script></head>
      <body>
        <div id="app"></div>
      <script src="renderer.js"></script></body>
    </html>
```

So now as a full prod dependency, the unpacked folder's `resources\app.asar` file does have source-map-support in that archived `app.asar`, under the archived `node_modules` subfolder.

**Comment by appurist** [comment]
@labriola It seems it **must** be included in your `package.json` (as a full production dependency).

**Comment by labriola** [comment]
Correct. Sorry my post wasn't clearer and I didn't see this sooner or I would have saved you some time

**Comment by lazarljubenovic** [comment]
This is an error even if there's no `source-map-support` listed in my `package.json` at all. Why would I need this for a production build?

**Comment by Hadatko** [comment]
> This is an error even if there's no `source-map-support` listed in my `package.json` at all. Why would I need this for a production build?

Same
