### ISSUE TITLE
DigitalOcean Spaces, useMultipleRangeRequest is not respected

### ISSUE THREAD

**Issue by makitsune** [electron-userland/electron-builder#4686]
Using version 22.3.2, my electron build config includes:

```json
"publish": [
	{
		"provider": "spaces",
		"region": "nyc3",
		"name": "...",
		"path": "...",
		"useMultipleRangeRequest": false
	}
]
```

However when I try to update, I get an error that says 
`Error: Content-Type "multipart/byteranges" is expected, but got "application/octet-stream"`

Which is why I added `"useMultipleRageRequest": false` but that doesn't change anything. I get the error regardless.

So instead I tried to use the config:

```json
"publish": [
	{
		"provider": "generic",
		"url": "https://nyc3.digitaloceanspaces.com/name/path",
		"useMultipleRangeRequest": false
	}
]
```

And it worked fine! However it won't publish if I use generic.

For now I've written a script that will publish for me, but I would like to use electron builder instead.

**Comment by wartab** [comment]
Probably because you did not spell Range correctly.

**Comment by makitsune** [comment]
> Probably because you did not spell Range correctly.

Ah whoops that's just a typo here on the issue. Thanks for noticing. It was spelled correctly in my testing so the issue can stay open

**Comment by makitsune** [comment]
I tried everything again just now and here's my test scenario.

In my `electron-builder.json` file, I have:
```js
"publish": {
	"provider": "spaces",
	"region": "nyc3",
	"name": "...",
	"path": "_releases",
	"useMultipleRangeRequest": false
}
```

Whilst version `1.0.0` in package.json, I ran `electron-builder --config electron-builder.json --publish`. It successfully packaged and uploaded to /_releases with a proper 7z, exe and latest.yml file.

Whilst version `0.0.0`, I ran `electron-builder --config electron-builder.json`. I copied everything from `dist/nsis-web` onto a usb drive and switched to a seperate machine.

I installed version `0.0.0` which used the local 7z file next to the exe file and everything worked fine. Then I opened my program using cmd and it found an update for version `1.0.0` and continued to auto update. Eventually this appears:

```
Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/octet-stream"
    at ClientRequest.<anonymous> (C:\Program Files\Tivoli Cloud VR\resources\app\node_modules\electron-updater\out\differentialDownloader\multipleRangeDownloader.js:124:14)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
```

If I do the same using:

```js
"publish": {
	"provider": "generic",
	"url": "https://nyc3.digitaloceanspaces.com/.../_releases",
	"useMultipleRangeRequest": false
}
```

Manually uploading the 3 files to spaces, then `useMultipleRangeRequest` is respected and everything works perfectly.

**Comment by makitsune** [comment]
https://github.com/electron-userland/electron-builder/blob/c01b7c0b55d3466b826ea9cc9a11ad34118801c1/packages/electron-updater/src/providerFactory.ts#L40

It should automatically disable when using spaces but it doesn't for me
