### ISSUE TITLE
Can I customize CFBundleDisplayName for the Renderer helper?

### ISSUE THREAD

**Issue by aguynamedben** [electron-userland/electron-builder#4691]
* **Version**: 22.3.2
* **Target**: macOS, Electron 7

Hi, first off, we love electron-builder and we will donate $100 after submitting this issue. Thank you for the time you spend working on this project, it makes our lives a lot easier.

My app is suffering an unfortunate real-world side effect rooted in the renderer process name changing `MyApp Helper` to `MyApp Helper (Renderer)` in Chromium/Electron 6. More on our specific problem [here](https://github.com/atom/node-keytar/issues/250), but the summary is:
* Then, from an Electron 5 renderer process, my app set macOS keychain values using keytar
* Now, from an Electron 7 renderer process, my app gets macOS keychain values using keytar, but macOS now prompts the user for a password for every keytar.get of a key.

I believe this is because the renderer name changed. Or possible the renderer bundle ID changing.

Can I specify `CFBundleDisplayName` (and similar values) for my renderer helper .plist file? I've had success defining a custom value for `CFBundleDisplayName` using `extendInfo`, but that value is for the main process. Is there something to akin to `extendInfo` to alter the name of the renderer helper?

In the code it looks like this is somewhere around [here](https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/src/electron/electronMac.ts#L58), but I'm not sure the plist values for **helpers** can be extended via the electron-builder API.

What I want to do is customize `CFBundleDisplayName` back to `MyApp Helper` to see if macOS will hopefully not freak out and ask for passwords to access keychain values it created from Electron 5 renderers. It seems like macOS makes its decisions based on either `CFBundleDisplayName`, `CFBundleExecutable`, `CFBundleIdentifier`, or `CFBundleName`, but I'm not sure, so it'd be nice to play with all of those.

Thanks again for the excellent work you do on this project.

**Comment by aguynamedben** [comment]
I'm not sure, but it looks like a similar issue may have happened before with the history of Electron, and the solution could have been to add the option `helperBundleId`. https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/src/electron/electronMac.ts#L88

I wonder if the right way to expose this post Electron 6 is `helperRendererBundleId`. I'll play with adding that option to see if it solve my specific problem.

**Comment by develar** [comment]
Are you sure that `MyApp Helper` id is not used by some another existing helper?

**Comment by aguynamedben** [comment]
I've been modding electron-builder and playing with this. macOS cared about bundleId. The problem is with the Electron 6 changes in electron-builder, bundleId for the renderer processes has changed. My app implicitly depended on the renderer bundle ID NOT changing, because keytar/macOS are sensitive to bundleId when requesting values out of macOS' keychain.

I submitted as WIP PR. I'll look at it more tomorrow, I think I can clean it up and propose a clean and flexible way to have:
* modern default bundle names for new users
* let long-time users maintain their bundleIds however they want in electron-builder config
