### ISSUE TITLE
Full example where you can build Mac and Windows files

### ISSUE THREAD

**Issue by LittleHamster** [electron-userland/electron-builder#4700]
I have been reading the docs for hours and cannot figure out how can I create a Windows file when I am on mac. 

I cloned this file `https://github.com/electron-userland/electron-webpack-quick-start` but when I run `yarn dist` it only gives me mac app. 

Is there a complete installation or full example where I can produce installable windows file?

**Comment by benjaffe** [comment]
I'm in the same boat as you, and it's all very confusing.

I'm building in a VM, but am running into issues with native dependencies not getting recompiled. In any case, if it helps, check out the bottom of this page. https://www.electron.build/multi-platform-build
