### ISSUE TITLE
config file is missing after building exe

### ISSUE THREAD

**Issue by DamithaPerera** [electron-userland/electron-builder#4703]
I have installed config (https://www.npmjs.com/package/config) for my electron project. when i use npm start project is working fine. but when i build exe (**electron-builder .** ) , after installing when i open it it not working. In developer tools it shoes **"No configurations found in configuration directory:C:\Users\hp\AppData\Local\Programs\test\config"**

![error](https://user-images.githubusercontent.com/11298536/75223407-66ed6400-57cc-11ea-9537-a24f83be48c4.jpg)

**Comment by kzimny** [comment]
Post your electron-builder configuration part from package.json

**Comment by DamithaPerera** [comment]
@kzimny  ![image](https://user-images.githubusercontent.com/11298536/75338637-0f76f300-58b5-11ea-8f0b-7f26c105bf37.png)

**Comment by kzimny** [comment]
1. change the appId to `org.mywebsite` 
2. the [name ](https://docs.npmjs.com/files/package.json#name
) property in your package.json mus not contain special characters

**Comment by DamithaPerera** [comment]
@kzimny  when i use this https://github.com/dw1284/electron-node-config it worked.
