### ISSUE TITLE
build linux deb APP can not produce latest.yml file

### ISSUE THREAD

**Issue by leejaygo** [electron-userland/electron-builder#4704]
"electron-builder": "21.2.0",
"electron-updater": "4.2.0"

build for deb app

some piece code in electron-builder.json 
"linux": {
    "icon": "img/",
    {
      "target": "deb",
      "arch": ["x64"]
    }],
    "category": "System",
    "publish": [
      {
        "provider":"generic",
        "url":"http://xxx.xxx.xxx.xx:1053/linux/",
        "channel": "latest"
      }
    ]
  }
i can create deb app, but it can not create latest.yml file, so i can not update app. so which produce this problem, the config problem of  other problem?

ps：when target is AppImage, it can create latest.yml. but change target to deb can not create latest.yml。in my project, i just need to build deb app。Recently, i read the source code and find the solution on the internet, it seem like, when build deb app, it can not create latest.yml，so what should i do to config or other methods?

**Comment by kzimny** [comment]
As explained in [documentation ](https://www.electron.build/auto-update.html#auto-updatable-targets) the target on Linux should be set to `AppImage`. Did you already try to build with this option? I'm not familiar with Linux, I only read the note in the documentation. The latest.yml should be generated then.

**Comment by Sednaoui** [comment]
In my case, I have my Linux target as AppImage, and it is still not generating neither `latest-linux.yml` nor `app-update.yml`. I am using a plain HTTP server. I tried to follow a workaround by adding a publish options specified for the build target (Linux) based on one of the [comments](https://github.com/electron-userland/electron-builder/issues/2736#issuecomment-456380922), but it did not work for me. 

I am using electron-builder: 20.39.0

https://github.com/electron-userland/electron-builder/issues/2736

**Comment by kzimny** [comment]
did you try to add the publish options with channel?
```
        "publish": {
            "provider": "generic",
            "url": "https://www.mywebsite.com/software/${os}",
            "channel": "latest-xyz"
        },
```

**Comment by Sednaoui** [comment]
I did. I still have the same error message on my console: 

`"Error: Error: Cannot find channel "latest-linux.yml" update info: HttpError: 404 Not Found"`

**Comment by leejaygo** [comment]
> As explained in [documentation ](https://www.electron.build/auto-update.html#auto-updatable-targets) the target on Linux should be set to `AppImage`. Did you already try to build with this option? I'm not familiar with Linux, I only read the note in the documentation. The latest.yml should be generated then.

**Comment by leejaygo** [comment]
ps：when target is AppImage, it can create latest.yml. but change target to deb can not create latest.yml。in my project, i just need to build deb app。Recently, i read the source code and find the solution on the internet, it seem like, when build deb app, it can not create latest.yml，so what should i do to config or other methods?

**Comment by Sednaoui** [comment]
@leejaygo does it create the `app-update.yml` file in your resources file for AppImage linux?

**Comment by kzimny** [comment]
why in ressources folder? .yml is created in output directory defined in the build section of packege.json file.
```
        "directories": {
            "output": "build"
        },
```

**Comment by Sednaoui** [comment]
I meant the resources folder in each target OS: linux-unpacked, win-unpacked, mac. In both mac and win-unpacked, I have a resource folder with app-update.yml inside, but not linux-unpacked. 

I still don't know why it is not generated automatically. For now, I added a script that copies app-update.yml from win and add it to linux since it is the same file

**Comment by IanMDay** [comment]
Having the same issue. AppImage is created, there is no `dist/latest.yml` nor a `dist/linux-unpacked/resources/app-update.yml`. Works fine for Windows and mac.

**Comment by starhu521** [comment]
> ps：when target is AppImage, it can create latest.yml. but change target to deb can not create latest.yml。in my project, i just need to build deb app。Recently, i read the source code and find the solution on the internet, it seem like, when build deb app, it can not create latest.yml，so what should i do to config or other methods?

hello, I have the same problem. It can't generate yml when set the target is deb for linux. In addition, I can't download when I set the target is AppImage. I got this error: https://github.com/electron-userland/electron-builder/issues/5678#issue-822701841

And I don't have any problems when target is nsis for windows.

**Comment by mmaietta** [comment]
I was under the impression that the publish latest.yml was only generated for supported targets:
> Auto-updatable Targets
macOS: DMG.
Linux: AppImage.
Windows: NSIS.

https://www.electron.build/auto-update

**Comment by starhu521** [comment]
> I was under the impression that the publish latest.yml was only generated for supported targets:
> 
> > Auto-updatable Targets
> > macOS: DMG.
> > Linux: AppImage.
> > Windows: NSIS.
> 
> https://www.electron.build/auto-update

Maybe, I just think those targets are default when I read the doc. Thanks.

**Comment by kroko** [comment]
Actually having `app-update.yml` in non AppImage targets would be helpful nonetheless.

Auto-update still looks for it under `resources/app-update.yml` if `.checkForUpdates()` is called in non AppImage cases (say, `deb`).

Currently it would fail of course with
```txt
checkForUpdates Error {"errno":-2,"code":"ENOENT","syscall":"open","path":"/opt/my-app-name/resources/app-update.yml"}
```

If such file existed `deb` user could still utilise `.checkForUpdates()` and on `'update-available` receive message - _'hey, update available, i just cannot auto update - you have to do it by yourself'_ 

Of course, some extra steps are needed on non AppImage, that is - never try to actually download and install, just notify
```
    // if GNU and not AppImage do not auto update, but try informing user that updates available when 'update-available' arrives
    if (platformIsNixlike() && !process.env.APPIMAGE) {
      autoUpdater.autoDownload = false;
      autoUpdater.autoInstallOnAppQuit = false;
      this.#manualUpdateFeedback = true;
    }
```

**Comment by aymengraoui** [comment]
any news about this issue ? :(
