### ISSUE TITLE
What is app-update.yml

### ISSUE THREAD

**Issue by boredstiff** [electron-userland/electron-builder#4708]
* **Version**: 22.3.2

* **electron-updater**: 4.2.2

* **Target**: MacOS

> 14:45:58.832 › Error: Error: ENOENT: no such file or directory, open '/Users/blah/MyApp.app/Contents/Resources/app-update.yml'
> (node:6333) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/blah/MyApp.app/Contents/Resources/app-update.yml'

I'm trying to find information about what this file is, and what information is needed to generate it for a build. I've looked in the docs and googled around a lot but nothing has come up, and I've tried looking through the issues, but nothing seems to answer my question - what do I need to do to make this file show up in the build? I don't even need updating in this application that I'm building, so disabling it would be a good solution as well. 

Thank you.

Edit: Found the appUpdater method and commented it out. Still curious about what stuff is needed for the file.

**Comment by kzimny** [comment]
Would this answer help? https://github.com/electron-userland/electron-builder/issues/4599#issuecomment-575885067

**Comment by boredstiff** [comment]
Yeah, thanks, that's filling in some of the blanks. Where would the target be updated? I used [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) so it may be obfuscating the configuration needs for electron-builder. The package.json lists these as the steps:

```
    "package": "yarn build && electron-builder build --publish never",
    "package-all": "yarn build && electron-builder build -ml",
    "package-ci": "yarn postinstall && yarn build && electron-builder --publish never",
    "package-linux": "yarn build && electron-builder build --linux",
    "package-mac": "yarn build && electron-builder build --mac",
    "postinstall": "node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll",
```

But I don't see anything about configuring electron-builder.

**Comment by kzimny** [comment]
Add the minimal build configuration section to your package.json:
```
    "build": {
        "appId": "com.my.website",
        "productName": "MyProduct",
        "afterSign": "crv/config/afterSignHook.js",
        "directories": {
            "output": "build"
        },
        "publish": {
            "provider": "generic",
            "url": "https://www.yourServer.com/software/${os}",
            "channel": "latest"
        },
        "mac": {
            "icon": "crv/assets/icons/icon.icns",
            "hardenedRuntime": true,
            "gatekeeperAssess": false
        }
    },
```
You can check the configuration settings [here](https://www.electron.build/configuration/configuration)

**Comment by boredstiff** [comment]
Awesome, thank you very much for this.
