### ISSUE TITLE
Not allowed to load local resource: ...../project/resources/app.asar/dist/angular-electron/index.html

### ISSUE THREAD

**Issue by ajithgadgeon14** [electron-userland/electron-builder#4709]
electron-builder
* **Version**: 22.3.2 
electron
* **Version**: 7.1.10
 
cant load generated index.html inside dist folder

code used
  win.loadURL(url.format({
    pathname: path.join(__dirname, './dist/angular-electron/index.html'),
    protocol: 'file:',
    slashes: true,
    icon: __dirname + '/Icon/Icon.icns'
  }));

also tried
  win.loadURL(url.format({
    pathname: path.join(__dirname, './resources/app.asar/dist/angular-electron/index.html'),
    protocol: 'file:',
    slashes: true,
    icon: __dirname + '/Icon/Icon.icns'
  }));

**Comment by kzimny** [comment]
Try the following:
```
    win.loadURL(
        url.format(
            {
                pathname: path.join(__dirname, './index.html'),
                protocol: 'file:',
                slashes: true
            }
        )
    );
```
