### ISSUE TITLE
electron-builder not signing .pkg. Application .app is signed properly.

### ISSUE THREAD

**Issue by andrew-mclachlan** [electron-userland/electron-builder#4710]
"electron-builder": "^22.3.2" ... (22.3.2)
macOS

electron-builder is not signing my .pkg. Application .app is signed properly.

```
electron-builder  version=22.3.2 os=18.7.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • rebuilding native dependencies  dependencies=... platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=8.0.1 appOutDir=Artifacts/mac
  • signing         file=Artifacts/mac/My App.app identityName=Developer ID Application: X-Y-Z (BLAHBLAH) identityHash=XXXXXXXXXXXXXXXXXXX provisioningProfile=none
  • building        target=pkg arch=x64 file=Artifacts/My App-0.1.0-osx.pkg
```

Signing was working fine earlier so is there now an additional step or configuration option?

**Comment by andrew-mclachlan** [comment]
So this issue boils down to needing to notarize the .pkg too.

**Comment by shardik95** [comment]
Hey, running into same issue. Only dmg and zip is working, but .pkg doesn't work. How did you notarize .pkg?

**Comment by andrew-mclachlan** [comment]
Hi @shardik95 -
I’m not distributing the App via the App Store so I build the install and then sign it separately with my own signing cert. using productsign.

**Comment by freddy-daniel** [comment]
pkg skip sign and notarization process. Is there any update on this issue?

**Comment by grahamtallen** [comment]
Any updates?

**Comment by marckohlbrugge** [comment]
I'm running into this same issue. For Mac App Store (MAS) it builds an `.app` and `.pkg`. The `.app` gets signed properly (verifiable with `codesign -d -vvv app-name.app`), but the `.pkg` installer that needs to be uploaded to App Store Connect does **not** get signed. (`code object is not signed at all` via `codesign`).

I've been unable to get my MAS builds accepted. A fix would be very welcome, because as it stands MAS builds seem broken.

**Comment by marckohlbrugge** [comment]
@andrew-mclachlan would you mind re-opening this issue as multiple people still seem to have this problem

**Comment by andrew-mclachlan** [comment]
Will try :-)

I too am facing this issue continuously. It's still not clear to me how to get the pkg properly setup like the .app which is properly notarized.

**Comment by andrew-mclachlan** [comment]
@marckohlbrugge I don't seem to be able to re-open the issue.

**Comment by Durgaprasad-Budhwani** [comment]
@marckohlbrugge - facing the same issue, any help will be much appreciated.

**Comment by Simonmg** [comment]
i have thesame issue, some update about this?

**Comment by marckohlbrugge** [comment]
I've been unable to resolve this. I even got into touch with an Apple engineer about it, but they weren't able to help either. Of course they support only goes so far when it comes to Electron apps.

**Comment by Bug-Reaper** [comment]
Ahhh a new year and same old sign/notarization problems. I think my pkg installer even had worked at one point 🤷 (Mighta been .dmg, don't remember). Anyways the .app is signed/notarized but the pkg installer isn't even signed

```
  spctl -a -t exec -vvvv maApp.pkg
  myApp.pkg: rejected
  source=no usable signature
```

Might take a stab at sign the pkg installer seperately but I'd assume this should just work out of the box. Gatekeeper on non dev computers gives you the whole rigamarole about can't identify this developer blah blah blah.

-------

No idea why this thread is closed, is this a won't fix situation?

**Comment by rohan-a99** [comment]
was this issue fixed, can i sign my .pkg file as well.

**Comment by andrew-mclachlan** [comment]
Hi @Bug-Reaper and @rohan-a99 -

I believe this may be a "won't fix situation". Signing the pkg separately is the likely course here.

**Comment by dingshaohua-com** [comment]
+1

**Comment by dingshaohua-com** [comment]
If uploading to the Apple Store does not require a signature, it does not matter whether pkg can sign or not
