### ISSUE TITLE
NSIS fails to autoUpdate when launched from app - exe rename necessary?

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#4711]
Relevant package.json versions:

```
"electron": "^8.0.0",
"electron-builder": "^22.3.2"
"electron-updater": "^4.2.0"
```

NSIS build seutp:
```
"nsis": {
  "oneClick": false,
  "allowToChangeInstallationDirectory": true,
  "perMachine": false
}
```

I'm having trouble with the NSIS build while doing autoUpdates.  I'm experiencing the following behavior:
1. The installer gets downloaded successfully through the app (full download) - OK
2. App quits and launches the installer - OK
3. NSIS installer successfully detects an existing build and tries to install there - OK
4. For whatever reason, it fails to update and crashes (terminates?) mid install. - Error

I don't know how to provide more information for step 4: there doesn't seem to be a log available anywhere, and I don't get an error message at any point. The only thing I can note is that successful updates happen with the progress bar "restarting" 2 times (reverting back in progress), while unsuccessful ones seem to freeze during the 1st time and then stop (crash?) without going to the last page.

What seems to work every time is if I manually download the new executable and **rename** it. I was renaming these files in order to keep some sort of record of various versions. If I run the renamed version (in this case `Chobby-1.36.0.exe`) it will successfully update. If I run it as `Chobby.exe` it will fail - same like the autoUpdater version. 
So my conclusion is that for whatever reason the updater executable *file name* must be different than `App.exe`

**Comment by gajop** [comment]
Following up on this, here's a very simple repository that will fail to update: https://github.com/gajop/electron-builder-example

Steps to reproduce:
1. Build with `npm run build-win` and install (either system or single user)
2. Change `version` in https://github.com/gajop/electron-builder-example/blob/master/package.json#L3 to `1.0.1` and build again.
3. Try installing (the installer will crash).

I found two different workarounds:
1) Do not specify an `artifactName` (https://github.com/gajop/electron-builder-example/blob/master/package.json#L12). This will generate an installer with a slightly different name which allows it to update.
2) Use `oneClick` installer: OneClick installers don't seem to suffer from this problem.

Still searching for a more satisfactory solution.

**Comment by robmro27** [comment]
I was able to reproduce this different way. 2 use cases:

1)
- download manually some version ie. 1.3.9 filename: TEST
- install
- download manually bumped version  1.3.10 filename: TEST (1) <- added by Windows
- install
WORKS - app reinstall and runs 

2)
- download manually some version ie. 1.3.9 filename: TEST
- install
- remove old file from downloads folder
- download manually bumped version  1.3.10 filename: TEST <- nothing changes this time in filename
- install
NOT WORKS - app reinstall (steps showing) but not run after it finish installing (checkbox run after checked) and after manually launch it shows version 1.3.9 still

**Comment by gajop** [comment]
bump

**Comment by gajop** [comment]
Still relevant and still affecting a lot of our users...
Is there anything I can do to help? @develar can you give me a hint where to look at? I'm willing to help get this fixed in any way I can.

**Comment by gajop** [comment]
bumping yet again ¯\_(ツ)_/¯

**Comment by gajop** [comment]
bumping yet again ¯_(ツ)_/¯

**Comment by ejwilburn** [comment]
Seeing the same issue with the guided installer, see my comments here: https://github.com/electron-userland/electron-builder/issues/5573#issuecomment-796838174
