### ISSUE TITLE
How to debug & log NSIS?

### ISSUE THREAD

**Issue by gajop** [electron-userland/electron-builder#4712]
Followup on https://github.com/electron-userland/electron-builder/issues/4711 that I think deserves its own issue.

Is there any way to figure out what went wrong with NSIS installs, updates, uninstalls? Having no ability to log or get any error messages makes it difficult to rely on it in production - getting user log info is hard as it is. Am I missing something or is there just no way to detect errors with it?

I'm using the following setup although I don't think it's relevant to any particular version:

package.json versions:

"electron": "^8.0.0",
"electron-builder": "^22.3.2"
"electron-updater": "^4.2.0"

NSIS build seutp:

"nsis": {
  "oneClick": false,
  "allowToChangeInstallationDirectory": true,
  "perMachine": false
}

**Comment by gajop** [comment]
Still relevant, please don't close

**Comment by gajop** [comment]
reopen please... still very important

**Comment by LukeXF** [comment]
Any update on this?
