### ISSUE TITLE
Can't auto publish snap application into snap store

### ISSUE THREAD

**Issue by JoSe086** [electron-userland/electron-builder#4716]
Hi,

I'm trying to build and publish my .snap app into the snap store with electron builder, but the documentation referred to this is incomplete.

The section Snap Store of the documentation (https://www.electron.build/configuration/publish) only specifies the "channel", but the provider and other information is missing (other sections like github or s3 are documented).

The documentation says too: "Snap target by default publishes to snap store (the app store for Linux). To force publishing to another providers, explicitly specify publish configuration for snap.", but this is false, because passing the publish parameter to the npm run command does nothing.

How is it supposed that a .snap is uploaded automatically to the snap store passing the publish parameter to the npm run command?

On the other hand, I specify too the application category, but is ignored and setted to "Utility" automatically (linux category is set to default utility, reason: linux.category is not set and cannot map from macOS). Why electron-builder is ignoring the category? Here is my package.json referred to the snap configuration:

"linux":{
    "target": [
      "snap"
    ],
    "category": "Office"
  },
  "snap":{
    "grade": "stable",
    "confinement": "strict"
  },

Thanks.

**Comment by zxdong262** [comment]
When set 
```
  "snap": {
    "publish": ["github", "snap"]
  }
``` 
will get error: `Error: Cannot find module '/home/travis/build/[secure]/[secure]/build/electron-publisher-snap.js'`
