### ISSUE TITLE
how to seperate build and publish?

### ISSUE THREAD

**Issue by rancheng123** [electron-userland/electron-builder#4718]
I expect:
first  I want to build my app,
 and then embed some other code into the app,
finally to publish the app to S3.

But the fact is:
build my app and publish to S3.  I have no chance to embed other code into the app before it is published to S3

**Comment by hgouveia** [comment]
for this you need to use `--dir` this will create a electron app , then you can use the `--prepackage` to create an installer with that content, something like:

```
  "scripts": {
    "package": "electron-builder -w --dir --x64",
    "publish": "electron-builder --prepackaged ./build/win-unpacked --publish always",
  },
```
