### ISSUE TITLE
Icon directory doesnt contain icons

### ISSUE THREAD

**Issue by luk3skyw4lker** [electron-userland/electron-builder#4721]
* **22.3.2**: 

* **None**

* **Windows**: 

When I try to execute electron-builder, it returns me an error that the icon directory doesnt contain the icons, even if the directory is specified on package.json.

`"win": {
    "icon": "./icons/win/app.ico",
    "target": [
      "portable"
    ]
  },
  "linux": {
    "icon": "./icons/png",
    "target": [
      "AppImage"
    ]
  },
  "mac": {
    "icon": "./icons/mac",
    "target": [
      "dmg"
    ]
  }`

And the icon directory looks like:
![image](https://user-images.githubusercontent.com/48929501/75554251-b9bb5b80-5a18-11ea-931a-262cf9a4cf55.png)

**Comment by luk3skyw4lker** [comment]
I've already solved this issue, my build config was missing some parameters and I've had written it in a wrong way.

**Comment by themota17** [comment]
> I've already solved this issue, my build config was missing some parameters and I've had written it in a wrong way.

sorry for my English, how did you solve this problem?
