### ISSUE TITLE
signDlls ignored for asar.unpacked

### ISSUE THREAD

**Issue by fonsleenaars** [electron-userland/electron-builder#4728]
* **Version**: 22.3.2

* **Target**: Windows 10

The `signDlls` option (https://www.electron.build/configuration/win) for Windows seems to not be used for the `asar.unpacked` files.

If I'm looking at the code correctly in `winPackager.ts` it's because of this block:

```js
protected async signApp(packContext: AfterPackContext, isAsar: boolean): Promise<any> {
    const exeFileName = `${this.appInfo.productFilename}.exe`
    if (this.platformSpecificBuildOptions.signAndEditExecutable === false) {
      return
    }

    await BluebirdPromise.map(readdir(packContext.appOutDir), (file: string): any => {
      if (file === exeFileName) {
        return this.signAndEditResources(path.join(packContext.appOutDir, exeFileName), packContext.arch, packContext.outDir, path.basename(exeFileName, ".exe"), this.platformSpecificBuildOptions.requestedExecutionLevel)
      }
      else if (file.endsWith(".exe") || (this.isSignDlls() && file.endsWith(".dll"))) {
        return this.sign(path.join(packContext.appOutDir, file))
      }
      return null
    })

    if (!isAsar) {
      return
    }

    const outResourcesDir = path.join(packContext.appOutDir, "resources", "app.asar.unpacked")
    // noinspection JSUnusedLocalSymbols
    const fileToSign = await walk(outResourcesDir, (file, stat) => stat.isDirectory() || file.endsWith(".exe") || file.endsWith(".dll"))
    await BluebirdPromise.map(fileToSign, file => this.sign(file), {concurrency: 4})
  }
```

The second to last line there isn't using the `this.isSignDlls()` check that is being used for the other resources.

Is this intended behavior? I have a setup where `sharp` is included in the `asar.unpacked` result, which leads to all of its `dlls` being signed, which I'm trying to avoid.

Thanks for all the hard work!

**Comment by fonsleenaars** [comment]
This is still relevant, I'm fine pushing a PR for it. I'm still looking for confirmation of whether or not it's intended behavior or just an oversight.

**Comment by adriendurepaire** [comment]
Any update on this issue?
