### ISSUE TITLE
Change auto-created build folder to a different name

### ISSUE THREAD

**Issue by yonHolmes** [electron-userland/electron-builder#4732]
* **Version**: 22.2.0

* **Target**: "win": { "target": "nsis" }

Hello,

I have a working Electron and React integrated App which builds fine both in a 'spin-up' and as a full build into a 'setup.exe' file.
- spin-up: "npm run build && npm run electron ."
- setup.exe: "npm run electron-builder -c.extraMetadata.main=build/electron.js"

What I want to do is instead of electron/builder creating a 'build' folder during spin-up and setup.exe, to create files to a differently named folder e.g. 'electronBuild' as we want to use the 'build' folder for a different process separate but involving the code we've developed.

All questions welcome, hopefully I've been detailed enough.

**Comment by kzimny** [comment]
Are you looking for this option?
```
    "build": {
        "appId": "org.test.myapp",
        "productName": "test",
        "directories": {
            "output": "MyOwnFolderName"
        },
}
```
