### ISSUE TITLE
does this tool support signing the installer with pfx file?

### ISSUE THREAD

**Issue by wangxiexe** [electron-userland/electron-builder#474]
previously when using 

    "electron-winstaller": "^2.1.0",

I can specify these two properties and sign the installer

  certificateFile: __dirname + '/certs/xxx.pfx',
  certificatePassword:'xxxaa',

but with electron-builder, it seems not support sign with pfx file any more, it mentions:

CSC_LINK	The HTTPS link (or base64-encoded data) to certificate (*.p12 file).

just double confirm can I find some way to still use the pfx file for signing ? thx.

**Comment by develar** [comment]
Duplicate #449 Fix will be in 15 minutes.

**Comment by develar** [comment]
> just double confirm can I find some way to still use the pfx file for signing ? thx.

On CI server you should use `CSC_LINK`. On development machine you can use `CSC_LINK` as well.

To simplify migration and to solve problem that Windows doesn't have keychain , `certificateFile` and `certificatePassword ` are fully supported. Specify it in the `build.win`.

**Comment by wangxiexe** [comment]
ok ,seems pfx and p12 files are same.
