### ISSUE TITLE
appimage autoupdate - duplicate tray icons

### ISSUE THREAD

**Issue by tzarebczan** [electron-userland/electron-builder#4740]
Noticed this comment on Tulip recently and we are running into the same problem:

```Starting today, electron-updater doesn’t seem to be completely killing the old version… after I run quitAndInstall(true, true), the old version runs its quit handlers (closes http listener) and starts up the new version, but there’s 2 tray icons. The old tray icon is unresponsive, but the process still shows up with ps. (linux AppImage, ubuntu 18.04, electron-builder 20.14.7)```

So you start the autoupgrade, you see the app shutdown, background processes close, it starts back up, but 2 tray icons are visible.  This happens all various distros, and both if appimage is run normally or from command line. 

This is in the logs during the auto update:
```
[22:45:50.186] [info] Install on explicit quitAndInstall
[22:45:50.186] [info] Install: isSilent: false, isForceRunAfter: true
[22:45:50.890] [info] Update installer has already been triggered. Quitting application.

```
![2020-03-05_22-41-50](https://user-images.githubusercontent.com/8120721/76048049-9e79b000-5f32-11ea-91ad-0f1ae848ab0b.gif)

I've tried with the latest builder (0.22.4) and updater (4.2.4) and seeing the same. Once it a while it will close the app completely, but then doesn't start back up. Seems to happen rarely.

Our setup: 
https://github.com/lbryio/lbry-desktop/blob/v0.43.3-rc.2/electron-builder.json
https://github.com/lbryio/lbry-desktop/blob/v0.43.3-rc.2/package.json

Sent a donation, thanks!

**Comment by develar** [comment]
But it worked previously correctly?

**Comment by tzarebczan** [comment]
Nope, didn't work on 0.20 builder either. Same behavior.

**Comment by tzarebczan** [comment]
Yes, still is!
