### ISSUE TITLE
Getting Error while uploading electron app to mac store

### ISSUE THREAD

**Issue by sunilv1611** [electron-userland/electron-builder#4742]
i am getting this error to upload the .pkg file to mac store using transporter app
Error:-  Invalid provisioning profile. The provisioning profile included in the bundle is invalid

![Screen Shot 2020-03-06 at 4 27 08 PM](https://user-images.githubusercontent.com/37995577/76079410-98cfa900-5fca-11ea-9cf1-e0aaead053ad.png)

Following are the details: -
"electron": "^6.1.4",
"electron-builder": "^22.0.0",

package.json:-

"build": {
"productName": "Fantom Wallet",
"appId": "********** appId********",
"mac": {
"category": "public.app-category.productivity",
"target": [
"pkg",
"dmg",
"zip",
"mas"
],
"provisioningProfile": "embedded.provisionprofile",
"entitlements": "build/entitlements.mac.plist",
"type": "distribution",
"icon": "build/icon.icns"
},
"mas": {
"type": "distribution",
"category": "public.app-category.productivity",
"entitlements": "build/entitlements.mas.plist",
"icon": "build/icon.icns"
},
"directories": {
"buildResources": "build",
"output": "dist"
},
"files": [
"build/static",
"build",
{
"from": "build/static",
"to": "static"
}
],
"extraResources": [
{
"from": "build/static",
"to": "static"
}
]
}

Kindly provide the steps to upload the app on iTunes or is there any update in packages please give me the solutions.
 
Thank you..

**Comment by Mmagnan1** [comment]
I have the same problem.
