### ISSUE TITLE
Fallback to CSC_KEY_PASSWORD if certificatePassword not given 4.2.4

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#475]
I noticed you just fixed code signing issue [#449](https://github.com/electron-userland/electron-builder/issues/449) with 4.2.4 release. Great and Thanks !

However, the new build requires `certificatePassword ` in package.json.

I prefer to set `CSC_KEY_PASSWORD` env variable, as I'm uneasy leaving my plaintext password in package.json. I want to use command line only (i.e. no programmatic API). This has worked fine in the past, only regressed with 4.2.4.

Can you please provide a CSC_KEY_PASSWORD fallback if certificatePassword is not present  ?

Thanks a million!

**Comment by develar** [comment]
@dharders Why not use `CSC_LINK` ? Because `CSC_LINK` doesn't support file path?

**Comment by dharders** [comment]
Last time I tried to use CSC_LINK I converted the pfx to base64 and tried to set the  CSC_LINK env variable from the command line but it was too large. Windows has a 1024 or 2048 char limit for env variable, which was too short for my encoded cert. 

Am I able to use a LOCAL (ie not remote https) file with CSC_LINK from command line without diving into the API?

**Comment by develar** [comment]
> Am I able to use a LOCAL (ie not remote https) file with CSC_LINK from command line without diving into the API?

Not yet supported.

**Comment by dharders** [comment]
In 4.2.3 using certificateFile in package.json and CSC_KEY_PASSWORD env variable worked fine for me (ie no certificatePassword specified in package.json). 

If you're planning on supporting CSC_LINK with local files then I'll just wait. 

Otherwise, is it possible to return the fallback behaviour of 4.2.3 easily ? (eg password = certificatePassword || CSC_KEY_PASSWORD)

**Comment by dharders** [comment]
@develar Found a simple fix!

Change [winPackager.ts#L29](https://github.com/electron-userland/electron-builder/blob/master/src/winPackager.ts#L29):

```
const certificatePassword = this.customBuildOptions.certificatePassword;
```

to:

```
const certificatePassword = this.customBuildOptions.certificatePassword || this.getCscPassword();
```
