### ISSUE TITLE
the latest version of electron-updater  package on yarn and npm rollback to 2.2.4?

### ISSUE THREAD

**Issue by KillingJacky** [electron-userland/electron-builder#4755]
* **Version**: 

* **Target**: 

I'm installing the electron-updater package through yarn, but I found out that the version yarn installed is 2.2.4, which is pretty old. So does npm. Is this desired?

**Comment by Danw33** [comment]
I'm also seeing this today whilst running `yarn upgrade-interactive`:

```
 dependencies
   name                  range   from       to      url
   electron-updater      latest  4.2.2   ❯  2.2.4   https://github.com/electron-userland/electron-builder
```
Supposedly wanting to "upgrade" from `4.2.2` to `2.2.4` 🤔

It appears this may be a mistake when the latest release was published, as the registry shows the following:

```json
"dist-tags": {
    "latest": "2.2.4",
    "next": "4.2.4"
},
```
