### ISSUE TITLE
Error: libcurl.so.4: version `CURL_OPENSSL_3' not found when running the builder in docker builder:wine

### ISSUE THREAD

**Issue by robinlu0705** [electron-userland/electron-builder#4756]
* **Version 22.3.2**: 

* **NSIS**: 

I am running the builder in the docker container `electronuserland/builder:wine`. The build process failed at the code signing phase:
```
/builder/home/.cache/electron-builder/winCodeSign/winCodeSign-2.5.0/linux/osslsigncode: 
/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found 
(required by /builder/home/.cache/electron-builder/winCodeSign/winCodeSign-2.5.0/linux/osslsigncode)
```

If I switch back to an old docker image digest (`electronuserland/builder@sha256:b50e44a98ffe9f716b2f66c51b7898404670c8b74c8c3fc2b152c53f8af60513`), then it builds successfully.

The regular Code Signing Certificate was used (not EV certificate) and `CSC_KEY_PASSWORD` and `CSC_LINK` were set in the environment variables.

**Comment by develar** [comment]
Already fixed in 22.4.0.
