### ISSUE TITLE
Error while doing a fresh install of electron-builder

### ISSUE THREAD

**Issue by ahgan84** [electron-userland/electron-builder#476]
Guys, I encounter below error message while trying to do a fresh install:

`C:\Work\Project2016\vct>npm i electron-builder --save-dev
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN No compatible version found: appdmg@^0.4.5
npm WARN Valid install targets:
npm WARN 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.10, 0.3.9, 0.3.8, 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm WARN
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "electron-builder" "--save-dev"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.5

npm ERR! No compatible version found: signcode-tf@~0.7.3
npm ERR! Valid install targets:
npm ERR! 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\Project2016\myq-vct\npm-debug.log

Any idea what went wrong?

**Comment by develar** [comment]
https://www.npmjs.com/package/signcode-tf "0.7.3 is the latest of 9 releases" Something is wrong on your side. Try to remove `node_modules` and install again. Or use nodejs 6.

**Comment by ahgan84** [comment]
I installed electron-prebuilt first before I try install electron-builder. Does this the caused?

**Comment by ahgan84** [comment]
Same error. I removed node_modules folder and install again but give me same error.

**Comment by develar** [comment]
Clean Travis blog is successful. Please try `npm cache clean`
