### ISSUE TITLE
AutoUpdate for AppImage

### ISSUE THREAD

**Issue by gillisig** [electron-userland/electron-builder#4761]
* Version 22.3.2: 
* Electron version: 5.0.13
* Target: Linux
* Built using Quasar and electron-builder

I've been trying to get autoUpdate to work for AppImage on linux. The app runs fine but doesn't auto uppdate, Mac and Windows auto updates just fine. 

The logs give me the following error:

´´´[warn] APPIMAGE env is not defined, current application is not an AppImage´´´

However it certainly is AppImage. Any ideas on how to fix the issue? 

Thanks!

**Comment by gillisig** [comment]
Still relevant. No idea how to fix.

**Comment by gillisig** [comment]
Yep, still haven't been able to fix this and my linux users need to manually update each time.

**Comment by okdistribute** [comment]
I also have this issue.

**Comment by gillisig** [comment]
Yes still relevant. I don't know the root cause, otherwise I would tackle fixing it myself.

**Comment by gillisig** [comment]
Yes..

**Comment by gillisig** [comment]
This stale bot is so pointless.

**Comment by mmaietta** [comment]
A quick github search for the error gave 1 result
https://github.com/electron-userland/electron-builder/search?q=%22current+application+is+not+an+AppImage%22&type=code

Best guess is that you need to configure the process env correctly.
https://github.com/electron-userland/electron-builder/blob/a879ba7f02ea704084b9672d6b9c9a47b7e5c27d/packages/electron-updater/src/AppImageUpdater.ts#L18-L21
