### ISSUE TITLE
App won't start after unzipping on Mac Catalina

### ISSUE THREAD

**Issue by HorinVova** [electron-userland/electron-builder#4762]
* **Version**: 22.4.0

* **Target**: Mac  / Zip

### **Description:**
After building an electron app for macOS with Zip target, it won't open after unzipping it by default Archive Utility app on Catalina.

### **Steps to reproduce:**
1. Build an electron app with the next build config:
![build_config](https://user-images.githubusercontent.com/26885882/76320185-f9bbf180-62e8-11ea-89a8-56f1f715f03b.png)
```
"build": {
    "mac": {
      "target": "zip",
      "icon": "./images/electron-icon-mac.icns",
      "category": "Development",
      "identity": null,
      "sign": false
    }
}
```

2. Run build command `electron-builder -m --x64`.

3. Unzip created zip on Mac (Catalina 10.15) using Archive Utility app.
![unzip](https://user-images.githubusercontent.com/26885882/76320490-70f18580-62e9-11ea-8181-7b2e8761b767.png)

4. Try to open the unzipped `.app` file.

### **Actual result:**
Can't open `.app` file.
<img width="555" alt="open_issue" src="https://user-images.githubusercontent.com/26885882/76320736-c2017980-62e9-11ea-82de-c702c1acd397.png">

### **Notes:**

1. If unzip app with any other archiver as Better Zip or The Unarchiver, the app file works. But most MacOS users use the default Archive Utility app, so this is a major issue.

2. As I have noticed the problem occurs because of bad symlinks for Electron Framework, Libraries, and Resources in `my_electron_app.app/Contents/Frameworks/Electron Framework.framework`

Not working version:
![bad_sym-links](https://user-images.githubusercontent.com/26885882/76327867-3856a980-62f3-11ea-9593-f85afea7bcc1.png)

Working version:
![good_sym-links](https://user-images.githubusercontent.com/26885882/76327907-45739880-62f3-11ea-80e1-240bec7da53b.png)

3. Also, I tried to remove **line 65** in my `node_modules/app-builder-lib` here: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/ArchiveTarget.ts#L65
```
if (this.isWriteUpdateInfo && format === "zip") {
    // updateInfo = await (0, _differentialUpdateInfoBuilder().appendBlockmap)(artifactPath);
}
```
After I removed that line and built the app (zip), the symlinks were created correctly and the app started successfully.

**Comment by shrinidhi111** [comment]
Not sure if this is related, but in my case I had to notarize the app (using electron-notarize) to make it working in Catalina

**Comment by quanglam2807** [comment]
@shrinidhi111 This bug is not related to notarization and only affect zip target. I'll see if I fix this.

**Comment by quanglam2807** [comment]
This bug is caused by this https://github.com/develar/app-builder/issues/24

**Comment by gerbus** [comment]
@kjg this is the only workaround so far: https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-557316888

**Comment by busticated** [comment]
lol c'mon stalebot read the room 😂 ❤️

**Comment by adam-lynch** [comment]
Yep

**Comment by adam-lynch** [comment]
Yes

**Comment by alectrocute** [comment]
Still relevant.
