### ISSUE TITLE
Manually setting already downloaded electron zip file ?

### ISSUE THREAD

**Issue by GKSONG** [electron-userland/electron-builder#4766]
o. Environment
    -- electron : 8.1.1
    -- electron-builder : 21.2.0
    -- target : windows 10  (win x64)

o. Question :
    The github site is blocked and cannot be downloaded.
     Is there any way to manually specify and execute an electron zip file?

o. Error Message :
> electron-builder --win --x64 --dir
  • electron-builder  version=21.2.0 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=8.1.1 appOutDir=dist\win-unpacked
  ⨯ Get https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip: dial tcp: lookup github.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1

**Comment by GKSONG** [comment]
It partially works based on other closed issues and document.
But nsis-resources issue isn't works

**Comment by GKSONG** [comment]
Under "AppData/Local/electron-builder/cache/nsis", nsis_*** and  nsis_resource_** should be exist.

**Comment by orange-beans** [comment]
> Under "AppData/Local/electron-builder/cache/nsis", nsis_*** and nsis_resource_** should be exist.

Have you solved the issue yet my friend? Can you share your solution please?
