### ISSUE TITLE
The error "request timed out" appears. What's the reason?

### ISSUE THREAD

**Issue by wslp12** [electron-userland/electron-builder#4767]
* **Version**: 22.4.0

* **Target**: nsis

Auto Update works fine. The problem is the phrase "request timed out" during the update. In this case, I am directly modifying httpExecutor.js in node_modules. Is there any other way?

build conf
`"build": {
        "directories": {
            "output": "dist_${version}"
        },
        "mac": {
            "publish": {
                "target": [
                    "zip",
                    "dmg"
                ],
                "provider": "generic",
                "url": "http://ip/update/${env.ENV_PLATFORM}"
            }
        },
        "win": {
            "publish": {
                "target": "nsis",
                "provider": "generic",
                "url": "http://ip/update/${env.ENV_PLATFORM}"
            }
        }
    },`

script conf
` "scripts": {
        "start_electron": "electron .",
        "build_mac_dmg": "electron-builder --mac=dmg ",
        "build_mac": "ENV_PLATFORM=darwin electron-builder --mac",
        "build_win": "ENV_PLATFORM=win32 electron-builder --win"
    },`

![wetv-minor-logs-02](https://user-images.githubusercontent.com/26638889/76398959-25aaa600-63c1-11ea-911e-9b58af121b2d.png)

**Comment by pverscha** [comment]
@wslp12 Duplicate of #4744

**Comment by wslp12** [comment]
@pverscha Thank you very much. This saved me a lot of time.
