### ISSUE TITLE
allow changing electron-updater download (cache) directory

### ISSUE THREAD

**Issue by aabuhijleh** [electron-userland/electron-builder#4769]
* **Version**: 22.4.0

* **electron-updater version**: 4.2.4

* **Target**:  Windows NSIS

**Use Case**

Some IT environments don't allow apps to execute files from some locations like `%localappdata%`

To workaround this issue, I'm using a fork of `electron-updater` and editing the `getAppCacheDir` function

I think it would be nice to add this as an option

for example:

```js
autoUpdater.cacheDir = A_SUITABLE_CACHE_LOCATION
```

Thanks!

**Comment by aabuhijleh** [comment]
This issue is still relevant. Not being able to change the download location of updates is blocking for some environments. I believe that the maintainer can hopefully integrate this change without much difficulty.

**Comment by harshitsilly** [comment]
https://github.com/imjsElectron/electron-differential-updater - check this pace we are working on

**Comment by AiHaibara** [comment]
the system user folder
C:/Windows/system32/config/systemprofile/AppData/Local/{xxxx}pending/ 
can't running the installer for updater
anyone can helpful this?
