### ISSUE TITLE
auto update faile Internal error, size mismatch, newSize undefined 

### ISSUE THREAD

**Issue by wslp12** [electron-userland/electron-builder#4772]
* **Version**: 22.4.0

* **updater-Version**:  4.2.2

* **Target**: nsis

error img
![image](https://user-images.githubusercontent.com/26638889/76511530-a687a180-6496-11ea-91f9-0f55f5cd13bf.png)

![image](https://user-images.githubusercontent.com/26638889/76511792-f8c8c280-6496-11ea-8ccc-dd6f6a36693f.png)

The information in the second screenshot is a log output directly from the module.

The size sent from the server is received, but the size does not appear to be used.

![image](https://user-images.githubusercontent.com/26638889/76512117-84425380-6497-11ea-82d9-7bf87cdc3d2c.png)

forcibly create info like line 127 in the screenshot above, it works.

But since I am modifying the module, I want a different way.

**Comment by wslp12** [comment]
solve,

**Comment by Zhell1** [comment]
having the same error, how did you solve this ?

**Comment by lmsccc** [comment]
> solve, 解决，

I would like to know how you solved this problem? Thanks
