### ISSUE TITLE
Signed and notarised .pkg installer doesn't unpack the signed and notarised .app into /Applications

### ISSUE THREAD

**Issue by glenveegee** [electron-userland/electron-builder#4773]
* **Version**:  electron-builder  version=22.4.0 os=18.7.0 

* **Target**: pkg

I've managed to sign and notarise my electron app with electron-builder.

The resulting installer `.pkg file` is neither signed correctly, nor notarised

Even after I manually sign, notarise and staple the notarisation to the `.pkg` file, the installer runs and reports "Successfully installed" but doesn't unpack the `XXXX.app` into `/Applications`. 

The only way I am able to install the app correctly is to run 

`sudo installer -verboseR  -pkg ./path/to/installer/XXXX.pkg -target /`

**Comment by pashvin** [comment]
I noticed the same issue sometimes but in my case this only happen when installer sometimes skips second screen(Destination select). But if second screen is skipped and if I select "change install location" on third screen and comeback to 2nd screen and make selection and then finish installer, then application is always installed.

Can you check you are also running into the same case?

**Comment by glenveegee** [comment]
Unfortunately that has no effect for me and doesn't fix the underlying issue.

**Comment by glenveegee** [comment]
Worked it out I think. We had an old version of the app lying around with a version (major.minor.patch) that was greater than the new version I was trying to install. As soon as I bumped the new apps version to something greater it installed fine.
