### ISSUE TITLE
[Bug] Auto updater has error with NSIS target: Windows 7 or above is required. 

### ISSUE THREAD

**Issue by lanistor** [electron-userland/electron-builder#4774]
* **Version**: 
  - electron-builder : ~22.4.1  
  - electron-updater : ~4.2.5

* **Target**: NSIS

I here this bug is fixed, but not for me in NSIS.
Auto updater is using 'electron-updater', it runs good in other windows version except windows 7.

In my case, when ready to install new version(after downloaded), main process will send a message to renderer progress to notify user, after user had make sure to quit and install, i call `quitAndInstall()`. Then error occurs in windows 7: 'Windows 7 or above is required';

I had change parameter `perMachine` to `false` (`true` failed either), and tested both choices while installing (current user or all users), both failed.

Here is my configuration:

```js
win: {
    icon: 'static/icons/icon.ico',
    requestedExecutionLevel: 'asInvoker',
    signingHashAlgorithms: [ 'sha256', 'sha1' ],
    certificateFile: 'scripts/cer/flicker_windows.pfx',
    publisherName: 'xxx',
    verifyUpdateCodeSignature: false,
    artifactName: 'xxx',
  },
  nsis: {
    include: 'scripts/nsis/installer.nsh',
    shortcutName: 'xxx',
    uninstallDisplayName: 'xxx',
    allowToChangeInstallationDirectory: true,
    createStartMenuShortcut: true,
    createDesktopShortcut: true,
    oneClick: false,
    perMachine: false,
  },
```
***scripts/nsis/installer.nsh***
```
!include WinVer.nsh

!macro customInstall
${If} ${AtMostWin7}
  WriteRegStr HKCU "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$INSTDIR\${PRODUCT_NAME}.exe" "VISTARTM"
${EndIf}
!macroend
```

**Comment by vifird** [comment]
@Agent77326 Thanks, but i tried and it cannot fix this error.

**Comment by cooderzeng** [comment]
I had the same problem at windows7 when I set the compatibility to Vista.

But if I not set ,it will show a black screen. 🥺🥺

Version:
	electron-builder : 21.2.0
	electron-updater : 4.2.0

**Comment by jackple** [comment]
Is there any solution?

**Comment by Larry-Arun** [comment]
Is there any solution? please tell me, tks.

**Comment by Larry-Arun** [comment]
I found that it can be updated normally when I install it on the C drive, and this error occurs when it is installed on the D drive.

**Comment by ffdfgdfg** [comment]
Need a `disable-gpu` flag to force CPU render, so I add a detection like this:
``` javascript
if (os.release().startsWith('6.1')) {
  app.disableHardwareAcceleration()
}
```
Don't need to set compatibility anymore, so auto updater works.
electron-updater: 4.3.4
electron: 9.2.0
electron-builder: 22.8.0
