### ISSUE TITLE
How to customize MAS pkg installer?

### ISSUE THREAD

**Issue by gtamas** [electron-userland/electron-builder#4775]
Version: 21.2.0: 

Target: MAS 

The MAS build creates an app and a PKG installer. However, I don't see any options for customizing the PKG. I mean none the options I would normally use for PKG target seem to be applicable here. I cannot specify welcome text, conclusion text, background etc.

Is there any way to use these? The PKG installer the build generates seems to be just a default one. I can't even specify the license text..

Thanks in advance!

**Comment by Vishal1419** [comment]
This is still relevant, I also cannot find any documentation.
Just commenting for re-opening the issue.
