### ISSUE TITLE
Problem with using functions inside custom script

### ISSUE THREAD

**Issue by Iskander7d** [electron-userland/electron-builder#4777]
* **Version**: 20.38.5
* **Target**: Windows

I'm trying create custom page of uninstaller with feedback form. I read documentation (https://www.electron.build/configuration/nsis#NsisOptions-script) and made all stuff with macros customUnInstall.
I found some issues with same problem, but it unresolved (#1122, #3871). The problem is using functions. 

An error is returned when attempting to build: "warning 6020: Uninstaller script code found but WriteUninstaller never used - no uninstaller will be created. Error: warning treated as error"

There is the code of script, that I insert in customUnInstall script with !insertmacro:

```
Function un.TestFunc
	MessageBox MB_OK "HELLO"
FunctionEnd
!macro testmacro
        Var /GLOBAL Dialog
        Var /GLOBAL CheckBox

	nsDialogs::Create 1018
	Pop $Dialog

	${NSD_CreateCheckbox} 0 25u 100% 10u "&Checkbox 1"
	Pop $CheckBox
	${NSD_OnClick} $CheckBox un.TestFunc

        nsDialogs::Show
!macroend
```
So, what i'm doing wrong? I would be very grateful if you could help me.

**Comment by bogdibota** [comment]
i managed to get this working by wrapping the function as described here https://github.com/electron-userland/electron-builder/issues/1122#issuecomment-272841143

```
!ifndef BUILD_UNINSTALLER
    Function TestFunc
	MessageBox MB_OK "HELLO"
    FunctionEnd
!endif

!macro testmacro
        Call TestFunc
!macroend
```

**Comment by aprilandjan** [comment]
@bogdibota I've got no luck trying your code , the builder process just failed. I dont know if this is supported or not 😭
