### ISSUE TITLE
Not able to download 7z file for NSIS WEB target

### ISSUE THREAD

**Issue by aditi-dev** [electron-userland/electron-builder#4778]
* **Version**: 
electron-builder : 22.4.1
electron: 8.1.1
* **Target**:  win -> nsis-web

Not able to run exe after publishing prerelease to Github private repo through electron-builder.
Below is my configuration
```
{
   ...
    "publish": [
        {
            "provider": "github",
            "private": true,
            "owner": "...",
            "repo": "...",
            "token": "...",
            "releaseType": "prerelease"
        }
    ],
    "asar": true,
    "win": {
        "target": [
            {
                "target": "nsis-web",
                "arch": [
                    "x64"
                ]
            }
        ],
        "icon": "Logo.ico"
    },
    "nsisWeb": {
        "artifactName": "${productName}-Setup-${version}.${ext}",
        "oneClick": true,
        "perMachine": false,
        "allowToChangeInstallationDirectory": false,
        "runAfterFinish": true,
        "deleteAppDataOnUninstall": true,
        "differentialPackage": true,
        "installerHeaderIcon": "Logo.ico",
        "installerIcon": "Logo.ico",
        "uninstallerIcon": "Logo.ico"
    }
}
```

When I build exe through `electron-builder public --win --publish always` , I am able to see below files in Github release 
```
- app-name-v0.0.1-beta.1-x64.nsis.7z
- AppName-Setup-0.0.1-beta.1.exe
- latest.yml
```
But when I download exe file and install it, received below error :
```
Unable to download application package from https://github.com/<MyID>/<RepoName>/releases/download/v0.0.1-beta.1/app-name-v0.0.1-beta.1-x64.nsis.7z (status: File Not Found (404)).
Please check you Internet connection and retry.
```

I have verified the unpacked resource folder contains proper Github configuration with token detail.
I also tried with adding environment variable GH_TOKEN on my windows machine. But still face the same issue.

I would appreciate any help in finding the issue.

PS - The same configuration is working with NSIS target.

**Comment by cwg999** [comment]
I am also trying to solve why this happens. Getting closer with [this stackoverflow question](https://stackoverflow.com/questions/20396329/how-to-download-github-release-from-private-repo-using-command-line) ...

**Comment by cwg999** [comment]
If we look at `computeDownloadUrl` in `PublishManager.ts` we see

```javascript 
baseUrl = `${githubUrl(gh)}/${gh.owner}/${gh.repo}/releases/download/${gh.vPrefixedTagName === false ? "" : "v"}${packager.appInfo.version}

${baseUrl}/${encodeURI(fileName)}
```
