### ISSUE TITLE
Instead of building the app, it just runs the app.

### ISSUE THREAD

**Issue by dragonmenorka** [electron-userland/electron-builder#4779]
* **Version**: 
22.4.1

Not using it yet.

* **Target**: 
Windows32

When I enter the build command (build) in the cmd it justignores it and does "npm start" (my command to run the application)
My package is this one:
. . .
  "main": "main.js",
  "scripts": {
    "pack": "build --dir",
    "dist": "build",
    "start": "electron main.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "JS Tech",
  "license": "MIT",
  "dependencies": {
    "electron": "^8.1.1",
    "mysql": "^2.18.1"
  },
  "devDependencies": {
    "electron-builder": "^22.4.1"
  },
  "build": {
    "appId": "com.myFirstApp.jstech",
    "win": {
      "target": "NSIS",
      "icon": "build/icon.ico"
    }
  }
}

**Comment by kzimny** [comment]
The command to build is: ``electron-builder .``. Add a script entry to your package.json and build the app as follow: ``npm run myprodbuild`` or ``yarn run myprodbuild``

```
  "scripts": {
    "myprodbuild": "electron-builder ."
  },
```

**Comment by dragonmenorka** [comment]
Thanks! i just did it and it worked for me
