### ISSUE TITLE
Both certificateSubjectName and certificateSha1 required for EV Signing Certificate

### ISSUE THREAD

**Issue by JamieRuderman** [electron-userland/electron-builder#4780]
* electron-builder: **v22.2.0**: 
* Target: **win**: 
* Platform: **Windows 10**

Documentation on https://www.electron.build/code-signing states:

> If you are using an EV Certificate, you need to provide win.certificateSubjectName in your electron-builder configuration.

Would be good to add that [win.certificateSha1](https://www.electron.build/configuration/win#WindowsConfiguration-certificateSha1) is also required, or make it not required.

https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts line 120
If either is missing it will Throw an error.

Hope to save someone else some hours... Thank you!

**Comment by kzimny** [comment]
To sign an app only one option need to be set certificateSubjectName **OR** certificateSha1. You are using an old version of electron-builder. Update to the @latest version.

**Comment by EddieOne** [comment]
How to resolve this: Cannot find certificate EXAMPLE BLABLA, all certs:   stackTrace=

Building works fine without the certificateSubjectName. Using the latest Electron Builder. Same error using the sha1 hash.

**Comment by kzimny** [comment]
@EddieOne try with certificateSha1 instead with the certificateSubjectName

**Comment by EddieOne** [comment]
Same results. I ended up just leaving out the certificate. If I understand correctly the Windows store provides it's own certificate, so maybe it doesn't matter for appx files. Still trying to upload it to Microsoft.
