### ISSUE TITLE
Windows notifications being prefixed with "app.electron."

### ISSUE THREAD

**Issue by hosnar** [electron-userland/electron-builder#4783]
Hello,
is there a way to remove prefix on windows when getting notification from my electron app. Currently it is being prefixed as "app.electron.MyApp" in actions center. Is there a setting to change that to "MyApp" only, or a least custom prefix?

Thank you.

**Comment by aabuhijleh** [comment]
To change this prefix, you need to call `app.setAppUserModelId(YOUR_APP_ID)` before using notifications on Windows. [electron docs](https://www.electronjs.org/docs/tutorial/notifications#windows) & [electron-builder docs](https://www.electron.build/configuration/configuration#configuration)

**Comment by hosnar** [comment]
Thank you!
