### ISSUE TITLE
[Question]: Code Signing without PFX or P12 for Windows

### ISSUE THREAD

**Issue by kasvith** [electron-userland/electron-builder#4785]
* **Version**:  20.19.2

* **Target**:  windows

Hi, we are using [certum](https://certum.pl) for code signing(listed in [Microsoft Official Page]( https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate))

Certum gave us a certificate and it did not provide or produced a p12 or pfx file. We contacted them and they also informed us these files are not accessible.

So we manually code signed Setup with Signtool in Windows(as per instructions given by Certrum https://www.certum.eu/en/data/Instruction-of-activation-and-installation-of-Code-Signing-Certificate-EN.pdf)

For example, using the following commands
```bat
signtool sign /n "Company" /t http://time.certum.pl/ /fd sha1 /v installer-1.0.0.exe
signtool sign /n "Company" /fd sha256 /tr http://time.certum.pl/ /td sha256 /as /v installer-1.0.0.exe
signtool verify /pa  installer-1.0.0.exe
```

Company is the name of `Certificate Owner` from Windows Certificate Manager(certmgr.msc)
This works fine and it's signed as well after build

But after building and downloading it from the website, it shows the following error
![image](https://user-images.githubusercontent.com/13379595/76711089-f4203a80-6732-11ea-90bd-088d071f4bf8.png)

Is electron-builder supports code signing methods rather than only using pfx or p12? Using `Certificate Owner` field
(Our private keys are stored in a USB Stick provided by cetrum)

**Comment by pplonski** [comment]
@kasvith were you able to do code cigning with certum?

If you use signtool what about automatic updates, are they still working?

**Comment by kasvith** [comment]
@pplonski yes we were managed to do it by writing a custom code signing script.

`codesign.js`
```js
'use strict'

const util = require('util')
const exec = util.promisify(require('child_process').exec)
const chalk = require('chalk')

const OwnerName = process.env.CERT_OWNERNAME || `"Certificate Owner Name"`
const TimeStampServer = process.env.CERT_TIMESTAMPSERVER || 'http://time.certum.pl/'
const Verbose = (process.env.CERT_VERBOSE && process.env.CERT_VERBOSE === 'true') || false
const Debug = (process.env.CERT_DEBUG && process.env.CERT_DEBUG === 'true') || false
const Skip = (process.env.CERT_SKIP && process.env.CERT_SKIP === 'true') || false

async function doSign (file, hash, owner) {
  const sha256 = hash === 'sha256'
  const appendCert = sha256 ? '/as' : null
  const timestamp = sha256 ? '/tr' : '/t'
  const appendTd = sha256 ? '/td sha256' : null
  const debug = Debug ? '/debug' : null

  let args = [
    'signtool',
    'sign',
    debug,
    '/n',
    owner,
    '/a',
    appendCert,
    '/fd',
    hash,
    timestamp,
    TimeStampServer,
    appendTd,
    '/v',
    `"${file}"`
  ]

  try {
    const { stdout } = await exec(args.join(' '))
    if (Verbose) {
      console.log(stdout)
    }
  } catch (error) {
    throw error
  }
}

exports.default = async function (config) {
  if (!Skip) {
    console.info(`Signing ${chalk.green.bold(config.path)} with ${chalk.magenta(config.hash)} to ${chalk.cyan.bold(OwnerName)}`)
    await doSign(config.path, config.hash, OwnerName)
  }
}
```

Now in your `electron-builder` config

```json
"win": {
      ....
      "sign": "./codesign.js",
      ...
    },
```

**Comment by pplonski** [comment]
@kasvith thank you! Amazing! :)

**Comment by ramiel** [comment]
Hello. Were any of you able to integrate this in a CI system such us github actions?
