### ISSUE TITLE
diffientential update faile (nsis)

### ISSUE THREAD

**Issue by wslp12** [electron-userland/electron-builder#4789]
* **Version**:  22.4.0

* **Target**: nsis

> 21:52:12.161 > Full: 107,615.75 KB, To download: 1,618.13 KB (2%)
21:52:12.185 > Differential download: http://ip/download/flavor/default/0.5.3/windows_32/wetv_view_type_0.5.3.exe
21:52:12.202 > download range: bytes=52122-109656
21:52:43.169 > download range: bytes=164803-197570
21:53:10.060 > download range: bytes=9374713-10604222
21:53:39.684 > download range: bytes=18061519-18122813
21:54:08.963 > download range: bytes=103303124-103415289
21:54:38.574 > download range: bytes=109803412-109817215
21:55:07.576 > download range: bytes=110048648-110198532
21:55:37.400 > New version 0.5.3 has been downloaded to C:\Users\yunji\AppData\Local\wetv-view-type-updater\pending\wetv_view_type_0.5.3.exe
21:55:42.978 > Install on explicit quitAndInstall
21:55:43.008 > Install: isSilent: false, isForceRunAfter: true
21:55:44.663 > Cannot run installer: error code: UNKNOWN, error message: "spawn UNKNOWN", will be executed again using elevate if EACCES"
21:55:44.683 > Error: Error: spawn C:\workdir\duzone\wetvminor-electron\node_modules\electron\dist\resources\elevate.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
21:55:44.701 > Update installer has already been triggered. Quitting application.
Done in 225.38s.

The 0.5.2 version works fine once when the onClick attribute is false and the 0.5.3 works once when the onClick attribute is true, but the error above appears after that.

version: 0.5.3 
oneClick: false,
---------------------
version: 0.5.4
onClick: false
= error 

version: 0.5.3 
oneClick: false,
---------------------
version: 0.5.4
onClick: true
= work

**Comment by harshitsilly** [comment]
@wslp12  - Hi, try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/).. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.
