### ISSUE TITLE
Error: mas target — Identity name is specified, but no valid identity with this name in the keychain

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#479]
Hi,

I try to use electron builder to MAS deploiement
    "electron-builder": "4.2.6",
    "electron-prebuilt": "1.2.2",

```
"build": {
    "productName": "My App",
    "app-bundle-id": "com.myapp",
    "app-category-type": "public.app-category.productivity",
    "osx": {
      "title": "MyApp",
      "target": "mas",
      "identity": "Jeremie Chazelle"
    },
    "mas": {
      "entitlements": "./default_mas_entitlements",
      "entitlementsInherit": "./default_mas_inherit_entitlements"
    }
  }
```

But I have an error :

```
Error: Identity name "Jeremie Chazelle" is specified, but no valid identity with this name in the keychain
    at Function.<anonymous> (/Users/jeremiechazelle/Sites/my-app/node_modules/electron-builder/src/osxPackager.ts:79:15)
```

I checked my certificat, my private key is "Jeremie Chazelle"

**Comment by develar** [comment]
Please execute `security find-identity -v -p codesigning` — attach out.

**Comment by develar** [comment]
And if no other identities in your keychain, don't specify `identity`.

**Comment by develar** [comment]
And valid Apple cert should be in your keychain — import https://developer.apple.com/certificationauthority/AppleWWDRCA.cer

**Comment by jechazelle** [comment]
I have 3 identities : 

security find-identity -v -p codesigning

  1) 3A6771093C136BDKJDA26E13FB106E178681923E "3rd Party Mac Developer Application: Jeremie Chazelle (BEQXXXXXXX)"
  2) D7C6A770BO8EK269A5C9B228CD5FEB4E90E0305 "Developer ID Application: Jeremie Chazelle (BEQXXXXXXX)"
  3) 2D80736BMDL0Z9D5D92F501A5B0651DEA4A0AF99 "Mac Developer: Jeremie Chazelle (KLXXXXXXXXX)"
     3 valid identities found

**Comment by develar** [comment]
One identity and 3 certificates ;) please try to not specify identify.

**Comment by jechazelle** [comment]
Without identity, electron-builder wants CSC_NAME and CSC_LINK

**Comment by develar** [comment]
On CI server or development machine?

**Comment by jechazelle** [comment]
development machine

**Comment by develar** [comment]
Hmmm, works for me. Please set `DEBUG=electron-builder` env and provide console out.
