### ISSUE TITLE
MAS com.apple.security.app-sandbox in entitlements crashes the application

### ISSUE THREAD

**Issue by danutzcodrescu** [electron-userland/electron-builder#4790]
* **Version**: 22.4.1

* **Target**: mas

Sandbox entitlement is crashing the mas build on startup. The application works fine if I do not include `<key>com.apple.security.app-sandbox</key><true/>`, but it is refused by Mac Store. I tried using both mac and mas plist. 

I even tried a workaround proposed in [https://github.com/electron/electron-osx-sign/issues/192](this issue) to add to `node_modules/app-builder-lib/templates/entitlements.mac.plist` the sandbox entitlement. The app crashes.

Here is my build config:

```json
 "build": {
    "productName": "xxxxx",
    "appId": "com.xxx.xx",
    "artifactName": "${productName} Setup-${version}.${ext}",
    "mac": {
      "entitlementsInherit": "build/entitlements.mac.plist",
      "category": "public.app-category.business",
      "extraResources": [
        {
          "from": "./preconfigMac",
          "to": "preconfig",
          "filter": [
            "*.sh"
          ]
        }
      ]
    },
    "directories": {
      "output": "release"
    },
    "files": [
      "dist/",
      "package.json"
    ],
    "protocols": {
      "name": "Test protocol",
      "role": "Viewer",
      "schemes": [
        "test"
      ]
    },
    "mas": {
      "type": "distribution",
      "provisioningProfile": "embedded.provisionprofile",
      "entitlements": "build/entitlements.mas.plist",
      "entitlementsInherit": "build/entitlements.mas.inherit.plist"
    },
    "afterSign": "scripts/notarize.js"
  },
```

I identified the problem by checking the entitlements of the output. It seems that when I add sandbox entitlement it completely messes up the xml.

Here is the output of `codesign -d --entitlements :- Test.app` when entitlements do not include sandbox:
```xml
Executable=xxxxxx
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.cs.allow-jit</key>
  <true/>
  <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
  <true/>
  <key>com.apple.security.cs.disable-library-validation</key>
  <true/>
</dict>
</plist>
```
That is exactly the xml that I have in my entitlements.mas.plist.

However, when I add the sandbox entitlement to mas.plist or to mas.inherit.plist, this is the output:
```
Executable=xxxxx
bplist00?
                _ com.apple.application-identifier_#com.apple.developer.team-identifier_com.apple.security.app-sandbox_%com.apple.security.application-groups_com.apple.security.cs.allow-jit_6com.apple.security.cs.allow-unsigned-executable-memory_0com.apple.security.cs.disable-library-validation_xxxxxx	?       	       :`???7U`acdef%  
```

As you can see the entitlements are completely messed up because of the sandbox. Seems that there is some issue in how the entitlements are created during the build.

Any suggestions of what might be wrong?

**Comment by samuelmeuli** [comment]
Same issue here.

- `mac` build: `codesign -d --entitlements :- dist/mac/MyApp.app` displays the correct XML of `entitlements.mac.plist`
- `mas` build: `codesign -d --entitlements :- dist/mas/MyApp.app` displays a garbled version of `entitlements.mas.plist`

This causes app verification in Transporter to fail ("App sandbox not enabled").

**Comment by werber** [comment]
I have identical issue with identical setup. Also I can change entitlements to anything I want and all works except the case when I enable app-sandbox in entitlements. Tried building for mas-dev and mas with different provision profiles and certificates. Any updates on this?

**Comment by greenimpala** [comment]
Having the exact same issue here too. Add `com.apple.security.app-sandbox` and the built app will not launch.

**Comment by schetle** [comment]
The reason the entitlements gets "messed up" is because your entitlements are being regenerated with extra fields, and then binary encoded. This only occurs when com.apple.securirty.app-sandbox is supplied in your entitlements, and is caused by util-entitlements.js in electron-osx-sign.

I'm currently unsure why this process takes place, because my native (non-electron) macOS apps don't have any of the extra stuff electron-osx-sign is adding to the entitlements, and further they are not in the encoded format being used here.

**Comment by greenimpala** [comment]
@schetle yep I think you're right. See https://github.com/electron/electron-osx-sign/issues/223#issuecomment-611070794 too.

**Comment by sangeeth96** [comment]
@schetle doesn't the binary encoding stem from the `app-builder-bin` package and not osx-sign?

**Comment by schetle** [comment]
@sangeeth96 The originating call for the entitlements (specifically the parent entitlements) getting encoded is in the preAutoEntitlements code in util-entitlements.js from the dependent electron-osx-sign package. The code can be seen on line 88 of util-entitlements.js. It is calling into appBuilder to perform the operation, it looks like, but you can prevent entitlements from getting encoded by preventing the call altogether.

Bypassing that whole section of electron-osx-sign will prevent your entitlements from getting encoded. Take a peek at the file for confirmation of this.

**Comment by mahnunchik** [comment]
It seems it is related:

* https://github.com/electron/electron-osx-sign/issues/192
* https://github.com/electron/electron-osx-sign/issues/223
* https://github.com/electron/electron/issues/20560
* Also there is a mistake in the documentation https://github.com/electron-userland/electron-builder/issues/4956

**Comment by mahnunchik** [comment]
Of course it is relevant! Fucking slate bot!

сб, 11 июл. 2020 г., 17:04 stale[bot] <notifications@github.com>:

**Comment by danutzcodrescu** [comment]
It is relevant and no solution is provided...

**Comment by johannesjo** [comment]
One of the many critical issues solved by the great stale bot! 🥳

**Comment by mahnunchik** [comment]
![110419_Gipnozhaba](https://user-images.githubusercontent.com/780935/98522556-85718d80-227d-11eb-886d-1d481319dad1.gif)

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4790#issuecomment-757380748

**Comment by danutzcodrescu** [comment]
no fix yet...

**Comment by jalilmotaz** [comment]
I had this issue but found out that it was because I was using requestSingleInstanceLock() in the main.js file and this was crashing the mas-dev build. 

https://github.com/electron/electron/issues/15958

**Comment by czzonet** [comment]
The mas-dev runs well after I install the correct provisionprofile. My crash info was 'EXC_CRASH (Code Signature Invalid)'.

"electron-builder": "22.10.5"

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4790#issuecomment-859179879

**Comment by danutzcodrescu** [comment]
https://github.com/electron-userland/electron-builder/issues/4790#issuecomment-817294450

**Comment by devon2018** [comment]
☝️

**Comment by hisnameisjimmy** [comment]
I'm still running into this exact issue. How do we fix this?

**Comment by fatemehmarzoughi** [comment]
Same here (

**Comment by gregoiregentil** [comment]
I have the same issue. Is there a basic entitlement file working somewhere?

**Comment by tylerlong** [comment]
I had been stuck on this issue for 2-3 days and finally I made it work!
Let me share the keys with your guys:

## Put *.plist files and *.provisionprofile files in the **root of `build/` folder**

I didn't do that, and my app quit right after I saw a window and no error was thrown.

## **Install** the *.provisionprofile file

I generated a *.provisionprofile file and I told electron-builder where it is. But I didn't double click to install it to my operating system.

**Comment by mordom0404** [comment]
Thank you so much for your solution here, this solved a problem that had been bugging me for weeks, especially the second point.
It should be pointed out that the plist file and provisionprofile file can be placed anywhere, as long as it can be referenced normally, not necessarily in the ./build folder
Regarding the second point, it took me 2 days to successfully install this provisionprofile into the system, until I found this link: ["Provisioning profile does not allow this device." Mac mini M1](https://developer.apple.com/forums/thread/673778)
The key point is that **both** your mac's UUID and UDID should be added to apple developer's device id list, and make sure they both exist in the provisionprofile. 
At this point, my mas-dev can finally run normally. 
Hope these experience can help latecomers and thank you again.


> I had been stuck on this issue for 2-3 days and finally I made it work! Let me share the keys with your guys:
> 
> ## Put *.plist files and *.provisionprofile files in the **root of `build/` folder**
> I didn't do that, and my app quit right after I saw a window and no error was thrown.
> 
> ## **Install** the *.provisionprofile file
> I generated a *.provisionprofile file and I told electron-builder where it is. But I didn't double click to install it to my operating system. I spent almost a day before I realized that I needed to install it.
> 
> There are lots of mistakes that you can make. The two above are the ones that cost me most time.

**Comment by lukedar** [comment]
@mordom0404 how do you install the .provisionprofile? When I double click its just opens the file in xCode. Is there another step that I need todo?

**Comment by dingshaohua-com** [comment]
> @mordom0404如何安装 .provisionprofile？双击它只会在 xCode 中打开文件。我还需要执行其他步骤吗？
你解决了吗 我也在看这个问题

**Comment by mordom0404** [comment]
> @mordom0404 how do you install the .provisionprofile? When I double click its just opens the file in xCode. Is there another step that I need todo?



> > @mordom0404如何安装 .provisionprofile？双击它只会在 xCode 中打开文件。我还需要执行其他步骤吗？
> > 你解决了吗 我也在看这个问题
> > did you resolve it?

首先要先到Apple Developer网站中的设备页，添加你电脑的UUID和UDID，这点非常重要，必须两个都要添加进去（虽然网页提示只需要UUID）

然后到Profiles页每个应用创建两个provisionprofile，一个是MacOS App Development（用于开发），一个是App Store Connect（用于发布到商店）。创建Development时请记得勾选全部的设备。
其中Development描述文件需要双击一下在系统描述文件中安装（打开方式选择"描述文件安装器.app"）。distribution预设不需要安装，只要放到我们的electron应用根目录即可。

最后一步，前往xcode中，进入设置，点击Accounts，登录你的账号，点击右下角download Manual Profiles。每次在apple developer中新增provisioning profile都要到这里来点击一下这个按钮，否则你的Transporter将无法上传应用到Mac App Store

更详细的内容可以看看我写的这篇踩坑文章：https://www.jianshu.com/p/3f4765c319b6

First, go to the device page on the Apple Developer website and add your computer's UUID and UDID. This is very important and you must add both (although the web page prompts that only the UUID is required).

Then go to the Profiles page and create two provisionprofiles for each application, one for MacOS App Development (for development) and one for App Store Connect (for publishing to the store). Please remember to check all devices when creating Development.
The Development profile needs to be double-clicked to install in the system profile (you can try right click and select "Profile Installer.app" when opening it). The distribution preset does not need to be installed, just put it in the root directory of our electron application.

The last step is to go to Xcode, enter Settings, click Accounts, log in to your account, and click Download Manual Profiles in the lower right corner. Every time you add a provisioning profile in Apple Developer, you must click this button here, otherwise your Transporter will not be able to upload apps to the Mac App Store.

For more details, please see this article I wrote: https://www.jianshu.com/p/3f4765c319b6

**Comment by lukedar** [comment]
@mordom0404 Thank you very much for these details. I will do

> > @mordom0404 how do you install the .provisionprofile? When I double click its just opens the file in xCode. Is there another step that I need todo?
> 
> > > @mordom0404如何安装 .provisionprofile？双击它只会在 xCode 中打开文件。我还需要执行其他步骤吗？
> > > 你解决了吗 我也在看这个问题
> > > did you resolve it?
> 
> 首先要先到Apple Developer网站中的设备页，添加你电脑的UUID和UDID，这点非常重要，必须两个都要添加进去（虽然网页提示只需要UUID）
> 
> 然后到Profiles页每个应用创建两个provisionprofile，一个是MacOS App Development（用于开发），一个是App Store Connect（用于发布到商店）。创建Development时请记得勾选全部的设备。 其中Development描述文件需要双击一下在系统描述文件中安装（打开方式选择"描述文件安装器.app"，当我右键查看打开方式时，Mac默认的就是描述文件安装器.app，我不知道你们为啥默认的是xcode）。distribution预设不需要安装，只要放到我们的electron应用根目录即可。
> 
> 最后一步，前往xcode中，进入设置，点击Accounts，登录你的账号，点击右下角download Manual Profiles。每次在apple developer中新增provisioning profile都要到这里来点击一下这个按钮，否则你的Transporter将无法上传应用到Mac App Store
> 
> 更详细的内容可以看看我写的这篇踩坑文章：https://www.jianshu.com/p/3f4765c319b6
> 
> First, go to the device page on the Apple Developer website and add your computer's UUID and UDID. This is very important and you must add both (although the web page prompts that only the UUID is required).
> 
> Then go to the Profiles page and create two provisionprofiles for each application, one for MacOS App Development (for development) and one for App Store Connect (for publishing to the store). Please remember to check all devices when creating Development. The Development profile needs to be double-clicked to install in the system profile (you can try right click and select "Profile Installer.app" when opening it, When I right-click to view the open method, the default on Mac is the profile installer.app. I don't know why your default is xcode.). The distribution preset does not need to be installed, just put it in the root directory of our electron application.
> 
> The last step is to go to Xcode, enter Settings, click Accounts, log in to your account, and click Download Manual Profiles in the lower right corner. Every time you add a provisioning profile in Apple Developer, you must click this button here, otherwise your Transporter will not be able to upload apps to the Mac App Store.
> 
> For more details, please see this article I wrote: https://www.jianshu.com/p/3f4765c319b6

Thank you for these details I will try this and confirm if it works for me. Much appreciated

**Comment by lukedar** [comment]
@mordom0404  Thank you for these details I will try this and confirm if it works for me. Much appreciated

**Comment by lukedar** [comment]
@mordom0404 I followed your guidelines carefully and I managed to fix most of the errors in Transporter apart from one todo with enabling sandbox. Did you experience this also? This is my current configuration that.

package.json
<img width="664" alt="Screenshot 2024-09-10 at 18 19 24" src="https://github.com/user-attachments/assets/c398c8b3-0da0-4a7f-b4e6-452100f0b6ea">

entitlements.mac.plist
<img width="938" alt="Screenshot 2024-09-10 at 18 18 57" src="https://github.com/user-attachments/assets/63d1c6db-c95f-4b4b-be78-4e75b2b58563">

Transporter Error
<img width="547" alt="Screenshot 2024-09-10 at 18 18 33" src="https://github.com/user-attachments/assets/363f6c80-b943-401e-ab30-f1548b20c66d">

Any help would be much appretiated.

**Comment by dingshaohua-com** [comment]
> @mordom0404我仔细遵循了您的指导，并设法修复了 Transporter 中的大部分错误，除了启用沙盒时的一个待办事项。您也遇到过这种情况吗？这是我当前的配置设置。
> 
> 包名.json <img alt="截图 2024-09-10 18 19 24" width="664" src="https://private-user-images.githubusercontent.com/7011014/366145185-c398c8b3-0da0-4a7f-b4e6-452100f0b6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDY3MTUsIm5iZiI6MTcyNjEwNjQxNSwicGF0aCI6Ii83MDExMDE0LzM2NjE0NTE4NS1jMzk4YzhiMy0wZGEwLTRhN2YtYjRlNi00NTIxMDBmMGI2ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDIwMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFlMzU5ZWMyMzQwZjgzZDg1YTI5NmUxMDdmZTg2ZGQxNWQxNjEwOGJhOWRiMGUzMjkzYjliYTEwZWJhNjkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dh4yyuW25U1V7cnjBNtdmhX7S732rr3q1Lox5ePiXos">
> 
> <img alt="截图 2024-09-10 18 32 14" width="908" src="https://private-user-images.githubusercontent.com/7011014/366148891-49c94834-e3b7-4424-8da8-27898fbb229b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDY3MTUsIm5iZiI6MTcyNjEwNjQxNSwicGF0aCI6Ii83MDExMDE0LzM2NjE0ODg5MS00OWM5NDgzNC1lM2I3LTQ0MjQtOGRhOC0yNzg5OGZiYjIyOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDIwMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWRlNDFhZjM1NzFiNzJiOWQ4ZWEwNDA3ZThkMjBiMWI3OWQ3YTFhOTc1MTk2NjJmOTcwNzlmODU0ODNmYWJjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zdSQedy7JeEmEe7e4gdDP6r6EySgQaM25bWEDHq28Hs"> <img alt="截图于 2024-09-10 18 18 57" width="938" src="https://private-user-images.githubusercontent.com/7011014/366145292-63d1c6db-c95f-4b4b-be78-4e75b2b58563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDY3MTUsIm5iZiI6MTcyNjEwNjQxNSwicGF0aCI6Ii83MDExMDE0LzM2NjE0NTI5Mi02M2QxYzZkYi1jOTVmLTRiNGItYmU3OC00ZTc1YjJiNTg1NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDIwMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU3ZTNmZTI0MGU1M2JiZDFlNzQ5NWM2MDUyYTNlYTlkOTIxZTdiM2RiNDQ5ZGM3MDMzMDc2ODExYzRkZTdhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vum_Jk-aCNDIq35MdtHBG8w2PvXW-EXIG8HisHHSVE0">
> 传输器错误 <img alt="截图于 2024-09-10 18 18 33" width="547" src="https://private-user-images.githubusercontent.com/7011014/366145609-363f6c80-b943-401e-ab30-f1548b20c66d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDY3MTUsIm5iZiI6MTcyNjEwNjQxNSwicGF0aCI6Ii83MDExMDE0LzM2NjE0NTYwOS0zNjNmNmM4MC1iOTQzLTQwMWUtYWIzMC1mMTU0OGIyMGM2NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDIwMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzRhMjcwNTk0ODkwMDI5NWI2MWVkNTM0ZDBlODQwMDkyYjdlOTBhMGNmYTViMzNkNDlmZGZhNDYzYzY3OGRkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xNkw2JWUzJ3Ubnur_lgPsHILUkzqjvfQHrPQt4a4_gA">
> 
> 如能提供任何帮助我将非常感激。

i can help you,I just successfully launched on the Apple Store，You may still have a lot of work to do in the future, as I prefer instant messaging. You can call me a friend like tg、qq、wechat

**Comment by mordom0404** [comment]
@lukedar 
You need at least 3 plist files. This is my mas settings:
```
"mas": {
    "type": "distribution",
    "identity": "xxx",
    "hardenedRuntime": false,
    "entitlements": "./entitlements.mas.plist",
    "entitlementsInherit": "./entitlements.mas.inherit.plist",
    "entitlementsLoginHelper": "./entitlements.mas.loginhelper.plist",
    "provisioningProfile": './xxx.provisionprofile',
  },
```

### First One
entitlements.mas.plist, this records the permissions required by the application, such as camera permissions, network permissions, file read and write permissions, etc.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>xxxxx.com.xxxxx.xxxx</string> //teamId.bundleId of your application
    </array>
    <key>com.apple.application-identifier</key>
    <string>xxxxx.com.xxxxx.xxxx</string> //teamId.bundleId of your application
    <key>com.apple.security.cs.allow-jit</key> //electron20+ must have this item, otherwise it will crash
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>// Prevent crash
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>// Prevent crash
    <true/>
    // The following permissions are custom permissions. Add them as needed based on your application. No more, no less.
    <key>com.apple.security.files.user-selected.read-only</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.files.bookmarks.document-scope</key>
    <true/>
    <key>com.apple.security.files.bookmarks.app-scope</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
  </dict>
</plist>
```

### Second One
entitlements.mas.inherit.plist, Do not modify any code in it
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```

### Third One
entitlements.mas.loginhelper.plist,  Do not modify any code in it
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <true/>
    </dict>
</plist>
```
The above content is all in my [article](https://www.jianshu.com/p/3f4765c319b6), please be sure to read it carefully

**Comment by dingshaohua-com** [comment]
> @mordom0404 how do you install the .provisionprofile? When I double click its just opens the file in xCode. Is there another step that I need todo?

i can help you,I just successfully launched on the Apple Store，You may still have a lot of work to do in the future, as I prefer instant messaging. You can call me a friend like tg、qq、wechat
