### ISSUE TITLE
Windows 10 report virus Trojan:Win32/Bulta!rfn of Uninstall xxx.exe

### ISSUE THREAD

**Issue by tangjfn** [electron-userland/electron-builder#4793]
* **Version**: 22.4.1

4.2.5

* **Target**: win32 x64 nsis-web

Windows 10 1909 18363.720

electron-builder execute fail, because windows has deleted the uninstall.exe

22.3.6 is OK

**Comment by baryon** [comment]
I have same issue. Trojan:Win32/Bulta!rfn

**Comment by Kyusung4698** [comment]
Same Issue. My NSIS installer got blocked. 

![poeoverlay-threat](https://user-images.githubusercontent.com/14848329/77107035-5a050e80-6a20-11ea-8eba-a0a8e4688c21.png)

**Comment by Kyusung4698** [comment]
Hi, I've submitted a flagged version of my installer as false positive to Microsoft. I'll keep you updated.

**Comment by Kyusung4698** [comment]
Update: Microsoft has removed/ approved the false Detection. Please see following Submission:
https://www.microsoft.com/en-us/wdsi/submission/69113a4a-0fc7-423d-80ad-f6ed0cf128ad

They'll roll out a new definition file of the Windows Defender soon which will prevent this false flagging.

**Comment by adriencohen** [comment]
I have submitted my own uninstaller too, they approved the false detection and it worked. However after rebuilding a new version of my app the uninstaller was detected again. Looks like we are going to need to pinpoint the commit which added this

**Comment by lutzroeder** [comment]
@develar could the update to nsis 3.0.4.2 in 4e454f8b4 have caused this?

```
4e454f8b4 packages/app-builder-lib/src/targets/nsis/nsisUtil.ts      (develar             2020-03-03 13:48:34 +0100  22)   return getBinFromUrl("nsis", "3.0.4.2", "o+YZsXHp8LNihhuk7JsCDhdIgx0MKKK+1b3sGD+4zX5djZULe4/4QMcAsfQ+0r+a8FnwBt7BVBHkIkJHjKQ0sg==")
```

**Comment by edward-buskus** [comment]
I have same issue. Is there any solution for this problem?

**Comment by develar** [comment]
NSIS updated to 3.0.5, maybe Windows Defender will be more happy with this version. electron-builder will be released soon.

**Comment by edward-buskus** [comment]
with   `deleteAppDataOnUninstall: false`  helped me at the moment.

**Comment by develar** [comment]
Please try 22.5.0

**Comment by awlx** [comment]
22.5.0 doesn't produce a build anymore:
https://ci.appveyor.com/project/awlx/jitsi-meet-electron/builds/31874856

**Comment by develar** [comment]
I don't have time today to investigate what's wrong with building on Windows using a new version of NSIS.

So, reverted to 3.0.4.1 as a quick solution.

**Comment by indutny-signal** [comment]
It has been a year since initial report. Should NSIS version be reverted back to `3.0.5.0` now?

**Comment by indutny-signal** [comment]
Friendly ping. The new NSIS build shouldn't trigger the antivirus anymore, so I think we could try bumping it up again.

**Comment by JCMais** [comment]
This seems to be happening again on the latest version.

**Comment by indutny-signal** [comment]
I don't believe nsis version was changed since September: https://github.com/electron-userland/electron-builder/commits/master

**Comment by vnicolici** [comment]
I have a similar problem with an install.exe file coming from an Electron app: https://i.imgur.com/Cxj1weh.png

**Comment by dclipca** [comment]
https://i.scdn.co/image/ab67616d0000b273950359444321d635b59838b3

**Comment by dclipca** [comment]
Updating to ```electron-builder 22.14.10``` fixes the issue because it has ```NSIS 3.0.4.1```.

**Comment by BarryCarlyon** [comment]
This one is rearing it's head again in the last couple of hours when trying to build.

On the uninstaller no less....

**Comment by ErikMach** [comment]
@BarryCarlyon I had the same problem with version 22.14.5.
But I just used 22.14.12 and it worked fine.

**Comment by BarryCarlyon** [comment]
@ErikMach since 22.14.12 isn't on NPM I tried to intalled it via github and got a weird "this is not a mac" error on my windows machine. So I'll need to dig about with that further.

**Comment by ErikMach** [comment]
I installed it via npm with the command `npm install --save-dev electron-builder@22.14.12`

**Comment by BarryCarlyon** [comment]
I'll give it a poke :-D

**Comment by koyuawsmbrtn** [comment]
Still an issue with the latest release of electron-builder. Issue can be reopened.

**Comment by egeres** [comment]
Same issue happening here!

**Comment by augustnmonteiro** [comment]
Same here as well

**Comment by augustnmonteiro** [comment]
When we send and update to the users, it gets uninstalled but it doesn't get installed again

**Comment by augustnmonteiro** [comment]
@develar can we reopen this one?

**Comment by joehinkle11** [comment]
I have the same issue on on 23.3.3. I just started investigating it.
