### ISSUE TITLE
Package both development & production applications

### ISSUE THREAD

**Issue by eschirtz** [electron-userland/electron-builder#4795]
* **Version**: 21.2.0
* **Target**: All

I am building an application that I would like to have both a packaged development build and a packaged production build. This would be great so we could test out the changes we make on our own machines before deploying to our users. Watching how auto-updates affect current users apps, avoiding breaking changes. 

I am able to achieve almost all of this functionality by relying on environment variables, such as process.env.NODE_ENV. However, I run into one big issue, the appName. 

The app name is pulled from package.json which is tricky because I can not dynamically change that value easily with an environment variable. When a dev build of an app is packed its appData collides with that of the production build. 

I know that I can change the appName at runtime, but this won't work for certain issues. For instance, I want to create a logger using `winston`, I would like to have it log to AppData/logs or something. But if I rely on `app.getPath('logs')`, I am unable to configure my specific app path or app name prior. Even when setting the appName via `app.setName` in `main.js`, that won't work because if I import my logger in that file, the logger will be configured prior to me being able to set the new app name.

I am wondering if there is a way to override the `package.json` name prior to runtime.

For more context, I am using the `vue-cli-plugin-electron-builder` package, and I have a config similar to this below which is how I am able to switch between dev and prod contexts. Just stuck on the appName. 

I hope this makes sense, thank you!

```
const builderOptions = {
  appId: 'com.my.app',
  artifactName: '${productName}-Setup.${ext}',
  directories: {
    buildResources: 'build',
  },
  productName: 'MyProduct',
  publish: {
    provider: 'github',
    owner: 'me,
    repo: 'my-repo',
  },
};

const devBuilderOptions = {
  appId: 'com.my-dev.app',
  artifactName: '${productName}-Setup.${ext}',
  directories: {
    buildResources: 'build-dev',
  },
  productName: 'MyApp Dev',
  publish: {
    provider: 'github',
    owner: 'me',
    repo: 'my-repo',
  },
};

// Electron builder options (via vue-cli-plugin-electron-builder)
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: process.env.NODE_ENV === 'development' ? devBuilderOptions : builderOptions,
    }
...
}
```

**Comment by nordskill** [comment]
Is there any solution for this case? Because I have exactly the same issue.
