### ISSUE TITLE
spawn unzip ENOENT npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! frontend@1.0.0 package-linux: `electron-packager ./src --platform darwin --icon=assets/icons/png/icon.png --out ./dist --overwrite` npm ERR! Exit status 1 npm ERR!  npm ERR! Failed at the frontend@1.0.0 package-linux script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  npm ERR! A complete log of this run can be found in: npm ERR!     /home/akhil/.npm/_logs/2020-03-18T12_07_45_746Z-debug.log

### ISSUE THREAD

**Issue by asakhil** [electron-userland/electron-builder#4796]
* **Version**: 

* **Target**:

**Comment by Slapbox** [comment]
Fix your issue title please, it's a monstrosity.

**Comment by asakhil** [comment]
spawn unzip ENOENT
npm ERR! code ELIFECYCLE
npm ERR! frontend@1.0.0 package-linux: `electron-packager ./src --platform darwin --icon=assets/icons/png/icon.png --out ./dist --overwrite`
npm ERR! Failed at the frontend@1.0.0 package-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

this error while happen in electron-packager run in loinux system. Cannot run properly npm run package-linux. shot the above error

**Comment by asakhil** [comment]
ok
