### ISSUE TITLE
Error with electron-packager

### ISSUE THREAD

**Issue by CandysMan** [electron-userland/electron-builder#4799]
Hi I am using electron(8.1.1) and electron-packager(14.2.1) and both are used as devDependencies  still they give one warning like this 

Please help me, for deploying electron project for production 

Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x 

![1](https://user-images.githubusercontent.com/60536077/77072055-18219b80-6a13-11ea-886a-c43c7da70353.JPG)
![2](https://user-images.githubusercontent.com/60536077/77072065-1ce64f80-6a13-11ea-8dcb-55f6b411ddee.JPG)

**Comment by CandysMan** [comment]
"win": "electron-packager . test --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/win/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Billing Bytes\""


When I run that it gives Legacy Error

**Comment by LaneSh4d0w** [comment]
The log is saying that he did not find a specific file to rename, the legacy error is only a warning in that case. I do not know if this is electron-builder related or if it's related to something else in your configuration that does that. It seems it is related to a dependency (rcedit in that case).
