### ISSUE TITLE
Help with publishing artifacts

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#480]
I have a few questions - I went through the docs and don't have 100% understanding, so help me out if you can :)

-If I could only get help on this part that'd be enough! In the [publishing artifacts](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts) page, what do all of these values mean in `publish` ? Does this go in my `package.json` ? I'm trying to integrate this into a Jenkins build, but not sure what and where the values `onTag`, `onTagOrDraft`, etc., mean and where they go.

-When publishing artifacts to Github, what's the recommended workflow? We create a draft of a release, then run ` npm run release ` which, in my npm scripts in `package.json` is `build --o && build --w && build --l`. This works fine, and my artifacts get published correctly. But then we do `publish release` on github, manually? Is there a way to automate this? I don't want to create a release draft, then do `npm run release`, then publish the draft.

-How are people usually doing their releases? Travis and AppVeyor seem to be the way to go, but I need to use Jenkins. Are you using a bash scripts as an intermediary before using `electron-builder` with a CI? Or just using `electron-builder` to generate everything, and manually uploading releases?

I know I asked a lot, but just looking for clarification, since almost everything works already.

**Comment by develar** [comment]
> what do all of these values mean in publish ? Does this go in my package.json ?

No. It is CLI. `--publish onTagOrDraft `. Or programmatic API.

> When publishing artifacts to Github, what's the recommended workflow?

https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts find "This is the recommended workflow."

> But then we do publish release on github, manually?

Yes, manually. 

>  Is there a way to automate this? I don't want to create a release draft, then do npm run release, then publish the draft.

#446 Help wanted. No resources yet to implement it.

> Travis and AppVeyor seem to be the way to go, but I need to use Jenkins

CI server can be any. No dependency. Well, Travis and other set convenient env vars like project slug, tag — but you can set it also manually.

**Comment by develar** [comment]
> I don't want to create a release draft, then do npm run release, then publish the draft.

Why it was implemented so — before you can release, you must test artifacts. But to test you should have artifacts — you must test artifacts from CI, not from your development machine, so, electron-builder uploads to draft release, you grab it and test, and if all is ok — you release.
