### ISSUE TITLE
ERR_ELECTRON_BUILDER_CANNOT_EXECUTE | Electron builder fails if version in package.json is set to 10.0.0

### ISSUE THREAD

**Issue by asadmalik3** [electron-userland/electron-builder#4802]
* **Version**:  22.4.1

* **Target**: win

**npm run dist** successfully creates installer which can be installed on windows. But if my version in package json is set to "10.0.0" or if any part of version is greater than 9, then **npm run dist** fails with below given error

AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.2\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

**How to reproduce:**
1. Install electron builder
2. Change version in package json to 10.0.0 or 0.0.10
3. Run **npm run dist**
4. See error in console

**Comment by asadmalik3** [comment]
IDK how, but this is working fine now.

**Comment by philippnoah** [comment]
What did you change to achieve it? Having a related issue.

**Comment by asadmalik3** [comment]
@philippnoah I dont know, it got fixed automatically.

**Comment by cnscorpions** [comment]
@asadmalik3 Hi, I am also stuck by this error. Please advise how to resolve it. 

OS win10 pro
"electron": "^10.1.1",
"electron-builder": "^22.8.0"

**Comment by neviko** [comment]
@cnscorpions did you find a solution for that? (electron v10)

**Comment by ufukomer** [comment]
@neviko I was getting same error while trying to build on Mac and the solution was to agreeing the Xcode agreement or something like that using this command:

`
sudo xcodebuild -license
`
