### ISSUE TITLE
Feature Request: specify custom filename output for targets on command line

### ISSUE THREAD

**Issue by AxelTerizaki** [electron-userland/electron-builder#4808]
* **Version**: 22.4.1
* **Target**: All

What I'd like to do is simple : specify a custom filename for my installers generated from electron-builder.

When electron-builder runs, it uses productName + version, but if for instance I'd like productanme + something else, I'd need to rename the executable in my CI runner and also modify the .yml file generated by electron-builder.

If this option exists and I missed it, I apologize.

I realize this isn't a very common use case, but it's also not urgent at all, but I'd appreciate if you could look into it, if time allows.

Thanks for such a good tool :)

**Comment by ivangomes** [comment]
You can do it on your: electron-builder.json file.

**Comment by AxelTerizaki** [comment]
Oh, to be more precise, is that the ArtifactFilename property ? I just noticed it now.

**Comment by ivangomes** [comment]
Yes!


You can specify the output filename using artifactName in the build section of your package.json.

The docs say the artifact file name template supports the ${ext} macro:

${ext} macro is supported in addition to file macros.
File Macros

You can use macros in the file patterns, artifact file name patterns and publish configuration url:

${arch} — expanded to ia32, x64. If no arch, macro will be removed from your pattern with leading space, - and _ (so, you don't need to worry and can reuse pattern).
${os} — expanded to mac, linux or win according to target platform.
${name} – package.json name.
${productName} — Sanitized product name.
${version} — from package.json
${channel} — detected prerelease component from version (e.g. beta).
${env.ENV_NAME} — any environment variable.
Any property of AppInfo (e.g. buildVersion, buildNumber).
Example

"build": {
    "appId": "com.electron.app.my",
    "artifactName": "node-app-${version}.${ext}",
    ...
},


Original Post [Click Here](https://stackoverflow.com/questions/40549421/retrieve-or-specify-output-file-name-in-electron-builder)

Thanks to Greg K

**Comment by AxelTerizaki** [comment]
That definitely sounds like something that hsould be in the docs, but it answers my question, even if it's not from the commandline :) Thank you!

**Comment by iamrmin** [comment]
I am not sure who else is facing this issue. having buildNumber is a common use case. like `MyAPp-3.19.0-latest-406.exe` I am using buildNumber in artifactName and this cause and issue in autoUpdate while fetching old blockmap file. [NsisUpdater](https://github.com/electron-userland/electron-builder/blob/9305fefa1265ec1a244b0003bd4489731d5f15a4/packages/electron-updater/src/util.ts#L35) take new blockmap and just replace the version with old version keeping build number of new block file that lead to wrong file name and could not download differentially.
