### ISSUE TITLE
How can I set custom application name?

### ISSUE THREAD

**Issue by VadimKorobka** [electron-userland/electron-builder#4809]
> [Specify the standard fields in the application package.json — name, description, version and author.](https://www.electron.build/#quick-setup-guide)

Can I set the application ***name*** manually through the config? I use an electronic builder programmatically. The **name**, not the **productName**. Because When installing an application with the same ***name*** but with a different ***productName***, they conflict.

**Comment by ivangomes** [comment]
Are you using electron-builder.json?

My package.json

{
  "name": "goproduce",
  "version": "1.0.0",
  "description": "Go Produce - enterprise resource planning (ERP)",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder build --mac --publish never",
    "deploy": "electron-builder build --mac -p always"
  },

My electron-builder.json:

{
  "productName": "Go Produce",
  "appId": "com.wmsgosoftware.goproduce",
  "directories": {
    "output": "dist/${version}"
  },
  "publish": [ <"I'm using this for auto update using Github Release"
    {
      "provider": "github",
      "private": true,
      "owner": "ivangomes",
      "repo": "goproduce",
      "token": ""
    }
  ]
}

**Comment by VadimKorobka** [comment]
@ivangomes Thank you very much for the quick response! No, I do not use, but how will this help me solve my problem? Based on environment variables, I need to build a program with a different name.

**Comment by ivangomes** [comment]
I see! Based on env variables. So what you trying to do is build the same project, but different builds based on the env for the same App. Is that correct?

**Comment by VadimKorobka** [comment]
Yes, now I hack this issue by using `sed`:
- sed -i "2s/somename/$BUILD_NAME/" package.json

**Comment by VadimKorobka** [comment]
I can implement this feature, of it is not available.

**Comment by VadimKorobka** [comment]
I deep-dive into the source code of the Electron-Builder and noticed the possibility of introducing any properties into the package.json. The solution to the problem is using [extraMetadata](https://www.electron.build/configuration/configuration.html#Configuration-extraMetadata):
```js
build: {
    appId: `com.${companyName}.${name}`,
    extraMetadata: {
        name, // !!!
    },
    productName: `${productName}`,
}
```
