### ISSUE TITLE
Builder attempts to sign OSX app even though no signing is specified

### ISSUE THREAD

**Issue by Edward-Lombe** [electron-userland/electron-builder#481]
How does one disable OSX code signing, is there an option for this?

**Comment by develar** [comment]
Attempt and failed or you just want to not sign using your identity?

**Comment by rafajaques** [comment]
Same here!
I just don't want to sign the app at all.

```
node_modules/.bin/build --osx
Rebuilding app dependencies for arch x64 to /Users/rafajaques/Node/php-assistant/app

...

Packaging app for platform darwin x64 using electron 1.2.2 to dist/osx
Signing app (identity: ghconduit.com)
Error: Command failed: codesign --sign ghconduit.com --force /Users/rafajaques/Node/php-assistant/dist/osx/PHP Assistant.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
ghconduit.com: this identity cannot be used for signing code
```

**Comment by develar** [comment]
Workaround: set env `CSC_IDENTITY_AUTO_DISCOVERY=false`. (version 5.0.3+).

**Comment by rafajaques** [comment]
Nice!
`export CSC_IDENTITY_AUTO_DISCOVERY=false` worked.
Thanks!

**Comment by develar** [comment]
It is only and only temp workaround. It is bug — we must use only `-p codesigning -p appleID` certs.

**Comment by develar** [comment]
@rafajaques  Please attach here result `security find-identity -v -p codesigning -p appleID`

**Comment by rafajaques** [comment]
```
     0 valid identities found
  1) 13E78D815D7D7DD88128F549D7E955AA18344D42 "ghconduit.com" (Missing required extension)
     1 valid identities found
```

**Comment by kunkinkan** [comment]
So what is the option we must add to our package.json to not codesign?

**Comment by develar** [comment]
@kunkinkan No option, invalid certs filtered out automatically. To not use valid certs, see https://github.com/electron-userland/electron-builder/issues/481#issuecomment-225169080
