### ISSUE TITLE
cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1f7mm3u": dial tcp 51.15.76.176:443:

### ISSUE THREAD

**Issue by teknoalex** [electron-userland/electron-builder#4812]
* **Version**: 
electron-builder  version=22.4.1 os=10.0.17763

* **Target**: 
windows & Linux

It seems like one of your servers is down.

**Comment by teknoalex** [comment]
seems like they are up now

**Comment by miyanoyuriko** [comment]
Did you solve your problem?
I have same problem,can you tell me how to solve it?

**Comment by teknoalex** [comment]
I am currently using electron-forge

**Comment by teknoalex** [comment]
I am currently using electron-forge
