### ISSUE TITLE
Update is downloaded but not installed, if application was installed for all users (in Program Files) on Windows

### ISSUE THREAD

**Issue by Dysey** [electron-userland/electron-builder#4815]
* **electron-builder**: 22.4.1

* **electron-updaterr**: 4.2.5

* **Target**: nsis

Settings:

```
"win": {
      "icon": "build/icons/icon.ico",
      "requestedExecutionLevel": "highestAvailable",
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "artifactName": "${productName}.${ext}",
      "uninstallDisplayName": "IC Launcher"
    },
```

Steps to reproduce:

1. Build electron app, and put the version to lets say 1.0.0;
2. Build nsis target and artifacts for auto-update (latest.yml);
3. Build the app again, put the version to lets say 1.0.1, also build artifacts (latest.yml);
4. Upload the 1.0.1 version to your server, or wherever, just so 1.0.0 can see it;
5. Launch the 1.0.0 app. Wait for the update to download, app relaunches to update. So far so good.
6. Now, if the app was installed for single user (to C:/Users/User/AppData/Local/Programs/...) everything is fine, the app is uninstalled, then the 1.0.1 version is installed, all good.
But if the app was installed for all users (to C:/Program Files/...) the UAC dialog launches, asking for permission (as expected), the app is uninstalled (as expected), but then it is not installed again (totally unexpected). No errors, no warning, no nothing.

I will be happy to provide any other info if needed.

I create this issus because this one is closed : https://github.com/electron-userland/electron-builder/issues/4474

Thanks

**Comment by ouyang-yuxuan** [comment]
I have encountered the same problem and have no solution at present

**Comment by ganthern** [comment]
We have the same problem. https://github.com/tutao/tutanota/issues/1413

**Comment by jmeinke** [comment]
We have seen this happen at some customers as well...

**Comment by Dysey** [comment]
If someone finds a solution !

**Comment by ganthern** [comment]
We now have a workaround that basically consists of not using the autoInstallOnAppQuit feature of autoUpdater, which seems to work.

 ```
autoUpdater.installOnAppQuit = false
app.once('before-quit', ev => {
    if (this._installOnQuit) {
        ev.preventDefault()
        this._installOnQuit = false
        autoUpdater.quitAndInstall(false, false)
    }
})
 ```

**Comment by Dysey** [comment]
> I noticed that the file `update-info.json` in `%APPDATA%\Local\appname-updater\pending` contains the key `isAdminRightsRequired`, which is set to `false` even for system-wide installs. This might be something to investigate.

I try to update manually this value, change nothing !!

**Comment by NoFrosty** [comment]
Got exactly the same problem,
If my application is installed in program files, and i got an update
it ask me permissions for OLDUNINSTALLER
But install nothing after that and ask nothing too.
So Updater just uninstall if it's installed in program files.

**Comment by NoFrosty** [comment]
Opening the application in Administrator Mode is solving the problem.
It doesn't ask permission for olduninstaller and install it after removing old files.

**Comment by yudioll** [comment]
> Opening the application in Administrator Mode is solving the problem.
> It doesn't ask permission for olduninstaller and install it after removing old files.

I try to run the program as an administrator, the upgrade will be interrupted

**Comment by Dysey** [comment]
Any update here pls ??

**Comment by Nerlin** [comment]
I have the same issue in my app.
If user installs the app to Program Files, the auto updater removes the program but doesn't install a new version. Users end up with broken shortcuts on their desktops and deleted application.

**Comment by lidel** [comment]
@Nerlin setting up NSIS `UAC_RunElevated` macro + `allowElevation: true` helped in my case ([example](https://github.com/ipfs-shipyard/ipfs-desktop/pull/1679/files))
