### ISSUE TITLE
Asar: true failing on Windows for electron-builder 5.x

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#482]
New changes to asar archiving in 5.x.x leads to an incorrect/corrupt `win-unpacked/resources/app.asar` when `"build" : { "asar" : true }` on Windows.

Hence, when the app is opened via Setup.exe (or app.exe) you get the exception "Error: Unable to find a valid app" in the main process. This is expected as app.asar is corrupt (only a few kB, normally ~5MB).

If I set **asar: false**, everything works.

Last known working version with asar: true was 4.2.6.

Note: I inspected the corrupt app.asar in vscode and it showed the directory/file structure to be correct, but the files were empty (or appeared as directories instead of files).

**Comment by develar** [comment]
Latest reverted to 4.2.6, issue will be checked/fixed ASAP.

**Comment by dharders** [comment]
I think I've found the issue:

[platformPackager.ts#L317](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L317) is checking `else if (glob!.cache[it] === "FILE")` 

Here glob.cache is using UNIX forward slashes /, but on Windows it's using back slashes \
 
Hence, the condition is never true (undefined) and thus falls through to else `type: 'directory'`, which explains why everything was a directory in vscode.

Soln: make a check in src param passed to createAsarArchive or path.join in a cross platform way... i.e. all forward slashes etc

**Comment by dharders** [comment]
@develar Here's my fix for windows ... I don't think it will break other platforms

Change this line [platformPackager.ts#L306](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L306)

`})).map(it => path.join(src, it))`
to
`})).map(it => path.join(src, it)).map(it => it.replace(new RegExp('\\\\', 'g'),'/'));`

Using the above works with **asar:true on 5.0.2 on Windows!**

**Comment by develar** [comment]
@dharders I am working on fix, will be release in 15 minutes. Thanks and sorry for inconvenience (check added to prevent such issues in the future).
