### ISSUE TITLE
Electron updater not downloading update on macOS

### ISSUE THREAD

**Issue by dusanristic** [electron-userland/electron-builder#4821]
**Versions:**
- Electron: 8.2.0
- Electron Builder: 22.4.1
- Electron Updater: 4.2.5

**Target**
- MacOS Catalina 10.15.1

I can't download updated version of app from Amazon S3. 
Download starts, and after some time I get error bellow:
 
`[1] Error: Error: Request timed out
[1]     at Timeout.timeoutCb [as _onTimeout] ({...}/node_modules/builder-util-runtime/out/httpExecutor.js:319:16)`
`[1]     at listOnTimeout (internal/timers.js:531:17)`
`[1]     at processTimers (internal/timers.js:475:7)`

It worked well until now. Any clues or ideas?

**Comment by shrinidhi111** [comment]
Does the bucket have public permissions and the .yml files?

Are you using dmg that is signed and notarized?

**Comment by dusanristic** [comment]
Bucket does not have public permissions, I am using `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` to access the bucket. It has .yml file. And yes, the app is signed and notarized.

I don't think that problem is in the code, because update worked well until the last Friday, and it start working again on Saturday. Colleague of mine said that he has encountered this error once more in the past, so that makes it total of two times that this error happened to us. In the meanwhile, code related to app's publishing hasn't been changed.

Is it possible that problem is related with Amazon S3 buckets?

**Comment by kanasimi** [comment]
Is #4744 related?
