### ISSUE TITLE
App update leaves previous installed version in Windows and cannot be removed

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron-userland/electron-builder#4826]
* **Version**: 21.1.5
* **Electron-updater**: 4.1.2
* **Target**: nsis
* **OS**: Windows 10

After updating to a new app version, two versions are displayed under the installed apps window:
Type in search  field:  **apps**, then open  **Settings window** and click to **Apps**. You will see two installed versions of app.
If you uninstall the first app, doesn't matter a new or old version (because actually only new version exists on the PC), and after that try to uninstall the second app, you will see such error:

![UninstallErroWin](https://user-images.githubusercontent.com/21108344/77917893-c810c780-72a3-11ea-9807-fb0cac4bcd6e.PNG)

**Note:** This problem occurs periodically with different versions of electron-builder

**Comment by jmeinke** [comment]
This is related to https://github.com/electron-userland/electron-builder/issues/4092
