### ISSUE TITLE
Webframe error.

### ISSUE THREAD

**Issue by ahgan84** [electron-userland/electron-builder#483]
Hi guys, I'm using win10 and electron-prebuilt 3.25. I encounter error when trying to use a zoom in function from webframe. Is the below code correct?
```js
const electron = require('electron'); 
const {app} = electron; 
const {BrowserWindow} = electron; 
let win; 
var settings = require('./settings');
const {ipcMain} = require('electron'); 
const {webFrame} = require('electron'); 
webFrame.setZoomFactor(2);
```

The error is :
`Cannot read property 'setZoomFactor' of undefined.`

I call the function at the top of the page. Is it correct?
If it is wrong then where should I put the webframe function in my code?

**Comment by develar** [comment]
Because you must wait app initialisation. Window at this time just not yet created. https://github.com/electron/electron-quick-start/blob/master/main.js#L33

https://github.com/electron/electron/blob/master/docs/api/app.md#event-ready

**Comment by ahgan84** [comment]
I use another approach. I put in web-preference. 

`    win = new BrowserWindow({
        fullscreen: true,
        webPreferences: {
            zoomFactor: 1.2
        }`

**Comment by ttynhi** [comment]
It still don't work.
