### ISSUE TITLE
Error during creating build; return super.executeDownload({ ...taskOptions SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by ahmadwaliesipick** [electron-userland/electron-builder#4835]
"electron-builder": **"21.2.0",**
"electron": "1.8.8",
I cannot used latest versions because i have project dependencies. 
"electron-updater": **"^4.0.0",**

**During creating build i am facing below error;**

node_modules\electron-updater\out\BaseUpdater.js:40
    return super.executeDownload({ ...taskOptions,
                                   ^^^
SyntaxError: Unexpected token ...
```

**Comment by gingerbeard-hnly** [comment]
I am experiencing a similar error but running all the latest versions.

"electron": "^1.8.8",
"electron-builder": "^22.6.0",
"electron-updater": "^4.3.1"

As soon as I add  **const {autoUpdater} = require('electron-updater');** and run **npm start** I get the following error.

C:\Users\<username>\github\<appname>\node_modules\electron-updater\out\BaseUpdater.js:40
    return super.executeDownload({ ...taskOptions,
                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _BaseUpdater (C:\Users\<username>\github\<appname>\node_modules\electron-updater\out\NsisUpdater.js:31:16)

I have deleted my node_modules and package-lock.json file and reinstalled everything again but this error keeps appearing every time I try add the auto update feature.

Any help resolving this would be greatly appreciated.

**Comment by LiamHillier** [comment]
@gingerbeard-hnly @ahmadwaliesipick Updating electron to the latest version fixed it for me.
