### ISSUE TITLE
Finds incorrect codesigning identity and fails

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-builder#484]
I have updated to version 5, and added `identity` to `package.json`, and changed it to be the name part only, but electron is now trying to use my iPhone Distribution certificate - it should be using "3rd Party Mac Developer Application" and "3rd Party Mac Developer Installer" certificates.

To me it seems like it was clearer when I specified the full name of both as `CSC_NAME` and `CSC_INSTALLER_NAME`.

**Comment by develar** [comment]
Please attach here result `security find-identity -v`

and log of your build (full name of used identity).
