### ISSUE TITLE
Dockerhub wine-chrome image out of date

### ISSUE THREAD

**Issue by bvc** [electron-userland/electron-builder#4842]
* **Version**: *electronuserland/builder:wine-chrome*

Filing an issue to notify that on dockerhub the official image for `electronuserland/builder:wine-chrome` appears to be out of date.  It seems like `wine` and `wine-mono` were recently updated 1 month from filing this issue but `wine-chrome` hasn't been updated since last year.

**Comment by develar** [comment]
Done.
