### ISSUE TITLE
No suitable image found.  Did find

### ISSUE THREAD

**Issue by Masaccioi** [electron-userland/electron-builder#4844]
* **Version**:  22.4.0

* **Electron Version**: 7.2.1
* **Electron Type (current, beta, nightly)**: current

* **electron-updater**: 4.2.0

* **Target**: 
* **Xcode Version**: 11.3

I try to upgrade to electron 7.2.1 from 5.0.12. After upgrading, the build is wired.
On my colleague's computer with Xcode 10.3, there is no problem.
But on my computer with Xcode 11.3, there is an error.
![image](https://user-images.githubusercontent.com/19363587/78359677-1d244480-75e8-11ea-80da-3af3cc721007.png)

I am so confusing, can you give me some clue to handle this error. Thank you so much

**Comment by matextrem** [comment]
You have to add    ` <key>com.apple.security.cs.disable-library-validation</key>` to your entitlements.mac.plist

**Comment by Masaccioi** [comment]
It works, thank you very much. Your answer made us focus on the native third-party libraries. Finally, we found we changed the spellchecker libraries but forgot to sign for the new library. 
![image](https://user-images.githubusercontent.com/19363587/78636211-75a25d00-78da-11ea-9704-6c65059056cd.png)
