### ISSUE TITLE
electron-updater update-downloaded not call on mac

### ISSUE THREAD

**Issue by FindChenLinJie** [electron-userland/electron-builder#4845]
* **Version**: 
4.2.5

* **Electron Version**: 4.0.2
* **Electron Type (current, beta, nightly)**:

* **Target**: dmg zip

autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
  console.log(event, releaseNotes, releaseName)
});

console.log is not print

**Comment by shrinidhi111** [comment]
Try other events. Check if console log is print? 


autoUpdater.on('checking-for-update', () => {
autoUpdater.on('update-available', (info) => {
autoUpdater.on('update-not-available', (info) => {
autoUpdater.on('error', (err) => {
autoUpdater.on('download-progress', (progressObj) => {
autoUpdater.on('update-downloaded', (info) => {


etc..
