### ISSUE TITLE
Creating an MSI on Windows fails

### ISSUE THREAD

**Issue by skewis6** [electron-userland/electron-builder#485]
I'm trying to build an MSI on Windows, I've added in the flag `msi: true`, but this keeps throwing this wonderful error. 

> Error: C:\test\directory\node_modules\electron-winstaller-fixed\vendor\Update.com failed with exit code: 4294967295

Not really sure what to do with that error. I notice it says **electron-winstaller**, so it could well be an issue with that project itself but I'm not sure.

I do have the application building without the msi flag set to `true`, to an installable windows `setup.exe`, which is great, but we do want the `.msi` as well.

Build task looks like this:
```
"build": {
    "asar": false,
    "win": {
      "msi": true
    },
    "osx": {
      "title": "Test Title",
      "target": "dmg",
      "icon": "src/icon.icns",
      "background": "src/img/bg.png",
      "contents": [
        {
          "x": 448,
          "y": 344,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 192,
          "y": 344,
          "type": "file",
          "path": "appPath/macApp.app"
        }
      ]
    }
  },
  "directories": {
    "buildResources": "dist/web/",
    "app": "./dist/web"
  }
```

**Comment by develar** [comment]
It is our bug. Are you sure that you want msi — https://github.com/electron-userland/electron-builder/issues/366#issuecomment-222430275 ?

**Comment by skewis6** [comment]
Yes, an MSI is pretty essential to the delivery of the application unfortunately!

**Comment by develar** [comment]
@skewis6 Will be fixed soon.

**Comment by develar** [comment]
As always *** Squirrel.Windows masks real exception :( Fixed
