### ISSUE TITLE
Can electron-builder go back to using the npm version of electron-osx-sign?

### ISSUE THREAD

**Issue by sangeeth96** [electron-userland/electron-builder#4854]
There seems to be a lot of issues related to publishing to MAS and codesigning in general. And it doesn't seem to help that this repo is using a vendored version of electron-osx-sign. I understand this was done in the past to patch some issues in electron-osx-sign but is it possible to use the actual version from npm now and removed the vendored dep? It can help identify issues faster and have fixes available for either users.

CC @sethlu

**Comment by wgcv** [comment]
Please 🙏 this is stoping to update apps in the App Store !
