### ISSUE TITLE
how can i disable auto install when app normal quit

### ISSUE THREAD

**Issue by FindChenLinJie** [electron-userland/electron-builder#4857]
* **Version**: 

* **Electron Version**: 4.0.2
* **Electron Type (current, beta, nightly)**: current

electron-updater : 4.2.5

* **Target**: macOS

**Comment by kevinlinv** [comment]
I don't think there is an API to achieve that on `macOS`. The existing configuration on `electron-updater` is documented to only work on `windows` or `linux` target.

https://www.electron.build/auto-update
<img width="756" alt="image" src="https://user-images.githubusercontent.com/44967897/78627055-e2febf80-78d3-11ea-9550-c1af760646c0.png">
