### ISSUE TITLE
'/tmp' is not owned by you, refusing to create a configuration directory there                      [31mcommand[0m=wine /tmp/.cache/electron-builder/winCodeSign/winCodeSign-2.5.0/rcedit-ia32.exe

### ISSUE THREAD

**Issue by navjot-bhullar** [electron-userland/electron-builder#4858]
* **Version**: 

* **Electron Version**:7.1.7
* **Electron builder Version**:21.2.0
* **Node**:v12.14.0
* **Electron Type (current, beta, nightly)**:

* **Target**: target for window on Linux

**Comment by shrinidhi111** [comment]
Check the read/write permissions of /tmp folder. If there are no write permissions for your user you can add it with chmod -R

`sudo chmod -R 777 /tmp`

**Comment by navjot-bhullar** [comment]
I updated permission in docker image but nothing work
