### ISSUE TITLE
Error: ditto: Couldn't read PKZip signature

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#486]
I am code signing from an OSX build server (Jenkins) and am getting this error whenever my app tries to use autoUpdater to update itself, on OSX. I am uploading both the `-mac.zip` and `.dmg` to Github. I download one of my `.dmg` files, install it, then open it, and get this error. Did I have to export the certificate in my npm script in order for it to work?

**Comment by develar** [comment]
> Did I have to export the certificate in my npm script in order for it to work?

Do you mean that problem is that your app is not signed correctly? Do you see "Signing ..." in your build log? Use https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12 to check app.

**Comment by mzmousa** [comment]
I _do_ see "signing..." in my build log. I used that app to check, and my app is signed correctly. Could there be any other reason for this? :(

**Comment by develar** [comment]
Checked – update works for my app. So, it is not an electron-builder regression issue.

**Comment by mzmousa** [comment]
Okay, it ended up working for some reason after I restarted my release server. May I ask what you're using for your release server for your app? I'm using Nuts... Did you come across better alternatives (from your experience)?

**Comment by MarshallOfSound** [comment]
@mzmousa Nut's caches resources locally, so if you changed the zip file nuts will not fetch the new one until it is restarted

**Comment by mzmousa** [comment]
@MarshallOfSound Damn...if I need to frequently restart the sever, that will be problematic. I'll either try to figure out how to clear the Nuts cache or I'll just make sure my windows builds are perfect :laughing:

**Comment by MarshallOfSound** [comment]
Well... Yeah... In theory you shouldn't be uploading bad builds 😕 

You can change nuts to proxy to a public GitHub releases section if that's what you want?  Then you don't need to worry about it's internal cache,

**Comment by develar** [comment]
I use nuts and restart server every release ;) See recommended servers https://github.com/electron/electron/blob/master/docs/api/auto-updater.md You can try https://github.com/Aluxian/squirrel-updates-server

**Comment by develar** [comment]
> Did you come across better alternative

For now I have no time to try — nuts works after restart.

**Comment by mzmousa** [comment]
@MarshallOfSound could you elaborate on the public releases thing and not storing internal caches? Or where I could read about that?

**Comment by develar** [comment]
Nuts doesn't just redirect requests to GitHub to support private github repositories. If your repo is public, I think https://github.com/Aluxian/squirrel-updates-server is a better solution.

**Comment by MarshallOfSound** [comment]
@mzmousa If you store your assets in a public GitHub repo you can set environment variables to tell Nuts to directly proxy requests

https://github.com/GitbookIO/nuts/blob/master/bin/web.js#L28

**Comment by apurvaSynerzip** [comment]
I am using private github repository for keeping my releases and for auto-update feature.
I am getting following issue:
```
[13:12:2018][19:47:55:187]New version 1.3.0 has been downloaded to /Users/Library/Application Support/Caches/project1-updater/pending/update.zip
[13:12:2018][19:47:55:236]/ requested
[13:12:2018][19:47:55:242]/1544710675192-8651.zip requested
[13:12:2018][19:47:55:242]/1544710675192-8651.zip requested by Squirrel.Mac, pipe /Users/Library/Application Support/Caches/project1-updater/pending/update.zip
[13:12:2018][19:47:55:673]Error: ditto: Couldn't read PKZip signature

[13:12:2018][19:47:55:674]Error: Error: ditto: Couldn't read PKZip signature
[13:12:2018][19:47:55:674]Error: ditto: Couldn't read PKZip signature

[13:12:2018][19:48:00:541]Proxy server for native Squirrel.Mac is closed (was started to download https://api.github.com/repos/Jarfus/project1/releases/assets/10112663)
```

**Comment by rayisooo** [comment]
did anybody find a fix im getting this error?
