### ISSUE TITLE
linux pacman missing dependency libappindicator-sharp

### ISSUE THREAD

**Issue by hei-pa** [electron-userland/electron-builder#4860]
* **Version**: 22.4.1

* **Electron Version**: 8.2.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux->pacman

The build is running fine and the `<package>.pacman` file is generated. For some reason the pacman file has a dependency that is no longer present on arch.

**libappindicator-sharp**

```
Name            : xxx
Version         : 0.0.0-1
Description     : None
Architecture    : x86_64
URL             : xxx
Licenses        : unknown
Groups          : default
Provides        : None
Depends On      : c-ares  ffmpeg  gtk3  http-parser  libevent  libvpx  libxslt  libxss  minizip
                  nss  re2  snappy  libnotify  libappindicator-gtk3  libappindicator-sharp
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Compressed Size : 49.46 MiB
Installed Size  : 197.86 MiB
Packager        : xxx
Build Date      : Tue Apr 7 21:37:14 2020
Install Script  : Yes
Validated By    : None
Signatures      : None
```

It was working yesterday, so i think this is a really new change.

**Comment by ruettenm** [comment]
I’ve the same issue for my builds.

**Comment by vladimiry** [comment]
https://github.com/develar/app-builder/pull/29

**Comment by vladimiry** [comment]
Adding `--assume-installed libappindicator-sharp` to pacman install command is a workaround.

**Comment by hovancik** [comment]
Still relevant. Still relevant. https://github.com/hovancik/stretchly/issues/616

**Comment by hovancik** [comment]
Ah, okay, thanks ;]This should be closed, then.
