### ISSUE TITLE
The documentation is very hard to work with

### ISSUE THREAD

**Issue by Serkonda** [electron-userland/electron-builder#4864]
In the docs I miss some more examples how the config would look like as JSON or YAML, as I had to look up other configs on GitHub before I exactly knew what to do.

**Comment by b-zurg** [comment]
I agree.  The documentation has the information but there's a lot that exists in issues and could be added to the documentation. 

@develar is there a documentation repo we could contribute to?  A setup with a doc repo and something like gitbook, [docsify](https://docsify.js.org/#/), [docusaurus](https://v2.docusaurus.io/)

I would be more than happy to assist with setting this up.   I think the community would be very interested in making this project as easy to use as possible and ease of documentation is huge for that :)
