### ISSUE TITLE
checkForUpdates doesn't get skipped when running unpackaged app.

### ISSUE THREAD

**Issue by futurelucas4502** [electron-userland/electron-builder#4865]
* **Electron Builder Version**: 22.3.2

* **Electron Version**: 8.0.2
* **Electron Type (current, beta, nightly)**: Current

* **Electron Updater Version**: 4.2.2

* **Target**: Windows NSIS

I have noticed that when using checkForUpdatesAndNotify in electron-updater it will give me this message when running the program when its not packaged:

> Skip checkForUpdatesAndNotify because application is not packed

However, when using checkForUpdates it doesn't have the same behavior and instead gives me a load of warnings as it doesnt skip checkForUpdates:

> 21:53:19.363 > Checking for update

> 21:53:21.904 > Error: Error: ENOENT: no such file or directory, open 'C:\Users\lucas_hs06s21\Documents\management-console\dev-app-update.yml'

> 21:53:21.987 > Error in auto-updater. Error: ENOENT: no such file or directory, open 'C:\Users\lucas_hs06s21\Documents\management-console\dev-app-update.yml'

> (node:19688) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\lucas_hs06s21\Documents\management-console\dev-app-update.yml'

> (node:19688) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\lucas_hs06s21\Documents\management-console\dev-app-update.yml'

> (node:19688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

> (node:19688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

> (node:19688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> (node:19688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Therefore could the same behavior used in checkForUpdatesAndNotify be used in checkForUpdates to avoid this issue and prevent the program from exiting automatically in future versions of node

**Comment by sergio9929** [comment]
same here

**Comment by futurelucas4502** [comment]
again this is still relevant

**Comment by JayCuevas** [comment]
Would just checking if you're in a development environment work? 
I only enable updates when in a production environment.
For example:
```js
const isDev = require('electron-is-dev');

if (!isDev) {
   autoUpdater.checkForUpdatesAndNotify();
}
```

For checking if the app is portable on windows, I check the `PORTABLE_EXECUTABLE_DIR` environment variable referenced [here](https://github.com/electron-userland/electron-builder/issues/3282#issuecomment-416460791)
