### ISSUE TITLE
electron-builder + notarize = Status Code: 2 Message: Package Invalid 

### ISSUE THREAD

**Issue by 020890** [electron-userland/electron-builder#4868]
-- Which version of electron-builder are you using? --

"electron-builder": "~22.4.1",
"electron-notarize": "~0.3.0",

-- Which version of electron are you using? --

"electron": "~8.2.1",

-- For which target are you building for? --

"target": "mas",
"type": "distribution",

-- Enter your issue details below this comment. --

I tried to make mas production build for app store, and few days ago I am started to get errors from notarize process, I am using electron-notarize with afterSign in package.json.

-- Problem details. --

Status Code: 2
Message: Package Invalid

Logs for apple notarize:
```
"status": "Invalid",
"statusSummary": "Archive contains critical validation errors",
"statusCode": 4000,
"issues": [
    {
      "severity": "error",
      "code": null,
      "message": "Embedded entitlements are invalid: syntax error near line 1",
    }
  ]
```

I checked apple docs:

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3561456

and tried to validate app that I got before notarize process with command:

> % codesign -d --entitlements :- <path to signed .app>

and I see bplist00 in command response

From apple article: 
_If the output of this command contains the text bplist00, the executable has a binary property list, which the notary service will reject with an error message like: Embedded entitlements are invalid: syntax error near line 1_

I am not sure for now: this is problem of new apple notarize rules & current electron-builder or I missed to do smth. with entitlements?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.application-groups</key>
	<string>[team_id_here]</string>
	<key>com.apple.security.cs.allow-dyld-environment-variables</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-write</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.print</key>
	<true/>
</dict>
</plist>
```

I am also used cli commands to covert & validate build/entitlements.* and response that files are correct
> % plutil -convert xml1 <Project_Name.entitlements>
> % plutil -lint <Project_Name.entitlements>

Any idea what's can be a reason of the problem?

**Comment by jpsilva** [comment]
I'm experiencing the same issue using Electron v4.2.12 and dmg, pkg and zip targets. The Apple docs are misnamed, since they give no instruction on how to resolve the bplist00 issue. `plutil` isn't any help for me either.

**Comment by jpsilva** [comment]
I had the same problem with dmg, pkg and zip targets. The solution was to remove the `com.apple.security.app-sandbox` entitlement. It took days of digging to figure that out.

**Comment by wolfoo2931** [comment]
I'm running in the same problem. 
I've read it is required to add app-sandbox in order to submit the app to the mac app store?
If this is true, removing those entitlements might not be an option?

**Comment by openspeedtest** [comment]
> I'm running in the same problem.
> I've read it is required to add app-sandbox in order to submit the app to the mac app store?
> If this is true, removing those entitlements might not be an option?

The app for uploading to Apple App Store, doesn’t need any notarization!
https://stephen-chen.medium.com/notarize-electron-app-for-macos-catalina-10-15-d994e29dfe82
