### ISSUE TITLE
skip checkForUpdates when target: portable

### ISSUE THREAD

**Issue by sergio9929** [electron-userland/electron-builder#4869]
* **Version**: 22.4.1

* **Electron Version**: 8.2.0

* **Electron Updater**: 4.2.5

* **Target**: portable

Doesn't skip auto update when opening the portable version

**Comment by futurelucas4502** [comment]
why have u made a duplicate of my post with less detail after commenting on mine there's literally no point

**Comment by futurelucas4502** [comment]
Duplicate of my post: https://github.com/electron-userland/electron-builder/issues/4865

**Comment by sergio9929** [comment]
> why have u made a duplicate of my post with less detail after commenting on mine there's literally no point

No, this isn't the same problem.
I have 2 different problems:
1- Yours.
2-I'm tryig to make a portable version of my app, but when I open it the electron updater isn´t disabled and installs the newer not portable version of the app.
