### ISSUE TITLE
NSIS Gif Spinner

### ISSUE THREAD

**Issue by kdumontnu** [electron-userland/electron-builder#4874]
* **Version**: 22.3.2

* **Electron Version**: 8.2.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: x64

I've been deciding which installer to use for my latest electron app release, and found that there seems to be a pretty big shift from squirrel to NSIS support for windows. I've enjoyed using squirrel in the past, but the lack of current maintenance is concerning. 

The biggest thing I'm currently missing from squirrel installer was how easy it was to use a custom spinner during installation. The default loading bar for NSIS feels quite dated at this point, and doesn't provide the most appealing user experience in my opinion.

Has anyone successfully been able to replace the default loading bar with a gif spinner similar to the [squirrel default](https://github.com/electron/windows-installer/blob/master/resources/install-spinner.gif)? My assumption is that I'll have to dig into [custom nsis](https://www.electron.build/configuration/nsis#custom-nsis-script) code. I wanted to check if anyone has a good resource for something like this, and also suggest this is something that could be added as an electron-builder config option.

**Comment by d-w-johnson** [comment]
I agree, I would love to have this option for my application!
