### ISSUE TITLE
Windows NSIS uninstall fails when built from MacOS Catalina

### ISSUE THREAD

**Issue by fkoehler42** [electron-userland/electron-builder#4875]
* **Version**: 22.4.1 
* **Electron Version**: 7.2.1
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater Version**: 4.2.5

* **Target**: Windows NSIS (tested on Windows 7 and 10)

I recently switched to Mac OS 10.15 (Catalina) which doesn't support 32 bit executables anymore. Doing so, I also upgraded electron-builder to the latest version so Wine isn't used.

Since then, my Windows NSIS uninstaller seems broken. The build process works as expected, no error/warning raised. However, after the first install of my app which works well, I face a NSIS error when I try to uninstall. This is the common "Installer integrity check has failed" error. When I try to either manually reinstall the app or update it using electron-updater, the installer progress bar stays stuck at around 40%.

My build config is the default one. I tried some tweaks suggested on similar issues but none of them helped. If I build my app from a previous MacOS version the issue disappears.

**Comment by shrinidhi111** [comment]
I had to downgrade to `21.2.0` to fix my issue https://github.com/electron-userland/electron-builder/issues/4878

**Comment by fkoehler42** [comment]
Unfortunately this issue seems different: I got no warning from Windows Defender. I tried to downgrade electron-builder to `21.x`, as well as turning off the "Windows Defender real-time protection". (Issue appears also on Windows 7 BTW)

**Comment by Snake231088** [comment]
Same issue!
Any solution or workaround?

**Comment by BusinessDuck** [comment]
![image](https://user-images.githubusercontent.com/10143411/79636961-1ff46d00-8184-11ea-8c5f-3716f5090a4c.png)
Affected by this reg key. Clean it and problem is gone. I think something wrong with nsis templates.

**Comment by BusinessDuck** [comment]
Hack solution: 
```json
"nsis": {
      "guid": "MyAppName",
      "include": "build/installer.nsh",
    },
```

> build/installe.nsh listing
```
!macro customInit
    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\TamTam"
!macroend

```

**Comment by BusinessDuck** [comment]
Hack solution: 
```json
"nsis": {
      "guid": "MyAppName",
      "include": "build/installer.nsh",
    },
```

> build/installer.nsh listing
```
!macro customInit
    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\MyAppName"
!macroend

```

**Comment by fkoehler42** [comment]
@BusinessDuck I tried to remove the `UninstallString` key but doing so Windows thinks my app has already been uninstalled so the program is removed from the control panel without being uninstalled

**Comment by BusinessDuck** [comment]
use `!macro customUnInstall` instead

**Comment by pavel-propeople** [comment]
Building with MacOS Catalina 10.15.4 and experiencing the same issues on Windows.
Custom removal in nsis scripts didn't worked at all (was not triggered).
When building the installer from Windows machine everything works well...

**Comment by matt-cree-instil** [comment]
I'm also experiencing the same issues.

**Comment by andywang646691** [comment]
This problem exists in many electron-builder versions, and has not been fixed until now. just try a hack, and modify electron-builder source code: 
![image](https://user-images.githubusercontent.com/19781389/81633815-34a0e980-9440-11ea-981f-3f1ffc69afd8.png)
comment code and throw error so that electron-builer can builds installer by parallels vm.

**Comment by ouzhou** [comment]
same issue

**Comment by simple-YoungBadBoy** [comment]
Same issue!
Any solution or workaround?

**Comment by matt-cree-instil** [comment]
Build your Windows installer in a docker container. Their docs mention how
to do this.

**Comment by aschmid** [comment]
same issue here. :(

**Comment by Ali-Baker** [comment]
same issue

**Comment by gentlecoder** [comment]
same here

**Comment by lauritzen** [comment]
Same here. I worked around it by building "on Windows" with the `electronuserland/builder:wine` Docker image on MacOS, more info here: https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine. The script I'm using:
```
docker run --rm \
       --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
       --env ELECTRON_CACHE="/root/.cache/electron" \
       --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
       -v ${PWD}:/project \
       -v ${PWD}/docker-node-modules:/project/node_modules \
       -v ~/.cache/electron:/root/.cache/electron \
       -v ~/.cache/electron-builder:/root/.cache/electron-builder \
       electronuserland/builder:wine \
       /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn electron:publish"
```

**Comment by olegdolenchuk** [comment]
same issue

**Comment by takuyabz** [comment]
same issue

**Comment by takuyabz** [comment]
This issue cause is building on mac.
You should build on a windows environment.
I installed the parallels desktop on Mac, and build it for windows.
Then I succeeded uninstall on windows.
please try this solution, thank you.

**Comment by LukeXF** [comment]
Same issue, can't understand why this is such a big issue

**Comment by tjx666** [comment]
Still exits....

**Comment by mmaietta** [comment]
This is the recommended solution: https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine

**Comment by Ali-Baker** [comment]
Still exists. It's best to use Windows OS, VM or docker to make the build

**Comment by adamcjm** [comment]
I find a way to solve this problem:

1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**

2. And then rebuild and install the application to windows, and try to uninstall or update.

*these two step fixed my problem.*

**Comment by adamcjm** [comment]
> Still exists. It's best to use Windows OS, VM or docker to make the build

I find a way to solve this problem:

1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**

2. And then rebuild and install the application to windows, and try to uninstall or update.

*these two step fixed my problem.*

**Comment by adamcjm** [comment]
> Still exits....

I find a way to solve this problem:

1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**

2. And then rebuild and install the application to windows, and try to uninstall or update.

*these two step fixed my problem.*

**Comment by adamcjm** [comment]
> Same issue, can't understand why this is such a big issue

I find a way to solve this problem:

1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**

2. And then rebuild and install the application to windows, and try to uninstall or update.

*these two step fixed my problem.*

**Comment by ErnestLeung52** [comment]
> I find a way to solve this problem:
> 
> 1. **You can try to add  a line code with the content `CRCCheck off` to bottom of the file `node_modules/app-builder-lib/templates/nsis/common.nsh`.**
> 2. And then rebuild and install the application to windows, and try to uninstall or update.
> 
> _these two step fixed my problem._

This works for me!!! Thank you!

**Comment by itsdouges** [comment]
When you turn CRCCheck off is there any unintended consequences of that? Does code signing become at risk?

**Comment by stefanroeck** [comment]
Another workaround is to build a portable by running `electron-builder --win portable` which doesn't need any install/uninstall at all.

**Comment by kkHAIKE** [comment]
Is there no elegant solution to this problem? It feels like the underlying principle isn't even clear, and using `CRCCheck off `seems too dirty

i'm certain this issue is related to the following code, ~~although I can't make any sense of what it's actually doing~~.
https://github.com/electron-userland/electron-builder/blob/e97982f06f81c53deb7ffebfec1b2b995b2cd290/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L423-L426

It looks like a hack to address Wine's inability to run in non-32-bit environments, but now Wine can execute 32-bit programs via WOW64.
https://github.com/electron-userland/electron-builder/issues/4305
