### ISSUE TITLE
Potential Trojan in electron builder uninstaller.

### ISSUE THREAD

**Issue by shrinidhi111** [electron-userland/electron-builder#4878]
* **Version**: 
22.4.1

* **Electron Version**: 8.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS

There seems to be a code signing issue in Windows while using pfx certificate as described in this issue https://github.com/electron-userland/electron-builder/issues/4383

Apparently it is only a problem when using electron-builder version `22.4.1`.

What's more, only in this version do I get a Windows Security Notification whenever I try to build. It seems Windows is finding a Trojan and therefore interferes with the signing process. Not sure when is a false positive or not. Or only with my system or not.

But I do not get any such errors with the previous major build.

![trojan](https://user-images.githubusercontent.com/10372299/79353960-674ae580-7f59-11ea-9ce6-b6fefbb7323d.png)

**Comment by b-zurg** [comment]
Could you run a scan on virustotal and post the results here? https://www.virustotal.com/gui/home

This would provide some pretty critical information about whether this is legit or a false positive.

**Comment by develar** [comment]
False positive, until MS Defender is not fixed, NSIS version was reverted. Please try 22.5.1
