### ISSUE TITLE
path to the script for web worker

### ISSUE THREAD

**Issue by navratill** [electron-userland/electron-builder#4884]
* **Version**:  22.5.1

* **Electron Version**: 7.1.9
* **Electron Type (current, beta, nightly)**: current

* **Target**:  MacOS (catalina)

Hello, I am building electron application, where I am using Web Workers:
new Worker(`${__dirname}/build.js`);

but when I run the electron app, its throwing the error:
Error: Cannot find module '...app/Contents/Resources/app.asar/dist/workers/build.js'

When I set asar=false it is working, but when the resources are inside of asar (I would appreciate it), it doesn't.

Thank you very much

**Comment by prvnsmpth** [comment]
I'm running into the same issue as well. If there was a way to exclude a few files from app.asar (but still package the rest), it would be a good solution.

**Comment by prvnsmpth** [comment]
Looks like there is a property that let's us do just that: `asarUnpack`. 

For anyone landing up here trying to find a solution to this issue, with the following config, the script will be placed in app.asar.unpacked:
`
"build": {
  "appId": "com.myapp",
  "files": ...,
  "asarUnpack": "path/to/worker/file.js" 
  ...
}
`
The documentation for `asarUnpack` is a bit misleading as well (#4641), it would have you think that it needs to be specified under the `asar` property, but it is actually a top-level config.
