### ISSUE TITLE
Useless download (electron source duplicate) when building

### ISSUE THREAD

**Issue by zNoobs** [electron-userland/electron-builder#4885]
* **Version**: 22.5.1
* **Electron Version**: 8.0.0
* **Electron Type (current, beta, nightly)**: current
* **Target**: win portable
* **OS**: Windows 7 64-bit

I enabled DEBUG, then I installed electron@8.0.0 (with --save-dev and ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/).

Here some parts of my package.json:
```
  "engines": {
    "node": ">=12.16.2"
  },
  "devDependencies": {
    "electron": "^8.0.0",
    "electron-builder": "^22.5.1"
  },
...
  "build": {
    ...,
    "win": {
      "target": "portable"
    },
```

Then when I build for Windows:
`electron-builder build --win`

I can see in the debug logs that it is downloading **AGAIN** electron@8.0.0:
```
 • computing effective URL  initialUrl=http://npm.taobao.org/mirrors/electron/8.0.0/electron-v8.0.0-win32-x64.zip currentUrl=https://cdn.npm.taobao.org/dist/electron/8.0.0/electron-v8.0.0-win32-x64.zip
  • downloading     url=http://npm.taobao.org/mirrors/electron/8.0.0/electron-v8.0.0-win32-x64.zip length=70590321 contentType=application/zip
  • downloading     url=http://npm.taobao.org/mirrors/electron/8.0.0/electron-v8.0.0-win32-x64.zip size=71 MB parts=8
...
  • downloaded      url=http://npm.taobao.org/mirrors/electron/8.0.0/electron-v8.0.0-win32-x64.zip duration=1m45.303s
```

Why is it re-downloading electron source again? It's such a waste of time and data, for this example it was less than 2 minutes because I used the mirror, but with the original source (aws servers) it takes hours sometimes.

**Comment by fengmk2** [comment]
fixed on https://github.com/cnpm/cnpmjs.org/issues/1539#issuecomment-619536610

```bash
ELECTRON_BUILDER_BINARIES_MIRROR=https://npm.taobao.org/mirrors/electron-builder-binaries/ \
  ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ electron-builder --win

```
