### ISSUE TITLE
Windows 10 - Windows Defender alert with Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by GregorBiswanger** [electron-userland/electron-builder#4886]
* **Version**: 
22.5.1

* **Electron Version**:
8.2.3

* **electron-updater Version**:
4.2.5

* **Target**: 
Windows 10.0.18363.778

I used the `npx electron-builder` command to build windows binaries. Windows Defender alerts the following:

Trojan:Win32/Wacatac.B!ml
in file: C:\Users\Gregor\AppData\Roaming\npm-cache\_npx\25688\node_modules\.staging\app-builder-bin-8e7fbe12\win\ia32\app-builder.exe

**Comment by greggman** [comment]
yea, same issue

`npm install --save-dev electron-builder@latest`

![コメント 2020-04-19 180329](https://user-images.githubusercontent.com/234804/79683884-3d9b0280-8268-11ea-862c-a43c06ff5921.jpg)

**Comment by develar** [comment]
```
develar@develar ~ % sha256sum /Volumes/data/Downloads/app-builder-bin-3.5.6/package/win/ia32/app-builder.exe
865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f  /Volumes/data/Downloads/app-builder-bin-3.5.6/package/win/ia32/app-builder.exe
develar@develar ~ % sha256sum /Volumes/data/Documents/app-builder/app-builder-bin/win/ia32/app-builder\ copy.exe 
865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f  /Volumes/data/Documents/app-builder/app-builder-bin/win/ia32/app-builder copy.exe
develar@develar ~ % 
```

NPM version equals to locally build executable. `865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f`.

So, false positive. I will rebuild with a new unreleased changes and publish a new version, maybe it will help.

**Comment by fedot** [comment]
I'm not sure this is correct to just assume it's a false positive...

Here are virustotal results for [865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f](https://www.virustotal.com/gui/file/865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f/details)

If I build the binary myself I'm getting [d839eb1a2ff1ed4e65489acbfeebac3093dfd26508692486e145b37c7876a496 ](https://www.virustotal.com/gui/file/d839eb1a2ff1ed4e65489acbfeebac3093dfd26508692486e145b37c7876a496/details) as the checksum and different set of detections (that looks more like previous versions published)
