### ISSUE TITLE
Quotes in updater path

### ISSUE THREAD

**Issue by Laruxo** [electron-userland/electron-builder#4889]
* **Version**: since `electron-updater` 4.2.0

* **Target**: Windows

Since [this commit](https://github.com/electron-userland/electron-builder/commit/dead150769463adbff38b19e9099df6547db0e24) quotes in destinationFile or packageFile throw an error during update. In windows it is possible to have account named `Jesse's` or `Joy's`, which results in download path being `C:\Users\Jesse's\AppData\Local\myApp-updater`.

I am not sure why this restriction was introduced, but it is obvious it should not crash on update for some users.

**Comment by Laruxo** [comment]
Related to https://github.com/electron-userland/electron-builder/issues/4701

**Comment by rajivshah3** [comment]
This was an incomplete fix for a vulnerability. Your best option is to use `patch-package` to revert this change if your users are running into issues. To patch the vulnerability, I think [this](https://github.com/iotaledger/trinity-wallet/blob/cf6e1099de10452a43cf59b144ff759788e77c72/src/desktop/patches/electron-updater%2B4.0.14.patch) is more appropriate.
