### ISSUE TITLE
Invalid version format

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#489]
Trying to use a version such as this:

`'0.1.2.beta' is not a valid version string 
`
Why can I not use my internal versioning format?

**Comment by MarshallOfSound** [comment]
Things like the auto update module and a whole lot of other code (not just in electron-builder) expects a semver string.

**Comment by develar** [comment]
Relates to #451 (nuget doesn't support all semver valid versions in addition).

**Comment by Bohooslav** [comment]
But it was working yet recently!
