### ISSUE TITLE
electron-updater: can't get feed URL anymore?

### ISSUE THREAD

**Issue by adam-lynch** [electron-userland/electron-builder#4894]
* **Version**: 22.4.1

* **Electron Version**: 8.2.1
* **Electron Type (current, beta, nightly)**: current

* **electron-updater version**: 4.2.5

* **Target**: Mac

`getFeedUrl` is in the [documentation](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+getFeedURL) and not marked as deprecated but when called, it returns `Deprecated. Do not use it.`

1. The documentation should be updated I assume.
2. Is there any way to get the feed URL? Or should we read `resources/app-update.yml` (assuming `setFeedURL` hasn't been called elsewhere)?

Related: https://github.com/electron-userland/electron-builder/issues/3259

**Comment by adam-lynch** [comment]
FYI this isn't as urgent for me anymore; we changed something around auto-update URLs. But it would be good to know for in future / it might help others.

**Comment by adam-lynch** [comment]
Yes

**Comment by kariharju** [comment]
Trying to setup a way to test auto-updates before actually releasing to production I would REALLY like to set the target url dynamically in code. Ran into `setFeedURL` and `getFeedURL` which seem to be the only way.

According to documentation these should be fine but when using these are now just deprecated without replacements.
..errr... what am I not getting here??

**Comment by adam-lynch** [comment]
Yes

**Comment by amilcarbg** [comment]
A sexta, 11/09/2020, 15:21, stale[bot] <notifications@github.com> escreveu:

**Comment by tance77** [comment]
This is still an issue.

**Comment by Denz1994** [comment]
Just noting this is still an issue. I get a message reading `Deprecated. Do not use it.`

```
"electron": "11.4.0",
"electron-builder": "22.9.1",
"electron-updater": "4.3.5"
```

**Comment by mikekok** [comment]
Still not working as of today.

**Comment by Cupcakus** [comment]
Still not working

**Comment by sanjai0py** [comment]
It's still not working. At least please provide another way to achieve this!
