### ISSUE TITLE
can you add supports for makensis INPUTCHARSET OUTPUTCHARSET?

### ISSUE THREAD

**Issue by hdfeng265** [electron-userland/electron-builder#4898]
* **Version**: app-builder-lib@22.4.1@app-builder-lib
* **Electron Version**: 5.0.4
* **Target**: build

My windows charset is gbk, when i use makensis.exe to compile utf-8 nsis script,  i got a  "Bad text encoding" error. 
![image](https://user-images.githubusercontent.com/17950041/80283187-60398980-8748-11ea-9225-b206fe97d12b.png)
Makensis.exe has option to specify input charset, but electron-builder seem doesn't have this option.
Can you add supports for makensis INPUTCHARSET OUTPUTCHARSET? Thanks!!

Temporarily, i modified "node_modules/electron-builder/node_modules/app-builder-lib/out/targets/nsis/NsisTarget.js" and "NsisTarget.js.map" by insert " args.push("-INPUTCHARSET", "UTF8", "-OUTPUTCHARSET", "UTF8");" into line 724, to support utf-8 nsis script.
![image](https://user-images.githubusercontent.com/17950041/80283237-9d9e1700-8748-11ea-89f5-90a2150c0c5b.png)
![image](https://user-images.githubusercontent.com/17950041/80283251-b9a1b880-8748-11ea-8bfd-dce8292db289.png)

**Comment by woxixiulayin** [comment]
same problem here.We have to use custom nsis script in electorn-builder, but got  "Bad text encoding" error.We have to use INPUTCHARSET option with makensis. Any fix for that?

**Comment by sohobloo** [comment]
These is useful to fix custom scripts encoding issues. Why closed.

**Comment by mmaietta** [comment]
Is there a particular reason why we wouldn't want the input and output charsets to be utf8? Seems like those args would be beneficial to just use by default.
