### ISSUE TITLE
can't find module 'auto-updater'

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#490]
Why would I get this error?

It happens on this line:

```
    if (isDevelopment || process.platform == "linux" || !electron.autoUpdater) {
      return;
    }

```
(and yes, it's a signed app, via electron-builder).

```
ErrorCannot find module '../auto-updater'Error: Cannot find module '../auto-updater'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.get [as autoUpdater] (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:17:14)
    at Object.App.autoUpdate (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/app.asar/main.js:108:66)
    at EventEmitter.<anonymous> (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/app.asar/main.js:1267:7)
    at emitOne (events.js:96:13)App.app
    at EventEmitter.emit (events.js:188:7)module.js:440
    throw err;
    ^
```

**Comment by kunkinkan** [comment]
- disabled asar, same issue. 
- checked resources/app/package.json, yes it is correct package json.
"main" = "./main.js"

Same issue. (actually it fails on 'dialog' module) in previous case too, i just added some extra logging to find out what the real reason was.

**Comment by kunkinkan** [comment]
when I remove the autoupdate code, the app runs fine.

**Comment by kunkinkan** [comment]
actually, no, doesn't run fine, seems like some other modules also don't work as intended. (shell)

**Comment by kunkinkan** [comment]
Here's my build package.json: 

```
{
  "devDependencies": {
    "electron-builder": "^4.2.0",
    "electron-prebuilt": "^1.2.1"
  },
  "build": {
    "app-bundle-id": "com.app.my",
    "iconUrl": "http://eatodo.s3.amazonaws.com/icon.ico",
    "extraResources": [
      "IRI"
    ],
    "osx": {
      "contents": [
        {
          "x": 375,
          "y": 130,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 130,
          "type": "file"
        }
      ]
    },
    "win": {}
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron ./app --enable-logging",
    "dev": "export NODE_ENV=development || set NODE_ENV=development && npm run start",
    "predist": "rm -rf dist/*",
    "dist": "build --win --osx --linux --x64 && npm run dist:win32 && npm run dist:lin32",
    "dist:win32": "build --win --ia32",
    "dist:lin32": "build --linux --ia32",
    "prerelease:osx": "mkdirp release/osx",
    "release:osx": "cp -rv dist/osx/*.{dmg,zip} release/osx && PACKAGE_VERSION=$(cat app/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && printf $PACKAGE_VERSION >> ./release/osx/VERSION",
    "prerelease:win32": "mkdirp release/win32",
    "release:win32": "cp -v dist/win-ia32/{RELEASES,*.nupkg,*.exe} release/win32",
    "prerelease:win64": "mkdirp release/win64",
    "release:win64": "cp -v dist/win/{RELEASES,*.nupkg,*.exe} release/win64",
    "prerelease:lin": "mkdirp release/lin/",
    "release:lin": "cp -v dist/*.deb release/lin",
    "prerelease": "rm -rf release/*",
    "release": "npm run release:osx && npm run release:win32 && npm run release:win64 && npm run release:lin",
    "deploy": "PACKAGE_VERSION=$(cat app/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && aws s3 sync release/ s3://iothingstest/updates/$PACKAGE_VERSION/ --acl public-read && aws s3 sync s3://iothingstest/updates/$PACKAGE_VERSION/ s3://iothingstest/updates/latest/ --delete --acl public-read",
    "all": "npm run dist && npm run release && npm run deploy"
  }
}
```

and the app package.json

```
{
  "name": "app",
  "productName": "app",
  "version": “0.1.2”,
  "main": "./main.js",
  "scripts": {
    "start": "electron main.js"
  },
  "devDependencies": {
    "devtron": "^1.1.2"
  },
  "dependencies": {
    "escape-string-regexp": "^1.0.5",
    "follow-redirects": "^0.1.0",
    "fs-extra": "^0.30.0",
    "glob": "^7.0.3",
    "jquery": "^2.2.4"
  }
}

```

**Comment by kunkinkan** [comment]
Getting a different error when building for windows (above was for mac os x):

```
Error: File "../App.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at Object.<anonymous> (/../app/node_modules/electron-builder/src/asarUtil.ts:76:13)

```

**Comment by kunkinkan** [comment]
(Note that for osx 64 bit the app.asar exists).

**Comment by kunkinkan** [comment]
(Perhaps the os x 32 bit issue is something else entirely, since it's the first time I've built 32-bit osx).

**Comment by develar** [comment]
OS X support only 64 bit — you don't need to build OS X ia32.

**Comment by develar** [comment]
Please use electron-builder 5.2.0.

**Comment by kunkinkan** [comment]
@devalar I did update to 5.2.0 today, but error is the same unfortunately.

Regarding os x 32-bit, yes, I didn't want to build for it but built using -owl --x64 --ia32. Perhaps, since no one needs 32-bit, it should just be disabled entirely by electron-builder?

**Comment by kunkinkan** [comment]
There's a similar issue with electron.remote.shell. I use it in renderer.

When I do only npm run start (see package json above), it works fine. But after building and using the .app, I get a similar error "cannot find module shell".

**Comment by develar** [comment]
> Perhaps, since no one needs 32-bit, it should just be disabled entirely by electron-builder?

Bug, fixed. Release will be soon.

> but error is the same unfortunately.

Could you please post current error message? What is the error?

**Comment by develar** [comment]
@kunkinkan Is it possible to send me your app? So, I can just try it?

**Comment by kunkinkan** [comment]
oops sorry i guess electron.shell works just as well. that error is fixed. so only the auto update issue remains.

**Comment by develar** [comment]
Is your app initialised?  `app.on("ready"`?

**Comment by kunkinkan** [comment]
oh yes, 

```
electron.app.on("ready", function() {
  App.initialize();
});

```

call for autoupdate is only made after window had loaded too;

```
electron.ipcMain.on("rendererIsReady", function() {
  App.uiIsReady = true;
  App.autoUpdate();
});
```

**Comment by develar** [comment]
Is `electron.autoUpdater` available in the dev mode? In your code I see `isDevelopment` and, so, code is not executed. i.e. I want to be sure that it works before package. Also, try to set `electron-prebuilt` version to 1.2.2 to match your dev version.

**Comment by kunkinkan** [comment]
Well I had an if isDevelopment, so if I remove that and just do electron ./app indeed it's not working either. But I read that electron.autoUpdate isn't supposed to work without signing, so not sure if that is a normal crash there or not. If not normal, sorry, it seems the issue is not electron-builder then. However I'm not sure what is causing it :-) I did update the dev dependency to electron-prebuilt 1.2.2 also.

**Comment by develar** [comment]
@kunkinkan Please attach full build log.

**Comment by kunkinkan** [comment]
@devalar just found something, if i define 

var autoUpdate = electron.autoUpdater;

at the top, it seems to work. don't even have to use that variable. All other code remains the same. After electron.autoUpdater will not throw an error in the App.autoUpdate() method that is called by my code. Very strange, is there something I'm doing wrong with modules?

**Comment by develar** [comment]
So, it is your code problem?

**Comment by kunkinkan** [comment]
probably yes, i just add the require to the top and it works. Strange, but ok, not your problem :-) sorry!

**Comment by liukun** [comment]
I met this error when I called `app.quit()` before `index.js` loaded.
