### ISSUE TITLE
Building snap with stage packages on CI (question)

### ISSUE THREAD

**Issue by Niquolas** [electron-userland/electron-builder#4903]
* **Version**: 22.5.1

* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux (Snap)

My application is configured to build and publish snaps with an additional stage package configured as follows:

```
"snap": {
      "stagePackages": [
        "default",
        "libglu1-mesa"
      ]
}
```

The [Multi Platform Build](https://www.electron.build/multi-platform-build) docs page states that the following commands must be run to allow this to work:

```
sudo snap install snapcraft --classic
sudo snap install multipass --beta --classic
```

thus my Travis CI configuration looks like this:

```
addons:
      snaps:
        - name: snapcraft
          confinement: classic
        - name: multipass
          confinement: classic
          channel: beta
```

However, when running a build, I receive the following error:

```
Setting target machine to 'amd64'
Launching a VM.
launch failed: multipass socket access denied
Please check that you have read/write permissions to '/var/snap/multipass/common/multipass_socket'
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

Snapcraft's [documentation](https://snapcraft.io/docs/build-options) seems to suggest that using the `--destructive-mode` flag would bypass the need for multipass entirely and resolve the issue, however to the best of my knowledge there isn't an option to do this with electron-builder. I would be grateful for any insight into this.

**Comment by Niquolas** [comment]
This is still relevant, I'd be grateful if anyone could assist.

**Comment by KhushrajRathod** [comment]
Hi, I was stuck with the same issue about 2 days ago. You can set
```
export SNAPCRAFT_BUILD_ENVIRONMENT=host
```
and remove the multipass snap completely

**Comment by adam-lynch** [comment]
While looking into another issue, I discovered `export SNAP_DESTRUCTIVE_MODE="true"` disables multipass too
