### ISSUE TITLE
Auto updater problems on windows

### ISSUE THREAD

**Issue by razvanstatescu** [electron-userland/electron-builder#4908]
* **electron-builder Version**:  ^22.5.1
* **electron-updater Version**:  ^4.3.1

* **Electron Version**: ^8.2.2

* **Target**: Windows

I have a public repo on GitHub where I publish my updates. In the electron app I just use:
`autoUpdater.checkForUpdatesAndNotify();`
When I try to update I get: 

> Cannot parse blockmap "...", error: incorrect header check, raw data: ...

I tried to set 
`"nsis": {
      "differentialPackage": false
    }`
in order to disable the generation of blockmap files. But now I get 

> Cannot download differentially, fallback to full download: Error: Cannot download ".....blockmap", status 404: Not Found

Any idea on how to make this work? Thanks!

**Comment by b-zurg** [comment]
Yeah same issue.

**Comment by codewaseem** [comment]
Same here.

**Comment by harshitsilly** [comment]
@codewaseem @b-zurg  @razvanstatescu  Hi, try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/).. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.

**Comment by undergroundwires** [comment]
Hi, had same issue with `vue-cli-plugin-electron-builder` in a vue + typescript project. And updating `electron-updater` to 4.3.4 ([prerelease](https://github.com/electron-userland/electron-builder/releases/tag/v22.8.0)) solved it for me. The fix is there 😀  Working example: [privacy.sexy](https://github.com/undergroundwires/privacy.sexy)

**Comment by b-zurg** [comment]
On the latest release block maps are working for me again

**Comment by marf** [comment]
We have the exact same problem. Any solutions?

**Comment by harshitsilly** [comment]
hi @marf  u can check this module https://github.com/imjsElectron/electron-differential-updater
