### ISSUE TITLE
what's the win.remoteReleases means

### ISSUE THREAD

**Issue by lzdnku307** [electron-userland/electron-builder#491]
I am not sure what the remoteReleases option exactly means?
`mysite.com/xxx-full.nupkg` or `mysite.com/xxx setup.exe` or `mysite.com/RELEASES`?

**Comment by develar** [comment]
A URL to your existing updates. If given, these will be downloaded to create delta updates

Please see example https://github.com/develar/onshape-desktop-shell/blob/master/package.json#L34

**Comment by mikew** [comment]
That's great for github releases, but how does it work otherwise? Does it take a path to a regular `RELEASES` file? Does it download that file and append the new entries to it? Does it download every previous release? It's really unclear what it does.

**Comment by develar** [comment]
@mikew `remoteReleases` moved to `.build.squirrelWindows` Squirrel.Windows is deprecated — do not use. Use nsis target, please see #529.

**Comment by mikew** [comment]
That just raises more questions, but thanks.
