### ISSUE TITLE
open ******/package.json: file name too long

### ISSUE THREAD

**Issue by daomul** [electron-userland/electron-builder#4913]
* **Version**: 22.5.1

* **Electron Version**:8.2.3
* **Electron Type (current, beta, nightly)**:current

* **Target**: mac

Error reported when I run npm run pack
pack.json
> "pack": "electron-builder --dir",
    "dist": "electron-builder",

 `⨯ open /Users/zerozheng/Documents/work/demo/markdown-notebook/node_modules/react-scripts/node_modules/optimize-css-assets-webpack-plugin/node_modules/cssnano/node_modules/cssnano-preset-default/node_modules/postcss-svgo/node_modules/svgo/node_modules/object.values/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/define-properties/node_modules/object-keys/package.json: file name too long

github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:192
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:95
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:56
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72  
  ⨯ /Users/zerozheng/Documents/work/demo/markdown-notebook/node_modules/_app-builder-bin@3.5.8@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                                       Error: /Users/zerozheng/Documents/work/demo/markdown-notebook/node_modules/_app-builder-bin@3.5.8@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                           at ChildProcess.<anonymous> (/Users/zerozheng/Documents/work/demo/markdown-notebook/node_modules/_builder-util@22.6.0@builder-util/src/util.ts:243:14)
                                                                                                                                                                                           at Object.onceWrapper (events.js:422:26)
                                                                                                                                                                                           at ChildProcess.emit (events.js:315:20)
                                                                                                                                                                                           at maybeClose (internal/child_process.js:1051:16)
                                                                                                                                                                                           at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
`

**Comment by xudafeng** [comment]
same to me

**Comment by xudafeng** [comment]
I solved this problem and installed via npm@6

**Comment by Ankcy** [comment]
@xudafeng via npm@6? my npm ver is 6.14.5, but come the same error, can you help me.?


OKAY  take it away `electron-builder`

  • electron-builder  version=22.6.1 os=19.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build/builder-effective-config.yaml
  ⨯ open /Users/admin/Documents/ws/media_pc/node_modules/@sentry/electron/node_modules/util.promisify/node_modules/object.getownpropertydescriptors/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimright/node_modules/es-abstract/node_modules/string.prototype.trimleft/node_modules/es-abstract/node_modules/object.assign/node_modules/define-properties/node_modules/object-keys/package.json: file name too long
github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:192
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:95
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:56
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72  
  ⨯ /Users/admin/Documents/ws/media_pc/node_modules/_app-builder-bin@3.5.9@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                   Error: /Users/admin/Documents/ws/media_pc/node_modules/_app-builder-bin@3.5.9@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                       at ChildProcess.<anonymous> (/Users/admin/Documents/ws/media_pc/node_modules/_builder-util@22.6.1@builder-util/src/util.ts:243:14)
                                                                                                                                                                       at Object.onceWrapper (events.js:417:26)
                                                                                                                                                                       at ChildProcess.emit (events.js:310:20)
                                                                                                                                                                       at maybeClose (internal/child_process.js:1021:16)
                                                                                                                                                                       at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
