### ISSUE TITLE
ElectronAppAdapter Uncaught TypeError: Cannot read property 'getVersion' of undefined

### ISSUE THREAD

**Issue by agnoam** [electron-userland/electron-builder#4916]
* **Version**: 
4.3.1

* **Electron Version**:
v8.2.4

* **Electron Type (current, beta, nightly)**:
current

Hey,
I'm using this package with my angular electron application [example repo](https://github.com/maximegris/angular-electron).

I have written this angular service:
```
import { Injectable } from '@angular/core';
import { autoUpdater } from 'electron-updater';


@Injectable({ providedIn: 'root' })
export class AppUpdateService {
    constructor() { }

    checkForUpdates() {
        const res = autoUpdater.checkForUpdates()
        console.log(res);
    }
}
```

But when I try this function it throws an exception: 
```
Uncaught TypeError: Cannot read property 'getVersion' of undefined
    at ElectronAppAdapter.get version [as version] (ElectronAppAdapter.js:34)
    at new AppUpdater (AppUpdater.js:232)
    at new BaseUpdater (BaseUpdater.js:20)
    at new NsisUpdater (NsisUpdater.js:126)
    at doLoadAutoUpdater (main.js:129)
    at Object.get [as autoUpdater] (main.js:142)
    at Module../src/app/services/app-update.service.ts (app-update.service.ts:4)
    at __webpack_require__ (bootstrap:79)
```
**Proposal for a fix**:
More thing, I have tried to fix this problem myself, and I found if you change `ElectronAppAdapter` constructor from: `constructor(app = require("electron").app)`,
to this: `constructor(app = require("electron").remote.app)`.
everything fixes.

Any other ideas ?

**Comment by b-zurg** [comment]
Is this code running on the renderer?  That's the only reason why accessing `app` from the remote object would work.

**Comment by agnoam** [comment]
Yes. I'm using the [angular-electron](https://github.com/maximegris/angular-electron) template, and I run it as service

app-update.service.ts:
```
import { Injectable } from '@angular/core';
import { autoUpdater } from 'electron-updater';

@Injectable({ providedIn: 'root' })
export class AppUpdateService {
    constructor() { }

    checkForUpdates() {
        const res = autoUpdater.checkForUpdates()
        console.log(res);
    }
}
```

**Comment by b-zurg** [comment]
I think probably `ElectronAppAdapter` is intended to run in the main process and not on a renderer process or a service.

The code change you're proposing would break the constructor for any code that's running on the main process (which is most people).

Typically if you need shared code that uses the app object it would be something like
```js
const electron = require("electron");
const app = electron.app || electron.remote.app
...
```

However as of the recent security developments in electron usage of "remote" is not recommended and any code running in a renderer should effectively be browser code with any "native" code being done on the main process using electron's IPC messaging methods.

So I don't see a great benefit to the way that the project you're using is structured and it typically should be fine to run an update check on the main process.  But if you want to make a pull request with something like what I had above then feel free to.

**Comment by agnoam** [comment]
But still, I have tried to run 
```
autoUpdater.checkForUpdates().then((newUpdate) => console.log('update found:', newUpdate))
``` 
in `main.ts` with the default `ElectronAppAdapter.js` constructor, and still got the same exception:

what should I do ?

**Comment by danielehrhardt** [comment]
Did you ever solved this Issue?
I have the same Problem. If i use checkForUpdates in Angular i am getting this error. If i use it in the Main.ts File everything works fine.

**Comment by stoefln** [comment]
Same here!

**Comment by vitor251093** [comment]
I have no idea why, but in my case, the issue was solved by switching the order of my require's. So originally I had:

```
const electron = require('electron')
const {Menu, globalShortcut, nativeTheme, dialog, ipcMain} = electron
const path = require('path')
const { autoUpdater } = require("electron-updater")
...Project specific require's...
const Store = require('electron-store');
const store = new Store({name:'userData'})
const remoteMain = require('@electron/remote/main')
const electronApp = electron.app
```

Then I changed it to:

```
const electron = require('electron')
const {Menu, globalShortcut, nativeTheme, dialog, ipcMain} = electron
const path = require('path')
...Project specific require's...
const Store = require('electron-store');
const store = new Store({name:'userData'})
const remoteMain = require('@electron/remote/main')
const electronApp = electron.app
const { autoUpdater } = require("electron-updater")
```

And that issue was gone. I'm having other issues, with @electron/remote/main being specific, but the electron-updater issue is gone. If I had to guess, what solved the issue was doing this before requiring electron-updater:

```
const electron = require('electron')
[...]
const electronApp = electron.app
```

**Comment by vitor251093** [comment]
I figured out what was going on, at least in my case. The problem was being caused by a misuse of webpack. I was calling it like that:

```
./node_modules/.bin/webpack --config ./webpack.main.config.js ./main.js
```

With a config like that:

```
module.exports = {
    target: 'electron-main',
    entry: ['./main.js'],
    node: {
        __filename: false,
        __dirname: false
    },
    output: {
        filename:'maino.js'
    },
    mode: "production"
};
```

main.js was being mentioned twice, which, unknownly to me, could cause an issue.

https://github.com/electron/electron/issues/7475

After changing the command line to that one:

```
./node_modules/.bin/webpack --config ./webpack.main.config.js
```

The issue was gone. I couldn't find the maino.js file though, and to fix that, I added an extra flag:

```
./node_modules/.bin/webpack --config ./webpack.main.config.js -o ./
```

That fixed the problem for me.
