### ISSUE TITLE
[Question] NSIS fails to update my app but shows no log... how to debug?

### ISSUE THREAD

**Issue by AxelTerizaki** [electron-userland/electron-builder#4918]
I just released a new version of my app, the second since I switched to electron, so I was expecting to update my app properly by downloading the installer first.

However, even though it detects an install and wants to install itself in that same directory, the progressbar goes to roughly 40% and then stops. No error message except for the banner showing "Installation process is interrupted". Only the cancel button works.

So my question is, where can I see details on what went wrong? I see no details button on the installer, under the progress bar.

I'm using the NSIS installer with the one-click install disabled, and letting people choose their install directory.

Since I feel like it's a problem on my end, I'd like to debug it and resolve it, but right now I can't. So how to do it? Thanks in advance.

**Comment by gengshenghong** [comment]
I also got this issue (same behavior) after upgrading electron-builder to 22.0.0. Is it an NSIS upgrade issue?
One of my windows 10 got this issue and after I sign the installer, it works. But another windows 10 still fail after signed.

Thanks,
Shenghong

**Comment by Svetch** [comment]
Hi, sorry for my english. Try rename the installer for other than application name or in build config edit this artifactName: '${productName}.${ext}', -> 
like this --> artifactName: '${productName}-installer-v${version}.${ext}',
this is works for me
[Docs)](https://www.electron.build/configuration/configuration#artifact-file-name-template

**Comment by gengshenghong** [comment]
@Svetch I wonder if it is same issue. In my case, I already configured the installer as below:
artifactName: "${productName} Setup ${version}.${ext}",

Thanks,
Shenghong

**Comment by AxelTerizaki** [comment]
It still is. Help would be appreciated.

**Comment by gengshenghong** [comment]
I also got this issue on another customer machine, and I even cannot reproduce using totally same windows version (including minor version). I also got no way to debug without any log. :(
