### ISSUE TITLE
Electron builder not giving chrome-sandbox correct permissions in AppImage

### ISSUE THREAD

**Issue by futurelucas4502** [electron-userland/electron-builder#4922]
* **Version**: 22.4.1

* **Electron Version**: 8.2.1
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Linux - AppImage

When building for Linux AppImage it successfully completes, however, chrome-sandbox in the compiled AppImage doesn't have the correct executable permissions and therefore the app cannot be run without using `--no-sandbox` which isn't great as I want users to just be able to double click to open the application.

Is there any chance this could be fixed so chrome-sandbox has permissions 4577 or is there a workaround I am not aware of?

**Comment by futurelucas4502** [comment]
This seems to be a distribution issue after switch distros it works perfectly

**Comment by futurelucas4502** [comment]
Okay it wasn't a distribution issue it seems to only happen on arm64 architecture

**Comment by futurelucas4502** [comment]
This is still relevant

**Comment by arsinclair** [comment]
This is still relevant.
