### ISSUE TITLE
Skip EV signature for .appx

### ISSUE THREAD

**Issue by AleshaOleg** [electron-userland/electron-builder#4923]
* **Version**:  22.5.1

* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: 
nsis, msi, appx

Trying to build all of three versions at once. Building `.appx` for Microsoft store requires a signature. But as I'm building a version for store I don't need it. How I can skip EV signature process for `.appx` build? Thanks!

**Comment by AleshaOleg** [comment]
Forgot to mentions, for `appx` build I set those values:

```
"applicationId": "com.ChatGrape",
"identityName": "Company",
"publisherDisplayName": "Company",
"publisher": "CN=value",
"languages": [
  "en-us",
  "de"
],
"showNameOnTiles": true,
"setBuildNumber": true
```

**Comment by AleshaOleg** [comment]
So, I resolved with two separated builds for now. Simply remove all other targets if you have and remove signature properties like `certificateSubjectName` and `rfc3161TimeStampServer`, then build process will skip signature and will build a version for Windows store.

**Comment by EddieOne** [comment]
Thank you, very useful info.
