### ISSUE TITLE
App data not getting removed automatically on Mac

### ISSUE THREAD

**Issue by VikramTiwari** [electron-userland/electron-builder#4924]
* **Version**: 22.5.1

* **Electron Version**: 8.2.4
* **Electron Type (current, beta, nightly)**: Current

* **Target**: mac

When the app is uninstalled, it doesn't remove the files in `appData` directory. This is supposed to happen automatically when user drags-to-delete on mac. It doesn't seem to happen at all. I have also tried using command + delete to remove the app.

**Comment by knubie** [comment]
I didn't think this was expected behavior on MacOS. This is why tools like AppZapper exists.
