### ISSUE TITLE
Usage of .squirrel files

### ISSUE THREAD

**Issue by KochiyaOcean** [electron-userland/electron-builder#493]
I set `build.win.target` as `["squirrel", "7z"]` and electron-builder has generated a `.squirrel ` file, but i couldn't find any information of this kind of file.

**Comment by develar** [comment]
Bug. For now please use `default` instead of `squirrel` — `["default", "7z"]`

**Comment by KochiyaOcean** [comment]
I got it. Thank you!

**Comment by develar** [comment]
Fixed in 5.2.2 (not yet published).
