### ISSUE TITLE
Virus Threat: node_modules\app-builder-bin\win\ia32\app-builder copy.exe

### ISSUE THREAD

**Issue by MrPeerless** [electron-userland/electron-builder#4930]
electron-builder Version:  22.6.0
Electron Version: 4.0.3
electron-updater version: 4.3.1
Target: windows 

After downloading Electron Builder, Windows Defender identified the attached threats.  Please advise. Many thanks.

![shot1](https://user-images.githubusercontent.com/50806081/81059660-c18bf600-8ec8-11ea-984a-bd53c96d3994.JPG)

![shot2](https://user-images.githubusercontent.com/50806081/81059680-cfda1200-8ec8-11ea-9c7e-124295a6471e.JPG)

**Comment by Amosss** [comment]
I had the same issue, following

**Comment by lewisgauss** [comment]
I am facing the same issue on BitDefender.

**Comment by helongbin** [comment]
I also have the issue, but it worked when I use `electron-builder@22.0.0`

**Comment by fedot** [comment]
> I also have the issue, but it worked when I use `electron-builder@22.0.0`

electron-builder@22.0.0 have app-builder-bin@3.4.4 as dependency which is already rise some flags, meanwhile I'm switching to electron-builder@21.2.0 which have app-builder-bin@3.4.3 as dependency and it seems to be the last clean version without any treats.

app-builder-bin@3.4.4:
https://www.virustotal.com/gui/file/b6482b825a51813e56511c12bca60e3748d11622b78e7bbd164fabe125d1c659/detection

app-builder-bin@3.4.3: https://www.virustotal.com/gui/file/18aca8542cf2561220a67c70a7b63bb4490ade7e26a5f57cdd220aef3da89913/detection

**Comment by gonzoua** [comment]
Same here:
app-builder-bin@3.5.8 has the 'ia32/app-builder copy.exe' and it triggers CbDefense on my laptop:
https://www.virustotal.com/gui/file/865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f/detection

app-builder-bin@3.5.9 does not have the file

**Comment by kevinlinv** [comment]
This is the same as issue https://github.com/electron-userland/electron-builder/issues/5004

The latest commit on master uses `app-builder-bin@3.5.9`. See:
https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/builder-util/package.json#L17

Which is also the commit where [`electron-builder v22.7.0`](https://github.com/electron-userland/electron-builder/releases/tag/v22.7.0) was cut from and released.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v22.8.1
