### ISSUE TITLE
productName for macOS "Standard Menu Item Actions"

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#4933]
* **Version**:  22.6.0

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS 10.15.4 (19E287)

According to [the documentation](https://www.electron.build/configuration/configuration) the key `productName` should be set as key of top level `build` object of `package.json`.

```json
{
  "name": "app",
  "build": {
    "productName": "Awesome App"
  }
}
```

But in this case the `name` kay is used for Standard Menu Item Actions on macOS as shown in https://github.com/electron-userland/electron-builder/issues/2468

Using undocumented feature and set top level `productName` key solves the issue.

```json
{
  "name": "app",
  "productName": "Awesome App FOR APP MENU",
  "build": {
    "productName": "Awesome App"
  }
}
```

The `app.setName` method is deprecated: https://www.electronjs.org/docs/api/app#appsetnamename

---

I think the right place of `productName` should be documented.

**Comment by mahnunchik** [comment]
On the other hand `productName` for app name in the doc and app name in the about window is taken from the `build.productName`.

So where is the source of true for `productName`?

**Comment by mahnunchik** [comment]
Yes! **IT IS RELEVANT**!!

**Comment by thomas-darling** [comment]
Yes, this is still relevant - and a fix would be much appreciated.

**Comment by mahnunchik** [comment]
![BP4wh2dCUAAmqma](https://user-images.githubusercontent.com/780935/98337714-b77eb780-2011-11eb-8a5b-7194465782e4.jpg)

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4933
