### ISSUE TITLE
package-win-32 error

### ISSUE THREAD

**Issue by ES1993** [electron-userland/electron-builder#4937]
* **Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 

![image](https://user-images.githubusercontent.com/28608890/81276876-2fc9e780-9086-11ea-88b2-4e9b1e5dfdd2.png)

**Comment by ES1993** [comment]
mac os 10.15.4

**Comment by fkoehler42** [comment]
MacOS 10.15.x doesn't support 32 bit executables anymore.
See the following issue #4875
