### ISSUE TITLE
Hope build command can add options for conditional compilation

### ISSUE THREAD

**Issue by towertop** [electron-userland/electron-builder#494]
I'm using electron-builder 5.1.0 to generate an installer for my app. I hoped the build command can help me a way to run some logging or checking code only in test version but it looks not support this yet.

My idea is like to add an option "--add-pakcage-json-field" to build command. It only put the given field and string to the application package.json.

So I use command:
build --win --x64 --add-package-json-field "env" "test"

My app get a modified package.json:

{
  // other fields like name, version
  // and a new item appended
  "env": "test"
}

That way I can check the 'env' field in code and package my app in 2 commands, rather than modifying code manually.

Look forward to this feature if possible.

**Comment by develar** [comment]
Why you have to modify `package.json`? Why not just put some magic file using https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources ?

**Comment by towertop** [comment]
Putting a magic file doesn't reduce more developers' manual work.

The ideal way is the build command can generate 2 versions of installer. 

For example I write development package.json as:
```json
{
  "scripts" : {
    "test": "build --win --x64 --add-package-json-field env test",
    "dist": "build --win --x64 --add-package-json-field env production"
  }
}
```

Then I can simply type 'npm test' to generate a test installer which would dump much logs for debugging. And typing 'npm dist' can get another installer for the final distribution.

I mentioned to put the condition field in package.json, it is for I usually read in name, version, and other metadata of app from it. It should be easy to test the env field and decide whether to do logging.

**Comment by develar** [comment]
> I mentioned to put the condition field in package.json, it is for I usually read in name, version, and other metadata of app from it

Important clarification, so, now is clear that magic file will just add complexity to your code.

**Comment by develar** [comment]
Why not just check 

```
export function isDev() {
  return app.getAppPath().includes("/node_modules/electron-prebuilt/")
}
```

?

**Comment by towertop** [comment]
> export function isDev() {
  return app.getAppPath().includes("/node_modules/electron-prebuilt/")
}

This way only helps when developing in the workspace folder but not in an installation. After getting the application installed from the installer, it includes no electron-prebuilt. I think it is still helpful to be able to do logging conditionally in that situation.

**Comment by develar** [comment]
Fixed. For ASAR only.
