### ISSUE TITLE
Auto updater error "latest-mac.yml not found"

### ISSUE THREAD

**Issue by sydney-d** [electron-userland/electron-builder#4942]
* **Version**: 21.2.0 (via vue-cli-plugin-electron-builder@1.4.6)

* **Electron Version**: 6.1.10
* **Electron Updater Version**: 4.3.1
* **Target**: Mac

Hello,

I'm pretty new to electron and Im trying to implement auto update on Mac (I have it working on windows)
The related code : 
```js
import { autoUpdater } from "electron-updater"

setInterval(() => {
    autoUpdater.checkForUpdates()
}, 60 * 1000 * 5)

autoUpdater.on('update-downloaded', () => {
    console.log('Update downloaded')
    autoUpdater.quitAndInstall()
})

autoUpdater.on('error', message => {
    console.log('There was a problem updating the application')
    console.log(message)
})
```

The error event is triggered with this message : 
```
  constructor: 'Error',
  code: 'ERR_UPDATER_CHANNEL_FILE_NOT_FOUND',
  stack: 'Error: Cannot find latest-mac.yml in the release ' +
    'https://github.com/MyProject/MyRepo/releases/tag/v0.10.3\n    at ' +
    'e.newError (/Applications/MyProject ' +
    '2.app/Contents/Resources/app.asar/background.js:1:5791)\n    at ' +
    'e.PrivateGitHubProvider.getLatestVersion (/Applications/MyProject ' +
    '2.app/Contents/Resources/app.asar/background.js:8:239102)\n    at ' +
    'processTicksAndRejections (internal/process/task_queues.js:89:5)\n    at ' +
    'async e.MacUpdater.getUpdateInfoAndProvider (/Applications/MyProject ' +
    '2.app/Contents/Resources/app.asar/background.js:1:60962)\n    at async ' +
    'e.MacUpdater.doCheckForUpdates (/Applications/MyProject ' +
    '2.app/Contents/Resources/app.asar/background.js:1:61248)'
```
My github repo looks like this : 

![image](https://user-images.githubusercontent.com/46789893/81419356-6bc87f80-914e-11ea-8fb3-c2bd358bf557.png)

What am I doing wrong ? 

Thank you for your time

**Comment by b-zurg** [comment]
Do you have your publish configuration handy?  I haven't released on github but I might notice something.

**Comment by sydney-d** [comment]
Hello !

I'm using : 
https://github.com/nklayman/vue-cli-plugin-electron-builder

My config looks like this : 
```js
builderOptions: {
  publish: [
    {
      provider: 'github',
      private: false,
      owner: "MyProject",
      repo: "MyRepo",
      token: process.env.GH_TOKEN
    }
  ],
  "asar": true,
  "asarUnpack": "node_modules/puppeteer/.local-chromium/**/*"
},
```

If I publish my tag without mac assets first, and then update it later to upload mac assets, could electron updater use some sort of cache and trigger this error while the assets are OK on github ?

**Comment by paragbaxi** [comment]
@sydney-d i'm also having this issue, were you able to fix? if so, please share!

**Comment by paragbaxi** [comment]
nevermind, release didn't start with `v`. Fix is change `1.0.0` to `v1.0.0`.

**Comment by dlamon1** [comment]
I'm getting this error, and my release does start with v.

**Comment by Travis-Sherman** [comment]
same here, is it only on mac that this is happening
