### ISSUE TITLE
Executable name and description are incorrect when target is win - dir.

### ISSUE THREAD

**Issue by kurt1288** [electron-userland/electron-builder#4944]
* **Version**: 22.4.1

* **Electron Version**: 8.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: win - dir

I'm trying to build a directory output for Windows. I have the following configuration in electron-builder.yml:

    productName: "My Product Name"
    appId: "com.companyname.productname"
    buildVersion: "12.23.456.789"
    artifactName: "Product.${ext}"

And in my package.json (not the entirety of it below, but the relevant parts) file:

    {
        "name": "productname",
        "version": "1.0.0",
        "description": "A short description about my app"
    }

I building it then by running `npx electron-builder --config electron-builder.yml`

But the packaged executable (in the win-unpacked folder) doesn't seem to match that config. The executable's name is "My Product Name" (instead of what I've set in the artifactName). In the Details tab of the Properties window, the description field is populated with the "productName" value instead of the "description" value.

**Comment by mahnunchik** [comment]
Hi @kurt1288 I think it may be related: https://github.com/electron-userland/electron-builder/issues/4933

**Comment by mahnunchik** [comment]
It is still relevant!

**Comment by mahnunchik** [comment]
пт, 25 сент. 2020 г., 14:04 stale[bot] <notifications@github.com>:

**Comment by kurt1288** [comment]
Yes, this is still relevant.

**Comment by mahnunchik** [comment]
y

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4944#issuecomment-766321782

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4944#issuecomment-857309859

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4944#issuecomment-907656694
