### ISSUE TITLE
Issue when npm run package-win command is used

### ISSUE THREAD

**Issue by Avi-hub247** [electron-userland/electron-builder#4963]
I am using -
electron: ^7.1.10, electron-builder: ^20.16.2,electron-directory: 0.0.3,electron-packager: ^12.1.0,
electron-progressbar": "1.0.4",electron-winstaller": "2.6.4" versions.

I keep getting the following error when "npm run package-win" command is used.

WARNING: --asar does not take any arguments, it only has sub-properties (see --help)
Packaging app for platform win32 ia32 using electron v7.1.10
WARNING: Found 'electron' but not as a devDependency, pruning anyway
rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-uikit@1.1.0 package-win: `electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=build/icon.ico   --extra-resource="./resources/" --prune=true --out=release-builds --version-string.CompanyName=abc --version-string.FileDescription=abc --version-string.ProductName="Design Book"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-uikit@1.1.0 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I was hoping someone would have an idea on what I can do from here.

**Comment by WayneGitShell** [comment]
I'm receiving this same error message. 

Was the issue ever resolved?

W
