### ISSUE TITLE
[mac/mas/mas-dev] entitlements plist in binary format crashes application

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#4964]
* **Version**:  22.6.0

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas, mas-dev, mac

Entitlements plist in binary format crashes application if it uses `com.apple.security.app-sandbox` necessary for App Store.

If `entitlements` has `com.apple.security.app-sandbox` then `electron-builder` try  to automate `entitlements` creation: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/util-entitlements.js#L34

And save new `entitlements` to binary format: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/util-entitlements.js#L87 instead XML.

Binary format of `entitlements` produces:

* Crash on startup on mas and mas-dev build.
* Crash on startup on mac build with sandbox enabled.

[electron-osx-sign](https://github.com/electron/electron-osx-sign) uses almost the same logic but saves plists to plain XML format.

https://github.com/electron-userland/electron-builder/tree/master/packages/app-builder-lib/electron-osx-sign - saves binary format through https://github.com/develar/app-builder package.

**Fix of issue**: https://github.com/develar/app-builder/pull/34

Related issues:

* https://github.com/electron-userland/electron-builder/issues/4040
* https://github.com/electron-userland/electron-builder/issues/4834
* https://github.com/electron/electron-osx-sign/issues/225
* https://github.com/electron/electron-osx-sign/issues/223
* https://github.com/electron-userland/electron-builder/issues/4790
* https://github.com/electron/electron-osx-sign/issues/192
* https://github.com/electron/electron/issues/20560

**Comment by mahnunchik** [comment]
It seems it is related too https://github.com/electron-userland/electron-builder/issues/4048

**Comment by replac5** [comment]
run `@replace5/app-builder-bin` and replace node_modules/app-builder-bin files with the package @replace5/app-builder-bin

**Comment by mahnunchik** [comment]
![IMG_20200426_090833](https://user-images.githubusercontent.com/780935/92333477-12ce1100-f086-11ea-909d-28b16aebd46b.jpg)

**Comment by mahnunchik** [comment]
![Ugdcp8r-6Us](https://user-images.githubusercontent.com/780935/98337671-a8980500-2011-11eb-9a7c-939d51557f6b.jpg)

**Comment by Farshatov-Alex-Magora** [comment]
> run `npm i @replace5/app-builder-bin` and replace node_modules/app-builder-bin files with the package @replace5/app-builder-bin files

didn't help to me - still getting same errors as described in this issue...

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4964#issuecomment-760882154
