### ISSUE TITLE
Can't add release-notes.md to latest.yml

### ISSUE THREAD

**Issue by ttomaszewski** [electron-userland/electron-builder#4966]
I'm a bit confused on this documentation https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources
and how to add `release-notes.md` to `latest.yml` and `latest-mac.yml`. 
I run `electron-builder build --mac --publish=never -c.releaseInfo.releaseNotes`
and creates this in the yml. 
```
releaseNotes: 'true'
releaseDate: '2020-05-14T00:47:45.936Z'
```
How can I add my .md file so I can later use for auto-updater. 
```
  autoUpdater.on('update-available', (updateInfo) => {
    logger.info('App update found.');
    const options = {
      type: 'info',
      title: 'Found Updates',
      message: updateInfo.releaseNotes,
      defaultId: 0,
      cancelId: 1,
      buttons: ['Update Now', 'Later']
    };
    dialog.showMessageBox(mainWindow, options).then((res) => {
      if (res.response === 0) {
        autoUpdater.downloadUpdate();
      }
    });
  });
```

**Comment by payitforwardnow** [comment]
This was close. If you need assistance please let me know. Add relase-notes.md or release-notes-${platform}.md to the build folder.

**Comment by shivamthakur98** [comment]
@ttomaszewski Did you found the solution? If you did, can you explain?
@payitforwardnow How can I add that to build folder? Can you explain step by step?
