### ISSUE TITLE
Skip NSIS assisted installer installation type UI with per machine false

### ISSUE THREAD

**Issue by killpowa** [electron-userland/electron-builder#4967]
Is there a reason why it shows the installation type selection UI (per user/per machine) when using NSIS assisted installer and per machine=false ? I would like to enforce installation per user while still using assisted installer to allow the user to change the installation directory.

**Comment by leandrogianotti** [comment]
You can add `!macro customInstallMode` on a `installer.nsh` file and include it on your NSIS configuration to force per user installation mode and add `"allowToChangeInstallationDirectory": true,` on your NSIS configuration to allow the user to change the installation directory.

```
!macro customInstallMode
  	StrCpy $isForceCurrentInstall "1"
    StrCpy $isForceMachineInstall "0"
!macroend
```

**Comment by killpowa** [comment]
How can I hide the "back" button?

**Comment by xieerduos** [comment]
> How can I hide the "back" button?

+1

**Comment by xieerduos** [comment]
> !macro customInstallMode
>     StrCpy $isForceCurrentInstall "1"
>     StrCpy $isForceMachineInstall "0"
> !macroend

Do you have a solution
