### ISSUE TITLE
.deb not installing?

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#497]
OK, so I've tried installing a deb for the first time. Double click the deb, it opens ubuntu software center. I click the install button. Loading indicator shows but stops immediately and text goes back from "installing" to "install". In the sidebar there is another item loaded which says "waiting to install". But clicking it does nothing. App is not installed. Is there a log anywhere so that I can see what went wrong?

**Comment by kunkinkan** [comment]
I suppose it's simply an ubuntu error ?  https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1573206

**Comment by develar** [comment]
Yes, is is Ubuntu critical bug. Solution — update system, it is already fixed. After system update, deb install works.

**Comment by yayolius** [comment]
@develar i just installed a new ubuntu 16.04.1 tried to install a package and nothing, did an apt-get update | apt-get upgrade and nothing the packager still does the same thing starts to install and fails.

**Comment by develar** [comment]
@yayolius Will check. BTW, consider to use AppImage target instead.
