### ISSUE TITLE
How to build and share app, if one is not a member of Apple Developer Program?

### ISSUE THREAD

**Issue by exogenesys** [electron-userland/electron-builder#4971]
Version of electron-builder: **22.6.0**

Version of electron:**7.1.13**

Target are you building for: **macOS**

macOS Version: **10.14.6 (18G2022)**

The app I've made and compiled into an .dmg or .app, works on my system but shows the error 'The application `ApplicationName` can't be opened' on all the other macOS systems. I also get the same error if upload the `.app.zip` somewhere and download it again. 

![image](https://user-images.githubusercontent.com/8681754/81947856-aa62ac00-961e-11ea-8e24-28fc1fae4ca8.png)

I understand that Gatekeeper doesn't let apps by unidentified developers run and I understand that there are process which you should do before distributing your app:

 1. Sign the app
 2. Notarize

I get the same error after signing the app using Apple Development Certificate. Notarization is only allowed to people who has the Apple's $99 membership. 

I just want to share the app I've made to my colleagues for feedback. As far as I know, you can share the app, it will just show a warning message, but you can still share the app. Is there no way I can do that, other getting to package the app with the source code on their own? This is just seems a very strange thing to me.

What are the steps to follow if I want to the app to compile and share the app outside the App Store and without Apple Developer Program, given that I don't mind the warning?

Thanks!

**Comment by b-zurg** [comment]
You can package the installer but they will have to follow the same steps any other unsigned un-notarized mac installer has to go through to run. 

This is a mac issue and it's aggressive but that's just the way it is.  

This should help: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by exogenesys** [comment]
> You can package the installer but they will have to follow the same steps any other unsigned un-notarized mac installer has to go through to run.
> 
> This is a mac issue and it's aggressive but that's just the way it is.
> 
> This should help: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

@b-zurg Thanks for replying! 👍

The error that I'm getting is different. It doesn't anywhere say that app can't be opened as it is by an unidentified developer. It just says 'The application "Skateboard" can't be opened.'. I've tried opening via Finder and Ctrl + Clicking, but it gives me the same error.

The app works right after I build it. But it doesn't work if I upload and download the zip to any cloud. (Can't be shared)

Could you please tell me how shall I proceed with this? :)

**Comment by b-zurg** [comment]
Oh you're running the zip? I thought you were packaging into a DMG and had trouble running that. 

I'm just speaking off the top of my head but if you extract the contents of the zip into a folder do you see the executable? Can you run the executable in a terminal and see the output?

**Comment by exogenesys** [comment]
Yes, I am uploading the `.app.zip`, in my case `Skateboard.app.zip` and downloading it, extracting to get `.app`, which gives me the above mentioned error.

If I open the `.app` after extracting with `Show Package Contents`, go to `Contents > MacOS`, where the executable should be. I find a file which is recognized as text file by the Finder and default app is set to TextEdit. If I try to execute it via the terminal with the command `./Skateboard`, I get a permission error (`permission denied`).

After fixing the permission error with `chmod 777 ./Skateboard` the Finder finally sees it as Unix Executable. If I run this executable, it immediately closes.

Whereas, with `.app` which I haven't uploaded and download, runs smoothly without any permission errors, with the command `./Skateboard.app/Contents/MacOS/Skateboard`. or even launching the `.app` with a double-click. :(

What should I do? 😕 


@b-zurg
