### ISSUE TITLE
Wrong StartupWMClass being set in the .desktop file for linux builds

### ISSUE THREAD

**Issue by rathboma** [electron-userland/electron-builder#4974]
* **Version**: 22.4.1
* **Electron Version**: 6.1.9
* **Electron Type (current, beta, nightly)**: current
* **Target**: linux (all)

My OSS project (github.com/beekeeper-studio/beekeeper-studio) is not showing an app icon on most Linux systems.

This is because:

1. In my builder config - `productName` is 'Beekeeper Studio', name is 'beekeeper-studio'
2. In the resulting .desktop file - StartupWMClass = 'Beekeeper Studio'
3. Actual WM_CLASS when inspecting with xprop - 'beekeeper-studio'

Here's the final desktop file:

```
[Desktop Entry]
Name=Beekeeper Studio
Exec="/opt/Beekeeper Studio/beekeeper-studio" %U
Terminal=false
Type=Application
Icon=beekeeper-studio
StartupWMClass=Beekeeper Studio
Comment=An easy-to use SQL query editor and database UI for Mac, Windows, and Linux
Categories=Development;
```
The icon entry is correct.

I think `StartupWMClass` should maybe be set to `appInfo.name` not `appInfo.productName`?

Clearly many other projects have solved this, so hoping for some direction on how to best do this!

Thanks

**Comment by omarkilani** [comment]
You can customize the StartupWMClass (and other .desktop entries) like:

```
    "linux": {
      "category": "Office",
      "synopsis": "Remember The Milk for Desktop",
      "desktop": {
        "Name": "Remember The Milk",
        "Categories": "Utility;Office;Calendar;ProjectManagement;",
        "Keywords": "rtm;todo;to-do;task;tasks;task manager;",
        "StartupWMClass": "Remember The Milk"
      }
    },

**Comment by rathboma** [comment]
Yep, totally agree -- however, the default seems to be incorrect?

**Comment by omarkilani** [comment]
I think it's just difficult to have one 'rule' that works for all cases. We just set everything explicitly to stop any magic.
