### ISSUE TITLE
Missing app-update.yml, why is this file mandatory ?

### ISSUE THREAD

**Issue by adriencohen** [electron-userland/electron-builder#4975]
Hello,

We have multiple users who have issues of with the auto update due to the `app-update.yml` gone missing and they end up with:

`ENOENT: no such file or directory, open 'C:\Users\Username\AppData\Local\Programs\electron-app-here\resources\app-update.yml'`

I checked the installers, they are all writing this file without any issues on my computer. We migth have found how the file is getting deleted and it would not be related to electron-builder.

However, I was wondering why is this file so important ? In our app we already use `autoUpdater.setFeedUrl()` so from what I see in `app-update.yml` the updater is only missing the `updaterCacheDirName`. Which lead me to wondering why we can't set it with `autoUpdater` and bypass completely the need to read `app-update.yml`.

**Comment by adam-lynch** [comment]
I ran into this today while [migrating an app from Squirrel to NSIS](https://github.com/electron-userland/electron-builder/issues/837). I was manually setting the feed URL but I still had to create the `app-update.yml` file (in the Squirrel app) because of this error

**Comment by abenoit-reeliant** [comment]
If anyone has any insight on this issue, I'm still interested in an answer. I feel like this file should not be mandatory if the required information is provided by the application on runtime.

**Comment by mhosken** [comment]
Or perhaps if the information is missing, don't bother trying to auto update? I too have fallen foul of this and it makes it impossible to use the app. This is a breaking bug since it makes it impossible for a normal user to get past it and actually run the app. OOI how does one work around this?
