### ISSUE TITLE
Separate build for stores with help of flag

### ISSUE THREAD

**Issue by AleshaOleg** [electron-userland/electron-builder#4978]
That's not a bug, but a feature request which I can help to implement if we will agree on details. So, my proposal is to make a flag, something like `storeBuild`. This flag will build a separate store version for macOS and Windows after a normal build.

As of macOS needs `hardenedRuntine` to be `false` for the macOS app store, and for Windows app shouldn't be signed (right now I'm dealing with this as I described here - https://github.com/electron-userland/electron-builder/issues/4923). As a result of `storeBuild: true` build process will create one more build for the store and will disable signature for Windows and will set `hardenedRuntine` to `false` for macOS.

Hope this makes sense, thanks!

**Comment by b-zurg** [comment]
Question: couldn't this be accomplished by a sequential build command with a different environment variable set?

I'm running a different set of publishers based on the `NODE_ENV` variable.  Since my config is a `.js` file then it becomes easy to do a ternary operation.  Before the build I then am using `cross-env` to set the env variable to what  I want.  So effectively I have a `yarn publish:dev` and `yarn publish:prod`.

I'm wondering if this sort of flexibility would be enough for what you're looking for.

**Comment by mahnunchik** [comment]
Hi All,

@b-zurg if I understand the question right it is not about environment `dev/prod` but it is about different versions of `prod` build.

@AleshaOleg If builder works according the documentation that separated build should be implemented by settings config like:

```json
{
"build": {
  "mac": {
    "hardenedRuntine": true,
    "target": [
      "dmg",
      "mas"
    ]
  },
  "mas": {
    "hardenedRuntine": false
  }
} 
```

So it builds a dmg `mac` build to `mac` folder with hardenedRuntine. And `mas` build to `mas` folder without hardenedRuntine.

**Comment by AleshaOleg** [comment]
@b-zurg this is for sure can be done with different build commands and configs with environment variables usage like in your example with `dev` and `prod` builds. But this will require a bit more settings then just simply set one variable, like `NODE_ENV` to `production` or `development`. And I think some flag `storeBuild` will make it easier.

**Comment by AleshaOleg** [comment]
@mahnunchik ok, yes. As `mac` build has `mas` config we can add `hardened runtime` to `mas` config. Then we will need some kind of `store` config for `appx` build for Windows.

**Comment by mahnunchik** [comment]
> some kind of store config for appx build for Windows.

+1

Actually I've faced with some mishmash in configuration:

1. For `mac` build we can specify `target` as `mas`, `dmg`, `zip` but at the same time we have top level `mas` and `dmg` and doesn't have `zip` top level key.
2. We have separated targets for macOS: `mac` and `mas`, but doesn't have separation for Windows AppX (self-made and store distribution).

---

I'd like to have config like the following:

```json
{
  "build": {
    "mac": {
      // common config
      "appId": "com.example",
      "target":{
        "dmg": {
          "hardenedRuntine": true
        },
        "mas": {
          "hardenedRuntine": false
        }
      }
    }
  }
}
  
```

**Comment by mahnunchik** [comment]
Yep, it is relevant!

**Comment by AleshaOleg** [comment]
Yes, up

**Comment by mahnunchik** [comment]
![TKoNiRAJTeo](https://user-images.githubusercontent.com/780935/99144819-c1d42d80-2671-11eb-8050-fa0e5495a651.jpg)

**Comment by AleshaOleg** [comment]
Up
