### ISSUE TITLE
Debian Icon

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#498]
Is there a way to add a debian icon? Ubuntu Software Center has possibility of an icon.

**Comment by develar** [comment]
> there is a white empty box indicating a space for a possible "screenshot". 

Do you mean https://github.com/electron-userland/electron-builder/issues/242 ? Help wanted — feel free to send PR ;)

**Comment by kunkinkan** [comment]
No, I'm talking about the Icon specifically. I have a build/icon.icns file but it is not used in ubuntu software center. Instead a default "puzzle" icon is shown.

**Comment by atypicalprogrammer** [comment]
What's the issue with this?

**Comment by develar** [comment]
> What's the issue with this?

I don't know. As we push using AppImage, I still don't have time to investigate. Help wanted.
