### ISSUE TITLE
App crashes after signing with sandbox enabled

### ISSUE THREAD

**Issue by philippnoah** [electron-userland/electron-builder#4980]
My goal is to build the app in order to submit it to the Mac App Store. It runs fine during development and when using ```mac``` as the target, but when I use the ```mas``` or ```mas-dev``` target, the app crashes right after opening it. I understand there's a high risk this issue is caused by a misconfiguration, but after days of debugging I'm willing to take my chance.

* **Version**: 
```
    "electron-builder": "^22.6.0"
```

* **Electron Version**:
 ```  
  "electron": "^8.2.5" 
```
* **Electron Type (current, beta, nightly)**: ```current```

* **Target**: ```[mas-dev, mas]```

* **package.json**: 
```
{
  "name": "Airnotes",
  "version": "7.0.3",
  "description": "A simple notes app.",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/philippnoah/airnotes-electron.git"
  },
  "keywords": [
    "airnotes",
    "notes",
    "air",
    "notes",
    "mac",
    "notes"
  ],
  "author": "Philipp Eibl",
  "license": "",
  "bugs": {
    "url": "https://www.airnotesapp.wordpress.com"
  },
  "homepage": "https://www.airnotesapp.wordpress.com",
  "private": true,
  "devDependencies": {
    "electron": "^8.2.5",
    "electron-builder": "^22.6.0"
  },
  "dependencies": {
    "electron-context-menu": "^2.0.1",
    "universal-analytics": "^0.4.20",
    "electron-json-storage": "^4.1.8"
  },
  "build": {
    "appId": "{appID}",
    "icon": "res/icon.icns",
    "mac": {
      "target": "mas-dev",
      "category": "public.app-category.productivity",
      "icon": "res/icon.icns",
      "type": "distribution",
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "provisioningProfile": "development.provisionprofile"
    },
    "mas": {
      "entitlements": "entitlements.mas.plist",
      "target": "mas-dev"
    }
  }
}
```

* **entitlements.mas.plist**:
```
<!--?xml version="1.0" encoding="UTF-8"?-->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
    <key>ElectronTeamID</key>
  <string>{teamID}</string>
  <key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.application-groups</key>
        <array>
            <string>{teamID}.{appID}</string>
        </array>
    </dict>
</plist>
```

* **Terminal output**: 
<img width="1657" alt="Screen Shot 2020-05-18 at 10 35 17 PM" src="https://user-images.githubusercontent.com/20135561/82257431-4f9bbe00-9958-11ea-8195-10ff52095d5b.png">

* **Node version**: v12.6.0

* **npm version**: 6.14.5

**Comment by philippnoah** [comment]
Looks like it might be related to [4790](https://github.com/electron-userland/electron-builder/issues/4790)

**Comment by AleshaOleg** [comment]
Use 22.6.1

**Comment by philippnoah** [comment]
@AleshaOleg Updated, thanks. Didn't do the trick unfortunately :(

**Comment by AleshaOleg** [comment]
For `mas`/`mas-dev` build, you should set`hardenedRuntime` to `false`.

**Comment by ahmadwaliesipick** [comment]
> Use 22.6.1

@philippnoah  can you please help me to resolve this issue?  #5011

**Comment by ahmadwaliesipick** [comment]
> For `mas`/`mas-dev` build, you should set`hardenedRuntime` to `false`.

@AleshaOleg  i had try that but still not working, can you please check issue details here? #5011
