### ISSUE TITLE
Error: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by vivex** [electron-userland/electron-builder#4984]
* **Version**: 22.3.6

* **Electron Version**:8.2.5
* **Electron Type (current, beta, nightly)**:current

* **Target**: mac
```
Error: spawn /bin/sh ENOENT    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
Getting above error while a node_module package is trying to run following command:
`screencapture -x -t jpg /var/folders/xc/87fy8l_n7h50wm003s5mqhcc0000gn/T/2020419-62347-g8qiui.kgax.jpg`

**Comment by mvaneijgen** [comment]
I think I have the same issue. My function looks like `spawn("node",[ path.join(__dirname, "../../plugins/puppeteer.js"), MY-ARGS]);` which works great while in development mode, but as soon as I build the project nothing works and all I can see is the following error and I have no idea what either `write EPIPE` or  `spawn node ENOENT` means or how to go about debugging it.

```
events.js:183 Uncaught Error: write EPIPE
    at _errnoException (util.js:1024)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867)
_errnoException @ util.js:1024
afterWrite @ net.js:867
renderer.js:1 err on spawn  Error: spawn node ENOENT
    at _errnoException (util.js:1024)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190)
    at onErrorNT (internal/child_process.js:372)
    at _combinedTickCallback (internal/process/next_tick.js:138)
    at process._tickCallback (internal/process/next_tick.js:180)
```

[Here is my function that is spawning a Node child process](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/components/Start/Generate.vue) and [here is the Node script that works fine before building the project](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/plugins/puppeteer.js)

I have the feeling somethings don't get packaged while building the project, but I have no idea why or how that is. 

[![Screenshot Generator App Preview](https://i.imgur.com/pTSFKqk.png)](https://github.com/mvaneijgen/screenshot-generator-app)

My app works great and its exactly what I want it to be, I'm just stuck at this little small step (for weeks now) and I'm kinda at a loss.

**Comment by EasyChris** [comment]
> I think I have the same issue. My function looks like `spawn("node",[ path.join(__dirname, "../../plugins/puppeteer.js"), MY-ARGS]);` which works great while in development mode, but as soon as I build the project nothing works and all I can see is the following error and I have no idea what either `write EPIPE` or `spawn node ENOENT` means or how to go about debugging it.
> 
> ```
> events.js:183 Uncaught Error: write EPIPE
>     at _errnoException (util.js:1024)
>     at WriteWrap.afterWrite [as oncomplete] (net.js:867)
> _errnoException @ util.js:1024
> afterWrite @ net.js:867
> renderer.js:1 err on spawn  Error: spawn node ENOENT
>     at _errnoException (util.js:1024)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190)
>     at onErrorNT (internal/child_process.js:372)
>     at _combinedTickCallback (internal/process/next_tick.js:138)
>     at process._tickCallback (internal/process/next_tick.js:180)
> ```
> 
> [Here is my function that is spawning a Node child process](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/components/Start/Generate.vue) and [here is the Node script that works fine before building the project](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/plugins/puppeteer.js)
> 
> I have the feeling somethings don't get packaged while building the project, but I have no idea why or how that is.
> 
> [![Screenshot Generator App Preview](https://camo.githubusercontent.com/bd4569247b48330836a906a05f5cb3caeff6c5243839019433f7f1761131b9dc/68747470733a2f2f692e696d6775722e636f6d2f705453464b716b2e706e67)](https://github.com/mvaneijgen/screenshot-generator-app)
> 
> My app works great and its exactly what I want it to be, I'm just stuck at this little small step (for weeks now) and I'm kinda at a loss.
> 
> I've made a video to better illustrate the issue https://www.youtube.com/watch?v=J0WLihlO1Go&feature=youtu.be
> 
> [![EPIPE](https://camo.githubusercontent.com/66627fe32c3f4be94d9980246a14a98aa86fe29383c9c2fccf46b516a176a79e/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f4a30574c69686c4f31476f2f302e6a7067)](https://www.youtube.com/watch?v=J0WLihlO1Go)

i have the same problems, How did you solve it?
