### ISSUE TITLE
How to remove AppData for Win, Linux, Mac platforms?

### ISSUE THREAD

**Issue by korenandr** [electron-userland/electron-builder#4985]
* **22.6.1**: 

* **5.0.0**:
* **stable**:

* **Win, Linux, Mac**: 

I need to delete app user data for all supported platforms (Win, Linux, Mac), when application uninstalled. But only suitable things that I found was customize "nsis" (add flag "deleteAppDataOnUninstall": true). Its working for Windows with simple *.exe installer, but doesnt work with *.msi installer. How can I customize package.json that app data will be removed for Win, Linux && Mac?

**Comment by apipaliya** [comment]
electron version: 17.4.3
electron-builder version: 23.3.3

I need to delete app user data for all supported platforms (Win, Linux, Mac), when application uninstalled. But only suitable things that I found was customize "nsis" (add flag "deleteAppDataOnUninstall": true). Its working for Windows with simple *.exe installer, 

How can I customize package.json that app data will be removed for Linux && Mac?
