### ISSUE TITLE
Electron 9.0 electron-osx-sign update

### ISSUE THREAD

**Issue by shahan312** [electron-userland/electron-builder#4989]
* **Version**: v22.6.1

* **Electron Version**: v9.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

The electron-osx-sign library inside electron-builder needs to be updated with the following change to allow the signing to occur correctly.

See:
https://github.com/electron/electron/issues/23565
 
https://github.com/electron/electron-osx-sign/pull/228

**Comment by athenawisdoms** [comment]
Also experiencing this problem.

Please update the version of `electron-osx-sign` :)

**Comment by lutzroeder** [comment]
Duplicate of #4969

**Comment by alchaplinsky** [comment]
+ 1 Having issues with signing app. Electron v9.0.0

**Comment by dariocravero** [comment]
until https://github.com/electron-userland/electron-builder/pull/4993 or a similar solution gets merged, monkey patching `node_modules/app-builder-lib/electron-osx-sign/sign.js` with the code on that PR works
