### ISSUE TITLE
Warning: App is not signed, but keychain has a valid identity.

### ISSUE THREAD

**Issue by verdecchia** [electron-userland/electron-builder#499]
Hi to everybody. I'm using this project from github: https://github.com/Vj3k0/ea-todo. Electron-builder 4.26 works like a charm, but if I upgrade to 5.3.0, I get an error about the identity present in the keychain. Why 4.26 works and 5.3.0 not? 

I hope it helps you.

MarcoVerdecchia:myapp mverdecchia$ ./node_modules/.bin/build --version
**4.2.6**

MarcoVerdecchia:myapp mverdecchia$ ./node_modules/.bin/build -o --x64
Rebuilding app dependencies for arch x64 to /Users/mverdecchia/Documents/myapp/app
angular@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular
angular-animate@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-animate
angular-aria@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-aria
angular-material@1.1.0-rc.5 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-material
electron-squirrel-startup@1.0.0 /Users/mverdecchia/Documents/myapp/app/node_modules/electron-squirrel-startup
debug@2.2.0 /Users/mverdecchia/Documents/myapp/app/node_modules/debug
ms@0.7.1 /Users/mverdecchia/Documents/myapp/app/node_modules/ms
Packaging app for platform darwin x64 using electron 1.2.2 to dist/osx
**Signing app (identity: iPhone Developer: marco.verdecchia@gmail.com (J5NZH9Q7TH))**
.....

MarcoVerdecchia:myapp mverdecchia$ ./node_modules/.bin/build --version
**5.3.0**

MarcoVerdecchia:myapp mverdecchia$ ./node_modules/.bin/build -o --x64
Rebuilding app dependencies for arch x64 to /Users/mverdecchia/Documents/myapp/app
angular@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular
angular-animate@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-animate
angular-aria@1.5.6 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-aria
angular-material@1.1.0-rc.5 /Users/mverdecchia/Documents/myapp/app/node_modules/angular-material
electron-squirrel-startup@1.0.0 /Users/mverdecchia/Documents/myapp/app/node_modules/electron-squirrel-startup
debug@2.2.0 /Users/mverdecchia/Documents/myapp/app/node_modules/debug
ms@0.7.1 /Users/mverdecchia/Documents/myapp/app/node_modules/ms
Packaging app for platform darwin x64 using electron 1.2.2 to dist/osx
**Warning: App is not signed: CSC_LINK or CSC_NAME are not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing**
Creating DMG
Creating OS X zip

**Comment by develar** [comment]
Because now we forbid  iPhone Developer certificate. You must (if I am not wrong) use Developer ID Application Certificate. Please see https://developer.apple.com/support/certificates/
