### ISSUE TITLE
app-builder-lib code sign error, not using electron-osx-sign as dep but pure file

### ISSUE THREAD

**Issue by s524797336** [electron-userland/electron-builder#4992]
This is my workaround.
```
yarn add electron-osx-sign -D
```
Add to package.json `scripts`
```
"postinstall": "rm -rf node_modules/app-builder-lib/electron-osx-sign && ln -s $(pwd)/node_modules/electron-osx-sign node_modules/app-builder-lib",
```
#4989 #4969

**Comment by lutzroeder** [comment]
Duplicate of #4969

**Comment by mahnunchik** [comment]
I think hardcoded [electron-osx-sign](https://github.com/electron-userland/electron-builder/tree/master/packages/app-builder-lib/electron-osx-sign) should be renamed to avoid confusion with package https://github.com/electron/electron-osx-sign

**Comment by s524797336** [comment]
^9.0.1 fix this, but still, why not use electron-osx-sign instead.
