### ISSUE TITLE
Renaming appId causes AutoUpdater to throw errors on update

### ISSUE THREAD

**Issue by frankrobert-ls** [electron-userland/electron-builder#4994]
* **Version**: 
22.6.0

* **Electron Version**:
8.2.3
* **Electron Type (current, beta, nightly)**:
current

* **Electron-Updater Version**:
4.3.1

* **Target**: 
Mac, Windows

When shipping an application with a fixed appId such as `"appId": "com.myOrg.myAppName"` all works well and the auto-updater is able to ship new versions to the end-user as expected. If you change the appId to something new (such as `"appId": "com.myOrg.myRenamedApp"`) due to rebranding or other reasons, the auto-updater will throw an error due to the mismatch in appId values.

Here's a screenshot reproing the problem:

![image](https://user-images.githubusercontent.com/47538444/82467066-36e1f400-9a8f-11ea-8ee6-67ed695d8356.png)

Our old appId is `com.lightspeed.CFD` whereas the new one is `com.lightspeed.Hub` which causes the update to fail.

This is obviously critical as it means it is impossible to rebrand an application automatically without having *all* users manually download and install a fresh version of the application, and of course the more users your application has the worse this is.

In our case, even a workaround would be helpful and allow us to move forward.

**Comment by frankrobert-ls** [comment]
This issue is still relevant.

**Comment by timche** [comment]
@frankrobert-ls were you able to fix this? I'd like to change the `appId` as well, but I'm afraid it will still break auto-updating.

**Comment by frankrobert-ls** [comment]
> @frankrobert-ls were you able to fix this? I'd like to change the `appId` as well, but I'm afraid it will still break auto-updating.

Never resolved the issue.

**Comment by timche** [comment]
Thanks for your response! Too bad. I can't believe we are the only people dealing with this. I guess there is no other option other than tell my users to download the update manually.

**Comment by shafayet2368** [comment]
@frankrobert-ls ,, any update on this issue in your case? .. I am facing the same problem for my app. Any help would be great..

**Comment by afgarcia86** [comment]
I am seeing this issue as well but I am not explicitly setting `appId` so I am not sure if maybe that causes the same issue?

**Comment by ufukomer** [comment]
+1
