### ISSUE TITLE
Can't delete URI Protocol registered in the Windows registry automatically when app was uninstalled

### ISSUE THREAD

**Issue by q837477816** [electron-userland/electron-builder#4997]
* **Version**: 22.4.0

* **Electron Version**: 7.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: .msi, .exe

Our app implements deeplink via add below config to build script, and it works. But after uninstall our app, I found the URI Protocol (applink) still exist in the Windows registry. Can it be deleted automatically when uninstalling our app?
```
protocols: [
   {
      name: 'app-deep-linking',
      schemes: ['applink']
    }
]
```

**Comment by danielweck** [comment]
yep, the problem still exists :(

**Comment by thomas-void0** [comment]
hey, I have same question.I check up some info.you can maual del this registered of info. In this link address: https://stackoverflow.com/questions/47210665/nsis-uninstaller-not-deleting-registry-for-electron-app-nsh-script. hope for help you.
