### ISSUE TITLE
How to include a 3rd party installer?

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#500]
Hi there,

I need to ship a 3rd party installer alongside my application. With NSIS this wasn't an issue; I could just call the 3rd party installer and continue installation after it was finished. But I've got no clue how to achieve anything comparable with `electron-builder`.

Any help is appreciated.

**Comment by develar** [comment]
NSIS target supported — released today https://github.com/electron-userland/electron-builder/releases/tag/v5.4.0 See not yet implemented features — https://github.com/electron-userland/electron-builder/pull/495#issue-160014408

**Comment by black-snow** [comment]
Neat, but this is an alternative to squirrel, right? Sadly, I need both, auto-update + 3rd party installer.

**Comment by develar** [comment]
NSIS will support auto-update as well, but I cannot say when it will be available. 

For Squirrel the only way — handle `--squirrel-install` or `--squirrel-updated` and run your 3rd party installer. Use [extraFiles](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraFiles) to copy it into the app.

**Comment by black-snow** [comment]
Alright, thanks a lot.
