### ISSUE TITLE
Similarity: buildVersion, buildNumber, process.env.BUILD_NUMBER etc on different platforms

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5000]
* **Version**: 22.6.1

* **Electron Version**: -
* **Electron Type (current, beta, nightly)**: -

* **Target**: any

There are some options related to build version/number:

* **macOS**: uses `buildVersion` and `bundleVersion` 
* **Windows**: uses `BUILD_NUMBER` and `setBuildNumber` flag in different way https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/appInfo.ts#L41-L47
* **Linux**: doesn't use `buildVersion` https://github.com/electron-userland/electron-builder/issues/4720

It would be nice to have ability to set option `buildVersion` for each OS.

**Comment by mahnunchik** [comment]
Example:

```bash
# For macOS I can set as parameter
electron-builder --mac  -c.buildVersion=123

# For WIndows I have to set variable
Set-Variable -Name "BUILD_NUMBER" -Value "123"
electron-builder --win
```

Because `buildVersion` is not used in: https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/appInfo.ts#L41

**Comment by mahnunchik** [comment]
Yep, it is relevant!

ср, 22 июл. 2020 г. в 00:56, stale[bot] <notifications@github.com>:

**Comment by mahnunchik** [comment]
![IMG_20200501_170620](https://user-images.githubusercontent.com/780935/93713915-35cdea00-fb89-11ea-9df8-4d1d50d4c5f9.jpg)

**Comment by mahnunchik** [comment]
![Uploading small_264a18c1-c424-481a-95fc-3efe93f11026.jpeg…]()

**Comment by DrNiels** [comment]
Yes, still relevant

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5000#issuecomment-857309928

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5000#issuecomment-907656692
