### ISSUE TITLE
Small Notification Icon

### ISSUE THREAD

**Issue by fsykes87** [electron-userland/electron-builder#5003]
version: 21.2.0

* **Version**: 

21.2.0

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 
windows 10

My application uses node-notifier to send toast notifications to the users desktop. In development the application work perfectly however after packing the app and installing, the toast icon is inside of a tiny blue box and icon is tiny. Any idea how to correct this?

**Comment by fsykes87** [comment]
@jviotti

**Comment by jviotti** [comment]
Hey @fsykes87 ,

Answering these questions would help us find the issue faster:

- What format are you using for the icon?
- What is/are the resolutions of the icon?
- What packaging format are you generating? (i.e. NSIS, AppX, etc)
- How are you specifying the icon?

**Comment by fsykes87** [comment]
icon is a 256 x 256 .ico file

i am using NSIS

```const checkMessage = async () => {

  const recordset = await query(`select alerts.dbo.groupmessages.pk, alerts.dbo.groupmessages.groupFK, alerts.dbo.groupmessages.isRead, alerts.dbo.message.message

  from alerts.dbo.groupmessages

  full outer join alerts.dbo.message

  on alerts.dbo.GroupMessages.messageFK = alerts.dbo.message.pk

  where userFK = (select pk from alerts.dbo.users where username = '${userName}')

  and (groupFK = (select groupFK from alerts.dbo.users where username ='${userName}'))

  and isRead = 0

  and isActive = 1`);

 

  if (recordset.rowsAffected > 0) {

    const promiseArr = [...new Array(recordset.rowsAffected).keys()].map((i, index) => {

      return new Promise((resolve, reject) => {

        notifier.removeAllListeners();

        notifier.notify(

          {

            appId: "com.electron.demo", // Absolute path (doesn't work on balloons),

            title: "Alert Message",

            message: "Click to view",

            icon:'./icon.ico',

            timeout: 60,

            wait: true,

            id: "demo app", 

            myCustomAction: openNotify

          },

          function(err, response) {

            // Response is response from notification

            if (err) {

              reject(err);

            } else {

              resolve(response);

            }

          }

        );`

**Comment by fsykes87** [comment]
@jviotti

**Comment by jviotti** [comment]
@fsykes87 Can you try with an `.ico` that is larger than 256x256? According to https://www.electron.build/icons, the icon should be *at least* that size, so we can see if a larger one works better.

**Comment by fsykes87** [comment]
@jviotti 

i was doing some research and the maximum size for windows 10 icons is 256 x 256.
Ive also noticed that the notification does not behave properly in the windows notification center after timeout the notification onCLick function no longer fires

[https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#:~:text=Icons%20have%20a%20maximum%20size,list%20views%20with%20large%20icons.](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#:~:text=Icons%20have%20a%20maximum%20size,list%20views%20with%20large%20icons.)

**Comment by jviotti** [comment]
256x256 does sound large enough. The fact that this works fine on local development but the icon gets smaller after running electron-build makes me think that electron-build is manipulating the icon in some way, and not doing that correctly.

Maybe @develar can chime in?

**Comment by fsykes87** [comment]
It should not be closed because multiple people are having the same issue
with no resolve. I want to say it may be a Microsoft issue....

**Comment by YeetOrBeYate** [comment]
Why is this closed, no answer was given? This is still a relevant issue
