### ISSUE TITLE
Request administrator rights for portable application

### ISSUE THREAD

**Issue by koppa96** [electron-userland/electron-builder#5008]
* **Version**: 22.4.1

* **Electron Version**: 8.2.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: portable

Hi,

My issue is rather a question. I'm trying to package an application with the portable target that requests administrator privileges to run. I set the option in the electron-builder.json:

```
"win": {
    "icon": "dist/assets/icons",
    "target": [
      "portable"
    ],
    "requestedExecutionLevel": "requireAdministrator"
  },
```
The unpacked exe file requests administrator rights to be open, but the packed, portable exe file does not. Is there a way to make the portable exe file request administrator rights?

I have looked into the manifest of the portable exe file, and it shows that the `requestedExecutionLevel` is set to `asInvoker` instead of `requireAdministrator`. I also tried editing the manifest with `mt.exe`, but then when I want to launch the app, it crashes with an NSIS error.

**Comment by mxswat** [comment]
Did you solve or you still have this issue?

**Comment by koppa96** [comment]
No, I ended up not creating a portable exe file, but an NSIS installer. The installed exe file requires admin privileges as it should. No idea why tha portable doesn't.

**Comment by mxswat** [comment]
@koppa96 
I foud a solution

```
"win": {
                    "target": ["portable"],
                },
                "portable": {
                    "artifactName": "R6CGT_portable.exe",
                    "requestExecutionLevel": "admin"
                },
```

**Comment by koppa96** [comment]
Thank you for sharing! I’ll close the issue then. 🙂

**Comment by tutiplain** [comment]
I know this issue is closed, but I'd like to point out that the options which solve the issue do not appear in electron-builder's documentation. Are there any plans to add them? This issue stumped me for days before I came across this post. If it were documented, it would've saved me a lot of time.

**Comment by trzaver-svg** [comment]
### [JUSTIN TV, CANLI MAÇ İZLE](https://github.com/microsoft/winget-pkgs/discussions/282476)

### [JUSTIN TV, CANLI MAÇ İZLE](https://github.com/microsoft/winget-pkgs/discussions/282476)

### [JUSTIN TV, CANLI MAÇ İZLE](https://github.com/microsoft/winget-pkgs/discussions/282476)

### [JUSTIN TV, CANLI MAÇ İZLE](https://github.com/microsoft/winget-pkgs/discussions/282476)

### [JUSTIN TV, CANLI MAÇ İZLE](https://github.com/microsoft/winget-pkgs/discussions/282476)
