### ISSUE TITLE
NSIS App ID

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#501]
Where are we supposed to define this? Docs are not yet up to date on this. Is it the same as app-bundle-id?

**Comment by develar** [comment]
Wiki synced, https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-appId

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/NSIS#guid-vs-application-name
