### ISSUE TITLE
The same app when install replace by new version, it show multiple.

### ISSUE THREAD

**Issue by phanpiseth9** [electron-userland/electron-builder#5010]
old 21.2.0 and current using 22.6.1

* **Version**: 22.6.1

old 6.0.12 and current 9.0.0

* **Electron Version**:9.0.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: nsis

When i was installing new version replace old it show multiple app version in ControlPanel Uninstall Program...Please help
https://www.dropbox.com/s/z62dzyu5tg5vi8o/multiple1.png?dl=0

Package.json
`"devDependencies": {
    "electron": "^9.0.0",
    "electron-builder": "^22.6.1"
  },
  "dependencies": {
    "@lottiefiles/lottie-player": "^0.3.0",
    "ajv": "^6.12.2",
    "auto-launch": "^5.0.5",
    "electron-config": "^1.0.0",
    "electron-push-receiver": "^2.1.3",
    "ffmpeg-static": "^2.3.0",
    "fluent-ffmpeg": "^2.1.2",
    "fs-extra": "^6.0.1",
    "getos": "^3.2.1",
    "image-compressor.js": "^1.1.4",
    "jsqr": "^1.3.1",
    "keytar": "^5.6.0",
    "lottie-web": "^5.6.10",
    "macaddress": "^0.2.9",
    "macos-release": "^2.3.0",
    "moment": "^2.26.0",
    "node-notifier": "^5.4.3",
    "pica": "^5.1.1",
    "redux": "^3.7.2",
    "redux-thunk": "^2.3.0",
    "redux-watch": "^1.1.1",
    "request": "^2.88.2",
    "tributejs": "^4.1.3",
    "unused-filename": "^1.0.0",
    "uuid": "^3.4.0",
    "windows-release": "^3.3.0",
    "xml-js": "^1.6.11"
  }`

**Comment by fjlJENNY** [comment]
same situation

**Comment by jhlee8804** [comment]
https://github.com/electron-userland/electron-builder/issues/4057#issuecomment-557570476

**Comment by robsonkades** [comment]
@phanpiseth9 @fjlJENNY Did you manage to solve it?
