### ISSUE TITLE
ERROR ITMS-90257: This bundle is invalid. The value for key CFBundleVersion

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5016]
* **Version**: 22.7.0

* **Electron Version**: 8.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  mac, mas, mas-dev

Using `BUILD_NUMBER` or any of CI build number values produces wrong Mac App Store build:

> ERROR ITMS-90257: "This bundle is invalid. The value for key CFBundleVersion [1.2.3.123] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

it would be better to set `buildVersion` as `buildNumber` without strange and unnecessary concatenation with `version`.

https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/appInfo.ts#L41-L48

Related issue:

* https://github.com/electron-userland/electron-builder/issues/4572
* https://github.com/electron-userland/electron-builder/issues/3730

**Comment by mahnunchik** [comment]
Also it is impossible to build version `0` because of `==`: https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/appInfo.ts#L42

🤦 🤦 🤦

**Comment by mahnunchik** [comment]
It is relevant

**Comment by mahnunchik** [comment]
![13736370577461](https://user-images.githubusercontent.com/780935/94364725-c2b5fd80-00cb-11eb-83e9-c8dc11723154.jpg)

**Comment by tseifried** [comment]
I have encountered the same problem, however I see the main issue being the documentation that is not clear about it:

> buildVersion String - The build version. Maps to the CFBundleVersion on macOS, and FileVersion metadata property on Windows. Defaults to the version. If TRAVIS_BUILD_NUMBER or APPVEYOR_BUILD_NUMBER or CIRCLE_BUILD_NUM or BUILD_NUMBER or bamboo.buildNumber or CI_PIPELINE_IID env defined, it will be used as a build version (version.build_number)
https://www.electron.build/configuration/configuration

But the documentation should actually be:
> buildVersion String - The build version. Maps to the CFBundleVersion on macOS, and FileVersion metadata property on Windows. Defaults to the version **defined in package.json + optional build_number (format: version.build_number). Whereas build_number is a value parsed from the following environment variables: BUILD_NUMBER, TRAVIS_BUILD_NUMBER, APPVEYOR_BUILD_NUMBER, CIRCLE_BUILD_NUM, BUILD_BUILDNUMBER, CI_PIPELINE_IID. First env variable that is "truthy" is used. If those environment variables are undefined or just contain just whitespace, build_number is not appended**

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5016#issuecomment-752091122
