### ISSUE TITLE
RPM Failure

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#502]
When trying to install an RPM (on opensuse): 

(Using command line rpm -ivh filename.rpm)

```
Warning: app-1.5.1.rpm: Header V4 RSA/SHA1 Signature, key ID f3a8c6bd: NOKEY
error: Failed dependencies:
        libappindicator1 is needed by app-1.5.1-1.x86_64
        libnotify-bin is needed by app-1.5.1-1.x86_64

```

Just double clicking seems to open it up in Ark as a simple archive file.

**Comment by develar** [comment]
Please specify Linux Distro.

**Comment by kunkinkan** [comment]
OpenSuse downloaded today, latest stable.

**Comment by develar** [comment]
Workaround: set [depends](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-depends) to `[]`.

**Comment by kunkinkan** [comment]
why are these depends used? I'm doing multiple targets simultaneously, will it affect deb ?

`      "target": ["deb", "rpm", "tar.gz"],
`

**Comment by develar** [comment]
Temp fix wil be in 10 minutes — use current deps only for deb. Real fix — help wanted.

**Comment by kunkinkan** [comment]
Yes, this works, however another issue; when trying to install a new version (or reinstall the same version): 

> Warning: app-1.5.2.rpm: Header V4 RSA/SHA1 Signature, key ID 3fb4cd59: NOKEY
> Preparing...                          ################################# [100%]
>         file /opt/App/resources/app.asar from install of app-1.5.2-1.x86_64 conflicts with file from package app-1.5.1-1.x86_64
>

**Comment by kunkinkan** [comment]
And one more thing, I noticed that the app is installed in the start menu under category "Other programs", any way to specify the app category like on mac (MAS) ?

**Comment by kunkinkan** [comment]
After uninstallation, can install again, but noticed (as above) that the rpm install name is: 

app-1.5.2-1 instead of just app-1.5.2.

**Comment by kunkinkan** [comment]
Has anyone been able to confirm this behavior?

**Comment by develar** [comment]
This issue about: RPM uses different package names then deb. Now we specify defaults deps only for deb. Ability to specify different deps per target is implemented, but not yet tested and documented.

If you ask about "app-1.5.2-1 instead of just app-1.5.2." — please open new issue. Please don't mix ;)

**Comment by sidneys** [comment]
@develar 

This does not work anymore (see #1338)

**Comment by logological** [comment]
From the discussion at develar/app-builder/issues/96 I gather this issue might not originate in electron-builder itself but rather in its dependency [develar/app-builder](https://github.com/develar/app-builder).  Can anyone confirm?
