### ISSUE TITLE
electron-updater latest.yml added to my generic server url

### ISSUE THREAD

**Issue by agnoam** [electron-userland/electron-builder#5020]
* **electron-builder Version**: 22.6.0

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.3.1

* **Target**: `Linux` and `Windows`

I'm using `electron-updater` when I try `autoUpdater.setFeedURL(http://localhost:3000/update/${process.platform}/${app.getVersion()});`. when I tried to make a request to my [hazel ](https://github.com/vercel/hazel)custom update server as response it throws this exception: 
```
Error: Error: Cannot find channel "latest.yml" update info: HttpError: 404 Not Found
"method: GET url: http://localhost:3000/update/win32/1.5.2/latest.yml?noCache=1e9l4bis0\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "content-security-policy": "default-src 'self'",
  "x-content-type-options": "nosniff",
  "content-type": "text/html; charset=utf-8",
  "content-length": "168",
  "date": "Sun, 31 May 2020 10:27:39 GMT",
  "connection": "keep-alive"
}
    at createHttpError (\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at newError (\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at GenericProvider.getLatestVersion (\node_modules\electron-updater\out\providers\GenericProvider.js:60:52)
```
So I just need to remove the `/latest.yml?noCache=1e9l4bis0` from the URL and everything should be fine. 
Does someone know how to do this ?

**Comment by Shandawei** [comment]
the error means your latest.yml on your server can not be got. you should chcek the file in your server,if the file /update/win32/1.5.2/latest.yml is exist and can be visited.

**Comment by agnoam** [comment]
I see. like I mentioned before, I'm using [hazel](https://github.com/vercel/hazel).
So by according to his documentation, `latest.yml` should not be in the url.
Is there a way that I can change the url manually ?

**Comment by aniketbiprojit** [comment]
@agnoam Did you find a solution to this?

**Comment by brennomarques** [comment]
I have this problem, any solution to indicate?

**Comment by aniketbiprojit** [comment]
I added a route to my custom server instead. Election updater needs latest.yml to check if the update needs to take place. So thae file should be available from the generic server.

**Comment by GorlikItsMe** [comment]
@aniketbiprojit Can you send here what exacly you change in hazel ?
