### ISSUE TITLE
Protocol doesn't work on Linux

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5024]
* **Version**: 22.7.0

* **Electron Version**: 8.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux - snap, AppImage

Deep linking doesn't work on linux.

https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock

Possible fixes:

* https://github.com/electron-userland/electron-builder/pull/5001
* https://github.com/electron-userland/electron-builder/pull/4909

**Comment by mahnunchik** [comment]
Related: https://github.com/electron-userland/electron-builder/issues/4035

**Comment by mahnunchik** [comment]
If `exec` is null then `%U` is added: https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/app-builder-lib/src/targets/LinuxTargetHelper.ts#L95-L105

**Comment by mahnunchik** [comment]
AAAAAAAAAAAAAAAAAA!

**Comment by gcascio** [comment]
I agree that this is still relevant. There are currently three PRs related to this problem, if there is anything I can do to get them merged I would be happy to help. In the meantime I applied a workaround, if anybody is interested [here](https://github.com/gcascio/electron-custom-url-workaround) is a minimal example.

**Comment by anteeek** [comment]
Yeah, same here. Hovewer for some reason snap works for me, while AppImage doesn't.

**Comment by lishid** [comment]
@mahnunchik Might want to close this issue as #5001 and #4909 have been merged.

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5024#issuecomment-739013018

**Comment by julien-boucly-needone** [comment]
+1

**Comment by mmaietta** [comment]
Just to confirm, is this still occurring on latest prerelease version v22.10.5?
I see PRs were merged in 22.9.1
https://github.com/electron-userland/electron-builder/releases/tag/v22.9.1

**Comment by lishid** [comment]
Should be safe to close since the two fixes have been merged. (see https://github.com/electron-userland/electron-builder/issues/5024#issuecomment-703473136)

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5024#issuecomment-855159867

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5024#issuecomment-907656735

**Comment by mmaietta** [comment]
Just to confirm, the deeplink association was also added to your desktop file?
```
  linux: {
    desktop: {
      ....
      MimeType: "x-scheme-handler/deeplink"
    }
  },
```

**Comment by tamerxkilinc** [comment]
I found out that it is working when using AppImageLauncher on Linux distributions like Ubuntu because AppImageLauncher correctly creates a .desktop file. 
Unfortunately without using AppImageLauncher it is not getting created and therefore we can't use custom url schemes to redirect to the Electron app.

**Comment by marf** [comment]
Hi @tamerxkilinc so isn't there any way to solve the issue?

**Comment by serverlesspolska** [comment]
I have the same problem on `"electron-builder": "23.0.2"`

```
    "linux": {
      "target": [
        "AppImage"
      ],
      "category": "Development",
      "executableArgs": ["--in-process-gpu"]
    },

The `--in-process-gpu` is not added while executing `AppImage` on Ubuntu.
```

**Comment by tamerxkilinc** [comment]
> Hi @tamerxkilinc so isn't there any way to solve the issue?

The only way I got it working was using the AppImageLauncher to install the Linux distribution of our app. However, I haven't looked further into it as our Linux user base is quite small.

**Comment by jt-l** [comment]
On Linux `tail -f /var/log/syslog` and when clicking on your deeplink check for an error message such as the one below: 

"Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service"

If you see this error in your logs install xdg-desktop-portal and xdg-desktop-portal-gtk and deeplinking should work assuming the rest of the setup is working.
