### ISSUE TITLE
How to configure snap target for publishing from CI

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5027]
* **Version**: 22.7.0

* **Electron Version**: any
* **Electron Type (current, beta, nightly)**: any

* **Target**: snap

How to configure credentials of `snap` target for publishing to store from CI?

* https://www.electron.build/configuration/snap
* https://www.electron.build/configuration/publish#snapstoreoptions

I've no idea according to documentation.

**Comment by adam-lynch** [comment]
This is my experience and might not the official way. When I tried to run it, I got an error that I wasn't logged in so I added a command to log in before electron-builder is ran. I run `echo LOGIN_DETAILS | snapcraft login --with -` (replace `LOGIN_DETAILS` with the output from `snapcraft export-login -`).

**Comment by mahnunchik** [comment]
![2012_06_09_02_26_cs403328_userapi_com_v403328804_dc2_mObl2sYhbag](https://user-images.githubusercontent.com/780935/96689612-f0b4f780-1382-11eb-9b81-e4c1443c5f26.jpg)

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5027#issuecomment-748609549

**Comment by tom-james-watson** [comment]
The details are all in the link I posted above. You can export your credentials as base64 and then set them as the `$SNAPCRAFT_LOGIN_FILE` environment variable. Then just

```
mkdir .snapcraft
echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
```

before trying to publish.
