### ISSUE TITLE
How to configure channels for snap publisher

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5028]
* **Version**: 22.7.0

* **Electron Version**: any
* **Electron Type (current, beta, nightly)**: any

* **Target**: snap

How to configure `channels` for snap publisher? It is not clear according to the documentation: https://www.electron.build/configuration/publish#snapstoreoptions

**Comment by mahnunchik** [comment]
![658](https://user-images.githubusercontent.com/780935/89108840-24dfe280-d43c-11ea-9456-2e6f4af9d24d.png)

**Comment by tom-james-watson** [comment]
This doesn't seem to work at the moment as far as I can tell.

**Comment by rasgo-cc** [comment]
It's not documented, but digging in the code you'll find this:

https://github.com/electron-userland/electron-builder/blob/ff242ab865f65987da4d95183a99c6fbaa7d3b78/packages/app-builder-lib/src/publish/SnapStorePublisher.ts#L18

So, it turns out you can pass Snap channels like this:
```
 snap: {
    publish:  {
        provider: "snapStore",
        channels: ['edge', 'stable'],
      }
  }
```
