### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by shaderbytes** [electron-userland/electron-builder#5035]
"electron-builder": "^22.7.0"

 "electron": "^9.0.2"
* **Electron Type (current, beta, nightly)**:

 "electron-updater": "^4.3.1"

Windows 

I followed this tutorial :
https://medium.com/@johndyer24/creating-and-deploying-an-auto-updating-electron-app-for-mac-and-windows-using-electron-builder-6a3982c0cee6

Everything works .. except the update .. nothing happens when relaunching the app. after changing the version number of the app as per the instructions..?

No errors in the console either.. it just does nothing

**Comment by gauravggg21** [comment]
Same Issue. If someone could just point out what is going wrong in this tutorial, it would be very helpful. Thanks.
