### ISSUE TITLE
Build AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#504]
[AppImage](http://appimage.org/) is a format for portable, distribution-agnostic binary software deployment for Linux without needing root permissions or installation. ([Wikipedia](https://en.wikipedia.org/wiki/AppImage_%28packaging_method%29))

Here is an example for Atom in AppImage format:
https://bintray.com/probono/AppImages/Atom/_latestVersion#files

And here is the script which produced it:
https://github.com/probonopd/AppImages/blob/master/recipes/atom/Recipe

While it is relatively easy to package an Electron-based app as an AppImage, it would be nice if this could be automated in electron-builder.

**Comment by kunkinkan** [comment]
oh shit, thats cool :)

**Comment by develar** [comment]
Sorry for dumb question, but quick search doesn't help — electron app requires libnotify and libappindicator packages — is this problem solved in the AppImage?

**Comment by probonopd** [comment]
Yes. Simply bundle them inside the AppImage.

**Comment by develar** [comment]
Ok, got it. Cool thing that electron-builder already provides tested and functional docker images, so,  first condition "Use an old system for building (at least 2-3 years old) to ensure the binaries run on older systems too" is already done.

**Comment by develar** [comment]
Sadly, that [fpm](https://github.com/jordansissel/fpm) doesn't support AppImage and even there is no issue.

**Comment by probonopd** [comment]
@develar Now there is: https://github.com/jordansissel/fpm/issues/1133

**Comment by probonopd** [comment]
[http://www.etcher.io/](http://www.etcher.io/) is using AppImage as their main format for distributing the Linux version of an Electron-based app. Here is their code that produces the AppImage:
https://github.com/resin-io/etcher/blob/master/scripts/build/linux.sh

**Comment by develar** [comment]
Looks like AppImage is a rescue for us. And Docker soon release dead simple docker installers for OS X and Windows. 

You can expect ApImage target in several weeks.

**Comment by probonopd** [comment]
@develar cool. Let me know if you run into any kind of issues you need help with.

**Comment by kunkinkan** [comment]
It means you will not be supporting deb and rpm any more in the future? There's some downsides to appimage too, namely it including old system binaries (I think). Will the appimageautoupdate work with electron as well? There's other tools as well, gnome flatpak, and ubuntu snappy apps that you may want to look at.

**Comment by develar** [comment]
@kunkinkan We are open source project.

I cannot in my free time test Linux Zoo and compute required packages for each format — https://github.com/electron-userland/electron-builder/issues/502 If you use opensuse&rpm — send PR or wait. i.e. — don't expect that RPM support will be polished if no-one will report issues.

> you will not be supporting

As we are open source project, there is no any guarantee ;) Current priority chain — OS X -> Windows -> NSIS -> Squirrel -> deb -> rpm -> AppImage.

**Comment by kunkinkan** [comment]
Of course, it was just a question, not a demand or anything :-) Unfortunately I'm not competent enough to contribute much to this project, I'm afraid :-) But I am reporting issues ;-)

**Comment by develar** [comment]
Why #509 is closed as backlog but this Appimage will be supported this week — see https://github.com/probonopd/AppImageKit/issues/166

**Comment by develar** [comment]
macOS: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#to-build-app-for-linux-on-macos (`xz` required now).

linux: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux (`xorriso ` required now). We don't bundle `xorriso` for Linux for now (only for macOS).

windows: use https://github.com/electron-userland/electron-builder/wiki/Docker (docker images updated, but not yet fully tested).

Thanks a lot @probonopd for amazing format.

Please note — we pack AppImage into `xz` to ensure that downloaded image can be just clicked to run (otherwise image file cannot be executed because no exec permission).

libnotify and auto update will be addressed in separate issues.

**Comment by atypicalprogrammer** [comment]
Please add version tag so that we can try it :-)

**Comment by develar** [comment]
Current known "critical" cosmetic issue — icon in the Uniny dock shown only if run as app, not on click on  image. https://github.com/probonopd/AppImageKit/issues/174

**Comment by atypicalprogrammer** [comment]
@devalar , still no version tag, and "dev-master" doesn't seem to work either. How can test?

**Comment by develar** [comment]
@atypicalprogrammer Release will be in 10 minutes (if Travis will be not broken again).

**Comment by probonopd** [comment]
> Current known "critical" cosmetic issue — icon in the Uniny dock shown only if run as app, not on click on image. probonopd/AppImageKit#174

If you launch the AppImage by double-clicking the AppImage, then install the desktop file when asked (using the desktopintegration script) and then quit the AppImage and launch it subsequently from the menu/Unity, then the icon should be there. Is it?

**Comment by develar** [comment]
>  then quit the AppImage and launch it subsequently from the menu/Unity, then the icon should be there. Is it?

Yes, it is. Commended https://github.com/probonopd/AppImageKit/issues/174#issuecomment-230678526 — "I am not Linux user. On OS X I always use Spotlight/Dock to run app. On Linux" — I don't is it real issue or not. But I am afraid we will get some issue reports about it soon.

**Comment by atypicalprogrammer** [comment]
Was travis broken? I still don't see next version? Sorry, just looking forward to this release I guess ;-)

**Comment by develar** [comment]
@atypicalprogrammer Yep, Travis broken. Currently, code singing issue fixed, but now npm broken. Damn. We use CircleCI for Linux and Travis for OS X. I am going to get rid of travis (or at least release from CircleCi, not from unreliable Travis).

**Comment by develar** [comment]
@atypicalprogrammer 5.11.0 is available.

**Comment by atypicalprogrammer** [comment]
OK so I don't understand it? I get a .xz file. When I double click it it asks to extract it. I select the file to extract, double click it, then it says "No applications found for "app-name".

**Comment by atypicalprogrammer** [comment]
Is there any way I can still use a system command as it appears java cannot be accessed from within the appimage?

**Comment by develar** [comment]
> Why is it packed as a xz file?

To prevent error `No applications found for "app-name"`. You cannot distribute only AppImage because `execute` flag will be cleared on download and file will be not executable. As a solution, we pack it into archive.

> Is there any way I can still use a system command as it appears java cannot be accessed from within the appimage? I don't want to bundle that.

Sample please. Do you execute `java ...` from your app code?

**Comment by atypicalprogrammer** [comment]
Never mind, sorry, java seems to be working now. Thanks!

**Comment by atypicalprogrammer** [comment]
Can you tell me what the message about creating a shortcut was about ? It only showed the first time, but I don't see any added shortcut on the desktop. (only my extracted app)

**Comment by develar** [comment]
@atypicalprogrammer I am not Linux user. I tested Ubuntu — "Spotlight" search — type in app name. i. e. it is added to menu/Unity.

**Comment by probonopd** [comment]
>  You cannot distribute only AppImage because execute flag will be cleared on download and file will be not executable. As a solution, we pack it into archive. 

That is not the recommended way for distributing AppImages, we should work out a better solution together that does not involve wrapping the AppImage inside an archive.

**Comment by develar** [comment]
@probonopd I am totally agree. But

* LZMA is better than ZIP — ~40% less size.
* I am not sure, but zip decompressing each time slightly slow down app launch.
* http://unix.stackexchange.com/questions/82578/why-is-that-when-i-download-a-binary-from-the-web-it-doesnt-have-executable-per/82579#82579

**Comment by atypicalprogrammer** [comment]
How would appimage delete leftover data? For example .config/App Name is left over after deleting the app itself.

`The key idea of the AppImage format is one app = one file. Every AppImage contains an app and all the files the app needs to run. In other words, each AppImage has no dependencies other than what is included in the targeted base operating system(s).`

**Comment by develar** [comment]
it is very disappointed when you download etcher app and... what, what I should do next? How do I run app? Opening terminal and `chmod +x`?

**Comment by develar** [comment]
> How would appimage delete leftover data? For example .config/App Name is left over after deleting the app itself.

icons and desktop files are also not deleted.

**Comment by probonopd** [comment]
> it is very disappointed when you download etcher app and... what, what I should do next? How do I run app? Opening terminal and chmod +x?

Right click, properties, permissions, execute as a program. Should be familiar to any Linux user, since this is standard in the Linux world.

Also see https://www.youtube.com/watch?v=7C9thHXPZd8 on an idea how to remove the need for this in the future.

Reasons for not putting an AppImage into an archive (among others):
- No need to unpack (e.g., a 700 MB file would take a couple of seconds to unpack)
- Possible for optional helper tools to manage AppImages (e.g., download, update, display in software centers etc.) - some additional functionality is planned in this area

**Comment by probonopd** [comment]
> How would appimage delete leftover data? For example .config/App Name is left over after deleting the app itself.

Same is true for versions installed by the package manager, `$HOME` is never touched.

**Comment by develar** [comment]
Next release: `.AppImage` extension added, not packed into `xz` anymore according to @probonopd suggestion.

**Comment by probonopd** [comment]
Is there any known example AppImage that has been created with electron-builder, or super-simple step-by-step instructions on how to make one?

**Comment by develar** [comment]
@probonopd https://github.com/develar/onshape-desktop-shell/releases 0.5.1 uses AppImage instead of deb. Just set target — https://github.com/develar/onshape-desktop-shell/blob/master/package.json#L33

**Comment by probonopd** [comment]
Thanks @develar - how would I use this to generate an AppImage of an app already using electron-builder? E.g., 

* Get and install npm from https://nodejs.org/dist/v4.4.7/node-v4.4.7-linux-x64.tar.xz
* git clone https://github.com/BHSPitMonkey/hipchat-electron

And now?

**Comment by develar** [comment]
@probonopd hipchat-electron uses outdated 3.x version.
* edit `package.json`: change `^3.23.0` electron-builder version to `^5.13.1`

   You will get some deprecation warnings on build, but should be ok.
* edit `package.json` — add after ` "build": { ... }`:

   ```
   , "linux": {
      "target": ["AppImage"]
    },
   ```

* `npm install`
* `npm dist` or `npm dist -- --linux=AppImage` if you want to explicitly set target and do not edit `package.json`

**Comment by probonopd** [comment]
@develar sorry if this is OT, but I would like to make sure I understand how to use this so that I can add a description to the AppImageKit wiki on how to package Electron apps. This is what I did:

```
# Install npm 6 and other prerequisites
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs icnsutils graphicsmagick

wget https://github.com/BHSPitMonkey/hipchat-electron/archive/master.zip
unzip master.zip
cd hipchat-electron-master/

sed -i -e 's|"electron-builder": ".*",|"electron-builder": "next",|g' package.json

npm install
npm run dist -- --linux=AppImage
```

It looks like an AppImage gets generated, but it refuses to work:

```
$ ./dist/HipChat\ Electron-1.0.3.AppImage 
/tmp/.mount_JuWoYc
installed: X-AppImage-Version=1.0.3 image: X-AppImage-Version=1.0.3
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'open'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/tmp/.mount_JuWoYc/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_JuWoYc/usr/bin/resources/app/main.js:4:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

Looking closer, I think the `desktopintegration` script got installed as `AppRun` -- this cannot work. AppRun is supposed to run the app, but the script that is called "AppRun" in this AppImage doesn't seem to do that, or even try; but merely install the desktop integration?

**Comment by probonopd** [comment]
With most Electron apps from GitHub I tried to package as an AppImage so far, I get **npm ERR! missing script: dist**:
* eye-sigil/curse-linux
* khornberg/docker-indicator
* loveky/EasyHost
* mudpuddle/inviewer
* nainemom/nai-electron-quick-start

Is there a simple way to package these anyway? Or what exactly would I have to ask the upstream authors to do?

**Comment by develar** [comment]
> With most Electron apps from GitHub I tried to package as an AppImage so far, I get npm ERR! missing script: dist:

`dist` is the name of script in the `package.json`. And electron-builder version must be 5+. If electron-builder version is 2, it is not easy to upgrade to 5.  khornberg/docker-indicator

* khornberg/docker-indicator — 2.
* loveky/EasyHost — 2
* mudpuddle/inviewer — 2
* nainemom/nai-electron-quick-start — 5 Only this package can build AppImage.

If no `dist` script in the `package.json` — run tool directly: 

```
./node_modules/.bin/build --linux=AppImage
```

> Looking closer, I think the desktopintegration script got installed as AppRun

Yes, we use own version of desktopintegration and don't use AppRun — https://github.com/electron-userland/electron-builder/blob/master/templates/linux/AppRun.sh

> You are assuming that the binary has the same name as the desktop file - I don't know whether that is a valid assumption. 

We generate all — desktop file, executable. https://github.com/electron-userland/electron-builder/blob/master/src/targets/appImage.ts So, I am sure, it is app error, not our error (please note, that hipchat-electron uses outdated 3.x version, so, maybe something goes wrong).

**Comment by probonopd** [comment]
> You are assuming that the binary has the same name as the desktop file - I don't know whether that is a valid assumption.

> We generate all — desktop file, executable. https://github.com/electron-userland/electron-builder/blob/master/src/targets/appImage.ts 

I tried
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs icnsutils graphicsmagick

wget https://github.com/irccloud/irccloud-desktop/archive/master.zip
unzip master.zip
cd *-master/

npm install
npm run dist -- --linux=AppImage
```
and an AppImage gets generated, but it wants to execute `usr/bin/irccloud` when in fact only `usr/bin/irccloud-desktop` is there (and even the .desktop file is called `irccloud-desktop.desktop`).

So could it be that this is not very robust?

**Comment by develar** [comment]
@probonopd Fixed, error was in bash script.

**Comment by develar** [comment]
AppImage is a default target for Linux since version 6 (will be released tomorrow).

**Comment by probonopd** [comment]
There should be a way for application authors to have fine-grained control over what ends up in the `$APPNAME.desktop` file; e.g. it should be possible to contain the correct `Categories=` and `MimeType=` entries for the app.

**Comment by develar** [comment]
@probonopd Fixed.

> should be a way for application authors to have fine-grained control over what ends up in the $APPNAME.desktop

[build.linux.desktop](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-desktop)

e.g.:
```
{foo: "bar"}
```

> the correct Categories=

[build.linux.category](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-category)

**Comment by Skywalker13** [comment]
@probonopd 
> 
>     it is very disappointed when you download etcher app and... what, what I should do next? How do I run app? Opening terminal and chmod +x?
> 
> Right click, properties, permissions, execute as a program. Should be familiar to any Linux user, since this is standard in the Linux world.
> 
> Also see https://www.youtube.com/watch?v=7C9thHXPZd8 on an idea how to remove the need for this in the future.
> 
> Reasons for not putting an AppImage into an archive (among others):
> 
>     No need to unpack (e.g., a 700 MB file would take a couple of seconds to unpack)
>     Possible for optional helper tools to manage AppImages (e.g., download, update, display in software centers etc.) - some additional functionality is planned in this area
> 


IMHO, the AppImage should be saved in a tar file (just TAR without compression), then the executable flag will be preserved and the "unpack" is very fast.

For a end-user it's easier... I know some Linux end-users where changing the permissions is not familiar at all.

**Comment by develar** [comment]
@Skywalker13 https://github.com/electron-userland/electron-builder/issues/893#issuecomment-259479401

**Comment by develar** [comment]
Now you can run AppImage produced by electron-builder on Elementary OS also. — https://github.com/electron-userland/electron-builder/issues/1082#issuecomment-272794622

**Comment by probonopd** [comment]
> I get npm ERR! missing script: dist

Running into this here again, https://travis-ci.org/probonopd/readium-desktop#L2604 - using the latest `electron-builder`. Do you have any idea why this might happen?

Here is the `travis.yml`:
https://github.com/probonopd/readium-desktop/blob/patch-1/.travis.yml

**Comment by develar** [comment]
@probonopd this project has "package" script. Instead of 

npm run build 
npm run dist

Just 

npm run package 

should be used

**Comment by develar** [comment]
https://github.com/probonopd/readium-desktop/blob/master/package.json#L26
