### ISSUE TITLE
Unsually large size of delta.nupkg files windows

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#505]
I know there are issues with similar names to this one, and I'm pretty sure there's an answer for this
[here](https://github.com/electron/windows-installer/issues/85) already, but if anything I'd like some clarification!
My full.nupkg files are about 80 MB, and delta.nupkg files are about 40 MB. I don't think this is normal as I expect them to be in the range of ~5-10 MB.
Background info: I'm only building x64 windows artifacts. Also I'm using only one `package.json`, not 2.

**Comment by develar** [comment]
I am sure your issue is https://github.com/electron-userland/electron-builder/issues/464 please attach log.

**Comment by mzmousa** [comment]
Will do tomorrow morning.

**Comment by mzmousa** [comment]
Ah, I found my mistake. I was packaging the app inside my development folder. I packaged it elsewhere and I got my delta files to be ~ 5 MB. :confetti_ball:

**Comment by develar** [comment]
> Ah, I found my mistake. I was packaging the app inside my development folder. 

Please explain and I add check to prevent such issues in the future. What do you mean "I was packaging the app inside my development folder."?

**Comment by mzmousa** [comment]
Inside my development folder, I had a number of downloaded node modules such as electron builder, electron prebuilt, other npm testing things, etc, that were getting packaged inside in my app that were unnecessary.
