### ISSUE TITLE
App Crash while generating from electron-builder

### ISSUE THREAD

**Issue by akbarbashakm** [electron-userland/electron-builder#5054]
Issue Details

Version:
"electron": "6.0.12",
"electron-builder": "^21.2.0"
os: macOS Catalina 10.15.5

Expected Behaviour
User should be prompted to grant microphone access.

Actual Behaviour
Application crashes

Replication Procedure

git clone 'https://github.com/akbarbashakm/electron-issue.git'
npm run start (it may crash if you are run in vsCode so better run in terminal it will work)
npm run package
open dist -> mac -> sample (Application crash)
Ya mostly lot of people reported the same is in a while... Please resolve asap else can you guyz suggest me how to resolve it...

While running app through vsCode (using npm run start) also it crash that's not a matter i am ok to run the app in terminal.
But i am facing the same issue while while generating the build using electron-builder..

**Comment by replac5** [comment]
run `npm i @replace5/app-builder-bin` and replace node_modules/app-builder-bin files with the package @replace5/app-builder-bin files
