### ISSUE TITLE
Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: 3w+qBq2mOeOWmM3i8PJfIvnhfbvs4eHAP7kw427ohPwKViWB7/8VTP8ZrlbXduqwAr6DHgHUcRluyY6yvTe+/g==, expected: U87SHKbG5EFxtaGuATUhNwx6Gg+EwXqEnls3GUhWMZPOlZPalMA5x+Ek1BFazBHhZuYGRR4wLf6W6oUK1BNG4A==. Directory for cached update will be cleaned

### ISSUE THREAD

**Issue by richard457** [electron-userland/electron-builder#5055]
"electron-builder": "22.7.0",

* **Version**: 22.7.0

* **Electron Version**:7.0.0
* **Electron Type (current, beta, nightly)**:
electron-updater

* **Target**: windows

I am having issue when updating the electron app that it fails to check the checksum which result in full download instead of downloading only changes. please help.

**Comment by harshitsilly** [comment]
@richard457  Hi, try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/).. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac
