### ISSUE TITLE
Error: --target-arch cannot be used with build provider 'multipass'

### ISSUE THREAD

**Issue by adam-lynch** [electron-userland/electron-builder#5059]
* **Version**: 22.7.0

* **Electron Version**: 9
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux snap

When building for snap with the latest snapcraft version (4.0.4), that error is thrown. More detail in https://github.com/develar/app-builder/issues/40

**Comment by mdiluz** [comment]
I have hit this as well, the problematic code is here: https://github.com/snapcore/snapcraft/blame/master/snapcraft/cli/_options.py#L232

I'm unsure though, it appears correct

**Comment by adam-lynch** [comment]
@mdiluz this is an intentional change by snapcraft. See my linked issue above

**Comment by mdiluz** [comment]
It has now been fixed though :) https://github.com/snapcore/snapcraft/commit/b29e100eb6b255e338adb5971ce0f6e7d97a2b19

**Comment by adam-lynch** [comment]
Yes

**Comment by adam-lynch** [comment]
Yes
