### ISSUE TITLE
Help code signing on Travis on OSX

### ISSUE THREAD

**Issue by joeferraro** [electron-userland/electron-builder#506]
Hi, despite my best efforts, I'm unable to get `electron-builder` to properly sign my app during a Travis build on OSX. I have followed these [directions](https://github.com/electron-userland/electron-builder/wiki/Code-Signing), but I can't seem to get a proper identity loaded into the keychain, which is obviously thwarting the code sign step. I know I can create a separate shell script to do the code signing, but I'd prefer to keep all of my build steps natively within `electron-builder`.

Here is the warning I get from `electron-builder`: **Warning: App is not signed: CSC_LINK or CSC_NAME are not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing**

Other things:
- I'm serving my .p12 file via Google Drive and I've verified the https url is working
- I've set and encrypted (via `travis encrypt`) `CSC_LINK` and included in my .travis.yml
- I've set and encrypted (via `travis encrypt`) `CSC_KEY_PASSWORD` and included in my .travis.yml
- I've verified that my certificate is valid

Any ideas? Am I right to assume that I shouldn't have to do anything beyond providing access to a valid certificate and key password? I don't need to do any manual keychain set up during my build (`electron-builder` handles that?)?

**Comment by develar** [comment]
I am sure that your problem is a bash escaping for password or link.

1) Use https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings UI to set env.
2) Encode file to base64 (see step 2, https://github.com/electron-userland/electron-builder/wiki/Code-Signing) and set `CSC_LINK` to base64 data.
3) "make sure to escape special characters (for bash) accordingly" in the password.

**Comment by joeferraro** [comment]
@develar Cheers, base64 encoding the cert worked. Perhaps it'd be helpful to add some logging if `electron-builder` can't properly download/read a file when `CSC_LINK` is set to a https URL?

**Comment by develar** [comment]
> can't properly download/read a file when CSC_LINK is set to a https URL?

Well, it is travis usabiliry issue. 
1) You see in the log: `export CSC_LINK=[secure]`
2) You think all is ok.
3) But actually `export` is failed and electron-builder just cannot see env — no such env, it is not defined.

electron-builder cannot check is it defined or not. Travis must warn user if env is not properly escaped.
