### ISSUE TITLE
d3dcompiler_47.dll got block

### ISSUE THREAD

**Issue by nssoldier** [electron-userland/electron-builder#5061]
* **Version**: 21.2.0

* **Electron Version**:7.3.1
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows 10

When I run built installer, my 360 safeguard block file d3dcompiler_47.dll with message "Usually trojans will modify these DLL attack pieces to start their own invasion of your electricity. If it is not your initiative to modify, please block"
![103606203_2386168065009282_2580576443011023358_n](https://user-images.githubusercontent.com/39984442/84394103-b09c7600-ac26-11ea-983f-feaf739d814b.jpg)

How can I fix it?

**Comment by chenweijianGZ** [comment]
I also have this problem
