### ISSUE TITLE
.d.ts are forcefully ignored and cannot be added

### ISSUE THREAD

**Issue by inca** [electron-userland/electron-builder#5064]
* **Version**: 22.7.0
* **Electron Version**: 7.0.0
* **Electron Type (current, beta, nightly)**: current
* **Target**: all

Related: #4545 #1131 #4165 #1352

I'm desperately trying to get Electron Builder to not ignore `.d.ts` files.
Unfortunately, the `d.ts` extension is [hardcoded](https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/fileMatcher.ts#L21) and it is only possible to un-ignore them by modifying the code (none of the other workarounds work).

I've considered sending a PR to just remove it from the list (which tbh makes sense given that `.d.ts.map` is not ignored, for example) — but I think the approach itself is flawed, because these were supposed to be the "safe defaults" and it should always be possible to override the defaults.

It would be interesting to hear what the official maintainers think.

**Comment by saurabh-deep** [comment]
@develar - We have a similar issue, where one of our dependencies (in node_modules) has the travis and circleci yml files which we need. Electron Builder is forcefully ignoring these files and we haven't been able to override the default exclusions to include these files in the build. Getting those files as extraResources is not an option as those files should be present in app.asar itself.

Please suggest if it is possible at all to override the default exclusions? And if yes, how do we do that?

Thanks much!

**Comment by shubham-root** [comment]
@develar this looks like a niche but repeatedly occurring issue (referring to #1352). I have npm library that has examples I need to use in my electron code. It happens to be kept in /examples folder, which is excluded by default too, and it looks like I am left with no option than to modify the electron-builder source to include all possible `example` folders inside node_modules libraries.

Hard coding defaults seem like an unnecessary work for electron-builder when the documentation could easily mention the list of default for people to use in their package.json or config.yaml.

**Comment by adipascu** [comment]
This issue is relevant and not resolved.

**Comment by slztfn** [comment]
Had to use this hacky workaround by patching the electron-builder source code:

package.json
```package.json
{
  "postinstall": "node patch-builder.mjs"
}
```

patch-builder.mjs
```typescript
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const filePath = join(
  __dirname,
  "../node_modules/app-builder-lib/out/fileMatcher.js",
);
const original = readFileSync(filePath, "utf-8");

const PATCH_COMMENT = "// patched by patch-builder.mjs";
if (original.startsWith(PATCH_COMMENT)) {
  console.log("[patch-builder] already patched");
  process.exit(0);
}
const patched = original.replace(",cc,d.ts,", ",cc,");
if (patched === original) {
  console.error("[patch-builder] pattern not found");
  process.exit(1);
}

writeFileSync(filePath, `${PATCH_COMMENT}\n${patched}`, "utf-8");
console.log("[patch-builder] patched app-builder-lib");

```
