### ISSUE TITLE
Generic Repo, Error: Cannot find channel "latest.yml" update

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [electron-userland/electron-builder#5070]
- Version: 4.3.1
- Electron Version: 9.0.3
- Electron Builder Version : 22.7.0
- Electron Type (current, beta, nightly): current
- Target: nsis

I am trying to use generic http server for update. When i use npm http-server package for update, it works well but when i want to use my iis localhost or any other http adress, it doesnt work.

- **Error**
Error: Error: Cannot find channel "latest.yml" update info: HttpError: 404 Not Found
"method: GET url: http://localhost:8080/latest.yml?noCache=1eard8d08 Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404."

- **Package.json**
 "build": {
    "publish": [
      {
        "provider": "generic",
        "url": "http://localhost:8080/",
        "publishAutoUpdate": true
      }
    ],
    "appId": "com.update",
    "productName": "electron-auto-update-example",
    "win": {
      "target": "nsis",
      "verifyUpdateCodeSignature": false
    },
    "mac": {
      "target": [
        "dmg"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false
    },
    "asar": true
  }

**Comment by abdurrahmanyildirim** [comment]
Resolved!
I added to mime type to this file C:\Windows\System32\inetsrv\config\applicationHost.config

<staticContent>
      <mimeMap fileExtension=".yml" mimeType="text/x-yaml" />
</staticContent>

**Comment by shickk** [comment]
> Resolved!
> I added to mime type to this file C:\Windows\System32\inetsrv\config\applicationHost.config
> 
> ```
> <staticContent>
>       <mimeMap fileExtension=".yml" mimeType="text/x-yaml" />
> </staticContent>
> ```

My inetsrv folder is empty, is there another workaround ?

**Comment by abdurrahmanyildirim** [comment]
@shickk i dont know. This solution for iis. If you already have iis and this file is still empty, try to find other ways of add mime type. The problem was mime type for me. Good luck.
