### ISSUE TITLE
electron-forge-maker-snap doesn't work with latest forge

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5078]
* **Version**: 22.7.0

* **Electron Version**: any
* **Electron Type (current, beta, nightly)**: any

* **Target**: snap

Current [`electron-forge-maker-snap`](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-forge-maker-snap) package doesn't work with latest [electron-forge](https://github.com/electron-userland/electron-forge/).

```bash
An unhandled rejection has occurred inside Forge:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at buildForge (/home/user/app/node_modules/app-builder-lib/src/forge-maker.ts:16:22)
    at new exports.default (/home/user/app/node_modules/electron-forge-maker-snap/main.js:13:10)
    at _default (/home/user/app/node_modules/@electron-forge/core/src/api/make.ts:128:15)
    at /home/user/app/node_modules/@electron-forge/cli/src/electron-forge-make.ts:44:5 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by mahnunchik** [comment]
![IMGP2282-1024x680](https://user-images.githubusercontent.com/780935/90341604-38c14200-e001-11ea-995b-541f7196fc8d.jpg)

**Comment by burnhamup** [comment]
electron-forge-maker-nsis seems to be having the same problems. 

I was able to get past this error by specifying a config key for 'dir', but started running up other errors.

**Comment by burnhamup** [comment]
Something along the lines of 
```
const MakerBase = require('@electron-forge/maker-base').default;
const buildForge = require('app-builder-lib').buildForge;

Object.defineProperty(exports, "__esModule", {
  value: true
})

class MakerSnap extends MakerBase {

  isSupportedOnCurrentPlatform() {
    return Promise.resolve(true);
  }

  async make(options) {
    return buildForge(options, {linux: [`snap:${options.targetArch}`]})
  }
}

exports.default = MakerSnap;
```
might work, but I'm not up to speed on how these forge plugins need to be configured.

**Comment by mahnunchik** [comment]
It is relevant!

**Comment by lysnikolaou** [comment]
Hey everyone and thanks for all of your work on this!

Is there any plan of providing maker targets for electron-forge v6? Would a PR implementing something like it be accepted/released?
