### ISSUE TITLE
403 error while trying to download update from S3. 

### ISSUE THREAD

**Issue by ifitzsimmons** [electron-userland/electron-builder#5079]
* **Version**:  22.3.6

* **Electron Version**: 7.1.13
* **Electron Type (current, beta, nightly)**: 

* electron-updater: v4.2.0

* **Target**: dmg

My app is successfully detecting that there is an update available, but returns a `403 error` when it tries to fetch the `mac.zip` file for download. The file exists in S3. Does the code need an Apple Developer signature before it can be downloaded or something? 

**Error**:
```
error: Error in auto-updater. Error: Cannot download "https://bucket-name.s3.amazonaws.com/app-15.0.0-mac.zip", status 403: Forbidden
``` 

**Code**
```js
const opts = {
  service: 's3',
  method: 'GET',
  region: 'us-east-1',
  host: 'bucket.s3.us-east-1.amazonaws.com',
  path: process.platform === 'win32' ? '/latest.yml' : '/latest-mac.yml'
};

aws4.sign(opts, {
  accessKeyId: process.env.UPDATER_AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.UPDATER_AWS_SECRET_ACCESS_KEY
});

autoUpdater.requestHeaders = opts.headers;

if (isDev) {
  autoUpdater.updateConfigPath = path.join(
    __dirname,
    '../../dev-app-update.yml'
  );
  autoUpdater.checkForUpdates();
} else {
  autoUpdater.checkForUpdatesAndNotify();
}

autoUpdater.on('checking-for-update', () => {
  logger.info('Checking for update...');
});

autoUpdater.on('update-available', () => {
  logger.info('Update available.');
});

autoUpdater.on('update-not-available', () => {
  logger.info('Update not available.');
});

autoUpdater.on('error', err => {
  logger.error(`Error in auto-updater. ${err}`);
});

autoUpdater.on('download-progress', progressObj => {
  let logMessage = `Download speed: ${progressObj.bytesPerSecond}`;
  logMessage = `${logMessage} - Downloaded ${progressObj.percent}%`;
  logMessage = `${logMessage} (${progressObj.transferred}/${progressObj.total})`;
  logger.info(logMessage);
});

autoUpdater.on('update-downloaded', () => {
  logger.info('Update downloaded');
});
```

**Comment by harshitsilly** [comment]
@ifitzsimmons  I have tried this url - https://bucket-name.s3.amazonaws.com/app-15.0.0-mac.zip.. for me it is giving access denied. Please make sure the release url should be set public with no authentication set

**Comment by SuperKirik** [comment]
Does anybody have some update on this ?
I have the same issue.

**Comment by annd22** [comment]
Same issuse here.
The S3 bucket is public and I can download object from the link, but when autoUpdater (electron-updater) try to download, it get the error:
`Cannot download "https:........exe", status 403: Forbidden`

**Comment by netflt** [comment]
> Same issuse here. The S3 bucket is public and I can download object from the link, but when autoUpdater (electron-updater) try to download, it get the error: `Cannot download "https:........exe", status 403: Forbidden`

I got this issue too, have you resolved this issue?

**Comment by annd22** [comment]
@netflt 
Set the provider to `generic` solve the issue
* Note: The S3 bucket is public and I can download object from the link,
```
const options = {
  provider: 'generic',
    url: ''
  } as any;

  const autoUpdater: any = process.platform === 'win32' ? new NsisUpdater(options) : new MacUpdater(options);
```

**Comment by netflt** [comment]
@annd22 Great, really appreciate your help, I'll try
