### ISSUE TITLE
nsis include defined macros are called during packaging, not during installation

### ISSUE THREAD

**Issue by electronWeb** [electron-userland/electron-builder#5085]
HI, @sethlu 
I've added the below script inside build/installer.nsh to customize the nsis installer but the commands are executed during packaging process, not during the installation of the installer.
```
!macro customHeader
  !system "echo 'customHeader' > ${BUILD_RESOURCES_DIR}\customHeader"
!macroend

!macro preInit
  !system "echo ${BUILD_RESOURCES_DIR} 'C:\resourcedirpath'"
  !system "echo 'preInit' > ${BUILD_RESOURCES_DIR}\preInit"
!macroend

!macro customInit
  !system "echo 'customInit' > ${BUILD_RESOURCES_DIR}\customInit"
!macroend

!macro customInstall
  !system "echo 'customInstall' > ${BUILD_RESOURCES_DIR}\customInstall"
!macroend

!macro customUnInstall
  !system "echo 'customUnInstall' > ${BUILD_RESOURCES_DIR}\customUnInstall"
!macroend
```

**Comment by mohammedshoib** [comment]
hello @artl-dev ,
I am having same issue, not sure where to start debugging, is your problem solved? Can you give more infor on how it solved?

**Comment by iotzy** [comment]
2024.2.18, 
i have same question 

 following the docs (https://www.electron.build/configuration/nsis#custom-nsis-script), customInstall always called during packaging
