### ISSUE TITLE
3rd party files for 3rd party application inside electron

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#5086]
* **Version**:  22.7.0

* **Electron Version**: 8.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows

In my electron app I am trying to run an exe through child process which works fine using ```electron .```

But on packing it to standalone exe the third party exe is not working 

here is my directory structure

```
App
|__resources
|   |___thirdparty.exe
|   |___thirparty_file.txt
|__main.js
|__index.html
```
thirdparty_file.txt is directly imported in thirdparty.exe both the third party exe in itself and using ```electron .``` runs as expected. But while using app_portable.exe or App.exe in build folder the thirdparty.exe is unable to find the thirdparty_file.txt. 

My electron builder configuration
```json
"build": {
    "productName": "App",
    "appId": "my.App",
    "win": {
      "target": [
        "portable"
      ]
    },
    "portable": {
      "artifactName": "app_portable.exe"
    },
    "extraFiles": [
      {
        "from": "resources/",
        "to": "Resources/",
        "filter": [
          "**/*"
        ]
      }
    ]
  }
```

**Comment by mxswat** [comment]
I still have this issue and the documentation about this isn't clear

**Comment by mxswat** [comment]
@MD-AZMAL 

"extraFiles": {
                    "from": "tool",
                    "to": "./resources/app.asar.unpacked/tool/"
                },

the tool folder is in the root of the project
I access my files using

path.join(process.resourcesPath, '/app.asar.unpacked/tool/tool.exe')

**Comment by MD-AZMAL** [comment]
unfortunately that doesn't work... the support files for exe are still not accessible

**Comment by mxswat** [comment]
> unfortunately that doesn't work... the support files for exe are still not accessible

Dude I made it working on my repo, same code that I posted

**Comment by MD-AZMAL** [comment]
@mxswat can you share the repo link
