### ISSUE TITLE
No way to auto-update 64 and 32 bit Windows installer separately

### ISSUE THREAD

**Issue by JannisX11** [electron-userland/electron-builder#5087]
* **Version**: 22.7.0
* **Electron Version**: 8.2.1
* **Electron Type**: current
* **Electron Updater:** 4.3.1
* **Target**: Windows NSIS

It is currently not possible to auto update 64 and 32 bit Windows versions individually. The Windows `latest.yml` file can only contain the link to one of the installers and there is no API to modify the download URL before downloading. If the installer for the wrong arch is downloaded, it cannot be installed. A possible workaround could be to use a combined installer for automatic updates, but that would unnecessarily double the download time. The lack of this simple feature makes it very difficult for me to implement this auto updater.

**Comment by gabrielhl91** [comment]
Hey, i've been having the same issue, and i was able to get around that situation using **setFeedUrl()** method from **autoUpdater**, altough it's not recomended, it worked. the code that i've implemented to get that working was, on my app.js ( Main Process)

```
const arch = process.arch;
if (arch == "x64") {
    autoUpdater.setFeedURL({ "provider": "generic", "url": "https://server/files/windows/64bit/" });
} else if (arch == "ia32") {
    autoUpdater.setFeedURL({ "provider": "generic", "url": "https://server/files/windows/32bit/" })
}

```
and in my server structure i've separated those folders. Of course, you will have to build the installers separately and upload those latest.yml files that are created in the process, but i guess its better than a combined installer.
