### ISSUE TITLE
The application Electron needs to be updated. Quit Electron to continue updating?

### ISSUE THREAD

**Issue by zallesov** [electron-userland/electron-builder#5089]
Hi, fellow devs.
Since yesterday i'm getting this annoying popup.

> The application Electron needs to be updated. Quit Electron to continue updating?
> [Not Now] [Quite and Update]

Clicking either button closes the popup but it comes back in a minute or so. Seems to me the update silently fails. 

I have at least two electron apps installed Slack and Postman that I know of. I don't even know which it comes from.
Even thou I'm not developing with Electron I'm a software developer. If you tell me where to look I can give some more info.

Tips on how to kill it are highly appreciated.

PS. System Mac Catalina

**Comment by amazingmarvin** [comment]
I guess if I were you I would wait for the popup to appear then run `ps -e | grep -i electron` and start killing stuff with `kill -9 xyz` where `xyz` is the first column of the processes listed by the first command that look like electron apps.  Then when you see the popup go away you'll know which app is the culprit.
