### ISSUE TITLE
Reduce Electron memory usage on Windows 10 by adding Segment heap type in app manifest

### ISSUE THREAD

**Issue by pashvin** [electron-userland/electron-builder#5091]
* **Version**: 22.7.0

* **Electron Version**: 8.x
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

This is enhancement request. Windows 10 Update 2004 has new attribute in application manifest file. Setting heapType to SegmentHeap can use modern heap system and can reduce memory usage. I don't know which component creates manifest but if we can add this new type , then that will improve memory usage. It might be good idea to put package.json flag to turn it on/off in case if some developer do not like or create side effects. 

Ref: https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests

**Comment by richiedevs** [comment]
Yeah, I like the idea, and It would be great to have it implemented in electron.
