### ISSUE TITLE
Invalid Provisioning Profile error when uploading Mas Build

### ISSUE THREAD

**Issue by johannesjo** [electron-userland/electron-builder#5092]
* **Version**:  22.7.0

* **Electron Version**: 9.0.4

* **Target**:  Mac OS

When uploading to the store I get the following error:
```
*** Error: Errors uploading 'app-builds/mas/superProductivity-5.4.0.pkg': (
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90283: \"Invalid Provisioning Profile. 
The provisioning profile included in the bundle com.super-productivity.app [com.super-productivity.app.pkg/Payload/superProductivity.app] is invalid. [Missing code-signing certificate.] For more information, visit the macOS Developer Portal.
```

The other logs look fine to me:
```
  • electron-builder  version=22.7.0 os=18.7.0
  • loaded configuration  file=/Users/johannesmillan/IdeaProjects/super-productivity/build/electron-builder.mas.yaml
  • writing effective config  file=app-builds/builder-effective-config.yaml
  • packaging       platform=mas arch=x64 electron=9.0.4 appOutDir=app-builds/mas
  • signing         file=app-builds/mas/superProductivity.app identityName=Developer ID Application: Johannes (16ADSK323) identityHash=D10278B411682SAAF9EF54D9F8896ASD153D3384 provisioningProfile=none
  • signing         file=app-builds/mas/superProductivity.app identityName=3rd Party Mac Developer Application: Johannes (16ADSK323) identityHash=B55EC8C3FB70ASDCDA32FD80490F485D2D509A71E provisioningProfile=embedded.provisionprofile
✨  Done in 49.84s.
```

I am pretty sure that the certificates and embedded profiles are correctly configured. I tried the process with several fresh combos of certificate and profile. Any clues what might be causing this?

The config can be found here:
https://github.com/johannesjo/super-productivity/blob/master/build/electron-builder.mas.yaml

**Comment by msavin** [comment]
@johannesjo any luck with this?

**Comment by johannesjo** [comment]
@msavin unfortunately not...

**Comment by msavin** [comment]
I’m going crazy... every minute that Electron saves you, you have to pay back in dealing with Electron Builder

**Comment by johannesjo** [comment]
This is still relevant. Just tested it again. Same error.

**Comment by msavin** [comment]
Can confirm after upgrading my device to macOS 10.15.6

**Comment by maksymkulia** [comment]
Same issue. The 2-nd day trying to solve it.

**Comment by johannesjo** [comment]
Maybe you can upvote the original issue (thumbs up). This makes it easier to see for the devs that multiple people are affected.

**Comment by maksymkulia** [comment]
> @msavin unfortunately not... I've been trying to make mac store builds work for almost 2 years now and I sunk many many hours into it. There is always something not working.

Have you tried this manual building:
[Mac App Store Submission Guide](https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide)

I am not sure if it worth wasting time?

**Comment by johannesjo** [comment]
Haven't tested it fully yet, but apparently `app-builds/mas/superProductivity.app/Contents/embedded.provisionprofile` contained the wrong provisioningprofile. I had multiple of those at the root of my project (e.g. `x.provisioninprofile`) which I copied to `embedded.provisioningprofile` before the build as needed. Not 100% sure yet, but this might be worth investigating.

**Comment by maksymkulia** [comment]
Ok, I'll try tomorrow with really simple app.

**Comment by johannesjo** [comment]
I had success with it! Which is truley amazing after 2 years of trying to get this dam thing deployed to the mac store. Let's see what the next obstacle will be :)

**Comment by maksymkulia** [comment]
@johannesjo OMG, I guess it would be great if you will publish your success story on Medium or personal blog.😎

Where should I dig to make it finally work?

**Comment by johannesjo** [comment]
At least for me the issue was caused by the comment above. You find all related code and configuration here: https://github.com/johannesjo/super-productivity

**Comment by ahmadwaliesipick** [comment]
> At least for me the issue was caused by the comment above. You find all related code and configuration here: https://github.com/johannesjo/super-productivity

@johannesjo  i am also struggling from last few months to submit mas build to Apple store. I have tried lot of methods to sign the build, after sign the app crash on launch there are no any error in log. Once i set sandbox to false then app is not crashing. But transporter reject to upload because of sandbox is not set true. Do you have any experience with this issue? Looking forward for your help. Thanks

**Comment by johannesjo** [comment]
@ahmadwaliesipick I'd recommend checking out the [source code](https://github.com/johannesjo/super-productivity) but I've to admit that I am not sure if the mas store version crashes or not because I don't have another device to test.

**Comment by ahmadwaliesipick** [comment]
> @ahmadwaliesipick I'd recommend checking out the [source code](https://github.com/johannesjo/super-productivity) but I've to admit that I am not sure if the mas store version crashes or not because I don't have another device to test and the review is not yet done.

I have seen your source code and i am doing same the package.json and plist info are same. Once i create dmg without sandbox true then app is build is not crashing. I have tried my app build in another mac but still it is crashing. 

I have also enabled debug mode of electron-builder and there are no any error in logs. The build is properly signing with provided provision profile and certificates. 
@johannesjo  how did you verify working of signed pkg?

**Comment by johannesjo** [comment]
@ahmadwaliesipick I didn't. I try to check this tomorrow.

**Comment by ahmadwaliesipick** [comment]
@johannesjo  I am able resolved the build sign issues and uploaded build to Apple Store. Soon app will be available at apple store. :-)

**Comment by Ali-Baker** [comment]
> I had success with it! Which is truley amazing after 2 years of trying to get this dam thing deployed to the mac store. Let's see what the next obstacle will be :)

Just to be clear. You need to remove all or your `.provisionprofile` and keep only one with name `embedded.provisionprofile`

**Comment by pedrumgolriz** [comment]
@Ali-Baker thank you for that info. I'm still struggling with this. I guess I don't know exactly which profile to embed, I've tried all of them. I still get this error: 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/5402482/194359206-4a1e5ba7-06ec-4d0f-adc4-70ae9a32813a.png">

**Comment by Ali-Baker** [comment]
> @Ali-Baker thank you for that info. I'm still struggling with this. I guess I don't know exactly which profile to embed, I've tried all of them. I still get this error: <img alt="image" width="551" src="https://user-images.githubusercontent.com/5402482/194359509-2e76b20d-87a8-493b-8912-483551217d89.png">

@pedrumgolriz you need a profile that is linked to `Mac App Distribution` certificate

**Comment by pedrumgolriz** [comment]
@Ali-Baker thanks, but still getting the same error message with the right cert. 
![image](https://user-images.githubusercontent.com/5402482/194374213-1a2bb836-b7cb-4c83-987e-e51bdb4b2040.png)

**Comment by Talhaasif95** [comment]
I have having the same issue still, can someone help me in this regard. I am using transporter to upload the application to mac store.
