### ISSUE TITLE
Using electron-builder for signing and publishing Windows app (with auto-update) by using EV dongle

### ISSUE THREAD

**Issue by jkdev601** [electron-userland/electron-builder#5094]
Version: 22.3.2
Electron Version: 8.0.3
Target: Windows

I want to ask about electron app signing process for Windows build on Ubuntu with electron-builder. I’m using EV certificate from digicert token. I’m following the steps described here: https://www.electron.build/tutorials/code-signing-windows-apps-on-unix and I’m able to sign the app by running this command:

`osslsigncode sign -verbose -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so -pkcs11module /lib/libeToken.so -h sha256 -n app-name -t https://timestamp.verisign.com/scripts/timestamp.dll -certs /link/to/cert.pem -key 'key-id-here' -pass 'password' -in /link/to/app.exe -out /link/to/app.signed.exe` 

But I want to integrate this with electron-builder by using custom signing script.
```
...
    "win": {
      "target": "nsis",
      "sign": "./sign.js"
    },
...
```
I know that electron-builder also generates .blockmap and .yml files which are required by electron-updater to handle the update process. I’ve noticed that sign.js script is called 8 times during building process, my question here is can I use osslisgncode tool in this custom sign.js script triggered by electron-bulider? If yes, there should be a possibility to pass the file name to sign.js scirpt to dynamically fill signing command ? My other question here is that possible to use custom signing script in electron-builder together with – p always option to also generate .blockmap and .yml files to handle auto-update for signed application.

**Comment by ymschaap** [comment]
I've been recently in a similar situation (EV dongle for Windows build) and eventually wrote down what I did here:

https://github.com/ebourg/jsign/issues/79#issuecomment-638382470

And used this gist as sign.js:
https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444

Hope it helps.

**Comment by jkdev601** [comment]
@ymschaap, thanks for your response. Could you please provide me more details about your approach with this post-build hook, are you also using `electron-builder -p always --win` to generate files required for auto-update mechanism from electron-updater ?

**Comment by ymschaap** [comment]
First of all, what you want demands some tinkering, and is not novice developer activity. 

Below are my steps you need to also undertake.

Flow:
```node -> npm run -> package.json -> electron-builder build -> script windows-sign.js -> java jsign -> output signed exe```

Setup:
1. I have setup `java` locally, and included `[jsign-3.1.jar](https://github.com/ebourg/jsign/releases/tag/3.1)` in my project root.
2. `jsign` to be setup to identify your dongle, so create a hardwareToken.cfg file as `--keystore`. More info [here](https://ebourg.github.io/jsign/).
3. Then create a javascript file to sign your exe similar to this [gist](https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444) which calls jsign from node. 
4. The automate this, in package.json under `win` add `"sign": "scripts/windows-sign.js"` (above file), see [here](https://www.electron.build/configuration/win#WindowsConfiguration-target).

Run
1. With `npm run package` it runs `electron-builder build --publish always --win` under `scripts`.
2. package.json has the configuration for electron-builder and builds an exe.
3. `windows-sign.js` is called automaticly when the exe is finished building (see setup step 3) and signs the exe using your EV dongle.

**Comment by jkdev601** [comment]
@ymschaap thanks for your help, your solution with jsign worked.

**Comment by PatricNox** [comment]
Sorry for hijacking, but i'm sitting with a similar case as you @jkdev601 . 

I found out that my code signing on the built electron exe (installer) doesn't sign  the binaries within it, does your way of signing it also include the contents to be signed or how is that part handled?

Maybe @ymschaap has an answer to this as well?

**Comment by ebourg** [comment]
@PatricNox Signing the installer doen't sign the binaries inside it, you have to sign each executable separately.

**Comment by PatricNox** [comment]
> @PatricNox Signing the installer doen't sign the binaries inside it, you have to sign each executable separately.

I see! thanks @ebourg. I think I'm missing something here then for above replies in how to sign it, doesn't  @ymschaap solution sign the builded exe? which is the installer?

**Comment by ShinHyunJong** [comment]
@ymschaap Thanks for your instruction. During following your guide I met  Unable to load the keystore hardwareToken.cfg error. I put the hardwareToken.cfg file on root of my project and content as your gist. error as below.

java.security.KeyStoreException: Unable to load the keystore hardwareToken.cfg
        at net.jsign.KeyStoreUtils.load(KeyStoreUtils.java:82)
        at net.jsign.PESignerHelper.build(PESignerHelper.java:272)
        at net.jsign.PESignerHelper.sign(PESignerHelper.java:377)
        at net.jsign.PESignerCLI.execute(PESignerCLI.java:109)
        at net.jsign.PESignerCLI.main(PESignerCLI.java:40)
Caused by: java.io.IOException: load failed
        at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:766)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at net.jsign.KeyStoreUtils.load(KeyStoreUtils.java:75)
        ... 4 more
Caused by: javax.security.auth.login.LoginException
        at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1303)
        at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:866)
        at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:753)
        ... 6 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_PIN_LOCKED
        at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
        at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1287)
        ... 8 more

**Comment by ebourg** [comment]
@ShinHyunJong What command line did you use? Did you set the PIN with the storepass parameter?
