### ISSUE TITLE
Unable to build for ARM64

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-builder#5095]
* **Version**: 22.7.0

* **Electron Version**: 9.0.4
* **Electron Type (current, beta, nightly)**: Current

* **Target**: All targets (ARM64)

I'm trying to produce arm64 artifacts for my app, for all platforms, from macOS 10.14, but the process gets stuck and never finishes, no error is outputted. I can only see the `multipass` process spinning forever from the task amanger.

**Comment by rankjie** [comment]
I believe the building process has hardcoded to be only building Arch.x64 for macOS right now.
https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/app-builder-lib/src/macPackager.ts#L103

Since Apple is about to release ARM-based Mac this year, we need to support building for ARM64.

**Comment by fabiospampinato** [comment]
Still relevant.

**Comment by deathlyrage** [comment]
Still relevant.

**Comment by fabiospampinato** [comment]
I like how the stupid bot just closes issues like that, shouldn't there be an issue tracking compatibility with Apple Silicon? @develar

**Comment by deathlyrage** [comment]
Apple silicon launching at the end of the year, google resolved ARM64 issues, Upstream is going to have ARM64 builds for apple silicon soon.  We should be tracking this one. Lots of electron builder apps have a lot of upgrade work to do to even open.

**Comment by mmaietta** [comment]
Just for posterity's sake and future readers, we probably should consolidate Apple Silicon/arm64 discussions in this ticket: https://github.com/electron-userland/electron-builder/issues/5392#issuecomment-725441867
An investigation is ongoing there.

**Comment by fabiospampinato** [comment]
Closing as this repo isn't issue-friendly, I don't want to receive notifications from the idiot bot anymore.
