### ISSUE TITLE
Add ability to use environment variables in electron-builder.yml

### ISSUE THREAD

**Issue by ms-dosx86** [electron-userland/electron-builder#5096]
* **Version**:  22.7.0
* **Electron Version**: 9.0.0
* **Electron Type (current, beta, nightly)**: current

Currently I see that there is section in the docs https://www.electron.build/configuration/configuration#environment-variables-from-file about using env variables with electron-builder.env, but no examples which syntax should be used to get variables in electron-builder.yml. Even if it's possible to use electron-builder.env, it's not that convenient as usual .env file. As mentioned by @jsheffers in https://github.com/electron-userland/electron-webpack/issues/329, we don't want to maintain two .env files. Would be nice if I could set nodejs env variable during CI and use it inside electron-builder.yml. My problem is to use different urls for auto updates for different environments (dev, stage, prod).

**Comment by Donil** [comment]
@ms-dosx86 
You can use this syntax for a value: `${env.ENV_VAR_NAME}`.
For instance:
```
...
artifactName: '${env.PRODUCT_NAME}.${ext}'
...
```

**Comment by mvandak** [comment]
@Donil 
It is not working for me this way.
If I configured
```
extraMetadata:

  version: '${env.VUE_APP_VERSION}'
```
effective config is the same and builded file name is produced as `appName-${env.VUE_APP_VERSION}.AppImage`

If I use js config, the process.env.VUE_APP_VERSION is present, but I have another error issue with ENONT file rename electron -> appName

**Comment by mvandak** [comment]
@ms-dosx86 Try to use electron-builder.js instead of yaml. I used it this way and it prepares effective config with env variables I expect, but I can't build it because of ENOENT error the cause I can't find, then it uses defaults. I am curious if this will work for you.

electron-builder.js example
```js
const builder = require("electron-builder")

const config = {
  appId: process.env.CUSTOM_ID,
  extraMetadata: {
    productName: process.env.CUSTOM_ID,
    version: process.env.CUSTOM_VERSION
  },
  copyright: "Copyright © 2020",
  win: { target: "nsis", icon: "src-electron/icons/logo.ico" },
  nsis: {
    oneClick: false,
    perMachine: true,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    installerIcon: "src-electron/icons/logo.ico",
    installerHeader: "src-electron/icons/header.bmp",
    installerSidebar: "src-electron/icons/sidebar.bmp",
    uninstallerIcon: "src-electron/icons/logo.ico",
    uninstallerSidebar: "src-electron/icons/sidebar.bmp",
    deleteAppDataOnUninstall: false,
    installerLanguages: ["cs_CZ", "sk_SK", "en_US"],
    multiLanguageInstaller: true,
    artifactName: "${productName}_${version}_setup.${ext}"
  }
}

builder.build({ config })
```

**Comment by ms-dosx86** [comment]
@mvandak I tried `electron-builder.js` and it didn't work for me too. It complains that `app.asar` doesn't have a `index.js` file. You can still use .yml file and pass env vars through cli when you run build `ENV_VAR=env_val npm run electron-builder` in my case. But it's not convenient for local dev tho. As a workaround I still use a self written script that adds env vars to `electron-builder.yml`.

**Comment by mvandak** [comment]
@ms-dosx86 I have it little bit complicated as far as we are using vue-cli to build electron and cordova and I want it to use node env variables from common env file for both, electron and cordova

**Comment by mvandak** [comment]
For us, when using vue-cli, it helped to move electron-builder.js configuration to vue.config.js
Then it works and we can use process.env variables to be used for effective config.
