### ISSUE TITLE
Incorrect path resolution causes not work with yarn workspace

### ISSUE THREAD

**Issue by Akimotorakiyu** [electron-userland/electron-builder#5097]
## what happened
when use  `yarn workspaces`, it cause `InvalidConfigurationError: Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.0.5") is not fixed in project.`

## why
https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/packages/app-builder-lib/src/electron/electronVersion.ts#L16-L52

```ts
// ...
return (await readJson(path.join(projectDir, "node_modules", name, "package.json"))).version
// ...
```

## somet info
according to [https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_require_resolve_request_options](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_require_resolve_request_options)

it should be something like 
```ts
// ...
return (await readJson(path.join(require.resolve(name), "..", "package.json")).version
// ...
```

but can't use `require.resolve` because of 

https://github.com/electron-userland/electron-builder/blob/7b335dbd7e5ca754598ca93318be1404fc518485/tsconfig-base.json#L4

**Comment by Akimotorakiyu** [comment]
temp solution, work with `build` script
`build.ts`
```ts
// ...
import { getElectronVersion } from "./electronVersion";
async function build(){
  // ...
 const electronVersion = await getElectronVersion();

 builder.build({
      // ...
      config: {
        // ...
        electronVersion: electronVersion,
        // ...
    }
  })
}

build()
```
`electronVersion.ts`
```ts
const path = require.resolve("electron");
import { join } from "path";
import { readFile } from "fs-extra";

export async function getElectronVersion(): Promise<string> {
  const data = await readFile(join(path, "..", "package.json"));
  const version = JSON.parse(data.toString())?.version;
  console.log(version);
  return version;
}
```

**Comment by nuochong** [comment]
me to

**Comment by chenjinchao1997** [comment]
me too

**Comment by Tajnymag** [comment]
This is still relevant as of 22.11.5

**Comment by LacombeJ** [comment]
Saw this error on version 25.1.8. It was solved for me by adding electronVersion configuration to electron-builder.yaml.

_electron-builder.yaml_
```yml
electronVersion: "^38.1.2"
```
