### ISSUE TITLE
Adding arguments to the output application 'launcher'

### ISSUE THREAD

**Issue by chamerling** [electron-userland/electron-builder#5099]
Hello,

I did not found in the documentation the way to add some default arguments to the generated application using electron-builder. Here is the use case:

- I have to enable/disable features from feature-flags coming as application parameters ie `electron --featureX=true --featureY=false`
- I expect to build some specific versions of an application based on these feature flags and distribute them to end users ie the user just have to launch the app from the binary generated by electron-builder

Is there a way to do this?
Thanks a lot

**Comment by chamerling** [comment]
Hello,

No one ever have this type of thing to do?

**Comment by divisumma18** [comment]
Same here: I'd like to pass some parameters from the setup executable to the installed app. Is there a way to do it?
