### ISSUE TITLE
Signing error on OS X after upgrade to version 5.x.x

### ISSUE THREAD

**Issue by otbe** [electron-userland/electron-builder#510]
Hi,

Im building an unsigned app for OS X. In version ```~4.2.6``` of ```electron-builder``` I get this as expected:
```
Warning: App is not signed: CSC_LINK or CSC_NAME are not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
```

Now I upgraded ```electron-builder``` to the latest version and I get:
```
Command failed: codesign --sign com.apple.idms.appleid.prdxxx --force path Helper EH
````
Build is broken.

I thought if I leave CSC_LINK and CSC_NAME unset it should work as before. Whats wrong with my setup? Is there a new configuration for this?

Thanks!

**Comment by develar** [comment]
Please attach here result `security find-identity -v -p codesigning -p appleID`

**Comment by develar** [comment]
Set env `CSC_IDENTITY_AUTO_DISCOVERY` to `false` as temp workaround.

**Comment by otbe** [comment]
Output of ```security find-identity -v -p codesigning -p appleID``` is:
```
0 valid identities found
  1) 04340D1211128CE52F26D2B5E57C4CECB6D4901D "com.apple.idms.appleid.prd.677655544355643177425769764b4e2f7646642b72513d3d"
  2) 6958D43B23AFA3C6FE257C2A54DC63AFB576F135 "com.apple.idms.appleid.prd.677655544355643177425769764b4e2f7646642b72513d3d"
  3) ECCB6CC552B67686A27B3B6DBFB899B9B370112E "com.apple.idms.appleid.prd.677655544355643177425769764b4e2f7646642b72513d3d"
     3 valid identities found
```

**Comment by otbe** [comment]
Wow. That was quick!

Thanks a lot!
