### ISSUE TITLE
SyntaxError: Unexpected string when running electron-builder install-app-deps with yarn@berry

### ISSUE THREAD

**Issue by Thomb89** [electron-userland/electron-builder#5102]
* **Version**: 22.7.0

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: default target 

I tried to integrate yarn2 (yarn@berry).
Our repo contains an Electron App with sqlite3 as a dependency, that get "built" by node-pre-gyp when building the app.
Whenn electron-builder tries to rebuild the native dependencies, the following error is thrown:

```
    • electron-builder  version=22.7.0
    • rebuilding native dependencies  dependencies=sqlite3@4.2.0 platform=linux arch=x64
    • rebuilding native dependency  name=sqlite3 version=4.2.0
    ⨯ cannot execute  cause=exit status 1
                    errorOut=/tmp/tmp-2426rUi2pP55zel/yarn:2
    exec "/usr/local/bin/node" '/project/electron-builder-yarn2/node_modules/yarn/bin/yarn.js' "$@"
             ^^^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string
        at wrapSafe (internal/modules/cjs/loader.js:1047:16)
        at Module._compile (internal/modules/cjs/loader.js:1097:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
        at Module.load (internal/modules/cjs/loader.js:977:32)
        at Function.Module._load (internal/modules/cjs/loader.js:877:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
        at internal/main/run_main_module.js:18:47

                    command=/tmp/tmp-2426rUi2pP55zel/node /tmp/tmp-2426rUi2pP55zel/yarn run install
                    workingDir=/project/electron-builder-yarn2/node_modules/sqlite3
```
A minimal Reproduction can be found here: https://github.com/Thomb89/electron-builder-yarn2

This error can be reproduced in the docker image (i used electronuserland/builder:wine) with the following steps:
* docker run -it electronuserland/builder:wine /bin/bash
* npm i -g yarn@berry
* git clone https://github.com/Thomb89/electron-builder-yarn2.git
* cd electron-builder-yarn2
* yarn
* yarn electron-builder install-app-deps

While yarn@berry is still not released (current version is 2.0.0-rc.27), will it be fully supported in the future?

**Comment by NoahAndrews** [comment]
I see this issue as well, even with `nodeLinker` set to `node-modules` in `.yarnrc.yml`, which disables Yarn 2's Plug and Play stuff.

**Comment by NoahAndrews** [comment]
It's also worth noting that while the version number of Yarn 2 shows it as an RC, nothing at http://yarnpkg.com suggests that it's merely a prerelease or that it's not ready for use yet.

**Comment by freshollie** [comment]
I'm still experiencing this, worth keeping open

**Comment by felix-h** [comment]
Same for me.

**Comment by Saul-Mirone** [comment]
Same for me.

**Comment by denniske** [comment]
Seems to be fixed with `"electron-builder": "^22.10.5"`.

At least for me the output changed from

```
➤ YN0006: │ aoe2companion@workspace:. lists build scripts, but is referenced through a soft link. Soft links don't support build scripts, so they'll be ignored.
➤ YN0007: │ aoe2companion@workspace:. must be built because it never did before or the last one failed
➤ YN0009: │ aoe2companion@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/jw/tky1gysn61q3rvvf2d16kfcm0000gn/T/xfs-f1f09467/build.log)
➤ YN0009: │ aoe2companion@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/jw/tky1gysn61q3rvvf2d16kfcm0000gn/T/xfs-f1f09467/build.log)
```

to only

```
➤ YN0006: │ aoe2companion@workspace:. lists build scripts, but is referenced through a soft link. Soft links don't support build scripts, so they'll be ignored.
➤ YN0007: │ aoe2companion@workspace:. must be built because it never did before or the last one failed
```

**Comment by Frizi** [comment]
I'm experiencing this with electron-builder 22.11.7. Downgrading to 22.10.5 didn't help for me.

**Comment by NoahAndrews** [comment]
> I'm experiencing this with electron-builder 22.11.7. Downgrading to 22.10.5 didn't work for me.

Have you tried updating yarn with `yarn set version berry`?

**Comment by Frizi** [comment]
Yes, I am in fact using the built from source version of yarn. The error is almost identical to the one in the original post (modulo the file paths), so I didn't bothered posting it again.

**Comment by NoahAndrews** [comment]
Interesting. What version of Electron are you on? For us, updating yarn to version `2.4.2`, electron to version `11.4.9`, and electron-builder to `22.10.5` fixed it.

**Comment by Frizi** [comment]
```
$ yarn --version
3.0.0-rc.9.git.20210706.hash-d0386b48
```
electron-builder: 22.11.8
electron: previously 10.4.3, updated to 13.1.7 and the issue persists.

**Comment by Matthew-McRaven** [comment]
I just say this today, yarn `3.1.1`, electron-builder `22.10.5`.

`nodeLinker` is `node-modules`.
