### ISSUE TITLE
[Win] npm run dist fails, remoteReleases issue on localhost

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#511]
First of all, I've got no idea where to post this issue; here or on *electron/windows-installer* or on *Squirrel.Windows* ...

First question:
Where should `remoteReleases` point to, exactely? It's not clear from the docs. I set up an [electron-release-server](https://github.com/ArekSredzki/electron-release-server) on localhost:1337 (default) and set `"remoteReleases": "http://download.localhost/update/win32/<MYVERSION>/RELEASES"`. 

Now `npm run dist` fails with this:

> Attemping to sync URL as remote RELEASES folder
> Failed to sync URL as GitHub repo: ...
> System.AggregateException: ... System.Net.Http.HttpRequestException: ... could not resolve host 'download.localhost'
> ...
> Error: ...\electron-winstaller-fixed\vendor\SyncReleases.exe failed with exit code: 4294967295
> ...

Seems like `download.localhost:1337` as well as `download.127.0.0.1:1337` cannot be resolved.

**Comment by black-snow** [comment]
Oh waint, just found this https://github.com/ArekSredzki/electron-release-server/blob/master/docs/update-windows.md

Will try that.

**Comment by develar** [comment]
https://github.com/develar/onshape-desktop-shell/blob/master/package.json#L34

```
"remoteReleases": "https://github.com/develar/onshape-desktop-shell"
```

**Comment by develar** [comment]
> Seems like download.localhost:1337 as well as download.127.0.0.1:1337 cannot be resolved.

If you want to use subdomains on localhost, you need to modify `/etc/hosts`.

**Comment by black-snow** [comment]
@develar Thanks for the reply. I'm not using github for releases. So where should `remoteReleases` point at / what's the directory structure?

**Comment by develar** [comment]
@black-snow This question should be addressed to your update server ;)

**Comment by black-snow** [comment]
@develar I'm now using a plain webserver for testing. I'd just like to know what the directory structure must look like.

**Comment by develar** [comment]
@black-snow I can only guess since it is a Squirrel.Windows implementation. `remoteReleases` should point to a directory where `RELEASES ` file located (if path is foo/bar/RELEASES then url should be `foo/bar`).

**Comment by develar** [comment]
Reference: https://github.com/Squirrel/Squirrel.Windows/blob/master/src/SyncReleases/Program.cs

**Comment by black-snow** [comment]
@develar Thanks again.
Wondering how to have multiple releases then - isn't there a RELEASES file generated everytime I run `npm run dist`? Am I supposed to put the newest RELEASES there and have the `.exe` etc. in some subdirs?

**Comment by develar** [comment]
> Wondering how to have multiple releases then - isn't there a RELEASES file generated everytime I run npm run dist?

No, if you set (and you *should* set) `remoteReleases` then we call SyncReleases — Squirrel will download RELEASES file and latest available release to build delta update.

**Comment by black-snow** [comment]
Oh okay, guess I'm starting to get how this works. Thanks you very much.

One last question: Let's say I have a version 0.0.1. I threw RELEASES, .exe and .nupkg on the server. Now I'm building 0.0.2. It's fetching RELEASES etc. and everything went okay. Now I want to threw the 0.0.2 on the server. What do I upload? .exe of course and .nupkg and probably some delta file but RELEASES, too? I'd think so.

**Comment by develar** [comment]
> What do I upload? .exe of course and .nupkg and probably some delta file but RELEASES, too? I'd think so.

Yes, RELEASES must be uploaded as well. It is better to use https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts and file issue to support another provider (currently, only GitHub supported).

**Comment by black-snow** [comment]
Great, guess I'm all set now. Kudos for the great support.
