### ISSUE TITLE
splash screen is not working for portable electron builder app

### ISSUE THREAD

**Issue by dasung** [electron-userland/electron-builder#5112]
* **Version**: "22.7.0",

* **Electron Version**:  "^9.0.0"
* **Electron Type (current, beta, nightly)**: stable 
 

* **Target**: windows

Hi,

I am trying to add a splash screen to an electron app. 
According to my understanding application itself takes some time to launch until extract files and loading electron.
During this time there is no feedback to the user and makes some confusion. 

Basically I followed this article,
https://dev.to/montoyaaguirre/adding-a-splash-screen-to-portable-electron-builder-apps-34d3

But nothing happens (no splash.bmp showing ) after creating the installer.

 ```javascript
  "build": { 
    ....
    "win": {
      "target": [
        "portable"
      ]
    },
    "portable": {
      "artifactName": "${name}-v${version}-portable.${ext}",
      "splashImage": "..\\..\\..\\..\\public\\splash.bmp"
    }
   ....
  }
```
Greatly appreciate if you can help me to solve this issue.

**Comment by ItsTommyGun** [comment]
@dasung hey, did you come up with a working solution?

**Comment by dasung** [comment]
> @dasung hey, did you come up with a working solution?

Still no specific answer.
I am no longer expect to see my application launches just after installation. 
Simply,
` "runAfterFinish": false,` in package.json.

**Comment by ItsTommyGun** [comment]
@dasung This may not be the answer you want to hear but I had at least a minimal success by showing the native Windows "installer/loader". Make sure to set the silent mode to normal or put it in a comment. Also remove the _hidewindow_ part. Using [this](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/portable.nsi) as reference:

`
; set SetSilent to normal or just remove it I guess
  !ifndef SPLASH_IMAGE
    SetSilent silent 
  !endif
[...]
; remove completely
  !ifdef SPLASH_IMAGE
    HideWindow 
  !endif
`

Tell me if this works for you!
