### ISSUE TITLE
Generate electron app.exe which will ask for user input during installation (using electron-builder and nsis)?

### ISSUE THREAD

**Issue by rachitsakhidas** [electron-userland/electron-builder#5113]
* **Version**:  ^22.7.0

* **Electron Version**: ^9.0.3
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis

I am trying to generate electron app.exe with the use of electron-builder and NSIS, which should ask user input at time of installation.

Following is my package.json.
...
"build": {
    "appId": "com.electron.test",
    "productName": "test",
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "assets/icon.ico"
    },
    "nsis": {
      "warningsAsErrors": false,
      "installerIcon": "assets/icon.ico",
      "runAfterFinish": false,
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "installerHeader": "assets/installerHeader.bmp",
      "include": "build/installer.nsh"
    },
    "mac": {
      "category": "your.app.category.type"
    }
}
...

I want to display custom page Between Select Location Page and Installation Progress Page.
Following is my installer.nsh which is create one custom page i.e. ask for user to input username and password.

 

!include "EnvVarUpdate.nsh"
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"

Var Dialog
Var UserLabel
Var UserText
Var UserState
Var PassLabel
Var PassText
Var PassState

;--------------------------------
; Show install details
    ShowInstDetails show

;--------------------------------
;Interface Settings

    !define MUI_ABORTWARNING

Page custom nsDialogsPage nsDialogsPageLeave

Function nsDialogsPage

    nsDialogs::Create 1018
    Pop $Dialog

    ${If} $Dialog == error
        Abort
    ${EndIf}

    ${NSD_CreateLabel} 0 0 100% 12u "Username:"
    Pop $UserLabel

    ${NSD_CreateText} 0 13u 100% 12u $UserState
    Pop $UserText

    ${NSD_CreateLabel} 0 39u 100% 12u "Password:"
    Pop $PassLabel

    ${NSD_CreatePassword} 0 52u 100% 12u $PassState
    Pop $PassText

    nsDialogs::Show

FunctionEnd

Function nsDialogsPageLeave

    ${NSD_GetText} $UserText $UserState
    ${NSD_GetText} $PassText $PassState

    ${If} $UserState == ""
        MessageBox MB_OK "Username is missing."
        Abort
    ${EndIf}

    ${If} $PassState == ""
        MessageBox MB_OK "Password is missing."
        Abort
    ${EndIf}

    StrCpy $1 $UserState
    StrCpy $2 $PassState

    FileOpen $9 $INSTDIR\credentials.txt w
    FileWrite $9 "$1:$2"
    FileClose $9
    SetFileAttributes $INSTDIR\credentials.txt HIDDEN|READONLY

FunctionEnd

Section
SectionEnd

!macro customHeader
    
!macroend

!macro preInit
    
!macroend

!macro customInstall
    ${EnvVarUpdate} $0 "PATH" "A" "HKLM" "$INSTDIR"
!macroend

!macro customUnInstall
    ${un.EnvVarUpdate} $0 "PATH" "R" "HKLM" "$INSTDIR"
!macroend

Please provide any solution.

Thanks & Regards
Rachit V. Sakhidas

**Comment by rachitsakhidas** [comment]
When we try to display installation page via using nsis from package.json like mentioned below:

"nsis": {
	"warningsAsErrors": false,
	"installerIcon": "assets/icon.ico",
	"runAfterFinish": false,
	"oneClick": false,
	"perMachine": true,
	"license": "LICENSE.txt", // remove this from package.json
	"allowToChangeInstallationDirectory": true, // remove this from package.json
	"installerHeader": "assets/installerHeader.bmp",
	"include": "build/installer.nsh"
}

Note: 	1)	We need to remove some of key because we want to manage installation pages via code from installer.nsh and if try to achieve this then we dont want to display same page twice when we try to run .exe file.
		2)	Also we need to rename our license.txt with terms.txt. Please go through below mentioned code of installer.nsh file.


!include "EnvVarUpdate.nsh"
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "WinMessages.nsh"

!define MUI_CUSTOMFUNCTION_GUIINIT myGuiInit



Var Dialog
Var Label
Var Checkbox1
Var Checkbox1_State
Var Checkbox2
Var Checkbox2_State
Var Checkbox3
Var Checkbox3_State

/** This is required to keep proper sequence **/
!insertMacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${BUILD_RESOURCES_DIR}/terms.txt"
!insertmacro MUI_PAGE_DIRECTORY
Page custom nsDialogsPage nsDialogsPageLeave


Function myGuiInit
	StrCpy $Checkbox1_State "1"
    StrCpy $Checkbox2_State "1"
    StrCpy $Checkbox3_State "1"
FunctionEnd


Function nsDialogsPage
    !insertmacro MUI_HEADER_TEXT "Select Additional Tasks" "Which additional tasks should be performed?"
	nsDialogs::Create 1018
	Pop $Dialog

	${If} $Dialog == error
		Abort
	${EndIf}

	${NSD_CreateLabel} 0 0 100% 20u "Select the additional tasks you would like Setup to perform while installing, then click Next."
	Pop $Label

    ; MessageBox MB_OK "1: $Checkbox1_State 2: $Checkbox2_State 3: $Checkbox3_State"

	${NSD_CreateGroupBox} 0% 25u 100% 80u "PostgreSQL Database Settings"
    Pop $0

        ${NSD_CreateCheckbox} 3% 40u 100% 12u "Add action to Windows Explorer file context menu"
		Pop $Checkbox1
        ${If} $Checkbox1_State == ${BST_CHECKED}
            ${NSD_Check} $Checkbox1
        ${EndIf}
		
		${NSD_CreateCheckbox} 3% 55u 100% 12u "Add action to Windows Explorer file context menu"
		Pop $Checkbox2
        ${If} $Checkbox2_State == ${BST_CHECKED}
            ${NSD_Check} $Checkbox2
        ${EndIf}
		
		${NSD_CreateCheckbox} 3% 70u 100% 12u "Add to PATH (required shell restart)"
		Pop $Checkbox3
        ${If} $Checkbox3_State == ${BST_CHECKED}
            ${NSD_Check} $Checkbox3
        ${EndIf}
		
	nsDialogs::Show

FunctionEnd

Function nsDialogsPageLeave
	${NSD_GetState} $Checkbox1 $Checkbox1_State  // value is available inside $Checkbox1_State
    ${NSD_GetState} $Checkbox2 $Checkbox2_State	 // value is available inside $Checkbox2_State
    ${NSD_GetState} $Checkbox3 $Checkbox3_State  // value is available inside $Checkbox3_State
FunctionEnd


Thanks & Regards
Rachit V. Sakhidas

**Comment by Puneetkumarpal** [comment]
thank you for your quick response  it's working for me but show me error:

!include: could not find: "EnvVarUpdate.nsh"

and can you send me resources wheres i can read these.

thanks again for help

**Comment by rachitsakhidas** [comment]
You will get that from below link: EnvVarUpdate.nsh

https://nsis.sourceforge.io/Environmental_Variables:_append,_prepend,_and_remove_entries

Thanks & Regards
Rachit V. Sakhidas

**Comment by Puneetkumarpal** [comment]
thankyou for your support
