### ISSUE TITLE
Code Signing Not Work

### ISSUE THREAD

**Issue by boyphongsakorn** [electron-userland/electron-builder#5121]
`Exit code: 127. Command failed: /home/travis/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/linux/osslsigncode -in /home/travis/build/boyphongsakorn/saox/dist/win-unpacked/saox.exe -out /home/travis/build/boyphongsakorn/saox/dist/win-unpacked/saox-signed-sha1.exe -t http://timestamp.digicert.com -pkcs12 /tmp/t-AQTt1c/0.p12 -h sha1 -n saox -i https://github.com/boyphongsakorn/saox#readme -pass 4bc7a4e2d84747b814e6b13ac28a21b84f89de1ebf07e25fb5f11c9e6c6611ee (sha256 hash) error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
`

> error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

How To Install libcrypto.so on travis-ci or anyway to Code Signing on travis-ci

**Comment by shrinidhi111** [comment]
I am not sure what environment the pipeline is executing on but you would have to install openssl for this to work. Or build it if not available

**Comment by NeuralMayu** [comment]
> I am not sure what environment the pipeline is executing on but you would have to install openssl for this to work. Or build it if not available

should i install openssl in package.json or else?
