### ISSUE TITLE
 can define shortcutName for Mac App?

### ISSUE THREAD

**Issue by ruifeng96150** [electron-userland/electron-builder#5124]
* **Version**: 21.2

* **Electron Version**:8.3.4
* **Electron Type (current, beta, nightly)**:current

* **Target**: nsis,zip

For Mac app. It's possible that to set application_name.app as Chinese or Japanese name but the productName as English name？Or the shortcutName can also be config for  Mac platform to get this points.
Because when I set application_name as English, it different for Chinese to read. Or I set the productName to Chinese. it different to monitor processes pids for statement reason.

Besides, I read the source, and try to config productFilename as application_name but not support.
Thanks All.

**Comment by CN-Tower** [comment]
any solution?
