### ISSUE TITLE
Is it possible to install as admin & not ask for admin privileges when running?

### ISSUE THREAD

**Issue by 20matan** [electron-userland/electron-builder#5125]
Hey, I have a question, but couldn't find an answer.
We would like to install the application as admin/root, and then launch the app as admin/root but without prompting the UAC message box anymore.
Is it possible?

**Comment by 20matan** [comment]
Some more details:

We are using 
`!macro customHeader
    RequestExecutionLevel admin
!macroend`
in order to install the application as administrators, and i know about the property "requestedExecutionLevel", but this property prompts the UAC every time the user launches the application. I would like to not have this prompt every time the user launches the application.

**Comment by shrinidhi111** [comment]
Sorry that I am not offering a solution but why exactly do you need UAC? Can that specific part be delegated to a service? So you can just install the service only once using admin privileges and never ask the user again?

This is the solution we implemented in our company so my two cents..
