### ISSUE TITLE
electron-updater quitAndInstall function is quit and restart app but not install new version on MacOS

### ISSUE THREAD

**Issue by vanthieu97** [electron-userland/electron-builder#5127]
Hello everyone, I have a problem with electron-builder and electron-updater.
I created electron app and I tried to use auto update feature for my app.
I detected new version, download successfully and run function quitAndInstall(), but my app just quit and restart after short time with old version, not apply new version.
Please help me, thanks all.
/Users/user-name/Library/Application Support/Caches/app-name/pending/update.zip: exist

electron: 9.1.0
electron-builder: 22.7.0
electron-updater: 4.3.1

My code:
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 680,
    webPreferences: {
      nodeIntegration: true,
    },
    show: false,
  })
  isDev && mainWindow.webContents.openDevTools()
  mainWindow.loadURL(isDev ? 'http://localhost:1234' : `file://${path.join(__dirname, './renderer/index.html')}`)
  mainWindow.on('closed', () => (mainWindow = null))
  mainWindow.once('ready-to-show', () => {
    autoUpdater.checkForUpdatesAndNotify()
    mainWindow.show()
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow()
  }
})

ipcMain.on('app_version', event => {
  event.sender.send('app_version', { version: app.getVersion() })
})

autoUpdater.on('update-available', () => {
  mainWindow.webContents.send('update_available')
})

autoUpdater.on('update-downloaded', (infos) => {
  mainWindow.webContents.send('update_downloaded')
})

autoUpdater.on('error', err => {
})
autoUpdater.on('update-not-available', info => {
})

ipcMain.on('restart_app', () => {
  autoUpdater.quitAndInstall()
})

**Comment by DarrenHou1993** [comment]
some +1

**Comment by minzhang2** [comment]
how to solve
