### ISSUE TITLE
How can I disable downgrading of Electron-app during installation?

### ISSUE THREAD

**Issue by Bhanuka94** [electron-userland/electron-builder#5128]
* **Version**: ^20.19.2

* **Electron Version**: ^2.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: x64 windows

I am developing a basic electron app.

I made two versions of this electron app as follows. Same app. Two different versions.

- **v1.0 - First one**
- **v2.0 - Second one with some bug fixes**

I made a build for both versions of the app.

Suppose I installed **v2.0** on my windows pc. After that, I don't want to install **v1.0** again. But even after installing the **v2.0** app, when I try installing the **v1.0** app, it replaces the **v2.0** app. Here the old build gets installed over the new build. Simply saying, downgrading happens.

How can I prevent the downgrading of this application, so the old one(**v1.0**) prevents replacing the new one(**v2.0**)?

How to prevent an old Build from installing over a newer Build?

**Comment by shrinidhi111** [comment]
From what I have seen, downgrade defaults to false unless you specify explicitly to allow it.

Although you have version numbering, you need to check the timestamp of the versions in the yml file. (For windows it is simply latest.yml)

If v1 has a newer timestamp then it'll "upgrade" to it.
