### ISSUE TITLE
Two package.json structure and Typescript typings

### ISSUE THREAD

**Issue by stijnvn** [electron-userland/electron-builder#513]
How do you set up an application with the two package.json structure and have the TypeScript compiler find the typings of a dependency without duplicating it in the two package.json files?

My project setup:
```
src/ <-- TypeScript source files
app/package.json
app/ <-- compiled *.js from src
package.json
tsconfig.json
```

`app/package.json` specifies a dependency authored in TypeScript and its `package.json` has a typings entry. The typings are not found by the TypeScript compiler because he only looks at te `package.json` file at the root.

Is there a way to make this compatible without duplicating the application dependencies in `package.json`?

**Comment by develar** [comment]
You don't need and should not include typings / TS / babel / etc in the app `app/package.json` 

TS project: https://github.com/develar/onshape-desktop-shell

`app` dir is no more than just TS out dir — https://github.com/develar/onshape-desktop-shell/blob/master/tsconfig.json#L7 `"outDir": "app/out"`

I see that in your case setup is correct — "app/ <-- compiled *.js from src" So, for what you need to add typings into the app package.json?

**Comment by develar** [comment]
Ah, got your problem. **specifies a dependency authored in TypeScript and its package.json has a typings entry.** Hmm...

**Comment by develar** [comment]
Well... to be honest since electron-builder 5 two package.json structure is required only if your project has native dependencies. If you don't have it, you can just correctly configure [files](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-files) to include required app directories (Development dependencies are never copied in any case. You don’t need to ignore it explicitly anymore).

**Comment by develar** [comment]
Another option is to explicitly specify files in the tsconfig — https://github.com/electron-userland/electron-builder/blob/master/tsconfig.json#L60 — `"node_modules/electron-osx-sign-tf/index.d.ts"`. But it is an ugly solution.

So, if you don't have native deps, you can try just use one-package structure (but in the case you should use correct [files](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-files) ).

**Comment by stijnvn** [comment]
Thanks for your suggestions.

**Comment by develar** [comment]
@stijnvn Please report here what solution you decided to use. Or what can be improved.

**Comment by stijnvn** [comment]
I will use the one-package structure. But I think both suggestions could work fine.

**Comment by Systemcluster** [comment]
A simple solution to this is to add the app package itself as a dependency to the main package. 

/app/package.json:

    "dependencies": {
        "dependency-with-typings": "*",
        "other-app-deps...": "*"
    }

/package.json:

    "dependencies": {
        "app-package": "file:app/"
    }

This way, typescripts type checker as well as the automatic type acquisition correctly recognize the app packages.
