### ISSUE TITLE
Windows MSI package build fails with CSC_LINK with base64 encoded signing certificate 

### ISSUE THREAD

**Issue by sduthil** [electron-userland/electron-builder#5130]
* **Version**: 22.7.0
* **Electron Version**: 9.0.0
* **Electron Type (current, beta, nightly)**: stable
* **Target**: Windows MSI
* **Build environment**: windows server 2016

Given I am building a signed windows MSI package
Given my windows build environment already contains about 7KB of environment variables names and values
Given I set the `CSC_LINK` environment variable to the base64-encoded certificate (7186 characters)
When I build my application with `electron-builder --windows`
Then the package is not built
Then I get the following errors repeatedly:
```
light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
 light.exe : error LGHT0217 : Error executing ICE action 'ICE02'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
...
```

Expected: the package is built and there are no such errors.

When storing the signing certificate in its own file, and setting `CSC_LINK` to the certificate filename, thus reducing the size of environment variables, the MSI package is correctly built.

According to this [StackOverflow thread](https://stackoverflow.com/a/9722623), this error only happens if the total environment variables names and values exceeds some threshold (10KB?) when `light.exe` is run, which was my case.

Is the `CSC_LINK` env variable needed when running `light.exe`? If not, could it be unset for this step?

**Comment by vraravam** [comment]
We are experiencing this issue : https://github.com/getferdi/ferdi/runs/3008115451?check_suite_focus=true - is there a workaround or resolution?

**Comment by kytwb** [comment]
Unticking "_Include all certificates in the certification path if possible_" did the trick:

![Screen-Shot-2021-07-07-at-12 27 33-PM](https://user-images.githubusercontent.com/412895/124757197-3de2f480-df25-11eb-9308-389a071f02ef.png)
