### ISSUE TITLE
Publish to Amazon S3 requires multiple attempts on Windows 10

### ISSUE THREAD

**Issue by jijojosephk** [electron-userland/electron-builder#5139]
* **Version**: 22.7.0

* **Electron Version**: 9.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: Nsis

I'm trying to publish my application to Amazon S3 bucket. I'm getting error multipart upload failed. It requires multiple attempts to finally publish. Please refer the log below:

$ electron-builder --publish always
  • electron-builder  version=22.7.0 os=10.0.18363
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=9.0.4 appOutDir=dist\win-unpacked
  • building        target=nsis file=dist\<app_name_setup>.exe archs=x64 oneClick=false perMachine=true
  • publishing      publisher=S3 (bucket: <bucket>)
  • uploading       file=<app_name_setup>.exe provider=S3
  ⨯ MultipartUpload: upload multipart failed
        upload id: hTJyu4VtodK0l8j9o6Q25pC9S5UifW26gD6_kpr97NrXvyVInEmfBRDxC.5cv
rx0KuTmlSFzAVmQj0Yk1m8tPrkaGApcnRF04Qrx4JMy4EaFF1j9foEgwROI1bnzBTVD
caused by: RequestError: send request failed
caused by: Put "https://<bucket>.s3.<region>.amazonaws.com/<app_name_setup>.exe?partNumber=4&uploadId=hTJyu4VtodK0l8j9o6Q25pC9S5UifW26gD6_kpr9
7NrXvyVInEmfBRDxC.5cvrx0KuTmlSFzAVmQj0Yk1m8tPrkaGApcnRF04Qrx4JMy4EaFF1j9foEgwROI
1bnzBTVD": write tcp 10.0.2.15:56879->52.219.66.127:443: wsasend: An existing co
nnection was forcibly closed by the remote host.
github.com/develar/app-builder/pkg/publisher.upload
        /Volumes/data/Documents/app-builder/pkg/publisher/s3.go:169
github.com/develar/app-builder/pkg/publisher.ConfigurePublishToS3Command.func1
        /Volumes/data/Documents/app-builder/pkg/publisher/s3.go:57
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
le/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
le/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
le/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
le/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373
  ⨯ C:\Users\<user_name>\Projects\ElectronJS\<app_name>\node_modules\app-builder-bin
\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  s
tackTrace=

 Error: C:\Users\<user_name>\Projects\ElectronJS\<app_name>\node_modules\app-builder
-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUT
E

     at ChildProcess.<anonymous> (C:\Users\<user_name>\Projects\ElectronJS\<app_name>\node_modules\builder-util\src\util.ts:243:14)

     at Object.onceWrapper (events.js:417:26)

     at ChildProcess.emit (events.js:310:20)

     at maybeClose (internal/child_process.js:1021:16)

     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by kingpalethe** [comment]
Same problem here. Likely the S3 upload is being done in a suboptimal way.

**Comment by kingpalethe** [comment]
If you have a very fast and stable upstream internet connection, it will work every time.

**Comment by jijojosephk** [comment]
Is it resolved? Can someone comment on this?

**Comment by kingpalethe** [comment]
Not resolved. Unless your internet connection is very fast and stable, the S3 upload will fail. The workaround is to only attempt an S3 upload from an extremely stable, high-bandwidth internet connection. I can't find the place in the code, but my guess is that this is happening because this package is not using aws-sdk, and is instead using some hand-rolled s3 upload solution that isn't stable?
