### ISSUE TITLE
Electron-updater did not generate latest.yml.

### ISSUE THREAD

**Issue by Geekhyt** [electron-userland/electron-builder#5140]
* **Version**: "electron-builder": "^22.4.1", "electron": "8.1.1", "vue-electron": "^1.0.6", "electron-updater": "^4.3.1",

* **Electron Version**: "electron": "8.1.1",
* **Electron Type (current, beta, nightly)**: current

* **Target**: In order to achieve automatic updates, I need to generate latest.yml

**Comment by taokanghua** [comment]
hi how to resove it
