### ISSUE TITLE
Remove Stale Bot

### ISSUE THREAD

**Issue by b-zurg** [electron-userland/electron-builder#5142]
## Problem

I see stale bot so many times closing **valid** issues that have simply not been looked into. 

Issues should be managed, not closed after time.  It seems like this project needs more maintainers.  At least a few people involved  in triage would be good.

**Comment by b-zurg** [comment]
LOL

Please keep open

**Comment by NullEnt1ty** [comment]
It's not even working correctly. It asks if the issue is still relevant which gets answered and then closes it nonetheless. Here's an example: https://github.com/electron-userland/electron-builder/issues/5257

What is this madness?

**Comment by NullEnt1ty** [comment]
> Is this still relevant?

Yes.

**Comment by NullEnt1ty** [comment]
@develar Can you please fix or remove stale bot? It's not working correctly.
