### ISSUE TITLE
This app can't run on you pc Windows 10.

### ISSUE THREAD

**Issue by clementvp** [electron-userland/electron-builder#5145]
* **Version**: 22.4.1

* **Electron Version**: 8.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

So with my project and even with the webpack-boilerplate project build process is ok, no error at all, but when i try to run the Exe file provided in the win-unpacked folder, windows 10 give me an error "This app can't run on your pc, thanks to contact the software developper".
And this is for every project using electron/electron-builder of mine (I try with  the webpack-boilerplate example).

I'am missing something ?

I was able to build for windows few month ago but not now.

Very strange this make me perplex and sad :/

**Comment by shrinidhi111** [comment]
I am not aware of the webpack-boilerplate but this error can mean the application is the wrong architecture for your Windows (are you using 32 bit Windows? If not is the application target 32 instead of 64?). 

Although a little more information would be helpful
