### ISSUE TITLE
needed to submit in mac store?? or what?  but Transporter only ipa, pkg files accept???

### ISSUE THREAD

**Issue by lse123** [electron-userland/electron-builder#5155]
what file submit to Transporter app??
yyy-mbp:electron-quick-start yyy$ npm electron --version
6.14.6
yyy-mbp:electron-quick-start yyy$ 

how to upgrade electron version??\
as seen in this shot -- only the file:  // needed to submit in mac store?? or what?  but Transporter only ipa, pkg files accept???
/Users/yyyy/Documents/Electron-Udemy/electron-quick-start/dist/mac/electron-quick-start.app

![2020-07-20_10-54-13 (2)](https://user-images.githubusercontent.com/2356781/87915004-35767d00-ca7a-11ea-88a9-55a1391197a0.png)

* **Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:

**Comment by shrinidhi111** [comment]
I recommend that you go through some tutorials like this https://webspaceteam.com/electron/how-to-publish-an-electron-application-to-mac-app-store

I am sure it will help you.


Also you can install any specific version of node/npm you need by using nvm. Check their github for more info.
