### ISSUE TITLE
Windows install directory

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#516]
So, using squirrel, my package.json is: 

```
{
  "name": "app",
  "productName": "My App",
}

```
I can't put spaces in "name" or otherwise building fails. But I'd like to have /Users/name/AppData/Local/My App/ as the installation directory and not /Users/name/AppData/Local/app 

Is this possible? And another question, can I customize it to use the same installation dir as NSIS? I believe you said it was another directory.

**Comment by develar** [comment]
> Is this possible?

For Squirrel – no. i.e. we can change it in our fork, but I will not do it.

For NSIS we already use product name — https://github.com/electron-userland/electron-builder/blob/v5.4.3/templates/nsis/NsisMultiUser.nsh#L105

> can I customize it to use the same installation dir as NSIS?

Well, yes (no option though), but don't do it. APP DATA for **data**, not for **app** — in the `/Users/name/AppData/Local/My App` app data should be stored and by default (NSIS only) we don't remove it on uninstall (i.e. user data persisted — see https://github.com/electron-userland/electron-builder/issues/465#issuecomment-223614065)

If you mean customize Squirrel — "no. i.e. we can change it in our fork, but I will not do it.".

**Comment by develar** [comment]
> For Squirrel – no. i.e. we can change it in our fork, but I will not do it.

Got your question, will be investigated.

**Comment by kunkinkan** [comment]
`electron.app.getPath("appData"), ` returns path to /Users/me/AppData/Roaming/ does it not?  - What's the difference anyway between roaming and local? And what is the path that NSIS will use ?
