### ISSUE TITLE
Wrong prebuilt binary target for native dependency

### ISSUE THREAD

**Issue by Dardin-dale** [electron-userland/electron-builder#5161]
* **Node**: 13.2.0
* **Version**: 22.7.0
* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current
* **Target**: win/nsis

* **serialport**: 9.0.0

I've been unable to successfully integrate the serialport npm module into my build. Here is my build configuration and script in my package.json:

```
  "scripts": {
    "start": "electron .",
    "build": "npm-run-all --parallel build:main build:renderer",
    "build:main": "webpack --config ./webpack.config.main.js --mode production",
    "build:renderer": "webpack --config ./webpack.config.renderer.js --mode production",
    "pack": "npm run-script build && electron-builder --dir",
    "dist": "npm run-script build && electron-builder"
  },
  "build": {
    "appId": "my_app",
    "files": [
      "build/**/*",
      "node_modules/**/*"
    ]
  }
```
the result of my "dist" script:
```
  • build native dependency from sources  name=@serialport/bindings
                                          version=9.0.0
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.4
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ C:\Users\Me\AppData\Roaming\npm-cache\_prebuilds\90024b-bindings-v9.0.0-electron-v80-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/serialport/node-serialport/releases/download/@serialport/bindings@9.0.0/bindings-v9.0.0-electron-v80-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/serialport/node-serialport/releases/download/@serialport/bindings@9.0.0/bindings-v9.0.0-electron-v80-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.0.5 runtime=electron arch=x64 libc= platform=win32)
```
Now it seems to me that the target would be the v83 build since that corresponds to the chrome version used in electron's 9.0.5 release and there is a v83 release of the serialport prebuilt binary in their releases, there is no v80 release. I do not know how electron-builder knows which release version to target or if this is a configuration issue with the serialport module. Should I be using an earlier version of electron/serialport? I have yet to try and put a re-named binary into that cache location.

**Comment by nick318** [comment]
I had similar issue with old `serialport `dependency, so here is my setup which works:

- Node: 12.18.3
- Electron builder: 22.8.0
- Electron: 9.1.1
- Serialport: 9.0.1
- Nodeabi: 2.18.0

**Comment by Dardin-dale** [comment]
Yeah the node-abi may be helping, I'll give that a try. I had some success using electron-rebuild and switching to the programmatic API (which seems to use the rebuilt version, instead of the git releases?) instead of using the CLI but I also upgraded my electron/serialport version. I'm not sure how electron-builder is deciding where to grab the prebuild from and if its the way the serialport is configured or just a bug with the CLI. I need to read through this repo to see what electron-builder is doing under the hood.

**Comment by Dardin-dale** [comment]
@neophob I think the "not" there is a typo. I know that serialport provides the prebuild for each OS in their releases. Electron-Builder should in theory go download the prebuild for your electron environment. At least for serialport there seems to be some version management that gives different results. In a similar project I've used the programmatic electron-builder API and that seems to use whatever is in your node_modules. I re-compiled the native library using electron-rebuild instead and then the programmatic API _seems_ to use the recompiled version when it builds the project. The CLI tries to download the prebuild from the github releases of the native library for your target machine and won't use the re-compiled version in your node_modules as far as I can tell from the logging. Although I'm not sure where the mismatch in the CLI occurs.

**Comment by andypotato** [comment]
This issue still exists in electron-builder 22.9.1
