### ISSUE TITLE
How to set "strict-verify = false" via configuration

### ISSUE THREAD

**Issue by TimPietrusky** [electron-userland/electron-builder#5163]
* **Version**:  22.7.0
* **Electron Version**: 7.1.3
* **Electron Type (current, beta, nightly)**: current

* **Electron updater**: 4.3.1

* **Target**: Mac

I want to deactivate the `--verify` parameter when signing code for MacOS as this is causing problems for me. There is a parameter for `electron-osx-sign` called `strict-verify`, but I can't figure out how to pass this when using electron-builder.

**Comment by 2xAA** [comment]
This was also asked for here back in 2018.
https://github.com/electron-userland/electron-builder/issues/1480#issuecomment-423188723

**Comment by DominikLevitsky** [comment]
It was asked, but never resolved. We need an option to set this parameter. Currently OSX builds are crashing because of this. @develar Any possible solutions?

**Comment by TimPietrusky** [comment]
This ticket makes it impossible to use https://github.com/jensstigaard/grandiose with electron-builder, as some files in grandiose are sym-links.

**Comment by TimPietrusky** [comment]
We will make sure to get this tested!

**Comment by TimPietrusky** [comment]
This was tested and it is working. Thank you very much.

**Comment by zjy369** [comment]
> This was tested and it is working since electron-builder 22.9.1:
> 
> ```js
> builderOptions: {
>   mac: {
>     strictVerify: false
>   }
> }
> ```
> 
> Thank you very much.

It's a fake
