### ISSUE TITLE
Facing error while building electron for windows 10

### ISSUE THREAD

**Issue by inder-ranadev** [electron-userland/electron-builder#5166]
* **22.7.0**: 

* **Electron Version**:7.2.3
* **Electron Type (current, beta, nightly)**: current 

* **Target**: windows 10

```
Done Adding Additional Store\r 
 Error information: "Error: SignerSign() failed." (-1073700864/0xc000a000)\r 
  
 SignTool Error: An unexpected internal error has occurred.\r 
  
     at C:\\projects\\sttm-desktop\node_modules\\builder-util\\src\\util.ts:129:16 
     at ChildProcess.exithandler (child_process.js:301:5) 
     at ChildProcess.emit (events.js:198:13) 
     at maybeClose (internal/child_process.js:982:16) 
     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) 
 From previous event: 
     at runCallback (timers.js:705:18) 
     at tryOnImmediate (timers.js:676:5) 
     at processImmediate (timers.js:658:5) 
 From previous event: 
     at WinPackager.signApp (C:\\projects\\sttm-desktop\node_modules\\app-builder-lib\\src\\winPackager.ts:374:27) 
',
```

**Comment by alex-dow** [comment]
have the same issue. this appears to be the solution, as I am using comodoca timestamp server

https://stackoverflow.com/questions/62161135/signersign-failed-2146869243-0x80096005

But not sure how I can add this argument

**Comment by DonMcNamara** [comment]
I think I was able to get around this by setting `rfc3161TimeStampServer` [docs](https://www.electron.build/configuration/win#WindowsConfiguration-rfc3161TimeStampServer) in the windows build configuration in package.json, but I'm not sure if I was hitting the same issue as you.

It looks like the debug flag is being used when signtool.exe is called, but I wonder if adding the verbose flag would give us better information.

**Comment by alex-dow** [comment]
I switched the timestamp url to http://timestamp.sectigo.com/?td=sha256 and my builds are working now.

```javascript
{
  win: {
    ...
    rfc3161TimeStampServer: "http://timestamp.sectigo.com/?td=sha256"
  }
}
```

**Comment by alex-dow** [comment]
this only fixed my issue for one build. they are now failing again. I do notice that some things get signed then it failed with the same ambigious error.

I wonder if I'm getting rate limited.... but using --verbose flag told me nothing.

**Comment by taratatach** [comment]
Doesn't https://github.com/electron-userland/electron-builder/pull/5147 fix this issue?
