### ISSUE TITLE
How can I run NSIS installer with admin rights only on manual install and uninstall

### ISSUE THREAD

**Issue by Sai1919** [electron-userland/electron-builder#5169]
** This is more of a query than issue. I hope someone can help me out with this. **

electron-builder: 22.4.0

electron: 8.1.1 (stable)

electron-updater: 4.2.5

* **Target**: Windows 10

I want to run my NSIS installer with admin permission only when the app is being installed manually. I tried including the below macro:
!macro customHeader
    RequestExecutionLevel admin
!macroend

The problem with this is even on auto updates when the new version is being triggered the installer is showing UAC prompt asking to allow to have admin privileges but I only want that when the app is being installed manually. 
I tried using "${ifNot} ${isUpdated} # your code ${endIf}" suggested on the electron-builder documentation page but the build is failing when I use that inside customHeader macro.

!macro customHeader
  ${ifNot} ${isUpdated}
    RequestExecutionLevel admin
  ${endIf}
!macroend

This is the error output if I use above script.

Error output:                                                                                                                                  
Error: command push not valid outside Section or Function                                                                                      
Error in macro _StdU_TestParameter on macroline 1                                                                                              
Error in macro _isUpdated on macroline 1                                                                                                       
Error in macro _If on macroline 11                                                                                                             
Error in macro customHeader on macroline 1

**Comment by Sai1919** [comment]
Checking on this, any help is greatly appreciated. thanks

**Comment by NickDiMucci** [comment]
Running into the same exact issue here. Would love any guidance on how to allow auto-update to not request admin rights, while manual installs do.

**Comment by has-n** [comment]
Necro'ing this because I'm looking for something similar

**Comment by has-n** [comment]
Found this in the documentation (can't believe I missed it on the first pass). Using this to off-ramp the commands that require admin rights:

`${ifNot} ${isUpdated}
  # your code
${endIf}`

**Comment by cs13b023** [comment]
Running into a similar issue. How can we customiseHeader only for manual installs and not for auto-update
