### ISSUE TITLE
Cannot build Squirrel.Windows target if & in the app name

### ISSUE THREAD

**Issue by drFabio** [electron-userland/electron-builder#517]
While building on windows and targeting windows I am receiving the following error:
     
     "Error: 2016-06-16 13:55:42> Unhandled exception: System.Xml.XmlException: An error occurred while parsing EntityName. Line 11, position 25." 

 [full error](http://pastebin.com/LtH04Lug)

When running the dist task on package.json.
I am following the 2 package.json file approach and I am not using any config option so far.
Do I have to do anything else to build on windows?

PS: I am using ^5.4.2

Thanks.

**Comment by develar** [comment]
Please set `DEBUG=electron-windows-installer` (env `DEBUG` to `electron-windows-installer`) and attach log here (I want to see generated nuspec xml).

**Comment by drFabio** [comment]
The output is 

```xml
  electron-windows-installer Created NuSpec file:
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>App</id>
    <version>0.0.1</version>
    <title>App</title>
    <authors>company</authors>
    <owners>company</owners>
    <iconUrl>https://github.com/dr_fabio_br/listenxelectron/blob/master/build/ic
on.ico?raw=true</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>the description/description>
    <copyright>Copyright © 2016 company</copyright>
    <projectUrl>http://www.company.com.br</projectUrl>
  </metadata>
</package> +0ms
````

**Comment by develar** [comment]
Quite strange because XML is correct (I hope you didn't change it).

**Comment by develar** [comment]
Well, I have no idea. Is it possible to send me app and I will try to investigate?

**Comment by drFabio** [comment]
Changed just the company name as i did not want it to appear on google searchs. I just realized what ti might be. The name had an "&" char on it which was breaking the XML.
Thanks!

**Comment by develar** [comment]
@drFabio In the future please keep in mind that I spent my free time ;) — you can send me email directly to avoid sensitive data disclosure or just don't send *modified* output ;) Or just ask to setup real issue tracker (with visibility levels).

Thanks, it will be fixed soon.

**Comment by drFabio** [comment]
Ok Sorry for taking your time. Thanks.

**Comment by develar** [comment]
Moved to backlog. Because Squirrel.Windows will be not default target in the next major release.

**Comment by initPRAGMA** [comment]
Ik this is an old issue, but also having &/! (Not sure which) in the "description" will cause this issue too.

**Comment by develar** [comment]
@initPRAGMA just use nsis target (default target for Windows now).
