### ISSUE TITLE
Running in Github Action causes 404 errors

### ISSUE THREAD

**Issue by justadaniel** [electron-userland/electron-builder#5174]
* **Version**: 22.7.0

* **Electron Version**: 9.1.1
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Windows

Running the build process in a Github Action causes the url to be "https://github.com/repos/justadaniel/WrenderTime/releases" instead of "https://api.github.com/repos/justadaniel/WrenderTime/releases."

I think it might have to do with this line at `gitHubPublisher.ts:253`
`` // host can contains port, but node http doesn't support host as url does
    const baseUrl = parseUrl(`https://${this.info.host || "api.github.com"}`)``

**Log:**
`
Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: GET url: https://github.com/repos/justadaniel/WrenderTime/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sun, 26 Jul 2020 08:43:43 GMT",
  "content-type": "text/plain; charset=utf-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 26 Jul 2021 08:43:43 GMT; secure; HttpOnly; SameSite=Lax"
  ],
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "x-github-request-id": "0402:5D11:DD6927:13F3A7C:5F1D423E"
}
    at createHttpError (D:\a\WrenderTime\WrenderTime\node_modules\builder-util\node_modules\builder-util-runtime\src\httpExecutor.ts:30:10)
    at NodeHttpExecutor.handleResponse (D:\a\WrenderTime\WrenderTime\node_modules\builder-util\node_modules\builder-util-runtime\src\httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (D:\a\WrenderTime\WrenderTime\node_modules\builder-util\node_modules\builder-util-runtime\src\httpExecutor.ts:86:16)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
`

**Comment by srevinsaju** [comment]
Looks like the auth token was incorrect. I do not face this problem.

**Comment by justadaniel** [comment]
> Looks like the auth token was incorrect. I do not face this problem. 

Well, this happens regardless of there being an auth token or not. It's also a public repository. Unless I'm doing something wrong? It says in the docs that I don't have to put an auth token in the repo settings.

**Comment by srevinsaju** [comment]
Is it possible to see your Github Actions `.yml` file. It is required to provide `GH_TOKEN` as the environment variable, for electron builder to publish to github releases

**Comment by justadaniel** [comment]
It's pretty much just stock settings using this action.

[Action Electron Builder](https://github.com/samuelmeuli/action-electron-builder)

**Comment by srevinsaju** [comment]
Ah, I see. Maybe its not a bug with electron-builder. Maybe, the creator of the action might be able to explain. @samuelmeuli.

**Comment by justadaniel** [comment]
Hmmmm, it says on his profile that he works at Apple, so he might be out of action. I'm going to go digging through his TypeScripts to see if there's anything.

**Comment by justadaniel** [comment]
So I figured it out. Long story short, the repository needed a secret for the token as well and at the same time, there were some errors that prevented it from building. What's weird is that it was giving off a 404 error before, and then that all of a sudden was fixed. I don't understand that at all.

**Comment by staltz** [comment]
I also got this error and I figured what's the root cause. I think if you specify `publish.host` as `github.com`, then electron-builder would calculate the API host as `.github.com` (note the prefix `.`). You can spot that in the error logs above.

To fix this, just leave the `publish.host` unspecified/undefined, and it electron-builder will correctly calculate `api.github.com` as the host.
