### ISSUE TITLE
Apple store rejection for use of non-public APIs

### ISSUE THREAD

**Issue by DarrenHooper** [electron-userland/electron-builder#5177]
* **Version**: 22.8.0

* **Electron Version**: 9.1.1
* **Electron Type (current, beta, nightly)**: Current

* **Target**: MacOS - Mas

Apple rejected the built version of our Electron app when it had not been an issue before. The error is copied below

```
Guideline 2.5.1 - Performance - Software Requirements


Your app uses or references the following non-public APIs:

Symbols: _kCGColorSpaceITUR_2020_PQ_EOTF, _getsectbynamefromheader_64, _getsectdatafromheader_64, _getsegmentdata

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.

We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. You should always use public APIs and frameworks and ensure they are up-to-date to prevent this issue in the future.
```
----
package.json copied below in case one of these packages is the offender. 

```
  "dependencies": {
    "app-root-dir": "~1.0.2",
    "electron-is-dev": "^1.0.1",
    "electron-log": "^3.0.5",
    "electron-window-state": "~4.1.1",
    "eol": "^0.9.1",
    "jsesc": "^2.5.2",
    "lodash": "4.17.13",
    "nconf": "~0.8.4"
  },
  "devDependencies": {
    "@jest-runner/electron": "^0.2.2",
    "devtron": "^1.4.0",
    "electron": "^9.1.1",
    "electron-builder": "^22.8.0",
    "jest": "^26.0.1"
  },
```

**Comment by msavin** [comment]
I'm having the same problem with Electron 8.0.2 and Electron-Builder 22.2.0

APIs in question are: _getsectbynamefromheader_64, _getsectdatafromheader_64, _getsegmentdata

**Comment by msavin** [comment]
Are you able to run the application in development mode? I had not been able to run it in anyway... meanwhile.. it runs fine on my old computer. I suspect some of the dependencies have changed.

**Comment by msavin** [comment]
I am noticing it builds fine on macOS 10.15.3 but not 10.15.5. Which macOS version are you using?

**Comment by DarrenHooper** [comment]
I'm currently on macOS 10.14.5.

Runs perfectly fine in a local development mode. I haven't gotten the packaging for development to work yet since we upgraded from an older version of Electron.

**Comment by msavin** [comment]
The x.x.5 update for both 10.14 and 10.15 came out around the same time. I wonder if that has something to do with it. 

For me, it also works fine locally, when I build for distribution, it no longer runs.

**Comment by DarrenHooper** [comment]
Also seemed to work on 10.14.6, so not sure if they fixed it after .5 or Apple just catches it differently sometimes. Well it works on everything but one specific, now old, version so problem solved I guess 👍
