### ISSUE TITLE
Updating via the MSI in Intune context is failing

### ISSUE THREAD

**Issue by thomasdarde** [electron-userland/electron-builder#5180]
* **Version**:  22.7.0

* **Electron Version**:  9.0
* **Electron Type (current, beta, nightly)**:  current

* **Target**: msi

The .msi generated works fine in GPO/user context.
However when deployed via Intune we have the following issue : If the app is running when the update is distributed, the app is "installed", but it fails to boot at  next launch. File icudtl.dat  is said missing

**Comment by andrew-oreshko** [comment]
Having issues with .msi installation via Intune as well

**Comment by thomasdarde** [comment]
I did use https://github.com/felixrieseberg/electron-wix-msi to create an intune compatible package
