### ISSUE TITLE
[monorepo] Error: electron-builder install-app-deps (Invalid regular expression).

### ISSUE THREAD

**Issue by xgustavoh** [electron-userland/electron-builder#5181]
* **Version**: 22.8.0

* **Electron Version**: 9.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 10
* **Used**: Monorepo + Vue + Electron (vue add electron-builder)

When the command is executed: `electron-builder install-app-deps`

Returns the error:
```
Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.0.0") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
```

When looking at the command `computeElectronVersion`, I noticed an error in the regular expression.
https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/electron/electronVersion.ts#L98

The correct is
```javascript
  if (version == null || !/\^\d/.test(version)) {
```

**Comment by wlcharlie** [comment]
I met the same issue and this help
