### ISSUE TITLE
nsis-web publish config not working.

### ISSUE THREAD

**Issue by PaoJiao** [electron-userland/electron-builder#5183]
* **Version**: 22.7.0

* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis-web

hello, im using `$schema` with https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json in my config;

it seems that `publish` could be placed in `nsisWeb`.
but actually it does not work with the following config: 

```js
{
  // ...
  "nsisWeb": {
    "publish": {
      "provider": "generic",
      "url": "http://example.com/dist/nsis-web",
      "channel": "latest"
    }
  },
  "publish": {
    "provider": "generic",
    "url": "http://example.com/dist",
    "channel": "latest"
  }
  // ...
}
```

the web installer always try to download `xxx.nsis.7z` from `http://example.com/dist`.

how to make it download from `http://example.com/dist/nsis-web`?

**Comment by ffdfgdfg** [comment]
Same question, I also found set publish option in `nsisWeb` and `nsis` without **top-level configuration**, it will set to github provider, that's seems different from documents.
_Can be specified in the top-level configuration or any platform- (mac, linux, win) or target- (e.g. nsis) specific configuration._
