### ISSUE TITLE
How to customize the installation path of DEB package?

### ISSUE THREAD

**Issue by kangerts** [electron-userland/electron-builder#5184]
* **Version**: 22.8.0

* **Electron Version**: 9.1.1
* **Electron Type (current, beta, nightly)**:

* **Target**: Linux(deb)

How to customize the installation path of DEB package? Now the default location for DEB installation is /opt/xxx, but I want to customize it to /opt/apps/xxx

**Comment by Dasherss** [comment]
如何配置打包deb的安装包？

**Comment by ZONEZH** [comment]
I also want to customize the installation path of deb. Has the blogger finally solved it?
