### ISSUE TITLE
specified icon not being used when generating osx build

### ISSUE THREAD

**Issue by symbyte** [electron-userland/electron-builder#519]
specifying a build to use a specific icon when building like this: 

```javascript
  "build": {
    "osx": {
      "icon": "./images/myIcon.icns"
    }
  },
```

the icon is only being used in the .dmg installation title bar and for the mounted dmg on the desktop, but the default electron icon is being used everywhere else (app tray icon, etc.). Is there anything that I need to do besides what I have shown here to get this behavior?

**Comment by develar** [comment]
Do you see warn about icon in the build log? Do you have icon in the `build/icon.icns`?

**Comment by symbyte** [comment]
I do not see the warning. I do not have the icon at `build/icon.icns` because I assumed that specifying the icon field in the build property in `package.json` overrides that. Does it still need to be there?

**Comment by develar** [comment]
> I do not see the warning.
@symbyte Do you use electron-builder 5.4.x? 

> I do not have the icon at build/icon.icns because I assumed that specifying the icon field in the build property in package.json overrides that. Does it still need to be there?

https://github.com/electron-userland/electron-builder/wiki/Options#OsXBuildOptions-icon **The path to DMG icon** Yeach, it is not user-friendly, will be fixed somehow soon.

**Comment by symbyte** [comment]
D'oh. Okay, placing icon.icns in the right place causes the expected behavior. Thanks for your clarification!

**Comment by develar** [comment]
Enough. We got enough feedback.

* deprecate `osx`
* introduce `dmg`. use `osx` if present and warn that it is deprecated. all appdmg options goes here.
* introduce `mac` — all mac platform options goes here. To not break existing behaviour, use `osx` as base and warn that it is deprecated.
* allow to override app icon using `mac.icon`.
