### ISSUE TITLE
Building snaps + publishing them on CI: Error: --target-arch cannot be used with build provider 'managed-host'

### ISSUE THREAD

**Issue by KhushrajRathod** [electron-userland/electron-builder#5195]
* **Version**: 22.8.0
* **Target**: snap

I'm building snaps on CI, so I can't use multipass. I'm setting SNAPCRAFT_BUILD_ENVIRONMENT to managed-host, but this results in `Error: --target-arch cannot be used with build provider 'managed-host'`
How can I build snaps & publish them to the Snap Store on CI?
Thanks

**Comment by KhushrajRathod** [comment]
Update: I can successfully build with SNAPCRAFT_BUILD_ENVIRONMENT = host, but I think managed-host is the option that is supposed to be used on CI.

**Comment by cjp256** [comment]
SNAPCRAFT_BUILD_ENVIRONMENT=managed-host is a snapcraft-internal mode. SNAPCRAFT_BUILD_ENVIRONMENT=host is appropriate for CI.

Typically this is done by invoking snapcraft with `--destructive-mode`.

Although misleading, electron-builder's use of `--target-arch` is incorrect and should be removed (I plan to PR something soon).

**Comment by KhushrajRathod** [comment]
> SNAPCRAFT_BUILD_ENVIRONMENT=managed-host is a snapcraft-internal mode. SNAPCRAFT_BUILD_ENVIRONMENT=host is appropriate for CI.
> 
> Typically this is done by invoking snapcraft with `--destructive-mode`.
> 
> Although misleading, electron-builder's use of `--target-arch` is incorrect and should be removed (I plan to PR something soon).

Alright, thanks for clearing that 👍
