### ISSUE TITLE
The ${arch} macro in artifactName is not (fully) respected and not usable

### ISSUE THREAD

**Issue by nomagick** [electron-userland/electron-builder#5196]
It is unexpected and hard to understand why ${arch} in `artifactName` is dropped in most circumstances.

Whenever `artifactName` is defined, the naming of artifacts is supposed to follow the pattern.

The naming of artifacts should be very simple if `artifactName` is explicitly defined: JUST DO WHAT THE USER SAID.

All stuff like no arch under macos platform should not take effect when user EXPLICITLY DEFINED `artifactName`.

**Comment by xiaoxiangmoe** [comment]
1

**Comment by xiaoxiangmoe** [comment]
1

**Comment by xiaoxiangmoe** [comment]
@state no! Please

**Comment by xiaoxiangmoe** [comment]
no
