### ISSUE TITLE
A JavaScript error occured in the main process during update

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron-userland/electron-builder#5198]
* **Version**: 22.7.0
* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current
* **Electron-updater**: 4.1.2
* **Target**: Nsis

Our clients can't update to a new release of my application. This issue occur not for all users, only for some of them.
Versions of electron from which issue occurs were 6.1.7(electron builder version was 22.2.0) or 7.1.11 (electron builder version was 22.3.2). Version of electron in updated application is 9.0.5. 

**They observe a popup with such error:**
A JavaScript error occured in the main process

Uncaught Exception:
Error: Cannot find module './common'
Require stack:

C:\Users\<userId>\AppData\Local\Programs\<appName>\resources\app.asar\It starts from file in main process, then goes to
C:\Users\<userId>\AppData\Local\Programs\<appName>\resources\app.asar\nodemodules...\index.js
C:\Users\<userId>\AppData\Local\Programs\<appName>\resources\app.asar\nodemodules...\node.js
And next is
![JsError](https://user-images.githubusercontent.com/21108344/89166771-341d7800-d583-11ea-96ff-97a771555c7b.PNG)

**Comment by kzimny** [comment]
Does those few users work on clients with very slow connection? I observed similar error on client with very slow wireless connection. Because this issue occure not for all users, can you try to update using LAN network? When exactly does the error occure? On my slow connection client the error occured around 30 second after application started.

**Comment by Sergey-Churilin** [comment]
Hi @kzimny, it looks like everything is fine with internet speed and connection
