### ISSUE TITLE
macOS pkg installer

### ISSUE THREAD

**Issue by sunnyrjuneja** [electron-userland/electron-builder#52]
I'm writing a GUI application that requires root permissions to modify `/etc/hosts`. Based on the following issue, I found myself here:
https://github.com/maxogden/electron-packager/issues/87

Is it possible use this installer to ask for administrative permissions? I personally only need to suport OS X.

I believe that this would be a great feature. I've seen it asked for in the following places (without a satisfactory solution):
https://discuss.atom.io/t/performing-actions-that-require-superuser-privileges/16892
https://discuss.atom.io/t/start-application-with-root/18815

**Comment by stefanjudis** [comment]
Honestly I've got no idea about that.

But as we simply using https://github.com/LinusU/node-appdmg here - you might want to ask there? :bowtie:

**Comment by whatasunnyday** [comment]
Cool, would you like me to close the issue @stefanjudis ?

**Comment by stefanjudis** [comment]
Let's keep it and link it to the issue over there then. :)

**Comment by stefanjudis** [comment]
@whatasunnyday 

As far as I see ( LinusU/node-appdmg#73 ) - achieving this is not possible here at all.

We maybe will offer to create real installer someday though. :bowtie:

**Comment by stefanjudis** [comment]
@whatasunnyday I think we can close this one here. 
Feel free to reopen if needen.

Creating real installers feels a bit like overhead for me now. :bowtie:

**Comment by creeperyang** [comment]
`real installer` is a useful feature.

I'm writing a hosts switcher and also need to write to `/etc/hosts`. Currently I use `electron-sudo` as an alternative.

**Comment by develar** [comment]
I don't like `pkg` and don't recommend it. Do any init logic on first start. Even, even docker app for Mac is a just DMG. It is better for users. I don't say that we will never support it, but for now I don't see any reason to implement it.

**Comment by develar** [comment]
Reopened — https://github.com/electron-userland/electron-builder/issues/874#issuecomment-258478915

`pkg` will be first-class target.

**Comment by develar** [comment]
Initial implementation will be pushed soon. Do not think that https://github.com/electron-userland/electron-builder/issues/52#issuecomment-233113059 is not actual or changed.
