### ISSUE TITLE
DMG contents position not working

### ISSUE THREAD

**Issue by danikoala** [electron-userland/electron-builder#5202]
* **Version**: 22.8.0

* **Electron Version**: 9.1.2
* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.3.4

* **Target**: mac/dmg

The icon contents position is not taken into account. My icon always appears at the top/left position.
```
"dmg": {
    "background": "icons/mac/dmg_bg.png",
    "contents": [
      {
        "x": 460,
        "y": 240,
        "type": "link",
        "path": "/Applications"
      },
      {
        "x": 180,
        "y": 240,
        "type": "file",
        "name": "Gelpiu Desktop"
      }
    ]
  },
```

<img width="658" alt="Screenshot 2020-08-04 at 12 28 45" src="https://user-images.githubusercontent.com/25309448/89284545-3b11bc80-d64f-11ea-9bff-90a65784367f.png">

**Comment by gelpiu-developers** [comment]
Hi!

For me it's relevant because it does not work as intended. I don't know why this is not taking into account the coordinates I'm giving. I've tried also with electron 10.1.3... Same behaviour.

**Comment by gelpiu-developers** [comment]
Hi!

I think this still must be relevant. I've been able to fix it changing from "type: file" to "type: dir".
Thanks!
