### ISSUE TITLE
Code signing is extremely slow

### ISSUE THREAD

**Issue by yanguoyu** [electron-userland/electron-builder#5208]
* **Version**: 21.2.0

* **Electron Version**:8.2.5
* **Electron Type (current, beta, nightly)**:current

* **Target**: mac and window

code sign cost about 6~8 minutes every time.
i set DEBUG=electron-builder,electron-osx-sign*
i find most time is on code sign Frameworks
this is log

[log.log](https://github.com/electron-userland/electron-builder/files/5040091/log.log)

![image](https://user-images.githubusercontent.com/12881040/89623863-f3e23080-d8c7-11ea-822a-6bdee5fe5c57.png)

**Comment by kzimny** [comment]
The performance depends on files included in your package. Maybe you can exclude files which are not needed as follow: https://www.electron.build/configuration/contents.html#files
```
"build": {
        "appId": "org.idkd.viewer",
        "productName": "Viewer",
        "afterSign": "crv/config/afterSignHook.js",
        "directories": {
            "output": "build"
        },
        "files": [
            "!apps${/*}",
            "!build${/*}",
            "!out${/*}",
            "!out-tsc${/*}",
            "!README.md",
            "!Stork.SPA.njsproj",
            "!Stork.SPA.njsproj.user",
            "!tsconfig.json",
            "!tslint.json",
            "!yarn-error.log",
            "!yarn.lock"
        ],
    },
```

**Comment by yanguoyu** [comment]
@kzimny most time is on code sign Frameworks, but not that files.

**Comment by kzimny** [comment]
what is the time difference when you compile with and without code signing?

**Comment by yanguoyu** [comment]
5~8 minutes

**Comment by Slapbox** [comment]
Duplicate of https://github.com/electron-userland/electron-builder/issues/4283

In previous versions these files were not signed.

**Comment by yanguoyu** [comment]
i has fixed this problem。i find many useless keychain in ~/Library/Preferences/com.apple.security.plist。i delete most of them, now code signing only need 10 second。

**Comment by Slapbox** [comment]
@yanguoyu, what about on Windows?

**Comment by yanguoyu** [comment]
@Slapbox windows has code signing?

**Comment by yanguoyu** [comment]
@Slapbox we code signing after pack on windows.

**Comment by Slapbox** [comment]
@yanguoyu ah, is that something that's built into Electron-Builder as an option, or is that something you're managing with another tool? That sounds very interesting. Right now my strategy is to disable code-signing while developing, but that makes for a pain when it comes time to actually make production releases.

**Comment by yanguoyu** [comment]
we windows code-signing by [qianxi](https://www.globalsign.cn/)
