### ISSUE TITLE
Unhandled rejection Error: spawn gm ENOENT

### ISSUE THREAD

**Issue by nuruddeensalihu** [electron-userland/electron-builder#521]
Hi,

I followed a very good tutorial on this wonderful tool http://electron.rocks/electron-builder-explained/ and did managed to build my electron. However, when i run my 

`npm run dist`

where dist is

`    "dist": "build -owl --x64 && build -wl --ia32",

I am getting the error below. 

![image](https://cloud.githubusercontent.com/assets/12234030/16145618/2529b7e0-34ac-11e6-9c89-6b281a8a07ba.png)

`

Despite the error , when i opened my dist folder, my apps where packed and working. It repeats the error while building for both win , darwin and linux . I am asking because there is not lead on the error message and i snot sure what causes it. Please where is the error message coming from ?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x Install required packages.

**Comment by develar** [comment]
` "dist": "build -owl --x64 && build -wl --ia32",

Just `build -owl --ia32 --x64` :)

**Comment by nuruddeensalihu** [comment]
@develar thank you for the prompt reply sir. Now the error happens ones instead of trice . It happened one time now immediately after creating osx version.

![image](https://cloud.githubusercontent.com/assets/12234030/16147512/13124b9e-34b6-11e6-8521-43d85f1bdf7c.png)


If i may ask sir what does the owl stands for please ?

**Comment by develar** [comment]
@nuruddeensalihu Did you install `brew install gnu-tar libicns graphicsmagick` as stated in the docs?

> what does the owl stands for please ?

`--osx --win --linux` == `-o -w -l` == `-owl`.

**Comment by nuruddeensalihu** [comment]
@develar thank you sir. The error is gone now. Please if i may asked once more , I noticed the files i intend to ignore are not ignoring . Below is my Developement package.json
```

 "appId": "myAppID",
      "app-category-type": "public.app-category.trading",
      "productName": "My trading app",
      "files": ["**\/*", "!ignoreMe${node_modules/*}"],
      "osx": {
        "title": "My App",
        "background": "build/background.png",
        "icon": "build/icon.icns",
        "icon-size": 128,
        "target": "dmg",
        "identity": "codesign",
        "contents": [
          {
            "x": 355,
            "y": 125,
            "type": "link",
            "path": "/Applications"
          },
          {
            "x": 155,
            "y": 125,
            "type": "file"
          }
        ]
      },
      "win": {
          "iconUrl": "My link",
          "target" : "zip",
          "loadingGif": "",
          "msi" : true
      },
      "linux": {
        "description": "Sharp Prices. Smart Trading",
        "target": "zip"
      }
```

and in my app package.json

```
{
  "name": "myApp",
  "productName": "My trading app",
  "version": "0.0.1",
  "description": "Sharp Prices. Smart Trading",
  "author": "myApp.com <contact@myApp.com>",
  "homepage": "app.myApp.com",
  "moduleType": [],
  "private": true,
  "ignore": ["**/.*","node_modules"],
  "main": "main.js",
  "license": "MIT",
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0"
  }
}

```

When i build, i can see my node_modules inside the app.asar folder.  From my two json files above sir, please if there is any other suggestion or correction would welcomed it sir. Thank you for your time once more.

**Comment by develar** [comment]
@nuruddeensalihu Don't use `ignore` — it is deprecated ugly option from electron-packager. Use https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-files

**Comment by nuruddeensalihu** [comment]
@develar But i used the` "files": ["**\/*", "!ignoreMe${node_modules/*}"],` as you can see from the developement package.json. Shouldn't that be ok ?

**Comment by develar** [comment]
Your glob is not correct — `/` must be used only, `"!ignoreMe${node_modules/*}"` — here you ignore file `ignoreMe`, not node_modules folder.
