### ISSUE TITLE
Configure electron-builder to only sign specified files

### ISSUE THREAD

**Issue by gumispl** [electron-userland/electron-builder#5210]
* **Version**: 21.2.0

* **Electron Version**: 6.1.11
* **Electron Type (current, beta, nightly)**: stable

* **electron-updater version**: 4.3.4

* **Target**: win x64

I'm using EV Code Signing certificate to avoid Windows SmartScreen warnings while launching NSIS.
I just added 'certificateSubjectName' property to my 'builderOptions' section and it auto-magically works.
But my EV Code Signing certificate requires USB smart card and it is asking me many many times to enter PIN for it during signing process.
This is very annoying and frustrating. 

Is there a way to tell Windows to remember PIN? 
Or maybe it is possible to configure electron-builder to only sign final installer exe?

I tried to sign final installer exe manually with signtool.exe instead of relying on electron-builder but then latest.yml have wrong hashes and auto-updater breaks.

**Comment by kzimny** [comment]
You can enable single sign on as follow:
![image](https://user-images.githubusercontent.com/12007674/90266396-34a3f180-de54-11ea-9bab-859310d66d72.png)

**Comment by gumispl** [comment]
Unfortunately I'm not using SafeNet Client. I have certificate from CERTUM which is supplied with client app proCertum Card Manager which doesn't have such option.

**Comment by kzimny** [comment]
why don't you ask the certificate provider?

**Comment by StaZhu** [comment]
> Unfortunately I'm not using SafeNet Client. I have certificate from CERTUM which is supplied with client app proCertum Card Manager which doesn't have such option.

Having same issue like you, I think electron-builder should make win.certificatePassword options suitable for both EV and Non EV Cert. 

codes below seems that as long as /p arg is provided, then we will not need input password manually.
```
// app-builder-lib/src/codeSign/windowsCodeSign.ts
const password = options.cscInfo == null ? null : (options.cscInfo as FileCodeSigningInfo).password
  if (password) {
    args.push(isWin ? "/p" : "-pass", password)
  }
```

**Comment by gumispl** [comment]
> why don't you ask the certificate provider?

I had asked and unfortunately they have no solution.


>Having same issue like you, I think electron-builder should make win.certificatePassword options suitable for both EV and Non EV Cert.
>codes below seems that as long as /p arg is provided, then we will not need input password manually.

Unfortunately I think that this argument serves a different purpose:

> /p <pass.>  Specify a password to use when opening the PFX file. 

I see two work-arounds:
1. electron-builder should allow us to specify which files to sign (eg. I don't want to sign third party libraries)
2. I haven't checked it but it seems that electron-builder is signing every exe independently instead of bulk sign (signtool.exe accepts multiple files at once). This would greatly reduce PIN dialogs (not entirely as final installer must be processed separately)

**Comment by gumispl** [comment]
I'm still looking for a solution.

**Comment by melbarra88** [comment]
> I'm still looking for a solution.

did you find a solution ?

**Comment by gumispl** [comment]
> did you find a solution ?

Unfortunately no.
