### ISSUE TITLE
Cannot build NSIS target with logging calls in installer script

### ISSUE THREAD

**Issue by larrywalters** [electron-userland/electron-builder#5220]
* **Version**: 22.8.0

* **Electron Version**: 9.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS

When building for NSIS with logging calls in the installer script, the build fails.
```
Error output:
Error: LogSet specified, NSIS_CONFIG_LOG not defined.
Error in macro customInit on macroline 2
Error in script "<stdin>" on line 146 -- aborting creation process
  stackTrace=

Error: ~/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
...
Error output:

Error: LogSet specified, NSIS_CONFIG_LOG not defined.
Error in macro customInit on macroline 2
Error in script "<stdin>" on line 146 -- aborting creation process

at ChildProcess.<anonymous> (/Users/.../client-electron/node_modules/builder-util/src/util.ts:243:14)
at Object.onceWrapper (events.js:422:26)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1026:16)
at Socket.<anonymous> (internal/child_process.js:441:11)
at Socket.emit (events.js:315:20)
at Pipe.<anonymous> (net.js:674:12)

```
I believe this is because the `nsis-3.0.4.1` binary does not have the `NSIS_CONFIG_LOG` flag set, and so logging is not enabled. I saw that it is enabled in `nsis-3.0.4.2`, but that electron-builder was reverted to use `nsis-3.0.4.1` back in `22.6.0`. Is there a timeframe for updating NSIS with this useful feature, or deploying an alternate version of NSIS with logging enabled, to get around the issue for which the revert was made in `22.6.0`? Thank you.

**Comment by larrywalters** [comment]
Yes, this is still an issue. Build fails with latest electron-builder 22.9.1 and Electron 9.3.2. Is there any update on when NSIS logging will be supported? Thanks.

**Comment by hgouveia** [comment]
This started to happened to me on Windows 20H2

Versions
node: 12.8.3
electron": 7.3.3
electron-builder : 22.9.1

`installer.nsh`
```
!define ENABLE_LOGGING
!macro customInit
     LogSet on
     ; others stuff
!macroend
```

getting same error message:
```
Error output:

Error: LogSet specified, NSIS_CONFIG_LOG not defined.
Error in macro customInit on macroline 1
```

for now, i fixed just commenting out `; LogSet on`

for some reason this doesn't happen on my GitLab-ci using **electronuserland/builder:wine** docker image
