### ISSUE TITLE
Cannot read property 'show' of undefined on startup after building

### ISSUE THREAD

**Issue by jan-scorl** [electron-userland/electron-builder#5221]
* **Version**:  22.2.0

* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

If I build the app (dmg), it runs flawlessly on my machine (macOS Catalina). However, if I send it to my friend (same version of macOS), he gets the following error when trying to open it: 
![WhatsApp Image 2020-08-13 at 10 00 11](https://user-images.githubusercontent.com/17554280/90113294-6f713100-dd51-11ea-875e-83343eb8c99d.jpeg)

If you want to double-check if you get the same error as well, you can download the latest .dmg from here: 
https://github.com/kollektive-technology/awake/releases/download/v0.0.4/Awake-0.0.4.dmg

**Comment by kzimny** [comment]
Is your app signed and notarized? The gatekeeper blocks everything comes over the wire. Try to save you app into flash drive and run on another mac, that should work.

**Comment by jan-scorl** [comment]
When I originally posted this issue, the app was not notarised yet, so I assumed that this was the root cause of the problem.

However, the app is signed and notarised now and other people still receive this error when starting the app. It works perfectly fine on my own machine.

**Comment by kzimny** [comment]
Hm..., maybe one of the paths you specified in your app is absolute instead of relative? You can try to rename the folder with your source code and start your compiled app again on your local machine.

**Comment by jan-scorl** [comment]
That was the right hint. Thank you Krzysztof.

Although the error pointed towards win being undefined (since .show() was only called on win), the real culprit were the absolute paths for the app and tray icons. What's strange though is that I would have expected this to fail for the other user on my machine too, since this user doesn't have access to my personal folder, which was part of the absolute path I had defined for the icons. It did work for the other user on my machine though.
