### ISSUE TITLE
FEATURE - Electron updater in macOS should check update `LSMinimumSystemVersion` before update

### ISSUE THREAD

**Issue by oriSomething** [electron-userland/electron-builder#5222]
* **Version**: `electron-updater@4.3.4`

* **Electron Version**: `9.1.0`

* **Target**: `mac`

Idea for a useful feature: Electron updater in macOS should check update `LSMinimumSystemVersion` before update, to make sure user can run application

**Comment by kzimny** [comment]
https://github.com/electron-userland/electron-builder/issues/2472
