### ISSUE TITLE
Set name app and icon app

### ISSUE THREAD

**Issue by ZaunSupremoXV** [electron-userland/electron-builder#5223]
**My configuration in package.json**

{
    "name": "system-info",
    "version": "1.0.0",
    "description": "System Info",
    "main": "src/index.js",
    "scripts": {
        "start": "electron-forge start",
        "package": "electron-forge package",
        "make": "electron-forge make",
        "publish": "electron-forge publish",
        "lint": "echo \"No linting configured\"",
        "build-installer": "electron-builder"
    },
    "build": {
        "appId": "br.com.systeminfo",
        "productName": "System Info",
        "copyright": "teste",
        "win": {
            "target": [
                "nsis"
            ],
            "icon": "./buid/icon.png",
            "requestedExecutionLevel": "requireAdministrator",
            "signAndEditExecutable": false
        },
        "files": [
            "**/*",
            "./build/icon.*"
        ],
        "directories": {
            "buildResources": "build"
        },
        "nsis": {
            "installerIcon": "build/icon.ico",
            "uninstallerIcon": "build/icon.ico",
            "uninstallDisplayName": "System Info",
            "license": "license.txt",
            "oneClick": false,
            "allowToChangeInstallationDirectory": true
        }
    },
    "keywords": [],
    "author": {
        "name": "Erick. Inc",
        "email": "erick@ximenes.com"
    },
    "license": "MIT",
    "config": {
        "forge": {
            "packagerConfig": {},
            "makers": [{
                    "name": "@electron-forge/maker-squirrel",
                    "config": {
                        "name": "System Info"
                    }
                },
                {
                    "name": "@electron-forge/maker-zip",
                    "platforms": [
                        "darwin"
                    ]
                },
                {
                    "name": "@electron-forge/maker-deb",
                    "config": {}
                },
                {
                    "name": "@electron-forge/maker-rpm",
                    "config": {}
                }
            ]
        }
    },
    "dependencies": {
        "active-windows": "^0.1.14",
        "electron-squirrel-startup": "^1.0.0",
        "os-utils": "0.0.14",
        "systeminformation": "^4.26.10"
    },
    "devDependencies": {
        "@electron-forge/cli": "6.0.0-beta.52",
        "@electron-forge/maker-deb": "6.0.0-beta.52",
        "@electron-forge/maker-rpm": "6.0.0-beta.52",
        "@electron-forge/maker-squirrel": "6.0.0-beta.52",
        "@electron-forge/maker-zip": "6.0.0-beta.52",
        "electron": "9.2.0",
        "electron-builder": "^22.8.0",
        "electron-rebuild": "^1.11.0"
    }
}

After generating the executable, it does not have the icon set and the name does not change to System Info.
![Captura de Tela (59)](https://user-images.githubusercontent.com/67069017/90167978-d8b56c00-dd72-11ea-92aa-80837c22a64b.png)
![Captura de Tela (60)](https://user-images.githubusercontent.com/67069017/90167988-de12b680-dd72-11ea-95db-60fc42be0130.png)

**Structure **
![Captura de Tela (61)](https://user-images.githubusercontent.com/67069017/90248036-3ba81100-de0e-11ea-82e7-449978ee4a84.png)

**Comment by kzimny** [comment]
for icons see #5226
