### ISSUE TITLE
Can't use icons

### ISSUE THREAD

**Issue by xRealNeon** [electron-userland/electron-builder#5226]
* **Version**: 22.8.0

* **Electron Version**: 9.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux

Hi I have an Electron app with an icon in the mainWindow and I build it but then the icon can't be loaded.
I have tried everything and search for everything but can't find something that can help.
```
(node:27353) UnhandledPromiseRejectionWarning: Error: Image could not be created from /tmp/.mount_FW-DesKIkK8v/resources/app.asar/build/icon.png
    at createWindow (/tmp/.mount_FW-DesKIkK8v/resources/app.asar/main.js:17:16)
    at /tmp/.mount_FW-DesKIkK8v/resources/app.asar/main.js:88:3
(node:27353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
```
tray = new Tray(path.join(__dirname, "/build/icon.png"));
```

**Comment by kzimny** [comment]
Hi, try with https://www.electron.build/icons.html#linux and add your icon to build config:
```
    "build": {
        "appId": "org.my.app",
        "productName": "MyApp",
        "directories": {
            "output": "build"
        },
        "win": {
            "icon": "crv/assets/icons/icon.ico"
        },
        "mac": {
            "icon": "crv/assets/icons/icon.icns"
        }
    },
```

**Comment by xRealNeon** [comment]
Doesn't work

**Comment by kzimny** [comment]
include crv/assets/icons/icon.ico + crv/assets/icons/icon.icns into bundle. The crv is my project name.

**Comment by xRealNeon** [comment]
I want to use my icon in my main.js to create a tray icon

**Comment by pranavwani** [comment]
Facing same issue with **electron v9.1.0, electron-builder: v22.8.0**

**Comment by pranavwani** [comment]
Hi, @xRealNeon issue can be fixed via https://github.com/electron/electron/issues/24221#issuecomment-651320602

**Comment by xRealNeon** [comment]
Please put it into your documentation
