### ISSUE TITLE
install rpm /user/lib/.build-id conflicts

### ISSUE THREAD

**Issue by jazzwsr** [electron-userland/electron-builder#5227]
Version: 22.7.0
Electron Version: 6.0.6
Electron Type (current, beta, nightly): current
Target: Linux

Process: i has a.rpm and b.rpm, when i install b.rpm in an environment where a.rpm is already installed, got a error, what's the reason?

Install result : ERROR yum: file /user/lib/.build-id/xx from install of a.x86_64 conflicts with file from package b.x86_64？

**Comment by aaronliu0130** [comment]
Can someone reopen this?
