### ISSUE TITLE
Is there any way to publish linux ".zip" artifact to GitHub?

### ISSUE THREAD

**Issue by rafajaques** [electron-userland/electron-builder#523]
I want to release the linux zip file generated by the builder to GitHub releases.
Is there a way to do that?

**Comment by develar** [comment]
It doesn't work or you missed https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts?

**Comment by rafajaques** [comment]
It works, put publishes only .deb files, not .zip.

**Comment by develar** [comment]
Please try 5.5.

**Comment by rafajaques** [comment]
Unfortunately not. Only *.deb and *-ia32.deb.
Should I set a flag?

**Comment by develar** [comment]
Hmm... You didn't specify custom target? `--linux deb zip`?

**Comment by rafajaques** [comment]
No, sorry.
That was not specified in --help.
Only now I noticed that in Options wiki.
I'll try again now.

**Comment by develar** [comment]
BTW, why zip? Why not `tar.xz`?

**Comment by rafajaques** [comment]
That's a good question! It was just an "autopilot" thing.
It worked very well. Thanks!
