### ISSUE TITLE
Files in folder`swiftshader` are not signed

### ISSUE THREAD

**Issue by cholic0304** [electron-userland/electron-builder#5236]
* **Version**: 21.2.0

* **Electron Version**: 5.0.11
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

I am trying to build and sign an electron app on windows, evyrything works fine but two files are not signed.
The folder is `AppInstalledRootPath/swiftshader`, and the files are `libEGL.dll` and `libGLEv2.dll`.

├───locales
├───resources
│   └───app.asar.unpacked
│       ├───node_modules
│       └───resources
└───swiftshader

Here is the code I found in electron-builder. Only `appOutDir` and `app.asar.unpacked` will be signed, `swiftshader` is not included. So is there any way to make these two files to be signed automaticlly?

```
    await BluebirdPromise.map(readdir(packContext.appOutDir), (file: string): any => {
      if (file === exeFileName) {
        return this.signAndEditResources(path.join(packContext.appOutDir, exeFileName), packContext.arch, packContext.outDir, path.basename(exeFileName, ".exe"), this.platformSpecificBuildOptions.requestedExecutionLevel)
      }
      else if (file.endsWith(".exe") || (this.isSignDlls() && file.endsWith(".dll"))) {
        return this.sign(path.join(packContext.appOutDir, file))
      }
      return null
    })

    if (!isAsar) {
      return
    }

    const outResourcesDir = path.join(packContext.appOutDir, "resources", "app.asar.unpacked")
    // noinspection JSUnusedLocalSymbols
    const fileToSign = await walk(outResourcesDir, (file, stat) => stat.isDirectory() || file.endsWith(".exe") || file.endsWith(".dll"))
    await BluebirdPromise.map(fileToSign, file => this.sign(file), {concurrency: 4})
```

**Comment by SuperKirik** [comment]
Hello, 
any update on this ?
