### ISSUE TITLE
codesign - bundle format is ambiguous: on symlink files and binary executables

### ISSUE THREAD

**Issue by gmcdev** [electron-userland/electron-builder#524]
A little bit out-of-my league here. 

electron-builder successfully signs about twenty files before it bombs out. Since the file was a symlink, I found this line in `electron-osx-sign-tf.index.js` and changed it to ` if (stat.isFile() && !stat.isSymbolicLink() ) {`.

But now it's bombing on binary-executable files, like `Electron Framework`, see DEBUG below.

Makes me think there must be some other problem in my setup. Any suggestions?

`  electron-osx-sign Signing... ./ELECTRON/dist/osx/AdApp.app/Contents/Resources/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework +72ms
Error: Command failed: codesign --sign AdAppMaster --force ./ELECTRON/dist/osx/AdApp.app/Contents/Resources/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework`

**Comment by gmcdev** [comment]
Also, I have gotten my versions of everything up-to-date per #388

**Comment by gmcdev** [comment]
This doesn't seem related to binary-executables, because there are many that successfully sign. It really seems to be `electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework` and `electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework` that don't want to sign. However, if I exclude those, then the recursive signing fails...

So I know this has worked for many people, and the problem is not with the Electron framework. I'm back to suspecting that the problem is with my certificate: I'm using a self-signed root certificate, trusted only for my account.

**Comment by develar** [comment]
Please specify electron-builder version.

**Comment by develar** [comment]
Problem that `electron-prebuilt` is included. But must be not.

If you use latest release 5.x, may be you have custom files option (and why did you disable asar). Please post your conf.

If you use old version, please upgrade.

**Comment by gmcdev** [comment]
"Everything is Ok"

`asar: true`, solves the problem. This app is internal to our company - I disabled asar so I could debug the app on anyone's machine. But( embarrassed ), now that I think about it, of course that's not going to work with codesign.

Thank you, develar - your commitment to this project, and your quick response to issues is really, really appreciated. electron-builder FTW!!

**Comment by develar** [comment]
@gmcdev Please ensure that generated `asar` doesn't contain electron-prebuilt — `asar e app.asar foo` (install asar before `npm install -g asar`)

**Comment by gmcdev** [comment]
Hmm, actually, I did what you said to look at my asar file: All of my `devDependencies` are asar-ed. I thought that they were automatically ignored.

**Comment by develar** [comment]
Please try 5.5.
