### ISSUE TITLE
Firewall on first start

### ISSUE THREAD

**Issue by Achder** [electron-userland/electron-builder#5241]
I'm wondering where the windows firewall on startup is coming from? 
If I ignore it, it doesn't seem to have any consequences.
And the publisher name is Github Inc.

How can I avoid this pop up?
Here is a screenshot (in german):

![firewall](https://user-images.githubusercontent.com/11417131/90751284-3a775800-e2d6-11ea-8e2d-5d3cb98a5f8a.png)

I'm using electron 8.1 on Windows 10.
The application is getting signed using an EV certificate. 
This is going to be a commercial product the firewall message is rather annoying since it's the first thing the user sees of the application.

**Comment by sandeep1995** [comment]
May I know the `target` of the electron-builder config?
If you set it to `nsis`, then this prompt will be shown only once. But if you set the target to be `squirrel` then it would be [shown every time you update the app. ](https://stackoverflow.com/questions/57414587/how-to-avoid-adding-a-new-windows-firewall-exemption-every-time-an-application-i)

**Comment by Achder** [comment]
the target is nsis. and the prompt only pops up once, i know. but like i said, its the first thing the user sees. and it says publisher github, not even our company name. is there a way around this? because this looks lile we are somehow tracking userdata.

**Comment by Achder** [comment]
I'm getting complaints about this. How can I disable it?

**Comment by Wensh** [comment]
Any conclusion about this?

**Comment by Achder** [comment]
Hi, sorry for the late reply.
I found out the window pops up because of a UDP service discovery call. 
But what I still cannot fix, is that Github, Inc. shows as publisher.

My build config looks like this:

```
{
  "appId": "com.mycompany.myapp",
  "productName": "myapp",
  "artifactName": "${name}-v${version}-internal.${ext}",
  "directories": {
    "buildResources": "build/resources/",
    "output": "dist/internal"
  },
  "win": {
    "certificateSubjectName": "myCompany GmbH",
    "target": "zip",
    "icon": "icon.ico",
    "publisherName": "myCompany GmbH"
  },
  "files": [
    "**/*", 
    "build/resources/icon.ico",
    "!dist/public/*",
    "!dist/internal/*",
    "!dist/dev/*",
    "!test/*",
    "!doc/*",
    "!.vscode/*"
  ]
}
```

I was hoping publisherName would fix this, but it doesn't.

**Comment by Achder** [comment]
Problem solved:
Had to set "author" in package.json.
