### ISSUE TITLE
Maximum download limit 50mb in public repo

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#5247]
Version: 22.4.1
Electron Version: 8.2.0
Electron Type (current, beta, nightly): current
Target: Windows NSIS
I am having the maximum download size error. It cannot download files over 50mb. On checking other similar issues i found that private repo have this issue but my repo is public.
I have attached the terminal output below.

My github repo link : https://github.com/aman-pandia/Medico

Terminal output :

Found version 1.0.2 (url: medico-Setup-1.0.2.exe)
Downloading update from medico-Setup-1.0.2.exe
updater cache dir: C:\Users\hp\AppData\Local\medico-updater
No cached update info available
Download block maps (old: "https://api.github.com/repos/aman-pandia/Medico/releases/assets/19672069.blockmap", new: https://api.github.com/repos/aman-pandia/Medico/releases/assets/19672069.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\hp\Desktop\New folder (2)\Medico\node_modules\builder-util-runtime\out\httpExecutor.js:240:26)
    at ClientRequest.<anonymous> (C:\Users\hp\Desktop\New folder (2)\Medico\node_modules\builder-util-runtime\out\httpExecutor.js:302:17)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)

**Comment by NGrey5** [comment]
I've been having this same issue for the last month now on both private and public repos. It also looks as if the old and new blockmap files it's trying to download are the same. I've tried reverting to an older version of both electron and electron-builder and that doesn't work.

"electron": "^9.2.0",
"electron-builder": "^22.8.0"

**Comment by MD-AZMAL** [comment]
@NGrey5 do let me know if you solve it
