### ISSUE TITLE
Different Icon for installer / App ? (Windows) 

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#525]
I use a white icon because it looks good in windows, but the installer has then a white-on-grey icon which is nearly invisible. Is it possible to use a different icon inside the installer window? (but not in the dock)? 

Also, the icon in the upper left corner of any windows app, has a white background, is it possible to use a different icon for that too?

**Comment by develar** [comment]
NSIS — cannot reproduce. Or do you mean to use different installer icon?

Please attach screenshots, I am not windows expert.

**Comment by develar** [comment]
As fat I understand, windows uses the same icon for task bar and window bar, but I am not expert, help wanted.

**Comment by kunkinkan** [comment]
Yes, I mean the icon that is shown in the installer, above the progress bar. Since my icon is white, on the light gray background it almost looks invisible. Same for the icon in the window bar, but that I don't know if it's possible to change. Installer matter most.

**Comment by kunkinkan** [comment]
http://stackoverflow.com/questions/7431039/how-to-replace-the-default-logo-in-nsis-installer - this may work but don't know if it works with your splash screen.

**Comment by develar** [comment]
Solution found — we use SpiderBanner plugin instead of splash, it is in 5.5. Installer icon and uninstaller will be customizable, you can expect fix on this week.

**Comment by kunkinkan** [comment]
Cool you're so fast, and this is done for free, its unbelievable. You should put up a donate page or something. Just to be clear, the icon shown INSIDE the installer window (above progress bar) can be different from the icon shown in the start menu bar / dock (however you call it in windows) (from that same installer) ? I'd like my white transparent icon to show in the windows dock, but the black one to show in the installer window itself.

**Comment by develar** [comment]
We use SpiderBanner plugin, `MUI_HEADERIMAGE_BITMAP` is not supported.

```
    /*  Set the icon on our dialog. It retrieves the icon from the installer resources. */
    SendDlgItemMessage(hwndDlg, 1025, STM_SETICON, (WPARAM)(HICON)LoadIcon(GetModuleHandle(NULL), MAKEINTRESOURCE(103)), 0);
```

**Comment by kunkinkan** [comment]
Not supported but you are supporting it anyway it seems? What should the size be of that bmp? (Does it need to be bmp?)

**Comment by develar** [comment]
@kunkinkan Supported only for boring installer, not for one-click. I will wait SpiderBanner plugin change — see http://forums.winamp.com/showthread.php?p=3061117#post3061117 

> What should the size be of that bmp?

See example https://media.githubusercontent.com/media/electron-userland/electron-builder/master/test/fixtures/test-app-one/installerHeader.bmp

Regular icon converted to bmp will not work.

> (Does it need to be bmp?)

Yes.

**Comment by kunkinkan** [comment]
I place headerIcon.ico in the build directory, but it doesn't seem to be used. Default still is. (Yes, one-click installer).

**Comment by develar** [comment]
I suppose that `installerHeader` is also specified? In the 5.9.0 there is a bug that `headerIcon.ico` is not checked if `installerHeader` specified, it is already fixed.

**Comment by kunkinkan** [comment]
No, i only have

```
    "win": {
      "target": "nsis"
    },
```

**Comment by develar** [comment]
@kunkinkan please try 5.10.0

**Comment by kunkinkan** [comment]
Seems to make no difference.

**Comment by develar** [comment]
Renamed to `installerHeaderIcon` and fixed.
