### ISSUE TITLE
Building with Docker fails because of 7z

### ISSUE THREAD

**Issue by KaloyanDimitrov** [electron-userland/electron-builder#5250]
* **Electron-builder Version**: 22.8.0

* **Electron Version**: 9.2.0

* **Target**: Windows

I am trying to build an electron application, triggering the build from Jenkins into a docker container. I have tried several different docker images including **electronuserland/builder:wineand** and **node:latest** keep, but getting this error and I can't find anything about it online. Anyone has an idea what this could be? Thanks.

> • electron-builder  version=22.8.0 os=4.4.0-134-generic
>   • artifacts will be published if draft release exists  reason=CI detected
>   • loaded configuration  file=package.json ("build" field)
>   • packaging       platform=win32 arch=x64 electron=9.2.0 appOutDir=release/win-unpacked
>   • default Electron icon is used  reason=application icon is not set
>   • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
>   • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=8.958s
>   ⨯ cannot execute  cause=exit status 2
>                     out=
>     7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
>     p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,6 CPUs Intel(R) Xeon(R) CPU E5-2695 v3 @ 2.30GHz (306F2),ASM,AES-NI)
>     
>     Scanning the drive for archives:
>     
>                     errorOut=
>     ERROR: No more files
>     .cache
>     
>     
>     
>     System ERROR:
>     Unknown error -2147024872
>     
>                     command=/var/lib/jenkins/workspace/FE_PWA_Pipeline/node_modules/7zip-bin/linux/x64/7za x -bd .cache/electron-builder/winCodeSign/126686379.7z -o.cache/electron-builder/winCodeSign/126686379
>                     workingDir=.cache/electron-builder/winCodeSign
>   • Above command failed, retrying 3 more times

**Comment by meta72** [comment]
I seem to have a related issue: The error message is the same (exit status 2, no more files, unknown error -2147024872), but the command is `...7za x -bd .cache/electron-builder/appimage...`.
I'm also in a Docker container executed by Jenkins, mine is based on centos:centos7 and target is linux AppImage. When I launch the container manually and build the app, everything works. 
electron-builder: 22.8.0
electron: 9.3.2
node: 12.19.0

**Comment by meta72** [comment]
I was able to identify the cause of this problem in my case: Setting a environment variable `HOME=.` to the build folder.
However I have not yet found a way to fix this. 

For some reason I have to set this environment variable in a CentOS 7 container, otherwise `npm ci` throws permission errors: https://stackoverflow.com/questions/42743201/npm-install-fails-in-jenkins-pipeline-in-docker
Debian based containers do not need this custom variable.

I suspect either electron-builder or 7zip don't use this variable in all places, so some cache is generated in the actual home folder but read from the overwritten one, or vice versa.

**Comment by roddc** [comment]
I also have this error using electronuserland/builder:16-wine-chrome when packaging deb in GitLab ci.
