### ISSUE TITLE
Tmp.Node is not a valid Win32 application

### ISSUE THREAD

**Issue by asadmalik3** [electron-userland/electron-builder#5254]
* **Version**:
22.4.1

* **Electron Version**:
9.2.1

* **Target**:
Mac, Windows, Linux

I am trying to build my electron application for all 3 platforms. I am using mac as build server. I am using below given command to build

`electron-builder -mwl`

Below is my build configuration in package json. Also note that i am using sqlite3 package which i use by running electron rebuild command.

 ```
"build": {
    "appId": "appName",
    "directories": {
      "output": "output-path"
    },
    "mac": {
      "category": "your.app.category.type",
      "icon": "/desktop-app-icon-mac-512.icns",
      "target": "dmg"
    },
    "win": {
      "icon": "/desktop-app-icon-win-256.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "target": [
        {
          "target": "AppImage",
          "arch": [
            "x64"
          ]
        }
      ]
    },
    "files": [
      "/views/"
    ],
    "publish": {
      "provider": "generic",
      "url": ""
    },
    "nsis": {
      "deleteAppDataOnUninstall": true
    }
  }
```

Generated DMG file works successfully on mac, but after installing executable on 64 bit machine, below given error is logged in renderer process console

```
Uncaught Error: Uncaught (in promise): Error: \\?\{local-dir-path}\AppData\Local\Temp\10\1435ac1f-8452-42d8-952d-e07381d1b44b.tmp.node is not a valid Win32 application.
\\?\{local-dir-path}\AppData\Local\Temp\10\1435ac1f-8452-42d8-952d-e07381d1b44b.tmp.node
Error: \\?\{local-dir-path}\AppData\Local\Temp\10\1435ac1f-8452-42d8-952d-e07381d1b44b.tmp.node is not a valid Win32 application.
\\?\{local-dir-path}\AppData\Local\Temp\10\1435ac1f-8452-42d8-952d-e07381d1b44b.tmp.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ({local-dir-path}\AppData\Local\Programs\{app-name}\resources\app.asar\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
```

It seems like 32-bit version got installed on 64 bit windows machine. If i create build for windows-only on 64-bit windows machine, then it is working fine. As it is clear in configuration, i am creating installer for both 32 and 64 bit platforms, i can confirm that installer contains both 32 and 64 bit application because my exe file got doubled once i included 32 bit architecture.

Does anybody else had the same issue? Kindly share your experiences.

**Comment by jjason685** [comment]
Also got this. Any fix?

**Comment by asadmalik3** [comment]
@jjason685 Are you building for windows on Mac OS?

**Comment by jjason685** [comment]
@asadmalik3 I was. Sorry for the late response, but I fixed it simply by upgrading sqlite3 to the latest version (^5.0.0 for me). Hope this helps.

**Comment by asadmalik3** [comment]
@jjason685 Thank you for the suggestion. My problem got fixed too by upgrading sqlite3 to latest version (^5.0.0).

**Comment by qld-cf** [comment]
upgrading sqlite3 not work

**Comment by peakcool** [comment]
there is a similar discussion here

https://github.com/electron-userland/electron-builder/issues/844

**Comment by narakuR** [comment]
我遇到了同样的问题，我是这样解决的：
可以把 sqlite3版本改成 v5.1.6
然后到 https://github.com/TryGhost/node-sqlite3/releases/tag/v5.1.6 所有的二进制文件下载到本地
将这些 文件复制到 /node_modules/sqlite3/lib/binding/ 下, 然后重新build一下试试
├── binding
│   ├── napi-v3-darwin-unknown-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v3-darwin-unknown-x64
│   │   └── node_sqlite3.node
│   ├── napi-v3-linux-glibc-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v3-linux-musl-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v3-linux-musl-x64
│   │   └── node_sqlite3.node
│   ├── napi-v3-win32-unknown-ia32
│   │   └── node_sqlite3.node
│   ├── napi-v3-win32-unknown-x64
│   │   └── node_sqlite3.node
│   ├── napi-v6-darwin-unknown-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v6-darwin-unknown-x64
│   │   └── node_sqlite3.node
│   ├── napi-v6-linux-glibc-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v6-linux-glibc-x64
│   │   └── node_sqlite3.node
│   ├── napi-v6-linux-musl-arm64
│   │   └── node_sqlite3.node
│   ├── napi-v6-linux-musl-x64
│   │   └── node_sqlite3.node
│   ├── napi-v6-win32-unknown-ia32
│   │   └── node_sqlite3.node
│   └── napi-v6-win32-unknown-x64
│       └── node_sqlite3.node
├── sqlite3-binding.js
├── sqlite3.d.ts
├── sqlite3.js
└── trace.js
