### ISSUE TITLE
Cannot run updater exe on nsis-web sometimes for certain users

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#5255]
* **Version**: latest

* **Electron Version**: 6.1.4
* **Electron Type (current, beta, nightly)**: current

latest

* **Target**: Windows

Some users do not seem to be able to use the updater correctly. It fails when trying to update their build. I did verify with the user that the exe exists, they ran it manually, and there were no issues. The question is why is NodeJS sometimes randomly failing to run this process?

Is there something wrong with the `_spawn()` function? Something wrong on the user's operating system?

```
2020/08/25 10:14:10:448 Cannot run installer: error code: ENOENT, error message: "spawn C:\Users\user\AppData\Local\badlion-client-updater\pending\Badlion Client Web Setup 2.16.0.exe ENOENT", will be executed again using elevate if EACCES"
2020/08/25 10:14:10:448 Error: Error: spawn C:\Users\user\AppData\Local\badlion-client-updater\pending\Badlion Client Web Setup 2.16.0.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)```

**Comment by jackple** [comment]
I'm facing this problem too.

**Comment by mastergberry** [comment]
Still an issue.

**Comment by mastergberry** [comment]
No way to reproduce, but still relevant.

**Comment by hiapkbb** [comment]
I had the same problem.
use nsis packaged the .exe installer。 but when it updates and installs, it got a error.

![image](https://user-images.githubusercontent.com/38156497/112285061-dcc04980-8cc4-11eb-953f-545d46fd5dae.png)

**Comment by mmaietta** [comment]
@hiapkbb are you able to create an example repo, such as via electron-quick-start, or upload a electron-builder config here?

I'm not too familiar with the Windows install process, but the EACCES is a permissions issue and it sounds like the `elevate` was not properly executed. Just to confirm, did a UAC pop up or some other permission/install request be displayed?
If no, I'm wondering if there's a conflict when `isSilent: true` and electron-builder config has `packElevateHelper: true`, `allowElevation: true`, and `perMachine: false`
