### ISSUE TITLE
add option to choose snapcraft base e.g. new core20

### ISSUE THREAD

**Issue by gocarlos** [electron-userland/electron-builder#5257]
* **Version**: 22.8.0

* **Electron Version**: 9.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux snap

when building a snap app, the based used is the `core18`
The new `core20` base was released earlier this year, it brings e.g. a new `libstdc++` which is needed if you have native modules and compile those to shared libs on the host system.

**Comment by gocarlos** [comment]
Yes

**Comment by picdc** [comment]
Hi,
It there any plan on adding support for this? I see that the bot simply closed the issue for no reason.

**Comment by johannesjo** [comment]
Could we reopen this?

**Comment by ppd** [comment]
An alternative to be able to use core20 for some projects would be electron-packager. See https://github.com/ogra1/mattermost-client/blob/master/snap/snapcraft.yaml for an example.

**Comment by ppd** [comment]
I think this should be re-opened. Core22 is already in the pipeline, so electron-builder must switch to a newer base soon to stay relevant.
