### ISSUE TITLE
linux.executableName does not default to productName

### ISSUE THREAD

**Issue by adam-lynch** [electron-userland/electron-builder#5259]
* **Version**:  22.8.0

* **Electron Version**: 9
* **Electron Type (current, beta, nightly)**: current

* **Target**: Just AppImage or AppImage, Debian, and Snap

The [docs](https://www.electron.build/configuration/linux) say that `executableName` "Defaults to `productName`" but it doesn't. 

I just ran into #3440, i.e. I got the `expected argument for flag '--executable'` error because the `name` property in my `package.json` contained `@`. I had `productName` set but still got this error. Once I set `executableName`, everything worked fine.

**Comment by maneetgoyal** [comment]
Facing same issue while trying to create Linux distributions on Windows via WSL.
