### ISSUE TITLE
[Rejection] Invalid Provisioning Profile

### ISSUE THREAD

**Issue by idoodler** [electron-userland/electron-builder#5263]
* **Version**: 22.8.0

* **Electron Version**: v9.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas/mas-dev

Apple Rejected our macOs application due to an crash on start. I tried to verify the issue and I am able to do so using the `mas-dev`target. 

According to the Console Application the embedded provisioning profile is not valide:
`embedded provisioning profile not valid: file:///{PATH_TO_PROJECT}/dist/mas-dev/APP.app/Contents/embedded.provisionprofile error: Error Domain=CPProfileManager Code=-215 "Only Development Provisioning Profiles can be installed in System Preferences. Production Provisioning Profiles are imported within Xcode." UserInfo={NSLocalizedDescription=Only Development Provisioning Profiles can be installed in System Preferences. Production Provisioning Profiles are imported within Xcode.}`

This provisioning profile has been downloaded from developer.apple.com (macOS AppStore) linked to the `Mac App Distribution` certificate. Both, the profile and the cert are still valide and not expired.

`electron-builder` does not throw any error when building the artifact. Attached is the electron builder config file.
```
{
  "appId": "BUNDLE_ID",
  "buildVersion": "2020.8.28",
  "artifactName": "${productName}.${ext}",
  "afterSign": "./build/hooks/afterSignHook.js",
  "afterAllArtifactBuild": "./build/hooks/afterAllArtifactBuildHook.js",
  "dmg": {
    "title": "${productName}",
    "window": {
      "width": 700,
      "height": 400,
      "x": 200,
      "y": 200
    },
    "contents": [
      {
        "x": 450,
        "y": 190,
        "type": "link",
        "path": "/Applications"
      },
      {
        "x": 230,
        "y": 190,
        "type": "file"
      }
    ]
  },
  "mac": {
    "category": "public.app-category.utilities",
    "hardenedRuntime": true,
    "entitlements": "build/entitlements_mas.plist",
    "entitlementsInherit": "build/entitlements_mas.inherit.plist",
    "provisioningProfile": "build/embedded_mas.provisionprofile",
    "darkModeSupport": true,
    "extraFiles": [
      "build/embedded_mas.provisionprofile"
    ],
    "target": [
      "mas-dev"
    ]
  }
}
```

`electron-builder` doesn't throw any error:
````
  • electron-builder  version=22.8.0 os=19.6.0
  • loaded configuration  file={PATH_TO_PROJECT}/build/electron-build-mac-mas-dev.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=keytar@6.0.1, websocket@1.0.31 platform=darwin arch=x64
  • install prebuilt binary  name=keytar version=6.0.1 platform=darwin arch=x64
  • packaging       platform=mas arch=x64 electron=9.1.0 appOutDir=dist/mas-dev
  • signing         file=dist/mas-dev/APP.app identityName=Developer ID Application: XXXXXXX (YYYYYYY) identityHash=9FF93808FF75CA13E3CFFE469D50C6024D0155A5 provisioningProfile=build/embedded_mas.provisionprofile
  • signing         file=dist/mas-dev/APP.app identityName=Mac Developer: ZZZZZZZ (AAAAAA) identityHash=5EC987CCC48CB8D4B07B973675BDD61F5863F836 provisioningProfile=build/embedded_mas.provisionprofile

````

**Comment by Padge91** [comment]
I just ran into this problem and was able to resolve it by importing a Developer Provisioning Profile. 

I just went to the the Apple Developer Console, generated a new macOS App Development Provisioning Profile for the same app, download the Provision Profile, and double clicked it to install, then rebuilt. My specific app still crashes, but now with an unsatisfied entitlement instead of the error above.

I tried this as after finding this SO question: https://stackoverflow.com/questions/27874660/mac-app-unable-to-import-mac-distribution-profile-in-organization. Looks like it's not specific to Electron, but to Apple's signing process. Appears to assume the provided profile is a Development profile if a Development profile is not already loaded.

Hope this helps!

**Comment by hisnameisjimmy** [comment]
@Padge91 What did you do to solve the unsatisfied entitlement? I'm in the same place, it's complaining about an unsatisfied entitlement but it looks satisfied, so I feel stuck!

This is what I'm getting in console:
`Unsatisfied entitlements: com.apple.developer.team-identifier` and when I try to run the app it comes up with this:

<img width="332" alt="Electron the application can't be opened entitlements" src="https://user-images.githubusercontent.com/740373/167997116-e9c82697-3597-47b9-b59c-522b6a592ab2.png">

**Comment by Padge91** [comment]
@hisnameisjimmy I don't remember exactly, it's been a while, and I'm not really an Apple developer. My first suggestion would be to open your entitlements file (either entitlements.mac.plist or entitlements.mas.plist) and make sure it contains the following:

`<key>com.apple.developer.team-identifier</key><string>EXAMPLE</string>`
The value of **EXAMPLE** should be your team identifier (I think you can find this on developer.apple.com). 

If I remember correctly, I had to manually modify the entitlements file to include a few things. This may have been one of them. Unfortunately that's my only suggestion. Good luck!

**Comment by hisnameisjimmy** [comment]
Hmm, already got that one. Confusing!

**Comment by serdarde** [comment]
Hey @hisnameisjimmy, did you find a solution, do you remember it?
