### ISSUE TITLE
Install dependency during installation like .net framework or node js.

### ISSUE THREAD

**Issue by aespinoza96** [electron-userland/electron-builder#5264]
* **Version**: 21.2.0

* **Electron Version**: 8.0.1
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows

Is there a way to install prerequisites dependencies like .NET Framework, MsBuild, or node js with the electron builder? I have researched but I don't see a way to make this. I want to know if there's a way to do it.

I need to tell the user to install some of those dependencies if they don't exist during the installation of the app.

**Comment by StaZhu** [comment]
.NET Framework is not necessary, as long as you install windows6.1-KB976932.exe, there is no other issue like white screen etc...., you can write install KB976932 process in you customed installer.nsh。

**Comment by aespinoza96** [comment]
I figured it out how to do it, turns out there's the "extraFiles" field in the build object where you can put the files that want to install with nsis, then just create a macro in the .nsh file and install them.
