### ISSUE TITLE
shortcutName in chinese Random code After packing

### ISSUE THREAD

**Issue by bzsj** [electron-userland/electron-builder#5266]
* **Version**: 22.8.0

* **Electron Version**:10.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: NISI

    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "./pic/dyb.ico",
      "uninstallerIcon": "./pic/dyb.ico",
      "installerHeaderIcon": "./pic/dyb.ico",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "artifactName":"${productName}${version}-setup.${ext}",
      "shortcutName": "电影"
    }

shortcutName in chinese Random code After packing,app name on desktop is ��Ӱ�� 

If this isn't bug ，there settings solve the problem??? thanks very much !

**Comment by LaneSh4d0w** [comment]
I think the issue is that electron-builder only supports Unicode. Please try by writing your shortcut name in Pinyin rather than using the Chinese characters.
