### ISSUE TITLE
Manually regenerate blockmap

### ISSUE THREAD

**Issue by KhushrajRathod** [electron-userland/electron-builder#5267]
Hi, I'm using electron-builder to build executables on Travis CI. Since I'm using a self-signed certificate, I'm having trouble signing, so I've decided to do it manually on my PC. However I don't know how I can rebuild the blockmap after signing...
Is this required? If so, how can I generate a blockmap based on my signed executable?
Thanks!

**Comment by gungorbudak** [comment]
Hi,

Does the following code bit help? I adapted from https://gist.github.com/wavifu/7539e5bf84a715f6e728bd14479d477c.

```javascript
var blockmap = JSON.parse(
  execSync(
    `./node_modules/app-builder-bin/mac/app-builder blockmap -i "${zipPath}" -o dist/tmp.zip`
  ).toString()
);
blockmap.blockMapSize = parseInt(
  execSync(
    "ls -l dist/tmp.zip | awk '{print $5}' && rm dist/tmp.zip"
  ).toString()
);
```

**Comment by KhushrajRathod** [comment]
Hi @gungorbudak, thanks for replying!
I'm currently build for Windows locally as a workaround, but I'll try this out when I get some time.

**Comment by KhushrajRathod** [comment]
I use Github actions now :)
