### ISSUE TITLE
npm outdated

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#527]
when I run command `npm outdated`;

output is: 

```
Package           Current  Wanted  Latest  Location
electron-builder    5.4.4   5.4.4   5.4.2  
```

**Comment by develar** [comment]
`latest` is `5.4.2`

`next` is `5.4.4`

It is correct. You use pre-release `next` version. What's wrong?

**Comment by kunkinkan** [comment]
Ah, had no idea I'm using "next" version :-) sorry!

**Comment by develar** [comment]
We use automatic release, so, you can receive updates as soon as possible. But we don't want to break build often and don't want to disturb all users. So, we publish `next` tagged release by default. When we feel that release is ready to be available for all, we mark it as `latest`.
