### ISSUE TITLE
Support WSL2 for windows builds

### ISSUE THREAD

**Issue by jakerobb** [electron-userland/electron-builder#5273]
* **Version**: 22.8.0

* **Electron Version**: 9.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

I'd like to be able to perform a Windows build from the WSL2 environment on a Windows machine. Right now, doing so would require that I install Wine, which is both difficult and silly.

**Comment by jakerobb** [comment]
/reopen

I guess I should check my notifications more often.

This is an enhancement request and should not be closed for staleness.

**Comment by OptimBro** [comment]
No discussions going on here. I also found it silly to install wine WSL2, there should be a way to use windows itself.
