### ISSUE TITLE
cannot decode PKCS 12 data using Go pure implementation, openssl will be used  error=pkcs12: error reading P12 data: asn1: syntax error: data truncated

### ISSUE THREAD

**Issue by sebastianripari** [electron-userland/electron-builder#5275]
electron-builder:

* **Version**: 21.2.0

Hi,
I facing this issue when singing windows app: 
`cannot decode PKCS 12 data using Go pure implementation, openssl will be used  error=pkcs12: error reading P12 data: asn1: syntax error: data truncated`

I am very stuck with this, 

Thank you

**Comment by sebastianripari** [comment]
Fixed,

My issue was that certificate (.pfx) is dirty maybe when i uploaded in my git repository.

**Comment by wuqinglaoxingxing** [comment]
hello Have you solved this problem?

**Comment by sebastianripari** [comment]
> hello Have you solved this problem?

Yes
