### ISSUE TITLE
Cookie cannot be set after electron:build

### ISSUE THREAD

**Issue by Liupeng8** [electron-userland/electron-builder#5278]
* **Version**: 22.8.0

* **Electron Version**:9.2.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: windows10

**To Reproduce**
$ vue create demo
$ cd demo
$ npm i
$ vue add electron-builder
$ choose electron 9.0 version
$ npm i js-cookie -S
$ at the vue page use js-cookie usage
$ npm run electron:build or npm run electron:serve
Or you can check [1](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1005)  or [2](https://github.com/electron/electron/issues/25182)

**Screenshots**
![image](https://user-images.githubusercontent.com/23046680/91935046-5db2f600-ed1f-11ea-883e-976b409035de.png)
![image](https://user-images.githubusercontent.com/23046680/91935055-6277aa00-ed1f-11ea-973e-f72de460ef18.png)

**Comment by Liupeng8** [comment]
@develar need your help

**Comment by felipefrodrigues** [comment]
@Liupeng8 were you able to solve the problem

**Comment by herOwOw** [comment]
@Liupeng8 same problem here , any solution

**Comment by herOwOw** [comment]
it seems that no cookie will be activated since the app:// protocol which by default i think the cookie panel not working on that protocol, without cookie y cant use withCredentials to send cookie with the http methods.

here a little hack how i did it:

take  the app.asar and extract it like this : `npx asar extract app.asar ./`

then in background.js file :
```

//at very top
var p = require('path');
var path = p.dirname(__dirname);
var http = require('http');
var fs = require('fs');

if (process.env.WEBPACK_DEV_SERVER_URL) {
  await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
} else{
//replace this block with my cutie http code ever 🥇  
     var app = http.createServer();
    var requestFile = "";
    app.on('request',(req,res)=>{

        (req.url == '/') ? requestFile = path +'/index.html' : 
        requestFile = path + req.url;

        fs.readFile(requestFile,(err,file)=>{
            if(!err)
                res.end(file);
            else
                throw err;
        })
    });
    //port 0 to avoid app existing port
    app.listen(0,(res)=>{ ;
  
      createProtocol('app');
      win.loadURL(`http://localhost:${app.address().port}`);
      
   })
}

```

**Comment by hungmonster** [comment]
> can you show me " createProtocol('app');" method? I try to make protocal like you to run electron app on locahost like dev env. Thank you!
![image](https://user-images.githubusercontent.com/85856036/148880389-b28943ea-8c8a-4b7d-abe8-800418929872.png)

**Comment by SHEN-EN** [comment]
already settled？

**Comment by SHEN-EN** [comment]
> it seems that no cookie will be activated since the app:// protocol which by default i think the cookie panel not working on that protocol, without cookie y cant use withCredentials to send cookie with the http methods.
> 
> here a little hack how i did it:
> 
> take the app.asar and extract it like this : `npx asar extract app.asar ./`
> 
> then in background.js file :
> 
> ```
> 
> //at very top
> var p = require('path');
> var path = p.dirname(__dirname);
> var http = require('http');
> var fs = require('fs');
> 
> //... 
> 
> //until
> if (process.env.WEBPACK_DEV_SERVER_URL) {
>   await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
> } else{
> //replace this block with my cutie http code ever 🥇  
>      var app = http.createServer();
>     var requestFile = "";
>     app.on('request',(req,res)=>{
> 
>         (req.url == '/') ? requestFile = path +'/index.html' : 
>         requestFile = path + req.url;
> 
>         fs.readFile(requestFile,(err,file)=>{
>             if(!err)
>                 res.end(file);
>             else
>                 throw err;
>         })
>     });
>     //port 0 to avoid app existing port
>     app.listen(0,()=>{ ;
>   
>       createProtocol('app');
>       win.loadURL(`http://localhost:${app.address().port}`);
>       
>    })
> }
> ```
> 
> can't believe it, since 10 hours i was trying to figured it how to make it works, a lot fails :p until done, now i can sleep :)

> it seems that no cookie will be activated since the app:// protocol which by default i think the cookie panel not working on that protocol, without cookie y cant use withCredentials to send cookie with the http methods.
> 
> here a little hack how i did it:
> 
> take the app.asar and extract it like this : `npx asar extract app.asar ./`
> 
> then in background.js file :
> 
> ```
> 
> //at very top
> var p = require('path');
> var path = p.dirname(__dirname);
> var http = require('http');
> var fs = require('fs');
> 
> //... 
> 
> //until
> if (process.env.WEBPACK_DEV_SERVER_URL) {
>   await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
> } else{
> //replace this block with my cutie http code ever 🥇  
>      var app = http.createServer();
>     var requestFile = "";
>     app.on('request',(req,res)=>{
> 
>         (req.url == '/') ? requestFile = path +'/index.html' : 
>         requestFile = path + req.url;
> 
>         fs.readFile(requestFile,(err,file)=>{
>             if(!err)
>                 res.end(file);
>             else
>                 throw err;
>         })
>     });
>     //port 0 to avoid app existing port
>     app.listen(0,()=>{ ;
>   
>       createProtocol('app');
>       win.loadURL(`http://localhost:${app.address().port}`);
>       
>    })
> }
> ```
> 
> can't believe it, since 10 hours i was trying to figured it how to make it works, a lot fails :p until done, now i can sleep :)

can't  find index.html,How to settled?

**Comment by Ishu1998** [comment]
+1 How to solve this problem

**Comment by Ishu1998** [comment]
I solved this by adding this package https://github.com/heap/electron-cookies
