### ISSUE TITLE
NSIS Uninstall Script?

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#528]
Is it possible to have uninstallation instructions? How does that work? I need to delete a directory (roaming/App Name) on uninstallation.

**Comment by develar** [comment]
Fixed, will be deleted: `RMDir /r "$APPDATA\${PRODUCT_NAME}"`

**Comment by kunkinkan** [comment]
And this will be done only on uninstall? Or also on reinstall (of the same version) 

It should of course never happen when installing a newer version. 

I suppose only on uninstall would be best.

**Comment by develar** [comment]
Yes, only on uninstall.

**Comment by artpol** [comment]
I'am testing on Windows 7 x86, nsis uninstaller doesn't remove  "C:\Users\MyName\AppData\Roaming\My App Id" with Local storage and other files. Is it possible to remove it automatically on uninstallation?
Thanks for help!
Electron builder version - 7.17.0

**Comment by develar** [comment]
Yes, app data is not removed. Do you want compile flag (I.e. Produce installer that will delete by default) or runtime option (ask user)

**Comment by artpol** [comment]
"Produce installer that will delete by default" - will be nice for my task. Because when user uninstall application, and install it again later, application can't understand that this is first run (to realise custom logic), because old data in place.

**Comment by develar** [comment]
@artpol What about auto updates?

**Comment by artpol** [comment]
During the auto-update, delete data should not be. We are talking only about the manual removal of the application, If it is possible to distinguish between them.

**Comment by develar** [comment]
@artpol I am not sure that your way is correct, but maybe it is ok and suitable for your application. Filed as https://github.com/electron-userland/electron-builder/issues/885
