### ISSUE TITLE
Auto-Updater - ERR_HTTP2_PROTOCOL_ERROR when an update is available

### ISSUE THREAD

**Issue by Relic** [electron-userland/electron-builder#5282]
* **Electron-Builder Version**: ^22.6.1

* **Electron Version**: ^9.0.0
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: ^4.3.4

* **Target**: win32, nsis

I am using a barebones auto update process as shown in the documentation:

```json
"publish": [
    {
        "provider": "generic",
        "url": "valid URL here, redacted"
    }
]
```

```javascript
mainWindow.webContents.on('did-finish-load', () => {
    if (splashWindow) {
        splashWindow.close();
    }

    autoUpdater.checkForUpdatesAndNotify();
    mainWindow.show();
});
```

The following error is displayed in a pop-up *only when an update is available*:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2545:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

Once the box is clicked away, the download continues as normal and completes successfully, and then the application is updated as expected, once the application is closed.

I attempted to fix the problem using a solution found in Issue #4987, with the following code suggested by the issue author:

```javascript
app.commandLine.appendSwitch('disable-http2');
autoUpdater.requestHeaders = {'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'};
```

After making these changes, I am receiving the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: net::ERR_INCOMPLETE_CHUNKED_ENCODING
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2545:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

These errors are uncatchable by catching the `autoUpdater.checkForUpdatesAndNotify()` promise and appear as pop-ups anyways.

If there is a fix for this without disabling HTTP2 this would be the most useful, since I want the app to support HTTP2.

**Comment by BhuvanRohith** [comment]
Having a similar issue with the temporary fix suggested as well
**Electron-Builder Version: ^22.10.15
Electron Version: ^10.1.5
Electron Type (current, beta, nightly): current
Electron-Updater Version: ^4.3.8
Target: win32, nsis**

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: net::ERR_INCOMPLETE_CHUNKED_ENCODING
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2545:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```
I added the suggested fix 

```
app.commandLine.appendSwitch('disable-http2');
autoUpdater.requestHeaders = {'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'};
```

But still the same issue persists.
I'm trying to test electron-updater, using a repo from github. It starts off detecting that an update is available, and then it starts downloading. But as the download starts picking up speed, this error gets triggered multiple times before the download stops altogether.

It works perfectly fine for linux App.Image build though.
