### ISSUE TITLE
Documentation: protocols does not belong in fileAssociations

### ISSUE THREAD

**Issue by lishid** [electron-userland/electron-builder#5286]
Page at https://www.electron.build/configuration/configuration

Here is what it looks like right now:
![image](https://user-images.githubusercontent.com/609710/92317709-fa042380-efd1-11ea-8048-4e0438510c1d.png)

What it should look like:
![image](https://user-images.githubusercontent.com/609710/92317706-eeb0f800-efd1-11ea-8be0-d4bf0aa37c80.png)

**Comment by aabuhijleh** [comment]
Agreed. I was confused by this too.

**Comment by lishid** [comment]
Yup it's still not fixed. I did not find where the documentation can be modified either.

**Comment by lishid** [comment]
Yup

**Comment by riQQ** [comment]
> Yup it's still not fixed. I did not find where the documentation can be modified either.

Documentation is in the [docs branch](/electron-userland/electron-builder/tree/docs)

**Comment by lishid** [comment]
The specific file is in https://github.com/electron-userland/electron-builder/blame/docs/generated/PlatformSpecificBuildOptions.md#L28 but it's in a "generated" folder so I'm assuming it's generated from some source-of-truth? Can't seem to find any build scripts to generate them.

**Comment by riQQ** [comment]
It's generated from here: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts

**Comment by lishid** [comment]
Yes, but I'm not sure how to fix it.

**Comment by vicke4** [comment]
I think it is already fixed and not deployed yet.

https://github.com/electron-userland/electron-builder/blob/docs/generated/PlatformSpecificBuildOptions.md
