### ISSUE TITLE
403 response downloading https://electronjs.org/headers/v9.3.0-wvvmp/node-v9.3.0-wvvmp.tar.gz

### ISSUE THREAD

**Issue by Mastermindzh** [electron-userland/electron-builder#5287]
* 22.8.0: 

* v9.3.0-wvvmp:
* castlab/wvvmp:

* Linux

Throws a 403 on build:
```
> electron-builder --publish=never -c ./build/electron-builder.yml

  • electron-builder  version=22.8.0 os=5.8.7-arch1-1
  • loaded configuration  file=/home/mastermindzh/tidal-hifi/build/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=abstract-socket@2.1.1 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
> abstract-socket@2.1.1 install /home/mastermindzh/tidal-hifi/node_modules/abstract-socket
> node-gyp rebuild


                    errorOut=gyp WARN install got an error, rolling back install
    gyp ERR! configure error 
    gyp ERR! stack Error: 403 response downloading https://electronjs.org/headers/v9.3.0-wvvmp/node-v9.3.0-wvvmp.tar.gz
```

Full error can be found in the CI pipeline: https://github.com/Mastermindzh/tidal-hifi/pull/18/checks?check_run_id=1077986831

**Comment by LaneSh4d0w** [comment]
It's the website giving an access denied. Issue isn't linked to electron-builder for this, but to the program you are trying to rebuild. (here, abstract-socket).

**Comment by JarekToro** [comment]
@Mastermindzh did you ever make any progress here? I running into the same issue building an Apple Music app for linux.

**Comment by Mastermindzh** [comment]
@JarekToro 

Someone posted a possible fix [here](https://github.com/castlabs/electron-releases/issues/70#issuecomment-731360649).
Haven't tried it out myself yet.
