### ISSUE TITLE
Is it possible to configure electron-updater to stop verifying Checksum?

### ISSUE THREAD

**Issue by aabuhijleh** [electron-userland/electron-builder#5296]
* **Version**: 22.8.0

* **Electron Version**: 9.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac (dmg, zip)

Due to some limitations caused by the tools we use, the zip file deployed to the server has a different checksum than the one expected by `electron-updater` in the `latest-mac.yml` file. An error is thrown as a result `sha512 checksum mismatch, expected xyz, got zyx` and the update process is not working.

Is it possible to pass an option to `electorn-updater` to stop verifying the checksum?

**Comment by alex86w** [comment]
why close?

**Comment by stoefln** [comment]
yes, indeed. I would be interested as well.
