### ISSUE TITLE
"main": "build/main.js" is ignored, "public/electron.js" is enforced instead.

### ISSUE THREAD

**Issue by hvqzao** [electron-userland/electron-builder#5299]
* **Version**:  version=22.8.1 os=10.0.19041

* **Electron Version**: 10.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: win

I would like to be able to configure path where my main is. In fact I do it in package.json as follows:
```
  "main": "build/main.js",
```
My current setup gives the following warning (after which I get an error that the path was not found):
```
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
```
Why can't I arbitrarily define my main? Why electron-builder is not picking it up from the package.json config from "main" as it supposed to? Why can't I override it in electron-builder specific section of package.json?

I believe this should be addressed. If it is not that simple as I expect, perhaps if the path needs to be hardcoded in packager and it is different than "public/electron.js" you can replace it with some code which dynamically at runtime goes through package.json, searches for main and loads it?

The main rationale behind my request is that I'm using typescript to build it first and public in CRA is a static folder which I don't want to mess up. I don't want to put any content there dynamically created. Static files are static. It is not place for code.

**Comment by hvqzao** [comment]
Ok nevermind, I figured that out, I solved it by adding:
  "build": {
    "extends": null,

**Comment by CalebAmes** [comment]
Thank you sooooo much for leaving this up!!! You are literally my hero. I'll buy you a beer anytime :)

**Comment by cnkumbula** [comment]
Thank you...

**Comment by marknestor261** [comment]
Thank you so much.

**Comment by Zel1x7** [comment]
Thank you

**Comment by Lai-shixuan** [comment]
Thank you

**Comment by liuqiuling3** [comment]
thank you so much！！

**Comment by sammlapp** [comment]
this appears to still trip everyone up, could someone explain the "solution"? Would the maintainers consider modifying electron's behavior or at least improving the error message? The error message I get currently points to an old blog post that is probably out of date
```
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
```
