### ISSUE TITLE
Windows Tile Assets

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#530]
Windows 10 : https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-app-assets  (different from app icon)

**Comment by untoldone** [comment]
@kunkinkan You can set these using a `<exename>.VisualElementsManifest.xml` file. You'd include this as in "extraFiles" in your electron-builder config.

An example of this (though you can google VisualElementsManifest.xml for more options):

```
<Application xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <VisualElements
      ShowNameOnSquare150x150Logo='on'
      Square150x150Logo='VisualElements_150.png'
      Square70x70Logo='VisualElements_70.png'
      ForegroundText='light'
      BackgroundColor='#28A7B6'/>
</Application>
```

**Comment by untoldone** [comment]
In case anyone tries to do this and hits weird issues with Mac code-signing -- look at the `afterPack` option. You can use it to delete the extraFiles for mac only so it doesn't blow up during signing
