### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB

### ISSUE THREAD

**Issue by marciocamello** [electron-userland/electron-builder#5305]
* **Version**: 22.8.1

* **Electron Version**: 10.1.2
* **Electron Type**:current

* **Target**: Auto updater

This error persists in some versions
[2020-09-22 18:20:33.484] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB

Public and Private, and some version, I try change versions to electron-builder and electron but don't works, in some versions, this message don't show, but download block don't end

**Comment by nancyMagdiModeso** [comment]
same issue
