### ISSUE TITLE
Electron updater helper tool: How to avoid “An update is ready to install”

### ISSUE THREAD

**Issue by EdvinM** [electron-userland/electron-builder#5307]
**electron-builder**: 22.8.1

**electron**: 10.1.2 current

**electron-updater**: 4.3.5

* **Target**: MacOS

One problem I noticed with my electron built app is that when a new update arrives, it always show this kind of popup:
<img width="663" alt="Screenshot 2020-09-23 at 16 06 17" src="https://user-images.githubusercontent.com/6151780/94023620-b887bc80-fdb6-11ea-89b3-591b036b7a6d.png">
I read a few articles, that If you change the files ownership located in
`/Applications/Appname.app`

from **root:wheel** to **user_root_name:staff** it won't show anymore. And it is true. After running my app again, the annoying popup from above doesn't show anymore for the users. So I click the 'Update' button located in my app, **the app quits but never installs the downloaded update**.

I run again the app, and it is the old version. If then I change the files ownership back to root:wheel, the dialog shows, I write the sudo password and update installs successfully.

What could be the problem? Slack is somehow handling this issue, and their automatic updates work as expected. I want to achieve the same behaviour.

**Comment by aabuhijleh** [comment]
I'm experiencing this issue as well. The ownership change you tried seems to not work. [Apparently downloads will silently fail in that case.](https://github.com/atom/atom/issues/2860)

**Comment by JCMais** [comment]
this is still an issue. Was someone able to fix it?

**Comment by qiqetes** [comment]
Having the same issue on some users (not all).

**Comment by kevinlinv** [comment]
I am seeing this too if the application is owned by root instead of specific users.
Would love to get clarity on why it is happening.

cc @mmaietta can we reopen this issue so we can get the conversation going? 🙂

**Comment by mmaietta** [comment]
Updates on mac are exclusively handled by electron's native updater. electron-builder does nothing more than download the update ZIP and then serves it via a local webserver for electron's `autoUpdater` to handle from there
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/MacUpdater.ts#L14

In my personal project, we support dmg updates separately, but it uses Obj-C code for mounting the dmg and moving the .app over the current executable (and also doesn't check signing or notarization). I've tried that via javascript and it doesn't work. Chromium does something fancy when installing mac updates behind-the-scenes

**Comment by bbrodbeck-memtime** [comment]
In-dependant on whose responsibility it is... Is there a known, working fix for it? I could not find anything here or the electron github or anywhere else...

**Comment by zzarcon** [comment]
Hi folks, some users of my app are facing this now. I'm trying to figure out what is the cause, were you able to come up with a solution for this? 

My suspicion is that these users might be running the app with elevated permission (root), hence calling `quitAndInstall()` will trigger a new prompt. Might be also related with users running the app under a managed macbook (MDM)?

Any further context will be very helpful, thanks!

**Comment by jameshfisher** [comment]
I've seen this happen when running the app from a terminal, like `/Applications/Foo.app/Contents/MacOS/Foo`, as opposed to say running the app from Spotlight. I guess the parent process(es) are a factor in whether these permissions are granted?

**Comment by DominikLevitsky** [comment]
We are having this issue happening for some Mac users. I was not able to pinpoint the exact reason of this. The weird thing is, they used our app before and the issue was not present. Seems like it reappeared only recently. Is there any solution?

**Comment by mmaietta** [comment]
This main issue I see here is that it's highly non-reproducible, and for those that do receive it, zero logs have been provided for investigation. I've never been able to repro this in either the `differentialUpdateTest` or e2e functional testing below.

I wrote full e2e auto-update test suite for monitoring and maintaining the stability of MacUpdater (they were running great until very recently when the apple dev cert expired - currently investigating a workaround)
https://github.com/electron-userland/electron-builder/blob/9c67fd31ce982d11c82aae71263ba1f0055a77cc/test/src/updater/blackboxUpdateTest.ts#L20-L29

**Comment by DominikLevitsky** [comment]
Could you please provide the path where the needed logs are located? I could then ask our users to send me the logs.

**Comment by mmaietta** [comment]
Logging is not enabled by default for a variety of reasons, but it has been left extensible to allow varying logging frameworks/approaches. You can find the simplest setup documented here: https://www.electron.build/auto-update#debugging

**Comment by ethanjyx** [comment]
> I've seen this happen when running the app from a terminal, like `/Applications/Foo.app/Contents/MacOS/Foo`, as opposed to say running the app from Spotlight. I guess the parent process(es) are a factor in whether these permissions are granted?

This seems relevant to what I'm seeing

Checking with Claude, got this "
When running from terminal, Terminal.app is the "responsible process" — filesystem access checks may behave differently (Terminal may have Full Disk Access, affecting Squirrel's writability check)."
