### ISSUE TITLE
`build --target dir` doesn't work

### ISSUE THREAD

**Issue by dfabulich** [electron-userland/electron-builder#531]
https://github.com/electron-userland/electron-builder/blob/master/README.md

The README says to install a `pack` script like this:

```javascript
"scripts": {
  "postinstall": "install-app-deps",
  "pack": "build --target dir",
  "dist": "build"
}
```

> And then you can run `npm run dist` (to package in a distributable format (e.g. dmg, windows installer, deb package)) or `npm run pack`.

But the `build` command doesn't accept a `target` parameter, so if you actually try to `npm run pack`, you just get an error message, `Unknown argument: target`

**Comment by develar** [comment]
I think, we should add `--dir` to build dir target for current platform.
