### ISSUE TITLE
feat: Remove existing uninstaller registry key if exists in NSIS installer

### ISSUE THREAD

**Issue by amiller-gh** [electron-userland/electron-builder#5311]
* **Version**: All
* **Electron Version**: All
* **Electron Type (current, beta, nightly)**: All
* **Target**: Windows NSIS Installer

This is a ticket to track work on https://github.com/electron-userland/electron-builder/issues/4057#issuecomment-694037831

When a well-intentioned, but non-technical Windows user wants to un-install and re-install a program, they often try to DELETE ALL THE FILES. However, this leaves vestigial registry keys lingering. Unfortunately, when they manually delete all the files, this often deletes the uninstaller too, leaving us to manually track down orphan registry keys before the NSIS installer can actually work again...

To avoid manual intervention for broken installed, the NSIS installer should remove these registry keys if they exist on each new install.

Users can currently add this functionality through a custom installer init script as referenced here: https://github.com/electron-userland/electron-builder/issues/4057#issuecomment-574823454

This functionality should be part of the default NSIS installer script. I'll be tackling this task in mid November, if nobody picks it up before then.

**Comment by o2genum** [comment]
I think this is fixed by #4057

However, there has been no electron-builder release with that fix included yet.
