### ISSUE TITLE
Cannot build DMG with Big Sur (Xcode 12): hdiutil: unflatten: verb not recognized

### ISSUE THREAD

**Issue by solshark** [electron-userland/electron-builder#5319]
* **Version**:  22.6.0

* **Electron Version**: v.8.1.1

* **Target**: mac

One of the options for `hdiutil` being deprecated (similar case: https://gitlab.kitware.com/cmake/cmake/-/issues/20889)
So build operation failed with error 

```
 ⨯ Exit code: 1. Command failed: hdiutil unflatten /Users/XXX.dmg
hdiutil: unflatten: verb not recognized
Usage: hdiutil <verb> <options>
<verb> is one of the following:
help
attach
detach
...
```

I'm on Big Sur beta 8 (Xcode 12) at the moment but seems like a not recognized option not coming back.

**Comment by nbashkankov** [comment]
Any news here?

**Comment by JuanIrache** [comment]
What workaround are people using? Reverting to Catalina? Removing the license?

**Comment by k2s** [comment]
@JuanIrache 
1. use my patch
2. or remove license file and then add manually with [dmg-license](https://github.com/argv-minus-one/dmg-license) CLI tool

**Comment by JuanIrache** [comment]
Thanks @k2s Unfortunately I already painfully rolled back to Catalina.

Do you know why your patch does not pass the checks? Thanks
