### ISSUE TITLE
"3rd Party Mac Developer ____" naming conventions are no longer accurate

### ISSUE THREAD

**Issue by alibosworth** [electron-userland/electron-builder#5320]
* **Version**: 22.8.1

* **Electron Version**: 10.1.3
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Mac, Mas

We have a CI build process which builds ZIP and DMG for "Mac" and PKG for "Mas".  It was working consistently until our certificates expired and we are working through updating them and running into trouble because it seems that apple's naming conventions have changed as of "Xcode 11".

Another signing project has some info: https://github.com/electron/electron-osx-sign/issues/227 https://github.com/electron/electron-osx-sign/pull/230

Looks like this issue was raised back in november but auto-closed: https://github.com/electron-userland/electron-builder/issues/4410

I'm not really sure why more people haven't encountered this?

**Comment by michihuber** [comment]
I think this only affects Mac App Store builds, but would be great to have this updated. Just donated for priority. Thank you!

**Comment by michihuber** [comment]
Investigating further, when you request the certificate through the Apple developer console, it is named 3rd Party Mac Developer ..., when you request it through XCode, it is named "Apple Distribution". Electron builder should probably fall back onto the other, but I assume that's why not that many people run into this issue.

**Comment by michihuber** [comment]
This is still an issue. Certificates provisioned through the developer portal instead of XCode are named “Apple Distribution” instead of “3rd party developer”. The check should look for both kinds of labels.
