### ISSUE TITLE
DEPLOY on all OS at once

### ISSUE THREAD

**Issue by HarisHodzicnt** [electron-userland/electron-builder#5321]
I just created Cordova - Electron using boilerplate + tutorials.
Using command **cordova build electron** i created executable .exe ( Windows ) file.

Is it possible and how to create installation file for all OS at once. ( from Windows )

**Comment by Ayzrian** [comment]
Nope. You should use a specific OS per build. Therefore to make a build for MacOS, please use MacOS machine. 
I believe you can use cloud computing services to automate the build process for different OS.
