### ISSUE TITLE
How to obfuscate source?

### ISSUE THREAD

**Issue by pedro-surf** [electron-userland/electron-builder#5325]
* **Version**:  "^22.8.0"

* **Electron Version**:  "9.2.0",

Win, macOS default targets

I've been [trying to use a lib called bytenode](https://github.com/OsamaAbbas/bytenode/issues/73) to hide the source as required. 
However, after building, I couldn't get the app running after the first time (when source is compiled and deleted). How could I keep files after closing the app built?

**Comment by neumartin** [comment]
+1
