### ISSUE TITLE
Pictures assets not found after production build

### ISSUE THREAD

**Issue by rxmoein** [electron-userland/electron-builder#5328]
* **Version**: ^22.8.0

* **Electron Version**: ^9.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

Hello, when I run my electron app in dev mode by `electron main.js`. I see all the pictures and image assets used in my project but after building the app. Pictures are not displayed and the error is `not found`.

I use angular to build the web page and this is the configuration for electron builder in package.json:
```
...
  "build": {
    "directories": {
      "buildResources": "dist/myproject"
    },
    "productName": "myproject",
    "appId": "com.myproject.myproject",
    "files": [
      "dist/myproject/*",
      "package.json",
      "main.js"
    ],
    "mac": {
      "category": "your.app.category.type"
    }
  }
...
```
Is there a working solution for this?

**Comment by sontd-0882** [comment]
Any update?

**Comment by sontd-0882** [comment]
Do you use `file://` protocol to loadUrl into window on the production build?

I think Picture assets are included in the package, but the relative path is incorrect.
