### ISSUE TITLE
NSIS installer has low resolution

### ISSUE THREAD

**Issue by Alatius** [electron-userland/electron-builder#5329]
I noticed that the NSIS installer that I generated with electron-builder (version 22.8.1) shows up with low resolution (i.e. pixelated) on my high DPI-display. It would give a better first impression, I think, if my program's installation program could look as crisp as most other programs these days. :-)

At https://nsis.sourceforge.io/Docs/Chapter4.html#attribgen I found the attribute ManifestDPIAware, which seems promising. Supposing that it solves my issue, I figure I could add it as part of an additional script, with the include option. But, being completely new to NSIS, it is not at all clear to me how such a script would look.

**Comment by mkarp** [comment]
@Alatius Here's what worked for me: put `ManifestDPIAware true` into a file `build/installer.nsh`. More about it here https://www.electron.build/configuration/nsis

**Comment by Alatius** [comment]
> @Alatius Here's what worked for me: put `ManifestDPIAware true` into the file `build/installer.nsh`. More about it here https://www.electron.build/configuration/nsis

Excellent, I am happy it wasn't more complicated. Thank you, it works well.
