### ISSUE TITLE
electron-updater: when targetting nsis-web, the "download-progress" event returns inaccurate results

### ISSUE THREAD

**Issue by wartab** [electron-userland/electron-builder#5341]
* **Version**: 22.8.1

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current
* **electron-updater version **: 4.3.1

* **Target**: nsis-web

This has been reported before, but closed quickly after no reaction was given, and the follow-up description was ignored.
See here: https://github.com/electron-userland/electron-builder/issues/2535

It seems like when targetting nsis-web, the `download-progress` event only gives information about the download of the relatively small installer executable. It does not take into account the more substantial download of the 7z file containing the actual application. 
This results in the download progress hanging at 100% for a long time when the actual application is being downloaded. Our users often assume the download has failed and just proceed to kill the application.

I believe it would be good if the progress did reflect a meaningful indication of progress.

In the meantime, if anyone knows a hack to circumvent this problem, I am willing to hear you out.

**Comment by utajum** [comment]
https://imjselectron.github.io/electron-differential-updater/#/?id=quick-start

**Comment by utajum** [comment]
Still relevant

**Comment by ubjw** [comment]
relevant
