### ISSUE TITLE
Can electron-builder create .pkg for Application Loader?

### ISSUE THREAD

**Issue by wonjun27** [electron-userland/electron-builder#535]
Can electron-builder create .pkg for Application Loader? Application Loader only accepts .pkg files to submit to iTunes Connect. Thanks

**Comment by develar** [comment]
Set `build.osx.target` to `mas`. Or CLI: `--osx mas`.

**Comment by wonjun27** [comment]
Thank you very much for the help @develar 

When I run CLI: --osx mas,

I'm seeing the following error,

Error: Cannot find valid installer certificate: CSC_LINK or CSC_NAME are not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

although CSC_NAME is set in the envrionment, 

printenv | grep CSC_NAME
CSC_NAME=3rd Party Mac Developer Installer: Wonjun Bae (*)

Thanks

**Comment by develar** [comment]
@wonjun27 If it is your development machine, not CI, don't use `CSC_NAME` — I suppose you don't have several identities (not several certs, but identities — different Apple developer accounts), so, you can just nothing specify.

> CSC_NAME=3rd Party Mac Developer Installer: Wonjun Bae (*)
Should be `Wonjun Bae`, because appropriate cert type will be selected automatically (2 different cert types are required to sign, electron-builder will select it automatically).

**Comment by wonjun27** [comment]
@develar After I unset CSC_NAME with
unset CSC_NAME
I'm still getting the same error 
Currently, I have these set on my Mac,

security find-identity -v

  1) 1E1E68E51E8A93896421D5694BE8CC49C987D253 "com.apple.idms.appleid.prd.4f69384c554949435a4a4851616c41525748663672413d3d"
  2) 4AB5866FEFC4480F3B26401455A793623370663C "com.apple.idms.appleid.prd.4f69384c554949435a4a4851616c41525748663672413d3d" (CSSMERR_TP_CERT_REVOKED)
  3) 084A9E8EB7C9BF30F97CBE108F46898E99485E7D "Won Jun Bae"
  4) 22E3B31630851A13937413EF8C1B8FC5C58852C1 "Mac Developer: Wonjun Bae (---)"
  5) 89CCCA0DDC284CD18D92A2C3745325CFCFC1766D "3rd Party Mac Developer Application: Wonjun Bae (---)"
  6) 7F0A051BD8C1FFC152FE93EA892437D23AF55161 "3rd Party Mac Developer Installer: Wonjun Bae (---)"
  7) 8B85FC9CA69F920C6DA38365C2FB9F03D0F05F19 "3rd Party Mac Developer Installer: Wonjun Bae (---)"
     7 valid identities found

Thanks

**Comment by develar** [comment]
@wonjun27 Please attach here result `security find-identity -v -p codesigning -p appleID`

**Comment by wonjun27** [comment]
@develar  Here is the current output from my Mac. Thank you.

 security find-identity -v -p codesigning -p appleID
  1) 084A9E8EB7C9BF30F97CBE108F46898E99485E7D "Won Jun Bae"
  2) 22E3B31630851A13937413EF8C1B8FC5C58852C1 "Mac Developer: Wonjun Bae (---)"
  3) 89CCCA0DDC284CD18D92A2C3745325CFCFC1766D "3rd Party Mac Developer Application: Wonjun Bae (---)"
     3 valid identities found
  1) 1E1E68E51E8A93896421D5694BE8CC49C987D253 "com.apple.idms.appleid.prd.4f69384c554949435a4a4851616c41525748663672413d3d"
  2) 4AB5866FEFC4480F3B26401455A793623370663C "com.apple.idms.appleid.prd.4f69384c554949435a4a4851616c41525748663672413d3d" (CSSMERR_TP_CERT_REVOKED)
     2 valid identities found

**Comment by develar** [comment]
Reproduced, fix will be today.

**Comment by wonjun27** [comment]
@develar That worked great and I was able to submit the build to iTunes via Application Loader successfully. Thank you for the amazing support.

**Comment by kiplphp79** [comment]
hello @develar  

When i try to build pkg with mas it give me error "cannot find valid "3rd Party Mac Developer Application" 

while i have associated certificates in my keychain and they are valid 
Can you please help me 

I am using below version 
"electron": "1.6.11",
 "electron-builder": "19.2.7",
