### ISSUE TITLE
Set useSessionCookies to enable the Electron-Updater to access protected urls

### ISSUE THREAD

**Issue by burnhamup** [electron-userland/electron-builder#5353]
* **Version**: 22.8.1

* **Electron Version**: 9.3.1
* **Electron Type (current, beta, nightly)**:current

* **Electron-Updater Version**: 4.3.5

* **Target**: NSIS

I was experimenting with requiring authentication on my update server which needs certain cookies set. I discovered I could access the session through getNetSession() from electronHttpExecutor.ts, and set the cookies I need on the session. However, the actual request needs to be sent with `useSessionCookies: true` for the cookies to be used.
https://github.com/electron-userland/electron-builder/blob/ede6d50ddb6c23fe6bbb056bd80509c8f2ea0116/packages/electron-updater/src/electronHttpExecutor.ts#L63-L66

I'd argue that it should be on by default, but I'm not sure what side effects it would have since cookies would start to persist between subsequent HTTP calls. Maybe it could work as a provider option like `useMultipleRangeRequest`?

**Comment by schmidtk** [comment]
@develar This issue is still relevant. `electron-updater` is currently unable to download updates from a server that requires cert/cookie authentication. Enabling `useSessionCookies` on the session would fix the issue, but there is currently no way to do that.

**Comment by schmidtk** [comment]
For more background, Electron added the `useSessionCookies` flag in electron/electron/pull/22704 and backported to previous release chains in related PR's. Prior to that change, session cookies were always sent by `electron.net.Request`. I believe setting `useSessionCookies: true` by default would be a good choice, otherwise it would be nice to have an API to set this flag.

**Comment by gregroyal** [comment]
For anyone else running into this. I hacked electron-updater using `package-patch` to pass requests through the renderer that the main process makes

heres the patch

`electron-updater+6.3.9.patch`

```
diff --git a/node_modules/electron-updater/out/electronHttpExecutor.js b/node_modules/electron-updater/out/electronHttpExecutor.js
index 0ae9e11..8d50c36 100644
--- a/node_modules/electron-updater/out/electronHttpExecutor.js
+++ b/node_modules/electron-updater/out/electronHttpExecutor.js
@@ -5,10 +5,20 @@ exports.getNetSession = getNetSession;
 const builder_util_runtime_1 = require("builder-util-runtime");
 exports.NET_SESSION_NAME = "electron-updater";
 function getNetSession() {
-    return require("electron").session.fromPartition(exports.NET_SESSION_NAME, {
-        cache: false,
-    });
+  const { session, webContents } = require("electron");
+
+  // Get the session from the first renderer window
+  const rendererSession = webContents.getAllWebContents()?.[0]?.session;
+  
+  if (rendererSession) {
+      console.log("Using renderer session for updates");
+      return rendererSession;
+  } else {
+      console.warn("Renderer session not found, falling back to default");
+      return session.defaultSession; // Fallback to default session
+  }
 }
+
 class ElectronHttpExecutor extends builder_util_runtime_1.HttpExecutor {
     constructor(proxyLoginCallback) {
         super();
@@ -48,9 +58,9 @@ class ElectronHttpExecutor extends builder_util_runtime_1.HttpExecutor {
             delete options.headers.Host;
         }
         // differential downloader can call this method very often, so, better to cache session
-        if (this.cachedSession == null) {
+        // if (this.cachedSession == null) {
             this.cachedSession = getNetSession();
-        }
+        // }
         const request = require("electron").net.request({
             ...options,
             session: this.cachedSession,
```

this allows the `main` to use the credentials from the `renderer`
