### ISSUE TITLE
Cannot run osslsigncode inside Docker for building Win on Mac

### ISSUE THREAD

**Issue by iwiedenm** [electron-userland/electron-builder#5355]
* **Version**: 22.9.1

* **Electron Version**: 10.1.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

I am having trouble code signing with an EV cert on Mac for Windows. I am building using the Docker image provided here: https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine

`electron-builder.json`
```
...
  "win": {
    "legalTrademarks": "© 2020, My Company",
    "target": [{
        "target": "nsis",
        "arch": [
          "x64"
        ]
      }
    ],
    "certificateSubjectName": "My Full Name",
    "sign": "./src/development/sign.js"
  },
...
```

`sign.js`
```
exports.default = async function(configuration) {
  require("child_process").execSync(
    `osslsigncode sign \
    -h sha256 \
    -pkcs11engine /usr/local/mac-dev/lib/engines-1.1/libpkcs11.dylib \
    -pkcs11module /usr/local/lib/libeTPkcs11.dylib \
    -spc /Users/me/path/to/key.pem \
    -key 'key' \
    -pass 'secret-password' \
    -n Appname \
    -t http://timestamp.sectigo.com \
    -in "${configuration.path}" \
    -out "${configuration.path}"
    `,
    {
      stdio: "inherit"
    }
  );
};
```

I tried the osslsigncode method and I was able to run and successfully codesign for Win on my Mac OUTSIDE of Docker. Since we are using the Docker method to build for Win on Mac, how do we run `osslsigncode` inside Docker? We get this error: 

`bash: osslsigncode: command not found`

Any help would be greatly appreciated!

**Comment by iwiedenm** [comment]
I just tried the osslsigncode method as well and got an error inside the terminal with Docker: `osslsigncode: command not found`. I must be doing something inherently wrong because it seems these libraries are not available in the Docker. What do I do?

**Comment by Ayzrian** [comment]
I assume that Docker mostly uses Linux containers, therefore it is no wonder you can not build something for Windows.

**Comment by iwiedenm** [comment]
@Ayzrian Thanks for your response. But I see so many people that claim to successfully build and sign Windows on a Mac, so how are they doing it?

Namely, this thread: https://github.com/electron-userland/electron-builder/issues/1299

**Comment by iwiedenm** [comment]
Still not sure how people are building Win on a Mac.

**Comment by damianobarbati** [comment]
@iwiedenm are you using the USB dongle with the EV certificate on it? Because the certificate can't be extracted from it as far as I know. How did you manage to sign your app (I'm building win+mac from mac)?

**Comment by Amethystafyy282** [comment]
> @iwiedenm are you using the USB dongle with the EV certificate on it? Because the certificate can't be extracted from it as far as I know. How did you manage to sign your app (I'm building win+mac from mac)?

Did u found a solution for this yet? how is it going?
