### ISSUE TITLE
what situation cause the auto-update's rename tempUpdateFile to updateFile error

### ISSUE THREAD

**Issue by DazzlingBeing** [electron-userland/electron-builder#5359]
* **Version**: ^22.8.0

* **Electron Version**:^9.2.1
* **Electron Type (current, beta, nightly)**:current

* **Electron Updater**:^4.3.4

* **Target**: NSIS

When build nsis target in Windows, and then install it. Then using a update server to publish a newer version, then check the update and the log record:
UNKNOWN: unknown error, rename 'C:\Users\cailo\AppData\Local\app-updater\pending\temp-app Setup 1.0.1.exe' -> 'C:\Users\cailo\AppData\Local\app-updater\pending\app Setup 1.0.1.exe'

I saw the source code, I though the exception hanppend here: line 620 in file https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts
await rename(tempUpdateFile, updateFile)

So what cause the exception happen?

**Comment by WalrusSoup** [comment]
Having this issue as well, specifically with Windows users.

**Comment by Alecyrus** [comment]
Any update?
