### ISSUE TITLE
How to pass --no-sandbox Debian appImage?

### ISSUE THREAD

**Issue by davidhealey** [electron-userland/electron-builder#5371]
In order to run electron on Debian I have to start it with the --no-sandbox option. How can I have this automatically done for my appImage generated by electron-builder? I don't want my users to have to run the app from the command line and enter --no-sandbox everytime.

Thanks.

**Comment by jely2002** [comment]
I'm having the exact same problem, any solutions or workarounds yet?

**Comment by csett86** [comment]
Yes, still relevant for Debian 10+

**Comment by jely2002** [comment]
Sharing my solution for other folks who stumble across this issue.

In my [package.json](https://github.com/jely2002/youtube-dl-gui/blob/f02ff4bfadb76008e1983efb9aaca10eea112b4a/package.json#L40) I run a script after packaging the app:

```json
 "build": {
    "afterPack": "./appimage-fix.js",
```

This script renames the executable that usually gets launched to `<app-name>.bin` and creates a shell script with the old name  of the executable: `<app-name>`. So that when you launch the app-image the shell script gets executed.

The shell script then opens the `<app-name>.bin` file with the --no-sandbox option.


### [appimage-fix.js](https://github.com/jely2002/youtube-dl-gui/blob/360c40803e46c51f3e1c3e6fa8e967d5390c90eb/appimage-fix.js)
Just swap out the appName variable with the one specified in your package.json and you're good to go.
```js
const child_process = require('child_process'),
    fs = require('fs'),
    path = require('path');
    
const appName = "youtube-dl-gui";    

function isLinux (targets) {
    const re = /AppImage|snap|deb|rpm|freebsd|pacman/i;
    return !!targets.find ( target => re.test (target.name));
}

async function afterPack ({targets, appOutDir}) {
    if ( !isLinux ( targets ) ) return;
    const scriptPath = path.join(appOutDir, appName),
        script = '#!/bin/bash\n"${BASH_SOURCE%/*}"/' + appName + '.bin "$@" --no-sandbox';
    new Promise((resolve) => {
        const child = child_process.exec(`mv ${appName} ${appName}.bin`, {cwd: appOutDir});  
        child.on('exit', () => {
            resolve();
        });    
    }).then(() => {
        fs.writeFileSync (scriptPath, script);
        child_process.exec(`chmod +x ${appName}`, {cwd: appOutDir});
    });
}

module.exports = afterPack;
```

**Comment by csett86** [comment]
Thanks a lot @jely2002, this is a good workaround.

Based on your solution I have taken the same approach for https://github.com/jitsi/jitsi-meet-electron/pull/550, only difference is that it takes the executable name from the packager context and the renames and file writing is done via the async promises nodejs api: https://github.com/csett86/jitsi-meet-electron/blob/fix-231/linux-sandbox-fix.js

**Comment by jely2002** [comment]
Yes, this is still relevant for Debian 10+

**Comment by bahadirdogru** [comment]
yes

**Comment by probonopd** [comment]
Please reopen.

**Comment by mmaietta** [comment]
This is the only information I could locate on your request, but I don't know what AppRun is.
https://discourse.appimage.org/t/command-line-parameter-transfer/1537

AFAICT, this is not a feature that can be built by electron-builder. AppImage creation is handled by an upstream project https://github.com/develar/app-builder, so any feature request will need to be opened there.

**Comment by mmaietta** [comment]
@probonopd I found this PR that might serve what you need for AppImages?
https://github.com/electron-userland/electron-builder/pull/6429/files
Way to pass `--no-sandbox` for linux is via `executableArgs` in electron-builder config, but it's already considered default if no other args provided

Alternatively, in my project, I noticed previous logic for just adding it in `main/index.ts`
```
app.commandLine.appendSwitch("--no-sandbox");
```

**Comment by probonopd** [comment]
Thanks @mmaietta. This will help a lot of people.

**Comment by gergof** [comment]
I have made a tool that automatically applies the --no-sandbox flag when the unprivileged_userns_clone kernel feature is not enabled: https://www.npmjs.com/package/electron-builder-sandbox-fix

**Comment by probonopd** [comment]
Cool! We should add this to the AppImage (and Electron?) docs.

**Comment by mmaietta** [comment]
@probonopd AppImage target already applies `--no-sandbox` by default (added Oct 16th, 2020 in ede6d50ddb6c23fe6bbb056bd80509c8f2ea0116) if no custom `executableArgs` are passed in via the electron-builder config
https://github.com/electron-userland/electron-builder/blob/f205998999ff615c9ea63184520a1efbbff5a785/packages/app-builder-lib/src/targets/AppImageTarget.ts#L22-L23

**Comment by hz2018tv** [comment]
I am getting "[1109/191656.470723:FATAL:electron_main_delegate.cc(298)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.". passing --no-sandbox will fix it. but none of the executableArgs and the app.commandLine.appendSwitch("--no-sandbox") worked. (electron v21.2.2, electron-builder v23.6.0 FWIW)
