### ISSUE TITLE
appUpdater.quitAndInstall（）When updating, the installation interface suddenly exits, resulting in unsuccessful installation

### ISSUE THREAD

**Issue by livelyPeng** [electron-userland/electron-builder#5374]
"electron-updater": "^4.3.5",
    "electron": "^10.1.3",
    "electron-builder": "^22.8.1",

    "electron-updater": "^4.3.5",
    "electron": "^10.1.3",
    "electron-builder": "^22.8.1",
* **Electron Type (current, beta, nightly)**:

When updating, the installation interface suddenly exits, resulting in unsuccessful installation

**Comment by mastergberry** [comment]
I seem to be experiencing this issue as well...seems random. Only happened when i upgraded from 22.8.0 -> 22.9.1. After a few tries I did manage to get a successful install...and unfortunately due to the lack of a NSIS log I can't really track down the problem.
