### ISSUE TITLE
Cannot build msi packages on macOS Catalina (10.15) (nsis is fine)

### ISSUE THREAD

**Issue by ndtreviv** [electron-userland/electron-builder#5377]
* **Version**: `22.2.0`
* **Electron Version**: `6.0.10`
* **Electron Type (current, beta, nightly)**: `current`
* **Electron Updater version**: `4.1.2`
* **Target**: `msi`

I can create an nsis package (MyApp Setup.exe) on macOS Catalina with the configuration:

```
    "win": {
      "icon": "build/icons/icon.ico",
      "sign": "./electron/winsign.js",
      "publisherName": "MyCompany Ltd"
    },
    "nsis": {
      "perMachine": false
    },
```

using this command:

```
electron-builder build --win -c.extraMetadata.main=build/electron/main.js --publish never
```

**BUT**

I cannot create an msi target. If I try with this configuration:

```
 "win": {
      "target": "msi",
      "icon": "build/icons/icon.ico",
      "sign": "./electron/winsign.js",
      "publisherName": "MyCompany Ltd"
    },
    "nsis": {
      "perMachine": false
    },
```

I get this error:

```
  • building        target=MSI arch=x64 file=dist/MyApp 0.3.4.msi
  ⨯ macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too  
  ⨯ /Users/me/gitrepos/myapp/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

I've also tried with the `--x64` flag to no joy.

I need to be able to build an msi for our users. Actually, I need to be able to build a silent installer package AND an msi, but that's part of another ticket.

How can I get building msi-s working?

This is similar to #4305 but people there are building nsis, not msis.

**Comment by ndtreviv** [comment]
I have tried going the route of using the docker container to build the application, but alas: code signing does not work.

I'm signing my code with an EV Cert made available from an eToken, but the docker container can never see that eToken (https://github.com/docker/for-mac/issues/3110#issuecomment-456853036), so that will never work.

**Comment by Ayzrian** [comment]
I think it is expected that you can not build `.exe` file on MacO. 
Please use Windows machine to product Windows artifacts e.g. MSI.

**Comment by Ayzrian** [comment]
FYI, the logs say the same thing  
⨯ macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too

**Comment by ndtreviv** [comment]
> I think it is expected that you can not build `.exe` file on MacO.
> Please use Windows machine to product Windows artifacts e.g. MSI.

This is not correct. I can successfully build a windows exe (nsis package) from my mac. I cannot build an msi. Something in the process attempts to run a 32-bit application to generate the msi, and Catalina doesn't support 32 bit apps anymore, and _that_ is what the logs are saying.

Apparently wine64 is a thing now, so getting that working here should fix it, I would have thought.

**Comment by BoBoooooo** [comment]
the same question..
