### ISSUE TITLE
RPM Naming Issue? 

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#538]
> when trying to install a new version (or reinstall the same version):

Warning: app-1.5.2.rpm: Header V4 RSA/SHA1 Signature, key ID 3fb4cd59: NOKEY
Preparing... ################################# [100%]
file /opt/App/resources/app.asar from install of app-1.5.2-1.x86_64 conflicts with file from package app-1.5.1-1.x86_64

> After uninstallation, can install again, but noticed (as above) that the rpm install name is:
> 
> app-1.5.2-1 instead of just app-1.5.2.
>

**Comment by jarredkenny** [comment]
+1

I am experiencing the same issue and it is complicating automatic upgrades in our environment. Does anyone know what causes this?

**Comment by atypicalprogrammer** [comment]
+1

**Comment by develar** [comment]
Consider to use AppImage. PR welcome.
