### ISSUE TITLE
AppImage relaunch & auto-updater

### ISSUE THREAD

**Issue by busaku** [electron-userland/electron-builder#5380]
* **Version**: 22.9.1
* **Electron Version**: 9.3.3
* **Target**: AppImage (Linux)

My englisch is not the yellow of the egg, so please be patient ;)

I need to write an App who run on remote-systems. So, the software need to relaunch & update automatically.

But it seems to impossible, caus Auto-Updater doenst work with quitAndInstall(). (App doesnt restart)
Same issue on app.relaunch() with AppImage.

So, i found old issues at this repository, but no feedback since months. 
Is electron-builder the wrong  solution for my projekt? I did not found workarounds :(

Thank you in advance
pad

**Comment by busaku** [comment]
No one? 
Did a donation :(

**Comment by busaku** [comment]
...

**Comment by taratatach** [comment]
Hi @busaku. I'm not sure I understand your issue but I use `autoUpdater.quitAndInstall()` in my project and it works perfectly with AppImages (you can see the call here: https://github.com/cozy-labs/cozy-desktop/blob/master/gui/js/updater.window.js#L101).

Maybe post your code here so you can get more help?

**Comment by busaku** [comment]
Hey @taratatach,

thank you for your response.
so, without an app-update (just relaunch) app.relaunch(); wont restart the app. It close the app, but it doenst start a new one.

and caus i need an auto-update i only can use app-images. but i need to "relaunch" the app to.
so: appImage = auto-update works fine, but no relaunch
.deb or something else the relaunch works, but i have no auto-update :(

maybe i misunderstood and the auto-update will work with other types instead of appimage, but i wasnt able to build a running linux-autoupdate with something else than appimage.

thank you :)

**Comment by taratatach** [comment]
Like I said, auto-update with restart works for us with AppImages.
We also have a normal app restart action that you can find here: https://github.com/cozy-labs/cozy-desktop/blob/master/gui/js/tray.window.js#L229.

Without code I won't be able to help you more than that.

**Comment by busaku** [comment]
dude, let me give you a big kiss!
thats what iam looking for. so, restart worked like a charm :)
