### ISSUE TITLE
Code can't be signed when playwright is added as a dependency

### ISSUE THREAD

**Issue by SentoxAIO** [electron-userland/electron-builder#5383]
* **Version**: 22.9.1
* **Electron Version**: 10.1.5
* **Target**:  macOS

I basically have the same error as this [issue](https://github.com/electron-userland/electron-builder/issues/2010)

It's just a different module doing the same so ignoring **playwright-firefox/.local-browsers/** should do the job.

For publishing the update I use the GitHub Action of [electron-builder](https://github.com/samuelmeuli/action-electron-builder), not sure if something has to be changed there too.

**Comment by isaacaddis** [comment]
Same issue here! Have you figured this out?

**Comment by FoonkG** [comment]
Same issue here!

**Comment by hyped0001** [comment]
Same issue

**Comment by SentoxAIO** [comment]
Getting fixed by https://github.com/electron-userland/electron-builder/pull/5451
