### ISSUE TITLE
Electron-builder keeps rebuilding native dependency

### ISSUE THREAD

**Issue by MMcKester** [electron-userland/electron-builder#5386]
Hi,

I experience a behavior where I am not sure if this is intended. I use `"electron-builder": "22.9.1",` which installs all native module dependencies in my project.

I noticed that `yarn install` rebuilds my native dependencies every time, although the compiled files are already in the directory. Is this intended? If so, could someone help me out by hinting me how to cache the output? Any help is highly appreciated! Thank you!

**Comment by Githubber2021** [comment]
Hi, is there any chance for support on this? Any help is appreciated! Thank you!

**Comment by lukaneco** [comment]
i have the same issue
![image](https://user-images.githubusercontent.com/32082555/103377424-23374b00-4abe-11eb-9d40-14a24ede5eda.png)

**Comment by Slapbox** [comment]
You can disable rebuilding with `npmRebuild: 'false'` in the config - but it would definitely be ideal if Electron-Builder could detect the need and rebuild only if needed. We ended up disabling it, but that has its own issues like accidentally building with broken node deps.
