### ISSUE TITLE
portable splashImage not working

### ISSUE THREAD

**Issue by Coding-Kiwi** [electron-userland/electron-builder#5390]
* **Version**: 22.9.1

* **Electron Version**: 10.1.5

* **Target**: portable

I'm using
```json
"portable": {
    "splashImage": "build/splash.bmp"
},
```
but the only thing that happens when launching the app is this little flash, then the app launches normally.

![bug](https://user-images.githubusercontent.com/5007641/97910328-e19e5400-1d49-11eb-9044-a5ad8e89b899.gif)

The title of the window says "Setup : Installing"
Am I doing something wrong? I even tried https://www.npmjs.com/package/@catdad/to-bmp

**Comment by Pallies** [comment]
hello, I had the same concerns. But by changing the bmp image it works. the image I used was in .bmp format and dimension 440x350 with a size of 446kb

<img width="222" alt="Capture" src="https://user-images.githubusercontent.com/57674602/105542071-0ecf2280-5cf9-11eb-9ab5-7c54b98f9d83.PNG">

**Comment by vmartins** [comment]
Try converting the image to [BMP Version 3 (Microsoft Windows 3.x)](https://www.fileformat.info/format/bmp/egff.htm#MICBMP-DMYID.3.3).
ImageMagick convert:
```sh
$ convert splash-old.bmp BMP3:splash-new.bmp
```

**Comment by leandrofreires** [comment]
> Try converting the image to [BMP Version 3 (Microsoft Windows 3.x)](https://www.fileformat.info/format/bmp/egff.htm#MICBMP-DMYID.3.3).
> ImageMagick convert:
> 
> ```shell
> $ convert splash-old.bmp BMP3:splash-new.bmp
> ```
this is real, i had to convert from 32bit bmp to 24bit and it worked, i used paint anyway, opened the image and saved as 24bit bmp easier

**Comment by Coding-Kiwi** [comment]
Just as a little follow up quite some time later:
I generated a bmp using imagick and compared it to the one I had, the difference was that the tool I used set the resolution to 0, imagick sets a default of 72dpi.

So yeah, a bitmap with 24bit and nonzero resolution is needed, we might need to add this to the documentation
