### ISSUE TITLE
Getting white screen when running the application

### ISSUE THREAD

**Issue by gabyvlad96** [electron-userland/electron-builder#5396]
* **Version**: 6.14.8

* **Electron Version**: 9.3.2

* **Target**: nsis

I use electron with react and webpack. For some reason it cannot find the path to the app.js and I am getting a blank screen and receiving 
`Failed to load resource: net::ERR_FILE_NOT_FOUND` error in the console when running the app.

I know this isn't a problem with the path for `index.html` as other responses address this, but the problem is in finding app.js because if I add a h2 tag for example I can get that text showing in the app so I assume it's because it cannot find the `app.js` file. This problem is also available on macOS when building for darwin.

Here is the body of the `index.html` file:
```
	<body>
		<div id="root"></div>
		<h2>Hello</h2>
		<script src="../build/js/app.js"></script>
	</body>
```
The `app.js` is generated by webpack by running `webpack --config webpack.common.js --watch` so it's not the original App.js file that is the entry of the application.

In this current configuration I am able to build the app and not having this problem with the other packages: electron-packager and electron-forge. So I assume this is a problem strict with `electron-builder`.

**Comment by Anil8753** [comment]
Can you please update the MacOS details.
