### ISSUE TITLE
You cannot open the application because this application is not supported by this Mac, Big Sur Silicon mac 

### ISSUE THREAD

**Issue by ahmadwaliesipick** [electron-userland/electron-builder#5397]
I am using current latest Electron Beta build to create dmg at Big Sur Silicon mac. Build has successfully created and installed. Once i try to open app i see below error.
https://share.getcloudapp.com/Z4uyExDY

Once I run build through electron command then app is working fine but after dmg create app is not working.
Anyone has experience this issue?

**Comment by Anil8753** [comment]
Is there any workaround available?

**Comment by ahmadwaliesipick** [comment]
No yet @Anil8753

**Comment by ahmadwaliesipick** [comment]
@Anil8753  see here they have put this ticket in backlog and marked closed even still electron-builder is not supporting ARM64 build. #5095

**Comment by Anil8753** [comment]
@ahmadwaliesipick did you find any other alternative. Yesterday Apple released Silicon hardware and user can not launch Electron builder apps, such a painful situation.

**Comment by ishowshao** [comment]
waiting...

**Comment by ahmadwaliesipick** [comment]
> @ahmadwaliesipick did you find any other alternative. Yesterday Apple released Silicon hardware and user can not launch Electron builder apps, such a painful situation.

I was thinking to use electron-packager but it is lot of work.

**Comment by Anil8753** [comment]
https://github.com/electron/electron/issues/26530#issuecomment-729163078
@MarshallOfSound  says, Confirmed that this will work just fine on the M1 machines. If you want to work around this on your DTK ensure you launch the app from the terminal directly. E.g. ./MyApp.app/Contents/MacOS/MyApp

**Comment by ishowshao** [comment]
`electronDownload.arch = arm64` is ok

**Comment by aeschylus** [comment]
https://github.com/beakerbrowser/beaker/issues/1861
