### ISSUE TITLE
Building 64-bit windows actually produces 32-bit.

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#540]
When I check in the task manager it shows as Product Name (32-bit).

generated as; 

`build --win --mac --linux --x64 --ia32`

**Comment by develar** [comment]
NSIS or Squirrel?

**Comment by kunkinkan** [comment]
NSIS. Will try new release soon.

**Comment by develar** [comment]
Please in the future specify target ;)

**Comment by develar** [comment]
Duplicates #536
