### ISSUE TITLE
downloadUpdate throw error on temp file

### ISSUE THREAD

**Issue by shivarkarimi** [electron-userland/electron-builder#5401]
"electron-builder": "22.8.1",
"electron": "9.1.2",
"electron-updater": "4.3.5",
"Angular: "7.1.1"
MAC: Catalina

I get the following error `no such file or directory for temp-* file in the cache folder`.  It seems like it is trying to rename the `temp` file but temp file is not in the folder yet.

```
   autoUpdater.logger = logger;
    autoUpdater.autoDownload = false;
    autoUpdater.allowDowngrade = false;
    autoUpdater.autoInstallOnAppQuit = false;

    ipcMain.on(CHANNELS.AUTO_UPDATE.UPDATE, (event, data) => {
      try {
        autoUpdater.downloadUpdate();
      } catch (error) {
        this.sendEventToWindow(CHANNELS.AUTO_UPDATE.ERROR, error);
        logger.error('Auto-updater Manager: Error happened during downloading files: ' + error);
      }
    });

   ipcMain.on(CHANNELS.AUTO_UPDATE.CHECK_UPDATE, (event, data) => {
      const feedURL = this.getFeedUrl(data.hostname);
      autoUpdater.setFeedURL(feedURL);

      try {
        autoUpdater.checkForUpdates();
      } catch (error) {
        this.sendEventToWindow(CHANNELS.AUTO_UPDATE.ERROR, error);
        logger.error('Auto-updater Manager: Error happened during checking for updates: ' + error);
      }
    });

    autoUpdater.on('update-downloaded', (event, info) => {
      logger.info('Auto-updater Manager: INSTALL APP event', event);
      this.sendEventToWindow(CHANNELS.AUTO_UPDATE.DOWNLOAD_COMPLETE, event);
      this.installNewVersion(event);
    });

  private installNewVersion(event: any): void {
    let counter = 0;
    const repetitions = 5;
    const errorMessage = 'Update failed, unable to locate downloaded files.';

    const intervalId = setInterval(() => {
      logger.log(`Auto-updater Manager: ${event}`);

      if (event && this.checkZipFileExists(event) && this.checkUpdateInfoFileExists(event)) {
        autoUpdater.quitAndInstall();
      } else {
        logger.log(`Auto-updater Manager: Could not find downloaded files, Attempt ${counter},  ${event.downloadedFile}`);
      }

      if (++counter === repetitions) {
        logger.error('Auto-updater Manager: Could not find downloaded files: ' + event);
        this.sendEventToWindow(CHANNELS.AUTO_UPDATE.ERROR, errorMessage);
        clearInterval(intervalId);
      }
    }, 5000);
  }

```

`[2020-11-03 14:46:54.279] [info] New version 6.4.1-dev has been downloaded to /Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip [2020-11-03 14:46:54.285] [error] Error: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip' [2020-11-03 14:46:54.286] [error] Auto-updater Manager: {"errno":-2,"code":"ENOENT","syscall":"rename","path":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip","dest":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip"}. Error message: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip' [2020-11-03 14:46:54.288] [error] Error: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip' [2020-11-03 14:46:54.288] [error] Auto-updater Manager: {"errno":-2,"code":"ENOENT","syscall":"rename","path":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip","dest":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip"}. Error message: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip'
`

**Comment by steabert** [comment]
We encountered the same problem with electron-updater 4.3.5. The problem goes away when using the `.checkForUpdatesAndNotify` instead of the `.checkForUpdates` method.
