### ISSUE TITLE
Effective configuration for CI builds

### ISSUE THREAD

**Issue by NullEnt1ty** [electron-userland/electron-builder#5403]
* **Version**: 22.2.0

* **Electron Version**: 7.1.8
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, Windows

I was wondering why electron-builder does not write an effective configuration file when building the application using a CI platform. So I dug a bit in the source code and found this:

https://github.com/electron-userland/electron-builder/blob/d5d21da12f5efaf02659ce8d32c48440f6cf91ff/packages/app-builder-lib/src/packager.ts#L358-L362

Why on earth are you disabling this feature for CI builds? It is *especially* useful for CI builds to investigate failed builds. I couldn't find any reasoning for this so I'm hoping to get an answer here.

Thanks!

**Comment by NullEnt1ty** [comment]
> Is this still relevant?

Yes.

**Comment by Marantesss** [comment]
Just came across this issue. I'm trying to build an electron app with Circle CI.

The build works fine (at first glance), however [`latest.yml`](https://www.electron.build/auto-update.html#staged-rollouts) is not being generated.
