### ISSUE TITLE
cannot execute  cause=signal: illegal instruction

### ISSUE THREAD

**Issue by gitTerebi** [electron-userland/electron-builder#5407]
Just built a new PC that uses new ryzen 5900x

Had to do some fandangling to get vmware images to start running as well.

When I try to buil for windows on a macos 10.13 image I always get error:
**cannot execute  cause=signal: illegal instruction**

>   • packaging       platform=win32 arch=x64 electron=8.5.3 appOutDir=dist/win-unpacked
>   ⨯ cannot execute  cause=signal: illegal instruction
>                     command=/Users/tan50/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/tan50/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.5.0/rcedit-ia32.exe '/Users/tan50/Dropbox/repo/scm-next/dist/win-unpacked/SEO Content Machine.exe' --set-version-string FileDescription 'SEO Content Machine' --set-version-string ProductName 'SEO Content Machine' --set-version-string LegalCopyright 'Copyright © 2020 SEO Content Machine' --set-file-version 2020.11.334 --set-product-version 2020.11.334.0 --set-version-string InternalName 'SEO Content Machine' --set-version-string OriginalFilename '' --set-version-string CompanyName 'SEO Content Machine' --set-icon /Users/tan50/Dropbox/repo/scm-next/dist/.icon-ico/icon.ico
>                     workingDir=
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scm-next-plus@2020.11.334 dist1: `electron-builder -w`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the scm-next-plus@2020.11.334 dist1 script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/tan50/.npm/_logs/2020-11-08T14_47_12_851Z-debug.log

I have: "electron-builder": "21.2.0"

Anyone else seeing this issue? Googling turns up no answers yet.

**Comment by abrorAbdullaev** [comment]
With what command you have run the builder, and also what is your configurations for builder?

**Comment by gitTerebi** [comment]
I gave up on it, had to do with one of the build tools running a wine emulator that relied specifically on some Intel instructions.

Note that I can build fine on my windows 10 machine, just doesn't work on macos in wmware on specifically a ryzen cpu.

**Comment by abrorAbdullaev** [comment]
As far as I know, you cannot build windows installers on MACOS machines, and the other way around. I had a similar issue and had to give up as I am using only win10 and wanted to build for MACOS.
