### ISSUE TITLE
Builder claims we should rename "osx" in package.json, but...

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#541]
When doing so (renaming to "mac"), dmg settings no longer apply.

**Comment by develar** [comment]
dmg settings should be in `dmg`.

**Comment by kunkinkan** [comment]
No, now it's in osx.dmg, but mac.dmg doesn't work. Or is the "mac" deprecation notice only for the build command? If so, makes no sense to not use "mac" in package json also?

**Comment by develar** [comment]
`build.dmg` doesn't work?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#DmgOptions

**Comment by kunkinkan** [comment]
oops sorry, bit confusing i mean osx.contents and osx.icon-size.. These are also dmg options but they are not under build.dmg but instead build.osx (why?) -- but when I rename build.osx to build.mac those settings aren't read.

**Comment by develar** [comment]
`mac` now doesn't configure DMG. See release notes why.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v5.6.0
