### ISSUE TITLE
Is comodo code signin certificate worked with electron builder?

### ISSUE THREAD

**Issue by mvkanha** [electron-userland/electron-builder#5411]
I wish to add comodo code signin certificate in my electron application, but I am confused it will work or not So Can you please clear me on my doubt ?

Here is link of certificate https://www.comodoca.com/code-signing

**Comment by fspoettel** [comment]
@mvkanha Yes, both certificate types should work with `electron-builder`. A couple of things to note:

* Standard code signing cert. show a _Windows SmartScreen_ warning until you have acquired a certain amount of installs and a bit of time has passed.
* EV certificates will never show that warning, however...
* EV certificates are bound to a hardware token so if you want to use a CI build env. (AppVeyor, CircleCI) you will have a hard time with them
* Standard code signing certs can be used on CI without issues

You can generally use code signing certs from any vendor (Comodo, GlobalSign, DigiCert) for signing Windows applications. You will need an Apple Developer cert. if you want to sign apps for macOS.

**Comment by AleshaOleg** [comment]
I'm using the Comodo EV certificate. Works perfectly fine didn't have any issues

**Comment by mvkanha** [comment]
Thanks @AleshaOleg and @fspoettel
