### ISSUE TITLE
[ Question ] App Size And .dll Generation

### ISSUE THREAD

**Issue by BLUE-DEVIL1134** [electron-userland/electron-builder#5414]
* **Version**: Latest one

* **Electron Version**: Latest
* **Electron Type (current, beta, nightly)**: current

* **Target**: Win10 nsis x64 (Later macOS And Linux)

So, Its Just A Question..
I Was Making A App and when i build its executable for win 64 it worked but
the size is 293 mb

i use only node-fetch and superagent as dependencies

Now, vs code is less than 100mb and has more dependencies that this..
The total lines of code used for app is not more than 1000..

**Question : How Can I Reduce The Size And Most Importantly How To Make The App In Such Way That It Auto Generates dll Files Instead Of Creating A StandAlone App?**

**Comment by BLUE-DEVIL1134** [comment]
any help?

**Comment by sleeyax** [comment]
@BLUE-DEVIL1134 did you solve this? My app is a little too big as well and I don't immediately see why...

**Comment by BLUE-DEVIL1134** [comment]
@sleeyax  Yes, I Was Having A Lot Of Dependencies In The Directory, So `electron-builder` added all the necessary and un-necessary dependencies..
The Whole `node_modules/` dir indeed..

The Best And Easiest Solution This Is ->
```python
Create A New Directory
Move All Required Files To The New Directory Except The `node_modules` Directory..

Now Just Install The Dependencies That Are Required Including `electron` and `electron-builder`
Then Build Your App..

For Me, The Before Size Was `~367.83mb` 
After This My App Size Is `~53mb`
```

**Comment by sleeyax** [comment]
> @sleeyax  Yes, I Was Having A Lot Of Dependencies In The Directory, So `electron-builder` added all the necessary and un-necessary dependencies..
> The Whole `node_modules/` dir indeed..
> 
> The Best And Easiest Solution This Is ->
> ```python
> Create A New Directory
> Move All Required Files To The New Directory Except The `node_modules` Directory..
> 
> Now Just Install The Dependencies That Are Required Including `electron` and `electron-builder`
> Then Build Your App..
> 
> For Me, The Before Size Was `~367.83mb` 
> After This My App Size Is `~53mb`
> ```

Huh, odd. The docs state that electron-builder won't copy developer dependencies :thinking: Oh well, this works too. sthanks!

**Comment by BLUE-DEVIL1134** [comment]
> > @sleeyax  Yes, I Was Having A Lot Of Dependencies In The Directory, So `electron-builder` added all the necessary and un-necessary dependencies..
> > The Whole `node_modules/` dir indeed..
> > The Best And Easiest Solution This Is ->
> > ```python
> > Create A New Directory
> > Move All Required Files To The New Directory Except The `node_modules` Directory..
> > 
> > Now Just Install The Dependencies That Are Required Including `electron` and `electron-builder`
> > Then Build Your App..
> > 
> > For Me, The Before Size Was `~367.83mb` 
> > After This My App Size Is `~53mb`
> > ```
> 
> Huh, odd. The docs state that electron-builder won't copy developer dependencies 🤔 Oh well, this works too. sthanks!

it dosent copy developer dependencies
it directly adds the whole `node_modules/` folder
