### ISSUE TITLE
electron-updater broken on Windows since Windows 10 1809 version

### ISSUE THREAD

**Issue by ankar84** [electron-userland/electron-builder#5415]
* **Version**: 4.3.5
* **Electron Version**: 10.0.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: I don't know

All Rocket.Chat community have issue with auto update on RC desktop client on any recent Windows 10 version since 1809. 
On Windows 1803 electron-updater works perfect!
So. I think some Microsoft security features introduced in Windows 10 1809 broke that update functionality.
Here is an issue in RC desktop app repo https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670#issuecomment-725355062

**Comment by EtienneLem** [comment]
@ankar84 Curious if you found a workaround? Looks like our Windows users are stuck in an infinite loop of
1. Auto-updater reporting that an update is available
2. Update downloaded
3. Nothing
4. Back to step 1

**Comment by ankar84** [comment]
> @ankar84 Curious if you found a workaround? Looks like our Windows users are stuck in an infinite loop of
> 1. Auto-updater reporting that an update is available
> 2. Update downloaded
> 3. Nothing
> 4. Back to step 1

Hi. I don't have a workaround for that issue.

Step 3 is not **nothing**, downloaded installer is deleted by (I guess) some new Windows security feature, which was implemented in Windows 10 version 1809.
On early Windows versions update process works fine in my case.

**Comment by ankar84** [comment]
Issue is still here

**Comment by EtienneLem** [comment]
FWIW; In our case that was a misconfiguration of a new code signing certificate and then our CloudFront distribution was being flagged as malware by Windows Defender. Once the code signing certificate fixed, we rolled out a new distribution and auto-updates started working properly again.

**Comment by ankar84** [comment]
> FWIW; In our case that was a misconfiguration of a new code signing certificate and then our CloudFront distribution was being flagged as malware by Windows Defender. Once the code signing certificate fixed, we rolled out a new distribution and auto-updates started working properly again.

Thanks a lot @EtienneLem 
@ggazzo @tassoevan @rodirok can you check signing certificate for current desktop RC electron application? Or just resign it with new certificate?

**Comment by rodrigok** [comment]
@ankar84 we will have someone joining the company to take care of the electron builds and improvements soon, I hope in the next weeks so we can focus on those issues. Thanks for the patience :)

**Comment by ankar84** [comment]
Thanks, Rodrigo!
