### ISSUE TITLE
white screen after build, but runs well on my own PC!

### ISSUE THREAD

**Issue by cyc790** [electron-userland/electron-builder#5416]
* **Version**: 22.2.0

* **Electron Version**: 7.1.7
* **Electron Type (current, beta, nightly)**:

* **Target**: mac

Runs fine in development.  But the dmg file after build only run wells in my own PC(the one build on), show white screen on  other PC. there is no error in console, seems javascript file does not execute in html. How to solve it? thanks a lot.

**Comment by idanwork** [comment]
This may be wrong path of the javascript file reference from your html file

Did you loading it relative to the "app.getAppPath()" method of electron

`${app.getAppPath()}/index.js` should work if your index.js file is in the root
