### ISSUE TITLE
install-app-deps not accepting --config flag

### ISSUE THREAD

**Issue by sirtimid** [electron-userland/electron-builder#5417]
* **Version**: 22.9.1

* **Electron Version**: 9.3.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: all

I want my dev builds not to build `ia32` for windows on CI, so I 've created a config file that detects that and feed the `build` command with the file, but `install-app-deps` command is not accepting `--config` flag, and this becomes a hassle to setup if we don't have the config in package.json. 

It would be great if `install-app-deps` accepted also the `--config` flag, is there a reason why this is not supported?

**Comment by mmaietta** [comment]
It looks like you could add the option here for yargs to parse
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/cli/install-app-deps.ts#L18

Just need to also make sure that you update here as well to respect the argv override:
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/cli/cli.ts#L88-L90
