### ISSUE TITLE
MAS build signing (cannot be opened because the developer cannot be verified.)

### ISSUE THREAD

**Issue by Gimanh** [electron-userland/electron-builder#5419]
* **Version**: 22.9.1

* **Electron Version**:10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas

I have an open-sourced [app](https://github.com/Gimanh/handscream), so every file you can found there.

* I run `npm run build` and get TaskView.app and TaskView.pkg  
After building MAS, I cannot start my application (TaskView.app). I received a message (cannot be opened because the developer cannot be verified).  
I also cannot start TaskView.pkg I am trying to install the application, the installation was successful, but the application was not installed (can not find in intalled apps).  

* Then I try to sign TaskView.app by using sign.sh script  
* I get TaskView-Publish-Ready.pkg.pkg  
* I am trying to install the TaskView-Publish-Ready.pkg.pkg, the installation was successful, but the application was not installed (can not find in intalled apps).  

### sign.sh
````
#!/bin/bash

CURRENT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

COMPANY_DEVELOPER_ID="XXXXX XXXXX (XXXXXXX)"

# Name of your app.
APP="TaskView"
# The path of your app to sign.
APP_PATH="$CURRENT_PATH/../build/mas/$APP.app"
# The path to the location you want to put the signed package.
RESULT_PATH="$CURRENT_PATH/../build/mas/$APP-Publish-Ready.pkg"
# The name of certificates you requested.
APP_KEY="3rd Party Mac Developer Application: $COMPANY_DEVELOPER_ID"
INSTALLER_KEY="3rd Party Mac Developer Installer: $COMPANY_DEVELOPER_ID"
# The path of your plist files.
CHILD_PLIST="child.plist"
PARENT_PLIST="parent.plist"
LOGINHELPER_PLIST="loginhelper.plist"

FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libnode.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"
````

### child.plist

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>

````

### parent.plist
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>XXXXXX.com.host.app</string>
    </array>
  </dict>
</plist>
````

### loginhelper.plist
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
  </dict>
</plist>

````

**Comment by Farshatov-Alex-Magora** [comment]
Have same error. I guess it is related to entitlments.mas.plist and inherit.plist with sandbox flag turned on. But it is required to be true for MAS upload...

**Comment by Gimanh** [comment]
@Farshatov-Alex-Magora If I find solutions I will share here! I hope you too :)

**Comment by Vishal1419** [comment]
I don't have much knowledge on signing and notarizing apps. But I found this blog post that may help you guys: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by Gimanh** [comment]
> I don't have much knowledge on signing and notarizing apps. But I found this blog post that may help you guys: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

Thanks for help! But this is about notarizing and it works!

**Comment by PaulKeefe** [comment]
I'm having the same issue with a non-MAS app. When I try to run the app it gives my appId plus other characters, so I can never approve it in Security & Privacy (using Allow Anyway). The id looks like this "TeamID.com.companyname.product.RANDOMCHARS" and the random chars change each time you open the app. 

If I run codesign -vv everything checks out. The same goes for pkgutil --check-signature. At this point I have no idea how to proceed.

**Comment by PaulKeefe** [comment]
I found the issue for me, and I hope it will help others here. It was simply about having the correct entitlements. In my case, because it is not a MAS app, I had to remove the sandbox entitlement. To get it to work I needed the following ones:

`<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
  </dict>
</plist>`

I would try adding and removing entitlements until your app runs. Good luck!
