### ISSUE TITLE
-c.extraMetadata option not working on Windows

### ISSUE THREAD

**Issue by emlys** [electron-userland/electron-builder#5420]
* **Version**: 22.9.1
* **Electron Version**: 10.1.2
* **Electron Type (current, beta, nightly)**: current
* **Target**: Windows

The CLI docs state that `electron-builder -c.extraMetadata.foo=bar` should "set package.json property foo to bar". This apparently isn't being parsed correctly on Windows.

Windows:

> Run npx --no-install electron-builder build --windows -c.extraMetadata.foo=bar
>   • electron-builder  version=22.9.1 os=10.0.17763
>   • artifacts will be published if draft release exists  reason=CI detected
>   ⨯ ENOENT: no such file or directory, open 'D:\a\invest-workbench\invest-workbench\.extraMetadata.foo=bar'  stackTrace=Error: ENOENT: no such file or directory, open 'D:\a\invest-workbench\invest-workbench\.extraMetadata.foo=bar'
> Error: Process completed with exit code 1.

MacOS:

> Run npx --no-install electron-builder build --mac -c.extraMetadata.foo=bar
  • electron-builder  version=22.9.1 os=19.6.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=darwin arch=x64 electron=10.1.2 appOutDir=dist/mac
...

**Comment by emlys** [comment]
My mistake! Was using the wrong shell in CI.

**Comment by rafaellehmkuhl** [comment]
Hey!
I'm having the same problem.
Could you help me with what exactly was wrong with your shell?
