### ISSUE TITLE
Building distribution-specific packages on ARM host machine.

### ISSUE THREAD

**Issue by SpacingBat3** [electron-userland/electron-builder#5422]
## Description
I'm trying to built an Electron application with ARM64 host machine and it doesn't seem to be possible because it uses some X86 binaries instead of the native one.

## Possible fixes:
- use the binaries (like `ruby`) depending on host architecture (`aarch64` for `arm64` etc.)

## Additional Information

* **Version**: 22.9.1

* **Electron Version**: v10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Host**: `arm64`
* **Target**: any (`arm64`,`armv7`,`ia32`,`x64`)

**Comment by utyfua** [comment]
I guess I have the same issue. 
I wanna build my app only for linux/armv7. If I build right away on the target system - no problem.
But I found hint [here](https://www.electron.build/multi-platform-build):

> If your app has native dependency, it can be compiled only on the target platform unless prebuild is not used.
prebuild is a solution, but most node modules don’t provide prebuilt binaries.

Also I tried docker with `--platform linux/armv7`, but it did not help. Maybe I was doing something wrong.

I only see one possible solution: just fork necessary packages and build them on all necessary systems in advance using [prebuild package](https://www.npmjs.com/package/prebuild)

**Comment by SpacingBat3** [comment]
Please note that by mean of the phrase:
> use the binaries (like ruby) depending on host architecture (aarch64 for arm64 etc.)

I meant the build dependencies – I bet they're hard-coded for X86 operating systems only...
I think the possible fix would be just using the binaries basing on the host architecture, not the target one for the all of the build dependencies. Right now building on the ARM gives these results:
```
  ⨯ cannot execute  cause=exit status 1
                    errorOut=/home/user/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby: line 6: /home/user/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real/ruby: cannot execute binary file: Exec format error
```
The output of `file /home/user/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real/ruby`:
```
/home/user/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real/ruby: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.9, stripped
```
As you can see it tries to run **X86 ruby** executable instead of the native ARM64 one... and this couldn't just work without any additional layer (like emulation or virtualization).

**Comment by utyfua** [comment]
I think we have the same nature of the problem.
In my case the linux/armv7(AppImage) build that was made on amd64 at startup knocks out such an error:
```
/tmp/.mount_kPYl0B/resources/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /tmp/.mount_kPYl0B/resources/app/node_modules/node-hid/build/Release/HID-hidraw.node: wrong ELF class: ELFCLASS64
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/tmp/.mount_kPYl0B/resources/app/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/tmp/.mount_kPYl0B/resources/app/node_modules/node-hid/nodehid.js:19:46)
```

I will try something from next thing:
- https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/
- https://cloud.google.com/solutions/building-multi-architecture-container-images-iot-devices-tutorial

I will let you know if I can still make a build using something of cloud thing.

**Comment by SpacingBat3** [comment]
> I think we have the same nature of the problem.
> In my case the linux/armv7(AppImage) build that was made on amd64 at startup knocks out such an error:
> 
> ```
> /tmp/.mount_kPYl0B/resources/app/node_modules/bindings/bindings.js:121
>         throw e;
>         ^
> 
> Error: /tmp/.mount_kPYl0B/resources/app/node_modules/node-hid/build/Release/HID-hidraw.node: wrong ELF class: ELFCLASS64
>     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
>     at Object.func [as .node] (electron/js2c/asar.js:140:31)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at bindings (/tmp/.mount_kPYl0B/resources/app/node_modules/bindings/bindings.js:112:48)
>     at loadBinding (/tmp/.mount_kPYl0B/resources/app/node_modules/node-hid/nodehid.js:19:46)
> ```
> 
> I will try something from next thing:
> 
> * https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/
> * https://cloud.google.com/solutions/building-multi-architecture-container-images-iot-devices-tutorial
> 
> I will let you know if I can still make a build using something of cloud thing.

Um... I think that's the problem with the issue with the node_modules...

Maybe give me the output of `file /tmp/.mount_kPYl0B/resources/app/node_modules/node-hid/build/Release/HID-hidraw.node`? Seems that uses some pre-built binaries?

Please note you're trying to *cross-compile* for ARMv7 on **amd64** host architecture and I'm trying to make compilation working on *arm64* for any arch (not just ARMv7 targets).

**Comment by utyfua** [comment]
[HID-hidraw.zip](https://github.com/electron-userland/electron-builder/files/5548969/HID-hidraw.zip) built on amd64 for armv7.

Anyway we are on one way) I wanna help but I don't know how) I have no idea which way to dig

**Comment by utyfua** [comment]
Also I haven't issues for win/ia32 and win/x64 built at linux/amd46

**Comment by utyfua** [comment]
By the way my discord: Utyfua#7777

**Comment by tanyo520** [comment]
fpm arm64?

**Comment by SpacingBat3** [comment]
> [HID-hidraw.zip](https://github.com/electron-userland/electron-builder/files/5548969/HID-hidraw.zip) built on amd64 for armv7.
> 
> Anyway we are on one way) I wanna help but I don't know how) I have no idea which way to dig

@utyfua I believe your issue were described there: [#5153](https://github.com/electron-userland/electron-builder/issues/5153).
You're trying to built it on AMD64 machine for ARM64. This calls **cross-compiling**. I want to have a **regular compilation** process fixed with the ARM architectures. Anyway, most of your comments are quite off-topic there, you should mention about your issue somewhere else – maybe eventually at the `node-hid` project? I don't think that's the `electron-builder`'s fault, but rather of some of the `node_modules` that is installed with the wrong architecture.

> fpm arm64?

@tanyo520 What are you asking/suggesting me with that? Could you describe it a little more?

**Comment by SpacingBat3** [comment]
And also @utyfua in my situation the `electron-builder` is an issue as it uses the some sort of FPM dependency (@tanyo520 you were about that, right?) that is for `linux-x86` platform only. Nothing's wrong with the `node_modules` and I were able to package it as an `tar.gz`, `AppImage` and (probably, as my OS has some troubles with the snap itself) `SNAP` of the electron application.

Anyway, IDK if there's an `FPM-arm64` somewhere... I don't even know from which repo/server it is taken by the `electron-builder` (I could try to compile it for the ARM64 if it is open-source and that's the case).

**Comment by hovancik** [comment]
Yes.
