### ISSUE TITLE
Override artifactName from command line do not expand File Macros

### ISSUE THREAD

**Issue by ggreco** [electron-userland/electron-builder#5428]
* **Version**:  22.9.1
* **Electron Version**: 10.1.x
* **Electron Type (current, beta, nightly)**: current
* **Target**: fails both on windows and mac

I want to build nightly build in my CI server, so I'm trying to override the artifactName from the command line:

`npx electron-builder build --mac --win -c.artifactName="${productName}-${arch}-${version}-nightly.${ext}" --publish never`

The File Macros are not expanded at all resulting in this:

 `• building        target=macOS zip arch=x64 file=dist/---nightly.`
 `• building        target=DMG arch=x64 file=dist/---nightly.`

And the command fails since it cannot produce dmg/zips with those names...

**Comment by AlternateVoid** [comment]
I have the same issue. Guess I'll be stuck to change the config file programmatically before run electron-builder
