### ISSUE TITLE
Change the default icon issues

### ISSUE THREAD

**Issue by caishengmao** [electron-userland/electron-builder#543]
.build.mac   How to use the icon this parameter?

**Comment by develar** [comment]
Why you cannot follow convention?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-icon

**Comment by caishengmao** [comment]
The document is not very understand, can you illustrate it?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder#in-short step 3. What is not clear?

**Comment by caishengmao** [comment]
@develar Still hadn't changed, can you tell me the specific need to operate? Or need to modify what place? My project now, only the index HTML, main. Js, package. Json, logo. Icns, thank you

**Comment by develar** [comment]
What problem do you have if you follow step 3?

**Comment by caishengmao** [comment]
@develar  I change in package.json so, but I didn't put the new icon was modified, did not know it can modify to write it off?   "build": "electron-packager . --platform=darwin --arch=x64 --icon=./logo.icns --version=0.37.8 yqx --ignore=node_modules/electron-*"

**Comment by develar** [comment]
@caishengmao Please do https://github.com/electron-userland/electron-builder#in-short, you don't need to execute electron-packager prior to electron-builder.

> Create directory build in the root of the project and put your background.png (MacOS DMG background), icon.icns (MacOS app icon) and icon.ico (Windows app icon).

Did you create `build/icon.icns` file (or `build/icon.ico` for windows)?

**Comment by caishengmao** [comment]
@develar  How to create build/icon.icns file？

**Comment by develar** [comment]
@caishengmao Sorry, your question is strange. Ask your designer to draw icon and save it as `build/icon.icns`.

**Comment by caishengmao** [comment]
@develar  Icon, and also save the build/icon. Icns, but haven't been able to modify, is now don't know where to modify.

**Comment by caishengmao** [comment]
@develar  "build": "electron-packager . MyApp && cp logo.icns MyApp.app/Contents/Resources/electron.icns“   Excuse me, is this change?

**Comment by develar** [comment]
@caishengmao Please see sample project https://github.com/develar/onshape-desktop-shell

**Comment by caishengmao** [comment]
@develar  This demo  https://github.com/electron/electron-api-demos, change icon to another, why I can't change?
