### ISSUE TITLE
[Question] Retrieve GUID of nsis package

### ISSUE THREAD

**Issue by fatoldsun00** [electron-userland/electron-builder#5430]
* **Version**: 21.2.0

* **Electron Version**: 7.3.2
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis-web

Hi,

It's possible to retrieve the GUID of an app build with electron-builder (nsis). I want modify registry but the app have a GUID auto generate.

Thanks

**Comment by mmaietta** [comment]
Previously I've browsed the registry until I found the right files.  First though, have you tried these solutions? https://stackoverflow.com/a/29937569

**Comment by fatoldsun00** [comment]
Hi mmaietta, yes i browse registry too but it's not very clean.

I can't change appId cause app use autoupdate, it's too dangerous.

Thank for the url, i go to read that.

Thanks for response !
