### ISSUE TITLE
hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by EdmarPereira** [electron-userland/electron-builder#5431]
I'm not able to generate builds for MacOs, I've made several attempts to change versions and the error persists:

`  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                    Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                        at ChildProcess.<anonymous> (/.../node_modules/builder-util/src/util.ts:243:14)
                                                                        at Object.onceWrapper (events.js:417:26)
                                                                        at ChildProcess.emit (events.js:310:20)
                                                                        at maybeClose (internal/child_process.js:1021:16)
                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`

I did the tests with the following combinations
electron-builder: 20.36.2
electron: 3.0.9

electron-builder: 21.1.6
electron: 7.15.0

electron-builder: 21.1.5
electron: 5.0.8

and also with the latest version for both
electron-builder: 22.9.1
electron: 11.0.2

All tests were done using a Macbook Air Catalina version 10.15.7 and Node version 12.16.3. Sometimes I have some success using debug mode with `DEBUG=electron-builder node_modules/.bin/electron-builder build -m`
Additional information: I do not use any kind of antivirus.

Please help me, I create a big project but in every version released I have problems building versions for MacOs.

**Comment by ahmetuysal** [comment]
I have the same issue.

**Comment by btzsoft** [comment]
having the same issue, also it says:

```
Error output:
- Searching dependency tree
rm: ./Release/.deps/Release/obj.target/validation/src/validation.o.d.raw: No such file or directory
make: *** [Release/obj.target/validation/src/validation.o] Error 1
✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
node-gyp failed t
```

**Comment by EdmarPereira** [comment]
I ask for help because in the company where we work we have created a very large project using electron, if we cannot solve this problem we will have to look for another option. I don't know what else to do, the only problem we found is to generate builds for MacOs, we bought a Macbook just for that, we don't have anything else installed to avoid conflicts, please if anyone has a solution for this I would really appreciate it.
Thank you.

**Comment by mmaietta** [comment]
What version of xcode are you guys using? What version of python?

Also, @btzsoft, thanks for adding. electron-rebuild is a different project, but I think it points to this being a node-gyp env issue. I found these in a quick search for `validation.o.d.raw`
https://github.com/Kurento/bugtracker/issues/362
https://github.com/OpenSOC/opensoc-ui/issues/23

My best guess is that there's an issue with xcode and node-gyp. Can you try troubleshooting with this?
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#the-acid-test

Still failing? Then this is the ultimate brute force reset: 
https://github.com/nodejs/node-gyp/issues/1861#issuecomment-547679016

**Comment by EdmarPereira** [comment]
For python --> 2.7.16
For xCode --> 11.4
Build version 11E146

and also follow the instructions:
```
I run sudo rm -rf /Library/Developer/CommandLineTools
and then xcode-select --install
```

But without success the error persists.

**Comment by chokladmal** [comment]
I've been struggling with this problem as well. After debugging I got to createStageDmg (https://github.com/electron-userland/electron-builder/blob/0dec1b8c198f1f9ca0124649883945ba561d11d3/packages/dmg-builder/src/dmg.ts#L194) where hdiutil seems to be failing randomly.

I still haven't figured out the root cause but by simply repeating that line, spawning hdiutil, until it it returns with a successful status code (for me it usually takes two or three attempts) the entire chain starts working. My quick and dirty hack solves my immediate problem of not being able to build my application but of course I'd like to get to the bottom of what is actually causing this.

**Comment by EdmarPereira** [comment]
484 / 5000
Resultados de tradução
I really don't know what to do, as I mentioned above I had a problem generating a build for the Mac on the day of the application release. We are about to lose the project because we cannot trust when the module will work, I have already done almost 20 builds without success, sometimes I can create the build the second time. I am working on this project that I created from the beginning a year ago and now I am no longer able to deliver the project ready to the client because we do several builds.

**Comment by chokladmal** [comment]
I just pushed the workaround I've tried here https://github.com/electron-userland/electron-builder/compare/master...chokladmal:workaround-for-hdiutil-failing
Perhaps you could try it out? I wish I had the answer to why it's failing but right now this is what is saving me.

**Comment by chokladmal** [comment]
Would something like that be accepted for merging until a better solution can be found?

**Comment by EdmarPereira** [comment]
How can I use this ? Just update the latest version of electron-builder and it will be there ?

**Comment by mmaietta** [comment]
@EdmarPereira you can use [patch-package](https://www.npmjs.com/package/patch-package) to get it working in your current repo without waiting for a fix upstream to be applied.

@chokladmal can you add your mac build configuration? I'm curious what config your build is failing with. Can you describe/log what `imageArgs` it's failing with? Perhaps add a console log in the npm module code?
I recall hitting an issue during `hdiutil unmount` a volume back when I didn't have electron-builder, it needed a few seconds delay in order for MacOS to deem it as no longer being used.

**Comment by chokladmal** [comment]
macOS Catalina, version 10.15.7
Python 2.7.16
Xcode 12.1, Build version 12A7403
macOS_Catalina_acid_test.sh returns `Command Line Tools not found`

Relevant logs:
` * spawning        command=hdiutil create -srcfolder /Users/myuser/projects/myapp/dist/mac/MyApp.app -volname MyApp 0.8.2 -anyowners -nospotlight -format UDRW -quiet -fs HFS+ -fsargs -c c=64,a=16,e=16 /private/var/folders/y6/qfhlwpld35q1gvpm6qm1j5580000gr/T/t-4w7RLH/0.dmg`
`  • exited          command=hdiutil code=1 pid=2736`
`  • hdiutil create failed  error=Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE`

Setting a breakpoint in handleProcess gives nothing more than the log: exit code 1 and no output on stdout or stderr (empty strings).

I've tried various things to try to figure out what is going on, including creating the full path to where the dmg would be created prior to spawning hdiutil and "sleeping" for a few seconds before spawning in case of race condition. No luck in finding any leads so far.

I will keep investigating and also check with my other team members if they can spot anything else. Not too long ago this used to work so I hope I can find a machine where it still builds and do some comparisons.

**Comment by chokladmal** [comment]
And the obvious thing that I should have tried from the beginning: running hdiutil with -debug

@EdmarPereira Looks like it might be related to what you had discovered before. The debug output reveals some unmounting problems:
```
detachTempimageFile: synchronous unmount /dev/disk3s1 returned 49168
```
and
```
2020-12-11 02:46:45.163 diskimages-helper[3922:2771162] detachTempImageFile: synchronous unmount /dev/disk3s1 [temp] returned 0x0000C010 (49168)
2020-12-11 02:46:45.165 diskimages-helper[3922:2771162] detachTempImageFile: synchronous eject /dev/disk3s1 [temp] returned 0x0000C010 (49168)
2020-12-11 02:46:45.165 diskimages-helper[3922:2771162] _detachTempImageFile: returning 49168
```
and finally
```
DIHLDiskImageCreate() returned 49168
hdiutil: create failed - Resource busy
```

**Comment by mmaietta** [comment]
Check your antivirus that's installed as it may be the blocker.  Half the time my builder fails when creating dmgs, even if signed. My Sophos Antivirus quarantines it lol

This may be a repeat of an old issue then: https://github.com/electron-userland/electron-builder/issues/854#issuecomment-555297129

**Comment by chokladmal** [comment]
In this case it's unmounting as part of `hdiutil create` that fails so not sure if we can force it in any way. I will try to get my antivirus to not touch the file but being a company laptop that may turn out to be somewhat complicated. We'll see...

**Comment by EdmarPereira** [comment]
About the antivirus problems I am not using for generate the dmg.

**Comment by mmaietta** [comment]
Left a comment on the PR to tidy it up.

Regarding a proper solution, I noticed on the `hdiutil` man page that the `create` command has an `-attach` option.
> -attach
attach the image after creating it.  If no filesystem is specified via -fs, the attach will fail per the default attach -mount required behavior.

I'm not able to repro this problem locally, so I'm wondering if you could test this approach of using `hdiutil create -attach -debug <imageArgs>` and see if it still fails.
If it doesn't fail, then maybe we just need to split "create" into steps and the 2nd (delayed) step be an explicit `hdiutil detach <pathToVolume>`

**Comment by lutzroeder** [comment]
Can you run:
 1. `export DEBUG=true`
 2. `npx electron-builder --mac --publish never`

This should print a more specific error message. 

See #5465

**Comment by chokladmal** [comment]
I've been context switching a bit working on other things but I will get
back to this soon. I've also asked some other team members to help out
looking at this.

Den tors 17 dec. 2020 04:06Lutz Roeder <notifications@github.com> skrev:

**Comment by chokladmal** [comment]
I've done some tests on the suggested -attach arg and it looks promising. With that arg it seems to succeed every time (at least the few times I've tried). Next step is to actually unmount it. When running hdiutil unmoun separately I'm getting:
```
hdiutil: unmount: "/private/var/folders/y6/qfhlwpld35q1gvpm6qm1j5580000gr/T/t-xz5mms/0.dmg" failed to unmount due to error 49168.
hdiutil: unmount: result: 49168
hdiutil: unmount failed - Resource busy
```

**Comment by mmaietta** [comment]
Can you please try `detach` instead of `unmount`?
> You need to always detach the disk image -- unmounting it unmounts the filesystem, but leaves disk image attached to a /dev/disk* entry, with a diskimages-helper process running to handle it. Note that hdiutil detach will take care of unmounting the volume for you (provided Disk Arbitration is running), so you can just skip the unmount step.

Ref: https://stackoverflow.com/a/4047528

**Comment by lutzroeder** [comment]
`ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` is a generic error. It would be helpful to see the actual error from `hdiutil` which should be written to console when running with `export DEBUG_DMG=true`. Do we understand the underlying issue down to running the `hdiutil` command that is failing in isolation and why it is failing?

**Comment by chokladmal** [comment]
I'm afraid I'll have to take back my previous happy comment about -attach. I'm back to getting the same error again. :(

**Comment by chokladmal** [comment]
> `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` is a generic error. It would be helpful to see the actual error from `hdiutil` which should be written to console when running with `export DEBUG_DMG=true`. Do we understand the underlying issue down to running the `hdiutil` command in isolation and why it is failing?

We know that "hdiutil create", when it fails, always fail due to failing to unmount (resource busy). Why that is is hard to say though. Could perhaps be antivirus or something else touching the files while the volume is mounted.

I've tried running it in isolation quite a few times now with about the same result: it sometimes succeeds and sometimes fail. The success-error ratio seems to be much better though with failures happening less than half the time.

**Comment by lutzroeder** [comment]
@chokladmal thank you for the additional info. There is another `hdiutil` related issue added in 22.10.3 which repros reliably and is different. See #5488.

**Comment by TongDaDa** [comment]
This may be a PROBLEM of BigSur system.

Adding the DEBUG_DMG=true env to the process could check out the ERROR.

In my case, the outputted ERROR was **Operation not permitted** when `hdiutil create` which is first step for creating dmg file. 

SOLUTION: removing [this line](https://github.com/chokladmal/electron-builder/blob/5788231abf0b5a70e15fa8b63beaab172a6e2231/packages/dmg-builder/src/dmg.ts#L192) will always works well.

**Comment by lutzroeder** [comment]
See #5322. Root cause is often copying an `.app` that contains incorrectly signed files to the DMG file.

**Comment by EdmarPereira** [comment]
Hey all, 
yesterday I did some tests and running this command `sudo mdutil -a -i off` it works !!!

**Comment by rizwan92** [comment]
just kill terminal and start fresh one i am sure it will work

**Comment by mmaietta** [comment]
Nice finds @TongDaDa ! 

Curious, can you try commenting out just the args section (` "-fsargs", "-c c=64,a=16,e=16"`) and still force `imageArgs.push("-fs", "HFS+")`? I'm wondering if suppressing the journal is the culprit.
> Suppressing the journal with -fs HFS+ and passing argu-
ments such as -c c=64,a=16,e=16 to -fsargs will min-
imize gaps at the front of the filesystem, allowing
resize to squeeze more space from the filesystem.
https://ss64.com/osx/hdiutil.html

Side note, do you know what filesystem type that `hdiutil` uses as its default on Big Sur?
I'm wondering when it'll be time to update the filesystem that the EB images are created with. APFS is backward compatible to 2016.

**Comment by Suhail** [comment]
> sudo mdutil -a -i off

For those wondering what this does: https://ss64.com/osx/mdutil.html

![image](https://user-images.githubusercontent.com/66225/108895074-f720dd80-75c7-11eb-96f9-17dba2089d0b.png)

**Comment by EdmarPereira** [comment]
Tested with the latest version 22.10.5, and it works !!!
https://github.com/electron-userland/electron-builder/releases/tag/v22.10.5

**Comment by mmaietta** [comment]
Closing per comment above 🙂

**Comment by StupidRepo** [comment]
> Since updating to Big Sur 11.3.1 I am receiving this same error message and I am unable to build a dmg file.
> 
> Xcode: Version 12.5 (12E262)
> Python: 2.7.16
> electron: "~11.4.5"
> electron-builder: "^22.11.1"

Try `sudo rm -rf /Library/Developer/CommandLineTools && xcode-select --install`

**Comment by StupidRepo** [comment]
Edit: Don't package as DMG, just use the .app file itself and get a separate app for dmg building.

**Comment by nazamov** [comment]
I had same problem. Give all permissions to terminal and IDE in mac settings. 
<img width="756" alt="Screenshot 2022-03-09 at 19 44 32" src="https://user-images.githubusercontent.com/34660427/157464731-05612581-3c36-4da2-a9cf-ffdb86678ae6.png">

**Comment by waabid** [comment]
Unfortunately, I'm still seeing this issue. I've tried disabling spotlight and giving terminal permissions possible.

MacOS: 12.3/12.3.1
electron-builder: 22.14.13
Intel Mac

**Comment by louismorgner** [comment]
Also getting this error. Perhaps interesting: the build works without any problems if no signing certificates are added to the keychain. Once I add them, this issues appears. Maybe helps someone debugging. Any hints?

**Comment by yaddran** [comment]
On Ventura 13.0.1 managed to solve it by allowing application (in my case the terminal I was using to run the build) to update or delete other applications. It is in Privacy & Security -> App Management.
<img width="492" alt="Screenshot 2022-11-11 at 21 49 08" src="https://user-images.githubusercontent.com/5527565/201428615-43053f3a-d63b-4eb4-8b06-27a3cfc91f3d.png">

**Comment by michaelwbarry** [comment]
> On Ventura 13.0.1 managed to solve it by allowing application (in my case the terminal I was using to run the build) to update or delete other applications. It is in Privacy & Security -> App Management. <img alt="Screenshot 2022-11-11 at 21 49 08" width="492" src="https://user-images.githubusercontent.com/5527565/201428615-43053f3a-d63b-4eb4-8b06-27a3cfc91f3d.png">

This worked for me, thanks.

**Comment by asajadian** [comment]
I'm having this issue too, tried all suggestions mentioned above but none helped.
The first time I tried building, everything went smoothly and I got all the output formats.
Strange that it worked the first time but not anymore. I also tried wiping the `node_modules` and `dist` folders but no luck.

**Comment by SpektacleFR** [comment]
> On Ventura 13.0.1 managed to solve it by allowing application (in my case the terminal I was using to run the build) to update or delete other applications. It is in Privacy & Security -> App Management. <img alt="Screenshot 2022-11-11 at 21 49 08" width="492" src="https://user-images.githubusercontent.com/5527565/201428615-43053f3a-d63b-4eb4-8b06-27a3cfc91f3d.png">
> 
> I would suggest the Full Disc Access, as well, for Terminal.

Worked for me on ver. 23.6.0

Thanks for this.

**Comment by direvus** [comment]
I'm getting this. MacOS 13.5.2, electron-react-boilerplate with electron-builder ^24.2.1.

`npm run package` shows the error in the title of this issue. Digging deeper with `export DEBUG_DMG=true`, I see:

```
                                                                                         detachTempimageFile: synchronous unmount /dev/disk3 returned 49168
retrying unmount (#1)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/ElectronReact 4.6.0 (/dev/disk3) returned 49168
retrying unmount (#2)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/ElectronReact 4.6.0 (/dev/disk3) returned 49168
retrying unmount (#3)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/ElectronReact 4.6.0 (/dev/disk3) returned 49168
2023-09-11 10:24:08.334 diskimages-helper[10884:99392] -processKernelRequest: flush received
2023-09-11 10:24:08.365 diskimages-helper[10884:99288] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
DIHLDiskImageCreate() returned 49168
hdiutil: create: returning 49168
hdiutil: create failed - Resource busy
```

Things I've tried:

* shutting down my dev instance of the app
* disabling real-time protection in Microsoft Defender
* adding an exclusion for my repo directory in Microsoft Defender
* granting Full Disk Access and App Management privileges to my terminal app (iTerm 2)
* restarting my terminal app
* disabling disk indexing with `sudo mdutil -a -i off`

Unlike some others in the thread, it doesn't seem to randomly work some of the time. So far all attempts have failed. I've never had a successful build.

**Comment by wangwei10** [comment]
我也遇到了
ExecError: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/estar/Desktop/HiGo-APP-PC/node_modules/builder-util/src/util.ts:250:14) 证书签名都是正常的 修改版本号重新打包可以成功 但是如果想打包第二次就会报这个错 十分的郁闷 有没有大佬解答一下

**Comment by mameier** [comment]
I recently ran again into this error.  
This time, a new security setting of macOS was the reason:
In
* Privacy and Security
* App Management

I had to grant the right to 'Allow apps to update or delete other apps on your Mac.' to my terminal or IDE.
