### ISSUE TITLE
Run packaged electron application in sudo linux

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#5433]
* **Version**: 22.3.6

* **Electron Version**:v8.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux

I want to package my application so it runs with SUDO privileges in Linux. For windows requestedExecutionLevel is required but is there any such parameter that I need to include in Linux build to do so?

**Comment by MD-AZMAL** [comment]
anybody found any workaround?

**Comment by SwapnilSoni1999** [comment]
> anybody found any workaround?

I guess nobody did

**Comment by freddy-daniel** [comment]
Needed
