### ISSUE TITLE
Target "msi" custom NSIS script

### ISSUE THREAD

**Issue by TorbusMateusz** [electron-userland/electron-builder#5435]
* **Version**:  22.9.1

* **Electron Version**: 9.0.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows - msi

I noticed problem when I wanted to create MSI installer. I included custom `"include": "build/installer.nsh"` script with code:
```
!macro preInit
  Exec 'taskkill /im "process_name.exe" /f'
  MessageBox MB_OK "simple message box"
!macroend
```
None of above commands execute. There were no errors during building project. I check if changing target from `"msi"` to `"nsis"` could help and every command from script run perfectly.

Second Issue is when upgrade or delete app built into msi file, popup appears which inform user about currently running app and installer is not able to close application. Changing target  from `"msi"` to `"nsis"` resolve problem as in previous case.

I'm stuck with this problem. Maybe I miss something in config. Has someone got similar issue or have knowledge how to resole it?

**Comment by bodyahnedko** [comment]
Hi. Have you resolved this issue related to `msi` build?

**Comment by bodyahnedko** [comment]
> * **Version**:  22.9.1
> 
> * **Electron Version**: 9.0.5
> * **Electron Type (current, beta, nightly)**: current
> 
> * **Target**: Windows - msi
> 
> I noticed problem when I wanted to create MSI installer. I included custom `"include": "build/installer.nsh"` script with code:
> 
> ```
> !macro preInit
>   Exec 'taskkill /im "process_name.exe" /f'
>   MessageBox MB_OK "simple message box"
> !macroend
> ```
> 
> None of above commands execute. There were no errors during building project. I check if changing target from `"msi"` to `"nsis"` could help and every command from script run perfectly.
> 
> Second Issue is when upgrade or delete app built into msi file, popup appears which inform user about currently running app and installer is not able to close application. Changing target from `"msi"` to `"nsis"` resolve problem as in previous case.
> 
> I'm stuck with this problem. Maybe I miss something in config. Has someone got similar issue or have knowledge how to resole it?

Hi. Have you resolved this issue related to msi build?

**Comment by bartosz-fpwd** [comment]
Hi, @ghost have you resolved this issue?
