### ISSUE TITLE
Windows Server - Renderer process broken for requireAdministrator

### ISSUE THREAD

**Issue by VisiontechGitHub** [electron-userland/electron-builder#5439]
* **Version**: 22.9.1

* **Electron Version**: 11.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32 x64

If requestedExecutionLevel: "requireAdministrator" is used in electron builder config OR Administrator account is used to run the Electron application via compatibility tab, bad things happen : 
- gpu-process won't start
- ctrl+shift+i won't open developer tools

You can reproduce the issue using the attached test application (it's just the hello world example from the electron starting guide) : 

[test.zip](https://github.com/electron-userland/electron-builder/files/5597966/test.zip)

I reproduced this on Windows Server 2012 - 2016 and 2019 so far using current and older versions of electron (still can't find a working one). You can run a virtualized (with Hyper-V) Windows Server using ISO from : 

https://www.microsoft.com/it-it/evalcenter/evaluate-hyper-v-server-2019

If Administrator is not used everything works : 

![image](https://user-images.githubusercontent.com/41678158/100254490-ab1bb980-2f42-11eb-821c-084e8f41cea6.png)

If you set "Run this program as Administrator" in compatibility tab of the shortcut or requestedExecutionLevel: "requireAdministrator" in config then it's broken (as you can see only white screen is shown, no errors in console remotely debugging) :

![image](https://user-images.githubusercontent.com/41678158/100254716-f2a24580-2f42-11eb-9cae-70e0dc09c780.png)

If you right click the link and "Run as Administrator" (without using the compatibility tab checkbox) then it works correctly:

![image](https://user-images.githubusercontent.com/41678158/100255755-38134280-2f44-11eb-803e-29a3174b4a9c.png)

Further tests : 

If I try to elevate from a non Administrator account using Administrator credentials the same issue applies.
If I create a second Administrator account, copy every privileges to such account, everything works as normal runnig this 'administrator account' (elevating, running as etcetc).
Event logs shows no error.

**Comment by VisiontechGitHub** [comment]
I discovered this problem may be caused from Chromium itself.
I opened an issue for Chromium:

https://bugs.chromium.org/p/chromium/issues/detail?id=1153062

**Comment by Aoiujz** [comment]
Is there any solution to this problem now? I have the same problem.

**Comment by justdoit366** [comment]
I have the same problem, did you solve it?

**Comment by justdoit366** [comment]
> I discovered this problem may be caused by Chromium itself. I opened an issue for Chromium:
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1153062

This issue cannot be opened. Have you solved this problem?

**Comment by ScarboroughCoral** [comment]
Is there any solution to this problem now?

**Comment by matteocappello94** [comment]
Launching with `--in-process-gpu` resolve the problem on Windows Server for our project
