### ISSUE TITLE
NSIS Shown before Centered

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#544]
* **Version**: 5.9.0

* **Target**: Win

Installer window is shown in uninitialized state (not yet showing icon, or text), and the window itself is not centered. Few ms later it is centered and text added. This goes very fast, but is still jarring. Better to only show after it is centered (if you can control it).

**Comment by develar** [comment]
Is it reproducible for you now?

**Comment by atypicalprogrammer** [comment]
Same for me, see steps here (in reverse order)

https://postimg.org/gallery/lsnn0c3c/54667fc9/

First transparent window, then larger window, then larger window resizes, finally text shows and icon.

**Comment by develar** [comment]
@atypicalprogrammer Is your computer slow? Or not?

**Comment by atypicalprogrammer** [comment]
Not particularly, but it is a VM.

**Comment by develar** [comment]
It is how SpiderPlugin works. I suppose on fast, normal user machine (cannot reproduce in my VM (Parallels, of course, I don't use windows and also use VM to test)). Help wanted :( Currently, no priority to fix it.
