### ISSUE TITLE
Update documentation about generic publish settings

### ISSUE THREAD

**Issue by archfz** [electron-userland/electron-builder#5442]
As I understand from https://github.com/electron-userland/electron-builder/issues/2170 the generic provider will never publish and one must implement their own publishing mechanism. This should be specified in the documentation.

**Comment by mspoerer** [comment]
Def. appreciated! It took me almost a day to figure out, that there is no generic provider and that the documentation is at least 3 years out-dated... 
https://github.com/electron-userland/electron-builder/blob/5d01ea6dc9daec4639ab54b38520b93833ac81d3/packages/app-builder-lib/src/publish/PublishManager.ts#L130

**Comment by 1111mp** [comment]
So how to implement a publishing server

**Comment by mspoerer** [comment]
@1111mp Right now we are publishing the following files ( .dmg, .exe, .zip, latest-mac.yml & latest.yml ) to a simple web server (nginx), with restricted access rights.

**Comment by 1111mp** [comment]
@mspoerer 
thank you very much
