### ISSUE TITLE
"node_modules" is not be packed into app.asar

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [electron-userland/electron-builder#5447]
* **Version**: 22.2.0
* **Electron Version**: 9.0.0
* **Target**: macOS

The bundled folder after build:
```
bundled
 ├── background.js
 ├── package.json
 ├── preload.js
 ├── sites.js
 ├── logo.png
 ├── index.html
 ├── node_modules
 └── js
```
![Xnip2020-11-29_16-39-44](https://user-images.githubusercontent.com/15119304/100537230-82a4ff80-3261-11eb-86c4-be56c3810cfd.png)

The app.asar:
```
app
 ├── background.js
 ├── package.json
 ├── preload.js
 ├── sites.js
 ├── logo.png
 ├── index.html
 └── js
```
![uTools_1606639130312](https://user-images.githubusercontent.com/15119304/100537208-61441380-3261-11eb-9e93-b05f8eec949f.png)

My options:
```
{
    "appId": "com.lanyuanxiaoyao.searchx",
    "files": [
        "**/*",
        "**/node_modules/*"
    ]
}
```

Only the "node_modules" folder is missed.

**Comment by lanyuanxiaoyao** [comment]
This is work for me:
```
{
    "files": [
        "**/*",
        {
            "from": "node_modules",
            "to": "node_modules",
            "filter": [
                "**/*"
            ]
        }
    ]
}
```
But why?

**Comment by cliqer** [comment]
Are you using `beforeBuild` inside package.json?
