### ISSUE TITLE
Ignore .DS_Store Files

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#545]
* **Version**: 5.1.0

* **Target**: Any

I get some complaints from users that .DS_Store files are in the repo's. Is it possible to ignore these files and not add them somehow? Or is that my responsibility?

**Comment by develar** [comment]
We don't pack dot files by default. Do you see such files in the your `app.asar`?

**Comment by kunkinkan** [comment]
I presume it comes from the resources folder.

**Comment by develar** [comment]
So, do you see see such files in the your app.asar? Or where?

**Comment by kunkinkan** [comment]
I mean the extraResources specified in package.json.

**Comment by develar** [comment]
How did you specify pattern? Just `foo` instead of `foo/**/*` ?

**Comment by kunkinkan** [comment]
Just `foo`

**Comment by develar** [comment]
Well, specify as `foo/**/*` ;) Does it help?

**Comment by kunkinkan** [comment]
hmm i don't understand that pattern? Why two subfolders deep as that? But ok, will try.

**Comment by kunkinkan** [comment]
OK this pattern seems to fix it, why does this work?  :-)
