### ISSUE TITLE
NSIS uninstall script does not clean up all files if the application is running ?

### ISSUE THREAD

**Issue by kennyyen** [electron-userland/electron-builder#5458]
* **Version**: 21.2.0

* **Electron Version**: 7.3.3

* **Target**: I want to have the uninstall clean up the installation directory and the Registry, 
While running the uninstall/install script when the application is running.

The Detail setup of my nsis is as below
```
    "nsis": {
      "oneClick": true,
      "perMachine": true,
      "license": "script/build/license.rtf",
      "createStartMenuShortcut": true,
      "menuCategory": true,
      "uninstallDisplayName": "My Application"
    }
```
My steps:
- build the .msi installer
- install the application, then have the application open and running
- then run the uninstaller/installer .msi
- 'Are you sure you want to uninstall My Application ?', click OK
- 'My Application is running. Click OK to close it.', click OK
- Check my Installation Directory, 'My Application.exe' still exist, and some other files are also left over as well

I checked that the 
`electron-builder/node_modules/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
`
line 38 `_CHECK_APP_RUNNING` should handle the process detecting and killing the running application

And, `electron-builder/node_modules/app-builder-lib/templates/nsis/uninstaller.nsh`
line 60 `RMDir /r $INSTDIR` should deal with removing the installation directory properly.
But apparently it was not able to do so.

Does any one know what's going on here, or having to encounter the same issue, or have an ideal to fix this issue ?

**Comment by SnehalJ1509** [comment]
@kennyyen May be [this solution](https://github.com/electron/windows-installer/issues/113#issuecomment-705517313) could help? I too had similar issue and it helped me for Windows app but didn't find anything similar for MacOS.

**Comment by SnehalJ1509** [comment]
@kennyyen May be [this solution](https://github.com/electron/windows-installer/issues/113#issuecomment-705517313) could help? I too had similar issue and it helped me for Windows app but didn't find anything similar for MacOS.

**Comment by kennyyen** [comment]
> 
> 
> @kennyyen May be [this solution](https://github.com/electron/windows-installer/issues/113#issuecomment-705517313) could help? I too had similar issue and it helped me for Windows app but didn't find anything similar for MacOS.

Hey SnehalJ thanks so much for the reply, i ended up having to add custom script 
with a longer delay before removing the Installation Directory
as below :
`
!macro customRemoveFiles
    Sleep 3000
    RMDir /r $INSTDIR
!macroend
`
