### ISSUE TITLE
NSIS Windows XP 32-bit

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#546]
* **Version**: Latest

* **Target**: NSIS

I'm building both 32 and 64-bit in a single installer. Works fine on windows 7 32-bit and on windows 7 64-bit. However, on windows xp 32-bit I get the error "App Name.exe is not a valid Win32 application." (Installation itself works fine, it's after opening the installed app that the error shows).

**Comment by develar** [comment]
windows xp is not supported. Is it really needed?

**Comment by kunkinkan** [comment]
Would be nice I guess, but not the highest priority :-)

**Comment by bontibon** [comment]
@kunkinkan @develar means that electron isn't even support on Windows XP, so why do you need an installer for it?

**Comment by kunkinkan** [comment]
Oh, lol, then obviously not :) Did not check electron requirements.

**Comment by develar** [comment]
https://github.com/electron/electron/issues/691#issuecomment-83776821

**Comment by develar** [comment]
Fixed — NSIS installer checks "at least windows 7" and user get clear error message.
