### ISSUE TITLE
Big Sur: "hdiutil: unflatten: verb not recognized" when adding license

### ISSUE THREAD

**Issue by Slidemagic** [electron-userland/electron-builder#5462]
* **Version**: 22.9.1

* **Electron Version**:11.04
* **Electron Type (current, beta, nightly)**:current

* **Target**: MacOS DMG

Big Sur 11.0.1
Xcode 12.2
Node 14:15.1
npm 6.14.8

Attaching a software license creates the following error in the build:
⨯ Exit code: 1. Command failed: hdiutil unflatten *****.dmg hdiutil: unflatten: verb not recognized

Apparently, Apple removed hdiutil flatten/unflatten in Big Sur https://github.com/electron-userland/electron-builder/issues/5392#issuecomment-733163827

**Comment by mmaietta** [comment]
This might be a duplicate of https://github.com/electron-userland/electron-builder/pull/5424

**Comment by Slidemagic** [comment]
Closing, a duplicate of https://github.com/electron-userland/electron-builder/pull/5424
