### ISSUE TITLE
Operation not permitted during dmg building on macOS 11 Big Sur

### ISSUE THREAD

**Issue by gnattu** [electron-userland/electron-builder#5465]
* **Version**: electron-builder@22.9.1

* **Electron Version**:electron@11.0.4
* **Electron Type (current, beta, nightly)**:current

* **Electron updater:**  electron-updater@4.3.1

* **Target**: `dmg` for macOS

After setting `DEBUG=electron-builder DEBUG_DMG=true`, the console logs error during copy:

```
2020-12-10 11:45:43.585 copy-helper[54295:350710] About to copy "/path/app.app".
2020-12-10 11:45:44.255 copy-helper[54295:350710] copy error (canceling): /Volumes/img/app.app/Contents/Resources/app.asar.unpacked/node_modules/npm/node_modules/libnpmorg/.BC.T_K9LSTf: Operation not permitted
2020-12-10 11:45:44.255 copy-helper[54295:350710] Copy finished with error 1 (Operation not permitted).
................................Error 1 (Operation not permitted).
could not access /Volumes/img/app.app/Contents/Resources/app.asar.unpacked/node_modules/npm/node_modules/libnpmorg/.BC.T_K9LSTf - Operation not permitted
```

Then building ultimately failed with:

```
2020-12-10 11:45:45.386 diskimages-helper[54280:350655] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
DIHLDiskImageCreate() returned 1
hdiutil: create: returning 1
hdiutil: create failed - Operation not permitted

...

 ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                    Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                        at ChildProcess.<anonymous> (/Users/gnattu/src/poi/node_modules/builder-util/src/util.ts:243:14)
                                                                        at Object.onceWrapper (node:events:483:26)
                                                                        at ChildProcess.emit (node:events:376:20)
                                                                        at maybeClose (node:internal/child_process:1063:16)
                                                                        at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
```

I can create an image with [appdmg](https://github.com/LinusU/node-appdmg) for the same app.

**Comment by gnattu** [comment]
By removing "-fs", "HFS+", "-fsargs", "-c c=64,a=16,e=16", dmg creation does work on Big Sur. Looks like HFS+ image creation is broken.

**Comment by mmaietta** [comment]
Copying from the other issue for posterity's sake.
> [This] seems to just need a one-liner PR change, but I don't think letting it use the default setting will be backward compatible as APFS is only available High Sierra 10.13+. It would also require verifying that the default value is consistent across all recent OS versions, so an explicit `-fs` arg might still be necessary.

Also, from a quick search for hdiutil returning error code 1, it might be due to the target file/directory path not existing.
Check out these two related to dmg creation, coincidentally from `appdmg`.
https://github.com/LinusU/node-appdmg/issues/65
https://github.com/LinusU/node-appdmg/issues/63#issuecomment-112512777
```
{ [Error: Error running `hdiutil`! Exit code was 1]
  exitCode: 1,
  stdout: 'Preparing imaging engine…\nReading Protective Master Boot Record (MBR : 0)…\n',
  stderr: '\nhdiutil: convert failed - Invalid argument\n' }
```

**Comment by lutzroeder** [comment]
@gnattu can you check the folder for any files with extended attributes (using `xattr`).

**Comment by gnattu** [comment]
@lutzroeder Yes, I can confirm that some files are incorrectly signed:

```
xattr PULL_REQUEST_TEMPLATE 
com.apple.cs.CodeDirectory
com.apple.cs.CodeEntitlements
com.apple.cs.CodeRequirements
com.apple.cs.CodeRequirements-1
com.apple.cs.CodeSignature
```

The file is just a text file indicating a PR template, but it is detected as a binary and got signed.

**Comment by lutzroeder** [comment]
@gnattu double-checking, are you using electron-builder@22.9.1 or electron-builder@22.10.3 and macOS BigSur? What is the name and extension of the file that got misclassified?

**Comment by gnattu** [comment]
It's electron-builder@22.9.1. The file has no extension at all, like `PULL_REQUEST_TEMPLATE`.

**Comment by gnattu** [comment]
For my case we need more than a revert as upstream detects files with an emoji as binary: gjtorikian/isBinaryFile#22

And npm's `PULL_REQUEST_TEMPLATE` does contain emoji, so `PULL_REQUEST_TEMPLATE` will still get signed after the revert. 

Maybe add a case to ignore `PULL_REQUEST_TEMPLATE`:

```js
if (path.basename(filePath)[0] !== '.' && path.basename(filePath) != 'PULL_REQUEST_TEMPLATE') {

```

As a workaround?

**Comment by mmaietta** [comment]
As opposed to using a specific name-based check, can we use another comparable package that is designed for binary detection? Such as: https://www.npmjs.com/package/file-type

@gnattu Is there a minimum/sample repo where I can easily repro/test this on?

**Comment by gnattu** [comment]
@mmaietta You can use the [electron-quick-start](https://github.com/electron/electron-quick-start).

Then add some dependencies inlcuding emoji text files to `package.json`. For example, `npm`.

Then run electron-builder after `npm i`, you will get the error.

**Comment by mmaietta** [comment]
@gnattu I've tried as you described and, unfortunately, I can't repro locally on both Big Sur or Catalina. No app.asar.unpacked is created. Running with `DEBUG=electron-osx-sign npx electron-builder --dir` doesn't show the file(s) being signed either.
What's your EB `build` config?
If you can create a sample repo or patch file(s) for me to apply the changes locally, it'd help a bunch.

Since I cant test atm, my suggestion for the interim is to flip the binary validation to no longer just check extensions and try `istextorbinary`:
```
import { isText, isBinary, getEncoding } from 'istextorbinary'

isBinary(aFilename, aBuffer) // returns true if a binary file otherwise false, checks filename then buffer
```
The quickest swap would probably just be to use `isBinary(filePath, null)` for the current extension-check functionality. Best usage of the package would be to include the Buffer for it to check 24 bytes from start/middle/end.
Can you try that out?

**Comment by gnattu** [comment]
I'm not using build config, which will load the default one I guess.

The package.json looks like below:

```json
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder -p never"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "dependencies": {
    "npm": "^6.14.8"
  },
  "devDependencies": {
    "electron": "^11.1.0",
    "electron-builder": "^22.10.3"
  }
}
```

**Comment by gnattu** [comment]
By the way, I do have code signing using npx as well:

```
  electron-osx-sign Signing... /Users/gnattu/src/electron-quick-start/dist/mac-arm64/electron-quick-start.app/Contents/Resources/app.asar.unpacked/node_modules/npm/node_modules/libnpmaccess/PULL_REQUEST_TEMPLATE +143ms
```

**Comment by gnattu** [comment]
@mmaietta I tried `istextorbinary ` and it does not work the same way as `isBinaryFile`. It will only perform extension check for filenames, and we have to provide buffer for content encoding checking ourselves.

`istextorbinary`'s `isBinary`  does return `false` for files contain emoji.

**Comment by mmaietta** [comment]
I was able to get it working in my limited local testing. Would you mind giving this branch a try?
https://github.com/mmaietta/electron-builder/tree/fix/BinaryDetectionSigning

**Comment by gnattu** [comment]
@mmaietta the branch is not runnable for my project:

```
getFilePathIfBinaryAsync is not defined  stackTrace
```

https://github.com/mmaietta/electron-builder/blob/f8bc3ec31c905ec019f6f0c2b9b14d4a7d7c5237/packages/app-builder-lib/electron-osx-sign/util.js#L204 should be changed as well to `getFilePathIfBinarySync`.

But after manually editing, the build still fails as the `icns` icon files get signed incorrectly, we should not drop the extension check as the extension check provided in `istextorbinary` is not good enough.

**Comment by mmaietta** [comment]
Sorry bout that. I've pushed an update to the branch, consolidated more of the logic within the binary check function. This also propagates the improvements to `unpackDetector`

**Comment by gnattu** [comment]
Close as #5493 merged

**Comment by tmacwill** [comment]
I'm not sure the above PR fixes this issue in all cases. I'm using macOS Big Sur 11.1 on an Apple M1 chip in a Rosetta 2 terminal. I've create a minimal repro case with `electron-builder 22.10.4` at this repository, using the macOS JDK as a test: https://github.com/tmacwill/electron-builder-dmg-repro

When I run `yarn dist`, I get the following error:

```
  • signing         file=dist/mac/electron-webpack-quick-start.app identityName=Developer ID Application: xxx identityHash=xxx provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/electron-webpack-quick-start-0.0.0-mac.zip
  • building        target=DMG arch=x64 file=dist/electron-webpack-quick-start-0.0.0.dmg
  • building embedded block map  file=dist/electron-webpack-quick-start-0.0.0-mac.zip
  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                    Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                        at ChildProcess.<anonymous> (/Users/tmac/tmp/electron-webpack-quick-start/node_modules/builder-util/src/util.ts:243:14)
                                                                        at Object.onceWrapper (events.js:421:26)
                                                                        at ChildProcess.emit (events.js:314:20)
                                                                        at maybeClose (internal/child_process.js:1021:16)
                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Using `xattr` in the `dist` directory shows that several files have extended attributes:

```
$ xattr dist/mac/electron-webpack-quick-start.app/Contents/Resources/static/jdk/lib/modules
com.apple.cs.CodeDirectory
com.apple.cs.CodeEntitlements
com.apple.cs.CodeRequirements
com.apple.cs.CodeRequirements-1
com.apple.cs.CodeSignature

$ xattr dist/mac/electron-webpack-quick-start.app/Contents/Resources/static/jdk/lib/security/cacerts
com.apple.cs.CodeDirectory
com.apple.cs.CodeEntitlements
com.apple.cs.CodeRequirements
com.apple.cs.CodeRequirements-1
com.apple.cs.CodeSignature
```

However, they don't have extended attributes before the build:

```
$ xattr static/jdk/lib/modules
$ xattr static/jdk/lib/security/cacerts
$
```

If you remove the files that are getting extended attributes added and then run `yarn dist`, the build succeeds:

```
$ rm -rf static/jdk/lib/modules static/jdk/lib/security/cacerts
$ yarn dist
```

The `static/jdk` directory also contains a number of binary files that are not given extended attributes after building. For instance, `static/jdk/bin/java` is a binary file, but it's not given extended attributes in `dist`:

```
$ xattr dist/mac/electron-webpack-quick-start.app/Contents/Resources/static/jdk/bin/java
$
```

Thanks!

**Comment by mmaietta** [comment]
> Is there ever a case where a non-executable binary file that doesn't pass the existing checks (e.g., ends in dylib) should be code signed? If not, then getFilePathIfBinarySync could also check for fs.accessSync(filePath, fs.constants.X_OK).

Honestly, I'm not sure. It seems electron-builder and electron-osx-sign both have similar odd issues in discerning binaries and the core issue is not particularly fixable with ease. 

Happy to run any tests/suggestions for you though. I tried your `fs.access` and receive this error in my testing:

```
fs.accessSync(filePath, fs.constants.F_OK) && fs.accessSync(filePath, fs.constants.X_OK)


⨯ EACCES: permission denied, access '/electron-builder-dmg-repro/dist/mac/electron-webpack-quick-start.app/Contents/Info.plist' 
stackTrace=
Error: EACCES: permission denied, access '/electron-builder-dmg-repro/dist/mac/electron-webpack-quick-start.app/Contents/Info.plist'
    at Object.accessSync (fs.js:203:3)
    at module.exports.getFilePathIfBinarySync (/electron-builder-dmg-repro/.yalc/app-builder-lib/electron-osx-sign/util.js:162:10)
```

I found another npm package, https://github.com/mscdex/mmmagic, that could potentially help here, but it's a native module. Not sure if that's too heavy of a package to introduce into this tool, but right now I can't even get it to rebuild with the right node version

**Comment by tmacwill** [comment]
Thanks for responding! I think that's actually the expected behavior of `fs.accessSync`--it throws an exception if the given permissions don't exist on the file (as opposed to returning `true` or `false`): https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode.

If we're not sure about which files should be signed vs. left unsigned, though, another potential option is to allow projects to specify an `exclude` list in the configuration or have a boolean option like `onlySignExecutables`.

I'm also happy to help test + submit a PR, but indeed wasn't sure how to get a dev environment set up :)

**Comment by mmaietta** [comment]
Okiedokie, two items to do!

### Optional signing

For specifically adding signing or ignoring files you can leverage either/both of these two EB features (`ignore` and `binaries`). This should be able to resolve the problem you're immediately facing right now.
- supplemental binaries: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141
- ignore function or regex: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/sign.js#L124-L131

### To setup a local dev environment

Original dev env setup can be found here: https://github.com/electron-userland/electron-builder/pull/5426#issue-522818144
Updated instructions are below:
> For local development, I used [yalc](https://github.com/whitecolor/yalc) so I could test changes with the electron-quick-start app
> Env setup from scratch (line by line for an easy copy-paste)
> 
> ```
> yarn global add yalc
> 
> git clone https://github.com/electron-builder/electron-builder.git
> git clone https://github.com/electron/electron-quick-start.git
> 
> cd electron-quick-start
> npm install && npm install -D electron-builder
> 
> # Setup link for yalc's local "repo"
> yalc link app-builder-lib builder-util builder-util-runtime dmg-builder electron-builder electron-publish electron-builder-squirrel-windows electron-forge-maker-appimage electron-forge-maker-nsis electron-forge-maker-nsis-web electron-forge-maker-snap electron-updater
>
> # Compile and store local "repo" of electron-builder
> pushd ../electron-builder
> yarn compile
> find packages/ -type d -maxdepth 1 -print0 | xargs -0 -L1 sh -c 'cd "$0" && yalc push'
> popd
> 
> yarn electron-builder --arm64 --x64
> ```
> 
> The magical script for whenever you make changes to electron-builder! Rebuilds electron-builder, patches the npm module in electron-quick-start, and begins packaging. Ready for copy-paste into terminal
> 
> ```
> pushd ../electron-builder
> yarn compile
> find packages/ -type d -maxdepth 1 -print0 | xargs -0 -L1 sh -c 'cd "$0" && yalc push'
> popd
> ```

**Comment by tmacwill** [comment]
Got it, thanks! Is there a way to specify `ignore` in the `package.json`? I see `binaries` listed on https://www.electron.build/configuration/mac.html, but not `ignore`. I tried adding `ignore` and got this error:

```
 - configuration.mac has an unknown property 'ignore'. These properties are valid:
   object { appId?, artifactName?, asar?, asarUnpack?, binaries?, bundleShortVersion?, bundleVersion?, category?, compression?, cscInstallerKeyPassword?, cscInstallerLink?, cscKeyPassword?, cscLink?, darkModeSupport?, detectUpdateChannel?, electronLanguages?, electronUpdaterCompatibility?, entitlements?, entitlementsInherit?, entitlementsLoginHelper?, extendInfo?, extraDistFiles?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, gatekeeperAssess?, generateUpdatesFilesForAllChannels?, hardenedRuntime?, helperBundleId?, helperEHBundleId?, helperGPUBundleId?, helperNPBundleId?, helperPluginBundleId?, helperRendererBundleId?, icon?, identity?, minimumSystemVersion?, protocols?, provisioningProfile?, publish?, releaseInfo?, requirements?, signIgnore?, strictVerify?, target?, type? }
```

Is there a different field I should be adding `ignore` to?

**Comment by mmaietta** [comment]
Haha, I just discovered that it's piped from elsewhere
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts#L212-L243

So _I think_ you'll need to use `signIgnore` and it's a string/regex array: `opts.signIgnore?.map(it => new RegExp(it))`

**Comment by tmacwill** [comment]
Ah got it, that worked for me! I added the two paths that were being incorrectly signed to `signIgnore`, and my DMG builds successfully now.

I think it'd be helpful to add documentation for `signIgnore` to https://www.electron.build/configuration/mac.html, since the combination of `signIgnore` and `binaries` can indeed fix any issues with electron-builder detecting / not detecting files to sign. (It might also be good not to sign non-executable binary files by default, though I'm not 100% sure what's best.)

Thanks for all of your help, I really appreciate it!

**Comment by ym13349140** [comment]
> Ah got it, that worked for me! I added the two paths that were being incorrectly signed to `signIgnore`, and my DMG builds successfully now.
> 
> I think it'd be helpful to add documentation for `signIgnore` to https://www.electron.build/configuration/mac.html, since the combination of `signIgnore` and `binaries` can indeed fix any issues with electron-builder detecting / not detecting files to sign. (It might also be good not to sign non-executable binary files by default, though I'm not 100% sure what's best.)
> 
> Thanks for all of your help, I really appreciate it!

Hello, I recently use `signIgnore`  to ignore some `.dll` files in my projects, these dll files are in `./dist_electron/mac/application/Contents` directory, I tried many times of different value , including `./dist_electron/mac/application/Contents/xxx.dll` , `.dll$` and array value '[`.dll$`]', but it never make sense, can you show me how you set this param value? I'd be really appreciate if you can reply me.

**Comment by xngln24** [comment]
this worked for me: [https://github.com/electron-userland/electron-builder/issues/5431#issuecomment-1566203180](url)

**Comment by xngln24** [comment]
Adding permissions in "App Management" to my IDE and Terminal worked for me. See: [https://github.com/electron-userland/electron-builder/issues/5431](url)
