### ISSUE TITLE
checkForUpdatesAndNotify() don't work with the file in S3

### ISSUE THREAD

**Issue by astrO1** [electron-userland/electron-builder#5470]
Hi guys,

I already made the publish on S3 using the default configuration from **S3 OPTION**, and the files appear on S3, but when my app from production start i execute this:

```
  win.once('ready-to-show', () => {
    autoUpdater.checkForUpdatesAndNotify();
  });

```
and on bottom 
```
autoUpdater.on('update-available', () => {
    win.webContents.send('update_available');
  });

  autoUpdater.on('update-downloaded', () => {
    win.webContents.send('update_downloaded');
  });

  ipcMain.on('restart_app', () => {
    autoUpdater.quitAndInstall();
  });

  ipcMain.on('app_version', (event) => {
    event.sender.send('app_version', { version: app.getVersion() });
  });
```

For testing purposes, I build a version to be updated to the highest version on S3, for example, local 8.2.0 on S3 8.3.0. And when the app starts, nothing is happening. I see a lot of tutorials that show the GITHUB or GITLAB release, I really need them?

Here is my code to detect.

```
      this.electronService.ipcRenderer.on('update_available', () => {
        this.electronService.ipcRenderer.removeAllListeners('update_available');
        this.showDownloadNotify = true;
      });

      this.electronService.ipcRenderer.on('update_downloaded', () => {
        this.electronService.ipcRenderer.removeAllListeners('update_downloaded');
        console.log('ENTROU NO UPDATE DOWNLOAD');
      });
```

**Comment by thegnuu** [comment]
Just an update, I was using electron `v12.0.0-beta.16` where I was not able to get things working reliably, I just tested with `v11.2.0` and everything works without any issues.
