### ISSUE TITLE
unable to install v22.10.1 on linux

### ISSUE THREAD

**Issue by vladimiry** [electron-userland/electron-builder#5474]
error dmg-license@1.0.8: The platform "linux" is incompatible with this module.
error Found incompatible module.

**Comment by mastergberry** [comment]
Same problem on Windows @develar 

Culprit is this commit: https://github.com/electron-userland/electron-builder/commit/9e7b3c39ad3c59b88d78e3f5a5948cf4ced3f92a#diff-659526d8e626d903a675df1daeb04c4e2a9abd7d7d9abb6b3237cdadf111b196

**Comment by develar** [comment]
`22.10.2` is released.
