### ISSUE TITLE
Auto update on linux changes file name to update.appimage

### ISSUE THREAD

**Issue by seenu-ssts** [electron-userland/electron-builder#5477]
* **Version**: 4.3.5

* **Electron Version**: 11.0.4

* **Electron Type (current, beta, nightly)**: current

* **Target**: AppImage

After auto-update on Linux changes the filename to update.appimage

**Comment by seenu-ssts** [comment]
Yes, it is relevant. After the auto-update of the application name changes to update.appimage on the Linux platform. Kindly help us with this to get is resolved as soon as possible. Thanks in advance

**Comment by zzxxiinn** [comment]
i still meet with it
- Version: 22.11.7
- Electron Version: 13.1.4
- Electron Type (current, beta, nightly): current
- Target: AppImage

**Comment by zzxxiinn** [comment]
still relevant

**Comment by marcuskirsch** [comment]
Still an issue. :(

**Comment by anas1412** [comment]
Workaround for anyone whose launcher or autostart breaks after the updater renames the AppImage to a new versioned filename: point the `.desktop` entry at a tiny wrapper that always runs the newest AppImage.

```sh
#!/bin/sh
# ~/.local/bin/myapp — run the newest AppImage, whatever the updater named it
exec "$(ls -t "$HOME"/.local/bin/MyApp*.AppImage | head -n1)" "$@"
```

Then in the `.desktop` file:

```
Exec=/home/you/.local/bin/myapp %U
TryExec=/home/you/.local/bin/myapp
```

Keep the AppImages in one folder, adjust the `MyApp*` glob to match yours. Hit this with Lens, which ships versioned filenames.
