### ISSUE TITLE
Version comparison not correct

### ISSUE THREAD

**Issue by adammeyer** [electron-userland/electron-builder#5479]
* **Updater Version**: 4.3.5
* **Electron Version**: 8.5.5
* **Target**: mac and windows

2020.4.11 is being seen as an available update to 2021.1.0, but 2021.1.0 is a higher version number.  This only is seen in a production build, in my dev env, the correct message is shown.  I've copied the `dev-app-update.yml` contents from the production `app-update.yml`, so I know they match.

In dev/debug run:
`Update for version 2021.1.0 is not available (latest version: 2020.4.11, downgrade is allowed).`

In proudction build:
`Found version 2020.4.11`

Any suggestions on why this happens or how I can replicate the behavior in my dev env?  Thanks

**Comment by adammeyer** [comment]
I've noticed that the `autoUpdater.currentVersion` object is not consistent between dev and build.  Version number is the same, but different props.

Build:
<img width="206" alt="Screen Shot 2020-12-15 at 2 31 24 PM" src="https://user-images.githubusercontent.com/4603906/102263589-8338c980-3ee2-11eb-966d-d8e7f75c1380.png">

Dev:
<img width="202" alt="Screen Shot 2020-12-15 at 2 32 00 PM" src="https://user-images.githubusercontent.com/4603906/102263597-86cc5080-3ee2-11eb-8378-fae082da0cef.png">

**Comment by crashedpixel** [comment]
i'm seeing the same issue... any updates?

**Comment by adammeyer** [comment]
@crashedpixel I wasn't able to find the root issue, so I used a library called `semver` to create my own comparison.
https://www.npmjs.com/package/semver

```
autoUpdater.on('update-available', info => {
      // version update is greater check
      if (semver.gte(info.version, autoUpdater.currentVersion.version)) {
        // update available
      } else {
        // update not available
      }
    });
```
