### ISSUE TITLE
app-update.yml not being generated when using the --prepackaged flag

### ISSUE THREAD

**Issue by FoonkG** [electron-userland/electron-builder#5480]
* **Version**: 22.9.1

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis

Exactly the same issue as #2761 , but that one is closed and noone helped them out so here i am creating a new one...

Any help would be appreciated.

**Comment by SentoxAIO** [comment]
+1, I am facing the same issue.

**Comment by Taraus-He** [comment]
+ 1, I am facing the same issue. but I create app-update.yml by
 "build": {
    "afterPack": "scripts/xxx.js",
   }
