### ISSUE TITLE
Feature Request: Provide a way to get delta size to be downloaded in auto update (differential download)

### ISSUE THREAD

**Issue by kksharma1618** [electron-userland/electron-builder#5482]
* **Version**:  22.9.1

* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**:

* **Target**:  Windows/Linux/Mac (applies to all)

This is not an issue. But a feature request.
The auto updater provided in electron-builder uses blockmaps to differential download updates. Right now there doesnt seem to be anyway to get the actual size which will be downloaded. 
electron-updater/src/differentialDownloader/DifferentialDownloader.ts has a method doDownload.
Which actually calculates how much it will download and how much it will copy

``` typescript
let downloadSize = 0
    let copySize = 0
    for (const operation of operations) {
      const length = operation.end - operation.start
      if (operation.kind === OperationKind.DOWNLOAD) {
        downloadSize += length
      }
      else {
        copySize += length
      }
    }
```
Then it prints in log:
``` typescript
logger.info(`Full: ${formatBytes(newSize)}, To download: ${formatBytes(downloadSize)} (${Math.round(downloadSize / (newSize / 100))}%)`)
```

## Use case
I would like to present the users of my app actual info about how much data will be downloaded during update. I reckon users will feel better knowing that 500kb will be downloaded (instead of 200 mb). Is it possible to expose this info (actual download size)? Some method like autoUpdate.getActualDownloadSize(). It should work after update info has been fetched.

**Comment by kksharma1618** [comment]
Yes. Still relevant

**Comment by mmaietta** [comment]
@kksharma1618 can you take a look at this PR? I think it solves your needs by providing an `onProgress` callback for differential downloads
https://github.com/electron-userland/electron-builder/pull/5515/files#diff-fbb4808de8ef67b244d52d1824827dde6a2c2eb17d4a2911b52d755a7b368558R25
