### ISSUE TITLE
How to publish dynamic bucket?

### ISSUE THREAD

**Issue by sontd-0882** [electron-userland/electron-builder#5483]
* **Version**: 22.9.1

* **Electron Version**: 10.1.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: 

I'm using `electron-updater` with S3 provider, configurations as below 
```
  "publish": {
    "provider": "s3",
    "bucket": "my-app-dev",
    "region": "ap-northeast-1",
    "path": "releases"
  },
```
I have 3 different environments, `dev`, `staging` and `production` and I want to separate into 3 buckets `my-app-dev`, `my-app-stg` and `my-app`. How to achieve this?

**Comment by fjeddy** [comment]
You can always use the versioning system to achieve this, and from what I understand, it's how it's intended to be used.

Basically, you upload everything to one bucket, but you use versioning like `0.0.5-dev`, `0.0.6-staging`, `0.0.3`, this would result in three different files being made `dev.yml`, `staging.yml`, `latest.yml`. Auto updater will know what version to update and fetch from based on the version installed. So if you have the staging version installed, it will call and look for updates in `staging.yml` and not `latest.yml`

It's [documented here](https://www.electron.build/configuration/publish#continuous-deployment-workflow-on-amazon-s3-and-other-non-github)
