### ISSUE TITLE
Cannot build MSI package on MacOS 10.14

### ISSUE THREAD

**Issue by mrjoshuaesmith** [electron-userland/electron-builder#5486]
* **Version**: 22.9.1

* **Electron Version**: 10.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: MSI ia32

I currently cannot build MSI in MacOS 10.15 because of [this issue](https://github.com/electron-userland/electron-builder/issues/5377).

But I happen to have 10.14 running in a VM, so I figured maybe I could get MSI built there. However, I'm getting this error, which I haven't been able to find in any other issue:

      • building        target=MSI arch=ia32 file=dist/MyApp 20.12.11713 ia32.msi
      ⨯ cannot execute  cause=exit status 1
                    out=WiX Toolset Linker version 4.0.0.5512
      Copyright (c) .NET Foundation and contributors. All rights reserved.
    
    Updating file information.
    Creating cabinet files.
    There will be '2' threads used to produce CAB files.
    Creating cabinet 'C:\users\develar\Temp\wix201217T1307348302\#cab1.cab'.
    
                    errorOut=wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
    err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
    light.exe : error LGHT0001 : Invalid handle. (Exception from HRESULT: 0x80070006 (E_HANDLE))
    
    Exception Type: System.Runtime.InteropServices.COMException
    
    Stack Trace:
       at WixToolset.Cab.Interop.NativeMethods.CreateCabFinish(IntPtr contextHandle, IntPtr newCabNamesCallBackAddress)
       at WixToolset.Cab.WixCreateCab.Complete(IntPtr newCabNamesCallBackAddress)
       at WixToolset.Bind.Databases.CabinetBuilder.CreateCabinet(CabinetWorkItem cabinetWorkItem)
       at WixToolset.Bind.Databases.CabinetBuilder.ProcessWorkItems()
    
                    command=/Users/jesmith/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine 'Z:\Users\jesmith\Library\Caches\electron-builder\wix\wix-4.0.0.5512.2\light.exe' -out 'Z:\private\tmp\4042\dist\MyApp 20.12.11713 ia32.msi' -v -spdb -sw1076 '-dappDir=Z:\private\tmp\4042\dist\win-ia32-unpacked' -pedantic -wx -sval project.wixobj
                    workingDir=

The "machine" I'm running 10.14 in is a Parallels Desktop VM, in case that helps narrow this down.

**Comment by mmaietta** [comment]
A quick search brought up this issue: https://github.com/electron-userland/electron-builder/issues/3830#issuecomment-669078664
Few solutions to try:
- Clear cache via `rm -rf ~/Library/Caches/electron-builder`
- Use electronuserland/builder:wine-mono instead of electronuserland/builder:wine
- Docker disk space is full, clear with `docker system prune -a -f`
- Config issue. Ex: MSI icon is missing

**Comment by mrjoshuaesmith** [comment]
Thanks, I did turn up that same comment which helped me get past another error. And I understand that the first error (cannot find) is bogus, but that the subsequent error (error running command) is the real issue.

I have tried clearing my cache. It downloaded the same things and then I got the same error.

I don't understand the wine-mono advice. I installed electron-builder with yarn and I'm running it from the node_modules folder. I don't know how to tell it to use wine-mono instead of wine.

If I'm running docker, I don't know it. Maybe that's how electron-builder does things under the covers? I certainly don't have docker in my path.

I'm game for looking for config issues. I can't find documentation of exactly where I'm supposed to be putting the MSI icon. It's in the "icon" attribute of the "win" object in the JSON.

**Comment by mrjoshuaesmith** [comment]
As a workaround, I copied my stuff over to a windows VM and installed the builder. It worked fine, which I would think eliminates any questions of my Mac configuration files being broken.

Note, however, that the desktop icon it creates has no icon. This was reported already:
https://github.com/electron-userland/electron-builder/issues/2799
But the bug report never got any love and a bot closed it.

**Comment by uiot-stack** [comment]
I have the same question, how to resolve it

**Comment by uiot-stack** [comment]
update icon， fixed it
