### ISSUE TITLE
MacOS Info.plist not being added

### ISSUE THREAD

**Issue by Ishaangandhi** [electron-userland/electron-builder#5494]
* **Version**: 
29.9.1

* **Electron Version**:
11.0.3

* **Electron Type (current, beta, nightly)**:
Current

* **Target**: 
MacOS

I'm trying to add an extra key to the Info.plist file. I've added this to my build rule:
```
      "extendInfo": "builddist/Info.plist",
```

And in my Info.plist file, I have 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSAppleEventsUsageDescription</key>
	<string>Shell Notebook can control other applications with AppleScript.</string>
</dict>
</plist>
```
Yet, this key is not showing up in the application after running Electron builder. What's happening?

**Comment by mmaietta** [comment]
IIRC, extendInfo takes a dictionary:
```
extendInfo: {
	NSAppleEventsUsageDescription: "Shell Notebook can control other applications with AppleScript."
}
```

**Comment by Ishaangandhi** [comment]
Thank you! That will do it!
