### ISSUE TITLE
use electron-builder, node-gyp will find error node version to download node headers!!@#!@#!@#!@@!#!@!

### ISSUE THREAD

**Issue by spcBackToLife** [electron-userland/electron-builder#5496]
electron version: 11.0.3
electron-builder version: ^22.9.1

when I set like this:
```
electronVersion: '11.0.3',
nodeVersion: '12.18.3'
```
in windows, it will find node-v11.0.3-headers.tar.gz  to download and obviously，it won't find that verson. why not use nodeVersion???????
![image](https://user-images.githubusercontent.com/20703494/102963735-d6370000-4524-11eb-939a-d66657093d60.png)

**Comment by spcBackToLife** [comment]
@spcBackToLife the reason is node-gyp will find node version by process.version ,but when we config electronVersion, seems this vill be gave to process.version=electronVersion, so node-gyp always find the error version to download headers , that won't find that node-gyp

**Comment by spcBackToLife** [comment]
the way is to set npmArgs to use the correct node version .
```
npmArgs: ['--target', '11.0.3'] .
```
then will download 11.0.3 node-headers

**Comment by ym13349140** [comment]
> the way is to set npmArgs to use the correct node version .
> 
> ```
> npmArgs: ['--target', '11.0.3'] .
> ```
> 
> then will download 11.0.3 node-headers

@spcBackToLife Hi, I'm having the same problem, so where did you set this `npmArgs` param?
