### ISSUE TITLE
Windows is searching for program.exe

### ISSUE THREAD

**Issue by alex-griffiths** [electron-userland/electron-builder#5499]
* **Version**: ^22.7.0 

* **Electron Version**: ^8.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  NSIS

Running my installer I get a dialog that pops up that says "Windows is searching for Quotation Assistant.exe.." and it gives me the option to try and browse and find the exe myself. 

![image](https://user-images.githubusercontent.com/19744255/103040837-c83abb00-45c8-11eb-8245-26f5672c953e.png)

If I let it continue trying to find the executable, it always fails. 

![image](https://user-images.githubusercontent.com/19744255/103040862-d4bf1380-45c8-11eb-883d-f9161c49b108.png)

I can browse and select the executable that is located at `dist/win-unpacked/Quotation Assistant.exe` and that will work until I try run the installer again and it fails.

In my `AppData/Local/Programs/quotation-assistant` folder, there is only the uninstaller present. I checked another program that I use electron-builder for, and it's got a lot more files present (what looks like to be the contents of the win-unpacked folder).

I've done some searching already trying to fix this issue, and I've found the following issue: #4057 . That seems to be the closest I can find to what I'm getting. The solutions proposed in that issue do not work for me.

My current build settings:
```
	"build": {
		"appId": "quotation-assistant",
		"productName": "Quotation Assistant",
		"compression": "store",
		"asar": true,
		"win": {
			"target": {
				"target": "NSIS",
				"arch": [
					"x64",
					"arm64"
				]
			},
			"icon": "app/static/icons/win/icon.ico"
		},
		"files": [
			"!dist/*",
			"!dummy_root/*",
			"!screens/*",
			"!app/sass/*",
			"!.sass-cache/*",
			"!.vscode/*",
			"!package-lock.json",
			"!*.rb",
			"!*.sql"
		]
	},
```

This issue appears to occur on multiple computers as well, not just the computer I'm building on.

**Comment by alex-griffiths** [comment]
As a bit of an update to this. 

The same issue has been occurring on three different computers. This is making me think that it's perhaps a config issue that I'm just not seeing.

**Comment by xuzhaobin** [comment]
I have the same problem.Try running the installation package with administrator privileges.

**Comment by alex-griffiths** [comment]
Running as administrator (both building and the installation) doesn't seem to work.

 I think it's probably got something to do mainly with this block of `package.json`

```json
"target": {
	"target": "NSIS",
	"arch": [
		"x64",
		"arm64"
	]
},
```

Which I pulled from the docs I think (it's been a while and I originally did it for another project) so that I could build on ARM.

**Comment by matthiasg** [comment]
@alex-griffiths I have the exact same issue. Building with just arm64 doesn't work either (complaining about not finding files).

**Comment by matthiasg** [comment]
this is related to https://github.com/electron-userland/electron-builder/issues/5461

**Comment by alex-griffiths** [comment]
This doesn't appear to have been an issue on version `20.40.x` which I had used on another project. So somewhere between then and `^22.7.0` something has gone awry.

@develar Do you have any idea what might have changed between these versions.

The only notable change I see as an end-user is that the `build` command was replaced by the `electron-builder` command.

**Comment by alex-griffiths** [comment]
Its been about 2 months since I made this issue, and there doesn't really seem to be any activity. I'm not sure who else to ping other than @develar.

Would be amazing if he or another community member with a bit more insight into this issue could respond.

**Comment by Tariqu** [comment]
Hi @alex-griffiths I am facing the same exact same issue. I also notice that this is happening after upgrading electron-builder version to 22.11.7 please any member of this community can help us then it will be a highly appriciable

**Comment by alex-griffiths** [comment]
@Tariqu I've sinced stopped using this project as I've moved on to other things, but it does seem that this issue isn't a priority at the moment. Best of luck trying to resolve this.

**Comment by ravi-poonia-7** [comment]
I am also facing the same issue

**Comment by Echo4F** [comment]
Can anyone be of help?

**Comment by joel-foo** [comment]
Same issue. Can the devs do something?

**Comment by erasmosoares** [comment]
I also facing the same issue only on a windows build, looks fine for the dmg btw.

**Comment by akhileshthite** [comment]
> I had this issue and resolved it by switching the build target, in my case to `ia32`
> 
> This is my `build:win` command in package.json
> 
> ```js
> npm run build && electron-builder --win --config --ia32
> ```
> 
> I am compiling for Windows on a Mac M1, and the default build was producing arm64 builds.

Hey @bradjasper,
Thanks for your fix!

I'm facing similar issue when I try to run my electron app in Intel x64 mac, it's producing arm64 builds.

**Comment by EarthsWormz** [comment]
I had this issue, My error was that my project folder was over 10gb, after deleting unused packaged builds i managed to get my project down to ~500mb. Now the project is smaller i have no issues building and installing.

**Comment by jehugaleahsa** [comment]
In my case, this issue was caused by adding `.exe` and `.dll` to the list of `preCompressedFileExtensions` under the `nsis` option. It really doesn't make any sense, since the documentation says this:

```
Applicable only for extraResources and extraFiles files.
```

Somehow this was influencing my results and there's no clear indication why,

**Comment by shealan** [comment]
Thank you @bradjasper, the issue was indeed default Windows builds on M series Macs being ARM. The `--ia32` flag fixes this.
