### ISSUE TITLE
Allow users to define array of path globs which will not be codesigned

### ISSUE THREAD

**Issue by nwittwer** [electron-userland/electron-builder#5500]
* **Version**: 22.9.1
* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: Current
* **Target**: MacOS

I am trying to notarize an Electron build for Mac but hitting issues codesigning bundled .app files (e.g. Chromium, Firefox, WebKit) installed by Playwright which are then moved to a directory besides `node_modules`. I noticed that there is a workaround for this here (#5451), but that solution breaks down when I have moved those binary files to a different directory. In my case I've copied those `./node_modules/playwright/.local-browsers` files to a directory which becomes `./dist/resources` when packaged, therefore causing the original issues about not being able to codesign arise again.

I noticed there is a `ignore` property added after #1699 here: https://github.com/SentoxAIO/electron-builder/blob/6bfc78078f51a9b63e5b37f8a699d3d19571ba4c/packages/app-builder-lib/src/macPackager.ts#L191, but it is unclear to me from the documentation how I should set this. Do I set this in my `builder.config.js` file like so under the `mac` target?

builder.config.js
```js
module.exports = {
  productName: require("./package.json").productName,
  appId: "com.reflex.app",
  directories: {
    output: "build",
  },
  // ... other options ...
  mac: {
    target: "dmg",
    icon: ICONS_DIR + "icon.icns",
    // ... other options ...
    ignore: "thing",                  // <---- this?
  },
  afterSign: 'scripts/notarize.js',
};
```

Or does it belong with the notarization script? 
scripts/notarize.js
```js
const { notarize } = require("electron-notarize");

exports.default = async function notarizing(context) {
  const { electronPlatformName } = context;

  if (electronPlatformName !== "darwin") return false; // Only Notarize MacOS apps

  return await notarize({
    appBundleId,
    appPath,
  });
};
```

Questions
1. How can I define paths which should be ignored for code signing on Mac? Is there a way to add an array of files to ignore in the `options` exposed in Electron-Builder?
2. Or, do you recommend I simply follow the file patterns defined in https://github.com/SentoxAIO/electron-builder/blob/6bfc78078f51a9b63e5b37f8a699d3d19571ba4c/packages/app-builder-lib/src/macPackager.ts#L200 of `./node_modules/playwright/.local-browsers`? 

It would be great to mention more about this process on https://www.electron.build/configuration/mac; I had to dig quite a bit through the source code to figure out why the notarization failed due to how certain paths are auto-ignored and others are not.

**Comment by nwittwer** [comment]
I found that `build: { mac: signIgnore: '' }` is the property that appears to be valid, at least for Mac builds. https://github.com/electron-userland/electron-builder/pull/5262

I expected that this would allow me to notarize the app for Macos: `build: { mac: signIgnore: '/node_modules/playwright/.local-browsers' }`.

However, I'm still still having issues when trying to bundle Playwright browser binaries:

Error log: (MacOS 11.1, Node v14, Playwright v1.7.1)
```
/Users/me/my-app/build/mac/MYAPP.app/Contents/Resources/app/node_modules/playwright/.local-browsers/firefox-1221/firefox/Nightly.app/Contents/MacOS/firefox: code object is not signed at all
```

Theoretically this should not be an issue if this is working: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts#L237

**Comment by mmaietta** [comment]
Latest electron-builder should be able to sign custom binaries from Contents root. https://github.com/mmaietta/electron-builder/blob/d6255e56d10ae74b599cb40259d680a41b2fcd9e/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141
Used as: 
```
mac: {
   binaries: ['MacOS/firefox']
}
```
Not sure if it's in the most recent pre-release cut yet though
