### ISSUE TITLE
Running yarn test on Windows

### ISSUE THREAD

**Issue by ficristo** [electron-userland/electron-builder#5503]
* **Version**: master commit a6e86b593048b4eb3047b7c3a54d02d0521b02d2

* **Electron Version**: N/A
* **Electron Type (current, beta, nightly)**: N/A

* **Target**: N/A

I run `yarn test` through the Git Bash and results in errors:
```
Test Suites: 6 failed, 17 skipped, 16 passed, 22 of 39 total
Tests:       7 failed, 175 skipped, 65 passed, 247 total
Snapshots:   2 failed, 85 passed, 87 total
Time:        404.625 s
Ran all test suites.
```
I've run `yarn && yarn compile` followed by `yarn test`.
Do I need to run some other commands?

**Comment by ficristo** [comment]
Not sure what is going on, but with master commit 77c215d1b1913982a7c9a62b1b5098d95a37272d and `pnpm test` now I get:
```
Test Suites: 11 failed, 14 skipped, 14 passed, 25 of 39 total
Tests:       16 failed, 156 skipped, 58 passed, 230 total
Snapshots:   3 failed, 75 passed, 78 total
```

**Comment by mmaietta** [comment]
Hmmm, from what I've noticed, it seems many of the tests are configured to run specifically on Linux or the Mac TravisCI node.  

To mirror the CI config, the tests to validate on Windows should be these:
https://github.com/electron-userland/electron-builder/blob/77c215d1b1913982a7c9a62b1b5098d95a37272d/.github/workflows/test.yaml#L40-L42

Tests will prob still be breaking though; happy to accept help in recovering our health checks.
