### ISSUE TITLE
Auto-Update invalid header and maximum allowed size.

### ISSUE THREAD

**Issue by Daniele122898** [electron-userland/electron-builder#5505]
* **electron-builder**: 22.9.1

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current

* **electron-updater**: 4.3.5

* **Target**: Windows

So this is the code i use for updating: 
```ts
// Disable auto downloading of updates
autoUpdater.autoDownload = false;

const updateApp = (mainWindow: BrowserWindow) => {
  // Check for update
  autoUpdater.checkForUpdates()
    .catch(e => logger.error('Check for updates failed', e));

  autoUpdater.on('update-available', () => {
    // prompt user to start download
    dialog.showMessageBox({
      type: 'info',
      title: 'Update available',
      message: 'A new version of Media Dashboard is available. Do you want to update now?',
      buttons: ['Update', 'No']
    }).then(res => {
      const buttonIndex = res.response;

      if (buttonIndex === 0) {
        autoUpdater.downloadUpdate()
          .catch(e => logger.error('Update download failed', e));
      }
    });

  });

  // Listen for update download finished
  autoUpdater.on('update-downloaded', () => {
    mainWindow.setProgressBar(-1);
    dialog.showMessageBox({
      type: 'info',
      title: 'Update ready',
      message: 'Update downloaded. Install update & restart now?',
      buttons: ['Yes', 'Later']
    }).then(res => {
      const buttonIndex = res.response;

      // install and restart
      if (buttonIndex === 0) {
        autoUpdater.quitAndInstall(false, true);
      }
    });
  });

  // Listen for download progress
  autoUpdater.on('download-progress', (progress, bytesPerSecond, percent) => {
    mainWindow.setProgressBar(progress);
  });
};
```

When i start my electron app it correctly tells me that there is a new version of the app. Once i click on Update i receive this error message: 
![image](https://user-images.githubusercontent.com/20451770/103177429-c009a680-487a-11eb-8335-8c3545952785.png)

The release on github looks like this:
![image](https://user-images.githubusercontent.com/20451770/103177438-d152b300-487a-11eb-9ec7-7a77812eea80.png)

This is the electron-builder.json:
```json
{
  "productName": "Media Dashboard",
  "directories": {
    "output": "release/"
  },
    "files": [
        "**/*",
        "!**/*.ts",
        "!*.code-workspace",
        "!LICENSE.md",
        "!package.json",
        "!package-lock.json",
        "!src/",
        "!e2e/",
        "!hooks/",
        "!angular.json",
        "!_config.yml",
        "!karma.conf.js",
        "!tsconfig.json",
        "!tslint.json"
    ],
  "extraFiles": [
    "trayTemplate@2x.png"
  ],
  "publish": {
    "provider": "github",
    "token": ""
  },
  "win": {
    "icon": "dist/assets/icons",
    "target": [
      "nsis"
    ],
    "publisherName": "ArgonautDevelopments",
    "certificateFile": "private/ArgonautDevelopments.pfx",
    "certificatePassword": ""
  },
  "mac": {
    "icon": "dist/assets/icons",
    "target": [
      "dmg"
    ]
  },
  "linux": {
    "icon": "dist/assets/icons",
    "target": [
      "AppImage"
    ]
  }
}

```

I have debuged this for many hours and have gotten nowhere. Initially i have gotten errors bcs of some header not being proper so i removed the portable version and now only use nsis. I installed the newest version and in the update logs i now see this:

```
[2020-12-27 19:30:52.118] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\danie\AppData\Local\Programs\media-dashboard\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:241:26)
    at ClientRequest.<anonymous> (C:\Users\danie\AppData\Local\Programs\media-dashboard\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:303:17)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6254)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    
```

Why is the differential download not possible? Also how can i increase the maximum allowed size? The change i made was 2 lines.

**Comment by biostunt** [comment]
same problem

**Comment by devsjangid** [comment]
I'm also facing the same problem.

**Comment by Daniele122898** [comment]
Any news on this?

**Comment by LeonanCarvalho** [comment]
I guess it only occurs in private repositories, maybe a GitHub restriction?

**Comment by LeonanCarvalho** [comment]
I guess it only occurs in private repositories, maybe a GitHub restriction?

I tried to understand why but its hardcoded and doesn't have any comment about  it 

Here:
https://github.com/electron-userland/electron-builder/blob/5d01ea6dc9daec4639ab54b38520b93833ac81d3/packages/builder-util-runtime/src/httpExecutor.ts#L210 

And here:

https://github.com/electron-userland/electron-builder/blob/5d01ea6dc9daec4639ab54b38520b93833ac81d3/packages/builder-util-runtime/src/httpExecutor.ts#L226

The limit was originally 5MB  when the method was created https://github.com/electron-userland/electron-builder/commit/c01b7c0b55d3466b826ea9cc9a11ad34118801c1#diff-f6445d9589029a2a1ce947c0940b7f7a715377570907a24a4e9087c582e07574


And this limit was increased from 5MB to 50MB By this PR:
https://github.com/electron-userland/electron-builder/commit/c5c2eeb80b9f357c18b486e94524580016009bd3#diff-f6445d9589029a2a1ce947c0940b7f7a715377570907a24a4e9087c582e07574

Maybe @develar  can help solve that?


Why do we need this limit? Why do we receive chunks bigger than 50mb? (network speed? server-side configuration?)

I guess the chunk size is a server-side configuration we can't control that size by application.

https://stackoverflow.com/questions/7058827/what-is-the-maximum-chunk-size-in-http-response-with-transfer-encoding-chunked


I tried to find when and why it was included  but no success :

https://github.com/electron-userland/electron-builder/commits/5d01ea6dc9daec4639ab54b38520b93833ac81d3/packages/builder-util-runtime/src/httpExecutor.ts

No comments at all.

**Comment by amiranagram** [comment]
Still having the same issue on 22.10.5

```
[2021-03-30 22:36:57.201] [info]  Found version 0.8.0 (url: app-0.8.0.exe)
[2021-03-30 22:36:57.210] [info]  Downloading update from app-0.8.0.exe
[2021-03-30 22:36:57.224] [info]  Download block maps (old: "https://api.github.com/repos/me/repo/releases/assets/34224707.blockmap", new: https://api.github.com/repos/me/repo/releases/assets/34224707.blockmap)
[2021-03-30 22:36:57.750] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\me\AppData\Local\Programs\app\resources\app.asar\background.js:2:191480)
    at ClientRequest.<anonymous> (C:\Users\me\AppData\Local\Programs\app\resources\app.asar\background.js:2:192996)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6777)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

Build options:

electron: `12.0.2`
electron-builder: `22.10.5`
os: `win-10.0.19042`

```
productName: 'App',
appId: 'com.example.app',
artifactName: 'App-${version}-${os}-${arch}.${ext}',
win: {
    target: 'nsis'
},
nsis: {
    artifactName: 'App-Setup-${version}-${os}-${arch}.${ext}',
    oneClick: true,
    perMachine: false,
    deleteAppDataOnUninstall: false,
    allowToChangeInstallationDirectory: false,
    runAfterFinish: true,
    differentialPackage: false
},
publish: [
    {
        provider: 'github',
        private: true,
        owner: 'me',
        repo: 'repo',
        token: 'token'
    }
],
```

Anything I'm doing wrong?

**Comment by mmaietta** [comment]
Can someone please try this patch from my comment here? https://github.com/electron-userland/electron-builder/issues/4676#issuecomment-811177696
Idk if 5 or 50 were specifically or arbitrarily determined, so the patch simply enables 100mb chunks. Give it a test and report back? Maybe we'll have a basic solution to start with.
