### ISSUE TITLE
electron打包

### ISSUE THREAD

**Issue by zhouyuanzhi92** [electron-userland/electron-builder#5508]
项目完成以后使用打包命令，然后就报这样的错 然后就有点懵，开始是看着打包命令出问题，但是修改以后还是依旧在报build:32这个命令有问题。
报错信息在下面 求大佬指点一下 谢谢勒

OKAY  take it away `electron-builder`

  • electron-builder  version=22.9.1 os=10.0.18363
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=build\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@4.2.0 platform=win32 arch=ia32
  ⨯ cannot execute  cause=exit status 1
                    out=
    > sqlite3@4.2.0 install D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3
    > node-pre-gyp install --fallback-to-build

    Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3\lib\binding\electron-v4.2-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3\lib\binding\electron-v4.2-win32-ia32 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (1)

                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v4.2-win32-ia32.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and electron@4.2.12 (electron-v4.2 ABI, unknown) (falling back to source compile with node-gyp)
    gyp ERR! find VS
    gyp ERR! find VS msvs_version not set from command line or npm config
    gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
    gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
    gyp ERR! find VS looking for Visual Studio 2015
    gyp ERR! find VS - not found
    gyp ERR! find VS looking for Visual Studio 2013
    gyp ERR! find VS - not found
    gyp ERR! find VS
    gyp ERR! find VS **************************************************************
    gyp ERR! find VS You need to install the latest version of Visual Studio
    gyp ERR! find VS including the "Desktop development with C++" workload.
    gyp ERR! find VS For more information consult the documentation at:
    gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
    gyp ERR! find VS **************************************************************
    gyp ERR! find VS
    gyp ERR! configure error
    gyp ERR! stack Error: Could not find any Visual Studio installation to use
    gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
    gyp ERR! stack     at findVisualStudio2013 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
    gyp ERR! stack     at regSearchKeys (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
    gyp ERR! stack     at regGetValue (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
    gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    gyp ERR! System Windows_NT 10.0.18363
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\swx_obj\\JAKB\\jakb\\04_code\\QuickCase\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-ia32\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\swx_obj\\JAKB\\jakb\\04_code\\QuickCase\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-ia32" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.2"
    gyp ERR! cwd D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3
    gyp ERR! node -v v10.20.0
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3\lib\binding\electron-v4.2-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3\lib\binding\electron-v4.2-win32-ia32 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    node-pre-gyp ERR! System Windows_NT 10.0.18363
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\swx_obj\\JAKB\\jakb\\04_code\\QuickCase\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\swx_obj\JAKB\jakb\04_code\QuickCase\node_modules\sqlite3
    node-pre-gyp ERR! node -v v10.20.0
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sqlite3@4.2.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-12-29T07_37_44_472Z-debug.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild sqlite3@4.2.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quickcase@1.0.86 build:32: `node .electron-vue/build.js && electron-builder --win --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quickcase@1.0.86 build:32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by StaZhu** [comment]
需要装一下vsstudio 和vsstudio build tools

**Comment by zhouyuanzhi92** [comment]
> 需要装一下vsstudio和vsstudio构建工具

我这里用的vs code，是不是还需要下一个vs studio？
