### ISSUE TITLE
App not appearing in Windows start menu after installation

### ISSUE THREAD

**Issue by YagoGG** [electron-userland/electron-builder#551]
* **Version**: 3.27.0

* **Target**: Windows x64

* **Node.js version**: 6.2.2
* **npm version**: 3.9.5

* **`build` field in development `package.json`**:

```
"build": {
    "app-bundle-id": "com.yagogg.myapp",
    "app-category-type": "public.app-category.productivity"
  }
```

I've created an app using Electron, and successfully bundled it in an `.exe` file with electron-builder, using the command `run`.

When I run the generated executable, the application starts with the default installation GIF, as expected.

After the GIF finishes, the app restarts and works properly. **It even appears in control panel's programs list**.

However, if I look for it in the start menu applications, it isn't there (and searching it by its name only returns the aforementioned `.exe` installer).
Because of this, once the app is closed, the only way to open it back is running again the installer.

I'd like to know why does this happen, and how can I solve it.
Thanks!

**Comment by develar** [comment]
Only NSIS installer creates shortcuts and start menu without code on your side. For Squirrel.Windows please see https://github.com/electron-userland/electron-builder/issues/549#issuecomment-229284853

**Comment by YagoGG** [comment]
Alright, thank you very much!

**Comment by develar** [comment]
We understand that it is not user-friendly, and it is why NSIS was added, but NSIS will not be default windows target until #529 is not fixed.

**Comment by YagoGG** [comment]
BTW, how come it says `Unknown target: nsis`?

```
"build": {
    "appId": "com.yagogg.myapp",
    "win": {
      "target": [ "nsis" ]
    },
    "nsis": {

    }
}
```

**Comment by develar** [comment]
@YagoGG electron-builder 3 is outdated, please use latest version.

**Comment by YagoGG** [comment]
Great, now it works like a charm! Thanks a lot @develar
