### ISSUE TITLE
macOS Installer overlapping

### ISSUE THREAD

**Issue by PaulKeefe** [electron-userland/electron-builder#5516]
* **Version**: 22.9.1

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

After double clicking my .dmg, the installer panel opens and shows my app icon on top of the Applications icon. Instead of my app on the left and the Applications icon on the right of the arrow, they are both at the bottom middle. You cannot drag the app icon on top of the Applications icon, because they are already over each other. The app installs correctly if I drag my app icon out of the installer panel and drop it into the "real" Applications folder in the finder.

Here is an image of the installer. Any hints on how to solve this would be appreciated!
<img width="541" alt="Screen Shot 2021-01-03 at 9 49 59 AM" src="https://user-images.githubusercontent.com/3914425/103481474-45281a80-4da9-11eb-9211-0a48634a974d.png">

**Comment by mmaietta** [comment]
What's your electron builder config for dmg? Have you tried individually positioning the icons?
```
dmg: {
        title: "${productName} " + buildVersion,
        background: "installer/mac/dmg-background.png",
        iconSize: 100,
        contents: [
            {
                x: 253,
                y: 100,
                type: "file"
            },
            {
                x: 253,
                y: 315,
                type: "link",
                path: "/Applications"
            }
        ]
    },
```

**Comment by PaulKeefe** [comment]
When I change the x/y of the icon, my icon and the Applications icon move together. They remain stacked. If there were a better explanation of the how the x/y relates to the installer panel, that would help. i.e., why are there two places for x/y but in the docs it doesn't mention that. What does each of the contents array objects represent?
