### ISSUE TITLE
Mac .app very big size

### ISSUE THREAD

**Issue by Levminer** [electron-userland/electron-builder#5517]
* **22.9.1**: 

* **11.1.1**:
* **current**:

* **mac**: 

I'm building for mac on github actions. The .dmg file is about 80mb but the .app is 500mb, its way to big for some reason.

The files: (https://nightly.link/Levminer/authme/workflows/mac-artifacts/dev/authme-latest-mac-x64-installer-portable.zip)

**Comment by Levminer** [comment]
After adding --x64 it' still an univeral app.

**Comment by mmaietta** [comment]
Would you mind trying with another version of Electron? Something like 8 or 10? I'm curious if this is isolated to electron-builder or if it's dependent upon the Electron version. The notion that the compressed size is an 80mb dmg confuses me since the app size is so large.

**Comment by Levminer** [comment]
Yes, same on electron 10.2.0

**Comment by Levminer** [comment]
Also same on electron 9.

**Comment by Levminer** [comment]
Any update on this?

**Comment by mmaietta** [comment]
Can you share your electron builder config, notably the parts regarding file packaging:  asar, files, extraFiles, resources, etc? 

I don't understand why the `.app` would be registering so large as this hasn't been reported elsewhere AFAIK. The frameworks were the notable culprits for the app size, so the fact this is occurring for you across multiple electron versions makes me think this is a local issue.
My best advice would be for you to slim down the electron-builder config to isolate what is causing the size difference.
Alternatively, if you can provide a minimum reproducible repo that'd help significantly.

Also, it may be worth trying out the latest pre-release branch 22.10.4

**Comment by Levminer** [comment]
1. Okay first my problem is this is a universal mac build, and I cant disable it. (https://www.electronjs.org/blog/apple-silicon) Also electron-builder is not supported according to the electron docs.

2. This is not only problem on my machine, the link I sent you is builded on GitHub Actions.

3. My package: 
```
"build": {
		"productName": "Authme",
		"appId": "com.levminer.authme",
		"asar": false,
		"win": {
			"target": [
				"nsis"
			],
			"icon": "img/icon.ico"
		},
		"nsis": {
			"installerIcon": "img/icon.ico",
			"uninstallerIcon": "img/icon.ico",
			"uninstallDisplayName": "Authme",
			"license": "LICENSE.md",
			"oneClick": false,
			"allowToChangeInstallationDirectory": true,
			"createDesktopShortcut": "always"
		},
		"linux": {
			"target": "deb",
			"icon": "img/icon.png",
			"maintainer": "levminer@levminer.com"
		},
		"mac": {
			"target": "dmg",
			"icon": "img/icon.icns",
			"category": "public.app-category.utilities"
		}
	},
```

4. I'll check the new update later, updating this.

**Comment by Levminer** [comment]
Nope, same on electron-builder@next.

**Comment by mmaietta** [comment]
This isn't a universal app issue unless you're explicitly setting mac target arch in config file with `arch: "universal"`, yours is just "dmg"
You can verify locally that it's not a universal build by running lipo on the app's executable, it's an x64 build in this case.
```
$ lipo -info ./authme-latest-mac-x64-installer-portable/mac/Authme.app/Contents/MacOS/Authme
Non-fat file: ./authme-latest-mac-x64-installer-portable/mac/Authme.app/Contents/MacOS/Authme is architecture: x86_64
```
Electron ships arm64 and x64 binaries separately for devs to stitch together using their @electron/universal npm package.


I just noticed that the `.app` within your DMG file is only 200mb, which seems normal considering your bundle is ~20mb and the Electron Framework seems to normalize around ~180mb
Your `/mac/Authme.app` is showing 500mb, but I'm not sure that should matter if your final packaged production asset is 200mb. Best guess is that electron-builder is stripping data between the unpacked dir and when it packages into the dmg.

**Comment by Levminer** [comment]
Okay than I don't understand why I have an "A" folder and a "Current" folder.

![image](https://user-images.githubusercontent.com/33373714/105106754-c58f9080-5ab6-11eb-94e5-e271736c6b41.png)

**Comment by mmaietta** [comment]
That's how mac/iOS frameworks work IIRC. 'A' is a version, 'Current' is an alias to it.

**Comment by Levminer** [comment]
Okay, so I guess this is not an issue of electron-builder, @mmaietta thansk for the help!
