### ISSUE TITLE
Packaged Electron app is throwing EPERM: operation not permitted while trying to protected User directories

### ISSUE THREAD

**Issue by ganeshrvel** [electron-userland/electron-builder#5525]
* **Version**: 22.9.1

* **Electron Version**:10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

I have a file manager, electron based, app which lets user browse through directories. In the development version of the app, users can read/write all the directories without any restriction.
But after packaging the app whenever the user tries to access the protected directories it throws `EPERM: operation not permitted, scandir` error. I use `fs.readdir` to read the directory.

The app runs into trouble reading these directories frequently:

- '/Users/username/Pictures/Photos Library.photoslibrary'
- '/Users/username/Desktop'
- '/Users/username/Download'
- '/Users/username/Document'

This happens even after notarizing the app.

This is my build config:
```json
"forceCodeSigning": true,
"mac": {
      "type": "distribution",
      "category": "public.app-category.productivity",
      "icon": "build/icon.icns",
      "target": [
        "dmg",
        "zip"
      ]
    },
```

I tried adding adding entitlements.mac.plist file and it threw `[1]    38639 killed ` while trying to open the app.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>com.apple.security.files.user-selected.read-only</key>
<true/>
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
</dict>
</plist>
```

How do I fix this issue?

**Comment by glk-hll** [comment]
How do you solve this problem?

**Comment by ganeshrvel** [comment]
> How do you solve this problem?

I haven't yet.

**Comment by mmaietta** [comment]
Pretty sure you're dealing with permission issues on mac that are simply due to system processes, unrelated to electron-builder.

If you want to have proper access to user directories, then you'll need to prompt them for them to add your app to Security & Preferences, regardless of entitlements.

Check out this project: https://github.com/codebytere/node-mac-permissions
