### ISSUE TITLE
The specified timestamp server could not be reached

### ISSUE THREAD

**Issue by vtebano13** [electron-userland/electron-builder#5529]
Electron builder version: 19.56.0 and 22.9.1
Electron version: 4.1.4
Targets are: Windows 32 and 64 bit
Issue:
The application use to build with no issue as of Dec 14, 2020 both with signing and not.

As of January I am no longer able to sign the application or installer.

I am getting the following error:
SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.

Error with electron builder 19.56.0
![image](https://user-images.githubusercontent.com/7851946/103952865-1db9b080-510f-11eb-8088-44289217b5fc.png)

When I change to Election builder 22.9.1 it can't seem to fine the build command.  

![image](https://user-images.githubusercontent.com/7851946/103952696-d6cbbb00-510e-11eb-96d5-1e3fa4fea09f.png)

**Comment by Neayto** [comment]
I ran into the same issue and added this snippet into my package.json

```
win:
  timeStampServer: "http://timestamp.globalsign.com/scripts/timstamp.dll"
```
  
 @vtebano13

**Comment by mmaietta** [comment]
Alternative setup that I used:
```
        rfc3161TimeStampServer: "http://timestamp.digicert.com", // Manually set due to bug in win-packager. https://github.com/electron-userland/electron-builder/issues/5166

```

**Comment by vtebano13** [comment]
Looks like adding the option to package.json is working.  Thanks for the help.

**Comment by quamrulmina** [comment]
Using rfc3161TimeStampServer: "http://timestamp.digicert.com" fixed my issue on Visual Studio 2017. The full signtool command that worked for us is:
signtool sign  /n "My Company Inc."  /t http://timestamp.digicert.com c:\dev\myproject\mydll_to_sign.dll
