### ISSUE TITLE
linux package name cannot be specified

### ISSUE THREAD

**Issue by zoltan-mihalyi** [electron-userland/electron-builder#5530]
* **Version**:  22.10.4

* **Target**:  Linux

app-builder-lib uses "name" from package.json as linux package name and there is no way to override it with options.

**Comment by mmaietta** [comment]
I think you can use this: 
https://www.electron.build/configuration/linux
```
executableName String - The executable name. Defaults to productName. Cannot be specified per target, allowed only in the linux.
```

**Comment by zoltan-mihalyi** [comment]
Thank you, but unfortunately, the executable name and the package name are two separate things, and I need to change the package name.

The --name argument is equal to linuxPackageName:
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/fpm.ts#L127

The linuxPackageName field uses metadata.name, which is the name field of package.json
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/appInfo.ts#L114-L121
