### ISSUE TITLE
Will changing the name of the app in a new sign cert breake auto updater

### ISSUE THREAD

**Issue by sergeyd63** [electron-userland/electron-builder#5533]
* **Version**:  22.9.1

* **Electron Version**: 10/11/latest
* **Electron Type (current, beta, nightly)**: current

* **Target**: win/lin/mac

We've rebranded the company and the name of the app has changed. Now our certificate is going to expire and i wonder if changing the name on the cert can break auto update?

We're using electron-updater@4.3.4

Thanks

**Comment by mmaietta** [comment]
I'm not positive, but from reading these docs, I think you'll be okay if configured:
https://www.electron.build/configuration/win
> verifyUpdateCodeSignature = true Boolean - Whether to verify the signature of an available update before installation. The publisher name will be used for the signature verification.

The publisher name is what is used to validate.

For NSIS builds, you can use GUID to align installs: https://www.electron.build/configuration/nsis
> guid String - See GUID vs Application Name.
