### ISSUE TITLE
Auto update download very slow

### ISSUE THREAD

**Issue by niranhen** [electron-userland/electron-builder#5537]
* **Version**: `22.9.1`

* **Electron Version**: `8.2.3`
* **Electron Type (current, beta, nightly)**: `current`

* **electron-updater:**`4.3.5`

* **Target**: `Mac`
I'm using auto-updater, and this is my log after built:

Hello, the download is very slow, I have 60 - 70Mb Download speed, 
and when I download something from the internet is between 3MB-6MB per sec,
with electron-updater download speed is like 100KB-200KB per sec.

What can I do?
thanks.

**Comment by Katheesh** [comment]
Share your code. We'll analyze about it!

**Comment by stephanebouget** [comment]
+1
For me the update download speed is 1kb/s on windows.
On Mac, the speed is normal.

**Comment by t4lpi** [comment]
+1
I have the same problem. I'm using windows too. Any solution?

**Comment by khiopsrelease** [comment]
> +1
> I have the same problem. I'm using windows too. Any solution?

Yes I think I found the reason : it's because of a size quota on your account.
You must have too many releases.

Try to remove old releases (keep only 3 or 4 of the latest)
**wait for some hours, maybe some days** 
And everything will return to normal

**Comment by stephanebouget** [comment]
> +1
> I have the same problem. I'm using windows too. Any solution?

Yes I think I found the reason : it's because of a size quota on your account.
You must have too many releases.

Try to remove old releases (keep only 3 or 4 of the latest)
**wait for some hours, maybe some days** 
And everything will return to normal

**Comment by t4lpi** [comment]
> > +1
> > I have the same problem. I'm using windows too. Any solution?
> 
> Yes I think I found the reason : it's because of a size quota on your account.
> You must have too many releases.
> 
> Try to remove old releases (keep only 3 or 4 of the latest)
> **wait for some hours, maybe some days**
> And everything will return to normal

I'll give it a try! Thank you so much!

**Comment by kvarmajazeera** [comment]
IAgain the same problem, is there any solution ?

**Comment by mihaerzen** [comment]
@stephanebouget What kind of size quota are you talking about? Is this documented somewhere? We are using the Amazon S3 for our releases and we are facing this issue.

**Comment by kvarmajazeera** [comment]
We are using git hub for our releases and we are facing this issue.

**Comment by kvarmajazeera** [comment]
I'm using git hub for our releases and we also facing this issue(slow download).

**Comment by stephanebouget** [comment]
@mihaerzen

Hello,
here is my history of issues:
Everything worked correctly, then one day the updates started to download at 1kb/s
I had 10-15 releases with 5 files of 60-70MB, so more than 3-4GB

I tried to complete the update more than once and each time the update crashed with this message:
net :: ERR_HTTP2_PROTOCOL_ERROR
https://github.com/electron-userland/electron-builder/issues/4987

I add this code:
app.commandLine.appendSwitch ('disable-http2');
autoUpdater.requestHeaders = {'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age = 0'};
(not sure if it changes anything, and difficult to test)

After a lot of research and testing I came across this article:
https://stackoverflow.com/a/59675793/1737410

I then deleted the large files from my old releases (I stored them locally)
then a few hours after all returned to normal.

Since then I only keep my last 3-4 releases and everything works

PS: I think Github uses S3 servers so ...

**Comment by mihaerzen** [comment]
Sounds really weird that keeping only a few releases would make the speed of the auto update faster...

Anyway, I've tried it and actually keeped only 2 latest versions on our S3 bucket and this did not improve the download speed of the auto update (I've waited a few hours and tried it over the day multiple times just to make sure).

Our app is unfortunately a bit larger than 500MB as it comes bundeled with some videos.

Anyone has an idea where to start digging in the source code for clues?

**Comment by DekCode** [comment]
Btw, I got the same problem. It was soooooo slooooo. First I thought it was Azure blob container issue. I initially use this to set the download URL
`autoUpdater.setFeedURL(config.updateUrl);`

The way I fixed this is to remove the code above and set the URL in the `package.config` instead. Like this
```json
"build": {
    "productName": "My App",
    "appId": "com.my.app",
    "win": {
      "target": "nsis",
      "publish": {
        "provider": "generic",
        "url": "https://xx.blob.core.windows.net/downloads/"
      }
    }
  ```

**Comment by eccentricengine** [comment]
facing same issue

**Comment by codeofandrin** [comment]
> Btw, I got the same problem. It was soooooo slooooow. First I thought it was an Azure blob container issue. I initially used this to set the download URL `autoUpdater.setFeedURL(config.updateUrl);`
> 
> The way I fixed this is to remove the code above and set the URL in the `package.config` instead. Like this
> 
> ```json
> "build": {
>     "productName": "My App",
>     "appId": "com.my.app",
>     "win": {
>       "target": "nsis",
>       "publish": {
>         "provider": "generic",
>         "url": "https://xx.blob.core.windows.net/downloads/"
>       }
>     }
> ```

I added it to `electron-builder.yml` like this:

```yml
mac:
  publish:
    - provider: github
      protocol: https
      owner: <owner>
      repo: <repo>
```
But still very slow, I'm on macOS.

**Comment by agarny** [comment]
Has anyone managed to speed up the download of an update? My releases are on GitHub and, like someone else, to download from GitHub directly is fast, but through electron-updater it is super slow. This is very frustrating as it makes the auto update somewhat pointless.

Also, I have a progress bar to show the progress of the download and, for some reasons, it goes from 0% to 100% and once reaching 100% you would expect the update to be downloaded, but for some reasons it goes back to 0% and progresses a second time to 100%!?
