### ISSUE TITLE
appUpdater.quitAndInstall in Big Sur won't autoRestar 

### ISSUE THREAD

**Issue by klwfwdk** [electron-userland/electron-builder#5539]
* **Version**: 22.9.1

* **Electron Version**: 10.1.3
* **Electron Type (current, beta, nightly)**: current

electron-updater: 4.3.5

* **Target**:  electron:build -m --x64 

In mac os lastest version Big Sur, after call `appUpdater.quitAndInstall()` , app will be installed but won't auto restart. Same dmg file works will in mac os catelina,

**Comment by Fargard** [comment]
Same here

**Comment by brianpattison** [comment]
Just updated our app via `appUpdater.quitAndInstall()` on Big Sur and it did launch after quitting, but it happened over 4 hours after the app quit!

**Comment by sapkra** [comment]
Having the exact problem additionally with some popular apps like figma.
