### ISSUE TITLE
Unpack multiple directories with asar build option

### ISSUE THREAD

**Issue by epezhman** [electron-userland/electron-builder#554]
* **Version**: 5.10.2

* **Target**: Win32

Hey, I'm trying to unpack multiple directories with `asar `option in `build`, but it doesn't work. according to `asar `doc it should look like this` $ asar pack app app.asar --unpack-dir "{x1,x2}" `but when I try it in my` package.json` it unpacks nothing, is it possible? 

```
"asar": {
      "unpackDir": "{assets, node_modules}"
    },

```

**Comment by develar** [comment]
Why do you want to unpack the whole `node_modules`?

**Comment by develar** [comment]
In any case I will check this case. Am I right that you use two-package structure?

**Comment by epezhman** [comment]
Thank you, I only need to unpack a few modules not all, I  was just trying to get it up an running.
Yes I use the two package structure

**Comment by develar** [comment]
Works for me.

Your pattern is not correct — must be no space before `node_modules`: must be
```
"{assets,node_modules}"
```

**Comment by epezhman** [comment]
Thanks for comment, it's working alright without any space.

**Comment by epezhman** [comment]
@develar but I'm not clear on the proper way unpack is supposed work, for example when I unpack the `assets ` (like above), it's presented in 2 places, once in `app.asar.unpacked` and the other time in `app.asar,` is this normal or I'm doing something wrong? thanks

**Comment by develar** [comment]
> is this normal or I'm doing something wrong

Yes, it is normal. It just listed in the asar archive, but content is not copied (referenced instead).

**Comment by KevinGruber** [comment]
@develar
First really cool Project!

is it possible to change the name of app.asar.unpacked? Or to leave that folder out completly?

and as offtopic question, why is it not possible to have a http connection for autoUpdate?

Best regards,
Kevin

**Comment by develar** [comment]
> is it possible to change the name of app.asar.unpacked?

No. Or you can use `extraResources`/`extraFiles` to just pack files into app and use it externally.

> why is it not possible to have a http connection for autoUpdate?

Due to security reasons. Http is not secure.

**Comment by espositot** [comment]
Can I unpack using `asar` but to a different folder?  Unpacking seems to default to resources\app and that is not what I desire.  If not capable, how can I get folders and files moved to a different folder?
