### ISSUE TITLE
Generate new blockmap file

### ISSUE THREAD

**Issue by Francrodi** [electron-userland/electron-builder#5540]
* **Version**: 22.9.1

* **Electron Version**: 10.2.0

* **Electron Updater Version**: 4.3.5

* **Target**: NSIS

I want to display the progress of an update download. My problem is that i sign the exe with another software thus changing the hash of the installer .exe. The block map file generated by the builder now is not correct and i can't upload it so i just publish the signed exe and latest.yml (with new hash). When the aplication starts downloading the new version, it throws an error and defaults to full download instead of differential and no download-progress event is emitted.
Is there a way to generate a new block map file with the new exe i signed? Or maybe another way to get the progress of the download?

**Comment by Pragadesh-45** [comment]
Hey @Francrodi, I'm facing the same issue. Did you find any solution or workaround to fix this?

**Comment by Pragadesh-45** [comment]
@Francrodi, thanks for the update. I've currently switched to the custom sign function to make it work for now. However, it would be really helpful if we had an option to create a blockmap for Electron-builder separately
