### ISSUE TITLE
Inconsistent FileVersion and ProductVersion injected in App.exe and Uninstall App.exe

### ISSUE THREAD

**Issue by ivanggq** [electron-userland/electron-builder#5545]
* **Version**: 22.7.0

* **Electron Version**: 11.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

When building with NSIS, the **FileVersion** and **ProductVersion** version info fields are inconsistent between the main app executable and the uninstaller executable.
For example, if my package.json has:
```
"version": "3.1.0-debug.46"
```
the versions in App.exe and Uninstall App.exe will be:
* App.exe
  * FILEVERSION 3,1,0,0
  * PRODUCTVERSION 3,1,0,1
  * FileVersion (in StringFileInfo section) 3.1.0-debug.46.1
  * ProductVersion (in StringFileInfo section) 3.1.0.1
* Uninstall App.exe
  * FILEVERSION 3,1,0,1
  * PRODUCTVERSION 3,1,0,1
  * FileVersion (in StringFileInfo section) 3.1.0-debug.46.1
  * ProductVersion (in StringFileInfo section) 3.1.0-debug.46

<img width="958" alt="InconsistentVersions" src="https://user-images.githubusercontent.com/48165365/104635025-3d446200-5656-11eb-9183-b2ded18ba487.png">

Ideally, the versions should be:
* App.exe
  * FILEVERSION 3,1,0,46
  * PRODUCTVERSION 3,1,0,46
  * FileVersion (in StringFileInfo section) 3.1.0-debug.46
  * ProductVersion (in StringFileInfo section) 3.1.0-debug.46
* Uninstall App.exe
  * FILEVERSION 3,1,0,46
  * PRODUCTVERSION 3,1,0,46
  * FileVersion (in StringFileInfo section) 3.1.0-debug.46
  * ProductVersion (in StringFileInfo section) 3.1.0-debug.46

or as consistent as possible.

**Comment by LucaPaganin** [comment]
I have the same problem here!
And I am using the following versions

electron: "20.0.0"
electron-builder: "^23.6.0"
