### ISSUE TITLE
Is it possible to auto-update the app without using additional setup window on Windows?

### ISSUE THREAD

**Issue by gabyvlad96** [electron-userland/electron-builder#5546]
* **22.9.1**: 

* **Electron Version**: 11.2.0

* **Electron Updater**: 4.3.5

* **Target**:  NSIS

I am using electron-updater for my Windows app. Before installing the update, it will pop up an installer window just like the one used to install the app (basically the regular setup wizard).

Is there a feature to make this whole process run in the background without any installer window appearing? 
I would like the app to update by itself without the intervention of the user.

**Comment by Fraasi** [comment]
Haven't tried it myself, but maybe this will help.
> isSilent Boolean - windows-only Runs the installer in silent mode. Defaults to false.

https://www.electron.build/auto-update.html#module_electron-updater.AppUpdater+quitAndInstall
