### ISSUE TITLE
Can't create a universal build

### ISSUE THREAD

**Issue by XRenSiu** [electron-userland/electron-builder#5547]
* **Version**: 22.10.4

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: mac universal

`Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Info.plist" did not`

**Comment by mmaietta** [comment]
@quanglam2807 is this similar to what you were experiencing? https://github.com/electron-userland/electron-builder/pull/5481#issuecomment-749898441
What did you mean by unify the app.asar process?
>So in this case, we can opt to remove AsarIntegrity from Info.plist. Or we can unify the app.asar process for universal build.

Another thought is to disable for universal builds: `asarOptions == null || arch == Arch.universal`, but I'm not familiar with this usage of electron-builder
https://github.com/electron-userland/electron-builder/blob/ca20151c3416324d2413f451dea0c9e3853bab79/packages/app-builder-lib/src/platformPackager.ts#L229

**Comment by quanglam2807** [comment]
@mmaietta Yes, if we disable `asarIntegrity`, this would be fixed. This is the patch I'm currently using: https://github.com/webcatalog/translatium/blob/287d5221656dbe7a640a43052d051ea0c97eb66c/patches/app-builder-lib%2B22.10.4.patch
I'm not sure what it is used for but I'm disabling it in production and nothing breaks.

> What did you mean by unify the app.asar process?
I was thinking we could use the same `app.asar` file for all architectures, so the `archIntegrity` field is the same for all `Info.plist`. But now as I think about it, it's not a good idea as binaries in each `app.asar` would be compiled explicitly for each arch.
