### ISSUE TITLE
Massive Installer Size

### ISSUE THREAD

**Issue by nikhiljha** [electron-userland/electron-builder#555]
* **Version**: 5.10.2

* **Target**: win32 - x64

The installer the app generates is HUGE. (~100MB) for a fairly small app!

https://github.com/nikhiljha/nemwallet-desktop/releases

https://github.com/nikhiljha/nemwallet-desktop/

**Comment by develar** [comment]
Because your `package.json` is invalid.

1. `electron-prebuilt` must be in the `devDependencies`.
2. `postinstall` task only for two-package structure.

**Comment by nikhiljha** [comment]
I removed the postinstall task and moved electron-prebuilt to devDependencies and the file is still ~98MB.

Deleted my node_modules folder and reinstalled, same problem.

Thanks for helping!

**Comment by nikhiljha** [comment]
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 x64 using electron 0.36.12 to dist\win-unpacked

Mabye this is why?
They're separated in the config, but not for electron-builder.

**Comment by develar** [comment]
~100 MB unpacked

and 

~36 MB DMG

is the minimal size for Electron apps. All is ok. 

Your package.json is not correct, but it is unrelated issue.

**Comment by develar** [comment]
@nikhiljha Consider update electron-prebuilt to latest electron version — `1.2.5`

**Comment by develar** [comment]
Exe size — 52 MB. Yours — 98. Accept my PR and build again to check.
