### ISSUE TITLE
Can't use extraFiles that contain Universal binaries

### ISSUE THREAD

**Issue by IanMDay** [electron-userland/electron-builder#5552]
* **Version**: 22.10.4

* **Electron Version**: 11.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS Universal

I have universal binaries built from another project which I want to include via extraFiles, and have been doing so a while, but I've since updated builds to create Universal binaries.

I'm specifying the folder for the binaries as:

```
"extraFiles": [
  {
    "from": "binaries/${arch}",
    "to": "binaries"
  }
],
```

So the configuration only expects to find files in x64 and arm64 folders, so it only attributes these files to one of those architectures.

Ideally, it should either test the contents of the files given in either folder, or have a new configuration option for a 'universal' arch to indicate the files are already universal, or additionally search the universal arch as well as x64 and arm64.

I've resorted to splitting the binaries with `lipo -extract` for now so that builder is happy, but I don't think this is an ideal solution.

**Comment by XRenSiu** [comment]
I have x64 and arm64 binary built from another project, x64 need support macOS 10.13 and it includes `Frameworks/libswift*` , but arm64 doesn't include `Frameworks`

use `@electron/universal`, i get some error `While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds`

As @IanMDay said:
> or have a new configuration option for a 'universal' arch to indicate the files are already universal

that is great.

**Comment by Hinton** [comment]
I just encountered the same issue as @XRenSiu, we bundle a Safari extension inside the `extraFiles` which contains `Frameworks/libswift*` which are no longer used in `arm64`. Adding an option to inject `extraFiles` after combining it should solve it for us.

**Comment by XRenSiu** [comment]
Workaround
1. prepare universal `extralFiles`
2. use `after-sign` hook 

     -  copy `extraFiles` into packaged app
     - resign code
     
```
module.exports = async fucntion(packContext){
  const {
    appOutDir,
    outDir,
    packager
  } = packContext

  const appFile = path.join(
    appOutDir,
    `${packager.appInfo.productFilename}.app`
  )
  copy('<extraFile path>',path.join(appFile, 'Contents/Library/xxxxx/xxx.qlgenerator'))

  // resign
  await packContext.packager.signApp(packContext, true)
}
```

**Comment by IanMDay** [comment]
Yes, its still relevant.

**Comment by alectrocute** [comment]
+1. Currently stuck here.

**Comment by mmaietta** [comment]
Pretty sure any changes that could be made here for detecting whether a binary is already universal would be part of either @electron/electron-osx-sign or @electron/universal libraries.

I'd advocate for using this workaround
https://github.com/electron-userland/electron-builder/issues/5552#issuecomment-805615861

**Comment by alectrocute** [comment]
@mmaietta Thanks so much for your help. How are you "preparing your `extraFiles` for `universal`"? I have a `.node` native module that I `require("./src/release/Build/my_module.node")`. Am I supposed to use `electron-rebuild` to compile it for `universal`? Any ideas?

**Comment by Hinton** [comment]
It's still relevant. The only current work-around requires signing twice.

**Comment by alectrocute** [comment]
Thanks for keeping this ticket of @Hinton! As a side effect of this bug, I've become pretty proficient using `lipo` manually.

**Comment by IanMDay** [comment]
I ended up using lipo -extract to split the universal out to its distinct parts and place those files into the x64 and arm folders.

**Comment by pmstani** [comment]
So basically you didn’t add the binaries in the extraResources field of package.json, packaged as usual, then used lipo -extract, then placed the files manually? And then I guess you need to recombine the thing? Sorry if my question seems dumb, trying to understand how lipo works :/

Thanks!

**Comment by IanMDay** [comment]
My prebuilt universals get lipo extracted before the build into binaries/arm and binaries/ia64

```
lipo -extract arm64 myUniversalBinary -output binaries/arm64/myUniversalBinary
lipo -extract x86_64 myUniversalBinary -output binaries/x64/myUniversalBinary
```

Then included into the package with extraFiles:

```json
"extraFiles": [
    {
        "from": "binaries/${arch}",
        "to": "binaries"
    }
],
```

The builder then uses lipo to recombine them back again.

**Comment by pmstani** [comment]
Thanks that was very useful. I figured it out at the same time I received your reply, but I'm sure it'll be useful to many others!

**Comment by jtbandes** [comment]
Seems like this is fixed by https://github.com/electron/universal/pull/47 + https://github.com/electron-userland/electron-builder/pull/6913, if you put the file in the new `x64ArchFiles` allowlist.
