### ISSUE TITLE
32bit build showing blank screen, and 64 bit working fine.

### ISSUE THREAD

**Issue by atuljain2995** [electron-userland/electron-builder#5560]
* **Version**: 22.9.1

* **Electron Version**:11.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: "nsis"

When I'm packaging app for 32 bit it's showing blank screen, whereas on 64 bit it's working fine.

64-bit Version
![image](https://user-images.githubusercontent.com/40145665/105042135-e1c90880-5a89-11eb-8e7e-da005eae29c0.png)

32 bit version
![image](https://user-images.githubusercontent.com/40145665/105042169-eb527080-5a89-11eb-8c1f-592ff57ebd7e.png)

**Comment by fzcs** [comment]
+1，faced same issue

**Comment by atuljain2995** [comment]
Solution:

Go to .erb > Scripts > ElectronRebuild js file.

Add --arch=ia32 to node command.

After that inside src run "yarn electron-rebuild"

Than go to project folder and run "yarn electron-builder --win --ia32"

This way it will work.

**Comment by atuljain2995** [comment]
Closing as issue not longer exists.
