### ISSUE TITLE
Generate a configuration file with TypeScript

### ISSUE THREAD

**Issue by KaminoRyo** [electron-userland/electron-builder#5563]
Hi. The Electron-builder config file is so complicated that I hope it can be auto-completed using TypeScript.
Tired of typos and nesting mistakes.😔
But I can't find this information by google search.
I'm asking for information about this. Any information is welcome.

**Comment by cawa-93** [comment]
If you using comminjs, you can get auto-completed using jsdoc
```js
/**
 * @type {import('electron-builder').Configuration}
 * @see https://www.electron.build/configuration/configuration
 */
module.exports = {
  // ...
};
```

**Comment by mmaietta** [comment]
Holy crap, that's genius, thank you @cawa-93 ! Works great for me.

**Comment by nerdybeast** [comment]
@cawa-93 lifesaver man, this is even working from within Vue CLI Plugin Electron Builder and has saved me a bunch of time 👍

**Comment by mmaietta** [comment]
Quick note. Latest v24 alpha supports typescript config files 🙂

**Comment by jsadoski-rockhall** [comment]
Sorry to necro, but your linter could also easily integrate type checking for `electron.[js|cjs]` with the [`@ts-check`](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check) directive!

**Comment by drasern** [comment]
For those who stumble in here and want the quick solution

electron.config.ts
```
import type { Configuration } from "electron-builder";

const config = {
    ...
} satisfies Configuration;

export default config;
```

and don't forget to set the config on the cli with `electron-builder --config electron.config.ts`
