### ISSUE TITLE
Auto update doesn't work: `app-update.yml` is missing

### ISSUE THREAD

**Issue by AbbassKhan123** [electron-userland/electron-builder#5564]
{
  "name": "auto-update",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "electron-log": "^4.3.1",
    "electron-updater": "^4.3.4",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.5",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

### Error
**Auto update doesn't work: `app-update.yml` is missing**
### Operating System 
**Windows**

**Comment by muhammadaqibawaan** [comment]
Facing Same Issue

**Comment by UsmanGul** [comment]
facing same issue...

**Comment by PByH** [comment]
latest.yml for mac is missing (405 code) because electron-updater is trying to get this file via POST, but a few versions ago it used GET method. I'm not sure is there any setting to change this.
