### ISSUE TITLE
Asar creation fails on Apple Silicon

### ISSUE THREAD

**Issue by elliottkember** [electron-userland/electron-builder#5565]
* **Version**: 22.10.4
* **Electron Version**: 11.1
* **Electron Type (current, beta, nightly)**: current
* **Electron-updater (current, beta, nightly)**: current
* **Target**: arm64, x64
* **Node**: v15.3.0

Apologies if you get déjà vu here. I have been working through this puzzle after writing this PR, and have edited it to update my findings.

This is my package.json configuration: 

```
"target": [
  {
    "target": "default",
    "arch": [
      "arm64",
      "x64"
    ]
  }
],
```

When building for both architectures, electron-builder seems to sometimes choke on a specific, particularly large 6.8MB file in my node_modules on M1 (`node_modules/react-icons/gi/index.js`, an icon set). 

The line that causes this is [here](https://github.com/electron-userland/electron-builder/blob/5203d7eb15726605e8987aeed7a5ccedc8152e04/packages/app-builder-lib/src/asar/asarUtil.ts#L209), which has a comment linking to [bulk file reads](https://github.com/yarnpkg/yarn/pull/3539) and changed in [this commit](https://github.com/electron-userland/electron-builder/commit/b061710f0126700ea8860d7db78441e8c7fcede2) three years ago.

```js
// https://github.com/yarnpkg/yarn/pull/3539
const stat = metadata.get(file)
if (stat != null && stat.size < (2 * 1024 * 1024)) {
  // This part works reliably, even on files that are > 2 * 1024 * 1024
  readFile(file)
    .then(it => {
      writeStream.write(it, () => w(index + 1))
    })
    .catch(e => reject(`Cannot read file ${file}: ${e.stack || e}`))
}
else {
  // This part fails, without emitting the "error" event below, ending the process
  const readStream = createReadStream(file)
  readStream.on("error", reject)
  readStream.once("end", () => w(index + 1))
  readStream.pipe(writeStream, {
    end: false
  })
}
```

This seems to work okay on Github Actions and on my x64 Mac Mini. But running it on the Apple Silicon mac, it quits before turning Electron.app into my MyApp.app bundle, every time. 

I traced down into [copyAppFiles](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/app-builder-lib/src/platformPackager.ts#L208) in `platformPackager`,  which calls `AsarPacker#pack` and then `AsarPacker#writeAsarFile` ([here](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/app-builder-lib/src/platformPackager.ts#L321)) into the Bluebird queue - but that task is never resolved and the process simply exits. 

Adding logging to the `writeAsarFile` call shows that a large file (6.45MB) is somehow aborting the process during the `fsExtra.createReadStream` / `readStream.pipe(writeStream)` calls. No "error" event is emitted, the stream just goes away and the process terminates. I can't diagnose why this is, I have plenty of disk space, and I would expect something to throw an error.

Below is a log output of what I see when I add I'm logging `readStream start` before the readStream starts, and then on `readStream.on("end"` I log `readStream end`.

```
Written /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/go/index.esm.js
Written /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/go/index.js
Written /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/go/package.json
readStream start 6.37mb /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/gi/index.esm.js
readStream end /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/gi/index.esm.js
readStream start 6.45mb /Users/elliott/Sites/soulmate/ide/node_modules/react-icons/gi/index.js
✨  Done in 5.92s.
yarn run electron-builder -m  10.02s user 2.36s system 206% cpu 5.986 total
```

The resulting files look like this: one packed app, and one that hasn't finished.

![image](https://user-images.githubusercontent.com/42827/105139962-d7b80180-5aab-11eb-80e1-0a5a91b3ad0e.png)

I have made [a PR](https://github.com/electron-userland/electron-builder/pull/5567) that removes this second, `writeStream` functionality in favour of the first way, treating every file as though it is under 2MB. This makes compilation work reliably on my M1 mac. I would also think that changing the size threshold to be, say, 10MB would work similarly. 

I don't know if anybody else will hit this problem, but it is very very difficult to diagnose and took me many hours to piece through. This problem is possibly caused by something in the `fs-extra` package, or (because this only seems to happen when compiling for multiple architectures) by something tracking the number of asynchronous tasks (looking at AsyncTaskManager in particular). I haven't found anything backing up either assumption yet.

**Comment by wizebin** [comment]
It looks like `fs-extra` is just using `new fs.ReadStream` via a helper in `graceful-fs`

https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/index.js#L5
https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L312

What version of node are you using? Have you tried more than one?

**Comment by elliottkember** [comment]
> It looks like `fs-extra` is just using `new fs.ReadStream` via a helper in `graceful-fs`
> 
> https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/index.js#L5
> https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L312
> 
> What version of node are you using? Have you tried more than one?

I’m using v15.3.0. I’ll try to reproduce in others. 

What’s a little odd to me is that building these architectures separately seems to work fine, this specifically fails when building both architectures in one run. I haven’t been able to replicate it in a test case yet either which would be very helpful. 

Fortunately I’ve managed to get builds working on macOS 10.15 so the older macOS GitHub action works again and I am unblocked.

**Comment by elliottkember** [comment]
This issue has an easy fix and has been open for a while now - the PR is approved, could someone please merge it?
