### ISSUE TITLE
Cannot Pass gatekeeper at Big Sur mac

### ISSUE THREAD

**Issue by rentianhua** [electron-userland/electron-builder#5566]
electron-builder: 22.9.1
Electron : 9.3.1
Electron Type (current, beta, nightly): current
electron-updater: 4.2.5
electron-notarize: 1.0.0

Target: Mac dmg 

After packaging, I encountered a problem: for bigsur, it can't pass security detection, but for other old versions of Mac OS, it's OK;

My program has been notarized, but it seems to have no effect on Big sur.

Is there any suggestion?

**Comment by czzonet** [comment]
For me, electron 11 cannot pass only in Mac os 10.15.4.

**Comment by rentianhua** [comment]
> For me, electron 11 cannot pass only in Mac os 10.15.4.

my os is 11.1, but it was fine before 11.1, and i have referred the [](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/).

**Comment by OrganicChem** [comment]
You need to sign and notarize the .app INSIDE the dmg. The dmg does not have to be notarized, only the .app.

**Comment by czzonet** [comment]
> You need to sign and notarize the .app INSIDE the dmg. The dmg does not have to be notarized, only the .app.

You are rihgt.

dmg:{
        sign: false,
}
