### ISSUE TITLE
 Publish triggers afterAllArtifactBuild hook too late 

### ISSUE THREAD

**Issue by vcombey** [electron-userland/electron-builder#5568]
Version:
    - 22.9.1

    Target:
    - Windows

I'm writing an afterAllArtifactBuild hook where I sign the installer with EV certificates. but It looks like the publish command is not waiting for the afterAllArtifactBuild hook to finish. 
I end up with an exec file on s3 wich is not signed whereas the local exe file is signed.

does publish wait for afterAllArtifactBuild to complete?
Are there any workaround?

related issue #3908

**Comment by vcombey** [comment]
```
...
• publishing      publisher=S3 (bucket: spoke-app)
  • uploading       file=Spoke Setup 2.0.9.exe.blockmap provider=S3
  • uploading       file=Spoke Setup 2.0.9.exe provider=S3
calling /Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x86/signtool.exe with [
...```

the last line of log (calling my afterAllArtifactBuild hook) should appear before publishing

**Comment by mmaietta** [comment]
From what I'm reading in the code, `afterAllArtifactBuild` is explicitly before publishing can begin
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/index.ts#L62-L69

Can you try a newer electron-builder version? Pre-release is at 22.10.5

**Comment by prinkeeras** [comment]
I'm still getting this issue, was there a fix?
