### ISSUE TITLE
artifactName for "arm64" not working

### ISSUE THREAD

**Issue by andreacavagna01** [electron-userland/electron-builder#5569]
- "electron-builder": "~22.9.1",

- "electron": "~11.1.0",

-  "electron-updater": "^4.3.5",

* **Target**: "mac" 
  * **Arch**: "arm64"

If I try to build a version of macOS with arm64 architecture, I no have any effect in `artifactName` changing.

**Comment by jimmy-tfp** [comment]
I think you are supposed to use the branch 22.10. 
I am using `"electron-builder": "22.10.4"` with `"electron:mac-arm64": "npm run build:prod && electron-builder build --mac --arm64"` and its working

**Comment by mmaietta** [comment]
@jimmy-tfp is correct. Closing this ticket
