### ISSUE TITLE
Unable to build windows installer and getting Error: spawn mono ENOENT

### ISSUE THREAD

**Issue by gopikrishnaA** [electron-userland/electron-builder#557]
* **Version**: 5.10.2

* **Target**: Installers are not generated.

**_Unable to generate the windows installers getting this weird error._** 

build	01-Jul-2016 02:38:47	Warning: For windows consider only distributing 64-bit, see https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130
build	01-Jul-2016 02:38:47	Building Squirrel.Windows installer
build	01-Jul-2016 02:38:47	
error	01-Jul-2016 02:39:14	Error: spawn mono ENOENT
error	01-Jul-2016 02:39:14	    at exports._errnoException (util.js:870:11)
error	01-Jul-2016 02:39:14	    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
error	01-Jul-2016 02:39:14	    at onErrorNT (internal/child_process.js:344:16)
error	01-Jul-2016 02:39:14	    at nextTickCallbackWith2Args (node.js:442:9)
error	01-Jul-2016 02:39:14	    at process._tickCallback (node.js:356:17)
error	01-Jul-2016 02:39:14	From previous event:
error	01-Jul-2016 02:39:14	    at exec (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:45:10)
error	01-Jul-2016 02:39:14	    at /home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:242:47
error	01-Jul-2016 02:39:14	    at next (native)
error	01-Jul-2016 02:39:14	From previous event:
error	01-Jul-2016 02:39:14	    at releasify (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:258:16)
error	01-Jul-2016 02:39:14	    at /home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:144:32
error	01-Jul-2016 02:39:14	From previous event:
error	01-Jul-2016 02:39:14	    at build (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:161:16)
error	01-Jul-2016 02:39:14	    at Object.<anonymous> (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:82:13)
error	01-Jul-2016 02:39:14	From previous event:
error	01-Jul-2016 02:39:14	    at Object.createWindowsInstaller (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:92:16)
error	01-Jul-2016 02:39:14	    at SquirrelWindowsTarget.<anonymous> (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/src/targets/squirrelWindows.ts:32:33)
error	01-Jul-2016 02:39:14	    at next (native)
error	01-Jul-2016 02:39:14	    at /home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/fs-extra/lib/mkdirs/mkdirs.js:35:14
error	01-Jul-2016 02:39:14	    at FSReqWrap.oncomplete (fs.js:82:15)
error	01-Jul-2016 02:39:14	From previous event:
error	01-Jul-2016 02:39:14	    at tsAwaiter (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/src/util/awaiter.ts:10:47)
error	01-Jul-2016 02:39:14	    at Object.build (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/src/builder.ts:190:52)
error	01-Jul-2016 02:39:14	    at Object.<anonymous> (/home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/node_modules/electron-builder/src/build-cli.ts:25:28)
error	01-Jul-2016 02:39:14	    at Module._compile (module.js:409:26)
error	01-Jul-2016 02:39:14	    at Object.Module._extensions..js (module.js:416:10)
error	01-Jul-2016 02:39:14	    at Module.load (module.js:343:32)
error	01-Jul-2016 02:39:14	    at Function.Module._load (module.js:300:12)
error	01-Jul-2016 02:39:14	    at Function.Module.runMain (module.js:441:10)
error	01-Jul-2016 02:39:14	    at startup (node.js:139:18)
error	01-Jul-2016 02:39:14	    at node.js:968:3
error	01-Jul-2016 02:39:14	
error	01-Jul-2016 02:39:15	npm ERR! Linux 2.6.32-504.el6.x86_64
error	01-Jul-2016 02:39:15	npm ERR! argv "/opt/node-v4.4.0-linux-x64/bin/node" "/opt/node-v4.4.0-linux-x64/bin/npm" "run" "dist:win32"
error	01-Jul-2016 02:39:15	npm ERR! node v4.4.0
error	01-Jul-2016 02:39:15	npm ERR! npm  v2.14.20
error	01-Jul-2016 02:39:15	npm ERR! code ELIFECYCLE
error	01-Jul-2016 02:39:15	npm ERR! yeti-notify@1.0.53 dist:win32: `build --platform win32 --arch ia32`
error	01-Jul-2016 02:39:15	npm ERR! Exit status 255
error	01-Jul-2016 02:39:15	npm ERR! 
error	01-Jul-2016 02:39:15	npm ERR! Failed at the yeti-notify@1.0.53 dist:win32 script 'build --platform win32 --arch ia32'.
error	01-Jul-2016 02:39:15	npm ERR! This is most likely a problem with the yeti-notify package,
error	01-Jul-2016 02:39:15	npm ERR! not with npm itself.
error	01-Jul-2016 02:39:15	npm ERR! Tell the author that this fails on your system:
error	01-Jul-2016 02:39:15	npm ERR!     build --platform win32 --arch ia32
error	01-Jul-2016 02:39:15	npm ERR! You can get information on how to open an issue for this project with:
error	01-Jul-2016 02:39:15	npm ERR!     npm bugs yeti-notify
error	01-Jul-2016 02:39:15	npm ERR! Or if that isn't available, you can get their info via:
error	01-Jul-2016 02:39:15	npm ERR! 
error	01-Jul-2016 02:39:15	npm ERR!     npm owner ls yeti-notify
error	01-Jul-2016 02:39:15	npm ERR! There is likely additional logging output above.
error	01-Jul-2016 02:39:15	
error	01-Jul-2016 02:39:15	npm ERR! Please include the following file with any support request:
error	01-Jul-2016 02:39:15	npm ERR!     /home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/npm-debug.log
error	01-Jul-2016 02:39:15	
error	01-Jul-2016 02:39:15	npm ERR! Linux 2.6.32-504.el6.x86_64
error	01-Jul-2016 02:39:15	npm ERR! argv "/opt/node-v4.4.0-linux-x64/bin/node" "/opt/node-v4.4.0-linux-x64/bin/npm" "run" "release:win"
error	01-Jul-2016 02:39:15	npm ERR! node v4.4.0
error	01-Jul-2016 02:39:15	npm ERR! npm  v2.14.20
error	01-Jul-2016 02:39:15	npm ERR! code ELIFECYCLE
error	01-Jul-2016 02:39:15	npm ERR! yeti-notify@1.0.53 release:win: `npm run clean && npm run transpile && npm run dist:win32 && npm run dist:win64`
error	01-Jul-2016 02:39:15	npm ERR! Exit status 1
error	01-Jul-2016 02:39:15	npm ERR! 
error	01-Jul-2016 02:39:15	npm ERR! Failed at the yeti-notify@1.0.53 release:win script 'npm run clean && npm run transpile && npm run dist:win32 && npm run dist:win64'.
error	01-Jul-2016 02:39:15	npm ERR! This is most likely a problem with the yeti-notify package,
error	01-Jul-2016 02:39:15	npm ERR! not with npm itself.
error	01-Jul-2016 02:39:15	npm ERR! Tell the author that this fails on your system:
error	01-Jul-2016 02:39:15	npm ERR!     npm run clean && npm run transpile && npm run dist:win32 && npm run dist:win64
error	01-Jul-2016 02:39:15	npm ERR! You can get information on how to open an issue for this project with:
error	01-Jul-2016 02:39:15	npm ERR!     npm bugs yeti-notify
error	01-Jul-2016 02:39:15	npm ERR! Or if that isn't available, you can get their info via:
error	01-Jul-2016 02:39:15	npm ERR! 
error	01-Jul-2016 02:39:15	npm ERR!     npm owner ls yeti-notify
error	01-Jul-2016 02:39:15	npm ERR! There is likely additional logging output above.
error	01-Jul-2016 02:39:15	
error	01-Jul-2016 02:39:15	npm ERR! Please include the following file with any support request:
error	01-Jul-2016 02:39:15	npm ERR!     /home/cmbuild/bamboo-agent-home/xml-data/build-dir/CE-YEG12-JOB1/npm-debug.log

**_I am using following build configuration :_** 
"build": {
    "iconUrl": "http://eatodo.s3.amazonaws.com/icon.ico",
    "prune": true,
    "asar": true,
    "overwrite": true,
    "win": {
      "title": "yeti-notify",
      "icon": "./images/favicon.ico"
    },
    "osx": {
      "title": "yeti-notify",
      "icon": "./images/favicon.icns",
      "icon-size": 80,
      "contents": [
        {
          "x": 438,
          "y": 344,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 192,
          "y": 344,
          "type": "file"
        }
      ]
    }
  }

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux (install mono)

**Comment by develar** [comment]
> Is this issue due to wine?

wine and mono (see docs) are required.

NSIS doesn't require mono. Squirrel.Windows requires.
