### ISSUE TITLE
AutoUpdater gets stuck on Apple Silicon

### ISSUE THREAD

**Issue by harshithdwivedi** [electron-userland/electron-builder#5576]
* **Version**: 4.3.5

* **Electron Version**:12.0.0-beta.16
* **Electron Type (current, beta, nightly)**: beta

* **Target**: macOS M1

I'm building the app on my Apple Silicon Machine but the autoupdated stops at random point without any error while it's downloading the update.

Here's what the log looks like: 
```
41/818318083)
22:54:43.460 › downloading updates
22:54:43.465 › Download speed: 3931662 - Downloaded 50.51182731837541% (413347417/818318083)
```
On this run, the update got stuck at 50% whereas earlier it got stuck at 5%, 16%, and so on.

FYI, this runs without any issues on normal Intel Mac, so not sure what's causing this issue on the M1 machine.

**Comment by harshithdwivedi** [comment]
It is, it's just that there has been no update on the team on this one.

**Comment by mmaietta** [comment]
Hi there!
Two things:
- Can you update to the latest electron-updater and retry?
- Are you able to provide any network/console logs from the failure or is it just failing silently?
