### ISSUE TITLE
APK fails to install

### ISSUE THREAD

**Issue by aMytho** [electron-userland/electron-builder#5577]
* **Version**:  22.9.1

* **Electron Version**: 10.1.4
* **Electron Type (current, beta, nightly)**: Current

* **Target**:  apk

I'm trying to install an apk file on android. The .apk file builds successfully. I enabled installing apps from unknown sources in android settings. When trying to install the apk using the built in installer it says "There was a problem parsing the package" .
I tried other apk installers but they didn't work either. One gave me an error -status_failure_invalid
I don't know if that error was specific to that app or an issue with the apk file itself.  My app does work on other platforms (.exe on windows, .deb on linux) so I'm assuming the problem is with electron-builder.

Any help would be appreciated.

**Comment by HashandSalt** [comment]
@aMytho Did you ever find a solution to this? Im seeing the same issue with Electron 12.0.4 and Electron Builder 22.10.5.

Installing the apk on Android 9, i get the same problem parsing package message. APK was generated on Ubuntu Budgie 20.04

**Comment by aMytho** [comment]
Nope, never figured it out.

**Comment by sebastien247** [comment]
Any solution found? I'm encounter same problem

**Comment by HashandSalt** [comment]
My project no longer needed an APK build so i actually gave up fully investigation this. However, i think it was down to the APK being to large. Although it appeared to build correctly, the promblem lies in that Android studio uses a 32bit Zip library to compress the APK. As far as im aware 32 bit has limitiations on file size (the size of the resulting APK and each individual file in it). If you can switch your project to use the 64bit Zip, i dont think you will run into this.

How big is your project?

**Comment by rukshan-perera** [comment]
Any solutions for this issue?

**Comment by JIMhackKING** [comment]
I have the same issue.

* **Version**: 24.6.4

Electron Version: 26.1.0

Electron Type (current, beta, nightly): Current

Target: apk

I have tried installing it on Android emulators and my real phone, it says "There was a problem parsing the package". My electron project does work fine on Windows.

**Comment by Nick2bad4u** [comment]
Same issue here 

Is this even possible to get built for a modern android phone like an S24 ultra? 

Does it have to do with my phone supposedly only allowing apps built with support for arm64-v8a?
