### ISSUE TITLE
Windows signing error

### ISSUE THREAD

**Issue by limoragni** [electron-userland/electron-builder#558]
* **Version**: 4.2.1

* **Target**: Windows

I'm trying to sign the app using a SSL certificate. Is a certificate bought in https://dnsimple.com. I think is supposed to be a valid certificate, since its use is labelled ad any. Any SSL certificate is valid or if it has to be an especial one?

The error I'm getting is `No certificates were found that meet all the given criteria`

I'm trying to sign the app in my windows development computer and in Appveyor with no luck in any of the environments. I'm setting the variables CSC_LINK and CSC_KEY_PASSWORD. But I always get the same error. 

Thanks!

**Comment by develar** [comment]
Please use 5.10.3 and attach context of the error message (build log).

**Comment by develar** [comment]
> No certificates were found that meet all the given criteria
>  Any SSL certificate is valid or if it has to be an especial one?

No, must be code signing certificate. See https://github.com/electron-userland/electron-builder/wiki/Code-Signing#where-to-buy-code-signing-certificate
