### ISSUE TITLE
New version is not signed by the application owner (Windows)

### ISSUE THREAD

**Issue by xoancosmed** [electron-userland/electron-builder#5580]
* **Version**: 22.9.1 (electron-updater 4.3.5)

* **Electron Version**: 7.2.4

* **Electron Updater**: 4.3.5

* **Target**: Windows

- **Related issues already seen:**
  - https://github.com/electron-userland/electron-builder/issues/3667
  - https://github.com/electron-userland/electron-builder/issues/1856
  - https://github.com/electron-userland/electron-builder/issues/2790

---------

I've an Electron app with Electron Builder and Electron Updater for updating it. I've the autoUpdate working successfully with a generic server and self updating in Linux and Mac, but on Windows I'm receiving this error when trying to update:

```
Error: New version 0.6.9 is not signed by the application owner: publisherNames: <my_publisher_name_2>, raw info: {
    "SignertCertificate": {
        "FriendlyName": "",
        "IssuerName": {
            "Name": "CN=<my_company_ca>, DC=<ca_sld>, DC=<ca_tld>",
            "Oid": "System.Security.Cryptography.Oid"
        },
        "NotAfter": "/Date(1677661612000)/"
        "NotBefore": "/Date(1611565612000)/",
        "PrivateKey": null,
        "PublicKey": {
            "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
            "Oid": "System.Security.Cryptography.Oid",
            "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
            "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
        },
        "SerialNumber": "<...>",
        "SignatureAlgorithm": {
            "Value": "1.2.840.113549.1.1.11",
            "FriendlyName": "sha256RSA"
        },
        "Thumbprint": "<...>",
        "Version": 3,
        "Issuer": "CN=<my_company_ca>, DC=<ca_sld>, DC=<ca_tld>",
        "Subject": "CN=<my_publisher_name_1>, CN=<my_publisher_name_2>, OU=<ou_1>, OU=<ou_2>, DC=<sld>, DC=<tld>"
    },
    "TimeStamperCertificate": {
        "Archived": false,
        "Extensions": [
            "System.Security.Cryptography.X509Certificates.X509Extension",
            "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
            "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
            "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
            "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
            "System.Security.Cryptography.X509Certificates.X509Extension",
            "System.Security.Cryptography.X509Certificates.X509Extension",
            "System.Security.Cryptography.X509Certificates.X509Extension",
            "System.Security.Cryptography.X509Certificates.X509Extension"
        ],
        "FriendlyName": "",
        "IssuerName": {
            "Name": "<our_ca's_ca_stuff>",
            "Oid": "System.Security.Cryptography.Oid"
        },
        <...this_continues...>
    }
}
```

This is my electron-builder configuration for Windows:

```json
"win": {
      "asar": true,
      "target": ["nsis"],
      "publisherName": ["<my_publisher_2>"]
},
```

I also tested:

```json
"win": {
      "asar": true,
      "target": ["nsis"],
      "publisherName": ["<my_publisher_1>"]
},
```

```json
"win": {
      "asar": true,
      "target": ["nsis"],
      "publisherName": ["<my_publisher_1>", "<my_publisher_2>"]
},
```

```json
"win": {
      "asar": true,
      "target": ["nsis"],
      "publisherName": ["<my_company_ca>"]
},
```

All of them resulting in a `is not signed by the application owner` error. I think the problem comes from my certificate having two CN, but this certificate is provided to me as it's. However, I have already tested this code and it returns `<my_publisher_2>`:

https://github.com/electron-userland/electron-builder/blob/0ba839b72b6a13178ad5bc4b03a47f9aca980650/packages/app-builder-lib/src/winPackager.ts#L103

Also I want to mention that by adding the `"verifyUpdateCodeSignature": false` to my electron-builder config file of course it solves the problem and everything works fine, as it skips the verification, but I'd like to have that certificate validation.

Does anyone know what is happen or could give me any suggestion?

Thanking you in advance,
Xoán

**Comment by xoancosmed** [comment]
Any clue?

**Comment by Fishervjacob** [comment]
We're having this exact issue. Did you ever figure out a fix?

**Comment by 1GMX1** [comment]
I had the same problem, and the solution of this problem is remove "publisherName".
