### ISSUE TITLE
electron-builder outputs error: Compressor “xz” is not supported on Raspberry Pi

### ISSUE THREAD

**Issue by Alesvetina** [electron-userland/electron-builder#5584]
* **Version**: 22.8.1

* **Electron Version**: 10.1.2
* **Electron Type (current, beta, nightly)**:

Electron updater: 4.3.5

* **Target**: armv7l

When trying to run electron-builder build on Raspberry Pi 4 in my Angular app I get an error:
cannot execute  cause=exit status 1
errorOut=/home/pi/.cache/electron-builder/appimage/appimage-12.0.1/linux-arm32/mksquashfs: Compressor "xz" is not supported!
/home/pi/.cache/electron-builder/appimage/appimage-12.0.1/linux-arm32/mksquashfs: Compressors available:
gzip (default)

Windows builds OK.

The build options are:
```
"linux": {
  "artifactName": "App Setup.${ext}",
  "executableName": "App Name",
  "category": "Utility",
  "target": {
    "target": "appimage",
      "arch": [
       "armv7l"
      ]
  }
}
```

Why is this error present and how to successfully build for Raspberry Pi?
Thank you!

**Comment by 6XGate** [comment]
This is still not working. So still very much relevant. Especially as ARM is becoming more and more common.
