### ISSUE TITLE
Auto Updater does not work for Amazon S3 private Bucket

### ISSUE THREAD

**Issue by dmtask** [electron-userland/electron-builder#5587]
* **Version**: 
22.9.1

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:
11.1.0 (stable)

* **Target**: 
mac OS 11.1

* **Electron Updater Version**: 
4.3.5

I set my S3 to private (see screen 
<img width="1077" alt="Bildschirmfoto 2021-01-26 um 15 40 35" src="https://user-images.githubusercontent.com/17166931/105859665-16d6dd00-5fed-11eb-8080-28f9cce201c4.png">
) and then put the following in my update script:
```
.......
autoUpdater.on('checking-for-update', () => {
            if (w !== undefined) {
                w.get('settings').content().send('check-for-updates-begin');
            }

            let opts = {
                service: 's3',
                region: 'eu-central-1',
                host: s3_bucket + '.s3.eu-central-1.amazonaws.com',
                path: '/latest-mac.yml' // For example....
            };
            aws4.sign(opts, {
                accessKeyId: "XXXXX",
                secretAccessKey: "XXXXXXXX"
            });

            autoUpdater.requestHeaders = opts.headers;
        });
........
```

Unfortunately, I then get the following error:
```
Error: HttpError: 403 Forbidden
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

.....
```

Someone a solution for me?

**Comment by dmtask** [comment]
My solution:
I set the FeedUrl for autoUpdater `autoUpdater.setFeedURL('https://[BUCKET].s3.[REGION].amazonaws.com');`

**Comment by ash0x0** [comment]
Just a security PSA: This is a really really bad way to do it. AWS keys should be absolutely nowhere near your client in any capacity. Even if they're restricted to access these particular objects in this particular bucket only. 
It's actually better to turn off this specific bucket's public access blocking and set public ACL on the electron builder objects. In that case you can publish to and grab updates directly from the bucket without any special `autoUpdater` configuration. This bucket in effect becomes insecure so you would reserve it to this purpose only. Public and partially public buckets is something you can track access to, audit, control, and more importantly, nobody can do anything with it that you don't directly allow.
