### ISSUE TITLE
The publisher of the Windows Control Panel is blank

### ISSUE THREAD

**Issue by KazukiSugiyama107** [electron-userland/electron-builder#5590]
* **Version**: 22.7.0

* **Electron Version**:8.2.3
* **Electron Type (current, beta, nightly)**:4.3.4

* **Target**: Windows

### Issue Details
There is a part where "Publisher" is displayed on the screen for uninstalling the program in Windows, but it is blank.
Do you know the cause of this?

### To Reproduce
I have added the following property to `module.exports` of `vue.contig.js` and confirmed the operation.
・publisherName
・owner

・module.exports 
```
win: {
  icon: 'build/icons/xxx.ico',
  target: [
    {
      target: 'nsis-web',
      arch: [
        'x64',
        'ia32'
      ]
    }
  ],
  publish: {
    provider: 'generic',
    url: 'https://download.xxx.com/win',
    owner: ‘publisher name’
  },
  publisherName: 'publisher name',
},
```

### Screenshots
![Publisher](https://user-images.githubusercontent.com/70558785/104893494-d822a080-59b6-11eb-8641-2cd031ec48f7.png)

**Comment by davidkhanpk** [comment]
I am still facing this issue,
Electron Version: 15.3.1
electron-builder: 23.0.3
OS: Windows
