### ISSUE TITLE
CSC_INSTALLER_LINK environment variable isn't picked up

### ISSUE THREAD

**Issue by jwheare** [electron-userland/electron-builder#560]
* **Version**: 5.10.3

* **Target**: "mac": { "target": ["dmg", "zip", "mas"] }

When building for both `mac` and `mas` I have `CSC_LINK`, `CSC_KEY_PASSWORD`, `CSC_INSTALLER_LINK`, `CSC_INSTALLER_KEY_PASSWORD` set and using `CSC_IDENTITY_AUTO_DISCOVERY=false` to bypass my keychain because this will eventually be run on CI.

From looking at the code it seems like the `CSC_INSTALLER_LINK` environment variable isn't being used anywhere, and as a result I'm getting the error:

```
Error: Signing is required for mas builds but CSC_INSTALLER_LINK is not specified
```

This works fine with auto discovery, just not environment variables.

Also, is it possible to specify two separate `CSC_LINK` files, one for mas builds and one for non-mas. I intend to distribute our application both on the store and via our website. I guess two separate builds could be run from the command line with separate environment and target rules, but this seems cumbersome.

**Comment by develar** [comment]
Solution:
* Multi-file p12 must be supported.
* Use the same auto discovery logic on CI for created temp keychain instead of explicit identity resolving using openssl.

Will be fixed soon.

**Comment by develar** [comment]
`CSC_INSTALLER_LINK` supported restored. This issue remains open because of "is it possible to specify two separate CSC_LINK files".

**Comment by jwheare** [comment]
I'm excited!

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos

**Comment by jwheare** [comment]
I'm getting this error now (with only `CSC_LINK` and `CSC_KEY_PASSWORD` set):

```
Unhandled rejection Error: keychainName is null, but CSC_LINK defined
```

**Comment by develar** [comment]
@jwheare Fixed in the next release (will be in 20 minutes).

**Comment by jwheare** [comment]
Thanks, confirmed this is fixed.
