### ISSUE TITLE
Command "electron-builder" not found

### ISSUE THREAD

**Issue by gschafra** [electron-userland/electron-builder#5604]
* **Version**: v22.9.1

* **Electron Version**: v7.3.3
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows (32bit) with Node.JS v10.23.1 (32bit)

**Problem Description**
We're getting the error `Command "electron-builder" not found` when trying to run electron-builder from within a package.json script (`"electron:win-build": "yarn build:prod && electron-builder build --win --ia32"`) as it seems to be missing in the `node_modules/.bin` directory. 
![image](https://user-images.githubusercontent.com/3999582/106593359-007ed300-6551-11eb-89dd-f4abaebbd9c6.png)
Installing electron-builder globally, as suggested in #5410 and #3825, in our case is NOT an acceptable solution (using CI infrastrukture). In particular, the electron-builder docs recommends installing the package locally (using yarn, see https://www.electron.build/#installation), providing the "runner" in the `node_modules/.bin` directory, which is searched for by yarn (and npm?) automatically. In my case, this problem occured on a win agent (with yarn v1.22.5) and after upgrading electron-builder from v22.8.1 -> v22.9.1, which caused the electron-builder runner missing in the node_modules/.bin directory after a clean yarn install (whereby I cannot exclude that the runner existing until then was an artifact of a previous update/install). Any help on this is very much appreciated.

**Comment by mmaietta** [comment]
Out of curiosity, can you try this?
`yarn build:prod && yarn electron-builder build --win --ia32`

**Comment by gschafra** [comment]
I have already tried this without success. But the issue was solved by cleaning the yarn cache using (`yarn cache clean`) and installing with file checking option (`yarn install --check-files`). Seems to be caused by a corrupted yarn cache (which is shared in out CI environment) and thereby caused incomplete installation... weird... Thank's a lot @mmaietta for your fast reply.
