### ISSUE TITLE
makensis.exe exited with code 1

### ISSUE THREAD

**Issue by joseypan** [electron-userland/electron-builder#5606]
Recently, i did demo by electron-vue. It is normal which the enviroment is development, when i used the scrpit 'npm run build ' may cause error. If I keep the default configuration , it was success to build.When I changed some configuration in package.json about nsis,throw the error like the picture shows . 
I ask for your help,thanks!
![image](https://user-images.githubusercontent.com/68236258/106690157-22df1380-6586-11eb-9b30-4bf76827f84a.png)
Here are my configuration in package.json:
![image](https://user-images.githubusercontent.com/68236258/106690952-874ea280-6587-11eb-990c-69927b43f690.png)

**Comment by joseypan** [comment]
error:
Error: C:\Users\***\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=com.example.yourapp"
Command line defined: "APP_GUID=1fb8a7aa-e784-579d-a981-2142d5507b97"
Command line defined: "UNINSTALL_APP_KEY=1fb8a7aa-e784-579d-a981-2142d5507b97"
Command line defined: "PRODUCT_NAME=electron-project"
Command line defined: "PRODUCT_FILENAME=electron-project"
Command line defined: "APP_FILENAME=electron-project"
Command line defined: "APP_DESCRIPTION=An electron-vue project"
Command line defined: "VERSION=0.0.1"
Command line defined: "PROJECT_DIR=D:\electron\electron-project"
Command line defined: "BUILD_RESOURCES_DIR=D:\electron\electron-project\build"
Command line defined: "APP_PACKAGE_NAME=electron-project"
Command line defined: "MUI_ICON=D:\electron\electron-project\build\icons\happy.ico"
Command line defined: "MUI_UNICON=D:\electron\electron-project\build\icons\happy.ico"
Command line defined: "APP_64=D:\electron\electron-project\build\electron-project-0.0.1-x64.nsis.7z"
Command line defined: "APP_64_NAME=electron-project-0.0.1-x64.nsis.7z"
Command line defined: "APP_64_HASH=DF37DAF389C4EDBE8560C43921173F6507A89B275E3F02EDD8ECEA780553521615AD9A2E9CBE78C4ADBEF20027D673FFEF7BC4AB00F139FA9CD0F67B2E5802D9"
Command line defined: "COMPANY_NAME=533"
Command line defined: "APP_INSTALLER_STORE_FILE=electron-project-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "MULTIUSER_INSTALLMODE_ALLOW_ELEVATION"
Command line defined: "INSTALL_MODE_PER_ALL_USERS_REQUIRED"
Command line defined: "allowToChangeInstallationDirectory"
Command line defined: "SHORTCUT_NAME=electron-project"
Command line defined: "UNINSTALL_DISPLAY_NAME=electron-project 0.0.1"
Command line defined: "MUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "MUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "ESTIMATED_SIZE=179687"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=D:\electron\electron-project\build\.__uninstaller-nsis-electron-project.exe"
Processing config: C:\Users\UX.PRD\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)
warning: !warning: LangString "MULTIUSER_TEXT_INSTALLMODE_TITLE" for language Turkish is missing, using fallback from "C:\Users\***\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\Contrib\Language files\English.nsh" (macro:LANGFILE_SETSTRING:7)

Error output:
Error: warning treated as error

    at ChildProcess.<anonymous> (D:\electron\electron-project\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**Comment by joseypan** [comment]
Here are my configuration in package.json:
"win": {
      "icon": "build/icons/happy.ico",
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "license": "LICENSE.txt"
    },

**Comment by PotapIlya** [comment]
You have fixed this problem
