### ISSUE TITLE
Publishing NSIS Web to Bintray not supported provider error

### ISSUE THREAD

**Issue by Alexbay218** [electron-userland/electron-builder#5609]
* **Version**: 22.9.1

* **Electron Version**: 10.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows x64 & ia32 - NSIS Web

When looking to publish to Bintray via GitLab CI/CD, electron-builder throws 'Not supported provider: bintray' error. What is weird is that the other targets get published fine.

Here are a few screen shots:

CI/CD Log:

![image](https://user-images.githubusercontent.com/9091117/106816072-d3aae880-6642-11eb-9485-dc193e87add1.png)

Package.json:

![image](https://user-images.githubusercontent.com/9091117/106816192-0523b400-6643-11eb-9926-988419879187.png)

My first guess is that something in electron build is trying to upload it to an s3 style bucket. Is something specific to NSIS Web installer forcing it to do s3 bucket uploads only?

Full logs and source code available here:

CI/CD Log: https://gitlab.com/alexbay218/chess-in-5d/-/jobs/1006167011

Full Pipeline: https://gitlab.com/alexbay218/chess-in-5d/-/pipelines/251070078

Package.json: https://gitlab.com/alexbay218/chess-in-5d/-/blob/f7b509e329339ae5ac6290b8d1859339fb764eb3/package.json

Source Code: https://gitlab.com/alexbay218/chess-in-5d/-/tree/f7b509e329339ae5ac6290b8d1859339fb764eb3

**Comment by Alexbay218** [comment]
Note the build environment was using the electronuserland/builder:wine docker image. Not sure if that changes anything.

**Comment by Alexbay218** [comment]
How much money do I donate for this to get priority?

**Comment by NoahAndrews** [comment]
Bintray has been shut down, so this can be closed.
