### ISSUE TITLE
how to sign the uninstaller with my own sign script, is there a hook?

### ISSUE THREAD

**Issue by QiZeyun** [electron-userland/electron-builder#5610]
On Windows, I have to use my own sign server to sign my DLLS, installer and the uninstaller. 
And I find the hook "afterSign" which can be used to sign the unpacked directory with some scripts,  but I can`t find a hook to sign the uninstaller.exe,  is there a way to sign the uninstaller.exe using my scripts?

**Comment by mmaietta** [comment]
There is `win: { sign: () => {} }` that is available for custom signing
https://www.electron.build/configuration/win#how-do-delegate-code-signing
