### ISSUE TITLE
How to change appId (and productName) without breaking autoUpdater?

### ISSUE THREAD

**Issue by timche** [electron-userland/electron-builder#5614]
* **Version**: 22.9.1

* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, Linux, Windows

I want to rename an Electron app (packaged with `electron-builder`), but when I change the `appId` in `package.json` from e.g. `com.foo.x` to `com.bar.y`, Electron's built-in `autoUpdater` fails with:

```
Error: Error: Could not locate update bundle for com.foo.x within file:///Users/<username>/Library/Caches/com.foo.x.ShipIt/update.<random_hash>/
```

After searching for this issue, I only found [one other person](https://github.com/electron-userland/electron-builder/issues/4994) dealing with the same problem.

Neither the Electron nor the `electron-builder` docs are giving any hints or guide on how to change it. Is it even possible? I'd like to avoid to ask the users to download the update manually.

**Comment by shafayet2368** [comment]
@timche , could you solve this issue? .. I am facing the same problem for my app. Any help would be great..

**Comment by timche** [comment]
Yes, this is still relevant. To this date not solution was found or workaround was found yet, other than telling the users to manually re-install the app again.

**Comment by capc0** [comment]
@timche did you found a solution?

**Comment by prodkt** [comment]
+1 to looking for a solution.

**Comment by CamelCoder** [comment]
Any solution found for this issue?

**Comment by yonatand-vec** [comment]
+1 looking for a solution
