### ISSUE TITLE
Intel mac auto-updates to arm64 build. Bump in electron-updater?

### ISSUE THREAD

**Issue by elliottkember** [electron-userland/electron-builder#5616]
* **Version**: 22.10.4

* **Electron Version**: 11.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: arm64, x64, windows

I've been using electron-updater. Unfortunately I noticed that arm64 builds were being downloaded instead of Intel builds on an Intel mac. When I investigated, I found that my node_modules contained an out-of-date version of `electron-updater`, which didn't have any of the `"arm64"` code updates, and downloaded the `arm64` build on an Intel mac.

The version of `electron-updater` that's available on NPM is still 4.3.5, but the latest version in the code is 4.3.7. I also don't know how to install `electron-updater` from source since it's part of the monorepo. I think the 4.3.5 version on NPM may actually relate to multiple tags somehow.

Can we please get a bump of `electron-updater` on NPM to 4.3.7? It might be sufficient to document that `electron-updater` has to be v4.3.7 and up. Either way, I broke a bunch of installs so I'm trying to stop others having the same problem.

I'd like to move to a unified build eventually, but my app is a few hundred megabytes so I'm putting it off for now :)

**Comment by alectrocute** [comment]
I would imagine you have to release artifacts with `electron-updater@4.3.7` and then in the subsequent build, release `arm64` artifacts. If you do both in the same build, the client's version of `electron-updater` will be outdated as they perform an upgrade. Let me know if that was your issue here, thanks!

**Comment by bjbk** [comment]
How would I change my config for the proper arch to pull down to the proper client?
```
mac: {
          target: [
            {
              target: 'default',
              arch: 'x64'
            },
            {
              target: 'default',
              arch: 'arm64'
            }
          ],
          category: 'public.app-category.productivity',
          icon: 'src-electron/icons/icon.icns',
          hardenedRuntime: true,
          entitlements: 'src-electron/entitlements.mac.plist',
          entitlementsInherit: 'src-electron/entitlements.mac.plist'
        }
```

**Comment by bjbk** [comment]
I took a look at https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater version 4.3.7 and the update there should do as I wish?  Seems to do a check for arm64 when grabbing the update if I understand correctly.

**Comment by bjbk** [comment]
This worked!  Now my Intel installs get the x64 and M1's get arm64.  Build process is as above.

**Builder:**`v22.10.3`
**Updater:**`v4.3.7`

After running 2 separate build versions of my app, installing the first manually, the second updates as it should.

**config file**
```
      mac: {
          target: {
            target: 'default',
            arch: [
              'x64',
              'arm64'
            ]
          },
          category: 'public.app-category.productivity',
          icon: 'src-electron/icons/icon.icns',
          hardenedRuntime: true,
          entitlements: 'src-electron/entitlements.mac.plist',
          entitlementsInherit: 'src-electron/entitlements.mac.plist'
        },
        dmg: {
          sign: false,
          contents: [
            {
              x: 410,
              y: 150,
              type: 'link',
              path: '/Applications'
            },
            {
              x: 130,
              y: 150,
              type: 'file'
            }
          ]
        }
```

Then run publish as normally.  Clients grab the proper build.  (have not tested with Windows arm vs. x86. That is beyond the scope of this issue)

**Comment by romansp** [comment]
@bjbk We're struggling with the similar issue. Quick question: do you remember if `latest-mac.yml` file in that successful build was the same as in your comment before?

**Comment by bjbk** [comment]
@romansp yes, the file is the same.  And builds are still properly being fetched.

**Comment by mmaietta** [comment]
@bjbk would you be willing to use universal instead of two separate arch targets? Or do you need all 3 builds to be distributed. It seems that Electron-Updater is expecting the default path to be a universal build.
```
          target: [
            {
              target: 'default',
              arch: 'universal'
            }
          ],
```

Side note, electron-updater prerelease was updated to 4.3.8 in latest electron-builder prerelease 22.10.5
You'll need to manually run `yarn upgrade "electron-updater@^"` to access the latest prerelease version.

**Comment by bjbk** [comment]
@mmaietta Universal would be wonderful!  I'll change my target and update my packages.  Having a universal app build would save having to code sign 2 separate builds?  I'm in!

**Comment by bjbk** [comment]
**Follow up:** Universal build works just fine.  One build, less to upload to server, only one version to get code-signed.  Thank you @mmaietta for your help!

**Comment by mmaietta** [comment]
@elliottkember is this issue still valid using current prerelease versions or are further investigations needed?

**Comment by elliottkember** [comment]
> @elliottkember is this issue still valid using current prerelease versions or are further investigations needed?

I’ll check when I get a chance with the latest version, but the problem disappeared with 4.3.7 so unless there’s a regression I think it will be fine. 

I will also attempt to convert to a universal build. x86 and ARM should both auto update to universal right?

**Comment by mmaietta** [comment]
>I will also attempt to convert to a universal build. x86 and ARM should both auto update to universal right?

Hmmm that I can't confirm and don't have a manner to really test it either as my project doesn't use electron-updater. I was under the impression autoupdate to the default build when there's only one update file available (i.e. universal)

**Comment by bjbk** [comment]
> > @elliottkember is this issue still valid using current prerelease versions or are further investigations needed?
> 
> I’ll check when I get a chance with the latest version, but the problem disappeared with 4.3.7 so unless there’s a regression I think it will be fine.
> 
> I will also attempt to convert to a universal build. x86 and ARM should both auto update to universal right?

I have found that my builds pull down the proper update.  First run on Apple Silicon is slower but subsequent starts are quick as normally.  The builds show as universal in the System Information under software.

**Comment by lostdesign** [comment]
@elliottkember have you solved the issue? Do you have any repo to look into? I tried with `4.6.5` and it still occurs.
