### ISSUE TITLE
Cannot find module 'electron-updater' after build

### ISSUE THREAD

**Issue by MuLiequan** [electron-userland/electron-builder#5617]
**Version:**
  "electron": "^11.1.1"
  "electron-builder": "^22.9.1"
  "electron-updater": "^4.3.5"

![image](https://user-images.githubusercontent.com/20575376/107174066-45e54980-6a04-11eb-97bf-7cbc910f81c3.png)

When I run the development mode, electron-updater is imported well. But for some reason, after the build module was not found.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-updater'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_hku8A9/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.b.__esModule (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:8501)
    at b (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:270)
    at Object.<anonymous> (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:7047)
    at b (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:270)
    at Object.module.exports.Object.defineProperty.value (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:6543)

**Comment by mmaietta** [comment]
Hi @MuLiequan  What does your package.json look like?
Also might be worth trying latest electron-builder 22.10.5

**Comment by rezastallone** [comment]
I have the same problem, if i extract app.asar, no nodes_module found there, I think that is the cause, still has no idea how to pack nodes_module inside app.asar

**Comment by mmaietta** [comment]
Shot in the dark here. Can you double check that electron-updater is a prod dependency, not a devDependency? That could explain it working in dev but not getting packaged in prod builds.

**Comment by rezastallone** [comment]
For my case, `electron-pos-printer` is prod dependency, it works in dev but "Module not found" in prod build when i access it through remote `remote.require("electron-pos-printer")`

**Comment by MuLiequan** [comment]
> Hi @MuLiequan What does your package.json look like?
> Also might be worth trying latest electron-builder 22.10.5

I still get an error (Cannot find module 'electron-updater') when I use the latest electron-builder 22.10.5
My package.json :
"dependencies": {
    "axios": "^0.21.1",
    "blueimp-md5": "^2.18.0",
    "concurrently": "^5.3.0",
    "core-js": "^2.6.11",
    "cos-js-sdk-v5": "^0.5.22",
    "electron-packager": "^15.2.0",
    "electron-updater": "^4.3.5",
    "element-ui": "^2.13.0",
    "mta-h5-analysis": "^2.0.15",
    "native-ext-loader": "^2.3.0",
    "string-replace-webpack-plugin": "^0.1.3",
    "tim-js-sdk": "^2.8.0",
    "trtc-electron-sdk": "^8.0.1",
    "trtc-js-sdk": "^4.6.3",
    "vue": "^2.6.11",
    "vue-router": "^3.4.9",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-eslint": "^3.12.1",
    "@vue/cli-service": "^3.12.1",
    "babel-eslint": "^10.0.3",
    "babel-plugin-component": "^1.1.1",
    "electron": "^11.1.1",
    "electron-builder": "^22.10.5",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-loader": "^1.0.2",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by MuLiequan** [comment]
> Hi @MuLiequan What does your package.json look like?
> Also might be worth trying latest electron-builder 22.10.5

{
  "name": "name",
  "version": "1.1.0",
  "author": "author",
  "description": "description",
  "private": true,
  "main": "main.js",
  "scripts": {
    "watch": "vue-cli-service build --watch --trtc_env=development",
    "build:mac": "vue-cli-service build --trtc_env=production --target_platform=darwin",
    "build:win": "vue-cli-service build --trtc_env=production --target_platform=win32",
    "start": "concurrently \"npm run serve\" \"npm run electron \"",
    "serve": "vue-cli-service serve",
    "lint": "vue-cli-service lint",
    "electron": "node_modules/.bin/electron . --trtc_env=development",
    "compile:mac": "node_modules/.bin/electron-builder --mac --arm64",
    "compile:win64": "node_modules/.bin/electron-builder --win --x64",
    "compile:win32": "node_modules/.bin/electron-builder --win --ia32",
    "pack:mac": "npm run build:mac && npm run compile:mac",
    "pack:win64": "npm run build:win && npm run compile:win64",
    "pack:win32": "npm run build:win && npm run compile:win32"
  },
  "build": {
    "appId": "baby_home",
    "productName": "小宝之家",
    "icon": "src/assets/image/logo_index.png",
    "directories": {
      "output": "./bin"
    },
    "electronDownload": {
      "mirror": "https://npm.taobao.org/mirrors/electron/"
    },
    "extraFiles": [
      "node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node"
    ],
    "win": {
      "target": [
        "nsis",
        "zip"
      ],
      "extraFiles": [
        {
          "from": "node_modules/trtc-electron-sdk/build/Release/",
          "to": "./resources",
          "filter": [
            "**/*"
          ]
        }
      ]
    },
    "mac": {
      "extraFiles": [
        {
          "from": "node_modules/trtc-electron-sdk/build/Release/trtc_electron_sdk.node",
          "to": "./Resources"
        }
      ]
    },
    "publish": [
      {
        "provider": "generic",
        "url": "https://api.xiaobaozhijia.com/admin/static/file_pool"
      }
    ],
    "files": [
      "*.png",
      "dist/**/*",
      "*.js",
      "src/utils/updater.js",
      "!node_modules"
    ],
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true
    }
  },
  "dependencies": {
    "axios": "^0.21.1",
    "blueimp-md5": "^2.18.0",
    "concurrently": "^5.3.0",
    "core-js": "^2.6.11",
    "cos-js-sdk-v5": "^0.5.22",
    "electron-packager": "^15.2.0",
    "electron-updater": "^4.3.5",
    "element-ui": "^2.13.0",
    "mta-h5-analysis": "^2.0.15",
    "native-ext-loader": "^2.3.0",
    "string-replace-webpack-plugin": "^0.1.3",
    "tim-js-sdk": "^2.8.0",
    "trtc-electron-sdk": "^8.0.1",
    "trtc-js-sdk": "^4.6.3",
    "vue": "^2.6.11",
    "vue-router": "^3.4.9",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-eslint": "^3.12.1",
    "@vue/cli-service": "^3.12.1",
    "babel-eslint": "^10.0.3",
    "babel-plugin-component": "^1.1.1",
    "electron": "^11.1.1",
    "electron-builder": "^22.10.5",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-loader": "^1.0.2",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "vue-template-compiler": "^2.6.11"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by Veiintc** [comment]
has any thing update?I have the same problem

**Comment by OldManMeta** [comment]
This needs to be resolved. 

Im running v 5.3.0 and this is still happening.
