### ISSUE TITLE
Feature request: beforePack callback (or: using distributed Node version to run some scripts before packaging)

### ISSUE THREAD

**Issue by ravicious** [electron-userland/electron-builder#5619]
* **Version**: 22.9.1
* **Electron Version**: 11.3.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: darwin, windows

electron-builder already offers the `afterPack` callback. However, before all the files are packaged into an asar, I need to run [bytenode](https://github.com/OsamaAbbas/bytenode/) on some of them. Now, in order for bytenode to work properly, it needs to be executed [using the Node binary which will be distributed with the app](https://github.com/OsamaAbbas/bytenode/issues/73#issuecomment-745100734).

As of now, when I use asar, `afterPack` executes when the files are already in the asar archive. The current workarounds I came up with:

1. From within `afterPack` run code that will unpack asar, compile the files with bytenode and then create the asar archive again.
   * This already doesn't play well with `asarUnpack`, as extracting the asar archive into an `app` folder copies those unpacked files there as well. So before creating the archive again I would need to remove paths from `asarUnpack` from my `app` folder. But I worry that in the future it's going to cause problems with `smartUnpack` anyway.
2. Use `extraResources` so that the files which need to be compiled with bytenode are not in the asar archive at all. Then compile them in `afterPack`.
   * If those compiled files happen to require some node modules, then most probably I'd need to manipulate the `NODE_PATH` env variable so that Node knows where to find the modules (in the asar archive). I'm yet to check if this actually works.

With something like `beforePack`, I could run bytenode on selected files and then builder could just include them in the asar as usual, without needing to worry about `asarUnpack` and `smartUnpack` myself.

This is somewhat similar to #4600, but the author of that issue seems to have asked about sth like `afterPack`.

Perhaps there's a more straightforward way to solve my problem than `beforePack`, in which case I'd highly appreciate any advice!

**Comment by ravicious** [comment]
Welp, my 2nd workaround doesn't work, as `NODE_PATH` is used as a location of last resort if Node.js can't find `node_modules` with [its default algorithm](https://nodejs.org/docs/latest-v12.x/api/modules.html#modules_loading_from_node_modules_folders). In my case it'll "exit" the `dist` folder while looking for `node_modules` and stumble upon `node_modules` in my project's root directory, where it'll encounter node modules compiled for the wrong version of Node.

I'll need to try the first workaround and keep my fingers crossed that it won't break anything. Or perhaps try to do whatever it is that electron-builder is doing to obtain the version of Node that it's going to distributed with the app so that I can compile my app with bytenode before running electron-builder.

**Comment by ravicious** [comment]
Ok, so in the end I realized that I can run bytenode like this:

```
ELECTRON_RUN_AS_NODE=true $(npm bin)/electron script-which-compiles-stuff-with-bytenode.js
```

and it's in fact going to run bytenode with the same version that electron-builder is going to download. I thought that they may differ in some way, but for now I'm fine with risking that.

Leaving the issue open for future consideration.

**Comment by mmaietta** [comment]
@ravicious There is a `beforeBuild` hook that's available (and I think undocumented) and it runs before app dependencies are rebuilt/installed.
https://github.com/electron-userland/electron-builder/blob/v22.10.4/packages/app-builder-lib/src/packager.ts#L490
Would that work?

**Comment by davej** [comment]
I'm having a similar issue. `beforeBuild` doesn't work because I want the hook to be called after the dependencies have been installed. A `beforePack` would be ideal. In electron-forge I could use an `afterCopy hook`.

**Comment by davej** [comment]
Also see: https://github.com/electron-userland/electron-builder/issues/4422

**Comment by marcoancona** [comment]
Also see #5709

**Comment by davej** [comment]
Still relevant.

**Comment by alexweininger** [comment]
I would like to have this as well. 👍

**Comment by davej** [comment]
Still relevant.

**Comment by mmaietta** [comment]
Please look into opening a PR to contribute~
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
