### ISSUE TITLE
Build can't download zip file?

### ISSUE THREAD

**Issue by oliversturm** [electron-userland/electron-builder#5621]
* **Version**: 22.9.1

* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux

In a test setup, my build fails almost immediately due to an inexplicable download error:

```
> electron-builder

  • electron-builder  version=22.9.1 os=5.10.12-hardened1-1-hardened
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • description is missed in the package.json  appPackageFile=/<localfolder>/package.json
  • author is missed in the package.json  appPackageFile=/<localfolder>/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=11.2.3 appOutDir=dist/linux-unpacked
  ⨯ Get "https://github.com/electron/electron/releases/download/v11.2.3/electron-v11.2.3-linux-x64.zip": dial tcp: lookup github.com on [::1]:53: read udp [::1]:47868->[::1]:53: read: connection refused
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_amd64.s:1373
  ⨯ /<localfolder>/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
  Error: /<localfolder>/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/<localfolder>/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

Note that I substituted `<localfolder>` for the long local path where my project resides.

I'm not sure that the stack trace is very important, because the error seems clear enough: 

> Get "https://github.com/electron/electron/releases/download/v11.2.3/electron-v11.2.3-linux-x64.zip": dial tcp: lookup github.com on [::1]:53: read udp [::1]:47868->[::1]:53: read: connection refused

Unfortunately I have no detailed idea what's going on here. If I click the link right there in the terminal window, it opens in the browser and downloads the zip file. I can also `wget https://github.com/electron/electron/releases/download/v11.2.3/electron-v11.2.3-linux-x64.zip`, and it downloads the zip file immediately and without trouble. 

So - my guess is that the build process uses some arcane download mechanism that is somehow incompatible with my machine configuration. Any ideas how to debug or fix this?

**Comment by cnJayceon** [comment]
@oliversturm I have the same issue with you, can you tell me how did you solved this problem?

**Comment by oliversturm** [comment]
@cnJayceon I'm afraid the issue on my end was totally my fault back then - I didn't figure out exactly why, but there was an intermittent fault that broke DNS service for some applications. IIRC I ended up restarting the machine a little later due to some updates I needed, and the problem went away after that. Sorry I don't have anything better to say :)

**Comment by cnJayceon** [comment]
@oliversturm It is indeed a network error, thank you for your reply!

**Comment by HenryVolkmer** [comment]
No, its not a Networkfailure on your site.
`dial tcp: lookup github.com on [::1]:53: read udp [::1]:47868->[::1]` trys connection via IPv6. if your IPS/Home-LAN dont provide such a route, no connection can be established. You can verify that by:

- show, whether IPv6 is enabled: `sysctl net.ipv6.conf | grep disable_ipv6` (disable_ipv6 = 0 means enabled)
- /etc/sysctl.d/40-disable-ipv6.conf and set `net.ipv6.conf.all.disable_ipv6 = 1` 
- reboot/restart systemd-sysctl.service

now node use IPv4 for connection and everthing should work
