### ISSUE TITLE
Question: Is there a way to set the autoupdates url programmatically at runtime?

### ISSUE THREAD

**Issue by andi23rosca** [electron-userland/electron-builder#5629]
* **Version**:  22.9.1

* **Electron Version**: 8.4.1
* **Electron Type (current, beta, nightly)**: current

* **electron-updater**: 4.3.1

* **Target**: Windows

I have a use case where I would like to change the url the auto updates are looking at, at runtime, based on an environment variable.
I couldn't find any options for this in the docs, only build time ways to change it.
Is it possible to do it in some way?

**Comment by shahkeyur** [comment]
I think what you are looking for is, appUpdater.setFeedUrl(). You can find some docs [here](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+setFeedURL). They look bit confusing but probably you can check in editor, it takes one object with the options that you want to override.

**Comment by andi23rosca** [comment]
Wow I don't know how I missed it completely, looked over the docs 3 times before I wrote the issue.
Thanks for the help.
