### ISSUE TITLE
Squirrel.Windows unsupported

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#5632]
I am not using electron builder.

current

i don't use electron updater

None

Squirrel.windows is unsupported by electron-builder and just gets more and more unfair and frustrating. There is no way to add an icon without electron-builder. please add support

**Comment by mmaietta** [comment]
AFAIK, it is indeed supported, but just deprecated. Icons look to already be supported as well, it seems that Squirrel.windows cannot embed an icon but must reference an icon web URL?
https://www.electron.build/configuration/squirrel-windows
>Squirrel.Windows target is maintained, but deprecated. Please use nsis instead.
>
>To use Squirrel.Windows please install electron-builder-squirrel-windows dependency.
>
>iconUrl String - A URL to an ICO file to use as the application icon (displayed in Control Panel > Programs and Features). Defaults to the Electron icon.
Please note — local icon file url is not accepted, must be https/http.
If you don’t plan to build windows installer, you can omit it. If your project repository is public on GitHub, it will be https://github.com/${u}/${p}/blob/master/build/icon.ico?raw=true by default.
