### ISSUE TITLE
There are a ${isInstalled} like ${isUpdated} ? For detecting uninstall from a re-install (without uninstalling before)

### ISSUE THREAD

**Issue by fatoldsun00** [electron-userland/electron-builder#5633]
* **Version**: 21.2.0

* **Electron Version**: 7.3.2
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows (nsis)

Hi, 

I make a custom uninstall with an ExecWait. My problem occur when user re-install app without uninstall before. NSIS uninstall app (wonderfull) but this fire my custom uninstall script (not wonderfull). 

You manage this issue for updating with an ${isUpdated} var, there are something like that for detecting that uninstall is calling from an install ?

this is my code
```
!macro customUnInit
  ${ifNot} ${isUpdated}
    ExecWait '"$INSTDIR\${_AppExe}" --uninstaller --hidden' $0
    ${if} $0 = 2
      Abort
    ${EndIf}
  ${EndIf}
!macroend
```

Thanks

**Comment by mmaietta** [comment]
Could this macro `!insertmacro CHECK_APP_RUNNING` provide what you're looking for?
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L10

**Comment by fatoldsun00** [comment]
Thanks for response.

I would try, but if i look at name of macro it's seems that it's for verify if app is launch. I want to verify if uninstaller is launch from a new install or from user (by using windows panel). I want launch an app before uninstall but only if uninstall are launch from user (and not from a new install who uninstall before install)

By the way, how i use !insertmacro CHECK_APP_RUNNING ? it's return a boolean ?

Thanks again for your time
