### ISSUE TITLE
GitHub publisher doesn't require a PAT and documentation should reflect that

### ISSUE THREAD

**Issue by fuxingloh** [electron-userland/electron-builder#5636]
> Created it here because, I can't the documentation repo to make a PR to it.

---
In the documentation https://www.electron.build/configuration/publish#githuboptions

> GitHub personal access token is required. You can generate by going to https://github.com/settings/tokens/new. The access token should have the repo scope/permission. Define GH_TOKEN environment variable.

With the arrival of GitHub Actions, more and more users are running their CI and publishing on GitHub Actions. GitHub Actions comes with a repo scoped session bounded GITHUB_TOKEN and I believe that can be used instead of a PAT. 

I believe the documentation should reflect that as PAT should not be used due to its extended privileges. 

### Suggested copy 

> A Github Token is required. For GitHub Actions users, you can use the provided repo scoped secrets.GITHUB_TOKEN as the environment variable. Alternatively, you can generate a GitHub personal access token by going to https://github.com/settings/tokens/new. The access token should have the repo scope/permission. Define GH_TOKEN environment variable.

### Context & References
* https://github.com/electron-userland/electron-builder/issues/4883
* https://github.com/electron-userland/electron-builder/blob/master/packages/electron-publish/src/gitHubPublisher.ts
* https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
* https://github.com/samuelmeuli/action-electron-builder/blame/master/README.md#L42-L44

**Comment by mmaietta** [comment]
@fuxingloh a PR would be most welcome if you're willing and I can enable a quick review.

I haven't worked with the EB docs before/yet, but I think you should be able to locate it in `docs` branch
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation
