### ISSUE TITLE
build dmg file throw error

### ISSUE THREAD

**Issue by mebtte** [electron-userland/electron-builder#5643]
* **Version**: 22.9.1

* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

building dmg file will throw python error like this:
![image](https://user-images.githubusercontent.com/8120967/108360504-46fc4f00-722c-11eb-9b04-9f8572801488.png)

here is the error log:
[build.log](https://github.com/electron-userland/electron-builder/files/6002921/build.log)

and here is my repository(branch is site_setting):
[cicada_desktop](https://github.com/mebtte/cicada_desktop/tree/site_setting)

**Comment by mmaietta** [comment]
Can you try the pre-release version, electron-builder@22.10.5?

**Comment by mebtte** [comment]
> Can you try the pre-release version, electron-builder@22.10.5?

@mmaietta I tried and got same error, log is here: [build.log](https://github.com/electron-userland/electron-builder/files/6007290/build.log)

**Comment by mmaietta** [comment]
>IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info'

It seems you don't have access to some files?

**Comment by mebtte** [comment]
@mmaietta I changed the permission of this file and it works, thanks very much.
```bash
sudo chmod 777 /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
```
