### ISSUE TITLE
Auto-Update (NSIS Win) perMachine instillation triggered on secondary user account

### ISSUE THREAD

**Issue by Nealsoni00** [electron-userland/electron-builder#5644]
Hey everyone! I want to get an NSIS that I can install from an admin account that installed perMachine (all users) with auto-updating when any user is logged in. 

**What I am experiencing now:**
* I install the app with the configuration below using an admin account (User A) Windows 10. I then switch accounts to another user (User B) and trigger an auto-update of the application. It force closes the app and runs the auto-update script. However, before installing, this prompt appears asking User B to input the password of the original admin account (User A) that installed the app. Photo of that prompt is **Photo A** below. 

* Auto-update triggers in general on the original admin account (User A) prompt the user to confirm as well. This prompt does not happen when the `perMachine: false` is set. Photo of that prompt is **Photo B** below. 

**What I am trying to get**
A `perMachine` installation that does not require the original admin password to install the update and have that update persist across all users (or even update to a new user-specific copy that uses the user's local app data). Ideally, it would not prompt for user confirmation as it did in the two above photos (Neither prompts appeared with `perMachine: false` but instillation was only one the one account). 

Any advice on what to do would be amazing to get this auto-updating to work with `perMachine: true`

**PHOTO A: Auto-Update on Account B**
![auto-update issue](https://user-images.githubusercontent.com/7013191/108428372-73a06e80-720c-11eb-8cf8-5371435a741a.jpg)

**PHOTO B: Auto-Update on Account A**
![auto-update issue 2](https://user-images.githubusercontent.com/7013191/108428333-671c1600-720c-11eb-9b35-d7d542726c92.jpg)

---------------------------------------------

* **Electron Version**:
```
electron: "11.2.0", 
electron-builder: "22.9.1",
electron-updater: "4.3.5",
```
* **Target**: 
NSIS

* **Electron-builder Configuration**: 
```
win: {
  icon: 'assets/StoreLogo.png',
  publisherName: 'XXX',
  target: winTargets(),
  requestedExecutionLevel: "highestAvailable"
},
nsis: {
  oneClick: true,
  allowElevation: true,
  perMachine: true,
  createDesktopShortcut: 'always',
  createStartMenuShortcut: true,
  runAfterFinish: true
},
```
---------------------------------------------

Prior Research: https://github.com/electron-userland/electron-builder/issues/2363 --> Solution did not work when I tried (creating custom NSIS file & theoretically that issue was closed)

**Comment by Nealsoni00** [comment]
Wanted to follow-up to see if anyone was able to find a solution to this?

**Comment by imagineapps1** [comment]
@Nealsoni00 did you find a solution to this?
