### ISSUE TITLE
【electron-updater】How to get update cache directory

### ISSUE THREAD

**Issue by gebilaofan** [electron-userland/electron-builder#5646]
* **Version**:  ^22.9.1

* **Electron Version**: 11.1.1

* **Electron-updater Version**: 4.3.5

* **Target**:  windows

I want to get the cache path before updating, Some people see others get it in this way
```js
import { autoUpdater } from 'electron-updater'

autoUpdater.app.baseCachePath,
```
And then I saw a error
```
The property "app" is protected and can only be accessed in class "AppUpdater" and its subclasses.
```

I went and looked at the type declaration
```js
export interface AppAdapter {
  readonly baseCachePath: string;
}
```
So how do I get it?

**Comment by idanwork** [comment]
I have the same exact question were you able to solve it?

**Comment by gebilaofan** [comment]
@idanwork 
This is how I solve my problem, but it is not an effective way.

In `AppUpdater.d.ts`, remove the `protected` of `app` or use `autoUpdater.app.baseCachePath` like this `autoUpdater[app].baseCachePath`. But I think this is unreasonable.

Logically speaking, the app should be accessible by its class. I have also seen people using the app in other blogs.

Then I tried your way and it really works. But the cache paths of different platforms are different. This is more troublesome and you need to write them one by one.

Thank you, I can use this method first, this looks more reliable than modifying the type file

**Comment by mmaietta** [comment]
Spitballing here. Would either of these work? https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/lib/browser/api/app.ts#L68-L69
Maybe  `app.getPath('userData') + '-updater'`?

**Comment by gebilaofan** [comment]
@mmaietta
It doesn't look good. `app.getPath('userData')`Is the directory where Electron works, It is not the update cache directory of electronic Updater, It's under the `Local\${appNmae}-updater`directory

**Comment by mmaietta** [comment]
Dam. Well, I can't think of any harm in exporting a read-only baseCachePath or a getter for it. What you do with the path afterward is your own prerogative 😅 

Happy to review a PR if anyone is willing to open one up
