### ISSUE TITLE
Ubuntu app quit.

### ISSUE THREAD

**Issue by Gowebbi-Dev** [electron-userland/electron-builder#5647]
While developing the app is working in ubuntu but after the build, with electron-builder, the app is installed successfully but the app is quit immediately.  I wasn't able to figure out what is going on. Thank you if anyone able to help in this matter.

  ```
"Dependencies": {
    "dotenv": "^8.2.0",
    "electron": "^11.2.3",
    "electron-builder": "^22.9.1",
    "electron-reload": "^1.5.0",
    "lottie-web": "^5.7.6",
    "macaddress": "^0.5.1",
    "mssql": "^6.3.1"
  },
```
Ubuntu version is - 16.04.6

**Comment by mmaietta** [comment]
Can you try creating a sample repo to reproduce this? Not sure, from what you've posted, if this is specific to electron-builder
