### ISSUE TITLE
Failed to load resources: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ashishgarg624** [electron-userland/electron-builder#5649]
![issue](https://user-images.githubusercontent.com/55501690/108606505-65775d00-7388-11eb-984f-4ad7d78e8e5b.jpeg)

The version I am using
"electron": "^11.2.0",
"electron-builder": "^22.9.1",

Package.json
 "win": {
      "publisherName": "SnabbLab",
      "icon": "assets/icons/win/snabb256.ico",
      "publish": [
        "github"
      ],
      "target": [
        "nsis",
        "portable"
      ]
    },
"nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "assets/icons/win/snabb.ico",
      "installerSidebar": "assets/icons/win/snabb.bmp",
      "uninstallerSidebar": "assets/icons/win/snabb.bmp",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true
    },

ISSUE:

When I am running .exe file on window 7 32-bit. Some files upload and some files giving this error. But When I am checking in .asar file the error are there.  Please let me know how can I fix this.

**Comment by mmaietta** [comment]
That looks like a potential bundling error. Not sure what your code looks like, but any chance you're trying to access `app` from the renderer process without via `remote.app`?
Just to confirm, by "But When I am checking in .asar file the error are there", you mean that your files are indeed present in the asar?
