### ISSUE TITLE
Unable to exclude node_modules from build

### ISSUE THREAD

**Issue by vic-shihang-li** [electron-userland/electron-builder#5650]
* **Version**: 21.2

* **Electron Version**: 8.5.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

It appears to be impossible to exclude `node_modules` from the packaged `app.asar` file. With the following configuration:

```yaml
files:
  - "!**/node_modules/*"
  - "package.json"
  - // other relevant build files
```

I could still find `node_modules` when expanding `app.asar`.

Is it intentional that modules referenced in the source code are included in the build? The docs page says:

> package.json and **/node_modules/**/* (only production dependencies will be copied) is added to your custom in any case.

I hope to only include the `dist` folder generated by frontend frameworks (React, Angular, etc.) to the electron build, since these files should run in the browser as-is. It seems unnecessary to pack `node_modules`, which can be quite large.

If any one could share how to avoid packing unnecessary module files to the electron build, that would be highly appreciated. Thanks!

**Comment by mmaietta** [comment]
Can you try `!node_modules`?
