### ISSUE TITLE
How do I code sign my electron app with self signed certificate

### ISSUE THREAD

**Issue by einkal** [electron-userland/electron-builder#5651]
electron builder  20.44.4
electron - 8.x

target: 
"target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "signAndEditExecutable": true

I am using a self signed *.pfx certificate(created using power shell) for signing my electron app but am unable to get it signed. 
command used : 
set CSC_LINK=file://<path to certificate file> && set CSC_KEY_PASSWORD= <password> &&  rimraf installers && yarn build && electron-builder build --win"

Is there anything that i need to take care of? I am not quite aware of this process and am unable to find much clarity on the same.  Is the ssue with my certificate? I have added it to my trusted list.

**Comment by mmaietta** [comment]
I think setting these as indeterminate would disable signing by EB
```
set CSC_LINK=file:// && set CSC_KEY_PASSWORD=
```

Also might be worth adding 
`win: { forceCodeSigning: true }` to see if that's blocking it

**Comment by einkal** [comment]
Hey.. Thanks.. Fixed it.. The certificate I created had to be of type codesigning as I was using powershell command to generate the certificate..Its working fine.

I have multiple utilities though which I want to be signed. 
The custom sign.js needs to use a some code signing utility to do that?

**Comment by mmaietta** [comment]
> The custom sign.js needs to use a some code signing utility to do that?

Yes, you must provide your own.  There's a chance that it is exposed through electron-builder via the params in `win.sign` but you'll have to explore further there
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L59-L65

**Comment by czzonet** [comment]
The script to create self cert:

"electron-builder create-self-signed-cert -p self-signed-cert"

**Comment by einkal** [comment]
Thanks I used windows signtool to get my utilities signed thru the custom script.
