### ISSUE TITLE
recommend use yarn2 with node_modules

### ISSUE THREAD

**Issue by codeudan** [electron-userland/electron-builder#5653]
eslint and some plugin not work well when missing node_modules because can not find package，so I recommend use yarn2 with node_modules

just add nodeLinker: node-modules in yarnrc.yml link this, and need change some testing

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
nodeLinker: node-modules

@develar @mmaietta

**Comment by mmaietta** [comment]
Would you be willing to open a PR? I can provide a quick review.
