### ISSUE TITLE
Error. Please move 'build' into the development package.json

### ISSUE THREAD

**Issue by fairking** [electron-userland/electron-builder#5657]
* **Version**: ^22.10.5

* **Electron Version**: ^9.4.3
* **Electron Type (current, beta, nightly)**:

* **Target**: windows

Running the command: `vue-cli-service electron:build && electron-builder --windows`

I encouter the following error:
```
 INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=package.json ("build" field)
InvalidConfigurationError: 'build' in the application package.json 
(C:\Code\MyProject\src\MyProject.App.Cmu\dist_electron\bundled\package.json) is not supported since 3.0 anymore. 
Please move 'build' into the development package.json (C:\Code\MyProject\src\MyProject.App.Cmu\package.json)
    at checkMetadata (C:\Code\MyProject\src\MyProject.App.Cmu\node_modules\app-builder-lib\src\util\packageMetadata.ts:79:11)
    at Packager.build (C:\Code\MyProject\src\MyProject.App.Cmu\node_modules\app-builder-lib\src\packager.ts:331:5)
    at executeFinally (C:\Code\MyProject\src\MyProject.App.Cmu\node_modules\builder-util\src\promise.ts:12:14) {
  code: 'ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject.app.cmu@1.0.1 dist-windows: `vue-cli-service electron:build && electron-builder --windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject.app.cmu@1.0.1 dist-windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\romeo_f717rj8\AppData\Roaming\npm-cache\_logs\2021-02-24T20_08_35_495Z-debug.log
```

The exact sentence is: `code: 'ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION'`

My package.json is:
```
{
    "name": "myproject.app.cmu",
    "description": "My Project CMU",
    "author": "My Project CMU <contact@myproject.example.com>",
    "version": "1.0.1",
    "private": true,
    "scripts": {
        "serve": "vue-cli-service serve",
        "build": "vue-cli-service build",
        "test:unit": "vue-cli-service test:unit",
        "lint": "vue-cli-service lint",
        "lint-fix": "vue-cli-service lint --fix",
        "electron:build": "vue-cli-service electron:build",
        "electron:serve": "vue-cli-service electron:serve",
        "dist-linux": "vue-cli-service electron:build && electron-builder --linux rpm",
        "dist-linux-dev": "vue-cli-service electron:build --mode development && electron-builder --linux rpm",
        "dist-windows": "vue-cli-service electron:build && electron-builder --windows",
        "dist-windows-dev": "vue-cli-service electron:build --mode development && electron-builder --windows",
        "postinstall": "electron-builder install-app-deps",
        "postuninstall": "electron-builder install-app-deps"
    },
    "main": "dist_electron/bundled/background.js",
    "homepage": "./",
    "dependencies": {
        ....
    },
    "devDependencies": {
        "electron": "^9.4.3",
        "electron-builder": "^22.10.5",
        "electron-devtools-installer": "^3.1.1",
        "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
        ....
    },
    "build": {
        "appId": "com.myproject.cmu",
        "productName": "My Project CMU",
        "copyright": "Copyright © year ${author}",
        "win": {
            "target": "nsis",
            "icon": "public/img/icons/logo_256x256.ico"
        },
        "rpm": {
            "category": "Other"
        },
        "extraFiles": [
            {
                "from": "public/",
                "to": "resources"
            }
        ]
    }
}
```

Can someone please explain what does it mean? 

The documentation says nothing about that issue: 
- https://www.electron.build/
- https://www.electron.build/configuration/configuration

What does development package.json mean ?

Searched the entire internet :-)

Thanks

**Comment by mmaietta** [comment]
It's referring to this (dev vs application package.json's)
https://www.electron.build/tutorials/two-package-structure

As a separate approach, you could move your build configuration into an `electron-builder.js` config file. You can get type safety as well 🙂 
```
/**
* @type {import('electron-builder').Configuration}
* @see https://www.electron.build/configuration/configuration
*/
module.exports = {
        "appId": "com.myproject.cmu",
        "productName": "My Project CMU",
        "copyright": "Copyright © year ${author}",
        "win": {
            "target": "nsis",
            "icon": "public/img/icons/logo_256x256.ico"
        },
        "rpm": {
            "category": "Other"
        },
        "extraFiles": [
            {
                "from": "public/",
                "to": "resources"
            }
        ]
    }

```

**Comment by fairking** [comment]
> It's referring to this (dev vs application package.json's)
> https://www.electron.build/tutorials/two-package-structure
> 
> As a separate approach, you could move your build configuration into an `electron-builder.js` config file. You can get type safety as well 🙂

But the documentation says package.json? What do I do wrong?

![image](https://user-images.githubusercontent.com/13495631/109151692-6599a300-7762-11eb-8048-07ff48050015.png)

https://www.electron.build/configuration/configuration

**Comment by fairking** [comment]
electron-builder.js aproach gives me an error:
```
 Application entry file "background.js" in the "C:\Code\electron_test\dist\win-unpacked\resources\app.asar" does not exist. 
Seems like a wrong configuration.  stackTrace=
Error: Application entry file "background.js" in the "C:\Code\electron_test\dist\win-unpacked\resources\app.asar" does not exist. 
Seems like a wrong configuration.
at error (C:\Code\electron_test\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
```

Please find my repo: https://github.com/fairking/electron_test

**Comment by fairking** [comment]
Ok, just one more clarification because I am confused.

The error says: 
```
'build' in the application package.json. Please move 'build' into the development package.json
```

But based on the https://www.electron.build/configuration/configuration the development file is exactly where I had my build configuration. It is a root folder of my repository. Can someone please explain where exactly should my package.json be ?? :-(

**Comment by mmaietta** [comment]
Your electron-builder.js file name is incorrect and shouldn't be starting with a `.` 🙂 

Also, additional notes, you need an "author" entry in your package.json
```
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
```

Running `npm run dist-windows` gives me this error after the above changes:
```
⨯ Application entry file "background.js" in the "/electron_test/dist/win-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
```

**Comment by fairking** [comment]
> @mmaietta  Your electron-builder.js file name is incorrect and shouldn't be starting with a `.` 🙂

Ok. I fixed it. Now I got this:
![image](https://user-images.githubusercontent.com/13495631/109189645-297b3800-778c-11eb-94e4-1ea43483e5d9.png)

**Comment by fairking** [comment]
> Running `npm run dist-windows` gives me this error after the above changes:

Yes. This is another unsolved `electron-builder` issue: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/188

**Comment by fairking** [comment]
Alright. Looks like everything has been solved by amending the script to run build in package.json.
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/188#issuecomment-786163703

Thanks for your help @mmaietta 

Feel free to close the issue. But I do recommend to improve the docs as There is no clear info about where is the "build" config needs to be placed in my opinion.

**Comment by mmaietta** [comment]
Hmmm, that's not an electron-builder issue then. AFAICT, the "build" configuration is being _created_ by vue-cli-plugin-electron-builder, and passing that configuration along to electron-builder. Best guess, that plugin is creating a new package.json for the bundle and electron-builder is detecting multiple package.json files, so thus, the detection activates the two-package-structure.
