### ISSUE TITLE
Build errors on latest electron 11.3.0

### ISSUE THREAD

**Issue by supertiger1234** [electron-userland/electron-builder#5660]
* **Version**: 22.9.1 (latest)

* **Electron Version**: 11.3.0 (latest) I have issues only on this latest version.
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Windows 10 64 bit

So, I've been using this package called `extract-file-icon` which has been working fine until i updated my electron to 11.3.0.
I get errors when I build. Downgrading to any older version of electron makes it work again.

This is the error : 
`
npm ERR! gyp: C:\Users\Fishie\.electron-gyp\11.3.0\common.gypi not found (cwd: D:\Fishie\Desktop\test\node_modules\extract-file-icon) while reading includes of binding.gyp while trying to load binding.gyp
`

I have tried installing node-gpy, windows build tools and stuff but none helped since they are all already installed.

I have built a really simple app with instructions to reproduce this issue in the readme.md here:
https://github.com/supertiger1234/electron-11.3.0-gyp-fail

Thank you.

**Comment by hovancik** [comment]
@supertiger1234 how did you solve it?

**Comment by supertiger1234** [comment]
Using it on another computer worked fine. I tried to reinstall everything, node-gyp etc but nothing fixed it :/ but suddenly after few days, it's working again. No idea sorry.
