### ISSUE TITLE
"Cannot find module" for remote.require in Universal mac build

### ISSUE THREAD

**Issue by elliottkember** [electron-userland/electron-builder#5662]
* **Version**: 22.10.5

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Universal

When I build for Universal, the Universal build can't find `remote` libraries.

Code:
```
electron.remote.require("electron-is-dev");
```

```
Uncaught Error: Cannot find module 'electron-is-dev'
Require stack:
- /Users/elliott/Sites/soulmate/ide/dist/mac-universal/Soulmate.app/Contents/Resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249)
    at Module._load (internal/modules/cjs/loader.js:848)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at electron/js2c/browser_init.js:213
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213)
    at IpcMainImpl.emit (events.js:315)
    at IpcMainImpl.EventEmitter.emit (domain.js:483)
    at Object.<anonymous> (electron/js2c/browser_init.js:157)
```

It looks like it's looking in `app.asar` and not in `app-arm64.asar` for these node_modules. 

I tried this, and it worked:

```
window.electron.remote.require('../app-x64.asar/node_modules/electron-is-dev')
```

It looks as though the `window.electron.remote` is always running in `app.asar`. We may need to monkey-patch that function.

**Comment by elliottkember** [comment]
Note that this will only happen for you in testing if you include a node module that has different files between ARM64 and X64. The `serialport` module is an example of one that appears to be different between architectures.

I am testing out this rather hacky little workaround, which is tied in with some helpers for determining that this build is a Mac Release Electron build. No doubt there is a better way of doing this.

```
export const remoteRequire = (module) => {
  if (!isDev && isMac() && isElectron()) {
    const path = `../app-${remote.process.arch}.asar/node_modules/${module}`;
    return remote?.require(path);
  }

  return remote?.require(module);
};
```

**Comment by mmaietta** [comment]
Would something like this work? (Note: Didn't test, just winging it from a quick Google search)
```
const path = path.join(path.dirname(remote.app.getAppPath()), 'node_modules', module)
```

**Comment by elliottkember** [comment]
> However, even with this hack, the serialport module has stopped receiving data and I'm not sure why.

I ended up using `require('serialport');` instead of remote.require, and I enabled `nodeIntegration` in my app to do so. 

> Would something like this work?

Sadly no. This code:

```
console.log(
      "[a]",
      path.join(path.dirname(remote.app.getAppPath()), "node_modules", module)
    );
    console.log(
      "[b]",
      `../app-${remote.process.arch}.asar/node_modules/${module}`
    );
```

Produced this:

```
[a] /Users/elliott/Sites/soulmate/ide/dist/mac-universal/Soulmate.app/Contents/Resources/node_modules/electron-root-path
src.43be16c5.js:2312 
[b] ../app-x64.asar/node_modules/electron-root-path
```

Looks a lot like `remote.app.getAppPath()` is the main asar file.
