### ISSUE TITLE
Specifying a timestamp server causes error CSSMERR_TP_NOT_TRUSTED

### ISSUE THREAD

**Issue by ervinewell** [electron-userland/electron-builder#5666]
* **Version**: 22.2.0

* **Electron Version**: 7.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  zip,dmg

As our service cannot reach apple's timestamp server http://timestamp.apple.com/ts01, I specify a timestamp server http://timestamp.entrust.net/TSS/RFC3161sha2TS for codesigning, and this causes error CSSMERR_TP_NOT_TRUSTED when verifying the signature.（and http://apple.timestamp.com/ts01 works as my friends tested）
According to imformations we googled, we tried to install Developer ID Certification Authority and didn't work. Anybody knows why or other solutions?
![image](https://user-images.githubusercontent.com/11768033/109593472-006ff400-7b4c-11eb-8aeb-b44f552f8521.png)

**Comment by mmaietta** [comment]
I'm honestly not sure. Marking this as "help wanted" in hopes someone else knows the answer

**Comment by alectrocute** [comment]
Today, it appears Apple blocked or accidentally prevented access for Travis-CI's request to `timestamp.apple.com/ts01`, and attempting a workaround causes the same issue. It's still relevant.

**Comment by mmaietta** [comment]
You can specify a timestamp url AFAICT via this PR
https://github.com/electron-userland/electron-builder/pull/6074

Regarding server being blocked, I can't help there. 

Regarding certificate, can you confirm you have the Apple root/authority cert installed?

If this were truly a widespread issue, there would be far more reports of it.

**Comment by alectrocute** [comment]
@mmaietta It was a network issue on Apple's end. I reverted my workaround so this is no longer relevant to me – Disregard! Thanks!
