### ISSUE TITLE
NSIS: Extracting wrong archive

### ISSUE THREAD

**Issue by TomSeldon** [electron-userland/electron-builder#567]
* **Version**: 5.10.5

* **Target**: NSIS (ia32)

I seem to have found an issue whereby the NSIS installer is trying to extract the wrong archive. The affected code can be seen here: https://github.com/electron-userland/electron-builder/blob/00e8da89e94f45b413f469d52575398d9cfc296a/templates/nsis/installer.nsi#L82

```code
  ${If} ${RunningX64}
    Nsis7z::Extract "$PLUGINSDIR\app-64.7z"
  ${Else}
    Nsis7z::Extract "$PLUGINSDIR\app-32.7z"
  ${EndIf}
```

The specific issue is when targeting **only ia32**, but then trying to run the resultant installer on a **x64** machine. The above check assumes that if the current machine is x64 based, then the x64 installer will exist. In fact, only the ia32 version exists which it never tries to extract.

**The result** is that the installer runs "successfully", but actually just outputs nothing. It tries to extract a non-existent archive.

 My understanding (which may well be wrong) is that the ia32 installer should run on x64 machines, and so by targeting just ia32 it will just work on both architectures.

I've worked around this for now by targeting both ia32 and x64, however I don't think this should be necessary.

**Comment by develar** [comment]
Thanks for clear issue report. Fixed in 5.11.1.
