### ISSUE TITLE
how to verify the `Code Signing` is  authorized

### ISSUE THREAD

**Issue by liuestc** [electron-userland/electron-builder#5670]
* **Version**: 22.8.0
* **Electron Version**: ^8.3.0

I want to verify the new version Code Signing is authorized when i update? 

-----

now my condition is:

**OS**: WIN10

**old version**: code signing

**new version**: no code signing or code signing thief in updateServer

**actual results**： auto update install scuess

**expected results**： verify code signing and notify signing error

I install a old version that have Code Signing, I put a new version without  Code Signing to my updateServer,  when auto update,I want to verify the Code Signing is illegal ？ how to verify ?

**Comment by mmaietta** [comment]
Is this for Mac or Windows?
Mac requires a signature+notarization on newer OS versions, unsigned updates shouldn't be allowed at all.

**Comment by liuestc** [comment]
> Is this for Mac or Windows?
> Mac requires a signature+notarization on newer OS versions, unsigned updates shouldn't be allowed at all.

windows

**Comment by mmaietta** [comment]
Would this do the trick for ya?
>verifyUpdateCodeSignature = true Boolean - Whether to verify the signature of an available update before installation. The publisher name will be used for the signature verification.

Ref: https://www.electron.build/configuration/win
