### ISSUE TITLE
after update the latest version dosen't override the last version in the program list of windows

### ISSUE THREAD

**Issue by StitchC** [electron-userland/electron-builder#5671]
* **Version: 21.2.0**: 

* **Electron Version: 4.2.12**:
* **Electron Type (current, beta, nightly): 4.x latest**:

* **Windows**: 

after user update, the last version app are still in the program list on windows platform, this problem still in the latest version of electron-builder ? or this problem has been fixed ?

![image](https://user-images.githubusercontent.com/21286819/109787513-452d8500-7c49-11eb-8dad-8e46a8b4620b.png)

**Comment by mmaietta** [comment]
It sounds like you need to set the `win: { appId: <uuid string> }` which internally maintains the same GUID across installs/updates. To be backward compatible with your previous installation, you can identify the GUID with some registry exploration (Google search something like "windows guid registry")

**Comment by StitchC** [comment]
> It sounds like you need to set the `win: { appId: <uuid string> }` which internally maintains the same GUID across installs/updates. To be backward compatible with your previous installation, you can identify the GUID with some registry exploration (Google search something like "windows guid registry")

i have set the appId in the config filed, last two day, i found the way to resolve, when i upgrade the electron-builder to "22.7.0", this issue will resolved
