### ISSUE TITLE
Can I package native module into the build?

### ISSUE THREAD

**Issue by petekblaz** [electron-userland/electron-builder#5674]
I have an app that is using this module: https://www.npmjs.com/package/node-tesseract

Is there any way I can package that directly into the build, without the need for end user to install it seperately?

Thanks

**Comment by mmaietta** [comment]
If binaries exist for each different OS you're packaing for, then you can probably use one of these two:
>extraResources
extraFiles

Ref: https://www.electron.build/configuration/contents#extrafiles
