### ISSUE TITLE
CancellationToken class is no longer exported from electron-updater package

### ISSUE THREAD

**Issue by NilSet** [electron-userland/electron-builder#5675]
* **electron-updater Version**: 4.3.8

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current

In previous versions of electron-updater, the `CancellationToken` class accepted in `downloadUpdate` was exported from the `electron-updater` package. After the change in https://github.com/electron-userland/electron-builder/commit/d05a62b80368411e36db1e5e4c187c12272fed11#diff-696065e91abd75ef7fc5992339caf92ac5a4bb3625474c8cb04f94fd1953f39f we need to import it directly from the transitive dependency `builder-util-runtime`.

Given that this class is part of the external api of `electron-updater` the class should still be exported from there.

**Comment by mmaietta** [comment]
I agree with you, but I'm hoping I can get more context on the original changes first

@mastergberry, why was `export { CancellationToken } from "builder-util-runtime"` removed in your PR: https://github.com/electron-userland/electron-builder/pull/5515/files

**Comment by mastergberry** [comment]
Think this was a mistake to be honest...feel free to submit a quick PR to revert it.

**Comment by mmaietta** [comment]
No worries! Just wanted to double-check first 🙂
