### ISSUE TITLE
update Error: net::ERR_FAILED for AppImage generic provider

### ISSUE THREAD

**Issue by starhu521** [electron-userland/electron-builder#5678]
**Describe the bug**
I create a test project.

When I update my app with control, I got this error:
```
"Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)" 
```

**To Reproduce**
It's a new test app.
```
  vue create electron_update_test

  vue add electron-builder

  yarn add electron-updater

```
I build target AppImage for linux and publish provider: 'generic' with my local http server.

Then ` autoUpdater.checkForUpdates() `, I got "update-available":
```
{"version":"0.1.1","files":[{"url":"electron_update_test-0.1.1.AppImage","sha512":"d+gxf7ZnmgdaElt6fE0f+sG25jOdCEgBAcslSYjaXZEOiBoD/c3D/agzxcA/Z9X/7Xs0qOeiRTeFB8WJ2IebPQ==","size":77632041,"blockMapSize":82493}],"path":"electron_update_test-0.1.1.AppImage","sha512":"d+gxf7ZnmgdaElt6fE0f+sG25jOdCEgBAcslSYjaXZEOiBoD/c3D/agzxcA/Z9X/7Xs0qOeiRTeFB8WJ2IebPQ==","releaseDate":"2021-03-05T02:51:25.056Z"}
```
Then I call, ` autoUpdater.downloadUpdate() ` , I got an error from ` autoUpdater.on('error') `, the error is :
```
"Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23275495/110061593-ca787d00-7da2-11eb-88a7-726e942d43a1.png)

**Environment (please complete the following information):**
node: v12.16.2
yarn: v1.22.4
electron: 11.3.0
vue-cli-plugin-electron-builder: 2.0.0-rc.6
electron-builder: 22.10.5
electron-updater: 4.3.8
@vue/cli: 4.5.9

**Comment by mmaietta** [comment]
From a quick glance, that url doesn't look correct.
`"url":"electron_update_test-0.1.1.AppImage"`
Are you setting the feed URL correctly?

**Comment by starhu521** [comment]
> From a quick glance, that url doesn't look correct.
> `"url":"electron_update_test-0.1.1.AppImage"`
> Are you setting the feed URL correctly?

Yes, It is correct. And I test lots of ways.  And I also build target nsis for windows, there is no problems, update normally.
