### ISSUE TITLE
macOS Hardened runtime, timestamp & signed binary errors when notarizing

### ISSUE THREAD

**Issue by alexgurr** [electron-userland/electron-builder#5679]
* **Version**: 
^22.4.1

* **Electron Version**:
^8.2.1

* **Target**: 
mac DMG

I'm trying to build/notarize my app using electron builder (using `electron-notarize`), but every time I get the results back I get a consistent collection of errors.

**Package.json build looks like:**
```
"build": {
    "appId": "com.shootsta.project.timer",
    "productName": "Shootsta Project Timer",
    "directories": {
      "buildResources": "public"
    },
    "afterSign": "notarize.js",
    "mac": {
      "category": "public.app-category.productivity",
      "icon": "build/icon.icns",
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.plist",
      "target": [
        "dmg"
      ],
      "electronLanguages": [
        "en"
      ]
    }
  },
```

**notarize.js looks like:**
```
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
  const { appOutDir } = context;

  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    appBundleId: 'com.shootsta.project.timer',
    appPath: `${appOutDir}/${appName}.app`,
    appleId: process.env.APPLEID,
    appleIdPassword: process.env.APPLEIDPASS,
    ascProvider: process.env.APPLEASC
  });
};

``` 

**Entitlements:**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
  </dict>
</plist>
```

[Errors here](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma114/v4/28/cf/91/28cf9101-c313-bc1f-c378-cbb944806fbb/developer_log.json?accessKey=1615113105_6600295056711224524_Do1zbuEY9HNrpe5t2%2FHGLxV3TfqWdHEISaKBWEAF%2BJMWy66oVRhdRS0i1NDjfGih9P394jEFr4pNugWz5eii1Dr%2BuYXbnjA1jyqfcF5R%2Fg%2FrbFHB%2FZ08hw7fsj4C0%2FucM%2FMtt%2F%2F920lKWfM9qRXR7ROe4e3p7ZWlaRTVqJWFvTk%3D)

I have disabled signing through builder as per the instructions [here](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/) and [here](https://twitterarchiveeraser.medium.com/notarize-electron-apps-7a5f988406db), where apparently notarization needs to occur on an unsigned build. However the errors that come back then complain some modules aren't signed?

Not sure what else needs to be done from the electron-builder side. Any ideas?

**Comment by mmaietta** [comment]
Can you try using a separate `entitlementsInherit: 'build/child.entitlements'`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```

**Comment by bornova** [comment]
Hi @alexgurr,
Just as an alternative to `electron-notarize`, I have had great success using [electron-builder-notarize](https://github.com/karaggeorge/electron-builder-notarize) and following these instructions: 

https://samuelmeuli.com/blog/2019-12-28-notarizing-your-electron-app/

**Comment by alexgurr** [comment]
Hi Bornova - I tried this, however it doesn't work for me and I actually couldn't even get my artefact uploaded to the Apple servers.

I've now fixed this. Moving `hardenedRuntime` to the `mac` configuration, re-enabling the default signing + using the child entitlements worked.
