### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by ngprasad** [electron-userland/electron-builder#568]
* **3.17.0**: 

* **Mac**: 

I think there has been some problem after the package was recently published. It was working fine but since the past few days I am getting the following error:-
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 failed to proxy package JSON from remote : @develar/rcedit
npm ERR! 404 
npm ERR! 404 '@develar/rcedit' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'electron-packager-tf'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nischalp/dev/mamba_workspace/qbo-client/npm-debug.log

Please look into this asap.

Thanks,
Nischal

**Comment by develar** [comment]
It is an NPM error, package is published — https://www.npmjs.com/package/@develar/rcedit

Please upgrade to electron-builder 5.10.5

**Comment by ngprasad** [comment]
@develar I uninstalled and then installed electron-builder v5.10.5 as you mentioned but still getting the same error. Could you please explain if there are any additional steps thatI may need to do in order to resolve this?

**Comment by develar** [comment]
@ngprasad Please try to 

1. remove node_modules directory,
2. `npm cache clean`
3. `npm install`

**Comment by ngprasad** [comment]
Currently I am getting this error for all electron-builder versions > 3.10.0

**Comment by ngprasad** [comment]
Ok got it working. Thank you!

**Comment by develar** [comment]
@ngprasad rcedit accepted our patch and next release will not use `@develar/rcedit` anymore in any case.
