### ISSUE TITLE
can't use nsis 

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#5682]
* **Version**:  The latest version.

* **Electron Version**: Latest
* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis

Every time I run "npm run dist", i always get an error saying "
'build' is not recognized as an internal or external command,
operable program or batch file.".

**Comment by mmaietta** [comment]
Can you please post your package.json and your EB config?

**Comment by ChaoticRaccoon** [comment]
what EB config?

**Comment by mmaietta** [comment]
Whoops, sorry, I shouldn't abbreviate things randomly.

Would you be willing to post your package.json "scripts" and the electron-builder config?
