### ISSUE TITLE
when use ’certificateSubjectName‘ sign，  sha256 use sha1 Thumbprint

### ISSUE THREAD

**Issue by hxkuc** [electron-userland/electron-builder#5683]
* **Version**: 

22.10.1

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 
when use ’certificateSubjectName‘ sign，  sha256 use sha1 Thumbprint

when i use certificateSubjectName with EV Code Signing , i have two  certificate sha256 , sha1  

the problem is sha256 Thumbprint is same as sha1

**Comment by mmaietta** [comment]
Just curious, what target are you building for? I'm seeing the hash config is overwritten depending on extension:
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L43-L56
For instance: 
>For AppX `sha256` is always used.

**Comment by hxkuc** [comment]
![86DE3A0A-2417-4b9b-B877-C66124235922](https://user-images.githubusercontent.com/17510186/111146937-f545ab00-85c4-11eb-8364-4299a9661dbb.png)
