### ISSUE TITLE
Can build for mac-arm64 on an intel mac?

### ISSUE THREAD

**Issue by ye0jun** [electron-userland/electron-builder#5689]
* **Version**: latest

* **Electron Version**: 11.0.4 or 11.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac-silicon

Can build for mac-arm64 on an intel mac?

**Comment by mmaietta** [comment]
Yes. Please search for previous issues first in the future.

There's CLI approach using `--arm64` or for full universal use `--universal`

For build config, there is:
```
mac: {
  target: {
    target: 'default',
    arch: [
      'x64',
      'arm64'
    ]
  },
}
```
For universal builds, you can use: `"arch": "universal"` instead.

**Comment by Slapbox** [comment]
How does this work with native modules that need to support multiple architectures? Enabling `npmRebuild: true` in the config causes the error:

`Installation error: 'darwin-x64' binaries cannot be used on 'darwin-arm64v8' platform.

The prebuilt files exist for both architectures, but it doesn't seem like it works to rebuild as intended.

**Comment by mmaietta** [comment]
I think `npmRebuild` is true by default.
Do you need one of these two config vars?
`nodeGypRebuild: true` or `buildDependenciesFromSource: true`

**Comment by Slapbox** [comment]
This is my bad, and sorry for wasting time. Apparently there was some discrepancy in the dependency's docs about which version started supporting `arm64` prebuilts, and we were not on a late enough version.

**Comment by AxelTerizaki** [comment]
Okay, my bad, I didn't search for the right words and found some similar issues (like #5552). I'll look into these more.

**Comment by nuthinking** [comment]
This overrides to me the x64 dmg with arm64. It weirdly creates also a .zip version 🤷‍♂️

```json
"mac": {
  "target": [
    {
      "target": "default",
      "arch": [
        "x64",
        "arm64"
      ]
    }
  ],
}
```

**Comment by owilliams320** [comment]
Just leaving this for those that are configuring this with YAML. i couldnt find an example anywhere

```
mac:
  target:
    - target: 'default'
      arch:
        - x64
        - arm64
```
