### ISSUE TITLE
Letsencrypt Compatibility?

### ISSUE THREAD

**Issue by amilajack** [electron-userland/electron-builder#569]
The wiki recommends StartSSL for code signing. Will a [letsencrypt](https://letsencrypt.org/) certificate work as well? This would be a great alternative.

**Comment by develar** [comment]
Any code sign certificate will work to sign windows app. If you need to sign mac app, you will need to export root letsencrypt  cert in addition to (https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos).

**Letsencrypt is not a code sign certificate** and cannot be used to sign —  https://community.letsencrypt.org/t/code-signing-certificates/815/5
