### ISSUE TITLE
xorriso failure when building AppImage

### ISSUE THREAD

**Issue by jwheare** [electron-userland/electron-builder#570]
* **Version**: 5.11.2

* **Target**: Linux, AppImage

Here's a build log: https://travis-ci.org/irccloud/irccloud-desktop/jobs/143193841

Any ideas?

`Error: Command failed: xorriso -joliet on -volid AppImage -dev /home/travis/build/irccloud/irccloud-desktop/dist/IRCCloud-0.1.9.AppImage -padding 0 -map /home/travis/build/irccloud/irccloud-desktop/dist/linux /usr/bin -map /home/travis/build/irccloud/irccloud-desktop/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/IRCCloud.desktop /irccloud-desktop.desktop -move /usr/bin/IRCCloud /usr/bin/irccloud-desktop -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_16x16x32.png /usr/share/icons/default/16x16/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_24x24x32.png /usr/share/icons/default/24x24/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_32x32x32.png /usr/share/icons/default/32x32/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_48x48x32.png /usr/share/icons/default/48x48/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_64x64x32.png /usr/share/icons/default/64x64/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_96x96x32.png /usr/share/icons/default/96x96/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_128x128x32.png /usr/share/icons/default/128x128/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_256x256x32.png /usr/share/icons/default/256x256/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_512x512x32.png /usr/share/icons/default/512x512/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-3mc-iqcxj20u-1/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /`

```
xorriso 1.1.8 : RockRidge filesystem manipulator, libburnia project
xorriso : FAILURE : Not a known option:  '-move'
xorriso : FAILURE : Not a known option:  '/usr/bin/IRCCloud'
xorriso : FAILURE : Not a known option:  '/usr/bin/irccloud-desktop'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
xorriso 1.1.8 : RockRidge filesystem manipulator, libburnia project.
xorriso : FAILURE : Not a known option:  '-move'
xorriso : FAILURE : Not a known option:  '/usr/bin/IRCCloud'
xorriso : FAILURE : Not a known option:  '/usr/bin/irccloud-desktop'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
```

**Comment by develar** [comment]
```
develar-home-imac:electron-builder develar$ xorriso --version
GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

GNU xorriso 1.4.4
ISO 9660 Rock Ridge filesystem manipulator and CD/DVD/BD burn program
Copyright (C) 2015, Thomas Schmitt <scdbackup@gmx.net>, libburnia project.
xorriso version   :  1.4.4
```

Your xorriso is outdated, please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#travis-linux

Or, just use our docker image! https://github.com/electron-userland/electron-builder/wiki/Docker It is not easy way, but reliable.

**Comment by jwheare** [comment]
On trusty and xorriso 1.3.2 now:

https://travis-ci.org/irccloud/irccloud-desktop/jobs/143383587

`Error: Command failed: xorriso -joliet on -volid AppImage -dev /home/travis/build/irccloud/irccloud-desktop/dist/IRCCloud-0.1.9.AppImage -padding 0 -map /home/travis/build/irccloud/irccloud-desktop/dist/linux /usr/bin -map /home/travis/build/irccloud/irccloud-desktop/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/IRCCloud.desktop /irccloud-desktop.desktop -move /usr/bin/IRCCloud /usr/bin/irccloud-desktop -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_16x16x32.png /usr/share/icons/default/16x16/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_24x24x32.png /usr/share/icons/default/24x24/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_32x32x32.png /usr/share/icons/default/32x32/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_48x48x32.png /usr/share/icons/default/48x48/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_64x64x32.png /usr/share/icons/default/64x64/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_96x96x32.png /usr/share/icons/default/96x96/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_128x128x32.png /usr/share/icons/default/128x128/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_256x256x32.png /usr/share/icons/default/256x256/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_512x512x32.png /usr/share/icons/default/512x512/apps/irccloud-desktop.png -map /tmp/electron-builder-linux-57u-iqdzq6fp-1/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /`
```
xorriso 1.3.2 : RockRidge filesystem manipulator, libburnia project.
xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Drive current: -dev '/home/travis/build/irccloud/irccloud-desktop/dist/IRCCloud-0.1.9.AppImage'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 16.5g free
New volume id: 'AppImage'
xorriso : UPDATE : 67 files added in 1 seconds
Added to ISO image: directory '/usr/bin'='/home/travis/build/irccloud/irccloud-desktop/dist/linux'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/AppRun'='/home/travis/build/irccloud/irccloud-desktop/node_modules/electron-builder/templates/linux/AppRun.sh'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/irccloud-desktop.desktop'='/tmp/electron-builder-linux-57u-iqdzq6fp-1/IRCCloud.desktop'
xorriso : FAILURE : Cannot find path '/usr/bin/irccloud-desktop' in loaded ISO image
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
```

**Comment by develar** [comment]
If you can wait 14 hours, I will bundle xorriso tomorrow, or you can try docker. But if you are familiar with docker, it is not easy.

**Comment by jwheare** [comment]
Happy to wait, thanks. I'm completely unfamiliar with docker, so probably even less easy!

**Comment by jwheare** [comment]
Thanks, that did the trick.

**Comment by Xstoudi** [comment]
I've got the same error, logs : 
https://travis-ci.org/Xstoudi/alduin-test-ci/jobs/182545357

**Comment by develar** [comment]
@Xstoudi Your issue is different — "xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-0c2rOC/0-1-linux.iconset/icon_512x512x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'"
