### ISSUE TITLE
electron-builder fails with codesign error

### ISSUE THREAD

**Issue by manngo** [electron-userland/electron-builder#5702]
* **Version**: electron-builder  version=21.2.0 os=20.3.0

* **Electron Version**: 12.0.1
* **Electron Type (current, beta, nightly)**:

* **Target**: macOS

I was having trouble with one of my modules, and decided to update everything:

```
ncu -u
npm install
```

I had also inadvertently deleted the electron module (it was in an old directory) and reinstalled it:

```
npm install electrom
```

Now when I try running `npx electron-builder build` I get the error:

```
Command failed: codesign …
```

(I’m not sure how much of the message I need to include here). It appears there is an issue with Electron Framework not being signed. The thing is, I don’t remember doing any code signing.

How can I fix this?

**Comment by mmaietta** [comment]
Isn't electron supposed to be a `devDependency`? If it's a `dependency`, then electron-builder will throw an error on latest versions.
Also, would you be willing to try repro-ing this on the latest prerelease version, 22.10.5? It'd help in triaging this
