### ISSUE TITLE
electron-builder custom NSIS include script macro not working

### ISSUE THREAD

**Issue by alokmahor** [electron-userland/electron-builder#5704]
* **Version**: 22.10.5

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 10

I have created a [electron][1] desktop app and created a installer using [electron-builder][2].

Now I want to try macro like `customInstall` and `customUnInstall`

My `installer.nsh` file is
```
!macro customInstall
  MessageBox MB_OK "Test output 1"
!macroend

!macro customUnInstall
  MessageBox MB_OK "Test output 2"
!macroend
```

My `electron-builder` config is 
```
"build": {
    "nsis": {
      "include": "installer.nsh"
    },
    "mac": {
      "icon": "build/icon.png"
    },
    "win": {
      "icon": "build/icon.png"
    }
  }
```

But this is not working for me.  
What I am missing to make it working?

  [1]: https://www.electronjs.org
  [2]: https://www.electron.build/

**Comment by mmaietta** [comment]
Why did you create two tickets for the same electron builder config with the same request for customInstall and customUnInstall. If this one isn't working, then neither would the other installer script.

Looking at the code, it seems the installer.nsh is explicitly required to be a path relative to your project dir or resources dir. Can you confirm that you're configured correctly?
https://github.com/electron-userland/electron-builder/blob/8df250b4645924942883ba6ad1418da994116521/packages/app-builder-lib/src/platformPackager.ts#L566-L578

**Comment by alokmahor** [comment]
I have confirmed that `installer.nsh` is working by introducing error in that.

**Comment by GeorgeFlorian** [comment]
I also have this issue !
