### ISSUE TITLE
A JavaScript error occurred in the main process, Error: The specified module could not be found.

### ISSUE THREAD

**Issue by alokmahor** [electron-userland/electron-builder#5707]
* **Version**: 22.10.5

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 10

On my laptop installer is working fine but on my friends laptop I am seeing error when app opens after installation

```
A JavaScript error occurred in the main process
 
Uncaught Exception:
Error: The specified module could not be found.
\\?C:\some\path\My-Electron-App\resources\app.asar.unpacked\node_modules\obs-studio-node\obs_studio_client.node
```

I guess its `asar` related issue. I tried by adding `"asarUnpack": ["**/*.node"]` but does not help.
How can I fix this problem?

**Comment by mmaietta** [comment]
Just to double check, is the file present at that path and is `obs-studio-node` listed under your prod `dependencies`?

**Comment by alokmahor** [comment]
Yes yes I have checked it. `C:\some\path\My-Electron-App\resources\app.asar.unpacked\node_modules\obs-studio-node\obs_studio_client.node` file is present.

`obs-studio-node` is added in `dependencies` in `package.json` so it should be part of prod dependecies.

its a problem with `asar` with `native module` I guess

**Comment by hrueger** [comment]
Are you using a framework of webpack? For Angular, I had to add a `.node`-file loader: https://github.com/hrueger/AGView/blob/c9dc138fb3c30e9a9c98b4e33d39682b7e0ccc74/angular.webpack.js#L25-L28

**Comment by alokmahor** [comment]
@hrueger I am using [react-scripts](https://github.com/facebook/create-react-app).

**Comment by Sailiy** [comment]
Excuse me, has this problem been solved? I have the same problem

**Comment by hrueger** [comment]
This is usually not a problem of `electron-builder`, but instead of your bundler. If you use webpack or similar build tools, make sure that they process the `.node` files correctly and not skip them.
