### ISSUE TITLE
[Feature request]: AfterDependenciesInstalled hook

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#5709]
I need a method that would allow me to control exactly which dependencies come in the distributable package and which should be excluded.

For this I propose to hang a `afterDependenciesInstalled ` hook that will fire immediately after the dependencies installed.

### Use case:
Using bundles, such as rollup or Vite, some runtime dependencies are optimized and bundled into source code. This means that there is no need to keep these optimized dependencies in node_modules.

With  `afterDependenciesInstalled ` hook, we could remove dependencies that have already been optimized and bundled.

**Comment by mmaietta** [comment]
What about just manually specifying a negation in the `files` config?
```
    files: [
        "out",
        "!node_modules/some-package",
        "!**/*.node",
        "!**/*.LICENSE.txt",
        "!**/*.map"
    ],
```
The Documentation site says that all prod dependencies are automatically included because `**/node_modules/**/*` is appended, but my project actually excludes all dependencies via `!node_modules` due to the way we have to bundle the source code. Any negations seem to be prioritized over the 'allow' regexes, possibly order-based.

**Comment by cawa-93** [comment]
@mmaietta I don't really understand how this should work.

Let's say I have a Vue production dependency

Vue depends on @ vue / compiler-dom, and that on @ vue / compiler-core

`Vue` -> `@vue/compiler-dom` -> `@vue/compiler-core`

I can exclude Vue from the package, as you described, but all other dependencies will remain in the package

```
files: [
        "dist",
        "!node_modules/vue",
]
```
`X` -> `@vue/compiler-dom` -> `@vue/compiler-core`

**Comment by cawa-93** [comment]
> Is this still relevant?

Yeap

**Comment by cawa-93** [comment]
> Is this still relevant?

Ага

**Comment by mmaietta** [comment]
Please consider opening a PR to contribute
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
