### ISSUE TITLE
[Windows] extraFiles Options

### ISSUE THREAD

**Issue by L3V147H4N** [electron-userland/electron-builder#571]
using version 5.11.2

target: windows ia32 - x64

please post an example of using the extraFiles options, I need to include some files in the root dir of the app and I've tried many different ways but I still cannot include the files, I need to include a whole directory in the root of my project named "public_admin" which contains 3 files

**Comment by L3V147H4N** [comment]
I just solved it with:

```
"build": {
    "productName": "SistarJSServer",
    "asar": false,
    "extraFiles": [
      "public_admin/"
    ]
  },
```

I was using version 3.x and it did nothing, now it works

**Comment by develar** [comment]
So, the problem was only in the old version or there is some usability aspect?

**Comment by L3V147H4N** [comment]
@develar It seems it was only a version problem
