### ISSUE TITLE
Electron can't find module if this module imported from npm workspaces

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#5713]
* **Version**: 22.10.5

* **Electron Version**: 12.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: Windows 10 x64

### Description
Electron can't find module if this module imported from npm workspaces. I guess the reason is that there is no `package-lock.json` file in the packed application.

Repo with reproduction: https://github.com/cawa-93/electron-builder-issue.

### Steps to reproduce
1. Clone repo 
2. Install electron and electron-builder: ``` npm ci```
3. Try run in Node:
    ```
    node /path/to/electron-builder-issue/packages/main/dist/index.cjs
    ```
    **Expected output:**
    ```
    /path/to/electron-builder-issue/packages/renderer/dist/index.html
    ```
4. Build Electron app: `npm run build`
5. Try run in Electron:
    ```
    /path/to/electron-builder-issue/dist/win-unpacked/vite-electron-builder.exe
    ```
    **Expected output:**
    ```
    /path/to/electron-builder-issue/dist/win-unpacked/resources/app/packages/renderer/dist/index.html
    ```
    **Actual behaver**:
    Electron throw Error: `Can not find module "@packages/renderer"`
6. Try to fix
    1. Go to `cd /path/to/electron-builder-issue/dist/win-unpacked/resources/app`
    2. `npm install`
    3. Repeat Step 5.

**Comment by develar** [comment]
I see your twit... Have you tried PNPM workspace instead of NPM ;)?

**Comment by cawa-93** [comment]
@develar I can't do that. I'm working on a template, so I want to minimize count of non-native tools.

**Comment by develar** [comment]
I think issue is that electron-builder somehow modifies package.json.

**Comment by cawa-93** [comment]
> Is this still relevant?

Yes

**Comment by cawa-93** [comment]
Yes.
Tested on
Electron: v14, v15.0.0-beta.7
electron-builder: v22.11.11, v22.14.2
