### ISSUE TITLE
Windows Application Install Directory Inheriting package.json "name" instead of electron-builder "productName"

### ISSUE THREAD

**Issue by bryceremick** [electron-userland/electron-builder#5719]
* **Version**:  22.2.0

* **Electron Version**: 11.3.0

* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis

---

When installing on Windows with the `oneClick` NSIS installer, the application gets installed to a directory which is named using the `name` key from the package.json rather than using the `productName` key from the electron-builder configs. If the `oneClick` option is set to false, the directory is named correctly. The `userData`  directory is always named using `productName` regardless of what `oneClick` is set to.

Is this intended? Or a bug? I would like to be able to use the `oneClick` installer and have the application directory be named using the `productName` value. 

Same issue as #4803

**Comment by JCMais** [comment]
This is still an issue
