### ISSUE TITLE
Custom dist output and app dir

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#572]
> and create the installers into the packaged directory

I suggest to use defaults — `dist` directory. You can set custom using [directories.output](https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-output):
```json
"directories": {
  "output": "packaged"
}
```

> The app is built from src using grunt into the build directory. 

If your app has native dependencies, I recommend to use [Two package.json structure]( https://github.com/electron-userland/electron-builder#two-packagejson-structure). If no native dependencies, use [build.files](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-files):

```json
"build": {
  "files": "build"
}
```

So, only `build` directory will be included into the packaged app. But! `build` is expected to be [directory of  build resources](https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-buildResources). So, recommended to use different name, `out` for example. Or set `directories.buildResources` to custom value.

And don't forget to read https://github.com/electron-userland/electron-builder#in-short

**Comment by Mercieral** [comment]
I actually do use a two package.json structure in some fashion. There is a package.json in my project base directory as well as in the the "src" directory. During the grunt build, the package.json needed for electron in "src" is copied over to the build directory along with the icons, backgrounds, and node_modules it needs (So I don't have to do an npm install every time). 

I should not be changing directory names so will it still work if I use "build" as my "files" directory?

**Comment by develar** [comment]
So, if you don't want to rename your `build` to `app`:

1. set `directories.buildResources` to custom dir name (app icons and other required assets must be not in the app production directory because it is only compile-time dependencies).
2. set `directories.app` to `build`

I recommend you to rename your `build` to `app` to avoid custom configuration ;)

**Comment by develar** [comment]
You are not forced to use special directory for build resources, you can explicitly set all options (e.g. [mac.icon](https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions-icon)), but as you understand, it is not easy way.

**Comment by Mercieral** [comment]
It's not that I don't want to, it is more that I do not have the authority to  (this is not my project, I am only helping). I will try your suggestion soon and see how it goes. Thanks for all your help so far :)

**Comment by Mercieral** [comment]
Both the MAC and Windows installers seem to be working! Thanks again for helping me out!

While it may be more of a question for the squirrel installer people, I do have one more question. On windows 10 I was hoping to have the app installed to be visible under "Programs and Features" with an uninstaller and maybe a desktop shortcut. However it is installed into AppData/local, is not visible by Windows, and doesn't seem to have an uninstaller (implying that the user would have to manually find the app in AppData/local and delete the files). Is there any way to go about this?

**Comment by develar** [comment]
@Mercieral Please see https://github.com/electron-userland/electron-builder/issues/551#issuecomment-229638846

> do not get the auto-updater. Any suggestions?

Wait. #529 Will be fixed soon, but cannot promise anything.
