### ISSUE TITLE
security breach with dotenv

### ISSUE THREAD

**Issue by dorkalev** [electron-userland/electron-builder#5720]
* **Version**: ^22.10.5

* **Electron Version**:12.0.1
* **Electron Type (current, beta, nightly)**: current
 4.2.0

* **Target**: mac

hi, after packaging and installing I opened my app's asar at /Applications/XXXAPPXXX/Contents/Resources/app.asar
and saw my .env content there on line 2 , including password to notarize app @ apple

now, i googled and saw there's a method to exclude the .env file from the build
BUT I'll bet 99% of devs don't do it
I assume a quick scan of electron repositories will find some .env files, some with passwords like i had

**Comment by mmaietta** [comment]
Is '.env' the filename needing to be excluded or is '.env' only the extension?
https://github.com/electron-userland/electron-builder/blob/da85087143d2c6a63faab4c44c28dc625326e9ee/packages/app-builder-lib/src/fileMatcher.ts#L15-L22

Seems reasonable to have it ignored by default, one can always force include it via their 'files' config, but it'd be a breaking change for any unsuspecting devs...so I'm hesitant to just jump in with a code change.
@develar what are your thoughts?

**Comment by develar** [comment]
What env file name do you use?

> what are your thoughts?

Should be a balance. Specific env files maybe ignored, but not the `*.env`. Moreover, I find it not good to store such sensitive variables in files at all.
