### ISSUE TITLE
docs: missing space

### ISSUE THREAD

**Issue by niexiaofei1988** [electron-userland/electron-builder#5723]
[The doc of missing space](https://www.electron.build/auto-update#quick-setup-guide)

<img width="1435" alt="11" src="https://user-images.githubusercontent.com/16014141/111906771-3f2f0500-8a8d-11eb-9472-543bb31dc4de.png">

**Comment by mmaietta** [comment]
Nice catch! Would you mind opening a PR for that targeting the `/docs` branch?
