### ISSUE TITLE
cannot require node modules

### ISSUE THREAD

**Issue by gggin** [electron-userland/electron-builder#573]
* **5.11.3**: 

* **npm run dist:win64**: 

cannot require electron-squireel-startup
may be other include also cannot require
3.xx.x works bug 5.11.3 cannot work

**Comment by develar** [comment]
**electron-squirrel-startup**

**Comment by gggin** [comment]
I always know i need to install but 3.x version work but 5.x version cannot require

**Comment by gggin** [comment]
no, I just install in dependenties...
