### ISSUE TITLE
no resource with given URL found

### ISSUE THREAD

**Issue by chenjunhuan666** [electron-userland/electron-builder#5730]
``

**Comment by mmaietta** [comment]
Closing until more details are provided.

**Comment by chenjunhuan666** [comment]
> Closing until more details are provided.
This is my mainJS configuration and I don't know why it caused this error:no resource with given URL found, please give some advice
`
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')
const isDev = require('electron-is-dev')
let mainWindow

function createWindow () {
    mainWindow = new BrowserWindow({
      width: 800, height: 600,
      webPreferences: {
        nodeIntegration: true,
      }
    })

  // 加载应用----适用于 react 项目
    if(isDev){
        mainWindow.loadURL('http://localhost:5002/');
    }else{
        mainWindow.loadURL(url.format({
            pathname: path.join(__dirname, './build/index.html'),
            protocol: 'file:',
            slashes: true
        }))
    }

  mainWindow.webContents.openDevTools()

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

`
