### ISSUE TITLE
Vulnerability in transitive dependency xmldom of electron-builder

### ISSUE THREAD

**Issue by Mvbraathen** [electron-userland/electron-builder#5733]
* **Version**: 22.10.5

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current

Vulnerability in transitive dependency xmldom of electron-builder.
![image](https://user-images.githubusercontent.com/16756739/112306890-9eb12e80-8ca0-11eb-9203-1bcc82ca32ff.png)

**Comment by mmaietta** [comment]
Thanks for pointing that out. 
Waiting on this PR to be merged+released: https://github.com/TooTallNate/plist.js/pull/107 so that dmg-license can pull it in.

**Comment by Mvbraathen** [comment]
From the PR you linked: 
![image](https://user-images.githubusercontent.com/16756739/114691473-0397fb80-9d18-11eb-830f-850a46cd5f64.png)
