### ISSUE TITLE
Automatic launch

### ISSUE THREAD

**Issue by maxdow** [electron-userland/electron-builder#574]
* **Version**: 5.12

* **Target**: Windows

I use one click install nsis setup for windows and it works very well. But is there a way to disable automatic launch after install ? 

I know it is possible with Squirrel by handling events correctly .

Thanks

**Comment by develar** [comment]
Why do you need to disable "run after start"?

**Comment by maxdow** [comment]
Because I want to install my app without running it directly after. In my use case some people install the app ( sometimes remotely ) and other use it.
It's not critical but maybe it could be nice to have an option to disable this feature ?

**Comment by develar** [comment]
> It's not critical but maybe it could be nice to have an option to disable this feature ?

Option will be added soon. Just want to know the reason. Please keep in mind — one-click installer doesn't have indicator of successful installation (no Finish page), so, the only indicator — desktop shortcut. In general, it is not user-friendly, but probably in your case it is ok.

**Comment by maxdow** [comment]
It is ok for my use case. Personally i like the one click fast setup but in my organization context simplicity is rarely the reality..

Having this option is IMO a good thing for the project :)

Thanks, I close the issue so

**Comment by develar** [comment]
Reopened — will be closed automatically on implementation commit :)
