### ISSUE TITLE
Not Publishing latest.yml, latest-mac.yml, or latest-linux.yml

### ISSUE THREAD

**Issue by kidsonfilms-python-rules** [electron-userland/electron-builder#5747]
* **Version**: ^22.10.5

* **Electron Version**: 12.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS, DMG, AppImage

When I run the following command:
```sh
npm run publish
```
`package.json`
```json
{
"scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder -mwl",
    "publish": "electron-builder -mwl --publish always"
  },
 .....
  "build": {
    "asar": true,
    "appId": "redacted",
    "files": [
      "list",
      "of",
      "files",
    ],
    "publish": [
      {
        "provider": "github",
        "owner": "kidsonfilms-python-rules",
        "repo": "redacted"
      }
    ],
    "mac": {
      "category": "public.app-category.music",
      "icon": "assets/appIcons/redacted Logo.icns"
    },
    "dmg": {
      "background": null,
      "icon": "assets/appIcons/redacted Logo.icns",
      "backgroundColor": "#202020",
      "window": {
        "width": "400",
        "height": "300"
      },
      "contents": [
        {
          "x": 100,
          "y": 100
        },
        {
          "x": 300,
          "y": 100,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false
    }
  }
}
```
It builds only the zip/unpacked folders/executables and not the `latest.yml` file of any OS.

I read in another issue that they don't make the file locally but do publish it but I cannot find it published (see image 1)

I waited for 3 hours just in case my web browser is running cached data but it is not showing up.

My question is, am I using the wrong command or is it something wrong in my config?

**Comment by eden-lane** [comment]
Have the same problem :(

**Comment by AxelTerizaki** [comment]
I have the same issue actually. When I build, no app-latest.yml (or latest-mac.yml) are generated even though I use `--publish always`. I'm just creating a dmg file.

**Comment by LoveCodingOnGithub** [comment]
> I have the same issue actually. When I build, no app-latest.yml (or latest-mac.yml) are generated even though I use `--publish always`. I'm just creating a dmg file.

Same problem here , have you solved it ?

**Comment by AxelTerizaki** [comment]
I don't remember the issue exactly but I think you need to also generate a zip file in order for the yml to be generated. Try adding zip to your targets for mac.
