### ISSUE TITLE
Register custom scheme?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#575]
Is it possible to register a custom URL scheme so that when I navigate to "sample://test" in Safari, it will open my app?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/397#issuecomment-230707504

As part of this issue I am going to simplify it.

**Comment by develar** [comment]
Relates #284

**Comment by develar** [comment]
`5.34`: https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-protocols
