### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB

### ISSUE THREAD

**Issue by amiranagram** [electron-userland/electron-builder#5755]
Hi, I read in an issue here that this bug has been fixed in 22.10.5 but the issue persists for me. Maybe I'm doing something wrong.

```
[2021-03-30 22:36:57.201] [info]  Found version 0.8.0 (url: app-0.8.0.exe)
[2021-03-30 22:36:57.210] [info]  Downloading update from app-0.8.0.exe
[2021-03-30 22:36:57.224] [info]  Download block maps (old: "https://api.github.com/repos/me/repo/releases/assets/34224707.blockmap", new: https://api.github.com/repos/me/repo/releases/assets/34224707.blockmap)
[2021-03-30 22:36:57.750] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\me\AppData\Local\Programs\app\resources\app.asar\background.js:2:191480)
    at ClientRequest.<anonymous> (C:\Users\me\AppData\Local\Programs\app\resources\app.asar\background.js:2:192996)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6777)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

electron: `12.0.2`
electron-builder: `22.10.5`
electron-updater: `4.3.8`
target: `nsis`
os: `win-10.0.19042`

Build options:

```
productName: 'App',
appId: 'com.example.app',
artifactName: 'App-${version}-${os}-${arch}.${ext}',
win: {
    target: 'nsis'
},
nsis: {
    artifactName: 'App-Setup-${version}-${os}-${arch}.${ext}',
    oneClick: true,
    perMachine: false,
    deleteAppDataOnUninstall: false,
    allowToChangeInstallationDirectory: false,
    runAfterFinish: true,
    differentialPackage: true
},
publish: [
    {
        provider: 'github',
        private: true,
        owner: 'me',
        repo: 'repo',
        token: 'token'
    }
],
```

package.json:

```
{
    "name": "repo",
    "version": "0.8.0",
    "private": true,
    "repository": {
        "url": "https://github.com/amiranagram/repo"
    },
    "author": {
        "name": "Amir Rami"
    },
    "main": "background.js",
    "scripts": {
        "serve": "vue-cli-service serve",
        "build": "vue-cli-service build",
        "lint": "vue-cli-service lint",
        "electron:serve": "vue-cli-service electron:serve",
        "electron:build": "vue-cli-service electron:build",
        "electron:publish": "vue-cli-service electron:build --publish always",
        "postinstall": "electron-builder install-app-deps"
    },
    "dependencies": {
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.4.0",
        "dexie": "^3.0.3",
        "electron-updater": "^4.3.8",
        "imask": "^6.0.7",
        "litepicker": "^2.0.7",
        "lodash": "^4.17.21",
        "moment": "^2.29.1",
        "vee-validate": "^3.4.5",
        "vue": "^2.6.11",
        "vue-clickaway": "^2.2.2",
        "vue-directive-tooltip": "^1.6.3",
        "vue-ray": "^1.15.0",
        "vue-router": "^3.2.0",
        "vue-the-mask": "^0.11.1"
    },
    "devDependencies": {
        "@tailwindcss/postcss7-compat": "^2.0.4",
        "@vue/cli-plugin-babel": "~4.5.0",
        "@vue/cli-plugin-eslint": "~4.5.0",
        "@vue/cli-plugin-router": "~4.5.0",
        "@vue/cli-service": "~4.5.12",
        "@vue/eslint-config-standard": "^5.1.2",
        "autoprefixer": "9",
        "babel-eslint": "^10.1.0",
        "electron": "^12.0.0",
        "electron-devtools-installer": "^3.1.1",
        "electron-log": "^4.3.2",
        "eslint": "^6.7.2",
        "eslint-plugin-import": "^2.20.2",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-promise": "^4.2.1",
        "eslint-plugin-standard": "^4.0.0",
        "eslint-plugin-vue": "^6.2.2",
        "postcss": "7",
        "postcss-import": "^12.0.1",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat",
        "vue-cli-plugin-electron-builder": "^2.0.0-rc.4",
        "vue-template-compiler": "^2.5.17"
    }
}
```

Anything I'm doing wrong?

**Comment by burnhamup** [comment]
How big are your blockmap files? The error says that it can't handle blockmaps bigger than 50MB.

For reference, the installers I've made have a blockmap size of 61KB, so I'd be surprised to see blockmaps that big. 

The URL to your blockmap is private: https://api.github.com/repos/me/repo/releases/assets/34224707.blockmap but I would double check that it actually is the correct file.

**Comment by amiranagram** [comment]
@burnhamup Last one was `62.7 KB`. According to this message `Cannot download differentially, fallback to full download` I think it's ignoring blockmap and trying to download the `.exe` file, which is around `58 MB`.

**Comment by amiranagram** [comment]
@burnhamup I found this comment: https://github.com/electron-userland/electron-builder/issues/4358#issuecomment-546982742

Is this relevant, because blockmap is not referenced in `latest.yml` for me as well?

```yml
version: 0.8.8
files:
  - url: app-setup-0.8.0.exe
    sha512: mUYsDYCZHVuNurMCFaie00j7p3DWQY3osXAI2PvRAuKWqlsjVlTf0vPwFaLgNAnB3W3KEKAX/FEPBUb5jfxxXg==
    size: 59807715
path: app-setup-0.8.0.exe
sha512: mUYsDYCZHVuNurMCFaie00j7p3DWQY3osXAI2PvRAuKWqlsjVlTf0vPwFaLgNAnB3W3KEKAX/FEPBUb5jfxxXg==
releaseDate: '2021-03-31T17:21:01.627Z'
```

As you can see there is not `.blockmap` in my `latest.yml` file.

**Comment by lilian131** [comment]
look my answer: https://stackoverflow.com/questions/59837408/electron-updater-notify-for-new-release-but-do-not-update-or-download-new-releas/66940788#66940788

**Comment by amiranagram** [comment]
@lilian131 I have node js v14.15.4 installed. I don't think this is it.

**Comment by HarunKilic** [comment]
I have same problem here.

**Comment by mmaietta** [comment]
Can you please try this patch from my comment here? https://github.com/electron-userland/electron-builder/issues/4676#issuecomment-811177696
Idk if 5 or 50 were specifically or arbitrarily determined, so the patch simply enables 100mb chunks. Give it a test and report back? Maybe we'll have a basic solution to start with.

**Comment by amiranagram** [comment]
@mmaietta Appreciate the patch, but the real issue here why does it fail to update the app from the blockmaps? Maybe @develar  can help us out.

**Comment by geolffreym** [comment]
Hi guys, same problem here using Ubuntu Linux distro
```
 Cannot download differentially, fallback to full download: Error: invalid block type
    at Zlib.zlibOnError [as onerror] (zlib.js:181:17)
    at processChunkSync (zlib.js:430:12)
    at zlibBufferSync (zlib.js:169:12)
    at syncBufferWrapper (zlib.js:764:14)
    at readBlockMap (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.js:53:48)
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.js:44:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.task (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:138:11)
    at async AppImageUpdater.executeDownload (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:754:7)
    at async AppImageUpdater.<anonymous> (/tmp/.mount_watchiuK0hmD/resources/app.asar/src/main/index.js:167:5)
```

**Comment by andrefmandrade** [comment]
Having this issue aswell.
blockmap has 88 kb, think blockmap download is failing and is trying to download the .exe (in my case it has 79mb)

**Comment by amiranagram** [comment]
Idk, I'm struggling here. There are probably 100 issues opened for this particular problem, but nobody has an answer.

**Comment by geolffreym** [comment]
@amiranagram my issue seems related to 7zip. Do you think this version upgrade have something to  do with it?
"7zip-bin": "~5.0.3", -> "7zip-bin": "~5.1.1",

**Comment by HarunKilic** [comment]
Still no updates on this? Does anyone have workaround for this issue?

**Comment by andrefmandrade** [comment]
> Still no updates on this? Does anyone have workaround for this issue?

I tried everything, since the blockmap fail, it will fallback to my 80mb .exe install and wont get anywhere.
This is sad, really.

**Comment by WahaWaher** [comment]
same issue :( node version 14.16.0

**Comment by andrefmandrade** [comment]
Workaround:
comment this block of code inside node_modules\builder-util-runtime\out\httpExecutor.js
```
              if (size > 52428800) {
                callback(new Error("Maximum allowed size is 50 MB"));
                return;
              }
```
and it will succeed downloading the update

**Comment by geolffreym** [comment]
> Workaround:
> comment this block of code inside node_modules\builder-util-runtime\out\httpExecutor.js
> 
> ```
>               if (size > 52428800) {
>                 callback(new Error("Maximum allowed size is 50 MB"));
>                 return;
>               }
> ```
> 
> and it will succeed downloading the update

Seems like this is not the same issue. It the same "Cannot download differentially, fallback to full download" but diff error  => https://github.com/electron-userland/electron-builder/issues/5755#issuecomment-815978567 ?

**Comment by WahaWaher** [comment]
> Workaround:
> comment this block of code inside node_modules\builder-util-runtime\out\httpExecutor.js
> 
> ```
>               if (size > 52428800) {
>                 callback(new Error("Maximum allowed size is 50 MB"));
>                 return;
>               }
> ```
> 
> and it will succeed downloading the update

thsnks, it works for me. at least better than nothing

**Comment by mmaietta** [comment]
Does anyone know/understand/hypothesize why there is a 50mb limit set?

**Comment by amiranagram** [comment]
Well I don't really wanna make changes to vendor files, and the 50MB limit is not the real problem IMO, it's why is it failing to apply the update from the blockmap?!

**Comment by neonux1987** [comment]
although the error states that there's a size problem, for many it's not the case.
if you notice the filenames of the blockmap old and new are not the right filenames. so basically when it's trying to fetch it gets not found error and then it fallbacks to full download.
my blockmap is income-outcome-management-system-setup-1.0.3.exe.blockmap
but it's trying to get 35287244.blockmap instead.

**Comment by mmaietta** [comment]
Happy to accept any PRs on this issue.
I don't have any project using electron-updater and haven't been able to figure out this works yet.

**Comment by mmaietta** [comment]
This file limit was increased in this PR. We still can't determine the origin for it being there in the first place
https://github.com/electron-userland/electron-builder/pull/5843
