### ISSUE TITLE
Building x64 on arm64 Mac

### ISSUE THREAD

**Issue by louistb** [electron-userland/electron-builder#5756]
* **22.10.5**: 

* **12.0.2**:
* **Current**:

* **Mac x64**: 

I was wondering if i should be able to build for x64 on a arm64 Mac. It seems like when i build for x64 on my arm64 mac, the actual executable crashes and returns : zsh: bus error. If it use build the same project using a x64 machine, the build is fine.

Is this by design or is this a issue with electron-builder ? 

Thanks

**Comment by louistb** [comment]
Here is the start of the error showing in mac os after the app crashes

Process:               App [93151]
Path:                  /Users/USER/Desktop/*/app.app/Contents/MacOS/
Identifier:            com.electron.
Version:               0.1.12 (0.1.12)
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           App [93151]
User ID:               501

Date/Time:             2021-03-31 21:38:41.662 -0400
OS Version:            macOS 11.2.2 (20D80)
Report Version:        12
Anonymous UUID:        231D9C36-F8D3-31D1-0004-7D2EAE28AF2D

Sleep/Wake UUID:       EE2A97C5-87ED-4A13-BF32-65E6BB3CE4A0

Time Awake Since Boot: 28000 seconds
Time Since Wake:       1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00000071ad7e87a9
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [93151]

**Comment by louistb** [comment]
Update, i working on another project in electron and the issue persist in a completely different project.

**Comment by cliqer** [comment]
+1. Exactly the same issue

**Comment by louistb** [comment]
@cliqer so i was able to build this for x64 on arm : 

https://github.com/electron/electron-quick-start

Im still trying to figure out what features are causing the issue.

**Comment by mmaietta** [comment]
I get an M1 mac coming in this week to take a look at this

Can you post your electron-builder config (general options + mac specific)?

**Comment by louistb** [comment]
Amazing, you will love the m1 im sure :)

My main build commands are : 

```
    "package:mac": "yarn build && electron-builder --mac --x64",
    "package:macarm": "yarn build && electron-builder --mac --arm64"
```

Not sure you if this is what you are talking about ?

**Comment by louistb** [comment]
Update : i tried to run electron-builder from a rosetta terminal and issue persist.

**Comment by louistb** [comment]
Hi :)

Any update on this ? 

Thanks

**Comment by cliqer** [comment]
In my case, I have installed node v15.14.0 with brew.
Both support arm, but even though everything is going so much faster I believe that is where part of our issue is.
@louistb are you sharing the same setup?

**Comment by louistb** [comment]
Ok so it seems like by installing node v14.16.1 and running yarn on my project it fixed the issue !!!!
