### ISSUE TITLE
Detected as malware by Windows Defender while signed by a valid code signing certificate

### ISSUE THREAD

**Issue by htxuuu** [electron-userland/electron-builder#5759]
* **Version: 22.10.5**: 

* **Electron Version: 12.0.2**:
* **Electron Type (current, beta, nightly): current**:

-

* **Target: windows nsis**: 

I use the code of [electron-quick-start](https://github.com/electron/electron-quick-start) to test this case,
after building and packing with electron builder, and signed it using a DigiCert code signing certificate,
Windows Defender still detect it as malware and delete it automatically when user download it from the internet. 
![image](https://user-images.githubusercontent.com/20788346/113378498-c3488d00-93a9-11eb-836a-7b5097c82c91.png)

Windows Defender detect it as Trojan:Win32/Spursint.F!cl

Is it a bug or there is something wrong in my process?

**Comment by mmaietta** [comment]
Can you please try reproing this issue on v22.9? I'm curious if this is a regression. My immediate guess is that there's something wrong with your process/certificate otherwise this problem would be much more pronounced in our Issues dashboard.

**Comment by htxuuu** [comment]
> Can you please try reproing this issue on v22.9? I'm curious if this is a regression. My immediate guess is that there's something wrong with your process/certificate otherwise this problem would be much more pronounced in our Issues dashboard.

thank you for your reply. It seems that my publiserName is not completely match the name set in the certificate, which cause windows defender detect it as malware.

for others who come up this problem, please make sure `config.win.publisherName` in your build params is completely match the name you set in your code certificate.
