### ISSUE TITLE
Electron zipPath=undefined during build with electron-builder 22.10.5 but not 22.9.1

### ISSUE THREAD

**Issue by somebeaver** [electron-userland/electron-builder#5762]
* **Version**: Bug happens in 22.10.5

* **Electron Version**: 7.3.1
* **Electron Type (current, beta, nightly)**: current?

* **Target**: macOS Catalina 10.15.7

I have been using electron-builder with my project successfully for a while, but when I upgraded to electron-builder 22.10.5, my builds for macOS would fail with this message:

![err](https://user-images.githubusercontent.com/3053410/113447101-33194080-93c7-11eb-864e-bdf5e211de49.png)

It seems to me that the error is being caused by `Unpacking electron zip zipPath=undefined` on the 2nd last line. When I downgraded electron-builder to 22.9.1 (and changed nothing else), builds worked again.

**Comment by mmaietta** [comment]
That line is actually an extra console.log I accidentally left in the code. It won't be the source of your error.

What's shown in your stack trace?

**Comment by somebeaver** [comment]
Here's the entire output using 22.10.5: [output.txt](https://github.com/electron-userland/electron-builder/files/6251724/output.txt)

**Comment by mmaietta** [comment]
I think I found the culprit.
```
at Object.<anonymous> (/Users/brian/Projects/Hydra/SourceCode/hydra-server-desktop/node_modules/istextorbinary/index.cjs:4:38)

...

↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
```

https://snyk.io/advisor/npm-package/binaryextensions
>This package is published with the following editions:
binaryextensions/source/index.ts is **TypeScript source code with Import for modules**
binaryextensions/edition-browsers/index.js is TypeScript compiled against ES2019 for web browsers with Import for modules
binaryextensions aliases binaryextensions/edition-es5/index.js
binaryextensions/edition-es5/index.js is TypeScript compiled against ES5 for Node.js with Require for modules
binaryextensions/edition-es5-esm/index.js is TypeScript compiled against ES5 for Node.js with Import for modules
binaryextensions/edition-deno/index.ts is TypeScript source code made to be compatible with Deno

As to what is going wrong, I'm not sure and very puzzled. I seems like an incorrect import but not sure how we're getting into that state

**Comment by somebeaver** [comment]
Hmm, I'm not sure what's going on. I'm not using `istextorbinary` or `binaryextensions`, they don't exist in my node_modules at that path, and `npm ls <pkg>` doesn't show anything for either package.

**Comment by mmaietta** [comment]
They're deps of electron-builder for detecting what files are binary in order to determine what to sign. `binaryextensions` is a subdependency.

Shot in the dark here, can you post your base tsconfig?

**Comment by somebeaver** [comment]
I'm not using Typescript, so I don't have one. Unless you mean something else?

**Comment by mmaietta** [comment]
Can you try with 22.10.4 and see if this still occurs? I think that's when `istextorbinary` was introduced, either that or 22.1.0.3. If it's a regression, I'll need to figure out another way to detect a binary file for signing.

**Comment by somebeaver** [comment]
Just tested with 22.10.4 and it works as expected.
