### ISSUE TITLE
"Uncaught ReferenceError: require is not defined" after building

### ISSUE THREAD

**Issue by ScribbleNerd** [electron-userland/electron-builder#5763]
* **Version**: 22.9.1

* **Electron Version**: v10.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis win64

I'm trying to use Electron's remoteModule and nodeIntegration, and everything works when using the electron cli, but after building it, the following gets logged to the renderer console:
```
Uncaught ReferenceError: require is not defined
```

and the line that is mentions as producing the error is:

```js
const { remote } = require('electron')
```

my electron config is:
```js
new BrowserWindow({
  // ...
  webPreferences: {
    enableRemoteModule: true,
    nodeIntegration: true,
    worldSafeExecuteJavaScript: true
  },
  // ...
})
```

**Comment by mmaietta** [comment]
That sounds like it isn't being bundled correctly. Do you have a repo repro-ing this that I could take a look at?

**Comment by ScribbleNerd** [comment]
> That sounds like it isn't being bundled correctly. Do you have a repo repro-ing this that I could take a look at?

Hmm, now that I'm going back and trying to run it again via the electron cli and it's now giving me the same error as it did when packaged...

**Comment by mmaietta** [comment]
Using webpack by chance? If so, I can possibly help out.

**Comment by ScribbleNerd** [comment]
> Using webpack by chance? If so, I can possibly help out. Post your config

Nope I'm not using webpack

**Comment by ScribbleNerd** [comment]
Here's the commit on one of my repos that is having this issue: [https://github.com/ScribbleNerd/node-rest-client/tree/bf244086e605d7aafaec73d80889136a013bdf1b](https://github.com/ScribbleNerd/node-rest-client/tree/bf244086e605d7aafaec73d80889136a013bdf1b)

**Comment by ScribbleNerd** [comment]
I've switched that project over to an older version of electron and it seems to have completely fixed the issue so I'm not really sure what's happening...
