### ISSUE TITLE
Startup-time for portable built-apps are quite slow

### ISSUE THREAD

**Issue by opvasger** [electron-userland/electron-builder#5765]
* **Versions**: 
```json
 "devDependencies": {
    "electron": "12.0.1",
    "electron-builder": "22.10.5"
}
```

* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows

Startup time on my i5 8gb Windows 10 laptop is ~10 seconds for a portable built of a hello-world electron-app. Is there anything I can do to reduce the startup time?

For now I've included a splash-image to be shown while loading to reduce perceived load-time, but its still really slow compared to a non-portable build.

Any suggestions, or work I can do to improve load-time? I'm not asking you to necessarily do work, I will try to contribute if it's within my skill-set

**Comment by mmaietta** [comment]
I'm not familiar with how portable apps work, especially w.r.t. performance. Happy to help here, but I'll need some directions.

If you'd like to take a gander, you can create a local dev environment with these instructions.
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by opvasger** [comment]
I've decided to abandon electron for deno-webview for the project in question, and won't look further into this now.

I'll return if the path of least resistance doesn't work out ☀️ cya
