### ISSUE TITLE
pass install directory on command line to installer.

### ISSUE THREAD

**Issue by lufang2000** [electron-userland/electron-builder#5766]
* **Version**: 
22.10.5

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

current, 10.1.5

* **Target**: 
windows 10 x64

My executable is part of a larger project. The install directory is controlled by the parent project. Is there a way to pass the install directory on this command line to the installer? For that matter, what parameters are supported?

**Comment by mmaietta** [comment]
Looks like it is possible when running an nsis exe via `/D=` arg
https://documentation.help/CTRE-NSIS/documentation.pdf
>3.2 Installer Usage
Generated installers and uninstallers accept a few options on the
command line. These options give the user a bit more control over the
installation process.
3.2.1 Common Options
/NCRC disables the CRC check, unless CRCCheck force was used in
the script.
/S runs the installer or uninstaller silently. See section 4.12 for more
information.
/D sets the default installation directory ($INSTDIR), overriding
InstallDir and InstallDirRegKey. It must be the last parameter used in
the command line and must not contain any quotes, even if the path
contains spaces. Only absolute paths are supported.
3.2.2 Uninstaller Specific Options
_?= sets $INSTDIR. It also stops the uninstaller from copying itself to
the temporary directory and running from there. It can be used along
with ExecWait to wait for the uninstaller to finish. It must be the last
parameter used in the command line and must not contain any
quotes, even if the path contains spaces.
3.2.3 Examples
installer.exe /NCRC
installer.exe /S
installer.exe /D=C:\Program Files\NSIS
installer.exe /NCRC /S /D=C:\Program Files\NSIS
uninstaller.exe /S _?=C:\Program Files\NSIS
