### ISSUE TITLE
MacOS - Remove/replace alias files in Electron Framework.framework folder

### ISSUE THREAD

**Issue by Faksprod** [electron-userland/electron-builder#5767]
* **Version**: 21.2.0

* **Electron Version**: 21.2.0

* **Target**: MAC

I am building an .APP file with **electron-buidler** and it works great. My app is able to run on my Mac.
My question is about the **Frameworks** folder structure I can see when right clicking my .app file then > show package content.

In the **Frameworks/Electron Framework.framework/** folder I can see 3 alias:

- Electron Framework
- Libraries
- Resources

![Capture d’écran 2021-04-04 à 19 05 15](https://user-images.githubusercontent.com/21133515/113516397-65b76a80-957a-11eb-9e01-2d360dd0006c.png)

Each of these alias are pointing to their original files stored in the sub folder folder **Versions/A/**
(this is the same concept/organization for each folder in the **Frameworks** folder such as **Mantle.framework**, **ReactiveCocoa.framework** and **Squirrel.framework**)

![Capture d’écran 2021-04-04 à 19 06 59](https://user-images.githubusercontent.com/21133515/113516534-0a39ac80-957b-11eb-8da1-3aa1aa6bde71.png)

For a very specific case, before publish/distribute my app, I need to reorganized this folder/file structure by replacing alias by their original folder/file (then after what I can also remove the **Versions** folder which is now useless).

I could of course do this manually (I did it and the app still works). I could open each sub folders, then replace each alias by its original file manually... But I will have to do this each time I will update my app before publishing it, which is kind of annoying. My questions:

-> Is there any option to pass to electron-builder to say "please don't create any alias in the **Frameworks** folder, just put original files where they have to be"?
-> Why such a structure/organization? What is it useful for?

Thanks!

**Comment by mmaietta** [comment]
The aliases are not something created by electron-builder.  That's the default structure of a static framework compiled on/for MacOS. I was under the impression that a static framework can have multiple versions, indexed by letter, and with one alias'd to Current. That being said, I've never seen one with more than just "A" and "Current".

Not sure I understand why you need to reorganize static libraries but you could probably achieve a programmatic route by using a hook, probably best suited for `afterPack` so that the app is signed after you've modifed the files.
https://www.electron.build/configuration/configuration#afterpack

**Comment by Faksprod** [comment]
Thanks a lot for clarification! I though this organization was specific to **electron-builder** (not a Mac Frameworks expert, sorry).
If I need to reorganize folder/file this way it's for a [Steam](https://partner.steamgames.com/) distribution. Explanation:

When you upload a .APP file (built with **electron-builder**) on Steam, all alias contained in the **/Contents/Frameworks** folder will be replaced by executable files. When you try to run this modified version of your .APP, alias aren't pointing anymore to their right location folder (they aren't alias anymore), and the app can't run.

So I figured out that I could simply remove/replace all the alias by their original file/folder just by reorganizing my .APP content structure before submitting to Steam. Then, it works.

Anyway, I already wrote a little **bash** script to reorganize the Frameworks folder of my .APP file.
```printf "Remove alias from Contents/Frameworks\n"

APP_NAME = "MySuperApp.app"
APP_RENAME = "MySuperApp_steam.app"
APP_PATH = "/Path/To/My/Super/App"
FRAMEWORKS_PATH = "$APP_PATH/$APP_NAME/Contents/Frameworks"

printf ". remove alias from folder Electron Framework.framework\n"
rm -r $FRAMEWORKS_PATH/Electron\ Framework.framework/Electron\ Framework
rm -r $FRAMEWORKS_PATH/Electron\ Framework.framework/Libraries				
rm -r $FRAMEWORKS_PATH/Electron\ Framework.framework/Resources
mv $FRAMEWORKS_PATH/Electron\ Framework.framework/Versions/A/* $FRAMEWORKS_PATH/Electron\ Framework.framework/
rm -r $FRAMEWORKS_PATH/Electron\ Framework.framework/Versions```

# repeat this action for all folders you want to process
# ...

mv $APP_PATH/$APP_NAME $APP_PATH/$APP_RENAME

printf "Remove alias -> Done\n"

**Comment by mmaietta** [comment]
Hmmm, let me know if that works? Because I have no idea how it could.

Related, it seems like Valve should be providing a build script to handle this alias "manipulation".
https://codepen.io/punkydrewster713/post/package-web-project-for-steam#bonus-rapid-fire-things-you-should-know-about-steam-4
> Uploading your game to Steam involves installing the Steam SDK to your computer. You copy your builds (same content as the dist folder above) into a specified location and run Valve's build script. Most of the documentation is for Windows, but the SDK works fine on Mac, too. Read the documentation. This screencast helped me wrap my head around the process.

That post also says nothing special needs to be done by electron-builder 😅

**Comment by Faksprod** [comment]
Yes replacing alias by their original files do the trick. I am now able to upload my .APP file on Steamworks and I can run it from the Steam library (didn't pass Steam validation yet, I'm beta testing before releasing).

Thanks for sharing this post which I had read months ago 🙏  but I didn't find anything talking about alias "manipulation/organization".

I'm not sure the Steam SDK goal/job is to organize/package your files into a build. From what I understood and tried:
- YOU have to make your own build
- THEN you can use the Steam SDK to upload your build (which is your .APP file or .EXE or whatever) through what they call the SteamPipe.

But the SDK doesn't run scripts that will make a build from your files.

**Comment by mmaietta** [comment]
Very interesting! Well glad to hear it worked. Can this issue be closed then? 
If you'd like to tie your script in with electron-builder, you can use the `afterPack` hook to execute the script before signing

**Comment by Faksprod** [comment]
Thanks for the **afterPack** trick I will give it a try. I usually launch my bash script  from the package.json "scripts" like this:
```
"scripts": {
        "start": "electron .",
        "build": "electron-builder",
        "build-mac": "electron-builder --mac",
        "build-mac-steam": "electron-builder --mac && bash build/osx-steam-replace-alias-frameworks.sh",
        "build-mac-mas": "electron-builder --mac && bash build/osx-mas-resign-and-package.sh",
        "build-win": "electron-builder --win"
    }
```

Yes you can close this issue.
Thanks for your help and time 🙏

**Comment by christophe-coyard** [comment]
Very usefull, many thanks ! 🙏

**Comment by samanpwbb** [comment]
I have been dealing with this same issue when attempting to upload a game to Steam, figured I'd share some advice. There's definitely a bug in Steam's system somewhere that breaks alias files, but _only_ if you use the web GUI to upload your game. If I upload using `steamcmd` rather than the web gui, I don't encounter this problem and my game works fine.

**Comment by hichemfantar** [comment]
Has someone reported this bug to the steam team?
