### ISSUE TITLE
Exclude certain targets from Github release publishing

### ISSUE THREAD

**Issue by jwheare** [electron-userland/electron-builder#577]
* **Version**: 5.11.3

* **Target**: windows, linux (deb+appimage), mac (dmg, zip, mas)

I'd like to be able to e.g. build for MAS on CI but not then publish to a Github release. Could you add a publish_filter build option to exclude certain targets?

I suppose a workaround for this right now would be to exclude MAS from the package.json default build options, and then run a separate build process with `--target=mas --publish=never`, but that would slow down the builds somewhat.

**Comment by develar** [comment]
MAS will be excluded from publishing by default.

**Comment by jwheare** [comment]
Thinking about this some more, what I actually want is for the MAS version to be published on CI so that I can download it for separate submission, but not published to Github.

Am I right in thinking this can be achieved by using Travis' built in support for [uploading artifacts to S3](https://docs.travis-ci.com/user/uploading-artifacts/)? Does the electron-builder process support this parallel usage?

**Comment by develar** [comment]
@jwheare Travis uploading is not good because of https://github.com/travis-ci/travis-ci/issues/2577 If you want to publish MAS to s3 — it can be implemented.

**Comment by jwheare** [comment]
@develar Looks like that issue is actually resolved in the comments (though not closed) and also it looks like you can customise the `addons.artifacts.paths` with custom commands.

I am not particularly attached to S3, and in fact it may be overcomplicating matters. I just want to be able to easily download it from *somewhere*. Maybe the Github release is after all the best place for it, since I am already downloading artifacts from there to perform final sanity testing. I just have to remember to remove it from the release before publishing it.

**Comment by develar** [comment]
Set `build.mas.publish` to `null` to disable publishing or set to `bintray` to publish to bintray ("to easily download it from somewhere."). Bintray — set package name to repository name, bintray repository — standard `generic`.
