### ISSUE TITLE
Rebuild phase not working as expected for Windows in some libs

### ISSUE THREAD

**Issue by Sharcoux** [electron-userland/electron-builder#5770]
* **Version**: 22.10.5

* **Electron Version**: 10.4.2
* **Electron Type (current, beta, nightly)**:

* **Target**: win32 x64

I think that there is an issue with the build process for win platform.

I created a minimal code that can reproduce the error. You can find the project [here](https://github.com/Sharcoux/electron-demo) and you can find the exe [here](https://drive.google.com/file/d/12zrAZnT33dfWeDCOABazWtI6InedzKrl/view?usp=sharing) if you want to see by yourself.

I'll present you the code quickly so that you can understand the issue.

The app was created with create-react-app. I removed everything unnecessary.

In `public/electron.js` you will find the minimal code needed to handle the electron app. Just note that it's calling 'ffi-napi' module.

In `src` you have just the app itself, which is just a 'Welcome' text

The electron build will rebuild all the node modules:

`  • rebuilding native dependencies  dependencies=ffi-napi@3.1.0, ref-napi@3.0.2, ref-napi@2.1.2 platform=win32 arch=x64`

The packaged app will work 100% fine on Mac and Linux, but on Windows I will get:

![image](https://user-images.githubusercontent.com/797545/113462373-d34f8380-9420-11eb-9daf-3ded3e33ae26.png)

I could fix it by disabling npmRebuild and running `node-gyp -C node_modules/ffi-napi clean configure --target_arch=x64 --target_platform=win32` but I don't think that it is the expected way of using electron-builder

**Comment by mmaietta** [comment]
Hi @Sharcoux, are you building a multi-arch windows installer? (any combo of ia32/x64/arm64)
This may be an issue in https://github.com/develar/app-builder

**Comment by Sharcoux** [comment]
Not unless this is done against my will. I'm not specifying the architecture, and the logs says that it's building for x64.
