### ISSUE TITLE
node addon not working in production mode

### ISSUE THREAD

**Issue by Kamran95** [electron-userland/electron-builder#5775]
**Describe the bug**
Project runs fine when run locally with command npm run electron:serve but gives error when build using command npm run electron:build
[electron-c-plus-plus.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/6262588/electron-c-plus-plus.zip)
used different node loader but nothing seems to be working
**Error**
Cannot find module './build/Release/addon.node'
Require stack:
- electron/js2c/worker_init

**To Reproduce**
- npm install
- node-gyp configure
- node-gyp build
- ./node_modules/.bin/electron-rebuild
- npm run electron:build #to generate build file in dost_electron
- install build file and run error will appear in console

**Expected behavior**
worker should load c++ file build with name addon.node in directory build/release/addon.node and console log 'sum() World'
as in code worker.js line number 8.
it works as expected but gives error in build

C++ code is mentioned in file src/addon.cc

**Environment (please complete the following information):**
- mac os
- node version : 14.16.0
- electron 11

**Additional context**
Project has been added as attachment to run this project use following commands

- npm install
- node-gyp configure
- node-gyp build
- ./node_modules/.bin/electron-rebuild
- npm run electron:serve #to run locally
- npm run electron:build #to generate build file in dost_electron

[electron-c-plus-plus.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/6262593/electron-c-plus-plus.zip)

**Comment by mmaietta** [comment]
AFAICT, I don't see it binding anywhere or an electron-builder config to pack the built addon or any webpack config, but I'm also not familiar with vue project configurations.

Also, for electron builds, you'll need something to rewrite the path as naturally the `./build/Release` won't be packed by default or be a fully defined path for the app to use

**Comment by Kamran95** [comment]
> AFAICT, I don't see it binding anywhere or an electron-builder config to pack the built addon or any webpack config, but I'm also not familiar with vue project configurations.
> 
> Also, for electron builds, you'll need something to rewrite the path as naturally the `./build/Release` won't be packed by default or be a fully defined path for the app to use. That would be why the path works in local dev, but never is packed into prod bundle.

i have used node-loader but still no progress
is there anyway you may provide example code or link for your second pint
it would help me a lot

**Comment by mmaietta** [comment]
Sure thing, however it's for webpack

Excerpt `webpack.config.ts`
```
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    loader: "ts-loader",
                    exclude: /node_modules/
                },
                {
                    test: /\.js$/,
                    // Finds node addons in build/Release and node_modules
                    loader: "node-bindings-loader"
                },
                {
                    test: /\.node$/,
                    // Converts paths from source code and resolved paths from `node-bindings-loader` to use __dirname or process.execPath
                    loader: "awesome-node-loader",
                    options: {
                        useDirname: !packDistributable
                    }
                }
            ]
        },
        // Bundle all deps when building dist (except native modules), otherwise streamline development by just using local node_modules dir
        externals: packDistributable ? [ 'electron-deeplink.node' ] : [nodeExternals()],
        resolve: {
            extensions: [".js", ".ts", ".node"],
            alias: resolveTsAliases(path.resolve("tsconfig.json"))
        },
```

Excerpt: electron-builder.js
```
    asar: true,
    files: [
        "out",
        "!node_modules",
        "!**/*.node",
        "!**/*.LICENSE.txt",
        "!**/*.map"
    ],

    extraFiles: [
        {
            from: "build/Release",
            to: nodeAddonDir,
            filter: "*.node"
        },
        {
            from: "node_modules/electron-deeplink/build/Release",
            to: nodeAddonDir,
            filter: "*.node"
        }
    ],
```
