### ISSUE TITLE
Electron-Builder does not recognize configuration js files with hyphens in their filenames

### ISSUE THREAD

**Issue by KaminoRyo** [electron-userland/electron-builder#5778]
* **Version**: 22.10.5

* **Electron Version**:12.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: Windows

As the title says. 
I originally used a config file named "electron-builder.json". This works fine.
I got some typing advice in [this issue](https://github.com/electron-userland/electron-builder/issues/5563) so I changed it to "electron-builder.js". 
I rewrote it as follows.

```js
module.exports = {
  "app_id": "Application ID"
  ...
}
```

When I try to build the EXE, it does not display a message and exits without creating an EXE.
I was confused, but I renamed the file to "electronBuilder.js". This works. 
You may not need to fix it, but I think it's better to display an error message or document it.

**Comment by mmaietta** [comment]
My config is electron-builder.js and it works perfectly fine.

Your config for app_id is incorrect, it's `appId`.  That's why it exits early, because the config is incorrect.

For type safety, use this approach in `electron-builder.js`
```
/**
* @type {import('electron-builder').Configuration}
* @see https://www.electron.build/configuration/configuration
*/
const options = { 
   ....yourElectronBuilderConfig
}
module.exports = options
```

**Comment by KaminoRyo** [comment]
@mmaietta
I made a mistake when writing here. It's actually "appId". 
Please, reopen this issue.
Then I'm confused to see your writing. I think I need to disclose more information. 

This is my "electron-builder.js".
```js
const option = {
	"appId": "[hidden]",
	"productName": "[hidden]",
	"artifactName": "${name}-${version}-${os}-${arch}.${ext}",
	"copyright": "[hidden]",
	"directories": {
		"output": "app-${name}"
	},
	"win": {
		"target": "zip",
		"icon": "[hidden].ico"
	},
	"portable": {
		"useZip": true
	},
	"mac": {
		"target": "zip",
		"category": "[hidden]",
		"icon": "[hidden].icns",
		"entitlements": "./entitlements.plist",
		"entitlementsInherit": "./entitlements.plist",
		"minimumSystemVersion": "10.14"
	},
	"files": [
		"dist/**/*",
		"![hidden]"
	],
	"asar": false,
}
module.exports = option
```
and I'm using webpack to call "electron-builder --config ./electron-builder.js" command.

Oh, by the way, I'm calling from the console screen of Visual Studio Code.
Whenever this trouble occurs, the electron-builder.js file will be opened to show the source code.😮
It will not open when the EXE is successfully generated with "electron-builder.json" or "electronBuilder.js".
Is the problem with how to call the command? Umm.....🤔

**Comment by mmaietta** [comment]
Can you please rerun the command with debug enabled and copy the log here?
`DEBUG=electron-builder npx electron-builder'

**Comment by KaminoRyo** [comment]
Hi, @mmaietta 
I set the environment variable.
I tried to build but it quit with nothing displayed.😥
By the way, if you build using electronBuider.js, more detailed logs will be written out than usual.
Therefore the environment variables themselves seem to be valid. 

this is log.
  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=[hiddenPath]\electronBuilder.js
  • writing effective config  file=[hiddenPath]\builder-effective-config.yaml
  • map async       taskCount=1
  • map async       taskCount=3
  • no native dependencies
  • packaging       platform=win32 arch=x64 electron=12.0.1 appOutDir=[hiddenPath]\win-unpacked
  • Unpacking electron zip  zipPath=undefined
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=73
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • path doesn't exist  path=[hiddenPath]\soft.ico
  • path resolved   path=[hiddenPath]\soft.ico outputFormat=ico
  • building        target=zip arch=x64 file=[hiddenPath]\.zip
