### ISSUE TITLE
Unable to override "https://electronjs.org/headers" during electron-builder install-app-deps

### ISSUE THREAD

**Issue by slawomirmuniak** [electron-userland/electron-builder#5781]
* **electron-builder  Version**: 22.10.5 
* **Electron Version**: 11.3.x
* **Electron Type (current, beta, nightly)**: current
* **Target**: win

It is not possible to override `npm_config_disturl` during `electron-builder install-app-deps`
this setting depends on some weird (for me) parameter `useCustomDist`

https://github.com/electron-userland/electron-builder/blob/a879ba7f02ea704084b9672d6b9c9a47b7e5c27d/packages/app-builder-lib/src/util/yarn.ts#L63

But as I have checked this parameter is always true:

https://github.com/search?q=org%3Aelectron-userland+useCustomDist&type=code

It is important for me to fast fix this, but I am not sure how it should be changed properly (without breaking changes to projects using it).

Why I need this change?
I have an environment with restricted network access rules. So I am getting:
`    gyp verb created nodedir C:\Users\Administrator\.electron-gyp\11.3.0`
`    gyp http GET https://electronjs.org/headers/v11.3.0/node-v11.3.0-headers.tar.gz`
`    gyp WARN install got an error, rolling back install`

I have downloaded all needed files to our secure repository, but I am unable to make it work with the new dist-url.

**Comment by mmaietta** [comment]
It looks like you can override it via `process.env`
https://github.com/electron-userland/electron-builder/blob/a879ba7f02ea704084b9672d6b9c9a47b7e5c27d/packages/app-builder-lib/src/util/yarn.ts#L44-L54

For a quick solution, just add a patch locally to set `useCustomDist` to false and then use `patch-package` to persist it across `npm install`s?
https://github.com/electron-userland/electron-builder/blob/a879ba7f02ea704084b9672d6b9c9a47b7e5c27d/packages/electron-builder/src/cli/install-app-deps.ts#L63

**Comment by slawomirmuniak** [comment]
Great tip, thanks. It seems to work.
Another workaround that I have is to manually rebuild native package like here:

`https://www.electronjs.org/docs/tutorial/using-native-node-modules#manually-building-for-electron`

Then the correct headers are cached in electron-gyp, so the electron-rebuild does not need to download it.

**Comment by mmaietta** [comment]
Wait, are you using `electron-rebuild` for rebuilding native modules or using `electron-builder`'s implementation that is dependent upon https://github.com/develar/app-builder?

**Comment by slawomirmuniak** [comment]
*`electron-builder`
I am using it as an additional step in npm:
`"postinstall": "electron-builder install-app-deps",`
