### ISSUE TITLE
[Question] - MSI - Can I stop the desktop shortcut being installed on Windows? 

### ISSUE THREAD

**Issue by edwardcurtin** [electron-userland/electron-builder#5782]
Wondering if you could possibly offer some help - please and thanks

* **Version**: 
^22.8.0

* **Electron Version**:
* v9.2.1
* **Electron Type (current, beta, nightly)**:
* Current

* **Target**: 
Windows / Mac / Linux - Question above relates to msi for windows 

Just a quick question we have a requirement not to install a desktop icon when we run our msi installer, wondering if currently there is a way of configuring same not to be dropped to the desktop as part of the msi installer running, were reluctant to have to switch to another method of generating a msi in order to stop a desktop icon being installed via the generated installer if at all possible, and are hopeful that we can maintain use of Electron Builder.

**Comment by mmaietta** [comment]
Would this solve your request?
`createDesktopShortcut: false`
https://www.electron.build/configuration/nsis

**Comment by edwardcurtin** [comment]
Afraid that config setting only works for the nsis installer and our
requirement is for a MSI installer
