### ISSUE TITLE
Native node module is very slow after packaged. 

### ISSUE THREAD

**Issue by jpkli** [electron-userland/electron-builder#5785]
In my project, I use a native node module, which is a database system mostly written in C++, that reads and writes to the userData folder. It runs fine and the native node module has very good performance in development mode. But after packaged using electron-builder, the app can still run, but the database performance is very poor (~100X slower). Any help is very appreciated.

electron-builder version: 22.10.5
electron version: 12.02 and 11.4.2 ( I tested both, and the results are the same)
node version: 14.16.0
MacOS version: 10.15.7 (only tested on Mac)

I am using webpack to do the bundling, and I tried both node-loader and the webpack externals configs, but the results are the same. I also tried packaging with and without asar, and still not working.

**Comment by mmaietta** [comment]
Can you create a minimum repro repo for this? 

Related, have you checked whether electron-packager or electron-forge have the same issue? There's an interactive CLI that could potentially make a great test case for this:
https://github.com/Urucas/electron-packager-interactive

**Comment by jpkli** [comment]
Our app has the same issue when using electron-packager, so it seems is not related to electron-builder. But any pointers for helping to resolve this issue would be appreciated. Thank you again.
