### ISSUE TITLE
Channels not preserved after autoupdate

### ISSUE THREAD

**Issue by ashbrowning** [electron-userland/electron-builder#5786]
* **Version**: 22.10.5

 

* **Electron Version**: 9.1.2
* **Electron Type (current, beta, nightly)**: curret

* **Target**: 

I am setting up a three-channel build (alpha, beta and latest) and storing the assets on S3, with the intention that an alpha build can autoupdate to a newer alpha, beta or latest build. This works initially, however when I'm on a more stable build (say beta) and I release an alpha build of a higher version, this beta build will not auto-update to the new alpha.

The steps specifically:

- Release `1.0.0-alpha.1` 
- Release `1.0.0-beta.1`
- Run `1.0.0-alpha.1` and have it auto-update to `1.0.0-beta.1`
- Release `2.0.0-alpha.1`
- The instance currently running `1.0.0-beta.1` after being updated from the first alpha does not update to the new `2.0.0-alpha.1`.

To my mind, the original channel build should persist (unless I'm missing something). ie, if a build was originally published as an alpha, it should pick up all newer alpha builds even after it's been updated to beta/latest versions.

The cause of this seems to be that the `app-update.yml` file changes in the auto-update. In the example above, `app-update.yml` will update to follow the beta channel and thus miss all future alpha builds. 

For the time being, there are a couple of workarounds I can think of:
 - On init of running the app, generate and store the channel preference in a file (ie alpha) and assign that to `autoUpdater.channel` each time
 - When I want to publish a new beta build, I also publish to the alpha channel with `generateUpdatesFilesForAllChannels: false`

**Comment by mmaietta** [comment]
Wait, is this a bug report or a feature request?

**Comment by ashbrowning** [comment]
I would argue it's a bug, or if it's intended behaviour this should be made clearer in the documentation.

To my mind, if I get a build on the alpha channel, I should be able to update to all future alphas as well as any betas/latests in between. Today by default, if I auto-update from an alpha build to a beta build, I will only get future beta/latest builds as `app-update.yml` will point to the beta channel and not keep pointing to the alpha channel.
