### ISSUE TITLE
Support video acceleration (VA-API) on Linux

### ISSUE THREAD

**Issue by pcworld** [electron-userland/electron-builder#5788]
* **Target**: affects snap, AppImage, probably also others like flatpak

Latest Electron supports hardware-accelerated video decoding on Linux with VA-API: https://github.com/electron/electron/issues/18942#issuecomment-793855814
However it seems that targets snap, AppImage and probably also others like flatpak are missing the libraries required for hardware-accelerated video playback, like libva and possibly others.

**Comment by mmaietta** [comment]
Does electron-builder need to provide these by default? My immediate assumption is to just allow users to configure it through `depends` field: https://www.electron.build/configuration/linux#debian-package-options
`snap` has `stagePackages` and `buildPackages`: https://www.electron.build/configuration/snap

Could you describe a bit further on what libraries are missing and why/how the current electron-builder config doesn't work for it? This is a new field/subject for me 😅
