### ISSUE TITLE
Potential trojan in latest release?

### ISSUE THREAD

**Issue by njbmartin** [electron-userland/electron-builder#579]
* **Version**: ^5.12.0

* **Target**: Windows

when installing the latest version via npm, McAfee Anti-virus removes the following file: `electron-winstaller-fixed\vendor\WriteZipToSetup.exe` which is needed for packaging the installer.

It detects the following virus/trojan: Artemis!93D2D59A3747

5.11.3 does not have this issue.

**Comment by develar** [comment]
Duplicates https://github.com/electron/windows-installer/issues/106
