### ISSUE TITLE
[Snap] WebAuthn doesn't work in linux snap build

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#5790]
* **Version**: 22.10.5

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current 
 -

* **Target**:  snap

`WebAuthn` over USB (Yubikey) doesn't work in linux snap. In packaged linux build it works as expected.

**Comment by mmaietta** [comment]
From a quick google search, pretty sure that this is unrelated to electron-builder
https://github.com/webauthn-open-source/fido2-server-demo/issues/9
https://forum.snapcraft.io/t/fido-u2f-authentication-fails-in-chromium-snap-build/6130

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/5790#issuecomment-862781069
