### ISSUE TITLE
runAfterFinish is ignored on app auto-update

### ISSUE THREAD

**Issue by beliaev-maksim** [electron-userland/electron-builder#5792]
* **Version**: 22.9.1

* **Electron Version**: 11.0.1
* **Electron Type (current, beta, nightly)**:
 
* electron-updater: 4.3.8

* **Target**: NSIS

If you pack you app to work with electron-updater but at the same time want to allow user to specify installation path for the first installation

then your config file will look like:
```
"nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "runAfterFinish": true,
      "shortcutName": "my name"
    }
```

for the first run it is fully OK, however, when auto-update is done, app is not auto-restarted but stuck on last installation page with "start the app" checkbox ticked and user has to manually click Finish to start the app

also see #1151

**Comment by asd281533890** [comment]
I've made it possible to skip the last installation page with "start the app" and run the app automatically after auto-update completes by including an nsh script. Here's the script.
```
!macro customFinishPage
  Function StartApp
    ${If} ${isUpdated}
      StrCpy $1 "--updated"
    ${Else}
      StrCpy $1 ""
    ${EndIf}
    ${StdUtils.ExecShellAsUser} $0 "$launchLink" "open" "$1"
  FunctionEnd

  Function finishPageCustomPRE
    ${If} ${isUpdated}
      HideWindow
      Call StartApp
      Abort
    ${EndIf}
  FunctionEnd

  !ifndef HIDE_RUN_AFTER_FINISH
    !define MUI_FINISHPAGE_RUN
    !define MUI_FINISHPAGE_RUN_FUNCTION "StartApp"
  !endif

  !define MUI_PAGE_CUSTOMFUNCTION_PRE finishPageCustomPRE
  !insertmacro MUI_PAGE_FINISH
!macroend
```
