### ISSUE TITLE
macOS application is signed and notarized but getting warning on startup ("abc.app" cannot be opened because the developer cannot be verified.)

### ISSUE THREAD

**Issue by MetinYarci** [electron-userland/electron-builder#5793]
* **Version**: 22.10.5

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**:

* **Electron  Updater Version**: 4.3.5

* **Target**: mac

I have an electron application, it is successfully signed and notarized. After it is uploaded to AWS S3, and downloaded to my computer, it gives the warning "abc.app cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.". 

I followed exactly the same steps in the blog about signing and notarizing apps.
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

My electron application depends on "active-win" npm package, and this package is detected automatically, and is unpacked to "app.asar.unpacked" directory.
It also depends on "screenshot-desktop" npm package, and this is not automatically detected, so it is unpacked by the help of the below config.
```
  "build": {
    "asarUnpack": [
      "node_modules/screenshot-desktop/lib/win32"
    ],
...
  }
```

If "active-win" and "screenshot-desktop" is not used, then there is no warning about verification of the developer at startup and it is working as expected. So, I think there is an issue if there is a package unpacked in asar. How can this be fixed?

This is my configuration in entitlements.mac.plist 

```
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.device.microphone</key>
    <true/>
  </dict>
</plist>
```

and this is the configuration about signing
```
  "build": {
    "mac": {
      "category": "public.app-category.productivity",
      "hardenedRuntime": true,
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.plist",
      "gatekeeperAssess": false
    },
  ...
  }
```

**Comment by 9oelM** [comment]
I had a similar issue, and the culprit was that one of my native modules did not have a support for Big Sur yet. It may be worth asking the developers of the modules that you are using if they've handled Big Sur. 
Otherwise.. if it's not Big Sur, I've got no clue.

**Comment by mmaietta** [comment]
Can you verify that any binaries with "screenshot-desktop" are properly being signed?

One thing you can add to your "mac" config is `binaries: []` to force identify certain files to be signed
https://github.com/electron-userland/electron-builder/blob/66f01bba33523544813418332a5643f8b09f5421/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141

**Comment by MetinYarci** [comment]
> Can you verify that any binaries with "screenshot-desktop" are properly being signed?
> 
> One thing you can add to your "mac" config is `binaries: []` to force identify certain files to be signed
> https://github.com/electron-userland/electron-builder/blob/66f01bba33523544813418332a5643f8b09f5421/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141

How can I verify them to be properly signed?

**Comment by MetinYarci** [comment]
> > Can you verify that any binaries with "screenshot-desktop" are properly being signed?
> > One thing you can add to your "mac" config is `binaries: []` to force identify certain files to be signed
> > https://github.com/electron-userland/electron-builder/blob/66f01bba33523544813418332a5643f8b09f5421/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141
> 
> How can I verify them to be properly signed?

I tried to use this command, but it says that this file is not properly signed.
spctl --assess -vvv /Applications/myapp.app/Contents/Resources/app.asar.unpacked/node_modules/active-win/index.js
/Applications/Pqtrace.app/Contents/Resources/app.asar.unpacked/node_modules/active-win/index.js: rejected
source=no usable signature

However, 
1) I added all the files in the app.asar.unpacked directory in the "mac" config binaries attribute.
    "mac": {
       ...      
      "binaries": [
        "node_modules/active-win/index.js",
        "node_modules/active-win/lib/linux.js",
        "node_modules/active-win/lib/macos.js",
        "node_modules/active-win/lib/windows.js",
        "node_modules/active-win/license",
        "node_modules/active-win/main",
        "node_modules/active-win/package.json",
        "node_modules/screenshot-desktop/lib/win32/app.manifest",
        "node_modules/screenshot-desktop/lib/win32/index.js",
        "node_modules/screenshot-desktop/lib/win32/screenCapture_1.3.2.bat"
      ]

2) I removed disable-library-validation from entitlements.mac.plist
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>

3) The command spctl --assess -vvv still rejects, but I don't get the warning "abc.app cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.". any more.

Thank you @mmaietta , my issue is resolved.

**Comment by mmaietta** [comment]
I'm not positive how to verify a specific file signature, only `.app`. My best guess is you probably can via: `find . -name "*.node"  -print0 | xargs -0 -n 1 spctl -a -vv`?
Replace "*.node" with whatever file extensions/names you're looking for.
If that doesn't work, then I'd suggest trying different keywords in Google 🙂
