### ISSUE TITLE
when cancel update, the temp-updater file  is not close

### ISSUE THREAD

**Issue by liuestc** [electron-userland/electron-builder#5795]
when cancel update, the temp-update file  is not close,

when I try to update again, the program will attempt to remove temp-update file but failed.

in this case ,the log is

`Error on remove temp update file: Error: EPERM: operation not permitted, unlink `

the updater floder will appeare two files : **temp.exe**   **0-temp.exe**

----

I think when write fileStream occured err ,we should close the stream

httpExxcutor.js

```
  for (const stream of streams) {
    stream.on("error", error => {
++      // fileOut.close();
      if (!options.options.cancellationToken.cancelled) {
        options.callback(error);
      }
    });
    lastStream = lastStream.pipe(stream);
  }
```

[related](https://github.com/electron-userland/electron-builder/pull/3845)

**Comment by SuperKirik** [comment]
Have the same issue, 
Is it solved somehow ?

**Comment by xibaohuole** [comment]
I had the same problem，But the problem I ran into was that the file didn't end properly when the network went wrong，
I solved it the following way
httpExxcutor.js > configurePipes(fn)
```
for (const stream of streams) {
        stream.on("error", (error) => {
            fileOut.close();
            if (!options.options.cancellationToken.cancelled) {
                options.callback(error);
            }
        });
        lastStream = lastStream.pipe(stream);
    }
    fileOut.on("finish", () => {
        fileOut.close();
    });
    response.on("error", () => {
        console.log("Here's the code I added");
        fileOut.close();
    });```

**Comment by xibaohuole** [comment]
I think it's the same problem 
https://github.com/electron-userland/electron-builder/issues/7056
