### ISSUE TITLE
NSIS auto update for all users not working

### ISSUE THREAD

**Issue by majorgeek85** [electron-userland/electron-builder#5796]
electron-builder:
22.10.5

electron-updater:
4.3.8

Electron:
10.4.2

Target:
NSIS

Settings:

"nsis": {
      "oneClick": false,
      "perMachine": false,
      "createDesktopShortcut": true,
      "allowToChangeInstallationDirectory": true,
      ...
}

I'm using: autoUpdater.checkForUpdatesAndNotify(); on app startup

Steps to reproduce:
Build and publish version 1.0
Build and publish version 1.1

If I install 1.0 for a single user and everything is fine. It detects an update when I close uninstalls and installs the update.

If I install 1.0 for all users, it detects update, when I close, asks permissions to uninstall, the app is uninstalled, and then it is not installed again. No errors, logs, nothing, just empty folder.

I noticed other closed tickets regarding this issue, but it seems it was not fixed, or the bug exists again.

Any help would be appreciated.

Best Regards,
Nelson Oliveira

**Comment by mmaietta** [comment]
Hi there!
Can you link the closed tickets here so I can track this better?

**Comment by mansoor93** [comment]
hi @majorgeek85 were you able to fix this? facing the same issue

**Comment by mansoor93** [comment]
hi @mmaietta 
here are the tickets similar to this
https://github.com/electron-userland/electron-builder/issues/5468
https://github.com/electron-userland/electron-builder/issues/4474
