### ISSUE TITLE
"Windows 7 or above is required" - Electron autoupdate fails on latest windows update.

### ISSUE THREAD

**Issue by EdvinM** [electron-userland/electron-builder#5807]
* **Version**: 22.10.5

* **Electron Version**: 11.4.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

Three days ago, I have updated my Windows machine to latest windows build: https://support.microsoft.com/en-us/topic/april-13-2021-kb5001330-os-builds-19041-928-and-19042-928-cead30cd-f284-4115-a42f-d67fec538490
and since then, I cannot use auto-updater anymore.

The classic error "**Windows 7 or above is required**" shows after I hit the update button. 
At first I thought it was because I changed the windows nsis to be built only for x64, but then I realized that neither my older builds can update.

Any thoughts on this?

**Comment by mmaietta** [comment]
😳
Would you mind pulling NSIS logs by trying this? https://github.com/electron-userland/electron-builder/issues/5119#issuecomment-811353612

I found where your error is being thrown:
https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/app-builder-lib/templates/nsis/common.nsh#L18-L24

**Comment by EdvinM** [comment]
@mmaietta I have tried to enable NSIS logging by going through the steps written on the link you referenced. The problem is that I am building my windows app on a macOS, and I stumbled upon the same issue as mentioned on [Issue #32](https://github.com/electron-userland/electron-builder-binaries/issues/32). Any ideas on this?

**Comment by mmaietta** [comment]
@EdvinM yeah, I'm running into the same issue.
For nsis on mac, I researched that you'll need to use this approach https://github.com/NSIS-Dev/homebrew-makensis
(It didn't install for me though ¯\\_(ツ)_/¯)

Once you're able to have that, you can override the makensis path via https://github.com/electron-userland/electron-builder/pull/6024/files#diff-8ad1d08aa2e58bd68d30240ff1f8390122d9a82ba65e7b57359629e03e246533R24
