### ISSUE TITLE
Prevent AppImage from changing name after auto-update

### ISSUE THREAD

**Issue by perry-mitchell** [electron-userland/electron-builder#5810]
* **Version**: 22.10.5

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux, AppImage

Hi! We're using a pretty standard Electron + Updater setup for [Buttercup](https://github.com/buttercup/buttercup-desktop), but we've noticed an issue when we update AppImage builds. The filename changes to include the _new_ version that we updated to. This causes a number of problems for us and our users, including the inability to easily map shortcuts to the file. For example: Setting Buttercup to be auto-started in Ubuntu yields nothing after the app has been updated and the name has changed.

Is there some way to disable this behaviour? Or perhaps some recommended method to manage this? I haven't seen any such option in the updater settings.

EDIT: Not sure if it could be related to #5477.

**Comment by mmaietta** [comment]
Hello! More than happy to accept a PR on this. 🙂 
Quick dev env setup can be found here: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by perry-mitchell** [comment]
Hi @mmaietta - I think I'm going to go with the approach listed in #2964, which seems to opt to simply leave out the version from the build artifact: https://github.com/electron-userland/electron-builder/commit/48a081159fcdde8218423fd680b17f3e30a8de15

This isn't ideal perhaps, but it makes sense for the AppImage itself to _not_ have the version in the filename, because if it were able to auto-update and keep the same filename, the version there would then be misleading. In this regard it works similar to the mac .app which also doesn't contain the version (though the .dmg does).

Thanks for responding, however. To those reading this now: I'd advise to simply omit the version from .AppImage artifacts. Electron updater will prevent renaming the file if it is omitted.
