### ISSUE TITLE
[WSL] app-builder.exe isn't downloaded on 22.8.1 and after

### ISSUE THREAD

**Issue by staniel359** [electron-userland/electron-builder#5812]
* **Version**: 22.8.1+

* **Electron Version**: 12.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

Hello. I'm running electron-builder on WSL and on version **22.8.0** it works fine, but after upgrade to **22.8.1** it doesn't download app-builder.exe and other .exe files, crashing with ENOENT.
What could be the problem?

**Comment by mmaietta** [comment]
You mentioned 22.8.1. Can you try using 22.10.5?

**Comment by staniel359** [comment]
@mmaietta I tried 22.10.5, but issue is still the same.

**Comment by staniel359** [comment]
**--- Update ---**

This happens in Windows Terminal after **electron-builder** is upgraded to **21.2.0** and **app-builder-bin** is upgraded to **3.4.3**.
Any ideas what has changed in these versions?

**Comment by staniel359** [comment]
Nevermind, the problem was gone with 22.10.5 version after Windows reinstall. That means it has nothing to do with electron-builder itself, sorry.
