### ISSUE TITLE
The value of updaterCacheDirName in 'app-update.yml' is not our expected.

### ISSUE THREAD

**Issue by byzhangkui** [electron-userland/electron-builder#5817]
* **Version**:  22.10.5

* **Electron Version**: 12.0.1
* **Electron Type (current, beta, nightly)**:  current

* **Target**:  Windows/macOS

electron-builder generate 'updaterCacheDirName' in 'app-update.yml' use the value of AppInfo.updaterCacheDirName, which generate from name in 'package.json'.

Out product use scope name in package.json such as 
`
{ 
  "name": "@OurCompany/OurProduct", 
  "productName": "OurProduct", 
  "version": "2.1.1", 
  ... 
} 
`
that cause the value of 'updaterCacheDirName' in app-update.yml is '@OurCompanyOurProduct', we expect that is 'OurProduct'.

We expect that 'updaterCacheDirName' is generated from 'productName', or can configurated in 'electron-builder.yaml'

**Comment by byzhangkui** [comment]
I expect that 'updaterCacheDirName'  can be configurated in 'electron-builder.yaml'

**Comment by Ares-Chang** [comment]
Hello, is there any other way to achieve this?

I am a novice and have been looking for a long time without finding any other way to use the value 'name' in package.json

Documentation and cases are not well represented

Do you have any good ideas?
