### ISSUE TITLE
Signing the app using SSL certificate

### ISSUE THREAD

**Issue by afshinm** [electron-userland/electron-builder#582]
* **Version**: 5.12.1

* **Target**: all

I'm trying to sign the app using an SSL Certificate and it says:

```
Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
```

While I'm sure I set the env variables correctly. 

I was wondering if it's possible to use an SSL cetificate to sign the app or not?

**Comment by develar** [comment]
Do you sign win or mac app?

> using an SSL Certificate

Is it valid codesign certificate?

**Comment by afshinm** [comment]
I'm trying to sign a mac app on mac. but I can try windows, too (I haven't tried yet)

> Is it valid codesign certificate?

Well, it's a wildcard valid SSL certificate.

**Comment by develar** [comment]
> Well, it's a wildcard valid SSL certificate.

Codesign cert is required. Web SSL cert is not suitable. Please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing#where-to-buy-code-signing-certificate
