### ISSUE TITLE
Automatic unpacking not working for screenshot-desktop npm package

### ISSUE THREAD

**Issue by sm-will** [electron-userland/electron-builder#5821]
* **Version**:  21.2.0

* **Electron Version**: 11.1.0

* **Target**: windows nsis

Per the docs:
```
Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set asarUnpack - please file an issue if this doesn’t work.
```

for the [screenshot-desktop](https://github.com/bencevans/screenshot-desktop) package, I have to specify
`"asarUnpack": ["node_modules/screenshot-desktop/lib/win32"],` to get it to unpack the executable - it doesn't automatically detect it.   `win32/screenCapture_1.3.2.exe` is the file needing to be unpacked on win.

It appears to be something [several others are dealing with as well](https://github.com/bencevans/screenshot-desktop/issues/135)

**Comment by sm-will** [comment]
Why yes it is, mr stalebot.  I'm not exactly sure what needs to be done to move it forward...I'm assuming a part of the packaging process is supposed to dynamically notice executables in packages, but for some reason, screenshot-desktop's exe isn't being picked up on.

Not sure what logic electron-builder is using to sniff those out.

**Comment by mmaietta** [comment]
Can you try using glob patterns?
```
"asarUnpack": ["node_modules/screenshot-desktop/lib/win32/*"]
```

**Comment by nihil-admirari** [comment]
Same issue with `windows-notification-state` and `macos-notification-state` on Windows and Linux, which should be unpacked automatically but aren't (see https://github.com/hovancik/stretchly/issues/976).

Some details: on Windows `ps-list`, which contains `exe`s does get auto-unpacked. `windows-notification-state` and `macos-notification-state` have `.node` modules (DLLs, not `exe`s) that must be built from sources, and they don't get auto-unpacked.

Electron: 13.1.2.
Electron builder: 22.11.7.
