### ISSUE TITLE
Unable to run a 32 bit Windows build on 32 bit platforms  (works running same build on 64 bit)

### ISSUE THREAD

**Issue by andrewrutter** [electron-userland/electron-builder#5822]
Running electron-builder 22.10.5 and electron 12.0.5 on a Mac (Mojave)

We are trying to build a windows win32 executable but when we do the application installs but will not start.  No errors are seen on the test device but the application simply refuses to start.  On a 64-bit machine the same build works without trouble.  The builds are being run from a Mac (Mojave) and then copied to the target test machines via Dropbox or over the local network.

We have tried testing the builds using both Windows 10 and 7 machines with the same effect.

Build is being run using the following in package.json:

electron-builder --win --ia32 -c.extraMetadata.main=build/electron.js

**Comment by mmaietta** [comment]
Can you please test this using 22.10.4? If still fails, then try 22.10.3? It'll significantly help me triage

**Comment by andrewrutter** [comment]
I have just tried on both of those older versions with the same result. I did also try a build dropping the --ia32 which did come up with an error as expected on deployment due to pushing a 64 bit build. Is there logging I can enable to catch what may be failing on startup or some other ways to assist in that triage process?

**Comment by mmaietta** [comment]
If you add this for logging, you may be able to debug further. Would you be willing to give it a shot?
https://github.com/electron-userland/electron-builder/issues/5119#issuecomment-811353612

**Comment by andrewrutter** [comment]
We ended up heading down a different packaging route which did not run into these issues but are back on this thread to try and get auto updates working.  We did run into problems with win 32 builds failing intermittently with a blank screen due to https://github.com/electron/electron/issues/28487 - there was a commit which reduced the stack size and caused issues.  As a result we are trying to run with an older electron version that does not suffer from this issue.

When launching the app from a bat file to try and capture output, we are seeing the following. Not sure if this helps.

```
[3580:0608/014012.483:ERROR:electron_api_top_level_window.cc(108)] Failed to convert NativeImage
[3672:0608/014012.723:ERROR:gl_surface_egl.cc(741)] EGL Driver message (Critical) eglInitialize: No available renderers.
[3672:0608/014012.723:ERROR:gl_surface_egl.cc(1247)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
Generated new staging user ID: 6015b574-a322-5ab6-abb2-e1f5497f26f7
[3672:0608/014013.745:ERROR:gl_surface_egl.cc(741)] EGL Driver message (Critical) eglInitialize: No available renderers.
[3672:0608/014013.745:ERROR:gl_surface_egl.cc(1247)] eglInitialize D3D9 failed with error EGL_NOT_INITIALIZED
[3672:0608/014013.745:ERROR:gl_initializer_win.cc(196)] GLSurfaceEGL::Initialize OneOff failed.
[3672:0608/014013.745:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
```

**Comment by nornagon** [comment]
Possibly related: https://github.com/electron/electron/pull/29474
