### ISSUE TITLE
Sign verification failed

### ISSUE THREAD

**Issue by shakogegia** [electron-userland/electron-builder#5824]
* **Version**:  22.10.5

* **Electron Version**:  11.3.0
* **Electron Type (current, beta, nightly)**: current
* **Target**: NSIS

Hi, I'm facing an error on windows after changing the certificate
```Sign verification failed, installer signed with incorrect certificate : publisherNames: COMPANY```

We had a code signing certificate that expired, so we brought a new EV Code signing certificate, but the new certificate is issued to a slightly different company name and I guess that's what causing the problem.

I tried to set old `publisherName` in electron builder configuration but I'm still getting the same error
Setting the `publisherName` in the config should resolve this error right? I think it does not work/not setting the publisherName I'm providing, or am I missing something?

has anyone faced the same issue?

**Comment by mmaietta** [comment]
Can you try setting `publisher` to the fully qualified name?
I pulled up this old ticket that seems related https://github.com/electron-userland/electron-builder/issues/4931

**Comment by shakogegia** [comment]
@mmaietta it gives me error
` - configuration.win has an unknown property 'publisher'.`

**Comment by mmaietta** [comment]
Looks like it's supposed to be in the specific exec config, such as in 
```
    "appx": {
      "publisher": "CN=Bob Doe, O=Bob Doe, STREET=123 Fake Street, L=London, S=London, PostalCode=A10 B42, C=GB",
      ...
    }
```
