### ISSUE TITLE
[Electron-updater] Problems with cashedInfo and fs-extra (Cannot read property 'sha512' of undefined)

### ISSUE THREAD

**Issue by fredikey** [electron-userland/electron-builder#5825]
* **Version**: 22.10.5

* **Electron Version**: 9.3.0
* **Electron Type (current, beta, nightly)**: current

* **electron-updater**: 4.3.8

* **Target**: macos

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/44212097/115965061-040e6e80-a530-11eb-96e6-d8cfbafad310.png">

It happens when some update already installed and autoUpdater want to download a new update
 

Issue almost fully related to https://github.com/electron-userland/electron-builder/issues/4928 but in my case update-info.json exists and **pathExists** method returns true   https://github.com/electron-userland/electron-builder/blob/6237e670a8ddd99ec8c076db86361c06c04eedd4/packages/electron-updater/src/DownloadedUpdateHelper.ts#L103-L110

When i tried to find the source of a bug I logged **cachedInfo** and found that bug occurred in **fsExtra.readJson** method, 
fsExtra tries to read update-info.json via readJson method but for unexpected reasons it returns undefined without even throwing an error. 

https://github.com/electron-userland/electron-builder/blob/6237e670a8ddd99ec8c076db86361c06c04eedd4/packages/electron-updater/src/DownloadedUpdateHelper.ts#L111-L122

And then it crashes when tries to read sha512 of undefined value
https://github.com/electron-userland/electron-builder/blob/6237e670a8ddd99ec8c076db86361c06c04eedd4/packages/electron-updater/src/DownloadedUpdateHelper.ts#L131-L137

Also there are some conditionals that can help to avoid an error but it checks only for null value, not undefined 😀 
https://github.com/electron-userland/electron-builder/blob/6237e670a8ddd99ec8c076db86361c06c04eedd4/packages/electron-updater/src/DownloadedUpdateHelper.ts#L124-L129
 
 So, in result there are two ways to fix that:
 1) Research problems with fxExtra.readJson
 2) Add check if **cachedInfo** is not undefined

**Comment by fredikey** [comment]
Problem was on my side, with dependency resolution and **fsExtra.readJson** as i said in comment above.  

**fs-extra** uses **jsonFile** library [under the hood](https://github.com/jprichardson/node-fs-extra/blob/master/lib/json/jsonfile.js#L3-L11) to interact with json files (readJson, writeJson and so on)

When I tried hypotheses with that library I found out a solution, steps that helped me: 
1) `yarn add jsonfile@latest` - install latest version directly to force libraries use it
2) Clear all .lock files and reinstall node_modules

<img width="459" alt="image" src="https://user-images.githubusercontent.com/44212097/116278464-2f42c900-a78f-11eb-9224-4ab0746f5c29.png">

**Comment by zac-jacobson** [comment]
Thanks for posting this, @fredikey . I had the same problem with electron-updater 4.3.9 and electron 12.0.17.  forcing the resolution of `jsonfile` to `^6.1` resolved the problem. Not sure what change between `jsonfile` 4.0 and 6.1 addresses the issue.
