### ISSUE TITLE
Custom scripts don't work, even when they are the same as what Electron-Builder uses

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron-userland/electron-builder#5826]
* **Version**:  ^22.10.5

* **Electron Version**:^12.0.4

* **Target**:  NSIS

Heres my package.json

`"build":{

    "appId": "com.example.nameelectrontest",
    "productName": "NameTest",
    "win":{
      "target": "nsis"
    },
    "nsis":{
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "./assets/app.ico",
      "uninstallerIcon": "./assets/app.ico",
      "installerHeader": "./assets/app.ico",
      "script": "./build/installer.nsi"
    }
  }`

All I did was copy-pasted all files found in app-builder-lib/templates/nsis to a build folder in my repo. SO I have the same exact nsi/nsh code that Electron-Builder uses.

I am getting this error:

`Output:

Output:
Command line defined: "APP_ID=com.example.nameelectrontest"
Command line defined: "APP_GUID=267981b0-3eab-545e-8942-3d9ddaad1e41"
Command line defined: "UNINSTALL_APP_KEY=267981b0-3eab-545e-8942-3d9ddaad1e41"
Command line defined: "PRODUCT_NAME=NameTest"
Command line defined: "PRODUCT_FILENAME=NameTest"
Command line defined: "APP_FILENAME=NameTest"
Command line defined: "APP_DESCRIPTION=First Electron Attempt"
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=/Users/kylecorbin/Documents/Github/Personal/ElectronApp"
Command line defined: "BUILD_RESOURCES_DIR=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/build"
Command line defined: "APP_PACKAGE_NAME=ElectronApp"
Command line defined: "MUI_ICON=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/assets/app.ico"
Command line defined: "MUI_UNICON=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/assets/app.ico"
Command line defined: "APP_64=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/dist/ElectronApp-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=ElectronApp-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=2A97FA47A79314D6CB9D59522E09A7341816871FF4B089854D66BB8EEB010FED867B7BADF1590E9FD89EF449A429A1D4F8B6CAAB88EF06AAE998C666230C7410"
Command line defined: "COMPANY_NAME=kCorbin"
Command line defined: "APP_INSTALLER_STORE_FILE=electronapp-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "MULTIUSER_INSTALLMODE_ALLOW_ELEVATION"
Command line defined: "INSTALL_MODE_PER_ALL_USERS_REQUIRED"
Command line defined: "allowToChangeInstallationDirectory"
Command line defined: "SHORTCUT_NAME=NameTest"
Command line defined: "UNINSTALL_DISPLAY_NAME=NameTest 1.0.0"
Command line defined: "MUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "MUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "MUI_HEADERIMAGE"
Command line defined: "MUI_HEADERIMAGE_RIGHT"
Command line defined: "MUI_HEADERIMAGE_BITMAP=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/assets/app.ico"
Command line defined: "UNINSTALLER_ICON=/Users/kylecorbin/Documents/Github/Personal/ElectronApp/assets/app.ico"
Command line defined: "ESTIMATED_SIZE=179996"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE"
Processing script file: "<stdin>" (UTF8)

Error output:

Error output:
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro installApplicationFiles on macroline 91
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 161 -- aborting creation process`

Not sure what to make of this, when I don't use the 'script' key it builds fine. I don't see why these scripts work normally but not when passed in as custom scripts

**Comment by locomotiveboy** [comment]
I have the same problem, how did you solve it, can you give me some advices, thanks very much.

**Comment by nazar322** [comment]
Exact same issue but with version `23.6.0`.
I want to add a custom page to the installer, multiple posts here about it and no replies seems like nobody knows how to add a custom page (
Poor documentation, no examples, only makes it useful for trivial cases.
