### ISSUE TITLE
electron-rebuild  Can't it?  sharp、canvas、iohook There are problems ？There is a problem in compiling and surviving Window executable program under Mac

### ISSUE THREAD

**Issue by sujiewen** [electron-userland/electron-builder#5830]
macOS 10.15.7
electron 11.3.0、12.0.5
node v14.16.1

**There is a problem in compiling and surviving Window executable program under Mac！**

Building app with electron-builder:
  • electron-builder  version=22.10.5 os=19.6.0
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist_electronlc/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.28.3 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.28.3 platform=win32 arch=x64
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 6.1.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/lc/.npm/_prebuilds/6de17a-sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=13.0.1 runtime=electron arch=x64 libc= platform=win32)
    
                                    command=/usr/local/bin/node /Users/lc/st/wmswarehouse2/node_modules/prebuild-install/bin.js --platform=win32 --arch=x64 --target=13.0.1 --runtime=electron --verbose --force
                                    workingDir=/Users/lc/st/wmswarehouse2/node_modules/sharp
ExecError: /Users/lc/st/wmswarehouse2/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/lc/st/wmswarehouse2/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sujiewen** [comment]
Is there a solution?

**Comment by mmaietta** [comment]
I see the error is coming in from `app-builder`, which would be coming from https://github.com/develar/app-builder

Can you give `electron-rebuild` a shot and report back if that resolves your native modules correctly?

**Comment by sujiewen** [comment]
Building app with electron-builder:
  • electron-builder  version=22.10.5 os=19.6.0
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist_electronlc/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.28.3 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.28.3 platform=win32 arch=x64
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 6.1.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/lc/.npm/_prebuilds/6de17a-sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v89-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=13.0.1 runtime=electron arch=x64 libc= platform=win32)
    
                                    command=/usr/local/bin/node /Users/lc/st/wmswarehouse2/node_modules/prebuild-install/bin.js --platform=win32 --arch=x64 --target=13.0.1 --runtime=electron --verbose --force
                                    workingDir=/Users/lc/st/wmswarehouse2/node_modules/sharp
ExecError: /Users/lc/st/wmswarehouse2/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/lc/st/wmswarehouse2/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sujiewen** [comment]
As long as sharp is installed, the packaging will not work properly

**Comment by sujiewen** [comment]
demo address： 
https://github.com/sujiewen/testSharp

**Comment by mmaietta** [comment]
I still don't believe this to be an electron-builder issue.

The error code is simply the cascading/fallthrough error in that your prebuild doesn't exist at this url.
>prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v87-win32-x64.tar.gz

Where is that URL coming from?

**Comment by sujiewen** [comment]
I am sorry! To survive the corresponding libraries on different platforms, you need to delete and then compile

    "electron:build": "rm -rf node_modules/sharp && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=darwin sharp && vue-cli-service electron:build",
    "electron:build-win64": "rm -rf node_modules/sharp && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=win32 sharp && vue-cli-service electron:build --windows --x64",

**Comment by AlanSean** [comment]
> 我仍然不相信这是电子制造商的问题。
> 
> 错误代码只是级联/失败错误，因为您的预构建在此 url 中不存在。
> 
> > 预构建安装 http 请求 GET https://github.com/lovell/sharp/releases/download/v0.28.3/sharp-v0.28.3-electron-v87-win32-x64.tar.gz
> 
> 该网址来自哪里？



from electron-builder 
```
  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=E:\github\image_compress\electron-builder.json
  • writing effective config  file=release\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.29.1 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.29.1 platform=win32 arch=x64
  • build native dependency from sources  name=sharp
                                          version=0.29.1
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 6.1.4
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.29.1-electron-v87-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ C:\Users\111\AppData\Local\npm-cache\_prebuilds\16a12e-sharp-v0.29.1-electron-v87-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.29.1/sharp-v0.29.1-electron-v87-win32-x64.tar.gz
    prebuild-install WARN install Request timed out

```
