### ISSUE TITLE
No app icon on OS X El Capitan

### ISSUE THREAD

**Issue by plakak** [electron-userland/electron-builder#5832]
* **Version**: 22.10.5

* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**: current

* **Target**:  macOS

I've got raport from one of the users that uses older macOS there is no application icon on his system. I installed `El Capitan` via Parallels and confirmed that there is no icon present.

The icon is there on `Catalina` &`Big Sur`.
I see no errors about the assets during build. Tried on both `Intel` & `M1`, `x64` & `Universal` - the same result.

![Screen Shot 2021-04-26 at 20 31 56](https://user-images.githubusercontent.com/13939486/116133450-06f39580-a6cf-11eb-9d66-cbd82f903ff1.png)

Here's my config:
``` 
// common.config.js
module.exports = (isDev = false) => ({
  artifactName: isDev ? '(${os})${productName}-${version}.${ext}' :'${productName}-${version}.${ext}',
  directories: {
    buildResources: 'src/assets',
  },
  files: [
    'dist/',
    'src/**/*',
    '!src/view${/*}'
  ]
});
```

```
// mac.build.js (entrypoint)
const common = require('../build.common.config')(true);

common.appId = 'XXX';
common.directories.output = 'release/dev';
common.mac = {
  target: [
    {
      target: 'dmg',
      arch: ['universal']
    }
  ],
  type: 'development',
  electronLanguages: ['en'],
  entitlements: 'build/mac-common/entitlements.mac.plist',
  provisioningProfile: 'build/mac-common/dev.provisionprofile'
};

common.dmg = {
  contents: [
    {
      x: 140,
      y: 220
    },
    {
      x: 390,
      y: 220,
      type: 'link',
      path: '/Applications'
    }
  ]
};

module.exports = common
```

Any help appreciated 🙂

**Comment by mmaietta** [comment]
Did this work on a previous version of electron-builder or is it a longstanding issue?

**Comment by plakak** [comment]
The oldest version of the app built with `22.7.0` and `Electron 9` has the same problem.

The icon shows up correctly on Mac OS High Sierra which is the oldest OS we've tested until got this bug report from El Captain.

**Comment by plakak** [comment]
It's still relevant but probably low priority.

**Comment by mmaietta** [comment]
Hmmm, can you list what image sizes are being bundled into your `icns` file? I'm wondering if it has to do with retina resolutions (1x, 2x, etc)
