### ISSUE TITLE
Is there any way to check available updates on debian app?

### ISSUE THREAD

**Issue by fredikey** [electron-userland/electron-builder#5837]
* **Version**: 22.10.5

* **Electron Version**: 9.3.0
* **Electron Type (current, beta, nightly)**: current

* **electron-updater**: 4.3.8

* **Target**: Linux, debian

I know that **electron-updater** supports only AppImage, but in my case I don't need auto-updates, i simply want to show a modal window with such message "New update available, you can download it on https://example.com/updates/"

How can i achieve that without developing custom update server ?

**Comment by Levminer** [comment]
Hi!

If you use GitHub releases you can use the GitHub API. I'm using node-fetch for this.
Store the current app version in a variable (let version = "1.1.0")
Than make a request to the API and get the tag_name then you can compare with the current version.

Example code:
```
		const api = async () => {
			try {
				await fetch("https://api.levminer.com/api/v1/authme/releases")
					.then((res) => res.json())
					.then((data) => {
						try {
							if (data.tag_name > version) {
								dialog
									.showMessageBox({
										title: "Authme",
										buttons: ["Yes", "No"],
										defaultId: 0,
										cancelId: 1,
										type: "info",
										message: `
										Update available: Authme ${data.tag_name}
										
										Do you want to download it?
					
										You currently running: Authme ${version}
										`,
									})
									.then((result) => {
										update = true

										if (result.response === 0) {
											shell.openExternal("https://github.com/Levminer/authme/releases/latest")
										}
									})
							}
						} catch (error) {
							return console.log(error)
						}
					})
			} catch (error) {
				return console.log(error)
			}
		}
```
