### ISSUE TITLE
panic: runtime error: index out of range [-1] - icons.ConvertIcnsToPng 

### ISSUE THREAD

**Issue by Levminer** [electron-userland/electron-builder#5844]
* **Version**:  22.10.5

* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux

# Issue:

```
goroutine 1 [running]:
github.com/develar/app-builder/pkg/icons.ConvertIcnsToPng(0xc0000ca630, 0x2d, 0x7ffd9f40874a, 0x2e, 0x2, 0x2, 0xc0000ca630, 0x2d, 0xe53320)
	/Volumes/data/Documents/app-builder/pkg/icons/icns-to-png.go:60 +0x4ab
github.com/develar/app-builder/pkg/icons.doConvertIcon(0xc00012a400, 0x5, 0x8, 0xc00025ec20, 0x2, 0x2, 0x7ffd9f4086ec, 0x3, 0x7ffd9f40874a, 0x2e, ...)
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:226 +0xa0d
github.com/develar/app-builder/pkg/icons.ConvertIcon(0xc0000ad3c0, 0x97, 0x0, 0xf6400f7800000000)
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56 +0xd6
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1(0xc0002375f0, 0x40b705, 0xc2b0e0)
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33 +0x7f
github.com/alecthomas/kingpin.(*actionMixin).applyActions(0xc000124d98, 0xc0002375f0, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28 +0x6d
github.com/alecthomas/kingpin.(*Application).applyActions(0xc0000e8780, 0xc0002375f0, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557 +0xdc
github.com/alecthomas/kingpin.(*Application).execute(0xc0000e8780, 0xc0002375f0, 0xc00021b150, 0x1, 0x1, 0x0, 0x0, 0x0, 0x904545)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390 +0x90
github.com/alecthomas/kingpin.(*Application).Parse(0xc0000e8780, 0xc0000ae010, 0xf, 0xf, 0xc0000e8780, 0xc00008a058, 0x0, 0x0)
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222 +0x213
main.main()
	/Volumes/data/Documents/app-builder/main.go:90 +0x2c5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! authme@2.4.1 build: `electron-builder --publish=never --x64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the authme@2.4.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-29T22_15_27_280Z-debug.log
```

# Build:

```
	"build": {
		"productName": "Authme",
		"appId": "com.levminer.authme",
		"asar": true,
		"asarUnpack": [
			"app/import/src/py/*",
			"src/install.py",
			"src/remove.py",
			"src/version.py"
		],
		"win": {
			"target": [
				"nsis"
			],
			"icon": "img/icon.ico"
		},
		"nsis": {
			"installerIcon": "img/icon.ico",
			"uninstallerIcon": "img/icon.ico",
			"uninstallDisplayName": "Authme",
			"license": "LICENSE.md",
			"oneClick": false,
			"allowToChangeInstallationDirectory": true,
			"createDesktopShortcut": "always"
		},
		"linux": {
			"target": "deb",
			"maintainer": "levminer@levminer.com"
		},
		"mac": {
			"target": "dmg",
			"icon": "img/icon.icns",
			"category": "public.app-category.utilities"
		}
	},
```

**Comment by mmaietta** [comment]
That stacktrace is coming from GO-based dependency. You may want to file details to this project: https://github.com/develar/app-builder

**Comment by yuripourre** [comment]
Hey @Levminer , I am having the same problem, did you find a way to avoid it?

It only happens to me if I am using the `@rabbit-hole-syndrome/electron-forge-maker-portable` to build the windows target.

**Comment by Levminer** [comment]
> Hey @Levminer , I am having the same problem, did you find a way to avoid it?
> 
> 
> 
> It only happens to me if I am using the `@rabbit-hole-syndrome/electron-forge-maker-portable` to build the windows target.
> 
> 
> 
> ```
> 
> panic: runtime error: index out of range [-1]
> 
> goroutine 1 [running]:
> 
> github.com/develar/app-builder/pkg/icons.doConvertIcon({0xc0000d13c0, 0x4, 0x4}, {0xc000093f00, 0x2, 0x2}, {0xc00009a090, 0x3}, {0xc0000b4140, 0x31})
> 
> 	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:220 +0xa6e
> 
> github.com/develar/app-builder/pkg/icons.ConvertIcon(0xc0000d12c0)
> 
> 	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56 +0x73
> 
> github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1(0x0)
> 
> 	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33 +0x85
> 
> github.com/alecthomas/kingpin.(*actionMixin).applyActions(0x1, 0xc000130d80)
> 
> 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28 +0x5c
> 
> github.com/alecthomas/kingpin.(*Application).applyActions(0xc0000f6780, 0xc00025a510)
> 
> 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557 +0xa2
> 
> github.com/alecthomas/kingpin.(*Application).execute(0xc0000f6780, 0xc00025a510, {0xc00020f2b0, 0x1, 0x1})
> 
> 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390 +0x66
> 
> github.com/alecthomas/kingpin.(*Application).Parse(0xc0000f6780, {0xc0000d4010, 0x6, 0xb})
> 
> 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222 +0x165
> 
> main.main()
> 
> 	/Volumes/data/Documents/app-builder/main.go:90 +0x1ec
> 
> ```

Honestly, no idea. I think i ended up replacing the icon.

**Comment by yuripourre** [comment]
@Levminer alright! Thank you, I could successfully build without icon. I will try to build with a different icon or replace the icon after building.
