### ISSUE TITLE
macOS pkg written to same filename for x64 and arm64

### ISSUE THREAD

**Issue by andersk** [electron-userland/electron-builder#5847]
* **Version**: 22.10.5
* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**: current
* **Target**: macOS pkg for x64 and arm64

`electron-builder --mac pkg --x64 --arm64` builds both the x64 pkg and the arm64 pkg, but it writes them both to the same filename `Zulip-5.6.0.pkg`, so the latter immediately overwrites the former.

```
  • building        target=pkg arch=x64 file=dist/Zulip-5.6.0.pkg
…
  • building        target=pkg arch=arm64 file=dist/Zulip-5.6.0.pkg
```

I would expect the latter to go to `Zulip-5.6.0-arm64.pkg`, as already happens with DMG and zip.

**Comment by mmaietta** [comment]
Hi @andersk ! 
If you're specifying two separate archs, as opposed to using `--universal`, then you will need to provide an `artifactName` template that has the `${arch}` macro in it.

**Comment by andersk** [comment]
@mmaietta We already have `"build": { "mac": { "artifactName": "${productName}-${version}-${arch}.${ext}" } }`, which works for DMG and zip.

**Comment by andersk** [comment]
Minimal reproduction: https://gist.github.com/andersk/590d4b064e9e07506d6747d7b3a6a977

```console
$ git clone https://gist.github.com/andersk/590d4b064e9e07506d6747d7b3a6a977 empty-electron-app
$ cd empty-electron-app
$ yarn
$ yarn electron-builder --mac default --x64 --arm64
…
  • building        target=macOS zip arch=x64 file=dist/empty-electron-app-1.0.0.zip
  • building        target=DMG arch=x64 file=dist/empty-electron-app-1.0.0.dmg
…
  • building        target=macOS zip arch=arm64 file=dist/empty-electron-app-1.0.0-arm64.zip
  • building        target=DMG arch=arm64 file=dist/empty-electron-app-1.0.0-arm64.dmg
$ yarn electron-builder --mac pkg --x64 --arm64
…
  • building        target=pkg arch=x64 file=dist/empty-electron-app-1.0.0.pkg
…
  • building        target=pkg arch=arm64 file=dist/empty-electron-app-1.0.0.pkg
```

**Comment by mmaietta** [comment]
Big thanks for the gist! Wish other tickets had those provided more often 🙂 

I added the arch/pkg args to the build config and it repro'd there as well.  Found the issue seems to only exist with `pkg` target. I tested `zip` and `dmg` too and both worked correctly.

I think I was able to identify the fix, can you try out this patch?
File: `app-builder-lib+22.10.5.patch`
```
diff --git a/node_modules/app-builder-lib/out/targets/pkg.js b/node_modules/app-builder-lib/out/targets/pkg.js
index 9a53e36..abd8215 100644
--- a/node_modules/app-builder-lib/out/targets/pkg.js
+++ b/node_modules/app-builder-lib/out/targets/pkg.js
@@ -115,7 +115,7 @@ class PkgTarget extends _core().Target {
     const options = this.options;
     const appInfo = packager.appInfo; // pkg doesn't like not ASCII symbols (Could not open package to list files: /Volumes/test/t-gIjdGK/test-project-0/dist/Test App ßW-1.1.0.pkg)
 
-    const artifactName = packager.expandArtifactNamePattern(options, "pkg");
+    const artifactName = packager.expandArtifactNamePattern(options, "pkg", arch);
     const artifactPath = path.join(this.outDir, artifactName);
     await packager.info.callArtifactBuildStarted({
       targetPresentableName: "pkg",
```

**Comment by andersk** [comment]
Yeah, that works for me.
