### ISSUE TITLE
I am using rush for npm packages and monorepo

### ISSUE THREAD

**Issue by ahmadfaraz84** [electron-userland/electron-builder#5849]
* **Version**: 22.7.0

* **Electron Version**:11.1.0
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis

I am using rush npm packages, app works fine in development mode, but when I try to create distribution, there is an exception of missing module. Actually it is a nested dependency which is not directly inside node modules, but in .pnpm store in common folder, since I am using Microsoft Rush for installations.

**Comment by mmaietta** [comment]
Can you please post the error you have?

Also, I'm only able to provide support 22.10.5+, mostly because I joined the crew then.

**Comment by ahmadfaraz84** [comment]
> Can you please post the error you have?
> 
> Also, I'm only able to provide support 22.10.5+, mostly because I joined the crew then.

Yeah sure. I will create a github branch to reproduce the problem and share it with you.
I am sorry for late reply, I am just having some problem with Gmail notifications. I saw ur comment today.
