### ISSUE TITLE
${arch} in nsis artifactName causes build to fail

### ISSUE THREAD

**Issue by vespasianvs** [electron-userland/electron-builder#5857]
Hi all,

I *think* I've found a bug here, so thought I'd report it:

**Versions installed:**

"@capacitor-community/electron": "^1.4.2",
"electron-log": "^4.3.5",
"electron-notarize": "^1.0.0",
"electron-updater": "^4.3.8"
"electron": "^12.0.6",
"electron-builder": "^22.11.1"

npm@6.14.12
node@v14.16.1

**Build command:**
npm run build && ARCH=win64 NOTARIZE=disable electron-builder build --windows --x64

**Build config (this one *WORKS*):**

    "win": {
        "target": "nsis"
    },
    "nsis": {
        "artifactName": "Setup ${version} ${env.ARCH}.${ext}",
        "oneClick": false,
        "perMachine": false,
        "allowElevation": true,
        "allowToChangeInstallationDirectory": true,
        "deleteAppDataOnUninstall": true,
        "include": "./build/installer.nsh"
    },

**Build config (this one *FAILS*):**

    "win": {
        "target": "nsis"
    },
    "nsis": {
        "artifactName": "Setup ${version} ${arch}.${ext}",
        "oneClick": false,
        "perMachine": false,
        "allowElevation": true,
        "allowToChangeInstallationDirectory": true,
        "deleteAppDataOnUninstall": true,
        "include": "./build/installer.nsh"
    },

**Error shown:**

  • electron-builder  version=22.10.5 os=10.0.19042
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.6 appOutDir=dist\win-unpacked
  • building        target=nsis file=dist\Setup 2.2.7 x64.exe archs=x64 oneClick=false perMachine=false
  • building        target=nsis file=dist\Setup 2.2.7 x64.exe archs=x64 oneClick=false perMachine=false
  • output file is locked for writing (maybe by virus scanner) => waiting for unlock...  
  • building block map  blockMapFile=dist\Setup 2.2.7 x64.exe.blockmap
  ⨯ C:\Users\-----\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

* I note that electron builder is listed as 22.10.5 in the build message, this is despite me having 22.11.1 installed (and having done a clean npm install after removing node_modules and package-lock.json
* There is an error for 'cannot check updates' - this happens for both successful and unsuccessful builds.
* The build appears to fail because it is trying to build twice to the same file.
* This is a configuration that we have been using for some time, so something has changed somewhere (though ${arch} didn't used to do anything at all, hence me using the ENV variable instead).

Any suggestions? If it is somewhere where I'm going wrong, please let me know.

**Comment by mmaietta** [comment]
Curious, does this work for you on v22.10.5? That should help significantly with bisecting this issue

**Comment by mmaietta** [comment]
Hi all. Can you please try v22.11.2?

**Comment by mmaietta** [comment]
Hmmm, that might actually be related. That file hasn't changed since Nov 20, 2020 so I must assume it's related

This might all be related to this change? https://github.com/electron-userland/electron-builder/pull/5718
Ironically, it was designed to handle the `${arch}` macro, but it seems that it's not filtering out duplicates?
>It looks like it tries to build the 'default' architecture (as in the architecture of the machine I am on (which is a Windows x64 machine) as well as the one I have specified in the command line with --x64.

**Comment by vespasianvs** [comment]
Looks to me like it's a similar thing. I think the two issues are probably the same, and probably to do with that PR. If I can find a minute I'll try and have a look myself at what's going on!

**Comment by Bug-Reaper** [comment]
I'm experiencing a similar macro related error building with `env` macro possibly unrelated?

Trying to create dual Installers on `Windows-11 24H2 (Arm64)`? 

❌ : Fails for ARM arch target
```js
{
  arifactName:"${productName}-" + PRETTY_VERSION + "-${env.XYZ_DEBUG_BOUGIE_ARCH}.$ext"
}
```
✅ : Works fine for both targets
```js
{
  artifactName:"${productName}-"+PRETTY_VERSION+"-${arch}.${ext}"
}
```
✅ Works either way for `x64` builds.

I'd assume it's some env-var madness and the builder messing up the env macro? 

Gonna do some logging around https://github.com/electron-userland/electron-builder/pull/5905 and pray
