### ISSUE TITLE
Do not trash old build artifacts

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#586]
Continuing from https://github.com/szwacz/electron-boilerplate/issues/172

*Afaik* on `npm run dist` electron-builder drops everything from the *output*-Directory. It then fetches the latest artifact from upstream and builds the delta etc.

I'd like electron-builder to not delete any files. It may overwrite an existing previous version with the downloaded one but *imho* it shouldn't delete other files in the directory.

> For what do you need old artifacts? 

I keep backups of every version. If an user experiences some problems I can always verify the issue with the exact version of the application. Clearly the output-directory **isn't** the place to keep backups long-term. But anyway, I tend to forget to always backup the build right after building it. After another `npm run dist` it's gone :(

Also, is it stated in the docs that the contents of the output-dir are discarded on every build? I was surprised and puzzled the first time I experienced it. It's a huge *pita* if you have some other files put there (e. g. a readme). If it's not in the docs please add it. (Gotta hurry to catch the train now, sorry.)

Thanks for your efforts :)

**Comment by develar** [comment]
Squirrel.Windows — only `*-full.nupkg` will be removed.

**Comment by black-snow** [comment]
Awesome!
