### ISSUE TITLE
Please add reference to apple doc to electron builder docs

### ISSUE THREAD

**Issue by Simon-Laux** [electron-userland/electron-builder#5860]
Please add this link to the documentation:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102207-TPXREF115

https://www.electron.build/generated/platformspecificbuildoptions
under fileAssociations -> protocols -> role

PS: it would make sense to think about improving your documentation, because having keys and sub-keys at the same indentation level is confusing as hell.

**Comment by mmaietta** [comment]
Happy to accept a PR! 
Docs are located on the `docs` branch
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation

**Comment by Simon-Laux** [comment]
yes still relevant and the stale bot isn't helping anyone, its just annoying

**Comment by Simon-Laux** [comment]
so seems like i missed the stalebot

**Comment by mmaietta** [comment]
Docs were moved to `master` branch under `docs` folder, please open a PR to add the link to it, I'd greatly appreciate it!
https://github.com/electron-userland/electron-builder/tree/master/docs
