### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Received data length is not equal to expected

### ISSUE THREAD

**Issue by spierala** [electron-userland/electron-builder#5864]
* **Version**:  22.11.1

* **Electron Version**:  11.4.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: WIN

When downloading a new version of our electron app via the auto-updater, there is this error in the Chrome console:

> Cannot download differentially, fallback to full download: Error: Received data length 3042 is not equal to expected 1295
>     at IncomingMessage.<anonymous> (C:\CoolApp\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:267:24)
>     at IncomingMessage.emit (events.js:315:20)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)

    
 I am not sure if we should worry about this error. How can we fix that error?

**Comment by mmaietta** [comment]
Linking this to this PR https://github.com/electron-userland/electron-builder/pull/5948 as we discerned that the incorrect URL was being passed for the blockmaps for differential downloads, causing a mismatch. Closing
