### ISSUE TITLE
Code object is not signed at all

### ISSUE THREAD

**Issue by desire** [electron-userland/electron-builder#5865]
Electron builder version: 22.11.1
Electron version: 12.0.6

I upgraded from Electron 8 -> 12 and now code signing doesn't work. I am trying to push this to production right now but cant.

`
  • signing         file=release/mac/Splashforce.app identityName=Developer ID Application: Liam Seskis (P38CSWKD6S) identityHash=F8C633663AE760E5F4280A02ADDBCED577566977 provisioningProfile=none
  ⨯ Command failed: codesign --sign F8C633663AE760E5F4280A02ADDBCED577566977 --force --keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/edf4ae3683ee1cc1c69e87e235b37e318b1cb4a06a5e5c992f291eb9cb5afbe7.keychain --options runtime --entitlements build_resources/entitlements.mac.plist /Users/runner/work/sf4/sf4/release/mac/Splashforce.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/runner/work/sf4/sf4/release/mac/Splashforce.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/runner/work/sf4/sf4/release/mac/Splashforce.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
  stackTrace=
`

**Comment by classmate-one** [comment]
me too

**Comment by mmaietta** [comment]
Can you please try 22.10.5?
It'll help me triage this

**Comment by desire** [comment]
Can confirm this fixed the issue
