### ISSUE TITLE
Error in travisCI

### ISSUE THREAD

**Issue by JeroenVinke** [electron-userland/electron-builder#587]
* **Version**:  5.12.1

* **Target**:  mac

Hi,

I'm trying to build the mac target using TravisCI, but for some reason it fails at the git-lfs step: https://travis-ci.org/monterey-framework/monterey/jobs/144776067. What's weird is that the [linux target](https://travis-ci.org/monterey-framework/monterey/builds/144776065) builds successfully. I have compared my [setup](https://github.com/monterey-framework/monterey/blob/dfa036bda1fcea9ba00fe027567d24d1ffdbd548/.travis.yml) to the one of [onshape](https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml) as onshape is building correctly (although the last build of it was 5 days ago).

I know this is probably not electron-builder's fault, but do you have a clue why this may be happening? I'm about 20 builds further and i'm pretty much out of ideas, so I take any help I can get.

```
1.73s$ mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609    0   609    0     0   2265      0 --:--:-- --:--:-- --:--:--  2272
100 3468k  100 3468k    0     0  4764k      0 --:--:-- --:--:-- --:--:-- 12.0M
Git LFS: (0 of 11 files, 11 skipped) 0 B / 706.11 KB, 706.11 KB skipped
[404] Object does not exist on the server
[ab8a1c158bd1b2585d778ed74e2a662aeff4ce7f42953b9ba85317b27cd88fb5] Object does not exist on the server
```

Thanks,

Jeroen

**Comment by develar** [comment]
I suppose git lfs is not installed correctly on your machine and git lfs hook didn't upload your file to server. Please `git lfs install --force` and recommit your binary file.

If you don't use git lfs, just remove this step from travis.yml.

**Comment by JeroenVinke** [comment]
@develar you saved me many hours of debugging, thanks!!

![image](https://cloud.githubusercontent.com/assets/2189477/16851403/b3c1a5d2-4a03-11e6-8532-9ad51535778c.png)
