### ISSUE TITLE
Cannot find module 'dmg-license'

### ISSUE THREAD

**Issue by kimlimjustin** [electron-userland/electron-builder#5884]
* **Version**: 22.11.3

* **Electron Version**: 12.0.5

* **Target**: windows, macos, linux

```
 ⨯ Cannot find module 'dmg-license'
Require stack:
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmgLicense.js
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmg.js
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmgUtil.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/macPackager.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/packager.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/index.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/out/builder.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/out/cli/cli.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
Require stack:
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmgLicense.js
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmg.js
- /home/justin/Projects/xplorer/node_modules/dmg-builder/out/dmgUtil.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/macPackager.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/packager.js
- /home/justin/Projects/xplorer/node_modules/app-builder-lib/out/index.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/out/builder.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/out/cli/cli.js
- /home/justin/Projects/xplorer/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/justin/Projects/xplorer/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/justin/Projects/xplorer/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

The version works were v20.31.2.

**Comment by sprout2000** [comment]
same with:

- version: 22.11.4
- macOS version: 11.3.1 (arm64)
- Electron version: 12.0.7
- target: 'default'
- arch: ['x64', 'arm64']

```sh
Error: Cannot find module 'dmg-license'
Require stack:
- /Users/sprout/myapp/node_modules/dmg-builder/out/dmgLicense.js
- /Users/sprout/myapp/node_modules/dmg-builder/out/dmg.js
- /Users/sprout/myapp/node_modules/dmg-builder/out/dmgUtil.js
- /Users/sprout/myapp/node_modules/app-builder-lib/out/macPackager.js
- /Users/sprout/myapp/node_modules/app-builder-lib/out/packager.js
- /Users/sprout/myapp/node_modules/app-builder-lib/out/index.js
- /Users/sprout/myapp/node_modules/electron-builder/out/builder.js
- /Users/sprout/myapp/node_modules/electron-builder/out/index.js
- /Users/sprout/myapp/scripts/build-unsign.ts
  at Function.Module.\_resolveFilename (node:internal/modules/cjs/loader:924:15)
  at Function.Module.\_load (node:internal/modules/cjs/loader:769:27)
  at Module.require (node:internal/modules/cjs/loader:996:19)
  at require (node:internal/modules/cjs/helpers:92:18)
  at Object.<anonymous> (/Users/sprout/myapp/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
  at Module.\_compile (node:internal/modules/cjs/loader:1092:14)
  at Object.Module.\_extensions..js (node:internal/modules/cjs/loader:1121:10)
  at Module.load (node:internal/modules/cjs/loader:972:32)
  at Function.Module.\_load (node:internal/modules/cjs/loader:813:14)
  at Module.require (node:internal/modules/cjs/loader:996:19)
  at require (node:internal/modules/cjs/helpers:92:18)
  at Object.<anonymous> (/Users/sprout/myapp/node_modules/dmg-builder/src/dmg.ts:13:1)
  at Module.\_compile (node:internal/modules/cjs/loader:1092:14)
  at Object.Module.\_extensions..js (node:internal/modules/cjs/loader:1121:10)
  at Module.load (node:internal/modules/cjs/loader:972:32)
  at Function.Module.\_load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
  '/Users/sprout/myapp/node_modules/dmg-builder/out/dmgLicense.js',
  '/Users/sprout/myapp/node_modules/dmg-builder/out/dmg.js',
  '/Users/sprout/myapp/node_modules/dmg-builder/out/dmgUtil.js',
  '/Users/sprout/myapp/node_modules/app-builder-lib/out/macPackager.js',
  '/Users/sprout/myapp/node_modules/app-builder-lib/out/packager.js',
  '/Users/sprout/myapp/node_modules/app-builder-lib/out/index.js',
  '/Users/sprout/myapp/node_modules/electron-builder/out/builder.js',
  '/Users/sprout/myapp/node_modules/electron-builder/out/index.js',
  '/Users/sprout/myapp/scripts/build-unsign.ts'
  ]
  }
```

**Comment by mmaietta** [comment]
Oomph, you're compiling on an M1?  Can you double check that `dmg-license` is present in your node_modules?
The module should be found, it's listed in electron-builder's dependencies as well
https://github.com/electron-userland/electron-builder/blob/c623279a31d3d203ad1f150d83905a7e1f58a731/package.json#L39-L41
https://github.com/electron-userland/electron-builder/blob/c623279a31d3d203ad1f150d83905a7e1f58a731/packages/dmg-builder/package.json#L23-L25
IIRC it's marked optional in the dmg-builder package.json because it only works on mac

**Comment by kimlimjustin** [comment]
> Oomph, you're compiling on an M1?

No, I'm compiling on Ubuntu 21.04 with the `electron-builder -wml` command, I remember that it crashed on the first time I try building WML on Linux, but after I installed docker and wine, this error occurs, and after I go into issues on electron-builder, I saw that people saying version 20.31.2 works fine, and yes, it works fine on version 20.31.2. Note: I open this issue because previous issues on GitHub are closed.

> Can you double check that dmg-license is present in your node_modules?

No, it does not present.

> IIRC it's marked optional in the dmg-builder package.json because it only works on mac

I think so, because when I install electron-builder@22.11.3, yarn give me these warnings:
```
```

**Comment by mmaietta** [comment]
You can't package or sign for macOS on Linux, as noted in the logs, `dmg-license` and `iconv-corefoundation` are incompatible with Linux. Both, if not just iconv, are needed for the bundling process.

**Comment by kimlimjustin** [comment]
> You can't package or sign for macOS on Linux, as noted in the logs, `dmg-license` and `iconv-corefoundation` are incompatible with Linux. Both, if not just iconv, are needed for the bundling process.

Oh okay, that means I can only build the macOS package on MacOS right? thanks!
Btw, I'm thinking about using docker to enable packaging  windows, macos and Linux packages on one OS.

**Comment by mmaietta** [comment]
Windows can use our Wine docker image, Linux can use the base docker image. You'll need to run Docker on a macOS build machine to achieve building all on one OS.
Note, if you have native modules, those are only compilable on their relative OS, so Windows native modules may require a Windows OS environment. I can't recall off the top of my head.

**Comment by kimlimjustin** [comment]
Oh okay, thanks!

**Comment by airtonix** [comment]
> Oomph, you're compiling on an M1? Can you double check that `dmg-license` is present in your node_modules?
> The module should be found, it's listed in electron-builder's dependencies as well
> https://github.com/electron-userland/electron-builder/blob/c623279a31d3d203ad1f150d83905a7e1f58a731/package.json#L39-L41
> 
> 
> https://github.com/electron-userland/electron-builder/blob/c623279a31d3d203ad1f150d83905a7e1f58a731/packages/dmg-builder/package.json#L23-L25
> 
> 
> IIRC it's marked optional in the dmg-builder package.json because it only works on mac

why is it listed?


> You can't package or sign for macOS on Linux, as noted in the logs, `dmg-license` and `iconv-corefoundation` are incompatible with Linux. Both, if not just iconv, are needed for the bundling process.

You also can't install `dmg-license` on linux... it fails.

**Comment by airtonix** [comment]
> Windows can use our Wine docker image, Linux can use the base docker image. You'll need to run Docker on a macOS build machine to achieve building all on one OS.
> Note, if you have native modules, those are only compilable on their relative OS, so Windows native modules may require a Windows OS environment. I can't recall off the top of my head.

just use github actions or circleci where you can describe the build platform.

another reason why macos specific things that cause exit 1 on non mac systems should not be in the base package

**Comment by airtonix** [comment]
```
x pnpm i || echo "💥 PNPM_INSTALL_UTTERLY_FAILED"
Scope: all 329 workspace projects
...

 ERROR  Unsupported platform for registry.npmjs.org/iconv-corefoundation/1.1.6: wanted {"cpu":["any"],"os":["darwin"]} (current: {"os":"linux","cpu":"x64"})
Progress: resolved 1145, reused 1142, downloaded 1, added 0
Downloading registry.npmjs.org/app-builder-bin/3.5.12: 14.9 MB/41.8 MB
💥 PNPM_INSTALL_UTTERLY_FAILED
```

**Comment by auaicn** [comment]
What if I want to target windows & macOS in once (on linux-wine system), without macOS signing ?
I set below config before calling `electron-builder` command, with `cross-end`
```
CSC_IDENTITY_AUTO_DISCOVERY=false 
```
It stills seems to need `dmg-license` even if i'm not supposed to use macOS signing.. :(
It would be nice if there's some other approaches I could try (to avoid macOS signing and build all platform-target at single-linux wine instance)
