### ISSUE TITLE
In DMG `licenseButtons` files, rename `lang` to `languageName`

### ISSUE THREAD

**Issue by argv-minus-one** [electron-userland/electron-builder#5887]
* **Version**: 22.11.3
* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current
* **Target**: macOS

My investigation of issue #5834 revealed a problem with how `licenseButtons` files are understood by `electron-builder`.

[The documentation](https://www.electron.build/configuration/dmg#dmg-license) says to put something like `English` in the `lang` property of `licenseButtons` files. But `dmg-license` expects a language *tag* (like `en-us`) there, not a language *name*, so doing what the documentation says will result in the error message seen in #5834: `No known languages found for specification English.`

I'm guessing the pre-`dmg-license` implementation expected a language name in the `lang` property. If that's correct, then [this code](https://github.com/electron-userland/electron-builder/blob/79940292bdd1a5de45b33453be492ea67529434b/packages/dmg-builder/src/dmgLicense.ts#L44) should rename the `lang` property to `languageName`, just like it renames `description` to `message`.

By the way, a `languageName` is only actually required for a handful of languages (those marked as "requires `languageName`" in [this list](https://github.com/argv-minus-one/dmg-license/blob/master/docs/Supported%20Language%20Tags.md)). For all other languages, a default is filled in by `dmg-license`. I don't think macOS actually displays the `languageName` anywhere anyway, so there isn't much point in providing a `languageName` when it's not required. The documentation should probably mention that.

**Comment by mmaietta** [comment]
First off, many thanks for your work on dmg-license, @argv-minus-one! Really appreciate it

Yeah, there was a previous implementation that was removed sometime before I joined. Our documentation is definitely out of date, and I don't know (or have access). I guess we should just link to your repo docs from the electron-builder docs site?

**Comment by argv-minus-one** [comment]
>First off, many thanks for your work on dmg-license, @argv-minus-one! Really appreciate it

I'm glad someone found it useful. ☺

>Our documentation is definitely out of date, and I don't know (or have access). I guess we should just link to your repo docs from the electron-builder docs site?

You could, but you'd need to explain the differences. `dmg-license` takes JSON with [this schema](https://github.com/argv-minus-one/dmg-license/blob/master/docs/License%20Specifications.md) as input, but `electron-builder` [generates it programmatically](https://github.com/electron-userland/electron-builder/blob/79940292bdd1a5de45b33453be492ea67529434b/packages/dmg-builder/src/dmgLicense.ts#L27) rather than taking it as input. Differences (that I know about) include:

* The `body` array is filled in from `license_*.{txt,rtf}` files.
* The `labels` array is filled in from `licenseButtons_*.json` files, each of which must contain a single label set (without a `lang` property).
* `rawLabels` and `defaultLang` are not supported by `electron-builder`.
* The language for a `license_*.{txt,rtf}` or `licenseButtons_*.json` file is parsed out of the file name.
* Language subtags (like the `us` in `en_US`) must be separated with an underscore instead of a dash (unless `electron-builder` is changed to accept dashes).
* A language tag is allowed to have only the language subtag and no region subtag (e.g. `en` or `de`, as opposed to `en_US` or `de_DE`). `dmg-license` doesn't allow that in most cases.
* `license_*.{txt,rtf}` files must be encoded in UTF-8.
* Numeric Mac OS language codes (like `24`) are not supported. Only language tags (like `tr_TR`) are.

**Comment by panther7** [comment]
Still relevant, docs are wrong: https://www.electron.build/configuration/dmg#dmg-license

`lang` must be rename to `langName`

**Comment by panther7** [comment]
Please, add `defaultLang`, thanks.
