### ISSUE TITLE
Mac dmg_builder failed

### ISSUE THREAD

**Issue by HackHarry** [electron-userland/electron-builder#5889]
* **Version**: 22.3.6

* **Electron Version**: 11.0.1
* **Electron Type (current, beta, nightly)**: not known

* **Target**: dmg

dmg_builder is runnning by python2, and it use path "/usr/bin/python" automatically. But my "/usr/bin/python" is python3.7.

If can it set python path by myself?

**Comment by mmaietta** [comment]
It doesn't appear so
https://github.com/electron-userland/electron-builder/blob/96d7813362d319c3141d78e179c3f6d71c798fab/packages/dmg-builder/src/dmg.ts#L301-L304

If you'd like to make it customizable, I'd recommend opening a PR to add that functionality. I imagine something like `process.env.PYTHON_PATH || "/usr/bin/python"` would do the trick

https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
