### ISSUE TITLE
How to specify architecture in programmatic builds

### ISSUE THREAD

**Issue by daviseford** [electron-userland/electron-builder#589]
* **Version**: 5.12.1

* **Target**: Win32

I'm attempting to use the programmatic builder in unit testing, but I can't figure out how to pass in the architecture option. I have tried many many variations, and I have inspected the type files and the builder, but I just cannot figure out how to create a win32 build

Here's my code

`function startWinBuild() {  

  return new Promise(function (ok) {

    return builder.build({

      targets: Platform.WINDOWS.createTarget(), // How do I set this to Arch = ia32?
      devMetadata: PackageJSON

    }).then(() => {
      ok(true);

    }).catch((err) => {
      console.log(err);
      ok(false);
    });
  });
}
`

This probably has a quick answer, but I've spent a couple hours in the docs/code now, and I'd just like to get an answer. :) Thanks!

**Comment by develar** [comment]
```
Platform.WINDOWS.createTarget(null, Arch.ia32)
```

You can see our test code — https://github.com/electron-userland/electron-builder/blob/master/test/src/BuildTest.ts#L35
