### ISSUE TITLE
Specify specific version to downgrade to

### ISSUE THREAD

**Issue by hrueger** [electron-userland/electron-builder#5892]
* **Version**: 22.10.5

* **Electron Version**: 12.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, MacOS, Linux

I'd like my users to be able to downgrade to a specific version if they want. For that I want to display a list of releases in my UI and once a user selects an entry, I'd like to use the autoUpdater to downgrade to this version.

I'm using an S3 provider, so I could build the list from the xml index file. But how do I tell the autoUpdater which version to downgrade to?

**Comment by mmaietta** [comment]
I'm not familiar enough with electron-updater to be able to advise on this one. I'm equally interested and would welcome any proposals on how we could create this interface. Perhaps manually specifying an update URL that has the dist and blockmap? Not sure if that's a messy approach though within the current architecture

**Comment by hrueger** [comment]
Like with #5895 I'd be happy to implement this if I know how it should look.
Just another idea here:

Like the `latest.yml` we could generate a `versions.yml`, a `versions-linux.yml` and a `versions-mac.yml` which each include all versions. Then, we could have a user just specify a version (or even provide them all in an array).

**Comment by hrueger** [comment]
Yes, it is still relevant. It just needs some more opinions from other people / maintainers about how to implement it.

**Comment by mmaietta** [comment]
Hi @hrueger !
Re:
> Like the latest.yml we could generate a versions.yml, a versions-linux.yml and a versions-mac.yml which each include all versions. Then, we could have a user just specify a version (or even provide them all in an array).

If these are including all versions, where is this list being maintained from? Another file in the repo tracking all previous releases to be maintained by the author?

I just wrote an updater/publisher in PR https://github.com/electron-userland/electron-builder/pull/6167 if you'd like to take a look. It might help for familiarizing with writing your own custom updater (or rather, downgrader).

**Comment by hrueger** [comment]
> If these are including all versions, where is this list being maintained from? Another file in the repo tracking all previous releases to be maintained by the author?

Hm, that's a good question. I honestly have not yet thought about that. Maybe we could also try to find those version files from previous releases online, read them and just add info about the new version?

**Comment by Bohooslav** [comment]
Is there any guide how can one downgrade/upgrade to specified version in existing architecture, at least as a temporary solution?
