### ISSUE TITLE
Installing electron builder in the wine-mono docker image fails

### ISSUE THREAD

**Issue by kolaente** [electron-userland/electron-builder#5893]
* **Version**: 22.10.5

* **Electron Version**: 12.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux and windows

Using the latest `electronuserland/builder:wine-mono` docker image, I am unable to run `yarn install` in a project with uses electron and electron builder in the versions mentioned above. 

It fails with this error:
```
error electron-builder@22.11.4: The engine "node" is incompatible with this module. Expected version ">=14.17.0". Got "14.16.0"
```
It looks like the node version in the container is too old. Or am I doing something wrong with my configuration?

You can see this in this ci run: https://drone.kolaente.de/vikunja/desktop/445/1/4

**Comment by dphochman** [comment]
Similar problem ... my app requires "node <= 14.16.1" (the LTS version as of last week), and now electron v12.11.4 requires "node = 14.17.0".  It looks like a mistaken change in package.json "engines" from `"node": ">=12.0.0"` in v22.11.3 to `"node": "14.17.0"` in v22.11.4.  

What Is the reason for this forced upgrade to node? Please revert to a more reasonable node version.

**Comment by kolaente** [comment]
@develar Will there be a new release with the fix?

**Comment by renanyoy** [comment]
can you update the [docker builder](https://hub.docker.com/r/electronuserland/builder) with the right node version ?
