### ISSUE TITLE
Release Notes Support for providers other than `GitHub Releases`

### ISSUE THREAD

**Issue by hrueger** [electron-userland/electron-builder#5895]
* **Version**: 22.10.5

* **Electron Version**: 12.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, MacOS, Linux

This is probably related to #5892. I'd like to also get release notes (in my case a changelog) for providers other than GitHub Releases. I'm using an S3 server. Maybe a `.json` or a `.yml` file could be uploaded there (like the `latest.yml`) to store the notes. This would also make it easier to get a full list of versions (see downgrading to specific versions in #5892)

What do you think?

**Comment by hrueger** [comment]
Sorry for another ping. I'd be happy to work on this, I'd just be interested in your thoughts about how it should be accomplished.

**Comment by mmaietta** [comment]
Off the top of my head, I believe you can achieve this by creating the changeset yourself during an electron-builder hook, then implement a "custom" Publisher that defines its own uploader or HttpExecutor. That should allow you to customize the full configuration of files to be uploaded and could include your changeset file.

**Comment by hrueger** [comment]
That's a great idea, I'll look into that, thanks. 

So would you say that this is not something which other people would also like to see and you would accept a PR for? I don't think that this would be a breaking change.

**Comment by mmaietta** [comment]
Sorry for leaving this hanging. Happy to accept contributions! I think it's a cool idea

It's relatively simple to get a local dev env set up: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by hrueger** [comment]
>Sorry for leaving this hanging

No problem. The company I work for currently has set other priorities. That means I won't be able to work on that right now, but definitely in a couple weeks.

>Where were you thinking of being able to pull the changelog from? The repo/project?

Yes, probably. I'll do some research if there's like a standardized changelog format which can be read programmatically.
