### ISSUE TITLE
Can I set some file don't update or modify in update  in electron-builder  auto update

### ISSUE THREAD

**Issue by colining** [electron-userland/electron-builder#5898]
* **Version**: 
22.3.6

* **Electron Version**:
11.3.0

* **Target**: 
win mac

### so, here is the situation:

My app has 2 JSON file  under the project folder, and they will be packaged into the assets folder 

### and here is the question:

I want to my app auto-update every time when I publish the new release 

but about the 2 JSON file, 

**source.json  is about the website configure, and the user can modify it locally, so if I release the new version. I want to auto-update can update sourece.json by my change and keep the user change**

**favorite.json is about something user like, so it's should be no update when app auto-update**

I have no idea about this problem, so can anyone give me a solution.

please !!!!

**Comment by ailin92** [comment]
I don't know if I understand correctly what you are asking for, but you can use custom NSIS scripts to do this. For example, drop the use of extraResources to export those files, but do everything in a custom installer.nsh, to be executed only when installing and not updating (use   ${if} ${isUpdated} for this). Give the documentation a look, section Custom NSIS script.
Hope it helps
.

**Comment by colining** [comment]
> I don't know if I understand correctly what you are asking for, but you can use custom NSIS scripts to do this. For example, drop the use of extraResources to export those files, but do everything in a custom installer.nsh, to be executed only when installing and not updating (use ${if} ${isUpdated} for this). Give the documentation a look, section Custom NSIS script.
> Hope it helps
> .

Thanks a lot!
I have already looked at the doc about the NSIS script
And I found My thinking was wrong at the beginning

this problem is not about the auto-update

this problem is only about the user configure is should save in where 

[the user configure is should saving in the user data folder ](https://www.electronjs.org/docs/api/app#appgetapppath)
