### ISSUE TITLE
/n signtool param support

### ISSUE THREAD

**Issue by vpj** [electron-userland/electron-builder#590]
`electron-builder` is using `electron-winstaller-fixed` npm module. This module links to `electron-winstaller` repo. So I assume it is a fork with some fixes. I couldn't find the actual repository of `electron-winstaller-fixed`.

I wanted to sign my code with a **EV certificate** on windows and it seemed easier to use signWithParams option of `electron-winstaller`. This option is not available under latest `electron-winstaller-fixed` and it no longer uses **signtool** even when *building under windows*. So I used `electron-builder` with `electron-winstaller` instead of `electron-winstaller-fixed`. *And it worked without a problem.*

I'm using `electron-builder` version `5.13.1` which depends on `electron-winstaller-fixed` version `3.0.0`.

Is there a particular reason why `electron-winstaller-fixed` is used? Also how do you sign with a EV certificate (one with a USB token)?

**Comment by develar** [comment]
We don't use signWithParams because on Linux and macOS we use another tool to sign.

> EV certificate

Please provide your `signWithParams` and it will be supported without such param. Why EV requires  signWithParams?

**Comment by vpj** [comment]
This is my `signWithParams` value.

    /t http://timestamp.digicert.com /n "NAME"

I'm new to electron builder, and I couldn't find any other options in [Options)(https://github.com/electron-userland/electron-builder/wiki/Options) or [Code Signing](https://github.com/electron-userland/electron-builder/wiki/Code-Signing) documents.

**Comment by develar** [comment]
@vpj Just set `certificateFile` and `certificatePassword` (in the `build.win`). Or [CSC_LINK](https://github.com/electron-userland/electron-builder/wiki/Code-Signing)

**Comment by develar** [comment]
`/n` do you mean that you don't have `p12` file, but instead you want to get cert from "The following command signs the file using a certificate whose private key information is protected by a hardware cryptography module. A computer store is specified for the certification authority (CA) store."?

**Comment by vpj** [comment]
Yes, I do not have a p12 file, and yes it comes with a usb device.

**Comment by develar** [comment]
[certificateSubjectName](https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-certificateSubjectName)
