### ISSUE TITLE
Enhancement Proposal: Use custom ProxyAgent if env vars are set

### ISSUE THREAD

**Issue by baparham** [electron-userland/electron-builder#5906]
* **Version**: 22.10.5

* **Electron Version**: 11.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows and linux

I am working behind a corporate proxy, and uploading to a GitHub private repo is not working right during the publish phase of building. Presumably this may affect the auto-updater too, but I am not sure since I haven't gotten that far yet.

I normally have a usual workflow of setting the proxy settings something like this, all using http protocol:
```
export https_proxy=http://my-proxy:<port>
export http_proxy=http://my-proxy:<port>
export HTTPS_PROXY=http://my-proxy:<port>
export HTTP_PROXY=http://my-proxy:<port>
```

but when electron-builder (well, `builder-util`) goes to query the github api, it uses node's built in https module, which doesn't seem to properly respect the environment variables, attempting to connect without using the proxy, which results in errors like this:
```
  • uploading       file=app-setup.exe provider=GitHub
  • async task error  error=connect ETIMEDOUT 140.82.121.5:443
  • async task error  error=connect ETIMEDOUT 140.82.121.5:443
```

If I add in an additional few lines to the nodeHttpExecutor class to instead create my own HttpsProxyAgent with a proxy, everything works.

```
export class NodeHttpExecutor extends HttpExecutor<ClientRequest> {
  // noinspection JSMethodCanBeStatic
  // noinspection JSUnusedGlobalSymbols
  createRequest(options: any, callback: (response: any) => void): any {
+   if (process.env['https_proxy'] && options.protocol === 'https:') {
+     const agent = HttpsProxyAgent(process.env['https_proxy']);
+     options.agent = agent;
+   } else if (process.env['http_proxy'] && options.protocol === 'http:') {
+     const agent = HttpProxyAgent(process.env['http_proxy']);
+     options.agent = agent
+   }
    return (options.protocol === "http:" ? httpRequest : https.request)(options, callback);
  }
}
```

Is something along these lines something worth putting into a PR to have reviewed or does electron-builder want to stay away from modifying the request agent like this?

Thanks for the guidance!

**Comment by baparham** [comment]
Yes, this is still relevant and I would still like feedback from the
maintainers if this will work.

**Comment by kevfuzz** [comment]
I'm having the same issue so would be great if it could be resolved.

**Comment by baparham** [comment]
@robertpatrick please see if pr #6410 solves this issue for you and let me know what you think
