### ISSUE TITLE
Is it possible to play music while the Windows installer is running?

### ISSUE THREAD

**Issue by nukeop** [electron-userland/electron-builder#5912]
* **Version**: 22.10.5

* **Electron Version**: 12.0.9
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

Is it possible to play music during installation? If not with any of the options available by default, can I patch it into the generated executable after electron-builder is done?

**Comment by mmaietta** [comment]
https://nsis.sourceforge.io/Play_music_in_your_installers_(NSISBASS)
https://nsis-dev.github.io/NSIS-Forums/html/t-184194.html

You'll likely need to use one of these:
>`include` String - The path to NSIS include script to customize installer. Defaults to build/installer.nsh. See Custom NSIS script.
`script` String - The path to NSIS script to customize installer. Defaults to build/installer.nsi. See Custom NSIS script.

https://www.electron.build/configuration/nsis
