### ISSUE TITLE
Electron Auto update

### ISSUE THREAD

**Issue by AkhmedovSH** [electron-userland/electron-builder#5914]
* **Version**: 22.11.5

* **Electron Version**:12.0.6
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis

I use nsis with allowToChangeInstallationDirectory true
After build project i got as result dist folder there my win-unpacked folder and etc
and install my project to C:\Program Files\my-app
my-app1.0.exe when i run that file start works my auto update and after succesfully updated 
new update.exe file located in
C:\Users\99899\AppData\Local\my-app\pending\update.exe
and installed app in folder
C:\Users\99899\AppData\Local\Programs\my-app
BUT I want to replace my exe to new version my-app1.1 in folder C:\Program Files\my-app
how can i do that
and want to know it will replace all my files? becouse I have extraFiles there my sqlite database will it will be replaced with auto update or will be saved old database without replace

**Comment by mmaietta** [comment]
Seems like you need to be using `perMachine: true` to have it installed to Program Files
> perMachine = false Boolean - Whether to show install mode installer page (choice per-machine or per-user) for assisted installer. Or whether installation always per all users (per-machine).

Ref: https://www.electron.build/configuration/nsis

**Comment by AkhmedovSH** [comment]
> Seems like you need to be using `perMachine: true` to have it installed to Program Files
> 
> > perMachine = false Boolean - Whether to show install mode installer page (choice per-machine or per-user) for assisted installer. Or whether installation always per all users (per-machine).
> 
> Ref: https://www.electron.build/configuration/nsis

I used perMachine true but it does not for what i want
