### ISSUE TITLE
App-icon missing on linux (ubuntu 18.04)

### ISSUE THREAD

**Issue by prakashnarkhede91** [electron-userland/electron-builder#5919]
* **Version**:  "electron-builder": "21.2.0",

* **Electron Version**: "electron": "3.1.13",
* **Electron Type (current, beta, nightly)**:

* **Target**: 
* I am trying to set the application icon ( launcher icon) for the last 4 hour
but each time when I am creating the build icon is miss

  "build": {
        "productName": "My APP",
        "appId": "MyAppId",
        "files": [
            "app/dist/",
            "app/app.html",
            "app/main.prod.js",
            "app/main.prod.js.map",
            "package.json",
            "resources"
        ],
        "extraFiles": [
            {
                "from": "app/assets/images/slipLogo/",
                "to": "resources",
                "filter": [
                    "**/*"
                ]
            },
            {
                "from": "app/assets/images/specials/",
                "to": "resources",
                "filter": [
                    "**/*"
                ]
            }
        ],
        "publish": [
            {
                "provider": "s3",
                "bucket": "-",
                "path": "/releases"
            }
        ],
        "mac": {
            "category": "-",
            "target": [
                "dmg"
            ]
        },
        "dmg": {
            "contents": [
                {
                    "x": 130,
                    "y": 220
                },
                {
                    "x": 410,
                    "y": 220,
                    "type": "link",
                    "path": "/Applications"
                }
            ]
        },
        "win": {
            "target": [
                "nsis"
            ]
        },
        "linux": {
            "target": [
                "AppImage"
            ],
            "category": "Office",
            "icon": "resources/icon.png"
        },
        "directories": {
            "buildResources": "resources",
            "output": "release"
        }
    },
Here is my package json code
Please help me..

**Comment by mmaietta** [comment]
My best guess is to try resaving the `icon.png` using a different application. I've seen a few cases where app-builder-bin has an issue converting an icon/image.

Another tidbit, can you try just using `icon: "icon.png"`? Should resolve it from `buildResources` dir. Shouldn't change anything, but it's another potential vector for me to investigate from.

**Comment by pkrishnaraj** [comment]
@prakashnarkhede91 hey were you able to get the app executable icon. I tried having the icons under /build/icons, in this directory i had all the sizes of the icons and named the files as per the dimensions. Happening only for linux, windows builder works like a charm
