### ISSUE TITLE
[feature request, nsis] add flag when user initiated uninstall happens

### ISSUE THREAD

**Issue by cvl** [electron-userland/electron-builder#5921]
Version: 22.8.1
Electron Version: 12.0.0
Electron Type (current, beta, nightly): current
Target: nsis

At this moment the installer runs the uninstaller when updating app/installing new version. This there's no way to keep the user config in case app is updated if user config must be deleted once app is uninstalled.

Uninstaller script https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/uninstaller.nsh actually has this flag (**${IfNot} ${Silent}** at https://github.com/electron-userland/electron-builder/blob/d307c21b34abee1cd2b8dcd3e705995914dda70f/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L4) yet it clears it right after using it ( https://github.com/electron-userland/electron-builder/blob/d307c21b34abee1cd2b8dcd3e705995914dda70f/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L11 )

Let's have one more flag e.g. userInitiatedUninstall so apps can decide how to behave when uninstalling or updating the app (those are quite different use cases).

**Comment by cvl** [comment]
Temporal workaround for those in need:

```
/*set flag when reinstall is in progress (note: I haven't managed for this to work with Var /GLOBAL */
!macro customInit
WriteRegStr SHELL_CONTEXT "${INSTALL_REGISTRY_KEY}" reinstallInProgress "true"
!macroend

/*decide to remove files or not */
!macro customRemoveFiles

   ReadRegStr $R1 SHELL_CONTEXT "${INSTALL_REGISTRY_KEY}" reinstallInProgress

   ${if} $R1 == "true"
       /*reinstall, keep your config or files*/
    ${else}
         /*clean uninstall, delete your config or files*/
    ${endIf}
    
    WriteRegStr SHELL_CONTEXT "${INSTALL_REGISTRY_KEY}" reinstallInProgress "false"
!macroend
```

**Comment by mmaietta** [comment]
Would you be willing to open a PR to add this? Setting up a local dev environment is fairly simple 🙂 
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by cvl** [comment]
Updated the script.

@mmaietta I believe this should have a better solution (than a quick-hack). I.e. there should be a flag if it's reinstall or uninstall. Shouldn't require mingling with registry. Should be done by someone with understanding how electron builder works.

**Comment by cvl** [comment]
Yes sure
