### ISSUE TITLE
Problem with Workers only after packaging with electron-builder

### ISSUE THREAD

**Issue by LightwithoutLisonlyight** [electron-userland/electron-builder#5924]
* **Version**:  22.10.5

* **Electron Version**:12.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: Windows 

Hi,
In my project I use woorkerpool module and even if i use the most simple configuration with dedicated worker like shown
in the [official NPM page](https://www.npmjs.com/package/workerpool?activeTab=readme),
( from npm page
Dedicated workers

A dedicated worker can be created in a separate script, and then used via a worker pool.

myWorker.js
```js
const workerpool = require('workerpool');

// a deliberately inefficient implementation of the fibonacci sequence
function fibonacci(n) {
  if (n < 2) return n;
  return fibonacci(n - 2) + fibonacci(n - 1);
}

// create a worker and register public functions
workerpool.worker({
  fibonacci: fibonacci
});
```
This worker can be used by a worker pool:

myApp.js
```js
const workerpool = require('workerpool');

// create a worker pool using an external worker script
const pool = workerpool.pool(__dirname + '/myWorker.js');

// run registered functions on the worker via exec
pool.exec('fibonacci', [10])
    .then(function (result) {
      console.log('Result: ' + result); // outputs 55
    })
    .catch(function (err) {
      console.error(err);
    })
    .then(function () {
      pool.terminate(); // terminate all workers when done
    });

```
)

 all works great but when a release application using electron-builder
```js
"release-windows": "electron-builder --windows",
```
and I start workers, they return me the error "MODULE_NOT_FOUND".
Now this error happen when the required resource is not found, but the only resource that i required is workerpool module and path module.
The error happens only after i package my app using electron-builder
Why ?
Thank you for reading and to spend time to try to solve my problem.

**Comment by LightwithoutLisonlyight** [comment]
I understand that the problem is the unwritability of the asar file. I think that when the pool of work generates a new process, it is treated as a different new process, completely separate from the main electron process.
In fact, I tried setting in the package.json file, ``" asar ":" false "`` and after compiling everything worked great.
I saw that there is an option ("asarUnpack") to which by assigning global patterns, it is possible to unpack some specific files or folders.
Now the problem is:
How can it unpack a specific node module and automatically unpack all module dependencies?

**Comment by LightwithoutLisonlyight** [comment]
Is otherwise possible to allow access to every child process to asar file resources ?

**Comment by mmaietta** [comment]
I thought for a release application, you need to use `file://` prefix for referencing anything with `__dirname`?

**Comment by Cmaxd** [comment]
@LightwithoutLisonlyight Hi, I have the same problem, how did you finally solve it?
