### ISSUE TITLE
[electron-updater] Proxy configuration is not documented

### ISSUE THREAD

**Issue by MareikeTaeubner** [electron-userland/electron-builder#5926]
* **Version**:  22.10.5

* **Electron Version**: 8.5.5
* **Electron Type (current, beta, nightly)**:

* **electron-updater Version**: 4.3.9

* **Target**:  Windows x64 NSIS

We tried to configure a proxy for the electron auto update.

We found that the electron-updater does not use the session.defaultSession and therefore does not go over the proxy - even if one is configured. After analyzing the electron-updater code we found out that the updater instance has its own session object, that needs to be configured.

```
autoUpdater.netSession.setProxy({
      proxyRules: "http://localhost:3128",
});
```

This seems to work fine, but since the `netSession` property is not documented at all ([documentation site](https://www.electron.build/auto-update)), we are unsure whether that is public API or internal API that might change in the future.

So hence my question:

Is `autoUpdater.netSession` public, stable API? If yes, it would be really helpful, if the documentation would include it and an example, how to configure a proxy, if needed.

**Comment by mmaietta** [comment]
Would you like it to be a stable API? 😅
I don't think any changes are planned, but our documentation isn't up to date. 

I'm honestly not familiar with electron-updater, but am really interested in your configuration. 

If you're willing to write some documentation here, I can get it into the docs and credit it to you. 

Alternatively, the instructions for setting up the docs branch are in the CONTRIBUTING.md

**Comment by MareikeTaeubner** [comment]
Yes, we would be very grateful if that API would be a stable one.

We are currently looking into when we can provide the documentation.
