### ISSUE TITLE
AppImage gets wrong icon

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#593]
* **Version**: master

* **Target**: Linux AppImage

Getting an "On" icon. I don't think that is the actual icon of the app I am trying to package.

This is what I did:

```
# Install npm 6 and other prerequisites
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs icnsutils graphicsmagick

REPO=ahdriel/thesis-lab

wget https://github.com/$REPO/archive/master.zip
unzip master.zip
cd *-master/

sed -i -e 's|"electron-builder": ".*",|"electron-builder": "next",|g' package.json

npm install
npm run dist -- --linux=AppImage
```

If the upstream app has no icon, then a more generic Electron icon should be used as a fallback.

**Comment by develar** [comment]
Icon is not required for macOS/Windows, but required for Linux — it is wrong, should be fixed. The same warn should be produced and default Electron icon used.
