### ISSUE TITLE
Debian priority "extra" is deprecated

### ISSUE THREAD

**Issue by jwr12135** [electron-userland/electron-builder#5930]
* **Version**: 22.10.5
* **Target**: Debian

Building a Debian package defaults to the "extra" priority (which is deprecated). The default priority should be changed to "optional".

[debian.org](https://www.debian.org/doc/debian-policy/ch-archive.html#s-priorities) says the following:
> **extra**
> This priority is deprecated. Use the optional priority instead. This priority should be treated as equivalent to optional.

**Comment by mmaietta** [comment]
electron-builder doesn't explicitly set the Priority, maybe that is the default behavior for the version of `fpm` being used? `use` is just a null-check wrapper before running the closure
https://github.com/electron-userland/electron-builder/blob/ef704a11e57666c723b6a5535c66b5a5cb697255/packages/app-builder-lib/src/targets/fpm.ts#L150-L152

Looking at the `debTest.js.snap`, `"Priority": "extra",` is coming from somewhere else.

**Comment by jwr12135** [comment]
It looks like a pull request to change the default priority on fpm has been open for quite a while (https://github.com/jordansissel/fpm/pull/1400). We might just want to set the default priority here.
