### ISSUE TITLE
The fileassociations icon setting causes all exe programs in the window to be replaced

### ISSUE THREAD

**Issue by styunan** [electron-userland/electron-builder#5931]
`    "fileAssociations": [
      {
        "ext": [
          "exe",
          "mkv",
          "mts",
          "f4b"
        ],
        "name": "japankana",
        "description": "Japanese Kanji to Katakana",
        "role": "Editor",
        "icon": "assets/icons/japankana256.ico"
      }
    ],`

The fileassociations icon setting causes all exe programs in the window to be replaced

When the build is successful and the package is completed, the following serious consequences will occur when installing the software，
Not only the icon has changed, but every exe program will open my electron program.

![image](https://user-images.githubusercontent.com/40879024/120094712-a8e62200-c154-11eb-895d-90c0497425d6.png)
![image](https://user-images.githubusercontent.com/40879024/120094722-b4d1e400-c154-11eb-96ff-dd8aebb1cdca.png)
![image](https://user-images.githubusercontent.com/40879024/120094734-c1563c80-c154-11eb-82a7-5d3595decef4.png)

**package.json**
`{
  "name": "japankana",
  "productName": "japankana",
  "version": "1.0.2",
  "description": "Japanese Kanji to Katakana",
  "main": "main.js",
  "icon": "assets/icons/japankana256.ico",
  "build": {
    "files": [
      "!.git${/*}",
      "!.vscode${/*}",
      "!.github${/*}",
      "!dist${/*}",
      "!**.md",
      "!**.eslintrc.**",
      "!**.gitignore",
      "!yarn.lock",
      "!package-lock.json",
      "!assets/imgs${/*}",
      "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples,*.d.ts}",
      "!**/node_modules/.bin",
      "!**/*.{o,hprof,orig,pyc,pyo,rbc}",
      "!**/._*",
      "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"
    ],
    "appId": "xxxxxx.japankana",
    "fileAssociations": [
      {
        "ext": [
          "exe",
          "mkv",
          "mts",
          "f4b"
        ],
        "name": "japankana",
        "description": "Japanese Kanji to Katakana",
        "role": "Editor",
        "icon": "assets/icons/japankana256.ico"
      }
    ],
    "linux": {
      "category": "Japanese Kanji to Katakana",
      "target": [
        "deb",
        "freebsd",
        "rpm",
        "AppImage"
      ]
    },
    "mac": {
      "target": {
        "target": "default",
        "arch": [
          "arm64",
          "x64"
        ]
      },
      "category": "Japanese Kanji to Katakana"
    },
    "nsis": {
      "artifactName": "${productName}-${version}-Setup.${ext}"
    },
    "win": {
      "target": [
        "zip",
        "portable",
        "nsis"
      ],
      "icon": "assetsJapanese Kanji to Katakana",
      "publisherName": "CN=2B3D4037-FF2E-4C36-84A6-CFF49F585C0C",
      "artifactName": "${productName}-${version}.${ext}"
    },
    "appx": {
      "displayName": "sleek - Todo.txt app for Windows, free and open-source",
      "identityName": "17450RobinAhle.sleektodomanager",
      "publisher": "CN=2B3D4037-FF2E-4C36-84A6-CFF49F585C0C",
      "publisherDisplayName": "Robin Ahle",
      "applicationId": "xxxxxx.japankana"
    }
  },
  "appImage": {
    "artifactName": "${productName}-${version}-${arch}.${ext}"
  },
  "rpm": {
    "artifactName": "${productName}-${version}-${arch}.${ext}"
  },
  "deb": {
    "artifactName": "${productName}-${version}-${arch}.${ext}"
  },
  "freebsd": {
    "artifactName": "${productName}-${version}-${arch}.${ext}"
  },
  "scripts": {
    "start": "electron .",
    "build:windows": "electron-builder -w --publish never",
    "build:macos": "electron-builder -m --publish never",
    "build:linux": "electron-builder -l --publish never",
    "build:appx": "electron-builder -w appx --publish never",
    "build:pacman": "electron-builder -l pacman --publish never",
    "build:appimage": "electron-builder -l AppImage --publish never",
    "pack": "electron-builder --dir",
    "build": "electron-packager . japankana --platform win32 --arch x64 --icon=japankana256.ico --overwrite --asar --out dist/",
    "package": "electron-installer-windows --src dist/japankana-win32-x64/ --icon=japankana256.ico --dest dist/installers/",
    "make": "electron-forge make",
    "import": "electron-forge import"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/xxxxxx/japankana.git"
  },
  "keywords": [
    "japankana",
    "japanhr",
    "Japanese",
    "Kanji",
    "Katakana"
  ],
  "author": "xxxxxx",
  "copyright": "Copyright © 2021 ${author}",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/xxxxxx/japankana/issues"
  },
  "homepage": "https://github.com/xxxxxx/japankana#readme",
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.54",
    "@electron-forge/maker-deb": "^6.0.0-beta.54",
    "@electron-forge/maker-rpm": "^6.0.0-beta.54",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.54",
    "@electron-forge/maker-zip": "^6.0.0-beta.54",
    "electron": "^12.0.2",
    "eslint": "^7.22.0",
    "eslint-plugin-jsdoc": "^31.6.1"
  },
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0",
    "electron-window-state": "^5.0.3",
    "kuroshiro": "^1.1.2",
    "kuroshiro-analyzer-kuromoji": "^1.1.0"
  },
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "japankana"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  }
}`

**Comment by styunan** [comment]
I set all the EXE shortcuts into the electron program, speechless

**Comment by OscarHedeby** [comment]
The same thing just happened to me, how did you fix it?
