### ISSUE TITLE
How to create multiple environments builds with electron builder

### ISSUE THREAD

**Issue by skyshine999** [electron-userland/electron-builder#5934]
Version: 22.11.3
Electron Version: 13.0.1
Electron Type (current, beta, nightly): current
Actually i wanted to create multiple flavours builds like staging,preproduction,production. With electron-builder local env variables and cross-env variables are also not working.
code:
   ```
  "electron": "cross-env ENV=staging electron .",  // this one is working
    "build:dit": "cross-env ENV=staging && electron-builder",
based on env variables
   if(process.env.ENV === "staging"){
        mainWindow.loadURL("https://reactjs.org/");
    }else if(process.env.ENV === "prod"){
        mainWindow.loadURL("https://www.opcito.com/blogs/managing-multiple-environment-configurations-in-react-app");
    }else{
        mainWindow.loadURL("https://dev.to/jsmanifest/create-your-first-react-desktop-application-in-electron-with-hot-reload-4jj5");
    }
```
i am loading like this, but this is not working

**Comment by mmaietta** [comment]
You're trying to do two separate things
`"cross-env ENV=staging electron ."` applies `ENV` var to the running command (your application)
`"cross-env ENV=staging && electron-builder"` applies `ENV` to the build process, which does nothing with it because there's nothing to do with it.

If you were to run your bundled app/dist with the env var specified as part of the command, it would be applied to the running command (your application). Such as with
`$ ENV=staging open -a <path to your .app>`

**Comment by suresh777** [comment]
so you are saying that generating multiple environments builds with electron builder is not possible with commands.For generating each environment build i have to change url in main browser window. Is there any way to pass dynamic environment variables to electron builder while building.

**Comment by suresh777** [comment]
I tried using webpack define plugin still i am not able to get env variable inside electron browser window.

package.json:
    "build:preprod": "cross-env STAND=preprod electron-builder",
    "build:prod": "cross-env STAND=prod electron-builder"
webpack.config.js:
     new webpack.DefinePlugin({
        "process.env":{
          "STAND":JSON.stringify(process.env.STAND)
        }
      }),
electron.js:
        if(process.env.STAND === "preprod"){
        mainWindow.loadURL("https://reactjs.org/");
    }else if(process.env.STAND === "prod"){
        mainWindow.loadURL("https://www.opcito.com/blogs/managing-multiple-environment-configurations-in-react-app");
    }else{
        mainWindow.loadURL("https://dev.to/jsmanifest/create-your-first-react-desktop-application-in-electron-with-hot-reload-4jj5");
    }

**Comment by mmaietta** [comment]
Webpack Define plugin is what I use in my project actually, however, I think that approach you're using may overwrite other env vars. Instead, I think the advised approach is `"process.env.STAND": JSON.stringify(process.env.STAND)`?

Regardless, you're running the electron-builder with the STAND=<var> configured, but that will never work. You're supposed to add that env var during the _compilation process_ (webpack).
i.e. `cross-env STAND=prod webpack`
After that, then you'd just run `electron-builder`, no env needed.

**Comment by vraravam** [comment]
On a meta aspect: why would one compile/build for each individual env separately? Wouldn't the evaluation of the current env-specific configs be a runtime responsibility? "Compile-once, promote to different envs"?

**Comment by suresh777** [comment]
suppose if i want to create 10 environments builds, i have to go into the code change the url to specific environment, i feel it's kind of redundant process

**Comment by jqueryisamonad** [comment]
@suresh777 you can do something like this:
```sh
for environment in staging preproduction production
do
  APP_ENV=$environment npm run build-webpack
  npm run build-electron
  mkdir -p builds
  mv build builds/$environment
done
```

**Comment by vraravam** [comment]
I'm not sure you understood what I asked @skyshine999 . Your target environment should be a runtime value. The compiled/packaged app should read this value at runtime to make logic paths.

**Comment by skylingfly** [comment]
any update
