### ISSUE TITLE
AppImage should have arch in filename

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#594]
* **Version**: master

* **Target**: Linux AppImage

The [recommended](https://github.com/AppImage/AppImageSpec/blob/e03b661e81d56ac3cc25fbd980db34eceaaaab4d/draft.md#specification) filename for an AppImage is AppName-1.0.1-**x86_64**.AppImage - this makes it easier for users to know which file to download. This would also allow me to do away with [workarounds  like this](https://github.com/probonopd/AppImages/blob/89096799eb6c7789c9cdec01eca610eb8859dbbf/recipes/electronbuilderapp/Recipe#L20-L23) in automated AppImage generation.

**Comment by develar** [comment]
Our convention for all targets that arch for x64 is not included in the name. Because x64 should be default (e.g., as macOS supports only x64). When you build for ia32, arch will be specified in the name. But I think this convention should be changed according to AppImage format.

**Comment by develar** [comment]
Also, we use currently `x64` (as node `process.arch` identifier). But I remember https://github.com/probonopd/AppImageKit/issues/178#issuecomment-229372662 and 

```
develar@ubuntu:~$ arch
x86_64
```

So, I don't like it, but... ok, we will use such suffix. Just want to be sure that it is really needed.
