### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch

### ISSUE THREAD

**Issue by janmechtel** [electron-userland/electron-builder#5940]
* **Version**:     "electron-builder": "^22.11.5",
* **Electron Version**:     "electron": "^12.0.8"
* **Electron Type (current, beta, nightly)**: current 
* **Target**: Win 64x

> Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected 9hPZayyjjUAUIMA+MhxQidIEUDl+Fir5vz9l38yPd40gUllpjA8Z8X1Q+N8LmGhyYtrRuyFu+AcfHA+0iC5XXw==, got 6B13SphX3U5/4qaSKpw6byvKT317XWI48UQHeBY4jDunHsKURJTfbbCPbczerb8mWDPEqcpdjeKS8NxRuPhOOw==
>     at Object.newError (C:\Users\xx\AppData\Local\Programs\xx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:47:19)
>     at DigestTransform.validate (C:\Users\xx\AppData\Local\Programs\xx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:323:27)
>     at WriteStream.<anonymous> (C:\Users\xx\AppData\Local\Programs\xx\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:133:41)
>     at WriteStream.emit (events.js:315:20)
>     at emitCloseNT (internal/streams/destroy.js:87:10)
>     at processTicksAndRejections (internal/process/task_queues.js:79:21)

I found similar issues but they were close without comments apart from trying to use 22.11.5

The upgrade works fine, but downloads the entire installed each time.

**Comment by Mgonand** [comment]
I'm comming from here #5836 and I think the error is in this line:
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/NsisUpdater.ts#L141

It should  be:
```js
const blockmapFileUrls = blockmapFiles(fileInfo.url, this.app.version, downloadUpdateOptions.updateInfoAndProvider.info.version)
```

For quick fix in node_modules code, edit the file `node_modules/electron-updater/out/NsisUpdater.js` and do this replace:
```js
// replace this
const blockmapFileUrls = util_1.blockmapFiles(fileInfo.url, downloadUpdateOptions.updateInfoAndProvider.info.version, this.app.version);

// with this
const blockmapFileUrls = util_1.blockmapFiles(fileInfo.url, this.app.version, downloadUpdateOptions.updateInfoAndProvider.info.version);
```

That did the trick for me. Hope it can help.

**Comment by janmechtel** [comment]
This works, thanks!

**Comment by stoefln** [comment]
@janmechtel why did you close this issue? This is not a real solution, since this line would have to be changed after each npm install. Am I wrong?
