### ISSUE TITLE
Updating from 22.10.5 to 22.11.5 causes nsis to fail windows archive creation

### ISSUE THREAD

**Issue by ggreco** [electron-userland/electron-builder#5943]
* **Version**: 22.11.5

* **Electron Version**: 13.1, 12.0.10
* **Electron Type (current, beta, nightly)**: stable
* **Target**: windows and mac

Trying to update from 22.10.5 to 22.11.5 causes the NSIS installer creation to fail with this error:

`⨯ ENOENT: no such file or directory, unlink '/Users/hudl/actions-runner/_work/wy-heat-hyperlays/wy-heat-hyperlays/dist/__uninstaller-nsis-hudlgfx.exe'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, unlink '/Users/hudl/actions-runner/_work/wy-heat-hyperlays/wy-heat-hyperlays/dist/__uninstaller-nsis-hudlgfx.exe'`

... it works again when switching back to 22.10.5.

Looking at the release history that probably should have been fixed here:

https://github.com/electron-userland/electron-builder/issues/5863

... but it's not.

**Comment by mmaietta** [comment]
What version of node are you using?

**Comment by ggreco** [comment]
> What version of node are you using?

14.3.0 the docs said that 14.0+ is ok.

**Comment by mmaietta** [comment]
Yes indeed. Was just curious, we've had a few other node-version incompatibilities reported in the past, wasn't sure if they were all resolved.

**Comment by mmaietta** [comment]
I think that might actually be resolved in this commit: https://github.com/electron-userland/electron-builder/commit/014cbf5f98a25d6537f9f2b49e90cc401a2f3bce
The NSIS target was building multiple installers/uninstallers in parallel.

@develar please perform a full release when you have a chance

**Comment by ggreco** [comment]
Latest version (22.13.1) works without problems.
