### ISSUE TITLE
NSIS - EULA is not always displayed on new installation

### ISSUE THREAD

**Issue by mboutin-qohash** [electron-userland/electron-builder#5944]
* **Version**: 22.10.5

* **Electron Version**:11.2.2
* **Electron Type (current, beta, nightly)**:current

* **Target**: Windows

<img width="764" alt="Screen Shot 2021-06-09 at 9 44 08 AM" src="https://user-images.githubusercontent.com/66835336/121366488-86e46080-c907-11eb-8cbb-181c83d8fe90.png">

The EULA don't show. We have to scroll or move the window. It's mandatory that we show it everytime for legal reasons.

Here are our config in the `package.json`:
```
"nsis": {
      "runAfterFinish": true,
      "oneClick": false,
      "deleteAppDataOnUninstall": true,
      "include": "scripts/nsis/installer.nsh",
      "license": "eula.html",
      "allowElevation": true,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true
    },
```

It happens maybe 1-2 times on 20, but it's still too much. Thank you in advance!

**Comment by mboutin-qohash** [comment]
The display is still unstable

**Comment by codagew** [comment]
I have the problem too.It appears when I use html license file,and can show when trigger scroll use a mouse

**Comment by lgushijima** [comment]
I'm having the very same issue here, does anyone has some tips on how to solve that?
