### ISSUE TITLE
Memory leak for appx Microsoft store upload

### ISSUE THREAD

**Issue by johannesjo** [electron-userland/electron-builder#5945]
* **Version**: 22.10.5

* **Electron Version**:  12.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**:  appx (Win)

[Several of my users are encountering a memory leak](https://github.com/johannesjo/super-productivity/issues/567) when downloading the appx from the Microsoft store. This doesn't happen for the Setup.exe and it doesn't happen on the pen drive or any other release. This leaves two possible sources for the error.
1. Something that is added or different for the appx build by electron builder
2. Something that is added when uploading the app to the store.

Help would be appreciated!

EDIT: Just a hunch, but I got the idea that this maybe is related to the commandline output of the app is being processed differently.

**Comment by Looooong** [comment]
Here is the [dump file](https://drive.google.com/file/d/1vSt5Sit2t1L8rnvFSP1DjuZ7TO1xheNg/view?usp=sharing) related to the possible memory leaking process.

**Comment by mmaietta** [comment]
@develar would you mind taking a look at this please?

**Comment by johannesjo** [comment]
This is still relevant.

**Comment by johannesjo** [comment]
Still relevant.
