### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Yongle-Fu** [electron-userland/electron-builder#5953]
NodeJS 12.18.3

.npmrc
```
runtime = electron
target = 7.3.3
```

fallback to  22.10.5 is ok

**Comment by alectrocute** [comment]
I'm experiencing this, but only on Travis.

**Comment by csett86** [comment]
"fs/promises" is available since node 14 (current lts), so to fix this on your end update your node version to 14+

**Comment by rafaelfquadros** [comment]
Recently also had the same error. Using ubunto 20.04, electron 8.2.5, electron-builder 22.6.0, electron-updater 4.3.1, I updated all previous packages and the error persists. I've even tested it with node 12, 14 and 16. I've also performed the same tests on another ubunto and the error persists, has anyone gone through something similar?
