### ISSUE TITLE
electron build creates binary, but createWindow() is never called 

### ISSUE THREAD

**Issue by rootVIII** [electron-userland/electron-builder#5958]
### electron-builder version:
```
solsticenet@mm1 cidr_calculator % npx electron-builder --version
22.11.7
```

### electron version:
```
solsticenet@mm1 cidr_calculator % npx electron --version                 
v13.1.2
```

### build target:
MacOS (Intel, not M1) 

### issue details:

I'm having some issues building binaries for MacOS; the application opens after installing via the DMG, but my application window never appears. The Node logo shows in the dock but no application can be seen (I didn't bother with an icon for now).

The application works fine via ```npm start .``` but no luck after making the ```dist/``` folder via ```npm run pack```.

I have the project in Git at https://github.com/rootVIII/cidr_calculator

When running the binary located in ```dist/``` I noticed that ```createWindow()``` never gets called. The server starts etc. and I can see a logging statement of mine indicating the server has started. However nothing gets called at all in the ```main.js``` file that contains the electron startup code.

I suspect that it cannot find ```main.js``` via my ```package.json``` through the line: ```"start": "electron main.js"```

Any suggestions? I'm worried maybe my project structure is incorrect for the binary...

**Comment by mmaietta** [comment]
I believe electron will use the path of wherever you entry is specified in `package.json`. For instance, mine is: ```"main": "out/main/main.js",``` in the `package.json`, but I run start with `electron .` since that starts from my root

In the binary, it'll be using the same approach and looking for your main.js using the `main` entry

**Comment by rootVIII** [comment]
Thanks @mmaietta ! Resetting the value I had for main to `main.js `did the trick. I will now commence shaking my head at myself.
