### ISSUE TITLE
Build the app (macos) on github action, It happen a error "struct.error"

### ISSUE THREAD

**Issue by catmans1** [electron-userland/electron-builder#5959]
* **Version**: 
"electron-builder": "^22.11.7",

* **Electron Version**: "electron": "^12.0.0",
* **Electron Type (current, beta, nightly)**:

* **Target**: 
Macos

I build the app macos on my local it's successful
but when build on virtual machine (I use github action) then it happen a error like this.
Anyone know this error and how to solve it?
Thank you.
![Screen Shot 2021-06-15 at 9 59 45 AM](https://user-images.githubusercontent.com/9440600/121978350-f56f6580-cdc2-11eb-9433-b135f4b23f68.png)

**Comment by mmaietta** [comment]
Hi there! Could you provide more info on the target/host machine? OS version, etc?

**Comment by catmans1** [comment]
@mmaietta Thank you for your reply
I use github action so this is machine info
![Screen Shot 2021-06-15 at 2 08 32 PM](https://user-images.githubusercontent.com/9440600/121996282-4727e800-cde3-11eb-8013-17a19b72031e.png)
