### ISSUE TITLE
Change installation directory when not using 'oneClick' with NSIS

### ISSUE THREAD

**Issue by gswebspace** [electron-userland/electron-builder#596]
electron-builder version
- **5.12.1**

Building for
- **windows nsis x64**

Building on
- **linux x64(Ubuntu 16.04)**

Assuming 'oneClick' is set to false for NSIS, and two package.json scheme is used with the development package.json having the build object as follows - 

``` javascript
"build": {
    "appId": "com.somerandom.name",
    "productName": "RandomName",
    "asar":false,
    "win": {
      "target": "nsis",
      "title": "TitleValue",
      "version": "1.0.0",
      "authors": "User Name"
    },
    "nsis":{
      "oneClick": false
    }
  }
```

The Installation directory(tested with Windows 10) defaults to 

> C:\Users\username\AppData\Local\Programs\appname

How can the user be allowed to change the installation directory ?

**Comment by develar** [comment]
If you want to install for all users, set `perMachine` to `true`. Or do you want to allow user to install to any location?

**Comment by meltedspark** [comment]
+1 For this one. Allowing user to install to a custom location.

**Comment by develar** [comment]
It is easy to do, will be implemented soon. But! Think twice — are you sure that your users will be more happy with boring installer instead of one-click (and without admin rights requirement)?

**Comment by gswebspace** [comment]
The default path works fine with one-click installs, it makes sense.This issue only applies if one-click install is not required. 

For such cases I want the user to be able to install to any location. If the user is an Administrator he should be allowed to choose the path suitable for his system configuration.

**Comment by meltedspark** [comment]
@develar 
You're right, but I can foresee that my users might request such a level of control (where to install).

**Comment by Murriouz** [comment]
+1
I think it's common sense for allowing users to choose where to install.

**Comment by domachine** [comment]
Is this possible to achieve using an `include` script?

**Comment by develar** [comment]
@domachine Yes. But if are able to make such change, it is better to send pull request.

**Comment by domachine** [comment]
@develar Ok, I'd happily send a pull-request. I'm just a little bit overwhelmed with this complex NSIS config. Currently figuring out the proper location to insert the `!insertmacro MUI_PAGE_DIRECTORY` statement. Would `customInit` be the right place?

**Comment by domachine** [comment]
OK, nope 😄 . The following include errors:

```
!macro customInit
  !insertmacro MUI_PAGE_DIRECTORY
!macroend
```

**Comment by develar** [comment]
@domachine You need to write completely different NSIS script — `script`. Sorry for false info.

**Comment by domachine** [comment]
@develar No problem. Do you have any hints on the template location where it might make sense to include such an option? Currently I'm hacking here https://github.com/electron-userland/electron-builder/blob/7ea3d62e837df0ae3c33b2a0dfe831964e077129/templates/nsis/boringInstaller.nsh#L28. As soon as I get somethin' working, I'll open a pull-request.

**Comment by develar** [comment]
Fixed in 11.1.0.

**Comment by gswebspace** [comment]
Thanks to all for the awesome new feature !

**Comment by Pandakls** [comment]
But now, we have a boring installer even for updates, am i wrong ?
How can i fix it ?
