### ISSUE TITLE
Missing information how to build for arm64 and x64

### ISSUE THREAD

**Issue by seb-mtl** [electron-userland/electron-builder#5962]
* **Version**: 22.11.7

* **Electron Version**: 13.1.2
* **Electron Type (current, beta, nightly)**: current
* **Electron-updater**: 4.3.9
* **Target**: *Mac *arm64** & **x64**

# Description

I'm building an Electron app on Mac for **arm64** and **x64**. There are 2 options for bundling. Could anyone help out with either or both of them?

1. Fat/Universal build

* Advantages: One file to rule them all
* **Problem**: There is no documentation how to build an Electron app for universal arch.

2. Seperate build
* Advantage 1: Smaller app bundle
* **Problem**: There is no documentation about how to use it with **electron-updater**. I've two build machines (arm64 and x64) and both would overwrite each others `latest-mac.yml`. Are there any insights to this topic how to have one `latest-mac.yml` with both architectures?

**Comment by mmaietta** [comment]
Regarding #1: This post has info on how to configure for `--universal` via CLI and in electron-builder.js config
https://github.com/electron-userland/electron-builder/issues/5689#issuecomment-792876001

**Comment by seb-mtl** [comment]
That solved my issue! Thanks!
