### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by pxr-mm** [electron-userland/electron-builder#5966]
Version: 22.11.7
Electron Version: 13.1.2
electron-builder: ^22.11.7,
Target: window

builder 
(node:7460) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'build' of undefined
    at D:\projects\admin\CrawlerBot\SpiderBot\node_modules\@quasar\app\lib\electron\index.js:136:21
    at new Promise (<anonymous>)
    at D:\projects\admin\CrawlerBot\SpiderBot\node_modules\@quasar\app\lib\electron\index.js:127:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mmaietta** [comment]
Hi there! 
How are you configuring electron-builder? What's your package.json look like?
