### ISSUE TITLE
Application is not signed when using prepacked builds

### ISSUE THREAD

**Issue by mook-as** [electron-userland/electron-builder#5968]
* **Version**: 22.10.5
(Checked with code inspection, issue should still be present as of 29.30.0)

* **Electron Version**:12.0.9
* **Electron Type (current, beta, nightly)**: Current (Obsolete?)

* **Target**: Windows

When building with `electron-builder --prepackaged`, the executable isn't signed; the installer and uninstaller are signed properly.  This appears to still be the case in versoin 29.30.0: on entering `doPack()`, it exits early if it's a prepackaged build:
https://github.com/electron-userland/electron-builder/blob/775c2553775c10b3c9b8ee6e86022b7f02aa8aa8/packages/app-builder-lib/src/platformPackager.ts#L166-L169
But the app signing is invoked later in the same function:
https://github.com/electron-userland/electron-builder/blob/775c2553775c10b3c9b8ee6e86022b7f02aa8aa8/packages/app-builder-lib/src/platformPackager.ts#L236

For context, I'm attempting to set up a workflow that's something like:
- Build the application in CI.  This does not have access to the certificates.
- Do some manual testing, etc.
- Manually sign the same zip built from CI, to ensure that it's the same bits that were tested.

I do not believe logs & `package.json` are relevant here, as the actual build succeeds (and, again, the installer and uninstaller executables are both signed correctly).  If this is the intended behaviour, then please treat this as a request to expanded the [prepackaged option documentation](https://www.electron.build/#pack-only-in-a-distributable-format) to indicate this.

**Comment by mmaietta** [comment]
AFAIK, that is indeed intended behavior. Maybe to prevent signatures from being overwritten? I'm not sure on the historical reasoning there. Any ideas by chance?

I use `electronDist` and it seems might be similar to what you're looking for. It allows you to specify the path to a zip of your prepackaged electron. It's not exactly the same, but the signing does complete as expected
It's basically mirroring the functionality of downloading electron dist (thus expects the same filename nomenclature), but allows you to utilize any of your own resources.
https://github.com/electron-userland/electron-builder/blob/c9b78f958daf778747843dd2d671628f9cbb8ef6/packages/app-builder-lib/src/electron/ElectronFramework.ts#L166-L176

That being said, it differs from your use case as it will completely repackage the app when using `electronDist`

**Comment by hrivks** [comment]
Running into this as well with the prepackage option. At minimum, please update documentation to reflect this behavior.
