### ISSUE TITLE
Semantic versioning rules seem to be violated

### ISSUE THREAD

**Issue by gtryus** [electron-userland/electron-builder#5969]
* 22.11.7: 
The requirements for node changed. According to the comments, they changed during a patch release from 22.11.4 to 22.11.5! Even if they changed from 22.10.x to 22.11.x changing the version of node from 12.x to 14.x broke the build on the build agent. To me it is a violation of semantic versioning to change the node dependency of electron-builder without making a major version change since it will require the user to update their computer and all their continuous integration build agents.

**Comment by mmaietta** [comment]
Yes... that does seem correct.
Now what to do about that, idk. I don't have access to publishing or manage the versioning, unfortunately.
