### ISSUE TITLE
extraResources parent directory

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#597]
Is it not possible to go outside the current directory? 

For .directories.app this is possible.

But for build.extraResources it seem not; 

`build.extraResources = ["../extra/**/*"]`

**Comment by develar** [comment]
`extraResources` *relative to the project directory*. Do you want to copy resources outside of project directory?

**Comment by atypicalprogrammer** [comment]
This is my structure

Folder 
  -- Packager (contains electron-builder)
  -- App
  -- Extra

All these are separate git repo's, that's why I can't include them together. So yes, I want to copy resources outside of the packager directory.

**Comment by develar** [comment]
And dev `package.json` in the `Packager`? Hmm... your setup is strange :) Why you cannot put `App` inside `Packager `? Just add `App` to `.gitignore`.

**Comment by atypicalprogrammer** [comment]
Seems easier like I have it now :-) but OK.

**Comment by develar** [comment]
FYI: My working project contains 8 inner git repositories :)

**Comment by atypicalprogrammer** [comment]
Well actually it seems illogical. Now I have to package my App inside a Packager folder. That just doesn't make sense. But fine!

**Comment by develar** [comment]
> it seems illogical

Well... To build app, you need some non-production code. Your `Packager` acts as a meta-directory — logical for me.

**Comment by atypicalprogrammer** [comment]
Ideally one should be able to run the packager from anywhere I want. That seems more logical. But that's just my humble opinion ;-)

**Comment by develar** [comment]
> Ideally one should be able to run the packager from anywhere I want.

You can, but `extraResources` should be in the project basedir ;) (location, where do you run / dev package.json is located). It can be fixed, but as there is a acceptable solution, it will be not fixed for now :)

**Comment by atypicalprogrammer** [comment]
How about we can add resources in the app folder, but not have them in the asar? so it would be app/resources or something and they'd automatically be added as extra resources. Not in asar is what I need.

**Comment by develar** [comment]
> How about we can add resources in the app folder, but not have them in the asar?

Originally, it was implemented for 2 package.json scheme. So, extra resources is not filtered automatically.

Why it is included if you have `Extra` not in the `App`?

**Comment by chrigu-ebert** [comment]
I have the same problem as @atypicalprogrammer because my application lives next to the packaging project. The application is a separate project used by other projects so I also think it should not live inside the packager directory :)

**Comment by develar** [comment]
@chrigu-ebert Now you have extraFiles/extraResources/files — please see https://github.com/electron-userland/electron-builder/wiki/Options

**Comment by chrigu-ebert** [comment]
@develar woah thanks for the super fast response! I'll check it out! Seems to do the trick :)
