### ISSUE TITLE
electron-builder 打包后不能使用 ipcmain.handle 方法

### ISSUE THREAD

**Issue by cnblogco** [electron-userland/electron-builder#5973]
const { BrowserWindow, app, dialog, ipcMain } = require("electron")
const path = require("path")

let win;
const create = () => {
  win = new BrowserWindow({
    width: 1400,
    height: 800,
    minWidth: 800,
    minHeight: 400,
    autoHideMenuBar: true, // 否则隐藏菜单栏.默认为 false。
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: false // 解决跨域
    },
  })

  win.loadFile(path.resolve(__dirname, './index.html'))
  win.openDevTools()
  dialog.showErrorBox('title', ` on:${ipcMain.on ? true : false}   handle: ${ipcMain.handle ? true : false}`);

  // ipcMain.handle('on-click', async (event, args) => {
  //   return '你是小可爱'
  // })

}

app.on("ready", () => {
  create()

})

ipcMain.handle：会输出 false

**Comment by mmaietta** [comment]
Is there a question to go with this?
