### ISSUE TITLE
Electron builder Can not find fs/promises

### ISSUE THREAD

**Issue by abhishekmatta999** [electron-userland/electron-builder#5978]
Error: Cannot find module 'fs/promises' Require stack:

```
/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/builder-util/out/fs.js
/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/builder-util/out/util.js
/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/electron-builder/out/cli/cli.js
/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/electron-builder/cli.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15) at Function.Module._load (internal/modules/cjs/loader.js:690:27) at Module.require (internal/modules/cjs/loader.js:852:19) at require (internal/modules/cjs/helpers.js:74:18) at Object. (/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/builder-util/src/fs.ts:4:1) at Module._compile (internal/modules/cjs/loader.js:959:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14) at Module.require (internal/modules/cjs/loader.js:852:19) at require (internal/modules/cjs/helpers.js:74:18) at Object. (/Users/abhimatta/Documents/abhishek/accura-electron-dev/node_modules/builder-util/src/util.ts:24:1) at Module._compile (internal/modules/cjs/loader.js:959:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Package.json configurations
```

"electron": "^10.4.0",
"electron-builder": "^22.10.4",
"node": "10.22"

**Comment by mmaietta** [comment]
For electron-builder ^22.11, you should use node 14+

**Comment by abhishekmatta999** [comment]
I'm using electron builder ^22.10.4 why it is giving this error?

**Comment by abhishekmatta999** [comment]
> For electron-builder ^22.11, you should use node 14+

I'm using ^22.10

**Comment by mmaietta** [comment]
https://github.com/electron-userland/electron-builder/pull/5880

**Comment by Bartel-C8** [comment]
Same problem here... But your electron uses another node version (in my case), e.g.:

Electron v8.2.0 | Chromium v80.0.3987.158 | Node v12.13.0 | v8 v8.0.426.27-electron.0

So need to update Electron?

**Comment by mmaietta** [comment]
@abhishekmatcha, please try updating to node 12 then.

@Bartel-C8, yes, electron would need to be updated to one that supports Node 14.
Is that not possible for you to do?

**Comment by KishanBagaria** [comment]
We run on Electron 11 and apply a patch for `node_modules/electron-updater/out/AppUpdater.js`:

```patch
8c8
< const promises_1 = require("fs/promises");
---
> const promises_1 = require("fs").promises;
```

**Comment by jzybert** [comment]
Had the same issue, but can't update to Node 14 yet. Downgraded my electron-builder dependency to 22.10.5 and it worked

**Comment by investisocial** [comment]
> We run on Electron 11 and apply a patch for `node_modules/electron-updater/out/AppUpdater.js`:
> 
> ```diff
> 8c8
> < const promises_1 = require("fs/promises");
> ---
> > const promises_1 = require("fs").promises;
> ```

This worked for me, Thank you :)

**Comment by MaShizhen** [comment]
I fixed this problem by rollback electron-updater version=4.3.9

**Comment by brgirgis** [comment]
Facing the same issue with node-v16.13.0-win-x64 and `electron-updater` latest=4.6.1. I get this error:

```
Failed to start the electron application.
Error: Cannot find module 'fs/promises'
```

Fixing this one line:

```
const promises_1 = require("fs/promises");
```

and changing it to:

```
const promises_1 = require("fs").promises;
```

Everything seems to work fine.

**Comment by abhishekmatta999** [comment]
> Had the same issue, but can't update to Node 14 yet. Downgraded my electron-builder dependency to 22.10.5 and it worked

Hi, Can you share your package.json file

**Comment by abhishekmatta999** [comment]
> 
Hi, Can you share your package.json file

**Comment by GiovanH** [comment]
Same issue.
