### ISSUE TITLE
Error while launching packaged app on Windows 10 (Surface)

### ISSUE THREAD

**Issue by RilRil** [electron-userland/electron-builder#598]
Hello,  i've got some trouble with Windows 10 ...
I'm packaging for platform windows x64 using electron 1.2.7; electron-builder 5.12.1 on a windows 10 x64.

when I execute the app file in the win-unpacked directory on the machine I packaged on everything is working correctly. 
But If I try to execute the same file on a Windows Surface I get this error : 
![screenshot](http://img11.hostingpics.net/pics/151917screenshoterror.png)

the module file (4753.tmp.node) exists ...

any idea ?

**Comment by develar** [comment]
Set [build.asar: false](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-asar)

Please see https://github.com/electron-userland/electron-packager/issues/425

**Comment by develar** [comment]
Do you use native extensions or do you execute external exe?

**Comment by RilRil** [comment]
what do you mean ?

**Comment by develar** [comment]
Please try to set [build.asar](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-asar) to `false` as temporary workaround. 

And 

> Do you use native extensions or do you execute external exe?

**Comment by RilRil** [comment]
oh ok sorry.
I'am using some native extensions

**Comment by RilRil** [comment]
When I'm packaging I have this message : "Skip app dependencies rebuild because dev and app dependencies are not separated", I dont know if it can be related though ...

**Comment by develar** [comment]
> I dont know if it can be related though

It means that you can build only on the same platform — i.e. you cannot build on Linux on Windows. It is not the reason of the issue (since you build in WIndows).

Asar is the issue, see http://electron.atom.io/docs/latest/tutorial/application-packaging/#limitations-on-node-api/

So, disable asar, and report — does it help you. If helps, please provide sample project (or name of native extensions) and I will try to fix it (such files should be not packed into asar archive). Or you can try to use `asar.unpackDir`.

**Comment by RilRil** [comment]
With the build.asar option to false  I now get the following error : 
![screenshot](http://img11.hostingpics.net/pics/921414screenshot2.png)

**Comment by develar** [comment]
Maybe for MS Surface you have to recompile native ext. I cannot help. BTW, is Surface is ARM or x86?

**Comment by RilRil** [comment]
it's x86. ok that's too bad ..  I'll try to remove that extension or maybe to recompile on the surface..

**Comment by develar** [comment]
Is your packaged app works on other words nodes machine? You can send me your app and I will try to investigate what is wrong. Develar@gmail.com

**Comment by RilRil** [comment]
It works if I execute the packaged app on the machine I packaged it...

**Comment by develar** [comment]
I doubt that Surface is the issue. So, I ask you sample/real project to investigate.

**Comment by RilRil** [comment]
Ok I made some progress, 
I run the app a first time, I get the error...
then I go to C:\Users<user>\AppData\ and I delete \Local<myapp> and Roaming<myapp>
I try again and it works !

I run my tests on a "clean" machine. Fresh windows install, no nodeJs, no electron, nothing.

Does this make sens to anyone ?

**Comment by bordunez** [comment]
Hi RilRil,
 I'm getting a similar problem with a native extension (windows.devices.geolocation), can you give some suggestion in order to find what is the missing .dll dependency in this native extension?

Thanks

**Comment by RilRil** [comment]
Hi @bordunez ,
in my case, the missing library (.lib) was referenced in a file (binding.gyp) of one of my dependancies. 

Maybe this could help you : http://stackoverflow.com/questions/33205339/what-dll-is-needed-for-windows-devices-geolocation,
