### ISSUE TITLE
Auto update doesn't work : MAC os Target .pkg

### ISSUE THREAD

**Issue by vivekthumarsixberries** [electron-userland/electron-builder#5985]
Previously we were using **.dmg** target and published on the **S3 bucket**, So on S3 and electron app it creates **latest-mac.yml** and **app-update.yml** files automatically, and for the next version app automatically update. 

But Right now we are using target as **.pkg** . The auto-updater is now stopped. **latest-mac.yml** and **app-update.yml** are not creating for **.pkg** target. But build uploaded to s3 successfully.

package.json

"package-ci": "yarn postinstall && yarn build && electron-builder --publish always",
.....
"mac": {
      "entitlements": "build/entitlements.mac.inherit.plist",
      "entitlementsInherit": "build/entitlements.mac.inherit.plist",
      "icon": "./resources/icon.png",
      "target": [
        "pkg"
      ]
    },
    ........
     "publish": {
      "provider": "s3",
      "bucket": "build",
    }

**Comment by mmaietta** [comment]
Hi @vivekthumarsixberries !
Is this a recent regression? What version was it previously working on?

**Comment by vivekthumarsixberries** [comment]
we are using electron 8.5.0 and electron-builder 22.8.0

**Comment by has-n** [comment]
@mmaietta am I missing something here? I thought pkg was not an acceptable target for auto updates? https://www.electron.build/auto-update#auto-updatable-targets

**Comment by vivekthumarsixberries** [comment]
@has-n and @mmaietta 

I tried with 

"target": [
"pkg",
"zip"
]

and it's working like dmg target. So I conclude that for dmg we just need to define the target as dmg and for pkg need to define two targets pkg and zip.

If you have any technical descriptions please let me know.

**Comment by has-n** [comment]
The default is "dmg" + "zip". I can't find any documentation to support "pkg" +"zip". If it's unsupported behaviour, you might want to be careful using it in production. Maybe @mmaietta can shed more light on this.
