### ISSUE TITLE
StdUtils.ExecShellAsUser not working when passing in an --arg

### ISSUE THREAD

**Issue by dtully** [electron-userland/electron-builder#5988]
* **Version**: 22.11.7

* **Electron Version**:13.1.3
* **Electron Type (current, beta, nightly)**:current

* **Target**: NSIS

I'm trying to write a NSIS custom script to pass any command line parameters launched by the installer itself to the installed application. The issue is that StdUtils.ExecShellAsUser does not seem to work when you pass in args. For example, this command does not work (It never opens the application, if I remove --testingMode it works fine);

 ${StdUtils.ExecShellAsUser} $0 "$launchLink" "open" "--testingMode"

**Comment by mmaietta** [comment]
I don't know much about NSIS, but I'm curious, can you see if this works?
`"open --testingMode"` where the strings are concatenated

**Comment by dtully** [comment]
Thanks so much for the feedback. I tried your suggestion and a few variations but no luck. It seems like "Open" needs to be passed alone and the arguments need to be the last parameter passed in. But it will only work if arguments="".
