### ISSUE TITLE
extraResources in app folder

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#599]
How about we can add resources in the app folder, but not have them in the asar? so it would be app/resources or something and they'd automatically be added as extra resources. Not in asar is what I need. Or simply (probably better) if the path is specified in extraResources, it is not added to the asar.

What did you mean by: Why it is included if you have Extra not in the App?

**Comment by develar** [comment]
> What did you mean by: Why it is included if you have Extra not in the App?

I mean that when you use 2-package.json structure, extraResources is not in the app dir, and, so, we don't need to exclude it.
