### ISSUE TITLE
electron-builder not being able to create an image out of icon.ico

### ISSUE THREAD

**Issue by SirReadsALot** [electron-userland/electron-builder#5991]
* **Version**: 22.10.5

* **Electron Version**: v9.0.0

* **Target**:  Windows

So basically, after I run the `npm run pack` and click on the exe file of the product
it says `Cannot create image out of  "./build/icon.ico"`
and it runs the app but the icon is switched to the default one and the menu is also displayed as the default one

I tried using previous versions like v8.0.0 but the result was the same

**Comment by mmaietta** [comment]
Some applications seem to output in a format our image converter can't utilize or recognize sometimes. Can you try using a different application to export your `icon.ico` file?

**Comment by SirReadsALot** [comment]
> Some applications seem to output in a format our image converter can't utilize or recognize sometimes. Can you try using a different application to export your `icon.ico` file?

Hello mmaietta, I tried to export ico files from every ico covertor I have seen and electron still throws this error after I build it using electron-builder
