### ISSUE TITLE
Pack Only in a Distributable Format

### ISSUE THREAD

**Issue by petef19** [electron-userland/electron-builder#5994]
* **Version**:  22.11.7

* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**: stable

* **Target**: win / nsis

Hello,

I'm using the `--prepackaged` option, all working, just have some questions that I could not find the answers to in the docs:

(1) why does the installer get copied to C:\Users\<username>\AppData\Local\ when the exe is executed and the app is installed ? is there any way to prevent that ? 

I do not want to clog up the users machine with unnecessary files, especially not the OS drive.
		
(2) what is the `--projectDir` option for when building an already packaged app ?

(3) how can I invoke the `--prepackaged` option programmatically via JS (not via CLI) ?

(4) where does electron-builder get the version from (of the prepackaged app) that is used in the name of the installer file ?

Thanks.

**Comment by mmaietta** [comment]
Are you looking for this?
https://www.electron.build/configuration/nsis#portable

**Comment by petef19** [comment]
@mmaietta: 

no, not at all. And your answer does not address any of my 4 questions...

**Comment by mmaietta** [comment]
JS entry point
https://www.electron.build/api/electron-builder#electron-builderbuildrawoptions-promisearraystring
Also can be traced to here: 
https://github.com/electron-userland/electron-builder/blob/0447b2457beb03648f1e7e841cd0a8d12d7e4aea/packages/electron-builder/src/builder.ts#L210-L213

rawOptions -> CliOptions -> PackagerOptions contain `config` var, that can accept your `electron-builder.js`, and a `prepackaged` var as well.
https://github.com/electron-userland/electron-builder/blob/0447b2457beb03648f1e7e841cd0a8d12d7e4aea/packages/app-builder-lib/src/packagerApi.ts#L9-L25
Version should be coming from package.json

I don't have my main project around, but it should be something like:
`electronBuilder.build({ config: require(./electron-builder.js) })`

**Comment by petef19** [comment]
Thanks for that !

so re my first question
> (1) why does the installer get copied to C:\Users<username>\AppData\Local\ when the exe is executed and the app is installed ? is there any way to prevent that ?

how can I avoid that ?

**Comment by mmaietta** [comment]
Are you asking if you can change the default install path or if you can have the app run without being installed?
The latter is nsis-portable.

**Comment by petef19** [comment]
neither ;-)

I'm saying that when the app is installed via the installer (that is created by electron-builder), the installer file itself is then also copied to  `C:\Users\AppData\Local\`, basically creating a **duplicate**. This clutters up the user's OS drive w/ unnecessary files.

How can I avoid/prevent that the installer is copied/duplicated ?

**Comment by mmaietta** [comment]
Oh...I didn't know that. I honestly have no idea where to start for that.

**Comment by petef19** [comment]
@mmaietta 

so where do we go from here ? how do we prevent this ?

Lmk if I can help testing etc

Thanks

**Comment by mmaietta** [comment]
PRs are most welcome! And a local dev env is pretty simple to set up too 🙂 https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
