### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB

### ISSUE THREAD

**Issue by snaildos** [electron-userland/electron-builder#5995]
* **Version**:  latest NPm version 22.17.7

1.13 latest

* **Electron Version**: latest
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows, linux snap

Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
Fairly annoying to update to clients using my app, since this is the error they are getting, how can I fix this ? What can I do to compress ?

**Comment by mmaietta** [comment]
Can you please try `electron-builder@^22.11.7`

**Comment by snaildos** [comment]
> Can you please try `electron-builder@^22.11.7`

I can't really mess around with that stuff since I don't have access to custom build servers. But is it seemed to be fixed on that version?

**Comment by mmaietta** [comment]
It shouldn't be a build server configuration, that version can just be specified in your project's package.json

That limit was increased significantly to 500mb in this PR
https://github.com/electron-userland/electron-builder/pull/5843/files

**Comment by snaildos** [comment]
Ah. Perfect, I just updated all my apps to the latest version and did a announcement to manually upgrade. Resolved.
