### ISSUE TITLE
Windows ignores config dot-notation when also specifying config file

### ISSUE THREAD

**Issue by jamezrin** [electron-userland/electron-builder#5997]
* **Version**: 22.11.7
* **Electron Version**: 11.4.9
* **Electron Type (current, beta, nightly)**: current
* **Target**: Windows (the problem), Linux and Mac OS

In the application I'm building I need to disable the asar packing, and instead have it all uncompressed. 

I run electron-builder with `-c.asar=false` but it doesn't seem to work on Windows. On Linux and MacOS it works, I validated the package doesn't have the asar and also the following message is printed for Linux and MacOS, but not on Windows:
```
asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
````

Does windows not support this option? I tried it multiple times and it's consistently never taking it into consideration.

The source code of the app is open [check here](https://github.com/jamezrin/notion-repackaged) and the workflow run is available here: https://github.com/jamezrin/notion-repackaged/runs/2925831089?check_suite_focus=true (compare Build App for linux or macos vs windows)

**Comment by mmaietta** [comment]
That's very odd indeed!
Does this only occur via CLI? Or does it occur also when specified in the yaml config file?

**Comment by jamezrin** [comment]
Good question! I have pushed a commit with `asar: false` specified in the windows platform directly, I'll let you know if that works.

**Comment by jamezrin** [comment]
I can confirm it only occurs when passing it through the CLI: 
https://github.com/jamezrin/notion-repackaged/runs/2926031117?check_suite_focus=true

I don't know much about how electron-builder works behind the hood so this may be a stretch, but can it be because of the order of the arguments I'm passing to electron-builder?. I'm calling it like this:
```
node_modules/.bin/electron-builder --windows -c.asar="false" -c.productName="Notion Enhanced" --config ../electron-builder.yaml
```

That wouldn't explain why it works for Linux and MacOS, but I don't know... I have also tried adding/removing the quotes around the boolean value of `-c.asar` and doesn't make a difference.

**Comment by mmaietta** [comment]
I'm actually not too familiar with the CLI either, but from just a quick guess, it seems like the `--config` entry is overwriting the `-c.asar` arg. The yaml file probably just takes precedence.

An alternative way of handling both use cases would be using an `electron-builder.js` config and having `asar: process.env.ASAR`.
But...I also just discovered that yaml should accept env vars so you could do this in `electron-builder.yaml`

```
appId: com.github.notion-repackaged
productName: ${PRODUCT_NAME:Notion}
asar: ${ASAR:true}
```

`ASAR=false PRODUCT_NAME="Notion Enhanced" npx electron-builder -w`

**Comment by jamezrin** [comment]
Yeah, I thought that too but I don't see why it would fail on Windows and be okay in Linux and MacOS... Maybe it's something in yargs that parses the options differently between Windows and other OS. I thought somewhere around here https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/builder.ts#L130

I tried using the env vars in the yaml file and that doesn't seem to work, as seen in [this log](https://github.com/jamezrin/notion-repackaged/runs/2926755842)

I would like to find a fix and submit a PR, but I'm not going to be able to look at this again until next Saturday. I can easily reproduce the issue so even if I don't get to fix it I might be able to see the root of the problem.

I will update this issue in 5 days regarding my findings. Thanks for the help.

**Comment by jamezrin** [comment]
As I suspected, arguments are parsed differently between Windows and other platforms. 

On Windows, every option is a string. On Linux (or Mac) there is an object with "dot-notation" options as well as the config path. See the following examples:

Windows
```
Raw options {
  _: [],
  windows: [],
  win: [],
  w: [],
  c: [
    '.asar=false',
    '.productName=Notion Enhanced',
    '../electron-builder.yaml'
  ],
  config: [
    '.asar=false',
    '.productName=Notion Enhanced',
    '../electron-builder.yaml'
  ],
  p: 'never',
  publish: 'never',
  '$0': 'node_modules\\electron-builder\\cli.js'
}
```

Linux (same as Mac)
```
Raw options {
  _: [],
  macos: [],
  mac: [],
  m: [],
  o: [],
  c: [
    { asar: 'false', productName: 'Notion Enhanced' },
    '../electron-builder.yaml'
  ],
  config: [
    { asar: 'false', productName: 'Notion Enhanced' },
    '../electron-builder.yaml'
  ],
  p: 'never',
  publish: 'never',
  '$0': 'node_modules/.bin/electron-builder'
}
```

I'm not sure how this should be fixed. I think it's a yargs's issue, but it could certainly be remediated here, right?

**Comment by mmaietta** [comment]
`yargs@17` is the latest and was updated in our most recent release v22.11.8, can you give that a shot?

**Comment by jamezrin** [comment]
I'm building from source + a commit that adds a `console.log` call to print the raw options, I'm emulating a local development environment but on the CI https://github.com/jamezrin/tests-electron-builder/blob/master/.github/workflows/main.yml
