### ISSUE TITLE
I want to call `electron-builder` using JS, where should I start?

### ISSUE THREAD

**Issue by AlanSean** [electron-userland/electron-builder#5998]
* **Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:

**Comment by m4heshd** [comment]
API documentation is right here - https://www.electron.build/api/electron-builder.
It's not very clear though. But you should get the hang of it once you fiddle around with it a bit.

**Comment by AlanSean** [comment]
Thanks!
