### ISSUE TITLE
Environment Variables are undefined 

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron-userland/electron-builder#6003]
* **Version**: ^22.10.5

* **Electron Version**: ^12.0.4
* **Electron Type (current, beta, nightly)**:

* **Target**: Mac (and Windows)

I have my `electron-builder.env` file in the root directory. The variables used for code signing (CSC_LINK) are working perfectly fine, but when I try to add an apiKey like this:

`API_KEY=Azq739u2-fdsfdsfnfndjdjdjdjdjdjFakeKey`

I only get undefined when operating the app.

Is there a way to inject environment variables into a distribution? Is there something wrong with my syntax?

**Comment by mmaietta** [comment]
CSC_LINK is an env var that electron-builder uses for/during packaging.
electron-builder doesn't inject env vars into your bundle, that should be done by your bundler. My project uses webpack's DefinePlugin for that purpose.
