### ISSUE TITLE
Install/Update broken on Windows server on v22.11.7

### ISSUE THREAD

**Issue by mansoor93** [electron-userland/electron-builder#6006]
* **Version**:  22.11.7

* **Electron Version**: 12.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS

The app is unable to install or auto-update on Windows server. 
This issue doesn't exist in v22.11.5.
The message on installation seems to be at first that the "App is running, Click to close". After clicking on it the message is "App cannot be closed. Please close it manually and click Retry to continue""
the app isn't running.
For update, as we use quitAndInstall on startup if there's an update, it just quits and doesn't start the update process. Making the app completely broken.

I think the issue is that its not checking if the app is running for the current user, and fails when another user on the server has the app open.

I believe it comes from this PR https://github.com/electron-userland/electron-builder/pull/5902/files
Before it was continuing even if it fails to close the app

Current workaround is to downgrade to v22.11.5

**Comment by shogo-fujisaki** [comment]
just in case you don't know: this got fixed by #6771 and #6472
