### ISSUE TITLE
Issue building for Mac App Store, due to app-builder-lib entitlements not having app-sandbox

### ISSUE THREAD

**Issue by mahgo** [electron-userland/electron-builder#6008]
* **Version**: 
22.9.1

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:
11.1.0

* **Target**: 
OSX - Mac App Store

I'm trying to my app submitted to the mac app store but it's failing because the app-builder-lib entitlements don't container app-sandbox. When I manually add it in, I'm able to submit it to the app store. What is the proper way to build for the Mac App Store so that app-builder-lib doesn't have this sandbox issue?

**Comment by mmaietta** [comment]
You should specify your own entitlements file if you need to customize it.

From the documentation https://www.electron.build/configuration/mas
>entitlements String - The path to entitlements file for signing the app. build/entitlements.mas.plist will be used if exists (it is a recommended way to set). Otherwise default.

>entitlementsInherit String - The path to child entitlements which inherit the security settings for signing frameworks and bundles of a distribution. build/entitlements.mas.inherit.plist will be used if exists (it is a recommended way to set). Otherwise default.

electron-builder default uses:
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/default.entitlements.mas.inherit.plist
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/electron-osx-sign/default.entitlements.mas.plist

**Comment by mahgo** [comment]
Thanks @mmaietta, I already had entitlements set, but adding entitlementsInherit as well did the trick.

**Comment by Slapbox** [comment]
@mmaietta those links are now dead, as is the link in the documentation: https://www.electron.build/configuration/mac.html

> Otherwise [default](https://github.com/electron-userland/electron-osx-sign/blob/master/default.entitlements.darwin.inherit.plist).
