### ISSUE TITLE
How to use single package.json structure

### ISSUE THREAD

**Issue by amilajack** [electron-userland/electron-builder#601]
The docs describe how to use the two package.json structure. However, when following this structure, I came across `dlopen` issues. How can I use a single package.json structure?

In my package.json, I have the following:

```json
  build": {
    "appId": "...",
    "app-category-type": "public.app-category.video",
    "win": {
      "iconUrl": "..."
    }
  },
  "directories": {
    "app": ".",
    "output": "release"
  }
```

Upon package, however, I get an error saying that my `main.js` file cannot be found.

**Comment by develar** [comment]
Do not specify `app` directory as `.` Just not specify it.

> when following this structure, I came across dlopen issues. 

Please provide more details or sample project. Maybe related: https://github.com/electron-userland/electron-builder/wiki/Loading-App-Dependencies-Manually

**Comment by fabiantheblind** [comment]
It would be great to have some more info on using just a single package.json file

**Comment by develar** [comment]
@fabiantheblind You can see project https://github.com/nodejs/installer It is  single package.json file project.

**Comment by fabiantheblind** [comment]
Thank you @develar

**Comment by fabiantheblind** [comment]
@develar I did it exactly like this but I'm running into an issue with that:  

    > frontal@0.5.0 dist /Users/me/path/to/my/project/root
    > build
    
    Error: ENOENT: no such file or directory, open '/Users/me/path/to/my/project/root/app/package.json'
        at Error (native)
    From previous event:
        at Packager.<anonymous> (/Users/me/path/to/my/project/root/node_modules/electron-builder/src/packager.ts:73:55)
        at next (native)
        at runCallback (timers.js:566:20)
        at tryOnImmediate (timers.js:546:5)
        at processImmediate [as _immediateCallback] (timers.js:525:5)
    From previous event:
        at tsAwaiter (/Users/me/path/to/my/project/root/node_modules/electron-builder/src/util/awaiter.ts:10:47)
        at Object.build (/Users/me/path/to/my/project/root/node_modules/electron-builder/src/builder.ts:193:52)
        at Object.<anonymous> (/Users/me/path/to/my/project/root/node_modules/electron-builder/src/build-cli.ts:27:28)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.runMain (module.js:575:10)
        at run (bootstrap_node.js:352:7)
        at startup (bootstrap_node.js:144:9)
        at bootstrap_node.js:467:3

looks like the same issue as #600

**Comment by develar** [comment]
@fabiantheblind Yes, it is #600

**Comment by fabiantheblind** [comment]
@develar thanks. I renamed my app folder and now run into errors of mismatching native modules   

    Error: Module version mismatch. Expected 48, got 49.

So the solution is to just use 2 package.json files instead I guess. https://github.com/electron-userland/electron-builder/issues/39#issuecomment-198504637

**Comment by develar** [comment]
@fabiantheblind If you have native modules — yes, you should use 2 package.json structure.

**Comment by fabiantheblind** [comment]
Last question:

For quick testing before restructuring my project with 2 package.json.

How to find out which node version electron uses so I can use nvm to make a test on my machine?

**Comment by develar** [comment]
> How to find out which node version electron uses so I can use nvm to make a test on my machine?

You don't need. Your unpacked electron app uses the same version of node as packed. So, just use electron-prebuilt or unpacked app.

**Comment by fabiantheblind** [comment]
hm. I'm using electron-prebuilt already. Anyway thanks a lot for the quick help. I will switch to 2 package.json files

**Comment by akashnimare** [comment]
@fabianmoronzirfas @develar did it work with single package.json?

**Comment by develar** [comment]
@akashnimare What do you mean?

**Comment by fabianmoronzirfas** [comment]
@akashnimare I work with 2 package.json anything else makes my head hurt

**Comment by akashnimare** [comment]
@fabianmoronzirfas haha. I have only one json file in my [app](github.com/zulip/zulip-electron). Could you tell me what changes I need to do to make it work (app structure wise etc) ?

**Comment by fabianmoronzirfas** [comment]
Check out this project. https://github.com/frntl/frontal Actually you only need to have a package.json  in the root of your project  and another in your app folder.  The one in the app Phone or Holz all of the dependencies.  The one in the root of your project hold your development dependencies.

**Comment by develar** [comment]
@akashnimare "to make it work" is not clear. Please file new issue and describe — doesn't build (error?) or doesn't run after build (error?). Sorry, but my free time is limited and it is not wise that investigate if no clear error description.

**Comment by akashnimare** [comment]
@develar Sorry if I was not clear. I'm currently trying as @fabianmoronzirfas suggested and will let you know if I have any issue. Thanks for the help.

**Comment by omenking** [comment]
Same problem. I thought maybe I could set:

```
    "directories" : {
      "app" : ".",
      "buildResources" : "static"
    },
```

Though getting error that results as such

```
Using node_modules/electron-webpack/electron-builder.yml configuration file
⚠️  Specified application directory "." equals to project dir — superfluous or wrong configuration
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.7.9 to dist/mac
Error: Application entry file "main.js" in the "/Users/andrew/Sites/swap-n-pop/dist/mac/swap-n-pop.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
```

I tried reading through the codebase to understand how electron-builder assembles the asar file and how it uses these build options but there was so much abstraction I couldn't tell what was going on.

The docs suggest you can do a single package.json build though no example

```
Since version 8 electron-builder rebuilds only production dependencies, so, you are not forced to use two package.json structure.
```

I used to have two package json structure though one of my devs changed it to one. I figured there was some way to configure to specific exactly what would get packed into the asar.

This was suggested to have a single package file as an example
https://github.com/nodejs/installer 
though it appears they are now using electron-forge

**Comment by develar** [comment]
@omenking What file is specified as `main` in your `package.json`?

**Comment by omenking** [comment]
if you mean what is set to `entry` its `main.js`
