### ISSUE TITLE
getFilePathIfBinarySync should not rely on filename and extname

### ISSUE THREAD

**Issue by AliasT** [electron-userland/electron-builder#6010]
https://github.com/electron-userland/electron-builder/blob/71d37044d348ab0cd8f0f9f7754bf6ebaa4b996c/packages/app-builder-lib/electron-osx-sign/util.js#L143-L162

I was trying to embed a python into an electron app. `getFilePathIfBinarySync` simply checked the files with blank extname, but files like `python/bin/python3.7` was ignored by the sign process. Also the `.so` and `.a` files.

These files should be included automatically.

**Comment by mmaietta** [comment]
Hi there!
Would you be willing to open a PR for adding `python`, `.so`, and `.a` files to `forceAllowedExts`? And also any other files ext you think are mandatory for signing?

For the interim, there's a `binaries` arg that accepts a list of paths of files you want to force-sign.
https://github.com/electron-userland/electron-builder/blob/71d37044d348ab0cd8f0f9f7754bf6ebaa4b996c/packages/app-builder-lib/electron-osx-sign/sign.js#L135-L141

**Comment by AliasT** [comment]
I think `isBinaryFile` should do most of the work.
```diff,js
- if ((ext === '' || ext.indexOf(' ') >= 0) && name[0] !== '.') { 
    return isBinaryFile(filePath) ? filePath : undefined 
- } 
```

**Comment by mmaietta** [comment]
Interesting, electron-osx-sign upstream has the code you suggest
https://github.com/electron/electron-osx-sign/blob/master/util.js#L157-L162

@develar was there a reason why we manually copied electron-osx-sign into the repo? Curious if we can return back to upstream

**Comment by AliasT** [comment]
https://github.com/electron-userland/electron-builder/issues/4656#issuecomment-590809499
