### ISSUE TITLE
Vulnerable dependencies (yargs)

### ISSUE THREAD

**Issue by zyrouge** [electron-userland/electron-builder#6011]
* **Version**: 22.11.7

![https://user-images.githubusercontent.com/50770114/123964041-afc0b880-d9d0-11eb-877e-652d46efac4f.png](https://user-images.githubusercontent.com/50770114/123964041-afc0b880-d9d0-11eb-877e-652d46efac4f.png)

**Comment by mmaietta** [comment]
Should be fixed in latest 22.11.8 - https://github.com/electron-userland/electron-builder/releases/tag/v22.11.8

This PR updated yargs to latest version: https://github.com/electron-userland/electron-builder/pull/6001/files
