### ISSUE TITLE
Mac build of multiple targets fails (ENOENT: no such file or directory, unlink)

### ISSUE THREAD

**Issue by zaneclaes** [electron-userland/electron-builder#6015]
* **Version**: 22.11.7

* **Electron Version**: v13.1.4
* **Electron Type (current, beta, nightly)**: Current

* **Target**: `Mac`

See: https://github.com/electron-userland/electron-builder/issues/4204 (which should have been fixed by @UzEE with https://github.com/electron-userland/electron-builder/pull/4269)

I would like to build to support both Apple Silicon (`arm64`) and Intel (`x64`) in order to support both common types of Mac machine. The following configuration fails deterministically:
```
mac:
  target:
    - target: pkg
      arch:
        - x64
        - arm64
```

With the following error:
```
zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop -c.extraMetadata.main=build/main.js -c.mac.identity=null
  • electron-builder  version=22.11.7 os=20.5.0
  • loaded configuration  file=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/WebApp/electron-builder.yml
  • loaded parent configuration  preset=react-cra
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=13.1.4 appOutDir=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/mac
  • default Electron icon is used  reason=application icon is not set
  • skipped macOS code signing  reason=identity explicitly is set to null
  • building        target=pkg arch=x64 file=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/Makerverse-1.2.0.pkg
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=13.1.4 appOutDir=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/mac-arm64
  • skipped macOS code signing  reason=identity explicitly is set to null
  • building        target=pkg arch=arm64 file=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/Makerverse-1.2.0-arm64.pkg
  ⨯ ENOENT: no such file or directory, unlink '/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/distribution.xml'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, unlink '/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop/distribution.xml'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERR] Error: Command failed: yarn run electron-builder --mac --publish=never -c.directories.output=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop -c.extraMetadata.main=build/main.js -c.mac.identity=null
error Command failed with exit code 1.
```

Removing the `arch` section entirely, or specifying a single arch causes the build to succeed. Note that other OSs do not exhibit this symptom (I am able to build for 4 linux architectures simultaneously).

FWIW, my command to invoke is:
`electron-builder --mac --publish=never -c.directories.output=/Users/zaneclaes/zdrive/zaneclaes/Programming/MakerHub/src/Makerverse/bin/Desktop -c.extraMetadata.main=build/main.js -c.mac.identity=null`

**Comment by zaneclaes** [comment]
This may be a race condition. My 2016 MacBook Pro exhibited symptoms, but a 2020 Mac Mini with a M1 chip was able to build both targets simultaneously without issue.

I'm closing this for now, unless it resurfaces on the Mac Mini (I don't think this would warrant maintainers' time).

**Comment by swapnilmishra** [comment]
I am also facing the same issue on my 2022 Macbook pro M1.

**Comment by nukeop** [comment]
I keep seeing this with pkg builds in Github Actions. Example: https://github.com/nukeop/nuclear/actions/runs/9830955589/job/27137726536

**Comment by oopses** [comment]
There will be an impact when building for multiple platforms, especially if electron requires different platforms, which will cause the packaged electron architecture to be inconsistent and make it unusable after actual installation
