### ISSUE TITLE
File not found in production build

### ISSUE THREAD

**Issue by BastienCivel** [electron-userland/electron-builder#6027]
* **Electron-Builder Version**:  22.10.5

* **Node Version**:  14.17.0

 

* **Electron Version**:13.1.1
* **Electron Type (current, beta, nightly)**:

* **Target**: production 

Hello everyone ! 
I'm kinda new to electron/electron_builder and I'm trying to build my react electron application via electron_builder. The process seems to work pretty well, until I launch the setup created in the dist folder. Upon execution, the application doesn't seem to be able to load images/icons (mostly .svg) located in my public/images (build/images once builded). Whereas the icons located in src/assets are well-loaded. 

I tried many configuration and read several topics, but I cannot make it work.
The interesting part on my package.json looks like this :
`  "homepage": "./",
  "build": {
    "files": [
      "build/**/*",
      "public/**/*"
    ],
    "directories": {
      "buildResources": "public"
    }
  },`

For example, inside a component, I try to load an image like this : 
`src={`/images/flags/${country}.svg`}`

The coutry variable is well defined, no worries. 

My process of building is the following : 

1. Use react-script-build (which creates a build folder)
2. Then run this script :  "electron-build-win": "electron-builder build --win --publish never --ia32" (which creates a dist folder).

Inside this dist folder, there is a setup and everything should be fine. I even checked the unpacked asar file and I find the images in here. 
The error I get : 
![image](https://user-images.githubusercontent.com/18723743/124451447-adba7900-dd85-11eb-81c7-3ebccae44699.png)

So obviously, the link seems wrong but how I set the good one ? 

So I don't really know what to do from now on...

Thanks in advance !

**Comment by Slapbox** [comment]
@BastienCivel the issue it a typo. You need to use `./` instead of `/` in `./images/flags/${country}.svg` The plain `/` means, relative to the root of the filesystem, in this case `C:/`

So I think this issue is safe to close, but let me know if that's not the issue.
