### ISSUE TITLE
Trouble including native module in built electron application on mac (arm64)

### ISSUE THREAD

**Issue by cbroad** [electron-userland/electron-builder#6028]
* **Electron-Builder Version**: 22.10.4

* **Node Version**: 14.15.1

* **Electron Version**: 11.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac/arm64

I have an electron project that has previously been built for both intel and m1 macs with not problem.  I've recently had to write some native code to hit some of Apple's APIs.  This native module has been working correctly when I run electron from the command line, but now I'm trying to build and distribute it.  I'm building this on an M1 mini and everything works fine when I build for arch: x64, but when I try to build with arch: arm64 I get errors with the message "no suitable image found."

I've noticed that for other native dependencies I've included in my project are listed with the message "rebuilding native dependencies" in the build output. My module, which is being sourced from a git repo, does not show up in that list for rebuild. What's required to get an N-API project build properly when I build my electron project? Is there some flag that would need to be present in the N-API project or in the electron project to let electron-builder know it's native and needs to be rebuilt?

Here's the output when my built program is run. The error on "/Users/.../binding/index.js:1:13" is where require is being run on my native module.

Uncaught Exception:
Error: dlopen(/var/folders/bq/9vw78mvd58ngylqxprkv7k5w0000gn/T/.com.fileshadow.desktop.QJfLzv, 1): no suitable image found. Did find:
/var/folders/bq/9vw78mvd58ngylqxprkv7k5w0000gn/T/.com.fileshadow.desktop.QJfLzv: mach-o, but wrong architecture
/var/folders/bq/9vw78mvd58ngylqxprkv7k5w0000gn/T/.com.fileshadow.desktop.QJfLzv: stat() failed with errno=17
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Users/carl/Documents/Development/FileShadow/fileshadow-desktop/dist/mac-arm64/FileShadow.app/Contents/Resources/app.asar/node_modules/fileshadow-darwin-native/binding/index.js:1:13)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)

**Comment by elmeet** [comment]
I also encountered such a problem.

**Comment by elmeet** [comment]
I have such a problem.

**Comment by cbroad** [comment]
I don't know if this will be the answer you're looking for.  In my case, I'd created a node-gyp module and then included it from the git repository into my project.  My problem was that the module was designed how I've been writing typescript modules, where the source and other files not used in the end-product of the module were  being deleted when the module was included in the project.  Specifically this was in my package.json under the `files` section: `"files": [ "binding/*", "build/Release/*.node", "lib/*", "types/*" ],`

What I wasn't understanding when I had the problem is that the module is rebuilt from the copy in your node_modules folder and not from the original source.  As such, I needed to have the built module keep all of the files necessary to rebuild the module in order for electron-builder to properly rebuild for both archs. (e.g. `"files":  [ "*" ],` )

My situation was just caused by my ignorance or lack of attention to detail.  I don't know if it helps, but good luck.

**Comment by elmeet** [comment]
Thank you very much. I don't know much English.
My application seems to be caused by sqlite3. But clone [electron-quick-start](https://github.com/electron/electron-quick-start)
And add `sqlite3` and execute `yarn electron-builder --arm64`, everything runs normally.
My application `node` and `electron` version and other related dependencies and packaging configuration are different,
I am narrowing the difference to reproduce this problem. Thanks again.

**Comment by elmeet** [comment]
I upgraded electron from v11.0.5 to v12 and later, everything works fine.
