### ISSUE TITLE
Application failing to install after uninstall on Windows 2016 server

### ISSUE THREAD

**Issue by WoojO** [electron-userland/electron-builder#6029]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.15.0

* **Electron Version**: 13.1.2
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows 10, Windows 2016, Windows 2019

We have issue with installer on Windows Server 2016 Standard 1607 (osbuild 14393.1884).
First time installer works fine. After uninstall and run installer again this error occurs.  If more details are needed, please let me know.

```
Faulting application name: XXXXX 1.1.335.exe, version: 1.1.335.0, time stamp: 0x5c157f86
Faulting module name: System.dll, version: 0.0.0.0, time stamp: 0x5c157efa
Exception code: 0xc0000005
Fault offset: 0x00001581
Faulting process id: 0xed0
Faulting application start time: 0x01d7725ce18a7dab
Faulting application path: C:\Users\XXXXX\Desktop\XXXXX 1.1.335.exe
Faulting module path: C:\Users\XXXXX\AppData\Local\Temp\nsh4B08.tmp\System.dll
Report Id: ed573e1d-3e93-41c1-bbef-4422f2a093ad
Faulting package full name:
Faulting package-relative application ID:

**Comment by mmaietta** [comment]
Hi there!
Was this working in a previous version of electron-builder?

**Comment by WoojO** [comment]
Hi!
Sorry for late response... It's working with version 22.11.6.
