### ISSUE TITLE
electron builder update emit error: {"code":"EBUSY","dest":"C:\\Users\\andyc\\AppData\\Local\\vipthink-updater\\pending\\vipthink_win_2.13.0.exe","errno":-4082,"path":"C:\\Users\\andyc\\AppData\\Local\\vipthink-updater\\pending\\temp-vipthink_win_2.13.0.exe","syscall":"rename"}

### ISSUE THREAD

**Issue by StitchC** [electron-userland/electron-builder#6031]
* **Electron-Builder Version**:  22.7.0

* **Node Version**: 12.22.0

* **Electron Version**: 4.2.12
* **Electron Type (current, beta, nightly)**: 

* **Target**: win32

and another error emit so:

{"code":"EPERM","dest":"C:\\Users\\David\\AppData\\Local\\vipthink-updater\\pending\\vipthink_win_2.13.0.exe","errno":-4048,"path":"C:\\Users\\David\\AppData\\Local\\vipthink-updater\\pending\\temp-vipthink_win_2.13.0.exe","syscall":"rename"}

should i upgrade my electron builder version to resovle this ? or how to avoid this problem?

**Comment by mmaietta** [comment]
You're running into a file lock issue so this may not explicitly be electron-builder: https://stackoverflow.com/a/44014485

Please update to latest 22.11.7 first though 🙂

**Comment by StitchC** [comment]
> You're running into a file lock issue so this may not explicitly be electron-builder: https://stackoverflow.com/a/44014485
> 
> Please update to latest 22.11.7 first though 🙂

sorry, i thought my word let you puzzle. i say clear now and let you know the detail

i use the autoUpdater of electron-builder to let our app update, and some of our user will emit the error, not  emit when npm install 😂

so, this error will be resolved in the latest version ? or how i can resolve this error, thanks~

**Comment by mmaietta** [comment]
>emit the error after downloaded the latest version app .zip and ready to install, not emit when npm install

Whoops, I definitely had misunderstood that. My bad 😅 

> so, this error will be resolved in the latest version ? or how i can resolve this error, thanks~

I just recall various electron-updater fixes occurring between 22.7 and 22.11, aaaand it's more efficient for the two maintainers of this project to only investigate on latest versions. 22.7.0 is also long before I joined the team.

**Comment by StitchC** [comment]
> > emit the error after downloaded the latest version app .zip and ready to install, not emit when npm install
> 
> Whoops, I definitely had misunderstood that. My bad 😅
> 
> > so, this error will be resolved in the latest version ? or how i can resolve this error, thanks~
> 
> I just recall various electron-updater fixes occurring between 22.7 and 22.11, aaaand it's more efficient for the two maintainers of this project to only investigate on latest versions. 22.7.0 is also long before I joined the team.

okay, i try to upgrade the electron-builder version

**Comment by theAV** [comment]
@StitchC  Did you get any solution? I am also getting the same, error no -4082, code "EBUSY" in windows 7.

**Comment by StitchC** [comment]
> @StitchC Did you get any solution? I am also getting the same, error no -4082, code "EBUSY" in windows 7.

no, but i ready to try upgrade the latest version

**Comment by theAV** [comment]
@StitchC My antivirus was blocking it. I stopped my antivirus and then auto-update worked as it should.
