### ISSUE TITLE
How to supply a name for appOutDir?

### ISSUE THREAD

**Issue by jceipek** [electron-userland/electron-builder#6038]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: v16.4.0

* **Electron Version**: 13.1.5
* **Electron Type (current, beta, nightly)**: current
* **Target**: Multiple targets

What is the easiest way to specify the `appOutDir` when packing using electron-builder?
I'm using `electron-builder --dir --config electron-builder.js [flags]` for building.
When `[flags]` is `--linux --x64`, I get `appOutDir=dist/linux-unpacked`.
When `[flags]` is `--linux --ia32`, I get `appOutDir=dist/linux-ia32-unpacked`.
When `[flags]` is `--mac`, I get `appOutDir=dist/mac`.
Instead of `appOutDir` containing an inconsistent combination of the platform, the architecture, and "unpacked", I would like to supply a custom `appOutDir`, ideally using the file macros documented here: https://www.electron.build/file-patterns#file-macros in order to get predictable output folders I can later use in my (non JS) build pipeline.
Is this possible? If so, how?

This is what my config looks like:
```js
// electron-builder.js
module.exports = {
  appId: 'com.mycompany.myappname',
  productName: 'MyProductName',
  mac: {
    category: 'public.app-category.productivity',
  },
  linux: {
    category: 'Utility',
  },
  directories: {
    buildResources: 'electron-build',
    output: 'dist',
  },
  files: ['./electron-build/**/*'],
};
```
I've unsuccessfully tried supplying `artifactName` and reading through all other CLI and config options with no luck.

**Comment by mmaietta** [comment]
Why do you consider it inconsistent? Seems pretty standardized:
`{platform}-{arch if not default}-unpacked` for Linux + Windows
Mac is always a `.app`, so there's no concept of an "unpacked" dir, the `.app` is considered the unpacked distributable.

And no, it's currently not possible to customize it. If you'd like to have direct access to that variable, then you should use electron-builder hooks, such as `afterPack` or `afterAllArtifactsBuild` in your case
https://www.electron.build/configuration/configuration#afterpackcontext
```
interface AfterPackContext {
  outDir: string
  appOutDir: string
  packager: PlatformPackager<any>
  electronPlatformName: string
  arch: Arch
  targets: Array<Target>
}
```

**Comment by jceipek** [comment]
@mmaietta  Thank you for confirming that there is no way to customize the output paths.

For reference, I consider the behavior inconsistent because the name has different per-platform and architecture rules rather than always being eg `{name}-{platform}-{arch}`. The presence or absence of `unpacked` and the notion that the arch is omitted if it happens to match a default value (which I imagined is the architecture of the current platform but actually appears to be x64 per https://github.com/electron-userland/electron-builder/blob/0447b2457beb03648f1e7e841cd0a8d12d7e4aea/packages/builder-util/src/arch.ts#L53) seem to me to be incidental implementation complexity that don't provide me any value as a user of the tool. On the contrary, the existence of any behavioral differences slightly increases the complexity of electron-builder and any downstream tools that need to account for them, which seems to me to be unnecessary.
