### ISSUE TITLE
Make sure compiled app has same hash on different computers.

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#604]
I notice in the node_modules directory (in app.asar), all package.json files have an "_args" array which contains as the second arguments a directory local to my system. 

This way it's not possible for me to build the app on multiple computers, and get the same md5 hash from the resulting app executable. (Because location is different (other username), on another computer, for example).

Being able to verify the build on different computers is however very important. Can something be done about this?

**Comment by develar** [comment]
It is an npm stuff. Well... I guess it is safe to get rid of these fields in the `package.json` on copy.  But please don't expect that it will be fixed by me soon. Please send PR.

**Comment by atypicalprogrammer** [comment]
Yes, should not be fixed by you but by NPM. I have already posted about it on their issue list (an issue already existed, it seems). For now, I'm using https://github.com/juanjoDiaz/removeNPMAbsolutePaths to remove it before distribution.

**Comment by develar** [comment]
It is not easy to implement for ASAR. But makes sense. So, not moved to backlog.

**Comment by develar** [comment]
For ASAR fixed only.
