### ISSUE TITLE
Old version not deleted?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#607]
I've had some reports from users, can you tell me what the problem is? Did the install location change in one of the newer versions and did the old directory not get deleted? Why is the desktop shortcut icon not updated? (Windows)

> Now I see the problem. The update with the .exe dosn't work properly.
> When I install the new .exe it works and opens the new 1.0.1 Version. As soon as I close it and open again with the shortcut on the desctop, it opens the old version.
> 
> [8:34]  
> Seems the new  .exe installer installs it some where else and dosn't update the desktop shortcut.
>

**Comment by develar** [comment]
Shortcut points to the same `Update.exe`. Maybe user manually created shortcut? Do you create shortcuts on `--squirrel-updated` (https://github.com/mongodb-js/electron-squirrel-startup/blob/master/index.js#L20)?

**Comment by atypicalprogrammer** [comment]
Sorry this is not squirrel windows, it's about NSIS. Forgot to include it in my original question.

**Comment by develar** [comment]
So the picture is completely different :) Hmm...

**Comment by atypicalprogrammer** [comment]
I did read in another issue of yours that there was a bug with NSIS that installed in program files instead of appdata. This was the case for this user too. Old version was not removed upon installation in correct appdata directory.

**Comment by develar** [comment]
Duplicates #564
