### ISSUE TITLE
"No files provided" error when trying to download an update

### ISSUE THREAD

**Issue by praneetrohida** [electron-userland/electron-builder#6075]
* **Electron-Builder Version**: 22.11.9

* **Node Version**: 14.7.3

* **Electron Version**: 13.1.7
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: 4.4.1

I recently upgraded to the latest electron-builder and electron-updater (versions above).
This broke the updates on MacOS x64 machines. I get the following error when downloading an update.
This worked fine before and seems to only affect MacOS x64 machines. I tested the updates on MacOS arm64 and they work fine. 

![CleanShot 2021-07-21 at 19 21 31](https://user-images.githubusercontent.com/23721710/126500798-e5664146-3549-4496-b4f8-5fa4ce9b3e96.png)

Contents of latest-mac.yml 
![CleanShot 2021-07-21 at 19 27 07](https://user-images.githubusercontent.com/23721710/126500896-0b6bc600-89cf-47c9-a8ca-1aa606a49204.png)

Update: Also tested on Windows, seems to work fine. So only mac x64 is affected

**Comment by mmaietta** [comment]
The error message being logged is expected on x64
https://github.com/electron-userland/electron-builder/blob/71d37044d348ab0cd8f0f9f7754bf6ebaa4b996c/packages/electron-updater/src/MacUpdater.ts#L33-L41

But it looks like `sysctl` is being executed twice

Can you confirm whether the file downloaded or not? I'm curious if there's an exception being thrown, and it'd help to know if it's the download or the process of installing it
https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/electron-updater/src/providers/Provider.ts#L82-L85

**Comment by praneetrohida** [comment]
@mmaietta the file is not downloaded. I also checked the logs on my updates server, the `latest-mac.yml` is served to the client, and the request for the `.zip` file is never made. I made sure that the updater cache was empty. 
The exception is indeed thrown from the `findFile` function in `Provider.js`
