### ISSUE TITLE
[Feature request] Downgrade Wixtoolset to v3 (3.14)

### ISSUE THREAD

**Issue by GeekCornerGH** [electron-userland/electron-builder#6077]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14

* **Electron Version**: 13.1.7
* **Electron Type (current, beta, nightly)**:

* **Target**: 
Windows

I wanted to build my Electron app for arm64, with msi format, but the version you are using doesn't support arm64. Wix toolset v3.14 supports arm64. Can you change it? Thank you

**Comment by mmaietta** [comment]
It looks like it pulls the toolset from https://github.com/electron-userland/electron-builder-binaries/tree/master/wix
So you'll need to move this request to that repo and/or contribute to that upstream project first.

**Comment by GeekCornerGH** [comment]
Done :)

**Comment by mrksr** [comment]
@mmaietta Hi! I've found this problem as well and also added a new reference in @GeekCornerGH's issue in the other repo. There has not been any activity there however. I'm quite new to the Electron ecosystem so I'm not sure how things work. Do you have an idea how the issue could be resolved? As I see it, this issue blocks _all_ Electron msi-builds for Windows on Arm, so it's not negligible. I'm happy to help things along, but I'm not sure who to get in contact with. Thanks!
