### ISSUE TITLE
Command failed: codesign --sign 

### ISSUE THREAD

**Issue by daovansonbg** [electron-userland/electron-builder#6081]
* **Electron-Builder Version**: 
     22.11.7

* **Node Version**: 
v14.17.0

* **Electron Version**:
13.1.7

* **Electron Type (current, beta, nightly)**:

* **Target**: 
Mac

![Screen Shot 2021-07-23 at 11 35 09](https://user-images.githubusercontent.com/11437473/126737980-85682aee-f6f8-4c0c-82eb-c337a0d1717f.png)

**Comment by mmaietta** [comment]
That is specifically an env configuration issue, not related to electron-builder. You're probably missing a intermediate cert

https://www.google.com/search?q=unable+to+build+chain+to+self-signed+root+for+signer+apple+distribution

Warning: unable to build chain to self-signed root for signer  https://developer.apple.com/forums/thread/86161?answerId=676773022#676773022
