### ISSUE TITLE
Cannot build both x64 and arm64 PKGs when not signing

### ISSUE THREAD

**Issue by larrywalters** [electron-userland/electron-builder#6083]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.17.0

* **Electron Version**: 13.1.7

* **Target**: macOS PKG

We encountered this issue in our app build process, but then confirmed the problem just using the _electron-webpack-quick-start_ project. If you try to build more than one architecture for macOS, both with a target of PKG, the build will fail with one of these errors. Some parts of the paths have been redacted for privacy reasons.
```
  • async task error  error=ENOENT: no such file or directory, unlink '/Users/.../electron-webpack-quick-start/dist/com.pkg.test.pkg'
  ⨯ ENOENT: no such file or directory, unlink '/Users/.../electron-webpack-quick-start/dist/com.pkg.test.pkg'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, unlink '/Users/.../electron-webpack-quick-start/dist/com.pkg.test.pkg'
error Command failed with exit code 1.
OR
  ⨯ ENOENT: no such file or directory, unlink '/Users/.../electron-webpack-quick-start/dist/distribution.xml'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, unlink '/Users/.../electron-webpack-quick-start/dist/distribution.xml'
error Command failed with exit code 1.
```
Here are the details:
- The pkg artifacts are created, but there appears to be a problem cleaning up. I suspect it is because of some timing contention between the commands to build both artifacts, which includes removing intermediate files. This would mean the command for one will remove the file and then the other tries to, and cannot find it, so it fails.
- If the app signing process is incorporated, then the timing is different and the failure does not happen.
- This only happens if both targets are PKG; I tried the other supported architectures for macOS and the problem doesn't happen.

A fix is prudent here because:
- We should be able to generate the same kind of target for both x64 and arm64. Especially now that Apple Silicon usage is increasing.
- Developers should not need to have signing credentials stored locally for security reasons, and yet should still be able to run the build without error.
- None of the other architectures manifest this problem, and PKG is not an uncommon deliverable.

Here is the `package.json` I used. If you use this with the [electron-webpage-quick-start](https://github.com/electron-userland/electron-webpack-quick-start) project, and simply do `yarn` and then `yarn dist`, you should see the error.
```
{
  "name": "electron-webpack-quick-start",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "compile": "electron-webpack",
    "dist-sign": "yarn compile && electron-builder",
    "dist": "yarn compile && electron-builder -c.mac.identity=null",
    "clean-dist": "rm -rf dist"
  },
  "build": {
    "appId": "com.pkg.test",
    "artifactName": "PkgTest-${version}-${os}-${arch}.${ext}",
    "mac": {
      "target": [
        {
          "target": "pkg",
          "arch": "x64"
        },
        {
          "target": "pkg",
          "arch": "arm64"
        }
      ],
      "hardenedRuntime": true,
      "gatekeeperAssess": true,
      "category": "public.app-category.business"
    }
  },
  "dependencies": {
    "source-map-support": "^0.5.16"
  },
  "devDependencies": {
    "electron": "^13.1.4",
    "electron-builder": "^22.11.7",
    "electron-webpack": "^2.8.2",
    "webpack": "~4.42.1"
  }
}
```
Thank you!

**Comment by larrywalters** [comment]
@mmaietta Thank you for the response and suggestion! That's an interesting idea, and after that change it does indeed pass with the sample `package.json` I provided! And that's regardless of signing or not.

While this type of package is a good option to consider, the downside is that universal builds are twice as big. And while it may solve the behavior stated here, there's still an underlying issue that is just worked around. I understand it's less important if there is a good alternative, but universal builds do not work for everyone. Specifically for us, the reduced file size is important.

Therefore, I think using a `universal` pkg is worthy of consideration in general, but I wouldn't consider it a resolution to the core issue in this ticket.

Note that I did not see the `universal` option indicated in the list of architectures [here](https://www.electron.build/configuration/mac).

**Comment by larrywalters** [comment]
This issue is still relevant, per my most recent comments. I still get the error when building the sample project. Thank you.

**Comment by oopses** [comment]
https://github.com/electron-userland/electron-builder/blob/8cbf079ec20bbc642f9b6c306e3e9141a1fcc385/packages/app-builder-lib/src/targets/pkg.ts#L87
The problem should be caused by trying to delete the same file when building multiple architectures.
