### ISSUE TITLE
Electron Builder isn't evaluating environment variables in `electron-builder.yml`

### ISSUE THREAD

**Issue by kitsune7** [electron-userland/electron-builder#6084]
* **Electron-Builder Version**: 22.11.7
* **Node Version**: 16.4.2
* **Electron Version**: 13.1.6
* **Electron Type (current, beta, nightly)**: current
* **Target**: mac, dmg

I'm working on code signing an application and I can't seem to get environment variables to work properly in `electron-builder.yml`. In `electron-builder.env`, I added a variable for `CSC_NAME` and set it to the hash of the certificate name (the one that gets listed right before the certificate name listed in quotes when running `security find-identity -v` in terminal), but the code signing fails with the following error:

```
skipped macOS application code signing  reason=Identity name is specified, but no valid identity with this name in the keychain identity=${CSC_NAME}
```

When I put the value assigned to `CSC_NAME` directly into the `identity` field, it works perfectly, but I don't want to have to expose that information in my repository.

I've tried using different variable names like `IDENTITY` and setting the environment variables on the command-line (e.g. `CSC_NAME=LOTS_OF_LETTERS_AND_NUMBERS electron-builder build --mac`), but I keep getting the same result. I'm pretty sure electron builder recognizes the values in `electron-builder.env` because if I set a value like `CSC_LINK` to a non-existent or non-certificate file, there will be a different error letting me know my mistake, but I don't understand why putting the identity directly works and the environment variables don't.

**Comment by mmaietta** [comment]
electron-builder.yml was never intended to support env vars.

For the interim, I'd recommend switching to an `electron-builder.js` so that you can leverage `process.env.____`

You mentioned you don't want to store that information in the repo. Where is your cert located then? Locally on the CI machine?

**Comment by kitsune7** [comment]
Okay. That's interesting. I know the [documentation](https://www.electron.build/configuration/configuration#environment-variables-from-file) does talk about using environment variables in configurations, but I don't think it specifies that the environment variables only work for configurations within a specific context. I'm pretty sure that YAML files can use environment variables, but maybe that only works in CI/CD workflows or situations where they're explicitly provided. 🤷🏻 

I'll switch it over to a JavaScript file. Thank you for helping me out with this. I was very confused. 😅 

I have the cert stored in my repository locally. It's just not stored in the remote repository because I listed the file type for it in `.gitignore`. I haven't put together a CI workflow for it yet, but I was planning on putting the contents of the certificate into an environment secret on Github when it came time for that.

**Comment by mmaietta** [comment]
Yeah, YAML supports env vars, but I think it requires a custom parser that we'd need to implement in electron-builder.
Happy to review any PRs if you're willing to take a dive. A local dev env is fairly simple to set up: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

A Github env secret would definitely be the best route for the cert. electron-builder will pick that up just fine.

**Comment by kitsune7** [comment]
Got it! That makes sense. I'll take a look at that. I think environment variable support would be really helpful to add.

**Comment by mmaietta** [comment]
I agree! But I don't have time to add that as a feature 😅 
Happy to review PRs 😉
