### ISSUE TITLE
Enhancement: macOS traditional installation process

### ISSUE THREAD

**Issue by amilajack** [electron-userland/electron-builder#609]
Many apps on macOS are installed with a 'install menu' like so:

![macOS install menu](http://theappledaily.com/wp-content/uploads/2011/11/install-mac-os-x-in-vmware.jpg)

Is it possible to provide something like this with electron-builder?

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-builder/issues/52#issuecomment-233113059 please see my linked comment. Comment if you have objections.
