### ISSUE TITLE
Cannot find module 'electron-publisher-custom', because the package name is already in use in npm

### ISSUE THREAD

**Issue by ArcherTrister** [electron-userland/electron-builder#6098]
* **Electron-Builder Version**: 
22.11.8

* **Node Version**: 
15.3.0

* **Electron Version**: 13.1.6
* **Electron Type (current, beta, nightly)**:

beta

* **Target**: 
win32

I am trying to use custom provider, the publish fails with the following warning:

```
  ⨯ Cannot find module 'electron-publisher-custom'
Require stack:
- D:\Code\ElectronDemo\node_modules\app-builder-lib\out\publish\PublishManager.js
- D:\Code\ElectronDemo\node_modules\app-builder-lib\out\index.js
- D:\Code\ElectronDemo\node_modules\electron-builder\out\builder.js
- D:\Code\ElectronDemo\node_modules\electron-builder\out\cli\cli.js
- D:\Code\ElectronDemo\node_modules\electron-builder\cli.js  failedTask=build stackTrace=Error: Cannot find module 'electron-publisher-custom' 
```

i think we should use providerName instead of name when constructing a new instance of a custom publisher,because the package name is already in use in npm,I don't have permission to publish.

like this:
```
function requireProviderClass(provider: string, packager: Packager, customProviderName?:string): any | null {
  switch (provider) {
    case "github":
      return GitHubPublisher
    case "bintray":
      return BintrayPublisher
    case "generic":
      return null
    case "s3":
      return S3Publisher
    case "snapStore":
      return SnapStorePublisher
    case "spaces":
      return SpacesPublisher
    default: {
      const name = `electron-publisher-${customProviderName}`
      let module: any = null
      try {
        module = require(path.join(packager.buildResourcesDir, name + ".js"))
      } catch (ignored) {
        console.log(ignored)
      }
      if (module == null) {
        module = require(name)
      }
      return module.default || module
    }
  }
}
```

or

```
function requireProviderClass(providerNmae: string, packager: Packager): any | null {
  switch (providerNmae) {
    case "GitHub":
      return GitHubPublisher
    ...
    default: {
      const name = `electron-publisher-${providerNmae}`
      let module: any = null
      try {
        module = require(path.join(packager.buildResourcesDir, name + ".js"))
      } catch (ignored) {
        console.log(ignored)
      }
      if (module == null) {
        module = require(name)
      }
      return module.default || module
    }
  }
}
```

**Comment by mmaietta** [comment]
Where have you defined your custom provider with name `custom`?
It seems it's not finding the expected custom publisher file here: `require(path.join(packager.buildResourcesDir, name + ".js"))`, which is why it's trying to execute `require(name)`

Do you have a file in your build resources directory named `electron-publisher-custom.js`?

**Comment by ArcherTrister** [comment]
If we use providerName instead of name，we can publish a custom package to npm, just use it this way, and we don't need to store electron-publisher-custom.js files under folder resources.

eg:

> npm i electron-publisher-xxx -save

```yml
publish:
  - provider: custom
    providerName: xxx
```

**Comment by wsw0108** [comment]
Agree with @ArcherTrister

**Comment by mmaietta** [comment]
Please feel free to submit a PR with the new setup. We're currently in a v23-alpha state, so breaking changes are allowed.
Setting up a local dev env is fairly simple too :)
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
