### ISSUE TITLE
Wrong filename generated in latest.yml on windows

### ISSUE THREAD

**Issue by hanabi1224** [electron-userland/electron-builder#6099]
* **Electron-Builder Version**:  22.11.7

* **Node Version**: v14.17.0

* **Electron Version**: v13.1.7
* **Electron Type (current, beta, nightly)**: current

*electron-updater*: 4.3.9

* **Target**:  windows, nsis

The generated setup files have space in file name, while the space is replace with '-' in latest.yml, however, when manually uploading to github release, the space is replaced by '.' which is inconsistent with latest.yaml, thus auto-updater won't work.

![image](https://user-images.githubusercontent.com/6546635/126962985-481fa4fd-2ee4-4391-aa45-853695d26723.png)
![image](https://user-images.githubusercontent.com/6546635/126963028-f6af611b-3195-4eca-a5cf-8c400ce7f9a4.png)
![image](https://user-images.githubusercontent.com/6546635/126963053-d87fb453-9a10-414f-939d-aed2e28bf17f.png)

**Comment by mmaietta** [comment]
Do you know if this was a recent regression?

**Comment by hanabi1224** [comment]
@mmaietta Yeah, I did manual uploads before using electron-builder built-in uploader, I think those are separate issues, it should allow ppl doing manual uploads, does that make sense?

**Comment by mmaietta** [comment]
Why not just configure electron-builder to name the artifacts such that you align it with Github?
```
win: {
   artifactName: '${productName}.Setup.${version}.${ext}'`
}
```

**Comment by hanabi1224** [comment]
> Why not just configure electron-builder to name the artifacts 

@mmaietta  Thanks for the hint and it does fix the problem! But at the same time, I think it's still an issue that electron builder produces inconsistent file names in build artifact with default options, does that make sense?

**Comment by mmaietta** [comment]
I disagree, it doesn't need to be consistent with specifically how Github handles uploads. There are multiple publishers supported and other storage hosts for a "generic" or "custom" publisher, I see no reason to change the current behavior.

**Comment by hanabi1224** [comment]
But why generate file names with space in it? It's undefined behaviour how various local or remote filesystem handle spaces in path so it's error prone. It can be fixed by just simply replacing spaces with commonly accepted chars like dot
