### ISSUE TITLE
Problems installing latest version

### ISSUE THREAD

**Issue by JulianHH** [electron-userland/electron-builder#610]
Hi there!

When trying to install the latest version I get the following error:

```
$ npm i electron-builder
npm WARN package.json slack-monitor@0.0.1 No repository field.
npm WARN package.json slack-monitor@0.0.1 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "electron-builder"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code E403

npm ERR! unregistered users are not allowed to access package @develar/asar : @develar/asar
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     .../npm-debug.log
```

I guess some configuration errors happening here?

**Comment by develar** [comment]
Do you use custom npm registry?

**Comment by JulianHH** [comment]
Yeah, but it goes straight through to npmjs when the package hasn't been found.

And it's the first time I have this issues. It did not appear a couple of weeks ago.

**Comment by develar** [comment]
It is your npm registry implementation issue. But I understand — will be fixed on electron-builder side.

**Comment by JulianHH** [comment]
So it's a sinopia issue? I should possible raise an issue there, too, shouldn't I?

But thanks anyway! 👍

**Comment by develar** [comment]
Yes, it is known bug — https://github.com/rlidwka/sinopia/issues/337#issuecomment-155054127

**Comment by JulianHH** [comment]
Allright. Thanks for clearing up! And for fixing on electron-builder side in advance!

**Comment by JulianHH** [comment]
Thanks :)
