### ISSUE TITLE
code object is not signed at all

### ISSUE THREAD

**Issue by GreedyWhale** [electron-userland/electron-builder#6101]
- Electron-Builder Version: 22.11.7
- Node Version: 14.17.0
- Electron Version: 11.1.0
- Target: mas

I have an app that needs to be on the App Store and when I finish building it (no errors reported) to deliver it to the App Store I have a problem with unsigned code and I use the `codesign -dvvv` command to get the following result.

<img width="622" alt="WX20210726-175418@2x" src="https://user-images.githubusercontent.com/22760464/126970887-b90ec27e-d198-4bf0-b056-c0a5e452d0d9.png">

A quick check revealed that it was my provisionprofile file that was missing a certificate of type `3rd Party Mac Developer Application`.

I did this by changing line 371 of `node_modules/app-builder-lib/out/macPackager.js` to `return isMas ? ["Apple Distribution"] : ["Developer ID Application"];` solved the problem and successfully delivered to the App Store

<img width="977" alt="WX20210726-180032@2x" src="https://user-images.githubusercontent.com/22760464/126971041-338107f7-2e6f-4505-9696-cdfbb5a666ba.png">

I would like to ask why I need a certificate of type `3rd Party Mac Developer Application`, thanks

**Comment by quanglam2807** [comment]
`3rd Party Mac Developer Application` is Apple's name for Mac-only Mac App Store distribution certificate, so I don't think we should remove it in #6105. Any thought?
