### ISSUE TITLE
Question: Possible to change certificate?

### ISSUE THREAD

**Issue by buelsenfrucht** [electron-userland/electron-builder#6102]
Hi guys,

I have a question concerning Windows certificates:

I had a certificate from GoDaddy to sign my code and to use autoUpdate.
Now they aren't selling code certificates anymore and I can't renew it neither, so I had to switch certificate.

After I did that, autoUpdate isn't working any more, so I assume it isn't working anymore because of the changed certificate?

I used the new certificate for another app too, and autoUpdate is working there, so it is working in general.

Thanks for your answers,
Jascha

**Comment by mmaietta** [comment]
Maybe you need to hardcode the GUID/`appId` now that you're changing certs? Here's a snapshot of a config I use:
```
    win: {
        target: 'nsis',
        verifyUpdateCodeSignature: true,
        signDlls: true,
        rfc3161TimeStampServer: "http://timestamp.digicert.com",
        appId: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    },
```

**Comment by mmaietta** [comment]
What version of electron-updater are you on? Curious if you're running into this issue as well
https://github.com/electron-userland/electron-builder/issues/6099

**Comment by buelsenfrucht** [comment]
Sorry for the late answer, did not get an e-mail notification.

I already hardcoded the appId (I am using `vue-cli-plugin-electron-builder`).

```
builderOptions: {
        appId: process.env.APP_ID,
        productName: process.env.VUE_APP_TITLE,
        afterSign: "electron-builder-notarize",
        mac: {
          icon: "public/icons/icon.icns",
          target: ["dmg", "zip"],
          hardenedRuntime: true,
          entitlements:
            "./node_modules/electron-builder-notarize/entitlements.mac.inherit.plist"
        },
        win: {
          icon: "public/icons/icon.ico",
          target: ["nsis", "zip"]
        },
      }
```

The strange thing is, while macOS-Build is adopting the App Title as configured via process.env.VUE_APP_TITLE, Windows Build isn't.


I'm on 22.9.1. The update did work before I switched certificate though.
