### ISSUE TITLE
Trying to find an installer log file

### ISSUE THREAD

**Issue by gunnarSensus** [electron-userland/electron-builder#6115]
* **Electron-Builder Version**: 20.19.2 

* **Node Version**: 10.21.4

* **Electron Version**: 4.2.12
* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis

A customer of my companies is having an issue installing our app where the installer hangs at around 40%, i have googled around for a while trying to find a log file for the installer so i can try and debug the issue but havent found anything. Is there an installer log file by default or do i need to explicitly set an option to generate one. Any help finding an installer log file would be greatly appreciated, thank you!

**Comment by mmaietta** [comment]
Hi @gunnarSensus !
I've built out a solution that will allow enabling nsis logging but I need some guinea pigs to try it out. Would you be willing to try this patch file? https://github.com/electron-userland/electron-builder/issues/5119#issuecomment-889608933
It contains everything needed so you can add
```
nsis: {
   debugLogging: true
}
```

**Comment by gunnarSensus** [comment]
Thanks for the quick reply mmaietta, but luckily the customers issue with installing was resolved by cleanly uninstalling via windows "add or remove program" and then re-running the installer so the urgency for this has been greatly diminished. if i can find some time i will try to play with your patch but im not certain i will be able to. really appreciate the speedy reply/help though!
