### ISSUE TITLE
Binaries failed to append signature file

### ISSUE THREAD

**Issue by whxleemdddd** [electron-userland/electron-builder#6125]
* **Electron-Builder Version**: 22.11.11

* **Node Version**: 

* **Electron Version**:7.2.4
* **Electron Type (current, beta, nightly)**:

* **Target**: mas

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libEGL.dylib' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/X-Note Helper (GPU).app/Contents/MacOS/X-Note Helper (GPU)' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/X-Note Helper (Plugin).app/Contents/MacOS/X-Note Helper (Plugin)' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/X-Note Helper (Renderer).app/Contents/MacOS/X-Note Helper (Renderer)' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Frameworks/X-Note Helper.app/Contents/MacOS/X-Note Helper' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Library/LoginItems/X-Note Login Helper.app/Contents/MacOS/X-Note Login Helper' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/MacOS/X-Note' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/@replace5/app-builder-bin/mac/app-builder' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/images/vendor/darwin-x64-binding.node' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/nodejieba/build/Release/nodejieba.node' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/sqlite3/build/Release/node_sqlite3.node' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/sqlite3/lib/binding/electron-v7.2-darwin-x64/node_sqlite3.node' must be signed with the certificate that is contained in the provisioning profile."

ERROR ITMS-90284: "Invalid Code Signing. The executable 'com.duita.X-Note.pkg/Payload/X-Note.app/Contents/Resources/app/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node' must be signed with the certificate that is contained in the provisioning profile."

To do this, I added

"binaries": [

"Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework",

"Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib",

"Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib",

"Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib",

"Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_ libEGL.dylib",

"Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_ libGLESv2.dylib",

"Contents/Frameworks/X-Note Helper (GPU).app/Contents/MacOS/X-Note Helper (GPU)",

"Contents/Frameworks/X-Note Helper (Plugin).app/Contents/MacOS/X-Note Helper (Plugin)",

"Contents/Frameworks/X-Note Helper (Renderer).app/Contents/MacOS/X-Note Helper (Renderer)",

"Contents/Frameworks/X-Note Helper.app/Contents/MacOS/X-Note Helper",

"Contents/Library/LoginItems/X-Note Login Helper.app/Contents/MacOS/X-Note Login Helper",

"Contents/MacOS/X-Note",

"Contents/Resources/app/node_ modules/@replace5/app-builder-bin/mac/app-builder",

"Contents/Resources/app/node_ modules/images/vendor/darwin-x64-binding.node",

"Contents/Resources/app/node_ modules/nodejieba/build/Release/nodejieba.node",

"Contents/Resources/app/node_ modules/sqlite3/build/Release/node_ sqlite3.node",

"Contents/Resources/app/node_ modules/sqlite3/lib/binding/electron-v7.2-darwin-x64/node_ sqlite3.node",

"Contents/Resources/app/node_ modules/sqlite3/lib/binding/node-v83-darwin-x64/node_ sqlite3.node"

],

But the build fails, always in "contents / resources / APP / node"_ modules/sqlite3/lib/binding/electron-v7.2-darwin-x64/node_ SQLite3. Node ", there is no such file or directory

**Comment by ramonhoyo** [comment]
Hi, Is there any solution to this? I'm facing the same problem

**Comment by enunmuz** [comment]
@whxleemdddd I am facing the same issue of `ERROR ITMS-90284: "Invalid Code Signing."` Can you please let me know how you got to fix it?
