### ISSUE TITLE
MacOS raises exception "The command is disabled and cannot be executed" in MacUpdater.quitAndInstall

### ISSUE THREAD

**Issue by seb-mtl** [electron-userland/electron-builder#6129]
- **Electron-Builder Version**:  22.10.4

- **Node Version**: 12.16.1

- **Electron Version**: 8.5.5

- **Target**: MacOS

A user recently shared a bug report with the following error message during the update process:

```
Error: The command is disabled and cannot be executed
    at MacUpdater.quitAndInstall (/Applications/Snowtrack.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:135:32)
    at IpcMainImpl.<anonymous> (/Applications/Snowtrack.app/Contents/Resources/app.asar/main.js:434:17)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
    at WebContents.emit (events.js:210:5) {
```

The app update file itself is downloaded successfully and the click on the "Restart app" button triggers the function below and eventually the error message:

```
ipcMain.on('restart_app', () => {
  autoUpdater.quitAndInstall();
});
```

I have seen this error being reported twice, [here](https://github.com/electron-userland/electron-builder/issues/5935) and [here](https://github.com/electron-userland/electron-builder/issues/5717), one of them being closed with a fix. In both reports there were several different workarounds, so I am reporting this here again since it should work without one.

**Comment by mmaietta** [comment]
Please update electron-builder, it's old. Also related, please confirm you've updated electron-updater to the latest version, that removed the double update+quit execution. If it's still occurring for you, then you're likely doing the equivalent of running quit twice on one app instance.

**Comment by hisnameisjimmy** [comment]
After having updated electron-builder to 22.11.11, I thought I'd handled this:

![CleanShot 2021-09-12 at 13 03 45@2x](https://user-images.githubusercontent.com/740373/133001588-1f19dccd-273b-40ed-87fb-d6e41668cf5e.png)

However, seeing this comment and still seeing the bug crop up, I'm now realizing I need to update both independently. 

I'm currently on electron-updater version 4.3.8, but it appears that in the 22.11.11 release notes that I should be on 4.4.3:

![CleanShot 2021-09-12 at 13 39 31@2x](https://user-images.githubusercontent.com/740373/133002145-92614ed9-e90f-4380-b4fc-dac40fefe15f.png)

Is that the right way to interpret this?

**Comment by mmaietta** [comment]
Yes
