### ISSUE TITLE
Unknown option 'cache-min' when running electron-builder with pnpm

### ISSUE THREAD

**Issue by mhatvan** [electron-userland/electron-builder#6130]
* **Electron-Builder Version**: 22.11.11

* **Node Version**: 14.17.2 (also occurs with v16)

* **Electron Version**: 13.1.8
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux x64

I am in the process of switching over a project from npm 6 to pnpm. There are no config changes, so I am wondering where this error is coming from.

## Screenshot

![Screenshot from 2021-08-08 17-23-23](https://user-images.githubusercontent.com/16797721/128637201-853f22e0-c88a-4061-a046-5b764226c54e.png)

**Comment by mmaietta** [comment]
So that error is probably coming from here:
https://github.com/electron-userland/electron-builder/blob/ae363e51957d0abfc7d848f51aa23c7e5faf5f33/packages/app-builder-lib/src/util/yarn.ts#L102-L104

Seems like we need a way to discern if running `npm`, instead of determining on whether it is `yarn`?

**Comment by mhatvan** [comment]
Ah, glad that you found the location of the issue. It might even be the case that npm, yarn and pnpm need to be handled differently, but unfamiliar with the code base.

**Comment by mmaietta** [comment]
Just need a way to discern npm from pnpm. The code part will be easy after that, just need to create `isRunningNPM`

**Comment by mhatvan** [comment]
I guess you could check for the existence of node_modules/.pnpm, related article: https://pnpm.io/symlinked-node-modules-structure

**Comment by mmaietta** [comment]
Would you be willing to contribute? Setting up a dev env is fairly simple :)
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by mhatvan** [comment]
If you give me proper instructions on what to do, okay.

Why is the cache-min line there in the first place? 
Should we conditionally check for not yarn and not pnpm or rather just check for npm?

**Comment by mhatvan** [comment]
I think I found an easy way to fix this:

According to https://docs.npmjs.com/cli/v7/using-npm/config#cache-min, the `--cache-min` option is deprecated anyways and it is recommend to use `--prefer-offline` instead.

pnpm doesn't support `--cache-min`, but both npm and pnpm support the usage of `--prefer-offline`.
