### ISSUE TITLE
Too big raw data in the console

### ISSUE THREAD

**Issue by NikolayMakhonin** [electron-userland/electron-builder#6131]
See please this line:

https://github.com/electron-userland/electron-builder/blob/39ac82f89a1a95b924bf1b9651ce143dd219687d/packages/electron-updater/src/NsisUpdater.ts#L157

The `data` is very big binary file (> 15 MB). Shrink please the `data` in error message to 1 KB

**Comment by mmaietta** [comment]
Just curious, is there a reason why we even need to log the raw data?
