### ISSUE TITLE
Bug: default imports for built-in node modules in electron-updater

### ISSUE THREAD

**Issue by Thomb89** [electron-userland/electron-builder#6134]
* **Electron-Builder Version**: 22.11.11

* **Node Version**: 16.6.1

* **Electron Version**: 13.1.8
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

There is a bug in the electron-updater package in the file [BaseUpdater.ts](https://github.com/electron-userland/electron-builder/blob/1580ea691c4b82ea80c6420d806bc4bfaef5fd38/packages/electron-updater/src/BaseUpdater.ts).

It was introduced recently with this commit: https://github.com/electron-userland/electron-builder/commit/45fc0a003abc58969bb3a5d6ab1e3b61a9ad1a8d.

The NodeJS Modules **fs** and **path** have no default imports 

```
import fs from "fs"
import path from "path"
```

should be 

```
import * as fs from "fs"
import * as path from "path"
```

or

```
import { writeFileSync, rmSync } from "fs"
import { join, dirname } from "path"
```

Because of this, it will always throw an error and set `installPathRequiresElevation = true`.
This is not needed, when installing in the %appdata% directory of the user.
For users without Admin-Rights, this will even install the update for the wrong user.

I think this slipped through because of the typescript compiler option "allowSyntheticDefaultImports".
With this flag 
```
import path from "path"

path.join(...)
```
compiles to
```
const path = require('path')

path.default.join(...)
````

**Comment by burnhamup** [comment]
I just noticed this too, trying to test the fix for the silent updater. I submitted a pull request for the import fix.
