### ISSUE TITLE
NSIS installer opening during update

### ISSUE THREAD

**Issue by megasanjay** [electron-userland/electron-builder#6135]
* **Electron-Builder Version**: 22.10.5

* **Node Version**: 10.13.0

* **Electron Version**: 6.1.9
* **Electron Type (current, beta, nightly)**:
 Which version of electron-updater are you using (if applicable)? 4.3.9

* **Target**: NSIS

I am using an older version of electron and electron-builder at the moment but we are stuck on those versions for the time being (looking to update to a later version in the future). On our app, we found a weird interaction with the autoupdate process on Windows. This was working correctly last month but on Windows, when the autoupdate module is called for the quit and install process, the NSIS setup appears again while updating. The install process for both macOS and Linux are working as intended. Previously, the install process would run in the background and no show any user prompts before reopening the updated app. I'm not sure if this is a new thing with a windows version-specific issue or if we are missing a config command in the build process that is causing this problem.

Our config at the moment:
`"nsis": {
      "createDesktopShortcut": "always",
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "assets/app-icon/win/icon.ico"
    },`

This is not a major issue but something we were concerned about since it just started happening. Thanks for the help and we love the work y'all do.

**Comment by mmaietta** [comment]
You mentioned this recently began for you in the past month. Was that after updating electron-updater or does this seem to be related to an OS update?

**Comment by megasanjay** [comment]
I'm thinking this might be an os specific issue in our case. We are running Windows 19042.1110 if that helps. Our electron-updater version is from 3 months ago and the update process ran silently in our previous builds so I don't think that is the culprit at least. Please correct me if I'm wrong.

**Comment by mmaietta** [comment]
It does indeed seem like a Windows issue then. Would you be willing to investigate and contribute to the code? My guess is some arg in the nsis scripts is no longer being parsed, but I don't know why that'd change recently.

Setting up a dev env is fairly simple though 🙂 
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
