### ISSUE TITLE
Node_modules module @serialport/bindings/build/Release/obj this directory has not been packaged

### ISSUE THREAD

**Issue by wcldyx** [electron-userland/electron-builder#6144]
* **Electron-Builder Version**: 22.12.0

* **Node Version**: v14.16.0

* **Electron Version**:12.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: 
Serialport in a production environment is not available, because the @ serialport node_modules/bindings/build/Release/obj has not been packaged

**Comment by wcldyx** [comment]
Did I not describe it clearly?

**Comment by wcldyx** [comment]
> Seems like an import issue in either your sourcecode such that it doesn't transform the path to be usable within, or your `files` config is incorrect.
> Is the module in your packaged `app.asar` at least or "smartly" unpacked to `app.asar.unpacked`?
> Try manually including the file path in the `files` section.
> 
> I strongly doubt this is an electron-builder issue

#https://github.com/serialport/node-serialport/issues/2229
Add to "npmRebuild": "false" to the electron- Builder configuration

**Comment by mmaietta** [comment]
If you're needing to use 'electron-rebuild' instead of electron-builder's built-in native rebuilder, then you're likely dealing with an upstream bug in the Golang module, app-builder-bin. 
I have to use electron-rebuild for universal builds on my Mac because of an upstream bug of that sort.
