### ISSUE TITLE
My app's users are reporting that the Windows version is phoning home to Google on run

### ISSUE THREAD

**Issue by szTheory** [electron-userland/electron-builder#6148]
* **Electron-Builder Version**: 
22.11.7

* **Node Version**: 
12.18.3

* **Electron Version**:
11.4.10

* **Electron Type (current, beta, nightly)**:
Current

* **Using electron-updater?**
No

* **Target**: 
Windows, Linux, Mac

A couple of my app's users are seeing outgoing connections in their firewall to Google when they run the app in Windows. I am running a firewall on a Mac and not seeing these connections. One user reported a connection to 172.217.164.238 on port 443/tcp which seemed to be Google site (yyz12s05-in-f14.1e100.net). Another user says they are seeing different Google IPs each time they run the app.

When they run the app locally in dev mode (not the packaged version downloaded from Github Release) they don't see this outgoing connection. When they built the packaged app locally on their Windows machine and tried running that they also didn't see the outgoing connections. I build the apps on my local Mac machine before pushing them to Github Releases on each new version release.

I'm not sure what could be causing this. Any ideas? [Here is the Github Issue](https://github.com/szTheory/exifcleaner/issues/116) that is open for this on my app ExifCleaner's Github page.

Thank you!

**Comment by mmaietta** [comment]
Hmmm, AFAIK, Electron-builder has nothing to do with Google IPs or lookups or phoning home.

Can you please try repro with electron-quick-start sample app?
