### ISSUE TITLE
Modules not working in the binary

### ISSUE THREAD

**Issue by matikbird** [electron-userland/electron-builder#615]
**Version**: ^5.12.1

* **Target**: Windows & Linux

Hi folks!
Hope you're doing OK.

I have this tiny situation, where some modules (like **electron-html-to** or a **medium-extension**) are not working. 
 If I do: `npm start` everything works as it should.
 If I do: `npm run release` the PDF export and the option of adding images and handling them are missing. It's like the whole editor it's broken.
 
And I can't see why. I can't debug it.
I uploaded the repo (which's an open source project, so thanks, thanks for your work, and thanks to electron itself and all the ones who contributed). This repo it's suppose to be a little Office, and so far it works (I have builded binaries already for Windows & Linux, you can check out here: [https://matikbird.github.io/textiled/](https://matikbird.github.io/textiled/).

This is the repo to reproduce the issue (export the content as PDF, in npm start it will work, in released version something not went good): 
https://github.com/matikbird/textiled

Thank you all in advance!

**Comment by develar** [comment]
You are lucky, I am working on #602 

Unrelated note: `devDependencies` in the app deps — `debug-menu` will be never copied into the packaged app. I hope, it is intentionally.

**Comment by develar** [comment]
`electron-html-to` uses https://github.com/bjrmatos/electron-workers, — electron-worker relies on installed `electron` — it is *** . See https://github.com/bjrmatos/electron-workers#solution
