### ISSUE TITLE
NSIS Installer hangs when being run silently

### ISSUE THREAD

**Issue by aharringtonaviata** [electron-userland/electron-builder#616]
* **Version**: 5.10.2

* **Target**: NSIS

I have built the NSIS installer for an electron app and I can run it from the command line in windows successfully but whenever I add the "/S" flag described here: http://nsis.sourceforge.net/Docs/Chapter3.html the installer hangs and never completes and prevents future attempts of the installer to never run until I terminate the process in windows task manager.

I was also able to silently install using a different NSIS installer executable for a simple example. Is there something that the electron builder does to prevent silent install from happening correctly?

**Comment by develar** [comment]
It seems https://github.com/electron-userland/electron-builder/blob/master/templates/nsis/installer.nsi#L65 is the cause. Will check.
