### ISSUE TITLE
Electron-Builder not specifiying Exec Path while building snaps

### ISSUE THREAD

**Issue by agam778** [electron-userland/electron-builder#6166]
* **Electron-Builder Version - 22.10.5**: 

* **Node Version - 16.6.2**: 

* **Electron Version - 12.0.0**:
* **Electron Type - current**:

* **Target - Snap** 

I have packaged the app for snap by running `yarn dist --linux snap`. I have checked the package.json file too. Everything is correct. Even the snap is installable. But the issue is, whenever i try opening the app, it gives this error

![unknown](https://user-images.githubusercontent.com/68941022/129936507-d9029062-8f0d-4716-b3b6-0b03b0dc0805.png)

When I edited the `.desktop` file in `/var/lib/snapd` and added the Exec value, it was working but yea i want it to pre configure as the people won't edit the `.desktop` file manually.

So is there a solution to fix this?

Edit: The app works if I run in the terminal with `snap run ms-office-electron`

**Comment by agam778** [comment]
Hello?

**Comment by agam778** [comment]
Hello?

**Comment by RickRollMaster101** [comment]
yes

**Comment by agam778** [comment]
> yes

Do you know the solution?
