### ISSUE TITLE
How to do continuous integration through update channel?

### ISSUE THREAD

**Issue by florisporro** [electron-userland/electron-builder#6168]
On our app we'd like the 'alpha' channel to be a continuously released latest build channel, so abandoning the semantic versioning and releasing the build from every latest commit. Is this something that can be done with electron-builder?

**Comment by mmaietta** [comment]
Curious. Why not just have your alpha channel be a timestamped build version so that the semver always seems to be increasing?
Something like `month.day.unix-timestamp`

**Comment by florisporro** [comment]
> Curious. Why not just have your alpha channel be a timestamped build version so that the semver always seems to be increasing?
> Something like `month.day.unix-timestamp`

I guess that would work if there was some way of programmatically setting the publish version in the electron-builder cli, otherwise the only way I see of doing that would committing package.json with every new commit. Seems like a messy solution to me.
