### ISSUE TITLE
Can't install electron-builder on linux.

### ISSUE THREAD

**Issue by airtonix** [electron-userland/electron-builder#6171]
* **Electron-Builder Version**: 

```
    "electron-builder": "22.11.7",
```

* **Node Version**: 
`nodejs v16.6.1`

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

```
    "electron": "13.2.1",
```

* **Target**: 
?
all of them. but i develop on linux.

`pnpm i` results in : 
```
 ERROR  Unsupported platform for registry.npmjs.org/iconv-corefoundation/1.1.6: wanted {"cpu":["any"],"os":["darwin"]} (current: {"os":"linux","cpu":"x64"})
```

**Comment by mhatvan** [comment]
Hey @airtonix, I ran into the exact same issue and reported it in pnpm: https://github.com/pnpm/pnpm/issues/3640

This is now fixed with pnpm v6.14.1, so you can probably close this issue.
