### ISSUE TITLE
Unable to load local resources error after rebuilding using typescript

### ISSUE THREAD

**Issue by kimlimjustin** [electron-userland/electron-builder#6173]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.15.0

* **Electron Version**: 13.1.9
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

Electron works fine before, however, after I rebuild my project using TypeScript, it shows "Unable to load local resources error"
![image](https://user-images.githubusercontent.com/61906684/130353341-8fc387d5-3ac4-4744-a9b7-f2ff93a2c2cf.png)

I place my typescript code into `src` folder and the typescript compilation output at the `outs` directory, and I also changed the configuration of electron-builder as fellow:
```json
"build": {
        "files": [
            "outs/**/*",
            "node_modules/**/*",
            "package.json",
            "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
            "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
            "!**/node_modules/*.d.ts",
            "!**/node_modules/.bin",
            "!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}",
            "!.editorconfig",
            "!**/._*",
            "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}",
            "!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}",
            "!**/{appveyor.yml,.travis.yml,circle.yml}",
            "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}"
        ],
```
Note that when I transpile the TypeScript code, I also added a code that copies two essential dirs, `lib` and `build`, my code and the native c++ builds respectively into the `outs` folder. 

I also tried to run electron on the TypeScript transpilation output, `electron ./outs/src/main.js` and everything works fine. The error occurs after building it using `electron-builder`

FYI, I tried to unpack the asar file, and the files are there, but It's just unable to load.

Any helps will be appreciated, thanks!

**Comment by mmaietta** [comment]
Can you give these answers a shot?
https://stackoverflow.com/questions/41130993/electron-not-allowed-to-load-local-resource

Also, all the ignores in your glob patterns should be added by default. I think you only need to have 
```
"files": [
  "outs/**/*"
]
```

**Comment by kimlimjustin** [comment]
> Can you give these answers a shot?
> https://stackoverflow.com/questions/41130993/electron-not-allowed-to-load-local-resource

I tried every solution out there before I open this issue but not any works

> Also, all the ignores in your glob patterns should be added by default. I think you only need to have
> 
> ```
> "files": [
>  "outs/**/*"
>]
> ```

I tried it too, but just the same error.

Or is there any template for electron + typescript + electron builder? I tried google but got nothing. 

Also, here's my code: https://github.com/kimlimjustin/xplorer/tree/typescript-dist

Thanks!

**Comment by kimlimjustin** [comment]
I'm able to handle it now with the [Electron forge](https://www.electronforge.io/templates/typescript-template). However, I still hope that electron-builder could fix this issue, thanks!

**Comment by kimlimjustin** [comment]
I'm now able to run it by config it like this:
```json
"files": [
     "**/*",
     "!src/**/*.ts"
]
```
but I'm wonder why it's not working by using the previous config
