### ISSUE TITLE
Open too soon after quit when update has downloaded

### ISSUE THREAD

**Issue by lukehaas** [electron-userland/electron-builder#6174]
After an update has been downloaded via electron-updater and instead of calling `autoUpdater.quitAndInstall()` you call `app.quit()` - if you then open the app too soon (maybe within 60 seconds?), the app will open but in some kind of partially updated state where there are numerous errors and fonts fail to load.

OS: macOS 10.15.7
Electron version: 13.1.7
Electron-builder version: 22.11.7

**Comment by mmaietta** [comment]
Wait, I'm not sure I'm following. Are you calling quit? Or are you saying electron-builder shouldn't be calling quit?

**Comment by lukehaas** [comment]
I'm calling quit, via `app.quit()`. 

Here is the sequence of events:

1. electron-updater downloads an update
2. user quits the app via `app.quit()`
3. the update starts getting installed in the background
4. the user opens the app before the installation is complete
5. app is open in a broken, partially updated state

**Comment by lukehaas** [comment]
@mmaietta if it helps, I think when an app is opened before the installation is complete, this is one of the errors that is present: `Error: Could not get code signature for running application`

**Comment by npc1437** [comment]
![image](https://user-images.githubusercontent.com/40747064/132378274-105374fa-ea2c-4724-b9e3-ad0b563e55f9.png)
I have the same problem

**Comment by Amethystafyy282** [comment]
Happened to me, I'm using `autoUpdater.autoInstallOnAppQuit = true`
here are the events:
1: Event `update-downloaded` trigger.
2: User quit app on `app.quit()`
3: Update is being installed
4: The user opens the app at this very moment
5: App Crash with error in the image
![Screen Shot 2022-08-01 at 16 02 43](https://user-images.githubusercontent.com/63139844/182113265-99a08c08-9f61-4fd7-a339-034961cb0464.png)
