### ISSUE TITLE
Uninstall Confirm Dialog Option for One-click Windows NSIS

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#618]
* **Version**: 5.19.0

* **Target**: Win32 NSIS One-click

Can we please add an option (or have it default behaviour) to have a simple "Are you sure you want to uninstall {{AppName}} ?" dialog popup when using the Add/Remove Programs feature of Windows ?

**Motivation:** Prevent unintentional data loss (from selecting the wrong program by mistake). Also it is standard Windows behaviour to have a confirmation dialog before uninstall.

**Comment by develar** [comment]
<img width="671" alt="screen shot 2016-07-29 at 11 32 13" src="https://cloud.githubusercontent.com/assets/350686/17244053/209a3156-5580-11e6-8efc-7426e2d97bae.png">

Windows 10 asks you about it. Is it not enough (I am not Windows user)?

**Comment by dharders** [comment]
Yes, that screenshot for Windows 10 is correct behaviour (I had only tested win 7 when posted the issue). 

That's the 'new' Windows 10 "Add or remove programs" feature and that works as expected (I have since tested on Win 10). However, in Windows 10 there is also a "Change or remove a program" feature (God, bless them and their consistency!) and that is where the unexpected behaviour is happening (this is the Windows 7 way too, via Control Panel). To find the feature in Win10, just type 'change or remove' in the search bar (or find it in Control Panel) and hopefully you'll see the behaviour I'm describing.

(side-issue: if I click Uninstall while App is running, nothing happens...I assume exception is swallowed silently? Should we also prompt like install "Click OK to close running app..." ?)

**Comment by dharders** [comment]
I just tried your 5.22.1 release with your fix and the confirm dialog still does not popup for Win10 "Change or remove a program" and Win7. It still uninstalls without prompting. 

Am I missing something?

**Comment by develar** [comment]
> (side-issue: if I click Uninstall while App is running, nothing happens...I assume exception is swallowed silently? Should we also prompt like install "Click OK to close running app..." ?)

Fixed.

> It still uninstalls without prompting.

Fixed.

Cause: `SilentUnInstall` equals to `/S` — but we need partial silent, so, granular `SetSilent` is used as a solution.

**Comment by dharders** [comment]
Awesome work!

I confirm that the fix in 5.23.1 is now working for both Win7 and Win10 (both uninstall variants)!

Perfect and thanks!

**Comment by adicojo** [comment]
Hello,

How can we skip the confirmation dialog <Are you sure you want to completely remove {AppName} and all of its components?> when the /S switch is used for a NSIS uninstallation? It prevents the uninstall from being unattended...

Thank you.

**Comment by ismoil793** [comment]
Hi @adicojo, it has been a while but anyway do you know a way to skip that confirmation screen?
