### ISSUE TITLE
How to modify the language？

### ISSUE THREAD

**Issue by Realybig** [electron-userland/electron-builder#6194]
![企业微信截图_1630056060767](https://user-images.githubusercontent.com/10878451/131104803-d8c3ffe1-efd6-4d0f-b1dd-731082900a33.png)

**Comment by mmaietta** [comment]
Language files can be provided for dmg-license and for nsis, it's provided as a language code (I'm guessing). Example I found in a unit test:
```
        nsis: {
          oneClick: false,
          language: "1031",
        },
```
