### ISSUE TITLE
Windows 10 S compatibility issue

### ISSUE THREAD

**Issue by jan-mastersoft** [electron-userland/electron-builder#6195]
When i run Windows App Certification Kit test on my app( APPX build),  it fails Package sanity test, saying that launching certain executables is restricted on Windows 10 S and because of that I can't submit my app on Windows Store. The thing is most if not all of those are Electron or Chrome executables, like d3dcompiler_47.dll, full list of errors below.

Any suggestions?

◦File app\GisMatrix.exe contains a reference to a "Launch Process" related API kernel32.dll!CreateProcessA
◦File app\GisMatrix.exe contains a reference to a "Launch Process" related API kernel32.dll!CreateProcessW
◦File d3dcompiler_47.dll contains a blocked executable reference to "cmd".
◦File d3dcompiler_47.dll contains a blocked executable reference to "Reg".
◦File GisMatrix.exe contains a blocked executable reference to "CDb".
◦File GisMatrix.exe contains a blocked executable reference to "CMd".
◦File GisMatrix.exe contains a blocked executable reference to "rEG".
◦File GisMatrix.exe contains a blocked executable reference to "DNX".
◦File GisMatrix.exe contains a blocked executable reference to "CSI".
◦File GisMatrix.exe contains a blocked executable reference to "bash".
◦File GisMatrix.exe contains a blocked executable reference to "cmd.exe".
◦File icudtl.dat contains a blocked executable reference to "Reg".
◦File icudtl.dat contains a blocked executable reference to "CDB".
◦File resources.pak contains a blocked executable reference to "csi".
◦File resources.pak contains a blocked executable reference to "REg".
◦File resources.pak contains a blocked executable reference to "bash".
◦File resources.pak contains a blocked executable reference to "cmd".
◦File resources.pak contains a blocked executable reference to "PowerShell".
◦File vk_swiftshader.dll contains a blocked executable reference to "reg".
◦File es-419.pak contains a blocked executable reference to "REg".
◦File hi.pak contains a blocked executable reference to "cMD".
◦File hi.pak contains a blocked executable reference to "dNx".
◦File sv.pak contains a blocked executable reference to "reg".
◦File app.asar contains a blocked executable reference to "cmd".
◦File app.asar contains a blocked executable reference to "reg".
◦File app.asar contains a blocked executable reference to "csi".
◦File app.asar contains a blocked executable reference to "Bash".
◦File app.asar contains a blocked executable reference to "cmd.exe".
◦File app.asar contains a blocked executable reference to "powershell".
◦File app.asar contains a blocked executable reference to "msbuild".
◦File app.asar contains a blocked executable reference to "msbuild.exe".
◦File app.asar contains a blocked executable reference to "powershell.exe".
◦File app.asar contains a blocked executable reference to "\MSBuild".
◦File app.asar contains a blocked executable reference to "reg.exe".
◦File app.asar contains a blocked executable reference to "wscript".
◦File libGLESv2.dll contains a blocked executable reference to "reg".
Impact if not fixed: Launching executable files is restricted on Windows 10 S systems. Apps that rely on this capability might not run correctly on Windows 10 S systems.

**Comment by mmaietta** [comment]
Would be happy to review a PR for this if you're willing to contribute! Setting up a local dev environment is fairly simple 🙂 
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by bojanbizjak** [comment]
Yes
