### ISSUE TITLE
Can't fork child process in packaged app (windows)

### ISSUE THREAD

**Issue by kouji-dev** [electron-userland/electron-builder#6199]
I'm currently facing an issue forking a nodejs script. I have a dir `/bot` which contains my `automate.js` file and in the main.ts i try to fork it as follow:

`const BOT_PATH = app.isPackaged
  ? path.join(process.resourcesPath, 'bot')
  : path.join(__dirname, '../../bot');
`
`const getBotPath = (...paths: string[]): string => {
  return path.join(BOT_PATH, ...paths);
};`

`const child = fork(getBotPath('automate.js'), [], {
      env: process.env,
});`

This is my build config:

`"build": {
    "productName": "kouji-bot",
    "appId": "org.koujiBOT.app",
    "asar": true,
    "asarUnpack": "**\\*.{node,dll}",
    "files": [
      "dist",
      "node_modules",
      "package.json"
    ],
    "afterSign": ".erb/scripts/notarize.js",
    "mac": {
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "gatekeeperAssess": false
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "target": [
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "app": "build/app",
      "buildResources": "assets",
      "output": "build/release"
    },
    "extraResources": [
      "./assets/**",
      "./bot/**"
    ],
    "publish": {
      "provider": "github",
      "owner": "kouji-bot",
      "repo": "kouji-bot"
    }
  }`

it works fine in development mode, but when I package the app and I try to lunch the .exe file it remains stuck (i don't know how to debug my packaged app).

* **Electron-Builder Version**: ^22.11.1
* **Node Version**:  v16.6.0
* **Electron Version**: ^13.1.8
* **Electron Type (current, beta, nightly)**: current
* **Operating System**: windows

**Comment by robertpatrick** [comment]
@goodbeysr this looks like a programing error and doesn't seem related to electron-builder.  One way to debug your packages application is to add logging and write log entries.  electron-log is a simple logging package that you could use (we use winston in the main process).  

The most obvious thing to do is to verify that getBothPath() is returning a valid path to the `automate.js` file.  In our app, all JS files are packaged inside app.asar so looking in the resources directory would not be correct.
