### ISSUE TITLE
Different package.json files packed in deb and rpm

### ISSUE THREAD

**Issue by mzmousa** [electron-userland/electron-builder#620]
* **Version**: 5.19.1

* **Target**: linux

When building for linux, I want to have `.deb` and `.rpm` files. However, I want to have different `package.json` files in each of them in order to do [linux updates](https://github.com/Aluxian/Whatsie/issues/371). I was wondering if I have to do separate builds of `deb` and `rpm` (the slow way) or if I can specify different `package.json` files for each of my `deb` and `rpm` files.

**Comment by develar** [comment]
Problem is that App packed once for all targets. So, #494 is not solution. I recommend you AppImage instead. AppImage supports auto-update but it is not yet supported by electron-builder yet.

**Comment by develar** [comment]
For ASAR fixed only.

**Comment by develar** [comment]
Duplicates #494 

Workaround: build in two invocations and pass `--em.propertyName=propertyValue`
