### ISSUE TITLE
Electron-builder fails to include prebuilt shared libraries on linux.

### ISSUE THREAD

**Issue by rrgeorge** [electron-userland/electron-builder#6200]
* **Electron-Builder Version**: 22.12.0

* **Node Version**: 14.17.2

* **Electron Version**: 12.0.12
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux x64

Electron-builder fails to include prebuilt shared libraries on linux.
This can be easily confirmed when using sharp, which should include libvips-cpp.so.42. Trying to an application that uses sharp on linux will result in the message:
`libvips-cpp.so.42: cannot open shared object file: No such file or directory`
Electron-builder correctly includes the required shared libraries on macOS and windows. The same application will function properly on both platforms, where the required library is included in the package.

**Comment by mmaietta** [comment]
Did you add that to `depends`?
https://www.electron.build/configuration/linux#debian-package-options

**Comment by rrgeorge** [comment]
That's for package dependencies, not libraries that should be included inside the package.

**Comment by mmaietta** [comment]
In that case, shouldn't using `files` or `extraFiles` then suffice by manually including the shared library?

**Comment by rrgeorge** [comment]
ElectronBuilder ignores linux. 

> In that case, shouldn't using `files` or `extraFiles` then suffice by manually including the shared library?

I tried that, but it didn't work. However, it did lead me to do some deeper investigation. It seems that my original premise was incorrect, the shared libraries *do get included*, but linux is unable to access them inside the asar archive.
So the correct solution is to add the affected modules to your `asarUnpack` setting. For sharp I'm using:
```
    "linux": {
         "asarUnpack": [
             "**/node_modules/sharp/**"
         ]
     },
```
 I'm going to close my issue.

**Comment by KillerCodeMonkey** [comment]
@rrgeorge it works

**Comment by ZhengyiLuo** [comment]
Thanks, @rrgeorge! Works!!
