### ISSUE TITLE
How to customize menu bar please?

### ISSUE THREAD

**Issue by yichengye310** [electron-userland/electron-builder#6202]
* **Electron-Builder Version**: 

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:  armv7l

I am new to electron & electron-builder. Just a quick question, how to change the menu bar in generated APPIMAGE?

Thanks in advance.

**Comment by mmaietta** [comment]
Probably should start here: https://www.electronjs.org/docs/api/menu
