### ISSUE TITLE
flatpak failed with status code 1

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [electron-userland/electron-builder#6211]
* **Electron-Builder Version**:  22.11.7

* **Node Version**: v14.17.5

* **Electron Version**: v11.0.3
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Linux

When building flatpak using the "flatpak" target inside the electronuserland/builder:wine docker image, I got the error "flatpak failed with status code 1". I'm a not very familiar with flatpak to say the least, and I have no idea what's going on.

Do I miss some configuration? I was very hard to find documentation about flatpak, so I definitely may have forgotten something 😕 

The configuration file can be found [here](https://gitlab.com/BenjaminVanRyseghem/SandGlass/-/blob/3a4ed97c/electron-builder.json).

Thanks in advance

Side note: I would be very cool if electronuserland/builder images could embed flatpak and flatpak-builder out of the box. I had to add quite some slow steps to [the CI](https://gitlab.com/BenjaminVanRyseghem/SandGlass/-/blob/6a6d375f/.gitlab-ci.yml#L24-28) to add them.

**Comment by mmaietta** [comment]
I'm not familiar with flatpak either, but it wasn't implemented to be able to run in the docker image, additional packages are required to be installed as you discovered. flatpak was a beta feature added by a courageous community member.

IIRC `flatpak` and `flatpak-builder` were quite heavy for bundling into an image. Do you know what the size impact is of adding those to the base docker image?
I can't test because docker doesn't run on Hackintosh's. 😬

**Comment by BenjaminVanRyseghem** [comment]
@mmaietta thanks for the answer :smile:

I followed a bit the trip to add it in the PR and the issue, read the code and so, but it was too complicated for me :smile:

I run the docker in Gitlab CI, so I don't know the size impact, sorry

**Comment by BenjaminVanRyseghem** [comment]
And trying it locally is complicated because I have a M1 macbook 😕

**Comment by benoitf** [comment]
on my side I received the status code 1 as some flatpak dependencies were not installed.

I got original error by passing env variable `DEBUG=*` before the electron-builder command

like:
```bash
DEBUG=* electron-builder build .... --linux flatpak
```

Then I can see commands/errors from flatpak-bundler

**Comment by RangerMauve** [comment]
@benoitf What were the missing dependencies in your case? I made sure to add `flatpak` and `flatpak-builder` in my dependencies before running the build.

**Comment by benoitf** [comment]
@RangerMauve 

on a CI:
```
sudo apt-get install flatpak -y
sudo apt-get install flatpak-builder -y
sudo apt-get install elfutils -y
```

**Comment by RangerMauve** [comment]
Thank you for the info. I had flatpak and flatpak-builder set up per the docs, but didn't have elfutils. Sadly adding that to the packages didn't fix it.

I'm currently using electron-builder via a github action which doesn't expose DEBUG environment variables directly. I'll see if I can do a workaround and give folks tips once I've figured it out. 🙇
