### ISSUE TITLE
How to build an installer directly from 'win-unpacked' file ?

### ISSUE THREAD

**Issue by DebraJohn** [electron-userland/electron-builder#6220]
* **Electron-Builder Version**: 22.11.11

* **Node Version**: 14.14.0

* **Electron Version**:13.1.9
* **Electron Type (current, beta, nightly)**:current

* **Target**:  target: 'nsis', arch: ['x64'],

When I run build app, it will pack a ‘win-unpacked’ file and a exe file.
If I already had a 'win-unpacked', how can I build an installer directly from the exsiting one?

**Comment by mmaietta** [comment]
You can use `--prepackaged` via CLI

**Comment by DebraJohn** [comment]
> You can use `--prepackaged` via CLI

It works. Thank you. @mmaietta
