### ISSUE TITLE
Please extend ("electron").autoUpdater to MSI builds

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron-userland/electron-builder#6222]
* **Electron-Builder Version**: ^22.10.5

* **Node Version**: v14.16.1

* **Electron Version**: ^13.1.8
* **Electron Type (current, beta, nightly)**:

* **Target**: MSI

Good afternoon,

It appears in the electron-updater-> src folder there isn't a file extending electron's native autoUpdater module for MSI builds

For example in MacUpdater.ts: `private readonly nativeUpdater: AutoUpdater = require("electron").autoUpdater`

Is there anyway we could get that for .msi build's aswell? I'm able to install and auto-update on my .dmg Mac builds no problem using the autoUpdater module from electron. But I'm unable to auto-update my msi installations using the autoUpdater module from electron. The only error I get from windows is "Cannot find Squirrel" but rest assured I **am** testing live installations **not** dev builds.

**Comment by mmaietta** [comment]
>It appears in the electron-updater-> src folder there isn't a file extending electron's native autoUpdater module for MSI builds

That's correct. Only NSIS target is supported for windows: https://www.electron.build/auto-update

**Comment by gujinku** [comment]
> > It appears in the electron-updater-> src folder there isn't a file extending electron's native autoUpdater module for MSI builds
> 
> That's correct. Only NSIS target is supported for windows: https://www.electron.build/auto-update

Could you please clarify why we don't support auto-update for MSI?
MSI is only a package that can easily support the IT push.

**Comment by YeetOrBeYate** [comment]
Funny enough that was also my reason for wanting autoupdate for MSI^
