### ISSUE TITLE
Can't build on Windows when using a JS file for config.

### ISSUE THREAD

**Issue by jedieaston** [electron-userland/electron-builder#6227]
* **Electron-Builder Version**: 22.11.11 (4.4.3)

* **Node Version**: 14.17.1

* **Electron Version**: 14.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

I'm attempting to run electron-builder using a JS file for config (so I have access to process.ENV, which isn't available in yaml files). Attempting to run any electron-builder command on Windows results in a JScript error (which is super weird unless somehow electron-builder is trying to execute the file without node). The screenshot was taken after running `npx electron-builder` from PowerShell at the project root:

![image](https://user-images.githubusercontent.com/21368066/132039131-d34383e6-300e-4105-abc8-5d11bfddccbc.png)

For reference, here's my electron-builder.js:

```
const config = {
    appId: "im.hmt.report.schild",
    productName: "schild.report",
    artifactName: "schild.report.${ext}",
    buildVersion: `2.5.${process.env.GITHUB_RUN_NUMBER}`,
    copyright: `Copyright ${process.env.THE_AUTHOR}`,
    extraMetadata: {
        author: {
            name: `${process.env.THE_AUTHOR}`,
            email: `${process.env.THE_EMAIL}`
        }
    },
    files: [
        "./build/**/*"
    ],
    win: {
        icon: "icons/icon.ico",
        target: "msi"
    },
    linux: {
        icon: "icons/icon.png",
        category: "app.tools",
        executableName: "schild.report",
        target: [
            "AppImage",
            "snap",
            "deb",
            "rpm"
        ]
    },
    mac: {
        icon: "icons/icon.icns",
        target: "dmg"
    },
    dmg: {
        icon: "icons/icon.icns",
        contents: [
            {
                x: 130,
                y: 220
            },
            {
                x: 550,
                y: 22,
                type: "link",
                path: "/Applications"
            }
        ],
        window: {
            width: 680,
            height: 42
        }
    }
}
module.exports = config

```
This also happens on GitHub Actions hosted runners, so it's not my machine.

**Comment by ahadcove** [comment]
We're currently running into this same issue

**Comment by ahadcove** [comment]
Seems like the node version was causing issues. Try downgrading to node 14 and the build should go through without any issues

**Comment by hmt** [comment]
As stated above this is node 14. What's the exact version you're using?

**Comment by IhorKobylinskiy** [comment]
Have the same issue. Tried with different node versions.

**Comment by mmaietta** [comment]
> I'm going to leave this open because it's definitely a bug

I still wholly disagree that this is due to it being an electron-builder-specific issue, as my project builds on linux/win/mac machines using a config file named `electron-builder.js` without any issues. Same with using a `electron-builder.yaml` and I've tested it using both npm and yarn.

**Comment by jedieaston** [comment]
I run from Windows PowerShell 5.1. I haven't had this issue with any other Node packages before, although the fact that renaming the file to something that isn't `electron-builder.js` makes it work is extremely weird. Maybe npm/npx is mangling the path somehow, and directing `electron-builder` to `./electron-builder.js` somehow?

**Comment by fairking** [comment]
The following might be related and could help to solve the problem: https://github.com/ficonsulting/RInno/issues/44#issuecomment-992299431
