### ISSUE TITLE
22.11.7: `install-app-deps` doesn't report build failure

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron-userland/electron-builder#6230]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.16.0

* **Electron Version**: 12.1.8
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows x64

I tried to use Visual Studio 2015 build tools to build `better-sqlite3`, and it worked for a normal `yarn install`. But when built via `electron-builder install-app-deps` it seemed to succeed, but actually didn't. I looked under the hood, and this build output happened, but wasn't considered an error by `install-app-deps`

```
> better-sqlite3@7.1.4 build-release <BASE_PATH>\node_modules\better-sqlite3
> node-gyp rebuild --release


<BASE_PATH>\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\Build\AppData\Roaming\nvm\v14.16.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\Build\AppData\Roaming\nvm\v14.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  extract_sqlite3
  Copying <BASE_PATH>\node_modules\better-sqlite3\build\Release\obj/global_intermediate/sqlite3/OpenSSL-Win64/libcrypto.lib to <BASE_PATH>\node_modules\better-sqlite3\build\Release\\libcrypto.lib
          1 file(s) copied.
  Copying <BASE_PATH>\node_modules\better-sqlite3\build\Release\obj/global_intermediate/sqlite3/OpenSSL-Win64/libssl.lib to <BASE_PATH>\node_modules\better-sqlite3\build\Release\\libssl.lib
          1 file(s) copied.
  Copying <BASE_PATH>\node_modules\better-sqlite3\build\Release\obj/global_intermediate/sqlite3/OpenSSL-Win64/ossl_static.pdb to <BASE_PATH>\node_modules\better-sqlite3\build\Release\\ossl_static.pdb
          1 file(s) copied.
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> <BASE_PATH>\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(1652): error C2059: syntax error: '' (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(1654): error C2238: unexpected token(s) preceding ';' (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(1670): error C2061: syntax error: identifier 'ResolveCallback' (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(7292): error C2059: syntax error: '' (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(8652): error C2061: syntax error: identifier 'HostImportModuleDynamicallyCallback' (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
./src/objects/database.lzz(361): warning C4309: 'static_cast': truncation of constant value (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
./src/util/binder.lzz(36): warning C4996: 'v8::Object::CreationContext': Use MaybeLocal<Context> GetCreationContext() (compiling source file ..\src\better_sqlite3.cpp) [<BASE_PATH>\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
  c:\users\build\.electron-gyp\13.1.8\include\node\v8.h(4294): note: see declaration of 'v8::Object::CreationContext' (compiling source file ..\src\better_sqlite3.cpp)
  test_extension.c
  win_delay_load_hook.cc
     Creating library <BASE_PATH>\node_modules\better-sqlite3\build\Release\test_extension.lib and object <BASE_PATH>\node_modules\better-sqlite3\build\Release\test_extension.exp
  test_extension.vcxproj -> <BASE_PATH>\node_modules\better-sqlite3\build\Release\\test_extension.node
  test_extension.vcxproj -> <BASE_PATH>\node_modules\better-sqlite3\build\Release\test_extension.pdb (Full PDB)
```

The solution, by the way, was to upgrade to Visual Studio 2017 build tools, and force it to use those updated tools with `npm config set msvs_version 2017`. I'd really rather not find out only when attempting to run the packaged version of the app. I'd like to know at build time that there's a problem.

**Comment by mmaietta** [comment]
There's nothing we can really do about this. Anything that is about native modules and install/rebuilding them is in an upstream Go library, app-builder. https://github.com/develar/app-builder

**Comment by scottnonnenberg-signal** [comment]
Are you sure? This is not about building the final package, but `install-app-deps`: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/cli/install-app-deps.ts

And `app-builder-lib` implements that command here, right? https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib

Likely this actual file, right? https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/util/yarn.ts

**Comment by bruceauyeung** [comment]
electron-builder version: 22.14.13
i get similar problem when `electron-builder install-app-deps` builds nativemodule `mmap-io`
**1. when i directly ran `electron-builder install-app-deps` in bash shell, i got error in stdout/stderr:**

>  npm verb lifecycle mmap-io@1.1.7~build-addon: CWD: /media/vdb/ucs/client/windows/XUI/node_modules/mmap-io
    npm info lifecycle mmap-io@1.1.7~build-addon: Failed to exec build-addon script
    npm verb stack Error: mmap-io@1.1.7 build-addon: `node-gyp configure && node-gyp rebuild`
    npm verb stack Exit status 1
    npm verb stack     at EventEmitter.<anonymous> (/hidden/for/security/.config/nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
    npm verb stack     at EventEmitter.emit (events.js:315:20)
    npm verb stack     at ChildProcess.<anonymous> (/hidden/for/security/.config/nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    npm verb stack     at ChildProcess.emit (events.js:315:20)
    npm verb stack     at maybeClose (internal/child_process.js:1048:16)
    npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    npm verb pkgid mmap-io@1.1.7
    npm verb cwd /media/vdb/ucs/client/windows/XUI/node_modules/mmap-io
    npm verb Linux 4.19.112-2.el8.x86_64
    npm verb argv "/hidden/for/security/.config/nvm/versions/node/v14.16.0/bin/node" "/hidden/for/security/.config/nvm/versions/node/v14.16.0/bin/npm" "run" "build-addon"
    npm verb node v14.16.0
    npm verb npm  v6.14.11
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! mmap-io@1.1.7 build-addon: `node-gyp configure && node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the mmap-io@1.1.7 build-addon script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm verb exit [ 1, true ]
    npm timing npm Completed in 1697ms
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /hidden/for/security/.npm/_logs/2022-02-08T08_25_22_102Z-debug.log
    npm verb lifecycle mmap-io@1.1.7~install: unsafe-perm in lifecycle true
    npm verb lifecycle mmap-io@1.1.7~install: PATH: /hidden/for/security/.config/nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/vdb/ucs/client/windows/XUI/node_modules/mmap-io/node_modules/.bin:/media/vdb/ucs/client/windows/XUI/node_modules/.bin:/hidden/for/security/.local/bin:/hidden/for/security/bin:/hidden/for/security/.config/nvm/versions/node/v14.16.0/bin:/hidden/for/security/.local/bin:/hidden/for/security/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/hidden/for/security/.rvm/bin:/usr/local/sbin:/usr/sbin:/hidden/for/security/.yarn/bin:/hidden/for/security/.rvm/bin:/hidden/for/security/.yarn/bin:/hidden/for/security/.rvm/bin
    npm verb lifecycle mmap-io@1.1.7~install: CWD: /media/vdb/ucs/client/windows/XUI/node_modules/mmap-io
    npm info lifecycle mmap-io@1.1.7~install: Failed to exec install script
    npm verb stack Error: mmap-io@1.1.7 install: `npm run build-addon`
    npm verb stack Exit status 1
    npm verb stack     at EventEmitter.<anonymous> (/hidden/for/security/.config/nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
    npm verb stack     at EventEmitter.emit (events.js:315:20)
    npm verb stack     at ChildProcess.<anonymous> (/hidden/for/security/.config/nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    npm verb stack     at ChildProcess.emit (events.js:315:20)
    npm verb stack     at maybeClose (internal/child_process.js:1048:16)
    npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    npm verb pkgid mmap-io@1.1.7
    npm verb cwd /media/vdb/ucs/client/windows/XUI
    npm verb Linux 4.19.112-2.el8.x86_64
    npm verb argv "/hidden/for/security/.config/nvm/versions/node/v14.16.0/bin/node" "/hidden/for/security/.config/nvm/versions/node/v14.16.0/bin/npm" "rebuild" "--verbose" "abstract-socket@2.1.1" "ced@1.0.0" "ffi-napi@2.4.7" "mmap-io@1.1.7" "ref-napi@1.4.3" "shmmap@1.0.0" "sleep@6.3.0" "sqlite3@5.0.2"
    npm verb node v14.16.0
    npm verb npm  v6.14.11
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! mmap-io@1.1.7 install: `npm run build-addon`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the mmap-io@1.1.7 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm verb exit [ 1, true ]
    npm timing npm Completed in 18403ms
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /hidden/for/security/.npm/_logs/2022-02-08T08_25_22_126Z-debug.log
                    command=npm rebuild --verbose abstract-socket@2.1.1 ced@1.0.0 ffi-napi@2.4.7 mmap-io@1.1.7 ref-napi@1.4.3 shmmap@1.0.0 sleep@6.3.0 sqlite3@5.0.2
                    workingDir=
  • exited          command=app-builder code=2 pid=20170

please note : **exited          command=app-builder code=2 pid=20170**

so i read some codes about `app-builder` and reachs here:
https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/util/util.go#L110

~~~
func LogErrorAndExit(err error) {
	if execError, ok := err.(*ExecError); ok {
		message := execError.Message
		if len(message) == 0 {
			message = "cannot execute"
		}

		fields := execError.ExtraFields
		fields = append(fields, CreateExecErrorLogEntry(execError)...)
		log.LOG.Error(message, fields...)
		_ = log.LOG.Sync()
		// electron-builder in this case doesn't report app-builder error
		os.Exit(2)
	} else {
		log.LOG.Fatal(fmt.Sprintf("%+v", err))
	}
}
~~~

i think app-builder exit 2 from here.

**2.if i run  `electron-builder install-app-deps` in yarn's  postinstall scripts, no build error !**

yarn's script-shell defaults to /bin/sh, but i can confirm that the problem is not about shell interpreter.

any help appreicated!
