### ISSUE TITLE
not able to build installer/uninstaller: UTF8 vs ASCII (ERR_ELECTRON_BUILDER_CANNOT_EXECUTE)

### ISSUE THREAD

**Issue by khatastroffik** [electron-userland/electron-builder#6235]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 16.8.0

* **Electron Version**: 13.1.9

* **Target**: nsis

## Summary
* **description**: not able to build installer/uninstaller - UTF8 vs ASCII
* **error**: ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
* **env**: windows 10+ (10.0.19043)
* **reproduce**: see below
* **relates to**: #5134

## Cause analysis

when running the builder for the first time, some binaries packages are **downloaded into a cache folder**.
Th folder is usually situated unter the user´s appdata local directory e.g. `C:\Users\<username>\AppData\Local\electron-builder\Cache\nsis\...`

In case the **path** - in particular due to the `<username>` mentioned above - to the cache folder is **containing non-ascii chars** (e.g. utf8 chars), the builder may **fail** at loading some plugins/executing some of the binaries ou of the cache: the path is not correctly interpreted...

it seems, that the builder is capturing the output of the "powershell" environment, which output (stderr) is by default using ascii encoding... which is conflicting with the non-ascii name of the cache path.

## Quick-Fix / temporary **Solution**

set the following environment variable

```shell
set ELECTRON_BUILDER_CACHE=C:\TEMP
```

before running the electron-builder command. When running, the command will download the binaries explicitly to the folder defined in the env variable (ensure the path does not contain any non-ascii char)

## Long-term Fix (potentially)

ensure that the builder code (the VM used by app-builder-lib?) is calling **powershell** with the `-encoding utf8` option.

## How to **reproduce** the issue

set the env variable to point to a path containing non-ascii chars prior running the build command. E.g.:

```shell
set ELECTRON_BUILDER_CACHE=C:\T€ST
```
note the usage of the "€" (Euro currency sign)

**Comment by mattwright324** [comment]
I got a `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` error on my first time building this project though the cache thing above didn't help. The rest of the error said something about symlinks for me and this helped me https://github.com/yarnpkg/berry/issues/278

Running `yarn` in an elevated command prompt fixed my issue.

**Comment by khatastroffik** [comment]
> 
> I got a `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` error on my first time building this project though the cache thing above didn't help. The rest of the error said something about symlinks for me and this helped me [yarnpkg/berry#278](https://github.com/yarnpkg/berry/issues/278)
> 
> Running `yarn` in an elevated command prompt fixed my issue.

Thx for the advice 😉 
Didn't experience that problem, though it's worth mentioning it!
Maybe worth creating another (separate) issue too, if you evalluate this "_symlink problem_" could be fixed by the project team

**Comment by Brouilles** [comment]
Same problem here on Windows.
`set ELECTRON_BUILDER_CACHE=C:\TEMP`, with a new path, don't work for me.
