### ISSUE TITLE
upgrade docker builder to nodejs 14

### ISSUE THREAD

**Issue by renanyoy** [electron-userland/electron-builder#6237]
electron builder needs nodejs 14 now
and the docker builder has only nodejs 12 installed

```
error electron-builder@22.11.7: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.18.3"
```

**Comment by shehi** [comment]
please do this

**Comment by develar** [comment]
For 5 months already we do provide LTS version of Node.JS. We do not update old tags to ensure that your CI will be not failed due to docker image update. Please use or `latest` tag or `electronuserland/builder:14-05.21` `05.21` is the latest update to docker images.

**Comment by shehi** [comment]
@develar , using `wine` tag. Is there `latest` for it?
