### ISSUE TITLE
Windows update failing to install due to file being deleted too early

### ISSUE THREAD

**Issue by Fouzyyyy** [electron-userland/electron-builder#6238]
* **Electron-Builder Version**: 22.9.1

* **Node Version**: 12.13.0

* **Electron Version**: 8.5.2
* **Electron Type (current, beta, nightly)**: current
* **electron-updater Version**: 4.3.5

* **Target**: windows 10

Greetings,

We are experiencing an issue with the updater on windows, we noticed that we get the new executable downloaded, and then right afterwards it gets deleted without the update being installed.

We are using a piece of code for detecting available updates and notify the user if any, it is the one below:

```javascript
import { autoUpdater } from 'electron-updater';
import { RELEASE_CHANNEL } from 'values';

import t from 'utils/strings/translate';

autoUpdater.channel = RELEASE_CHANNEL === 'latest' ? '' : RELEASE_CHANNEL;

const safeUpdateAndNotify = async () => {
  try {
    const { updateInfo } = await autoUpdater.checkForUpdates();

    autoUpdater.checkForUpdatesAndNotify({
      title: '',
      body: `Une nouvelle mise à jour est disponible, ${updateInfo.version}`
    });
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log('Auto-updater failed during checkForUpdatesAndNotify: ', e);
  }
};

export const initializeAutoUpdate = () => {
  safeUpdateAndNotify();

  setInterval(() => {
    safeUpdateAndNotify();
  }, 10 * 60 * 1000);
};
```

Is there anything wrong in our way of using the auto-updater? Could we possible be using it in a wrong way?

**Comment by ezekg** [comment]
I'm pretty sure you're checking for updates twice. Maybe try this:

```diff
-const { updateInfo } = await autoUpdater.checkForUpdates();
-
autoUpdater.checkForUpdatesAndNotify({
  title: '',
- body: `Une nouvelle mise à jour est disponible, ${updateInfo.version}`
+ body: 'Une nouvelle mise à jour est disponible, {version}'
});
```

The `{version}` template variable [will automatically be replaced by electron-builder with the update version](https://github.com/electron-userland/electron-builder/blob/f45110cbf66572d5748d21fc24dc26cabd06f35f/packages/electron-updater/src/AppUpdater.ts#L281-L284).

**Comment by Fouzyyyy** [comment]
Thanks @ezekg for the solution, this seems to be what we need to check for updates and have a notification displayed with the version number.
