### ISSUE TITLE
Build on windows failing with "The batch file cannot be found."

### ISSUE THREAD

**Issue by mcmxcdev** [electron-userland/electron-builder#6241]
* **Electron-Builder Version**: 22.12.1

* **Node Version**: 14.17.6

* **Electron Version**: 13.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: https://github.com/getferdi/ferdi/blob/develop/electron-builder.yml

We are in the process of switching from npm 6 to pnpm, linux and macOS builds are working fine already, but windows is failing with a cryptic error that I can not understand: https://github.com/getferdi/ferdi/pull/1826/checks?check_run_id=3544723264

Is this `electron-builder` related?

**Comment by vraravam** [comment]
Bump - any update on this please?

**Comment by vraravam** [comment]
Any update on this please? We are completely blocked from upgrading to `pnpm` due to this bug.

**Comment by tomaszferens** [comment]
@vraravam any ideas if pnpm now works with electron-builder? The last time I check (~year ago) the error was still present
