### ISSUE TITLE
dmg-license incompatible error when building on Linux

### ISSUE THREAD

**Issue by Webreaper** [electron-userland/electron-builder#6243]
* **Electron-Builder Version**: 22.11.11

* **Node Version**: v14.17.6

* **Electron Version**: 14.0.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: MacOS, Linux, Windows

I'm running a cross-platform build on MacOS, Linux and Windows. It's running in GitHub actions, and each platform builds on a runner using its own OS (so Linux builds on Ubuntu, MacOS builds on Mac, and Windows builds on Windows). 

My build has been fine using electron v11.0.0 and electron-builder v22.11.4. However, upgrading to electron v14, with the same version of electron-builder or newer, and I get this:

```
*** Building Electron Desktop app for linux...
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info dmg-license@1.0.9: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.6: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 18.25s.
yarn install v1.22.11
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
yarn version v1.22.11
info Current version: 1.7.7
info New version: 2.2.1
error Command failed.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
Exit code: 128
```

Now, I've seen issues saying that the `platform "linux" is incompatible with this module` error is because you have to build on linux - but I am building on linux. So I don't understand why dmg-licence is being pulled in as a dependency at all (my app doesn't use it...). 

The MacOS version builds just fine on MacOS.

I can workaround it by reverting back to Electron v11, but that's not ideal. Any ideas how to fix?

Sample build here: https://github.com/Webreaper/Damselfly/runs/3550094307?check_suite_focus=true#step:4:1

**Comment by mhatvan** [comment]
I also remember experiencing this issue.

Seems it will be fixed in the next release by: https://github.com/electron-userland/electron-builder/pull/6244

**Comment by Webreaper** [comment]
Got it, thanks.

**Comment by mmaietta** [comment]
Please try the newest `next` release 22.14.2

**Comment by Webreaper** [comment]
Looks better, thanks
