### ISSUE TITLE
u2f-devices is not a recognized plugs value for snap

### ISSUE THREAD

**Issue by mcmxcdev** [electron-userland/electron-builder#6246]
Electron-Builder Version: 22.12.1
Node Version: 14.17.6
Electron Version: 13.3.0
Electron Type (current, beta, nightly): current
Target: snap

According to https://snapcraft.io/docs/supported-interfaces, `u2f-devices` is a supported value for `plugs`. 

When using a CLI configuration like `electron-builder ... "-c.snap.plugs=['default', 'u2f-devices']"`, it crashes due to invalid configuration: https://github.com/getferdi/ferdi/runs/3551218989?check_suite_focus=true

What is the correct way to pass plugs as CLI argument?

**Comment by vraravam** [comment]
bump - can this be prioritized please?
