### ISSUE TITLE
There maybe a url error when downloading

### ISSUE THREAD

**Issue by nothatDinger** [electron-userland/electron-builder#6249]
![image](https://user-images.githubusercontent.com/52913141/132931201-4e04f3ce-1207-4a57-9539-9dbeeb22b7a5.png)
I use npm run electron:build to build my electron project but meet this error.
The url in photo is not exist in github, but I found the new url of the zip (https://github.com/electron/electron/releases/tag/v14.0.0/electron-v14.0.0-win32-x64.zip)

**Comment by mmaietta** [comment]
What's the project setup for this? I don't recognize the functionality

**Comment by nothatDinger** [comment]
I mean the program may download a zip file from github through a wrong url which I underlined in the photo

**Comment by mmaietta** [comment]
No, I meant what's your electron-builder config setup

Anyways, I tracked down the issue, it's basically this https://github.com/develar/app-builder/issues/57
URL is coming from here: https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/electron/electronDownloader.go#L100
