### ISSUE TITLE
[object Object] Error when attempting to compile on Linux

### ISSUE THREAD

**Issue by brendon-gonzalez** [electron-userland/electron-builder#6252]
* **Electron-Builder Version**:  22.13.1

* **Node Version**: 14.17.4

* **Electron Version**: 13.1.9
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Linux, `tar.gz`

We are currently attempting to build a `tar.gz` file using Electron Builder and running into an unknown error that provides little explanation as to what is wrong. I am looking for suggestions on how to get a better/more verbose error during this build process. Here is the output

```
INFO: Running command line: bazel-bin/experimental/scout/core/electronINFO: Build completed successfully, 1 total action
  • electron-builder  version=22.13.1 os=5.4.0-1054-aws
  • loaded configuration  file=/home/brendon/.cache/bazel/_bazel_brendon/7f219bcfe2b61979e9e57fd12dfee725/execroot/__main__/bazel-out/k8-opt/bin/experimental/scout/core/electron-builder.json
  • writing effective config  file=/home/brendon/.cache/bazel/_bazel_brendon/7f219bcfe2b61979e9e57fd12dfee725/execroot/__main__/bazel-out/k8-opt/bin/experimental/scout/core/out/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=13.1.9 appOutDir=/home/brendon/.cache/bazel/_bazel_brendon/7f219bcfe2b61979e9e57fd12dfee725/execroot/__main__/bazel-out/k8-opt/bin/experimental/scout/core/out/linux-unpacked
  • building        target=tar.gz arch=x64 file=/home/brendon/.cache/bazel/_bazel_brendon/7f219bcfe2b61979e9e57fd12dfee725/execroot/__main__/bazel-out/k8-opt/bin/experimental/scout/core/out/aurora-scout-0.1.0.tar.gz
  ⨯ [object Object]
```

A few things to note. We are using bazel as a build system as per our mono repo's requirements. We do have to use the `--projectDir` flag when we run this as bazel does run this two folders away, but as you can see, it successfully creates the unpacked versions, just not the `tar.gz` we are expecting.

Any advice would be greatly appreciated here.

**Comment by mmaietta** [comment]
Can you please run with `DEBUG=electron-builder` env var set?

**Comment by brendon-gonzalez** [comment]
Hey there. We deep dove into this issue on our end and found it was a result of `fs` Failing to set up a temp directory. Though when running with debug, the only additional info we picked up was that an asynchronous task failed with `false`. I’m going to close this issue as I don’t think it’s directly related to builder.

**Comment by pgherveou** [comment]
@brendon-gonzalez  do you mind sharing which task is failing with `false` ? I am also seeing this on our project. Ideally we can come up with a Patch that spit an error a bit more useful 😅
