### ISSUE TITLE
Code signing DLL files

### ISSUE THREAD

**Issue by ncortines** [electron-userland/electron-builder#6255]
* **Electron-Builder Version**: 21.2.0

* **Node Version**: 9.1.0

* **Electron Version**: 6.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32

Hi!

I have a few .DLL files which are packaged together with the main .EXE file and are left unsigned.

In my case, these files are: ffmpeg.dll, libeay32.dll, libEGL.dll, libGLESv2.dll and sqlite3.dll.

I think that ffmpeg.dll, libEGL.dll, and libGLESv2.dll are Chromium and Node dependencies, whereas sqlite3.dll, libeay32.dll are dependencies of one of our dependencies.

Is there a reason why electron-builder ignores unsigned .DLL files, even those which are direct Electron dependencies?

Is there a way to include them in the code signing process?

Thanks!
Juan

**Comment by ncortines** [comment]
I have posted the question in https://stackoverflow.com/questions/69174622/code-signing-dll-files-with-electron-builder.
Sorry for posting questions in here.

**Comment by paragdulam** [comment]
I am facing the same issue. **I have set signDlls to true in my package.json.**

electron-builder: 23.3.3
electron: 20.1.4
node: 14.17.4
npm: 6.x

I primarily care about the electron, chromium and node related dlls to code-sign using the certificate I provide. I have CSC_LINK and CSC_LINK_PASSWORD set as well. My setup.exe and main executable gets code signed as well. Its just the dlls like ffmpeg.dll, libEGL.dll, and libGLESv2.dll are not getting code signed. 

Thanks in advance.

**Comment by paragdulam** [comment]
Please ignore above comment. I have multiple build variants in the app. Hence its the other json file that electron-builder refers from.  Added correct keys in that file. Worked like a charm!!
