### ISSUE TITLE
GLIBC change between 22.10.5 & 22.13.0

### ISSUE THREAD

**Issue by umerkk** [electron-userland/electron-builder#6256]
* **Target**: Linux => CentOS 7

We recently upgraded to Electron 13 and CentOS 7 is among our supported Linux versions. It looks like the `Electron-Builder` version (22.10.5) we were using to build Electron 11 was using the correct & standard `GLIBC & GLIBCXX` versions that CentOS support out of the box.
But after the upgrade of `Electron-Builder` to version 22.13.0, it seems like it is (or a dependency) is using a newer version of `GLIBC & GLIBCXX` that is not compatible with CentOS out fo the box and require users to update their GCC & Glibc (which isn't ideal).

I would like to ask, is there a specific change that resulted in this usage of newer versions or is it a side effect?

I can still build Electron 13 using the older electron-builder version, so it seems imminent that Electron 13 is not relying on the new GLIBC, there is something happening in Electron-Builder which is causing this problem.

The normal error we get in Terminal logs are "GliBCXX is not found" when we run the app built using a newer electron-builder' version.

Any help here would be apprecaited/

**Comment by aspyk** [comment]
@umerkk I've got the same kind of issue, did find any solution or workaround for it ? Thank you !
