### ISSUE TITLE
Need to remove keys from from Credential Vaul/Key Chain when the app is uninstalled

### ISSUE THREAD

**Issue by augustnmonteiro** [electron-userland/electron-builder#6262]
We save some passwords into the credential Vaul/Key Chain when the user log in.
When uninstalling the app we need to be able to remove those keys.

* **Electron-Builder Version**: 

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:

**Comment by mmaietta** [comment]
What OS is this for?

**Comment by augustnmonteiro** [comment]
Windows, I'm using a keytar to save to credential vault, I would need to run a script during uninstall to remove them.

**Comment by mmaietta** [comment]
Looks like you can customize the uninstall script phases: `customRemoveFiles` and `customUnInstall`
www.electron.build/configuration/nsis.html#custom-nsis-script

**Comment by darshitshah8** [comment]
this link is no longer available i think, i want to remove keytar value, when i uninstall my msi application , did you have any other reference

**Comment by mmaietta** [comment]
https://www.electron.build/nsis.html#custom-nsis-script
