### ISSUE TITLE
Deactivate blockmap generation

### ISSUE THREAD

**Issue by arnegroskurth** [electron-userland/electron-builder#6267]
* **Electron-Builder Version**: 22.10.5
* **Node Version**: 10.19.0
* **Electron Version**: 12.0.7
* **Electron Type (current, beta, nightly)**: current
* **Target**: dmg

This is a feature request to finally officially support control over of the generation of dmg blockmaps (and similar formats) as it is often not used but its generation has a major impact on runtime (5 minutes vs 50 minutes).

An option for that has already been implemented for faster test-case execution (https://github.com/electron-userland/electron-builder/blob/f4c2a19778c6d95c98fd018b2c7397b77b91f31d/packages/app-builder-lib/src/options/macOptions.ts#L254) but is currently marked as `@private`. So this appears to be about documentation only.

This has already been filed as an issue multiple times: #2900 #2972

Update: The blockmap-generation runs for more than an hour in our (private) CI-pipeline with GitHub Actions which would pretty quickly eat up our whole monthly quota in just a few jobs. So far we have always aborted the run an never saw it complete. For some reason we are also unable to de-activate the generation with the mentioned (undocumented) option - but as we are currently not able to test this offline on a mac, that error might be on our side.

**Comment by mmaietta** [comment]
Can you try this approach? https://github.com/electron-userland/electron-builder/issues/2900#issuecomment-730571696

**Comment by arnegroskurth** [comment]
Sure but for some reason that option does (currently?) not seem to have an effect. (See update above)
