### ISSUE TITLE
Signing with timestamp

### ISSUE THREAD

**Issue by kasrak** [electron-userland/electron-builder#627]
Is there a way to pass the `/t` param to signcode when generating the Windows installer?

**Comment by develar** [comment]
We already do that. What's wrong?

**Comment by kasrak** [comment]
Ah, sorry—I meant the `/tr` param to specify the timestamp server.

I'm using the `CSC_LINK` and `CSC_KEY_PASSWORD` environment variables to code sign on Windows, but couldn't figure out how to specify a timestamp server (e.g. `signtool sign /tr http://timestamp.digicert.com [...]`)

**Comment by develar** [comment]
Will be `win.rfc3161TimeStampServer`
