### ISSUE TITLE
Building for arm64 Macs fails with 404 error

### ISSUE THREAD

**Issue by xvaultwallet** [electron-userland/electron-builder#6274]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.17.6

* **Electron Version**:1.6.2
* **Electron Type (current, beta, nightly)**:LTS

* **Target**: Mac pkg x64 arm64

Building for arm64 fails with the following error
⨯ cannot resolve https://github.com/electron/electron/releases/download/v1.6.2/electron-v1.6.2-darwin-arm64.zip: status code 404

**Comment by neoxpert** [comment]
Electron 1.6.2 was released in March 2017. I don't think that there will be a build of such an old version for a platform that was released in November 2020. I fear you have to switch to a more recent version of Electron.
