### ISSUE TITLE
how to use asar.createPackageWithOptions make a custom transform?

### ISSUE THREAD

**Issue by zhiying8710** [electron-userland/electron-builder#6278]
* **Electron-Builder Version**: 22.10.4

* **Node Version**: 11.15.0

* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current

none

* **Target**: 
win32

`asar.createPackageWithOptions` 's last argument can have a transform function to do something before file pack into asar package, how can i use this feature in `electron-builder`?

**Comment by mmaietta** [comment]
electron-builder has an alternative hook, `beforePack` that I think you could use. Have you tried that out yet?
https://jolly-roentgen-9c9aba.netlify.app/configuration/configuration.html#beforepack
