### ISSUE TITLE
Users getting SmartScreen Filter on install

### ISSUE THREAD

**Issue by sklink** [electron-userland/electron-builder#628]
* **Version**:  5.21.0

* **Target**: Windows x64

After running `npm run dist` which calls `build` I go ahead and manually code sign the `.exe` found in the `dist\win` folder. Following that I check that the file has been signed correctly like this:
`signtool.exe verify /pa my-app-1.0.0.exe` 

It confirms that the file is signed correctly.

However, when I publish a release to `Nuts` with the `.nupkg` files for Squirrel, my users are getting the SmartScreen filter show up, sometimes killing the installation all together.

My first thought is that it's the `.exe`'s packaged within. This indicated by the **Unknown Publisher** tag Windows gives to `Update.exe`--I believe that belongs to the Squirrel piece.

What am I doing wrong here?

I haven't been able to get a CI to work because one of my native node modules is finicky to build.

**Comment by develar** [comment]
You cannot sign manually after electron-builder. Number of files must be signed, not only resulting exe, and some files packed in the archive. So, let's solve issue why you cannot sign using electron-builder.

**Comment by sklink** [comment]
I'm sure I can, I just cannot use a CI. Is there a way to sign locally when running `npm run dist`?

**Comment by develar** [comment]
The same way as on CI. Please attach code sign error and I will try to help you.

**Comment by sklink** [comment]
I haven't even tried locally. I'm assuming I just need to set those environment variables listed here then?

https://github.com/electron-userland/electron-builder/wiki/Code-Signing

This is my `build` configuration: (I replaced the names with generic ones)

```
{
    "appId": "com.myapplication.myapp",
    "asar": false,
    "productName": "MyApplication",
    "win": {
      "iconUrl": "https://mysite.com/img/favicon.ico",
      "remoteReleases": "https://github.com/my-company/my-project"
    }
  }
```

And the `dist` script simply calls `build`.

**Comment by sklink** [comment]
I spoke with someone at DigiCert about this and they mentioned that an EV certificate is required to bypass SmartScreen filter. Are you familiar with that requirement?

**Comment by develar** [comment]
> I'm assuming I just need to set those environment variables listed here then?

Yes.

**Comment by sklink** [comment]
> SignTool Error: An unexpected internal error has occurred.
> Error: C:\Users\Matt\.cache\winCodeSign\winCodeSign-1.0.0\windows-10\signtool.exe exited with code 1
>     at ChildProcess.childProcess.on.code (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\util.ts:132:14)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:850:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> From previous event:
>     at Object.spawn (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\util.ts:109:9)
>     at D:\dev\myapp\overlay\build\node_modules\electron-builder\src\windowsCodeSign.ts:101:21
>     at next (native)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback] (timers.js:523:5)
> From previous event:
>     at tsAwaiter (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\awaiter.ts:10:47)
>     at Object.build (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\builder.ts:195:52)
>     at Object.<anonymous> (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\build-cli.ts:27:28)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)
>     at Function.Module.runMain (module.js:575:10)
>     at startup (node.js:160:18)
>     at node.js:445:3

**Comment by develar** [comment]
@sklink Please set env `DEBUG=electron-builder` and attach log here.

**Comment by sklink** [comment]
> electron-builder Found existing nsis C:\Users\Matt\.cache\nsis\nsis-3.0.0 +0ms
> electron-builder Spawning C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js rebuild --production +47ms
> Rebuilding app dependencies for arch x64 to D:\dev\myapp\overlay\build\app
> 
> npm WARN prefer global node-gyp@3.4.0 should be installed with -g
> npm WARN prefer global node-ninja@1.0.2 should be installed with -g
> electron-builder C:\Program Files\nodejs\node.exe (15200) exited with code 0 +17s
> electron-builder null +10ms
> Packaging for platform win32 x64 using electron 1.3.1 to dist\win-unpacked
> 
> Signing MyApp.exe (certificate file "/D:/dev/myapp/signing/overlay-new.pfx")
> electron-builder Found existing winCodeSign C:\Users\Matt\.cache\winCodeSign\winCodeSign-1.0.0 +47s
> electron-builder Spawning C:\Users\Matt\.cache\winCodeSign\winCodeSign-1.0.0\windows-10\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f /D:/dev/myapp/signing/overlay-new.pfx /d MyApp /p pass D:\dev\myapp\overlay\build\dist\win-unpacked\MyApp.exe +4ms
> SignTool Error: An unexpected internal error has occurred.
> Error: C:\Users\Matt\.cache\winCodeSign\winCodeSign-1.0.0\windows-10\signtool.exe exited with code 1
>   at ChildProcess.childProcess.on.code (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\util.ts:132:14)
>   at emitTwo (events.js:106:13)
>   at ChildProcess.emit (events.js:191:7)
>   at maybeClose (internal/child_process.js:850:16)
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> From previous event:
>   at Object.spawn (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\util.ts:109:9)
>   at D:\dev\myapp\overlay\build\node_modules\electron-builder\src\windowsCodeSign.ts:101:21
>   at next (native)
>   at tryOnImmediate (timers.js:543:15)
>   at processImmediate [as _immediateCallback] (timers.js:523:5)
> From previous event:
>   at tsAwaiter (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\util\awaiter.ts:10:47)
>   at Object.build (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\builder.ts:195:52)
>   at Object.<anonymous> (D:\dev\myapp\overlay\build\node_modules\electron-builder\src\build-cli.ts:27:28)
>   at Module._compile (module.js:541:32)
>   at Object.Module._extensions..js (module.js:550:10)
>   at Module.load (module.js:456:32)
>   at tryModuleLoad (module.js:415:12)
>   at Function.Module._load (module.js:407:3)
>   at Function.Module.runMain (module.js:575:10)
>   at startup (node.js:160:18)
>   at node.js:445:3

Could it be the verisign timestamp? I have a DigiCert certificate.

**Comment by develar** [comment]
> Could it be the verisign timestamp? I have a DigiCert certificate.

No, it is just timestamp server.

Could you please specify your windows version? And execute manually

```
signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f /D:/dev/myapp/signing/overlay-new.pfx /d MyApp /p pass D:\dev\myapp\overlay\build\dist\win-unpacked\MyApp.exe

```

to ensure that you get the same error in terminal. If command ok, please try execute again using `C:\Users\Matt.cache\winCodeSign\winCodeSign-1.0.0\windows-10\signtool.exe`

**Comment by sklink** [comment]
This is the error I get:
> SignTool Error: An unexpected internal error has occurred.
> Error information: "Error: Store IsDiskFile() failed." (-2147024773/0x8007007b)

When I change this it works:
`/f /D:/dev/myapp/signing/overlay-new.pfx` to `/f "D:/dev/myapp/signing/overlay-new.pfx"`

This was with both signtool.exe's, i.e.:
`C:\Users\Matt\.cache\winCodeSign\winCodeSign-1.0.0\windows-10\signtool.exe`

**Comment by develar** [comment]
How did you specify `CSC_LINK`? Must be `CSC_LINK=file://D:/dev/myapp/signing/overlay-new.pfx`

**Comment by sklink** [comment]
Wow. Yep, there was an extra slash in there... embarassing. 

Thank you for all your help, I really appreciate it!

**Comment by develar** [comment]
Proposed fix:

* Investigate why `Error information: "Error: Store IsDiskFile() failed." (-2147024773/0x8007007b)` is not printed as part of error message
* Auto-fix *** windows urls, support *** windows paths (without `file://`).

**Comment by develar** [comment]
> Investigate why Error information: "Error: Store IsDiskFile() failed." 

Done.

**Comment by develar** [comment]
File path is supported in the CSC_LINK (10.1.0).
