### ISSUE TITLE
Uninstaller should remove ALL files, including the installer.exe in the updater directory.

### ISSUE THREAD

**Issue by gfrung4** [electron-userland/electron-builder#6283]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.16.0

* **Electron Version**: 10.4.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32

Using the NSIS installer to install and run my project, files are created in:

Location | Path
------------ | -------------
Program Files | `%LOCALAPPDATA%\Programs\project-name`
Runtime Data | `%APPDATA%\project-name`
"Updater" | `%LOCALAPPDATA%\project-name-updater`

The uninstaller removes the first of these directories by default, and I can use the `deleteAppDataOnUninstall` [configuration option](https://www.electron.build/configuration/nsis) to delete the second, but I have not yet found any way to delete the "updater" directory.  The uninstaller leaves it behind, and it contains a large executable (seemingly the entire installer, which can be used later to re-install the program).

It is my belief that uninstallers should remove any and all remnants of a program, and leaving anything behind is a bug.  How can I ensure the uninstaller removes *everything*, even that pesky "updater" directory?

**Comment by minht11** [comment]
This should be reopened because it is still relevant.

**Comment by yssmile** [comment]
add include
`"nsis": {
      "createDesktopShortcut": "always",
      "include": "./build/include.nsh"
    },`
in include.nsh
`
!macro customUnInit
  RMDir /r "$PROFILE\AppData\Local\yourprojectname-updater"
!macroend
`

**Comment by harmonikas996** [comment]
Still relevant. For now, I'm manually deleting these, but it should be automatically done.
