### ISSUE TITLE
electron-publish fails behind proxy server

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#6286]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.17.3

* **Electron Version**: 14.0.1
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater Version**: 4.3.9

* **Target**: AppImage, NSIS, DMG/ZIP

I have forked the electron-updater-example and updated it to use current versions and include MacOS code-signing.  You can find the repo at [Electron Updater Example](https://github.com/robertpatrick/electron-updater-example/).

After publishing artifacts for MacOS and Linux (so far), the MacOS app seems to work fine from inside of our corporate network (which requires the use of a proxy server to reach the Internet).  

![MacOS](https://user-images.githubusercontent.com/31662131/134784247-3fabc3c9-867d-433e-b639-e29d36ad638d.png)

The AppImage version of the app is failing while trying to check for updates inside our corporate network.

![AppImage](https://user-images.githubusercontent.com/31662131/134784239-607d392d-07ac-4866-a00d-bec3c02d3d2a.png)

What am I missing?  curl and firefox are able to find github.com without issue.  How do I get electron-updater to use our proxy server on Linux?

**Comment by robertpatrick** [comment]
It seems clear that the mechanisms used by electron-updater clearly can work with a proxy server.  The real issue is a lack of documentation on how to configure the autoUpdater to use a proxy.

**Comment by robertpatrick** [comment]
By the way, the publish step also seems to require additional configuration to work with the proxy server...

**Comment by mmaietta** [comment]
I'm not familiar with how the `--proxy-server` arg works but I did a quick dive into the code and am curious if this is what you're looking for?
https://github.com/electron-userland/electron-builder/blob/8ebfc96276bffe0bc1ad394c5ae6843976e01709/packages/electron-updater/src/electronHttpExecutor.ts#L52-L57
Is it possible to add a `Host` to your headers for electron-updater?

**Comment by robertpatrick** [comment]
Thanks, --proxy-server does allow me to get past the Checking for Updates issue on Linux.  

The remaining problem is how to get `electron-builder -p` publishing to use the proxy server.  Currently, it doesn't work on any platform from behind a proxy server.  Any hints?

**Comment by mmaietta** [comment]
@robertpatrick would you be willing to provide any console logs with `DEBUG=electron-builder` set?
Trying to figure out where the publishing process fails. We currently handle all redirects manually, I think it's a requirement for all GitHub/s3 requests, not sure if that is being impacted by your proxy.

**Comment by robertpatrick** [comment]
@mmaietta I am willing to share this output with you directly but I am hesitant to put it on GitHub for all to see due to concerns about exposing sensitive information.  If you want to send me an email to robert (dot) patrick at oracle (dot) com, I will send them to you.  If you have some other way in which you would prefer me sharing this data, just let me know...

**Comment by robertpatrick** [comment]
@mmaietta OK, here is the output from my Windows machine (since it doesn't contain any sensitive info):
[electron-builder-DEBUG.txt](https://github.com/electron-userland/electron-builder/files/7286362/electron-builder-DEBUG.txt)

**Comment by mmaietta** [comment]
I found this, would this help with routing? Allows you to specify a dedicated host. Perhaps you could route it internally to reach github? Might be a potential workaround, but just a shot in the dark.
https://github.com/electron-userland/electron-builder/blob/286d76818f2ed2245774b50a440d7777bb7db0b5/packages/electron-publish/src/gitHubPublisher.ts#L259-L261
https://github.com/electron-userland/electron-builder/blob/286d76818f2ed2245774b50a440d7777bb7db0b5/packages/builder-util-runtime/src/publishOptions.ts#L96-L100
I'm not familiar without how to set up a debug environment for this.  This is the first time I've read of a proxy not working tbh

**Comment by robertpatrick** [comment]
In looking at the `electron-update` package (that generally seems to work with the OS system proxy and --proxy-server argument), the main difference is that `electron-update` seems to use the [electron.net](https://www.electronjs.org/docs/api/net) API while `electron-publish` is using the Node.js [https](https://nodejs.org/api/https.html) or [http](https://nodejs.org/api/http.html) APIs directly (without accounting for any required proxy configuration).

**Comment by baparham** [comment]
> For example, this code below is an example of one of the places `electron-publish` would need to change to make this work properly (assuming you wanted to get the proxy information from one of the standard environment variables). Unfortunately, there are other places that would also need to change since not all paths use githubRequest(); for example, doUploadFile().
> 
> ```js
>     const HttpsProxyAgent = require('https-proxy-agent');
>     ...
>     githubRequest(path, token, data = null, method) {
>         // host can contains port, but node http doesn't support host as url does
>         const baseUrl = url_1.parse(`https://${this.info.host || "api.github.com"}`);
>         const options = {
>             hostname: baseUrl.hostname,
>             port: baseUrl.port,
>             path: this.info.host != null && this.info.host !== "github.com" ? `/api/v3${path.startsWith("/") ? path : `/${path}`}` : path,
>             headers: { accept: "application/vnd.github.v3+json" },
>         };
>         
>         const proxy = process.env.HTTPS_PROXY || process.env.HTTP_PROXY;
>         if (proxy) {
>             options.agent = new HttpsProxyAgent(proxy);
>        }    
>         return builder_util_runtime_1.parseJson(nodeHttpExecutor_1.httpExecutor.request(builder_util_runtime_1.configureRequestOptions(options, token, method), this.context.cancellationToken, data));
>     }
> ```

From following through these code paths, it appears that all of these places end up using `NodeHttpExecutor` from `builder-util` at the low level to perform the request, so the fix in #6410 would cover these cases as well.

**Comment by robertpatrick** [comment]
@baparham That makes sense.  I chimed in on your PR so hopefully it will be merged!

**Comment by mmaietta** [comment]
Released in 22.14.7
