### ISSUE TITLE
Dependencies are not packaged by electron-builder when using pnpm

### ISSUE THREAD

**Issue by Ripwords** [electron-userland/electron-builder#6289]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 16.9.1

* **Electron Version**: 15.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows/nsis

I'm having issues trying to use pnpm and electron-builder. I tried multiple times to package the app using basic commands and build configurations from online guides but i would always get dependency related errors after packaging it.

Initially i thought it was my configuration error, but after copying the whole project and used npm instead, everything worked as expected.

From what i could find, it seems that electron-builder can't resolve the dependencies within the .pnpm folder, but i am not 100% certain of this.

pnpm and electron-builder are both great would love to have this fixed

### Build config
![image](https://user-images.githubusercontent.com/58784686/134793881-c4232013-78a2-4378-9f39-70a777c5b5c3.png)
<br>
### Using pnpm 
As shown in the screenshot, semver already exist in node_modules/.pnpm
![image](https://user-images.githubusercontent.com/58784686/134793796-2ddad351-90e8-418f-8a8d-3df463e48e1c.png)
<br>
### Using npm with same exact build config
Application is built with no errors by electron-builder
![image](https://user-images.githubusercontent.com/58784686/134793941-d07778c6-3dfd-4a9b-97a3-93af49157cb0.png)

**Comment by mmaietta** [comment]
@develar can you please take a look at this when you have a chance?

**Comment by cangzhang** [comment]
Run into same problem, the `node_modules` folder bundled in `app.asar` does not have modules installed in `.pnpm/`

**Comment by mervinjin** [comment]
Any updates?

**Comment by cah4a** [comment]
Hey guys!
Do you have any plans to support pnpm?
It reduces pain for developers that have gigabytes of `node_modules` placed here and there.
Would love to use it with electron too.

**Comment by mmaietta** [comment]
I don't have plans to implement the support for pnp. But I'd happily review PRs for it! 🙂

**Comment by cupcakearmy** [comment]
Same here, would be awesome to have support for it

**Comment by mmaietta** [comment]
Quick test, can someone try setting `.npmrc` to copy from the global pnpm store for deps?
https://pnpm.io/npmrc#package-import-method
```
package-import-method=copy
```

**Comment by monsterkodi** [comment]
I tried the `copy` setting. But doesn't seem to make any difference for me.

**Comment by mmaietta** [comment]
@develar really could use your help on this one. Seems to be failing with `readDependencyTree` in your `app-builder` project.
https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/node-modules/tree.go#L41

I've tried other alternatives for reading dependency trees and they aren't viable. I'm not sure how app-builder works, but it seems like it just needs to also search `node_modules/.pnpm/node_modules/*` for all dependencies

**Comment by BlackHole1** [comment]
* set `node-linker=hoisted` in .npmrc
* set ` public-hoist-pattern = *` or `hamefully-hoist = true` in `.npmrc`

Choose any of them. The problem will be solved.
Of course, it would be great if electron-builder could support it.

**Comment by CallanBi** [comment]
Same. Would really love to see it is supported.

**Comment by the0rem** [comment]
@BlackHole1 thanks for the suggested solution. This is probably an acceptable solution for some however the suggested approach is basically throwing away the benefits of using pnpm in the first place.

The repo's readme also links to a comment about [why yarn should be used](https://github.com/electron-userland/electron-builder/issues/1147#issuecomment-276284477) however with 129 downvotes and 94 confused emojis it's clearly not backed by the community running into these issues.

I'm not able to provide a better solution myself but I'd like to point out how much of a hurdle this is for adoption. We're not prepared to relax the reliability of our dependency system that pnpm brings to our monorepo. Changing this for a single package is an unreasonable ask. I hope there is a path forward soon; A fundamental library shouldn't have to compromise it's audience based on a package manager.

**Comment by cah4a** [comment]
Any progress here?

**Comment by mmaietta** [comment]
Issue is in upstream dependency app-builder (node_modules/app-builder-bin)
Ref: https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1033243907
You're welcome to file a ticket here https://github.com/develar/app-builder

Workaround is: https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422
