### ISSUE TITLE
System hangs on "install-app-deps"

### ISSUE THREAD

**Issue by makeitcount** [electron-userland/electron-builder#629]
* **Version**: 5.20.0

* **Target**: ubuntu, windows, mac

> package.json
{
  "name": "testingelectron",
  "productName": "testingelectronbuild",
  "version": "0.0.1",
  "repository": "user/repo",
  "author": {
    "name": "Pradeep Sharma"
  },
  "scripts": {
    "test": "xo",
    "start": "electron .",
    "postinstall": "install-app-deps",
    "pack": "build --dir",
    "dist": "build",
    "build_with_epackager": "electron-packager . --out=dist --app-version=$npm_package_version --icon=./assets/img/icon --prune --asar --overwrite --all"
  },
  "files": [
    "index.js",
    "index.html",
    "index.css"
  ],
  "keywords": [
    "electron-app",
    "electron"
  ],
  "dependencies": {
    "electron-debug": "^1.0.0"
  },
  "devDependencies": {
    "devtron": "^1.1.0",
    "electron-packager": "^7.0.0",
    "electron-prebuilt": "^1.0.1",
    "electron-builder": "latest",
    "xo": "^0.15.0"
  },
  "xo": {
    "esnext": true,
    "envs": [
      "node",
      "browser"
    ]
  }

**I run `npm install` on my system which ubuntu 14.04 os, has Node v4.4.7. And then system hangs. There is nothing in npm-debug.log.**

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/376#issuecomment-236672418 Is it your case?

**Comment by makeitcount** [comment]
Ok. How do we set up 'two package.json structure'. And how does it work (we need make different node_modules for development/production?)?

**Comment by develar** [comment]
You only need two package.json structure if you have native modules. Otherwise you don't need to use it.

**Comment by makeitcount** [comment]
will need to integrate native modules. So I would create two package.json. and will keep 
`"postinstall": "install-app-deps"`.  One at the root and another one inside app folder.
I suppose I would need to **modify postintall** as well to install the second package dependency as well  like this `"postinstall": "install-app-deps && cd app && npm install"`

**Comment by develar** [comment]
> I suppose I would need to **modify postintall** as well to install the second package dependency as well  like this `"postinstall": "install-app-deps && cd app && npm install"`

No. `install-app-deps` automatically detects app directory and install dependencies. You should use `postinstall` script exactly as in docs.

**Comment by makeitcount** [comment]
Creating two package.json worked. Thanks @develar.
