### ISSUE TITLE
ENOENT: no such file or directory, symlink

### ISSUE THREAD

**Issue by zjy369** [electron-userland/electron-builder#6290]
ENOENT: no such file or directory, symlink '../is-ci/bin.js' -> '/Users/macpack/Desktop/build/3/mac/mac-universal--x64/Electron.app/Contents/Resources/app/node_modules/update-notifier/node_modules/.bin/is-ci'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, symlink '../is-ci/bin.js' -> '/Users/macpack/Desktop/build/3/mac/mac-universal--x64/Electron.app/Contents/Resources/app/node_modules/update-notifier/node_modules/.bin/is-ci'
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at Object.copyAppFiles (/Users/macpack/Desktop/node_modules/app-builder-lib/src/util/appFileCopier.ts:85:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

electron 11.0.0
electron-builder 22.11.11
osx 11.6
xcode 13.0

**Comment by zjy369** [comment]
Try working normally until electron- Builder 22.10.5

**Comment by zjy369** [comment]
builder-debug.yml     - '!**/node_modules'


x64:
  firstOrDefaultFilePatterns:
    - '**/*'
    - '!**/node_modules'
    - '!build{,/**/*}'
    - '!build/3/mac{,/**/*}'
    - '!**/*.{iml,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,suo,xproj,cc,d.ts,pdb}'
    - '!**/._*'
    - '!**/electron-builder.{yaml,yml,json,json5,toml}'
    - '!**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.flowconfig,.jshintrc,.eslintrc,.circleci,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,appveyor.yml,.travis.yml,circle.yml,.nyc_output}'
    - '!.yarn{,/**/*}'
    - '!.editorconfig'
    - '!.yarnrc.yml'

**Comment by 50calDhruv** [comment]
How was this issue resolved? I'm also facing a similar issue. When trying to put the .bin dir from node_modules into the extra resources I get the error:

ENOENT: no such file or directory, stat '/private/var/folders/jd/q6l4k9dd19gbr5cb03y9czlh0000gn/T/electron-universal-AEIPoS/Tmp.app/Contents/Resources/node_modules/.bin/acorn' failedTask=build stackTrace

The .bin folder contains symlinks.

**Comment by Valeaal** [comment]
To copy the node_modules folder on your .app, in the package.json:
 "files": [
      [...],
      {
        "from": "[...]/node_modules",
        "to": "[...]/node_modules",
        "filter": [
          "**/*",
          "!**/.bin/**"
        ]
      },
      {
        "from": "[...]/node_modules/.bin",
        "to": "[...]/node_modules/.bin"
      }
    ],

make sure to copy .bin in the end, if not, you'll receive the error "ENOENT: no such file or directory, symlink", at least on electron-builder 23.6
