### ISSUE TITLE
App installer detected as HEUR: `Trojan-PSW.Win32.Stealer.gen`

### ISSUE THREAD

**Issue by juanmartin** [electron-userland/electron-builder#6294]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.2.0

* **Electron Version**: 14.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS and Windows

Hi
Our application installer is being detected as `Trojan-PSW.Win32.Stealer.gen` by Kaspersky software only on Windows.
Ran VirusTotal over the installer and the only one which detects this is Kaspersky.
Installed Kaspersky Internet Security to test on a Windows machine and it instantly deletes the installer when downloading it.
We do code sign our package.
Please let me know what other info can I provide to help solve this issue.
Thanks!

**Comment by mmaietta** [comment]
Can you try upgrading to `next` electron-builder 22.14.x?

**Comment by juanmartin** [comment]
I can confirm Kaspersky Internet Virus did not delete my application installer after updating to `electron-builder@next` and running a package build through CircleCI.

Thank you so much!!! this fixed issues for our customers using Kaspersky software.
