### ISSUE TITLE
Change behaviour of the --out cli param

### ISSUE THREAD

**Issue by rishson** [electron-userland/electron-builder#63]
[Enhancement request]
Hi.
Any chance we could change the behaviour of the --out param from specifying the output directory, to specifying the output file (and path)?

e.g.

```--out=packaged``` (Creates ./packaged/MyApp Setup.exe)
to
```--out=packaged/MyApp_currentVersion_setup.exe``` (creates ./packaged/MyApp_currentVersion_setup.exe)

This has the following benefits:

- Allows for templating of the resulting setup filename. This is useful when creating beta builds etc..
- More consistent with other related packagers such as appDmg, or just plain old zip.

**Comment by stefanjudis** [comment]
Thanks.

Hmm... I like the fact, that users don't have to deal with the file format when creating crossplatform installers.

But yeah - might be a good idea. :)

**Comment by rishson** [comment]
Maybe keeping ```--out``` as it is and adding ```--outfile``` as a separate option, so as not to introduce a breaking change, but allow this ability as well?

**Comment by stefanjudis** [comment]
Ja, that's what I first, too. :)

So I think that's a good idea that helps everybody. :+1:

**Comment by rishson** [comment]
:+1:

**Comment by havenchyk** [comment]
@stefanjudis maybe add tag "help wanted" or something similar for it?

**Comment by stefanjudis** [comment]
Please feel always free to solve any issue... No need for requesting labels ( it just makes the conversation longer ). :bowtie:

**Comment by stefanjudis** [comment]
I could basically add "help wanted" to every issue. ;)

**Comment by develar** [comment]
@rishson Is it still needed or I can close this issue (please see our new API and layout)?
