### ISSUE TITLE
autoUpdater downloads the update but doesn't quit and install on macOs

### ISSUE THREAD

**Issue by WolfgangReip** [electron-userland/electron-builder#6302]
* **Electron-Builder Version**: ^22.11.7

* **Electron-updater Version**: ^4.3.9

* **Node Version**: v14.15.5

* **Electron Version**: 11.3.0
* **Electron Type (current, beta, nightly)**: current
 

* **Target**: macOs

Hello,

I have an electron app on s3, the auto updater works perfectly fine on Windows (downloads the update, and automatically quit and install, same code for both OS), but on macOs, it downloads the update, but then doesn't quit and install, I have to manually trigger quit and install in the tray for it to update. 

Here are the logs and the function: 
<img width="1249" alt="Capture d’écran 2021-09-29 à 09 33 21" src="https://user-images.githubusercontent.com/54063166/135224426-4f8730bd-8a4e-4030-aa6d-75d119b615a7.png">

<img width="704" alt="Capture d’écran 2021-09-29 à 09 42 15" src="https://user-images.githubusercontent.com/54063166/135224716-68d087e1-f4d4-4072-b5cc-cab834df6c22.png">

Looks like two events are triggered in a row when it's called only once. 

Also tried to setTimeOut the quitAndInstall method, if I do that I don't have anymore the "Error: The command is disabled and cannot be executed
" but it still doesn't quit and install, it that scenario I get the same logs as the ones above but starting at time 9:32:00.496

Thank you very much for the help :)

**Comment by ttomaszewski** [comment]
Also been seeing this event triggered twice. This has been an issue for use for several months now.

**Comment by jkowalski** [comment]
Seeing this in https://github.com/kopia/kopia/issues/1630 too.
