### ISSUE TITLE
xmldom 

### ISSUE THREAD

**Issue by VigneshSonaiya** [electron-userland/electron-builder#6303]
**Electron-Builder Version: ^22.11.11
Node Version: v14.16.1
Electron Version: 15.0.0
Electron Type (current, beta, nightly): current
Target: windows**

Hi I have got some security update alert from **dependabot** when we use the **electron-builder** package. I have updated everything to latest

![image](https://user-images.githubusercontent.com/47246527/135249358-23e5a6b0-68e0-4a5e-b3eb-26107497c37f.png)

**Comment by mmaietta** [comment]
I'm not sure how to resolve this. Could you please advise?

`xmldom` is used by `plist`, which is a dependency of both [electron-osx-sign](https://www.npmjs.com/package/electron-osx-sign) and [dmg-license](https://www.npmjs.com/package/dmg-license) packages, both of which don't have any updates that upgrade `xmldom` to `0.6.0`
```
"node_modules/plist": {
    "version": "3.0.2",
    "resolved": "https://registry.npmjs.org/plist/-/plist-3.0.2.tgz",
    "integrity": "sha512-MSrkwZBdQ6YapHy87/8hDU8MnIcyxBKjeF+McXnr5A9MtffPewTs7G3hlpodT5TacyfIyFTaJEhh3GGcmasTgQ==",
    "dev": true,
    "dependencies": {
        "base64-js": "^1.5.1",
        "xmlbuilder": "^9.0.7",
        "xmldom": "^0.5.0"
    },
    "engines": {
        "node": ">=6"
    }
},
```

**Comment by baparham** [comment]
`xmldom` is [now listed](https://github.com/xmldom/xmldom/issues/271) as `@xmldom/xmldom` past version 0.7.0, so we need to make some upstream PRs to plist it sounds like.

**Comment by baparham** [comment]
or since it seems `plist` has already just inlined the used code from xmldom to avoid migrating to a different dependency, then we may just need to get `electron-osx-sign` to use `plist@3.0.4` and that would resolve this.
