### ISSUE TITLE
Any update about being able to install the pkg in user's home directory in macOS?

### ISSUE THREAD

**Issue by skinner2012** [electron-userland/electron-builder#6305]
* **Electron-Builder Version**:  22.9.1

* **Node Version**: 11

* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

Hi there was such issue https://github.com/electron-userland/electron-builder/issues/2201 which I am trying to resolve. Is there any update about this issue?  If it's still nothing we can do. Does anyone know how to not ask user to input the password when installing or upgrading the app in macOS by resolving through the scripts via Electron and Electron Builder?

Thanks. 🙏

**Comment by aam1r** [comment]
This is still happening on macOS Big Sur (11.2.3) but does not happen on macOS Monterey (12.1).

Has anyone been able to figure out why this happens and if there's a workaround here?
