### ISSUE TITLE
Electron-Updated breaks npm run build 

### ISSUE THREAD

**Issue by 503Dev** [electron-userland/electron-builder#6306]
* **Electron-Builder Version**: 22.14.3 

* **Node Version**:  16.9.1

* **Electron Version**: 7.2.4
* **Electron Type (current, beta, nightly)**:  current 

* **Target**: win

When adding electron-updater to my project, I am experiencing issues with my build command.  These are the errors, only removing electron-updater will fix the issue with my production build.  I am sure it's my own stupidity so any help would be appreciated.

`ERROR in ./~/electron-updater/out/AppImageUpdater.js
Module parse failed: C:\Temp\3DPRINT\threejs-desktop - working\electron-threejs-editor\node_modules\electron-updater\out\AppImageUpdater.js Unexpected token (37:54)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (37:54)`

`ERROR in ./~/electron-updater/out/providers/Provider.js
Module parse failed: C:\Temp\3DPRINT\threejs-desktop - working\electron-threejs-editor\node_modules\electron-updater\out\providers\Provider.js Unexpected token (53:71)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (53:71)`

`ERROR in ./~/electron-updater/out/MacUpdater.js
Module parse failed: C:\Temp\3DPRINT\threejs-desktop - working\electron-threejs-editor\node_modules\electron-updater\out\MacUpdater.js Unexpected token (49:32)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (49:32)`

`ERROR in ./~/electron-updater/out/AppUpdater.js
Module parse failed: C:\Temp\3DPRINT\threejs-desktop - working\electron-threejs-editor\node_modules\electron-updater\out\AppUpdater.js Unexpected token (160:16)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (160:16)`

`ERROR in ./~/electron-updater/out/NsisUpdater.js
Module parse failed: C:\Temp\3DPRINT\threejs-desktop - working\electron-threejs-editor\node_modules\electron-updater\out\NsisUpdater.js Unexpected token (29:92)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (29:92)`

If I had to make an educated guess I would say my webpack is not compatible with es6 or babel and thus the issue, but sincerely, it is out of my league.  Please let me know where I fudged this one.  Thanks.

**Comment by mmaietta** [comment]
I took a look at this file: `node_modules\electron-updater\out\AppImageUpdater.js Unexpected token (37:54)` and at line 37 it's an `async` arrow function:
```
task: async (updateFile, downloadOptions) => {
```

Similarily, this file `node_modules\electron-updater\out\providers\Provider.js Unexpected token (53:71)` is using spread syntax
```
result.headers = headers == null ? this.requestHeaders : { ...this.requestHeaders, ...headers };
```

My best guess is that you need some polyfills. Since you mentioned webpack and babel, I did a quick search and found this: https://dev.to/btandayamo/a-guide-to-through-async-await-with-babel-and-webpack-mh5
