### ISSUE TITLE
electron-builder tests fail on Apple Silicon dev machine

### ISSUE THREAD

**Issue by sr258** [electron-userland/electron-builder#6310]
If you use an Apple Silicon dev machine to work on electron-builder many tests fail as the artifacts produced don't match the ones expected in the snapshots:

Example when executing `pnpm test-all`:

```
 license ja

    expect(received).toMatchSnapshot()

    Snapshot name: `license ja 1`

    - Snapshot  - 3
    + Received  + 3

    @@ -1,18 +1,18 @@
      Object {
        "mac": Array [
          Object {
    -       "arch": "x64",
    -       "file": "Test App ßW-1.1.0.dmg",
    +       "arch": "arm64",
    +       "file": "Test App ßW-1.1.0-arm64.dmg",
            "safeArtifactName": "TestApp-1.1.0.dmg",
            "updateInfo": Object {
              "sha512": "@sha512",
              "size": "@size",
            },
          },
          Object {
    -       "file": "Test App ßW-1.1.0.dmg.blockmap",
    +       "file": "Test App ßW-1.1.0-arm64.dmg.blockmap",
            "safeArtifactName": "TestApp-1.1.0.dmg.blockmap",
            "updateInfo": Object {
              "sha512": "@sha512",
              "size": "@size",
            },

      242 |   }
      243 |
    > 244 |   expect(objectToCompare).toMatchSnapshot()
          |                           ^
      245 |
      246 |   c: for (const [platform, archToType] of packagerOptions.targets!!) {
      247 |     for (const [arch, targets] of computeArchToTargetNamesMap(

      at packAndCheck (src/helpers/packTester.ts:244:27)
      at src/helpers/packTester.ts:134:36
      at executeFinally (../packages/builder-util/src/promise.ts:12:14)
      at assertPack (src/helpers/packTester.ts:117:3)
```

As you can see, the filename automatically gets a -arm64 suffix on Apple Silicon which is not what is saved in the snapshot. This affects ~80 snapshots.

**Comment by mmaietta** [comment]
That's correct and as expected. Because the snapshots are used to verify tests in our CI environment, which is either Windows, Linux, or x64 Mac depending on which test file is selected. Linux tests can run in a docker container, but that also doesn't work on M1s

None of the CI nodes are arm64. 

You'll need to push to the repo in order for GitHub actions and related CI tests to be picked up correctly.

**Comment by sr258** [comment]
Alright, any tips on running the maximum amount of tests possible without running into these issues?

**Comment by mmaietta** [comment]
For my fork, I signed up and linked my CircleCI and reused the github actions so that I can run the tests.
