### ISSUE TITLE
compression maximum makes AppImages run very slowly

### ISSUE THREAD

**Issue by ashleysimpson** [electron-userland/electron-builder#6316]
* **Electron-Builder Version**: `22.13.0`

* **Node Version**: `14.17.0`

* **Electron Version**: `13.2.3`
* **Electron Type (current, beta, nightly)**: `current`

* **Target**: `AppImage`

### Question/Bug Report

We started using the `compression` flag recently and setting it to `maximum`. This did decrease the package size for us, which was great. One issue is that it makes the `AppImage` run really slow. Not sure if this is expected or not but we were really confused for a while and had to revert this change. Just wondering if this should be something mentioned in the documentation or maybe it is an issue that should be looked into (I understand that `AppImage`s are self-contained and therefore any form of compression might affect the speed). Thanks! Really appreciate all the work that is put into this package.

**Comment by mmaietta** [comment]
Duplicates #6317
