### ISSUE TITLE
NODE_ENV variables showing as undefined in packaged application

### ISSUE THREAD

**Issue by Mercieral** [electron-userland/electron-builder#632]
* **Version**: 5.20.0

* **Target**: Mac 

I originally was setting the NODE_ENV variables through the build script...
`    "packageALL": "NODE_ENV=production grunt build_production_electron && build -mwl",`
and that seemed to be working properly about 2 weeks ago. But now I am just getting NODE_ENV=undefined whenever I call `process.env.NODE_ENV` in the packaged application (but not when run using electron-prebuilt). Did something happen to how node environment variables are set in the packaged application, or is there a better way to set the NODE_ENV variable?

**Comment by develar** [comment]
`NODE_ENV` is a just env var, it is not set to packaged app. 

>  I am just getting NODE_ENV=undefined whenever I call process.env.NODE_ENV in the packaged application (but not when run using electron-prebuilt)

So, it means that no `NODE_ENV` in your env. `NODE_ENV=production` during build only set env during build, not for production app. 

Use `--extraMetadata` param (5.22.1+). e.g. `build --em.foo=bar` and then read your `package.json` (see #494)

**Comment by Mercieral** [comment]
@develar 

Thanks, I thought it was working earlier but I was probably just fooling myself 😆. I will try using extraMetadata

**Comment by develar** [comment]
Please note — `extraMetadata` only for ASAR.

**Comment by ganeshrvel** [comment]
@Mercieral how did you solve this issue?
