### ISSUE TITLE
electron-builder not generating app-update.yml for Linux

### ISSUE THREAD

**Issue by mohsintahir** [electron-userland/electron-builder#6322]
* **Electron-Builder Version**:  22.9.1

* **Node Version**: 12.12.69

* **Electron Version**: 10.1.4
* **Electron Type (current, beta, nightly)**: current
 4.2.5

 Linux default target
* **Target**: Linux default target

here is my package.json file 
```
{
  "name": "",
  "version": "",
  "description": "",
  "main": "built/main.js",
  "scripts": {
    "build": "tsc && (cp -r src/assets built/assets || xcopy \"src/assets\" \"built/assets\" /y /i /s)",
    "watch": "tsc -w",
    "lint": "tslint -c tslint.json -p tsconfig.json",
    "start": "yarn run build && electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder build",
    "postinstall": "electron-builder install-app-deps",
    "build-mac": "yarn build && electron-builder build --mac",
    "build-windows": "yarn build && electron-builder build --windows nsis --x64 --ia32 --arm64",
    "build-linux": "yarn build && electron-builder build --linux rpm deb AppImage",
    "publish-mac": "yarn build && electron-builder build --mac --publish always",
    "publish-linux": "yarn build && electron-builder build --linux rpm deb AppImage --publish always",
    "publish-windows": "yarn build && electron-builder build --windows nsis --x64 --ia32 --arm64 --publish always",
    "publish-win-mac": "yarn build && electron-builder build --mac --windows nsis --x64 --ia32 --arm64 --publish always"
  },
  "repository": "",
  "keywords": [],
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "license": "",
  "build": {
    "appId": "",
    "productName": "",
    "asar": true,
    "asarUnpack": [
      "**/dict/*"
    ],
    "artifactName": "app-name-${version}-${arch}.${ext}",
    "afterSign": "build/notarize.js",
    "mac": {
      "category": "public.app-category.utilities",
      "icon": "build/icon.png",
      "type": "distribution",
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.plist"
    },
    "dmg": {
      "sign": false
    },
    "win": {
      "icon": "build/icon.png"
    },
    "linux": {
      "icon": "build",
      "category": "Utility"
    },
    "publish": [
      {
        "provider": "github",
        "owner": "mohsintahir",
        "repo": "some-sample-app",
        "releaseType": "draft"
      }
    ]
  },
  "devDependencies": {
    "@types/node": "12.12.69",
    "dotenv": "8.1.0",
    "electron": "10.1.4",
    "electron-builder": "22.9.1",
    "electron-notarize": "^0.1.1",
    "tslint": "5.18.0",
    "typescript": "3.9.7"
  },
  "dependencies": {
    "electron-hunspell": "1.1.2",
    "electron-json-storage": "3.1.0",
    "electron-log": "4.4.1",
    "electron-settings": "3.1.4",
    "electron-updater": "4.2.5",
    "electron-window-state": "5.0.3",
    "https-proxy-agent": "4.0.0",
    "ws": "3.3.1"
  }
}

```
 When I build my Linux app using `sudo yarn build-linux` and opens the app, auto update doesn't work. When I look at the logs, it says 
```
Error: Error: ENOENT: no such file or directory, open '/opt/{app name}/resources/app-update.yml'
```

It seems app-update.yml doesn't get generated. Can anybody guide me what I am doing wrong?

**Comment by robertpatrick** [comment]
@mmaietta There is a problem here though.  The problem is that `autoUpdater.checkForUpdates()` call is trying to find app-update.yml when the application is running from a non-supported installer type (e.g., `rpm` or `deb`).  For example, my application uses electron-builder to create Linux `AppImage`, `rpm` and `deb` binaries.  When I run my application from the `rpm` installer, I get the following log entries:

```
info: Checking for update
error: Error: Error: ENOENT: no such file or directory, open '/opt/WebLogic Kubernetes Toolkit UI/resources/app-update.yml'
error: Application auto-updater failed: ENOENT: no such file or directory, open '/opt/WebLogic Kubernetes Toolkit UI/resources/app-update.yml'
error: Error: ENOENT: no such file or directory, open '/opt/WebLogic Kubernetes Toolkit UI/resources/app-update.yml'
```

While these are not fatal, it is annoying to pollute the log file with them.  Is there something I can do in the code to figure out that the application is running from a non-supported installer platform?  If not, the auto-updater should probably figure this out somehow and make the calls no-ops.

**Comment by panther7** [comment]
App-update.yml is not genereate on Windows also. I do not know, no error message.

**Comment by robertpatrick** [comment]
@panther7 app-update.yaml should be generated when building the NSIS installer (and are using the `electron-updater` package).   My project, [WebLogic Kubernetes Toolkit UI](https://github.com/oracle/weblogic-toolkit-ui), is building an NSIS installer and the build (and subsequent auto-updates checks at runtime) work fine.

Are you saying that your `electron-builder build` is failing with an error about a missing `app-update.yml` file?

My previous comment was a runtime, rather than a build-time issue.  At runtime, I added a check like this to my code to eliminate the errors from our log file.

```
  _supportsAutoUpdate = !(osUtils.isLinux() && !process.env.APPIMAGE);
  ...
  if (_supportsAutoUpdate) {
    const checkResult = await autoUpdater.checkForUpdates();
    ...
  } 
```

**Comment by panther7** [comment]
@robertpatrick Yes, you have right, but, why does not works autoupdate with archive like zip?

**Comment by robertpatrick** [comment]
@panther7 Because the `electron-updater` package does not support them.  Refer to the [docs](https://www.electron.build/auto-update) to see the supported installer types.

**Comment by panther7** [comment]
I still dont understand, why is not support create "app-update.yml" for each situation.

Now, i must "manualy" create app-update.yml with afterPack callback :-/

**Comment by rpatrick00** [comment]
@panther7 i think the better question is why electron-builder thinks you need this file for unsupported installer types

**Comment by mmaietta** [comment]
@rpatrick00 maybe we can do something like this?
https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/electron-updater/src/AppUpdater.ts#L252-L258

Replace with
```
  public isUpdaterActive(): boolean {
    if (!this.app.isPackaged) {
      this._logger.info("Skip checkForUpdates because application is not packed")
      return false
    }
    const isAppImage = process.platform === "linux" && !!process.env.APPIMAGE
    const canUpdate = this instanceof MacUpdater || this instanceof NsisUpdater || isAppImage
    if (!canUpdate) {
      this._logger.info(`Not a MacOS, NSIS, or AppImage distributable, auto-updates are not supported.`)
      return false
    }
    return true
  }
```
A few changes elsewhere are needed, such as `checkForUpdates` to enable a null Promise return, but that's minor.

My only pickle right now is: How do we detect it's an NSIS-installer app and not MSI? Do you know if there are any env vars we can check for at runtime?

**Comment by mmaietta** [comment]
Wait, it doesn't need that extra check. It already checks in AppImageAdapter
https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/electron-updater/src/AppImageUpdater.ts#L18-L28

Are you guys using `checkForUpdates` or `checkForUpdatesAndNotify`?

**Comment by robertpatrick** [comment]
@mmaietta in our app, we are using checkForUpdates().  The app was working fine from an RPM installation but the checkForUpdates() call resulted in a few error messages being written to the log.  I wrapped the call to checkForUpdates to not call it is the platform is Linux and the APPIMAGE environment variable is not set to prevent these error messages from being written to the log...

**Comment by mmaietta** [comment]
The `isUpdaterActive` is only called in `checkForUpdatesAndNotify`, so I'm pulling that into `checkForUpdates` and that should resolve the errors in your logs I think
Opened https://github.com/electron-userland/electron-builder/pull/6616

**Comment by lacymorrow** [comment]
Huge thanks for fixing this issue! Was a big deal with appx in windows store

**Comment by sascha-schieferdecker** [comment]
After this change I cannot force the application to check for Updates if it's not packaged, even if I use checkForUpdates and place a dev-app-update.yml in the root folder of the app next to the package.json. Is this intended?

**Comment by mmaietta** [comment]
Yes, that seems to be intended from previous business logic
https://github.com/electron-userland/electron-builder/blob/86e6d1509f9b9c76c559e9c3a12b7a1595fe3ac4/packages/electron-updater/src/AppUpdater.ts#L256-L262
