### ISSUE TITLE
NSIS electron-updater uninstalls old version, but does not install new version

### ISSUE THREAD

**Issue by delewis13** [electron-userland/electron-builder#6329]
**UPDATE - NAMING COLLISION BETWEEN INSTALLER & PRODUCT**

I will note that there are a number of other threads / bugs that exhibit similar behaviour [i.e. uninstalls and doesn't reinstall], but all with seemingly different root causes. I have fixed this in my case, for my specific root cause [detailed below]. If this helps you, awesome - please post in the thread that it helped to let maintainers know.

If not, then your root cause is probably different - in this case, probably better you post on one of the other threads around this issue / create your own, rather than adding here.

**THE FIX**

Minimal reproduction: https://github.com/delewis13/electron-builder-minimal/tree/electron-updater-nsis-bug
Issue can be reproduced across multiple version combinations of `electron-builder` / `electron` / `electron-updater`

It seems there is some naming collision when the `productName` in your electron-builder config (which is used to name the installed .exe) and the `artifactName` (which is the installer) are the same (case-insensitive). 

For example, previously I had `productName: 'myapp'` and `artifactName: 'myApp.exe'` which caused the issue as described below. Simply changing `artifaceName: 'myApp Setup.exe` resolved the issue.

**ORIGINAL POST**

electron: 11.1
electron-builder: 22.13.1
electron-updater: 4.3.9
node: 15.0.1

Pretty much as title says. 

Tried with various build configs & electron-updater methods. The most simple of which was:

```
  },
  nsis: {
    oneClick: true,
    installerIcon: `./builder/images/ico/${pkg.productName}/recording.ico`,
    uninstallerIcon: `./builder/images/ico/${pkg.productName}/recording.ico`,
    installerHeaderIcon: `./builder/images/ico/${pkg.productName}/recording.ico`,
  },
```
with
`    autoUpdater.checkForUpdatesAndNotify()
`

Tested with & without code-signing cert

**Comment by delewis13** [comment]
> Install new version

New version of what? My electron-builder + electron-updater are both latest published on NPM :S

**Comment by Echo4F** [comment]
iOS is for iPhone and am using Android

**Comment by Echo4F** [comment]
I have done it 
Please what next

**Comment by delewis13** [comment]
Afraid none of those fixes helped @ragauskl :( Thanks for the suggestion though

**Comment by delewis13** [comment]
@mmaietta noticed you are quite active here - thought i'd tag you.

I've made a minimal reproduction of this error forked from `electron-webpack-quick-start`, though i've also reproduced it on other electron / electron builder versions.

See the post above for more info, i've updated it with link to minimal reproduction of bug + description

**Comment by robertpatrick** [comment]
@mmaietta I am seeing the same behavior with our app.  autoInstallOnAppQuit=true works when the NSIS app is installed "only for you".  When installed for "All users" and exiting the app, the Windows UAC prompt is displayed asking for permissions for the "old-installer".  Upon granting permission, the app is uninstalled but the installer never starts (and no Windows UAC Prompt is ever displayed).

**Comment by ejwilburn** [comment]
We're seeing the same issue. This used to happen with just the advanced installer (not the one-click installer) and switching to the one-click installer fixed it for us but now auto-update is broken completely on Windows.

Windows 10 x64 in my test environment.

**Comment by delewis13** [comment]
@robertpatrick  @ejwilburn 

Looks like a similar symptom with a different root causes. Probably not suitable for this thread! You've probably already looked, but perhaps https://github.com/electron-userland/electron-builder/issues/2363?

**Comment by robertpatrick** [comment]
@delewis13 I didn't realize that #2363 existed.  That, and #6425, have me concerned that this feature isn't being properly tested on Windows.  What can I do to help get auto-update working correctly on Windows?

**Comment by robertpatrick** [comment]
@mmaietta i think this is resolved already, probably should close this.
