### ISSUE TITLE
define extraFiles option per target

### ISSUE THREAD

**Issue by davidcassany** [electron-userland/electron-builder#6337]
* **Electron-Builder Version**:  v22.14.2

* **Node Version**: Node v14

* **Electron Version**: 12.0.18
* **Electron Type (current, beta, nightly)**:

* **Target**: rpm/deb, AppImage

In order to build rpm/deb and AppImage packages for linux it would be really handy to be capable to enable `extraFiles` (and the other files related options like `files` or `extraResources`) per target rather than per platform. In the case I am working with I require to package relatively different files structure for the AppImage in comparison to what I need for rpm/deb. So for AppImage I need to add an `extraFiles` option with a custom fileSet to rename and relocate certain files. I'd love to be capable to keep all this in a single yaml manifest, however with the current logic I can't add `extraFiles` under the specific target. I could not find any workaround other than having two manifests at the moment. Is there any way to customize file structure per target currently? Is there any chance this feature could be included in electron-builder?

**Comment by sohobloo** [comment]
this is my solution:

``` json
"extraResources": [
    {
      "from": "assets/plugins",
      "to": ".",
      "filter": [
        "!io",
        "io/${platform}/${arch}",
      ]
    }
  ],
```
place your platform and arch specified into different folders and this config will copy only that folder's files into destination folder.

**Comment by davidcassany** [comment]
@sohobloo thanks for your suggestion. I am not sure I am following you, not sure how to apply that in my case. The platform and arch is independent of the targets I am after. Basically I want to build an RPM and an AppImage both in x86_64 and Linux, so in that case `${platform}` and `${arch}` have the same value. Is there a `${target}` variable that could be used for templating? I have not seen it documented anywhere...

**Comment by mikey0000** [comment]
I've just now run into this problem, it would be good to either be able to apply extra files based on the target .e.g deb AppImage, even if I could write a function as long as there is something that I can use to know what its targeting
