### ISSUE TITLE
Publish all builds to Github

### ISSUE THREAD

**Issue by morpig** [electron-userland/electron-builder#634]
* **Version**: 5.22.1

* **Target**: macOS, Linux and Windows

Hey there,

Is there anyway to upload all builds (macOS, Linux and Windows) to GitHub Releases? I tried to do it with build --p always, but it only uploads the macOS build.

Any ideas?
Thanks

**Comment by develar** [comment]
All artifacts should be uploaded. Please set env `DEBUG=electron-builder`, build and attach debug out.
