### ISSUE TITLE
The .exe application disappeared after the window 7 system was updated with electron-updater

### ISSUE THREAD

**Issue by Bravo123** [electron-userland/electron-builder#6342]
* **Electron-Builder Version**: 
* "electron-builder": "^22.9.1",

* **Node Version**: v12.18.3

* **Electron Version**: "electron": "^6.1.12",
* **Electron Type (current, beta, nightly)**:

"electron-updater": "^4.3.8",

* **Target**: window
 "nsis": {
	"oneClick": false,
	"createDesktopShortcut": "always",
	"allowToChangeInstallationDirectory": true
}

Not necessarily, there is no way to provide recurring steps, currently only appears on window 7 system.
Has anyone encountered a similar problem？

**Comment by delewis13** [comment]
I had similar issue here - https://github.com/electron-userland/electron-builder/issues/6329

Other similar issues:
https://github.com/electron-userland/electron-builder/issues/6329
https://github.com/electron-userland/electron-builder/issues/6312

**Comment by delewis13** [comment]
Hi @Bravo123 I solved my issue here: https://github.com/electron-userland/electron-builder/issues/6329

It may or may not be the same as yours, but mine originated from having `productName` the same as my `artifactName`
