### ISSUE TITLE
electron: 11.1
electron-builder: 22.13.1
electron-updater: 4.3.9
node: 15.0.1

### ISSUE THREAD

**Issue by Echo4F** [electron-userland/electron-builder#6343]
Pretty much as title says.
Tried with various build configs & electron-updater methods. The most simple of which was:

}, nsis: { oneClick: true, installerIcon: `./builder/images/ico/${pkg.productName}/recording.ico`, uninstallerIcon: `./builder/images/ico/${pkg.productName}/recording.ico`, installerHeaderIcon: `./builder/images/ico/${pkg.productName}/recording.ico`, }, 

with
autoUpdater.checkForUpdatesAndNotify()

Should also mention that I don't have a code signing cert - not sure if this is an issue?

autoUpdater.logger = require("electron-log") autoUpdater.logger.transports.file.level

**Comment by mmaietta** [comment]
https://www.electron.build/auto-update#debugging
```
autoUpdater.logger = require("electron-log")
autoUpdater.logger.transports.file.level = "info"
```
This would give you debug logging

I'm fairly positive the logs will show that a code signing cert is required for auto-updates to work.

**Comment by Echo4F** [comment]
> https://www.electron.build/auto-update#debugging
> ```
> autoUpdater.logger = require("electron-log")
> autoUpdater.logger.transports.file.level = "info"
> ```
> This would give you debug logging
> 
> I'm fairly positive the logs will show that a code signing cert is required for auto-updates to work.
