### ISSUE TITLE
Run `electron-builder install-app-deps` Error Windows Script Host 800A0404

### ISSUE THREAD

**Issue by iDerekLi** [electron-userland/electron-builder#6354]
* **Electron-Builder Version**:  22.13.1

* **Node Version**:  v14.15.0

* **Electron Version**: 15.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

I use `yarn` to install dependencies on MacOS and it works normally, but an error occurs in the script `"postinstall": "electron-builder install-app-deps"` on Windows. What should I do? 

![image](https://user-images.githubusercontent.com/24502299/137656375-2aff6e54-d189-48c1-aae1-f9b2a8426509.png)

**Comment by mmaietta** [comment]
You'll need to rename the config file to something different as there's an issue with npm on windows: https://github.com/electron-userland/electron-builder/issues/6227

**Comment by fairking** [comment]
It might be related and could help to solve the problem: https://github.com/ficonsulting/RInno/issues/44#issuecomment-992299431
