### ISSUE TITLE
Deb/Rpm icons not working

### ISSUE THREAD

**Issue by umerkk** [electron-userland/electron-builder#6358]
* **Electron-Builder Version**: 22.13.0
* **Node Version**: 14.17.0
* **Electron Version**: 13
* **Electron Type (current, beta, nightly)**:

* **Target**: Ubuntu, CentOS

I have been creating .deb & .rpm packages of my application and providing the "ICNS" file as an icon for my Linux config.
Once the application is installed, I do see the different sizes of icons are generated & placed under the right location "/usr/share/icons/hicolor".
I also verified that the .desktop file points to the correct filename and all seem to be correct and the icons file have correct READ permission "rw-rw-r--"
However, for some reason, the application icon does not appear on the launcher, etc both on Ubuntu & CentOS.

Is there anything I am missing or is it a bug?

**Comment by LuisAlejandro** [comment]
@umerkk did you manage to solve this? I'm having the same issue

**Comment by umerkk** [comment]
Can you paste your config and path to icon file?

**Comment by umerkk** [comment]
We sovled it by moving away from .png to .icns
Is this something possible on your end?

Also please make sure that your reference to `asset/icon.png` is valid.
we use 
```
  "directories": {
    "buildResources": "electron-builder-configuration/latest/resources"
  },
```
and our icon is inside the `resources` folder.

**Comment by LuisAlejandro** [comment]
@umerkk Thanks! it worked

**Comment by Jaifroid** [comment]
This needs to be added to the documentation -- it worked for me using the top-level `deb` key (because using the Icon Set for AppImage breaks the AppImage build).

**Comment by Jaifroid** [comment]
Although the suggested fix works for deb, using the same fix for rpm fails for me, at least on Fedora.

**Comment by Natega** [comment]
same problem
