### ISSUE TITLE
Error when trying to sign macos app from ssh

### ISSUE THREAD

**Issue by johanpoirier** [electron-userland/electron-builder#636]
* **Version**: 5.18.0

* **Target**: MacOS

I wrote a script to build my apps for all platforms with signature.
It works well if I run it directly on my MacBook Air.

I've set up a Mac Mini to do all the build since it's always online.
It works well on this Mac too.

So I activated the ssh access and I ran the same script from a ssh connection.
I got this error:
```
Error: Command failed: codesign --sign Mac Developer: me@mycompany.com (XXXXXXX) --force /pathToMyApp/electron-builds/mac/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/pathToMyApp/electron-builds/mac/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: User interaction is not allowed.
```

I found this topic on SO: http://stackoverflow.com/questions/20205162/user-interaction-is-not-allowed-trying-to-sign-an-osx-app-using-codesign

I tried to add the ```-A``` in the ```codeSign.ts``` script but no luck.

Do you have any idea if it's possible to sign a MacOS app from ssh?

Thanks.

**Comment by develar** [comment]
I think Keychain is not unlocked. Do you use codesign manually (you shouldn't)? Do you use CSC_LINK or auto-discovery as on a development machine?

**Comment by johanpoirier** [comment]
I don't use codesign manually.
I use auto-discovery.

What do you mean by "Keychain is not unlocked"?

**Comment by develar** [comment]
I strongly recommend you to use auto-discovery only on development machine. Your Mac Mini is a CI server, so, consider to use `CSC_LINK`.

If you still want to use auto-discovery, please try to execute `security unlock-keychain -p yourPassword login.keychain` before build where `yourPassword` is your mac mini password.

**Comment by johanpoirier** [comment]
Thanks @develar, I will look how to use CSC_LINK.

**Comment by johanpoirier** [comment]
It's OK now with ```CSC_LINK```.

Thanks again for your amazing work and reactivity @develar.

**Comment by develar** [comment]
> It's OK now with CSC_LINK.

Yes, as expected. A lot of magic under the hood is done by electron-builder to ensure that you can sign app on CI (not developer machine) without any headache. Auto-discovery only and only for developer machine.
