### ISSUE TITLE
Quit and install error

### ISSUE THREAD

**Issue by Adrien-Kourganoff** [electron-userland/electron-builder#6367]
- Electron-builder Version : 22.13.1
- Node version: 14.15.5
- Electron Version: 14.1.1 (current)
- Target: Mac 

Unknown error linked to quitAndInstall method, blocking the app closing.

Logs: 
[electron] Checking for update
[electron] Found version 1.1.1634744534 (url: XXX.zip, XXX.dmg)
[electron] Downloading update from XXX.zip, XXX.dmg
dbg updater cache dir: [PATH]
[electron] New version 1.1.1634744534 has been downloaded to [PATH]/XXX.zip
[electron] / requested
[electron] /1634909897976-6851.zip requested
[electron] /1634909897976-6851.zip requested by Squirrel.Mac, pipe [PATH]/XXX.zip
[electron] Proxy server for native Squirrel.Mac is closed (was started to download XXX.zip)
[router] Execute quit-and-install-version
1634745141256 wrn Error: The command is disabled and cannot be executed at l.p.quitAndInstall (/App/Contents/Resources/app/build/main.js:2:419079) at o.onQuitAndInstallUpdate (/App/Contents/Resources/app/build/main.js:2:2075170) at o.t.quitAndInstallUpdate (/App/Contents/Resources/app/build/main.js:2:2051738) at r.s.prepare (/App/Contents/Resources/app/build/main.js:2:2006270) at _k (/App/Contents/Resources/app/build/main.js:2:2041056) at s.Tk (/App/Contents/Resources/app/build/main.js:2:2045029) at s.Ok (/App/Contents/Resources/app/build/main.js:2:2044117) at /App/Contents/Resources/app/build/main.js:2:2047218 at new Promise (<anonymous>) at s.o.execute (/App/Contents/Resources/app/build/main.js:2:2047188)

**Comment by robertpatrick** [comment]
@Adrien-Kourganoff take a look at #6418 to see if you might be having the same issue I had.

**Comment by robertpatrick** [comment]
@mmaietta i think this issue is resolved so you should probably close it
