### ISSUE TITLE
Overwrite installation will create a subfolder in the installation root directory.

### ISSUE THREAD

**Issue by asd281533890** [electron-userland/electron-builder#6369]
* **Electron-Builder Version**: 
* 22.10.5

* **Node Version**: 
* 14.17.1

* **Electron Version**:11.4.3
* **Electron Type (current, beta, nightly)**:stable

* **Target**: nsis
* **OS**: windows 10

I add an nsh file for nsis options to change the default installation directory:
```
!macro preInit
  SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\dyplatform"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\dyplatform"
  SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\dyplatform"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\dyplatform"
!macroend
```
![image](https://user-images.githubusercontent.com/46190356/138702698-eafcce99-e1b0-446f-b6ac-767bddf3e9dd.png)

My directory structure was like this when I first installed the application:
![image](https://user-images.githubusercontent.com/46190356/138700988-d06fe396-5d27-4212-8bbe-302bb22bab2c.png)
But when I installed it again in the same directory without uninstallation, the directory structure became as follows
![image](https://user-images.githubusercontent.com/46190356/138702194-d62b811c-92fe-42ef-8883-68a575f64ec8.png)

Its directory has one more folder with the name of package.json as the name.
![image](https://user-images.githubusercontent.com/46190356/138701945-5be5c6ce-a41f-490b-b479-afc17b5400bc.png)

Then I tested it again and found that as long as the installation directory already exists, nsis will create one more folder under the installation directory.I checked the electron-builder documentation but did not find the relevant configuration and instructions.Does anyone know why this is happening and how to solve this problem? I just want it to overwrite the installation and keep the exe executable in the same directory.

**Comment by psulek** [comment]
Hi there, i have this same problem. Here is detailed description of problem:

my project uses (till now) version `20.38.5` of `electron-builer` and when i set custom install location via recommended NSI script:

```nsi
!macro preInit
    SetRegView 64
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "c:\MyApp"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "c:\MyApp"
    SetRegView 32
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "c:\MyApp"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "c:\MyApp"
!macroend
```

and `productName` is `MyCompany Super Product` and run MSI installer (without changing install location in installer UI) my app is **properly** installed in `c:\MyApp` where i can find exe file eg. `c:\MyApp\myapp.exe` - **this is expected and valid**

But updating to latest version `24.9.1` with same `nsi` preInit script, and values, my app is installed into folder `c:\MyApp\MyCompany Super Product` and exe is found in `c:\MyApp\MyCompany Super Product\myapp.exe` - **this is unexpected and wrong**.

I found (thanks to @xyyHIT) what causing this is in file `app-builder-lib/templates/nsis/assistedInstaller.nsh` and function `instFilesPre`, where old was:

```nsi
    Function instFilesPre
      ${If} ${FileExists} "$INSTDIR\*"
        ${StrContains} $0 "${APP_FILENAME}" $INSTDIR
        ${If} $0 == ""
          StrCpy $INSTDIR "$INSTDIR\${APP_FILENAME}"
        ${endIf}
      ${endIf}
    FunctionEnd
```

but new one has:

```nsi
    Function instFilesPre
      ${StrContains} $0 "${APP_FILENAME}" $INSTDIR
      ${If} $0 == ""
        StrCpy $INSTDIR "$INSTDIR\${APP_FILENAME}"
      ${endIf}
    FunctionEnd
```

missing `${If}` on first line of function. Maybe this change fixes some other issue or was changed by mistake. Can you elaborate this? For now im stuck on older version.
