### ISSUE TITLE
Installation directory gets truncated name when package name contains dashes or dots.

### ISSUE THREAD

**Issue by djpereira** [electron-userland/electron-builder#637]
Electron Builder v5.22.1
Target: Windows x64

It seems like the name of your package, in the application package.json, is used to determine in which folder within `appdata\local` the application will be installed.

If the name of your package contains a period or a dash, then when the application is installed, the name of the folder gets truncated on that character. For example, an app with a package name of electron-quick-start, would get installed in `%userprofile%/appdata/local/electron` instead of `%userprofile%/appdata/local/electron-quick-start`.

This causes issues when you have different apps with the same prefix, which is common when you have different products of the same company. Maybe there's a way to overwrite this, but I am not sure how.

I put together an example on the repo below.
https://github.com/djpereira/electron-quick-start/tree/electron-builder-appname-issue

**Comment by develar** [comment]
Just to be sure — squirrel.windows?

**Comment by djpereira** [comment]
Yes, this is just for Windows. This works well on OSX, which gets installed in a different way.

**Comment by develar** [comment]
We also support nsis and it is much better than squirrel.windows, not yet default because auto-update not yet supported.

**Comment by djpereira** [comment]
Thanks @develar, we are aware of NSIS and we have taken it into consideration. As of right now, we believe that Squirrel fits our needs in a better way. I am looking at the code to try to figure out if it is a squirrel or an electron-builder issue, but I haven't figure it out yet. If you know is a squirrel issue, let me know and I'll file it with them.

**Comment by djpereira** [comment]
I think this is actually an issue with Squirrel. See https://github.com/Squirrel/Squirrel.Windows/issues/523. It may be good to at least warn the user when there's a space, dash or dots in the package ID.

By the way I think winstaller also fails if you try to create an MSI with a package name that contains a dash.

**Comment by develar** [comment]
> It may be good to at least warn the user when there's a space, dash or dots in the package ID.

We are going to throw Squirrel.Windows away (change default target) and make NSIS as default target. As a real solution. I am tired to fix Squirrel.Windows bugs.

**Comment by djpereira** [comment]
@develar, these seem to be problems that could be addressed at [electron/windows-installer](https://github.com/electron/windows-installer). If they do get fixed there, would you be open to update your package [develar/windows-installer](https://github.com/develar/windows-installer) with the fix?

**Comment by develar** [comment]
> If they do get fixed there, would you be open to update your package develar/windows-installer with the fix?

Of course, actually, I didn't move this issue to backlog — I am going to investigate and fix it.

**Comment by develar** [comment]
NSIS is recommended, moved to backlog.
