### ISSUE TITLE
Missing `icon` field both in doc and interface Configuration

### ISSUE THREAD

**Issue by thekingofcity** [electron-userland/electron-builder#6371]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: v14.17.4

* **Electron Version**: 12.0.17
* **Electron Type (current, beta, nightly)**: current

* **Target**: All platforms

Missing `icon` field both in [doc](https://www.electron.build/icons.html) and `packages/app-builder-lib/src/configuration.ts`.

`icon` field indeed can be added in `build` section of `package.json`:

```json
    "build": {
        "publish": [
            ...
        ],
        "icon": "./public/icon.png"
    }
```

However, it is not mentioned both in [doc](https://www.electron.build/icons.html) and `packages/app-builder-lib/src/configuration.ts`.

The place where I was convinced that I can use it is in here [`platformPackager.ts#L652`](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/platformPackager.ts#L652) and it sure works.

So is it like some dirty trick part? Hope not 😄

**Comment by thekingofcity** [comment]
No reply from authors is what blocks this :)

**Comment by dr-vortex** [comment]
@thekingofcity 

> The place where I was convinced that I can use it is in here [`platformPackager.ts#L652`](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/platformPackager.ts#L652) and it sure works.

Can you update this code link to point to a specific commit? It the latest one, it points to `return null`?

**Comment by thekingofcity** [comment]
> Can you update this code link to point to a specific commit? It the latest one, it points to `return null`?

Wow, the project did have some _maintainers_ to update. I thought this is already dead two years ago.

FYI, I'm no longer using Electron as my distributing method since it is slow and lacks the support of ESM in node. Tauri is a better option I think.

**Comment by dr-vortex** [comment]
> Wow, the project did have some _maintainers_ to update. I thought this is already dead two years ago.

I'm not a maintainer, just experiencing the same issue. I may move to Tauri though.
