### ISSUE TITLE
electron-builder crashing my mac due to memory leak (?)

### ISSUE THREAD

**Issue by JhaAman** [electron-userland/electron-builder#6386]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: 16.10.0

* **Electron Version**: 15.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS (dmg, arm-dmg)

I’ve been using electron-builder to push out updates on macOS for a while. After changing some UI details and a few other things, it has now becoming impossible to build or publish my app on my mac. 

Everytime I use electron-builder, my Mac begins the process but eventually crashes. It seems to be a memory leak issue. The last time the build worked was early last week. In the meantime, the only edits I’ve made were in the renderer process, and running an unpackaged version locally isn’t an issue at all. 

I suspect the issue is related to me upgrading my computer to macOS monterey in the past week. I don’t know what other issue may be causing the crash. 

Please let me know if you need any other details and where to get them - really perplexed on this issue

**Comment by harusurv** [comment]
I also reproduce this issue on Monterey

**Comment by billmn** [comment]
Same for me using Monterey, before upgrade to macOS 12 all works fine.

**Comment by billmn** [comment]
I got around the problem using the `notarytool`

For those who use the `electon-notarize` package like me, the "tool" parameter must be changed:
https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid

**Comment by mmaietta** [comment]
Sooo, just to confirm, is this still a valid electron-builder issue? Or can it be closed since it seems that the underlying issue was electron-notarize+MacOS 12

**Comment by jeanfbrito** [comment]
> I got around the problem using the `notarytool`
> 
> For those who use the `electon-notarize` package like me, the "tool" parameter must be changed: https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid

This can solve the problem with the auto-update memory leaking? Or is just in the build?
