### ISSUE TITLE
Changing build attributes for different environment

### ISSUE THREAD

**Issue by jbleuzen** [electron-userland/electron-builder#639]
This is more a question than an issue...

Let say I want to build my app for various environment and change for example based on environment : 
 - the name
 - the icon path
 - the appId 

Is this possible with electron-builder to change build attributes ? I thought that extraMetadata would overwrite build attributes but it's not the case with my testing...

If this is possible how would you do that ?
Thanks !

**Comment by develar** [comment]
> I thought that extraMetadata would overwrite build attributes but it's not the case with my testing...

Currently it doesn't overwrite. If it will be fixed to overwrite — is it a solution?

**Comment by jbleuzen** [comment]
If it overwrites it is a solution thanks !

**Comment by jbleuzen** [comment]
Thanks it's working like a charm…
And thanks a lot for this awesome project 👍

**Comment by ir-fuel** [comment]
There is something I don't understand here.
In the docs it says:

Specify the build configuration in the development `package.json` as follows: ....

So the icon file is in the development `package.json`

However the `--em` option docs say:

Inject properties to application `package.json`


So how can injecting properties in the application `package.json` override an icon?

**Comment by develar** [comment]
@ir-fuel Docs is a little bit outdated. `--em.build.` If property named as `build`, it will change build configuration. So, for example, you can use `--em.build.windows.icon` to change icon for windows.

Also, please note — since electron-builder 8 you don't need to use two-package.json structure anymore (https://github.com/electron-userland/electron-builder/issues/906#issuecomment-260344645).

**Comment by VynnykV** [comment]
> @ir-fuel Docs is a little bit outdated. `--em.build.` If property named as `build`, it will change build configuration. So, for example, you can use `--em.build.windows.icon` to change icon for windows.
> 
> Also, please note — since electron-builder 8 you don't need to use two-package.json structure anymore ([#906 (comment)](https://github.com/electron-userland/electron-builder/issues/906#issuecomment-260344645)).

Can I do the same with publish provider url? Could you give me an example please?
