### ISSUE TITLE
Electron-updater doesn't find latest release

### ISSUE THREAD

**Issue by stoefln** [electron-userland/electron-builder#6397]
* **Electron-Builder Version**:  22.13.1

* **Node Version**:  11.15.0

* **Electron Version**: 5.0.6
* **Electron Type (current, beta, nightly)**: current

electron-updater: 4.3.9

* **Target**: Mac OS

Hi there, 
I can't find any information about how electron-updater fetches information regards the latest release.
The latest release in my case is clearly 1.0.0-beta14 as you can see here: https://github.com/stoefln/repeato-releases/releases

The problem is that when I launch an older version of my software this is what the log shows:
```
Update for version 1.0.0-beta.7 is not available (latest version: 0.9.10, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```
So users don't get the update. What can I do? Shouldn't we document the way version information is fetched?
I also didn't find any information on how the latest.yml and latest-mac.yml files work.

**Comment by mmaietta** [comment]
I think this might be what you're looking for?
> allowDowngrade = false Boolean - Whether to allow version downgrade (when a user from the beta channel wants to go back to the stable channel).

https://www.electron.build/auto-update

**Comment by stoefln** [comment]
@mmaietta unfortunately not.  My problem is that the newest release doesn't seem to be found.

**Comment by stoefln** [comment]
The application I am running is a pre-release, yes (1.0.0-beta7). The latest release (1.0.0-beta14) is not

**Comment by vylqtopcv** [comment]
let set feedUrl host = null, it works for me
