### ISSUE TITLE
No desktop icon or start menu icon from squirrel installer

### ISSUE THREAD

**Issue by brandoncc** [electron-userland/electron-builder#640]
* **Version**: 5.19.1

* **Target**: Windows x64

I am building using squirrel as a target so that I have auto-updating, and I am not getting an icon on the desktop or start menu. How do I configure electron-builder to add both of those things? I searched Google but was unsuccessful. When I built for nsis I got both, but had no auto-update. I see that is in the works though, so I am looking forward to it!

**Comment by brandoncc** [comment]
If anybody else experiences this, I found https://github.com/mongodb-js/electron-squirrel-startup to be exactly what I needed.

**Comment by develar** [comment]
Only NSIS does it. Not Squirrel. `electron-squirrel-startup` is recommended, yes.

**Comment by develar** [comment]
Duplicates #551
