### ISSUE TITLE
Latest electron-updater version not published to npm ?

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#6408]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: 14

* **Electron Version**: 13
* **Electron Type (current, beta, nightly)**:

* **Target**: 

Latest `electron-updater` version published to NPM is 4.3.9.

But it seems that `electron-updater` v4.4.3 is available (since `electron-builder` v22.11.11 -> [see changelogs](https://github.com/electron-userland/electron-builder/releases/tag/v22.11.11)).

This is a problem for me because this bug https://github.com/electron-userland/electron-builder/pull/5989 is only resolve since `electron-builder` v4.4.0

Is this a bug or could you publish the latest version please ?

**Comment by mmaietta** [comment]
electron-updater@next is 4.6.2
electron-updater@latest needs to be moved forward still, I should be able to do that today.

**Comment by popod** [comment]
@mmaietta Thank you for reply !

Hope you could release electron-updater@latest soon in NPM :)
