### ISSUE TITLE
.deb package section

### ISSUE THREAD

**Issue by cGuille** [electron-userland/electron-builder#641]
Hello,

I am trying to specify [the `section` field](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Section) of the Debian package control file.
Currently, my package's control file contains the following line:
```
Section: default
```

I would like to change this `default` value, but it looks like it is not currently supported.
I expected this to be documented in the [Linux build options](https://github.com/electron-userland/electron-builder/wiki/Options#buildlinux).

It seems to [be supported by fpm](https://github.com/jordansissel/fpm/blob/0b104c260501cc7f09e85e8418fa2fdfb7a7e039/templates/deb.erb#L39) that is used to build .deb files. We would need to use [the `category` command argument](https://github.com/jordansissel/fpm/blob/420a76b46f0ce6ede2471e05f90ee4e80e8a5dca/spec/fpm/command_spec.rb#L18); we would probably set its value [around here](https://github.com/electron-userland/electron-builder/blob/01abc3aad1ac71e0d65ff288d252c1439a258f14/src/targets/fpm.ts#L116-L134).

- Could you confirm that it is not currently supported?
- Would you consider a PR about this?

Thank you!

**Comment by develar** [comment]
Workaround (not tested): Add to `build.linux` (development package.json) new field:
```
"fpm": ["--category", "yourCategory"]
```

Yes, `fpm` is not documented because it is only for experiments. You can pass any fpm arg using it (on you own risk :)).

> Would you consider a PR about this?

`app-category-type` must be deprecated and renamed to `category`.  `category` should be specified in the platform-specific options — `mac` or `lunux`. Not in the root because values are different per platform (or we can try to map mac values to linux values, it seems it is possible).

**Comment by develar** [comment]
And consider to use AppImage target instead of deb.

**Comment by cGuille** [comment]
Thank you! This workaround will certainly help us while we set up a proper `category` option.

> `app-category-type` must be deprecated and renamed to `category`.

:+1: 

> `category` should be specified in the platform-specific options — `mac` or `linux`. Not in the root (build) because values are different per platform (or we can try to map mac values to linux values, it seems it is possible).

I think considering `category` as a platform specific option is an easier way to begin with. Mapping mac values to linux (Debian?) values may require an overhead of work because of the maintenance of the category lists and mappings.
I think it's better if it is the app maintainer's work to define which categories to apply to the app on which platform.
Moreover, it seems more flexible to me (from the electron-builder user point of vue).

**Comment by develar** [comment]
> I think considering category as a platform specific option is an easier way to begin with.

👍 but in any case `category` in the `build` should be checked and error thrown (error because it s a new property) — just to be sure that configuration is correct.

**Comment by develar** [comment]
#727 `category` will be used for `Categories` in the desktop entry. `packageCategory` will be added to set deb section
