### ISSUE TITLE
When configuring requireAdministrator the interface automatically disappears

### ISSUE THREAD

**Issue by GreedyWhale** [electron-userland/electron-builder#6413]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: 14.17.0

* **Electron Version**: 15.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 10, x64

When the "requiredExecutionLevel": "requireAdministrator" option is configured, the packaged application will automatically disappear, but can be found in the process list

My configuration：

![微信截图_20211112122658](https://user-images.githubusercontent.com/22760464/141409579-d1efabe6-72c6-4f25-b92d-31f58b2d5803.png)

Example: [electron-builder-error-demo-1
](https://github.com/GreedyWhale/electron-builder-error-demo-1)

Resolved：My System Problem

**Comment by wittDe** [comment]
Hi @GreedyWhale , I have the same problem. Can you be specific about what is the system  problem? thanks.

**Comment by GreedyWhale** [comment]
> Hi @GreedyWhale , I have the same problem. Can you be specific about what is the system problem? thanks.

This problem still exists, I'm not sure why, but my colleague wrote his own startup program and solved it by starting electron with `--no-sandbox`.

Reference: https://www.electronjs.org/zh/docs/latest/tutorial/sandbox#disabling-chromiums-sandbox-testing-only

**Comment by wittDe** [comment]
Using `--no-sandbox` works fine. But I don't know if there will be other side effects.
Some say the problem is because

> Running elevated is not supported by Chromium

https://github.com/electron/electron/issues/32143#issuecomment-1073139870
