### ISSUE TITLE
electron-updater setting autoInstallOnAppQuit=true causes quitAndInstall() error on MacOS

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#6418]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: 16.13.0

* **Electron Version**: 13.5.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS

Our app is using electron-updater by prompting the user to tell us if they want to take the available update (which calls `autoUpdater.downloadUpdate()`) and then prompts the user if they want to install now or on exit.  Although the documentation says `autoUpdater.autoInstallOnAppQuit` is only for Windows and Linux (see doc snippet below), the `MacUpdater` is clearly looking at the `autoInstallOnAppQuit` flag.

```
autoInstallOnAppQuit = true Boolean - Whether to automatically install a downloaded update on app quit (if quitAndInstall was not called before).

Applicable only on Windows and Linux.
```

Setting `autoUpdateOnAppQuit=true` does work on MacOS.  The problem is that, unlike what the documentation says about the behavior and the actual behavior on both Windows and Linux, calling `quitAndInstall()` with `autoUpdateOnAppQuit=true` causes an error (but it seems to eventually perform the update anyway).  

```
info: Found version 0.9.3 (url: WebLogic-Kubernetes-Toolkit-UI-0.9.3-mac.zip, WebLogic-Kubernetes-Toolkit-UI-0.9.3.dmg)
info: Downloading update from WebLogic-Kubernetes-Toolkit-UI-0.9.3-mac.zip, WebLogic-Kubernetes-Toolkit-UI-0.9.3.dmg
debug: updater cache dir: /Users/rpatrick/Library/Application Support/Caches/wktui-updater
info: New version 0.9.3 has been downloaded to /Users/rpatrick/Library/Application Support/Caches/wktui-updater/pending/WebLogic-Kubernetes-Toolkit-UI-0.9.3-mac.zip
info: Download complete, install type: now
warn: The command is disabled and cannot be executed {"code":1,"domain":"RACCommandErrorDomain"}
error: Error: Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Applications/WebLogic Kubernetes Toolkit UI.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:114:48)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
error: Error: Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Applications/WebLogic Kubernetes Toolkit UI.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:114:48)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
error: Application auto-updater failed: The command is disabled and cannot be executed
error: Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Applications/WebLogic Kubernetes Toolkit UI.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:114:48)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
info: / requested
info: /1636779321864-5247.zip requested
info: /1636779321864-5247.zip requested by Squirrel.Mac, pipe /Users/rpatrick/Library/Application Support/Caches/wktui-updater/pending/WebLogic-Kubernetes-Toolkit-UI-0.9.3-mac.zip
```

While I can work around this behavior by setting it to `false` prior to calling `quitAndInstall()` on MacOS, we should really make this work consistently with the documentation and other platforms.

**Comment by robertpatrick** [comment]
@mmaietta i have to say the bot assigning labels is the stupidest bot I have ever seen.  Testing with latest versions to see if this has been addressed already…

**Comment by robertpatrick** [comment]
Upgrading to electron 15.3.1, electron-builder 22.14.7, and electron-updater 4.6.2 resolved the issue...

**Comment by robertpatrick** [comment]
@alimuddins It is working for my app (though I am currently on newer versions than you).  Try downloading and installing [WebLogic-Kubernetes-Toolkit-UI-1.4.0.dmg](https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.4.0/WebLogic-Kubernetes-Toolkit-UI-1.4.0.dmg) and see what happens when you start this older version of the app.  It should give you an Application Update dialog box with three options: `Install Now`, `Install on Exit` or `Ignore Update`.

**Comment by alimuddins** [comment]
@robertpatrick , its working on my MAC, I see your logic is little different.

1) You're downloading the update once user clicks "Install Now". In my case I am downloading the update in
the background by setting autoInstallOnAppQuit = false, then I am asking user whether to install now or later.

Have you tried above case?

**Comment by robertpatrick** [comment]
No, because that use case didn’t add any value for our users over what we have implemented.  If you can create a simple reproducer, you should open a new bug.

**Comment by alimuddins** [comment]
@robertpatrick , I cannot reveal sample app, i have checked internally with the company as it reveals undisclosed information. I am sorry for that.

I also see below error during normal quit and launch update.

Basically test case is - 
Note: this is happening to only specific MAC machine

OS - 12.4
electron = 13.6.1
electron-builder = 23.1.0
electron-updater = 4.6.5

Test case - 

1) Get the auto update downloaded, popup displayed, 
2) Press cancel for update request.
3) Kill the app now manually.
4) Open the app manually, now it tries to update because, appInstallOnQuit  is set to true.

Below error is seen.

<img width="207" alt="image" src="https://user-images.githubusercontent.com/76930713/204209251-0f157998-3689-4d7b-ad9b-f9987a62851e.png">
