### ISSUE TITLE
AutoUpdate deletes everything forcing me to download the installer again manually

### ISSUE THREAD

**Issue by lukasportal** [electron-userland/electron-builder#6420]
* **Electron-Builder Version**: latest via npx

* **Node Version**: 16.13

* **Electron Version**: 13.5.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: win-x86;win - ia32

AutoUpdate finds and downloads the new version correctly, but when it tries to install it, it wipes out every single file from the installation folder and does not install the new one

the only way to have it running is to download again via browser and install it

**Comment by ejwilburn** [comment]
We're seeing the same issue.  This used to happen with just the advanced installer (not the one-click installer) and switching to the one-click installer fixed it for us but now auto-update is broken completely on Windows.

Windows 10 x64 in my test environment.

**Comment by ejwilburn** [comment]
This looks like a dupe of #6329

**Comment by lukasportal** [comment]
Yes!
this comment https://github.com/electron-userland/electron-builder/issues/6329#issue-1022662906 is a good workaround, but still think a fix should be in place
anyways, closing here
