### ISSUE TITLE
fresh installation header always shows "Choose Uninstallation Options"

### ISSUE THREAD

**Issue by rwlnd** [electron-userland/electron-builder#643]
* **Version**: 5.12.1
* **Target**: nsis

Even when installing my nsis-generated exe on a machine where it has never been installed before, the header of the first step of the installer always says: 
```
Choose Uninstallation Options
Which installation should be removed?
```

**Comment by develar** [comment]
>  5.12.1

Please use 5.22.2

> Target: nsis

one-click installer or do you have custom options?

**Comment by rwlnd** [comment]
I'm sorry I am in fact using 5.22.2,  I just updated, my bad.
I am not using onClick and that's the only custom nsis setting I have in my package.json build section

**Comment by develar** [comment]
> I am not using onClick and that's the only custom nsis setting I have in my package.json build section

Please, could you please post your custom `nsis`? It will help me to reproduce and fix issue quickly.

**Comment by rwlnd** [comment]
this is my build config , nothing special as you can see:

"build": {
    "appId": "ID",
    "win": {
      "title": "APP",
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false
    },
    "directories": {
      "app": ".",
      "output": "dist"
    }
  }

I'm currently making a x64/x32 build using: build --arch all
