### ISSUE TITLE
feat: Gitlab Packages as a Provider

### ISSUE THREAD

**Issue by tomaspiaggio** [electron-userland/electron-builder#6435]
* **Electron-Builder Version**: ~22.11.1

* **Node Version**: v14.15.4

* **Electron Version**: 12.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: any

# Gitlab Packages as a Provider for Auto Update

I have a working CI pipeline that builds the project with electron builder and pushes the built app to gitlab packages. Additionally, I configured a generic provider for auto update but I think this could be an option for an actual provider.

It's pretty easy to replicate, but reaching here took me some time. I think other people can benefit from this.

**Comment by mmaietta** [comment]
Heya!
This was recently done for Bitbucket publishing. You can find the commit here: https://github.com/electron-userland/electron-builder/commit/a94532164709a545c0f6551fdc336dbc5377bda8
If you're willing, please submit a draft PR and I'm happy to work through it with you to get it integrated.

**Comment by tomaspiaggio** [comment]
Ok @mmaietta, I have an initial implementation for this. How should I test it? Are there any unit tests?

**Comment by mmaietta** [comment]
Most excellent!

Here are som example unit tests:
- publisher
https://github.com/electron-userland/electron-builder/blob/759fe3a3bc0a4d3a187ace765a8c9767f6fe09e3/test/src/ArtifactPublisherTest.ts#L129-L153
- provider
https://github.com/electron-userland/electron-builder/blob/759fe3a3bc0a4d3a187ace765a8c9767f6fe09e3/test/src/updater/nsisUpdaterTest.ts#L50-L71

**Comment by gwendalF** [comment]
@tomaspiaggio Do you need help with this feature? It is something I am trying to use so I Can help you to make it works if needed

**Comment by tomaspiaggio** [comment]
@gwendalF I had most of the implementation done but couldn't test it because more urgent things came up. I could help you and provide you access to my forked repo so we can finish it together. What do you think?

**Comment by gwendalF** [comment]
@tomaspiaggio Ok perfect. I used a generic server instead but I think having a gitlab server would be really usefull for many users
