### ISSUE TITLE
Failed to load Pepper Flash plugin in an Electron app bundled in an AppImage

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#644]
* **Version**: latest

* **Target**: Linux (AppImage)

Please consider the following sample project: https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin

I've cloned it, copied Flash plugin to app folder, completed the remaining steps to be able to build it with electron-builder and built it with AppImage target.

However, when I try to run the AppImage, it doesn't load the plugin. Instead, it renders a message like "Unable to load the plugin"

Here is the output of my `ldd libpepflashplayer.so` command:
```
        linux-vdso.so.1 (0x00007ffe073bb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb3837f1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb3835e9000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fb383260000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb382f5c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb382d45000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb382b27000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb382785000)
        /lib64/ld-linux-x86-64.so.2 (0x00005640c7d3a000)
```

Should I include any of these libs as a dependency in my build process?

Related issue in AppImageKit project: https://github.com/probonopd/AppImageKit/issues/206

**Comment by develar** [comment]
> Should I include any of these libs as a dependency in my build process?

As workaround, but electron-builder should do it for you.

**Comment by lbssousa** [comment]
I'm trying another approach: moving out libpepflashplayer.so from `app/` folder (so it won't be bundled in `app.asar` file) and installing it in the same folder as `libnode.so` et al. via `build` property `"extraFiles": "libpepflashplayer.so"`.

Now my question is: which is the right way to reference the correct libpepflashplayer.so new path in script `app/main.js`? Should I use an absolute path or a relative one to `__dirname`?

**Comment by develar** [comment]
Ah, I missed that it is not bundled, but user `so` file.

> Should I use an absolute path or a relative one to __dirname?

relative one

**Comment by develar** [comment]
I don't see how electron-builder can automate it.

`extraFiles` or `extraResources ` is a right way to do it. Also, please note, macro `${os}` is available for you in this patterns.

**Comment by lbssousa** [comment]
Sorry for the naive question, but I'm still in trouble to reach the libpepflashplayer.so new path relatively to `__dirname` in `app/main.js`. Should it be `${__dirname}/../`, `${__dirname}/../../` or something else?

Remember that I'm currently installing this file via `extraFiles` property, so it goes on the same folder as `libnode.so`, `libffmeg.so`, the main binary called by `AppRun` et al.

**Comment by lbssousa** [comment]
I've got it! The correct path (for Linux) is `${__dirname}/../../`, if installed via `extraFiles`, or `${__dirname}/../../resources`, if installed via `extraResources` one.

I would like to suggest you to include these details in electron-builder documentation.

**Comment by develar** [comment]
> ${__dirname}/../../resources, if installed via extraResources

Your app files in the `resources`, so, just `${__dirname}/../..` should be (if I am not wrong).

> I would like to suggest you to include these details in electron-builder documentation.

Paths? It depends on file location. Or info in general? Pull Request welcome ;) (https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation "Don't edit wiki directly. Instead, edit files in the /docs.")

**Comment by lbssousa** [comment]
I mean "general info" about
 * the correct way to bundle Pepper Flash  plugin (why does it seem to fail if I bundle it inside `app/` folder? Should I prefer `extraFiles` or `extraResources` for installing it?), and
 * the correct path to reference it in `app/main.js` script.

I can try to send a PR in the next days. Before that, I wanna try to generalize my sample project to be able to build for Windows as well.

**Comment by develar** [comment]
> why does it seem to fail if I bundle it inside app/ folder? Should I prefer extraFiles or extraResources for installing it?

electron-builder CAN detects `so` files. BUT the next question — what should you do if you support not only Linux, but macOS and Windows? So, `extraResources` is a right way to solve this task because of os and arch available macro.

> I wanna try to generalize my sample project to be able to build for Windows as well.

Hint: "You can use ${os} (expanded to mac, linux or win according to current platform) and ${arch} in the pattern."

**Comment by lbssousa** [comment]
> Your app files in the resources, so, just ${__dirname}/../.. should be (if I am not wrong).

You're (almost) right. Instead of `${__dirname}/../../resources`, I could just use `${__dirname}/../`.

I've tested both possibilities here. I can confirm the following paths in `app/main.js` as the correct ones:
 *  `${__dirname}/../`, if libpepflashplayer.so is installed via `extraResources`.
 *  `${__dirname}/../../`, if libpepflashplayer.so is installed via `extraFiles`.

> So, extraResources is a right way to solve this task because of os and arch available macro.
> Hint: "You can use ${os} (expanded to mac, linux or win according to current platform) and ${arch} in the pattern."

Thanks for the hint!

**Comment by lbssousa** [comment]
A last question: I've put several copies of Flash plugin in my project folder and set up

```
"extraResources": "ppapi-flash-plugin/${os}/${arch}/libpepflashplayer.so"
```

in my devepolment `package.json` file, but my plugin is being copied with its full path to my resources folder (example: `dist/linux/resources/ppapi-flash-plugin/linux/x64/libpepflashplayer.so`). How could I prevent this, so it installs just as `dist/linux/resources/libpepflashplayer.so`?

**Comment by develar** [comment]
@lbssousa Will be fixed.

**Comment by EddieOne** [comment]
TL:DR

put this in package.json `"extraResources": "${__dirname}/../",`

**Comment by EddieOne** [comment]
It's not working for me. I have a folder named flash that has my plugins.

`"extraResources": "${__dirname}/flash/*",`

It doesn't copy the files. Anyone know why?
