### ISSUE TITLE
ENOENT: no such file or directory : app-update.yml

### ISSUE THREAD

**Issue by NijsJonas** [electron-userland/electron-builder#6440]
* **Electron-Builder Version**: 22.14.5
* **Node Version**: 17.1.0
* **Electron Version**: 16.0.1
* **Electron Type (current, beta, nightly)**: current
* **Electron-Updater Version**: 4.6.1
* **Target**:  Windows - Zip

When i run : "npm run dist" the zip file gets created and my app works, but auto-updater doesnt.
the app-update.yml file doesnt get created.

my package.json:
![image](https://user-images.githubusercontent.com/479392/142769262-ac01a508-0cd4-4dbd-bf80-56e96be99310.png)

the error i get :
ENOENT: no such file or directory, open 'C:\Users\jonas\Downloads\AAA\resources\app-update.yml'

**Comment by MLY123** [comment]
Solved？why Closed?

**Comment by gpetrov** [comment]
this is not solved
