### ISSUE TITLE
Fail to run exe file due to javascript error

### ISSUE THREAD

**Issue by allanwxm** [electron-userland/electron-builder#6442]
Hi, I've created a windows desktop app using vue electron builder plugin. When launching the .exe file, an error showed in the console and the app failed to display the login page.

'Uncaught ReferenceError: Cannot access 'l' before initialization
at Object.b (app.69de525b.js:1)'

The error occurred in the following code in app.69de525b.js because const l is accessed before initialization.
```
d73b: function (e, t, a) {
    "use strict";
    a.d(t, "b", function () {
      return l;
    });
    const l = [
        {
          path: "/",
          name: "dashboard",
          component: i["default"],
          meta: { title: "MainPage" },
          redirect: "/dashboard/analysis",
          children: [],
        },
        { path: "*", redirect: "/404", hidden: !0 },
    ]
}
```
I checked the code that is generated by command 'npm run build' and const l is replaced by var l, so no error occurred. How can I fix this error? Thanks
```
node v14.16.0
npm v7.4.2
webpack v4.46.0
vue cli v3.2.1
electron v13.6.2
vue-cli-plugin-electron-builder v2.1.1
```

**Comment by mmaietta** [comment]
That seems to be an error with webpack or vue. electron-builder only packages the code, it does not bundle or minify it.

**Comment by yourenyouyu** [comment]
how to resolve@allanwxm
