### ISSUE TITLE
problems installing nsis-generated exe for all users

### ISSUE THREAD

**Issue by rwlnd** [electron-userland/electron-builder#645]
* **Version**: 5.22.2
* **Target**: nsis - no oneClick - no custom options
* **Operating system**: windows 10
* **Build command**: build --arch all

I've been installing/uninstalling my application using an nsis-generated exe quite a few times now and while I was trying to write down the symptoms of the early behavior, I think I stumbled upon the actual bug.

I was having some troubles installing for "all users". When landing on the final page, I leave the "run APP" option selected, but the application was not opened. There was however a shortcut placed on the desktop and clicking on that opened the application.

After a few installs/uninstalls, I noticed that even the desktop shortcut was no longer placed after installing, although "the installing completed successfully".

After installing/uninstalling a few more times, I opened the installation location of the application (C:\program files(x86)\APP ) to see what was going on, if there were some files left , ... etc

Which lead me to the discovery of the actual problem:

If you close/finish the install wizard too fast, the installation folder stops getting filled with the necessary files. If you quickly press Install, Finish on the installer, only some of the files are copied. 
IF however you keep the final page of the installation wizard open, you can see all the files getting added in C:\program files(x86)\APP , the desktop icon gets added, and if you THEN click the finish button, everything works as expected.

The installer should be kept in the "installing" stage until all files are copied and after that show the final page. I guess this is the case when installing for "just me".

Feel free to contact me if you want additional info

**Comment by rwlnd** [comment]
Just to follow up on this issue, if you rightclick the installer and run it as administator, then it works correctly..

**Comment by develar** [comment]
It seems due to UAC impl. outer process kills inner before. Strange. *** Windows :(

**Comment by FromStoneage** [comment]
@rwlnd @develar I too observe the same behaviour on Windows 10 with nsis installer. Only works when running it as administrator, regardless of the UAC permission level.

**Comment by develar** [comment]
I hope it will be fixed in several days. Keep in mind — default is one-click and it is the reason why it is not fixed ASAP.

**Comment by develar** [comment]
Please try 5.31.1

**Comment by develar** [comment]
Closed, feel free to reopen if still occurs.

**Comment by RyanEwen** [comment]
Same issue seems to exist on 7.7.0 for me

**Comment by igorcandeia** [comment]
Same to me. "electron-builder": "^10.5.0"

**Comment by develar** [comment]
@igorcandeia Please see #767, it seems it is your issue.

**Comment by igorcandeia** [comment]
Run it as administator, then it works correctly. But lay users do not know this
