### ISSUE TITLE
PKG not installing applications

### ISSUE THREAD

**Issue by Thyssenkrupp234** [electron-userland/electron-builder#6454]
Latest version grabbed from `npx electron-builder`

Latest version of node

Used electron-forge to create boilerplate, electron ver. 16.0.2
Current
N/A

macOS: PKG
Whenever I build my application for macOS, it never actually installs the application to the applications folder. Although Suspicious Package says it installs the app to `/Applications`, but never actually does.

my `electron-builder.json` file config:

{
    "appId": "com.lincolnmuller.osleadship",
    "productName": "Osler Leadership app",
    "copyright": "Lincoln Muller",
    "directories": {
        "output": "out",
        "buildResources": "build-res"
    },
    "dmg": {
        "window": {
            "width": "700",
            "height": "700"
        },
        "contents": [
            {
                "x": 100,
                "y": 100
            },
            {
                "x": 300,
                "y": 100,
                "type": "link",
                "path": "/Applications"
            }
        ]
    },
    "pkg": {
        "allowCurrentUserHome": "true",
        "installLocation": "/Applications",
        "allowAnywhere": "true",
        "welcome": "welcome.rtf",
        "conclusion": "summary.rtf"
    },
    "mac": {
        "target": [
            "dmg",
            "pkg"
        ]
      },
      "win": {
          "target": {
              "target": "nsis",
              "arch": [
                  "ia32",
                  "x64"
              ]
              
          }
      },
    "linux": {
        "target": "AppImage",
        "category": "Utility"
    }
}

and my `package.json` config:

{
  "name": "osler-leadership-offline",
  "productName": "osler leadership (offline)",
  "version": "v0.0.3",
  "description": "Osler Leadership offline variant",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\""
  },
  "keywords": [],
  "author": {
    "name": "Thyssenkrupp234",
    "email": "76831903+Thyssenkrupp234@users.noreply.github.com"
  },
  "license": "MIT",
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "osler leadership (offline)"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  },
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0",
    "save-dev": "^0.0.1-security"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.61",
    "electron-builder": "^22.14.5",
    "@electron-forge/maker-deb": "^6.0.0-beta.61",
    "@electron-forge/maker-rpm": "^6.0.0-beta.61",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.61",
    "@electron-forge/maker-zip": "^6.0.0-beta.61",
    "electron": "16.0.2"
  }
}

Any help would be great. For now, I am using a application known as "Packages" to actually build my .pkg files, until this is resolved. Thanks.

**Comment by Thyssenkrupp234** [comment]
I apologize for the bad formatting, no idea why the linux blurb is capitalized.

**Comment by Thyssenkrupp234** [comment]
I noticed the PKG does upgrade the app if already in the directory, otherwise does not write app

**Comment by holmesadrianh** [comment]
This is relevant to me. When I build my electron app and then run the package on my mac, the installation seems successful but the app file is never really copied or installed.

**Comment by rkbhochalya** [comment]
@holmesadrianh this is the case for me as well.

**Comment by somidad** [comment]
Is it still a valid issue?

Recently, I build Windows app on macOS (Apple Silicon, I am not sure whether CPU arch does matter, anyway...).

But when I run the installer on Windows, it does not install anything but leaves only `Uninstall <appname>.exe` in the app directory (`AppData/Local/Programs/<appname>`)

**Comment by theRatramnus** [comment]
i have the same problem 😭

**Comment by alinmateutdev** [comment]
It might be because of [this issue](https://github.com/electron-userland/electron-builder/issues/5135)
