### ISSUE TITLE
create installer in specific language

### ISSUE THREAD

**Issue by rwlnd** [electron-userland/electron-builder#646]
* **Version**: 5.22.2
* **Target**: nsis - no oneClick - no custom options
* **Operating system**: windows 10
* **Build command**: build --arch all

I've been spending quite some time in the documentation of electron-builder AND nsis.

I am looking for a way to set the language of the installer to a specific language. From looking at examples like http://nsis.sourceforge.net/Examples/languages.nsi and seeing how this was implemented in the boringInstaller.nsi, i can tell that the English language is enforced using  `!insertmacro MUI_LANGUAGE "English"`

Adding a custom include and adding the additional language there doesn't work as it is the first inserted language that is used by default.

Any plans on making the language easily customizable without having to modify the build templates or use a custom script? Or is there another way to set the UI language of the installer ?

**Comment by develar** [comment]
Installer will automatically detect user lang. Our custom string is not translated, please file PR. This issue will be closed.

<img width="539" alt="screen shot 2016-08-08 at 08 56 00" src="https://cloud.githubusercontent.com/assets/350686/17471628/f57c9ae0-5d45-11e6-9e61-28207bbabe35.png">

<img width="531" alt="screen shot 2016-08-08 at 08 49 27" src="https://cloud.githubusercontent.com/assets/350686/17471587/a69ad9a0-5d45-11e6-8081-7e64cc4821ae.png">
