### ISSUE TITLE
Native compilation doesn't happen if the package is using prebuilt (eg leveldown)

### ISSUE THREAD

**Issue by cosmosgenius** [electron-userland/electron-builder#647]
electron-builder@5.22.2

OSX el capitan x64

My app directory package.json has a dependency to leveldown 1.4.0. Since leveldown is natively compiled, I was expecting install-app-deps to compile with electron-prebuilt deps on dev package.json. While installing leveldown, it uses prebuilt to download native binary instead of compiling.

Passing `--build-from-source` as args in the `doSpawn` function fixes the issues and compile with the correct version.

**Comment by cosmosgenius** [comment]
Is there any update on this? or is there some option which can force a rebuild in such cases?

**Comment by develar** [comment]
Is it possible to attach sample project?

**Comment by cosmosgenius** [comment]
sample project https://github.com/cosmosgenius/electron-leveldb

**Comment by cosmosgenius** [comment]
What i am doing currently is modifying the `npmExecArgs ` variable in `spawnNpmProduction` by adding `--build-from-source` to args list. Is there anyway to passing this args to install-app-deps? That would solve this issue.

**Comment by develar** [comment]
Thanks for clear explanation and sample project. `--build-from-source` added by default.
