### ISSUE TITLE
electron-updater cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Pulset** [electron-userland/electron-builder#6477]
* **Electron-Builder Version**:  22.14.10

* **Node Version**: 14.17.6

* **Electron Version**: 4.2.9

* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.6.1

* **Target**:  mac

v4.6.1 electron-updater cannot find module 'fs/promises', I rollback electron-updater to 4.3.9 is ok

**Comment by search5** [comment]
It has been confirmed that this error does not occur if the node version for building the electronjs app is set to 14 or higher and the electronjs version is changed to the last version of the 12 version.

**Comment by Pulset** [comment]
@search5 , I upgrade Node to 14, it also throw error cannot find module 'fs/promises'

**Comment by search5** [comment]
@Pulset  Please try uploading the version of Electron as well as Node js to version 12 or higher. In my case, Electron was 11, which caused the problem.

**Comment by zlshames** [comment]
I'm also having this issue on 4.3.5 using node version 14.17.6. Attempting to update package to the latest to fix it. If that doesn't work, i'm going to try what @Pulset suggested

**Comment by Pulset** [comment]
@zlshames I fixed electron-updater to v4.3.9

**Comment by ahmadwaliesipick** [comment]
> 4.3.9

Not works for me

**Comment by maugustosemperfi** [comment]
> > 4.3.9
> 
> Not works for me

In the issue [#6456 ](https://github.com/electron-userland/electron-builder/issues/6456), aymengraoui said to " remove ^ from package json worked" and it actually worked well. Hope it solves the problem temporally for you too

**Comment by suandicreative** [comment]
consider upgrade to electron-updater@5.0.0
it has patch changes Replacing fs/promises with fs-extra :rocket: to support legacy versions of electron

**Comment by berkon** [comment]
Same with (latest npm) version 4.6.5. I can confirm that everything works fine when going back to verion 4.3.1.

**Comment by bksubhuti** [comment]
I did npm upgrade and deleted the node module dir and did npm install and it still did not work.  ubuntu 22.04

**Comment by loveheenavasu** [comment]
> > > 4.3.9
> > 
> > 
> > Not works for me
> 
> In the issue [#6456 ](https://github.com/electron-userland/electron-builder/issues/6456), aymengraoui said to " remove ^ from package json worked" and it actually worked well. Hope it solves the problem temporally for you too

Thanks a lot, buddy, It worked for me.

**Comment by SkybuckFlying** [comment]
This repo is affected to, how to properly fix it ????????????????????????????????????????????????????????

Been struggling for months with this, still not fixed. I don;'t unde5rstand it well enoiugh, but slowly getting there:

https://github.com/vitelabs/vite-wallet

**Comment by SkybuckFlying** [comment]
I guess this line must be updated, very maybe then it works, but to what version ? ;) anyway I will ask AI about it.

        "electron-updater": "^4.3.5",

Thanks for screwing this project hard ! NOOOTTT. Shame on you

**Comment by mmaietta** [comment]
@SkybuckFlying Please see earlier comment https://github.com/electron-userland/electron-builder/issues/6477#issuecomment-1079696594

**Comment by SkybuckFlying** [comment]
I found a way to fix the vitex wallet, it required updating the updater to a newer version from what I can remember.

Alas, the vite blockchain and exchange is badly managed and I must say goodbye to it for now.
