### ISSUE TITLE
Unable to autoUpdater in macos (error code: InvalidAuthenticationInfo)

### ISSUE THREAD

**Issue by certong0507** [electron-userland/electron-builder#6479]
* Electron-Builder Version:  **^22.9.1**

* Node Version: **v14.15.0**

* Electron Version: **^9.1.1**

* Electron-Updater: **^4.3.5**

* Build Target: **DMG**
* Publish Provider: **Github**

When I try to update my electron app, it prompt this error box, below is the full error message and attached is the screenshot for reference: 

```
HttpError: 400 
"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.\nRequestId:1ba4da8e-e01e-003c-0bee-eb0ba2000000\nTime:2021-12-08T04:44:04.1715259Z</Message></Error>"
Headers: {
  "status": "400",
  "content-type": "application/xml",
  "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
  "x-ms-request-id": "1ba4da8e-e01e-003c-0bee-eb0ba2000000",
  "fastly-restarts": "1",
  "accept-ranges": "bytes",
  "date": "Wed, 08 Dec 2021 04:44:04 GMT",
  "via": "1.1 varnish",
  "x-served-by": "cache-tyo11930-TYO",
  "x-cache": "MISS",
  "x-cache-hits": "0",
  "x-timer": "S1638938644.928290,VS0,VE326",
  "content-length": "298"
}
at createHttpError (/Users/xxx/yyy/React/aaa-bbb-ccc/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
at IncomingMessage.<anonymous> (/Users/xxx/Workspace/React/aaa-bbb-ccc/node_modules/builder-util-runtime/out/httpExecutor.js:201:18)
at IncomingMessage.emit (events.js:223:5)
at endReadableNT (_stream_readable.js:1185:12)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
<img width="249" alt="Screenshot 2021-12-08 at 2 07 40 PM" src="https://user-images.githubusercontent.com/29158694/145157980-e2c190de-92ad-437e-8705-63832405b566.png">

**Comment by orgertot** [comment]
I can confirm this problem.

Electron-Builder Version: ^22.10.5
Node Version: v14.15.0
Electron Version: ^12.0.1
Electron-Updater: ^4.3.8
Build Target: NSIS
Publish Provider: Github

It seems Github has changed its APIs again... Seens to be related to https://github.com/electron-userland/electron-builder/issues/5595

**Comment by trixie88** [comment]
Same here. If you are using a GitHub repo for releases then it is the same issue that had happened again back in February https://github.com/electron-userland/electron-builder/issues/5595.

At that time, in order the issue to be fixed, there was a change server-wise from GitHub which fixed the issue. Probably that fix was now removed. I contancted GitHub support again now and i wait for their response.

You can fix this issue by doing this https://github.com/electron-userland/electron-builder/issues/5595#issuecomment-770019745 but this is not a viable solution, as users have older versions  installed and can't update to the new one which would have this fix.

**Comment by trixie88** [comment]
I contacted Github support and they provided a fix on their server side for this. Issue seems to be fixed.
Checked it on windows and updates work again.

**Comment by certong0507** [comment]
@trixie88 holy moly! thank you so much for contacting Github support on this issue.
