### ISSUE TITLE
Electron builder msi is not working

### ISSUE THREAD

**Issue by acuemor** [electron-userland/electron-builder#649]
* **Version**: 5.22.1

* **Target**: Windows x64

I have an electron app running. I build my app with electron builder and it works fine. It creates an .exe, but I really want my application installed in Program Files via .msi.

I set msi: true in my [package.json](https://github.com/electron-userland/electron-builder/files/403381/package.txt). 

This creates a msi when the application is builded, but when I run de msi, nothing seems to happen:

![installer](https://cloud.githubusercontent.com/assets/9961207/17430891/332b07d8-5af7-11e6-8de6-3ae9c69c117f.png)

I'm on Windows 7 x64 platform.

**Comment by develar** [comment]
Duplicates #608 

Instead of MSI, you can set target to nsis and enable per machine installation.
