### ISSUE TITLE
More advanced extraFiles

### ISSUE THREAD

**Issue by ha-D** [electron-userland/electron-builder#650]
I have a project structure such as below:
```
└── MainProject
    ├── OtherProject
    │   ├── app
    │   └── dist
    ├── app
    └── dist
```
Where `OtherProject` is a separate project with its own git repository. I want to have the binary outputs of `OtherProject` to be included in the MainProject bundle, I'm using the `extraFiles` option to do so. The directory structure I want to get from my build is (for osx):
```
└── Contents
    ├── Frameworks
    ├── Info.plist
    ├── MacOS
    │   ├── mainproject
    │   └── otherproject
    └── Resources
```
But since `extraFiles` copies everything with the original directory structure relative to the project root, I can only get:
```
└── Contents
    ├── Frameworks
    ├── Info.plist
    ├── MacOS
    │   └── mainproject
    ├── OtherProject
    │   └── dist
    │       └── otherproject
    └── Resources
```

Although it's possible to get the app content structure I want by restructuring the directories before build, it's kind of an inconvenience.

I propose that aside from the glob patterns, `extraFiles` also accepts JSON objects with a structure such as:
```
{
  "from": "path/to/src",
  "to": "path/to/dst",
  "filter": ["glob patterns"]
}
```
Where `from` specifies the base directory to be copied from relative to the project root, `to` specifies the directory to be copied to relative to the app's content directory and `filter` specifies patterns to match when copying.

This would effectively solve issue #597 as well, as `from` can be a parent directory.

If you approve of this, I could send a pull request myself.

**Comment by develar** [comment]
Related https://github.com/electron-userland/electron-builder/issues/644#issuecomment-237775111

**Comment by develar** [comment]
:+1: PR welcome.
* os and arch patterns should be supported in the from and to
* to is optional and defaults to app contents (as now).
