### ISSUE TITLE
Invalid nuget output filename

### ISSUE THREAD

**Issue by jzvelc** [electron-userland/electron-builder#651]
* **Version**: 5.22.2

* **Target**: win squirrel

When building and publishing for win-squirrel output filenames of nuget packages differ from other outputs. Example (note the dot after beta):
someapp-0.0.1-beta.1-win.zip
someapp-Setup-0.0.1-beta.1.exe
someapp-0.0.1-beta1-full.nupkg (here beta1 is not beta.1 - dot is missing)

This causes issues with update server because the actual version of app is `0.0.1-beta.1` and not `0.0.1-beta1`. When we request an update with a following version filename will be resolved to someapp-0.0.1-beta.1-full.nupkg which doesn't exist. This might be an issue with the update server but I have tried it with both (nuts and squirrel-updates-server) and both fail. Any idea why the dot is escaped? Our current workaround is to avoid the dot and use channels like 0.0.1-beta1, 0.0.2-beta2 because this produces outputs with consistent filenames.

**Comment by develar** [comment]
Unfortunately, it cannot be fixed. It is how Squirrel.Windows and nuget works. https://github.com/electron/windows-installer/blob/master/src/index.js#L14

As a proper solution, electron-builder support NSIS target instead of Squirrel.Windows (auto-update will be implemented soon).
