### ISSUE TITLE
Disable resizing DMG window in MacOS?

### ISSUE THREAD

**Issue by hkors** [electron-userland/electron-builder#6512]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 16.13.0

* **Electron Version**: 15.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**:  MacOS

Hello,

I was wondering whether it is possible to disable resizing of a DMG window in MacOS? 

According to https://www.electron.build/configuration/dmg, the default window size is 540 x 380. So I created a PNG background image with the same dimensions. However, when the user resizes the window, the background image stays in the upper left corner, while on the right and bottom a plain white background appears. 

Is there something to do about that?

**Edit:** If I close the DMG window and reopen it, then it has the size when it was closed the time before. It doesn't reset its size to the default, even if I add this to my `package.json`:

```json
"dmg": {
    "window": {
        "width": 540,
        "height": 380
    }
}
```

**Comment by mmaietta** [comment]
IIRC that's just the default behavior of MacOS.  The dmg window width/height is a suggested size for Finder to open the window as if user settings are to always open a new window, otherwise it seems Mac will reuse previous settings.
