### ISSUE TITLE
Cannot display Chinese alert title correctly

### ISSUE THREAD

**Issue by haydenull** [electron-userland/electron-builder#6515]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 14.17.0

* **Electron Version**: 14.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows

1. set productName to "测试中文"
2. build a new package
3. exec `alert(123)` in page DevTools
4. alert title is garbled

This problem only occurs with:
```
win: {
  "target": {
      "target": "nsis",
      "arch": "ia32"
  }
}
```

![image](https://user-images.githubusercontent.com/17695989/147457504-a07ce0c0-a277-4640-ac7c-f65bce628d7d.png)

**Comment by robertpatrick** [comment]
@haydenull Does the title display correctly when running your electron app in development mode (i.e., running via node.js directly) prior to building the executable/installer?

**Comment by haydenull** [comment]
I'm using [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) to create my project. The title is `electron.exe` when running `npm start`.

**Comment by mmaietta** [comment]
Can you try this patch? https://github.com/electron-userland/electron-builder/issues/6232#issuecomment-918706699
I think it may be related to the charset makensis is using
