### ISSUE TITLE
Docker Hub inconsistent or missing tags

### ISSUE THREAD

**Issue by iAlexanderMoon** [electron-userland/electron-builder#6519]
Image: Tags
* fd11d1fea82f: base, base-05.21
* 837f5cbec373: latest, 14, 14-05.21
* b44981dcdc60: wine
* e131c776f376: chrome, wine-chrome-05.21
* a623432c159a: wine-mono, wine-mono-05.21

__Expected but missing based on the above: wine-05.21__

Some additional tags that might be considered based on the idea that 14 is important as the version of Node and 05.21 is the release version

* 14-wine, 14-wine-05.21
* 14-wine-chrome, 14-wine-chrome-05.21
* 14-wine-mono,  14-wine-mono-05.21

If these tags are desired it would be nice to have them applied to the existing images.

I'd be willing to make a pull request expecting to modify docker/build.sh for going forward if that helps.

Thank you for all your work on this project.

**Comment by mmaietta** [comment]
@develar can you assist here? That and/or provide me access to electron-builder dockerhub account so I can manage the docker images

**Comment by mmaietta** [comment]
Just pushed images with a more consistent tagging nomenclature
Build/tag script: https://github.com/electron-userland/electron-builder/blob/master/docker/build.sh
