### ISSUE TITLE
Building Windows with `electron-builder -w --x64 --ia32` causes autoupdate to fail due to naming mismatch

### ISSUE THREAD

**Issue by moughxyz** [electron-userland/electron-builder#6536]
When using the command `electron-builder -w --x64 --ia32`, three executables are created:

```shell
app-1.0.0-win.exe
app-1.0.0-win-x64.exe
app-1.0.0-win-ia32.exe
```

When a user uses `app-1.0.0-win-x64.exe` to install the application, and a new 1.0.1 version is released with the same 3 asset types, the autoupdater looks for `app-1.0.1-win.exe` **_without_** the _x64_ suffix:

> [info]  Checking for update
> [info]  Found version 1.0.1 (url: app-1.0.1-win.exe, app-1.0.1-win-x64.exe, app-1.0.1-win-ia32.exe)
> [info]  Downloading update from app-1.0.1-win.exe, app-1.0.1-win-x64.exe, app-1.0.1-win-ia32.exe
> [info]  Download block maps (old: "https://github.com/app/desktop/releases/download/v1.0.0/app-1.0.0-win.exe.blockmap", new: https://github.com/app/desktop/releases/download/v1.0.1/app-1.0.1-win.exe.blockmap)
> [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://github.com/app/desktop/releases/download/v1.0.0/app-1.0.0-win.exe.blockmap", status 404: 

This fails because the asset _without_ the x64 suffix was never uploaded.

**Expected outcome:**

The autoupdate script looks for `app-1.0.0-win-x64.exe` instead of `app-1.0.0-win.exe`.

**Ancillary question:**

What's the difference between `app-1.0.0-win.exe` and `app-1.0.0-win-x64.exe`? `app-1.0.0-win.exe` is almost double the size of `app-1.0.0-win-x64.exe`.

---

"electron-builder": "22.14.5"
"electron-updater": "^4.6.1"
"electron": "^16.0.4"

**Comment by mmaietta** [comment]
`app-1.0.0-win.exe` is the universal build (contains both x64 and i32). Previously it wasn't possible to generate individual installers for each bitness, so I'm guessing the electron-updater is hardcoded to not look for bitness specific binaries.
