### ISSUE TITLE
How do we configure custom locations for 'resource' and 'locals' directory for electron application

### ISSUE THREAD

**Issue by buddy9389** [electron-userland/electron-builder#6538]
* **Electron-Builder Version**: 22.13.0

* **Node Version**: 16.12.0

* **Electron Version**: 14.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: win x64

- Presently on building electron application 'resources' folder gets created at 'dist/win-unpacked'. 
- 'locals' folder gets created at 'dist/win-unpacked' on running electron.exe 
- Is there any way we can configure custom location for 'resources' and 'locals' folders?
- So, that in place of 'dist/win-unpacked' folder gets created at custom location.

Please help.

**Comment by mmaietta** [comment]
I'm not sure if that's possible. I was always under the impression that it was hardcoded to chromium.
