### ISSUE TITLE
Issue with repetitive "macOS wants to make changes" dialog during code signing.

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#6542]
```
> ./node_modules/.bin/electron-builder --version
22.14.5
> node -v
v17.3.0
> ./node_modules/.bin/electron --version
v12.0.7
```

* **Target**:  MacOS arm64

I'm having an issue with my build script asking me for permissions during code signing. I get this popup and I've entered my username and password about 10 times now and its just a huge pain. I just get another popup, one after the other...

<img width="1368" alt="Screen Shot 2022-01-11 at 1 04 17 AM" src="https://user-images.githubusercontent.com/1794527/148913801-1431dd5f-3647-4519-a601-42d88b2fe096.png">

<img width="1417" alt="Screen Shot 2022-01-11 at 1 12 47 AM" src="https://user-images.githubusercontent.com/1794527/148914091-d849a60a-ff6e-4cb5-b60d-7ce39f5028bc.png">

I believe there used to be an "Always Allow" option that I'm not seeing anymore...

Any thoughts?

**Comment by mmaietta** [comment]
That's not an issue with electron-builder but rather changes that Apple made to their system in the name of bettering security.

An alternative solution is to generate a base64 string of the cert file and provide that to electron-builder via `CSC_LINK`. It won't need to access your System or Login keychains then, so you shouldn't get that popup.
