### ISSUE TITLE
Unable to build MacOS anymore

### ISSUE THREAD

**Issue by vtebano13** [electron-userland/electron-builder#6545]
* **Electron-Builder Version**: "19.56.2"
* **Electron-Packager**: "8.2.0"

* **Node Version**: "14.15.4"

* **Electron Version**: "^4.2.12"

* **Target**: "MacOS"

The issue is that the Electron Helper files are not found so the build stops.

Error: ENOENT: no such file or directory, open '/www/dist/mac/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'

**Comment by mmaietta** [comment]
Can you please try updating your electron-builder version to latest?

**Comment by vtebano13** [comment]
I tried that before and it didn't work.  I had the config incorrect and once I tried it again it now works.  The is no longer an issue.  Thanks
