### ISSUE TITLE
Modify Windows File Details: Setup.exe and App.exe

### ISSUE THREAD

**Issue by dharders** [electron-userland/electron-builder#655]
* **Version**: 5.23.1

* **Target**: Windows NSIS & Squirrel

In Windows, when you right-click (on either Setup.exe or App.exe) and select `Properties->Details ` a list of file attributes are displayed such as file version, file description etc.

Currently, these can be cleaned up a bit to make the installer/app a bit more professional.
Eg.

- NSIS+Squirrel App.exe: Remove Original Filename "electron.exe"
- NSIS Setup.exe: Add ProductVersion   (data is blank, although file version is set)
- Squirrel Setup.exe: Remove Original Filename "Setup.exe"
- Both: Add option for "LegalTrademarks"

These issues can be easily solved via your bundled dependency `rcedit` **BEFORE** code signing.

```
.\node_modules\rcedit\bin\rcedit.exe "AppOrSetup.exe" --set-version-string "LegalTrademarks" "My Trademark™"
.\node_modules\rcedit\bin\rcedit.exe "AppOrSetup.exe" --set-version-string "OriginalFilename" ""
```

Another issue is setting the Language to something other than English US. But currently `rcedit` doesn't do this from command line, although I think it is possible. I submitted an issue with the atom/rcedit repo [here ](https://github.com/atom/rcedit/issues/18) a while ago but still haven't had a response. Don't particularly want to fork their repo, but if they don't respond I might have to when I eventually get time. Check out the issue for more details on how I'd set the Language/Locale code.

As for the LegalTrademarks, may I suggest putting the option in `build.win` for scripts to pick up ?

**Comment by develar** [comment]
> NSIS+Squirrel App.exe: Remove Original Filename "electron.exe"
> Squirrel Setup.exe: Remove Original Filename "Setup.exe"

Fixed.

> NSIS Setup.exe: Add ProductVersion (data is blank, although file version is set)

Fixed.

> Both: Add option for "LegalTrademarks"

`win.legalTrademarks` added.

> Another issue is setting the Language to something other than English US. 

Please file separate issue, this issue will be closed. PR welcome to fix it :)
