### ISSUE TITLE
Built static assets are missing in build *.app

### ISSUE THREAD

**Issue by sergeybekrin** [electron-userland/electron-builder#657]
* **Version**: 5.23.2
* **Target**: macos

I'm using single package.json project structure and building app to ./dist folder.
Once packaged, ./dist folder is ignored and missed in final executable *.app.
I guess built resources are [ignored internally](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L171). Is there are any way to avoid this?

My `directories` setup is:
```json
  "directories": {
	"buildResources": "dist",
	"output": "release"
  }
```

**Comment by develar** [comment]
Please change https://github.com/electron-userland/electron-builder/wiki/Options#directories

**Comment by develar** [comment]
Hmm... are you sure? Have you checked `app.asar`?

**Comment by sergeybekrin** [comment]
@develar yep, everything is bundled (with default `file` glob, event node_modules) except `dist` directory. Setting `files` directly to `[ "package.json", "main.js", "dist/**/*" ]` does't help.

**Comment by sergeybekrin** [comment]
I suppose this is because of `buildResourcesDir` being ignored in [platformPackager.ts](https://github.com/electron-userland/electron-builder/blob/master/src/platformPackager.ts#L171)

**Comment by develar** [comment]
Well, you should not include build resources in your app — icons and other stuff should be excluded.  Do not set `buildResources` to your packaged app directory.

**Comment by sergeybekrin** [comment]
@develar `dist` contains bundles produced by webpack in my case. What is the point of `buildResources` then?

**Comment by develar** [comment]
> What is the point of buildResources then?

`buildResources` directory contains resources required to build your app in a packaged or distributable form — icons, installer templates, entitlements and so on. It is not directory for app resources.

**Comment by develar** [comment]
Where did you put application icons — `icons.incs`?

**Comment by sergeybekrin** [comment]
> `buildResources` directory contains resources required to build your app in a packaged or distributable form — icons, installer templates, entitlements and so on. It is not directory for app resources.

That makes sense now. My `icon.icns` were bundled with app itself to `dist` directory.
I wish this to be in the docs. What do you think?

**Comment by develar** [comment]
> My icon.icns were bundled with app itself to dist directory.

And that's is very bad, because it adds unnecessary weight.

> I wish this to be in the docs. What do you think?

+100. I dream about it. #357

**Comment by moaxaca** [comment]
This thread is super helpful, thanks from the future.
