### ISSUE TITLE
FYI: Publisher-github uploads files, but github does not list anything under Releases (GitHub bug?)

### ISSUE THREAD

**Issue by catpea** [electron-userland/electron-builder#6572]
@electron-forge/publisher-github: ^6.0.0-beta.63

This maybe a github bug that I want you to be aware of.

npm run publish will upload files, but they will not appear.

Github will state unter the Releases section on the right hand side:
"No releases published"

If you manually create a new tag via the github interface, with the same name as a release published with publisher-github then the files will appear.

Furthermore, more information is requred in publisher-github about what kinds of permissions are required to create the GITHUB_TOKEN (I only enabled repo [which includes private repo])

I also post this issue to make everyone aware that you are uploading files to github, __but you can't see them__. If you continue debugging this, you may trigger a bot that suspends your account.

**Comment by mmaietta** [comment]
That's part of `electron-forge` package. I don't think it has any relevance to `electron-builder`?
