### ISSUE TITLE
advice / question: Does this superseed electron packer ?

### ISSUE THREAD

**Issue by joeblew99** [electron-userland/electron-builder#658]
Hey !!

Does this superseed electron packer ?

--

Also i need to include and run some scripts as part of the install. this is because i have some usb drivers, etc i need to include.
Can this generally handle stuff like this too ?

thank you

**Comment by develar** [comment]
> Does this superseed electron packer ?

Yes. You don't need to use electron-packager.

> Can this generally handle stuff like this too ?

Please use `extraFiles` (see https://github.com/electron-userland/electron-builder/wiki/Options). See #644 for example. Or `afterPack` (doubt that it will be required).
