### ISSUE TITLE
Rational for semver nupkg/RELEASES modification?

### ISSUE THREAD

**Issue by joeferraro** [electron-userland/electron-builder#659]
* **Version**: 5.4.1

* **Target**: Windows

Hi, I'm curious why this project modifies the prerelease semver when writing the nupkg/RELEASES file. Is this a squirrel requirement?

Example:

My version: myapp-0.0.1-beta.1

**electron-builder nupkg file name**: myapp-0.0.1-beta1-full.nupkg
**electron-builder RELEASES file entry**: 3223432 myapp-0.0.1-beta1-full.nupkg 60956022

This is causing issues with my update server, but I figured there must be a reason why `beta.1` is being changed to `beta1` during the publish process.

Thanks in advance.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/651#issuecomment-238093295

Duplicates #651

**Comment by joeferraro** [comment]
sorry for the dup @develar. cheers
