### ISSUE TITLE
electron-builder not including entire dependency in built version

### ISSUE THREAD

**Issue by Irantwomiles** [electron-userland/electron-builder#6602]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: v17.4.0

* **Electron Version**: 16.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Window and MacOS

I am attempting to package my application using electron-builder, but one of my dependencies is not getting the entire module in the built version. Here is what the dependency looks like in my node_modules folder that is not built: 
![image](https://user-images.githubusercontent.com/11483711/151920241-769bbb3b-c74a-45a1-ab2d-0416ceacd580.png)

And here is what it looks like when I extract the app.asar file:
![image](https://user-images.githubusercontent.com/11483711/151920293-9f861101-bb5c-417f-93ac-c960d47d5bd4.png)

As you can see it is missing the `constructor` folder entirely. I have tried including the specific files in the build path but I simply cannot get this to work. I've tried everything from re-installing my packages, updating node version, importing the index.js file directly, adding every variation of the file path to the build section of package.json. I would great appreciate some help on this. If you'd like even more info I even made a stackoverflow question:

https://stackoverflow.com/questions/70901907/electron-builder-not-including-entire-dependency-in-built-version

**Comment by mmaietta** [comment]
Can you set up a minimum repro repo for this?
I think the issue here is that the folder is named `constructor` and that's causing it to get passed over. That being said, I have no idea why it would do that. The only place in the codebase where we filter for the work "constructor" is for the website docs to apply custom formatting.

**Comment by Irantwomiles** [comment]
> 

That's interesting, I thought about that early on but I thought that would be a silly thing. I'll give that a try and if that doesn't work I'll try and create a minimum repository.

**Comment by Irantwomiles** [comment]
omg, I renamed it to something else and it worked 🤦🏼 
 Please fix this

**Comment by mmaietta** [comment]
Please provide minimum repro repo and I can try and take a look at this edge case

**Comment by Irantwomiles** [comment]
> Please provide minimum repro repo and I can try and take a look at this edge case

I will later today once I get home.

**Comment by Irantwomiles** [comment]
@mmaietta Here is the repo I've been using to test with.

https://github.com/Irantwomiles/please-work

**Comment by mmaietta** [comment]
Seems there's a bug with [`asar`](https://github.com/electron/asar).

I ran electron-builder with `asar: false` and the files correctly showed up.

Tested further, ran `asar pack <node modules dir> ./test-app.asar`, then unpacked the test asar via `asar extract test-app.asar ./test-app`
The `./test-app` dir was missing the `@truffle` `constructor` folder.

**Comment by Irantwomiles** [comment]
> Seems there's a bug with [`asar`](https://github.com/electron/asar).
> 
> I ran electron-builder with `asar: false` and the files correctly showed up.
> 
> Tested further, ran `asar pack <node modules dir> ./test-app.asar`, then unpacked the test asar via `asar extract test-app.asar ./test-app` The `./test-app` dir was missing the `@truffle` `constructor` folder.

Does this mean that I have to have all of my files unpacked?

**Comment by mmaietta** [comment]
Maybe you can use patch-package to rename the folder and imports? Or manually include. You might be able to use `asarUnpack` to include everything else in an asar and then have `@truffle` only unpacked (like how a `.node` file would normally be)
>asarUnpack Array<String> | String | “undefined” - A [glob patterns](https://www.electron.build/file-patterns) relative to the [app directory](https://www.electron.build/configuration/configuration.html#MetadataDirectories-app), which specifies which files to unpack when creating the [asar](http://electron.atom.io/docs/tutorial/application-packaging/) archive.
