### ISSUE TITLE
Is it possible to publish latest.yaml file separately from other files ? (s3)

### ISSUE THREAD

**Issue by SuperKirik** [electron-userland/electron-builder#6604]
* **Electron-Builder Version**: 
^22.11.7

* **Node Version**: 
v14.18.0

* **The target**: 
macOS, Windows

Currently, I have the following settings:
```
        publish: {
          provider: 's3',
          bucket: bucketName,
          path: `/${packageJson.version}`,
          acl: 'public-read',
          region: process.env.AWS_REGION,
        },
```
I set 'path' as the app version to upload each new version to a separate directory (because it is not convenient to have all files for each app version in the same folder).

But the problem is that 'latest.yaml' is always uploaded into the same folder as other files. So each folder has its own 'latest.yaml' file.

And what I need is **one 'latest.yml' at the root** of the bucket which **points to the latest version files located in separate folder** named after the version number.

Is it possible to do with electron-builder ? 
Or maybe there is some alternative solution to keep app versions in separate folders ?

**Comment by mmaietta** [comment]
Sorry, no, I don't think that is possible with the current (intricate) logic flow

**Comment by SuperKirik** [comment]
@mmaietta oh what a pity... So, usually there is only one s3 folder where all files (for all previous and current versions) are located ?

**Comment by mmaietta** [comment]
Technically, you could provide you're own custom publisher for uploading files. It'd require a full implementation, but you could probably copy much logic from (or probs simplify)
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/publish/s3/s3Publisher.ts
Just need to extend this class I think? Haven't used this "custom" approach myself yet, I've only implemented Keygen and Bitbucket publishers directly within electron-builder
https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/electron-publish/src/publisher.ts#L71
