### ISSUE TITLE
request: Set app ASAR name

### ISSUE THREAD

**Issue by Antix-Development** [electron-userland/electron-builder#6609]
For my current project I would like to have two Electron apps in one folder.

This seems to be impossible because both apps want to open the same ASAR file which is `resources\app.asar`.

Would it be possible in future to be able to make the name of the ASAR file able to be specified?

I'm mostly asking because it seems that many files created during the building process are duplicates (chrome_100_percent.pak, etc) and and common to all Eectron apps, and if I am distributing two apps, then it is kind of dumb to have multiple copies of redundant files.

**Comment by mmaietta** [comment]
AFAICT That's not possible as it's hardcoded in electron
https://github.com/electron/electron/blob/d44a187d0b226800fe0cb4f7a0d2b36c871b27cd/lib/browser/init.ts#L190-L191

**Comment by Antix-Development** [comment]
Thanks, it is what it is I suppose.
