### ISSUE TITLE
Uncaught exception: Invalid or unexpected token

### ISSUE THREAD

**Issue by bontibon** [electron-userland/electron-builder#661]
* **Version**: 5.24.0

* **Target**: Windows Squirrel (32-bit)

The following exception is shown when trying to run my built executable on 5.24.0. Downgrading back to 5.16.0 fixed the issue.

![image](https://cloud.githubusercontent.com/assets/110883/17561169/2deeaa92-5efb-11e6-9e4e-18044160130b.png)

**Comment by develar** [comment]
Please try 5.24.1

**Comment by bontibon** [comment]
No more error dialog. Thanks, @develar!
