### ISSUE TITLE
Duplicate download of Electron

### ISSUE THREAD

**Issue by PleasantFuban** [electron-userland/electron-builder#6613]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 14.17.4

* **Electron Version**: 17.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

So my project has both `electron` and `electron-builder` in `devDependency`. As I run `npm install`, A binary of Electron is already downloaded in postinstall of `electron`, to this destination:

`C:\Users\Administrator\AppData\Local\electron\Cache\dbd8fc4d3473df2...b2fe4046a38\electron-v17.0.0-win32-x64.zip`

which is the only file that exists in the folder.

I am expecting this download to also serve my packaging process. However, when I run the command `npm build pack` (which is defined as `electron-builder --dir`) trying to pack my app, I can see that it is trying to download Electron *AGAIN*, but **to a different destination** (more precisely, the folder w/o the long hash string, which is the parent of above, and root of electron cache):

`C:\Users\Administrator\AppData\Local\electron\Cache\electron-v17.0.0-win32-x64.zip`

And these two zips are identical. Console outputs are:

```
> electron-builder --dir

  • electron-builder  version=22.14.5 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=<path-to-my-package-json>
  • author is missed in the package.json  appPackageFile=<path-to-my-package-json>
  • writing effective config  file=build\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=17.0.0 appOutDir=build\win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v17.0.0/electron-v17.0.0-win32-x64.zip size=88 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v17.0.0/electron-v17.0.0-win32-x64.zip duration=8m22.898s
  • default Electron icon is used  reason=application icon is not set
```

I also noticed a similar issue #4885 where a different mirror is used. In my case, both copies are downloaded from GitHub, which can be sometimes slow. And also I don't have a rich disk space, so it's also a waste for me.

How can my electron-builder make use of the existing download of Electron?

**Comment by mmaietta** [comment]
You can specify electron-builder to use a custom location of using `electronDist` string (or closure most likely for your purposes)
https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/app-builder-lib/src/configuration.ts#L143-L146

Note:
> Zip files must follow the pattern `electron-v${version}-${platformName}-${arch}.zip`, otherwise it will be assumed to be an unpacked Electron app directory

**Comment by PleasantFuban** [comment]
> You can specify electron-builder to use a custom location of using `electronDist` string (or closure most likely for your purposes)
> 
> https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/app-builder-lib/src/configuration.ts#L143-L146
> 
> Note:
> 
> > Zip files must follow the pattern `electron-v${version}-${platformName}-${arch}.zip`, otherwise it will be assumed to be an unpacked Electron app directory

Thank you for your suggestion. But it remains unclear to me how the hash string in the paths are generated; they are different from the SHASUM256s of the zip files.
Is it possible to do this with other configurations or package.json? Also I don't think I've ever configured Node or electron-builder so I believe they have both downloaded to the default paths.

**Comment by mmaietta** [comment]
Looks like it might be possible to use an `ELECTRON_CACHE` env var to override the path?
https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/electron/electronDownloader.go#L54-L62
https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/download/artifactDownloader.go#L195

Haven't tested it myself, but looking at the Go code, seems that's where the default download path is being created.

**Comment by PleasantFuban** [comment]
> That's driven by an upstream dependency. Looks like it might be possible to use an `ELECTRON_CACHE` env var to override the path? https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/electron/electronDownloader.go#L54-L62 https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/download/artifactDownloader.go#L195
> 
> Haven't tested it myself, but looking at the Go code, seems that's where the default download path is being created.

I tried setting the `ELECTRON_CACHE` env var to `C:\Users\Administrator\AppData\Local\electron\Cache`, then removed `node_modules`  and Electron cache inside the hash string folder (the one downloaded by electron-builder is still there), finally ran `npm install` to reinstall the packages. But it still attempts to download a new zip file back to that same hash string folder, instead of finding the one in `ELECTRON_CACHE` path.

**Comment by mmaietta** [comment]
Whelp, not something that we can fix via electron-builder. You'll need to open a ticket for `app-builder` project

**Comment by oech3** [comment]
It seems we can block 2nd (without long hash) .zip by symlinking 1st one to there.
