### ISSUE TITLE
npx asar extract | prevent unpacking

### ISSUE THREAD

**Issue by MwSpaceLLC** [electron-userland/electron-builder#6622]
Hi there, 😐

I tried to use (npx asar extract app.asar destfolder) in my compiled app.

I'm not very sure how this works But this allows any person who downloads my program to extract the source files.

![image](https://user-images.githubusercontent.com/29952045/152851015-5014c098-bd9a-439a-b635-e5c1a5c9a51a.png)

I don't know about these technologies but I believe that exposing the source files to everyone is compromising the business of this application.

Sorry if it's not the correct department but I think this is very important, all Electron and React files are then accessible by anyone

**Comment by TC-mSundaram** [comment]
If you are concerned about exposing source files, you would need to ship a binary from a compiled language like Go, C, etc.

**Comment by MwSpaceLLC** [comment]
Thanks @TC-mSundaram, In fact we have chosen to use [webpack](https://webpack.js.org/concepts/#plugins) to reduce the reading clear code of electron file in main process and the [node addon](https://nodejs.org/api/addons.html#hello-world) cpp compiled classes of for main env vars and other private functions.

![image](https://user-images.githubusercontent.com/29952045/152927965-f85236c2-0487-4350-86ac-9c7b7a76bde2.png)

Now the application works the same way, only it is safe even if you are looking for keys, urls and other sensitive data.

However, I leave this case open for a few days for anyone looking for a good solution for interacting with Electronjs and the nodejs part.😋
