### ISSUE TITLE
Building for macOS failing

### ISSUE THREAD

**Issue by vtebano13** [electron-userland/electron-builder#6631]
22.14.13

* **Electron-Builder Version**: 

* **Node Version**: 14.15.4

* **Electron Version**: 4.2.12
* **Electron Type (current, beta, nightly)**:

* **Target**: OSX

Can not seem to build the OSX version.  

 electron-builder --mac

  • electron-builder  version=22.14.13 os=20.6.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=package.json ("build" field)
  ⨯ node_modules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|cies"  : [],
  "repo|..., bigger context ...|g>",
  "contributors"  : [],
  "dependencies"  : [],
  "repository"    : {"type": "git", "url": "git|...
Error reading package.json: /Users/runner/work/1/s/Hydrogen/src/node_modules/dep-graph/node_modules/underscore/package.json  
  ⨯ /Users/runner/work/1/s/Hydrogen/src/node_modules/app-builder-bin/mac/app-builder_amd64 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /Users/runner/work/1/s/Hydrogen/src/node_modules/app-builder-bin/mac/app-builder_amd64 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/runner/work/1/s/Hydrogen/src/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by vtebano13** [comment]
Does anyone have an idea what is going on?

**Comment by vtebano13** [comment]
Anyone know what is going on?

**Comment by bugeats** [comment]
> `Error reading package.json: /Users/runner/work/1/s/Hydrogen/src/node_modules/dep-graph/node_modules/underscore/package.json`

Syntax error in your `package.json`?

**Comment by vtebano13** [comment]
It seems it was being caused by the a newer node.js.  I loaded the same one as on my desktop and electron builder worked as expected.
