### ISSUE TITLE
Native File Drag-and-Drop Doesn't Work After Packaging

### ISSUE THREAD

**Issue by dlackey** [electron-userland/electron-builder#6633]
* **Electron-Builder Version**: ^22.14.13

* **Node Version**: v16.4.2

* **Electron Version**: ^17.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macos, dmg

Native file drag-and-drop works in development (`electron .`), but doesn't work after packaging. Dragging a file outside of the application results in a cancel sign underneath the cursor. I'm unable to drop the file at this point. When I package my application with electron-forge, native file drag-and-drop still works. 

I tried targeting dmg and installing. I've also tried signing the app and giving it "Full Disk Access" under "Security and Privacy".
I'm probably missing some configuration, but opening an issue just in case.

**Comment by cbrwizard** [comment]
@dlackey what was the solution? I'm also having this issue
