### ISSUE TITLE
generic publisher config does not accept any requestHeaders

### ISSUE THREAD

**Issue by D4uS1** [electron-userland/electron-builder#6635]
* **Electron-Builder Version**:  22.14.13

* **Node Version**:  16.14.0

* **Electron Version**:  17.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  MacOS

Hi Guys,

i am trying to use the generic publisher option in electron-builder, but it seems not to accept any request headers.
My publish config in __builder.config.js__:
```
module.exports = {
...
    publish: {
        provider: "generic",
        url: "http://localhost:3000/electron_publish",
        requestHeaders: {
            "access-token": "some-access-token-here"
        }
    }
}
```

If i try to build i just receive an error message:
```
 - configuration.publish should be one of these:
   object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | [object { provider, channel?, host?, owner?, private?, protocol?, publishAutoUpdate?, publisherName?, releaseType?, repo?, requestHeaders?, token?, updaterCacheDirName?, vPrefixedTagName? } | object { bucket, provider, acl?, channel?, encryption?, endpoint?, path?, publishAutoUpdate?, publisherName?, region?, requestHeaders?, storageClass?, updaterCacheDirName? } | object { name, provider, region, acl?, channel?, path?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, url, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName?, useMultipleRangeRequest? } | object { provider, component?, distribution?, owner?, package?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, token?, updaterCacheDirName?, user? } | object { provider, publishAutoUpdate?, publisherName?, requestHeaders?, updateProvider?, updaterCacheDirName?, <key>: {} } | object { account, product, provider, channel?, platform?, publishAutoUpdate?, publisherName?, requestHeaders?, updaterCacheDirName? } | object { provider, channels?, publishAutoUpdate?, publisherName?, repo?, requestHeaders?, updaterCacheDirName? } | object { owner, provider, slug, channel?, publishAutoUpdate?, publisherName?, requestHeaders?, token?, updaterCacheDirName?, username? } | string, ...] | null | string
   Details:
    * configuration.publish.requestHeaders has an unknown property 'access-token'. These properties are valid:
      object {}
```

I guess i am passing the wrong configuration. In this case please tell me how to do it right, because i can not find my mistake related to the [documentation](https://www.electron.build/configuration/publish#genericserveroptions).

Thank you very much

**Comment by mmaietta** [comment]
I'm not sure I follow. Was this working previously for you and only changed when updating electron-builder?
`requestHeaders` are just the standard `http.OutgoingHttpHeaders` object 
https://github.com/electron-userland/electron-builder/blob/c561af810d5de52bec57709cbaebca2ac92c55fc/packages/builder-util-runtime/src/publishOptions.ts#L45-L48
https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules__types_node_http_d_._http_.outgoinghttpheaders.html

**Comment by fauxsoup** [comment]
The problem is in `scheme.json`, where `OutgoingHttpHeaders` has `additionalProperties` set to `false`. Node does not enumerate all available HTTP headers. The typescript definitions just refer to a string-indexed object/dictionary.

See here: https://github.com/electron-userland/electron-builder/blob/e6312cb54e5d957289d5c07b506491fcaea9e334/packages/app-builder-lib/scheme.json#L4247

**Comment by fauxsoup** [comment]
Blame suggests this commit is at fault: https://github.com/electron-userland/electron-builder/commit/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6 (introduced Sep. 20, 2022)

**Comment by mmaietta** [comment]
Hmmm That's for configuration/scheme validation, it doesn't have any application to the rest of the build process. It's autogenerated. From the commit you linked though, I do see
```
-    "@types/node": "^14.10.3",
+    "@types/node": "^14.11.2",
```
Could that be related?

**Comment by sandersdevelopments** [comment]
We have the same problem, where 

 "publish": [
    {
      "provider": "generic",
      "url": "myUrl",
      "requestHeaders": {
        "Authorization": "SharedKey ...."
      }
    }
  ] 
  
  throws an error because it cant find the Authorization Header Key...

**Comment by fauxsoup** [comment]
> Hmmm That's for configuration/scheme validation, it doesn't have any application to the rest of the build process. It's autogenerated. From the commit you linked though, I do see
> ```
> -    "@types/node": "^14.10.3",
> +    "@types/node": "^14.11.2",
> ```
> Could that be related?

I believe so. Validation is asserting an empty object for request headers, I'm just not sure where the validation rule comes from

**Comment by sandersdevelopments** [comment]
@fauxsoup are you able to suggest any workaround for this issue? downgrading electron-builder does not seem to be an option ^^

**Comment by mmaietta** [comment]
I force installed via `pnpm upgrade @types/node@14.10.3` and then reran `pnpm schema` and the `scheme.json` file did not change, so I'm not what changed `additionalProperties: false`. That being said, I found a way to override it since it as I guess the schema generator is not parsing `NodeJS.Dict<number | string | string[]>` properly.
