### ISSUE TITLE
ELECTRON_CUSTOM_DIR="v{{ version }}" is not working

### ISSUE THREAD

**Issue by iamyoki** [electron-userland/electron-builder#6636]
* **Electron-Builder Version**: ^22.14.13

* **Node Version**: v14.18.1

* **Electron Version**: v16.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: -mw

## Problem
Input
```bash
ELECTRON_CUSTOM_DIR="v{{ version }}" npx electron-builder -mw
```

Output
![image](https://user-images.githubusercontent.com/74389358/153794812-f88c4ab3-f7fa-4907-83c8-3b9bfb452f70.png)

> The `"v{{ version }}"` template string not been replaced correctly.

## Related issue https://github.com/electron-userland/electron-builder/issues/6445
This bug has been more than a year, I tried to find the source code problem, but I can't do anything, the code is too deep

**Comment by iamyoki** [comment]
## Share my temp solution
1. Create a file called `./setEnv.js`
```js
const {version} = require('electron/package.json');
const {spawn} = require('child_process');

process.env.ELECTRON_MIRROR = 'https://npmmirror.com/mirrors/electron/';
process.env.ELECTRON_CUSTOM_DIR = `v${version}`;

let [, , command, ...args] = process.argv;

if (command === '--') {
  command = args.shift();
}

spawn(command, args, {stdio: 'inherit'});

```
2.  Run `electron-builder` command like this
```bash
node ./setEnv.js -- yarn electron-builder
```

By doing so, the `setEnv` file will preset the proper env as we needed

**Comment by Gu-Miao** [comment]
Same issue here. Write `ELECTRON_CUSTOM_DIR="v{{ version }}"` in .npmrc doesn't work too.

**Comment by mmaietta** [comment]
It's being used in a upstream library https://github.com/develar/app-builder/blob/c79345743b794ccef41493decafb0b5b2eece505/pkg/electron/electronDownloader.go#L107

AFAICT, it was never made to handle macros, so I don't think this is really a bug... Regardless, the ticket should be opened against https://github.com/develar/app-builder

**Comment by Gu-Miao** [comment]
That's nice! We could add `electronDownload.customDir` to reslove this. I suggest add this to offical document and make the part more clearly, document doesn't show this property but shows a link of `@electron/get` which has a different API scheme. If I didn't know about `app-builder` library or see this issue, I may never make it ok.

**Comment by iamyoki** [comment]
## Again, share another better solution
Create a config file `electron-builder-config.js`
```js
const mirror =
  process.env.ELECTRON_MIRROR ?? 'https://npmmirror.com/mirrors/electron/';
const {version} = require('./package.json');

module.exports = /** @type {import('electron-builder').Configuration} */ ({
  productName: 'ONEUP Desktop',
  appId: 'com.iamyoki.oneup',
  copyright: 'ONEUP Desktop ©2021 Powered by Yoki',
  files: ['assets', 'build'],
  mac: {
    category: 'public.app-category.developer-tools',
    target: [
      {target: 'dmg', arch: ['arm64', 'x64']},
      {target: 'zip', arch: ['arm64', 'x64']},
    ],
    icon: './assets/logo.icns',
  },
  win: {
    target: [{target: 'nsis', arch: 'x64'}],
    icon: './assets/logo.ico',
  },
  electronDownload: {
    mirror,
    customDir: `v${version}`,
  },
});

```

The idea is that electron-builder.json can be written in `.js` file, so it can access env by `process.env` object and we can customize the version format as we wish for, but be careful with the config filename
![image](https://user-images.githubusercontent.com/74389358/154390973-271c3fe6-fd8a-4d01-88b3-700efeec5818.png)
