### ISSUE TITLE
Can't launch the app after adding the com.apple.developer.automatic-assessment-configuration entitlement

### ISSUE THREAD

**Issue by romikps** [electron-userland/electron-builder#6637]
* **Electron-Builder Version**: 22.8.1

* **Node Version**: 12.16.3

* **Electron Version**: 10.1.3

* **Electron-Updater Version**: 4.3.5

* **Target**: mac, dmg

Hi! I need to be able to run my Mac app in Assessment Mode. But even though I use a provisioning profile with the Assessment Mode capability enabled, the moment I add the `com.apple.developer.automatic-assessment-configuration` entitlement to my entitlements.mac.plist file, the app cannot be launched anymore and I get this error:
```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x137622890 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x13761c7d0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}
```
<img width="538" alt="image" src="https://user-images.githubusercontent.com/11509278/153846997-d53835ef-1a69-4eef-8851-f2a9b011cfd7.png">

I was able to reproduce the issue even using the boilerplate from https://github.com/electron-react-boilerplate/electron-react-boilerplate

The steps I done are:
1. added these entitlements to my entitlements.mac.plist file (as described [here](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_automatic-assessment-configuration?language=objc)):
```
<key>com.apple.developer.automatic-assessment-configuration</key>
<true/>
<key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
<array>
	<string>com.apple.assessmentagent</string>
</array>
```

2. enabled the following Additional Capabilities for my app ID in Identifiers at developer.apple.com
- Automatic Assessment Configuration

3. enabled the following Entitlements for my Developer ID Application Provisioning Profile linked to my app ID and Developer ID Application certificate at developer.apple.com
- macOS Automatic Assessment Configuration (Developer ID)

After building the app, I cannot start it and get the errors mentioned above. Removing the `com.apple.developer.automatic-assessment-configuration` entitlement, makes the app launch as normal. I've been trying to solve this for a while now, but nothing has worked so far. Could you please help me figure out what might be the issue here? Thank you!

**Comment by lauw70** [comment]
@romikps hi, did you ever manage to find a solution?
