### ISSUE TITLE
Alpha Versions do not work with electron-builder-notarize

### ISSUE THREAD

**Issue by WrathofthePast** [electron-userland/electron-builder#6638]
* **Electron-Builder Version**: 23.0.0-alpha.3

* **Node Version**: 16.6.1

* **Electron Version**:14.2.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS 12.3 universal

I opened the same issue at karaggeorge/electron-builder-notarize#16 as my understanding is that either project can fix the issue. 
Running `yarn check` returns 1 error:
`error "electron-builder-notarize#electron-builder@>= 20.44.4" doesn't satisfy found match of "electron-builder@23.0.0-alpha.3"`

electron-builder-notarize works with any version of electron-builder ≥20.44.4 including the latest release, but fails to work with the current alpha. Waiting for the full release of v23.0.0 is not feasible due to #6606. Is it possible to incorporate #6617 into a stopgap release or release v23.0.0 soon?

**Comment by mmaietta** [comment]
Personally, I'd recommend using electron-notarize directly to stay more up to date with their development: https://github.com/electron/electron-notarize

v23-alpha has been available for less than a month, I was hoping to wait a little longer before pushing it to for broader usage

**Comment by WrathofthePast** [comment]
> Personally, I'd recommend using electron-notarize directly to stay more up to date with their development: https://github.com/electron/electron-notarize

The purpose of electron-builder-notarize is to seemlessly bridge electron-notarize and electron-builder. It uses electron-builder ≥20.44.4 as a peerDependency and the latest release of electron-notarize as a dependency. As a result, I have no reason to believe that using electron-notarize straight up would solve the error.

> v23-alpha has been available for less than a month, I was hoping to wait a little longer before pushing it to for broader usage

macOS 12.3 Beta 3 came out today. The full release could be out in as little as 2-3 weeks. Do you think you'll feel comfortable with releasing v23 by then? If not, do you have another suggestion to solve the error?

**Comment by mmaietta** [comment]
Opened https://github.com/electron-userland/electron-builder/pull/6653. Will get to it later this week

**Comment by WrathofthePast** [comment]
> Opened #6653. Will get to it later this week

Perfect. Thank you. I tried alpha 4 and confirmed that it didn't change anything, so I'm eagerly awaiting the full release. Thanks again.
