### ISSUE TITLE
Linux - Error: ENOENT: no such file or directory, open '/opt/AppName/resources/app-update.yml' 

### ISSUE THREAD

**Issue by Sakthivelgovindan** [electron-userland/electron-builder#6642]
AppImage auto-update is working fine in electron-updater, but in debian auto-update is not working.

Below the error occured,
Error: ENOENT: no such file or directory, open '/opt/AppName/resources/app-update.yml'

**Comment by mmaietta** [comment]
`deb` never supported auto-update
https://www.electron.build/auto-update
