### ISSUE TITLE
Got corrupted exe file

### ISSUE THREAD

**Issue by Orgil** [electron-userland/electron-builder#665]
* **Version**:  5.24.0

* **Target**: win x64

Starting from the 5.24.0 i got corrupted installer, but works from win-unpacked folder. I got "this application could not be started" error on windows 10 if try to run from win folder. i downgraded to 5.23.2 then everything works as expected.
I'm on mac 10.11 building windows installer.

**Comment by develar** [comment]
Please specify you app product name.

**Comment by develar** [comment]
5.25.1

**Comment by hoffmabc** [comment]
I'm sorry I didn't see what the solution was here.

**Comment by develar** [comment]
@hoffmabc it was temporary regression — icon was set for update.exe.

**Comment by hoffmabc** [comment]
Thank you.
