### ISSUE TITLE
icon.ico in resources dir not used by Squirrel.Windows build

### ISSUE THREAD

**Issue by CoDanny** [electron-userland/electron-builder#666]
5.25.1

Windows

The icon.ico in my 'resources' directory is ignored.

I have to place the ico file in build/icon.ico

My expectation is that if I set a different directory in package.json (using the "directories.buildResources" key it would use that file instead.

**Comment by develar** [comment]
Please ensure that `buildResources` correctly set in the dev package.json file (do you use 2 package.json structure?).

**Comment by CoDanny** [comment]
Yes, it is and for other platforms (e.g. MacOS) it's reading the resources from the right directory:

`  "directories": {
    "app": "build/app",
    "output": "build/dist",
    "buildResources": "resources"
  },`

Yes, it's a 2 package.json structure.

**Comment by develar** [comment]
Could you please try 5.27.0?

**Comment by CoDanny** [comment]
Just did. Here's the installer created:

<img width="570" alt="screen shot 2016-08-16 at 11 32 08 am" src="https://cloud.githubusercontent.com/assets/542760/17692929/26c8bef2-63a5-11e6-8fbd-24c6687815de.png">

I have a file at resources/icon.ico

and the "directories" member of package.json is structured as indicated above

**Comment by CoDanny** [comment]
This is now working fine on 5.30

**Comment by develar** [comment]
Thanks for confirmation.
