### ISSUE TITLE
On Mac I get "This build is using a beta version of Xcode and can't be submitted."

### ISSUE THREAD

**Issue by lukas2** [electron-userland/electron-builder#6665]
* **Electron-Builder Version**:  22.11.10

* **Node Version**: 16.13.2

* **Electron Version**: 13.3.0

* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac App Store

When we upload our build to the app store it goes through, however when creating an external beta test in TestFlight we get the following error message:

```
This build is using a beta version of Xcode and can't be submitted. Make sure you're using the
latest version of Xcode or the latest seed release found on the releases tab in a
href="https://developer.apple.com/news/releases/" target=" blank">News and Updates
```

We build with a release version of Xcode and if I look at the binaries in `node_modules/electron/dist` 

which by the way are

```
./Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/Info.plist
./Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/Info.plist
./Electron.app/Contents/Frameworks/ReactiveObjC.framework/Versions/A/Resources/Info.plist
./Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/Info.plist
./Electron.app/Contents/Frameworks/Mantle.framework/Versions/A/Resources/Info.plist
./Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/Info.plist
./Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/Info.plist
./Electron.app/Contents/Frameworks/Electron Helper.app/Contents/Info.plist
./Electron.app/Contents/Info.plist
```

and check all their `Info.plist` files they tell me:

```
<key>DTXcode</key>
<string>1240</string>
<key>DTXcodeBuild</key>
<string>12D4e</string>
```

And ^ this doesn't seem to be a Non-Release version.

So does anyone know if there's a problem with the distributed Electron files? Or with the builder? Help is appreciated.

**Comment by mmaietta** [comment]
I don't see how this is caused by electron-builder. It simply downloads the electron binaries before packaging the app.asar with it and into the configured distributable.
electron-builder doesn't know what xcode is installed, and I think it's only an upstream dependency, electron-osx-sign, package that utilizes xcode build tools.

You mentioned uploading to the app store goes through, but only the external beta Testflight build is throwing the error. I'm honestly not sure what discrepancy could cause that

**Comment by lukas2** [comment]
Me neither, we are currently puzzled. Thank you for taking your time to answer.

**Comment by stami-fb** [comment]
I am having the same issue, using [electron-forge](https://github.com/electron-userland/electron-forge) as the builder, so this is not electron-builder specific issue. Any insight on how to get the builds to external testing would be appreciated, though! 😁

**Comment by idoodler** [comment]
Dealing with the same issue right now. I am able to submit this Version to the AppStore or to an internal TestFlight group. However I am unable to publish it to an external TestFlight group. I asked Apple Support why this version is not allowed, lets see their response.

**Comment by idoodler** [comment]
The issue is tracked here: https://github.com/electron/electron/issues/33054
