### ISSUE TITLE
Publish GitHub Actions Creating Multiple Drafts

### ISSUE THREAD

**Issue by jliddev** [electron-userland/electron-builder#6676]
* **Electron-Builder Version**:  `"electron-builder": "22.14.13"`

* **Node Version**:  v16.13.1

* **Electron Version**:  17.1.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Any

After updating to the latest electron-builder package the process can no longer find drafts on GitHub but instead creates a multiple drafts for the same version with the following error: `creating GitHub release  reason=release doesn't exist`. This is incorrect since we see multiple release drafts getting created with the same version. 

The build process is run as  a GitHub action and was previously working on electron-builder 22.14.5 without issue.

**Comment by pgherveou** [comment]
running into this as well, it looks like there is an issue with the GH api. The releases endpoint only returns draft, causing electron-builder not to find the latest release

**Comment by jliddev** [comment]
Upon further inspection it does seem something has changed GitHub side as downgrading the electron-builder version does not fix it. I don't know what the change would be though.

**Comment by mmaietta** [comment]
Happy to accept a community contribution! Setting up a local dev env is fairly straightforward too
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by jliddev** [comment]
Seems to have fixed itself GitHub side

**Comment by codeofandrin** [comment]
I got this issue as well

<img width="403" alt="image" src="https://github.com/user-attachments/assets/74d48945-c7d5-4346-8f12-6e0282e787a2" />

**Comment by haneeshraj** [comment]
@codeofandrin I just created a script that creates the tag for me using an auth token, so when the update is being published it just adds it to the tag rather than depending on the `electron-updater` package to create it for me. Try doing that hopefully that is a good workaround for you.

**Comment by codeofandrin** [comment]
@haneeshraj Thanks for your input, would you mind to share it?
