### ISSUE TITLE
app-builder-lib reliance on 7zip-bin breaks builds running on arm64 windows (e.g. parallels on M1)

### ISSUE THREAD

**Issue by UppaJung** [electron-userland/electron-builder#6677]
electron-builder crashes on windows on arm64 (e.g. Parallels on a Mac M1) because there is no arm64 binary for 7za (7zip).
```bash
> cannot execute  cause=exec: "...\\electron\\node_modules\\7zip-bin\\win\\arm64\\7za.exe": file does not exist
```

This occurs because app-builder-lib requires the `7zip-bin` package:
https://github.com/electron-userland/electron-builder/blob/e1a439be9d78c99da5940a68a632f39e922504fb/packages/app-builder-lib/package.json#L50

7zip-bin (at version 5.1.1 at the time of this report, last updated in 2019) contains binaries only for windows only on x32 and x64:
https://github.com/develar/7zip-bin/tree/00b052b49c5cac2cda4bdb06b5b0628095d40a8c/win
(for latest version, see: https://github.com/develar/7zip-bin/tree/master/win)

**Comment by mmaietta** [comment]
I'm not sure how I can help with this as I only maintain electron-builder.
That's an upstream dependency, and 7zip seems to be heavily relied upon by internal electron-builder logic. Please open an Issue upstream for 7zip-bin

**Comment by UppaJung** [comment]
@mmaietta, I've filed an issue with 7zip-bin, but since it doesn't look like that will be fixed any time soon, I'd love to see the documentation updated so that others don't buy new macs hoping they'll be able to run electron-builder on Windows via VM when this is not currently supported on ARM.
