### ISSUE TITLE
What is the programmatic equivalent to --dir flag ? (Building only to unpacked dir w/o creating installer)

### ISSUE THREAD

**Issue by petef19** [electron-userland/electron-builder#6679]
Hi,

we're moving away form using `electron-builder` via CLI and use the JS instance directly.

We only need to build to the unpacked `win-unpacked` dir - do not need to create an installer - hence we used the `--dir` CLI flag before.

What is the equivalent option using the JS config object ? Cannot find it in the docs...

Thanks !

**Comment by mmaietta** [comment]
You can use `target: 'dir'`
