### ISSUE TITLE
Is there an exclusion setting for the file to be signed? 

### ISSUE THREAD

**Issue by KaminoRyo** [electron-userland/electron-builder#6681]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: v16.14.0

* **Electron Version**:17.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: macOS

I'm having trouble signing an app for mac, so I'd like information. 

I'm building the Electron app every few months since April 2020. (For Windows and macOS) 
I am making an app with ```asar: false``` settings due to circumstances,
A web application created by another team (thousands of files of images, JS, CSS, HTML files, etc.) is set in the files property and built. 
I understand that it is deprecated, but if asar: true, there is a problem that the path of the image file of the web application is broken and some images cannot be displayed, so it can not be dealt with.
Last time, I made an app in July 2021. 

However, when I recently upgraded electron-builder, I noticed that it took an unusual amount of time to create a macOS application.
Apparently, it has changed to recursively sign all the files inside.
(Because sometimes a message is output informing you that an error occurred while **signing the image file** when interrupted)

# Question
1. Do I need to sign resource files such as image files to clear the current GateKeeper?
2. Are there any options or settings to exclude only signatures if not needed?

**Comment by KaminoRyo** [comment]
- [Code signing on MacOS should skip text files · Issue #6085 · electron-userland/electron-builder](https://github.com/electron-userland/electron-builder/issues/6085)
- [Code signing is extremely slow · Issue #2169 · electron-userland/electron-builder](https://github.com/electron-userland/electron-builder/issues/2169)

It feels similar to these issues.
By the way, I reverted electron-builder to the July'21 version, but it work to recursively try to sign all the files.
I don't know why the problem didn't occur for about two years. Some apps have more resource files than this app....🤔

**Comment by mmaietta** [comment]
Would `signIgnore` work for you?
https://github.com/electron-userland/electron-builder/blob/81132a857b24bfdb01fc44eba75fc89fa2885545/packages/app-builder-lib/src/options/macOptions.ts
https://www.electron.build/configuration/mac
