### ISSUE TITLE
Setting the requestExecutionLevel option to requireAdministrator on Windows Server OS will cause the application to crash

### ISSUE THREAD

**Issue by Aoiujz** [electron-userland/electron-builder#6685]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 14.17.1

* **Electron Version**:17.1.0
* **Electron Type (current, beta, nightly)**:current

* **Target**:  Windows x64

When `requestedExecutionLevel: requireAdministrator` is set, the application runs fine on Windows Desktop OS (Windows 10, Windows 11), but when running on Windows Server OS (Windows Server 2016, Windows Server 2019, Windows Server 2022), the application crashes.

When `requestedExecutionLevel: highestAvailable` is set, it works fine on both Windows desktop operating systems and Windows server operating systems but does not request administrator privileges when started on a Windows server operating system that is not logged in with an administrator account.

**Comment by mmaietta** [comment]
`highestAvailable` is an enum option. I'm not sure I understand, is this a bug report?
There isn't any special logic going on with the execution level:
https://github.com/electron-userland/electron-builder/blob/8bfeef83a9b1f75761596d33b9504c7dca1cac53/packages/app-builder-lib/src/winPackager.ts#L295-L297

**Comment by Aoiujz** [comment]
@mmaietta I compile without any problem.
My problem is that if I set `requiredExecutionLevel: requireAdministrator`, then the compiled app will not start on Windows Server OS.

**Comment by mmaietta** [comment]
That seems like correct behavior from what I'm reading:
https://serverfault.com/questions/847252/what-is-windows-server-2016-administrator-username
>Instead, you'll need to log in using a domain user with the appropriate authorization; that local Administrator user should have been converted to a domain user if this was the first domain controller in the domain.

For servers, the `highestAvailable` resolves to the correct user. On servers, I'm reading that the default local Administrator account is disabled as well and then eventually replaced by Active Directory.

**Comment by Aoiujz** [comment]
My computer is not joined to Active Directory and I am logged in as the Administrator user. But Electron applications that set `requiredExecutionLevel: requireAdministrator` cannot run.
The systems I tested are (Windows Server 2016, Windows Server 2019, Windows Server 2022, Windows Server vNext )

**Comment by Aoiujz** [comment]
Does this seem to be an Electron bug? I found that Electron 13 and below don't have this problem. Electron 14 and above have this problem.

**Comment by mmaietta** [comment]
Since nothing changed in electron-builder, and this issue doesn't affect solely newer versions of Windows Server, it doesn't seem like a compatibility issue or something in app-builder-bin upstream dependency.
I have to assume something changed in Electron between 13 and 14.

**Comment by Aoiujz** [comment]
I'm sure it's not electron-builder's problem. Because I have the same problem with `mt.exe` setting `requiredExecutionLevel: requireAdministrator`.    
Then I'll close the issue first.

**Comment by HyunhoCho** [comment]
i have same issue. for window os.   one of my Client pc can not run. requireAdministrator mode.  but. sral pc could run in admin mode
there are solution to solve it???
