### ISSUE TITLE
Universal build process leaves native modules "unclean"

### ISSUE THREAD

**Issue by has-n** [electron-userland/electron-builder#6688]
* **Electron-Builder Version**: 22.14.10

* **Node Version**: 14.17.2

* **Electron Version**: 16.0.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: universal (macos)

I'm making universal builds on an Intel mac. When the universal build process runs, it rebuilds all native modules to x64 then arm64 next. This leaves them in an unusable state for a local development run.

I'm considering using the afterAllArtifactBuild hook to clean the node_modules directory and rebuilding everything. Is that the recommended way or should I look at something better?

**Comment by mmaietta** [comment]
Why are you expecting for electron-builder to clean your node modules after a build? Regardless, seems like you could just rerun `electron-builder node-gyp-rebuild` or `install-app-deps` after your `electron-builder _____` dist command.
