### ISSUE TITLE
(electron-update). The 4.6.5 version of the code in the NPM repository differs from the 4.6.5 source in the Github repository!

### ISSUE THREAD

**Issue by zshuaia** [electron-userland/electron-builder#6689]
I'm extending the `electron-update`.

**Comment by zshuaia** [comment]
I'm extending the `electron-update`.
We are going to implement a custom provider.According to github 4.6.5 tag source,the custom provider is passed in using the `SetFeedURL` function.

After restoring the code on NPM from the map file, it is different from the source file, such as this one  
`electron-builder-electron-updater-4.6.5\packages\electron-updater\src\providerFactory.ts`

**Comment by mmaietta** [comment]
Idk how to resolve this. We use `tsc` to compile and then automatically, as part of the CI Github Actions, publish the entire bundle (js + map + typings) to npm. There's nothing special in our pipeline

**Comment by zshuaia** [comment]
Sorry, it's an unexpected question.
