### ISSUE TITLE
Build package for Ubuntu successfully but cannot run the app

### ISSUE THREAD

**Issue by tibuchivn** [electron-userland/electron-builder#671]
* **Version**: 1.3.3

* **Target**: --platform=linux --arch=x64 (ia32)

I can successfully build the app with electron-builder. It generates folder socialdrip-linux-x64 and socialdrip-linux-ia32. After that I run the app by following command

`cd socialdrip-linux-x64
sh socialdrip`

And I have following errors, for x64
`socialdrip: 1: socialdrip: ELF: not found
socialdrip: 2: socialdrip: Syntax error: Unterminated quoted string
`

for ia32
`socialdrip: 1: socialdrip: ELFP�4@: not found
socialdrip: 3: socialdrip: Syntax error: "(" unexpected (expecting ")")
`

I also packaging for MacOS and Windows, and both of them works correctly on those platforms. So I only have issue with Linux.

Any help is appreciated.
Thanks

**Comment by develar** [comment]
`sh` — why do you use `sh`? It is not self executable installer, it is linux executable file. Execute file directly.
