### ISSUE TITLE
NSIS_CONFIG_LOG not defined

### ISSUE THREAD

**Issue by hgouveia** [electron-userland/electron-builder#6715]
* **Electron-Builder Version**:  22.14.13
* **Node Version**:  14.19.0
* **Electron Version**: 16.1.0
* **Electron Type (current, beta, nightly)**: current
* **Target**:  Windows

I recently upgrade from `electron-builder 22.9.1`  to latest `22.14.13` and now i get this error when making the installer with **nsis**

```
Error output:
Error: LogSet specified, NSIS_CONFIG_LOG not defined.
Error in macro LogSetMacro on macroline 2
Error in script "<stdin>" on line 123 -- aborting creation process
  failedTask=build stackTrace=Error: C:\Users\{user}\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
```

i use a custom `install.nsh` where i have at the beginning 
```
!define ENABLE_LOGGING
```

if i remove it, the installer is built, but i need to enable it, i also tried by spcifing debug in the config
```
nsis: {
   debugLogging: true
}
``` 

but same error

**Comment by mmaietta** [comment]
That's being set from here:
https://github.com/electron-userland/electron-builder/blob/12fee6be2b2a6ab9b69b194dab86b048423bae07/packages/app-builder-lib/templates/nsis/common.nsh#L103-L108

Any chance you can use a different variable name instead of `ENABLE_LOGGING`?

**Comment by hgouveia** [comment]
> 

well i intentionally added `ENABLE_LOGGING` to enable logging in **nisis** i could remove it if there is another way to activate logging? 

because for example i removed `ENABLE_LOGGING` , and added `nsis: { debugLogging: true }` ,but i get the same error

**Comment by mmaietta** [comment]
Hmmm, looks like `debugLogging` feature was removed in 22.14.8 by virtue of downgrading `nsis` binaries, this was required due to https://github.com/electron-userland/electron-builder/issues/6334 (Trojan (potentially false) positive detected)

**Comment by hgouveia** [comment]
@mmaietta  due that I can't use `ENABLE_LOGGING` and `debugLogging`,  is there any other way to enable the logs?

**Comment by mmaietta** [comment]
I think I just need to remove the feature entirely since the integrated makensis no longer supports it. I'll try and work on it this weekend

**Comment by mqliutie** [comment]
electron-builder version 23.0.3 
I have modify `common.nsh` and comment 
```
# !ifdef ENABLE_LOGGING_ELECTRON_BUILDER
# !endif
```
The error will be shown 
**LogSet specified , NSIS_CONFIG_LOG not defined **
