### ISSUE TITLE
Cannot uninstall program after having permanently deleted Uninstall executable

### ISSUE THREAD

**Issue by JAM-WizRanch** [electron-userland/electron-builder#6719]
* **Electron-Builder Version**: 
* The version that is built into Gdevelop 5.0.128.

* **Node Version**: 
* The version that is built into Gdevelop 5.0.128.

* **Electron Version**:
* The version that is built into Gdevelop 5.0.128.
* **Electron Type (current, beta, nightly)**:
* The type that is built into Gdevelop 5.0.128.

* **Target**: 
* It's to turn html games into executable apps on Windows.

Hello.
I have installed a program using Electron builder through the Gdevelop game engine app.
Normally you uninstall the program by executing the Uninstall.exe file that is created.
However I wasn't aware and permanently deleted that executable.
Now I'm unable to uninstall the program without the Uninstall executable.

When I try to re-install the same program with the electron builder-installer, the installation freezes mid-point and does not complete,
no matter how long I wait.
I use Windows 11.

How can I remove the old program from my computer without the unistall.exe file?

**Comment by mmaietta** [comment]
Potential workaround: Install your app on a Windows VM and then copy-paste the Uninstall executable from that VM on to your Windows 11 PC.

**Comment by JAM-WizRanch** [comment]
Thank you very much, that worked.
