### ISSUE TITLE
can't generate delta

### ISSUE THREAD

**Issue by Orgil** [electron-userland/electron-builder#673]
* **Version**: 5.28

* **Target**: win

when remoteRelease set it correctly parse releases but can't generate delta nupkg. i've got "ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory" error.

**Comment by develar** [comment]
Does it work before (<=5.25.0?

**Comment by Orgil** [comment]
same error on 5.24.1

**Comment by Orgil** [comment]
Also i've noticed that pkg url messed up on generated RELEASES. i'm using .mn domain but it changed to .com and "download" added to url. is it somehow hardcoded?

**Comment by Orgil** [comment]
nvm. it is on electron-release-server bug i guess.

**Comment by develar** [comment]
So, it is not a regression. I guess your previous release is corrupted, please check.

**Comment by Orgil** [comment]
i found out that electron-release-server uses hardcoded path for previous pkg download url. So i changed storage path to match with it then it works. Thanks for your support.
