### ISSUE TITLE
mac builder electron@11.0.0 404

### ISSUE THREAD

**Issue by w1922616586** [electron-userland/electron-builder#6736]
* **Electron-Builder Version**: 22.5.1

* **Node Version**: 16.13.2

* **Electron Version**: 11.0.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: mac builder 404. electron@11.0.0

![image](https://user-images.githubusercontent.com/24916392/159460208-0bd55bf7-267d-4edd-a500-6ee34cece03c.png)

Excuse me, this document. Where else can I find it. thank you. Or what can I do to change it to the correct address. thank you.

**Comment by mmaietta** [comment]
That is an upstream dependency that you'll need a file ticket for.
https://github.com/develar/app-builder
