### ISSUE TITLE
Win folder empty after install

### ISSUE THREAD

**Issue by LinraGames** [electron-userland/electron-builder#6738]
Hello,

**Electron-Builder Version:** 23.0.3
**Node Version:** v16.14.0
**Electron Version:** 17.1.2
**Electron Type (current, beta, nightly):** current
**Target:** Window and MacOS

I try build new App Svelte and Electron with tutorial :
https://dev.to/khangnd/build-a-desktop-app-with-electron-and-svelte-44dp

I develop and build on MacBook M1 Pro, when i install app on Windows the shortcut is break, when i explore folder install is empty .. juste 1 file "Uninstall MyProgramm.exe" .. 

Did I miss something ?

EDIT-1 : I have try with "electron-quick-start 17.1.2" and "electron-builder 22.14.13" only, same problem..
EDIT-2 : It's Working build on Windows 10..

package.json
```
{
  "name": "svelte-app",
  "version": "0.1.4",
  "private": true,
  "main": "index.js",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "electron .",
    "dist": "npm run build && electron-builder build --mac --win"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "electron": "^17.1.2",
    "electron-builder": "^23.0.3",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.0.0"
  },
  "dependencies": {
    "sirv-cli": "^2.0.0"
  },
  "build": {
    "appId": "com.programme",
    "productName": "Programme",
    "copyright": "Copyright © 2022 Programme",
    "win": {
      "icon": "build/icon.png",
      "publisherName": "Linra Games",
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true
    }
  }
}
```

**Comment by paulpascal** [comment]
I have the same issue on Mac M1, please any update about this?

**Comment by hieunc229** [comment]
I also have this issue!

**Comment by Linrasis** [comment]
I have same issue too 😩

**Comment by leena-prabhat** [comment]
I was facing the same error. Then I built the application on a windows machine and it worked. Still don't know the reason why it wasn't working when building from an M1.

**Comment by stuartaccent** [comment]
Had the same issue then realised i was building an arm64 based windows version on the m1 by not specifying the arch.

`
"win": {
    "icon": "...",
    "target": {
      "target": "NSIS",
      "arch": [
        "x64"
      ]
    }
  }
`

**Comment by LinraGames** [comment]
Thanks, I'll try that tonight or tomorrow.

**Comment by leena-prabhat** [comment]
> Had the same issue then realised i was building an arm64 based windows version on the m1 by not specifying the arch.
> 
> Below fixed it for me.
> 
> ```
> "win": {
>     "icon": "...",
>     "target": {
>       "target": "NSIS",
>       "arch": [
>         "x64"
>       ]
>     }
>   }
> ```

Thanks that worked as well

**Comment by LinraGames** [comment]
It's Works, thank's.
