### ISSUE TITLE
Getting AppVeyor to Generate an Installer (Build Artifacts)

### ISSUE THREAD

**Issue by vicatcu** [electron-userland/electron-builder#674]
* **Version**: v.1.3.3

* **Target**:  Windows x64

I'm just getting my feet wet with electron and electron-builder, and am experimenting with using appveyor build server to build Windows executables. Stumbling through and reacting to the build errors, I've gotten as far as a successful build, but I'm not managing to get artifacts (I presume an exe file) to get published. I've read the Wiki and followed its instructions as closely as I can, reviewing it multiple times, but I can't figure out what I'm doing wrong.

Here is the AppVeyor I'm experimenting with, it's just the electron getting started app: https://ci.appveyor.com/project/vicatcu/electron-sandbox. I have a Draft release on Git-Hub with "Release title": "v1.0.0" and "Tag version": "v1.0.0", but I get no evidence of an executable being generated in the logs. Where am I going wrong?

**Comment by develar** [comment]
I don't see `CI detected, so artifacts will be published if draft release exists` in your log. Hmm... that's really strange.

**Comment by develar** [comment]
Is `GH_TOKEN` env defined?

**Comment by vicatcu** [comment]
@develar forgive my naivety, but how / where do I define that; now that you mention it, I noticed it in the Wiki, but I didn't see how to configure it.

**Comment by develar** [comment]
> Custom environment variables can be set on the Environment tab of project settings

**Comment by vicatcu** [comment]
@develar ah, so it's not in the appveyor.yml somewhere, but rather in the project settings of the AppVeyor web interface?

**Comment by develar** [comment]
Please see https://www.appveyor.com/docs/build-configuration#environment-variables

I strongly suggest to use web interface instead of `appveyor.yml` to simplify management.

**Comment by vicatcu** [comment]
@develar yes, I'm using an appveyor.yml file. So I take it I need a section something like:
environment:
  GH_TOKEN: token_created_from_within_github

Is that about right?

**Comment by vicatcu** [comment]
I get this output tail on AppVeyor.

```
CI detected, so artifacts will be published if draft release exists
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 x64 using electron 1.3.3 to dist\win-unpacked
Warning: Application icon is not set, default Electron icon will be used
Building Squirrel.Windows installer
Creating Github Publisher — user: vicatcu, project: Electron-Sandbox, version: 1.0.0
Updating build cache
Cache entry not found: C:\projects\electron-sandbox\app\node_modules
Saving "C:\Users\appveyor\AppData\Roaming\npm-cache"...OK
Build success
```

As a documentation  note, I don't see anything on the AppVeyor web interface under Artifacts, but if I go to my GitHub repository Draft Release, I see three attachments: 
```
electron-sandbox-1.0.0-full.nupkg
electron-sandbox-Setup-1.0.0.exe
RELEASES
```

I suspect the EXE is the Windows Installer, what are the other two? Also, for anyone following along, I checked all three boxes under repo for the permissions on my GitHub token. Not sure if you can get away with less.
