### ISSUE TITLE
Cannot compute app package download URL

### ISSUE THREAD

**Issue by ohad32** [electron-userland/electron-builder#6742]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 17.7.2

* **Electron Version**: 17.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis-web

Hey,
I'm trying to build my app and I get:
⨯ Cannot compute app package download URL  failedTask=build stackTrace=Error: Cannot compute app package download URL

my package.json file:
{
  "name": "Updater",
  "version": "1.0.0",
  "description": "Boi",
  "main": "index.js",
  "scripts": {
    "start": "node .",
    "electron": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "build": {
    "appId": "LoL",
    "win": {
      "target": "nsis-web"
    },
    "nsisWeb": {
      "createDesktopShortcut": true,
      "runAfterFinish": true,
      "deleteAppDataOnUninstall": true,
      "allowToChangeInstallationDirectory": true,
      "oneClick": false
    }
  },
  "author": "ohadXD",
  "license": "ISC",
  "devDependencies": {
    "electron": "^17.2.0",
    "electron-builder": "^22.14.13"
  }
}

**Comment by ramstheroyalp** [comment]
Hi,
Are you able to fix the issue?
I'm facing the same issue. 
The build worked fine when the repo is in GitHub and recently we moved the repo to azure DevOps and started getting the build error in the azure repo.
Appreciate, if you can share the solution if you were able to fix the issue.

Regards,
Rama Rao.
