### ISSUE TITLE
nsis.deleteAppDataOnUninstall property not work if package.json's name property has scope

### ISSUE THREAD

**Issue by lowfront** [electron-userland/electron-builder#6747]
* **Electron-Builder Version**: 22.14.5, 22.14.13

* **Node Version**:  16.13.2

* **Electron Version**: 16.0.7, 17.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS
* **OS**: Windows 10

Hi. I noticed that the `AppData/Roaming/` data folder is not deleted when `nsis.deleteAppDataOnUninstall` is `true`. When I tested it, I found that the folder was not deleted if the package.json's name has scope. Regardless of whether have a scope, I think the property `nsis.deleteAppDataOnUninstall` should work.
This is a repository [link](https://github.com/lowfront/electron-builder-remove-test) that can reproduce the problem.

**Comment by lowfront** [comment]
I found the cause of the problem. This [line](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L225) specifies the directory to be deleted as `$APPDATA\${APP_PACKAGE_NAME}` but for package name with scope, `APP_PACKAGE_NAME` is like `@lowfront/electron-builder-remove-test`.
At this time, the entire path is `$APPDATA\@lowfront/electron-builder-remove-test`, and the path contains a slash(/) and is incompatible with the Windows OS path.

So I modified this [line](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L192) as follows and it worked.
```ts
APP_PACKAGE_NAME: appInfo.name.replace(/\//g, '\\'), // delete path to $APPDATA\@lowfront\electron-builder-remove-test
```
I think can fix the `nsisTarget.ts` file, or `uninstaller.nsh` file to fix the problem. Regardless of which method choose, NSIS is an installation program for Windows, so there will probably be no problem with other OS builds.
I wonder which method looks better.

**Comment by mmaietta** [comment]
Closing per #6772
