### ISSUE TITLE
Problem with linked npm packages and asar

### ISSUE THREAD

**Issue by anri-asaturov** [electron-userland/electron-builder#675]
* **Version**:  5.26.0

* **Target**: mac

One of my node modules is linked via `npm link` and I get an error during build:
```
> build --dir

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.3.3 to dist/mac

Error: /Users/anri/myapp/node_modules/myapp-lib: file links out of the package
    at Filesystem.insertLink (/Users/anri/myapp/node_modules/asar-electron-builder/lib/filesystem.js:82:15)
    at /Users/anri/myapp/node_modules/electron-builder/src/asarUtil.ts:316:28
    at next (native)...
```

Without linking it works fine.

**Comment by virror** [comment]
Would also love to see a fix for this : )

**Comment by cwillisf** [comment]
I don't think this is ASAR-specific -- it's just that the error is more noisy when ASAR is enabled. It looks like the symlink just isn't getting dereferenced / followed.

Packaging succeeds when ASAR is disabled, but that's because it just includes the addon's symlink in the app bundle as-is. In my case the symlink is relative, so the resulting bundle can't load the linked addon when it's installed in Applications as usual.

**Comment by anri-asaturov** [comment]
@cwillisf check this out (link to source inside): https://github.com/electron/asar/issues/85

**Comment by develar** [comment]
Working on fix.

**Comment by develar** [comment]
BTW, you should never build production builds using npm linked modules.

**Comment by virror** [comment]
I know, but its convenient for developing sometimes : )

**Comment by anri-asaturov** [comment]
@develar Well, if you bundle everything and keep everything in 'devDependencies' then it's fine.

**Comment by develar** [comment]
@anri-asaturov No. Linked module copied AS IS — all node module development files, all node module dependencies including development — not pruned and not optimised (duplicated) will be included to production app.

**Comment by anri-asaturov** [comment]
@develar i understand, but i don't have any 'dependencies' in my package.json and therefore no 'node-modules' in built app. Everything is bundled with webpack to 2 files 'electron.js' and 'renderer.js'

**Comment by develar** [comment]
@anri-asaturov So, your issue is completely different. Please attach sample project. If "i don't have any 'dependencies' in my package.json and therefore no 'node-modules' in built app" then electron-builder must not try to pack your linked module at all.

**Comment by anri-asaturov** [comment]
@develar yes, you are right, I wasn't bundling electron process code when I stumbled into this problem, then I started bundling it too to avoid this issue.

**Comment by develar** [comment]
next version: Set `build.dereference` to `true` and disable asar as workaround. Moved to backlog — a lot of more important issues should be solved. PR is welcome.

**Comment by anri-asaturov** [comment]
Any hints on how to potentially fix the 'copy as is' issue with linked packages? I could try to fix it.

**Comment by develar** [comment]
@anri-asaturov Please clarify — is your statement `i don't have any 'dependencies' in my package.json and therefore no 'node-modules' in built app` still true or not.

**Comment by anri-asaturov** [comment]
Currently, for the project I initially opened this issue for it's true, it's my workaround. 
But I'd like to switch back to linked module because now i have to push/publish my dependency every time I change it.

**Comment by develar** [comment]
Not clear for me — why  you need to have packed app often. Why you cannot use electron-prebuilt?

In any case — there is a workaround — `build.dereference` added for you. Disable asar:
 ```
"asar": false,
"dereference": true`
```

add this to your `build`. Next version will be published soon. Is it suitable for you?

> Any hints on how to potentially fix the 'copy as is' issue with linked packages?

This issue in any case should be fixed before, right?

**Comment by develar** [comment]
Linked module is supported in the upcoming electron-builder 11.2.0.

**Comment by anaszgh** [comment]
I'm still facing the same problem with electron-builder 19.24.1

**Comment by develar** [comment]
19.39.0
