### ISSUE TITLE
Docs: `globalPaths` no longer work in Electron v17+

### ISSUE THREAD

**Issue by KishanBagaria** [electron-userland/electron-builder#6752]
[Loading App Dependencies Manually](https://www.electron.build/tutorials/loading-app-dependencies-manually) recommends using:

```js
if (devMode) {
  // load the app dependencies
  const PATH_APP_NODE_MODULES = path.join(__dirname, '..', '..', 'app', 'node_modules')
  require('module').globalPaths.push(PATH_APP_NODE_MODULES)
}
```

`require('module').globalPaths.push` no longer has any effect after https://github.com/electron/electron/pull/31275 – released in Electron v17+. The docs should be updated with an alternative or a warning for v17+.

Reported to Electron: https://github.com/electron/electron/issues/33504

**Comment by mmaietta** [comment]
Would you be willing to submit a PR for updating the docs? It'd be greatly appreciated!
