### ISSUE TITLE
app-update.yml

### ISSUE THREAD

**Issue by ohad32** [electron-userland/electron-builder#6759]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 17.7.2

* **Electron Version**: 18.0.1
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater**: 4.6.5

* **Target**: Squirrel.Windows

Squirrel.Windows do not generate app-update.yml
What can I do?

**Comment by edson-k** [comment]
the bug still persists for a long time for Linux, will there ever be a solution?

**Comment by mmaietta** [comment]
Squirrel.Windows never has supported auto-updates.
