### ISSUE TITLE
NPM package is not correctly tagged? (`next` should be `lastest`?)

### ISSUE THREAD

**Issue by danielweck** [electron-userland/electron-builder#6764]
https://www.npmjs.com/package/electron-builder

* `latest` is [22.14.13](https://www.npmjs.com/package/electron-builder/v/22.14.13)
* `next` is [23.0.3](https://www.npmjs.com/package/electron-builder/v/23.0.3)

My MacOS DMG build was breaking because of the erroneous Python path (`usr/bin/python`), which prompted me to look at NPM published versions, only to realise that version 23 which contains the fix is not "advertised" properly as `latest` by NPM update tools.

**Comment by danielweck** [comment]
Quick search for `/usr/bin/python`:
https://github.com/electron-userland/electron-builder/issues?q=is%3Aissue++%2Fusr%2Fbin%2Fpython+

**Comment by mmaietta** [comment]
I'm not sure I understand, it's set correctly.
`next` represents "bleeding edge"
`latest` is generally what I run with in terms of "minimum supported version"

I generally wait a month or two before updating `latest` tag from `next`
`next` seems to be stable enough at this point to move it to `latest` tag though.

**Comment by mmaietta** [comment]
`latest` is now 23.0.3

**Comment by danielweck** [comment]
FYI, dev tools like npm-check-updates consider the 'latest' NPM publish tag by default (production-grade, tested releases), not 'next' which is normally used for unstable bleeding edge builds (typically with semantic versioning 1.2.3-beta.4 (for example)

**Comment by danielweck** [comment]
Back to the future :)

https://github.com/electron-userland/electron-builder/issues/9789
