### ISSUE TITLE
Is any other reason for checking oneClick options for deciding isAdminRightsRequired for update-info.json?

### ISSUE THREAD

**Issue by HwangTaehyun** [electron-userland/electron-builder#6786]
* **Electron-Builder Version**: 
  * 23.0.3

* **Node Version**: 
  * 16.3.1

* **Electron Version**:
  * 14.2.4
* **Electron Type (current, beta, nightly)**:
   * current

* **Target**: 
  * window 10

  * Is any other reason for checking oneClick options for deciding isAdminRightsRequired for update-info.json? When I update electron app on window service, it required isAdminRigthsRequired. However, my electron app needs some mui page, so i setup custom nsis installer script and set oneClick to false. In this case, because of the below logic, my electron installer cannot get isAdminRightsRequired.
Thank you for the amazing library!
  * https://github.com/electron-userland/electron-builder/blob/fca50aea42fc054b87bbe943bbe5c1c235a186e1/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#:~:text=if%20(updateInfo%20!%3D%20null,%7D

**Comment by mmaietta** [comment]
@develar would you be willing to provide context here? I don't know the history

**Comment by HwangTaehyun** [comment]
Resolved by #6787
