### ISSUE TITLE
Option to clear persisted JSON storage files

### ISSUE THREAD

**Issue by Mercieral** [electron-userland/electron-builder#679]
* **Version**: latest

* **Target**: All

As I was researching how to persist data in an Electron application, I came across two options: use the localStorage object which is only accessible in render process or use an Electron JSON storage module which is accessible by both main and render process and stores each data key in a JSON file in the app.getPath("userData") folder. I decided to go with the latter as I needed that data in the main process before the window is opened. For example, [Electron-Storage](https://www.npmjs.com/package/electron-storage) and (the one I am using) [Electron-json-storage](https://www.npmjs.com/package/electron-json-storage)

It appears that the data saved by these modules is being persisted through the build as well, which is causing users to have non-default behavior when they first open the app.

Is there any way to clear (or add an option to clear) this data on build in Electron-builder? Currently I have to add some code to clear all data, run the app, remove the code, and build, which is a pain.

Thanks

**Comment by develar** [comment]
> It appears that the data saved by these modules is being persisted through the build as well, which is causing users to have non-default behavior when they first open the app.

Users of your app are not affected. `build` in the build time, not in runtime. I don't understand you, sorry.

NSIS installer doesn't delete local app data on reinstall, but remove on uninstall.

**Comment by Mercieral** [comment]
@develar 

Sorry for the confusion. I will give my use case to maybe clear this up.

I have some settings a user should be able to set when they first open the  newly-installed app. These settings are persisted using [Electron-json-storage](https://www.npmjs.com/package/electron-json-storage) so I can access them in my main process. My main process checks if these settings have been set and determines whether to load the initial settings page or the homepage. 

The issue I am having is that these settings are set on my development mac machine because I am testing my application. When I am done, I build my installers using Electron-builder, transfer the Setup.exe installer to my windows machine, and open the app, but I get redirected to the homepage with the settings configured as they were on my development machine (as if the persisted data is being put into the installer).

> build in the build time, not in runtime.

I am not building in runtime. This data is persisted as files so they still exist even when out of runtime.

> NSIS installer doesn't delete local app data on reinstall, but remove on uninstall.

I am still using Squirrel for both Windows and Mac currently, not NSIS.

**Comment by Mercieral** [comment]
Silly me, I see the issue now. I was not realizing that these files were being persisted in a separate directory than the application itself (in Windows at least, they are saved in `.../AppData/Roaming/myApp`). 

My assumption was that uninstalling the app would delete this storage as well, which does not seem to be the case. I see now that it does work initially and properly loads the page I want when I delete the AppData after uninstalling and reinstalling.

Maybe a dumb question, but is there a way to have the squirrel or NSIS uninstaller clear this data on uninstall? This may not be related to Electron-builder at all...

**Comment by bontibon** [comment]
> Is there a way to have the squirrel uninstaller remove the local app data

@Mercieral Perform the removal in your `--squirrel-uninstall` handler.
