### ISSUE TITLE
Error when compilling Linux app

### ISSUE THREAD

**Issue by freedomstalker64** [electron-userland/electron-builder#6798]
electron-builder --linux tar.xz snap

  • electron-builder  version=22.5.1 os=10.0.22000
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=18.0.4 appOutDir=dist\linux-unpacked
  • building        target=tar.xz arch=x64 file=dist\ponytown-1.0.0.tar.xz
  • scheduling remote build  target=snap arch=x64
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1
h5lt2t": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1
h5lt2t": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1
h5lt2t": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1h5lt2t": dial tcp 51.15.
76.176:443: connectex: No connection could be made because the target machine actively refused it.

How to fix it?

**Comment by mmaietta** [comment]
That project is dead https://github.com/electron-userland/electron-build-service
