### ISSUE TITLE
'install-app-deps' intermittently misses required dependencies

### ISSUE THREAD

**Issue by whaleprophet** [electron-userland/electron-builder#6805]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: v16.14.2

* **Electron Version**:  17.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: x64 win32

Trying to use `active-win` library. Dependencies include `ffi-napi`. While building for production builds, the `install-app-deps` would intermittently not find all the dependent libraries:

```
> electron-builder install-app-deps

  • electron-builder  version=22.14.13
  • rebuilding native dependencies  dependencies=ref-napi@3.0.3 platform=win32 arch=x64
  ```
  Versus:
  
```
> electron-builder install-app-deps

  • electron-builder  version=22.14.13
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, iconv@2.3.5, ref-napi@3.0.3 platform=win32 arch=x64
  ```
  
  
Build environment is exactly the same, and `active-win` is put into the unpackAsar option. Yet when we try to use `active-win` (therefore ffi-napi), the package would look for `ffi-napi` in the asar instead of asar.unpacked structure.

**Comment by mmaietta** [comment]
Native dependencies are handled by app-builder-bin, which are binaries from the upstream package https://github.com/develar/app-builder/issues. Can you please open an issue there?
