### ISSUE TITLE
update-downloaded not triggered on windows

### ISSUE THREAD

**Issue by timebuzzerfelix** [electron-userland/electron-builder#6808]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 15.0.2

* **Electron Version**:12.0.0
* **Electron Type (current, beta, nightly)**:current

* **Electron-Updater Version**: 5.0.1

* **Target**:  NSIS

The download of the new version of the exe-file into the "pending" folder works, but after the download has finished, the 
autoUpdater.on('update-downloaded'..) is not triggered. The file still has the prefix "temp-", I'm not sure if the prefix should be removed after the download has finished?

On macOS and Linux everything works fine.

**Comment by mmaietta** [comment]
Just to help triage this more, was this previously working for you? If so, what version?

**Comment by timebuzzerfelix** [comment]
Yes it was working on 
Electron-Builder Version: ^22.11.7
Node Version: ^15.0.2
Electron Version: 12.0.0
Electron-Updater Version: ^4.3.5

I had the same issue there, so tried the updates. Right now I'm trying to fix it in the older version.

I think we need a log from the moment after the update package is downloaded, how can I get this?

**Comment by mmaietta** [comment]
Can you try this? Doesn't seem to require app 'ready' event
```
autoUpdater.logger = require("electron-log")
autoUpdater.logger.transports.file.level = "info"
```
https://www.electron.build/auto-update#debugging

**Comment by timebuzzerfelix** [comment]
Hi, solved it, was something totally different with the signing process.. thanks for your help!
