### ISSUE TITLE
Guard in GithubProvider custom channel breaks case of no prerelease versions

### ISSUE THREAD

**Issue by blakebyrnes** [electron-userland/electron-builder#6809]
Whoops, seems there was an error in some code I suggested:
```
packages/electron-updater/src/providers/GitHubProvider.ts:76:63 - error TS2345: Argument of type 'string | number | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.

76           const isCustomChannel = !['alpha', 'beta'].includes(hrefChannel)
```
Since we don't care about number/null when comparing against alpha/beta, let's just wrap `hrefChannel` to be `String(hrefChannel)`

_Originally posted by @mmaietta in https://github.com/electron-userland/electron-builder/issues/6505#issuecomment-1018041463_

**Comment by blakebyrnes** [comment]
This ticket has a strange format. Sorry for that. I was trying to reference where this originated. There's an issue if you use the `allowPrerelease` feature of the GithubProvider that causes it to fail to find any github releases if the current version is not a prerelease.

https://github.com/electron-userland/electron-builder/blob/8b43098338d9f911eaf60ecab3fa0a26fd500722/packages/electron-updater/src/providers/GitHubProvider.ts#L60

The string wrap added above causes the `|| null` to never occur, however, the same string wrap was not added to the comparison a few lines below.

https://github.com/electron-userland/electron-builder/blob/8b43098338d9f911eaf60ecab3fa0a26fd500722/packages/electron-updater/src/providers/GitHubProvider.ts#L71

Solution seems to be to just wrap the second option (null !== "undefined")

**Comment by mmaietta** [comment]
Can you please open a PR with the fix? 🙂
