### ISSUE TITLE
NSIS build fails when oneClick is set to false (unknown variable/constant "HasPerUserInstallation")

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#681]
* **Version**: lasest on npm

* **Target**: Windows (NSIS)

I'm trying to build a NSIS installer in a `electronuserland/electron-builder:wine`-based Docker container with the following options:
```
"oneClick": false,
"perMachine": true,
"allowElevation": true,
"runAfterFinish": false
```

However, the build process fails with the following message:
```
warning: unknown variable/constant "HasPerUserInstallation" detected, ignoring (macro:_==:1)
```

If I only change my option `oneClick` to `true`, it builds correctly.

**Comment by develar** [comment]
Please try pre-release version `5.29.0`
