### ISSUE TITLE
Beforepack and Afterpack hooks don't work for Mac Universal builds

### ISSUE THREAD

**Issue by has-n** [electron-userland/electron-builder#6815]
* **Electron-Builder Version**: 22.14.10

* **Node Version**: 14.17.3

* **Electron Version**: 16.0.5
* **Electron Type (current, beta, nightly)**:

* **Target**: MacOS Universal

beforePack and afterPack hooks do not fire for MacOS Universal builds. They fire for the individual x64 and arm64 architectures but not when combining them into the universal build.

**Comment by gaodeng** [comment]
Universal build is generated by merging the x64 and arm64 versions together using @electron/universal package. There is no doPack process, so of course there are no beforePack and afterPack hooks

**Comment by mmaietta** [comment]
Yeahh, I'm with @gaodeng on this one, I think it needs to be left as-is. IIRC `beforePack` and `afterPack` correspond to arch-specific pack events
