### ISSUE TITLE
GitHub release names are now undefined

### ISSUE THREAD

**Issue by adelphes** [electron-userland/electron-builder#6819]
* **Electron-Builder Version**: 23.0.3

I think [this commit](https://github.com/electron-userland/electron-builder/commit/6a116b027504d1b3d44f78ba3df20f68d01dcb32) (related to [this issue](https://github.com/electron-userland/electron-builder/issues/3683)) has broken integrations that make use of release names.

On the GitHub website, an undefined release name gets displayed as the tag name - but the "real" name associated with the release is still `undefined`.
Common integrations that use the release name now look like this (Slack GitHub App for example):

<img width="331" alt="Screenshot 2022-04-26 at 15 38 36" src="https://user-images.githubusercontent.com/13035517/165326293-687da488-79ae-4414-9c3a-322dc7fe3260.png">

Prior to the change, they used to look like this:
<img width="292" alt="Screenshot 2022-04-26 at 15 40 40" src="https://user-images.githubusercontent.com/13035517/165326377-d3b0271a-368c-403b-8da7-d3746cfd1be7.png">

Can you revert the change or provide a way for setting the release name?

**Comment by mmaietta** [comment]
Oh interesting! Happy to have it reverted, makes more sense that we'd want integrations to properly render release names. Would you mind opening a PR with the needed change?
