### ISSUE TITLE
XDG_DATA_DIRS is missing when starting AppImage on Fedora 24

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#682]
* **Version**: 5.23.2

* **Target**: Linux AppImage

The script used as AppRun in electron-builder fails on systems that have no `$XDG_DATA_DIRS` environment variable set, e.g., Fedora 24.

In AppImageKit, [AppRun.c normally sets $XDG_DATA_DIRS](https://github.com/probonopd/AppImageKit/blob/7ab97bbe89e680b4b7ed7936d7899ac39df6d776/AppRun.c#L44) so that this is not an issue there, but since AppRun.c from AppImageKit is not used in electron-builder, this needs to be taken care of in the script that electron-builder uses as its AppRun. The best behavior would probably be to set $XDG_DATA_DIRS to `$APPDIR/usr/share:$HOME/.local/share:/usr/local/share/:/usr/share`, or remove the line that checks for XDG_DATA_DIRS being set.

See
https://github.com/toolkit-for-ynab/unofficial-desktop-for-ynab/issues/1
https://github.com/zeit/hyperterm/issues/551
https://github.com/probonopd/AppImageKit/issues/208

**Comment by develar** [comment]
Thanks!
