### ISSUE TITLE
Can I set executable name & product name separately?

### ISSUE THREAD

**Issue by jhh-ncurity** [electron-userland/electron-builder#6823]
I'm using `vue-cli-plugin-electron-builder@2.1.1` but my question also applies to plain `electron-builder`.

I want my executable to have **non-white-space & lower-case** name and my product name (which is shown in shortcuts, installers, control pannel etc.) to have spaces and case-sensitive names.

But it seems like I can only customise installer names by setting `artifactName` property.

And all other file names are created using `productName` which can contain white-spaces and mixed-cases.

Is there way to customize this?

**Comment by KaminoRyo** [comment]
Is ['executableName' property](https://www.electron.build/configuration/configuration) useless?

**Comment by jhh-ncurity** [comment]
oh, my bad. I missed it. Thanks a lot. I'll close this issue.
