### ISSUE TITLE
OS X: Error: Module version mismatch. Expected 48, got 49

### ISSUE THREAD

**Issue by meltedspark** [electron-userland/electron-builder#683]
* **^5.30.0**: 

* **1.3.3**: 

When trying to build for OS X getting the following error:
`tsc && node-gyp rebuild && build --mac`

> Error: Module version mismatch. Expected 48, got 49.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:583:18)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/macos-alias/lib/create.js:7:13)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/macos-alias/index.js:1:18)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/ds-store/index.js:2:13)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
> From previous event:
>     at tsAwaiter (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/electron-builder/src/util/awaiter.ts:10:47)
>     at Object.build (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/electron-builder/src/builder.ts:195:52)
>     at Object.<anonymous> (/Users/Jenia/Desktop/git/electron-angular2-native/node_modules/electron-builder/src/build-cli.ts:27:28)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.runMain (module.js:590:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3

To reproduce:
* Pull this repository: https://github.com/meltedspark/electron-angular2-native
* Run `npm install`
* Run `npm run dist:osx`

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-builder/issues/453#issuecomment-222734707

**Comment by meltedspark** [comment]
Tried removing node_modules + `npm cache clean` + `npm install`. Won't help. Running node 6.4.0.

**Comment by develar** [comment]
Please do not node-gyp rebuild — it is not correct — electron headers must be used. If you have native deps, use 2 package.json structure and electron-builder will compile it for you automatically.

**Comment by develar** [comment]
I see that you author of this boilerplate project, may be https://github.com/szwacz/electron-boilerplate will be useful for you.

**Comment by meltedspark** [comment]
I am using 2 package.json structure, and I have to do `node-gyp rebuild` as
I have native modules as a part of the project (not just external
dependency).
But this is not the issue, I'm pretty convinced so. I do use electron
headers (see `.npmrc` in the root of tje project), and it also works with
no problems on Windows and Linux. The problem only appears on OS X.

**Comment by meltedspark** [comment]
Also, I am able to run it on OS X (`npm start`), what fails is only the build.

**Comment by develar** [comment]
Ok, I will investigate.

**Comment by develar** [comment]
Related https://github.com/electron-userland/electron-builder/issues/683

**Comment by develar** [comment]
You should not use `node-gyp rebuild` before `build`. Even `must not`. electron-builder does it for you. And now even more correctly — #647

**Comment by develar** [comment]
Reproduced. `node_modules/macos-alias` — it means that `node-gyp rebuild` not only rebuld your project sources, but deps also. But must not — electron-builder will rebuild dependencies for you.

**Comment by meltedspark** [comment]
I'm not sure this is correct. I use the following in my root `binding.gyp` for specifying which dependencies to compile:
```
'dependencies': [ 
				'<!@(find ./app/* -name binding.gyp -not -path \"./**/node_modules/*\" | sed -e s/$/:*/)'
			]
```
As you can see it skips all the `node_modules` folders. Since `node-gyp rebuild` looks for the `binding.gyp` in the directory it was called from, I can't see how `node-gyp rebuild` invocation would build the `macos-alias`.

**Comment by develar** [comment]
Sorry, it cannot be fixed.  On macOS electron-builder uses some native deps. When you have file `.npmrc` in your project, it means that `npm install` will compile native modules according to this configuration. But then you execute `build` and node trying to use such native modules, but cannot, because it is compiled for electron, not for node.

**Comment by develar** [comment]
I will investigate is it possible to remove such native deps (`macos-alias` as dep of `appdmg`).

**Comment by develar** [comment]
I think, as solution, electron-builder can provide some script to perform `node-gyp rebuild` task.

**Comment by meltedspark** [comment]
Ok, let me see if I got it right. 
The problem is that I'm specifying headers by exporting variables (and not by [passing](http://electron.atom.io/docs/tutorial/using-native-node-modules/) it to `node-gyp rebuild`, for example).
Since I export the variables it applies to all the native modules, including some electron-builder dependecies (`macos-alias`). Then node tries to use electron-builder and fails because some of its dependencies were built with another (electrons) headers.
Is that correct?
If so, the simplest solution (on my side) will be passing the arguments to `node-gyp rebuild` from the command line, instead of `.npmrc` file. 
How electron-builder providing a script to perform `node-gyp rebuild` will help?

**Comment by develar** [comment]
> How electron-builder providing a script to perform node-gyp rebuild will help?

Option `nodeGypRebuild` will be added in 10 minutes. You just set it to true and electron-builder will call it for you with proper env/conf.

**Comment by develar** [comment]
Set `"nodeGypRebuild": true` in your `build` and remove `.npmrc` file.

**Comment by meltedspark** [comment]
Well, it indeed solves the problem, kudos for the solution.
It does introduce a new problem though. When I had `.npmrc` file, the `node-gyp rebuild` (which occurred on `npm install` or by demand) was compiling my own native addons with electron headers. 
So I was able to run and debug the application without packaging it. Now I cannot do this, because the native addons compile with node headers. 
The only way to run the application is running a `build` step first. 
I can run `node-gyp rebuild` explicitly while specifying electron headers and target, but in this case this whole solution becomes redundant.
Thoughts?

**Comment by develar** [comment]
`node-gyp-rebuild` bin will be added.

**Comment by meltedspark** [comment]
Great. Btw, perhaps you should add to the documentation clarification about `.npmrc` affecting the build.

**Comment by develar** [comment]
@meltedspark PR to improve doc welcome :) Or donation ;)

**Comment by zaggino** [comment]
@develar same error here, repo https://github.com/zaggino/brackets-electron and build here https://travis-ci.org/zaggino/brackets-electron ... linux is passing, osx is not with `Module version mismatch. Expected 48, got 49.` There're no node-gyp references in the project or `npmrc` file. Can you advise?

**Comment by songlineboy** [comment]
How are you running the process?

If it might help anyone, we had a similar issues running node via pm2, we were getting this error: **Error: Module version mismatch. Expected 48, got 57**

It seems the number refers to NODE MODULE version, 48 is node 6, 57 is node 8.

We were running our pm2 processes and each process specifies a particular node version to use. They were point to node 6 versions, even thought our current nvm use version was at 8.12. (node.js version 8.12.0 )

Deleting and restarting the PM2 jobs, created the tasks with the updated link to node 8.12 and we stopped getting that error.

Hope it helps someone!
