### ISSUE TITLE
I can't found the MetadataDirectories of type on electron.build website

### ISSUE THREAD

**Issue by seanock** [electron-userland/electron-builder#6836]
I looked at document on electron.build
the configuration directories is MetadataDirectories of type.
The MetadataDirectories type details could not be found.
I'm sorry, My english is so bad. 
Thank you for your patient answer.

**Comment by seanock** [comment]
i found it in source code.
the code at packages/app-builder-lib/src/configuration.ts
```
export interface MetadataDirectories {
  /**
   * The path to build resources.
   *
   * Please note — build resources are not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly: `"files": ["**\/*", "build/icon.*"]`
   * @default build
   */
  readonly buildResources?: string | null

  /**
   * The output directory. [File macros](/file-patterns#file-macros) are supported.
   * @default dist
   */
  readonly output?: string | null

  /**
   * The application directory (containing the application package.json), defaults to `app`, `www` or working directory.
   */
  readonly app?: string | null
}
```

**Comment by zanzara** [comment]
Not fixed yet :-(

**Comment by azchohfi** [comment]
@seanock would you mind re-opening this? It has not been fixed.

**Comment by zanzara** [comment]
This is also dead: [https://www.electron.build/generated/nsisoptions#custom-nsis-script](https://www.electron.build/generated/nsisoptions#custom-nsis-script)

**Comment by jo-cor** [comment]
Sadly, still an issue
