### ISSUE TITLE
No dependencies built in packaged app

### ISSUE THREAD

**Issue by Meadowcottage** [electron-userland/electron-builder#684]
* **Version**: `5:30.0`
* **Target**:  `All platforms`
* **[REPOSITORY](https://github.com/Meadowcottage/devRant)**
* **Issue**: App runs in development as expected. Building either `dist` or `pack`, both package the app as normal with no errors or warnings. But when the packaged app is executed, following error is shown: http://i.imgur.com/AnFHdap.png  
I've tested it without this exact module, [electron-config](https://www.npmjs.com/package/electron-config), and the remaining dependencies bring up the same error. EG: [electron-is-dev](https://www.npmjs.com/package/electron-is-dev) | [electron-dl](https://www.npmjs.com/package/electron-dl).  
Unsure if it's an error with my code or if something wrong with the builder.

**Comment by GDur** [comment]
I have the same problem. 
Target and platform: Windows

Please advise :)

**Comment by develar** [comment]
Is this dependency listed in your `package.json`?

**Comment by GDur** [comment]
Yes. However I just realized that I didn't install Docker

>  5. Install required system packages.

Might this be the source of my error?

**Comment by develar** [comment]
`Docker` is not required. I will check your project after working day.

**Comment by develar** [comment]
@GDur You must add app dependencies to app package.json, not to dev.

```
"dependencies": {
    "electron-config": "^0.2.1",
    "electron-is-dev": "^0.1.2"
  },
```

must be in the `app/package.json`.

**Comment by GDur** [comment]
It's working now :)
Thank you very much for the fast Answer!
