### ISSUE TITLE
Downloading old releases for delta on windows

### ISSUE THREAD

**Issue by solgarius** [electron-userland/electron-builder#685]
* **Version**: 5.22.1

* **Target**: Windows

I have a question about the downloads of old releases for creating delta files on windows builds. As far as I can tell whenever I do a build, electron-builder downloads all of the previous releases to create the latest delta and as each .nupkg release is ~65mb in our system, that means every release the amount that needs to be downloaded is getting much larger. 

For example to calculate the deltas: 
build release 1.0.0, to calculate delta doesn't download anything
build release 1.0.1, downloads 1.0.0 ~65mb (total 65mb)
build release 1.0.2, downloads 1.0.1 ~65mb + 1.0.1.delta ~1mb or so, + 1.0.0 ~65mb (total 131mb)
build release 1.0.3, downloads: 1.0.2, 1.0.2.delta, 1.0.1, 1.0.1.delta, 1.0.0 (total ~197mb)
etc etc

Even after 4 releases the build is starting to take quite a while as it tries to download many files that appear unnecessary.

Is there a point where it stops downloading every version, and why does it need to download more than just the most recent release? i.e. when doing 1.0.3 why does it need 1.0.1 and 1.0.0?

My setup is downloading from a github private repository, same repository that it pushes the release to when completed. 

Also note, our repository is used to _only_ store releases and does not contain any code etc in the repository itself. We do this due to security restrictions on the github token and access to the raw source code. I'm not sure if this might be an issue.

I'm not sure if I am perhaps setting up the build incorrectly?
Below is my code for running a build.

```
var builder  = require('electron-builder');
var Platform = builder.Platform;
var repository = 'https://github.com/ID/REPO';
builder
    .build({
        targets:     Platform.WINDOWS.createTarget(),
        publish:     'always',
        draft:       false,
        prerelease:  false,
        devMetadata: {
            repository:  repository,
            build:       {
                appId:       'com.squirrel.clientName.exeName',
                productName: 'App',
                compression: 'normal',
                files:       ['**'],
                win:         {
                    loadingGif:     'loader.gif',
                    iconUrl:        'https://example.com/loader.gif',
                    icon:           'app.ico',
                    remoteReleases: repository,
                    remoteToken:    process.env.GH_TOKEN
                }
            },
            directories: {
                output: './bld/release/client',
                app:    './bin/client'
            }
        }
    })
    .then(function () { console.log('Success!'); })
    .catch(function (error) { console.error('Failed',error); });
```

**Comment by develar** [comment]
> that means every release the amount that needs to be downloaded is getting much larger.

No. AFAIK, Squirrel.Windows downloads only previous version.  

Could you please repost this issue to https://github.com/electron/windows-installer/issues or Squirrel.Windows issue tracker?

Your config looks correct.
