### ISSUE TITLE
Generate installer only

### ISSUE THREAD

**Issue by Unforgiven-wanda** [electron-userland/electron-builder#686]
Hello,
I've already gone through the process of packaging my app with electron-packager. Would it be possible at this point to generate only the installer(s) out of my packaged app? The documentation isn't clear on this point, as revisiting my packaging process would be extremely time-consuming now.

Thank you.

**Comment by develar** [comment]
No, unfortunately, it is not supported.

> as revisiting my packaging process would be extremely time-consuming now

`electron-builder` is much more easy than `electron-packager`. Migration should be straightforward.
