### ISSUE TITLE
dmg-license not accessible

### ISSUE THREAD

**Issue by roddc** [electron-userland/electron-builder#6866]
* **Electron-Builder Version**: 
23.0.3

* **Electron Version**: 18.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows, Linux

I got an error `npm ERR! dmg-license not accessible from dmg-builder
` when I run `npm ci --cache .npm --prefer-offline` with `electronuserland/builder:wine` image
I have no idea what caused the problem

**Comment by roddc** [comment]
> @roddc, did you find a solution?

I forgot how I exactly fix it, I think the problem is `lockfileVersion`, you could try downgrading Node and npm(maybe v6?) versions of your project to match the `electronuserland/builder:wine`'s, and generate a new package-lock.json

**Comment by roddc** [comment]
> @roddc, did you find a solution?

I forgot how I exactly fix it, but I think the problem is package-lock.json, you could try downgrading Node and npm versions of your project, I am using Node v16.14.2 and npm v6.14.16, and generate a new package-lock.json

**Comment by vassbo** [comment]
I suddenly got this error, and I fixed it by updating the `node-version` in my GitHub Actions workflow file. 😊
Then I also had to install dmg-license as found here: https://github.com/electron-userland/electron-builder/issues/6489
