### ISSUE TITLE
macOS: Support protocol/protocolName

### ISSUE THREAD

**Issue by creshal** [electron-userland/electron-builder#687]
* **Version**: 5.30.0

* **Target**: Mac

As per [electron doc](http://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-macos-windows), `CFBundleURLSchemes` and `CFBundleURLName` need to be set for protocol handlers to properly work in macOS. This is [already supported by electron-packager](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#protocol), it only needs to be passed to it by electron-builder.

**Comment by develar** [comment]
Duplicates #575 Fixed :)
