### ISSUE TITLE
Build Linux version on Travis CI failed

### ISSUE THREAD

**Issue by KochiyaOcean** [electron-userland/electron-builder#688]
* **Version**:  5.32.1

* **Target**:  Linux x64

Travis CI throw an error `gm convert: Unable to open file (/tmp/electron-builder-26ohKk/3-electron-builder-linux/icon_256x256x32.png) [No such file or directory]` and stopped the build process.

Detailed log is in https://api.travis-ci.org/jobs/154199522/log.txt?deansi=true

**Comment by develar** [comment]
Please ensure that you `icns` file contains 256x256 icon. Please see https://github.com/electron-userland/electron-builder/issues/239

**Comment by KochiyaOcean** [comment]
I'm sure the file contains a 256x256-32 icon. The `icns` file is in https://github.com/poooi/poi/blob/master/build/icon.icns

**Comment by develar** [comment]
I suppose `icnsutils` is broken. You can try https://github.com/electron-userland/electron-builder/issues/239#issuecomment-215676565

Or as workaround, 

> (or you can put them into the build/icons directory — filename must contains size (e.g. 32x32.png

as here https://github.com/develar/onshape-desktop-shell/tree/master/build/icons

Duplicates #239

**Comment by KochiyaOcean** [comment]
Okay, I will have a try.
