### ISSUE TITLE
I have an app named A.app in /Application directroy  Now I want to change it to B.app  I have set productName to B  The app can run perfectly  But in /Application the app name is still A.  Is there a way to change it?

### ISSUE THREAD

**Issue by thirteen13Floor** [electron-userland/electron-builder#6881]
I have an app named A.app in /Application directroy

Now I want to change it to B.app

I have set productName to B

The app can run perfectly

But in /Application the app name is still A.

Is there a way to change it?

**Comment by burgil** [comment]
Hey, Will be easier to see your repo, can you share it? otherwise please share your `electron-builder.yml`, Maybe we can spot the issue together
