### ISSUE TITLE
child process is not working in electron app

### ISSUE THREAD

**Issue by s-beladiya7** [electron-userland/electron-builder#6883]
* **Electron-Builder Version**: 22.11.9

* **Node Version**: 14.17.1

* **Electron Version**:13.1.7

I'm creating a child process using "fork" in the "electron" app. I'm creating child process as below:
```
   const child_process_file = path.join(__dirname, 'getSubFolders.js')
   const sub = fork(child_process_file, [JSON.stringify(subFolderObj), JSON.stringify(arg)])
```

when I run this program in debug mode, the child process is working fine, but when I generate an exe file and run the exe file, child process is not working as it should be. It is targetting main.ts(main file) instead of a file('getSubFolders.js' here) passed in params while creating child process.

path generated for child_process_file is => C:\Users\Saurabh\AppData\Local\Programs\a-sync-qa\resources\app.asar\two-way-sync\getSubFolders.js

can anyone suggest what am i doing wrong in this?

**Comment by burgil** [comment]
Hey there, let's try to fix it shall we?

1. Add the following line:
```js
console.log('path generated for child_process_file is:', child_process_file);
```
Under the line:
```
const child_process_file = path.join(__dirname, 'getSubFolders.js')
```

2. Run the app in debug and attach the log:

3. Build the exe, open CMD, navigate where the exe is and type `call test.exe` while test is the file name, if it has spaces using "", you can also use the TAB key to auto complete

4. Attach the full log below, including the actual error (which you seem to forgot to attach) from the child_process

5. Can you repeat the process with `asar: false` and attach the full log?

6. Do you put your build configuration on `electron-builder.yml` or your `package.json`? can you attach those?

7. Did you tried to enable `includeYarnSubNodeModules: true`?

8. Did you try to set `npmRebuild: false`?

9. are you using NPM or yarn?

10. Did you tried to update electron-builder to the latest v23+?

**Comment by s-beladiya7** [comment]
I got a solution and it is working for me in debug mode as well as exe mode.
```
const env = { ...process.env, PATH: `${process.env.PATH}:/usr/local/bin` };
const child_process_file = path.join(__dirname, 'getSubFolders.js')
const sub = fork(child_process_file, [JSON.stringify(subFolderObj), JSON.stringify(arg)], {
                  env,
                  stdio: ['ipc', out, err]
})
```

**Comment by sakshammalge** [comment]
Hey there! Could you tell what the issue was? I am having similar isssue wiht my app.

backend;
  backend = path.join(process.cwd(), "build/dist/app.exe")
  console.log('path generated for child_process_file is:', backend);
  console.log(backend)
  var execfile = require('child_process').execFile;
  execfile(
  backend,
  {
    windowsHide: true,
  },
  (err, stdout, stderr) => {
    if (err) {
    console.log(err);
    }
    if (stdout) {
    console.log(stdout);
    }
    if (stderr) {
    console.log(stderr);
    }
  }
  )
  
  This is how I am starting my child process.
