### ISSUE TITLE
Please enable wayland for snaps

### ISSUE THREAD

**Issue by aripollak** [electron-userland/electron-builder#6888]
Currently, the snap builder is setting `DISABLE_WAYLAND: 1`, but I don't think that's necessary anymore. Electron apps run fine under Wayland since they default to Xwayland, but there are some commandline arguments available to run it under native Wayland: `--enable-features=WaylandWindowDecorations --ozone-platform=wayland`. The Chromium snap has also [recently re-enabled wayland support](https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/commit/?id=a4f41b5c065e14e954bc81d2d3e2b0c7fc26fc4d). Keeping `DISABLE_WAYLAND: 1` means that even the commandline options to force native Wayland don't work.

**Comment by burgil** [comment]
Hey, Maybe you could submit a pull request about it, Here are the relevant files:
![image](https://user-images.githubusercontent.com/41600149/172072247-d4923d3d-e222-45bb-84be-83d6b9b29c68.png)

Also there are many more references to just wayland in the code:
![image](https://user-images.githubusercontent.com/41600149/172072269-6d5e7736-5328-4f42-ae12-3a902ce84653.png)
![image](https://user-images.githubusercontent.com/41600149/172072273-d23d3773-9e8b-4b7d-96c1-f52dd179fcf3.png)

Good luck 👍
