### ISSUE TITLE
issue with "contains executable code"

### ISSUE THREAD

**Issue by virror** [electron-userland/electron-builder#689]
* **Version**: 5.30.0

* **Target**: win32

Im trying to use asar to get a dll and a node file as a dependency to my project, but im getting the error: "node_modules\nodeaep is not packed into asar archive - contains executable code"
This worked fine before in 4.x.

Part of the package.json:
  "devDependencies": {
    "electron-builder": "^5.30.0",
    "electron": "^1.3.3"
  },
  "build": {
    "asar.unpack": "**/app/{VROOT/**, node_modules/**/*.+(lua|node|dll)}",
  },

**Comment by develar** [comment]
> error: "node_modules\nodeaep is not packed into asar archive - contains executable code"

It is not an error. electron-builder automatically compute correct `asar.unpack` — you don't need to specify it explicitly.

> asar.unpack

If you still want to explicitly set `unpack`, use `asar` as object – 

```json
"asar": {
  "unpack": "your value"
}
```

But as far I see electron-builder correctly detects DLLs and unpack it.

**Comment by develar** [comment]
What error do you mean? " is not packed into asar archive - contains executable code" is not an error and not even a warning — it is just info.

**Comment by virror** [comment]
True its just info, im sorry i was a bit unclear here. I get this following error message after and i thought it was because of the asar.unpack thing: 
"Error: ENOENT: no such file or directory, open 'D:\Source\aep-sdk\electron\dist\win-ia32-unpacked\resources\app.asar.unpacked\node_modules\nodeaep\aep.dll'" 
Since thats one of the files that triggers the info.

**Comment by develar** [comment]
is it possible to share project?

**Comment by virror** [comment]
Thats not really possible since its a commercial project. I can share whatever information you need though.
Have to ask the boss about sharing actual files : )

**Comment by develar** [comment]
> Have to ask the boss about sharing actual files : )

I think it will be possible to create simple project using only `nodeaep` dep. But I don't see `nodeaep` in the npm. Source code is not required for me.

**Comment by develar** [comment]
If you cannot wait, you can temporary disable asar: `"asar": false`. I will wait sample project from you to reproduce.

**Comment by virror** [comment]
Here are a small sample project: https://dl.dropboxusercontent.com/u/1688685/electron.rar
just run: "npm run pack:win" in the electron folder.
I hope thats helps : )

**Comment by develar** [comment]
@virror Thanks for sample project, fixed.

**Comment by virror** [comment]
Np, happy to help : )
