### ISSUE TITLE
Wine is not running on AWS Lambda container. Segmentation fault

### ISSUE THREAD

**Issue by paulyves** [electron-userland/electron-builder#6890]
I have this docker file that displays the wine version:
```
FROM electronuserland/builder:wine

ENTRYPOINT [ "wine", "--version" ]
```
When running this on my local docker, it returns the version of wine.

```
>> docker build -t wine-version .
>> docker run wine-version
>> wine-7.0
```
but when I uploaded it to AWS ECR and use it as my lambda function container, it printed `exited with error: signal: segmentation fault`
Arch: x86_64

Expectation:  wine version should be printed on the logs.
```
START RequestId: bc7b454b-22c9-4373-aaa3-091c8c4fa17c Version: $LATEST
END RequestId: bc7b454b-22c9-4373-aaa3-091c8c4fa17c
REPORT RequestId: bc7b454b-22c9-4373-aaa3-091c8c4fa17c	Duration: 4.32 ms	Billed Duration: 5 ms	Memory Size: 128 MB	Max Memory Used: 3 MB	
RequestId: bc7b454b-22c9-4373-aaa3-091c8c4fa17c Error: Runtime exited with error: signal: segmentation fault
Runtime.ExitError
```

**Comment by mmaietta** [comment]
I'm not sure I understand. wine version should be frozen to 6
https://github.com/electron-userland/electron-builder/blob/2ece89a08e7fb74a11ba3d0f5980b2a57c8b34ad/docker/wine/Dockerfile#L8-L13

**Comment by mmaietta** [comment]
Not sure why the `:wine` tag didn't update, but please try using `electronuserland/builder:14-wine` or `electronuserland/builder:16-wine`
```
docker run --rm electronuserland/builder:14-wine /bin/bash -c "wine --version"
wine-6.0.4
```

**Comment by michaeldoron59** [comment]
wine still doesn't run on aws lambda, and I get the same error, any thoughts?

**Comment by mmaietta** [comment]
What docker image are you using?

Docker images were updated recently to the latest `buildpack-deps` (22.04 IIRC), and as part of that, the `wine` version was bumped up significantly as well.
