### ISSUE TITLE
Built for arm64 on x64 doesn't mount

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [electron-userland/electron-builder#6897]
* **Electron-Builder Version**: 23.0.3
* **Node Version**: 16.4.2
* **Electron Version**: 19.0.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: darwin + arm64

The dmg file built for arm64 (with `--arm64` option) does not open on `M1` chip laptops. Possible reason is here [packages/dmg-builder/src/dmg.ts#L202](https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmg.ts#L202) since to enable `APFS`, it checks if current process is running on `arm64`, not the option we passed. Then on laptops with `M1`, `hdiutil` cannot mount `HFS` filesystems.

**Comment by burgil** [comment]
Hey, Have you tried to build it on the `M1` chip laptops?

**Comment by vaibhavpandeyvpz** [comment]
Yes, it does. It's just builds for `arm64` done on `x64` do not work on `arm64`.

**Comment by vaibhavpandeyvpz** [comment]
I'll try explaining again. If built on M1 laptop, it works fine on M1 laptop. if built on Intel laptop with `--arm64` option, it does not work on M1 laptop.

**Comment by vaibhavpandeyvpz** [comment]
Alright. Looks like arm64 OS X builds are impossible on major cloud CI platforms currently.

**Comment by burgil** [comment]
@vaibhavpandeyvpz why do you need the enterprise version isn't the essential enough?
![image](https://user-images.githubusercontent.com/41600149/172198711-89a9a834-a4c1-4b8c-8614-e73431a83f1d.png)

**Comment by burgil** [comment]
I am not affiliated with them, I also simply consider using them

**Comment by vaibhavpandeyvpz** [comment]
I'll maybe just create an internal fork on this package and patch. Only concerned about one more stuff to maintain.
