### ISSUE TITLE
Dockerfile: Upgrade to Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by relativisticelectron** [electron-userland/electron-builder#6898]
* **Electron-Builder Version**:  electronuserland/builder:wine
 

[Specter Desktop](https://github.com/cryptoadvance/specter-desktop/blob/2f0f743ccd17128993289eba57abcb34b05b62ff/docker/electron-builder/Dockerfile#L1)  is using electronuserland/builder:wine to build the app.  [Now we are upgrading](https://github.com/cryptoadvance/specter-desktop/pull/1688) to Ubuntu 22.04 Jammy and python 3.10, but electronuserland/builder:wine is only available based on ubuntu focal https://github.com/electron-userland/electron-builder/blob/587db8f73e10b087cec2bb3535c70f0bc9667952/docker/base/Dockerfile?msclkid=03d4d3eacfa911ecb025aa2752367fbc#L1

When do you plan to upgrade to Ubuntu 22.04 Jammy and python 3.10 ?

**Comment by mmaietta** [comment]
Seems like it's relatively straightforward for upgrading the base dockerfile to be `22.04-curl` with `python3` installed. The downside is that I can't get the `./docker/wine/Dockerfile` to build from that updated `./docker/base/Dockerfile` image.
If you're willing to investigate that further, then we can unblock an upgrade.

**Comment by relativisticelectron** [comment]
The branch https://github.com/electron-userland/electron-builder/compare/master...relativisticelectron:upgrade_to_2204?expand=1  builds fine. However I ignored this issue that arose without the fixed wine version:  https://github.com/electron-userland/electron-builder/blob/a8418ac42d9775753f19794d38cd237600cf0993/docker/wine/Dockerfile#L6

**Comment by mmaietta** [comment]
Alright, let's use Impish, I don't see a reason as to why not. Please open a PR with your changes and we'll send it through the CI/CD
