### ISSUE TITLE
tiffutil error

### ISSUE THREAD

**Issue by khornberg** [electron-userland/electron-builder#69]
This relates to #45 

When I had either a blank background key or a non existing file I get a `tiffutil` error.
This was fixed by adding a background.

**Comment by stefanjudis** [comment]
Hey.

Please provide more information and follow https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md.

**Comment by khornberg** [comment]
Error below

```
- Running electron-builder 2.1.1
- Starting creation of installer for ´osx
Writing temporary ´appdmg.json´
Wrote temporary ´appdmg.json´
Kicking off ´appdmg´
appdmg: [1] Looking for target
appdmg: [2] Reading JSON Specification
appdmg: [3] Parsing JSON Specification
appdmg: [4] Validating JSON Specification
appdmg: [5] Looking for files
appdmg: [6] Calculating size of image
appdmg: [7] Creating temporary image
appdmg: [8] Mounting temporary image
appdmg: [9] Making hidden background folder
appdmg: [10] Copying background
appdmg: [11] Unmounting temporary image
appdmg: [12] Removing temporary image
/projects/docker-indicator/node_modules/electron-builder/cli.js:30
    throw error;
    ^

Error: Error running `tiffutil`! Exit code was 5
    at ChildProcess.<anonymous> (/projects/docker-indicator/node_modules/electron-builder/node_modules/appdmg/lib/util.js:30:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

The [files](https://github.com/khornberg/docker-indicator) I'm using are available. If one changes the background value to a blank string in the `packager.json` the above error is produced. I'm using node 4.2.2 and npm 2.14.7 on OS X.

This may not be an issue since it can be worked around by using a background image. I chose a 1x1 blank image. The fact that a background image is require can be implied by the examples in the readme. However, it may be helpful to make it more clear if this is the desired behavior. If the absence of a background should not break the build then this is an issue.

**Comment by stefanjudis** [comment]
Thanks. This is actually not on the side of `electron-builder`. Will ask at `appdmg` about that.

**Comment by stefanjudis** [comment]
I will update the documentation here when this question is resolved over at `appdmg`.

Thanks.

**Comment by develar** [comment]
In the 2.8+ API we require background image, but according to https://github.com/LinusU/node-appdmg/issues/76#issuecomment-158080026 we should not. If background is not explicitly specified, we must not substitute default value if file doesn't exist.
