### ISSUE TITLE
Error: Filename can either be an absolute HTTP[s] URL, *or* a file name

### ISSUE THREAD

**Issue by virror** [electron-userland/electron-builder#690]
* **Version**: 5.30.0

* **Target**: Win32

Im trying to use electron together with the electron release server (https://github.com/ArekSredzki/electron-release-server) but im getting a system error when using dots in the path for the auto-update server and thats required with the electron release server.
Im getting the same issue as here;
https://github.com/Squirrel/Squirrel.Windows/issues/436

**Comment by gdurastanti** [comment]
Getting this as well while using the autoUpdater in electron with electron-release-server backend. Any workarounds?

**Comment by virror** [comment]
Have not found any workaround sadly : /
I put the updated files on dropbox at the moment so i can continue, hope this can be fixed or worked around.

**Comment by virror** [comment]
ANyone??

**Comment by develar** [comment]
It is not electron-builder issue. Currently we are working on #529 and NSIS will be default target instead of Squirrel.Windows.

**Comment by virror** [comment]
Ok, thanx for the answer.
How does this package work with Squirrel.Windows? The only package i have added is this one and the electron one and i saw this was reported before and marked fixed in the squirrel.windows git, but how do i know what version is being used?

**Comment by develar** [comment]
> but how do i know what version is being used?

Latest version of Squirrel.Windows is bundled into your app.

**Comment by virror** [comment]
This one is marked as fixed almost a year ago so i guess this must me a new error then, thanx for the clarification : ) I will contact them about it, do you plan on abandoning squirrel after implementing NSIS or will you continue to use and update squirrel.windows? The electron release server only supports that atm : /

**Comment by develar** [comment]
> do you plan on abandoning squirrel after implementing NSIS or will you continue to use and update squirrel.windows

Although it is an open source project, personally I am not going to abandon Squirrel.Windows support. Personally I am not going to improve Squirrel.Windows, only maintains. As in this case – I don't want to waste my free time and investigate what's wrong with Squirrel.Windows if I am sure that is not an electron-builder bug. Instead, we will provide robust and maintainable NSIS/JS-based solution.

**Comment by virror** [comment]
I understand and have already posted an issue on their forum about it. I was just wondering tf you planned on updating squirrel.windows when there are official fixes even going forward?

**Comment by develar** [comment]
> I was just wondering tf you planned on updating squirrel.windows when there are official fixes even going forward?

Yes.

**Comment by virror** [comment]
Thank you, sorry for taking up your time : )

**Comment by AlexeyVoroshak** [comment]
One solution is to specify appUrl: 'http: // localhost: 1337', in the file config/local.js of electron-release-server.

**Comment by phoenix2692** [comment]
> One solution is to specify appUrl: 'http: // localhost: 1337', in the file config/local.js of electron-release-server.

Specifying appUrl fixed my issue. Thank you :)

**Comment by gdmec07150725** [comment]
I specify port 1337, but also has this issue. @phoenix2692

**Comment by Wiktor102** [comment]
Can confirm that specifying the `appUrl` option for electron-release-server solves the problem. You just need to specify it in the correct place and set the proper port (ex., I use Docker, so I had to use port 8080).

Nevertheless, this issue has nothing to do with **electron-builder**, therefore, it should be closed and any further discussion should happen inside of [electron-release-server repo](https://github.com/ArekSredzki/electron-release-server/issues).
