### ISSUE TITLE
Publish: custom version when using buildVersion

### ISSUE THREAD

**Issue by jeffdanielperso** [electron-userland/electron-builder#6901]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16.13.2

* **Electron Version**: 19.0.1

* **Target**: NSIS & DMG

We are working on a NX repository (angular / module federation / electron app).
Our concern is that the version of the Electron App and the Web App are not the same.

We played a lot with the `buildVersion / mac: bundleVersion / mac:bundleShortVersion` and looked at the code...
We can get a correct filename with the specific version but the publisher always use the `package.json version` as release number.
We think that the release version should be set to the `buildVersion` when it is setup.

**Comment by burgil** [comment]
Hey, Have you tried to overwrite the package.json using `extraMetadata` option?
Example for `electron-builder.yml`:
```yml
extraMetadata:
  version: 1.0.0
```

More on that here: https://www.electron.build/configuration/configuration.html#:~:text=extraMetadata

**Comment by jeffdanielperso** [comment]
@burgil It works. Thanks a lot.
