### ISSUE TITLE
Cross-compiled Windows application will no longer launch on Electron 18

### ISSUE THREAD

**Issue by felipe-linares** [electron-userland/electron-builder#6902]
* **Electron-Builder Version**: 22.0.3

* **Node Version**: 14.9.2 (also tried node v16 and didn't work)

* **Electron Version**: 18.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

Our team is currently updating our application to Electron 18 and our CI/CD works on a macOS machine that compiles the application for windows, macOS (both intel and M1).

The application on Windows no longer starts with error: `[19940:0530/134211.901:ERROR:crashpad_client_win.cc(814)] not connected`

We are able to reproduce this issue when compiling locally on an M1 MacBook pro and using that nsis installer on a windows machine (to rule out an issue with maybe just the deployment machine).

Any tips for debugging this would be appreciated as the application crashes before any of our logs even appear.

**Comment by 61go** [comment]
那怎么解决呢

**Comment by 61go** [comment]
Then how to resolve the problem...
