### ISSUE TITLE
NSIS Unistaller fails claiming application is running and cannot be closed!

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#6916]
* **Electron-Builder Version**:  23.0.3

* **Node Version**: 16.14.2

* **Electron Version**: 17.4.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS

Our application that has been working with electron-build 22.14.xx is now failing to uninstall.  The Uninstaller claims that the application is still running (it is not--tried doing this immediately after reboot) and asks if I want to close it.  Clicking on the OK button fails saying that the application cannot be closed and that I should close it manually and click Retry.

**Comment by mmaietta** [comment]
Hi @robertpatrick , is there anything unique about your installation setup? Are there multiple users logged in at the same time. I think I recall the PR that could have introduced this but struggling to find it atm.

**Comment by robertpatrick** [comment]
@mmaietta We found the issue and it appears that it has already been addressed in 23.1.0.  This was occurring on Windows machines with MKS Toolkit installed, where their Unix-like `find` utility was on the path before the normal Windows `find` utility.  This unexpected version of `find` was causing the uninstaller to fail.
