### ISSUE TITLE
CircleCi fails to build

### ISSUE THREAD

**Issue by Razzeee** [electron-userland/electron-builder#692]
* **5.18.0** is the first version which fails to build on circleCi for me

* **Target**: Linux

Up until version 5.17.1 everything builds without an error. As you can see here https://circleci.com/gh/mattermost/desktop/623

When going to 5.18.0 it fails with a "makeDirectory homeless?" error
https://circleci.com/gh/mattermost/desktop/630

You can find the code I'm trying to build in this PR https://github.com/mattermost/desktop/pull/257

If I can somehow help or provide anymore infos, please let me know.

**Comment by develar** [comment]
Please try 6.3.4.

**Comment by Razzeee** [comment]
Didn't change anything unfortunately.

https://circleci.com/gh/mattermost/desktop/655

**Comment by Razzeee** [comment]
We were able to reduce the time by not building in docker, so our problem is solved by that.
