### ISSUE TITLE
App install location

### ISSUE THREAD

**Issue by sho-87** [electron-userland/electron-builder#693]
* **Version**:  5.30.0

* **Target**: Windows

I'm using electron builder to package my app and can successfully create the .exe file for windows. Running this file starts an installer. When I check control panel I can see that the app is in fact installed, but where is the default install location? It doesn't show up in my programs list and I'm not sure where the app is installed to so cant actually run it

**Comment by develar** [comment]
Squirrel.Windows? Duplicates #551

**Comment by dash1001** [comment]
If build you app by electron-builder  ( NSIS ), yuo van  write it in package.js and the user can  change directory of installation path 
"nsis":{
      "oneClick": false,
      "allowToChangeInstallationDirectory":true
}

**Comment by rajkrrai** [comment]
Thanks.

Installed Path is: C:\Users\{yourPCname}\AppData\Local\Programs\{your APP name}

**Comment by ShahriarKh** [comment]
A list of all available options for future Googlers:
https://www.electron.build/configuration/nsis.html

**Comment by ShahriarKh** [comment]
> If build you app by electron-builder ( NSIS ), yuo van write it in package.js and the user can change directory of installation path "nsis":{ "oneClick": false, "allowToChangeInstallationDirectory":true }

+ A list of all available options for future Googlers:
https://www.electron.build/configuration/nsis.html
