### ISSUE TITLE
"Ozone X11" initially displayed in window title

### ISSUE THREAD

**Issue by lukas2** [electron-userland/electron-builder#6931]
<img width="523" alt="Screenshot 2022-06-09 at 17 24 39" src="https://user-images.githubusercontent.com/213249/172884393-2f7e879e-78c5-44dd-adf6-9ef034389025.png">

* **Electron-Builder Version**: 23.0.3

* **Node Version**: v16.13.2

* **Electron Version**: 17.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux (Ubuntu)

When the finished app starts, initially, and for a brief moment, the text "Ozone X11" is displayed in the title bar - before the actual correct title is displayed. I have experimented with several app specific settings but no luck. 

I have also tried setting `desktop.Name` in electon-builder config .. no change.

It's not clear if this is an electron-builder issue, but maybe it will ring a bell for someone if I post it here.

Any help is appreciated.

**Comment by mmaietta** [comment]
When you say "before the actual correct title is displayed", was this for a previous version of electron-builder with the same electron 17? Or was electron also updated?

**Comment by mmaietta** [comment]
https://github.com/electron/electron/issues/34467
