### ISSUE TITLE
Could not locate update bundle

### ISSUE THREAD

**Issue by lucaslomeu** [electron-userland/electron-builder#6932]
* **Electron-Builder Version**: 22.14.2

* **Node Version**: 16.14.2

* **Electron Version**: 13.1.9
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS, but i need WML

> [Error: Could not locate update bundle for com.github.Electron within file:///Users/lucas/Library/Caches/com.github.Electron.ShipIt/update.erv01nk/] {
>   code: 2,
>   domain: 'SQRLUpdaterErrorDomain'
> }
> Error: Error: Could not locate update bundle for com.github.Electron within file:///Users/lucas/Library/Caches/com.github.Electron.ShipIt/update.erv01nk/

**Comment by qiqetes** [comment]
Same thing happening to me. My guess is the cache clears too fast and is not able to quit and install after having the file unziped.

**Comment by lucaslomeu** [comment]
> > * **Electron-Builder Version**: 22.14.2
> > * **Node Version**: 16.14.2
> > * **Electron Version**: 13.1.9
> > * **Electron Type (current, beta, nightly)**: current
> > * **Target**: MacOS, but i need WML
> > 
> > > [Error: Could not locate update bundle for com.github.Electron within file:///Users/lucas/Library/Caches/com.github.Electron.ShipIt/update.erv01nk/] {
> > > code: 2,
> > > domain: 'SQRLUpdaterErrorDomain'
> > > }
> > > Error: Error: Could not locate update bundle for com.github.Electron within file:///Users/lucas/Library/Caches/com.github.Electron.ShipIt/update.erv01nk/
> 
> Ok, so I came with the solution.
> 
> Your application need a bundleId, **the problem is** even if you set it for the electron-packager in the package.json. When you execute the app with `npm start` the bundleId is set to `com.github.Electron` while the one in your packaged app that you uploaded to your releases server is: `com.yourcompany.yourapp`.
> 
> The autoUpdater checks them and silently deletes the unziped application, giving you the error `Could not locate update bundle...`.
> 
> ### Solution:
> Execute the autoupdater with your packaged app.

I managed to solve this but now I have another problem.. this autoUpdater is getting more and more complicated
New Issue:  https://github.com/electron-userland/electron-builder/issues/6969

**Comment by Vuduccong2000** [comment]
there is my package.json file, when i run npm start still the same error

**Comment by whitesunset** [comment]
same issue, any solution?

**Comment by lucaslomeu** [comment]
At the time I managed to solve the problem, but I no longer have the code or remember the solution. Can you send a print or something like that to try to help?
