### ISSUE TITLE
Using "signAndEditExecutable": false and "verifyUpdateCodeSignature": false will disable icon

### ISSUE THREAD

**Issue by VanDeny** [electron-userland/electron-builder#6934]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16.14.2

* **Electron Version**: 19.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

If you are using     
```
"signAndEditExecutable": false,
"verifyUpdateCodeSignature": false,
```
the electron-builder ignores any icon specified in electron-builder.json, resulting in app using the native app icon instead of specified one. This is probably not intended behavior(disabling code signing in electron-builder should not disable app icon).

To reproduce issue you can use this [project](https://github.com/VanDeny/angular-electron).

**Comment by VanDeny** [comment]
Maybe friendly ping so this doesn't just go by?

**Comment by VanDeny** [comment]
Maybe friendly ping @mmaietta so this doesn't just go by?

**Comment by mmaietta** [comment]
Looking at the code, seems to be expected behavior, it's in `signAndEditResources`
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/winPackager.ts#L302

Signing is the only time `rcedit` is used.

**Comment by rbartosek202** [comment]
We facing the same problem. We have set 
{
"signAndEditExecutable": false,
"verifyUpdateCodeSignature": false
}

and it is not possible set icon for windows.
What is recomended way if you do not want sign app and need set icon?

**Comment by mmaietta** [comment]
Editing the executable is the only way to apply an icon, which is paired heavily with signing logic flow.

Happy to review a PR that decouples them, but it seems like it's a very complex flow that I'm not familiar with.
