### ISSUE TITLE
Electron builder NSIS error

### ISSUE THREAD

**Issue by acuemor** [electron-userland/electron-builder#694]
* **Version**: 5.22.1

* **Target**: Windows 7 x64

I have an electron app. When I built my app, I was generating an .exe with NSIS. It worked fine! But suddenly it stopped working. I checkout to a tag that I know was fine (I built my app in this tag), but it does not work.

This is the [error log](https://github.com/electron-userland/electron-builder/files/432004/npm-debug.txt)

Here is a dummy example, [electron-quick-start.zip](https://github.com/electron-userland/electron-builder/files/432152/electron-quick-start.zip), to reproduce the error.

Just needed: npm install && npm run dist

**Comment by develar** [comment]
Duplicates #700
