### ISSUE TITLE
Unable to install .deb packages due to embedding CI tag in Version number

### ISSUE THREAD

**Issue by antonycourtney** [electron-userland/electron-builder#6945]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: 16.5.0

* **Electron Version**: 18.0.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux .deb package

I've recently gotten electron-builder building and uploading my packaged app in CI (using Azure Pipelines) for Mac, Windows and Linux. It's mostly working great, and I was all set to do a release, when I discovered that the generated .deb file won't install (using `dpkg` on Ubuntu 20) because of the format of the `Version` field in the generated .deb file.
The issue appears to be that, under CI, electron-builder is automatically adding a tag (presumably from an env var set by the CI system) to the generated version number:

```sh
$ sudo dpkg -i tad_0.10.1_amd64.deb
[sudo] password for parallels: 
dpkg: error processing archive tad_0.10.1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'tad':
 'Version' field value '0.10.1-IndividualCI_refs_heads_master_25': invalid character in revision number
Errors were encountered while processing:
 tad_0.10.1_amd64.deb
```

Looking at the .deb package contents:
```sh
$ dpkg --info tad_0.10.1_amd64.deb
 new Debian package, version 2.0.
 size 138734940 bytes: control archive=9440 bytes.
     510 bytes,    14 lines      control              
   32336 bytes,   292 lines      md5sums              
     257 bytes,    10 lines   *  postinst             #!/bin/bash
      66 bytes,     4 lines   *  postrm               #!/bin/bash
 Package: tad
 Version: 0.10.1-IndividualCI_refs_heads_master_25
 License: MIT
 Vendor: Antony Courtney <antony@xxxxxx.com>
 Architecture: amd64
 Maintainer: Antony Courtney <antony@xxxxxx.com>
 Installed-Size: 525349
 Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
 Recommends: libappindicator3-1
 Section: default
 Priority: optional
 Homepage: https://www.tadviewer.com
 Description: 
   Tabular data viewer desktop app, built with Electron
```

Is there some way to change the behavior of electron-builder so that it just uses the `version` from `package.json` as the `Version` field in the generated .deb file, without attempting to append the build tag / build number?

(That said, I can see that it's quite helpful and convenient to have this build tag stamped into the generated package for debugging purposes. Would love to know how others are dealing with this, or if there is some other recommended solution for getting installable .deb files).

Thanks in advance for any help!

**Comment by antonycourtney** [comment]
I've struggled all evening to figure this out and find a workaround, but I'm stumped. Looking at the code, it looked to me like this was the `buildVersion` in the constructor for `AppInfo`, as there is code in there that definitely constructs a `buildVersion` from `version` with the build number appended. But no amount of either explicitly setting `buildVersion` in my `package.json` or trying to explicitly set the environment variables seemed to have any effect.
But then I noticed that the code in `fpm.ts` seems to use `appInfo.version` (not `buildVersion`) and I wasn't able to fully trace how that's getting set (since it's clearly not just the unqualified `version` at the top level of my `package.json`).

I've made a small donation to the project, and would greatly appreciate any help...

**Comment by mmaietta** [comment]
So, I see that it's being set by `metadata`
https://github.com/electron-userland/electron-builder/blob/369f1fa793c28d8743e19ef07ce6eb091c191fb0/packages/app-builder-lib/src/appInfo.ts#L36

I think metadata is being pulled from: 
https://github.com/electron-userland/electron-builder/blob/03cc9b96e0be07ef3450e3992eafcb7fe903a853/packages/app-builder-lib/src/packager.ts#L322-L330

Do you have extraMetadata in your config by chance? It looks like it'll override any `metadata.version`
