### ISSUE TITLE
Shortcut not found .exe

### ISSUE THREAD

**Issue by lucaslomeu** [electron-userland/electron-builder#6974]
* **Electron-Builder Version**: ^23.0.3

* **Node Version**: 16.14.2

* **Electron Version**: ^13.1.9

* **Target**: -mwl (mac, windows and linux)

Shortcut not found when I install on windows. On Mac it works perfectly.

 
![image](https://user-images.githubusercontent.com/67932278/176695605-718e527b-b567-4595-99a0-2f93d9999770.png)

**Comment by mmaietta** [comment]
Does your installer script need to have it spelled `extractEmbeddedAppPackage`? A macro already exists with that name per the error logs.
```
!macro: macro named "extractEmbeddedAppPackage" already exists!
```
Are you trying to override it?

**Comment by lucaslomeu** [comment]
> Does your installer script need to have it spelled `extractEmbeddedAppPackage`? A macro already exists with that name per the error logs.
> 
> ```
> !macro: macro named "extractEmbeddedAppPackage" already exists!
> ```
> 
> Are you trying to override it?

I saw this possible "solution" in an older issue, it was even you who said the resolution.

I tried to use it like this to fix this of not finding the executable shortcut. On Mac M1 it works perfectly, only on windows it doesn't.

**Comment by liamlkh** [comment]
I have the exact problem. How did you fix it?
