### ISSUE TITLE
Is there any way to customize the message box when .net Framework is not installed on clients computer?

### ISSUE THREAD

**Issue by Chenimal** [electron-userland/electron-builder#698]
* **Version**: 
5.12.0

* **Target**: 
windows squirrel

I use Windows.Squirrel to build .exe for windows platform. It requires .Net 4.5 to be installed when installing the app. I want to add a download link of .Net 4.5 into the message box. Right now it only displays as 

![default](https://cloud.githubusercontent.com/assets/15117627/17968090/82c97156-6afd-11e6-84c6-46486b178e5f.png)

Thanks!

**Comment by develar** [comment]
Just use NSIS installer instead of Squirrel.Windows. #529 will be fixed soon.
