### ISSUE TITLE
Taskbar icon changes when pinning and unpinning

### ISSUE THREAD

**Issue by adriencarbonaro** [electron-userland/electron-builder#6984]
* **Electron-Builder Version**: `v22.14.9`

* **Node Version**: `v14.16.1`

* **Electron Version**: `v12.0.9`

* **Target**: Windows

## Description 

- When I package, install then run my app, it seems the icon in the taskbar is not the one I want (seems like a cache issue). It is more pixelated and smaller. Simply pinning to taskbar then unpinning is enough to make it perfect, but it comes back to ugly when pinning again.
- I also have the problem where using `BrowserWindow.setIcon` does not work in this case, but works after the sequence of pinning unpinning.

I've seen issues with icons but nothing describing this issue. Can you help ?

**Comment by jadedigital** [comment]
Did you find a solution to this issue? I'm having the same problem
