### ISSUE TITLE
Msi installer not support auto-update

### ISSUE THREAD

**Issue by dlliu114** [electron-userland/electron-builder#6985]
* **Electron-Builder Version**:  22.10.5

* **Node Version**: 12.22.4

* **Electron Version**: 13.6.3
* **Electron Type (current, beta, nightly)**:

* **Target**:  msi

After installing the application with the msi installation package, a new version is detected. After downloading, reopening the application is still the old version.

**Comment by jukicatoni** [comment]
On windows only NSIS target supports auto updates, check the [docs](https://www.electron.build/auto-update).
