### ISSUE TITLE
Sync the configuration of nsis to msi

### ISSUE THREAD

**Issue by dlliu114** [electron-userland/electron-builder#6991]
* **Electron-Builder Version**: 22.10.5

* **Node Version**: 12.22.4

* **Electron Version**: 13.6.3
* **Electron Type (current, beta, nightly)**:

* **Target**:  msi

when I wanted to create MSI installer, NSIS configuration like include, installerIcon, uninstallerIcon, deleteAppDataOnUninstall  cannot be used.  Is there any plan to sync the configuration of nsis to msi？

**Comment by mmaietta** [comment]
Sorry, there are no plans to do so. Closing ticket
