### ISSUE TITLE
Arm64 / Universal Build Causes Blank Screen

### ISSUE THREAD

**Issue by emaciel10** [electron-userland/electron-builder#6993]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: 14.19.3

* **Electron Version**: 19.0.8

* **Target**: mac arm64 / universal

If we build our electron application for x86 the application loads and works as expected. Once we change our target to arm64 or universal the application initially loads but we eventually get a blank screen and a devtools window that says: "Devtools was disconnected from the page."

Loading the application using Debugtron I can see these error logs:
```
DevTools listening on ws://127.0.0.1:55114/devtools/browser/84014e38-536a-49c0-82a8-5103746fb6a8
Screen width: 1728
objc[14462]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23a5731a8) and /Applications/Hive.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10948d3c8). One of the two will be used. Which one is undefined.

<--- Last few GCs --->

[14468:0x148008000]     3446 ms: Scavenge 121.9 (136.7) -> 115.8 (137.2) MB, 0.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
[14468:0x148008000]     3502 ms: Scavenge 123.5 (137.5) -> 116.9 (139.0) MB, 0.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
[14468:0x148008000]     3543 ms: Scavenge 123.5 (139.2) -> 117.8 (139.5) MB, 0.9 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task; 


<--- JS stacktrace --->
```

And there is another issue related to this here but not sure if this is the cause for the blank screen
https://github.com/electron/electron/issues/33685

**Comment by harlandjp** [comment]
Facing the same issue. Did you find any hints?

**Comment by emaciel10** [comment]
@harlandjp unfortunately we have not found a workaround for this issue
