### ISSUE TITLE
Cannot use glob/file patterns in mac.binaries

### ISSUE THREAD

**Issue by gsidsid** [electron-userland/electron-builder#7000]
* **Electron-Builder Version**: 
22.11.7

* **Node Version**: 
15.14.0

* **Electron Version**: 14

* **Target**: 
Mac

I need to sign a ton of python `*.cpython-39-darwin.so` files inside our application in our extraResources directory. These files change as our python backend evolves, so ideally I could use a file pattern like `Resources/extraResources/core/Contents/MacOS/**/*.cpython-39-darwin.so` in the mac.binaries property of the electron-builder.config.js file to add certain files that need to be signed explicitly for our app to pass Apple notarization.

However, when I import glob and try to do this myself (since it doesn't seem mac.binaries supports patterns), I get strange errors that say `Please specify 'version' in your package.json`, even though it'd work without a version property before importing any modules. Even if I do specify a version in my package json (which gets replaced later in our build process anyway),  executing our build process for our windows target still produces the same error, even though none of this is relevant to the windows target.

A simple enough fix I presume would be to just support file patterns for the mac.binaries property. Would be a huge quality of life upgrade for us as we're currently hardcoding hundreds of paths in the electron-builder.config.js.

**Comment by mmaietta** [comment]
I took a look at the code and the `mac.binaries` is passed basically verbatim to [electron-osx-sign](https://github.com/electron/osx-sign) upstream package. All electron-builder does is resolve if the string is a relative destination path or an absolute path.  
I'm not sure if I can implement glob pattern matching using the same methods that are done for `files`, extras, etc. Happy to review a PR contribution though

Can you elaborate on:
>However, when I import glob and try to do this myself (since it doesn't seem mac.binaries supports patterns), I get strange errors that say Please specify 'version' in your package.json

How are you applying this via config file to set the `binaries` entry?

**Comment by gsidsid** [comment]
Ah, alright, thanks for checking it out. Will see if I have any options with a electron-osx-sign script of some sort.

Wasn't too sure what I was doing frankly but I tried using something like:

```
binaries: [
    ...glob.sync('packages/extraResources/core/Contents/MacOS/**/*.cpython-39-darwin.so').map(path => 'Resources/' + path.substring(9)),
    // resolves to something like "Resources/extraResources/core/Contents/MacOS/lib-dynload/_asyncio.cpython-39-darwin.so"
    // paths like which are currently hardcoded en masse
]
```

which hasn't been working.
