### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by imbichitra** [electron-userland/electron-builder#7004]
Hi Team.
I am doing two level of sign to the exe file and try to auto update also, but at the time of auto update it shows below error.

`
Error: Error: sha512 checksum mismatch, expected WKPMD//jTxK3Zls7i3vvZlPbKQglMI3dtHDUhTZRjwMbkRDHcip3GTJfQ4bjSFqmZVVQI7zMQfveSwtPSD0aPA==, got 9EkyQVFv0jEOMdAdqdbokkk19TAK+PPishqvqJUOLYW0cv6Usrhp5euewA1k+ewuKzsYIpujvHSNL0gZidGTMg==
`

**So any command that use the signed ex to update the  latest.yml**

Thanks

**Comment by Sdqumar** [comment]
have same issue, any help is appreciated
