### ISSUE TITLE
Got allows a redirect to a UNIX socket

### ISSUE THREAD

**Issue by benjamin-mogensen** [electron-userland/electron-builder#7006]
### Expected Behavior

No vulnerabilities reported.

### Actual Behavior

Vulnerabilities when doing `npm audit` and in Github:
```
electron-builder@23.1.0 requires got@^9.6.0 via a transitive dependency on package-json@6.5.0
```
I am unable to get rid of these even updating both Electron and Electron Builder to their latest versions

**Comment by sandersdevelopments** [comment]
Same here. Our CI is very sad about it 😿

**Comment by dongivan** [comment]
electron-builder should update dependency `update-notifier` to version 6.
