### ISSUE TITLE
build.files won't work as expected

### ISSUE THREAD

**Issue by meltedspark** [electron-userland/electron-builder#701]
* **5.34.1**: 

* **1.3.4**: 

I would expect that if I specify `"files": ["*.js"]`, it would include all the `.js` files in the `app` folder and its subfolders (similarly to `find -name`) into the build. However it includes only `.js` files in the `app` folder (won't include the subfolders).   
Specifying `"files": ["**/*.js"]` causes `electron-builder` to include the **whole** `app` folder into the build (i.e. the same as specifying  `"files": ["**/*"]`).  
Both options appear to not work in a right way, so I suppose there is a bug here.

**Comment by develar** [comment]
<img width="1914" alt="screen shot 2016-08-27 at 16 41 06" src="https://cloud.githubusercontent.com/assets/350686/18028084/158a6b80-6c75-11e6-9137-225dc37bb449.png">

**Comment by meltedspark** [comment]
This particular issue has been fixed. Still a problem here: empty directories (that are not specified in `build.files`) are being copied. 
To reproduce: 
 - Checkout [this](https://github.com/meltedspark/electron-angular2-native) repo
 - Run `npm dist:*whatever*`
 - Find the `dist` directory - there are empty directories that are not specified in the `build.files` (in `plugins\native\precompiled-library`)

**Comment by develar** [comment]
@meltedspark Filed as #732
