### ISSUE TITLE
Opening the app locally works fine, but publishing to the Mac App Store opens a white screen

### ISSUE THREAD

**Issue by jialinghui** [electron-userland/electron-builder#7014]
* **Electron-Builder Version**: 23.3.0

* **Node Version**: 14.16.1

* **Electron Version**: 15.4.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas

<img width="800" alt="image" src="https://user-images.githubusercontent.com/29021622/179950849-bf8c5583-5ce7-4230-9d3e-ed49227b9eae.png">

**Comment by technotip** [comment]
Check the logs in devtools.
