### ISSUE TITLE
Copying files in directory with `extraFiles` without copying directory structure

### ISSUE THREAD

**Issue by donovanhiland** [electron-userland/electron-builder#7015]
* **Electron-Builder Version**: 
22.14.13

* **Node Version**: 
v16.14.2

* **Electron Version**:
18.0.1
* **Electron Type (current, beta, nightly)**:
current

* **Target**: 
Windows

I'm trying to copy `extraFiles` in to my packaged app's content directory. I'm trying to include .dll files my app needs to run so I need those files to be directly in the root. In relation to the root of my project I'm keeping those dependencies in a directory, let's say `build/win32/dependencies` and I include `build/win32/dependencies/*.dll` in my `extraFiles` configuration for windows. I'm curious if there's a supported way to include the files inside a directory without maintaining the parent directory structure in the packaged app?

relevant config:
```
{
...
  win: {
    extraFiles: "build/win32/dependencies/*.dll",
  },
...
}

**Comment by donovanhiland** [comment]
I should have known as soon as I asked the question I'd find the answer. Leaving this here in case it helps someone in the future.

If I target the files I'd like to move via the [FileSet ](https://www.electron.build/configuration/contents.html#filesetfrom) type it works as expected.

I've updated my config to:
```
{
...
  win: {
    extraFiles: [
      { from: "build/win32/dependencies", to: ".", filter: ["*.dll"] },
    ],
  },
...
}
```

The first time I tried this it wasn't working, no files were being moved at all. I just needed to look closer at the build output to find that I had a typo in my `from` path 🤦🏻‍♂️

**Comment by RSS1102** [comment]
> 我一问这个问题就应该知道我会找到答案。把它留在这里，以防将来对某人有所帮助。
> 
> 如果我将我想通过[FileSet](https://www.electron.build/configuration/contents.html#filesetfrom)类型移动的文件作为目标，它会按预期工作。
> 
> 我已将我的配置更新为：
> 
> ```
> {
> ...
>   win: {
>     extraFiles: [
>       { from: "build/win32/dependencies", to: ".", filter: ["*.dll"] },
>     ],
>   },
> ...
> }
> ```
> 
> 我第一次尝试这个时它不起作用，根本没有文件被移动。我只是需要仔细查看构建输出，发现我的`from`路径中有错别字🤦🏻‍♂️

Thank you. I'm also troubled by this problem.

It's solved.
