### ISSUE TITLE
Electron-builder won't copy .pyc files even when explicitly added to files

### ISSUE THREAD

**Issue by InstantCoffeeGuy** [electron-userland/electron-builder#7016]
* **Electron-Builder Version**: 23.3.1
* **Node Version**: 18.6.0
* **Electron Version**: 19.0.8
* **Electron Type (current, beta, nightly)**: current
* **Target**: the bug occurs for any target tested

I went to package an old electron app and found that it wouldn't include the .pyc files. Reading the documentation it appears that these are now excluded by default. However adding a line:

>"files": ["**/*.pyc"],

either doesn't copy the pyc files or causes an error:

>Application entry file ".../app/main.js" does not exist. Seems like a wrong configuration.

I get the first behavior if there is an exclusion in the platform-specific files rules and the second behavior if I leave out any platform-specific files rules.

Further odd behavior occurs if I make the global files:

>"files": ["**/*"]

and the platform-specific files:

>"files": ["!directory/"]

In which case I get an error:

>EEXIST: file already exists, symlink ...

I think there may be several bugs here interacting, but the documentation is relatively vague too. In any case, I think there should be a way to copy pyc files since many apps need them in the final build.

**Comment by mmaietta** [comment]
Can you try using `next` 23.3.3? I'm wondering if that fixes your "file already exists" error

>I get the first behavior if there is an exclusion in the platform-specific files rules and the second behavior if I leave out any platform-specific files rules.

Default pattern `**/*` is not added to your custom if some of your patterns is not ignore (i.e. not starts with !). `package.json` and `**/node_modules/**/*` (only production dependencies will be copied) is added to your custom in any case. All default ignores are added in any case — you don’t need to repeat it if you configure own patterns.
Ref: https://www.electron.build/configuration/contents
