### ISSUE TITLE
After obtaining administrator rights, click the previous step to disappear the installation program

### ISSUE THREAD

**Issue by web-liuyang** [electron-userland/electron-builder#7017]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 14.20.0

* **Electron Version**: 15.3.5

* **Target**:  win10

Hello, I have a question: Ordinary users need administrator rights when they click on the installation package and select next. However, after I give the permission, I can go to the next step, but clicking on the previous step will directly close, without returning to the interface of the previous step.
Can you cancel the previous step? Or is there another way to solve it?

![image](https://user-images.githubusercontent.com/52391595/180169265-ad492c26-0328-4241-a971-fc5b3b136771.png)

![image-1](https://user-images.githubusercontent.com/52391595/180169308-727e2a39-5c62-446b-89af-4abb8e60e20d.png)

**Comment by Cathinty1** [comment]
请问你的问题解决了吗
