### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by Toflar** [electron-userland/electron-builder#702]
Hi

It took me like an hour now to understand how the part about the `install-app-deps` postinstall script was meant. The way it is written in the README sounds to me like you would specify **both**, the `dependencies` as well as the `devDependencies` in the development `package.json` and the `install-app-deps` script would just **read** that development `package.json` and install only the `dependencies` in the `app` folder. However, that's not the case. The `install-app-deps` script just executes a simpe `npm install` in the `app` folder so you **must** define the `dependencies` in the app `package.json` as well!

Can you confirm this? I'll be happy to improve the docs then :)

**Comment by meltedspark** [comment]
That is correct. You should specify `devDependencies` in the top level `package.json` and `dependencies` in the app `package.json`.

**Comment by Toflar** [comment]
I see, but you need the `dependencies` on top level too, don't you? I test if my electron app is working by simply executing `electron .`. Is there a better approach for that?

**Comment by meltedspark** [comment]
You don't need `dependencies` on the top level. Just add it on the app level and run your electron app by executing `electron ./app`.

**Comment by Toflar** [comment]
Hm, could indeed do this. That was too obvious :D Still I want to prevent other users from having the same issue or let's just call it my faulty reasoning. I'll submit a PR. Thanks for your help!

**Comment by Toflar** [comment]
Closing in favor of https://github.com/electron-userland/electron-builder/pull/703 :)
