### ISSUE TITLE
Electron Updater changes file name top updater.appImage. GH_Token not found when set in enviroment

### ISSUE THREAD

**Issue by kamranRNS** [electron-userland/electron-builder#7022]
Node.js Version 16.14.2, 
Chromium 102.0.5005.148
Electron 19.0.8.
OS:Linux

1. After the auto-update is successfully installed it changes appImage file name to update.AppImage. Whereas it should only change version number rather than the whole name as its not possible to identify files after an update

2. Secondly, auto update works fine when the token is set in electron-builder.json but when set in terminal it logs error of 404 of invalid token
i-e when set gh_token using the following command in terminal 
export GH_TOKEN="my_token"

Our team Is building co-operate level desktop app for Korean company we faced these issues while doing RND 
It will help us a lot if these issues are resolved so we may move forward for the project

### Electron-builder.json

{
  "productName": "sot-dev",
  "appId": "com.example.sot",
  "asar": false,
  "directories": {
    "output": "build/${version}"
  },
  "npmRebuild": false,
  "mac": {
    "hardenedRuntime": false,
    "provisioningProfile": "build/embedded_mas.provisionprofile",
    "extendInfo": {
      "NSMicrophoneUsageDescription": "I need access to your microphone to send your voice to others in the session room.",
      "NSCameraUsageDescription": "I need access to your camera so that others can see you in the session room."
    }
  },
  "dmg": {
    "background": "build/background.png",
    "iconSize": 80,
    "iconTextSize": 34,
    "window": {
      "x": 0,
      "y": 0
    }
  },
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": ["x64", "ia32"]
      }
    ]
  },
  "linux": {
    "target": "AppImage",
    "artifactName": "SoT.${version}.${ext}"
  },
  "publish": [
    {
      "provider": "github",
      "private": true,
      "owner": "kamranRNS",
      "repo": "SoT-desktop-app",
      "token": "my token"
    }
  ]
}
after update
![image](https://user-images.githubusercontent.com/109574617/180597884-34018348-43db-4323-930e-2dd4ccdea21f.png)

**Comment by AhsanAli13503** [comment]
facing same issue

**Comment by AhsanAli13503** [comment]
any updates

**Comment by mmaietta** [comment]
`$GH_TOKEN` is only read during publish. It is not available for usage during runtime (updating)

**Comment by kamranRNS** [comment]
> `$GH_TOKEN` is only read during publish. It is not available for usage during runtime (updating)

I have added GH_Token in the environment and build app with it but when running that build file it shows logs 404 un authorized

**Comment by mmaietta** [comment]
>but when running that build file it shows logs 404 unauthorized

Please see: https://github.com/electron-userland/electron-builder/issues/7022#issuecomment-1197054298
