### ISSUE TITLE
Bitbucket OAuth Support

### ISSUE THREAD

**Issue by FizzBuzz791** [electron-userland/electron-builder#7024]
* **Electron-Builder Version**: N/A

* **Node Version**: N/A

* **Electron Version**: N/A
* **Electron Type (current, beta, nightly)**: N/A

* **Target**: N/A

I'm trying to publish my app with Bitbucket and from what I can see, the [BitBucket Publisher](https://github.com/electron-userland/electron-builder/blob/66ca625f892329fd7bedf52fddc6659ec83b7cd3/packages/app-builder-lib/src/publish/BitbucketPublisher.ts#L71) only uses Basic auth. It'd be great if it could support OAuth and the client-cred flow. At present, I have to use my own account and generate an app password, which isn't the best flow.

**Comment by mmaietta** [comment]
Would love to have a community contribution on this. Setting up a local dev environment is fairly straight forward too
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
