### ISSUE TITLE
Unable to uninstall or install Lens

### ISSUE THREAD

**Issue by craph** [electron-userland/electron-builder#7025]
* **Electron-Builder Version**: ^23.1.0

* **Node Version**: >=0.12 <0.13

* **Electron Version**: 15.5.7

I have install k8slens and when I want to uninstall it the nsis uninstaller show a message like Lens is running and try to close it. But it fail to close it and it can't uninstall the software.

Issue reference : https://github.com/lensapp/lens/issues/5887

Do you have any idea ?

Thank you very much.
Best regards,

**Comment by craph** [comment]
Maybe a similar issue : https://github.com/electron-userland/electron-builder/issues/6865

**Comment by craph** [comment]
Anyone can help on this kind of issue ?

**Comment by craph** [comment]
Is it possible that there are some conflicts with antivirus or EDR like Crowdstrike with the NSIS installer ?
To be able to uninstall correctly k8slens version `5.5.4` I had to install an old version of the soft and I can uninstall both version correctly.

I the version `5.5.4` of Lens it use electron-builder version `^23.1.0` and in the version `4.2.4` it use the version `^22.7.0` of electron-builder. 

Did you do some major changes with the NSIS installer steps / process ? or are you aware of possible conflicts / issues with edr like Crowdstrike ?
Thank you very much.

**Comment by mmaietta** [comment]
I can't really tell via the diff https://github.com/electron-userland/electron-builder/compare/v22.7.0...v23.1.0
Between those versions was also a doc site migration and a "prettier" release to bring consistency to the code format, so the diff is huge

Can you please try latest 23.3.3?

**Comment by craph** [comment]
problem solved with version 23.3.3
