### ISSUE TITLE
Publish timeout too short

### ISSUE THREAD

**Issue by FizzBuzz791** [electron-userland/electron-builder#7026]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: N/A

* **Electron Version**: N/A
* **Electron Type (current, beta, nightly)**: N/A

* **Target**: MSI

The [60-second timeout](https://github.com/electron-userland/electron-builder/blob/869ec27fd1d99b9913875cb4d7ae7c733c1f3e25/packages/builder-util-runtime/src/httpExecutor.ts#L329) is infeasible for larger uploads. For example, I'm uploading a 150Mb MSI to BitBucket and it regularly times out, I think the upload speed to BitBucket servers is limited as my connection has a 40Mbps upload.

Ideally, we could just have a configuration option to override the default.

**Comment by mmaietta** [comment]
Hmmm, I'll see if I can add a property to `publish` config for timeouts for API requests and data uploads. Not sure how well the timeout callback will work, but maybe I can cover it with some integration tests

**Comment by mmaietta** [comment]
@FizzBuzz791 thoughts on this?
https://github.com/electron-userland/electron-builder/pull/7028

**Comment by FizzBuzz791** [comment]
@mmaietta wow, you work quick! Looks great 🤩
