### ISSUE TITLE
Change install directory when installing EXE or MSI silently

### ISSUE THREAD

**Issue by vtebano13** [electron-userland/electron-builder#7031]
* **Electron-Builder Version**: 19.56.0

* **Node Version**: 14.15.1

* **Electron Version**:4.2.12
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows 64

Is there a way to change the installation directory silently at runtime when installing the freshly built EXE or MSI.

**Comment by mmaietta** [comment]
Not sure I follow, but would this help? "How do change the default installation directory to custom?"
https://www.electron.build/configuration/nsis#common-questions

**Comment by vtebano13** [comment]
Can that custom directory be changed once the MSI or exe has been built?

I was looking to run something like this where I can set the install directory when running the exe/msi.

msiexec /i "msi path" INSTALLDIR="C:\myfolder" /qb

**Comment by mmaietta** [comment]
Not for msi unfortunately. I did notice there is code for it in NSISUpdater though for install directory.
https://github.com/electron-userland/electron-builder/blob/caf05a9dab9c6a99aac5420f58c85fff1eb54b3e/packages/electron-updater/src/NsisUpdater.ts#L18-L23

**Comment by vtebano13** [comment]
Correct me if I am wrong but isn't this for when updating an already installed application?  
If so then this would not help me with this issue. 

Kinda shocked that this is not something that has not come up before.  Alot of IT departments want to silently install an MSI/EXE from which they may need to change the location of the installation, maybe the primary location is not allowed to install into.

**Comment by mmaietta** [comment]
Happy to review a PR for having that functionality added :) 
I'm not comfortable working with nsis install scripts and I'm not familiar with msi implementation either

Setting up a dev environment is fairly straightforward too https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by vtebano13** [comment]
I was able to figure this out on my own.  Just in case anyone else runs into this.

Silent install of an MSI to a custom location at run time.
<MSI Application Name>.msi  /quiet  APPLICATIONFOLDER="<location to install files>"

**Comment by yssmile** [comment]
try this  xxx.exe /S /D=D:\xxx\xxxx
