### ISSUE TITLE
Vue CLI build failed. Please resolve any issues with your build and try again.

### ISSUE THREAD

**Issue by zhangshoucheng1** [electron-userland/electron-builder#7033]
PS E:\项目\vue-cli\vue2-cli-vue-router-3 - 副本 (2)> npm run electron:build

> gshop@1.0.0 electron:build E:\项目\vue-cli\vue2-cli-vue-router-3 - 副本 (2)
> vue-cli-service electron:build

 INFO  Bundling render process:

✔  Building modern bundle for production...
 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gshop@1.0.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gshop@1.0.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.   

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86189\AppData\Roaming\npm-cache\_logs\2022-07-31T15_03_20_151Z-debug.log       
PS E:\项目\vue-cli\vue2-cli-vue-router-3 - 副本 (2)>

**Comment by mmaietta** [comment]
What version of electron-builder are you on?

Please try running with `DEBUG=electron-builder` and post back the logs. My best guess is that `vue-cli-service` is using an old version of electron-builder

**Comment by zhangshoucheng1** [comment]
在不是electron创建vue项目中，在另一个新的vue项目中通过  vue add electron-builder  命令打包成桌面程序
需要在 package.json 配置

"repository": {
    "type": "git",
    "url": "https://github.com/electron-userland/electron-builder.git"
  },

**Comment by Carry6666** [comment]
你好 ，可以问一下，您这个问题解决了么
