### ISSUE TITLE
app. Ispackaged is also false after it is packaged by electronic builder

### ISSUE THREAD

**Issue by message163** [electron-userland/electron-builder#7034]
import { app, BrowserWindow } from 'electron'

import path from 'path'
let win: BrowserWindow | null;

const createWindow = () => {

    win = new BrowserWindow({
        webPreferences: {
            devTools:true,
            contextIsolation: false,
            nodeIntegration: true
        }
    })

    if (app.isPackaged) {
        win.loadFile(path.join(__dirname, '../index.html'))
    } else {
        win.loadURL(`http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`)
    }

}

app.whenReady().then(createWindow)

**Comment by mmaietta** [comment]
That's electron code and functions like this:
https://github.com/electron/electron/blob/db3cf52add2c88f99dc0b6c787ebbe801cc934c0/lib/browser/api/app.ts#L40-L46
```
App.prototype.isPackaged = (() => {
  const execFile = path.basename(process.execPath).toLowerCase()
  if (process.platform === 'win32') {
    return execFile !== 'electron.exe'
  }
  return execFile !== 'electron'
})()
```
