### ISSUE TITLE
TravisCI electron builder not publish to GitHub from MacOS

### ISSUE THREAD

**Issue by djiangdev** [electron-userland/electron-builder#7042]
* **Electron-Builder Version**:  23.3.3

* **Node Version**: 16.16

* **Electron Version**: 18.2.3

![Screenshot_6](https://user-images.githubusercontent.com/86147621/182647545-c7cd3408-866b-40d4-9d85-262e49365c8b.png)
![Screenshot_5](https://user-images.githubusercontent.com/86147621/182631584-d6af72f1-3a6e-403f-8bd4-b97cb687970b.png)
![Screenshot_4](https://user-images.githubusercontent.com/86147621/182631593-b4283c05-5c42-406d-90e9-95a41b3191b3.png)

**Comment by mmaietta** [comment]
Hard to say what happened. Please rerun with DEBUG=electron-builder env var set and see what pops up that could be causing your build to hang/stall

**Comment by djiangdev** [comment]
> 
![Screenshot_7](https://user-images.githubusercontent.com/86147621/185382467-c5b50585-3378-49fb-a1b1-9c051ae5710a.png)

**Comment by mmaietta** [comment]
electron-builder doesn't have any logging that says "Skipping notarizing step". Are you using a plugin?
