### ISSUE TITLE
CSC_LINK-variable doesn't work if base64-encoded value doesn't end with =

### ISSUE THREAD

**Issue by acutus** [electron-userland/electron-builder#7045]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.16.0

* **Electron Version**: 19.0.10
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

Code signing with CSC_LINK-variable pointing to a base64 encoded .p12 certificate which happens to be of suitable byte-length so that base64-encoded cert doesn't end with `=` doesn't seem to work due to code expecting `=` at end of base64 endcoded value:

https://github.com/electron-userland/electron-builder/blob/e7179b57bdba192acfdb439c03099e6629e98f6a/packages/app-builder-lib/src/codeSign/codesign.ts#L22

Due to this, electron-builder tries to create a file named with the base64 value, resulting in `Error: ENAMETOOLONG: name too long`.

**Comment by mmaietta** [comment]
I'm not particularly familiar with this logic tbh. What would you suggest as a fix to it?

**Comment by acutus** [comment]
IIRC base64 encoding pads the end of encoded string with '=' sign if the encoded byte-array length is not divisible by 3, so an encoded byte-array with length divisible by 3 doesn't have '=' at the end.

Currently the linked `if`-statement assumes that base64 encoded certificate always ends with '='-sign.

I would think the best way to fix this would be to require a proper data-url (e.g. `data:application/x-pkcs12;base64,...`) or separate variable for the base64 encoded cert. This would obviously be a backwards incompatible change, but would provide a reliable way of knowing what the user intended to do with the variable. Maybe in the meantime one could try to maintain backwards compatibility by assuming also that all values longer than 1024 characters and not containing '://' are base64 encoded keys?

**Comment by mmaietta** [comment]
Hmmmm, my worry is that 2048 was chosen for a specific reason that I don't have historical context into. How would changing it to 1024 help?

**Comment by acutus** [comment]
I would wager 2048 is meant to distinguish URLs as 2048 used to be IE11 max URL length IIRC. Unfortunately base64 encoded certificate may be less than 2048 characters which means that the original if condition fails. Suggestion of shortening it to 1024 was just based on playing the odds that the URL to a downloadable cert is likely not that long, but I agree that it's likely not a good idea, especially if the more reliable way of actual data-URL is implemented.

As you suggested, adding the `data:application/x-pkcs12;base64,`-check to the if-condition and then removing it when using the value would be a good fix to this in my opinion (requires adding it to documentation as well ofc). Stylewise I'd add it as the first check to the condition, as it's the only reliable way to see if the user intended the variable to be a data-URL.

If there are other formats of certificates accepted, the condition should consider those as well. So not just `data:application/x-pkcs12;base64,`, but `data:<mime-type>;base64,` where <mime-type> matches the any accepted certificate mime-type.

**Comment by mmaietta** [comment]
Hmmm what if we just tested for `base64,` in the dataUrl and substring-ed after it? I have no idea what mime-types are supported, but at least we could cover it more unconditionally. Probably a breaking change but could be a worthwhile approach.

**Comment by mmaietta** [comment]
Sounds solid, we can add that logic. I think we should also add a unit test for this. I'll need to figure that out, maybe just reuse one of the current CSC_WIN_LINK vars and prepend the data-mime prefix. Since we're substringing it out of the CSC_LINK, it shouldn't affect the tests at all, but at least cover this use case?

**Comment by acutus** [comment]
I don't think you'll necessarily need an actual certificate in that base64-string after the prefix for the test, more important that you have some content which doesn't end with '=' simulating the base64-cert. But if you want to create some actual certificate, you could probably use openssl to generate a self-signed certificate and key and then use openssl to export those to a pkcs12 keystore and base64 encode that.

**Comment by mmaietta** [comment]
Our windows signing key used in the integration tests already doesn't end in a `=`
https://github.com/electron-userland/electron-builder/blob/master/test/src/helpers/codeSignData.ts#L6
That's why I want to recreate your environment directly

**Comment by stoefln** [comment]
Any solution for this? I think I might have run into this issue. See my stack trace:
```> electron-builder build --mac --arm64 --publish never --config electron-builder.json

  • electron-builder  version=24.4.0 os=21.6.0
  • loaded configuration  file=/Users/runner/work/myapp-studio/myapp-studio/electron-builder.json
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=12.2.3 appOutDir=dist/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v12.2.3/electron-v12.2.3-darwin-arm64.zip size=83 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v12.2.3/electron-v12.2.3-darwin-arm64.zip duration=1.252s
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  ⨯ ENAMETOOLONG: name too long, stat '/Users/runner/work/myapp-studio/myapp-studio/***'  failedTask=build stackTrace=Error: ENAMETOOLONG: name too long, stat '/Users/runner/work/myapp-studio/myapp-studio/***'
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at createKeychain (/Users/runner/work/myapp-studio/myapp-studio/node_modules/app-builder-lib/src/codeSign/macCodeSign.ts:195:21)
    at MacPackager.sign (/Users/runner/work/myapp-studio/myapp-studio/node_modules/app-builder-lib/src/macPackager.ts:217:27)
    at /Users/runner/work/myapp-studio/myapp-studio/node_modules/app-builder-lib/src/macPackager.ts:470:11```
