### ISSUE TITLE
Error with escape characters while executing sign command on MacOS, entitlements.mac.plist: cannot read entitlement data

### ISSUE THREAD

**Issue by kazeens** [electron-userland/electron-builder#7048]
Electron-builder 23.1.0

* **Electron-Builder Version**: 

* **Node Version v14.16.0**: 

* **Electron Version 19.0.8**:
* **Electron Type current**:

* **MacOS application**: 

Error while executing signing
entitlements.mac.plist: cannot read entitlement data

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/31125887/183248591-d263f847-0ab3-430d-b275-e8c1f1ae9ba4.png">

But if I execute this command manually in terminal(
codesign --sign 3D63F2B865A5B77336B5EEF9EC817F738163B994 --force --timestamp --options runtime --entitlements  ./src/desktop/entitlements.mac.plist /Users/nick/Documents/Medami/medami-backoffice/dist/mac/Medami.app/Contents/Frameworks/Electron\ Framework.framework/Versions/A/Resources/MainMenu.nib/keyedobjects-101300.nib
), correctly handling escape character in this place ( Frameworks/Electron Framework.framework -> Frameworks/Electron\ Framework.framework), it signings without any error

The certificate for signing is valid and correct, electron-builder successfully  finds it before executing command above

**Comment by mmaietta** [comment]
We use upstream package [electron-osx-sign](https://github.com/electron/osx-sign) for signing. I'm not sure if this is on our side
