### ISSUE TITLE
No clue how to sign a Windows app

### ISSUE THREAD

**Issue by robwilkerson** [electron-userland/electron-builder#705]
* **Version**: 2.11.0 (believe me, I know it's old)

* **Target**: Windows

I have an app that's been waiting on release for somewhere around a year now. We've been waiting on the client to get the appropriate developer certificates in place. Well, we _finally_ got those and I have no idea how to proceed with Windows. I know we're using a _very_ old version of `electron-builder`, but I'm hoping someone can push me through so I can get this release out the door and then start working on updates.

For OSX, even on my similarly old version of `electron-packager`, it was as simple as adding the `--osx-sign` flag to my build script (with the certificate details in my build's `config.json` file, of course). I have no idea how to proceed in order to sign a Windows app.

Since it's the installer I need to sign, it seems reasonable to assume that whatever I need to do needs to get done in my `electron-builder` command:

```
electron-builder \"dist/win/MyApp-win32-ia32\" --platform=win --out=dist/win/ --config=build/config.json
```

Since my version is so old, though, I can't even find a tag for it to pull up that version's README. Is there any chance someone can help me get this done so we can finally move this forward? "Desperation" is the word of the day.

In case it matters, here's my build's `config.json` file:

```javascript
{
  "osx" : {
    "title": "My App",
    "background": "./assets/osx/dmg_background.png",
    "icon": "./assets/osx/mount-myapp.icns",
    "icon-size": 96,
    "contents": [
      { "x": 345, "y": 150, "type": "link", "path": "/Applications" },
      { "x": 125, "y": 150, "type": "file" }
    ],
    "osx-sign": {
        "identity": "Developer ID Application: XXX"
    }
  },
  "win" : {
    "title" : "My App",
    "icon" : "./build/assets/win/My App.ico"
  }
}
```

Any push in the right direction would be very much appreciated.

**Comment by develar** [comment]
Version 2 uses old variant of NSIS and doesn't support code signing at all.

So, you can use use signtool directly. https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx

**Comment by develar** [comment]
I believe that upgrade to electron-builder will be easier and more robust :)
