### ISSUE TITLE
Security Advisory requires updating dependency to newest build of update-notifier

### ISSUE THREAD

**Issue by thewriteway** [electron-userland/electron-builder#7052]
* **Electron-Builder Version: "23.3.3"**: 

* **Node Version: "18.7.0"**: 

* **Electron-updater Version: "5.2.1"**: 

    electron-builder  >=5.6.1
        Depends on vulnerable versions of update-notifier
        node_modules/electron-builder

**Comment by thewriteway** [comment]
This is the current dependency listed "update-notifier": "^5.1.0"
The newest build of update-notifier is now on 6.0.2

**Comment by cjeonguk** [comment]
Same issue #7006. In my opinion, it seems to be the best solution to update `update-notifier`'s version. However, it was changed to [pure esm module](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) after [v6](https://github.com/yeoman/update-notifier/releases/tag/v6.0.0). I think it requires not only dependency updates but also some modifications if there is any confilct.

**Comment by mmaietta** [comment]
The pure ESM module screws up electron-builder, so I've found a potential replacement: simple-update-notifier. Going to see if that can work for us
