### ISSUE TITLE
CSC_KEY_PASSWORD not working with DigiCert EV hardware token on Windows builds

### ISSUE THREAD

**Issue by LieutenantKernel** [electron-userland/electron-builder#7055]
Electron-Builder Version: 22.10.5
Node Version: 12
Electron Version: 1.7.9
Electron Type (current, beta, nightly): current 2.23.3

Target: windows 10

electron-builder is not accepting CSC_KEY_PASSWORD set password. I am using a Digicert EV Hardware Token with Windows but the Safenet Auth Client windows keep popping up asking for the password. It happens at least 10 times, so I have to manually enter the password 10 times. I'm in the process of automated our builds so this is a huge blocker for me. Is there any resolution to this?

**Comment by dougw-bc** [comment]
had a similar problem - CSC_KEY_PASSWORD will not work for the windows hardware token.
You can within the safenet client, update the settings to allow only one password prompt per session, which makes the signing process much more tolerable. 

Docs: 
https://knowledge.digicert.com/content/dam/digicertknowledgebase/attachment/solution/SO28683/SafeNet%20Authentication%20Client_9.0_Users_Guide.pdf

Search that pdf for `Enabling Single Logon` for some assistance
