### ISSUE TITLE
AutoUpdater can‘t access feed url after cancel download 4/5 times

### ISSUE THREAD

**Issue by zhhan0012** [electron-userland/electron-builder#7056]
- Electron Builder Version: 22.10.5 / 23.3.3
- Electron Version: 13.1.4
- Electron Type (current, beta, nightly): 
- Electron Updater Version: 4.3.5 / 5.2.1
- target: Window10

### step

1. autoUpdater.setFeedURL(url)
2. check for update
3. autoUpdater.downloadUpdate(cancellationToken) to satrt download
4. cancellationToken.cancel to cancel before download completed
5. repeat steps 2-4, after 4/5 times, can't check update and downlaod, throw error
 
###  error
`[error] Error: Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)`
`Error in auto-updater. Error: net::ERR_HTTP2_PROTOCOL_ERROR`
### note
set disable-http2 and requestHeaders is invalid

**Comment by mmaietta** [comment]
Please try latest version of electron-builder and electron-updater. I can't support/debug older versions.

**Comment by zhhan0012** [comment]
> Please try latest version of electron-builder and electron-updater. I can't support/debug older versions.

I try with the  electron-builder(23.3.3) and electron-updater(5.2.1)，the problem still exists
