### ISSUE TITLE
cannot generate latest.linux.yml file 

### ISSUE THREAD

**Issue by LoveCodingOnGithub** [electron-userland/electron-builder#7064]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 14.17.4

* **Electron Version**: 12.1.0
* **Electron Type (current, beta, nightly)**:

* **Target**: ARM64 - Raspberry Pi

 I run `npm run build` , it built successfully , but the latest-linux.yml file did not generate in my folder.
This is the error mesage:
  • electron-builder  version=22.14.13 os=5.10.35-rt39-v8-catbot-mini+
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`

  • writing effective config  file=build/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=arm64 electron=12.1.0 appOutDir=build/linux-arm64-unpacked
  • building        target=snap arch=arm64 file=build/myStudio_3.3.3_arm64.snap
  • building        target=AppImage arch=arm64 file=build/myStudio-3.3.3-arm64.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-mystudio" does not exist
launch failed: Unable to find an image matching "core18". Please use `multipass find` for supported remotes and images.
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
  ⨯ exit status 2
github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr
    /Volumes/data/Documents/app-builder/pkg/util/exec.go:23
github.com/develar/app-builder/pkg/package-format/snap.buildWithoutTemplate
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:348
github.com/develar/app-builder/pkg/package-format/snap.Snap
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:200
github.com/develar/app-builder/pkg/package-format/snap.ConfigureCommand.func1
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:78
github.com/alecthomas/kingpin.(*actionMixin).applyActions
    /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
    /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
    /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
    /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
    /Volumes/data/Documents/app-builder/main.go:90
runtime.main
    /usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225
runtime.goexit
    /usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_arm64.s:1130 
  ⨯ /home/ubuntu/Desktop/myStudio/node_modules/app-builder-bin/linux/arm64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /home/ubuntu/Desktop/myStudio/node_modules/app-builder-bin/linux/arm64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/home/ubuntu/Desktop/myStudio/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myStudio@3.3.3 build: `node .electron-vue/build.js && electron-builder`

**Comment by LoveCodingOnGithub** [comment]
I tried the latest version of electron-builder , and got this error below:

• electron-builder  version=23.3.3 os=5.10.35-rt39-v8-catbot-mini+
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`

  • writing effective config  file=build/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=arm64 electron=12.1.0 appOutDir=build/linux-arm64-unpacked
  • building        target=snap arch=arm64 file=build/myStudio_3.3.3_arm64.snap
  • building        target=AppImage arch=arm64 file=build/myStudio-3.3.3-arm64.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-mystudio" does not exist
launch failed: Unable to find an image matching "core18". Please use `multipass find` for supported remotes and images.
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
  ⨯ exit status 2
[github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr](http://github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr)
    /Volumes/data/Documents/app-builder/pkg/util/exec.go:23
[github.com/develar/app-builder/pkg/package-format/snap.buildWithoutTemplate](http://github.com/develar/app-builder/pkg/package-format/snap.buildWithoutTemplate)
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:352
[github.com/develar/app-builder/pkg/package-format/snap.Snap](http://github.com/develar/app-builder/pkg/package-format/snap.Snap)
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:204
[github.com/develar/app-builder/pkg/package-format/snap.ConfigureCommand.func1](http://github.com/develar/app-builder/pkg/package-format/snap.ConfigureCommand.func1)
    /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:82
[github.com/alecthomas/kingpin.(*actionMixin).applyActions](http://github.com/alecthomas/kingpin.(*actionMixin).applyActions)
    /Volumes/data/go/pkg/mod/[github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28](http://github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28)
[github.com/alecthomas/kingpin.(*Application).applyActions](http://github.com/alecthomas/kingpin.(*Application).applyActions)
    /Volumes/data/go/pkg/mod/[github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557](http://github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557)
[github.com/alecthomas/kingpin.(*Application).execute](http://github.com/alecthomas/kingpin.(*Application).execute)
    /Volumes/data/go/pkg/mod/[github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390](http://github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390)
[github.com/alecthomas/kingpin.(*Application).Parse](http://github.com/alecthomas/kingpin.(*Application).Parse)
    /Volumes/data/go/pkg/mod/[github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222](http://github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222)
main.main
    /Volumes/data/Documents/app-builder/main.go:90
runtime.main
    /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
    /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1133 
  ⨯ /home/ubuntu/Desktop/myStudio/node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/ubuntu/Desktop/myStudio/node_modules/app-builder-bin/linux/arm64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/ubuntu/Desktop/myStudio/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! code ELIFECYCLE

**Comment by mmaietta** [comment]
Looks like you're hitting an issue with an upstream Go dependency https://github.com/develar/app-builder

There's not much I can do here other than advocate for either opening up a issue in that repo and/or to scour the internet for snap<->multipass<->core18.
