### ISSUE TITLE
github actions tag

### ISSUE THREAD

**Issue by nanamicat** [electron-userland/electron-builder#7066]
* **Electron-Builder Version**: 
23.3.3

* **Node Version**: 
v8.7.0

* **Electron Version**:20.0.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: all

in github actions, electron-builder can't get current tag.
`onTag` and `onTagOrDraft` publish policy not works.

```javascript
function getCiTag() {
    const tag = process.env.TRAVIS_TAG || process.env.APPVEYOR_REPO_TAG_NAME || process.env.CIRCLE_TAG || process.env.BITRISE_GIT_TAG || process.env.CI_BUILD_TAG || process.env.BITBUCKET_TAG;
    return tag != null && tag.length > 0 ? tag : null;
}
```

https://docs.github.com/en/actions/learn-github-actions/environment-variables
should check GITHUB_REF_TYPE == 'tag'  and return GITHUB_REF

**Comment by mmaietta** [comment]
Please open a PR adding that logic to the function :)
