### ISSUE TITLE
Cannot download differentially, fallback to full download: HttpError: 401

### ISSUE THREAD

**Issue by stoefln** [electron-userland/electron-builder#7070]
* **Electron-Builder Version**: 23.0.2

* **Node Version**: 14.18.1

* **Electron Version**: 12.2.3
* **Electron Type (current, beta, nightly)**: 4.6.5

* **Target**: Windows

This is the error messages which gets printed on windows:
```
Cannot download differentially, fallback to full download: HttpError: 401
Headers: {
  "x-github-backend": "Kubernetes",
  "x-github-request-id": "3176:2AEC:396699:13E6CC0:62FCC75F",
  "accept-ranges": "bytes",
  "date": "Wed, 17 Aug 2022 10:47:59 GMT",
  "via": "1.1 varnish",
  "x-served-by": "cache-vie6362-VIE",
  "x-cache": "MISS",
  "x-cache-hits": "0",
  "x-timer": "S1660733279.170218,VS0,VE101",
  "content-length": "0"
}
    at Object.p (C:\Program Files\Repeato\resources\app\static\index-bundle.js:26:115400)
    at ClientRequest.<anonymous> (C:\Program Files\Repeato\resources\app\static\index-bundle.js:26:139799)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:467:12)"
```
This is the release: https://github.com/stoefln/repeato-releases/releases/tag/v1.1.0

**Comment by mmaietta** [comment]
401 Unauthorized seems like a local configuration issue, not intrinsic to electron-builder. Are you adding the proper authentication credentials/token to your request?

**Comment by stoefln** [comment]
I think so. This is how I publish the app. Might the problem be that I am publishing the windows build via a Mac?
This is my script:
"publish-win": "cross-env GH_TOKEN=ghp_EpHxyz CSC_LINK=../Certificates/yyy-certificate.p12 CSC_KEY_PASSWORD=xyz DEBUG=electron-builder EP_GH_IGNORE_TIME=true electron-builder build --win --x64 --publish always",

**Comment by mmaietta** [comment]
`GH_TOKEN` is only used for publishing. It is not stored in the package. So if you're needing to update from any server requiring authentication, you'll need to use `autoUpdater.addAuthHeader(...)`

**Comment by stoefln** [comment]
I am not aware that I would need any auth for the server. Take a look here, it's public: https://github.com/stoefln/repeato-releases/releases/tag/v1.1.0

**Comment by nkartik01** [comment]
Facing this issue. Artifact is public and full download is happening
