### ISSUE TITLE
How to remove AppData for Win, Linux, Mac platforms when using MSI? 

### ISSUE THREAD

**Issue by vtebano13** [electron-userland/electron-builder#7076]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 14.17.0

* **Electron Version**:4.2.12
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows

I noticed that there was an old ticket on this but wondering why this option was never added for MSI.

I need to delete app user data for all supported platforms (Win and Mac), when application uninstalled. But only suitable things that I found was customize "nsis" (add flag "deleteAppDataOnUninstall": true). Its working for Windows with simple *.exe installer, but doesnt work with *.msi installer. 

How can I customize package.json that app data will be removed for Win and Mac?

**Comment by vtebano13** [comment]
Anyone?

**Comment by vtebano13** [comment]
I can't believe that I only one that has had this issue or request.

**Comment by gittare** [comment]
its good

**Comment by vtebano13** [comment]
What does "its good" mean?  Are you saying it works?  If so, then some detail how would be appreciated.
