### ISSUE TITLE
Prevent duplicate downloads of electron binary

### ISSUE THREAD

**Issue by KishanBagaria** [electron-userland/electron-builder#7079]
* **Electron-Builder Version**: 23.0.6

* **Node Version**: v16.15.1

electron-builder is downloading binaries to `~/Library/Caches/electron/electron-v19.0.13-darwin-arm64.zip`. When I install electron with yarn/npm/Electron Fiddle, it uses [@electron/get](https://www.npmjs.com/package/@electron/get) which downloads it to `~/Library/Caches/electron/3f6f49f831938723e7d8cd53e64df194ed958c819864fbce429d739e7d95cfea/electron-v19.0.13-darwin-arm64.zip`. Using @electron/get would let electron-builder avoid many duplicate downloads.

**Comment by mmaietta** [comment]
Unfortunately, we can't leverage `@electron/get` as [app-builder-bin](https://github.com/develar/app-builder) dependency is what is downloading and caching the electron binaries

**Comment by KishanBagaria** [comment]
Could we modify the directory path for download to include the hash? Should achieve the same thing.

**Comment by KishanBagaria** [comment]
If the main use case of app-builder has been electron, would it make sense to patch this in app-builder? (maybe with a flag)

**Comment by mmaietta** [comment]
Sorry, I don't manage that project, nor know Golang. 

But I just checked further, it seems you may be able to use an env var already, but you'll need to manually provide the full cache path incl. of the hash.
https://github.com/develar/app-builder/blob/7e5f3301fa7d517105276e7916db19d509eaa517/pkg/electron/electronDownloader.go#L62
Set `ELECTRON_CACHE` env var

**Comment by KishanBagaria** [comment]
We could set `process.env.ELECTRON_CACHE` for all electron-builder users and save them the extra download time?

**Comment by mmaietta** [comment]
Why does this matter for users?
Electron downloader is for developers pre-packaging the app.

**Comment by KishanBagaria** [comment]
Indeed, a general patch could be applied for all developers using electron-builder to save them the time?
