### ISSUE TITLE
Can I control the localization files

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-builder#708]
- **Version**: 5.35

- **Target**:  MAS

The electron zip file contains 100s of language.lproj folders, and this causes the mac app store to list the app as being available in all of these languages.
1. Would electron build be interested in adding code to allow me to choose which of these folders to leave and which to remove?
2. Or is these a hook that I can run some code between the files being prepared and before they are packaged and code signed? That way I could write project specific code to clean up these folders, and potentially make other changes, this could be a more generic solution

**Comment by develar** [comment]
You can use [afterPack](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-afterPack), but if you can write code, it is better to prepare PR instead of hack on your side.

> Would electron build be interested in adding code to allow me to choose which of these folders to leave and which to remove?

Yes, `files` currently affects only app code, not electron distribution. Maybe `electronFiles`?

**Comment by develar** [comment]
Do you know, for what so many empty `language.lproj` directories? Maybe we can just leave `en.lproj` and `electronFiles` will allow to add another if need?

**Comment by develar** [comment]
https://github.com/electron/electron/issues/2484

**Comment by mcfedr** [comment]
For the moment I am adding quick fix to my gulp task. I'm going to put it here for reference. If I find some time ill try and make a pull request.

    let languages = ['en'];
    electronBuilder.build({
        platform: getElectronPlatforms(),
        devMetadata: {
            build: {
                afterPack: ({appOutDir, options}) => {
                    return new Promise((res, rej) => {
                        console.log('afterPack', appOutDir, options.platformPackager.platform);
                        if (options.platformPackager.platform.name === 'mac') {
                            let glob = require('glob'),
                                del = require('del');
                            glob(`${appOutDir}/${options.appInfo.name}.app/Contents/Resources/!(${languages.join('|')}).lproj`, (err, files) => {
                                if (err) return rej(err);
                                del(files).then(res, rej);
                            });
                        } else {
                            res();
                        }
                    });
                }
            }
        }
    })

**Comment by develar** [comment]
Do you like `electronFiles` solution?

**Comment by mcfedr** [comment]
I'd probably be more inclined to add a list of languages as a setting, that's why I put `languages` as a variable in that code. 

I think it might be hard to get electron to remove the default ones.

**Comment by fab1an** [comment]
Is there a way of doing this without afterpack? I'm not using the programmatic api, and I don't want to start using it because of that (I run my build using gradle/kotlin, so easy javascript support there).

**Comment by develar** [comment]
@fab1an for what?

**Comment by fab1an** [comment]
Never mind, I just added a `.js`-file to my build for now.

**Comment by develar** [comment]
Reopened — requested by 2 VIP users is enough to implement.

**Comment by develar** [comment]
Implemented. `mac.electronLanguages` Set to array of lang codes. e.g. `["en", "bn"]`

**Comment by perryy** [comment]
I have figured out, that I have to use pt_BR, zh_TW and so on. Sorry for bothering you

**Comment by fabiospampinato** [comment]
> Reopened — requested by 2 VIP users is enough to implement.

@develar Are VIP users still a thing? If yes how does one become a VIP user?

**Comment by linonetwo** [comment]
I have this set:

```js
    "packagerConfig": {
        "icon": "build-resources/icon.icns",
        "asar": {
          "unpack": "**/.webpack/main/0.index.worker.js"
        },
        "extraResource": [
          "localization",
          "template/wiki"
        ],
        "mac": {
          "category": "productivity",
          "target": "dmg",
          "icon": "build-resources/icon.icns",
          "electronLanguages": [
            "zh_CN",
            "en",
            "ja"
          ]
        }
      },
```

But there are still lots of lproj files

![Screen Shot 2021-05-04 at 01 43 22](https://user-images.githubusercontent.com/3746270/116911945-1e57f300-ac7a-11eb-97cc-532059b46200.png)

**Comment by pravichandran15** [comment]
electronLanguagues with list of array / null is working fine with **electron-builder : 23.3.3**

**Comment by alon42** [comment]
Have the same problem:
"electron-builder": "24.13.3",

it seems like a bug in electron builder

**Comment by jamierpond** [comment]
also having this issue

**Comment by balazserdeszlogmein** [comment]
This doesn't work as of 26.0.12
