### ISSUE TITLE
Windows: quitAndInstall() quits the application but fails to launch installation process

### ISSUE THREAD

**Issue by acutus** [electron-userland/electron-builder#7084]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.16.0

* **Electron Version**: 19.0.10
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

We are seeing an issue where `quitAndInstall()` quits the application but fails to install in one go on windows. Works fine on Mac which leads me to think the issue is within NsisUpdater.

Logs below:

```
[2022-08-23 13:02:28.518] [info] installing update ...
[2022-08-23 13:02:28.518] [info] Install on explicit quitAndInstall
[2022-08-23 13:02:28.519] [info] Install: isSilent: false, isForceRunAfter: true
[2022-08-23 13:02:28.519] [info] isAdminRightsRequired is set to true, run installer using elevate.exe
[2022-08-23 13:02:28.590] [info] Update installer has already been triggered. Quitting application.
```
After this, the app quits but doesn't launch the installation process. Next startup launches the old version and installation process is then launched and completes successfully after manually quitting the application.

Based on logs and a quick look at source-code, seems like `NsisUpdater::callUsingElevation()` fails silently somehow.

https://github.com/electron-userland/electron-builder/blob/94982619c1c2131918171ae61dc676c77d6d769f/packages/electron-updater/src/NsisUpdater.ts#L135

**Comment by acutus** [comment]
This and #7058 could be related

**Comment by mmaietta** [comment]
Hmmm I'm wondering if it should be `await callUsingElevation` (with relevant changes to the closure to return a promise) to validate that the spawned process has returned a `pid`. `callUsingElevation` already calls `dispatchError`, but it's possible that the app has already quit by that point without spawning the installer.

**Comment by xztl** [comment]
+1

**Comment by lguibr** [comment]
+1

**Comment by odusseys** [comment]
same issue here - windows only. Installer starts, app quits, and then the app is uninstalled (desktop shortcuts remain, broken) and nothing is installed after

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by mmaietta** [comment]
So it appears that `doInstall` is expected to be synchronous, even though the spawn call is written as async. I still have a strong hunch that the process is not being spawned in time before the function returns `true` and exits the app.
Not sure how to proceed without a very large refactor AFAICT
Even still, there's even a comment that it MUST be sync, and I have no idea why so I don't really want to touch this code
https://github.com/electron-userland/electron-builder/blob/d71a5790a94cd56b6e033b656b4892ec31f14b9d/packages/electron-updater/src/BaseUpdater.ts#L38-L39

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by aymengraoui** [comment]
same thig issue

    - "electron-updater": "5.3.0",
    - "electron": "^23.2.1",
    - "electron-builder": "^23.6.0"
   
 windows: app quits, Installer starts, and then the app is uninstalled (desktop shortcuts remain, broken) and nothing is installed after
 
 manually installing the app downloaded by the electron-updater work just fine.

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by aymengraoui** [comment]
if anyone finds this i had this 

problem: 

windows app quits, Installer starts, and then the app is uninstalled (desktop shortcuts remain, broken) and nothing is installed after

my solution: 

add the version in the name of the app "artifactName": "${productName}-${version}.${ext}" this solved my problem for some reason

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by dafatov** [comment]
> if anyone finds this i had this
> 
> problem:
> 
> windows app quits, Installer starts, and then the app is uninstalled (desktop shortcuts remain, broken) and nothing is installed after
> 
> my solution:
> 
> add the version in the name of the app "artifactName": "${productName}-${version}.${ext}" this solved my problem for some reason

If anyone else has been looking for how to solve the problem for days. This comment saved me. Thank you. In general, it is worth adding this to the documentation

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by popod** [comment]
This is still an issue..

@aymengraoui workaround can fix it.. so is it not possible to fix the original bug @mmaietta ?

Updater problems are really bad user experiences..

Thank you.

**Comment by mmaietta** [comment]
I don't know... Did anyone ever try this patch to see if it resolved the issue for them?
https://github.com/electron-userland/electron-builder/issues/7084#issuecomment-1256509406

**Comment by popod** [comment]
Unfortunately I don't have the time right now, but I'll try as soon as I can and let you know.

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！

**Comment by elderdog** [comment]
If anyone encountered the same issue and happened to use a `customWelcomePage`, this https://github.com/electron-userland/electron-builder/issues/8760#issuecomment-2579646554 might help.

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！
