### ISSUE TITLE
Issues on windows update

### ISSUE THREAD

**Issue by qishibo** [electron-userland/electron-builder#7086]
* **Electron-Builder Version**: 22.14.5
* Electron-updater Version: 4.6.5

* **Node Version**: all

* **Electron Version**: 12.2.3
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis

When the nsis (exe) package is installed, the user runs with **administrator** privileges and installs it for **all users**, then when it is updated, if app is run by a **common** user(not admin), it will ask for administrator privileges during uninstall, but It will **fail** when reinstalling and the folder is empty, it should be caused by non-administrator permissions. 

Does anyone know how to solve this problem? Or how can I ask administrator privileges again when updating after opening it by no-admin?

This is my config:
```json
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false,
      "menuCategory": true,
      "allowElevation": false
    }
```

**Comment by biaomingzhong** [comment]
same here

**Comment by byzhangkui** [comment]
I encountered the same problem. When performing the uninstallation process, the installation package will elevate privileges if the installation mode is per-machine and does not start with administrator permissions.  

My solution is to do the same thing when the installation package starts. I create a custom script to implement `customInit` marco like this:

```
!macro customInit
  ${if} $hasPerMachineInstallation == "1"
  ${andIf} ${Silent}
    ${ifNot} ${UAC_IsAdmin}
      !insertmacro UAC_RunElevated
      ${Switch} $0
        ${Case} 0
          ${Break}
        ${Case} 1223 ;user aborted
          ${Break}
        ${Default}
          MessageBox mb_IconStop|mb_TopMost|mb_SetForeground "Unable to elevate, error $0"
          ${Break}
      ${EndSwitch}
      Quit
    ${endIf}
  ${endIf}
!macroend
```
The usage instructions of NSIS macro can be found at [custom-nsis-script](https://www.electron.build/configuration/nsis.html#custom-nsis-script).
