### ISSUE TITLE
Cannot sign windows binary in electronuserland/builder:wine because libcrypto.so.1.1 doesn't exist

### ISSUE THREAD

**Issue by asmsuechan** [electron-userland/electron-builder#7092]
* **Electron-Builder Version**: 23.4.0

* **Node Version**: 16.13.1

* **Electron Version**: 16.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

Hi, developers. My electron build fails with the following error after electronuserland/builder:wine is updated.

```
/root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/linux/osslsigncode: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

My situation: I build an electron app inside electronuserland/builder:wine container.

I investigated the new container and found that the version of libcrypto isn't 1.1, it's 3.

```
root@1c6f31ac3c40:/project# find / | grep libcrypto
/usr/lib/x86_64-linux-gnu/libcrypto.so.3
/usr/lib/x86_64-linux-gnu/pkgconfig/libcrypto.pc
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/lib/x86_64-linux-gnu/libcrypto.so
/usr/lib/i386-linux-gnu/libcrypto.so.3
```

I guess that's because of container image update to Ubuntu 22.04 in this [commit](https://github.com/electron-userland/electron-builder/commit/03cc9b96e0be07ef3450e3992eafcb7fe903a853).

Note: I use `electronuserland/builder:wine-chrome-05.21` to avoid this error.

Do you plan to make electron-builder use OpenSSL 3.0 instead of 1.1? Or, are there some smart answers to solve my problem?

Thank you.

**Edited: People who need a workaround for now**

* Use `electronuserland/builder:wine-chrome-05.21` instead of `electronuserland/builder:wine`
* Update GPG key by `wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -`

**Comment by NeuralMayu** [comment]
Please ask how you use electronuserland/builder:wine-chrome-05.21 to avoid this error ？

**Comment by asmsuechan** [comment]
@NeuralMayu I changed the image from `electronuserland/builder:wine` to `electronuserland/builder:wine-chrome-05.21` and updated GPG key by `wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -`. Other flows are same.

**Comment by NeuralMayu** [comment]
> @NeuralMayu I changed the image from `electronuserland/builder:wine` to `electronuserland/builder:wine-chrome-05.21` and updated GPG key by `wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -`. Other flows are same.

the electronuserland/builder is electron-userland/electron-builder ?

**Comment by asmsuechan** [comment]
No, it's not. As this page https://hub.docker.com/r/electronuserland/builder/tags shows, the container is `electronuserland/builder`.

**Comment by acutus** [comment]
Ran into this as well. Thank you @asmsuechan for investigating and providing a workaround.

**Comment by Muukuro** [comment]
Yup, same issue here. I managed to work around it by using `electronuserland/builder:14-wine-05.22` instead of `electronuserland/builder:wine` (thanks @asmsuechan!)
