### ISSUE TITLE
sha512 checksum mismatch, expected xxx, got xxx (help wanted)

### ISSUE THREAD

**Issue by xxxace** [electron-userland/electron-builder#7096]
* **Electron-Builder Version**: 23.3.3
* **Electron-Updater Version**: 5.2.1

* **Node Version**: 14.18.0

* **Electron Version**: 20.0.2
* **Electron Type (current, beta, nightly)**:

* **Target**:  windows

```
{
  appId: "com.zy.ace.tc",
  asar: true,
  directories: {
    output: "release/${version}",
  },
  files: ["dist"],
  mac: {
    artifactName: "${productName}_${version}.${ext}",
    target: ["dmg"],
  },
  win: {
    icon: "./public/favicon.ico",
    target: [
      {
        target: "nsis",
        arch: ["x64"],
      },
    ],
    artifactName: "${productName}_${version}.${ext}",
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
    shortcutName: ${productName},
    installerIcon: "./public/favicon.ico",
    uninstallerIcon: "./public/favicon.ico",
    installerHeaderIcon: "./public/favicon.ico",
  },
  publish: [
    {
      provider: "generic",
      url: "http://xxx.xxx.xxx",
    },
  ],
}
```

![image](https://user-images.githubusercontent.com/60084325/187013707-cc3ba37d-59ea-4a7c-b144-bb0ef9c93513.png)

whatever i change the local version it always got :
RsYJoPGNN39siDFgmZSqpi/W7HYLTLmsYwGjY9CI6BSKU6+iymaKkHURAvWOlvT//b6Gt8ehYBFRoRj2mE3XaA==

**Comment by xxxace** [comment]
Ooops! it's the shortcutName made me always got the same sha512.

**Comment by xiaoyang168** [comment]
Hello, can you tell me how to solve it

**Comment by Sdqumar** [comment]
have same issue, any help is appreciated
