### ISSUE TITLE
CSC_LINK not picked up?

### ISSUE THREAD

**Issue by Vj3k0** [electron-userland/electron-builder#710]
* **Version**: 6.1.0

* **Target**: Mac

I have a project on which I had electron-builder se to v5.10. I've decided that it's time to update it, but when I did I got following message:

> Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing     

The thing is that its been working fine on 5.10, and it found my env var CSC_LINK. Tracking it down, I've found out that it breaks for me in 5.11 (I suppose that it has to do with [this commit](https://github.com/electron-userland/electron-builder/commit/de01c6dd)). I looked at wiki, but I don't see there were major changes for that and it should work.

Note: I have base64 on CSC_LINK.

Any ideas?

**Comment by develar** [comment]
Please enable debug: set env `DEBUG=electron-builder`

**Comment by Vj3k0** [comment]
Nothing fancy there. Is something like this what you need?

```
  electron-builder npm (72515) exited with code 0 +1s                                                                      
Packaging for platform darwin x64 using electron 1.3.4 to dist/mac                                                         
                                                                                                                           
  electron-builder Executing security find-identity -v /var/folders/94/2pwtm33s68l1httjp185pf8w0000gp/T/electron-builder-11
b41-156d71fc476-1/0.keychain +2s                                                                                           
  electron-builder Executing security find-identity -v -p codesigning /var/folders/94/2pwtm33s68l1httjp185pf8w0000gp/T/elec
tron-builder-11b41-156d71fc476-1/0.keychain +7ms                                                                           
Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electr
on-userland/electron-builder/wiki/Code-Signing                                                                             
Creating DMG                                                                                                               
Creating MacOS zip                                                                                                         
```

**Comment by develar** [comment]
Do you use `CSC_LINK` on dev or CI machine? Hmm... it seems on CI (custom keychain is used).

Yes, error message is not correct — `CSC_LINK` is specified, but no valid identities.

Do you use Apple cert? Does your cert contains both cert and private key?

**Comment by develar** [comment]
We have tests for this functionality (yes, as base64), so, it is very strange for me. Is it possible to share project, so, I can try?

**Comment by Vj3k0** [comment]
Unfortunately I cannot share the project. It is actually an Apple cert, which is used both on CI and on my local machine. As I said, everything works on my local machine with 5.10, but on newer versions, I'm getting this message. Same certificate, same environment, same env variable, same terminal window.

**Comment by develar** [comment]
@Vj3k0 Ok, I will try to investigate.

**Comment by Vj3k0** [comment]
Thank you very much Vladimir. If I can be of help, let me know.

**Comment by develar** [comment]
Cannot reproduce. Do you use Travis? Do you use programmatic API or CLI?

**Comment by Vj3k0** [comment]
I don't use Travis, and I'm trying to build it locally on my machine through CLI. I'm running simple:

```
node_modules/.bin/build -m
```

So, on your machine, CSC_LINK in base64 gets picked up?

**Comment by develar** [comment]
> So, on your machine, CSC_LINK in base64 gets picked up?

Yes. Local or CI machine. I am afraid, that previously it works for you on local machine only because identity from your login.keychain was used. Please try to reexport your cert&private key. Does it work on CI?

**Comment by Vj3k0** [comment]
After looking into electron-builder, I saw that thing falls apart for me in `codeSign.js` in `_findIdentify` function. Since I have Apple certificate set on CSC_LINK, it is found in `appleCertificatePrefixes` and it avoids it so it return `null`.

Apple certificates are not supported? Mine contains "3rd Party Mac Developer Application:" string.

**Comment by develar** [comment]
> 3rd Party Mac Developer Application

This certificate is not valid to sign mac application, please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos Must be `Developer ID Application:`

**Comment by Vj3k0** [comment]
Thanks Vladimir, I'll close this issue then. I can't change it right now, but I will in near future.
