### ISSUE TITLE
Snap.yaml has invalid fields

### ISSUE THREAD

**Issue by MikeJerred** [electron-userland/electron-builder#7104]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.14.2

* **Electron Version**: 19.0.14
* **Electron Type (current, beta, nightly)**: current

* **Target**: snap

Currently app-builder-lib copies all the fields specified in `snapcraft.yaml` into `meta/snap.yaml`, but there are some fields that shouldn't be copied (see https://code.launchpad.net/~logicoversnacks/review-tools/+git/review-tools/+merge/429123). Including any of these invalid fields will cause the snap to fail validation and require manual review.

A list of fields that should be stripped out:

```
compression
contact
donation
issues
source-code
website
```

I would make a pull request but I am not sure what app-builder-lib is doing when `this.isUseTemplateApp` is false, it seems to make `snap/snapcraft.yaml` instead of `meta/snap.yaml`

**Comment by mmaietta** [comment]
Hi @MikeJerred , I'm honestly not familiar with the implementation of snap within electron-builder. Would be happy to accept a PR for this change.

**Comment by MikeJerred** [comment]
I opened a PR: https://github.com/electron-userland/electron-builder/pull/7110
It looks like when `isUseTemplateApp` is false then the snap cli tool is used which should create the `snap.yaml` correctly, so I have only stripped the fields out when `isUseTemplateApp == true`
