### ISSUE TITLE
Uninstaller fails to see app is already closed

### ISSUE THREAD

**Issue by NikhilNarayana** [electron-userland/electron-builder#7114]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 16.13.1

* **Electron Version**: 19.0.11
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

The current version of my app fails to uninstall when upgrading because the uninstaller gets stuck thinking the app isn't closed even though it doesn't show up in Task Manager's details tab.

After a bit of finagling I managed to find that the new installer runs `old-uninstaller.exe /KEEP_APP_DATA /allusers --updated _?=C:\Program Files\<app name>`, but fails due to the mentioned issue. Removing `--updated _?=C:\Program Files\<app name>` from that command gets the uninstaller to complete , but that doesn't seem like the right solution nor does there seem to be an easy way to actually remove that argument from the uninstall call.

One of the goals of the update to my app is to upgrade to a newer electron-builder, where i've noticed this issue doesn't exist. I appreciate any insight I can get into this issue, thanks.

**Comment by mmaietta** [comment]
Hmmm. Not sure I can help you here... If you're unable to update the app due to a legacy version of electron-updater, then no matter of changes to the current electron-builder/updater will resolve that.

**Comment by NikhilNarayana** [comment]
> Hmmm. Not sure I can help you here... If you're unable to update the app due to a legacy version of electron-updater, then no matter of changes to the current electron-builder/updater will resolve that.

I have found a patch that isn't ideal but does do the trick based on what I mentioned regarding `_?=C:\Program Files\<app name>`. I definitely don't consider this to be a true solution but it might have to do to ensure i can migrate my users.

https://github.com/project-slippi/slippi-launcher/commit/04fc7af34ee9074f76db8f3d40aed36bf4114b98
