### ISSUE TITLE
NSIS perMachine fails if UAC prompt is enabled

### ISSUE THREAD

**Issue by cwillisf** [electron-userland/electron-builder#712]
* **Version**: 6.3.0

* **Target**: NSIS

[This call to exec](https://github.com/electron-userland/electron-builder/blob/v6.3.0/src/targets/nsis.ts#L170) fails with "Error: spawn UNKNOWN" when `perMachine` is true and UAC prompts are enabled.

Workarounds:
- Disable UAC prompts
- Run from an elevated command prompt

Here's a partial log of the failure, running with `DEBUG=*`. I'd be happy to provide more logging output if it would help -- just let me know :)
[NSIS-perMachine-UAC-error.txt](https://github.com/electron-userland/electron-builder/files/443969/NSIS-perMachine-UAC-error.txt)

**Comment by develar** [comment]
Hmm... Ha! You set `perMachine` to `true` and we set `RequestExecutionLevel` to `admin` But! To build uninstaller we don't need admin rights.
