### ISSUE TITLE
**Asset validation failed (90236) icon required missing** 

### ISSUE THREAD

**Issue by html5technologies786** [electron-userland/electron-builder#7123]
**Asset validation failed (90236) icon required missing.** 

### Electron-builder
22.14.3

**Electron: 8.5.5**
### Node Version: 
**14.18.3:**

### platform
*** MAC OS :** 

*** Target :**
MAS :pkg installer for mac app store

I am trying to create mas pkg installer for mac app store, all things are working fine, but when i am trying to upload to store via Transporter and during verification , it says, asset validation failed. Icon missing, though I have .icns extension icon and its placed in resources only this issue I am seeing. can anybody let me know how can fix this. 

here my mac and mas configuration of package.json

`"build": {
  "appId": "com.****.****",
  "afterSign": "./resources/notarize.js",
  "mac": {
   "icon": "icon.icns",
   "hardenedRuntime": true,
   "entitlements": "./resources/entitlements.mac.plist",
   "entitlementsInherit": "./resources/entitlements.mac.plist",
   "target": ["dmg", "mas"]
  },
  "mas": {
   "type": "distribution",
   "hardenedRuntime": false,
   "entitlements": "resources/entitlements.mas.plist",
   "entitlementsInherit": "resources/entitlements.mas.inherit.plist",
   "provisioningProfile": "resources/magnifhire2022.provisionprofile",
   "asarUnpack": []
  },
  "files": [],
  "directories": {
   "output": "release",
   "buildResources": "resources"
  }
  }

![issueValidationFailed](https://user-images.githubusercontent.com/49685385/188549460-72e894cc-77b8-4093-8afc-397ef96a25bf.png)
`

**Comment by mmaietta** [comment]
Hmmm Have you tried placing `icon` within the `mas` config?
My other best guess is that the icns could need to be regenerated if it's not containing the correct image asset sizes embedded with it.

**Comment by html5technologies786** [comment]
I am actually replaced icon in mas too, when I explored Content, I saw in resources icon.icns file is placed. but when pkg installer file is uploaded it says, icon is missing . For regeneration I put icon.png with 512*512 by uisng iconutil -c icns icon.iconse. its generated icon.icns file.

**Comment by mmaietta** [comment]
You also need a 1024x1024 icon (512x512@2x)

**Comment by html5technologies786** [comment]
In icon.icns ? yes, I place this too, but when i generate icns, it only created icon.icns, 
Where do I place 1024x1024  ?

**Comment by mmaietta** [comment]
In the icns file

**Comment by geoff8888** [comment]
I am having the same problem.  Where do you place the icons?  and what filename?  Do you need to create plist for this?
