### ISSUE TITLE
How can I exclude specific module getting part of build for MacOS only using electron-builder?

### ISSUE THREAD

**Issue by alokmahor** [electron-userland/electron-builder#7128]
I have [electron][1] application which is targated for [Windows OS][2] and [MacOS][3].  

I am using [electron-builder][4] for generating build.

There is one specific module which is getting used only in Windows OS. That module is listed in `dependencies` section of `package.json`.  

How can I exclude that specific module in case of MacOS while generating build. Because in MacOS that module is not getting used anything. If I can exclude that module than I can save space in MacOS buils size.

electron-builder have [file-patterns][5] but that we can not set per target.

  [1]: https://www.electronjs.org/
  [2]: https://en.wikipedia.org/wiki/Microsoft_Windows
  [3]: https://en.wikipedia.org/wiki/MacOS
  [4]: https://www.electron.build/
  [5]: https://www.electron.build/file-patterns

**Comment by mmaietta** [comment]
There isn't a possibility to do that. `install-app-deps` only accepts `platform` and `arch` args. It is run by upstream dependency `app-builder` IIRC
