### ISSUE TITLE
Signature does not contain any timestamp Digicert

### ISSUE THREAD

**Issue by creaz35** [electron-userland/electron-builder#7134]
* **Electron-Builder Version**: 20.8.1

* **Node Version**: v16.15.1

* **Electron Version**: 19.0.1
* **Electron Type (current, beta, nightly)**: Current

After running npm run dist:win and check the signature in Digicert Certificate Utility Tool i'm getting "the signature does not contain any timestamp". 

`    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ],
      "icon": "./public/icons/png/256x256.png",
      "certificateSubjectName": "XXX",
      "signingHashAlgorithms": [
        "sha256"
      ],
      "publisherName": "XXX",
      "signAndEditExecutable": true,
      "rfc3161TimeStampServer": "http://timestamp.digicert.com",
      "certificatePassword": "XXX"
    }`

**Comment by antt0n** [comment]
Hello

I have the same problem with lastest release.
