### ISSUE TITLE
How do I build a universal bundle on MacOS

### ISSUE THREAD

**Issue by jrohlandt** [electron-userland/electron-builder#7135]
* **Electron-Builder Version**: 
v23.3.3

* **Node Version**: 
v16.17

* **Electron Version**:
18

* **Target**: 
MacOS universal (arm64 and x64

This my build command:
```
"release:mac": "electron-builder -m --publish 'onTagOrDraft'",
```

On an Intel based mac this produces a universal bundle that can be installed on either Intel or M1 Macs.
But on a M1 mac it creates an arm64 bundle.

How do I modify it to create a universal bundle when running it on an M1 mac?

Sorry for posting here but I can't get an answer anywhere and I can't figure out what I need to do from the electron.build documentation site either.

**Comment by mmaietta** [comment]
https://github.com/electron-userland/electron-builder/issues/5689
