### ISSUE TITLE
hdiutil failures block building macOS versions

### ISSUE THREAD

**Issue by Nokel81** [electron-userland/electron-builder#7137]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.11.59

* **Electron Version**: 19.0.16
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS 11

Similar to https://github.com/electron-userland/electron-builder/issues/4606

While running on github actions we very often run into the following error:

```
Exit code: 16. Command failed: hdiutil detach -force /dev/disk2
hdiutil: couldn't eject "disk2" - Resource busy

hdiutil: couldn't eject "disk2" - Resource busy
  failedTask=build stackTrace=Error: Exit code: 16. Command failed: hdiutil detach -force /dev/disk2
hdiutil: couldn't eject "disk2" - Resource busy
```

If I rerun it then it generally passes but that wastes times.

**Comment by mmaietta** [comment]
I don't think we have a way for determining if the resource is still busy, we simply can't move forward with the rest of the build process.
We already retry ejecting the dmg 3 times.

**Comment by roryabraham** [comment]
We also encountered this in electron-builder 23.5.0

**Comment by roryabraham** [comment]
Also experiencing the same thing in 24.4.0

**Comment by roryabraham** [comment]
Created https://github.com/electron-userland/electron-builder/pull/7600 to attempt to resolve this issue.

**Comment by mmaietta** [comment]
Released 24.5.0

**Comment by doyeonOh** [comment]
electron: 26.6.2
electron-builder: 24.9.4
---

I had the same error, so I searched all the related information and searched for a week.

And I solved it in the following way.
- After booting into Mac safe mode, the build was completed normally.
(My case is suspected to be either antivirus or Office Keeper)

Hope it helps someone...

**Comment by xngln24** [comment]
This [https://github.com/electron-userland/electron-builder/issues/5431#issuecomment-1566203180](url) worked for me
