### ISSUE TITLE
Building a second Windows release gives a task was cancelled error

### ISSUE THREAD

**Issue by tom-james-watson** [electron-userland/electron-builder#714]
* **6.3.1**: 

* **Squirrel.Windows**: 

I successfully built a first windows release and create a release on my github repository with the relevant build files attached. I have a squirrel server that is correctly finding these builds and I can install my application from the packages perfectly.

When I try to build a new version of the app, the build errors out with the below error. I am not entirely sure what the actual error is here. What is this /RELEASES url? Is that valid?

Here is the relevant config from my package.json:
```
"build": {
  "appId": "<redacted>",
  "category": "public.app-category.utilities",
  "asar": false,
  "win": {
    "iconUrl": "<redacted>",
    "remoteReleases": "https://github.com/tom-james-watson/artpip-app",
    "remoteToken": "<redacted>"
  }
},
"directories": {
  "output": "releases"
},
```

Any pointers? Let me know if you need more info.

Error:
```
Building Squirrel.Windows installer

Error: mono exited with code 255
Output:
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES

Error output:
Attempting to sync URL as remote RELEASES folder
Failed to sync URL as GitHub repo: A task was canceled.
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: 404 (Not Found)
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () <0x1138b6200 + 0x000f0> in <filename unknown>:0
  at System.Net.Http.HttpClient+<GetStringAsync>c__async6.MoveNext () <0x1138b48b0 + 0x00277> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
......
```

**Comment by develar** [comment]
> https://github.com/tom-james-watson/artpip-app"

404 Not Found. Is it correct URL?

**Comment by tom-james-watson** [comment]
Yeah, it's a private repository.

**Comment by develar** [comment]
@tom-james-watson In this case please specify `remoteToken` (where `remoteReleases` defined, `build.win.remoteToken`) — https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by develar** [comment]
Hmm... it seems you in any case already specified `GH_TOKEN`.

**Comment by develar** [comment]
`GH_TOKEN` now reused for Squirrel.Windows sync releases.

**Comment by tom-james-watson** [comment]
Hello - thank you for your very quick fix! That has cleared that error.

However, I am now actually receiving the same error as https://github.com/electron-userland/electron-builder/issues/713

Please see error stack below

```
Error: Command failed: mono /Users/tomw/.cache/Squirrel.Windows/Squirrel.Windows-1.4.4/Update-Mono.exe --releasify /Users/tomw/git/artpip-app/releases/win/artpip-0.0.12-full.nupkg -
-releaseDir /Users/tomw/git/artpip-app/releases/win
2016-09-01 10:24:36> Unhandled exception: System.IO.FileNotFoundException: The base package release does not exist
File name: '/Users/tomw/git/artpip-app/releases/win/artpip-0.0.11-full.nupkg'
```

**Comment by tom-james-watson** [comment]
Just to be clear - that file does exist before running the command, but it seems to get deleted during the process.

**Comment by develar** [comment]
Strange... works for me. Is `artpip-0.0.11-full.nupkg` available on github?

**Comment by develar** [comment]
We DO REMOVE old artifacts to be sure that delta will be computed using correct artifact.

**Comment by tom-james-watson** [comment]
It is yeah, actually I presume that the problem is that it is a private respository. Is it using my `remoteToken` correctly when trying to fetch the files?

**Comment by develar** [comment]
> Is it using my remoteToken correctly when trying to fetch the files?

I don't know, it is Squirrel.Windows and I suppose it maybe buggy.

**Comment by develar** [comment]
To be sure — artpip-0.0.11-full.nupkg available on github?

**Comment by tom-james-watson** [comment]
Yeah, see below.

The file is available at https://github.com/tom-james-watson/artpip-app/releases/download/v0.0.11/artpip-0.0.11-full.nupkg

However, being a private repository it needs to use my `remoteToken` to be able to access this file. My squirrel server (which is configured with my token) can download these files fine.

![image](https://cloud.githubusercontent.com/assets/3852719/18164587/953ab5d0-7038-11e6-85f9-c26d3c1cbdde.png)

**Comment by develar** [comment]
Do you see `artpip-0.0.11-full.nupkg` file in the output directory during build? Please set env `DEBUG=electron-builder`

**Comment by develar** [comment]
Please try to remove output directory completely and build again.

**Comment by tom-james-watson** [comment]
Hello - removing my release directory and rebuilding everything worked once. However, trying again a few hours later to create a new version, I am getting the same error as earlier. I have ensured that I am DEFINITELY on 6.3.3. Any idea?

Here's the output:

```
Building Squirrel.Windows installer

  electron-builder Found existing Squirrel.Windows /Users/tomw/.cache/Squirrel.Windows/Squirrel.Windows-1.4.4 +4s
  electron-builder Spawning mono /Users/tomw/.cache/Squirrel.Windows/Squirrel.Windows-1.4.4/SyncReleases.exe -u https://github.com/tom-james-watson/artpip-app -r /Users/tomw/git/art
pip-app/releases/win -t 9ccbf6164718414abde1c5ec118fcf89aa002d7d +63ms
  electron-builder appdmg: [20] Removing temporary image +5s

Files read from disk: 3246
Archive size: 46056809 bytes (44 MiB)
Everything is Ok
  electron-builder /Users/tomw/git/artpip-app/node_modules/7zip-bin-osx/7za (15288) exited with code 0 +2s
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Trying to download RELEASES index from https://github.com/tom-james-watson/artpip-app/RELEASES
Error: mono exited with code 255
Error output:
Attempting to sync URL as remote RELEASES folder
Failed to sync URL as GitHub repo: A task was canceled.
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: 404 (Not Found)
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () <0x1120cc780 + 0x000f0> in <filename unknown>:0
  at System.Net.Http.HttpClient+<GetStringAsync>c__async6.MoveNext () <0x1120cae30 + 0x00277> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by develar** [comment]
@tom-james-watson Fixed. Squirrel.Windows doesn't check files at all :(, so, `RELEASES` must be deleted also. Fixed version will be published soon.

**Comment by tom-james-watson** [comment]
I am still getting the same error as above. I ended up removing `remoteReleases` and `remoteToken` from config and then it builds fine. As far as I can tell, all this changes is that it will no longer produce delta updates? So if my app auto-updates on windows it will always have to download the full package? That's not the end of the world - that's what happens on Mac anyway.

**Comment by develar** [comment]
6.3.5 doesn't help you?

> all this changes is that it will no longer produce delta updates. Is that correct? 

yes

**Comment by arkakkar** [comment]
Hi,
electron-builder : 19.27.7
I get this error which making a build for the windows platform, target Squirrel.
I have mentioned both remoteReleases and remoteToken fro my private repo
<img width="1280" alt="screen shot 2017-09-20 at 9 22 58 pm" src="https://user-images.githubusercontent.com/13099382/30653875-ef2dfb02-9e49-11e7-8404-8a6c7a41b583.png">

**Comment by arkakkar** [comment]
This is resolved. Issue was due to trust certificates with mono for fetching resource over https://.
