### ISSUE TITLE
Append command-line configuration values to existing configuration?

### ISSUE THREAD

**Issue by leetal** [electron-userland/electron-builder#7140]
* **Electron-Builder Version**:  23.3.3

* **Node Version**: 16.17.0

* **Electron Version**: 20.1.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac/Mas

Is there any way to append to build-configuration values instead of overwringing them?
I cannot seem to find a way of appending values to for example the `extendInfo`-list under the mac confuguration options. 

There exists multiple use-cases for this like replacing the `DTSDKBuild` value during build time by supplying something like ```-c.mac.extendInfo+="DTSDKBuild: $(sw_vers -buildVersion)"```. Please note that extendInfo is a list of key-value pairs.

The intent is to not replace the already present list in the configuration that provides static values that do not change.

Thanks in advance!

**Comment by mmaietta** [comment]
What about using the programmatic API as I do in my project:
https://www.electron.build/api/programmatic-usage

Then in the script just use `const info = execSync('sw_vers -buildVersion`)` and set that value in the config directly.
