### ISSUE TITLE
cannot find module electron updater

### ISSUE THREAD

**Issue by deco-dev** [electron-userland/electron-builder#7147]
* **Electron-Builder Version**:  22.11.7

* **Node Version**: 14.17.4

* **Electron Version**: 12.0.9
* **Electron Type (current, beta, nightly)**: 

electron-updater: 5.2.1

* **Target**: windows

![image](https://user-images.githubusercontent.com/87562003/191163389-238b888d-2597-4196-8caf-f042e62cfffd.png)
First I installed electron-updater to dependencies.
```
"dependencies": {
        "@emotion/react": "^11.8.2",
        "@material-ui/core": "^4.11.3",
        "@material-ui/data-grid": "^4.0.0-alpha.26",
        "@material-ui/icons": "^4.11.2",
        "@material-ui/lab": "^4.0.0-alpha.57",
        "@mui/material": "^5.5.1",
        "@testing-library/jest-dom": "^5.11.10",
        "@testing-library/react": "^11.2.6",
        "@testing-library/user-event": "^12.8.3",
        "@types/jest": "^26.0.22",
        "@types/js-cookie": "^2.2.6",
         ...
        "electron-updater": "^5.2.1",
```
And I used electron updater to typescript.
```
import { app, BrowserWindow, ipcMain, dialog } from "electron";
import { autoUpdater } from "electron-updater";
```
So when I built typescript, There is no error. But I executed the app, the error occurred.
So I try to fix some code. This is orignal code. I removed the !node_modules. After that, there is no error.
```
        "files": [
            "desktop/*",
            "build/**/*",
            "build-desktop/**/*",
            "!node_modules"
        ],
```
But I don't want to add node_modules because the app size is increased.
This is log that gets with tsc --traceResolution option. As you can see the log, when build time, electron-updater is found.
But why can not found the module on runtime?
```
======== Resolving module 'electron-updater' from 'D:/DI/front-end/desktop/main.ts'. ========
Resolving real path for 'D:/DI/front-end/node_modules/electron-updater/out/main.d.ts', result 'D:/DI/front-end/node_modules/electron-updater/out/main.d.ts'.
======== Module name 'electron-updater' was successfully resolved to 'D:/DI/front-end/node_modules/electron-updater/out/main.d.ts' with Package ID 'electron-updater/out/main.d.ts@5.2.1'. ========
```

**Comment by deco-dev** [comment]
This list is tsc compiled files that gets  with--listFiles option.
```
D:/DI/front-end/node_modules/electron-updater/out/AppAdapter.d.ts
D:/DI/front-end/node_modules/electron-updater/out/DownloadedUpdateHelper.d.ts
D:/DI/front-end/node_modules/electron-updater/out/electronHttpExecutor.d.ts
D:/DI/front-end/node_modules/electron-updater/out/providers/Provider.d.ts
D:/DI/front-end/node_modules/typed-emitter/index.d.ts
D:/DI/front-end/node_modules/electron-updater/out/AppUpdater.d.ts
D:/DI/front-end/node_modules/electron-updater/out/BaseUpdater.d.ts
D:/DI/front-end/node_modules/electron-updater/out/AppImageUpdater.d.ts
D:/DI/front-end/node_modules/electron-updater/out/MacUpdater.d.ts
D:/DI/front-end/node_modules/electron-updater/out/NsisUpdater.d.ts
D:/DI/front-end/node_modules/electron-updater/out/main.d.ts
D:/DI/front-end/desktop/socketClient.ts
```

**Comment by deco-dev** [comment]
This is my build command.
```
"desktop-tsc": "tsc desktop/main.ts --skipLibCheck --target es5 --outDir build-desktop --esModuleInterop",
```
I execute npm run desktop-tsc && electron-builder --win

**Comment by deco-dev** [comment]
I checked the npm ls --production, it has electron-updater.
```
+-- electron-updater@5.2.1
```

**Comment by mmaietta** [comment]
You shouldn't explicitly exclude `"!node_modules"` as that's deliberately blocking the asset from being bundled in the asar. electron-builder should automatically parse your node_modules and only pack the ones that are production dependencies

**Comment by KVAnton-WEB** [comment]
Did you find a solution?
I have a similar problem one with rxjs

**Comment by OldManMeta** [comment]
The solution I found was to add a postinstall option:

 "package": "electron-builder",
 "postinstall": "electron-builder install-app-deps"

**Comment by Keyur-Dobariya** [comment]
any one find solution of this issue?

please share here
