### ISSUE TITLE
Setting perMachine: true causing build to fail on Windows

### ISSUE THREAD

**Issue by sfraise** [electron-userland/electron-builder#715]
3.10.6 + newest szwacz electron boilerplate

Windows

When trying to build on Windows 10 setting perMachine: true in package.json causes the build process to fail.

This was not an issue until early Monday morning.  I'm also trying to build this on a Mac and I do NOT have an issue with the build failing there, however the file association does not appear to be working.

I'm also NOT getting a npm-debug.log file written so I can't post anything from it.  See the attached screenshot of my terminal instead.
![electron-error](https://cloud.githubusercontent.com/assets/5533668/18149640/fc5b054a-6fa6-11e6-8aaa-2a825440c98c.png)

Here is a copy of my main package.json file:
```json
{
  "build": {
    "appId": "com.elite.planner",
    "category": "public.app-category.business",
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "resources/windows/icon.ico"
    },
    "nsis": {
      "oneClick": true,
      "perMachine": true,
      "installerHeaderIcon": "resources/windows/setup-icon.ico"
    },
    "mac": {
      "icon": "resources/osx/icon.icns"
    },
    "dmg": {
      "target": [
        "nsis"
      ],
      "icon": "resources/osx/dmg-icon.icns",
      "background": "resources/osx/dmg-background.png"
    },
    "fileAssociations": {
      "ext": "elite",
      "name": "ELITE"
    }
  },
  "directories": {
    "buildResources": "resources"
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "build": "gulp build",
    "prerelease": "gulp build --env=production",
    "release": "build --x64 --publish never",
    "start": "gulp start",
    "pretest": "gulp build-unit --env=test",
    "test": "electron-mocha app/specs.js.autogenerated --renderer --require source-map-support/register",
    "pree2e": "gulp build-e2e --env=test",
    "e2e": "mocha app/e2e.js.autogenerated --require source-map-support/register"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "electron": "1.3.3",
    "electron-builder": "^6.3.0",
    "electron-mocha": "^3.0.0",
    "fs-jetpack": "^0.9.0",
    "gulp": "^3.9.0",
    "gulp-batch": "^1.0.5",
    "gulp-less": "^3.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.3.5",
    "mocha": "^3.0.2",
    "rollup": "^0.34.7",
    "source-map-support": "^0.4.2",
    "spectron": "^3.3.0",
    "yargs": "^4.2.0"
  }
}
```

**Comment by develar** [comment]
It is `rcedit` bug (https://github.com/electron/rcedit). And rcedit was recently updated. Is it possible to send me your project? Without project I cannot reproduce.

**Comment by develar** [comment]
Please try to execute failed command in the terminal — is it still fail?

**Comment by sfraise** [comment]
@develar I just invited you to our bitbucket repo for the project.

**Comment by develar** [comment]
> The owner of this repository (codemonkeysllc) is already at their plan limit and will need to upgrade before adding more users.

Cannot access :(

**Comment by sfraise** [comment]
Ahh sorry @develar , stupid bitbucket...

I was able to figure this out though and it was a pretty silly oversight (lack of sleep tends to do that).  I was still using electron 1.3.3, I bumped it up to 1.3.5 and it worked like a champ.  I still need to confirm on the Mac now that the file association works but I'm guessing it will.

Thanks for all the help and for the work you put into this file association stuff, much appreciated!

**Comment by develar** [comment]
>  I bumped it up to 1.3.5 and it worked like a champ

Cool.

FYI: I have discovered possible bug, new version will be published soon.

**Comment by sfraise** [comment]
Everything seems to be working as expected now, even adding the icon to the custom file extension files, great job @develar !

I do have another question though.  My custom file is basically a data object string that I need to pull data from on open to populate values in the app, what do I hook into in order to fire my function when opening the file by just double clicking it?  Basically if you open a file from within the app it fires a function that pulls that data and works fine, I just need to do the same when clicking a file before the app is open if that makes sense?

**Comment by develar** [comment]
>  if that makes sense?

Sorry, canno advise, it is your app-specific.

**Comment by sfraise** [comment]
Thanks @develar , I don't think I was very clear in my last post.  I guess I wanted to know if there was anything in particular you built into your functionality that I should hook into or if I need to just try and parse the process.argv or something.

The reason I even ask is when I looked through your commit code it looks like your adding an option to set the file association type (editor, viewer, shell, etc) which made me think that maybe you're setting up some open-file handlers or something somewhere that I could hook into.

I'll just try to parse process.argv.

**Comment by develar** [comment]
> file association type (editor, viewer, shell, etc)

macOS-only. OS level. Not related to electron app code.
