### ISSUE TITLE
*** Error: The Info.plist in the package must contain the CFBundleShortVersionString key. Unable to validate your application.

### ISSUE THREAD

**Issue by lanyusan** [electron-userland/electron-builder#7150]
* **Electron-Builder Version**: 
23.3.3

* **Node Version**: 
16.17.0

* **Electron Version**:
20.1.4

* **Electron Type (current, beta, nightly)**:

current

* **Target**: 

Mac MAS

After the app is packaged and signed, when I use `altool` to upload app for review, I got following error:

```
2022-09-22 10:15:02.016 *** Error: Error uploading 'release/build/mas-arm64/xxx.app'.
2022-09-22 10:15:02.016 *** Error: The Info.plist in the package must contain the CFBundleShortVersionString key. Unable to validate your application. (-27002)
 {
    NSLocalizedDescription = "The Info.plist in the package must contain the CFBundleShortVersionString key.";
    NSLocalizedFailureReason = "Unable to validate your application.";
}
```

How to set`CFBundleShortVersionString`? Should I set it manually? I couldn't find instruction in doc or issue. 

Thanks in advance

**Comment by lanyusan** [comment]
Update: 
I have added the following keys
```
bundleVersion String | “undefined” - The CFBundleVersion. Do not use it unless [you need to](https://github.com/electron-userland/electron-builder/issues/565#issuecomment-230678643).

bundleShortVersion String | “undefined” - The CFBundleShortVersionString. Do not use it unless you need to.
```
Still  the same problem.

**Comment by Deamoner** [comment]
This issue is driving me nuts. That term is in the plist but it says it is not.

**Comment by rsunil123** [comment]
any update on this. I am facing the same problem.

**Comment by Deamoner** [comment]
I have fixed this issue, I think this particular issue is driven by the formatting of the xml in the file. I used an online editor to fix it.

**Comment by bluebreadhead** [comment]
> I have fixed this issue, I think this particular issue is driven by the formatting of the xml in the file. I used an online editor to fix it.
@Deamoner Can you suggest which one?
