### ISSUE TITLE
Deep linking behavior when no app is installed

### ISSUE THREAD

**Issue by KazukiSugiyama107** [electron-userland/electron-builder#7151]
* **Electron-Builder Version**: 22.2.0

* **Node Version**: v16.16.0

* **Electron Version**:v8.2.3
* **Electron Type (current, beta, nightly)**:beta

* **Target**: general user

I was able to set up a desktop app created with electron-builder to start with a deep link and launch the app from the browser.
I would like to implement this so that if the app is not installed, it jumps to a specific page from the browser, but I do not know how to do this.
There are multiple ways to do this on Android and iOS devices, but do you know of a feasible way to do this on a PC?

Perhaps this is not a problem I should post here, but if so, please point me in the right direction.

**Comment by mmaietta** [comment]
AFAIK, that is not possible as the protocol must be registered with the app already installed. I'm guessing the OS checks whether the app is installed prior to opening a deeplink
