### ISSUE TITLE
Two native modules have the same architectures (x86_64) and can't be in the same fat output file error

### ISSUE THREAD

**Issue by harlandjp** [electron-userland/electron-builder#7155]
* **Electron-Builder Version**: 23.5.1

* **Node Version**: v16.17.0

* **Electron Version**:20.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS universal

I'm trying to package my app with a npm package (active-win) that includes a native universal module, but I get the following error:
```
node_modules/active-win have the same architectures (x86_64) and can't be in the same fat output file
```
Looking around, it seems [this has been addressed](https://github.com/electron/universal/pull/47) in @electron/universal's latest version, which electron-builder doesn't use yet. Can you update the dependency please?

**Comment by mmaietta** [comment]
`x64ArchFiles` is already supported in electron-builder: https://www.electron.build/configuration/mac

**Comment by cyspath** [comment]
@harlandjp were you able to get it to work with x64ArchFiles? I tried this flag yet builder still tries to bundle it

**Comment by pantelispanayiotou** [comment]
Running in to the same issue. I am not able to use the flag cause electron builder 23.6.0 support it but it references an older version of electron universal. Are there any workarounds?

**Comment by mmaietta** [comment]
Alpha build should be promoted to regular in the near future.

My main concern (and reason for long alpha cycle) was regarding some changes to electron-updater, specifically changes that added rpm/deb auto-update support - it consolidated `spawn` logic that is also used by  AppImages and NSIS. Latest alpha release resolves related electron-updater issue: https://github.com/electron-userland/electron-builder/issues/7393

Unfortunately, due to the way `changesets` work, both electron-updater and electron-builder alpha states are "linked"

**Comment by idevelop** [comment]
@mmaietta any update on promoting the alpha build to production?

**Comment by mmaietta** [comment]
Out of curiosity, [24.4.0](https://www.npmjs.com/package/electron-builder/v/24.4.0) is `next`, not specifically `latest` tag. Do you need it as `latest`?

Can bump it to `latest` easily, I honestly forgot lost track of this request

**Comment by mmaietta** [comment]
Done

**Comment by rasgo-cc** [comment]
@mmaietta would it make sense to have a `arm64ArchFiles`? I'm currently trying to get a `universal` build but stuck with a native dependency (`leveldown`) built for `arm64` only.

The error I get is something like this:
```
Command failed: lipo /private/var/folders/3v/qtqyt73168z7pryd0mnty67w0000gn/T/arm64-yHKlJ8/node_modules/leveldown/build/Release/leveldown.node /private/var/folders/3v/qtqyt73168z7pryd0mnty67w0000gn/T/x64-wER0TT/node_modules/leveldown/build/Release/leveldown.node -create -output /private/var/folders/3v/qtqyt73168z7pryd0mnty67w0000gn/T/x64-wER0TT/node_modules/leveldown/build/Release/leveldown.node
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/3v/qtqyt73168z7pryd0mnty67w0000gn/T/arm64-yHKlJ8/node_modules/leveldown/build/Release/leveldown.node and /private/var/folders/3v/qtqyt73168z7pryd0mnty67w0000gn/T/x64-wER0TT/node_modules/leveldown/build/Release/leveldown.node have the same architectures (arm64) and can't be in the same fat output file
```
