### ISSUE TITLE
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by Brad-Dui** [electron-userland/electron-builder#7157]
### Electron Version

20.2.0

### Electron-builder Version

22.14.13

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

There was no problem in the development environment, but `localStorage` in the page showed the error when I packaged it.

### Actual Behavior

![image](https://user-images.githubusercontent.com/79361167/192188521-0fd66087-ec4c-4d91-abf8-cad819eca0b1.png)

**Comment by Brad-Dui** [comment]
It's been solved
` standard: true`
```js
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { standard: true, supportFetchAPI: true, secure: true } }
])
```

**Comment by HAIlows** [comment]
Hi, I have the same problem, I added `protocol.registerSchemesAsPrivileged([{ scheme: 'app', privileges: { secure: true } }]);`and I will have the same problem after build
