### ISSUE TITLE
I want to build electron-updater on my local system

### ISSUE THREAD

**Issue by alimuddins** [electron-userland/electron-builder#7159]
* **Electron-Builder Version**:  23.1.0

* **Node Version**:  14x

* **Electron Version**: 13
* **Electron Type (current, beta, nightly)**: Current

* **Target**:  Current

I am using electron-updater version 4.6.5, i am tweaking this version with my current needs without actually 
upgrading the electron builder version.

I want to compile the electron-updater to the same version, can you help me how to setup into my local
and do the build?

**Comment by mmaietta** [comment]
To set up a dev environment, you can follow these instructions for develop+testing in your app.
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

To persist the changes between your project's CI/CD builds, you can use patch-package (installed via npm) to retain the changes with your custom version (as opposed to requiring you to publish to npm your own fork)

**Comment by alimuddins** [comment]
Thanks @mmaietta , worked for me.
