### ISSUE TITLE
Installer is lauching app during install

### ISSUE THREAD

**Issue by Hazow** [electron-userland/electron-builder#716]
* **Version**: 3.10.3

* **Target**: Windows x64

I think I did it fine but when I launch the .exe :
- The gif appear.
- The app start (here is the problem)
- The app close
- The gif disapear
- The app start

And I have the same issue for uninstall, the app start during process.
Ho and when the app is installed, i don't have any shortcut for open it (Windows 10)

Note : The app works fine with the unpacked version.

### Dev package.json 
`{
  "name": "MyApp",
  "scripts": {
    "postinstall": "install-app-deps",
    "pack": "build --win --x64 --dir",
    "dist": "build --win --x64"
  },
  "build": {
    "appId": "me.myapp",
    "productName": "My App",
    "win": {
      "title": "MyApp",
      "version": "0.0.3",
      "authors": "ME",
      "iconUrl": "https://mywebsite.fr/img/icon.ico"
    }
  },
  "devDependencies": {
    "electron": "^1.3.4"
}
`

### App package.json
`{
  "name": "MyApp",
  "version": "0.0.3",
  "description": "Awesome app",
  "author": "ME",
  "main": "main.js",
  "dependencies": {
    "electron-notify": "^0.1.0"
  }
}
`

Thank you.

**Comment by develar** [comment]
Please ensure that you use latest version — `6.3.2`.

**Comment by develar** [comment]
> when the app is installed, i don't have any shortcut for open it (Windows 10)

Please see #551

**Comment by Hazow** [comment]
Thank you for the shortcut ! I will looking that

But same things after upgrade to 6.3.2 :/

**Comment by develar** [comment]
You should handle Squirrel.Windows events — https://github.com/electron/windows-installer#handling-squirrel-events

If you don't like it — use `nsis` target instead (but be aware of #529).

**Comment by Hazow** [comment]
Thank you, I will do that with squirrel
