### ISSUE TITLE
Startup item not removed after uninstall when openAtLogin is true

### ISSUE THREAD

**Issue by yooouuri** [electron-userland/electron-builder#7160]
* **Electron-Builder Version**: 

^23.3.3

* **Node Version**: 

v16.17.0

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

^20.0.0

* **Target**: 

Windows (NSIS)

When I use Settings > Apps > Apps & Features and I uninstall the app, there is still an entry in App > Startup.

So the app is uninstalled, but when I reboot the app shows because of the `openAtLogin` property.

(Sorry for photos taken with my camera)

![IMG_1646](https://user-images.githubusercontent.com/12934957/192475914-3f8fa14c-d94b-4e58-9eb4-e8c2f3b0a276.jpg)

![IMG_1645](https://user-images.githubusercontent.com/12934957/192475942-42cf984b-f28c-4a46-8cd2-04138a420c96.jpg)

**Comment by jaime-rivas** [comment]
We are having the same issue. @yooouuri did you find any solution? Thanks!
