### ISSUE TITLE
electron-updater fails to connect to the server...again

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#7167]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.17.0

* **Electron Version**: 20.0.3
* **Electron Type (current, beta, nightly)**: current

5.2.1

* **Target**: macOS (Intel)

After spending lots of time fixing the electron updater to make it work with a proxy server to access the Internet, we ran into a proxy issue again trying to update to our [latest release](https://github.com/oracle/weblogic-toolkit-ui/releases/tag/v1.3.0) from the [previous release](https://github.com/oracle/weblogic-toolkit-ui/releases/tag/v1.2.0).  We can see very clearly what is happening:

```
info: Downloading update from WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip, WebLogic-Kubernetes-Toolkit-UI-1.3.0.dmg, WebLogic-Kubernetes-Toolkit-UI-1.3.0-arm64-mac.zip, WebLogic-Kubernetes-Toolkit-UI-1.3.0-arm64.dmg
debug: Checking for macOS Rosetta environment
warn: sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'

debug: Checking for arm64 in uname
info: Checked 'uname -a': arm64=false
debug: updater cache dir: /Users/rpatrick/Library/Application Support/Caches/wktui-updater
info: Update has already been downloaded to /Users/rpatrick/Library/Application Support/Caches/wktui-updater/pending/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip).
debug: Creating proxy server for native Squirrel.Mac (fileToProxy=https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.3.0/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip)
debug: Proxy server for native Squirrel.Mac is created (fileToProxy=https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.3.0/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip)
debug: Proxy server for native Squirrel.Mac is starting to listen (fileToProxy=https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.3.0/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip)
debug: Proxy server for native Squirrel.Mac is listening (address=http://127.0.0.1:56997, fileToProxy=https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.3.0/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip)
info: Download complete, install type: now
info: Proxy server for native Squirrel.Mac is closed (fileToProxy=https://github.com/oracle/weblogic-toolkit-ui/releases/download/v1.3.0/WebLogic-Kubernetes-Toolkit-UI-1.3.0-mac.zip)
warn: Could not connect to the server. {"code":-1004,"domain":"NSURLErrorDomain"}
error: Error: Error: Could not connect to the server.
error: Error: Error: Could not connect to the server.
error: Application auto-updater failed: Could not connect to the server.
error: Error: Could not connect to the server.
```

**Comment by robertpatrick** [comment]
It seems like this has nothing to do with the proxy.  Install Now is failing (whether behind the proxy or not) but Install on Exit is working.

**Comment by robertpatrick** [comment]
@mmaietta any thoughts on why I am seeing this?

**Comment by mmaietta** [comment]
Hmmm, I found this: https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorcannotconnecttohost
> This can occur when a host name resolves, but the host is down or may not be accepting connections on a certain port.

```
info: Download complete, install type: now
```
That seems to be coming from electron's native updater, as I don't see "Download complete" anywhere in our codebase.


Two things stick out to me in the code:
https://github.com/electron-userland/electron-builder/blob/3816d4f30371345def83a0667d67648790259605/packages/electron-updater/src/MacUpdater.ts#L191-L192
Server listens to port `0`, but then for the logs, it is `address=http://127.0.0.1:56997`. Not sure if this is an issue though as it would be a much more wide-spread issue (with all mac updates broken for everyone)
This seems to be where the code is failing for you. It's almost as if the file hasn't been downloaded yet or electron's native updater still is checking to see if the server is up (via `quitAndInstall`)?
https://github.com/electron-userland/electron-builder/blob/3816d4f30371345def83a0667d67648790259605/packages/electron-updater/src/MacUpdater.ts#L216-L220

**Comment by mmaietta** [comment]
@robertpatrick side question. Do you think it's necessary to `close()` the server when `quitAndInstall()`? Wouldn't the server automatically be closed when the app exits?
This is in regards to this hunch:
> It's almost as if the file hasn't been downloaded yet or electron's native updater still is checking to see if the server is up (via quitAndInstall)?

**Comment by robertpatrick** [comment]
@mmaietta As far as I can tell from the Node.js docs, it looks like the "server" is created inside the current Node.js process.  If so, then it is not strictly necessary to call `close()` but it doesn't hurt anything and shows that the code is trying to clean up resources it created.  Personally, I would leave it but that's up to you.

It seems that my issue was likely related to having an intermediate build installed that was not published on GitHub as once I cleaned things up, I was no longer able to reproduce the problem...
