### ISSUE TITLE
winCodeSign SignTool.exe - unexpected internal error

### ISSUE THREAD

**Issue by jschimmoeller** [electron-userland/electron-builder#717]
* **Version**:  6.3.2

* **Target**:  1.3.4

I am using an EV usb cert. 

Here is my debug.log with error:
CI detected, so artifacts will be published if draft release exists
Thu, 01 Sep 2016 15:53:24 GMT electron-builder Found existing nsis C:\Users\S2S Dev\.cache\nsis\nsis-3.0.1
Thu, 01 Sep 2016 15:53:24 GMT electron-builder Spawning npm.cmd rebuild --production --build-from-source --cache-min 999999999
Rebuilding app dependencies for arch x64 to C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app

child_process@1.0.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\child_process
electron-json-storage@2.0.0 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage
async@1.5.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\async
exists-file@1.0.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\exists-file
lodash@4.15.0 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\lodash
rimraf@2.5.4 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf
glob@7.0.6 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob
fs.realpath@1.0.0 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\fs.realpath
inflight@1.0.5 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\inflight
once@1.3.3 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\once
wrappy@1.0.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\once\node_modules\wrappy
wrappy@1.0.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\inflight\node_modules\wrappy
inherits@2.0.1 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\inherits
minimatch@3.0.3 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\minimatch
brace-expansion@1.1.6 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion
balanced-match@0.4.2 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match
concat-map@0.0.1 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map
path-is-absolute@1.0.0 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\electron-json-storage\node_modules\rimraf\node_modules\glob\node_modules\path-is-absolute
path@0.12.7 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\path
process@0.11.9 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\path\node_modules\process
util@0.10.3 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\path\node_modules\util
inherits@2.0.1 C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\app\node_modules\path\node_modules\util\node_modules\inherits
Thu, 01 Sep 2016 15:53:26 GMT electron-builder npm.cmd (4748) exited with code 0
Packaging for platform win32 x64 using electron 1.3.4 to dist\win-unpacked

Thu, 01 Sep 2016 15:53:34 GMT electron-builder Found existing winCodeSign C:\Users\S2S Dev\.cache\winCodeSign\winCodeSign-1.4.2
Thu, 01 Sep 2016 15:53:34 GMT electron-builder Executing C:\Users\S2S Dev\.cache\winCodeSign\winCodeSign-1.4.2\rcedit.exe C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\dist\win-unpacked\StarPhoneDesktop.exe --set-version-string CompanyName Star2Star --set-version-string FileDescription StarPhone Desktop --set-version-string ProductName StarPhoneDesktop --set-version-string InternalName StarPhoneDesktop --set-version-string LegalCopyright © 2016 Star2Star Communications, LLC --set-version-string OriginalFilename  --set-file-version 2.5.0 --set-product-version 2.5.0 --set-icon C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\build\icon.ico
Signing StarPhoneDesktop.exe (certificate file "undefined")
Thu, 01 Sep 2016 15:53:34 GMT electron-builder Executing C:\Users\S2S Dev\.cache\winCodeSign\winCodeSign-1.4.2\windows-6\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /n star2star /d StarPhoneDesktop C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\dist\win-unpacked\StarPhoneDesktop.exe
Thu, 01 Sep 2016 15:53:44 GMT electron-builder Executing C:\Users\S2S Dev\.cache\winCodeSign\winCodeSign-1.4.2\windows-6\signtool.exe sign /tr http://timestamp.digicert.com /n star2star /fd sha256 /td sha256 /d StarPhoneDesktop /as C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\dist\win-unpacked\StarPhoneDesktop.exe
Error: Command failed: C:\Users\S2S Dev\.cache\winCodeSign\winCodeSign-1.4.2\windows-6\signtool.exe sign /tr http://timestamp.digicert.com /n star2star /fd sha256 /td sha256 /d StarPhoneDesktop /as C:\Users\S2S Dev\projects\softphone\desktop\trunk\app-container\dist\win-unpacked\StarPhoneDesktop.exe
SignTool Error: An unexpected internal error has occurred.

Done Adding Additional Store
Error information: "Error: SignerSign() failed." (-2146893792/0x80090020)

SignTool Error: An unexpected internal error has occurred.

    at C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:96:16
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at Object.exec (C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:77:9)
    at C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\windowsCodeSign.ts:114:20
From previous event:
    at tsAwaiter (C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:195:52)
    at Object.<anonymous> (C:\Users\S2S Dev\AppData\Roaming\npm\node_modules\electron-builder\src\build-cli.ts:27:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by jschimmoeller** [comment]
FYI, by adding signingHashAlgorithms: ['sha1'] does work must be an issue with sha256

**Comment by develar** [comment]
> Executing C:\Users\S2S Dev.cache\winCodeSign\winCodeSign-1.4.2\windows-6\signtool.exe

It seems your Windows is outdated. Please specify Windows version.

**Comment by jschimmoeller** [comment]
it is on a windows 7 Home Premium Service Pack 1

**Comment by develar** [comment]
Unlikly issue will be fixed — if possible please use Windows 10.

**Comment by develar** [comment]
Duplicates #584

**Comment by rptwsthi** [comment]
I am using Windows 10. After packaging process is completed I get this:

Package creation succeeded.

Error information: "Error: Store IsDiskFile() failed." (-2147024893/0x80070003)

SignTool Error: An unexpected internal error has occurred.

> Error: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> Error: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> PS D:\Arpit\GSWindows\GSLive\GoSesstionDesktop>
