### ISSUE TITLE
Universal MAS app cannot be opened because the developer cannot be verified 

### ISSUE THREAD

**Issue by gpronet** [electron-userland/electron-builder#7171]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.14.0

 

* **Electron Version**:19.0.0
* **Electron Type (current, beta, nightly)**:

* **Target**: mas

When building an app for the MAS platform, the app can be installed through TestFlight but when started through TestFlight, it displays the following message:

“.TeamId.com.app.id.[random string]” cannot be opened because the developer cannot be verified. (notice the dot before TeamId)

I've checked the app with the usual tools (codesign,pkgutil, spctl), they give no clue to any problems. All entitlements also look fine.

When submitted for review in the MacOS store, it gets rejected with the following message:

"The app cannot be opened because the developer cannot be verified. This may due to an issue with your app’s Gatekeeper conformance. Please see the Checking Gatekeeper Conformance section of Technote 2206 - macOS Code Signing In Depth."

I have run out of ideas what to try to fix this. The app runs fine on all other platforms including Mac, Gatekeeper does not complain. Attaching a log from the build process. Here is the config:

```
{
  "appId": "com.app.id",
  "afterSign": "resources/notarize.js",
  "directories": {
    "buildResources": "resources"
  },
  "files": [
    "assets/**/*",
    "build/**/*",
    "capacitor.config.*",
    "app/**/*"
  ],
  "publish": {
    "provider": "github"
  },
  "nsis": {
    "allowElevation": true,
    "oneClick": false,
    "allowToChangeInstallationDirectory": true
  },
  "win": {    
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64",
          "ia32",
          "arm64"
        ]
      },
      {
        "target": "appx",
        "arch": [
          "x64",
          "ia32",
          "arm64"
        ]
      }
    ],
    "icon": "assets/appIcon.ico"
  },
  "appx":{
      "identityName": "Company.AppName",
      "publisher": "CN=...",
      "publisherDisplayName": "Company",
      "applicationId": "AppName",
      "displayName": "AppName"
  },
  "mac": {
    "asarUnpack": [
      "**/*.node"
    ],
    "icon":"assets/icon.icns",
    "category": "public.app-category.racing-games",    
    "target": [
      {
        "target": "mas",
        "arch": [
          "universal"
        ]
      }
      
    ],
    "type": "distribution",
    "provisioningProfile":"embedded.provisionprofile",
    "entitlements": "build/entitlements.mac.plist",
    "entitlementsInherit": "build/entitlements.mac.plist",
    "hardenedRuntime": true,
    "gatekeeperAssess": false,
    "extendInfo": {
      "DTSDKBuild": "21E226",
      "ElectronTeamID":"TeamId",
      "ITSAppUsesNonExemptEncryption":false
    }
  },
  "mas": {
    "hardenedRuntime": false,
    "gatekeeperAssess": false,
    "provisioningProfile":"embedded.provisionprofile",
    "entitlements": "build/entitlements.mas.plist", 
    "entitlementsInherit": "build/entitlements.mas.inherit.plist",
    "entitlementsLoginHelper": "build/entitlements.mas.loginhelper.plist",
    "extendInfo": {
      "DTSDKBuild": "21E226",
      "ElectronTeamID":"TeamId",
      "ITSAppUsesNonExemptEncryption":false
    }
  },
  "dmg": {
    "sign": false
  },
  "linux": {
    "icon":"assets/icon.icns",
    "category":"Game",
    "target":["AppImage","snap","deb","rpm"],
    "executableName":"appname"
  }
}
```

[buildlog.txt](https://github.com/electron-userland/electron-builder/files/9693129/buildlog.txt)

**Comment by mmaietta** [comment]
Pretty sure these are required to be `true`
```
    "hardenedRuntime": false,
    "gatekeeperAssess": false,
```

**Comment by gpronet** [comment]
> Pretty sure these are required to be `true`

After setting them to true and rebuilding, the app generates the same error in TestFlight.

**Comment by mmaietta** [comment]
The only reference to `ElectronTeamID` in electron-builder is in test code: https://github.com/electron-userland/electron-builder/search?q=ElectronTeamID
Other than that, we don't do any appending. How is your notarizing set up?

**Comment by lukas2** [comment]
> > Pretty sure these are required to be `true`
> 
> After setting them to true and rebuilding, the app generates the same error in TestFlight.

same here

**Comment by gpronet** [comment]
> How is your notarizing set up?

The app notarizing works ok when I build for MAC (distribution outside the Mac App store). The app can be distributed and started by users without any problem. The problem occurs when I build for MAS (Mac app store distribution) and unless I've missed something notarization is not needed or relevant for that build type (it happens internally on Apple's side after the app is uploaded to TestFlight). But anyway here is the setup:

`require('dotenv').config();
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
  const { electronPlatformName, appOutDir } = context;  
  if (electronPlatformName !== 'darwin') {
    return;
  }

  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    appBundleId: 'com.app.id',
    appPath: `${appOutDir}/${appName}.app`,
    appleId: 'apple@id.com',
    appleIdPassword: 'app-specific-password'
  });
};`

**Comment by gpronet** [comment]
I have some new findings. Upon starting the app in TestFlight, it displays this message 2 times:

> “.TeamId.com.app.id.[6 random chars]” cannot be opened because the developer cannot be verified. 
> 
> macOS cannot verify that this app is free from malware.

Below this message it says: "AppName created this file today at 18:40." and I get the options [Move to Bin] or [Cancel].

I clicked [Move to Bin] and went to look for the files. The 2 binary files are actually hidden files, so after showing them and pulling them out of the bin I went to analyze them. The file names look like this:

._.TeamId.com.app.id.[6 random chars]
 
The only readable text in them is the following:

Near the top:

```
Mac OS X 
ATTR
com.apple.quarantine
0086;634040d0;AppName;
```

Near the bottom:

`This resource fork intentionally left blank`

Any ideas why those files are created and what is their purpose? Is it because Gatekeeper quarantines the app? Can they give us any clues at to what is going on?

**Comment by mmaietta** [comment]
I've never heard of those files/entries before tbh
Have you tried this potential solution? https://github.com/electron/osx-sign/issues/251#issuecomment-1252814349

**Comment by gpronet** [comment]
I managed to get the app running (disabled app.requestSingleInstanceLock() check). Now the app displays the same dreaded error message when started in TestFlight and actually starts running normally after that. The new quest is to figure out why those error messages appear. After some digging in the system log I found the following entries when I start the app from TestFlight (rows 1-7 are probably the key to this puzzle):

```
error	19:02:46.238619+0300	kernel	8 duplicate reports for Sandbox: TestFlightServic(1116) deny(1) mach-lookup com.apple.xpc.amsengagementd
error	19:02:46.238626+0300	kernel	Sandbox: taskgated-helper(37435) deny(1) user-preference-read kCFPreferencesAnyApplication
error	19:02:46.238631+0300	cfprefsd	rejecting read of { kCFPreferencesAnyApplication, kCFPreferencesAnyUser, kCFPreferencesCurrentHost, /Library/Preferences/.GlobalPreferences.plist, managed: 0 } from process 37435 (taskgated-helper) because accessing these preferences requires user-preference-read or file-read-data sandbox access
fault	19:02:46.238792+0300	taskgated-helper	Couldn't read values in CFPrefsPlistSource<0x13e1066f0> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: No): accessing these preferences requires user-preference-read or file-read-data sandbox access
error	19:02:46.285345+0300	taskgated-helper	com.app.id: Unsatisfied entitlements: com.apple.security.application-groups
error	19:02:46.285392+0300	taskgated-helper	Disallowing: com.app.id
error	19:02:46.285716+0300	CoreServicesUIAgent	Soft-restriction provisioning profile validation failure: Error Domain=AppleMobileFileIntegrityError Code=-413 "No matching profile found" UserInfo={NSURL=<private>, unsatisfiedEntitlements=<private>, NSLocalizedDescription=No matching profile found}
error	19:02:46.357287+0300	taskgated-helper	com.app.id: Unsatisfied entitlements: com.apple.security.application-groups
error	19:02:46.357336+0300	taskgated-helper	Disallowing: com.app.id
error	19:02:46.357661+0300	amfid	CPValidateProvisioningDictionariesExtViaBridge returned invalid result: {
    success = 0;
}
error	19:02:48.953510+0300	containermanagerd	failed to read /Library/Preferences/Logging/com.apple.diagnosticd.filter.plist: [1: Operation not permitted]
error	19:02:48.953685+0300	containermanagerd	failed to read /Library/Preferences/Logging/com.apple.diagnosticd.filter.plist: [1: Operation not permitted]
error	19:02:49.105560+0300	kernel	Sandbox: AppName(37436) deny(1) iokit-open-user-client AppleNVMeEANUC
error	19:02:49.257153+0300	kernel	Sandbox: swcd(505) deny(1) system-fsctl _IO('h', 47)
error	19:02:49.300983+0300	syspolicyd	Unable to get certificates array: (null)
error	19:02:49.511677+0300	syspolicyd	cannot open file at line 45530 of [9ff244ce07]
error	19:02:49.511707+0300	syspolicyd	os_unix.c:45530: (2) open(/var/db/DetachedSignatures) - No such file or directory
error	19:02:49.513717+0300	syspolicyd	Error Domain=NSOSStatusErrorDomain Code=-67062
error	19:02:49.601536+0300	syspolicyd	SecAssessmentCreate failure for PST: (vuid: CB50A6AF-DC9B-4B48-86DA-90CE8EBEDE3A), (objid: 22268418), (team: (null)), (id: (null)), (bundle_id: (null)): Error Domain=NSOSStatusErrorDomain Code=-67026
error	19:02:49.873014+0300	TestFlightServiceExtension	tcp_input [C146.1:3] flags=[R.] seq=298832937, ack=2163560869, win=501 state=CLOSED rcv_nxt=298832913, snd_una=2163560869
```

I attempted giving the app additional entitlements like the below but it made no difference:

<key>com.apple.security.temporary-exception.shared-preference.read-only</key>
<array>
	<string>.GlobalPreferences</string>
	<string>com.apple.WebKit.PluginProcess</string>
	<string>kCFPreferencesAnyApplication</string>
	<string>kCFPreferencesAnyUser</string>
	<string>kCFPreferencesCurrentHost</string>
</array>

The app is nothing special, it doesn't use any special entitlements. So this must be an internal Electron issue. Any ideas?

**Comment by mmaietta** [comment]
Ah, regarding the single instance lock, that doesn't seem to be supported specifically for mas target, as I guess MacOS only allows one instance of the App Store apps anyways?
https://github.com/electron/electron/issues/15958#issuecomment-472211386

**Comment by gpronet** [comment]
Finally we were able to come to the solution, just add `mergeASARs: false` in the config, it gets rid of the error messages. The problem was related to native modules. More info here:

https://github.com/electron/osx-sign/issues/266#issuecomment-1274257957

**Comment by grantmk** [comment]
Thank you @gpronet for this solution!

**Comment by batis97** [comment]
Hello i still have this problem

> mergeASARs

I've set it up > mergeASARs: false  and the eror still show in testflight
i using electron + svelkit 
this my electron and builder version:
"electron": "^26.2.2",
"electron-builder": "^24.6.4",
