### ISSUE TITLE
After upgrade to Electron 21.0.1 app longer starts on macOS/M1

### ISSUE THREAD

**Issue by jkowalski** [electron-userland/electron-builder#7172]
(Not sure if this electron or an electron-builder issue):

* **Electron-Builder Version**: 23.3.3 

* **Node Version**: 16.13.0

* **Electron Version**: 21.0.1
* **Electron Type (current, beta, nightly)**:

* **Target**:  macOS/ARM

I've been using Electron Builder for a while, i was on Electron 19.0.8. After upgrade to 21.0.1 which is causing application to no longer start on macOS/M1.

I can repro this on both CI/CD (Github Actions, the builder is on x64) and when building locally. The change is: https://github.com/kopia/kopia/pull/2477

### Symptom 1: ARM64 binary built by CI/CD is reported as damaged and can't start (x64 works fine under Rosetta):

![image](https://user-images.githubusercontent.com/249880/193470366-9c1c21f0-76d9-4ae0-b8fd-a760c5b374da.png)

(x64 builds for macOS, Windows and Linux builds are also fine - they pass automated tests on Github)

### Symptom 2: ARM64 binary built locally on M1 fails to start (x64 works fine under Rosetta) - the error is different:

In http://github.com/kopia/kopia:

```
$ gh pr checkout 2477
$ make kopia-ui
$ open dist/kopia-ui/mac-arm64/KopiaUI.app
```

![image](https://user-images.githubusercontent.com/249880/193470608-4887449b-8ffa-4217-96fb-3aefd6066210.png)

**Comment by mmaietta** [comment]
Is your arm64 app signed and notarized? I believe that's a necessity in order for it to run on arm64 devices (that the app wasn't also built on)

**Comment by jkowalski** [comment]
yes both local and CI/CD builds do sign and notarize. It's been working for years now and stopped with this upgrade.

**Comment by mmaietta** [comment]
Hmmm I'm not able to reproduce the issue when building electron-quickstart-typescript project with electron 21. I built an arm64 binary locally on my m1, without signing or notarizing, and am able to still run it.
![Screen Shot 2022-10-07 at 7 14 04 AM](https://user-images.githubusercontent.com/5238867/194574380-e0aa8de4-83cd-4eab-8a73-bee0f0795b4a.png)
Could it be some entitlements that you're missing? I'm using the standard template entitlements that come with electron-builder.
