### ISSUE TITLE
Upgrading to electron builder 21.2.0 from previous versions

### ISSUE THREAD

**Issue by rlsmith04** [electron-userland/electron-builder#7176]
* **Electron-Builder Version**: 21.2.0

* **Node Version**: 16.15.1

* **Electron Version**:11.5
* **Electron Type (current, beta, nightly)**:current
n/a

* **Target**: 

In previous versions of electron-builder (we are using 20.43.0), a plain GUID was being used for the installation.
Since 21.2.0, a bracketed GUID {GUID} is being used which causes an upgrade to show both the old and new installation and changes the behaviour of the installation.

**Comment by mmaietta** [comment]
Unfortunately, I didn't join the maintainer crew until after v21 was released, so I'm not too sure what changed between those versions. 
My best recommendation is to try manually specifying `guid` in the config file https://www.electron.build/configuration/nsis as it should set it verbatim, hopefully without the brackets. I don't see any code for the brackets though that reference `guid` in the code (or when it generates a UUID.v5(...) if none provided).

Regardless, can you try latest version of electron-builder, as I'm not able to provide support for older ones
