### ISSUE TITLE
How to show installtion progress after execute autoUpdater.quitAndInstall()

### ISSUE THREAD

**Issue by KongLee26** [electron-userland/electron-builder#7186]
* **Electron-Builder Version**: 

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:

**Comment by mmaietta** [comment]
Unfortunately, there's no way for us to provide a progress status for the installation method. For Mac, it uses electron's native electron-updater. For AppImage, it's a simple `.AppImage` file replacement via `mv -f`. For NSIS, it spawns a **detached** thread for the installer to kickoff before calling `app.quit()`
None of which are able to provide a callback or indicator that electron-builder could listen/forward to the app
