### ISSUE TITLE
Per FPM Target Depends

### ISSUE THREAD

**Issue by Rob4001** [electron-userland/electron-builder#719]
* **Version**: 5.18.0

* **Target**: rpm deb

I am trying to create an app which depends on system python 2.7

On deb based systems the dependency is called python2.7 and on rpm it is just called python,
Is there any way to differentiate the depends by which target is being built for?

**Comment by develar** [comment]
Yes — don't specify in `linux`, but in `rpm`. You can specify custom configuration using target name as key in the `build`.

**Comment by develar** [comment]
Relates: #502

**Comment by develar** [comment]
It is better to use AppImage, but deps is no yet supported for it. If need, please file issue to track progress. In case of AppImage you will be able to distribute only one file.

**Comment by sidneys** [comment]
@develar 
This does not work anymore at all, maybe due to the newly introduced configuration validation, breaking usage of newer versions of electron-builder for our projects - when specifying targets at the top  configuration (`build.target`) level, we get this result:

```
Raw validation errors: [
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "pacman"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "rpm"
    },
    "message": "should NOT have additional properties"
  }
]
```

Is there any solution for this?
