### ISSUE TITLE
Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies"

### ISSUE THREAD

**Issue by fieteboerner** [electron-userland/electron-builder#7191]
* **Electron-Builder Version**: 23.3.3

* **Node Version**: 16.13.2

* **Electron Version**: 19.0.2
* **Electron Type (current, beta, nightly)**: 

* **Target**: AppImage

By building a production application I get the following error:
> ⨯ Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.

What is the reason for this error message? I tried to add electron also to the devDependencies (and keep them in the dependencies as well). But I get the exact same error.
I really dont get why ist the builder aborting at this point. Is there a technical or just a philosophical reason for this? If last, it would be nice to allow electron in the dependencies as well. We are using this [eslint rule](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-extraneous-dependencies.md) in our project to enforce to only import dependencies in our application. But this rule clashes with the enforcement of the electron-builder. Electron is a normal dependency in a classic electron app. (Even if it is a devDependency, for bundling, as well)

**Comment by robertpatrick** [comment]
Both electron and electron-builder (and other packages like electron-notarize) should only be declared as devDependencies.  Declaring them as dependencies will impact your packaged applications in undesirable ways.  Just swallow this as how it has to be and move on to more important issues... 

> Electron is a normal dependency in a classic electron app.

No, it is not.   For example, VS Code properly lists electron as a devDependency only.

https://github.com/microsoft/vscode/blob/main/package.json

Likewise, our project does the same: https://github.com/oracle/weblogic-toolkit-ui/blob/main/electron/package.json

**Comment by mmaietta** [comment]
Thank you @robertpatrick for the explanation, I appreciate it :)

**Comment by mifozski** [comment]
I have `electron` listed only in the `"bundledDependencies"` field in package.json (for eslint reasons) and still get the error. If I remove it everything works fine.
My expectation is that I still can list `electron` in the `bundledDependencies` since it doesn't affect the bundle output.

**Comment by robertpatrick** [comment]
@mifozski What eslint reasons?  We declare electron as a devDependency and use eslint on our code without any issues.

**Comment by mifozski** [comment]
@robertpatrick When I try to import from "electron" in the preload script file I get this error from `import/no-extraneous-dependencies` rule:

![image](https://github.com/electron-userland/electron-builder/assets/3611730/23318cbd-79c9-427b-a97f-977487d2c52a)

I know that I can disable the rule for this specific file completely, but if I want to disable it only for `electron` import there's no way to do it via eslintrc config, and one of the options would be to add it to the `bundledDependencies` field in the package.json (https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md#options)

**Comment by robertpatrick** [comment]
Add a comment in the code?

```javascript
// eslint-disable-next-line import/no-extraneous-dependencies
import { contextBridge, IpcRenderer, IpcRendererEvent } from ‘electron’;
```

**Comment by mifozski** [comment]
I can do it, but still seems like it this should be fixed on electron-builder side. It seems like it's checking whether `electron` is in any other section other than `devDependencies` not whether it's not in `dependencies` which is too strict for what is worth. For example, it could also be in `peerDependencies` section which would also not affect the bundle, but I haven't actually checked if it's going to break electron-builder.

**Comment by mifozski** [comment]
I can provide a PR if it's OK, seems like an easy thing to fix.

**Comment by mifozski** [comment]
Ok, scratch that. I misunderstood what `bundledDependencies` do and seems like they're still bundled as the normal `dependencies`: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bundledependencies.
So updating the ESLint config would be a way to go here.
