### ISSUE TITLE
MSI custom `APPLICATIONFOLDER` param no longer works

### ISSUE THREAD

**Issue by davej** [electron-userland/electron-builder#7193]
* **Electron-Builder Version**: 23.5.0 (previous working version was `22.14.13`)

* **Node Version**: `16.15.1`

* **Electron Version**: `19.0.4`

* **Target**: Windows

Previously it was possible to specify a custom install location for MSI by using the following command:
```
msiexec /i "<MSI Download File>" APPLICATIONFOLDER="<Desired install folder>"
```

This was useful when combined with unattended installs. This seems to have broken in a recent version of Electron Builder. Any idea what might be going on here? Happy to jump in and PR this if anybody has a few pointers and why it no longer works.

**Comment by mmaietta** [comment]
I'm seeing this change in the (very large) diff
```
-      installationDirectoryWixName: getWindowsInstallationDirName(appInfo, commonOptions.isPerMachine === true),
+      installationDirectoryWixName: getWindowsInstallationDirName(appInfo, commonOptions.isAssisted || commonOptions.isPerMachine === true),
```

Can you try setting `isAssisted: false` in your config? I'm not seeing much else in the diff that could impact this. I saw your comment on PR #6550 as well

**Comment by aplum** [comment]
@davej Do you only need this to work for unattended installs? I just tried with one of my MSIs (built using electron-builder v23.0.0-alpha.0) using `/qn` and it installed to the custom dir (full command: `msiexec /i "C:\path\to\app.msi" APPLICATIONFOLDER="C:\test" /qn`).

Do you also need the custom APPLICATIONFOLDER to work when using the installer GUI?

**Comment by davej** [comment]
@aplum It is a customer who is using the command, not me personally. I'll reach out to them to see if this is for unattended installs. Thanks so much for your help, I'll report back.

@mmaietta: will try your solution if @aplum's suggestion doesn't work.
