### ISSUE TITLE
Window takes 1-2 seconds to appear after packaging

### ISSUE THREAD

**Issue by christianlundberg** [electron-userland/electron-builder#7195]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: 14.19.2

* **Electron Version**: 20.0.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: macOS

I'm migrating an electron app from vanilla js to react/typescript/webpack. I'm basically creating a bundle with webpack for a specific window which more or less consists of react, material ui and a small component. When the app is running locally, I click a menu item from the main window to open this new window which happens pretty much instantly. The problem is that after I build a dmg and run it, it seems noticeably slower because the window takes 1-2 seconds to appear after clicking the same menu item.

```
...
browserWindow.loadURL(buildWindowUrl());

browserWindow.once('ready-to-show', () => {
  browserWindow.webContents.send('send-component-data', data);
  browserWindow.show();
});
```

There aren't any errors whatsoever during build or when the app is running, it's just that the window takes so much longer to appear which is really weird because in theory it should be faster after the code has been bundled and minimized.

**Comment by mmaietta** [comment]
This really has nothing to do with electron-builder. It's simply bundling an asar with your resources, which is read by electron. The rest of the logic is packaging your app in a distributable (dmg, zip, etc.) and electron-updater integration.
Best guess is that reading the asar from the file system takes longer than reading js files directly.
