### ISSUE TITLE
document for both 32-bit and 64-bit windows release

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#720]
I see #359 there is lot of messy in dual-arch and `For windows consider only distributing 64-bit versions` in document.
But most of my users are not experienced at computer, they don't know to upgrade their os arch and 32-bit is still in high-percentage. then .. I can't just provide 64-bit only version.

Is there any way to provide both 32-bit and 64-bit windows release?
I see #190 there is a `RELEASES-ia32` fix to do that, but I can't find any document to use that.

1. which server should I use, any prefer between  `Nuts`, `Electron Release Server` or `Squirrel Updates Server` ? 
2. I use `AppVeyor`, `Publishing Artifacts`, and `remoteRelease` with github releases. as wiki exampled [appveyor.yml](https://github.com/develar/onshape-desktop-shell/blob/master/appveyor.yml) it only contains 64-bit build. what should I do if I want AppVeyor build both version and push them to github without conflict?
3. should I use `NSIS` ? (and to do what)

**Comment by develar** [comment]
NSIS allows you to build ONE installer that contains both arch. #529 Will be fixed soon.

> which server should I use, any prefer between Nuts, Electron Release Server or Squirrel Updates Server

Squirrel Updates Server if you decide to use Squirrel.Windows. But I suggest to use NSIS — #529 will new fixed next week.
