### ISSUE TITLE
The systray icon still exists when electron process is killed by cmd taskkill

### ISSUE THREAD

**Issue by qq790880208** [electron-userland/electron-builder#7204]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 14.18.0

* **Electron Version**:13.5.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: Window 10/11

The systray icon still exists when electron process is killed by cmd taskkill

**Comment by mmaietta** [comment]
That's not an electron-builder bug, it has nothing to do with runtime process. Seems like an electron bug
