### ISSUE TITLE
minimatch ReDoS vulnerability

### ISSUE THREAD

**Issue by Itzdan0ul** [electron-userland/electron-builder#7206]
* **Electron-Builder Version**:  23.6.0

### Expected Behavior
No vulnerabilities reported.

### Actual Behavior

Vulnerabilities when doing `yarn audit` or `npm audit`:

![redos_vulnerability](https://user-images.githubusercontent.com/69698529/197262319-a85e4052-c43d-437e-8fa6-c77539321b5e.JPG)

**Comment by mmaietta** [comment]
Please open a ticket with upstream dependency @electron/universal https://github.com/electron/universal and link back here for us to track. As it currently stands, I'm unable to resolve this specifically from electron-builder's side

**Comment by SheharyarSMAdil** [comment]
I am also getting the same issue, after installing an electron-forge.

**Comment by mmaietta** [comment]
Please open a ticket with upstream @electron/universal package. There's nothing electron-builder can do here

**Comment by downace** [comment]
> There's nothing electron-builder can do here

Vulnerability was fixed in `@electron/universal@1.3.4`, but we can't get use of this fix because electron-builder (at least latest stable 23.6.0) requires exactly 1.2.1 version of `@electron/universal`.

Will there be a patch that updates required version?

**Comment by mmaietta** [comment]
Yes, I can add that into the next `24-alpha` release when I have a chance, work is a bit overloading atm.
Happy to accept a community contribution though 😉
