### ISSUE TITLE
Question: Is there value putting together a PR for non-proprietary FFmpeg download?

### ISSUE THREAD

**Issue by baparham** [electron-userland/electron-builder#7210]
Looking for some feedback if it's worth putting together a PR to support downloading the non-proprietary FFmpeg binary that the Electron org releases with each version of Electron.

This can be accomplished with some basic `afterPack` scripting to find the asset, and replace the current FFmpeg library in the unpacked folder, but I'm curious if this would be valuable as a direct option that just handles this in the standard flow.

Thanks for the feedback!

**Comment by mmaietta** [comment]
I not familiar with FFmpeg binary or its usage (or why it needs to be replaced). Could you elaborate on what that provides?

**Comment by baparham** [comment]
Electron ships by default with an ffmpeg.dll (on windows at least...libffmpeg.so on linux) to support [audio/video in the browser window](https://www.chromium.org/audio-video/), and from what I can tell, you can't just remove it if you don't need it (not without compiling electron yourself).

The default dll contains proprietary h264 codecs, which may cause issues for most commercial apps shipping electron, so the Electron team releases another version of ffmpeg.dll that does not contain proprietary codecs. These are available alongside the normal assets for each release and can serve as drop in replacements for the default dll that ships with normal electron release assets.

Some related commentary on the subject: https://github.com/electron/electron/issues/13445

AFAIK the h.264 codec is really the only one in the default ffmpeg library that could cause issues, and of course I'm not a lawyer, but it seems like using the "non proprietary" ffmpeg build that the electron team releases would mitigate some of the risk for developers of electron apps.

Making it easier for electron-builder users to incorporate this into their flows seems like a helpful strategy, since helping the ecosystem comply with licensing and patent obligations likely helps us all in the long run.

**Comment by mmaietta** [comment]
Very interesting! I did not know of that.

Re: the FFmpeg, is it already being downloaded with the current electron-builder implementation? IIRC, it's currently being downloaded using an upstream GoLang library app-builder-bin.

**Comment by baparham** [comment]
I am actually not sure if the current `electron-builder`/`app-builder-lib` implementation downloads the target electron asset (I believe it does) or just reuses what has already been downloaded/installed into node_modules. Since you can cross-"compile" with electron-builder, I suspect it downloads the electron dist asset directly itself.

Either way, the original FFmpeg lib files are already included with that single archive that is downloaded (e.g. https://github.com/electron/electron/releases/download/v21.2.0/electron-v21.2.0-linux-x64.zip or https://github.com/electron/electron/releases/download/v21.2.0/electron-v21.2.0-win32-x64.zip) just like the libGLESv2 or libEGL dlls are also included by default.

**Comment by baparham** [comment]
This ended up way more detailed than I intended, so I've tried to highlight what the actual use case looks like, with one possible solution later on if we care to venture into discussion in that space yet.

I gave this a brief dive into the code, and confirmed that the current default behavior (if you haven't overridden the `electronDist` config option) is that we use the `app-builder-bin` binary (as you mentioned) to download and unpack the electron distributable zip file.

#### Use case summary
The high level use case would be some hypothetical config flag, let's call it `downloadNonProprietaryFFmpeg` or `downloadAlternateFFmpeg` or something, which if set to `true` would work only if `electronDist === null` (i.e. the user didn't point to some other place to get the electron distributable, like a custom built version, etc). It would have the `app-builder-bin` additionally download the ffmpeg asset released by Electron (for the same version, platform and arch as the electron distributable zip file, of course) and unpack it into the same place we unpack the electron distributable zip. Default would be `false`.

#### Solution space
Looking into one possible solution to satisfy this use case...

The happy path I see, without covering edge cases, would probably be to add a _second_ `ElectronDownloadOptions` object to the value we pass the `--configuration` parameter to the app-builder-bin call in the `ElectronFramework`:

https://github.com/electron-userland/electron-builder/blob/d42fa79a8bdacd81565bfab37db7f97e49a5a185/packages/app-builder-lib/src/electron/ElectronFramework.ts#L183

which would replicate the original `options` but override the `customFilename` property to be `ffmpeg-${options.version}-${options.platform}-${options.arch}.zip` and then the ffmpeg zip would (hopefully) just get unpacked into the same output directory as the electron dist zip got unpacked into.

This is based on the assumption that in [the app-builder-bin code](https://github.com/develar/app-builder/blob/master/pkg/electron/electronUnpack.go) the configuration we pass to it can be an array of `ElectronDownloadOptions` instead of just a single one. Right now it looks like we pass it an array, but with just the single `[options]` object. This potential enhancement would rely on being able to specify an additional `options` object, like `[options, ffmpegOptions]`

**Comment by baparham** [comment]
@mmaietta what do you think about this option in #7247 ?
