### ISSUE TITLE
Unavailable transitive dependencies (@types/keyv) in 24.0.0-alpha.1

### ISSUE THREAD

**Issue by raksooo** [electron-userland/electron-builder#7211]
* **Electron-Builder Version**: 24.0.0-alpha.1

* **Node Version**: 16.16.0

* **Electron Version**: 21.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, macOS (haven't tested Linux)

We've tried upgrading from 23.3.3 to 24.0.0-alpha.1. Sadly we were greeted by the following error:
```
error TS2688: Cannot find type definition file for 'keyv'.
  The file is in the program because:
    Entry point for implicit type library 'keyv'
TypeScript: 1 options error
TypeScript: emit succeeded (with errors)
[15:58:36] 'compile-scripts' errored after 17 s
[15:58:36] Error: TypeScript: Compilation failed
    at Output.mightFinish (C:\Users\oskar\mullvadvpn-app\gui\node_modules\gulp-typescript\release\output.js:130:43)
    at C:\Users\oskar\mullvadvpn-app\gui\node_modules\gulp-typescript\release\output.js:43:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It looks like `@types/keyv` and `@types/cacheable-request` were deprecated and had an update which is just an empty package. `@types/cacheable-request` has specified the `@types/keyv` version to `*` which leads npm to use the latest version, which is empty. We tried overriding it with the following in `package.json`:
```
"override": {
  "@types/keyv": "4.2.0"
},
``` 
It did solve the issue on macOS but not on Windows for some reason.

We suspect the best solution would be for `electron-rebuild` to depend on `got` version 12+ which removes the dependency on `@types/cacheable-request`. Here's the dependecy tree from `electron-builder` down to `@types/cacheable-request`:
```
└─┬ electron-builder@24.0.0-alpha.1
  └─┬ app-builder-lib@24.0.0-alpha.1
    └─┬ electron-rebuild@3.2.9
      └─┬ got@11.8.5
        └─┬ @types/cacheable-request@6.0.2
          └── @types/keyv@4.2.0
```

We'll report it to `electron-rebuild` as well, but as long as this issue remains, the electron builder alpha is unusable unless there's another solution?

**Comment by mmaietta** [comment]
I had a feeling the alpha version incorporating electron-rebuild would have a few issues arise. It worked with some of my local projects, but they're more simple in configuration.
I'll see if there's a way to resolve this quickly in electron-builder, but it seems it would indeed be best resolved by upstream electron-rebuild

**Comment by mmaietta** [comment]
Can you try `"@types/keyv": "3.1.4"` in the overrides section?

**Comment by raksooo** [comment]
Yes, it works with `3.1.4`. I've only tested this on Windows now.

**Comment by mmaietta** [comment]
Can you please test with `v24.0.0-alpha.3`? I've added a `@types/keyv` override in the pnpm dependency section. Not sure if it carries over into the npm artifact or not, or whether I need to add it directly as a dependency to force pin to.

**Comment by mmaietta** [comment]
I see. Yes, I guess since it is a prod `dependencies` section of electron-builder, I can't provide an override in the package.json, it'll need to be overridden by your project directly.

**Comment by mmaietta** [comment]
For others that find this discussion, please use the solution as described here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793#issuecomment-1285167695

There's no way for this to be fixed on the electron-builder side

**Comment by raksooo** [comment]
`@types/cacheable-request` has been fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63097 and now `24.0.0-alpha.3` seems to be working fine :+1:
