### ISSUE TITLE
Native dependencies are not built when using yarn workspaces in 24.0.0-alpha.1

### ISSUE THREAD

**Issue by gzdunek** [electron-userland/electron-builder#7212]
* **Electron-Builder Version**: 24.0.0-alpha.1

* **Node Version**: 16.18.0

* **Electron Version**: 21.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, Windows, Linux

Project structure: monorepo (yarn workspaces).
It seems that after migrating to `electron-rebuild` the native dependencies are no longer rebuilt. `electron-builder install-app-deps` only looks for modules in `node_modules` of the workspace, but of course it doesn't find any (because they are kept in the root `node_modules`). 
CLI command `electron-rebuild` handles this situation by providing [`projectRootPath`](https://github.com/electron/electron-rebuild/blob/6f94aaace0ea72a342e9249328293644caec5723/src/cli.ts#L62) to `rebuild()`. If this option is not passed, the search for modules [stops at the directory where the app `package.json` is located](https://github.com/electron/electron-rebuild/blob/6f94aaace0ea72a342e9249328293644caec5723/src/search-module.ts#L8). 
It would be great if `electron-builder` could populate this field using a function similar to [`getProjectRootPath()`](https://github.com/electron/electron-rebuild/blob/6f94aaace0ea72a342e9249328293644caec5723/src/search-module.ts#L76).

As a workaround, [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) option can be used in yarn workspaces to prevent some dependencies from being hoisted to the project's root.

**Comment by mmaietta** [comment]
Hmmm I had a feeling the alpha version incorporating electron-rebuild would have a few issues arise. It worked with some of my local projects, but they're more simple in configuration.
I'll take a look at this asap

**Comment by mmaietta** [comment]
Would you mind generating an electron-quick-start monorepo project utilizing a yarn workspace such that I can repro this with?

**Comment by mmaietta** [comment]
Can you try this patch? Curious if it'll do the trick
```
diff --git a/node_modules/app-builder-lib/out/util/yarn.js b/node_modules/app-builder-lib/out/util/yarn.js
index 41fde4d..f278239 100644
--- a/node_modules/app-builder-lib/out/util/yarn.js
+++ b/node_modules/app-builder-lib/out/util/yarn.js
@@ -5,8 +5,9 @@ const builder_util_1 = require("builder-util");
 const fs_extra_1 = require("fs-extra");
 const os_1 = require("os");
 const path = require("path");
-const electronRebuild = require("electron-rebuild");
 const electronVersion_1 = require("../electron/electronVersion");
+const electronRebuild = require("electron-rebuild");
+const searchModule = require("electron-rebuild/lib/src/search-module");
 async function installOrRebuild(config, appDir, options, forceInstall = false) {
     let isDependenciesInstalled = false;
     for (const fileOrDir of ["node_modules", ".pnp.js"]) {
@@ -104,7 +105,7 @@ function installDependencies(appDir, options) {
     });
 }
 async function nodeGypRebuild(arch) {
-    return rebuild(process.cwd(), false, arch);
+    return rebuild(await searchModule.getProjectRootPath(process.cwd()), false, arch);
 }
 exports.nodeGypRebuild = nodeGypRebuild;
 function getPackageToolPath() {
```

**Comment by gzdunek** [comment]
Thanks for your response! 
I tried the patch, but it doesn't help :( 

Here is the project using yarn workspaces https://github.com/gzdunek/electron-quick-start-monorepo. 

When you run `yarn build-electron-app-native-deps` the output is:
```bash
$ electron-builder install-app-deps
  • electron-builder  version=24.0.0-alpha.1
  • executing electron-rebuild  appDir=/Users/grzegorz/code/electron-quick-start-monorepo/packages/electron-app arch=arm64
✨  Done in 0.60s.
```
but is should be:
(I provided `projectRootPath: '/Users/grzegorz/code/electron-quick-start-monorepo/'` manually) 
```bash
$ electron-builder install-app-deps
  • electron-builder  version=24.0.0-alpha.1
  • executing electron-rebuild  appDir=/Users/grzegorz/code/electron-quick-start-monorepo/packages/electron-app arch=arm64
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
✨  Done in 1.39s.
```
Let me know if you need anything else.

**Comment by mmaietta** [comment]
Thanks for the sample repo! Was able to get it working locally. Please try v24.0.0-alpha.2

**Comment by gzdunek** [comment]
Thanks, `v24.0.0-alpha.2` solved the issue!
