### ISSUE TITLE
error when using electron-builder for mac in linux

### ISSUE THREAD

**Issue by buivietqng02** [electron-userland/electron-builder#7225]
when build, i got this error:  

• electron-builder  version=23.6.0 os=5.15.0-52-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  ⨯ Cannot find module 'dmg-license'
Require stack:
- /home/viet/iptp/xm-desktop/node_modules/dmg-builder/out/dmgLicense.js
- /home/viet/iptp/xm-desktop/node_modules/dmg-builder/out/dmg.js
- /home/viet/iptp/xm-desktop/node_modules/dmg-builder/out/dmgUtil.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/node_modules/app-builder-lib/out/macPackager.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/node_modules/app-builder-lib/out/packager.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/node_modules/app-builder-lib/out/index.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/out/builder.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/out/cli/cli.js
- /home/viet/iptp/xm-desktop/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
---------------------------------------------------------
if i try to install dmg-license in linux, i got error
iet@viet-Latitude-E6540:~/iptp/xm-desktop$ npm instal dmg-license
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for iconv-corefoundation@1.1.7: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

**Comment by mmaietta** [comment]
You can only build mac apps on mac build machines.

**Comment by coreybruce** [comment]
Lmao this is so stupid, I guess that means hardly anyone will make Mac apps since not everyone has a mac or will buy one just to be able to make a Mac version or bother to ¯\_(ツ)_/¯

**Comment by coreybruce** [comment]
Wouldn't this be electron-builders fault? Electron-packager can build for Mac OS

**Comment by mmaietta** [comment]
How do you plan on signing and notarizing the mac app without being on macOS? AFAIK, those codesign tools are only in macos

**Comment by coreybruce** [comment]
> How do you plan on signing and notarizing the mac app without being on macOS? AFAIK, those codesign tools are only in macos

I guess I won't, don't have a Mac so I wouldn't bother to, I can build my apps using electron-packager but why can't we just build it and not sign it if we're not on a Mac instead of informing that it doesn't work?

**Comment by buivietqng02** [comment]
you can build for mac on linux if you specify: "target": "mas" and do not sign the app

**Comment by coreybruce** [comment]
Ah ok so if I do that target instead I can build on Linux? Il leave to try that out. Thanks for letting me know
