### ISSUE TITLE
Question/request: aborting an upgrade *after* download completes?

### ISSUE THREAD

**Issue by danenania** [electron-userland/electron-builder#7226]
Hi! Thanks for all your hard work.

We currently have a user-initiated upgrade, and would like to keep it that way, but as the downloads are pretty large, the upgrades are quite slow.

If we could automatically download upgrades in the background, but wait for user approval to apply the upgrade, this would offer the best of both worlds. We'd keep user-approved upgrades, but the user wouldn't have to sit and wait for them to complete.

Currently, it doesn't seem that this is possible, since after `update-downloaded` is fired, the next restart of the app will use the upgraded version, with no way to opt-out. 

Is that right, or is there some way I'm not aware of to abort an already-downloaded upgrade? Or to not apply an upgrade on restart until `quitAndInstall` is called explicitly?

If it can't be done currently, how difficult would it be to make this possible? I'm  willing to put together a PR, but want to be sure it's actually doable first given the architecture. Perhaps someone can point me in the right direction?

**Comment by danenania** [comment]
Thanks @mmaietta, `autoInstallOnAppQuit` sounds like it might be exactly what I'm missing. So just to be sure I'm understanding, you're saying that if `autoInstallOnAppQuit` is set to `false` and `quitAndInstall` isn't called, the upgrade will never be applied?

**Comment by mmaietta** [comment]
AFAIK, yes, that's the expected behavior. I've not worked with that flow before tbh

**Comment by danenania** [comment]
Great, I'll this out. Thanks again.
