### ISSUE TITLE
error while loading shared libraries: libgbm.so.1

### ISSUE THREAD

**Issue by ThenWang** [electron-userland/electron-builder#7234]
* **Electron-Builder Version**:  v23.0.3

* **Node Version**:  v16.13.2

* **Electron Version**: v21.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: arm

It can be packaged normally using the command `electron-builder --armv7l`. But when the application is opened, an error `error while loading shared libraries: libgbm.so.1: cannot open shared object file` is reported. Although it work well when I adjust electron to v3.1.8, I think it maybe an issue with electron-builder.

**Comment by mmaietta** [comment]
If the applicatiion isn't running properly when being opened, then you need to add to the requirements saying that the dep is needed. Seems like this is a pointer as to the lib your app requires to run https://stackoverflow.com/questions/67407104/error-while-loading-shared-libraries-libgbm-so-1-cannot-open-shared-object-fil#comment127682006_67407105
Use `depends` should be the right direction. 
https://www.electron.build/configuration/linux

Overall, closing as this isn't a problem within electron-builder

**Comment by simlu** [comment]
@ThenWang I have the same problem. Probably doing some wrong... Did you ever resolve this?
