### ISSUE TITLE
electron-updater: download-progress event not firing

### ISSUE THREAD

**Issue by myesn** [electron-userland/electron-builder#7235]
**os:** Windows 10 21H2 x64

**packages.json:**
```json
  "dependencies": {
    "electron": "^21.2.2",
    "electron-builder": "^23.6.0",
    "electron-log": "^4.4.8",
    "electron-updater": "^5.3.0"
  }
```

**electron/main.ts:**
```ts
import { autoUpdater } from 'electron-updater';
import log from 'electron-log';

autoUpdater.logger = log;
autoUpdater.autoDownload = true;

win.webContents.on('did-finish-load', async () => {
  await autoUpdater.checkForUpdates();
});

autoUpdater.on('download-progress', (info) => {
  console.log('download-progress', info);
  win?.webContents.send('download-progress', info);
});
```

`update-available` and `update-downloaded` all trigger successfully, but the `download-progress` event does not trigger.

**Comment by myesn** [comment]
The reason is that the file server does not return the `Content-Length` in the response header.

**Comment by Asplitline** [comment]
> The reason is that the file server does not return the `Content-Length` in the response header.

how to solve it ? Add content-length to the request header ?

**Comment by keysoutlet** [comment]
Got the same problem even with content-length header present.
```
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
content-type: application/x-7z-compressed
content_disposition: filename=/win/ks-manager-1.1.6-x64.nsis.7z
date: Mon, 06 Feb 2023 14:04:05 GMT
etag: "63e0fbf2-4ba64b2"
last-modified: Mon, 06 Feb 2023 13:09:06 GMT
server: nginx
content-length: 79324338
```

Full log:
```
[2023-02-06 15:32:44.850] [info]  (update)       Checking for update
[2023-02-06 15:32:45.105] [info]  (update)       Found version 1.1.6 (url: ks-manager_1.1.6.exe, ks-manager_x64_1.1.6.exe, ks-manager_ia32_1.1.6.exe)
[2023-02-06 15:32:45.108] [info]  (update)       Downloading update from ks-manager_1.1.6.exe, ks-manager_x64_1.1.6.exe, ks-manager_ia32_1.1.6.exe
[2023-02-06 15:32:45.114] [debug] (update)       updater cache dir: C:\Users\ainz\AppData\Local\ks-manager-updater
[2023-02-06 15:33:13.492] [info]  (update)       File has 56 changed blocks
[2023-02-06 15:33:13.498] [debug] (update)       [
  {
    "kind": 1,
    "start": 0,
    "end": 9582
  },
  {
    "kind": 0,
    "start": 9582,
    "end": 15294633
  },
  {
    "kind": 1,
    "start": 15294633,
    "end": 16336244
  },
  {
    "kind": 0,
    "start": 16336267,
    "end": 71269042
  },
  {
    "kind": 1,
    "start": 71269019,
    "end": 71301787
  },
  {
    "kind": 0,
    "start": 71301810,
    "end": 71313393
  },
  {
    "kind": 1,
    "start": 71313370,
    "end": 71375484
  },
  {
    "kind": 0,
    "start": 71375514,
    "end": 79237480
  },
  {
    "kind": 1,
    "start": 79237450,
    "end": 79240261
  }
]
[2023-02-06 15:33:13.531] [info]  (update)       Full: 77,465.17 KB, To download: 1,121.96 KB (1%)
[2023-02-06 15:33:57.822] [info]  (update)       New version 1.1.6 has been downloaded to C:\...
```

**Comment by xiopt** [comment]
Got the same problem even with content-length header present.
```
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
content-type: application/x-7z-compressed
content_disposition: filename=/win/ks-manager-1.1.6-x64.nsis.7z
date: Mon, 06 Feb 2023 14:04:05 GMT
etag: "63e0fbf2-4ba64b2"
last-modified: Mon, 06 Feb 2023 13:09:06 GMT
server: nginx
content-length: 79324338
```

Full log:
```
[2023-02-06 15:32:44.850] [info]  (update)       Checking for update
[2023-02-06 15:32:45.105] [info]  (update)       Found version 1.1.6 (url: ks-manager_1.1.6.exe, ks-manager_x64_1.1.6.exe, ks-manager_ia32_1.1.6.exe)
[2023-02-06 15:32:45.108] [info]  (update)       Downloading update from ks-manager_1.1.6.exe, ks-manager_x64_1.1.6.exe, ks-manager_ia32_1.1.6.exe
[2023-02-06 15:32:45.114] [debug] (update)       updater cache dir: C:\Users\ainz\AppData\Local\ks-manager-updater
[2023-02-06 15:33:13.492] [info]  (update)       File has 56 changed blocks
[2023-02-06 15:33:13.498] [debug] (update)       [
  {
    "kind": 1,
    "start": 0,
    "end": 9582
  },
  {
    "kind": 0,
    "start": 9582,
    "end": 15294633
  },
  {
    "kind": 1,
    "start": 15294633,
    "end": 16336244
  },
  {
    "kind": 0,
    "start": 16336267,
    "end": 71269042
  },
  {
    "kind": 1,
    "start": 71269019,
    "end": 71301787
  },
  {
    "kind": 0,
    "start": 71301810,
    "end": 71313393
  },
  {
    "kind": 1,
    "start": 71313370,
    "end": 71375484
  },
  {
    "kind": 0,
    "start": 71375514,
    "end": 79237480
  },
  {
    "kind": 1,
    "start": 79237450,
    "end": 79240261
  }
]
[2023-02-06 15:33:13.531] [info]  (update)       Full: 77,465.17 KB, To download: 1,121.96 KB (1%)
[2023-02-06 15:33:57.822] [info]  (update)       New version 1.1.6 has been downloaded to C:\...
```

**Comment by mx1120** [comment]
> Got the same problem even with content-length header present.
> 
> ```
> HTTP/2 200
> accept-ranges: bytes
> access-control-allow-origin: *
> content-type: application/x-7z-compressed
> content_disposition: filename=/win/manager-1.1.6-x64.nsis.7z
> date: Mon, 06 Feb 2023 14:04:05 GMT
> etag: "63e0fbf2-4ba64b2"
> last-modified: Mon, 06 Feb 2023 13:09:06 GMT
> server: nginx
> content-length: 79324338
> ```
> 
> Full log:
> 
> ```
> [2023-02-06 15:32:44.850] [info]  (update)       Checking for update
> [2023-02-06 15:32:45.105] [info]  (update)       Found version 1.1.6 (url: manager_1.1.6.exe, manager_x64_1.1.6.exe, manager_ia32_1.1.6.exe)
> [2023-02-06 15:32:45.108] [info]  (update)       Downloading update from manager_1.1.6.exe, ks-manager_x64_1.1.6.exe, ks-manager_ia32_1.1.6.exe
> [2023-02-06 15:32:45.114] [debug] (update)       updater cache dir: C:\Users\aguy\AppData\Local\manager-updater
> [2023-02-06 15:33:13.492] [info]  (update)       File has 56 changed blocks
> [2023-02-06 15:33:13.498] [debug] (update)       [
>   {
>     "kind": 1,
>     "start": 0,
>     "end": 9582
>   },
>   {
>     "kind": 0,
>     "start": 9582,
>     "end": 15294633
>   },
>   {
>     "kind": 1,
>     "start": 15294633,
>     "end": 16336244
>   },
>   {
>     "kind": 0,
>     "start": 16336267,
>     "end": 71269042
>   },
>   {
>     "kind": 1,
>     "start": 71269019,
>     "end": 71301787
>   },
>   {
>     "kind": 0,
>     "start": 71301810,
>     "end": 71313393
>   },
>   {
>     "kind": 1,
>     "start": 71313370,
>     "end": 71375484
>   },
>   {
>     "kind": 0,
>     "start": 71375514,
>     "end": 79237480
>   },
>   {
>     "kind": 1,
>     "start": 79237450,
>     "end": 79240261
>   }
> ]
> [2023-02-06 15:33:13.531] [info]  (update)       Full: 77,465.17 KB, To download: 1,121.96 KB (1%)
> [2023-02-06 15:33:57.822] [info]  (update)       New version 1.1.6 has been downloaded to C:\...
> ```

Have you solved it？
