### ISSUE TITLE
Fork electron-builder to test in Windows App Store/Prod?

### ISSUE THREAD

**Issue by ethielc** [electron-userland/electron-builder#7237]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: v16.15.0

* **Electron Version**: 19.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows App Store

Hi,

I'd like to test some changes in electron-builder startup for Windows App Store, the problem is that in order to test the functionality I need to generate a signed build from Windows and I need an electron-builder for "prod", is there a way to made this tests?
Our case is that we want to include to our app the startup extension and with the existing default value (true) the app is set by default to startup for users that update from version that doesn't have the feature to version that has it, and it seems this breaks the Microsoft Policy
We already have in our code the logic to handle our cases, but its useless if the app is not launched yet after updating, the app is set to true and we can't handle it from outside apart of this change that we need to test
The changes (testing purpose) that I need to do is set the value to false(1) and/or add an extra config value to appx(2) that allows to determine the value, something like

1. if (isAddAutoLaunchExtension) {
      extensions += `
        <desktop:Extension Category="windows.startupTask" Executable="${executable}" EntryPoint="Windows.FullTrustApplication">
          <desktop:StartupTask TaskId="SlackId" Enabled="false" DisplayName="${displayName}" />
        </desktop:Extension>`
   }
2. if (isAddAutoLaunchExtension) {
      extensions += `
        <desktop:Extension Category="windows.startupTask" Executable="${executable}" EntryPoint="Windows.FullTrustApplication">
          <desktop:StartupTask TaskId="SlackId" Enabled=${valueFromConfig ?? true} DisplayName="${displayName}" />
        </desktop:Extension>`
    }

Could you help me with instructions to make this possible? I think dev environment doesn't work for Windows App Store since I need to sign the app before use it
If it works I could made a PR, but I'm not familiar in how to build electron-builder with my changes
Thanks!

**Comment by mmaietta** [comment]
This is the best way to contribute and a manner with which to test in your local project without publishing yourr own fork 🙂 
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md

**Comment by ethielc** [comment]
Hi @mmaietta 
Thanks for your reply, do you know if dev environment works for Windows App Store? The test I want to do is WAS specific
This is the yarn.lock file for electron-builder using yalc

```
"electron-builder@file:.yalc/electron-builder":
  version "23.1.0"
  dependencies:
    "@types/yargs" "^17.0.1"
    app-builder-lib "23.1.0"
    builder-util "23.0.9"
    builder-util-runtime "9.0.2"
    chalk "^4.1.1"
    dmg-builder "23.1.0"
    fs-extra "^10.0.0"
    is-ci "^3.0.0"
    lazy-val "^1.0.5"
    read-config-file "6.2.0"
    update-notifier "^5.1.0"
    yargs "^17.0.1"
```
As you can see, app-builder-lib dependency has `"23.1.0"` instead of something like `file:../app-builder-lib`, and the things I needed to change were in that package, app-builder-lib

**Comment by mmaietta** [comment]
As long as you performed this step in your test project, then all deps should be linked correctly for a monorepo AFAICT
```
yalc link app-builder-lib builder-util builder-util-runtime dmg-builder electron-builder electron-publish electron-builder-squirrel-windows electron-forge-maker-appimage electron-forge-maker-nsis electron-forge-maker-nsis-web electron-forge-maker-snap electron-updater
```

**Comment by ethielc** [comment]
I recently sign a WAS build and it seems to be working, at least by checking the manifest. I need to do some tests to confirm and if it work I'll made a PR
Thanks!

**Comment by ethielc** [comment]
I found a better approach for what I wanted (custom extensions), no pr is needed (although I think it would be great to allow through package.json modify the TaskId to avoid having SlackStartup in every app if that extension is used)
