### ISSUE TITLE
How to disable electron generate zip.blockmap?

### ISSUE THREAD

**Issue by Eve-Sama** [electron-userland/electron-builder#7242]
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/tmODO.png

I am using electron-builder to build mac and windows app. Abouve is my electron build output directory. I don't need autoupdater. So I just wanna `.dmg` and `.exe` files. How can I set `builder` config to diable electron generate those useless files(yal、yaml、zip、zip.blockmap)?

Below is my package.json
```json
  "build": {
    "appId": "we-media-helper",
    "copyright": "Copyright © 2022 Eve-Sama",
    "generateUpdatesFilesForAllChannels": true,
    "directories": {
      "output": "./dist/installer"
    },
    "mac": {
      "target": {
        "target": "default",
        "arch": [
          "arm64",
          "x64",
          "universal"
        ]
      },
      "icon": "./assets/icons/mac-dock.icns",
      "publish": {
        "owner": "Eve-Sama",
        "repo": "we-media-helper",
        "provider": "github"
      }
    },
    "dmg": {
      "writeUpdateInfo": false
    },
    "nsis": {
      "differentialPackage": false,
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "./assets/icons/win-taskbar.ico",
      "uninstallerIcon": "./assets/icons/win-taskbar.ico",
      "installerHeaderIcon": "./assets/icons/win-taskbar.ico",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "artifactName": "${productName}_Setup_${version}.${ext}"
    },
    "win": {
      "icon": "./assets/icons/win-taskbar.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "files": [
      "**/*",
      "!dist/installer",
      "!**/*.ts",
      "!**/*.tsx",
      "!src/",
      "!public/",
      "!.eslintignore",
      "!.eslintrc.js",
      "!.gitignore",
      "!.prettierrc",
      "!gulpfile.ts",
      "!LICENSE",
      "!package-lock.json",
      "!README.md",
      "!tsconfig.json",
      "!yarn.lock"
    ],
    "extends": null
  },
```

And I have another question. As you can see, I set `mac.target.arch` as `['arm64', 'x64', 'universal']`. And output directory contains folder `mac` rather than `mac-x64`. why? How can I set it as `mac-x64`

**Comment by Eve-Sama** [comment]
There is a solution prevent `.zip` files generated.
```json
    "mac": {
      "target": {
        "target": "dmg"
      },
    },
    "win": {
      "target": [
        {
          "target": "nsis"
        }
      ]
    },
```

But don't know how to disable `yml`、`yaml` generated.

**Comment by mmaietta** [comment]
`--publish never` I think would do the trick in disabling the update files from being generated

**Comment by Eve-Sama** [comment]
> `--publish never` I think would do the trick in disabling the update files from being generated

It didn't work.

**Comment by ReneeDress** [comment]
use `--dir` in command line

**Comment by leohxj** [comment]
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/ArchiveTarget.ts#L67

can not configure, Mac target zip will  call create blockmap,

**Comment by yikuansun** [comment]
> https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/ArchiveTarget.ts#L67 the var `isWriteUpdateInfo` is pass `true`: 

I see it's now `false`, is blockmap generation skipped in the new release?
