### ISSUE TITLE
Allow to use v24.0.0-alpha.1 electron-rebuild monorepo behavior

### ISSUE THREAD

**Issue by witcher112** [electron-userland/electron-builder#7252]
* **Electron-Builder Version**: 24.0.0-alpha.2

* **Node Version**: v16.16.0

* **Electron Version**: 17.4.11
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, Linux, macOS

While #7212 fixes the monorepo setup of https://github.com/gzdunek/electron-quick-start-monorepo it actually breaks the setup for my project which uses the _nohoist_ workaround (due to the nature of my project's structure, it's actually not a workaround but an intended setup).

Can we perhaps introduce an option to keep the _v24.0.0-alpha.1_ behavior?

I'm willing to create a PR with such modification, but I would need guidance on where to put the configuration option and how to name it.

**Comment by mmaietta** [comment]
Hmmm, which part is breaking by chance? Is the package.json just not able to be found?  Is this a two package.json structure?
Happy to review a PR

**Comment by witcher112** [comment]
Things have changed and I got rid of the requirement of rebuilding native packages in my project, thus eliminating the problem.

Anyway, thanks for the reply, good job with the project!
