### ISSUE TITLE
Windows multi architecture build issue in v24.0.0-alpha.3 

### ISSUE THREAD

**Issue by balajiv113** [electron-userland/electron-builder#7256]
* **Electron-Builder Version**: v24.0.0-alpha.3

* **Node Version**: v16.18.0

* **Electron Version**: 21.2.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

In v24.0.0-alpha.3, electron-builder uses electron-rebuild to rebuilt native dependencies. 

In this, electron-rebuild is called via API not as a child process. Due to this, env like GYP_MSVS_VERSION set from node-gyp is impacting next architecture build. As of now, this is impacting multi architecture build in windows with native dependencies.

**Unfortunately, i am not able to put down a small reproduction repo. I will try to put the root issue in steps, hope it helps**
Current architecture: x64
Target build architecture in electron-builder: x64, ia32, arm
env: {GYP_MSVS_VERSION: 2019}

The steps happens within electron-builder,
- electron-builder starts and installs production dependency
- **builds for x64**, since current and build arch are same, no rebuild happens [All Good]
- **build for ia32**, since current and build arch are not same, rebuild happens (electron-rebuild is called via API, so process.env is same) [All Good, but env corrupted]
  - electron-rebuild again call node-gyp with msvs_version as 2019. This is from GYP_MSVS_VERSION env (https://github.com/electron/rebuild/blob/main/src/rebuild.ts#L77).
  - node-gyp picks vscode 2019, but after that they sets GYP_MSVS_VERSION env to 2015 at the end (https://github.com/nodejs/node-gyp/blob/main/lib/configure.js#L120)
- **build for arm**, since current and build arch are not same, rebuild happens (now the process.env contains {GYP_MSVS_VERSION: 2015}) [Fails]
  - electron-rebuild again call node-gyp with msvs_version as 2015
  - node-gyp fails stating not able to find VS Code

Though this issue happens on windows as of now, this kind of env corruption can happen in various different cases. Since same process being reused for multiple architecture build. 

Please refer to this actions log, if you are interested in actual application build logs
x64 - https://github.com/balajiv113/ferdium-app/actions/runs/3460425812/jobs/5776949792#step:15:306
arm - https://github.com/balajiv113/ferdium-app/actions/runs/3460425812/jobs/5776949792#step:15:890
ia32 - https://github.com/balajiv113/ferdium-app/actions/runs/3460425812/jobs/5776949792#step:15:4322

**Comment by mmaietta** [comment]
I think this may be a bug in electron-rebuild? There's nothing we can set from the electron-builder side that would force a new process to be used each time.
This is all we are doing:
https://github.com/electron-userland/electron-builder/blob/341221c801f563349f1cbd4d164f5f915c284c41/packages/app-builder-lib/src/util/yarn.ts#L154-L165

**Comment by balajiv113** [comment]
@mmaietta 
I think electron-rebuild itself is not supposed to be called multiple times with-in same process like done here. I can raise a upstream issue as well to see if this understanding is correct.

Maybe we could do something similar like this to make it run in a child process
https://github.com/electron/forge/blob/main/packages/utils/core-utils/src/rebuild.ts#L25
https://github.com/electron/forge/blob/main/packages/utils/core-utils/src/remote-rebuild.ts

**Comment by balajiv113** [comment]
Just for info,
i was able to overcome this issue with the below tweak in beforePack hook of electron-builder

```
exports.default = async function (context) {
  delete process.env.GYP_MSVS_VERSION;
};
```

**Comment by baversjo** [comment]
thank you so much @balajiv113 that worked for me, but took me a day of struggling with building my app on windows to figure this. @mmaietta in case forking is not a good idea, maybe the above beforePack can be added into electron-builder as a solution?

**Comment by mmaietta** [comment]
Hi @baversjo, sure, I'm not opposed. It seems reasonable to add.

Please open a PR adding that line of code to L203 along with a comment to this issue url so we can track the reason why we added it.
https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/app-builder-lib/src/platformPackager.ts#L203-L205
(my dev env is corrupted atm so I'm unable to do so myself for now)
