### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by AlexeyShalik** [electron-userland/electron-builder#7259]
Uncaught SyntaxError: missing ) after argument list

electron-builder: 22.13.1
node: 14.17.3
electron: 18.3.6

Hi, I develop a corporate messenger and I'm having a problem. When I build a new version of the application, macOS users update successfully, but Windows users get an error, after which the download reaches 100%. This error is "SyntaxError: missing ) after argument list". How fix it? What is wrong?

![Снимок](https://user-images.githubusercontent.com/25623226/201944150-e51f09a4-a659-43de-b09e-fe4371642100.PNG)

**Comment by AlexeyShalik** [comment]
Somebody?

**Comment by mmaietta** [comment]
What version of electron-updater are you on? You might need to update electron-builder and electron-updater

I can't support old versions of electron-builder (v23.x) or early versions of electron-updater (5.x) as I wasn't part of the maintainer crew before then
