### ISSUE TITLE
Path To Long Exception if Version >5.1.12

### ISSUE THREAD

**Issue by vabene1111** [electron-userland/electron-builder#726]
* **Version**:  everything above 5.1.12, in this case 6.4.0

* **Target**: Windows

When using any Version higher than 5.1.12 my build fails with PathTooLong excpetion.
For testing i even moved my build env on a server and put it on a path of about 50 characters but it still says its too long.

Here is one example Log, the message is german and says the Path is too long it must be shorter than 248 and with the name it cant be bigger than 260
[log.txt](https://github.com/electron-userland/electron-builder/files/453904/log.txt)

I hope i haven't missed any reports reporting this, it might be my fault but if so i cant see where, thanks for the help.

Additional Info:
Node Version: 4.4.4
Electron Version: 1.3.5
NPM Version: 2.15.1
Package.json (important stuff): 
```javascript
"scripts": {
        "start": "electron .",  
        "postinstall": "install-app-deps",  
        "pack": "build --target dir",  
        "dist": "build",  
        "install": "npm install --prefix ./app"  
    },
    "devDependencies": {
        "electron-builder": "6.4.0",
        "electron-prebuilt": "1.3.5"
    },"dependencies": {
        "devtron": "^1.2.1",
        "dwn": "^0.0.2",
        "electron-json-storage": "^2.0.0",
        "electron-squirrel-startup": "^1.0.0",
        "highcharts": "^4.2.5",
        "mkpath": "^1.0.0",
        "node-notifier": "^4.6.0",
        "progress-stream": "^1.2.0",
        "recursive-readdir": "^2.0.0",
        "shelljs": "^0.7.0",
        "winreg": "^1.2.1"
    }
```

**Comment by develar** [comment]
Please ensure that asar is not disabled.

**Comment by vabene1111** [comment]
i think asar is enabled (as i never disabled it) but i will update NPM and report back, thank you

**Comment by vabene1111** [comment]
Updated NPM to 3.10.7 and still getting the exact same problem.
I will try different things and report if i can get it fixed.

**Comment by vabene1111** [comment]
Ok so i updated Node and Npm:
Node: 4.5.0
NPM: 3.10.7

Ran the scripts as Admin in Powershell and Cmd and could not get it working (same error)

I will report back when i get it solved, thanks for the help.

**Comment by develar** [comment]
This error must not happen if you use asar. If it is still error for you, reopen issue.
