### ISSUE TITLE
MAS is signing two times

### ISSUE THREAD

**Issue by MustafaEminn** [electron-userland/electron-builder#7260]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  16.17.1

* **Electron Version**: 21.2.0
* **Electron Type (current, beta, nightly)**: current

ElectronUpdater Version: 5.0.5

* **Target**:  MAS

I know that there is already an opened issue but there is no solution. When I try to build mas app, the app is signing two times. This problem is not happening when building mac. We need to use only the first certificate. 
![image](https://user-images.githubusercontent.com/63938499/201969098-0bb2e8b8-6dd6-40e8-83ef-8b3d7db0cd4d.png)

**Comment by technotip** [comment]
Same with my build. You were able to upload it to TestFlight?
Got any error? Resolved it?
