### ISSUE TITLE
MacOs installing third party PKG after initial Install.

### ISSUE THREAD

**Issue by savageqm** [electron-userland/electron-builder#7261]
Hello, I'm trying to install a third party .pkg or run a curl command for install after my electron installer finishes. I added this to my electron-builder.config file
`  "pkg": {
    "scripts": "../build/pkg-scripts"
  },

inside that folder I have postinstall.sh file which includes 
`#!/bin/sh
echo "testing postInstall"
curl qz.sh | bash`

I don't think my postinstall.sh is doing anything because my third party software is not installed.  Any information in what i'm doing wrong.

**Comment by mmaietta** [comment]
Sorry it's not possible for electron-builder to support this feature on mac, it's not something that can be implemented. For linux you have `postinstall` option for rpm/deb and for windows you can `include: <path to nsis file>`

If you want to install additional libraries, then you should do so with a prompt from your app on first-run. This would be logic purely on your side and probably the proper UX route to go
