### ISSUE TITLE
asarUnpack causes strange error

### ISSUE THREAD

**Issue by maphstr** [electron-userland/electron-builder#7264]
* **Electron-Builder Version**: 23.1.0

* **Node Version**:  14.17.13

* **Electron Version**: 19.0.8
* **Electron Type (current, beta, nightly)**:

* **Target**: linux

Hi, i am trying to get asarUnpack to unpack a folder with scripts for me (bat, ps) that i need to be unpacked in order to run them on a windows client. 

Ive located these in a folder 'scripts'  and have tried every version of specifing this folder in asarUnpack i can think of. 
I am using angular and a 'two-package.json-structure' from this boilerplate. https://github.com/maximegris/angular-electron

electron-builder.json:
<pre>
{
  "asar": true,
  "directories": {
    "output": "release/"
  },
  "files": [
    "**/*",
    "!**/*.ts",
    "!*.map",
    "!package.json",
    "!package-lock.json",
    {
      "from": "../dist",
      "filter": ["**/*"]
    }
  ],
  "asarUnpack": [
    "./scripts"
  ],
}
</pre>

However, no matter how i specify "scripts" under asarUnpack, i get this error:

<pre>
{"platform":"linux","arch":"x64","version":"19.0.8"}] --output /project-dir/git/angular-electron/release/linux-unpacked --distMacOsAppName Electron.app
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=74
  • exited          command=app-builder code=0 pid=1203076
  • async task error  error=/project-dir/git/angular-electron/dist/150.e37d8e7f4efc2bc5.js must be under /project-dir/git/angular-electron/app/
  ⨯ /project-dir/git/angular-electron/dist/150.e37d8e7f4efc2bc5.js must be under /project-dir/git/angular-electron/app/  failedTask=build stackTrace=Error: /project-dir/git/angular-electron/dist/150.e37d8e7f4efc2bc5.js must be under /project-dir/git/angular-electron/app/
    at getRelativePath (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/util/filter.ts:32:13)
    at AsarPackager.unpackPattern (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/util/filter.ts:57:22)
    at AsarPackager.createPackageFromFiles (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/asar/asarUtil.ts:117:82)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AsarPackager.pack (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/asar/asarUtil.ts:37:41)
    at /project-dir/git/angular-electron/node_modules/app-builder-lib/src/platformPackager.ts:418:11
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/project-dir/git/angular-electron/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at LinuxPackager.doPack (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/platformPackager.ts:276:5)
    at LinuxPackager.pack (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/project-dir/git/angular-electron/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/project-dir/git/angular-electron/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/project-dir/git/angular-electron/node_modules/builder-util/src/promise.ts:12:14)
</pre>

Ive tried <pre>["**/*"], ["scripts/*"], ["**/scripts/*"], ["**/scripts"]</pre> and every variation. Always the same error. 

Btw, "150.e37d8e7f4efc2bc5.js" which the error mentions is one of the built js files that are in dist, and are in the asar-archive during successfull builds (when i remove the asarUnpack line)

Anyone have any clue what is going wrong here?

Mads

**Comment by DustinPham** [comment]
im having something very similar with 

`/project-dir/git/angular-electron/dist/150.e37d8e7f4efc2bc5.js must be under /project-dir/git/angular-electron/app/`

as well but it is for a different file.

**Comment by maphstr** [comment]
I hacked this to work by tracing the error down to this line  https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/app-builder-lib/src/asar/asarUtil.ts#L116

I think it might have to do with me having a two package.json structure or something, cause i saw that it tried to run this isUnpacked line on all my files in dist as well, and could not locate them. 

Quick fix that seemed to work for me was to change that line with 

<code>
if (file.includes('dist')) {

                isUnpacked = false;
            } else {
                isUnpacked = dirNode.unpacked || (this.unpackPattern != null && this.unpackPattern(file, stat));
            }
</code>

Not a good solution but perhaps it helps someone else.

**Comment by mmaietta** [comment]
That is bizarre behavior indeed. I see that both of your configs are relative and up the file tree.  What happens if you add a `to: "./"` to the from/filter object to force a FileSet?

**Comment by weiyuanbj** [comment]
Same issue, when i set up asarUnpack value, and electron builder will check if all files are under the root dir of my project. But when not set up it, electron builder will not check that. Is it reasonable?

**Comment by weiyuanbj** [comment]
Same issue, when i set up asarUnpack value, and electron builder will check if all files are under the root dir of my project even if i move files into it in files option. But when not set up it, electron builder will not check that. Maybe there is a issue with sequence of files and asarUnpack options

**Comment by Devine-Davies** [comment]
Hello, i seem to have gone down the same road, did any find a resolution to this ?

**Comment by maphstr** [comment]
> I hacked this to work by tracing the error down to this line
> 
> https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/app-builder-lib/src/asar/asarUtil.ts#L116
> 
> I think it might have to do with me having a two package.json structure or something, cause i saw that it tried to run this isUnpacked line on all my files in dist as well, and could not locate them.
> 
> Quick fix that seemed to work for me was to change that line with
> 
> `` if (file.includes('dist')) { ``` isUnpacked = false; } else { isUnpacked = dirNode.unpacked || (this.unpackPattern != null && this.unpackPattern(file, stat)); } ``` ``
> Not a good solution but perhaps it helps someone else.

Is still working for me. I included a step in npm install where i overwrite a separate copy of asarUtil over the official one.

**Comment by Devine-Davies** [comment]
@maphstr Cheers for the response i did see your comment and was intrigued, I started digging around with what you suggested but hit a dead end. Would be good to see how the `npm i` step is configured.

I included a step in my publishing stage to move the dist folder to the correct directory before building, using cpx.

I'm guessing this is a bug with `electron-builder` as this was previously working when not specifying `asarUnpack `.

**Comment by maphstr** [comment]
Sure, it's been a while so I don't remember exactly but this at least is the line in my package.json. I've put the modified asarUtil.js in my src/ folder. 

```
  "scripts": {
    "postinstall": "electron-builder install-app-deps && cp src/asarUtil.js node_modules/app-builder-lib/out/asar/asarUtil.js",
    ...
```

**Comment by kirill-konshin** [comment]
This ticket needs to be reopened, as the error is very misleading and should not happen...

In my case in a monorepo setup this same function fails on a file from linked package:

```
  ⨯ /x/lib/.tscache/cache must be under /x/demo/  failedTask=build stackTrace=Error: /x/lib/.tscache/cache must be under /x/demo/
    at getRelativePath (/x/demo/node_modules/app-builder-lib/src/util/filter.ts:32:13)
    at AsarPackager.unpackPattern (/x/demo/node_modules/app-builder-lib/src/util/filter.ts:57:22)
    at AsarPackager.createPackageFromFiles (/x/demo/node_modules/app-builder-lib/src/asar/asarUtil.ts:129:82)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at AsarPackager.pack (/x/demo/node_modules/app-builder-lib/src/asar/asarUtil.ts:49:41)
    at /x/demo/node_modules/app-builder-lib/src/platformPackager.ts:439:11
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/x/demo/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at MacPackager.doPack (/x/demo/node_modules/app-builder-lib/src/platformPackager.ts:293:5)
    at MacPackager.pack (/x/demo/node_modules/app-builder-lib/src/macPackager.ts:215:9)
    at Packager.doBuild (/x/demo/node_modules/app-builder-lib/src/packager.ts:459:9)
    at executeFinally (/x/demo/node_modules/builder-util/src/promise.ts:12:14)
    at Packager.build (/x/demo/node_modules/app-builder-lib/src/packager.ts:393:31)
    at executeFinally (/x/demo/node_modules/builder-util/src/promise.ts:12:14)
```

I run `electron-builder` in `demo` directory, and the linked library is in `lib` dir.

When there's no `asarUnpack` everything works just fine.

Repository is public https://github.com/kirill-konshin/next-electron-rsc just change `demo/eletron-builder.yml`:

```yml
asarUnpack:
  - '.next/standalone/demo/.next/cache/**/*'
```

And the error will appear.

**Comment by kirill-konshin** [comment]
@mmaietta thank you for your response, can you pls share how to configure Electron Builder to use package with the version you mentioned?

**Comment by kirill-konshin** [comment]
@mmaietta it builds, but I had to remove `includeSubNodeModules`, so it now fails in runtime... 

The demo uses standalone Next.js output in `.next/standalone/demo/`, which contains `node_modules`:

```yml
includeSubNodeModules: true

files:
  - build
  - from: '.next/standalone/demo/'
    to: '.next/standalone/demo/'
```

**Comment by beyondkmp** [comment]
This usage doesn't seem quite right. The app.asar.unpacked folder should be fixed and shouldn't contain the cache directory, as it needs to dynamically write files. It would make more sense to place the cache in the user data directory instead.

**Comment by beyondkmp** [comment]
This may not be achievable during runtime.
Because the code(https://github.com/vercel/next.js/blob/canary/packages/next/src/server/image-optimizer.ts#L372) is inside app.asar, the current path it retrieves is app.asar, and then this path is combined in the code to become /x/demo/dist/mac-arm64/Next Electron RSC.app/Contents/Resources/app.asar/.next/standalone/demo/.next/cache.

**Comment by kirill-konshin** [comment]
The problem is Next.js does not allow to set custom path to cache… at all. Its hardcoded to be relative to distDir: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/image-optimizer.ts#L372

**Comment by beyondkmp** [comment]
It seems to be an Electron issue. When Electron reads the asar files, it should look up or replace them during runtime.
