### ISSUE TITLE
Failed to run "electric builder" on kylin

### ISSUE THREAD

**Issue by rdtx661** [electron-userland/electron-builder#7267]
There are two "kylin" computers made in China. Their CPU models are different. One CPU model is "physium, ft – 2000/4 (64 bit, 4-core)", which can run "electric builder" normally. The other CPU model is "64cores physium, ft – 2000+/64 64bit". When running "electric builder", it will download (more like updating) the current version of electric (my electric version is 11.3.0) from github, Then the compilation fails, and one of the error prompts is exited with code err_ electron_ builder_ cannot_ Execute, should I upgrade the version of Electron in this case? Which version do you need to upgrade to? Thank you, please tell me

**Comment by mmaietta** [comment]
Please run with DEBUG=electron-builder env var set tto see where it's crashing. Best guess is that one of the binaries used to package an app is not supported  on kylin
