### ISSUE TITLE
AppImage support for passing of Categories for .desktop file

### ISSUE THREAD

**Issue by mackenza** [electron-userland/electron-builder#727]
* **Version**: 6.4.0

* **Target**: Linux AppImage

I would be very useful to be able to pass a list of Categories as options for `build.linux` key.
The Categories is a string in the form (LibreOffice Calc example):
 `Categories=Office;Spreadsheet;X-Red-Hat-Base;X-MandrivaLinux-Office-Spreadsheets;`
https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

zaggino/brackets-electron#65

I will try and work on a PR for this but wanted to get it logged here just in case someone else can knock it off faster than me ;)

**Comment by develar** [comment]
Relates: #641

**Comment by develar** [comment]
PR is welcome.
