### ISSUE TITLE
autoUpdater.autoInstallOnAppQuit = false, doesn't update the app after quitAndInstall on MAC

### ISSUE THREAD

**Issue by alimuddins** [electron-userland/electron-builder#7279]
For MAC, app is not getting updated after update is downloaded.

**Requirement is -**
User should get the update pop up (Note: Update is already downloaded here)
User can click cancel or update now.
If clicked cancel & users quits the app and relaunch, then app should not udpate.
App should update only when user clicks "Update Now" button.
I am using **autoUpdater.autoInstallOnAppQuit = false**, flag to do this, works fine on windows but not on MAC.

**Configs -**
electron = 13.6.1
electron-builder = 23.1.0
electron-updater = 4.6.5

MAC = 12.3 Monterey

It works fine for windows.

**Code for quit and install -**
autoUpdater.quitAndInstall();
app.exit();

![image](https://user-images.githubusercontent.com/76930713/203292212-4bcda7b2-d4fc-4853-8a10-3bbd9ecabd3a.png)

**Comment by alimuddins** [comment]
Team, any support on this?

**Comment by mmaietta** [comment]
This is one of the two places where `autoInstallOnAppQuit` is being used as `false`
https://github.com/electron-userland/electron-builder/blob/a117ccb7592f49f82053951c18b2ece7d6eab12d/packages/electron-updater/src/MacUpdater.ts#L227-L233

The only way to trigger this is if you explicitly are calling `quitAndInstall`, which is the correct behavior.
