### ISSUE TITLE
"npm run dist" fails when behind a proxy

### ISSUE THREAD

**Issue by stepbeta** [electron-userland/electron-builder#728]
* System: **Windows 10 Home x64**
* electron: **1.3.5**
* node: **5.8.0**
* npm: **3.7.1**
* electron-builder: **6.4.1**
* target platform: **Windows**

I'm trying to build an application, following the steps outlined [here](https://github.com/electron-userland/electron-builder#electron-builder--).
I am behind an enterprise proxy, which gives me headaches every day, but I managed to get npm working, using the following configs:

> C:\path>npm config list
> ; cli configs
> user-agent = "npm/3.7.1 node/v5.8.0 win32 x64"
> 
> http-proxy = "http://user:pwd@adress:port/"
> https-proxy = "http://user:pwd@adress:port/"
> proxy = "http://user:pwd@adress:port/"
> registry = "http://registry.npmjs.org/"
> strict-ssl = false

when executing `npm run dist`, though, these settings are ignored and the following errors are produced on console:

> C:\Users\Stefano>npm run dist
> 
> > Derris@0.1.0 dist C:\path
> > build
> 
> Rebuilding app dependencies for arch x64 to C:\path\app
> 
> Unhandled rejection Error: getaddrinfo ENOTFOUND dl.bintray.com dl.bintray.com:443
>     at errnoException (dns.js:26:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
> From previous event:
>     at C:\path\node_modules\electron-builder\src\util\binDownload.ts:57:17
>     at next (native)
>     at C:\path\node_modules\fs-extra-tf\lib\mkdirs\mkdirs.js:35:14
>     at FSReqWrap.oncomplete (fs.js:82:15)
> From previous event:
>     at tsAwaiter (C:\path\node_modules\electron-builder\src\util\awaiter.ts:10:47)
>     at Object.build (C:\path\node_modules\electron-builder\src\builder.ts:179:52)
>     at Object.<anonymous> (C:\path\node_modules\electron-builder\src\build-cli.ts:27:28)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at startup (node.js:141:18)
>     at node.js:933:3
> 
> Packaging for platform win32 x64 using electron 1.3.5 to dist\win-unpacked
> 
> Error: getaddrinfo ENOTFOUND dl.bintray.com dl.bintray.com:443
>     at errnoException (dns.js:26:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
> From previous event:
>     at C:\path\node_modules\electron-builder\src\util\binDownload.ts:57:17
>     at next (native)
>     at C:\path\node_modules\fs-extra-tf\lib\mkdirs\mkdirs.js:35:14
>     at FSReqWrap.oncomplete (fs.js:82:15)
> From previous event:
>     at tsAwaiter (C:\path\node_modules\electron-builder\src\util\awaiter.ts:10:47)
>     at Object.build (C:\path\node_modules\electron-builder\src\builder.ts:179:52)
>     at Object.<anonymous> (C:\path\node_modules\electron-builder\src\build-cli.ts:27:28)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at startup (node.js:141:18)
>     at node.js:933:3
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Stefano\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
> npm ERR! node v5.8.0
> npm ERR! npm  v3.7.1
> npm ERR! code ELIFECYCLE
> npm ERR! Derris@0.1.0 dist: `build`
> npm ERR! Exit status 4294967295
> npm ERR!
> npm ERR! Failed at the Derris@0.1.0 dist script 'build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the Derris package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs Derris
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls Derris
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\path\npm-debug.log

Attachments:
* [npm-debug.log](https://github.com/electron-userland/electron-builder/files/456627/npm-debug.txt)
* [dev-package.json](https://github.com/electron-userland/electron-builder/files/456631/package.txt)
* [package.json](https://github.com/electron-userland/electron-builder/files/456636/package.txt)

**Comment by develar** [comment]
Duplicates #585
