### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Pulset** [electron-userland/electron-builder#7280]
* **Electron-Builder Version**:  23.3.1

* **Node Version**:  16.16

* **Electron Version**: 19.1.6
* **Electron Type (current, beta, nightly)**: current

* **Electron Version**: 5.0.5

* **Target**: MAC Intel and ARM 

```
Error: Error: Code signature at URL file:///Users/pulse/Library/Caches/xxx.app/ 
did not pass validation: 代码未能满足指定的代码要求
```
Apple signature is successful, but it throws an Error when it updates.I don't know why did't pass validation.

**Comment by mmaietta** [comment]
Is it notarized?

**Comment by Krishnaraj-shankar** [comment]
Error: Code signature at URL file:///Users/krishna-pt5814/Library/Caches/com.Krishnaraj.autoupdater.ShipIt/update.Homm8pL/Autoupdater%20app.app/ did not pass validation: code has no resources but signature indicates they must be present

Getting this error while downloading updates from github release
