### ISSUE TITLE
Exit code: 1. Command failed: which python

### ISSUE THREAD

**Issue by yf339339** [electron-userland/electron-builder#7283]
* **Electron-Builder Version**:  23.6.0

* **Node Version**: 14.8.0

* **Electron Version**: 21.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  dmg

**Comment by mmaietta** [comment]
You need python installed

**Comment by yf339339** [comment]
thanks，mac python3 doesn't work，I installed python 2.7
