### ISSUE TITLE
I have a build error if my configuration has two or more Mac OS targets and one of targets is mas

### ISSUE THREAD

**Issue by Incont** [electron-userland/electron-builder#7284]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v16.18.1

* **Electron Version**: 21.3.0
* **Electron Type (current, beta, nightly)**: current

4.3.5

* **Target**: ["dmg","mas" ]

Hello. My code has a native module (https://github.com/Incont/n-ftdi). And when I try to build Mac OS targets [dmg, mas] I have a build error. It happened because in macPackager.ts https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts the method doPack is invoked in parallel for mas and dmg targets and "node-gyp rebuild" also is invoked in parallel.
I used previously electron-builder v.22.9.1 and had no issues with the building.

 electron-builder  version=23.6.0 os=20.6.0
  • loaded configuration  file=/Users/artem.kozlov/bitbucket/relab2-desktop/electron-builder.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=n-ftdi@1.3.10 platform=darwin arch=x64
  • rebuilding native dependencies  dependencies=n-ftdi@1.3.10 platform=darwin arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/n-ftdi
    npm ERR! command failed
    npm ERR! command sh -c -- node-gyp rebuild
    npm ERR! CXX(target) Release/obj.target/N-FTD2XX/src/N_FTD2XX.o
    npm ERR!   CXX(target) Release/obj.target/N-FTD2XX/src/ft_program_data_wrapper.o
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.1.0
    npm ERR! gyp info using node@16.18.1 | darwin | x64
    npm ERR! gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
    npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/n-ftdi/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/artem.kozlov/.electron-gyp/21.3.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/artem.kozlov/.electron-gyp/21.3.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/artem.kozlov/.electron-gyp/21.3.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/n-ftdi',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! sed: ./Release/.deps/Release/obj.target/N-FTD2XX/src/ft_program_data_wrapper.o.d.raw: No such file or directory
    npm ERR! rm: ./Release/.deps/Release/obj.target/N-FTD2XX/src/ft_program_data_wrapper.o.d.raw: No such file or directory
    npm ERR! make: *** [Release/obj.target/N-FTD2XX/src/ft_program_data_wrapper.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    npm ERR! gyp ERR! System Darwin 20.6.0
    npm ERR! gyp ERR! command "/Users/artem.kozlov/.nvm/versions/node/v16.18.1/bin/node" "/Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/n-ftdi
    npm ERR! gyp ERR! node -v v16.18.1
    npm ERR! gyp ERR! node-gyp -v v9.1.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/artem.kozlov/.npm/_logs/2022-11-23T07_42_41_448Z-debug-0.log
    
                    command=/Users/artem.kozlov/.nvm/versions/node/v16.18.1/bin/node /Users/artem.kozlov/.nvm/versions/node/v16.18.1/lib/node_modules/npm/bin/npm-cli.js rebuild n-ftdi@1.3.10
                    workingDir=

/Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/builder-util/src/util.ts:250
      reject(new ExecError(command, code, out, errorOut))
             ^
Error: /Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/app-builder-bin/mac/app-builder_amd64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
2
    at ChildProcess.<anonymous> (/Users/artem.kozlov/bitbucket/relab2-desktop/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by mmaietta** [comment]
I took a quick look and not sure I'm following. Where does it show that it is building in parallel? Seems like it'd be an easy fix to just make it sync.
Would love to have a community contribution on this. Setting up a local dev environment is fairly straight forward too
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
