### ISSUE TITLE
Adding extraResources to package.json does nothing, tells nothing when fails,  does not work

### ISSUE THREAD

**Issue by Sakari369** [electron-userland/electron-builder#7293]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  v16.18.1

* **Electron Version**: 18.3.15
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

Why is this so difficult?

I have the following directory structure:

```
electron_build/
                           assets/
                                        File.json
                           ...
                           package.json
```

This means my assets directory is in the same directory as package.json.

I add this line to my package.json:

```
  "build": {
    "extraResources": [
      "assets/*.json"
    ],
```

I run this command inside "electron_build" directory:

```
npx electron-builder -m
```

I would expect the extraResources file 'File.json' to be inside the distributed application 'Contents/Resources' on Mac, yet nothing is copied there.

I've tried multiple variations of "./assets/*.json" or "assets/File.json" "./assets/File.json" "**/assets/File.json" and nothing happens when running this command.

The command tells nothing if something is not working, I've now spent about 4 hours just trying to figure why this thing wont work or say something why it is not working. Could it even report that "No files matching" or tell which directory it is trying find the resource at, relative to the package.json ?

What am I missing ?

Thanks!

**Comment by Sakari369** [comment]
Okay apparently you are supposed to use this format 

```
    "extraResources": [
    {
      "from": "./assets/",
      "to": "assets/",
      "filter": [
        "**/*"
      ]
    }
    ],
```

Then it works..

Could you provide an example in https://www.electron.build/configuration/contents#extraresources so that the user is not confused about this ? Thank you!

**Comment by mmaietta** [comment]
Please open up a PR at your leisure to add that to the docs.
