### ISSUE TITLE
MacOS - PKG build - Preinstall/Postinstall scripts KO

### ISSUE THREAD

**Issue by qfl75** [electron-userland/electron-builder#7299]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.18.0

* **Electron Version**:21.2.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: macOS - PKG

I try to build a pkg for my apps with preinstall script.
When I add "scripts" option with the path to the repo nothing happened.

The --scripts options with the directory path is added to the pkgbuild command but the .plist file used in package build doesn't contains BundlePreInstallScriptPath or BundlePostInstallScriptPath keys which should contains scripts name (eg: preinstall.sh).

These keys are necessary to execute preinstall or postinstall script on pkg install.

Could you have a look on this.

Thanks.

**Comment by KaminoRyo** [comment]
I am also in the same situation and came to the same conclusion after reading `/app-builder-lib/targets/pkg.ts`. This option is not working.
