### ISSUE TITLE
MS Authenticode and Apple Gatekeeper signing

### ISSUE THREAD

**Issue by Vj3k0** [electron-userland/electron-builder#730]
To sign app for Authenticode I need one certificate. For Gatekeeper, I need an Apple developer certificate. I have my own build machine (not using Travis or AppVeyor) and only one CSC_LINK variable, meaning I can use only one certificate.

I can skip signing with electron-builder and then sign it manually as additional step in build process, but I'd like to know first if there is some solution already implemented in electron-builder for this scenario.

(Or maybe somewhere exists a single certificate for both?)

Cheers,
Vjeko

**Comment by develar** [comment]
Duplicates #548

**Comment by develar** [comment]
Workaround: https://github.com/electron-userland/electron-builder/issues/548#issuecomment-234536292

PR welcome.
