### ISSUE TITLE
NSIS "Error launching installer" after moving portable exe to System32

### ISSUE THREAD

**Issue by KernelDeimos** [electron-userland/electron-builder#7301]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 18.7.0

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: --win portable

I'm attempting to build a screensaver using Electron. To do this I'm using `electron-builder` with arguments `--win portable` and then renaming the executable to a `.scr`. Thanks to the `screen` module in Electron I'm able to display a full screen window on each monitor, and if I double-click my scr file it works great - looks just like a screensaver!

The trouble is, if I want to "select" it as a screensaver it needs to be in the System32 folder (at least, as far as I know). if I move the scr file into System32 it stops working. Trying to run it now shows an error dialog - window title is "NSIS error" and contents are "Error launching installer".

Additional note: building in CentOS 8, testing in Windows 10

**Comment by KernelDeimos** [comment]
I figured it out by Googling something less specific. I was searching everywhere for this "NSIS" error and then I simply searched "exe doesn't work after moving to System32"... I haven't used Windows since when 7 came out, and even then I was still using XP. It turns out this particular executable goes in "SysWOW64". From what I've read, this is where 32-bit executables go, with 64-bit executables residing in System32. Intuitive, right? Why would the directory an executable resides in change how it's executed? Really glad I switched to Linux early on and avoided this nonsense for the most part.

**Comment by neurotech** [comment]
> I figured it out by Googling something less specific. I was searching everywhere for this "NSIS" error and then I simply searched "exe doesn't work after moving to System32"... I haven't used Windows since when 7 came out, and even then I was still using XP. It turns out this particular executable goes in "SysWOW64". From what I've read, this is where 32-bit executables go, with 64-bit executables residing in System32. Intuitive, right? Why would the directory an executable resides in change how it's executed? Really glad I switched to Linux early on and avoided this nonsense for the most part.

Thank you, this helped me out with the same problem. Windows is something else. 🤦🏻‍♂️
