### ISSUE TITLE
[I tried all new builder flags] but still with error: ...have the same architectures (x86_64) and can't be in the same fat output file

### ISSUE THREAD

**Issue by cyspath** [electron-userland/electron-builder#7303]
> * **Electron-Builder Version**:  23.3.0 (upgraded from 23.0.0, to obtain the x64ArchFiles flag)
> * **Node Version**: v10.21.0
> * **Electron Version**: 16.2.0
> 
> * **Target**: universal (just arm64 works)

`fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: /private/var/folders/02/prpjgj8133s0y7n5xv2lbskm0000gn/T/electron-universal-9urm2b/Tmp.app/Contents/Resources/bin/aapt2 and /Users/mzl/fbsource/arvr/js/dist/mac-universal--arm64/Meta Quest Developer Hub.app/Contents/Resources/bin/aapt2 have the same architectures (x86_64) and can't be in the same fat output file`

I am building this from my intel Mac:
In the build config, I've tried few combination of those flags already but always the same error

```
      mac: {
        ...,
        target: [
          {
            target: 'dir',
            arch: 'universal',
          },
          {
            target: 'zip',
            arch: 'universal',
          },
          {
            target: 'dmg',
            arch: 'universal',
          },
        ],
        mergeASARs: true,
        // singleArchFiles: '**/aapt2',
        x64ArchFiles: '**/aapt2',
        ....
    }
```

cc @mmaietta for insights if you can please

**Comment by mmaietta** [comment]
I think you're running into an issue with app-builder-bin dependency not recompiling the right lib arch's

Can you try `next` electron-builder 24-alpha?
It migrates from app-builder-bin to use official @electron/rebuild project

**Comment by cyspath** [comment]
@mmaietta thanks for the reply, please correct me if I am mistaken but it seems that electron-builder is referring to electron/universal version that does not contain this flag? So even if I use this flag in electron-builder the electron/universal will not have such feature

electron/universal 1.3.4 commit:
https://github.com/electron/universal/commit/01dfb8a9636965fe154192b07934670dd42509f3

electron/builder latest is referring to "@electron/universal": "1.3.3"
https://github.com/electron-userland/electron-builder/blob/a117ccb7592f49f82053951c18b2ece7d6eab12d/packages/app-builder-lib/package.json

**Comment by leylita** [comment]
Hi! I would like to know if there is more informations about this issue?

I've got the same problem with my electron project:

> - Electron-Builder Version: 23.6.0 
> - Node Version: v16.14.0
> - Electron Version: 17.1.0

`... have the same architectures (x86_64) and can't be in the same fat output file`
while I'm using x64ArchFiles parameter

Here is my config:

```
return builder.build({
        mac: osList.includes("mac") ? ["dmg"] : undefined,        
        universal: osList.includes("mac"),        
        config: {
              ...
            mac: {
                category: "public.app-category.productivity",
                type: "distribution",
                electronLanguages: ["frFR", "enUS"],
                artifactName: settings.mac.artifactName,
                icon: iconFilename,
                target: "dmg",
                mergeASARs: true,
                hardenedRuntime: true,
                gatekeeperAssess: false,
                entitlements: "config/entitlements.plist",
                entitlementsInherit: "config/entitlements.plist",
                x64ArchFiles: "./extensions/${os}/*"
            },
            dmg: {
                sign: false
            }
        }
    });
```

**Comment by cyspath** [comment]
> Hi! I would like to know if there is more informations about this issue?
> 
> I've got the same problem with my electron project:
> 
> > * Electron-Builder Version: 23.6.0
> > * Node Version: v16.14.0
> > * Electron Version: 17.1.0
> 
> `... have the same architectures (x86_64) and can't be in the same fat output file` while I'm using x64ArchFiles parameter
> 
> Here is my config:
> 
> ```
> return builder.build({
>         mac: osList.includes("mac") ? ["dmg"] : undefined,        
>         universal: osList.includes("mac"),        
>         config: {
>               ...
>             mac: {
>                 category: "public.app-category.productivity",
>                 type: "distribution",
>                 electronLanguages: ["frFR", "enUS"],
>                 artifactName: settings.mac.artifactName,
>                 icon: iconFilename,
>                 target: "dmg",
>                 mergeASARs: true,
>                 hardenedRuntime: true,
>                 gatekeeperAssess: false,
>                 entitlements: "config/entitlements.plist",
>                 entitlementsInherit: "config/entitlements.plist",
>                 x64ArchFiles: "./extensions/${os}/*"
>             },
>             dmg: {
>                 sign: false
>             }
>         }
>     });
> ```

leylita, I got it resolved. I end up using a later version like 24.alpha 5 electron-builder, upon examining actual source code for those flags is only in later versions.

**Comment by pantelispanayiotou** [comment]
can this be included as a fix in the next stable release of electron-builder. I want to use it in production and i feel more safe to use a stable build
