### ISSUE TITLE
[Feature Request]: Support package.json5

### ISSUE THREAD

**Issue by BlackHole1** [electron-userland/electron-builder#7308]
* **Electron-Builder Version**: latest

* **Node Version**: v18.4.0

* **Electron Version**: v22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS / Windows / Linux

At this stage, there are some projects that use `package.json5` and I think we should support it. The current code is hard-coded with `package.json`

**Comment by mmaietta** [comment]
Happy to accept a community contribution! Setting up a local dev environment is pretty simple too :) 
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
