### ISSUE TITLE
electron-builder is too complex

### ISSUE THREAD

**Issue by axetroy** [electron-userland/electron-builder#7309]
Sorry for open in here, I wanted to open this thread to the discussion, but it doesn't exist.

At first I just wanted to know, where Electron is downloaded, I want to replace a DLL before building.

Then I starting search about `download` and found `electron-download` but it has been deprecate, now it `@electron/get`

Follow the `electron-download` guide, and I found this:

```
C:\Users\Admin\AppData\Local\electron\Cache\f62ba093f7e08d759d67e6079b8ceda89d44440a59c75ab0642c095d5b49e722\electron-v16.2.8-win32-x64.zip
```

But I found that electron-builder is not using it to build.

I have to research from source code.

#### 1. research the electron keyword in source, and found

https://github.com/electron-userland/electron-builder/blob/8166267d487cd26b154e28cf60d89102a487a353/packages/app-builder-lib/src/electron/ElectronFramework.ts#L126-L141

And you can see, Here is the logic for unzip

https://github.com/electron-userland/electron-builder/blob/8166267d487cd26b154e28cf60d89102a487a353/packages/app-builder-lib/src/electron/ElectronFramework.ts#L178-L191

#### 2. Let's find `executeAppBuilder` out in the next file

https://github.com/electron-userland/electron-builder/blob/8166267d487cd26b154e28cf60d89102a487a353/packages/builder-util/src/util.ts#L348-L355

Here is a child process to spawn something

https://github.com/electron-userland/electron-builder/blob/8166267d487cd26b154e28cf60d89102a487a353/packages/builder-util/src/util.ts#L371-L375

Let's print the command and arguments

```
C:\Users\Admin\gpm\project\node_modules\app-builder-bin\win\x64\app-builder.exe
[
  'unpack-electron',
  '--configuration',
  '[{"platform":"win32","arch":"x64","version":"16.2.8","mirror":"https://npmmirror.com/mirrors/electron/"}]',
  '--output',
  'C:\\Users\\Admin\\project\\build\\win-unpacked',
  '--distMacOsAppName',
  'Electron.app'
]
```

Oh, god, It is still impossible to know where it was decompressed.

### 3. Let's find what is '**app-pbuilder.exe**'

try to search from `electron-userland` repo

As you can see. There's no one package name `app-builder`

![截屏2022-12-09 17 57 35](https://user-images.githubusercontent.com/9758711/206675905-5771471f-c742-4bca-b96a-92ac18314f34.png)

But still got some similar package names `electron-builder`/`app-builder-lib`

There's no `app-builder` from electron-builder and app-builder-lib
https://github.com/electron-userland/electron-builder/blob/8166267d487cd26b154e28cf60d89102a487a353/packages/electron-builder/package.json#L2-L12

I gonna search the keyword **'unpack-eletron'**

Thanks god, nothing found.

![截屏2022-12-09 18 02 48](https://user-images.githubusercontent.com/9758711/206676836-65850b50-c1ae-4c9e-bc95-a7ffb21d26ea.png)

Finally I got it in `https://github.com/develar/app-builder` with search `app-builder-bin` package in npm

### Conclusion

I looked at the source code of electron-builder, it was complicated.

app-builder
builder-util
app-builder-bin

The names seem unrelated, and make me confused.
Hopefully the cost of understanding this project can be reduced

**Comment by axetroy** [comment]
This is not a complaint against the electron-builder project.

i just want to make it better.

Currently it doesn't have a nice directory hierarchy to help people quickly understand

For example, it seems that `app-builder-lib` does everything, including packaging the application, code signing, downloading dependencies, publishing the application and more.

I prefer to split them into several different packages.

```
paclages/electron-builder-code-signing
paclages/electron-builder-code-signing-macos
paclages/electron-builder-code-signing-windows
paclages/electron-builder-publish
paclages/electron-builder-packer-nsis
paclages/electron-builder-packer-appx
paclages/electron-builder-packer-deb
paclages/electron-builder-packer-rpm
...
```

**Comment by killaragorn** [comment]
+1
