### ISSUE TITLE
Nodemailer module cannot be found after packaging

### ISSUE THREAD

**Issue by sfraise** [electron-userland/electron-builder#731]
6.3.0

nsis

Trying to use nodemailer in our project.  Running from ./app in dev environment it works great but once packaged the nodemailer module can't be found.

I know technically electron isn't officially supported by nodemailer but has anyone gotten this to work or have any ideas on how to get the module found once packaged?

**Comment by develar** [comment]
Is `nodemailer` in your application dependencies?

**Comment by sfraise** [comment]
Nevermind I got it, I had to install it in the app directory not the top directory.
