### ISSUE TITLE
Mac code signing compatibility with @electron/osx-sign 1.0.4

### ISSUE THREAD

**Issue by mayfield** [electron-userland/electron-builder#7317]
* **Electron-Builder Version**: 24.0.0-alpha.7

* **Node Version**: 16

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

I'm in the process of updating to electron-builder 24 and having issues with code signing.  It looks like EB is using the legacy "identity-validation" property https://github.com/electron-userland/electron-builder/blob/ffe99677610e933a5a22ceb70ba0cbb7edf55695/packages/app-builder-lib/src/macPackager.ts#L273 which should be camelCase now.  

More importantly, while tracking this down, it became clear there is some conflated use of the `options.identity` string and the return value of the `findIdentity` function that returns an osx-sign `Identity` object.  In EB versions before 24 the legacy `identity-validation=false` working properly would mask this for my particular use case.

At this line, I think the identity value should be `qualifer` instead of the `Identity` instance.

https://github.com/electron-userland/electron-builder/blob/ffe99677610e933a5a22ceb70ba0cbb7edf55695/packages/app-builder-lib/src/macPackager.ts#L297

**Comment by mayfield** [comment]
I have this untested patch as an example https://github.com/mayfield/electron-builder/commit/8557a663b83ff3ec948cf1eb74a2f02aa0174f65

I was going to attempt a PR but I failed to achieve success manual or unit testing in a reasonable amount of time.  I ended up implementing an `afterPack` hook in my project instead that monkey patches the current code as follows...

https://github.com/SauceLLC/sauce4zwift/commit/e4e722f07573d75ddd7bef63b24b7650e5ea4011

**Comment by panther7** [comment]
Last worked version is ` 24.0.0-alpha.5`.

**Comment by mmaietta** [comment]
Thanks for calling this out. Would you be willing to open a PR with the value change?

**Comment by filfreire** [comment]
Also noticed this in our project, https://github.com/Kong/insomnia/actions/runs/3846215323/jobs/6551824759#step:5:146
```
⨯ No identity found for signing.  failedTask=build stackTrace=Error: No identity found for signing.
    at signApp (/Users/runner/work/***/***/packages/***/node_modules/@electron/osx-sign/src/sign.ts:360:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MacPackager.sign (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/macPackager.ts:324:5)
    at /Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/macPackager.ts:452:9
```

We are using `"app-builder-lib": "24.0.0-alpha.8"`
