### ISSUE TITLE
Icons look jagged on Windows 10+ when using 256x256 icon due to bad downscaling, but that's the minimum allowed size

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#7328]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  16.17.0

* **Electron Version**: 19.x
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows

This issue didn't occur on Windows 7, I guess due to a different downscaling algorithm in Windows?

In the new versions on Windows, the downscaling is atrociously bad in the file explorer and in the installer: 
![image](https://user-images.githubusercontent.com/6835891/208775042-13b9d380-d2a5-4545-b3a1-0fb1fbbce989.png)

![image](https://user-images.githubusercontent.com/6835891/208775253-a4ec7e6d-0b79-4506-be52-a3ea45ec8557.png)

You can see the maximum icon size that's displayed in 32x32, so why is building hardcoded to exit if an icon smaller than 256x256 is used?

Note that the icon is generated from a smooth SVG, and the input file of 256x256 looks totally smooth.

![icon-256x256@1x](https://user-images.githubusercontent.com/6835891/208775529-906d529d-55b1-4419-bd8b-af75cb2d39cb.png)

**Suggested resolution:** Stop requiring a minimum icon size of 256x256 on Windows, or outline the need for that size and downscale the image before packaging so it will be spared the gruesome downscaling of Windows 11.

**Comment by mmaietta** [comment]
The icon size resolution might be related to this so I don't think there's anything electron-builder can do. Best advice is to manually generate an `ico` file with more resolutions in it to account for every scale factor to avoid scaling issues.
>Apps should have, at the bare minimum: 16x16, 24x24, 32x32, 48x48, and 256x256. This covers the most common icon sizes, and by providing a 256px icon, ensures Windows should only ever scale your icon down, never up.

https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction

**Comment by Slapbox** [comment]
@mmaietta I don't know that this is possible given the current design though? Because it's not the runtime application for our app that's the problem - but the icon generated by `eelectron-builder`. Is there anything we can do about that without changes to `electron-builder`?

This is a pretty minor issue, but it would be nice to have a way to work around it. But I hear what you're saying that `electron-builder` is just following Microsoft's quidelines.

**Comment by mmaietta** [comment]
This is what is generating the icons: https://github.com/develar/app-builder
`icon --input=INPUT --format=FORMAT --out=OUT`
That's why I can't change anything on the electron-builder side. I also don't know what resolutions it's outputting

The alternative route is how I always took it in the past. Just generate your own `.ico` file from your svg with all resolutions you need/want, then supply it through
```
win: {
   icon: ./path/to/file.ico
}
```
