### ISSUE TITLE
[Bug] Electron Builder built apps not working with WDAC

### ISSUE THREAD

**Issue by hj-collab** [electron-userland/electron-builder#7329]
Hi,

Electron builder built apps which uses unsigned .node modules are not working with WDAC. It requires all code to be signed. https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create

An app which I use is called [Frappe Books](https://github.com/frappe/books/blob/master/electron-builder.yml) and it loads better_sqlite3.node for example.

![image](https://user-images.githubusercontent.com/101234934/208785324-e9d0c272-87e9-4863-8d3d-cea2fd123ede.png)

It's located under "App Folder\resources\app.asar.unpacked\node_modules\better-sqlite3\build\Release\better_sqlite3.node"

I see Electron builder provides an option to sign all .dll files. Why not do the same for these node files? That will allow us to run electron builder built apps in WDAC hardened environments.

**Comment by mmaietta** [comment]
Would you be willing to give this a shot using [patch-package](https://www.npmjs.com/package/patch-package)?
`app-builder-lib+24.0.0-alpha.8.patch`
```
diff --git a/node_modules/app-builder-lib/out/winPackager.js b/node_modules/app-builder-lib/out/winPackager.js
index 8eae916..1b1f002 100644
--- a/node_modules/app-builder-lib/out/winPackager.js
+++ b/node_modules/app-builder-lib/out/winPackager.js
@@ -294,15 +294,16 @@ class WinPackager extends platformPackager_1.PlatformPackager {
             await buildCacheManager.save();
         }
     }
-    isSignDlls() {
-        return this.platformSpecificBuildOptions.signDlls === true;
+    shouldSignFile(file) {
+        const shouldSignDll = this.platformSpecificBuildOptions.signDlls === true && file.endsWith(".dll");
+        return file.endsWith(".exe") || shouldSignDll || file.endsWith('.node');
     }
     createTransformerForExtraFiles(packContext) {
         if (this.platformSpecificBuildOptions.signAndEditExecutable === false) {
             return null;
         }
         return file => {
-            if (file.endsWith(".exe") || (this.isSignDlls() && file.endsWith(".dll"))) {
+            if (this.shouldSignFile(file)) {
                 const parentDir = path.dirname(file);
                 if (parentDir !== packContext.appOutDir) {
                     return new fs_1.CopyFileTransformer(file => this.sign(file));
@@ -320,7 +321,7 @@ class WinPackager extends platformPackager_1.PlatformPackager {
             if (file === exeFileName) {
                 return this.signAndEditResources(path.join(packContext.appOutDir, exeFileName), packContext.arch, packContext.outDir, path.basename(exeFileName, ".exe"), this.platformSpecificBuildOptions.requestedExecutionLevel);
             }
-            else if (file.endsWith(".exe") || (this.isSignDlls() && file.endsWith(".dll"))) {
+            else if (this.shouldSignFile(file)) {
                 return this.sign(path.join(packContext.appOutDir, file));
             }
             return null;
@@ -330,7 +331,7 @@ class WinPackager extends platformPackager_1.PlatformPackager {
         }
         const signPromise = (filepath) => {
             const outDir = path.join(packContext.appOutDir, ...filepath);
-            return (0, fs_1.walk)(outDir, (file, stat) => stat.isDirectory() || file.endsWith(".exe") || (this.isSignDlls() && file.endsWith(".dll")));
+            return (0, fs_1.walk)(outDir, (file, stat) => stat.isDirectory() || this.shouldSignFile(file));
         };
         const filesToSign = await Promise.all([signPromise(["resources", "app.asar.unpacked"]), signPromise(["swiftshader"])]);
         await bluebird_lst_1.default.map(filesToSign.flat(1), file => this.sign(file), { concurrency: 4 });
```

I don't have a project to test locally on, but that patch will trigger signing on all .node files. Please give it a shot and report back? 🙂

**Comment by mmaietta** [comment]
@hj-collab updated `latest` to [24.4.0](https://www.npmjs.com/package/electron-builder/v/24.4.0)

**Comment by mmaietta** [comment]
Hey @hj-collab , quick update. This had to be reverted due to https://github.com/electron-userland/electron-builder/issues/7652. What I've done instead is remove `.node` files from being signed by default. Instead, there's a `signExts?: string[] | null` configuration option in v24.6.3 where you can specify `signExts: [".node"]` and any other file extension that needs to be signed. `signDll` will be deprecated since it overlaps with `signExts` array functionality.
