### ISSUE TITLE
Hidden 'dotfiles' within an extraResources folder aren't copied

### ISSUE THREAD

**Issue by joerick** [electron-userland/electron-builder#733]
* **5.18.0**: 

* **Mac**: 

Using electron-builder to build a Mac .app file. My resources include some Python libraries, and they store some files in a folder called `.dylibs`. So the tree looks like (simplified):

    Repo root
    |- vendor
    |  |- tide-packages
    |  |  |- PIL
    |  |  |  |- image.py
    |  |  |  |- .dylibs
    |  |  |  |  |- libjpeg.dylib

I've specified the `vendor` folder in `extraResources` in my package.json, and everything inside it is copied, except the .dylibs folder. I think its due to the use of minimatch in the copy filter.

Currently the workaround is to add another rule in package.json:
   
      "build": {
        "extraResources": [
          "vendor",
          "vendor/**/.*",
          "vendor/**/.*/**",
        ],
      }
   
I didn't expect this to be needed, though, since I don't expect `glob` to be used when there are no wildcards in the path.

Ref: https://github.com/tingbot/tide-electron/issues/42

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Options#file-patterns **hidden files are ignored by default**

I don't want to change defaults — is there magic or not in the pattern, doesn't matter.

But yes – `.dylibs` should be added to exclusions add copied by default, because it is common known folder name.

**Comment by joerick** [comment]
Okay, that's your call. I don't agree, because I'd expect it to work like `cp`, i.e.
```
    # this would copy everything inside vendor
    cp -R vendor $BUILD_ROOT/vendor
```
```
    # this would skip the dotfiles in vendor
    mkdir -p $BUILD_ROOT/vendor
    cp -R vendor/* $BUILD_ROOT/vendor
```
Adding extra filters after the user has given an explicit path seems to go against the wishes of the user.

**Comment by develar** [comment]
> seems to go against the wishes of the user.

Files like `.DS_Store` or `thumbs.db` should be ignored. Excluding dot files by default helps to reduce size of packaged app.

**Comment by joerick** [comment]
> Files like .DS_Store or thumbs.db should be ignored.

Couldn't disagree with that.

Another factor was that this decreases dev/prod parity - for me it caused a bug that only occurred in production builds. And I can only test a fix by doing a full rebuild.

**Comment by develar** [comment]
Ok. If we will exclude only dot files, but not dot folders, is it ok for you?

**Comment by joerick** [comment]
My absolute preferred solution would be: when a folder is explicitly listed as something to copy, only exclude files within that we _know_ are useless in a production build - .DS_Store, thumbs.db, .git, etc.

Just checked Xcode's copy command... it does the following-

    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks $SRC $DEST

**Comment by develar** [comment]
Thanks a lot that you decided to argue your position instead of just workaround only for your project.

**Comment by joerick** [comment]
👍 no worries!
