### ISSUE TITLE
Using `allowNativeWayland` is an unknown property

### ISSUE THREAD

**Issue by KorbsStudio** [electron-userland/electron-builder#7330]
* **Electron-Builder Version**: 22.10.3

* **Node Version**: 18.7.0

* **Electron Version**: 22.0.0 and 23.0.0 Alpha 3
* **Electron Type (current, beta, nightly)**: Current and Alpha

* **Target**: Snap

When enabling the option for `allowNativeWayland`, Electron Builder finds it to be an unknown property. 

```
configuration.snap has an unknown property 'allowNativeWayland'
```

This option is listed in the [Electron Builder documentation](https://www.electron.build/configuration/snap#:~:text=allowNativeWayland%20Boolean%20%7C%20%E2%80%9Cundefined%E2%80%9D%20%2D%20Allow%20running%20the%20program%20with%20native%20wayland%20support%20with%20%2D%2Dozone%2Dplatform%3Dwayland.).

**Comment by mmaietta** [comment]
Works for me on most recent release of electron-builder. Tag is `next` on npm

**Comment by KorbsStudio** [comment]
Seems to be working in `v23.6.0` of Electron Builder.
