### ISSUE TITLE
Missing documentation in configuration.md

### ISSUE THREAD

**Issue by jklp** [electron-userland/electron-builder#7335]
* **Electron-Builder Version**: N/A

* **Node Version**: N/A

* **Electron Version**: N/A
* **Electron Type (current, beta, nightly)**: N/A

* **Target**: N/A

In [configuration.md](https://github.com/electron-userland/electron-builder/blob/master/docs/configuration/configuration.md), it looks like there's anchor links to section that don't exist e.g.

- #MetadataDirectories
- #NsisWebOptions
- #PortableOptions 
- etc

Digging up an old version of configuration.md, it appears these sections were once inline:

https://github.com/electron-userland/electron-builder/blob/4084450851318f76872404a4f49f0dfc9a56d394/docs/configuration/configuration.md 

I was about to submit a PR to restore this, but noticed that the doc is generated, and I can't figure out where the source is. 

So just logging an issue so someone with more experience in the codebase can help fix this.

Thanks!

**Comment by mmaietta** [comment]
Looks like the path is supposed to be `!docs/generated/_____` now? The docs were moved from the `docs` branch to `master` a long time ago, so I'm guessing the links have been broken for quite some time. Would you mind opening a PR for this?
https://github.com/electron-userland/electron-builder/blob/master/docs/generated/Metadata.md

**Comment by jklp** [comment]
@mmaietta Hi, sorry I've just spent the last little bit trying to figure out how to create the PR - with my main problem being I can't find the files the anchor links are supposed to point to.  

If you can give me an idea on how the generated files are built i.e. where are the source files, I think I can work it out from there

Thanks!
