### ISSUE TITLE
autoUpdater is undefined on dynamic import

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#7338]
* **Electron-Builder Version**: 23.6.0
* **Electron-updater Version**: 5.3.0

* **Node Version**: v18.9.0

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

In static import declaration you can import `autoUpdater` like so:
```js
import { autoUpdater } from 'electron-updater'
```
But in dynamic import `autoUpdater` is undefined but placed in `default.autoUpdater` and it's mismatch with type declaration
```js
import('electron-updater').then(module => {
  module.autoUpdater // undefined
  module.default.autoUpdater // AppUpdater exist, but leads to TypeScript error
})
```

**Comment by mmaietta** [comment]
What's the typescript error? I was under the impression `module.default` was always required for CJS modules

**Comment by cawa-93** [comment]
@mmaietta 
> TS2339: Property 'default' does not exist on type 'typeof import("C:/Users/kozac/Dev/vite-electron-builder/node_modules/electron-updater/out/main")'.

Because it expect `autoUpdater` as named export, not as property in default export

**Comment by cawa-93** [comment]
Here I make reproduction for it: https://github.com/cawa-93/electron-updater-issue-repro

Steps:
1. Install deps: `npm ci`
2. Build from TS: `npm run build`
3. Run electron: `npm start`

**Comment by kernoeb** [comment]
I think this is related to Vite.js and Rollup, because it works with Vite.js 3
I'm not sure but it's probably related to `rollupOptions.interop`

**Comment by kernoeb** [comment]
Nope, sorry it's related to `rollupOptions.output.dynamicImportInCjs` which needs to be set to false since the last major version of Rollup

**Comment by cawa-93** [comment]
It's kinda super strange. Seems native dynamic import return all exported members exept `autoUpdater`
```ts
import('electron-updater/out/main.js') [Module: null prototype] {   
  AppImageUpdater: [class AppImageUpdater extends BaseUpdater],     
  AppUpdater: [class AppUpdater extends EventEmitter],
  CancellationToken: [class CancellationToken extends EventEmitter],
  DOWNLOAD_PROGRESS: 'download-progress',
  MacUpdater: [class MacUpdater extends AppUpdater],
  NoOpLogger: [class NoOpLogger],
  NsisUpdater: [class NsisUpdater extends BaseUpdater],
  Provider: [class Provider],
  UPDATE_DOWNLOADED: 'update-downloaded',
  UpdaterSignal: [class UpdaterSignal],
  __esModule: true,
  default: {
    AppUpdater: [Getter],
    NoOpLogger: [Getter],
    CancellationToken: [Getter],
    Provider: [Getter],
    AppImageUpdater: [Getter],
    MacUpdater: [Getter],
    NsisUpdater: [Getter],
    DOWNLOAD_PROGRESS: 'download-progress',
    UPDATE_DOWNLOADED: 'update-downloaded',
    UpdaterSignal: [class UpdaterSignal],
    autoUpdater: [Getter]
  }                                                                 
}
```

**Comment by cawa-93** [comment]
It's kinda super strange. Seems native dynamic import return all members exapt `autoUpdater` in root 
```js
import('electron-updater/out/main.js') 

[Module: null prototype] {   
  AppImageUpdater: [class AppImageUpdater extends BaseUpdater],     
  AppUpdater: [class AppUpdater extends EventEmitter],
  CancellationToken: [class CancellationToken extends EventEmitter],
  DOWNLOAD_PROGRESS: 'download-progress',
  MacUpdater: [class MacUpdater extends AppUpdater],
  NoOpLogger: [class NoOpLogger],
  NsisUpdater: [class NsisUpdater extends BaseUpdater],
  Provider: [class Provider],
  UPDATE_DOWNLOADED: 'update-downloaded',
  UpdaterSignal: [class UpdaterSignal],
  __esModule: true,
  default: {
    AppUpdater: [Getter],
    NoOpLogger: [Getter],
    CancellationToken: [Getter],
    Provider: [Getter],
    AppImageUpdater: [Getter],
    MacUpdater: [Getter],
    NsisUpdater: [Getter],
    DOWNLOAD_PROGRESS: 'download-progress',
    UPDATE_DOWNLOADED: 'update-downloaded',
    UpdaterSignal: [class UpdaterSignal],
    autoUpdater: [Getter]
  }
} 
```

**Comment by roddc** [comment]
Hi, I am facing a issue with dynamic import in a bundled app, ```Error: ENOTDIR: not a directory, stat '/tmp/.mount_test-aQxmSmS/resources/app.asar/packages/main/dist/node_modules/electron-updater' ```

**Comment by Tanimodori** [comment]
Duplicate of https://github.com/vitejs/vite/issues/2139
