### ISSUE TITLE
Pre-install target setup

### ISSUE THREAD

**Issue by lyssdod** [electron-userland/electron-builder#734]
Hi, are there any options to run a command/program before running actual installer? For example, my app depends on some native libraries and I have installers for them (for every target platform). How do I run them before actual install? I would like to bundle them into package and run on demand

**Comment by develar** [comment]
Use [custom NSIS](https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script) or handle corresponding Squirrel.Windows event (`--squirrel-install` or `--squirrel-updated`).

**Comment by lyssdod** [comment]
Thanks!
