### ISSUE TITLE
How can I make auto-updater work with changing my main version and CI/CD build new package when new commit pushed

### ISSUE THREAD

**Issue by kafka-yu** [electron-userland/electron-builder#7340]
Hi all,
I'm new to auto-updater, is it possible that I can keep the main version (e.g. 2.0.0), but at the same time I can also make the new package be able to auto-updater, to be a new version? e.g. 2.0.0 build 100, and then 2.0.0 build 101 etc.

**Comment by kafka-yu** [comment]
Any one have suggestions? Or the best practice?

**Comment by mmaietta** [comment]
Wouldn't that just be a patch version? i.e. `2.0.100` and `2.0.101`? [Semver](https://semver.org/) is probably the best practice here
