### ISSUE TITLE
`electron-builder` not working in mac OS ventura. `make` failed with exit code: 2

### ISSUE THREAD

**Issue by injas427** [electron-userland/electron-builder#7341]
* **Electron-Builder Version**: 
`23.6.0`

* **Node Version**: 
`v18.12.1`

* **Electron Version**:
`22.0.0`
* **Electron Type (current, beta, nightly)**:

* **Target**: 
`Mac OS Ventura 13.1 (22C65)`

I've https://github.com/glawson/electron-deeplink native module and when I try `yarn install` the command fails at `postinstall`.

```
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.12.1 | darwin | x64
gyp info find Python using Python version 3.10.9 found at "/usr/local/opt/python@3.10/bin/python3.10"
gyp info spawn /usr/local/opt/python@3.10/bin/python3.10
gyp info spawn args [
gyp info spawn args   '/Volumes/Projects/neeto-planner-electron/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/Projects/neeto-planner-electron/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/Projects/neeto-planner-electron/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/injasmtp/Library/Caches/node-gyp/18.12.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/injasmtp/Library/Caches/node-gyp/18.12.1',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/Projects/neeto-planner-electron/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/injasmtp/Library/Caches/node-gyp/18.12.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/Projects/neeto-planner-electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/binding/src/binding.o', needed by `Release/binding.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/Projects/neeto-planner-electron/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.2.0
gyp ERR! command "/Users/injasmtp/.nvm/versions/node/v18.12.1/bin/node" "/Volumes/Projects/neeto-planner-electron/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/Projects/neeto-planner-electron
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
error Command failed with exit code 1.
```

**Comment by rileycleavenger** [comment]
I'm having the same issue, lmk if you solve it

**Comment by injas427** [comment]
@rileycleavenger The issue happens when I had multiple targets (`mas`, `mas-dev`, `pkg`) set in the configuration. When there are multiple tagrets set, then the native modules are not building properly. When I had only one target set (`mas`), I could generate the build and upload it to the store. But it's not the right solution.

**Comment by mmaietta** [comment]
Can you try the latest `next` version of electron-builder? I transitioned the native module builds to utilize the official `@electron/rebuild` npm package instead of the custom Golang lib that was handling node-gyp directly. Curious if that'll help

**Comment by injas427** [comment]
@mmaietta I've tried the version and still getting the error when multiple targets are set.

<img width="950" alt="Screenshot 2023-01-16 at 3 21 50 PM" src="https://user-images.githubusercontent.com/14922455/212648949-c3577310-63ff-418f-9d69-3a3e303064de.png">

**Comment by Koppel-Zhou** [comment]
> @mmaietta I've tried the version and still getting the error when multiple targets are set.
> 
> <img alt="Screenshot 2023-01-16 at 3 21 50 PM" width="950" src="https://user-images.githubusercontent.com/14922455/212648949-c3577310-63ff-418f-9d69-3a3e303064de.png">

I have the same issue

**Comment by parvans** [comment]
My electron app which is build by using electron-builder is not working in macos ventura 13.6.6
