### ISSUE TITLE
Do we need maintainer with no experience in this?

### ISSUE THREAD

**Issue by OnClickListener2048** [electron-userland/electron-builder#7343]
* **Electron-Builder Version**: 

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**:

**Comment by mmaietta** [comment]
I'm always in favor of having additional maintainers come onboard. Currently it is just me and I still am not familiar with the entire codebase tbh.

All things go through PRs so maintainers can easily collaborate there.
