### ISSUE TITLE
pkgbuild failing with "No package identifier specified and not exactly one component to derive it from."

### ISSUE THREAD

**Issue by michaelwbarry** [electron-userland/electron-builder#7348]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v16

* **Electron Version**:22.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac - dmg, pkg, zip

Pkg builds in pkgbuilder with "pkgbuild: error: No package identifier specified and not exactly one component to derive it from."

Uncommenting line 143 in pkg.ts in app-builder-lib/out/targets/pkg.ts in my node modules fixes it. 

It's line 175 in packages/app-builder-lib/src/targets/pkg.ts in master. It looks like that line was commented out in a commit (f0cb15d2723ee0da263cf2d1a71fcba777133f3f) about 'chore: update deps.' Perhaps it was commented out in error?

There's a backlog issue on this:
https://github.com/electron-userland/electron-builder/issues/4527

**Comment by mmaietta** [comment]
I don't have any context as to why it was previously commented out, the commit message isn't very helpful either 😅 
I'm not opposed to having it uncommented and see what happens, at least in this case we'd have a git issue history/tracking for the change.

**Comment by Ange0** [comment]
j'ai pu contourner ce problème en spécifiant une version stable dans mon package.json

dans mon exemple: donc preciser 
 "devDependencies": {
   ...
    "electron-builder": "^23.6.0",
  ...
  }
