### ISSUE TITLE
NSIS /silent option installs in wrong directory

### ISSUE THREAD

**Issue by TC-mSundaram** [electron-userland/electron-builder#7358]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16.9.1

* **Electron Version**: 16.0.8
* **Electron Type (current, beta, nightly)**: current?

* **Target**: Windows

I have an nsh script for installing on Windows. I found that when adding the `/silent` flag the install is "bare" in `C:\Program Files` i.e. all of the files are in `C:\Program Files` instead of `C:\Program Files\AppName` 

From what I can tell, I am simply passing this `/silent` parameter on

```nsh
  ${StdUtils.TestParameter} $R0 "S"
  ${StdUtils.TestParameter} $R1 "s"
  ${StdUtils.TestParameter} $R2 "silent"
  ${If} $R0 == "true"
  ${OrIf} $R1 == "true"
  ${OrIf} $R2 == "true"
    SetSilent silent
  ${EndIf}
```

I wonder if anyone has come across this issue, and if so, how you resolved it? 

Finally, I have inherited this NSIS `nsh` script, so I am not yet familiar with the syntax but I would like to create a clean up function that when the user runs the installer to upgrade, will safely clean up the previously install files in `C:\Program Files` 

Thank you!

**Comment by mmaietta** [comment]
Hmmm, where are you adding the `/silent` flag? I'm not sure I understand why/where you're using as electron-builder already have that included in the NsisUpdater code
https://github.com/electron-userland/electron-builder/blob/1d130012737e77b57c8923fcc0e6ad2cbc5da0e8/packages/electron-updater/src/NsisUpdater.ts#L107-L111

>user runs the installer to upgrade, will safely clean up the previously install files

From what I understood, the previously installed files should already be getting cleaned up. What is being orphaned/left behind?

**Comment by TC-mSundaram** [comment]
Hi @mmaietta thank you for your reply. The `/silent` flag is used by users installing the app, e.g. `"App.exe" /d="C:\Program Files" /silent`

electron-builder already supports `/S` but we added the above code inside `!macro customInit` in `build/installer.nsh` to additionally allow `/s` and `/silent` parameters.

**Comment by TC-mSundaram** [comment]
As a workaround I did this

```
  ${StrContains} $0 "AppName" $INSTDIR
  StrCmp $0 "" notcontains
    Goto done
  notcontains:
    StrCpy $INSTDIR "$INSTDIR\AppName"
  done:
```

This is inside `customInit` macro.
