### ISSUE TITLE
can I want to know how to make exceptions to certain routes when building an app?

### ISSUE THREAD

**Issue by soboti** [electron-userland/electron-builder#7359]
electron-builder: "21.2.0"

Hi,
I want to know how to make exceptions to certain routes when building an app.
I want to build an app except for the files I specified.
Can I change this by adding a script?
Or I wonder if there is a guide document.

I asked a question using a translator. I don't know if you understand my question well. I'm sorry.
If you don't understand, please leave a comment.

Have a great day!

**Comment by mmaietta** [comment]
>I want to build an app except for the files I specified.

Are you trying to bundle your electron app but only with specific files? If so, that's what the file contents are for https://www.electron.build/configuration/contents

**Comment by soboti** [comment]
> > 내가 지정한 파일을 제외하고 앱을 빌드하고 싶습니다.
> 
> 전자 앱을 특정 파일과만 번들로 묶으려고 합니까? 그렇다면 [https://www.electron.build/configuration/contents 에 대한 파일 내용입니다.](https://www.electron.build/configuration/contents)

First of all, thank you.
I'm sorry for the late reply.
It took me a long time to understand the page you sent me because I am not good at English.
I added the build option to "package.json" as below.
```
  "build": {
    "files": [
      "**/*",
      "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
      "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
      "!**/node_modules/*.d.ts",
      "!**/node_modules/.bin",
      "!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}",
      "!.editorconfig",
      "!**/._*",
      "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}",
      "!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}",
      "!**/{appveyor.yml,.travis.yml,circle.yml}",
      "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}",

      // From now on, these are the options I added.
      "!**/external/*",
      "!**/web/assets/video/*.mp4"
    ]
  }
```

But I want one more thing.
I want to exclude paths only in certain situations with a script.
Is there a way?

Have a nice day.

**Comment by soboti** [comment]
First of all, I inform you that I have solved this problem.

I loaded the javascript file from the script of "package.json".
After that, I modified the build property of package.json using the fs module of "Node.js".

Thank you for your help.
