### ISSUE TITLE
Could not get code signature for running application for signed application

### ISSUE THREAD

**Issue by oltreseba** [electron-userland/electron-builder#7375]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 18.9.0

* **Electron Version**: 21.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg, exe

Every now and then, only for some users, the auto-update process throws the error:

```
Could not get code signature for running application
```

This error has been tracked on our bugtracking system (sentry).

The app the user is using **is correctly signed** as well as the new app. This happens every time we deploy a new update of the app (we have been deploying updates almost every month for 2 years now): some users have random errors (not only this).

Is there any reason why the signature check may fail even if the app is properly signed?

Could the user be having some software on his device somehow altering the application's files (antivirus, clean my mac, etc?) that could lead to problems in verifying the signature?

**Comment by Ahmed-Sarmoum** [comment]
try to add this line at the top of your file 

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

**Comment by oltreseba** [comment]
How is this supposed to help?
Also, all the certificates on our servers are fine, so there should be no need to disable tls validation.
