### ISSUE TITLE
Japanese license file doesn't displayed exact characters

### ISSUE THREAD

**Issue by vvillaluna** [electron-userland/electron-builder#7390]
* **Electron-Builder Version**:  24.0.0-alpha.9

* **Node Version**: 16.19.0

* **Electron Version**: 22.0.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 10

I made a comment under [Here](https://github.com/electron-userland/electron-builder/pull/7339#issuecomment-1401351570) I explained there the problem.

---
**Edited:** This was my concern

What's the difference in the process of reading the license file when using the `multiLanguage` and adding them directly on `license` nsis config ?

Seems like it has differences in the output, 

Using `license: "license_ja.html"` works well.
![image](https://user-images.githubusercontent.com/118970389/214207076-a2992b97-4e4e-4361-9c8c-f4d9fb15ad01.png)

But using multilanguage like putting licenses under build resources is not working properly html tags were included:
![image](https://user-images.githubusercontent.com/118970389/214206612-955e22f7-d89c-40c9-aa67-74024c4eba4b.png)

@mmaietta can you guide me where to check that functionality would like to contribute

**Comment by itsPG** [comment]
I encountered the same issue.

The behavior of "using the multiLanguage " and "adding them directly on license nsis config" are dfferent.

multiLanguage doesn't work in my environment.
