### ISSUE TITLE
Publish to bitbucke: Error: Not supported provider: bitbucket 

### ISSUE THREAD

**Issue by sergeu90** [electron-userland/electron-builder#7395]
* **Electron-Builder Version**:  22.14.13"

* **Node Version**:  v14.20.0

* **Electron Version**: 22.0.1

* **Target**:  windows

<img width="883" alt="image" src="https://user-images.githubusercontent.com/7217517/214677357-d5645cea-63ed-4a42-ab4d-2407a1b3a270.png">

`
    "publish": {
        "provider": "bitbucket",
        "owner": "owner",
        "slug": "reponame"
      },
`

**Comment by le4onardo** [comment]
Hi, could you post all your electron builder config?
I saw 22.14.13 should support bitbucket already
