### ISSUE TITLE
Use standard macOS disk volume icon by default

### ISSUE THREAD

**Issue by matthewpaulthomas** [electron-userland/electron-builder#7401]
Hello!

From [the DMG reference page](https://www.electron.build/configuration/dmg):

> - `icon` String | “undefined” - The path to DMG icon (volume icon), which will be shown when mounted, relative to the [build resources](https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources) or to the project directory. Defaults to the application icon (`build/icon.icns`).

Unfortunately, if you open a DMG directly from your browser downloads, then drag the app out of the mounted volume onto the Desktop, it’s very difficult to tell which is the volume and which is the app — because they have exactly the same icon.

Perhaps the simplest solution would be, if no `icon` is declared, [leave the volume icon unset](https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmg.ts#L151), so that macOS will use the default volume icon. This is common behaviour for Mac apps distributed as DMG, and it’s equivalent to the approach proposed for document icons in #6966.

[I originally encountered this issue in an app, [Zettlr/Zettlr#4101](https://github.com/Zettlr/Zettlr/issues/4101).]

**Comment by mmaietta** [comment]
That seems reasonable for the v24-alpha version since it seems like it'll be "breaking" change. Please open a PR for the change

**Comment by matthewpaulthomas** [comment]
I’m a designer and I’ve never used TypeScript, so my submitting a PR would be a poor use of time both for me and for any unfortunate reviewer. Best I could do was to link to what I guessed were the relevant lines of code.
