### ISSUE TITLE
Snap packages dont use icon declared in desktop file

### ISSUE THREAD

**Issue by stationaryStation** [electron-userland/electron-builder#7406]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 19.5

* **Electron Version**: 22
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux Snap

I am building a snap for an application called [revolt](https://github.com/revoltchat/desktop) (Which is not mine) and I see that the icons from the .destkop file are declared properly, the appimage uses those icons but the snap package doesn't use them and falls back to the executable icon.

Is there a way to make the snap use those icons?

**Comment by stationaryStation** [comment]
An update on the issue: The icon seems to show in other desktop environments but not on gnome.

**Comment by mmaietta** [comment]
Looks like that's expected behavior on gnome
https://access.redhat.com/discussions/4725951
