### ISSUE TITLE
Windows installer not working. Though it works on development windows machine.

### ISSUE THREAD

**Issue by makeitcount** [electron-userland/electron-builder#741]
* **Version**: 5.23.2
* **Target**: Windows, Linux, Mac

I have built windows installer on my windows machine. It works on my machine well. But it does not work on different windows machine.

The app name appears in "uninstall program and features" list. But it's not there in program files or programs list. Does not appear in search either. 

I am using two package.json structure
>
{
  "name": "Test",
  "productName": "TestingElectronPacakging",
  "version": "0.0.2",
  "build": {
    "compression": "normal",
    "appId": "com.random.morerandom",
    "app-category-type": "public.app-category.productivity",
    "asar": true,
    "win": {
      "iconUrl": "https://url_to_asset/assets/favicon_64.png",
      "icon": "build/icon.ico",
      "msi": true
    },
    "mac": {
      "icon": "build/icon.icns"
    }
  },
  "scripts": {
    "test": "xo",
    "start": "cd app && electron .",
    "postinstall": "install-app-deps",
    "pack": "build --dir",
    "dist": "build",
    "build_win32": "build --win --ia32",
    "build_win64": "build --win --x64",
    "build_rpm64": "electron-installer-redhat --src dist/linux/ --dest dist/rpm/ --arch amd64",
    "build_with_epackager": "electron-packager . --out=dist --app-version=$npm_package_version --icon=./assets/img/icon --prune --asar --overwrite --all"
  },
  "devDependencies": {
    "devtron": "latest",
    "electron-builder": "latest",
    "electron-installer-redhat": "^0.3.0",
    "electron-packager": "latest",
    "electron-prebuilt": "latest",
    "xo": "latest"
  }
}

To build installer I run `npm run dist` on my windows machine.
I don't know if this helps but I have added this code in index.js as well
`if (require('electron-squirrel-startup')) return;//for handling squirel startup events`

**Comment by develar** [comment]
Duplicates #551
