### ISSUE TITLE
The title bar icon is not showing.

### ISSUE THREAD

**Issue by hams-i** [electron-userland/electron-builder#7411]
* **Electron-Builder Version**: v23.6.0

* **Node Version**: v18.12.1

* **Electron Version**:22.2.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: win

this is my build: 
If I make the icon extensions to .ico in the package.json, the icon next to the title bar does not appear when I run it as an application.
![22](https://user-images.githubusercontent.com/44506956/216848553-7ed16526-e9bf-4a2a-ad89-3e8f4186b124.png)
"build": {
    "appId" : "(...)",
    "productName":"(...)",
    "win":{
        "target": "nsis",
        "icon": "build/icon.ico"
    },
    "directories":{
        "output":"dist"
    },
    "nsis": {
        "perMachine": true,
        "installerIcon": "build/icon.ico",
        "uninstallerIcon": "build/icon.ico",
        "oneClick": false,
        "allowToChangeInstallationDirectory": true,
        "deleteAppDataOnUninstall": true
    },
    "artifactName":"${productName}-${version}.${ext}"
  },

If I png the icon extensions in package.json, it extracts the "win-unpacked" folder to the dist folder. The icon appears in the title bar of the portable application in the win-unpacked folder. But where is the installation .exe? why did it give an error while installing it?
![33](https://user-images.githubusercontent.com/44506956/216848783-ea170469-54b0-40ae-bd2b-021c769971c4.png)
"build": {
    "appId" : "(...)",
    "productName":"(...)",
    "win":{
        "target": "nsis",
        "icon": "build/icon.png"
    },
    "directories":{
        "output":"dist"
    },
    "nsis": {
        "perMachine": true,
        "installerIcon": "build/icon.png",
        "uninstallerIcon": "build/icon.png",
        "oneClick": false,
        "allowToChangeInstallationDirectory": true,
        "deleteAppDataOnUninstall": true
    },
    "artifactName":"${productName}-${version}.${ext}"
  },

Error while loading icon from "appnme\build\icon.png": invalid icon file

**Comment by hams-i** [comment]
I tried turning the computer off and on. the problem persisted.
There is no problem with the desktop shortcut icon, the start icon, the icon in the control panel(app uninstall menu). Only the icon in the title bar of the program does not appear.

**Comment by mmaietta** [comment]
If it's only that specific size of an icon, then maybe the `.ico` file doesn't have all the correct icon dimensions that are supporting multiple scale factors. Please see: https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction
