### ISSUE TITLE
Build not arm64, even though it says it is building for that. 

### ISSUE THREAD

**Issue by iamjohnbarker** [electron-userland/electron-builder#7412]
* **Electron-Builder Version**: 23.0.2

* **Node Version**: 16.17.0

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

I cannot seem to get electron-builder to package my macOS app for arm64, even though it assures me that is is indeed trying to do that. 

```
rebuilding native dependencies  dependencies=fsevents@1.2.13, fsevents@1.2.13 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=22.0.0 appOutDir=dist/mac-arm64
  • signing         file=dist/mac-arm64/APP_NAME.app identityName=Developer ID Application: XXX identityHash=XXX provisioningProfile=none
  • building        target=macOS zip arch=arm64 file=dist/APP_NAME-arm64-mac.zip
  • building        target=DMG arch=arm64 file=dist/APP_NAME-2.14.0-arm64.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/APP_NAME-2.14.0-arm64.dmg.blockmap
  ```

When installed it still claims its an Intel app.
<img width="259" alt="Screenshot 2023-02-07 at 10 53 37" src="https://user-images.githubusercontent.com/7009061/217211521-970c55ee-bf1d-4282-926d-b20eb155c187.png">

I'm using the `"electron-pack-m1": "electron-builder -c.extraMetadata.main=build/electron.js --arm64"` script to pass in the --arm64 prop.

**Comment by mmaietta** [comment]
Please try `latest` (23.6.0) or `next` (24.0.0), the latter leverages the official `@electron/rebuild` for building deps
