### ISSUE TITLE
Bug: NSIS Installer fails to check if app is running

### ISSUE THREAD

**Issue by mkozonits** [electron-userland/electron-builder#7413]
Which version of electron-builder are you using?

* **23.6.0**: 

Which version of node are you using?
* **14.17.3**: 

Which version of electron are you using?

* **20.0.2**:
* **not electron related**:

For which target are you building for?
* **Windows 10 x64**: 

The issue occurs with the following config for NSIS installer: 
* perMachine = false

Before the NSIS Installer/Uninstaller does any modifications, it will check, if the app is currently running. After this change https://github.com/electron-userland/electron-builder/pull/6472 the installer will only check for running app with the same user (which is currently logged in), not for the whole system.

![image](https://user-images.githubusercontent.com/35677427/217278114-b3dcbae6-cc63-4859-8e0e-01c16cfc3155.png)

This line of code checks for running app with "tasklist" and then filtering with "find" in case there is some unexpected output or an error.
Here comes the problem: If the name of the .exe file is too long, it will get cut off by windows with the "tasklist" command. If that is the case, "find" will not find the whole app .exe name anymore, and therefore assumes, that no app is currently running.

Here I attach an picuture of an example why this "find" breaks the logic:

![image](https://user-images.githubusercontent.com/35677427/217279957-bffcda20-97a7-4c35-8e66-ddd6be04943b.png)

**Comment by mmaietta** [comment]
Nice find, that's quite some odd behavior.
What's a good alternative to use then?

**Comment by mkozonits** [comment]
This would be possible https://stackoverflow.com/a/56577365
or there is also a option to output in tasklist in csv to have the full name, I don't know which one is the best for our case
