### ISSUE TITLE
NSIS Installer Is Making the App the Default Opener When File Associations Are Defined

### ISSUE THREAD

**Issue by arman-canva** [electron-userland/electron-builder#7414]
* **Electron-Builder Version**: `23.6.0`

* **Node Version**: `18.11.0`

* **Electron Version**: `22.0.2`
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows/NSIS

**Summary**
The NSIS installer is making our app the default file opener when file associations are defined.
Ideally, it would be possible to support opening a given file format without being the default opener.

**Current behaviour:**
Our app is becoming the default opener for associated file formats on Windows.
Ideally, this would not be the case.

**Expected behaviour:**
It would be possible to register a given file association without the app becoming the default opener on Windows.

**Notes:**
There is an exception to the current behavior where, if a user has manually set another application as the default file opener for a given file extension, the current `electron-builder` configuration will not supersede that decision.

**Comment by arman-canva** [comment]
Update: Commenting out [these lines](https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/app-builder-lib/templates/nsis/include/FileAssociation.nsh#L67-L70) produces the expected behaviour.

**Comment by arman-canva** [comment]
I'm wondering whether [unwinding this behaviour](https://github.com/electron-userland/electron-builder/pull/7419) would be an option; esp. considering users seem to find it intrusive/confusing.

**Comment by arman-canva** [comment]
Update: Further testing suggests that this issue could be specific to Microsoft Office-related files (`.docx`, `.pptx`, `.xlsx`). Has anyone else run into this sort of problem before?

**Comment by Imperat** [comment]
ping
