### ISSUE TITLE
[Bug]: Build RedisInsight for Mac Apple Store doesn't launch from TestFlight

### ISSUE THREAD

**Issue by zalenskiSofteq** [electron-userland/electron-builder#7417]
* **Electron-Builder Version**: ^23.6.0

* **Node Version**: 16.15.1

* **Electron Version**: ^22.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: 
Mac Apple Store

### Expected Behavior

Build for Mac Apple Store should launch from TestFlight

### Actual Behavior

Build for Mac Apple Store doesn't launch from TestFlight. It crashes without any error and log

![RedisInsight_crash](https://user-images.githubusercontent.com/63463140/218084975-63c59185-1232-49ec-a967-a1d433268d25.gif)

### Additional information

Steps: 
1. Package and sign (Developer ID Application and Apple Distribution certificates) builds
2. upload to the https://appstoreconnect.apple.com/
3. Enable to download package from TestFlight
4. Try to launch from TestFlight

Answer from the Apple support team:
>  When reviewing the screen recording it is likely this is due to a coding issue within the app. We’ve determined that your question should be addressed by the support channel for Electron - the third-party resource you are using.

Links:
1. branch for MAS in our public repo: https://github.com/RedisInsight/RedisInsight/tree/build/mas
2. electron-builder config https://github.com/RedisInsight/RedisInsight/blob/build/mas/electron-builder.json
3. build pipeline https://app.circleci.com/pipelines/github/RedisInsight/RedisInsight/5608/workflows/71ba96d2-44a9-4c7e-8922-8df47d8c8f55/jobs/71418
4. related issue in the electron repo: https://github.com/electron/electron/issues/37220

I will be grateful for any help

**Comment by mmaietta** [comment]
Generally, errors like this relate to improper entitlements being applied to your electron app. There is `entitlements`, `entitlementsInherit`, and `entitlementsLoginHelper` that may need to be provided

**Comment by zalenskiSofteq** [comment]
> Generally, errors like this relate to improper entitlements being applied to your electron app. There is `entitlements`, `entitlementsInherit`, and `entitlementsLoginHelper` that may need to be provided

Interesting. I already provided them:
[electron-builder.json#mas.entitlements](https://github.com/RedisInsight/RedisInsight/blob/c66f9495d0a6c0b82f2f4426c8f55fbdb115e9b8/electron-builder.json#L42)
[entitlements.mas.plist](https://github.com/RedisInsight/RedisInsight/blob/build/mas/resources/entitlements.mas.plist)

**Comment by JIACHENG135** [comment]
@zalenskiSofteq I'm facing same issue. And i noticed it happened when you made a https request call to non localhost endpoint. the developer tool is showing `Provisional headers are shown` then failed the xhr call. I'm not sure if they are related or not. Hope your issue can be fixed soon. 
![Image 2-24-23 at 22 22](https://user-images.githubusercontent.com/31320373/221342203-a116f162-37ff-418c-9952-f2b61d6f894d.jpg)
This is the screenshot of the app installed from testflight. I'm interested if you meet this error before? Thanks in advance for any help!

**Comment by xieerduos** [comment]
> @zalenskiSofteq我有同样的问题。解决了吗？ 如果还没有解决，请您在终端输入`lldb /Applications/RedisInsight.app`和，通过运行检查是否是同一个日志？ 这是我的日志。`run`
> 
> ```
> [75718:0403/233943.624625:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233943.626116:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233943.762069:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233943.762850:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233943.794908:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233943.827328:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233943.859402:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233943.891014:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233943.923358:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233943.955267:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233943.989621:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233944.023695:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233944.057460:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233944.090689:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233944.123564:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233944.155913:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233944.189068:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
> [75718:0403/233944.194164:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=5
> [75718:0403/233944.194179:FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye.
> ```

I also encountered the same problem. Is there a solution
