### ISSUE TITLE
Codesigning and notarize fail in all the v24 builds

### ISSUE THREAD

**Issue by pantelispanayiotou** [electron-userland/electron-builder#7418]
* **Electron-Builder Version**: 
24.0.0-alpha3,5,7,911 and 23.6.0

* **Node Version**: 
16.10.0

11.1.0

* **Target**: 
Universal

I really need to use x64ArchFiles option which is allowed to be used from 24.0.0-alpha3 and up in order to make a universal build. The build is successfully signed and notarized in all of my trial but wjen i open it it immediately closes and says either that the developer cant be verified or in console it says Code Signature Invalid. In 23.6.0 version everything works fine. Has anything major changes that i also have to alter in my config?

**Comment by mmaietta** [comment]
This is the entire diff: https://github.com/electron-userland/electron-builder/compare/v23.6.0...v24.0.0-alpha.3
This is the only aspect that seems to differ that could be related (from my brief look through the changelog)
```
-    "@electron/universal": "1.2.1",
+    "@electron/universal": "1.3.3",
```
