### ISSUE TITLE
fix [demo] ：There seems to be an error in the example here

### ISSUE THREAD

**Issue by RSS1102** [electron-userland/electron-builder#7422]
https://github.com/electron-userland/electron-builder/blob/dba9cfa73257b4993fac41cea825c73f7d733353/encapsulated%20manual%20update%20via%20menu.js#L27

[electron docs ：](https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options)
```text
Returns Promise<Object> - resolves with a promise containing the following properties:

response number - The index of the clicked button.
checkboxChecked boolean - The checked state of the checkbox if checkboxLabel was set. Otherwise false.
```

---
should be?
```ts
 if (buttonIndex.response  === 0) { 
```

**Comment by mmaietta** [comment]
Yes, that appears to be correct. Maybe the API has changed since the demo docs were first written.
I'll update the docs accordingly.
