### ISSUE TITLE
Correct Way To Notarize an Apple DMG Through Electron

### ISSUE THREAD

**Issue by KristinaPlusPlus** [electron-userland/electron-builder#7424]
I followed the electron documentation for code signing: https://www.electron.build/code-signing and specifically followed the article where it mentioned how to notarize (from 2019): https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

I distribute a DMG outside the Mac store by signing and notarizing the app but not the DMG.  This does not throw any errors.

However, I was questioning what was the official Apple recommendation.  I am starting to wondering if I need to sign my application and then sign and notaize the DMG instead: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

Then I see the following issue: https://github.com/electron/notarize/issues/60

So my question is whether the electron build website's official guidance is out of date and goes against the Apple guidance?  Or are both acceptable for Apple's standards?  I couldn't find any article that negates what electron recommends but I can't quite find evidence it is correct.

What is the 2023 recommendation from electron on how to sign and notarize?  Is it the same?

**Comment by mmaietta** [comment]
AFAIK, dmg's are not supposed to be notarized.
`.app` should be notarized. I'm not aware of `.pkg` requiring it, but there's nothing electron-builder can do there since it just leverages `electron/notarize` directly.

**Comment by KristinaPlusPlus** [comment]
@mmaietta - Just for clarification, if my `.app` is signed and notarized and I am not notarizing the `.dmg`, should I sign the `.dmg`?  Or also not even sign the `.dmg`?

**Comment by keomabrun** [comment]
Sorry to reopen this thread, but from what I read in the mentioned thread, it is recommended to sign the disk image file (dmg).
Is there a way to do that with electron-builder ? (I haven't found so far).
Are you not facing Gatekeeper issues if you only notarize the .app ?

Thank you for this amazing tool !
