### ISSUE TITLE
Set title for GitHub release (GithubOptions) 

### ISSUE THREAD

**Issue by bra1n** [electron-userland/electron-builder#7426]
Full details in #3225 which was closed but not resolved.

TL;DR: it's currently not possible to set the Github Release title, as it will always be set to the version number.

**Comment by CubE135** [comment]
Can confirm this.

**Comment by mmaietta** [comment]
Feel free to open a PR to add that configuration property

**Comment by CubE135** [comment]
> Feel free to open a PR to add that configuration property

Should it not be possible already?
https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-releaseInfo

Looks like a bug or wrong docs to me

**Comment by mmaietta** [comment]
IIRC, that's for the name attached to the UpdateInfo. Not directly translated to GitHub release title which is the default version number (per GitHub)

Feel free to open a PR adding a `name` field added to `GithubOptions`, that should make it to the Publisher for "create Version"

**Comment by bra1n** [comment]
Not stale
