### ISSUE TITLE
post-install script doesn't run

### ISSUE THREAD

**Issue by msotnikov** [electron-userland/electron-builder#7429]
* **Electron-Builder Version**: 23.3.3
* **Node Version**: 18
* **Electron Version**: 19
* **Electron Type (current, beta, nightly)**: current
* **Target**: any

The post-install script doesn't run . In my case it contain patch-package to fix a native builds.

**Comment by mmaietta** [comment]
This sounds like a config problem, unrelated to electron-builder. electron-builder is a packager, not to be confused with a package manager, like `npm` that would run a `postinstall: "patch-package"` script.
