### ISSUE TITLE
Don't throw an error if version doesn't start with `v´

### ISSUE THREAD

**Issue by leo** [electron-userland/electron-builder#743]
IMHO, there's no reason to strictly throw an error [here](https://github.com/electron-userland/electron-builder/blob/master/src/publish/gitHubPublisher.ts#L81). Instead of doing that, we should just log the suggestion and let things like Travis CI simply pass on with other tasks.

For example: At HyperTerm we're [not using](https://github.com/zeit/hyperterm/tags) the "v" (because there's simply no point in using it), but we would still like to use the "GitHub publisher" feature... 😊

**Comment by develar** [comment]
Problem is that we search version by v-prefixed tag name — https://github.com/electron-userland/electron-builder/blob/master/src/publish/gitHubPublisher.ts#L53 

Solution — use both variants to find and log warn instead of throwing error.

**Comment by leo** [comment]
@develar That sounds like a great way to handle it!

**Comment by leo** [comment]
@develar Is this a big change? Probably not, right? Is there are chance that you could fix this and release a patch? We're going to release a big thing and would like to use this feature for it.

**Comment by develar** [comment]
@leo Sorry, I missed your last message. Fixed.

`build.publish.vPrefixedTagName` can be set to `false` to create tag name without `v` prefix. Regardless of this option, `v` is not required anymore, both variants are checked.

**Comment by leo** [comment]
@develar Cool, thanks! 👍 😊
