### ISSUE TITLE
Docker image for electron  23.1.0 with node 18.12.1

### ISSUE THREAD

**Issue by grafanauser** [electron-userland/electron-builder#7430]
electron 23 uses node 18 now under the hood. But currently there are only electron-builder docker images available for older electron versions. Like this one for electron 22: electronuserland/builder:16-wine-10.22
https://hub.docker.com/layers/electronuserland/builder/16-wine-10.22/images/sha256-b3bdbed7d794b8e4a2cc908e5a1049d4d0f0f4be446b99d870b335085155dc32?context=explore

Can someone create an image for node 18 for electorn 23? e.g. "electronuserland/builder:18-wine..." 
Electron 23.1.0 uses Node 18.12.1: https://releases.electronjs.org/release/v23.1.0

Sadly I am not really familiar with docker, so i cannot help with that. But I saw it has been done in the past for electron 15 (node 16) https://github.com/electron-userland/electron-builder/issues/6405

Thanks in advance :)

**Comment by mmaietta** [comment]
Done https://hub.docker.com/repository/docker/electronuserland/builder/tags?page=1&ordering=last_updated
`electronuserland/builder:18`
