### ISSUE TITLE
electron-builder hangs for user other than root in ubuntu 20.04

### ISSUE THREAD

**Issue by alishefaee** [electron-userland/electron-builder#7434]
Which version of electron-builder are you using?<br>
package.json:
```json
{
  "name": "name",
  "private": true,
  "version": "0.0.0",
  "description": "desc",
  "main": "electron/main.js",
  "author": {
    "name": "name",
    "email": "email"
  },
  "scripts": {
    "electron:dev": "node scripts/dev.mjs",
    "electron:build": "electron-builder"
  },
  "build": {
    "appId": "com.electron.w",
    "productName": "<product-name>",
    "extraResources": [
      {
        "from": "./resources/",
        "to": "resources",
        "filter": [
          "**/*"
        ]
      }
    ],
    "publish": [
      {
        "provider": "generic",
        "url": "http://127.0.0.1:8080/"
      }
    ],
    "linux": {
      "target": [
        "deb"
      ],
      "category": "Utility",
      "icon": "./icon/logo.png"
    },
    "win": {
      "target": [
        "portable"
      ],
      "icon": "./icon/logo.png"
    },
    "portable": {
      "artifactName": "WasteManagement.exe"
    }
  },
  "dependencies": {
    "electron-log": "^4.4.8",
    "electron-root-path": "^1.1.0",
  },
  "devDependencies": {
    "electron": "^22.0.1",
    "electron-builder": "^23.6.0",
  }
}

```

Which version of node are you using?
v18.14.1

For which target are you building for?
deb

problem:
when I run ```npm run electron:build``` (which execute ```electron-builder```) it stops in this line:
```
  • electron-builder  version=23.6.0 os=5.15.0-46-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=22.0.1 appOutDir=dist/linux-unpacked

```
no matter how much I wait.
what I tried:
* I tried logout and then login with root user (using gui login page) and **it worked**. but I do not want to login as root always.
* I tried with privileged permissions by using (```sudo su```) but **no luck**.
* I tried to change ```opt``` folder permission (```chmod 777 opt```) if it is related to that but **did not work**.
* I used window 10 and it **worked** for window version.

what I expected:
use electron-builder to build deb version of application.

**Comment by mmaietta** [comment]
Maybe there's a permission/ownership issue with the volumes that are being mounted to the contatiner or something like that?

I've used electron-builder for a long time with docker using non-root and have had zero issues.
