### ISSUE TITLE
build hang on

### ISSUE THREAD

**Issue by codeongit** [electron-userland/electron-builder#744]
* **Version**: 
electron-builder@6.7.3
* **Target**: 
 platform win32 x64 

below is the console message on my mac pro
> npm run compile && build -w
> @ compile /Users/will/IdeaProjects/onshape-desktop-shell
> rimraf app/out && tsc
Skip app dependencies rebuild because platform is different
Packaging for platform win32 x64 using electron 1.3.5 to dist/win-unpacked
Warning: Application icon is not set, default Electron icon will be used
Building Squirrel.Windows installer
Sync releases to build delta package

and just hang on.......
i want to see if there is a way  to show the debug  message.
i have read through the docs and issues,still have no idea.
so any help will be appreciate.

**Comment by develar** [comment]
> Sync releases to build delta package

It can took a lot of time (10 minutes).

**Comment by codeongit** [comment]
thx,it fixed.
