### ISSUE TITLE
fails on building universal on Mac M1

### ISSUE THREAD

**Issue by pingleware** [electron-userland/electron-builder#7440]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 19.4.0

* **Electron Version**: 23.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: universal (x64 and amr64(

uniqueToX64: [],
  uniqueToArm64: [
    '._Contents',
    'Contents/._Frameworks',
    'Contents/._Info.plist',
    'Contents/._MacOS',
    'Contents/._PkgInfo',
    'Contents/._Resources',
    'Contents/Frameworks/._Electron Framework.framework',
    'Contents/Frameworks/._Mantle.framework',
    'Contents/Frameworks/._ReactiveObjC.framework',
    'Contents/Frameworks/._Squirrel.framework',
    'Contents/Frameworks/._credit-reporting-agency Helper (GPU).app',
    'Contents/Frameworks/._credit-reporting-agency Helper (Plugin).app',
    'Contents/Frameworks/._credit-reporting-agency Helper (Renderer).app',
    'Contents/Frameworks/._credit-reporting-agency Helper.app',
    'Contents/Frameworks/Electron Framework.framework/._Electron Framework',
    'Contents/Frameworks/Electron Framework.framework/._Helpers',
    'Contents/Frameworks/Electron Framework.framework/._Libraries',
    'Contents/Frameworks/Electron Framework.framework/._Resources',
    'Contents/Frameworks/Electron Framework.framework/._Versions',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/._chrome_crashpad_handler',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/._libEGL.dylib',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/._libGLESv2.dylib',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/._libffmpeg.dylib',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/._libvk_swiftshader.dylib',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/._vk_swiftshader_icd.json',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._Info.plist',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._MainMenu.nib',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._af.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._am.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ar.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._bg.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._bn.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ca.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._chrome_100_percent.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._chrome_200_percent.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._cs.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._da.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._de.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._el.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._en.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._en_GB.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._es.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._es_419.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._et.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._fa.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._fi.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._fil.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._fr.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._gu.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._he.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._hi.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._hr.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._hu.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._icudtl.dat',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._id.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._it.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ja.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._kn.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ko.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._lt.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._lv.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ml.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._mr.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ms.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._nb.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._nl.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._pl.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._pt_BR.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._pt_PT.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._resources.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ro.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ru.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._sk.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._sl.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._sr.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._sv.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._sw.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ta.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._te.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._th.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._tr.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._uk.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._ur.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._vi.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._zh_CN.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/._zh_TW.lproj',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/af.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/am.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/ar.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/bg.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/bn.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/ca.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/cs.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/da.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/de.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/el.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en_GB.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/es.lproj/._locale.pak',
    'Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/es_419.lproj/._locale.pak',
    ... 149 more items
  ]
}
  ⨯ While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds  failedTask=build stackTrace=Error: While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds

**Comment by mmaietta** [comment]
Looks like you're running into an issue with `electron/universal` dependency due to a misconfiguration on your side. I think you need to use one of these two params:
https://github.com/electron/universal/blob/main/src/index.ts#L39-L46

The options are also specified here: https://www.electron.build/configuration/mac
