### ISSUE TITLE
Any way to launch app after macOS install?

### ISSUE THREAD

**Issue by aguynamedben** [electron-userland/electron-builder#7443]
* **Electron-Builder Version**: 23.1.0
* **Node Version**: 16.17.1
* **Electron Version**: 13.6.9
* **Target**: macOS

Is there a way to launch the app after the user installs on macOS? We're distributing the .dmg with a the "drag-and-drop" workflow, then the user must go to the Applications folder and open the app. This is a common flow on macOS, but some install flows automatically launch the app after install.

Does electron-builder have any way to automatically launch the app after install?

**Comment by mmaietta** [comment]
I'm not aware of any auto-launch functionality/hooks that works post drag-n-drop on MacOS.

For other install flows that you're mentioning, maybe those are using a `.pkg` install method?

**Comment by aguynamedben** [comment]
@mmaietta Cool, thanks for chiming in to confirm I wasn't missing something.
