### ISSUE TITLE
PeerDependencies are not fetched when using git+ssh synthax

### ISSUE THREAD

**Issue by dark-matter-matters** [electron-userland/electron-builder#7446]
* **Electron-Builder Version**: 
 • electron-builder  version=23.6.0 os=10.0.22000
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=22.2.0 appOutDir=dist\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=distApp Setup0.1.0.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist\App Setup 0.1.0.exe.blockmap

Electron-builder is incorrectly fecthing my node_modules. il doesn't include some _peerDependencies_ from an external project included with a _git+ssh_ url. In the lines below, the dependency   *@mui/x-data-grid* (amongst others) is not present in the ASAR's node_modules.

```json
"dependencies": {
    "externalDep": "git+ssh://git@192.168.0.10:LIBS/externalDep.git#develop"
  },
```
externalDep's package.json 
```json
 "peerDependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.6.2",
    "@mui/material": "^5.7.0",
    "@mui/x-data-grid": "^5.11.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },
```

I am able to build a working ASAR, but I can't feed it to electron-builder. Electron-packager has a very handful option called *prebuiltAsar* (https://electron.github.io/electron-packager/main/interfaces/electronpackager.options.html#prebuiltasar) for this use case.  

Is there any way to bypass the default ASAR building to include my own archive (an option like _prebuiltAsar_ I wouldn't have found) ? Setting  `"includeSubNodeModules": true` did not change anything.

# Workaround
As a workaround, to include the missing *peerDependencies*, I have written two scripts that will automatically include the missing dependencies on the *package.json*. Note that runing `npm install` is NOT required as adding these lines on the *package.json* is enough to fix this issue. They have to be included in the *build* section : 
package.json
```json
"build": {
    "beforePack": "build-scripts/addPeerDeps.js",
    "afterPack": "build-scripts/removePeerDeps.js",
}
```
addPeerDeps.js
```js
"use strict";

const fs = require("fs-extra");
const path = require("path");

const mainLocation = path.resolve(__dirname, "../package.json");
const mainBackupLocation = path.resolve(__dirname, "../package.json.bak");
const externalDep1Location =
  path.resolve(__dirname, "../node_modules/externalDep1/package.json");
const externalDep2Location =
  path.resolve(__dirname, "../node_modules/externalDep2/package.json");
/**
 * Workaround for bug https://github.com/electron-userland/electron-builder/issues/7446
 * Peer dependencies of external packages are not included in the ASAR archive,
 * So we have to manually add them on the main package.json
 * @param {*} _context
 */
exports.default = (_context) => {
  const rawMainPackageFile = fs.readFileSync(mainLocation);
  const mainPackageFile = JSON.parse(rawMainPackageFile.toString());
  const externalDep1PackageFile = JSON.parse(
    fs.readFileSync(externalDep1Location.toString())
  );
  const externalDep2PackageFile = JSON.parse(
    fs.readFileSync(externalDep2Location).toString()
  );

  // Create a copy to restaure it after build
  fs.writeFileSync(mainBackupLocation, rawMainPackageFile);

  const peerDeps = {
    ...externalDep1PackageFile.peerDependencies,
    ...externalDep2PackageFile.peerDependencies,
  };
  mainPackageFile.dependencies = {
    ...mainPackageFile.dependencies,
    ...peerDeps,
  };

  fs.writeFileSync(mainLocation, JSON.stringify(mainPackageFile));
};

```
removePeerDeps.js
```js
"use strict";

const fs = require("fs-extra");
const path = require("path");

const mainLocation = path.resolve(__dirname, "../package.json");
const mainBackupLocation = path.resolve(__dirname, "../package.json.bak");

/**
 * Restaure the original package file
 * @param {*} _context
 */
exports.default = (_context) => {
  const rawBackupPackageFile = fs.readFileSync(mainBackupLocation);
  fs.writeFileSync(mainLocation, rawBackupPackageFile);
  fs.removeSync(mainBackupLocation);
};
```

**Comment by mmaietta** [comment]
A prebuilt asar (or maybe it's just an `<os>-unpacked` dir?) can be used with `prepackaged: <path>` IIRC. Would that serve your purpose? I honestly haven't used it before, but I do see it in the codebase.
