### ISSUE TITLE
checkForUpdates resolve value seems to be incomplete

### ISSUE THREAD

**Issue by RobMayer** [electron-userland/electron-builder#7447]
```checkForUpdates(): Promise<UpdateCheckResult | null>;```

does the promise resolving to null mean that there is no update available?
- if so, why does the update-not-available event contain an UpdateInfo payload? - the pattern is inconstent.
- if not, do I really need to compare the updateInfo version to the app's current version myself?

**Comment by mmaietta** [comment]
Great question. It'll resolve null if the updater is not "active"
https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/electron-updater/src/AppUpdater.ts#L266-L269

It mainly checks this: 
https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/electron-updater/src/AppUpdater.ts#L296
But for AppImages it is overridden
https://github.com/electron-userland/electron-builder/blob/4684ac55937780f4f8cdeab225739eceb97af795/packages/electron-updater/src/AppImageUpdater.ts#L18-L28

**Comment by mmaietta** [comment]
Looks like it compares version numbers already for you
https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/electron-updater/src/AppUpdater.ts#L367-L395

**Comment by RobMayer** [comment]
That's not accessible in the UpdateCheckResult that the check result promise resolves to.

let me put this another way:

```typescript
autoUpdater.checkForUpdates().then((checkResult) => {
        if (checkResult) { //Updates are not disabled
          // Now what? There is no direct way to know if an update is avaiable or if there is no new update. Do I have compare the checkResult.updateInfo.version against the user's version myself?
          // 
          checkResult.updateInfo.version
        }
      }).catch((e) => {
        reject(e);
      });
```
or I have to do this:

```typescript
() => {
    return new Promise((resolve, reject) => {
      autoUpdater.on("update-available", (info) => {
        resolve({ info, status: "AVAILABLE" });
      });

      autoUpdater.on("update-not-available", (info) => {
        resolve({ info, status: "UNAVAILABLE" });
      });

      autoUpdater.on("error", (e) => {
        reject(e);
      });

      autoUpdater.checkForUpdates().catch((e) => {
        reject(e);
      });
    });
  })
```

**Comment by mmaietta** [comment]
```
() => {
    return new Promise((resolve, reject) => {
      autoUpdater.on("update-available", (info) => {
        resolve({ info, status: "AVAILABLE" });
      });

      autoUpdater.on("update-not-available", (info) => {
        resolve({ info, status: "UNAVAILABLE" });
      });

      autoUpdater.on("error", (e) => {
        reject(e);
      });

      autoUpdater.checkForUpdates().catch((e) => {
        reject(e);
      });
    });
  })
```
This looks to be correct AFAICT. I haven't used electron-updater directly in my projects before as we used a C++ native addon for mounting dmg and replacing the .app file directly (not something that could be made available via electron-updater otherwise it'd break multi-platform builds). We also had C++ addons for rpm and deb updates, which I was actually able to translate into JS code for (beta) usage in electron-builder v24

**Comment by RobMayer** [comment]
stop me if I'm wrong, but doesn't that leave orphaned listeners? even i made them "once" rather than "on" that's still an orphaned listener?
I *can* refactor to destroy the listeners when the event fires, and I probably will, but I'm more pointing out that being able to not know if an update is available or not seems like a no-brainer to be within the resolve value of "checkForUpdates"

**Comment by mmaietta** [comment]
Traditionally, I don't think it was meant to have all listeners wrapped in a promise, rather, you use some other state management to be prepared for any update being available at any time and the `autoUpdater.on(....)` is just sitting in `app.on('ready',...)`
No idea re: orphaned listeners.
