### ISSUE TITLE
A JavaSript error occurred in the main process

### ISSUE THREAD

**Issue by codeongit** [electron-userland/electron-builder#745]
* **Version**: 
electron-builder@6.7.3
* **Target**: 
 platform win32 x64 

![image](https://cloud.githubusercontent.com/assets/5747175/18429410/b8dad300-7905-11e6-852b-d37cef2692bd.png)
I think it is not a problem with the build target.
because i run the .exe in the unpacked folder and show the same message. 
don't work on my virtual machine  and my colleague's machine
The application is the Onshape application.
thank you for your time :)

**Comment by develar** [comment]
Do you build project on windows?

**Comment by codeongit** [comment]
no, on my mac.
the packed exe is weird "Onshape Setup 0.5.3.exe" with space.
"Onshape-Setup-0.5.3.exe" not with -

**Comment by develar** [comment]
Please pay attention to log message about native dependencies.

https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**If your app has native dependencies, it can be compiled only on the target platform. **
