### ISSUE TITLE
 Is it possible to get an Android (APK) build?

### ISSUE THREAD

**Issue by Nimesha-Chamod** [electron-userland/electron-builder#7457]
I am using Electron for one of my projects. Is it possible to get an Android (APK) build?  I want to install it on Android OS box.

**Comment by mmaietta** [comment]
>target = AppImage String | [TargetConfiguration](https://www.electron.build/cli#targetconfiguration) - Target package type: list of AppImage, flatpak, snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir

https://www.electron.build/configuration/linux

Never tried it before, but `apk` is listed as a `target` option.
