### ISSUE TITLE
Electron builder Mac App signing identity issue for mas build

### ISSUE THREAD

**Issue by nishchal-v** [electron-userland/electron-builder#7458]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v14.15.3

* **Electron Version**: 5.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas

Upon firing following commands for my electron app

export CSC_IDENTITY_AUTO_DISCOVERY=false
export CSC_NAME="3rd Party Mac Developer Application: Comp name (12345)"
npm run build:prod && electron-builder build --mac

it throws error
* ⨯ Please remove prefix "3rd Party Mac Developer Application:" from the specified name — appropriate certificate will be chosen automatically

The issue is I want to use that specific certificate to sing the mac app. If I don't specify then it takes any random XYZ cert from keychain and starts signing (Obviously that will lead to invalid code signing).

Also I have tried to add "identity" key for mac specifications in electron-builder.jason. But that throws the same error while building the production build.

How to provide the signing identify to sign the .pkg using "3rd Party Mac Developer Installer" certificate?

**Comment by mmaietta** [comment]
Have you considered including a specific keychain committed to your repo? Then you only need to include the explicit certificates you need (instead of using system keychain) and can use `CSC_LINK` and `CSC_KEY_PASSWORD`

I've not used `CSC_NAME` before, but it looks like `export CSC_NAME="Comp name (12345)"` would work?

**Comment by nishchal-v** [comment]
@mmaietta using
 export CSC_KEYCHAIN=KeychainName

Does not work, I have created a separate keychain and put my certs there. But it does not try to use certs from the specified keychain and fails to find in the login keychain.

**Comment by nishchal-v** [comment]
It's resolved, you need to specify the extension as well.

`export CSC_KEYCHAIN=KeychainName.keychain`

The builder will look into that keychain only whether it is your default keychain or not. Works as a charm!
