### ISSUE TITLE
Installation fails when already installed and symlink are present

### ISSUE THREAD

**Issue by virror** [electron-userland/electron-builder#746]
- **Version**: 6.7.3

- **Target**: win32

When i install my program, i have one folder thats moved out of the app folder and a symlinc is created in its place, because this folder can not change between software updates. 
The problem is when i try to install the same version again without uninstalling first, then the installation crashes with the following error:
Failed to remove existing directory on full install, is the app still running???: System.IO.DirectoryNotFoundException: Could not find a part of the path 'thePath'

**Comment by develar** [comment]
Please use app data directory and do not modify installation folder.

**Comment by virror** [comment]
Moving and creating a symlink is the only way i can make sure a folder thats send with the installation is not changed on update or reinstall

**Comment by develar** [comment]
Put such data to use app data and update/reinstall will not touch it. What's the issue?
