### ISSUE TITLE
Mac App Store error : Got ERROR ITMS-90135 when using the Realm-js library

### ISSUE THREAD

**Issue by nguyen-tam** [electron-userland/electron-builder#7462]
* **Electron-Builder Version**:  23.6.0

* **Node Version**: 18

* **Electron Version**: 23
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac App Store

I got this error message when submit app to Mac App Store, it happens when I add Realm library. It seems the error happens when Electron-builder pack the Realm library.

ERROR ITMS-90135: "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools."

**Comment by mmaietta** [comment]
We use the official electron/osx-sign package for signing mac assets and just pipe options to it from the config.

Is the Realm library not being signed? It seems like an issue specific to the Realm library. Can you confirm no dSYM is being packaged with the app? That'll for sure throw the ITMS-90135 error from a quick Google search.

**Comment by nguyen-tam** [comment]
> dSYM

How to check there's dSYM is being packaged in the app or not? as I search in the Contents folder, there's no dSYM. When I asked in the Realm library Github, [they said that it may because of .o files](https://github.com/electron/osx-sign/issues/22). Seem you're fixed the .o file issue in the new version, right? @mmaietta

**Comment by mmaietta** [comment]
I migrated electron-builder to use the official `electron/rebuild` native handler in v24, but that's all I touched regarding building+packaging. Can't confirm anything changed for `.o` files
