### ISSUE TITLE
Building Native dependencies/executables into Frameworks or MacOS directories possible?

### ISSUE THREAD

**Issue by calumbutler** [electron-userland/electron-builder#7464]
* **Electron-Builder Version**:  v23.6.0

* **Node Version**:  v18.13.0

* **Electron Version**: ^v23.0.0
* **Electron Type (current, beta, nightly)**:

* **Target**:  dmg

Finding this hard to achieve this or find any information with the current documentation, but I have a preferred standard to place all executables in the `Frameworks` or `MacOS` directory. I have tried using a combination of `files` 'extraFiles`, but running into issues with this. Is there documentation that explains why the native modules get bundled under `Resources`?  If this is possible, can you point me in the right direction terms of configuration?

Currently native modules for my application are being bundled separately.  Here is my configuration:
```
  "build": {
    "productName": "MY Application",
    "appId": "com.my.application",
    "asar": true,
    "asarUnpack": "**\\*.{node,dll}",
    "buildDependenciesFromSource": true,
    "files": [
      "package.json",
      "dist",
      "node_modules"
    ],
    "afterAllArtifactBuild": "./scripts/notarize.js",
    "nsis": {
      "oneClick": true,
      "perMachine": false,
      "warningsAsErrors": true,
      "runAfterFinish": true
    },
    "mac": {
      "target": {
        "target": "default",
        "arch": [
          "universal"
        ]
      },
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "gatekeeperAssess": false,
      "mergeASARs": false
    },
    "dmg": {
      "title": "MY Application",
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "directories": {
      "app": "release/app",
      "buildResources": "assets",
      "output": "release/build"
    },
    "extraResources": [
      "./assets/**",
      "./bin/**"
    ]
  },
```

**Comment by mmaietta** [comment]
I had a similar occurrence with a project I used to manage. Basically, the electron app expected all `.node` modules in the `MacOS` directory (`process.execPath`).
There's example code hidden in the doc's Example page
```
  extraFiles: [
    {
      from: "build/Release",
      to: nodeAddonDir,
      filter: "*.node"
    }
  ],
```
Where `nodeAddonDir = process.platform === 'darwin' ? 'MacOS' : ''` since `extraFiles` is from the app's root dir IIRC.

Honestly, not sure why `.node` files end up in Resources by default, it seems to be the standard paradigm across the electron ecosystem AFAICT.
