### ISSUE TITLE
64 bit deb release artifact filename

### ISSUE THREAD

**Issue by jwheare** [electron-userland/electron-builder#747]
* **Version**: 6.5.2

* **Target**: Linux deb 64-bit

We're using nuts as an update server and it's not picking up our 64-bit linux deb builds because they don't get published with x86_64. Is it possible to specify this as an option/default?

**Comment by develar** [comment]
We add such prefix for AppImage.

But for `deb` should be used `amd64`, but not `x86_64` according to the Debian naming conventions. If `amd64` suitable for you, I will change default.

BTW, consider to use AppImage.

**Comment by jwheare** [comment]
That should work fine https://github.com/GitbookIO/nuts/blob/0c2c21a250f803931b3a124efec1cbc35b439be1/lib/utils/platforms.js#L68

And we do use AppImage too, but nuts doesn't recognise it yet.

**Comment by jwheare** [comment]
Although, looking at that link, it would if the artifact contained the word "linux"

**Comment by develar** [comment]
Ok, so, `amd64` will be added.
