### ISSUE TITLE
Unexpected suffix /allusers in uninstallstring

### ISSUE THREAD

**Issue by SergiiMarkin** [electron-userland/electron-builder#7472]
* **Electron-Builder Version**:  ^23.6.0

* **Node Version**: 16.12.0

* **Electron Version**: 23.1.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis

After I install the packaged app (.exe) file, uninstall string inside windows registry has unexpected /allusers.
- Current behavior

> "C:\Program Files (x86)\${Directory Name}\${Directory Name}\Uninstall Product Name.exe" /allusers

- Expected behavior
  It has to be without /allusers suffix

> "C:\Program Files (x86)\${Directory Name}\${Directory Name}\Uninstall Product Name.exe"

- Nsis configuration in package.json
> "allowToChangeInstallationDirectory": true,
>       "perMachine": true,
>       "allowElevation": false,
>       "oneClick": false,
>       "deleteAppDataOnUninstall": true,
>       "include": "release/installer.nsh"

**Comment by mmaietta** [comment]
I'm not sure I understand. Wouldn't `"perMachine": true` === `/allusers`?
If you want it for the current user, then that'd have to be `false`

**Comment by SergiiMarkin** [comment]
@mmaietta  Thanks for your reply.

- If I set `perMachine: false to remove `/allusers?` from `UninstallString` from Windows registry, then It is failed to run the packaged app (.exe file).
- In my case, only perMachine: true packages .exe file successfully and I am able to run only exe file with perMachine: true.

Can you please let me know what `nsis` config with `perMachine: false` should look like to package .exe file successfully?
Or provide me some nsis configuration with `perMachine: false`?

**Comment by SergiiMarkin** [comment]
This issue still persist.
Can anyone please give me help or any tips?
