### ISSUE TITLE
Cannot find module napi-v6-darwin-unknown-x64 in the universal app

### ISSUE THREAD

**Issue by oalfroukh** [electron-userland/electron-builder#7473]
* **Electron-Builder Version**: 24.0.0

* **Node Version**: 16.15.1

* **Electron Version**:23.1.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Universal

- I'm trying to build our Electron app as a Universal (I'm using this command `electron-builder --config ./electron-builder.json --mac --universal`), but I got this error in the run time for the app after building it from the M1 machine with XCode v14.2 (I'm using `sqlite3 v5.1.4`)

```js
An unexpected error occurred at startup

09/03/2023, 17:06:04 EET Error details: 
name: Error,
message: Cannot find module '/Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node'
Require stack:
- /Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/sqlite3.js
- /Applications/myApp.app/Contents/Resources/app-x64.asar/dist/main-bundle.js
- /Applications/myApp.app/Contents/Resources/app.asar/index.js
- ,

```

- Here is `myApp.app/Contents/Resources directory` in the `Application` path 
<img width="321" alt="Screenshot 2023-03-09 170831" src="https://user-images.githubusercontent.com/80884942/224067936-3c08424c-19fe-4fd8-b4a0-150ce3d43ca4.png">

- As you see there is no `napi-v6-darwin-unknown-x64 ` inside `app-x64.asar.unpacked` while there is `napi-v{napi_build_version}-darwin-unknown-x64`

- When I tried to build the app from an Intel machine (Xcode `v14.2`) there is `napi-v6-darwin-unknown-x64 ` inside `app-x64.asar.unpacked` while there is no `napi-v6-darwin-unknown-arm64 ` inside `app-arm64.asar.unpacked`(`napi-v{napi_build_version}-darwin-unknown-arm64` exists)

- Here is `electron-builder.json` contents:

```json
{
  "appId": "com.myapp.myApp",
  "productName": "mayApp",
  "buildVersion": "2.1.0",
  "compression": "normal",
  "directories": {
    "app": "./rb-services",
    "buildResources": "./setup/build",
    "output": "./compile"
  },
  "afterSign": "./notarize.js",
  "asarUnpack": ["**/*.node"],
  "mac": {
    "category": "public.app-category.business",
    "icon": "./setup/build/icon.icns",
    "hardenedRuntime": true,
    "mergeASARs": false,
    "entitlements": "./setup/build/entitlements.mac.plist",
    "entitlementsInherit": "./setup/build/entitlements.mac.plist",
    "files": [
      "**/*",
      "!**/*.ts",
      "!**/*.tlog",
      "!**/*.log",
      "!**/*.exp",
      "!**/*.lib",
      "!**/*.iobj",
      "!**/*.obj",
      "!**/*.ipdb",
      "!**/*.pdb",
      "!**/*.ilk",
      "!**/*.map",
      "!**/*.vcxproj*",
      "!**/*.lastbuildstate",
      "!**/*config.gypi",
      "!**/*binding.gyp",
      "!**/*Dockerfile",
      "!**/*tsconfig.json",
      "!**/patches/*.patch",
      "!**/node_modules/**/*/doc/**/*",
      "!**/node_modules/**/*/docs/**/*",
      "!**/node_modules/sqlite3/build/**/*",
      "!**/node_modules/sqlite3/build-tmp-napi-v6/**/*",
      "!**/node_modules/**/*.{mk,a,o,h}",
      "!src"
    ],
  "dmg": {
    "title": "mayApp",
    "background": "./setup/build/myApp.png",
    "iconSize": 90,
    "contents": [
      { "x": 448, "y": 300, "type": "link", "path": "/Applications" },
      { "x": 192, "y": 300, "type": "file" }
    ],
    "window": {
      "height": 500
    }
  }, 
  "appx": {
    "publisherDisplayName": "myApp"
  },
  "electronVersion": "23.1.3",
  "buildDependenciesFromSource": true,
  "nodeGypRebuild": false,
  "npmRebuild": true,
  "extends": null
}

```
** **Update: The issue doesn't exist when using `electron-builder v23.6.0`**, it seems related to the latest version (`24.0.0`)

**Comment by oalfroukh** [comment]
Hi @mmaietta 
Could you please take a look at this issue, seems it's a side effect of your MR https://github.com/electron-userland/electron-builder/pull/7196  in `v24.0.0-alpha.1` when migrating to electron-rebuild for handling native dependencies

Thanks in advance!

**Comment by mmaietta** [comment]
Sure thing. Can you create a minimum reproducible repo for this, such as using `electron-quick-start` project?

For context on the change, the `electron/rebuild` migration was a necessity as the previous golang builder doesn't support newer versions of electron due to some C compiler flags

**Comment by Slapbox** [comment]
@oalfroukh sorry for the off-topic comment but I'm wondering what `"!**/node_modules/**/*.{mk,a,o,h}",` achieves - what kind of files are those? Many of your entries look like great additions to our exclusions list.

**Comment by mmaietta** [comment]
Got it working with the sample project you sent me @oalfroukh 
I had simplified the config, but most notably, AFAICT the `mergeASAR: false` means that you need to be loading the index.html from the new arch-specific asar.
```
mainWindow.loadFile(path.join(__dirname, "index.html"));
```
electron-builder.js config excerpt `mac`
```
"asarUnpack": ["**/*.node"],
  "mac": {
    "target": {
      "arch": "universal",
      "target": "dir"
    },
    "hardenedRuntime": true,
    "files": [
      "index.html",
      "main.js",
      "preload.js",
      "renderer.js",
      "styles.css",
    ],
    "mergeASARs": false
  }
```

**Comment by oalfroukh** [comment]
> (path.join(__dirname, "index.html"));

Thanks for the follow-up, I'm still faced the same issue, I'm generating the app from Intel macOS now

There is `napi-v6-darwin-unknown-x64`  inside `app-x64.asar.unpacked `while there is no `napi-v6-darwin-unknown-arm64`  inside `app-arm64.asar.unpacked` that will generate an error when running the app on M1 machine

```bash
An unexpected error occurred at startup

09/03/2023, 17:06:04 EET Error details: 
name: Error,
message: Cannot find module '/Applications/myApp.app/Contents/Resources/myApp-arm64.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'

```

Here are the generated app contents:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/80884942/226134973-f4317741-1af9-4091-91aa-16df2f89ca06.png">

Can you please attach your app contents?

**Comment by oalfroukh** [comment]
> .{mk,a,o,h}

I think the extensions ".mk", ".a", ".o", and ".h" are used for make files, static libraries, object files, and header files, respectively. Each of these file types serves a specific purpose in the process of compiling and linking source code, but as I saw no need to be in the generated app (at least in my project),

**Comment by oalfroukh** [comment]
Hi @mmaietta
Any updates about the case?
Thanks in advance!

**Comment by mmaietta** [comment]
I just redownloaded and tested again. The sample project you posted works perfectly fine for me on my M1 when I just change this line
```
mainWindow.loadFile("index.html");
```
to
```
mainWindow.loadFile(path.join(__dirname, "index.html"));
```
I'm also running xcode 14.2.
<img width="1358" alt="Screenshot 2023-03-26 at 8 55 38 AM" src="https://user-images.githubusercontent.com/5238867/227787804-e6080235-4f1c-47f1-9651-6531c95238d2.png">

**Comment by oalfroukh** [comment]
First of all, 
- It seems you are using `"mergeASARs": true` because there is `app.asar.unpacked` and not `app-x64.asar.unpacked` & `app-arm64.asar.unpacked`, but I think the issue will be the same.

- The issue will not appear on `M1` machine, because the app is generated from `M1` on your case, so the issue will appear on `intel` machine only with error `Cannot find module '/Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node`, as you see on your screenshot there is no `napi-v6-darwin-unknown-x64`, while the issue will appear on `M1` machine when packaging the app from `intel` machine, that is my point (you can see the attached screenshot on my previous comment, the app generated on `intel` machine)

Thanks again!

**Comment by mmaietta** [comment]
I used the exact project config your electron-quick-start used with `npm run dist-mac`

**Comment by oalfroukh** [comment]
> I used the exact project config your electron-quick-start used with `npm run dist-mac`
> 
> I also dont own an intel mac to test with



Yes, removing `compile` and `node_modules` folders and rebuilding the app via `npm run dist-mac` will generate `app-x64.asar` & `app-x64.asar` as expected, it's OK that's not the issue.

** Any suggestion to move forward in solving the issue because those folders should exist in the expected result in the `universal` app to work fine on both architects?

Thanks for your follow-up!

**Comment by mmaietta** [comment]
Wait, why is it not leveraging `build/Release/node_sqlite3.node` in each of the relative unpacked asars?
```
~/D/electron-builder-test> ls **/*.node
  app-arm64.asar.unpacked/node_modules/sqlite3/bin/darwin-arm64-110/sqlite3.node
  app-arm64.asar.unpacked/node_modules/sqlite3/bin/darwin-x64-110/sqlite3.node
  app-arm64.asar.unpacked/node_modules/sqlite3/build/Release/node_sqlite3.node
  app-arm64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node
  app-arm64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-arm64/node_sqlite3.node
  app-arm64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-x64/node_sqlite3.node
  app-x64.asar.unpacked/node_modules/sqlite3/bin/darwin-x64-110/sqlite3.node
  app-x64.asar.unpacked/node_modules/sqlite3/build/Release/node_sqlite3.node
  app-x64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node
  app-x64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-x64/node_sqlite3.node
```

**Comment by oalfroukh** [comment]
> ```json
> "!**/node_modules/sqlite3/build/**/*",
> ```

- I was using `"!**/node_modules/sqlite3/build/**/*",` I removed it, but the same issue, when building the app from `M1` machine I got the same error when running the app on `Intel` machine:

```bash
An unexpected error occurred at startup

09/03/2023, 17:06:04 EET Error details: 
name: Error,
message: Cannot find module '/Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node'
Require stack:
- /Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /Applications/myApp.app/Contents/Resources/app-x64.asar/node_modules/sqlite3/lib/sqlite3.js
- /Applications/myApp.app/Contents/Resources/app-x64.asar/dist/main-bundle.js
- /Applications/myApp.app/Contents/Resources/app.asar/index.js
- ,
```

- If you see the `package.josn`  of sqlite3 contains this line `"module_path": "./lib/binding/napi-v{napi_build_version}-{platform}-{libc}-{arch}",` maybe that is why `build/Release/node_sqlite3.node` not leveraging

**Comment by oalfroukh** [comment]
Hi again @mmaietta 

Another point maybe will help in the investigation, if you try to use electron v`19.0.0` and `electron-builder` v`23.6.0` that is not using `electron-rebuild` will see there is `node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node` on both `app-arm64.asar` and `app-x64.asar`, so I'm not sure who is responsible about this issue `electron-builder` or `electron-rebuild`

![image](https://user-images.githubusercontent.com/80884942/230896395-f0eb6ff7-297e-4d1e-8b13-ccc839686b4c.png)

**Comment by mmaietta** [comment]
>if you want I can upload the generated dmg from Intel to google drive to try to use it on your M1 machine to be able to reproduce the issue on your machine.

I trust you there.

Was finally able to emulate an x64 mac and create the crash you've been describing, did so by invoking rosetta to launch the app.
```
arch -x86_64 open ~/Development/electron-quick-start-issue7473/dist/mac-universal/myApp.app  --args --inspect --remote-debugging-port=8888
```
The other route is to right click -> "Get Info" -> "Launch using Rosetta"

I just built a x64-only app using your electron-quick-start.zip you previously linked, and it fails to launch with the same error.
When compiling for universal, I checked everything again with `lipo` using `v24.2.0`
```
~/D/electron-quick-start-issue7473> lipo -info **/sqlite3/**/*.node
Non-fat file: dist/mac-universal/myApp.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/sqlite3/build/Release/node_sqlite3.node is architecture: arm64
Non-fat file: dist/mac-universal/myApp.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-arm64/node_sqlite3.node is architecture: arm64
Non-fat file: dist/mac-universal/myApp.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-x64/node_sqlite3.node is architecture: x86_64
Non-fat file: dist/mac-universal/myApp.app/Contents/Resources/app-x64.asar.unpacked/node_modules/sqlite3/build/Release/node_sqlite3.node is architecture: x86_64
Non-fat file: dist/mac-universal/myApp.app/Contents/Resources/app-x64.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-darwin-unknown-x64/node_sqlite3.node is architecture: x86_64
```

The reason it's failing is because `{napi_build_version}` isn't being replaced with `6` with what `sqlite3` is expecting (`napi-v6-darwin-unknown-x64/node_sqlite3.node`. Everything else seems to line up correctly.
I think that may actually be resolved by https://github.com/electron/rebuild/pull/1076 as I have no idea where else `napi_build_version` could possibly be coming from.

**Comment by mmaietta** [comment]
Here you go, this fixes it for me
Add this patch file to your project via [patch-package](https://www.npmjs.com/package/patch-package) and it properly replaces `napi_build_version` as expected
`@electron+rebuild+3.2.10.patch`
```
diff --git a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
index 8fd6878..e9e2b4b 100644
--- a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
+++ b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
@@ -46,6 +46,10 @@ class NodeGyp extends _1.NativeModule {
     }
     async buildArgsFromBinaryField() {
         const binary = await this.packageJSONFieldWithDefault('binary', {});
+        let napi_build_version = undefined
+        if (binary.napi_versions) {
+            napi_build_version = this.nodeAPI.getNapiVersion(binary.napi_versions)
+        }
         const flags = await Promise.all(Object.entries(binary).map(async ([binaryKey, binaryValue]) => {
             if (binaryKey === 'napi_versions') {
                 return;
@@ -60,6 +64,9 @@ class NodeGyp extends _1.NativeModule {
                 .replace('{arch}', this.rebuilder.arch)
                 .replace('{version}', await this.packageJSONField('version'))
                 .replace('{libc}', await detect_libc_1.default.family() || 'unknown');
+            if (napi_build_version !== undefined) {
+                value = value.replace('{napi_build_version}', napi_build_version.toString())
+            }
             for (const [replaceKey, replaceValue] of Object.entries(binary)) {
                 value = value.replace(`{${replaceKey}}`, replaceValue);
             }

```
I was able to launch the app successfully with Rosetta 2 env.

**Comment by oalfroukh** [comment]
> Here you go, this fixes it for me Add this patch file to your project via [patch-package](https://www.npmjs.com/package/patch-package) and it properly replaces `napi_build_version` as expected `@electron+rebuild+3.2.10.patch`
> 
> ```
> diff --git a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
> index 8fd6878..e9e2b4b 100644
> --- a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
> +++ b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
> @@ -46,6 +46,10 @@ class NodeGyp extends _1.NativeModule {
>      }
>      async buildArgsFromBinaryField() {
>          const binary = await this.packageJSONFieldWithDefault('binary', {});
> +        let napi_build_version = undefined
> +        if (binary.napi_versions) {
> +            napi_build_version = this.nodeAPI.getNapiVersion(binary.napi_versions)
> +        }
>          const flags = await Promise.all(Object.entries(binary).map(async ([binaryKey, binaryValue]) => {
>              if (binaryKey === 'napi_versions') {
>                  return;
> @@ -60,6 +64,9 @@ class NodeGyp extends _1.NativeModule {
>                  .replace('{arch}', this.rebuilder.arch)
>                  .replace('{version}', await this.packageJSONField('version'))
>                  .replace('{libc}', await detect_libc_1.default.family() || 'unknown');
> +            if (napi_build_version !== undefined) {
> +                value = value.replace('{napi_build_version}', napi_build_version.toString())
> +            }
>              for (const [replaceKey, replaceValue] of Object.entries(binary)) {
>                  value = value.replace(`{${replaceKey}}`, replaceValue);
>              }
> ```
> 
> I was able to launch the app successfully with Rosetta 2 env.

Hi @mmaietta,
Thanks for your great efforts! I used that patch and it's working fine on my Intel machine.

I have another question maybe it's not related to this topic I see there is a warning message ["Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+"](https://github.com/electron-userland/electron-builder/blob/master/packages/dmg-builder/src/dmg.ts#L206) Does this mean the generated dmg will never work on OSX 10.11 and below? if yes, does generating Universal dmg from Intel machine will support these OSX versions, and will be the same efficient as that generated app from arm64?

**Comment by mmaietta** [comment]
That's correct.
arm64 does not support HFS+ dmg creation. Intel machines still will be able to, presuming that Apple hasn't removed that support in most recent versions of mac. If the dmg succeeds on an Intel machine, then it's still HFS+

**Comment by oalfroukh** [comment]
> That's correct. arm64 does not support HFS+ dmg creation. Intel machines still will be able to, presuming that Apple hasn't removed that support in most recent versions of mac. If the dmg succeeds on an Intel machine, then it's still HFS+

OK, thanks a lot Mike! 
so I'll try to use an Intel machine for the official build to give our users the last chance to use our app on these old OSX versions.

**Comment by nikhilro** [comment]
Hey @mmaietta, thanks for electron builder. Noticed `electron-rebuild` is out with your patch. Could you cut a new version of `electron-builder` with updated dependencies, please? Reliant on `electron-builder` but completely ignorant of it's working 😅 It _just_ works.

**Comment by mmaietta** [comment]
Updated `@electron/rebuild` dependency so that you don't need to use a custom patch-package approach. electron-builder 24.3.0 has the fix
