### ISSUE TITLE
Exclude `elevate.exe` in Portable app

### ISSUE THREAD

**Issue by Arubinu** [electron-userland/electron-builder#7474]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.13.1

* **Electron Version**: 19.1.9
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

Hi, compiling in `portable` mode works fine but I noticed the `elevate.exe`.
While searching on the internet I came across `packElevateHelper` which would allow me to remove it and gain confidence in antivirus.

Here is my `package.json` file:
```
{
  "name": "Scripts-Manager",
  "version": "2.1.0",
  "description": "Scripts Manager is a tool for streamers, developers, but also anyone who wants to automate actions on their computer.",
  "main": "main.js",
  "scripts": {
    "start": "cross-env NODE_TOOLS=1 electron .",
    "lint": "eslint --max-warnings=0 .",
    "lint-fix": "eslint --max-warnings=0 --fix .",
    "pre-build": "electron-builder build --config.files=\"!docs\" --win portable",
    "build": "electron-builder build --config.files=\"!env.json\" --config.files=\"!docs\" --win portable"
  },
  "repository": "https://github.com/Arubinu/Scripts-Manager",
  "keywords": [
    "Scripts",
    "Manager",
    "Addons",
    "Scripts",
    "OBS",
    "Studio",
    "Touch",
    "Portal",
    "Spotify",
    "Stream",
    "Twitch",
    "Multi",
    "Actions",
    "Flash",
    "Widget"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "cross-env": "^7.0.3",
    "electron": "^19.0.6",
    "eslint": "^8.33.0"
  },
  "dependencies": {
    "@twurple/api": "^6.0.6",
    "@twurple/auth": "^6.0.6",
    "@twurple/chat": "^6.0.6",
    "@twurple/eventsub-ws": "^6.0.6",
    "@twurple/pubsub": "^6.0.6",
    "discord.js": "^13.8.0",
    "electron-custom-notifications": "github:Arubinu/electron-custom-notifications",
    "electron-log": "^4.4.7",
    "electron-store": "^8.0.1",
    "node-global-key-listener": "^0.1.1",
    "obs-websocket-js": "^5.0.2",
    "read-ini-file": "^3.0.1",
    "spotify-web-api-node": "^5.0.2",
    "temp": "^0.9.4",
    "touchportal-api": "github:Arubinu/touchportal-node-api",
    "undici": "^5.5.1",
    "uniqid": "^5.4.0",
    "usb": "^2.4.3",
    "websocket": "^1.0.34",
    "write-ini-file": "^3.0.2"
  },
  "build": {
    "appId": "fr.arubinu.scripts-manager",
    "productName": "Scripts Manager",
    "copyright": "",
    "mac": {
      "target": [
        "zip"
      ]
    },
    "win": {
      "publisherName": "Arubinu",
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "tar.gz"
      ]
    },
    "nsis": {
      "oneClick": true,
      "perMachine": false,
      "allowElevation": false,
      "packElevateHelper": false,
      "allowToChangeInstallationDirectory": false
    },
    "files": [
      "!docs"
    ]
  },
  "gitHooks": {
    "pre-push": "npm run lint"
  }
}
```

It seems to me that a lot of `NSIS` options are useless in `portable` mode, but in doubt.
I tried several combinations but it is always present no matter what I do.

Do you have an idea of ​​the problem ?

**Comment by mmaietta** [comment]
>To customize web installer, use the top-level `nsisWeb` key (not `nsis`).

https://www.electron.build/configuration/nsis#web-installer

**Comment by Arubinu** [comment]
I just tried and figured out the documentation, but I feel like nothing fits my use case.

My goal is to use the applciation without installation.
It works perfectly but I would just like to remove this file.

You see what I mean ?

**Comment by Arubinu** [comment]
So I put `portable` instead of `nsis` or `nsisWeb`, but suddenly I have no choice for the `elevate.exe`...

Here is my new config:
```
{
  "name": "Scripts-Manager",
  "version": "2.1.0",
  "description": "Scripts Manager is a tool for streamers, developers, but also anyone who wants to automate actions on their computer.",
  "main": "main.js",
  "scripts": {
    "start": "cross-env NODE_TOOLS=1 electron .",
    "lint": "eslint --max-warnings=0 .",
    "lint-fix": "eslint --max-warnings=0 --fix .",
    "pre-build": "electron-builder build --win portable",
    "build": "electron-builder build --config.files=\"!env.json\" --win portable"
  },
  "repository": "https://github.com/Arubinu/Scripts-Manager",
  "keywords": [
    "Scripts",
    "Manager",
    "Addons",
    "Scripts",
    "OBS",
    "Studio",
    "Touch",
    "Portal",
    "Spotify",
    "Stream",
    "Twitch",
    "Multi",
    "Actions",
    "Flash",
    "Widget"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "cross-env": "^7.0.3",
    "electron": "^19.0.6",
    "eslint": "^8.33.0"
  },
  "dependencies": {
    "@twurple/api": "^6.0.6",
    "@twurple/auth": "^6.0.6",
    "@twurple/chat": "^6.0.6",
    "@twurple/eventsub-ws": "^6.0.6",
    "@twurple/pubsub": "^6.0.6",
    "discord.js": "^13.8.0",
    "electron-custom-notifications": "github:Arubinu/electron-custom-notifications",
    "electron-log": "^4.4.7",
    "electron-store": "^8.0.1",
    "node-global-key-listener": "^0.1.1",
    "obs-websocket-js": "^5.0.2",
    "read-ini-file": "^3.0.1",
    "spotify-web-api-node": "^5.0.2",
    "temp": "^0.9.4",
    "touchportal-api": "github:Arubinu/touchportal-node-api",
    "undici": "^5.5.1",
    "uniqid": "^5.4.0",
    "usb": "^2.4.3",
    "websocket": "^1.0.34",
    "write-ini-file": "^3.0.2"
  },
  "build": {
    "appId": "fr.arubinu.scripts-manager",
    "productName": "Scripts Manager",
    "copyright": "",
    "mac": {
      "target": [
        "zip"
      ]
    },
    "win": {
      "publisherName": "Arubinu",
      "target": [
        "portable"
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "tar.gz"
      ]
    },
    "portable": {},
    "files": [
      "!docs"
    ]
  },
  "gitHooks": {
    "pre-push": "npm run lint"
  }
}
```

**Comment by mmaietta** [comment]
Correct.
https://github.com/electron-userland/electron-builder/blob/c1448c6584bb5106aaa2766379fd0917508ce3bf/packages/app-builder-lib/src/targets/nsis/nsisOptions.ts#L58

https://github.com/electron-userland/electron-builder/blob/c1448c6584bb5106aaa2766379fd0917508ce3bf/packages/app-builder-lib/src/targets/nsis/nsisOptions.ts#L199

https://github.com/electron-userland/electron-builder/blob/c1448c6584bb5106aaa2766379fd0917508ce3bf/packages/app-builder-lib/src/targets/nsis/nsisOptions.ts#L28-L56

**Comment by Arubinu** [comment]
However, `requestExecutionLevel` (on "user") should cancel the copy of `elevate.exe`, since it is no longer necessary...

**Comment by Arubinu** [comment]
I just tried compiling the `win-unpacked` folder by first removing the `elevate.exe` file and it works, but it recreates the file anyway.

There is no solution?

**Comment by Arubinu** [comment]
Is it possible to add this functionality in a future version?

**Comment by mmaietta** [comment]
I took a quick look in the code and it doesn't appear easily achievable. An alternative approach is to use `afterPack` hook and just force `rmSync` on that specific file within the `win-unpacked` folder (IIRC, that's `appOutDir`?)
https://www.electron.build/configuration/configuration#afterpack
https://github.com/electron-userland/electron-builder/blob/c1448c6584bb5106aaa2766379fd0917508ce3bf/packages/app-builder-lib/src/configuration.ts#L280-L287

**Comment by Arubinu** [comment]
Thank you for this answer which seems to be in the right direction, but the hook does not fall at the right time (the file does not exist yet).
I put a `setTimeout` of 600ms, but if I don't put the right timing, the file is expected by `electron-builder` and generates an error.

After creating the executable, I was able to see that the file was not in it using 7zip.

Thanks for this workaround :)
