### ISSUE TITLE
Can't find a way to enable npmRebuild with arch: universal

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#7479]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.17.0

* **Electron Version**: 20.3.x
* **Electron Type (current, beta, nightly)**: Current

* **Target**: 

```js
  target: [
    {
      target: 'default',
      arch: 'universal',
    },
  ],
  ```
  
 We can't use `npmRebuild: true` when the `arch` is set to `universal` because the `.node` files differ for x64 vs ARM - so I tried this configuration:
  
  ```js
    mergeASARs: false,
    singleArchFiles: '*.node'
  ```
  
 And that lets us build - but when I ran the app on x64 it fails to run properly - erroring out on a line like `mainWindow.webContents.send()` with the error `TypeError: Cannot read properties of undefined (reading 'webContents')`
  
Can we remedy this? Or is there another way to enable `npmRebuild` with the `universal` arch?

**Comment by Slapbox** [comment]
With `24.0.0` instead we get past that but fail with the following error on our x64 machine:

```
[2023-03-15 22:24:27.636] [error] Error: dlopen(/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh, 0x0001): tried: '/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/private/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

**Comment by oalfroukh** [comment]
> With `24.0.0` instead we get past that but fail with the following error on our x64 machine:
> 
> ```
> [2023-03-15 22:24:27.636] [error] Error: dlopen(/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh, 0x0001): tried: '/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/private/var/folders/y5/pp8xq1qd1f78jth_11nsxndh0000gn/T/.com.electron.app.qsKNgh' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
> ```

do you try to run your app from the generated app that is in `compile\mac-universal`, or run the app from `node_modules`?

**Comment by Slapbox** [comment]
Thanks for your reply @oalfroukh.

I don't know what you mean by run the app from `node_modules`. We ran the file: `release/mac-universal/OurApp.app`

It runs fine if we remove these lines:

```
  mergeASARs: false,
  singleArchFiles: '*.node'
```

But then we must set `npmRebuild` to false or it fails during building.

**Comment by oalfroukh** [comment]
> Thanks for your reply @oalfroukh.
> 
> 
> 
> I don't know what you mean by run the app from `node_modules`. We ran the file: `release/mac-universal/OurApp.app`
> 
> 
> 
> It runs fine if we remove these lines:
> 
> 
> 
> ```
> 
>   mergeASARs: false,
> 
>   singleArchFiles: '*.node'
> 
> ```
> 
> 
> 
> But then we must set `npmRebuild` to false or it fails during building.
> 
> 
> 
> As I'm writing this out - I'm beginning to doubt that our universal builds work on ARM, but I have no way to test them myself.

Regarding `singleArchFiles` has no effect without `mergeASARs: true` as electron-builder docs

```readme
singleArchFiles String | “undefined” - Minimatch pattern of paths that are allowed to be present in one of the ASAR files, but not in the other.

This option has no effect unless building for “universal” arch and applies only if is true.
```

**Comment by Slapbox** [comment]
Right, but we're not wrongfully combining those settings. You can see `mergeASARs` is set to `false`.

Is there any way we can enable `npmRebuild` with universal builds?

**Comment by oalfroukh** [comment]
> Right, but we're not wrongfully combining those settings. You can see `mergeASARs` is set to `false`.
> 
> 
> 
> Is Is there any way we can enable `npmRebuild` with universal builds?

I think you should set `npmRebuild` to true, you can take a look at my config on the attached issue maybe will help you 

https://github.com/electron-userland/electron-builder/issues/7473
