### ISSUE TITLE
Do the *-unpacked folders need to be uploaded for auto-update to work?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#7481]
Apologies for not using the template, but none of it seems relevant as I just have this yes/no question.

**Comment by mmaietta** [comment]
No. Autoupdate just requires `exe`, `zip`(mac), `AppImage` and the related update.yml files

**Comment by Slapbox** [comment]
I imagine we should include the `.blockmap` files as well, but that they're not strictly necessary? If I understand correctly they're necessary for differential updating, right?

**Comment by mmaietta** [comment]
Oh right, yes, those should be included as well

**Comment by 147258369112** [comment]
上传免安装的zip包可以进行升级吗，不上传.exe包
