### ISSUE TITLE
Possibility to exclude '!**/node_modules/**/src/**/*' - only when there is a lib or dist folder in the same directory?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#7482]
* **Electron-Builder Version**: 24.0.0

* **Node Version**: 16.18.0

* **Electron Version**: 20.3.x
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Any

Is it possible to exclude `src` files from the bundle when the package includes a `dist` or `lib` directory? I don't think this can be achieved with the current API, but it would be useful in my opinion.

In total these directories appear to add about 1.7mb (unpacked) to the ASAR - but only about 20kb appears to be required.

**Comment by mmaietta** [comment]
That's what the `files` regex is for?
https://www.electron.build/configuration/contents#files
>Default pattern **/* is not added to your custom if some of your patterns is not ignore

So you can specify what you want to exclude - i.e. blacklist. Or alternatively, output your dist files to a separate dir and only whitelist those files to be included.

**Comment by Slapbox** [comment]
Thanks for your reply @mmaietta. I think either I misunderstand your reply or you misunderstand my question.

It's easy to _always_ exclude the `src` folders within `node_modules` - but what about excluding them only if there's an adjacent `dist` or `lib` folder? Because some projects the `src` folder is what needs to be included in the final package - but generally it's not - and if it's not then there's always a `dist` or `lib` folder next to the `src`.

I don't think that's possible with globs, but maybe it is?

**Comment by mmaietta** [comment]
Ohhhhh, my apologies. I definitely misunderstood. You're referring to the way the node_modules are selectively included?

Honestly, in that case, I took a different approach with one of my projects. I didn't use any node module externals for production builds, instead, I fully compiled **everything** using webpack into 3 bundles: main.js, preload.js, renderer.js. I still used `.node` native modules from my project and npm deps, and those were just explicitly copied to resources, and the 3 other files were explicitly included via `./out`. So I had zero node_modules included in asar, no unpacking necessary
```
  files: [
    "out"
  ],
  extraFiles: [
    {
      from: "build/Release",
      to: nodeAddonDir,
      filter: "*.node"
    }
  ],
```
The example on the website is a simplified excerpt of what that project's config was
https://www.electron.build/api/programmatic-usage

Thoughts?

**Comment by Slapbox** [comment]
Thanks very much for sharing @mmaietta! That makes sense - but because we use Sharp and simply adding `*.node` to `asarUnpack` failed to work, I think it might break Sharp.

Nonetheless I'll give it a try!

How exactly should `nodeAddonDir` be defined here though? I'm a little confused on that.

Should it look like: `const nodeAddonDir = process.platform === "darwin" ? "MacOS" : ""`? If so that might be worth adding to the example. I found it [in another of your comments](https://github.com/electron-userland/electron-builder/issues/5750#issuecomment-837433071).

**Comment by Slapbox** [comment]
Interestingly that approach adds 17mb to our AppImage file and still includes what is apparently the same `node_modules` folders inside of the ASAR - although I didn't do a robust comparison.

Any thoughts why that might be?

**Comment by mmaietta** [comment]
I was using a webpack plugin that allowed me to load all `*.node` addons directly from `process.execRoot`.
Also, I think a node_modules negation is needed in the config.
This is an excerpt from the project's unique setup. I think that was how I unpackaged it.
`build/Release` is where your native addons go if you have your own native code (binding.gyp -> .node)
```
const nodeAddonDir = process.platform === "darwin" ? "MacOS" : ""; // Copy native addons to process.exec root dir
```
```
    files: [
        "out",
        "!node_modules",
        "!**/*.node",
        "!**/*.map"
    ],

    extraFiles: [
        {
            from: "build/Release",
            to: nodeAddonDir,
            filter: ["*.node"]
        },
        {
            from: "node_modules/node-mac-permissions/build/Release",
            to: nodeAddonDir,
            filter: "*.node"
        },
        {
            from: "node_modules/electron-deeplink/build/Release",
            to: nodeAddonDir,
            filter: "*.node"
        }
    ],
```


Can you put together a minimum repro repo for me to take a look at?

**Comment by Slapbox** [comment]
I wish I could find time to make a repro but I'm afraid I won't be able to - but I'm close to having your approach working and I appreciate all of your guidance (and all the previous work of yours I already rely on!)

I'm a little confused still about the `to: nodeAddonDir` - I'm testing on Linux and I'm able to copy the native dependency files into the installer - but the Webpack-bundled JS code still fails because it can't find the dependency `Sharp`. I guess that was not relevant to you while using I was using [awesome node loader](https://www.npmjs.com/package/awesome-node-loader) - but I'm rather hesitant to add a new build dependency which hasn't been updated in 5 years.

**Comment by mmaietta** [comment]
Just copy the code so you can use latest dev dependencies for it and then load the loader as a file 🙂 
https://github.com/gurisko/awesome-node-loader/blob/master/index.js
https://webpack.js.org/contribute/writing-a-loader/

**Comment by Slapbox** [comment]
That's a possibility for sure, but I'm always hesitant to rely on abandoned repos and to incorporate them into our own project. Down the line that sometimes ends up coming back to bite you - eg requiring code changes to work with some hypothetical future Webpack release. But I'll keep it in mind as a possibility still. Thanks very much for your help @mmaietta.
