### ISSUE TITLE
Electron cannot be found after packaging

### ISSUE THREAD

**Issue by l-lemming** [electron-userland/electron-builder#7484]
There is no problem in the development stage, but after packaging, there is no error in the project packaging folder, but this error will be reported when the software is placed on the desktop

why？

- package.json
```
"dependencies": {
    "mysql": "2.16.1",
    "redis": "4.6.5",
    "electron-reload": "^2.0.0-alpha.1",
    "electron-store": "^8.1.0",
    "element-plus": "2.2.32",
    "@element-plus/icons-vue": "^2.1.0",
    "vue": "3.2.45",
    "vue-router": "4.1.6"
  }, 
 "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "electron": "^19.0.4",
    "electron-rebuild": "^3.2.9",
    "electron-builder": "^22.13.1",
    "vite": "^4.1.0"
  },
```
- preload.js
```
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('action', {
  module: (data) => ipcRenderer.invoke('actionModule', data)
})
```

- error
```
Uncaught (in promise) Error: Error invoking remote method 'actionModule': Error: Cannot find module 'electron'
Require stack:
- /Users/nw_air_1/Desktop/auto_mobile.app/Contents/Resources/app.asar/utils/onMysqlAction.js
- /Users/nw_air_1/Desktop/auto_mobile.app/Contents/Resources/app.asar/utils/debuglog.js
- /Users/nw_air_1/Desktop/auto_mobile.app/Contents/Resources/app.asar/utils/utils.js
- /Users/nw_air_1/Desktop/auto_mobile.app/Contents/Resources/app.asar/utils/adb.js
- /Users/nw_air_1/Desktop/auto_mobile.app/Contents/Resources/app.asar/utils/adb_worker.js
```

**Comment by mmaietta** [comment]
> Uncaught (in promise) Error: Error invoking remote method 'actionModule': Error: Cannot find module 'electron'

How are you invoking `actionModule` in the renderer thread?

Additional note, this isn't an electron-builder issue. Might be vite, but I'm not familiar with it.

**Comment by l-lemming** [comment]
> > Uncaught (in promise) Error: Error invoking remote method 'actionModule': Error: Cannot find module 'electron'
> 
> How are you invoking `actionModule` in the renderer thread?
> 
> Additional note, this isn't an electron-builder issue. Might be vite, but I'm not familiar with it.

Thank you. I've taken care of it
