### ISSUE TITLE
Vulnerabilities found on electron-builder latest version

### ISSUE THREAD

**Issue by sn06work** [electron-userland/electron-builder#7485]
* **23.6.0**: 

* **lts/fermium**: 

* **22.0.0**:
* **Electron Type (current, beta, nightly)**:

<img width="597" alt="Screenshot 2023-03-17 at 4 11 38 PM" src="https://user-images.githubusercontent.com/128142423/225882654-419a1e57-54be-4891-9fea-11e83da1b7b2.png">

There are vulnerabilities coming up in electron-builder due to ansi-regex, minimatch, http-cache-semantics ,minimist even after updating electron-builder to the latest version.

**Comment by mmaietta** [comment]
Can you please check with `next` v24.0.0

**Comment by mmaietta** [comment]
Verified locally.
```
  "devDependencies": {
    "electron": "23.1.3",
    "electron-builder": "24.0.0",
    "electron-rebuild": "^3.2.9"
  }
```
```
~/D/electron-quick-start> npm audit
found 0 vulnerabilities
```

**Comment by sn06work** [comment]
@mmaietta 
Even I tried using electron-builder 24.0.0
  "devDependencies": {
    "@electron/remote": "^2.0.9",
    "clean-css": "^5.3.2",
    "electron": "23.1.3",
    "electron-builder": "^24.0.0",
}
But there are still vulnerabilities in electron-builder due to http-cache-semantics, minimatch, ansi-regex . Where  http-cache-semantics should be updated to version >=4.1.1 , minimatch should be updated to version >=3.0.5, ansi-regex should be updated to version >=5.0.1
