### ISSUE TITLE
Squirrel.Windows does not support ARM64

### ISSUE THREAD

**Issue by t3chguy** [electron-userland/electron-builder#7492]
* **Electron-Builder Version**: 24.0.0

* **Node Version**: 18

* **Electron Version**: 23
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows arm64

The app builds fine and works as expected in unpacked mode, but in Squirrel.Windows mode it will not run due to https://github.com/Squirrel/Squirrel.Windows/issues/1616 - updating to Squirrel.Windows v2 should fix it due to https://github.com/Squirrel/Squirrel.Windows/pull/1617 having landed.

**Comment by t3chguy** [comment]
@mmaietta done

**Comment by baxyz** [comment]
Any update?

**Comment by mmaietta** [comment]
This should be resolved with the squirrel upgrade in https://github.com/electron-userland/electron-builder/pull/8344
