### ISSUE TITLE
Builds failing after upgrading to electron-builder 24.x

### ISSUE THREAD

**Issue by kylekirkby** [electron-userland/electron-builder#7494]
* **Electron-Builder Version**: 24.1.0

* **Node Version**: v18.14.2

* **Electron Version**: 23.2.0 

* **Target**:  Mac OSX / Windows / Linux

After upgrading to electron-builder `24.1.0`, our builds have started failing with:

```
OSX/node_modules/app-builder-lib/src/electron/electronVersion.ts:102
error	23-Mar-2023 07:49:46	    throw new InvalidConfigurationError(
error	23-Mar-2023 07:49:46	          ^
error	23-Mar-2023 07:49:46	InvalidConfigurationError: Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
error	23-Mar-2023 07:49:46	See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
```

I've tried every suggestion mentioned on https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246 but have had no success.

Any idea what's happening here?

**Comment by mmaietta** [comment]
Oomph, I can take a look at this asap. Surprised it wasn't caught in any of the alpha versions.

Would you be willing to put together a minimum reproducible repo for this? That'd help immensely

**Comment by glennmartinez** [comment]
Getting the same here, latest electron with latest electron-builder.

**Comment by mmaietta** [comment]
I need more info to work with here. Please post build logs with env var `DEBUG=electron-builder` or a minimum reproducible repo/gist (such as with electron-quick-start).

Are your projects using native modules?

**Comment by zibra** [comment]
same on my end

**Comment by 1zilc** [comment]
[same problem](https://github.com/1zilc/fishing-funds/actions/runs/4543819080/jobs/8009011417)

**Comment by glennmartinez** [comment]
@mmaietta I'm using this project https://github.com/electron-react-boilerplate/electron-react-boilerplate and to reproduce just try to bump electron-builder dependency. I don't have any probs with the latest 23.alpha versions, only from 24 onwards.

**Comment by mmaietta** [comment]
Hmmm does this repro for you guys on m1 devices? Or is it only on intel-based macs?

@glennmartinez I just tried that project: Set electron-builder 24.1.1 and upped electron to 23.2.0, then ran `npm run package` successfully.

**Comment by 1zilc** [comment]
> Hmmm does this repro for you guys on m1 devices? Or is it only on intel-based macs? Are your npm modules already installed when running `npm electron-builder` or are you requiring electron-builder to do so?
> 
> @glennmartinez I just tried that project: Set electron-builder 24.1.1 and upped electron to 23.2.0 (also tried with 23.0.0), then ran `npm install && npm run package` successfully.
> 
> For those that are experiencing this failing build, can someone **please** post a build log with `DEBUG=electron-builder` env var?

This is the build log for my project https://github.com/1zilc/fishing-funds/actions/runs/4549186129/jobs/8020996987 . I have added the DEBUG=electron-builder environment variable. My project is based on the electron-react-boilerplate, It seems to be related to the construction method of this project. I think we should submit an issue to ERB 🤔️

**Comment by ajgassner** [comment]
A possible workaround is to define electron under devDependencies in the app/package.json. The bad side effect for my project is a ~6MB larger app.asar. I found no way to define electronVersion via config, env var etc.... 

My env:
Electron-Builder Version: 24.1.1
Node Version: v18.12.1
Electron Version: 23.2.0
Target: Mac M1 / Windows

**Comment by mmaietta** [comment]
Thanks all for the logs and project info! I was able to identify the issue and have implemented a fix. Also added a fixture+test to cover the two-package.json project structure with a native module. Tested the fix using the fixture and a fork of @1zilc's project

Please try `24.1.2`
My apologies for any frustrations/issues this caused.

**Comment by mmaietta** [comment]
Thanks all for the logs and project info! I was able to identify the issue and have implemented a fix. Also added a fixture+test to cover the two-package.json project structure with a native module. Tested the fix using the fixture and a fork of @1zilc's project

Please try `24.1.2`
My apologies for any frustrations/issues this caused.

**Comment by 1zilc** [comment]
> Thanks all for the logs and project info! I was able to identify the issue and have implemented a fix. Also added a fixture+test to cover the two-package.json project structure with a native module. Tested the fix using the fixture and a fork of @1zilc's project
> 
> Please try `24.1.2` My apologies for any frustrations/issues this caused.

Very thanks for your work! [24.1.2 solved this issue](https://github.com/1zilc/fishing-funds/actions/runs/4560484690/jobs/8045478911)

**Comment by glennmartinez** [comment]
@mmaietta nice one buddy!!!
