### ISSUE TITLE
Auto update not working on Windows

### ISSUE THREAD

**Issue by sukolenvo** [electron-userland/electron-builder#7502]
* **Electron-Builder Version**: 
^23.6.0

* **Node Version**: 
16.14.0

 

* **Electron Version**: ^19.1.9
* **Electron Type (current, beta, nightly)**: stable

* **Electron Updater**: 6.0.0

* **Target**: NSIS

`AppUpdater.quitAndInstall()` simply quits app and doesn't install.

Logs: 
```
09:55:42.348 UTC +08:00 > Install on explicit quitAndInstall
09:55:42.349 UTC +08:00 > Install: isSilent: false, isForceRunAfter: true
09:55:43.586 UTC +08:00 > Update installer has already been triggered. Quitting application.
```
This seems to be a bug in https://github.com/electron-userland/electron-builder/blob/a0e09c33d0b9692d10e384a34cf3f2ea6d7ed592/packages/electron-updater/src/BaseUpdater.ts#L137
Installer need to run with elevated permissions. But promiss resolved successfully instead of propagating error to error code handling in https://github.com/electron-userland/electron-builder/blob/a0e09c33d0b9692d10e384a34cf3f2ea6d7ed592/packages/electron-updater/src/NsisUpdater.ts#L155

Here is a simplified script to reproduce the issue:
```js
var spawn = require('child_process').spawn;

function spawnLog(cmd, args) {
    return new Promise((resolve, reject) => {
      try {
        const p = spawn(cmd, args, {
		 stdio: 'inherit',
                 detached: true,
        })
        p.on("error", error => {
          console.log('we reject', error)
          reject(error)
        })
        p.unref()
	console.log("we resolve");
	resolve(p.pid !== undefined)
      } catch (error) {
        reject(error)
      }
    })
  }

const cmd = 'C:\\Users\\vs\\AppData\\Local\\desktop-fe-app-updater\\pending\\WiseTime Setup 3.7.20.exe'
const args = ['--updated', '--force-run']

spawnLog(cmd, args)
  .then((res) => console.log("Resolved (no error check). Result: " + res))
  .catch(e => console.log("Receive error. Error code handling for " + e))
```

Output is:
```
$  node test.js
we resolve
we reject Error: spawn C:\Users\vs\AppData\Local\desktop-fe-app-updater\pending\WiseTime Setup 3.7.20.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4092,
  code: 'EACCES',
  syscall: 'spawn C:\\Users\\vs\\AppData\\Local\\desktop-fe-app-updater\\pending\\WiseTime Setup 3.7.20.exe',
  path: 'C:\\Users\\vs\\AppData\\Local\\desktop-fe-app-updater\\pending\\WiseTime Setup 3.7.20.exe',
  spawnargs: [ '--updated', '--force-run' ]
}
Resolved (no error check). Result: false
```
I think we should not both `resolve()` with false and `reject()` Promise. Error handling logic is not triggered

**Comment by mmaietta** [comment]
Hmmm, great callout. Need to fix this asap
This is what the code was originally before it was extracted to `BaseUpdater`:
https://github.com/electron-userland/electron-builder/blob/v23.6.0/packages/electron-updater/src/NsisUpdater.ts#L253-L264

The most notable differences I see are:
```
stdio: "ignore",
// and
...
      if (process.pid !== undefined) {
        resolve(true)
      }
```

Can you try that with your example code and see if it resolves the problem?

**Comment by mmaietta** [comment]
Returned it back to match the previous logic, albeit still extracted. Releasing electron-updater 6.0.1

**Comment by sukolenvo** [comment]
Thank you for a quick fix. I can confirm locally your suggestion fixes the issue

```js
      if (process.pid !== undefined) {
        resolve(true)
      }
```

**Comment by NoahAndrews** [comment]
Nice, I was running into this issue while testing an overdue electron-builder bump, but hadn't figured it out yet.

**Comment by kafka-yu** [comment]
We meet this issue too. 
> Update installer has already been triggered. Quitting application.

**Comment by NoahAndrews** [comment]
I don't think you can fix it for an already-published version. I would never update electron-updater/builder without thoroughly re-testing the update process.

**Comment by andirsun** [comment]
Still happening to me:
electron-updater: 6.1.4
```
[2023-12-04 14:57:25.488] [info]  New version 5.0.48 has been downloaded to C:\Users\hola\AppData\Local\streamline-mono-updater\pending\Streamline.exe
[2023-12-04 14:57:25.495] [info]  Updater service -> update downloaded, waiting for next app launch to install it
[2023-12-04 14:58:04.119] [info]  Install on explicit quitAndInstall
[2023-12-04 14:58:04.120] [info]  Install: isSilent: false, isForceRunAfter: true
[2023-12-04 14:58:04.121] [info]  Executing: C:\Users\hola\AppData\Local\streamline-mono-updater\pending\Streamline.exe with args: --updated,--force-run
[2023-12-04 14:58:05.021] [info]  Update installer has already been triggered. Quitting application.
```
After trying to open the app after auto update, the app was uninstalled
![Screenshot 2023-12-04 151202](https://github.com/electron-userland/electron-builder/assets/22928302/d8deeb65-29dc-49c9-8e8c-5bc3b87cde68)

**Comment by Heet-vamja** [comment]
@andirsun Is your artiFactName and productName is same? If it is same, I reckon it is the root cause. could you please try changing artiFactName in such a way that productName and artiFactName not remain same.
