### ISSUE TITLE
bug: latest.yml filename wrong when package.json version includes '-'

### ISSUE THREAD

**Issue by joyexpr** [electron-userland/electron-builder#7505]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  16.19.1

* **Electron Version**: 22.3.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows 、macos

when my package.json version include '-', for example, '1.0.0-rc1'，after build, it generated rc1.yml or  rc1-mac.yml.

what I expected is latest.yml (latest-mac.yml) or 1.0.0-rc1.yml (1.0.0-rc1-mac.yml)

or is it has any options can custom my latest.yml filename ? I didnot find in the doc

**Comment by mmaietta** [comment]
I think that's intentional since `-rc1` is considered a prerelease? `latest` entails that it's an `x.x.x` semver

**Comment by joyexpr** [comment]
got it.  but for some reason, in our project, it is a normal release.  

may be I should modify the name by myself  after built.
