### ISSUE TITLE
How to exclude unused locales on Windows

### ISSUE THREAD

**Issue by kingyue737** [electron-userland/electron-builder#7506]
* **Electron-Builder Version**:  v23.6.0

* **Node Version**: v18.14.2

* **Electron Version**:  v23.1.4
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows 10

related issue: https://github.com/electron/electron/issues/18738

![image](https://user-images.githubusercontent.com/40021217/227834152-6f5f0615-e34d-4ef6-a84f-69fcbc8b4d03.png)

electron-builder includes all the locales in the final pack. I only found `mac.electronLanguages` in config. Didn't find a config for Windows to choose which locales to include.

**Comment by mmaietta** [comment]
AFAICT, the code logic supports both windows and mac, but the filename filter only checks for `.lproj`. Is it even safe to delete `.pak` files on windows? Can you confirm the electron app runs without those files?

**Comment by kingyue737** [comment]
1. My app contains English and Chinese. I removed all the other locales, the app still ran perfectly. 
2. Then I removed `zh-CN.pak`. The app still worked fine but the font family changed.
3. Finally, I deleted the remaining `en-US.pak` and the app no longer worked properly.

It seems safe to remove unused locales.

**Comment by NoahAndrews** [comment]
I believe this should have been closed when #7516 was merged, but the wrong keyword was used in the PR's description.
