### ISSUE TITLE
Setting CSC_IDENTITY_AUTO_DISCOVERY=false skips signing although I've specified the CSC_KEY_PASSWORD and CSC_LINK variables to use my own certificate rather than the one in keychain. 

### ISSUE THREAD

**Issue by nfl-nzr** [electron-userland/electron-builder#7515]
* **Electron-Builder Version**:  23.6.0

* **Node Version**: 14.21.3

* **Electron Version**:12.0.0
* **Electron Type (current, beta, nightly)**:

* **Target**: Mac

 Setting CSC_IDENTITY_AUTO_DISCOVERY=false skips signing although I've specified the CSC_KEY_PASSWORD and CSC_LINK variables to use my own certificate rather than the one in keychain. 
 Wouldn't CSC_IDENTITY_AUTO_DISCOVERY=false force using the specified cert file?
 Instead I see the following message. If I remove the variable I see that it picks up the Developer ID Application cert that is available in keychain.
 `skipped macOS application code signing  reason=, see https://electron.build/code-signing CSC_IDENTITY_AUTO_DISCOVERY=false`

**Comment by sduthil** [comment]
I agree that it's rather weird to completely disable signing by disabling auto-discovery... That being said a certificate file can contain multiple certificates, so auto-discovery may still be useful when setting a specific file. 

If you want to use a specific certificate in the file, you can provide `CSC_NAME=123456789ABCDEF`, where the value is the certificate hash (e.g. `ADC03B244F4C1018384DCAFFC920F26136F6B59B`) or certificate name (e.g. `Developer ID Application: …`).

More info about signing certificates here: https://developer.apple.com/forums/thread/701514.
