### ISSUE TITLE
NSIS: When `isAdminRightsRequired` is incorrectly set to false in `update-info.json`, updating fails

### ISSUE THREAD

**Issue by NoahAndrews** [electron-userland/electron-builder#7523]
* **electron-updater version**: 6.0.2

* **Node Version**: 16.19.1

* **Target**: NSIS

https://github.com/electron-userland/electron-builder/pull/7503 may have fixed the happy case, but it (re?) introduced a problem with error handling. PR incoming.

**Comment by mmaietta** [comment]
Released `6.0.3`, thanks for fixing this!
