### ISSUE TITLE
Pressing the Tab button while installing will cause the NSIS installer to crash.

### ISSUE THREAD

**Issue by weiluenju** [electron-userland/electron-builder#7526]
* **Electron-Builder Version**: 23.6.0
* **Node Version**: 16.16.0
* **Electron Version**:21.3.4
* **Electron Type (current, beta, nightly)**:current
* **Target**: Windows

This problem occurs when using the NSIS installer and set oneClick is true. 

Pressing Tab during the installation process will cause the program show no respond and stuck.

![image](https://user-images.githubusercontent.com/10330207/230278577-70066994-2a8f-4531-964c-0f83324e508d.png)

**Comment by mmaietta** [comment]
I think that's just how NSIS installers work? I'm not even sure what the Tab button equates to during an install process.

**Comment by weiluenju** [comment]
Some blind people try to click the Tab button during the installation process to make sure there is a Next or OK button, which causes the installer to not respond.

This bug does happen, so why close it? @mmaietta 

> I think that's just how NSIS installers work? I'm not even sure what the Tab button equates to during an install process.

**Comment by mmaietta** [comment]
Unless you're an expert in `.nsh` scripting for NSIS installers, there's no way for me to complete this. I don't even know if it's possible to fix in the `.nsh` scripts, if it can't be, then it's most certainly not a bug within electron-builder
