### ISSUE TITLE
NSIS Installer Issue: Unnecessary Uninstallation Prompt when Renaming Installer Executable

### ISSUE THREAD

**Issue by EvanMeek** [electron-userland/electron-builder#7527]
* **Electron-Builder Version**:  ^23.6.0

* **Node Version**:  ^23.6.0

* **Electron Version**: ^20.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis

When creating an installer with NSIS, if the filename is changed to one that doesn't include version information, it may result in the installer prompting to uninstall the previous version before proceeding with the installation, even if the files are identical.

eg: 
packaged exe filename:  helloworld-beta-0.0.1.exe
rename to : helloworld-beta.exe

**Comment by EvanMeek** [comment]
Does anyone handle this error? This bug is 100% reproducible.

**Comment by mmaietta** [comment]
How is that an error?
Windows assigns a GUID to an application, so no matter how you name the file, it'll still reference the previous install GUID to prompt uninstalling the previous version
