### ISSUE TITLE
Separate test and production builds on Squirrel.Windows

### ISSUE THREAD

**Issue by symbyte** [electron-userland/electron-builder#753]
* **6.3.0**: 

* **Mac/Windows**: 

I am trying to be able to create separate test and production builds for my application. On mac this works fine by changing the appId from `my.domain.appid` to `my.domain.appid-test` for my test version. Both the mac prod build and the mac test build are able to run at the same time with no problems. 

When I try to do the same thing with the windows build, the more recently installed build always overwrites the least recently installed build causing the shortcut for the older build to do nothing. I'm assuming this is because appId is only supported for `nsis` distributions on windows and that lack of support is not allowing the applications to have unique ids and thus overwriting each other. 

Is there any way support for appId can be added to the `Squirrel.Windows` target? If not, is it possible to get this behavior another way?

**Comment by develar** [comment]
Use `--extraMetadata` CLI param to change `productName` of your test app.

> Is there any way support for appId can be added to the Squirrel.Windows target?

`appId` will not help you on Windows in any case. Yes, you must use different (only if you explicitly set it, otherwise changing `productName` is enough) `appId`, but app will be installed on Windows using your product name, so, even for superb NSIS you need to change `productName`.

**Comment by symbyte** [comment]
I should have mentioned that I am already changing the `productName` for the test app when generating the test build and I am getting this behavior.

**Comment by develar** [comment]
@symbyte Please try to change `name`.

**Comment by symbyte** [comment]
I'm also already changing `name` on the test build of the app =(

**Comment by develar** [comment]
Hmm... I cannot believe. If name and productName are changed, it is different app. Does NSIS works for you?

**Comment by symbyte** [comment]
I will try to reproduce with NSIS either Wednesday or Thursday

**Comment by symbyte** [comment]
I tried with NSIS and everything worked fine. After this I went back and double checked my `package.json` and `name` was not being reset for test builds as I thought. I apologize for the confusion. 

Would it be possible to use something other than the `name` to make a windows application unique? It feels weird to have appId be the uniqueness identifier for mac but the windows build you have to change the name of the repo.
