### ISSUE TITLE
feature request: Migration to @electron/asar

### ISSUE THREAD

**Issue by sprout2000** [electron-userland/electron-builder#7536]
Currently we are greeted with the following message every time we install electron-builder:

```shell
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.
There is no API change, just a package name change
````

Please update the dependency package as they say it's **just a package name change**.

* **Electron-Builder Version**: 23.6.0

* **Node Version**: v18.15.0

* **Electron Version**: 24.1.0

* **Target**:  win32, darwin (intel, aarch64), linux

**Comment by ydelx** [comment]
Hello, I keep getting "npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward." when installing ASAR, how to solve this error，thanks for you .

**Comment by mmaietta** [comment]
electron-builder doesn't use @electron/asar, it has a custom asar bundling process
(I've spent the last year trying various paths to migrate to it though....no success yet 🙁  )
