### ISSUE TITLE
feature request: Migration to @electron/osx-sign

### ISSUE THREAD

**Issue by sprout2000** [electron-userland/electron-builder#7537]
Currently we are greeted with the following message every time we install electron-builder:

```shell
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward.
Be aware the API is slightly different
```
Please update the dependency package as they say its API is just **slightly** different.

* **Electron-Builder Version**: v23.6.0

* **Node Version**: v18.15.0

* **Electron Version**: v24.1.0

* **Target**: win32, darwin (intel, aarch64), linux

**Comment by mmaietta** [comment]
It's already updated in electron-builder `v24` :)
