### ISSUE TITLE
Do we really need a setuid root chrome-sandbox for every platform?

### ISSUE THREAD

**Issue by jbillingredhat** [electron-userland/electron-builder#7545]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  16

* **Electron Version**: 21.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: x86_64 linux

I opened a ticket for the Bitwarden client, which uses electron-builder, and they asked me to raise this issue here.

The Bitwarden client package package uses the electron-builder tool to build its packages. The resulting package has a post script that sets a setuid root chrome-sandbox. I'm seeing this in the latest RHEL/Fedora and Debian packages.  On the RPM packages being created, the chrome-sandbox executable is modified as part of the post-install process, which results in the package failing RPM validation because the mode on the file is different than what the package manifest claims. Any tool that relies on the RPM database validation would fail on that package. 

Also, I really would prefer to keep the number of setuid root executables on my systems to a minimum.

Looking through the Issues raised here, it looks like the setuid root executable is only needed  for sandboxing on platforms that do not support namespaces.  Perhaps the 'chmod 4755' command could have some logic to detect whether the kernel supports it before setting the mode? As far as I know, user namespaces are enabled by default in 5.10 and later Linux kernels. RHEL8 and later have it enabled by default, as does every supported Fedora.  I expect many other distros do as well.

**Comment by mmaietta** [comment]
> have some logic to detect whether the kernel supports it before setting the mode?

Try changing that line to this?
```
if [[ `cat /boot/config-$(uname -a | awk '{print $3}') | grep '^CONFIG_USER_NS'` == "CONFIG_USER_NS=y" ]]; then echo "You have support for User Namespaces, skipping setuid root chrome-sandbox"; else chmod 4755 '/opt/${sanitizedProductName}/chrome-sandbox' || true; fi
```
Pulled the code from https://stackoverflow.com/a/40155124

I don't know enough linux to be able to assist much here, but happy to open a PR for it the change above works for you

**Comment by jbillingredhat** [comment]
> if [[ `cat /boot/config-$(uname -a | awk '{print $3}') | grep '^CONFIG_USER_NS'` == "CONFIG_USER_NS=y" ]]; then echo 

This might not work if the builder is running in a container, since `uname -a` or more specifically, `uname -r` will reflect the kernel of the host and not the container.

**Comment by mmaietta** [comment]
Sorry, I'm really out of my element on this topic.

**Comment by Lunarequest** [comment]
hi I'm not too well versed in this but I have worked on flatpak's which have no setuid binaries so electron can't have any setuid binaries. Currently chrome's sandbox is tied to setuid binaries it is not possible to disable without a work around like [zypak](https://github.com/refi64/zypak) there are talks of a namespace based sandbox but I'm not aware of how far its gotten
