### ISSUE TITLE
Why isn't  differential update supported on macOS?

### ISSUE THREAD

**Issue by beyondkmp** [electron-userland/electron-builder#7547]
* **Electron-Builder Version**: 
23.6.0

* **Node Version**: 
Node 18

* **Electron Version**:
Electron 22

The electron updater now supports differential updates, but I noticed that it hasn't been implemented on macOS. Is there any technical limitation for this? If not, I'm willing to implement it.

**Comment by mmaietta** [comment]
I don't think there's any technical limitation. IIRC `zip` blockmaps already exist? All `electron-builder` is doing is downloading the files, then serving them over localhost to Electron's native `electron-updater`

**Comment by petem24** [comment]
I'm also looking for this. Seems crazy download my full app size (180mb) for a 100kb patch
