### ISSUE TITLE
electron-builder.js is executed in windows script host

### ISSUE THREAD

**Issue by Lunarequest** [electron-userland/electron-builder#7553]
* **Electron-Builder Version**: 23.60

* **Node Version**: 19.x

* **Electron Version**: 24.1.2
* **Electron Type (current, beta, nightly)**:current

5.3.0

* **Target**:  windows

For awhile now I have been unable to release windows binaries as when `yarn dist` i.e. `electron-builder --config electron-builder.js` is run it outputs nothing and runs until the ci timesout. I have tried changing other things but it appears to be a problem related electron-builder, an example is this job(https://github.com/Lunarequest/NightPDF/actions/runs/4782230243/jobs/8501375773) which is stuck on using electron-builder and has no output

**Comment by mmaietta** [comment]
Can you try renaming the js config file and explicitly define the config param `electron-builder --config electron-builder-config.js`

**Comment by mmaietta** [comment]
I mentioned to rename the file `--config electron-builder-anything.js`

**Comment by Lunarequest** [comment]
renaming the file to `electron-build-anything.js` fixes it, would there be a better way to fix it?

**Comment by mmaietta** [comment]
Unfortunately, no. AFAICT, the `electron-builder.js` is perceived as a node executable on windows, so calling `electron-builder` calls the script instead. The only way around this is by using a different name and pass to `--config`
