### ISSUE TITLE
macOS update Electron Builder strange behavior

### ISSUE THREAD

**Issue by TrofinSorin** [electron-userland/electron-builder#7561]
I've implemented an Electron update for macOS with Electron Builder but I've noticed a strange behavior during the update.

I publish to a public github repository a version 1.0.1, let' say;

I then open my currently installed 1.0.0 version;

I receive the prompt to update;

I press restart which does quit the app and start installing the updates;

ISSUE: but the update takes 30-45 seconds to install.

So if I open the app again after 20 seconds (after starting the actual update), the same update prompt is there with asking me if I want to update, and I become stuck within an update loop prompt, where I hit "Yes" for update, open the app again, seeing the prompt and so on.

The idea of displaying an info message for users "Please don't open the app for 1 min after hitting the update button" is not actually a viable solution.

Is there any way we could add a loading view while the actual update is being made? Or can I catch the pending update and restrict them to open the app somehow? It only happens on macOS.

"electron": "^24.0.0", 
"electron-builder": "^23.6.0", 
macOS version: Catalina

**Comment by mmaietta** [comment]
MacOS installation process uses a localhost server than then pipes to electron's built-in native updater. Unfortunately, it doesn't receive progress updates. AFAICT, it's doing a native implementation of copy-pasting the new `.app` over the previous install, with signature validation.

> Is there any way we could add a loading view while the actual update is being made? Or can I catch the pending update and restrict them to open the app somehow? It only happens on macOS.

I'd recommend creating a temporary "update lockfile" that is stored in your app cache directory, which would persist between app launches. Check for the file existence on app launch and determine if the app should automatically close.
