### ISSUE TITLE
requestedExecutionLevel not working on target Portable Build

### ISSUE THREAD

**Issue by HyunhoCho** [electron-userland/electron-builder#7566]
Version: ^23.6.0
Electron Version: ^19.0.0
Target: Portable

Hi, I am new to electron and electron-builder. I have this config (see below), and I am trying to make my application having requireAdministrator for requestedExecutionLevel. The build is successful, however, when I open my application, it doesn't ask/request to be run as administrator. Can someone help me on this? Thank you in advance.

I Think that when i tried double click my App,
Windows OS suggest Alert about usage of Administrator Auth.

        config:{
            asar: true,
            win: {

                target: [
                    {
                    target: 'portable',
                    arch: [
                        'x64'
                        ]
                    },
                ],
                icon: 'src/static/images/favicon_STg_icon.ico',             
                requestedExecutionLevel : 'requireAdministrator',
                },
            nsis: {
                oneClick: false,
                perMachine: true,
                installerIcon: 'src/static/images/favicon_STg_icon.ico',
                createDesktopShortcut: true,
                allowElevation: false,
            },
            directories: {
                buildResources: './resources/installer/',
                output: './dist/',
            },
            buildVersion: '20200524'

        }
    }).then(function(value){
        console.log('result', value);
        
    }).catch(function(error) {
        console.log('catch', error);
      }).finally(function() {
        if (typeof cbFunc === 'function') {
          cbFunc();
        }
    });
}

**Comment by qazhub** [comment]
I've had the same issue with 23.3.3. The built exe file would unpack, but it does not ask for admin elevation, the app does not launch at all. If I go to the unpacked directory (inside Temp) manually, I can see the exe file has a shield icon on it, and launching it would correctly ask for admin elevation.

**Comment by qazhub** [comment]
It's an issue of the documentation. By reading throughout the source code, I found another option related the elevation of portable builds, see [here](https://github.com/electron-userland/electron-builder/commit/3f8caab0cd7e403c4124882a53da1a7929399a98#diff-bc25504c53a7561a4cd2350125da5df7ef91537bdf2de827d899f2570728753fR158) and [here](https://github.com/electron-userland/electron-builder/blob/80a3ae857b9305aff1774e1b2b932601af50231b/packages/app-builder-lib/src/targets/nsis/nsisOptions.ts#L199).

So the correct configuration should be like this:

```json5
{
  // ...
  win: {
    target: [
      {
        target: "portable",
        arch: [ "x64" ]
      }
    ],
    artifactName: "xxxxx",
    requestedExecutionLevel: "requireAdministrator",  // This is mentioned in the doc
  },
  portable: {
    requestExecutionLevel: "admin", // However this is not
  }
  // ...
}
```

You need to put `requestExecutionLevel` under `portable` key too, and it has different option values as well.

**Comment by qazhub** [comment]
The `win.requestedExecutionLevel` key controls your main program (the entrance `.exe` file), and the `portable.requestExecutionLevel` controls the final portable `.exe` file.
When launching a portable app, the portable `.exe` runs first, it extracts all the files - includes the main `.exe` file - to a temporary directory; it would then run the main `.exe` file.

So the `win.requestedExecutionLevel` is not necessary. If the portable `.exe` required admin elevation upon launching, the main program (your app process) would inherit the privilege as well. So setting `portable.requestExecutionLevel` is enough.

**Comment by HyunhoCho** [comment]
Wow Thanks a lot
