### ISSUE TITLE
auto-updater notification has no icon and adds app.electron prefix to app name

### ISSUE THREAD

**Issue by chipimix** [electron-userland/electron-builder#7576]
* **Electron-Builder Version**: 23.6.0
* **Node Version**:  16.15.0
* **Electron Version**: 24.3.0 
* **Electron Type (current, beta, nightly)**: current
* **Which version of electron-updater are you using (if applicable)?**: 5.3.0
* **Target**: 
windows 11

Hi!

Is there any way to parameterize the notifications for the autoUpdater so that I can choose the same app name and icon as other electron notifications?

In the image below you can see the autoUpdater notification on top and regular app notifications below. Both notifications fetch MY_APP_PRODUCT_NAME from package.json's productName key-value. 
![image](https://github.com/electron-userland/electron-builder/assets/15652959/7a25ec59-a91a-48ce-b6fb-ce0d16e47bce)
However, for some reason, the autoUpdater adds app.electron prefix to this. How can I remove this?
Additionally, is it possible to parameterize the autoUpdater icon?

Thanks in advance!

**Comment by GorlikItsMe** [comment]
I think this can help you https://github.com/electron-userland/electron-builder/issues/4783#issuecomment-599343629
