### ISSUE TITLE
Electron-Updater returning 404 on Bitbucket

### ISSUE THREAD

**Issue by faribauc** [electron-userland/electron-builder#7577]
* **Electron-Builder Version**: 23.6.0
* **Electron-Updater Version**: 5.3.0

* **Node Version**: v16.18.0

* **Electron Version**: 21.3.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32

I have an Angular/Electron app running, which I want to auto-update itself. I have `electron-builder` working, it uploads the build files (`<name>.exe`, `<name>.blockmap` and `latest.yml`) without issue. But when I run the app on my Windows machine, `electron-updater` returns a 404 on the "latest.yml" file.

I've rested it directly with cURL and it works fine.

```
curl -L -H "Authorization: Basic <token>" https://api.bitbucket.org/2.0/repositories/<owner>/<repo>/downloads/latest.yml
```

The only different I can see is the `-L` switch which makes cURL follow redirects. Is this handled by `electron-updater`? Does it require some specific config for this to work properly?

Or maybe I'm doing the build wrong... I have the 2 `BITBUCKET_*` variables set on my build command. Should I expect the values to be built into the app? If not, what would be the best way to have those values set in the app without hardcoding them in the code?

Thanks!

-------

UPDATE 1: I tried to put those variables in a `.env` file and include it in the build files list but it doesn't seem to be read when the app is run on the Windows machine.

-------

UPDATE 2: I compiled the app as a Linux AppImage, then ran it from the command line while also setting the env variables in the command: `BITBUCKET_USERNAME=<user> BITBUCKET_TOKEN=<app-password> ./<name>.AppImage` but I'm also getting a 404 on the version update check. I see the variables as set if I log `process.env` to the console.

-------

UPDATE 3: I even hardcoded the values in the entry script like so on the very first line, before require statements:
```
process.env.BITBUCKET_USERNAME = '<user>';
process.env.BITBUCKET_TOKEN = '<app-password>';
```
and still getting a 404.

-------

UPDATE 4: Moved variables to `.env` and used `dotenv` to load them. That works, and I see the `Authorization` header right up to the point of the request:
```
request._urlLoaderOptions.headers {
  'x-user-staging-id': {
    name: 'x-user-staging-id',
    value: '00d94d71-bcfa-5150-a8be-ae0f1dbdca5b'
  },
  authorization: {
    name: 'Authorization',
    value: 'Basic: <token>'
  },
  'user-agent': { name: 'User-Agent', value: 'electron-builder' },
  'cache-control': { name: 'Cache-Control', value: 'no-cache' }
}
```
but still getting a 404. If I use those very same headers on a `cURL` request, it works fine.

I set the header using the `addAuthHeader` function:
```
const {autoUpdater} = require('electron-updater');
autoUpdater.addAuthHeader('Basic: ' + process.env.BITBUCKET_AUTH_TOKEN);
```

I'm at a loss at this poing, I don't know what else to try.

**Comment by faribauc** [comment]
Or maybe I'm doing the build wrong... I have the 2 BITBUCKET_* variables set on my build command. Should I expect the values to be build into the app? If not, what would be the best way to have those values set in the app without hardcoding them in the code?

**Comment by faribauc** [comment]
I tried to put thise variables in a `.env` file and include it in the build files list but it doesn't seem to be read when the app is run on the Windows machine.

**Comment by faribauc** [comment]
I compiled the app as a Linux AppImage, then ran it from the command line while also setting the env variables in the command: `BITBUCKET_USERNAME=<user> BITBUCKET_TOKEN=<app-password> ./<name>.AppImage` but I'm also getting a 404 on the version update check. I see the variables as set if I log `process.env` to the console.

**Comment by faribauc** [comment]
I even hardcoded the values in the entry script like so on the very first line, before require statements:
```
process.env.BITBUCKET_USERNAME = '<user>';
process.env.BITBUCKET_TOKEN = '<app-password>';
```

and still getting a 404.

**Comment by faribauc** [comment]
@jbool24 Would you happen to have any insight on this? I read the thread on  issue #6192 but nothing helped in my case.

**Comment by jbool24** [comment]
@faribauc I am not exactly sure based on your situation and setup, but something I realized is that the values get read differently at different times. During the build, you can use regular variables from .env, BUT during runtime, I had to make sure the variables were prefixed with `VITE_*` so they got "BAKED" into the output js files because my client's machines would not have the .env file at runtime. I also used basic auth and app password Auth for bitbucket so I have separated the values to use on the requests. There is an internal function that creates the base64 hash to pass on the requests.

I have the following present at build-time and no .env present at runtime on my Client's machines
```bash
VITE_BITBUCKET_APP_UPDATE_USERNAME=
VITE_BITBUCKET_APP_UPDATE_PASSWORD=
VITE_BITBUCKET_REPO_OWNER=
VITE_BITBUCKET_REPO_SLUG=
```
And I manually set up `autoUpdater` in the main process index.js with this:
```javascript
  autoUpdater.addAuthHeader(
    basicAuth(
      import.meta.env.VITE_BITBUCKET_APP_UPDATE_USERNAME,
      // eslint-disable-next-line comma-dangle
      import.meta.env.VITE_BITBUCKET_APP_UPDATE_PASSWORD
    )
  );
```

I'm not sure this is relevant to your problem but I'm happy to continue to help if I can

**Comment by faribauc** [comment]
OMFG here's the problem:

before:
```autoUpdater.addAuthHeader('Basic: ' + process.env['BITBUCKET_AUTH_TOKEN']);```
after
```autoUpdater.addAuthHeader('Basic ' + process.env['BITBUCKET_AUTH_TOKEN']);```

:facepalm: :facepalm: :facepalm: 

It would be very useful if the `BitbucketPublisher.convertAppPassword` was exposed, though.

Thanks @jbool24 for making me think in a different way. Had I not looked at the `convertAppPassword` again, I'm not sure I would've notived the extra semi-colon in my header value! :smile:

**Comment by faribauc** [comment]
The last issue is that the Win32 compiled app is not reading the `.env` file included in the build. It works when I run the compiled Linux version locally.

**Comment by jbool24** [comment]
You could add the .env to the "files" property in the `electron-builder.config.js` just to test values locally. Otherwise, I would make sure that your webpack or vite config defines the "string replace" values that will get used at runtime. I use Vite to build the web assets, so there is `import.meta.env` which will replace all usages of the exact values in code with the corresponding VITE_ value like I mentioned above. I think for webpack this was the DefinePlugin that does that job.

**Comment by faribauc** [comment]
@jbool24 I did add the `.env` file to undre `build.files` in `package.json`. Note that I'm using Angular so I don't have a webpack config per say. I do like the idea of a "built" environment file though. The idea behind using the `.env` file was to basically keep it out of the GIT repo, but I can just as easily do that with any file containing, although I do plan to have the release build process automated with CI/CD at some point, where env variables will probably be necessary.

**Comment by faribauc** [comment]
@reddybhavanish The issue disappeared after upgrading to Electron 24.x diring an upgrade to Angular 17. I'm also manually setting the env variables when I run the build command.
