### ISSUE TITLE
How to disable preAutoEntitlements

### ISSUE THREAD

**Issue by Xing1P** [electron-userland/electron-builder#7579]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.15.1

* **Electron Version**:24.2.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: mas

How to disable preAutoEntitlements osx-sign when build with Electron-builder

**Comment by mmaietta** [comment]
Closing. It was merged into electron-builder v24.4 IIRC
