### ISSUE TITLE
build is not recognized as external or internal command, operable program or batch file

### ISSUE THREAD

**Issue by Viren0007** [electron-userland/electron-builder#758]
* **6.7.6 although your git hub page shows latest builder is 6.7.7 but when I click on the link it shows latest version is 6.7.6**: 

* **Windows, Mac & Linux**: 

When i am executing command **npm run dist** it throws exception **build** is not recognized as external or internal command, operable program or batch file. I have attached log file with the issue.

[npm-debug.zip](https://github.com/electron-userland/electron-builder/files/478945/npm-debug.zip)

**Comment by develar** [comment]
All should be fine. Please try to install version `7.0.0`

**Comment by Niyaz2498** [comment]
Install electron-builder globally . It worked for me
