### ISSUE TITLE
'reload' is not defined

### ISSUE THREAD

**Issue by SudoVanilla** [electron-userland/electron-builder#7582]
* **Electron-Builder Version**: v22.10.3

* **Node Version**: v18.16.0

* **Electron Version**: 23.2.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: DMG

When building the DMG target, the following error occurs:
```
⨯ Exit code: 1. Command failed: /usr/bin/python3 /Users/korbsstudio/Desktop/Penpot-Desktop/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/korbsstudio/Desktop/Penpot-Desktop/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined
```

Also, the `dmg-builder` package should look for `/usr/bin/python3` if `/usr/bin/python`, creating a syslink is hard with newer versions of macOS. I should also note I'm on the M2 chip, not sure if that's important to know.

**Comment by liubobuzhidao** [comment]
Do you try update electron-builder version to 23.0.2?

**Comment by jmg-duarte** [comment]
> Do you try update electron-builder version to 23.0.2?

OP is using 23.2.0. Though I was having the same problem with v22.14.10 and upgrading to 23.6 worked.

**Comment by SudoVanilla** [comment]
Updating to the latest version has fixed this.
