### ISSUE TITLE
You should be able to define minimum windows version when building appx files

### ISSUE THREAD

**Issue by tormodAase** [electron-userland/electron-builder#7585]
* **Electron-Builder Version**: 23.6

* **Node Version**: 16.18

* **Electron Version**: 23.2
* **Electron Type (current, beta, nightly)**:

* **Target**: appx (x64, arm64)

When creating appx builds for x64 and arm64 architectures, they end up with different minimum windows versions. The x64 app has a minimum windows version of `10.0.14316.0`, while the arm64 app has a minimum windows version of `10.0.16299.0`. This prevents us from combining the apps into a single appxbundle. If we could set the target minimum windows version in our build config, it would solve our issue

**Comment by mmaietta** [comment]
Do you have any docs to point to on where a "minimum windows version" can be set for appx config? I've never worked with appx before.
