### ISSUE TITLE
Auto updater issue

### ISSUE THREAD

**Issue by qazhub** [electron-userland/electron-builder#7588]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.16.0

* **Electron Version**: 19.0.12
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: 5.3.0

* **Target**: Windows (NSIS oneClick)

I've done multiple tests on the same project, tweaking the config file according to the documentation. But I found the documentation very unintuitive and hard to understand:

1. If I use `generic` type to publish my updates, what files do I need to host? Seems to be `latest.yml` (or `{channel}.yml`, `app.exe` and `app.exe.blockmap`, but the documentation does not clearly list them.
2. It's not clear where I should put the `publish` key. I'm using `js` config file, and there's at least these locations the `publish` key can be placed:

A. it can be at the top level
```js
module.exports = {
  // ...
  win: {
    target: [
      {
        target: 'nsis',
        arch: ['x64'],
      }
    ],
    publish: [ "generic" ] // see https://www.electron.build/configuration/publish
  },
  nsis: {
    oneClick: true,
  },
  publish: [
    {
      provider: 'generic',
      url: "${env.UPDATE_URL}"
    }
  ]
}
```

B. it can be placed inside `nsis`:

```js
module.exports = {
  // ...
  win: {
    target: [
      {
        target: 'nsis',
        arch: ['x64'],
      }
    ]
  },
  nsis: {
    oneClick: true,
    publish: [
      {
        provider: 'generic',
        url: "${env.UPDATE_URL}"
      }
    ]
  }
}
```

C. it can be placed inside `win`:

```js
module.exports = {
  // ...
  win: {
    target: [
      {
        target: 'nsis',
        arch: ['x64'],
      }
    ],
    publish: [
      {
        provider: 'generic',
        url: "${env.UPDATE_URL}"
      }
    ]
  },
  nsis: {
    oneClick: true,
  }
}
```

And they all behave differently:

According to [the documentation](https://www.electron.build/configuration/publish):

> Generic (any HTTP(S) server) options. In all publish options File Macros are supported.

So all usages should expand `${env.UPDATE_URL}` with the environment variable I set. But `A` does not, building with this config results in error:

```log
dist/electron/main/index.js   347.30 KiB / gzip: 98.76 KiB         15:53:56
  • electron-builder  version=23.6.0 os=...
  • loaded configuration  file=....../electron-builder-config.js
  • writing effective config  file=release/0.5.1/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=... platform=win32 arch=x64
  • install prebuilt binary  name=...
  • rebuilding native dependency  name=...
  • packaging       platform=win32 arch=x64 electron=19.0.12 appOutDir=release/0.5.1/win-unpacked
  ⨯ Please specify "url" for "generic" update server
```

Then I tried `B`, it builds ok, but does not generate `app-update.yml` in `resources` directory, so when the app calls `autoUpdater.checkForUpdatesAndNotify()` it results in error:

```log
ENOENT: no such file or directory, open 'C:\Program Files\......\resources\app-update.yml'
```

After reading through a dozens of related issues, I found the only working config is `C`. This is based on comments of [this issue](https://github.com/electron-userland/electron-builder/issues/1939#issuecomment-321982709) and the original config of that author.

I'm quite confused. Is `A` and `B` considered bugs of electron-builder?

**Comment by iamsee** [comment]
need help !!

**Comment by qazhub** [comment]
This is still relevant.
