### ISSUE TITLE
Support command line switch for nsis oneclick installers to change between single vs multi user

### ISSUE THREAD

**Issue by lishid** [electron-userland/electron-builder#7598]
So it seems like nsis oneclick installers [can only be pre-configured](https://github.com/electron-userland/electron-builder/blob/e3fc9b544cc8c6728ffd77a45408d6e0e87dbb46/packages/app-builder-lib/templates/nsis/oneClick.nsh#L14) to either use single user mode (%appdata%) or multi user mode (Program Files) via the perMachine flag.

I am hoping to make an nsis oneclick installer with `perMachine: false` to take the `/allusers` cli parameter to install to Program Files at install time [like the assisted installer](https://github.com/electron-userland/electron-builder/blob/e3fc9b544cc8c6728ffd77a45408d6e0e87dbb46/packages/app-builder-lib/templates/nsis/assistedInstaller.nsh#LL118C25-L118C33).

**Comment by mmaietta** [comment]
I'm not familiar with nsis scripting. Happy to review a PR if you'd like to contribute!

**Comment by lishid** [comment]
This would still be a useful feature to add, although I am not quite familiar with NSIS scripting either and I haven't been able to look into it.
