### ISSUE TITLE
Custom Electron.app

### ISSUE THREAD

**Issue by adammeyer** [electron-userland/electron-builder#760]
* **Version**: 6.7.7

* **Target**: MacOS

I have a custom Electron.app I built manually (not using the Electron Prebuilt).  It would be great if I could use Electron Builder somehow with this custom build.

**Comment by develar** [comment]
Do you mean that you have own version of electron? I mean — electron-builder should somehow use your files instead of original from https://github.com/electron/electron/releases?

**Comment by adammeyer** [comment]
Yes, I have my own version.  Is there a way to tell Electron Builder to not use the prebuilt?

**Comment by develar** [comment]
You can set `ELECTRON_MIRROR` environment variable to use a custom base URL for grabbing Electron zips (https://github.com/electron-userland/electron-download)

But I think, no rush, — I can add option tomorrow morning (CET). `electronVersion` will accept path to zip of your electron version (or just directory). Is suitable for you?

**Comment by adammeyer** [comment]
Yes, that should work great.  Thank you!

**Comment by develar** [comment]
Please specify what is more suitable for you — path to local directory (where files named in the same way as electron) or base http path? How do you distribute your electron version?

**Comment by adammeyer** [comment]
Local directory

**Comment by develar** [comment]
[electronDist](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-electronDist)
