### ISSUE TITLE
invalid version for semver pre-releases when targeting `"pacman"`

### ISSUE THREAD

**Issue by m4rch3n1ng** [electron-userland/electron-builder#7601]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v20.2.0

* **Target**: pacman

building for target `"pacman"` with a [semver compatible pre-release version](https://semver.org/#spec-item-9) (e.g. `0.0.0-alpha.0`, `3.0.0-preview.19`) results in an invalid version format, since [arch linux does not allow hyphens in package versions](https://wiki.archlinux.org/title/PKGBUILD#pkgver). installing the package then results not in installing the desired `package-name@0.0.0-alpha.0` but instead `package-name-0.0.0@alpha.0`.

changing the hyphen to an underscore (like the arch wiki recommends) or a period (also common, though not recommended) results in an `Invalid version: "0.0.0_alpha.0"` error.

i am unsure how exactly to deal with this, but i would probably recommend following the advice from the arch wiki and replacing the hyphen with an underscore when building for the `"pacman"` target.

**Comment by mmaietta** [comment]
Happy to review a PR for the change!

**Comment by mvitale1989** [comment]
Hello @mmaietta , the current implementation still presents some weird ordering behaviour on Debian:
```bash
### According to semver 2.0, '1.0.0' should be considered greater than '1.0.0-rc1'. But for Debian it's not.
### This means that Debian will consider final releases a "downgrade" compared to the RCs, so it will always prefer installing the RC if both are available
$ dpkg --compare-versions 1.0.0 gt 1.0.0-rc1; echo $?
1
### On the other hand, using '~' instead of '-' yelds the correct ordering
$ dpkg --compare-versions 1.0.0 gt 1.0.0~rc1; echo $?
0
```

I have tested the changes from https://github.com/electron-userland/electron-builder/pull/7630 and extended the translation of `-` to a `~` for debian, and the deb packages are built with the correct version. I will open a PR to fix this.

**Comment by m4rch3n1ng** [comment]
ah i didn't see the footnotes when i opened the pr, the tilde is explained in the [debian docs in footnote 7](https://www.debian.org/doc/debian-policy/ch-controlfields.html#id22)
