### ISSUE TITLE
 'update-available'  do not fires immedately, it takes like 5 mins 

### ISSUE THREAD

**Issue by wangxiexe** [electron-userland/electron-builder#761]
* **Version**:  5.23.2

* **Target**:  windows 

I am creating an app with electron and electron-builder ,

everytime we update the seed server with a new version with files like below:

MicloudPC_Setup.exe
MiCloudPC-0.0.258-full.nupkg
RELEASES

and call in our app
autoUpdater.checkForUpdates()

it take quite a while (like 5 mins) for the 'update-available' event to be fired

it seems the updater only need to compare RELEASES and it then can know if there is update or not. 
why it take so long ? It seems the nupkg is getting downloaded and then the 'update-available' got fired.

btw, if there is no update, the 'update-not-available' event just fires immediately. 

any suggestions ? thanks a lot!

**Comment by develar** [comment]
Is is electron / Squirrel.Windows issue. Our own update for NSIS (#529) is not yet ready.
