### ISSUE TITLE
Error on run: "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by stoefln** [electron-userland/electron-builder#7612]
* **Electron-Builder Version**:  24.4.0

* **Node Version**: 18.16.0

* **Electron Version**: 12.2.3

* **Target**: mac arm64

When running "./node_modules/.bin/electron-builder build --mac --arm64" I am getting following error:

```
/Users/steph.../node_modules/tar/lib/read-entry.js:101
  [SLURP] (ex, global) {
   ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/steph/Workspace/myproj/node_modules/tar/lib/read-entry.js:101:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/steph/Workspace/myproj/node_modules/tar/lib/pack.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/steph/Workspace/myproj/node_modules/tar/lib/create.js:6:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

I found the same issue reported here: https://github.com/isaacs/node-tar/issues/384

Apparently, there seems to be something wrong with transitive dependency versions.

Output of `npm ls minipass tar`:
```
└─┬ electron-builder@24.4.0
  └─┬ app-builder-lib@24.4.0
    ├─┬ @electron/rebuild@3.2.13
    │ ├─┬ node-gyp@9.4.0
    │ │ ├─┬ make-fetch-happen@11.1.1
    │ │ │ ├─┬ cacache@17.1.3
    │ │ │ │ ├─┬ fs-minipass@3.0.2
    │ │ │ │ │ └── minipass@5.0.0 deduped
    │ │ │ │ ├─┬ glob@10.2.7
    │ │ │ │ │ ├── minipass@5.0.0 deduped
    │ │ │ │ │ └─┬ path-scurry@1.9.2
    │ │ │ │ │   └── minipass@5.0.0 deduped
    │ │ │ │ ├─┬ minipass-collect@1.0.2
    │ │ │ │ │ └── minipass@3.3.6
    │ │ │ │ ├── minipass@5.0.0 deduped
    │ │ │ │ └── tar@6.1.15 deduped
    │ │ │ ├─┬ minipass-fetch@3.0.3
    │ │ │ │ ├─┬ minipass-sized@1.0.3
    │ │ │ │ │ └── minipass@3.3.6
    │ │ │ │ └── minipass@5.0.0 deduped
    │ │ │ ├─┬ minipass-flush@1.0.5
    │ │ │ │ └── minipass@3.3.6
    │ │ │ ├─┬ minipass-pipeline@1.2.4
    │ │ │ │ └── minipass@3.3.6
    │ │ │ ├── minipass@5.0.0
    │ │ │ └─┬ ssri@10.0.4
    │ │ │   └── minipass@5.0.0 deduped
    │ │ └── tar@6.1.15 deduped
    │ └── tar@6.1.15 deduped
    └─┬ tar@6.1.15
      ├─┬ fs-minipass@2.1.0
      │ └── minipass@3.1.5 deduped invalid: "^5.0.0" from node_modules/tar
      ├── minipass@3.1.5 invalid: "^5.0.0" from node_modules/tar
      └─┬ minizlib@2.1.2
        └── minipass@3.1.5
```

**Comment by stoefln** [comment]
I fixed the issue by running `npx npm-force-resolutions; npm i`. Now the dependencies looks like this:
```
└─┬ electron-builder@24.4.0
  └─┬ app-builder-lib@24.4.0
    ├─┬ @electron/rebuild@3.2.13
    │ └─┬ node-gyp@9.4.0
    │   └─┬ make-fetch-happen@11.1.1
    │     ├─┬ cacache@17.1.3
    │     │ ├─┬ fs-minipass@3.0.2
    │     │ │ └── minipass@5.0.0 deduped
    │     │ ├─┬ glob@10.2.7
    │     │ │ ├── minipass@5.0.0 deduped
    │     │ │ └─┬ path-scurry@1.9.2
    │     │ │   └── minipass@5.0.0 deduped
    │     │ ├─┬ minipass-collect@1.0.2
    │     │ │ └── minipass@3.3.6
    │     │ └── minipass@5.0.0 deduped
    │     ├─┬ minipass-fetch@3.0.3
    │     │ ├─┬ minipass-sized@1.0.3
    │     │ │ └── minipass@3.3.6
    │     │ └── minipass@5.0.0 deduped
    │     ├─┬ minipass-flush@1.0.5
    │     │ └── minipass@3.3.6
    │     ├─┬ minipass-pipeline@1.2.4
    │     │ └── minipass@3.3.6
    │     ├── minipass@5.0.0 deduped
    │     └─┬ ssri@10.0.4
    │       └── minipass@5.0.0 deduped
    └─┬ tar@6.1.15
      ├─┬ fs-minipass@2.1.0
      │ └── minipass@3.3.6
      ├── minipass@5.0.0
      └─┬ minizlib@2.1.2
        └── minipass@3.1.5
```

**Comment by AlanGreyjoy** [comment]
> I fixed the issue by running `npx npm-force-resolutions; npm i`. Now the dependencies looks like this:
> 
> ```
> └─┬ electron-builder@24.4.0
>   └─┬ app-builder-lib@24.4.0
>     ├─┬ @electron/rebuild@3.2.13
>     │ └─┬ node-gyp@9.4.0
>     │   └─┬ make-fetch-happen@11.1.1
>     │     ├─┬ cacache@17.1.3
>     │     │ ├─┬ fs-minipass@3.0.2
>     │     │ │ └── minipass@5.0.0 deduped
>     │     │ ├─┬ glob@10.2.7
>     │     │ │ ├── minipass@5.0.0 deduped
>     │     │ │ └─┬ path-scurry@1.9.2
>     │     │ │   └── minipass@5.0.0 deduped
>     │     │ ├─┬ minipass-collect@1.0.2
>     │     │ │ └── minipass@3.3.6
>     │     │ └── minipass@5.0.0 deduped
>     │     ├─┬ minipass-fetch@3.0.3
>     │     │ ├─┬ minipass-sized@1.0.3
>     │     │ │ └── minipass@3.3.6
>     │     │ └── minipass@5.0.0 deduped
>     │     ├─┬ minipass-flush@1.0.5
>     │     │ └── minipass@3.3.6
>     │     ├─┬ minipass-pipeline@1.2.4
>     │     │ └── minipass@3.3.6
>     │     ├── minipass@5.0.0 deduped
>     │     └─┬ ssri@10.0.4
>     │       └── minipass@5.0.0 deduped
>     └─┬ tar@6.1.15
>       ├─┬ fs-minipass@2.1.0
>       │ └── minipass@3.3.6
>       ├── minipass@5.0.0
>       └─┬ minizlib@2.1.2
>         └── minipass@3.1.5
> ```

What is the equivalent using yarn?

**Comment by apm29** [comment]
> > I fixed the issue by running `npx npm-force-resolutions; npm i`. Now the dependencies looks like this:
> > ```
> > └─┬ electron-builder@24.4.0
> >   └─┬ app-builder-lib@24.4.0
> >     ├─┬ @electron/rebuild@3.2.13
> >     │ └─┬ node-gyp@9.4.0
> >     │   └─┬ make-fetch-happen@11.1.1
> >     │     ├─┬ cacache@17.1.3
> >     │     │ ├─┬ fs-minipass@3.0.2
> >     │     │ │ └── minipass@5.0.0 deduped
> >     │     │ ├─┬ glob@10.2.7
> >     │     │ │ ├── minipass@5.0.0 deduped
> >     │     │ │ └─┬ path-scurry@1.9.2
> >     │     │ │   └── minipass@5.0.0 deduped
> >     │     │ ├─┬ minipass-collect@1.0.2
> >     │     │ │ └── minipass@3.3.6
> >     │     │ └── minipass@5.0.0 deduped
> >     │     ├─┬ minipass-fetch@3.0.3
> >     │     │ ├─┬ minipass-sized@1.0.3
> >     │     │ │ └── minipass@3.3.6
> >     │     │ └── minipass@5.0.0 deduped
> >     │     ├─┬ minipass-flush@1.0.5
> >     │     │ └── minipass@3.3.6
> >     │     ├─┬ minipass-pipeline@1.2.4
> >     │     │ └── minipass@3.3.6
> >     │     ├── minipass@5.0.0 deduped
> >     │     └─┬ ssri@10.0.4
> >     │       └── minipass@5.0.0 deduped
> >     └─┬ tar@6.1.15
> >       ├─┬ fs-minipass@2.1.0
> >       │ └── minipass@3.3.6
> >       ├── minipass@5.0.0
> >       └─┬ minizlib@2.1.2
> >         └── minipass@3.1.5
> > ```
> 
> What is the equivalent using yarn?

how to do this in pnpm? : (
