### ISSUE TITLE
The electron automatic update also executes the customUnInstall of the nsis script

### ISSUE THREAD

**Issue by 1339240789** [electron-userland/electron-builder#7614]
* **Electron-Builder Version**: v23.6.0

* **Node Version**: v20.3.0

* **Electron Version**:v22.3.12
* **Electron Type (current, beta, nightly)**:current

* **Target**: windows nsis

I use electron-builder for automatic updates. I have configured an nsis include script. I don't want to execute customUnInstall in the script when it is automatically updated, I just want it to be executed when it is uninstalled

**Comment by ghost1face** [comment]
I ran into that too, I wasn't sure if that's normal expected behavior or not so I added a check to see if the installer was running in the update context:

```
!macro customUnInstall
   ${IfNot} ${isUpdated}
          // whatever you want to run on uninstall and not when updated
   ${EndIf}
!macroEnd
```

I am curious though for those who may have been using this longer, is this expected behavior?
