### ISSUE TITLE
electron-updater@6 not released on npm

### ISSUE THREAD

**Issue by mtdvlpr** [electron-userland/electron-builder#7615]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 18.16.0

* **Electron Version**: 25.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macos, windows, linux

Electron-updater@6 has been released on GitHub for a while now, but [npm](https://www.npmjs.com/package/electron-updater) and [yarn](https://classic.yarnpkg.com/en/package/electron-updater) are still on v5.3.0.

Is this intentional or an oversight?

**Comment by mmaietta** [comment]
Oversight!

Updated it.
