### ISSUE TITLE
Failed to get authorization for username '***' on GitHub CI

### ISSUE THREAD

**Issue by tbhaxor** [electron-userland/electron-builder#7617]
* **Electron-Builder Version**: v23.1.0

* **Node Version**: v16.13.2

* **Electron Version**: v25.1.0
* **Electron Type (current, beta, nightly)**: _no idea_

* **Target**:  Macos

```
2023-06-16 18:47:40.641 *** Error: Notarization failed for '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-notarize-UVgW1w/MyApp.zip'.
2023-06-16 18:47:40.641 *** Error: Unable to upload your app for notarization. Failed to get authorization for username '***' and password. (
    "Error Domain=NSCocoaErrorDomain Code=0 \"Status code: 0\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}"
) (-1011)
 {
    NSLocalizedDescription = "Unable to upload your app for notarization.";
    NSLocalizedFailureReason = "Failed to get authorization for username '***' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)";
}
```

I am getting error in github CI, this how I am setting environment in build script

```yaml
...
env:
   APPLE_ID: ${{ secrets.APPLE_ID }}
...
```

There is OTP on the login screen on web, could that be a reason, if yes how can i fix it?

**Comment by tbhaxor** [comment]
This *** is for security reason from github CI. They redact PII. I checked with

```js
console.log(process.env.APPLE_ID === "doe@john.com@") // true
```

**Comment by mmaietta** [comment]
> Note: You MUST specify APPLE_ID and APPLE_APP_SPECIFIC_PASSWORD via environment variables to activate notarization step

https://www.electron.build/configuration/mac

**Comment by tbhaxor** [comment]
> > Note: You MUST specify APPLE_ID and APPLE_APP_SPECIFIC_PASSWORD via environment variables to activate notarization step
> 
> https://www.electron.build/configuration/mac

Can we re-open this, it is still not done on my end?

Do you want to use `identifier` in electron build file?

**Comment by tbhaxor** [comment]
Now getting error 

Error: No authentication properties provided (e.g. appleId, appleApiKey)


```js
// notorize.js
const { notarize } = require("electron-notarize")

// const path = require("path")
// const notorizePath = path.parse(__filename)
// process.env.CSC_LINK = "file://" + path.join(notorizePath.dir, "ApplicationCertificates.p12")

exports.default = async function (context) {
  const {electronPlatformName, appOutDir} = context;
  if (electronPlatformName !== 'darwin') {
    return;
  }

  console.log('Notarizing script started');
  console.log(`Using certificate from ${process.env.CSC_LINK}`)
  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    appBundleId: 'com.myapp.app',
    appPath: `${appOutDir}/${appName}.app`,
    // appleId: process.env.APPLE_ID,
    // appleIdPassword: process.env.APPLE_ID_PASSWORD,
  });
};
```

And electron config is in

```js
// vue.config.js

const { defineConfig } = require("@vue/cli-service");
const { EnvironmentPlugin } = require("webpack");
const path = require("path")

module.exports = defineConfig({
  pluginOptions: {
    electronBuilder: {
      extends: null,
      nodeIntegration: false,
      preload: {
        common: "electron/preloads/common.js",
      },
      mainProcessFile: "electron/background.js",
      builderOptions: {
        appId: "com.myapp.app",
        productName: "MyApp",
        artifactName: "${productName}-v${version}.${ext}",
        win: {
          target: ["nsis"],
        },
        linux: {
          target: ["AppImage"],
          category: "Utility",
        },
        mac: {
          target: ["dmg", "zip"],
          icon: "electron/build-rsrc/icon.png",
          hardenedRuntime: true,
          gatekeeperAssess: false,
          identity: `file://` + path.join(__dirname, "scripts", "ApplicationCertificates.p12")
        },
        afterSign: 'scripts/notorize.js',
        dmg: {
          title: "Install ${productName} v${version}",
        },
      },
    },
  },
  chainWebpack: (config) => {
    config.plugin("process.env").use(EnvironmentPlugin);
    config.output.hashFunction("sha256");
  },
  transpileDependencies: true,
  lintOnSave: false,
});

```

**Comment by tbhaxor** [comment]
Now getting error

Error: No authentication properties provided (e.g. appleId, appleApiKey)

**Comment by Ladvace** [comment]
I follow all the steps but I still get:

`Error: No authentication properties provided (e.g. appleId, appleApiKey, keychain)`

**Comment by mmaietta** [comment]
Sorry, this issue fell off my radar in my GH notifications list. This is the logic being used before calling the official npm `electron/notarize` package. Hopefully this helps describe further what env vars are needed to activate the notarization integration.
https://github.com/electron-userland/electron-builder/blob/d5d9f3f9aaac0385cc943e30a0841669133afde8/packages/app-builder-lib/src/macPackager.ts#L532-L584

@Ladvace looks like your error may be coming from the electron/notarize package itself as I don't see that line logged anywhere in electron-builder. Can you please double-check the code linked above to make sure your env vars are set correctly? I'm wondering if we missed a verification edge case in the current notarization logic.

**Comment by Ladvace** [comment]
I think I probably called them in a different why, that's why, I'm gonna try renaming them asap:

`APPLE_API_KEY`
`APPLE_API_KEY_ID`
`APPLE_API_KEY_ISSUER`

**Comment by Ladvace** [comment]
actually another thing I got in before the error above is this one: 

`  • skipped macOS notarization  reason=`notarize` options were unable to be generated`

is this something related or can I ignore it?

**Comment by Ladvace** [comment]
@mmaietta  I think I managed to do this, but for some reason now I'm getting this error:

```
 ⨯ Unexpected token 'E', "Error: The"... is not valid JSON  failedTask=build stackTrace=SyntaxError: Unexpected token 'E', "Error: The"... is not valid JSON
SyntaxError: Unexpected token 'E', "Error: The"... is not valid JSON
    at JSON.parse (<anonymous>)
    
```

those are the env I'm currently using:

```

APPLE_API_KEY_ID=MY_KEY
APPLE_API_ISSUER=MY_ISSUER_ID
APPLE_TEAM_ID=MY_TEAM_ID
APPLE_API_KEY=/Users/name/private_keys/AuthKey_MY_KEY.p8
```

**Comment by Ladvace** [comment]
one problem I'm getting is, not sure why thi happens since I've setted `APPLE_API_ISSUER`

`Error: The appleApiIssuer property is required when using notarization with ASC credentials`

**Comment by Ladvace** [comment]
managed to fix!, I think I didn't have to set notarize: true in the package.json since i'm using `electron-builder-notarize`
