### ISSUE TITLE
how to build onefile exe for windows 11?

### ISSUE THREAD

**Issue by sandersbasket** [electron-userland/electron-builder#7618]
* **Electron-Builder Version**:  lastet

* **Node Version**:  lastet

* **Electron Version**: lastet
* **Electron Type (current, beta, nightly)**: current

* **Target**:  my app

how to build onefile exe for windows 11?

**Comment by mmaietta** [comment]
Please provide more info? What archs are you trying to combine?

It should already be possible for it to build archs into one exe file
