### ISSUE TITLE
Which files get signed?

### ISSUE THREAD

**Issue by chscott** [electron-userland/electron-builder#7619]
* **Electron-Builder Version**: 

22.13.1

* **Node Version**: 

14.17.5

* **Electron Version**:

11.5.0

* **Electron Type (current, beta, nightly)**:

N/A

* **Target**: 

`win`

Which files get signed, and is there any difference in this respect between automatic signing and using a delegated signing script via the `sign` property? I'm asking because I had to switch from automatic to delegated due to DigiCert's requirement to use EV code-signing certificates, and I'm seeing that the files that usually get signed are now not signed. I'm also troubleshooting this from the script perspective, but I can't seem to find any documentation on what files get signed with the two different approaches (automatic v. delegated).

**Comment by mmaietta** [comment]
AFAICT, it's the same logic as to what is signed. We're just replacing the signtool command with your hook but it's executed against all the task configurations the same
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L55
