### ISSUE TITLE
Autostart app after Install

### ISSUE THREAD

**Issue by jochenonline** [electron-userland/electron-builder#762]
* **Version**: 7.3.0

* **Target**: Win, Mac, Linux

Wenn installing my app with NSIS under Windows. My app is started automatically after successful setup. Now I have to questions:

1. Where is the switch to influence the postInstallStart under Windows?
2. Is it possible to have the same effect on OSX and Linux? At the moment I use DMG and DMG there. Do I have to use sth different to achieve what I want?

**Comment by develar** [comment]
> Where is the switch to influence the postInstallStart under Windows?

Please see https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script and https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions-runAfterFinish

> Is it possible to have the same effect on OSX and Linux? At the moment I use DMG and DMG there. Do I have to use sth different to achieve what I want?

You should not. macOS and Linux offers you zero installation and you should not auto start app.
