### ISSUE TITLE
How run as admin can install in current user appdata

### ISSUE THREAD

**Issue by algorys** [electron-userland/electron-builder#7623]
* **Electron-Builder Version**: 
24.4.0

* **Node Version**: 
18.16.0

* **Electron Version**: 
25.0.1
* **Electron Type (current, beta, nightly)**:
N/A

* **Target**: 
Windows

I've an electron app that I installed in $LocalAppdata folder today. My configuration is as follow today :

```json
"nsis": {
    "oneClick": true,
    "perMachine": false,
    "createDesktopShortcut": true,
    "createStartMenuShortcut": true,
    "runAfterFinish": false,
    "include": "installer.nsh"
}
```

In my `installer.nsh` file:

```nsh
!macro preInit
  SetRegView 64
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppdata\Programs\My App"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppdata\Programs\My App"
 SetRegView 32
    WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppdata\Programs\My App"
    WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$LocalAppdata\Programs\My App"
!macroend
```

If I run the installer as normal user (or admin user), everithing works fine and app is installed under "$LocalAppdata\Programs\My App" without any problem.

But in case of a normal user who right click on installer then choose "install as administrator", app will be installed inside `$LocalAppdata` of admin account and not the current user. I've tried to find a solution by replacing `$LocalAppdata` by `$PROFILE` but it seems not resolves my issue.

Can I have help please to make it work and use the current user `$LocalAppdata` instead of the admin who give the rights ?

Is there a way to do that by `.nsh` script ?

Thanks in advance !

**Comment by mmaietta** [comment]
Sorry, `.nsh` files are a bit outside my expertise. Will leave this issue open in case someone else can chime in

**Comment by VigneshSonaiya** [comment]
I'm also finding resolution for this issue
