### ISSUE TITLE
Suggestion:  support relocatable RPM package

### ISSUE THREAD

**Issue by lfeigen** [electron-userland/electron-builder#7625]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 16.17

* **Electron Version**: 25.1.0
* **Electron Type (current, beta, nightly)**: current
 5.3.0

* **Target**: This issue is relevant to rpm packages, though we build for many

A customer of ours has asked that our rpm package be relocatable - http://ftp.rpm.org/api/4.4.2.2/relocatable.html .  We use electron-builder to build it and I don't think there is a way to make it do such.  Seems reasonable enough, though I'm no expert on RPM.

**Comment by mmaietta** [comment]
I'm also no expert on RPM, but is this for the beta auto-update feature or is this via manual installation?

**Comment by lfeigen** [comment]
Manual installation.
