### ISSUE TITLE
【Question】How can I sign the DLL files in the nsis-resources during the packaging process?

### ISSUE THREAD

**Issue by sjfkai** [electron-userland/electron-builder#7634]
How can I sign the DLL files in the nsis-resources during the packaging process? I need to digitally sign all the DLL files used during the installation phase, but I haven't found a feasible method to accomplish it.

**Comment by mmaietta** [comment]
You should be able to go two routes.

There's a handler for using your own signing tool and process via `win.sign` property
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/options/winOptions.ts#L31-L34

Alternatively, there is also the `afterPack` hook where you can directly path to the `resources` folder.
https://www.electron.build/configuration/configuration#afterpack
https://www.electron.build/configuration/configuration#afterpackcontext
