### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch

### ISSUE THREAD

**Issue by asifnawaz24** [electron-userland/electron-builder#7635]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.15.1

* **Electron Version**: 23.2.0
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater Version**: 5.3.0

* **Target**: NSIS

I am getting the following error although after searching I found this solution ( https://github.com/electron-userland/electron-builder/issues/4682#issuecomment-808737800 ). My question is that is there a better way to handle this? Since manipulating packages doesn't seem like a very good fix. Also, it would be kind of you to share what differential download is and how do they work.

```
Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected eW80wDLXuxvwUpSr4DClif0nJcdHFnevcA8inxjJtx8tKPPwdwnhspGo9/VqnTHAU5YKOsDXXUCXPjTBWbmp1w==, got TfH5dXVEF7oP4W/qPGh+hbApXmxTnruD6y9hE5ytyuqDN8/5RrDI6e+VS3zNWQAZPu68x0Y0x/kAviydv53Qwg==
```

![image](https://github.com/electron-userland/electron-builder/assets/72155056/13fdce52-7b29-45c2-9901-9e3d44541978)

**Comment by freddy-daniel** [comment]
Got this issue after signing with renewed certificate....

**Comment by catshanshan** [comment]
I got this issue too.
