### ISSUE TITLE
Auto updater install in the foreground?

### ISSUE THREAD

**Issue by addlistener** [electron-userland/electron-builder#7636]
My app is large and auto-updater quitAndInstall() will take around 5min, during which time the app cannot be opened and seems broken.

Is it possible that I let the user open the setup binary manually in the foreground? So the user will know a installation is in progress and will be patient.

**Comment by mmaietta** [comment]
What OS is this on?

Windows installers have a progress bar by default IIRC.
Linux AppImages are simply a `execFileSync("mv", ["-f", options.installerPath, destination])` so there's no progress status available there
Mac Updates serve the zip file over localhost to electron's built-in electron-updater, so there's no progress status available either IIRC

**Comment by addlistener** [comment]
@mmaietta 

Edition	Windows 10 Pro
Version	22H2
Installed on	‎7/‎19/‎2021
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

I'm building thru windows PowerShell. And the target is 'nsis'

**Comment by Jaifroid** [comment]
I also need a foreground install. Also for Windows, but I don't see a progress bar currently (NSIS install).

**Comment by Jaifroid** [comment]
Well, that's a shame (atuo-closing this issue), because this is a real need.
