### ISSUE TITLE
Dynamically imported modules cannot be found in the asar

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#7641]
## Env

* **Electron-Builder Version**: 24.4.0

* **Node Version**: 18.16.0

* **Electron Version**: 8.43.0
* **Electron Type (current, beta, nightly)**: current

* **Electron-updater Version**: 6.1.1

* **Target**: Windows

## Description

If I try to import `electron-updater` dynamically, it will not be found inside `asar`
```ts
app
  .whenReady()
  .then(() => import('electron-updater'))
```
```
 Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'electron-updater'
```

Reproduction repository : https://github.com/cawa-93/auto-update-issue-test
`main` code: https://github.com/cawa-93/auto-update-issue-test/blob/29819c6dfbbc2406789faceb794d42f8594a1089/packages/main/src/index.ts#L5

## Steps to reproduce:
1. Clone [reproduction repository](https://github.com/cawa-93/auto-update-issue-test) and install dependencies by `npm ci`
2. Run `npm run compile` to build app.
3. Run `dist/vite-electron-builder Setup 1.0.6.exe` to install app.
4. Run installed app. I'm using this command:
    ```
    NODE_DEBUG=module ~/AppData/Local/Programs/vite-electron-builder/vite-electron-builder.exe
   ```
5. See console output. In my case it's:
   ```
	MODULE 15336: load built-in module electron/js2c/browser_init
	MODULE 15336: looking for "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\package.json" in []
	MODULE 15336: load "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\package.json" for module "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\package.json"
	MODULE 15336: looking for "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\dist\\index.cjs" in []
	MODULE 15336: Module._load REQUEST C:\Users\kozac\AppData\Local\Programs\vite-electron-builder\resources\app.asar\packages\main\dist\index.cjs parent: undefined
	MODULE 15336: looking for "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\dist\\index.cjs" in []
	MODULE 15336: load "C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\dist\\index.cjs" for module "."
	MODULE 15336: Module._load REQUEST electron parent: .
	MODULE 15336: looking for "electron-updater" in ["C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\dist\\index.cjs\\node_modules","C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\dist\\node_modules","C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\main\\node_modules","C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\packages\\node_modules","C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\app.asar\\node_modules","C:\\Users\\kozac\\AppData\\Local\\Programs\\vite-electron-builder\\resources\\node_modules"]
	Failed check and install updates: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'electron-updater' imported from C:\Users\kozac\AppData\Local\Programs\vite-electron-builder\resources\app.asar\packages\main\dist\index.cjs
	Did you mean to import electron-updater/out/main.js?
	    at new NodeError (node:internal/errors:399:5)
	    at packageResolve (node:internal/modules/esm/resolve:895:9)
	    at moduleResolve (node:internal/modules/esm/resolve:944:20)
	    at defaultResolve (node:internal/modules/esm/resolve:1159:11)
	    at nextResolve (node:internal/modules/esm/loader:163:28)
	    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
	    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
	    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
	    at importModuleDynamically (node:internal/modules/cjs/loader:1193:29)
	    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21) {
	  code: 'ERR_MODULE_NOT_FOUND'
	}
	```

At the same time, if you run the unpacked application, the error disappears and the module founded as expected.
```
dist/win-unpacked/vite-electron-builder.exe 
```
```
{
  module: [Module: null prototype] { ... }
}
```

**Comment by mmaietta** [comment]
Was this working previously with electron updater 5.x?
Just because it works in an unpacked application, doesn't mean that it's an electron-builder issue.

AFAICT, seems more like an issue with vite not bundling electron-updater into your project.
Have you tried using a direct import like the documentation shows?
`import { autoUpdater } from "electron-updater"`

**Comment by cawa-93** [comment]
@mmaietta Vite should not bundle `electron-builder`. It shipped as "external" dependencies, i.e. it stays in the node_modules folder and will be resolved by node at runtime.
If you install app and unpack asar you should see `node_module/electron-builder` in resources. 

Static import works fine. 
Also, cjs import works as expected. Vite does not handle such imports at all in the current configuration.

```ts
// source code
import {app} from 'electron';
import {autoUpdater} from 'electron-updater';

app
  .whenReady()
  .then(async () => {
    console.log('resolve', require.resolve('electron-updater'));
    console.log('cjs', require('electron-updater'));
    console.log('autoUpdater', autoUpdater);
    console.log('mjs', await import('electron-updater'));
    app.exit(0);
  })
```

```js
// Bundled code
const a = require('electron'), 
h = require('electron-updater'); // ok ✅
a.app.whenReady().then(async () => {
	console.log('resolve', require.resolve('electron-updater')), // ok ✅
	console.log('cjs', require('electron-updater')), // ok ✅
	console.log('autoUpdater', h.autoUpdater), // ok ✅
	console.log('mjs', await import('electron-updater')), // fail ❌
	a.app.exit(0);
}).catch(e => {
  console.error('Failed check and install updates:', e), a.app.exit(1);
});
```

**Comment by cawa-93** [comment]
Ok, it's not `electron-updater` specific. I try with `lodash` and got same issue.

**Comment by vgmartinez** [comment]
hi guys, any update on this? I have the same issue importing this: `const { pipeline, env } = await import('@xenova/transformers')`.

**Comment by mmaietta** [comment]
I'm wondering if this is an electron issue (or specific to asar?)
With the minimum reproducible repo on MacOS, I'm getting this in Devtools
```
VM171 index.cjs:1 Error: ENOTDIR: not a directory, stat '/Development/auto-update-issue-test/dist/mac-arm64/vite-electron-builder.app/Contents/Resources/app.asar/packages/main/dist/node_modules/lodash'
    at statSync (VM69 node:fs:1615:3)
    at tryStatSync (VM145 resolve:176:13)
    at packageResolve (VM145 resolve:864:18)
    at moduleResolve (VM145 resolve:944:20)
```
When I disable asar, i.e. `asar: false` in electron-builder config, everything runs correctly as expected and logs the mjs module. From what I can tell, it seems dynamic imports do not work within asar as `statSync` fails

**Comment by zacharygriffee** [comment]
> I'm wondering if this is an electron issue (or specific to asar?) With the minimum reproducible repo on MacOS, I'm getting this in Devtools
> 
> ```
> VM171 index.cjs:1 Error: ENOTDIR: not a directory, stat '/Development/auto-update-issue-test/dist/mac-arm64/vite-electron-builder.app/Contents/Resources/app.asar/packages/main/dist/node_modules/lodash'
>     at statSync (VM69 node:fs:1615:3)
>     at tryStatSync (VM145 resolve:176:13)
>     at packageResolve (VM145 resolve:864:18)
>     at moduleResolve (VM145 resolve:944:20)
> ```
> 
> When I disable asar, i.e. `asar: false` in electron-builder config, everything runs correctly as expected and logs the mjs module. From what I can tell, it seems dynamic imports do not work within asar as `statSync` fails

This was the only way I could get my app to work! ASAR was messing things up for some reason on my system. Thanks! Although I'd prefer the ASAR to work.

Zack
