### ISSUE TITLE
MSI Build error CNDL0242 : Invalid product version '2023.7.4'.

### ISSUE THREAD

**Issue by wildone** [electron-userland/electron-builder#7644]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  v16.17.0

* **Electron Version**: 24.2.0
* **Electron Type (current, beta, nightly)**:  current

* **Target**:  squirrel with `MSI=true`

Currently, I am using the following versioning `YYYY.m.d` in the package.json.

When I backage the electron I get the following error:

```
dist_electron\squirrel-windows\Setup.wxs(2) : error CNDL0242 : Invalid product version '2023.7.4'. Product version must have a major version less than 256, a minor version less than 256, and a build version less than 65536.
```

This is cleary MSI issue, is there a workaround to specify just MSI version during squirrel build?

For now looks like I have to build MSI individually with different version.

**Comment by mmaietta** [comment]
Is that a limitation of MSI? That error code is not coming from electron-builder code.
