### ISSUE TITLE
files field do not work consistently with a single element in the list, fails with "app.asar" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by ozgeneral** [electron-userland/electron-builder#7647]
I'm having a similar issue to https://github.com/electron-userland/electron-builder/issues/2693
(version=24.4.0 os=22.4.0)

here is my setup (on purpose this setup to simplify my trial/error loop):

```
build
├── desktop
│   └── package.json
└── app.js
└── test.html
```

below fails:
```
    "extraMetadata": {
      "main": "app.js"
    },
    "files": [
      {
        "from": "/path/to/build",
        "to": "."
      }
    ],
```
with:
```
  ⨯ Application "package.json" in the "/path/to/build/desktop/dist/mac/MyApp.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build 
```

and below succeeds (running from "/path/to/build/desktop"):
```
    "extraMetadata": {
      "main": "app.js"
    },
    "files": [
      "*",
      {
        "from": "/path/to/build",
        "to": "."
      }
    ],
```
note that removing {from:..., to:...} also fails, so I know it's not about * fixing things alone. 

if this was intended, the docs is extremely misleading. 
if it's not intended, I guess path handling in files might have a bug

**Comment by mmaietta** [comment]
`package.json` needs to be at the root level with `main: app.js`, which is why the 2nd route running from `/build/desktop` works.

**Comment by ozgeneral** [comment]
Thanks a lot for replying. I have few concerns and a clarification. 

Concerns:
 - [if intentional] I think electron-builder should allow arbitrary project setup, for example I would like to keep my_project/desktop folder that keeps all electron related complexity isolated from the rest of the project, and I would like to be able to pass a path containing node_modules and package.json instead of having to refactor the whole project for using electron-builder
 - [if intentional] Anything around this behavior is completely undocumented

Clarification:
build works when files list has 2 elements, and doesn't work when it has only single item. I would have expected it to work or not work depending on whether `{"from": "/path/to/build", "to": "." }` is in the list or not

**Comment by mmaietta** [comment]
Sounds like you're looking to have a 2 package.json setup then where all your electron complexity is within a subdirectory
https://www.electron.build/tutorials/two-package-structure
