### ISSUE TITLE
Code sign NSIS setup file

### ISSUE THREAD

**Issue by JiaHenry** [electron-userland/electron-builder#765]
* **Version**: 5.34.1

* **Target**: Windows

Sorry that I didn't find where can I ask a question, so just create an issue.

I want to know whether can I code sign the NSIS setup file just like squirrel. If it's possible, how to make it works (for example, add option config, add script or ...)

Thanks in advance.

**Comment by JiaHenry** [comment]
Sorry that I made a mistake: not set environment variable for code signing :(

It works after provide information for code signing. One point should be pay attention is, just like MSI, you can't do  dual code signing (sha1 & sha256), set one of them in build.win.signingHashAlgorithms is fine.

**Comment by develar** [comment]
> you can't do dual code signing (sha1 & sha256)

You can and should use dual code signing for exe. Or do you use Windows 7?

**Comment by JiaHenry** [comment]
No, I'm using Windows 8.1.
I tested that the dual code signing for exe is just fine, but when create with MSI or NSIS setup, it will failed.
