### ISSUE TITLE
Linux deep link doesn't work from browser

### ISSUE THREAD

**Issue by Tuditi** [electron-userland/electron-builder#7654]
* **Electron-Builder Version**: Tested 24.0.0 & 23.6.0

* **Node Version**:  18.16.0

* **Electron Version**:* **Electron Type (current, beta, nightly)**: 22.3.13

* **Target**: 

Hello there! I cannot to open a deep link when built with electron-builder (not sure if this is an electron-builder issue) **from the browser address bar**. Running it with the `xdg-open bloom-alpha://test` opens the application however. I think I'm missing something. Below you can find the `.desktop` file:

```
[Desktop Entry]
Name=Bloom - Alpha
Exec=/home/tuditi/Applications/bloom-desktop-0.1.0_d112b668a101e7fae23ad6330e7ec0fc.AppImage --no-sandbox %U
Terminal=false
Type=Application
Icon=appimagekit_595e114c17762a08626a369298dc5e85_desktop
StartupWMClass=Bloom - Alpha
X-AppImage-Version=0.1.0
Comment=Simple and secure web3 wallet for the IOTA and Shimmer ecosystem
Categories=Office;Finance;
MimeType=x-scheme-handler/bloom-alpha;
TryExec=/home/tuditi/Applications/bloom-desktop-0.1.0_d112b668a101e7fae23ad6330e7ec0fc.AppImage
X-AppImage-Old-Icon=desktop
X-AppImage-Identifier=595e114c17762a08626a369298dc5e85
Actions=Remove;
X-AppImageLauncher-Version=2.2.0 (git commit 0f91801), built on 2022-11-02 23:51:55 UTC

[Desktop Action Remove]
Name=Remove AppImage from system
Icon=AppImageLauncher
Exec=/usr/lib/x86_64-linux-gnu/appimagelauncher/remove "/home/tuditi/Applications/bloom-desktop-0.1.0_d112b668a101e7fae23ad6330e7ec0fc.AppImage"
```

Everything seems to work and other applications (e.g.: ledgerlive) open just fine. I'll also link the main.js file:

https://github.com/iotaledger/firefly/blob/develop/packages/desktop/electron/main.js

Any help much appreciated!

**Comment by Thesiva7** [comment]
@Tuditi how you added desktop action. can you explain how to add desktop actions with electron builder using package.json build
