### ISSUE TITLE
why is there a detection of an empty application?

### ISSUE THREAD

**Issue by sandersbasket** [electron-userland/electron-builder#7656]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  19.1.0

* **Electron Version**: 22.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  just example

I created a completely empty application on electron, compiled using electron-builder with the command -npx electron-builder build --win portable, but when downloading the file to VirusTotal I found a number of detections, why?
![image](https://github.com/electron-userland/electron-builder/assets/101429671/aee35091-36fa-4dc7-a68d-40a89684f5ed)
![image](https://github.com/electron-userland/electron-builder/assets/101429671/7f6ac028-5542-4273-92da-14a61fac5f84)

**Comment by mmaietta** [comment]
Can you please try latest electron-builder?

Also, are you bundling the app cross-platform? i.e. windows portable via mac build machine.

**Comment by sandersbasket** [comment]
> Can you please try latest electron-builder?
> 
> Also, are you bundling the app cross-platform? i.e. windows portable via mac build machine.


what command do I need to use to create a one-file build for windows?
the first screenshot is the compilation method used on the latest version of electron-builder
