### ISSUE TITLE
Can electron-autoupdater  detect automatically at intervals？

### ISSUE THREAD

**Issue by thomas-void0** [electron-userland/electron-builder#7658]
* **Electron-Builder Version**: 

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: Can electron-autoupdater  detect automatically at intervals？

I found electron of autoupdater can intervals check. can electron-autoupdater do it? such as :

<img width="1476" alt="image" src="https://github.com/electron-userland/electron-builder/assets/48620706/3979429f-1aaa-48b4-aba7-827604388c4b">

**Comment by mmaietta** [comment]
Can you use NodeJS' internal `setInterval` with `autoUpdater.checkForUpdates()` with your own time duration?

**Comment by thomas-void0** [comment]
> Can you use NodeJS' internal `setInterval` with `autoUpdater.checkForUpdates()` with your own time duration?

yes i can, That's what I'm doing now. thx bro
