### ISSUE TITLE
electron version and electron-builder version compatibility relationship?

### ISSUE THREAD

**Issue by grafanauser** [electron-userland/electron-builder#7660]
because the readme.md “I have a question | Join the discussions" link ends in 404 i ask here:

Is there a compatibility relationship between the electron version and the electron-builder version? e.g. do i have to use electron-builder 25.x.x when i use electron 25.x.x? Or does electron-builder 24.x.x works with electron 25.x.x as well?

**Comment by mmaietta** [comment]
Great question!
No, there's no direct relationship between electron versions and electron-builder. 🙂
