### ISSUE TITLE
How to autoInstallOnAppQuit only if the downloaded version is not a major-version upgrade?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#7661]
* **Electron-Builder Version**: `23.x.x`

* **Node Version**: `18.x.x`

* **Electron Version**: `25.x.x`
* **Electron Type (current, beta, nightly)**: `current`
* **Electron-Updater Version:** `5.x`

Is there some way we can keep the default `autoInstallOnAppQuit` for minor/patch level version changes but bail out if the new version is a major version upgrade? eg `3.1.0` can auto-install to `3.1.1` or `3.2.0` but not to `4.0.0`

Is this possible with the current API? Am I overlooking some way to do it?

I see we could handle the download manually and manually invoke `autoUpdater.quitAndInstall()` but that's not quite the same as auto-updating when the user closes the app themselves.

**Edit:** I guess this could be done by intercepting the normal quit event and using `autoUpdater.quitAndInstall()`, but that means our auto-update logic needs to start mixing with unrelated logic which I'd really love to avoid if at all possible. **Is there any way to change the `autoInstallOnAppQuit` setting on the fly?** eg once we realize the update is for a version we don't want to allow auto-update to?

**Comment by mmaietta** [comment]
> Is there any way to change the autoInstallOnAppQuit setting on the fly?

I'm not too familiar with the updater flow tbh. Is it possible to do `checkForUpdates()` and tap into the listener for `update-available`, then do your version-check logic in the listener and set the `autoUpdater.autoInstallOnAppQuit = false` appropriately?
