### ISSUE TITLE
Enhancement, Windows: Scoop Installer Support

### ISSUE THREAD

**Issue by c3er** [electron-userland/electron-builder#7662]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 18.16.0

* **Electron Version**: 25.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

A direct support for [Scoop](https://scoop.sh/#/) as Windows target would be very nice.

**Comment by mmaietta** [comment]
Happy to review a PR for this addition! As it currently stands, adding additional targets is not in my workflow.
