### ISSUE TITLE
FEAT: Add support for required 'FileSet' files under `extraResources`

### ISSUE THREAD

**Issue by Nokel81** [electron-userland/electron-builder#7663]
* **Electron-Builder Version**: 
23.6.0

* **Node Version**: 
16.19.0

* **Electron Version**: 22.3.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: all

It would be great if the 'FileSet' type used by `extraResources` and `extraFiles` could have an optional field `required: boolean` field (default `false`) which when set to `true` would cause the electron-builder invocation to fail with an error.

**Comment by mmaietta** [comment]
This sounds like a great idea, however, I've been trying to figure out how to modify the `appFileCopier` and related `ResolvedFileSet` logic for over a year with no success. 😞  Happy to review a PR if you're willing to give it a shot!
I'll investigate as well but can't guarantee any timeline for doing so (work is crazy as of late)

**Comment by Nokel81** [comment]
Yes still interested

**Comment by Nokel81** [comment]
Still interested

**Comment by Nokel81** [comment]
Not stale

**Comment by mmaietta** [comment]
Happy to review a PR if you're willing to give it a shot!
