### ISSUE TITLE
Docker image for electron 25 with node 18.15.0

### ISSUE THREAD

**Issue by grafanauser** [electron-userland/electron-builder#7667]
request:
- new electron-builder docker image for electron 25 with node 18.15.0 (includes npm 9.5.0 automatically).

Background:
- for the old electron 23 (node 18.12.1, npm 8.19.2) this docker image worked great (thanks again):
https://hub.docker.com/layers/electronuserland/builder/18-wine-03.23/images/sha256-de2edd04a74711c0a730f6682ea248e56a5c47a0639c5376f4531e9e855eb3b7?context=explore
  - related: https://github.com/electron-userland/electron-builder/issues/7430
- but for the new electron 25 (node 18.15.0, npm 9.5.0) the major update in npm introduces breaking changes, which in our case broke our build pipelines.

**Comment by mmaietta** [comment]
Wait, why do you need 18.15.0 exactly? I thought semver was just `>= 18.15.0`, so it'd be satisfied by 18.16.1

**Comment by grafanauser** [comment]
> Wait, why do you need 18.15.0 exactly? I thought semver was just `>= 18.15.0`, so it'd be satisfied by 18.16.1

The problem is that a node installation is combined with npm. The Node api itself only got a minor update from 18.12.1 to 18.15.0. 
But the old node 18.12.1 installed npm 8.19.2 while the new node 18.15.0 installed npm 9.5.0. So there is a major change in npm. This major change introduced breaking changes to the auth settings used by npm.

**Comment by mmaietta** [comment]
Not sure I can do anything there?
This is the command being run to install Node in the docker image
https://hub.docker.com/layers/electronuserland/builder/latest/images/sha256-0011b9cd930a60061a5b7fb152611d4236a530a1a3b0bdfd6e9d417e26e50e2e?context=explore
```
NODE_VERSION=18.16.1 /bin/sh -c curl -L https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz | tar xz -C /usr/local --strip-components=1 &&   unlink /usr/local/CHANGELOG.md && unlink /usr/local/LICENSE && unlink /usr/local/README.md &&   echo "unsafe-perm true" > .npmrc
```

**Comment by grafanauser** [comment]
that would be nice. to 18.15.0 instead of 18.16.1

**Comment by mmaietta** [comment]
Please try latest docker image, it downgraded node version to 18.15.0

**Comment by grafanauser** [comment]
It still causes the auth error. I think the docker image is still 18.16.0. I think you have to change the "ARG NODE_VERSION 18.16.0" to 18.15.0, too, or?


https://hub.docker.com/layers/electronuserland/builder/18-wine-07.23/images/sha256-2fb178a8f43a50a73e7754045b4a274f2810acabb4957c1467301540618a70eb?context=explore

**Comment by mmaietta** [comment]
That's not how ARGs work. It's passed in via the build.sh script. You can tell because of the next step that has the correct node version set.
```
NODE_VERSION=18.15.0 /bin/sh -c curl -L https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz | tar xz -C /usr/local --strip-components=1 &&   unlink /usr/local/CHANGELOG.md && unlink /usr/local/LICENSE && unlink /usr/local/README.md &&   echo "unsafe-perm true" > .npmrc
```

Running locally:
```
> docker pull electronuserland/builder:18
....
> docker run --rm -it electronuserland/builder:18
root@87c126bb869c:/project# npm -v
9.5.0
root@87c126bb869c:/project# node -v
v18.15.0
```
Looks like you need a different node version

**Comment by grafanauser** [comment]
that is really strange. 

The first build pipeline is using "FROM node:18.15.0". After updating the auth for npm 9, it worked again.  auth is requiring the registry as namespace now.
https://hub.docker.com/layers/library/node/18.15.0/images/sha256-634dfe323bf6033880d41c9ebca6badef038ea10279c26d814fe414871002566?context=repo&tab=vulnerabilities

The second build pipeline for electron-builder is using "FROM electronuserland/builder:18-wine-07.23" still fails with the new auth settings for npm 9.

both use the same settings and do the same thing until the fail happens. They are different in later steps but they dont matter in case of this error.
