### ISSUE TITLE
NSIS setup allowElevation(true) can't open app after install auto

### ISSUE THREAD

**Issue by JiaHenry** [electron-userland/electron-builder#767]
- **Version**: 7.4.0

- **Target**: Windows (build on Windows 8.1 64Bit)

I'm trying create a windows setup (NSIS) file for my app since the default squirrel is a little different from normal setup and user experience is not good (I'm not sure if it's related with no squirrel events handle in my app's main.js).

After change build options and I'm happy to create a NSIS setup (boring installer).

But when I run the setup and  select for all users -> install with allow elevation and confirm -> jump to complete page directly.

The related problems are:
1.  Here seems missing the install progress related items;
2. If you press the 'Finish' at the complete page  when it appears, the setup will failed (such as file not fully unzipped, not shortcut created etc. Which depends on how long you wait the setup and press the Finish button';
3. If I wait a little a while and make sure the shortcut on desktop was created, then press the Finish button
((with default 'Run ***' chcked)), the app won't auto open.

If I run the setup by right click and select 'Run as administrator', it works fine for all users just like for myself.

Related items in package.json FYI:

"scripts" : { "dist-w": "build -w --x64" },
"build" : {
    "appId": "*******_",
    "app-category-type": "public.app-category.productivity",
    "win": {
      "target": ["nsis"],
      "signingHashAlgorithms": [
        "sha256"
      ],
      ***_*
    },
    "nsis": {
      "oneClick": false
    }
}

**Comment by saghul** [comment]
Bump. I'm running into the same problem, any idea of what could be the problem? Thanks!

**Comment by PauloLira** [comment]
same here, this is the relevant part of my package.json 


 "win": {
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false,
      "warningsAsErrors" : true,
      "allowElevation": false
    },

**Comment by igorcandeia** [comment]
Same here.
