### ISSUE TITLE
Webcam not working in windows (getUserMedia - Uncaught DOMException: Could not start video source)

### ISSUE THREAD

**Issue by russianxiii** [electron-userland/electron-builder#7676]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: v20.4.0

* **Electron Version**: 23.3.10
* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis

Hello, the webcam does not work in the version for Windows, which is built through nsis.
Although it works on macOS.

![image](https://github.com/electron-userland/electron-builder/assets/38250817/edefb59e-fc92-4b98-9dbf-286b776256fd)

But audio work and screen sharing work too.

Tell me what can be done about it?

**Comment by mmaietta** [comment]
Idk why electron is not letting you access `getUserMedia`, but I can confirm this is not due to electron-builder.
