### ISSUE TITLE
'tool: "notarytool"' won't work

### ISSUE THREAD

**Issue by sprout2000** [electron-userland/electron-builder#7677]
* **Electron-Builder Version**: 24.6.1
* **@electron/notarize Version**: 2.1.0
* **@electron/osx-sign Version**: 1.0.4

* **Node Version**: 18.16.1

* **Electron Version**: 25.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

Legacy altool mode is used even if 'tool: "notarytool"' is specified in the notarize script.

```typescript
const notarizer = async (context: AfterPackContext) => {
  const { appOutDir } = context;
  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    tool: "notarytool",
    appPath: `${appOutDir}/${appName}.app`,
    teamId: `${process.env.TEAM_ID}`,
    appleId: `${process.env.APPLE_ID}`,
    appleIdPassword: `${process.env.APPLE_APP_SPECIFIC_PASSWORD}`,
  });
};
```

Output to the console is as follows:

```sh
Notarizing using the legacy altool system. The altool system will be disabled on November 1 2023. Please switch to the notarytool system before then.
You can do this by setting "tool: notarytool" in your "@electron/notarize" options. Please note that the credentials options may be slightly different between tools.
```

**Comment by mmaietta** [comment]
Yeahhh, that's not related to electron-builder. You're using the @electron/notarize package directly via our AfterPack hook.

**Comment by duereg** [comment]
https://github.com/electron-userland/electron-builder/issues/7683#issuecomment-1724537409

**Comment by XanderEmu** [comment]
My not-perfect-but-working solution was to disable notarization in builder configuration completely, then setting up notarization script in `afterSign`.
