### ISSUE TITLE
Parameters to ExecWait are grouped together in the wrong way

### ISSUE THREAD

**Issue by galassimarco** [electron-userland/electron-builder#7681]
I'm experiencing some weird behavior when running a .exe with certain parameters during installation of my software built with electron-builder.
My `electron-builder.config.json` includes a `.nsh` script that performs an ExecWait as follows:

`ExecWait '"$PLUGINSDIR\LsInit.exe" 1AAAAAA-BB1B-CCC1-11BB-0FF9A305326C appname 1.0.0'`

We checked the logs of the LsInit.exe and noticed that it receives `appname` and `1.0.0` together, causing issues.
De facto, LsInit.exe receives 2 parameters instead of 3, them being:
param1: `1AAAAAA-BB1B-CCC1-11BB-0FF9A305326C`
param2: `appname 1.0.0`

Adding quotes around each parameter does not change the situation.

It looks, instead, that inserting a tab instead of a single space as a parameter separator does solve the issue:

`ExecWait '"$PLUGINSDIR\LsInit.exe" 1AAAAAA-BB1B-CCC1-11BB-0FF9A305326C appname 1.0.0'` <-- \t between as whitespaces between parameters.

Doing this, LsInit.exe correctly receives 3 parameters, which is what we need:
param1: `1AAAAAA-BB1B-CCC1-11BB-0FF9A305326C`
param2: `appname`
param3: `1.0.0`

**Comment by mmaietta** [comment]
Would you be willing to open a PR with the change and include your debugging details with it?

**Comment by galassimarco** [comment]
I can try, do you think you can guide me into where to look at?

**Comment by mmaietta** [comment]
I'm actually not sure what in electron-builder is supposed to be fixed as you mention this:
>My electron-builder.config.json includes a .nsh script that performs an ExecWait as follows:

If it's your .nsh script, is there something electron-builder supposed to do?
