### ISSUE TITLE
macOS: bug in the multi-architecture target specification

### ISSUE THREAD

**Issue by sprout2000** [electron-userland/electron-builder#7683]
* **Electron-Builder Version**: 24.6.2

* **Node Version**: 18.17.0

* **Electron Version**: 25.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS arm64 and x64

When multiple architectures are specified in target, electron-notarize's notarytool mode is not enabled.
It seems like a bug in builder.

Please see @electron/notarize's issues: [#148](https://github.com/electron/notarize/issues/148#issuecomment-1646493431) and [#150](https://github.com/electron/notarize/issues/150).

```javascript
require("electron-builder").build({
  config: {
    mac: {
      target: [
        {
          target: "default",
          arch: ["x64", "arm64"],
        },
      ],
    },
    afterSign: "notarizer.js",
  },
});
```

```javascript
const { notarize } = require("@electron/notarize");

const notarizer = async (context) => {
  const { appOutDir } = context;
  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    tool: "notarytool",
    appPath: ...,
    teamId: ...,
    appleId: ...,
    appleIdPassword: ...,
  });
};

module.exports = notarizer;
```

**Comment by mmaietta** [comment]
Can you try the direct notarize integration within electron-builder?
https://www.electron.build/configuration/mac
```
`notarize` module:app-builder-lib/out/options/macOptions.NotarizeOptions | Boolean | “undefined” - Options to use for @electron/notarize (ref: https://github.com/electron/notarize). Supports both legacy and notarytool notarization tools. Use false to explicitly disable

Note: You MUST specify APPLE_ID and APPLE_APP_SPECIFIC_PASSWORD via environment variables to activate notarization step
```

**Comment by sprout2000** [comment]
I am very sorry for the delay in responding to you.
Finally everything just worked!!!
Thank you so so much.

```typescript
import dotenv from "dotenv";
import { build } from "electron-builder";

dotenv.config();

build({
  config: {
    productName: "Sample",
    artifactName: "${productName}-${version}-${platform}-${arch}.${ext}",
    mac: {
      appId: "jp.wassabie64.Sample",
      category: "public.app-category.developer-tools",
      target: [
        {
          target: "default",
          arch: ["arm64", "x64"],
        },
      ],
      notarize: {
        appBundleId: "jp.wassabie64.Sample",
        teamId: "**********",
      },
    },
  },
});
```

**Comment by raul-guerrero** [comment]
How come this bug is closed if it's still happening? on package.json notarizing using notarytool doesn't work and altool's EOL date. keeps getting closer.
Is there a way to contribiute to fixing this?

**Comment by mmaietta** [comment]
Wait, so what's the bug? Using the `afterSign` hook? Or using the direct integration of electron/notarize package via `notarize` configuration option?

To contribute, it's easy to set up a dev environment
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by raul-guerrero** [comment]
@mmaietta direct integration of electron/notarize package via notarize configuration option doesn't work if setting tool as notarytool, it always ends up using altool, once we reach Nov. 1st. this will be broken entirely, as altool won't be able to upload files to notarize on Apple's servers.

**Comment by brondibur** [comment]
@mmaietta Any updates on this?

**Comment by duereg** [comment]
Looking at the [notary code](https://github.com/electron/notarize/blob/main/src/types.ts), it appears that if you include legacy fields in the configuration (such as`appBundleId`), it will effectively force you into legacy mode (even if you include valid non-legacy fields in your install).

**Comment by duereg** [comment]
It looks like these are the only fields you can include that won't trigger `legacy` mode:

**Comment by duereg** [comment]
Ok, I've got a working solution, but it took me reading the source for both this project and `@electron\notarize` to figure it out. 

Set these two environment variables on your build environment, as shown used [here](https://github.com/electron-userland/electron-builder/blob/562870e92dea50b2d20e4fd8519ac8f5293b6336/packages/app-builder-lib/src/macPackager.ts#L481):
```
    APPLE_ID
    APPLE_APP_SPECIFIC_PASSWORD
```

Then, in your config file, set ONLY the `teamId` field and nothing else:

```
"build": {
    ...
    "mac": {
      ...
      "notarize": {
        "teamId": "YOUR_TEAM_ID_HERE"
      }
    }
```

If you set additional fields (such as `appBundleId`) the notarize tool will automatically convert you to using the legacy signing tool (even if `teamId` is present).

**Comment by mmaietta** [comment]
Nice work @duereg!
Maybe I can split the notarize configuration object to be 2 separate interfaces, if so, it'll allow you to only set `teamId` when using the new notary tool. That way we don't end up in this weird state. Thoughts?
