### ISSUE TITLE
Error: ⨯ cannot execute  cause=exit status 1 errorOut=Fatal error: Unable to commit changes

### ISSUE THREAD

**Issue by Super12138** [electron-userland/electron-builder#7689]
* **Electron-Builder Version**: 24.6.3

* **Node Version**: v18.14.2

* **Electron Version**: v25.3.1
* **Electron Type (current, beta, nightly)**: current
(I don't use `electron-updater`)

* **Target**: Windows

Today I package my app, it showed the error below (Packing is contiune)
```
  ⨯ cannot execute  cause=exit status 1
                    errorOut=Fatal error: Unable to commit changes

                    command='C:\Users\UserName\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\rcedit-x64.exe' 'C:\Users\UserName\Desktop\ProjectName\dist\dist\win-arm64-unpacked\AppName.exe' --set-version-string FileDescription 'AppName' --set-version-string ProductName 'AppName' --set-version-string LegalCopyright 'Copyright' --set-file-version 1.0.8 --set-product-version 1.0.8.0 --set-version-string InternalName 'AppName' --set-version-string OriginalFilename '' --set-version-string CompanyName CompanyName --set-icon 'C:\Users\UserName\Desktop\ProjectName\dist\build\AppIcon.ico'
                    workingDir=
  • Above command failed, retrying 3 more times
```
And I tried so many time, it always showed this error. So, I checked the issues (#4657), and didn't found the solution.

**Comment by mmaietta** [comment]
Did this issue just recently start? I'm not too sure how `rcedit` works, but I'll need a minimum reproducible repo to work with to debug deeper.

**Comment by Super12138** [comment]
> Did this issue just recently start? I'm not too sure how `rcedit` works, but I'll need a minimum reproducible repo to work with to debug deeper.

No, it start at about 1 month ago. At that time, every time I try the second time, it didn't give me an error.
If you want to debug more deeper, you can see my repository [Hash-Checker](https://github.com/Super12138/Hash-Checker). You can run `npm run build` first, and go to the `dist` folder, run `npm install` and `npm run build` second.

**Comment by Super12138** [comment]
> Did this issue just recently start? I'm not too sure how `rcedit` works, but I'll need a minimum reproducible repo to work with to debug deeper.

I also try use the error command(command='C:\Users\UserName\AppData\Local\electron-builder\Cache\winCodeSign...), it show error:
```
Unable to load file: "'C:\Users\UserName\Desktop\GitHub\Hash-Checker\dist\dist\win-unpacked\Hash"
```
Maybe it's because there are spaces in the application name.

**Comment by angelhdzmultimedia** [comment]
Having this issue.

I made a Quasar Electron app on march 2023. It was working great in Windows 10 and now Windows 11.
Today I wanted to just update the app's icon, and got this error. I submitted the issue to Quasar, thinking it was something related to Quasar, but then I made a Nuxt 3 app using electron-builder and got this same error.

Tried different versions of electron and electron-builder Node packages, and same thing.

**Comment by angelhdzmultimedia** [comment]
### Solved
Deleted this directory `C:\Users\AngelHdz\AppData\Local\electron-builder`. Executed `quasar build -m electron` (which executes electron-builder). All executable dependencies were finally downloaded and installed in `C:\Users\AngelHdz\AppData\Local\electron-builder\Cache` like `C:\Users\AngelHdz\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\rcedit-x64.exe` and `C:\Users\AngelHdz\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\makensis.exe`. Finally it built the Packaged and Unpackaged files, and I ran the installer and it was installed on Windows 11. Hope this helps someone.
