### ISSUE TITLE
Roaming folder deleted?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#769]
* **Version**: latest

* **Target**: NSIS

Why is the roaming folder deleted during install? (AppData/Roaming/App Name/) and how can I prevent this? This contains files that should never be deleted on install / upgrade.

**Comment by develar** [comment]
We do not remove app data on auto uninstall (as part of installing new version), but we remove on uninstall.

**Comment by bontibon** [comment]
> Please specify do you mean that app data must be not removed on uninstall (Add or Remove Programms -> Uninstall)?

Correct. This should not happen without explicit user consent.

**Comment by atypicalprogrammer** [comment]
Well, for me data is removed on auto uninstall as part of installing new version. So I don't know why that is. It happens during the NSIS installation phase.
