### ISSUE TITLE
electron-builder does not bundle the dependencies correctly in the build

### ISSUE THREAD

**Issue by nikitavoloboev** [electron-userland/electron-builder#7702]
* **Electron-Builder Version**: 24.4.0

* **Node Version**:  18.15.0

Trying to do build of app here:

https://github.com/learn-anything/electron-version

If git clone and `cd app` and `pnpm run compile` which runs:

`electron-builder build --config .electron-builder.config.js --dir --config.asar=false`

[.electron-builder.config.js](https://github.com/learn-anything/electron-version/blob/main/app/.electron-builder.config.js#L11) is config file.

<img width="1469" alt="image" src="https://github.com/electron-userland/electron-builder/assets/6391776/905ac7d1-2fe5-464d-8c4e-e9f3f85b4f29">

It compiles

But when I try open the app from dist I see this:

<img width="461" alt="image" src="https://github.com/electron-userland/electron-builder/assets/6391776/10dca694-c61e-4060-9a05-ab2a5ccc1e67">

I am not sure why but it seems that electron-builder is not bundling the node dependencies correctly for the build?

Thank you lots for any help.

**Comment by nikitavoloboev** [comment]
From my investigations I found this issue:

https://github.com/TryGhost/node-sqlite3/issues/909

Which had this comment

<img width="1060" alt="image" src="https://github.com/electron-userland/electron-builder/assets/6391776/d102816e-bc58-4e9f-89ab-125fbb9d225b">

trying to add https://github.com/electron/rebuild now

hopefully that fixes it

**Comment by nikitavoloboev** [comment]
It's unclear how to actually integrate rebuild package into the process. Like at which point does rebuild get used.

**Comment by nikitavoloboev** [comment]
Opened issue in rebuild project too: https://github.com/electron/rebuild/issues/1094

**Comment by AiHaibara** [comment]
for electron-builder 25 or 25.0.4
when i using pnpm and
`shamefully-hoist=true` in npmrc
sometimes the builded exe, it will show the error` cannot find module 'jsonfile/utils'...`
but using `node-linker=hoisted` in npmrc is ok
and in 24.13.3 `shamefully-hoist=true` is working.

**Comment by hifron** [comment]
I would expect something like post:install script, plugin or addon to build process. Maybe in pnpm or electron which not copy but maybe some additional work if required and not fully expose all the shit.
