### ISSUE TITLE
AsarUnpack issue <xxx must be under building dir>

### ISSUE THREAD

**Issue by weiyuanbj** [electron-userland/electron-builder#7716]
* **Electron-Builder Version**: 
latest

* **Node Version**: 
16.18

* **Electron Version**: 11.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: 
mac

https://github.com/electron-userland/electron-builder/issues/7264

Same issue, when i set up asarUnpack value, and electron builder will check if all files are under the root dir of my project even if i move files into it in files option. But when not set up it, electron builder will not check that. Maybe there is a issue of execution sequence of files and asarUnpack options
![image](https://github.com/electron-userland/electron-builder/assets/141129889/1f78b187-a885-4a19-b939-6cd5336ef3dc)

**Comment by GeorgeBarlow** [comment]
I also am facing this issue, does anyone have ideas on a solution or what could be causing this?
