### ISSUE TITLE
Must be error if file association is set, but perMachine not

### ISSUE THREAD

**Issue by virror** [electron-userland/electron-builder#772]
- **Version**: 7.3.0

- **Target**: win32

After updating to latest electron-builder, file association including icon stopped working. Worked perfectly before updating, i think last version was the last 6.x, but cant remember exactly.
Using NSIS
"fileAssociations": {
      "ext": ".aepwx",
      "name": "myName",
      "icon": "build/icon.ico"
    }

**Comment by develar** [comment]
Works for me. Nothing changed. Please provide sample project or set debug env `DEBUG=electron-builder` and attach logs.

> "icon": "build/icon.ico"

Do not specify app icon — it is default value in any case.

**Comment by virror** [comment]
Sadly i cant send you the project, but im willing to help in other ways. We have tested on several machines now and non of them works. How do you set the debug variable?

**Comment by develar** [comment]
> We have tested on several machines now and non of them works

Please try to not set icon at all. Since it is equal to app icon, no need to set it explicitly.

> How do you set the debug variable?

It is an environment variable. Set `DEBUG=electron-builder`

**Comment by develar** [comment]
> non of them works.

No icon? Could you please attach screenshot of file in the File Explorer?

**Comment by virror** [comment]
Yes, app does not open on double click and icon is just a white standard "no specific icon" icon.
When i check properties of the file it says that no program is associated to this file type.
I will try with the debug mode and see if i can get some data.
Were do the log file end up?

**Comment by develar** [comment]
Do you use `perMachine: true`?

**Comment by virror** [comment]
No.
"nsis": {
      "oneClick": true,
      "perMachine": false,
      "installerHeaderIcon": "build/icon.ico"
    },

**Comment by develar** [comment]
Because Windows is *** Windows, per-user installed program cannot register file associations.

Yes — it is not documented. Yes — we must throw error if file associations set, but `perMachine` (or boring installer) not.

**Comment by virror** [comment]
But you just said that "per-user installed program cannot register file associations", doesn't that mean that you should set error if file associations set and perMachine is TRUE? For my case its set to false?

**Comment by develar** [comment]
> doesn't that mean that you should set error if file associations set and perMachine is TRUE?

`perMachine: true` means that app will be installer for all users. Ugly *** UAC in action — user cannot install app only per-user — admin rights is required to install.

> For my case its set to false?

`false` is the default value.

**Comment by virror** [comment]
Ahh, i thought perMachine true was that it should install for one user only, i will try change this then : )

**Comment by virror** [comment]
Ok, now the association works : )
No icon though and the application does not work at all anymore, just a blank white app : p

**Comment by develar** [comment]
> No icon though.

Did you remove unnecessary `"icon": "build/icon.ico"`?

**Comment by virror** [comment]
No, but i think its just some cache issue, cause when i try to open a file inside of the program, the icon shows. Thanx for the help!

**Comment by jakubzitny** [comment]
I can see that it throws an error now, if I have fileAssociations set to true and perMachine to false. Can we set it for macOS only, so it does not fail when perMachine is false, but we still want it on Mac?

**Comment by develar** [comment]
@jakubzitny Just move `fileAssociations` to `mac` to apply it only for macOS.

**Comment by jakubzitny** [comment]
Thanks, it works.
