### ISSUE TITLE
 Error: sha512 checksum mismatch

### ISSUE THREAD

**Issue by raghavnaphade** [electron-userland/electron-builder#7724]
Electron-Builder Version ^23.6.0
Node Version v18.16.0
Electron Version: 24.4.1
electron-updater: ^5.3.0
Target: nsis

I am using auto updater and application gets downloaded from server in Appdata but after 100% download it is giving this error

** Error: sha512 checksum mismatch, expected  ** 

```
 "build": {
    "appId": "com.itp",
    "productName": "itp",
    "artifactName": "itp-${version}.${ext}",
    "files": [
      "dist/**/*",
      "node_modules/**/*",
      "app-update.yml"
    ],
    "directories": {
      "output": "dist"
    },
    "win": {
      "target": "nsis",
      "artifactName": "itp-${version}.${ext}",
      "icon": "icons/ITP_Logo_192X192.ico",
      "publish": [
        {
          "provider": "generic",
          "url": "https://example.blob.core.windows.net/electron/WinMicoApp/"
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    }
  },
```

Can someone please help me to solve this issue

**Comment by Taha-daboussi** [comment]
Make sure that the signing of the application happened in the same appid/productName this might create this error

**Comment by Sdqumar** [comment]
also have this error when ever I code sign the app. I code sign the app, after building the app. any suggestions on how to solve this. Thanks

**Comment by raghavnaphade** [comment]
I have resolved this issue
Please follow this link
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by raghavnaphade** [comment]
I have resolved this issue
Please follow this link
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by alminQSD** [comment]
> I have resolved this issue Please follow this link https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

Hi. What exactly did you do to resolve the issue?

**Comment by akshay-aravind** [comment]
I am facing the same issue, if anyone found something please update.

**Comment by Sdqumar** [comment]
I have this code that kinda did the trick for me, I still get checksum mismatch but the update works

`const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const yaml = require("js-yaml");
const content = fs.readFileSync("./release/app/package.json");
const parsedContent = JSON.parse(content);
const win_file = `./release/build/chronly-Setup-${parsedContent["version"]}.exe`;
const yml_file = "./release/build/latest.yml";

function hashFile(file, algorithm = "sha512", encoding = "base64", options) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash(algorithm);
    hash.on("error", reject).setEncoding(encoding);
    fs.createReadStream(
      file,
      Object.assign({}, options, {
        highWaterMark: 1024 * 1024,
        /* better to use more memory but hash faster */
      }),
    )
      .on("error", reject)
      .on("end", () => {
        hash.end();
        console.log("hash done");
        updateSHA512Value(yml_file, hash.read());
        resolve(hash.read());
      })
      .pipe(hash, {
        end: false,
      });
  });
}

const installerPath = path.resolve(__dirname, win_file);

hashFile(installerPath);

function updateSHA512Value(filePath, newSHA512Value) {
  console.log({ newSHA512Value, filePath });

  try {
    // Read the YAML file
    const fileContent = fs.readFileSync(filePath, "utf8");

    // Parse YAML into an object
    const data = yaml.load(fileContent, { schema: yaml.JSON_SCHEMA });

    // Update the sha512 field with the new value for all entries in 'files'
    if (data.files && Array.isArray(data.files) && data.files.length > 0) {
      data.files.forEach((file) => {
        if (file.sha512) {
          file.sha512 = newSHA512Value !== null ? newSHA512Value : null;
        }
      });
    }

    // Update the sha512 field at the root level
    if (data.sha512) {
      data.sha512 = newSHA512Value !== null ? newSHA512Value : null;
    }

    // Convert the updated object back to YAML
    const updatedContent = yaml.dump(data, {
      noCompatMode: true,
      lineWidth: 500,
    });

    const finalContent = updatedContent.replace(/: ~(\s|$)/g, ": null$1");
    fs.writeFileSync(filePath, finalContent);
    console.log("SHA-512 value updated successfully.");
  } catch (error) {
    console.error("Error reading or updating the file:", error);
  }
}
`

**Comment by 20vipul** [comment]
Hi I'm using electron-builder auto update

use this command to build and publish the application on git hub
"publish" : "electron-builder --publish always"

but this does not give me option to  sign the code 
i use ssl eSigner to sign the code

**Comment by scottcorgan** [comment]
Still getting this as well

**Comment by vukadinFE** [comment]
Any solutions for this?

I've signed and notarized the app, but when `electron-updater` detects a new version, it auto-downloads it and then throws the "sha512 checksum mismatch"

**Comment by theIYD** [comment]
I am facing this same issue. Please help with a solution. For me this is happening with Windows.

**Comment by jason-murray** [comment]
I also had this issue but I think I've solved it. In my case it's because my `artifactName` would not be unique between builds.

I had it set like `myapp-setup.exe` so that I could always use the same link to distribute the app. But this seems to break the updater.

Now I have reverted to `artifactName: ${productName}-${version}.${ext}` and the updates are not failing with the sha512 error anymore. I'll just need to find another way to always point to the latest installer.

**Comment by ryanjones** [comment]
```
  - autoUpdater.requestHeaders = {
  -   authorization: `Bearer ${token}`,
  -   accept: "application/vnd.github+json",
  - };
  + autoUpdater.requestHeaders = {
  +   authorization: `token ${token}`,
  + };
```

I had a similar issue with 502 mismatch but mine was failing immediately. I had set an incorrect header on the updater and it caused the same error. Removing the header fixed the mismatch and I could download the file and apply the update.
