### ISSUE TITLE
nsis-web: appPackageUrl not working as intended anymore. Always appends extra 7z versioned filename

### ISSUE THREAD

**Issue by mjwvb** [electron-userland/electron-builder#7732]
* **Electron-Builder Version**: 24.6.3
* **Node Version**: 14.21.3
* **Electron Version**:25.3.1
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater**: 6.1.1
* **Target**: windows (nsis + nsis-web)

Since fix #6964 (v23.3.0) appPackageUrl of the nsis-web target is not working as intended anymore. Before this fix the nsis web installer was downloading the package.7z when we configured appPackageUrl as https://UPDATE_SERVER_URL/package.nsis.7z. Now we get always get this error:

> Unable to download application package from https://UPDATE_SERVER_URL/package.nsis.7z/NAME-0.24.0-x64.nsis.7z (status: File Not Found (404)).
> Please check your internet connection and retry.

This is not behaving according to the docs, as it always appends an extra filename to the package url including the version and arch. There's no way to make the url version independent anymore. The docs describe the intended behavior as follows:

> The application package download URL. Optional — by default computed using publish configuration. URL like `https://example.com/download/latest` **allows web installer to be version independent** (installer will download latest application package). (...) Custom `X-Arch` http header is set to `32` or `64`.

Now we have to downgrade to 23.2.0 (targeting for 24.6.3, coming from 22.x.x) which is very unfortunate. Whatever we try there doesn't seem to be a workaround available for this. It always appends the extra .7z filename.

Looking at the code in #6964, it seems that APP_PACKAGE_URL_IS_INCOMPLETE is now always defined (null thus defined?), and now always append APP_64_NAME and APP_32_NAME to the package name.

This is our trimmed electron-builder config

```json
{
    "publish": [
        {
            "provider": "generic",
            "url": "https://UPDATE_SERVER_URL"
        }
    ],
    "nsisWeb": {
        "artifactName": "XXXSetup.${ext}",
        "appPackageUrl": "https://UPDATE_SERVER_URL/package.nsis.7z"
    }
}
```

**Comment by grovesNL** [comment]
@mjwvb I ran into the same issue, do you know if there's another tracking issue for this?
