### ISSUE TITLE
run electron application with admin privileges on windows can't receive second-instance event

### ISSUE THREAD

**Issue by stefanJi** [electron-userland/electron-builder#7738]
* **Electron-Builder Version**:  23.6.0

* **Node Version**: 14.19.2

* **Electron Version**: 20.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis

```
        nsis: {
            artifactName: `${PackName}.\${ext}`,
            createDesktopShortcut: true,
            createStartMenuShortcut: true,
            menuCategory: true,
            guid: 'aip',
            perMachine: false,
            allowElevation: false,
            runAfterFinish: true,
            oneClick: false,
            allowToChangeInstallationDirectory: false,
            deleteAppDataOnUninstall: true,
            packElevateHelper: true,
            warningsAsErrors: false
        }
```

- Normal run, will receive second-instance event, then we can restore/show exist window.

https://github.com/electron-userland/electron-builder/assets/15273198/46112329-a833-473a-8184-6dd7a5c21803

- When run with admin, can't receive second-instance event, so we can't show exist window.

https://github.com/electron-userland/electron-builder/assets/15273198/2a311272-71c5-452d-9bef-8e1589c9ffde

**Comment by mmaietta** [comment]
This is definitely an electron issue, not specific to electron-builder. electron-builder doesn't have anything to do with the inner workings of electron's second-instance management
