### ISSUE TITLE
nsis installer translate issues

### ISSUE THREAD

**Issue by json-zhou** [electron-userland/electron-builder#7746]
Electron-Builder Version:  23.6.0
Electron Version: 22
Target:  window nsis installer

some message in file “packages/app-builder-lib/templates/nsis
/messages.yml“ do not have zh-CN translation， like：
uninstallFailed:
Failed to decompress files. Please try running the installer again.
解压安装文件失败，请尝试再次执行安装程序。

decompressionFailed:
Failed to uninstall old application files. Please try running the installer again.
无法正确卸载旧的程序文件，请尝试再次执行安装程序。

**Comment by glk-hll** [comment]
I have also encountered the same problem, but it only appears on some `win10` computers, and I don't know why.
