### ISSUE TITLE
Security concerns with the GH_TOKEN

### ISSUE THREAD

**Issue by mleister97** [electron-userland/electron-builder#7747]
I would really like to draw attention to this issue & reopen it again

https://github.com/electron-userland/electron-builder/issues/5688

Currently, it is not possible to use different keys/tokens for publishing and reading private repositories, except by manually modifying the token using the setFeedURL function. For security reasons, I kindly request you to reopen the issue.

**Comment by mleister97** [comment]
For everyone who is interested, this is currently the only way to use 2 different tokens:

```
    autoUpdater.setFeedURL({
      provider: 'github',
      repo: 'xxx',
      owner: 'xxx',
      private: true,
      token: 'read_token',
    });
```

.env
```
GH_TOKEN=publish_token
```

package.json
Do not include any tokens here!

```
"deploy": "ts-node ./.erb/scripts/clean.js dist && npm run build && dotenv -- electron-builder build --publish always",
```

**Comment by NordlingDev** [comment]
@mleister97 I'm concerned about the exposure of token in client side code, even if it's a read only token. You explicitly set the token inside your client basically. Doesn't matter if it's in an env variable or not, the final bundle will still contain the token. So anyone can go through the file and find the token, right?

I can't think of any workaround either... Is there really no other way to do it?
