### ISSUE TITLE
Electron & Mac Capabilities NetworkExtension

### ISSUE THREAD

**Issue by qq815776412** [electron-userland/electron-builder#7748]
When I use in "entitlements.mac.plist" file

<key>com.apple.developer.networking.networkextension</key>
<array>
<string>packet-tunnel-provider</string>
</array>

The packaged dmg installation package cannot be opened, and an error is reported directly

The application "My application" could not be opened.

But when I don't add this configuration, the program can run normally, but there is no project corresponding to NetworkExtension, how can I change it?
<img width="263" alt="截屏2023-08-29 21 35 56" src="https://github.com/electron-userland/electron-builder/assets/8295680/570f1a1d-f42d-4be1-b424-1d4409a6b310">
<img width="772" alt="截屏2023-08-29 21 38 31" src="https://github.com/electron-userland/electron-builder/assets/8295680/25323558-56c2-4659-a2e8-cba75e140258">

**Comment by quocanh944** [comment]
This issue may be related to this article [Hardened Runtime](https://developer.apple.com/documentation/security/hardened-runtime?language=objc). 

> Due to their privileged position in the system, macOS refuses to load system extensions that use Hardened Runtime exception entitlements. There’s one exception to this general rule: macOS allows the [Allow execution of JIT-compiled code entitlement](https://developer.apple.com/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit?language=objc) in non-DEXT system extensions.
