### ISSUE TITLE
AppImage binary uses name instead of productName

### ISSUE THREAD

**Issue by saghul** [electron-userland/electron-builder#775]
- **Version**: 1.4.1

- **Target**: Linux

Even if I have specified the productName both in my app package.json and in the development package.json, the generated binaries have name-version-arch.AppImage format.  Is there a way to customize this pattern?  Having a way of doing this consistently across all platforms would be ideal.

Last, thanks a lot for electron-builder, it's such a great tool! :heart:

**Comment by develar** [comment]
I am afraid that it is not safe to use space in the AppImage file name for now. Root issue (doesn't work at all if space in the name) fixed, but I am not yet sure that all possible bugs are fixed.

So, please wait a week or so — I will investigate is it possible to use space in the file name again or not.

**Comment by saghul** [comment]
Thanks for the heads up!

**Comment by dperetti** [comment]
Yeah, the AppImage build doesn't seem to be using the right executable name :-(

**Comment by black-snow** [comment]
@saghul @dperetti is this still an issue?

**Comment by develar** [comment]
`artifactName` is supported in the next release. By default nothing changed, but you want — you can customize artifact name on your own risk. Maybe decision will be reconsidered later, but not now.
