### ISSUE TITLE
Exclude specific dependencies from rebuilding native dependencies

### ISSUE THREAD

**Issue by temuccio** [electron-userland/electron-builder#7752]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  18.17.1

* **Electron Version**: 24.0.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**:  Windows 10

Hi all,
I'm use `electron.js` with `react`.
My react project has a dependencies was require canvas. In demo mode it works fine.
When I build the appication, electron-build try to
`rebuilding native dependencies  dependencies=better-sqlite3@8.5.2, canvas@2.11.2, sqlite3@5.1.6 platform=win32 arch=x64`
and it cause error.
I believe that canvas is not necessary to rebuild as a dependency; it is included in the React bundle.js.
How I can exlcude canvas from rebuilding native dependencies?
In `package.json`, I've tried adding the following:

```
"build":{
  ...
  files":[
    "!node_modules/canvas/*"
  ]
  ...
}
```

but not works.
Other solution?
If I delete directory `node_modelus/canvas`, the build works fine (but not react project).
Thanks

**Comment by mmaietta** [comment]
Sorry, that's not possible to achieve. The native dependency tree is generated by an upstream GoLang dependency app-builder.
