### ISSUE TITLE
Taskbar icon not correct on Windows

### ISSUE THREAD

**Issue by JeroenVinke** [electron-userland/electron-builder#776]
- **Version**:  electron-builder

- **Target**:  Windows

Somehow the icon in the taskbar is incorrect when I have used the installer of the application.

**When installer is running**
## ![image](https://cloud.githubusercontent.com/assets/2189477/18808066/83362270-8258-11e6-94b6-c935a41f2bd2.png)

---

**After installer is done and app opens**
## ![image](https://cloud.githubusercontent.com/assets/2189477/18808062/79abccf0-8258-11e6-86e4-816edeebe4a0.png)

---

**Files in appdata have right icon**
## ![image](https://cloud.githubusercontent.com/assets/2189477/18808067/90d5241c-8258-11e6-9473-7b6e3fdcdc2e.png)

---

**Files in appdata have right icon**
## ![image](https://cloud.githubusercontent.com/assets/2189477/18808068/990cc37e-8258-11e6-8414-c0f4af4573bb.png)

---

**win-unpacked has correct icon**
![image](https://cloud.githubusercontent.com/assets/2189477/18808079/b262afbe-8258-11e6-83af-ad0f1971d749.png)

---

---

What setting am I looking for that could be causing this issue?

Thanks

**Comment by JeroenVinke** [comment]
@develar if you have time, can you point us in the right direction? thanks!

**Comment by develar** [comment]
Please use nsis target and electron-builder 10.2.0

Sorry for late response. I have missed issue.
