### ISSUE TITLE
Can't package into apk

### ISSUE THREAD

**Issue by JIMhackKING** [electron-userland/electron-builder#7766]
* **Version**: 24.6.4

* **Electron Version**: 26.1.0

* **Electron Type (current, beta, nightly)**: Current

* **Target**: apk

I have tried installing the apk file on Android emulators and my real phone, it says "There was a problem parsing the package". My electron project does work fine on Windows.

I’ve tried creating the simplest Electron project with just one HTML file and packaging it into an APK, but I also couldn’t install it.

_Originally posted by @JIMhackKING in https://github.com/electron-userland/electron-builder/issues/5577#issuecomment-1709761969_

**Comment by selfisekai** [comment]
apk here (fpm, electron-builder) refers to [apk-tools](https://gitlab.alpinelinux.org/alpine/apk-tools) (alpine package keeper), not android. it's the format used on alpine linux.

**Comment by JIMhackKING** [comment]
> apk here (fpm, electron-builder) refers to [apk-tools](https://gitlab.alpinelinux.org/alpine/apk-tools) (alpine package keeper), not android. it's the format used on alpine linux.

My mistake, I misunderstood the meaning of apk. Is there any way to package an electron project into an Android APK installation package?
