### ISSUE TITLE
 ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Headers'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Headers'

### ISSUE THREAD

**Issue by orange-blossoms** [electron-userland/electron-builder#7768]
ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Headers'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Headers'
 at processImmediate (internal/timers.js:456:21)
From previous event:
    at copyAppFiles (/workspace/ada-hyperion-test/node_modules/app-builder-lib/src/util/appFileCopier.ts:86:27)
child_process.js:650
    throw err;
    
    "electron-builder": "24.6.3",
    "electron-rebuild": "1.8.4",

**Comment by justb** [comment]
+1 same error

**Comment by KishanBagaria** [comment]
We face this. Perhaps passing [`verbatimSymlinks: true`](https://nodejs.org/api/fs.html#fspromiseslinkexistingpath-newpath:~:text=recursively%20Default%3A%20false-,verbatimSymlinks,-%3Cboolean%3E%20When) to `fs.cp` might fix this.

**Comment by StreetStrider** [comment]
Hello, yall. How did you workaround?

**Comment by StreetStrider** [comment]
`electron-builder@23.6` is not affected
`electron-builder@24.0.0` is affected
I guess, the workaround is to use latest in 23. Is it possible to attract maintainers' attention to this.

**Comment by greenn-lab** [comment]
If you suffer yet, try to treat to `asar: true` build options.

**Comment by dingshaohua-com** [comment]
> If you suffer yet, try to treat to `asar: true` build options.

Firstly, I just don't want to activate Asar. Secondly, even if I kneel down and close it, I will get another mistake, but in any case, I must be wrong
![ed700b9b694ee8733b81248636afc542](https://github.com/user-attachments/assets/725d64df-a0ae-4231-bc67-d0f7d71b6a98)

**Comment by Valeaal** [comment]
no problem using a intel macos-13 runner

**Comment by no3plane** [comment]
This line of code causes the bug when copying symlink chain. (such as dynamic under macOS)
I tried it out. If I replace the call to `ensureSymlink` with a call to `symlink`, then there's no problem

<img width="915" height="446" alt="Image" src="https://github.com/user-attachments/assets/4278a9c5-f6dc-43a6-b83e-0e40170a1490" />

<img width="841" height="368" alt="Image" src="https://github.com/user-attachments/assets/d885a41b-e051-4fcf-9613-3aaad6608cff" />
