### ISSUE TITLE
permission denied - HELP!

### ISSUE THREAD

**Issue by DracotMolver** [electron-userland/electron-builder#777]
Version:  6.7.7
Target:  rpm and deb

Hi, In my app I'm using some json files that I have into resources folder...and I need to modify them ...but I can't because sasy permission denied. This does not happen when I'm using electron-packager.

**Comment by develar** [comment]
Issue solved?

**Comment by DracotMolver** [comment]
@develar yes. The thing was that I was working into the app folders, and I can't use them to store data. But reading the doc, I found that electeonjs has special folder to store data. So it is not an issue of electron-builder. I think, it was my fault and at the same time it can be the doc of electronjs.

**Comment by pie6k** [comment]
@DracotMolver so what was the issue?
