### ISSUE TITLE
electron-builder config can‘t load .ts file in windows OS

### ISSUE THREAD

**Issue by TianbinTobin** [electron-userland/electron-builder#7775]
* **Electron-Builder Version**: 
24.6.4

* **Node Version**: 
18.17.1

* **Electron Version**:
26.2.1
* **Electron Type (current, beta, nightly)**:
current

* **Target**: 
win x64

![image](https://github.com/electron-userland/electron-builder/assets/16282973/21fa3555-c739-4381-ac10-62624470ef1c)
![image](https://github.com/electron-userland/electron-builder/assets/16282973/206059c2-0a2c-40a3-a1cd-3a25193c898b)
![image](https://github.com/electron-userland/electron-builder/assets/16282973/e4aebedc-4bb5-4b13-bbc2-d5685ff3d88f)
: is an illegal character in windows and cannot be used as the file name

**Comment by seanssel** [comment]
Bumping this

**Comment by t3chguy** [comment]
Tracked in https://github.com/develar/read-config-file/pull/17

**Comment by mmaietta** [comment]
This should be resolved now as the config loading now leverages the same module resolution function/logic that the electron-builder hooks utilize. I removed the upstream dependency and rewrote it internally to add some features.
