### ISSUE TITLE
Support for Electron for ARM

### ISSUE THREAD

**Issue by Rob4001** [electron-userland/electron-builder#778]
* **Version**: 5.18.0

* **Target**: Linux Deb + RPM for ARM

Electron has builds for Linux ARM... This is supported by electron-packager, could we make it an available arch for the linux build target?

**Comment by develar** [comment]
Please note — AppImage arm is not supported. Please file issue if target format doesn't support arm — will be fixed/investigated by request.

**Comment by probonopd** [comment]
The AppImage format also works for ARM, e.g., the MuseScore project provides [armhf (new 32-bit) AppImages](https://musescore.org/en/download/musescore-armhf.AppImage).

**Comment by jeroenrinzema** [comment]
I am currently developing a application for the raspberry pi which requires the AppImage to be in ARM format. It would be nice if i could build my application in ARM format with electron-builder.

**Comment by develar** [comment]
@jeroenrinzema could you please file new issue?

**Comment by jeroenrinzema** [comment]
#1478
