### ISSUE TITLE
Binaries in extraResources are not automatically updated with asar

### ISSUE THREAD

**Issue by Zhengyangzuishuai** [electron-userland/electron-builder#7781]
Here is my package.json and extra dir, I used electron-updater to auto update.
All the contents including the rendering process and the main process have been updated, but the contents in extra are not updated together.
<img width="423" alt="image" src="https://github.com/electron-userland/electron-builder/assets/43663302/d2837cef-9fd2-459c-811c-03838aa1f541">
<img width="305" alt="image" src="https://github.com/electron-userland/electron-builder/assets/43663302/50594912-a366-4a9f-837a-97c8a518532e">
<img width="279" alt="image" src="https://github.com/electron-userland/electron-builder/assets/43663302/394cd8a3-84be-48d0-ae8e-05a3f70c6198">

**Comment by Zhengyangzuishuai** [comment]
When I do not use autoupdater, but only use the npm run build packaged installation file to install, the content in extraResources is updated correctly. It seems that the content in extraResources will not be overwritten.

**Comment by Zhengyangzuishuai** [comment]
This is my problem. The binary file in my extraResources is a daemon process. During quitandinstall(), the exe is occupied by the process, making it impossible to successfully uninstall the program.

**Comment by mmaietta** [comment]
It sounds the proper solution would to have your daemon process killed prior to `quitAndInstall`. Is that something you can do via js code? If not, then probably `nsis` scripting would be the next best solution https://www.electron.build/configuration/nsis#custom-nsis-script
