### ISSUE TITLE
Documentation issue build/category

### ISSUE THREAD

**Issue by ir-fuel** [electron-userland/electron-builder#780]
When looking there:
https://github.com/electron-userland/electron-builder

in the Quick setup guide there is a json file containing:
`"category": "your.app.category.type"`

However when checking the docs at
https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata

`category` is not in the list

Where can we find the possible values for this attribute?

**Comment by develar** [comment]
`category` should be in the `build.mac` / `build.linux`.
