### ISSUE TITLE
Autoupdate quitAndInstall() Not Restarting App after install (MAC) 

### ISSUE THREAD

**Issue by idnistrian** [electron-userland/electron-builder#7800]
* **Electron-Builder Version**: 24.6.4

* **Node Version**:  v16.17.0

* **Electron Version**: 26.2.2
* **Electron Type (current, beta, nightly)**: current

 6.1.5

* **Target**: 
default

We have implemented auto updater server by using Nuts server, and successfuly getting all of .yml file to update, when users click 
quitAndInstall app getting closed to install update, but we are never get app to restart. 
We have checked log files, 

[ShipIt_stderr.log](https://github.com/electron-userland/electron-builder/files/12736006/ShipIt_stderr.log)

and lookslike some processes were spawn not correctly.

Can some one to help us? 
BTW on windows everything is okay, here is the piece of code how do we trigger quitAndInstall event 
<img width="765" alt="image" src="https://github.com/electron-userland/electron-builder/assets/91140978/43ac8c47-f385-45cc-8f4d-f065152f2a72">
 
[main.log](https://github.com/electron-userland/electron-builder/files/12736038/main.log)

**Comment by BruceMacD** [comment]
Are you downloading the update multiple times by any chance? I see the same behaviour when I call `autoUpdater.checkForUpdates()` more than once when an update is available (MacOS only as far as I know).

The actual error on `autoUpdater.quitAndInstall()` is:
```
No update available, can't quit and install
```

**Comment by liangskyli** [comment]
I also have the same problem in mac
