### ISSUE TITLE
msiWrapped does not seem to pass oneClick or perMachine options to build 

### ISSUE THREAD

**Issue by itsBrady** [electron-userland/electron-builder#7801]
* **Electron-Builder Version**: "24.6.3"

* **Node Version**: v14.17.3

* **Electron Version**: "16.0.2"
* **Electron Type (current, beta, nightly)**:

* **Target**: nsis msi

when trying to build using the new msiWrapped option, it does not use the oneClick or perMachine options passed in the msiWrapped definition

```
"msiWrapped": {
      "warningsAsErrors": false,
      "oneClick": false,
      "perMachine": true,
      "createDesktopShortcut": true,
      "runAfterFinish": false
    },

"win": {
      "target": [
        {
          "target": "msiWrapped",
          "arch": [
            "x64",
            "ia32"
          ]
        },
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
```

results in this in logs when building

```
building        target=nsis file=boop.exe archs=x64, ia32 oneClick=true perMachine=false
building        target=MSI arch=x64 file=dist\Boop 254.254.254.msi
```

installing the wrapped MSI afterwards does not prompt for install location it just automatically puts it into appData.

In testing it looks like it just inherits those from whatever the nsis target has set

**Comment by robatwilliams** [comment]
This is still an issue.
