### ISSUE TITLE
app icon not set for signed windows builds

### ISSUE THREAD

**Issue by brett-koonce** [electron-userland/electron-builder#7803]
We have recently gotten an EV certificate to allow us to sign builds of our app for distribution.  I have set up signing and am able to make signed builds for our users.  The issue is that the electron app is not updating the icon in the signed builds.

When I run `yarn dist:windows` without any signing parameters in the electron-builder.json file (eg just target/icon), the resulting app shows the specified (correct) icon:

![Screenshot 2023-09-28 135302](https://github.com/electron-userland/electron-builder/assets/127266705/54978a24-8b84-45d3-9891-29e715fd4c4b)

However, when I add the signing flags to the electron-builder config, the app is built and signed correctly, but the default react icon gets used:

![Screenshot 2023-09-28 135736](https://github.com/electron-userland/electron-builder/assets/127266705/f07ffbd3-c2f6-4793-a761-0c7013f4a727)

We are using an older version of electron/electron-builder, eg
```
    "electron": "^19.0.7",
    "electron-builder": "^23.1.0",
```
but it doesn't seem like too much has changed in the past ~18 months that would trigger this behavior.

My yarn commands look like so:

```
    "build:all": "yarn build:app && yarn build:electron",
    "build:app": "cross-env BUILD_PATH='./build/browser' react-scripts build",
    "build:electron": "tsc -p ./src/node",
    "dist:windows": "yarn build:all && electron-builder -w",
```

Has anybody seen this behavior before?  Any suggestions for things to try?

**Comment by mmaietta** [comment]
`signAndEditExecutable` is the step when the icon is applied, so the step is being skipped because it's being set `false`
Ref: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/winPackager.ts#L275

If you just want to disable signing, then I think you can just set `sign: null` in the win config.

(Not sure why it was written this way, but that's what I'm garnering from a quick read of the current code)

**Comment by brett-koonce** [comment]
@mmaietta I was trying to make sense of that file earlier!  What you are saying makes sense/tracks with what I am observing here.  I am embedding another application inside the bundle with a self-signed cert.  I will do a pass on getting that validated as well and then I should be able to run with flag set to true.

**Comment by brett-koonce** [comment]
see also #4343
