### ISSUE TITLE
include EULA license file in windows installer

### ISSUE THREAD

**Issue by fridgerator** [electron-userland/electron-builder#781]
* **Version**: latest **7.9.0**

* **Target**: windows 10 x64

I am including an EULA license file in the NSIS installer.

I have edited package.json to include  a custom `nsis.include` = `resources/windows/license.nsh`

My `license.nsh` script looks like this:
```
!include "MUI2.nsh"

!insertmacro MUI_PAGE_LICENSE "resources\license.txt"
```

The NSIS installer creation fails at `common.nsh` line 11 when setting `Unicode true` with:
```
Error: Can't change target architecture after data already got compressed or header already changed!
Error: Unable to set target charset (adequate stub not found?)
```

I can fix this temporarily by commenting out line 11 in `common.nsh`.

I'm not very familiar with NSIS, I wasn't sure it its possible to check the mentioned cases in the error message before setting the `Unicode` value or not.  Or if this is even something that you all wanted to worry about.

**Comment by develar** [comment]
Please try to wrap your code into macro customHeader.

I am on vacation — you can expect fix in 3 days.

**Comment by artpol** [comment]
Builder Version: 7.14.1
Target: Windows 10 x64

I'am trying to make EULA page in NSIS, 

I make windows_license.nsh:
```
!macro customHeader
    !include "MUI2.nsh"
    !insertmacro MUI_PAGE_LICENSE "windows_license.txt"
!macroend
```

my developer package.json have this build section:
```
  "build": {
    "appId": "company.product",
    "productName":"Company Product",
    "mac": {
      "category": "public.app-category.business"
    },
    "win": {
      "target": ["nsis"],
      "msi": true
    },
    "nsis": {
      "oneClick": false,
      "perMashine": false,
      "include": "build/windows_license.nsh"
    }
  }
```

The NSIS installer creation fails with error:

> Building NSIS installer
> ....
> warning: !warning: MUI_PAGE_* inserted after MUI_LANGUAGE (macro:MUI_PAGE_INIT:3)
> Error: warning treated as error

Please tell me what I'm doing wrong?

**Comment by develar** [comment]
@artpol Issue is fixed, I will finish and push fix in the evening, please wait.

**Comment by artpol** [comment]
Thanks a lot

**Comment by develar** [comment]
Please try 7.14.2. `nsis.license` or just put `license.rtf` or `license.txt` to build resources (`build` directory.

**Comment by fridgerator** [comment]
works great! thank you! 👍
