### ISSUE TITLE
Is support for custom channels dropped?

### ISSUE THREAD

**Issue by SoumyaRanjanPatnaik** [electron-userland/electron-builder#7815]
## Environment Details

* **Electron-Builder Version**: 

* **Node Version**:  18

* **Electron Version**: 24.4.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows, linux, macos

## Description

I'm trying to setup ci for one of the applications I'm working on. We have 4 branches -> development,  demo, internal, main and want my binaries to use a different channel for each branch. I found [this](https://www.electron.build/configuration/publish.html#continuous-deployment-workflow-on-amazon-s3-and-other-non-github) in the  documentation. 

> Set your version in your application package.json to 1.9.0-snapshot (or 1.9.0-master or whatever you want your development channel to be named).

This suggests that we can use any set of channel names, and it should work, but it doesn't. 

In my case, I've set the package.json version to v2.0.0-development. The generated binary is always `Appname-2.0.0-latest.AppImage` (I've set my artefact name manually to include the channel name). 

## What I've tried

- setting `"generateUpdatesFilesForAllChannels": true`
- using `c.publish.channel=development` flag causes this issue:
    ```
    configuration.publish.channel should be one of these:
      "alpha" | "beta" | "dev" | "rc" | "stable" | null
    ``` 
- Also tried using a combination of both

I also found [this](https://github.com/electron-userland/electron-builder/issues/1182#issuecomment-352190312) comment on one of the issues explaining the usage of channels. Tried to find an issue that tries something like this but there were none.

**Comment by k2s** [comment]
Try to use `dev` instead of `development`. Names of the channels are given https://www.electron.build/tutorials/release-using-channels.
