### ISSUE TITLE
Description displayed rather than name?

### ISSUE THREAD

**Issue by robwilkerson** [electron-userland/electron-builder#783]
- **Version**: 7.3.0

- **Target**: Windows

It looks like the `description` value from our `app/package.json` file might be appearing where it should be showing the `productName` value. Or maybe I'm just doing something wrong. Specifically, we see the description in the Task Manager.

Screenshots below, but here's a snippet from our `app/package.json` file:

``` javascript
{
  "name": "hughesnet-status-meter",
  "author": "Hughes Network Systems, LLC",
  "productName": "HughesNet Status Meter",
  "description": "Status Meter is like a fuel gauge for your HughesNet Data Allowance.",
  "main": "app.js",
  "version": "6.5.1-rc.4",
  ...
}
```

![name_taskmanager](https://cloud.githubusercontent.com/assets/7735/18876150/92118920-8496-11e6-88e5-90d950521026.PNG)
![name_start-up](https://cloud.githubusercontent.com/assets/7735/18876152/921420b8-8496-11e6-917a-e37b3a1eb1b4.PNG)

**Comment by develar** [comment]
Please try NSIS target.
