### ISSUE TITLE
Pass OTHER_LDFLAGS option to xcodebuild command

### ISSUE THREAD

**Issue by DavidWnek** [electron-userland/electron-builder#7832]
* **Electron-Builder Version**: 25.6.4

* **Node Version**: 18.16.9

* **Electron Version**: 26.2.1
* **Electron Type (current, beta, nightly)**: current

* **Target**:  mac-intel, mac-arm, win-64

I'm in the process of evaluating some external wrapping software for applications, and a requirement is to set additional OTHER_LDFLAGS into the xcodeproject.

I've looked through the configuration docs, but didn't see a way to set any OTHER_LDFLAGS in there.

Specifically I need to set:
`OTHER_LDFLAGS = -Xlinker -headerpad -Xlinker 800`

Is there any other options I've missed to accomplish this?

Full Exception:
```
MachOException::InsufficientHeaderPad, 12, Insufficient size available in the Mach-O header for the operation. Please try again after rebuilding the binary with the following header pad setting:
OTHER_LDFLAGS = -Xlinker -headerpad -Xlinker 800
```

**Comment by mmaietta** [comment]
I'm assuming this is related to a native binary, for which only npm rebuild is being called. electron-builder doesn't execute xcodebuild directly so I'm not sure how I can help here
