### ISSUE TITLE
Electron Builder Not Updating Until App Is Closed

### ISSUE THREAD

**Issue by ProdigyView** [electron-userland/electron-builder#7834]
Here is my code for doing updates:

```
autoUpdater.on('update-downloaded', (info) => {

  try {

    dialog.showMessageBox({
      type: 'question',
      buttons: ['Install and Restart', 'Later'],
      defaultId: 0,
      message: 'A new update for Glitch has been downloaded. Would you like to install and restart the Glitch now?'
    }, (response) => {
      if (response === 0) {
        try {

          setTimeout(() => {
            app.relaunch();
            app.exit(0);
          }, 10000);

          setImmediate(() => {
            autoUpdater.quitAndInstall(false);
          });



        } catch (e) {
          dialog.showErrorBox('Error', 'Failed to install updates');
          console.error(e);
        }
      }
    });

  } catch (error) {
    console.error(error);
  }

});
```

Now what happens  is after the user agrees to install the update, the app installs the new update(I think) but it doesn't quit. The user can continuing using the current release of the application as normal. But when the user quits the application, that is when the update occurs and new version is actually installed.

My app:
"electron-builder": "^24.6.4",
"electron": "27.0.0",
"electron-updater": "^6.1.4",
"node": v20.7.0

**Comment by ProdigyView** [comment]
@mmaietta What I am saying is the expected before is that quitAndInstall should stop the application, and then run the install, and then re-open. This is not what happens.

The application must be quit by the user, and then the install process begins. The fact the user has to be the one to quit the application is the problem.

**Comment by alchalade** [comment]
I'm facing the same issue as well (both on MAC and Windows). The expected behavior of `autoUpdater.quitAndInstall();` is to terminate the application, initiate an installation process, and then relaunch the app with the updated version. However, it leaves the outdated app running, and the installation only occurs when the user manually terminates the app.

**Comment by mmaietta** [comment]
`app.quit` is explicitly called to terminate the app.
https://github.com/electron-userland/electron-builder/blob/869c7e4652a5d5a3562e25723d6cedd622ab657b/packages/electron-updater/src/BaseUpdater.ts#L14-L27

Code looks fine to me. Installation process kicks off before the app calls `quit`. `app.exit()` and `app.relaunch` shouldn't be called most likely, best guess is that it's overriding the `quit` logic that is within electron.
