### ISSUE TITLE
File licensed under LGPL v2.1 or later in a package

### ISSUE THREAD

**Issue by rahulmohang** [electron-userland/electron-builder#7836]
Hi,

The file, 'https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/include/StdUtils.nsh' is licensed under the license, LGPL v2.1 or later. 

Do you think that it may have a copyleft effect on the rest of the parts of electron-builder?

**Comment by mmaietta** [comment]
Sorry, I'm not familiar with types of licensing, nor was aware of the templates having varying licenses. Those were likely introduced by the repo owner @develar, who could probably provide more insight here?

**Comment by rahulmohang** [comment]
Some discussions on this issue may be found at https://github.com/lordmulder/stdutils/issues/21.

**Comment by develar** [comment]
> Calling my LGPL'd plug-in from a proprietary (non-LGPL) installer is allowed. It's exactly how the plug-in is intended to be used. It does not require you to release your own code under the LGPL too.
But, if you modify my plug-in, then you have to share that modified plug-in version under the LGPL again! Assuming that you didn't modify my plug-in and distribute the plug-in DLL as I provide it, you are fine.

Also, 


> The GPL (not LGPL) essentially says that, if you incorporate any GPL'd code into your software - even by calling the GPL'd code from a separate(!) DLL file - then your software becomes a "derivative work" of the GPL'd code. And, therefore, your software - as a whole - must be distributed under the GPL too!

> The LGPL is more permissive.

`L` stands for `Library`. 
electron-builder doesn't stole source code — copyright note in-place and preserved.

**Comment by rahulmohang** [comment]
Thank you.
