### ISSUE TITLE
The appData will not removed when uninstalling electron app on macOS

### ISSUE THREAD

**Issue by oalfroukh** [electron-userland/electron-builder#7840]
* **Electron-Builder Version**: v24.6.0

* **Node Version**: v16.17.1

* **Electron Version**: v22.3.27
* **Electron Type (current, beta, nightly)**:

* **Target**:  dmg

- Expected behavior:
Uninstalling the Electron app by moving it to the trash should clear the app data of the removed app (`/Users/username/Library/Application\ Support/appName/`).

- Actual behavior:
Uninstall the Electron app by moving it to the trash will not clean the appData (`/Users/username/Library/Application\ Support/appName/`).

**Comment by oalfroukh** [comment]
"bump"

**Comment by ayushete02** [comment]
@codebytere check this
https://github.com/electron/electron/issues/40314

**Comment by Coffe2Cat** [comment]
sos, this question has been bothering me for a long time

**Comment by Finesse** [comment]
> * Uninstalling the Electron app by moving it to the trash should clear the app data of the removed app (`/Users/username/Library/Application\ Support/appName/`).

Does any macOS app do it? Is it even possible without a separate uninstaller app?
