### ISSUE TITLE
checkForUpdates takes 22 seconds to check S3, every time. Anyway to speed this up?

### ISSUE THREAD

**Issue by ianoble** [electron-userland/electron-builder#7843]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 18.18

* **Electron Version**: Latest
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Windows

Running autoUpdater.checkForUpdates() consistently takes 22 seconds to return "update-not-available". We're trying to check for updates when the application launches, but it's taking too long for it to be feasible on every launch.

Is there anyway to speed this up just to tell us if there is a new version or not?

We're using S3 for our published repository. The FeedURL is getting set by:

`if (process.env.VUE_APP_S3) autoUpdater.setFeedURL(process.env.VUE_APP_S3);`

**Comment by mayfield** [comment]
@ianoble did you ever find a resolution to this?  I have a user reporting extremely long update checks with the github provider as well.  Since it looks like EB is using a custom http client and my user has no other networking issues, I suspect this is an open problem.
