### ISSUE TITLE
macOS icon size is not correct

### ISSUE THREAD

**Issue by jhh-ncurity** [electron-userland/electron-builder#7845]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.20.0

* **Electron Version**: 24.4.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macos

According to your doc, macOS Icon size should be at least 512x512.
https://www.electron.build/icons#macos

So I used `.png` file at exactly 512x512 size.

But icon is somewhat different in size to a normal macOS applications.
See the screenshot below.

in launchpad:
<img width="727" alt="스크린샷 2023-10-25 오전 11 19 44" src="https://github.com/electron-userland/electron-builder/assets/99626969/ed23ca96-410e-48fa-bfbe-b26252bfce98">

in dock:
<img width="727" alt="스크린샷 2023-10-25 오전 11 23 46" src="https://github.com/electron-userland/electron-builder/assets/99626969/db5f2c90-5ad2-4fb6-ba47-cd1d22a3bf89">

How can I fix this? Or what is correct size?

**Comment by mmaietta** [comment]
Looks like MacOS Design Guidelines expect there to be a padding and shadow for icons. Apple provides a template for app icons as well
https://developer.apple.com/design/human-interface-guidelines/app-icons#Platform-considerations

**Comment by tranvuluan** [comment]
@jhh-ncurity did you solve it?
I have the same issue
