### ISSUE TITLE
electronuserland/builder:18 has node v18.15.0 but I need 18.16.0

### ISSUE THREAD

**Issue by ScubaDrew** [electron-userland/electron-builder#7848]
`electronuserland/builder:18`

* **Electron-Builder Version**: 24.6.4

* **Node Version**: 18.16.0

* **Electron Version**: 26.4.2

How can I get node `18.16.0`+ in `electronuserland/builder:18` ?

**Comment by mmaietta** [comment]
I can update the docker images to latest node18. Would 18.17.0 work for you or does it have to be 18.16.0?

**Comment by ScubaDrew** [comment]
Hey @mmaietta ! Thank you for responding. I'd upgrade to whatever is best for the community, not just me :) 

I'm surprised I'm the only one running into this. It seems like if we had `electronuserland/builder:18.16.0` and other versions as tagged containers, that would serve the most folks the best. 

Again, I am a single developer, and and an electron beginner - so maybe I'm doing something entirely wrong here. I'm very surprised to be the only one running into this.

**Comment by mmaietta** [comment]
I've been debating on tagging images with the Node version for some time now. Previously it was always the `month-day`, but I'm not sure why.

**Comment by ScubaDrew** [comment]
Yeah `month-day` -- can't think of a good reason for that except easier to implement a scheduled build?

**Comment by mmaietta** [comment]
Give the latest build a shot, it has 18.18.2
https://hub.docker.com/layers/electronuserland/builder/18/images/sha256-b6bd511155ec4607890f3c9767871691b1b0448ed41445377cd61df83c5310ca?context=explore

**Comment by ScubaDrew** [comment]
Thanks @mmaietta I'll give it a shot!

**Comment by mmaietta** [comment]
Scratch that. Forcing a redeploy, I think the ARG was overridden by a build script. Will be upgraded in https://github.com/electron-userland/electron-builder/pull/7882
