### ISSUE TITLE
How to use other binary apllications?

### ISSUE THREAD

**Issue by Luchanso** [electron-userland/electron-builder#785]
* **Version**: 7.9.0

* **Target**: Win-ia32

I use other programms in my project like this:
```js
const spawn = require('child_process').spawn
const bin = spawn('tor/tor.exe')
```

How to build it files? Or how to use other application in project?
When builded and runed, this code not work
![image](https://cloud.githubusercontent.com/assets/2098777/18931428/cc4ad1b6-85d4-11e6-9fee-e3ea9418c2ab.png)

**Comment by develar** [comment]
Does it work before package? Do you see this file in the `resources` in the packed app (please attach directory listing).

**Comment by Luchanso** [comment]
Yes, it work before package. I got [answer](https://github.com/electron/electron/issues/7396#event-806218963) on my question in electron issue.

**Comment by develar** [comment]
Duplicate #751
