### ISSUE TITLE
builder-util-runtime error due to @types/node (module httpExecutor.d.ts)

### ISSUE THREAD

**Issue by ArMinasyan** [electron-userland/electron-builder#7850]
* **Electron-Builder Version**:  24.6.3

* **Node Version**: 18.17.1

* **Electron Version**: 25.3.1
* **Electron Type (current, beta, nightly)**:

* **Target**:  Error with electron-updater, in package builder-util-runtime (module httpExecutor.d.ts)

**Comment by MadEddieFFS** [comment]
Same error: https://github.com/electron-userland/electron-builder/issues/7837

**Comment by mmaietta** [comment]
Please try latest pre-release https://github.com/electron-userland/electron-builder/releases/tag/v24.8.1

It has the updated `@node/types`

**Comment by ArMinasyan** [comment]
Sane error 
![image](https://github.com/electron-userland/electron-builder/assets/46679050/04b8f6ee-05be-48c0-9fa0-9aae4313457c)

**Comment by MadEddieFFS** [comment]
@ArMinasyan - You need to use Yarn. If you use npm you will continue to get this error

**Comment by ArMinasyan** [comment]
I used yarn too,  but get same

**Comment by mmaietta** [comment]
Please create a local reproducible repo of this issue. I can't repro it locally and the code `[key: string]: string` isn't anywhere in that file anymore

**Comment by MadEddieFFS** [comment]
Its worth trying - delete node_modules and if you previously used npm - delete pagckage-lock.json and try again with Yarn. Or if you are set on npm, just try the deletion of node_modules and package-lock.json.
