### ISSUE TITLE
Desktop file generation for unpackaged dir build

### ISSUE THREAD

**Issue by zt64** [electron-userland/electron-builder#7856]
* **Electron-Builder Version**:  v24.6.4

* **Node Version**: v20.9.0

* **Electron Version**: v27.0.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Linux x86_64 & Arm64

Currently the `--dir` build option does not create a `.desktop` file in the build directory. Packaged build options for linux do include a desktop file within. So it would make sense for the unpackaged version to also include a desktop file. 
Personally I am using electron-builder in an AUR package, and the only way in its current state is to extract the desktop file from an appimage, or generation through other means.

**Comment by zt64** [comment]
Not stale

**Comment by oech3** [comment]
Would you reopen?
