### ISSUE TITLE
Can't run generated app due to wrong permission in Linux builds ("locales" and "resources" directories)

### ISSUE THREAD

**Issue by blueoctopus** [electron-userland/electron-builder#786]
- **Version**: 7.10.0

- **Target**: Ubuntu .deb package

The permissions are correctly set when using electron-builder v7.3.0. When building with v7.10.0, the installed app can't run after it's installed due to these wrong permissions:

```
drwx------ 2 root root 4.0K Sep 27 23:07 locales
drwx------ 3 root root 4.0K Sep 27 23:07 resources
```

I've also found this issue is present in the `linux-unpacked` directory that is generated during a build, so it doesn't seem related to generating deb or rpm packages.

**Comment by hovancik** [comment]
I believe I have the similar problem: 

after building my app for linux (.deb), I can not run app as normal user: 

```
module.js:457
    throw err;
    ^

Error: Cannot find module '/opt/stretchly/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

```

I am able to run app as root (with sudo) properly. 

source code for my app is here:  https://github.com/hovancik/stretchly

**Comment by makeitcount** [comment]
Me too

**Comment by develar** [comment]
Confirmed, will be fixed ASAP, sorry for delay.

**Comment by KochiyaOcean** [comment]
ExtraResources seems still have wrong permission. Electron-builder v7.11.4
![image](https://cloud.githubusercontent.com/assets/8194131/19992177/9eb3924c-a276-11e6-86b9-493a9e1f80a6.png)

**Comment by develar** [comment]
@KochiyaOcean Extra directories permissions is fixed — 755 regardless of original source directory mode. Extra files permissions is fixed as well — read for all is added if missed in the original source file mode. 10.1.0
