### ISSUE TITLE
Prlctl error for windows build

### ISSUE THREAD

**Issue by reddybhavanish** [electron-userland/electron-builder#7862]
Hi all, 
I have implemented CI/CD for my desktop application using circleci, while generating windows build i am getting the following error
<img width="579" alt="image" src="https://github.com/electron-userland/electron-builder/assets/98303580/80b26f06-39c6-4fa2-97ab-b20006e3f254">

 **⨯ Exit code: ENOENT. spawn prlctl ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /root/project/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:427:5)
    at ChildProcess.errorhandler (node:child_process:439:5)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
error Command failed with exit code 1.**

Does anyone have idea about this error ? I am using this docker image - "electronuserland/builder:wine", for windows build.
This is the "electron-builder": "^23.6.0" version i am using.

**Comment by mmaietta** [comment]
Can you try the latest versions (or even `next`) of electron-builder, I'm not able to provide support for older versions, most notably because there's no way to release patches for older versions.

**Comment by adumbgreen** [comment]
Bumping this - I am also running into this issue using the same docker image and latest versions.

**Comment by mmaietta** [comment]
Can you please provide a minimum reproducible repo and I can investigate this asap. I have a Parallels VM with Windows arm64, so hopefully I can replicate it from there.
