### ISSUE TITLE
How can I bypass entry file check?

### ISSUE THREAD

**Issue by Usey95** [electron-userland/electron-builder#7863]
Hi, my case is a little bit special.
I have a self-compiled electron use an encoded asar file as entry, after I delete the origin asar file in "afterPack" hook it throws error:

```
Application entry file "dist/main/main.js" in the "/Users/test/release/build/mac/test.app/Contents/Resources/app.asar" is corrupted: Error: ENOENT: no such file or directory, open '/Users/test/release/build/mac/test.app/Contents/Resources/app.asar'"
```

How can I solve this?

**Comment by mmaietta** [comment]
I used to do something similar in a previous project. I had a `dummy.asar` file with one file in it `/main/main.js` that was just a stub file, and I manually copied it into the electron app during `afterPack`

```
async function afterPackHandler(context: builder.AfterPackContext) {
    const { packager, appOutDir } = context;
    const resourcesDir = packager.getResourcesDir(appOutDir);

    // Remove previous asar files, swap in dummy/decoy asar.
    const unnecessaryFiles = glob.sync([path.join(resourcesDir, "*.asar")]);
    console.log("Removing:", unnecessaryFiles);
    unnecessaryFiles.forEach(filePath => fs.unlinkSync(filePath));

    // Decoy asar has an empty package.json and one funny comment in an otherwise empty out/main.js to troll any prying eyes.
    fs.copyFileSync(path.join(packager.projectDir, "installer", "resources", "dummy.asar"), path.join(resourcesDir, appFilename));
}
```

**Comment by Usey95** [comment]
> I used to do something similar in a previous project. I had a `dummy.asar` file with one file in it `/main/main.js` that was just a stub file, and I manually copied it into the electron app during `afterPack`
> 
> ```
> async function afterPackHandler(context: builder.AfterPackContext) {
>     const { packager, appOutDir } = context;
>     const resourcesDir = packager.getResourcesDir(appOutDir);
> 
>     // Remove previous asar files, swap in dummy/decoy asar.
>     const unnecessaryFiles = glob.sync([path.join(resourcesDir, "*.asar")]);
>     console.log("Removing:", unnecessaryFiles);
>     unnecessaryFiles.forEach(filePath => fs.unlinkSync(filePath));
> 
>     // Decoy asar has an empty package.json and one funny comment in an otherwise empty out/main.js to troll any prying eyes.
>     fs.copyFileSync(path.join(packager.projectDir, "installer", "resources", "dummy.asar"), path.join(resourcesDir, appFilename));
> }
> ```

Nice workaround, thanks a lot.
