### ISSUE TITLE
Assistance Required for Electron Builder and NSIS Installer Integration

### ISSUE THREAD

**Issue by ranjithrr** [electron-userland/electron-builder#7868]
I am facing challenges with my Electron application, which is currently built with Electron Builder version 22 and Electron Updater support. The application was not initially released as an  exe file due to a specific user requirement - the need to package a substantial amount of data along with the application. Consequently, we placed this data folder inside the application's resource/app folder.

Now, we are tasked with providing update support using an electron-builder NSIS (Nullsoft Scriptable Install System) with electron-updator, we have created exe,   We have attempted to do this, and while we are making progress, we are encountering the following issues:

1. **Incorrect Installation Path:** The NSIS installer is not automatically setting the installation path to the current application path. How can we configure it to use the current application path as the installation directory?

2. **Data Folder Removal:** During updates, the NSIS installer is removing the data folder, which is a crucial component of the application. We need a solution to prevent the data folder from being deleted during updates.

3. **Multiple Update Event Triggers:** We have observed that the update event is triggering multiple times during the update process and completing the update as well. How can we ensure that the update event only triggers once for a seamless update experience?

waiting for your support

Thank you in advance for your assistance and support. We look forward to your insights and recommendations.

**Comment by mmaietta** [comment]
1. AFAIK, an installer cannot garner the previous location of the installed application, the installer is self-serve in that it's state-agnostic. It's a self-contained executable that is stateless (with respect to the installed application at least)
2. Probably can consolidate that conversation here https://github.com/electron-userland/electron-builder/issues/7880
3. Which update event is this specifically? I can take a look at the code and check the event payload

**Comment by rustleliu** [comment]
I propose considering an enhancement to the Electron Builder's NSIS installer. 
This enhancement could involve implementing an option or a setting that allows users to choose whether they want to delete only the installed files during the uninstallation process while retaining any additional user-created or unknown content within the installation directory.

**Comment by mmaietta** [comment]
Sounds very nice, but there's no way to discern what files should be remaining in the installation directory. Also, as mentioned in https://github.com/electron-userland/electron-builder/issues/7880, user-created and unknown content is supposed to be stored in AppData/AppLocal (Windows), Application Support (Mac), and Home dir IIRC for Linux. That's the purpose of those folders, to store non-temporary files specific to an application

**Comment by rustleliu** [comment]
I think it is difficult too, but that is the default behavior of MSI installer: it removes what it has installed and keeps any user content.
