### ISSUE TITLE
starting the same "portable" app on windows twice crashes the first instance if unpackDirName is set

### ISSUE THREAD

**Issue by valueerrorx** [electron-userland/electron-builder#7870]
* **Electron-Builder Version**: 24.2.1

* **Node Version**: v21.1.0

* **Electron Version**: 24.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

```
"portable": {
            "useZip": true,
            "unpackDirName": "next-exam-student",
            "splashImage": "public/splash.bmp"
 },
```

package.json configuration is set to unpack into the same directory always. this is necessary because otherwise windows thinks my app is a new app everytime i start it and defender asks over and over again for permissions.

the problem is that students seem to be not patient enough to wait for the app to fully unpack into the tmp directory and double click the executable again and again. 

the second unpack process unfortunately unpacks into the same directory and overwrites some of the files the first process needs to run. therefore the first one crashes and taskmanager is needed to get rid of stalled electron processes.

is it possible to completely check if another electron process of the same application is already running and if so immediately quit the app?

or just check the files in the tmp directory and only unpack if they changed (newer version)

thx a million !

**Comment by valueerrorx** [comment]
it is probably interesting to know that if the splashImage option is used, a second start of the app will immediately fail with an error message because some files are not writable. 

this is actually what i would expect from electron even without splashImage.
and it should fail with "another instance of the program is already running" instead ;-)

**Comment by mmaietta** [comment]
> it should fail with "another instance of the program is already running" instead ;-)

I'm honestly not sure how to implement this, as nsis and portable installers are not my specialty. 

`unpackDirName` is meant to be a static "installation"/runtime folder, so by definition, two apps cannot run from the same unpack directory.
