### ISSUE TITLE
SplashScreen unclean experience. A small window shows for a fraction of a second right before the spash appears.

### ISSUE THREAD

**Issue by valueerrorx** [electron-userland/electron-builder#7871]
* **Electron-Builder Version**: 24.2.1

* **Node Version**: v21.1.0

* **Electron Version**:24.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows

`"splashImage": "public/splash.bmp"`

showing a splash image in order to prevent my users from starting the app twice if unpacking takes too long looks a little bit weird.

the splash is shown as expected but shortly before a small windows window shows (some installer) and disapears immediately. 
the same window shows and disappears when i close the app.

what kind of window is that and why is it shown for a fraction of a second before the splashscreen shows?

**Comment by dfoley-greenlight** [comment]
have the same issue. window pops up on app close for a fraction of a second. only happens if splash screen is configured.
