### ISSUE TITLE
🔥 It says that squirrel cannot be run in administrator mode.🔥

### ISSUE THREAD

**Issue by oinochoe** [electron-userland/electron-builder#7872]
* **Electron-Builder Version**: 24.6.3

* **Node Version**: 18.12.0

* **Electron Version**: 19.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: squirrel

I have a question.
It says that squirrel cannot be run in administrator mode, but I am wondering if I can use electron-builder's requestedExecutionLevel option.

[Link](https://github.com/Squirrel/Squirrel.Windows/issues/1264#issuecomment-1802113686)

And here's another thing I'm curious about:
1. I'm curious as to what part of squirrel I modified and whether it works well as an administrator.
2. I am curious about what concerns there are when running Updater.exe with squirrel as the administrator.

cc @develar  @mmaietta

**Comment by mmaietta** [comment]
Based on that comment you linked, it seems that it isn't supposed to run with admin mode.

I have no idea how squirrel works under-the-hood though, nor the fork of squirrel that we're apparently using

**Comment by oinochoe** [comment]
> Based on that comment you linked, it seems that it isn't supposed to run with admin mode.
> 
> I have no idea how squirrel works under-the-hood though, nor the fork of squirrel that we're apparently using

@mmaietta 
Okay, so electron-builder took squirrel and used it, but electron-builder has no idea what it is. Anyway, I confirmed that electron-builder has no problem creating folders when turned on in administrator mode, and this part is Can I assume it is guaranteed?

**Comment by oinochoe** [comment]
@mmaietta This seems to be saying that the option is provided but suqirrel doesn't know, right?

**Comment by oinochoe** [comment]
@lutzroeder @ezekg Is there anything you know?

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts
