### ISSUE TITLE
Auto update fails without error on Windows(NSIS)

### ISSUE THREAD

**Issue by OSA2001d** [electron-userland/electron-builder#7877]
* **Electron-Builder Version**:  23.6.0, 24.6.4 (22.12.0 and after)

* **Node Version**: v18.17.1

* **Electron Version**: 26.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows(NSIS)

Now we are using electron-builder@22.11.11 and tried to upgrade the version to 23.6.0 and 24.6.4. But by using new versions, we faced auto update fail. Seems like download of the update file is successful, but the subsequent installation fails.

We confirmed that the issue occurs with electron-builder versions after v.22.12.0.

Is there anyone else experiencing the same issue as us?
Does anyone have an idea to fix the issue?

----
**Workaround**
We could fix the issue by changing `uninstall.nsh` as commented [here](https://github.com/electron-userland/electron-builder/commit/baf640da459dc667240e6015deaf11adb2155063#r89379508) on [the commit](https://github.com/electron-userland/electron-builder/commit/baf640da459dc667240e6015deaf11adb2155063) for electron-builder@22.12.0. 

But we are not sure the change is truly correct for us.

**Comment by Jaifroid** [comment]
This could be the same issue as #7127. There are thousands of people affected, but no comment from Electron devs on that issue...

**Comment by louismorgner** [comment]
facing the same issue on nsis builds for windows. tried all combinations of nsis configs. essence is that releases are downloaded from github, but the moment the installation should happens, it just fails silently.

finding: when navigating to `User/username/App Data/Locale/appName-updater`, you find a "pending" folder which includes the installer for the new version (we assume). Opening this one manually just leads to the same silent failure.

extremely frustrating for us as we are using pretty much a default setup for nsis & electron. Will keep you posted if we find something uself.
