### ISSUE TITLE
[Windows] electron-updater is downloading files to C//users/runneradmin instead user folder 

### ISSUE THREAD

**Issue by ivukasinovic** [electron-userland/electron-builder#7878]
* **Electron-Builder Version**: 
* 24.6.4

* **Node Version**: 
18

* **Electron Version**:
* 25.1.0
* **Electron Type (current, beta, nightly)**:
* Current
* **electron-updater
6.1.4

* **Target**: 
* Windows

The updater is always creating C://Users/runneradmin and putting there update files instead of the current user folder.
 I have issues for clients without permission to read files outside their folder. 

I checked logs and got this:
"Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\\Users\\runneradmin\\AppData\\Local\\appName

I'm building app on github actions and using keygen as version repository.

Does anyone know whats the issue here?

**Comment by mmaietta** [comment]
There's a new property in electron-builder `disableDifferentialDownload` for nsis. Would you be willing to try that out and see if that resolves the issue? I recognize that it does disable different downloading, but curious if that's the issue or if the entire download/install process has an issue with the target tmp directory
