### ISSUE TITLE
How Do i Connect Repo To Solar Hosting (Discord Bot Hosting) to auto update files

### ISSUE THREAD

**Issue by KazimFedxD** [electron-userland/electron-builder#7879]
i want to auto update my discord bot files in my hosting but i dont know how to setup it i have put in a personal token and username and i the link for cloned repo i dont get it why its not doing it 
The Repo is private btw

**Comment by mmaietta** [comment]
@KazimFedxD you can use a custom publisher if you implement it yourself. Not sure if you're also requesting for an Auto Update `Provider` for Solar Hosting as well
https://github.com/electron-userland/electron-builder/issues/8049#issuecomment-1955741412

**Comment by KazimFedxD** [comment]
> @KazimFedxD you can use a custom publisher if you implement it yourself. Not sure if you're also requesting for an Auto Update `Provider` for Solar Hosting as well
> https://github.com/electron-userland/electron-builder/issues/8049#issuecomment-1955741412 

It uses the git pull command to pull and I don't know how to connect that up with using the token

**Comment by mmaietta** [comment]
I'm not sure if that'll work with electron-builder (or electron in general)? I don't think it has access to git once compiled.

**Comment by KazimFedxD** [comment]
I don't know and I don't even use it now I auto deploy after each update
because I use GitHub repo so often it's not good to connect
