### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by makeitcount** [electron-userland/electron-builder#788]
* Electron version: 1.4.1
* Operating system: Windows
* Electron-builder : 7.9.0

I am facing this frustrating issue for last 1 week. Everything was working fine earlier.
Issue is that when I build executable and run it, the app installs correctly and starts on first instance. When I close the app and start it again, it doesn't work, app does not get launched.

- App works fine when run in development i.e. `electron .`
- There's no exception (I catch uncaughtexception and write that to file)
- I have tried uninstalling app completely and then again installing apps running executable, issue persists
- Have tried earlier version which were working fine earlier, issue persists

Based on above clues I can say that it's not happening because of the app code. On the other hand the app just never starts in Linux. I believe this has something to do with operating system itself.

I have checked task manager, it does not show the app.

What could be the possible reason? How can I figure this one out? Have anyone else faced it, any clue would help.

**Comment by develar** [comment]
> When I close the app and start it again, it doesn't work, app does not get launched.

Using shortcut?

**Comment by makeitcount** [comment]
Yes

**Comment by makeitcount** [comment]
Squirrel log looks like this
'''
2016-09-29 17:44:44> Program: Starting Squirrel Updater: --processStart MyElectron App.exe
2016-09-29 17:44:44> Program: Want to launch 'C:\Users\u\AppData\Local\MyElectronApp\app-0.0.45\MyElectron App.exe'
2016-09-29 17:44:44> Program: About to launch: 'C:\Users\u\AppData\Local\MyElectronApp\app-0.0.45\MyElectron App.exe':
'''

**Comment by develar** [comment]
Do you handle Squirrel events properly? Please see https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by makeitcount** [comment]
> Do you handle Squirrel events properly?
Yes, I have handled that correctly. I have following code lines at the start of my main js file

```
'use strict';
const electron = require('electron');
const {
    Menu,
    app,
    shell,
    dialog,
    ipcMain,
    autoUpdater,
    BrowserWindow
} = electron;
const path = require('path');
const winston = require('winston');
require('electron-debug')(); // adds debug features like hotkeys for triggering dev tools and reload
if (require('electron-squirrel-startup')) return; //for handling squirel startup events
```

**Comment by makeitcount** [comment]
On receiving window closing event, close all the opening windows(including hidden one). then call app.quit()
this solved it.

**Comment by makeitcount** [comment]
Even now, it's working for windows fine but I am not able to run the app on ubuntu after installing through deb file. It works for AppImage but not deb.

**Comment by makeitcount** [comment]
@develar Is there any known issue with creating deb packaging with electron-builder? 
I am not able to start app after installing through deb package, while it works fine with AppImage?

**Comment by develar** [comment]
@makeitcount Please see #786.

**Comment by Boid-John** [comment]
Hello, I am facing this same issue.

> Issue is that when I build executable and run it, the app installs correctly and starts on first instance. When I close the app and start it again, it doesn't work, app does not get launched.

I believe that I am handling squirrel and app.quit() events correctly:

`if (require('electron-squirrel-startup')) app.quit()
`

and

```
var cleanUp = function(event) {
  if (appWindow) appWindow.close()
  // app.quit()
}

app.on('before-quit', cleanUp)
```

The application works as expected in dev mode and also when running the packaged exe directly (before it's packed into the squirrel installer). 
The problem is only apparent when running the squirrel installed application.
