### ISSUE TITLE
electron-builder build and install, run with error Cannot read property '_android' of undefined

### ISSUE THREAD

**Issue by wuhaodes** [electron-userland/electron-builder#7881]
"vue-cli-plugin-electron-builder": "~2.1.1",
"electron": "^13.0.0",
"electron-devtools-installer": "^3.1.0",
"vue": "2.6.12",
node -v
// v16.18.0
Target: win32

a old vue management item, use vue add electron-builder and select electron@13.0, when add finished, run electron:serve, it's run very well; and run electron:build, the exe file has been output; but when install this file, and run, it's export the error [Cannot read property '_android' of undefined]

**Comment by mmaietta** [comment]
That's an error in your code, `_android` isn't anywhere in the electron-builder codebase. Also, I'm not sure what version of electron-builder the vue-cli plugin is using, I'd recommend using a direct implementation of electron-builder if it isn't on the most recent versions of electron-builder.

**Comment by wuhaodes** [comment]
can I use electon-builder directly to transform a old Vue project to Desketop app, I will try use it directly

**Comment by wuhaodes** [comment]
I think this error is caused by the window or dom can't be reached, which cause the other dependencies can't run correctly

**Comment by wuhaodes** [comment]
may be the vue-cli-plugin-electron-builder used too old electron builder

**Comment by wuhaodes** [comment]
![image](https://github.com/electron-userland/electron-builder/assets/17507141/5f39f3d6-4497-46c2-a631-c54b23bea463)
I see the the vue-cli-plugin-electron-builder  use the version ^22.2.0 electron-builder

**Comment by wuhaodes** [comment]
![image](https://github.com/electron-userland/electron-builder/assets/17507141/270627fa-827f-4dc4-bfb3-7c119155031c)
I have installed the electron-builder directly, but find it's only two big version gap of generations

**Comment by wuhaodes** [comment]
![image](https://github.com/electron-userland/electron-builder/assets/17507141/960cd7a7-d371-4b2d-be72-1d356d630584)
I find this error was poped by qrcodejs2, I will try to remove it

**Comment by wuhaodes** [comment]
when I removed qrcodejs2, it's worked
