### ISSUE TITLE
error LGHT0094 : The identifier 'Icon:FirstElectronAppIcon.exe' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

### ISSUE THREAD

**Issue by niyazpk07** [electron-userland/electron-builder#7892]
Hi,

I have limited experience with ElectronNET, and I'm currently encountering an issue. I successfully created a basic Electron app using a Blazor server project. However, I'm now facing an error while attempting to generate an MSI executable using Electron-Builder. I'm unsure about the solution to this problem and would greatly appreciate your assistance.

**Error:**

`PS C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp> npm run build

> my-electron-app@1.0.0 build
> electron-builder

  • electron-builder  version=24.6.4 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
PS C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp> npm run build

> my-electron-app@1.0.0 build
> electron-builder

  • electron-builder  version=24.6.4 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=27.1.0 appOutDir=dist\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=MSI arch=x64 file=dist\my-electron-app 1.0.0.msi
  • building        target=zip arch=x64 file=dist\my-electron-app-1.0.0-win.zip
  ⨯ Exit code: 94. Command failed: C:\Users\niyas.pk\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\my-electron-app 1.0.0.msi -v -spdb -sw1076 -dappDir=C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\win-unpacked -pedantic -wx project.wixobj
C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\__msi-x64\project.wxs(91) : error LGHT0094 : The identifier 'Icon:myelectronappIcon.exe' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

WiX Toolset Linker version 4.0.0.5512
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\__msi-x64\project.wxs(91) : error LGHT0094 : The identifier 'Icon:myelectronappIcon.exe' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.
  failedTask=build stackTrace=Error: Exit code: 94. Command failed: C:\Users\niyas.pk\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\my-electron-app 1.0.0.msi -v -spdb -sw1076 -dappDir=C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\win-unpacked -pedantic -wx project.wixobj
C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\__msi-x64\project.wxs(91) : error LGHT0094 : The identifier 'Icon:myelectronappIcon.exe' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

WiX Toolset Linker version 4.0.0.5512
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\dist\__msi-x64\project.wxs(91) : error LGHT0094 : The identifier 'Icon:myelectronappIcon.exe' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

    at C:\Users\niyas.pk\source\repos\ElectronApplications\FirstElectronApp\node_modules\builder-util\src\util.ts:133:18
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)`

**package.json**

`{
  "name": "my-electron-app",
  "version": "1.0.0",
  "description": "My Electron application",
  "main": "main.js",
  "author": "Annax",
  "license": "MIT",
  "devDependencies": {
    "electron": "^27.1.0",
    "electron-builder": "^24.6.4"
  },
  "scripts": {
    "start": "electron .",
    "build": "electron-builder"
  },
  "build": {
    "appId": "com.FirstElectronApp.app",
    "directories": {
      "output": "dist"
    },
    "win": {
      "target": [ "msi", "zip" ]
    }
  }
}
`

**electron.manifest.json**

`{
  "executable": "FirstElectronApp",
  "splashscreen": {
    "imageFile": ""
  },
  "name": "FirstElectronApp",
  "icon": "wwwroot/Icon.ico",
  "author": "Niyaz",
  "description": "My Electron application",
  "singleInstance": false,
  "environment": "Production",
  "build": {
    "appId": "com.FirstElectronApp.app",
    "productName": "FirstElectronApp",
    "copyright": "Copyright © 2020",
    "buildVersion": "1.0.0",
    "compression": "maximum",
    "icon": "icon.ico",
    "directories": {
      "output": "../../../bin/Desktop"
    },
    "extraResources": [
      {
        "from": "./bin",
        "to": "bin",
        "filter": [ "**/*" ]
      }
    ],
    "files": [
      {
        "from": "./ElectronHostHook/node_modules",
        "to": "ElectronHostHook/node_modules",
        "filter": [ "**/*" ]
      },
      "**/*"
    ],
    "win": {
      "target": [ "msi" ],
      "icon": "icon.ico"
    },
    "msi": {
      "oneClick": false
    }
  }
}`

**Files inside my solution:**

<img width="260" alt="image" src="https://github.com/electron-userland/electron-builder/assets/8319413/17a8f80e-4c85-41f5-a373-fff6446ae12f">

**Comment by mmaietta** [comment]
How is `electron.manifest.json` being used? I don't see it anywhere in the electron-builder codebase

**Comment by ismoil793** [comment]
Hi @niyazpk07 did you resolve the problem? I am having a similar issue

**Comment by alicestoneprod** [comment]
![image](https://github.com/electron-userland/electron-builder/assets/126640746/faf84b94-7bf5-4ad8-947b-b1f6100dd388)
How to fix it??

**Comment by ismoil793** [comment]
@alicestoneprod let me know if you find the answer

**Comment by alicestoneprod** [comment]
> @alicestoneprod let me know if you find the answer

![image](https://github.com/electron-userland/electron-builder/assets/126640746/9a52cef8-03b1-460f-ab88-961cd0bacafd)

just add path to ico)

**Comment by ismoil793** [comment]
@alicestoneprod I did, I guess my problem is different

This is what I have today with electron v14 and it works there, 
I would like to migrate the latest version but getting this "error LGHT0094"

Anyways thanks for the response

```
    "win": {
      "target": [
        "nsis",
        "msi"
      ],
      "icon": "images/icon.ico",
      "artifactName": "${productName}-${version}.${ext}"
    },
```

**Comment by alicestoneprod** [comment]
> @alicestoneprod I did, I guess my problem is different
> 
> This is what I have today with electron v14 and it works there, I would like to migrate to the latest version but getting this "error LGHT0094"
> 
> Anyways thanks for the response
> 
> ```
>     "win": {
>       "target": [
>         "nsis",
>         "msi"
>       ],
>       "icon": "images/icon.ico",
>       "artifactName": "${productName}-${version}.${ext}"
>     },
> ```

my settings
```
"build": {
    "appId": "com.dnpak.alicemor.app",
    "productName": "DNPak",
    "directories": {
      "output": "build",
      "buildResources": "assets"
    },
    "files": [
      "script/**/*",
      "index.js",
      "*.js",
      "*.css",
      "*.html",
      "assets/**/*"
    ],
    "nsis": {
      "allowToChangeInstallationDirectory": true,
      "oneClick": false
    },
    "msi": {
      "oneClick": false,
      "perMachine": true,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true
    },
    "win": {
      "target": "nsis",
      "icon": "assets/lencea.ico"
    }
  }
```
