### ISSUE TITLE
Suggestions for simplifying Mac notarization docs

### ISSUE THREAD

**Issue by tuliomir** [electron-userland/electron-builder#7893]
While trying to update the notarization configs for electron builder I got quite confused trying to understand which parameters I should use where. Below I grouped some suggestions to improve on the current state of the docs, based on my recent experience:

#### Move _legacy_ notarization instructions to a comment or note block
Starting November 1, 2023, Apple no longer accepts notarizations made with the legacy mode ( [Apple docs](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) ). That way, the instructions shown on the `electron-builder` docs ( [relevant page](https://www.electron.build/configuration/mac#MacConfiguration-notarize) ) should highlight the modern way to implement this.

A note to help with legacy troubleshooting could be left after the main text for the `notarize` property.

#### Example configs
I had to search into [the source code](https://github.com/electron-userland/electron-builder/blob/6b84010b67de0ddc07404d53436bbfbfa2761f88/packages/app-builder-lib/src/macPackager.ts#L535-L564) for `macPackager.ts` to understand that all I needed to inform was `"notarize": { "teamId": "xxxx" }`. The links offered on the [builder docs](https://www.electron.build/configuration/mac#MacConfiguration-notarize) pointed to the programmatic way to call `@electron/notarize`, and not the JSON configurations for the builder itself. This added to the confusion, since each has its own set of parameters.

I suggest adding a config example to help with the simplest path, and then the developer can troubleshoot from there if necessary. In my case, simply an object with the `teamId`.

#### Links to the types
Even though the docs already mention `module:app-builder-lib/out/options/macOptions.NotarizeLegacyOptions | module:app-builder-lib/out/options/macOptions.NotarizeNotaryOptions`, I would suggest simplifying this with links. An example below:

> [NotarizeLegacyOptions](https://github.com/electron-userland/electron-builder/blob/6b84010b67de0ddc07404d53436bbfbfa2761f88/packages/app-builder-lib/scheme.json#L3881-L3900) | [NotarizeNotaryOptions](https://github.com/electron-userland/electron-builder/blob/6b84010b67de0ddc07404d53436bbfbfa2761f88/packages/app-builder-lib/scheme.json#L3901-L3913) | Boolean | “undefined” - Options to use for @electron/notarize (ref: https://github.com/electron/notarize). Supports both legacy and notarytool notarization tools. Use false to explicitly disable

#### Bullet points on environment variables description
The explanation on env variables currently have a `\n` characters instead of a line break. This is probably just a typo.

**Comment by mmaietta** [comment]
Updated the docs to explicitly list those Options out. Thanks for surfacing the topic :) 
https://www.electron.build/configuration/mac
