### ISSUE TITLE
PORTABLE_EXECUTABLE_DIR is blank/not set on MacOs 10.x when using dmg or .app

### ISSUE THREAD

**Issue by eolasd** [electron-userland/electron-builder#7894]
* **Electron-Builder Version**: 24.6.4

* **Node Version**: v18.15.0

* **Electron Version**:26.6.1
* **Electron Type (current, beta, nightly)**:

* **Target**: macos (portable/dmg)

I am trying to get the executable path of the .app or dmg file during startup.

I have tried to use ```process.env.PORTABLE_EXECUTABLE_DIR``` but it is blank/null on MacOs v10.13.x
All other path vars resolve to to the /private folders...
```
__dirname = /private/var/folders/fp/........

```

We are trying to build a portable app that does not require installation. 

I am currently testing on an older macbook ( os v10.13), unfortunately I do not have a more recent mac to test on.

Electron-builder runs using github actions, using this build file::
-----
```
....
  "icon": "./assets/icon.png",
    "files": [
        "**/**",
        "!**node_modules**"
    ],
    "artifactName": "${productName}-${arch}-${version}.${ext}",
    "directories": {
        "output": "./dist/"
    },
    "npmRebuild": false,
    "publish": {
        "provider": "github"
    },
    "mac": {
        "category": "public.app-category.medical",
        "target": [
            { "target": "zip", "arch": [
                "x64",
                "arm64"
            ]
            },
            { "target": "dmg", "arch": [
                "x64",
                "arm64",
                "universal"
            ]
            }
        ]
    },
    "dmg": {
    },
    "portable": {
        "artifactName": "${productName}-${version}-mac-portable.${ext}"
    }
.....
```

Is PORTABLE_EXECUTABLE_DIR supported/used on MacOs targets?
Are there some other settings I should be using my build config to enable a portable mac app that can read from its EXECUTABLE directory (ie. NOT the extraction/app data folders, but from the original source it was clicked like a USB drive or DVD)

Thanks.

**Comment by mmaietta** [comment]
`PORTABLE_EXECUTABLE_DIR` only exists on Windows portable apps IIRC

**Comment by eolasd** [comment]
Yep, Portable only seems to work on Windows. 

Ended up with something like this... bit messy, but it works on a new Mac and older 10.13.x MacOs.

  ```js
  if (isWin) {
        return process.env.PORTABLE_EXECUTABLE_DIR || __dirname;
    }
    if (isMac) {
        if (process.env.NODE_ENV === 'development') return __dirname;

        // If app uses asar archive or on mac, we need to go up two or more level to get root executing path.
        const appNoAsarPath = ['Contents', 'Resources', 'app']; 
        const appAsarPath = ['Contents', 'Resources', 'app.asar']; 

        const pathMatchesApp = getHigherPathIfExactMatch(__dirname, appNoAsarPath);
        const pathMatchesAppAsar = getHigherPathIfExactMatch(__dirname, appAsarPath)

        if (pathMatchesApp !== null || pathMatchesAppAsar !== null) {
            applog.log("App path - " + path.join(__dirname, '../../../../'));

            return path.join(__dirname, '../../../../');
        } else return __dirname;

    } else return __dirname;
    ```
