### ISSUE TITLE
Process of starting a packaged app/signing runtime chromium instance

### ISSUE THREAD

**Issue by malinka-2233** [electron-userland/electron-builder#7906]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.10.0

* **Electron Version**: 22.3.25
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux deb

Hey. I am re-packaging https://github.com/brimdata/zui for my own needs and it works just fine, package works.
Problem is - i need all of the elf binaries on my system - signed. (basically with this https://github.com/digsig-ng/bsign-mirror , i dont think the process is that important)  I sign all the binaries in the package, but there is a problem - on runtime, when i start the ${packagename} binary it produces a chromium bin at /tmp/.org.chromium.Chromium.YzFLzi. And since its not signed - start fails. 
My question is - where can i look to understand the start process of the packaged app, what produces this chromium bin (i assume electron itself) and how can i interact with it? (and will there be any other surprise runtime binaries like this?)

**Comment by mmaietta** [comment]
If electron is producing that file (which is a file I'm not familiar with), then there's nothing electron-builder can do from a signing perspective as electron-builder is just a packager, not executed at runtime. It might be worth opening a github issue with the electron project itself
