### ISSUE TITLE
Custom Windows Signing does not work when signing to a different location

### ISSUE THREAD

**Issue by sdesmond46** [electron-userland/electron-builder#7910]
* Electron-Builder Version****:  24.4.0

* **Node Version**: 18.15.0 

* **Electron Version**: 25.8.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows 

When providing a custom sign function to the windows config section you have the option to set a [`resultOutputPath`](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L32C3-L32C19) which is then supposed to be copied over the original file by electron-builder. However, where the actual sign function is called the object is passed using the [spread operator](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L61-L64) which means you are modifying a copy of the context instead of the context itself. This then means that you never have a value for `resultOutputPath` set where the [renaming](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L69-L71) is supposed to happen. 

Minimal repo:
```
  win: {
    signingHashAlgorithms: ['sha256'],
    sign: async (context) => {
      // This should cause a failure when copying the file but it does not
      context.resultOutputPath = 'foo';
    },
    target: ['nsis'],
  },
```

**Comment by mmaietta** [comment]
Nice find! Would you be willing to open a PR with the needed changes?
