### ISSUE TITLE
[Electron-Updater] Release date of GithubProvider should be `release.published_at` instead of `asset.updated_at`

### ISSUE THREAD

**Issue by Keith-CY** [electron-userland/electron-builder#7912]
* **Electron-Builder Version**: 23.6.0
* **Node Version**: 18.17.0
* **Electron Version**: 24.8.8
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater**: 4.6.5, but I've read the code and found it's a logical issue.
* **Target**: Windows, MacOS, Linux

The `updateInfo.releaseDate` returned in `autoUpdater.on('update-available, (info) => void)`(https://github.com/electron-userland/electron-builder/blob/512fb9ea0fd42158ee86d2989c3b8e1be0876ae7/packages/electron-updater/src/AppUpdater.ts#L457) is incorrect.
`release.published_at` is expected to be returned, but `asset.updated_at` is returned in fact.

---

### Issue detail

Take my app as the example:

#### Release on Github: https://api.github.com/repos/nervosnetwork/neuron/releases/tags/v0.111.1

```json
{
  "published_at": "2023-11-08T00:00:02Z"
}
```

#### Update Info from `electron-builder`
```bash
[1] version: 0.111.1
# ...
[1] releaseDate: '2023-11-07T15:55:58.007Z'
```
<img width="1555" alt="Pasted Graphic 26" src="https://github.com/electron-userland/electron-builder/assets/7271329/d08cb5cc-9299-4429-9b48-566733a6227f">

The release date returned by **electron updater** is actually the **upload time of assets** https://api.github.com/repos/nervosnetwork/neuron/releases/assets/134382357

```json
{
  "updated_at": "2023-11-07T15:55:58Z"
}
```

It comes from https://objects.githubusercontent.com//github-production-release-asset-2e65be/165770137/01980fb8-f910-4120-bba1-807f79dc5d57?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=... (URL truncated because it includes `credential`, it points to such a file [latest-mac.yml.zip](https://github.com/electron-userland/electron-builder/files/13515059/latest-mac.yml.zip))

Obviously, the request returns info of **github-production-release-asset**, not the release.

### Expectation

`release.published_at` is returned as the `releaseDate` field.

**Comment by mmaietta** [comment]
I would actually argue against using `published_at` as a release can have assets updated and we'd want to trigger the update based on whether the latest assets are installed, right?

**Comment by Keith-CY** [comment]
> I would actually argue against using `published_at` as a release can have assets updated and we'd want to trigger the update based on whether the latest assets are installed, right?

Make sense, I should treat git tag and its artifacts separately because they are not always matched. 👍
