### ISSUE TITLE
App cannot install success when build in Jenkins

### ISSUE THREAD

**Issue by yijialee** [electron-userland/electron-builder#7917]
* **Electron-Builder Version**:  22.14.5 -  latest

* **Node Version**:  16.6

* **Electron Version**: 16.0.5 - latest
* **Electron Type (current, beta, nightly)**:

* **Target**:  linux  arm64 deb 

build on deb linux x86/64, when I build use `npm run build` in terminal, the result app will be installed success .
If I build in jenkins, App cannot install success .

**Comment by mmaietta** [comment]
Please try `latest` or even `next` version of electron-builder. We're at [v24.9.3](https://github.com/electron-userland/electron-builder/releases/tag/v24.9.3)

Also, this sounds more like a build environment issue, such as some transient dependencies that need to be present to run the app. Please try debugging further in your environment when trying to install the app. This seems highly unlikely related to electron-builder.
