### ISSUE TITLE
Update installation fails on macOS because of EACCES

### ISSUE THREAD

**Issue by raphaelmenges** [electron-userland/electron-builder#7918]
* **Electron-Builder Version**: 24.9.1
* **Electron-Updater Version**: 6.1.7
* **Node Version**: 18.18.2
* **Electron Version**: 27.1.3
* **Electron Type (current, beta, nightly)**: current
* **Target**:  macOS (arm64)

Hello developers 👋

I am trying to deploy our application for macOS. After quite some debugging, I managed to sign, notarize and setup the app and the updater. Everything works but the final step in installing the downloaded update. The log is as follows:

```
[2023-12-04 16:55:25.545] [info]  Install on explicit quitAndInstall
[2023-12-04 16:55:25.547] [info]  Install: isSilent: false, isForceRunAfter: false
[2023-12-04 16:55:25.548] [info]  Executing: /Users/<user-name>/Library/Caches/app-updater/pending/App-1.0.1-arm64-mac.zip with args: --updated
[2023-12-04 16:55:25.549] [info]  Cannot run installer: error code: EACCES, error message: "spawn /Users/<user-name>/Library/Caches/app-updater/pending/App-1.0.1-arm64-mac.zip EACCES", will be executed again using elevate if EACCES, and will try to use electron.shell.openItem if ENOENT
[2023-12-04 16:55:25.549] [info]  Executing: /Applications/App.app/Contents/Resources/elevate.exe with args: /Users/<user-name>/Library/Caches/app-updater/pending/App-1.0.1-arm64-mac.zip,--updated
[2023-12-04 16:55:25.550] [error] Error: Error: spawn /Applications/App.app/Contents/Resources/elevate.exe ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
I am highly confused why the updater attempts to run `elevate.exe` on a Mac!

Following some suggestions from an [ancient issue](https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-306709572), I have implemented the update installation process as follows:

```
setImmediate(() => {
  app.removeAllListeners("window-all-closed");
  for(const window of BrowserWindow.getAllWindows()) {
    window.close();
    window.destroy();
  }
  setTimeout(() => updater.quitAndInstall(false), 1000);
});
```
I have tested many different variations of this approach, e.g., with and without timeout. Updates on Windows work fine! Any hint or ideas?

**Comment by mmaietta** [comment]
That's super bizarre! The only way that could happen is if it were in the NSISUpdater.ts
https://github.com/electron-userland/electron-builder/blob/4497e865ca653d1986ef2871b3db4e3e61f5167a/packages/electron-updater/src/NsisUpdater.ts#L159-L163

How are you fetching the autoUpdater?

**Comment by raphaelmenges** [comment]
Hello @mmaietta!

Can you elaborate what you mean by "fetching"?

To check about NSIS influence, I have even set its configuration to `false`. The error persists. Here is a simplified variant of my `electron-builder` configuration:

```js
return {
    productName: `app`,
    appId: `com.company.app`,
    publish: [{
      provider: "generic",
      url: "",
      channel: "latest",
    }],
    forceCodeSigning: true,
    directories: {
      output: "dist",
      buildResources: "resources",
    },
    files: ["packages/**/dist/**"],
    electronUpdaterCompatibility: ">= 2.16",
    mac: {
      category: "public.app-category.utilities",
      target: {
        target: "default",
        arch: process.env.ARCH !== undefined ? process.env.ARCH : "x64",
      },
      hardenedRuntime : true,
      gatekeeperAssess: false,
      entitlements: "resources/entitlements.mac.plist",
      entitlementsInherit: "resources/entitlements.mac.plist",
      notarize: {
        teamId: process.env.APPLE_TEAM_ID !== undefined ? process.env.APPLE_TEAM_ID : "",
      }
    },
    win: false,
    nsis: false,
    asar: true,
  };
```

**Comment by raphaelmenges** [comment]
I now believe that I understood your comment and found out that the updater object I had created was indeed a `NsisUpdater` for both, Windows and macOS. After using the `MacUpdater` on macOS, the auto update finally worked! Including auto-start of the app after update. 🎉

I could even remove the workarounds from the [ancient issue](https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-306709572).

Thank you very much!

**Comment by mmaietta** [comment]
Related note, if you use this, electron-updater will automatically provide the correct updater instance for you per-OS
```
import { autoUpdater } from 'electron-updater'
```
https://github.com/electron-userland/electron-builder/blob/4497e865ca653d1986ef2871b3db4e3e61f5167a/packages/electron-updater/src/main.ts#L61-L66
https://github.com/electron-userland/electron-builder/blob/4497e865ca653d1986ef2871b3db4e3e61f5167a/packages/electron-updater/src/main.ts#L27-L32
