### ISSUE TITLE
Electron Updater with Bitbucket private repo

### ISSUE THREAD

**Issue by andrepnunes** [electron-userland/electron-builder#7920]
* **Electron-Builder Version**:  24.3.6

* **Node Version**:  16.20.1

* **Electron Version**: 25.3.1
* **Electron Type (current, beta, nightly)**: current

* **ElectronUpdater**: 6.1.7

* **Target**:  22.04.1 Ubuntu

I am trying to use electron updater to upload my software's releases to Bitbucket but I cannot connect to it.
I run into this error:
```
⨯ 401 Unauthorized
"method: POST url: https://api.bitbucket.org/2.0/repositories/<owner>/<repo_name>/downloads\n\n          Data:\n          \n          "
Headers: {
  "server": "envoy",
  "www-authenticate": "Basic realm=\"Bitbucket.org HTTP\"",

```

i added this to my package.json
```
"publish": [
      {
        "provider": "bitbucket",
        "owner": "<owner>",
        "username": "<username>",
        "channel": "latest",
        "slug": "<repo_name>",
        "token": "Basic <token>"
      }
    ]
```
I generated my token as it is explained in the documentation but i still get the 401 error.
Also, if i send the POST request myself, with the same token, it works.

How can i see the request that is actually being sent and fix this?

**Comment by BaraoVlask** [comment]
You need to create a APP password in https://bitbucket.org/account/settings/app-passwords/ in you account. (bad docs)

**Comment by andrepnunes** [comment]
Thx for your answer
yes i did create a password

i also generated a token using that same password as mentioned in the [docs](https://www.electron.build/configuration/publish.html#bitbucketoptions)
```
convertAppPassword(owner: string, appPassword: string) {
const base64encodedData = Buffer.from(`${owner}:${appPassword.trim()}`).toString("base64")
return `Basic ${base64encodedData}`
}
```

i know that the token works because i tested it with Postman.
I built the request manualy and i managed to upload a file.
but i cant do it with electron and i cant see what the request looks like

**Comment by mmaietta** [comment]
Is your `owner` and `username` different? Try setting `username` to the same value as `owner`

**Comment by andrepnunes** [comment]
ok i rechecked my parameters and i found the issue.

on the token field i wrote token: "Basic <token>"
where the value <token> was generated, as stated in the [docs](https://www.electron.build/configuration/publish.html#bitbucketoptions), by encoding my username and app password in base 64

However, it seems that your library already does this with this function

    static convertAppPassword(username, token) {
        const base64encodedData = Buffer.from(`${username}:${token.trim()}`).toString("base64");
        return `Basic ${base64encodedData}`;
    }

So, Bitbucket users should put their AppPassword on the Token field instead of the actual request token.

**Comment by mmaietta** [comment]
That code is for handling authentication in the updater, not for publishing.

The docs state that as such:
> token String | “undefined” - The **app password (account>settings>app-passwords)** to support auto-update from private bitbucket repositories.

**Comment by andrepnunes** [comment]
you're right my bad

**Comment by dansoalv** [comment]
> y b
 @andrepnunes I have the same issue, you can find a fix or solution about it?

**Comment by andrepnunes** [comment]
The solution is to put the Bit bucket AppPassword directly on the token field like so:
```
"publish": [
      {
        "provider": "bitbucket",
        "owner": "<owner>",
        "username": "<username>",
        "channel": "latest",
        "slug": "<repo_name>",
        "token": "<app password>"
      }
    ]
```

**Comment by Reddeck** [comment]
@andrepnunes How did you manage to implement autoUpdater in main.js, to check for updates inside your electron executable?

**Comment by andrepnunes** [comment]
@Reddeck 
this is what i added to my main.js:
```
import { autoUpdater } from "electron-updater"

  // The project name on package.json MUST NOT have whitespaces
  // Basic auth: token generated by creating bitbucket app_password and encoding it in base 64 -> base64(username:app_password)
  autoUpdater.addAuthHeader('Basic <my_token>');

  autoUpdater.checkForUpdatesAndNotify()
```

**Comment by Reddeck** [comment]
@andrepnunes 
Thanks for the quick reply! It was easier than expected.
I was confused as the docs for "autoUpdate" don't explicitly state that Bitbucket is supported out-of-the-box as it is the case with GitHub.
However, it apparently does support it fully. Thanks again for the help :D

**Comment by andrepnunes** [comment]
According to my google search that error happens with slow connections.
I assume the timeout is not related to the size of the file (it is probably related to each http packet or smth)
My file is 98MB and it worked. is your file bigger?

I'd recommend you to make sure the problem is not from your internet connection.

I'd also recommend you to try your request with Postman.
Create a request, choose basic Auth, put your username and app password there
![image](https://github.com/electron-userland/electron-builder/assets/58053186/8a7cd197-7b05-496e-975a-b098870324f3)

On the body of the message choose form-data, upload your file and see what you get
![image](https://github.com/electron-userland/electron-builder/assets/58053186/9b593afa-d822-4a5d-a781-d6517a99378a)

**Comment by mmaietta** [comment]
Maybe you can also try adding a longer `timeout` value to the publisher config to test the timeout hypothesis
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/publish/BitbucketPublisher.ts#L52

**Comment by andrepnunes** [comment]
this is just a guess but maybe it is because of your whitespaces.

I think you named your file "xxxx Setup 2.1.2.exe" and the url becomes "xxx%20Setup%202.1.2.exe"
that might be why it isnt found.

Try to avoid white spaces in general when you code.
Try naming your file like this "xxxx_Setup_2.1.2.exe" and tell us if it works.

**Comment by andrepnunes** [comment]
i don't think so. i haven't tested on windows either, i only use linux sry
