### ISSUE TITLE
Docs suggestion

### ISSUE THREAD

**Issue by BaraoVlask** [electron-userland/electron-builder#7922]
https://github.com/electron-userland/electron-builder/blame/4e930a74d7c2e9b53d47e37997b444da95680a24/docs/configuration/publish.md#L260

Will be easier to have this link https://bitbucket.org/account/settings/app-passwords/ instead of this text (account&gt;settings&gt;app-passwords)

**Comment by mmaietta** [comment]
Feel free to open a PR with that change please 🙂
