### ISSUE TITLE
I have issues when I tried to build cordova-electron : TypeError: The "code" argument must be of type number

### ISSUE THREAD

**Issue by BenLaKnet** [electron-userland/electron-builder#7923]
* **Electron-Builder Version**: electron-builder  version=22.14.13 os=10.0.19045

* **Node Version**: v20.10.0

* **Electron Version**: Cordova electron 3.1.0
* **Electron Type (current, beta, nightly)**:

* **Target**:  windows

I have this error message when building app :

```
cordova build electron --release
  • electron-builder  version=22.14.13 os=10.0.19045
  • writing effective config  file=platforms\electron\build\builder-effective-config.yaml
TypeError: The "code" argument must be of type number. Received type string ('ERR_ELECTRON_BUILDER_INVA...')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at c:\Users\xxxx\AppData\Roaming\npm\node_modules\cordova\bin\cordova:32:22
```

Please help me.

**Comment by mmaietta** [comment]
Please try a newer version of electron-builder. I'm unable to provide for support for older versions
We're currently on `24.9.x`

**Comment by BenLaKnet** [comment]
Many thanks @mmaietta,

I tried to update cordova electron-builder, but I do not know how to do that.

**Comment by BenLaKnet** [comment]
If I am running : >electron-builder directly,

I obtain this error message:

```
  • electron-builder  version=24.9.1 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=14.2.9 appOutDir=dist\win-unpacked
  ⨯ Application entry file "index.js" in the "c:\xxx\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "index.js" in the "c:\xxx\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
```

**Comment by BenLaKnet** [comment]
I found, I have to go to app project/platforms/electron to use : electron-builder.

**Comment by BenLaKnet** [comment]
I found, I have to go to app project/platforms/electron to use : electron-builder.

**Comment by BenLaKnet** [comment]
I found, I have to go to app project/platforms/electron to use : electron-builder.
