### ISSUE TITLE
File access after building

### ISSUE THREAD

**Issue by justijndepover** [electron-userland/electron-builder#793]
* electron: ^1.4.2
* electron-builder: ^7.9.0
* Operating system: macOS Sierra

Inside my app I have a link to open up an external pdf file. For this to work properly I send a message with IPC from my render process to my main process. 

inside my main I have 
```
ipcMain.on('open_file', function(event, file){
    shell.openItem(__dirname + file);
})
```

inside my render process i have 
```
$('.open_file').on('click', function(event){
    event.preventDefault();

    var url = $(this).data('url');
    ipcRenderer.send('open_file', url)
})
```

When i use `npm start` to run my application everything works fine. But when i build my app with electron-builder nothing happens when I try to open the file. No errors show up in my console. 
Am I doing something wrong with my paths? Or could it be that the electon-builder does not include the pdf's to my package? They live inside my `app` directory

**Comment by develar** [comment]
Probably it is packed into asar and cannot be accessed externally. Please use https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources (see #751).

**Comment by justijndepover** [comment]
Is it also possible to add a rule in my package.json build to unpack the file?
```
"asar.unpack" : "/app/*/document/*.pdf",
```
The files are located as following: 
```
/app/nl/document/jaydess-notice.pdf
/app/nl/document/mirena-notice.pdf
/app/fr/document/jaydess-notice.pdf
/app/fr/document/mirena-notice.pdf
```
 Excuse me if I ask stupid questions but i don't really understand the asar packaging.

**Comment by develar** [comment]
@justijndepover Please do not use `asar.unpack`. It is supported, but I strongly advice you to use more smart and more user-friendly [extraResources](https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources) or `extraFiles`.

e.g.: 
```json
"build": {
  "extraResources": "app/*/document/*.pdf"
}
```

**Comment by justijndepover** [comment]
Thanks, that worked!

**Comment by develar** [comment]
Solution — `pdf` files should be not packed to asar automatically.
