### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by lutzroeder** [electron-userland/electron-builder#7935]
* **Electron-Builder Version**: 24.9.1
* **Node Version**: 21.4.0
* **Electron Version**: 28.0.0
* **Target**: macOS

1. Set `package.json` to `type: module`.
2. Create `afterSign: notarize.js` using ESM imports.
3. Run `npx electron-builder --mac --universal --publish never`.

```
⨯ require() of ES Module ~/Projects/Test/notarize.js from ~/Projects/Test/node_modules/app-builder-lib/out/platformPackager.js not supported.
Instead change the require of notarize.js in ~/Projects/Test/node_modules/app-builder-lib/out/platformPackager.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by omarabdula** [comment]
@lutzroeder  HELLO DID YOU MANAGE TO FIND A SOLUTION?

**Comment by briantolsen** [comment]
Running into this issue now as well using 24.13.3

**Comment by mmaietta** [comment]
So the current code detects if the package.json is of type `module`, but it automatically has a fallback of `require` from the `try-catch` logic
https://github.com/electron-userland/electron-builder/blob/29f6504e181cef2c43ac070a80f24ee79dc52481/packages/app-builder-lib/src/platformPackager.ts#L775-L787

It should be fully functional for handling both ES and CJS modules in the `next` alpha version, would you mind giving it a try?

**Comment by leo4life2** [comment]
> Running into this issue now as well using 24.13.3

added some debug logs to platformPackager.js today, and turns out that the try part failed not because it's not an es module, but because there's bugs in my `notarize.js`'s code, so it threw exceptions on import. for me it was because i gave bad arguments to the `notarize` function.

Here's my working `afterSign` script:
```
import { notarize } from '@electron/notarize';

export default async function afterSign(context) {
  const { appOutDir, electronPlatformName } = context;

  if (electronPlatformName !== 'darwin') {
    return;
  }

  const appName = context.packager.appInfo.productFilename;

  await notarize({
    appPath: `${appOutDir}/${appName}.app`,
    appleApiKey: '~/private_keys/notarize.p8', // Path to your .p8 file
    appleApiKeyId: process.env.API_KEY_ID,
    appleApiIssuer: process.env.API_KEY_ISSUER_ID,
  });
}
```

**Comment by mmaietta** [comment]
@leo4life2 that's a great callout and something I'll implement.

Do you recall what the error message you were receiving? Was it `Unable to dynamically import hook, falling back to "require"` or an error being thrown during the fallback `require` statement?

**Comment by mmaietta** [comment]
Added better logging in https://github.com/electron-userland/electron-builder/pull/8356
