### ISSUE TITLE
How to use electron-builder with Webpack bundled files?

### ISSUE THREAD

**Issue by gmantri** [electron-userland/electron-builder#794]
* **7.10.2**: 

* **Windows**: 

I'm trying to understand how can I use electron-builder to use bundled files? I'm building a desktop app using Electron and React.JS. I'm using Webpack to transpile JSX/JS code into ES5 and create bundles for JS and CSS files. During development, I simply refer to these files in my main.html file which is called by "index.js" file (entry point into the application). 

This is what my main.html file looks like:

```
<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <link rel="stylesheet" href="./app.css" />
</head>
<body id="AppBody">
  <div id="Main"></div>
</body>
</html>
<script>if (typeof module === 'object') {window.module = module; module = undefined;};</script>
<script type="text/javascript" src="bundle.js"></script>

```

All the examples I have seen make use of "app" folder where the application code is stored. From the documentation I read (and understood), it is my understanding is that electron-builder will use the files in the "app" folder and create an executable application. So what I did is have Webpack create a bundle for JS file (called bundle.js) and put that in "app" folder. For testing purposes, I had manually put in "main.html" and "index.js" files in this folder along with "package.json". Here's what my package.json file looks like in "app" folder:

```
{
    "name": "ApplicationName",
    "description": "ApplicationDescription.",
    "version": "1.0.0",
    "author": "Me",
    "main": "index.js"
}

```

Here's what my package.json file ("build" element) looks like in application root folder:

```
  "build": {
    "appId": "my.id",
    "asar": false,
    "win": {
      "msi": true
    }
  },

```

The application builds fine however when I run the application, nothing but a blank window appears. It appears to me that "bundle.js" is not launched.

Are there any tutorials or guides available that talk about how to use bundled js files? Any help regarding this would be highly appreciated.

**Comment by develar** [comment]
Does it work before package? Please see https://github.com/szwacz/electron-boilerplate as an example of preprocessed js files.

**Comment by gmantri** [comment]
@develar Thank you so much for the response (and apologies for the delay in replying back). The link you shared is exactly what I needed.
