### ISSUE TITLE
Codesigning for mac in circleci is not happening

### ISSUE THREAD

**Issue by reddybhavanish** [electron-userland/electron-builder#7944]
<img width="742" alt="image" src="https://github.com/electron-userland/electron-builder/assets/98303580/2e241cda-9a5b-43e0-9cf3-c50de0d24e05">

Please refer to the above image.

**Comment by mmaietta** [comment]
We call `electron/osx-sign` package directly, anything hanging there can be debugged with `DEBUG=electron-osx-sign`
https://github.com/electron/osx-sign/blob/162b053ac5d3e03790fc81d44fe66157c665272a/src/util.ts#L9C32-L9C49

**Comment by mmaietta** [comment]
Yeah, add the DEBUG env var to your circleci environment per https://github.com/electron-userland/electron-builder/issues/7944#issuecomment-1852570211

**Comment by mmaietta** [comment]
You'll need to open a GH issue for `electron/osx-sign`, it's unrelated to electron-builder. As mentioned, it just executes it under-the-hood. Any processes during that time are owned by that project
