### ISSUE TITLE
32-bit program updates will download other versions of the program.

### ISSUE THREAD

**Issue by bzw1204** [electron-userland/electron-builder#7945]
* **Electron-Builder Version**:  22.3.16

* **Node Version**:  16.20.1

* **Electron Version**: 22.3.16
* **Electron Type (current, beta, nightly)**:

* **Target**:  Windows 10

When I was testing the update, I found that the 32-bit version downloaded a 64-bit update program. By tracing the source code, I discovered that the logic here is to download any program listed as the first item in the "latest.yml" file, rather than downloading the update program based on the current program version. I would like to know what considerations were made for this and if there is any configuration that can solve this issue.

![image](https://github.com/electron-userland/electron-builder/assets/9693637/b16639fb-c0d3-4510-abed-309a94f4b528)
![image](https://github.com/electron-userland/electron-builder/assets/9693637/042c5839-36b7-4b95-8b3b-1cce57134dba)

**Comment by psilogroup** [comment]
maybe we can use **process.arch** to detect current platform

**Comment by bzw1204** [comment]
> maybe we can use **process.arch** to detect current platform

Yes, I also think so.
