### ISSUE TITLE
How to add preinst and postinst to deb target?

### ISSUE THREAD

**Issue by mariotacke** [electron-userland/electron-builder#795]
**Version**: 7.10.2
**Target**: deb/Linux

How can I add `preinst` and `postinst` scripts to the deb executable? I find myself needing to add an autostart script and desktop shortcut after installation.

## Reference
- [Debian Policy Manual - Chapter 6 - Package maintainer scripts and installation procedure](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html)

**Comment by develar** [comment]
Set `build.deb.afterInstall` to path to your custom `after-install.tpl` (please see [default](https://github.com/electron-userland/electron-builder/blob/master/templates/linux/after-install.tpl))

And `build.deb.afterRemove`.
