### ISSUE TITLE
Set .env variable while build electron app for window in react

### ISSUE THREAD

**Issue by Abhi-Radadiya** [electron-userland/electron-builder#7956]
* **Electron-Builder Version**:  24.9.1

* **Node Version**:  20.10.0

* **Electron Version**:28.0.0

* **Target**: window

I have three environment files .env.staging, .env.testing and .env.production in react each contains specific main window load-url. 

file structure
|- src/
     |- electron-starter.js
     |- electron-preload.js
|-.env.staging
|- .env.production
|- .env.testing
|- package.json

inside electron-starter.js ==>
function createWindow() {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;
  mainWindow = new BrowserWindow({
    width: width,
    height: height,
    title: "PILOT",
    webPreferences: {
      preload: path.join(__dirname, "electron-preload.js"),
    },
  });

  mainWindow.loadURL(process.env.ELECTRON_APP_SITE_URL);
}

here at run time using this script I can set environment variable
"electron:staging": "env-cmd -f ./.env.staging electron .", 

but how to set specific environment file while build-time I am using this cmd to build  
"dist:win": "electron-builder --windows -c.extraMetadata.main=./src/electron-starter.js"

Thank you so much ...!!

**Comment by mmaietta** [comment]
Unfortunately, you can't. It's always read directly from the .env file. Best route to get around this is to use the programmatic electron-builder API (https://www.electron.build/api/programmatic-usage) and then dynamically create the env file (or just provide the variables directly in the programmatic usage
