### ISSUE TITLE
Getting error with Electron App while launching in RHEL 8x: (Error: Failed to get 'userData' path at initDataListener (../../app.asar/main.bundle.js)

### ISSUE THREAD

**Issue by ghoshujjwal** [electron-userland/electron-builder#7963]
* **Electron-Builder Version**:  24.4.0

* **Node Version**: 20.10.0

* **Electron Version**: 26.2.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux (RHEL 8x)

Getting error with Electron App while launching in RHEL 8x: (Error: Failed to get 'userData' path at initDataListener (../../app.asar/main.bundle.js).
When I checked main.bundle.js file, found that it is throwing error from below line:
	const appData = {
		**defaultCwd: app.getPath('userData'),**
		appVersion: app.getVersion()
	};

However, in code I have not used getPath. Instead I used getAppPath.

**Comment by mmaietta** [comment]
Electron-builder doesn't transpile code, it only pacakges the files that it is provided. You'll need to debug this further from your side, it's likely something with how you're compiling the app assets
