### ISSUE TITLE
Node modules not imported accurately compared to local, missing files.

### ISSUE THREAD

**Issue by 12Jeef** [electron-userland/electron-builder#7964]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18.15.0

* **Electron Version**: 28.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS (Ventura M2)

`electron-builder` is not accurately importing the ThreeJS module into the `node_modules` directory. I have tried many versions of ThreeJS, but it has no effect on the packaged app. Below is a side-by-side comparison of the difference in the `three` module located in `node_modules`. Above is `node_modules/three` unpacked from the `app.asar` located in the `Resources` of the MacOS application. Below is the module as it looks like from local development, not packaged whatsoever.

<img width="233" alt="Screenshot 2024-01-04 at 10 55 59 AM" src="https://github.com/electron-userland/electron-builder/assets/113314268/243176e1-a50b-47ca-a9e0-28d369737f03">

As you can see, it is missing the `examples` directory, which contains many crucial files needed for the application to work, such as `OrbitControls`, etc. Is there any reason `electron-builder` is not including the `examples` directory? I have also tried including ThreeJS directly in `package.json` using the `files` option, but that seems to have no effect. Here is the entire build configuration:

```
"appId": "org.app.id",
"copyright": "Copyright © 2024",
"npmRebuild": false,
"publish": [],
"files": [
	"node_modules/three/**/*",
	"node_modules/ionicons/**/*",
	"src/**/*",
	"docs/**/*",
	"package.json",
	"README.md"
],
"fileAssociations": [],
"mac": {
	"target": "dmg",
	"icon": "src/assets/app/icon.icns",
	"notarize": false
},
"linux": {
	"target": [
		"AppImage",
		"snap",
		"flatpak",
		"deb",
		"rpm",
		"pacman"
	],
	"icon": "src/assets/app/icon.png",
	"category": "Utility"
},
"flatpak": {
	"runtimeVersion": "22.08",
	"baseVersion": "22.08"
},
"win": {
	"target": "nsis",
	"icon": "src/assets/app/icon.ico"
}
```

Some more info: IonIcons, another module I am using, seems to import entirely fine; the packaged and unpackaged versions in `node_modules` look entirely the same.

**Comment by 12Jeef** [comment]
I am currently resorting to copying over the entire `three` module out of `node_modules`, then importing that instead, but this method is more tedious and I'd prefer not to do it this way.

**Comment by mikaelcolboc** [comment]
I have the exact same issue.
I think it's weird of three.js to include all there addons inside the "example" directory.
It's misleading and feels wrong. Maybe that's why electron skips that folder. Might be more of a three.js issue than electron.

**Comment by mmaietta** [comment]
So it is indeed part of the default `excludes` in electron-builder.
https://github.com/electron-userland/electron-builder/blob/17b50818730a5e6d7d1d1875df633e1413cf899e/packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts#L29-L30

I agree with @mikaelcolboc that it might not be best for three.js to have addons in the `example` directory, but I'm wondering if we provide a way to disable default excludes or at least allow electron-builder `files` to effectively bypass base restrictions?

**Comment by mmaietta** [comment]
So I'm hesitant to add another property as I think there may be an intrinsic issue with how `files` regex is being performed. Theoretically, I think the default exclusions should be able to be overwritten directly in the `files` configuration. I feel like I've seen a few other Github issues hit a similar issue with some `files` not being included even when specified, albeit I can't recall them off the top of my head.

Can you share a minimum reproducible repo for this issue? I can debug it further locally and probably add some unit tests to cover this use case.

**Comment by mikaelcolboc** [comment]
Thanks, I just created a private demo repo [electron-builder-threejs-bug-example](https://github.com/amnh/electron-builder-threejs-bug-example) and added you to it.

**Comment by mmaietta** [comment]
Created PR #8043 and added unit tests for this use case. Now you can leverage `onNodeModuleFile` hook to explicitly force certain paths to be included in the package (if returning `true`), otherwise it fallbacks to default logic
For your use case:
```
onNodeModuleFile: filePath => {
  // Force include this directory in the pakage
  return filePath.includes("node_modules/three/examples")
}
```
