### ISSUE TITLE
 The electron-updater encounters issues when cancelling the update download multiple times using the cancellationToken.

### ISSUE THREAD

**Issue by Thesiva7** [electron-userland/electron-builder#7965]
@develar @mmaietta @renovate-bot 

The autoUpdater functionality provided by electron-updater operates effectively for the initial 3 to 4 update attempts only. Here's the sequence of events:

Initially, the autoUpdater identifies an available update. Subsequently, I trigger the download process by clicking a button using the following code:

**const cancellationToken = new CancellationToken();
autoUpdater.downloadUpdate(cancellationToken);**

During the download of the update file, I have a mechanism to cancel the ongoing download by clicking a "stop" button, which is handled by the following code:

**cancellationToken.cancel();**

However, the issue arises when I repeat this sequence—initiating the download and canceling it—multiple times. After repeating these steps approximately 3 to 4 times or even more, the autoUpdater ceases to function correctly. It becomes unresponsive, failing to provide any response, error message, or indication of its status.

I am seeking guidance or a resolution to this problem where the autoUpdater stops working after a series of download initiation and cancellation cycles.

Thank you.

**Comment by mmaietta** [comment]
Few questions:
- Whats the user flow that is causing multiple update/cancel events in succession?
- What operating system is this on? mac (local http server served directly to electron to fetch from) is distinctly different from windows/linux implementation (execute distributable via OS-level commands)
