### ISSUE TITLE
Deeplinks with Linux requires xdg-desktop-portal and xdg-desktop-portal-gtk

### ISSUE THREAD

**Issue by jt-l** [electron-userland/electron-builder#7969]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18.8.0

* **Electron Version**: 21.3.3

* **Target**: deb

Clicking on a deeplink was causing this error to appear in the syslog:

`Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service`

After installing `xdg-desktop-portal` and `xdg-desktop-portal-gtk`, deeplinking appears to work as expected.

Note: this is an issue I ran into on a fresh install of Ubuntu 22.04.3 LTS. 

Wondering if there is a way to require those packages for install on Linux w/ the deb?

**Comment by mmaietta** [comment]
I'm not too familiar with linux, but there is a `depends` config option where you could probably specify those as requirements
https://www.electron.build/configuration/linux#debian-package-options
