### ISSUE TITLE
Fails on building node-gyp  dependencies e.g sqlite3

### ISSUE THREAD

**Issue by spamshaker** [electron-userland/electron-builder#7972]
Problem described here
https://github.com/TryGhost/node-sqlite3/issues/1746#issuecomment-1880025996

Root cause is an old app-builder-bin dependency which has a bug in version 4.0.0 and dosn't have it in version 4.2.0
https://github.com/electron-userland/electron-builder/blob/03c94516ef3b1b31b2f5b7bcdb9c6d3753d36b8d/packages/builder-util/package.json#L20

here is minimum code to reproduce bug
https://github.com/spamshaker/electron-builder-bug

**Comment by mmaietta** [comment]
We can't upgrade to 4.20 due to a bug in app-builder. See https://github.com/electron-userland/electron-builder/pull/7774
