### ISSUE TITLE
electron-updater: Named export 'autoUpdater' not found

### ISSUE THREAD

**Issue by ashwin-mittal** [electron-userland/electron-builder#7976]
* **Node Version**: 18.18.2
* **Electron Version**: 28.0.0
* **Electron Type (current, beta, nightly)**: current
Which version of electron-updater are you using (if applicable)? 6.1.1

I am not able to static import (`import { autoUpdater } from "electron-updater"
`) electron-updater in my electron application where it is mentioned clearly in [the docs](https://www.electron.build/auto-update.html) that we can do that. Here is [the repository](https://github.com/ashwin-mittal/electron-updater-issue) to reproduce the issue.

**Comment by mmaietta** [comment]
In the console logs, there's an error as to why it doesn't work **in addition to** how to properly import a CJS module.
```
App threw an error during load
file:///Users/michael.maietta/Development/electron-updater-issue-main/index.js:1
import { autoUpdater } from "electron-updater";
         ^^^^^^^^^^^
SyntaxError: Named export 'autoUpdater' not found. The requested module 'electron-updater' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using

import pkg from 'electron-updater';
const { autoUpdater } = pkg;
```

Solution:
```
import pkg from 'electron-updater';
const { autoUpdater } = pkg;
```

**Comment by undergroundwires** [comment]
Any plans to support ESM natively in electron-updater?

Thank you for the post @mmaietta, it solves the problem but I believe it is a workaround rather than an actual solution. If this is the way forward, I believe the docs should be updated.

**Comment by mmaietta** [comment]
It's probably unlikely I think in order to maintain backward support? I think electron-builder could be a hybrid npm package but that looks to require significant changes in both compilation, package imports, and test runners due to the monorepo configuration

Great feedback on the docs, I'll add that to my (lengthy) todo list

**Comment by mhkeller** [comment]
I came here after seeing the same error. The docs tell you to use the ESM import syntax and it looks like the package is ESM but yet I'm still seeing this error saying it's CommonJS.

edit: I was looking at the TypeScript declaration which looked like ESM. It seems the package is still built as CJS?

**Comment by shaolongcai** [comment]
This is my solution:
import pkg from 'electron-updater'
const { autoUpdater } = pkg;

**Comment by mmaietta** [comment]
Hey folks! Circling back on this topic. I'm sequencing a node22 + ESM migration (not a hybrid CJS+ESM package) for the next major semver bump; hoping to start this soon.

Does anyone here have any concerns with the dropping of CJS support and node <22?
