### ISSUE TITLE
docs probably misleading about squirrel properties

### ISSUE THREAD

**Issue by wojtkowiak** [electron-userland/electron-builder#798]
Works:
```
"win": {
            "loadingGif": ".desktop/assets/install.gif"
        }
```
Does not work:
```
"squirrelWindows": {
            "loadingGif": ".desktop/assets/install.gif"
        }
```

Seems that what is defined in the docs as `.build.squirrelWindows` should be in `.build.win`?

**Comment by develar** [comment]
Please specify electron-builder version.

**Comment by wojtkowiak** [comment]
`7.3.0`, update to the newest and now it works in `.build.squirrelWindows` 👍
