### ISSUE TITLE
Check the os version number before update

### ISSUE THREAD

**Issue by Eisiloljkee** [electron-userland/electron-builder#7984]
I am using version 21 of electron and am going to update it to version 28. I am looking for some mechanism that will prevent Windows 7/8/8.1 users from installing my update with the new version of electron, which will break their applications. How can i do this?

As far as I know there's no any solutions for this in electron-updater. It would be nice to have something. For example, I would like to have something like an additional field in latest.yml like "minimalRequiredOS" that will be checked before update-available event fired.

**Comment by mmaietta** [comment]
Correct, there's no built-in support for this in electron-updater. What I'd advise is applying an os version check in `update-available` in your current electron 21 version, release that in preparation for version 28, and filter from there accordingly.

Happy to review a PR for this as a community contribution though
