### ISSUE TITLE
Artifact name not used as GitHub file name

### ISSUE THREAD

**Issue by DreiDe** [electron-userland/electron-builder#7993]
* **Electron-Builder Version**:  24.9.1

* **Node Version**: 18

* **Electron Version**: 28
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac, Windows, Linux

When using the Github publisher the `build.artifactName` is not used as the file upload name. I would like the file name in GitHub to be `My-Software-1.1.1+000.exe`. Renaming it manually in GitHub is possible, so this is not a limitation of GitHub file names. I would suggest forwarding the `artifactName` without any validation to GitHub and see if it likes it or not.

**Comment by kashamalasha** [comment]
You can set up the asset name of the build with placeholders, like this:
```
"build": {
    "artifactName": "${productName}-${version}-${os}-${arch}.${ext}"
}
```
and set the whenever you like name in the `build.productName` field. It works fine.

**Comment by DreiDe** [comment]
@kashamalasha
I'm using `My-Software-${env.npm_package_version}.${ext}` as artifact name. However the resulting name in Github is `my-software-1.2.3.exe`. The two mistakes are that the capital letters are removed as well as the semver build version (should be `1.2.3+000`). In the env variable `npm_package_version` the build version is still included.

When building locally the name is also set correctly. Just not when uploading to Github.

**Comment by kashamalasha** [comment]
Try to set the My-Software as the build.productName and put the placeholder in the artifact as ${productName}. In my build it works fine. All Cap letters are still Capitalized in the release assets after uploading to GitHub.

**Comment by DreiDe** [comment]
Yes, I tried that too. No success either. Also the `+000` build number will not work for an application name on MacOs.

**Comment by kashamalasha** [comment]
` "electron-builder": "^24.12.0"`
