### ISSUE TITLE
directories are not explained in the documentation

### ISSUE THREAD

**Issue by Edge-coordinates** [electron-userland/electron-builder#7996]
This is a documentation problem, the link below points to this address 
```
https://www.electron.build/configuration/configuration.html#MetadataDirectories 
```
but it doesn't actually exist and I can't find a way to search for it through the I can't find it by searching for it.

So I'm at a loss as to how to configure `directories`.

Please fix the documentation, thanks!

![image](https://github.com/electron-userland/electron-builder/assets/68896486/4faa0d19-1d8e-43e0-91cc-b6a560b60a46)

The image is located at [the link ](https://www.electron.build/configuration/configuration.html#configuration)

**Comment by mmaietta** [comment]
I've updated mkdocs, mkdocs-material, and converted it to use typedoc. The docs are currently more verbose, but here:s the new location of the doc https://www.electron.build/configuration.html#metadata
