### ISSUE TITLE
Add an option to set a start screen shortcut with a specific AppUserModelID

### ISSUE THREAD

**Issue by etiktin** [electron-userland/electron-builder#80]
Windows notification support was added to Electron in v0.35. To make notifications work on Windows 8/8.1, you need to add a shortcut to the start screen that contains the same AppUserModelID as the one you set in your app using `app.setAppUserModelId(id)`.
NSIS apparently supports setting AppUserModelID:
http://nsis.sourceforge.net/ApplicationID_plug-in

It would be awesome if we support that, so people can actually use the notification support on Windows 8/8.1.

**Comment by stefanjudis** [comment]
:+1:

**Comment by develar** [comment]
Since 3.0 we support only Squirrel.Windows.

**Comment by develar** [comment]
Relates #362 @etiktin NSIS ApplicationID_plug-in is dead — links don't work.

**Comment by develar** [comment]
Solution — http://nsis.sourceforge.net/WinShell_plug-in

**Comment by McPo** [comment]
@develar Would I be correct in assuming that this hasn't been implemented and that native notifications will not work for Windows 8/8.1?

**Comment by develar** [comment]
@McPo Implemented for NSIS. https://github.com/electron-userland/electron-builder/wiki/NSIS#guid-vs-application-name

**Comment by McPo** [comment]
@develar I was aware of that GUID however I don't believe its being set it in all the required locations. 

It only appears to only be set in the INSTALL/UNINSTALL registry keys and as a mutex to prevent multiple installer instances from running. https://github.com/electron-userland/electron-builder/search?utf8=%E2%9C%93&q=APP_GUID

On Windows 8/8.1 the appId needs to be set as the Application User Model ID, on the shortcuts themselves. It also need to be set within the code itself before launching any windows, using `app.setAppUserModelId(id)` (I have done this myself, using the UUIDv5 thats printed out during the building phase)

http://electron.atom.io/docs/tutorial/desktop-environment-integration/#notifications-windows-linux-macos
https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

Maybe Im doing something daft, but it doesn't appear to be working.

I also ran the commands listed here https://msdn.microsoft.com/en-us/library/windows/hardware/mt661825(v=vs.85).aspx. And it never showed my application as having a AUMID set.

**Comment by McPo** [comment]
@develar My bad, I was foolishly setting the  `app.setAppUserModelId(id)` to the UUIDv5 as opposed to the appId. It also wasn't clear to me that the stated paragraph referenced  the AUMID, Ive submitted a pull request to make it more apparent https://github.com/electron-userland/electron-builder/pull/1007.

Thanks for the great work, it really is an excellent piece of kit.
