### ISSUE TITLE
Significant Performance Difference Between electron-builder and electron-forge

### ISSUE THREAD

**Issue by LoveLuanQi1202** [electron-userland/electron-builder#8000]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 20.10.0

* **Electron Version**:28.1.2
* **Electron Type (current, beta, nightly)**:current

* **Target**:  mac

Subject: Significant Performance Difference Between electron-builder and electron-forge

Body:
Dear electron-builder team,

I am writing to report a performance issue I have encountered with your tool. I have noticed that when I package the same application using electron-builder, it runs significantly slower compared to when it is packaged with electron-forge.

I have ensured that the application code is identical in both cases, and the only variable is the packaging tool used. This leads me to believe that the issue may lie with electron-builder.

I would appreciate it if you could look into this matter. Please let me know if you need any additional information or details to assist in your investigation.

Thank you for your time and assistance.

demo: https://github.com/LoveLuanQi1202/forgeAndBuilder

**Comment by mmaietta** [comment]
Can you run a test with `asar: false`? 

electron-builder only packages the code into an asar format and then copies that into the `.app`, which should be no different than electron-forge. The only difference I can think of is that the asar compilation is not as optimized in electron-builder's approach than that of `@electron/asar` package handles it.

Note: I've tried several times to try and migrate electron-builder's custom asar packaging logic to leverage the official `@electron/asar` package and have failed just as many times. Would love community assistance on it, the CI test suite works quite well in verifying the result.

**Comment by LoveLuanQi1202** [comment]
> Can you run a test with `asar: false`?
> 
> electron-builder only packages the code into an asar format and then copies that into the `.app`, which should be no different than electron-forge. The only difference I can think of is that the asar compilation is not as optimized in electron-builder's approach than that of `@electron/asar` package handles it.
> 
> Note: I've tried several times to try and migrate electron-builder's custom asar packaging logic to leverage the official `@electron/asar` package and have failed just as many times. Would love community assistance on it, the CI test suite works quite well in verifying the result.

i try to set `asar: false` but build with error ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Resources'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, ensureSymlink 'Versions/Current/Resources'

**Comment by LoveLuanQi1202** [comment]
I found out that it was my problem. It was wrongly packaged into an Intel chip.
