### ISSUE TITLE
When using Electron Builder to package on Windows 11, an error message "Image: Unknown Format" was reported.

### ISSUE THREAD

**Issue by tq-flySky** [electron-userland/electron-builder#8004]
* **Electron-Builder Version**: 24.6.3

* **Node Version**: 16.16.0

* **Electron Version**:28.1.4
* **Electron Type (current, beta, nightly)**:current

* **Target**: Windows 11 家庭中文版

![Snipaste_2024-01-24_16-20-40](https://github.com/electron-userland/electron-builder/assets/43290432/26c84711-90bf-46cc-a068-366adbdb30ff)

**Comment by mmaietta** [comment]
This is an error from https://github.com/develar/app-builder, might be worth opening a Github Issue there as there's nothing I can do from this project's perspective AFAICT
