### ISSUE TITLE
Electron Net

### ISSUE THREAD

**Issue by bella1890alt** [electron-userland/electron-builder#8005]
Hi,

When launching the electron app, i get the below error:
ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

Below are the details:
ElectronNet.Api =>13.5.1
ElectronNet.CLI =>23.6.1
.Net Core 6

I tried updating the ElectronNet.Api to 23.6.1 , but i was getting SocketIOClient Exception("Cannot connect to localhost")

Pleas guide me the solution to this issue. Been stuck for many days.

**Comment by mmaietta** [comment]
This seems genuinely unrelated to electron-builder. I'm not sure what your application is doing, but runtime errors are rarely due to a packager. Electron artifacts/dist/prod builds function differently than local development.
