### ISSUE TITLE
Socket Connection Error

### ISSUE THREAD

**Issue by bella1890alt** [electron-userland/electron-builder#8007]
**Electron.NET API**-23.6.1
 **Electron.NET CLI** -23.6.1 
**Framework** - net6.0

**code:**

public async void ElectronBootstrap()
    {
        //AddDevelopmentTests();

        var browserWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
        {
            Width = 1152,
            Height = 940,
            Show = false
        });

        await browserWindow.WebContents.Session.ClearCacheAsync();

        browserWindow.OnReadyToShow += () => browserWindow.Show();
        browserWindow.SetTitle(Configuration["DemoTitleInSettings"]);
    }

When I try to debug, i get the below error:
![image](https://github.com/electron-userland/electron-builder/assets/157344727/f713d120-52d3-4a04-accd-50229100be44)

**Comment by mmaietta** [comment]
The only localhost server that is used is electron-updater on macos and this seems unrelated to electron-builder
