### ISSUE TITLE
Code signing flexibility for multiple Windows targets

### ISSUE THREAD

**Issue by smasuda-isi** [electron-userland/electron-builder#8009]
* **Electron-Builder Version**:  24.6.3

* **Node Version**: 18.13.0

* **Electron Version**: 26.0.0
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows

Is there any way to designate specific Windows targets to sign? I want to build an unsigned zip for easy testing and a signed AppX for deployment.

The only way I can think of to do this currently is to have 2 separate electron-builder config files.

**Comment by mmaietta** [comment]
I think you can use `nsis.signAndEditExecutable: false` and `appx.signAndEditExecutable: true` in your config?
https://www.electron.build/configuration/win
