### ISSUE TITLE
Make keychain optional for macOS notarizing

### ISSUE THREAD

**Issue by MaartenBent** [electron-userland/electron-builder#8015]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 21.5

* **Electron Version**: 28.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS arm64

I want to notarize using electron-builder built-in notarize feature.

Previously I successfully used `afterSign` and manually notarized using `electron-notarize`. I only provide the `keychainProfile`, no `keychain`. Because with an empty keychain it allows to use the iCloud keychain.

From the electron-notarize docs:
>    * ... or keychain with keychainProfile:
      * `keychain` String (optional) - The name of the keychain or path to the keychain you stored notarization credentials in. If omitted, iCloud keychain is used by default.
      * `keychainProfile` String - The name of the profile you provided when storing notarization credentials.

```js
await notarize.notarize({
    tool: 'notarytool',
    appPath: appPath,
    keychainProfile: 'AC_PASSWORD',
});
```

Currently electron-builder requires to set the `APPLE_KEYCHAIN` envvar and forces to use a keychain. I would like this to become an optional parameter. And only require `APPLE_KEYCHAIN_PROFILE`. Relevant code:

https://github.com/electron-userland/electron-builder/blob/f5340b732dc0a303743a2a924750e9861e3a345f/packages/app-builder-lib/src/macPackager.ts#L533-L538

Thank you.

**Comment by mmaietta** [comment]
Great callout and thanks for the code pointers as well. I've updated the code and it will be in our next release
