### ISSUE TITLE
NSCameraUsageDescription keeps getting added to info.plist despite not requesting it

### ISSUE THREAD

**Issue by Melynt3** [electron-userland/electron-builder#8016]
* **Electron-Builder Version**: 24.6.3

* **Node Version**: v18.17.1

* **Electron Version**: 25.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**:  MAS/OSx

Despite having no need for camera access in my app, electron builder somehow keeps adding it to my plist:

```xml
        <key>NSCameraUsageDescription</key>
        <string>This app needs access to the camera</string>
```

My builder.config includes, both entitlements.mac.plist and entitlements.mac.inherit.plist as while as variant for MAS build.
Total of 4 files. None of them mentions camera in any way, and yet it keeps adding itself. 

**entitlements**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>xxxx</string>
    </array>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.device.bluetooth</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.device.usb</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <false/>
  </dict>
</plist>
```

**entitlements inherit**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <true/>
        <key>com.apple.security.inherit</key>
        <true/>
    </dict>
</plist>
```

As you can see i have also explicitly tried to disable the camera usage, but app support keeps rejecting app this way saying that the key should not exist `NSCameraUsageDescription`. 

How can i fix this?

**Comment by mmaietta** [comment]
That's not in our electron-builder codebase at all, so it must be coming from the electron app directly? Might be worth opening an issue there and/or test with electron-forge to see if you can reproduce without electron-builder?

**Comment by Melynt3** [comment]
Well, i still did not managed to locate core of the problem. 

But was able to solve this by setting in mac>extendedInfo those keys and set them to undefined
