### ISSUE TITLE
Unable to support fr-CA, es-419 for NSIS in app-builder-lib

### ISSUE THREAD

**Issue by billrccrop** [electron-userland/electron-builder#8018]
* **Electron-Builder Version**: 23.3.0

* **Node Version**: v18.17

* **Electron Version**: 27.2.4
* **Electron Type (current, beta, nightly)**: stable

* **Target**: exe(nsis)

We add some strings in the messages.yml, and also we add some additional region code. like fr-CA, es-419, but the message of i18n are incorrect for fr-CA, es-419

- Switching system language to fr-CA, but the translation is fr-FR 
- Switching system language to es-419, but the translation is es-ES

Can you guys help check is this a system limitation or a problem with app-builder-lib?

Thanks!

**Comment by mmaietta** [comment]
I'm not seeing any custom code that modifies language/translations from messages.yml so I'm thinking this may either be a system limitation or how nsis installers detect system languages.
