### ISSUE TITLE
  ⨯ Exit code: 1. Command failed: which python

### ISSUE THREAD

**Issue by mridul-jarvisbitz** [electron-userland/electron-builder#8027]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18

* **Electron Version**: 26.6.8
* **Electron Type (current, beta, nightly)**:

* **Target**: mac

![Screenshot 2024-02-02 at 3 31 45 PM](https://github.com/electron-userland/electron-builder/assets/119835660/011e0d47-c9c9-4d9b-bdc7-7bbdc630c3e0)

Getting the build failed error

**Comment by mmaietta** [comment]
Pretty sure you just need python installed on your machine.
