### ISSUE TITLE
Request for secure contact to report a security vulnerability

### ISSUE THREAD

**Issue by bruno-1337** [electron-userland/electron-builder#8033]
Hi, I have found a security issue that affects the app's functionality. I want to share the issue in a responsible way, without exposing it to the public. Could you please provide me a secure and private way to contact you and send you the issue report? You can reply to this issue with an email address or a link to a secure communication platform. Thank you for your time and effort.

**Comment by mmaietta** [comment]
Just circling back here for public awareness. Thanks for emailing me @bruno-1337, I'll investigate it as soon as possible
