### ISSUE TITLE
JavaScript Error - '.node' Not Found in ASAR

### ISSUE THREAD

**Issue by MrTob** [electron-userland/electron-builder#8034]
* **Electron-Builder Version**:  24.9.1
* **Node Version**: 18.17
* **Electron Version**: 24.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows

I have an Angular webapp which I would like to build as an Electron app. A self-written `.node` library is integrated into the Electron app. When I now want to build the Electron app, I get the error that the '.node' file was not found because it is not in `resources/app.asar`. How can I put the file into the directory?

![chrome_y5SxfTeZBh](https://github.com/electron-userland/electron-builder/assets/30464573/a6a30edc-1bb8-405c-9c5f-665e99cec0f6)

**Comment by mmaietta** [comment]
You should be able to add it via `files` option in electron-builder configuration
