### ISSUE TITLE
notarize: true has no effect with apple API key

### ISSUE THREAD

**Issue by dancarasco** [electron-userland/electron-builder#8040]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 20.11.0

* **Electron Version**: 28.2.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac - dmg/universal, zip/universal

When setting the following env variables:

<img width="483" alt="Screenshot 2024-02-08 at 01 02 47" src="https://github.com/electron-userland/electron-builder/assets/49026110/74886cdf-78fa-42f0-8bd0-fbd87d42a091">

And setting notarize to true:

<img width="143" alt="Screenshot 2024-02-08 at 00 49 17" src="https://github.com/electron-userland/electron-builder/assets/49026110/7c054267-4133-4616-a582-4658e24640d3">

Notarizing silently fails in electron-builder:

<img width="345" alt="Screenshot 2024-02-08 at 00 53 44" src="https://github.com/electron-userland/electron-builder/assets/49026110/5b8e6df0-dcf9-416c-8191-c86f49da7976">

I would expect to see one of the following messages

> skipped macOS notarization - `notarize` options were not provided 
or
> `Env vars APPLE_API_KEY, APPLE_API_KEY_ID and APPLE_API_ISSUER need to be set`
or
> "notarization successful"

None appear.

**Comment by mmaietta** [comment]
Can you please try without setting `notarize: true`, electron-builder should automatically detect based on the env vars being set. Would appreciate if you also tried this with `next` version [v24.12.0](https://github.com/electron-userland/electron-builder/releases/tag/v24.12.0)

**Comment by dancarasco** [comment]
> Can you please try without setting `notarize: true`, electron-builder should automatically detect based on the env vars being set. Would appreciate if you also tried this with `next` version [v24.12.0](https://github.com/electron-userland/electron-builder/releases/tag/v24.12.0)

Removed `notarize: true` from package.json and received the following warning:

<img width="633" alt="Screenshot 2024-02-13 at 20 43 57" src="https://github.com/electron-userland/electron-builder/assets/49026110/992fc089-4a38-49c6-9bd4-2215bba9cd05">


Same behaviour on both **v24.9.1** and **v24.12.0**

Can confirm the App Store Connect env vars are present in the environment:

`echo ${APPLE_API_KEY}` returns the full path to the .p8 file which contains a valid PRIVATE KEY.
`echo ${APPLE_API_KEY_ID}` returns the the 10 character key ID.
`echo ${APPLE_API_ISSUER}` returns the issuer UUID.

MacBook Pro / M2 Max / Sonoma 14.3.1

**Comment by mmaietta** [comment]
Will take a look at it this week. (Currently swamped with work)
