### ISSUE TITLE
Change electron-builder entrypoint to main.js or resolve missing index.js issue

### ISSUE THREAD

**Issue by bishaldg** [electron-userland/electron-builder#8041]
* **Electron-Builder Version**: 24.9.1

* **Electron Version**:28.2.2
* **Electron Type (current, beta, nightly)**:current

* **Target**: windows

WHen building my electron app, getting the error, "Application entry file "index.js" in the "*file-location*\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.

My entrypoint should be main.js not index.js. How to change the entrypoint in the electron-builder.json I have created?

**Comment by bishaldg** [comment]
Edit: I also tried changing the file from main.js to index.js as a last try but it didnt help. Any resolution to this issue?

**Comment by mmaietta** [comment]
You should be able to define the entry point in your package.json, such as via `"main": "dist/main.js"`

**Comment by bishaldg** [comment]
> You should be able to define the entry point in your package.json, such as via `"main": "dist/main.js"`

Thanks, that worked.
