### ISSUE TITLE
Get an app to open this app link getting this error while opening electron app

### ISSUE THREAD

**Issue by AyushVe99** [electron-userland/electron-builder#8046]
I created build of my electron app while opening the app I am getting the error the Get an app to open this app link. Can anybody help me to solve this issue
![Screenshot (10)](https://github.com/electron-userland/electron-builder/assets/112403149/8f4ad008-db3a-41b3-86a7-b915fcbaa550)

**Comment by mmaietta** [comment]
Is this for deeplinking from a browser url into your application?
