### ISSUE TITLE
[DEB][Suggestion] install files in folder /opt/[appId]

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#805]
* **Version**: 7.11.3

* **Target**: Linux (deb)

It seems a deb package generated by electron-builder install its files in folder `/opt/[productName]`. I would like to suggest that this folder be replaced with `/opt/[appId]`, since `appId` generally also contains info about vendor/organization, which may be handful to keep `/opt` hierarchy organized (e.g., avoid conflicts with two different vendors which provide the same product name).

**Comment by develar** [comment]
deb is deprecated and should be not used at all to distribute app. 

Please use AppImage or vote for #509 — I completely understand that we cannot say "use AppImage forever and for all" — it is the reason why Snaps will be supported as soon as I finish NSIS auto-update.

**Comment by develar** [comment]
We install as `product name` on Windows too, so, unlikely it will be fixed. Maybe should be an option to customise installation path deb.
