### ISSUE TITLE
Possible to publish via config rather than CLI arguments?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#8050]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 20.11.0

* **Electron Version**: 28.2.x
* **Electron Type (current, beta, nightly)**: current

* **Target**: Snap & AppImage

I can't seem to find any way to programmatically invoke the publishing via modifying our config file. We use a custom build script which creates the final JSON for the build, but it appears that that config is identical whether publishing or not.

I feel like I must be overlooking something because in the docs [here](https://www.electron.build/configuration/publish.html#how-to-publish) it says:

> But please consider using automatic rules instead of explicitly specifying publish

Is there any way we can manage this from the config file?

**Comment by mmaietta** [comment]
All publisher json/js configurations can be applied to `publish:` field in the config.

Depending on your setup, these are the properties each publisher type accepts https://www.electron.build/configuration/publish#publishers

**Comment by Slapbox** [comment]
Sorry if I'm misunderstanding @mmaietta.

We indeed define the `publish` field, but it doesn't seem to do anything without also using CLI flag `--publish always` or similar. I'm a little confused by that.

Our `publish` key looks like this, but without that flag, nothing actually happens - it builds but doesn't publish.

```js
publish: {
  acl: 'public-read',
  bucket: 'our-bucket',
  path: 'path/inside/bucket',
  provider: 's3',
};
```

It's possible I made some mistake in our `buildConfig.js` that produces the JSON, but it's pretty simple and I haven't found the error if it's in there.

**Comment by mmaietta** [comment]
Ohhhh, I see what you're saying, my apologies.

Yes, I think there's two ways to do this. Either via `--publish always`, OR through other means of "auto activating" it such as by providing a `GH_TOKEN` env var for Github. It doesn't seem to have a reciprocal for S3, probably due to security reasons since electron-builder also can read from `.aws/credentials` file I think

There's also the programmatic API (which I always recommend for greater control)
https://www.electron.build/api/programmatic-usage

Looking at the code, I think this would work
```
builder.build({
  targets: Platform.MAC.createTarget(), // Or any other specification of targets, can also be omitted if you want electron-builder to figure it out. I haven't personally tried it omitted before though.
  config: electronBuilderConfigObject,
  publish: "always" // types: "onTag" | "onTagOrDraft" | "always" | "never"
})
```

**Comment by Slapbox** [comment]
> There's also the programmatic API

Oh, so I didn't have to make a custom Node spawn script? 😅

Thanks so much for the tip! I'm going to try to shift our build process to rely on `builder.build` when I can find some spare time.

**Comment by mmaietta** [comment]
Happy to help if you have additional questions.

I think I have an old typescript script with the programmatic approach lying around. Will try to find it
