### ISSUE TITLE
Package node that depends on dll files

### ISSUE THREAD

**Issue by Moebits** [electron-userland/electron-builder#8054]
* **Electron-Builder Version**:  24.9.1

* **Node Version**:  20.11.0

* **Electron Version**: 28.2.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows nsis x64

Hello I am trying to build a native node module that depends on several .dll files (node-canvas). 

<img width="232" alt="Screenshot 2024-02-16 at 1 08 30 AM" src="https://github.com/electron-userland/electron-builder/assets/37512637/d98ae681-a909-41e1-ad95-2ad1503e68a5">

I don't know how to build it with asar enabled. It works if you disable asar, but when it's enabled it looks like the node file gets copied to `C:/users/name/AppData/Local/Temp` without any of the dll files and thus it doesn't work.

How can I copy the dll files to the local/temp folder on installation?

**Comment by mmaietta** [comment]
Can you try manually specifying `**/*.dll` in your `files` configuration?

**Comment by Tenpi** [comment]
> Can you try manually specifying `**/*.dll` in your `files` configuration?

Nope it didn't work I already included all the files in dist with `dist/**/*` so don't think that's the issue.

**Comment by mmaietta** [comment]
Can you share a minimum reproducible repo/gist of the issue? I can then replicate from there and debug

**Comment by Tenpi** [comment]
Try building this project: https://github.com/Tenpi/electron-builder-dll
