### ISSUE TITLE
❓ Why are the GitHub and npm releases staying as pre-release?

### ISSUE THREAD

**Issue by KatoakDR** [electron-userland/electron-builder#8058]
👋 Hello, curious why the GitHub and npm releases for this project since `v24.9.1` have been `pre-release`?

The side-effect, intended or not, is that on https://www.npmjs.com/package/electron-builder the "latest" release is still pinned as `v24.9.1`, and neither `npm` nor `yarn` say that there's a newer version to upgrade to.

There's been multiple releases since `v24.9.1` but since they are marked as `pre-release` on GitHub and on npm then I'm not sure if we should upgrade to them?

Thanks

**Comment by mmaietta** [comment]
Mostly my user error tbh. The GH release pipeline auto publishes as `next`. Usually, I let releases "bake" for a while as `next` tag on npm before promoting it to `latest`, and depending on how I much time I'm able to provide to this project, I sometimes forget to promote the versions to `latest`. Thanks for the reminder 🙂 

Is there a version you're particularly concerned with I need to investigate into?

**Comment by KatoakDR** [comment]
Thanks for the confirmation :)

I don't have any further questions at this time. I'll happily upgrade to the latest release. 

Thanks for your work on this project!

**Comment by Bartel-C8** [comment]
Can you do the same for https://www.npmjs.com/package/electron-updater?activeTab=versions ?


Thanks @mmaietta !

**Comment by mmaietta** [comment]
6.1.9 has a significant change to windows verification flow in powershell and the release is only 9 days old. I'd prefer to leave that one as `next` for now so that developers know to delicately test that updater flow as part of their own processes.
