### ISSUE TITLE
`snapcraft` is required in building `snap` (provider: github) after `24.9.2`

### ISSUE THREAD

**Issue by JellyBrick** [electron-userland/electron-builder#8061]
* **Electron-Builder Version**: 24.13.1, 24.12.0
* **Latest Known Working Electron-Builder Version**: 24.9.1

* **Node Version**: 20 (GitHub Actions)

* **Electron Version**: 28.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux x64

The build failed with this error. 

```bash
 ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  
```

Detailed log: https://github.com/th-ch/youtube-music/actions/runs/7969007984/job/21754132043

We are using pnpm (`8.15.3`)

**Comment by JellyBrick** [comment]
- 24.12.0
  - https://github.com/th-ch/youtube-music/actions/runs/7968235719/job/21752174790
  - https://github.com/th-ch/youtube-music/actions/runs/7968236579/job/21752176733
  - https://github.com/th-ch/youtube-music/actions/runs/7968247870/job/21752928339
- 24.13.1
  - https://github.com/th-ch/youtube-music/actions/runs/7969007984/job/21754132043
- 24.9.1
  - https://github.com/th-ch/youtube-music/actions/runs/7969339455/job/21755000082

#### 24.9.1 -> 24.12.0 commit

https://github.com/th-ch/youtube-music/commit/6358a2d0b1fb7d54da31269b2ce16799705c449e

#### 24.13.1 -> 24.9.1 commit

https://github.com/th-ch/youtube-music/commit/8bd05f525df98671f0a516b159cccab302b7ae99

Yes, this issue is 100% reproducible in this repository (https://github.com/th-ch/youtube-music)

**Comment by JellyBrick** [comment]
still experiencing this issues in 24.13.3

https://github.com/th-ch/youtube-music/actions/runs/8125045551/job/22207198684

**Comment by JellyBrick** [comment]
- 24.9.2: Successful
- 24.9.3: Failed

https://github.com/electron-userland/electron-builder/compare/v24.9.2...v24.9.3

**Comment by JellyBrick** [comment]
Caused by https://github.com/electron-userland/electron-builder/pull/7908

**Comment by cmdcolin** [comment]
what was the resolution to this? I don't currently want to setup snapcraft but want to publish snap files

**Comment by mmaietta** [comment]
How would you bundle a snap distributable but not set up snapcraft? That seems like mutually exclusive

**Comment by cmdcolin** [comment]
I am not really sure. I just had a setup that "worked" and was creating and releasing .snap files to github but then it stopped working after a electron-builder version upgrade similar to what @JellyBrick had experienced. my understanding is using snapcraft and such would release to the snap store? i just removed snap builds for now in our project...it's pretty low usage

**Comment by JellyBrick** [comment]
> what was the resolution to this? I don't currently want to setup snapcraft but want to publish snap files

@mmaietta @cmdcolin 

It can't; for versions after 24.9.4, you must install snapcraft before you can bundle snap.

https://github.com/th-ch/youtube-music/commit/d09858cbec5919746060e7c26c53a9657d332731
