### ISSUE TITLE
Electron-updater: App icon disappears from Launchpad after Auto-Update on macOS

### ISSUE THREAD

**Issue by kashamalasha** [electron-userland/electron-builder#8066]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18.14.0

* **Electron Version**: 27.1.2
* **Electron Type (current, beta, nightly)**: current

* **Electron-updater Version**: 6.1.7

* **Target**: MacOS DMG

After an auto-update was applied to the application, the app icon vanished from the Launchpad of the device. Nevertheless, the app is accessible from the Application folder and works properly. This issue persists despite restarting the device. The disappearance of the app icon impedes access to the app's functionalities and impacts user experience negatively.

OS Information:
```
ProductName:       macOS
ProductVersion:    14.4
BuildVersion:      23E5180j
CPU:               Apple M2
```

**Comment by mmaietta** [comment]
I've actually not seen a report like this before. I found this SO post: https://stackoverflow.com/a/35689026

I checked the codebase and we're explicitly setting CFBundleVersion though
https://github.com/electron-userland/electron-builder/blob/538dd86bf52f0091dbb1120bdd30f56dfdbd5747/packages/app-builder-lib/src/appInfo.ts#L45-L63
At this point of the code, it's impossible for `this.buildVersion` to be null
https://github.com/electron-userland/electron-builder/blob/538dd86bf52f0091dbb1120bdd30f56dfdbd5747/packages/app-builder-lib/src/macPackager.ts#L460-L461

Just to double check that assumption though, can you verify that your deployed `Info.plist` has this CFBundleVersion  supplied?

**Comment by kashamalasha** [comment]
`CFBundleVersion` is set correctly according to the `package.json[version]` value. However, the application is not on the Launchpad.
