### ISSUE TITLE
Question: What are the command line parameters for Silent Install and All Users for Windows Installer .exe

### ISSUE THREAD

**Issue by kirannatarajan** [electron-userland/electron-builder#8075]
* **24.6.4**: 

* **16.18.2**: 

* **22.3.27**:
* **Electron Type (current, beta, nightly)**:

* **Windows**: 

We are using the command **electron-builder --win --publish never** command to generate Windows Installer exe.
What are the command line parameters that can be used with this installer for Silent Install, Install for All Users and Silent Uninstall.

**Comment by mmaietta** [comment]
These are the command line arguments provided to the installer
https://github.com/electron-userland/electron-builder/blob/8e51ba508f39abb670bb145a79b2a3c0d4af19c9/packages/electron-updater/src/NsisUpdater.ts#L128-L147

Silent Uninstall and Install for All Users are not command line args
