### ISSUE TITLE
[Win][SUGGESTION] Add support for PortableApps.com Format

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#808]
- **Version**: any

- **Target**: Windows

I would like to suggest you to add support for building packages in PortableApps.com format for Windows.

Reference: http://portableapps.com/development/portableapps.com_format

**Comment by yahyaKacem** [comment]
I think you're looking for [electron-packager](https://github.com/electron-userland/electron-packager).

**Comment by develar** [comment]
@yahyaKacem it is `dir` target and this issue is not about it.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear. 

I hope I will address this feature later.

**Comment by develar** [comment]
@lbssousa Please try `portable` #1157 It is suitable for you?
