### ISSUE TITLE
Are there any options for retrying file codesign logic when it fails due to a timestamp service unavailable issue on MacOS?

### ISSUE THREAD

**Issue by appdevbuild** [electron-userland/electron-builder#8089]
* **Electron-Builder Version**: 24.12.0

* **Node Version**: 18.16.1

* **Electron Version**: Any
* **Electron Type (current, beta, nightly)**: Any
 Any

* **Target**: x64 & arm64

We always encounter apple's timestamp service unavailable issues when we are building electron packages on macOS.
Error like this: The timestamp service is not available.

This error occurred randomly when it was signing files one by one. There are no network issues on AWS, actually.
But when this error occurs, we have to restart the whole building process, although the signing step only takes up a small portion of the total building time. This will waste a lot of time.

Are there any solutions to retry signing a file when it fails with a timestamp issue?

**Comment by mmaietta** [comment]
We use the official `@electron/osx-sign` npm package for signing. I'm not sure if we can wrap their exported function with a retry block, but feel free to give this `patch-package` a shot:
`app-builder-lib+24.13.3.patch`
```
diff --git a/node_modules/app-builder-lib/out/macPackager.js b/node_modules/app-builder-lib/out/macPackager.js
index d5acbdd..9676310 100644
--- a/node_modules/app-builder-lib/out/macPackager.js
+++ b/node_modules/app-builder-lib/out/macPackager.js
@@ -336,7 +336,7 @@ class MacPackager extends platformPackager_1.PlatformPackager {
             identity: identity || "none",
             provisioningProfile: provisioningProfile || "none",
         }, customSign ? "executing custom sign" : "signing");
-        return customSign ? Promise.resolve(customSign(opts, this)) : (0, osx_sign_1.signAsync)(opts);
+        return customSign ? Promise.resolve(customSign(opts, this)) : (0, builder_util_1.retry)(() => (0, osx_sign_1.signAsync)(opts), 3, 1000, 1000);
     }
     //noinspection JSMethodCanBeStatic
     async doFlat(appPath, outFile, identity, keychain) {
```
It gives 3 retries with both an interval and backoff of 1 second.

**Comment by beyondkmp** [comment]
I haven't encountered similar issues on Windows, but I have experienced this signing failure issue on macOS. Looking at the code, the dosign process on Windows includes a retry mechanism. Therefore, we can implement the same method on macOS as well.

https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/codeSign/windowsCodeSign.ts#L170
