### ISSUE TITLE
Windows 7: build msi installer error

### ISSUE THREAD

**Issue by xiangkaiy** [electron-userland/electron-builder#809]
- **Version**: 5.35.0

- **Target**:Windows7 64bit

I can build an exe file to run, but when I add the noMsi config, there is an error.
Here is my config for win:
"win":{
    "target": "squirrel",
    "noMsi": false,
    "iconUrl": "https://(someurl of my png image)"
}
when I run the builder code, I got an error below:
error LGHT0311 :  A string was provided with characters that are not available in the specified database code page '1252'. Either change these character to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.

```
at C:\Users\xiangkai.xk\Repo\x-xiami-desktop\node_modules\electron-builder\src\util\uti.ts:96:16
at ChildProcess.exithandler (child_process.js:220:5)
at emitTwo (events.js:87:13)
```

**Comment by develar** [comment]
> Version: 5.35.0

Please use latest version.

**Comment by PinkyJie** [comment]
I use the latest version of electron-builder, but still encountered this issue. I did some googling, it seems the root cause is we use some Chinese characters for `productName` and the encoding is not consistent with Windows-1252, how to change this encoding?

**Comment by develar** [comment]
@PinkyJie Please use nsis target and create MSI using another tool (see #723).

**Comment by PinkyJie** [comment]
@develar I tried NSIS, it works fine for me, but I can't make it working with AutoUpdate feature, it seems AutoUpdate on Windows can only work with `Squirrel.Windows`. Is there a solution for this?

**Comment by develar** [comment]
> it seems AutoUpdate on Windows can only work with Squirrel.Windows. Is there a solution for this?

See #529
