### ISSUE TITLE
Windows 10 Icon Missing In Application Bar

### ISSUE THREAD

**Issue by ryanpager** [electron-userland/electron-builder#810]
- **Version**: ^7.9.0

- **Target**:  Mac & Windows (64 & 32bit)

So everything works great -- application runs, no errors nothing. However, on _windows 10 only_ the icon does not show up in the application bar -- only a blank file icon. On all other platforms, the icon works perfectly.

The icon was generated as the proper file type (ico & icns), and is the correct size. Im not sure what else I should be checking, but the problem only happens on windows 10.

Any ideas on this one?

**Comment by develar** [comment]
Do you mean that icon is visible on Windows 7 or 8? Have you tried nsis target?

**Comment by ryanpager** [comment]
@develar Yup windows 7 and 8 are perfect. I did try the NSIS target, which didn't solve the issue.

**Comment by ryanpager** [comment]
@develar Tried the target: "nsis", didnt work.

**Comment by tomzx** [comment]
Interesting, in my case, I do not see any icon on both Win 7/10. The **unpacked** executable does work just fine though.

**Comment by develar** [comment]
Sorry for delay, I am currently busy on other issues. It works for me (it is Squirrel.Windows app) — 
<img width="693" alt="screen shot 2016-10-13 at 08 44 47" src="https://cloud.githubusercontent.com/assets/350686/19339086/772af23a-9121-11e6-9010-6ae1542b6662.png">

Further investigation is not possible since I cannot reproduce :)

If it is important for you — well, you can help us to investigate/fix. Or just use nsis target and set `nsis.perMachine` to `true`.

**Comment by develar** [comment]
BTW, my app is signed.

**Comment by develar** [comment]
Could you please specify your application product names?

**Comment by tomzx** [comment]
After further inspection, I'd say the issue is related to the filename. If I leave everything the same, except that I rename the executable, then the icon appears in the taskbar. I thinking it might have something to do with the registry at this point since I don't see anything else that would keep this kind of information about an application/executable.

I did try to compare the operations executed by using ProcMon, but I haven't found anything of interest searching for "icon".

**Comment by develar** [comment]
@tomzx That's why I ask you "please specify your application product names (spase/special symbols/unicode)?" :)

**Comment by tomzx** [comment]
@develar By renaming, I meant changing Abc1.exe to Abc2.exe (name has this exact format). No special symbols(non-ascii)/spaces.

**Comment by ryanpager** [comment]
@develar Maybe this might help -- its my build setup in the package.json.

```js
"build": {
    "appId": "com.electron.talkfusion.platform",
    "productName": "Talk Fusion",
    "win": {
      "loadingGif": "build/loading-icon.gif",
      "certificateFile": "build/codesigning-certificate.p12"
    },
    "mac": {
      "category": "public.app-category.productivity"
    },
    "dmg": {
      "title": "Talk Fusion Installer",
      "background": "build/background.png",
      "contents": [
        {
          "x": 448,
          "y": 344,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 192,
          "y": 344,
          "type": "file",
          "path": "Talk Fusion.app"
        }
      ],
      "window": {
        "side": {
          "width": 640,
          "height": 480
        }
      }
    }
  }
```

**Comment by tomzx** [comment]
@ryanpager Have you attempted to change the executable name once it is installed to see if you get the same behavior I have, that is, once renamed, the icon is shown in the taskbar?

I simply want to confirm we're experiencing a similar issue and not two different issues (which would deserve to be tracked separately).

**Comment by ryanpager** [comment]
@tomzx Hmmm I havent tried that -- will try that tomorrow morning when im back at work.

**Comment by develar** [comment]
Also, please try to restart Windows.

**Comment by tomzx** [comment]
@develar Tested by rebooting on Windows 10. Issue is still present.
However, I'd like to retract my statement about Windows 7.
Is there a required icon size? Our icon is currently 256x256.

**Comment by develar** [comment]
> Is there a required icon size? Our icon is currently 256x256 (it displays properly on the desktop).

It is ok. (it is minimum allowed size).

**Comment by ryanpager** [comment]
Any other suggestions on this @develar? Its not a game breaker, but its definitely annoying our users.

**Comment by develar** [comment]
Please try upcoming 10.2.0

**Comment by ryanpager** [comment]
@develar 

So 10.2.0 fixed the icons on NSIS installers -- but not the squirrel target. Unfortunately, I have to use the squirrel builder because of auto updates (for reference, I use https://github.com/ArekSredzki/electron-release-server).

Anyhow, my understanding is that NSIS will not recognize the auto updates -- and even if it did it would not general the nupkg files that I need. Is that understanding correct, or am I a little bit sideways on my thinking?

Is there something else I could try here to generate the nupkg files for windows, or fix this?

Either way -- thank you so much for spending the time to help with this (and anyone else). This is not a critical issue for me, but it is annoying to see the white file icon instead of a nice one :)

**Comment by develar** [comment]
@ryanpager Probably upgrade to Squirrel.Windows 1.5.0 will help you. I am going to upgrade this week especially to address your issue.

**Comment by develar** [comment]
> my understanding is that NSIS will not recognize the auto updates

NSIS supports auto-update, please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update

Do you need nupkg only for https://github.com/ArekSredzki/electron-release-server?
