### ISSUE TITLE
artifactName is not applied in the unpacked directory

### ISSUE THREAD

**Issue by veodko** [electron-userland/electron-builder#8106]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 20.11.0

* **Electron Version**: 29.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows x64, linux arm64

When doing normal builds (e.g. portable for windows), the `artifactName` configuration option is respected.
But when using the `--dir` flag for generating unpacked build (which is what is what I need, because packed ones are simply too slow and startup time is crucial to me), the binary generated in the unpacked dir is always generated with a default artifact name schema, e.g. `my-app.exe` no matter what I set in the `artifactName` option.

My package.json:
```json
{
  "name": "my-app",
  "version": "0.0.1",
  "description": "Electron app",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron .",
    "build": "electron-builder"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  },
  "devDependencies": {
    "electron": "^29.1.0",
    "electron-builder": "^24.13.3"
  },
  "build": {
    "artifactName": "${productName}-${version}-${os}-${arch}.${ext}",
    "win": {
      "icon": "./icon.ico",
      "artifactName": "${productName}-TEST.${ext}"
    },
    "portable": {
      "unicode": false
    }
  }
}
```

When built using just `npx electron-builder`, the packed binary is called `my-app-TEST.exe` but the real one inside unpacked directory is just `my-app.exe`. Same if I build with `--dir` flag: `npx electron-builder --dir`.

Is there any way to affect the name generated in the directory, or do I need to resort to changing this name after every build?

**Comment by beyondkmp** [comment]
I think you want to use change productName. 

https://www.electron.build/configuration/configuration#artifact-file-name-template
```
productName String | “undefined” - As name, but allows you to specify a product name for your executable which contains spaces and other special characters not allowed in the name property. If not specified inside of the build configuration, productName property defined at the top level of package.json is used. If not specified at the top level of package.json, name property is used.
```

**Comment by veodko** [comment]
This does not allow me to modify the name per system configuration (e.g. I cannot put a separate productName to the linux build and windows build as it throws an error) and afaik won't allow me to add any variable stuff to the name either, such as architecture I'm building for.

There is also  `executableName`:
```
executableName String | “undefined” - The executable name. Defaults to productName.
```
And it does indeed work, but also does not allow any variable interpolation.

IMO `artifactName` should be applied to every generated binary but I saw that in the past there were also some inconsistencies here and some build types didn't respect this option at all.
