### ISSUE TITLE
disable `sanityCheckPackage` in the `doPack` step

### ISSUE THREAD

**Issue by nikitakot** [electron-userland/electron-builder#8122]
* **Electron-Builder Version**: 24.13.3 

* **Node Version**: v18.19.0

* **Electron Version**: 28.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32 & darwin

Is it somehow possible to disable `sanityCheckPackage` check? I am using a custom electron fork where I implemented encrypted asar support. When packing my app I encrypt the asar archive in the `afterPack` hook, but the `sanityCheckPackage` then fails because it can't open the encrypted asar.

I'm happy to contribute and implement `sanityCheckPackage` disabling through the config if it's not possible already.

**Comment by beyondkmp** [comment]
From the current code, it seems impossible to disable sanityCheckPackage.
https://github.com/electron-userland/electron-builder/blob/00f46e6f60a8a762a2094264c2f2473f0a6334be/packages/app-builder-lib/src/platformPackager.ts#L319

I have already submitted a PR that supports disabling SanityCheckPackage.

**Comment by nikitakot** [comment]
@beyondkmp thanks! how long does it take for the pr to get through and get released eventually?

**Comment by mmaietta** [comment]
@nikitakot just need to verify the ☝️ approach then we can release today
