### ISSUE TITLE
com.apple.developer.endpoint-security.client entitlement

### ISSUE THREAD

**Issue by DeGolan** [electron-userland/electron-builder#8134]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18.18.2

* **Electron Version**: 28.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS universal

As part of the build process, I'm also compiling a Go process that the Electron app depends on. My challenge is that the Go process requires a different set of entitlements (com.apple.developer.endpoint-security.client) than the main Electron application. These entitlements are critical for the Go process to function correctly, but they should not apply to the entire Electron app to maintain security and compliance with macOS guidelines. I've been researching and experimenting with various configurations in electron-builder.yml and trying to apply custom entitlements specifically for the Go process, but I haven't found a clear path forward.

**Comment by mmaietta** [comment]
There's a new `sign` hook for `mac` (and `mas`) configurations that passes in the `SignOptions`. Specifically, there's a `optionsForFile` function that allows you to return different entitlements for different files
https://github.com/electron-userland/electron-builder/blob/fbb891c507ddefe3086258157c50abd866204fc8/packages/app-builder-lib/src/macPackager.ts#L278-L315

You could theoretically implement your own `optionsForFiles` function and use the `sign` hook. That would probably look something like this (untested, just whipped it up in Sublime Text, but should get you going in the right direction)
```
const path = require('path')
const { sign } = require('app-builder-lib/out/codeSign/macCodeSign')
const { CustomMacSignOptions, MacPackager } = require('app-builder-lib/out/macPackager')
const { PerFileSignOptions } = require("@electron/osx-sign/dist/cjs/types")

/**
 * @type {import("electron-builder").MacPackager} sign
 */
module.exports = async function sign(config: CustomMacSignOptions, packager: MacPackager) {
  const oldOptionsForFile = config.optionsForFile
  const optionsForFile = (filePath: string) => PerFileSignOptions = filePath => {
      if (filePath === `<path to your Go binaries>`) {
        const args = {
          entitlements: yourEntitlementsFilePath,
          requirements: packager.platformSpecificBuildOptions.requirements == null ? undefined : await packager.getResource(packager.platformSpecificBuildOptions.requirements),
        }
        return args
      }
      return oldOptionsForFile(filePath)
    }

  }
  await sign({ ...config, optionsForFile }, packager)
}
```

**Comment by DeGolan** [comment]
Do I need to give the path to this file on my electron.build.darwin.json file?
I didn't understand how can I use it.

**Comment by mmaietta** [comment]
Anything 24.12+.
https://github.com/electron-userland/electron-builder/releases/tag/v24.12.0

Used as `build.mac.sign=<path to sign.js file>`

**Comment by DeGolan** [comment]
@mmaietta hi, the code that you wrote on Sublime is not working (you are using types in js file), do you have a working example that I can use?

**Comment by mmaietta** [comment]
Remove the types then

**Comment by DeGolan** [comment]
Hi, its still not working man, do you have any working and tested version for this?
