### ISSUE TITLE
Can't run from network drive / Replicate setups

### ISSUE THREAD

**Issue by gbaumgart** [electron-userland/electron-builder#814]
Hi,
I was just toying with this. It seems I need to replicate on each target OS the same setup. Can someone confirm this ? 

I did run "npm run release" (build --x64 --publish never) on a network drive in windows (which is a smb share from ubuntu having all installed already and everything works). It last it very long til an error pops up : 'build is not recognized command'.

Does it need some fiddling to get it working on network drives with no additional npm install or is just not designed for? 

With almost 1TB data load it will last days creating the installers,.... 

thanks.

**Comment by develar** [comment]
You cannot and should not use network drive — npm node_modules is not cross-platform. But... electron-builder doesn't have native dependencies anymore, so, maybe, you can try to use full path to build instead of bin link (created by npm for you).

**Comment by gbaumgart** [comment]
well, what silly excuse, I've got ALL! my software running this way. But ok, I guess NodeJS have their own idea building good software running like any other. 

Saving resources is a good policy, also for NodeJS devs!

Never mind, just shocked this is indeed reality

**Comment by develar** [comment]
I suggest you to use Travis & AppVeour to build for all platforms. Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by gbaumgart** [comment]
travis: sure, also a way to build more dependencies and waste more real resources.. thanks anyway
