### ISSUE TITLE
vscode excute electron-build --universal on mac(M1) report have the same architectures(arm64/x64) and can not be in the same fat output file

### ISSUE THREAD

**Issue by ZONEZH** [electron-userland/electron-builder#8144]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  18.15.0

* **Electron Version**: 22.3.12
* **Electron Type (current, beta, nightly)**:current

* **Target**: electron-build --universal for arm64 and x64

<img width="1680" alt="error" src="https://github.com/electron-userland/electron-builder/assets/102672709/34157894-5fb8-40e4-b6c9-1d4670f558ae">

**Comment by ZONEZH** [comment]
There are folders arm64 and x64 in the clt sdk server directory, and the backend has already compiled and packaged the arm64 and x64 platforms. When I deleted these two folders and built the general package, everything was normal. It must be this folder that caused this error, but why did it report，I just copied a copy of this folder through extraResources

extraResources: [
   {
      from: './clt-sdk-server/mac',
      to: 'clt-sdk-server/mac',
    },
  ],

**Comment by mmaietta** [comment]
Please try updating to `next` electron-builder [v25.0.0-alpha.5](https://github.com/electron-userland/electron-builder/releases/tag/v25.0.0-alpha.5), it utilizes the official electron/rebuild npm package for rebuilding dependencies. If that still fails, please run with env var `DEBUG=electron-builder` and post back the logs
