### ISSUE TITLE
Mac Bundle Id is always prefixed with com.electron

### ISSUE THREAD

**Issue by smaccoun** [electron-userland/electron-builder#8146]
* **Node Version**: 18.9.1

* **Electron Version**: 24.13.3
* **Electron Type (current, beta, nightly)**: current

* **Target**:  mac (dmg, mas)

I can make something reproducible but first I want to check if the behavior is expected.

Every time I run `electron-builder --mac --config --universal` I am seeing bundleIds being set as `com.electron.mycompany`. In other words, `com.electron` is always prefixed. However, in my `electron-builder.yml` the very first line i have is `appId: com.mycompany.desktop`. 

I'm wondering if this is expected behavior because [in the docs ](https://www.electron.build/configuration/configuration.html) it says:

```
appId = com.electron.${name} String | “undefined” - The application id. Used as [CFBundleIdentifier](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102070) for MacOS and as [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx) for Windows (NSIS target only, Squirrel.Windows not supported). It is strongly recommended that an explicit ID is set.
```

So to me that looks like the bundle id will always begin with `com.electron`. If this is the case I guess that's okay, but it's a bit limiting, especially if we are adding our desktop app as just an extra platform to an existing app (which has a mobile app)

**Comment by smaccoun** [comment]
Apologies. There must have been something else in my build process causing this. Closing!

**Comment by keith-gardner** [comment]
were you able to pinpoint the issue? running into the same thing
