### ISSUE TITLE
`FlatpakOptions.files` has inconsistent type

### ISSUE THREAD

**Issue by rotu** [electron-userland/electron-builder#8160]
* **Electron-Builder Version**: 8e36be113489c1afa6ce5ee6cdda73049bc619a6

* **Node Version**: N/A

* **Electron Version**: N/A
* **Electron Type (current, beta, nightly)**: N/A

* **Target**: Linux

Type `FlatpakOptions` is incompatible with `PlatformSpecificBuildOptions` due to conflicting types of the `files` property.

`PlatformSpecificBuildOptions`:
https://github.com/electron-userland/electron-builder/blob/8e36be113489c1afa6ce5ee6cdda73049bc619a6/packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts#L53

whereas `FlatpakOptions`:
https://github.com/electron-userland/electron-builder/blob/8e36be113489c1afa6ce5ee6cdda73049bc619a6/packages/app-builder-lib/src/options/linuxOptions.ts#L219-L224

These two objects are merged together in `FlatpakTarget` but the type incompatibility is obscured behind an `as any` cast.

https://github.com/electron-userland/electron-builder/blob/8e36be113489c1afa6ce5ee6cdda73049bc619a6/packages/app-builder-lib/src/targets/FlatpakTarget.ts#L12-L16

**Comment by rotu** [comment]
Found during development on macOS. I'm not sure the actual runtime implications of this since I'm not on Linux.

**Comment by rotu** [comment]
not stale

**Comment by rotu** [comment]
not stale

**Comment by rotu** [comment]
Has this been fixed?

**Comment by mmaietta** [comment]
I took a look at this and am not sure what's wrong in the code. To remove the `any`, the code can just be changed to this
```
  readonly options: FlatpakOptions = {
    ...this.packager.platformSpecificBuildOptions,
    ...this.packager.config.flatpak,
    files: this.packager.config.flatpak?.files,
  }
```
The previous code should work as-is though as `this.name = flatpak` so it's overriding the `platformSpecificBuildOptions.files` already
```
...(this.packager.config as any)[this.name]
```

**Comment by rotu** [comment]
> Can you post an error log of what's not working for you?

I don't quite remember. I think I was just trying to figure out "what should I put in this config object?" and it looked funny to me that the `files` property can't accept a list of strings.

If this is not actionable, feel free to close.

**Comment by mmaietta** [comment]
Going to close this as it's correctly rendered in the documentation site as well https://www.electron.build/flatpak#files
