### ISSUE TITLE
productName in the electron builder is not applied.

### ISSUE THREAD

**Issue by Tuditi** [electron-userland/electron-builder#8165]
* **Electron-Builder Version**:  24.13.3

* **Node Version**:  18.16.0

* **Electron Version**: 28.2.7
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Linux

Specifying the `productName` in the Configuration file doesn't have any impact. `productName` specified in the package.json is used. 
(ref: https://www.electron.build/configuration/configuration#configuration)

Electron builder config:
- https://github.com/bloomwalletio/bloom/blob/develop/packages/desktop/electron-builder-config.ts

When logging through the build step we get the following name:
`Bloom - Alpha`

However, when the app opens we see the `productName` that was specified in [package.json](https://github.com/bloomwalletio/bloom/blob/develop/packages/desktop/package.json).

![image](https://github.com/electron-userland/electron-builder/assets/45079109/653e9636-d77c-46b3-847a-c930cd862052)

We have a [script](https://github.com/bloomwalletio/bloom/blob/develop/packages/desktop/scripts/fix-productName.js) that solves this issue in the CI by replacing the productName in the package.json before the app is built. It would be good if the documentation would be updated accordingly or if the issue would be fixed in general for future development.

**Comment by isti115** [comment]
Not stale, I'm also experiencing this.
Only build-time values seem to be affected by the setting in the `electron-builder` configuration, at runtime the strings from `package.json` take over.
My example is the name of the folder that gets created in `~/.config` under linux.
