### ISSUE TITLE
Regression in postinstall scripts

### ISSUE THREAD

**Issue by MaximKalinin** [electron-userland/electron-builder#8166]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 20.10.0

* **Electron Version**: 29.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: pkg

Postinstall script in pkg target receives wrong `$2` argument. 

There is a regression in electron-builder or one of its dependencies that was not documented. It first appeared in 24.13.2 version and is still present in the latest version (24.13.3). Specifically, I believe it is related to [this modification](https://github.com/electron-userland/electron-builder/compare/v24.13.1...v24.13.2#diff-aedc8a44cc67716e293933ffed3e8b7b1faf07a5764062782afadff11f91bfe5R178-R200).

Here is a minimal repository that reproduces the issue: https://github.com/MaximKalinin/electron-builder-test

Steps to reproduce: 
```
# clone the repo

npm install
npm run package

# install the packaged app from dist folder

cat /var/log/test.log
```

Expected result: the output of the file is `/Applications`

Actual result: the output of the file is `/Applications/electron-builder-test.app`

**Comment by mmaietta** [comment]
Hmmm the post install script never changed, the only change was adding `BundlePostInstallScriptPath` and `BundlePreInstallScriptPath` keys and script names to the Info.plist. I'm not familiar with `pkg` and was only provided guidance on the expected behavior, it shouldn't have changed the $2 arg though AFAICT. What is the impact of the $2 argument not working as it previously was?

If a postinstall script was `open -a $2` to autolauch the app, wouldn't `/Applications/electron-builder-test.app` be the correct arg?

**Comment by MaximKalinin** [comment]
> What is the impact of the $2 argument not working as it previously was?

I am trying to access files that are placed inside the installed app folder. For that I access `"${2}/electron-builder-test.app/resources/"`. It used to evaluate to `"/Applications/electron-builder-test.app/resources/"`, but now it evaluates to `"/Applications/electron-builder-test.app/electron-builder-test.app/resources/"` which does not exist.

> If a postinstall script was open -a $2 to autolauch the app, wouldn't /Applications/electron-builder-test.app be the correct arg?

The thing is, it used to be `open -a "${2}/electron-builder-test.app"`.

**Comment by mmaietta** [comment]
I still think it's expected behavior from my quick research
https://stackoverflow.com/a/11636246/3498974
```
$0 - Script path
$1 - Package path
$2 - Target location
$3 - Target volume`
```

My guess is that adding `BundlePostInstallScriptPath` added the proper configuration for the postinstall script to properly run

**Comment by MaximKalinin** [comment]
> I still think it's expected behavior from my quick research

Does it mean that all the previous versions were working incorrectly, passing `/Applications` as a second argument?

**Comment by mmaietta** [comment]
That's my current hypothesis. If you look through the [PR code diff](https://github.com/electron-userland/electron-builder/compare/v24.13.1...v24.13.2#diff-aedc8a44cc67716e293933ffed3e8b7b1faf07a5764062782afadff11f91bfe5R190-R195), there's nothing setting the path or changing the executable script itself. Rather, it's simply scanning the install scripts directory, identifying any that are preinstall/postinstall and adding that file entry into the Info.plist. It doesn't modify the pkg scripts' arguments itself.

**Comment by MaximKalinin** [comment]
What is the manual step for generating .pkg file? If I try `pkgbuild --root --scripts --component-plist` I will get the expected `/Applications` as a second argument.

> If you look through the [PR code diff](https://github.com/electron-userland/electron-builder/compare/v24.13.1...v24.13.2#diff-aedc8a44cc67716e293933ffed3e8b7b1faf07a5764062782afadff11f91bfe5R190-R195), there's nothing setting the path or changing the executable script itself.

The bug is not necessarily introduced by this PR, it could just be revealed now.

**Comment by MaximKalinin** [comment]
Ok, I think I found the real issue. It actually runs the postinstall script twice. Once for the application and once for the component specified in plist file. This seems like a bug to me.

**Comment by mmaietta** [comment]
Excellent debugging, thank you! I'll take a look when I have a chance, potentially this week if I can find time after work.

**Comment by KaminoRyo** [comment]
@MaximKalinin 
@mmaietta 
I know about this from a [Japanese technical memo](https://qiita.com/u83unlimited/items/4a7a97db1a82f0adaf78).
To summarize, 

- ``The behavior changes depending on the presence or absence of the file extension of the script (for some reason it runs twice if there is no `.sh`),'' 
- ``If there is no extension, it is determined to be a `top-level postinstall script.'' Isn't this the cause?"

**Comment by KaminoRyo** [comment]
related issue: #7299 #8063

@MaximKalinin 
There was a problem with the `scripts` option not working in the first place, and this commit came in.
How did you get postinstall to work until now? Did you create a `.app` file with electron-builder and create an installer using `pkgbuild` or `productbuild` in your own shell? 
(Since it wasn't working originally) I would like to know what comparison made it decide that "electron-builder is wrong".
I don't want to criticize you. but I rarely meet people who create pkg installers for Mac, so I'd like to deepen my knowledge.

**Comment by MaximKalinin** [comment]
Scripts were working fine for me, you can see it in the test repository: https://github.com/MaximKalinin/electron-builder-test.

**Comment by MaximKalinin** [comment]
I can confirm adding `.sh` extension solves the issue. I am fine with having that workaround.
