### ISSUE TITLE
Include and run external installer

### ISSUE THREAD

**Issue by FelikZ** [electron-userland/electron-builder#817]
* **7.11.4**: 

* **Win x64**: 

Is there any option to include and run external installers during the actual install?

For instance I have native modules that require [MS VS redist 2015 package](https://www.microsoft.com/en-us/download/details.aspx?id=48145), how I suppose to include and run it during the install?

Thanks

**Comment by develar** [comment]
Please use NSIS target and [customise](https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script) install script.

**Comment by develar** [comment]
> For instance I have native modules that require

I doubt that it is required for runtime. It should be compile time dependency, but not runtime.
