### ISSUE TITLE
nsis help

### ISSUE THREAD

**Issue by ZadgeIsCool** [electron-userland/electron-builder#8170]
i just have a .7z file with some files and i wanna make it exe with nsis the same way electron does it i just dont know how to

**Comment by MaximKalinin** [comment]
Do you mean creating NSIS installer without using electron-builder? If that is the case, there's an official website with some examples and tutorials: https://nsis.sourceforge.io/Main_Page.

**Comment by ZadgeIsCool** [comment]
i understand but electron's nsis process is very complex with a bunch of
app-builder-lib and app-builder-bin and NSIS and 7z and 7za and nsi and nsh
and all that stuff its not just simple NSIS

**Comment by ZadgeIsCool** [comment]
maybe u cant tell me everything in a short sentence but ive looked for the
NSIS 3.04 you use in electron but i couldnt find the binary, i
stumbled upon this:
https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z
but it seems like its not it since its detected by avast antivirus, would
just getting this:  electron-builder-binaries/nsis at master ·
electron-userland/electron-builder-binaries (github.com)
<https://github.com/electron-userland/electron-builder-binaries/tree/master/nsis>
along
with the nsis7z plugin good enough and do the same thing? if possible
please share the current electron-builder NSIS files along with the
plugins, Thanks!

**Comment by MaximKalinin** [comment]
> i stumbled upon this: https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z but it seems like its not it since its detected by avast antivirus

Yes, I think this is what electron-builder uses: 
https://github.com/electron-userland/electron-builder/blob/fa6fc16040a93c6ee751a7a27ab6eeb1dbdd31a7/packages/app-builder-lib/src/targets/nsis/nsisUtil.ts#L38 https://github.com/electron-userland/electron-builder/blob/fa6fc16040a93c6ee751a7a27ab6eeb1dbdd31a7/packages/app-builder-lib/src/binDownload.ts#L18-L40

There's quite a few things going on, the main directory containing the source code seems to be https://github.com/electron-userland/electron-builder/tree/fa6fc16040a93c6ee751a7a27ab6eeb1dbdd31a7/packages/app-builder-lib/src/targets/nsis and the one containing `.nsh`, `.nsi` templates is https://github.com/electron-userland/electron-builder/tree/fa6fc16040a93c6ee751a7a27ab6eeb1dbdd31a7/packages/app-builder-lib/templates/nsis.

What I believe can help you is git history: you could go through it searching for commits containing "nsis" or "windows installer". For example, here is the commit containing the early nsis implementation: https://github.com/electron-userland/electron-builder/commit/1779ac5d4b1e122f46e2c25783fe160826a94bda.

**Comment by ZadgeIsCool** [comment]
Thanks for your help! After searching for a while, I figured out how it
works. My goal was to go to the "win-unpacked" folder and remove
unnecessary files and packages, and then build them. That's why I asked
about electron packages and builds using NSIS with the nsis7z plugin. I
created my builder and built it, but the issue is the file size is still
big because the electron exe (the unpacked one) contains many things. The
aim is to make the file size as small as possible. My suggestion is to
compress the main exe and remove unneeded components based on the type of
application you're making. For example, if it's a browser app, only include
necessary files like the chromium engine. However, if it's a silent
optimizer app, don't include the chromium engine. I'm referring
specifically to the main exe, but it would be great if this could also
apply to other files!
