### ISSUE TITLE
electron-updater and github provider doesn't work when files have spaces in them

### ISSUE THREAD

**Issue by theogravity** [electron-userland/electron-builder#8172]
* **Electron-Builder Version**:  24.13.3

* **Node Version**:  20

* **Electron Version**: 29
* **Electron Type (current, beta, nightly)**: current

5.3.0

* **Target**: mac

If my built app / package uses a space in the name, the resulting `latest-mac.yml` file will list the `url` with the appropriate spaces, eg `My Application-v1-universal-mac.zip`.

However, when using the github provider, the download will fail because when you publish files to github releases, they convert spaces to a period / dot, so the resulting download being offered from GH releases is actually `My.Application-v1-universal-mac.zip`.

The logic for reading the `latest.yml` / `latest-<platform>.yml` manifest needs to account for this behavior when using the github provider.

**Comment by mlshv** [comment]
I've noticed it too. Had to remove spaces from my app's name because of it

**Comment by parz3val** [comment]
This is because github replaces your space with ., Use '-' when you build your app and it'll work.

**Comment by theogravity** [comment]
> This is because github replaces your space with ., Use '-' when you build your app and it'll work. 

Doesn't help when the app name itself has spaces in it.

And yes, as noted in the issue you can work around it but it's not ideal.

**Comment by parz3val** [comment]
> And yes, as noted in the issue you can work around it but it's not ideal.

I literally have the same issue. But I am only replacing the space in the name of installer not the app itself. And yes, I agree its not ideal.
