### ISSUE TITLE
Auto-update error for Debian installers

### ISSUE THREAD

**Issue by akshitcompro** [electron-userland/electron-builder#8177]
* **Electron-Builder Version**:  24.9.1

* **Node Version**: 18.18.2

* **Electron Version**: 13.6.9
* **Electron Type (current, beta, nightly)**: NA

* **Electron-updater Version**: 6.1.8

* **Target**: Debian

Facing the below issue when trying to auto-update our electron application (based on Debian) on a Chromebook.  We have not been able to pin-point the cause of this issue or why this issue might occur. It is to be noted that it is not occurring on all Chromebook machines since we were able to achieve successful auto-update on some of them.
<img width="601" alt="image" src="https://github.com/electron-userland/electron-builder/assets/85864914/938e283f-9c70-406b-acbc-2aa1f6d609b5">

Could anyone please advise on the next steps here?

**Comment by akshitcompro** [comment]
Still facing the above issue

**Comment by Aman-Sahota** [comment]
I am also facing the same issue

**Comment by nikhil072000** [comment]
facing the same #issue

**Comment by mmaietta** [comment]
Can you try adding additional logging to electron-updater via https://www.electron.build/auto-update#debugging

Looking to get more logs on what `cmd` is being executed and with what `args`
https://github.com/electron-userland/electron-builder/blob/145ecb66baabd39ca523ebbba26ef484384fe8e7/packages/electron-updater/src/BaseUpdater.ts#L119-L127
