### ISSUE TITLE
Output .exe icon (and desktop shortcut accordingly) reverts to default electron icon

### ISSUE THREAD

**Issue by dale-als** [electron-userland/electron-builder#8187]
* **Electron-Builder Version**:  24.13.3

* **Node Version**: 18.17.1

* **Electron Version**: 30.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows NSIS

I have icon.ico in my buildResources folder, that include 16x16, 32x32, 48x48 and 256x256 icons.
Output installer has the correct icon, but unpacked exe and all system shortcuts (excluding tray, which is correct as well) has default Electron icon. What might be the case here?

My nsis config includes only shortcutName and deleteAppDataOnUninstall options

**Comment by shengzhou1216** [comment]
same issue.

**Comment by liuliu-dev** [comment]
same issue, not stale

**Comment by drewklein20** [comment]
same issue
