### ISSUE TITLE
MacOS builds unusable: App is damaged and can't be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by Maxou44** [electron-userland/electron-builder#8191]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 22.0.0

* **Electron Version**: 30.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS

I've developed an electron application, but it seems that the DMG builds I make available through my Github Actions pipeline don't work.

I don't sign the application, I don't have an Apple Developper account, but normally there's just a warning that you can override by pressing CTRL + Clic and “Open”.

When users try to install it but get an error when launching:
![image](https://github.com/electron-userland/electron-builder/assets/8138585/33e8e4cb-c784-48a9-9af7-0c3ac4f6f2a0)

If they build the application on their machine, the DMG is functional, can be installed and the application launches without problems.

My Electron Builder configuration is available here: https://github.com/brick-a-brack/eagle-animation/blob/dev/electron-builder.yaml

Any ideas?

**Comment by cpvalente** [comment]
I am not related to electron-builder but am here looking for some help with an issue and thought I may help you as well

This is a common and well documented behaviour for apps that have not been notarized
https://discussions.apple.com/thread/253714860?sortBy=best

This requirement was introduced in a recent-ish OS and it affects distributions for Apple silicon processors. If you make distributions for old intel processors you will see the previous error "unknown developer". 

Your users will still be able to circumvent this by disabling gatekeeper as described in the thread.

**Comment by robincsamuel** [comment]
> This is a common and well documented behaviour for apps that have not been notarized https://discussions.apple.com/thread/253714860?sortBy=best

Thanks! That worked. Here's the relevant section for others.

<blockquote>
My goodness. And there even is an incompetent reply from Apple themselves.

When an application gets downloaded from any source other than those that Apple seems suited, the application gets an extended attribute "com.apple.Quarantine". This triggers the message: "<application> is damaged and can't be opened. You should move it to the Bin."

Remove the attribute and you can launch the application.

To do this, open a console and type:

`$ xattr -c <path/to/application.app>`
</blockquote>
