### ISSUE TITLE
Electron updater delete all non-app files/folders in the installation folder

### ISSUE THREAD

**Issue by m-mohamedin** [electron-userland/electron-builder#8196]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 20

* **Electron Version**: 28.1.0
* **Electron Type (current, beta, nightly)**: current

electron-updater: 6.1.7

* **Target**: Windows

When electron-updater updates an application installed in Windows in a custom location `c:\my_app`, any file/folders added to that custom location is also deleted.

Non-app files/folders should be kept as users can lost their data this way

**Comment by VectorGC** [comment]
This is actual
