### ISSUE TITLE
Arch is wrong in artifact name on Linux deb x64 target

### ISSUE THREAD

**Issue by m-mohamedin** [electron-userland/electron-builder#8197]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 20

* **Electron Version**:28.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux (Debian)

We use the following configuration (the important part shown)
```
{
   "artifactName": "${productName}-${arch}-${version}.${ext}",
   "linux": {	
      "target": [
      { "target": "deb", "arch": [
          "x64",
          "arm64"
        ]
      }
    ],
  }
}
```
But, in recent builds we get the artifactName arch as amd64 instead of x64 as before (and as other targets and systems do)

**Comment by mmaietta** [comment]
What version was this previously working on? I can try git diff-ing when time allows me to return to this project

**Comment by m-mohamedin** [comment]
I'm sorry, I forwarded the issue as is but I found out this was the name since 2017
