### ISSUE TITLE
how can we change the download path for updater

### ISSUE THREAD

**Issue by aravind-ui** [electron-userland/electron-builder#8209]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.16.0

* **Electron Version**: 24.8.8
* **Electron Type (current, beta, nightly)**:

* **Target**: 

Now it's targeted to download the updated version to the local app data
C:\Users\ {{userName}}\AppData\Local\ {{appName}}-updater

I need to download it to the custom folder path
**Example: C:\{{someFolderName}}\**

**Comment by beyondkmp** [comment]
Currently, customizing the download directory for updater is not supported.
