### ISSUE TITLE
There is a build error when the configuration file on window is ts

### ISSUE THREAD

**Issue by just-ads** [electron-userland/electron-builder#8212]
* **Electron-Builder Version**: ^24.13.3

* **Node Version**:  v20.11.0

* **Electron Version**:^30.0.3
* **Electron Type (current, beta, nightly)**:current

* **Target**: win

![1715398025720](https://github.com/electron-userland/electron-builder/assets/50706050/c3430eab-e98a-4baa-9600-584d17136f13)

It may be because `platform.name` in `defaultOutDir` in the **loadTSConfig file** is not the correct value.
It actually returns `platform`, and does not return `win32` as expected.
![image](https://github.com/electron-userland/electron-builder/assets/50706050/d419ade2-87ea-48c2-bcac-838c56cfc793)
Should os.platform() be used?
![image](https://github.com/electron-userland/electron-builder/assets/50706050/35912cbd-a9c2-40a8-9cda-8786f16fbe1a)

**Comment by mmaietta** [comment]
Blocked by https://github.com/mighdoll/config-file-ts/pull/22

**Comment by just-ads** [comment]
> Blocked by [mighdoll/config-file-ts#22](https://github.com/mighdoll/config-file-ts/pull/22)

`config-file-ts` Looks to have fixed this bug. [Fixed platform selection in loadTsConfig.ts](https://github.com/mighdoll/config-file-ts/commit/eae1b27ec5e3b8435fc7250c1abcd10d2a40ffb1)
However, the read-config-file dependency used by electron-builder has not updated the config-file-ts dependency.
This library seems to be unmaintained? It was last updated two years ago.

**Comment by mmaietta** [comment]
Looks like there's a dependency in between. I've opened up a PR with that project, read-config-file https://github.com/develar/read-config-file/pull/19
