### ISSUE TITLE
Code signing for windows and mac in macOS

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#822]
* **Version**: 7.13.0

* **Target**: macOS and Win (squirrel and nsis)

Could you provide different env variable for signing osx and win ?

with `build -mw --x64 --ia32` with CSC_LINK and CSC_KEY_PASSWORD set with certificat for win and CSC_NAME for macOS certificat, the build don't work ! Building separately for mac and win work fine..

If I set certificateFile and certificatePassword in place of CSC_LINK and CSC_KEY_PASSWORD in package.json build.win, it don't work again.

Could you try that and give me the right configuration ? Thank

**Comment by develar** [comment]
> If I set certificateFile and certificatePassword in place of CSC_LINK and CSC_KEY_PASSWORD in package.json build.win, it don't work again.

As far I see, it should work — `certificateFile` is checked before `CSC_LINK`.

In any case — `WIN_CSC_LINK` env added. (please the same password for win and mac certs).

**Comment by popod** [comment]
Thanks for answer. Why should I use the same password for win and mac certs ? This is not my case, so why could we not define different pass for mac and win ?

**Comment by develar** [comment]
Fixed. `WIN_CSC_KEY_PASSWORD` will be supported in next electron-builder version.

**Comment by popod** [comment]
Perfect ! Thanks a lot.
