### ISSUE TITLE
Ignore more files by default on build

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#823]
Why do you not ignore this files by default on build ?
- package.json
- node_modules/exemples
- node_modules/src

They aren't needed by the app and take place for nothing.

**Comment by develar** [comment]
`package.json` — maybe required. Not going to be deleted.

`node_modules/examples` — makes sense. 👍 

`src` — maybe required. Not safe. TBD — I am not sure. It is npm module author responsibility to taker care of this.

I am going to see what `yarn` does on `clean`.

**Comment by develar** [comment]
__tests__, tests, example, examples were added to default ignores list. For any other files – please use `yarn`.

**Comment by popod** [comment]
Perfect, thanks !

**Comment by popod** [comment]
By telling me to use yarn, you would say that use yarn in place of npm ?

**Comment by develar** [comment]
Yarn cannot be used right now because of https://github.com/yarnpkg/yarn/issues/756, but `yarn clean` works.
