### ISSUE TITLE
Docs for `NotarizeNotaryOptions` stop mid-sentence

### ISSUE THREAD

**Issue by ferenc-a** [electron-userland/electron-builder#8230]
Here's the link: https://www.electron.build/configuration/mac.html#NotarizeNotaryOptions

And this is what is displayed.
![image](https://github.com/electron-userland/electron-builder/assets/140697579/e43e1fa5-c5d4-46ac-b14d-1213dfec9e34)

All instances of this sentence are somewhat different: https://github.com/search?q=repo%3Aelectron-userland%2Felectron-builder+%22The+team+ID+you+want+to+notarize+under+for+when+using%22&type=code

The one in `scheme.json` doesn't mention deprecation, and the one in `mac.md` is the one that stops mid-sentence, possibly because of faulty or obsolete auto-generation. The one at `macOptions.ts` seems to be the source of truth.

**Comment by ferenc-a** [comment]
This is a minor issue, but still definitely not fixed.
Is there a ticket tracking static docs generation that might relate to this?

**Comment by mmaietta** [comment]
There isn't a "central" ticket, but it's an issue I'm aware of. I intend on having the entire docs site (hopefully) redesigned to be more fluid and intuitive, as well as optimize the API doc generation that is current inter-spliced with static markdown doc content.

**Comment by mmaietta** [comment]
Resolved: https://www.electron.build/mac#notarize
