### ISSUE TITLE
The issue lies in the organization and clarity of the electron-builder documentation, as well as the lack of an explanation for the MetadataDirectories type and the purpose of directories.

### ISSUE THREAD

**Issue by JohnBrayden** [electron-userland/electron-builder#8237]
### The issue lies in the organization and clarity of the electron-builder documentation, as well as the lack of an explanation for the MetadataDirectories type and the purpose of directories.

I would like to inquire about the type of [MetadataDirectories](https://www.electron.build/configuration/configuration#MetadataDirectories) in the **electron-builder** documentation, as it is not clear to me at all. I have searched for its type and couldn't find whether it is an array or an object, nor do I know what properties it contains. I searched the internet a bit and found that some of the properties of this type are output and app, but the problem is that the documentation itself does not explain or clarify them at all. Even after extensively searching the documentation for something clear to guide me, I found nothing.

I believe that the documentation needs a complete update because it lacks clarity and explanation. As we progress in technology, we have reached a point where documentation is clear, comprehensive, and includes simple and clear explanations in many technologies. However, the electron-builder documentation is still unorganized and **unclear**.

Furthermore, in the documentation, [MetadataDirectories](https://www.electron.build/configuration/configuration#MetadataDirectories) is indicated as a clickable link or button to understand its type, but when I click on it, nothing happens, and it does not take me to a page for clarification. It seems like a button without any purpose.

There is also no explanation of what exactly `directories` refers to. Are they the directories located in the `dist` folder? Or are they located somewhere else? What exactly is the purpose of specifying the `directories`?

All these matters are difficult to understand and comprehend without an explanation. Even if they are clear to some, **not everyone has a high level of expertise or extraordinary intelligence to understand things without a clear (even if simple) explanation**.

**Comment by mmaietta** [comment]
Thanks for chiming in.

So I've been wanting for awhile to have the entire docs site redone entirely as the build scripts are a mess to understand on their own. That being said, there's a lot of custom static pages being merged with autogenerated content in the repo's `/docs` directory. To cap it off, I also don't have access to the netlify site that is hosting the domain either, so I'm trying to figure out if I need a replacement.

Posting this all here with a question for you (and the community) as I'm not familiar with doc generators. What packages/tools have you used previously to generate documentation sites? I can't use a generic typescript->jsdoc converter as we need to have further documentation generated or static "tutorial" pages interspersed throughout the site.

**Comment by JohnBrayden** [comment]
Finally, a deep thank you for the intention to start new, modern, and understandable documentation.

In truth, I do not have extensive experience, as I have never built any documentation myself. However, I am confident that the community will be eager to start helping and they have more expertise.

I only have some basic information and sites to share with you, and I hope you will choose the best sites that suit you, and most importantly, those that make the documentation clearer and more organized:

1. VitePress
2. Docusaurus
3. Sphinx
4. GitBook
5. MkDocs
6. Jekyll
7. Hugo
8. Docsify
9. VuePress

I find that VitePress is somewhat suitable, but it ultimately depends on what works best for you.

Some of these tools offer you the ability to customize and build all the documentation in your own style, so it is best to choose them over others. VitePress is one such tool that provides customization capabilities.

**Comment by mmaietta** [comment]
Honestly, I may look into contracting a dedicated API/SDK documentation engineer for rewriting the website entirely. I'll continue investigating the technologies in the interim, but I'm thinking a brand new website may work best for organizing all the details, especially the API-related TSDocs and any hyperlinks/organization between them (I do agree it's a mess currently)

**Comment by JohnBrayden** [comment]
> Honestly, I may look into contracting a dedicated API/SDK documentation engineer for rewriting the website entirely. I'll continue investigating the technologies in the interim, but I'm thinking a brand new website may work best for organizing all the details, especially the API-related TSDocs and any hyperlinks/organization between them (I do agree it's a mess currently)

@mmaietta 

Great idea! The distinction and uniqueness in creating custom documentation is excellent, and I wanted to suggest it to you earlier, but I thought you preferred to use ready-made technologies.

The most important thing to consider is the clarity and simplicity of the documentation. It shouldn't be cluttered with everything on one page and too many overlapping words. Additionally, the documentation should be set up as an SPA (Single Page Application) so that navigation between topics doesn't require page loading.

I wish you success and look forward to the new documentation for electron-builder!
