### ISSUE TITLE
hdiutil 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE' when building dmg.

### ISSUE THREAD

**Issue by connorgmeehan** [electron-userland/electron-builder#8238]
* **Electron-Builder Version**: ^24.13.3

* **Node Version**: 16.20

* **Electron Version**: 14.2.9
* **Electron Type (current, beta, nightly)**:

* **Target**: ac

When building the DMG for MacOS I get a issue with hdiutil that happens sporadically on x86_64 Mac.

```
• building        target=macOS zip arch=x64 file=dist_electron/bundled/dist/EyeJack Creator 2024-3.4.4-mac.zip
  • building        target=DMG arch=x64 file=dist_electron/bundled/dist/EyeJack Creator 2024-3.4.4.dmg
  • Above command failed, retrying 5 more times
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • Above command failed, retrying 0 more times
  • building block map  blockMapFile=dist_electron/bundled/dist/EyeJack Creator 2024-3.4.4-mac.zip.blockmap
  ⨯ hdiutil process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: hdiutil process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/Users/connormeehan/projects/eyejack/eyejack-creator/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by connorgmeehan** [comment]
**Unmount the previous DMG**.  I had mounted the DMG from the `dist_electron/` folder and therefore `hdiutil` couldn't mount another DMG with the same name.  Reposting this as I didn't see this as an answer and it seems to be a frequent issue.  I hope this helps others avoid losing time over such a silly error. :)

**Comment by wangXP001** [comment]
I also encountered the same problem, how did you solve it

**Comment by bradjasper** [comment]
@wangXP001  I was having this same issue, the solution was ensuring my artifact name didn't have any strange special characters in it (in my case it was "@").

```
dmg:
    artifactName: ${name}-${version}.${ext}
```

My config was setup like this, but I had accidentally renamed my project to be "@project/desktop" — and the "@" was messing up hdiutil.

You can get useful debugging info with:

DEBUG=* DEBUG_DMG=true ELECTRON_BUILDER_VERBOSE=true  electron-builder ....

**Comment by funwithtriangles** [comment]
> @wangXP001 I was having this same issue, the solution was ensuring my artifact name didn't have any strange special characters in it (in my case it was "@").
> 
> ```
> dmg:
>     artifactName: ${name}-${version}.${ext}
> ```
> 
> My config was setup like this, but I had accidentally renamed my project to be "@project/desktop" — and the "@" was messing up hdiutil.
> 
> You can get useful debugging info with:
> 
> DEBUG=* DEBUG_DMG=true ELECTRON_BUILDER_VERBOSE=true electron-builder ....

**MONOREPO USERS TAKE NOTE**

Thanks, this fixed it for me! I have a monorepo and my packages are named `@myAppName/foo`.

I changed it to:

 ```
> dmg:
>     artifactName: myAppName-${version}.${ext}
> ```
