### ISSUE TITLE
"one-click installer executes uninstall section in the silent mode" causes all MessageBox with /SD flag to go silent even if user didn't run uninstaller with /S flag?

### ISSUE THREAD

**Issue by Agritite** [electron-userland/electron-builder#8240]
* **Electron-Builder Version**:  24.10.0

* **Node Version**: 18.20.2

* **Electron Version**: 28.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: NSIS

So it seems like due to here:
https://github.com/electron-userland/electron-builder/blob/278a3df3c738dbe0d2240f338e901774b7d578c5/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L15-L20

all calls to `MessageBox` with `/SD` flag in the `customUnInit` and `customUninstall` macro would go into silent mode regardless of whether the user actually runs the uninstaller with the `/S` flag?

This is not ideal, because we have a messagebox to confirm reboot if `RMDir /REBOOTOK` is required. We definitely do not want to reboot without user's consent. Any other options? or is manually calling `${GetOptions} "/S"` the only way?

**Comment by mmaietta** [comment]
I must admit that I'm not familiar with nsis scripting but I'd be happy to review/test a PR changing this behavior. Setting up a developer environment is fairly easy :)
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment
