### ISSUE TITLE
25.0.0-alpha.9 was released to npm as "latest"

### ISSUE THREAD

**Issue by AviVahl** [electron-userland/electron-builder#8244]
The new version was released as "latest", overriding the previous "24.13.3"

```sh
$ npm dist-tags electron-builder
latest: 25.0.0-alpha.9
next: 25.0.0-alpha.8
```

can also be seen on: https://www.npmjs.com/package/electron-builder?activeTab=versions

**Comment by leevva** [comment]
Hi! When you fix this?

**Comment by AviVahl** [comment]
It can be easily fixed using https://docs.npmjs.com/cli/v10/commands/npm-dist-tag (has to be someone with publish access to the npm package)

**Comment by lutzroeder** [comment]
@mmaietta any insights if this was intentional or can be rolled back?

See #8241

**Comment by lutzroeder** [comment]
@mmaietta looks like same happened with `electron-builder@25.0.0-alpha.10`.

See #8253

**Comment by mmaietta** [comment]
Oh gosh darn it. I'll fix that asap. Not sure why the automation isn't working correctly now despite no changes. Thanks for the quick heads up!

**Comment by mmaietta** [comment]
Thanks for notifying me! I've updated the `latest` tag for app-builder-lib. Not sure why it was frozen on the alpha version, it seems other packages within electron-builder also have the same issue. I'm trying to update them currently but am receiving 400 HTTP errors for some of the packages
