### ISSUE TITLE
electron-updater  ERR_UPDATER_INVALID_SIGNATURE

### ISSUE THREAD

**Issue by zengxiaoya** [electron-userland/electron-builder#8246]
"electron-updater": "^6.1.8",

**Comment by zengxiaoya** [comment]
NsisUpdater.js  code Error
const signatureVerificationStatus = await this.verifySignature(destinationFile);
                if (signatureVerificationStatus != null) {
                    await removeTempDirIfAny();
                    // noinspection ThrowInsideFinallyBlockJS
                    throw (0, builder_util_runtime_1.newError)(`New version ${downloadUpdateOptions.updateInfoAndProvider.info.version} is not signed by the application owner: ${signatureVerificationStatus}`, "ERR_UPDATER_INVALID_SIGNATURE");
                }

**Comment by zengxiaoya** [comment]
此段代码的null判断存在逻辑问题

**Comment by xlei1123** [comment]
the same error
