### ISSUE TITLE
How to add aditional keys to the Info.plist for mac / mas builds

### ISSUE THREAD

**Issue by screenmeet** [electron-userland/electron-builder#825]
I want to add a few additional keys to the Info.plist that is generated when building the app, but am not sure how to properly achieve this.

I want to add some extra keys, such as CFBundleURLSchemes and NSuserNotificationAlertStyle.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/549#issuecomment-229285326

CFBundleURLSchemes — please use fileAssociations. https://github.com/electron-userland/electron-builder/wiki/Options#FileAssociation

**Comment by screenmeet** [comment]
The documentation there seems pretty sparse. Not clear on how to set the values. And what about other plist values, like NSuserNotificationAlertStyle or anything else for that matter?

**Comment by develar** [comment]
> what about other plist values, like NSuserNotificationAlertStyle or anything else for that matter?

@screenmeet Yes, `build.extend-info` is not documented. Use `build.extend-info` (https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#extend-info) to add custom entries to the Info.plist.
