### ISSUE TITLE
Encountering EBUSY: resource busy or locked  error in electron-builder 25.0.0-alpha.9

### ISSUE THREAD

**Issue by holizero** [electron-userland/electron-builder#8250]
Encountering 'EBUSY: resource busy or locked' error when using 'asar: false' option in electron-builder 25.0.0-alpha.9.

The error mainly occurs in the '@colors' module and downgrading to version 24.13.1 resolves the issue.

**Comment by Rebel028** [comment]
Can confirm this error on windows (including windows runners for Github Actions).
Works just great together with https://github.com/electron-userland/electron-builder/issues/8244 
Now I know that running `npm install -g electron-builder` with no version specified is a bad idea 😄

**Comment by holizero** [comment]
> Can confirm this error on windows (including windows runners for Github Actions). Works just great together with #8244 Now I know that running `npm install -g electron-builder` with no version specified is a bad idea 😄

Thanks !

**Comment by mmaietta** [comment]
Can you create a minimum reproducible repo for this issue? I can take a look at it locally, hopefully can reproduce it on my parallels Windows arm64 VM

**Comment by dowmeister** [comment]
this still happens also on electron-builder 26 and, as far i've reproduced - but not sure if it has really sense - restarting vscode when there are other vscode instances running will give the error.
if the vscode restarted is the only one open, the build work...

**Comment by badspider7** [comment]
have the same question
