### ISSUE TITLE
25.0.0-alpha.9 bundles @electron/remote wrongly into Windows app.asar

### ISSUE THREAD

**Issue by pbi-qfs** [electron-userland/electron-builder#8252]
* 25.0.0-alpha.9

* **Node Version**: v18.13.0

* **Electron Version**: 30.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

The javascript files of @electron/remote are all placed into `app.asar/node_modules/@electron`, without any inner directory structure, so the internal relative `requires` fail.

**Comment by mmaietta** [comment]
@beyondkmp can you take a look at this? I believe it's due to the new app-builder-bin alpha changes

**Comment by beyondkmp** [comment]
Okay, I'll try to reproduce it first.
