### ISSUE TITLE
electron打包报错

### ISSUE THREAD

**Issue by 955965** [electron-userland/electron-builder#8255]
在我怕的vue3项目里使用了elctron和electron-builder
版本为 "electron": "^31.0.0",
            "electron-builder": "^24.13.3"
在项目打包的时候总是报错Get "https://npm.taobao.org/mirrors/electron/31.0.0/electron-v31.0.0-win32-x64.zip": proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.

这是什么原因？
![1717747706500](https://github.com/electron-userland/electron-builder/assets/172348498/615e6528-d543-4e2f-a1b6-2d7f0f2c1e2d)

**Comment by ifurther** [comment]
Hi you picture show the error link which is belong `gihtub.com`, and it is not `npm.taobao.org`
