### ISSUE TITLE
Error: No valid update available, can't quit and install

### ISSUE THREAD

**Issue by James-Shared-Studios** [electron-userland/electron-builder#8257]
* **Electron-Builder Version**: ^24.9.13

* **Node Version**: 21.4.0

* **Electron Version**: ^27.1.3
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: ^6.1.7

* **Target**: Windows 10 Pro 22H2

We have experienced the exact same issue as reported many years ago here: [Error: No update available, can't quit and install #3269](https://github.com/electron-userland/electron-builder/issues/3269
) and [Error no valid update available, can't quite and install / EExist file already exist](https://github.com/electron-userland/electron-builder/issues/7069). 

the latest update has been downloaded, but it can not be installed, and getting the following error:
`error:  "Error: No valid update available, can't quit and install\n    at m.install (C:\\Users\\Portal\\AppData\\Local\\Programs\\pragent-dev\\resources\\app\\dist\\main\\webpack:\\pragent-dev\\node_modules\\electron-updater\\out\\BaseUpdater.js:45:32)\n    at m.quitAndInstall (C:\\Users\\Portal\\AppData\\Local\\Programs\\pragent-dev\\resources\\app\\dist\\main\\webpack:\\pragent-dev\\node_modules\\electron-updater\\out\\BaseUpdater.js:13:34)\n    at IpcMainImpl.<anonymous> (C:\\Users\\Portal\\AppData\\Local\\Programs\\pragent-dev\\resources\\app\\dist\\main\\webpack:\\pragent-dev\\src\\main\\main.ts:1086:29)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)" ---- event:  {}`

It does not seem that a valid solution has ever been discovered. Is there any solution available now? Please advise. Thank you.

**Comment by MadEddieFFS** [comment]
We had this recently and it was due to the signing certificate not validating as electron updater deletes the downloaded files and so this next step fails to find the files

**Comment by James-Shared-Studios** [comment]
> We had this recently and it was due to the signing certificate not validating as electron updater deletes the downloaded files and so this next step fails to find the files

How did you resolve the issue please? Thank you.
