### ISSUE TITLE
Notarize notarytool JSON parsing error

### ISSUE THREAD

**Issue by Drecula** [electron-userland/electron-builder#8258]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: v20.14.0

* **Electron Version**: 30.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac M1

I am trying to notarize my app. In electron-builder.env, I have
`APPLE_API_KEY="my apple id"
APPLE_API_KEY_ID="my apple api key"
APPLE_API_ISSUER="my apple api issuer"`

I do not have 'notarize' in my electron-builder.yml. My understanding is if I have these env vars, electron-builder will automatically notarize.

I have started walking back versions until I find one where this works. I will update this thread when I confirm the bugless version.

I get the below error. 
Please help.
Thanks!

` • signing         file=dist/mac-arm64/MyApp.app platform=darwin type=distribution identity=9067B593388510D403BB17F8DC30B39D5077AD50 provisioningProfile=none
  ⨯ Unexpected token 'E', "Error: The"... is not valid JSON  failedTask=build stackTrace=SyntaxError: Unexpected token 'E', "Error: The"... is not valid JSON
SyntaxError: Unexpected token 'E', "Error: The"... is not valid JSON
    at JSON.parse (<anonymous>)
    at /Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/node_modules/@electron/notarize/src/notarytool.ts:79:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/node_modules/@electron/notarize/lib/notarytool.js:28:58)
    at processTicksAnspufijections (node:internal/process/task_queues:95:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at readDirectoryAndSign (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/macPackager.ts:478:29)
    at MacPackager.signApp (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/macPackager.ts:488:11)
    at MacPackager.doSignAfterPack (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/platformPackager.ts:336:21)
    at MacPackager.doPack (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/platformPackager.ts:321:7)
    at MacPackager.pack (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/macPackager.ts:198:9)
    at Packager.doBuild (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/packager.ts:445:9)
    at executeFinally (/Users/spufi/gitRepos/my-app/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/packager.ts:379:31)
    at Packager.build (/Users/spufi/gitRepos/my-app/node_modules/app-builder-lib/src/packager.ts:340:12)
    at executeFinally (/Users/spufi/gitRepos/my-app/node_modules/builder-util/src/promise.ts:12:14)`

**Comment by Drecula** [comment]
Others have commented on this as well. This uses electron/notarize, which expects the notarize keys as camelCase. Perhaps the expected camelCase values could be a notarize config option instead of or in addition to the 'fully automatic' mode where electron-builder detects the notarize k/v pairs from env?

**Comment by Nantris** [comment]
Same issue. Quite a strange and difficult to diagnose one. I'm not sure where I should even start looking, but it does seem related to notarization.

**Comment by Nantris** [comment]
Thanks for sharing. When I downgrade though, it works fine, so no clues there unfortunately.

**Comment by stoefln** [comment]
@Nantris, which version is the one that still works? Want to downgrade too. Need this fixed ASAP

**Comment by stoefln** [comment]
Found a solution for myself:

After downgrading to v24.9.1, I got this information: 
```
• selecting signing options  file=dist/mac/myapp.app/Contents/Resources/icon.icns entitlements=build/entitlements.mac.plist hardenedRuntime=true timestamp=undefined requirements=undefined
  • selecting signing options  file=dist/mac/myapp.app entitlements=build/entitlements.mac.plist hardenedRuntime=true timestamp=undefined requirements=undefined
  • executing       file=security args=delete-keychain /var/folders/s...f0be6.keychain
  • executed        file=security
  ⨯ Failed to notarize via notarytool

Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.
  failedTask=build stackTrace=Error: Failed to notarize via notarytool
                                                                                                                                                                                                                                                                                                         Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.
```

So I logged in to https://developer.apple.com/, saw that a license agreement needed to be accepted, did that, and things worked again.

**Comment by Nantris** [comment]
Unfortunately that's not the root issue here since the old version produces no error for us.

**Comment by Nantris** [comment]
Thank you but I just explained for the second time in this thread, that that is not our issue.

**Comment by pimterry** [comment]
I also faced this issue - with no license agreements appearing when logging into https://developer.apple.com/.

Downgrading from 24.13.3 to 24.9.1 seemed to fix it for me too. I think because of https://github.com/electron-userland/electron-builder/commit/65817e0edc43a2e6707fab835b0bbe680bd0b1e4 (included in 24.9.2).

In fact, in my case the underlying issue was that due to other changes (updating MacOS version in CI, but not updating an `if` that set env vars for Mac only and depended on that) I was accidentally no longer setting `APPLE_API_KEY` in my build, and this error was an authentication failure (which presumably only appears here as 24.9.2 changes support for API keys somehow).

If you run into this and you're using API key auth, it's worth double-checking that your authentication is all set up correctly :smile:. On 24.13.3 at least, this `Unexpected token 'E', "Error: The"... is not valid JSON` is exactly what you'll see if it's not (it would be great if that full error was provided!)

**Comment by hopkins385** [comment]
even though it doesn't seem to be the issue of the creator of this thread (see comments above). **accepting the new terms from apple developer has solved the issue for me.** you just need to login into your apple developer account and accept the updated license.

**Comment by kangfenmao** [comment]
Fixed: update your package.json add resolutions version

```json
"resolutions": {
  "@electron/notarize": "2.3.2"
}
```

**Comment by mmaietta** [comment]
Quick note: Latest 2.3.2 @electron/notarize is in `next` version of electron-builder. `next` will be promoted to `latest` soon, just been waiting for broader adoption and also to return from vacation so I can quickly field any issues that are reported
