### ISSUE TITLE
MAS build error: Trying to open a `.exe` file

### ISSUE THREAD

**Issue by ashwin-mittal** [electron-userland/electron-builder#8260]
* **Electron-Builder Version**:  24.4.0

* **Node Version**:  18.19.0

* **Electron Version**: 30.1.0

* **Electron Type (current, beta, nightly)**: current

* **Target**: mas-dev

I'm attempting to create a package for the Mac App Store using electron-builder. Below is the configuration for the 'mac' platform.
```json
{
  "target": "mas-dev",
  "type": "development",
  "provisioningProfile": "entitlements/AppleDevelopment.provisionprofile",
  "entitlements": "entitlements/entitlements.mas.plist",
  "entitlementsInherit": "entitlements/entitlements.mas.inherit.plist",
  "category": "public.app-category.productivity",
  "icon": "src/assets/logo_1024.png",
  "gatekeeperAssess": true,
  "hardenedRuntime": false,
}
```

The error below is displayed when I run the 'electron-builder' command from the terminal to package the application.
```text
Running electron builder
  • electron-builder  version=24.4.0 os=23.5.0
  • loaded configuration  file=.../electron-builder-config.cjs
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  arch=arm64 version=30.1.0 appDir=...
  • packaging       platform=mas arch=arm64 electron=30.1.0 appOutDir=dist/mas-dev-arm64
  ⨯ ENOENT: no such file or directory, open '.../dist/mas-dev-arm64/<app_name>.exe'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, open '.../mas-dev-arm64/<app_name>.exe'
```

Please help us understand why it attempted to open a `<app_name>.exe` file when we were building for MAS target on an Apple Silicon Mac with macOS version 14.5. We also tried building on a Mac running Ventura 13.6.7.

**Comment by mmaietta** [comment]
This is very interesting! Would you mind putting together a minimum reproducible repo/gist for me and I can take a deeper look

**Comment by mmaietta** [comment]
Please try v25.0.1 electron-builder and run your command with `DEBUG=electron-builder` env var set.
