### ISSUE TITLE
Allow "compression" parameter for nsis/portable on win32

### ISSUE THREAD

**Issue by mydevpeeps** [electron-userland/electron-builder#8261]
### Environment

* **Electron-Builder Version**: 24.13.3

* **Node Version**: 20.14.0

* **Electron Version**: 31.0.1
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater**: 6.2.1

* **Target**: NSIS

### Details
Currently it is only possible to set compression to store on a "win" target. When building NSIS targets it is not possible to set this in the config as the builder errors out with it being an invalid option.

_I think this option will help with development cycles and especially while developers are getting used to all the settings to test._

### Testing
I tested hardcoding -mx=0 and -mmt=on inside app-builder-lib's out/targets/archive.js and saw the time it was taking to build my test NSIS build decrease by more than 50%, sometimes 70%.  Further the size difference for my basic build was 119MB vs. 123MB so there wasn't much to gain there in my case.  I could not get this to do the same with portable.

**Comment by mmaietta** [comment]
>I think this option will help with development cycles and especially while developers are getting used to all the settings to test.

Why not use the global `compression: store` for faster build times?
```
  // "store” | “normal” | "maximum". - For testing builds, use 'store' to reduce build time significantly.
  compression: "normal",
```
https://www.electron.build/api/programmatic-usage

I do see a valid usage for allowing custom args for `archive.js` so you don't have to hardcode, however, I'm not sure if that will be easily understandable by end-user developers as opposed to using an enum like `store | normal | maximum`

**Comment by mmaietta** [comment]
Found another route. Try setting `process.env.ELECTRON_BUILDER_COMPRESSION_LEVEL=0` for your use case. You can set the `-mx` level to whatever value you want.

**Comment by mydevpeeps** [comment]
> Found another route. Try setting `process.env.ELECTRON_BUILDER_COMPRESSION_LEVEL=0` for your use case. You can set the `-mx` level to whatever value you want via that env var.

will try ty
