### ISSUE TITLE
process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by hanxiang-li** [electron-userland/electron-builder#8263]
* **Electron-Builder Version**:   24.13.3

* **Node Version**:  20.14.0

* **Electron Version**:  22.3.27
* **Electron Type (current, beta, nightly)**: NO

* **Target**: 
In the Mac environment, if the number of characters in the project directory name exceeds 32, this error may occur. It is suspected that there is a problem with this method

![image](https://github.com/electron-userland/electron-builder/assets/45918130/e9c287f6-19f4-476d-9dee-becf29a3203f)
![image](https://github.com/electron-userland/electron-builder/assets/45918130/7ffb267f-a1a6-4286-9538-02505f348420)
![image](https://github.com/electron-userland/electron-builder/assets/45918130/3c6ae339-733a-41fe-8621-325a23f17e5e)

**Comment by beyondkmp** [comment]
From your screenshot, it seems you are compiling the Windows version build on a Mac, which is causing the issue. Have you always been compiling the Windows installer package on a Mac?

**Comment by hanxiang-li** [comment]
> From your screenshot, it seems you are compiling the Windows version build on a Mac, which is causing the issue. Have you always been compiling the Windows installer package on a Mac?

Yes, this issue occurs when my project folder name exceeds 32 bytes. Windows system compilation is not a problem, but there is a problem with Mac. If I set the folder name to be less than 32 bytes, there will be no problem

**Comment by beyondkmp** [comment]
<img width="1085" alt="image" src="https://github.com/electron-userland/electron-builder/assets/5462444/3d4ed3cb-9f36-4f66-b060-5b15fa978ec4">
Cannot reproduce in my computer. Can you provide a minimal reproduction example ?

**Comment by hanxiang-li** [comment]
>  Cannot reproduce in my computer. Can you provide a minimal reproduction example ?
<img width="585" alt="image" src="https://github.com/electron-userland/electron-builder/assets/45918130/7d391af6-d9c8-480d-9285-c9402915e4dc">
Excuse me, are you using Mac to package the win? This is a demo, and I am unable to package it properly during testing
1. pnpm install
2. pnpm run build:win
[test-test-test-test-test-test-test-test-test-test.zip](https://github.com/user-attachments/files/15895932/test-test-test-test-test-test-test-test-test-test.zip)

**Comment by hanxiang-li** [comment]
> > Cannot reproduce in my computer. Can you provide a minimal reproduction example ?
version:
node: v20.14.0
pnpm: 9.4.0
mac: sonoma 14.5

**Comment by beyondkmp** [comment]
cannot reproduce from your demo.
<img width="1342" alt="image" src="https://github.com/electron-userland/electron-builder/assets/5462444/0c2ea118-7a3c-4de9-b425-33aca2c26a39">

**Comment by hanxiang-li** [comment]
> cannot reproduce from your demo. 

`work@lhx test-test-test-test-test-test-test-test-test-test % pnpm run build:win            

> test-test-test-test-test-test-test-test-test-test@1.0.0 build:win /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test
> npm run build && electron-builder --win


> test-test-test-test-test-test-test-test-test-test@1.0.0 build
> npm run typecheck && electron-vite build


> test-test-test-test-test-test-test-test-test-test@1.0.0 typecheck
> npm run typecheck:node && npm run typecheck:web


> test-test-test-test-test-test-test-test-test-test@1.0.0 typecheck:node
> tsc --noEmit -p tsconfig.node.json --composite false


> test-test-test-test-test-test-test-test-test-test@1.0.0 typecheck:web
> vue-tsc --noEmit -p tsconfig.web.json --composite false

vite v5.3.1 building SSR bundle for production...
✓ 2 modules transformed.
out/main/index.js  1.48 kB
✓ built in 116ms
vite v5.3.1 building SSR bundle for production...
✓ 1 modules transformed.
out/preload/index.js  0.42 kB
✓ built in 10ms
vite v5.3.1 building for production...
✓ 13 modules transformed.
../../out/renderer/index.html                      0.55 kB
../../out/renderer/assets/electron-DtwWEc_u.svg    5.82 kB
../../out/renderer/assets/index-CsbMxbyG.css       6.74 kB
../../out/renderer/assets/index-BnHjTmbH.js      162.72 kB
✓ built in 505ms
  • electron-builder  version=24.13.3 os=23.5.0
  • loaded configuration  file=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/electron-builder.yml
  • effective config  config=directories:
  output: dist
  buildResources: build
appId: com.electron.app
productName: test-test-test-test-test-test-test-test-test-test
files:
  - filter:
      - '!**/.vscode/*'
      - '!src/*'
      - '!electron.vite.config.{js,ts,mjs,cjs}'
      - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
      - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
      - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
asarUnpack:
  - resources/**
win:
  executableName: test-test-test-test-test-test-test-test-test-test
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates

  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=28.3.3 appOutDir=dist/win-unpacked
  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 unpack-electron --configuration [{"platform":"win32","arch":"x64","version":"28.3.3"}] --output /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/win-unpacked --distMacOsAppName Electron.app
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=73
  • exited          command=app-builder_amd64 code=0 pid=27513
  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 node-dep-tree --dir /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test
  • exited          command=app-builder_amd64 code=0 pid=27518 out=[{"dir":"/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules","deps":[{"name":"@electron-toolkit/preload","version":"3.0.1"},{"name":"@electron-toolkit/utils","version":"3.0.0"}]}]
  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 icon --format ico --root /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build --root /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test --out /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/.icon-ico
  • path resolved   path=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico outputFormat=ico
  • exited          command=app-builder_amd64 code=0 pid=27519 out={"icons":[{"file":"/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico","size":0}],"isFallback":false}
  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 rcedit --args ["/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/win-unpacked/test-test-test-test-test-test-test-test-test-test.exe","--set-version-string","FileDescription","test-test-test-test-test-test-test-test-test-test","--set-version-string","ProductName","test-test-test-test-test-test-test-test-test-test","--set-version-string","LegalCopyright","Copyright © 2024 example.com","--set-file-version","1.0.0","--set-product-version","1.0.0.0","--set-version-string","InternalName","test-test-test-test-test-test-test-test-test-test","--set-version-string","OriginalFilename","","--set-version-string","CompanyName","example.com","--set-icon","/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico"]
  • found existing  path=/Users/work/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.6.0
  • found existing  path=/Users/work/Library/Caches/electron-builder/wine/wine-4.0.1-mac
  • execute command  command=/Users/work/Library/Caches/electron-builder/wine/wine-4.0.1-mac/bin/wine64 /Users/work/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-x64.exe /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/win-unpacked/test-test-test-test-test-test-test-test-test-test.exe --set-version-string FileDescription test-test-test-test-test-test-test-test-test-test --set-version-string ProductName test-test-test-test-test-test-test-test-test-test --set-version-string LegalCopyright 'Copyright © 2024 example.com' --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName test-test-test-test-test-test-test-test-test-test --set-version-string OriginalFilename '' --set-version-string CompanyName example.com --set-icon /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico
                     workingDirectory=
  • command executed  executable=/Users/work/Library/Caches/electron-builder/wine/wine-4.0.1-mac/bin/wine64
                      errorOut=wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
    000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
    Wine cannot find the FreeType font library.  To enable Wine to
    use TrueType fonts please install a version of FreeType greater than
    or equal to 2.0.5.
    http://www.freetype.org
    Wine cannot find the FreeType font library.  To enable Wine to
    use TrueType fonts please install a version of FreeType greater than
    or equal to 2.0.5.
    http://www.freetype.org
    Wine cannot find the FreeType font library.  To enable Wine to
    use TrueType fonts please install a version of FreeType greater than
    or equal to 2.0.5.
    http://www.freetype.org
    
  • exited          command=app-builder_amd64 code=0 pid=27520
wine&sign: 3s 683ms
  • building        target=nsis file=dist/test-test-test-test-test-test-test-test-test-test-1.0.0-setup.exe archs=x64 oneClick=true perMachine=false
  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 download-artifact --name nsis-3.0.4.1 --url https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z --sha512 VKMiizYdmNdJOWpRGz4trl4lD++BvYP2irAXpMilheUP0pc93iKlWAoP843Vlraj8YG19CVn0j+dCo/hURz9+Q==
  • found existing  path=/Users/work/Library/Caches/electron-builder/nsis/nsis-3.0.4.1
  • exited          command=app-builder_amd64 code=0 pid=27539 out=/Users/work/Library/Caches/electron-builder/nsis/nsis-3.0.4.1
  • executing       file=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/7zip-bin@5.2.0/node_modules/7zip-bin/mac/x64/7za args=a -bd -mx=9 -md=1m -mtc=off -ms=off -mtm=off -mta=off /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z . -xr!*.avi -xr!*.mov -xr!*.m4v -xr!*.mp4 -xr!*.m4p -xr!*.qt -xr!*.mkv -xr!*.webm -xr!*.vmdk cwd=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/win-unpacked
nsis package, x64: 16s 561ms
  • executing       file=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/7zip-bin@5.2.0/node_modules/7zip-bin/mac/x64/7za args=l /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z
  • executed        file=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/7zip-bin@5.2.0/node_modules/7zip-bin/mac/x64/7za stdout=
7-Zip (a) [64] 17.03 : Copyright (c) 1999-2020 Igor Pavlov : 2017-08-28
p7zip Version 17.03 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)
                      Scanning the drive for archives:
1 file, 81263244 bytes (78 MiB)
                      Listing archive: /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z
                      --
Path = /Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z
Type = 7z
Physical Size = 81263244
Headers Size = 1364
Method = LZMA2:20 BCJ
Solid = -
Blocks = 75
                         Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
                    D....            0            0  locales
                    D....            0            0  resources
                    D....            0            0  resources/app.asar.unpacked
                    D....            0            0  resources/app.asar.unpacked/resources
                    ....A         1096          689  LICENSE.electron.txt
                    ....A      9142459       260940  LICENSES.chromium.html
                    ....A       167733       156829  chrome_100_percent.pak
                    ....A       227823       212875  chrome_200_percent.pak
                    ....A     10717392      3452022  icudtl.dat
                    ....A       475987       116526  locales/af.pak
                    ....A       774206       131841  locales/am.pak
                    ....A       848943       136104  locales/ar.pak
                    ....A       881843       131476  locales/bg.pak
                    ....A      1138948       137349  locales/bn.pak
                    ....A       536688       119891  locales/ca.pak
                    ....A       552003       128990  locales/cs.pak
                    ....A       499433       117216  locales/da.pak
                    ....A       534385       123779  locales/de.pak
                    ....A       966750       138708  locales/el.pak
                    ....A       434881       108588  locales/en-GB.pak
                    ....A       438820       108822  locales/en-US.pak
                    ....A       528171       119529  locales/es-419.pak
                    ....A       528159       119158  locales/es.pak
                    ....A       479354       119738  locales/et.pak
                    ....A       786229       128100  locales/fa.pak
                    ....A       489527       119699  locales/fi.pak
                    ....A       554334       119746  locales/fil.pak
                    ....A       572576       124170  locales/fr.pak
                    ....A      1117670       136021  locales/gu.pak
                    ....A       688870       125515  locales/he.pak
                    ....A      1176726       140770  locales/hi.pak
                    ....A       533826       124865  locales/hr.pak
                    ....A       574850       130896  locales/hu.pak
                    ....A       473577       108848  locales/id.pak
                    ....A       521539       118015  locales/it.pak
                    ....A       637276       114597  locales/ja.pak
                    ....A      1280837       138074  locales/kn.pak
                    ....A       538740       111144  locales/ko.pak
                    ....A       578461       127357  locales/lt.pak
                    ....A       577630       128399  locales/lv.pak
                    ....A      1332459       141489  locales/ml.pak
                    ....A      1094665       133209  locales/mr.pak
                    ....A       496447       110621  locales/ms.pak
                    ....A       482576       114718  locales/nb.pak
                    ....A       496419       117597  locales/nl.pak
                    ....A       556829       129857  locales/pl.pak
                    ....A       523253       119584  locales/pt-BR.pak
                    ....A       524567       118090  locales/pt-PT.pak
                    ....A       543759       121507  locales/ro.pak
                    ....A       893079       137622  locales/ru.pak
                    ....A       561212       131897  locales/sk.pak
                    ....A       539150       124749  locales/sl.pak
                    ....A       830811       131631  locales/sr.pak
                    ....A       484580       114766  locales/sv.pak
                    ....A       510585       117668  locales/sw.pak
                    ....A      1320024       137281  locales/ta.pak
                    ....A      1220352       137700  locales/te.pak
                    ....A      1027321       121071  locales/th.pak
                    ....A       521272       119158  locales/tr.pak
                    ....A       891667       136135  locales/uk.pak
                    ....A       780171       128145  locales/ur.pak
                    ....A       616935       118614  locales/vi.pak
                    ....A       445903       110449  locales/zh-CN.pak
                    ....A       441078       109001  locales/zh-TW.pak
                    ....A      5331889      5248989  resources.pak
                    ....A          135           91  resources/app-update.yml
                    ....A       223422        44651  resources/app.asar
                    ....A        35949        34856  resources/app.asar.unpacked/resources/icon.png
                    ....A       276794        46132  snapshot_blob.bin
                    ....A       642377       112358  v8_context_snapshot.bin
                    ....A          106           96  vk_swiftshader_icd.json
                    ....A      4916712      1617784  d3dcompiler_47.dll
                    ....A      2877440       962409  ffmpeg.dll
                    ....A       478208       169113  libEGL.dll
                    ....A      7808512      2220593  libGLESv2.dll
                    ....A       107520        49682  resources/elevate.exe
                    ....A    176900096     58260335  test-test-test-test-test-test-test-test-test-test.exe
                    ....A      5238784      1305287  vk_swiftshader.dll
                    ....A       947200       269659  vulkan-1.dll
------------------- ----- ------------ ------------  ------------------------
                             263898000     81261880  75 files, 4 folders

  • spawning        command=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/mac/app-builder_amd64 download-artifact --name nsis-resources-3.4.1 --url https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z --sha512 Dqd6g+2buwwvoG1Vyf6BHR1b+25QMmPcwZx40atOT57gH27rkjOei1L0JTldxZu4NFoEmW4kJgZ3DlSWVON3+Q==
  • found existing  path=/Users/work/Library/Caches/electron-builder/nsis/nsis-resources-3.4.1
  • exited          command=app-builder_amd64 code=0 pid=27550 out=/Users/work/Library/Caches/electron-builder/nsis/nsis-resources-3.4.1
  • spawning        command=/Users/work/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis -WX -INPUTCHARSET UTF8 -DAPP_ID=com.electron.app -DAPP_GUID=f8941786-352c-5c22-bea5-7886c3ac4a8f -DUNINSTALL_APP_KEY=f8941786-352c-5c22-bea5-7886c3ac4a8f -DPRODUCT_NAME=test-test-test-test-test-test-test-test-test-test -DPRODUCT_FILENAME=test-test-test-test-test-test-test-test-test-test -DAPP_FILENAME=test-test-test-test-test-test-test-test-test-test -DAPP_DESCRIPTION=An Electron application with Vue and TypeScript -DVERSION=1.0.0 -DPROJECT_DIR=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test -DBUILD_RESOURCES_DIR=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build -DAPP_PACKAGE_NAME=test-test-test-test-test-test-test-test-test-test -DMUI_ICON=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico -DMUI_UNICON=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico -DAPP_64=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z -DAPP_64_NAME=test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z -DAPP_64_HASH=3120436564498547B5AE6E35C149027CD30EF98785C214B78D9A05B128CAFCA84234C29F97E0ABE3FAB468367E2B75DCE7BBE33CE466DD178DDE959B48EEFA5F -DAPP_64_UNPACKED_SIZE=257713 -DCOMPANY_NAME=example.com -DAPP_INSTALLER_STORE_FILE=test-test-test-test-test-test-test-test-test-test-updater\installer.exe -DCOMPRESSION_METHOD=7z -DONE_CLICK -DRUN_AFTER_FINISH -DSHORTCUT_NAME=test-test-test-test-test-test-test-test-test-test -DUNINSTALL_DISPLAY_NAME=test-test-test-test-test-test-test-test-test-test -DRECREATE_DESKTOP_SHORTCUT -DESTIMATED_SIZE=257713 -DCOMPRESS=auto -DBUILD_UNINSTALLER -DUNINSTALLER_OUT_FILE=Z:\Users\work\Downloads\test-test-test-test-test-test-test-test-test-test\dist\__uninstaller-nsis-test-test-test-test-test-test-test-test-test-test.exe -XOutFile "/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-setup.exe" -XVIProductVersion 1.0.0.0 -XVIAddVersionKey /LANG=1033 ProductName "test-test-test-test-test-test-test-test-test-test" -XVIAddVersionKey /LANG=1033 ProductVersion "1.0.0" -XVIAddVersionKey /LANG=1033 LegalCopyright "Copyright © 2024 example.com" -XVIAddVersionKey /LANG=1033 FileDescription "An Electron application with Vue and TypeScript" -XVIAddVersionKey /LANG=1033 FileVersion "1.0.0" -XVIAddVersionKey /LANG=1033 CompanyName "example.com" -XUnicode true -XSetCompressor zlib - cwd=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/app-builder-lib@24.13.3_dmg-builder@24.13.3_electron-builder-squirrel-windows@24.13.3__electr_jhkj5etvr5lkpiqd5wtx2uh6ge/node_modules/app-builder-lib/templates/nsis
Command line defined: "APP_ID=com.electron.app"
Command line defined: "APP_GUID=f8941786-352c-5c22-bea5-7886c3ac4a8f"
Command line defined: "UNINSTALL_APP_KEY=f8941786-352c-5c22-bea5-7886c3ac4a8f"
Command line defined: "PRODUCT_NAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "PRODUCT_FILENAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "APP_FILENAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "APP_DESCRIPTION=An Electron application with Vue and TypeScript"
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test"
Command line defined: "BUILD_RESOURCES_DIR=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build"
Command line defined: "APP_PACKAGE_NAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "MUI_ICON=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico"
Command line defined: "MUI_UNICON=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/build/icon.ico"
Command line defined: "APP_64=/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/dist/test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=test-test-test-test-test-test-test-test-test-test-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=3120436564498547B5AE6E35C149027CD30EF98785C214B78D9A05B128CAFCA84234C29F97E0ABE3FAB468367E2B75DCE7BBE33CE466DD178DDE959B48EEFA5F"
Command line defined: "APP_64_UNPACKED_SIZE=257713"
Command line defined: "COMPANY_NAME=example.com"
Command line defined: "APP_INSTALLER_STORE_FILE=test-test-test-test-test-test-test-test-test-test-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "UNINSTALL_DISPLAY_NAME=test-test-test-test-test-test-test-test-test-test"
Command line defined: "RECREATE_DESKTOP_SHORTCUT"
Command line defined: "ESTIMATED_SIZE=257713"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=Z:\Users\work\Downloads\test-test-test-test-test-test-test-test-test-test\dist\__uninstaller-nsis-test-test-test-test-test-test-test-test-test-test.exe"
Processing script file: "<stdin>" (UTF8)
  • exited          command=makensis code=null pid=27551
  ⨯ /Users/work/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
null  failedTask=build stackTrace=Error: /Users/work/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
null
    at ChildProcess.<anonymous> (/Users/work/Downloads/test-test-test-test-test-test-test-test-test-test/node_modules/.pnpm/builder-util@24.13.1/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ELIFECYCLE  Command failed with exit code 1.`

This is all the logs

**Comment by hanxiang-li** [comment]
> cannot reproduce from your demo. 

If "test-test-test-test-test-test-test-test-test-test“ is changed to ”test-test-test-test“, I can succeed
![image](https://github.com/electron-userland/electron-builder/assets/45918130/fc08554a-7973-4d76-acbd-dd55e28324c0)

**Comment by beyondkmp** [comment]
I can reproduce your issue. Currently, the problem occurs when the cwd directory exceeds 255 characters, which seems to be related to the Windows directory length limit. Therefore, it is best not to exceed 255 characters in the Windows directory path.
<img width="1791" alt="image" src="https://github.com/electron-userland/electron-builder/assets/5462444/1140ee55-8147-46c3-9f70-ef2126b4b513">

**Comment by hanxiang-li** [comment]
yes，Thank you for your support
