### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by HAnshu47** [electron-userland/electron-builder#8268]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 18.4.0

* **Electron Version**:21.4.4
* 
* **framework**:Vue 3.4.15

description：
在使用electron-builder 打包，win7系统会报错版本过高，尝试降低electron等级至23一下（23开始不在兼容win7，win8），依然报错undefined is not a function，window系统和mac-intel系统都会报此问题

Error reporting of unknown problem img
<img width="564" alt="image" src="https://github.com/electron-userland/electron-builder/assets/53853575/aa29546a-a356-4df4-82bb-bdb8bf39310f">

Version incompatibility issues img
<img width="260" alt="image" src="https://github.com/electron-userland/electron-builder/assets/53853575/76e44149-7724-4288-bdb1-d4b77b407786">

**Comment by mmaietta** [comment]
That logic is coming from `bytecode-loader` and is an electron-specific error due to the difference between local development and a packaged electron app, not intrinsically caused by electron-builder
