### ISSUE TITLE
AppImages fail to run if appimaged process is running

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#827]
- **Version**: 7.11.4

- **Target**: Linux AppImage

If a process called `appimaged` is running, then desktop integration must not be shown. However this functionality seems to be broken and results in the AppImage not launch its app but saying `line 43: exec: : not found` instead.
The original desktopintegration script does not show this behavior.

```
+ pidof appimaged
2677
+ exit 0
+ atexit
+ '[' 0 -eq 0 ']'
+ exec ''
/home/me/Downloads/donut-1.2.0-x86_64/AppRun: line 43: exec: : not found
```

(In case you are wondering: `appimaged` is an optional daemon that watches the system for AppImages and integrates them with the system, [video](https://www.youtube.com/watch?v=FqVAtHdK1N0))

**Comment by develar** [comment]
In electron-builder script there is 
```sh
# Exit immediately if appimaged is running
pidof appimaged 2>/dev/null && exit 0
```

in the same place where original line placed. Probably this check should be move to the top of the script.

**Comment by probonopd** [comment]
I suspect that the line you posted is correct: If `appimaged` is running, then the desktopintegration script should cease execution and the `atexit` trap should take over and launch the app. It seems like `atexit` doesn't have the information it needs to launch the app. (Le me know if you think this makes no sense and I should investigate deeper.)

**Comment by probonopd** [comment]
ping @develar
