### ISSUE TITLE
Compiled Binary goes blank screen for all OS versions

### ISSUE THREAD

**Issue by crypto-matto** [electron-userland/electron-builder#8272]
* **Electron-Builder Version**: 
24.13.2 / 24.13.3

* **Node Version**: 
18.20.3

* **Electron Version**:
19.1.9
* **Electron Type (current, beta, nightly)**:
electron-updater 4.3.9

* **Target**: 
MacOS, Windows, Linux

I was originally using `electron-builder` `23.2.0`. The app works fine. After I upgrade `electron-builder` to `24.13.2 / 24.13.3`, while the binaries can be built without errors, it goes blank screen after opening it. 

Weirdly I cannot debug at all, as in watch mode, the app can be opened & operates perfectly fine. 

When opening the built binary / executable, I can see that it can load my index.html, as the app title is correct. Yet I can't open any developer console, no matter with `Ctrl + shift + I` or adding `win.webContents.openDevTools()` inside the code. 

What else can I debug it, and any potential cause of this? Thanks.

**Comment by mmaietta** [comment]
Please provide a minimum reproducible repo for this issue. This is the first I've heard of its kind
