### ISSUE TITLE
How to set linux app icon in linux software installer

### ISSUE THREAD

**Issue by Thesiva7** [electron-userland/electron-builder#8278]
![Screenshot from 2024-06-13 13-47-03](https://github.com/electron-userland/electron-builder/assets/95845976/853a6e30-7fd0-4074-9dfc-b38f67907f89)

How to set linux app icon in linux software installer.

My build configuration for linux is below.

"linux": {
      "desktop": {
        "StartupNotify": "false",
        "Encoding": "UTF-8",
        "icon": "assets/icons/my-app-256x256.icns"
      },
      "target": [
        "deb"
      ],
      "icon": "assets/icons/my-app-256x256.icns",
      "category": "AudioVideo",
      "synopsis": "Multi Video Conference Solution",
      "description": "This application is for multi video conference room solutions"
    },

any know how to provide app in linux software installer. help me.
Thanks.

**Comment by Thesiva7** [comment]
Any help please....

**Comment by mmaietta** [comment]
What's the required image dimensions of that icon preview? Does the `icns` file include one of that size?

**Comment by tianyichuxin** [comment]
I also encountered it, have you solved it yet

**Comment by Thesiva7** [comment]
> What's the required image dimensions of that icon preview? Does the `icns` file include one of that size?

i have tried with 16x16.png,32x32.png,64x64.png,128x128.png, 256x256.png, 512x512.png, 1024x1024.png image. i kept these in assests/icon folder. and given below configuration. but still it is not showing.
"linux": {
"desktop": {
"StartupNotify": "false",
"Encoding": "UTF-8",
"icon": "assets/icons"
},
"target": [
"deb"
],
"icon": "assets/icons",
"category": "AudioVideo",
"synopsis": "Multi Video Conference Solution",
"description": "This application is for multi video conference room solutions"
},

**Comment by Thesiva7** [comment]
> I also encountered it, have you solved it yet

no, not yet. have you?
