### ISSUE TITLE
There are no issues with local debugging and detection updates. After successful packaging, when installing the Electron application, it prompts Cannot find module 'Electron Updater'

### ISSUE THREAD

**Issue by 18715672252** [electron-userland/electron-builder#8289]
![1719820965784_2A8DC75E-9817-4672-AE78-9D63D28670F8](https://github.com/electron-userland/electron-builder/assets/51355379/1614036d-ddce-4a2b-9df8-d0a9d71c62ac)

"devDependencies": {
    "electron": "^30.0.4",
    "electron-builder": "^24.13.3"
  }

"dependencies": {
    "@electron-toolkit/utils": "^3.0.0",
    "axios": "^1.6.8",
    "electron-is-dev": "^3.0.1",
    "form-data": "^4.0.0",
    "electron-updater": "^6.2.1"
  }

**Comment by mmaietta** [comment]
How are you importing electron-updater? Did you use the sample code from here by chance? https://www.electron.build/auto-update#quick-setup-guide
