### ISSUE TITLE
How to show EULA before install app with squirrel?

### ISSUE THREAD

**Issue by artpol** [electron-userland/electron-builder#829]
* **7.13.1**: 

* **Squirrel Windows**: 

Installer squirrel shows only the GIF file while installation process, and then starts the application. Is it possible to show the user license agreement before installing?

**Comment by develar** [comment]
It will be fixed for NSIS target only (#781) this week. Squirrel.Windows is deprecated, do not use it (#529 is ready to close).

**Comment by develar** [comment]
Duplicates #781
