### ISSUE TITLE
Drag and drop files doesn't work after package application

### ISSUE THREAD

**Issue by Vromga** [electron-userland/electron-builder#8292]
- Electron-Builder Version: ^24.13.3
- Node Version: v20.15.0
- Electron Version: ^31.1.0
- Electron Type (current, beta, nightly): current
- Target: nsis

Hi.
Drag and drop files works during development (electronic), but does not work after packaging. Dragging a file from the explorer into the application causes a cancel sign to appear under the cursor. I tried setting the asar: false; flag. But it didn't help me either.
The drop, dragenter and dragleave events do not emit any value at all. Has anyone encountered this problem and can give advice on how to get around it?
p.s. I can't use electron-forge.

**Comment by mmaietta** [comment]
I found this through a quick google search.
>This is not a problem with Electron, this is a Windows OS concept (Mandatory Integrity Control).
If you run Electron from an administrator mode console, or any "Run as Administrator" process, then you try to drag&drop from a Windows Explorer instance (which can't run in administrator mode), then Drag & Drop, and many other capabilities, will not work.
If I run my Electron app from a normal console with no administrator UAC elevation, I can drag and drop normally.

During development, I'm guessing you're not running as Admin, but does your app require elevated admin mode in production?

**Comment by mmaietta** [comment]
I found this through a quick google search.
>This is not a problem with Electron, this is a Windows OS concept (Mandatory Integrity Control).
If you run Electron from an administrator mode console, or any "Run as Administrator" process, then you try to drag&drop from a Windows Explorer instance (which can't run in administrator mode), then Drag & Drop, and many other capabilities, will not work.
If I run my Electron app from a normal console with no administrator UAC elevation, I can drag and drop normally.

During development, I'm guessing you're not running as Admin, but does your app require elevated admin mode in production?

**Comment by Vromga** [comment]
Hello @mmaietta!  No, I do not need administrator rights. But I tried to launch with the rights of the administrator, and I get the same effect.
