### ISSUE TITLE
Command ran by the RPM updater not working

### ISSUE THREAD

**Issue by rastiqdev** [electron-userland/electron-builder#8305]
* **Electron-Builder Version**: 
24.13.3 (electron-updater 6.2.1)

* **Node Version**: 
20.15.0

* **Electron Version**:
31.1.0
* **Electron Type (current, beta, nightly)**:
current

* **Target**: 
RPM

When an app from an RPM file updates, the command that electron-updater runs tries to uninstall the app by its name, then installs the new version's RPM file. However, (with the dnf package manager for example) it is not possible to do this, as we need the app's package name to uninstall it. On Electron apps it seems to be the `name` value in our package.json, but electron-updater tries to do this with the `productName` value from our electron-builder config. 

So, the app just restarts on the same version and causes a bootloop if updates are on start, automatic and forced.

(I also do not understand the need to uninstall the app before installing the new version, as dnf, yum, and zypper all support updating apps from RPM files.)

**Comment by rastiqdev** [comment]
(sorry, the `productName` seems to be from the package.json, but that doesn't change the fact that `app.getName()` shouldn't be used to get the package name of an app)

**Comment by mmaietta** [comment]
> (I also do not understand the need to uninstall the app before installing the new version, as dnf, yum, and zypper all support updating apps from RPM files.)
That's very interesting! Would you be willing to open up a PR with that change?

**Comment by rastiqdev** [comment]
PR: #8311
