### ISSUE TITLE
It is ARM supported?

### ISSUE THREAD

**Issue by yayolius** [electron-userland/electron-builder#831]
From what i checked on previous comments and the code it seems that is enabled but i don't see any official documentation.
Thanks

**Comment by develar** [comment]
Please see `./node_modules/.bin/build --help`

Use `--armv7l` to build for ARM.

**Comment by develar** [comment]
Please see #778

**Comment by yayolius** [comment]
I am triting to use:
./node_modules/.bin/build --platform=linux --arch=armv7l -d
and i get:
Skip app dependencies rebuild because platform is different
Error: Unsupported arch armv7l; must be one of: ia32, x64
    at Function.pack (/Users/Claudio/Code/app/node_modules/electron-packager-tf/index.js:169:52)
    at LinuxPackager.<anonymous> (/Users/Claudio/Code/app/node_modules/electron-builder/src/platformPackager.ts:180:15)

I run
./node_modules/.bin/build --platform=linux --armv7l

and i get

/Users/Claudio/Code/app/node_modules/command-line-args/lib/argv.js:81
  const err = new Error(message)
              ^
UNKNOWN_OPTION: Unknown option: --armv7l


Best regards
Claudio

**Comment by yayolius** [comment]
Sorry guys, i just checked and i was using a very old version of electron builder

**Comment by TsPuujee** [comment]
use electron-packager

**Comment by saifeiLee** [comment]
> Please see `./node_modules/.bin/build --help`
> 
> Use `--armv7l` to build for ARM.

Do I have to run build-task on ARM machine if I want a package for ARM-linux?
