### ISSUE TITLE
AutoUpdater doesn't detect latest-mac.yml from github

### ISSUE THREAD

**Issue by Travis-Sherman** [electron-userland/electron-builder#8312]
* **Electron-Builder Version: 24.13.3**: 

* **Node Version: 20.5.0**: 

* **Electron Version: 31.1.0**
* **Electron Type: current**
* **Electron-Updater: 6.1.8**

* **Target: Mac**

For some reason when I upload my packaged files (.dmg and .zip files) with my latest-mac.yml to my github release and try to update my app using 
```autoUpdater.setFeedURL({
  provider: 'generic',
  url: `${serverUrl}/update/${process.platform}_${process.arch}/${version}`
})
```

I still get an error saying Error: Cannot find channel "latest-mac.yml" update info: HttpError: 404 
"method: GET url: https:/${serverUrl}/update/darwin_arm64/1.8.7/latest-mac.yml?noCache=1i2d3gjca"

I'm using a public repo and hazel to host version control (with my .dmg,.zip, and latest-mac.yml file) but where does this latest-mac.yml come from and why do I need it?

**Comment by Travis-Sherman** [comment]
oh guys, i guess i was looking at different docs:

I took out the setfeed function and it works but now
i get this error
```
Error: ENOENT: no such file or directory, rename '/Users/{mac-username}/Library/Caches/{project}-updater/pending/temp-{project}-2.0.0-arm64-mac.zip' -> '/Users/{mac-username}/Library/Caches/{project}-updater/pending/{project}-2.0.0-arm64-mac.zip'
```

can anyone help?

**Comment by mmaietta** [comment]
Can you try adding additional logging for electron-updater? Can follow this example for doing so
https://www.electron.build/auto-update#examples

**Comment by Travis-Sherman** [comment]
I can close this issue. I had a setTime interval that's why I was getting that error because it was timing out.
