### ISSUE TITLE
[Linux AppImage] support type 2 image format

### ISSUE THREAD

**Issue by probonopd** [electron-userland/electron-builder#832]
Just a heads-up that we are working on the [type 2 image format](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format) for AppImage. It will have a number of advantages:
- Uses more mordern, more flexible squashfs rather than outdated zisofs
- Optionally, can use different compressors
- Optionally, can embed digital signatures in an ELF section inside the AppImage
- Does not require fixed offsets
- Stores optional update information in an ELF section
- Is more future-proof

Since `electron-builder` is an important stakeholder in the AppImage ecosystem, some aspects of the type 2 image format were specifically designed with tools like electron-builder in mind that might want to use their own tools (e.g., `mksquashfs`, similar to `xorriso`) rather than the ones provided by AppImageKit, in fact this has been made **super simple**:

```
mksquashfs Your.AppDir Your.squashfs -root-owned -noappend
cat runtime >> Your.AppImage
cat Your.squashfs >> Your.AppImage
chmod a+x Your.AppImage
```

Note that there are no fixed offsets to observe, unlike with type 1 AppImages.

If you want to play with it, here are the tools (will move into AppImageKit when ready):
https://github.com/probonopd/appimagetool

Would electron-builder consider to switch to the type 2 image format? If no, what would need to be changed?

**Comment by develar** [comment]
The only important reason why electron-builder doesn't use original tool to build AppImage — [mappings](https://github.com/probonopd/AppImageKit/issues/230#issuecomment-246581739)

mksquashfs also supports several source directories. If you don't want to complicate `appimagetool` — I realized, that there is a simple solution — copy using hard links (`cp -al`). So, I will try to use `appimagetool` soon. 

Will be cool if you can provide `appimagetool` builds for x64/x32/arm, or at least, docker images to build :) (as far I see, runtime.c is a part of tool).

**Comment by develar** [comment]
> super simple

I see that now signing is supported, so, it will be better to use original tool to build AppImage.

**Comment by probonopd** [comment]
> mksquashfs also supports several source directories.

Will look into this. If it's easy to support and if it helps you, why not.

> Will be cool if you can provide appimagetool builds for x64/x32/arm

Yes, I am looking into building on x64/x32 CentOS 6 at the moment.

**Comment by GitZamfir** [comment]
Hello.
I was wondering what the status of this is, it appears electron builder still only supports Type 1, which prevents issues when trying to extract and run inside docker containers, where the https://github.com/AppImage/AppImageKit/wiki/FUSE documentation seems to show that Type 2 Release 9 its a lot easier?

**Comment by develar** [comment]
Status — overloaded :( Will be done in several weeks as part of Linux auto update.

**Comment by probonopd** [comment]
:+1:
