### ISSUE TITLE
When use transparent on Linux, it can only start with the parameters of --enable-transparent-visuals --disable-gpu. How can I run it directly ?

### ISSUE THREAD

**Issue by ThomasSoloist** [electron-userland/electron-builder#833]
When use transparent on Linux, it can only start with the parameters of --enable-transparent-visuals --disable-gpu. How can I run it directly ?

**Comment by lbssousa** [comment]
I can pass these options silently to Electron's renderer proccess on Linux just by putting the following code in `main.js` (or whatever your main script name is):

```
if (process.platform === 'linux') {
    app.commandLine.appendSwitch('enable-transparent-visuals');
    app.commandLine.appendSwitch('disable-gpu');
}
```

**Comment by belvederef** [comment]
This solution does not seem to work anymore.
