### ISSUE TITLE
dmg.title option removal

### ISSUE THREAD

**Issue by thomasjbradley** [electron-userland/electron-builder#834]
- **Version**: 7.14.1

- **Target**: Mac, DMG

I just upgraded to the newer version of `electron-builder` and now the `dmg.title` option is removed. Displaying this error message:

```
Warning: dmg.title is not supported, file issue if need
```

Well, I'm doing exactly what it’s asking.

_Use case_: Right now when I build the app the DMG gets named with the version, like this, “Markbot 4.2.2”—I don't want the version number in the mounted drive image name, I want it to say exactly “Install Markbot” which previous versions did, thanks to the `dmg.title` option.

**Comment by thomasjbradley** [comment]
I suppose I should also mention that I'd really like this feature back because I won't be using auto-updating. My users will always be seeing the mounted DMG.

The tool is specialized and tied specifically to encrypted & authenticated private things that I don't really want to have an auto-updater on—I'd like to control the version distribution.

**Comment by develar** [comment]
Feature will be restored soon, in several days. Sorry for inconvenience.

**Comment by thomasjbradley** [comment]
Thanks so much!
