### ISSUE TITLE
Suggestion - tutorial

### ISSUE THREAD

**Issue by paulbjensen** [electron-userland/electron-builder#835]
**Version:** 7.14.1
**Target**: Mac & Windows 

Hi,

I managed to figure out how to use the builder, but it wasn't clear that I needed to put the application's files in a folder called app. A tutorial would be great, so I will contribute a tutorial for this. I'm just marking this issue down as a note. 

PS - You might like to know that electron-builder is mentioned in a book I'm writing for Manning publications titled [Cross Platform Desktop Applications](https://manning.com/books/cross-platform-desktop-applications).

**Comment by develar** [comment]
Will be cool if you will manage to write tutorial :)

**Comment by develar** [comment]
Duplicates #357
