### ISSUE TITLE
Mac: "your.app.category.type" ??

### ISSUE THREAD

**Issue by philcockfield** [electron-userland/electron-builder#836]
# Question

* **Version**:  1.4.3

* **Target**:  Mac

The sample has:

```
"build": {
  "appId": "your.id",
  "mac": {
    "category": "your.app.category.type",
  },
```

Is there any guidance on what the `your.app.category.type` value should be?  I can't find anything, other than https://developer.apple.com/app-store/categories/

Thanks?

**Comment by develar** [comment]
Please see https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW8

**Comment by philcockfield** [comment]
Sweet , thanks.

**Comment by alvesl** [comment]
Hello!
What if we want a secondary category id?
Mac App Store support both primary and secondary.

Thanks!
