### ISSUE TITLE
Icons missing for uninstall and install warning

### ISSUE THREAD

**Issue by TimvdEijnden** [electron-userland/electron-builder#838]
* **Version**: 7.12.2

* **Target**: Squirrel

The installer, shortcut and application while running all have the correct icon.

When I'm going to add/remove programs the icon is missing.
![uninstall icon missing](https://cloud.githubusercontent.com/assets/951290/19557349/94d90016-96c5-11e6-8da2-120e899f52f6.PNG)

When installing you get a dialog and that dialog is also missing the icon.
![install icon missing](https://cloud.githubusercontent.com/assets/951290/19557366/a8f919f0-96c5-11e6-9dad-715dd49a6151.PNG)

We use a gulp script to create the installer:
```js
builder.build({
    targets:  Platform.WINDOWS.createTarget('Squirrel', Arch.ia32);,
    publish: true,
    githubToken: 'xxx',
    devMetadata: {
        build: {
            win: {
    			loadingGif: 'resources/windows/installer_animated_' + lang + '.gif',
    			msi: false,
    			icon: 'resources/windows/icon.ico'
    		}
        },
        directories: {
            output: 'dist/' + lang
        }
    }
})
```

Package.json
```js
{
	"repository": "https://github.com/xxx/xxx",
	"licence": "UNLICENSED",
	"private": "private",
	"build": {
		"appId": "com.xxx.xxx",
		"category": "public.app-category.productivity",
		"extraResources": "xxx-resources"
	},
	"directories": {
		"buildResources": "resources",
		"app": "build"
	},
	"devDependencies": {
		"asar": "0.12.3",
		"chai": "3.5.0",
		"electron": "1.4.3",
		"electron-builder": "7.12.2",
		"electron-mocha": "3.1.1",
		"fs-jetpack": "0.9.2",
		"gulp": "3.9.1",
		"gulp-batch": "1.0.5",
		"gulp-less": "3.1.0",
		"gulp-plumber": "1.1.0",
		"gulp-replace": "0.5.4",
		"gulp-watch": "4.3.10",
		"request": "2.75.0",
		"run-sequence": "1.2.2",
		"semver": "5.3.0",
		"yargs": "6.0.0"
	},
	"scripts": {
		"build": "gulp build",
		"install-app-modules": "cd app && npm install && cd ..",
		"create-installer": "gulp create-installer",
		"preinstall": "npm run install-app-modules",
		"start": "gulp start",
		"pretest": "gulp build --env=test",
		"test": "electron-mocha build --renderer"
	}
}
```

Another question: how do we change the help link and add update information link? (see first screenshot) We want them to be different.

**Comment by develar** [comment]
Please use NSIS instead of Squirrel.Windowsif possible.

If you cannot use NSIS — well, so, additional `build.squirrelWindows.iconUrl` is required. https://github.com/electron-userland/electron-builder/wiki/Options#SquirrelWindowsOptions-iconUrl

> how do we change the help link and add update information link? (see first screenshot) We want them to be different.

Hmm... Please try to set https://docs.npmjs.com/files/package.json#homepage in your app package.json

**Comment by TimvdEijnden** [comment]
We need the squirrel auto-update and have it working. We've released our app a month a go and a lot of users have installed it. So we cannot change to NSIS because that'll break our working auto-update mechanism. I guess changing the homepage url works, but how do we get two different urls for help link and update information link, some applications even have a 3rd support link. I'd really like to specify all 3 to different urls.

**Comment by develar** [comment]
@TimvdEijnden Filed as separate issue #839 Please note — I cannot promise time frame.

**Comment by TimvdEijnden** [comment]
Thank you very much, I can contribute if you'd like. But we don't have to rush 😃 .

**Comment by dcyoung** [comment]
Did you ever figure out a fix for the missing icon in the add/remove programs screen (see the OP's first image). I'm using an NSIS installer with electron-builder v11.2.1.  and the installer itself has the correct icon (unlike the OP's second image), but the add/remove programs screen isn't showing the icon.

**Comment by TimvdEijnden** [comment]
Yes I fixed it by using iconUrl but we used Squirrel.

On Jan 12, 2017 02:03, "dcyoung" <notifications@github.com> wrote:

Did you ever figure out a fix for the missing icon in the add/remove
programs screen (see the OP's first image). I'm using an NSIS installer
with electron-builder v11.2.1. and the installer itself has the correct
icon (unlike the OP's second image), but the add/remove programs screen
isn't showing the icon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/electron-userland/electron-builder/issues/838#issuecomment-272045494>,
or mute the thread

**Comment by dcyoung** [comment]
Thanks for the response. 
The squirrel is working just fine for me as well, but I'd like to be able to use NSIS installer. This seems to be the only remaining issue. Should I create a separate issue for it, given that it is not relevant to the squirrel target?

**Comment by develar** [comment]
@dcyoung Yes, please create separate issue.

**Comment by Zamiell** [comment]
He created the issue here: https://github.com/electron-userland/electron-builder/issues/1108

I'm linking it so that future readers don't have to go searching for it.
