### ISSUE TITLE
trailing commas in dependency package.json cause havok

### ISSUE THREAD

**Issue by drclementshimizu** [electron-userland/electron-builder#8391]
* **Electron-Builder Version**: 
^24.13.3

* **Node Version**: 
10.7.0

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:
26.0.0

* **Target**: 
windows

Electron builder fails when there is a trailing comma in a package.json.
this is not allowed in json, but many systems are able to overlook it, because javascript allows it.

for example, a NPM dependency of a project's package.json has a trailing comma.  and this produces a difficult to interpret error
https://www.npmjs.com/package/Babel

 electron-builder

  • electron-builder  version=24.13.3 os=10.0.22631
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=MYAPP\package.json
  • writing effective config  file=dist\builder-effective-config.yaml
  ⨯ node_modules.Dependency.ReadString: expects " or n, but found }, error found in #10 byte of ...|.x"
  },
}|..., bigger context ...| "step": "0.0.x",
    "underscore": "1.x.x"
  },
}|...
Error reading package.json: MYAPP\node_modules\Babel\package.json

I was able to fix my error by ensuring the node_modules\Babel\package.json has no trailing commas

However, just a request to make that work without having to police my dependencies...

**Comment by mmaietta** [comment]
That's an issue with an upstream Go-based dependency https://github.com/develar/app-builder

Feel free to open an issue there but there's nothing I can do from the electron-builder side

**Comment by drclementshimizu** [comment]
thank you
