### ISSUE TITLE
Linux deb auto updater doesn't update due wrong install command

### ISSUE THREAD

**Issue by Ryan432** [electron-userland/electron-builder#8395]
* **Electron-Builder Version**: 25.0.3
* **Node Version**: v18.15.0
* **Electron Type (current, beta, nightly)**: stable
* **Electron Version**:  30.2.0
* **Electron Updater Version**:  6.3.2
* **Target**: linux, deb

The auto updater is not updating correctly on Linux, Ubuntu 22.04.

So, in fact what happening is that when the update is finished to download, I open a dialog, after confirm I am executing the function `autoUpdate.quitAndInstall();`, then it's requesting for the password for the privilege, quitting the app and reopening but the update didn't happen. 

After long investigation, I have found that the install command in electron-updater is wrong and the bash cannot execute it.

Relevant logs:
```
Executing: /usr/bin/pkexec --disable-internal-agent with args: /bin/bash,-c,dpkg -i /home/username/.cache/app-updater/pending/app-1.0.30-arm64.deb || apt-get install -f -y
Update installer has already been triggered. Quitting application.
```

Now, if you take the Executing command, you will see that it's not really can be executed as can seen here:
<img width="1544" alt="Screenshot 2024-08-04 at 02 47 13" src="https://github.com/user-attachments/assets/c577a487-65ab-4330-8fc9-9c8576073cf5">

Relevant code: My auto updater implementation.
```js
const showUpdateVersionModal = async ({ version }) => {
	// INFO: MacOS specific, show bouncing app in dock.
	if (process.platform === 'darwin') app.dock.bounce('informational');

	await dialog.showMessageBox(mainWindow, {
		type: 'info',
		title: 'Application Update',
		message: `${version}`,
		detail: 'A new version is available. Restart the application now to apply the updates.',
		buttons: ['Restart']
	});

	autoUpdater.quitAndInstall();
};

const startAutoUpdater = async () => {
	autoUpdater.autoRunAppAfterInstall = true;
	autoUpdater.autoDownload = true;
	autoUpdater.autoInstallOnAppQuit = true;

	setTimeout(() => {
		autoUpdater.checkForUpdatesAndNotify();
	}, 2000);

	const checkUpdatesInterval = setInterval(() => {
		autoUpdater.checkForUpdatesAndNotify();
	}, 10000);

	autoUpdater.on('update-available', async () => {
		clearInterval(checkUpdatesInterval);
	});

	autoUpdater.on('update-downloaded', ({ version, downloadedFile }) => {
		showUpdateVersionModal({ version, downloadedFile });
	});

	autoUpdater.on('error', (_error, message) => {
		autoUpdater.logger.error(message);
	});
};

```

I found the problem in `packages/electron-updater/src/DebUpdater.ts` at `doInstall` function, I fixed it locally, it works, and I am ready to PR, just couldn't find way to open branch & PR.

Here is the function scope after a fix:
```js
  protected doInstall(options: InstallOptions): boolean {
    const sudo = this.wrapSudo()
    const installCommand = `'dpkg -i ${options.installerPath} || apt-get install -f -y'`
    this.spawnSyncLog(sudo, ["/bin/bash", "-c", installCommand])
    if (options.isForceRunAfter) {
      this.app.relaunch()
    }
    return true
  }
```

After that fix, the auto-updater works correctly with no issues.
Would love if will allow me to contribute and push that update asap.

Thank you.

**Comment by Bug-Reaper** [comment]
@Ryan432 you should be able to:
1. Fork this repo
2. Clone your fork
3. Create a new branch > commit your change > push to your forked repo
4. PR from the branch on your fork to the main-repo

Lmk if that works for you

**Comment by Ryan432** [comment]
@Bug-Reaper 
Thanks for explaining, I have just opened PR, you can find it here:

https://github.com/electron-userland/electron-builder/pull/8400

Is there any ETA to when you will be able to release that update? 
Or can you suggest a way where I can already have a "beta" release of my fix so I can use that right now?

Thank you,

**Comment by xyloflake** [comment]
> @Bug-Reaper Thanks for explaining, I have just opened PR, you can find it here: #8400
> 
> Is there any ETA to when you will be able to release that update? Or can you suggest a way where I can already have a "beta" release of my fix so I can use that right now?
> 
> Thank you,

@mmaietta is the maintainer, not @Bug-Reaper. You can take a look at the existing PRs to figure out when it will be merged. If you ask me, it's about 3 to 4 days.

**Comment by Ryan432** [comment]
@xyloflake Thanks.

@mmaietta 
Would love if you can look into it :)

**Comment by xyloflake** [comment]
> @xyloflake Thanks.
> 
> @mmaietta 
> Would love if you can look into it :)

I think he's on a vacation. Btw, autoupdates work fine for the .deb target  in the [app I work on](https://github.com/staniel359/muffon). You can verify through the [betas](https://github.com/muffonlabs/mufbeta). Please note that the betas don't have an UI rn for the the autoupdates. You'll have to open muffon through the terminal to have a look at the log.

None of our users have a problem with the autoupdates.

**Comment by xyloflake** [comment]
> @Bug-Reaper 
> Thanks for explaining, I have just opened PR, you can find it here: https://github.com/electron-userland/electron-builder/pull/8400
> 
> Is there any ETA to when you will be able to release that update? 
> Or can you suggest a way where I can already have a "beta" release of my fix so I can use that right now?
> 
> Thank you,
> 
> 

If you want this to immediately work for your app, create a patch. I'd recommend using pnpm patches. v25s are in alphas rn.

**Comment by Ryan432** [comment]
Weird that it works on your app, I have tried in multiple linux pcs and it never worked.

I will wait for the publish and build with a local package for now.

**Comment by xyloflake** [comment]
> Now, if you take the Executing command, you will see that it's not really can be executed as can seen here: <img alt="Screenshot 2024-08-04 at 02 47 13" width="1544" src="https://private-user-images.githubusercontent.com/52235584/354857919-c577a487-65ab-4330-8fc9-9c8576073cf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzcwNzIsIm5iZiI6MTcyMjg3Njc3MiwicGF0aCI6Ii81MjIzNTU4NC8zNTQ4NTc5MTktYzU3N2E0ODctNjVhYi00MzMwLThmYzktOWM4NTc2MDczY2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE2NTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMDU4NmFhMjFjNzkyZWY4MjUxMjQwOTlhNGZiZGY5OGU3NGIwYjM4MDM1ZmUyYmM1ZWRlMDhjOTA0N2YyNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4PXQY4wKJCuE8nLGKndMvcLVn7ESKrxCOLNeWiMakDs">

@Ryan432 that's because you're running the command with no quotes after /usr/bin/pkexec. It works FINE when you include the quotes.

**Comment by Ryan432** [comment]
That command was made by DebUpdater.js, not me, I copied that command to present the issue.

Of course with single quote it works and that exactly my fix.

**Comment by xyloflake** [comment]
> That command was made by DebUpdater.js, not me, I copied that command to present the issue.
> 
> Of course with single quote it works and that exactly my fix.

Sorry, my bad. I thought pkexec needed quotes before `bin/bash`.

**Comment by xyloflake** [comment]
@Ryan432 how are you determining that what you're executing was **exactly ** what electron-updater was running?![image]

I simulated a similar environment and it generates those quotes for me.
(https://github.com/user-attachments/assets/b2019afd-c40b-4a63-9f75-1326c25d9d4b)

**Comment by Ryan432** [comment]
I determine it by application logs when running the app through the terminal.
The function `spawnSyncLog` prints before executing.

**Comment by xyloflake** [comment]
> I determine it by application logs when running the app through the terminal.
> The function `spawnSyncLog` prints before executing.

The logs don't show the single quotes either for me, but patching with a console.log prints the entire command with the single quotes.

**Comment by xyloflake** [comment]
@Ryan432 congratulations on getting the PR merged! I think you can close this now 😄

Once again, nice work, thank you for your contribution!!

**Comment by Ryan432** [comment]
> @Ryan432 congratulations on getting the PR merged! I think you can close this now 😄
> 
> Once again, nice work, thank you for your contribution!!

Issue is closed, thank you :)
