### ISSUE TITLE
Cannot include `node_modules/*/examples/**/*`?

### ISSUE THREAD

**Issue by Bug-Reaper** [electron-userland/electron-builder#8397]
* **Electron-Builder Version**:  24.13.3
* **Node Version**: 16.20.2
* **Electron Version**: 29.4.5
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater**: 6.2.1
* **Target**: MacOS - ARM-64 - DMG

Popular lib THREE.js includes a variety of optional (but useful) modules in `node_modules/three/examples/**/*`. My app uses these and they're not getting bundled into my ASAR.

I see the default [file filters](https://www.electron.build/configuration/contents#files) cause these to be filtered out but I cannot figure out how to stop this behavior. I've tried below config and a few variants:
```javascript
{
   files : [
      "**/*",
      "**/node_modules/*/examples/**/*",
    ]
}
```
From the docs it appears I'm getting f*cked by "**All default ignores are added in any case**" which seems to be the case even if the default-ignores are explicitly included.

Is there some way to override the default ignores so I can build properly?

**Comment by Bug-Reaper** [comment]
I went snooping and I couldn't locate where these "default-ignores" are appended. Ironically, I did discover a test that accomplishes a work-around for my exact issue lol: https://github.com/electron-userland/electron-builder/blob/84f290990915d7ffa0d2dfe0a1d739aeb2b21560/test/src/BuildTest.ts#L336-L339


This does force the relevant files to be included but it feels hacky and borderline undocumented. Are we open for an easier way for users to override the "default-ignore" patterns?

**Comment by beyondkmp** [comment]
By default, these files will be excluded.

https://github.com/electron-userland/electron-builder/blob/84f290990915d7ffa0d2dfe0a1d739aeb2b21560/packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts#L17-L33


We should provide an option that allows users to decide for themselves, or perhaps we could remove these examples. @mmaietta , what do you think?

**Comment by mmaietta** [comment]
@beyondkmp I just realized this may have a different underlying issue.

Even if there's a default excludes, I think we should allow specifications in the `files` to be able to override that behavior. Basically, check if filematcher matches the `files` array as more important than the default excluded files.

```
   files : [
      "**/*",
      "**/node_modules/*/examples/**/*",
    ]
```
This should be prioritized higher than `topLevelExcludedFiles`. This would prevent having to add another configuration option and I think be more intuitive since the `files` array is supposed to be an overall configuration for the asar. What are your thoughts?

**Comment by Bug-Reaper** [comment]
> Even if there's a default excludes, I think we should allow specifications in the `files` to be able to override that behavior. Basically, check if filematcher matches the `files` array as more important than the default excluded files.

Intuitively that was what I assumed the behavior would be. Possibly tricky to implement no?

Also I really like the [PR-ed](https://github.com/electron-userland/electron-builder/pull/8398) config boolean to skip the default-ignores entirely looks helpful and nice to have for when you wanna go very custom with includes.

**Comment by beyondkmp** [comment]
> check if filematcher matches the `files` array as more important than the default excluded files.

I don't see any issues on my end, and indeed, it should be added to avoid user confusion.

However, I suggest also including a `disableDefaultIgnoredFiles` configuration to allow users to easily set this option.

**Comment by Bug-Reaper** [comment]
Just a note for anyone that stumbles onto this from google or something. I Had to modify the workaround slightly to allow proper bypass in my windows builds:
```javascript
 onNodeModuleFile: filePath => { 
   // Force include this directory in the package 
   return (filePath.includes("node_modules/three/examples") || filePath.includes("node_modules\\three\\examples")) 
 }, 
```
Though if you're using a newer version of electron check for aforementioned `disableDefaultIgnoredFiles` and/or possibly `files` override of defaults.

**Comment by mmaietta** [comment]
@Bug-Reaper I think an alternative route you can use is with `import * as path from "path"` then use `filePath.includes('node_modules${path.sep}three${path.sep}examples')`

Just merged the other PR though, it'll make it out in the next release (tag `next`)
