### ISSUE TITLE
Changing Icons (not updating on dist output)

### ISSUE THREAD

**Issue by philcockfield** [electron-userland/electron-builder#840]
* **Version**:  `7.13.0`

* **Target**:  `mac`

On the Mac, I'm changing the icons that are in the build folder. When I package the app, the new icon is not being updated consistently across all of the output files.

Is there a build-cache somewhere that I need to delete?

I have tried deleting the Xcode/DerivedData but that makes no difference.

Thanks.

**Comment by develar** [comment]
Do you mean that icon of your `YourName.app` in the Finder has old icon?

**Comment by philcockfield** [comment]
The `build` folder with the latest icon selected - looks like this:

![image](https://cloud.githubusercontent.com/assets/185555/19613758/229cb484-984b-11e6-9913-829509488260.png)


The built `dist` folder after a build has this:

![image](https://cloud.githubusercontent.com/assets/185555/19613766/2fba43d4-984b-11e6-80b1-508a39d4197c.png)

Which is a previous incarnation of the icon.

And the DMG when opened does have the latest version of the icon.

![image](https://cloud.githubusercontent.com/assets/185555/19613780/4efdb9e2-984b-11e6-9db9-e115e88dd127.png)

**Comment by philcockfield** [comment]
Furthermore, it's displaying differently on retina and non-retina screens:

## Non-retina
![image](https://cloud.githubusercontent.com/assets/185555/19613980/0a61a558-984d-11e6-8e14-19eb775668f2.png)

## Retina
![image](https://cloud.githubusercontent.com/assets/185555/19613985/11368056-984d-11e6-8bba-9d3e67a80433.png)


I wonder if this is perhaps. the Finder caching things.

**Comment by willyb321** [comment]
@philcockfield I did a bit of research on the topic - and it seems that your hunch was correct - see [here](https://gist.github.com/fabiofl/5873100) for a potential fix for it!

**Comment by develar** [comment]
I can confirm, that it is Finder cache issue — not your app or electron-builder issue.

**Comment by philcockfield** [comment]
Pulling a bunch of those suggestions together, I have this "nuke'em" set of commands:

    sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {};
    sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {};
    sudo rm -rf /Library/Caches/com.apple.iconservices.store
    killall Dock
    killall Finder

Not totally working - the DMG is still lagging behind, but some of the icons are now updating.  Thanks everyone.

**Comment by develar** [comment]
Help-wanted — electron-builder should not  confuse users. Probably we should touch application executable to update cache.

**Comment by philcockfield** [comment]
What would be the file to `touch`?

In this case, would it be:

    touch /<path>/dist/mac/Team DB.app
    touch /<path>/dist/mac/Team DB.app/Contents/Info.plist

![image](https://cloud.githubusercontent.com/assets/185555/19660010/af982d3c-9a8a-11e6-8712-a6323071c887.png)

**Comment by develar** [comment]
8.4.1+ will touch `.app` directory.

**Comment by philcockfield** [comment]
Awesome.
