### ISSUE TITLE
Post uninstall on OSX

### ISSUE THREAD

**Issue by khaledabbas** [electron-userland/electron-builder#841]
* **Version**: 
7.10.2

* **Target**: 
Mac, Squirrel

I want to clear all webview cache when the app is uninstalled (without this, the user keeps logged-in in the embedded web app even after re-install). In windows, I can do this by handling `--squirrel-uninstall` event. Is there a similar way for doing this with the OSX version of the app?

Thanks

**Comment by develar** [comment]
No. And it is ok on macOS.

> even after re-install

It is ok. No install actions — it is not windows. If it is important for user — user can use sign-out option in your app (or manually remove corresponding folder).
