### ISSUE TITLE
Confusing versioning of electron-updater

### ISSUE THREAD

**Issue by ficristo** [electron-userland/electron-builder#8430]
The latest version on GitHub is 6.3.4 but if you run something like `npm view electron-updater version` it says the latest version is 6.2.1
Is electron-updater on alpha development? If so why the version on GitHub is not something like 6.3.4-alpha.1 ?
If not can the version 6.3.4 be marked as latest on npm?

**Comment by Tom4nt** [comment]
I was wondering the same thing. I need to upgrade to 6.3.1 because of #8264.

**Comment by mmaietta** [comment]
The "latest" tag on GH is the result of the CD automation always marking it as such, but the source of truth should be 
https://www.npmjs.com/package/electron-updater?activeTab=versions
https://www.npmjs.com/package/electron-builder?activeTab=versions

I haven't gotten around to promoting `next` to `latest` but I'll do it soon, was waiting on more community adoption before toggling it as `latest`

**Comment by ficristo** [comment]
I was looking at some security issues and found out there was one related to electron-updater.
I thought was fixed in the latest version so I was a bit surprised to still have the warning.
It would be nice to make a little clearer that the latest version on GH could be not the latest on npm.
That said feel free to close this issue.

**Comment by mmaietta** [comment]
Update: `next` tags have been promoted to `latest`
