### ISSUE TITLE
25.0.5 builds broken due to missing native binaries

### ISSUE THREAD

**Issue by Galkon** [electron-userland/electron-builder#8431]
* **Electron-Builder Version**:  25.0.5

* **Node Version**:  20.11.0

* **Electron Version**: 32.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS arm64 dmg

I am having a lot of issues with macos-14 github action runners and hdiutil errors, so I tried upgrading to 25.0.5 for the retry logic it has. This results in the build breaking, seemingly related to native modules going missing for both macOS and windows. The latest 24.x works.

![image](https://github.com/user-attachments/assets/8e2dcd0e-7d2f-4a77-b9b4-738494bdad5f)
![image](https://github.com/user-attachments/assets/4f68f210-1482-4358-8922-6bdcf7adc125)

**Comment by beyondkmp** [comment]
Can you provide a minimal reproducible demo code?

**Comment by Galkon** [comment]
> Can you provide a minimal reproducible demo code?

Unfortunately I cannot, this is the electron app of a private repository, and recreating the same scenario with a native node module isn't doable publicly right now.

I am going to test 25.0.3 to see if it worked prior to https://github.com/electron-userland/electron-builder/pull/8392

**Comment by beyondkmp** [comment]
You can reproduce this using a public native Node module along with your Electron Builder configuration.

**Comment by Galkon** [comment]
25.0.3 also did not work. If I find time I will make a repro project

**Comment by benoitf** [comment]
updating to v25.0.5 from 24.13.3 was also breaking our builds

example of failure:
```
Uncaught Exception:
TypeError: Class extends value undefined is not a constructor or null
at Object.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/minizlib/dist/commonjs/index.js:138:6)
at Module._compile (node:internal/modules/cjs/loader:1373:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
at Module.load (node:internal/modules/cjs/loader:1215:32)
at Module._load (node:internal/modules/cjs/loader:1031:12)
at c._load (node:electron/js2c/node_init:2:17025)
at Module.require (node:internal/modules/cjs/loader:1240:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/tar/dist/commonjs/parse.js:24:20)
at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

no 'minimal reproducer' :-/ but repository is public

in the tree:
https://github.com/containers/podman-desktop/tree/1949bc2ff50f64137706278082bfefd025141476

(need to fetch this exact commit to reproduce the bug)

using Node.js v20 and then `pnpm install` and then `pnpm compile:current` will produce in `dist` folder dmg, exe or .tgz (depending on if you're on macOS, Windows or Linux) 

moving back to v24.13.3 works, using latest 25.0.5 the binary is no longer starting.
