### ISSUE TITLE
Cannot read properties of undefined (reading 'extends')

### ISSUE THREAD

**Issue by ficristo** [electron-userland/electron-builder#8435]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 20.16.0

* **Electron Version**: 31.4.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: all

I wanted to move the configuration of electron-builder from `package.json` to a typescript file named `electron-builder.ts`.
Running the script `electron-builder --dir` throws the following error:
`Cannot read properties of undefined (reading 'extends')`
I tried to rename the config file but had the same error.
See also:
https://github.com/quadre-code/quadre/commit/9c02b17a31188af27639c68999f38c2e4fd393ce
https://github.com/quadre-code/quadre/actions/runs/10614792861/job/29421489405

Using the js version seems to work (just needs to have a differente name from the default).

**Comment by mmaietta** [comment]
Can you try using `export default` instead of `module.exports`?

This is how I've set up the typescript config file for my test project. Wondering if the `satifies Configuration` is causing the subdependency `read-config-file` (or internally the https://www.npmjs.com/package/config-file-ts package) to throw the error.
```
import { Configuration } from "app-builder-lib"

const options: Configuration = {
    // options
};

export default options;

```

**Comment by ficristo** [comment]
@mmaietta thank you!
It worked https://github.com/quadre-code/quadre/commit/b07a2c8ffefaad4bd6bee2a022a2543e463848ca
I just used the `Configuration` type from `electron-builder` instead of `app-builder-lib`.

I would be nice to add this to the documentation and how to add the types in the jsdoc comment in a js file.
Also it seems that the configuration file can be something like `electron-builder.config.ts` even without using the `--config` command.

**Comment by mmaietta** [comment]
You mean like this? https://www.electron.build/api/programmatic-usage

**Comment by ficristo** [comment]
Oh, didn't see that! 
I was only looking here https://www.electron.build/configuration/configuration
