### ISSUE TITLE
how to build dmg in linux(cent os 7)

### ISSUE THREAD

**Issue by dingshaohua-com** [electron-userland/electron-builder#8445]
how to build dmg in linux(cent os 7)?

* **Electron-Builder Version**:  v24.13.3

* **Node Version**: 20.16.0

* **Electron Version**: v32.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

**Comment by mmaietta** [comment]
Short answer is you can't AFAIK.

dmg's are specific to macos and only can be built on macos due to macos' hdiutil requiring to be present
