### ISSUE TITLE
nsis arguments /allusers /S

### ISSUE THREAD

**Issue by christophew** [electron-userland/electron-builder#845]
- **Version**: 7.14.2

- **Target**: windows, NSIS

Hi,

I"ve created a boringInstaller with the NSIS options.
Now a customers helpdesk asked me if they could bulk install this on all the pc's of the company.

I did some experimenting with the command line arguments on the boringInstaller.
It seems '/S' is supported for a silent install, and '/allusers' for setting the perMachine option..
But, the combination of both arguments doesn't seem to work ('allusers' is ignored in silent mode).

Ofcourse, that is exactly what this helpdesk would want; > installer.exe /S /AllUsers
Is there some way of doing this? Without building 2 installers..

Any help is appreciated,
Christophe

**Comment by develar** [comment]
> Is there some way of doing this?

It seems it is a bug. Will be fixed (I hope, this week, or you can send PR).

**Comment by christophew** [comment]
Thanks, will be looking forward to the fix.

**Comment by develar** [comment]
`/S /allusers` is supported. Please note — you must run it as administrator.
`/S /currentuser` is supported as well.

**Comment by christophew** [comment]
Tested & working, thanks. Client will  be happy.
