### ISSUE TITLE
Appx build failure because of identityName

### ISSUE THREAD

**Issue by TianbinTobin** [electron-userland/electron-builder#8479]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 20.16.0

* **Electron Version**: 31.6.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: appx

![image](https://github.com/user-attachments/assets/669eaf5b-2ed0-4123-979e-696b3881d3d2)
My identityName is "8B075296.boardmix-" cause build failure.
![image](https://github.com/user-attachments/assets/fa972d13-9aac-4d18-9ffe-1d7b13b07e56)
I can't specify applicationId myself if the identityName exists.

**Comment by mmaietta** [comment]
Can you share your electron-builder config? My initial guess is that what you have set for the `applicationId` field should instead be `identityName`, which maps to `Package/Identity/Name` in your screenshot

**Comment by TianbinTobin** [comment]
> Can you share your electron-builder config? My initial guess is that what you have set for the `applicationId` field should instead be `identityName`, which maps to `Package/Identity/Name` in your screenshot你能分享你的电子构建器配置吗？我最初的猜测是，您为`applicationId`字段设置的内容应该是`identityName` ，它映射到屏幕截图中的`Package/Identity/Name`
> 
> Your error is being thrown here in the `applicationId` logic您的错误在`applicationId`逻辑中抛出
> 
> https://github.com/electron-userland/electron-builder/blob/b3ce7f788cccf87ba841c9189a3b8758cd7c27c2/packages/app-builder-lib/src/targets/AppxTarget.ts#L246-L248

**Comment by TianbinTobin** [comment]
> Can you share your electron-builder config? My initial guess is that what you have set for the `applicationId` field should instead be `identityName`, which maps to `Package/Identity/Name` in your screenshot

![image](https://github.com/user-attachments/assets/5122bb12-1505-4964-abfe-4bb6c93aadec)

If I don't set identityName, then I have to set productName to “8B075296.boardmix-”, but that won't work.
![image](https://github.com/user-attachments/assets/a4e1c1f7-4482-4616-9f46-3b81ad04f373)

I wish I could use my own applicationId first, rather than calculate it based on identityName, unless I didn't set applicationId.

**Comment by mmaietta** [comment]
Gotcha, got a fix coming your way!

**Comment by mmaietta** [comment]
Released in 25.1.4
