### ISSUE TITLE
"app can't be opened" even if notarization succeeds

### ISSUE THREAD

**Issue by jhh-ncurity** [electron-userland/electron-builder#8509]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 20.12.1

* **Electron Version**: 32.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, dmg, x64

Does anyone has same phenomenon, where all builds succeeds but then, can't be opened on other macOS?

It is code-signed, and notarized successfully... (`spctl` command result captured)

<img width="976" alt="스크린샷 2024-09-19 오후 5 53 32" src="https://github.com/user-attachments/assets/3b50852b-437d-4d58-8d2b-40ec215329d9">

When I run it on terminal using `open` command, I get following error:

```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10810 "kLSUnknownErr: Unexpected internal error" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=3090, NSUnderlyingError=0x600000ad4090 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600000ad4f60 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}}}
```

**Comment by mmaietta** [comment]
```
Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Launchd job spawn failed}
```
Looks like your app is trying to do something that it doesn't have Entitlements for? That and/or the provisioning profile could be misconfigured.

**Comment by jhh-ncurity** [comment]
I believe that provisioning profile is for development purpose only, isn't it? I don't have any explicit settings for the profile. Here is what I did:

`electron-builder`'s internal process doesn't recognize my env var properly so I disabled its process by setting `notarize: false`, then I notarized my app using old-fashioned `afterSign` hook.

`scripts/notarize.cjs`
```js
const { notarize } = require("@electron/notarize")
const path = require("node:path")

module.exports = async (context) => {
    if (process.platform !== 'darwin') {
        return;
    }

    await notarize({
        appPath: path.join(context.appOutDir, `${context.packager.appInfo.productFilename}.app`),
        appleId: "XXX",
        appleIdPassword: "XXX",
        teamId: "XXX"
    })

    console.log(`(scripts/notarize.cjs) Notarization complete.`)
};
```

(credentials are hard-coded only for test purpose, did not upload to any repository)

Did I miss something here?

here is my electron-builder's setting. (json5)

```json
// @see - https://www.electron.build/configuration/configuration
{
  "$schema": "https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json",
  "appId": "...",
  "asar": true,
  "directories": {
    "output": "release/${version}"
  },
  "files": [
    "dist",
    "dist-electron"
  ],
  "mac": {
    "target": { "target": "default", "arch": "x64" },
    "artifactName": "${productName}-${version}-Installer.${ext}",
    "notarize": false
  },
  "afterSign": "scripts/notarize.cjs",
  "win": {
    "requestedExecutionLevel": "requireAdministrator",
    "target": { "target": "nsis", "arch": "x64" },
    "artifactName": "${productName}-${version}-Setup.${ext}",
    "certificateSubjectName": "..."
  },
  "nsis": {
    "oneClick": false,
    "perMachine": true,
    "allowToChangeInstallationDirectory": false,
    "deleteAppDataOnUninstall": false
  },
  "extraResources": ["vpn", "!vpn/*.ovpn"],
  "protocols": { "name": "SSO Redirect", "schemes": [ "..." ] },
  "publish": { "provider": "generic", "url": "http://localhost:8443/downloads/", "timeout": 30000 }
}
```

I believe in recent `electron-builder`, necessary settings such as, `hardenedRuntime` etc... are set by default.

And here is my entitlements:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.cs.allow-jit</key>
		<true/>
	</dict>
</plist>
```

fyi, my app is custom openvpn GUI app. Is there anything weird in my settings that I can dig into?

**Comment by mmaietta** [comment]
Not sure what the name of your entitlements file is, so I felt it worth mentioning. If the entitlements file isn't located in your build resources (expecting  `<build resources dir>/entitlements.mac.plist`), then it isn't automatically being used by electron-builder. You can configure the path manually via: https://www.electron.build/mac#entitlements

**Comment by AndrewEQ** [comment]
I had to add specific node_modules to my asarUnpack for my app to work as it couldn't find the node_modules: https://github.com/electron-userland/electron-builder/issues/6200#issuecomment-907830847

For me specifically it was:
```
asarUnpack:
  - "**/node_modules/sharp/**"
  - "**/node_modules/semver/functions/coerce/**"
  - "**/node_modules/yargs/helpers/**"
```

**Comment by AndrewEQ** [comment]
...ok, upon further inspection, my ```"postinstall": "electron-builder install-app-deps",``` in the package.json was failing the rebuild, I fixed it by downgrading to the matching Node version for Electron 32.1.2 (https://www.electronjs.org/blog/electron-32-0) which is Node 20.16.0... after fixing it, I didn't have to specifically specify node_modules for asarUnpack 🥇

**Comment by AndrewEQ** [comment]
Sorry, false alarm; it works with electron-builder 24.13.3

**Comment by jhh-ncurity** [comment]
I started over and created new project with `npm create vite@latest` and then select `Others` > `create-electron-vite` template.

And put all code-sign and notarization settings there, and results are same.

I think its problem is on apple's side maybe although all verification commands say succeeded on code-signing and notarization.

**Comment by mmaietta** [comment]
@AndrewEQ I think your issue is isolated to https://github.com/electron-userland/electron-builder/issues/8518 and not this issue.

@jhh-ncurity curious if you keep all the code-sign and notarization settings the same (using `afterSign` hook as you mentioned previously), does the app run when packaged with electron-builder v24.13.3?

**Comment by jhh-ncurity** [comment]
@mmaietta It is same with v24.13.3... I don't think this is a electron problem anymore. I think there is an issue with our apple developer program. I renewed it this month and got confirm mail but I think it somehow did not applied correctly. Although all commands verifies code sign and notarized successfully I still suspect it. I've sent a ticket to Apple.

**Comment by jhh-ncurity** [comment]
For anyone interested, it is found out to be caused by MS Teams.

If I pass the `dmg` file over MS Teams Chat, it somehow happens. If I just uploaded to web and download it using a browser, it's fine.

I don't know why this happens. but this was so hard to find out as all inspecting commands show no relevant error message.

**Comment by paladin952** [comment]
> > If I pass the `dmg` file over MS Teams Chat, it somehow happens. If I just uploaded to web and download it using a browser, it's fine.message.
> 
> Spent hours trying fix this exact issue before finding this comment. What on earth is causing it??

damn! same happened to me with whatsapp. Thanks!
