### ISSUE TITLE
Compiling on win x64 fails with gyp modules

### ISSUE THREAD

**Issue by cajus** [electron-userland/electron-builder#851]
* **Version**: 7.14.2

* **Target**: win x64

I've a small project that is build like the doc-linked sample 3D CAD thingie - a two *package.json* structure. When I run `npm install` inside the *app* subfolder, the included *keytar* node module is compiled and everything seems fine.

If I run *npm run dist* from the top level directory, *something* seems to be different:

```
PS C:\Users\Cajus Pollmeier\Dev\desktop-app> npm run dist

> @ dist C:\Users\Cajus Pollmeier\Dev\desktop-app
> npm run compile && build


> @ compile C:\Users\Cajus Pollmeier\Dev\desktop-app
> rimraf app/out

Rebuilding app dependencies for arch x64 to C:\Users\Cajus Pollmeier\Dev\desktop-app\app

Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> keytar@3.0.2 install C:\Users\Cajus Pollmeier\Dev\desktop-app\app\node_modules\keytar
> node-gyp rebuild


C:\Users\Cajus Pollmeier\Dev\desktop-app\app\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\nod
e-gyp.js" rebuild )  else (node "" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
  main.cc
c:\users\cajus pollmeier\dev\desktop-app\app\node_modules\keytar\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated [C:\Users\Cajus Pollmeier\
Dev\desktop-app\app\node_modules\keytar\build\keytar.vcxproj]
  C:\Users\Cajus Pollmeier\.electron-gyp\.node-gyp\iojs-1.4.4\deps\v8\include\v8.h(3052): note: see declaration of 'v8::Array::CloneElementAt'
c:\users\cajus pollmeier\dev\desktop-app\app\node_modules\keytar\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated [C:\Users\Cajus Pollm
eier\Dev\desktop-app\app\node_modules\keytar\build\keytar.vcxproj]
  C:\Users\Cajus Pollmeier\.electron-gyp\.node-gyp\iojs-1.4.4\deps\v8\include\v8.h(4030): note: see declaration of 'v8::BooleanObject::New'
C:\Users\Cajus Pollmeier\Dev\desktop-app\app\node_modules\keytar\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated [C:\Users\Cajus Pollmeier\Dev\desktop-ap
p\app\node_modules\keytar\build\keytar.vcxproj]
  C:\Users\Cajus Pollmeier\.electron-gyp\.node-gyp\iojs-1.4.4\deps\v8\include\v8.h(2763): note: see declaration of 'v8::Object::SetAccessor'
  keytar_win.cc
  win_delay_load_hook.cc
C:\Users\Cajus Pollmeier\.electron-gyp\.node-gyp\iojs-1.4.4\Release\iojs.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0xF2ADE [C:\Users\Cajus Pollmeier\Dev\desktop-app\app\node_
modules\keytar\build\keytar.vcxproj]
```

So - the disk is not full, and it doesn't seem likely that the build process consumes 35GB of disk space. The disk isn't corrupted, too.

What can I do to make the build proceed?

**Comment by develar** [comment]
Please try to remove `node_modules` from app directory (to remove cache).

**Comment by cajus** [comment]
@develar thanks for the reply. Already did this multiple times and it doesn't help.

**Comment by develar** [comment]
> I've a small project that is build like the doc-linked sample 3D CAD thingie

To be sure that your Windows is correctly configured — please try to build https://github.com/develar/onshape-desktop-shell (https://git-lfs.github.com is required) — 

```sh
git lfs clone git@github.com:develar/onshape-desktop-shell.git
cd onshape-desktop-shel
npm install
npm run dist
```

**Comment by develar** [comment]
Do you have `  "postinstall": "install-app-deps",` task in your main package.json script? (in the readme: To ensure your dependencies are always updated based on both files, simply add "postinstall": "install-app-deps" to your development package.json. This will basically automatically trigger an npm install within your app directory so you don't have to do this work everytime you install/update your dependencies.) Does it work for you (i.e. if you run `npm install` in the root of the project)?

**Comment by cajus** [comment]
Yes, I've the *install-app-deps* in my top level package.json. Checking... If I clean all *node_modules* and run `npm install`, I get the same error.

**Comment by cajus** [comment]
Haha. Figured it out. There was one `npm run compile` left in my top level *package.json*. I've no typescript and missed that one removal. If the error messages would have been a bit more precise, I could have figured that out more early. Doh.

Thanks for your help - closing ;-)

**Comment by develar** [comment]
> If the error messages would have been a bit more precise, I could have figured that out more early. Doh.

Yeah, it is why yarn will be recommended soon instead of unreliable and buggy npm.
