### ISSUE TITLE
The build process will change the encoding of the license.rtf file.

### ISSUE THREAD

**Issue by TianbinTobin** [electron-userland/electron-builder#8512]
* **Electron-Builder Version**: v25.1.4

* **Node Version**: v20.16.0

* **Electron Version**: v31.6.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

The original encoding of my license.rtf file is UTF-8, but after the build process, the encoding has changed to UTF-8 with BOM.
This behavior will cause the License display on the installation interface to appear as garbled text.
(My language is Chinese.)
![image](https://github.com/user-attachments/assets/7997b526-5108-45f2-9aa0-62ab15ba96a5)

**Comment by mmaietta** [comment]
@TianbinTobin what OS are you packaging your Windows app on?

@beyondkmp looks like this may be related to the changes in https://github.com/electron-userland/electron-builder/pull/8314. Wondering if we need to have conditional logic when building on windows vs mac w.r.t file encoding

**Comment by TianbinTobin** [comment]
> what OS are you packaging your Windows app on?

@mmaietta  Windows

**Comment by beyondkmp** [comment]
@mmaietta  In https://github.com/electron-userland/electron-builder/issues/8294,  I have only fixed the issue of garbled text display on Windows. 

The problem describing seems to be a different issue on Windows. @TianbinTobin  Could you provide a minimal demo to reproduce the problem?

**Comment by TianbinTobin** [comment]
> Could you provide a minimal demo to reproduce the problem?

[https://github.com/TianbinTobin/electron-builder-8512.git](https://github.com/TianbinTobin/electron-builder-8512.git)

The first build will change the encoding of the rtf file, and the second build of the installation package will appear garbled on windows. @beyondkmp
