### ISSUE TITLE
Auto updater doesn't support modern yaml syntax

### ISSUE THREAD

**Issue by mikey0000** [electron-userland/electron-builder#8513]
* **Electron-Builder Version**: 
latest

* **Node Version**: 

* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Target**: 
mac

when using yq to merge some file entries it produces a files list with the following

files: |-

which is supposedly valid?

electron auto updater fails with files.map is not a function

**Comment by mmaietta** [comment]
We use the latest version of https://www.npmjs.com/package/js-yaml under-the-hood. Not sure if there's anything electron-builder can do here.

**Comment by mikey0000** [comment]
Thanks, I'll see if yq peeps can help resolve this.
