### ISSUE TITLE
.directories.output option ignored in package.json

### ISSUE THREAD

**Issue by eriedl** [electron-userland/electron-builder#852]
* **Version**: 7.14.2

* **Target**: any

 The option [.directories.output](https://github.com/electron-userland/electron-builder/wiki/Options#MetadataDirectories-output) is ignored when specified in `package.json` and it always defaults to `dist`.
When using electron-builder from a script and setting the `devMetadata.directories.output` the custom directory value it is picked up correctly.

**Comment by develar** [comment]
Do you specify it in the `build` (not correct) or in the root entry?

**Comment by eriedl** [comment]
You are correct, I had configured it under `build`. The docs are actually pretty clear about it. I must have mixed up the indentation.
