### ISSUE TITLE
Incorrect @electron/rebuild output build type

### ISSUE THREAD

**Issue by jacksman** [electron-userland/electron-builder#8529]
* **Electron-Builder Version**: 25.0.1

* **Node Version**:  20.17.0

* **Electron Version**: 32.1.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: any

I believe this line might contain a typo. AFAIU It links the output module type with the debug log level setting.
(README ref: https://github.com/electron-userland/electron-builder/blob/2db62725d060d9f8d84194cba6c1118d93856205/README.md?plain=1#L202-L204)

https://github.com/electron-userland/electron-builder/blob/2db62725d060d9f8d84194cba6c1118d93856205/packages/app-builder-lib/src/util/yarn.ts#L206

According to the `@electron/rebuild` API documentation, the `debug` parameter is intended to specify whether to generate a Debug or Release version of the module and not the log level ([ref](https://github.com/electron/rebuild/blob/cb372cdf09d9ca3ac8f1231608e4ebedddabe51c/src/rebuild.ts#L58-L63))

In the old legacy builder version (I was using e`lectron-builder` 24.6.4), this parameter was (and still is) ignored, always producing Release builds. This change is causing my current build flow to fail, as several modules expect to be rebuilt in Release mode. However, I still want to enable verbose logging in the `electron-builder` process.

**Comment by mmaietta** [comment]
Nice find and thank you for reporting with debug/investigative work!

Created PR https://github.com/electron-userland/electron-builder/pull/8531 to remove the `debug` property from electron-rebuild configuration

**Comment by mmaietta** [comment]
Released in v25.1.6
