### ISSUE TITLE
Error with nconf after upgrading to latest version of electron-builder.

### ISSUE THREAD

**Issue by ahgan84** [electron-userland/electron-builder#853]
- **Version**: 7.14.2

- **Target**: Windows OS 32-bit

Hi guys, before this I'm using electron-builder version 3.25.0 to compile my apps to become exe to run in windows and everything is well.
I have just upgraded electron-builder to the latest version which is 7.14.2. The compiling to exe is successful. But when I run my app, the error "cannot find module nconf" appear. I'm using nconf to read settings that my app will need from a config file. I also have already downloaded the nconf module into my node_modules So, any idea what goes wrong? 

Below is the full error message:

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'nconf'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Work\Project2016\gmc-vct-psy-nsis\dist\win-ia32-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Work\Project2016\gmc-vct-psy-nsis\dist\win-ia32-unpacked\resources\app\settings.js:3:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by ahgan84** [comment]
After investigation, I notice that the node_modules folder that my exe use is empty. The compiler does not copy the packages inside the node_modules during compiling. Any idea why this is happening?

**Comment by develar** [comment]
Do you use two-package.json project structure? Did you call `npm install` before build? Please attach build log.

**Comment by keverw** [comment]
Are you using a native module? Wonder if maybe it's the same issue I'm having.

**Comment by ahgan84** [comment]
I only use one package.json for my app.
What's the purpose of calling npm install? Install what?
Where to get build log?

**Comment by develar** [comment]
> What's the purpose of calling npm install? Install what?

Install dependencies in your project. Stupid question, but who knows ;)

> Where to get build log?

Console output of electron-builder.

**Comment by ahgan84** [comment]
Yes. Those dependencies are installed in my project.. jz that when I run built n compiled it to become an exe.. the output node_modules folder is empty.. this causes the exe cannot find the nconf package..

**Comment by ahgan84** [comment]
Anybody know what's wrong wif my issue?

**Comment by develar** [comment]
@ahgan84 "Console output of electron-builder." is still needed. Sample package.json is welcome also.

**Comment by ahgan84** [comment]
I think I don't have the console output because I can compile my app successfully. Only if compilation error then the error will be shown in console output right?

Below is my package.json:

`{
  "name": "myApp",
  "version": "1.0.0",
  "description": "myApp",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "pack": "build --arch ia32",
    "dist": "build --arch ia32"
  },
  "author": "My",
  "license": "ISC",
  "build": {
    "appId": "myApp",
    "win": {
	  "target": "nsis",
      "iconUrl": "http://megaicons.net/static/img/icons_sizes/51/832/64/pirate-icon.png"
    },
    "asar": false
  },
  "devDependencies": {
    "electron-builder": "^7.14.2",
	"electron-prebuilt": "^1.4.4",
    "electron-squirrel-startup": "^1.0.0",
    "ipc": "0.0.1",
    "nconf": "^0.8.4"
  }
}`

Below is my project folder structure for my app:

build
--icon.ico
dist
--win-ia32
--win-ia32-unpacked
node_modules
--(ALL THE PACKAGE THAT MY APP USE)
index.html
builder.html
package.html

Hope this help you guys to figure out what's wrong with my app.

**Comment by ahgan84** [comment]
Anyone can help me with this?

**Comment by develar** [comment]
@ahgan84 `nconf` listed in the `devDependencies`, but must be in the `dependencies`.

**Comment by develar** [comment]
`electron-squirrel-startup` is not required for you since you use NSIS.

`iconUrl` option is also not required for NSIS.

**Comment by ahgan84** [comment]
But how come the node_modules is empty in the win-ia32-unpacked folder?

**Comment by ahgan84** [comment]
The compiler should copy the whole node_modules folder into win-ia32-unpacked folder also right?

**Comment by develar** [comment]
> should copy the whole node_modules folder into win-ia32-unpacked folder also right?

No. All dev dependencies must be pruned. electron-builder copies only production dependencies.

**Comment by ahgan84** [comment]
Then is it that we must have node_modules folder resides in the root of your project and also another node_modules folder resides in the app directory?

**Comment by develar** [comment]
> we must have node_modules folder resides in the root of your project and also another node_modules folder resides in the app directory

No. Npm has production (`dependencies`) and dev dependencies (`devDependencies`). In the app only production dependencies must be packed. Not the whole `node_modules` directory.

**Comment by ahgan84** [comment]
can you write out what is normally the files reside on the root of our project and what is reside in the app directory of our project?

**Comment by develar** [comment]
[Two package.json structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure) is recommended only if you have native dependencies. 

> our project

if you mean your project, you don't use Two package.json structure as far as I see.

**Comment by ahgan84** [comment]
Yup.. I'm now trying to put two package.json and see the problem can be solve or not. 
Is my below project folder structure correct?

app
--node_modules --(ALL THE PACKAGE THAT MY APP USE)
--index.html
--builder.html
--package.html
build
--icon.ico
dist
--win-ia32
--win-ia32-unpacked
node_modules --(ALL THE PACKAGE THAT MY APP USE)
index.html
builder.html
package.html

**Comment by develar** [comment]
> the problem can be solve or not. 

Your problem can be easily solved — `nconf` is not a dev dependency, but production.

> --node_modules --(ALL THE PACKAGE THAT MY APP USE)

Again — we do not copy `node_modules` — we  copy only and only production dependencies.

**Comment by ahgan84** [comment]
yes. the node_modules only contain my production dependencies. 
I think not only nconf should be in the node_modules right? electron-builder packages should be in node_modules right?

**Comment by develar** [comment]
> electron-builder

No. electron-builder is a dev dependency, not production.

**Comment by ahgan84** [comment]
Then does electron-builder will be put inside the node_modules folder in the installation setup?
