### ISSUE TITLE
How to silence warning "no signing info identified, signing is skipped"?

### ISSUE THREAD

**Issue by crystalfp** [electron-userland/electron-builder#8559]
* **Electron-Builder Version**:  25.1.7

* **Node Version**: 22.5.1

* **Electron Version**: 32.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

With the latest electron-builder version this annoying warning appears five times during build:
```
no signing info identified, signing is skipped  signHook=false cscInfo=null
```
I added `sign: null` in the `win` section of `electron-builder.yaml` but seems it has no effect.
I don't need signing. What should I do to silence the warning?
Thanks!

**Comment by mmaietta** [comment]
Hi @crystalfp, thanks for the feedback! I can definitely just convert that to a `log.debug` 🙂 
The reason I had added it was that there were some users realizing that their app wasn't being signed and I had wanted to make it more explicit. Great feedback though
