### ISSUE TITLE
DMG background resource does not work if projectDir set

### ISSUE THREAD

**Issue by lishid** [electron-userland/electron-builder#858]
* **Version**: 7.14.2

* **Target**: OSX(DMG)

When using a projectDir that's different than current directory ("."), specifying a dmg background causes an exception (Error: ENOENT: no such file or directory, lstat 'resources/osx/dmg-background.png').

Code below refers to file https://github.com/electron-userland/electron-builder/blob/master/src/targets/dmg.ts

The root cause seems to be from line 30
```await copy(specification.background!, path.join(backgroundDir, backgroundFilename))```

Looking at how the dmg icon resource is processed, we notice that it uses `path.resolve(packager.projectDir, specification.icon)` to find the resource. Maybe that should have been used?

**Comment by develar** [comment]
Fix will be in 20 minutes. Thanks for clear report.

**Comment by develar** [comment]
Fixed in 7.15.2
