### ISSUE TITLE
Output .exe icon reverts to default electron icon

### ISSUE THREAD

**Issue by liuliu-dev** [electron-userland/electron-builder#8585]
* **Electron-Builder Version**: 25.1.7

* **Node Version**: v20.18.0

* **Electron Version**: 31.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows NSIS

I have an icon.ico file placed in the build folder, and while the output installer (setup.exe) correctly uses this icon, the unpacked executable (.exe) and all system shortcuts (Start Menu, desktop) show the default Electron icon instead of the custom one. 

This seems related to a previously reported issue ([#8187](https://github.com/electron-userland/electron-builder/issues/8187)), which was closed due to inactivity. Since the issue persists, I'm resubmitting it here.

**Comment by drewklein20** [comment]
I have this exact issue as well with 
Electron-Builder Version: 24.9.1

**Comment by drewklein20** [comment]
This worked for me!

https://github.com/electron-userland/electron-builder/issues/5784#issuecomment-817908014

**Comment by liuliu-dev** [comment]
> This worked for me!
> 
> [#5784 (comment)](https://github.com/electron-userland/electron-builder/issues/5784#issuecomment-817908014)

Thank you!
