### ISSUE TITLE
Ask for an advice in folder structure with external JS files

### ISSUE THREAD

**Issue by crashbell** [electron-userland/electron-builder#859]
* **Version**: 7.14.2

* **Target**: MacOS, Windows

Please take a look at the folder structures below:
#### Development folder structure (after compiled from `src`)
```
▾ app/
  ▸ node_modules/
  ▸ out/
  ▸ workers/
    package.json
```

#### Build folder structure
```
▸ app.asar/
  ▸ node_modules/
  ▸ out/
  package.json
▾ app/
  ▸ workers/
```

I'm trying to find a good way to work with external files. Due to our project's needs, we have to fork some processes from `workers` folder. I used `extraResouces` to get rid of `worker` folder and I got a problem since the path of `worker` folder is changed in the build. For instance, if I want to require `blahblah-modules`, I have to declare the path differently for each environment: `blahblah-modules` (development) and `../../app.asar/node_modules/blahblah-modules` (build). I would like to ask for an advice to improve this silly path.

**Comment by develar** [comment]
To be clear — require from worker code, right?

**Comment by develar** [comment]
Possible approach — https://github.com/electron-userland/electron-builder/wiki/Loading-App-Dependencies-Manually

**Comment by crashbell** [comment]
@develar Thanks a lot. That seems what I'm looking for.

**Comment by develar** [comment]
Probably, if you can provide sample app, I will try find free time to play with it and simplify somehow.

Maybe, electron supports this search path if your worker will use `asar.unpack`. I am sorry, but without sample app I will not investigate it further.

**Comment by crashbell** [comment]
@develar That's surprising when I tried to make a sample app. I can fork the worker with the path like `electron-sample.app/Contents/Resources/app.asar/workers/text-generator`. Regarding [this](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#executing-binaries-inside-asar-archive) I never thought that it could work. So I don't need any workaround so far.
