### ISSUE TITLE
Additional unversial exe package is generated

### ISSUE THREAD

**Issue by qishibo** [electron-userland/electron-builder#8597]
* **Electron-Builder Version**: 23.0.2

* **Node Version**: v16.20.0

* **Electron Version**:12.2.3
* **Electron Type (current, beta, nightly)**:

* **Target**:  `{"target": "nsis", "arch": ["x64", "arm64"]}`

if I build arm64 and x64 nsis target, and my build field like bellow
```json
"win": {
  "target": [
    {"target": "nsis", "arch": ["x64", "arm64"]}
  ]
},
"nsis": {
  "artifactName": "${productName}-Setup-${version}-${arch}.${ext}",
}
```

after building I got 3 exes instead of 2(arm64 and x64), it seems that an universial package is generated, and its size is about 2 times bigger than arm64 and x64. I am quite confused about this, can I remove the universal version??

<img width="931" alt="image" src="https://github.com/user-attachments/assets/ef8fd507-0845-415e-8ea4-2cba76f877b2">

**Comment by qishibo** [comment]
if I don't want this universal version, how can I config to reduct this


![image](https://github.com/user-attachments/assets/73864d77-b224-48c0-9ec9-16b88123525b)

**Comment by mmaietta** [comment]
I took a solid look at the code and am unable to determine the reason as to why a universal package needs to be generated. The logic is quite complex though and AFAICT I don't think it's possible to remove the universal package from being generated.
AFAICT, the logic exists here: https://github.com/electron-userland/electron-builder/blob/f941f18a003a3762949a36e4a06e98e1014d3ed1/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L237-L252

**Comment by mmaietta** [comment]
Looks like there's been a request to disable the universal package before as well: https://github.com/electron-userland/electron-builder/issues/8298

**Comment by mmaietta** [comment]
X-posting

>Would anyone be willing to test out this [patch-package](https://www.npmjs.com/package/patch-package)?

Patch found here: https://github.com/electron-userland/electron-builder/issues/8298#issuecomment-2432884953

**Comment by m1rn** [comment]
Is there any progress?
