### ISSUE TITLE
How to prevent package.json's description from being used as the process name?

### ISSUE THREAD

**Issue by dorei44** [electron-userland/electron-builder#8599]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 22.8.0

* **Electron Version**: 33.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis

Somehow the description from package.json is being used as the process name instead of the title? How to change this?

![ss1](https://github.com/user-attachments/assets/9051f1e0-9246-40b9-904d-dcd9a4241f42)

![ss](https://github.com/user-attachments/assets/412ce04b-1b88-4a73-8f51-eb85ab3c99b8)

**Comment by mmaietta** [comment]
This is new, I've never seen a report of this before.
Was this working this way in a previous electron-builder version? Trying to determine where I can do a git diff from.

**Comment by dorei44** [comment]
My build from 2 months ago shows the "correct" behavior which uses `"electron-builder": "^24.13.3"` and `"electron": "^31.4.0"`

**Comment by mmaietta** [comment]
This is the only PR that sticks out to me. https://github.com/electron-userland/electron-builder/pull/8125
The release previous to that is 25.0.0-alpha.2, would you be willing to give that a test run to help isolate the git diff? (The diff between 24.13.3 and 25.1.8 is HUGE to work with)

**Comment by dorei44** [comment]
I gave `25.0.0-alpha.2` a try and it produces the "correct" behavior.

**Comment by dorei44** [comment]
I gave `25.0.0-alpha.2` a try and it produces the "correct" behavior.

**Comment by mmaietta** [comment]
Thanks for confirming. I've opened a revert PR and will get this released as soon as possible 🙂

**Comment by dorei44** [comment]
Yes, the issue occurs in `25.0.0-alpha.3`.

**Comment by mmaietta** [comment]
You're amazing, thanks for the quick confirmation. I have a few other things to get into the next release, but I'll be sure to include the revert as part of it

**Comment by mmaietta** [comment]
Released in [v26.0.0-alpha.3](https://github.com/electron-userland/electron-builder/releases/tag/v26.0.0-alpha.3)!

Note, the alpha version also migrates to electron/asar and integrates electron/fuses (electron-builder config object `electronFuses`). Before I had migrated to electron/asar, several new asar unit tests were added to make sure the migration pathway was clean, so all should be fine. Please do let me know if you experience any issues with it though

**Comment by mmaietta** [comment]
Because you didn't read? It's correctly closed as completed. Please ref: https://github.com/electron-userland/electron-builder/issues/8599#issuecomment-2417176342

A patch fix doesn't redeploy the current version, that's not how releases work...

Fix is under the `v26` `next` tag

**Comment by SupertigerDev** [comment]
And when is that coming out? 2026?

**Comment by mmaietta** [comment]
It's already out ya derp...
>Fix is under the v26 next tag

It's production-ready as it's out of the `alpha` release cycle, the GH pre-release tag and npm `next` tags are used for gradual rollouts. It takes time or adoption percentage before it's promoted to `latest`. See ref for more details as to why: https://github.com/electron-userland/electron-builder/issues/8837

I also don't appreciate your tone. It comes off self-entitled and honestly, is not warranted in a project that is worked on during my free time nor is for-profit.
