### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#860]
7.15.2

1.4.4? Not sure what "target" means in this context

On running app following installation:

`Not allowed to load local resource: file:///C:/Users/Slapbox/AppData/Local/myappname/app-0.9.2/resources/app.asar/app/app.html`

Any ideas? My app is based on Electron-react-boilerplate.

I suspect it's based on the use of this code in my main.js, but I'm not sure what alternative I have to how I'm doing this already.

`mainWindow.loadURL(`file://${__dirname}/app/app.html`);`

**Comment by Slapbox** [comment]
Okay so I am stupidly building from development files, not from a finished bundle.js as I should be. That being said, I'm not sure how to accomplish building from the bundle.js instead of the source. Advice?

**Comment by develar** [comment]
It is not electron-builder issue, please e.g. https://github.com/electron/electron/issues/5107
