### ISSUE TITLE
npm run build no longer creates dmg or zip archive

### ISSUE THREAD

**Issue by rmdashrfv** [electron-userland/electron-builder#8614]
* **Electron-Builder Version**: 23.6.0 & tested on latest version and older versions as well

* **Node Version**:  18.18.2

* **Electron Version**: 30.0.1

* **Target**: 
Mac (dmg, zip)

I've been building apps all year long with no issue, and suddenly, the build process is no longer producing a latest.yml file, a resulting zip target, and several other things that the build process used to create in the ./dist folder. I even went back to an old version of my repo and tried building with electron-builder from months ago that I know was working and still the build result is now different.

Did some API change that I'm not aware of? Now running `npm run build:mac` has a completely different output than it did last month and I haven't changed anything.

Similar to #8544 but for mac. And I know that the electron-builder.yml file is correct because I haven't changed it at all.

```yml
mac:
  hardenedRuntime: true
  target:
    - target: dmg
      arch: arm64
    - target: zip
      arch: arm64
```

This has been the yml code all year and now suddenly, I am getting no dmg and no zip target at all. Only the .app bundle itself.

After completely switching back to a version of my app from 3 months ago, that was already shipped with electron-builder (meaning it is using the same code from 3 months ago), I am now getting the new behavior I've noticed today: No dmg or zip are created at all, despite the fact that 3 months ago it worked.

**Comment by mmaietta** [comment]
>Did some API change that I'm not aware of?

That's super odd indeed as the API has not changed. Can you post back logs of `DEBUG=electron-builder` env var set?

**Comment by rmdashrfv** [comment]
Hard to believe, but this issue was actually caused by me having 0.0 mibps upload speed, while having paid for the best internet plan from my ISP. It never occurred to me that my internet was the issue because it was working well in other places including smaller asset uploads, but it turns out it's not enough bandwidth for code signing an Electron app (or perhaps even a non-electron app)
