### ISSUE TITLE
Need a way to exclude unnecessary files from node_modules in Electron Builder

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#8617]
* **Electron-Builder Version**: 26.0.0-alpha.3

* **Node Version**: v23.0.0

* **Electron Version**: 33.0.1
* **Electron Type (current, beta, nightly)**:

* **Target**: 

### Question:

I am building an Electron project where all the logic is divided into modules, organized as npm workspaces. Each workspace may have an extra build step from `src` to `dist`.

I have a single entry point that calls the backend module. The entry point looks like this:

```javascript
import {initApp} from 'workspace-packages/package-a';

initApp();
```

After compilation, the file structure in the compiled app looks like this:
```
app/
├── node_modules/
│   └── workspace-packages/
│       ├── package-a/
│       │   ├── src/  # Garbage. May be safely removed
│       │   └── dist/  # Runtime code
│       ├── package-b/
│       ├── package-c/
│       └── package-d/
├── entry-point.js
└── package.json
```

The problem I am encountering is that electron-builder copies the entire package directories, including the src/ folders (which contain source files not needed at runtime). I only need the dist/ folders with the compiled runtime code in the final build.

Is there a way to configure electron-builder to exclude the src/ directories or any unnecessary files and only include the compiled dist/ files from the workspace packages?

I hoped to use the `files` parameter in the sub-packages to specify which files should be copied, but it seems that electron-builder does not consider this parameter when copying the packages.

I also looked into the `onNodeModuleFile` hook, but it appears to allow only two states: "Force-Include" and "Default," and does not provide a way to "Force-Exclude" files from the build process.

You can found reference repository here in `feat/workspaces` branch
https://github.com/cawa-93/vite-electron-builder/tree/feat/workspaces

My config is:
```js
export default {
  directories: {
    output: 'dist',
    buildResources: 'buildResources',
  },
  files: [
    'entry-point.js',
  ],
};
```

**Comment by mmaietta** [comment]
> I hoped to use the files parameter in the sub-packages to specify which files should be copied, but it seems that electron-builder does not consider this parameter when copying the packages.

Can you explain more about what this means?

The `files` config param should allow you to specify files inside node_modules via minimatch
https://www.electron.build/contents#files

**Comment by cawa-93** [comment]
I was talking about npm files property in package.json. 

> The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files

**Comment by mmaietta** [comment]
Ahh, I see, thank you.

The `files` property in package.json is for a different purpose than electron-builder's `files`, and I don't think they should overlap in terms of configuration and probably not be implemented for merging the configs either. Looking at your linked repo, electron-builder simply packages the files; it doesn't have the ability to interpolate imported files within the `main` entry points specified in each `package.json` of your workspace.

A great example is here:
```
{
  "name": "@vite-electron-builder/renderer",
  "type": "module",
  "main": "./dist/index.html",
```
If electron-builder just were to "detect" and copy the asset in `main`, no other files would be copied with it. That's why workspaces take a bit more manual setup within electron-builder's `files` config param.

For your project, it looks like you could simply add a minimatch like `'!node_modules/@vite-electron-builder/**/src',` to the `files` config.

**Comment by cawa-93** [comment]
Indeed. Thank you. I was confused by the lack of understanding that electron-builder `file` settings DO affect how the builder copies dependencies. 

I was able to resolve this issue. In the `electron-builder.mjs`, I read the existing workspaces, look for the `files` in each `package.json` field, and add all files that do not fit the defined pattern to the `electron-builder`'s  `file` as exclusion.

Pseudocode:

```js
// electron-builder.mjs
import rootPkg from './package.json' with {type: 'json'};
import mapWorkspaces from '@npmcli/map-workspaces';

const workspaces = await mapWorkspaces({ cwd: process.cwd(), pkg: rootPkg });

const filesToExcludeFromAll = [];

for (const [name, path] of workspaces) {

  const pkgPath = resolve(path, 'package.json');
  const {default: workspacePkg} = await import(pathToFileURL(pkgPath), {with: {type: 'json'}});

  let patterns = workspacePkg.files || [];
  patterns.push('package.json');

  patterns = patterns.map(p => resolve(path, p));

  let filesToExclude = getFilesThatDoesntMathGlobPatterns(
    path,
    patterns,
  );

  filesToExclude = filesToExclude.map(f =>  join('!node_modules', name, f.replace(path + sep, '')));
  allFilesToExclude.push(...filesToExclude);
}

// export config
export default {
  directories: {
    output: 'dist',
    buildResources: 'buildResources',
  },
  files: [
    'packages/entry-point.js',
    ...allFilesToExclude,
  ],
};

```
