### ISSUE TITLE
electron-builder cant build msi after upgrade

### ISSUE THREAD

**Issue by avivsalman** [electron-userland/electron-builder#8619]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 20.11.1

* **Electron Version**: 30.0.8
* **Electron Type (current, beta, nightly)**:

* **Target**: windows msi

got error when packing app with electron-builder version 25.1.8 (msi)

```
⨯ Exit code: 103. Command failed: C:\Users\XXX\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\XXX\dist\dokopos\dokopos 7.1.1.msi -v -spdb -sw1076 -dappDir=C:\XXX\dist\dokopos\win-unpacked -pedantic -wx project.wixobj
C:\XXX\dist\dokopos\__msi-x64\project.wxs(2716) : error LGHT0103 : The system cannot find the file 'C:\XXX\dist\dokopos\win-unpacked\resources\app.asar.unpacked\node_modules\@bugsnag\plugin-electron-client-state-persistence\build\Release\obj\bugsnag_pecsp_bindings\bugsnag_.E1E0FB2C.tlog\bugsnag_pecsp_bindings.lastbuildstate'.
```

i tried to uninstall electron and its worked fine, so i dont understand what happend between version 24.13.3 to 25.1.8, because its worked fine.

**Comment by beyondkmp** [comment]
@avivsalman  Could you provide a minimal demo code to reproduce the issue?

**Comment by nchobat** [comment]
how did you solve it? i have same issue now
