### ISSUE TITLE
Squirrel installer Update.exe missing icon

### ISSUE THREAD

**Issue by elronalds** [electron-userland/electron-builder#862]
* **Version**: 7.15.2

* **Target**: Squirrel.Windows

When I generate a Squirrel installer the Update.exe file doesn't have an icon set.  This should be customisable from the `.build.squirrelWindows` or `.build.win` options.  The Update.exe appears in the Windows task bar so the icon should be customisable.

**Comment by develar** [comment]
Please use nsis target. If custom icon will be set for `Update.exe`, squirrel installer will not work correctly.

**Comment by Stanzilla** [comment]
@develar so far Squirrel is not yet deprecated, is this still a won't fix?

**Comment by develar** [comment]
> squirrel installer will not work correctly.

It is Squirrel.Windows bug / rcedit. So, I am not going to waste my time since NSIS works perfectly.
