### ISSUE TITLE
Add a YouTube Video Tutorial on Packaging and Notarizing macOS Applications

### ISSUE THREAD

**Issue by Chetan11-dev** [electron-userland/electron-builder#8621]
I want to express my heartfelt gratitude for the incredible work you do with Electron Builder. Your tool has been a lifesaver, making the process of creating executables for different platforms a breeze. Thank you for your dedication and effort.

2 weeks ago, I encountered a significant challenge while trying to sign and notarize my application. Despite the available resources, I found the process confusing and assumed prior knowledge. It took me considerable trial and error to finally get the app signing and notarization working correctly.

I realize that many developers face similar frustrations, and more will likely encounter this issue in the future. To help alleviate this problem, I plan to create a comprehensive YouTube video that guides developers through the entire process of signing and notarizing an application, using simple, step-by-step instructions.

I have a feature request: would you consider adding a link to this video in the [Code Signing section](https://www.electron.build/code-signing.html) of your documentation? I believe that a single line in the docs would be incredibly beneficial, saving countless developers from the frustration I experienced.

Please note:

- You are welcome to upload the video on your own YouTube channel. I am not seeking personal recognition.
- As the creator of [Botasaurus](https://github.com/omkarcloud/botasaurus), a framework with 1.4K stars, I assure you of my dedication and commitment to creating a high-quality, informative video.

Thank you for considering my request. I genuinely believe that this video will make a significant difference in the lives of many developers.

**Comment by Chetan11-dev** [comment]
Sure! Here's the plan:

1. Create a rough YouTube video that describes the macOS signing and notarization process in simple steps. (within 2 days)
2. Send the rough video to you for review.
3. You'll provide feedback and suggest any necessary changes to improve the clarity and content of the video.
4. Based on the feedback, create a final production-ready video.
5. Send the final video to you, with youtube tags, description, thumbnail, and you'll upload it to your YouTube channel. (Electron Builder)
6. Add a link to the video on the code signing documentation page at https://www.electron.build/code-signing.html. Ideally an embedded video would be great.

This approach ensures that the video is well-structured, clear, and aligns with the standards of Electron Builder documentation.

Does that sounds good?

Additionally, once the macOS video is available on YouTube, we can follow a similar process for the Windows signing. (which I aim to get done for my app by November End)

**Comment by mmaietta** [comment]
Sounds excellent. Want to ping me via discord? @onegoldfish Might be easier to collaborate there than on this GH issue 🙃
