### ISSUE TITLE
Linux build error "ELF SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by avivsalman** [electron-userland/electron-builder#8624]
* **Electron-Builder Version**: 25.1.5+ (even 26 beta versions)

* **Last working version is**: 24.13.3

* **Node Version**: 20.18.0

* **Electron Version**:32.2.1
* **Electron Type (current, beta, nightly)**:current

* **Target**: linux amd

i am getting this error after packing the application in linux (ubuntu) appimage + deb, i am trying to run the application after succesfullt build process and nothing happend, so i tryed to debug the app with electron inspect and i got this error:

"ELF SyntaxError: Invalid or unexpected token"

<img width="737" alt="image" src="https://github.com/user-attachments/assets/e36e20b7-9c76-4c8b-928c-36cc4315819c">

**Comment by mmaietta** [comment]
Are you intending to debug the packaged application? In which case, I thought that'd be 
```
./dist/dokopos/linux-unpacked/dokopos --inspect=9229
```
IIRC, running with `electron` executable expects the file path to be a JS entry point, which is why you're receiving `Unexpected token`

**Comment by mmaietta** [comment]
Can you try using `--inspect-brk=9229` to attach to the main process before it executes any code? From there, you should find what it's erroring on
