### ISSUE TITLE
App icon in `.dmg` at some sizes incorrect

### ISSUE THREAD

**Issue by ivanmaeder** [electron-userland/electron-builder#863]
* **Version**: 7.15.2

* **Target**: macOS

Really strange issue, I can't find any help anywhere or references to the same issue.

The build is fine, except in the generated `.dmg`, in the window that shows the app icon and the icon to the applications folder, the app icon is shown with the default Atom icon... but only at certain sizes!

When you open the `.dmg` the app icon is shown with the Atom icon, but using the slider to resize the icons, at the smallest size the correct icon is shown, and at larger sizes. Here are some screenshots:

![screen shot 2016-10-31 at 14 35 57](https://cloud.githubusercontent.com/assets/1976478/19857909/5ebe5d90-9f77-11e6-863e-af5468ff96d4.png)

![screen shot 2016-10-31 at 14 35 59](https://cloud.githubusercontent.com/assets/1976478/19857925/640be8ee-9f77-11e6-83ad-8b16a646a949.png)

![screen shot 2016-10-31 at 14 36 04](https://cloud.githubusercontent.com/assets/1976478/19857928/6739cca2-9f77-11e6-891f-f7a73e7a0b4e.png)

The icons are generated by creating an `.iconset` dir and then using `iconutil`.

I've checked the original `.png` files again and again and these are the details:

Filename             |Size     |px/inch
---------------------|--------:|------:|
icon_16x16.png       |16x16    |72     |
icon_16x16@2x.png    |32x32    |72     |
icon_32x32.png       |32x32    |72     |
icon_32x32@2x.png    |64x64    |72     |
icon_128x128.png     |128x128  |72     |
icon_128x128@2x.png  |256x256  |72     |
icon_256x256.png     |256x256  |72     |
icon_256x256@2x.png  |512x512  |72     |
icon_512x512.png     |512x512  |72     |
icon_512x512@2x.png  |1024x1024|72     |

The actual `.app` that is generated in the `dist/` folder has the correct icon. Changing the zoom in Finder to see different sizes of this icon is fine (the correct icon is shown in all sizes).

I tried the same with the `.app` extracted from the `.dmg` and the default Mac app icon is showing at larger sizes, with the Atom icon showing at smaller sizes:

<img width="348" alt="screen shot 2016-10-31 at 14 47 20" src="https://cloud.githubusercontent.com/assets/1976478/19858367/10e1295c-9f79-11e6-99a6-3e0e539d895d.png">

<img width="406" alt="screen shot 2016-10-31 at 14 47 31" src="https://cloud.githubusercontent.com/assets/1976478/19858369/12b1e3a2-9f79-11e6-9c47-34a461661724.png">

Launchpad shows the default Atom icon.

I'm running El Capitan 10.11.6 (15G1004).

I'm running the build with `npm run dist` and this is the part from `package.json` where the build is configured:

```
{
  "scripts": {
    "dist": "rimraf ./dist && build"
  },
  "devDependencies": {
    "electron": "^1.4.3",
    "electron-builder": "^7.15.2",
    "rimraf": "^2.5.4"
  },
  "build": {
    "appId": "com.website.bolt",
    "extraFiles": "tools",
    "mac": {
    }
  }
}
```

Just to be sure the `mac` section is being used I added a `background` entry and it was used (I tried just as a test to set the `iconSize` field to 16 but no change was visible).

Any ideas of what I could try? Thanks!

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/840#issuecomment-255619704 Does it help?

**Comment by ivanmaeder** [comment]
Thanks @develar. Yes, that fixed part of the issue. The app icon inside the "installation" window (where the app icon is shown with the arrow pointing to the `Applications/` folder) is now correct. Cool :)

But after dragging the app into the `Applications/` folder, the icon shown there is the default macOS app icon.

Any other ideas?

**Comment by develar** [comment]
> Any other ideas?

It is macOS cache issues. Production is not affected. 

Duplicates #840

**Comment by ivanmaeder** [comment]
OK good to know. I tried it on someone's computer that was new to the app and it all worked. Thanks!
