### ISSUE TITLE
Honor `AppUpdater.autoRunAppAfterInstall` in macOS?

### ISSUE THREAD

**Issue by toddsouthenbentley** [electron-userland/electron-builder#8630]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: v20.16.0

* **Electron Version**:29.1.0
* **Electron Type (current, beta, nightly)**: current

* **Electrong Updater**: 6.3.9

* **Target**: macOS

We don't want our app to relaunch after updating (as the app requires command line args). Currently we have patched MacUpdater.ts to honor the `autoRunAppAfterInstall` option with the following code changes:

```ts
  private handleUpdateDownloaded() {
    if (this.autoRunAppAfterInstall) this.nativeUpdater.quitAndInstall()
    else this.app.quit()
    this.closeServerIfExists()
  }

  quitAndInstall(): void {
    if (this.squirrelDownloadedUpdate) {
      // update already fetched by Squirrel, it's ready to install
      this.handleUpdateDownloaded()
    } else {
      // Quit and install as soon as Squirrel get the update
      this.nativeUpdater.on("update-downloaded", () => this.handleUpdateDownloaded())

      if (!this.autoInstallOnAppQuit) {
        /**
         * If this was not `true` previously then MacUpdater.doDownloadUpdate()
         * would not actually initiate the downloading by electron's autoUpdater
         */
        this.nativeUpdater.checkForUpdates()
      }
    }
  }
```

**Comment by mmaietta** [comment]
Thanks for the patch code @toddsouthenbentley! Looks like the code docs weren't updated when auto-install+relaunch were implemented for linux. Opened a PR with your code changes so that mac updater can leverage similar logic flow.

**Comment by toddsouthenbentley** [comment]
Excellent, thank-you for the quick response and PR creation!
