### ISSUE TITLE
Machine-wide NSIS installer launches application as administrator

### ISSUE THREAD

**Issue by bontibon** [electron-userland/electron-builder#864]
* **Version**: 7.14.2

* **Target**: Windows

With a machine-wide NSIS installer (a UAC dialog popped when launching), having the "Run $application" checkbox checked, my application runs with administrative privileges; I expected my application to be run with non-elevated privileges.

**Comment by develar** [comment]
We do use `UAC_AsUser_ExecShell` https://github.com/electron-userland/electron-builder/blob/master/templates/nsis/boringInstaller.nsh#L9 and it still doesn't help? Oh, *** Windows :(

**Comment by bontibon** [comment]
Correct, installer is still run as admin. I noticed this when launching an executable with `shell.openItem`, expecting to see a UAC dialog, but I did not.

Here are screenshots from procexp:

**Launching application normally from desktop shortcut**
![regular](https://cloud.githubusercontent.com/assets/110883/19866915/d74687ac-9f80-11e6-8094-5364aec62050.jpg)

**Launching application at end of installer**
![installer](https://cloud.githubusercontent.com/assets/110883/19866939/f6089c48-9f80-11e6-8f10-ecbcd27c117d.jpg)

**Comment by bontibon** [comment]
From the [NSIS UAC page](http://nsis.sourceforge.net/UAC_plug-in), I see the following line in the code example:

    RequestExecutionLevel user ; << Required, you cannot use admin!

Perhaps the electron-builder NSIS template is incorrectly requesting administrative privileges via `RequestExecutionLevel`?

**Comment by develar** [comment]
No. one click machine wide installer must use admin because it is one click, not boring installer. I will investigate issue.

**Comment by develar** [comment]
Reproduced (to reproduce, your account should be not administrator).

**Comment by develar** [comment]
Fixed — StdUtils.ExecShellAsUser must be used. https://github.com/lordmulder/stdutils

**Comment by develar** [comment]
Thanks for spotting it and clear report.

**Comment by bontibon** [comment]
I just upgraded to 7.18.1, re-built my installer, and I am experiencing the same issue.

**Comment by bontibon** [comment]
My NSIS configuration:
```javascript
"nsis": {
    "oneClick": false,
    "perMachine": true,
    "guid": "939693fe-aa4b-4da5-b1de-34700e4f1c83"
}
```

**Comment by develar** [comment]
I created test user without admin rights and tested — works for me (win 10). Ok — will try to test it again.

**Comment by develar** [comment]
Ouch, ` "oneClick": false,` — boring installer, not one-click?

**Comment by bontibon** [comment]
> boring installer, not one-click?

Correct.

**Comment by develar** [comment]
Every user of NSIS boring installer should upgrade to next electron-builder version as soon as possible.

**Comment by anran800** [comment]
I  include file 'installer.nsh' .test successful
!macro customInstall
	StrCpy $appExe "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
	WriteRegStr HKCU "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$appExe" "RUNASADMIN"
!macroend

**Comment by DxCx** [comment]
@anran800 thanks for your solution, it helped 👍 
just one correction, you are missing '\', so it should be:
```nsis
!macro customInstall
StrCpy $appExe "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
WriteRegStr HKCU "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$appExe" "RUNASADMIN"
!macroend
```

**Comment by DxCx** [comment]
for uninstalling the rule when application uninstalls i used:
```nsis
!macro customUnInstall
DeleteRegValue HKCU "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
!macroend
```

**Comment by develar** [comment]
@anran800 Why do you need to do it, what's wrong? This issue was fixed.

**Comment by DxCx** [comment]
@develar what do you mean fixed?
This marks the installed exe as RunAsAdmin

**Comment by develar** [comment]
@DxCx So, please do not comment here, but create new issue and request feature :)

**Comment by DxCx** [comment]
that's not a new issue :)
i got here with google looking for solution and found halfworking one,
just wanted to share my experience with the others who will get here.

**Comment by develar** [comment]
@DxCx This issue about "installer by mistake runs installed app as admin" ;)

**Comment by DxCx** [comment]
then you are right @develar , my bad =) i was getting here searching the exact opposite 🤣
