### ISSUE TITLE
NSIS windows 10 desktop shortcut icon missing

### ISSUE THREAD

**Issue by embeddedemily** [electron-userland/electron-builder#865]
* **7.15.2**: 

* **Windows 10**: 

When using NSIS to create a windows single click installer it creates a desktop icon with a blank icon and that doesn't work, i.e. it points to nowhere and doesn't launch app when you click it. See image: 
![screen shot 2016-10-31 at 3 22 03 pm](https://cloud.githubusercontent.com/assets/6764718/19868317/e8dc65b6-9f7d-11e6-81fa-797094e7afdf.png)

![screen shot 2016-10-31 at 3 29 00 pm](https://cloud.githubusercontent.com/assets/6764718/19868518/c762d46e-9f7e-11e6-9821-3ed36713df1e.png)

I have sniffed around nsh scripts and don't see anything weird about desktop icon, and I should note that the start menu icon and shortcut works fine, it's only the desktop shortcut that has this issue. Tried running installer as admin too, same issues. Tried compatibility mode and that has the same issue too.

`"build": {
    "appId": "com.domain.application",
    "linux": [
      "AppImage",
      "deb",
      "rpm"
    ],
    "win": {
      "target": "nsis"
    }
  }`

**Comment by develar** [comment]
Please try to restart Windows.

**Comment by embeddedemily** [comment]
The issue persists after restart as well

**Comment by embeddedemily** [comment]
Were you able to reproduce the issue?

**Comment by develar** [comment]
@embeddedemily Not yet. My test apps work for me. If you can attach here your project / link to repo — it will help me to reproduce the issue.

**Comment by embeddedemily** [comment]
I can't do that unfortunately, since it's a private repo which I do not have rights to share. Let me investigate as well on my end. I'll try making brand new sample app and packaging it up and see what happens.

Another possible helpful detail: I don't use the two package.json build system I only have one json file. Maybe that makes a difference

**Comment by develar** [comment]
Could you please try run your installer on another machine?

> since it's a private repo which I do not have rights to share

Is it possible to send me only installer?

**Comment by embeddedemily** [comment]
I tested installer on two other windows 7 machines and both had same issue where icon would appear on desktop with right app name but wrong icon and the link path would be blank. I might be able to give installer (I believe we're still in discussion as to whether installer for our app will be freely available for download online. But I'd rather try and work it out without at first.

I made brand new electron app, simply cloned electron-quick-start repo, added electron builder as follows:

`
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^1.4.1",
    "electron-builder": "^7.14.1"
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "com.redpillanalytics.checkmate",
    "linux": [
      "AppImage"
    ],
    "win": {
      "target": "nsis"
    }
  }
}
`

And ran "nom run list" on my windows 10 virtual machine and got the following:

![screen shot 2016-11-02 at 4 19 13 pm](https://cloud.githubusercontent.com/assets/6764718/19945820/2fc92fea-a118-11e6-906f-514e6219c2f2.png)

![screen shot 2016-11-02 at 4 19 28 pm](https://cloud.githubusercontent.com/assets/6764718/19945832/40700490-a118-11e6-9296-a9dece845459.png)

It appears as though it is at least linking  and putting icon in this instance but it's still the wrong icon and appears to link the folder from which I ran the installer rather than the folder where it installed to on the local machine: C:\Users\Emily\AppData\Local\Programs\electron-quick-start

But again on windows machine start menu shortcut it perfect.

**Comment by embeddedemily** [comment]
@develar I suspect the issue is target path based and not truly with the icon. That is to say the reason I got a blank white icon in my first case was because the target path was completely blank. Yet with the last case for simple test case I do get a folder icon which would be appropriate considering it's pointing to a folder. But the question becomes why is it pointing to a folder and not the install path and subsequently the executable. Because my guess would be once target path is present icon will display properly.

**Comment by develar** [comment]
Relates #864

**Comment by develar** [comment]
Ouch. If you use Parallels, you must not use "Share Mac user folders with Windows" feature and must not run installers from such folders. I am also macOS user and Parallels user and aware about this problem. I didn't report about it to Parallels, if you want – please report (but I guess it is Windows bug).

You should or use feature "Open in Windows"
<img width="1370" alt="screen shot 2016-11-03 at 11 14 33" src="https://cloud.githubusercontent.com/assets/350686/19962168/bb2480b4-a1b6-11e6-90ad-245f21519575.png">

or copy installer to windows machine.

**Comment by embeddedemily** [comment]
@develar worked like a charm when I disabled that feature! thanks a ton for your help!

**Comment by develar** [comment]
@embeddedemily Yep. Thanks for confirmation. I didn't report to Parallels since this feature is nightmare in any case and should be disabled in any case. Maybe this feature is ok for dummy home users, but for developers it is no-no.

**Comment by gtkpr** [comment]
@emilyplusplus what option to i use to change the desktop shortcut icon for `electron-builder`?? thanks

**Comment by jackHom** [comment]
I've focused this problem for a few days."nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": "always",
      "createStartMenuShortcut": true,
      "perMachine": true
