### ISSUE TITLE
Question: Best way to have different package.json data for different build targets?

### ISSUE THREAD

**Issue by screenmeet** [electron-userland/electron-builder#866]
Can anyone recommend the best way to change some values in a package.json (or have different version of it) for different build variants?

I know it's possible to have a dev vs. production setup via the application directory, but that doesn't really cut it for my case... I'd like to be able to change some config vars for different build flavors, or maybe somehow include an auxiliary config file different build types.

Just wondering if I'd be re-inventing wheels here before I start going the programmatic afterPack API route...

**Comment by develar** [comment]
Duplicates #639
