### ISSUE TITLE
Use of extraResources prevents node_modules from being included in asar

### ISSUE THREAD

**Issue by gerges** [electron-userland/electron-builder#867]
* **Version**: 7.14.1

* **Target**: OSX

When using the `extraResources` JSON object option, the node_modules is never included in the asar. This issue is caused by a change recently made to `filter.ts` (the inclusion of `stat.isDirectory()` in the following line)

```
match = pattern.match(path, stat.isDirectory() && !pattern.negate)
```

The `extraResources` results in a `excludePatterns` array being built up, which eventually is used to filter files (incorrectly) in the following line `createFilter` (`filter.ts` )

```
return minimatchAll(relative, patterns, stat) && (excludePatterns == null || !minimatchAll(relative, excludePatterns, stat))
```
I believe Instead of using `!minimatchAll` (which is triggering the `stat.isDirectory()` case) this issue could be resolved by creating the `excludePatterns` as negated globs (instead of negating the result of attempting to filter)

**Comment by develar** [comment]
Could you please provide example of such `extraResources` to easy reproduce?

**Comment by gerges** [comment]
Sure

```
    "extraResources": [
      {
        "from": "node_modules/spellchecker/vendor",
        "to": "app.asar.unpacked/node_modules/spellchecker/vendor",
        "filter": "**/*"
      }
    ],
```

**Comment by L0L3k** [comment]
Hi Another example when trying to use [xsd-schema-validator](https://www.npmjs.com/package/xsd-schema-validator) with electron-builder:
```
  "build": {
    "extraResources": [
      "node_modules/xsd-schema-validator/support/XMLValidator.{class,java}"
    ],
    "asarUnpack": [
      "node_modules/xsd-schema-validator/support/XMLValidator.{class,java}"
    ]
  }
```
After deploying app.asar is missing or does not include all the node_modules - only electron.asar is included.

Is there any workaround?

**Comment by farfromrefug** [comment]
I have the exact same issue. I use ```extraResources``` for ```node_modules``` so that i can filter what is copied.
But when ```asar``` is set to ```true```, ```node_modules``` is not inside the asar file, it's present as an unpacked file.
