### ISSUE TITLE
Use project environment tsconfig for reading electron-builder.ts config file

### ISSUE THREAD

**Issue by tom2strobl** [electron-userland/electron-builder#8681]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 20.17

* **Electron Version**: 32.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: doesn't matter

In our full-ESM project (both main thread, renderer and tooling) in `electron-builder.ts`, when using `import.meta` like eg so:
```typescript
const desktopPath = join(import.meta.dirname, 'desktop')
```

we run into:
```bash
tsc: (/Users/thomas/dev/fugoya/desktop/tooling/scripts/electron-builder.ts:10:26): The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.
```

Our `tsconfig.json` already has
```json
{
    "lib": ["DOM", "ESNext"],
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
}
```

For typescript config resolution you seem to use https://www.npmjs.com/package/read-config-file which in return seems to use https://www.npmjs.com/package/config-file-ts, which, if I'm not mistaken uses a hardcoded tsconfig (https://github.com/mighdoll/config-file-ts/blob/b72adf1a409327c93a7a0b2a4a44c811a333473a/src/compileUtil.ts#L72) and not the one of the userland project.

Which in our case means we can use `import.meta.dirname` in every .ts file except for electron-builder.ts, which will be confusing for new devs working in the project.

**Comment by tom2strobl** [comment]
Ah, I just realized that it's even worse – since the config read thingy does caching with fs writes into a `.cache` in the user directory, traversal with `__dirname` from the file is fucked anyway, resulting in paths like:

```bash
/Users/<me>/.cache/config-file-ts/Users-<me>-<long-ass-string>-electron-builder.ts/Users/<the actual path>
```

So I suppose `process.cwd()` to construct paths and enforcing from where to run commands is the way to go? Or do you all just write relative paths? I always find it confusing for new people that work on the project as nobody knows where these paths start from and the docs afaik don't really tell you either – is it the directory:
- the command was run from (which is even more confusing when using a monorepo like we do where you run commands from root but they are executed in a package dir)
- the electron-builder config is placed in
- the package.json main property indicates

We have a dual package.json system for native dependencies with asarUnpack, which makes it even trickier for new people to understand. Using something like `__dirname` to join paths makes it very straightforward to understand where paths are pointing to.

I don't really want to go back to a .js file because `import type { Configuration } from 'electron-builder'` is so nice.

**Comment by mmaietta** [comment]
So if I'm understanding correctly, the problem here lies within the dependency we're using `config-file-ts`. If so, I'm unable to change that logic on my own and it's fairly complex for me to just copy-paste into electron-builder

>I don't really want to go back to a .js file because import type { Configuration } from 'electron-builder' is so nice.

Re: this though. You can add this to your js file (similar to the [example on the docs site](https://www.electron.build/programmatic-usage))
```
/**
* @type {import('electron-builder').Configuration}
* @see https://www.electron.build/configuration
*/
const options = { .... }
```

**Comment by tom2strobl** [comment]
You're right in that it's mainly an issue in read-config-file and it's use of config-file-ts (and not _directly_ an issue in electron-builder, I just thought other people that might stumble into the same issue will not search for it in the 7 & 11 stars repos, but you're right it's likely better to post there).

I would have assumed there's an easier path in transpiling in memory rather than filesystem with something like https://github.com/unjs/jiti or a plain old ts-node register and then regular import, but maybe I'm simplifying thing's too much. I'll open up an issue there.

And thanks for the jsdoc tip. I still feel like if we have the option of .ts we should use it for consistency, so maybe process.cwd() with a manual check for the result and a helpful error message is just enough safety.

While I have you here reading this @mmaietta – thank you so much for all the hard work and effort you put into electron-builder. It doesn't go unnoticed and is so so so much appreciated! 🙂
