### ISSUE TITLE
Sponsorship options

### ISSUE THREAD

**Issue by pimterry** [electron-userland/electron-builder#8702]
Hi,

I'd like to sponsor electron builder (on behalf of https://github.com/httptoolkit) but the current options (https://www.electron.build/donate) are pretty niche and inconvenient.

Would you be open to enabling GitHub Sponsors, or using Open Collective? I already sponsor lots of projects on both so that's much more convenient. If you use GitHub, I think you'd also get sponsored by everybody using https://github.com/sponsors/explore to auto-sponsor their dependencies, since I suspect this package is pretty widely used in lots of places.

**Comment by pimterry** [comment]
@beyondkmp @mmaietta I'd like to sponsor your team and help fund Electron Builder! I suspect lots of more people would do this if it were easier. Any thoughts on the above to make that happen?

**Comment by mmaietta** [comment]
Thanks for reaching out! I'll look into how we can support an official sponsor/donation setup through Github. Hopefully I have the right admin permissions to do so for electron-builder, not sure if it needs to be applied to the full electron-userland project (which I don't have full control of)

**Comment by mmaietta** [comment]
Updated @pimterry !
