### ISSUE TITLE
Documentation/Website broken?

### ISSUE THREAD

**Issue by mschoeffmann** [electron-userland/electron-builder#8750]
* **Electron-Builder Version**: -

* **Node Version**: -

* **Electron Version**: -
* **Electron Type (current, beta, nightly)**: -

* **Target**: -

It looks like the current build of the website is missing some parts of the documentation?
For example: https://www.electron.build/auto-update#updateinfo used to have more content below the "UpdateInfo" header. Like on 8th of December: https://web.archive.org/web/20241208222033/https://www.electron.build/auto-update#updateinfo
Also here: https://www.electron.build/win#configuration ...

**Comment by mmaietta** [comment]
Wow, thank you for bringing this to my attention. I'm quite confused since locally all the assets are rendered properly when building the site. Not sure what changed but I'll investigate this ASAP

**Comment by mmaietta** [comment]
Alright, site is live with a previous `next` version of electron-builder `alpha.7`. It seems an error popped up loading the plugin in the latest deploy and only on the GH build machine, can't repro locally
```
[error] The plugin typedoc-plugin-markdown could not be loaded
[error] TypeError: Cannot read properties of undefined (reading 'addOutput')
```

I'll continue to debug, but the site is back up at least. Thanks for notifying me
