### ISSUE TITLE
`productName` isn't being respected on Linux

### ISSUE THREAD

**Issue by matheuss** [electron-userland/electron-builder#877]
* **Version**: `7.21.0 `

* **Target**: `deb`/`AppImage`

`package.sjon`
```
...
"build": {
  ...
  "linux": {
    "arch": [
      "ia32",
      "x64"
    ],
    "target": [
      "deb",
      "AppImage"
    ]
  }
  ...
}
...
```

`app/package.json`
```
...
"name": "hyper",
"productName": "Hyper",
...
```

### Expected behavior

As per [the docs], after running `build`, `dist/linux-unpacked/Hyper` should be present.

### Actual behavior

After running `build`, `dist/linux-unpacked/hyper` is present – instead of `Hyper`.

I believe this regression was introduced [here] 😕 

[the docs]: https://github.com/electron-userland/electron-builder/wiki/Options#application-packagejson
[here]: https://github.com/electron-userland/electron-builder/commit/c3136adeeb837bf46e4fea201ed36b5938d93b4f#diff-58b7f704c3bb687133ff104a6622bfb2R73

**Comment by develar** [comment]
Why hyper is not suitable for you?

**Comment by develar** [comment]
* you can set `linux.executableName` explicitly if need.
* previously `name` was used as executable for AppImage in any case

Please explain why `hyper` is not suitable for you.

**Comment by matheuss** [comment]
@develar https://github.com/zeit/hyper/blob/master/test/index.js#L15:

`pathToBinary = path.join(__dirname, '../dist/linux-unpacked/Hyper')`

**Comment by matheuss** [comment]
To be clear: `hyper` is not suitable because the name of the app is `Hyper` 😅

**Comment by develar** [comment]
Please set `linux.executableName` to `Hyper` if it is important for you in case. Please note — user will run your app using desktop files (i.e by product name) or by AppImage file. executable name only for terminal.

**Comment by develar** [comment]
> but my concern is the inconsistency between the 3 platforms – it was consistent before 

1. AppImage since begging use name, but not productName for executable (because space in the executable causes (mostly fixed now, but anyway) weird issues).
2. You cannot modify macOs executable name after sign — weird things will happen. So, it is better to use `name` on macOs also. But we cannot change due to backward compatibility (you must not change executable name once signed app is delivered to customers).

So... I don't think it is inconsistent. We build app according to platform/target conventions, not according to some unified and artificial standard.

**Comment by cardoe** [comment]
While I got tripped up on this issue locally. I agree with the change overall. I do wish it wasn't shipped as a semver compat change since there was a change to the end user effectively. However it is more natural on Linux for the binary name to be lower case so overall the change is better.

**Comment by develar** [comment]
@cardoe Yes, sorry that it was not major upgrade.
