### ISSUE TITLE
disable "unpack execuatable"

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#879]
I have a module contains executable binary files, but they never execute them directly, only copy them to outside directory via `fs`. It works in asar packages.

Is there any way to say don't unpack these module, just put them into asar package?

**Comment by develar** [comment]
> Is there any way to say don't unpack these module, just put them into asar package?

No. In general, it is ok — doesn't affect performance. Does it lead to runtime error?

**Comment by zh99998** [comment]
no, just lead to uncomfortable

**Comment by develar** [comment]
If it doesn't lead to any runtime error and conditional statements in the code, then I am going to close won't fix. Don't you mind?

**Comment by develar** [comment]
Log level changed from info to debug.
