### ISSUE TITLE
should set --abi on `npm rebuild` to make `prebuild` work properly

### ISSUE THREAD

**Issue by mmckegg** [electron-userland/electron-builder#882]
* **Version**: 7.21.0

* **Target**: All

I am building an electron app that uses native dependencies targeting multiple platforms. [Prebuild](https://github.com/mafintosh/prebuild) binaries are available for all of them. 

However when `npmSkipBuildFromSource` is enabled, `prebuild` downloads the binary for the installed node version instead of the electron version. This can be easily handled by specifying a `--abi=ELECTRON_ABI_VERSION` argument, but electron-builder does not allow this.

#881 is a quick workaround to solve this, but as discussed with @develar, it would make sense for electron-builder to just set `--abi=$(electron --abi)` automatically.

**Comment by mmckegg** [comment]
@develar I'm happy to do a PR for this, just not right now, since #881 solves this for me. Might look again in a few weeks if no one else has taken it on.

**Comment by lgeiger** [comment]
Since `prebuild v5.0.0+` it can prebuilt native modules against Electron headers and determines the ABI based on the `--target` and `--runtime` flags. 

This makes it compatible with `electron-builder`. So this issue can be closed.
