### ISSUE TITLE
option to delete app data on manual uninstall

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-builder#885]
https://github.com/electron-userland/electron-builder/issues/528#issuecomment-258673100

**Comment by develar** [comment]
`nsis.deleteAppDataOnUninstall` is added.

**Comment by arthur791004** [comment]
Hi,

I set deleteAppDataOnUninstall to true, but the directory, "<AppData>/roaming/<AppName>", does not be deleted.

How can I deal with it?

Thanks.

**Comment by develar** [comment]
@arthur791004 Please specify app name (`name` and `productName` if set), `appId` if specified. And current full path to directory that is not deleted on uninstall.

**Comment by arthur791004** [comment]
@develar 

The current full path is:
C:\Users\\<user name\>\AppData\Roaming\\<APP_FILENAME\>

Thanks.
