### ISSUE TITLE
Uninstaller not signed ?

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#886]
* **Version**: 7.23.2

* **Target**: win with target nsis

It seems that the uninstaller is not signed. When I want to uninstall my app on Windows 10, I get a popup that tell me that this "Uninstaller" is not sure..

popup:
![detail](https://cloud.githubusercontent.com/assets/3807312/20041680/290c1642-a46d-11e6-8b71-94c35d41efbc.jpg)

**Comment by joshualambert** [comment]
Can confirm I've seen this also on Windows when testing Electron NSIS builds over there.

**Comment by develar** [comment]
Cannot reproduce. We sign uninstaller. Please check Properties -> Digital Signatures.

<img width="444" alt="screen shot 2016-11-12 at 18 24 31" src="https://cloud.githubusercontent.com/assets/350686/20239650/492107e8-a905-11e6-8dcb-871bad2a8912.png">

<img width="514" alt="screen shot 2016-11-12 at 18 25 33" src="https://cloud.githubusercontent.com/assets/350686/20239656/6e88f220-a905-11e6-9eea-2ac18fde5fd7.png">

**Comment by popod** [comment]
I've juste test with a clean installer of my app (new app installer create with electron-builder) and it works now.. Don't know why ;)

Thanks and sorry for "fake" issue

**Comment by khurana3192** [comment]
Its happening for me though, I have signed the generated .exe file...still upon its install from windows control panel, I get an error that this file is from an unpublished developer

**Comment by develar** [comment]
@khurana3192 Please properties of the uninstaller file. Is it signed (as on my schreenshot)?
