### ISSUE TITLE
'will-finish-launching' event not fired on first launch ?

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#887]
* **Version**: 7.23.2

* **Target**: windows 10 with nsis target

Seems that "will-finish-launching" event will not always been fired on Windows. I do a simple init on this event and it is not always executing..

I don't know what is exactly the problem.

I found that on Windows 10, the first time I start my app (after install it from nsis .exe built with electron-builder) my functions that are in "will-finish-launching" are not called.

If I move them on the "ready" event, this works..

**Comment by popod** [comment]
electron/electron#7879

**Comment by develar** [comment]
electron-builder doesn't affect this aspect of Electron app, please file issue to Electron.

**Comment by popod** [comment]
electron/electron#7879
