### ISSUE TITLE
Cannot use NSIS StrFunc header

### ISSUE THREAD

**Issue by bontibon** [electron-userland/electron-builder#888]
* **Version**: 7.19.1

* **Target**: NSIS Windows x86

I am trying to use the `${StrTok}` function from `StrFunc.nsh`. In order to use the function, I need to call it with no arguments. I am trying to do that at the beginning of my `installer.nsh` file:

```nsis
!include "StrFunc.nsh"

!ifndef BUILD_UNINSTALLER
  ${StrTok}
!endif
```

However, the NSIS build fails with the following error:

```text
Processing script file: "<stdin>" (ACP)
Error: Can't change target charset after data already got compressed or header already changed!
!include: error in script: "common.nsh" on line 11
Error in script "<stdin>" on line 3 -- aborting creation process
```

**Comment by develar** [comment]
Please ensure that`!include "common.nsh"` is the first line in your `installer.nsh`

**Comment by develar** [comment]
Why do you need custom installer?

**Comment by bontibon** [comment]
I do not have a custom NSIS **script**, but I do have an **include**. From what I understand, I do not need to `!include "common.nsh"` from an include.

**Comment by bontibon** [comment]
@develar Thanks for the quick fix!
