### ISSUE TITLE
NSIS Auto Update: Bintray Auth

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#891]
* **Version**: 7.15.12

electron-auto-updater@0.3.1

* **Target**: Windows 7

Thank you so much for all of the recent work on the NSIS Installer / Auto Update flow. I'm able to successfully build and install my Electron app with Windows 7 as the target platform but had a question regarding authentication during the auto-update process.

It seems that during build, if the `BT_TOKEN` env var is set, publishes work against my private Bintray Organization. This is the relevant portion of my package.json:

```
"build": {
    "app-bundle-id": "fk.fk.fk",
    "app-category-type": "fk.fk.fk",
    "iconUrl": "http://someurl.ico",
    "publish": {
      "provider": "bintray",
      "repo": "my-private-repo",
      "user": "nader@org",
      "package": "my-private-package",
      "owner": "nader"
    },
    "mac": {},
    "win": {
      "target": "nsis",
      "publish": {
        "provider": "bintray",
        "repo": "my-private-repo",
        "user": "nader@org",
        "package": "my-private-package",
        "owner": "nader"
      }
    }
  },
  "directories": {
    "app": "electron",
    "output": "release"
  }
```

However, when the auto-update module attempts to check for updates I see the following error:

`Error: No latest version, please ensure that user, package and repository correctly configured. Or at least one version is published. ..... Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404`

Am I missing something that would allow the auto updater to make authenticated requests to Bintray or is that not supported at this time?

Thanks so much for your help, please let me know if there is any more information I can provide.

**Comment by develar** [comment]
Auto updater cannot access private resources because no way to provide access token — app resources is visible for anyone. So, your bintray repo must be public.

**Comment by naderhen** [comment]
Ok, definitely good to know! I was thinking maybe providing the `token` in the package.json would add it to app-update.yml which would allow the updater client to make authenticated requests.

I will look into our options given your response, thanks again!

**Comment by develar** [comment]
> maybe providing the token in the package.json would add it to app-update.yml which would allow the updater client to make authenticated requests

But in this case anyone can use this token to access your private repo :)

**Comment by naderhen** [comment]
Haha yes, I was mostly testing that just to see if it would work at all. Is there any avenue to hiding our resources behind some kind of auth?

**Comment by develar** [comment]
> Is there any avenue to hiding our resources behind some kind of auth?

Why do you need to hide public accessible artefacts? Maybe you can make public only one repo?

**Comment by naderhen** [comment]
I'm mostly wondering from a business requirement perspective. Our
application will have multiple channels that we would like to auto-update
within. I noticed the Generic Provider has the concept of channels, but no
auth either. Hypothetically if we wanted to restrict the auto-update
functionality to authenticated users, i'm curious how it could be done. It
doesn't seem possible out of the box with Bintray, but maybe with the
Generic Provider as that has a more flexible api

**Comment by develar** [comment]
Please see https://www.jfrog.com/article/private-repositories/ and https://www.jfrog.com/article/access-keys-and-entitlements/ I didn't read it completely, but it seems it is what you want.

> Generic Provider as that has a more flexible api

Major drawback — you need to maintain own server and own API. If you already pay *** 150$ per month — Bintray is ok for your needs.

I will check.

> Hypothetically if we wanted to restrict the auto-update
functionality to authenticated users

Do you want to provide some token to users? i.e. user can configure access to some channel using some credentials?

**Comment by naderhen** [comment]
Thanks! I will read into those and maybe speak with our rep at JFrog.

Maybe if we started checking for updates after a user has completed some
action (i.e. logging in), we could then add some session token to the
request which our server would use to identify them. This would allow for
things like holding some group of users to one version, or managing the
update versions via feature flags etc.. I'm open to discuss further or test
out any ideas you may have on the subject.
