### ISSUE TITLE
Signing Mac app in development, getting spctl rejected error

### ISSUE THREAD

**Issue by rahilsondhi** [electron-userland/electron-builder#892]
* **Version**: `electron 1.4.3 `

* **Target**: `Packaging for platform darwin x64 using electron 1.4.3 to dist/mac`

I generated a self-signed certificate for development purposes by following the instructions [here](https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos) under `To obtain a self-signed certificate using Certificate Assistant`. In keychain, I `right clicked on the certificate > Get Info > When using this certificate > Always trust`.

Then I did `export CSC_NAME="My Signing Certificate"` and ran `npm run dist` and got this error:

```
Signing app (identity: My Signing Certificate)

Error: Exit code: 3. Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/rahilsondhi/Sites/p*** rejected

/Users/rahilsondhi/Sites/my_app/dist/mac/MyApp.app: rejected
```

Any ideas? I tried following the [Code Signing](https://github.com/electron-userland/electron-builder/wiki/Code-Signing#how-to-export-certificate-on-macos) guide, but it seems that's just for production. I just want to self sign my app for development purposes.

**Comment by develar** [comment]
Duplicates #890
