### ISSUE TITLE
Add option to wrap AppImage in tarball

### ISSUE THREAD

**Issue by MaKleSoft** [electron-userland/electron-builder#893]
It would be nice if we could configure electron-builder to automatically pack any `AppImage` releases in a tarball. This has two advantages:

1. Users don't have to manually make `.AppImage` file executable. Instead they can simply run it after extracting it from the tarball.

2. The archived `.AppImage` file could have a more user-friendly name like `productName` instead of `{name}-{version}-{arch}` while the tarball file name could still contain all the relevant information to identify a release.

E.g. you could distribute a `my-app-1.0.0-linux-x64.tar` that, when extracted, produces `MyApp.AppImage` that can be run without any additional steps. Essentially this would be analog to distributing `.app` folders as `.zip` archives on OSX.

**Comment by develar** [comment]
@probonopd If you don't mind :)

**Comment by jbleuzen** [comment]
I'm interested on this too but we did this manually and if I remember correctly @probonopd send us a message on Twitter telling us not to do that...

If he changes his mind, that would be cool feature just for the right problem !

**Comment by develar** [comment]
Our official position is — to not teach users. But issue in the TBD state anyway.

>  file could have a more user-friendly name like productName instead of {name}-{version}-{arch}

https://github.com/electron-userland/electron-builder/issues/775

**Comment by develar** [comment]
> extracting it from the tarball

On Linux `xz` is available in most cases, so, app can be compressed using efficient `lzma` (AppImage uses zip — compression ratio is not good). So, wrapping into `tar.xz` makes sense to reduce download size.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/504#issuecomment-231013103

**Comment by probonopd** [comment]
While you certainly can do what you like with AppImage (after all, that is what it is made for), I ask you to _please_ **NOT** put an AppImage into another archive like a .zip or .tar.gz. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, signature verification of the embedded signatures, and a lot of upcoming AppImage features that depend on the AppImage not being wrapped in yet another archive.

Besides, the beauty of the AppImage format is that you never need to unpack anything. It is a central element of the AppImage user experience.

The AppImage itself is the archive. Never AppImages can even be extracted with the `--appimage-extract` option.

**Comment by develar** [comment]
@probonopd Why "this breaks desktop integration" if after unpack it will be the same AppImage?

**Comment by MaKleSoft** [comment]
@probonopd While I value your opinion high above my own (I don't claim to have any significant experience in this matter) and will definitely follow your advice, I am worried that the whole set-permission-before run thing will confuse a lot of users. I don't know about the current demographic of Linux users but I imagine that with distros like Ubuntu becoming more 'mainstream', there are more and more Linux users who don't know much about apps beyond 'double-click to run'. Well, I guess I'll simply start by distributing plain `.AppImage` files and see what feedback I get from users.

**Comment by probonopd** [comment]
@MaKleSoft thanks for your valuable feedback. I will think about what we can do to make this even easier. In the meantime, feel free to use/copy/link to this: http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80

**Comment by probonopd** [comment]
> Why "this breaks desktop integration" if after unpack it will be the same AppImage?

`appimaged` and `appimagetool` cannot operate on AppImages inside archives. `appimaged` would not be able to make a download executable, install it in the menu, install icons and mime types unelss you would manually unpack it, which would add an unnecessary step. `appimagetool` could not change update information in case you need it without having to unpack each AppImage. So it would add significant overhead on all sides and make the overall experience much more clumsy. After all, why even bother with AppImage anyway if you are OK with extracting an archive?

**Comment by develar** [comment]
When here will be >10 angry app developers with stats — decision will be reconsidered.

**Comment by develar** [comment]
Also, electron-builder should support auto-update for AppImage to reduce manual "download, make executable".

**Comment by probonopd** [comment]
That would be relatively easy to do: Put AppImageUpdate inside the AppImage at `./usr/bin`, and have the app call `AppImageUpdate $APPIMAGE`. Voilá, the AppImage will update itself (if [update information](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information) is present).

**Comment by jayarjo** [comment]
Setting exec permission is not obvious at all, especially fro those not familiar with AppImage (there are many). So it requires to have a special warning message for Linux platform only - for users to do that operation, but still - no one pays attention to those warnings and then they fill our QA with endless lament about not being able to launch AppImage.

> When here will be >10 angry app developers with usage stats — decision will be reconsidered.

How many are there already @develar?

Electron Builder bundles it's own system integration script with the every AppImage now, so `appimaged` and `appimagetool` reasoning is not actual anymore I think. Also unpacking the download is much more natural and intuitive for a random user, then going to properties and setting execution permission.

I think the option to wrap the AppImage into a tarball (gzipped or not) should be there for us.

**Comment by develar** [comment]
> How many are there already @develar?

As you can see, this issue has 3 👍 and 1 👎 

Don't get me wrong — I also think that we should probably provide packed AppImage, or at least provide an option, but... as we in touch with AppImage team and this team is not MS, well... I don't want to conflict.

**Comment by jayarjo** [comment]
I'm pretty sure everybody does it anyway ('cause it is a logical thing to do), it's just that at the moment we manually hook up a wrapper onto `afterAllArtifactBuild`.

**Comment by probonopd** [comment]
@jayarjo please __DO NOT__ put AppImages into other archives. This is a common mistake made by beginners. In fact so common that we have an entire wiki section on it:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by jayarjo** [comment]
@probonopd I've read that and I still do not get it. Is it still broken for `appimaged` after it gets unpacked? I've asked literally everybody around me - whether they would prefer to unpack the `tar` and launch the thing right away, or go to properties and set exec permission. Apart from those who didn't even understand the idea behind the second option, everybody chose the first one. After all, for the mac platform the app is distributed in `zip` archive, so unpacking the thing before installation is a natural operation to many.

**Comment by probonopd** [comment]
Imagine the AppImage is 2GB in size. Unpacking wastes time and is an two extra manual step because unlike on the Mac with Safari, Linux OSes don't automatically unpack the zip files, and then delete the zip. Binary delta updates entirely break.

**Comment by jayarjo** [comment]
I can see why it might be bad for 2GB apps. But mine is 80MB or so. Also I still publish an AppImage (for auto update, etc), I just provide a tar for the first download. 'cause automatic or not, unpacking is still a way more familiar action for regular users, than changing a permission. Even advanced users get confused initially.

**Comment by probonopd** [comment]
Publishing both is an option of course.
