### ISSUE TITLE
NSIS installer "CHECK_APP_RUNNING" breaks if installer has same executable file name as app 

### ISSUE THREAD

**Issue by lishid** [electron-userland/electron-builder#894]
* **Version**: 7.24.1

* **Target**: Windows NSIS

Observed behavior:
- User downloads installer
- User renames installer from "Appname Setup 1.0.0.exe" to "Appname.exe"
- User runs installer
- Installer prompts "Appname is running. Click OK to close it..."
- User clicks OK
- Installer disappears (process is killed), user confused.

Code reference: https://github.com/electron-userland/electron-builder/blob/master/templates/nsis/allowOnlyOneInstallerInstance.nsh#L26

According to this CHECK_APP_RUNNING check, we're only looking for the process name. Is there any way we can exclude the current executable (the installer) from the check?

I understand that most users won't bother renaming the installer, but out of the few who does, that're totally confused why the app won't install. As a result, we get complaints from time to time from users who think we might have dropped support for their version of Windows, or if we don't support 32-bit or 64-bit version.

**Comment by develar** [comment]
For now if installer process name equals to `APP_EXECUTABLE_FILENAME`, we do not check if app is already running. Probably `pid` should be used, but for now it is implemented so.
