### ISSUE TITLE
mas app crashing after signing

### ISSUE THREAD

**Issue by workswithweb** [electron-userland/electron-builder#897]
* **pre release 8.2.0**
* **mas**
* **electron": "1.4.6"**

I was able to sign mas apps successfully with electron-builder 7.14.2 and publish on mac store. however after updating to 7.24.1, I started getting errors "Error: Exit code: 3. Command failed: spctl --assess --type execute --verbose --ignore-cache " which was fixed with [issue#890](https://github.com/electron-userland/electron-builder/issues/890) in 8.2.0 branch.

I updated electron-builder to pre-release branch 8.2.0 and when I build my app with gatekeeper-assess set to false, app is generated successfully however app crashes when we try to open. (attached is error screenshot) . 

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

If I generate app without specifying gatekeeper-assess flag, I get "Error: Exit code: 3. Command failed: spctl --assess" back mentioned in [issue#890](https://github.com/electron-userland/electron-builder/issues/890)
![screen shot 2016-11-11 at 5 10 20 am](https://cloud.githubusercontent.com/assets/17054312/20213473/7440d5e4-a7ce-11e6-9b6f-20412d39a310.png)

**Comment by develar** [comment]
Please attach full build log (better to set env `DEBUG=electron-builder`).

**Comment by workswithweb** [comment]
Attached is the log file with DEBUG=electron-builder
[log.zip](https://github.com/electron-userland/electron-builder/files/585691/log.zip)

**Comment by workswithweb** [comment]
Attached is the log file with DEBUG=electron-builder and when gatekeeper-assess  not set
[log2.zip](https://github.com/electron-userland/electron-builder/files/585704/log2.zip)

**Comment by workswithweb** [comment]
I am having app crash issue from 7.24.1

**Comment by develar** [comment]
I see that you not only build mas, but for mac as well. And no valid `Developer ID Application:` in the keychain.

**Comment by workswithweb** [comment]
Ok. Thanks for the feedback. Will try including "Developer ID Application" or just build MAC apps. (I was not having this issue before when building both apps together)

**Comment by workswithweb** [comment]
Still having same issue while generating only for mas.
Attached is the logs.
[log3.zip](https://github.com/electron-userland/electron-builder/files/586220/log3.zip)

**Comment by workswithweb** [comment]
May be below information is helpful.

I narrowed down issue to "electron-osx-sign-tf". (with electron-builder v 7.24.1)
If I use electron-osx-sign-tf version 1.0.1, it works fine. 
using electron-osx-sign-tf version 1.1.0 is having above issue (I haven't tried electron-osx-sign-tf releases in between. If you need, I can try with other versions of electron-osx-sign-tf )

**Comment by chunkiat82** [comment]
I have having this issue too. I managed to sign the app manually without issues.

**Comment by develar** [comment]
Please provide debug log — set env `DEBUG=electron-builder,electron-osx-sign*`

@sethlu If you have time, could you please help? electron-builder uses latest version of electron-osx-sign (+ https://github.com/electron-userland/electron-osx-sign/pull/80) 

As @workswithweb discovered, "I use electron-osx-sign-tf version 1.0.1, it works fine", probably your latest changes is the reason of issue.

**Comment by develar** [comment]
Reproduced.

**Comment by develar** [comment]
```
 electron-osx-sign `identity` passed in arguments. +734ms
  electron-osx-sign:warn No `entitlements` passed in arguments: 
 * Sandbox entitlements are required for Mac App Store distribution, your codesign entitlements file is default to: /Users/develar/Documents/electron-builder/node_modules/electron-macos-sign/default.entitlements.mas.plist +0ms
  electron-osx-sign:warn No `entitlements-inherit` passed in arguments: 
 * Sandbox entitlements file for enclosing app files is default to: /Users/develar/Documents/electron-builder/node_modules/electron-macos-sign/default.entitlements.mas.inherit.plist +0ms
  electron-osx-sign Identity: 
 > Name: 3rd Party Mac Developer Application: Vladimir Krivosheev (X8C9Z9L4HW) +687ms
  electron-osx-sign Found 1 identity. +1ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile: 
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +0ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign:pre-embed-provisioning-profile No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +1ms
  electron-osx-sign:pre-embed-provisioning-profile No provisioning profile found, will not embed profile in app contents. +1ms
  electron-osx-sign:pre-auto-entitlements Automating entitlement app group... 
 > Info.plist: /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Info.plist 
 > Entitlements: /Users/develar/Documents/electron-builder/node_modules/electron-macos-sign/default.entitlements.mas.plist +0ms
  electron-osx-sign:pre-auto-entitlements `ElectronTeamID` not found in `Info.plist`, use parsed from signing identity: X8C9Z9L4HW +2ms
  electron-osx-sign:pre-auto-entitlements Entitlements file updated: 
 > Info.plist: /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Info.plist +3ms
  electron-osx-sign:pre-auto-entitlements `com.apple.application-identifier` not found in entitlements file, new inserted: X8C9Z9L4HW.org.develar.onshape +0ms
  electron-osx-sign:pre-auto-entitlements `com.apple.developer.team-identifier` not found in entitlements file, new inserted: X8C9Z9L4HW +0ms
  electron-osx-sign:pre-auto-entitlements `com.apple.security.application-groups` not found in entitlements file, new inserted: X8C9Z9L4HW.org.develar.onshape +0ms
  electron-osx-sign:pre-auto-entitlements Entitlements file updated: 
 > Entitlements: /var/folders/3f/qqlb61zj491dnhr434dhwb8m0000gn/T/electron-macos-sign-94969-org.develar.onshape.plist +1ms
  electron-osx-sign Signing application... 
 > Application: /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app 
 > Platform: mas 
 > Entitlements: /var/folders/3f/qqlb61zj491dnhr434dhwb8m0000gn/T/electron-macos-sign-94969-org.develar.onshape.plist 
 > Child entitlements: /Users/develar/Documents/electron-builder/node_modules/electron-macos-sign/default.entitlements.mas.inherit.plist 
 > Additional binaries: undefined 
 > Identity: 3rd Party Mac Developer Application: Vladimir Krivosheev (X8C9Z9L4HW) +0ms
  electron-osx-sign Walking... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents +0ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +38ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +1s
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +493ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Electron Framework.framework +583ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper EH.app/Contents/MacOS/Onshape Helper EH +1s
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper EH.app +427ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper NP.app/Contents/MacOS/Onshape Helper NP +413ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper NP.app +426ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper.app/Contents/MacOS/Onshape Helper +501ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Frameworks/Onshape Helper.app +496ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/MacOS/Onshape +417ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Resources/app/node_modules/keytar/build/Release/keytar.node +504ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app/Contents/Resources/app/node_modules/nslog/build/Release/nslog.node +456ms
  electron-osx-sign Signing... /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app +433ms
  electron-osx-sign Verifying... +497ms
  electron-osx-sign Verifying application bundle with codesign... +1ms
  electron-osx-sign Verified. +436ms
  electron-osx-sign Displaying entitlements... +0ms
  electron-osx-sign Entitlements (prefixed with blob header):
��qq<<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.application-identifier</key>
    <string>X8C9Z9L4HW.org.develar.onshape</string>
    <key>com.apple.developer.team-identifier</key>
    <string>X8C9Z9L4HW</string>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>X8C9Z9L4HW.org.develar.onshape</string>
    </array>
  </dict>
</plist> +30ms
  electron-osx-sign Application signed. +1ms
  electron-builder Executing productbuild --component /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app /Applications --sign 3rd Party Mac Developer Installer: Vladimir Krivosheev (X8C9Z9L4HW) /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape-0.5.4.pkg +5ms
productbuild: Adding component at /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape.app
productbuild: Signing product with identity "3rd Party Mac Developer Installer: Vladimir Krivosheev (X8C9Z9L4HW)" from keychain /Users/develar/Library/Keychains/login.keychain-db
productbuild: Adding certificate "Apple Worldwide Developer Relations Certification Authority"
productbuild: Adding certificate "Apple Root CA"
productbuild: Wrote product to /Users/develar/Documents/onshape-desktop-shell/dist/mas/Onshape-0.5.4.pkg
productbuild: Supported OS versions: [10.9.0, )

```

**Comment by sethlu** [comment]
@develar I've already review the changes; sorry for it taking this long.

And @chunkiat82 I've just posted a PR addressing the unexpected team identifier in entitlements file, on which I will test and merge later.

**Comment by develar** [comment]
All changes after https://github.com/electron-userland/electron-osx-sign/commit/0fd220e756060ca220455b1beb0f226242506356 were reverted. Sorry for inconvenience. Our test suite will be improved to avoid such issues in the future.

**Comment by sethlu** [comment]
@develar would you check if your npm module published `electron-macos-sign` is up to date with the latest `electron-osx-sign`? Quite a few changes have been introduced since `@0.4.0-beta4`.

**Comment by sethlu** [comment]
@develar @chunkiat82 I would recommend generating a provisioning profile (wildcard is fine) for development first and then test signing with it first with `--type=development`.

**Comment by develar** [comment]
I am not expert here and trust @sethlu. Issue reopened — docs will be added about it.

**Comment by sethlu** [comment]
@develar I'll soon update guides to sign with the latest standard https://github.com/electron-userland/electron-osx-sign/issues/106.

**Comment by integrable** [comment]
Hi, I get the same error `EXC_CRASH (Code Signature Invalid)`, I think after updating Xcode from 7 to 8.   So, if I understand correctly, there is no way to run MAS build signed with the distribution certificate. Thus, I try to use the developer certificate to sign MAS build, but it fails: `Error: App is not signed: cannot find valid "3rd Party Mac Developer Application" identity` (I tried using CSC_LINK and automatic discovery in keychain). Is there any other way to run MAS build on the dev machine?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-osx-sign/pull/105#issuecomment-260211431

> This means that, going forward, distribution builds of Mac apps cannot be run directly; they are for submitting to iTunes Connect for app review only.

**Comment by develar** [comment]
@sethlu Could you please confirm that electron-builder behaviour is correct? We use latest version of electron-osx-sign without any extra and changed defaults. Exactly as if user will use electron-osx-sign directly. Maybe electron-builder should warn that mas build cannot be run directly and provide special target to test mas build locally?

**Comment by pie6k** [comment]
I'm also having this issue, anyone found some solution?

**Comment by sethlu** [comment]
@pie6k Please note that app bundles codesigned via `electron-osx-sign` will not run if using `3rd Party Mac Developer Application`... Here's a summary of what leads to this somewhat unexpected behavior:

1. With App Sandbox, the main/renderer Electron processes will have trouble communicating to each other, resulting in frozen renderer (so after codesign the app would launch just fine, but frozen).
2. We can add application group property to the entitlements file to allow interprocess communication & add `ElectronTeamID` to `Info.plist` and the app should behave correctly after codesigning. ✅ 

🎯 The above procedure corresponds to the following code signing script

```sh
electron-osx-sign path/to.app --no-pre-auto-entitlements --entitlements=mas.entitlements
# include "--type=development" for development 😅 
```

The `mas.entitlements` should include the following (minimal)

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>XXXXXXXXXX.app-bundle-id</string>
	</array>
	<key>com.apple.application-identifier</key>
	<string>XXXXXXXXXX.app-bundle-id</string>
</dict>
</plist>
```

The `Info.plist` should include `ElectronTeamID` as `XXXXXXXXXX`.

With this setup, the app should launch with either signing certificate for development or distribution.

---

Some additional information from: https://github.com/electron-userland/electron-osx-sign/blob/b6fcaa570cf306771b3af9a8394ccd7037a74b25/README.md

> Since electron-osx-sign adds the entry com.apple.developer.team-identifier to a temporary copy of the specified entitlements file (with the default option --pre-auto-entitlements) distribution builds can no longer be run directly. To run the app codesigned for distribution locally after codesigning, you may manually add ElectronTeamID in your Info.plist and com.apple.security.application-groups in the entitlements file, and provide the flag --no-pre-auto-entitlements for electron-osx-sign to avoid this extra bit. Note that "certain features are only allowed across apps whose team-identifier value match" (Technical Note TN2415).

---

**Here's what `electron-osx-sign` does a little differently:** Since Electron supports macOS features like Handoff, _when app sandbox is enabled_, `electron-osx-sign` (default with `--pre-auto-entitlements`) will automatically inject `com.apple.developer.team-identifier` into the entitlements to enable these features... and this entry must be whitelisted by a provisioning profile.

Therefore, `electron-osx-sign` requires provisioning profiles whenever app sandbox is enabled (applicable to MAS development and distribution). They will be picked up automatically if placed in the current working directory.

🤔 _I think the this entitlements automation behavior will likely change in a next major release of `electron-osx-sign` so the presence of provisioning profile should be what adds in the whitelisted entitlement entries, instead of when app sandbox is enabled._

---

To answer the question, the part marked 🎯 should be a workable code signing setup.

Alternatively, you can generate the provisioning profiles for development & for distribution on the MAS, place them in the current working directory, and trust `electron-osx-sign` to embed profiles and make the correct entitlements updates. Then the following script should do...

```sh
electron-osx-sign path/to.app
# include "--type=development" for development 😅 
```

More info: https://mintkit.net/electron-userland/electron-osx-sign/guide/

**Comment by pauljonescodes** [comment]
One thing that was contributing to this for me was that a certain entitlement is inexplicably required and commonly cited as being a string when it's an array of strings.

https://github.com/electron/osx-sign/issues/281#issuecomment-1967719627
