### ISSUE TITLE
Mac build: Error: spawnSync electron-builder ENOENT

### ISSUE THREAD

**Issue by beshur** [electron-userland/electron-builder#898]
* **Version**: 2.9.0

* **Build platform**: Mac

* **Target**: Mac

Hi.
I'm trying to build our app and get this error: https://gist.github.com/beshur/dc6b46b75f8beaa9ef5fa64b63561bdd

My user is the owner of all the folders.

Here is also a totally different error on a different machine:
https://gist.github.com/beshur/0bc201ebe51dde8136e28907c648fb3f

Any ideas guys?

**Comment by develar** [comment]
If you really use version 2.9.0, then I can say only "please use latest version" ;)

**Comment by beshur** [comment]
Thanks for suggestion, @develar.
But we used it this summer to build an app and it worked. Then we did not touch it for a while. And now need to build that old version with pre-release Electron.

**Comment by develar** [comment]
Sorry, it is too old. I cannot advice.

**Comment by develar** [comment]
I see that old API was removed only in the 3.0.0. So, please ensure that you did `npm install` before.

**Comment by beshur** [comment]
I did `npm install`

**Comment by beshur** [comment]
@develar, what old API you are talking about?

**Comment by develar** [comment]
> what old API you are talking about?

Please see https://github.com/electron-userland/electron-builder/blob/master/CHANGELOG.md#breaking-changes-4
