### ISSUE TITLE
Get or Specify Final Build exe or dmg file names.

### ISSUE THREAD

**Issue by aesalazar** [electron-userland/electron-builder#899]
* **Version**: 7.24.1 

* **Target**: Windows and Mac

Doing programmatic builds in JavaScript.  I would like to be able to get the output file name somehow.  I can concatenate the properties but that is assumption based and would rather know definitely what the final file_name.exe is.  It would be nice to actually specify it somehow.  I posted a question on StackOverflow:  http://stackoverflow.com/questions/40549421/retrieve-or-specify-output-file-name-in-electron-builder

Thanks
Ernie

**Comment by develar** [comment]
For what do you need output file name?

You can use `packager`directly and listen `artifactCreated` event. Please see https://github.com/electron-userland/electron-builder/blob/master/src/builder.ts method `build` implementation.

**Comment by aesalazar** [comment]
Consider this:

```javascript
//Install page for Electron Application
router.get('/electron', function(req, res, next){
    const promise = electronBuilder
        .buildPromise()
        .then(() => {
            const file = electronBuilder.outputFilename;
            const data = fs.readFileSync(`${electronBuilder.outputPath}/${file}`);

            res.setHeader('Content-Disposition', `attachment; filename="${file}"`);

            if(file.substr(file.length - 3) === "exe")
                res.setHeader('Content-type', 'application/exe, application/octet-stream');
            else if (file.substr(file.length - 3) === "dmg")
                res.setHeader('Content-type', 'application/dmg, application/octet-stream');

            res.send(data);
        }).catch((error) => {
            console.error(error);
        });
});
```

What I am doing is calling the builder trigger by the user, say, clicking a Download button.  After the builder is done I want to send the file back over the response.  I do that by recreating the file name like this inside `electronBuilder` and exposing it:

```javascript
//Have to recreate output file path
let outputPath = devMetadata.directories.output;
let outputFilename = `${devMetadata.build.productName} Setup ${packagejson.version}`;

if (Platform.current().name === "windows")
    outputFilename += ".exe";
else if(Platform.current().name === "mac")
    outputFilename += ".dmg";
```

I would be much more comfortable getting the file name directly from the source (i.e. `builder`) rather then assuming the format.

**Comment by develar** [comment]
`builder.buld` currently returns `Promise<void>` and it is not useful. Will be improved.

**Comment by aesalazar** [comment]
That would be great if it is some kind of pass argument.  Thanks for the help!

Ernie

**Comment by develar** [comment]
List of artifacts is returned.

<img width="889" alt="screen shot 2016-11-12 at 18 53 41" src="https://cloud.githubusercontent.com/assets/350686/20239785/5b46618a-a909-11e6-8ccf-41d7e8547765.png">

**Comment by aesalazar** [comment]
Works great, thanks for adding it!

**Comment by aesalazar** [comment]
I tried to test out my app in Unbutu (was using windows before) and get an error during npm install:

```
TypeError: Cannot read property 'npmArgs' of undefined
    at computeExtraArgs (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-
builder/src/yarn.ts:31:24)
    at /home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/src/yarn.t
s:9:16
    at next (native)
From previous event:
    at installOrRebuild (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-
builder/out/yarn.js:33:21)
    at /home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/src/instal
l-app-deps.ts:29:2
    at next (native)
From previous event:
    at main (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/out/
install-app-deps.js:27:21)
    at Object.<anonymous> (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electro
n-builder/out/install-app-deps.js:73:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Let me know if you need any more details on it.
