### ISSUE TITLE
Auto updater "error" event does not contain error message

### ISSUE THREAD

**Issue by MaKleSoft** [electron-userland/electron-builder#900]
* **Version**: 8.3.0
* **Target**: nsis

When I run `checkForUpdates` in the nsis windows app I see the `checking-for-update` event, followed, by the `error` event. However, instead of an error message, two empty objects are passed to the event handler. I use "github" as `publish.provider` in case that's relevant.

**Comment by develar** [comment]
Fixed version: 0.5.1 electron-builder version doesn't matter.

**Comment by MaKleSoft** [comment]
@develar Hm, now I'm getting no 'error' event at all after the 'checking-for-update' event, nor am I getting any other event.

**Comment by develar** [comment]
Please try  0.5.2.

**Comment by MaKleSoft** [comment]
@develar Looks good, thanks! (I'm getting an unexpected error now, but I'll create another issue for that)
