### ISSUE TITLE
"The directory [object Object]/RELEASES does not exist"

### ISSUE THREAD

**Issue by Meadowcottage** [electron-userland/electron-builder#901]
## Issue:
> Error with Windows AutoUpdater.
> **"The directory [object Object]/RELEASES does not exist"**
![](https://i.gyazo.com/bc976e24ca10f56e1ed9a22097c44b7d.png)

**Comment by develar** [comment]
Have you read breaking changes in the 8 release? Nsis is the default target now.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v8.0.0

**Comment by develar** [comment]
Sorry, I see that squirrel target is specified.

**Comment by Meadowcottage** [comment]
Yes I specify Squirrel.
You recommend that I move my default target to NSIS now?

**Comment by develar** [comment]
Yes, I recommend to use NSIS but currently NSIS doesn't help you to migrate old Squirrel Windows to NSIS, so, for existing apps it maybe not acceptable.

**Comment by Meadowcottage** [comment]
It is fine. This `TestElectron` repo is a test for an auto updater. Testing it here before I add the updater to all my apps. Better I switch to NSIS now rather than later.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update please keep in mind that https://github.com/megahertz/electron-simple-updater will be soon integrated into electron-builder.

**Comment by Meadowcottage** [comment]
Would it be worth me instead waiting for you to integrate `electron-simple-update`?
Or shall I update now?

**Comment by develar** [comment]
Auto Update for when ndows tested and works. You can use NSIS.

**Comment by Meadowcottage** [comment]
Okay. Any idea how much of a change there will be from the current `electron-auto-updater` to the new `electron-simple-update`?

**Comment by develar** [comment]
Nothing will be changed. Electron auto update API is supported and will be still supported. You are not forced to use custom promise-based API.

**Comment by Meadowcottage** [comment]
Okay. Good to know, thank.

**Comment by develar** [comment]
Please be aware of #884

**Comment by Meadowcottage** [comment]
Thanks for the heads up 😄
