### ISSUE TITLE
Update CodeSign wiki regarding Start SSL

### ISSUE THREAD

**Issue by MrBlenny** [electron-userland/electron-builder#904]
* **Target**: Windows

StartSSL is not currently selling certificates.

The notice in the [StartCom ToolBox](https://www.startssl.com/Certificates) says:

> Notice: 
> Mozilla and Google decided to distrust all StartCom root certificates as of 21st of October, this situation will have an impact in the upcoming release of Firefox and Chrome in January. StartCom will provide an interim solution soon and will replace all the issued certificates from that date in case of requested. Meanwhile StartCom is updating all their systems and will generate new root CAs as requested by Mozilla to regain the trust in these browsers. 
> StartCom decide to paused the charged validation service from Nov. 3rd, any subscribers that paid the validation fee after Oct. 21st can get full refund by request.

* Is there another recommended service for cheap Windows Code Signing?
* It appears as though the Apple Certificate will not work for windows - Is this still the case?

**Comment by develar** [comment]
I think code signing certificates are not affected. I will contact StartSSL.

**Comment by develar** [comment]
> the Apple Certificate will not work for windows - Is this still the case?

Yes, because Apple root cert is not trusted on windows.

**Comment by develar** [comment]
Official answer:

> Hi, the ssl certificate will be affected but the code signing cert will not be affected. In addition, I would like to mention that all certificates issued before 21.10.2016 will not be affected. You will be able to use them even after January.
