### ISSUE TITLE
Process Id over 2048 on Windows leads to System.IndexOutOfRangeException on Squirrel Install

### ISSUE THREAD

**Issue by michael-kindtner** [electron-userland/electron-builder#905]
* **Version**: 7.26.0

* **Target**: Windows 7/8/8.1/10

When installing an electron/aurelia app on Windows with many open programs, taskbar-icons etc., an error is raised (System.IndexOutOfRangeException)
 
The Log is attached.
[SquirrelSetup (2).log.zip](https://github.com/electron-userland/electron-builder/files/589252/SquirrelSetup.2.log.zip)

**Comment by develar** [comment]
Please use nsis instead of Squirrel.Windows.
