### ISSUE TITLE
Mac App is not signed: cannot find valid "Developer ID Application"

### ISSUE THREAD

**Issue by alexKazarin** [electron-userland/electron-builder#910]
* **Version**: 7.26.0

* **Target**: OSX (10.9.5)

  I have tried to sign my app with "Developer ID Application" cert, which was generated in developer account and it's (cert) valid:
![certificate2016-11-15](https://cloud.githubusercontent.com/assets/18268219/20302840/f5e6aac4-ab39-11e6-92a3-7d8114bab2e4.png)
  But when I build mac, I receive warning in console:
![error](https://cloud.githubusercontent.com/assets/18268219/20302979/54e8b292-ab3a-11e6-865c-78ce014e6ba0.png)
 And as a result - app is not signed.

**Comment by develar** [comment]
Please update to 8.6.0.

Please set env `DEBUG=electron-builder`.

**Comment by alexKazarin** [comment]
Updated to 8.6.0;
With use of DEBUG:
```
electron-builder Executing security find-identity -v +5s
  electron-builder Executing security find-identity -v -p codesigning +92ms
     0 valid identities found
     0 valid identities found
```
I try *security find-identity -v -p codesigning* on other machine, and receive only keys from  "My Certificates" category, but "Developer ID Application" cert is under Certificates Category.

**Comment by develar** [comment]
Your identity is not valid because no private key (only public cert without private key). Please use Xcode to retrieve identity.

<img width="1177" alt="screen shot 2016-11-15 at 14 55 20" src="https://cloud.githubusercontent.com/assets/350686/20308303/8e0367ee-ab43-11e6-82be-789944b160ad.png">

**Comment by alexKazarin** [comment]
Now all clear. Thank you!
I have created my public/private keys and generated a request for certificate (certSigningRequest).
My team administrator generate new Developer ID Application cert with use of certSigningRequest-file.
After that I add it to my Certificates in Keychain.

**Comment by sourabhverificient** [comment]
I tried 

**electron-builder.env**

`DEBUG=electron-builder
CSC_LINK=~/Downloads/Certs/Certificates.p12
CSC_NAME=Company name, Inc. (SKW21623)
CSC_IDENTITY_AUTO_DISCOVERY=false


**electron-builder.json`**

 ` "mac": {
    "identity":"Company name, Inc. (SKW21623)",
    "icon": "build/favicon.icns",
    "target": ["dmg"]
  }`

**and got this error**

 ⨯ Command failed: codesign --sign 4fd3e432124324fdf234 --force --timestamp --options runtime --entitlements /Users/apple/Documents/folder/desktopApp/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/apple/Documents/folder/desktopApp/release/mac/Demo1.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/apple/Documents/folder/desktopApp/release/mac/Demo1.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/apple/Documents/folder/desktopApp/release/mac/Demo1.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
  stackTrace=
  
  
  I can see key is added in keychain and its also showing disclosure triangle for private key .
