### ISSUE TITLE
Electron Builder fails when using privately-hosted scoped packages.

### ISSUE THREAD

**Issue by tomhallam** [electron-userland/electron-builder#911]
* ^7.23.2: 

* Any:

I'm attempting to script the build of our Mac and Windows app through our Bamboo build server. We use scoped packages to split functionality out. These scoped packages are hosted in a Sinopia instance within our VPC. 

It seems that `electron-builder` doesn't source the `.npmrc` file. The project builds correctly (there is an `npm install` task which executes without issue) - it seems when the context is switched to the `build -w` command (or indeed `install-app-deps`) it doesn't know where to find our private packages.

It's important to note that `electron-packager` works fine on Bamboo, the issue has only surfaced since we started to use `electron-builder`. Our `build` script in `electron-packager` is as follows:
`./node_modules/.bin/electron-packager . Project --platform=darwin --out release --overwrite`

I have removed the specific package and project names from the log below to maintain my organisation's privacy, however I feel this is representative.

```
build	15-Nov-2016 10:59:38	Installing app dependencies for arch x64 to /bamboo-agent-home/xml-data/build-dir/PROJECT-NAME/client/dist
build	15-Nov-2016 10:59:38	
error	15-Nov-2016 10:59:40	Error: /Users/bamboo/.nvm/versions/node/v6.8.1/bin/node exited with code 1
error	15-Nov-2016 10:59:40	Error output:
error	15-Nov-2016 10:59:40	npm ERR! Darwin 15.6.0
error	15-Nov-2016 10:59:40	npm ERR! argv "/Users/bamboo/.nvm/versions/node/v6.8.1/bin/node" "/Users/bamboo/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/npm-cli.js" "install" "--production" "--cache-min" "999999999" "--build-from-source"
error	15-Nov-2016 10:59:40	npm ERR! node v6.8.1
error	15-Nov-2016 10:59:40	npm ERR! npm  v3.10.8
error	15-Nov-2016 10:59:40	npm ERR! code E404
error	15-Nov-2016 10:59:40	
error	15-Nov-2016 10:59:40	npm ERR! 404 Not found : @organisation/package-name
error	15-Nov-2016 10:59:40	npm ERR! 404 
error	15-Nov-2016 10:59:40	npm ERR! 404  '@organisation/package-name' is not in the npm registry.
```

**Comment by develar** [comment]
electron-builder spawns npm and, so, we don't need to care about `.npmrc`.

Do you call `build` using npm script or directly?

BTW: please use version `8.6.0` — unlikely it will fix the issue, but just to be sure,

**Comment by develar** [comment]
Also, please, set env `DEBUG=electron-builder`.

**Comment by tomhallam** [comment]
@develar thanks for your reply - in my `package.json` I have the following line:
`    "distMac": "build -m",`
and Bamboo runs this:
`npm run-script distMac`

**Comment by develar** [comment]
I think, it is Sinopia bug. https://github.com/rlidwka/sinopia/issues/337 (https://github.com/rlidwka/sinopia/pull/280#issuecomment-255099370)

**Comment by tomhallam** [comment]
We're not using Sinopia as a caching server, only for specific scoped packages. Entire contents of `.npmrc` (modified for privacy):

```
@organisation:registry=http://npm.our.organisation.org/
//npm.our.organisation.org/:_authToken="the/token="
```

**Comment by develar** [comment]
1. Please upgrade to electron-builder 8.6.0 (major because of https://github.com/electron-userland/electron-builder/releases/tag/v8.0.0).

2. If you use 2-package.json structure — do not use (https://github.com/electron-userland/electron-builder/issues/906).

I am sure it will solve your issue.

**Comment by tomhallam** [comment]
@develar I have removed any reference to `install-app-deps` and upgraded the version of `electron-builder` to `8.6.0` but I still get errors related to the private scoped repositories. 

After having enabled the `DEBUG` environment variable, the only extra log line I get is as follows:

```
build	15-Nov-2016 11:50:29	Installing app dependencies for arch x64 to /bamboo-agent-home/xml-data/build-dir/PROJECT-NAME/client/dist
error	15-Nov-2016 11:50:29	Tue, 15 Nov 2016 11:50:29 GMT electron-builder Spawning /Users/bamboo/.nvm/versions/node/v6.8.1/bin/node /Users/bamboo/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/npm-cli.js install --production --cache-min 999999999 --build-from-source
```

**Comment by develar** [comment]
Do you use 2-package.json structure?

Please try to execute `/Users/bamboo/.nvm/versions/node/v6.8.1/bin/node /Users/bamboo/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/npm-cli.js install --production --cache-min 999999999 --build-from-source`

**Comment by tomhallam** [comment]
We do use the two package.json structure.

I am not sure I'll be able to execute that command as it's within our build system and I probably don't have access. I will check, but do you think the two package.json structure is something to do with it?

**Comment by develar** [comment]
> do you think the two package.json structure is something to do with it?

No, you should not use it. But if you see 

`Installing app dependencies`

in the log it means:

* you use electron-builder < 8
* or you use two package.json structure
* or no `node_modules` — you didn't call `npm install` before build.

I ask you to provide full build log.

**Comment by tomhallam** [comment]
I fixed this with the two `package.json` structure by copying `.npmrc` into my `dist` folder before `electron-builder` gets to work. I now have a different issue, but we can consider this matter closed. Thanks for your help.

**Comment by develar** [comment]
It looks like as `npm` bug. Well, because `npm` will be soon deprecated by electron-buidler in favour of `yarn`, I am not going to dig deeper.
