### ISSUE TITLE
Error: electron must be in the devDependencies

### ISSUE THREAD

**Issue by jlouazel** [electron-userland/electron-builder#912]
* **Version**: 

Latest -> 8.6.0

* **Target**: 

Whatever

It happens as soon as I try to use the script `node_modules/.bin/build`. I can't get rid of the following error:

<img width="819" alt="screen shot 2016-11-15 at 13 39 22" src="https://cloud.githubusercontent.com/assets/2803310/20306206/68fdcee4-ab39-11e6-9e60-a38081fd3df8.png">

I used to make it work but something is definitively broken now. Here is the current packages I use for now:

![image](https://cloud.githubusercontent.com/assets/2803310/20306292/c7e596bc-ab39-11e6-8af2-cf152498a84d.png)

Thanks in advance for your help.

**Comment by develar** [comment]
`electron` must be in the `devDependencies`. It is valid error.

> something is definitively broken now

Runtime error?

**Comment by jlouazel** [comment]
I understand what's going on. I have the following project architecture:
```
.
├── app
│   ├── ...
│   └── package.json (B)
├── ...
└── package.json (A)
```

The file `(A)` contains all the electron stuff (and `electron` in **devDependendies**)  to build my app and the file `(B)` contains what's needed by my app. In my app, I do import the `ipcRenderer` from electron and so I put `electron` inside of ... **dependencies** in the file `(B)`.

Removing `electron` from the **dependencies** of the file `(B)` fixed the problem. The thing I don't understand is why the `checkDependencies` of the **packager.ts** produces an error for this case. Since I'm calling it from my root folder, it should not care about the `app/` folder right?

**Comment by jlouazel** [comment]
Btw, thank you for your quick answer. Effectively `electron-builder` was providing a correct error given the context explained on my previous answer.

**Comment by develar** [comment]
> I'm calling it from my root folder, it should not care about the app/ folder right?

No, you use two-package.json structure and electron-builder aware about it. BTW, since electron-builder 8 consider to use simple 1 package.json structure (https://github.com/electron-userland/electron-builder/issues/906).

**Comment by develar** [comment]
> I do import the ipcRenderer from electron and so I put electron inside of ... dependencies in the file (B).

Doesn't matter. electron is not resolved as standard node module. It is not node module. So, `electron` dependency is required only and only if you want to run your app without pack.

**Comment by jlouazel** [comment]
Thanks for you help @develar

**Comment by seeekr** [comment]
Just wanna say that while the error message is technically correct, it is still confusing to (especially new) users of electron / electron-builder. Ideally the message would explicitly state that the `electron` dependency has been found inside of `dependencies`, instead of inside the `devDependencies` section. That would make the solution that much easier to find.
Aside from that, thanks for making this software! Using it for the first time, enjoying it!

**Comment by develar** [comment]
@seeekr Thanks for note. PR to correct warning text is welcome ;)

**Comment by seeekr** [comment]
@develar #986 :)
