### ISSUE TITLE
Cannot launch app after install Windows x64 Squirrel

### ISSUE THREAD

**Issue by ipatina** [electron-userland/electron-builder#914]
* **Version**: 8.6.0

* **Target**: Windows x64 Squirrel

Here is the content of SquirrelSetup file:
2016-11-16 15:02:15> Program: Starting Squirrel Updater: --processStart appname.exe
2016-11-16 15:02:15> Program: Want to launch 'C:\Users\nnn\AppData\Local\vuzb\app-0.0.1\appname.exe'
2016-11-16 15:02:15> Program: About to launch: 'C:\Users\nnn\AppData\Local\vuzb\app-0.0.1\appname.exe':

I have no idea what can be wrong.

**Comment by develar** [comment]
Are you aware that since 8.0 Squirrel.Windows is deprecated and nsis is the default target for windows? https://github.com/electron-userland/electron-builder/releases/tag/v8.0.0

**Comment by ipatina** [comment]
Is auto-updating works ok with nsis?

**Comment by develar** [comment]
Yes. Please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by develar** [comment]
Related to #901

**Comment by ipatina** [comment]
I switched to NSIS, but problem is still there. 
App launches via npm start.

**Comment by develar** [comment]
Please specify runtime error.

**Comment by ipatina** [comment]
No runtime errors. It just doesn't launch, silently (sorry, i know this answer wont help you).

**Comment by develar** [comment]
Well... is it possible to provide test project?

**Comment by ipatina** [comment]
No.. Project uses webpack, maybe some problems with it.
I have another question about https server for generic provider. I'm using local https server with self-signed sertificate for tests, and when my app makes reqest for updates it receives nothing. Neither update-available nor update-not-available event emits. Is it because self-signed sertificate? Can I do smth like 'curl -k' for auto-updater? Should I make new issue for this question?

**Comment by develar** [comment]
Алина, если возможно, укажите пожалуйста точную причину — может  быть electron-builder может это как-то обнаруживать и предупреждать?

**Comment by ipatina** [comment]
Причина в подключении модулей 'electron-debug' и 'devtron'. К сожалению, не могу сказать почему и как именно эти модули влияют на запуск, так как приложение писал другой разработчик.
