### ISSUE TITLE
[DEB packaging] Replace ia32 arch name with i386 in package filename

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#915]
As you already do with 64-bit packages, replacing arch name `x86_64` with `amd64`, I would like to suggest you to replace `ia32` arch name with `i386` in 32-bit DEB packages' filename. Currently all non-ARM 32-bit DEB packages available in official Debian/Ubuntu repositories have `i386` as the arch name.

**Comment by develar** [comment]
It is another breaking change :) ....

**Comment by SxMShaDoW** [comment]
breaking changes are the best!

**Comment by giacgbj** [comment]
In breaking changes we trust!
