### ISSUE TITLE
Access denied when running app created by electron-builder

### ISSUE THREAD

**Issue by wangxiexe** [electron-userland/electron-builder#917]
* **Version**: 5.23.2

* **Target**: windows

Got error like this, please advice.

Access is denied.

\\?\c:\Users\Alley\AppData\Local\Temp\EA4B.tmp.node
at Error (natvie)
.........
.........

**Comment by develar** [comment]
Workaround: add `"asar": false"` to the `"build"`. Could you please provide project to reproduce?
