### ISSUE TITLE
RangeError: Maximum call stack size exceeded in yarn

### ISSUE THREAD

**Issue by ztooner** [electron-userland/electron-builder#918]
* **Version**: 7.14.2

* **Target**: win32

Packaging for platform win32 x64 using electron 1.4.6 to dist\win-unpacked
RangeError: Maximum call stack size exceeded
  at flatDependencies (E:\build\85b48912f8609468\node_modules\electron-builder\src\yarn.ts:76:17)

This error has been there for three days, it's a clean build.
Has anyone else run into this error?

**Comment by develar** [comment]
Duplicates #895
