### ISSUE TITLE
Target-specific extraResources ?

### ISSUE THREAD

**Issue by pconerly** [electron-userland/electron-builder#919]
* **Version**: 8.6.0

* **Target**: Windows and Mac

Is there a way to specify `extraResources` in a per-target basis?

There is some content I want to include only for windows, and there is some content I only want to include for OSX.

**Comment by develar** [comment]
Most of the options can be specified per target or per platform. If not, option marked as `Cannot be specified per target`. 

extraResources can be specified per platform, but not for per target — it is ok for your case: put `extraResources` to `mac` (win specific to `win`).

If `extraResources` also specified in the `build` it will be added to list as well.

**Comment by pconerly** [comment]
Cool, thanks for the answer.

Just to document this more--- what I ended up doing was including this in `files`:

```
files: [ "special_plugins_${os}" ]
```

And then organizing the files accordingly into `special_plugins_win/` and `special_plugins_osx/`.

**Comment by develar** [comment]
Probably for plugins you should use extraFiles — it will be not packed into asar by default.

**Comment by Holybasil** [comment]
> Most of the options can be specified per target or per platform. If not, option marked as `Cannot be specified per target`.
> 
> extraResources can be specified per platform, but not for per target — it is ok for your case: put `extraResources` to `mac` (win specific to `win`).
> 
> If `extraResources` also specified in the `build` it will be added to list as well.

My error:
```
configuration.dmg has an unknown property 'extraResources'. These properties are valid:
   object { artifactName?, background?, backgroundColor?, contents?, format?, icon?, iconSize?, iconTextSize?, internetEnabled?, publish?, sign?, title?, window?, writeUpdateInfo? }
```

My code:
```
 "extraResources": [
      {
        "from": "extra",
        "to": "externalDep/extra"
      }
    ],
 "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ],
      "sign": false,
      "extraResources":[
        {
          "from": "server/macos",
          "to": "externalDep/macos"
        }
      ]
    }
```
What else do I need to do?

**Comment by Holybasil** [comment]
> Cool, thanks for the answer.
> 
> Just to document this more--- what I ended up doing was including this in `files`:
> 
> ```
> files: [ "special_plugins_${os}" ]
> ```
> 
> And then organizing the files accordingly into `special_plugins_win/` and `special_plugins_osx/`.

It works! Thank you:)

**Comment by ppazos** [comment]
@Holybasil is $os defined by electron-builder? or should it be defined somewhere? thanks
