### ISSUE TITLE
can electron-builder change electron download source?

### ISSUE THREAD

**Issue by FTAndy** [electron-userland/electron-builder#920]
* **Version**: 

* **Target**: 

electron-packager can download electron with --mirror options, seems electron builder can not do this. Any way to download electron faster ?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-download

> You can set the ELECTRON_MIRROR or NPM_CONFIG_ELECTRON_MIRROR environment variable or mirror opt variable to use a custom base URL for grabbing Electron zips.

**Comment by FTAndy** [comment]
@develar 
```javascript
function createDownloadOpts(opts: any, platform: string, arch: string, electronVersion: string) {
  const downloadOpts = Object.assign({
    cache: opts.cache,
    strictSSL: opts["strict-ssl"]
  }, opts.download)
```
the options doc does not declare the `build.download` options. i add a [pr](https://github.com/electron-userland/electron-builder/pull/921)
