### ISSUE TITLE
self signed certificate error

### ISSUE THREAD

**Issue by ipatina** [electron-userland/electron-builder#922]
* **Version**: 8.6.0

* **Target**: Windows NSIS

I'm using local https server with self-signed certificate for auto-update tests. I installed my certificate to os, but I'm receiving error 'self signed certificate' when auto-updater requests for update.

**Comment by develar** [comment]
We don't yet use our own implementation for macOS. You can or file issue to https://github.com/Squirrel/Squirrel.Mac or, and I recommend it, consider to use https://github.com/megahertz/electron-simple-updater (for macOS only). electron-simple-updater will be soon merged into electron-builder.

**Comment by ipatina** [comment]
macOS? No, I'm using Windows.

**Comment by develar** [comment]
In this case please specify full error message including stack trace.

**Comment by ipatina** [comment]
"Error: self signed certificate" - this is full error from this code 
```
autoUpdater.on('error', (error) => {
    dialog.showMessageBox({
        message: "error " + error,
        buttons: ['ok'],
        type: 'info'
    });
});
```

**Comment by develar** [comment]
Please try http://stackoverflow.com/a/38989441/1910191

**Comment by ipatina** [comment]
Still getting this error. [Here's code](https://github.com/ipatina/auto-update/blob/master/main.js)
![screenshot from 2016-11-23 13 19 48](https://cloud.githubusercontent.com/assets/16451144/20556423/6e67dad0-b180-11e6-9f6a-d8c9fa239815.png)

**Comment by ipatina** [comment]
Solved it by adding process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; before 
autoUpdater.checkForUpdates();
but now I'm getting error:
```
Cannot read property 'getVersion' of undefined
    at C:\Users\nnn\AppData\Local\Programs\application-name\0.0.10\resources\app.asar\node_modules\electron-auto-updater\out\nsis-auto-updater\src\NsisUpdater.js:134:85
```
On server side request responses ok.
from nginx logs:
``` [25/Nov/2016:14:56:52 +0400] "GET /latest.yml HTTP/1.1" 200 127 "-" "electron-builder```

and by curl response is ok: 
```
$ curl --insecure https://my.domain/latest.yml
version: 0.0.10
path: application-name Setup 0.0.10.exe
sha2: 480c8373fec21813eb89f73da80d3b279590830570120d19f4f08d46aeaf2425
```

**Comment by ipatina** [comment]
Solved by adding ```process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";``` before ```update.checkUpdate();```

**Comment by develar** [comment]
Please note — since 0.8 electron http API is used. Probably `process.env.NODE_TLS_REJECT_UNAUTHORIZED` workaround is outdated.
