### ISSUE TITLE
Installer window SOMETIMES does not close after app is launched for the first time (possible race condition)

### ISSUE THREAD

**Issue by Zamiell** [electron-userland/electron-builder#923]
* **Version**: 8.6.0

* **Target**: win32 x64

* **Build command**:
`npm run dist --python="C:/Python27/python.exe"`

* **Console output**:
```
Building: isaac-racing-client v0.0.1

> RacingPlus@ dist D:\Repositories\isaac-racing-client
> build

Rebuilding app dependencies for arch x64 to D:\Repositories\isaac-racing-client\
app

Packaging for platform win32 x64 using electron 1.4.1 to dist\win-unpacked

Building Squirrel.Windows installer
```

* **SquirrelSetup.log file after installation with the problem occuring**:
```
2016-11-18 12:01:35> Program: Starting Squirrel Updater: --createShortcut=Racing+.exe
2016-11-18 12:01:35> ApplyReleasesImpl: About to create shortcuts for Racing+.exe, rootAppDir C:\Users\james\AppData\Local\RacingPlus
2016-11-18 12:01:35> ApplyReleasesImpl: Creating shortcut for Racing+.exe => C:\Users\james\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Racing+\Racing+.lnk
2016-11-18 12:01:35> ApplyReleasesImpl: About to save shortcut: C:\Users\james\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Racing+\Racing+.lnk (target C:\Users\james\AppData\Local\RacingPlus\Update.exe, workingDir C:\Users\james\AppData\Local\RacingPlus\app-0.0.1, args --processStart "Racing+.exe")
2016-11-18 12:01:35> ApplyReleasesImpl: Creating shortcut for Racing+.exe => C:\Users\james\Desktop\Racing+.lnk
2016-11-18 12:01:35> ApplyReleasesImpl: About to save shortcut: C:\Users\james\Desktop\Racing+.lnk (target C:\Users\james\AppData\Local\RacingPlus\Update.exe, workingDir C:\Users\james\AppData\Local\RacingPlus\app-0.0.1, args --processStart "Racing+.exe")
2016-11-18 12:01:35> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-11-18 12:01:35> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2016-11-18 12:01:35> ApplyReleasesImpl: Examining Pin: OBS.lnk
2016-11-18 12:01:35> ApplyReleasesImpl: Examining Pin: Opera.lnk
```

* **Main package.json**:
```
{
  "name": "RacingPlus",
  "description": "A racing mod for The Binding of Isaac: Afterbirth+.",
  "scripts": {
    "start": "electron ./app",
    "postinstall": "install-app-deps",
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "squirrelWindows": {
      "iconUrl": "https://github.com/Zamiell/isaac-racing-client/blob/master/build/icon.ico?raw=true",
      "remoteReleases": false
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Zamiell/isaac-racing-client.git"
  },
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/Zamiell/isaac-racing-client/issues"
  },
  "homepage": "https://isaacracing.net",
  "devDependencies": {
    "electron": "^1.4.7",
    "electron-builder": "^8.6.0"
  }
}
```

* **App package.json (in app subdirectory)**:
```
{
  "name": "RacingPlus",
  "productName": "Racing+",
  "main": "./main.js",
  "version": "0.0.1",
  "description": "A racing mod for The Binding of Isaac: Afterbirth+.",
  "author": "Racing+",
  "license": "GPL-3.0",
  "dependencies": {
    "electron-is-dev": "^0.1.2",
    "electron-squirrel-startup": "^1.0.0",
    "fs-extra": "^1.0.0",
    "keytar": "^3.0.2",
    "ps-node": "^0.1.4",
    "tail": "^1.2.1"
  }
}
```

* **Node version**: v6.9.1
* **NPM version**: 3.10.8
* **OS**: Windows 7 x64 Professional

**What is supposed to happen and DOES happen in around 75% of installs**: The application successfully boots for the first time and the installer window closes less than a second later.

**What happens in around 25% of installs**: The application successfully boots for the first time, but the installer window stays around for another full 1-2 minutes (I haven't timed exactly how long). Eventually, it closes. My suspicion is that it is hanging until it times out or some such.

**Other information**: This has been happening for a few months ever since I started using electron-builder, so it is NOT just an isolated problem with version 8.6.0. Of course, this could be a problem in my utilization of electron-builder and/or package.json itself, but I'm not sure where to start troubleshooting. I will gladly provide any additional information if needed.

**Comment by develar** [comment]
Could you please use nsis target (default since electron-builder 8)?

**Comment by Zamiell** [comment]
Just to be clear, you want me to change my package.json from this:

```
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "squirrelWindows": {
      "iconUrl": "https://github.com/Zamiell/isaac-racing-client/blob/master/build/icon.ico?raw=true",
      "remoteReleases": false
    }
```

to this:

```
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "win": {
    }
```

?

**Comment by develar** [comment]
@Zamiell I recommend to migrate from Squirrel.Windows to NSIS. Currently, you don't specify target – but logs shows that Squirrel.Windows being built.

To migrate to NSIS:
* remove `squirrelWindows` configuration
* remove dependency electron-squirrel-startup — not required anymore.
* see https://github.com/electron-userland/electron-builder/wiki/Auto-Update
* ensure that you use electron-builder >=8.6.0.

**Comment by Zamiell** [comment]
Great! Since it is an entirely new installation system, I doubt the bug will persist, but I'll give it a whirl and report back.

One small thing though:

```
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "win": {
    }
```

This defaulted to a SquirrelWindows install. I had to explicitly use:

```
    "win": {
        "target": "nsis"
    },
```

(Again, I'm currently on electron-builder v8.6.0.)
This is contrary to what the docs say (https://github.com/electron-userland/electron-builder/wiki/Options):
`target	Target package type: list of nsis, squirrel, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir. Defaults to nsis.`

So either the docs are bugged or electron-builder is bugged?

**Comment by develar** [comment]
> or electron-builder is bugged?

I will check it right now.

**Comment by develar** [comment]
Are you sure that electron-builder 8 is installed? `./node_modules/.bin/build --version`?

**Comment by Zamiell** [comment]
Ah, my apologies. Apparently I was on version 7.9.0, even though I did a `ncu --upgradeAll` and my package.json reported `"electron-builder": "^8.6.0"`.

**Comment by develar** [comment]
@Zamiell Consider to use `^9.0.1` ;)

**Comment by Zamiell** [comment]
I've nuked my `node_modules` and `app/node_modules` directories and reinstalled, so now I have the latest versions.

I've also added a publish section to `package.json` file, so now it looks like this:

```
   ...
  "build": {
    "appId": "org.electron.isaacRacingClient",
    "win": {},
    "publish": {
      "provider": "github"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Zamiell/isaac-racing-client.git"
  },
  ...
```

However, now after installing my app, I get a "Please pass PublishConfiguration object at createCreate" error:

[error]: http://i.imgur.com/hXOieSo.png "error"

I googled around for this error and I wasn't able to find anything. Furthermore, the documentation surrounding this is unclear. All it says is literally "Configure publish", which is quite vague (from: https://github.com/electron-userland/electron-builder/wiki/Auto-Update)

Any tips?
