### ISSUE TITLE
Electron-Builder leaves node process running after build is complete

### ISSUE THREAD

**Issue by rainyday** [electron-userland/electron-builder#928]
* **Version**: 8.6.0
* **Electron Version**: 1.4.7
* **Target**: Windows x64 NSIS

After the build command finishes there is still a node.exe process that stays running for up to a few minutes after the build command has finished. This is causing occasional problems on our CI server if two jobs are kicked off in quick succession on the same build agent as the 2nd job won't be able to clean up app directory as it's still in use by a process from the previous build.

**Comment by develar** [comment]
Please try upcoming 10.2.0
