### ISSUE TITLE
asar problem, file not found

### ISSUE THREAD

**Issue by FTAndy** [electron-userland/electron-builder#929]
* **Version**: 7.15.2

* **Target**: all

When i run the local environment with `electron ./app/`, the font resource require fine.

But when i package for local operation system with `build --publish never`, and run the output file. The app can not find some font resource.

Which look like this in chrome dev tool
```
release/mac/gs-dagger.app/Contents/Resources/app/style/icon/iconfont.woff Failed to load resource: 
```
 I found that electron-builder use asar to pack and unpack the app file, so i check the file folder to find my font resource. I unpack file `release/mac/gs-dagger.app/Contents/Resources/app.asar` in that folder. Turn out my font file is in that folder.

```
$ asar e app.asar .
$ ls

// here is my font file
```

And what is more surprise me is that when I reopen my app in the release folder, **the app find the font resource**. Is there any trick to help me out here? I want my app to find the font resource without unpack the `asar` file.

**Comment by FTAndy** [comment]
i update the electron-builder version to 8.7.0, seems not working neither. @develar

**Comment by FTAndy** [comment]
@develar I fix this problem use config `extraResources`  to include my extra font resource in `package.json`. But the concept `files`, `extraResources`, `extraFiles`.

- files: files in the `Contents/Resources/app.asar`, which when open it in the operation system, files will be extracted and app can access them.
- extraResources: files in the `Contents/Resources`, which app can access them directlly.
- extraFiles: files in the `Contents`(Contents for MacOS, root directory for Linux/Windows), which app can access them directlly.

This can explain everything.

**Comment by develar** [comment]
And also now there is option `asarUnpack` ;)
