### ISSUE TITLE
How to use desktop option in build.linux.desktop 

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#931]
* **Version**: 
9.1.0

* **Target**: 
Linux

This might be a very silly question but I'm not able to get how to use [desktop](https://github.com/electron-userland/electron-builder/wiki/Options#buildlinux.desktop) option in my package.json -
```json
  "build": {
    "linux" : {
      "arch" : 64,
      "target" : ["deb", "AppImage"],
      "desktop": {
        "Icon": "build/icon.png",
        "Name": "Sample Application Name",
        "Comment": "A sample application",
        "Categories": "GNOME;GTK;Network;InstantMessaging"
        }
    }
  }
```

**Comment by jbleuzen** [comment]
I think you must point to a file...

**Comment by akashnimare** [comment]
@jbleuzen something like? - 
```json
  "build": {
    "linux" : {
      "target" : ["deb", "AppImage"],
      "desktop": "build/.desktop"
    }
  }
```

**Comment by jbleuzen** [comment]
Yep and you put the content you want in your file

**Comment by develar** [comment]
@jbleuzen @akashnimare 

1. No, you should not point to a file. https://github.com/electron-userland/electron-builder/issues/931#issue-191066175 is a correct variant. It is name to value map.

2. All mentioned fields should be defined using meta information. 

e.g. Icon — is already set.
`Name` — use productName if name is not suitable for you (e.g. contains space).
Comment — use description.
Categories — use packageCategory.


So, I don't see why  do you need to use desktop option.

I have added missed test — it works for me.

```json
    "build": {
      "linux": {
        "desktop": {
          "Terminal": "true",
        }
      }
    }
```

**Comment by jbleuzen** [comment]
So you cant use the desktop file to handle custom scheme on Linux ?
Thanks for the heads up

**Comment by develar** [comment]
@jbleuzen Why cannot? Just use `desktop` option as shown.

**Comment by akashnimare** [comment]
@develar thanks for the clarification 💃 . I don't need it, just wanted to explore that option 😄
