### ISSUE TITLE
MacOS Timestamps are incorrect after building

### ISSUE THREAD

**Issue by woomike** [electron-userland/electron-builder#932]
* **Version**: 7.21.0

* **Target**: MacOS

After copying the `.app` into my Applications folder from a `.dmg` the creation and modified timestamps are not the current date.  They are dated when I originally ran the build several weeks ago.  Deleting previous version of the app and dmg does not seem to fix the problem.  Is there a way to make the timestamp the current time when building the app?

**Comment by woomike** [comment]
I've updated to the newest 9.1.0 release and this issue seems to have been fixed. ❤️

**Comment by develar** [comment]
@woomike Yep, electorn-buidler constantly improving :)
