### ISSUE TITLE
App Icon missing(sometimes broken) in ubuntu dash after installation

### ISSUE THREAD

**Issue by karthikud** [electron-userland/electron-builder#935]
* **Version**: 8.6.0

* **Target**: deb

My target build is deb.After installation,the application icon doesn't appear(sometimes broken) in ubuntu dash.
After restarting unity or PC am able to see the app icon in dash

**Comment by karthikud** [comment]
fixed above issue by adding below code in after-install.tpl 
```
if hash desktop-file-install 2>/dev/null; then
 desktop-file-install /usr/share/applications/<%= executable %>.desktop
 fi
```

**Comment by develar** [comment]
Since we are going push AppImage and Snaps instead of deb, I am not going to investigate. Feel free to send PR.
