### ISSUE TITLE
NSIS Documentation

### ISSUE THREAD

**Issue by TakenPilot** [electron-userland/electron-builder#940]
* **Version**: >=9

* **Target**: Windows, MacOSX, Linux

Is there a place to see more documentation about the version of NSIS that this project is using?  I'm having trouble finding documentation about the latest NSIS in general.  There are plenty of docs about old versions it seems on the Internet, but I can't seem to find _the_ source of up-to-date NSIS information.

My project is [this](https://www.yhat.com/products/rodeo), and my goal is to change from Squirrel to NSIS.  (Squirrel's 15 second timeout for extra actions on install means I can't install python before the first-run of the app, and uninstalling the app is often inconsistent on slower computers about giving me time to remove the icons and registry keys I added to the system, which is inconsiderate.)

I also want to find a way to control the auto-update part of the app more, so that I can do extra actions.  All of these things require some kind of documentation, which I am really struggling to find.

Is there a link or location I can read about the version that electron-building is using?

**Comment by develar** [comment]
> about the version of NSIS that this project is using

Latest NSIS 3.0.

> There are plenty of docs about old versions it seems on the Internet

AFAIK, nsis 3 doesn't have a lot of breaking changes. Old info is still valid in most cases.

Please see https://github.com/electron-userland/electron-builder/wiki/NSIS about customisation.

> I also want to find a way to control the auto-update part of the app more, so that I can do extra actions. 

Please see source code of https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/NsisUpdater.ts

**Comment by develar** [comment]
Feel free to ask advice. As stated in the "Custom NSIS script", — "don't expect that your issue will be resolved" but will try to help.
