### ISSUE TITLE
Customize install directory name in NSIS oneClick mode

### ISSUE THREAD

**Issue by topmat** [electron-userland/electron-builder#941]
* **Version**: 9.2.0

* **Target**: Windows

I read the source code that related NSIS target. It used $(PRODUCT_FILENAME)\$(VERSION) as install path. The Squirrel.Windows is using app/package.json's name as directory. However my productName is non-ASCII name(ex: 大量刊登助手). My App have the other execution file that can't be running on the non-ASCII path in windows. Can you help me to customize the install directory name in NSIS oneClick mode? Or any workaround?

**Comment by develar** [comment]
Will be fixed in 2 days.

**Comment by topmat** [comment]
Thank you very much
