### ISSUE TITLE
install with AutoUpdate in existing application

### ISSUE THREAD

**Issue by Ludea** [electron-userland/electron-builder#946]
* **Version**:  9.1

* **Target**:  Windows x64

I can not integrate the AutoUpdate with my electron application.

Here attached, I have this error with "npm start".
I also add my package.json, tsconfig.js and update.ts
I don't inderstant what happen. I start development, all works fine.
I add electron-builder with autoupdate but it fails.

![error](https://cloud.githubusercontent.com/assets/2116692/20686369/ab149f90-b5b8-11e6-8999-0e757b870caa.png)

package.json :
`{
  "name": "Johnny-app",
  "version": "0.0.1",
  "description": "",
  "main": "app.js",
  "author": "Johnny",
  "scripts": {
       "start": "electron .",
       "pack": "build --dir",
       "dist": "build"
  },

  "build": {
  "appId": "your.id",
  "mac": {
    "category": "your.app.category.type"
  },
  "win": {
    "iconUrl": "(windows-only) https link to icon"
  }
},

  "dependencies": {
    "electron-auto-updater": "latest"
  },

  "devDependencies": {
    "electron": "latest",
    "electron-builder": "latest",
    "typescript" : "^2.0.10"
  }
}
`

tsconfig.json :
`{
  "compilerOptions":{
  "module" : "commonjs",
  "target" : "es6",
  "noImplicitAny" : true,
  "removeContents" : true,
  "outDir" : "out",
  "newLine" : "LF",
  "noResolve" : true,
  "noEmitOnError" : true,
  "inlineSources" : true,
  "sourceMap" : true,
  "noUnusedLocals" : true
},
"include" : [
  "node_modules/electron-auto-updater/out/*.d.ts" ,
  "src/*.ts",
  "typings/**/*.d.ts"
  ],
"exclude" :[
  ]
}`

/js/update.ts
`import {app, BrowserWindow as BrowserWindowElectron} from "electron";
import * as os from "os";
import {isDev, log} from "./util";
import {autoUpdater} from "electron-auto-updater";
import BrowserWindow = GitHubElectron.BrowserWindow

const UPDATE_SERVER_HOST = "test.org"

export default class AppUpdater {
constructor(window: BrowserWindow) {
  if (isDev()) {
    return
  }

  const platform = os.platform()
  if (platform === "linux") {
    return
  }

  const version = app.getVersion()
  autoUpdater.addListener("update-available", (event: any) => {
    log("A new update is available")
  })
  autoUpdater.addListener("update-downloaded", (event: any, releaseNotes: string, releaseName: string, releaseDate: string, updateURL: string) => {
    notify("A new update is ready to install", `Version ${releaseName} is downloaded and will be automatically installed on Quit`)
    log("quitAndInstall")
    autoUpdater.quitAndInstall()
    return true

  })
  autoUpdater.addListener("error", (error: any) => {
    log(error)
  })
  autoUpdater.addListener("checking-for-update", (event: any) => {
    log("checking-for-update")
  })
  autoUpdater.addListener("update-not-available", () => {
    log("update-not-available")
  })

  if (platform === "darwin") {
    autoUpdater.setFeedURL(`https://${UPDATE_SERVER_HOST}/update/${platform}_${os.arch()}/${version}`)
  }

  window.webContents.once("did-frame-finish-load", (event: any) => {
    autoUpdater.checkForUpdates()
  })
}
}

function notify(title: string, message: string) {
let windows = BrowserWindowElectron.getAllWindows()
if (windows.length == 0) {
  return
}

windows[0].webContents.send("notify", title, message)
}

`

**Comment by develar** [comment]
Please answer to my another questions in the email.

**Comment by Ludea** [comment]
Can I use the AutoUpdate module in Javascript instead of typescript ?

**Comment by develar** [comment]
Of course. Doesn't mater what language is used to implement electron-builder — it is compiled to JS in any case. I can even use Kotlin.
