### ISSUE TITLE
Path of update file from temporary directory

### ISSUE THREAD

**Issue by ipatina** [electron-userland/electron-builder#948]
* **Version**: 10.2.0

* **Target**: Windows 32/64 NSIS

I have to make progress bar to show downloading progress of update file (exe file from release server). But this file is in temporary directory with randomly generated name.
Is there any api method to get path of this file?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/529#issuecomment-263201920

Well, it is better to send PR if this functionality required for you soon. Or you can wait when it will be implemented by me.

**Comment by develar** [comment]
BTW — for what? Are you sure that this functionality is required for your users? Or download speed very bad?

**Comment by ipatina** [comment]
Yes, download speed is not good. User should understand what's going on with app.

**Comment by SxMShaDoW** [comment]
@develar - I think this is similar to the [request](https://github.com/electron-userland/electron-builder/issues/884#issuecomment-258641870). I don't think a "progress" bar is the _true_ need, but some sort of message, installer gif,  progress bar (even if its not accurate) for the user to understand "hey we are doing an update after we closed the app". This isn't an issue for Squirrel.mac because it relaunches the app super fast, but NSIS can take a long time to install the app (esp if asar isn't being used).

**Comment by develar** [comment]
> esp if asar isn't being used

You should use saar. And in a case of *** Windows I would say you must.

**Comment by develar** [comment]
> I think this is similar to the request.

@SxMShaDoW No. Your request is already implemented – if app installed not on quite, but on explicit exit, installer is not silent.

**Comment by SxMShaDoW** [comment]
@develar -  Thanks for clarifying that. will look into the code more to see what we are doing wrong then. 

As far as asar, I agree that we should use asar, we just haven't found a way to make my web pack config, asar, and modifying of local files all play nicely just yet. Would love to use asar but in my case, our application uses execSync to do operations on local machines, modifying files locally after pulling down from git, and probably more things I can't think of off the top of my head. What do you think is the best way to tackle troubleshooting/enabling asar compatibility?

**Comment by develar** [comment]
> What do you think is the best way to tackle troubleshooting/enabling asar compatibility?

https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md

"only execFile is supported to execute binaries inside asar archive."

Use asarUnpack to unpack all files that should be available externally.

> modifying files locally after pulling down from git

But not in the app directory, right?

**Comment by develar** [comment]
@SxMShaDoW Please ensure that you use latest version of electron-auto-updater `0.6.2`.

**Comment by develar** [comment]
Duplicates #958
