### ISSUE TITLE
ExtraResources doesn't copied when create NSIS installer 

### ISSUE THREAD

**Issue by topmat** [electron-userland/electron-builder#949]
* **Version**: 10.2.0

* **Target**: Windows

I have a directory and a file in ExtraResource. Ex: (server/apiserver-win32.exe) I found this file doesn't copy to NSIS installer after electron-builder>10.0.0. When I tried  electron-builder@9.2.0, it copied to right place and size is correct. The win32-ia32-unpacked has the file and size is correct. 

This is the file in "win32-ia32-unpacked"
![2016-11-30 12 07 12](https://cloud.githubusercontent.com/assets/7737138/20739650/9774e2f2-b6f7-11e6-8162-b47c93756630.png)

I used electron-builder@10.2.0 packed and install to target machine. The file size is 0.
![2016-11-30 12 08 01](https://cloud.githubusercontent.com/assets/7737138/20739662/a9ca3394-b6f7-11e6-92b8-74aa5b9bb0c6.png)

I tried again that used electron-builder@9.2.0 packed and install to target machine. The file size is correct. 
![2016-11-30 12 16 31](https://cloud.githubusercontent.com/assets/7737138/20739714/11e80e88-b6f8-11e6-94ef-c01f408d62d8.png)

**Comment by develar** [comment]
Do you build on a CI server? What is your host platform — Linux?

**Comment by topmat** [comment]
Yes, I'm building on a CI server. The build machine(slave) is Windows 8 - 64 bits.

**Comment by develar** [comment]
So, not clear for me. If you build on Windows it means that hard links are definitely not used. 

Could you please build on local linux/mac machine for windows? Does it work? 
Is it possible to provide project?

I cannot reproduce.

**Comment by topmat** [comment]
I found your release that tried to fix this. 
I'm debugging in the windows environment. 
The "isUseHardLink" is false and process.platform is win32. I think your logic is right. This is not HARD LINK issue.

May I have a question of this process? I found the resources/server/apiserver-win32.exe is copied into "win32-ia32-unpacked". However the 7z doesn't pack the file into target.  Is the 7z will pack all of file from "win32-ia32-unpacked" ? 

I will try to build on mac machine, Today. 

Thank you

**Comment by develar** [comment]
> Is the 7z will pack all of file from "win32-ia32-unpacked" ?

Yes, 7z just packs the whole directory (it is already filtered).

**Comment by develar** [comment]
Windows version? Do you use *** MS Defender antivirus? Another antivirus?

**Comment by topmat** [comment]
Windows Version: Windows 8 - 64 bits. 
No antivirtus. My MS Defender is enabled. Any impact on it?

**Comment by develar** [comment]
Please try to disable MS Defender (just to be sure, I see that you say that it works with v9 of electron-builder).

**Comment by topmat** [comment]
It's working. Great. 

Thank you very much.

**Comment by develar** [comment]
If you disable ** ** ** ** Defender?

**Comment by topmat** [comment]
yes. I disabled the Defender. The file(apiserver-win32.exe) will ziped into 7z file.
I still didn't know why.

**Comment by develar** [comment]
> I still didn't know why.

Because MS tools just suck.

**Comment by develar** [comment]
Maybe you can add your dist as ignored directory in the Defender settings (I don't know).
