### ISSUE TITLE
can't set specail codesign timestamp

### ISSUE THREAD

**Issue by hugohuang1111** [electron-userland/electron-builder#951]
* **Version**: v8.7.0

* **Target**: win

i set timestamp like follow:
```
{
....
  "build": {
    "win": {
      "rfc3161TimeStampServer": "http://timestamp.comodoca.com/authenticode"
    }
  }
....
}
```

but still use "http://timestamp.verisign.com/scripts/timstamp.dll" as timestamp

**Comment by develar** [comment]
`rfc3161TimeStampServer` sets only rfc3161 TimeStamp Server.

**Comment by develar** [comment]
`timeStampServer` option is added.

**Comment by develar** [comment]
FYI: rfc3161TimeStampServer  is used for`sha256`, timeStampServer is used for `sha1`.

**Comment by hugohuang1111** [comment]
got it, thank you.
