### ISSUE TITLE
build.fileAssociations icon links to original file in output

### ISSUE THREAD

**Issue by wuz23** [electron-userland/electron-builder#954]
* **Version**: 10.3.0

* **Target**: macOS 10.12

The Info.plist of the output bundle contains the absolute path to the build folder, not to icon in the bundle. In my case:
`<key>CFBundleTypeIconFile</key>`
`<string>/Users/***/projects/****/build/ext.icns</string>`

**Comment by develar** [comment]
Will be fixed tomorrow.

**Comment by wuz23** [comment]
Thank you very much! Now this works.
