### ISSUE TITLE
Use non-Apple certificate from keychain to sign win on mac

### ISSUE THREAD

**Issue by ivanovit** [electron-userland/electron-builder#957]
* **7.14.1**: 

* **win**

I want to build electron app for all platforms on **mac**. Can I use non-Apple cert imported in the keychain on MacOS to sign win app and what parameters should I pass?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

Or do you request feature — somehow grab cert from keepass?

**Comment by ivanovit** [comment]
Sorry, I mean certificate imported in the keychain on MacOS.

**Comment by develar** [comment]
You are not the first who asks about it. But you are first who created issue about. So, it will be fixed someday (because I hate *** windows, don't expect that it will be fixed soon).

In general, I recommend you to use CI server (https://www.appveyor.com) to build signed production ready dist.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
