### ISSUE TITLE
NSIS auto-update doesn't use system HTTP proxy

### ISSUE THREAD

**Issue by dbkr** [electron-userland/electron-builder#959]
* **Version**: 10.4.1
* **Target**: Windows (NSIS)

The NSIS auto-updater appears not to use a system HTTP proxy if Windows is set up with one and instead tries to connect to the update URL directly. On machines where the only web access is via the proxy, this means the app will just not update (even though the embedded chromium appears to use the proxy).

**Comment by develar** [comment]
Yes. We must not use node http API, but instead use chromium electron API.

**Comment by maczikasz** [comment]
So I spend some time looking into this feature and assuming you haven't started any work on this, I would propose and do the following:

- Consolidate all HTTP related requests behind a common interface (stuff from publish/restApiRequest and util/httpRequest
- and create a HTTP based implementation for this (for publishing and stuff done by the builder)
- and create an Electron NET api based implementation for the stuff done in AutoUpdater

So then this IF will have to be used by all Providers and Publishers

**Comment by develar** [comment]
Yes. Electron Chrome Network API mimics node, so should be easy to migrate existing helpers publish/restApiRequest and util/httpRequest.

**Comment by maczikasz** [comment]
Yes, my point was, that it should be done in a manner where it's possible to use normal HTTP, as net api requires app ready event, also when the app is building or the tests are running there is no electron app, I will create the PR either during the weekend or latest on monday

**Comment by maurovitale** [comment]
Hi to all,
my electron proxy setting doesn't work with AutoUpdater.  On the main process I have this configuration : 
      
```
session.defaultSession.setProxy({
    proxyRules : proxyString
 }, function () {
    console.log("proxy ok")
 });

```
This works in the entire electron app. I can see the logs on squid. AutoUpdater should use Electron Chrome Network API but in my case this not works, the method 'checkForUpdates' of AutoUpdater bypass the proxy. Is there something that I miss ?

**Comment by akioyamamoto1977** [comment]
I have same issue with maurovitale.
Is there any conclusion if there is a way to indicate a proxy server by program code ?

**Comment by akioyamamoto1977** [comment]
> I have same issue with maurovitale.
> Is there any conclusion if there is a way to indicate a proxy server by program code ?

Excuse me putting a comment on this closed issue but I found a  solution to indicate a default proxy (for Electron) from program code as below.

```
app.commandLine.appendSwitch('proxy-server', '127.0.0.1:2222');
```

**Comment by elonzh** [comment]
> > I have same issue with maurovitale.
> > Is there any conclusion if there is a way to indicate a proxy server by program code ?
> 
> Excuse me putting a comment on this closed issue but I found a solution to indicate a default proxy (for Electron) from program code as below.
> 
> ```
> app.commandLine.appendSwitch('proxy-server', '127.0.0.1:2222');
> ````

It doesn't work for me with electron-builder 22.8.1 and electron-updater 4.3.5

**Comment by MareikeTaeubner** [comment]
The updater seems to have its own netSession, so changes on `session.defaultSession` will not work.

This is entirely undocumented, so the API might not be stable or internal, but for now (electron-updater@4.3.9) the following works:

```
autoUpdater.netSession.setProxy({
      proxyRules: "http://localhost:3128",
});
```

If your proxy requires authentication you'll need something like this additionally:

```
autoUpdater.signals.login((_authInfo, callback) => {
  callback("username", "password");
});
```
