### ISSUE TITLE
Unable to package into all platform, process unable to finish

### ISSUE THREAD

**Issue by stephennyu** [electron-userland/electron-builder#960]
So here is my dev dependencies

```json
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.4",
    "babel-register": "^6.18.0",
    "cross-env": "^3.1.3",
    "css-loader": "^0.23.1",
    "electron-builder": "^10.4.1",
    "electron-packager": "^5.2.1",
    "electron-prebuilt": "^0.37.8",
    "electron-rebuild": "^1.1.3",
    "electron-winstaller": "^2.4.1",
    "json-loader": "^0.5.4",
    "less": "^2.6.1",
    "less-loader": "^2.2.2",
    "minimist": "^1.2.0",
    "node-libs-browser": "^1.0.0",
    "react": "^0.14.8",
    "react-dom": "^0.14.8",
    "redux-devtools": "^3.3.1",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.3"
  }
```

So the main problem is I am running on Mac OSX and would like to package my electron app to Mac, WIndows, and Linux.

I am able to package it into mac os however things get weird when the process is running for packaging linux or windows.

> Here is the log
> 
> Skip app dependencies rebuild because platform is different
> Packaging for linux x64 using electron 0.37.8 to dist/linux-unpacked
> ⚠️  Application icon is not set, default Electron icon will be used
> 
> ... and 1 more

The problem is that the process is unable to stop and keeps like that even when I have click on ctrl +C , I just can't stop the process unless using a force method.
Kindly need your help

**Comment by develar** [comment]
> 0.37.8

Please use latest electron version.

Please specify electron-builder version.

Is it full log? Please set env `DEBUG=electron-builder`

**Comment by stephennyu** [comment]
okay, I got it, it was due to my electron version is not the most updated one.

I solved this by adding electron in devDependencies
