### ISSUE TITLE
issue at start after packaging

### ISSUE THREAD

**Issue by Ludea** [electron-userland/electron-builder#963]
* **Version**:  9.3

* **Target**:  Debian x64

I use electron-builder for build and package application for Debian x64.
all fines until I launch my application.
#./myapp give me an error :
`ENOTDIR : not a directory, uv_chdir`

**Comment by develar** [comment]
Please provide your deb to test.

**Comment by Ludea** [comment]
https://drive.google.com/file/d/0B0ton0VHwDPiMGJJamZhVXJGa0k/view?usp=drivesdk

There is all outputs

**Comment by develar** [comment]
@Ludea Attached dist contains AppImage, not deb. Please reopen if issue is still actual for you.
