### ISSUE TITLE
Customize icon for NSIS and/or Squirrel.Windows installers

### ISSUE THREAD

**Issue by unindented** [electron-userland/electron-builder#964]
* **Version**: 10.4.1

* **Target**: nsis and squirrelWindows

Is it possible to customize the icon for the NSIS and/or Squirrel.Windows installers, so that they are different from the app icon? I basically want the installer to have a cardboard box icon, and then the app executable to have my product's logo. If both executables have the same icon, I fear my users will be confused...

If it's not currently possible, how hard would it be to support it? I will create the PR myself if you give me some guidance.

**Comment by develar** [comment]
Squirrel.Windows is deprecated and not recommended. I will talk here only about NSIS.

NSIS — not possible currently. If you want to make PR — cool. Please see https://github.com/electron-userland/electron-builder/blob/master/src/targets/nsis.ts#L88 

You need to introduce some option (`installerIcon` ?, add it to winOptions.ts) and then check it

```
await packager.getResource(this.options.installerIcon, "installerIcon.ico")
```

i.e. user can just put file `installerIcon.ico` to build resources to override default installer icon.

If result is null, then use `await packager.getIconPath()` (as it is implemented now).

**Comment by unindented** [comment]
Haha you really hate Squirrel.Windows, why is that?

Ok, I'll try to find time this weekend to implement the `installerIcon` option for NSIS.

**Comment by develar** [comment]
> Haha you really hate Squirrel.Windows, why is that?

I hate only Windows. Not Squirrel.Windows. As author of open-source project, I found NSIS solution more suitable for all users needs. Please use search to find issues about this decision.

I don't say that PR for Squirrel.Windows will be not accepted — you are welcome.

**Comment by AmpersandGD** [comment]
But why is Squirrel.windows unsupported? I want to add an icon to my app, but I can't install electron-builder because of this.
