### ISSUE TITLE
Build doesn't work.. do you really need to download electron if I  installed it

### ISSUE THREAD

**Issue by notanark** [electron-userland/electron-builder#967]
lastest

windows

build --w --x64 app
Packaging for win32 x64 using electron 1 to dist\win-unpacked
Downloading tmp-11872-0-electron-v1-win32-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v1/electron-v1-win32-x64.zip returned 404
Error: Failed to find Electron v1 for win32-x64 at https://github.com/electron/electron/releases/download/v1/electron-v1-win32-x64.zip

**Comment by develar** [comment]
How is specified electron version in the package.json?

**Comment by notanark** [comment]
Hi I am using skeletron starter kit here is my package.json


{
  "name": "SkelEktron",
  "productName": "SkelEktron",
  "description": "Electron Template Desktop Application",
  "version": "0.0.6",
  "homepage": "https://github.com/BZCoding/SkelEktron",
  "author": {
    "name": "BZ Coding",
    "email": "hello@bzcoding.com",
    "url": "https://bzcoding.com/"
  },
  "license": "MIT",
  "main": "main.js",
  "electronVersion": "1.0.0",
  "dependencies": {
    "devtron": "^1",
    "electron-debug": "^1",
    "electron-is-dev": "^0.1",
    "electron-window-state": "^3",
    "lodash": "^4"
  },
  "config": {
    "url": "index.html",
    "update": {
      "url": false
    }
  }
}


please guide me sempai

**Comment by develar** [comment]
`electronVersion` must be in the `build`. And please set it to latest `1.4.10`.

`"build": { "electronVersion": "1.4.10" } `

**Comment by notanark** [comment]
much obliged, testing now
Packaging for win32 x64 using electron 1.4.10 to dist\win-unpacked
seems to be working. Will reply if not. Otherwise thank you and close in 24h
