### ISSUE TITLE
building snap fails

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#968]
1.4.10

snap

`Building Snap for arch ia32
Error: docker exited with code 1
Output:
NODE_VERSION=7.2.0
HOSTNAME=7cd2c363f48b
XZ_VERSION=5.2.2
LC_ALL=en_US.UTF-8
PATH=/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/out/linux-unpacked-snap
LANG=en_US.UTF-8
FORCE_COLOR=true
USE_SYSTEM_7ZA=true
DEBUG_COLORS=true
SHLVL=1
HOME=/root
LANGUAGE=en_US:en
no_proxy=*.local, 169.254/16
_=/usr/bin/env
Preparing to pull desktop-glib-only 
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/main Sources [1,103 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [5,179 B]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9,802 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [264 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [1,872 B]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [137 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [555 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [11.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [459 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-security/main Sources [62.9 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-security/restricted Sources [1,872 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial-security/universe Sources [15.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [232 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [11.7 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [76.9 kB]
Fetched 24.6 MB in 6s (915 kB/s)
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 gcc-6-base amd64 6.0.1-0ubuntu1 [14.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libffi6 amd64 3.2.1-4 [17.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libelf1 amd64 0.165-3ubuntu1 [42.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libglib2.0-0 amd64 2.48.1-1~ubuntu16.04.1 [1,118 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libglib2.0-data all 2.48.1-1~ubuntu16.04.1 [132 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libglib2.0-bin amd64 2.48.1-1~ubuntu16.04.1 [39.4 kB]
Fetched 1,364 kB in 0s (0 B/s)
Pulling desktop-glib-only 
'app' has prerequisites that need to be staged: desktop-glib-only
Preparing to build desktop-glib-only 
Building desktop-glib-only 
make -j4
make install DESTDIR=/out/linux-unpacked-snap/parts/desktop-glib-only/install
install -D -m755 desktop-launch /out/linux-unpacked-snap/parts/desktop-glib-only/install/bin/desktop-launch
Staging desktop-glib-only 

Error output:
Unable to find image 'electronuserland/electron-builder:latest' locally
latest: Pulling from electronuserland/electron-builder
aed15891ba52: Pulling fs layer
773ae8583d14: Pulling fs layer
d1d48771f782: Pulling fs layer
cd3d6cd6c0cf: Pulling fs layer
8ff6f8a9120c: Pulling fs layer
1ccb97d77c06: Pulling fs layer
2f99ab97e4d6: Pulling fs layer
5062fa682504: Pulling fs layer
2391f7a42cae: Pulling fs layer
378129a84a19: Pulling fs layer
0e500e2615d3: Pulling fs layer
cd3d6cd6c0cf: Waiting
8ff6f8a9120c: Waiting
1ccb97d77c06: Waiting
2f99ab97e4d6: Waiting
5062fa682504: Waiting
2391f7a42cae: Waiting
378129a84a19: Waiting
0e500e2615d3: Waiting
a9c2cceee84a: Pulling fs layer
a9c2cceee84a: Waiting
d1d48771f782: Verifying Checksum
d1d48771f782: Download complete
cd3d6cd6c0cf: Verifying Checksum
cd3d6cd6c0cf: Download complete
8ff6f8a9120c: Verifying Checksum
8ff6f8a9120c: Download complete
aed15891ba52: Verifying Checksum
aed15891ba52: Download complete
5062fa682504: Verifying Checksum
5062fa682504: Download complete
1ccb97d77c06: Verifying Checksum
1ccb97d77c06: Download complete
2391f7a42cae: Verifying Checksum
2391f7a42cae: Download complete
378129a84a19: Verifying Checksum
378129a84a19: Download complete
aed15891ba52: Pull complete
0e500e2615d3: Verifying Checksum
0e500e2615d3: Download complete
a9c2cceee84a: Verifying Checksum
a9c2cceee84a: Download complete
2f99ab97e4d6: Verifying Checksum
2f99ab97e4d6: Download complete
773ae8583d14: Pull complete
d1d48771f782: Pull complete
cd3d6cd6c0cf: Pull complete
8ff6f8a9120c: Pull complete
1ccb97d77c06: Pull complete
2f99ab97e4d6: Pull complete
5062fa682504: Pull complete
2391f7a42cae: Pull complete
378129a84a19: Pull complete
0e500e2615d3: Pull complete
a9c2cceee84a: Pull complete
Status: Downloaded newer image for electronuserland/electron-builder:latest
Cloning into '/out/linux-unpacked-snap/parts/desktop-glib-only/src'...
Downloading parts list|                                                        
'/out/linux-unpacked-snap/parts/desktop-glib-only/install/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0' and '/out/linux-unpacked-snap/stage/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0' are the same file

    at ChildProcess.childProcess.once.code (/Users/atypical/IOTA/node_modules/electron-builder/src/util/util.ts:135:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
From previous event:
    at spawn (/Users/atypical/IOTA/node_modules/electron-builder/src/util/util.ts:98:3)
    at /Users/atypical/IOTA/node_modules/electron-builder/src/targets/snap.ts:84:7
    at next (native)
    at /Users/atypical/IOTA/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/atypical/IOTA/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at SnapTarget.build (/Users/atypical/IOTA/node_modules/electron-builder/out/targets/snap.js:141:11)
    at postAsyncTasks.push.default.map.it (/Users/atypical/IOTA/node_modules/electron-builder/src/platformPackager.ts:163:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/atypical/IOTA/node_modules/electron-builder/src/platformPackager.ts:163:41)
    at /Users/atypical/IOTA/node_modules/electron-builder/src/platformPackager.ts:159:10
From previous event:
    at LinuxPackager.pack (/Users/atypical/IOTA/node_modules/electron-builder/out/platformPackager.js:219:11)
    at /Users/atypical/IOTA/node_modules/electron-builder/src/packager.ts:132:22
From previous event:
    at Packager.doBuild (/Users/atypical/IOTA/node_modules/electron-builder/out/packager.js:260:11)
    at /Users/atypical/IOTA/node_modules/electron-builder/src/packager.ts:100:38
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Packager.build (/Users/atypical/IOTA/node_modules/electron-builder/out/packager.js:212:11)
    at /Users/atypical/IOTA/node_modules/electron-builder/src/builder.ts:241:40
    at next (native)
From previous event:
    at build (/Users/atypical/IOTA/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/Users/atypical/IOTA/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by develar** [comment]
#509 is not yet done. But it seems your issue is different — do you build it on Linux? Only Linux is supported currently.

**Comment by atypicalprogrammer** [comment]
Ah sorry, please adjust the options wiki page then as that is where I read about snap as an available distro. I tried to build on mac.

**Comment by develar** [comment]
> . I tried to build on mac.

Definitely it will be supported. But as snaps is a far from ideal I cannot fix it yet.
