### ISSUE TITLE
NSIS: Distinguish between first start and update 

### ISSUE THREAD

**Issue by maczikasz** [electron-userland/electron-builder#970]
* **Version**:  8.6.0

* **Target**:  Win x64

Is it possible to have Squirrel like events when using NSIS target from the auto updater? 

I would like to show a different messages when the app was auto updated and when it was installed the first time.

Thanks

**Comment by develar** [comment]
Yes, it is possible.

**Comment by maczikasz** [comment]
I will create a PR for this then, I'll post my solution idea here first so you can agree or disagree if it fits your code/thinking

**Comment by develar** [comment]
@maczikasz Solution is easy —
1. pass special param to installer (https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/NsisUpdater.ts#L148)
2. Handle param when https://github.com/electron-userland/electron-builder/blob/master/templates/nsis/oneClick.nsh#L4

**Comment by maczikasz** [comment]
That's much easier than what I had in mind, thanks,

will get you the PR today tomorrow
