### ISSUE TITLE
Multiple package.json files?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#971]
I have a use case where I want to build two version of the app. 

1 for a testnet release 
1 for mainnet release

The only difference between these is : 

- github publication URL
- app name
- app id
- different extraResources

The code itself is the same.

What would be the best way to accomplish this? Can we have different package.json files ? For example package.testnet.json etc?

**Comment by develar** [comment]
Related #639

Not closed as duplicated — I want to implement config files in YAML.

**Comment by develar** [comment]
Closed in favour of #1109
