### ISSUE TITLE
Request for NSIS Updater API to Start Downloading

### ISSUE THREAD

**Issue by evshiron** [electron-userland/electron-builder#972]
* **Version**: 10.5.0

* **Target**: win32 ia32

Greetings,

I really appreciate it if there is an API to start downloading updates rather than the current all-in-one check-and-download `autoUpdater.checkForUpdates` function.

What I want is something like this:

```javascript
autoUpdater.autoDownload = false;
autoUpdater.on('update-available', () => {
    if(confirm('New version is available, download now?')) {
        autoUpdater.on('update-downloaded', () => {
            if(confirm('New version is downloaded, quit and install now?')) {
                autoUpdater.quitAndInstall();
            }
        });
        autoUpdater.download();
    }
});
autoUpdater.checkForUpdates();
```

I can do and PR it but I want to know if it comforts you so feel free to discuss. Thanks.

**Comment by develar** [comment]
There is a plan to merge electron-simple-updater into the electorn-updater (https://github.com/electron-userland/electron-builder/tree/master/nsis-auto-updater).

If you want to help — cool.

What I suggest:

* add method https://github.com/megahertz/electron-simple-updater#setoptionsname-value

* change our impl of https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/NsisUpdater.ts#L67 (doCheckForUpdates) to respect new option `autoDownload`

* add method https://github.com/megahertz/electron-simple-updater#downloadupdate

**Comment by develar** [comment]
Issue is not closed as backlog because if no one will send PR, it will be implemented by my next or this month.

**Comment by evshiron** [comment]
Is `electron-auto-updater` supposed to provide the same API as Electron's Auto Updater?

According to [/nsis-auto-updater/src/main.ts#L2](https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/main.ts#L2), original Auto Updater is used when the platform is not `win32`, and the call to the to-be-added `autoUpdater.setOptions` function will fail.

That's why I was using `autoUpdater.autoDownload = false`.

And does the plan to merge `electron-simple-updater` imply that there will be changes to `latest.yml` and `app-update.yml`, for example, use `updates.json` instead?

**Comment by develar** [comment]
Yes, we must provide the same API as electron. But we can extend it. Users are informed that extended API currently available only for Windows.

Your suggestion to use simple property autoDownload is reasonable, no need to use options objects, 👍 

No — latest and app-update.yml are not going to be changed. We will (or you help) grab ideas, but no exact implementation (because electron-builder can simplify some aspects).

**Comment by develar** [comment]
BTW — consider to use promise based API instead of event based.

**Comment by evshiron** [comment]
I did it partially in evshiron/electron-builder@2416af8 but found it hard to try on a test case. Could you give me some suggestion?

**Comment by develar** [comment]
Please see test "file url generic" https://github.com/electron-userland/electron-builder/blob/master/test/src/nsisUpdaterTest.ts#L77

Test plan:
* should be not event "update-downloaded"
* updateCheckResult.downloadPromise should be null

**Comment by evshiron** [comment]
No idea on how tests work :(

Can you test my fork and see if it works?

**Comment by develar** [comment]
@evshiron Will do soon. Thanks for your work.

**Comment by develar** [comment]
0.8.3 published. Thanks for PR.
