### ISSUE TITLE
NSIS auto-update error

### ISSUE THREAD

**Issue by cumajkeee** [electron-userland/electron-builder#973]
* **Version**: 10.4.0

* **Target**: Windows

I'm a bit confused with auto-updates with NSIS So far I'm switching from squirrel to nsis, and was lucky to made build process work but auto updates seems to not working.

I'm using "generic" server. 
Set autoUpdater.setFeedURL({
    provider: 'generic',
    url: 'https://blablabla/updates/${platform}/${version}
});

And got following error during updating app

Error Downloading Update: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-x64\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

Probably missed something?
Thanks in advance!

**Comment by develar** [comment]
Please try to add port number to url. `:443`

**Comment by cumajkeee** [comment]
@develar, same result. It's required to have .yml file?

**Comment by develar** [comment]
Maybe. Need to investigate. Why do you need to explicitly call `setFeedURL`?

**Comment by cumajkeee** [comment]
@develar cause beside I use generic server, it can be different depends on rules. And I'll get exact url only when app is opened.

**Comment by cumajkeee** [comment]
@develar does mac auto-update will still support new notation of setFeedURL I mentioned before?

**Comment by develar** [comment]
@cumajkeee No. Supported only on Windows.

**Comment by develar** [comment]
Please set DEBUG=electron-builder env for your electron app to see all http requests (and cli switch `--enable-logging` (https://github.com/electron/electron/issues/3032)).

**Comment by cumajkeee** [comment]
Didn't get about DEBUG=electron-builder, what do you mean?

**Comment by develar** [comment]
To debug, you can set env var `DEBUG` to `electron-builder`. In this case all http requests will be printed to console.

**Comment by cumajkeee** [comment]
Ok, BTW, seems that it missing .yml file.

**Comment by cumajkeee** [comment]
@develar For NSIS auto-updates with generic server needs:
1. On client: app-update.yml (should be created manually, in generic case)
2. On server latest.yml (should be also created manually) and the installer-version.exe

Am I right?

That mean that update url is kinda hardcoded. Any workaround to support multiple update severs?

**Comment by develar** [comment]
`setFeedURL` should work. "seems that it missing .yml file" I think, you can ignore this error (will be fixed). So, I want to see debug logs to see all http requests. Maybe in this case I can advice you something. Otherwise it can took several days until I will investigate issue using test app.

**Comment by cumajkeee** [comment]
script "SET DEBUG=electron-builder && electron ./app --enable-logging" printed other errors but no one request, something wrong with script or it broken even before requests send?

**Comment by cumajkeee** [comment]
Hi @develar, have no luck with establish debug to see http requests, could you please take a look on setup script in comment above, does it supposed to do the magic? thanks.

**Comment by develar** [comment]
> does it supposed to do the magic

Yes, looks correct. 

I will investigate your issue till next monday. I am sorry, but quite busy now.

**Comment by cumajkeee** [comment]
@develar, thanks, feel free to write me if I can help you somehow.

**Comment by cumajkeee** [comment]
Hi @develar, did you have a chance to look on my issue?

**Comment by develar** [comment]
electron-auto-updater 0.7.1 doesn't load default update configuration only if custom was not set. So, error "missing .yml file" is fixed.

Other aspect of this issue I didn't yet investigate. 

`https://blablabla/updates/${platform}/${version}`

Please note — url must be base url for all files — i.e. `https://blablabla/updates/${platform}/${version}` must be a directory and contain both `update.yml` and setup exe.

**Comment by cumajkeee** [comment]
Yes, it is. What server supposed to return for such request? Is it enough to return:
`{url: https://blablabla/updates/win/AppName 1.0.0.exe}`

**Comment by cumajkeee** [comment]
BTW, how I got error: Error Downloading Update: Error: socket hang up

**Comment by cumajkeee** [comment]
@develar, is it required to sign application for windows? any workaround to not use signing?

**Comment by develar** [comment]
> What server supposed to return for such request?

We just request `latest.yml` (where `latest` is the name channel) and setup exe (file url specified in the `latest.yml`)

>  where I can take update.yml?

Sorry, not `update.yml`, but `latest.yml`.
Generated by electorn-builder. Please see https://github.com/ArekSredzki/electron-release-server/issues/87#issuecomment-261600371

> Is it required to sign application for windows?

No.

**Comment by cumajkeee** [comment]
@develar, we got latest.yml, but with it faced issue similar to this one https://github.com/electron-userland/electron-builder/issues/291

**Comment by develar** [comment]
Definitely something wrong with your server. Please try to use Amazon S3.
