### ISSUE TITLE
node http timeout when run from compiled electron, but works fine with run with electron .

### ISSUE THREAD

**Issue by openhardwarecoza** [electron-userland/electron-builder#974]
* **Version**:  1.4.1

* **Target**:  Win64

Hi 

Source code: https://github.com/LaserWeb/LaserWeb3-Electron/blob/master/server.js

1)  This a simple websocket server which uses node-static to serve some content

2)  Under electron, if the app is run from 'electron . ' (using npm script here https://github.com/LaserWeb/LaserWeb3-Electron/blob/master/package.json#L40)  then the application comes up in electron, and as I want it, also listens on port 8000, and I can access the interface from a browser too (the purpose here is despite the local electron window, someone may want to access the interface from a different room over network)

3) Once built using my npm script https://github.com/LaserWeb/LaserWeb3-Electron/blob/master/package.json#L42  however, the exe installed, and run: 
3.1) Electron window comes up as expected
3.2) but accessing localhost:8000 in a browser just sits there for a couple minutes, eventually times out

The only difference being that it doesnt work after being built

Note:  I am quite open to the mistake being in my code too:

Electron section: https://github.com/LaserWeb/LaserWeb3-Electron/blob/master/server.js#L555-L612
http/node-static section:  https://github.com/LaserWeb/LaserWeb3-Electron/blob/master/server.js#L70-L100

**Comment by develar** [comment]
Does setting `build.asar` to `false` help you?

`"build": {"asar": false}`

**Comment by openhardwarecoza** [comment]
Perfectly so (:

So, researched a little, thats because node-static/http cannot read from
the ASAR archive, correct?

So in this case, fine to ignore `Warning: Packaging using asar archive is
disabled — it is strongly not recommended. Please enable asar and use
asarUnpack to unpack files that must be externally available.` ?

Any impact on future plans with auto updating etc?

(Or is there an electron capable alternative to node-static/http)

**Comment by openhardwarecoza** [comment]
Just peaking in to see if you had any luck tracing down this issue yet?

**Comment by develar** [comment]
@openhardwarecoza No. Sorry. Have you identified the issue?

**Comment by openhardwarecoza** [comment]
No still not resolved,  and we do still need this resolved

**Comment by openhardwarecoza** [comment]
Well, its finally resolved (: 
Didnt change anything on our side related to this, but now, it just works (: 
Yay, we can close this one

I suspect it got fixed in one of the depencies
