### ISSUE TITLE
Feature request: Force application signing

### ISSUE THREAD

**Issue by tarjei** [electron-userland/electron-builder#975]
* **Version**: 9.2.0 

* **Target**: windows/osx

It would be great to have a command line switch that fails the build if application signing fails. This could catch a lot of setup errors faster and better that other methods.

**Comment by develar** [comment]
Not clear for what do you mean — if app cannot be signed — will be a build error.

**Comment by tarjei** [comment]
Are you sure?

I had a script running that I expected should sign the app - but it didn't happen:

```
CSC_IDENTITY_AUTO_DISCOVERY=false
+ CSC_LINK=file://../certificates/comodo.p12
+ '[' '!' -f /home/tarjei/ask/core/offline/electron/bin/../comodo.p12.password ']'
++ cat /home/tarjei/ask/core/offline/electron/bin/../comodo.p12.password
+ CSC_KEY_PASSWORD=****
+ /home/tarjei/ask/core/offline/electron/bin/../node_modules/.bin/build -w
Skip app dependencies rebuild because platform is different
⚠️  "electron-squirrel-startup" dependency is not required for NSIS
Packaging for win32 x64 using electron 1.4.10 to dist/win-unpacked
Packaging NSIS installer for arch x64
Building NSIS installer
```

Here, I suspect the CSC_LINK is wrong or somehow not found in the environment variables of the app. I want a commandline option that says "if signing fails or is not enabled (by lack of env vars) then fail".

T

**Comment by develar** [comment]
@tarjei It is already fixed, please try 10.5.0

**Comment by tarjei** [comment]
How is it fixed? 

I.e. I managed to create a signed build with 9.2.0 as well. What I want is a surefire way to ensure that signing happens.

**Comment by tarjei** [comment]
I updated the title to better reflect what I'm looking for.

**Comment by develar** [comment]
> How is it fixed?

We check that file exists. Please try.

> What I want is a surefire way to ensure that signing happens.

Do you mean that you want to enable some mode, in which app must be or signed, or build failed? To ensure, that even if you forget to define CSC_LINK, you will be aware because CI will be broken?

**Comment by develar** [comment]
I think, you want not CLI switch, but `build.forceCodeSigning` to avoid repeat such CLI flag in all build (i.e. the same for macOS).

**Comment by tarjei** [comment]
Yes!
