### ISSUE TITLE
Builder is exluding some files

### ISSUE THREAD

**Issue by notanark** [electron-userland/electron-builder#980]
* **Version**:  10.06

* **Target**:  Windows

It's missing some files when I install. One folder filled with javascript 

js/controllers/b  

is missing

**Comment by develar** [comment]
Please attach sample project to reproduce. Please try to disable *** MS Defender if you use it.

**Comment by notanark** [comment]
I emptied the dist folder and it worked. Just to note I do use comodo sandbox.

**Comment by notanark** [comment]
It's probably more to do with my security settings and not your software.

**Comment by develar** [comment]
Closed since Windows s****.
