### ISSUE TITLE
Build and sign application

### ISSUE THREAD

**Issue by stephennyu** [electron-userland/electron-builder#981]
Hello,

I got a problem and I can't figure out how can I sign my application ?
I am able to build and package my electron application into OSX and Windows, however I just can't figure out how to sign them.

Is the code sign a prerequisite for an auto-update feature ? Do I need a valid certificate in order to sign the application ? Or can I use a self-signed certificate ?

Thank you

**Comment by develar** [comment]
You cannot use self-signed certificate.

Your app must be signed for an auto-update feature on macOS and should be signed on Windows.

Please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing https://startssl.com/Support?v=34
