### ISSUE TITLE
electron-auto-updater dependency

### ISSUE THREAD

**Issue by giacgbj** [electron-userland/electron-builder#984]
* **Version**: 10.6.0

* **Target**: dmg, zip, nsis, AppImage. I'm building on a Mac.

According to [Auto Update guide](https://github.com/electron-userland/electron-builder/wiki/Auto-Update) you just have to add electron-auto-updater as app dependency.

When I execute tsc the result is:

> src/AppUpdater.ts(5,27): error TS2307: Cannot find module 'electron-auto-updater'.

To fix this issue I had to add to tsconfig.json:

```
"include": [
     [OMISSIS]
     "node_modules/electron-auto-updater/out/*.d.ts"
 ]
```

Is it the expected behavior?

**Comment by develar** [comment]
Is `electron-auto-updater` in your app dependencies (not in the devDependencies)?

**Comment by giacgbj** [comment]
Yes it is.
I just lookead at your project and you are doing the same https://github.com/develar/onshape-desktop-shell/blob/master/tsconfig.json :D

**Comment by develar** [comment]
Do you use 1 package.json structure? It is recommended now.

**Comment by giacgbj** [comment]
Yes, I do.

**Comment by develar** [comment]
Please specify your TS version. Or attach sample project. As you see, it works in my project;)

**Comment by giacgbj** [comment]
As I said it works in mine too, but I asked you if it's the expected behavior because it's the only dependency i have to explicitly declare in TS.

**Comment by develar** [comment]
Ouch, I missed it. Well, typing is specified, https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/package.json#L24 but TS doesn't support it correctly. In all my TS projects auto discovery of typing doesn't work and typings explicitly specified.
