### ISSUE TITLE
Updater: NSIS Low Disk Space not correctly handled

### ISSUE THREAD

**Issue by McPo** [electron-userland/electron-builder#985]
10.5.0

NSIS

Installed on Windows 10 x64 machine. Everything worked as expected.
Proceeded to download Update. Everything worked as expected.

Repeated the above steps, and noticed various issues.

During installation
```
Extract: error writing to file
Local\Temp\nsw3A35.tmp\app-32.7z
```

```
Extract: error writing to file
Uninstall SaltIM.exe
```

When executing the installed application (No issue was raised during the installation, silently fails to install)
`node.dll is either not designed to run on windows or it contains an error`
`This app cant't run on your PC`
I also noticed that the application icon would be blank, or a screen like icon.

Tried numerous times, rebooted etc.
At one point managed to get it to install again, but when it went to install the update, it wouldn't open again.

Noticed I only had 277MB free space, when nothing was installed and 70MB when the application had been installed (ie, no wonder updates broke).

Free'd up 500MB and installed the application again, the update also succeeded. 

However when I uninstalled the application and rebooted I only had 20MB left. I assume something is downloading a large update, but the point is, running out of Hard drive space is a common scenario with such things running in the background.

The installer should check that there is enough free space available + more, and warn the user.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.

**Comment by oboshto** [comment]
still relevant on update.

versions:
```
"electron-builder": "24.6.4",
"electron-updater": "6.1.1"
```
