### ISSUE TITLE
appx - wrong icon / how to set assets

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#987]
* **Version**: 10.6.1

* **Target**: appx (32/64)

When building for windows store the `icon.ico` isn't used in a couple places. E. g. the installed software list shows a default electron icon. Start menu as well.
I found those default icons in `assets`. I haven't yet figured out how to use my own icon for those assets.

**Comment by develar** [comment]
If you can and want — please file PR.

**Comment by black-snow** [comment]
Will try, guess I'll have to start here https://github.com/electron-userland/electron-builder/blob/master/src/targets/appx.ts#L49

**Comment by develar** [comment]
@black-snow Ouch, sorry, it is already implemented :) Just put `44x44.png` and other such files into your build resources directory.

**Comment by black-snow** [comment]
@develar You sure? I put `myappname.44x44.png` and the others (50x50, ...) into my `build` folder but it's still using the default ones.

**Comment by develar** [comment]
> ah wait, I must leave out the app name, right?

Yes. Only size.

**Comment by black-snow** [comment]
Alright, that works. Some quirks, though.

* Install Screen (dbl click appx) - image is blurry (upscaled)
* Start Menu & Task Bar - icon just looks weird ![Image of Taskbar](http://www.black-snow.net/tmp/weird_taskbar.png)

Sources look okay, though. The images in `pre-appx--ia32` are just fine and the manifest seems okay ...

**Comment by develar** [comment]
> Fo AppX sha256 is always used.

Thanks, fixed.

> Where does the Square150x150Logo etc. in the manifest come from? I

I don't know. To investigate.

@black-snow  Would you like to help and fix this issue?

**Comment by black-snow** [comment]
@develar of course. At first I'll unpack the appx and stuff all the assets in there that a VS plugin generated for me. Will report back.

**Comment by black-snow** [comment]
Also there's some manual steps that have to be done in order to publish the appx in the Windows Store. Maybe we can automate these, too. There's four fields in the manifest that need to be set:

* Package.Identity.Name
* Package.Identitiy.Publisher
* Package.Properties.DisplayName
* Package.Properties.PublisherDisplayName

Publisher is already correctly set (CN=...). PublisherDisplayName was correct in my case, too. There might be cases where someone needs to set a different one. I'd say we add an option for each of the remaining three fields. Maybe `.build.win.appx.identitiy.name` (default author.display name without whitespaces), `.build.win.appx.properties.displayName` (default productName) and `.build.win.appx.properties.publisherDisplayName` (default author)?

@develar Shall I open a new issue? Option names okay? I would try to file a PR for this. Doc would also need an update of course.

I haven't fixed the asset thing yet.

**Comment by develar** [comment]
> Shall I open a new issue? Option names okay?

👍 Also, I think, it makes sense to allow any extra properties in the `.build.win.appx.properties` — just add it to resulting xml as is.

**Comment by black-snow** [comment]
For the icons here's what I had to (thanks to Matteo Pagani from Microsoft):

For the assets:
* get the [VS plugin](https://visualstudiogallery.msdn.microsoft.com/09611e90-f3e8-44b7-9c83-18dba8275bb2)
* create a new universal project in VS 2015
* remove the existing assets
* drop your own icon into assets (400x400 or bigger)
* rightclick your icon, select generate assets

If you have your assets:
* unpack the electron-builder-generated appx
* copy your own assets into the unpacked assets folder
* edit the manifest: 
* * set Applications.Application.VisualElements.BackgroundColor to `transparent`
* * set Applications.Application.VisualElements.Square150x150Logo to `assets\Square150x150Logo.png`
* * Square44x44 and Wide310x150 analogue
* * set Properties.Logo to `assets\NewStoreLogo.png`
* now open the VS2015 native cmd (x86 for 32bit / x64 for 64bit)
* navigate to the unpacked files
* run `makepri createconfig /cf priconfig.xml /dq en-US /pv 10.0.0` (for win10)
* run `makepri new /pr . /cf priconfig.xml`
* `cd ..`
* run `makeappx pack -d ".\your_unpacked_files" -p "name_of_the_appx.appx" -l
* and optionally sign `signtool.exe sign -f path\to\your\cert.pfx -fd SHA256 -v .\name_of_the_appx.appx`

Key was the `-l` (or `/l`) option for makeappx.exe plus the generated `unplated` asset versions.

-----

That's quite a bunch of steps. I fear I have no time this year left to work on this :|
Guess I'll start with adding the props to the manifest.

**Comment by black-snow** [comment]
https://github.com/electron-userland/electron-builder/pull/1017 for the extra custom properties

**Comment by develar** [comment]
@black-snow Did you successfully submit appx to windows store?

**Comment by black-snow** [comment]
@develar yup. I'm still thinking of automating the assets workflow.

**Comment by baldash** [comment]
Hi, upping a 2 years old issue but, any easier way found to do this ? I'm struggling with the same error (blurry / margin in taskbar icon)

**Comment by black-snow** [comment]
@baldash sadly no - I haven't revisited this issue since then. But let me hear if you find anything new!

**Comment by baldash** [comment]
@black-snow your instructions were very helpful, I fixed my main problem thanks to them !

but I still have one last issue, even when tweaking the target-size and target-size_unplated values, my icon doesn't seem to change its size:

![taskbar-icon-problem-2](https://user-images.githubusercontent.com/20284898/68193191-edc6c880-ffb2-11e9-8244-eb87294e9b58.png)

Do eventually remember anything in relation to that ? That could be helpful ^^

(I followed everything except the VS part cause I already had my set of icons)

**Comment by baldash** [comment]
Okay fixed I'm just a bad person who doesn't read the doc properly. The issue was that for a resource named "SampleAppx.44x44.png", I created a `SampleAppx.targetsize-44_altform-unplated` AND a `SampleAppx.targetsize-44.png`.

So, two things here

1. The name is wrong -> for `SampleAppx.44x44.png` you should create a file named `SampleAppx.44x44.targetsize-44_altform-unplated.png`

2. You only need the `targetsize-44_altform-unplated.png` file and not the `targetsize-44.png` file

Ref link: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion
