### ISSUE TITLE
Application icon is corrupt after building

### ISSUE THREAD

**Issue by smithalan92** [electron-userland/electron-builder#991]
10.6.1

Windows Squirrel

The application icon for Windows builds is corrupt. The icon in the taskbar shows as below
![](https://s23.postimg.org/yw53ergaj/Capture.png)

Everything is correctly set in the build file ( `build.win.icon` ) . The Squirrel Installer icon is also missing, although the icon beside the Squirrel installer filename, and the main application executable filename do display correctly. 

The BrowserWindow icon is also set correctly, and running the app using the `electron` command from a terminal to launch the unpacked app from a folder, launches the app and the correct application icon is displayed in the taskbar.

After examining the folder of the installed app , it appears `C:\Users\Alan\AppData\Local\MyElectronApp\app.icon` is corrupt.

**Comment by adam-lynch** [comment]
Hmm no reply. @smithalan92 I guess we could create a hello world app that reproduces this to make it easier for @develar  (or whoever to fix)?

**Comment by develar** [comment]
@adam-lynch Hi :) If you use Squirrel.Windows, please try to use 10.9.2 (Squirrel.Windows upgraded to 1.5.1).

**Comment by loziobiz** [comment]
I just tested with the latest release.
Stubbed executables are now working but the icon on the taskbar is still missing.
Even the icon showed in the control panel/remove program is gone.

On windows7 are both correctly displayed

**Comment by smithalan92** [comment]
@develar I've just tested this with Electron Builder 10.9.2 , I can confirm the application icon is now showing in the taskbar and the control panel, the installer icon beside the file name is also appearing, however the Squirrel Installer taskbar icon is still missing. This is on Windows 10.

**Comment by develar** [comment]
@smithalan92 do you mean that the only issue now is that icon of installer in the taskbar during installation is not correct? If so, that as far I remember it was so always due to squirrel.windows bug.

**Comment by smithalan92** [comment]
@develar , thats right, this would be the icon when you run the Squirrel Installer.

![](https://camo.githubusercontent.com/0dee167f25251a28ac5a15f282df19b2ebf1b32f/68747470733a2f2f7332332e706f7374696d672e6f72672f79773533657267616a2f436170747572652e706e67)

You're actually right I think, I thought the installer taskbar icon was present in the previous version of electron-builder we were using (v6.0.0) but I double checked and it's missing there too!

**Comment by loziobiz** [comment]
Yes. Same here. The icon is blank when the app auto-runs for the first time after being installed, but when you manually run it from the shortcuts the icon is there.

**Comment by develar** [comment]
@smithalan92 no, Squirrel.Windows doesn't support it and in any case it leads to broken installer — https://github.com/electron/windows-installer/pull/68#issue-147831157

**Comment by smithalan92** [comment]
Ah very good @develar , Can this issue me closed so or should it be left open as a reference?

**Comment by develar** [comment]
> or should it be left open as a reference?

Someone should check — is it still an issue for recent rcedit (I guess — yes). I don't have time to check and don't want to introduce possible regressions for deprecated Squirrel.Windows.
