### ISSUE TITLE
libreadline.so.6 required but libreadline.so.7 is the current version, build fails

### ISSUE THREAD

**Issue by daikiuk** [electron-userland/electron-builder#993]
* **Version**: 6.7.7

* **Target**: --x64

Unhandled rejection Error: Exit code: 127. Command failed: /home/daniel/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/daniel/Dev/xt/curo/curo-electron/dist/Curo-0.1.0-x86_64.AppImage -padding 0 -map /home/daniel/Dev/xt/curo/curo-electron/dist/linux-unpacked /usr/bin -map /home/daniel/Dev/xt/curo/curo-electron/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-Na3OzB/0-2-Curo.desktop /curo.desktop -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_16x16x32.png /usr/share/icons/default/16x16/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_24x24x32.png /usr/share/icons/default/24x24/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_32x32x32.png /usr/share/icons/default/32x32/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_48x48x32.png /usr/share/icons/default/48x48/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_64x64x32.png /usr/share/icons/default/64x64/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_96x96x32.png /usr/share/icons/default/96x96/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_128x128x32.png /usr/share/icons/default/128x128/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_256x256x32.png /usr/share/icons/default/256x256/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_512x512x32.png /usr/share/icons/default/512x512/apps/Curo.png -map /tmp/electron-builder-Na3OzB/0-1-linux.iconset/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/daniel/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

/home/daniel/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

**Comment by develar** [comment]
Could you please try to install xorriso package?

**Comment by daikiuk** [comment]
I have installed https://www.archlinux.org/packages/extra/x86_64/libisoburn/ error remains. was able to solve it by sym link `sudo ln -s libreadline.so.7.0 libreadline.so.6`

**Comment by develar** [comment]
Workaround: 

```
sudo apt-get install -y xorriso
ln -sf /usr/bin/xorriso ~/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso
```

**Comment by develar** [comment]
Workaround: Install `xorriso` (`sudo apt-get install xorriso -y`) and set env `USE_SYSTEM_XORRISO=true` (10.13.1+)

**Comment by belltown** [comment]
As a workaround, this has been working for me without having to install anything else:

```
cd /lib/x86_64-linux-gnu
sudo ln -s libreadline.so.7.0 libreadline.so.6
```

**Comment by BaptN** [comment]
Encountered this issue with electron-builder 16.6.1, on an updated Arch x64.
Installing xorriso and having ENV set to use it did not change anything, but the symlink trick allowed me to build, so I'll go with it for now ...

**Comment by saveman71** [comment]
For what it's worth, installing the package and having the ENV variable set did the trick as of today for me on an updated Arch x64.
