### ISSUE TITLE
Allow to set the LSTypeIsPackage for file associations to true in the Info.plist

### ISSUE THREAD

**Issue by wuz23** [electron-userland/electron-builder#995]
* **Version**: 10.5.0

* **Target**: macOS

It would be helpful if I could set the LSTypeIsPackage flag to _true_ for a specific extention so that folders with this extention show up as packages within Finder. I hacked 2 lines into the mac.js file to fix this for me, but I think it would be helpful for others as well

**Comment by develar** [comment]
`isPackage` added, will be published soon.
