### ISSUE TITLE
Not installing for every user on Windows 7 machine

### ISSUE THREAD

**Issue by rjb8682** [electron-userland/electron-builder#999]
* **Version**: electron-builder@7.19.1

* **Target**: Windows and Mac. Issue is with Windows build

I am currently attempting to make a build of our app for windows and mac. We were told by our client that it only installed on that user's account for Windows 7, but we want it to install for their whole machine. I attempted to add the "nsis" flags to force perMachine, but it did not work. Here is the build portion of our package.json for the project: 

```
"build": {
    "appId": "com.bryx.ha",
    "categoy": "public.app-category.health",
    "nsis": {
      "oneClick": true,
      "perMachine": true
    },
    "dmg": {
      "contents": [
        {
          "x": 150,
          "y": 200
        },
        {
          "x": 380,
          "y": 200,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "iconUrl": "https://bryx.com/bryxha.ico",
      "publish": null
    },
    "linux": {
      "publish": null,
      "target": [
        "AppImage"
      ]
    }
  }
```

I'm fairly certain it is building for nsis, since the default green installer gif plays when running the .exe installer. When I run the installer, it installs to "c:/users/<username>/App Data/Local/..." on the current user, but does not add it to the other users on the same machine. 

If i'm doing something wrong in our build object, or if you have any advice of what to try next, that would be great!

Thanks!

**Comment by rainyday** [comment]
The animated gif installer is Squirrel. Nsis has a progress bar. You need to specify target: nsis in your json file if you want to build for nsis.

**Comment by develar** [comment]
> electron-builder@7.19.1

NSIS is the default target for Windows since 8. Please use latest version.
